Azerotcore-wotlk: npc_ulduar_vx001::npc_ulduar_vx001AI Struct Reference
npc_ulduar_vx001::npc_ulduar_vx001AI Struct Reference
Public Member Functions
npc_ulduar_vx001AI (Creature *pCreature)
void Reset () override
void AttackStart (Unit *) override
void SetData (uint32 id, uint32 value) override
uint32 GetData (uint32) const override
void DoAction (int32 action) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
void PassengerBoarded (Unit *p, int8, bool apply) override
== Fields =======================================
void SpellHit (Unit *, const SpellInfo *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsEvading
uint8 Phase
bool fighting
bool leftarm
uint32 spinningUpOrientation
uint16 spinningUpTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1278 of file boss_mimiron.cpp.
Constructor & Destructor Documentation
npc_ulduar_vx001AI()
npc_ulduar_vx001::npc_ulduar_vx001AI::npc_ulduar_vx001AI (Creature * pCreature) inline
Definition at line 1280 of file boss_mimiron.cpp.
                                                 : ScriptedAI(pCreature)
         {
             pInstance = me->GetInstanceScript();
             bIsEvading = false;
         }
References bIsEvading, WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_ulduar_vx001::npc_ulduar_vx001AI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1305 of file boss_mimiron.cpp.
 {}
DamageTaken()
void npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1369 of file boss_mimiron.cpp.
         {
             if (damage >= me->GetHealth() || me->GetHealth() < 15000)
             {
                 damage = 0;
                 if (me->GetReactState() == REACT_PASSIVE)
                     return;
                 me->SetReactState(REACT_PASSIVE);
                 if (Phase == 2)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         SetData(1, 0);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         me->SendMeleeAttackStop();
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_CUSTOM_SPELL_06);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_06);
                         if (Creature* c = GetMimiron())
                             c->AI()->SetData(0, 2);
                     }
                 }
                 else if (Phase == 4)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         me->CastSpell(me, SPELL_SELF_REPAIR, false);
                         if (Creature* c = GetMimiron())
{
                             if (c->AI()->GetData(1))
                                 me->CastSpell(me, SPELL_EMERGENCY_MODE, true);
                             if (c->AI()->GetData(2))
                                 me->CastSpell(me, SPELL_BERSERK, true);
                             c->AI()->SetData(0, 5);
                         }
                     }
                 }
             }
         }
References Unit::CastSpell(), EMOTE_ONESHOT_CUSTOM_SPELL_06, Unit::GetHealth(), GetMimiron, Creature::GetReactState(), Unit::HandleEmoteCommand(), Object::HasFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAllAurasExceptType(), Unit::SendMeleeAttackStop(), SetData(), Object::SetFlag(), Creature::SetReactState(), Object::SetUInt32Value(), SPELL_AURA_CONTROL_VEHICLE, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_SELF_REPAIR, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
DoAction()
void npc_ulduar_vx001::npc_ulduar_vx001AI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1359 of file boss_mimiron.cpp.
         {
             if (action == 1337)
                 if( Vehicle* vk = me->GetVehicleKit() )
                     for (uint8 i = 0; i < 2; ++i)
                         if (Unit* r = vk->GetPassenger(5 + i))
                             if (r->GetTypeId() == TYPEID_UNIT)
                                 r->ToCreature()->DespawnOrUnsummon(1);
         }
References Unit::GetVehicleKit(), ScriptedAI::me, and TYPEID_UNIT.
EnterEvadeMode()
void npc_ulduar_vx001::npc_ulduar_vx001AI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1577 of file boss_mimiron.cpp.
         {
             if (bIsEvading)
                 return;
             bIsEvading = true;
             me->RemoveAllAuras();
             me->ExitVehicle();
             _EnterEvadeMode();
             Reset();
             if (Creature* mimiron = GetMimiron())
                 mimiron->AI()->EnterEvadeMode();
             bIsEvading = false;
         }
References CreatureAI::_EnterEvadeMode(), bIsEvading, Unit::ExitVehicle(), GetMimiron, ScriptedAI::me, Unit::RemoveAllAuras(), and Reset().
GetData()
uint32 npc_ulduar_vx001::npc_ulduar_vx001AI::GetData (uint32) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1354 of file boss_mimiron.cpp.
         {
             return spinningUpOrientation;
         }
References spinningUpOrientation.
KilledUnit()
void npc_ulduar_vx001::npc_ulduar_vx001AI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1543 of file boss_mimiron.cpp.
         {
             if( who->GetTypeId() == TYPEID_PLAYER )
                 if( Creature* c = GetMimiron() )
                 {
                     if( Phase == 2 )
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_VX001_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_TORSO_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_VX001_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_TORSO_SLAY_2);
                         }
                     }
                     else
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_VOLTRON_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_VOLTRON_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_2);
                         }
                     }
                 }
         }
References GetMimiron, Object::GetTypeId(), LANG_UNIVERSAL, SOUND_TORSO_SLAY_1, SOUND_TORSO_SLAY_2, SOUND_VOLTRON_SLAY_1, SOUND_VOLTRON_SLAY_2, TEXT_VOLTRON_SLAIN_1, TEXT_VOLTRON_SLAIN_2, TEXT_VX001_SLAIN_1, TEXT_VX001_SLAIN_2, and TYPEID_PLAYER.
MoveInLineOfSight()
void npc_ulduar_vx001::npc_ulduar_vx001AI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1541 of file boss_mimiron.cpp.
 {}
PassengerBoarded()
void npc_ulduar_vx001::npc_ulduar_vx001AI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 1593 of file boss_mimiron.cpp.
         {
             if (p->GetEntry() == NPC_ROCKET_VISUAL && !apply)
                 p->ToCreature()->DespawnOrUnsummon(8000);
         }
References ByteConverter::apply(), Creature::DespawnOrUnsummon(), Object::GetEntry(), NPC_ROCKET_VISUAL, and Object::ToCreature().
Reset()
void npc_ulduar_vx001::npc_ulduar_vx001AI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1295 of file boss_mimiron.cpp.
         {
             Phase = 0;
             fighting = false;
             leftarm = false;
             spinningUpTimer = 0;
             me->SetRegeneratingHealth(false);
             events.Reset();
         }
References fighting, leftarm, ScriptedAI::me, Creature::SetRegeneratingHealth(), and spinningUpTimer.
Referenced by EnterEvadeMode().
SetData()
void npc_ulduar_vx001::npc_ulduar_vx001AI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 1307 of file boss_mimiron.cpp.
         {
             if (id == 1) // setting phase to start fighting
             {
                 switch (value)
                 {
                     case 0:
                         Phase = 0;
                         fighting = false;
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         events.Reset();
                         break;
                     case 2:
                         Phase = 2;
                         fighting = true;
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_SPELL_CAST_OMNI);
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_HEAT_WAVE, 10000);
                         events.ScheduleEvent(EVENT_SPELL_ROCKET_STRIKE, 16000);
                         events.ScheduleEvent(EVENT_SPELL_RAPID_BURST, 0);
                         events.ScheduleEvent(EVENT_SPELL_SPINNING_UP, 30000);
                         events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 3000);
                         if (Creature* c = GetMimiron())
                             if (c->AI()->GetData(1))
{
                                 events.ScheduleEvent(EVENT_FLAME_SUPPRESSION_10, 7000);
                                 events.ScheduleEvent(EVENT_FROST_BOMB, 1000);
                             }
                         break;
                     case 4:
                         Phase = 4;
                         fighting = true;
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         events.Reset();
                         events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 3000);
                         events.ScheduleEvent(EVENT_SPELL_ROCKET_STRIKE, 16000);
                         events.ScheduleEvent(EVENT_HAND_PULSE, 1);
                         events.ScheduleEvent(EVENT_SPELL_SPINNING_UP, 30000);
                         if (Creature* c = GetMimiron())
                             if (c->AI()->GetData(1))
                                 events.ScheduleEvent(EVENT_FROST_BOMB, 1000);
                         break;
                 }
             }
         }
References EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_SPELL_CAST_OMNI, EVENT_FLAME_SUPPRESSION_10, EVENT_FROST_BOMB, EVENT_HAND_PULSE, EVENT_REINSTALL_ROCKETS, EVENT_SPELL_HEAT_WAVE, EVENT_SPELL_RAPID_BURST, EVENT_SPELL_ROCKET_STRIKE, EVENT_SPELL_SPINNING_UP, fighting, GetMimiron, ScriptedAI::me, Object::RemoveFlag(), Object::SetUInt32Value(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
Referenced by DamageTaken().
SpellHit()
void npc_ulduar_vx001::npc_ulduar_vx001AI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1599 of file boss_mimiron.cpp.
         {
             if( spell->Id == SPELL_SELF_REPAIR )
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetReactState(), SPELL_SELF_REPAIR, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1413 of file boss_mimiron.cpp.
         {
             if (!fighting)
                 return;
             events.Update(diff);
             if (spinningUpTimer) // executed about a second after starting casting to ensure players can see the correct direction
             {
                 if (spinningUpTimer <= diff)
                 {
                     float angle = (spinningUpOrientation * 2 * M_PI) / 100.0f;
                     me->SetFacingTo(angle);
                     spinningUpTimer = 0;
                 }
                 else
                     spinningUpTimer -= diff;
             }
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_HEAT_WAVE:
                     me->CastSpell(me, SPELL_HEAT_WAVE, true);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_SPELL_ROCKET_STRIKE:
                     if( Vehicle* vk = me->GetVehicleKit() )
                     {
                         for( int i = 0; i < (Phase / 2); ++i )
{
                             uint8 index = (Phase == 2 ? rand() % 2 : i);
                             if( Unit* r = vk->GetPassenger(5 + index) )
                                 if (Player* temp = SelectTargetFromPlayerList(100.0f))
{
                                     if( Creature* trigger = me->SummonCreature(NPC_ROCKET_STRIKE_N, temp->GetPositionX(), temp->GetPositionY(), temp->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 6000) )
                                         trigger->CastSpell(trigger, SPELL_ROCKET_STRIKE_AURA, true);
                                     Position exitPos = r->GetPosition();
                                     exitPos.m_positionX += cos(me->GetOrientation()) * 2.35f;
                                     exitPos.m_positionY += sin(me->GetOrientation()) * 2.35f;
                                     exitPos.m_positionZ += 2.0f * Phase;
                                     r->_ExitVehicle(&exitPos);
                                     me->RemoveAurasByType(SPELL_AURA_CONTROL_VEHICLE, r->GetGUID());
                                     if (r->GetTypeId() == TYPEID_UNIT)
                                         r->ToCreature()->AI()->SetData(0, 0);
                                 }
                         }
                         events.RepeatEvent(20000);
                         events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 10000);
                     }
                     break;
                 case EVENT_REINSTALL_ROCKETS:
                     if (Vehicle* vk = me->GetVehicleKit())
                     {
                         for (uint8 i = 5; i <= 6; ++i)
                             if (!vk->GetPassenger(i))
                                 if (TempSummon* accessory = me->SummonCreature(NPC_ROCKET_VISUAL, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 4.0f, me->GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                                     if (!me->HandleSpellClick(accessory, i))
                                         accessory->UnSummon();
                     }
                     break;
                 case EVENT_SPELL_RAPID_BURST:
                     if (Player* p = SelectTargetFromPlayerList(80.0f))
                     {
                         me->CastSpell(p, SPELL_RAPID_BURST, true);
                         me->SetFacingToObject(p);
                     }
                     events.RepeatEvent(3200);
                     break;
                 case EVENT_HAND_PULSE:
                     if (Player* p = SelectTargetFromPlayerList(80.0f))
                     {
                         me->SetFacingToObject(p);
                         if (Unit* vb = me->GetVehicleBase())
{
                             vb->SendMeleeAttackStop();
                             vb->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                             if( !leftarm )
{
                                 vb->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_03);
                                 me->CastSpell(p, SPELL_HAND_PULSE_R, false);
                             }
                             else
{
                                 vb->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_04);
                                 me->CastSpell(p, SPELL_HAND_PULSE_L, false);
                             }
                         }
                         leftarm = !leftarm;
                     }
                     events.RepeatEvent(1750);
                     break;
                 case EVENT_SPELL_SPINNING_UP:
                     events.RepeatEvent(45000);
                     if (Player* p = SelectTargetFromPlayerList(80.0f))
                     {
                         float angle = me->GetAngle(p);
                         spinningUpOrientation = (uint32)((angle * 100.0f) / (2 * M_PI));
                         spinningUpTimer = 1500;
                         me->SetFacingTo(angle);
                         me->CastSpell(p, SPELL_SPINNING_UP, true);
                         if (Unit* vehicle = me->GetVehicleBase())
{
                             vehicle->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_CUSTOM_SPELL_01);
                             vehicle->HandleEmoteCommand(EMOTE_STATE_CUSTOM_SPELL_01);
                         }
                         events.RescheduleEvent((Phase == 2 ? EVENT_SPELL_RAPID_BURST : EVENT_HAND_PULSE), 14500);
                     }
                     break;
                 case EVENT_FLAME_SUPPRESSION_10:
                     me->CastSpell(me, SPELL_FLAME_SUPPRESSANT_10yd, false);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_FROST_BOMB:
                     me->CastCustomSpell(SPELL_VX001_FROST_BOMB, SPELLVALUE_MAX_TARGETS, 1, (Unit*)nullptr, false);
                     events.RepeatEvent(45000);
                     break;
             }
         }
References Unit::CastCustomSpell(), Unit::CastSpell(), EMOTE_ONESHOT_CUSTOM_SPELL_03, EMOTE_ONESHOT_CUSTOM_SPELL_04, EMOTE_ONESHOT_NONE, EMOTE_STATE_CUSTOM_SPELL_01, EVENT_FLAME_SUPPRESSION_10, EVENT_FROST_BOMB, EVENT_HAND_PULSE, EVENT_REINSTALL_ROCKETS, EVENT_SPELL_HEAT_WAVE, EVENT_SPELL_RAPID_BURST, EVENT_SPELL_ROCKET_STRIKE, EVENT_SPELL_SPINNING_UP, fighting, Position::GetAngle(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleBase(), Unit::GetVehicleKit(), Unit::HandleSpellClick(), Unit::HasUnitState(), leftarm, Position::m_positionX, Position::m_positionY, Position::m_positionZ, ScriptedAI::me, NPC_ROCKET_STRIKE_N, NPC_ROCKET_VISUAL, Phase, Unit::RemoveAurasByType(), ScriptedAI::SelectTargetFromPlayerList(), Unit::SetFacingTo(), Unit::SetFacingToObject(), SPELL_AURA_CONTROL_VEHICLE, SPELL_FLAME_SUPPRESSANT_10yd, SPELL_HAND_PULSE_L, SPELL_HAND_PULSE_R, SPELL_HEAT_WAVE, SPELL_RAPID_BURST, SPELL_ROCKET_STRIKE_AURA, SPELL_SPINNING_UP, SPELL_VX001_FROST_BOMB, SPELLVALUE_MAX_TARGETS, spinningUpOrientation, spinningUpTimer, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TYPEID_UNIT, UNIT_NPC_EMOTESTATE, and UNIT_STATE_CASTING.
Member Data Documentation
bIsEvading
bool npc_ulduar_vx001::npc_ulduar_vx001AI::bIsEvading
Definition at line 1288 of file boss_mimiron.cpp.
Referenced by EnterEvadeMode(), and npc_ulduar_vx001AI().
events
EventMap npc_ulduar_vx001::npc_ulduar_vx001AI::events
Definition at line 1287 of file boss_mimiron.cpp.
fighting
bool npc_ulduar_vx001::npc_ulduar_vx001AI::fighting
Definition at line 1290 of file boss_mimiron.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
leftarm
bool npc_ulduar_vx001::npc_ulduar_vx001AI::leftarm
Definition at line 1291 of file boss_mimiron.cpp.
Referenced by Reset(), and UpdateAI().
Phase
uint8 npc_ulduar_vx001::npc_ulduar_vx001AI::Phase
Definition at line 1289 of file boss_mimiron.cpp.
Referenced by UpdateAI().
pInstance
InstanceScript* npc_ulduar_vx001::npc_ulduar_vx001AI::pInstance
Definition at line 1286 of file boss_mimiron.cpp.
Referenced by npc_ulduar_vx001AI().
spinningUpOrientation
uint32 npc_ulduar_vx001::npc_ulduar_vx001AI::spinningUpOrientation
Definition at line 1292 of file boss_mimiron.cpp.
Referenced by GetData(), and UpdateAI().
spinningUpTimer
uint16 npc_ulduar_vx001::npc_ulduar_vx001AI::spinningUpTimer
Definition at line 1293 of file boss_mimiron.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp