Azerotcore-wotlk: SpellDestination Struct Reference
SpellDestination Struct Reference
#include <Spell.h>
Public Member Functions
SpellDestination ()
SpellDestination (float x, float y, float z, float orientation=0.0f, uint32 mapId=MAPID_INVALID)
SpellDestination (Position const &pos)
SpellDestination (WorldObject const &wObj)
void Relocate (Position const &pos)
void RelocateOffset (Position const &offset)
Public Attributes
WorldLocation _position
ObjectGuid _transportGUID
Position _transportOffset
Detailed Description
Definition at line 93 of file Spell.h.
Constructor & Destructor Documentation
SpellDestination() [1/4]
SpellDestination::SpellDestination ()
Definition at line 69 of file Spell.cpp.
 {
     _position.Relocate(0, 0, 0, 0);
     _transportOffset.Relocate(0, 0, 0, 0);
 }
References _position, _transportOffset, and Position::Relocate().
SpellDestination() [2/4]
SpellDestination::SpellDestination (float x, float y, float z, float orientation = 0.0f, uint32 mapId = MAPID_INVALID)
Definition at line 75 of file Spell.cpp.
 {
     _position.Relocate(x, y, z, orientation);
     _position.m_mapId = mapId;
     _transportOffset.Relocate(0, 0, 0, 0);
 }
References _position, _transportOffset, WorldLocation::m_mapId, Position::Relocate(), G3D::x, G3D::y, and G3D::z.
SpellDestination() [3/4]
SpellDestination::SpellDestination (Position const & pos)
Definition at line 82 of file Spell.cpp.
 {
     _position.Relocate(pos);
     _transportOffset.Relocate(0, 0, 0, 0);
 }
References _position, _transportOffset, pos(), and Position::Relocate().
SpellDestination() [4/4]
SpellDestination::SpellDestination (WorldObject const & wObj)
Definition at line 88 of file Spell.cpp.
 {
     _transportGUID = wObj.GetTransGUID();
     _transportOffset.Relocate(wObj.GetTransOffsetX(), wObj.GetTransOffsetY(), wObj.GetTransOffsetZ(), wObj.GetTransOffsetO());
     _position.Relocate(wObj);
 }
References _position, _transportGUID, _transportOffset, WorldObject::GetTransGUID(), WorldObject::GetTransOffsetO(), WorldObject::GetTransOffsetX(), WorldObject::GetTransOffsetY(), WorldObject::GetTransOffsetZ(), and Position::Relocate().
Member Function Documentation
Relocate()
void SpellDestination::Relocate (Position const & pos)
Definition at line 95 of file Spell.cpp.
 {
     if (_transportGUID)
     {
         Position offset;
         _position.GetPositionOffsetTo(pos, offset);
         _transportOffset.RelocateOffset(offset);
     }
     _position.Relocate(pos);
 }
References _position, _transportGUID, _transportOffset, Position::GetPositionOffsetTo(), pos(), Position::Relocate(), and Position::RelocateOffset().
Referenced by spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), SpellCastTargets::ModDst(), SpellCastTargets::ModSrc(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTargetDestTargets(), Spell::SelectImplicitTrajTargets(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::SetDest(), spell_q10898_skywing::spell_q10898_skywing_SpellScript::SetDest(), spell_item_dragon_kite_summon_lightning_bunny::SetDest(), and spell_item_recall::SetDest().
RelocateOffset()
void SpellDestination::RelocateOffset (Position const & offset)
Definition at line 106 of file Spell.cpp.
 {
     if (_transportGUID)
         _transportOffset.RelocateOffset(offset);
     _position.RelocateOffset(offset);
 }
References _position, _transportGUID, _transportOffset, and Position::RelocateOffset().
Referenced by spell_random_lightning_visual_effect::spell_random_lightning_visual_effect_SpellScript::ModDestHeight(), spell_kiljaeden_armageddon_missile::spell_kiljaeden_armageddon_missile_SpellScript::SetDest(), spell_oculus_call_ruby_emerald_amber_drake::spell_oculus_call_ruby_emerald_amber_drake_SpellScript::SetDest(), spell_shade_of_akama_akama_soul_expel::spell_shade_of_akama_akama_soul_expel_SpellScript::SetDest(), spell_q10930_big_bone_worm::spell_q10930_big_bone_worm_SpellScript::SetDest(), spell_q10929_fumping::spell_q10929_fumping_SpellScript::SetDest(), spell_q10923_evil_draws_near_visual::spell_q10923_evil_draws_near_visual_SpellScript::SetDest(), spell_q10898_skywing::spell_q10898_skywing_SpellScript::SetDest(), spell_item_dragon_kite_summon_lightning_bunny::SetDest(), spell_q12661_q12669_q12676_q12677_q12713_summon_stefan::SetDest(), and spell_q13291_q13292_q13239_q13261_armored_decoy_summon_skytalon::SetDest().
Member Data Documentation
_position
WorldLocation SpellDestination::_position
Definition at line 103 of file Spell.h.
Referenced by SpellCastTargets::GetDist2d(), SpellCastTargets::GetDstPos(), SpellCastTargets::GetSrcPos(), Spell::HandleEffects(), SpellCastTargets::HasDstChannel(), SpellCastTargets::OutDebug(), SpellCastTargets::Read(), Relocate(), RelocateOffset(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTargetDestTargets(), spell_prince_taldaram_flame_sphere_summon::spell_prince_taldaram_flame_sphere_summon_SpellScript::SetDest(), spell_azjol_nerub_impale_summon::spell_azjol_nerub_impale_summon_SpellScript::SetDest(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), SpellDestination(), SpellCastTargets::Update(), Spell::UpdatePointers(), and SpellCastTargets::Write().
_transportGUID
ObjectGuid SpellDestination::_transportGUID
Definition at line 104 of file Spell.h.
Referenced by SpellCastTargets::OutDebug(), SpellCastTargets::Read(), Relocate(), RelocateOffset(), SpellDestination(), SpellCastTargets::Update(), Spell::UpdatePointers(), and SpellCastTargets::Write().
_transportOffset
Position SpellDestination::_transportOffset
Definition at line 105 of file Spell.h.
Referenced by SpellCastTargets::OutDebug(), SpellCastTargets::Read(), Relocate(), RelocateOffset(), SpellDestination(), SpellCastTargets::Update(), Spell::UpdatePointers(), and SpellCastTargets::Write().
The documentation for this struct was generated from the following files:
src/server/game/Spells/Spell.h
src/server/game/Spells/Spell.cpp