Azerotcore-wotlk: CalendarEvent Struct Reference
CalendarEvent Struct Reference
#include <CalendarMgr.h>
Public Member Functions
CalendarEvent (CalendarEvent const &calendarEvent, uint64 eventId)
CalendarEvent (uint64 eventId, ObjectGuid creatorGUID, uint32 guildId, CalendarEventType type, int32 dungeonId, time_t eventTime, uint32 flags, time_t timezoneTime, std::string title, std::string description)
CalendarEvent ()
~CalendarEvent ()
void SetEventId (uint64 eventId)
uint64 GetEventId () const
void SetCreatorGUID (ObjectGuid guid)
ObjectGuid GetCreatorGUID () const
void SetGuildId (uint32 guildId)
uint32 GetGuildId () const
void SetTitle (const std::string &title)
std::string GetTitle () const
void SetDescription (const std::string &description)
std::string GetDescription () const
void SetType (CalendarEventType type)
CalendarEventType GetType () const
void SetDungeonId (int32 dungeonId)
int32 GetDungeonId () const
void SetEventTime (time_t eventTime)
time_t GetEventTime () const
void SetFlags (uint32 flags)
uint32 GetFlags () const
void SetTimeZoneTime (time_t timezoneTime)
time_t GetTimeZoneTime () const
bool IsGuildEvent () const
bool IsGuildAnnouncement () const
std::string BuildCalendarMailSubject (ObjectGuid remover) const
std::string BuildCalendarMailBody () const
Static Public Member Functions
static bool IsGuildEvent (uint32 flags)
static bool IsGuildAnnouncement (uint32 flags)
Private Attributes
uint64 _eventId
ObjectGuid _creatorGUID
uint32 _guildId
CalendarEventType _type
int32 _dungeonId
time_t _eventTime
uint32 _flags
time_t _timezoneTime
std::string _title
std::string _description
Detailed Description
Definition at line 195 of file CalendarMgr.h.
Constructor & Destructor Documentation
CalendarEvent() [1/3]
CalendarEvent::CalendarEvent (CalendarEvent const & calendarEvent, uint64 eventId) inline
Definition at line 198 of file CalendarMgr.h.
     {
         _eventId = eventId;
         _creatorGUID = calendarEvent.GetCreatorGUID();
         _guildId = calendarEvent.GetGuildId();
         _type = calendarEvent.GetType();
         _dungeonId = calendarEvent.GetDungeonId();
         _eventTime = calendarEvent.GetEventTime();
         _flags = calendarEvent.GetFlags();
         _timezoneTime = calendarEvent.GetTimeZoneTime();
         _title = calendarEvent.GetTitle();
         _description = calendarEvent.GetDescription();
     }
References _creatorGUID, _description, _dungeonId, _eventId, _eventTime, _flags, _guildId, _timezoneTime, _title, _type, GetCreatorGUID(), GetDescription(), GetDungeonId(), GetEventTime(), GetFlags(), GetGuildId(), GetTimeZoneTime(), GetTitle(), and GetType().
CalendarEvent() [2/3]
CalendarEvent::CalendarEvent (uint64 eventId, ObjectGuid creatorGUID, uint32 guildId, CalendarEventType type, int32 dungeonId, time_t eventTime, uint32 flags, time_t timezoneTime, std::string title, std::string description) inline
Definition at line 212 of file CalendarMgr.h.
                                                                                                                :
         _eventId(eventId), _creatorGUID(creatorGUID), _guildId(guildId), _type(type), _dungeonId(dungeonId),
         _eventTime(eventTime), _flags(flags), _timezoneTime(timezoneTime), _title(title),
         _description(description) { }
CalendarEvent() [3/3]
CalendarEvent::CalendarEvent () inline
Definition at line 218 of file CalendarMgr.h.
                     : _eventId(1), _guildId(0), _type(CALENDAR_TYPE_OTHER), _dungeonId(-1), _eventTime(0),
         _flags(0), _timezoneTime(0), _title(""), _description("") { }
~CalendarEvent()
CalendarEvent::~CalendarEvent ()
Definition at line 34 of file CalendarMgr.cpp.
 {
     sCalendarMgr->FreeEventId(_eventId);
 }
References _eventId, and sCalendarMgr.
Member Function Documentation
BuildCalendarMailBody()
std::string CalendarEvent::BuildCalendarMailBody () const
Definition at line 460 of file CalendarMgr.cpp.
 {
     WorldPacket data;
     uint32 time;
     std::ostringstream strm;
     // we are supposed to send PackedTime so i used WorldPacket to pack it
     data.AppendPackedTime(_eventTime);
     data >> time;
     strm << time;
     return strm.str();
 }
References _eventTime, and ByteBuffer::AppendPackedTime().
Referenced by CalendarMgr::RemoveEvent().
BuildCalendarMailSubject()
std::string CalendarEvent::BuildCalendarMailSubject (ObjectGuid remover) const
Definition at line 453 of file CalendarMgr.cpp.
 {
     std::ostringstream strm;
     strm << remover.ToString().c_str() << ':' << _title;
     return strm.str();
 }
References _title, and ObjectGuid::ToString().
Referenced by CalendarMgr::RemoveEvent().
GetCreatorGUID()
ObjectGuid CalendarEvent::GetCreatorGUID () const inline
Definition at line 227 of file CalendarMgr.h.
 { return _creatorGUID; }
References _creatorGUID.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::AddInvite(), CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::UpdateEvent().
GetDescription()
std::string CalendarEvent::GetDescription () const inline
Definition at line 236 of file CalendarMgr.h.
 { return _description; }
References _description.
Referenced by CalendarEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
GetDungeonId()
int32 CalendarEvent::GetDungeonId () const inline
Definition at line 242 of file CalendarMgr.h.
 { return _dungeonId; }
References _dungeonId.
Referenced by CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
GetEventId()
uint64 CalendarEvent::GetEventId () const inline
Definition at line 224 of file CalendarMgr.h.
 { return _eventId; }
References _eventId.
Referenced by WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::RemoveEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventRemovedAlert(), CalendarMgr::SendCalendarEventStatus(), CalendarMgr::SendCalendarEventUpdateAlert(), CalendarMgr::SendPacketToAllEventRelatives(), and CalendarMgr::UpdateEvent().
GetEventTime()
time_t CalendarEvent::GetEventTime () const inline
Definition at line 245 of file CalendarMgr.h.
 { return _eventTime; }
References _eventTime.
Referenced by CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventRemovedAlert(), CalendarMgr::SendCalendarEventStatus(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
GetFlags()
uint32 CalendarEvent::GetFlags () const inline
Definition at line 248 of file CalendarMgr.h.
 { return _flags; }
References _flags.
Referenced by CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::RemoveInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventStatus(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
GetGuildId()
uint32 CalendarEvent::GetGuildId () const inline
Definition at line 230 of file CalendarMgr.h.
 { return _guildId; }
References _guildId.
Referenced by CalendarEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::SendPacketToAllEventRelatives().
GetTimeZoneTime()
time_t CalendarEvent::GetTimeZoneTime () const inline
Definition at line 251 of file CalendarMgr.h.
 { return _timezoneTime; }
References _timezoneTime.
Referenced by CalendarEvent(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::UpdateEvent().
GetTitle()
std::string CalendarEvent::GetTitle () const inline
Definition at line 233 of file CalendarMgr.h.
 { return _title; }
References _title.
Referenced by CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
GetType()
CalendarEventType CalendarEvent::GetType () const inline
Definition at line 239 of file CalendarMgr.h.
 { return _type; }
References _type.
Referenced by CalendarEvent(), WorldSession::HandleCalendarGetCalendar(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventUpdateAlert(), and CalendarMgr::UpdateEvent().
IsGuildAnnouncement() [1/2]
bool CalendarEvent::IsGuildAnnouncement () const inline
Definition at line 254 of file CalendarMgr.h.
 { return _flags & CALENDAR_FLAG_WITHOUT_INVITES; }
References _flags, and CALENDAR_FLAG_WITHOUT_INVITES.
Referenced by CalendarMgr::AddInvite(), WorldSession::HandleCalendarAddEvent(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::SendPacketToAllEventRelatives().
IsGuildAnnouncement() [2/2]
static bool CalendarEvent::IsGuildAnnouncement (uint32 flags) inline static
Definition at line 257 of file CalendarMgr.h.
 { return (flags & CALENDAR_FLAG_WITHOUT_INVITES) != 0; }
References CALENDAR_FLAG_WITHOUT_INVITES.
IsGuildEvent() [1/2]
bool CalendarEvent::IsGuildEvent () const inline
Definition at line 253 of file CalendarMgr.h.
 { return _flags & CALENDAR_FLAG_GUILD_EVENT; }
References _flags, and CALENDAR_FLAG_GUILD_EVENT.
Referenced by CalendarMgr::AddInvite(), WorldSession::HandleCalendarAddEvent(), CalendarMgr::RemoveInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::SendPacketToAllEventRelatives().
IsGuildEvent() [2/2]
static bool CalendarEvent::IsGuildEvent (uint32 flags) inline static
Definition at line 256 of file CalendarMgr.h.
 { return (flags & CALENDAR_FLAG_GUILD_EVENT) != 0; }
References CALENDAR_FLAG_GUILD_EVENT.
SetCreatorGUID()
void CalendarEvent::SetCreatorGUID (ObjectGuid guid) inline
Definition at line 226 of file CalendarMgr.h.
 { _creatorGUID = guid; }
References _creatorGUID.
SetDescription()
void CalendarEvent::SetDescription (const std::string & description) inline
Definition at line 235 of file CalendarMgr.h.
 { _description = description; }
References _description.
SetDungeonId()
void CalendarEvent::SetDungeonId (int32 dungeonId) inline
Definition at line 241 of file CalendarMgr.h.
 { _dungeonId = dungeonId; }
References _dungeonId.
SetEventId()
void CalendarEvent::SetEventId (uint64 eventId) inline
Definition at line 223 of file CalendarMgr.h.
 { _eventId = eventId; }
References _eventId.
SetEventTime()
void CalendarEvent::SetEventTime (time_t eventTime) inline
Definition at line 244 of file CalendarMgr.h.
 { _eventTime = eventTime; }
References _eventTime.
Referenced by WorldSession::HandleCalendarCopyEvent().
SetFlags()
void CalendarEvent::SetFlags (uint32 flags) inline
Definition at line 247 of file CalendarMgr.h.
 { _flags = flags; }
References _flags.
SetGuildId()
void CalendarEvent::SetGuildId (uint32 guildId) inline
Definition at line 229 of file CalendarMgr.h.
 { _guildId = guildId; }
References _guildId.
Referenced by WorldSession::HandleCalendarAddEvent().
SetTimeZoneTime()
void CalendarEvent::SetTimeZoneTime (time_t timezoneTime) inline
Definition at line 250 of file CalendarMgr.h.
 { _timezoneTime = timezoneTime; }
References _timezoneTime.
SetTitle()
void CalendarEvent::SetTitle (const std::string & title) inline
Definition at line 232 of file CalendarMgr.h.
 { _title = title; }
References _title.
SetType()
void CalendarEvent::SetType (CalendarEventType type) inline
Definition at line 238 of file CalendarMgr.h.
 { _type = type; }
References _type.
Member Data Documentation
_creatorGUID
ObjectGuid CalendarEvent::_creatorGUID private
Definition at line 264 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetCreatorGUID(), and SetCreatorGUID().
_description
std::string CalendarEvent::_description private
Definition at line 272 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetDescription(), and SetDescription().
_dungeonId
int32 CalendarEvent::_dungeonId private
Definition at line 267 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetDungeonId(), and SetDungeonId().
_eventId
uint64 CalendarEvent::_eventId private
Definition at line 263 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetEventId(), SetEventId(), and ~CalendarEvent().
_eventTime
time_t CalendarEvent::_eventTime private
Definition at line 268 of file CalendarMgr.h.
Referenced by BuildCalendarMailBody(), CalendarEvent(), GetEventTime(), and SetEventTime().
_flags
uint32 CalendarEvent::_flags private
Definition at line 269 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetFlags(), IsGuildAnnouncement(), IsGuildEvent(), and SetFlags().
_guildId
uint32 CalendarEvent::_guildId private
Definition at line 265 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetGuildId(), and SetGuildId().
_timezoneTime
time_t CalendarEvent::_timezoneTime private
Definition at line 270 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetTimeZoneTime(), and SetTimeZoneTime().
_title
std::string CalendarEvent::_title private
Definition at line 271 of file CalendarMgr.h.
Referenced by BuildCalendarMailSubject(), CalendarEvent(), GetTitle(), and SetTitle().
_type
CalendarEventType CalendarEvent::_type private
Definition at line 266 of file CalendarMgr.h.
Referenced by CalendarEvent(), GetType(), and SetType().
The documentation for this struct was generated from the following files:
src/server/game/Calendar/CalendarMgr.h
src/server/game/Calendar/CalendarMgr.cpp