Azerotcore-wotlk: MapUpdateRequest Class Reference
MapUpdateRequest Class Reference
Public Member Functions
MapUpdateRequest (Map &m, MapUpdater &u, uint32 d, uint32 sd)
void call () override
Public Member Functions inherited from UpdateRequest
UpdateRequest ()=default
virtual ~UpdateRequest ()=default
Private Attributes
Map & m_map
MapUpdater & m_updater
uint32 m_diff
uint32 s_diff
Detailed Description
Definition at line 33 of file MapUpdater.cpp.
Constructor & Destructor Documentation
MapUpdateRequest()
MapUpdateRequest::MapUpdateRequest (Map & m, MapUpdater & u, uint32 d, uint32 sd) inline
Definition at line 36 of file MapUpdater.cpp.
         : m_map(m), m_updater(u), m_diff(d), s_diff(sd)
     {
     }
Member Function Documentation
call()
void MapUpdateRequest::call () inline override virtual
Implements UpdateRequest.
Definition at line 41 of file MapUpdater.cpp.
     {
         METRIC_TIMER("map_update_time_diff", METRIC_TAG("map_id", std::to_string(m_map.GetId())));
         m_map.Update(m_diff, s_diff);
         m_updater.update_finished();
     }
References Map::GetId(), m_diff, m_map, m_updater, METRIC_TAG, METRIC_TIMER, s_diff, Map::Update(), and MapUpdater::update_finished().
Member Data Documentation
m_diff
uint32 MapUpdateRequest::m_diff private
Definition at line 51 of file MapUpdater.cpp.
Referenced by call().
m_map
Map& MapUpdateRequest::m_map private
Definition at line 49 of file MapUpdater.cpp.
Referenced by call().
m_updater
MapUpdater& MapUpdateRequest::m_updater private
Definition at line 50 of file MapUpdater.cpp.
Referenced by call().
s_diff
uint32 MapUpdateRequest::s_diff private
Definition at line 52 of file MapUpdater.cpp.
Referenced by call().
The documentation for this class was generated from the following file:
src/server/game/Maps/MapUpdater.cpp