Azerotcore-wotlk: NecroticPlagueTargetCheck Class Reference
NecroticPlagueTargetCheck Class Reference
Public Member Functions
NecroticPlagueTargetCheck (Unit const *obj, uint32 notAura1, uint32 notAura2)
bool operator() (Unit *unit) const
Private Attributes
Unit const * _sourceObj
uint32 _notAura1
uint32 _notAura2
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 590 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
NecroticPlagueTargetCheck()
NecroticPlagueTargetCheck::NecroticPlagueTargetCheck (Unit const * obj, uint32 notAura1, uint32 notAura2) inline
Definition at line 593 of file boss_the_lich_king.cpp.
 : _sourceObj(obj), _notAura1(notAura1), _notAura2(notAura2) {}
Member Function Documentation
operator()()
bool NecroticPlagueTargetCheck::operator() (Unit * unit) const inline
Definition at line 595 of file boss_the_lich_king.cpp.
     {
         if (!unit || unit->GetTypeId() != TYPEID_PLAYER || unit == _sourceObj || _sourceObj->GetVictim() == unit || !unit->isTargetableForAttack())
             return false;
         if (unit->HasAura(SPELL_PLAGUE_AVOIDANCE) || unit->HasAura(SPELL_BOSS_HITTIN_YA_AURA) || unit->HasAura(_notAura1) || unit->HasAura(_notAura2))
             return false;
         if (!_sourceObj->IsWithinLOSInMap(unit))
             return false;
         return true;
     }
References _notAura1, _notAura2, _sourceObj, Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), Unit::isTargetableForAttack(), WorldObject::IsWithinLOSInMap(), SPELL_BOSS_HITTIN_YA_AURA, SPELL_PLAGUE_AVOIDANCE, and TYPEID_PLAYER.
Member Data Documentation
_notAura1
uint32 NecroticPlagueTargetCheck::_notAura1 private
Definition at line 608 of file boss_the_lich_king.cpp.
Referenced by operator()().
_notAura2
uint32 NecroticPlagueTargetCheck::_notAura2 private
Definition at line 609 of file boss_the_lich_king.cpp.
Referenced by operator()().
_sourceObj
Unit const* NecroticPlagueTargetCheck::_sourceObj private
Definition at line 607 of file boss_the_lich_king.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp