Azerotcore-wotlk: DynamicTreeIntersectionCallback Struct Reference
DynamicTreeIntersectionCallback Struct Reference
Public Member Functions
DynamicTreeIntersectionCallback (uint32 phasemask)
bool operator() (const G3D::Ray &r, const GameObjectModel &obj, float &distance, bool stopAtFirstHit)
bool didHit () const
Public Attributes
bool did_hit
uint32 phase_mask
Detailed Description
Definition at line 147 of file DynamicTree.cpp.
Constructor & Destructor Documentation
DynamicTreeIntersectionCallback()
DynamicTreeIntersectionCallback::DynamicTreeIntersectionCallback (uint32 phasemask) inline
Definition at line 151 of file DynamicTree.cpp.
 : did_hit(false), phase_mask(phasemask) { }
Member Function Documentation
didHit()
bool DynamicTreeIntersectionCallback::didHit () const inline
Definition at line 161 of file DynamicTree.cpp.
 { return did_hit;}
References did_hit.
Referenced by DynamicMapTree::getHeight(), and DynamicMapTree::GetIntersectionTime().
operator()()
bool DynamicTreeIntersectionCallback::operator() (const G3D::Ray & r, const GameObjectModel & obj, float & distance, bool stopAtFirstHit) inline
Definition at line 152 of file DynamicTree.cpp.
     {
         bool result = obj.intersectRay(r, distance, stopAtFirstHit, phase_mask);
         if (result)
         {
             did_hit = result;
         }
         return result;
     }
References did_hit, G3D::distance(), GameObjectModel::intersectRay(), and phase_mask.
Member Data Documentation
did_hit
bool DynamicTreeIntersectionCallback::did_hit
Definition at line 149 of file DynamicTree.cpp.
Referenced by didHit(), DynamicMapTree::isInLineOfSight(), and operator()().
phase_mask
uint32 DynamicTreeIntersectionCallback::phase_mask
Definition at line 150 of file DynamicTree.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/common/Collision/DynamicTree.cpp