Azerotcore-wotlk: deps/mysqllite/libmysql/get_password.c File Reference
get_password.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include "mysql.h"
#include <m_string.h>
#include <m_ctype.h>
#include <sys/ioctl.h>
#include <sgtty.h>
Macros
#define TERMIO struct sgttyb
Functions
static void get_password (char *to, uint length, int fd, my_bool echo)
char * get_tty_password (const char *opt_message)
Macro Definition Documentation
TERMIO
#define TERMIO struct sgttyb
Definition at line 49 of file get_password.c.
Function Documentation
get_password()
static void get_password (char * to, uint length, int fd, my_bool echo) static
Definition at line 110 of file get_password.c.
 {
   char *pos=to,*end=to+length;
   for (;;)
   {
     char tmp;
     if (my_read(fd,&tmp,1,MYF(0)) != 1)
       break;
     if (tmp == '\b' || (int) tmp == 127)
     {
       if (pos != to)
       {
     if (echo)
     {
       fputs("\b \b",stdout);
       fflush(stdout);
     }
     pos--;
     continue;
       }
     }
     if (tmp == '\n' || tmp == '\r' || tmp == 3)
       break;
     if (iscntrl(tmp) || pos == end)
       continue;
     if (echo)
     {
       fputc('*',stdout);
       fflush(stdout);
     }
     *(pos++) = tmp;
   }
   while (pos != to && isspace(pos[-1]) == ' ')
     pos--;                  /* Allow dummy space at end */
   *pos=0;
   return;
 }
References fputs(), G3D::length(), my_read, MYF, and pos().
Referenced by get_tty_password().
get_tty_password()
char* get_tty_password (const char * opt_message)
Definition at line 151 of file get_password.c.
 {
 #ifdef HAVE_GETPASS
   char *passbuff;
 #else /* ! HAVE_GETPASS */
   TERMIO org,tmp;
 #endif /* HAVE_GETPASS */
   char buff[80];
   DBUG_ENTER("get_tty_password");
 #ifdef HAVE_GETPASS
   passbuff = getpass(opt_message ? opt_message : "Enter password: ");
   /* copy the password to buff and clear original (static) buffer */
   strnmov(buff, passbuff, sizeof(buff) - 1);
 #ifdef _PASSWORD_LEN
   memset(passbuff, 0, _PASSWORD_LEN);
 #endif
 #else
   if (isatty(fileno(stdout)))
   {
     fputs(opt_message ? opt_message : "Enter password: ",stdout);
     fflush(stdout);
   }
 #if defined(HAVE_TERMIOS_H)
   tcgetattr(fileno(stdin), &org);
   tmp = org;
   tmp.c_lflag &= ~(ECHO | ISIG | ICANON);
   tmp.c_cc[VMIN] = 1;
   tmp.c_cc[VTIME] = 0;
   tcsetattr(fileno(stdin), TCSADRAIN, &tmp);
   get_password(buff, sizeof(buff)-1, fileno(stdin), isatty(fileno(stdout)));
   tcsetattr(fileno(stdin), TCSADRAIN, &org);
 #elif defined(HAVE_TERMIO_H)
   ioctl(fileno(stdin), (int) TCGETA, &org);
   tmp=org;
   tmp.c_lflag &= ~(ECHO | ISIG | ICANON);
   tmp.c_cc[VMIN] = 1;
   tmp.c_cc[VTIME]= 0;
   ioctl(fileno(stdin),(int) TCSETA, &tmp);
   get_password(buff,sizeof(buff)-1,fileno(stdin),isatty(fileno(stdout)));
   ioctl(fileno(stdin),(int) TCSETA, &org);
 #else
   gtty(fileno(stdin), &org);
   tmp=org;
   tmp.sg_flags &= ~ECHO;
   tmp.sg_flags |= RAW;
   stty(fileno(stdin), &tmp);
   get_password(buff,sizeof(buff)-1,fileno(stdin),isatty(fileno(stdout)));
   stty(fileno(stdin), &org);
 #endif
   if (isatty(fileno(stdout)))
     fputc('\n',stdout);
 #endif /* HAVE_GETPASS */
   DBUG_RETURN(my_strdup(buff,MYF(MY_FAE)));
 }
References DBUG_ENTER, DBUG_RETURN, fputs(), get_password(), memset, MY_FAE, my_strdup(), MYF, strnmov(), and TERMIO.