Azerotcore-wotlk: G3D::AreaMemoryManager Class Reference
G3D::AreaMemoryManager Class Reference
Allocates memory in large blocks and then frees it as an area.
#include <AreaMemoryManager.h>
Classes
class Buffer
Public Types
typedef shared_ptr< AreaMemoryManager > Ref
Public Types inherited from G3D::MemoryManager
typedef shared_ptr< class MemoryManager > Ref
Public Member Functions
~AreaMemoryManager ()
size_t bytesAllocated () const
virtual void * alloc (size_t s)
virtual void free (void *x)
virtual bool isThreadsafe () const
void deallocateAll ()
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static AreaMemoryManager::Ref create (size_t sizeHint=10 *1024 *1024)
Static Public Member Functions inherited from G3D::MemoryManager
static MemoryManager::Ref create ()
Private Member Functions
AreaMemoryManager (size_t sizeHint)
Private Attributes
size_t m_sizeHint
Array< Buffer * > m_bufferArray
Additional Inherited Members
Protected Member Functions inherited from G3D::MemoryManager
MemoryManager ()
Detailed Description
Allocates memory in large blocks and then frees it as an area.
Useful for ensuring cache coherence and for reducing the time cost of multiple allocations and deallocations.
Not threadsafe
Definition at line 32 of file AreaMemoryManager.h.
Member Typedef Documentation
Ref
typedef shared_ptr<AreaMemoryManager> G3D::AreaMemoryManager::Ref
Definition at line 60 of file AreaMemoryManager.h.
Constructor & Destructor Documentation
AreaMemoryManager()
G3D::AreaMemoryManager::AreaMemoryManager (size_t sizeHint) private
Definition at line 50 of file AreaMemoryManager.cpp.
                                                     : m_sizeHint(sizeHint) {
     debugAssert(sizeHint > 0);
 }
References debugAssert.
Referenced by create().
~AreaMemoryManager()
G3D::AreaMemoryManager::~AreaMemoryManager ()
Invokes deallocateAll.
Definition at line 55 of file AreaMemoryManager.cpp.
{
     deallocateAll();
 }
References deallocateAll().
Member Function Documentation
alloc()
void * G3D::AreaMemoryManager::alloc (size_t s) virtual
Allocates memory out of the buffer pool.
Parameters
s must be no larger than sizeHint
Reimplemented from G3D::MemoryManager.
Definition at line 65 of file AreaMemoryManager.cpp.
{
     void* n = (m_bufferArray.size() > 0) ? m_bufferArray.last()->alloc(s) : NULL;
     if (n == NULL) {
         // This buffer is full
         m_bufferArray.append(new Buffer(max(s, m_sizeHint)));
         return m_bufferArray.last()->alloc(s);
     } else {
         return n;
     }
 }
References m_bufferArray, m_sizeHint, G3D::max(), and NULL.
bytesAllocated()
size_t G3D::AreaMemoryManager::bytesAllocated () const
Definition at line 60 of file AreaMemoryManager.cpp.
{
     return m_sizeHint * m_bufferArray.size();
 }
References m_bufferArray, and m_sizeHint.
create()
AreaMemoryManager::Ref G3D::AreaMemoryManager::create (size_t sizeHint = 10 * 1024 * 1024) static
Parameters
sizeHint Total amount of memory expected to be allocated. The allocator will allocate memory from the system in increments of this size.
Definition at line 45 of file AreaMemoryManager.cpp.
{
     return shared_ptr<AreaMemoryManager>(new AreaMemoryManager(sizeHint));
 }
References AreaMemoryManager().
deallocateAll()
void G3D::AreaMemoryManager::deallocateAll ()
Deletes all previously allocated memory. Because delete is not invoked on objects in this memory, it is not safe to simply free memory containing C++ objects that expect their destructors to be called.
Definition at line 82 of file AreaMemoryManager.cpp.
{
     m_bufferArray.invokeDeleteOnAllElements();
     m_bufferArray.clear();
 }
References m_bufferArray.
Referenced by ~AreaMemoryManager().
free()
void G3D::AreaMemoryManager::free (void * x) virtual
Ignored.
Reimplemented from G3D::MemoryManager.
Definition at line 77 of file AreaMemoryManager.cpp.
{
     // Intentionally empty; we block deallocate
 }
Referenced by G3D::AreaMemoryManager::Buffer::~Buffer().
isThreadsafe()
bool G3D::AreaMemoryManager::isThreadsafe () const virtual
Returns true if this memory manager is threadsafe (i.e., alloc and free can be called asychronously)
Reimplemented from G3D::MemoryManager.
Definition at line 40 of file AreaMemoryManager.cpp.
{
     return false;
 }
Member Data Documentation
m_bufferArray
Array<Buffer*> G3D::AreaMemoryManager::m_bufferArray private
The underlying array is stored in regular MemoryManager heap memory
Definition at line 54 of file AreaMemoryManager.h.
Referenced by alloc(), bytesAllocated(), and deallocateAll().
m_sizeHint
size_t G3D::AreaMemoryManager::m_sizeHint private
Definition at line 51 of file AreaMemoryManager.h.
Referenced by alloc(), and bytesAllocated().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/AreaMemoryManager.h
deps/g3dlite/source/AreaMemoryManager.cpp