Azerotcore-wotlk: G3D::Image3 Class Reference
G3D::Image3 Class Reference
#include <Image3.h>
Public Types
typedef Image3 Type
typedef shared_ptr< class Image3 > Ref
Public Types inherited from G3D::Map2D< Color3, Color3 >
typedef Color3 StorageType
typedef Color3 ComputeType
typedef Map2D< Color3, Color3 > Type
typedef shared_ptr< Map2D > Ref
Public Member Functions
const class ImageFormat * format () const
void load (const std::string &filename)
void save (const std::string &filename)
Public Member Functions inherited from G3D::Map2D< Color3, Color3 >
const Color3 & fastGet (int x, int y) const
void fastSet (int x, int y, const Color3 &v)
Color3 bicubic (float x, float y, WrapMode wrap) const
Color3 bicubic (float x, float y) const
Color3 bicubic (const Vector2 &p, WrapMode wrap) const
Color3 bicubic (const Vector2 &p) const
void resize (uint32 newW, uint32 newH)
bool changed ()
void setChanged (bool c)
Color3 * getCArray ()
const Color3 * getCArray () const
Array< Color3 > & getArray ()
const Array< Color3 > & getArray () const
bool inBounds (int x, int y) const
bool inBounds (const Vector2int16 &v) const
const Color3 & get (int x, int y, WrapMode wrap) const
const Color3 & get (int x, int y) const
const Color3 & get (const Vector2int16 &p) const
const Color3 & get (const Vector2int16 &p, WrapMode wrap) const
Color3 & get (int x, int y, WrapMode wrap)
Color3 & get (int x, int y)
Color3 & get (const Vector2int16 &p)
void set (const Vector2int16 &p, const Color3 &v)
void set (int x, int y, const Color3 &v, WrapMode wrap)
void set (int x, int y, const Color3 &v)
void set (const shared_ptr< Map2D< Color3, T > > &src)
void setAll (const Color3 &v)
void maybeFlipVertical (bool flip)
virtual void flipVertical ()
virtual void flipHorizontal ()
virtual void crop (int newX, int newY, int newW, int newH)
virtual void crop (const Rect2D &rect)
Color3 nearest (float x, float y, WrapMode wrap) const
Color3 nearest (float x, float y) const
Color3 nearest (const Vector2 &p) const
Color3 average () const
Color3 bilinear (float x, float y, WrapMode wrap) const
Color3 bilinear (float x, float y) const
Color3 bilinear (const Vector2 &p) const
Color3 bilinear (const Vector2 &p, WrapMode wrap) const
int32 width () const
int32 height () const
Vector2int16 size () const
Rect2D rect2DBounds () const
size_t sizeInMemory () const
WrapMode wrapMode () const
void setWrapMode (WrapMode m)
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static Ref createEmpty (int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref createEmpty (WrapMode wrap=WrapMode::ERROR)
static Ref fromFile (const std::string &filename, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromImage3unorm8 (const shared_ptr< class Image3unorm8 > &im)
Static Public Member Functions inherited from G3D::Map2D< Color3, Color3 >
static Ref create (int w=0, int h=0, WrapMode wrap=WrapMode::ERROR)
Protected Member Functions
Image3 (int w, int h, WrapMode wrap)
void copyArray (const Color1 *src, int w, int h)
void copyArray (const Color3 *src, int w, int h)
void copyArray (const Color4 *src, int w, int h)
void copyArray (const Color1unorm8 *src, int w, int h)
void copyArray (const Color3unorm8 *src, int w, int h)
void copyArray (const Color4unorm8 *src, int w, int h)
Protected Member Functions inherited from G3D::Map2D< Color3, Color3 >
const Color3 & slowGet (int x, int y, WrapMode wrap)
Color3 bicubic (const Color3 *ctrl, double s) const
Map2D (int w, int h, WrapMode wrap)
Additional Inherited Members
Public Attributes inherited from G3D::Map2D< Color3, Color3 >
GMutex mutex
Protected Attributes inherited from G3D::Map2D< Color3, Color3 >
Color3 ZERO
uint32 w
uint32 h
WrapMode _wrapMode
AtomicInt32 m_changed
Array< Color3 > data
Detailed Description
RGB image with 32-bit floating point storage for each channel.
See also G3D::Image3unorm8, G3D::GImage.
Definition at line 27 of file Image3.h.
Member Typedef Documentation
Ref
typedef shared_ptr<class Image3> G3D::Image3::Ref
Definition at line 31 of file Image3.h.
Type
typedef Image3 G3D::Image3::Type
Definition at line 30 of file Image3.h.
Constructor & Destructor Documentation
Image3()
G3D::Image3::Image3 (int w, int h, WrapMode wrap) protected
Definition at line 24 of file Image3.cpp.
                                           : Map2D<Color3, Color3>(w, h, wrap) {
     setAll(Color3::black());
 }
References G3D::Color3::black(), and G3D::Map2D< Color3, Color3 >::setAll().
Referenced by createEmpty().
Member Function Documentation
copyArray() [1/6]
void G3D::Image3::copyArray (const Color1 * src, int w, int h) protected
Definition at line 192 of file Image3.cpp.
{
     resize(w, h);
     int N = w * h;
     Color3* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i].r = dst[i].g = dst[i].b = src[i].value;
     }
 }
References G3D::Color3::b, G3D::Color3::g, G3D::Map2D< Color3, Color3 >::getCArray(), G3D::Map2D< Color3, Color3 >::h, G3D::Color3::r, G3D::Map2D< Color3, Color3 >::resize(), G3D::Color1::value, and G3D::Map2D< Color3, Color3 >::w.
Referenced by load().
copyArray() [2/6]
void G3D::Image3::copyArray (const Color1unorm8 * src, int w, int h) protected
Definition at line 181 of file Image3.cpp.
{
     resize(w, h);
     int N = w * h;
     Color3* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i].r = dst[i].g = dst[i].b = Color1(src[i]).value;
     }
 }
References G3D::Color3::b, G3D::Color3::g, G3D::Map2D< Color3, Color3 >::getCArray(), G3D::Map2D< Color3, Color3 >::h, G3D::Color3::r, G3D::Map2D< Color3, Color3 >::resize(), G3D::Color1::value, and G3D::Map2D< Color3, Color3 >::w.
copyArray() [3/6]
void G3D::Image3::copyArray (const Color3 * src, int w, int h) protected
Definition at line 162 of file Image3.cpp.
{
     resize(w, h);
     System::memcpy(getCArray(), src, w * h * sizeof(Color3));
 }
References G3D::Map2D< Color3, Color3 >::getCArray(), G3D::Map2D< Color3, Color3 >::h, G3D::System::memcpy(), G3D::Map2D< Color3, Color3 >::resize(), and G3D::Map2D< Color3, Color3 >::w.
copyArray() [4/6]
void G3D::Image3::copyArray (const Color3unorm8 * src, int w, int h) protected
Definition at line 137 of file Image3.cpp.
{
     resize(w, h);
     int N = w * h;
     Color3* dst = data.getCArray();
     // Convert int8 -> float
     for (int i = 0; i < N; ++i) {
         dst[i] = Color3(src[i]);
     }
 }
References G3D::Map2D< Color3, Color3 >::h, G3D::Map2D< Color3, Color3 >::resize(), and G3D::Map2D< Color3, Color3 >::w.
copyArray() [5/6]
void G3D::Image3::copyArray (const Color4 * src, int w, int h) protected
Definition at line 168 of file Image3.cpp.
{
     resize(w, h);
     int N = w * h;
     Color3* dst = data.getCArray();
     // Strip alpha
     for (int i = 0; i < N; ++i) {
         dst[i] = src[i].rgb();
     }
 }
References G3D::Map2D< Color3, Color3 >::h, G3D::Map2D< Color3, Color3 >::resize(), G3D::Color4::rgb(), and G3D::Map2D< Color3, Color3 >::w.
copyArray() [6/6]
void G3D::Image3::copyArray (const Color4unorm8 * src, int w, int h) protected
Definition at line 149 of file Image3.cpp.
{
     resize(w, h);
     int N = w * h;
     Color3* dst = data.getCArray();
     // Strip alpha and convert
     for (int i = 0; i < N; ++i) {
         dst[i] = Color3(src[i].rgb());
     }
 }
References G3D::Map2D< Color3, Color3 >::h, G3D::Map2D< Color3, Color3 >::resize(), and G3D::Map2D< Color3, Color3 >::w.
createEmpty() [1/2]
Image3::Ref G3D::Image3::createEmpty (int width, int height, WrapMode wrap = WrapMode::ERROR) static
Creates an all-zero width x height image.
Definition at line 43 of file Image3.cpp.
{
     return shared_ptr<Image3>(new Image3(width, height, wrap));
 }
References G3D::Map2D< Color3, Color3 >::height(), Image3(), G3D::Map2D< Color3, Color3 >::width(), and G3D::wrap().
Referenced by createEmpty(), fromArray(), fromFile(), and fromImage3unorm8().
createEmpty() [2/2]
Image3::Ref G3D::Image3::createEmpty (WrapMode wrap = WrapMode::ERROR) static
Creates a 0 x 0 image.
Definition at line 48 of file Image3.cpp.
{
     return createEmpty(0, 0, wrap);
 }
References createEmpty(), and G3D::wrap().
format()
const ImageFormat * G3D::Image3::format () const
Definition at line 211 of file Image3.cpp.
{
     return ImageFormat::RGB32F();
 }
References G3D::ImageFormat::RGB32F().
fromArray() [1/6]
Image3::Ref G3D::Image3::fromArray (const class Color1 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 102 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromArray() [2/6]
Image3::Ref G3D::Image3::fromArray (const class Color1unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 109 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromArray() [3/6]
Image3::Ref G3D::Image3::fromArray (const class Color3 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 116 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromArray() [4/6]
Image3::Ref G3D::Image3::fromArray (const class Color3unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 95 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromArray() [5/6]
Image3::Ref G3D::Image3::fromArray (const class Color4 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 130 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromArray() [6/6]
Image3::Ref G3D::Image3::fromArray (const class Color4unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 123 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color3, Color3 >::h, ptr(), G3D::Map2D< Color3, Color3 >::w, and G3D::wrap().
fromFile()
Image3::Ref G3D::Image3::fromFile (const std::string & filename, WrapMode wrap = WrapMode::ERROR) static
Definition at line 53 of file Image3.cpp.
{
     Ref out = createEmpty(wrap);
     out->load(filename);
     return out;
 }
References createEmpty(), and G3D::wrap().
fromImage3unorm8()
Image3::Ref G3D::Image3::fromImage3unorm8 (const shared_ptr< class Image3unorm8 > & im) static
Definition at line 29 of file Image3.cpp.
{
     Ref out = createEmpty(im->wrapMode());
     out->resize(im->width(), im->height());
     int N = im->width() * im->height();
     const Color3unorm8* src = reinterpret_cast<Color3unorm8*>(im->getCArray());
     for (int i = 0; i < N; ++i) {
         out->data[i] = Color3(src[i]);
     }
     return out;
 }
References createEmpty().
load()
void G3D::Image3::load (const std::string & filename)
Loads from any of the file formats supported by G3D::GImage. If there is an alpha channel on the input, it is stripped. Converts 8-bit formats to the range (0, 1)
Definition at line 60 of file Image3.cpp.
{
     shared_ptr<Image> image = Image::fromFile(filename);
     if (image->format() != ImageFormat::RGB32F()) {
         image->convertToRGB8();
     }
     switch (image->format()->code)
     {
         case ImageFormat::CODE_L8:
             copyArray(static_cast<const Color1unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_L32F:
             copyArray(static_cast<const Color1*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGB8:
             copyArray(static_cast<const Color3unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGB32F:
             copyArray(static_cast<const Color3*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGBA8:
             copyArray(static_cast<const Color4unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGBA32F:
             copyArray(static_cast<const Color4*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         default:
             debugAssertM(false, "Trying to load unsupported image format");
             break;
     }
     setChanged(true);
 }
References G3D::ImageFormat::CODE_L32F, G3D::ImageFormat::CODE_L8, G3D::ImageFormat::CODE_RGB32F, G3D::ImageFormat::CODE_RGB8, G3D::ImageFormat::CODE_RGBA32F, G3D::ImageFormat::CODE_RGBA8, copyArray(), debugAssertM, G3D::ImageFormat::RGB32F(), and G3D::Map2D< Color3, Color3 >::setChanged().
save()
void G3D::Image3::save (const std::string & filename)
Saves in any of the formats supported by G3D::GImage. Assumes the data is on the range (0, 1) if saving to an 8-bit format.
Saves in any of the formats supported by G3D::GImage.
Definition at line 204 of file Image3.cpp.
{
     // To avoid saving as floating point image.  FreeImage cannot convert floating point to RGB8.
     Image3unorm8::Ref unorm8 = Image3unorm8::fromImage3(dynamic_pointer_cast<Image3>(shared_from_this()));
     unorm8->save(filename);
 }
References G3D::unorm8.
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Image3.h
deps/g3dlite/source/Image3.cpp