Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/ctl.h File Reference
ctl.h File Reference
#include "jemalloc/internal/jemalloc_internal_types.h"
#include "jemalloc/internal/malloc_io.h"
#include "jemalloc/internal/mutex_prof.h"
#include "jemalloc/internal/ql.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/stats.h"
Classes
struct ctl_node_s
struct ctl_named_node_s
struct ctl_indexed_node_s
struct ctl_arena_stats_s
struct ctl_stats_s
struct ctl_arena_s
struct ctl_arenas_s
Macros
#define CTL_MAX_DEPTH 7
#define xmallctl(name, oldp, oldlenp, newp, newlen)
#define xmallctlnametomib(name, mibp, miblenp)
#define xmallctlbymib(mib, miblen, oldp, oldlenp, newp, newlen)
Typedefs
typedef struct ctl_node_s ctl_node_t
typedef struct ctl_named_node_s ctl_named_node_t
typedef struct ctl_indexed_node_s ctl_indexed_node_t
typedef struct ctl_arena_stats_s ctl_arena_stats_t
typedef struct ctl_stats_s ctl_stats_t
typedef struct ctl_arena_s ctl_arena_t
typedef struct ctl_arenas_s ctl_arenas_t
Functions
int ctl_byname (tsd_t *tsd, const char *name, void *oldp, size_t *oldlenp, void *newp, size_t newlen)
int ctl_nametomib (tsd_t *tsd, const char *name, size_t *mibp, size_t *miblenp)
int ctl_bymib (tsd_t *tsd, const size_t *mib, size_t miblen, void *oldp, size_t *oldlenp, void *newp, size_t newlen)
bool ctl_boot (void)
void ctl_prefork (tsdn_t *tsdn)
void ctl_postfork_parent (tsdn_t *tsdn)
void ctl_postfork_child (tsdn_t *tsdn)
Macro Definition Documentation
CTL_MAX_DEPTH
#define CTL_MAX_DEPTH 7
Definition at line 12 of file ctl.h.
xmallctl
#define xmallctl (name, oldp, oldlenp, newp, newlen)
Value:
    do {        \
    if (je_mallctl(name, oldp, oldlenp, newp, newlen)       \
        != 0) {                         \
        malloc_printf(                      \
            "<jemalloc>: Failure in xmallctl(\"%s\", ...)\n",   \
            name);                      \
        abort();                        \
    }                               \
} while (0)
Definition at line 107 of file ctl.h.
xmallctlbymib
#define xmallctlbymib (mib, miblen, oldp, oldlenp, newp, newlen)
Value:
    do {    \
    if (je_mallctlbymib(mib, miblen, oldp, oldlenp, newp,       \
        newlen) != 0) {                     \
        malloc_write(                       \
            "<jemalloc>: Failure in xmallctlbymib()\n");    \
        abort();                        \
    }                               \
} while (0)
Definition at line 125 of file ctl.h.
xmallctlnametomib
#define xmallctlnametomib (name, mibp, miblenp)
Value:
    do {            \
    if (je_mallctlnametomib(name, mibp, miblenp) != 0) {        \
        malloc_printf("<jemalloc>: Failure in "         \
            "xmallctlnametomib(\"%s\", ...)\n", name);      \
        abort();                        \
    }                               \
} while (0)
Definition at line 117 of file ctl.h.
Typedef Documentation
ctl_arena_stats_t
typedef struct ctl_arena_stats_s ctl_arena_stats_t
ctl_arena_t
typedef struct ctl_arena_s ctl_arena_t
Definition at line 1 of file ctl.h.
ctl_arenas_t
typedef struct ctl_arenas_s ctl_arenas_t
ctl_indexed_node_t
typedef struct ctl_indexed_node_s ctl_indexed_node_t
ctl_named_node_t
typedef struct ctl_named_node_s ctl_named_node_t
ctl_node_t
typedef struct ctl_node_s ctl_node_t
ctl_stats_t
typedef struct ctl_stats_s ctl_stats_t
Function Documentation
ctl_boot()
bool ctl_boot (void)
Definition at line 1387 of file ctl.c.
                {
     if (malloc_mutex_init(&ctl_mtx, "ctl", WITNESS_RANK_CTL,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     ctl_initialized = false;
     return false;
 }
References ctl_initialized, ctl_mtx, malloc_mutex_init, malloc_mutex_rank_exclusive, and WITNESS_RANK_CTL.
ctl_bymib()
int ctl_bymib (tsd_t * tsd, const size_t * mib, size_t miblen, void * oldp, size_t * oldlenp, void * newp, size_t newlen)
Definition at line 1338 of file ctl.c.
{
     int ret;
     const ctl_named_node_t *node;
     size_t i;
     if (!ctl_initialized && ctl_init(tsd)) {
         ret = EAGAIN;
         goto label_return;
     }
     /* Iterate down the tree. */
     node = super_root_node;
     for (i = 0; i < miblen; i++) {
         assert(node);
         assert(node->nchildren > 0);
         if (ctl_named_node(node->children) != NULL) {
             /* Children are named. */
             if (node->nchildren <= mib[i]) {
                 ret = ENOENT;
                 goto label_return;
             }
             node = ctl_named_children(node, mib[i]);
         } else {
             const ctl_indexed_node_t *inode;
             /* Indexed element. */
             inode = ctl_indexed_node(node->children);
             node = inode->index(tsd_tsdn(tsd), mib, miblen, mib[i]);
             if (node == NULL) {
                 ret = ENOENT;
                 goto label_return;
             }
         }
     }
     /* Call the ctl function. */
     if (node && node->ctl) {
         ret = node->ctl(tsd, mib, miblen, oldp, oldlenp, newp, newlen);
     } else {
         /* Partial MIB. */
         ret = ENOENT;
     }
 label_return:
     return(ret);
 }
References assert(), ctl_named_node_s::children, ctl_named_node_s::ctl, ctl_indexed_node(), ctl_init(), ctl_initialized, ctl_named_children(), ctl_named_node(), ctl_indexed_node_s::index, ctl_named_node_s::nchildren, NULL, ret, super_root_node, and tsd_tsdn().
ctl_byname()
int ctl_byname (tsd_t * tsd, const char * name, void * oldp, size_t * oldlenp, void * newp, size_t newlen)
Definition at line 1292 of file ctl.c.
{
     int ret;
     size_t depth;
     ctl_node_t const *nodes[CTL_MAX_DEPTH];
     size_t mib[CTL_MAX_DEPTH];
     const ctl_named_node_t *node;
     if (!ctl_initialized && ctl_init(tsd)) {
         ret = EAGAIN;
         goto label_return;
     }
     depth = CTL_MAX_DEPTH;
     ret = ctl_lookup(tsd_tsdn(tsd), name, nodes, mib, &depth);
     if (ret != 0) {
         goto label_return;
     }
     node = ctl_named_node(nodes[depth-1]);
     if (node != NULL && node->ctl) {
         ret = node->ctl(tsd, mib, depth, oldp, oldlenp, newp, newlen);
     } else {
         /* The name refers to a partial path through the ctl tree. */
         ret = ENOENT;
     }
 label_return:
     return(ret);
 }
References ctl_named_node_s::ctl, ctl_init(), ctl_initialized, ctl_lookup(), CTL_MAX_DEPTH, ctl_named_node(), name, NULL, ret, and tsd_tsdn().
ctl_nametomib()
int ctl_nametomib (tsd_t * tsd, const char * name, size_t * mibp, size_t * miblenp)
Definition at line 1324 of file ctl.c.
{
     int ret;
     if (!ctl_initialized && ctl_init(tsd)) {
         ret = EAGAIN;
         goto label_return;
     }
     ret = ctl_lookup(tsd_tsdn(tsd), name, NULL, mibp, miblenp);
 label_return:
     return(ret);
 }
References ctl_init(), ctl_initialized, ctl_lookup(), name, NULL, ret, and tsd_tsdn().
ctl_postfork_child()
void ctl_postfork_child (tsdn_t * tsdn)
Definition at line 1409 of file ctl.c.
{
     malloc_mutex_postfork_child(tsdn, &ctl_mtx);
 }
References ctl_mtx, and malloc_mutex_postfork_child.
ctl_postfork_parent()
void ctl_postfork_parent (tsdn_t * tsdn)
Definition at line 1404 of file ctl.c.
{
     malloc_mutex_postfork_parent(tsdn, &ctl_mtx);
 }
References ctl_mtx, and malloc_mutex_postfork_parent.
ctl_prefork()
void ctl_prefork (tsdn_t * tsdn)
Definition at line 1399 of file ctl.c.
{
     malloc_mutex_prefork(tsdn, &ctl_mtx);
 }
References ctl_mtx, and malloc_mutex_prefork.