Azerotcore-wotlk: go_bells::go_bellsAI Struct Reference
go_bells::go_bellsAI Struct Reference
Public Member Functions
go_bellsAI (GameObject *go)
void UpdateAI (uint32 const diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
EventMap _events
uint32 _soundId
bool once
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 1684 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_bellsAI()
go_bells::go_bellsAI::go_bellsAI (GameObject * go) inline
Definition at line 1686 of file go_scripts.cpp.
                                    : GameObjectAI(go), _soundId(0), once(true)
         {
             uint32 zoneId = go->GetZoneId();
             switch (go->GetEntry())
             {
             case GO_HORDE_BELL:
             {
                 switch (zoneId)
                 {
                 case TIRISFAL_ZONE:
                 case UNDERCITY_ZONE:
                 case HILLSBRAD_FOOTHILLS_ZONE:
                 case DUSKWOOD_ZONE:
                     _soundId = BELLTOLLHORDE;
                     break;
                 default:
                     _soundId = BELLTOLLTRIBAL;
                     break;
                 }
                 break;
             }
             case GO_ALLIANCE_BELL:
             {
                 switch (zoneId)
                 {
                 case IRONFORGE_ZONE:
                 case DUN_MOROGH_ZONE:
                     _soundId = BELLTOLLDWARFGNOME;
                     break;
                 case DARNASSUS_ZONE:
                 case TELDRASSIL_ZONE:
                 case ASHENVALE_ZONE:
                 case SHATTRATH_ZONE:
                     _soundId = BELLTOLLNIGHTELF;
                     break;
                 case WESTFALL_ZONE:
                     if (go->GetAreaId() == AREA_WESTFALL_LIGHTHOUSE)
                     {
                         _soundId = LIGHTHOUSEFOGHORN;
                     }
                     else
                     {
                         _soundId = BELLTOLLALLIANCE;
                     }
                     break;
                 case DUSTWALLOW_MARSH_ZONE:
                     if (go->GetAreaId() == AREA_ALCAZ_ISLAND)
                     {
                         _soundId = LIGHTHOUSEFOGHORN;
                     }
                     else
                     {
                         _soundId = BELLTOLLALLIANCE;
                     }
                     break;
                 default:
                     _soundId = BELLTOLLALLIANCE;
                     break;
                 }
                 break;
             }
             case GO_KHARAZHAN_BELL:
             {
                 _soundId = BELLTOLLKHARAZHAN;
                 break;
             }
             break;
             }
         }
References _soundId, AREA_ALCAZ_ISLAND, AREA_WESTFALL_LIGHTHOUSE, ASHENVALE_ZONE, BELLTOLLALLIANCE, BELLTOLLDWARFGNOME, BELLTOLLHORDE, BELLTOLLKHARAZHAN, BELLTOLLNIGHTELF, BELLTOLLTRIBAL, DARNASSUS_ZONE, DUN_MOROGH_ZONE, DUSKWOOD_ZONE, DUSTWALLOW_MARSH_ZONE, WorldObject::GetAreaId(), Object::GetEntry(), WorldObject::GetZoneId(), GO_ALLIANCE_BELL, GO_HORDE_BELL, GO_KHARAZHAN_BELL, HILLSBRAD_FOOTHILLS_ZONE, IRONFORGE_ZONE, LIGHTHOUSEFOGHORN, SHATTRATH_ZONE, TELDRASSIL_ZONE, TIRISFAL_ZONE, UNDERCITY_ZONE, and WESTFALL_ZONE.
Member Function Documentation
UpdateAI()
void go_bells::go_bellsAI::UpdateAI (uint32 const diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1757 of file go_scripts.cpp.
         {
             _events.Update(diff);
             if (sGameEventMgr->IsActiveEvent(GAME_EVENT_HOURLY_BELLS) && once)
             {
                 // Reset
                 once = false;
                 _events.ScheduleEvent(EVENT_TIME, 1000);
             }
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                 case EVENT_TIME:
                 {
                     // Get how many times it should ring
                     time_t t = time(nullptr);
                     tm local_tm;
                     tzset(); // set timezone for localtime_r() -> fix issues due to daylight time
                     localtime_r(&t, &local_tm);
                     uint8 _rings = (local_tm.tm_hour) % 12;
                     _rings = (_rings == 0) ? 12 : _rings; // 00:00 and 12:00
                     // Schedule ring event
                     for (auto i = 0; i < _rings; ++i)
                     {
                         _events.ScheduleEvent(EVENT_RING_BELL, (i * 4 + 1) * 1000);
                     }
                     break;
                 }
                 case EVENT_RING_BELL:
                 {
                     me->PlayDirectSound(_soundId);
                     break;
                 }
                 default:
                     break;
                 }
             }
         }
References _events, _soundId, EVENT_RING_BELL, EVENT_TIME, EventMap::ExecuteEvent(), GAME_EVENT_HOURLY_BELLS, localtime_r(), GameObjectAI::me, once, WorldObject::PlayDirectSound(), EventMap::ScheduleEvent(), sGameEventMgr, and EventMap::Update().
Member Data Documentation
_events
EventMap go_bells::go_bellsAI::_events private
Definition at line 1801 of file go_scripts.cpp.
Referenced by UpdateAI().
_soundId
uint32 go_bells::go_bellsAI::_soundId private
Definition at line 1802 of file go_scripts.cpp.
Referenced by go_bellsAI(), and UpdateAI().
once
bool go_bells::go_bellsAI::once private
Definition at line 1803 of file go_scripts.cpp.
Referenced by UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/World/go_scripts.cpp