Azerotcore-wotlk: ChaseAngle Struct Reference
ChaseAngle Struct Reference
#include <MotionMaster.h>
Public Member Functions
ChaseAngle (float angle, float _tolerance=M_PI_4)
float UpperBound () const
float LowerBound () const
bool IsAngleOkay (float relativeAngle) const
Public Attributes
float RelativeAngle
float Tolerance
Detailed Description
Definition at line 94 of file MotionMaster.h.
Constructor & Destructor Documentation
ChaseAngle()
ChaseAngle::ChaseAngle (float angle, float _tolerance = M_PI_4)
Definition at line 42 of file MotionMaster.cpp.
 : RelativeAngle(Position::NormalizeOrientation(angle)), Tolerance(_tolerance) { }
Member Function Documentation
IsAngleOkay()
bool ChaseAngle::IsAngleOkay (float relativeAngle) const
Definition at line 54 of file MotionMaster.cpp.
 {
     float const diff = std::abs(relativeAngle - RelativeAngle);
     return (std::min(diff, float(2 * M_PI) - diff) <= Tolerance);
 }
References abs(), diff(), M_PI, min, RelativeAngle, and Tolerance.
LowerBound()
float ChaseAngle::LowerBound () const
Definition at line 49 of file MotionMaster.cpp.
 {
     return Position::NormalizeOrientation(RelativeAngle - Tolerance);
 }
References Position::NormalizeOrientation(), RelativeAngle, and Tolerance.
UpperBound()
float ChaseAngle::UpperBound () const
Definition at line 44 of file MotionMaster.cpp.
 {
     return Position::NormalizeOrientation(RelativeAngle + Tolerance);
 }
References Position::NormalizeOrientation(), RelativeAngle, and Tolerance.
Member Data Documentation
RelativeAngle
float ChaseAngle::RelativeAngle
Definition at line 98 of file MotionMaster.h.
Referenced by IsAngleOkay(), LowerBound(), and UpperBound().
Tolerance
float ChaseAngle::Tolerance
Definition at line 99 of file MotionMaster.h.
Referenced by IsAngleOkay(), LowerBound(), and UpperBound().
The documentation for this struct was generated from the following files:
src/server/game/Movement/MotionMaster.h
src/server/game/Movement/MotionMaster.cpp