Azerotcore-wotlk: npc_announcer_toc5 Class Reference
npc_announcer_toc5 Class Reference
Classes
struct npc_announcer_toc5AI
Public Member Functions
npc_announcer_toc5 ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 29 of file trial_of_the_champion.cpp.
Constructor & Destructor Documentation
npc_announcer_toc5()
npc_announcer_toc5::npc_announcer_toc5 () inline
Definition at line 32 of file trial_of_the_champion.cpp.
 : CreatureScript("npc_announcer_toc5") {}
Member Function Documentation
GetAI()
CreatureAI* npc_announcer_toc5::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 96 of file trial_of_the_champion.cpp.
     {
         return GetTrialOfTheChampionAI<npc_announcer_toc5AI>(creature);
     }
OnGossipHello()
bool npc_announcer_toc5::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 34 of file trial_of_the_champion.cpp.
     {
         if (!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         InstanceScript* pInstance = creature->GetInstanceScript();
         if (!pInstance)
             return true;
         uint32 gossipTextId = 0;
         switch (pInstance->GetData(DATA_INSTANCE_PROGRESS))
         {
             case INSTANCE_PROGRESS_INITIAL:
                 if (!player->GetVehicle())
                 {
                     if (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE)
                         gossipTextId = 15043; //Horde text
                     else
                         gossipTextId = 14757; //Alliance text
                 }
                 else
                 {
                     gossipTextId = 14688;
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_START_EVENT1a, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1338);
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_START_EVENT1b, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1341);
                 }
                 break;
             case INSTANCE_PROGRESS_CHAMPIONS_DEAD:
                 gossipTextId = 14737;
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_START_EVENT2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1339);
                 break;
             case INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED:
                 gossipTextId = 14738;
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_START_EVENT3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1340);
                 break;
             default:
                 return true;
         }
         SendGossipMenuFor(player, gossipTextId, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), DATA_INSTANCE_PROGRESS, DATA_TEAMID_IN_INSTANCE, ZoneScript::GetData(), Object::GetGUID(), WorldObject::GetInstanceScript(), Unit::GetVehicle(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, GOSSIP_START_EVENT1a, GOSSIP_START_EVENT1b, GOSSIP_START_EVENT2, GOSSIP_START_EVENT3, Object::HasFlag(), INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED, INSTANCE_PROGRESS_CHAMPIONS_DEAD, INSTANCE_PROGRESS_INITIAL, SendGossipMenuFor(), TEAM_HORDE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
OnGossipSelect()
bool npc_announcer_toc5::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 77 of file trial_of_the_champion.cpp.
     {
         if(!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         InstanceScript* pInstance = creature->GetInstanceScript();
         if(!pInstance)
             return true;
         if(uiAction == GOSSIP_ACTION_INFO_DEF + 1338 || uiAction == GOSSIP_ACTION_INFO_DEF + 1341 || uiAction == GOSSIP_ACTION_INFO_DEF + 1339 || uiAction == GOSSIP_ACTION_INFO_DEF + 1340)
         {
             pInstance->SetData(DATA_ANNOUNCER_GOSSIP_SELECT, (uiAction == GOSSIP_ACTION_INFO_DEF + 1341 ? 1 : 0));
             creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
         }
         CloseGossipMenuFor(player);
         return true;
     }
References CloseGossipMenuFor(), DATA_ANNOUNCER_GOSSIP_SELECT, WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, Object::HasFlag(), Object::RemoveFlag(), ZoneScript::SetData(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp