Azerotcore-wotlk: deps/mysqllite/mysys/errors.c File Reference
errors.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
Functions
void init_glob_errs (void)
void wait_for_free_space (const char *filename, int errors)
const char ** get_global_errmsgs ()
Variables
const char * globerrs [GLOBERRS]
Function Documentation
get_global_errmsgs()
const char** get_global_errmsgs ()
Definition at line 116 of file errors.c.
 {
   return globerrs;
 }
References globerrs.
init_glob_errs()
void init_glob_errs (void)
Definition at line 58 of file errors.c.
 {
   /* This is now done statically. */
 }
Referenced by my_basic_init().
wait_for_free_space()
void wait_for_free_space (const char * filename, int errors)
Definition at line 102 of file errors.c.
 {
   if (errors == 0)
     my_error(EE_DISK_FULL,MYF(ME_BELL | ME_NOREFRESH),
              filename,my_errno,MY_WAIT_FOR_USER_TO_FIX_PANIC);
   if (!(errors % MY_WAIT_GIVE_USER_A_MESSAGE))
     my_printf_error(EE_DISK_FULL,
                     "Retry in %d secs. Message reprinted in %d secs",
                     MYF(ME_BELL | ME_NOREFRESH),
                     MY_WAIT_FOR_USER_TO_FIX_PANIC,
                     MY_WAIT_GIVE_USER_A_MESSAGE * MY_WAIT_FOR_USER_TO_FIX_PANIC );
   (void) sleep(MY_WAIT_FOR_USER_TO_FIX_PANIC);
 }
References EE_DISK_FULL, mpq::errors, ME_BELL, ME_NOREFRESH, my_errno, my_error(), my_printf_error(), MY_WAIT_FOR_USER_TO_FIX_PANIC, MY_WAIT_GIVE_USER_A_MESSAGE, and MYF.
Referenced by my_fwrite(), my_pwrite(), and my_write().
Variable Documentation
globerrs
const char* globerrs[GLOBERRS]
Definition at line 21 of file errors.c.
Referenced by get_global_errmsgs().