Azerotcore-wotlk: Acore::UnitLastSearcher< Check > Struct Template Reference
Acore::UnitLastSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitLastSearcher (WorldObject const *searcher, Unit *&result, Check &check)
void Visit (CreatureMapType &m)
void Visit (PlayerMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
Unit *& i_object
Check & i_check
Detailed Description
template<class Check>
struct Acore::UnitLastSearcher< Check >
Definition at line 374 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitLastSearcher()
template<class Check > Acore::UnitLastSearcher< Check >::UnitLastSearcher (WorldObject const * searcher, Unit *& result, Check & check) inline
Definition at line 380 of file GridNotifiers.h.
             : i_phaseMask(searcher->GetPhaseMask()), i_object(result), i_check(check) {}
Member Function Documentation
Visit() [1/3]
template<class Check > void Acore::UnitLastSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 388 of file GridNotifiersImpl.h.
 {
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void Acore::UnitLastSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 386 of file GridNotifiers.h.
 {}
Visit() [3/3]
template<class Check > void Acore::UnitLastSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 401 of file GridNotifiersImpl.h.
 {
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Member Data Documentation
i_check
template<class Check > Check& Acore::UnitLastSearcher< Check >::i_check
Definition at line 378 of file GridNotifiers.h.
i_object
template<class Check > Unit*& Acore::UnitLastSearcher< Check >::i_object
Definition at line 377 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::UnitLastSearcher< Check >::i_phaseMask
Definition at line 376 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h