Azerotcore-wotlk: achievement_intense_cold Class Reference
achievement_intense_cold Class Reference
Public Member Functions
achievement_intense_cold ()
bool OnCheck (Player *player, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 195 of file boss_keristrasza.cpp.
Constructor & Destructor Documentation
achievement_intense_cold()
achievement_intense_cold::achievement_intense_cold () inline
Definition at line 198 of file boss_keristrasza.cpp.
                                : AchievementCriteriaScript("achievement_intense_cold")
     {
     }
Member Function Documentation
OnCheck()
bool achievement_intense_cold::OnCheck (Player * player, Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 202 of file boss_keristrasza.cpp.
     {
         if (!target)
             return false;
         return target->GetAI()->GetData(player->GetGUID().GetCounter());
     }
References Unit::GetAI(), ObjectGuid::GetCounter(), UnitAI::GetData(), and Object::GetGUID().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Nexus/Nexus/boss_keristrasza.cpp