Azerotcore-wotlk: rcIntArray Class Reference
rcIntArray Class Reference
Legacy class. Prefer rcVector<int>.
#include <RecastAlloc.h>
Public Member Functions
rcIntArray ()
rcIntArray (int n)
void push (int item)
void resize (int size)
int pop ()
int size () const
int & operator[] (int index)
int operator[] (int index) const
Private Attributes
rcTempVector< int > m_impl
Detailed Description
Legacy class. Prefer rcVector<int>.
Definition at line 298 of file RecastAlloc.h.
Constructor & Destructor Documentation
rcIntArray() [1/2]
rcIntArray::rcIntArray () inline
Definition at line 302 of file RecastAlloc.h.
 {}
rcIntArray() [2/2]
rcIntArray::rcIntArray (int n) inline
Definition at line 303 of file RecastAlloc.h.
 : m_impl(n, 0) {}
Member Function Documentation
operator[]() [1/2]
int& rcIntArray::operator[] (int index) inline
Definition at line 313 of file RecastAlloc.h.
 { return m_impl[index]; }
References index, and m_impl.
operator[]() [2/2]
int rcIntArray::operator[] (int index) const inline
Definition at line 314 of file RecastAlloc.h.
 { return m_impl[index]; }
References index, and m_impl.
pop()
int rcIntArray::pop () inline
Definition at line 306 of file RecastAlloc.h.
     {
         int v = m_impl.back();
         m_impl.pop_back();
         return v;
     }
References rcVectorBase< T, H >::back(), m_impl, and rcVectorBase< T, H >::pop_back().
Referenced by mergeAndFilterRegions(), removeAdjacentNeighbours(), and walkContour().
push()
void rcIntArray::push (int item) inline
Definition at line 304 of file RecastAlloc.h.
 { m_impl.push_back(item); }
References m_impl, and rcVectorBase< T, H >::push_back().
Referenced by addUniqueConnection(), addUniqueFloorRegion(), buildPolyDetail(), mergeAndFilterLayerRegions(), mergeAndFilterRegions(), mergeRegions(), simplifyContour(), triangulateHull(), and walkContour().
resize()
void rcIntArray::resize (int size) inline
Definition at line 305 of file RecastAlloc.h.
 { m_impl.resize(size); }
References m_impl, rcVectorBase< T, H >::resize(), and size().
Referenced by buildPolyDetail(), delaunayHull(), getHeightData(), mergeAndFilterLayerRegions(), mergeAndFilterRegions(), mergeRegions(), push3(), rcBuildContours(), removeDegenerateSegments(), and simplifyContour().
size()
int rcIntArray::size () const inline
Definition at line 312 of file RecastAlloc.h.
 { return static_cast<int>(m_impl.size()); }
References m_impl, and rcVectorBase< T, H >::size().
Referenced by addUniqueConnection(), addUniqueFloorRegion(), buildPolyDetail(), canMergeWithRegion(), delaunayHull(), getHeightData(), isRegionConnectedToBorder(), mergeAndFilterLayerRegions(), mergeAndFilterRegions(), mergeRegions(), push3(), rcBuildContours(), rcBuildPolyMeshDetail(), rcBuildRegions(), removeAdjacentNeighbours(), removeDegenerateSegments(), replaceNeighbour(), resize(), simplifyContour(), and walkContour().
Member Data Documentation
m_impl
rcTempVector<int> rcIntArray::m_impl private
Definition at line 300 of file RecastAlloc.h.
Referenced by operator[](), pop(), push(), resize(), and size().
The documentation for this class was generated from the following file:
deps/recastnavigation/Recast/Include/RecastAlloc.h