Azerotcore-wotlk: deps/jemalloc/src/bin.c File Reference
bin.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/bin.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/witness.h"
Functions
static void bin_infos_init (sc_data_t *sc_data, unsigned bin_shard_sizes[SC_NBINS], bin_info_t bin_infos[SC_NBINS])
bool bin_update_shard_size (unsigned bin_shard_sizes[SC_NBINS], size_t start_size, size_t end_size, size_t nshards)
void bin_shard_sizes_boot (unsigned bin_shard_sizes[SC_NBINS])
void bin_boot (sc_data_t *sc_data, unsigned bin_shard_sizes[SC_NBINS])
bool bin_init (bin_t *bin)
void bin_prefork (tsdn_t *tsdn, bin_t *bin)
void bin_postfork_parent (tsdn_t *tsdn, bin_t *bin)
void bin_postfork_child (tsdn_t *tsdn, bin_t *bin)
Variables
bin_info_t bin_infos [SC_NBINS]
Function Documentation
bin_boot()
void bin_boot (sc_data_t * sc_data, unsigned bin_shard_sizes[SC_NBINS])
Definition at line 62 of file bin.c.
{
     assert(sc_data->initialized);
     bin_infos_init(sc_data, bin_shard_sizes, bin_infos);
 }
References assert(), bin_infos, bin_infos_init(), and sc_data_s::initialized.
bin_infos_init()
static void bin_infos_init (sc_data_t * sc_data, unsigned bin_shard_sizes[SC_NBINS], bin_info_t bin_infos[SC_NBINS]) static
Definition at line 12 of file bin.c.
{
     for (unsigned i = 0; i < SC_NBINS; i++) {
         bin_info_t *bin_info = &bin_infos[i];
         sc_t *sc = &sc_data->sc[i];
         bin_info->reg_size = ((size_t)1U << sc->lg_base)
             + ((size_t)sc->ndelta << sc->lg_delta);
         bin_info->slab_size = (sc->pgs << LG_PAGE);
         bin_info->nregs =
             (uint32_t)(bin_info->slab_size / bin_info->reg_size);
         bin_info->n_shards = bin_shard_sizes[i];
         bitmap_info_t bitmap_info = BITMAP_INFO_INITIALIZER(
             bin_info->nregs);
         bin_info->bitmap_info = bitmap_info;
     }
 }
References bin_infos, bin_info_s::bitmap_info, BITMAP_INFO_INITIALIZER, sc_s::lg_base, sc_s::lg_delta, LG_PAGE, bin_info_s::n_shards, sc_s::ndelta, bin_info_s::nregs, sc_s::pgs, bin_info_s::reg_size, sc_data_s::sc, SC_NBINS, and bin_info_s::slab_size.
Referenced by bin_boot().
bin_init()
bool bin_init (bin_t * bin)
Definition at line 68 of file bin.c.
                      {
     if (malloc_mutex_init(&bin->lock, "bin", WITNESS_RANK_BIN,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     bin->slabcur = NULL;
     extent_heap_new(&bin->slabs_nonfull);
     extent_list_init(&bin->slabs_full);
     if (config_stats) {
         memset(&bin->stats, 0, sizeof(bin_stats_t));
     }
     return false;
 }
References config_stats, extent_heap_new, extent_list_init(), bin_s::lock, malloc_mutex_init, malloc_mutex_rank_exclusive, memset, NULL, bin_s::slabcur, bin_s::slabs_full, bin_s::slabs_nonfull, bin_s::stats, and WITNESS_RANK_BIN.
bin_postfork_child()
void bin_postfork_child (tsdn_t * tsdn, bin_t * bin)
Definition at line 93 of file bin.c.
{
     malloc_mutex_postfork_child(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_postfork_child.
bin_postfork_parent()
void bin_postfork_parent (tsdn_t * tsdn, bin_t * bin)
Definition at line 88 of file bin.c.
{
     malloc_mutex_postfork_parent(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_postfork_parent.
bin_prefork()
void bin_prefork (tsdn_t * tsdn, bin_t * bin)
Definition at line 83 of file bin.c.
{
     malloc_mutex_prefork(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_prefork.
bin_shard_sizes_boot()
void bin_shard_sizes_boot (unsigned bin_shard_sizes[SC_NBINS])
Definition at line 54 of file bin.c.
{
     /* Load the default number of shards. */
     for (unsigned i = 0; i < SC_NBINS; i++) {
         bin_shard_sizes[i] = N_BIN_SHARDS_DEFAULT;
     }
 }
References N_BIN_SHARDS_DEFAULT, and SC_NBINS.
bin_update_shard_size()
bool bin_update_shard_size (unsigned bin_shard_sizes[SC_NBINS], size_t start_size, size_t end_size, size_t nshards)
Definition at line 30 of file bin.c.
{
     if (nshards > BIN_SHARDS_MAX || nshards == 0) {
         return true;
     }
     if (start_size > SC_SMALL_MAXCLASS) {
         return false;
     }
     if (end_size > SC_SMALL_MAXCLASS) {
         end_size = SC_SMALL_MAXCLASS;
     }
     /* Compute the index since this may happen before sz init. */
     szind_t ind1 = sz_size2index_compute(start_size);
     szind_t ind2 = sz_size2index_compute(end_size);
     for (unsigned i = ind1; i <= ind2; i++) {
         bin_shard_sizes[i] = (unsigned)nshards;
     }
     return false;
 }
References BIN_SHARDS_MAX, SC_SMALL_MAXCLASS, and sz_size2index_compute().
Variable Documentation
bin_infos
bin_info_t bin_infos[SC_NBINS]
Definition at line 9 of file bin.c.
Referenced by bin_boot(), and bin_infos_init().