Azerotcore-wotlk: NetworkThread< SocketType > Class Template Reference
NetworkThread< SocketType > Class Template Reference
#include <NetworkThread.h>
Public Member Functions
NetworkThread ()
virtual ~NetworkThread ()
void Stop ()
bool Start ()
void Wait ()
int32 GetConnectionCount () const
virtual void AddSocket (std::shared_ptr< SocketType > sock)
tcp::socket * GetSocketForAccept ()
Protected Member Functions
virtual void SocketAdded (std::shared_ptr< SocketType >)
virtual void SocketRemoved (std::shared_ptr< SocketType >)
void AddNewSockets ()
void Run ()
void Update ()
Private Types
typedef std::vector< std::shared_ptr< SocketType > > SocketContainer
Private Attributes
std::atomic< int32 > _connections
std::atomic< bool > _stopped
std::thread * _thread
SocketContainer _sockets
std::mutex _newSocketsLock
SocketContainer _newSockets
Acore::Asio::IoContext _ioContext
tcp::socket _acceptSocket
Acore::Asio::DeadlineTimer _updateTimer
Detailed Description
template<class SocketType>
class NetworkThread< SocketType >
Definition at line 38 of file NetworkThread.h.
Member Typedef Documentation
SocketContainer
template<class SocketType > typedef std::vector<std::shared_ptr<SocketType> > NetworkThread< SocketType >::SocketContainer private
Definition at line 161 of file NetworkThread.h.
Constructor & Destructor Documentation
NetworkThread()
template<class SocketType > NetworkThread< SocketType >::NetworkThread () inline
Definition at line 41 of file NetworkThread.h.
                     : _connections(0), _stopped(false), _thread(nullptr), _ioContext(1),
         _acceptSocket(_ioContext), _updateTimer(_ioContext) { }
~NetworkThread()
template<class SocketType > virtual NetworkThread< SocketType >::~NetworkThread () inline virtual
Definition at line 44 of file NetworkThread.h.
     {
         Stop();
         if (_thread)
         {
             Wait();
             delete _thread;
         }
     }
References NetworkThread< SocketType >::_thread, NetworkThread< SocketType >::Stop(), and NetworkThread< SocketType >::Wait().
Member Function Documentation
AddNewSockets()
template<class SocketType > void NetworkThread< SocketType >::AddNewSockets () inline protected
Definition at line 99 of file NetworkThread.h.
     {
         std::lock_guard<std::mutex> lock(_newSocketsLock);
         if (_newSockets.empty())
             return;
         for (std::shared_ptr<SocketType> sock : _newSockets)
         {
             if (!sock->IsOpen())
             {
                 SocketRemoved(sock);
                 --_connections;
             }
             else
                 _sockets.push_back(sock);
         }
         _newSockets.clear();
     }
References NetworkThread< SocketType >::_connections, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_newSocketsLock, NetworkThread< SocketType >::_sockets, and NetworkThread< SocketType >::SocketRemoved().
Referenced by NetworkThread< SocketType >::Update().
AddSocket()
template<class SocketType > virtual void NetworkThread< SocketType >::AddSocket (std::shared_ptr< SocketType > sock) inline virtual
Definition at line 84 of file NetworkThread.h.
     {
         std::lock_guard<std::mutex> lock(_newSocketsLock);
         ++_connections;
         _newSockets.push_back(sock);
         SocketAdded(sock);
     }
References NetworkThread< SocketType >::_connections, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_newSocketsLock, and NetworkThread< SocketType >::SocketAdded().
GetConnectionCount()
template<class SocketType > int32 NetworkThread< SocketType >::GetConnectionCount () const inline
Definition at line 79 of file NetworkThread.h.
     {
         return _connections;
     }
References NetworkThread< SocketType >::_connections.
GetSocketForAccept()
template<class SocketType > tcp::socket* NetworkThread< SocketType >::GetSocketForAccept () inline
Definition at line 93 of file NetworkThread.h.
 { return &_acceptSocket; }
References NetworkThread< SocketType >::_acceptSocket.
Run()
template<class SocketType > void NetworkThread< SocketType >::Run () inline protected
Definition at line 120 of file NetworkThread.h.
     {
         LOG_DEBUG("misc", "Network Thread Starting");
         _updateTimer.expires_from_now(boost::posix_time::milliseconds(10));
         _updateTimer.async_wait(std::bind(&NetworkThread<SocketType>::Update, this));
         _ioContext.run();
         LOG_DEBUG("misc", "Network Thread exits");
         _newSockets.clear();
         _sockets.clear();
     }
References NetworkThread< SocketType >::_ioContext, NetworkThread< SocketType >::_newSockets, NetworkThread< SocketType >::_sockets, NetworkThread< SocketType >::_updateTimer, LOG_DEBUG, G3D::units::milliseconds(), and Acore::Asio::IoContext::run().
Referenced by NetworkThread< SocketType >::Start().
SocketAdded()
template<class SocketType > virtual void NetworkThread< SocketType >::SocketAdded (std::shared_ptr< SocketType >) inline protected virtual
Reimplemented in WorldSocketThread.
Definition at line 96 of file NetworkThread.h.
 { }
Referenced by NetworkThread< SocketType >::AddSocket().
SocketRemoved()
template<class SocketType > virtual void NetworkThread< SocketType >::SocketRemoved (std::shared_ptr< SocketType >) inline protected virtual
Reimplemented in WorldSocketThread.
Definition at line 97 of file NetworkThread.h.
 { }
Referenced by NetworkThread< SocketType >::AddNewSockets().
Start()
template<class SocketType > bool NetworkThread< SocketType >::Start () inline
Definition at line 61 of file NetworkThread.h.
     {
         if (_thread)
             return false;
         _thread = new std::thread(&NetworkThread::Run, this);
         return true;
     }
References NetworkThread< SocketType >::_thread, and NetworkThread< SocketType >::Run().
Stop()
template<class SocketType > void NetworkThread< SocketType >::Stop () inline
Definition at line 55 of file NetworkThread.h.
     {
         _stopped = true;
         _ioContext.stop();
     }
References NetworkThread< SocketType >::_ioContext, NetworkThread< SocketType >::_stopped, and Acore::Asio::IoContext::stop().
Referenced by NetworkThread< SocketType >::~NetworkThread().
Update()
template<class SocketType > void NetworkThread< SocketType >::Update () inline protected
Definition at line 133 of file NetworkThread.h.
     {
         if (_stopped)
             return;
         _updateTimer.expires_from_now(boost::posix_time::milliseconds(10));
         _updateTimer.async_wait(std::bind(&NetworkThread<SocketType>::Update, this));
         AddNewSockets();
         _sockets.erase(std::remove_if(_sockets.begin(), _sockets.end(), [this](std::shared_ptr<SocketType> sock)
         {
             if (!sock->Update())
             {
                 if (sock->IsOpen())
                     sock->CloseSocket();
                 this->SocketRemoved(sock);
                 --this->_connections;
                 return true;
             }
             return false;
         }), _sockets.end());
     }
References NetworkThread< SocketType >::_sockets, NetworkThread< SocketType >::_stopped, NetworkThread< SocketType >::_updateTimer, NetworkThread< SocketType >::AddNewSockets(), and G3D::units::milliseconds().
Wait()
template<class SocketType > void NetworkThread< SocketType >::Wait () inline
Definition at line 70 of file NetworkThread.h.
     {
         ASSERT(_thread);
         _thread->join();
         delete _thread;
         _thread = nullptr;
     }
References NetworkThread< SocketType >::_thread, and ASSERT.
Referenced by NetworkThread< SocketType >::~NetworkThread().
Member Data Documentation
_acceptSocket
template<class SocketType > tcp::socket NetworkThread< SocketType >::_acceptSocket private
Definition at line 174 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::GetSocketForAccept().
_connections
template<class SocketType > std::atomic<int32> NetworkThread< SocketType >::_connections private
Definition at line 163 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::AddSocket(), and NetworkThread< SocketType >::GetConnectionCount().
_ioContext
template<class SocketType > Acore::Asio::IoContext NetworkThread< SocketType >::_ioContext private
Definition at line 173 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Stop().
_newSockets
template<class SocketType > SocketContainer NetworkThread< SocketType >::_newSockets private
Definition at line 171 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::AddSocket(), and NetworkThread< SocketType >::Run().
_newSocketsLock
template<class SocketType > std::mutex NetworkThread< SocketType >::_newSocketsLock private
Definition at line 170 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::AddNewSockets(), and NetworkThread< SocketType >::AddSocket().
_sockets
template<class SocketType > SocketContainer NetworkThread< SocketType >::_sockets private
Definition at line 168 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::AddNewSockets(), NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Update().
_stopped
template<class SocketType > std::atomic<bool> NetworkThread< SocketType >::_stopped private
Definition at line 164 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::Stop(), and NetworkThread< SocketType >::Update().
_thread
template<class SocketType > std::thread* NetworkThread< SocketType >::_thread private
Definition at line 166 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::Start(), NetworkThread< SocketType >::Wait(), and NetworkThread< SocketType >::~NetworkThread().
_updateTimer
template<class SocketType > Acore::Asio::DeadlineTimer NetworkThread< SocketType >::_updateTimer private
Definition at line 175 of file NetworkThread.h.
Referenced by NetworkThread< SocketType >::Run(), and NetworkThread< SocketType >::Update().
The documentation for this class was generated from the following file:
src/server/shared/Network/NetworkThread.h