Azerotcore-wotlk: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <ByteBuffer.h>
Public Member Functions
ByteBuffer ()
ByteBuffer (size_t reserve)
ByteBuffer (ByteBuffer &&buf) noexcept
ByteBuffer (ByteBuffer const &right)=default
ByteBuffer (MessageBuffer &&buffer)
virtual ~ByteBuffer ()=default
ByteBuffer & operator= (ByteBuffer const &right)
ByteBuffer & operator= (ByteBuffer &&right) noexcept
void clear ()
template<typename T >
void append (T value)
template<typename T >
void put (std::size_t pos, T value)
ByteBuffer & operator<< (bool value)
ByteBuffer & operator<< (uint8 value)
ByteBuffer & operator<< (uint16 value)
ByteBuffer & operator<< (uint32 value)
ByteBuffer & operator<< (uint64 value)
ByteBuffer & operator<< (int8 value)
ByteBuffer & operator<< (int16 value)
ByteBuffer & operator<< (int32 value)
ByteBuffer & operator<< (int64 value)
ByteBuffer & operator<< (float value)
ByteBuffer & operator<< (double value)
ByteBuffer & operator<< (std::string_view value)
ByteBuffer & operator<< (std::string const &str)
ByteBuffer & operator<< (char const *str)
ByteBuffer & operator>> (bool &value)
ByteBuffer & operator>> (uint8 &value)
ByteBuffer & operator>> (uint16 &value)
ByteBuffer & operator>> (uint32 &value)
ByteBuffer & operator>> (uint64 &value)
ByteBuffer & operator>> (int8 &value)
ByteBuffer & operator>> (int16 &value)
ByteBuffer & operator>> (int32 &value)
ByteBuffer & operator>> (int64 &value)
ByteBuffer & operator>> (float &value)
ByteBuffer & operator>> (double &value)
ByteBuffer & operator>> (std::string &value)
uint8 & operator[] (size_t const pos)
uint8 const & operator[] (size_t const pos) const
size_t rpos () const
size_t rpos (size_t rpos_)
void rfinish ()
size_t wpos () const
size_t wpos (size_t wpos_)
template<typename T >
void read_skip ()
void read_skip (size_t skip)
template<typename T >
T read ()
template<typename T >
T read (size_t pos) const
void read (uint8 *dest, size_t len)
template<size_t Size>
void read (std::array< uint8, Size > &arr)
void readPackGUID (uint64 &guid)
std::string ReadCString (bool requireValidUtf8=true)
uint32 ReadPackedTime ()
ByteBuffer & ReadPackedTime (uint32 &time)
uint8 * contents ()
uint8 const * contents () const
size_t size () const
bool empty () const
void resize (size_t newsize)
void reserve (size_t ressize)
void shrink_to_fit ()
void append (const char *src, size_t cnt)
template<class T >
void append (const T *src, size_t cnt)
void append (uint8 const *src, size_t cnt)
void append (ByteBuffer const &buffer)
template<size_t Size>
void append (std::array< uint8, Size > const &arr)
void appendPackXYZ (float x, float y, float z)
void appendPackGUID (uint64 guid)
void AppendPackedTime (time_t time)
void put (size_t pos, const uint8 *src, size_t cnt)
void print_storage () const
void textlike () const
void hexlike () const
template<>
void read_skip ()
template<>
void read_skip ()
Static Public Attributes
constexpr static size_t DEFAULT_SIZE = 0x1000
Protected Attributes
size_t _rpos
size_t _wpos
std::vector< uint8 > _storage
Detailed Description
Definition at line 69 of file ByteBuffer.h.
Constructor & Destructor Documentation
ByteBuffer() [1/5]
ByteBuffer::ByteBuffer () inline
Definition at line 75 of file ByteBuffer.h.
                  : _rpos(0), _wpos(0)
     {
         _storage.reserve(DEFAULT_SIZE);
     }
ByteBuffer() [2/5]
ByteBuffer::ByteBuffer (size_t reserve) inline
Definition at line 80 of file ByteBuffer.h.
                                : _rpos(0), _wpos(0)
     {
         _storage.reserve(reserve);
     }
ByteBuffer() [3/5]
ByteBuffer::ByteBuffer (ByteBuffer && buf) inline noexcept
Definition at line 85 of file ByteBuffer.h.
                                           :
         _rpos(buf._rpos), _wpos(buf._wpos), _storage(std::move(buf._storage))
     {
         buf._rpos = 0;
         buf._wpos = 0;
     }
ByteBuffer() [4/5]
ByteBuffer::ByteBuffer (ByteBuffer const & right) default
ByteBuffer() [5/5]
ByteBuffer::ByteBuffer (MessageBuffer && buffer)
Definition at line 27 of file ByteBuffer.cpp.
                                              :
     _rpos(0), _wpos(0), _storage(buffer.Move()) { }
~ByteBuffer()
virtual ByteBuffer::~ByteBuffer () virtual default
Member Function Documentation
append() [1/6]
void ByteBuffer::append (ByteBuffer const & buffer) inline
Definition at line 479 of file ByteBuffer.h.
     {
         if (buffer.wpos())
         {
             append(buffer.contents(), buffer.wpos());
         }
     }
References contents(), and wpos().
append() [2/6]
void ByteBuffer::append (const char * src, size_t cnt) inline
Definition at line 467 of file ByteBuffer.h.
     {
         return append((const uint8 *)src, cnt);
     }
append() [3/6]
template<class T > void ByteBuffer::append (const T * src, size_t cnt) inline
Definition at line 472 of file ByteBuffer.h.
     {
         return append((const uint8*)src, cnt * sizeof(T));
     }
append() [4/6]
template<size_t Size> void ByteBuffer::append (std::array< uint8, Size > const & arr) inline
Definition at line 488 of file ByteBuffer.h.
     {
         append(arr.data(), Size);
     }
References Acore::Size().
append() [5/6]
template<typename T > void ByteBuffer::append (T value) inline
Definition at line 129 of file ByteBuffer.h.
     {
         static_assert(std::is_fundamental<T>::value, "append(compound)");
         EndianConvert(value);
         append((uint8*)&value, sizeof(value));
     }
References EndianConvert().
Referenced by UpdateData::AddUpdateBlock(), AddonHandler::BuildAddonPacket(), UpdateData::BuildPacket(), Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleGameObjectQueryOpcode(), WorldSession::HandleRequestAccountData(), WorldSocket::HandleSendAuthSession(), WardenWin::InitializeModule(), AuthSession::LogonChallengeCallback(), lfg::LFGMgr::RBPacketBuildDifference(), lfg::LFGMgr::RBPacketBuildFull(), AuthSession::RealmListCallback(), AuthSession::ReconnectChallengeCallback(), WardenMac::RequestChecks(), WardenWin::RequestChecks(), WardenMac::RequestHash(), WardenWin::RequestHash(), Warden::RequestModule(), WorldSession::SendAddonsInfo(), Spell::SendLogExecute(), Warden::SendModuleToClient(), GmTicket::SendResponse(), Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), and Movement::PacketBuilder::WriteCreate().
append() [6/6]
void ByteBuffer::append (uint8 const * src, size_t cnt)
Definition at line 110 of file ByteBuffer.cpp.
 {
     ASSERT(src, "Attempted to put a NULL-pointer in ByteBuffer (pos: " SZFMTD " size: " SZFMTD ")", _wpos, size());
     ASSERT(cnt, "Attempted to put a zero-sized value in ByteBuffer (pos: " SZFMTD " size: " SZFMTD ")", _wpos, size());
     ASSERT(size() < 10000000);
     size_t const newSize = _wpos + cnt;
     if (_storage.capacity() < newSize) // custom memory allocation rules
     {
         if (newSize < 100)
             _storage.reserve(300);
         else if (newSize < 750)
             _storage.reserve(2500);
         else if (newSize < 6000)
             _storage.reserve(10000);
         else
             _storage.reserve(400000);
     }
     if (_storage.size() < newSize)
         _storage.resize(newSize);
     std::memcpy(&_storage[_wpos], src, cnt);
     _wpos = newSize;
 }
References _storage, _wpos, ASSERT, size(), and SZFMTD.
AppendPackedTime()
void ByteBuffer::AppendPackedTime (time_t time)
Definition at line 137 of file ByteBuffer.cpp.
 {
     tm lt;
     localtime_r(&time, &lt);
     append<uint32>((lt.tm_year - 100) << 24 | lt.tm_mon << 20 | (lt.tm_mday - 1) << 14 | lt.tm_wday << 11 | lt.tm_hour << 6 | lt.tm_min);
 }
References localtime_r().
Referenced by AchievementMgr::BuildAllDataPacket(), CalendarEvent::BuildCalendarMailBody(), WorldSession::HandleCalendarGetCalendar(), AchievementMgr::SendAchievementEarned(), AuctionHouseMgr::SendAuctionSalePendingMail(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventRemovedAlert(), CalendarMgr::SendCalendarEventStatus(), CalendarMgr::SendCalendarEventUpdateAlert(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), AchievementMgr::SendCriteriaUpdate(), Guild::SendInfo(), and Player::SendInitialPacketsBeforeAddToMap().
appendPackGUID()
void ByteBuffer::appendPackGUID (uint64 guid) inline
Definition at line 503 of file ByteBuffer.h.
     {
         uint8 packGUID[8 + 1];
         packGUID[0] = 0;
         size_t size = 1;
         for (uint8 i = 0; guid != 0;++i)
         {
             if (guid & 0xFF)
             {
                 packGUID[0] |= uint8(1 << i);
                 packGUID[size] =  uint8(guid & 0xFF);
                 ++size;
             }
             guid >>= 8;
         }
         append(packGUID, size);
     }
Referenced by AchievementMgr::BuildAllDataPacket(), Guild::MassInviteToEvent(), PackedGuid::PackedGuid(), AchievementMgr::SendCriteriaUpdate(), Player::SendEquipmentSetList(), PackedGuid::Set(), and Player::SetEquipmentSet().
appendPackXYZ()
void ByteBuffer::appendPackXYZ (float x, float y, float z) inline
Definition at line 494 of file ByteBuffer.h.
     {
         uint32 packed = 0;
         packed |= ((int)(x / 0.25f) & 0x7FF);
         packed |= ((int)(y / 0.25f) & 0x7FF) << 11;
         packed |= ((int)(z / 0.25f) & 0x3FF) << 22;
         *this << packed;
     }
Referenced by Movement::WriteLinearPath().
clear()
void ByteBuffer::clear () inline
Definition at line 122 of file ByteBuffer.h.
     {
         _storage.clear();
         _rpos = _wpos = 0;
     }
Referenced by UpdateData::Clear(), WorldSession::HandleCalendarGetCalendar(), WorldPacket::Initialize(), Channel::Invite(), Channel::LeaveChannel(), Map::SendObjectUpdates(), and lfg::LFGMgr::UpdateRaidBrowser().
contents() [1/2]
uint8* ByteBuffer::contents () inline
Definition at line 424 of file ByteBuffer.h.
     {
         if (_storage.empty())
         {
             throw ByteBufferException();
         }
         return _storage.data();
     }
Referenced by append(), AddonHandler::BuildAddonPacket(), UpdateData::BuildPacket(), WardenWin::HandleData(), WorldSession::HandleGMTicketCreateOpcode(), WardenMac::HandleHashResult(), WardenWin::HandleHashResult(), AuthSession::HandleLogonProof(), WorldSession::HandleRequestAccountData(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleWardenDataOpcode(), PacketLog::LogPacket(), WorldSession::ReadAddonsInfo(), WardenMac::RequestChecks(), AuthSession::SendPacket(), and WorldSocket::Update().
contents() [2/2]
uint8 const* ByteBuffer::contents () const inline
Definition at line 434 of file ByteBuffer.h.
     {
         if (_storage.empty())
         {
             throw ByteBufferException();
         }
         return _storage.data();
     }
empty()
bool ByteBuffer::empty () const inline
Definition at line 445 of file ByteBuffer.h.
 { return _storage.empty(); }
Referenced by UpdateData::BuildPacket(), WorldSession::HandleRaidReadyCheckOpcode(), WorldSession::HandleWardenDataOpcode(), PacketLog::LogPacket(), AuthSession::SendPacket(), and WorldSocket::Update().
hexlike()
void ByteBuffer::hexlike () const
Definition at line 189 of file ByteBuffer.cpp.
 {
     if (!sLog->ShouldLog("network.opcode.buffer", LogLevel::LOG_LEVEL_TRACE)) // optimize disabled trace output
         return;
     uint32 j = 1, k = 1;
     std::ostringstream o;
     o << "STORAGE_SIZE: " << size();
     for (uint32 i = 0; i < size(); ++i)
     {
         char buf[4];
         snprintf(buf, 4, "%2X ", read<uint8>(i));
         if ((i == (j * 8)) && ((i != (k * 16))))
         {
             o << "| ";
             ++j;
         }
         else if (i == (k * 16))
         {
             o << "\n";
             ++k;
             ++j;
         }
         o << buf;
     }
     o << " ";
     LOG_TRACE("network.opcode.buffer", "%s", o.str().c_str());
 }
References LOG_LEVEL_TRACE, LOG_TRACE, size(), and sLog.
Referenced by debug_commandscript::HandleDebugSendOpcodeCommand(), WorldSession::HandleWardenDataOpcode(), WardenMac::RequestChecks(), and WorldSession::Update().
operator<<() [1/14]
ByteBuffer& ByteBuffer::operator<< (bool value) inline
Definition at line 144 of file ByteBuffer.h.
     {
         append<uint8>(value ? 1 : 0);
         return *this;
     }
operator<<() [2/14]
ByteBuffer& ByteBuffer::operator<< (char const * str) inline
Definition at line 228 of file ByteBuffer.h.
     {
         return operator<<(std::string_view(str ? str : ""));
     }
References operator<<().
operator<<() [3/14]
ByteBuffer& ByteBuffer::operator<< (double value) inline
Definition at line 206 of file ByteBuffer.h.
     {
         append<double>(value);
         return *this;
     }
operator<<() [4/14]
ByteBuffer& ByteBuffer::operator<< (float value) inline
Definition at line 200 of file ByteBuffer.h.
     {
         append<float>(value);
         return *this;
     }
operator<<() [5/14]
ByteBuffer& ByteBuffer::operator<< (int16 value) inline
Definition at line 181 of file ByteBuffer.h.
     {
         append<int16>(value);
         return *this;
     }
operator<<() [6/14]
ByteBuffer& ByteBuffer::operator<< (int32 value) inline
Definition at line 187 of file ByteBuffer.h.
     {
         append<int32>(value);
         return *this;
     }
operator<<() [7/14]
ByteBuffer& ByteBuffer::operator<< (int64 value) inline
Definition at line 193 of file ByteBuffer.h.
     {
         append<int64>(value);
         return *this;
     }
operator<<() [8/14]
ByteBuffer& ByteBuffer::operator<< (int8 value) inline
Definition at line 175 of file ByteBuffer.h.
     {
         append<int8>(value);
         return *this;
     }
operator<<() [9/14]
ByteBuffer& ByteBuffer::operator<< (std::string const & str) inline
Definition at line 223 of file ByteBuffer.h.
     {
         return operator<<(std::string_view(str));
     }
References operator<<().
operator<<() [10/14]
ByteBuffer& ByteBuffer::operator<< (std::string_view value) inline
Definition at line 212 of file ByteBuffer.h.
     {
         if (size_t len = value.length())
         {
             append(reinterpret_cast<uint8 const*>(value.data()), len);
         }
         append(static_cast<uint8>(0));
         return *this;
     }
operator<<() [11/14]
ByteBuffer& ByteBuffer::operator<< (uint16 value) inline
Definition at line 156 of file ByteBuffer.h.
     {
         append<uint16>(value);
         return *this;
     }
operator<<() [12/14]
ByteBuffer& ByteBuffer::operator<< (uint32 value) inline
Definition at line 162 of file ByteBuffer.h.
     {
         append<uint32>(value);
         return *this;
     }
operator<<() [13/14]
ByteBuffer& ByteBuffer::operator<< (uint64 value) inline
Definition at line 168 of file ByteBuffer.h.
     {
         append<uint64>(value);
         return *this;
     }
operator<<() [14/14]
ByteBuffer& ByteBuffer::operator<< (uint8 value) inline
Definition at line 150 of file ByteBuffer.h.
     {
         append<uint8>(value);
         return *this;
     }
operator=() [1/2]
ByteBuffer& ByteBuffer::operator= (ByteBuffer && right) inline noexcept
Definition at line 108 of file ByteBuffer.h.
     {
         if (this != &right)
         {
             _rpos = right._rpos;
             right._rpos = 0;
             _wpos = right._wpos;
             right._wpos = 0;
             _storage = std::move(right._storage);
         }
         return *this;
     }
References _rpos.
operator=() [2/2]
ByteBuffer& ByteBuffer::operator= (ByteBuffer const & right) inline
Definition at line 96 of file ByteBuffer.h.
     {
         if (this != &right)
         {
             _rpos = right._rpos;
             _wpos = right._wpos;
             _storage = right._storage;
         }
         return *this;
     }
References _rpos, _storage, and _wpos.
Referenced by WorldPacket::operator=().
operator>>() [1/12]
ByteBuffer& ByteBuffer::operator>> (bool & value) inline
Definition at line 233 of file ByteBuffer.h.
     {
         value = read<char>() > 0;
         return *this;
     }
operator>>() [2/12]
ByteBuffer & ByteBuffer::operator>> (double & value)
Definition at line 67 of file ByteBuffer.cpp.
 {
     value = read<double>();
     if (!std::isfinite(value))
         throw ByteBufferInvalidValueException("double", "infinity");
     return *this;
 }
operator>>() [3/12]
ByteBuffer & ByteBuffer::operator>> (float & value)
Definition at line 57 of file ByteBuffer.cpp.
 {
     value = read<float>();
     if (!std::isfinite(value))
         throw ByteBufferInvalidValueException("float", "infinity");
     return *this;
 }
operator>>() [4/12]
ByteBuffer& ByteBuffer::operator>> (int16 & value) inline
Definition at line 270 of file ByteBuffer.h.
     {
         value = read<int16>();
         return *this;
     }
operator>>() [5/12]
ByteBuffer& ByteBuffer::operator>> (int32 & value) inline
Definition at line 276 of file ByteBuffer.h.
     {
         value = read<int32>();
         return *this;
     }
operator>>() [6/12]
ByteBuffer& ByteBuffer::operator>> (int64 & value) inline
Definition at line 282 of file ByteBuffer.h.
     {
         value = read<int64>();
         return *this;
     }
operator>>() [7/12]
ByteBuffer& ByteBuffer::operator>> (int8 & value) inline
Definition at line 264 of file ByteBuffer.h.
     {
         value = read<int8>();
         return *this;
     }
operator>>() [8/12]
ByteBuffer& ByteBuffer::operator>> (std::string & value) inline
Definition at line 291 of file ByteBuffer.h.
     {
         value = ReadCString(true);
         return *this;
     }
operator>>() [9/12]
ByteBuffer& ByteBuffer::operator>> (uint16 & value) inline
Definition at line 245 of file ByteBuffer.h.
     {
         value = read<uint16>();
         return *this;
     }
operator>>() [10/12]
ByteBuffer& ByteBuffer::operator>> (uint32 & value) inline
Definition at line 251 of file ByteBuffer.h.
     {
         value = read<uint32>();
         return *this;
     }
operator>>() [11/12]
ByteBuffer& ByteBuffer::operator>> (uint64 & value) inline
Definition at line 257 of file ByteBuffer.h.
     {
         value = read<uint64>();
         return *this;
     }
operator>>() [12/12]
ByteBuffer& ByteBuffer::operator>> (uint8 & value) inline
Definition at line 239 of file ByteBuffer.h.
     {
         value = read<uint8>();
         return *this;
     }
operator[]() [1/2]
uint8& ByteBuffer::operator[] (size_t const pos) inline
Definition at line 297 of file ByteBuffer.h.
     {
         if (pos >= size())
         {
             throw ByteBufferPositionException(false, pos, 1, size());
         }
         return _storage[pos];
     }
operator[]() [2/2]
uint8 const& ByteBuffer::operator[] (size_t const pos) const inline
Definition at line 307 of file ByteBuffer.h.
     {
         if (pos >= size())
         {
             throw ByteBufferPositionException(false, pos, 1, size());
         }
         return _storage[pos];
     }
print_storage()
void ByteBuffer::print_storage () const
Definition at line 153 of file ByteBuffer.cpp.
 {
     if (!sLog->ShouldLog("network.opcode.buffer", LogLevel::LOG_LEVEL_TRACE)) // optimize disabled trace output
         return;
     std::ostringstream o;
     o << "STORAGE_SIZE: " << size();
     for (uint32 i = 0; i < size(); ++i)
         o << read<uint8>(i) << " - ";
     o << " ";
     LOG_TRACE("network.opcode.buffer", "%s", o.str().c_str());
 }
References LOG_LEVEL_TRACE, LOG_TRACE, size(), and sLog.
Referenced by WorldSession::LogUnprocessedTail().
put() [1/2]
void ByteBuffer::put (size_t pos, const uint8 * src, size_t cnt)
Definition at line 144 of file ByteBuffer.cpp.
 {
     ASSERT(pos + cnt <= size(), "Attempted to put value with size: " SZFMTD " in ByteBuffer (pos: " SZFMTD " size: " SZFMTD ")", cnt, pos, size());
     ASSERT(src, "Attempted to put a NULL-pointer in ByteBuffer (pos: " SZFMTD " size: " SZFMTD ")", pos, size());
     ASSERT(cnt, "Attempted to put a zero-sized value in ByteBuffer (pos: " SZFMTD " size: " SZFMTD ")", pos, size());
     std::memcpy(&_storage[pos], src, cnt);
 }
References _storage, ASSERT, size(), and SZFMTD.
put() [2/2]
template<typename T > void ByteBuffer::put (std::size_t pos, T value) inline
Definition at line 137 of file ByteBuffer.h.
     {
         static_assert(std::is_fundamental<T>::value, "append(compound)");
         EndianConvert(value);
         put(pos, (uint8*)&value, sizeof(value));
     }
References EndianConvert().
Referenced by Guild::_SendBankList(), BattlegroundMgr::BuildBattlegroundListPacket(), Player::BuildEnchantmentsInfoData(), UpdateData::BuildPacket(), Player::BuildPetTalentsInfoData(), Player::BuildPlayerTalentsInfoData(), BattlegroundMgr::BuildPvpLogDataPacket(), AuctionListItemsDelayEvent::Execute(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionListOwnerItemsEvent(), WorldSession::HandleCharEnum(), WorldSession::HandleGetMailList(), WorldSession::HandleQueryNextMailTime(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleWhoOpcode(), Channel::List(), Guild::MassInviteToEvent(), CreatureTextLocalizer< Builder >::operator()(), Player::PetSpellInitialize(), AchievementMgr::SendAchievementEarned(), Player::SendEquipmentSetList(), Player::SendInitialSpells(), Player::SendInitWorldStates(), WorldSession::SendListInventory(), PlayerMenu::SendQuestGiverQuestList(), Player::SendQuestGiverStatusMultiple(), Player::SendRaidInfo(), PlayerSocial::SendSocialList(), WorldSession::SendStablePetCallback(), ReputationMgr::SendState(), WorldSession::SendTrainerList(), Guild::BankTab::WritePacket(), Guild::BankTab::WriteSlotPacket(), and Spell::WriteSpellGoTargets().
read() [1/4]
template<typename T > T ByteBuffer::read () inline
Definition at line 351 of file ByteBuffer.h.
     {
         T r = read<T>(_rpos);
         _rpos += sizeof(T);
         return r;
     }
Referenced by WorldSocket::HandleAuthSession(), WorldSession::HandleClientCastFlags(), WardenMac::HandleData(), WardenWin::HandleData(), WorldSession::HandleQuestPOIQuery(), operator>>(), WorldPackets::operator>>(), and AuctionHouseMgr::SendAuctionSalePendingMail().
read() [2/4]
template<typename T > T ByteBuffer::read (size_t pos) const inline
Definition at line 358 of file ByteBuffer.h.
     {
         if (pos + sizeof(T) > size())
         {
             throw ByteBufferPositionException(false, pos, sizeof(T), size());
         }
         T val = *((T const*)&_storage[pos]);
         EndianConvert(val);
         return val;
     }
References EndianConvert().
read() [3/4]
template<size_t Size> void ByteBuffer::read (std::array< uint8, Size > & arr) inline
Definition at line 382 of file ByteBuffer.h.
     {
         read(arr.data(), Size);
     }
References Acore::Size().
read() [4/4]
void ByteBuffer::read (uint8 * dest, size_t len) inline
Definition at line 370 of file ByteBuffer.h.
     {
         if (_rpos  + len > size())
         {
             throw ByteBufferPositionException(false, _rpos, len, size());
         }
         std::memcpy(dest, &_storage[_rpos], len);
         _rpos += len;
     }
read_skip() [1/4]
template<typename T > void ByteBuffer::read_skip () inline
Definition at line 339 of file ByteBuffer.h.
 { read_skip(sizeof(T)); }
References read_skip().
Referenced by WorldSession::HandleAuctionListPendingSales(), WorldSession::HandleBattlefieldLeaveOpcode(), WorldSession::HandleCancelCastOpcode(), WorldSession::HandleCancelChanneling(), WardenWin::HandleData(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleItemNameQueryOpcode(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleMailDelete(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMoveHoverAck(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMoveSetCanFlyAckOpcode(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleMoveWaterWalkAck(), WorldSession::HandlePageTextQueryOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetActiveVoiceChannel(), WorldSession::HandleShowingCloakOpcode(), WorldSession::HandleShowingHelmOpcode(), WorldSession::HandleVoiceSessionEnableOpcode(), and read_skip().
read_skip() [2/4]
template<> void ByteBuffer::read_skip () inline
Definition at line 545 of file ByteBuffer.h.
 {
     std::string temp;
     *this >> temp;
 }
read_skip() [3/4]
template<> void ByteBuffer::read_skip () inline
Definition at line 552 of file ByteBuffer.h.
 {
     read_skip<char*>();
 }
read_skip() [4/4]
void ByteBuffer::read_skip (size_t skip) inline
Definition at line 341 of file ByteBuffer.h.
     {
         if (_rpos + skip > size())
         {
             throw ByteBufferPositionException(false, _rpos, skip, size());
         }
         _rpos += skip;
     }
ReadCString()
std::string ByteBuffer::ReadCString (bool requireValidUtf8 = true)
Definition at line 77 of file ByteBuffer.cpp.
 {
     std::string value;
     while (rpos() < size()) // prevent crash at wrong string format in packet
     {
         char c = read<char>();
         if (c == 0)
             break;
         value += c;
     }
     if (requireValidUtf8 && !utf8::is_valid(value.begin(), value.end()))
         throw ByteBufferInvalidValueException("string", value.c_str());
     return value;
 }
References rpos(), and size().
Referenced by WorldSession::HandleMessagechatOpcode().
ReadPackedTime() [1/2]
uint32 ByteBuffer::ReadPackedTime ()
Definition at line 95 of file ByteBuffer.cpp.
 {
     uint32 packedDate = read<uint32>();
     tm lt = tm();
     lt.tm_min = packedDate & 0x3F;
     lt.tm_hour = (packedDate >> 6) & 0x1F;
     //lt.tm_wday = (packedDate >> 11) & 7;
     lt.tm_mday = ((packedDate >> 14) & 0x3F) + 1;
     lt.tm_mon = (packedDate >> 20) & 0xF;
     lt.tm_year = ((packedDate >> 24) & 0x1F) + 100;
     return uint32(mktime(&lt));
 }
Referenced by WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarCopyEvent(), and WorldSession::HandleCalendarUpdateEvent().
ReadPackedTime() [2/2]
ByteBuffer& ByteBuffer::ReadPackedTime (uint32 & time) inline
Definition at line 418 of file ByteBuffer.h.
     {
         time = ReadPackedTime();
         return *this;
     }
readPackGUID()
void ByteBuffer::readPackGUID (uint64 & guid) inline
Definition at line 387 of file ByteBuffer.h.
     {
         if (rpos() + 1 > size())
         {
             throw ByteBufferPositionException(false, _rpos, 1, size());
         }
         guid = 0;
         uint8 guidmark = 0;
         (*this) >> guidmark;
         for (int i = 0; i < 8; ++i)
         {
             if (guidmark & (uint8(1) << i))
             {
                 if (rpos() + 1 > size())
                 {
                     throw ByteBufferPositionException(false, _rpos, 1, size());
                 }
                 uint8 bit;
                 (*this) >> bit;
                 guid |= (uint64(bit) << (i * 8));
             }
         }
     }
Referenced by WorldSession::HandleEquipmentSetDelete(), WorldSession::HandleEquipmentSetSave(), and operator>>().
reserve()
void ByteBuffer::reserve (size_t ressize) inline
Definition at line 454 of file ByteBuffer.h.
     {
         if (ressize > size())
         {
             _storage.reserve(ressize);
         }
     }
resize()
void ByteBuffer::resize (size_t newsize) inline
Definition at line 447 of file ByteBuffer.h.
     {
         _storage.resize(newsize, 0);
         _rpos = 0;
         _wpos = size();
     }
Referenced by AddonHandler::BuildAddonPacket(), UpdateData::BuildPacket(), WorldSession::HandleGMTicketCreateOpcode(), AuthSession::HandleLogonProof(), WorldSession::HandleRequestAccountData(), WorldSession::HandleUpdateAccountData(), Acore::LocalizedPacketDo< Builder >::operator()(), and WorldSession::ReadAddonsInfo().
rfinish()
void ByteBuffer::rfinish () inline
Definition at line 325 of file ByteBuffer.h.
     {
         _rpos = wpos();
     }
Referenced by WorldSession::HandleActivateTaxiExpressOpcode(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarRemoveEvent(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharFactionOrRaceChange(), WardenWin::HandleData(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleEjectPassenger(), WorldSession::HandleFeatherFallAck(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleLearnPreviewTalents(), WorldSession::HandleLearnPreviewTalentsPet(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveSetCanFlyAckOpcode(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleQuestPOIQuery(), WorldSession::HandleSendMail(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUpdateMissileTrajectory(), and validUtf8String().
rpos() [1/2]
size_t ByteBuffer::rpos () const inline
Definition at line 317 of file ByteBuffer.h.
 { return _rpos; }
Referenced by AddonHandler::BuildAddonPacket(), WorldSocket::HandleAuthSession(), WardenWin::HandleData(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGuildRankOpcode(), WardenMac::HandleHashResult(), WardenWin::HandleHashResult(), WorldSession::HandleUpdateAccountData(), WorldSession::LogUnprocessedTail(), WorldSession::ReadAddonsInfo(), and ReadCString().
rpos() [2/2]
size_t ByteBuffer::rpos (size_t rpos_) inline
Definition at line 319 of file ByteBuffer.h.
     {
         _rpos = rpos_;
         return _rpos;
     }
shrink_to_fit()
void ByteBuffer::shrink_to_fit () inline
Definition at line 462 of file ByteBuffer.h.
     {
         _storage.shrink_to_fit();
     }
size()
size_t ByteBuffer::size () const inline
Definition at line 444 of file ByteBuffer.h.
 { return _storage.size(); }
Referenced by append(), AddonHandler::BuildAddonPacket(), WorldSession::HandleAuctionListBidderItems(), WorldSocket::HandleAuthSession(), WorldSession::HandleCastSpellOpcode(), WardenWin::HandleData(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetSetAction(), WorldSession::HandleTogglePvP(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWardenDataOpcode(), hexlike(), PacketLog::LogPacket(), print_storage(), put(), WorldSession::ReadAddonsInfo(), ReadCString(), AuthSession::RealmListCallback(), WardenMac::RequestChecks(), AuthSession::SendPacket(), WorldSession::SendPacket(), PackedGuid::size(), textlike(), and WorldSocket::Update().
textlike()
void ByteBuffer::textlike () const
Definition at line 169 of file ByteBuffer.cpp.
 {
     if (!sLog->ShouldLog("network.opcode.buffer", LogLevel::LOG_LEVEL_TRACE)) // optimize disabled trace output
         return;
     std::ostringstream o;
     o << "STORAGE_SIZE: " << size();
     for (uint32 i = 0; i < size(); ++i)
     {
         char buf[2];
         snprintf(buf, 2, "%c", read<uint8>(i));
         o << buf;
     }
     o << " ";
     LOG_TRACE("network.opcode.buffer", "%s", o.str().c_str());
 }
References LOG_LEVEL_TRACE, LOG_TRACE, size(), and sLog.
wpos() [1/2]
size_t ByteBuffer::wpos () const inline
Definition at line 330 of file ByteBuffer.h.
 { return _wpos; }
Referenced by Guild::_SendBankList(), append(), BattlegroundMgr::BuildBattlegroundListPacket(), ChatHandler::BuildChatPacket(), Player::BuildEnchantmentsInfoData(), UpdateData::BuildPacket(), Player::BuildPetTalentsInfoData(), Player::BuildPlayerTalentsInfoData(), BattlegroundMgr::BuildPvpLogDataPacket(), WardenWin::HandleData(), WorldSession::HandleGetMailList(), WorldSession::HandleGuildRankOpcode(), WardenMac::HandleHashResult(), WardenWin::HandleHashResult(), WorldSession::HandleRequestPartyMemberStatsOpcode(), Channel::List(), WorldSession::LogUnprocessedTail(), Player::PetSpellInitialize(), AchievementMgr::SendAchievementEarned(), Player::SendEquipmentSetList(), Player::SendInitialSpells(), Player::SendInitWorldStates(), WorldSession::SendListInventory(), WorldSession::SendPacket(), PlayerMenu::SendQuestGiverQuestList(), Player::SendRaidInfo(), PlayerSocial::SendSocialList(), WorldSession::SendStablePetCallback(), ReputationMgr::SendState(), WorldSession::SendTrainerList(), PackedGuid::Set(), Guild::BankTab::WritePacket(), Guild::BankTab::WriteSlotPacket(), and Spell::WriteSpellGoTargets().
wpos() [2/2]
size_t ByteBuffer::wpos (size_t wpos_) inline
Definition at line 332 of file ByteBuffer.h.
     {
         _wpos = wpos_;
         return _wpos;
     }
Member Data Documentation
_rpos
size_t ByteBuffer::_rpos protected
Definition at line 531 of file ByteBuffer.h.
Referenced by operator=().
_storage
std::vector<uint8> ByteBuffer::_storage protected
Definition at line 532 of file ByteBuffer.h.
Referenced by append(), WorldPacket::Initialize(), operator=(), and put().
_wpos
size_t ByteBuffer::_wpos protected
Definition at line 531 of file ByteBuffer.h.
Referenced by append(), and operator=().
DEFAULT_SIZE
constexpr static size_t ByteBuffer::DEFAULT_SIZE = 0x1000 static constexpr
Definition at line 72 of file ByteBuffer.h.
The documentation for this class was generated from the following files:
src/server/shared/Packets/ByteBuffer.h
src/server/shared/Packets/ByteBuffer.cpp