Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/ckh.h File Reference
ckh.h File Reference
#include "jemalloc/internal/tsd.h"
Classes
struct ckhc_t
struct ckh_t
Macros
#define LG_CKH_BUCKET_CELLS (LG_CACHELINE - LG_SIZEOF_PTR - 1)
Typedefs
typedef void ckh_hash_t(const void *, size_t[2])
typedef bool ckh_keycomp_t(const void *, const void *)
Functions
bool ckh_new (tsd_t *tsd, ckh_t *ckh, size_t minitems, ckh_hash_t *hash, ckh_keycomp_t *keycomp)
void ckh_delete (tsd_t *tsd, ckh_t *ckh)
size_t ckh_count (ckh_t *ckh)
bool ckh_iter (ckh_t *ckh, size_t *tabind, void **key, void **data)
bool ckh_insert (tsd_t *tsd, ckh_t *ckh, const void *key, const void *data)
bool ckh_remove (tsd_t *tsd, ckh_t *ckh, const void *searchkey, void **key, void **data)
bool ckh_search (ckh_t *ckh, const void *searchkey, void **key, void **data)
void ckh_string_hash (const void *key, size_t r_hash[2])
bool ckh_string_keycomp (const void *k1, const void *k2)
void ckh_pointer_hash (const void *key, size_t r_hash[2])
bool ckh_pointer_keycomp (const void *k1, const void *k2)
Macro Definition Documentation
LG_CKH_BUCKET_CELLS
#define LG_CKH_BUCKET_CELLS (LG_CACHELINE - LG_SIZEOF_PTR - 1)
Definition at line 21 of file ckh.h.
Typedef Documentation
ckh_hash_t
typedef void ckh_hash_t(const void *, size_t[2])
Definition at line 24 of file ckh.h.
ckh_keycomp_t
typedef bool ckh_keycomp_t(const void *, const void *)
Definition at line 25 of file ckh.h.
Function Documentation
ckh_count()
size_t ckh_count (ckh_t * ckh)
Definition at line 439 of file ckh.c.
                       {
     assert(ckh != NULL);
     return ckh->count;
 }
References assert(), ckh_t::count, and NULL.
ckh_delete()
void ckh_delete (tsd_t * tsd, ckh_t * ckh)
Definition at line 417 of file ckh.c.
{
     assert(ckh != NULL);
 #ifdef CKH_VERBOSE
     malloc_printf(
         "%s(%p): ngrows: %"FMTu64", nshrinks: %"FMTu64","
         " nshrinkfails: %"FMTu64", ninserts: %"FMTu64","
         " nrelocs: %"FMTu64"\n", __func__, ckh,
         (unsigned long long)ckh->ngrows,
         (unsigned long long)ckh->nshrinks,
         (unsigned long long)ckh->nshrinkfails,
         (unsigned long long)ckh->ninserts,
         (unsigned long long)ckh->nrelocs);
 #endif
     idalloctm(tsd_tsdn(tsd), ckh->tab, NULL, NULL, true, true);
     if (config_debug) {
         memset(ckh, JEMALLOC_FREE_JUNK, sizeof(ckh_t));
     }
 }
References __func__, assert(), config_debug, FMTu64, idalloctm(), JEMALLOC_FREE_JUNK, malloc_printf, memset, NULL, ckh_t::tab, and tsd_tsdn().
ckh_insert()
bool ckh_insert (tsd_t * tsd, ckh_t * ckh, const void * key, const void * data)
Definition at line 467 of file ckh.c.
{
     bool ret;
     assert(ckh != NULL);
     assert(ckh_search(ckh, key, NULL, NULL));
 #ifdef CKH_COUNT
     ckh->ninserts++;
 #endif
     while (ckh_try_insert(ckh, &key, &data)) {
         if (ckh_grow(tsd, ckh)) {
             ret = true;
             goto label_return;
         }
     }
     ret = false;
 label_return:
     return ret;
 }
References assert(), ckh_grow(), ckh_search(), ckh_try_insert(), NULL, and ret.
ckh_iter()
bool ckh_iter (ckh_t * ckh, size_t * tabind, void ** key, void ** data)
Definition at line 446 of file ckh.c.
{
     size_t i, ncells;
     for (i = *tabind, ncells = (ZU(1) << (ckh->lg_curbuckets +
         LG_CKH_BUCKET_CELLS)); i < ncells; i++) {
         if (ckh->tab[i].key != NULL) {
             if (key != NULL) {
                 *key = (void *)ckh->tab[i].key;
             }
             if (data != NULL) {
                 *data = (void *)ckh->tab[i].data;
             }
             *tabind = i + 1;
             return false;
         }
     }
     return true;
 }
References ckhc_t::data, ckhc_t::key, LG_CKH_BUCKET_CELLS, ckh_t::lg_curbuckets, NULL, ckh_t::tab, and ZU.
ckh_new()
bool ckh_new (tsd_t * tsd, ckh_t * ckh, size_t minitems, ckh_hash_t * hash, ckh_keycomp_t * keycomp)
Definition at line 360 of file ckh.c.
{
     bool ret;
     size_t mincells, usize;
     unsigned lg_mincells;
     assert(minitems > 0);
     assert(hash != NULL);
     assert(keycomp != NULL);
 #ifdef CKH_COUNT
     ckh->ngrows = 0;
     ckh->nshrinks = 0;
     ckh->nshrinkfails = 0;
     ckh->ninserts = 0;
     ckh->nrelocs = 0;
 #endif
     ckh->prng_state = 42; /* Value doesn't really matter. */
     ckh->count = 0;
     /*
      * Find the minimum power of 2 that is large enough to fit minitems
      * entries.  We are using (2+,2) cuckoo hashing, which has an expected
      * maximum load factor of at least ~0.86, so 0.75 is a conservative load
      * factor that will typically allow mincells items to fit without ever
      * growing the table.
      */
     assert(LG_CKH_BUCKET_CELLS > 0);
     mincells = ((minitems + (3 - (minitems % 3))) / 3) << 2;
     for (lg_mincells = LG_CKH_BUCKET_CELLS;
         (ZU(1) << lg_mincells) < mincells;
         lg_mincells++) {
         /* Do nothing. */
     }
     ckh->lg_minbuckets = lg_mincells - LG_CKH_BUCKET_CELLS;
     ckh->lg_curbuckets = lg_mincells - LG_CKH_BUCKET_CELLS;
     ckh->hash = hash;
     ckh->keycomp = keycomp;
     usize = sz_sa2u(sizeof(ckhc_t) << lg_mincells, CACHELINE);
     if (unlikely(usize == 0 || usize > SC_LARGE_MAXCLASS)) {
         ret = true;
         goto label_return;
     }
     ckh->tab = (ckhc_t *)ipallocztm(tsd_tsdn(tsd), usize, CACHELINE, true,
         NULL, true, arena_ichoose(tsd, NULL));
     if (ckh->tab == NULL) {
         ret = true;
         goto label_return;
     }
     ret = false;
 label_return:
     return ret;
 }
References arena_ichoose(), assert(), CACHELINE, ckh_t::count, ckh_t::hash, hash(), ipallocztm(), ckh_t::keycomp, LG_CKH_BUCKET_CELLS, ckh_t::lg_curbuckets, ckh_t::lg_minbuckets, NULL, ckh_t::prng_state, ret, SC_LARGE_MAXCLASS, sz_sa2u(), ckh_t::tab, tsd_tsdn(), unlikely, and ZU.
ckh_pointer_hash()
void ckh_pointer_hash (const void * key, size_t r_hash[2])
Definition at line 556 of file ckh.c.
{
     union {
         const void  *v;
         size_t      i;
     } u;
     assert(sizeof(u.v) == sizeof(u.i));
     u.v = key;
     hash(&u.i, sizeof(u.i), 0xd983396eU, r_hash);
 }
References assert(), and hash().
ckh_pointer_keycomp()
bool ckh_pointer_keycomp (const void * k1, const void * k2)
Definition at line 568 of file ckh.c.
{
     return (k1 == k2);
 }
ckh_remove()
bool ckh_remove (tsd_t * tsd, ckh_t * ckh, const void * searchkey, void ** key, void ** data)
Definition at line 490 of file ckh.c.
                  {
     size_t cell;
     assert(ckh != NULL);
     cell = ckh_isearch(ckh, searchkey);
     if (cell != SIZE_T_MAX) {
         if (key != NULL) {
             *key = (void *)ckh->tab[cell].key;
         }
         if (data != NULL) {
             *data = (void *)ckh->tab[cell].data;
         }
         ckh->tab[cell].key = NULL;
         ckh->tab[cell].data = NULL; /* Not necessary. */
         ckh->count--;
         /* Try to halve the table if it is less than 1/4 full. */
         if (ckh->count < (ZU(1) << (ckh->lg_curbuckets
             + LG_CKH_BUCKET_CELLS - 2)) && ckh->lg_curbuckets
             > ckh->lg_minbuckets) {
             /* Ignore error due to OOM. */
             ckh_shrink(tsd, ckh);
         }
         return false;
     }
     return true;
 }
References assert(), ckh_isearch(), ckh_shrink(), ckh_t::count, ckhc_t::data, ckhc_t::key, LG_CKH_BUCKET_CELLS, ckh_t::lg_curbuckets, ckh_t::lg_minbuckets, NULL, SIZE_T_MAX, ckh_t::tab, and ZU.
ckh_search()
bool ckh_search (ckh_t * ckh, const void * searchkey, void ** key, void ** data)
Definition at line 523 of file ckh.c.
{
     size_t cell;
     assert(ckh != NULL);
     cell = ckh_isearch(ckh, searchkey);
     if (cell != SIZE_T_MAX) {
         if (key != NULL) {
             *key = (void *)ckh->tab[cell].key;
         }
         if (data != NULL) {
             *data = (void *)ckh->tab[cell].data;
         }
         return false;
     }
     return true;
 }
References assert(), ckh_isearch(), ckhc_t::data, ckhc_t::key, NULL, SIZE_T_MAX, and ckh_t::tab.
Referenced by ckh_insert().
ckh_string_hash()
void ckh_string_hash (const void * key, size_t r_hash[2])
Definition at line 543 of file ckh.c.
{
     hash(key, strlen((const char *)key), 0x94122f33U, r_hash);
 }
References hash().
ckh_string_keycomp()
bool ckh_string_keycomp (const void * k1, const void * k2)
Definition at line 548 of file ckh.c.
{
     assert(k1 != NULL);
     assert(k2 != NULL);
     return !strcmp((char *)k1, (char *)k2);
 }
References assert(), and NULL.