Azerotcore-wotlk: boss_volkhan::boss_volkhanAI Struct Reference
boss_volkhan::boss_volkhanAI Struct Reference
Public Member Functions
boss_volkhanAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void GetNextPos ()
void KilledUnit (Unit *victim) override
void ScheduleEvents (bool anvil)
void JustSummoned (Creature *summon) override
void DoAction (int32 param) override
void MovementInform (uint32 type, uint32 id) override
void SpellHitTarget (Unit *, const SpellInfo *spellInfo) override
void GoToAnvil ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 HealthCheck
float x
float y
float z
uint8 PointID
uint8 ShatteredCount
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 91 of file boss_volkhan.cpp.
Constructor & Destructor Documentation
boss_volkhanAI()
boss_volkhan::boss_volkhanAI::boss_volkhanAI (Creature * creature) inline
Definition at line 93 of file boss_volkhan.cpp.
                                            : ScriptedAI(creature), summons(creature)
         {
             m_pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
DoAction()
void boss_volkhan::boss_volkhanAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 213 of file boss_volkhan.cpp.
         {
             if (param == ACTION_DESTROYED)
             {
                 ShatteredCount++;
                 if (ShatteredCount > 4)
                     m_pInstance->SetData(DATA_VOLKHAN_ACHIEVEMENT, false);
             }
         }
References ACTION_DESTROYED, DATA_VOLKHAN_ACHIEVEMENT, m_pInstance, ZoneScript::SetData(), and ShatteredCount.
EnterCombat()
void boss_volkhan::boss_volkhanAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 122 of file boss_volkhan.cpp.
         {
             me->SetInCombatWithZone();
             Talk(SAY_AGGRO);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_VOLKHAN, IN_PROGRESS);
             ScheduleEvents(false);
         }
References IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_AGGRO, ScheduleEvents(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and TYPE_VOLKHAN.
GetNextPos()
void boss_volkhan::boss_volkhanAI::GetNextPos () inline
Definition at line 143 of file boss_volkhan.cpp.
         {
             if (me->GetPositionY() < -180)
             {
                 if (me->GetPositionX() > 1330)
                     x = 1355;
                 else
                     x = 1308;
                 y = -178;
                 z = 52.5f;
             }
             else if (me->GetPositionY() < -145)
             {
                 if (me->GetPositionX() > 1330)
                     x = 1355;
                 else
                     x = 1308;
                 y = -137;
                 z = 52.5f;
             }
             else if (me->GetPositionY() < -130)
             {
                 if (me->GetPositionX() > 1330)
                     x = 1343;
                 else
                     x = 1320;
                 y = -123;
                 z = 56.7f;
             }
             else
             {
                 PointID = POINT_ANVIL;
                 x = 1327;
                 y = -96;
                 z = 56.7f;
             }
         }
References Position::GetPositionX(), Position::GetPositionY(), ScriptedAI::me, POINT_ANVIL, PointID, x, y, and z.
Referenced by UpdateAI().
GoToAnvil()
void boss_volkhan::boss_volkhanAI::GoToAnvil () inline
Definition at line 260 of file boss_volkhan.cpp.
         {
             events.SetPhase(2);
             HealthCheck -= 20;
             me->SetSpeed(MOVE_RUN, 4.0f, true);
             me->SetReactState(REACT_PASSIVE);
             Talk(SAY_FORGE);
             if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE)
                 me->GetMotionMaster()->MovementExpired();
             events.ScheduleEvent(EVENT_MOVE_TO_ANVIL, 0, 0, 2);
         }
References CHASE_MOTION_TYPE, EVENT_MOVE_TO_ANVIL, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), HealthCheck, ScriptedAI::me, MOVE_RUN, MotionMaster::MovementExpired(), REACT_PASSIVE, SAY_FORGE, Creature::SetReactState(), Unit::SetSpeed(), and CreatureAI::Talk().
Referenced by UpdateAI().
JustDied()
void boss_volkhan::boss_volkhanAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 133 of file boss_volkhan.cpp.
         {
             Talk(SAY_DEATH);
             summons.DespawnAll();
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_VOLKHAN, DONE);
         }
References SummonList::DespawnAll(), DONE, m_pInstance, SAY_DEATH, ZoneScript::SetData(), summons, CreatureAI::Talk(), and TYPE_VOLKHAN.
JustSummoned()
void boss_volkhan::boss_volkhanAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 201 of file boss_volkhan.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_MOLTEN_GOLEM)
             {
                 summon->SetFaction(me->GetFaction());
                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                     summon->AI()->AttackStart(target);
             }
         }
References Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), Unit::GetFaction(), ScriptedAI::me, NPC_MOLTEN_GOLEM, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetFaction(), SummonList::Summon(), and summons.
KilledUnit()
void boss_volkhan::boss_volkhanAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 184 of file boss_volkhan.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_volkhan::boss_volkhanAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 223 of file boss_volkhan.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (id == POINT_ANVIL)
             {
                 me->SetSpeed(MOVE_RUN, 1.2f, true);
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->CastSpell(me, SPELL_TEMPER, false);
                 PointID = 0;
                 ScheduleEvents(true);
                 // update orientation at server
                 me->SetOrientation(2.19f);
                 // and client
                 WorldPacket data;
                 me->BuildHeartBeatMsg(&data);
                 me->SendMessageToSet(&data, false);
                 me->SetControlled(true, UNIT_STATE_ROOT);
             }
             else
                 events.ScheduleEvent(EVENT_MOVE_TO_ANVIL, 0, 0, 2);
         }
References Unit::BuildHeartBeatMsg(), Unit::CastSpell(), EVENT_MOVE_TO_ANVIL, ScriptedAI::me, MOVE_RUN, POINT_ANVIL, POINT_MOTION_TYPE, PointID, REACT_AGGRESSIVE, ScheduleEvents(), WorldObject::SendMessageToSet(), Unit::SetControlled(), Position::SetOrientation(), Creature::SetReactState(), Unit::SetSpeed(), SPELL_TEMPER, and UNIT_STATE_ROOT.
Reset()
void boss_volkhan::boss_volkhanAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 106 of file boss_volkhan.cpp.
         {
             x = y = z = PointID = ShatteredCount = 0;
             HealthCheck = 100;
             events.Reset();
             summons.DespawnAll();
             me->SetSpeed(MOVE_RUN, 1.2f, true);
             me->SetReactState(REACT_AGGRESSIVE);
             if (m_pInstance)
             {
                 m_pInstance->SetData(TYPE_VOLKHAN, NOT_STARTED);
                 m_pInstance->SetData(DATA_VOLKHAN_ACHIEVEMENT, true);
             }
         }
References DATA_VOLKHAN_ACHIEVEMENT, SummonList::DespawnAll(), HealthCheck, m_pInstance, ScriptedAI::me, MOVE_RUN, NOT_STARTED, PointID, REACT_AGGRESSIVE, ZoneScript::SetData(), Creature::SetReactState(), Unit::SetSpeed(), ShatteredCount, summons, TYPE_VOLKHAN, x, y, and z.
ScheduleEvents()
void boss_volkhan::boss_volkhanAI::ScheduleEvents (bool anvil) inline
Definition at line 192 of file boss_volkhan.cpp.
         {
             events.SetPhase(1);
             events.RescheduleEvent(EVENT_HEAT, 8000, 0, 1);
             events.RescheduleEvent(EVENT_SHATTER, 10000, 0, 1);
             events.RescheduleEvent(EVENT_CHECK_HEALTH, anvil ? 1000 : 6000, 0, 1);
             events.RescheduleEvent(EVENT_POSITION, 4000, 0, 1);
         }
References EVENT_CHECK_HEALTH, EVENT_HEAT, EVENT_POSITION, and EVENT_SHATTER.
Referenced by EnterCombat(), and MovementInform().
SpellHitTarget()
void boss_volkhan::boss_volkhanAI::SpellHitTarget (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 249 of file boss_volkhan.cpp.
         {
             if (spellInfo->Id == SPELL_TEMPER)
             {
                 me->CastSpell(me, SPELL_SUMMON_MOLTEN_GOLEM, true);
                 me->CastSpell(me, SPELL_SUMMON_MOLTEN_GOLEM, true);
                 me->GetMotionMaster()->MoveChase(me->GetVictim());
                 me->SetControlled(false, UNIT_STATE_ROOT);
             }
         }
References Unit::CastSpell(), Unit::GetMotionMaster(), Unit::GetVictim(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveChase(), Unit::SetControlled(), SPELL_SUMMON_MOLTEN_GOLEM, SPELL_TEMPER, and UNIT_STATE_ROOT.
UpdateAI()
void boss_volkhan::boss_volkhanAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 275 of file boss_volkhan.cpp.
         {
             //Return since we have no target
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_HEAT:
                     me->CastSpell(me, me->GetMap()->IsHeroic() ? SPELL_HEAT_H : SPELL_HEAT_N, true);
                     events.RepeatEvent(8000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (HealthBelowPct(HealthCheck))
                         GoToAnvil();
                     events.RepeatEvent(1000);
                     return;
                 case EVENT_SHATTER:
                     {
                         events.RepeatEvent(10000);
                         summons.DoAction(ACTION_SHATTER);
                         break;
                     }
                 case EVENT_MOVE_TO_ANVIL:
                     GetNextPos();
                     me->GetMotionMaster()->MovePoint(PointID, x, y, z);
                     return;
                 case EVENT_POSITION:
                     if (me->GetDistance(1331.9f, -106, 56) > 95)
                         EnterEvadeMode();
                     else
                         events.RepeatEvent(4000);
                     return;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_SHATTER, Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_HEALTH, EVENT_HEAT, EVENT_MOVE_TO_ANVIL, EVENT_POSITION, EVENT_SHATTER, WorldObject::GetDistance(), WorldObject::GetMap(), Unit::GetMotionMaster(), GetNextPos(), GoToAnvil(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), HealthCheck, Map::IsHeroic(), ScriptedAI::me, MotionMaster::MovePoint(), PointID, SPELL_HEAT_H, SPELL_HEAT_N, summons, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), x, y, and z.
Member Data Documentation
events
EventMap boss_volkhan::boss_volkhanAI::events
Definition at line 99 of file boss_volkhan.cpp.
HealthCheck
uint8 boss_volkhan::boss_volkhanAI::HealthCheck
Definition at line 101 of file boss_volkhan.cpp.
Referenced by GoToAnvil(), Reset(), and UpdateAI().
m_pInstance
InstanceScript* boss_volkhan::boss_volkhanAI::m_pInstance
Definition at line 98 of file boss_volkhan.cpp.
Referenced by boss_volkhanAI(), DoAction(), EnterCombat(), JustDied(), and Reset().
PointID
uint8 boss_volkhan::boss_volkhanAI::PointID
Definition at line 103 of file boss_volkhan.cpp.
Referenced by GetNextPos(), MovementInform(), Reset(), and UpdateAI().
ShatteredCount
uint8 boss_volkhan::boss_volkhanAI::ShatteredCount
Definition at line 104 of file boss_volkhan.cpp.
Referenced by DoAction(), and Reset().
summons
SummonList boss_volkhan::boss_volkhanAI::summons
Definition at line 100 of file boss_volkhan.cpp.
Referenced by JustDied(), JustSummoned(), Reset(), and UpdateAI().
x
float boss_volkhan::boss_volkhanAI::x
Definition at line 102 of file boss_volkhan.cpp.
Referenced by GetNextPos(), Reset(), and UpdateAI().
y
float boss_volkhan::boss_volkhanAI::y
Definition at line 102 of file boss_volkhan.cpp.
Referenced by GetNextPos(), Reset(), and UpdateAI().
z
float boss_volkhan::boss_volkhanAI::z
Definition at line 102 of file boss_volkhan.cpp.
Referenced by GetNextPos(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp