Azerotcore-wotlk: src/server/game/AI/ScriptedAI/ScriptedCreature.cpp File Reference
ScriptedCreature.cpp File Reference
#include "Cell.h"
#include "CellImpl.h"
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "ObjectMgr.h"
#include "ScriptedCreature.h"
#include "Spell.h"
#include "TemporarySummon.h"
Classes
struct TSpellSummary
Enumerations
enum eNPCs {
NPC_BROODLORD = 12017 , NPC_JAN_ALAI = 23578 , NPC_SARTHARION = 28860 , NPC_FREYA = 32906 ,
NPC_INGVAR_UNDEAD = 23980 , NPC_ANNHYLDE = 24068 , NPC_THROW = 23997 , NPC_FROST_TOMB = 23965 ,
NPC_SKELETON = 23970
}
Functions
Creature * GetClosestCreatureWithEntry (WorldObject *source, uint32 entry, float maxSearchRange, bool alive)
GameObject * GetClosestGameObjectWithEntry (WorldObject *source, uint32 entry, float maxSearchRange, bool onlySpawned)
void GetCreatureListWithEntryInGrid (std::list< Creature * > &list, WorldObject *source, uint32 entry, float maxSearchRange)
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &list, WorldObject *source, uint32 entry, float maxSearchRange)
void GetDeadCreatureListInGrid (std::list< Creature * > &list, WorldObject *source, float maxSearchRange, bool alive)
Variables
struct TSpellSummary * SpellSummary
Enumeration Type Documentation
eNPCs
enum eNPCs
Enumerator
NPC_BROODLORD
NPC_JAN_ALAI
NPC_SARTHARION
NPC_FREYA
NPC_INGVAR_UNDEAD
NPC_ANNHYLDE
NPC_THROW
NPC_FROST_TOMB
NPC_SKELETON
Definition at line 483 of file ScriptedCreature.cpp.
 {
     NPC_BROODLORD   = 12017,
     NPC_JAN_ALAI    = 23578,
     NPC_SARTHARION  = 28860,
     NPC_FREYA       = 32906,
 };
Function Documentation
GetClosestCreatureWithEntry()
Creature* GetClosestCreatureWithEntry (WorldObject * source, uint32 entry, float maxSearchRange, bool alive)
Definition at line 740 of file ScriptedCreature.cpp.
 {
     return source->FindNearestCreature(entry, maxSearchRange, alive);
 }
References WorldObject::FindNearestCreature().
Referenced by npc_mrfloppy::npc_mrfloppyAI::EnterCombat(), npc_mrfloppy::npc_mrfloppyAI::EnterEvadeMode(), SmartScript::GetTargets(), npc_emily::npc_emilyAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), Condition::Meets(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), go_naga_brazier::OnGossipHello(), go_elune_fire::OnGossipHello(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), go_amberpine_outhouse::OnGossipSelect(), npc_emily::OnQuestAccept(), at_ancient_leaf::OnTrigger(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), Map::ScriptsProcess(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_warmage_violetstand::npc_warmage_violetstandAI::UpdateAI(), npc_deaths_fel_cannon::npc_deaths_fel_cannonAI::UpdateAI(), and npc_emily::npc_emilyAI::WaypointReached().
GetClosestGameObjectWithEntry()
GameObject* GetClosestGameObjectWithEntry (WorldObject * source, uint32 entry, float maxSearchRange, bool onlySpawned)
Definition at line 745 of file ScriptedCreature.cpp.
 {
     return source->FindNearestGameObject(entry, maxSearchRange, onlySpawned);
 }
References WorldObject::FindNearestGameObject().
Referenced by npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), npc_firework::npc_fireworkAI::FindNearestLauncher(), SmartScript::GetTargets(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), Condition::Meets(), AreaTrigger_at_coilfang_waterfall::OnTrigger(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), npc_muglash::npc_muglashAI::WaypointReached(), and npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::WaypointReached().
GetCreatureListWithEntryInGrid()
void GetCreatureListWithEntryInGrid (std::list< Creature * > & list, WorldObject * source, uint32 entry, float maxSearchRange)
Definition at line 750 of file ScriptedCreature.cpp.
 {
     source->GetCreatureListWithEntryInGrid(list, entry, maxSearchRange);
 }
References WorldObject::GetCreatureListWithEntryInGrid().
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLichKingAvailability(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::EnterCombat(), boss_arlokk::boss_arlokkAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), npc_sindragosa_trash::npc_sindragosa_trashAI::EnterCombat(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), go_veil_skith_cage::OnGossipHello(), at_icc_saurfang_portal::OnTrigger(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::StoreTargets(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), and npc_warmage_violetstand::npc_warmage_violetstandAI::UpdateAI().
GetDeadCreatureListInGrid()
void GetDeadCreatureListInGrid (std::list< Creature * > & list, WorldObject * source, float maxSearchRange, bool alive)
Definition at line 760 of file ScriptedCreature.cpp.
 {
     source->GetDeadCreatureListInGrid(list, maxSearchRange, alive);
 }
References WorldObject::GetDeadCreatureListInGrid().
GetGameObjectListWithEntryInGrid()
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > & list, WorldObject * source, uint32 entry, float maxSearchRange)
Definition at line 755 of file ScriptedCreature.cpp.
 {
     source->GetGameObjectListWithEntryInGrid(list, entry, maxSearchRange);
 }
References WorldObject::GetGameObjectListWithEntryInGrid().
Referenced by boss_broodlord::boss_broodlordAI::JustDied(), npc_coren_direbrew::npc_coren_direbrewAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), and npc_ranshalla::npc_ranshallaAI::WaypointReached().
Variable Documentation
SpellSummary
struct TSpellSummary* SpellSummary
Referenced by ScriptedAI::SelectSpell().