Azerotcore-wotlk: PlayerTaxi Class Reference
PlayerTaxi Class Reference
#include <PlayerTaxi.h>
Public Member Functions
PlayerTaxi ()
~PlayerTaxi ()=default
void InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint8 level)
void LoadTaxiMask (std::string const &data)
bool IsTaximaskNodeKnown (uint32 nodeidx) const
bool SetTaximaskNode (uint32 nodeidx)
void AppendTaximaskTo (ByteBuffer &data, bool all)
bool LoadTaxiDestinationsFromString (std::string const &values, TeamId teamId)
std::string SaveTaxiDestinationsToString ()
void ClearTaxiDestinations ()
void AddTaxiDestination (uint32 dest)
uint32 GetTaxiSource () const
uint32 GetTaxiDestination () const
uint32 GetCurrentTaxiPath () const
uint32 NextTaxiDestination ()
void SetTaxiSegment (uint32 segment)
uint32 GetTaxiSegment () const
std::vector< uint32 > const & GetPath () const
bool empty () const
Private Attributes
TaxiMask m_taximask
std::vector< uint32 > m_TaxiDestinations
uint32 _taxiSegment
Friends
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
Detailed Description
Definition at line 18 of file PlayerTaxi.h.
Constructor & Destructor Documentation
PlayerTaxi()
PlayerTaxi::PlayerTaxi ()
Definition at line 20 of file PlayerTaxi.cpp.
                        : _taxiSegment(0)
 {
     memset(m_taximask, 0, sizeof(m_taximask));
 }
References m_taximask, and memset.
~PlayerTaxi()
PlayerTaxi::~PlayerTaxi () default
Member Function Documentation
AddTaxiDestination()
void PlayerTaxi::AddTaxiDestination (uint32 dest) inline
Definition at line 52 of file PlayerTaxi.h.
 { m_TaxiDestinations.push_back(dest); }
References m_TaxiDestinations.
Referenced by Player::ActivateTaxiPathTo(), Player::LoadFromDB(), LoadTaxiDestinationsFromString(), and Player::ProcessDelayedOperations().
AppendTaximaskTo()
void PlayerTaxi::AppendTaximaskTo (ByteBuffer & data, bool all)
Definition at line 105 of file PlayerTaxi.cpp.
 {
     if (all)
     {
         for (uint8 i = 0; i < TaxiMaskSize; i++)
             data << uint32(sTaxiNodesMask[i]);              // all existed nodes
     }
     else
     {
         for (uint8 i = 0; i < TaxiMaskSize; i++)
             data << uint32(m_taximask[i]);                  // known nodes
     }
 }
References G3D::all(), m_taximask, sTaxiNodesMask, and TaxiMaskSize.
Referenced by WorldSession::SendTaxiMenu().
ClearTaxiDestinations()
void PlayerTaxi::ClearTaxiDestinations () inline
Definition at line 51 of file PlayerTaxi.h.
 { m_TaxiDestinations.clear(); _taxiSegment = 0; }
References _taxiSegment, and m_TaxiDestinations.
Referenced by Player::ActivateTaxiPathTo(), Player::CleanupAfterTaxiFlight(), Player::ContinueTaxiFlight(), Player::LoadFromDB(), and LoadTaxiDestinationsFromString().
empty()
bool PlayerTaxi::empty () const inline
Definition at line 67 of file PlayerTaxi.h.
 { return m_TaxiDestinations.empty(); }
References m_TaxiDestinations.
Referenced by FlightPathMovementGenerator::DoFinalize(), and Player::SetEntryPoint().
GetCurrentTaxiPath()
uint32 PlayerTaxi::GetCurrentTaxiPath () const
Definition at line 169 of file PlayerTaxi.cpp.
 {
     if (m_TaxiDestinations.size() < 2 || m_TaxiDestinations.size() <= _taxiSegment + 1)
         return 0;
     uint32 path;
     uint32 cost;
     sObjectMgr->GetTaxiPath(m_TaxiDestinations[_taxiSegment], m_TaxiDestinations[_taxiSegment + 1], path, cost);
     return path;
 }
References _taxiSegment, m_TaxiDestinations, and sObjectMgr.
Referenced by Player::ContinueTaxiFlight().
GetPath()
std::vector<uint32> const& PlayerTaxi::GetPath () const inline
Definition at line 66 of file PlayerTaxi.h.
 { return m_TaxiDestinations; }
References m_TaxiDestinations.
Referenced by FlightPathMovementGenerator::LoadPath(), and Player::SetEntryPoint().
GetTaxiDestination()
uint32 PlayerTaxi::GetTaxiDestination () const inline
Definition at line 54 of file PlayerTaxi.h.
 { return m_TaxiDestinations.size() <= _taxiSegment + 1 ? 0 : m_TaxiDestinations[_taxiSegment + 1]; }
References _taxiSegment, and m_TaxiDestinations.
Referenced by NextTaxiDestination().
GetTaxiSegment()
uint32 PlayerTaxi::GetTaxiSegment () const inline
Definition at line 64 of file PlayerTaxi.h.
 { return _taxiSegment; }
References _taxiSegment.
Referenced by FlightPathMovementGenerator::LoadPath(), and Player::SetEntryPoint().
GetTaxiSource()
uint32 PlayerTaxi::GetTaxiSource () const inline
Definition at line 53 of file PlayerTaxi.h.
 { return m_TaxiDestinations.size() <= _taxiSegment + 1 ? 0 : m_TaxiDestinations[_taxiSegment]; }
References _taxiSegment, and m_TaxiDestinations.
Referenced by Player::ContinueTaxiFlight(), and LoadTaxiDestinationsFromString().
InitTaxiNodesForLevel()
void PlayerTaxi::InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint8 level)
Definition at line 25 of file PlayerTaxi.cpp.
 {
     // class specific initial known nodes
     switch (chrClass)
     {
         case CLASS_DEATH_KNIGHT:
         {
             for (uint8 i = 0; i < TaxiMaskSize; ++i)
                 m_taximask[i] |= sOldContinentsNodesMask[i];
             break;
         }
     }
     // race specific initial known nodes: capital and taxi hub masks
     switch (race)
     {
         case RACE_HUMAN:
             SetTaximaskNode(2);
             break;     // Human
         case RACE_ORC:
             SetTaximaskNode(23);
             break;     // Orc
         case RACE_DWARF:
             SetTaximaskNode(6);
             break;     // Dwarf
         case RACE_NIGHTELF:
             SetTaximaskNode(26);
             SetTaximaskNode(27);
             break;     // Night Elf
         case RACE_UNDEAD_PLAYER:
             SetTaximaskNode(11);
             break;// Undead
         case RACE_TAUREN:
             SetTaximaskNode(22);
             break;     // Tauren
         case RACE_GNOME:
             SetTaximaskNode(6);
             break;     // Gnome
         case RACE_TROLL:
             SetTaximaskNode(23);
             break;     // Troll
         case RACE_BLOODELF:
             SetTaximaskNode(82);
             break;     // Blood Elf
         case RACE_DRAENEI:
             SetTaximaskNode(94);
             break;     // Draenei
     }
     // new continent starting masks (It will be accessible only at new map)
     switch (Player::TeamIdForRace(race))
     {
         case TEAM_ALLIANCE:
             SetTaximaskNode(100);
             break;
         case TEAM_HORDE:
             SetTaximaskNode(99);
             break;
         default:
             break;
     }
     // level dependent taxi hubs
     if (level >= 68)
         SetTaximaskNode(213);                               //Shattered Sun Staging Area
 }
References CLASS_DEATH_KNIGHT, m_taximask, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD_PLAYER, SetTaximaskNode(), sOldContinentsNodesMask, TaxiMaskSize, TEAM_ALLIANCE, TEAM_HORDE, and Player::TeamIdForRace().
Referenced by Player::InitTaxiNodesForLevel().
IsTaximaskNodeKnown()
bool PlayerTaxi::IsTaximaskNodeKnown (uint32 nodeidx) const inline
Definition at line 27 of file PlayerTaxi.h.
     {
         uint8  field   = uint8((nodeidx - 1) / 32);
         uint32 submask = 1 << ((nodeidx - 1) % 32);
         return (m_taximask[field] & submask) == submask;
     }
References m_taximask.
LoadTaxiDestinationsFromString()
bool PlayerTaxi::LoadTaxiDestinationsFromString (std::string const & values, TeamId teamId)
Definition at line 119 of file PlayerTaxi.cpp.
 {
     ClearTaxiDestinations();
     Tokenizer tokens(values, ' ');
     for (Tokenizer::const_iterator iter = tokens.begin(); iter != tokens.end(); ++iter)
     {
         uint32 node = uint32(atol(*iter));
         AddTaxiDestination(node);
     }
     // Check integrity
     if (m_TaxiDestinations.size() < 3)
         return false;
     // xinef: current segment is saved as last destination in db
     _taxiSegment = m_TaxiDestinations[m_TaxiDestinations.size() - 1];
     m_TaxiDestinations.pop_back();
     for (size_t i = 0; i < m_TaxiDestinations.size() - 1; ++i)
     {
         uint32 cost;
         uint32 path;
         sObjectMgr->GetTaxiPath(m_TaxiDestinations[i], m_TaxiDestinations[i + 1], path, cost);
         if (!path)
             return false;
     }
     // can't load taxi path without mount set (quest taxi path?)
     if (!sObjectMgr->GetTaxiMountDisplayId(GetTaxiSource(), teamId, true))
         return false;
     return true;
 }
References _taxiSegment, AddTaxiDestination(), Tokenizer::begin(), ClearTaxiDestinations(), Tokenizer::end(), GetTaxiSource(), m_TaxiDestinations, and sObjectMgr.
Referenced by Player::LoadFromDB().
LoadTaxiMask()
void PlayerTaxi::LoadTaxiMask (std::string const & data)
Definition at line 91 of file PlayerTaxi.cpp.
 {
     Tokenizer tokens(data, ' ');
     uint8 index;
     Tokenizer::const_iterator iter;
     for (iter = tokens.begin(), index = 0;
          (index < TaxiMaskSize) && (iter != tokens.end()); ++iter, ++index)
     {
         // load and set bits only for existed taxi nodes
         m_taximask[index] = sTaxiNodesMask[index] & uint32(atol(*iter));
     }
 }
References Tokenizer::begin(), Tokenizer::end(), index, m_taximask, sTaxiNodesMask, and TaxiMaskSize.
Referenced by Player::LoadFromDB().
NextTaxiDestination()
uint32 PlayerTaxi::NextTaxiDestination () inline
Definition at line 56 of file PlayerTaxi.h.
     {
         ++_taxiSegment;
         return GetTaxiDestination();
     }
References _taxiSegment, and GetTaxiDestination().
Referenced by FlightPathMovementGenerator::DoUpdate().
SaveTaxiDestinationsToString()
std::string PlayerTaxi::SaveTaxiDestinationsToString ()
Definition at line 155 of file PlayerTaxi.cpp.
 {
     if (m_TaxiDestinations.empty())
         return "";
     std::ostringstream ss;
     for (size_t i = 0; i < m_TaxiDestinations.size(); ++i)
         ss << m_TaxiDestinations[i] << ' ';
     ss << _taxiSegment << ' ';
     return ss.str();
 }
References _taxiSegment, and m_TaxiDestinations.
Referenced by Player::_SaveCharacter().
SetTaximaskNode()
bool PlayerTaxi::SetTaximaskNode (uint32 nodeidx) inline
Definition at line 33 of file PlayerTaxi.h.
     {
         uint8  field   = uint8((nodeidx - 1) / 32);
         uint32 submask = 1 << ((nodeidx - 1) % 32);
         if ((m_taximask[field] & submask) != submask)
         {
             m_taximask[field] |= submask;
             return true;
         }
         else
             return false;
     }
References m_taximask.
Referenced by InitTaxiNodesForLevel().
SetTaxiSegment()
void PlayerTaxi::SetTaxiSegment (uint32 segment) inline
Definition at line 63 of file PlayerTaxi.h.
 { _taxiSegment = segment; }
References _taxiSegment.
Referenced by Player::LoadFromDB(), and Player::ProcessDelayedOperations().
Friends And Related Function Documentation
operator<<
std::ostringstream& operator<< (std::ostringstream & ss, PlayerTaxi const & taxi) friend
Definition at line 182 of file PlayerTaxi.cpp.
 {
     for (uint8 i = 0; i < TaxiMaskSize; ++i)
         ss << taxi.m_taximask[i] << ' ';
     return ss;
 }
Member Data Documentation
_taxiSegment
uint32 PlayerTaxi::_taxiSegment private
Definition at line 73 of file PlayerTaxi.h.
Referenced by ClearTaxiDestinations(), GetCurrentTaxiPath(), GetTaxiDestination(), GetTaxiSegment(), GetTaxiSource(), LoadTaxiDestinationsFromString(), NextTaxiDestination(), SaveTaxiDestinationsToString(), and SetTaxiSegment().
m_TaxiDestinations
std::vector<uint32> PlayerTaxi::m_TaxiDestinations private
Definition at line 72 of file PlayerTaxi.h.
Referenced by AddTaxiDestination(), ClearTaxiDestinations(), empty(), GetCurrentTaxiPath(), GetPath(), GetTaxiDestination(), GetTaxiSource(), LoadTaxiDestinationsFromString(), and SaveTaxiDestinationsToString().
m_taximask
TaxiMask PlayerTaxi::m_taximask private
Definition at line 71 of file PlayerTaxi.h.
Referenced by AppendTaximaskTo(), InitTaxiNodesForLevel(), IsTaximaskNodeKnown(), LoadTaxiMask(), PlayerTaxi(), and SetTaximaskNode().
The documentation for this class was generated from the following files:
src/server/game/Entities/Player/PlayerTaxi.h
src/server/game/Entities/Player/PlayerTaxi.cpp