Azerotcore-wotlk: G3D::Color3 Class Reference
G3D::Color3 Class Reference
#include <Color3.h>
Public Member Functions
Color3 ()
Initializes to all zero.
bool nonZero () const
Color3 (const Any &any)
Color3 & operator= (const Any &a)
Any toAny () const
Color3 (class BinaryInput &bi)
Color3 (float r, float g, float b)
Color3 (float v)
Initializes all channels to v.
Color3 (const class Vector3 &v)
Color3 (const float value[3])
const Color3 & rgb () const
Color3 (const Color3 &other)
Color3 (const class Color3unorm8 &other)
bool isZero () const
bool isOne () const
bool isFinite () const
void serialize (class BinaryOutput &bo) const
void deserialize (class BinaryInput &bi)
const float & operator[] (int i) const
float & operator[] (int i)
Color3 & operator= (const Color3 &rkVector)
bool operator== (const Color3 &rkVector) const
bool operator!= (const Color3 &rkVector) const
size_t hashCode () const
Color3 operator+ (const Color3 &rkVector) const
Color3 operator- (const Color3 &rkVector) const
Color3 operator* (float s) const
Color3 operator/ (const Color3 &rkVector) const
Color3 operator* (const Color3 &rkVector) const
Color3 operator/ (float fScalar) const
Color3 operator- () const
Color3 & operator+= (const Color3 &rkVector)
Color3 & operator-= (const Color3 &rkVector)
Color3 & operator*= (const Color3 &rkVector)
Color3 & operator*= (float fScalar)
Color3 & operator/= (float fScalar)
bool fuzzyEq (const Color3 &other) const
bool fuzzyNe (const Color3 &other) const
float length () const
Color3 direction () const
float squaredLength () const
float dot (const Color3 &rkVector) const
float unitize (float fTolerance=1e-06f)
Color3 cross (const Color3 &rkVector) const
Color3 unitCross (const Color3 &rkVector) const
Color3 pow (const Color3 &other) const
Color3 pow (float other) const
Color3 max (const Color3 &other) const
Color3 min (const Color3 &other) const
float min () const
float max () const
Color3 lerp (const Color3 &other, float a) const
float sum () const
float average () const
std::string toString () const
Color3 bgr () const
Static Public Member Functions
static Color3 fromARGB (uint32)
static Color3 fromASRGB (uint32)
static const Color3 & wheelRandom ()
static Color3 ansiMap (uint32 i)
static Color3 pastelMap (uint32 i)
static Color3 fromHSV (const Vector3 &_hsv)
static Vector3 toHSV (const Color3 &_rgb)
static Color3 jetColorMap (const float &val)
static Color3 rainbowColorMap (float hue)
static Color3 random ()
static const Color3 & red ()
static const Color3 & green ()
static const Color3 & blue ()
static const Color3 & purple ()
static const Color3 & cyan ()
static const Color3 & yellow ()
static const Color3 & brown ()
static const Color3 & orange ()
static const Color3 & black ()
static const Color3 & gray ()
static const Color3 & white ()
static const Color3 & zero ()
static const Color3 & one ()
Public Attributes
float r
float g
float b
Private Member Functions
bool operator< (const Color3 &) const
bool operator> (const Color3 &) const
bool operator<= (const Color3 &) const
bool operator>= (const Color3 &) const
Detailed Description
Do not subclass– this implementation makes assumptions about the memory layout.
Definition at line 33 of file Color3.h.
Constructor & Destructor Documentation
Color3() [1/9]
G3D::Color3::Color3 () inline
Initializes to all zero.
Definition at line 45 of file Color3.h.
 : r(0), g(0), b(0) {}
Referenced by bgr(), cross(), fromARGB(), fromASRGB(), fromHSV(), max(), min(), operator*(), operator+(), operator-(), operator/(), operator=(), pow(), and random().
Color3() [2/9]
G3D::Color3::Color3 (const Any & any) explicit
Parameters
any Must be in one of the following forms:
Color3(#, #, #)
Color3(#)
Color3::fromARGB(#)
Color3::fromASRGB(#)
Color3{r = #, g = #, b = #)
Color3::one()
Color3::zero()
In the current implementation, G3D::Power3, G3D::Radiance3, and G3D::Irradiance3 are typedefs for Color3, so Color3 accepts "Power3" and "Radiance3" as a prefixes as well, e.g., Power3(1,0,0).
Definition at line 31 of file Color3.cpp.
{
     *this = Color3::zero();
     any.verifyNameBeginsWith("Color3", "Power3", "Radiance3", "Irradiance3", "Energy3", "Radiosity3", "Biradiance3");
     switch (any.type()) {
     case Any::TABLE:
         for (Any::AnyTable::Iterator it = any.table().begin(); it.isValid(); ++it) {
             const std::string& key = toLower(it->key);
             if (key == "r") {
                 r = it->value;
             } else if (key == "g") {
                 g = it->value;
             } else if (key == "b") {
                 b = it->value;
             } else {
                 any.verify(false, "Illegal key: " + it->key);
             }
         }
         break;
     case Any::ARRAY: // Intentionally falls through
     case Any::EMPTY_CONTAINER:
         {
             const std::string& name = any.name();
             std::string factoryName;
             size_t i = name.find("::");
             if (i != std::string::npos && i > 1) {
                 factoryName = name.substr(i + 2);
             }
             if (factoryName == "") {
                 if (any.size() == 1) {
                     r = g = b = any[0];
                 } else {
                     any.verifySize(3);
                     r = any[0];
                     g = any[1];
                     b = any[2];
                 }
             } else if (factoryName == "one") {
                 any.verifySize(0);
                 *this = one();
             } else if (factoryName == "zero") {
                 any.verifySize(0);
                 *this = zero();
             } else if (factoryName == "fromARGB") {
                 *this = Color3::fromARGB((int)any[0].number());
             } else if (factoryName == "fromASRGB") {
                 *this = Color3::fromASRGB((int)any[0].number());
             } else {
                 any.verify(false, "Expected Color3 constructor");
             }
         }
         break;
     default:
         any.verify(false, "Bad Color3 constructor");
     }
 }
References G3D::any(), G3D::Any::ARRAY, b, G3D::Any::EMPTY_CONTAINER, fromARGB(), fromASRGB(), g, one(), r, G3D::Any::TABLE, G3D::toLower(), and zero().
Color3() [3/9]
G3D::Color3::Color3 (class BinaryInput & bi) explicit
Definition at line 203 of file Color3.cpp.
{
     deserialize(bi);
 }
References deserialize().
Color3() [4/9]
G3D::Color3::Color3 (float r, float g, float b) inline
Definition at line 294 of file Color3.h.
{
     r = fX;
     g = fY;
     b = fZ;
 }
References b, g, and r.
Color3() [5/9]
G3D::Color3::Color3 (float v) inline explicit
Initializes all channels to v.
Definition at line 77 of file Color3.h.
 : r(v), g(v), b(v) {}
Color3() [6/9]
G3D::Color3::Color3 (const class Vector3 & v) explicit
Color3() [7/9]
G3D::Color3::Color3 (const float value[3]) inline explicit
Definition at line 301 of file Color3.h.
{
     r = afCoordinate[0];
     g = afCoordinate[1];
     b = afCoordinate[2];
 }
References b, g, and r.
Color3() [8/9]
G3D::Color3::Color3 (const Color3 & other) inline
Initialize from another color.
Definition at line 308 of file Color3.h.
{
     r = rkVector.r;
     g = rkVector.g;
     b = rkVector.b;
 }
References b, g, and r.
Color3() [9/9]
G3D::Color3::Color3 (const class Color3unorm8 & other)
Definition at line 248 of file Color3.cpp.
                                               : r(other.r), g(other.g), b(other.b) {
 }
Member Function Documentation
ansiMap()
Color3 G3D::Color3::ansiMap (uint32 i) static
Generate colors according to the ANSI color set, mod 16.
See also
pastelMap
Definition at line 100 of file Color3.cpp.
{
     static const Color3 map[] =
         {Color3::black(), Color3::red() * 0.75f, Color3::green() * 0.75f, Color3::yellow() * 0.75f,
          Color3::blue() * 0.75f, Color3::purple() * 0.75f, Color3::cyan() * 0.75f, Color3::white() * 0.75f,
          Color3::white() * 0.90f, Color3::red(), Color3::green(), Color3::yellow(), Color3::blue(),
          Color3::purple(), Color3::cyan(), Color3::white()};
     return map[i & 15];
 }
References black(), blue(), cyan(), green(), purple(), red(), white(), and yellow().
average()
float G3D::Color3::average () const inline
Definition at line 229 of file Color3.h.
{
         return sum() / 3.0f;
     }
References sum().
bgr()
Color3 G3D::Color3::bgr () const inline
Definition at line 270 of file Color3.h.
{
         return Color3(b, g, r);
     }
References b, Color3(), g, and r.
black()
const Color3 & G3D::Color3::black () static
Definition at line 169 of file Color3.cpp.
{
     static Color3 c(0.0f, 0.0f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), fromHSV(), G3D::Image3::Image3(), and G3D::Image3uint8::Image3uint8().
blue()
const Color3 & G3D::Color3::blue () static
Definition at line 133 of file Color3.cpp.
{
     static Color3 c(0.0f, 0.0f, 1.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
brown()
const Color3 & G3D::Color3::brown () static
Definition at line 157 of file Color3.cpp.
{
     static Color3 c(0.5f, 0.5f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by wheelRandom().
cross()
Color3 G3D::Color3::cross (const Color3 & rkVector) const inline
Definition at line 434 of file Color3.h.
{
     return Color3(g*rkVector.b - b*rkVector.g, b*rkVector.r - r*rkVector.b,
                   r*rkVector.g - g*rkVector.r);
 }
References b, Color3(), g, and r.
cyan()
const Color3 & G3D::Color3::cyan () static
Definition at line 145 of file Color3.cpp.
{
     static Color3 c(0.0f, 0.7f, 1.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
deserialize()
void G3D::Color3::deserialize (class BinaryInput & bi)
Definition at line 208 of file Color3.cpp.
{
     r = bi.readFloat32();
     g = bi.readFloat32();
     b = bi.readFloat32();
 }
References b, g, r, and G3D::BinaryInput::readFloat32().
Referenced by Color3().
direction()
Color3 G3D::Color3::direction () const inline
Definition at line 418 of file Color3.h.
{
     float lenSquared = r * r + g * g + b * b;
     if (lenSquared != 1.0f) {
         return *this / sqrtf(lenSquared);
     } else {
         return *this;
     }
 }
References b, g, and r.
Referenced by unitCross().
dot()
float G3D::Color3::dot (const Color3 & rkVector) const inline
Definition at line 429 of file Color3.h.
{
     return r*rkVector.r + g*rkVector.g + b*rkVector.b;
 }
References b, g, and r.
fromARGB()
Color3 G3D::Color3::fromARGB (uint32 x) static
Initialize from an HTML-style color (e.g. 0xFF0000 == RED)
Definition at line 252 of file Color3.cpp.
{
     return Color3(Color3unorm8::fromARGB(x));
 }
References Color3(), and G3D::x.
Referenced by Color3().
fromASRGB()
Color3 G3D::Color3::fromASRGB (uint32 x) static
Initialize from an HTML-style color (e.g. 0xFF0000 == RED) by converting from sRGB to RGB.
Definition at line 256 of file Color3.cpp.
{
     return Color3(Color3unorm8::fromARGB(x)).pow(2.2f);
 }
References Color3(), and G3D::x.
Referenced by Color3().
fromHSV()
Color3 G3D::Color3::fromHSV (const Vector3 & _hsv) static
Converts from HSV to RGB , note: toHSV(fromHSV(_hsv)) may not be _hsv, if it is at a grey point or black point. The components of _hsv should lie in the unit interval. [Alvy] Ray Smith SIGGRAPH 1978 "Color Gamut Transform Pairs"
Definition at line 302 of file Color3.cpp.
{
     debugAssertM((_hsv.x <= 1.0f && _hsv.x >= 0.0f)
                  && (_hsv.y <= 1.0f && _hsv.y >= 0.0f)
                  && ( _hsv.z <= 1.0f && _hsv.z >= 0.0f), "H,S,V must be between [0,1]");
     const int i = iMin(5, G3D::iFloor(6.0 * _hsv.x));
     const float f = 6.0f * _hsv.x - i;
     const float m = _hsv.z * (1.0f - (_hsv.y));
     const float n = _hsv.z * (1.0f - (_hsv.y * f));
     const float k = _hsv.z * (1.0f - (_hsv.y * (1 - f)));
     switch(i) {
     case 0:
         return Color3(_hsv.z, k, m);
     case 1:
         return Color3(n, _hsv.z, m);
     case 2:
         return Color3(m, _hsv.z, k);
     case 3:
         return Color3(m, n, _hsv.z);
     case 4:
         return Color3(k, m, _hsv.z);
     case 5:
         return Color3(_hsv.z, m, n);
     default:
         debugAssertM(false, "fell through switch..");
     }
     return Color3::black();
 }
References black(), Color3(), debugAssertM, f(), G3D::iFloor(), G3D::iMin(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by pastelMap(), and rainbowColorMap().
fuzzyEq()
bool G3D::Color3::fuzzyEq (const Color3 & other) const inline
Definition at line 327 of file Color3.h.
{
     return G3D::fuzzyEq((*this - other).squaredLength(), 0);
 }
References G3D::fuzzyEq(), and squaredLength().
fuzzyNe()
bool G3D::Color3::fuzzyNe (const Color3 & other) const inline
Definition at line 333 of file Color3.h.
{
     return G3D::fuzzyNe((*this - other).squaredLength(), 0);
 }
References G3D::fuzzyNe(), and squaredLength().
gray()
const Color3 & G3D::Color3::gray () static
Definition at line 186 of file Color3.cpp.
{
     static Color3 c(0.7f, 0.7f, 0.7f);
     return c;
 }
References mpq::c.
green()
const Color3 & G3D::Color3::green () static
Definition at line 127 of file Color3.cpp.
{
     static Color3 c(0.0f, 1.0f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
hashCode()
size_t G3D::Color3::hashCode () const
Definition at line 232 of file Color3.cpp.
{
     unsigned int rhash = (*(int*)(void*)(&r));
     unsigned int ghash = (*(int*)(void*)(&g));
     unsigned int bhash = (*(int*)(void*)(&b));
     return rhash + (ghash * 37) + (bhash * 101);
 }
References b, g, and r.
Referenced by HashTrait< G3D::Color3 >::hashCode().
isFinite()
bool G3D::Color3::isFinite () const
Definition at line 198 of file Color3.cpp.
{
     return G3D::isFinite(r) && G3D::isFinite(g) && G3D::isFinite(b);
 }
References b, g, G3D::isFinite(), and r.
isOne()
bool G3D::Color3::isOne () const inline
Definition at line 99 of file Color3.h.
{
         return (r == 1.0f) && (g == 1.0f) && (b == 1.0f);
     }
References b, g, and r.
isZero()
bool G3D::Color3::isZero () const inline
Definition at line 95 of file Color3.h.
{
         return (r == 0.0f) && (g == 0.0f) && (b == 0.0f);
     }
References b, g, and r.
jetColorMap()
Color3 G3D::Color3::jetColorMap (const float & val) static
Duplicates the matlab jet colormap maps [0,1] --> (r,g,b) where blue is close to 0 and red is close to 1.
Definition at line 372 of file Color3.cpp.
{
     debugAssertM(val <= 1.0f && val >= 0.0f , "value should be in [0,1]");
     //truncated triangles where sides have slope 4
     Color3 jet;
     jet.r = G3D::min(4.0f * val - 1.5f,-4.0f * val + 4.5f) ;
     jet.g = G3D::min(4.0f * val - 0.5f,-4.0f * val + 3.5f) ;
     jet.b = G3D::min(4.0f * val + 0.5f,-4.0f * val + 2.5f) ;
     jet.r = G3D::clamp(jet.r, 0.0f, 1.0f);
     jet.g = G3D::clamp(jet.g, 0.0f, 1.0f);
     jet.b = G3D::clamp(jet.b, 0.0f, 1.0f);
     return jet;
 }
References b, G3D::clamp(), debugAssertM, g, G3D::min(), and r.
length()
float G3D::Color3::length () const inline
Definition at line 413 of file Color3.h.
{
     return sqrtf(r*r + g*g + b*b);
 }
References b, g, and r.
Referenced by unitize().
lerp()
Color3 G3D::Color3::lerp (const Color3 & other, float a) const inline
Definition at line 220 of file Color3.h.
{
         return (*this) + (other - *this) * a;
     }
References mpq::a.
Referenced by G3D::lerp().
max() [1/2]
float G3D::Color3::max () const inline
Largest element
Definition at line 216 of file Color3.h.
{
         return G3D::max(G3D::max(r, g), b);
     }
References b, g, G3D::max(), and r.
max() [2/2]
Color3 G3D::Color3::max (const Color3 & other) const inline
Definition at line 202 of file Color3.h.
{
         return Color3(G3D::max(r, other.r), G3D::max(g, other.g), G3D::max(b, other.b));
     }
References b, Color3(), g, G3D::max(), and r.
Referenced by G3D::max().
min() [1/2]
float G3D::Color3::min () const inline
Smallest element
Definition at line 211 of file Color3.h.
{
         return G3D::min(G3D::min(r, g), b);
     }
References b, g, G3D::min(), and r.
min() [2/2]
Color3 G3D::Color3::min (const Color3 & other) const inline
Definition at line 206 of file Color3.h.
{
         return Color3(G3D::min(r, other.r), G3D::min(g, other.g), G3D::min(b, other.b));
     }
References b, Color3(), g, G3D::min(), and r.
Referenced by G3D::min().
nonZero()
bool G3D::Color3::nonZero () const inline
Definition at line 47 of file Color3.h.
{
         return (r != 0) || (g != 0) || (b != 0);
     }
References b, g, and r.
one()
const Color3 & G3D::Color3::one () static
Definition at line 180 of file Color3.cpp.
{
     static Color3 c(1.0f, 1.0f, 1.0f);
     return c;
 }
References mpq::c.
Referenced by Color3().
operator!=()
bool G3D::Color3::operator!= (const Color3 & rkVector) const inline
Definition at line 352 of file Color3.h.
{
     return ( r != rkVector.r || g != rkVector.g || b != rkVector.b );
 }
References b, g, and r.
operator*() [1/2]
Color3 G3D::Color3::operator* (const Color3 & rkVector) const inline
Definition at line 367 of file Color3.h.
{
     return Color3(r * rkVector.r, g  * rkVector.g, b * rkVector.b);
 }
References b, Color3(), g, and r.
operator*() [2/2]
Color3 G3D::Color3::operator* (float s) const inline
Definition at line 161 of file Color3.h.
{
         return Color3(r * s, g * s, b * s);
     }
References b, Color3(), g, and r.
operator*=() [1/2]
Color3 & G3D::Color3::operator*= (const Color3 & rkVector) inline
Definition at line 401 of file Color3.h.
{
     r *= rkVector.r;
     g *= rkVector.g;
     b *= rkVector.b;
     return *this;
 }
References b, g, and r.
operator*=() [2/2]
Color3 & G3D::Color3::operator*= (float fScalar) inline
Definition at line 393 of file Color3.h.
{
     r *= fScalar;
     g *= fScalar;
     b *= fScalar;
     return *this;
 }
References b, g, and r.
operator+()
Color3 G3D::Color3::operator+ (const Color3 & rkVector) const inline
Definition at line 357 of file Color3.h.
{
     return Color3(r + rkVector.r, g + rkVector.g, b + rkVector.b);
 }
References b, Color3(), g, and r.
operator+=()
Color3 & G3D::Color3::operator+= (const Color3 & rkVector) inline
Definition at line 377 of file Color3.h.
{
     r += rkVector.r;
     g += rkVector.g;
     b += rkVector.b;
     return *this;
 }
References b, g, and r.
operator-() [1/2]
Color3 G3D::Color3::operator- () const inline
Definition at line 372 of file Color3.h.
{
     return Color3( -r, -g, -b);
 }
References b, Color3(), g, and r.
operator-() [2/2]
Color3 G3D::Color3::operator- (const Color3 & rkVector) const inline
Definition at line 362 of file Color3.h.
{
     return Color3(r -rkVector.r, g - rkVector.g, b - rkVector.b);
 }
References b, Color3(), g, and r.
operator-=()
Color3 & G3D::Color3::operator-= (const Color3 & rkVector) inline
Definition at line 385 of file Color3.h.
{
     r -= rkVector.r;
     g -= rkVector.g;
     b -= rkVector.b;
     return *this;
 }
References b, g, and r.
operator/() [1/2]
Color3 G3D::Color3::operator/ (const Color3 & rkVector) const inline
Definition at line 164 of file Color3.h.
{
         return Color3(r / rkVector.r, g / rkVector.g, b / rkVector.b);
     }
References b, Color3(), g, and r.
operator/() [2/2]
Color3 G3D::Color3::operator/ (float fScalar) const inline
Definition at line 169 of file Color3.h.
{
         return (*this) * (1.0f / fScalar);
     }
operator/=()
Color3 & G3D::Color3::operator/= (float fScalar)
Definition at line 270 of file Color3.cpp.
{
     if (fScalar != 0.0f) {
         float fInvScalar = 1.0f / fScalar;
         r *= fInvScalar;
         g *= fInvScalar;
         b *= fInvScalar;
     } else {
         r = (float)G3D::finf();
         g = (float)G3D::finf();
         b = (float)G3D::finf();
     }
     return *this;
 }
References b, G3D::finf(), g, and r.
operator<()
bool G3D::Color3::operator< (const Color3 &) const private
operator<=()
bool G3D::Color3::operator<= (const Color3 &) const private
operator=() [1/2]
Color3 & G3D::Color3::operator= (const Any & a)
Definition at line 25 of file Color3.cpp.
{
     *this = Color3(a);
     return *this;
 }
References mpq::a, and Color3().
operator=() [2/2]
Color3 & G3D::Color3::operator= (const Color3 & rkVector) inline
Definition at line 339 of file Color3.h.
{
     r = rkVector.r;
     g = rkVector.g;
     b = rkVector.b;
     return *this;
 }
References b, g, and r.
operator==()
bool G3D::Color3::operator== (const Color3 & rkVector) const inline
Definition at line 347 of file Color3.h.
{
     return ( r == rkVector.r && g == rkVector.g && b == rkVector.b );
 }
References b, g, and r.
operator>()
bool G3D::Color3::operator> (const Color3 &) const private
operator>=()
bool G3D::Color3::operator>= (const Color3 &) const private
operator[]() [1/2]
float & G3D::Color3::operator[] (int i) inline
Definition at line 315 of file Color3.h.
{
     return ((float*)this)[i];
 }
operator[]() [2/2]
const float & G3D::Color3::operator[] (int i) const inline
Definition at line 321 of file Color3.h.
{
     return ((float*)this)[i];
 }
orange()
const Color3 & G3D::Color3::orange () static
Definition at line 163 of file Color3.cpp.
{
     static Color3 c(1.0f, 0.5f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by wheelRandom().
pastelMap()
Color3 G3D::Color3::pastelMap (uint32 i) static
Generate colors using a hash such that adjacent values are unlikely to have similar colors.
Useful for rendering with stable but arbitrary colors, e.g., when debugging a mesh algorithm.
See also
ansiMap
Definition at line 111 of file Color3.cpp.
{
     uint32 x = Crypto::crc32(&i, sizeof(uint32));
     // Create fairly bright, saturated colors
     Vector3 v(((x >> 22) & 1023) / 1023.0f,
               (((x >> 11) & 2047) / 2047.0f) * 0.5f + 0.25f,
               ((x & 2047) / 2047.0f) * 0.75f + 0.25f);
     return Color3::fromHSV(v);
 }
References G3D::Crypto::crc32(), fromHSV(), and G3D::x.
pow() [1/2]
Color3 G3D::Color3::pow (const Color3 & other) const inline
Definition at line 194 of file Color3.h.
{
         return Color3(::pow(r, other.r), ::pow(g, other.g), ::pow(b, other.b));
     }
References b, Color3(), g, and r.
Referenced by pow().
pow() [2/2]
Color3 G3D::Color3::pow (float other) const inline
Definition at line 198 of file Color3.h.
{
         return Color3(::pow(r, other), ::pow(g, other), ::pow(b, other));
     }
References b, Color3(), g, pow(), and r.
purple()
const Color3 & G3D::Color3::purple () static
Definition at line 139 of file Color3.cpp.
{
     static Color3 c(0.7f, 0.0f, 1.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
rainbowColorMap()
Color3 G3D::Color3::rainbowColorMap (float hue) static
Returns colors with maximum saturation and value
Parameters
hue [0, 1]
Definition at line 400 of file Color3.cpp.
{
     return fromHSV(Vector3(hue, 1.0f, 1.0f));
 }
References fromHSV().
random()
Color3 G3D::Color3::random () static
Random unit vector
Definition at line 263 of file Color3.cpp.
                       {
     return Color3(uniformRandom(),
                   uniformRandom(),
                   uniformRandom()).direction();
 }
References Color3(), and G3D::uniformRandom().
red()
const Color3 & G3D::Color3::red () static
Definition at line 121 of file Color3.cpp.
{
     static Color3 c(1.0f, 0.0f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
rgb()
const Color3& G3D::Color3::rgb () const inline
Returns this color
Definition at line 84 of file Color3.h.
{
         return *this;
     }
serialize()
void G3D::Color3::serialize (class BinaryOutput & bo) const
Definition at line 215 of file Color3.cpp.
{
     bo.writeFloat32(r);
     bo.writeFloat32(g);
     bo.writeFloat32(b);
 }
References b, g, r, and G3D::BinaryOutput::writeFloat32().
squaredLength()
float G3D::Color3::squaredLength () const inline
Definition at line 408 of file Color3.h.
{
     return r*r + g*g + b*b;
 }
References b, g, and r.
Referenced by fuzzyEq(), and fuzzyNe().
sum()
float G3D::Color3::sum () const inline
Definition at line 225 of file Color3.h.
{
         return r + g + b;
     }
References b, g, and r.
Referenced by average().
toAny()
Any G3D::Color3::toAny () const
Converts the Color3 to an Any.
Definition at line 93 of file Color3.cpp.
{
     Any a(Any::ARRAY, "Color3");
     a.append(r, g, b);
     return a;
 }
References mpq::a, G3D::Any::ARRAY, b, g, and r.
toHSV()
Vector3 G3D::Color3::toHSV (const Color3 & _rgb) static
Definition at line 337 of file Color3.cpp.
{
     debugAssertM((_rgb.r <= 1.0f && _rgb.r >= 0.0f)
             && (_rgb.g <= 1.0f && _rgb.g >= 0.0f)
             && (_rgb.b <= 1.0f && _rgb.b >= 0.0f), "R,G,B must be between [0,1]");
     Vector3 hsv = Vector3::zero();
     hsv.z = G3D::max(G3D::max(_rgb.r, _rgb.g), _rgb.b);
     if (G3D::fuzzyEq(hsv.z, 0.0f)) {
         return hsv;
     }
     const float x =  G3D::min(G3D::min(_rgb.r, _rgb.g), _rgb.b);
     hsv.y = (hsv.z - x) / hsv.z;
     if (G3D::fuzzyEq(hsv.y, 0.0f)) {
         return hsv;
     }
     Vector3 rgbN;
     rgbN.x = (hsv.z - _rgb.r) / (hsv.z - x);
     rgbN.y = (hsv.z - _rgb.g) / (hsv.z - x);
     rgbN.z = (hsv.z - _rgb.b) / (hsv.z - x);
     if (_rgb.r == hsv.z) {  // note from the max we know that it exactly equals one of the three.
         hsv.x = (_rgb.g == x)? 5.0f + rgbN.z : 1.0f - rgbN.y;
     } else if (_rgb.g == hsv.z) {
         hsv.x = (_rgb.b == x)? 1.0f + rgbN.x : 3.0f - rgbN.z;
     } else {
         hsv.x = (_rgb.r == x)? 3.0f + rgbN.y : 5.0f - rgbN.x;
     }
     hsv.x /= 6.0f;
     return hsv;
 }
References b, debugAssertM, G3D::fuzzyEq(), g, if(), G3D::max(), G3D::min(), r, G3D::x, G3D::Vector3::x, G3D::Vector3::y, G3D::Vector3::z, and G3D::Vector3::zero().
toString()
std::string G3D::Color3::toString () const
Definition at line 394 of file Color3.cpp.
{
     return G3D::format("(%g, %g, %g)", r, g, b);
 }
References b, G3D::format(), g, and r.
unitCross()
Color3 G3D::Color3::unitCross (const Color3 & rkVector) const inline
Definition at line 440 of file Color3.h.
{
     Color3 kCross(g*rkVector.b - b*rkVector.g, b*rkVector.r - r*rkVector.b,
                   r*rkVector.g - g*rkVector.r);
     return kCross.direction();
 }
References b, direction(), g, and r.
unitize()
float G3D::Color3::unitize (float fTolerance = 1e-06f)
Definition at line 286 of file Color3.cpp.
{
     float fLength = length();
     if ( fLength > fTolerance ) {
         float fInvLength = 1.0f / fLength;
         r *= fInvLength;
         g *= fInvLength;
         b *= fInvLength;
     } else {
         fLength = 0.0f;
     }
     return fLength;
 }
References b, g, length(), and r.
wheelRandom()
const Color3 & G3D::Color3::wheelRandom () static
Returns one of the color wheel colors (e.g. RED, GREEN, CYAN). Does not include white, black, or gray.
Definition at line 222 of file Color3.cpp.
{
     static const Color3 colorArray[8] =
     {Color3::blue(),   Color3::red(),    Color3::green(),
      Color3::orange(), Color3::yellow(),
      Color3::cyan(),   Color3::purple(), Color3::brown()};
     return colorArray[iRandom(0, 7)];
 }
References blue(), brown(), cyan(), green(), G3D::iRandom(), orange(), purple(), red(), and yellow().
white()
const Color3 & G3D::Color3::white () static
Definition at line 192 of file Color3.cpp.
{
     static Color3 c(1.0f, 1.0f, 1.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap().
yellow()
const Color3 & G3D::Color3::yellow () static
Definition at line 151 of file Color3.cpp.
{
     static Color3 c(1.0f, 1.0f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by ansiMap(), and wheelRandom().
zero()
const Color3 & G3D::Color3::zero () static
Definition at line 174 of file Color3.cpp.
{
     static Color3 c(0.0f, 0.0f, 0.0f);
     return c;
 }
References mpq::c.
Referenced by Color3().
Member Data Documentation
b
float G3D::Color3::b
Definition at line 139 of file Color3.h.
Referenced by bgr(), Color3(), G3D::Color4::Color4(), G3D::Image3::copyArray(), cross(), deserialize(), direction(), dot(), hashCode(), isFinite(), isOne(), isZero(), jetColorMap(), length(), max(), min(), nonZero(), operator!=(), G3D::operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), pow(), serialize(), squaredLength(), sum(), toAny(), toHSV(), toString(), unitCross(), unitize(), and G3D::BinaryOutput::writeColor3().
g
float G3D::Color3::g
Definition at line 139 of file Color3.h.
Referenced by bgr(), Color3(), G3D::Color4::Color4(), G3D::Image3::copyArray(), cross(), deserialize(), direction(), dot(), hashCode(), isFinite(), isOne(), isZero(), jetColorMap(), length(), max(), min(), nonZero(), operator!=(), G3D::operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), pow(), serialize(), squaredLength(), sum(), toAny(), toHSV(), toString(), unitCross(), unitize(), and G3D::BinaryOutput::writeColor3().
r
float G3D::Color3::r
Channel value.
Definition at line 139 of file Color3.h.
Referenced by bgr(), Color3(), G3D::Color4::Color4(), G3D::Image3::copyArray(), cross(), deserialize(), direction(), dot(), hashCode(), isFinite(), isOne(), isZero(), jetColorMap(), length(), max(), min(), nonZero(), operator!=(), G3D::operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), pow(), serialize(), squaredLength(), sum(), toAny(), toHSV(), toString(), unitCross(), unitize(), and G3D::BinaryOutput::writeColor3().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Color3.h
deps/g3dlite/source/Color3.cpp