Azerotcore-wotlk: go_apexis_relic Class Reference
go_apexis_relic Class Reference
Public Member Functions
go_apexis_relic ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *go, uint32, uint32) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1037 of file zone_blades_edge_mountains.cpp.
Constructor & Destructor Documentation
go_apexis_relic()
go_apexis_relic::go_apexis_relic () inline
Definition at line 1040 of file zone_blades_edge_mountains.cpp.
 : GameObjectScript("go_apexis_relic") { }
Member Function Documentation
OnGossipHello()
bool go_apexis_relic::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1042 of file zone_blades_edge_mountains.cpp.
     {
         player->PrepareGossipMenu(go, go->GetGOInfo()->questgiver.gossipID);
         player->SendPreparedGossip(go);
         return true;
     }
References GameObject::GetGOInfo(), Player::PrepareGossipMenu(), GameObjectTemplate::questgiver, and Player::SendPreparedGossip().
OnGossipSelect()
bool go_apexis_relic::OnGossipSelect (Player * player, GameObject * go, uint32 , uint32) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1049 of file zone_blades_edge_mountains.cpp.
     {
         CloseGossipMenuFor(player);
         bool large = (go->GetEntry() == GO_APEXIS_MONUMENT);
         if (player->HasItemCount(ITEM_APEXIS_SHARD, large ? 35 : 1))
         {
             player->CastSpell(player, large ? SPELL_TAKE_REAGENTS_GROUP : SPELL_TAKE_REAGENTS_SOLO, false);
             if (Creature* bunny = player->SummonCreature(NPC_SIMON_BUNNY, go->GetPositionX(), go->GetPositionY(), go->GetPositionZ()))
                 bunny->AI()->SetGUID(player->GetGUID(), large);
         }
         return true;
     }
References Unit::CastSpell(), CloseGossipMenuFor(), Object::GetEntry(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_APEXIS_MONUMENT, Player::HasItemCount(), ITEM_APEXIS_SHARD, NPC_SIMON_BUNNY, SPELL_TAKE_REAGENTS_GROUP, SPELL_TAKE_REAGENTS_SOLO, and WorldObject::SummonCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_blades_edge_mountains.cpp