Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/safety_check.h File Reference
safety_check.h File Reference
Functions
void safety_check_fail (const char *format,...)
void safety_check_set_abort (void(*abort_fn)())
JEMALLOC_ALWAYS_INLINE void safety_check_set_redzone (void *ptr, size_t usize, size_t bumped_usize)
JEMALLOC_ALWAYS_INLINE void safety_check_verify_redzone (const void *ptr, size_t usize, size_t bumped_usize)
Function Documentation
safety_check_fail()
void safety_check_fail (const char * format, ...)
Definition at line 10 of file safety_check.c.
{
     char buf[MALLOC_PRINTF_BUFSIZE];
     va_list ap;
     va_start(ap, format);
     malloc_vsnprintf(buf, MALLOC_PRINTF_BUFSIZE, format, ap);
     va_end(ap);
     if (safety_check_abort == NULL) {
         malloc_write(buf);
         abort();
     } else {
         safety_check_abort(buf);
     }
 }
References format(), MALLOC_PRINTF_BUFSIZE, malloc_vsnprintf, malloc_write, NULL, and safety_check_abort.
Referenced by safety_check_verify_redzone().
safety_check_set_abort()
void safety_check_set_abort (void(*)() abort_fn)
safety_check_set_redzone()
JEMALLOC_ALWAYS_INLINE void safety_check_set_redzone (void * ptr, size_t usize, size_t bumped_usize)
Definition at line 9 of file safety_check.h.
{
     assert(usize < bumped_usize);
     for (size_t i = usize; i < bumped_usize && i < usize + 32; ++i) {
         *((unsigned char *)ptr + i) = 0xBC;
     }
 }
References assert(), and ptr().
Referenced by arena_prof_promote().
safety_check_verify_redzone()
JEMALLOC_ALWAYS_INLINE void safety_check_verify_redzone (const void * ptr, size_t usize, size_t bumped_usize)
Definition at line 17 of file safety_check.h.
 {
     for (size_t i = usize; i < bumped_usize && i < usize + 32; ++i) {
         if (unlikely(*((unsigned char *)ptr + i) != 0xBC)) {
             safety_check_fail("Use after free error\n");
         }
     }
 }
References ptr(), safety_check_fail(), and unlikely.
Referenced by arena_dalloc_promoted().