Azerotcore-wotlk: AreaTrigger_at_nats_landing Class Reference
AreaTrigger_at_nats_landing Class Reference
Public Member Functions
AreaTrigger_at_nats_landing ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 301 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_nats_landing()
AreaTrigger_at_nats_landing::AreaTrigger_at_nats_landing () inline
Definition at line 304 of file areatrigger_scripts.cpp.
 : AreaTriggerScript("at_nats_landing") { }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_nats_landing::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 306 of file areatrigger_scripts.cpp.
     {
         if (!player->IsAlive() || !player->HasAura(SPELL_FISH_PASTE))
             return false;
         if (player->GetQuestStatus(QUEST_NATS_BARGAIN) == QUEST_STATUS_INCOMPLETE)
         {
             if (!player->FindNearestCreature(NPC_LURKING_SHARK, 20.0f))
             {
                 if (Creature* shark = player->SummonCreature(NPC_LURKING_SHARK, -4246.243f, -3922.356f, -7.488f, 5.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 100000))
                     shark->AI()->AttackStart(player);
                 return false;
             }
         }
         return true;
     }
References WorldObject::FindNearestCreature(), Player::GetQuestStatus(), Unit::HasAura(), Unit::IsAlive(), NPC_LURKING_SHARK, QUEST_NATS_BARGAIN, QUEST_STATUS_INCOMPLETE, SPELL_FISH_PASTE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp