Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tsd_generic.h File Reference
tsd_generic.h File Reference
Classes
struct tsd_init_block_s
struct tsd_wrapper_t
Macros
#define JEMALLOC_INTERNAL_TSD_GENERIC_H
Typedefs
typedef struct tsd_init_block_s tsd_init_block_t
typedef struct tsd_init_head_s tsd_init_head_t
Functions
void * tsd_init_check_recursion (tsd_init_head_t *head, tsd_init_block_t *block)
void tsd_init_finish (tsd_init_head_t *head, tsd_init_block_t *block)
JEMALLOC_ALWAYS_INLINE void tsd_cleanup_wrapper (void *arg)
JEMALLOC_ALWAYS_INLINE void tsd_wrapper_set (tsd_wrapper_t *wrapper)
JEMALLOC_ALWAYS_INLINE tsd_wrapper_t * tsd_wrapper_get (bool init)
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_get (bool init)
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t *val)
Variables
pthread_key_t tsd_tsd
tsd_init_head_t tsd_init_head
tsd_wrapper_t tsd_boot_wrapper
bool tsd_booted
Macro Definition Documentation
JEMALLOC_INTERNAL_TSD_GENERIC_H
#define JEMALLOC_INTERNAL_TSD_GENERIC_H
Definition at line 4 of file tsd_generic.h.
Typedef Documentation
tsd_init_block_t
typedef struct tsd_init_block_s tsd_init_block_t
Definition at line 1 of file tsd_generic.h.
tsd_init_head_t
typedef struct tsd_init_head_s tsd_init_head_t
Definition at line 1 of file tsd_generic.h.
Function Documentation
tsd_boot()
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
Definition at line 122 of file tsd_generic.h.
                {
     if (tsd_boot0()) {
         return true;
     }
     tsd_boot1();
     return false;
 }
References tsd_boot0(), and tsd_boot1().
tsd_boot0()
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
Definition at line 93 of file tsd_generic.h.
                 {
     if (pthread_key_create(&tsd_tsd, tsd_cleanup_wrapper) != 0) {
         return true;
     }
     tsd_wrapper_set(&tsd_boot_wrapper);
     tsd_booted = true;
     return false;
 }
References tsd_boot_wrapper, tsd_booted, tsd_cleanup_wrapper(), tsd_tsd, and tsd_wrapper_set().
Referenced by malloc_tsd_boot0(), and tsd_boot().
tsd_boot1()
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
Definition at line 103 of file tsd_generic.h.
                 {
     tsd_wrapper_t *wrapper;
     wrapper = (tsd_wrapper_t *)malloc_tsd_malloc(sizeof(tsd_wrapper_t));
     if (wrapper == NULL) {
         malloc_write("<jemalloc>: Error allocating TSD\n");
         abort();
     }
     tsd_boot_wrapper.initialized = false;
     tsd_cleanup(&tsd_boot_wrapper.val);
     wrapper->initialized = false;
   JEMALLOC_DIAGNOSTIC_PUSH
   JEMALLOC_DIAGNOSTIC_IGNORE_MISSING_STRUCT_FIELD_INITIALIZERS
     tsd_t initializer = TSD_INITIALIZER;
   JEMALLOC_DIAGNOSTIC_POP
     wrapper->val = initializer;
     tsd_wrapper_set(wrapper);
 }
References tsd_wrapper_t::initialized, JEMALLOC_DIAGNOSTIC_IGNORE_MISSING_STRUCT_FIELD_INITIALIZERS, JEMALLOC_DIAGNOSTIC_POP, JEMALLOC_DIAGNOSTIC_PUSH, malloc_tsd_malloc, malloc_write, NULL, tsd_boot_wrapper, tsd_cleanup, TSD_INITIALIZER, tsd_wrapper_set(), and tsd_wrapper_t::val.
Referenced by malloc_tsd_boot1(), and tsd_boot().
tsd_booted_get()
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
Definition at line 131 of file tsd_generic.h.
                      {
     return tsd_booted;
 }
References tsd_booted.
tsd_cleanup_wrapper()
JEMALLOC_ALWAYS_INLINE void tsd_cleanup_wrapper (void * arg)
Definition at line 32 of file tsd_generic.h.
{
     tsd_wrapper_t *wrapper = (tsd_wrapper_t *)arg;
     if (wrapper->initialized) {
         wrapper->initialized = false;
         tsd_cleanup(&wrapper->val);
         if (wrapper->initialized) {
             /* Trigger another cleanup round. */
             if (pthread_setspecific(tsd_tsd, (void *)wrapper) != 0)
             {
                 malloc_write("<jemalloc>: Error setting TSD\n");
                 if (opt_abort) {
                     abort();
                 }
             }
             return;
         }
     }
     malloc_tsd_dalloc(wrapper);
 }
References arg(), tsd_wrapper_t::initialized, malloc_tsd_dalloc, malloc_write, opt_abort, tsd_cleanup, tsd_tsd, and tsd_wrapper_t::val.
Referenced by tsd_boot0().
tsd_get()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_get (bool init)
Definition at line 142 of file tsd_generic.h.
                    {
     tsd_wrapper_t *wrapper;
     assert(tsd_booted);
     wrapper = tsd_wrapper_get(init);
     if (tsd_get_allocates() && !init && wrapper == NULL) {
         return NULL;
     }
     return &wrapper->val;
 }
References assert(), NULL, tsd_booted, tsd_get_allocates(), tsd_wrapper_get(), and tsd_wrapper_t::val.
Referenced by free_fastpath(), and JEMALLOC_ATTR().
tsd_get_allocates()
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
Definition at line 136 of file tsd_generic.h.
{
     return true;
 }
Referenced by imalloc(), JEMALLOC_ATTR(), and tsd_get().
tsd_init_check_recursion()
void* tsd_init_check_recursion (tsd_init_head_t * head, tsd_init_block_t * block)
Definition at line 488 of file tsd.c.
{
     pthread_t self = pthread_self();
     tsd_init_block_t *iter;
     /* Check whether this thread has already inserted into the list. */
     malloc_mutex_lock(TSDN_NULL, &head->lock);
     ql_foreach(iter, &head->blocks, link) {
         if (iter->thread == self) {
             malloc_mutex_unlock(TSDN_NULL, &head->lock);
             return iter->data;
         }
     }
     /* Insert block into list. */
     ql_elm_new(block, link);
     block->thread = self;
     ql_tail_insert(&head->blocks, block, link);
     malloc_mutex_unlock(TSDN_NULL, &head->lock);
     return NULL;
 }
References tsd_init_block_s::data, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ql_elm_new, ql_foreach, ql_tail_insert, tsd_init_block_s::thread, and TSDN_NULL.
Referenced by tsd_wrapper_get().
tsd_init_finish()
void tsd_init_finish (tsd_init_head_t * head, tsd_init_block_t * block)
Definition at line 509 of file tsd.c.
{
     malloc_mutex_lock(TSDN_NULL, &head->lock);
     ql_remove(&head->blocks, block, link);
     malloc_mutex_unlock(TSDN_NULL, &head->lock);
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), ql_remove, and TSDN_NULL.
Referenced by tsd_wrapper_get().
tsd_set()
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t * val)
Definition at line 154 of file tsd_generic.h.
                     {
     tsd_wrapper_t *wrapper;
     assert(tsd_booted);
     wrapper = tsd_wrapper_get(true);
     if (likely(&wrapper->val != val)) {
         wrapper->val = *(val);
     }
     wrapper->initialized = true;
 }
References assert(), tsd_wrapper_t::initialized, likely, tsd_booted, tsd_wrapper_get(), and tsd_wrapper_t::val.
Referenced by tsd_cleanup(), and tsd_fetch_slow().
tsd_wrapper_get()
JEMALLOC_ALWAYS_INLINE tsd_wrapper_t* tsd_wrapper_get (bool init)
Definition at line 62 of file tsd_generic.h.
{
     tsd_wrapper_t *wrapper = (tsd_wrapper_t *)pthread_getspecific(tsd_tsd);
     if (init && unlikely(wrapper == NULL)) {
         tsd_init_block_t block;
         wrapper = (tsd_wrapper_t *)
             tsd_init_check_recursion(&tsd_init_head, &block);
         if (wrapper) {
             return wrapper;
         }
         wrapper = (tsd_wrapper_t *)
             malloc_tsd_malloc(sizeof(tsd_wrapper_t));
         block.data = (void *)wrapper;
         if (wrapper == NULL) {
             malloc_write("<jemalloc>: Error allocating TSD\n");
             abort();
         } else {
             wrapper->initialized = false;
       JEMALLOC_DIAGNOSTIC_PUSH
       JEMALLOC_DIAGNOSTIC_IGNORE_MISSING_STRUCT_FIELD_INITIALIZERS
             tsd_t initializer = TSD_INITIALIZER;
       JEMALLOC_DIAGNOSTIC_POP
             wrapper->val = initializer;
         }
         tsd_wrapper_set(wrapper);
         tsd_init_finish(&tsd_init_head, &block);
     }
     return wrapper;
 }
References tsd_wrapper_t::initialized, JEMALLOC_DIAGNOSTIC_IGNORE_MISSING_STRUCT_FIELD_INITIALIZERS, JEMALLOC_DIAGNOSTIC_POP, JEMALLOC_DIAGNOSTIC_PUSH, malloc_tsd_malloc, malloc_write, NULL, tsd_init_check_recursion(), tsd_init_finish(), tsd_init_head, TSD_INITIALIZER, tsd_tsd, tsd_wrapper_set(), unlikely, and tsd_wrapper_t::val.
Referenced by tsd_get(), and tsd_set().
tsd_wrapper_set()
JEMALLOC_ALWAYS_INLINE void tsd_wrapper_set (tsd_wrapper_t * wrapper)
Definition at line 54 of file tsd_generic.h.
{
     if (pthread_setspecific(tsd_tsd, (void *)wrapper) != 0) {
         malloc_write("<jemalloc>: Error setting TSD\n");
         abort();
     }
 }
References malloc_write, and tsd_tsd.
Referenced by tsd_boot0(), tsd_boot1(), and tsd_wrapper_get().
Variable Documentation
tsd_boot_wrapper
tsd_wrapper_t tsd_boot_wrapper extern
Definition at line 49 of file tsd.c.
Referenced by tsd_boot0(), and tsd_boot1().
tsd_booted
bool tsd_booted extern
Definition at line 53 of file tsd.c.
Referenced by tsd_boot0(), tsd_booted_get(), tsd_get(), and tsd_set().
tsd_init_head
tsd_init_head_t tsd_init_head extern
Definition at line 44 of file tsd.c.
Referenced by tsd_wrapper_get().
tsd_tsd
pthread_key_t tsd_tsd extern
Definition at line 43 of file tsd.c.
Referenced by tsd_boot0(), tsd_cleanup_wrapper(), tsd_wrapper_get(), and tsd_wrapper_set().