Azerotcore-wotlk: deps/mysqllite/mysys/my_access.c File Reference
my_access.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Macros
#define MAX_RESERVED_NAME_LENGTH 6
Functions
static int str_list_find (const char **list, const char *str)
int check_if_legal_tablename (const char *name)
Variables
static const char * reserved_names []
static char reserved_map [256]
Macro Definition Documentation
MAX_RESERVED_NAME_LENGTH
#define MAX_RESERVED_NAME_LENGTH 6
Definition at line 74 of file my_access.c.
Function Documentation
check_if_legal_tablename()
int check_if_legal_tablename (const char * name)
Definition at line 148 of file my_access.c.
 {
   DBUG_ENTER("check_if_legal_tablename");
   DBUG_RETURN((reserved_map[(uchar) name[0]] & 1) &&
               (reserved_map[(uchar) name[1]] & 2) &&
               (reserved_map[(uchar) name[2]] & 4) &&
               str_list_find(&reserved_names[1], name));
 }
References DBUG_ENTER, DBUG_RETURN, reserved_map, reserved_names, and str_list_find().
str_list_find()
static int str_list_find (const char ** list, const char * str) static
Definition at line 90 of file my_access.c.
 {
   const char **name;
   for (name= list; *name; name++)
   {
     if (!my_strcasecmp(&my_charset_latin1, *name, str))
       return 1;
   }
   return 0;
 }
References list(), my_charset_latin1, and my_strcasecmp.
Referenced by check_if_legal_tablename().
Variable Documentation
reserved_map
char reserved_map[256] static
Initial value:
=
{
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,1,0,1,0,0,0,0,0,0,0,0,7,4,5,2,
  3,0,2,0,4,2,0,0,4,0,0,0,0,0,0,0,
  0,1,0,1,0,0,0,0,0,0,0,0,7,4,5,2,
  3,0,2,0,4,2,0,0,4,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
}
Definition at line 109 of file my_access.c.
Referenced by check_if_legal_tablename().
reserved_names
const char* reserved_names[] static
Initial value:
=
{
  "CLOCK$",
  "CON", "PRN", "AUX", "NUL",
  "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
  "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
  NullS
}
Definition at line 65 of file my_access.c.
Referenced by check_if_legal_tablename().