Azerotcore-wotlk: instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript Struct Reference
instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript Struct Reference
Public Member Functions
instance_old_hillsbrad_InstanceMapScript (Map *map)
void Initialize () override
void OnPlayerEnter (Player *player) override
void CleanupInstance ()
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 data) const override
ObjectGuid GetGuidData (uint32 data) const override
void Update (uint32 diff) override
void Reposition (Creature *thrall)
void EnsureGridLoaded ()
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounterProgress
uint32 _barrelCount
uint32 _attemptsCount
ObjectGuid _thrallGUID
ObjectGuid _tarethaGUID
GuidSet _initalFlamesSet
GuidSet _finalFlamesSet
GuidSet _prisonersSet
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 50 of file instance_old_hillsbrad.cpp.
Constructor & Destructor Documentation
instance_old_hillsbrad_InstanceMapScript()
instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::instance_old_hillsbrad_InstanceMapScript (Map * map) inline
Definition at line 52 of file instance_old_hillsbrad.cpp.
 : InstanceScript(map) { }
Member Function Documentation
CleanupInstance()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::CleanupInstance () inline
Definition at line 77 of file instance_old_hillsbrad.cpp.
         {
             if (_encounterProgress == ENCOUNTER_PROGRESS_NONE)
                 return;
             _events.ScheduleEvent(EVENT_INITIAL_BARRELS_FLAME, 0);
             _events.ScheduleEvent(EVENT_FINAL_BARRELS_FLAME, 0);
             if (_encounterProgress == ENCOUNTER_PROGRESS_BARRELS)
                 _events.ScheduleEvent(EVENT_SUMMON_LIEUTENANT, 0);
             else
                 SetData(DATA_THRALL_REPOSITION, 2);
         }
References _encounterProgress, _events, DATA_THRALL_REPOSITION, ENCOUNTER_PROGRESS_BARRELS, ENCOUNTER_PROGRESS_NONE, EVENT_FINAL_BARRELS_FLAME, EVENT_INITIAL_BARRELS_FLAME, EVENT_SUMMON_LIEUTENANT, EventMap::ScheduleEvent(), and SetData().
Referenced by OnPlayerEnter().
EnsureGridLoaded()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded () inline
Definition at line 295 of file instance_old_hillsbrad.cpp.
         {
             for (uint8 i = 0; i < THRALL_POSITIONS_COUNT; ++i)
                 instance->LoadGrid(thrallPositions[i].GetPositionX(), thrallPositions[i].GetPositionY());
         }
References Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, Map::LoadGrid(), THRALL_POSITIONS_COUNT, and thrallPositions.
Referenced by OnPlayerEnter(), and Update().
GetData()
uint32 instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::GetData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 170 of file instance_old_hillsbrad.cpp.
         {
             if (data == DATA_ESCORT_PROGRESS)
                 return _encounterProgress;
             else if (data == DATA_ATTEMPTS_COUNT)
                 return _attemptsCount;
             return 0;
         }
References _attemptsCount, _encounterProgress, DATA_ATTEMPTS_COUNT, and DATA_ESCORT_PROGRESS.
Referenced by Reposition().
GetGuidData()
ObjectGuid instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 179 of file instance_old_hillsbrad.cpp.
         {
             if (data == DATA_THRALL_GUID)
                 return _thrallGUID;
             else if (data == DATA_TARETHA_GUID)
                 return _tarethaGUID;
             return ObjectGuid::Empty;
         }
References _tarethaGUID, _thrallGUID, DATA_TARETHA_GUID, DATA_THRALL_GUID, and ObjectGuid::Empty.
GetSaveData()
std::string instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 301 of file instance_old_hillsbrad.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "O H " << _encounterProgress << ' ' << _attemptsCount;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References _attemptsCount, _encounterProgress, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_old_hillsbrad.cpp.
         {
             _encounterProgress = 0;
             _barrelCount = 0;
             _attemptsCount = 0;
             _initalFlamesSet.clear();
             _finalFlamesSet.clear();
             _prisonersSet.clear();
             _events.Reset();
         }
References _attemptsCount, _barrelCount, _encounterProgress, _events, _finalFlamesSet, _initalFlamesSet, _prisonersSet, and EventMap::Reset().
Load()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 312 of file instance_old_hillsbrad.cpp.
         {
             if (!in)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             uint32 data0, data1;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> data0 >> data1;
             if (dataHead1 == 'O' && dataHead2 == 'H')
             {
                 _encounterProgress = data0;
                 _attemptsCount = data1;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References _attemptsCount, _encounterProgress, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 91 of file instance_old_hillsbrad.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_THRALL:
                     _thrallGUID = creature->GetGUID();
                     if (_encounterProgress == ENCOUNTER_PROGRESS_FINISHED)
                         creature->SetVisible(false);
                     else
                         Reposition(creature);
                     break;
                 case NPC_ORC_PRISONER:
                     _prisonersSet.insert(creature->GetGUID());
                     break;
                 case NPC_TARETHA:
                     if (_encounterProgress == ENCOUNTER_PROGRESS_FINISHED)
                         creature->SetVisible(false);
                     _tarethaGUID = creature->GetGUID();
                     break;
             }
         }
References _encounterProgress, _prisonersSet, _tarethaGUID, _thrallGUID, ENCOUNTER_PROGRESS_FINISHED, Object::GetEntry(), Object::GetGUID(), NPC_ORC_PRISONER, NPC_TARETHA, NPC_THRALL, Reposition(), and Unit::SetVisible().
OnGameObjectCreate()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 113 of file instance_old_hillsbrad.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_BARREL:
                     if (_encounterProgress >= ENCOUNTER_PROGRESS_BARRELS)
                         gameobject->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case GO_PRISON_DOOR:
                     if (_encounterProgress >= ENCOUNTER_PROGRESS_THRALL_ARMORED)
                         gameobject->SetGoState(GO_STATE_ACTIVE);
                     break;
                 case GO_ROARING_FLAME:
                     // Xinef: hack in DB to distinguish final / initial flames
                     if (gameobject->GetPhaseMask() & 0x2)
                         _finalFlamesSet.insert(gameobject->GetGUID());
                     else
                         _initalFlamesSet.insert(gameobject->GetGUID());
                     break;
             }
         }
References _encounterProgress, _finalFlamesSet, _initalFlamesSet, ENCOUNTER_PROGRESS_BARRELS, ENCOUNTER_PROGRESS_THRALL_ARMORED, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetGUID(), WorldObject::GetPhaseMask(), GO_BARREL, GO_FLAG_NOT_SELECTABLE, GO_PRISON_DOOR, GO_ROARING_FLAME, GO_STATE_ACTIVE, Object::SetFlag(), and GameObject::SetGoState().
OnPlayerEnter()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
Definition at line 66 of file instance_old_hillsbrad.cpp.
         {
             if (instance->GetPlayersCountExceptGMs() == 1)
                 CleanupInstance();
             EnsureGridLoaded();
             if (_encounterProgress < ENCOUNTER_PROGRESS_BARRELS)
                 player->SendUpdateWorldState(WORLD_STATE_BARRELS_PLANTED, _barrelCount);
         }
References _barrelCount, _encounterProgress, CleanupInstance(), ENCOUNTER_PROGRESS_BARRELS, EnsureGridLoaded(), Map::GetPlayersCountExceptGMs(), InstanceScript::instance, Player::SendUpdateWorldState(), and WORLD_STATE_BARRELS_PLANTED.
Reposition()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Reposition (Creature * thrall) inline
Definition at line 279 of file instance_old_hillsbrad.cpp.
         {
             switch (uint32 data = GetData(DATA_ESCORT_PROGRESS))
             {
                 case ENCOUNTER_PROGRESS_THRALL_ARMORED:
                 case ENCOUNTER_PROGRESS_AMBUSHES_1:
                 case ENCOUNTER_PROGRESS_SKARLOC_KILLED:
                 case ENCOUNTER_PROGRESS_TARREN_MILL:
                 case ENCOUNTER_PROGRESS_TARETHA_MEET:
                     thrall->UpdatePosition(thrallPositions[data - ENCOUNTER_PROGRESS_THRALL_ARMORED], true);
                     thrall->SetHomePosition(thrallPositions[data - ENCOUNTER_PROGRESS_THRALL_ARMORED]);
                     thrall->SetFacingTo(thrallPositions[data - ENCOUNTER_PROGRESS_THRALL_ARMORED].GetOrientation());
                     break;
             }
         }
References DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_AMBUSHES_1, ENCOUNTER_PROGRESS_SKARLOC_KILLED, ENCOUNTER_PROGRESS_TARETHA_MEET, ENCOUNTER_PROGRESS_TARREN_MILL, ENCOUNTER_PROGRESS_THRALL_ARMORED, GetData(), Unit::SetFacingTo(), Creature::SetHomePosition(), thrallPositions, and Unit::UpdatePosition().
Referenced by OnCreatureCreate(), SetData(), and Update().
SetData()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 135 of file instance_old_hillsbrad.cpp.
         {
             switch (type)
             {
                 case DATA_THRALL_REPOSITION:
                     if (data > 1)
                         _events.ScheduleEvent(EVENT_THRALL_REPOSITION, data == 2 ? 0 : 10000);
                     else if (Creature* thrall = instance->GetCreature(_thrallGUID))
                         Reposition(thrall);
                     return;
                 case DATA_ESCORT_PROGRESS:
                     _encounterProgress = data;
                     SaveToDB();
                     break;
                 case DATA_BOMBS_PLACED:
                     {
                         if (_barrelCount >= 5 || _encounterProgress > ENCOUNTER_PROGRESS_NONE)
                             return;
                         DoUpdateWorldState(WORLD_STATE_BARRELS_PLANTED, ++_barrelCount);
                         if (_barrelCount == 5)
{
                             _events.ScheduleEvent(EVENT_INITIAL_BARRELS_FLAME, 4000);
                             _events.ScheduleEvent(EVENT_FINAL_BARRELS_FLAME, 12000);
                             _events.ScheduleEvent(EVENT_SUMMON_LIEUTENANT, 18000);
                         }
                         break;
                     }
                 case DATA_THRALL_ADD_FLAG:
                     if (Creature* thrall = instance->GetCreature(_thrallGUID))
                         thrall->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     break;
             }
         }
References _barrelCount, _encounterProgress, _events, _thrallGUID, DATA_BOMBS_PLACED, DATA_ESCORT_PROGRESS, DATA_THRALL_ADD_FLAG, DATA_THRALL_REPOSITION, InstanceScript::DoUpdateWorldState(), ENCOUNTER_PROGRESS_NONE, EVENT_FINAL_BARRELS_FLAME, EVENT_INITIAL_BARRELS_FLAME, EVENT_SUMMON_LIEUTENANT, EVENT_THRALL_REPOSITION, Map::GetCreature(), InstanceScript::instance, Reposition(), InstanceScript::SaveToDB(), EventMap::ScheduleEvent(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and WORLD_STATE_BARRELS_PLANTED.
Referenced by CleanupInstance(), and Update().
Update()
void instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 189 of file instance_old_hillsbrad.cpp.
         {
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case EVENT_INITIAL_BARRELS_FLAME:
                     {
                         instance->LoadGrid(instancePositions[0].GetPositionX(), instancePositions[0].GetPositionY());
                         instance->LoadGrid(instancePositions[1].GetPositionX(), instancePositions[1].GetPositionY());
                         for (ObjectGuid const& guid : _prisonersSet)
                             if (Creature* orc = instance->GetCreature(guid))
{
                                 uint8 index = orc->GetDistance(instancePositions[0]) < 80.0f ? 0 : 1;
                                 Position pos(instancePositions[index]);
                                 orc->MovePosition(pos, frand(1.0f, 3.0f) + 15.0f * (float)rand_norm(), (float)rand_norm() * static_cast<float>(2 * M_PI));
                                 orc->GetMotionMaster()->MovePoint(1, pos);
                                 orc->SetStandState(UNIT_STAND_STATE_STAND);
                             }
                         for (ObjectGuid const& guid : _initalFlamesSet)
                             if (GameObject* gobject = instance->GetGameObject(guid))
{
                                 gobject->SetRespawnTime(0);
                                 gobject->UpdateObjectVisibility(true);
                             }
                         break;
                     }
                 case EVENT_FINAL_BARRELS_FLAME:
                     {
                         instance->LoadGrid(instancePositions[0].GetPositionX(), instancePositions[0].GetPositionY());
                         instance->LoadGrid(instancePositions[1].GetPositionX(), instancePositions[1].GetPositionY());
                         if (_encounterProgress == ENCOUNTER_PROGRESS_NONE)
{
                             Map::PlayerList const& players = instance->GetPlayers();
                             if (!players.isEmpty())
                                 for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                                     if (Player* player = itr->GetSource())
                                         player->KilledMonsterCredit(NPC_LODGE_QUEST_TRIGGER);
                         }
                         for (ObjectGuid const& guid : _finalFlamesSet)
                             if (GameObject* gobject = instance->GetGameObject(guid))
{
                                 gobject->SetRespawnTime(0);
                                 gobject->UpdateObjectVisibility(true);
                             }
                         for (ObjectGuid const& guid : _prisonersSet)
                             if (Creature* orc = instance->GetCreature(guid))
                                 if (roll_chance_i(25))
                                     orc->HandleEmoteCommand(EMOTE_ONESHOT_CHEER);
                         SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_BARRELS);
                         DoUpdateWorldState(WORLD_STATE_BARRELS_PLANTED, 0);
                         break;
                     }
                 case EVENT_SUMMON_LIEUTENANT:
                     {
                         instance->LoadGrid(instancePositions[2].GetPositionX(), instancePositions[2].GetPositionY());
                         if (Creature* drake = instance->SummonCreature(NPC_LIEUTENANT_DRAKE, instancePositions[2]))
{
                             drake->AI()->Talk(0);
                         }
                         [[fallthrough]]; // TODO: Not sure whether the fallthrough was a mistake (forgetting a break) or intended. This should be double-checked.
                     }
                 case EVENT_THRALL_REPOSITION:
                     {
                         if (Creature* thrall = instance->GetCreature(_thrallGUID))
{
                             if (!thrall->IsAlive())
{
                                 ++_attemptsCount;
                                 EnsureGridLoaded();
                                 thrall->SetVisible(false);
                                 Reposition(thrall);
                                 thrall->setDeathState(DEAD);
                                 thrall->Respawn();
                                 thrall->SetVisible(true);
                                 SaveToDB();
                             }
                             else
                                 thrall->AI()->Reset();
                         }
                         break;
                     }
             }
         }
References _attemptsCount, _encounterProgress, _events, _finalFlamesSet, _initalFlamesSet, _prisonersSet, _thrallGUID, MapRefMgr::begin(), DATA_ESCORT_PROGRESS, DEAD, InstanceScript::DoUpdateWorldState(), EMOTE_ONESHOT_CHEER, ENCOUNTER_PROGRESS_BARRELS, ENCOUNTER_PROGRESS_NONE, MapRefMgr::end(), EnsureGridLoaded(), EVENT_FINAL_BARRELS_FLAME, EVENT_INITIAL_BARRELS_FLAME, EVENT_SUMMON_LIEUTENANT, EVENT_THRALL_REPOSITION, EventMap::ExecuteEvent(), frand(), Map::GetCreature(), Map::GetGameObject(), Map::GetPlayers(), InstanceScript::instance, instancePositions, LinkedListHead::isEmpty(), Map::LoadGrid(), NPC_LIEUTENANT_DRAKE, NPC_LODGE_QUEST_TRIGGER, rand_norm(), Reposition(), roll_chance_i(), InstanceScript::SaveToDB(), SetData(), Map::SummonCreature(), UNIT_STAND_STATE_STAND, EventMap::Update(), and WORLD_STATE_BARRELS_PLANTED.
Member Data Documentation
_attemptsCount
uint32 instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_attemptsCount private
Definition at line 342 of file instance_old_hillsbrad.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and Update().
_barrelCount
uint32 instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_barrelCount private
Definition at line 341 of file instance_old_hillsbrad.cpp.
Referenced by Initialize(), OnPlayerEnter(), and SetData().
_encounterProgress
uint32 instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_encounterProgress private
Definition at line 340 of file instance_old_hillsbrad.cpp.
Referenced by CleanupInstance(), GetData(), GetSaveData(), Initialize(), Load(), OnCreatureCreate(), OnGameObjectCreate(), OnPlayerEnter(), SetData(), and Update().
_events
EventMap instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_events private
Definition at line 350 of file instance_old_hillsbrad.cpp.
Referenced by CleanupInstance(), Initialize(), SetData(), and Update().
_finalFlamesSet
GuidSet instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_finalFlamesSet private
Definition at line 347 of file instance_old_hillsbrad.cpp.
Referenced by Initialize(), OnGameObjectCreate(), and Update().
_initalFlamesSet
GuidSet instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_initalFlamesSet private
Definition at line 346 of file instance_old_hillsbrad.cpp.
Referenced by Initialize(), OnGameObjectCreate(), and Update().
_prisonersSet
GuidSet instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_prisonersSet private
Definition at line 348 of file instance_old_hillsbrad.cpp.
Referenced by Initialize(), OnCreatureCreate(), and Update().
_tarethaGUID
ObjectGuid instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_tarethaGUID private
Definition at line 345 of file instance_old_hillsbrad.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_thrallGUID
ObjectGuid instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::_thrallGUID private
Definition at line 344 of file instance_old_hillsbrad.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/instance_old_hillsbrad.cpp