Azerotcore-wotlk: src/server/game/Skills/SkillExtraItems.h File Reference
SkillExtraItems.h File Reference
#include "Common.h"
Functions
bool CanCreatePerfectItem (Player *player, uint32 spellId, float &perfectCreateChance, uint32 &perfectItemType)
void LoadSkillPerfectItemTable ()
bool canCreateExtraItems (Player *player, uint32 spellId, float &additionalChance, int32 &newMaxOrEntry)
void LoadSkillExtraItemTable ()
Function Documentation
canCreateExtraItems()
bool canCreateExtraItems (Player * player, uint32 spellId, float & additionalChance, int32 & newMaxOrEntry)
Definition at line 225 of file SkillExtraItems.cpp.
 {
     // get the info for the specified spell
     SkillExtraItemMap::const_iterator ret = SkillExtraItemStore.find(spellId);
     if (ret == SkillExtraItemStore.end())
         return false;
     SkillExtraItemEntry const* specEntry = &ret->second;
     // if no entry, then no extra items can be created
     if (!specEntry)
         return false;
     // the player doesn't have the required specialization, return false
     if (!player->HasSpell(specEntry->requiredSpecialization))
         return false;
     // set the arguments to the appropriate values
     additionalChance = specEntry->additionalCreateChance;
     newMaxOrEntry = specEntry->newMaxOrEntry;
     // enable extra item creation
     return true;
 }
References SkillExtraItemEntry::additionalCreateChance, Player::HasSpell(), SkillExtraItemEntry::newMaxOrEntry, SkillExtraItemEntry::requiredSpecialization, ret, and SkillExtraItemStore.
Referenced by Spell::DoCreateItem().
CanCreatePerfectItem()
bool CanCreatePerfectItem (Player * player, uint32 spellId, float & perfectCreateChance, uint32 & perfectItemType)
Definition at line 201 of file SkillExtraItems.cpp.
 {
     SkillPerfectItemMap::const_iterator ret = SkillPerfectItemStore.find(spellId);
     // no entry in DB means no perfection proc possible
     if (ret == SkillPerfectItemStore.end())
         return false;
     SkillPerfectItemEntry const* thisEntry = &ret->second;
     // lack of entry means no perfection proc possible
     if (!thisEntry)
         return false;
     // if you don't have the spell needed, then no procs for you
     if (!player->HasSpell(thisEntry->requiredSpecialization))
         return false;
     // set values as appropriate
     perfectCreateChance = thisEntry->perfectCreateChance;
     perfectItemType = thisEntry->perfectItemType;
     // and tell the caller to start rolling the dice
     return true;
 }
References Player::HasSpell(), SkillPerfectItemEntry::perfectCreateChance, SkillPerfectItemEntry::perfectItemType, SkillPerfectItemEntry::requiredSpecialization, ret, and SkillPerfectItemStore.
Referenced by Spell::DoCreateItem().
LoadSkillExtraItemTable()
void LoadSkillExtraItemTable ()
Definition at line 137 of file SkillExtraItems.cpp.
 {
     uint32 oldMSTime = getMSTime();
     SkillExtraItemStore.clear();                            // need for reload
     //                                                  0               1                       2                    3
     QueryResult result = WorldDatabase.Query("SELECT spellId, requiredSpecialization, additionalCreateChance, additionalMaxNum FROM skill_extra_item_template");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 spell specialization definitions. DB table `skill_extra_item_template` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 spellId = fields[0].GetUInt32();
         if (!sSpellMgr->GetSpellInfo(spellId))
         {
             LOG_ERROR("sql.sql", "Skill specialization %u has non-existent spell id in `skill_extra_item_template`!", spellId);
             continue;
         }
         uint32 requiredSpecialization = fields[1].GetUInt32();
         if (!sSpellMgr->GetSpellInfo(requiredSpecialization))
         {
             LOG_ERROR("sql.sql", "Skill specialization %u have not existed required specialization spell id %u in `skill_extra_item_template`!", spellId, requiredSpecialization);
             continue;
         }
         float additionalCreateChance = fields[2].GetFloat();
         if (additionalCreateChance <= 0.0f)
         {
             LOG_ERROR("sql.sql", "Skill specialization %u has too low additional create chance in `skill_extra_item_template`!", spellId);
             continue;
         }
         int32 newMaxOrEntry = fields[3].GetInt32();
         if (!newMaxOrEntry)
         {
             LOG_ERROR("sql.sql", "Skill specialization %u has 0 max number of extra items in `skill_extra_item_template`!", spellId);
             continue;
         }
         SkillExtraItemEntry& skillExtraItemEntry = SkillExtraItemStore[spellId];
         skillExtraItemEntry.requiredSpecialization = requiredSpecialization;
         skillExtraItemEntry.additionalCreateChance = additionalCreateChance;
         skillExtraItemEntry.newMaxOrEntry          = newMaxOrEntry;
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u spell specialization definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References SkillExtraItemEntry::additionalCreateChance, count(), Field::GetFloat(), Field::GetInt32(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, SkillExtraItemEntry::newMaxOrEntry, SkillExtraItemEntry::requiredSpecialization, SkillExtraItemStore, sSpellMgr, and WorldDatabase.
Referenced by reload_commandscript::HandleReloadSkillExtraItemTemplateCommand(), and World::SetInitialWorldSettings().
LoadSkillPerfectItemTable()
void LoadSkillPerfectItemTable ()
Definition at line 51 of file SkillExtraItems.cpp.
 {
     uint32 oldMSTime = getMSTime();
     SkillPerfectItemStore.clear(); // reload capability
     //                                                  0               1                      2                  3
     QueryResult result = WorldDatabase.Query("SELECT spellId, requiredSpecialization, perfectCreateChance, perfectItemType FROM skill_perfect_item_template");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 spell perfection definitions. DB table `skill_perfect_item_template` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do /* fetch data and run sanity checks */
     {
         Field* fields = result->Fetch();
         uint32 spellId = fields[0].GetUInt32();
         if (!sSpellMgr->GetSpellInfo(spellId))
         {
             LOG_ERROR("sql.sql", "Skill perfection data for spell %u has non-existent spell id in `skill_perfect_item_template`!", spellId);
             continue;
         }
         uint32 requiredSpecialization = fields[1].GetUInt32();
         if (!sSpellMgr->GetSpellInfo(requiredSpecialization))
         {
             LOG_ERROR("sql.sql", "Skill perfection data for spell %u has non-existent required specialization spell id %u in `skill_perfect_item_template`!", spellId, requiredSpecialization);
             continue;
         }
         float perfectCreateChance = fields[2].GetFloat();
         if (perfectCreateChance <= 0.0f)
         {
             LOG_ERROR("sql.sql", "Skill perfection data for spell %u has impossibly low proc chance in `skill_perfect_item_template`!", spellId);
             continue;
         }
         uint32 perfectItemType = fields[3].GetUInt32();
         if (!sObjectMgr->GetItemTemplate(perfectItemType))
         {
             LOG_ERROR("sql.sql", "Skill perfection data for spell %u references non-existent perfect item id %u in `skill_perfect_item_template`!", spellId, perfectItemType);
             continue;
         }
         SkillPerfectItemEntry& skillPerfectItemEntry = SkillPerfectItemStore[spellId];
         skillPerfectItemEntry.requiredSpecialization = requiredSpecialization;
         skillPerfectItemEntry.perfectCreateChance = perfectCreateChance;
         skillPerfectItemEntry.perfectItemType = perfectItemType;
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u spell perfection definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References count(), Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, SkillPerfectItemEntry::perfectCreateChance, SkillPerfectItemEntry::perfectItemType, SkillPerfectItemEntry::requiredSpecialization, SkillPerfectItemStore, sObjectMgr, sSpellMgr, and WorldDatabase.
Referenced by reload_commandscript::HandleReloadSkillPerfectItemTemplateCommand(), and World::SetInitialWorldSettings().