Azerotcore-wotlk: WretchedGhoulCleaner Class Reference
WretchedGhoulCleaner Class Reference
Public Member Functions
void operator() (Creature *creature)
Detailed Description
Definition at line 738 of file zone_dragonblight.cpp.
Member Function Documentation
operator()()
void WretchedGhoulCleaner::operator() (Creature * creature) inline
Definition at line 741 of file zone_dragonblight.cpp.
     {
         if (creature->GetEntry() == NPC_SAC_WRETCHED_GHOUL && creature->GetDisplayId() != 11686 && creature->IsAlive())
             Unit::Kill(creature, creature);
     }
References Unit::GetDisplayId(), Object::GetEntry(), Unit::IsAlive(), Unit::Kill(), and NPC_SAC_WRETCHED_GHOUL.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp