Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/pages.h File Reference
pages.h File Reference
Macros
#define PAGE ((size_t)(1U << LG_PAGE))
#define PAGE_MASK ((size_t)(PAGE - 1))
#define PAGE_ADDR2BASE(a) ((void *)((uintptr_t)(a) & ~PAGE_MASK))
#define PAGE_CEILING(s) (((s) + PAGE_MASK) & ~PAGE_MASK)
#define HUGEPAGE ((size_t)(1U << LG_HUGEPAGE))
#define HUGEPAGE_MASK ((size_t)(HUGEPAGE - 1))
#define HUGEPAGE_ADDR2BASE(a) ((void *)((uintptr_t)(a) & ~HUGEPAGE_MASK))
#define HUGEPAGE_CEILING(s) (((s) + HUGEPAGE_MASK) & ~HUGEPAGE_MASK)
#define THP_MODE_DEFAULT thp_mode_default
Enumerations
enum thp_mode_t {
thp_mode_default = 0 , thp_mode_always = 1 , thp_mode_never = 2 , thp_mode_names_limit = 3 ,
thp_mode_not_supported = 3
}
Functions
void * pages_map (void *addr, size_t size, size_t alignment, bool *commit)
void pages_unmap (void *addr, size_t size)
bool pages_commit (void *addr, size_t size)
bool pages_decommit (void *addr, size_t size)
bool pages_purge_lazy (void *addr, size_t size)
bool pages_purge_forced (void *addr, size_t size)
bool pages_huge (void *addr, size_t size)
bool pages_nohuge (void *addr, size_t size)
bool pages_dontdump (void *addr, size_t size)
bool pages_dodump (void *addr, size_t size)
bool pages_boot (void)
void pages_set_thp_state (void *ptr, size_t size)
Variables
static const bool pages_can_purge_lazy
static const bool pages_can_purge_forced
thp_mode_t opt_thp
thp_mode_t init_system_thp_mode
const char * thp_mode_names []
Macro Definition Documentation
HUGEPAGE
#define HUGEPAGE ((size_t)(1U << LG_HUGEPAGE))
Definition at line 18 of file pages.h.
HUGEPAGE_ADDR2BASE
#define HUGEPAGE_ADDR2BASE (a) ((void *)((uintptr_t)(a) & ~HUGEPAGE_MASK))
Definition at line 21 of file pages.h.
HUGEPAGE_CEILING
#define HUGEPAGE_CEILING (s) (((s) + HUGEPAGE_MASK) & ~HUGEPAGE_MASK)
Definition at line 24 of file pages.h.
HUGEPAGE_MASK
#define HUGEPAGE_MASK ((size_t)(HUGEPAGE - 1))
Definition at line 19 of file pages.h.
PAGE
#define PAGE ((size_t)(1U << LG_PAGE))
Definition at line 8 of file pages.h.
PAGE_ADDR2BASE
#define PAGE_ADDR2BASE (a) ((void *)((uintptr_t)(a) & ~PAGE_MASK))
Definition at line 11 of file pages.h.
PAGE_CEILING
#define PAGE_CEILING (s) (((s) + PAGE_MASK) & ~PAGE_MASK)
Definition at line 14 of file pages.h.
PAGE_MASK
#define PAGE_MASK ((size_t)(PAGE - 1))
Definition at line 9 of file pages.h.
THP_MODE_DEFAULT
#define THP_MODE_DEFAULT thp_mode_default
Definition at line 70 of file pages.h.
Enumeration Type Documentation
thp_mode_t
enum thp_mode_t
Enumerator
thp_mode_default
thp_mode_always
thp_mode_never
thp_mode_names_limit
thp_mode_not_supported
Definition at line 61 of file pages.h.
              {
     thp_mode_default       = 0, /* Do not change hugepage settings. */
     thp_mode_always        = 1, /* Always set MADV_HUGEPAGE. */
     thp_mode_never         = 2, /* Always set MADV_NOHUGEPAGE. */
     thp_mode_names_limit   = 3, /* Used for option processing. */
     thp_mode_not_supported = 3  /* No THP support detected. */
 } thp_mode_t;
Function Documentation
pages_boot()
bool pages_boot (void)
Definition at line 599 of file pages.c.
                  {
     os_page = os_page_detect();
     if (os_page > PAGE) {
         malloc_write("<jemalloc>: Unsupported system page size\n");
         if (opt_abort) {
             abort();
         }
         return true;
     }
 #ifndef _WIN32
     mmap_flags = MAP_PRIVATE | MAP_ANON;
 #endif
 #ifdef JEMALLOC_SYSCTL_VM_OVERCOMMIT
     os_overcommits = os_overcommits_sysctl();
 #elif defined(JEMALLOC_PROC_SYS_VM_OVERCOMMIT_MEMORY)
     os_overcommits = os_overcommits_proc();
 #  ifdef MAP_NORESERVE
     if (os_overcommits) {
         mmap_flags |= MAP_NORESERVE;
     }
 #  endif
 #else
     os_overcommits = false;
 #endif
     init_thp_state();
 #ifdef __FreeBSD__
     /*
      * FreeBSD doesn't need the check; madvise(2) is known to work.
      */
 #else
     /* Detect lazy purge runtime support. */
     if (pages_can_purge_lazy) {
         bool committed = false;
         void *madv_free_page = os_pages_map(NULL, PAGE, PAGE, &committed);
         if (madv_free_page == NULL) {
             return true;
         }
         assert(pages_can_purge_lazy_runtime);
         if (pages_purge_lazy(madv_free_page, PAGE)) {
             pages_can_purge_lazy_runtime = false;
         }
         os_pages_unmap(madv_free_page, PAGE);
     }
 #endif
     return false;
 }
References assert(), init_thp_state(), malloc_write, MAP_NORESERVE, MAP_PRIVATE, mmap_flags, NULL, opt_abort, os_overcommits, os_page, os_page_detect(), os_pages_map(), os_pages_unmap(), PAGE, pages_can_purge_lazy, pages_can_purge_lazy_runtime, and pages_purge_lazy().
pages_commit()
bool pages_commit (void * addr, size_t size)
Definition at line 282 of file pages.c.
{
     return pages_commit_impl(addr, size, true);
 }
References pages_commit_impl().
Referenced by pages_purge_forced().
pages_decommit()
bool pages_decommit (void * addr, size_t size)
Definition at line 287 of file pages.c.
{
     return pages_commit_impl(addr, size, false);
 }
References pages_commit_impl().
pages_dodump()
bool pages_dodump (void * addr, size_t size)
Definition at line 405 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
 #ifdef JEMALLOC_MADVISE_DONTDUMP
     return madvise(addr, size, MADV_DODUMP) != 0;
 #else
     return false;
 #endif
 }
References assert(), PAGE_ADDR2BASE, and PAGE_CEILING.
pages_dontdump()
bool pages_dontdump (void * addr, size_t size)
Definition at line 394 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
 #ifdef JEMALLOC_MADVISE_DONTDUMP
     return madvise(addr, size, MADV_DONTDUMP) != 0;
 #else
     return false;
 #endif
 }
References assert(), PAGE_ADDR2BASE, and PAGE_CEILING.
pages_huge()
bool pages_huge (void * addr, size_t size)
Definition at line 360 of file pages.c.
{
     return pages_huge_impl(addr, size, true);
 }
References pages_huge_impl().
pages_map()
void* pages_map (void * addr, size_t size, size_t alignment, bool * commit)
Definition at line 179 of file pages.c.
{
     assert(alignment >= PAGE);
     assert(ALIGNMENT_ADDR2BASE(addr, alignment) == addr);
 #if defined(__FreeBSD__) && defined(MAP_EXCL)
     /*
      * FreeBSD has mechanisms both to mmap at specific address without
      * touching existing mappings, and to mmap with specific alignment.
      */
     {
         if (os_overcommits) {
             *commit = true;
         }
         int prot = *commit ? PAGES_PROT_COMMIT : PAGES_PROT_DECOMMIT;
         int flags = mmap_flags;
         if (addr != NULL) {
             flags |= MAP_FIXED | MAP_EXCL;
         } else {
             unsigned alignment_bits = ffs_zu(alignment);
             assert(alignment_bits > 1);
             flags |= MAP_ALIGNED(alignment_bits - 1);
         }
         void *ret = mmap(addr, size, prot, flags, -1, 0);
         if (ret == MAP_FAILED) {
             ret = NULL;
         }
         return ret;
     }
 #endif
     /*
      * Ideally, there would be a way to specify alignment to mmap() (like
      * NetBSD has), but in the absence of such a feature, we have to work
      * hard to efficiently create aligned mappings.  The reliable, but
      * slow method is to create a mapping that is over-sized, then trim the
      * excess.  However, that always results in one or two calls to
      * os_pages_unmap(), and it can leave holes in the process's virtual
      * memory map if memory grows downward.
      *
      * Optimistically try mapping precisely the right amount before falling
      * back to the slow method, with the expectation that the optimistic
      * approach works most of the time.
      */
     void *ret = os_pages_map(addr, size, os_page, commit);
     if (ret == NULL || ret == addr) {
         return ret;
     }
     assert(addr == NULL);
     if (ALIGNMENT_ADDR2OFFSET(ret, alignment) != 0) {
         os_pages_unmap(ret, size);
         return pages_map_slow(size, alignment, commit);
     }
     assert(PAGE_ADDR2BASE(ret) == ret);
     return ret;
 }
References ALIGNMENT_ADDR2BASE, ALIGNMENT_ADDR2OFFSET, assert(), ffs_zu(), MAP_FAILED, mmap_flags, NULL, os_overcommits, os_page, os_pages_map(), os_pages_unmap(), PAGE, PAGE_ADDR2BASE, pages_map_slow(), PAGES_PROT_COMMIT, PAGES_PROT_DECOMMIT, and ret.
pages_nohuge()
bool pages_nohuge (void * addr, size_t size)
Definition at line 384 of file pages.c.
{
     return pages_nohuge_impl(addr, size, true);
 }
References pages_nohuge_impl().
pages_purge_forced()
bool pages_purge_forced (void * addr, size_t size)
Definition at line 327 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
     if (!pages_can_purge_forced) {
         return true;
     }
 #if defined(JEMALLOC_PURGE_MADVISE_DONTNEED) && \
     defined(JEMALLOC_PURGE_MADVISE_DONTNEED_ZEROS)
     return (madvise(addr, size, MADV_DONTNEED) != 0);
 #elif defined(JEMALLOC_MAPS_COALESCE)
     /* Try to overlay a new demand-zeroed mapping. */
     return pages_commit(addr, size);
 #else
     not_reached();
 #endif
 }
References assert(), not_reached, PAGE_ADDR2BASE, PAGE_CEILING, pages_can_purge_forced, and pages_commit().
pages_purge_lazy()
bool pages_purge_lazy (void * addr, size_t size)
Definition at line 292 of file pages.c.
{
     assert(ALIGNMENT_ADDR2BASE(addr, os_page) == addr);
     assert(PAGE_CEILING(size) == size);
     if (!pages_can_purge_lazy) {
         return true;
     }
     if (!pages_can_purge_lazy_runtime) {
         /*
          * Built with lazy purge enabled, but detected it was not
          * supported on the current system.
          */
         return true;
     }
 #ifdef _WIN32
     VirtualAlloc(addr, size, MEM_RESET, PAGE_READWRITE);
     return false;
 #elif defined(JEMALLOC_PURGE_MADVISE_FREE)
     return (madvise(addr, size,
 #  ifdef MADV_FREE
         MADV_FREE
 #  else
         JEMALLOC_MADV_FREE
 #  endif
         ) != 0);
 #elif defined(JEMALLOC_PURGE_MADVISE_DONTNEED) && \
     !defined(JEMALLOC_PURGE_MADVISE_DONTNEED_ZEROS)
     return (madvise(addr, size, MADV_DONTNEED) != 0);
 #else
     not_reached();
 #endif
 }
References ALIGNMENT_ADDR2BASE, assert(), endif(), not_reached, os_page, PAGE_CEILING, pages_can_purge_lazy, and pages_can_purge_lazy_runtime.
Referenced by pages_boot().
pages_set_thp_state()
void pages_set_thp_state (void * ptr, size_t size)
Definition at line 530 of file pages.c.
{
     if (opt_thp == thp_mode_default || opt_thp == init_system_thp_mode) {
         return;
     }
     assert(opt_thp != thp_mode_not_supported &&
         init_system_thp_mode != thp_mode_not_supported);
     if (opt_thp == thp_mode_always
         && init_system_thp_mode != thp_mode_never) {
         assert(init_system_thp_mode == thp_mode_default);
         pages_huge_unaligned(ptr, size);
     } else if (opt_thp == thp_mode_never) {
         assert(init_system_thp_mode == thp_mode_default ||
             init_system_thp_mode == thp_mode_always);
         pages_nohuge_unaligned(ptr, size);
     }
 }
References assert(), init_system_thp_mode, opt_thp, pages_huge_unaligned(), pages_nohuge_unaligned(), ptr(), thp_mode_always, thp_mode_default, thp_mode_never, and thp_mode_not_supported.
pages_unmap()
static void pages_unmap (void * addr, size_t size)
Definition at line 61 of file chunk_mmap.c.
 {
 #ifdef _WIN32
     if (VirtualFree(addr, 0, MEM_RELEASE) == 0)
 #else
     if (munmap(addr, size) == -1)
 #endif
     {
         char buf[BUFERROR_BUF];
         buferror(get_errno(), buf, sizeof(buf));
         malloc_printf("<jemalloc>: Error in "
 #ifdef _WIN32
                       "VirtualFree"
 #else
                       "munmap"
 #endif
                       "(): %s\n", buf);
         if (opt_abort)
             abort();
     }
 }
References assert(), buferror, BUFERROR_BUF, endif(), get_errno(), malloc_printf, opt_abort, os_pages_unmap(), PAGE_ADDR2BASE, and PAGE_CEILING.
Variable Documentation
init_system_thp_mode
thp_mode_t init_system_thp_mode extern
Definition at line 38 of file pages.c.
Referenced by init_thp_state(), and pages_set_thp_state().
opt_thp
thp_mode_t opt_thp extern
Definition at line 37 of file pages.c.
Referenced by init_thp_state(), and pages_set_thp_state().
pages_can_purge_forced
const bool pages_can_purge_forced static
Initial value:
=
    false
Definition at line 53 of file pages.h.
Referenced by pages_purge_forced().
pages_can_purge_lazy
const bool pages_can_purge_lazy static
Initial value:
=
    false
Definition at line 46 of file pages.h.
Referenced by arena_may_have_muzzy(), pages_boot(), and pages_purge_lazy().
thp_mode_names
const char* thp_mode_names[] extern
Definition at line 31 of file pages.c.