Azerotcore-wotlk: ADTFile Class Reference
ADTFile Class Reference
#include <adtfile.h>
Public Member Functions
ADTFile (char *filename)
~ADTFile ()
bool init (uint32 map_num, uint32 tileX, uint32 tileY)
Public Attributes
std::vector< std::string > WmoInstanceNames
std::vector< std::string > ModelInstanceNames
Private Attributes
MPQFile _file
std::string Adtfilename
Detailed Description
Definition at line 137 of file adtfile.h.
Constructor & Destructor Documentation
ADTFile()
ADTFile::ADTFile (char * filename)
Definition at line 80 of file adtfile.cpp.
                               : _file(filename)
 {
     Adtfilename.append(filename);
 }
References Adtfilename.
~ADTFile()
ADTFile::~ADTFile ()
Definition at line 198 of file adtfile.cpp.
 {
     _file.close();
 }
References _file, and MPQFile::close().
Member Function Documentation
init()
bool ADTFile::init (uint32 map_num, uint32 tileX, uint32 tileY)
Definition at line 85 of file adtfile.cpp.
 {
     if (_file.isEof())
         return false;
     uint32 size;
     std::string dirname = std::string(szWorkDirWmo) + "/dir_bin";
     FILE* dirfile;
     dirfile = fopen(dirname.c_str(), "ab");
     if (!dirfile)
     {
         printf("Can't open dirfile!'%s'\n", dirname.c_str());
         return false;
     }
     while (!_file.isEof())
     {
         char fourcc[5];
         _file.read(&fourcc, 4);
         _file.read(&size, 4);
         flipcc(fourcc);
         fourcc[4] = 0;
         size_t nextpos = _file.getPos() + size;
         if (!strcmp(fourcc, "MCIN"))
         {
         }
         else if (!strcmp(fourcc, "MTEX"))
         {
         }
         else if (!strcmp(fourcc, "MMDX"))
         {
             if (size)
             {
                 char* buf = new char[size];
                 _file.read(buf, size);
                 char* p = buf;
                 while (p < buf + size)
                 {
                     fixnamen(p, strlen(p));
                     char* s = GetPlainName(p);
                     fixname2(s, strlen(s));
                     ModelInstanceNames.emplace_back(s);
                     string path(p);
                     ExtractSingleModel(path);
                     p = p + strlen(p) + 1;
                 }
                 delete[] buf;
             }
         }
         else if (!strcmp(fourcc, "MWMO"))
         {
             if (size)
             {
                 char* buf = new char[size];
                 _file.read(buf, size);
                 char* p = buf;
                 while (p < buf + size)
                 {
                     std::string path(p);
                     char* s = GetPlainName(p);
                     fixnamen(s, strlen(s));
                     fixname2(s, strlen(s));
                     WmoInstanceNames.emplace_back(s);
                     ExtractSingleWmo(path);
                     p += strlen(p) + 1;
                 }
                 delete[] buf;
             }
         }
         //======================
         else if (!strcmp(fourcc, "MDDF"))
         {
             if (size)
             {
                 uint32 doodadCount = size / sizeof(ADT::MDDF);
                 for (uint32 i = 0; i < doodadCount; ++i)
                 {
                     ADT::MDDF doodadDef;
                     _file.read(&doodadDef, sizeof(ADT::MDDF));
                     Doodad::Extract(doodadDef, ModelInstanceNames[doodadDef.Id].c_str(), map_num, tileX, tileY, dirfile);
                 }
             }
         }
         else if (!strcmp(fourcc, "MODF"))
         {
             if (size)
             {
                 uint32 mapObjectCount = size / sizeof(ADT::MODF);
                 for (uint32 i = 0; i < mapObjectCount; ++i)
                 {
                     ADT::MODF mapObjDef;
                     _file.read(&mapObjDef, sizeof(ADT::MODF));
                     MapObject::Extract(mapObjDef, WmoInstanceNames[mapObjDef.Id].c_str(), map_num, tileX, tileY, dirfile);
                     Doodad::ExtractSet(WmoDoodads[WmoInstanceNames[mapObjDef.Id]], mapObjDef, map_num, tileX, tileY, dirfile);
                 }
             }
         }
         //======================
         _file.seek(nextpos);
     }
     _file.close();
     fclose(dirfile);
     return true;
 }
References _file, MPQFile::close(), Doodad::Extract(), MapObject::Extract(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), fixname2(), fixnamen(), flipcc(), GetPlainName(), MPQFile::getPos(), ADT::MDDF::Id, ADT::MODF::Id, MPQFile::isEof(), ModelInstanceNames, printf(), MPQFile::read(), MPQFile::seek(), szWorkDirWmo, WmoDoodads, and WmoInstanceNames.
Member Data Documentation
_file
MPQFile ADTFile::_file private
Definition at line 140 of file adtfile.h.
Referenced by mpq.Reader::__del__(), mpq.Reader::__repr__(), mpq.Reader::_read_block(), init(), mpq.Reader::read(), mpq.Reader::seek(), and ~ADTFile().
Adtfilename
std::string ADTFile::Adtfilename private
Definition at line 141 of file adtfile.h.
Referenced by ADTFile().
ModelInstanceNames
std::vector<std::string> ADTFile::ModelInstanceNames
Definition at line 146 of file adtfile.h.
Referenced by init().
WmoInstanceNames
std::vector<std::string> ADTFile::WmoInstanceNames
Definition at line 145 of file adtfile.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/tools/vmap4_extractor/adtfile.h
src/tools/vmap4_extractor/adtfile.cpp