Azerotcore-wotlk: Acore::AnyAssistCreatureInRangeCheck Class Reference
Acore::AnyAssistCreatureInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyAssistCreatureInRangeCheck (Unit *funit, Unit *enemy, float range)
bool operator() (Creature *u)
Private Attributes
Unit *const i_funit
Unit *const i_enemy
float i_range
Detailed Description
Definition at line 1145 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyAssistCreatureInRangeCheck()
Acore::AnyAssistCreatureInRangeCheck::AnyAssistCreatureInRangeCheck (Unit * funit, Unit * enemy, float range) inline
Definition at line 1148 of file GridNotifiers.h.
             : i_funit(funit), i_enemy(enemy), i_range(range)
         {
         }
Member Function Documentation
operator()()
bool Acore::AnyAssistCreatureInRangeCheck::operator() (Creature * u) inline
Definition at line 1152 of file GridNotifiers.h.
         {
             if (u == i_funit)
                 return false;
             if (!u->CanAssistTo(i_funit, i_enemy))
                 return false;
             // too far
             if (!i_funit->IsWithinDistInMap(u, i_range))
                 return false;
             // only if see assisted creature
             if (!i_funit->IsWithinLOSInMap(u))
                 return false;
             return true;
         }
References Creature::CanAssistTo(), i_enemy, i_funit, i_range, WorldObject::IsWithinDistInMap(), and WorldObject::IsWithinLOSInMap().
Member Data Documentation
i_enemy
Unit* const Acore::AnyAssistCreatureInRangeCheck::i_enemy private
Definition at line 1172 of file GridNotifiers.h.
Referenced by operator()().
i_funit
Unit* const Acore::AnyAssistCreatureInRangeCheck::i_funit private
Definition at line 1171 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::AnyAssistCreatureInRangeCheck::i_range private
Definition at line 1173 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h