Azerotcore-wotlk: npc_pos_leader::npc_pos_leaderAI Struct Reference
npc_pos_leader::npc_pos_leaderAI Struct Reference
Public Member Functions
npc_pos_leaderAI (Creature *creature)
void Reset () override
void SetData (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
InstanceScript * pInstance
uint8 counter
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 34 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
npc_pos_leaderAI()
npc_pos_leader::npc_pos_leaderAI::npc_pos_leaderAI (Creature * creature) inline
Definition at line 36 of file pit_of_saron.cpp.
                                              : NullCreatureAI(creature), summons(me)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_pos_leader::npc_pos_leaderAI::AttackStart (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 372 of file pit_of_saron.cpp.
 {}
JustSummoned()
void npc_pos_leader::npc_pos_leaderAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from CreatureAI.
Definition at line 362 of file pit_of_saron.cpp.
         {
             summons.Summon(s);
         }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void npc_pos_leader::npc_pos_leaderAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 373 of file pit_of_saron.cpp.
 {}
Reset()
void npc_pos_leader::npc_pos_leaderAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 46 of file pit_of_saron.cpp.
         {
             counter = 0;
             events.Reset();
             summons.DespawnAll();
             me->SetVisible(true);
             if (pInstance)
                 switch (pInstance->GetData(DATA_INSTANCE_PROGRESS))
                 {
                     case INSTANCE_PROGRESS_NONE:
                         me->SetVisible(false);
                         break;
                 }
         }
References counter, DATA_INSTANCE_PROGRESS, SummonList::DespawnAll(), ZoneScript::GetData(), INSTANCE_PROGRESS_NONE, CreatureAI::me, pInstance, Unit::SetVisible(), and summons.
SetData()
void npc_pos_leader::npc_pos_leaderAI::SetData (uint32 type, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 62 of file pit_of_saron.cpp.
         {
             if (type == DATA_START_INTRO && pInstance->GetData(DATA_INSTANCE_PROGRESS) == INSTANCE_PROGRESS_NONE && counter == 0 && !me->IsVisible())
             {
                 me->setActive(true);
                 events.RescheduleEvent(1, 0);
             }
         }
References counter, DATA_INSTANCE_PROGRESS, DATA_START_INTRO, ZoneScript::GetData(), INSTANCE_PROGRESS_NONE, Unit::IsVisible(), CreatureAI::me, pInstance, and WorldObject::setActive().
SummonedCreatureDespawn()
void npc_pos_leader::npc_pos_leaderAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from CreatureAI.
Definition at line 367 of file pit_of_saron.cpp.
         {
             summons.Despawn(s);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_pos_leader::npc_pos_leaderAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 71 of file pit_of_saron.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     {
                         if (counter == 0)
{
                             me->SetVisible(true);
                             me->GetMotionMaster()->MovePoint(1, LeaderIntroPos);
                         }
                         uint8 idx = 0;
                         if (pInstance)
                             idx = (pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_ALLIANCE ? 0 : 1);
                         if (introPositions[counter].entry[idx] != 0)
{
                             if (Creature* summon = me->SummonCreature(introPositions[counter].entry[idx], PortalPos))
{
                                 summon->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                 summon->SetSpeed(MOVE_RUN, 0.8f);
                                 summon->GetMotionMaster()->MovePoint(1, introPositions[counter].endPosition);
                                 summon->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                             }
                             ++counter;
                             events.RepeatEvent(150);
                         }
                         else
{
                             events.RescheduleEvent(2, 2500);
                         }
                     }
                     break;
                 case 2:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
{
                             c->setActive(true);
                             c->AI()->Talk(SAY_TYRANNUS_INTRO_1);
                         }
                     events.RescheduleEvent(3, 7000);
                     break;
                 case 3:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                             c->AI()->Talk(SAY_TYRANNUS_INTRO_2);
                     events.RescheduleEvent(4, 14000);
                     break;
                 case 4:
                     if (pInstance)
                     {
                         Creature* n1 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_1_GUID));
                         Creature* n2 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_2_GUID));
                         if (n1 && n2)
{
                             if (!n1->IsInCombat() && n1->IsAlive())
{
                                 n1->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                 n1->GetMotionMaster()->MovePoint(1, NecrolytePos1);
                                 n1->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                             }
                             if (!n2->IsInCombat() && n2->IsAlive())
{
                                 n2->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                 n2->GetMotionMaster()->MovePoint(1, NecrolytePos2);
                                 n2->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                             }
                             // TODO This spell check is invalid
                             //                            if (SPELL_NECROLYTE_CHANNELING)
                             //                            {
                             n1->RemoveAura(SPELL_NECROLYTE_CHANNELING);
                             n2->RemoveAura(SPELL_NECROLYTE_CHANNELING);
                             //                            }
                             for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                                 if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                     if (c->GetPositionX() < 440.0f)
                                         continue;
                                     if (c->GetPositionY() > 215.0f)
                                         c->GetMotionMaster()->MoveChase(n2, 0.0f, rand_norm() * 2 * M_PI);
                                     else
                                         c->GetMotionMaster()->MoveChase(n1, 0.0f, rand_norm() * 2 * M_PI);
                                 }
                         }
                     }
                     events.RescheduleEvent(5, 1);
                     break;
                 case 5:
                     Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_1 : SAY_SYLVANAS_INTRO_1);
                     events.RescheduleEvent(6, 1000);
                     break;
                 case 6:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                             c->AI()->Talk(SAY_TYRANNUS_INTRO_3);
                     events.RescheduleEvent(7, 5000);
                     break;
                 case 7:
                     if (pInstance)
                     {
                         if (Creature* n1 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_1_GUID)))
                             n1->AI()->DoAction(1337); // remove invincibility
                         if (Creature* n2 = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_NECROLYTE_2_GUID)))
                             n2->AI()->DoAction(1337); // remove invincibility
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->GetPositionX() < 450.0f)
                                     continue;
                                 c->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                                 c->GetMotionMaster()->Clear(false);
                                 c->GetMotionMaster()->MoveIdle();
                                 c->StopMoving();
                                 c->CastSpell(c, 69413, true);
                                 c->SetCanFly(true);
                                 c->SetDisableGravity(true);
                                 c->SendMovementFlagUpdate();
                                 float dist = rand_norm() * 2.0f;
                                 float angle = rand_norm() * 2 * M_PI;
                                 c->GetMotionMaster()->MoveTakeoff(0, c->GetPositionX() + dist * cos(angle), c->GetPositionY() + dist * sin(angle), c->GetPositionZ() + 6.0f + (float)urand(0, 4), 1.5f + frand(0.0f, 1.5f));
                             }
                     }
                     events.RescheduleEvent(8, 7000);
                     break;
                 case 8:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                             c->CastSpell(c, 69753, false);
                     events.RescheduleEvent(9, 400);
                     break;
                 case 9:
                     if (pInstance)
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->GetPositionX() < 450.0f)
                                     continue;
                                 Unit::Kill(c, c);
                                 c->RemoveAllAuras();
                                 c->GetMotionMaster()->MoveFall(0, true);
                             }
                     events.RescheduleEvent(10, 1000);
                     break;
                 case 10:
                     Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_2 : SAY_SYLVANAS_INTRO_2);
                     events.RescheduleEvent(11, 1000);
                     break;
                 case 11:
                     if (pInstance)
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->GetPositionX() < 450.0f)
                                     continue;
                                 c->SetCanFly(false);
                                 c->SetDisableGravity(false);
                                 c->SendMovementFlagUpdate();
                                 c->CastSpell(c, 69350, true);
                             }
                     events.RescheduleEvent(12, 2000);
                     break;
                 case 12:
                     if (pInstance)
                     {
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                             c->AI()->Talk(SAY_TYRANNUS_INTRO_4);
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->GetPositionX() < 450.0f)
                                     continue;
                                 c->SetHomePosition(c->GetPositionX(), c->GetPositionY(), c->GetPositionZ(), c->GetOrientation());
                                 c->Respawn(true);
                                 c->UpdateEntry(36796, 0, false);
                                 c->SetFacingTo(M_PI);
                                 c->SetReactState(REACT_PASSIVE);
                             }
                     }
                     events.RescheduleEvent(13, 3000);
                     break;
                 case 13:
                     if (pInstance)
                     {
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->GetPositionX() < 450.0f)
                                     continue;
                                 c->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                                 float dist = rand_norm();
                                 float angle = rand_norm() * 2 * M_PI;
                                 c->SetSpeed(MOVE_RUN, 0.8f);
                                 c->SetInCombatWithZone();
                                 c->GetMotionMaster()->MoveChase(me, dist, angle);
                                 c->SetHomePosition(me->GetPositionX() + dist * cos(angle), me->GetPositionY() + dist * sin(angle), me->GetPositionZ(), 0.0f);
                             }
                     }
                     events.RescheduleEvent(14, 2000);
                     break;
                 case 14:
                     if (pInstance)
                     {
                         if (me->GetEntry() == NPC_JAINA_PART1)
{
                             Talk(SAY_JAINA_INTRO_3);
                             me->CastSpell(me, 70132, false);
                         }
                         else
{
                             me->CastSpell(me, 59514, false);
                             for (uint8 i = 0; i < 2; ++i)
                                 if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                     c->CastSpell(c, 70513, false);
                         }
                     }
                     events.RescheduleEvent(15, 2000);
                     break;
                 case 15:
                     if (pInstance)
                     {
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_EVENT_GUID)))
                             c->GetMotionMaster()->MovePoint(0, SBSTyrannusStartPos);
                         if (me->GetEntry() == NPC_JAINA_PART1)
{
                             for (uint8 i = 0; i < 2; ++i)
                                 if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                     c->CastSpell(c, 70464, false);
                         }
                     }
                     events.RescheduleEvent(16, 3000);
                     break;
                 case 16:
                     Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_4 : SAY_SYLVANAS_INTRO_3);
                     if (pInstance)
                     {
                         for (uint8 i = 0; i < 2; ++i)
                             if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GUARD_1_GUID + i)))
                                 c->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
{
                                 if (c->IsAlive())
{
                                     if (c->GetEntry() == NPC_KALIRA || c->GetEntry() == NPC_ELANDRA || c->GetEntry() == NPC_LORALEN || c->GetEntry() == NPC_KORELN)
                                         continue;
                                     Unit::Kill(c, c, false);
                                 }
                                 c->DespawnOrUnsummon(10000);
                             }
                         pInstance->SetData(DATA_INSTANCE_PROGRESS, INSTANCE_PROGRESS_FINISHED_INTRO);
                     }
                     events.RescheduleEvent(17, 5000);
                     break;
                 case 17:
                     me->setActive(false);
                     Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_5 : SAY_SYLVANAS_INTRO_4);
                     break;
             }
             if (!UpdateVictim())
                 return;
             DoMeleeAttackIfReady();
         }
References Unit::AddUnitMovementFlag(), SummonList::begin(), Unit::CastSpell(), counter, DATA_GUARD_1_GUID, DATA_INSTANCE_PROGRESS, DATA_NECROLYTE_1_GUID, DATA_NECROLYTE_2_GUID, DATA_TEAMID_IN_INSTANCE, DATA_TYRANNUS_EVENT_GUID, UnitAI::DoMeleeAttackIfReady(), EMOTE_STATE_READY1H, SummonList::end(), ChampionPosition::entry, frand(), Map::GetCreature(), ZoneScript::GetData(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), InstanceScript::instance, INSTANCE_PROGRESS_FINISHED_INTRO, introPositions, Unit::IsAlive(), Unit::IsInCombat(), Unit::Kill(), LeaderIntroPos, CreatureAI::me, MOVE_RUN, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NecrolytePos1, NecrolytePos2, NPC_ELANDRA, NPC_JAINA_PART1, NPC_KALIRA, NPC_KORELN, NPC_LORALEN, pInstance, PortalPos, rand_norm(), REACT_PASSIVE, Unit::RemoveAura(), SAY_JAINA_INTRO_1, SAY_JAINA_INTRO_2, SAY_JAINA_INTRO_3, SAY_JAINA_INTRO_4, SAY_JAINA_INTRO_5, SAY_SYLVANAS_INTRO_1, SAY_SYLVANAS_INTRO_2, SAY_SYLVANAS_INTRO_3, SAY_SYLVANAS_INTRO_4, SAY_TYRANNUS_INTRO_1, SAY_TYRANNUS_INTRO_2, SAY_TYRANNUS_INTRO_3, SAY_TYRANNUS_INTRO_4, SBSTyrannusStartPos, WorldObject::setActive(), ZoneScript::SetData(), Object::SetUInt32Value(), Unit::SetVisible(), SPELL_NECROLYTE_CHANNELING, WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEAM_ALLIANCE, UNIT_NPC_EMOTESTATE, UNIT_STATE_NO_ENVIRONMENT_UPD, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
counter
uint8 npc_pos_leader::npc_pos_leaderAI::counter
Definition at line 44 of file pit_of_saron.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
events
EventMap npc_pos_leader::npc_pos_leaderAI::events
Definition at line 41 of file pit_of_saron.cpp.
pInstance
InstanceScript* npc_pos_leader::npc_pos_leaderAI::pInstance
Definition at line 43 of file pit_of_saron.cpp.
Referenced by npc_pos_leaderAI(), Reset(), SetData(), and UpdateAI().
summons
SummonList npc_pos_leader::npc_pos_leaderAI::summons
Definition at line 42 of file pit_of_saron.cpp.
Referenced by JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp