Azerotcore-wotlk: deps/mysqllite/include/internal/thr_alarm.h File Reference
thr_alarm.h File Reference
Classes
struct st_alarm_info
struct st_alarm
Macros
#define USE_ONE_SIGNAL_HAND /* One must call process_alarm */
#define THR_SERVER_ALARM SIGALRM
#define thr_got_alarm(thr_alarm) (**(thr_alarm))
#define thr_alarm_init(A) (*(A))=0
#define thr_alarm_in_use(A) (*(A)!= 0)
Typedefs
typedef struct st_alarm_info ALARM_INFO
typedef int thr_alarm_entry
typedef thr_alarm_entry * thr_alarm_t
typedef struct st_alarm ALARM
Functions
void thr_alarm_info (ALARM_INFO *info)
void init_thr_alarm (uint max_alarm)
void resize_thr_alarm (uint max_alarms)
my_bool thr_alarm (thr_alarm_t *alarmed, uint sec, ALARM *buff)
void thr_alarm_kill (my_thread_id thread_id)
void thr_end_alarm (thr_alarm_t *alarmed)
void end_thr_alarm (my_bool free_structures)
sig_handler process_alarm (int)
Variables
uint thr_client_alarm
pthread_t alarm_thread
Macro Definition Documentation
thr_alarm_in_use
#define thr_alarm_in_use (A) (*(A)!= 0)
Definition at line 92 of file thr_alarm.h.
thr_alarm_init
#define thr_alarm_init (A) (*(A))=0
Definition at line 91 of file thr_alarm.h.
thr_got_alarm
#define thr_got_alarm (thr_alarm) (**(thr_alarm))
Definition at line 74 of file thr_alarm.h.
THR_SERVER_ALARM
#define THR_SERVER_ALARM SIGALRM
Definition at line 32 of file thr_alarm.h.
USE_ONE_SIGNAL_HAND
#define USE_ONE_SIGNAL_HAND /* One must call process_alarm */
Definition at line 25 of file thr_alarm.h.
Typedef Documentation
ALARM
typedef struct st_alarm ALARM
ALARM_INFO
typedef struct st_alarm_info ALARM_INFO
thr_alarm_entry
typedef int thr_alarm_entry
Definition at line 72 of file thr_alarm.h.
thr_alarm_t
typedef thr_alarm_entry* thr_alarm_t
Definition at line 78 of file thr_alarm.h.
Function Documentation
end_thr_alarm()
void end_thr_alarm (my_bool free_structures)
Definition at line 434 of file thr_alarm.c.
 {
   DBUG_ENTER("end_thr_alarm");
   if (alarm_aborted != 1)           /* If memory not freed */
   {
     mysql_mutex_lock(&LOCK_alarm);
     DBUG_PRINT("info",("Resheduling %d waiting alarms",alarm_queue.elements));
     alarm_aborted= -1;              /* mark aborted */
     if (alarm_queue.elements || (alarm_thread_running && free_structures))
     {
       if (pthread_equal(pthread_self(),alarm_thread))
     alarm(1);               /* Shut down everything soon */
       else
     reschedule_alarms();
     }
     if (free_structures)
     {
       struct timespec abstime;
       DBUG_ASSERT(!alarm_queue.elements);
       /* Wait until alarm thread dies */
       set_timespec(abstime, 10);        /* Wait up to 10 seconds */
       while (alarm_thread_running)
       {
         int error= mysql_cond_timedwait(&COND_alarm, &LOCK_alarm, &abstime);
     if (error == ETIME || error == ETIMEDOUT)
       break;                /* Don't wait forever */
       }
       delete_queue(&alarm_queue);
       alarm_aborted= 1;
       mysql_mutex_unlock(&LOCK_alarm);
       if (!alarm_thread_running)              /* Safety */
       {
         mysql_mutex_destroy(&LOCK_alarm);
         mysql_cond_destroy(&COND_alarm);
       }
     }
     else
       mysql_mutex_unlock(&LOCK_alarm);
   }
   DBUG_VOID_RETURN;
 }
References alarm_aborted, alarm_queue, alarm_thread, alarm_thread_running, COND_alarm, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, delete_queue(), st_queue::elements, error(), ETIME, LOCK_alarm, mysql_cond_destroy, mysql_cond_timedwait, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, st_my_thread_var::pthread_self, reschedule_alarms, and set_timespec.
init_thr_alarm()
void init_thr_alarm (uint max_alarm)
Definition at line 70 of file thr_alarm.c.
 {
   sigset_t s;
   DBUG_ENTER("init_thr_alarm");
   alarm_aborted=0;
   next_alarm_expire_time= ~ (time_t) 0;
   init_queue(&alarm_queue,max_alarms+1,offsetof(ALARM,expire_time),0,
          compare_ulong,NullS);
   sigfillset(&full_signal_set);         /* Neaded to block signals */
   mysql_mutex_init(key_LOCK_alarm, &LOCK_alarm, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_COND_alarm, &COND_alarm, NULL);
   if (thd_lib_detected == THD_LIB_LT)
     thr_client_alarm= SIGALRM;
   else
     thr_client_alarm= SIGUSR1;
 #ifndef USE_ALARM_THREAD
   if (thd_lib_detected != THD_LIB_LT)
 #endif
   {
     my_sigset(thr_client_alarm, thread_alarm);
   }
   sigemptyset(&s);
   sigaddset(&s, THR_SERVER_ALARM);
   alarm_thread=pthread_self();
 #if defined(USE_ALARM_THREAD)
   {
     pthread_attr_t thr_attr;
     pthread_attr_init(&thr_attr);
     pthread_attr_setscope(&thr_attr,PTHREAD_SCOPE_PROCESS);
     pthread_attr_setdetachstate(&thr_attr,PTHREAD_CREATE_DETACHED);
     pthread_attr_setstacksize(&thr_attr,8196);
     mysql_thread_create(key_thread_alarm,
                         &alarm_thread, &thr_attr, alarm_handler, NULL);
     pthread_attr_destroy(&thr_attr);
   }
 #elif defined(USE_ONE_SIGNAL_HAND)
   pthread_sigmask(SIG_BLOCK, &s, NULL);     /* used with sigwait() */
   if (thd_lib_detected == THD_LIB_LT)
   {
     my_sigset(thr_client_alarm, process_alarm);        /* Linuxthreads */
     pthread_sigmask(SIG_UNBLOCK, &s, NULL);
   }
 #else
   my_sigset(THR_SERVER_ALARM, process_alarm);
   pthread_sigmask(SIG_UNBLOCK, &s, NULL);
 #endif
   DBUG_VOID_RETURN;
 }
References alarm_aborted, alarm_queue, alarm_thread, compare_ulong(), COND_alarm, DBUG_ENTER, DBUG_VOID_RETURN, full_signal_set, init_queue(), LOCK_alarm, MY_MUTEX_INIT_FAST, my_sigset, mysql_cond_init, mysql_mutex_init, mysql_thread_create, next_alarm_expire_time, NULL, NullS, offsetof, process_alarm(), pthread_attr_setscope, pthread_attr_setstacksize, thd_lib_detected, THD_LIB_LT, thr_client_alarm, THR_SERVER_ALARM, and thread_alarm().
process_alarm()
sig_handler process_alarm (int)
resize_thr_alarm()
void resize_thr_alarm (uint max_alarms)
Definition at line 120 of file thr_alarm.c.
 {
   mysql_mutex_lock(&LOCK_alarm);
   /*
     It's ok not to shrink the queue as there may be more pending alarms than
     than max_alarms
   */
   if (alarm_queue.elements < max_alarms)
     resize_queue(&alarm_queue,max_alarms+1);
   mysql_mutex_unlock(&LOCK_alarm);
 }
References alarm_queue, st_queue::elements, LOCK_alarm, mysql_mutex_lock, mysql_mutex_unlock, and resize_queue().
thr_alarm()
my_bool thr_alarm (thr_alarm_t * alarmed, uint sec, ALARM * buff)
Definition at line 152 of file thr_alarm.c.
 {
   time_t now;
 #ifndef USE_ONE_SIGNAL_HAND
   sigset_t old_mask;
 #endif
   my_bool reschedule;
   struct st_my_thread_var *current_my_thread_var= my_thread_var;
   DBUG_ENTER("thr_alarm");
   DBUG_PRINT("enter",("thread: %s  sec: %d",my_thread_name(),sec));
   now= my_time(0);
 #ifndef USE_ONE_SIGNAL_HAND
   pthread_sigmask(SIG_BLOCK,&full_signal_set,&old_mask);
 #endif
   mysql_mutex_lock(&LOCK_alarm);        /* Lock from threads & alarms */
   if (alarm_aborted > 0)
   {                 /* No signal thread */
     DBUG_PRINT("info", ("alarm aborted"));
     *alrm= 0;                   /* No alarm */
     mysql_mutex_unlock(&LOCK_alarm);
 #ifndef USE_ONE_SIGNAL_HAND
     pthread_sigmask(SIG_SETMASK,&old_mask,NULL);
 #endif
     DBUG_RETURN(1);
   }
   if (alarm_aborted < 0)
     sec= 1;                 /* Abort mode */
   if (alarm_queue.elements >= max_used_alarms)
   {
     if (alarm_queue.elements == alarm_queue.max_elements)
     {
       DBUG_PRINT("info", ("alarm queue full"));
       fprintf(stderr,"Warning: thr_alarm queue is full\n");
       *alrm= 0;                 /* No alarm */
       mysql_mutex_unlock(&LOCK_alarm);
 #ifndef USE_ONE_SIGNAL_HAND
       pthread_sigmask(SIG_SETMASK,&old_mask,NULL);
 #endif
       DBUG_RETURN(1);
     }
     max_used_alarms=alarm_queue.elements+1;
   }
   reschedule= (ulong) next_alarm_expire_time > (ulong) now + sec;
   if (!alarm_data)
   {
     if (!(alarm_data=(ALARM*) my_malloc(sizeof(ALARM),MYF(MY_WME))))
     {
       DBUG_PRINT("info", ("failed my_malloc()"));
       *alrm= 0;                 /* No alarm */
       mysql_mutex_unlock(&LOCK_alarm);
 #ifndef USE_ONE_SIGNAL_HAND
       pthread_sigmask(SIG_SETMASK,&old_mask,NULL);
 #endif
       DBUG_RETURN(1);
     }
     alarm_data->malloced=1;
   }
   else
     alarm_data->malloced=0;
   alarm_data->expire_time=now+sec;
   alarm_data->alarmed=0;
   alarm_data->thread=    current_my_thread_var->pthread_self;
   alarm_data->thread_id= current_my_thread_var->id;
   queue_insert(&alarm_queue,(uchar*) alarm_data);
   /* Reschedule alarm if the current one has more than sec left */
   if (reschedule)
   {
     DBUG_PRINT("info", ("reschedule"));
     if (pthread_equal(pthread_self(),alarm_thread))
     {
       alarm(sec);               /* purecov: inspected */
       next_alarm_expire_time= now + sec;
     }
     else
       reschedule_alarms();          /* Reschedule alarms */
   }
   mysql_mutex_unlock(&LOCK_alarm);
 #ifndef USE_ONE_SIGNAL_HAND
   pthread_sigmask(SIG_SETMASK,&old_mask,NULL);
 #endif
   (*alrm)= &alarm_data->alarmed;
   DBUG_RETURN(0);
 }
References alarm_aborted, alarm_queue, alarm_thread, st_alarm::alarmed, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_queue::elements, st_alarm::expire_time, fprintf(), full_signal_set, st_my_thread_var::id, LOCK_alarm, st_alarm::malloced, st_queue::max_elements, max_used_alarms, my_malloc(), my_thread_name(), my_thread_var, my_time(), MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, next_alarm_expire_time, NULL, st_my_thread_var::pthread_self, queue_insert(), reschedule_alarms, sec, st_alarm::thread, and st_alarm::thread_id.
Referenced by CLI_MYSQL_REAL_CONNECT(), my_real_read(), and net_real_write().
thr_alarm_info()
void thr_alarm_info (ALARM_INFO * info)
Definition at line 504 of file thr_alarm.c.
 {
   mysql_mutex_lock(&LOCK_alarm);
   info->next_alarm_time= 0;
   info->max_used_alarms= max_used_alarms;
   if ((info->active_alarms=  alarm_queue.elements))
   {
     ulong now=(ulong) my_time(0);
     long time_diff;
     ALARM *alarm_data= (ALARM*) queue_top(&alarm_queue);
     time_diff= (long) (alarm_data->expire_time - now);
     info->next_alarm_time= (ulong) (time_diff < 0 ? 0 : time_diff);
   }
   mysql_mutex_unlock(&LOCK_alarm);
 }
References st_alarm_info::active_alarms, alarm_queue, st_queue::elements, st_alarm::expire_time, LOCK_alarm, st_alarm_info::max_used_alarms, max_used_alarms, my_time(), mysql_mutex_lock, mysql_mutex_unlock, st_alarm_info::next_alarm_time, and queue_top.
thr_alarm_kill()
void thr_alarm_kill (my_thread_id thread_id)
Definition at line 483 of file thr_alarm.c.
 {
   uint i;
   if (alarm_aborted)
     return;
   mysql_mutex_lock(&LOCK_alarm);
   for (i=0 ; i < alarm_queue.elements ; i++)
   {
     if (((ALARM*) queue_element(&alarm_queue,i))->thread_id == thread_id)
     {
       ALARM *tmp=(ALARM*) queue_remove(&alarm_queue,i);
       tmp->expire_time=0;
       queue_insert(&alarm_queue,(uchar*) tmp);
       reschedule_alarms();
       break;
     }
   }
   mysql_mutex_unlock(&LOCK_alarm);
 }
References alarm_aborted, alarm_queue, st_queue::elements, st_alarm::expire_time, LOCK_alarm, mysql_mutex_lock, mysql_mutex_unlock, queue_element, queue_insert(), queue_remove(), reschedule_alarms, and thread_id.
thr_end_alarm()
void thr_end_alarm (thr_alarm_t * alarmed)
Definition at line 244 of file thr_alarm.c.
 {
   ALARM *alarm_data;
 #ifndef USE_ONE_SIGNAL_HAND
   sigset_t old_mask;
 #endif
   uint i, found=0;
   DBUG_ENTER("thr_end_alarm");
 #ifndef USE_ONE_SIGNAL_HAND
   pthread_sigmask(SIG_BLOCK,&full_signal_set,&old_mask);
 #endif
   mysql_mutex_lock(&LOCK_alarm);
   alarm_data= (ALARM*) ((uchar*) *alarmed - offsetof(ALARM,alarmed));
   for (i=0 ; i < alarm_queue.elements ; i++)
   {
     if ((ALARM*) queue_element(&alarm_queue,i) == alarm_data)
     {
       queue_remove(&alarm_queue,i),MYF(0);
       if (alarm_data->malloced)
     my_free(alarm_data);
       found++;
 #ifdef DBUG_OFF
       break;
 #endif
     }
   }
   DBUG_ASSERT(!*alarmed || found == 1);
   if (!found)
   {
     if (*alarmed)
       fprintf(stderr,"Warning: Didn't find alarm 0x%lx in queue of %d alarms\n",
           (long) *alarmed, alarm_queue.elements);
     DBUG_PRINT("warning",("Didn't find alarm 0x%lx in queue\n",
               (long) *alarmed));
   }
   mysql_mutex_unlock(&LOCK_alarm);
 #ifndef USE_ONE_SIGNAL_HAND
   pthread_sigmask(SIG_SETMASK,&old_mask,NULL);
 #endif
   DBUG_VOID_RETURN;
 }
References alarm_queue, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_queue::elements, fprintf(), full_signal_set, LOCK_alarm, st_alarm::malloced, my_free(), MYF, mysql_mutex_lock, mysql_mutex_unlock, NULL, offsetof, queue_element, and queue_remove().
Referenced by CLI_MYSQL_REAL_CONNECT(), my_real_read(), and net_real_write().
Variable Documentation
alarm_thread
pthread_t alarm_thread extern
Definition at line 52 of file thr_alarm.c.
Referenced by end_thr_alarm(), init_thr_alarm(), process_alarm(), process_alarm_part2(), and thr_alarm().
thr_client_alarm
uint thr_client_alarm extern
Definition at line 38 of file thr_alarm.c.
Referenced by init_thr_alarm(), process_alarm(), and process_alarm_part2().