Azerotcore-wotlk: Guild::PlayerMoveItemData Class Reference
Guild::PlayerMoveItemData Class Reference
Public Member Functions
PlayerMoveItemData (Guild *guild, Player *player, uint8 container, uint8 slotId)
bool IsBank () const override
bool InitItem () override
void RemoveItem (CharacterDatabaseTransaction trans, MoveItemData *pOther, uint32 splitedAmount=0) override
Item * StoreItem (CharacterDatabaseTransaction trans, Item *pItem) override
void LogBankEvent (CharacterDatabaseTransaction trans, MoveItemData *pFrom, uint32 count) const override
Public Member Functions inherited from Guild::MoveItemData
MoveItemData (Guild *guild, Player *player, uint8 container, uint8 slotId)
virtual ~MoveItemData ()
virtual bool CheckItem (uint32 &splitedAmount)
virtual bool HasStoreRights (MoveItemData *) const
virtual bool HasWithdrawRights (MoveItemData *) const
bool CanStore (Item *pItem, bool swap, bool sendError)
bool CloneItem (uint32 count)
virtual void LogAction (MoveItemData *pFrom) const
void CopySlots (SlotIds &ids) const
Item * GetItem (bool isCloned=false) const
uint8 GetContainer () const
uint8 GetSlotId () const
Protected Member Functions
InventoryResult CanStore (Item *pItem, bool swap) override
Additional Inherited Members
Protected Attributes inherited from Guild::MoveItemData
Guild * m_pGuild
Player * m_pPlayer
uint8 m_container
uint8 m_slotId
Item * m_pItem
Item * m_pClonedItem
ItemPosCountVec m_vec
Detailed Description
Definition at line 625 of file Guild.h.
Constructor & Destructor Documentation
PlayerMoveItemData()
Guild::PlayerMoveItemData::PlayerMoveItemData (Guild * guild, Player * player, uint8 container, uint8 slotId) inline
Definition at line 628 of file Guild.h.
                                                                                         :
             MoveItemData(guild, player, container, slotId) { }
Member Function Documentation
CanStore()
InventoryResult Guild::PlayerMoveItemData::CanStore (Item * pItem, bool swap) inline override protected virtual
Implements Guild::MoveItemData.
Definition at line 906 of file Guild.cpp.
 {
     return m_pPlayer->CanStoreItem(m_container, m_slotId, m_vec, pItem, swap);
 }
References swap().
InitItem()
bool Guild::PlayerMoveItemData::InitItem () override virtual
Implements Guild::MoveItemData.
Definition at line 853 of file Guild.cpp.
 {
     m_pItem = m_pPlayer->GetItemByPos(m_container, m_slotId);
     if (m_pItem)
     {
         // Anti-WPE protection. Do not move non-empty bags to bank.
         if (m_pItem->IsNotEmptyBag())
         {
             m_pPlayer->SendEquipError(EQUIP_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS, m_pItem);
             m_pItem = nullptr;
         }
         // Bound items cannot be put into bank.
         else if (!m_pItem->CanBeTraded())
         {
             m_pPlayer->SendEquipError(EQUIP_ERR_ITEMS_CANT_BE_SWAPPED, m_pItem);
             m_pItem = nullptr;
         }
     }
     return (m_pItem != nullptr);
 }
References EQUIP_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS, and EQUIP_ERR_ITEMS_CANT_BE_SWAPPED.
IsBank()
bool Guild::PlayerMoveItemData::IsBank () const inline override virtual
Implements Guild::MoveItemData.
Definition at line 631 of file Guild.h.
 { return false; }
LogBankEvent()
void Guild::PlayerMoveItemData::LogBankEvent (CharacterDatabaseTransaction trans, MoveItemData * pFrom, uint32 count) const override virtual
Implements Guild::MoveItemData.
Definition at line 898 of file Guild.cpp.
 {
     ASSERT(pFrom);
     // Bank -> Char
     m_pGuild->_LogBankEvent(trans, GUILD_BANK_LOG_WITHDRAW_ITEM, pFrom->GetContainer(), m_pPlayer->GetGUID(),
                             pFrom->GetItem()->GetEntry(), count);
 }
References ASSERT, count(), Guild::MoveItemData::GetContainer(), Object::GetEntry(), Guild::MoveItemData::GetItem(), and GUILD_BANK_LOG_WITHDRAW_ITEM.
RemoveItem()
void Guild::PlayerMoveItemData::RemoveItem (CharacterDatabaseTransaction trans, MoveItemData * pOther, uint32 splitedAmount = 0) override virtual
Implements Guild::MoveItemData.
Definition at line 874 of file Guild.cpp.
 {
     if (splitedAmount)
     {
         m_pItem->SetCount(m_pItem->GetCount() - splitedAmount);
         m_pItem->SetState(ITEM_CHANGED, m_pPlayer);
         m_pPlayer->SaveInventoryAndGoldToDB(trans);
     }
     else
     {
         m_pPlayer->MoveItemFromInventory(m_container, m_slotId, true);
         m_pItem->DeleteFromInventoryDB(trans);
         m_pItem = nullptr;
     }
 }
References ITEM_CHANGED.
StoreItem()
Item * Guild::PlayerMoveItemData::StoreItem (CharacterDatabaseTransaction trans, Item * pItem) override virtual
Implements Guild::MoveItemData.
Definition at line 890 of file Guild.cpp.
 {
     ASSERT(pItem);
     m_pPlayer->MoveItemToInventory(m_vec, pItem, true);
     m_pPlayer->SaveInventoryAndGoldToDB(trans);
     return pItem;
 }
References ASSERT.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp