Azerotcore-wotlk: HomeMovementGenerator< Creature > Class Reference
HomeMovementGenerator< Creature > Class Reference
#include <HomeMovementGenerator.h>
Public Member Functions
HomeMovementGenerator ()
~HomeMovementGenerator ()
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoReset (Creature *)
bool DoUpdate (Creature *, const uint32)
MovementGeneratorType GetMovementGeneratorType ()
void unitSpeedChanged ()
Public Member Functions inherited from MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual bool GetResetPosition (float &, float &, float &)
Private Member Functions
void _setTargetLocation (Creature *)
Private Attributes
bool arrived: 1
bool i_recalculateTravel: 1
Detailed Description
Definition at line 29 of file HomeMovementGenerator.h.
Constructor & Destructor Documentation
HomeMovementGenerator()
HomeMovementGenerator< Creature >::HomeMovementGenerator () inline
Definition at line 32 of file HomeMovementGenerator.h.
 : arrived(false), i_recalculateTravel(false) {}
~HomeMovementGenerator()
HomeMovementGenerator< Creature >::~HomeMovementGenerator () inline
Definition at line 33 of file HomeMovementGenerator.h.
 {}
Member Function Documentation
_setTargetLocation()
void HomeMovementGenerator< Creature >::_setTargetLocation (Creature * owner) private
Definition at line 49 of file HomeMovementGenerator.cpp.
 {
     // Xinef: dont interrupt in any cast!
     //if (owner->HasUnitState(UNIT_STATE_ROOT | UNIT_STATE_STUNNED | UNIT_STATE_DISTRACTED))
     //    return;
     Movement::MoveSplineInit init(owner);
     float x, y, z, o;
     // Xinef: if there is motion generator on controlled slot, this one is not updated
     // Xinef: always get reset pos from idle slot
     MovementGenerator* gen = owner->GetMotionMaster()->GetMotionSlot(MOTION_SLOT_IDLE);
     if (owner->GetMotionMaster()->empty() || !gen || !gen->GetResetPosition(x, y, z))
     {
         owner->GetHomePosition(x, y, z, o);
         init.SetFacing(o);
     }
     owner->UpdateAllowedPositionZ(x, y, z);
     init.MoveTo(x, y, z, DisableMgr::IsPathfindingEnabled(owner->FindMap()), true);
     init.SetWalk(false);
     init.Launch();
     arrived = false;
     owner->ClearUnitState(uint32(UNIT_STATE_ALL_STATE & ~(UNIT_STATE_POSSESSED | UNIT_STATE_EVADE | UNIT_STATE_IGNORE_PATHFINDING | UNIT_STATE_NO_ENVIRONMENT_UPD)));
 }
References Unit::ClearUnitState(), MotionMaster::empty(), WorldObject::FindMap(), Creature::GetHomePosition(), Unit::GetMotionMaster(), MotionMaster::GetMotionSlot(), MovementGenerator::GetResetPosition(), DisableMgr::IsPathfindingEnabled(), Movement::MoveSplineInit::Launch(), MOTION_SLOT_IDLE, Movement::MoveSplineInit::MoveTo(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetWalk(), UNIT_STATE_ALL_STATE, UNIT_STATE_EVADE, UNIT_STATE_IGNORE_PATHFINDING, UNIT_STATE_NO_ENVIRONMENT_UPD, UNIT_STATE_POSSESSED, and WorldObject::UpdateAllowedPositionZ().
DoFinalize()
void HomeMovementGenerator< Creature >::DoFinalize (Creature * owner)
Definition at line 30 of file HomeMovementGenerator.cpp.
 {
     owner->ClearUnitState(UNIT_STATE_EVADE);
     if (arrived)
     {
         // Xinef: npc run by default
         //owner->SetWalk(true);
         owner->LoadCreaturesAddon(true);
         owner->AI()->JustReachedHome();
     }
     if (!owner->HasSwimmingFlagOutOfCombat())
         owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING);
 }
References Creature::AI(), Unit::ClearUnitState(), Creature::HasSwimmingFlagOutOfCombat(), CreatureAI::JustReachedHome(), Creature::LoadCreaturesAddon(), Object::RemoveFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING, and UNIT_STATE_EVADE.
DoInitialize()
void HomeMovementGenerator< Creature >::DoInitialize (Creature * owner)
Definition at line 25 of file HomeMovementGenerator.cpp.
 {
     _setTargetLocation(owner);
 }
DoReset()
void HomeMovementGenerator< Creature >::DoReset (Creature *)
Definition at line 45 of file HomeMovementGenerator.cpp.
 {
 }
DoUpdate()
bool HomeMovementGenerator< Creature >::DoUpdate (Creature * owner, const uint32)
Definition at line 76 of file HomeMovementGenerator.cpp.
 {
     arrived = owner->movespline->Finalized();
     if (arrived)
         return false;
     if (i_recalculateTravel)
     {
         _setTargetLocation(owner);
         i_recalculateTravel = false;
     }
     return true;
 }
References Movement::MoveSpline::Finalized(), and Unit::movespline.
GetMovementGeneratorType()
MovementGeneratorType HomeMovementGenerator< Creature >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 39 of file HomeMovementGenerator.h.
 { return HOME_MOTION_TYPE; }
References HOME_MOTION_TYPE.
unitSpeedChanged()
void HomeMovementGenerator< Creature >::unitSpeedChanged () inline virtual
Reimplemented from MovementGenerator.
Definition at line 40 of file HomeMovementGenerator.h.
 { i_recalculateTravel = true; }
Member Data Documentation
arrived
bool HomeMovementGenerator< Creature >::arrived private
Definition at line 44 of file HomeMovementGenerator.h.
i_recalculateTravel
bool HomeMovementGenerator< Creature >::i_recalculateTravel private
Definition at line 45 of file HomeMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/HomeMovementGenerator.h
src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp