Azerotcore-wotlk: spell_q13011_bear_flank_master Class Reference
spell_q13011_bear_flank_master Class Reference
Private Member Functions
PrepareSpellScript (spell_q13011_bear_flank_master)
bool Validate (SpellInfo const *) override
bool Load () override
void HandleScript (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2025 of file spell_quest.cpp.
Member Function Documentation
HandleScript()
void spell_q13011_bear_flank_master::HandleScript (SpellEffIndex) inline private
Definition at line 2039 of file spell_quest.cpp.
         {
             bool failed = RAND(0, 1); // 50% chance
             Creature* creature = GetCaster()->ToCreature();
             if (Player* player = GetHitPlayer())
             {
                 if (failed)
                 {
                     player->CastSpell(creature, SPELL_BEAR_FLANK_FAIL);
                     creature->AI()->Talk(0, player);
                 }
                 else
                     player->CastSpell(player, SPELL_CREATE_BEAR_FLANK);
             }
         }
References Creature::AI(), Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetHitPlayer(), RAND(), SPELL_BEAR_FLANK_FAIL, SPELL_CREATE_BEAR_FLANK, CreatureAI::Talk(), and Object::ToCreature().
Referenced by Register().
Load()
bool spell_q13011_bear_flank_master::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 2034 of file spell_quest.cpp.
         {
             return GetCaster()->GetTypeId() == TYPEID_UNIT;
         }
References SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_UNIT.
PrepareSpellScript()
spell_q13011_bear_flank_master::PrepareSpellScript (spell_q13011_bear_flank_master) private
Register()
void spell_q13011_bear_flank_master::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2055 of file spell_quest.cpp.
         {
             OnEffectHitTarget += SpellEffectFn(spell_q13011_bear_flank_master::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
         }
References EFFECT_0, HandleScript(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, and SpellEffectFn.
Validate()
bool spell_q13011_bear_flank_master::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 2029 of file spell_quest.cpp.
         {
             return ValidateSpellInfo({ SPELL_BEAR_FLANK_MASTER, SPELL_CREATE_BEAR_FLANK });
         }
References SPELL_BEAR_FLANK_MASTER, SPELL_CREATE_BEAR_FLANK, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_quest.cpp