Azerotcore-wotlk: src/common/Utilities/MathUtil.h File Reference
MathUtil.h File Reference
#include <algorithm>
#include <iterator>
#include <numeric>
#include <vector>
Functions
template<typename Container , typename T = typename std::decay<decltype(*std::begin(std::declval<Container>()))>::type>
T standard_deviation (Container &&c)
template<typename Container , typename T = typename std::decay<decltype(*std::begin(std::declval<Container>()))>::type>
T mean (Container &&c)
template<typename T >
T median (std::vector< T > a)
Function Documentation
mean()
template<typename Container , typename T = typename std::decay<decltype(*std::begin(std::declval<Container>()))>::type> T mean (Container && c) inline
Definition at line 49 of file MathUtil.h.
 {
     auto b = std::begin(c), e = std::end(c);
     auto size = std::distance(b, e);
     auto sum = std::accumulate(b, e, T());
     return sum / size;
 }
Referenced by WorldSession::ComputeNewClockDelta(), and standard_deviation().
median()
template<typename T > T median (std::vector< T > a) inline
Definition at line 59 of file MathUtil.h.
 {
     size_t n = a.size();
     // If size of the arr[] is even
     if (n % 2 == 0)
     {
         // Applying nth_element
         // on n/2th index
         std::nth_element(a.begin(),
             a.begin() + n / 2,
             a.end());
         // Applying nth_element
         // on (n-1)/2 th index
         std::nth_element(a.begin(),
             a.begin() + (n - 1) / 2,
             a.end());
         // Find the average of value at
         // index N/2 and (N-1)/2
         return (T)(a[(n - 1) / 2]
             + a[n / 2])
             / 2.0;
     }
     // If size of the arr[] is odd
     else
     {
         // Applying nth_element
         // on n/2
         std::nth_element(a.begin(),
             a.begin() + n / 2,
             a.end());
         // Value at index (N/2)th
         // is the median
         return (T)a[n / 2];
     }
 }
Referenced by WorldSession::ComputeNewClockDelta().
standard_deviation()
template<typename Container , typename T = typename std::decay<decltype(*std::begin(std::declval<Container>()))>::type> T standard_deviation (Container && c) inline
Definition at line 28 of file MathUtil.h.
 {
     auto b = std::begin(c), e = std::end(c);
     auto size = std::distance(b, e);
     auto sum = std::accumulate(b, e, T());
     auto mean = sum / size;
     if (size == 1)
     {
         return (T) 0;
     }
     T accum = T();
     for (const auto d : c)
     {
         accum += (d - mean) * (d - mean);
     }
     return std::sqrt(accum / (size - 1));
 }
References mean().
Referenced by WorldSession::ComputeNewClockDelta().