Azerotcore-wotlk: deps/zlib/minigzip.c File Reference
minigzip.c File Reference
#include "zlib.h"
#include <stdio.h>
Macros
#define SET_BINARY_MODE(file)
#define GZ_SUFFIX ".gz"
#define SUFFIX_LEN (sizeof(GZ_SUFFIX)-1)
#define BUFLEN 16384
#define MAX_NAME_LEN 1024
#define local
Functions
int unlink OF ((const char *))
void error OF ((const char *msg))
void gz_compress OF ((FILE *in, gzFile out))
void gz_uncompress OF ((gzFile in, FILE *out))
void file_compress OF ((char *file, char *mode))
void file_uncompress OF ((char *file))
int main OF ((int argc, char *argv[]))
void error (char *msg) const
void gz_compress (FILE *in, gzFile out)
void gz_uncompress (gzFile in, FILE *out)
void file_compress (char *file, char *mode)
void file_uncompress (char *file)
int main (int argc, argv)
Variables
char * prog
Macro Definition Documentation
BUFLEN
#define BUFLEN 16384
Definition at line 131 of file minigzip.c.
GZ_SUFFIX
#define GZ_SUFFIX ".gz"
Definition at line 127 of file minigzip.c.
local
#define local
Definition at line 138 of file minigzip.c.
MAX_NAME_LEN
#define MAX_NAME_LEN 1024
Definition at line 132 of file minigzip.c.
SET_BINARY_MODE
#define SET_BINARY_MODE (file)
Definition at line 40 of file minigzip.c.
SUFFIX_LEN
#define SUFFIX_LEN (sizeof(GZ_SUFFIX)-1)
Definition at line 129 of file minigzip.c.
Function Documentation
error()
void error (char * msg) const
Definition at line 156 of file minigzip.c.
 {
     fprintf(stderr, "%s: %s\n", prog, msg);
     exit(1);
 }
References fprintf(), and prog.
Referenced by DatabaseLoader::AddDatabase(), AsyncAcceptor::AsyncAccept(), AsyncAcceptor::AsyncAcceptWithCallback(), SecretMgr::AttemptLoad(), BanExpiryHandler(), bin2decimal(), CLI_MYSQL_REAL_CONNECT(), cli_read_query_result(), Metric::Connect(), decimal2bin(), decimal2double(), decimal2string(), decimal_mul(), decimal_round(), do_add(), do_div_mod(), do_sub(), end_io_cache(), end_thr_alarm(), eval_num_suffix(), fetch_long_with_conversion(), find_key_block(), flush_cached_blocks(), flush_key_blocks_int(), detail::for_each_codepoint(), detail::dragonbox::cache_accessor< double >::get_cached_power(), detail::get_round_direction(), getopt_double(), detail::grisu_gen_digits(), gz_compress(), gz_uncompress(), handle_options(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugSendBuyErrorCommand(), debug_commandscript::HandleDebugSendEquipErrorCommand(), debug_commandscript::HandleDebugSendSellErrorCommand(), WorldSession::HandleGrantLevel(), Socket< T >::HandleQueue(), FreezeDetector::Handler(), misc_commandscript::HandleSkirmishCommand(), init_key_cache(), internal_str2dec(), IsIPAddress(), KeepDatabaseAliveHandler(), key_cache_insert(), key_cache_read(), key_cache_write(), libmpq__archive_open(), libmpq__block_open_offset(), list_walk(), G3D::GImage::load(), ObjectMgr::LoadLinkedRespawn(), main(), my_atof(), my_block_write(), my_dir(), my_fcvt(), my_gcvt(), my_hash_check(), my_load_defaults(), my_message(), my_pread(), my_printf_error(), my_printv_error(), my_pwrite(), my_read_charset_file(), my_redel(), my_rename(), my_search_option_files(), my_stat(), my_strntoull10rnd_8bit(), my_strtod(), my_strtod_int(), my_strtoll10(), my_strtoll10_8bit(), my_thread_global_end(), my_thread_init(), my_well_formed_len_8bit(), mysql_select_db(), net_flush(), detail::fixed_handler::on_digit(), detail::fixed_handler::on_start(), DatabaseWorkerPool< T >::Open(), DatabaseWorkerPool< T >::OpenConnections(), prof_lookup(), Socket< T >::ReadHandlerInternal(), RASession::ReadString(), real_open_cached_file(), safe_hash_set(), search_default_file(), send_change_user_packet(), send_client_reply_packet(), Player::SendLootError(), WorldSession::SendPetNameInvalid(), setval(), SignalHandler(), stmt_read_row_unbuffered(), Acore::StringFormat(), lfg::LFGMgr::TeleportPlayer(), tree_walk_left_root_right(), tree_walk_right_root_left(), tsd_cleanup_wrapper(), tsd_wrapper_get(), ull2dec(), RealmList::UpdateRealms(), utf8_to_utf16::utf8_to_utf16(), and Socket< T >::~Socket().
file_compress()
void file_compress (char * file, char * mode)
Definition at line 262 of file minigzip.c.
 {
     local char outfile[MAX_NAME_LEN];
     FILE  *in;
     gzFile out;
     if (strlen(file) + strlen(GZ_SUFFIX) >= sizeof(outfile)) {
         fprintf(stderr, "%s: filename too long\n", prog);
         exit(1);
     }
     strcpy(outfile, file);
     strcat(outfile, GZ_SUFFIX);
     in = fopen(file, "rb");
     if (in == NULL) {
         perror(file);
         exit(1);
     }
     out = gzopen(outfile, mode);
     if (out == NULL) {
         fprintf(stderr, "%s: can't gzopen %s\n", prog, outfile);
         exit(1);
     }
     gz_compress(in, out);
     unlink(file);
 }
References mpq::file, fprintf(), gz_compress(), GZ_SUFFIX, gzopen(), local, MAX_NAME_LEN, NULL, perror(), and prog.
Referenced by main().
file_uncompress()
void file_uncompress (char * file)
Definition at line 297 of file minigzip.c.
 {
     local char buf[MAX_NAME_LEN];
     char *infile, *outfile;
     FILE  *out;
     gzFile in;
     size_t len = strlen(file);
     if (len + strlen(GZ_SUFFIX) >= sizeof(buf)) {
         fprintf(stderr, "%s: filename too long\n", prog);
         exit(1);
     }
     strcpy(buf, file);
     if (len > SUFFIX_LEN && strcmp(file+len-SUFFIX_LEN, GZ_SUFFIX) == 0) {
         infile = file;
         outfile = buf;
         outfile[len-3] = '\0';
     } else {
         outfile = file;
         infile = buf;
         strcat(infile, GZ_SUFFIX);
     }
     in = gzopen(infile, "rb");
     if (in == NULL) {
         fprintf(stderr, "%s: can't gzopen %s\n", prog, infile);
         exit(1);
     }
     out = fopen(outfile, "wb");
     if (out == NULL) {
         perror(file);
         exit(1);
     }
     gz_uncompress(in, out);
     unlink(infile);
 }
References mpq::file, fprintf(), GZ_SUFFIX, gz_uncompress(), gzopen(), local, MAX_NAME_LEN, NULL, perror(), prog, and SUFFIX_LEN.
Referenced by main().
gz_compress()
void gz_compress (FILE * in, gzFile out)
Definition at line 167 of file minigzip.c.
 {
     local char buf[BUFLEN];
     int len;
     int err;
 #ifdef USE_MMAP
     /* Try first compressing with mmap. If mmap fails (minigzip used in a
      * pipe), use the normal fread loop.
      */
     if (gz_compress_mmap(in, out) == Z_OK) return;
 #endif
     for (;;) {
         len = (int)fread(buf, 1, sizeof(buf), in);
         if (ferror(in)) {
             perror("fread");
             exit(1);
         }
         if (len == 0) break;
         if (gzwrite(out, buf, (unsigned)len) != len) error(gzerror(out, &err));
     }
     fclose(in);
     if (gzclose(out) != Z_OK) error("failed gzclose");
 }
References BUFLEN, error(), gzclose(), gzerror(), gzwrite(), local, perror(), and Z_OK.
Referenced by file_compress(), and main().
gz_uncompress()
void gz_uncompress (gzFile in, FILE * out)
Definition at line 235 of file minigzip.c.
 {
     local char buf[BUFLEN];
     int len;
     int err;
     for (;;) {
         len = gzread(in, buf, sizeof(buf));
         if (len < 0) error (gzerror(in, &err));
         if (len == 0) break;
         if ((int)fwrite(buf, 1, (unsigned)len, out) != len) {
             error("failed fwrite");
         }
     }
     if (fclose(out)) error("failed fclose");
     if (gzclose(in) != Z_OK) error("failed gzclose");
 }
References BUFLEN, error(), gzclose(), gzerror(), gzread(), local, and Z_OK.
Referenced by file_uncompress(), and main().
main()
int main (int argc, argv)
Definition at line 349 of file minigzip.c.
 {
     int copyout = 0;
     int uncompr = 0;
     gzFile file;
     char *bname, outmode[20];
     strcpy(outmode, "wb6 ");
     prog = argv[0];
     bname = strrchr(argv[0], '/');
     if (bname)
       bname++;
     else
       bname = argv[0];
     argc--, argv++;
     if (!strcmp(bname, "gunzip"))
       uncompr = 1;
     else if (!strcmp(bname, "zcat"))
       copyout = uncompr = 1;
     while (argc > 0) {
       if (strcmp(*argv, "-c") == 0)
         copyout = 1;
       else if (strcmp(*argv, "-d") == 0)
         uncompr = 1;
       else if (strcmp(*argv, "-f") == 0)
         outmode[3] = 'f';
       else if (strcmp(*argv, "-h") == 0)
         outmode[3] = 'h';
       else if (strcmp(*argv, "-r") == 0)
         outmode[3] = 'R';
       else if ((*argv)[0] == '-' && (*argv)[1] >= '1' && (*argv)[1] <= '9' &&
                (*argv)[2] == 0)
         outmode[2] = (*argv)[1];
       else
         break;
       argc--, argv++;
     }
     if (outmode[3] == ' ')
         outmode[3] = 0;
     if (argc == 0) {
         SET_BINARY_MODE(stdin);
         SET_BINARY_MODE(stdout);
         if (uncompr) {
             file = gzdopen(fileno(stdin), "rb");
             if (file == NULL) error("can't gzdopen stdin");
             gz_uncompress(file, stdout);
         } else {
             file = gzdopen(fileno(stdout), outmode);
             if (file == NULL) error("can't gzdopen stdout");
             gz_compress(stdin, file);
         }
     } else {
         if (copyout) {
             SET_BINARY_MODE(stdout);
         }
         do {
             if (uncompr) {
                 if (copyout) {
                     file = gzopen(*argv, "rb");
                     if (file == NULL)
                         fprintf(stderr, "%s: can't gzopen %s\n", prog, *argv);
                     else
                         gz_uncompress(file, stdout);
                 } else {
                     file_uncompress(*argv);
                 }
             } else {
                 if (copyout) {
                     FILE * in = fopen(*argv, "rb");
                     if (in == NULL) {
                         perror(*argv);
                     } else {
                         file = gzdopen(fileno(stdout), outmode);
                         if (file == NULL) error("can't gzdopen stdout");
                         gz_compress(in, file);
                     }
                 } else {
                     file_compress(*argv, outmode);
                 }
             }
         } while (argv++, --argc);
     }
     return 0;
 }
References error(), mpq::file, file_compress(), file_uncompress(), fprintf(), gz_compress(), gz_uncompress(), gzdopen(), gzopen(), NULL, perror(), prog, and SET_BINARY_MODE.
OF() [1/7]
void file_uncompress OF ((char *file))
OF() [2/7]
void file_compress OF ((char *file, char *mode))
OF() [3/7]
int unlink OF ((const char *))
OF() [4/7]
void error OF ((const char *msg))
OF() [5/7]
void gz_compress OF ((FILE *in, gzFile out))
OF() [6/7]
void gz_uncompress OF ((gzFile in, FILE *out))
OF() [7/7]
int main OF ((int argc, char *argv[]))
Variable Documentation
prog
char* prog
Definition at line 141 of file minigzip.c.
Referenced by error(), file_compress(), file_uncompress(), main(), my_path(), and usage().