Azerotcore-wotlk: WorldLocation Class Reference
WorldLocation Class Reference
#include <Object.h>
Public Member Functions
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Attributes
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Additional Inherited Members
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Detailed Description
Definition at line 460 of file Object.h.
Constructor & Destructor Documentation
WorldLocation() [1/2]
WorldLocation::WorldLocation (uint32 _mapId = MAPID_INVALID, float x = 0.f, float y = 0.f, float z = 0.f, float o = 0.f) inline explicit
Definition at line 463 of file Object.h.
         : Position(x, y, z, o), m_mapId(_mapId) { }
Referenced by Player::_LoadEntryPointData(), Player::GetStartPosition(), Player::SetEntryPoint(), and Player::TeleportTo().
WorldLocation() [2/2]
WorldLocation::WorldLocation (uint32 mapId, Position const & position) inline
Definition at line 466 of file Object.h.
         : Position(position), m_mapId(mapId) { }
Member Function Documentation
GetMapId()
uint32 WorldLocation::GetMapId () const inline
Definition at line 486 of file Object.h.
     {
         return m_mapId;
     }
References m_mapId.
Referenced by Group::_homebindIfInstance(), Player::_LoadItem(), KillRewarder::_RewardGroup(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), Player::ActivateTaxiPathTo(), WorldObject::AddObjectToRemoveList(), Map::AddObjectToRemoveList(), Map::AddObjectToSwitchList(), Pet::AddToWorld(), Player::BuildPlayerRepop(), Player::CalculateTalentsPoints(), Group::CanJoinBattlegroundQueue(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), Player::ContinueTaxiFlight(), BattlegroundSA::DefendersPortalTeleport(), Player::DestroyZoneLimitedItem(), go_commandscript::DoTeleport(), ScriptedAI::DoTeleportAll(), ScriptedAI::DoTeleportPlayer(), FlightPathMovementGenerator::DoUpdate(), Spell::EffectBind(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Spell::EffectTeleportUnits(), Battleground::EndBattleground(), SendEncounterUnit::Execute(), Unit::ExecuteDelayedUnitRelocationEvent(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::FindNextKeg(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::FinishAttackDueToWin(), lfg::LFGMgr::FinishDungeon(), Acore::XP::Gain(), MapMgr::GetAreaId(), Graveyard::GetClosestGraveyard(), Player::GetNextQuest(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::GetRandomBartender(), MapMgr::GetZoneId(), Group::GroupLoot(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCorpseQueryOpcode(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoXYZCommand(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleGroupInviteOpcode(), misc_commandscript::HandleGroupSummonCommand(), instance_commandscript::HandleInstanceUnbindCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::HandleScriptEffect(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), tele_commandscript::HandleTeleCommand(), Player::HasCorpse(), Player::IsAtRecruitAFriendDistance(), DisableMgr::IsDisabledFor(), Unit::isInAccessiblePlaceFor(), Player::IsInAreaTriggerRadius(), WorldObject::IsInWintergrasp(), MapMgr::IsValidMapCoord(), Player::KillPlayer(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::Load(), Player::LoadCorpse(), Player::LoadFromDB(), LogCommandUsage(), lfg::LFGMgr::MakeNewGroup(), AchievementCriteriaData::Meets(), npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI::MoveInLineOfSight(), Unit::NearTeleportTo(), Group::NeedBeforeGreed(), Unit::OutDebugInfo(), PathGenerator::PathGenerator(), MapMgr::PlayerCannotEnter(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), Player::PrepareQuestMenu(), BfGraveyard::RelocateDeadPlayers(), spell_quest_dragonmaw_race_generic::RelocateDest(), Group::RemoveMember(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Spell::SelectImplicitCasterDestTargets(), Player::SendInitWorldStates(), WorldSession::SendLearnNewTaxiNode(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Pet::setDeathState(), Player::SetEntryPoint(), Player::SetHomebind(), Player::SetMover(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), lfg::LFGMgr::TeleportPlayer(), Player::TeleportTo(), Player::Update(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), Player::UpdateAreaDependentAuras(), GameObject::Use(), and WorldRelocate().
GetWorldLocation() [1/5]
WorldLocation WorldLocation::GetWorldLocation () const inline
Definition at line 524 of file Object.h.
     {
         return *this;
     }
GetWorldLocation() [2/5]
void WorldLocation::GetWorldLocation (uint32 & mapId, float & x, float & y) const inline
Definition at line 491 of file Object.h.
     {
         mapId = m_mapId;
         x = m_positionX;
         y = m_positionY;
     }
References m_mapId, Position::m_positionX, and Position::m_positionY.
Referenced by Spell::EffectBind(), Graveyard::GetClosestGraveyard(), and lfg::LFGMgr::TeleportPlayer().
GetWorldLocation() [3/5]
void WorldLocation::GetWorldLocation (uint32 & mapId, float & x, float & y, float & z) const inline
Definition at line 498 of file Object.h.
     {
         mapId = m_mapId;
         x = m_positionX;
         y = m_positionY;
         z = m_positionZ;
     }
References m_mapId, Position::m_positionX, Position::m_positionY, and Position::m_positionZ.
GetWorldLocation() [4/5]
void WorldLocation::GetWorldLocation (uint32 & mapId, float & x, float & y, float & z, float & o) const inline
Definition at line 506 of file Object.h.
     {
         mapId = m_mapId;
         x = m_positionX;
         y = m_positionY;
         z = m_positionZ;
         o = m_orientation;
     }
References m_mapId, Position::m_orientation, Position::m_positionX, Position::m_positionY, and Position::m_positionZ.
GetWorldLocation() [5/5]
void WorldLocation::GetWorldLocation (WorldLocation * location) const inline
Definition at line 515 of file Object.h.
     {
         if (location)
         {
             location->Relocate(m_positionX, m_positionY, m_positionZ, m_orientation);
             location->SetMapId(m_mapId);
         }
     }
References m_mapId, Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, Position::Relocate(), and SetMapId().
SetMapId()
void WorldLocation::SetMapId (uint32 mapId) inline
Definition at line 481 of file Object.h.
     {
         m_mapId = mapId;
     }
References m_mapId.
Referenced by GetWorldLocation().
WorldRelocate() [1/2]
void WorldLocation::WorldRelocate (const WorldLocation & loc) inline
Definition at line 469 of file Object.h.
     {
         m_mapId = loc.GetMapId();
         Relocate(loc);
     }
References GetMapId(), m_mapId, and Position::Relocate().
Referenced by Player::CreateCorpse(), Spell::EffectBind(), WorldSession::HandleCharFactionOrRaceChangeCallback(), Player::LoadCorpse(), Player::RemovedInsignia(), and Player::SpawnCorpseBones().
WorldRelocate() [2/2]
void WorldLocation::WorldRelocate (uint32 mapId = MAPID_INVALID, float x = 0.f, float y = 0.f, float z = 0.f, float o = 0.f) inline
Definition at line 475 of file Object.h.
     {
         m_mapId = mapId;
         Relocate(x, y, z, o);
     }
References m_mapId, and Position::Relocate().
Member Data Documentation
m_mapId
uint32 WorldLocation::m_mapId
Definition at line 529 of file Object.h.
Referenced by GetMapId(), GetWorldLocation(), Player::SetEntryPoint(), WorldObject::SetLocationMapId(), WorldObject::SetMap(), SetMapId(), BattlefieldWG::SetupBattlefield(), SpellDestination::SpellDestination(), Player::TeleportToEntryPoint(), and WorldRelocate().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/Object.h