Azerotcore-wotlk: boss_malchezaar::boss_malchezaarAI Struct Reference
boss_malchezaar::boss_malchezaarAI Struct Reference
Public Member Functions
boss_malchezaarAI (Creature *creature)
void Initialize ()
void clearweapons ()
void Reset () override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void SummonAxes ()
void EnfeebleHealthEffect ()
void EnfeebleResetHealth ()
void SummonInfernal ()
void Phase2 ()
void Phase3 ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 EnfeebleTimer
uint32 EnfeebleResetTimer
uint32 ShadowNovaTimer
uint32 SWPainTimer
uint32 SunderArmorTimer
uint32 AmplifyDamageTimer
uint32 InfernalTimer
uint32 InfernalCleanupTimer
uint32 phase
uint32 enfeeble_health [5]
ObjectGuid enfeeble_targets [5]
GuidVector infernals
std::vector< InfernalPoint * > positions
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 171 of file boss_prince_malchezaar.cpp.
Constructor & Destructor Documentation
boss_malchezaarAI()
boss_malchezaar::boss_malchezaarAI::boss_malchezaarAI (Creature * creature) inline
Definition at line 173 of file boss_prince_malchezaar.cpp.
                                               : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
clearweapons()
void boss_malchezaar::boss_malchezaarAI::clearweapons () inline
Definition at line 210 of file boss_prince_malchezaar.cpp.
         {
             SetEquipmentSlots(false, EQUIP_UNEQUIP, EQUIP_UNEQUIP, EQUIP_NO_CHANGE);
             me->SetCanDualWield(false);
         }
References EQUIP_NO_CHANGE, EQUIP_UNEQUIP, ScriptedAI::me, Creature::SetCanDualWield(), and ScriptedAI::SetEquipmentSlots().
Referenced by Initialize(), and Phase3().
EnfeebleHealthEffect()
void boss_malchezaar::boss_malchezaarAI::EnfeebleHealthEffect () inline
Definition at line 248 of file boss_prince_malchezaar.cpp.
         {
             const SpellInfo* info = sSpellMgr->GetSpellInfo(SPELL_ENFEEBLE_EFFECT);
             if (!info)
                 return;
             ThreatContainer::StorageType const& t_list = me->getThreatMgr().getThreatList();
             std::vector<Unit*> targets;
             if (t_list.empty())
                 return;
             //begin + 1, so we don't target the one with the highest threat
             ThreatContainer::StorageType::const_iterator itr = t_list.begin();
             std::advance(itr, 1);
             for (; itr != t_list.end(); ++itr) //store the threat list in a different container
                 if (Unit* target = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
                     if (target->IsAlive() && target->GetTypeId() == TYPEID_PLAYER)
                         targets.push_back(target);
             //cut down to size if we have more than 5 targets
             while (targets.size() > 5)
                 targets.erase(targets.begin() + rand() % targets.size());
             uint32 i = 0;
             for (std::vector<Unit*>::const_iterator iter = targets.begin(); iter != targets.end(); ++iter, ++i)
                 if (Unit* target = *iter)
                 {
                     enfeeble_targets[i] = target->GetGUID();
                     enfeeble_health[i] = target->GetHealth();
                     me->CastSpell(target, SPELL_ENFEEBLE, true, 0, 0, me->GetGUID());
                     target->SetHealth(1);
                 }
         }
References Unit::CastSpell(), enfeeble_health, enfeeble_targets, Object::GetGUID(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), ScriptedAI::me, SPELL_ENFEEBLE, SPELL_ENFEEBLE_EFFECT, sSpellMgr, and TYPEID_PLAYER.
Referenced by UpdateAI().
EnfeebleResetHealth()
void boss_malchezaar::boss_malchezaarAI::EnfeebleResetHealth () inline
Definition at line 284 of file boss_prince_malchezaar.cpp.
         {
             for (uint8 i = 0; i < 5; ++i)
             {
                 Unit* target = ObjectAccessor::GetUnit(*me, enfeeble_targets[i]);
                 if (target && target->IsAlive())
                     target->SetHealth(enfeeble_health[i]);
                 enfeeble_targets[i].Clear();
                 enfeeble_health[i] = 0;
             }
         }
References ObjectGuid::Clear(), enfeeble_health, enfeeble_targets, ObjectAccessor::GetUnit(), Unit::IsAlive(), ScriptedAI::me, and Unit::SetHealth().
Referenced by UpdateAI().
EnterCombat()
void boss_malchezaar::boss_malchezaarAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 236 of file boss_prince_malchezaar.cpp.
         {
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), false);
         }
References DATA_GO_NETHER_DOOR, CreatureAI::DoZoneInCombat(), InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), instance, SAY_AGGRO, and CreatureAI::Talk().
Initialize()
void boss_malchezaar::boss_malchezaarAI::Initialize (void) inline
Definition at line 194 of file boss_prince_malchezaar.cpp.
         {
             EnfeebleTimer = 30000;
             EnfeebleResetTimer = 38000;
             ShadowNovaTimer = 35500;
             SWPainTimer = 20000;
             InfernalCleanupTimer = 47000;
             AmplifyDamageTimer = 5000;
             SunderArmorTimer = urand(5000, 10000);
             InfernalTimer = 40000;
             phase = 1;
             clearweapons();
             positions.clear();
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), true);
         }
References AmplifyDamageTimer, clearweapons(), DATA_GO_NETHER_DOOR, EnfeebleResetTimer, EnfeebleTimer, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), InfernalCleanupTimer, InfernalTimer, instance, positions, ShadowNovaTimer, SunderArmorTimer, SWPainTimer, and urand().
Referenced by Reset().
JustDied()
void boss_malchezaar::boss_malchezaarAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 226 of file boss_prince_malchezaar.cpp.
         {
             Talk(SAY_DEATH);
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_NETHER_DOOR), true);
             if (Creature*  Axe = me->FindNearestCreature(MALCHEZARS_AXE, 100.0f))
             {
                 Axe->DespawnOrUnsummon();
             }
         }
References DATA_GO_NETHER_DOOR, WorldObject::FindNearestCreature(), InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), instance, MALCHEZARS_AXE, ScriptedAI::me, SAY_DEATH, and CreatureAI::Talk().
KilledUnit()
void boss_malchezaar::boss_malchezaarAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 221 of file boss_prince_malchezaar.cpp.
         {
             Talk(SAY_SLAY);
         }
References SAY_SLAY, and CreatureAI::Talk().
Phase2()
void boss_malchezaar::boss_malchezaarAI::Phase2 () inline
Definition at line 326 of file boss_prince_malchezaar.cpp.
         {
             me->InterruptNonMeleeSpells(false);
             phase = 2;
             DoCast(me, SPELL_EQUIP_AXES);
             Talk(SAY_AXE_TOSS1);
             DoCast(me, SPELL_THRASH_AURA, true);
             SetEquipmentSlots(false, EQUIP_ID_AXE, EQUIP_ID_AXE, EQUIP_NO_CHANGE);
             me->SetCanDualWield(true);
             me->SetAttackTime(OFF_ATTACK, (me->GetAttackTime(BASE_ATTACK) * 150) / 100);
             SunderArmorTimer = urand(5000, 10000);
         }
References BASE_ATTACK, UnitAI::DoCast(), EQUIP_ID_AXE, EQUIP_NO_CHANGE, Unit::GetAttackTime(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, OFF_ATTACK, SAY_AXE_TOSS1, Unit::SetAttackTime(), Creature::SetCanDualWield(), ScriptedAI::SetEquipmentSlots(), SPELL_EQUIP_AXES, SPELL_THRASH_AURA, SunderArmorTimer, CreatureAI::Talk(), and urand().
Referenced by UpdateAI().
Phase3()
void boss_malchezaar::boss_malchezaarAI::Phase3 () inline
Definition at line 339 of file boss_prince_malchezaar.cpp.
         {
             me->RemoveAurasDueToSpell(SPELL_THRASH_AURA);
             Talk(SAY_AXE_TOSS2);
             phase = 3;
             clearweapons();
             SummonAxes();
             AmplifyDamageTimer = urand(20000, 30000);
         }
References AmplifyDamageTimer, clearweapons(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_AXE_TOSS2, SPELL_THRASH_AURA, SummonAxes(), CreatureAI::Talk(), and urand().
Referenced by UpdateAI().
Reset()
void boss_malchezaar::boss_malchezaarAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 216 of file boss_prince_malchezaar.cpp.
         {
             Initialize();
         }
References Initialize().
SummonAxes()
void boss_malchezaar::boss_malchezaarAI::SummonAxes () inline
Definition at line 243 of file boss_prince_malchezaar.cpp.
         {
             me->SummonCreature(MALCHEZARS_AXE, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 10000);
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MALCHEZARS_AXE, ScriptedAI::me, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
Referenced by Phase3().
SummonInfernal()
void boss_malchezaar::boss_malchezaarAI::SummonInfernal () inline
Definition at line 296 of file boss_prince_malchezaar.cpp.
         {
             Position pos;
             if ((me->GetMapId() == 532))
             {
                 pos = me->GetRandomNearPosition(40.0);
             }
             else
             {
                 InfernalPoint* point = Acore::Containers::SelectRandomContainerElement(positions);
                 pos.Relocate(point->x, point->y, INFERNAL_Z, frand(0.0f, float(M_PI * 2)));
             }
             if (Creature*  RELAY = me->FindNearestCreature(NPC_RELAY, 100.0f))
             {
                 Creature* infernal = RELAY->SummonCreature(NETHERSPITE_INFERNAL, pos, TEMPSUMMON_TIMED_DESPAWN, 180000);
                 if (infernal)
                 {
                     infernal->SetDisplayId(INFERNAL_MODEL_INVISIBLE);
                     infernal->SetFaction(me->GetFaction());
                     infernals.push_back(infernal->GetGUID());
                     infernal->SetControlled(true, UNIT_STATE_ROOT);
                     RELAY->AI()->DoCast(infernal, SPELL_INFERNAL_RELAY);
                 }
             }
             Talk(SAY_SUMMON);
         }
References WorldObject::FindNearestCreature(), frand(), Unit::GetFaction(), Object::GetGUID(), WorldLocation::GetMapId(), WorldObject::GetRandomNearPosition(), INFERNAL_MODEL_INVISIBLE, INFERNAL_Z, infernals, ScriptedAI::me, NETHERSPITE_INFERNAL, NPC_RELAY, positions, Position::Relocate(), SAY_SUMMON, Acore::Containers::SelectRandomContainerElement(), Unit::SetControlled(), Creature::SetDisplayId(), Unit::SetFaction(), SPELL_INFERNAL_RELAY, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_ROOT, InfernalPoint::x, and InfernalPoint::y.
Referenced by UpdateAI().
UpdateAI()
void boss_malchezaar::boss_malchezaarAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 349 of file boss_prince_malchezaar.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (EnfeebleResetTimer && EnfeebleResetTimer <= diff) // Let's not forget to reset that
             {
                 EnfeebleResetHealth();
                 EnfeebleResetTimer = 0;
             }
             else EnfeebleResetTimer -= diff;
             if (InfernalTimer <= diff)
             {
                 SummonInfernal();
                 InfernalTimer = phase == 3 ? 14500 : 44500;    // 15 secs in phase 3, 45 otherwise
             }
             else InfernalTimer -= diff;
             if (phase != 2)
             {
                 if (SWPainTimer <= diff)
                 {
                     // if phase == 1 target the tank, otherwise anyone but the tank
                     Unit* target = phase == 1
                             ? me->GetVictim()
                             : SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (target)
                     {
                         DoCast(target, SPELL_SW_PAIN);
                     }
                     SWPainTimer = 20000;
                 }
                 else
                     SWPainTimer -= diff;
             }
             if (ShadowNovaTimer <= diff)
             {
                 DoCast(SPELL_SHADOWNOVA);
                 ShadowNovaTimer = 35500;
             }
             else
                 ShadowNovaTimer -= diff;
             if (phase == 1)
             {
                 if (HealthBelowPct(60))
                 {
                     Phase2();
                 }
             }
             if (phase == 2)
             {
                 if (SunderArmorTimer <= diff)
                 {
                     DoCast(SPELL_SUNDER_ARMOR);
                     SunderArmorTimer = urand(5000, 10000);
                 }
                 else
                     SunderArmorTimer -= diff;
                 if (HealthBelowPct(30))
                 {
                     Phase3();
                 }
             }
             if (phase == 3)
             {
                 if (AmplifyDamageTimer <= diff)
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (target)
                     {
                         DoCast(target, SPELL_AMPLIFY_DAMAGE);
                         AmplifyDamageTimer = urand(20000, 30000);
                     }
                 }
                 else
                 {
                     AmplifyDamageTimer -= diff;
                 }
             }
             if (phase != 3)
             {
                 if (EnfeebleTimer <= diff)
                 {
                     EnfeebleHealthEffect();
                     EnfeebleTimer = 30000;
                     ShadowNovaTimer = 5000;
                     EnfeebleResetTimer = 9000;
                 }
                 else EnfeebleTimer -= diff;
             }
             DoMeleeAttackIfReady();
         }
References AmplifyDamageTimer, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EnfeebleHealthEffect(), EnfeebleResetHealth(), EnfeebleResetTimer, EnfeebleTimer, Unit::GetVictim(), ScriptedAI::HealthBelowPct(), InfernalTimer, ScriptedAI::me, Phase2(), Phase3(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ShadowNovaTimer, SPELL_AMPLIFY_DAMAGE, SPELL_SHADOWNOVA, SPELL_SUNDER_ARMOR, SPELL_SW_PAIN, SummonInfernal(), SunderArmorTimer, SWPainTimer, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
AmplifyDamageTimer
uint32 boss_malchezaar::boss_malchezaarAI::AmplifyDamageTimer
Definition at line 184 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), Phase3(), and UpdateAI().
enfeeble_health
uint32 boss_malchezaar::boss_malchezaarAI::enfeeble_health[5]
Definition at line 188 of file boss_prince_malchezaar.cpp.
Referenced by EnfeebleHealthEffect(), and EnfeebleResetHealth().
enfeeble_targets
ObjectGuid boss_malchezaar::boss_malchezaarAI::enfeeble_targets[5]
Definition at line 189 of file boss_prince_malchezaar.cpp.
Referenced by EnfeebleHealthEffect(), and EnfeebleResetHealth().
EnfeebleResetTimer
uint32 boss_malchezaar::boss_malchezaarAI::EnfeebleResetTimer
Definition at line 180 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and UpdateAI().
EnfeebleTimer
uint32 boss_malchezaar::boss_malchezaarAI::EnfeebleTimer
Definition at line 179 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and UpdateAI().
InfernalCleanupTimer
uint32 boss_malchezaar::boss_malchezaarAI::InfernalCleanupTimer
Definition at line 186 of file boss_prince_malchezaar.cpp.
Referenced by Initialize().
infernals
GuidVector boss_malchezaar::boss_malchezaarAI::infernals
Definition at line 191 of file boss_prince_malchezaar.cpp.
Referenced by SummonInfernal().
InfernalTimer
uint32 boss_malchezaar::boss_malchezaarAI::InfernalTimer
Definition at line 185 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and UpdateAI().
instance
InstanceScript* boss_malchezaar::boss_malchezaarAI::instance
Definition at line 178 of file boss_prince_malchezaar.cpp.
Referenced by boss_malchezaarAI(), EnterCombat(), Initialize(), and JustDied().
phase
uint32 boss_malchezaar::boss_malchezaarAI::phase
Definition at line 187 of file boss_prince_malchezaar.cpp.
positions
std::vector<InfernalPoint*> boss_malchezaar::boss_malchezaarAI::positions
Definition at line 192 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and SummonInfernal().
ShadowNovaTimer
uint32 boss_malchezaar::boss_malchezaarAI::ShadowNovaTimer
Definition at line 181 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and UpdateAI().
SunderArmorTimer
uint32 boss_malchezaar::boss_malchezaarAI::SunderArmorTimer
Definition at line 183 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), Phase2(), and UpdateAI().
SWPainTimer
uint32 boss_malchezaar::boss_malchezaarAI::SWPainTimer
Definition at line 182 of file boss_prince_malchezaar.cpp.
Referenced by Initialize(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp