Azerotcore-wotlk: spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript Class Reference
spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_putricide_mutated_transformation_SpellScript)
void HandleSummon (SpellEffIndex effIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1508 of file boss_professor_putricide.cpp.
Member Function Documentation
HandleSummon()
void spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon (SpellEffIndex effIndex) inline private
Definition at line 1512 of file boss_professor_putricide.cpp.
         {
             PreventHitDefaultEffect(effIndex);
             Unit* caster = GetOriginalCaster();
             if (!caster)
                 return;
             InstanceScript* instance = caster->GetInstanceScript();
             if (!instance)
                 return;
             Creature* putricide = ObjectAccessor::GetCreature(*caster, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE));
             if (!putricide)
                 return;
             if (putricide->AI()->GetData(DATA_ABOMINATION))
             {
                 if (Player* player = caster->ToPlayer())
                     Spell::SendCastResult(player, GetSpellInfo(), 0, SPELL_FAILED_CUSTOM_ERROR, SPELL_CUSTOM_ERROR_TOO_MANY_ABOMINATIONS);
                 return;
             }
             if (!putricide->IsInCombat())
                 putricide->SetInCombatWithZone();
             uint32 entry = uint32(GetSpellInfo()->Effects[effIndex].MiscValue);
             SummonPropertiesEntry const* properties = sSummonPropertiesStore.LookupEntry(uint32(GetSpellInfo()->Effects[effIndex].MiscValueB));
             uint32 duration = uint32(GetSpellInfo()->GetDuration());
             Position pos = caster->GetPosition();
             TempSummon* summon = caster->GetMap()->SummonCreature(entry, pos, properties, duration, caster, GetSpellInfo()->Id);
             if (!summon || !summon->IsVehicle())
                 return;
             summon->CastSpell(summon, SPELL_ABOMINATION_VEHICLE_POWER_DRAIN, true);
             summon->CastSpell(summon, SPELL_MUTATED_TRANSFORMATION_DAMAGE, true);
             caster->CastSpell(summon, SPELL_MUTATED_TRANSFORMATION_NAME, true);
             //EnterVehicle(summon, 0);    // VEHICLE_SPELL_RIDE_HARDCODED is used according to sniff, this is ok
             caster->CastCustomSpell(VEHICLE_SPELL_RIDE_HARDCODED, SPELLVALUE_BASE_POINT0, 1, summon, TRIGGERED_FULL_MASK);
             summon->SetCreatorGUID(caster->GetGUID());
             putricide->AI()->JustSummoned(summon);
             summon->setPowerType(POWER_ENERGY);
             summon->SetMaxPower(POWER_ENERGY, 100);
             summon->SetPower(POWER_ENERGY, 0);
             summon->SetStatFloatValue(UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER, 0);
             summon->SetStatFloatValue(UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER, 0);
         }
References Creature::AI(), Unit::CastCustomSpell(), Unit::CastSpell(), DATA_ABOMINATION, DATA_PROFESSOR_PUTRICIDE, ObjectAccessor::GetCreature(), UnitAI::GetData(), Object::GetGUID(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), SpellScript::GetOriginalCaster(), Position::GetPosition(), SpellScript::GetSpellInfo(), Unit::IsInCombat(), Unit::IsVehicle(), CreatureAI::JustSummoned(), pos(), POWER_ENERGY, SpellScript::PreventHitDefaultEffect(), Spell::SendCastResult(), Unit::SetCreatorGUID(), Creature::SetInCombatWithZone(), Unit::SetMaxPower(), Unit::SetPower(), Unit::setPowerType(), Object::SetStatFloatValue(), SPELL_ABOMINATION_VEHICLE_POWER_DRAIN, SPELL_CUSTOM_ERROR_TOO_MANY_ABOMINATIONS, SPELL_FAILED_CUSTOM_ERROR, SPELL_MUTATED_TRANSFORMATION_DAMAGE, SPELL_MUTATED_TRANSFORMATION_NAME, SPELLVALUE_BASE_POINT0, sSummonPropertiesStore, Map::SummonCreature(), Object::ToPlayer(), TRIGGERED_FULL_MASK, UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER, UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER, and VEHICLE_SPELL_RIDE_HARDCODED.
Referenced by Register().
PrepareSpellScript()
spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::PrepareSpellScript (spell_putricide_mutated_transformation_SpellScript) private
Register()
void spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1562 of file boss_professor_putricide.cpp.
         {
             OnEffectHit += SpellEffectFn(spell_putricide_mutated_transformation_SpellScript::HandleSummon, EFFECT_0, SPELL_EFFECT_SUMMON);
         }
References EFFECT_0, HandleSummon(), SpellScript::OnEffectHit, SPELL_EFFECT_SUMMON, and SpellEffectFn.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp