Azerotcore-wotlk: G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc > Class Template Reference
G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc > Class Template Reference
#include <PointKDTree.h>
Classes
class AxisComparator
class BoxIntersectionIterator
class Handle
class Iterator
class Node
Public Member Functions
PointKDTree ()
PointKDTree (const PointKDTree &src)
PointKDTree & operator= (const PointKDTree &src)
~PointKDTree ()
void clear ()
void clearData ()
size_t size () const
void insert (const T &value)
void insert (const Array< T > &valueArray)
bool contains (const T &value)
void remove (const T &value)
void update (const T &value)
void balance (int valuesPerNode=40, int numMeanSplits=3)
void getIntersectingMembers (const Array< Plane > &plane, Array< T > &members) const
void getIntersectingMembers (const Frustum &frustum, Array< T > &members) const
BoxIntersectionIterator beginBoxIntersection (const AABox &box) const
BoxIntersectionIterator endBoxIntersection () const
void getIntersectingMembers (const AABox &box, Array< T > &members) const
void getIntersectingMembers (const Sphere &sphere, Array< T > &members) const
void serializeStructure (BinaryOutput &bo) const
void deserializeStructure (BinaryInput &bi)
void getMembers (Array< T > &members) const
Iterator begin () const
Iterator end () const
Protected Types
typedef Table< T, Node *, HashFunc, EqualsFunc > MemberTable
Protected Member Functions
Node * makeNode (Array< Handle > &source, Array< Handle > &temp, int valuesPerNode, int numMeanSplits)
Node * cloneTree (Node *src)
Static Protected Member Functions
static AABox computeBounds (const Array< Handle > &point)
Protected Attributes
MemberTable memberTable
Node * root
Static Private Member Functions
static void getIntersectingMembers (const Array< Plane > &plane, Array< T > &members, Node *node, uint32 parentMask)
Detailed Description
template<class T, class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>>
class G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >
A set data structure that supports spatial queries using an axis-aligned BSP tree for speed.
PointKDTree allows you to quickly find points in 3D that lie within a box or sphere. For large sets of objects it is much faster than testing each object for a collision. See also G3D::KDTree; this class is optimized for point sets, e.g.,for use in photon mapping and mesh processing.
Template Parameters
The template parameter T must be one for which the following functions are overloaded:
     T::T(); (public constructor of no arguments)
      template<> struct PositionTrait<class T> {
        static void getPosition(const T& v, G3D::Vector3& p);};
      template <> struct HashTrait<class T> {
        static size_t hashCode(const T& key);};
      template<> struct EqualsTrait<class T> {
          static bool equals(const T& a, const T& b); };
G3D provides these for the Vector2, Vector3, and Vector4 classes. If you use a custom class, or a pointer to a custom class, you will need to define those functions.
Moving Set Members
It is important that objects do not move without updating the PointKDTree. If the position of an object is about to change, PointKDTree::remove it before they change and PointKDTree::insert it again afterward. For objects where the hashCode and == operator are invariant with respect to the 3D position, you can use the PointKDTree::update method as a shortcut to insert/remove an object in one step after it has moved.
Note: Do not mutate any value once it has been inserted into PointKDTree. Values are copied interally. All PointKDTree iterators convert to pointers to constant values to reinforce this.
If you want to mutate the objects you intend to store in a PointKDTree simply insert pointers to your objects instead of the objects themselves, and ensure that the above operations are defined. (And actually, because values are copied, if your values are large you may want to insert pointers anyway, to save space and make the balance operation faster.)
Dimensions Although designed as a 3D-data structure, you can use the PointKDTree for data distributed along 2 or 1 axes by simply returning bounds that are always zero along one or more dimensions.
Definition at line 102 of file PointKDTree.h.
Member Typedef Documentation
MemberTable
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> typedef Table<T, Node*, HashFunc, EqualsFunc> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::MemberTable protected
Maps members to the node containing them
Definition at line 561 of file PointKDTree.h.
Constructor & Destructor Documentation
PointKDTree() [1/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::PointKDTree () inline
To construct a balanced tree, insert the elements and then call PointKDTree::balance().
Definition at line 570 of file PointKDTree.h.
 : root(NULL) {}
PointKDTree() [2/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::PointKDTree (const PointKDTree< T, PositionFunc, HashFunc, EqualsFunc > & src) inline
Definition at line 573 of file PointKDTree.h.
                                         : root(NULL) {
         *this = src;
     }
~PointKDTree()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::~PointKDTree () inline
Definition at line 586 of file PointKDTree.h.
                    {
         clear();
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear().
Member Function Documentation
balance()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance (int valuesPerNode = 40, int numMeanSplits = 3) inline
Rebalances the tree (slow). Call when objects have moved substantially from their original positions (which unbalances the tree and causes the spatial queries to be slow).
Parameters
valuesPerNode Maximum number of elements to put at a node.
numMeanSplits numMeanSplits = 0 gives a fully axis aligned BSP-tree, where the balance operation attempts to balance the tree so that every splitting plane has an equal number of left and right children (i.e. it is a median split along that axis).
This tends to maximize average performance; all querries will return in the same amount of time.
You can override this behavior by setting a number of mean (average) splits. numMeanSplits = MAX_INT creates a full oct-tree, which tends to optimize peak performance (some areas of the scene will terminate after few recursive splits) at the expense of peak performance.
Definition at line 754 of file PointKDTree.h.
{
         if (root == NULL) {
             // Tree is empty
             return;
         }
         Array<Handle> handleArray;
         root->getHandles(handleArray);
         // Delete the old tree
         clear();
         Array<Handle> temp;
         root = makeNode(handleArray, temp, valuesPerNode, numMeanSplits);
         temp.fastClear();
         // Walk the tree, assigning splitBounds.  We start with unbounded
         // space.
         root->assignSplitBounds(AABox::maxFinite());
 #       ifdef _DEBUG
             root->verifyNode(Vector3::minFinite(), Vector3::maxFinite());
 #       endif
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear(), G3D::Array< T, MIN_ELEMENTS >::fastClear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::AABox::maxFinite(), G3D::Vector3::maxFinite(), G3D::Vector3::minFinite(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
begin()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Iterator G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::begin () const inline
C++ STL style iterator method. Returns the first member.
Use preincrement (++entry) to get to the next element (iteration order is arbitrary).
Do not modify the set while iterating.
Definition at line 1171 of file PointKDTree.h.
{
         return Iterator(memberTable.begin());
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable.
beginBoxIntersection()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> BoxIntersectionIterator G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::beginBoxIntersection (const AABox & box) const inline
Iterates through the members that intersect the box
Definition at line 1051 of file PointKDTree.h.
{
         return BoxIntersectionIterator(box, root);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
clear()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear () inline
Throws out all elements of the set and erases the structure of the tree.
Definition at line 593 of file PointKDTree.h.
                  {
         memberTable.clear();
         delete root;
         root = NULL;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::deserializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::~PointKDTree().
clearData()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData () inline
Removes all elements of the set while maintaining the structure of the tree
Definition at line 600 of file PointKDTree.h.
                      {
         memberTable.clear();
         Array<Node*> stack;
         stack.push(root);
         while (stack.size() > 0) {
             Node* node = stack.pop();
             node->valueArray.fastClear();
             for (int i = 0; i < 2; ++i) {
                 if (node->child[i] != NULL) {
                     stack.push(node->child[i]);
                 }
             }
         }
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, G3D::Array< T, MIN_ELEMENTS >::pop(), G3D::Array< T, MIN_ELEMENTS >::push(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
cloneTree()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree (Node * src) inline protected
Recursively clone the passed in node tree, setting pointers for members in the memberTable as appropriate. called by the assignment operator.
Definition at line 542 of file PointKDTree.h.
{
         Node* dst = new Node(*src);
         // Make back pointers
         for (int i = 0; i < dst->valueArray.size(); ++i) {
             memberTable.set(dst->valueArray[i].value, dst);
         }
         // Clone children
         for (int i = 0; i < 2; ++i) {
             if (src->child[i] != NULL) {
                 dst->child[i] = cloneTree(src->child[i]);
             }
         }
         return dst;
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::operator=().
computeBounds()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> static AABox G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::computeBounds (const Array< Handle > & point) inline static protected
Returns the bounds of the sub array. Used by makeNode.
Definition at line 133 of file PointKDTree.h.
{
         if (point.size() == 0) {
             return AABox(Vector3::inf(), Vector3::inf());
         }
         AABox bounds(point[0].position());
         for (int p = 0; p < point.size(); ++p) {
             bounds.merge(point[p].position());
         }
         return bounds;
     }
References G3D::Vector3::inf(), G3D::AABox::merge(), and G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode().
contains()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains (const T & value) inline
Returns true if this object is in the set, otherwise returns false. O(1) time.
Definition at line 682 of file PointKDTree.h.
{
         return memberTable.containsKey(value);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::update().
deserializeStructure()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::deserializeStructure (BinaryInput & bi) inline
Clears the member table
Definition at line 1097 of file PointKDTree.h.
{
         clear();
         root = Node::deserializeStructure(bi);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
end()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Iterator G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::end () const inline
C++ STL style iterator method. Returns one after the last iterator element.
Definition at line 1180 of file PointKDTree.h.
{
         return Iterator(memberTable.end());
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::end(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable.
endBoxIntersection()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> BoxIntersectionIterator G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::endBoxIntersection () const inline
Definition at line 1055 of file PointKDTree.h.
{
         // The "end" iterator instance
         return BoxIntersectionIterator();
     }
getIntersectingMembers() [1/5]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers (const AABox & box, Array< T > & members) const inline
Appends all members whose bounds intersect the box. See also PointKDTree::beginBoxIntersection.
Definition at line 1064 of file PointKDTree.h.
{
         if (root == NULL) {
             return;
         }
         root->getIntersectingMembers(box, Sphere(Vector3::zero(), 0), members, false);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, and G3D::Vector3::zero().
getIntersectingMembers() [2/5]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers (const Array< Plane > & plane, Array< T > & members) const inline
Returns all members inside the set of planes.
Parameters
members The results are appended to this array.
Definition at line 847 of file PointKDTree.h.
{
         if (root == NULL) {
             return;
         }
         getIntersectingMembers(plane, members, root, 0xFFFFFF);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), NULL, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
getIntersectingMembers() [3/5]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> static void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers (const Array< Plane > & plane, Array< T > & members, Node * node, uint32 parentMask) inline static private
Returns the elements
Parameters
parentMask The mask that this node returned from culledBy.
Definition at line 786 of file PointKDTree.h.
{
         int dummy;
         if (parentMask == 0) {
             // None of these planes can cull anything
             for (int v = node->valueArray.size() - 1; v >= 0; --v) {
                 members.append(node->valueArray[v].value);
             }
             // Iterate through child nodes
             for (int c = 0; c < 2; ++c) {
                 if (node->child[c]) {
                     getIntersectingMembers(plane, members, node->child[c], 0);
                 }
             }
         } else {
             if (node->valueArray.size() >  0) {
                 // This is a leaf; check the points
                 debugAssertM(node->child[0] == NULL, "Malformed Point tree");
                 debugAssertM(node->child[1] == NULL, "Malformed Point tree");
                 // Test values at this node against remaining planes
                 for (int p = 0; p < plane.size(); ++p) {
                     if (((parentMask >> p) & 1) != 0) {
                         // Test against this plane
                         const Plane& curPlane = plane[p];
                         for (int v = node->valueArray.size() - 1; v >= 0; --v) {
                             if (curPlane.halfSpaceContains(node->valueArray[v].position())) {
                                 members.append(node->valueArray[v].value);
                             }
                         }
                     }
                 }
             } else {
                 uint32 childMask  = 0xFFFFFF;
                 // Iterate through child nodes
                 for (int c = 0; c < 2; ++c) {
                     if (node->child[c] &&
                         ! node->child[c]->splitBounds.culledBy(plane, dummy, parentMask, childMask)) {
                         // This node was not culled
                         getIntersectingMembers(plane, members, node->child[c], childMask);
                     }
                 }
             }
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), mpq::c, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::AABox::culledBy(), debugAssertM, G3D::Plane::halfSpaceContains(), NULL, G3D::Array< T, MIN_ELEMENTS >::size(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers().
getIntersectingMembers() [4/5]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers (const Frustum & frustum, Array< T > & members) const inline
Typically used to find all visible objects inside the view frustum (see also Camera::getClipPlanes)... i.e. all objects not culled by frustum.
Example:
   Array<Object*>  visible;
   tree.getIntersectingMembers(camera.frustum(), visible);
   // ... Draw all objects in the visible array.
Parameters
members The results are appended to this array.
Definition at line 868 of file PointKDTree.h.
{
         Array<Plane> plane;
         for (int i = 0; i < frustum.faceArray.size(); ++i) {
             plane.append(frustum.faceArray[i].plane);
         }
         getIntersectingMembers(plane, members);
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Frustum::faceArray, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers().
getIntersectingMembers() [5/5]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers (const Sphere & sphere, Array< T > & members) const inline
Parameters
members The results are appended to this array.
Definition at line 1075 of file PointKDTree.h.
{
         if (root == NULL) {
             return;
         }
         AABox box;
         sphere.getBounds(box);
         root->getIntersectingMembers(box, sphere, members);
     }
References G3D::Sphere::getBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), NULL, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
getMembers()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getMembers (Array< T > & members) const inline
Returns an array of all members of the set. See also PointKDTree::begin.
Definition at line 1105 of file PointKDTree.h.
{
         memberTable.getKeys(members);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable.
insert() [1/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert (const Array< T > & valueArray) inline
Inserts each elements in the array in turn. If the tree begins empty (no structure and no elements), this is faster than inserting each element in turn. You still need to balance the tree at the end.
Definition at line 652 of file PointKDTree.h.
{
         // Pre-size the member table to avoid multiple allocations
         memberTable.setSizeHint(valueArray.size() + size());
         if (root == NULL) {
             // Optimized case for an empty tree; don't bother
             // searching or reallocating the root node's valueArray
             // as we incrementally insert.
             root = new Node();
             root->valueArray.resize(valueArray.size());
             for (int i = 0; i < valueArray.size(); ++i) {
                 // Insert in opposite order so that we have the exact same
                 // data structure as if we inserted each (i.e., order is reversed
                 // from array).
                 root->valueArray[valueArray.size() - i - 1] = Handle(valueArray[i]);
                 memberTable.set(valueArray[i], root);
             }
         } else {
             // Insert at appropriate tree depth.
             for (int i = 0; i < valueArray.size(); ++i) {
                 insert(valueArray[i]);
             }
         }
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::setSizeHint(), G3D::Array< T, MIN_ELEMENTS >::size(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::size(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
insert() [2/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert (const T & value) inline
Inserts an object into the set if it is not already present. O(log n) time. Does not cause the tree to be balanced.
Definition at line 626 of file PointKDTree.h.
{
         if (contains(value)) {
             // Already in the set
             return;
         }
         Handle h(value);
         if (root == NULL) {
             // This is the first node; create a root node
             root = new Node();
         }
         Node* node = root->findDeepestContainingNode(h.position());
         // Insert into the node
         node->valueArray.append(h);
         // Insert into the node table
         memberTable.set(value, node);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::position(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::update().
makeNode()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode (Array< Handle > & source, Array< Handle > & temp, int valuesPerNode, int numMeanSplits) inline protected
Recursively subdivides the subarray.
The source array will be cleared after it is used
Call assignSplitBounds() on the root node after making a tree.
Definition at line 444 of file PointKDTree.h.
{
         Node* node = NULL;
         if (source.size() <= valuesPerNode) {
             // Make a new leaf node
             node = new Node(source);
             // Set the pointers in the memberTable
             for (int i = 0; i < source.size(); ++i) {
                 memberTable.set(source[i].value, node);
             }
         } else {
             // Make a new internal node
             node = new Node();
             const AABox bounds = computeBounds(source);
             const Vector3 extent = bounds.high() - bounds.low();
             Vector3::Axis splitAxis = extent.primaryAxis();
             float splitLocation;
             Array<Handle> lt, gt;
             if (numMeanSplits <= 0) {
                 source.medianPartition(lt, node->valueArray, gt, temp, AxisComparator(splitAxis));
                 splitLocation = node->valueArray[0].position()[splitAxis];
                 if ((node->valueArray.size() > source.size() / 2) &&
                     (source.size() > 10)) {
                     // Our median split put an awful lot of points on the splitting plane.  Try a mean
                     // split instead
                     numMeanSplits = 1;
                 }
             }
             if (numMeanSplits > 0) {
                 // Compute the mean along the axis
                 splitLocation = (bounds.high()[splitAxis] +
                                  bounds.low()[splitAxis]) / 2.0f;
                 Handle splitHandle;
                 Vector3 v;
                 v[splitAxis] = splitLocation;
                 splitHandle.setPosition(v);
                 source.partition(splitHandle, lt, node->valueArray, gt, AxisComparator(splitAxis));
             }
 #           if defined(G3D_DEBUG) && defined(VERIFY_TREE)
                 for (int i = 0; i < lt.size(); ++i) {
                     const Vector3& v = lt[i].position();
                     debugAssert(v[splitAxis] < splitLocation);
                 }
                 for (int i = 0; i < gt.size(); ++i) {
                     debugAssert(gt[i].position()[splitAxis] > splitLocation);
                 }
                 for (int i = 0; i < node->valueArray.size(); ++i) {
                     debugAssert(node->valueArray[i].position()[splitAxis] == splitLocation);
                 }
 #           endif
             node->splitAxis = splitAxis;
             node->splitLocation = splitLocation;
             // Throw away the source array to save memory
             source.fastClear();
             if (lt.size() > 0) {
                 node->child[0] = makeNode(lt, temp, valuesPerNode, numMeanSplits - 1);
             }
             if (gt.size() > 0) {
                 node->child[1] = makeNode(gt, temp, valuesPerNode, numMeanSplits - 1);
             }
             // Add the values stored at this interior node to the member table
             for(int i = 0; i < node->valueArray.size(); ++i) {
                 memberTable.set(node->valueArray[i].value, node);
             }
         }
         return node;
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::computeBounds(), debugAssert, G3D::Array< T, MIN_ELEMENTS >::fastClear(), G3D::AABox::high(), G3D::AABox::low(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, NULL, G3D::Array< T, MIN_ELEMENTS >::partition(), G3D::Vector3::primaryAxis(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::setPosition(), G3D::Array< T, MIN_ELEMENTS >::size(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance().
operator=()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> PointKDTree& G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::operator= (const PointKDTree< T, PositionFunc, HashFunc, EqualsFunc > & src) inline
Definition at line 578 of file PointKDTree.h.
{
         delete root;
         // Clone tree takes care of filling out the memberTable.
         root = cloneTree(src.root);
         return *this;
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root.
remove()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove (const T & value) inline
Removes an object from the set in O(1) time. It is an error to remove members that are not already present. May unbalance the tree.
Removing an element never causes a node (split plane) to be removed... nodes are only changed when the tree is rebalanced. This behavior is desirable because it allows the split planes to be serialized, and then deserialized into an empty tree which can be repopulated.
Definition at line 697 of file PointKDTree.h.
{
         debugAssertM(contains(value),
             "Tried to remove an element from a "
             "PointKDTree that was not present");
         Array<Handle>& list = memberTable[value]->valueArray;
         // Find the element and remove it
         for (int i = list.length() - 1; i >= 0; --i) {
             if (list[i].value == value) {
                 list.fastRemove(i);
                 break;
             }
         }
         memberTable.remove(value);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains(), debugAssertM, list(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::update().
serializeStructure()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::serializeStructure (BinaryOutput & bo) const inline
Stores the locations of the splitting planes (the structure but not the content) so that the tree can be quickly rebuilt from a previous configuration without calling balance.
Definition at line 1092 of file PointKDTree.h.
{
         Node::serializeStructure(root, bo);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure().
size()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> size_t G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::size () const inline
Definition at line 617 of file PointKDTree.h.
{
         return memberTable.size();
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::size().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert().
update()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::update (const T & value) inline
If the element is in the set, it is removed. The element is then inserted.
This is useful when the == and hashCode methods on T are independent of the bounds. In that case, you may call update(v) to insert an element for the first time and call update(v) again every time it moves to keep the tree up to date.
Definition at line 726 of file PointKDTree.h.
{
         if (contains(value)) {
             remove(value);
         }
         insert(value);
     }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove().
Member Data Documentation
memberTable
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> MemberTable G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::memberTable protected
Definition at line 562 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::begin(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::end(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::size().
root
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::root protected
Definition at line 564 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::beginBoxIntersection(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::deserializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::operator=(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::serializeStructure().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointKDTree.h