Azerotcore-wotlk: npcs_ashyen_and_keleth Class Reference
npcs_ashyen_and_keleth Class Reference
Public Member Functions
npcs_ashyen_and_keleth ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 152 of file zone_zangarmarsh.cpp.
Constructor & Destructor Documentation
npcs_ashyen_and_keleth()
npcs_ashyen_and_keleth::npcs_ashyen_and_keleth () inline
Definition at line 155 of file zone_zangarmarsh.cpp.
 : CreatureScript("npcs_ashyen_and_keleth") { }
Member Function Documentation
OnGossipHello()
bool npcs_ashyen_and_keleth::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 157 of file zone_zangarmarsh.cpp.
     {
         if (player->GetReputationRank(942) > REP_NEUTRAL)
         {
             if (creature->GetEntry() == NPC_ASHYEN)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BLESS_ASH, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             if (creature->GetEntry() == NPC_KELETH)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BLESS_KEL, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetReputationRank(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BLESS_ASH, GOSSIP_ITEM_BLESS_KEL, GOSSIP_SENDER_MAIN, NPC_ASHYEN, NPC_KELETH, REP_NEUTRAL, and SendGossipMenuFor().
OnGossipSelect()
bool npcs_ashyen_and_keleth::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 172 of file zone_zangarmarsh.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
         {
             creature->setPowerType(POWER_MANA);
             creature->SetMaxPower(POWER_MANA, 200);             //set a "fake" mana value, we can't depend on database doing it in this case
             creature->SetPower(POWER_MANA, 200);
             if (creature->GetEntry() == NPC_ASHYEN)                //check which Creature we are dealing with
             {
                 uint32 spell = 0;
                 switch (player->GetReputationRank(942))
                 {
                     //mark of lore
                     case REP_FRIENDLY:
                         spell = SPELL_BLESS_ASH_FRI;
                         break;
                     case REP_HONORED:
                         spell = SPELL_BLESS_ASH_HON;
                         break;
                     case REP_REVERED:
                         spell = SPELL_BLESS_ASH_REV;
                         break;
                     case REP_EXALTED:
                         spell = SPELL_BLESS_ASH_EXA;
                         break;
                     default:
                         break;
                 }
                 if (spell)
                 {
                     creature->CastSpell(player, spell, true);
                     creature->AI()->Talk(GOSSIP_REWARD_BLESS);
                 }
             }
             if (creature->GetEntry() == NPC_KELETH)
             {
                 uint32 spell = 0;
                 switch (player->GetReputationRank(942))         //mark of war
                 {
                     case REP_FRIENDLY:
                         spell = SPELL_BLESS_KEL_FRI;
                         break;
                     case REP_HONORED:
                         spell = SPELL_BLESS_KEL_HON;
                         break;
                     case REP_REVERED:
                         spell = SPELL_BLESS_KEL_REV;
                         break;
                     case REP_EXALTED:
                         spell = SPELL_BLESS_KEL_EXA;
                         break;
                     default:
                         break;
                 }
                 if (spell)
                 {
                     creature->CastSpell(player, spell, true);
                     creature->AI()->Talk(GOSSIP_REWARD_BLESS);
                 }
             }
             CloseGossipMenuFor(player);
             player->TalkedToCreature(creature->GetEntry(), creature->GetGUID());
         }
         return true;
     }
References Creature::AI(), Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetEntry(), Object::GetGUID(), Player::GetReputationRank(), GOSSIP_ACTION_INFO_DEF, GOSSIP_REWARD_BLESS, NPC_ASHYEN, NPC_KELETH, POWER_MANA, REP_EXALTED, REP_FRIENDLY, REP_HONORED, REP_REVERED, Unit::SetMaxPower(), Unit::SetPower(), Unit::setPowerType(), SPELL_BLESS_ASH_EXA, SPELL_BLESS_ASH_FRI, SPELL_BLESS_ASH_HON, SPELL_BLESS_ASH_REV, SPELL_BLESS_KEL_EXA, SPELL_BLESS_KEL_FRI, SPELL_BLESS_KEL_HON, SPELL_BLESS_KEL_REV, CreatureAI::Talk(), and Player::TalkedToCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_zangarmarsh.cpp