Azerotcore-wotlk: Acore::Crypto::Argon2 Struct Reference
Acore::Crypto::Argon2 Struct Reference
#include <Argon2.h>
Static Public Member Functions
static Optional< std::string > Hash (std::string const &password, BigNumber const &salt, uint32 nIterations=DEFAULT_ITERATIONS, uint32 kibMemoryCost=DEFAULT_MEMORY_COST)
static bool Verify (std::string const &password, std::string const &hash)
Static Public Attributes
static constexpr uint32 HASH_LEN = 16
static constexpr uint32 ENCODED_HASH_LEN = 100
static constexpr uint32 DEFAULT_ITERATIONS = 10
static constexpr uint32 DEFAULT_MEMORY_COST = (1u << 17)
static constexpr uint32 PARALLELISM = 1
Detailed Description
Definition at line 16 of file Argon2.h.
Member Function Documentation
Hash()
Optional< std::string > Acore::Crypto::Argon2::Hash (std::string const & password, BigNumber const & salt, uint32 nIterations = DEFAULT_ITERATIONS, uint32 kibMemoryCost = DEFAULT_MEMORY_COST) static
Definition at line 9 of file Argon2.cpp.
 {
     char buf[ENCODED_HASH_LEN];
     std::vector<uint8> saltBytes = salt.ToByteVector();
     int status = argon2id_hash_encoded(
         nIterations,
         kibMemoryCost,
         PARALLELISM,
         password.c_str(), password.length(),
         saltBytes.data(), saltBytes.size(),
         HASH_LEN, buf, ENCODED_HASH_LEN
     );
     if (status == ARGON2_OK)
     {
         return std::string(buf);
     }
     return {};
 }
References ENCODED_HASH_LEN, HASH_LEN, PARALLELISM, and BigNumber::ToByteVector().
Referenced by SecretMgr::AttemptTransition().
Verify()
bool Acore::Crypto::Argon2::Verify (std::string const & password, std::string const & hash) static
Definition at line 30 of file Argon2.cpp.
 {
     int status = argon2id_verify(hash.c_str(), password.c_str(), password.length());
     return (status == ARGON2_OK);
 }
Referenced by SecretMgr::AttemptLoad().
Member Data Documentation
DEFAULT_ITERATIONS
constexpr uint32 Acore::Crypto::Argon2::DEFAULT_ITERATIONS = 10 static constexpr
Definition at line 20 of file Argon2.h.
DEFAULT_MEMORY_COST
constexpr uint32 Acore::Crypto::Argon2::DEFAULT_MEMORY_COST = (1u << 17) static constexpr
Definition at line 21 of file Argon2.h.
ENCODED_HASH_LEN
constexpr uint32 Acore::Crypto::Argon2::ENCODED_HASH_LEN = 100 static constexpr
Definition at line 19 of file Argon2.h.
Referenced by Hash().
HASH_LEN
constexpr uint32 Acore::Crypto::Argon2::HASH_LEN = 16 static constexpr
Definition at line 18 of file Argon2.h.
Referenced by Hash().
PARALLELISM
constexpr uint32 Acore::Crypto::Argon2::PARALLELISM = 1 static constexpr
Definition at line 22 of file Argon2.h.
Referenced by Hash().
The documentation for this struct was generated from the following files:
src/common/Cryptography/Argon2.h
src/common/Cryptography/Argon2.cpp