Azerotcore-wotlk: deps/mysqllite/mysys/thr_lock.c File Reference
thr_lock.c File Reference
#include "mysys_priv.h"
#include "thr_lock.h"
#include <m_string.h>
#include <errno.h>
#include <my_sys.h>
Macros
#define FORCE_DBUG_OFF
#define MAX_THREADS 100
#define MAX_LOCKS 100
#define check_locks(A, B, C)
#define LOCK_CMP(A, B) ((uchar*) (A->lock) - (uint) ((A)->type) < (uchar*) (B->lock)- (uint) ((B)->type))
Functions
void thr_set_lock_wait_callback (void(*before_wait)(void), void(*after_wait)(void))
static mysql_cond_t * get_cond (void)
my_bool init_thr_lock ()
static my_bool thr_lock_owner_equal (THR_LOCK_INFO *rhs, THR_LOCK_INFO *lhs)
void thr_lock_init (THR_LOCK *lock)
void thr_lock_delete (THR_LOCK *lock)
void thr_lock_info_init (THR_LOCK_INFO *info)
void thr_lock_data_init (THR_LOCK *lock, THR_LOCK_DATA *data, void *param)
static my_bool has_old_lock (THR_LOCK_DATA *data, THR_LOCK_INFO *owner)
static my_bool have_specific_lock (THR_LOCK_DATA *data, enum thr_lock_type type)
static void wake_up_waiters (THR_LOCK *lock)
Wake up all threads which pending requests for the lock can be satisfied.
static enum enum_thr_lock_result wait_for_lock (struct st_lock_list *wait, THR_LOCK_DATA *data, my_bool in_wait_list, ulong lock_wait_timeout)
enum enum_thr_lock_result thr_lock (THR_LOCK_DATA *data, THR_LOCK_INFO *owner, enum thr_lock_type lock_type, ulong lock_wait_timeout)
static void free_all_read_locks (THR_LOCK *lock, my_bool using_concurrent_insert)
void thr_unlock (THR_LOCK_DATA *data)
static void sort_locks (THR_LOCK_DATA **data, uint count)
enum enum_thr_lock_result thr_multi_lock (THR_LOCK_DATA **data, uint count, THR_LOCK_INFO *owner, ulong lock_wait_timeout)
void thr_lock_merge_status (THR_LOCK_DATA **data, uint count)
void thr_multi_unlock (THR_LOCK_DATA **data, uint count)
void thr_abort_locks (THR_LOCK *lock, my_bool upgrade_lock)
my_bool thr_abort_locks_for_thread (THR_LOCK *lock, my_thread_id thread_id)
void thr_downgrade_write_lock (THR_LOCK_DATA *in_data, enum thr_lock_type new_lock_type)
my_bool thr_upgrade_write_delay_lock (THR_LOCK_DATA *data, enum thr_lock_type new_lock_type, ulong lock_wait_timeout)
my_bool thr_reschedule_write_lock (THR_LOCK_DATA *data, ulong lock_wait_timeout)
static void thr_print_lock (const char *name, struct st_lock_list *list)
void thr_print_locks (void)
Variables
my_bool thr_lock_inited =0
ulong locks_immediate = 0L
ulong locks_waited = 0L
enum thr_lock_type thr_upgraded_concurrent_insert_lock = TL_WRITE
LIST * thr_lock_thread_list
ulong max_write_lock_count = ~(ulong) 0L
static void(* before_lock_wait)(void)=0
static void(* after_lock_wait)(void)=0
Macro Definition Documentation
check_locks
#define check_locks (A, B, C)
Definition at line 313 of file thr_lock.c.
FORCE_DBUG_OFF
#define FORCE_DBUG_OFF
Definition at line 72 of file thr_lock.c.
LOCK_CMP
#define LOCK_CMP (A, B) ((uchar*) (A->lock) - (uint) ((A)->type) < (uchar*) (B->lock)- (uint) ((B)->type))
Definition at line 1014 of file thr_lock.c.
MAX_LOCKS
#define MAX_LOCKS 100
Definition at line 87 of file thr_lock.c.
MAX_THREADS
#define MAX_THREADS 100
Definition at line 86 of file thr_lock.c.
Function Documentation
free_all_read_locks()
static void free_all_read_locks (THR_LOCK * lock, my_bool using_concurrent_insert) inline static
Definition at line 786 of file thr_lock.c.
 {
   THR_LOCK_DATA *data=lock->read_wait.data;
   check_locks(lock,"before freeing read locks",1);
   /* move all locks from read_wait list to read list */
   (*lock->read.last)=data;
   data->prev=lock->read.last;
   lock->read.last=lock->read_wait.last;
   /* Clear read_wait list */
   lock->read_wait.last= &lock->read_wait.data;
   do
   {
     mysql_cond_t *cond= data->cond;
     if ((int) data->type == (int) TL_READ_NO_INSERT)
     {
       if (using_concurrent_insert)
       {
     /*
       We can't free this lock;
       Link lock away from read chain back into read_wait chain
     */
     if (((*data->prev)=data->next))
       data->next->prev=data->prev;
     else
       lock->read.last=data->prev;
     *lock->read_wait.last= data;
     data->prev= lock->read_wait.last;
     lock->read_wait.last= &data->next;
     continue;
       }
       lock->read_no_write_count++;
     }
     /* purecov: begin inspected */
     DBUG_PRINT("lock",("giving read lock to thread: 0x%lx",
                data->owner->thread_id));
     /* purecov: end */
     data->cond=0;               /* Mark thread free */
     mysql_cond_signal(cond);
   } while ((data=data->next));
   *lock->read_wait.last=0;
   if (!lock->read_wait.data)
     lock->write_lock_count=0;
   check_locks(lock,"after giving read locks",0);
 }
References check_locks, st_lock_list::data, DBUG_PRINT, st_lock_list::last, mysql_cond_signal, st_thr_lock::read, st_thr_lock::read_no_write_count, st_thr_lock::read_wait, TL_READ_NO_INSERT, and st_thr_lock::write_lock_count.
Referenced by thr_reschedule_write_lock(), and wake_up_waiters().
get_cond()
static mysql_cond_t* get_cond (void) inline static
Definition at line 103 of file thr_lock.c.
 {
   return &my_thread_var->suspend;
 }
References my_thread_var.
Referenced by thr_reschedule_write_lock().
has_old_lock()
static my_bool has_old_lock (THR_LOCK_DATA * data, THR_LOCK_INFO * owner) inline static
Definition at line 368 of file thr_lock.c.
 {
   for ( ; data ; data=data->next)
   {
     if (thr_lock_owner_equal(data->owner, owner))
       return 1;                 /* Already locked by thread */
   }
   return 0;
 }
References thr_lock_owner_equal().
have_specific_lock()
static my_bool have_specific_lock (THR_LOCK_DATA * data, enum thr_lock_type type) inline static
Definition at line 378 of file thr_lock.c.
 {
   for ( ; data ; data=data->next)
   {
     if (data->type == type)
       return 1;
   }
   return 0;
 }
init_thr_lock()
my_bool init_thr_lock (void)
Definition at line 112 of file thr_lock.c.
 {
   thr_lock_inited=1;
   return 0;
 }
References thr_lock_inited.
sort_locks()
static void sort_locks (THR_LOCK_DATA ** data, uint count) static
Definition at line 1016 of file thr_lock.c.
 {
   THR_LOCK_DATA **pos,**end,**prev,*tmp;
   /* Sort locks with insertion sort (fast because almost always few locks) */
   for (pos=data+1,end=data+count; pos < end ; pos++)
   {
     tmp= *pos;
     if (LOCK_CMP(tmp,pos[-1]))
     {
       prev=pos;
       do {
     prev[0]=prev[-1];
       } while (--prev != data && LOCK_CMP(tmp,prev[-1]));
       prev[0]=tmp;
     }
   }
 }
References count(), LOCK_CMP, pos(), and prev().
thr_abort_locks()
void thr_abort_locks (THR_LOCK * lock, my_bool upgrade_lock)
Definition at line 1174 of file thr_lock.c.
 {
   THR_LOCK_DATA *data;
   DBUG_ENTER("thr_abort_locks");
   mysql_mutex_lock(&lock->mutex);
   for (data=lock->read_wait.data; data ; data=data->next)
   {
     data->type=TL_UNLOCK;           /* Mark killed */
     /* It's safe to signal the cond first: we're still holding the mutex. */
     mysql_cond_signal(data->cond);
     data->cond=0;               /* Removed from list */
   }
   for (data=lock->write_wait.data; data ; data=data->next)
   {
     data->type=TL_UNLOCK;
     mysql_cond_signal(data->cond);
     data->cond=0;
   }
   lock->read_wait.last= &lock->read_wait.data;
   lock->write_wait.last= &lock->write_wait.data;
   lock->read_wait.data=lock->write_wait.data=0;
   if (upgrade_lock && lock->write.data)
     lock->write.data->type=TL_WRITE_ONLY;
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References st_lock_list::data, DBUG_ENTER, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_cond_signal, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, TL_UNLOCK, TL_WRITE_ONLY, st_thr_lock_data::type, st_thr_lock::write, and st_thr_lock::write_wait.
thr_abort_locks_for_thread()
my_bool thr_abort_locks_for_thread (THR_LOCK * lock, my_thread_id thread_id)
Definition at line 1209 of file thr_lock.c.
 {
   THR_LOCK_DATA *data;
   my_bool found= FALSE;
   DBUG_ENTER("thr_abort_locks_for_thread");
   mysql_mutex_lock(&lock->mutex);
   for (data= lock->read_wait.data; data ; data= data->next)
   {
     if (data->owner->thread_id == thread_id)    /* purecov: tested */
     {
       DBUG_PRINT("info",("Aborting read-wait lock"));
       data->type= TL_UNLOCK;            /* Mark killed */
       /* It's safe to signal the cond first: we're still holding the mutex. */
       found= TRUE;
       mysql_cond_signal(data->cond);
       data->cond= 0;                /* Removed from list */
       if (((*data->prev)= data->next))
     data->next->prev= data->prev;
       else
     lock->read_wait.last= data->prev;
     }
   }
   for (data= lock->write_wait.data; data ; data= data->next)
   {
     if (data->owner->thread_id == thread_id) /* purecov: tested */
     {
       DBUG_PRINT("info",("Aborting write-wait lock"));
       data->type= TL_UNLOCK;
       found= TRUE;
       mysql_cond_signal(data->cond);
       data->cond= 0;
       if (((*data->prev)= data->next))
     data->next->prev= data->prev;
       else
     lock->write_wait.last= data->prev;
     }
   }
   wake_up_waiters(lock);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(found);
 }
References st_lock_list::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_lock_list::last, st_thr_lock::mutex, mysql_cond_signal, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, thread_id, TL_UNLOCK, TRUE, wake_up_waiters(), and st_thr_lock::write_wait.
thr_downgrade_write_lock()
void thr_downgrade_write_lock (THR_LOCK_DATA * in_data, enum thr_lock_type new_lock_type)
Definition at line 1282 of file thr_lock.c.
 {
   THR_LOCK *lock=in_data->lock;
 #ifndef DBUG_OFF
   enum thr_lock_type old_lock_type= in_data->type;
 #endif
   DBUG_ENTER("thr_downgrade_write_only_lock");
   mysql_mutex_lock(&lock->mutex);
   DBUG_ASSERT(old_lock_type == TL_WRITE_ONLY);
   DBUG_ASSERT(old_lock_type > new_lock_type);
   in_data->type= new_lock_type;
   check_locks(lock,"after downgrading lock",0);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References check_locks, DBUG_ASSERT, DBUG_ENTER, DBUG_VOID_RETURN, st_thr_lock_data::lock, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, TL_WRITE_ONLY, and st_thr_lock_data::type.
thr_lock()
enum enum_thr_lock_result thr_lock (THR_LOCK_DATA * data, THR_LOCK_INFO * owner, enum thr_lock_type lock_type, ulong lock_wait_timeout)
Definition at line 390 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum enum_thr_lock_result result= THR_LOCK_SUCCESS;
   struct st_lock_list *wait_queue;
   DBUG_ENTER("thr_lock");
   data->next=0;
   data->cond=0;                 /* safety */
   data->type=lock_type;
   data->owner= owner;                           /* Must be reset ! */
   mysql_mutex_lock(&lock->mutex);
   DBUG_PRINT("lock",("data: 0x%lx  thread: 0x%lx  lock: 0x%lx  type: %d",
                      (long) data, data->owner->thread_id,
                      (long) lock, (int) lock_type));
   check_locks(lock,(uint) lock_type <= (uint) TL_READ_NO_INSERT ?
           "enter read_lock" : "enter write_lock",0);
   if ((int) lock_type <= (int) TL_READ_NO_INSERT)
   {
     /* Request for READ lock */
     if (lock->write.data)
     {
       /*
         We can allow a read lock even if there is already a
         write lock on the table if they are owned by the same
         thread or if they satisfy the following lock
         compatibility matrix:
            Request
           /-------
          H|++++  WRITE_ALLOW_WRITE
          e|+++-  WRITE_CONCURRENT_INSERT
          l|++++  WRITE_DELAYED
          d ||||
            |||\= READ_NO_INSERT
            ||\ = READ_HIGH_PRIORITY
            |\  = READ_WITH_SHARED_LOCKS
            \   = READ
         + = Request can be satisified.
         - = Request cannot be satisified.
         READ_NO_INSERT and WRITE_ALLOW_WRITE should in principle
         be incompatible. However this will cause starvation of
         LOCK TABLE READ in InnoDB under high write load.
         See Bug#42147 for more information.
       */
       DBUG_PRINT("lock",("write locked 1 by thread: 0x%lx",
              lock->write.data->owner->thread_id));
       if (thr_lock_owner_equal(data->owner, lock->write.data->owner) ||
       (lock->write.data->type <= TL_WRITE_DELAYED &&
        (((int) lock_type <= (int) TL_READ_HIGH_PRIORITY) ||
         (lock->write.data->type != TL_WRITE_CONCURRENT_INSERT))))
       {                     /* Already got a write lock */
     (*lock->read.last)=data;        /* Add to running FIFO */
     data->prev=lock->read.last;
     lock->read.last= &data->next;
     if (lock_type == TL_READ_NO_INSERT)
       lock->read_no_write_count++;
     check_locks(lock,"read lock with old write lock",0);
     if (lock->get_status)
       (*lock->get_status)(data->status_param, 0);
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
       if (lock->write.data->type == TL_WRITE_ONLY)
       {
     /* We are not allowed to get a READ lock in this case */
     data->type=TL_UNLOCK;
         result= THR_LOCK_ABORTED;               /* Can't wait for this one */
     goto end;
       }
     }
     else if (!lock->write_wait.data ||
          lock->write_wait.data->type <= TL_WRITE_LOW_PRIORITY ||
          lock_type == TL_READ_HIGH_PRIORITY ||
          has_old_lock(lock->read.data, data->owner)) /* Has old read lock */
     {                       /* No important write-locks */
       (*lock->read.last)=data;          /* Add to running FIFO */
       data->prev=lock->read.last;
       lock->read.last= &data->next;
       if (lock->get_status)
     (*lock->get_status)(data->status_param, 0);
       if (lock_type == TL_READ_NO_INSERT)
     lock->read_no_write_count++;
       check_locks(lock,"read lock with no write locks",0);
       statistic_increment(locks_immediate,&THR_LOCK_lock);
       goto end;
     }
     /*
       We're here if there is an active write lock or no write
       lock but a high priority write waiting in the write_wait queue.
       In the latter case we should yield the lock to the writer.
     */
     wait_queue= &lock->read_wait;
   }
   else                      /* Request for WRITE lock */
   {
     if (lock_type == TL_WRITE_DELAYED)
     {
       if (lock->write.data && lock->write.data->type == TL_WRITE_ONLY)
       {
     data->type=TL_UNLOCK;
         result= THR_LOCK_ABORTED;               /* Can't wait for this one */
     goto end;
       }
       if (lock->write.data || lock->read.data)
       {
     /* Add delayed write lock to write_wait queue, and return at once */
     (*lock->write_wait.last)=data;
     data->prev=lock->write_wait.last;
     lock->write_wait.last= &data->next;
     data->cond=get_cond();
         /*
           We don't have to do get_status here as we will do it when we change
           the delayed lock to a real write lock
         */
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
     }
     else if (lock_type == TL_WRITE_CONCURRENT_INSERT && ! lock->check_status)
       data->type=lock_type= thr_upgraded_concurrent_insert_lock;
     if (lock->write.data)           /* If there is a write lock */
     {
       if (lock->write.data->type == TL_WRITE_ONLY)
       {
         /* purecov: begin tested */
         /* Allow lock owner to bypass TL_WRITE_ONLY. */
         if (!thr_lock_owner_equal(data->owner, lock->write.data->owner))
         {
           /* We are not allowed to get a lock in this case */
           data->type=TL_UNLOCK;
           result= THR_LOCK_ABORTED;               /* Can't wait for this one */
           goto end;
         }
         /* purecov: end */
       }
       /*
         The idea is to allow us to get a lock at once if we already have
         a write lock or if there is no pending write locks and if all
         write locks are of TL_WRITE_ALLOW_WRITE type.
         Note that, since lock requests for the same table are sorted in
         such way that requests with higher thr_lock_type value come first
         (with one exception (*)), lock being requested usually (**) has
         equal or "weaker" type than one which thread might have already
         acquired.
         *)  The only exception to this rule is case when type of old lock
             is TL_WRITE_LOW_PRIORITY and type of new lock is changed inside
             of thr_lock() from TL_WRITE_CONCURRENT_INSERT to TL_WRITE since
             engine turns out to be not supporting concurrent inserts.
             Note that since TL_WRITE has the same compatibility rules as
             TL_WRITE_LOW_PRIORITY (their only difference is priority),
             it is OK to grant new lock without additional checks in such
             situation.
         **) The exceptions are situations when:
             - when old lock type is TL_WRITE_DELAYED
             But these should never happen within MySQL.
         Therefore it is OK to allow acquiring write lock on the table if
         this thread already holds some write lock on it.
         (INSERT INTO t1 VALUES (f1()), where f1() is stored function which
         tries to update t1, is an example of statement which requests two
         different types of write lock on the same table).
       */
       DBUG_ASSERT(! has_old_lock(lock->write.data, data->owner) ||
                   ((lock_type <= lock->write.data->type ||
                     (lock_type == TL_WRITE &&
                      lock->write.data->type == TL_WRITE_LOW_PRIORITY)) &&
                    lock->write.data->type != TL_WRITE_DELAYED));
       if ((lock_type == TL_WRITE_ALLOW_WRITE &&
            ! lock->write_wait.data &&
            lock->write.data->type == TL_WRITE_ALLOW_WRITE) ||
           has_old_lock(lock->write.data, data->owner))
       {
     /*
           We have already got a write lock or all locks are
           TL_WRITE_ALLOW_WRITE
         */
         DBUG_PRINT("info", ("write_wait.data: 0x%lx  old_type: %d",
                             (ulong) lock->write_wait.data,
                             lock->write.data->type));
     (*lock->write.last)=data;   /* Add to running fifo */
     data->prev=lock->write.last;
     lock->write.last= &data->next;
     check_locks(lock,"second write lock",0);
     if (data->lock->get_status)
       (*data->lock->get_status)(data->status_param, 0);
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
       DBUG_PRINT("lock",("write locked 2 by thread: 0x%lx",
              lock->write.data->owner->thread_id));
     }
     else
     {
       DBUG_PRINT("info", ("write_wait.data: 0x%lx",
                           (ulong) lock->write_wait.data));
       if (!lock->write_wait.data)
       {                     /* no scheduled write locks */
         my_bool concurrent_insert= 0;
     if (lock_type == TL_WRITE_CONCURRENT_INSERT)
         {
           concurrent_insert= 1;
           if ((*lock->check_status)(data->status_param))
           {
             concurrent_insert= 0;
             data->type=lock_type= thr_upgraded_concurrent_insert_lock;
           }
         }
     if (!lock->read.data ||
         (lock_type <= TL_WRITE_DELAYED &&
          ((lock_type != TL_WRITE_CONCURRENT_INSERT &&
            lock_type != TL_WRITE_ALLOW_WRITE) ||
           !lock->read_no_write_count)))
     {
       (*lock->write.last)=data;     /* Add as current write lock */
       data->prev=lock->write.last;
       lock->write.last= &data->next;
       if (data->lock->get_status)
         (*data->lock->get_status)(data->status_param, concurrent_insert);
       check_locks(lock,"only write lock",0);
       statistic_increment(locks_immediate,&THR_LOCK_lock);
       goto end;
     }
       }
       DBUG_PRINT("lock",("write locked 3 by thread: 0x%lx  type: %d",
              lock->read.data->owner->thread_id, data->type));
     }
     wait_queue= &lock->write_wait;
   }
   /* Can't get lock yet;  Wait for it */
   DBUG_RETURN(wait_for_lock(wait_queue, data, 0, lock_wait_timeout));
 end:
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(result);
 }
thr_lock_data_init()
void thr_lock_data_init (THR_LOCK * lock, THR_LOCK_DATA * data, void * param)
Definition at line 357 of file thr_lock.c.
 {
   data->lock=lock;
   data->type=TL_UNLOCK;
   data->owner= 0;                               /* no owner yet */
   data->status_param=param;
   data->cond=0;
 }
References TL_UNLOCK.
thr_lock_delete()
void thr_lock_delete (THR_LOCK * lock)
Definition at line 337 of file thr_lock.c.
 {
   DBUG_ENTER("thr_lock_delete");
   mysql_mutex_lock(&THR_LOCK_lock);
   thr_lock_thread_list=list_delete(thr_lock_thread_list,&lock->list);
   mysql_mutex_unlock(&THR_LOCK_lock);
   mysql_mutex_destroy(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, st_thr_lock::list, list_delete(), st_thr_lock::mutex, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_lock, and thr_lock_thread_list.
thr_lock_info_init()
void thr_lock_info_init (THR_LOCK_INFO * info)
Definition at line 348 of file thr_lock.c.
 {
   struct st_my_thread_var *tmp= my_thread_var;
   info->thread=    tmp->pthread_self;
   info->thread_id= tmp->id;
 }
References st_my_thread_var::id, my_thread_var, st_my_thread_var::pthread_self, st_thr_lock_info::thread, and st_thr_lock_info::thread_id.
thr_lock_init()
void thr_lock_init (THR_LOCK * lock)
Definition at line 319 of file thr_lock.c.
 {
   DBUG_ENTER("thr_lock_init");
   bzero((char*) lock,sizeof(*lock));
   mysql_mutex_init(key_THR_LOCK_mutex, &lock->mutex, MY_MUTEX_INIT_FAST);
   lock->read.last= &lock->read.data;
   lock->read_wait.last= &lock->read_wait.data;
   lock->write_wait.last= &lock->write_wait.data;
   lock->write.last= &lock->write.data;
   mysql_mutex_lock(&THR_LOCK_lock);              /* Add to locks in use */
   lock->list.data=(void*) lock;
   thr_lock_thread_list=list_add(thr_lock_thread_list,&lock->list);
   mysql_mutex_unlock(&THR_LOCK_lock);
   DBUG_VOID_RETURN;
 }
References bzero, st_lock_list::data, st_list::data, DBUG_ENTER, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::list, list_add(), st_thr_lock::mutex, MY_MUTEX_INIT_FAST, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, st_thr_lock::read_wait, THR_LOCK_lock, thr_lock_thread_list, st_thr_lock::write, and st_thr_lock::write_wait.
thr_lock_merge_status()
void thr_lock_merge_status (THR_LOCK_DATA ** data, uint count)
Ensure that all locks for a given table have the same status_param.
This is a MyISAM and possibly Maria specific crutch. MyISAM engine stores data file length, record count and other table properties in status_param member of handler. When a table is locked, connection-local copy is made from a global copy (myisam_share) by mi_get_status(). When a table is unlocked, the changed status is transferred back to the global share by mi_update_status().
One thing MyISAM doesn't do is to ensure that when the same table is opened twice in a connection all instances share the same status_param. This is necessary, however: for one, to keep all instances of a connection "on the same page" with regard to the current state of the table. For other, unless this is done, myisam_share will always get updated from the last unlocked instance (in mi_update_status()), and when this instance was not the one that was used to update data, records may be lost.
For each table, this function looks up the last lock_data in the list of acquired locks, and makes sure that all other instances share status_param with it.
Definition at line 1094 of file thr_lock.c.
 {
 #if !defined(DONT_USE_RW_LOCKS)
   THR_LOCK_DATA **pos= data;
   THR_LOCK_DATA **end= data + count;
   if (count > 1)
   {
     THR_LOCK_DATA *last_lock= end[-1];
     pos=end-1;
     do
     {
       pos--;
       if (last_lock->lock == (*pos)->lock &&
       last_lock->lock->copy_status)
       {
     if (last_lock->type <= TL_READ_NO_INSERT)
     {
       THR_LOCK_DATA **read_lock;
       /*
         If we are locking the same table with read locks we must ensure
         that all tables share the status of the last write lock or
         the same read lock.
       */
       for (;
            (*pos)->type <= TL_READ_NO_INSERT &&
          pos != data &&
          pos[-1]->lock == (*pos)->lock ;
            pos--) ;
       read_lock = pos+1;
       do
       {
         (last_lock->lock->copy_status)((*read_lock)->status_param,
                        (*pos)->status_param);
       } while (*(read_lock++) != last_lock);
       last_lock= (*pos);            /* Point at last write lock */
     }
     else
       (*last_lock->lock->copy_status)((*pos)->status_param,
                       last_lock->status_param);
       }
       else
     last_lock=(*pos);
     } while (pos != data);
   }
 #endif
 }
References st_thr_lock::copy_status, count(), st_lock_list::data, st_thr_lock_data::lock, pos(), st_thr_lock_data::status_param, TL_READ_NO_INSERT, and st_thr_lock_data::type.
thr_lock_owner_equal()
static my_bool thr_lock_owner_equal (THR_LOCK_INFO * rhs, THR_LOCK_INFO * lhs) inline static
Definition at line 119 of file thr_lock.c.
 {
   return rhs == lhs;
 }
Referenced by has_old_lock().
thr_multi_lock()
enum enum_thr_lock_result thr_multi_lock (THR_LOCK_DATA ** data, uint count, THR_LOCK_INFO * owner, ulong lock_wait_timeout)
Definition at line 1016 of file thr_lock.c.
 {
   THR_LOCK_DATA **pos,**end;
   DBUG_ENTER("thr_multi_lock");
   DBUG_PRINT("lock",("data: 0x%lx  count: %d", (long) data, count));
   if (count > 1)
     sort_locks(data,count);
   /* lock everything */
   for (pos=data,end=data+count; pos < end ; pos++)
   {
     enum enum_thr_lock_result result= thr_lock(*pos, owner, (*pos)->type,
                                                lock_wait_timeout);
     if (result != THR_LOCK_SUCCESS)
     {                       /* Aborted */
       thr_multi_unlock(data,(uint) (pos-data));
       DBUG_RETURN(result);
     }
     DEBUG_SYNC_C("thr_multi_lock_after_thr_lock");
 #ifdef MAIN
     printf("Thread: %s  Got lock: 0x%lx  type: %d\n",my_thread_name(),
        (long) pos[0]->lock, pos[0]->type); fflush(stdout);
 #endif
   }
   thr_lock_merge_status(data, count);
   DBUG_RETURN(THR_LOCK_SUCCESS);
 }
thr_multi_unlock()
void thr_multi_unlock (THR_LOCK_DATA ** data, uint count)
Definition at line 1144 of file thr_lock.c.
 {
   THR_LOCK_DATA **pos,**end;
   DBUG_ENTER("thr_multi_unlock");
   DBUG_PRINT("lock",("data: 0x%lx  count: %d", (long) data, count));
   for (pos=data,end=data+count; pos < end ; pos++)
   {
 #ifdef MAIN
     printf("Thread: %s  Rel lock: 0x%lx  type: %d\n",
        my_thread_name(), (long) pos[0]->lock, pos[0]->type);
     fflush(stdout);
 #endif
     if ((*pos)->type != TL_UNLOCK)
       thr_unlock(*pos);
     else
     {
       DBUG_PRINT("lock",("Free lock: data: 0x%lx  thread: 0x%lx  lock: 0x%lx",
                          (long) *pos, (*pos)->owner->thread_id,
                          (long) (*pos)->lock));
     }
   }
   DBUG_VOID_RETURN;
 }
References count(), DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, my_thread_name(), pos(), printf(), thr_unlock(), and TL_UNLOCK.
thr_print_lock()
static void thr_print_lock (const char * name, struct st_lock_list * list) static
Definition at line 1394 of file thr_lock.c.
 {
   THR_LOCK_DATA *data,**prev;
   uint count=0;
   if (list->data)
   {
     printf("%-10s: ",name);
     prev= &list->data;
     for (data=list->data; data && count++ < MAX_LOCKS ; data=data->next)
     {
       printf("0x%lx (%lu:%d); ", (ulong) data, data->owner->thread_id,
              (int) data->type);
       if (data->prev != prev)
     printf("\nWarning: prev didn't point at previous lock\n");
       prev= &data->next;
     }
     puts("");
     if (prev != list->last)
       printf("Warning: last didn't point at last lock\n");
   }
 }
References count(), st_lock_list::data, list(), MAX_LOCKS, name, prev(), and printf().
Referenced by thr_print_locks().
thr_print_locks()
void thr_print_locks (void)
Definition at line 1417 of file thr_lock.c.
 {
   LIST *list;
   uint count=0;
   mysql_mutex_lock(&THR_LOCK_lock);
   puts("Current locks:");
   for (list= thr_lock_thread_list; list && count++ < MAX_THREADS;
        list= list_rest(list))
   {
     THR_LOCK *lock=(THR_LOCK*) list->data;
     mysql_mutex_lock(&lock->mutex);
     printf("lock: 0x%lx:",(ulong) lock);
     if ((lock->write_wait.data || lock->read_wait.data) &&
     (! lock->read.data && ! lock->write.data))
       printf(" WARNING: ");
     if (lock->write.data)
       printf(" write");
     if (lock->write_wait.data)
       printf(" write_wait");
     if (lock->read.data)
       printf(" read");
     if (lock->read_wait.data)
       printf(" read_wait");
     puts("");
     thr_print_lock("write",&lock->write);
     thr_print_lock("write_wait",&lock->write_wait);
     thr_print_lock("read",&lock->read);
     thr_print_lock("read_wait",&lock->read_wait);
     mysql_mutex_unlock(&lock->mutex);
     puts("");
   }
   fflush(stdout);
   mysql_mutex_unlock(&THR_LOCK_lock);
 }
References count(), st_lock_list::data, list(), list_rest, MAX_THREADS, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, printf(), st_thr_lock::read, st_thr_lock::read_wait, THR_LOCK_lock, thr_lock_thread_list, thr_print_lock(), st_thr_lock::write, and st_thr_lock::write_wait.
thr_reschedule_write_lock()
my_bool thr_reschedule_write_lock (THR_LOCK_DATA * data, ulong lock_wait_timeout)
Definition at line 1354 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum thr_lock_type write_lock_type;
   DBUG_ENTER("thr_reschedule_write_lock");
   mysql_mutex_lock(&lock->mutex);
   if (!lock->read_wait.data)            /* No waiting read locks */
   {
     mysql_mutex_unlock(&lock->mutex);
     DBUG_RETURN(0);
   }
   write_lock_type= data->type;
   data->type=TL_WRITE_DELAYED;
   if (lock->update_status)
     (*lock->update_status)(data->status_param);
   if (((*data->prev)=data->next))       /* remove from lock-list */
     data->next->prev= data->prev;
   else
     lock->write.last=data->prev;
   if ((data->next=lock->write_wait.data))   /* Put first in lock_list */
     data->next->prev= &data->next;
   else
     lock->write_wait.last= &data->next;
   data->prev= &lock->write_wait.data;
   data->cond=get_cond();            /* This was zero */
   lock->write_wait.data=data;
   free_all_read_locks(lock,0);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(thr_upgrade_write_delay_lock(data, write_lock_type,
                                            lock_wait_timeout));
 }
References st_lock_list::data, DBUG_ENTER, DBUG_RETURN, free_all_read_locks(), get_cond(), if(), st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, thr_upgrade_write_delay_lock(), TL_WRITE_DELAYED, st_thr_lock::update_status, st_thr_lock::write, and st_thr_lock::write_wait.
thr_set_lock_wait_callback()
void thr_set_lock_wait_callback (void(*)(void) before_wait, void(*)(void) after_wait)
Definition at line 96 of file thr_lock.c.
 {
   before_lock_wait= before_wait;
   after_lock_wait= after_wait;
 }
References after_lock_wait, and before_lock_wait.
thr_unlock()
void thr_unlock (THR_LOCK_DATA * data)
Definition at line 838 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum thr_lock_type lock_type=data->type;
   DBUG_ENTER("thr_unlock");
   DBUG_PRINT("lock",("data: 0x%lx  thread: 0x%lx  lock: 0x%lx",
                      (long) data, data->owner->thread_id, (long) lock));
   mysql_mutex_lock(&lock->mutex);
   check_locks(lock,"start of release lock",0);
   if (((*data->prev)=data->next))       /* remove from lock-list */
     data->next->prev= data->prev;
   else if (lock_type <= TL_READ_NO_INSERT)
     lock->read.last=data->prev;
   else if (lock_type == TL_WRITE_DELAYED && data->cond)
   {
     /*
       This only happens in extreme circumstances when a
       write delayed lock that is waiting for a lock
     */
     lock->write_wait.last=data->prev;       /* Put it on wait queue */
   }
   else
     lock->write.last=data->prev;
   if (lock_type >= TL_WRITE_CONCURRENT_INSERT)
   {
     if (lock->update_status)
       (*lock->update_status)(data->status_param);
   }
   else
   {
     if (lock->restore_status)
       (*lock->restore_status)(data->status_param);
   }
   if (lock_type == TL_READ_NO_INSERT)
     lock->read_no_write_count--;
   data->type=TL_UNLOCK;             /* Mark unlocked */
   check_locks(lock,"after releasing lock",1);
   wake_up_waiters(lock);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References check_locks, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, st_thr_lock::read_no_write_count, st_thr_lock::restore_status, TL_READ_NO_INSERT, TL_UNLOCK, TL_WRITE_CONCURRENT_INSERT, TL_WRITE_DELAYED, st_thr_lock::update_status, wake_up_waiters(), st_thr_lock::write, and st_thr_lock::write_wait.
Referenced by thr_multi_unlock().
thr_upgrade_write_delay_lock()
my_bool thr_upgrade_write_delay_lock (THR_LOCK_DATA * data, enum thr_lock_type new_lock_type, ulong lock_wait_timeout)
Definition at line 1303 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   DBUG_ENTER("thr_upgrade_write_delay_lock");
   mysql_mutex_lock(&lock->mutex);
   if (data->type == TL_UNLOCK || data->type >= TL_WRITE_LOW_PRIORITY)
   {
     mysql_mutex_unlock(&lock->mutex);
     DBUG_RETURN(data->type == TL_UNLOCK);   /* Test if Aborted */
   }
   check_locks(lock,"before upgrading lock",0);
   /* TODO:  Upgrade to TL_WRITE_CONCURRENT_INSERT in some cases */
   data->type= new_lock_type;                    /* Upgrade lock */
   /* Check if someone has given us the lock */
   if (!data->cond)
   {
     if (!lock->read.data)           /* No read locks */
     {                       /* We have the lock */
       if (data->lock->get_status)
     (*data->lock->get_status)(data->status_param, 0);
       mysql_mutex_unlock(&lock->mutex);
       DBUG_RETURN(0);
     }
     if (((*data->prev)=data->next))     /* remove from lock-list */
       data->next->prev= data->prev;
     else
       lock->write.last=data->prev;
     if ((data->next=lock->write_wait.data)) /* Put first in lock_list */
       data->next->prev= &data->next;
     else
       lock->write_wait.last= &data->next;
     data->prev= &lock->write_wait.data;
     lock->write_wait.data=data;
     check_locks(lock,"upgrading lock",0);
   }
   else
   {
     check_locks(lock,"waiting for lock",0);
   }
   DBUG_RETURN(wait_for_lock(&lock->write_wait,data,1, lock_wait_timeout));
 }
References check_locks, st_lock_list::data, DBUG_ENTER, DBUG_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, TL_UNLOCK, TL_WRITE_LOW_PRIORITY, wait_for_lock(), st_thr_lock::write, and st_thr_lock::write_wait.
Referenced by thr_reschedule_write_lock().
wait_for_lock()
static enum enum_thr_lock_result wait_for_lock (struct st_lock_list * wait, THR_LOCK_DATA * data, my_bool in_wait_list, ulong lock_wait_timeout) static
Definition at line 390 of file thr_lock.c.
 {
   struct st_my_thread_var *thread_var= my_thread_var;
   mysql_cond_t *cond= &thread_var->suspend;
   struct timespec wait_timeout;
   enum enum_thr_lock_result result= THR_LOCK_ABORTED;
   const char *old_proc_info;
   DBUG_ENTER("wait_for_lock");
   /*
     One can use this to signal when a thread is going to wait for a lock.
     See debug_sync.cc.
     Beware of waiting for a signal here. The lock has aquired its mutex.
     While waiting on a signal here, the locking thread could not aquire
     the mutex to release the lock. One could lock up the table
     completely.
     In detail it works so: When thr_lock() tries to acquire a table
     lock, it locks the lock->mutex, checks if it can have the lock, and
     if not, it calls wait_for_lock(). Here it unlocks the table lock
     while waiting on a condition. The sync point is located before this
     wait for condition. If we have a waiting action here, we hold the
     the table locks mutex all the time. Any attempt to look at the table
     lock by another thread blocks it immediately on lock->mutex. This
     can easily become an unexpected and unobvious blockage. So be
     warned: Do not request a WAIT_FOR action for the 'wait_for_lock'
     sync point unless you really know what you do.
   */
   DEBUG_SYNC_C("wait_for_lock");
   if (!in_wait_list)
   {
     (*wait->last)=data;             /* Wait for lock */
     data->prev= wait->last;
     wait->last= &data->next;
   }
   statistic_increment(locks_waited, &THR_LOCK_lock);
   /* Set up control struct to allow others to abort locks */
   thread_var->current_mutex= &data->lock->mutex;
   thread_var->current_cond=  cond;
   data->cond= cond;
   old_proc_info= proc_info_hook(NULL, "Waiting for table level lock",
                                 __func__, __FILE__, __LINE__);
   /*
     Since before_lock_wait potentially can create more threads to
     scheduler work for, we don't want to call the before_lock_wait
     callback unless it will really start to wait.
     For similar reasons, we do not want to call before_lock_wait and
     after_lock_wait for each lap around the loop, so we restrict
     ourselves to call it before_lock_wait once before starting to wait
     and once after the thread has exited the wait loop.
    */
   if ((!thread_var->abort || in_wait_list) && before_lock_wait)
     (*before_lock_wait)();
   set_timespec(wait_timeout, lock_wait_timeout);
   while (!thread_var->abort || in_wait_list)
   {
     int rc= mysql_cond_timedwait(cond, &data->lock->mutex, &wait_timeout);
     /*
       We must break the wait if one of the following occurs:
       - the connection has been aborted (!thread_var->abort), but
         this is not a delayed insert thread (in_wait_list). For a delayed
         insert thread the proper action at shutdown is, apparently, to
         acquire the lock and complete the insert.
       - the lock has been granted (data->cond is set to NULL by the granter),
         or the waiting has been aborted (additionally data->type is set to
         TL_UNLOCK).
       - the wait has timed out (rc == ETIMEDOUT)
       Order of checks below is important to not report about timeout
       if the predicate is true.
     */
     if (data->cond == 0)
     {
       DBUG_PRINT("thr_lock", ("lock granted/aborted"));
       break;
     }
     if (rc == ETIMEDOUT || rc == ETIME)
     {
       /* purecov: begin inspected */
       DBUG_PRINT("thr_lock", ("lock timed out"));
       result= THR_LOCK_WAIT_TIMEOUT;
       break;
       /* purecov: end */
     }
   }
   /*
     We call the after_lock_wait callback once the wait loop has
     finished.
    */
   if (after_lock_wait)
     (*after_lock_wait)();
   DBUG_PRINT("thr_lock", ("aborted: %d  in_wait_list: %d",
                           thread_var->abort, in_wait_list));
   if (data->cond || data->type == TL_UNLOCK)
   {
     if (data->cond)                             /* aborted or timed out */
     {
       if (((*data->prev)=data->next))       /* remove from wait-list */
     data->next->prev= data->prev;
       else
     wait->last=data->prev;
       data->type= TL_UNLOCK;                    /* No lock */
       check_locks(data->lock, "killed or timed out wait_for_lock", 1);
       wake_up_waiters(data->lock);
     }
     else
     {
       DBUG_PRINT("thr_lock", ("lock aborted"));
       check_locks(data->lock, "aborted wait_for_lock", 0);
     }
   }
   else
   {
     result= THR_LOCK_SUCCESS;
     if (data->lock->get_status)
       (*data->lock->get_status)(data->status_param, 0);
     check_locks(data->lock,"got wait_for_lock",0);
   }
   mysql_mutex_unlock(&data->lock->mutex);
   /* The following must be done after unlock of lock->mutex */
   mysql_mutex_lock(&thread_var->mutex);
   thread_var->current_mutex= 0;
   thread_var->current_cond=  0;
   mysql_mutex_unlock(&thread_var->mutex);
   proc_info_hook(NULL, old_proc_info, __func__, __FILE__, __LINE__);
   DBUG_RETURN(result);
 }
Referenced by thr_upgrade_write_delay_lock().
wake_up_waiters()
static void wake_up_waiters (THR_LOCK * lock) static
Wake up all threads which pending requests for the lock can be satisfied.
Parameters
lock Lock for which threads should be woken up
Definition at line 890 of file thr_lock.c.
 {
   THR_LOCK_DATA *data;
   enum thr_lock_type lock_type;
   DBUG_ENTER("wake_up_waiters");
   if (!lock->write.data)            /* If no active write locks */
   {
     data=lock->write_wait.data;
     if (!lock->read.data)           /* If no more locks in use */
     {
       /* Release write-locks with TL_WRITE or TL_WRITE_ONLY priority first */
       if (data &&
       (data->type != TL_WRITE_LOW_PRIORITY || !lock->read_wait.data ||
        lock->read_wait.data->type < TL_READ_HIGH_PRIORITY))
       {
     if (lock->write_lock_count++ > max_write_lock_count)
     {
       /* Too many write locks in a row;  Release all waiting read locks */
       lock->write_lock_count=0;
       if (lock->read_wait.data)
       {
         DBUG_PRINT("info",("Freeing all read_locks because of max_write_lock_count"));
         free_all_read_locks(lock,0);
         goto end;
       }
     }
     for (;;)
     {
       if (((*data->prev)=data->next))   /* remove from wait-list */
         data->next->prev= data->prev;
       else
         lock->write_wait.last=data->prev;
       (*lock->write.last)=data;     /* Put in execute list */
       data->prev=lock->write.last;
       data->next=0;
       lock->write.last= &data->next;
       if (data->type == TL_WRITE_CONCURRENT_INSERT &&
           (*lock->check_status)(data->status_param))
         data->type=TL_WRITE;            /* Upgrade lock */
           /* purecov: begin inspected */
       DBUG_PRINT("lock",("giving write lock of type %d to thread: 0x%lx",
                  data->type, data->owner->thread_id));
           /* purecov: end */
       {
             mysql_cond_t *cond= data->cond;
         data->cond=0;               /* Mark thread free */
             mysql_cond_signal(cond);                    /* Start waiting thread */
       }
       if (data->type != TL_WRITE_ALLOW_WRITE ||
           !lock->write_wait.data ||
           lock->write_wait.data->type != TL_WRITE_ALLOW_WRITE)
         break;
       data=lock->write_wait.data;       /* Free this too */
     }
     if (data->type >= TL_WRITE_LOW_PRIORITY)
           goto end;
     /* Release possible read locks together with the write lock */
       }
       if (lock->read_wait.data)
     free_all_read_locks(lock,
                 data &&
                 (data->type == TL_WRITE_CONCURRENT_INSERT ||
                  data->type == TL_WRITE_ALLOW_WRITE));
       else
       {
     DBUG_PRINT("lock",("No waiting read locks to free"));
       }
     }
     else if (data &&
          (lock_type=data->type) <= TL_WRITE_DELAYED &&
          ((lock_type != TL_WRITE_CONCURRENT_INSERT &&
            lock_type != TL_WRITE_ALLOW_WRITE) ||
           !lock->read_no_write_count))
     {
       /*
     For DELAYED, ALLOW_READ, WRITE_ALLOW_WRITE or CONCURRENT_INSERT locks
     start WRITE locks together with the READ locks
       */
       if (lock_type == TL_WRITE_CONCURRENT_INSERT &&
       (*lock->check_status)(data->status_param))
       {
     data->type=TL_WRITE;            /* Upgrade lock */
     if (lock->read_wait.data)
       free_all_read_locks(lock,0);
     goto end;
       }
       do {
         mysql_cond_t *cond= data->cond;
     if (((*data->prev)=data->next))     /* remove from wait-list */
       data->next->prev= data->prev;
     else
       lock->write_wait.last=data->prev;
     (*lock->write.last)=data;       /* Put in execute list */
     data->prev=lock->write.last;
     lock->write.last= &data->next;
     data->next=0;               /* Only one write lock */
     data->cond=0;               /* Mark thread free */
         mysql_cond_signal(cond);                /* Start waiting thread */
       } while (lock_type == TL_WRITE_ALLOW_WRITE &&
            (data=lock->write_wait.data) &&
            data->type == TL_WRITE_ALLOW_WRITE);
       if (lock->read_wait.data)
     free_all_read_locks(lock,
                 (lock_type == TL_WRITE_CONCURRENT_INSERT ||
                  lock_type == TL_WRITE_ALLOW_WRITE));
     }
     else if (!data && lock->read_wait.data)
       free_all_read_locks(lock,0);
   }
 end:
   check_locks(lock, "after waking up waiters", 0);
   DBUG_VOID_RETURN;
 }
References check_locks, st_thr_lock::check_status, st_lock_list::data, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, free_all_read_locks(), st_lock_list::last, max_write_lock_count, mysql_cond_signal, st_thr_lock::read, st_thr_lock::read_no_write_count, st_thr_lock::read_wait, TL_READ_HIGH_PRIORITY, TL_WRITE, TL_WRITE_ALLOW_WRITE, TL_WRITE_CONCURRENT_INSERT, TL_WRITE_DELAYED, TL_WRITE_LOW_PRIORITY, st_thr_lock_data::type, st_thr_lock::write, st_thr_lock::write_lock_count, and st_thr_lock::write_wait.
Referenced by thr_abort_locks_for_thread(), and thr_unlock().
Variable Documentation
after_lock_wait
void(* after_lock_wait) (void)=0 (void) static
Definition at line 94 of file thr_lock.c.
Referenced by thr_set_lock_wait_callback().
before_lock_wait
void(* before_lock_wait) (void)=0 (void) static
Definition at line 93 of file thr_lock.c.
Referenced by thr_set_lock_wait_callback().
locks_immediate
ulong locks_immediate = 0L
Definition at line 82 of file thr_lock.c.
locks_waited
ulong locks_waited = 0L
Definition at line 82 of file thr_lock.c.
max_write_lock_count
ulong max_write_lock_count = ~(ulong) 0L
Definition at line 91 of file thr_lock.c.
Referenced by wake_up_waiters().
thr_lock_inited
my_bool thr_lock_inited =0
Definition at line 81 of file thr_lock.c.
Referenced by init_thr_lock().
thr_lock_thread_list
LIST* thr_lock_thread_list
Definition at line 90 of file thr_lock.c.
Referenced by thr_lock_delete(), thr_lock_init(), and thr_print_locks().
thr_upgraded_concurrent_insert_lock
enum thr_lock_type thr_upgraded_concurrent_insert_lock = TL_WRITE
Definition at line 82 of file thr_lock.c.