Azerotcore-wotlk: rcContext Class Reference
rcContext Class Reference
#include <Recast.h>
Public Member Functions
rcContext (bool state=true)
virtual ~rcContext ()
void enableLog (bool state)
void resetLog ()
Clears all log entries.
void log (const rcLogCategory category, const char *format,...)
void enableTimer (bool state)
void resetTimers ()
Clears all peformance timers. (Resets all to unused.)
void startTimer (const rcTimerLabel label)
void stopTimer (const rcTimerLabel label)
int getAccumulatedTime (const rcTimerLabel label) const
Protected Member Functions
virtual void doResetLog ()
Clears all log entries.
virtual void doLog (const rcLogCategory, const char *, const int)
virtual void doResetTimers ()
Clears all timers. (Resets all to unused.)
virtual void doStartTimer (const rcTimerLabel)
virtual void doStopTimer (const rcTimerLabel)
virtual int doGetAccumulatedTime (const rcTimerLabel) const
Protected Attributes
bool m_logEnabled
True if logging is enabled.
bool m_timerEnabled
True if the performance timers are enabled.
Detailed Description
Provides an interface for optional logging and performance tracking of the Recast build process.
This class does not provide logging or timer functionality on its own. Both must be provided by a concrete implementation by overriding the protected member functions. Also, this class does not provide an interface for extracting log messages. (Only adding them.) So concrete implementations must provide one.
If no logging or timers are required, just pass an instance of this class through the Recast build process.
Definition at line 101 of file Recast.h.
Constructor & Destructor Documentation
rcContext()
rcContext::rcContext (bool state = true) inline
Contructor.
Parameters
[in] state TRUE if the logging and performance timers should be enabled. [Default: true]
Definition at line 107 of file Recast.h.
 : m_logEnabled(state), m_timerEnabled(state) {}
~rcContext()
virtual rcContext::~rcContext () inline virtual
Definition at line 108 of file Recast.h.
 {}
Member Function Documentation
doGetAccumulatedTime()
virtual int rcContext::doGetAccumulatedTime (const rcTimerLabel) const inline protected virtual
Returns the total accumulated time of the specified performance timer.
Parameters
[in] label The category of the timer.
Returns
The accumulated time of the timer, or -1 if timers are disabled or the timer has never been started.
Definition at line 167 of file Recast.h.
 { return -1; }
Referenced by getAccumulatedTime().
doLog()
virtual void rcContext::doLog (const rcLogCategory, const char * , const int) inline protected virtual
Logs a message.
Parameters
[in] category The category of the message.
[in] msg The formatted message.
[in] len The length of the formatted message.
Definition at line 151 of file Recast.h.
 {}
Referenced by log().
doResetLog()
virtual void rcContext::doResetLog () inline protected virtual
Clears all log entries.
Definition at line 145 of file Recast.h.
 {}
Referenced by resetLog().
doResetTimers()
virtual void rcContext::doResetTimers () inline protected virtual
Clears all timers. (Resets all to unused.)
Definition at line 154 of file Recast.h.
 {}
Referenced by resetTimers().
doStartTimer()
virtual void rcContext::doStartTimer (const rcTimerLabel) inline protected virtual
Starts the specified performance timer.
Parameters
[in] label The category of timer.
Definition at line 158 of file Recast.h.
 {}
Referenced by startTimer().
doStopTimer()
virtual void rcContext::doStopTimer (const rcTimerLabel) inline protected virtual
Stops the specified performance timer.
Parameters
[in] label The category of the timer.
Definition at line 162 of file Recast.h.
 {}
Referenced by stopTimer().
enableLog()
void rcContext::enableLog (bool state) inline
Enables or disables logging.
Parameters
[in] state TRUE if logging should be enabled.
Definition at line 112 of file Recast.h.
 { m_logEnabled = state; }
References m_logEnabled.
enableTimer()
void rcContext::enableTimer (bool state) inline
Enables or disables the performance timers.
Parameters
[in] state TRUE if timers should be enabled.
Definition at line 124 of file Recast.h.
 { m_timerEnabled = state; }
References m_timerEnabled.
getAccumulatedTime()
int rcContext::getAccumulatedTime (const rcTimerLabel label) const inline
Returns the total accumulated time of the specified performance timer.
Parameters
label The category of the timer.
Returns
The accumulated time of the timer, or -1 if timers are disabled or the timer has never been started.
Definition at line 140 of file Recast.h.
 { return m_timerEnabled ? doGetAccumulatedTime(label) : -1; }
References doGetAccumulatedTime(), and m_timerEnabled.
log()
void rcContext::log (const rcLogCategory category, const char * format, ...)
Logs a message.
Parameters
[in] category The category of the message.
[in] format The message.
Example:
// Where ctx is an instance of rcContext and filepath is a char array.
ctx->log(RC_LOG_ERROR, "buildTiledNavigation: Could not load '%s'", filepath);
Definition at line 79 of file Recast.cpp.
 {
     if (!m_logEnabled)
         return;
     static const int MSG_SIZE = 512;
     char msg[MSG_SIZE];
     va_list ap;
     va_start(ap, format);
     int len = vsnprintf(msg, MSG_SIZE, format, ap);
     if (len >= MSG_SIZE)
     {
         len = MSG_SIZE-1;
         msg[MSG_SIZE-1] = '\0';
     }
     va_end(ap);
     doLog(category, msg, len);
 }
References doLog(), format(), and m_logEnabled.
Referenced by addEdge(), buildPolyDetail(), canRemoveVertex(), delaunayHull(), mergeAndFilterLayerRegions(), mergeAndFilterRegions(), mergeRegionHoles(), rcAddSpan(), rcBuildCompactHeightfield(), rcBuildContours(), rcBuildDistanceField(), rcBuildHeightfieldLayers(), rcBuildLayerRegions(), rcBuildPolyMesh(), rcBuildPolyMeshDetail(), rcBuildRegions(), rcBuildRegionsMonotone(), rcCopyPolyMesh(), rcErodeWalkableArea(), rcMedianFilterWalkableArea(), rcMergePolyMeshDetails(), rcMergePolyMeshes(), rcRasterizeTriangle(), rcRasterizeTriangles(), removeVertex(), and seedArrayWithPolyCenter().
resetLog()
void rcContext::resetLog () inline
Clears all log entries.
Definition at line 115 of file Recast.h.
 { if (m_logEnabled) doResetLog(); }
References doResetLog(), and m_logEnabled.
resetTimers()
void rcContext::resetTimers () inline
Clears all peformance timers. (Resets all to unused.)
Definition at line 127 of file Recast.h.
 { if (m_timerEnabled) doResetTimers(); }
References doResetTimers(), and m_timerEnabled.
startTimer()
void rcContext::startTimer (const rcTimerLabel label) inline
Starts the specified performance timer.
Parameters
label The category of the timer.
Definition at line 131 of file Recast.h.
 { if (m_timerEnabled) doStartTimer(label); }
References doStartTimer(), and m_timerEnabled.
Referenced by rcBuildContours(), rcBuildRegions(), and rcScopedTimer::rcScopedTimer().
stopTimer()
void rcContext::stopTimer (const rcTimerLabel label) inline
Stops the specified performance timer.
Parameters
label The category of the timer.
Definition at line 135 of file Recast.h.
 { if (m_timerEnabled) doStopTimer(label); }
References doStopTimer(), and m_timerEnabled.
Referenced by rcBuildContours(), rcBuildRegions(), and rcScopedTimer::~rcScopedTimer().
Member Data Documentation
m_logEnabled
bool rcContext::m_logEnabled protected
True if logging is enabled.
Definition at line 170 of file Recast.h.
Referenced by enableLog(), log(), and resetLog().
m_timerEnabled
bool rcContext::m_timerEnabled protected
True if the performance timers are enabled.
Definition at line 173 of file Recast.h.
Referenced by enableTimer(), getAccumulatedTime(), resetTimers(), startTimer(), and stopTimer().
The documentation for this class was generated from the following files:
deps/recastnavigation/Recast/Include/Recast.h
deps/recastnavigation/Recast/Source/Recast.cpp