Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/mutex_pool.h File Reference
mutex_pool.h File Reference
#include "jemalloc/internal/hash.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/witness.h"
Classes
struct mutex_pool_s
Macros
#define MUTEX_POOL_SIZE 256
Typedefs
typedef struct mutex_pool_s mutex_pool_t
Functions
bool mutex_pool_init (mutex_pool_t *pool, const char *name, witness_rank_t rank)
static malloc_mutex_t * mutex_pool_mutex (mutex_pool_t *pool, uintptr_t key)
static void mutex_pool_assert_not_held (tsdn_t *tsdn, mutex_pool_t *pool)
static void mutex_pool_lock (tsdn_t *tsdn, mutex_pool_t *pool, uintptr_t key)
static void mutex_pool_unlock (tsdn_t *tsdn, mutex_pool_t *pool, uintptr_t key)
static void mutex_pool_lock2 (tsdn_t *tsdn, mutex_pool_t *pool, uintptr_t key1, uintptr_t key2)
static void mutex_pool_unlock2 (tsdn_t *tsdn, mutex_pool_t *pool, uintptr_t key1, uintptr_t key2)
static void mutex_pool_assert_owner (tsdn_t *tsdn, mutex_pool_t *pool, uintptr_t key)
Macro Definition Documentation
MUTEX_POOL_SIZE
#define MUTEX_POOL_SIZE 256
Definition at line 9 of file mutex_pool.h.
Typedef Documentation
mutex_pool_t
typedef struct mutex_pool_s mutex_pool_t
Definition at line 1 of file mutex_pool.h.
Function Documentation
mutex_pool_assert_not_held()
static void mutex_pool_assert_not_held (tsdn_t * tsdn, mutex_pool_t * pool) inline static
Definition at line 27 of file mutex_pool.h.
{
     for (int i = 0; i < MUTEX_POOL_SIZE; i++) {
         malloc_mutex_assert_not_owner(tsdn, &pool->mutexes[i]);
     }
 }
References malloc_mutex_assert_not_owner(), MUTEX_POOL_SIZE, and mutex_pool_s::mutexes.
Referenced by mutex_pool_lock(), mutex_pool_lock2(), mutex_pool_unlock(), and mutex_pool_unlock2().
mutex_pool_assert_owner()
static void mutex_pool_assert_owner (tsdn_t * tsdn, mutex_pool_t * pool, uintptr_t key) inline static
Definition at line 90 of file mutex_pool.h.
{
     malloc_mutex_assert_owner(tsdn, mutex_pool_mutex(pool, key));
 }
References malloc_mutex_assert_owner(), and mutex_pool_mutex().
mutex_pool_init()
bool mutex_pool_init (mutex_pool_t * pool, const char * name, witness_rank_t rank)
Definition at line 10 of file mutex_pool.c.
{
     for (int i = 0; i < MUTEX_POOL_SIZE; ++i) {
         if (malloc_mutex_init(&pool->mutexes[i], name, rank,
             malloc_mutex_address_ordered)) {
             return true;
         }
     }
     return false;
 }
References malloc_mutex_address_ordered, malloc_mutex_init, MUTEX_POOL_SIZE, and mutex_pool_s::mutexes.
mutex_pool_lock()
static void mutex_pool_lock (tsdn_t * tsdn, mutex_pool_t * pool, uintptr_t key) inline static
Definition at line 41 of file mutex_pool.h.
{
     mutex_pool_assert_not_held(tsdn, pool);
     malloc_mutex_t *mutex = mutex_pool_mutex(pool, key);
     malloc_mutex_lock(tsdn, mutex);
 }
References malloc_mutex_lock(), mutex_pool_assert_not_held(), and mutex_pool_mutex().
Referenced by extent_lock().
mutex_pool_lock2()
static void mutex_pool_lock2 (tsdn_t * tsdn, mutex_pool_t * pool, uintptr_t key1, uintptr_t key2) inline static
Definition at line 57 of file mutex_pool.h.
                     {
     mutex_pool_assert_not_held(tsdn, pool);
     malloc_mutex_t *mutex1 = mutex_pool_mutex(pool, key1);
     malloc_mutex_t *mutex2 = mutex_pool_mutex(pool, key2);
     if ((uintptr_t)mutex1 < (uintptr_t)mutex2) {
         malloc_mutex_lock(tsdn, mutex1);
         malloc_mutex_lock(tsdn, mutex2);
     } else if ((uintptr_t)mutex1 == (uintptr_t)mutex2) {
         malloc_mutex_lock(tsdn, mutex1);
     } else {
         malloc_mutex_lock(tsdn, mutex2);
         malloc_mutex_lock(tsdn, mutex1);
     }
 }
References malloc_mutex_lock(), mutex_pool_assert_not_held(), and mutex_pool_mutex().
Referenced by extent_lock2().
mutex_pool_mutex()
static malloc_mutex_t* mutex_pool_mutex (mutex_pool_t * pool, uintptr_t key) inline static
Definition at line 20 of file mutex_pool.h.
{
     size_t hash_result[2];
     hash(&key, sizeof(key), 0xd50dcc1b, hash_result);
     return &pool->mutexes[hash_result[0] % MUTEX_POOL_SIZE];
 }
References hash(), MUTEX_POOL_SIZE, and mutex_pool_s::mutexes.
Referenced by mutex_pool_assert_owner(), mutex_pool_lock(), mutex_pool_lock2(), mutex_pool_unlock(), and mutex_pool_unlock2().
mutex_pool_unlock()
static void mutex_pool_unlock (tsdn_t * tsdn, mutex_pool_t * pool, uintptr_t key) inline static
Definition at line 49 of file mutex_pool.h.
{
     malloc_mutex_t *mutex = mutex_pool_mutex(pool, key);
     malloc_mutex_unlock(tsdn, mutex);
     mutex_pool_assert_not_held(tsdn, pool);
 }
References malloc_mutex_unlock(), mutex_pool_assert_not_held(), and mutex_pool_mutex().
Referenced by extent_unlock().
mutex_pool_unlock2()
static void mutex_pool_unlock2 (tsdn_t * tsdn, mutex_pool_t * pool, uintptr_t key1, uintptr_t key2) inline static
Definition at line 75 of file mutex_pool.h.
                     {
     malloc_mutex_t *mutex1 = mutex_pool_mutex(pool, key1);
     malloc_mutex_t *mutex2 = mutex_pool_mutex(pool, key2);
     if (mutex1 == mutex2) {
         malloc_mutex_unlock(tsdn, mutex1);
     } else {
         malloc_mutex_unlock(tsdn, mutex1);
         malloc_mutex_unlock(tsdn, mutex2);
     }
     mutex_pool_assert_not_held(tsdn, pool);
 }
References malloc_mutex_unlock(), mutex_pool_assert_not_held(), and mutex_pool_mutex().
Referenced by extent_unlock2().