Azerotcore-wotlk: npc_scarlet_guard::npc_scarlet_guardAI Struct Reference
npc_scarlet_guard::npc_scarlet_guardAI Struct Reference
Public Member Functions
npc_scarlet_guardAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
Public Member Functions inherited from SmartAI
~SmartAI () override
SmartAI (Creature *c)
void StartPath (bool run=false, uint32 path=0, bool repeat=false, Unit *invoker=nullptr)
bool LoadPath (uint32 entry)
void PausePath (uint32 delay, bool forced=false)
void StopPath (uint32 DespawnTime=0, uint32 quest=0, bool fail=false)
void EndPath (bool fail=false)
void ResumePath ()
WayPoint * GetNextWayPoint ()
void GenerateWayPointArray (Movement::PointsArray *points)
bool HasEscortState (uint32 uiEscortState)
void AddEscortState (uint32 uiEscortState)
bool IsEscorted () override
void RemoveEscortState (uint32 uiEscortState)
void SetAutoAttack (bool on)
void SetCombatMove (bool on)
bool CanCombatMove ()
void SetFollow (Unit *target, float dist=0.0f, float angle=0.0f, uint32 credit=0, uint32 end=0, uint32 creditType=0, bool aliveState=true)
void StopFollow (bool complete)
void SetScript9 (SmartScriptHolder &e, uint32 entry, Unit *invoker)
SmartScript * GetScript ()
bool IsEscortInvokerInRange ()
void JustRespawned () override
void JustReachedHome () override
void EnterCombat (Unit *enemy) override
void EnterEvadeMode () override
void JustDied (Unit *killer) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *creature) override
void AttackStart (Unit *who) override
void SpellHit (Unit *unit, const SpellInfo *spellInfo) override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void DamageTaken (Unit *done_by, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
void HealReceived (Unit *doneBy, uint32 &addhealth) override
void UpdateAI (uint32 diff) override
void ReceiveEmote (Player *player, uint32 textEmote) override
void MovementInform (uint32 MovementType, uint32 Data) override
void IsSummonedBy (Unit *summoner) override
void DamageDealt (Unit *doneTo, uint32 &damage, DamageEffectType damagetyp) override
void SummonedCreatureDespawn (Creature *unit) override
void CorpseRemoved (uint32 &respawnDelay) override
== Triggered Actions Requested ==================
void UpdateAIWhileCharmed (const uint32 diff)
void PassengerBoarded (Unit *who, int8 seatId, bool apply) override
== Fields =======================================
void InitializeAI () override
void OnCharmed (bool apply) override
bool CanAIAttack (const Unit *who) const override
void DoAction (int32 param=0) override
uint32 GetData (uint32 id=0) const override
void SetData (uint32 id, uint32 value) override
void SetGUID (ObjectGuid guid, int32 id=0) override
ObjectGuid GetGUID (int32 id=0) const override
void MovepointReached (uint32 id)
void SetRun (bool run=true)
void SetFly (bool fly=true)
void SetSwim (bool swim=true)
void SetInvincibilityHpLevel (uint32 level)
void sGossipHello (Player *player) override
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
void sGossipSelectCode (Player *player, uint32 sender, uint32 action, const char *code) override
void sQuestAccept (Player *player, Quest const *quest) override
void sQuestReward (Player *player, Quest const *quest, uint32 opt) override
void sOnGameEvent (bool start, uint16 eventId) override
void SetDespawnTime (uint32 t)
void StartDespawn ()
void OnSpellClick (Unit *clicker, bool &result) override
void SetWPPauseTimer (uint32 time)
void SetForcedCombatMove (float dist)
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
Private Attributes
bool SayAshbringer = false
Additional Inherited Members
Static Public Member Functions inherited from SmartAI
static int32 Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from SmartAI
uint32 mEscortQuestID
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 203 of file instance_scarlet_monastery.cpp.
Constructor & Destructor Documentation
npc_scarlet_guardAI()
npc_scarlet_guard::npc_scarlet_guardAI::npc_scarlet_guardAI (Creature * creature) inline
Definition at line 205 of file instance_scarlet_monastery.cpp.
 : SmartAI(creature) { }
Member Function Documentation
MoveInLineOfSight()
void npc_scarlet_guard::npc_scarlet_guardAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from SmartAI.
Definition at line 212 of file instance_scarlet_monastery.cpp.
         {
             if (who && who->GetDistance2d(me) < 12.0f)
             {
                 if (Player* player = who->ToPlayer())
                 {
                     if (player->HasAura(AURA_ASHBRINGER) && !SayAshbringer)
                     {
                         Talk(SAY_WELCOME);
                         me->SetFaction(FACTION_FRIENDLY);
                         me->SetSheath(SHEATH_STATE_UNARMED);
                         me->SetFacingToObject(player);
                         me->SetStandState(UNIT_STAND_STATE_KNEEL);
                         me->AddAura(SPELL_AURA_MOD_ROOT, me);
                         me->CastSpell(me, SPELL_AURA_MOD_ROOT, true);
                         SayAshbringer = true;
                     }
                 }
             }
             SmartAI::MoveInLineOfSight(who);
         }
References Unit::AddAura(), AURA_ASHBRINGER, Unit::CastSpell(), FACTION_FRIENDLY, WorldObject::GetDistance2d(), CreatureAI::me, SmartAI::MoveInLineOfSight(), SAY_WELCOME, SayAshbringer, Unit::SetFacingToObject(), Unit::SetFaction(), Unit::SetSheath(), Unit::SetStandState(), SHEATH_STATE_UNARMED, SPELL_AURA_MOD_ROOT, CreatureAI::Talk(), Object::ToPlayer(), and UNIT_STAND_STATE_KNEEL.
Reset()
void npc_scarlet_guard::npc_scarlet_guardAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 207 of file instance_scarlet_monastery.cpp.
         {
             SayAshbringer = false;
         }
References SayAshbringer.
Member Data Documentation
SayAshbringer
bool npc_scarlet_guard::npc_scarlet_guardAI::SayAshbringer = false private
Definition at line 235 of file instance_scarlet_monastery.cpp.
Referenced by MoveInLineOfSight(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp