Azerotcore-wotlk: at_thaddius_entrance Class Reference
at_thaddius_entrance Class Reference
Public Member Functions
at_thaddius_entrance ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 746 of file boss_thaddius.cpp.
Constructor & Destructor Documentation
at_thaddius_entrance()
at_thaddius_entrance::at_thaddius_entrance () inline
Definition at line 749 of file boss_thaddius.cpp.
 : AreaTriggerScript("at_thaddius_entrance") { }
Member Function Documentation
OnTrigger()
bool at_thaddius_entrance::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 751 of file boss_thaddius.cpp.
     {
         InstanceScript* instance = player->GetInstanceScript();
         if (!instance || instance->GetData(DATA_HAD_THADDIUS_GREET) || instance->GetBossState(BOSS_THADDIUS) == DONE)
             return true;
         if (Creature* thaddius = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_THADDIUS_BOSS)))
         {
             thaddius->AI()->Talk(SAY_GREET);
         }
         instance->SetData(DATA_HAD_THADDIUS_GREET, 1);
         return true;
     }
References BOSS_THADDIUS, DATA_HAD_THADDIUS_GREET, DATA_THADDIUS_BOSS, DONE, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), SAY_GREET, and ZoneScript::SetData().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp