Azerotcore-wotlk: deps/mysqllite/include/my_global.h File Reference
my_global.h File Reference
#include <my_config.h>
#include <pthread.h>
#include <stdio.h>
#include <stdarg.h>
#include <math.h>
#include <time.h>
#include <errno.h>
#include <assert.h>
#include <my_compiler.h>
#include <my_dbug.h>
Macros
#define INNODB_COMPATIBILITY_HOOKS
#define C_MODE_START
#define C_MODE_END
#define IF_WIN(A, B) B
#define IF_PURIFY(A, B) B
#define HAVE_REPLICATION
#define HAVE_EXTERNAL_CLIENT
#define __builtin_expect(x, expected_value) (x)
#define likely(x) __builtin_expect((x),1)
#define unlikely(x) __builtin_expect((x),0)
#define __EXTENSIONS__ 1 /* We want some extension */
#define __STDC_EXT__ 1 /* To get large file support on hpux */
#define _POSIX_PTHREAD_SEMANTICS /* We want posix threads */
#define _REENTRANT 1 /* Some thread libraries require this */
#define _THREAD_SAFE /* Required for OSF1 */
#define compile_time_assert(X) do { } while(0)
#define QUOTE_ARG(x) #x /* Quote argument (before cpp) */
#define STRINGIFY_ARG(x) QUOTE_ARG(x) /* Quote argument, after cpp */
#define SIGNAL_HANDLER_RESET_ON_DELIVERY
#define LINT_INIT(var)
#define SO_EXT ".so"
#define UNINIT_VAR(x) x= 0
#define HAVE_UINT
#define swap_variables(t, a, b) { t dummy; dummy= a; a= b; b= dummy; }
#define test(a) ((a) ? 1 : 0)
#define set_if_bigger(a, b) do { if ((a) < (b)) (a)=(b); } while(0)
#define set_if_smaller(a, b) do { if ((a) > (b)) (a)=(b); } while(0)
#define test_all_bits(a, b) (((a) & (b)) == (b))
#define array_elements(A) ((uint) (sizeof(A)/sizeof(A[0])))
#define TRUE (1) /* Logical true */
#define FALSE (0) /* Logical false */
#define INVALID_SOCKET -1
#define sig_handler RETSIGTYPE
#define qsort_t RETQSORTTYPE /* Broken GCC cant handle typedef !!!! */
#define SOCKOPT_OPTLEN_TYPE size_socket
#define O_SHARE 0 /* Flag to my_open for shared files */
#define O_BINARY 0 /* Flag to my_open for binary files */
#define FILE_BINARY O_BINARY /* Flag to my_fopen for binary streams */
#define O_TEMPORARY 0
#define O_SHORT_LIVED 0
#define O_NOFOLLOW 0
#define FN_LEN 256 /* Max file name len */
#define FN_HEADLEN 253 /* Max length of filepart of file name */
#define FN_EXTLEN 20 /* Max length of extension (part of FN_LEN) */
#define FN_REFLEN 512 /* Max length of full path-name */
#define FN_EXTCHAR '.'
#define FN_HOMELIB '~' /* ~/ is used as abbrev for home dir */
#define FN_CURLIB '.' /* ./ is used as abbrev for current dir */
#define FN_PARENTDIR ".." /* Parent directory; Must be a string */
#define FN_LIBCHAR '/'
#define FN_LIBCHAR2 '/'
#define FN_DIRSEP "/" /* Valid directory separators */
#define FN_ROOTDIR "/"
#define MY_FILE_MIN 0
#define MY_NFILE 64
#define OS_FILE_LIMIT UINT_MAX
#define IO_SIZE 4096
#define MALLOC_OVERHEAD 8
#define ONCE_ALLOC_INIT (uint) (4096-MALLOC_OVERHEAD)
#define RECORD_CACHE_SIZE (uint) (64*1024-MALLOC_OVERHEAD)
#define KEY_CACHE_SIZE (uint) (8*1024*1024)
#define KEY_CACHE_BLOCK_SIZE (uint) 1024
#define closesocket(A) close(A)
#define ulonglong2double(A) ((double) (ulonglong) (A))
#define my_off_t2double(A) ((double) (my_off_t) (A))
#define double2ulonglong(A) ((ulonglong) (double) (A))
#define offsetof(TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
#define ulong_to_double(X) ((double) (ulong) (X))
#define strtok_r(A, B, C) strtok((A),(B))
#define INT_MIN64 (~0x7FFFFFFFFFFFFFFFLL)
#define INT_MAX64 0x7FFFFFFFFFFFFFFFLL
#define INT_MIN32 (~0x7FFFFFFFL)
#define INT_MAX32 0x7FFFFFFFL
#define UINT_MAX32 0xFFFFFFFFL
#define INT_MIN24 (~0x007FFFFF)
#define INT_MAX24 0x007FFFFF
#define UINT_MAX24 0x00FFFFFF
#define INT_MIN16 (~0x7FFF)
#define INT_MAX16 0x7FFF
#define UINT_MAX16 0xFFFF
#define INT_MIN8 (~0x7F)
#define INT_MAX8 0x7F
#define UINT_MAX8 0xFF
#define DBL_MIN 4.94065645841246544e-324
#define FLT_MIN ((float)1.40129846432481707e-45)
#define DBL_MAX 1.79769313486231470e+308
#define FLT_MAX ((float)3.40282346638528860e+38)
#define SIZE_T_MAX (~((size_t) 0))
#define finite(x) (1.0 / fabs(x) > 0.0)
#define isfinite(x) (1.0 / fabs(x) > 0.0)
#define isnan(x) ((x) != (x))
#define my_isinf(X) (!finite(X) && !isnan(X))
#define M_PI 3.14159265358979323846
#define M_E 2.7182818284590452354
#define M_LN2 0.69314718055994530942
#define MY_ALIGN(A, L) (((A) + (L) - 1) & ~((L) - 1))
#define ALIGN_SIZE(A) MY_ALIGN((A),sizeof(double))
#define ADD_TO_PTR(ptr, size, type) (type) ((uchar*) (ptr)+size)
#define PTR_BYTE_DIFF(A, B) (my_ptrdiff_t) ((uchar*) (A) - (uchar*) (B))
#define my_offsetof(TYPE, MEMBER) ((size_t)((char *)&(((TYPE *)0x10)->MEMBER) - (char*)0x10))
#define NullS (char *) 0
#define STDCALL
#define MY_ERRPTR ((void*)(intptr)1)
#define MY_FILEPOS_ERROR (~(my_off_t) 0)
#define socket_errno errno
#define closesocket(A) close(A)
#define SOCKET_EINTR EINTR
#define SOCKET_EAGAIN EAGAIN
#define SOCKET_ETIMEDOUT SOCKET_EINTR
#define SOCKET_EWOULDBLOCK EWOULDBLOCK
#define SOCKET_EADDRINUSE EADDRINUSE
#define SOCKET_ENFILE ENFILE
#define SOCKET_EMFILE EMFILE
#define MYF(v) (myf) (v)
#define LL(A) A ## L
#define ULL(A) A ## UL
#define reg1 register
#define reg2 register
#define reg3 register
#define reg4 register
#define reg5 register
#define reg6 register
#define reg7 register
#define reg8 register
#define reg9 register
#define reg10 register
#define reg11 register
#define reg12 register
#define reg13 register
#define reg14 register
#define reg15 register
#define reg16 register
#define YESNO(X) ((X) ? "yes" : "no")
#define MY_HOW_OFTEN_TO_ALARM 2 /* How often we want info on screen */
#define MY_HOW_OFTEN_TO_WRITE 1000 /* How often we want info on screen */
#define sint2korr(A)
#define sint3korr(A)
#define sint4korr(A)
#define sint8korr(A) (longlong) uint8korr(A)
#define uint2korr(A)
#define uint3korr(A)
#define uint4korr(A)
#define uint5korr(A)
#define uint6korr(A)
#define uint8korr(A)
#define int2store(T, A)
#define int3store(T, A)
#define int4store(T, A)
#define int5store(T, A)
#define int6store(T, A)
#define int8store(T, A)
#define float4get(V, M) memcpy(&V, (M), sizeof(float))
#define float4store(V, M) memcpy(V, (&M), sizeof(float))
#define float8get(V, M) doubleget((V),(M))
#define float8store(V, M) doublestore((V),(M))
#define int4net(A)
#define ushortget(V, M) do { V = uint2korr(M); } while(0)
#define shortget(V, M) do { V = sint2korr(M); } while(0)
#define longget(V, M) do { V = sint4korr(M); } while(0)
#define ulongget(V, M) do { V = uint4korr(M); } while(0)
#define shortstore(T, V) int2store(T,V)
#define longstore(T, V) int4store(T,V)
#define floatstore(T, V) memcpy((T), (void *) (&V), sizeof(float))
#define floatget(V, M) memcpy(&V, (M), sizeof(float))
#define doubleget(V, M) memcpy(&V, (M), sizeof(double))
#define doublestore(T, V) memcpy((T), (void *) &V, sizeof(double))
#define longlongget(V, M) memcpy(&V, (M), sizeof(ulonglong))
#define longlongstore(T, V) memcpy((T), &V, sizeof(ulonglong))
#define MYSQL_UNIVERSAL_CLIENT_CHARSET MYSQL_DEFAULT_CHARSET_NAME
#define dlerror() "No support for dynamic loading (static build?)"
#define MY_INT32_NUM_DECIMAL_DIGITS 11
#define MY_INT64_NUM_DECIMAL_DIGITS 21
#define max(a, b) ((a) > (b) ? (a) : (b))
#define min(a, b) ((a) < (b) ? (a) : (b))
#define bool In_C_you_should_use_my_bool_instead()
#define __func__ "<unknown>"
#define MAX_EXACT_INTEGER ((1LL << DBL_MANT_DIG) - 1)
#define MYSQL_PLUGIN_IMPORT
Typedefs
typedef unsigned int uint
typedef unsigned short ushort
typedef int File
typedef int my_socket
typedef uint puchar
typedef int pbool
typedef int pshort
typedef double pfloat
typedef int(* qsort_cmp2) (void *, const void *, const void *)
typedef SOCKET_SIZE_TYPE size_socket
typedef long long my_ptrdiff_t
typedef unsigned char uchar
typedef signed char int8
typedef unsigned char uint8
typedef short int16
typedef unsigned short uint16
typedef unsigned long ulong
typedef unsigned long ulonglong
typedef long longlong
typedef longlong int64
typedef ulonglong uint64
typedef unsigned long long my_ulonglong
typedef int intptr
typedef off_t os_off_t
typedef unsigned long my_off_t
typedef ulonglong table_map
typedef ulong nesting_map
typedef int myf
typedef char my_bool
Functions
static double rint (double x)
Variables
C_MODE_START typedef void(* sig_return)()
C_MODE_END typedef int pchar
C_MODE_START typedef int(* qsort_cmp)(const void *, const void *)
Macro Definition Documentation
__builtin_expect
#define __builtin_expect (x, expected_value) (x)
Definition at line 195 of file my_global.h.
__EXTENSIONS__
#define __EXTENSIONS__ 1 /* We want some extension */
Definition at line 220 of file my_global.h.
__func__
#define __func__ "<unknown>"
Definition at line 1407 of file my_global.h.
__STDC_EXT__
#define __STDC_EXT__ 1 /* To get large file support on hpux */
Definition at line 222 of file my_global.h.
_POSIX_PTHREAD_SEMANTICS
#define _POSIX_PTHREAD_SEMANTICS /* We want posix threads */
Definition at line 259 of file my_global.h.
_REENTRANT
#define _REENTRANT 1 /* Some thread libraries require this */
Definition at line 263 of file my_global.h.
_THREAD_SAFE
#define _THREAD_SAFE /* Required for OSF1 */
Definition at line 266 of file my_global.h.
ADD_TO_PTR
#define ADD_TO_PTR (ptr, size, type) (type) ((uchar*) (ptr)+size)
Definition at line 841 of file my_global.h.
ALIGN_SIZE
#define ALIGN_SIZE (A) MY_ALIGN((A),sizeof(double))
Definition at line 839 of file my_global.h.
array_elements
#define array_elements (A) ((uint) (sizeof(A)/sizeof(A[0])))
Definition at line 484 of file my_global.h.
bool
#define bool In_C_you_should_use_my_bool_instead()
Definition at line 1399 of file my_global.h.
C_MODE_END
#define C_MODE_END
Definition at line 68 of file my_global.h.
C_MODE_START
#define C_MODE_START
Definition at line 67 of file my_global.h.
closesocket [1/2]
#define closesocket (A) close(A)
Definition at line 981 of file my_global.h.
closesocket [2/2]
#define closesocket (A) close(A)
Definition at line 981 of file my_global.h.
compile_time_assert
#define compile_time_assert (X) do { } while(0)
Definition at line 391 of file my_global.h.
DBL_MAX
#define DBL_MAX 1.79769313486231470e+308
Definition at line 782 of file my_global.h.
DBL_MIN
#define DBL_MIN 4.94065645841246544e-324
Definition at line 778 of file my_global.h.
dlerror
#define dlerror () "No support for dynamic loading (static build?)"
Definition at line 1366 of file my_global.h.
double2ulonglong
#define double2ulonglong (A) ((ulonglong) (double) (A))
Definition at line 720 of file my_global.h.
doubleget
#define doubleget (V, M) memcpy(&V, (M), sizeof(double))
Definition at line 1329 of file my_global.h.
doublestore
#define doublestore (T, V) memcpy((T), (void *) &V, sizeof(double))
Definition at line 1330 of file my_global.h.
FALSE
#define FALSE (0) /* Logical false */
Definition at line 489 of file my_global.h.
FILE_BINARY
#define FILE_BINARY O_BINARY /* Flag to my_fopen for binary streams */
Definition at line 567 of file my_global.h.
finite
#define finite (x) (1.0 / fabs(x) > 0.0)
Definition at line 792 of file my_global.h.
float4get
#define float4get (V, M) memcpy(&V, (M), sizeof(float))
Definition at line 1238 of file my_global.h.
float4store
#define float4store (V, M) memcpy(V, (&M), sizeof(float))
Definition at line 1239 of file my_global.h.
float8get
#define float8get (V, M) doubleget((V),(M))
Definition at line 1263 of file my_global.h.
float8store
#define float8store (V, M) doublestore((V),(M))
Definition at line 1264 of file my_global.h.
floatget
#define floatget (V, M) memcpy(&V, (M), sizeof(float))
Definition at line 1326 of file my_global.h.
floatstore
#define floatstore (T, V) memcpy((T), (void *) (&V), sizeof(float))
Definition at line 1325 of file my_global.h.
FLT_MAX
#define FLT_MAX ((float)3.40282346638528860e+38)
Definition at line 783 of file my_global.h.
FLT_MIN
#define FLT_MIN ((float)1.40129846432481707e-45)
Definition at line 779 of file my_global.h.
FN_CURLIB
#define FN_CURLIB '.' /* ./ is used as abbrev for current dir */
Definition at line 601 of file my_global.h.
FN_DIRSEP
#define FN_DIRSEP "/" /* Valid directory separators */
Definition at line 615 of file my_global.h.
FN_EXTCHAR
#define FN_EXTCHAR '.'
Definition at line 599 of file my_global.h.
FN_EXTLEN
#define FN_EXTLEN 20 /* Max length of extension (part of FN_LEN) */
Definition at line 597 of file my_global.h.
FN_HEADLEN
#define FN_HEADLEN 253 /* Max length of filepart of file name */
Definition at line 596 of file my_global.h.
FN_HOMELIB
#define FN_HOMELIB '~' /* ~/ is used as abbrev for home dir */
Definition at line 600 of file my_global.h.
FN_LEN
#define FN_LEN 256 /* Max file name len */
Definition at line 595 of file my_global.h.
FN_LIBCHAR
#define FN_LIBCHAR '/'
Definition at line 613 of file my_global.h.
FN_LIBCHAR2
#define FN_LIBCHAR2 '/'
Definition at line 614 of file my_global.h.
FN_PARENTDIR
#define FN_PARENTDIR ".." /* Parent directory; Must be a string */
Definition at line 602 of file my_global.h.
FN_REFLEN
#define FN_REFLEN 512 /* Max length of full path-name */
Definition at line 598 of file my_global.h.
FN_ROOTDIR
#define FN_ROOTDIR "/"
Definition at line 616 of file my_global.h.
HAVE_EXTERNAL_CLIENT
#define HAVE_EXTERNAL_CLIENT
Definition at line 103 of file my_global.h.
HAVE_REPLICATION
#define HAVE_REPLICATION
Definition at line 102 of file my_global.h.
HAVE_UINT
#define HAVE_UINT
Definition at line 474 of file my_global.h.
IF_PURIFY
#define IF_PURIFY (A, B) B
Definition at line 92 of file my_global.h.
IF_WIN
#define IF_WIN (A, B) B
Definition at line 86 of file my_global.h.
INNODB_COMPATIBILITY_HOOKS
#define INNODB_COMPATIBILITY_HOOKS
Definition at line 35 of file my_global.h.
int2store
#define int2store (T, A)
Value:
                                  do { uint def_temp= (uint) (A) ;\
                                  *((uchar*) (T))=  (uchar)(def_temp); \
                                   *((uchar*) (T)+1)=(uchar)((def_temp >> 8)); \
                             } while(0)
Definition at line 1177 of file my_global.h.
int3store
#define int3store (T, A)
Value:
                                  do { /*lint -save -e734 */\
                                  *((uchar*)(T))=(uchar) ((A));\
                                  *((uchar*) (T)+1)=(uchar) (((A) >> 8));\
                                  *((uchar*)(T)+2)=(uchar) (((A) >> 16)); \
                                  /*lint -restore */} while(0)
Definition at line 1181 of file my_global.h.
int4net
#define int4net (A)
Value:
                  (int32) (((uint32) ((uchar) (A)[3]))        |\
                  (((uint32) ((uchar) (A)[2])) << 8)  |\
                  (((uint32) ((uchar) (A)[1])) << 16) |\
                  (((uint32) ((uchar) (A)[0])) << 24))
Definition at line 1273 of file my_global.h.
int4store
#define int4store (T, A)
Value:
                                  do { *((char *)(T))=(char) ((A));\
                                  *(((char *)(T))+1)=(char) (((A) >> 8));\
                                  *(((char *)(T))+2)=(char) (((A) >> 16));\
                                  *(((char *)(T))+3)=(char) (((A) >> 24)); } while(0)
Definition at line 1186 of file my_global.h.
int5store
#define int5store (T, A)
Value:
                                  do { *((char *)(T))=     (char)((A));  \
                                  *(((char *)(T))+1)= (char)(((A) >> 8)); \
                                  *(((char *)(T))+2)= (char)(((A) >> 16)); \
                                  *(((char *)(T))+3)= (char)(((A) >> 24)); \
                                  *(((char *)(T))+4)= (char)(((A) >> 32)); \
                        } while(0)
Definition at line 1190 of file my_global.h.
int6store
#define int6store (T, A)
Value:
                                  do { *((char *)(T))=     (char)((A)); \
                                  *(((char *)(T))+1)= (char)(((A) >> 8)); \
                                  *(((char *)(T))+2)= (char)(((A) >> 16)); \
                                  *(((char *)(T))+3)= (char)(((A) >> 24)); \
                                  *(((char *)(T))+4)= (char)(((A) >> 32)); \
                                  *(((char *)(T))+5)= (char)(((A) >> 40)); \
                                } while(0)
Definition at line 1196 of file my_global.h.
int8store
#define int8store (T, A)
Value:
                                  do { uint def_temp= (uint) (A), def_temp2= (uint) ((A) >> 32); \
                                  int4store((T),def_temp); \
                                  int4store((T+4),def_temp2); } while(0)
Definition at line 1203 of file my_global.h.
INT_MAX16
#define INT_MAX16 0x7FFF
Definition at line 770 of file my_global.h.
INT_MAX24
#define INT_MAX24 0x007FFFFF
Definition at line 767 of file my_global.h.
INT_MAX32
#define INT_MAX32 0x7FFFFFFFL
Definition at line 764 of file my_global.h.
INT_MAX64
#define INT_MAX64 0x7FFFFFFFFFFFFFFFLL
Definition at line 762 of file my_global.h.
INT_MAX8
#define INT_MAX8 0x7F
Definition at line 773 of file my_global.h.
INT_MIN16
#define INT_MIN16 (~0x7FFF)
Definition at line 769 of file my_global.h.
INT_MIN24
#define INT_MIN24 (~0x007FFFFF)
Definition at line 766 of file my_global.h.
INT_MIN32
#define INT_MIN32 (~0x7FFFFFFFL)
Definition at line 763 of file my_global.h.
INT_MIN64
#define INT_MIN64 (~0x7FFFFFFFFFFFFFFFLL)
Definition at line 761 of file my_global.h.
INT_MIN8
#define INT_MIN8 (~0x7F)
Definition at line 772 of file my_global.h.
INVALID_SOCKET
#define INVALID_SOCKET -1
Definition at line 525 of file my_global.h.
IO_SIZE
#define IO_SIZE 4096
Definition at line 662 of file my_global.h.
isfinite
#define isfinite (x) (1.0 / fabs(x) > 0.0)
Definition at line 794 of file my_global.h.
isnan
#define isnan (x) ((x) != (x))
Definition at line 797 of file my_global.h.
KEY_CACHE_BLOCK_SIZE
#define KEY_CACHE_BLOCK_SIZE (uint) 1024
Definition at line 676 of file my_global.h.
KEY_CACHE_SIZE
#define KEY_CACHE_SIZE (uint) (8*1024*1024)
Definition at line 674 of file my_global.h.
likely
#define likely (x) __builtin_expect((x),1)
Definition at line 198 of file my_global.h.
LINT_INIT
#define LINT_INIT (var)
Definition at line 445 of file my_global.h.
LL
#define LL (A) A ## L
Definition at line 1001 of file my_global.h.
longget
#define longget (V, M) do { V = sint4korr(M); } while(0)
Definition at line 1320 of file my_global.h.
longlongget
#define longlongget (V, M) memcpy(&V, (M), sizeof(ulonglong))
Definition at line 1332 of file my_global.h.
longlongstore
#define longlongstore (T, V) memcpy((T), &V, sizeof(ulonglong))
Definition at line 1333 of file my_global.h.
longstore
#define longstore (T, V) int4store(T,V)
Definition at line 1323 of file my_global.h.
M_E
#define M_E 2.7182818284590452354
Definition at line 822 of file my_global.h.
M_LN2
#define M_LN2 0.69314718055994530942
Definition at line 825 of file my_global.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 819 of file my_global.h.
MALLOC_OVERHEAD
#define MALLOC_OVERHEAD 8
Definition at line 667 of file my_global.h.
max
#define max (a, b) ((a) > (b) ? (a) : (b))
Definition at line 1386 of file my_global.h.
MAX_EXACT_INTEGER
#define MAX_EXACT_INTEGER ((1LL << DBL_MANT_DIG) - 1)
All integers up to this number can be represented exactly as double precision values (DBL_MANT_DIG == 53 for IEEE 754 hardware).
Definition at line 1426 of file my_global.h.
min
#define min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 1387 of file my_global.h.
MY_ALIGN
#define MY_ALIGN (A, L) (((A) + (L) - 1) & ~((L) - 1))
Definition at line 838 of file my_global.h.
MY_ERRPTR
#define MY_ERRPTR ((void*)(intptr)1)
Definition at line 949 of file my_global.h.
MY_FILE_MIN
#define MY_FILE_MIN 0
Definition at line 634 of file my_global.h.
MY_FILEPOS_ERROR
#define MY_FILEPOS_ERROR (~(my_off_t) 0)
Definition at line 962 of file my_global.h.
MY_HOW_OFTEN_TO_ALARM
#define MY_HOW_OFTEN_TO_ALARM 2 /* How often we want info on screen */
Definition at line 1041 of file my_global.h.
MY_HOW_OFTEN_TO_WRITE
#define MY_HOW_OFTEN_TO_WRITE 1000 /* How often we want info on screen */
Definition at line 1042 of file my_global.h.
MY_INT32_NUM_DECIMAL_DIGITS
#define MY_INT32_NUM_DECIMAL_DIGITS 11
Definition at line 1379 of file my_global.h.
MY_INT64_NUM_DECIMAL_DIGITS
#define MY_INT64_NUM_DECIMAL_DIGITS 21
Definition at line 1382 of file my_global.h.
my_isinf
#define my_isinf (X) (!finite(X) && !isnan(X))
Definition at line 814 of file my_global.h.
MY_NFILE
#define MY_NFILE 64
Definition at line 650 of file my_global.h.
my_off_t2double
#define my_off_t2double (A) ((double) (my_off_t) (A))
Definition at line 717 of file my_global.h.
my_offsetof
#define my_offsetof (TYPE, MEMBER) ((size_t)((char *)&(((TYPE *)0x10)->MEMBER) - (char*)0x10))
Definition at line 856 of file my_global.h.
MYF
#define MYF (v) (myf) (v)
Definition at line 995 of file my_global.h.
MYSQL_PLUGIN_IMPORT
#define MYSQL_PLUGIN_IMPORT
Definition at line 1465 of file my_global.h.
MYSQL_UNIVERSAL_CLIENT_CHARSET
#define MYSQL_UNIVERSAL_CLIENT_CHARSET MYSQL_DEFAULT_CHARSET_NAME
Definition at line 1340 of file my_global.h.
NullS
#define NullS (char *) 0
Definition at line 859 of file my_global.h.
O_BINARY
#define O_BINARY 0 /* Flag to my_open for binary files */
Definition at line 564 of file my_global.h.
O_NOFOLLOW
#define O_NOFOLLOW 0
Definition at line 582 of file my_global.h.
O_SHARE
#define O_SHARE 0 /* Flag to my_open for shared files */
Definition at line 562 of file my_global.h.
O_SHORT_LIVED
#define O_SHORT_LIVED 0
Definition at line 579 of file my_global.h.
O_TEMPORARY
#define O_TEMPORARY 0
Definition at line 576 of file my_global.h.
offsetof
#define offsetof (TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
Definition at line 724 of file my_global.h.
ONCE_ALLOC_INIT
#define ONCE_ALLOC_INIT (uint) (4096-MALLOC_OVERHEAD)
Definition at line 670 of file my_global.h.
OS_FILE_LIMIT
#define OS_FILE_LIMIT UINT_MAX
Definition at line 654 of file my_global.h.
PTR_BYTE_DIFF
#define PTR_BYTE_DIFF (A, B) (my_ptrdiff_t) ((uchar*) (A) - (uchar*) (B))
Definition at line 842 of file my_global.h.
qsort_t
#define qsort_t RETQSORTTYPE /* Broken GCC cant handle typedef !!!! */
Definition at line 549 of file my_global.h.
QUOTE_ARG
#define QUOTE_ARG (x) #x /* Quote argument (before cpp) */
Definition at line 421 of file my_global.h.
RECORD_CACHE_SIZE
#define RECORD_CACHE_SIZE (uint) (64*1024-MALLOC_OVERHEAD)
Definition at line 672 of file my_global.h.
reg1
#define reg1 register
Definition at line 1018 of file my_global.h.
reg10
#define reg10 register
Definition at line 1027 of file my_global.h.
reg11
#define reg11 register
Definition at line 1028 of file my_global.h.
reg12
#define reg12 register
Definition at line 1029 of file my_global.h.
reg13
#define reg13 register
Definition at line 1030 of file my_global.h.
reg14
#define reg14 register
Definition at line 1031 of file my_global.h.
reg15
#define reg15 register
Definition at line 1032 of file my_global.h.
reg16
#define reg16 register
Definition at line 1033 of file my_global.h.
reg2
#define reg2 register
Definition at line 1019 of file my_global.h.
reg3
#define reg3 register
Definition at line 1020 of file my_global.h.
reg4
#define reg4 register
Definition at line 1021 of file my_global.h.
reg5
#define reg5 register
Definition at line 1022 of file my_global.h.
reg6
#define reg6 register
Definition at line 1023 of file my_global.h.
reg7
#define reg7 register
Definition at line 1024 of file my_global.h.
reg8
#define reg8 register
Definition at line 1025 of file my_global.h.
reg9
#define reg9 register
Definition at line 1026 of file my_global.h.
set_if_bigger
#define set_if_bigger (a, b) do { if ((a) < (b)) (a)=(b); } while(0)
Definition at line 481 of file my_global.h.
set_if_smaller
#define set_if_smaller (a, b) do { if ((a) > (b)) (a)=(b); } while(0)
Definition at line 482 of file my_global.h.
shortget
#define shortget (V, M) do { V = sint2korr(M); } while(0)
Definition at line 1319 of file my_global.h.
shortstore
#define shortstore (T, V) int2store(T,V)
Definition at line 1322 of file my_global.h.
sig_handler
#define sig_handler RETSIGTYPE
Definition at line 528 of file my_global.h.
SIGNAL_HANDLER_RESET_ON_DELIVERY
#define SIGNAL_HANDLER_RESET_ON_DELIVERY
Definition at line 432 of file my_global.h.
sint2korr
#define sint2korr (A)
Value:
                 (int16) (((int16) ((uchar) (A)[0])) +\
                 ((int16) ((int16) (A)[1]) << 8))
Definition at line 1133 of file my_global.h.
sint3korr
#define sint3korr (A)
Value:
                  ((int32) ((((uchar) (A)[2]) & 128) ? \
                  (((uint32) 255L << 24) | \
                   (((uint32) (uchar) (A)[2]) << 16) |\
                   (((uint32) (uchar) (A)[1]) << 8) | \
                   ((uint32) (uchar) (A)[0])) : \
                  (((uint32) (uchar) (A)[2]) << 16) |\
                  (((uint32) (uchar) (A)[1]) << 8) | \
                  ((uint32) (uchar) (A)[0])))
Definition at line 1135 of file my_global.h.
sint4korr
#define sint4korr (A)
Value:
                (int32) (((int32) ((uchar) (A)[0])) +\
                (((int32) ((uchar) (A)[1]) << 8)) +\
                (((int32) ((uchar) (A)[2]) << 16)) +\
                (((int32) ((int16) (A)[3]) << 24)))
Definition at line 1143 of file my_global.h.
sint8korr
#define sint8korr (A) (longlong) uint8korr(A)
Definition at line 1147 of file my_global.h.
SIZE_T_MAX
#define SIZE_T_MAX (~((size_t) 0))
Definition at line 786 of file my_global.h.
SO_EXT
#define SO_EXT ".so"
Definition at line 454 of file my_global.h.
SOCKET_EADDRINUSE
#define SOCKET_EADDRINUSE EADDRINUSE
Definition at line 986 of file my_global.h.
SOCKET_EAGAIN
#define SOCKET_EAGAIN EAGAIN
Definition at line 983 of file my_global.h.
SOCKET_EINTR
#define SOCKET_EINTR EINTR
Definition at line 982 of file my_global.h.
SOCKET_EMFILE
#define SOCKET_EMFILE EMFILE
Definition at line 988 of file my_global.h.
SOCKET_ENFILE
#define SOCKET_ENFILE ENFILE
Definition at line 987 of file my_global.h.
socket_errno
#define socket_errno errno
Definition at line 980 of file my_global.h.
SOCKET_ETIMEDOUT
#define SOCKET_ETIMEDOUT SOCKET_EINTR
Definition at line 984 of file my_global.h.
SOCKET_EWOULDBLOCK
#define SOCKET_EWOULDBLOCK EWOULDBLOCK
Definition at line 985 of file my_global.h.
SOCKOPT_OPTLEN_TYPE
#define SOCKOPT_OPTLEN_TYPE size_socket
Definition at line 556 of file my_global.h.
STDCALL
#define STDCALL
Definition at line 868 of file my_global.h.
STRINGIFY_ARG
#define STRINGIFY_ARG (x) QUOTE_ARG(x) /* Quote argument, after cpp */
Definition at line 422 of file my_global.h.
strtok_r
#define strtok_r (A, B, C) strtok((A),(B))
Definition at line 733 of file my_global.h.
swap_variables
#define swap_variables (t, a, b) { t dummy; dummy= a; a= b; b= dummy; }
Definition at line 479 of file my_global.h.
test
#define test (a) ((a) ? 1 : 0)
Definition at line 480 of file my_global.h.
test_all_bits
#define test_all_bits (a, b) (((a) & (b)) == (b))
Definition at line 483 of file my_global.h.
TRUE
#define TRUE (1) /* Logical true */
Definition at line 488 of file my_global.h.
uint2korr
#define uint2korr (A)
Value:
                  (uint16) (((uint16) ((uchar) (A)[0])) +\
                  ((uint16) ((uchar) (A)[1]) << 8))
Definition at line 1148 of file my_global.h.
uint3korr
#define uint3korr (A)
Value:
                  (uint32) (((uint32) ((uchar) (A)[0])) +\
                  (((uint32) ((uchar) (A)[1])) << 8) +\
                  (((uint32) ((uchar) (A)[2])) << 16))
Definition at line 1150 of file my_global.h.
uint4korr
#define uint4korr (A)
Value:
                  (uint32) (((uint32) ((uchar) (A)[0])) +\
                  (((uint32) ((uchar) (A)[1])) << 8) +\
                  (((uint32) ((uchar) (A)[2])) << 16) +\
                  (((uint32) ((uchar) (A)[3])) << 24))
Definition at line 1153 of file my_global.h.
uint5korr
#define uint5korr (A)
Value:
                    ((ulonglong)(((uint32) ((uchar) (A)[0])) +\
                    (((uint32) ((uchar) (A)[1])) << 8) +\
                    (((uint32) ((uchar) (A)[2])) << 16) +\
                    (((uint32) ((uchar) (A)[3])) << 24)) +\
                    (((ulonglong) ((uchar) (A)[4])) << 32))
Definition at line 1157 of file my_global.h.
uint6korr
#define uint6korr (A)
Value:
                                     ((ulonglong)(((uint32)    ((uchar) (A)[0]))          + \
                                     (((uint32)    ((uchar) (A)[1])) << 8)   + \
                                     (((uint32)    ((uchar) (A)[2])) << 16)  + \
                                     (((uint32)    ((uchar) (A)[3])) << 24)) + \
                         (((ulonglong) ((uchar) (A)[4])) << 32) +       \
                         (((ulonglong) ((uchar) (A)[5])) << 40))
Definition at line 1162 of file my_global.h.
uint8korr
#define uint8korr (A)
Value:
                    ((ulonglong)(((uint32) ((uchar) (A)[0])) +\
                    (((uint32) ((uchar) (A)[1])) << 8) +\
                    (((uint32) ((uchar) (A)[2])) << 16) +\
                    (((uint32) ((uchar) (A)[3])) << 24)) +\
            (((ulonglong) (((uint32) ((uchar) (A)[4])) +\
                    (((uint32) ((uchar) (A)[5])) << 8) +\
                    (((uint32) ((uchar) (A)[6])) << 16) +\
                    (((uint32) ((uchar) (A)[7])) << 24))) <<\
                    32))
Definition at line 1168 of file my_global.h.
UINT_MAX16
#define UINT_MAX16 0xFFFF
Definition at line 771 of file my_global.h.
UINT_MAX24
#define UINT_MAX24 0x00FFFFFF
Definition at line 768 of file my_global.h.
UINT_MAX32
#define UINT_MAX32 0xFFFFFFFFL
Definition at line 765 of file my_global.h.
UINT_MAX8
#define UINT_MAX8 0xFF
Definition at line 774 of file my_global.h.
ULL
#define ULL (A) A ## UL
Definition at line 1009 of file my_global.h.
ulong_to_double
#define ulong_to_double (X) ((double) (ulong) (X))
Definition at line 726 of file my_global.h.
ulongget
#define ulongget (V, M) do { V = uint4korr(M); } while(0)
Definition at line 1321 of file my_global.h.
ulonglong2double
#define ulonglong2double (A) ((double) (ulonglong) (A))
Definition at line 716 of file my_global.h.
UNINIT_VAR
#define UNINIT_VAR (x) x= 0
Definition at line 466 of file my_global.h.
unlikely
#define unlikely (x) __builtin_expect((x),0)
Definition at line 199 of file my_global.h.
ushortget
#define ushortget (V, M) do { V = uint2korr(M); } while(0)
Definition at line 1318 of file my_global.h.
YESNO
#define YESNO (X) ((X) ? "yes" : "no")
Definition at line 1039 of file my_global.h.
Typedef Documentation
File
typedef int File
Definition at line 520 of file my_global.h.
int16
typedef short int16
Definition at line 884 of file my_global.h.
int64
typedef longlong int64
Definition at line 925 of file my_global.h.
int8
typedef signed char int8
Definition at line 878 of file my_global.h.
intptr
typedef int intptr
Definition at line 940 of file my_global.h.
longlong
typedef long longlong
Definition at line 921 of file my_global.h.
my_bool
typedef char my_bool
Definition at line 992 of file my_global.h.
my_off_t
typedef unsigned long my_off_t
Definition at line 959 of file my_global.h.
my_ptrdiff_t
typedef long long my_ptrdiff_t
Definition at line 835 of file my_global.h.
my_socket
typedef int my_socket
Definition at line 524 of file my_global.h.
my_ulonglong
typedef unsigned long long my_ulonglong
Definition at line 936 of file my_global.h.
myf
typedef int myf
Definition at line 991 of file my_global.h.
nesting_map
typedef ulong nesting_map
Definition at line 968 of file my_global.h.
os_off_t
typedef off_t os_off_t
Definition at line 955 of file my_global.h.
pbool
typedef int pbool
Definition at line 541 of file my_global.h.
pfloat
typedef double pfloat
Definition at line 543 of file my_global.h.
pshort
typedef int pshort
Definition at line 542 of file my_global.h.
puchar
typedef uint puchar
Definition at line 540 of file my_global.h.
qsort_cmp2
typedef int(* qsort_cmp2) (void *, const void *, const void *)
Definition at line 547 of file my_global.h.
size_socket
typedef SOCKET_SIZE_TYPE size_socket
Definition at line 553 of file my_global.h.
table_map
typedef ulonglong table_map
Definition at line 967 of file my_global.h.
uchar
typedef unsigned char uchar
Definition at line 874 of file my_global.h.
uint
typedef unsigned int uint
Definition at line 475 of file my_global.h.
uint16
typedef unsigned short uint16
Definition at line 887 of file my_global.h.
uint64
typedef ulonglong uint64
Definition at line 928 of file my_global.h.
uint8
typedef unsigned char uint8
Definition at line 881 of file my_global.h.
ulong
typedef unsigned long ulong
Definition at line 908 of file my_global.h.
ulonglong
typedef unsigned long ulonglong
Definition at line 920 of file my_global.h.
ushort
typedef unsigned short ushort
Definition at line 476 of file my_global.h.
Function Documentation
rint()
static double rint (double x) inline static
rint(3) implementation for platforms that do not have it. Always rounds to the nearest integer with ties being rounded to the nearest even integer to mimic glibc's rint() behavior in the "round-to-nearest" FPU mode. Hardware-specific optimizations are possible (frndint on x86). Unlike this implementation, hardware will also honor the FPU rounding mode.
Definition at line 1436 of file my_global.h.
 {
   double f, i;
   f = modf(x, &i);
   /*
     All doubles with absolute values > MAX_EXACT_INTEGER are even anyway,
     no need to check it.
   */
   if (x > 0.0)
     i += (double) ((f > 0.5) || (f == 0.5 &&
                                  i <= (double) MAX_EXACT_INTEGER &&
                                  (longlong) i % 2));
   else
     i -= (double) ((f < -0.5) || (f == -0.5 &&
                                   i >= (double) -MAX_EXACT_INTEGER &&
                                   (longlong) i % 2));
   return i;
 }
References f(), MAX_EXACT_INTEGER, and G3D::x.
Variable Documentation
pchar
C_MODE_END typedef int pchar
Definition at line 539 of file my_global.h.
qsort_cmp
C_MODE_START typedef int(* qsort_cmp) (const void *, const void *) (const void * , const void *)
Definition at line 546 of file my_global.h.
Referenced by _lf_pinbox_real_free(), flush_cached_blocks(), and my_dir().
sig_return
C_MODE_START typedef void(* sig_return) () ()
Definition at line 530 of file my_global.h.