Azerotcore-wotlk: npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI Struct Reference
npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI Struct Reference
Public Member Functions
npc_mature_netherwing_drakeAI (Creature *creature)
void Reset () override
void SpellHit (Unit *pCaster, SpellInfo const *spell) override
void MovementInform (uint32 type, uint32 id) override
void JustReachedHome () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid uiPlayerGUID
bool bCanEat
bool bIsEating
uint32 EatTimer
uint32 CastTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 311 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_mature_netherwing_drakeAI()
npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::npc_mature_netherwing_drakeAI (Creature * creature) inline
Definition at line 313 of file zone_shadowmoon_valley.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
JustReachedHome()
void npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 359 of file zone_shadowmoon_valley.cpp.
         {
             me->GetMotionMaster()->InitDefault();
         }
References Unit::GetMotionMaster(), MotionMaster::InitDefault(), and ScriptedAI::me.
MovementInform()
void npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 346 of file zone_shadowmoon_valley.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (id == POINT_ID)
             {
                 bIsEating = true;
                 EatTimer = 7000;
                 me->HandleEmoteCommand(EMOTE_ONESHOT_ATTACK_UNARMED);
             }
         }
References bIsEating, EatTimer, EMOTE_ONESHOT_ATTACK_UNARMED, Unit::HandleEmoteCommand(), ScriptedAI::me, POINT_ID, and POINT_MOTION_TYPE.
Reset()
void npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 323 of file zone_shadowmoon_valley.cpp.
         {
             uiPlayerGUID.Clear();
             bCanEat = false;
             bIsEating = false;
             EatTimer = 5000;
             CastTimer = 5000;
         }
References bCanEat, bIsEating, CastTimer, ObjectGuid::Clear(), EatTimer, and uiPlayerGUID.
Referenced by UpdateAI().
SpellHit()
void npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::SpellHit (Unit * pCaster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 334 of file zone_shadowmoon_valley.cpp.
         {
             if (bCanEat || bIsEating)
                 return;
             if (pCaster->GetTypeId() == TYPEID_PLAYER && spell->Id == SPELL_PLACE_CARCASS && !me->HasAura(SPELL_JUST_EATEN))
             {
                 uiPlayerGUID = pCaster->GetGUID();
                 bCanEat = true;
             }
         }
References bCanEat, bIsEating, Object::GetGUID(), Object::GetTypeId(), Unit::HasAura(), SpellInfo::Id, ScriptedAI::me, SPELL_JUST_EATEN, SPELL_PLACE_CARCASS, TYPEID_PLAYER, and uiPlayerGUID.
UpdateAI()
void npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 364 of file zone_shadowmoon_valley.cpp.
         {
             if (bCanEat || bIsEating)
             {
                 if (EatTimer <= diff)
                 {
                     if (bCanEat && !bIsEating)
                     {
                         if (Unit* unit = ObjectAccessor::GetUnit(*me, uiPlayerGUID))
{
                             if (GameObject* go = unit->FindNearestGameObject(GO_CARCASS, 10))
{
                                 if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == WAYPOINT_MOTION_TYPE)
                                     me->GetMotionMaster()->MovementExpired();
                                 me->GetMotionMaster()->MoveIdle();
                                 me->StopMoving();
                                 me->GetMotionMaster()->MovePoint(POINT_ID, go->GetPositionX(), go->GetPositionY(), go->GetPositionZ());
                             }
                         }
                         bCanEat = false;
                     }
                     else if (bIsEating)
                     {
                         DoCast(me, SPELL_JUST_EATEN);
                         Talk(SAY_JUST_EATEN);
                         if (Player* player = ObjectAccessor::GetPlayer(*me, uiPlayerGUID))
{
                             player->KilledMonsterCredit(NPC_EVENT_PINGER);
                             if (GameObject* go = player->FindNearestGameObject(GO_CARCASS, 10))
                                 go->Delete();
                         }
                         Reset();
                         me->GetMotionMaster()->MoveTargetedHome();
                     }
                 }
                 else
                     EatTimer -= diff;
                 return;
             }
             if (!UpdateVictim())
                 return;
             if (CastTimer <= diff)
             {
                 DoCastVictim(SPELL_NETHER_BREATH);
                 CastTimer = 5000;
             }
             else CastTimer -= diff;
             DoMeleeAttackIfReady();
         }
References bCanEat, bIsEating, CastTimer, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EatTimer, WorldObject::FindNearestGameObject(), MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), ObjectAccessor::GetUnit(), GO_CARCASS, ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), MotionMaster::MovePoint(), MotionMaster::MoveTargetedHome(), NPC_EVENT_PINGER, POINT_ID, Reset(), SAY_JUST_EATEN, SPELL_JUST_EATEN, SPELL_NETHER_BREATH, Unit::StopMoving(), CreatureAI::Talk(), uiPlayerGUID, CreatureAI::UpdateVictim(), and WAYPOINT_MOTION_TYPE.
Member Data Documentation
bCanEat
bool npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::bCanEat
Definition at line 317 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
bIsEating
bool npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::bIsEating
Definition at line 318 of file zone_shadowmoon_valley.cpp.
Referenced by MovementInform(), Reset(), SpellHit(), and UpdateAI().
CastTimer
uint32 npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::CastTimer
Definition at line 321 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), and UpdateAI().
EatTimer
uint32 npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::EatTimer
Definition at line 320 of file zone_shadowmoon_valley.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
uiPlayerGUID
ObjectGuid npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::uiPlayerGUID
Definition at line 315 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp