Azerotcore-wotlk: deps/SFMT/SFMT.c File Reference
SFMT.c File Reference
SIMD oriented Fast Mersenne Twister(SFMT)
#include <string.h>
#include <assert.h>
#include "SFMT.h"
#include "SFMT-params.h"
#include "SFMT-common.h"
Macros
#define UNUSED_VARIABLE(x) (void)(x)
Functions
static int idxof (int i)
static void gen_rand_array (sfmt_t *sfmt, w128_t *array, int size)
static uint32_t func1 (uint32_t x)
static uint32_t func2 (uint32_t x)
static void period_certification (sfmt_t *sfmt)
const char * sfmt_get_idstring (sfmt_t *sfmt)
int sfmt_get_min_array_size32 (sfmt_t *sfmt)
int sfmt_get_min_array_size64 (sfmt_t *sfmt)
void sfmt_gen_rand_all (sfmt_t *sfmt)
void sfmt_fill_array32 (sfmt_t *sfmt, uint32_t *array, int size)
void sfmt_fill_array64 (sfmt_t *sfmt, uint64_t *array, int size)
void sfmt_init_gen_rand (sfmt_t *sfmt, uint32_t seed)
void sfmt_init_by_array (sfmt_t *sfmt, uint32_t *init_key, int key_length)
Detailed Description
SIMD oriented Fast Mersenne Twister(SFMT)
Author
Mutsuo Saito (Hiroshima University)
Makoto Matsumoto (Hiroshima University)
Copyright (C) 2006, 2007 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. Copyright (C) 2012 Mutsuo Saito, Makoto Matsumoto, Hiroshima University and The University of Tokyo. Copyright (C) 2013 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. All rights reserved.
The 3-clause BSD License is applied to this software, see LICENSE.txt
Definition in file SFMT.c.
Macro Definition Documentation
UNUSED_VARIABLE
#define UNUSED_VARIABLE (x) (void)(x)
Definition at line 205 of file SFMT.c.
Function Documentation
func1()
static uint32_t func1 (uint32_t x) inline static
This function represents a function used in the initialization by init_by_array
Parameters
x 32-bit integer
Returns
32-bit integer
Definition at line 152 of file SFMT.c.
{
     return (x ^ (x >> 27)) * (uint32_t)1664525UL;
 }
References G3D::x.
Referenced by sfmt_init_by_array().
func2()
static uint32_t func2 (uint32_t x) inline static
This function represents a function used in the initialization by init_by_array
Parameters
x 32-bit integer
Returns
32-bit integer
Definition at line 162 of file SFMT.c.
{
     return (x ^ (x >> 27)) * (uint32_t)1566083941UL;
 }
References G3D::x.
Referenced by sfmt_init_by_array().
gen_rand_array()
static void gen_rand_array (sfmt_t * sfmt, w128_t * array, int size) inline static
This function fills the user-specified array with pseudorandom integers.
Parameters
sfmt SFMT internal state
array an 128-bit array to be filled by pseudorandom numbers.
size number of 128-bit pseudorandom numbers to be generated.
Definition at line 95 of file SFMT.c.
{
     int i, j;
     w128_t *r1, *r2;
     r1 = &sfmt->state[SFMT_N - 2];
     r2 = &sfmt->state[SFMT_N - 1];
     for (i = 0; i < SFMT_N - SFMT_POS1; i++) {
         do_recursion(&array[i], &sfmt->state[i], &sfmt->state[i + SFMT_POS1], r1, r2);
         r1 = r2;
         r2 = &array[i];
     }
     for (; i < SFMT_N; i++) {
         do_recursion(&array[i], &sfmt->state[i],
                      &array[i + SFMT_POS1 - SFMT_N], r1, r2);
         r1 = r2;
         r2 = &array[i];
     }
     for (; i < size - SFMT_N; i++) {
         do_recursion(&array[i], &array[i - SFMT_N],
                      &array[i + SFMT_POS1 - SFMT_N], r1, r2);
         r1 = r2;
         r2 = &array[i];
     }
     for (j = 0; j < 2 * SFMT_N - size; j++) {
         sfmt->state[j] = array[j + size - SFMT_N];
     }
     for (; i < size; i++, j++) {
         do_recursion(&array[i], &array[i - SFMT_N],
                      &array[i + SFMT_POS1 - SFMT_N], r1, r2);
         r1 = r2;
         r2 = &array[i];
         sfmt->state[j] = array[i];
     }
 }
References array, do_recursion(), SFMT_N, SFMT_POS1, and SFMT_T::state.
Referenced by sfmt_fill_array32(), and sfmt_fill_array64().
idxof()
static int idxof (int i) inline static
This function simulate a 64-bit index of LITTLE ENDIAN in BIG ENDIAN machine.
Definition at line 81 of file SFMT.c.
{
     return i;
 }
Referenced by period_certification(), sfmt_init_by_array(), and sfmt_init_gen_rand().
period_certification()
static void period_certification (sfmt_t * sfmt) static
This function certificate the period of 2^{MEXP}
Parameters
sfmt SFMT internal state
Definition at line 170 of file SFMT.c.
{
     uint32_t inner = 0;
     int i, j;
     uint32_t work;
     uint32_t *psfmt32 = &sfmt->state[0].u[0];
     const uint32_t parity[4] = {SFMT_PARITY1, SFMT_PARITY2,
                                 SFMT_PARITY3, SFMT_PARITY4};
     for (i = 0; i < 4; i++) {
         inner ^= psfmt32[idxof(i)] & parity[i];
     }
     for (i = 16; i > 0; i >>= 1) {
         inner ^= inner >> i;
     }
     inner &= 1;
     /* check OK */
     if (inner == 1) {
         return;
     }
     /* check NG, and modification */
     for (i = 0; i < 4; i++) {
         work = 1;
         for (j = 0; j < 32; j++) {
             if ((work & parity[i]) != 0) {
                 psfmt32[idxof(i)] ^= work;
                 return;
             }
             work = work << 1;
         }
     }
 }
References idxof(), SFMT_PARITY1, SFMT_PARITY2, SFMT_PARITY3, SFMT_PARITY4, SFMT_T::state, and W128_T::u.
Referenced by sfmt_init_by_array(), and sfmt_init_gen_rand().
sfmt_fill_array32()
void sfmt_fill_array32 (sfmt_t * sfmt, uint32_t * array, int size)
This function generates pseudorandom 32-bit integers in the specified array[] by one call. The number of pseudorandom integers is specified by the argument size, which must be at least 624 and a multiple of four. The generation by this function is much faster than the following gen_rand function.
For initialization, init_gen_rand or init_by_array must be called before the first call of this function. This function can not be used after calling gen_rand function, without initialization.
Parameters
sfmt SFMT internal state
array an array where pseudorandom 32-bit integers are filled by this function. The pointer to the array must be "aligned" (namely, must be a multiple of 16) in the SIMD version, since it refers to the address of a 128-bit integer. In the standard C version, the pointer is arbitrary.
size the number of 32-bit pseudorandom integers to be generated. size must be a multiple of 4, and greater than or equal to (MEXP / 128 + 1) * 4.
Note
memalign or posix_memalign is available to get aligned memory. Mac OSX doesn't have these functions, but malloc of OSX returns the pointer to the aligned memory block.
Definition at line 293 of file SFMT.c.
{
     assert(sfmt->idx == SFMT_N32);
     assert(size % 4 == 0);
     assert(size >= SFMT_N32);
     gen_rand_array(sfmt, (w128_t *)array, size / 4);
     sfmt->idx = SFMT_N32;
 }
References array, assert(), gen_rand_array(), SFMT_T::idx, and SFMT_N32.
sfmt_fill_array64()
void sfmt_fill_array64 (sfmt_t * sfmt, uint64_t * array, int size)
This function generates pseudorandom 64-bit integers in the specified array[] by one call. The number of pseudorandom integers is specified by the argument size, which must be at least 312 and a multiple of two. The generation by this function is much faster than the following gen_rand function.
Parameters
sfmt SFMT internal state For initialization, init_gen_rand or init_by_array must be called before the first call of this function. This function can not be used after calling gen_rand function, without initialization.
array an array where pseudorandom 64-bit integers are filled by this function. The pointer to the array must be "aligned" (namely, must be a multiple of 16) in the SIMD version, since it refers to the address of a 128-bit integer. In the standard C version, the pointer is arbitrary.
size the number of 64-bit pseudorandom integers to be generated. size must be a multiple of 2, and greater than or equal to (MEXP / 128 + 1) * 2
Note
memalign or posix_memalign is available to get aligned memory. Mac OSX doesn't have these functions, but malloc of OSX returns the pointer to the aligned memory block.
Definition at line 329 of file SFMT.c.
{
     assert(sfmt->idx == SFMT_N32);
     assert(size % 2 == 0);
     assert(size >= SFMT_N64);
     gen_rand_array(sfmt, (w128_t *)array, size / 2);
     sfmt->idx = SFMT_N32;
 #if defined(BIG_ENDIAN64) && !defined(ONLY64)
     swap((w128_t *)array, size /2);
 #endif
 }
References array, assert(), gen_rand_array(), SFMT_T::idx, SFMT_N32, SFMT_N64, and swap().
sfmt_gen_rand_all()
void sfmt_gen_rand_all (sfmt_t * sfmt)
This function fills the internal state array with pseudorandom integers.
Parameters
sfmt SFMT internal state
Definition at line 245 of file SFMT.c.
{
     int i;
     w128_t *r1, *r2;
     r1 = &sfmt->state[SFMT_N - 2];
     r2 = &sfmt->state[SFMT_N - 1];
     for (i = 0; i < SFMT_N - SFMT_POS1; i++) {
         do_recursion(&sfmt->state[i], &sfmt->state[i],
                      &sfmt->state[i + SFMT_POS1], r1, r2);
         r1 = r2;
         r2 = &sfmt->state[i];
     }
     for (; i < SFMT_N; i++) {
         do_recursion(&sfmt->state[i], &sfmt->state[i],
                      &sfmt->state[i + SFMT_POS1 - SFMT_N], r1, r2);
         r1 = r2;
         r2 = &sfmt->state[i];
     }
 }
References do_recursion(), SFMT_N, SFMT_POS1, and SFMT_T::state.
Referenced by sfmt_genrand_uint32(), and sfmt_genrand_uint64().
sfmt_get_idstring()
const char* sfmt_get_idstring (sfmt_t * sfmt)
This function returns the identification string. The string shows the word size, the Mersenne exponent, and all parameters of this generator.
Parameters
sfmt SFMT internal state
Definition at line 212 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_IDSTR;
 }
References SFMT_IDSTR, and UNUSED_VARIABLE.
sfmt_get_min_array_size32()
int sfmt_get_min_array_size32 (sfmt_t * sfmt)
This function returns the minimum size of array used for fill_array32() function.
Parameters
sfmt SFMT internal state
Returns
minimum size of array used for fill_array32() function.
Definition at line 223 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_N32;
 }
References SFMT_N32, and UNUSED_VARIABLE.
sfmt_get_min_array_size64()
int sfmt_get_min_array_size64 (sfmt_t * sfmt)
This function returns the minimum size of array used for fill_array64() function.
Parameters
sfmt SFMT internal state
Returns
minimum size of array used for fill_array64() function.
Definition at line 234 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_N64;
 }
References SFMT_N64, and UNUSED_VARIABLE.
sfmt_init_by_array()
void sfmt_init_by_array (sfmt_t * sfmt, uint32_t * init_key, int key_length)
This function initializes the internal state array, with an array of 32-bit integers used as the seeds
Parameters
sfmt SFMT internal state
init_key the array of 32-bit integers, used as a seed.
key_length the length of init_key.
Definition at line 371 of file SFMT.c.
{
     int i, j, count;
     uint32_t r;
     int lag;
     int mid;
     int size = SFMT_N * 4;
     uint32_t *psfmt32 = &sfmt->state[0].u[0];
     if (size >= 623) {
         lag = 11;
     } else if (size >= 68) {
         lag = 7;
     } else if (size >= 39) {
         lag = 5;
     } else {
         lag = 3;
     }
     mid = (size - lag) / 2;
     memset(sfmt, 0x8b, sizeof(sfmt_t));
     if (key_length + 1 > SFMT_N32) {
         count = key_length + 1;
     } else {
         count = SFMT_N32;
     }
     r = func1(psfmt32[idxof(0)] ^ psfmt32[idxof(mid)]
               ^ psfmt32[idxof(SFMT_N32 - 1)]);
     psfmt32[idxof(mid)] += r;
     r += key_length;
     psfmt32[idxof(mid + lag)] += r;
     psfmt32[idxof(0)] = r;
     count--;
     for (i = 1, j = 0; (j < count) && (j < key_length); j++) {
         r = func1(psfmt32[idxof(i)] ^ psfmt32[idxof((i + mid) % SFMT_N32)]
                   ^ psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] += r;
         r += init_key[j] + i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] += r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     for (; j < count; j++) {
         r = func1(psfmt32[idxof(i)] ^ psfmt32[idxof((i + mid) % SFMT_N32)]
                   ^ psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] += r;
         r += i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] += r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     for (j = 0; j < SFMT_N32; j++) {
         r = func2(psfmt32[idxof(i)] + psfmt32[idxof((i + mid) % SFMT_N32)]
                   + psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] ^= r;
         r -= i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] ^= r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     sfmt->idx = SFMT_N32;
     period_certification(sfmt);
 }
References count(), func1(), func2(), SFMT_T::idx, idxof(), memset, period_certification(), SFMT_N, SFMT_N32, SFMT_T::state, and W128_T::u.
Referenced by SFMTRand::SFMTRand().
sfmt_init_gen_rand()
void sfmt_init_gen_rand (sfmt_t * sfmt, uint32_t seed)
This function initializes the internal state array with a 32-bit integer seed.
Parameters
sfmt SFMT internal state
seed a 32-bit integer used as the seed.
Definition at line 349 of file SFMT.c.
{
     int i;
     uint32_t *psfmt32 = &sfmt->state[0].u[0];
     psfmt32[idxof(0)] = seed;
     for (i = 1; i < SFMT_N32; i++) {
         psfmt32[idxof(i)] = 1812433253UL * (psfmt32[idxof(i - 1)]
                                             ^ (psfmt32[idxof(i - 1)] >> 30))
             + i;
     }
     sfmt->idx = SFMT_N32;
     period_certification(sfmt);
 }
References SFMT_T::idx, idxof(), period_certification(), SFMT_N32, SFMT_T::state, and W128_T::u.
Referenced by SFMTRand::SFMTRand().