Azerotcore-wotlk: EventProcessor Class Reference
EventProcessor Class Reference
#include <EventProcessor.h>
Public Member Functions
EventProcessor ()
~EventProcessor ()
void Update (uint32 p_time)
void KillAllEvents (bool force)
void AddEvent (BasicEvent *Event, uint64 e_time, bool set_addtime=true)
void ModifyEventTime (BasicEvent *event, Milliseconds newTime)
uint64 CalculateTime (uint64 t_offset) const
uint64 CalculateQueueTime (uint64 delay) const
Protected Attributes
uint64 m_time
EventList m_events
bool m_aborting
Detailed Description
Definition at line 74 of file EventProcessor.h.
Constructor & Destructor Documentation
EventProcessor()
EventProcessor::EventProcessor () inline
Definition at line 77 of file EventProcessor.h.
 : m_time(0) { }
~EventProcessor()
EventProcessor::~EventProcessor ()
Definition at line 35 of file EventProcessor.cpp.
 {
     KillAllEvents(true);
 }
References KillAllEvents().
Member Function Documentation
AddEvent()
void EventProcessor::AddEvent (BasicEvent * Event, uint64 e_time, bool set_addtime = true)
Definition at line 114 of file EventProcessor.cpp.
 {
     if (set_addtime)
         Event->m_addTime = m_time;
     Event->m_execTime = e_time;
     m_events.insert(std::pair<uint64, BasicEvent*>(e_time, Event));
 }
References m_events, and m_time.
Referenced by Unit::_ApplyAura(), Unit::_ExitVehicle(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate(), BattlegroundQueue::AddEvent(), Spell::AddUnitTarget(), spell_sindragosa_ice_tomb::spell_sindragosa_ice_tomb_AuraScript::AfterApply(), Creature::CallAssistance(), Unit::CastDelayedSpellWithPeriodicAmount(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction(), CreatureAI::EnterEvadeMode(), SpellEvent::Execute(), BattleExperienceEvent::Execute(), UtherBatteredHiltEvent::Execute(), TriggerWickedSpirit::Execute(), lapseTeleport::Execute(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), Creature::ForcedDespawn(), WorldSession::HandleAuctionListOwnerItems(), spell_alar_flame_quills::spell_alar_flame_quills_AuraScript::HandlePeriodic(), npc_pet_mage_mirror_image::InitializeAI(), npc_swarm_scarab::npc_swarm_scarabAI::JustDied(), npc_nerubian_burrower::npc_nerubian_burrowerAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_xt002_boombot::npc_xt002_boombotAI::JustDied(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform(), boss_essence_of_desire::boss_essence_of_desireAI::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), spell_halion_twilight_realm::spell_halion_twilight_realm_AuraScript::OnApply(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), spell_halion_leave_twilight_realm::spell_halion_leave_twilight_realm_AuraScript::OnRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Spell::prepare(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), npc_gunship_boarding_addAI::SetData(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies(), TempSummon::UnSummon(), Totem::UnSummon(), spell_illidari_council_deadly_strike::spell_illidari_council_deadly_strike_AuraScript::Update(), Update(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), and boss_magtheridon::boss_magtheridonAI::UpdateAI().
CalculateQueueTime()
uint64 EventProcessor::CalculateQueueTime (uint64 delay) const
Definition at line 141 of file EventProcessor.cpp.
 {
     return CalculateTime(delay - (m_time % delay));
 }
References CalculateTime(), and m_time.
Referenced by Unit::CastDelayedSpellWithPeriodicAmount().
CalculateTime()
uint64 EventProcessor::CalculateTime (uint64 t_offset) const
Definition at line 136 of file EventProcessor.cpp.
 {
     return (m_time + t_offset);
 }
References m_time.
Referenced by Unit::_ApplyAura(), Unit::_ExitVehicle(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate(), BattlegroundQueue::AddEvent(), Spell::AddUnitTarget(), CalculateQueueTime(), Creature::CallAssistance(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction(), CreatureAI::EnterEvadeMode(), UtherBatteredHiltEvent::Execute(), TriggerWickedSpirit::Execute(), lapseTeleport::Execute(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), Creature::ForcedDespawn(), WorldSession::HandleAuctionListOwnerItems(), npc_pet_mage_mirror_image::InitializeAI(), npc_swarm_scarab::npc_swarm_scarabAI::JustDied(), npc_nerubian_burrower::npc_nerubian_burrowerAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_xt002_boombot::npc_xt002_boombotAI::JustDied(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform(), boss_essence_of_desire::boss_essence_of_desireAI::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Spell::prepare(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), npc_gunship_boarding_addAI::SetData(), boss_the_beast::boss_thebeastAI::SetData(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies(), TempSummon::UnSummon(), Totem::UnSummon(), Update(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), and boss_magtheridon::boss_magtheridonAI::UpdateAI().
KillAllEvents()
void EventProcessor::KillAllEvents (bool force)
Definition at line 82 of file EventProcessor.cpp.
 {
     // first, abort all existing events
     for (auto itr = m_events.begin(); itr != m_events.end();)
     {
         // Abort events which weren't aborted already
         if (!itr->second->IsAborted())
         {
             itr->second->SetAborted();
             itr->second->Abort(m_time);
         }
         // Skip non-deletable events when we are
         // not forcing the event cancellation.
         if (!force && !itr->second->IsDeletable())
         {
             ++itr;
             continue;
         }
         delete itr->second;
         if (force)
             ++itr; // Clear the whole container when forcing
         else
             itr = m_events.erase(itr);
     }
     if (force)
         m_events.clear();
 }
References m_events, and m_time.
Referenced by Unit::CleanupBeforeRemoveFromMap(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::DoAction(), NPCStaveQuestAI::ResetState(), BattlegroundQueue::~BattlegroundQueue(), and ~EventProcessor().
ModifyEventTime()
void EventProcessor::ModifyEventTime (BasicEvent * event, Milliseconds newTime)
Definition at line 122 of file EventProcessor.cpp.
 {
     for (auto itr = m_events.begin(); itr != m_events.end(); ++itr)
     {
         if (itr->second != event)
             continue;
         event->m_execTime = newTime.count();
         m_events.erase(itr);
         m_events.insert(std::pair<uint64, BasicEvent*>(newTime.count(), event));
         break;
     }
 }
References m_events.
Referenced by Spell::RecalculateDelayMomentForDst().
Update()
void EventProcessor::Update (uint32 p_time)
Definition at line 40 of file EventProcessor.cpp.
 {
     // update time
     m_time += p_time;
     // main event loop
     EventList::iterator i;
     while (((i = m_events.begin()) != m_events.end()) && i->first <= m_time)
     {
         // get and remove event from queue
         BasicEvent* event = i->second;
         m_events.erase(i);
         if (event->IsRunning())
         {
             if (event->Execute(m_time, p_time))
             {
                 // completely destroy event if it is not re-added
                 delete event;
             }
             continue;
         }
         if (event->IsAbortScheduled())
         {
             event->Abort(m_time);
             // Mark the event as aborted
             event->SetAborted();
         }
         if (event->IsDeletable())
         {
             delete event;
             continue;
         }
         // Reschedule non deletable events to be checked at
         // the next update tick
         AddEvent(event, CalculateTime(1), false);
     }
 }
References AddEvent(), CalculateTime(), m_events, and m_time.
Referenced by Unit::Update(), and BattlegroundQueue::UpdateEvents().
Member Data Documentation
m_aborting
bool EventProcessor::m_aborting protected
Definition at line 92 of file EventProcessor.h.
m_events
EventList EventProcessor::m_events protected
Definition at line 91 of file EventProcessor.h.
Referenced by AddEvent(), KillAllEvents(), ModifyEventTime(), and Update().
m_time
uint64 EventProcessor::m_time protected
Definition at line 90 of file EventProcessor.h.
Referenced by AddEvent(), CalculateQueueTime(), CalculateTime(), KillAllEvents(), and Update().
The documentation for this class was generated from the following files:
src/common/Utilities/EventProcessor.h
src/common/Utilities/EventProcessor.cpp