Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/prof_externs.h File Reference
prof_externs.h File Reference
#include "jemalloc/internal/mutex.h"
Typedefs
typedef int() prof_dump_open_t(bool, const char *)
typedef bool() prof_dump_header_t(tsdn_t *, bool, const prof_cnt_t *)
Functions
void prof_alloc_rollback (tsd_t *tsd, prof_tctx_t *tctx, bool updated)
void prof_malloc_sample_object (tsdn_t *tsdn, const void *ptr, size_t usize, prof_tctx_t *tctx)
void prof_free_sampled_object (tsd_t *tsd, const void *ptr, size_t usize, prof_tctx_t *tctx)
void bt_init (prof_bt_t *bt, void **vec)
void prof_backtrace (prof_bt_t *bt)
prof_tctx_t * prof_lookup (tsd_t *tsd, prof_bt_t *bt)
bool prof_accum_init (tsdn_t *tsdn, prof_accum_t *prof_accum)
void prof_idump (tsdn_t *tsdn)
bool prof_mdump (tsd_t *tsd, const char *filename)
void prof_gdump (tsdn_t *tsdn)
prof_tdata_t * prof_tdata_init (tsd_t *tsd)
prof_tdata_t * prof_tdata_reinit (tsd_t *tsd, prof_tdata_t *tdata)
void prof_reset (tsd_t *tsd, size_t lg_sample)
void prof_tdata_cleanup (tsd_t *tsd)
bool prof_active_get (tsdn_t *tsdn)
bool prof_active_set (tsdn_t *tsdn, bool active)
const char * prof_thread_name_get (tsd_t *tsd)
int prof_thread_name_set (tsd_t *tsd, const char *thread_name)
bool prof_thread_active_get (tsd_t *tsd)
bool prof_thread_active_set (tsd_t *tsd, bool active)
bool prof_thread_active_init_get (tsdn_t *tsdn)
bool prof_thread_active_init_set (tsdn_t *tsdn, bool active_init)
bool prof_gdump_get (tsdn_t *tsdn)
bool prof_gdump_set (tsdn_t *tsdn, bool active)
void prof_boot0 (void)
void prof_boot1 (void)
bool prof_boot2 (tsd_t *tsd)
void prof_prefork0 (tsdn_t *tsdn)
void prof_prefork1 (tsdn_t *tsdn)
void prof_postfork_parent (tsdn_t *tsdn)
void prof_postfork_child (tsdn_t *tsdn)
void prof_sample_threshold_update (prof_tdata_t *tdata)
bool prof_log_start (tsdn_t *tsdn, const char *filename)
bool prof_log_stop (tsdn_t *tsdn)
Variables
malloc_mutex_t bt2gctx_mtx
bool opt_prof
bool opt_prof_active
bool opt_prof_thread_active_init
size_t opt_lg_prof_sample
ssize_t opt_lg_prof_interval
bool opt_prof_gdump
bool opt_prof_final
bool opt_prof_leak
bool opt_prof_accum
bool opt_prof_log
char opt_prof_prefix [1]
bool prof_active
bool prof_gdump_val
uint64_t prof_interval
size_t lg_prof_sample
prof_dump_open_t *JET_MUTABLE prof_dump_open
prof_dump_header_t *JET_MUTABLE prof_dump_header
Typedef Documentation
prof_dump_header_t
typedef bool() prof_dump_header_t(tsdn_t *, bool, const prof_cnt_t *)
Definition at line 61 of file prof_externs.h.
prof_dump_open_t
typedef int() prof_dump_open_t(bool, const char *)
Definition at line 58 of file prof_externs.h.
Function Documentation
bt_init()
void bt_init (prof_bt_t * bt, void ** vec)
Definition at line 540 of file prof.c.
{
     cassert(config_prof);
     bt->vec = vec;
     bt->len = 0;
 }
References cassert(), config_prof, prof_bt_s::len, and prof_bt_s::vec.
Referenced by prof_try_log().
prof_accum_init()
bool prof_accum_init (tsdn_t * tsdn, prof_accum_t * prof_accum)
Definition at line 2033 of file prof.c.
{
     cassert(config_prof);
 #ifndef JEMALLOC_ATOMIC_U64
     if (malloc_mutex_init(&prof_accum->mtx, "prof_accum",
         WITNESS_RANK_PROF_ACCUM, malloc_mutex_rank_exclusive)) {
         return true;
     }
     prof_accum->accumbytes = 0;
 #else
     atomic_store_u64(&prof_accum->accumbytes, 0, ATOMIC_RELAXED);
 #endif
     return false;
 }
References prof_accum_s::accumbytes, ATOMIC_RELAXED, cassert(), config_prof, malloc_mutex_init, malloc_mutex_rank_exclusive, prof_accum_s::mtx, and WITNESS_RANK_PROF_ACCUM.
prof_active_get()
bool prof_active_get (tsdn_t * tsdn)
Definition at line 2400 of file prof.c.
{
     bool prof_active_current;
     malloc_mutex_lock(tsdn, &prof_active_mtx);
     prof_active_current = prof_active;
     malloc_mutex_unlock(tsdn, &prof_active_mtx);
     return prof_active_current;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_active, prof_active_mtx, and prof_gctx_merge_iter_arg_s::tsdn.
prof_active_set()
bool prof_active_set (tsdn_t * tsdn, bool active)
Definition at line 2410 of file prof.c.
{
     bool prof_active_old;
     malloc_mutex_lock(tsdn, &prof_active_mtx);
     prof_active_old = prof_active;
     prof_active = active;
     malloc_mutex_unlock(tsdn, &prof_active_mtx);
     return prof_active_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_active, prof_active_mtx, and prof_gctx_merge_iter_arg_s::tsdn.
prof_alloc_rollback()
void prof_alloc_rollback (tsd_t * tsd, prof_tctx_t * tctx, bool updated)
Referenced by imalloc_body(), irallocx_prof(), irealloc_prof(), ixallocx_prof(), and prof_realloc().
prof_backtrace()
void prof_backtrace (prof_bt_t * bt)
Definition at line 802 of file prof.c.
{
     cassert(config_prof);
     not_reached();
 }
References cassert(), config_prof, and not_reached.
Referenced by prof_try_log().
prof_boot0()
void prof_boot0 (void)
Definition at line 2920 of file prof.c.
                  {
     cassert(config_prof);
     memcpy(opt_prof_prefix, PROF_PREFIX_DEFAULT,
         sizeof(PROF_PREFIX_DEFAULT));
 }
References cassert(), config_prof, memcpy, opt_prof_prefix, and PROF_PREFIX_DEFAULT.
prof_boot1()
void prof_boot1 (void)
Definition at line 2928 of file prof.c.
                  {
     cassert(config_prof);
     /*
      * opt_prof must be in its final state before any arenas are
      * initialized, so this function must be executed early.
      */
     if (opt_prof_leak && !opt_prof) {
         /*
          * Enable opt_prof, but in such a way that profiles are never
          * automatically dumped.
          */
         opt_prof = true;
         opt_prof_gdump = false;
     } else if (opt_prof) {
         if (opt_lg_prof_interval >= 0) {
             prof_interval = (((uint64_t)1U) <<
                 opt_lg_prof_interval);
         }
     }
 }
References cassert(), config_prof, opt_lg_prof_interval, opt_prof, opt_prof_gdump, opt_prof_leak, and prof_interval.
prof_boot2()
bool prof_boot2 (tsd_t * tsd)
Definition at line 2952 of file prof.c.
{
     cassert(config_prof);
     if (opt_prof) {
         unsigned i;
         lg_prof_sample = opt_lg_prof_sample;
         prof_active = opt_prof_active;
         if (malloc_mutex_init(&prof_active_mtx, "prof_active",
             WITNESS_RANK_PROF_ACTIVE, malloc_mutex_rank_exclusive)) {
             return true;
         }
         prof_gdump_val = opt_prof_gdump;
         if (malloc_mutex_init(&prof_gdump_mtx, "prof_gdump",
             WITNESS_RANK_PROF_GDUMP, malloc_mutex_rank_exclusive)) {
             return true;
         }
         prof_thread_active_init = opt_prof_thread_active_init;
         if (malloc_mutex_init(&prof_thread_active_init_mtx,
             "prof_thread_active_init",
             WITNESS_RANK_PROF_THREAD_ACTIVE_INIT,
             malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (ckh_new(tsd, &bt2gctx, PROF_CKH_MINITEMS, prof_bt_hash,
             prof_bt_keycomp)) {
             return true;
         }
         if (malloc_mutex_init(&bt2gctx_mtx, "prof_bt2gctx",
             WITNESS_RANK_PROF_BT2GCTX, malloc_mutex_rank_exclusive)) {
             return true;
         }
         tdata_tree_new(&tdatas);
         if (malloc_mutex_init(&tdatas_mtx, "prof_tdatas",
             WITNESS_RANK_PROF_TDATAS, malloc_mutex_rank_exclusive)) {
             return true;
         }
         next_thr_uid = 0;
         if (malloc_mutex_init(&next_thr_uid_mtx, "prof_next_thr_uid",
             WITNESS_RANK_PROF_NEXT_THR_UID, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (malloc_mutex_init(&prof_dump_seq_mtx, "prof_dump_seq",
             WITNESS_RANK_PROF_DUMP_SEQ, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (malloc_mutex_init(&prof_dump_mtx, "prof_dump",
             WITNESS_RANK_PROF_DUMP, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (opt_prof_final && opt_prof_prefix[0] != '\0' &&
             atexit(prof_fdump) != 0) {
             malloc_write("<jemalloc>: Error in atexit()\n");
             if (opt_abort) {
                 abort();
             }
         }
         if (opt_prof_log) {
             prof_log_start(tsd_tsdn(tsd), NULL);
         }
         if (atexit(prof_log_stop_final) != 0) {
             malloc_write("<jemalloc>: Error in atexit() "
                      "for logging\n");
             if (opt_abort) {
                 abort();
             }
         }
         if (malloc_mutex_init(&log_mtx, "prof_log",
             WITNESS_RANK_PROF_LOG, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (ckh_new(tsd, &log_bt_node_set, PROF_CKH_MINITEMS,
             prof_bt_node_hash, prof_bt_node_keycomp)) {
             return true;
         }
         if (ckh_new(tsd, &log_thr_node_set, PROF_CKH_MINITEMS,
             prof_thr_node_hash, prof_thr_node_keycomp)) {
             return true;
         }
         log_tables_initialized = true;
         gctx_locks = (malloc_mutex_t *)base_alloc(tsd_tsdn(tsd),
             b0get(), PROF_NCTX_LOCKS * sizeof(malloc_mutex_t),
             CACHELINE);
         if (gctx_locks == NULL) {
             return true;
         }
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             if (malloc_mutex_init(&gctx_locks[i], "prof_gctx",
                 WITNESS_RANK_PROF_GCTX,
                 malloc_mutex_rank_exclusive)) {
                 return true;
             }
         }
         tdata_locks = (malloc_mutex_t *)base_alloc(tsd_tsdn(tsd),
             b0get(), PROF_NTDATA_LOCKS * sizeof(malloc_mutex_t),
             CACHELINE);
         if (tdata_locks == NULL) {
             return true;
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             if (malloc_mutex_init(&tdata_locks[i], "prof_tdata",
                 WITNESS_RANK_PROF_TDATA,
                 malloc_mutex_rank_exclusive)) {
                 return true;
             }
         }
 #ifdef JEMALLOC_PROF_LIBGCC
         /*
          * Cause the backtracing machinery to allocate its internal
          * state before enabling profiling.
          */
         _Unwind_Backtrace(prof_unwind_init_callback, NULL);
 #endif
     }
     prof_booted = true;
     return false;
 }
References _Unwind_Backtrace, b0get, base_alloc, bt2gctx, bt2gctx_mtx, CACHELINE, cassert(), ckh_new, config_prof, gctx_locks, lg_prof_sample, log_bt_node_set, log_mtx, log_tables_initialized, log_thr_node_set, malloc_mutex_init, malloc_mutex_rank_exclusive, malloc_write, next_thr_uid, next_thr_uid_mtx, NULL, opt_abort, opt_lg_prof_sample, opt_prof, opt_prof_active, opt_prof_final, opt_prof_gdump, opt_prof_log, opt_prof_prefix, opt_prof_thread_active_init, prof_active, prof_active_mtx, prof_booted, prof_bt_hash(), prof_bt_keycomp(), prof_bt_node_hash(), prof_bt_node_keycomp(), PROF_CKH_MINITEMS, prof_dump_mtx, prof_dump_seq_mtx, prof_fdump(), prof_gdump_mtx, prof_gdump_val, prof_log_start(), prof_log_stop_final(), PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thr_node_hash(), prof_thr_node_keycomp(), prof_thread_active_init, prof_thread_active_init_mtx, tdata_locks, tdatas, tdatas_mtx, tsd_tsdn(), WITNESS_RANK_PROF_ACTIVE, WITNESS_RANK_PROF_BT2GCTX, WITNESS_RANK_PROF_DUMP, WITNESS_RANK_PROF_DUMP_SEQ, WITNESS_RANK_PROF_GCTX, WITNESS_RANK_PROF_GDUMP, WITNESS_RANK_PROF_LOG, WITNESS_RANK_PROF_NEXT_THR_UID, WITNESS_RANK_PROF_TDATA, WITNESS_RANK_PROF_TDATAS, and WITNESS_RANK_PROF_THREAD_ACTIVE_INIT.
prof_free_sampled_object()
void prof_free_sampled_object (tsd_t * tsd, const void * ptr, size_t usize, prof_tctx_t * tctx)
Definition at line 521 of file prof.c.
{
     malloc_mutex_lock(tsd_tsdn(tsd), tctx->tdata->lock);
     assert(tctx->cnts.curobjs > 0);
     assert(tctx->cnts.curbytes >= usize);
     tctx->cnts.curobjs--;
     tctx->cnts.curbytes -= usize;
     prof_try_log(tsd, ptr, usize, tctx);
     if (prof_tctx_should_destroy(tsd_tsdn(tsd), tctx)) {
         prof_tctx_destroy(tsd, tctx);
     } else {
         malloc_mutex_unlock(tsd_tsdn(tsd), tctx->tdata->lock);
     }
 }
References assert(), prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), prof_tctx_destroy(), prof_tctx_should_destroy(), prof_try_log(), ptr(), tctx, prof_tctx_s::tdata, and tsd_tsdn().
prof_gdump()
void prof_gdump (tsdn_t * tsdn)
Definition at line 2106 of file prof.c.
{
     tsd_t *tsd;
     prof_tdata_t *tdata;
     cassert(config_prof);
     if (!prof_booted || tsdn_null(tsdn) || !prof_active_get_unlocked()) {
         return;
     }
     tsd = tsdn_tsd(tsdn);
     if (tsd_reentrancy_level_get(tsd) > 0) {
         return;
     }
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return;
     }
     if (tdata->enq) {
         tdata->enq_gdump = true;
         return;
     }
     if (opt_prof_prefix[0] != '\0') {
         char filename[DUMP_FILENAME_BUFSIZE];
         malloc_mutex_lock(tsdn, &prof_dump_seq_mtx);
         prof_dump_filename(filename, 'u', prof_dump_useq);
         prof_dump_useq++;
         malloc_mutex_unlock(tsdn, &prof_dump_seq_mtx);
         prof_dump(tsd, false, filename, false);
     }
 }
References cassert(), config_prof, DUMP_FILENAME_BUFSIZE, prof_tdata_s::enq, prof_tdata_s::enq_gdump, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof_prefix, prof_active_get_unlocked(), prof_booted, prof_dump(), prof_dump_filename(), prof_dump_seq_mtx, prof_dump_useq, prof_tdata_get(), prof_gctx_merge_iter_arg_s::tsdn, tsdn_null(), and tsdn_tsd().
Referenced by prof_leave().
prof_gdump_get()
bool prof_gdump_get (tsdn_t * tsdn)
Definition at line 2899 of file prof.c.
{
     bool prof_gdump_current;
     malloc_mutex_lock(tsdn, &prof_gdump_mtx);
     prof_gdump_current = prof_gdump_val;
     malloc_mutex_unlock(tsdn, &prof_gdump_mtx);
     return prof_gdump_current;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_gdump_mtx, and prof_gdump_val.
prof_gdump_set()
bool prof_gdump_set (tsdn_t * tsdn, bool active)
Definition at line 2909 of file prof.c.
{
     bool prof_gdump_old;
     malloc_mutex_lock(tsdn, &prof_gdump_mtx);
     prof_gdump_old = prof_gdump_val;
     prof_gdump_val = gdump;
     malloc_mutex_unlock(tsdn, &prof_gdump_mtx);
     return prof_gdump_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_gdump_mtx, and prof_gdump_val.
prof_idump()
void prof_idump (tsdn_t * tsdn)
Definition at line 2049 of file prof.c.
{
     tsd_t *tsd;
     prof_tdata_t *tdata;
     cassert(config_prof);
     if (!prof_booted || tsdn_null(tsdn) || !prof_active_get_unlocked()) {
         return;
     }
     tsd = tsdn_tsd(tsdn);
     if (tsd_reentrancy_level_get(tsd) > 0) {
         return;
     }
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return;
     }
     if (tdata->enq) {
         tdata->enq_idump = true;
         return;
     }
     if (opt_prof_prefix[0] != '\0') {
         char filename[PATH_MAX + 1];
         malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump_filename(filename, 'i', prof_dump_iseq);
         prof_dump_iseq++;
         malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump(tsd, false, filename, false);
     }
 }
References cassert(), config_prof, prof_tdata_s::enq, prof_tdata_s::enq_idump, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof_prefix, prof_active_get_unlocked(), prof_booted, prof_dump(), prof_dump_filename(), prof_dump_iseq, prof_dump_seq_mtx, prof_tdata_get(), tsd_tsdn(), prof_gctx_merge_iter_arg_s::tsdn, tsdn_null(), and tsdn_tsd().
Referenced by prof_leave().
prof_log_start()
bool prof_log_start (tsdn_t * tsdn, const char * filename)
Definition at line 2517 of file prof.c.
{
     if (!opt_prof || !prof_booted) {
         return true;
     }
     bool ret = false;
     size_t buf_size = PATH_MAX + 1;
     malloc_mutex_lock(tsdn, &log_mtx);
     if (prof_logging_state != prof_logging_state_stopped) {
         ret = true;
     } else if (filename == NULL) {
         /* Make default name. */
         malloc_snprintf(log_filename, buf_size, "%s.%d.%"FMTu64".json",
             opt_prof_prefix, prof_getpid(), log_seq);
         log_seq++;
         prof_logging_state = prof_logging_state_started;
     } else if (strlen(filename) >= buf_size) {
         ret = true;
     } else {
         strcpy(log_filename, filename);
         prof_logging_state = prof_logging_state_started;
     }
     if (!ret) {
         nstime_update(&log_start_timestamp);
     }
     malloc_mutex_unlock(tsdn, &log_mtx);
     return ret;
 }
References FMTu64, log_filename, log_mtx, log_seq, log_start_timestamp, malloc_mutex_lock(), malloc_mutex_unlock(), malloc_snprintf, nstime_update, NULL, opt_prof, opt_prof_prefix, prof_booted, prof_getpid(), prof_logging_state, prof_logging_state_started, prof_logging_state_stopped, ret, and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_boot2().
prof_log_stop()
bool prof_log_stop (tsdn_t * tsdn)
Definition at line 2696 of file prof.c.
{
     if (!opt_prof || !prof_booted) {
         return true;
     }
     tsd_t *tsd = tsdn_tsd(tsdn);
     malloc_mutex_lock(tsdn, &log_mtx);
     if (prof_logging_state != prof_logging_state_started) {
         malloc_mutex_unlock(tsdn, &log_mtx);
         return true;
     }
     /*
      * Set the state to dumping. We'll set it to stopped when we're done.
      * Since other threads won't be able to start/stop/log when the state is
      * dumping, we don't have to hold the lock during the whole method.
      */
     prof_logging_state = prof_logging_state_dumping;
     malloc_mutex_unlock(tsdn, &log_mtx);
     emitter_t emitter;
     /* Create a file. */
     int fd;
 #ifdef JEMALLOC_JET
     if (prof_log_dummy) {
         fd = 0;
     } else {
         fd = creat(log_filename, 0644);
     }
 #else
     fd = creat(log_filename, 0644);
 #endif
     if (fd == -1) {
         malloc_printf("<jemalloc>: creat() for log file \"%s\" "
                   " failed with %d\n", log_filename, errno);
         if (opt_abort) {
             abort();
         }
         return true;
     }
     /* Emit to json. */
     struct prof_emitter_cb_arg_s arg;
     arg.fd = fd;
     emitter_init(&emitter, emitter_output_json, &prof_emitter_write_cb,
         (void *)(&arg));
     emitter_begin(&emitter);
     prof_log_emit_metadata(&emitter);
     prof_log_emit_threads(tsd, &emitter);
     prof_log_emit_traces(tsd, &emitter);
     prof_log_emit_allocs(tsd, &emitter);
     emitter_end(&emitter);
     /* Reset global state. */
     if (log_tables_initialized) {
         ckh_delete(tsd, &log_bt_node_set);
         ckh_delete(tsd, &log_thr_node_set);
     }
     log_tables_initialized = false;
     log_bt_index = 0;
     log_thr_index = 0;
     log_bt_first = NULL;
     log_bt_last = NULL;
     log_thr_first = NULL;
     log_thr_last = NULL;
     log_alloc_first = NULL;
     log_alloc_last = NULL;
     malloc_mutex_lock(tsdn, &log_mtx);
     prof_logging_state = prof_logging_state_stopped;
     malloc_mutex_unlock(tsdn, &log_mtx);
 #ifdef JEMALLOC_JET
     if (prof_log_dummy) {
         return false;
     }
 #endif
     return close(fd);
 }
References arg(), ckh_delete, close, creat, emitter_begin(), emitter_end(), emitter_init(), emitter_output_json, errno, prof_emitter_cb_arg_s::fd, log_alloc_first, log_alloc_last, log_bt_first, log_bt_index, log_bt_last, log_bt_node_set, log_filename, log_mtx, log_tables_initialized, log_thr_first, log_thr_index, log_thr_last, log_thr_node_set, malloc_mutex_lock(), malloc_mutex_unlock(), malloc_printf, NULL, opt_abort, opt_prof, prof_booted, prof_emitter_write_cb(), prof_log_emit_allocs(), prof_log_emit_metadata(), prof_log_emit_threads(), prof_log_emit_traces(), prof_logging_state, prof_logging_state_dumping, prof_logging_state_started, prof_logging_state_stopped, and tsdn_tsd().
Referenced by prof_log_stop_final().
prof_lookup()
prof_tctx_t* prof_lookup (tsd_t * tsd, prof_bt_t * bt)
Definition at line 1053 of file prof.c.
{
     union {
         prof_tctx_t *p;
         void        *v;
     } ret;
     prof_tdata_t *tdata;
     bool not_found;
     cassert(config_prof);
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return NULL;
     }
     malloc_mutex_lock(tsd_tsdn(tsd), tdata->lock);
     not_found = ckh_search(&tdata->bt2tctx, bt, NULL, &ret.v);
     if (!not_found) { /* Note double negative! */
         ret.p->prepared = true;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
     if (not_found) {
         void *btkey;
         prof_gctx_t *gctx;
         bool new_gctx, error;
         /*
          * This thread's cache lacks bt.  Look for it in the global
          * cache.
          */
         if (prof_lookup_global(tsd, bt, tdata, &btkey, &gctx,
             &new_gctx)) {
             return NULL;
         }
         /* Link a prof_tctx_t into gctx for this thread. */
         ret.v = iallocztm(tsd_tsdn(tsd), sizeof(prof_tctx_t),
             sz_size2index(sizeof(prof_tctx_t)), false, NULL, true,
             arena_ichoose(tsd, NULL), true);
         if (ret.p == NULL) {
             if (new_gctx) {
                 prof_gctx_try_destroy(tsd, tdata, gctx, tdata);
             }
             return NULL;
         }
         ret.p->tdata = tdata;
         ret.p->thr_uid = tdata->thr_uid;
         ret.p->thr_discrim = tdata->thr_discrim;
         memset(&ret.p->cnts, 0, sizeof(prof_cnt_t));
         ret.p->gctx = gctx;
         ret.p->tctx_uid = tdata->tctx_uid_next++;
         ret.p->prepared = true;
         ret.p->state = prof_tctx_state_initializing;
         malloc_mutex_lock(tsd_tsdn(tsd), tdata->lock);
         error = ckh_insert(tsd, &tdata->bt2tctx, btkey, ret.v);
         malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
         if (error) {
             if (new_gctx) {
                 prof_gctx_try_destroy(tsd, tdata, gctx, tdata);
             }
             idalloctm(tsd_tsdn(tsd), ret.v, NULL, NULL, true, true);
             return NULL;
         }
         malloc_mutex_lock(tsd_tsdn(tsd), gctx->lock);
         ret.p->state = prof_tctx_state_nominal;
         tctx_tree_insert(&gctx->tctxs, ret.p);
         gctx->nlimbo--;
         malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
     }
     return ret.p;
 }
References arena_ichoose(), prof_tdata_s::bt2tctx, cassert(), ckh_insert, ckh_search, config_prof, error(), iallocztm(), idalloctm(), prof_gctx_s::lock, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), memset, prof_gctx_s::nlimbo, NULL, prof_gctx_try_destroy(), prof_lookup_global(), prof_tctx_state_initializing, prof_tctx_state_nominal, prof_tdata_get(), ret, sz_size2index(), prof_tdata_s::tctx_uid_next, prof_gctx_s::tctxs, prof_tdata_s::thr_discrim, prof_tdata_s::thr_uid, and tsd_tsdn().
prof_malloc_sample_object()
void prof_malloc_sample_object (tsdn_t * tsdn, const void * ptr, size_t usize, prof_tctx_t * tctx)
Definition at line 343 of file prof.c.
{
     prof_tctx_set(tsdn, ptr, usize, NULL, tctx);
     /* Get the current time and set this in the extent_t. We'll read this
      * when free() is called. */
     nstime_t t = NSTIME_ZERO_INITIALIZER;
     nstime_update(&t);
     prof_alloc_time_set(tsdn, ptr, NULL, t);
     malloc_mutex_lock(tsdn, tctx->tdata->lock);
     tctx->cnts.curobjs++;
     tctx->cnts.curbytes += usize;
     if (opt_prof_accum) {
         tctx->cnts.accumobjs++;
         tctx->cnts.accumbytes += usize;
     }
     tctx->prepared = false;
     malloc_mutex_unlock(tsdn, tctx->tdata->lock);
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), nstime_update, NSTIME_ZERO_INITIALIZER, NULL, opt_prof_accum, prof_tctx_s::prepared, prof_alloc_time_set(), prof_tctx_set(), ptr(), tctx, and prof_tctx_s::tdata.
prof_mdump()
bool prof_mdump (tsd_t * tsd, const char * filename)
Definition at line 2083 of file prof.c.
{
     cassert(config_prof);
     assert(tsd_reentrancy_level_get(tsd) == 0);
     if (!opt_prof || !prof_booted) {
         return true;
     }
     char filename_buf[DUMP_FILENAME_BUFSIZE];
     if (filename == NULL) {
         /* No filename specified, so automatically generate one. */
         if (opt_prof_prefix[0] == '\0') {
             return true;
         }
         malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump_filename(filename_buf, 'm', prof_dump_mseq);
         prof_dump_mseq++;
         malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         filename = filename_buf;
     }
     return prof_dump(tsd, true, filename, false);
 }
References assert(), cassert(), config_prof, DUMP_FILENAME_BUFSIZE, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof, opt_prof_prefix, prof_booted, prof_dump(), prof_dump_filename(), prof_dump_mseq, prof_dump_seq_mtx, and tsd_tsdn().
prof_postfork_child()
void prof_postfork_child (tsdn_t * tsdn)
Definition at line 3139 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_postfork_child(tsdn, &prof_thread_active_init_mtx);
         malloc_mutex_postfork_child(tsdn, &next_thr_uid_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_gdump_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_active_mtx);
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_postfork_child(tsdn, &gctx_locks[i]);
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_postfork_child(tsdn, &tdata_locks[i]);
         }
         malloc_mutex_postfork_child(tsdn, &tdatas_mtx);
         malloc_mutex_postfork_child(tsdn, &bt2gctx_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_dump_mtx);
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_postfork_child, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_mtx, prof_dump_seq_mtx, prof_gdump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thread_active_init_mtx, tdata_locks, and tdatas_mtx.
prof_postfork_parent()
void prof_postfork_parent (tsdn_t * tsdn)
Definition at line 3116 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_postfork_parent(tsdn,
             &prof_thread_active_init_mtx);
         malloc_mutex_postfork_parent(tsdn, &next_thr_uid_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_gdump_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_active_mtx);
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_postfork_parent(tsdn, &gctx_locks[i]);
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_postfork_parent(tsdn, &tdata_locks[i]);
         }
         malloc_mutex_postfork_parent(tsdn, &tdatas_mtx);
         malloc_mutex_postfork_parent(tsdn, &bt2gctx_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_dump_mtx);
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_postfork_parent, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_mtx, prof_dump_seq_mtx, prof_gdump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thread_active_init_mtx, tdata_locks, and tdatas_mtx.
prof_prefork0()
void prof_prefork0 (tsdn_t * tsdn)
Definition at line 3088 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_prefork(tsdn, &prof_dump_mtx);
         malloc_mutex_prefork(tsdn, &bt2gctx_mtx);
         malloc_mutex_prefork(tsdn, &tdatas_mtx);
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_prefork(tsdn, &tdata_locks[i]);
         }
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_prefork(tsdn, &gctx_locks[i]);
         }
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_prefork, opt_prof, prof_dump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, tdata_locks, and tdatas_mtx.
prof_prefork1()
void prof_prefork1 (tsdn_t * tsdn)
Definition at line 3105 of file prof.c.
{
     if (config_prof && opt_prof) {
         malloc_mutex_prefork(tsdn, &prof_active_mtx);
         malloc_mutex_prefork(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_prefork(tsdn, &prof_gdump_mtx);
         malloc_mutex_prefork(tsdn, &next_thr_uid_mtx);
         malloc_mutex_prefork(tsdn, &prof_thread_active_init_mtx);
     }
 }
References config_prof, malloc_mutex_prefork, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_seq_mtx, prof_gdump_mtx, and prof_thread_active_init_mtx.
prof_reset()
void prof_reset (tsd_t * tsd, size_t lg_sample)
Definition at line 2359 of file prof.c.
{
     prof_tdata_t *next;
     assert(lg_sample < (sizeof(uint64_t) << 3));
     malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_mtx);
     malloc_mutex_lock(tsd_tsdn(tsd), &tdatas_mtx);
     lg_prof_sample = lg_sample;
     next = NULL;
     do {
         prof_tdata_t *to_destroy = tdata_tree_iter(&tdatas, next,
             prof_tdata_reset_iter, (void *)tsd);
         if (to_destroy != NULL) {
             next = tdata_tree_next(&tdatas, to_destroy);
             prof_tdata_destroy_locked(tsd, to_destroy, false);
         } else {
             next = NULL;
         }
     } while (next != NULL);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tdatas_mtx);
     malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_mtx);
 }
References assert(), lg_prof_sample, malloc_mutex_lock(), malloc_mutex_unlock(), next(), NULL, prof_dump_mtx, prof_tdata_destroy_locked(), prof_tdata_reset_iter(), tdatas, tdatas_mtx, and tsd_tsdn().
prof_sample_threshold_update()
void prof_sample_threshold_update (prof_tdata_t * tdata)
Definition at line 1140 of file prof.c.
{
 #ifdef JEMALLOC_PROF
     if (!config_prof) {
         return;
     }
     if (lg_prof_sample == 0) {
         tsd_bytes_until_sample_set(tsd_fetch(), 0);
         return;
     }
     /*
      * Compute sample interval as a geometrically distributed random
      * variable with mean (2^lg_prof_sample).
      *
      *                             __        __
      *                             |  log(u)  |                     1
      * tdata->bytes_until_sample = | -------- |, where p = ---------------
      *                             | log(1-p) |             lg_prof_sample
      *                                                     2
      *
      * For more information on the math, see:
      *
      *   Non-Uniform Random Variate Generation
      *   Luc Devroye
      *   Springer-Verlag, New York, 1986
      *   pp 500
      *   (http://luc.devroye.org/rnbookindex.html)
      */
     uint64_t r = prng_lg_range_u64(&tdata->prng_state, 53);
     double u = (double)r * (1.0/9007199254740992.0L);
     uint64_t bytes_until_sample = (uint64_t)(log(u) /
         log(1.0 - (1.0 / (double)((uint64_t)1U << lg_prof_sample))))
         + (uint64_t)1U;
     if (bytes_until_sample > SSIZE_MAX) {
         bytes_until_sample = SSIZE_MAX;
     }
     tsd_bytes_until_sample_set(tsd_fetch(), bytes_until_sample);
 #endif
 }
References config_prof, lg_prof_sample, G3D::log(), prng_lg_range_u64(), prof_tdata_s::prng_state, SSIZE_MAX, and tsd_fetch().
Referenced by if(), and prof_tdata_init_impl().
prof_tdata_cleanup()
void prof_tdata_cleanup (tsd_t * tsd)
Definition at line 2386 of file prof.c.
{
     prof_tdata_t *tdata;
     if (!config_prof) {
         return;
     }
     tdata = tsd_prof_tdata_get(tsd);
     if (tdata != NULL) {
         prof_tdata_detach(tsd, tdata);
     }
 }
References config_prof, NULL, and prof_tdata_detach().
prof_tdata_init()
prof_tdata_t* prof_tdata_init (tsd_t * tsd)
Definition at line 2247 of file prof.c.
{
     return prof_tdata_init_impl(tsd, prof_thr_uid_alloc(tsd_tsdn(tsd)), 0,
         NULL, prof_thread_active_init_get(tsd_tsdn(tsd)));
 }
References NULL, prof_tdata_init_impl(), prof_thr_uid_alloc(), prof_thread_active_init_get(), and tsd_tsdn().
prof_tdata_reinit()
prof_tdata_t* prof_tdata_reinit (tsd_t * tsd, prof_tdata_t * tdata)
Definition at line 2321 of file prof.c.
{
     uint64_t thr_uid = tdata->thr_uid;
     uint64_t thr_discrim = tdata->thr_discrim + 1;
     char *thread_name = (tdata->thread_name != NULL) ?
         prof_thread_name_alloc(tsd_tsdn(tsd), tdata->thread_name) : NULL;
     bool active = tdata->active;
     prof_tdata_detach(tsd, tdata);
     return prof_tdata_init_impl(tsd, thr_uid, thr_discrim, thread_name,
         active);
 }
References prof_tdata_s::active, NULL, prof_tdata_detach(), prof_tdata_init_impl(), prof_thread_name_alloc(), prof_tdata_s::thr_discrim, prof_tdata_s::thr_uid, prof_tdata_s::thread_name, and tsd_tsdn().
prof_thread_active_get()
bool prof_thread_active_get (tsd_t * tsd)
Definition at line 2855 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return false;
     }
     return tdata->active;
 }
References prof_tdata_s::active, NULL, and prof_tdata_get().
prof_thread_active_init_get()
bool prof_thread_active_init_get (tsdn_t * tsdn)
Definition at line 2878 of file prof.c.
{
     bool active_init;
     malloc_mutex_lock(tsdn, &prof_thread_active_init_mtx);
     active_init = prof_thread_active_init;
     malloc_mutex_unlock(tsdn, &prof_thread_active_init_mtx);
     return active_init;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_thread_active_init, and prof_thread_active_init_mtx.
Referenced by prof_tdata_init().
prof_thread_active_init_set()
bool prof_thread_active_init_set (tsdn_t * tsdn, bool active_init)
Definition at line 2888 of file prof.c.
{
     bool active_init_old;
     malloc_mutex_lock(tsdn, &prof_thread_active_init_mtx);
     active_init_old = prof_thread_active_init;
     prof_thread_active_init = active_init;
     malloc_mutex_unlock(tsdn, &prof_thread_active_init_mtx);
     return active_init_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_thread_active_init, and prof_thread_active_init_mtx.
prof_thread_active_set()
bool prof_thread_active_set (tsd_t * tsd, bool active)
Definition at line 2866 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return true;
     }
     tdata->active = active;
     return false;
 }
References prof_tdata_s::active, NULL, and prof_tdata_get().
prof_thread_name_get()
const char* prof_thread_name_get (tsd_t * tsd)
Definition at line 2783 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return "";
     }
     return (tdata->thread_name != NULL ? tdata->thread_name : "");
 }
References NULL, prof_tdata_get(), and prof_tdata_s::thread_name.
Referenced by prof_try_log().
prof_thread_name_set()
int prof_thread_name_set (tsd_t * tsd, const char * thread_name)
Definition at line 2817 of file prof.c.
{
     prof_tdata_t *tdata;
     unsigned i;
     char *s;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return EAGAIN;
     }
     /* Validate input. */
     if (thread_name == NULL) {
         return EFAULT;
     }
     for (i = 0; thread_name[i] != '\0'; i++) {
         char c = thread_name[i];
         if (!isgraph(c) && !isblank(c)) {
             return EFAULT;
         }
     }
     s = prof_thread_name_alloc(tsd_tsdn(tsd), thread_name);
     if (s == NULL) {
         return EAGAIN;
     }
     if (tdata->thread_name != NULL) {
         idalloctm(tsd_tsdn(tsd), tdata->thread_name, NULL, NULL, true,
             true);
         tdata->thread_name = NULL;
     }
     if (strlen(s) > 0) {
         tdata->thread_name = s;
     }
     return 0;
 }
References mpq::c, idalloctm(), NULL, prof_tdata_get(), prof_thread_name_alloc(), prof_tdata_s::thread_name, and tsd_tsdn().
Variable Documentation
bt2gctx_mtx
malloc_mutex_t bt2gctx_mtx extern
Definition at line 193 of file prof.c.
Referenced by prof_boot2(), prof_enter(), prof_leave(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork0().
lg_prof_sample
size_t lg_prof_sample extern
Definition at line 73 of file prof.c.
Referenced by prof_boot2(), prof_dump_header_impl(), prof_leakcheck(), prof_log_emit_metadata(), prof_reset(), and prof_sample_threshold_update().
opt_lg_prof_interval
ssize_t opt_lg_prof_interval extern
Definition at line 37 of file prof.c.
Referenced by prof_boot1().
opt_lg_prof_sample
size_t opt_lg_prof_sample extern
Definition at line 36 of file prof.c.
Referenced by prof_boot2().
opt_prof
bool opt_prof extern
Definition at line 33 of file prof.c.
Referenced by prof_boot1(), prof_boot2(), prof_log_start(), prof_log_stop(), prof_mdump(), prof_postfork_child(), prof_postfork_parent(), prof_prefork0(), and prof_prefork1().
opt_prof_accum
bool opt_prof_accum extern
Definition at line 41 of file prof.c.
Referenced by prof_dump_gctx(), prof_gctx_should_destroy(), prof_malloc_sample_object(), prof_tctx_destroy(), prof_tctx_merge_gctx(), prof_tctx_merge_tdata(), prof_tctx_should_destroy(), and prof_tdata_merge_iter().
opt_prof_active
bool opt_prof_active extern
Definition at line 34 of file prof.c.
Referenced by prof_boot2().
opt_prof_final
bool opt_prof_final extern
Definition at line 39 of file prof.c.
Referenced by prof_boot2(), and prof_fdump().
opt_prof_gdump
bool opt_prof_gdump extern
Definition at line 38 of file prof.c.
Referenced by prof_boot1(), and prof_boot2().
opt_prof_leak
bool opt_prof_leak extern
Definition at line 40 of file prof.c.
Referenced by prof_boot1(), and prof_fdump().
opt_prof_log
bool opt_prof_log extern
Definition at line 42 of file prof.c.
Referenced by prof_boot2().
opt_prof_prefix
char opt_prof_prefix[ 1] extern
Definition at line 43 of file prof.c.
Referenced by prof_boot0(), prof_boot2(), prof_dump_filename(), prof_fdump(), prof_gdump(), prof_idump(), prof_log_start(), and prof_mdump().
opt_prof_thread_active_init
bool opt_prof_thread_active_init extern
Definition at line 35 of file prof.c.
Referenced by prof_boot2().
prof_active
bool prof_active extern
Definition at line 54 of file prof.c.
Referenced by prof_active_get(), prof_active_set(), and prof_boot2().
prof_dump_header
prof_dump_header_t* JET_MUTABLE prof_dump_header extern
Definition at line 1615 of file prof.c.
Referenced by prof_dump_file().
prof_dump_open
prof_dump_open_t* JET_MUTABLE prof_dump_open extern
Definition at line 1242 of file prof.c.
Referenced by prof_dump_file().
prof_gdump_val
bool prof_gdump_val extern
Definition at line 68 of file prof.c.
Referenced by prof_boot2(), prof_gdump_get(), and prof_gdump_set().
prof_interval
uint64_t prof_interval extern
Definition at line 71 of file prof.c.
Referenced by prof_boot1().