Azerotcore-wotlk: spell_sha_earth_shield Class Reference
spell_sha_earth_shield Class Reference
Private Member Functions
PrepareAuraScript (spell_sha_earth_shield)
bool Validate (SpellInfo const *) override
void CalculateAmount (AuraEffect const *, int32 &amount, bool &)
bool CheckProc (ProcEventInfo &)
void HandleProc (AuraEffect const *aurEff, ProcEventInfo &)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 518 of file spell_shaman.cpp.
Member Function Documentation
CalculateAmount()
void spell_sha_earth_shield::CalculateAmount (AuraEffect const * , int32 & amount, bool &) inline private
WORKAROUND this glyphe is a proc
Definition at line 527 of file spell_shaman.cpp.
     {
         if (Unit* caster = GetCaster())
         {
             int32 baseAmount = amount;
             amount = caster->SpellHealingBonusDone(GetUnitOwner(), GetSpellInfo(), amount, HEAL);
             // xinef: taken should be calculated at every heal
             //amount = GetUnitOwner()->SpellHealingBonusTaken(caster, GetSpellInfo(), amount, HEAL);
             // Glyph of Earth Shield
             if (AuraEffect* glyphe = caster->GetAuraEffect(SPELL_SHAMAN_GLYPH_OF_EARTH_SHIELD, EFFECT_0))
                 AddPct(amount, glyphe->GetAmount());
             // xinef: Improved Shields
             if ((baseAmount = amount - baseAmount))
                 if (AuraEffect* aurEff = caster->GetAuraEffect(SPELL_AURA_ADD_PCT_MODIFIER, SPELLFAMILY_SHAMAN, 19, EFFECT_1))
                 {
                     ApplyPct(baseAmount, aurEff->GetAmount());
                     amount += baseAmount;
                 }
         }
     }
References AddPct(), ApplyPct(), EFFECT_0, EFFECT_1, AuraScript::GetCaster(), AuraScript::GetSpellInfo(), AuraScript::GetUnitOwner(), HEAL, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_SHAMAN_GLYPH_OF_EARTH_SHIELD, and SPELLFAMILY_SHAMAN.
Referenced by Register().
CheckProc()
bool spell_sha_earth_shield::CheckProc (ProcEventInfo &) inline private
Definition at line 552 of file spell_shaman.cpp.
     {
         return !GetTarget()->HasSpellCooldown(SPELL_SHAMAN_EARTH_SHIELD_HEAL);
     }
References AuraScript::GetTarget(), Unit::HasSpellCooldown(), and SPELL_SHAMAN_EARTH_SHIELD_HEAL.
Referenced by Register().
HandleProc()
void spell_sha_earth_shield::HandleProc (AuraEffect const * aurEff, ProcEventInfo &) inline private
Definition at line 557 of file spell_shaman.cpp.
     {
         PreventDefaultAction();
         GetTarget()->CastCustomSpell(SPELL_SHAMAN_EARTH_SHIELD_HEAL, SPELLVALUE_BASE_POINT0, aurEff->GetAmount(), GetTarget(), true, nullptr, aurEff, GetCasterGUID());
         GetTarget()->AddSpellCooldown(SPELL_SHAMAN_EARTH_SHIELD_HEAL, 0, 3500);
     }
References Unit::AddSpellCooldown(), Unit::CastCustomSpell(), AuraEffect::GetAmount(), AuraScript::GetCasterGUID(), AuraScript::GetTarget(), AuraScript::PreventDefaultAction(), SPELL_SHAMAN_EARTH_SHIELD_HEAL, and SPELLVALUE_BASE_POINT0.
Referenced by Register().
PrepareAuraScript()
spell_sha_earth_shield::PrepareAuraScript (spell_sha_earth_shield) private
Register()
void spell_sha_earth_shield::Register () inline override private virtual
Implements _SpellScript.
Definition at line 564 of file spell_shaman.cpp.
     {
         DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_sha_earth_shield::CalculateAmount, EFFECT_0, SPELL_AURA_DUMMY);
         DoCheckProc += AuraCheckProcFn(spell_sha_earth_shield::CheckProc);
         OnEffectProc += AuraEffectProcFn(spell_sha_earth_shield::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
     }
References AuraCheckProcFn, AuraEffectCalcAmountFn, AuraEffectProcFn, CalculateAmount(), CheckProc(), AuraScript::DoCheckProc, AuraScript::DoEffectCalcAmount, EFFECT_0, HandleProc(), AuraScript::OnEffectProc, and SPELL_AURA_DUMMY.
Validate()
bool spell_sha_earth_shield::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 522 of file spell_shaman.cpp.
     {
         return ValidateSpellInfo({ SPELL_SHAMAN_EARTH_SHIELD_HEAL, SPELL_SHAMAN_GLYPH_OF_EARTH_SHIELD });
     }
References SPELL_SHAMAN_EARTH_SHIELD_HEAL, SPELL_SHAMAN_GLYPH_OF_EARTH_SHIELD, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_shaman.cpp