Azerotcore-wotlk: InstanceScript Class Reference
InstanceScript Class Reference
#include <InstanceScript.h>
Public Member Functions
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Static Public Member Functions
static std::string GetBossStateName (uint8 state)
Public Attributes
Map * instance
Protected Member Functions
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Static Private Member Functions
static void LoadObjectData (ObjectData const *creatureData, ObjectInfoMap &objectInfo)
Private Attributes
std::vector< BossInfo > bosses
DoorInfoMap doors
MinionInfoMap minions
ObjectInfoMap _creatureInfo
ObjectInfoMap _gameObjectInfo
ObjectGuidMap _objectGuids
uint32 completedEncounters
std::unordered_set< uint32 > _activatedAreaTriggers
Detailed Description
Definition at line 140 of file InstanceScript.h.
Constructor & Destructor Documentation
InstanceScript()
InstanceScript::InstanceScript (Map * map) inline explicit
Definition at line 143 of file InstanceScript.h.
 : instance(map), completedEncounters(0) {}
~InstanceScript()
InstanceScript::~InstanceScript () inline override
Definition at line 145 of file InstanceScript.h.
 {}
Member Function Documentation
AddDoor()
void InstanceScript::AddDoor (GameObject * door, bool add) protected
Definition at line 254 of file InstanceScript.cpp.
 {
     DoorInfoMapBounds range = doors.equal_range(door->GetEntry());
     if (range.first == range.second)
         return;
     for (; range.first != range.second; ++range.first)
     {
         DoorInfo const& data = range.first->second;
         if (add)
         {
             data.bossInfo->door[data.type].insert(door);
             switch (data.boundary)
             {
                 default:
                 case BOUNDARY_NONE:
                     break;
                 case BOUNDARY_N:
                 case BOUNDARY_S:
                     data.bossInfo->boundary[data.boundary] = door->GetPositionX();
                     break;
                 case BOUNDARY_E:
                 case BOUNDARY_W:
                     data.bossInfo->boundary[data.boundary] = door->GetPositionY();
                     break;
                 case BOUNDARY_NW:
                 case BOUNDARY_SE:
                     data.bossInfo->boundary[data.boundary] = door->GetPositionX() + door->GetPositionY();
                     break;
                 case BOUNDARY_NE:
                 case BOUNDARY_SW:
                     data.bossInfo->boundary[data.boundary] = door->GetPositionX() - door->GetPositionY();
                     break;
             }
         }
         else
             data.bossInfo->door[data.type].erase(door);
     }
     if (add)
         UpdateDoorState(door);
 }
References DoorInfo::bossInfo, BossInfo::boundary, DoorInfo::boundary, BOUNDARY_E, BOUNDARY_N, BOUNDARY_NE, BOUNDARY_NONE, BOUNDARY_NW, BOUNDARY_S, BOUNDARY_SE, BOUNDARY_SW, BOUNDARY_W, BossInfo::door, doors, Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), DoorInfo::type, and UpdateDoorState().
Referenced by instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate(), instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectCreate(), OnGameObjectCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectCreate(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectCreate(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectRemove(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectRemove(), instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectRemove(), OnGameObjectRemove(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectRemove(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectRemove(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectRemove(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectRemove(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectRemove(), instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectRemove(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectRemove(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectRemove(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectRemove(), and instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectRemove().
AddMinion()
void InstanceScript::AddMinion (Creature * minion, bool add) protected
Definition at line 298 of file InstanceScript.cpp.
 {
     MinionInfoMap::iterator itr = minions.find(minion->GetEntry());
     if (itr == minions.end())
         return;
     if (add)
         itr->second.bossInfo->minion.insert(minion);
     else
         itr->second.bossInfo->minion.erase(minion);
 }
References Object::GetEntry(), and minions.
Referenced by OnCreatureCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureCreate(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureCreate(), OnCreatureRemove(), instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureRemove(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureRemove(), and instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureRemove().
AddObject() [1/3]
void InstanceScript::AddObject (Creature * obj, bool add) protected
Definition at line 220 of file InstanceScript.cpp.
 {
     ObjectInfoMap::const_iterator j = _creatureInfo.find(obj->GetEntry());
     if (j != _creatureInfo.end())
     {
         AddObject(obj, j->second, add);
     }
 }
References _creatureInfo, and Object::GetEntry().
Referenced by AddObject(), OnCreatureCreate(), OnCreatureRemove(), OnGameObjectCreate(), and OnGameObjectRemove().
AddObject() [2/3]
void InstanceScript::AddObject (GameObject * obj, bool add) protected
Definition at line 229 of file InstanceScript.cpp.
 {
     ObjectInfoMap::const_iterator j = _gameObjectInfo.find(obj->GetEntry());
     if (j != _gameObjectInfo.end())
     {
         AddObject(obj, j->second, add);
     }
 }
References _gameObjectInfo, AddObject(), and Object::GetEntry().
AddObject() [3/3]
void InstanceScript::AddObject (WorldObject * obj, uint32 type, bool add) protected
Definition at line 238 of file InstanceScript.cpp.
 {
     if (add)
     {
         _objectGuids[type] = obj->GetGUID();
     }
     else
     {
         ObjectGuidMap::iterator i = _objectGuids.find(type);
         if (i != _objectGuids.end() && i->second == obj->GetGUID())
         {
             _objectGuids.erase(i);
         }
     }
 }
References _objectGuids, and Object::GetGUID().
CheckAchievementCriteriaMeet()
bool InstanceScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * = nullptr, uint32 = 0) virtual
Reimplemented in instance_oculus::instance_oculus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, and instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript.
Definition at line 503 of file InstanceScript.cpp.
 {
     LOG_ERROR("scripts.ai", "Achievement system call InstanceScript::CheckAchievementCriteriaMeet but instance script for map %u not have implementation for achievement criteria %u",
                    instance->GetId(), criteria_id);
     return false;
 }
References Map::GetId(), instance, and LOG_ERROR.
Referenced by AchievementCriteriaData::Meets().
CheckRequiredBosses()
virtual bool InstanceScript::CheckRequiredBosses (uint32 , Player const * = nullptr) const inline virtual
Reimplemented in instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, and instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript.
Definition at line 232 of file InstanceScript.h.
 { return true; }
Referenced by BossAI::_EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::AttackStart(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), and boss_rotface::boss_rotfaceAI::EnterCombat().
CreatureLooted()
virtual void InstanceScript::CreatureLooted (Creature * , LootType) inline virtual
Reimplemented in instance_blackrock_spire::instance_blackrock_spireMapScript.
Definition at line 156 of file InstanceScript.h.
 {}
DoAction()
virtual void InstanceScript::DoAction (int32) inline virtual
Reimplemented in instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, and instance_molten_core::instance_molten_core_InstanceMapScript.
Definition at line 251 of file InstanceScript.h.
 {}
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_sartharion_dragonAI::JustDied(), boss_sartharion_dragonAI::Reset(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies(), and npc_core_rager::npc_core_ragerAI::UpdateAI().
DoCastSpellOnPlayers()
void InstanceScript::DoCastSpellOnPlayers (uint32 spell)
Definition at line 493 of file InstanceScript.cpp.
 {
     Map::PlayerList const& PlayerList = instance->GetPlayers();
     if (!PlayerList.isEmpty())
         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
             if (Player* player = i->GetSource())
                 player->CastSpell(player, spell, true);
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
Referenced by boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::SetData(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetData(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update(), and boss_icehowl::boss_icehowlAI::UpdateAI().
DoRemoveAurasDueToSpellOnPlayers()
void InstanceScript::DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
Definition at line 475 of file InstanceScript.cpp.
 {
     Map::PlayerList const& PlayerList = instance->GetPlayers();
     if (!PlayerList.isEmpty())
     {
         for (Map::PlayerList::const_iterator itr = PlayerList.begin(); itr != PlayerList.end(); ++itr)
         {
             if (Player* player = itr->GetSource())
             {
                 player->RemoveAurasDueToSpell(spell);
                 if (Pet* pet = player->GetPet())
                     pet->RemoveAurasDueToSpell(spell);
             }
         }
     }
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
Referenced by boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CleanAuras(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ClearInstance(), boss_kalecgos::boss_kalecgosAI::ClearPlayerAuras(), boss_hodir::boss_hodirAI::DamageTaken(), boss_twin_valkyrAI::DoAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_amanitar::boss_amanitarAI::EnterEvadeMode(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), boss_vexallus::boss_vexallusAI::JustDied(), boss_amanitar::boss_amanitarAI::JustDied(), boss_twin_valkyrAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_toravon::boss_toravonAI::JustDied(), boss_moroes::boss_moroesAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerEnter(), boss_vexallus::boss_vexallusAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_sartharion::boss_sartharionAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_hodir::boss_hodirAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), and boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI().
DoRespawnGameObject()
void InstanceScript::DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn = MINUTE)
Definition at line 391 of file InstanceScript.cpp.
 {
     if (GameObject* go = instance->GetGameObject(uiGuid))
     {
         //not expect any of these should ever be handled
         if (go->GetGoType() == GAMEOBJECT_TYPE_FISHINGNODE || go->GetGoType() == GAMEOBJECT_TYPE_DOOR ||
                 go->GetGoType() == GAMEOBJECT_TYPE_BUTTON || go->GetGoType() == GAMEOBJECT_TYPE_TRAP)
             return;
         if (go->isSpawned())
             return;
         go->SetRespawnTime(uiTimeToDespawn);
     }
 }
References GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_TRAP, Map::GetGameObject(), and instance.
Referenced by instance_molten_core::instance_molten_core_InstanceMapScript::SetBossState(), instance_karazhan::instance_karazhan_InstanceMapScript::SetBossState(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), and instance_oculus::instance_oculus_InstanceMapScript::SetData().
DoSendNotifyToInstance()
void InstanceScript::DoSendNotifyToInstance (char const * format, ...)
Definition at line 424 of file InstanceScript.cpp.
 {
     InstanceMap::PlayerList const& players = instance->GetPlayers();
     if (!players.isEmpty())
     {
         va_list ap;
         va_start(ap, format);
         char buff[1024];
         vsnprintf(buff, 1024, format, ap);
         va_end(ap);
         for (Map::PlayerList::const_iterator i = players.begin(); i != players.end(); ++i)
             if (Player* player = i->GetSource())
                 player->GetSession()->SendNotification("%s", buff);
     }
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
DoStartTimedAchievement()
void InstanceScript::DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
Definition at line 453 of file InstanceScript.cpp.
 {
     Map::PlayerList const& PlayerList = instance->GetPlayers();
     if (!PlayerList.isEmpty())
         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
             if (Player* player = i->GetSource())
                 player->StartTimedAchievement(type, entry);
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
Referenced by boss_freya::boss_freyaAI::DoAction(), boss_kologarn::boss_kologarnAI::DoAction(), boss_onyxia::boss_onyxiaAI::EnterCombat(), boss_volazj::boss_volazjAI::EnterCombat(), boss_anub_arak::boss_anub_arakAI::EnterCombat(), boss_twin_valkyrAI::EnterCombat(), boss_loken::boss_lokenAI::EnterCombat(), boss_maiden_of_grief::boss_maiden_of_griefAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_skadi::boss_skadiAI::EnterCombat(), boss_patchwerk::boss_patchwerkAI::EnterCombat(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), boss_anubrekhan::boss_anubrekhanAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_oculus::instance_oculus_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), and boss_malygos::boss_malygosAI::UpdateAI().
DoStopTimedAchievement()
void InstanceScript::DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
Definition at line 464 of file InstanceScript.cpp.
 {
     Map::PlayerList const& PlayerList = instance->GetPlayers();
     if (!PlayerList.isEmpty())
         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
             if (Player* player = i->GetSource())
                 player->RemoveTimedAchievement(type, entry);
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
Referenced by boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_onyxia::boss_onyxiaAI::EnterCombat(), boss_onyxia::boss_onyxiaAI::Reset(), boss_volazj::boss_volazjAI::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_malygos::boss_malygosAI::Reset(), boss_loken::boss_lokenAI::Reset(), boss_maiden_of_grief::boss_maiden_of_griefAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_skadi::boss_skadiAI::Reset(), and instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData().
DoUpdateAchievementCriteria()
void InstanceScript::DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1 = 0, uint32 miscValue2 = 0, Unit * unit = nullptr)
Definition at line 442 of file InstanceScript.cpp.
 {
     Map::PlayerList const& PlayerList = instance->GetPlayers();
     if (!PlayerList.isEmpty())
         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
             if (Player* player = i->GetSource())
                 player->UpdateAchievementCriteria(type, miscValue1, miscValue2, unit);
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, and LinkedListHead::isEmpty().
Referenced by boss_paletress::boss_paletressAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_freya::boss_freyaAI::DoAction(), boss_archimonde::boss_archimondeAI::JustDied(), boss_malygos::boss_malygosAI::JustDied(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), boss_razorscale::boss_razorscaleAI::KilledUnit(), boss_svala::boss_svalaAI::KilledUnit(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), and boss_mimiron::boss_mimironAI::UpdateAI().
DoUpdateWorldState()
void InstanceScript::DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
Definition at line 407 of file InstanceScript.cpp.
 {
     Map::PlayerList const& lPlayers = instance->GetPlayers();
     if (!lPlayers.isEmpty())
     {
         for (Map::PlayerList::const_iterator itr = lPlayers.begin(); itr != lPlayers.end(); ++itr)
             if (Player* player = itr->GetSource())
                 player->SendUpdateWorldState(uiStateId, uiStateData);
     }
     else
     {
         LOG_DEBUG("scripts.ai", "DoUpdateWorldState attempt send data but no players in map.");
     }
 }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), instance, LinkedListHead::isEmpty(), and LOG_DEBUG.
Referenced by instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::AddWave1(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::DoWipe1(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HandleDropAttempt(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Load(), instance_ulduar::instance_ulduar_InstanceMapScript::Load(), hyjalAI::Reset(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState(), instance_zulaman::instance_zulaman_InstanceMapScript::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_oculus::instance_oculus_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), hyjalAI::StartEvent(), hyjalAI::SummonNextWave(), instance_zulaman::instance_zulaman_InstanceMapScript::Update(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), hyjalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), and instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::UpdateEventState().
DoUseDoorOrButton()
void InstanceScript::DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime = 0, bool useAlternativeState = false)
Definition at line 370 of file InstanceScript.cpp.
 {
     if (!uiGuid)
         return;
     GameObject* go = instance->GetGameObject(uiGuid);
     if (go)
     {
         if (go->GetGoType() == GAMEOBJECT_TYPE_DOOR || go->GetGoType() == GAMEOBJECT_TYPE_BUTTON)
         {
             if (go->getLootState() == GO_READY)
                 go->UseDoorOrButton(uiWithRestoreTime, bUseAlternativeState);
             else if (go->getLootState() == GO_ACTIVATED)
                 go->ResetDoorOrButton();
         }
         else
             LOG_ERROR("scripts.ai", "SD2: Script call DoUseDoorOrButton, but gameobject entry %u is type %u.", go->GetEntry(), go->GetGoType());
     }
 }
References GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_DOOR, Object::GetEntry(), Map::GetGameObject(), GameObject::GetGoType(), GameObject::getLootState(), GO_ACTIVATED, GO_READY, instance, LOG_ERROR, GameObject::ResetDoorOrButton(), and GameObject::UseDoorOrButton().
Referenced by instance_stratholme::instance_stratholme_InstanceMapScript::gate_delay(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::SetData(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::SetData(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), and npc_barnes::npc_barnesAI::WaypointReached().
FillInitialWorldStates()
virtual void InstanceScript::FillInitialWorldStates (WorldPacket &) inline virtual
Reimplemented in instance_ulduar::instance_ulduar_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, and instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript.
Definition at line 241 of file InstanceScript.h.
 {}
Referenced by Player::SendInitWorldStates().
GetBossBoundary()
BossBoundaryMap const* InstanceScript::GetBossBoundary (uint32 id) const inline
Definition at line 224 of file InstanceScript.h.
 { return id < bosses.size() ? &bosses[id].boundary : nullptr; }
References bosses.
GetBossInfo()
BossInfo const* InstanceScript::GetBossInfo (uint32 id) const inline
Definition at line 225 of file InstanceScript.h.
 { return &bosses[id]; }
References bosses.
Referenced by instance_nexus::instance_nexus_InstanceMapScript::SetBossState().
GetBossSaveData()
std::string InstanceScript::GetBossSaveData () protected
Definition at line 362 of file InstanceScript.cpp.
 {
     std::ostringstream saveStream;
     for (std::vector<BossInfo>::iterator i = bosses.begin(); i != bosses.end(); ++i)
         saveStream << (uint32)i->state << ' ';
     return saveStream.str();
 }
References bosses.
Referenced by GetSaveData(), instance_blackrock_spire::instance_blackrock_spireMapScript::GetSaveData(), instance_molten_core::instance_molten_core_InstanceMapScript::GetSaveData(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetSaveData(), instance_zulgurub::instance_zulgurub_InstanceMapScript::GetSaveData(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetSaveData(), instance_ahnkahet::instance_ahnkahet_InstanceScript::GetSaveData(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::GetSaveData(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::GetSaveData(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::GetSaveData(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::GetSaveData(), instance_gundrak::instance_gundrak_InstanceMapScript::GetSaveData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetSaveData(), instance_naxxramas::instance_naxxramas_InstanceMapScript::GetSaveData(), instance_nexus::instance_nexus_InstanceMapScript::GetSaveData(), instance_auchenai_crypts::instance_auchenai_crypts_InstanceMapScript::GetSaveData(), instance_mana_tombs::instance_mana_tombs_InstanceMapScript::GetSaveData(), instance_black_temple::instance_black_temple_InstanceMapScript::GetSaveData(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetSaveData(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::GetSaveData(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::GetSaveData(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::GetSaveData(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetSaveData(), instance_arcatraz::instance_arcatraz_InstanceMapScript::GetSaveData(), instance_the_botanica::instance_the_botanica_InstanceMapScript::GetSaveData(), instance_the_eye::instance_the_eye_InstanceMapScript::GetSaveData(), and instance_mechanar::instance_mechanar_InstanceMapScript::GetSaveData().
GetBossState()
EncounterState InstanceScript::GetBossState (uint32 id) const inline
Definition at line 222 of file InstanceScript.h.
 { return id < bosses.size() ? bosses[id].state : TO_BE_DECIDED; }
References bosses, and TO_BE_DECIDED.
Referenced by npc_hive_zara_larva::npc_hive_zara_larvaAI::AttackStart(), boss_felmyst::boss_felmystAI::boss_felmystAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::boss_wrath_scryer_soccothratesAI(), spell_serpentshrine_cavern_coilfang_water::spell_serpentshrine_cavern_coilfang_water_AuraScript::CalcPeriodic(), npc_gunship_mage::npc_gunship_mageAI::CanAIAttack(), npc_gunship_rocketeer::npc_gunship_rocketeerAI::CanAIAttack(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), npc_gunship_gunner::npc_gunship_gunnerAI::CanAIAttack(), boss_majordomo::boss_majordomoAI::CanAIAttack(), boss_keristrasza::boss_keristraszaAI::CanRemovePrison(), instance_naxxramas::instance_naxxramas_InstanceMapScript::CheckAchievementCriteriaMeet(), spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript::CheckAreaTarget(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckCrimsonHalls(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckFrostwingHalls(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLichKingAvailability(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLowerSpire(), instance_molten_core::instance_molten_core_InstanceMapScript::CheckMajordomoExecutus(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckPlagueworks(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::CheckRequiredBosses(), npc_core_rager::npc_core_ragerAI::DamageTaken(), npc_gunship::npc_gunshipAI::DamageTaken(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), boss_sartharion_dragonAI::EnterCombat(), boss_hakkar::boss_hakkarAI::EnterCombat(), npc_crystalline_frayer::npc_crystalline_frayerAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), SendEncounterUnit::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HandleDropAttempt(), instance_commandscript::HandleInstanceGetBossStateCommand(), spell_serpentshrine_cavern_coilfang_water::spell_serpentshrine_cavern_coilfang_water_AuraScript::HandlePeriodic(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), go_suppression_device::go_suppression_deviceAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::InitializeAI(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::IsEncounterInProgress(), instance_naxxramas::instance_naxxramas_InstanceMapScript::IsEncounterInProgress(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), boss_sartharion_dragonAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), boss_sartharion_dragonAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::Load(), npc_hive_zara_larva::npc_hive_zara_larvaAI::MoveInLineOfSight(), npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::npc_crok_scourgebaneAI(), npc_madrigosa::npc_madrigosaAI::npc_madrigosaAI(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnPlayerEnter(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerEnter(), at_icc_saurfang_portal::OnTrigger(), at_thaddius_entrance::OnTrigger(), at_blackrock_stadium::OnTrigger(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), spell_dreamwalker_nightmare_cloud::spell_dreamwalker_nightmare_cloud_AuraScript::PeriodicTick(), instance_blackrock_spire::instance_blackrock_spireMapScript::ProcessEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), boss_gyth::boss_gythAI::Reset(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), npc_core_rager::npc_core_ragerAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), npc_akama_illidan::npc_akama_illidanAI::Reset(), npc_akama_shade::npc_akamaAI::Reset(), boss_sartharion::boss_sartharionAI::RespawnDragons(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), instance_blackrock_spire::instance_blackrock_spireMapScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetData(), instance_gundrak::instance_gundrak_InstanceMapScript::SetData(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), instance_molten_core::instance_molten_core_InstanceMapScript::SummonMajordomoExecutus(), instance_blackrock_spire::instance_blackrock_spireMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), npc_hive_zara_larva::npc_hive_zara_larvaAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_gunship_mage::npc_gunship_mageAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), and npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI().
GetBossStateName()
std::string InstanceScript::GetBossStateName (uint8 state) static
Definition at line 560 of file InstanceScript.cpp.
 {
     // See enum EncounterState in InstanceScript.h
     switch (state)
     {
         case NOT_STARTED:
             return "NOT_STARTED";
         case IN_PROGRESS:
             return "IN_PROGRESS";
         case FAIL:
             return "FAIL";
         case DONE:
             return "DONE";
         case SPECIAL:
             return "SPECIAL";
         case TO_BE_DECIDED:
             return "TO_BE_DECIDED";
         default:
             return "INVALID";
     }
 }
References DONE, FAIL, IN_PROGRESS, NOT_STARTED, SPECIAL, and TO_BE_DECIDED.
Referenced by instance_commandscript::HandleInstanceGetBossStateCommand(), instance_commandscript::HandleInstanceSetBossStateCommand(), and SmartScript::ProcessAction().
GetCompletedEncounterMask()
uint32 InstanceScript::GetCompletedEncounterMask () const inline
Definition at line 237 of file InstanceScript.h.
 { return completedEncounters; }
References completedEncounters.
Referenced by InstanceMap::AddPlayerToMap().
GetCreature()
Creature * InstanceScript::GetCreature (uint32 type)
Definition at line 90 of file InstanceScript.cpp.
 {
     return instance->GetCreature(GetObjectGuid(type));
 }
References Map::GetCreature(), GetObjectGuid(), and instance.
Referenced by instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnCreatureCreate().
GetEncounterCount()
uint32 InstanceScript::GetEncounterCount () const inline
Definition at line 243 of file InstanceScript.h.
 { return bosses.size(); }
References bosses.
Referenced by instance_commandscript::HandleInstanceGetBossStateCommand(), and instance_commandscript::HandleInstanceSetBossStateCommand().
GetGameObject()
GameObject * InstanceScript::GetGameObject (uint32 type)
Definition at line 95 of file InstanceScript.cpp.
 {
     return instance->GetGameObject(GetObjectGuid(type));
 }
References Map::GetGameObject(), GetObjectGuid(), and instance.
GetGuidData()
ObjectGuid InstanceScript::GetGuidData (uint32 type) const override virtual
Reimplemented from ZoneScript.
Reimplemented in instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, and instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript.
Definition at line 85 of file InstanceScript.cpp.
 {
     return GetObjectGuid(type);
 }
References GetObjectGuid().
Referenced by boss_sjonnir::boss_sjonnirAI::ActivatePipe(), boss_freya_summons::boss_freya_summonsAI::boss_freya_summonsAI(), boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI(), boss_tyrannus::boss_tyrannusAI::boss_tyrannusAI(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom(), violet_hold_trashAI::ClearDoorSealAura(), boss_mimiron::boss_mimironAI::CloseDoorAndButton(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::DamageDealt(), npc_mograine::npc_mograineAI::DamageTaken(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_twilight_halion::boss_twilight_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), hyjalAI::DeSpawnVeins(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), npc_hor_lich_king::npc_hor_lich_kingAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), npc_argent_captainAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), npc_molten_golem::npc_molten_golemAI::DoAction(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), npc_rocknot::npc_rocknotAI::DoGo(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), boss_kiljaeden::boss_kiljaedenAI::EmpowerOrb(), boss_malchezaar::boss_malchezaarAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::EnterCombat(), npc_risen_archmage::npc_risen_archmageAI::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_illidari_council_memberAI::EnterCombat(), boss_the_maker::boss_the_makerAI::EnterCombat(), npc_buru_egg::npc_buru_eggAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_priestess_lackey_commonAI::EnterCombat(), boss_sacrolash::boss_sacrolashAI::EnterCombat(), boss_alythess::boss_alythessAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_four_horsemen::boss_four_horsemenAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_heigan::boss_heiganAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), boss_loatheb::boss_loathebAI::EnterCombat(), boss_maexxna::boss_maexxnaAI::EnterCombat(), boss_noth::boss_nothAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::EnterCombat(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::EnterCombat(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::EnterCombat(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), npc_erekem_guard::npc_erekem_guardAI::EnterCombat(), boss_priestess_lackey_commonAI::EnterEvadeMode(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::EnterEvadeMode(), boss_sacrolash::boss_sacrolashAI::EnterEvadeMode(), boss_alythess::boss_alythessAI::EnterEvadeMode(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterEvadeMode(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), npc_tirion_fordring_tft::npc_tirion_fordringAI::EnterEvadeMode(), npc_argent_captainAI::EnterEvadeMode(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::FilterTargets(), boss_erekem::boss_erekemAI::GetChainHealTargetGUID(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::GetHarpoonGunIdForThisHFS(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::GetKelidan(), boss_twinemperorsAI::GetOtherBoss(), boss_twin_valkyrAI::GetSister(), boss_thorim::boss_thorimAI::GetThorimObject(), boss_netherspite::boss_netherspiteAI::HandleDoors(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), npc_grimstone::npc_grimstoneAI::HandleGameObject(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), boss_nightbane::boss_nightbaneAI::HandleTerraceDoors(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), go_troll_cage::go_troll_cageAI::initBlyCrewMember(), boss_malchezaar::boss_malchezaarAI::Initialize(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_aeonus::boss_aeonusAI::InitializeAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::InitializeAI(), IsEncounterComplete(), npc_direbrew_minion::npc_direbrew_minionAI::IsSummonedBy(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::IsSummonedBy(), npc_raging_spirit::npc_raging_spiritAI::IsSummonedBy(), npc_suppresser::npc_suppresserAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_malchezaar::boss_malchezaarAI::JustDied(), boss_shade_of_aran::boss_aranAI::JustDied(), npc_kilrek::npc_kilrekAI::JustDied(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustDied(), npc_zulian_prowler::npc_zulian_prowlerAI::JustDied(), npc_buru_egg::npc_buru_eggAI::JustDied(), boss_kurinnaxx::boss_kurinnaxxAI::JustDied(), boss_sartharion_dragonAI::JustDied(), npc_memory::npc_memoryAI::JustDied(), boss_jormungarAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), npc_little_ooze::npc_little_oozeAI::JustDied(), npc_big_ooze::npc_big_oozeAI::JustDied(), npc_raging_spirit::npc_raging_spiritAI::JustDied(), npc_spirit_warden::npc_spirit_wardenAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_thaddius_summon::boss_thaddius_summonAI::JustDied(), boss_drakos::boss_drakosAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), brann_bronzebeard::brann_bronzebeardAI::JustDied(), boss_steelbreaker::boss_steelbreakerAI::JustDied(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustDied(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::JustDied(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::JustDied(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::JustDied(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::JustDied(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::JustDied(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_xt002::boss_xt002AI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::JustDied(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustDied(), npc_massive_jormungar::npc_massive_jormungarAI::JustDied(), npc_ferocious_rhino::npc_ferocious_rhinoAI::JustDied(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::JustDied(), npc_frenzied_worgen::npc_frenzied_worgenAI::JustDied(), boss_skadi::boss_skadiAI::JustDied(), npc_ichor_globule::npc_ichor_globuleAI::JustDied(), violet_hold_trashAI::JustDied(), npc_akama_shade::npc_akamaAI::JustDied(), boss_illidari_council_memberAI::JustDied(), boss_broggok::boss_broggokAI::JustDied(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::JustDied(), boss_the_maker::boss_the_makerAI::JustDied(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustDied(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::JustDied(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_twilight_halion::boss_twilight_halionAI::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::JustDied(), boss_aeonus::boss_aeonusAI::JustReachedHome(), boss_halion::boss_halionAI::JustReachedHome(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), npc_buru_egg::npc_buru_eggAI::JustSummoned(), boss_priestess_lackey_commonAI::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), npc_hive_zara_larva::npc_hive_zara_larvaAI::MovementInform(), npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_sergeant_bly::npc_sergeant_blyAI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_big_ooze::npc_big_oozeAI::npc_big_oozeAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::npc_lesser_doomguardAI(), npc_little_ooze::npc_little_oozeAI::npc_little_oozeAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_towering_infernal::npc_towering_infernalAI::npc_towering_infernalAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), achievement_yogg_saron_darkness::OnCheck(), achievement_yogg_saron_he_waits_dreaming::OnCheck(), go_palehoof_sphere::OnGossipHello(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_harpoon_canon::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipSelect(), at_thaddius_entrance::OnTrigger(), at_tyrannus_event_starter::OnTrigger(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), IgbTeleportOnVictoryCheck::operator()(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_shade_of_aran::boss_aranAI::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_ancient_wisp::npc_ancient_wispAI::Reset(), boss_tyrannus::boss_tyrannusAI::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_heigan::boss_heiganAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_xt002::boss_xt002AI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Reset(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Reset(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_the_maker::boss_the_makerAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::ResetEvent(), boss_mimiron::boss_mimironAI::ResetGameObjects(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::ResetOrbs(), RespawnAssemblyOfIron(), boss_sartharion::boss_sartharionAI::RespawnDragons(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::SelectCouncilMember(), boss_svala::boss_svalaAI::SetData(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetGate(), npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID(), boss_kaelthas::boss_kaelthasAI::SetRoomState(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), npc_sergeant_bly::npc_sergeant_blyAI::switchFactionIfAlive(), brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul(), npc_rocknot::npc_rocknotAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), npc_healing_ward::npc_healing_wardAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), npc_ichor_globule::npc_ichor_globuleAI::UpdateAI(), npc_suppresser::npc_suppresserAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes(), npc_arthas::npc_arthasAI::WaypointReached(), npc_barnes::npc_barnesAI::WaypointReached(), boss_anetheron::boss_anetheronAI::WaypointReached(), boss_azgalor::boss_azgalorAI::WaypointReached(), boss_kazrogal::boss_kazrogalAI::WaypointReached(), boss_rage_winterchill::boss_rage_winterchillAI::WaypointReached(), npc_giant_infernal::npc_giant_infernalAI::WaypointReached(), npc_abomination::npc_abominationAI::WaypointReached(), npc_ghoul::npc_ghoulAI::WaypointReached(), npc_necromancer::npc_necromancerAI::WaypointReached(), npc_banshee::npc_bansheeAI::WaypointReached(), npc_crypt_fiend::npc_crypt_fiendAI::WaypointReached(), npc_fel_stalker::npc_fel_stalkerAI::WaypointReached(), npc_frost_wyrm::npc_frost_wyrmAI::WaypointReached(), npc_gargoyle::npc_gargoyleAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached(), and npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart().
GetObjectGuid()
ObjectGuid InstanceScript::GetObjectGuid (uint32 type) const
Definition at line 73 of file InstanceScript.cpp.
 {
     ObjectGuidMap::const_iterator i = _objectGuids.find(type);
     if (i != _objectGuids.end())
     {
         return i->second;
     }
     return ObjectGuid::Empty;
 }
References _objectGuids, and ObjectGuid::Empty.
Referenced by GetCreature(), GetGameObject(), and GetGuidData().
GetSaveData()
virtual std::string InstanceScript::GetSaveData () inline virtual
Reimplemented in instance_mechanar::instance_mechanar_InstanceMapScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_the_botanica::instance_the_botanica_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_mana_tombs::instance_mana_tombs_InstanceMapScript, instance_auchenai_crypts::instance_auchenai_crypts_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_deadmines::instance_deadmines_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, and instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript.
Definition at line 159 of file InstanceScript.h.
 { return GetBossSaveData(); }
References GetBossSaveData().
Referenced by SaveToDB().
HandleGameObject()
void InstanceScript::HandleGameObject (ObjectGuid guid, bool open, GameObject * go = nullptr)
Definition at line 100 of file InstanceScript.cpp.
 {
     if (!go)
         go = instance->GetGameObject(GUID);
     if (go)
         go->SetGoState(open ? GO_STATE_ACTIVE : GO_STATE_READY);
     else
     {
         LOG_DEBUG("scripts.ai", "InstanceScript: HandleGameObject failed");
     }
 }
References Map::GetGameObject(), GO_STATE_ACTIVE, GO_STATE_READY, instance, LOG_DEBUG, and GameObject::SetGoState().
Referenced by instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ActivateCell(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::AddWave1(), instance_zulaman::instance_zulaman_InstanceMapScript::CheckInstanceStatus(), boss_taldaram::boss_taldaramAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::DoWipe1(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), boss_malchezaar::boss_malchezaarAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), boss_the_maker::boss_the_makerAI::EnterCombat(), npc_grimstone::npc_grimstoneAI::HandleGameObject(), boss_nightbane::boss_nightbaneAI::HandleTerraceDoors(), boss_malchezaar::boss_malchezaarAI::Initialize(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), boss_malchezaar::boss_malchezaarAI::JustDied(), boss_shade_of_aran::boss_aranAI::JustDied(), boss_skadi::boss_skadiAI::JustDied(), boss_broggok::boss_broggokAI::JustDied(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::JustDied(), boss_the_maker::boss_the_makerAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_deadmines::instance_deadmines_InstanceMapScript::OnGameObjectCreate(), instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::OnGameObjectCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_maraudon::instance_maraudon_InstanceMapScript::OnGameObjectCreate(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnGameObjectCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnGameObjectCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnGameObjectCreate(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), boss_shade_of_aran::boss_aranAI::Reset(), boss_the_maker::boss_the_makerAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisons(), instance_karazhan::instance_karazhan_InstanceMapScript::SetBossState(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetBossState(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetBossState(), instance_arcatraz::instance_arcatraz_InstanceMapScript::SetBossState(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SetData(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_scholomance::instance_scholomance_InstanceMapScript::SetData(), instance_uldaman::instance_uldaman_InstanceMapScript::SetData(), instance_zulaman::instance_zulaman_InstanceMapScript::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::SetData(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::SetData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData(), instance_steam_vault::instance_steam_vault_InstanceMapScript::SetData(), instance_arcatraz::instance_arcatraz_InstanceMapScript::SetData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::SetData(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::SetData(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetGate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::TombOfSevenReset(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), and instance_blood_furnace::instance_blood_furnace_InstanceMapScript::UpdateBroggokEvent().
Initialize()
virtual void InstanceScript::Initialize () inline virtual
Reimplemented in instance_the_eye::instance_the_eye_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_deadmines::instance_deadmines_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, and instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript.
Definition at line 150 of file InstanceScript.h.
 {}
Referenced by InstanceMap::CreateInstanceScript().
IsAreaTriggerDone()
bool InstanceScript::IsAreaTriggerDone (uint32 id) const inline
Definition at line 248 of file InstanceScript.h.
 { return _activatedAreaTriggers.find(id) != _activatedAreaTriggers.end(); }
References _activatedAreaTriggers.
IsEncounterInProgress()
bool InstanceScript::IsEncounterInProgress () const virtual
Reimplemented in instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, and instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript.
Definition at line 112 of file InstanceScript.cpp.
 {
     for (std::vector<BossInfo>::const_iterator itr = bosses.begin(); itr != bosses.end(); ++itr)
         if (itr->state == IN_PROGRESS)
             return true;
     return false;
 }
References bosses, and IN_PROGRESS.
Referenced by InstanceMap::CannotEnter(), Spell::EffectSanctuary(), spell_teron_gorefiend_shadow_of_death::spell_teron_gorefiend_shadow_of_death_AuraScript::HandleEffectRemove(), AuraEffect::HandleFeignDeath(), WorldSession::HandleSetRaidDifficultyOpcode(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), and npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality().
Load()
virtual void InstanceScript::Load (char const * data) inline virtual
Reimplemented in instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, instance_deadmines::instance_deadmines_InstanceMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_the_botanica::instance_the_botanica_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_mana_tombs::instance_mana_tombs_InstanceMapScript, instance_auchenai_crypts::instance_auchenai_crypts_InstanceMapScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, and instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript.
Definition at line 153 of file InstanceScript.h.
 { LoadBossState(data); }
References LoadBossState().
Referenced by InstanceMap::CreateInstanceScript().
LoadBossState()
std::string InstanceScript::LoadBossState (char const * data) protected
Definition at line 346 of file InstanceScript.cpp.
 {
     if (!data)
         return nullptr;
     std::istringstream loadStream(data);
     uint32 buff;
     uint32 bossId = 0;
     for (std::vector<BossInfo>::iterator i = bosses.begin(); i != bosses.end(); ++i, ++bossId)
     {
         loadStream >> buff;
         if (buff < TO_BE_DECIDED)
             SetBossState(bossId, (EncounterState)buff);
     }
     return loadStream.str();
 }
References bosses, SetBossState(), and TO_BE_DECIDED.
Referenced by instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript::Load(), Load(), instance_auchenai_crypts::instance_auchenai_crypts_InstanceMapScript::Load(), and instance_mana_tombs::instance_mana_tombs_InstanceMapScript::Load().
LoadDoorData()
void InstanceScript::LoadDoorData (DoorData const * data) protected
Definition at line 133 of file InstanceScript.cpp.
 {
     while (data->entry)
     {
         if (data->bossId < bosses.size())
             doors.insert(std::make_pair(data->entry, DoorInfo(&bosses[data->bossId], data->type, BoundaryType(data->boundary))));
         ++data;
     }
     LOG_DEBUG("scripts.ai", "InstanceScript::LoadDoorData: " UI64FMTD " doors loaded.", uint64(doors.size()));
 }
References bosses, DoorData::bossId, DoorData::boundary, doors, DoorData::entry, LOG_DEBUG, DoorData::type, and UI64FMTD.
Referenced by instance_gundrak::instance_gundrak_InstanceMapScript::Initialize(), instance_nexus::instance_nexus_InstanceMapScript::Initialize(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Initialize(), instance_arcatraz::instance_arcatraz_InstanceMapScript::instance_arcatraz_InstanceMapScript(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::instance_azjol_nerub_InstanceScript(), instance_black_temple::instance_black_temple_InstanceMapScript::instance_black_temple_InstanceMapScript(), instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::instance_blackwing_lair_InstanceMapScript(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::instance_drak_tharon_keep_InstanceScript(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::instance_gruuls_lair_InstanceMapScript(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::instance_icecrown_citadel_InstanceMapScript(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::instance_magtheridons_lair_InstanceMapScript(), instance_mechanar::instance_mechanar_InstanceMapScript::instance_mechanar_InstanceMapScript(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::instance_ruby_sanctum_InstanceMapScript(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::instance_sunwell_plateau_InstanceMapScript(), and instance_zulgurub::instance_zulgurub_InstanceMapScript::instance_zulgurub_InstanceMapScript().
LoadMinionData()
void InstanceScript::LoadMinionData (MinionData const * data) protected
Definition at line 121 of file InstanceScript.cpp.
 {
     while (data->entry)
     {
         if (data->bossId < bosses.size())
             minions.insert(std::make_pair(data->entry, MinionInfo(&bosses[data->bossId])));
         ++data;
     }
     LOG_DEBUG("scripts.ai", "InstanceScript::LoadMinionData: " UI64FMTD " minions loaded.", uint64(minions.size()));
 }
References bosses, MinionData::bossId, MinionData::entry, LOG_DEBUG, minions, and UI64FMTD.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::instance_gruuls_lair_InstanceMapScript(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::instance_magtheridons_lair_InstanceMapScript(), and instance_molten_core::instance_molten_core_InstanceMapScript::instance_molten_core_InstanceMapScript().
LoadObjectData() [1/2]
void InstanceScript::LoadObjectData (ObjectData const * creatureData, ObjectData const * gameObjectData) protected
Definition at line 145 of file InstanceScript.cpp.
 {
     if (creatureData)
     {
         LoadObjectData(creatureData, _creatureInfo);
     }
     if (gameObjectData)
     {
         LoadObjectData(gameObjectData, _gameObjectInfo);
     }
     LOG_ERROR("scripts", "InstanceScript::LoadObjectData: " SZFMTD " objects loaded.", _creatureInfo.size() + _gameObjectInfo.size());
 }
References _creatureInfo, _gameObjectInfo, creatureData, LOG_ERROR, and SZFMTD.
Referenced by instance_azjol_nerub::instance_azjol_nerub_InstanceScript::instance_azjol_nerub_InstanceScript().
LoadObjectData() [2/2]
void InstanceScript::LoadObjectData (ObjectData const * creatureData, ObjectInfoMap & objectInfo) static private
Definition at line 160 of file InstanceScript.cpp.
 {
     while (data->entry)
     {
         objectInfo[data->entry] = data->type;
         ++data;
     }
 }
References ObjectData::entry, and ObjectData::type.
MarkAreaTriggerDone()
void InstanceScript::MarkAreaTriggerDone (uint32 id) inline
Definition at line 246 of file InstanceScript.h.
 { _activatedAreaTriggers.insert(id); }
References _activatedAreaTriggers.
OnCreatureCreate()
void InstanceScript::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from ZoneScript.
Reimplemented in instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, and instance_scholomance::instance_scholomance_InstanceMapScript.
Definition at line 49 of file InstanceScript.cpp.
 {
     AddObject(creature, true);
     AddMinion(creature, true);
 }
References AddMinion(), and AddObject().
Referenced by instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate(), and instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnCreatureCreate().
OnCreatureRemove()
void InstanceScript::OnCreatureRemove (Creature * creature) override virtual
Reimplemented from ZoneScript.
Reimplemented in instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, and instance_molten_core::instance_molten_core_InstanceMapScript.
Definition at line 55 of file InstanceScript.cpp.
 {
     AddObject(creature, false);
     AddMinion(creature, false);
 }
References AddMinion(), and AddObject().
OnGameObjectCreate()
void InstanceScript::OnGameObjectCreate (GameObject * go) override virtual
Reimplemented from ZoneScript.
Reimplemented in instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, and instance_deadmines::instance_deadmines_InstanceMapScript.
Definition at line 61 of file InstanceScript.cpp.
 {
     AddObject(go, true);
     AddDoor(go, true);
 }
References AddDoor(), and AddObject().
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), and instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate().
OnGameObjectRemove()
void InstanceScript::OnGameObjectRemove (GameObject * go) override virtual
Reimplemented from ZoneScript.
Reimplemented in instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, and instance_gundrak::instance_gundrak_InstanceMapScript.
Definition at line 67 of file InstanceScript.cpp.
 {
     AddObject(go, false);
     AddDoor(go, false);
 }
References AddDoor(), and AddObject().
Referenced by instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove().
OnPlayerAreaUpdate()
virtual void InstanceScript::OnPlayerAreaUpdate (Player * , uint32 , uint32) inline virtual
Reimplemented in instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, and instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript.
Definition at line 186 of file InstanceScript.h.
 {}
OnPlayerEnter()
virtual void InstanceScript::OnPlayerEnter (Player *) inline virtual
Reimplemented in instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, and instance_molten_core::instance_molten_core_InstanceMapScript.
Definition at line 184 of file InstanceScript.h.
 {}
Referenced by InstanceMap::AddPlayerToMap().
ResetAreaTriggerDone()
void InstanceScript::ResetAreaTriggerDone (uint32 id) inline
Definition at line 247 of file InstanceScript.h.
 { _activatedAreaTriggers.erase(id); }
References _activatedAreaTriggers.
Referenced by OnlyOnceAreaTriggerScript::ResetAreaTriggerDone().
SaveToDB()
void InstanceScript::SaveToDB ()
Definition at line 32 of file InstanceScript.cpp.
 {
     std::string data = GetSaveData();
     //if (data.empty()) // pussywizard: encounterMask can be updated and theres no reason to not save
     //    return;
     // pussywizard:
     InstanceSave* save = sInstanceSaveMgr->GetInstanceSave(instance->GetInstanceId());
     if (save)
         save->SetInstanceData(data);
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_INSTANCE_SAVE_DATA);
     stmt->setString(0, data);
     stmt->setUInt32(1, instance->GetInstanceId());
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_INSTANCE_SAVE_DATA, CharacterDatabase, Map::GetInstanceId(), GetSaveData(), instance, InstanceSave::SetInstanceData(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and sInstanceSaveMgr.
Referenced by BossAI::_JustDied(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoCheckDedicatedInsanity(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HandleDropAttempt(), instance_commandscript::HandleInstanceSaveDataCommand(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), boss_mandokir::boss_mandokirAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnUnitDeath(), instance_stratholme::instance_stratholme_InstanceMapScript::OnUnitDeath(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnUnitDeath(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), SetBossState(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetBossState(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::SetBossState(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetData(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SetData(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_deadmines::instance_deadmines_InstanceMapScript::SetData(), instance_scholomance::instance_scholomance_InstanceMapScript::SetData(), instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::SetData(), instance_uldaman::instance_uldaman_InstanceMapScript::SetData(), instance_zulaman::instance_zulaman_InstanceMapScript::SetData(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData(), instance_dire_maul::instance_dire_maul_InstanceMapScript::SetData(), instance_maraudon::instance_maraudon_InstanceMapScript::SetData(), instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript::SetData(), instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript::SetData(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SetData(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), instance_oculus::instance_oculus_InstanceMapScript::SetData(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::SetData(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::SetData(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::SetData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::SetData(), instance_steam_vault::instance_steam_vault_InstanceMapScript::SetData(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::SetData(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::SetData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::SetData(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_zulaman::instance_zulaman_InstanceMapScript::Update(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), and instance_mechanar::instance_mechanar_InstanceMapScript::Update().
SendEncounterUnit()
void InstanceScript::SendEncounterUnit (uint32 type, Unit * unit = nullptr, uint8 param1 = 0, uint8 param2 = 0)
Definition at line 529 of file InstanceScript.cpp.
 {
     // size of this packet is at most 15 (usually less)
     WorldPacket data(SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT, 15);
     data << uint32(type);
     switch (type)
     {
         case ENCOUNTER_FRAME_ENGAGE:
         case ENCOUNTER_FRAME_DISENGAGE:
         case ENCOUNTER_FRAME_UPDATE_PRIORITY:
             data << unit->GetPackGUID();
             data << uint8(param1);
             break;
         case ENCOUNTER_FRAME_ADD_TIMER:
         case ENCOUNTER_FRAME_ENABLE_OBJECTIVE:
         case ENCOUNTER_FRAME_DISABLE_OBJECTIVE:
             data << uint8(param1);
             break;
         case ENCOUNTER_FRAME_UPDATE_OBJECTIVE:
             data << uint8(param1);
             data << uint8(param2);
             break;
         case ENCOUNTER_FRAME_REFRESH_FRAMES:
         default:
             break;
     }
     instance->SendToPlayers(&data);
 }
References ENCOUNTER_FRAME_ADD_TIMER, ENCOUNTER_FRAME_DISABLE_OBJECTIVE, ENCOUNTER_FRAME_DISENGAGE, ENCOUNTER_FRAME_ENABLE_OBJECTIVE, ENCOUNTER_FRAME_ENGAGE, ENCOUNTER_FRAME_REFRESH_FRAMES, ENCOUNTER_FRAME_UPDATE_OBJECTIVE, ENCOUNTER_FRAME_UPDATE_PRIORITY, Object::GetPackGUID(), instance, Map::SendToPlayers(), and SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT.
Referenced by boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), boss_halion::boss_halionAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_twilight_halion::boss_twilight_halionAI::JustDied(), boss_halion::boss_halionAI::JustReachedHome(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustReachedHome(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::Reset(), and boss_twilight_halion::boss_twilight_halionAI::UpdateAI().
ServerAllowsTwoSideGroups()
bool InstanceScript::ServerAllowsTwoSideGroups () inline
Definition at line 219 of file InstanceScript.h.
 { return sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP); }
References CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP, and sWorld.
SetBossNumber()
void InstanceScript::SetBossNumber (uint32 number) inline protected
Definition at line 253 of file InstanceScript.h.
 { bosses.resize(number); }
References bosses.
Referenced by instance_gundrak::instance_gundrak_InstanceMapScript::Initialize(), instance_nexus::instance_nexus_InstanceMapScript::Initialize(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Initialize(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::Initialize(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Initialize(), instance_the_eye::instance_the_eye_InstanceMapScript::Initialize(), instance_ahnkahet::instance_ahnkahet_InstanceScript::instance_ahnkahet_InstanceScript(), instance_arcatraz::instance_arcatraz_InstanceMapScript::instance_arcatraz_InstanceMapScript(), instance_auchenai_crypts::instance_auchenai_crypts_InstanceMapScript::instance_auchenai_crypts_InstanceMapScript(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::instance_azjol_nerub_InstanceScript(), instance_black_temple::instance_black_temple_InstanceMapScript::instance_black_temple_InstanceMapScript(), instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::instance_blackwing_lair_InstanceMapScript(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::instance_drak_tharon_keep_InstanceScript(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::instance_gruuls_lair_InstanceMapScript(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::instance_icecrown_citadel_InstanceMapScript(), instance_karazhan::instance_karazhan_InstanceMapScript::instance_karazhan_InstanceMapScript(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::instance_magtheridons_lair_InstanceMapScript(), instance_mana_tombs::instance_mana_tombs_InstanceMapScript::instance_mana_tombs_InstanceMapScript(), instance_mechanar::instance_mechanar_InstanceMapScript::instance_mechanar_InstanceMapScript(), instance_molten_core::instance_molten_core_InstanceMapScript::instance_molten_core_InstanceMapScript(), instance_naxxramas::instance_naxxramas_InstanceMapScript::instance_naxxramas_InstanceMapScript(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::instance_obsidian_sanctum_InstanceMapScript(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::instance_ruby_sanctum_InstanceMapScript(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::instance_ruins_of_ahnqiraj_InstanceMapScript(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::instance_sunwell_plateau_InstanceMapScript(), instance_the_botanica::instance_the_botanica_InstanceMapScript::instance_the_botanica_InstanceMapScript(), and instance_zulgurub::instance_zulgurub_InstanceMapScript::instance_zulgurub_InstanceMapScript().
SetBossState()
bool InstanceScript::SetBossState (uint32 id, EncounterState state) virtual
Reimplemented in instance_mechanar::instance_mechanar_InstanceMapScript, instance_the_botanica::instance_the_botanica_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, and instance_molten_core::instance_molten_core_InstanceMapScript.
Definition at line 310 of file InstanceScript.cpp.
 {
     if (id < bosses.size())
     {
         BossInfo* bossInfo = &bosses[id];
         if (bossInfo->state == TO_BE_DECIDED) // loading
         {
             bossInfo->state = state;
             return false;
         }
         else
         {
             if (bossInfo->state == state)
                 return false;
             if (state == DONE)
                 for (MinionSet::iterator i = bossInfo->minion.begin(); i != bossInfo->minion.end(); ++i)
                     if ((*i)->isWorldBoss() && (*i)->IsAlive())
                         return false;
             bossInfo->state = state;
             SaveToDB();
         }
         for (uint32 type = 0; type < MAX_DOOR_TYPES; ++type)
             for (DoorSet::iterator i = bossInfo->door[type].begin(); i != bossInfo->door[type].end(); ++i)
                 UpdateDoorState(*i);
         for (MinionSet::iterator i = bossInfo->minion.begin(); i != bossInfo->minion.end(); ++i)
             UpdateMinionState(*i, state);
         return true;
     }
     return false;
 }
References bosses, DONE, BossInfo::door, MAX_DOOR_TYPES, BossInfo::minion, SaveToDB(), BossInfo::state, TO_BE_DECIDED, UpdateDoorState(), and UpdateMinionState().
Referenced by BossAI::_EnterCombat(), BossAI::_JustDied(), BossAI::_Reset(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_hadronox::boss_hadronoxAI::DoAction(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction(), boss_sartharion_dragonAI::EnterCombat(), boss_lord_marrowgar::EnterCombat(), boss_olm_the_summoner::boss_olm_the_summonerAI::EnterCombat(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::EnterCombat(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::EnterCombat(), boss_krosh_firehand::boss_krosh_firehandAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), instance_commandscript::HandleInstanceSetBossStateCommand(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), boss_gyth::boss_gythAI::JustDied(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustDied(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_crone::boss_croneAI::JustDied(), boss_bigbadwolf::boss_bigbadwolfAI::JustDied(), boss_julianne::boss_julianneAI::JustDied(), boss_romulo::boss_romuloAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustDied(), boss_mandokir::boss_mandokirAI::JustDied(), npc_ohgan::npc_ohganAI::JustDied(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustDied(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_moroes::boss_moroesAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_thekal::boss_thekalAI::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), boss_sindragosa::boss_sindragosaAI::JustReachedHome(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::Load(), instance_the_eye::instance_the_eye_InstanceMapScript::Load(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::Load(), instance_zulgurub::instance_zulgurub_InstanceMapScript::Load(), LoadBossState(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_mandokir::boss_mandokirAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), SmartScript::ProcessAction(), boss_gyth::boss_gythAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::Reset(), npc_zealot_zath::npc_zealot_zathAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::Reset(), boss_olm_the_summoner::boss_olm_the_summonerAI::Reset(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::Reset(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::Reset(), boss_krosh_firehand::boss_krosh_firehandAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), instance_molten_core::instance_molten_core_InstanceMapScript::SetBossState(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::SetBossState(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::SetBossState(), instance_nexus::instance_nexus_InstanceMapScript::SetBossState(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::SetBossState(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetBossState(), instance_blackrock_spire::instance_blackrock_spireMapScript::SetBossState(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState(), instance_karazhan::instance_karazhan_InstanceMapScript::SetBossState(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetBossState(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::SetBossState(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState(), instance_gundrak::instance_gundrak_InstanceMapScript::SetBossState(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), instance_black_temple::instance_black_temple_InstanceMapScript::SetBossState(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetBossState(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::SetBossState(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetBossState(), instance_arcatraz::instance_arcatraz_InstanceMapScript::SetBossState(), instance_the_botanica::instance_the_botanica_InstanceMapScript::SetBossState(), instance_mechanar::instance_mechanar_InstanceMapScript::SetBossState(), npc_barnes::npc_barnesAI::StartEvent(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), and npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI().
SetCompletedEncountersMask()
void InstanceScript::SetCompletedEncountersMask (uint32 newMask, bool save)
Definition at line 510 of file InstanceScript.cpp.
 {
     if (completedEncounters == newMask)
         return;
     completedEncounters = newMask;
     // pussywizard:
     if (save)
     {
         InstanceSave* iSave = sInstanceSaveMgr->GetInstanceSave(instance->GetInstanceId());
         if (iSave)
             iSave->SetCompletedEncounterMask(completedEncounters);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_INSTANCE_SAVE_ENCOUNTERMASK);
         stmt->setUInt32(0, completedEncounters);
         stmt->setUInt32(1, instance->GetInstanceId());
         CharacterDatabase.Execute(stmt);
     }
 }
References CHAR_UPD_INSTANCE_SAVE_ENCOUNTERMASK, CharacterDatabase, completedEncounters, Map::GetInstanceId(), instance, InstanceSave::SetCompletedEncounterMask(), PreparedStatementBase::setUInt32(), and sInstanceSaveMgr.
Referenced by InstanceMap::CreateInstanceScript().
Update()
virtual void InstanceScript::Update (uint32) inline virtual
Reimplemented in instance_mechanar::instance_mechanar_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, and instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript.
Definition at line 163 of file InstanceScript.h.
 {}
Referenced by InstanceMap::Update().
UpdateDoorState()
void InstanceScript::UpdateDoorState (GameObject * door) protected
Definition at line 190 of file InstanceScript.cpp.
 {
     DoorInfoMapBounds range = doors.equal_range(door->GetEntry());
     if (range.first == range.second)
         return;
     // xinef: doors can be assigned to few bosses, if any of them demands doors closed - they should be closed (added & operator for assigment)
     bool open = true;
     for (; range.first != range.second && open; ++range.first)
     {
         DoorInfo const& info = range.first->second;
         switch (info.type)
         {
             case DOOR_TYPE_ROOM:
                 open &= (info.bossInfo->state != IN_PROGRESS);
                 break;
             case DOOR_TYPE_PASSAGE:
                 open &= (info.bossInfo->state == DONE);
                 break;
             case DOOR_TYPE_SPAWN_HOLE:
                 open &= (info.bossInfo->state == IN_PROGRESS);
                 break;
             default:
                 break;
         }
     }
     door->SetGoState(open ? GO_STATE_ACTIVE : GO_STATE_READY);
 }
References DoorInfo::bossInfo, DONE, DOOR_TYPE_PASSAGE, DOOR_TYPE_ROOM, DOOR_TYPE_SPAWN_HOLE, doors, Object::GetEntry(), GO_STATE_ACTIVE, GO_STATE_READY, IN_PROGRESS, GameObject::SetGoState(), BossInfo::state, and DoorInfo::type.
Referenced by AddDoor(), and SetBossState().
UpdateMinionState()
void InstanceScript::UpdateMinionState (Creature * minion, EncounterState state) protected
Definition at line 169 of file InstanceScript.cpp.
 {
     switch (state)
     {
         case NOT_STARTED:
             if (!minion->IsAlive())
                 minion->Respawn();
             else if (minion->IsInCombat())
                 minion->AI()->EnterEvadeMode();
             break;
         case IN_PROGRESS:
             if (!minion->IsAlive())
                 minion->Respawn();
             else if (!minion->GetVictim())
                 minion->AI()->DoZoneInCombat(nullptr, 100.0f);
             break;
         default:
             break;
     }
 }
References Creature::AI(), CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), Unit::GetVictim(), IN_PROGRESS, Unit::IsAlive(), Unit::IsInCombat(), NOT_STARTED, and Creature::Respawn().
Referenced by SetBossState().
Member Data Documentation
_activatedAreaTriggers
std::unordered_set<uint32> InstanceScript::_activatedAreaTriggers private
Definition at line 280 of file InstanceScript.h.
Referenced by IsAreaTriggerDone(), MarkAreaTriggerDone(), and ResetAreaTriggerDone().
_creatureInfo
ObjectInfoMap InstanceScript::_creatureInfo private
Definition at line 276 of file InstanceScript.h.
Referenced by AddObject(), and LoadObjectData().
_gameObjectInfo
ObjectInfoMap InstanceScript::_gameObjectInfo private
Definition at line 277 of file InstanceScript.h.
Referenced by AddObject(), and LoadObjectData().
_objectGuids
ObjectGuidMap InstanceScript::_objectGuids private
Definition at line 278 of file InstanceScript.h.
Referenced by AddObject(), and GetObjectGuid().
bosses
std::vector<BossInfo> InstanceScript::bosses private
Definition at line 273 of file InstanceScript.h.
Referenced by GetBossBoundary(), GetBossInfo(), GetBossSaveData(), GetBossState(), GetEncounterCount(), IsEncounterInProgress(), LoadBossState(), LoadDoorData(), LoadMinionData(), SetBossNumber(), and SetBossState().
completedEncounters
uint32 InstanceScript::completedEncounters private
Definition at line 279 of file InstanceScript.h.
Referenced by GetCompletedEncounterMask(), and SetCompletedEncountersMask().
doors
DoorInfoMap InstanceScript::doors private
Definition at line 274 of file InstanceScript.h.
Referenced by AddDoor(), LoadDoorData(), and UpdateDoorState().
instance
Map* InstanceScript::instance
Definition at line 147 of file InstanceScript.h.
Referenced by instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ActivateCell(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ActivatePrisoners(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::AddWave1(), boss_tyrannus::boss_tyrannusAI::boss_tyrannusAI(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::CheckAchievementCriteriaMeet(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::CheckAchievementCriteriaMeet(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckAchievementCriteriaMeet(), instance_naxxramas::instance_naxxramas_InstanceMapScript::CheckAchievementCriteriaMeet(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), CheckAchievementCriteriaMeet(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckLichKingAvailability(), instance_molten_core::instance_molten_core_InstanceMapScript::CheckMajordomoExecutus(), boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::CheckTombReset(), instance_stratholme::instance_stratholme_InstanceMapScript::CheckZiggurats(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::CleanupInstance(), violet_hold_trashAI::ClearDoorSealAura(), hyjalAI::DeSpawnVeins(), npc_hor_lich_king::npc_hor_lich_kingAI::DoAction(), npc_vh_void_sentry::npc_vh_void_sentryAI::DoAction(), instance_molten_core::instance_molten_core_InstanceMapScript::DoAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), DoCastSpellOnPlayers(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoCheckDedicatedInsanity(), npc_rocknot::npc_rocknotAI::DoGo(), instance_violet_hold::instance_violet_hold_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoNeedCleanup(), DoRemoveAurasDueToSpellOnPlayers(), DoRespawnGameObject(), DoSendNotifyToInstance(), DoStartTimedAchievement(), DoStopTimedAchievement(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoSummonGrandChampion(), DoUpdateAchievementCriteria(), DoUpdateWorldState(), DoUseDoorOrButton(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::DoWipe1(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::EnterCombat(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), npc_erekem_guard::npc_erekem_guardAI::EnterCombat(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::FillInitialWorldStates(), instance_stratholme::instance_stratholme_InstanceMapScript::gate_critter_delay(), boss_erekem::boss_erekemAI::GetChainHealTargetGUID(), GetCreature(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetData(), GetGameObject(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry(), instance_mechanar::instance_mechanar_InstanceMapScript::GetPassagePlayer(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetPlayerInMap(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GetSaveData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::HandleDropAttempt(), HandleGameObject(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::HandleOutro(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::IsEncounterInProgress(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::IsEncounterInProgress(), instance_ulduar::instance_ulduar_InstanceMapScript::IsEncounterInProgress(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::IsWaveAllDead(), boss_jormungarAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_varos::boss_varosAI::JustDied(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::JustDied(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::JustDied(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::JustDied(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::JustDied(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::JustDied(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustDied(), npc_ichor_globule::npc_ichor_globuleAI::JustDied(), npc_vh_void_sentry::npc_vh_void_sentryAI::JustDied(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Load(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::Load(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::MoveNPCIfAlive(), npc_frost_tomb::npc_frost_tombAI::npc_frost_tombAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnCreatureCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), instance_zulaman::instance_zulaman_InstanceMapScript::OnPlayerEnter(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnPlayerEnter(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnPlayerEnter(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::OnPlayerEnter(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnPlayerEnter(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnPlayerEnter(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnPlayerEnter(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnPlayerEnter(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnPlayerEnter(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), at_tyrannus_event_starter::OnTrigger(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), instance_blackrock_spire::instance_blackrock_spireMapScript::ProcessEvent(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::ProcessEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::RandomizeCompositionsAndShow(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::RemoveBackPack(), boss_tyrannus::boss_tyrannusAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisoners(), SaveToDB(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SendAddsUpStairs(), SendEncounterUnit(), instance_molten_core::instance_molten_core_InstanceMapScript::SetBossState(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetBossState(), instance_blackrock_spire::instance_blackrock_spireMapScript::SetBossState(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState(), instance_karazhan::instance_karazhan_InstanceMapScript::SetBossState(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::SetBossState(), instance_gundrak::instance_gundrak_InstanceMapScript::SetBossState(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), instance_black_temple::instance_black_temple_InstanceMapScript::SetBossState(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetBossState(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::SetBossState(), instance_ulduar::instance_ulduar_InstanceMapScript::setChestsLootable(), SetCompletedEncountersMask(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::SetData(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_blackrock_spire::instance_blackrock_spireMapScript::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), instance_scholomance::instance_scholomance_InstanceMapScript::SetData(), instance_stratholme::instance_stratholme_InstanceMapScript::SetData(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData(), instance_dire_maul::instance_dire_maul_InstanceMapScript::SetData(), instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript::SetData(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), instance_oculus::instance_oculus_InstanceMapScript::SetData(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::SetData(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::SetData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::SetData(), instance_steam_vault::instance_steam_vault_InstanceMapScript::SetData(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetData(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetData(), instance_arcatraz::instance_arcatraz_InstanceMapScript::SetData(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), instance_gundrak::instance_gundrak_InstanceMapScript::SetData(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetData(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::SetData(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::SetData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::SetData(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::ShowKeeperGossip(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SpawnAnubArak(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SpawnGunship(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnLeviathanEncounterVehicles(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter(), instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage(), instance_molten_core::instance_molten_core_InstanceMapScript::SummonMajordomoExecutus(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), instance_blackrock_spire::instance_blackrock_spireMapScript::SummonSolakarWave(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::TombOfSevenEvent(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::TombOfSevenReset(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Update(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_gundrak::instance_gundrak_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update(), instance_mechanar::instance_mechanar_InstanceMapScript::Update(), npc_arthas::npc_arthasAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_ichor_globule::npc_ichor_globuleAI::UpdateAI(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::UpdateBroggokEvent(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::UpdateEventState(), and npc_arthas::npc_arthasAI::WaypointReached().
minions
MinionInfoMap InstanceScript::minions private
Definition at line 275 of file InstanceScript.h.
Referenced by AddMinion(), and LoadMinionData().
The documentation for this class was generated from the following files:
src/server/game/Instances/InstanceScript.h
src/server/game/Instances/InstanceScript.cpp