Azerotcore-wotlk: Object Class Reference
Object Class Reference abstract
#include <Object.h>
Public Member Functions
virtual ~Object ()
bool IsInWorld () const
virtual void AddToWorld ()
virtual void RemoveFromWorld ()
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
virtual void BuildUpdate (UpdateDataMapType &, UpdatePlayerSet &)
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Static Public Member Functions
static ObjectGuid GetGUID (Object const *o)
Public Attributes
DataMap CustomData
Protected Member Functions
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const
virtual void AddToObjectUpdate ()=0
virtual void RemoveFromObjectUpdate ()=0
void AddToObjectUpdateIfNeeded ()
Protected Attributes
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
bool PrintIndexError (uint32 index, bool set) const
Object (const Object &)
Object & operator= (Object const &)
Private Attributes
bool m_inWorld
PackedGuid m_PackGUID
Detailed Description
Definition at line 88 of file Object.h.
Constructor & Destructor Documentation
~Object()
Object::~Object () virtual
Definition at line 97 of file Object.cpp.
 {
     sScriptMgr->OnDestructObject(this);
     if (IsInWorld())
     {
         LOG_FATAL("entities.object", "Object::~Object - %s deleted but still in world!!", GetGUID().ToString().c_str());
         if (isType(TYPEMASK_ITEM))
             LOG_FATAL("entities.object", "Item slot %u", ((Item*)this)->GetSlot());
         ABORT();
     }
     if (m_objectUpdated)
     {
         LOG_FATAL("entities.object", "Object::~Object - %s deleted but still in update list!!", GetGUID().ToString().c_str());
         ABORT();
     }
     delete [] m_uint32Values;
     m_uint32Values = 0;
 }
References ABORT, GetGUID(), IsInWorld(), isType(), LOG_FATAL, m_objectUpdated, m_uint32Values, sScriptMgr, Acore::ToString(), and TYPEMASK_ITEM.
Object() [1/2]
Object::Object () protected
Definition at line 63 of file Object.cpp.
                : m_PackGUID(sizeof(uint64) + 1)
 {
     m_objectTypeId      = TYPEID_OBJECT;
     m_objectType        = TYPEMASK_OBJECT;
     m_uint32Values      = nullptr;
     m_valuesCount       = 0;
     _fieldNotifyFlags   = UF_FLAG_DYNAMIC;
     m_inWorld           = false;
     m_objectUpdated     = false;
     sScriptMgr->OnConstructObject(this);
 }
References _fieldNotifyFlags, m_inWorld, m_objectType, m_objectTypeId, m_objectUpdated, m_uint32Values, m_valuesCount, sScriptMgr, TYPEID_OBJECT, TYPEMASK_OBJECT, and UF_FLAG_DYNAMIC.
Object() [2/2]
Object::Object (const Object &) private
Member Function Documentation
_ConcatFields()
std::string Object::_ConcatFields (uint16 startIndex, uint16 size) const protected
Definition at line 139 of file Object.cpp.
 {
     std::ostringstream ss;
     for (uint16 index = 0; index < size; ++index)
         ss << GetUInt32Value(index + startIndex) << ' ';
     return ss.str();
 }
References GetUInt32Value(), and index.
Referenced by Corpse::SaveToDB().
_Create()
void Object::_Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh) protected
Definition at line 129 of file Object.cpp.
 {
     if (!m_uint32Values) _InitValues();
     ObjectGuid guid(guidhigh, entry, guidlow);
     SetGuidValue(OBJECT_FIELD_GUID, guid);
     SetUInt32Value(OBJECT_FIELD_TYPE, m_objectType);
     m_PackGUID.Set(guid);
 }
References _InitValues(), m_objectType, m_PackGUID, m_uint32Values, OBJECT_FIELD_GUID, OBJECT_FIELD_TYPE, PackedGuid::Set(), SetGuidValue(), and SetUInt32Value().
Referenced by WorldObject::_Create(), Corpse::Create(), Player::Create(), Pet::Create(), Item::Create(), Bag::Create(), GameObject::Create(), StaticTransport::Create(), Creature::CreateFromProto(), MotionTransport::CreateMoTrans(), Player::Initialize(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), and Item::LoadFromDB().
_InitValues()
void Object::_InitValues () protected
Definition at line 119 of file Object.cpp.
 {
     m_uint32Values = new uint32[m_valuesCount];
     memset(m_uint32Values, 0, m_valuesCount * sizeof(uint32));
     _changesMask.SetCount(m_valuesCount);
     m_objectUpdated = false;
 }
References _changesMask, m_objectUpdated, m_uint32Values, m_valuesCount, memset, and UpdateMask::SetCount().
Referenced by _Create().
_LoadIntoDataField()
void Object::_LoadIntoDataField (std::string const & data, uint32 startOffset, uint32 count) protected
Definition at line 611 of file Object.cpp.
 {
     if (data.empty())
         return;
     Tokenizer tokens(data, ' ', count);
     if (tokens.size() != count)
         return;
     for (uint32 index = 0; index < count; ++index)
     {
         m_uint32Values[startOffset + index] = atol(tokens[index]);
         _changesMask.SetBit(startOffset + index);
     }
 }
References _changesMask, count(), index, m_uint32Values, UpdateMask::SetBit(), and Tokenizer::size().
Referenced by Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), and Item::LoadFromDB().
AddGuidValue()
bool Object::AddGuidValue (uint16 index, ObjectGuid value)
Definition at line 677 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, true));
     if (value && !*((ObjectGuid*)&(m_uint32Values[index])))
     {
         *((ObjectGuid*)&(m_uint32Values[index])) = value;
         _changesMask.SetBit(index);
         _changesMask.SetBit(index + 1);
         AddToObjectUpdateIfNeeded();
         return true;
     }
     return false;
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Unit::SetCharm(), Unit::SetMinion(), and Player::SetViewpoint().
AddToObjectUpdate()
virtual void Object::AddToObjectUpdate () protected pure virtual
Implemented in WorldObject, and Item.
Referenced by AddToObjectUpdateIfNeeded().
AddToObjectUpdateIfNeeded()
void Object::AddToObjectUpdateIfNeeded () protected
Definition at line 523 of file Object.cpp.
 {
     if (m_inWorld && !m_objectUpdated)
     {
         AddToObjectUpdate();
         m_objectUpdated = true;
     }
 }
References AddToObjectUpdate(), m_inWorld, and m_objectUpdated.
Referenced by AddGuidValue(), ForceValuesUpdateAtIndex(), RemoveByteFlag(), RemoveFlag(), RemoveGuidValue(), SetByteFlag(), SetFlag(), SetFloatValue(), SetGuidValue(), SetInt32Value(), SetUInt16Value(), SetUInt32Value(), and SetUInt64Value().
AddToWorld()
void Object::AddToWorld () virtual
Reimplemented in Unit, Player, Pet, WorldObject, Bag, GameObject, DynamicObject, Creature, and Corpse.
Definition at line 147 of file Object.cpp.
 {
     if (m_inWorld)
         return;
     ASSERT(m_uint32Values);
     m_inWorld = true;
     // synchronize values mirror with values array (changes will send in updatecreate opcode any way
     ASSERT(!m_objectUpdated);
     ClearUpdateMask(false);
 }
References ASSERT, ClearUpdateMask(), m_inWorld, m_objectUpdated, and m_uint32Values.
Referenced by Player::_StoreItem(), Corpse::AddToWorld(), Bag::AddToWorld(), WorldObject::AddToWorld(), Player::AddToWorld(), Player::EquipItem(), Guild::BankTab::LoadItemFromDB(), and Player::QuickEquipItem().
ApplyModFlag()
void Object::ApplyModFlag (uint16 index, uint32 flag, bool apply)
Definition at line 890 of file Object.cpp.
 {
     if (apply)
     {
         SetFlag(index, flag);
     }
     else
     {
         RemoveFlag(index, flag);
     }
 }
References ByteConverter::apply(), index, RemoveFlag(), and SetFlag().
Referenced by npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), AuraEffect::HandleAuraTrackStealthed(), AuraEffect::HandleModUnattackable(), WorldSession::HandleTogglePvP(), Player::KillPlayer(), Player::LoadCorpse(), Item::LoadFromDB(), Item::SetBinding(), and Player::SetDeveloper().
ApplyModFlag64()
void Object::ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
Definition at line 979 of file Object.cpp.
 {
     if (apply)
     {
         SetFlag64(index, flag);
     }
     else
     {
         RemoveFlag64(index, flag);
     }
 }
References ByteConverter::apply(), index, RemoveFlag64(), and SetFlag64().
ApplyModInt32Value()
void Object::ApplyModInt32Value (uint16 index, int32 val, bool apply)
Definition at line 806 of file Object.cpp.
 {
     int32 cur = GetInt32Value(index);
     cur += (apply ? val : -val);
     SetInt32Value(index, cur);
 }
References ByteConverter::apply(), GetInt32Value(), index, and SetInt32Value().
Referenced by Player::ApplySpellPenetrationBonus(), Player::ApplySpellPowerBonus(), AuraEffect::HandleModDamageDone(), AuraEffect::HandleModPowerCost(), and AuraEffect::HandleModTargetResistance().
ApplyModPositiveFloatValue()
void Object::ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
Definition at line 827 of file Object.cpp.
 {
     float cur = GetFloatValue(index);
     cur += (apply ? val : -val);
     if (cur < 0)
         cur = 0;
     SetFloatValue(index, cur);
 }
References ByteConverter::apply(), GetFloatValue(), index, and SetFloatValue().
ApplyModSignedFloatValue()
void Object::ApplyModSignedFloatValue (uint16 index, float val, bool apply)
Definition at line 813 of file Object.cpp.
 {
     float cur = GetFloatValue(index);
     cur += (apply ? val : -val);
     SetFloatValue(index, cur);
 }
References ByteConverter::apply(), GetFloatValue(), index, and SetFloatValue().
Referenced by Unit::ApplyResistanceBuffModsMod(), Unit::ApplyStatBuffMod(), Unit::ApplyStatPercentBuffMod(), and AuraEffect::HandleModPowerCostPCT().
ApplyModUInt32Value()
void Object::ApplyModUInt32Value (uint16 index, int32 val, bool apply)
Definition at line 797 of file Object.cpp.
 {
     int32 cur = GetUInt32Value(index);
     cur += (apply ? val : -val);
     if (cur < 0)
         cur = 0;
     SetUInt32Value(index, cur);
 }
References ByteConverter::apply(), GetUInt32Value(), index, and SetUInt32Value().
Referenced by Player::_ApplyWeaponDependentAuraDamageMod(), Player::ApplySpellPowerBonus(), AuraEffect::HandleAuraEmpathy(), and Player::RewardHonor().
ApplyModUInt64Value()
void Object::ApplyModUInt64Value (uint16 index, int32 val, bool apply)
ApplyPercentModFloatValue()
void Object::ApplyPercentModFloatValue (uint16 index, float val, bool apply)
Definition at line 820 of file Object.cpp.
 {
     float value = GetFloatValue(index);
     ApplyPercentModFloatVar(value, val, apply);
     SetFloatValue(index, value);
 }
References ByteConverter::apply(), ApplyPercentModFloatVar(), GetFloatValue(), index, and SetFloatValue().
Referenced by Unit::ApplyAttackTimePercentMod(), Unit::ApplyCastTimePercentMod(), Unit::ApplyResistanceBuffModsPercentMod(), and AuraEffect::HandleModDamagePercentDone().
BuildCreateUpdateBlockForPlayer()
void Object::BuildCreateUpdateBlockForPlayer (UpdateData * data, Player * target) const virtual
lower flag1
Reimplemented in Player, and Bag.
Definition at line 184 of file Object.cpp.
 {
     if (!target)
         return;
     uint8  updatetype = UPDATETYPE_CREATE_OBJECT;
     uint16 flags      = m_updateFlag;
     if (target == this)                                      // building packet for yourself
         flags |= UPDATEFLAG_SELF;
     if (flags & UPDATEFLAG_STATIONARY_POSITION)
     {
         // UPDATETYPE_CREATE_OBJECT2 dynamic objects, corpses...
         if (isType(TYPEMASK_DYNAMICOBJECT) || isType(TYPEMASK_CORPSE) || isType(TYPEMASK_PLAYER))
             updatetype = UPDATETYPE_CREATE_OBJECT2;
         // UPDATETYPE_CREATE_OBJECT2 for pets...
         if (target->GetPetGUID() == GetGUID())
             updatetype = UPDATETYPE_CREATE_OBJECT2;
         // UPDATETYPE_CREATE_OBJECT2 for some gameobject types...
         if (isType(TYPEMASK_GAMEOBJECT))
         {
             switch (((GameObject*)this)->GetGoType())
             {
                 case GAMEOBJECT_TYPE_TRAP:
                 case GAMEOBJECT_TYPE_DUEL_ARBITER:
                 case GAMEOBJECT_TYPE_FLAGSTAND:
                 case GAMEOBJECT_TYPE_FLAGDROP:
                     updatetype = UPDATETYPE_CREATE_OBJECT2;
                     break;
                 default:
                     if (((GameObject*)this)->GetOwner())
                         updatetype = UPDATETYPE_CREATE_OBJECT2;
                     break;
             }
         }
         if (isType(TYPEMASK_UNIT))
         {
             if (((Unit*)this)->GetVictim())
                 flags |= UPDATEFLAG_HAS_TARGET;
         }
     }
     ByteBuffer buf(500);
     buf << (uint8)updatetype;
     buf << GetPackGUID();
     buf << (uint8)m_objectTypeId;
     BuildMovementUpdate(&buf, flags);
     BuildValuesUpdate(updatetype, &buf, target);
     data->AddUpdateBlock(buf);
 }
References BuildMovementUpdate(), BuildValuesUpdate(), GAMEOBJECT_TYPE_DUEL_ARBITER, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_TRAP, GetGUID(), GetPackGUID(), Unit::GetPetGUID(), isType(), m_objectTypeId, m_updateFlag, TYPEMASK_CORPSE, TYPEMASK_DYNAMICOBJECT, TYPEMASK_GAMEOBJECT, TYPEMASK_PLAYER, TYPEMASK_UNIT, UPDATEFLAG_HAS_TARGET, UPDATEFLAG_SELF, UPDATEFLAG_STATIONARY_POSITION, UPDATETYPE_CREATE_OBJECT, and UPDATETYPE_CREATE_OBJECT2.
Referenced by Map::AddToMap(), Bag::BuildCreateUpdateBlockForPlayer(), Player::BuildCreateUpdateBlockForPlayer(), BattlegroundSA::SendTransportInit(), and SendUpdateToPlayer().
BuildFieldsUpdate()
void Object::BuildFieldsUpdate (Player * player, UpdateDataMapType & data_map) const
Definition at line 544 of file Object.cpp.
 {
     UpdateDataMapType::iterator iter = data_map.find(player);
     if (iter == data_map.end())
     {
         std::pair<UpdateDataMapType::iterator, bool> p = data_map.insert(UpdateDataMapType::value_type(player, UpdateData()));
         ASSERT(p.second);
         iter = p.first;
     }
     BuildValuesUpdateBlockForPlayer(&iter->second, iter->first);
 }
References ASSERT, and BuildValuesUpdateBlockForPlayer().
Referenced by WorldObjectChangeAccumulator::BuildPacket(), Item::BuildUpdate(), MotionTransport::BuildUpdate(), and StaticTransport::BuildUpdate().
BuildMovementUpdate()
void Object::BuildMovementUpdate (ByteBuffer * data, uint16 flags) const protected
Unit, Player and default here are sending wrong values.
Todo:
Research the proper formula
Todo:
Allow players to aquire this updateflag.
Definition at line 338 of file Object.cpp.
 {
     Unit const* unit = nullptr;
     WorldObject const* object = nullptr;
     if (isType(TYPEMASK_UNIT))
         unit = ToUnit();
     else
         object = ((WorldObject*)this);
     *data << uint16(flags);                                  // update flags
     // 0x20
     if (flags & UPDATEFLAG_LIVING)
     {
         unit->BuildMovementPacket(data);
         *data << unit->GetSpeed(MOVE_WALK)
               << unit->GetSpeed(MOVE_RUN)
               << unit->GetSpeed(MOVE_RUN_BACK)
               << unit->GetSpeed(MOVE_SWIM)
               << unit->GetSpeed(MOVE_SWIM_BACK)
               << unit->GetSpeed(MOVE_FLIGHT)
               << unit->GetSpeed(MOVE_FLIGHT_BACK)
               << unit->GetSpeed(MOVE_TURN_RATE)
               << unit->GetSpeed(MOVE_PITCH_RATE);
         // 0x08000000
         if (unit->m_movementInfo.GetMovementFlags() & MOVEMENTFLAG_SPLINE_ENABLED)
         {
             const G3D::Vector3* p = &unit->movespline->_Spline().getPoints(true)[0];
             if (unit->movespline->_Spline().getPoints(true).empty() || (!unit->movespline->_Spline().getPoints(true).empty() && !p))
                 const_cast<Unit*>(unit)->DisableSpline();
             else
                 Movement::PacketBuilder::WriteCreate(*unit->movespline, *data);
         }
     }
     else
     {
         if (flags & UPDATEFLAG_POSITION)
         {
             Transport* transport = object->GetTransport();
             if (transport)
                 *data << transport->GetPackGUID();
             else
                 *data << uint8(0);
             *data << object->GetPositionX();
             *data << object->GetPositionY();
             *data << object->GetPositionZ();
             if (transport)
             {
                 *data << object->GetTransOffsetX();
                 *data << object->GetTransOffsetY();
                 *data << object->GetTransOffsetZ();
             }
             else
             {
                 *data << object->GetPositionX();
                 *data << object->GetPositionY();
                 *data << object->GetPositionZ();
             }
             *data << object->GetOrientation();
             if (GetTypeId() == TYPEID_CORPSE)
                 *data << float(object->GetOrientation());
             else
                 *data << float(0);
         }
         else
         {
             // 0x40
             if (flags & UPDATEFLAG_STATIONARY_POSITION)
             {
                 *data << object->GetStationaryX();
                 *data << object->GetStationaryY();
                 *data << object->GetStationaryZ();
                 *data << object->GetStationaryO();
             }
         }
     }
     // 0x8
     if (flags & UPDATEFLAG_UNKNOWN)
     {
         *data << uint32(0);
     }
     // 0x10
     if (flags & UPDATEFLAG_LOWGUID)
     {
         switch (GetTypeId())
         {
             case TYPEID_OBJECT:
             case TYPEID_ITEM:
             case TYPEID_CONTAINER:
             case TYPEID_GAMEOBJECT:
             case TYPEID_DYNAMICOBJECT:
             case TYPEID_CORPSE:
                 *data << uint32(GetGUID().GetCounter());
                 break;
             case TYPEID_UNIT:
                 *data << uint32(0x0000000B);                // unk
                 break;
             case TYPEID_PLAYER:
                 if (flags & UPDATEFLAG_SELF)
                     *data << uint32(0x0000002F);            // unk
                 else
                     *data << uint32(0x00000008);            // unk
                 break;
             default:
                 *data << uint32(0x00000000);                // unk
                 break;
         }
     }
     // 0x4
     if (flags & UPDATEFLAG_HAS_TARGET)
     {
         if (Unit* victim = unit->GetVictim())
             *data << victim->GetPackGUID();
         else
             *data << uint8(0);
     }
     // 0x2
     if (flags & UPDATEFLAG_TRANSPORT)
     {
         GameObject const* go = ToGameObject();
         if (go && go->ToTransport())
             *data << uint32(go->ToTransport()->GetPathProgress());
         else
             *data << uint32(0);
     }
     // 0x80
     if (flags & UPDATEFLAG_VEHICLE)
     {
         *data << uint32(unit->GetVehicleKit()->GetVehicleInfo()->m_ID);
         if (unit->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT))
             *data << float(unit->GetTransOffsetO());
         else
             *data << float(unit->GetOrientation());
     }
     // 0x200
     if (flags & UPDATEFLAG_ROTATION)
     {
         *data << int64(ToGameObject()->GetPackedLocalRotation());
     }
 }
References Movement::MoveSpline::_Spline(), Unit::BuildMovementPacket(), GetGUID(), MovementInfo::GetMovementFlags(), Position::GetOrientation(), GetPackGUID(), Transport::GetPathProgress(), Movement::SplineBase::getPoints(), Unit::GetSpeed(), WorldObject::GetTransOffsetO(), WorldObject::GetTransport(), GetTypeId(), Vehicle::GetVehicleInfo(), Unit::GetVehicleKit(), Unit::GetVictim(), Unit::HasUnitMovementFlag(), isType(), VehicleEntry::m_ID, WorldObject::m_movementInfo, MOVE_FLIGHT, MOVE_FLIGHT_BACK, MOVE_PITCH_RATE, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_TURN_RATE, MOVE_WALK, MOVEMENTFLAG_ONTRANSPORT, MOVEMENTFLAG_SPLINE_ENABLED, Unit::movespline, ToGameObject(), GameObject::ToTransport(), ToUnit(), TYPEID_CONTAINER, TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_ITEM, TYPEID_OBJECT, TYPEID_PLAYER, TYPEID_UNIT, TYPEMASK_UNIT, UPDATEFLAG_HAS_TARGET, UPDATEFLAG_LIVING, UPDATEFLAG_LOWGUID, UPDATEFLAG_POSITION, UPDATEFLAG_ROTATION, UPDATEFLAG_SELF, UPDATEFLAG_STATIONARY_POSITION, UPDATEFLAG_TRANSPORT, UPDATEFLAG_UNKNOWN, UPDATEFLAG_VEHICLE, and Movement::PacketBuilder::WriteCreate().
Referenced by BuildCreateUpdateBlockForPlayer(), and BuildMovementUpdateBlock().
BuildMovementUpdateBlock()
void Object::BuildMovementUpdateBlock (UpdateData * data, uint32 flags = 0) const
Definition at line 172 of file Object.cpp.
 {
     ByteBuffer buf(500);
     buf << uint8(UPDATETYPE_MOVEMENT);
     buf << GetPackGUID();
     BuildMovementUpdate(&buf, flags);
     data->AddUpdateBlock(buf);
 }
References BuildMovementUpdate(), GetPackGUID(), and UPDATETYPE_MOVEMENT.
BuildOutOfRangeUpdateBlock()
void Object::BuildOutOfRangeUpdateBlock (UpdateData * data) const
Definition at line 264 of file Object.cpp.
 {
     data->AddOutOfRangeGUID(GetGUID());
 }
References GetGUID().
Referenced by Map::RemoveFromMap(), and BattlegroundSA::SendTransportsRemove().
BuildUpdate()
virtual void Object::BuildUpdate (UpdateDataMapType & , UpdatePlayerSet &) inline virtual
Reimplemented in WorldObject, StaticTransport, MotionTransport, and Item.
Definition at line 171 of file Object.h.
 {}
Referenced by Map::SendObjectUpdates().
BuildValuesUpdate()
void Object::BuildValuesUpdate (uint8 updatetype, ByteBuffer * data, Player * target) const protected virtual
Reimplemented in Unit, and GameObject.
Definition at line 496 of file Object.cpp.
 {
     if (!target)
         return;
     ByteBuffer fieldBuffer;
     UpdateMask updateMask;
     updateMask.SetCount(m_valuesCount);
     uint32* flags = nullptr;
     uint32 visibleFlag = GetUpdateFieldData(target, flags);
     for (uint16 index = 0; index < m_valuesCount; ++index)
     {
         if (_fieldNotifyFlags & flags[index] ||
                 ((updateType == UPDATETYPE_VALUES ? _changesMask.GetBit(index) : m_uint32Values[index]) && (flags[index] & visibleFlag)))
         {
             updateMask.SetBit(index);
             fieldBuffer << m_uint32Values[index];
         }
     }
     *data << uint8(updateMask.GetBlockCount());
     updateMask.AppendToPacket(data);
     data->append(fieldBuffer);
 }
References _changesMask, _fieldNotifyFlags, UpdateMask::AppendToPacket(), UpdateMask::GetBit(), UpdateMask::GetBlockCount(), GetUpdateFieldData(), index, m_uint32Values, m_valuesCount, UpdateMask::SetBit(), UpdateMask::SetCount(), and UPDATETYPE_VALUES.
Referenced by BuildCreateUpdateBlockForPlayer(), and BuildValuesUpdateBlockForPlayer().
BuildValuesUpdateBlockForPlayer()
void Object::BuildValuesUpdateBlockForPlayer (UpdateData * data, Player * target) const
Definition at line 252 of file Object.cpp.
 {
     ByteBuffer buf(500);
     buf << (uint8) UPDATETYPE_VALUES;
     buf << GetPackGUID();
     BuildValuesUpdate(UPDATETYPE_VALUES, &buf, target);
     data->AddUpdateBlock(buf);
 }
References BuildValuesUpdate(), GetPackGUID(), and UPDATETYPE_VALUES.
Referenced by Group::AddMember(), BuildFieldsUpdate(), Unit::SetOwnerGUID(), BattlegroundSA::StartShips(), GameObject::Update(), Player::UpdateForQuestWorldObjects(), and Player::UpdateTriggerVisibility().
ClearUpdateMask()
void Object::ClearUpdateMask (bool remove)
Definition at line 532 of file Object.cpp.
 {
     _changesMask.Clear();
     if (m_objectUpdated)
     {
         if (remove)
             RemoveFromObjectUpdate();
         m_objectUpdated = false;
     }
 }
References _changesMask, UpdateMask::Clear(), m_objectUpdated, and RemoveFromObjectUpdate().
Referenced by AddToWorld(), Item::BuildUpdate(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), WorldObject::BuildUpdate(), and RemoveFromWorld().
DestroyForPlayer()
void Object::DestroyForPlayer (Player * target, bool onDeath = false) const virtual
If the following bool is true, the client will call "void CGUnit_C::OnDeath()" for this object. OnDeath() does for eg trigger death animation and interrupts certain spells/missiles/auras/sounds...
Reimplemented in Player.
Definition at line 269 of file Object.cpp.
 {
     ASSERT(target);
     if (isType(TYPEMASK_UNIT) || isType(TYPEMASK_PLAYER))
     {
         if (Battleground* bg = target->GetBattleground())
         {
             if (bg->isArena())
             {
                 WorldPacket data(SMSG_ARENA_UNIT_DESTROYED, 8);
                 data << GetGUID();
                 target->GetSession()->SendPacket(&data);
             }
         }
     }
     WorldPacket data(SMSG_DESTROY_OBJECT, 8 + 1);
     data << GetGUID();
     data << uint8(onDeath ? 1 : 0);
     target->GetSession()->SendPacket(&data);
 }
References ASSERT, bg(), Player::GetBattleground(), GetGUID(), Player::GetSession(), isType(), WorldSession::SendPacket(), SMSG_ARENA_UNIT_DESTROYED, SMSG_DESTROY_OBJECT, TYPEMASK_PLAYER, and TYPEMASK_UNIT.
Referenced by Player::_StoreItem(), WorldObject::DestroyForNearbyPlayers(), Player::DestroyForPlayer(), Player::DestroyItem(), Player::EquipItem(), and Player::UpdateVisibilityOf().
ForceValuesUpdateAtIndex()
void Object::ForceValuesUpdateAtIndex (uint32 i)
Definition at line 2173 of file Object.cpp.
 {
     _changesMask.SetBit(i);
     AddToObjectUpdateIfNeeded();
 }
References _changesMask, AddToObjectUpdateIfNeeded(), and UpdateMask::SetBit().
Referenced by spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript::ActivateSpirit(), Group::BroadcastGroupUpdate(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), WorldSession::DoLootRelease(), and Player::SendLoot().
GetByteValue()
uint8 Object::GetByteValue (uint16 index, uint8 offset) const
Definition at line 318 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     ASSERT(offset < 4);
     return *(((uint8*) &m_uint32Values[index]) + offset);
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Player::_SaveCharacter(), Player::CreateCorpse(), Player::GetBankBagSlotCount(), Player::GetBarberShopCost(), Unit::getClass(), Player::GetDrunkValue(), Pet::GetFreeTalentPoints(), Unit::getGender(), GameObject::GetGoAnimProgress(), GameObject::GetGoArtKit(), GameObject::GetGoState(), GameObject::GetGoType(), Unit::GetModelForForm(), Unit::getPowerType(), Unit::getRace(), Unit::GetShapeshiftForm(), Unit::GetSheath(), Unit::getStandState(), WorldSession::HandleMirrorImageDataRequest(), Creature::LoadCreaturesAddon(), Unit::SetCharm(), and Unit::SetMinion().
GetEntry()
uint32 Object::GetEntry () const inline
Definition at line 101 of file Object.h.
 { return GetUInt32Value(OBJECT_FIELD_ENTRY); }
References GetUInt32Value(), and OBJECT_FIELD_ENTRY.
Referenced by PetAI::_canMeleeAttack(), Spell::_cast(), Unit::_EnterVehicle(), Unit::_ExitVehicle(), Map::_GetScriptCreatureSourceOrTarget(), Map::_GetScriptPlayerSourceOrTarget(), Map::_GetScriptUnit(), Unit::_IsValidAttackTarget(), Player::_LoadItem(), Guild::BankMoveItemData::_ReserveSpace(), Player::_StoreItem(), GameObject::ActivateToQuest(), BattlegroundAV::AddAVCreature(), InstanceScript::AddDoor(), Player::AddItemToBuyBackSlot(), InstanceScript::AddMinion(), InstanceScript::AddObject(), Vehicle::AddPassenger(), Player::AddQuestAndCheckCompletion(), HostileReference::addThreat(), Spell::AddUnitTarget(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::AllowAction(), Player::ApplyEquipCooldown(), ArcherAI::ArcherAI(), TotemAI::AttackStart(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::AttackStart(), boss_brutallus::boss_brutallusAI::AttackStart(), npc_suppresser::npc_suppresserAI::AttackStart(), boss_four_horsemen::boss_four_horsemenAI::AttackStart(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::AttackStart(), npc_doctor::npc_doctorAI::BeginEvent(), boss_four_horsemen::boss_four_horsemenAI::boss_four_horsemenAI(), boss_freya_summons::boss_freya_summonsAI::boss_freya_summonsAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::boss_lieutenant_drakeAI(), boss_twin_valkyrAI::boss_twin_valkyrAI(), AuctionEntry::BuildAuctionInfo(), Player::BuildEnchantmentsInfoData(), Player::BuyItemFromVendorSlot(), boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::CanAIAttack(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::CanAIAttack(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::CanAIAttack(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::CanAIAttack(), boss_anubarak_trial::boss_anubarak_trialAI::CanAIAttack(), npc_swarm_scarab::npc_swarm_scarabAI::CanAIAttack(), npc_nerubian_burrower::npc_nerubian_burrowerAI::CanAIAttack(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), boss_sindragosa::boss_sindragosaAI::CanAIAttack(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::CanAIAttack(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::CanAIAttack(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::CanAIAttack(), boss_illidan_stormrage::boss_illidan_stormrageAI::CanAIAttack(), boss_tyrannus::boss_tyrannusAI::CanAIAttack(), npc_pos_freed_slave::npc_pos_freed_slaveAI::CanAIAttack(), npc_mindless_ghoul::npc_mindless_ghoulAI::CanAIAttack(), npc_tirion_fordring_tft::npc_tirion_fordringAI::CanAIAttack(), npc_terenas_menethil::npc_terenas_menethilAI::CanAIAttack(), npc_risen_archmage::npc_risen_archmageAI::CanAIAttack(), npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack(), npc_thrall_bfu::npc_thrall_bfuAI::CanAIAttack(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::CanAIAttack(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::CanAIAttack(), PetAI::CanAttack(), Player::CanBankItem(), Item::CanBeMergedPartlyWith(), npc_steam_powered_auctioneer::npc_steam_powered_auctioneerAI::CanBeSeen(), npc_mei_francis_mount::npc_mei_francis_mountAI::CanBeSeen(), npc_wg_demolisher_engineer::canBuild(), npc_wg_siege_machine::npc_wg_siege_machineAI::CanControlVehicle(), WorldObject::CanDetect(), Player::CanEquipItem(), Spell::CanOpenLock(), Guild::BankMoveItemData::CanStore(), Player::CanStoreItem(), Player::CanStoreItems(), Player::CanTakeMoreSimilarItems(), Player::CanUnequipItem(), Player::CanUseItem(), Unit::CastPetAura(), spell_orbital_supports::spell_orbital_supports_AuraScript::CheckAreaTarget(), spell_gen_av_drekthar_presence::CheckAreaTarget(), spell_demolisher_ride_vehicle::spell_demolisher_ride_vehicle_SpellScript::CheckCast(), spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript::CheckCast(), Spell::CheckCast(), Spell::CheckItems(), Spell::CheckPetCast(), spell_sindragosa_permeating_chill::spell_sindragosa_permeating_chill_AuraScript::CheckProc(), Item::CloneItem(), instance_blackrock_spire::instance_blackrock_spireMapScript::CreatureLooted(), boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI::DamageTaken(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::DamageTaken(), boss_sartharion::boss_sartharionAI::DamageTaken(), npc_gunship::npc_gunshipAI::DamageTaken(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken(), npc_molten_golem::npc_molten_golemAI::DamageTaken(), boss_brutallus::boss_brutallusAI::DamageTaken(), boss_kalec::boss_kalecAI::DamageTaken(), boss_razuvious::boss_razuviousAI::DamageTaken(), boss_kologarn::boss_kologarnAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), MotionMaster::DelayedDelete(), SummonList::DespawnEntry(), BattlegroundIC::DestroyGate(), BattlegroundSA::DestroyGate(), Player::DestroyItem(), Player::DestroyItemCount(), boss_twin_valkyrAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_pos_leader_second::npc_pos_leader_secondAI::DoAction(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::DoAction(), boss_thaddius_summon::boss_thaddius_summonAI::DoAction(), npc_molten_golem::npc_molten_golemAI::DoAction(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::DoAction(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), ScriptedAI::DoResetThreat(), Spell::DoSpellHitOnUnit(), InstanceScript::DoUseDoorOrButton(), CreatureAI::DoZoneInCombat(), SummonList::DoZoneInCombat(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), Spell::EffectAddHonor(), Spell::EffectDurabilityDamage(), Spell::EffectFeedPet(), Spell::EffectInebriate(), Spell::EffectPersistentAA(), Spell::EffectScriptEffect(), Spell::EffectSummonChangeItem(), Spell::EffectSummonPet(), Spell::EffectWeaponDmg(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), GameObject::EnableCollision(), boss_sartharion_dragonAI::EnterCombat(), boss_servant_quarters::boss_servant_quartersAI::EnterCombat(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::EnterCombat(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::EnterCombat(), npc_argent_soldier::npc_argent_soldierAI::EnterCombat(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::EnterCombat(), boss_twin_valkyrAI::EnterCombat(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::EnterCombat(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::EnterCombat(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::EnterCombat(), npc_hol_monument::npc_hol_monumentAI::EnterCombat(), boss_freya_summons::boss_freya_summonsAI::EnterCombat(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::EnterCombat(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::EnterCombat(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::EnterCombat(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::EnterCombat(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), boss_brutallus::boss_brutallusAI::EnterCombat(), npc_rinji::npc_rinjiAI::EnterCombat(), npc_sindragosa_trash::npc_sindragosa_trashAI::EnterCombat(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::EnterCombat(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::EnterCombat(), npc_mrfloppy::npc_mrfloppyAI::EnterCombat(), CreatureAI::EnterEvadeMode(), GuardAI::EnterEvadeMode(), hyjalAI::EnterEvadeMode(), spell_dk_death_grip::EntryCheck(), Player::EquipItem(), EquippedOk(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundIC::EventPlayerClickedOnFlag(), BattlegroundAV::EventPlayerClickedOnFlag(), BattlegroundSA::EventPlayerClickedOnFlag(), BattlegroundSA::EventPlayerDamagedGO(), BattlegroundSA::EventPlayerUsedGO(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), npc_escortAI::FillPointMovementListForCreature(), SmartScript::FillScript(), Creature::GetAIName(), GameObject::GetAIName(), Unit::GetAllMinionsByEntry(), boss_hadronox::boss_hadronoxAI::GetData(), boss_krik_thir::boss_krik_thirAI::GetData(), boss_dred::boss_dredAI::GetData(), boss_novos::boss_novosAI::GetData(), boss_slad_ran::boss_slad_ranAI::GetData(), boss_anomalus::boss_anomalusAI::GetData(), boss_magus_telestra::boss_magus_telestraAI::GetData(), npc_wg_quest_giver::GetDialogStatus(), Unit::GetEffectiveResistChance(), SummonList::GetEntryCount(), npc_arthas::npc_arthasAI::GetEventNpc(), NPCStaveQuestAI::GetFormEntry(), Player::GetItemCount(), Bag::GetItemCount(), Creature::GetNameForLocaleIdx(), GameObject::GetNameForLocaleIdx(), Player::GetNextQuest(), spell_gen_on_tournament_mount::GetPennatSpellId(), Player::GetQuestDialogStatus(), SmartScript::GetScript(), Creature::GetScriptId(), boss_twin_valkyrAI::GetSister(), SmartScript::GetTargets(), Item::GetTemplate(), Creature::GetTrainerSpells(), Creature::GetVendorItems(), npc_escortAI::GetWaypointPosition(), go_bells::go_bellsAI::go_bellsAI(), go_soulwell::go_soulwellAI::go_soulwellAI(), WorldSession::HandleAuctionSellItem(), AuraEffect::HandleAuraDummy(), WorldSession::HandleAutoBankItemOpcode(), WorldSession::HandleAutoStoreBankItemOpcode(), spell_dk_death_grip::HandleBaseDummy(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBuybackItem(), misc_commandscript::HandleCreatePetCommand(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::HandleDummy(), spell_q12851_going_bearback::HandleEffectApply(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::HandleExtraEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::HandleExtraEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::HandleExtraEvent(), gobject_commandscript::HandleGameObjectInfoCommand(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGetMailList(), BattlefieldWG::HandleKill(), BattlegroundSA::HandleKillUnit(), BattlegroundAV::HandleKillUnit(), BattlegroundIC::HandleKillUnit(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectApply(), AuraEffect::HandlePeriodicHealthFunnelAuraTick(), WorldSession::HandlePetAction(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), Unit::HandleProcTriggerSpell(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSocketOpcode(), Unit::HandleSpellClick(), Battleground::HandleTriggerBuff(), WorldSession::HandleUseItemOpcode(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), WorldSession::HandleWrapItemOpcode(), SummonList::HasEntry(), Creature::hasInvolvedQuest(), GameObject::hasInvolvedQuest(), Player::HasItemCount(), Player::HasItemOrGemWithIdEquipped(), Creature::hasQuest(), GameObject::hasQuest(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), BfWGGameObjectBuilding::Init(), boss_twilight_corrupter::boss_twilight_corrupterAI::InitializeAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), Pet::InitLevelupSpellsForLevel(), CharmInfo::InitPossessCreateSpells(), Guardian::InitStatsForLevel(), Totem::InitSummon(), Unit::InitTamedPet(), NPCStaveQuestAI::InNormalForm(), SmartScript::InstallTemplate(), Creature::isCanInteractWithBattleMaster(), Creature::IsDungeonBoss(), spell_item_unsated_craving::isException(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::IsFuture(), Creature::IsImmuneToKnockback(), Pet::IsPermanentPetFor(), Unit::IsPetAura(), Minion::IsPetGhoul(), SmartScript::IsSmart(), SmartScript::IsSmartGO(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), boss_archimonde::boss_archimondeAI::JustDied(), boss_sartharion_dragonAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustDied(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustDied(), boss_thaddius_summon::boss_thaddius_summonAI::JustDied(), boss_naxxramas_misc::boss_naxxramas_miscAI::JustDied(), boss_freya_iron_root::boss_freya_iron_rootAI::JustDied(), boss_freya_summons::boss_freya_summonsAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::JustDied(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), npc_scholomance_occultist::npc_scholomance_occultistAI::JustReachedHome(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustReachedHome(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustRespawned(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_anubrekhan::boss_anubrekhanAI::JustSummoned(), boss_grobbulus::boss_grobbulusAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), brann_bronzebeard::brann_bronzebeardAI::JustSummoned(), boss_auriaya::boss_auriayaAI::JustSummoned(), boss_flame_leviathan::boss_flame_leviathanAI::JustSummoned(), boss_freya::boss_freyaAI::JustSummoned(), boss_kologarn::boss_kologarnAI::JustSummoned(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), npc_archmage_landalock::npc_archmage_landalockAI::JustSummoned(), boss_eregos::boss_eregosAI::JustSummoned(), boss_onyxia::boss_onyxiaAI::JustSummoned(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_majordomo::boss_majordomoAI::JustSummoned(), boss_midnight::boss_midnightAI::JustSummoned(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), boss_halazzi::boss_halazziAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustSummoned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::JustSummoned(), boss_taldaram::boss_taldaramAI::JustSummoned(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::JustSummoned(), boss_sartharion::boss_sartharionAI::JustSummoned(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustSummoned(), boss_halion::boss_halionAI::JustSummoned(), boss_paletress::boss_paletressAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), boss_gluth::boss_gluthAI::JustSummoned(), boss_malygos::boss_malygosAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_svala::boss_svalaAI::JustSummoned(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustSummoned(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_supremus::boss_supremusAI::JustSummoned(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustSummoned(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::JustSummoned(), boss_alar::boss_alarAI::JustSummoned(), boss_kaelthas::boss_kaelthasAI::JustSummoned(), boss_vaelastrasz::boss_vaelAI::JustSummoned(), boss_terestian_illhoof::boss_terestianAI::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_kurenai_captive::npc_kurenai_captiveAI::JustSummoned(), npc_earthmender_wilda::npc_earthmender_wildaAI::JustSummoned(), npc_varian_wrynn::npc_varian_wrynnAI::JustSummoned(), boss_ayamiss::boss_ayamissAI::JustSummoned(), npc_buru_egg::npc_buru_eggAI::JustSummoned(), Unit::Kill(), Player::KilledMonsterCredit(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::KilledUnit(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::KilledUnit(), boss_sartharion_dragonAI::KilledUnit(), boss_razorscale::boss_razorscaleAI::KilledUnit(), boss_svala::boss_svalaAI::KilledUnit(), kaylaan_the_lost::kaylaan_the_lostAI::KilledUnit(), boss_gluth::boss_gluthAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::Load(), VehicleAI::LoadConditions(), Creature::LoadEquipment(), LootItemStorage::LoadStoredLoot(), Guild::PlayerMoveItemData::LogBankEvent(), Guild::BankMoveItemData::LogBankEvent(), MailSender::MailSender(), npc_a_special_surprise::npc_a_special_surpriseAI::MeetQuestCondition(), AchievementCriteriaData::Meets(), Unit::MeleeDamageBonusDone(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::MoveInLineOfSight(), boss_aeonus::boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::MoveInLineOfSight(), boss_temporus::boss_temporusAI::MoveInLineOfSight(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), boss_gluth::boss_gluthAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_future_you::npc_future_youAI::MoveInLineOfSight(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::MoveInLineOfSight(), npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI::MoveInLineOfSight(), Player::MoveItemToInventory(), MotionMaster::MoveLand(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), npc_fos_leader_second::npc_fos_leader_secondAI::MovementInform(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), boss_four_horsemen::boss_four_horsemenAI::MovementInform(), npc_corki::npc_corkiAI::MovementInform(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::MovementInform(), boss_sartharion_dragonAI::MovementInform(), npc_wild_wyrm::npc_wild_wyrmAI::MovementInform(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::MovementInform(), MotionMaster::MoveTakeoff(), boss_four_horsemen::boss_four_horsemenAI::MoveToCorner(), npc_air_force_bots::npc_air_force_botsAI::npc_air_force_botsAI(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::npc_frostwing_vrykulAI(), npc_pet_gen_target_following_bomb::npc_pet_gen_target_following_bomb(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::npc_toc5_player_vehicleAI(), npc_wg_queue::npc_wg_queueAI::npc_wg_queueAI(), achievement_hadronox_denied::OnCheck(), achievement_watch_him_die::OnCheck(), achievement_better_off_dred::OnCheck(), achievement_oh_novos::OnCheck(), achievement_share_the_love::OnCheck(), achievement_snakes_whyd_it_have_to_be_snakes::OnCheck(), achievement_all_you_can_eat::OnCheck(), achievement_portal_jockey::OnCheck(), achievement_chaos_theory::OnCheck(), achievement_split_personality::OnCheck(), achievement_assembly_of_iron::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), achievement_iron_dwarf_medium_rare::OnCheck(), achievement_yogg_saron_kiss_and_make_up::OnCheck(), instance_scholomance::instance_scholomance_InstanceMapScript::OnCreatureCreate(), BattlefieldWG::OnCreatureCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnCreatureCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnCreatureCreate(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnCreatureCreate(), instance_stratholme::instance_stratholme_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnCreatureCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnCreatureCreate(), instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnCreatureCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnCreatureCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnCreatureCreate(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnCreatureCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnCreatureCreate(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureCreate(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnCreatureCreate(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnCreatureCreate(), instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript::OnCreatureCreate(), instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript::OnCreatureCreate(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnCreatureCreate(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnCreatureCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnCreatureCreate(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnCreatureCreate(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::OnCreatureCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnCreatureCreate(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnCreatureCreate(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnCreatureCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript::OnCreatureCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnCreatureCreate(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureCreate(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnCreatureCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnCreatureCreate(), instance_the_eye::instance_the_eye_InstanceMapScript::OnCreatureCreate(), instance_mechanar::instance_mechanar_InstanceMapScript::OnCreatureCreate(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnCreatureCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnCreatureCreate(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::OnCreatureCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnCreatureCreate(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::OnCreatureCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnCreatureCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureRemove(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureRemove(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureRemove(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureRemove(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureRemove(), instance_deadmines::instance_deadmines_InstanceMapScript::OnGameObjectCreate(), instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::OnGameObjectCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnGameObjectCreate(), instance_maraudon::instance_maraudon_InstanceMapScript::OnGameObjectCreate(), instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript::OnGameObjectCreate(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnGameObjectCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectCreate(), BattlefieldWG::OnGameObjectCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnGameObjectCreate(), instance_scholomance::instance_scholomance_InstanceMapScript::OnGameObjectCreate(), instance_stratholme::instance_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectCreate(), instance_zulaman::instance_zulaman_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnGameObjectCreate(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnGameObjectCreate(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnGameObjectCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnGameObjectCreate(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnGameObjectCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectCreate(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnGameObjectCreate(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::OnGameObjectCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectCreate(), instance_the_eye::instance_the_eye_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnGameObjectCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectRemove(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectRemove(), instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectRemove(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectRemove(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectRemove(), instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectRemove(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectRemove(), instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectRemove(), instance_black_temple::instance_black_temple_InstanceMapScript::OnGameObjectRemove(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectRemove(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectRemove(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectRemove(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectRemove(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_elune_fire::OnGossipHello(), go_call_tram::OnGossipHello(), go_main_chambers_access_panel::OnGossipHello(), npc_brewfest_keg_reciver::OnGossipHello(), npc_costumed_orphan_matron::OnGossipHello(), npc_aged_dying_ancient_kodo::OnGossipHello(), npcs_riverbreeze_and_silversky::OnGossipHello(), npc_essence_of_twin::OnGossipHello(), npc_fos_leader::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_razael_and_lyana::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), npc_shattrathflaskvendors::OnGossipHello(), npcs_ashyen_and_keleth::OnGossipHello(), npc_innkeeper::OnGossipHello(), npc_prof_alchemy::OnGossipHello(), npc_prof_blacksmith::OnGossipHello(), npc_engineering_tele_trinket::OnGossipHello(), npc_prof_leather::OnGossipHello(), npc_prof_tailor::OnGossipHello(), npc_taxi::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_simon_cluster::OnGossipHello(), go_corkis_prison::OnGossipHello(), go_jotunheim_cage::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), npc_ulduar_keeper::OnGossipSelect(), npc_engineering_tele_trinket::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_beaten_corpse::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), npc_captain_saeed::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), Player::OnGossipSelect(), SmartScript::OnInitialize(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnUnitDeath(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), instance_stratholme::instance_stratholme_InstanceMapScript::OnUnitDeath(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnUnitDeath(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnUnitDeath(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnUnitDeath(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), instance_oculus::instance_oculus_InstanceMapScript::OnUnitDeath(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnUnitDeath(), item_only_for_flight::OnUse(), item_gor_dreks_ointment::OnUse(), RisenArchmageCheck::operator()(), WretchedGhoulCleaner::operator()(), ValithriaDespawner::operator()(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::AllGameObjectsWithEntryInRange::operator()(), FrozenThroneResetWorker::operator()(), Acore::AllCreaturesOfEntryInRange::operator()(), FrostwingVrykulSearcher::operator()(), FlameLeviathanPursuedTargetSelector::operator()(), IgbArtilleryCheck::operator()(), CreatureTextBuilder::operator()(), PlayerTextBuilder::operator()(), Unit::OutDebugInfo(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::OwnTalk(), boss_temporus::boss_temporusAI::OwnTalk(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::PassengerBoarded(), npc_ulduar_vx001::npc_ulduar_vx001AI::PassengerBoarded(), npc_four_car_garage::npc_four_car_garageAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI::PassengerBoarded(), SmartAI::PausePath(), Spell::prepare(), Player::PrepareQuestMenu(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), BattlefieldWG::ProcessEvent(), Player::QuickEquipItem(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), Creature::Regenerate(), Unit::RemoveAllControlled(), Unit::RemoveAllMinionsByEntry(), Unit::RemoveFromWorld(), Player::RemoveItem(), Vehicle::RemovePassenger(), Player::RemovePet(), boss_servant_quarters::boss_servant_quartersAI::Reset(), hyjalAI::Reset(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::Reset(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::Reset(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::Reset(), npc_twilight_summon::npc_twilight_summonAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_argent_captainAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_thaddius_summon::boss_thaddius_summonAI::Reset(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::Reset(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::Reset(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::Reset(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::Reset(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_lake_frog::npc_lake_frogAI::Reset(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::Reset(), npc_phase_hunter::npc_phase_hunterAI::Reset(), npc_injured_patient::npc_injured_patientAI::Reset(), Creature::Respawn(), KillRewarder::Reward(), Pet::SavePetToDB(), Item::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_grand_champion::boss_grand_championAI::ScheduleAbilitiesEvents(), boss_jormungarAI::ScheduleEvents(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), CreatureTextMgr::SendChat(), npc_prof_alchemy::SendConfirmLearn(), npc_prof_blacksmith::SendConfirmLearn(), npc_prof_tailor::SendConfirmLearn(), npc_prof_alchemy::SendConfirmUnlearn(), npc_prof_blacksmith::SendConfirmUnlearn(), npc_prof_tailor::SendConfirmUnlearn(), Player::SendInitialPacketsBeforeAddToMap(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendListInventory(), Player::SendLoot(), MailDraft::SendMailTo(), npc_minigob_manabonk::npc_minigob_manabonkAI::SendMailToPlayer(), Player::SendNewItem(), WorldSession::SendPetNameQuery(), Spell::SendSpellCooldown(), WorldSession::SendStablePetCallback(), WorldSession::SendTaxiMenu(), BfCapturePoint::SetCapturePointData(), Unit::SetCharm(), Unit::SetCharmedBy(), boss_slad_ran::boss_slad_ranAI::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), boss_dred::boss_dredAI::SetData(), boss_novos::boss_novosAI::SetData(), boss_anomalus::boss_anomalusAI::SetData(), boss_keristrasza::boss_keristraszaAI::SetData(), npc_argent_soldier::npc_argent_soldierAI::SetData(), Minion::setDeathState(), Item::SetEnchantment(), SpellCastTargets::SetItemTarget(), Unit::SetMinion(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetPositionTraps(), Player::SetViewpoint(), Player::SetVisibleItemSlot(), SmartAI::SmartAI(), Unit::SpellDamageBonusDone(), npc_argent_captainAI::SpellHit(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::SpellHit(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::SpellHit(), npc_iron_watcher::npc_iron_watcherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_jungle_punch_target::npc_jungle_punch_targetAI::SpellHit(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), Unit::SpellPctDamageModsDone(), Player::SplitItem(), npc_escortAI::Start(), SmartAI::StartPath(), NPCStaveQuestAI::StoreAttackerGuidValue(), Guild::BankMoveItemData::StoreItem(), WorldObject::SummonCreatureGroup(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SummonedCreatureDespawn(), boss_ahune::boss_ahuneAI::SummonedCreatureDespawn(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDespawn(), npc_arthas::npc_arthasAI::SummonedCreatureDies(), boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDies(), boss_auriaya::boss_auriayaAI::SummonedCreatureDies(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_midnight::boss_midnightAI::SummonedCreatureDies(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::SummonedCreatureDies(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), npc_coren_direbrew::npc_coren_direbrewAI::SummonedCreatureDies(), boss_elder_nadox::boss_elder_nadoxAI::SummonedCreatureDies(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDies(), boss_the_lich_king::boss_the_lich_kingAI::SummonedCreatureDies(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), npc_ranshalla::npc_ranshallaAI::SummonedMovementInform(), Player::SwapItem(), npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI::Talk(), Player::TeleportTo(), TurretAI::TurretAI(), NPCStaveQuestAI::UnitIsUnfair(), Totem::UnSummon(), Pet::Update(), GameObject::Update(), Creature::Update(), TempSummon::Update(), SpellCastTargets::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), hyjal_trashAI::UpdateAI(), hyjalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_ulduar_icicle::npc_ulduar_icicleAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), boss_thorim_trap::boss_thorim_trapAI::UpdateAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI(), npc_jungle_punch_target::npc_jungle_punch_targetAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_doctor::npc_doctorAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI(), npc_suppresser::npc_suppresserAI::UpdateAI(), boss_sjonnir_dwarf::boss_sjonnir_dwarfAI::UpdateAI(), npc_warmage_violetstand::npc_warmage_violetstandAI::UpdateAI(), Player::UpdateAreaDependentAuras(), Guardian::UpdateAttackPowerAndDamage(), InstanceScript::UpdateDoorState(), Item::UpdateDuration(), Player::UpdateForQuestWorldObjects(), Item::UpdateItemSuffixFactor(), Guardian::UpdateMaxHealth(), Guardian::UpdateMaxPower(), boss_twin_valkyrAI::UpdateSharedHealth(), SpellCastTargets::UpdateTradeSlotItem(), BfWGGameObjectBuilding::UpdateTurretAttack(), GameObject::Use(), Player::VehicleSpellInitialize(), Player::VisualizeItem(), hyjalAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), Guild::BankTab::WriteSlotPacket(), Bag::~Bag(), and Vehicle::~Vehicle().
GetFloatValue()
float Object::GetFloatValue (uint16 index) const
Definition at line 312 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     return m_floatValues[index];
 }
References ASSERT, index, m_floatValues, m_valuesCount, and PrintIndexError().
Referenced by Player::_SaveStats(), ApplyModPositiveFloatValue(), ApplyModSignedFloatValue(), ApplyPercentModFloatValue(), SpellInfo::CalcPowerCost(), Unit::CalculateDamage(), AuraEffect::CalculatePeriodic(), Spell::DoSpellHitOnUnit(), Unit::GetAttackTime(), Unit::GetHoverHeight(), Unit::GetNegStat(), GetObjectScale(), Unit::GetPosStat(), DynamicObject::GetRadius(), Unit::GetResistanceBuffMods(), Unit::GetTotalAttackPowerValue(), Unit::GetUnitBlockChance(), Unit::GetUnitCriticalChance(), Spell::handle_immediate(), debug_commandscript::HandleDebugGetValueCommand(), Unit::HandleProcTriggerSpell(), Unit::ModSpellCastTime(), Player::outDebugValues(), Aura::RefreshDuration(), Player::Regenerate(), StaticTransport::RelocateToProgress(), Unit::SetHover(), Unit::SpellDoneCritChance(), Spell::TriggerGlobalCooldown(), Creature::UpdateMovementFlags(), and lfg::LFGMgr::UpdateRaidBrowser().
GetGUID() [1/2]
ObjectGuid Object::GetGUID () const inline
Definition at line 99 of file Object.h.
 { return GetGuidValue(OBJECT_FIELD_GUID); }
References GetGuidValue(), and OBJECT_FIELD_GUID.
Referenced by Unit::_AddAura(), Player::_addSpell(), Player::_AddSpellCooldown(), Unit::_ApplyAuraEffect(), Unit::_CreateAuraApplication(), Player::_LoadArenaTeamInfo(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadBrewOfTheMonth(), Player::_LoadDailyQuestStatus(), Player::_LoadGroup(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMail(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Player::_LoadSeasonalQuestStatus(), Player::_LoadSkills(), Player::_LoadSpellCooldowns(), Player::_LoadWeeklyQuestStatus(), Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), Player::_SaveDailyQuestStatus(), Player::_SaveEntryPoint(), Player::_SaveEquipmentSets(), Player::_SaveGlyphs(), Player::_SaveInventory(), Player::_SaveMonthlyQuestStatus(), Player::_SaveQuestStatus(), Player::_SaveSeasonalQuestStatus(), Player::_SaveSkills(), Player::_SaveSpellCooldowns(), Player::_SaveSpells(), Player::_SaveStats(), Player::_SaveTalents(), Player::_SaveWeeklyQuestStatus(), Player::_StoreItem(), Player::_StoreOrEquipNewItem(), Unit::_UnapplyAura(), Player::ActivateSpec(), Player::addActionButton(), Player::AddComboPoints(), Player::AddEnchantmentDuration(), Unit::AddGameObject(), Player::AddNewMailDeliverTime(), WorldObject::AddObjectToRemoveList(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Player::AddQuest(), Pet::addSpell(), Corpse::AddToWorld(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), Pet::AddToWorld(), Unit::AttackerStateUpdate(), Player::BindToInstance(), Unit::BuildCooldownPacket(), BuildCreateUpdateBlockForPlayer(), BuildMovementUpdate(), BuildOutOfRangeUpdateBlock(), Player::BuildPlayerRepop(), Player::CanBankItem(), Item::CanBeTraded(), Player::CanRollForItemInLFG(), WorldObject::CanSeeOrDetect(), Player::CanUninviteFromGroup(), Unit::CastCustomSpell(), Unit::CastDelayedSpellWithPeriodicAmount(), Player::CastItemCombatSpell(), Unit::CastSpell(), Player::CheckAreaExploreAndOutdoor(), Unit::CleanupBeforeRemoveFromMap(), Unit::ClearComboPointHolders(), Player::ClearComboPoints(), Item::ClearSoulboundTradeable(), Player::CompleteQuest(), Player::ContinueTaxiFlight(), Pet::CreateBaseAtCreature(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), Unit::DealMeleeDamage(), Unit::DelayOwnedAuras(), GameObject::Delete(), Creature::DeleteFromDB(), Item::DeleteFromDB(), Item::DeleteFromInventoryDB(), Item::DeleteRefundDataFromDB(), GameObject::DespawnOrUnsummon(), WorldObject::DestroyForNearbyPlayers(), DestroyForPlayer(), Player::DuelComplete(), Player::EnvironmentalDamage(), Player::EquipItem(), Unit::ExitVehicle(), Unit::GetCharmerOrOwnerOrOwnGUID(), Player::GetCorpse(), Unit::GetFactionTemplateEntry(), Player::GetGameObjectIfCanInteractWith(), Bag::GetSlotByItemGUID(), Unit::GetUnitCriticalChance(), Pet::HandleAsynchLoadSucceed(), Unit::HandleAuraProc(), Unit::HandleDummyAuraProc(), Unit::HandleEmoteCommand(), Player::HaveAtClient(), Player::InitDisplayIds(), Totem::InitStats(), TempSummon::InitStats(), Guardian::InitSummon(), Unit::InitTamedPet(), Player::inRandomLfgDungeon(), Player::isAllowedToLoot(), Player::IsAtLootRewardDistance(), Player::IsPetDismissed(), Player::isUsingLfg(), Player::LearnCustomSpells(), Player::learnSpell(), Player::LeaveBattleground(), Corpse::LoadCorpseFromDB(), Creature::LoadCreaturesAddon(), Player::LoadFromDB(), Player::ModifyArenaPoints(), Unit::ModifyAuraState(), Player::ModifyHonorPoints(), Player::ModifySpellCooldown(), Player::MoveItemToInventory(), Player::NeedSendSpectatorData(), Player::OnGossipSelect(), Unit::OutDebugInfo(), WorldObject::PlayDistanceSound(), Player::PrettyPrintRequirementsAchievementsList(), Unit::ProcDamageAndSpellFor(), Player::ProcessDelayedOperations(), Player::RefundItem(), DynamicObject::Remove(), Player::removeActionButton(), Unit::RemoveAllControlled(), Player::RemoveAtLoginFlag(), Unit::RemoveAura(), Unit::RemoveAurasByType(), Unit::RemoveCharmedBy(), Player::RemoveCorpse(), Player::RemovedInsignia(), Player::RemoveFromGroup(), GameObject::RemoveFromOwner(), Corpse::RemoveFromWorld(), Creature::RemoveFromWorld(), TempSummon::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Pet::RemoveFromWorld(), Unit::RemoveFromWorld(), Unit::RemoveGameObject(), Player::RemoveItemDependentAurasAndCasts(), Unit::RemoveNotOwnSingleTargetAuras(), Player::RemovePet(), Pet::RemoveSpellCooldown(), Creature::Respawn(), Unit::RestoreDisplayId(), Player::ResurrectPlayer(), Player::Satisfy(), Player::SaveGoldToDB(), Item::SaveRefundDataToDB(), Item::SaveToDB(), Creature::SelectVictim(), Player::SendActionButtons(), Creature::SendAIReaction(), Player::SendClearCooldown(), Player::SendCooldownEvent(), GameObject::SendCustomAnim(), Player::SendEnchantmentDurations(), Player::SendInstanceResetWarning(), Player::SendItemRetrievalMail(), Player::SendLoot(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), Player::SendNewItem(), Unit::SendPetTalk(), Unit::SendPlaySpellVisual(), Player::SendQuestConfirmAccept(), Player::SendRaidInfo(), Player::SendRefundInfo(), Player::SendSavedInstances(), Unit::SendSpellDamageImmune(), Unit::SendSpellDamageResist(), Unit::SendSpellMiss(), Item::SendTimeUpdate(), Item::SendUpdateSockets(), Unit::SetAuraStack(), Unit::SetCharm(), Unit::SetCharmedBy(), Unit::SetConfused(), Minion::setDeathState(), Player::setDeathState(), Player::SetDrunkValue(), Unit::SetFeared(), Unit::SetHealth(), Player::SetHomebind(), Player::SetInGuild(), Unit::SetLevel(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetMinion(), Player::SetMover(), Item::SetNotRefundable(), Unit::SetPower(), Unit::setPowerType(), Player::SetRandomWinner(), Player::SetSelection(), Item::SetState(), Unit::SetStunned(), Player::SpawnCorpseBones(), Unit::SpellDamageBonusDone(), Unit::SpellPctDamageModsDone(), Unit::SpellTakenCritChance(), Player::StopCastingBindSight(), Player::StopCastingCharm(), Bag::StoreItem(), Player::StoreLootItem(), Player::TeleportTo(), Totem::UnSummon(), Pet::Update(), GameObject::Update(), Creature::Update(), Player::Update(), Player::UpdateHomebindTime(), Player::UpdateNextMailTimeAndUnreads(), Player::UpdateSoulboundTradeItems(), Player::UpdateSpecCount(), GameObject::Use(), Player::VisualizeItem(), ~Object(), and WorldObject::~WorldObject().
GetGUID() [2/2]
static ObjectGuid Object::GetGUID (Object const * o) inline static
Definition at line 98 of file Object.h.
 { return o ? o->GetGUID() : ObjectGuid::Empty; }
References ObjectGuid::Empty, and GetGUID().
Referenced by Unit::_ApplyAura(), Aura::_ApplyForTarget(), Player::_ApplyItemMods(), Group::_cancelHomebindIfInstance(), Spell::_cast(), Map::_GetScriptCreature(), Map::_GetScriptCreatureSourceOrTarget(), Map::_GetScriptPlayer(), Map::_GetScriptPlayerSourceOrTarget(), Map::_GetScriptUnit(), Map::_GetScriptWorldObject(), Spell::_handle_finish_phase(), AuraApplication::_HandleEffect(), ticket_commandscript::_HandleGMTicketResponseAppendCommand(), Guild::_HasRankRight(), AuraApplication::_InitFlags(), Guild::_IsLeader(), WorldObject::_IsWithinDist(), Player::_LoadItem(), Player::_SaveInventory(), Map::_ScriptProcessDoor(), Guild::_SendBankContent(), Guild::_SendBankList(), PetAI::_stopAttack(), Player::_StoreItem(), Player::_StoreOrEquipNewItem(), Unit::_TryStackingOrRefreshingExistingAura(), Aura::_UnapplyForTarget(), AuctionHouseMgr::AddAItem(), LootItem::AddAllowedLooter(), npc_anubisath_sentinel::aqsentinelAI::AddBuddyToList(), Player::AddComboPoints(), Battleground::AddCreature(), FormationMgr::AddCreatureToGroup(), Player::AddEnchantmentDuration(), Unit::AddGameObject(), Spell::AddGOTarget(), BattlegroundQueue::AddGroup(), Group::AddInvite(), MailDraft::AddItem(), Player::AddItemToBuyBackSlot(), Group::AddLeaderInvite(), CreatureGroup::AddMember(), Group::AddMember(), Player::AddMItem(), Battleground::AddObject(), InstanceScript::AddObject(), Battlefield::AddOrSetPlayerToCorrectBfGroup(), Battleground::AddOrSetPlayerToCorrectBgGroup(), Vehicle::AddPassenger(), Battleground::AddPlayer(), BattlegroundAB::AddPlayer(), BattlegroundAV::AddPlayer(), BattlegroundBE::AddPlayer(), BattlegroundDS::AddPlayer(), BattlegroundEY::AddPlayer(), BattlegroundIC::AddPlayer(), BattlegroundNA::AddPlayer(), BattlegroundRL::AddPlayer(), BattlegroundRV::AddPlayer(), BattlegroundSA::AddPlayer(), BattlegroundWS::AddPlayer(), Map::AddPlayerToMap(), InstanceMap::AddPlayerToMap(), spell_rog_killing_spree::spell_rog_killing_spree_AuraScript::AddTarget(), Map::AddToMap(), Item::AddToUpdateQueueOf(), GameObject::AddUniqueUse(), Spell::AddUnitTarget(), BattlefieldWG::AddUpdateTenacity(), Channel::AddWatching(), LootItem::AllowedForPlayer(), Channel::Announce(), Player::ApplyEnchantment(), Player::ApplyEquipCooldown(), Player::ApplyEquipSpell(), AuraEffect::ApplySpellMod(), Battlefield::AskToLeaveQueue(), Unit::Attack(), Unit::AttackerStateUpdate(), TotemAI::AttackStart(), boss_malygos::boss_malygosAI::AttackStart(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::AttackStart(), npc_snobold_vassal::npc_snobold_vassalAI::AttackStart(), npc_vengeful_shade::npc_vengeful_shadeAI::AttackStart(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::AttackStart(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::AttackStart(), BanMgr::BanCharacter(), BeforeVisibilityDestroy< Creature >(), npc_doctor::npc_doctorAI::BeginEvent(), boss_vaelastrasz::boss_vaelAI::BeginSpeech(), Group::BroadcastPacket(), Group::BroadcastReadyCheck(), SocialMgr::BroadcastToFriendListers(), Guild::BroadcastToGuild(), Unit::BuildAuraStateUpdateForTarget(), ChatHandler::BuildChatPacket(), AuctionHouseObject::BuildListBidderItems(), AuctionHouseObject::BuildListOwnerItems(), WorldObjectChangeAccumulator::BuildPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), BattlegroundMgr::BuildPlayerJoinedBattlegroundPacket(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), Unit::CalcAbsorbResist(), CalculateSpellAmount(), Creature::CallAssistance(), npc_inner_demon::npc_inner_demonAI::CanAIAttack(), Player::CanAlwaysSee(), BGSpamProtect::CanAnnounce(), PetAI::CanAttack(), Spell::CanAutoCast(), Player::CanBankItem(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::CanBeSeen(), Spell::cancel(), Player::CanInteractWithQuestGiver(), InstanceMap::CannotEnter(), BattlegroundMap::CannotEnter(), WorldSession::CanOpenMailBox(), npc_commander_dawnforge::npc_commander_dawnforgeAI::CanStartEvent(), Player::CanStoreItem(), Player::CanStoreItem_InBag(), Player::CanStoreItems(), WorldSession::CanUseBank(), Unit::CastDelayedSpellWithPeriodicAmount(), GameObject::CastSpell(), Group::ChangeLeader(), CharacterActionIpLogger::CharacterIPLogAction(), Player::CharmSpellInitialize(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), Spell::CheckEffectTarget(), Spell::CheckItems(), spell_pri_vampiric_touch::CheckProc(), spell_rog_blade_flurry::CheckProc(), spell_sha_earthliving_weapon::CheckProc(), spell_warl_drain_soul::CheckProc(), violet_hold_trashAI::ClearDoorSealAura(), Map::ConvertCorpseToBones(), Group::CountTheRoll(), Corpse::Create(), Item::Create(), Bag::Create(), Group::Create(), Guild::Create(), Aura::Create(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), netherspite_infernal::netherspite_infernalAI::DamageTaken(), npc_calvin_montague::npc_calvin_montagueAI::DamageTaken(), npc_inner_demon::npc_inner_demonAI::DamageTaken(), Unit::DealDamage(), Unit::DealMeleeDamage(), Spell::DelayedChannel(), MailDraft::deleteIncludedItems(), SummonList::Despawn(), WorldObject::DestroyForNearbyPlayers(), Player::DestroyItem(), Player::DestroyItemCount(), Vehicle::Dismiss(), boss_illidari_council::boss_illidari_councilAI::DoAction(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), PetAI::DoAttack(), Spell::DoCreateItem(), ConfusedMovementGenerator< T >::DoFinalize(), WorldSession::DoLootRelease(), ScriptedAI::DoPlaySoundToSet(), Spell::DoSpellHitOnUnit(), instance_mechanar::instance_mechanar_InstanceMapScript::DoSummonAction(), ScriptedAI::DoTeleportPlayer(), Spell::DoTriggersOnSpellHit(), FlightPathMovementGenerator::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), Player::DuelComplete(), Spell::EffectAddHonor(), Spell::EffectBind(), Spell::EffectCharge(), Spell::EffectDisEnchant(), Spell::EffectDispel(), Spell::EffectDispelMechanic(), Spell::EffectDuel(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectForceDeselect(), Spell::EffectHeal(), Spell::EffectInstaKill(), Spell::EffectLearnSpell(), Spell::EffectMilling(), Spell::EffectOpenLock(), Spell::EffectPersistentAA(), Spell::EffectPickPocket(), Spell::EffectProspecting(), Spell::EffectQuestStart(), Spell::EffectRedirectThreat(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectSkinning(), Spell::EffectStealBeneficialBuff(), Spell::EffectSummonChangeItem(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Spell::EffectSummonType(), Spell::EffectTransmitted(), Spell::EffectUnlearnSpecialization(), Spell::EffectUntrainTalents(), Spell::EffectWeaponDmg(), Battleground::EndBattleground(), boss_malchezaar::boss_malchezaarAI::EnfeebleHealthEffect(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), npc_phase_hunter::npc_phase_hunterAI::EnterCombat(), BattlegroundEY::EventPlayerClickedOnFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAV::EventPlayerClickedOnFlag(), BattlegroundEY::EventPlayerDroppedFlag(), BattlegroundWS::EventPlayerDroppedFlag(), npc_unworthy_initiate::npc_unworthy_initiateAI::EventStart(), BGQueueRemoveEvent::Execute(), AuraMunchingQueue::Execute(), IceTombSummonEvent::Execute(), VerasEnvenom::Execute(), DealDebrisDamage::Execute(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), ChatHandler::extractPlayerTarget(), npc_shay_leafrunner::npc_shay_leafrunnerAI::FailQuest(), Loot::FillFFALoot(), Loot::FillLoot(), Loot::FillNonQuestNonFFAConditionalLoot(), Loot::FillNotNormalLootFor(), Loot::FillQuestLoot(), spell_send_mug_target_picker::spell_send_mug_target_picker_SpellScript::FilterTargets(), TimedFleeingMovementGenerator::Finalize(), BattlefieldWG::FindAndRemoveVehicleFromList(), PathGenerator::FindSmoothPath(), Spell::finish(), lfg::LFGMgr::FinishDungeon(), Channel::FlagsNotify(), Creature::FocusTarget(), CreatureGroup::FormationReset(), boss_erekem::boss_erekemAI::GetChainHealTargetGUID(), GetGUID(), WorldSession::GetGuidLow(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::GetHarpoonGunIdForThisHFS(), FollowerAI::GetLeaderForFollower(), Unit::GetMagicHitRedirectTarget(), Loot::GetMaxSlotInLootFor(), Unit::GetMeleeAttackPoint(), SpellCastTargets::GetObjectTargetChannel(), ChatHandler::GetPlayerGroupAndGUIDByName(), WorldSession::GetPlayerInfo(), GetPlayerInfo(), ThreatContainer::getReferenceByTarget(), CreatureTextMgr::GetRepeatGroup(), Vehicle::GetSeatForPassenger(), Vehicle::GetSeatIteratorForPassenger(), SmartScript::GetTargets(), WorldObject::GetTransGUID(), Unit::GetTransGUID(), GetUpdateFieldData(), GetVelocity(), npc_anubisath_sentinel::aqsentinelAI::GiveBuddyMyList(), GmTicket::GmTicket(), go_wind_stone::go_wind_stoneAI::GossipHello(), Group::GroupLoot(), Guild::HandleAcceptMember(), WorldSession::HandleAcceptTradeOpcode(), account_commandscript::HandleAccountCreateCommand(), spell_rog_deadly_poison::HandleAfterHit(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), BattlegroundEY::HandleAreaTrigger(), BattlegroundWS::HandleAreaTrigger(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamDisbandOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), Pet::HandleAsynchLoadFailed(), Pet::HandleAsynchLoadSucceed(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleAuctionSellItem(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraLinked(), AuraEffect::HandleAuraOpenStable(), Unit::HandleAuraProc(), Aura::HandleAuraSpecificMods(), WorldSession::HandleAutostoreLootItemOpcode(), ban_commandscript::HandleBanInfoCharacterCommand(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::HandleBeforeHit(), WorldSession::HandleBfEntryInviteResponse(), WorldSession::HandleBusyTradeOpcode(), WorldSession::HandleBuybackItem(), Guild::HandleBuyBankTab(), WorldSession::HandleBuyItemInSlotOpcode(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarArenaTeam(), WorldSession::HandleCalendarComplain(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarEventInvite(), WorldSession::HandleCalendarEventModeratorStatus(), WorldSession::HandleCalendarEventRemoveInvite(), WorldSession::HandleCalendarEventRsvp(), WorldSession::HandleCalendarEventSignup(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCalendarGetEvent(), WorldSession::HandleCalendarGetNumPending(), WorldSession::HandleCalendarGuildFilter(), WorldSession::HandleCalendarRemoveEvent(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleChangeSeatsOnControlledVehicle(), character_commandscript::HandleCharacterCheckBankCommand(), misc_commandscript::HandleCreatePetCommand(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugThreatListCommand(), debug_commandscript::HandleDebugUpdateCommand(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleDismissCritter(), WorldSession::HandleDuelAcceptedOpcode(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::HandleDummy(), spell_dk_death_strike::HandleDummy(), spell_dk_scourge_strike::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), Unit::HandleDummyAuraProc(), AuraEffect::HandleEffect(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::HandleEffectApply(), WorldSession::HandleEquipmentSetSave(), WorldSession::HandleFarSightOpcode(), AuraEffect::HandleFeignDeath(), WorldSession::HandleForceSpeedChangeAck(), gobject_commandscript::HandleGameObjectSetStateCommand(), misc_commandscript::HandleGearStatsCommand(), WorldSession::HandleGetMailList(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGossipHelloOpcode(), OPvPCapturePointZM_GraveYard::HandleGossipOption(), WorldSession::HandleGossipSelectOptionOpcode(), WorldSession::HandleGroupChangeSubGroupOpcode(), misc_commandscript::HandleGroupSummonCommand(), WorldSession::HandleIgnoreTradeOpcode(), spell_sindragosa_frost_breath::spell_sindragosa_frost_breath_SpellScript::HandleInfusion(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleInspectHonorStatsOpcode(), instance_commandscript::HandleInstanceListBindsCommand(), WorldSession::HandleInstanceLockResponse(), instance_commandscript::HandleInstanceUnbindCommand(), Guild::HandleInviteMember(), BattlegroundIC::HandleKillUnit(), Guild::HandleLeaveMember(), WorldSession::HandleLfgGetStatus(), WorldSession::HandleLfgLeaveOpcode(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), WorldSession::HandleLfgSetBootVoteOpcode(), WorldSession::HandleLfgSetCommentOpcode(), WorldSession::HandleLfgSetRolesOpcode(), WorldSession::HandleLoadPetFromDBFirstCallback(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMoneyOpcode(), misc_commandscript::HandleMailBoxCommand(), WorldSession::HandleMailDelete(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberLogout(), Guild::HandleMemberWithdrawMoney(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMinimapPingOpcode(), modify_commandscript::HandleModifyFactionCommand(), WorldSession::HandleMountSpecialAnimOpcode(), misc_commandscript::HandleMovegensCommand(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleMoveWorldportAck(), misc_commandscript::HandleMuteCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetLinkCommand(), AuraEffect::HandleObsModPowerAuraTick(), WorldSession::HandleOfferPetitionOpcode(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectApply(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePartyAssignmentOpcode(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicEnergizeAuraTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), AuraEffect::HandlePeriodicManaLeechAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetRename(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), BfCapturePoint::HandlePlayerEnter(), OPvPCapturePoint::HandlePlayerEnter(), BattlefieldMgr::HandlePlayerEnterZone(), OutdoorPvPMgr::HandlePlayerEnterZone(), Battlefield::HandlePlayerEnterZone(), OutdoorPvP::HandlePlayerEnterZone(), BfCapturePoint::HandlePlayerLeave(), OPvPCapturePoint::HandlePlayerLeave(), BattlefieldMgr::HandlePlayerLeaveZone(), OutdoorPvPMgr::HandlePlayerLeaveZone(), Battlefield::HandlePlayerLeaveZone(), OutdoorPvP::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginOpcode(), spell_dk_dancing_rune_weapon::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_warl_drain_soul::HandleProc(), WorldSession::HandlePushQuestToParty(), quest_commandscript::HandleQuestComplete(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestLogRemoveQuest(), WorldSession::HandleQuestPushResult(), WorldSession::HandleRaidReadyCheckOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), WorldSession::HandleRandomRollOpcode(), WorldSession::HandleReadItem(), Guild::HandleRemoveMember(), WorldSession::HandleRequestAccountData(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ArenaSpectator::HandleResetCommand(), WorldSession::HandleResetInstancesOpcode(), PetAI::HandleReturnMovement(), spell_prince_taldaram_conjure_flame_sphere::spell_prince_taldaram_conjure_flame_sphere_SpellScript::HandleScript(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript2(), spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::spell_winter_veil_shoot_air_rifle_SpellScript::HandleScriptEffect(), spell_dk_pestilence::HandleScriptEffect(), spell_dru_glyph_of_starfire::HandleScriptEffect(), spell_hun_chimera_shot::HandleScriptEffect(), WorldSession::HandleSellItemOpcode(), misc_commandscript::HandleSendItemsCommand(), WorldSession::HandleSendMail(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMoneyCommand(), WorldSession::HandleSetActionButtonOpcode(), WorldSession::HandleSetActiveMoverOpcode(), WorldSession::HandleSetDungeonDifficultyOpcode(), Guild::HandleSetLeader(), WorldSession::HandleSetRaidDifficultyOpcode(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleSetTradeItemOpcode(), AuraEffect::HandleShapeshiftBoosts(), misc_commandscript::HandleSkirmishCommand(), WorldSession::HandleSocketOpcode(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), Unit::HandleSpellClick(), WorldSession::HandleStablePet(), WorldSession::HandleStablePetCallback(), WorldSession::HandleStableSwapPet(), WorldSession::HandleStableSwapPetCallback(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), misc_commandscript::HandleSummonCommand(), WorldSession::HandleTrainerBuySpellOpcode(), Battleground::HandleTriggerBuff(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleUnstablePetCallback(), Guild::HandleUpdateMemberRank(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWhoOpcode(), wp_commandscript::HandleWpModifyCommand(), WorldSession::HandleWrapItemOpcode(), Unit::HasAuraState(), Loot::hasItemFor(), Battlefield::HasPlayer(), OutdoorPvP::HasPlayer(), Player::HaveAtClient(), HostileReference::HostileReference(), BfWGGameObjectBuilding::Init(), npc_scarlet_miner::npc_scarlet_minerAI::InitCartQuest(), boss_twilight_corrupter::boss_twilight_corrupterAI::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), brann_bronzebeard::brann_bronzebeardAI::InitializeEvent(), lfg::LFGMgr::InitializeLockedDungeons(), Minion::InitStats(), Guardian::InitStatsForLevel(), Vehicle::InstallAccessory(), Channel::Invite(), BattlegroundMgr::InviteGroupToBG(), Battlefield::InvitePlayerToQueue(), Battlefield::InvitePlayerToWar(), Unit::IsAlwaysDetectableFor(), GameObject::IsAlwaysVisibleFor(), Unit::IsAlwaysVisibleFor(), Item::IsBindedNotWith(), Unit::IsInCombatWith(), boss_heigan::boss_heiganAI::IsInRoom(), BfCapturePoint::IsInsideObjective(), OPvPCapturePoint::IsInsideObjective(), GameObject::IsLootAllowedFor(), Unit::isPossessing(), Aura::IsRemovedOnShapeLost(), SpellInfo::IsStrongerAuraActive(), TriggerAI::IsSummonedBy(), npc_burning_spirit::npc_burning_spiritAI::IsSummonedBy(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), npc_inner_demon::npc_inner_demonAI::IsSummonedBy(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::IsSummonedBy(), npc_infernal_attacker::npc_infernal_attackerAI::IsSummonedBy(), npc_kservant::npc_kservantAI::IsSummonedBy(), npc_pet_gen_fetch_ball::IsSummonedBy(), npc_spirit_shade::npc_spirit_shadeAI::IsSummonedBy(), Creature::isTappedBy(), boss_sapphiron::boss_sapphironAI::IsValidExplosionTarget(), Channel::JoinChannel(), lfg::LFGMgr::JoinLfg(), Channel::JoinNotify(), lfg::LFGMgr::JoinRaidBrowser(), npc_zulaman_hostage::npc_zulaman_hostageAI::JustDied(), npc_buru_egg::npc_buru_eggAI::JustDied(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::JustDied(), npc_frost_tomb::npc_frost_tombAI::JustDied(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_archmage_landalock::npc_archmage_landalockAI::JustSummoned(), boss_ichoron::boss_ichoronAI::JustSummoned(), boss_xevozz::boss_xevozzAI::JustSummoned(), boss_zuramat::boss_zuramatAI::JustSummoned(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::JustSummoned(), boss_halazzi::boss_halazziAI::JustSummoned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), boss_paletress::boss_paletressAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_balinda::boss_balindaAI::JustSummoned(), boss_vaelastrasz::boss_vaelAI::JustSummoned(), boss_terestian_illhoof::boss_terestianAI::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), boss_broggok::boss_broggokAI::JustSummoned(), npc_commander_dawnforge::npc_commander_dawnforgeAI::JustSummoned(), boss_ayamiss::boss_ayamissAI::JustSummoned(), Channel::KickOrBan(), WorldSession::KickPlayer(), Unit::Kill(), PetAI::KilledUnit(), boss_xevozz::boss_xevozzAI::KilledUnit(), boss_taldaram::boss_taldaramAI::KilledUnit(), boss_anubrekhan::boss_anubrekhanAI::KilledUnit(), boss_malygos::boss_malygosAI::KilledUnit(), boss_cyanigosa::boss_cyanigosaAI::KilledUnit(), boss_erekem::boss_erekemAI::KilledUnit(), boss_ichoron::boss_ichoronAI::KilledUnit(), boss_zuramat::boss_zuramatAI::KilledUnit(), boss_ick::boss_ickAI::KilledUnit(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::LapseAction(), Player::LearnPetTalent(), Channel::LeaveChannel(), Channel::LeaveNotify(), lfg::LFGMgr::LfrSearchAdd(), lfg::LFGMgr::LfrSearchRemove(), lfg::LFGMgr::LfrSetComment(), Channel::List(), Player::LoadFromDB(), WaypointMovementGenerator< Creature >::LoadPath(), Pet::LoadPetFromDB(), LogCommandUsage(), WorldSession::LogoutPlayer(), Loot::LootItemInSlot(), MailReceiver::MailReceiver(), MailSender::MailSender(), lfg::LFGMgr::MakeNewGroup(), ArenaTeam::MassInviteToEvent(), Guild::MassInviteToEvent(), Condition::Meets(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), ArenaTeam::MemberLost(), ArenaTeam::MemberWon(), MotionMaster::MoveCharge(), MotionMaster::MoveChase(), MotionMaster::MoveConfused(), MotionMaster::MoveFleeing(), MotionMaster::MoveFollow(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_doomfire_targetting::npc_doomfire_targettingAI::MoveInLineOfSight(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_twiggy_flathead::npc_twiggy_flatheadAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI::MoveInLineOfSight(), MotionMaster::MoveJump(), PetAI::MovementInform(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), MotionMaster::MovePath(), MotionMaster::MovePoint(), MotionMaster::MoveRandom(), MotionMaster::MoveSeekAssistance(), MotionMaster::MoveSeekAssistanceDistract(), MotionMaster::MoveTargetedHome(), MotionMaster::MoveTaxiFlight(), Group::NeedBeforeGreed(), Loot::NotifyQuestItemRemoved(), npc_ancestral_wolf::npc_ancestral_wolfAI::npc_ancestral_wolfAI(), WaypointMovementGenerator< Creature >::OnArrived(), BattlefieldWG::OnBattleStart(), achievement_intense_cold::OnCheck(), achievement_once_bitten_twice_shy::OnCheck(), instance_scholomance::instance_scholomance_InstanceMapScript::OnCreatureCreate(), BattlefieldWG::OnCreatureCreate(), OutdoorPvP::OnCreatureCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnCreatureCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnCreatureCreate(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnCreatureCreate(), instance_stratholme::instance_stratholme_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnCreatureCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate(), instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnCreatureCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnCreatureCreate(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnCreatureCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnCreatureCreate(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureCreate(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnCreatureCreate(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnCreatureCreate(), instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript::OnCreatureCreate(), instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript::OnCreatureCreate(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnCreatureCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnCreatureCreate(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnCreatureCreate(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnCreatureCreate(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::OnCreatureCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnCreatureCreate(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnCreatureCreate(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript::OnCreatureCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnCreatureCreate(), instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureCreate(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnCreatureCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnCreatureCreate(), instance_the_eye::instance_the_eye_InstanceMapScript::OnCreatureCreate(), instance_mechanar::instance_mechanar_InstanceMapScript::OnCreatureCreate(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnCreatureCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnCreatureCreate(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::OnCreatureCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnCreatureCreate(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::OnCreatureCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnCreatureCreate(), OutdoorPvP::OnCreatureRemove(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureRemove(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureRemove(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnGameObjectCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), OutdoorPvP::OnGameObjectCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::OnGameObjectCreate(), instance_scholomance::instance_scholomance_InstanceMapScript::OnGameObjectCreate(), instance_stratholme::instance_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnGameObjectCreate(), instance_zulaman::instance_zulaman_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnGameObjectCreate(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnGameObjectCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnGameObjectCreate(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnGameObjectCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnGameObjectCreate(), instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::OnGameObjectCreate(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate(), instance_arcatraz::instance_arcatraz_InstanceMapScript::OnGameObjectCreate(), instance_the_eye::instance_the_eye_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnGameObjectCreate(), OutdoorPvP::OnGameObjectRemove(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove(), instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectRemove(), go_shadowforge_brazier::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_lokhtos_darkbargainer::OnGossipHello(), boss_gloomrel::OnGossipHello(), boss_doomrel::OnGossipHello(), boss_majordomo::OnGossipHello(), npc_grandmother::OnGossipHello(), npc_barnes::OnGossipHello(), npc_death_knight_initiate::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_fairbanks::OnGossipHello(), npc_augustus_the_touched::OnGossipHello(), npc_parqual_fintallas::OnGossipHello(), npc_varian_wrynn::OnGossipHello(), npc_thrall_bfu::OnGossipHello(), npc_zulaman_hostage::OnGossipHello(), npc_brewfest_keg_reciver::OnGossipHello(), npc_costumed_orphan_matron::OnGossipHello(), npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), npc_tyrande_whisperwind::OnGossipHello(), npc_arthas::OnGossipHello(), npc_cos_chromie_middle::OnGossipHello(), npc_rizzle_sprysprocket::OnGossipHello(), npc_aged_dying_ancient_kodo::OnGossipHello(), npc_lady_jaina_proudmoore::OnGossipHello(), npc_nat_pagle::OnGossipHello(), npcs_riverbreeze_and_silversky::OnGossipHello(), npc_bunthen_plainswind::OnGossipHello(), npc_great_bear_spirit::OnGossipHello(), npc_silva_filnaveth::OnGossipHello(), npc_thrall_warchief::OnGossipHello(), npc_braug_dimspirit::OnGossipHello(), npc_steward_of_time::OnGossipHello(), npc_stone_watcher_of_norgannon::OnGossipHello(), npc_beaten_corpse::OnGossipHello(), npc_plucky::OnGossipHello(), npc_rivern_frostwind::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_fos_leader::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_keeper::OnGossipHello(), npc_vh_sinclari::OnGossipHello(), npc_iruk::OnGossipHello(), npc_shandy_dalaran::OnGossipHello(), npc_razael_and_lyana::OnGossipHello(), npc_mcmanus::OnGossipHello(), npc_vekjik::OnGossipHello(), npc_avatar_of_freya::OnGossipHello(), npc_roxi_ramrocket::OnGossipHello(), npc_wg_demolisher_engineer::OnGossipHello(), npc_wg_spirit_guide::OnGossipHello(), npc_wg_queue::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), npc_finklestein::OnGossipHello(), adyen_the_lightbringer::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_professor_dabiri::OnGossipHello(), npc_drake_dealer_hurlunk::OnGossipHello(), npcs_flanis_swiftwing_and_kagrosh::OnGossipHello(), npc_raliq_the_drunk::OnGossipHello(), npc_salsalabim::OnGossipHello(), npc_shattrathflaskvendors::OnGossipHello(), npc_zephyr::OnGossipHello(), npc_ishanah::OnGossipHello(), npc_floon::OnGossipHello(), npc_slim::OnGossipHello(), npcs_ashyen_and_keleth::OnGossipHello(), npc_cooshcoosh::OnGossipHello(), npc_elder_kuruti::OnGossipHello(), npc_mortog_steamhead::OnGossipHello(), npc_timothy_daniels::OnGossipHello(), npc_innkeeper::OnGossipHello(), npc_prof_alchemy::OnGossipHello(), npc_prof_blacksmith::OnGossipHello(), npc_engineering_tele_trinket::OnGossipHello(), npc_prof_leather::OnGossipHello(), npc_prof_tailor::OnGossipHello(), npc_artorius::OnGossipHello(), npc_simone::OnGossipHello(), npc_nelson::OnGossipHello(), npc_franklin::OnGossipHello(), npc_taxi::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), npc_riggle_bassbait::OnGossipHello(), npc_sayge::OnGossipHello(), npc_locksmith::OnGossipHello(), npc_venomhide_hatchling::OnGossipHello(), go_evil_book_for_dummies::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_the_pearl_of_the_depths::OnGossipHello(), go_pressure_valve::OnGossipHello(), go_brazier::OnGossipHello(), go_finklestein_cauldron::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_ahune_ice_stone::OnGossipHello(), go_skull_pile::OnGossipHello(), go_fel_crystalforge::OnGossipHello(), go_bashir_crystalforge::OnGossipHello(), go_table_theka::OnGossipHello(), go_amberpine_outhouse::OnGossipHello(), go_hive_pod::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), npc_lokhtos_darkbargainer::OnGossipSelect(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_augustus_the_touched::OnGossipSelect(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), npc_tyrande_whisperwind::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_lady_jaina_proudmoore::OnGossipSelect(), npc_nat_pagle::OnGossipSelect(), npc_bunthen_plainswind::OnGossipSelect(), npc_great_bear_spirit::OnGossipSelect(), npc_silva_filnaveth::OnGossipSelect(), npc_thrall_warchief::OnGossipSelect(), npc_stone_watcher_of_norgannon::OnGossipSelect(), npc_beaten_corpse::OnGossipSelect(), npc_rivern_frostwind::OnGossipSelect(), npc_razael_and_lyana::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_roxi_ramrocket::OnGossipSelect(), npc_drake_dealer_hurlunk::OnGossipSelect(), npc_shattrathflaskvendors::OnGossipSelect(), npc_ishanah::OnGossipSelect(), npc_floon::OnGossipSelect(), npc_slim::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_elder_kuruti::OnGossipSelect(), npc_mortog_steamhead::OnGossipSelect(), npc_timothy_daniels::OnGossipSelect(), npc_innkeeper::OnGossipSelect(), npc_fairbanks::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_mcmanus::OnGossipSelect(), npc_finklestein::OnGossipSelect(), npc_captain_saeed::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), npc_simone::OnGossipSelect(), npc_franklin::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), go_fel_crystalforge::OnGossipSelect(), go_bashir_crystalforge::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), Player::OnGossipSelect(), lfg::LFGPlayerScript::OnLogin(), lfg::LFGPlayerScript::OnLogout(), lfg::LFGPlayerScript::OnMapChanged(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), BattlefieldWG::OnPlayerEnterZone(), Guild::OnPlayerStatusChange(), npc_kernobee::OnQuestAccept(), npc_koltira_deathweaver::OnQuestAccept(), pyrewood_ambush::OnQuestAccept(), npc_daphne_stilwell::OnQuestAccept(), npc_mikhail::OnQuestAccept(), npc_prospector_remtravel::OnQuestAccept(), npc_gilthares::OnQuestAccept(), npc_lakota_windsong::OnQuestAccept(), npc_paoka_swiftmountain::OnQuestAccept(), npc_engineer_helice::OnQuestAccept(), npc_maghar_captive::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_maxx_a_million_escort::OnQuestAccept(), npc_earthmender_wilda::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_ranger_lilatha::OnQuestAccept(), npc_deathstalker_erland::OnQuestAccept(), npc_tyrion::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_shenthul::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_wizzlecrank_shredder::OnQuestAccept(), npc_ame::OnQuestAccept(), npc_ranshalla::OnQuestAccept(), npc_lurgglbr::OnQuestAccept(), npc_mootoo_the_younger::OnQuestAccept(), npc_bonker_togglevolt::OnQuestAccept(), npc_emily::OnQuestAccept(), npc_apothecary_hanes::OnQuestAccept(), npc_battle_at_valhalas::OnQuestAccept(), npc_finklestein::OnQuestAccept(), npc_bessy::OnQuestAccept(), npc_isla_starmane::OnQuestAccept(), npc_kayra_longmane::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), npc_lady_sylvanas_windrunner::OnQuestReward(), at_q24545_frostmourne_cavern::OnTrigger(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnUnitDeath(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnUnitDeath(), instance_mechanar::instance_mechanar_InstanceMapScript::OnUnitDeath(), CreatureTextLocalizer< Builder >::operator()(), Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::operator()(), Acore::MostHPMissingGroupInRange::operator()(), BloodboltHitCheck::operator()(), SpectralBlastCheck::operator()(), Acore::ObjectGUIDCheck::operator()(), Acore::EmoteChatBuilder::operator()(), boss_kologarn::boss_kologarnAI::PassengerBoarded(), npc_frosthound::npc_frosthoundAI::PassengerBoarded(), npc_icefang::npc_icefangAI::PassengerBoarded(), Channel::Password(), npc_doctor::npc_doctorAI::PatientSaved(), spell_love_in_air_periodic_perfumes::spell_love_in_air_periodic_perfumes_AuraScript::PeriodicTick(), InstanceMap::PermBindAllPlayers(), Unit::PetSpellFail(), Player::PetSpellInitialize(), Battlefield::PlayerAcceptInviteToQueue(), Battlefield::PlayerAcceptInviteToWar(), MapMgr::PlayerCannotEnter(), InstanceSaveMgr::PlayerGetDestinationInstanceId(), Player::PossessSpellInitialize(), Spell::prepare(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), Player::PrepareGossipMenu(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessAction(), Battleground::ReadyMarkerClicked(), npc_pet_gen_mojo::ReceiveEmote(), PetAI::ReceiveEmote(), Player::RefundItem(), Map::RemoveAllObjectsInRemoveList(), Vehicle::RemoveAllPassengers(), BanMgr::RemoveBanCharacter(), Player::RemovedInsignia(), Item::RemoveFromUpdateQueueOf(), Unit::RemoveGameObject(), Vehicle::RemovePassenger(), BattlegroundEY::RemovePlayer(), BattlegroundWS::RemovePlayer(), Battleground::RemovePlayerAtLeave(), Battleground::RemovePlayerFromResurrectQueue(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::RemoveTargetAura(), BattlefieldWG::RemoveUpdateTenacity(), Player::ReportedAfkBy(), AchievementMgr::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), boss_archimonde::boss_archimondeAI::Reset(), Vehicle::Reset(), Player::ResetInstances(), Group::ResetInstances(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), Player::ResetPetTalents(), Pet::resetTalentsForAllPetsOf(), hyjalAI::Retreat(), Player::RewardHonor(), Player::RewardPlayerAndGroupAtEvent(), Player::RewardQuest(), npc_finklestein::npc_finklesteinAI::RightClickCauldron(), ReputationMgr::SaveToDB(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), Map::ScriptCommandStart(), Map::ScriptsProcess(), Map::ScriptsStart(), FactorySelector::selectAI(), FactorySelector::SelectGameObjectAI(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), PetAI::SelectNextTarget(), ThreatContainer::selectNextVictim(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), AchievementMgr::SendAchievementEarned(), npc_sayge::SendAction(), npc_prof_alchemy::SendActionMenu(), npc_prof_blacksmith::SendActionMenu(), npc_prof_leather::SendActionMenu(), npc_prof_tailor::SendActionMenu(), AuctionHouseMgr::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionWonMail(), Player::SendBuyError(), Spell::SendChannelStart(), CreatureTextMgr::SendChat(), Player::SendClearCooldown(), npc_prof_alchemy::SendConfirmLearn(), npc_prof_blacksmith::SendConfirmLearn(), npc_prof_tailor::SendConfirmLearn(), go_evil_book_for_dummies::SendConfirmLearn(), npc_prof_alchemy::SendConfirmUnlearn(), npc_prof_blacksmith::SendConfirmUnlearn(), npc_prof_tailor::SendConfirmUnlearn(), go_evil_book_for_dummies::SendConfirmUnlearn(), Player::SendEquipError(), SendGossipMenuFor(), Map::SendInitSelf(), WorldSession::SendLearnNewTaxiNode(), WorldSession::SendLfgBootProposalUpdate(), WorldSession::SendLfgUpdateProposal(), Guild::SendLoginInfo(), Player::SendLogXPGain(), Player::SendLoot(), Spell::SendLoot(), Group::SendLooter(), MailDraft::SendMailTo(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), Guild::SendMoneyInfo(), Guild::SendPermissions(), Player::SendPreparedGossip(), Player::SendPushToPartyResponse(), Player::SendQuestGiverStatusMultiple(), lfg::LFGMgr::SendRaidBrowserJoinedPacket(), Player::SendRefundInfo(), Spell::SendResurrectRequest(), MailDraft::SendReturnToSender(), Player::SendSellError(), Spell::SendSpellCooldown(), Unit::SendSpellDamageImmune(), Unit::SendSpellDamageResist(), Unit::SendSpellMiss(), Spell::SendSpellStart(), WorldSession::SendStablePet(), WorldSession::SendStablePetCallback(), WorldSession::SendTaxiMenu(), BfCapturePoint::SetCapturePointData(), Unit::SetCharm(), Unit::SetCharmedBy(), SpellCastTargets::SetCorpseTarget(), AchievementMgr::SetCriteriaProgress(), Movement::MoveSplineInit::SetFacing(), SmartAI::SetFollow(), SpellCastTargets::SetGOTarget(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::SetGUID(), Guild::BankTab::SetItem(), TradeData::SetItem(), SpellCastTargets::SetItemTarget(), GameObject::SetLinkedTrap(), Creature::SetLootRecipient(), Unit::SetMinion(), Channel::SetMode(), Player::SetMover(), Channel::SetOwner(), WorldSession::SetPlayer(), CreatureTextMgr::SetRepeatId(), SmartAI::SetScript9(), SmartGameObjectAI::SetScript9(), TradeData::SetSpell(), BfGraveyard::SetSpirit(), SpellCastTargets::SetUnitTarget(), Player::SetViewpoint(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipHello(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipHello(), npc_thassarian2::npc_thassarian2AI::sGossipSelect(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipSelect(), npc_hidden_cultist::npc_hidden_cultistAI::sGossipSelect(), npc_maredis_firestar::npc_maredis_firestarAI::sGossipSelect(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), boss_zuljin::boss_zuljinAI::SpawnAdds(), boss_janalai::boss_janalaiAI::SpawnBombs(), hyjalAI::SpawnVeins(), Spell::Spell(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusTaken(), npc_ulduar_flames_spread::npc_ulduar_flames_spreadAI::SpellHit(), npc_death_knight_initiate::npc_death_knight_initiateAI::SpellHit(), npc_draenei_survivor::npc_draenei_survivorAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::SpellHit(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_garments_of_quests::npc_garments_of_questsAI::SpellHit(), npc_shay_leafrunner::npc_shay_leafrunnerAI::SpellHit(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::SpellHit(), boss_garfrost::boss_garfrostAI::SpellHitTarget(), boss_lord_marrowgar::SpellHitTarget(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::SpellHitTarget(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_headless_horseman::boss_headless_horsemanAI::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), npc_pet_gen_fetch_ball::SpellHitTarget(), boss_rotface::boss_rotfaceAI::SpellHitTarget(), Unit::SpellPctDamageModsDone(), Unit::SpellTakenCritChance(), Player::SplitItem(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::sQuestAccept(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_muglash::npc_muglashAI::sQuestAccept(), npc_magwin::npc_magwinAI::sQuestAccept(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::sQuestAccept(), hyjalAI::StartEvent(), npc_clintar_spirit::npc_clintar_spiritAI::StartEvent(), FollowerAI::StartFollow(), npc_stillpine_capitive::npc_stillpine_capitiveAI::StartMoving(), NPCStaveQuestAI::StoreAttackerGuidValue(), Bag::StoreItem(), Player::StoreNewItem(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner(), SummonList::Summon(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::SummonChannelers(), hyjalAI::SummonCreature(), Map::SummonCreature(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SummonedCreatureDespawn(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDespawn(), boss_ichoron::boss_ichoronAI::SummonedCreatureDespawn(), boss_xevozz::boss_xevozzAI::SummonedCreatureDespawn(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), npc_vh_void_sentry::npc_vh_void_sentryAI::SummonedCreatureDespawn(), npc_medivh_bm::npc_medivh_bmAI::SummonedCreatureDespawn(), boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDies(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_vexallus::boss_vexallusAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::SummonedMobDied(), npc_air_force_bots::npc_air_force_botsAI::SummonGuard(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::SummonNextWave(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), boss_dorothee::boss_dorotheeAI::SummonTito(), Player::SwapItem(), Map::SwitchGridContainers(), Spell::TakeCastItem(), Channel::ToggleModeration(), Pet::TryLoadFromDB(), Channel::UnBan(), Vehicle::Uninstall(), NPCStaveQuestAI::UnitIsUnfair(), spell_illidari_council_deadly_strike::spell_illidari_council_deadly_strike_AuraScript::Update(), OPvPCapturePoint::Update(), SpellCastTargets::Update(), TotemAI::UpdateAI(), SimpleCharmedAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), npc_dark_nucleus::npc_dark_nucleusAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_doctor::npc_doctorAI::UpdateAI(), PetAI::UpdateAI(), PetAI::UpdateAllies(), Spell::UpdateChanneledTargetList(), Player::UpdateCharmedAI(), Group::UpdateLooterGuid(), Guild::UpdateMemberData(), Battleground::UpdatePlayerScore(), BattlegroundAB::UpdatePlayerScore(), BattlegroundAV::UpdatePlayerScore(), BattlegroundEY::UpdatePlayerScore(), BattlegroundIC::UpdatePlayerScore(), BattlegroundSA::UpdatePlayerScore(), BattlegroundWS::UpdatePlayerScore(), Spell::UpdatePointers(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), SpellCastTargets::UpdateTradeSlotItem(), Player::UpdateVisibilityOf(), UpdateVisibilityOf_helper(), GameObject::Use(), SpellInfo::ValidateAttribute6SpellDamageMods(), Player::VehicleSpellInitialize(), WorldObjectChangeAccumulator::Visit(), Acore::VisibleNotifier::Visit(), Acore::PlayerRelocationNotifier::Visit(), Player::VisualizeItem(), and SpellEvent::~SpellEvent().
GetGuidValue()
ObjectGuid Object::GetGuidValue (uint16 index) const
Definition at line 332 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, false));
     return *((ObjectGuid*) &(m_uint32Values[index]));
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by boss_malygos::boss_malygosAI::AttackStart(), AuraEffect::AuraEffect(), Player::BuildEnchantmentsInfoData(), Player::CanAlwaysSee(), Player::CheckDuelDistance(), Player::DuelComplete(), Spell::EffectJumpDest(), DynamicObject::GetCasterGUID(), Unit::GetCharmerGUID(), Unit::GetCharmGUID(), Unit::GetCreatorGUID(), Unit::GetCritterGUID(), GetGUID(), Unit::GetMinionGUID(), Corpse::GetOwnerGUID(), GameObject::GetOwnerGUID(), Item::GetOwnerGUID(), Unit::GetOwnerGUID(), Player::GetSelectedPlayer(), Player::GetSelectedUnit(), Unit::GetTarget(), Player::GetViewpoint(), WorldSession::HandleFarSightOpcode(), WorldSession::HandleWrapItemOpcode(), PetAI::KilledUnit(), Item::SaveToDB(), and Player::TeleportTo().
GetInt32Value()
int32 Object::GetInt32Value (uint16 index) const
Definition at line 294 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     return m_int32Values[index];
 }
References ASSERT, index, m_int32Values, m_valuesCount, and PrintIndexError().
Referenced by ApplyModInt32Value(), SpellInfo::CalcPowerCost(), Item::GetItemRandomPropertyId(), Item::GetSpellCharges(), Unit::GetTotalAttackPowerValue(), AuraEffect::HandleAuraModFakeInebriation(), spell_warl_life_tap::HandleDummy(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), and Item::SetItemRandomProperties().
GetObjectScale()
float Object::GetObjectScale () const inline
Definition at line 104 of file Object.h.
 { return GetFloatValue(OBJECT_FIELD_SCALE_X); }
References GetFloatValue(), and OBJECT_FIELD_SCALE_X.
Referenced by Unit::GetCollisionHeight(), Unit::GetCollisionWidth(), WorldObject::GetObjectSize(), GameObjectModelOwnerImpl::GetScale(), AuraEffect::HandleAuraModScale(), GameObject::IsAtInteractDistance(), GameObject::IsInRange(), and Creature::SetDisplayId().
GetPackGUID()
PackedGuid const& Object::GetPackGUID () const inline
Definition at line 100 of file Object.h.
 { return m_PackGUID; }
References m_PackGUID.
Referenced by Unit::_ExitVehicle(), AchievementMgr::BuildAllDataPacket(), BuildCreateUpdateBlockForPlayer(), Unit::BuildHeartBeatMsg(), Unit::BuildMovementPacket(), BuildMovementUpdate(), BuildMovementUpdateBlock(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::BuildPlayerRepop(), BuildValuesUpdateBlockForPlayer(), AuraApplication::ClientUpdate(), Spell::Delayed(), Unit::Dismount(), Spell::EffectDispel(), Spell::EffectStealBeneficialBuff(), Spell::ExecuteLogEffectDurabilityDamage(), Spell::ExecuteLogEffectExtraAttacks(), Spell::ExecuteLogEffectInterruptCast(), Spell::ExecuteLogEffectOpenLock(), Spell::ExecuteLogEffectResurrect(), Spell::ExecuteLogEffectSummonObject(), Spell::ExecuteLogEffectTakeTargetPower(), Spell::ExecuteLogEffectUnsummonObject(), Player::GetAurasForTarget(), AuraEffect::HandleAuraSetVehicle(), debug_commandscript::HandleDebugSendOpcodeCommand(), gm_commandscript::HandleGMFlyCommand(), WorldSession::HandleGrantLevel(), WorldSession::HandleInspectOpcode(), WorldSession::HandleLoadPetFromDBFirstCallback(), WorldSession::HandleLogoutCancelOpcode(), WorldSession::HandleLogoutRequestOpcode(), WorldSession::HandlePlayerLoginOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleTeleportTimeout(), Unit::JumpTo(), npc_gunship::npc_gunshipAI::JustDied(), Unit::KnockbackFrom(), Movement::MoveSplineInit::Launch(), GameObject::ModifyHealth(), Unit::Mount(), AchievementMgr::SendAchievementEarned(), Unit::SendAttackStateUpdate(), WorldSession::SendAttackStop(), Player::SendAutoRepeatCancel(), Unit::SendChangeCurrentVictimOpcode(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Unit::SendClearTarget(), Unit::SendClearThreatListOpcode(), spell_igb_overheat::spell_igb_overheat_AuraScript::SendClientControl(), Player::SendComboPoints(), AchievementMgr::SendCriteriaUpdate(), InstanceScript::SendEncounterUnit(), Unit::SendEnergizeSpellLog(), Unit::SendHealSpellLog(), Player::SendInitialPacketsAfterAddToMap(), Spell::SendInterrupted(), Spell::SendLogExecute(), Group::SendLooter(), Unit::SendMeleeAttackStop(), Unit::SendMonsterMove(), Unit::SendMovementFeatherFall(), Unit::SendMovementHover(), Unit::SendMovementWaterWalking(), Unit::SendPeriodicAuraLog(), Unit::SendRemoveFromThreatListOpcode(), AchievementMgr::SendRespondInspectAchievements(), Spell::SendSpellGo(), Unit::SendSpellNonMeleeReflectLog(), Spell::SendSpellStart(), Player::SendTeleportAckPacket(), Unit::SendTeleportPacket(), Unit::SendThreatListUpdate(), Player::SetCanFly(), Creature::SetCanFly(), Player::SetClientControl(), npc_eye_of_acherus::npc_eye_of_acherusAI::SetControl(), Player::SetDisableGravity(), Creature::SetDisableGravity(), Player::SetFeatherFall(), Creature::SetFeatherFall(), Creature::SetHover(), Player::SetHover(), Player::SetMovement(), Unit::SetPower(), Unit::SetRooted(), Unit::SetSpeed(), Creature::SetSwim(), Creature::SetWalk(), Player::SetWaterWalking(), Creature::SetWaterWalking(), Movement::MoveSplineInit::Stop(), boss_svala::boss_svalaAI::UpdateAI(), and SpellCastTargets::Write().
GetTypeId()
TypeID Object::GetTypeId () const inline
Definition at line 107 of file Object.h.
 { return m_objectTypeId; }
References m_objectTypeId.
Referenced by ThreatMgr::_addThreat(), Aura::_ApplyForTarget(), Spell::_cast(), Unit::_CreateAuraApplication(), Unit::_EnterVehicle(), Unit::_ExitVehicle(), Map::_GetScriptCreatureSourceOrTarget(), Map::_GetScriptPlayerSourceOrTarget(), Map::_GetScriptUnit(), Spell::_handle_finish_phase(), KillRewarder::_InitXP(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), KillRewarder::_RewardPlayer(), Aura::_UnapplyForTarget(), Unit::_UpdateAutoRepeatSpell(), Unit::AddGameObject(), Map::AddObjectToSwitchList(), Vehicle::AddPassenger(), Unit::AddPetAura(), Player::AddQuest(), Player::AddQuestAndCheckCompletion(), Acore::AnyAoETargetUnitInObjectRangeCheck::AnyAoETargetUnitInObjectRangeCheck(), Unit::ApplyDiminishingToDuration(), Unit::ApplyResilience(), AuraEffect::ApplySpellMod(), npc_escortAI::AssistPlayerInCombat(), Unit::Attack(), Unit::AttackerStateUpdate(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::AttackStart(), TotemAI::AttackStart(), npc_living_mojo::npc_living_mojoAI::AttackStart(), Aura::BuildEffectMaskForOwner(), BuildMovementUpdate(), Unit::CalcAbsorbResist(), Unit::CalcArmorReducedDamage(), Unit::CalculateAOEDamageReduction(), Unit::CalculateLevelPenalty(), boss_hodir::boss_hodirAI::CanAIAttack(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::CanAIAttack(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::CanAIAttack(), npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack(), npc_argent_captainAI::CanAIAttack(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::CanAIAttack(), Creature::CanAssistTo(), Spell::cancel(), Spell::CancelGlobalCooldown(), Creature::CanCreatureAttack(), WorldObject::CanDetect(), WorldObject::CanDetectStealthOf(), Unit::CanHaveThreatList(), Player::CanInteractWithQuestGiver(), WorldObject::CanNeverSee(), Spell::CanOpenLock(), WorldObject::CanSeeOrDetect(), Creature::CanStartAttack(), Pet::CastPetAuras(), CharmInfo::CharmInfo(), Player::CharmSpellInitialize(), spell_igb_rocket_pack_useable::spell_igb_rocket_pack_useable_AuraScript::CheckAreaTarget(), spell_gen_area_aura_select_players::CheckAreaTarget(), spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::CheckAreaTarget(), spell_dk_death_grip::CheckCast(), spell_hun_disengage::CheckCast(), spell_hun_tame_beast::CheckCast(), spell_pal_righteous_defense::CheckCast(), Spell::CheckCast(), Spell::CheckEffectTarget(), Spell::CheckItems(), Spell::CheckPower(), spell_dk_dancing_rune_weapon::CheckProc(), spell_item_lil_phylactery::CheckProc(), spell_item_unsated_craving::CheckProc(), Spell::CheckRange(), Spell::CheckRuneCost(), SpellInfo::CheckTarget(), SpellInfo::CheckTargetCreatureType(), Unit::ClearAllReactives(), Unit::CombatStart(), Unit::CombatStartOnCast(), Unit::CombatStop(), Aura::Create(), PathGenerator::CreateFilter(), Unit::CreateTamedPetFrom(), CreatureUnitRelocationWorker(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DamageDealt(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DamageDealt(), boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt(), npc_ball_of_flame::npc_ball_of_flameAI::DamageDealt(), hyjal_trashAI::DamageTaken(), npc_infested_root_walker::npc_infested_root_walkerAI::DamageTaken(), npc_rotting_forest_rager::npc_rotting_forest_ragerAI::DamageTaken(), npc_calvin_montague::npc_calvin_montagueAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), npc_heated_battle::npc_heated_battleAI::DamageTaken(), boss_razuvious::boss_razuviousAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), Unit::DealDamage(), Unit::DealDamageMods(), Unit::DealHeal(), Unit::DealMeleeDamage(), Unit::DealSpellDamage(), Spell::DelayedChannel(), MotionTransport::DelayedTeleportTransport(), spell_rotface_unstable_ooze_explosion_suicide::spell_rotface_unstable_ooze_explosion_suicide_AuraScript::DespawnSelf(), Unit::DisableRotate(), Unit::Dismount(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), PetAI::DoAttack(), Spell::DoSpellHitOnUnit(), FollowMovementGenerator< T >::DoUpdate(), CreatureAI::DoZoneInCombat(), Spell::EffectActivateObject(), Spell::EffectActivateRune(), Spell::EffectAddFarsight(), Spell::EffectAddHonor(), Spell::EffectApplyGlyph(), Spell::EffectBlock(), Spell::EffectCastButtons(), Spell::EffectCharge(), Spell::EffectChargeDest(), Spell::EffectCreateTamedPet(), Spell::EffectDistract(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectEnergizePct(), Spell::EffectInstaKill(), Spell::EffectJump(), Spell::EffectJumpDest(), Spell::EffectKnockBack(), Spell::EffectLeapBack(), Spell::EffectLearnSkill(), Spell::EffectLearnSpell(), Spell::EffectMilling(), Spell::EffectOpenLock(), Spell::EffectParry(), Spell::EffectPickPocket(), Spell::EffectProficiency(), Spell::EffectProspecting(), Spell::EffectPullTowards(), Spell::EffectRechargeManaGem(), Spell::EffectRenamePet(), Spell::EffectResurrectNew(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSelfResurrect(), Spell::EffectSkinning(), Spell::EffectSkinPlayerCorpse(), Spell::EffectStuck(), Spell::EffectSummonChangeItem(), Spell::EffectSummonPet(), Spell::EffectSummonRaFFriend(), Spell::EffectTameCreature(), Spell::EffectTeleportUnits(), Spell::EffectTitanGrip(), Spell::EffectTradeSkill(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), Spell::EffectUntrainTalents(), Spell::EffectWeaponDmg(), npc_gilthares::npc_giltharesAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), npc_phase_hunter::npc_phase_hunterAI::EnterCombat(), npc_earthmender_wilda::npc_earthmender_wildaAI::EnterCombat(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::FilterTargets(), RotateMovementGenerator::Finalize(), DistractMovementGenerator::Finalize(), EffectMovementGenerator::Finalize(), Spell::finish(), boss_shade_of_aran::boss_aranAI::FlameWreathEffect(), Unit::GetAllMinionsByEntry(), Unit::GetAPMultiplier(), Unit::GetCastingTimeForBonus(), Unit::GetCollisionWidth(), WorldObject::GetContactPoint(), Unit::GetCreatePowers(), Unit::GetCreatureType(), Player::GetDefaultGossipMenuForSource(), Unit::GetDefenseSkillValue(), Unit::GetFactionTemplateEntry(), WorldObject::GetGridActivationRange(), Unit::GetModelForForm(), Unit::GetNextRandomRaidMemberOrPet(), ObjectAccessor::GetObjectByTypeMask(), Unit::GetPartyMembers(), Player::GetQuestDialogStatus(), Unit::getRace(), WorldObject::GetSightRange(), Aura::GetType(), Unit::GetUnitCriticalChance(), Unit::GetUnitDodgeChance(), Unit::GetUnitParryChance(), GetUpdateFieldData(), WorldObject::GetVisibilityRange(), Player::GiveXP(), go_soulwell::go_soulwellAI::GossipHello(), spell_dru_berserk::HandleAfterCast(), spell_infected_worgen_bite::spell_infected_worgen_bite_AuraScript::HandleAfterEffectApply(), Pet::HandleAsynchLoadFailed(), AuraEffect::HandleAuraAllowFlight(), AuraEffect::HandleAuraAllowOnlyAbility(), AuraEffect::HandleAuraControlVehicle(), AuraEffect::HandleAuraConvertRune(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraFeatherFall(), AuraEffect::HandleAuraGhost(), AuraEffect::HandleAuraModAttackPowerOfArmor(), AuraEffect::HandleAuraModBaseResistancePCT(), AuraEffect::HandleAuraModBlockPercent(), AuraEffect::HandleAuraModCritPct(), AuraEffect::HandleAuraModDisarm(), AuraEffect::HandleAuraModDodgePercent(), AuraEffect::HandleAuraModExpertise(), AuraEffect::HandleAuraModFaction(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleAuraModIncreaseFlightSpeed(), AuraEffect::HandleAuraModParryPercent(), AuraEffect::HandleAuraModPetTalentsPoints(), AuraEffect::HandleAuraModRangedAttackPowerOfStatPercent(), AuraEffect::HandleAuraModResistance(), AuraEffect::HandleAuraModResistanceExclusive(), AuraEffect::HandleAuraModResistenceOfStatPercent(), AuraEffect::HandleAuraModShapeshift(), AuraEffect::HandleAuraModSkill(), AuraEffect::HandleAuraModStalked(), AuraEffect::HandleAuraModStat(), AuraEffect::HandleAuraModTotalThreat(), AuraEffect::HandleAuraModWeaponCritPercent(), AuraEffect::HandleAuraOpenStable(), Unit::HandleAuraRaidProcFromChargeWithValue(), AuraEffect::HandleAuraRetainComboPoints(), AuraEffect::HandleAuraSetVehicle(), Aura::HandleAuraSpecificMods(), AuraEffect::HandleAuraTrackCreatures(), AuraEffect::HandleAuraTrackResources(), AuraEffect::HandleAuraTrackStealthed(), AuraEffect::HandleAuraTransform(), AuraEffect::HandleBindSight(), WorldSession::HandleCancelChanneling(), WorldSession::HandleCastSpellOpcode(), AuraEffect::HandleChannelDeathItem(), misc_commandscript::HandleCreatePetCommand(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugUpdateCommand(), AuraEffect::HandleDetectAmore(), misc_commandscript::HandleDieCommand(), WorldSession::HandleDismissCritter(), spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::HandleDummy(), Unit::HandleDummyAuraProc(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_AuraScript::HandleDummyTick(), spell_dk_master_of_ghouls::HandleEffectApply(), spell_gen_creature_permanent_feign_death::HandleEffectApply(), spell_yogg_saron_sanity_well::spell_yogg_saron_sanity_well_AuraScript::HandleEffectPeriodic(), spell_rog_prey_on_the_weak::HandleEffectPeriodic(), spell_dk_master_of_ghouls::HandleEffectRemove(), spell_gen_creature_permanent_feign_death::HandleEffectRemove(), AuraEffect::HandleFarSight(), AuraEffect::HandleFeignDeath(), spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::HandleFinish(), AuraEffect::HandleForceReaction(), OutdoorPvP::HandleKill(), BattlefieldWG::HandleKill(), OutdoorPvPHP::HandleKillImpl(), OutdoorPvPNA::HandleKillImpl(), OutdoorPvPZM::HandleKillImpl(), WorldSession::HandleLoadPetFromDBSecondCallback(), WorldSession::HandleMirrorImageDataRequest(), AuraEffect::HandleModBaseResistance(), AuraEffect::HandleModDamageDone(), AuraEffect::HandleModDamagePercentDone(), AuraEffect::HandleModHealingDone(), AuraEffect::HandleModHitChance(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyPhaseCommand(), modify_commandscript::HandleModifyTalentCommand(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModManaRegen(), AuraEffect::HandleModPercentStat(), AuraEffect::HandleModPossess(), AuraEffect::HandleModPossessPet(), AuraEffect::HandleModPowerRegen(), AuraEffect::HandleModRating(), AuraEffect::HandleModRatingFromStat(), AuraEffect::HandleModResistancePercent(), AuraEffect::HandleModSpellCritChance(), AuraEffect::HandleModSpellCritChanceShool(), AuraEffect::HandleModSpellDamagePercentFromAttackPower(), AuraEffect::HandleModSpellDamagePercentFromStat(), AuraEffect::HandleModSpellHealingPercentFromAttackPower(), AuraEffect::HandleModSpellHealingPercentFromStat(), AuraEffect::HandleModSpellHitChance(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), AuraEffect::HandleModStealthLevel(), AuraEffect::HandleModTargetResistance(), AuraEffect::HandleModTotalPercentStat(), modify_commandscript::HandleMorphResetCommand(), modify_commandscript::HandleMorphTargetCommand(), misc_commandscript::HandleMovegensCommand(), WorldSession::HandleMovementOpcodes(), AuraEffect::HandleNoReagentUseAura(), npc_commandscript::HandleNpcSetEntryCommand(), Unit::HandleOverrideClassScriptAuraProc(), spell_voa_overcharge::spell_voa_overcharge_AuraScript::HandlePeriodicDummy(), AuraEffect::HandlePeriodicDummyAuraTick(), AuraEffect::HandlePeriodicEnergizeAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetRename(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), AuraEffect::HandlePreventFleeing(), AuraEffect::HandlePreventResurrection(), Unit::HandleProcTriggerSpell(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverStatusQueryOpcode(), AuraEffect::HandleRangedAmmoHaste(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleRespawnCommand(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_the_flag_of_ownership::HandleScript(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::HandleScriptEffect(), AuraEffect::HandleShieldBlockValue(), Unit::HandleSpellClick(), AuraEffect::HandleSpiritOfRedemption(), WorldSession::HandleTextEmoteOpcode(), spell_warl_drain_soul::HandleTick(), AuraEffect::HandleWaterBreathing(), Spell::HasGlobalCooldown(), CharmInfo::InitCharmCreateSpells(), MotionMaster::InitDefault(), Spell::InitExplicitTargets(), CharmInfo::InitPossessCreateSpells(), TempSummon::InitStats(), Guardian::InitStatsForLevel(), TempSummon::InitSummon(), Pet::InitTalentForLevel(), Unit::InitTamedPet(), Vehicle::Install(), Vehicle::InstallAccessory(), Unit::InterruptSpell(), SmartScript::IsCreature(), DisableMgr::IsDisabledFor(), SmartScript::IsGameObject(), Player::isHonorOrXPTarget(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Unit::IsPetAura(), IsPlayer(), SmartScript::IsPlayer(), Aura::IsProcTriggeredOnEvent(), Unit::isSpellBlocked(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), npc_venomhide_hatchling::npc_venomhide_hatchlingAI::IsSummonedBy(), Unit::isTargetableForAttack(), Unit::IsTriggeredAtSpellProcEvent(), SmartScript::IsUnit(), ThreatCalcHelper::isValidProcess(), WorldObject::IsWithinLOS(), WorldObject::IsWithinLOSInMap(), Unit::JumpTo(), npc_nerubar_victim::npc_nerubar_victimAI::JustDied(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::JustDied(), Unit::Kill(), boss_sartharion::boss_sartharionAI::KilledUnit(), boss_sathrovarr::boss_sathrovarrAI::KilledUnit(), boss_ragnaros::boss_ragnarosAI::KilledUnit(), boss_priestess_delrissa::boss_priestess_delrissaAI::KilledUnit(), boss_selin_fireheart::boss_selin_fireheartAI::KilledUnit(), boss_vexallus::boss_vexallusAI::KilledUnit(), boss_brutallus::boss_brutallusAI::KilledUnit(), boss_sacrolash::boss_sacrolashAI::KilledUnit(), boss_alythess::boss_alythessAI::KilledUnit(), boss_felmyst::boss_felmystAI::KilledUnit(), boss_kalecgos::boss_kalecgosAI::KilledUnit(), boss_kiljaeden::boss_kiljaedenAI::KilledUnit(), boss_twilight_corrupter::boss_twilight_corrupterAI::KilledUnit(), boss_halazzi::boss_halazziAI::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_archimonde::boss_archimondeAI::KilledUnit(), boss_epoch_hunter::boss_epoch_hunterAI::KilledUnit(), boss_lieutenant_drake::boss_lieutenant_drakeAI::KilledUnit(), boss_aeonus::boss_aeonusAI::KilledUnit(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::KilledUnit(), boss_temporus::boss_temporusAI::KilledUnit(), boss_buru::boss_buruAI::KilledUnit(), npc_tiger_matriarch::npc_tiger_matriarchAI::KilledUnit(), boss_elder_nadox::boss_elder_nadoxAI::KilledUnit(), boss_volazj::boss_volazjAI::KilledUnit(), boss_taldaram::boss_taldaramAI::KilledUnit(), boss_halion::boss_halionAI::KilledUnit(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), boss_black_knight::boss_black_knightAI::KilledUnit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::KilledUnit(), boss_prince_keleseth_icc::boss_prince_kelesethAI::KilledUnit(), boss_prince_taldaram_icc::boss_prince_taldaramAI::KilledUnit(), boss_prince_valanar_icc::boss_prince_valanarAI::KilledUnit(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::KilledUnit(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::KilledUnit(), boss_festergut::boss_festergutAI::KilledUnit(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::KilledUnit(), boss_lord_marrowgar::KilledUnit(), boss_professor_putricide::boss_professor_putricideAI::KilledUnit(), boss_rotface::boss_rotfaceAI::KilledUnit(), boss_sindragosa::boss_sindragosaAI::KilledUnit(), boss_the_lich_king::boss_the_lich_kingAI::KilledUnit(), boss_sister_svalna::boss_sister_svalnaAI::KilledUnit(), npc_argent_captainAI::KilledUnit(), boss_anubrekhan::boss_anubrekhanAI::KilledUnit(), boss_bjarngrim::boss_bjarngrimAI::KilledUnit(), boss_ionar::boss_ionarAI::KilledUnit(), boss_loken::boss_lokenAI::KilledUnit(), boss_volkhan::boss_volkhanAI::KilledUnit(), boss_algalon_the_observer::boss_algalon_the_observerAI::KilledUnit(), boss_freya::boss_freyaAI::KilledUnit(), boss_xt002::boss_xt002AI::KilledUnit(), boss_palehoof::boss_palehoofAI::KilledUnit(), boss_svala::boss_svalaAI::KilledUnit(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::KilledUnit(), boss_pandemonius::boss_pandemoniusAI::KilledUnit(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::KilledUnit(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::KilledUnit(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::KilledUnit(), boss_najentus::boss_najentusAI::KilledUnit(), boss_doomlord_kazzak::boss_doomlordkazzakAI::KilledUnit(), boss_hydromancer_thespia::boss_thespiaAI::KilledUnit(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::KilledUnit(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::KilledUnit(), boss_the_maker::boss_the_makerAI::KilledUnit(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::KilledUnit(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::KilledUnit(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::KilledUnit(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::KilledUnit(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::KilledUnit(), boss_commander_sarannis::boss_commander_sarannisAI::KilledUnit(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::KilledUnit(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::KilledUnit(), boss_warp_splinter::boss_warp_splinterAI::KilledUnit(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::KilledUnit(), boss_kaelthas::boss_kaelthasAI::KilledUnit(), boss_void_reaver::boss_void_reaverAI::KilledUnit(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::KilledUnit(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::KilledUnit(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::KilledUnit(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::KilledUnit(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::KilledUnit(), boss_akilzon::boss_akilzonAI::KilledUnit(), boss_anetheron::boss_anetheronAI::KilledUnit(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::KilledUnit(), boss_eadric::boss_eadricAI::KilledUnit(), boss_paletress::boss_paletressAI::KilledUnit(), boss_anubarak_trial::boss_anubarak_trialAI::KilledUnit(), boss_twin_valkyrAI::KilledUnit(), boss_bronjahm::boss_bronjahmAI::KilledUnit(), boss_falric::boss_falricAI::KilledUnit(), boss_marwyn::boss_marwynAI::KilledUnit(), boss_garfrost::boss_garfrostAI::KilledUnit(), boss_ick::boss_ickAI::KilledUnit(), boss_tyrannus::boss_tyrannusAI::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_four_horsemen::boss_four_horsemenAI::KilledUnit(), boss_gluth::boss_gluthAI::KilledUnit(), boss_gothik::boss_gothikAI::KilledUnit(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit(), boss_grobbulus::boss_grobbulusAI::KilledUnit(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::KilledUnit(), boss_heigan::boss_heiganAI::KilledUnit(), boss_kelthuzad::boss_kelthuzadAI::KilledUnit(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::KilledUnit(), boss_loatheb::boss_loathebAI::KilledUnit(), boss_maexxna::boss_maexxnaAI::KilledUnit(), boss_noth::boss_nothAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_razuvious::boss_razuviousAI::KilledUnit(), boss_razuvious_minion::boss_razuvious_minionAI::KilledUnit(), boss_sapphiron::boss_sapphironAI::KilledUnit(), boss_thaddius::boss_thaddiusAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), boss_steelbreaker::boss_steelbreakerAI::KilledUnit(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::KilledUnit(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::KilledUnit(), boss_flame_leviathan::boss_flame_leviathanAI::KilledUnit(), boss_vezax::boss_vezaxAI::KilledUnit(), boss_hodir::boss_hodirAI::KilledUnit(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::KilledUnit(), npc_ulduar_vx001::npc_ulduar_vx001AI::KilledUnit(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::KilledUnit(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::KilledUnit(), npc_q24545_vegard::npc_q24545_vegardAI::KilledUnit(), emerald_dragonAI::KilledUnit(), boss_emeriss::boss_emerissAI::KilledUnit(), KillRewarder::KillRewarder(), spell_hate_to_zero::spell_hate_to_zero_SpellScript::Load(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::Load(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::Load(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::Load(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::Load(), spell_volazj_whisper::spell_volazj_whisper_SpellScript::Load(), spell_jedoga_sacrafice_beam::spell_jedoga_sacrafice_beam_AuraScript::Load(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Load(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::Load(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::Load(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::Load(), spell_igb_cannon_blast::spell_igb_cannon_blast_SpellScript::Load(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Load(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::Load(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::Load(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::Load(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::Load(), spell_illidan_demon_transform1::spell_illidan_demon_transform1_AuraScript::Load(), spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript::Load(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::Load(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Load(), spell_kaelthas_flame_strike::spell_kaelthas_flame_strike_AuraScript::Load(), spell_dk_blood_boil::Load(), spell_dk_icebound_fortitude::Load(), spell_dk_raise_dead::Load(), spell_dru_rip::Load(), spell_dru_swift_flight_passive::Load(), spell_dru_t10_restoration_4p_bonus::Load(), spell_gen_pet_summoned::Load(), spell_pvp_trinket_wotf_shared_cd::Load(), spell_gen_divine_storm_cd_reset::Load(), spell_gen_profession_research::Load(), spell_gen_seaforium_blast::Load(), spell_gen_vehicle_scaling_aura::Load(), spell_gen_oracle_wolvar_reputation::Load(), spell_gen_spirit_healer_res::Load(), spell_gen_on_tournament_mount::Load(), spell_gen_tournament_pennant::Load(), spell_gen_despawn_self::Load(), spell_hun_aspect_of_the_beast::Load(), spell_hun_readiness::Load(), spell_hun_scatter_shot::Load(), spell_item_feast::Load(), spell_item_deviate_fish::Load(), spell_item_make_a_wish::Load(), spell_item_noggenfogger_elixir::Load(), spell_item_savory_deviate_delight::Load(), spell_item_scroll_of_recall::Load(), spell_item_underbelly_elixir::Load(), spell_item_book_of_glyph_mastery::Load(), spell_item_ashbringer::Load(), spell_item_purify_helboar_meat::Load(), spell_item_demon_broiled_surprise::Load(), spell_item_teach_language::Load(), spell_item_rocket_boots::Load(), spell_item_chicken_cover::Load(), spell_mage_cold_snap::Load(), spell_pal_ardent_defender::Load(), spell_pri_penance::Load(), spell_pri_renew::Load(), spell_q5206_test_fetid_skull::Load(), spell_q6124_6129_apply_salve::Load(), spell_q11730_ultrasonic_screwdriver::Load(), spell_q12937_relief_for_the_fallen::Load(), spell_q12659_ahunaes_knife::Load(), spell_q9874_liquid_fire::Load(), spell_q12805_lifeblood_dummy::Load(), spell_q9452_cast_net::Load(), spell_q13011_bear_flank_master::Load(), spell_q12690_burst_at_the_seams::Load(), spell_rog_deadly_poison::Load(), spell_rog_preparation::Load(), spell_rog_rupture::Load(), spell_rog_shiv::Load(), spell_warl_improved_demonic_tactics::Load(), spell_warl_life_tap::Load(), spell_warl_curse_of_doom::Load(), Unit::MagicSpellHitResult(), MailSender::MailSender(), Condition::Meets(), AchievementCriteriaData::Meets(), Unit::MeleeDamageBonusDone(), Unit::MeleeSpellHitResult(), Unit::MeleeSpellMissChance(), CreatureAI::MoveBackwardsChecks(), MotionMaster::MoveCharge(), MotionMaster::MoveChase(), CreatureAI::MoveCircleChecks(), MotionMaster::MoveConfused(), MotionMaster::MoveFall(), MotionMaster::MoveFleeing(), MotionMaster::MoveFollow(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight(), boss_twilight_corrupter::boss_twilight_corrupterAI::MoveInLineOfSight(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_brewfest_keg_thrower::npc_brewfest_keg_throwerAI::MoveInLineOfSight(), npc_brewfest_keg_reciver::npc_brewfest_keg_reciverAI::MoveInLineOfSight(), npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI::MoveInLineOfSight(), npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::MoveInLineOfSight(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::MoveInLineOfSight(), npc_doomfire_targetting::npc_doomfire_targettingAI::MoveInLineOfSight(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::MoveInLineOfSight(), boss_aeonus::boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::MoveInLineOfSight(), boss_temporus::boss_temporusAI::MoveInLineOfSight(), npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight(), boss_onyxia::boss_onyxiaAI::MoveInLineOfSight(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::MoveInLineOfSight(), npc_onyxia_whelp::npc_onyxia_whelpAI::MoveInLineOfSight(), npc_depth_charge::npc_depth_chargeAI::MoveInLineOfSight(), npc_draenei_survivor::npc_draenei_survivorAI::MoveInLineOfSight(), npc_twiggy_flathead::npc_twiggy_flatheadAI::MoveInLineOfSight(), boss_anub_arak::boss_anub_arakAI::MoveInLineOfSight(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), boss_lord_marrowgar::MoveInLineOfSight(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::MoveInLineOfSight(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_anubrekhan::boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlina::boss_faerlinaAI::MoveInLineOfSight(), boss_kelthuzad::boss_kelthuzadAI::MoveInLineOfSight(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_brann_radio::npc_brann_radioAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_guardian_pavilion::npc_guardian_pavilionAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), boss_exarch_maladaar::boss_exarch_maladaarAI::MoveInLineOfSight(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_talon_king_ikiss::boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), boss_doomwalker::boss_doomwalkerAI::MoveInLineOfSight(), boss_lady_vashj::boss_lady_vashjAI::MoveInLineOfSight(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::MoveInLineOfSight(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::MoveInLineOfSight(), boss_kaelthas::boss_kaelthasAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), MotionMaster::MoveJumpTo(), MotionMaster::MoveKnockbackFrom(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::MovementInform(), MotionMaster::MovePath(), MotionMaster::MovePoint(), MotionMaster::MoveRandom(), MotionMaster::MoveSeekAssistance(), MotionMaster::MoveSeekAssistanceDistract(), MotionMaster::MoveSplinePath(), MotionMaster::MoveTargetedHome(), MotionMaster::MoveTaxiFlight(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget(), npc_pet_mage_mirror_image::MySelectNextTarget(), Unit::NearTeleportTo(), npc_ancestral_wolf::npc_ancestral_wolfAI::npc_ancestral_wolfAI(), ScriptMgr::OnAddPassenger(), spell_gen_aura_service_uniform::spell_gen_aura_service_uniform_AuraScript::OnApply(), spell_pilgrims_bounty_serve_generic::spell_pilgrims_bounty_serve_generic_AuraScript::OnAuraRemove(), achievement_flu_shot_shortage::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_ignis_shattered::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), Player::OnGossipSelect(), SmartScript::OnInitialize(), ScriptMgr::OnInstall(), ScriptMgr::OnInstallAccessory(), spell_gen_aura_service_uniform::spell_gen_aura_service_uniform_AuraScript::OnRemove(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnReset(), ScriptMgr::OnUninstall(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnUnitDeath(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnUnitDeath(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::OnUnitDeath(), instance_mechanar::instance_mechanar_InstanceMapScript::OnUnitDeath(), item_gor_dreks_ointment::OnUse(), SplineHandler::operator()(), Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::operator()(), Acore::AnyAoETargetUnitInObjectRangeCheck::operator()(), Acore::NearestHostileUnitCheck::operator()(), Acore::MostHPMissingGroupInRange::operator()(), NecroticPlagueTargetCheck::operator()(), DefaultTargetSelector::operator()(), NonTankTargetSelector::operator()(), PowerUsersSelector::operator()(), FarthestTargetSelector::operator()(), BoneStormMoveTargetSelector::operator()(), MalleableGooSelector::operator()(), LastPhaseIceTombTargetSelector::operator()(), ShadowTrapLKTargetSelector::operator()(), NonTankLKTargetSelector::operator()(), DefileTargetSelector::operator()(), HammerOfJusticeSelector::operator()(), DoorsGuidCheck::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), StoneGripTargetSelector::operator()(), IgbArtilleryCheck::operator()(), VehicleCheck::operator()(), HasInLineCheck::operator()(), PlayerOrPetCheck::operator()(), Acore::ObjectTypeIdCheck::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::PassengerBoarded(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::PassengerBoarded(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), npc_frosthound::npc_frosthoundAI::PassengerBoarded(), npc_icefang::npc_icefangAI::PassengerBoarded(), Unit::PetSpellFail(), FollowMovementGenerator< T >::PositionOkay(), Spell::prepare(), spell_dtk_raise_dead::spell_dtk_raise_dead_AuraScript::PrepareAuraScript(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::PrepareAuraScript(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::PrepareAuraScript(), Spell::prepareDataForTriggerSystem(), Player::PrepareGossipMenu(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), spell_sha_lava_lash::PrepareSpellScript(), PrintIndexError(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessEvent(), Unit::ProcessTerrainStatusUpdate(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), npc_pet_gen_mojo::ReceiveEmote(), Unit::RemoveAllControlled(), Unit::RemoveAllMinionsByEntry(), Map::RemoveAllObjectsInRemoveList(), Unit::RemoveCharmedBy(), Unit::RemoveGameObject(), Vehicle::RemovePassenger(), Unit::RemovePetAura(), Vehicle::Reset(), Pet::resetTalents(), Unit::RestoreFaction(), Player::RewardHonor(), Player::RewardPlayerAndGroupAtEvent(), Player::RewardReputation(), Unit::RollMeleeOutcomeAgainst(), Map::ScriptCommandStart(), Map::ScriptsProcess(), Map::ScriptsStart(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitCasterObjectTargets(), Unit::SendAttackStateUpdate(), Spell::SendCastResult(), Spell::SendChannelStart(), CreatureTextMgr::SendChatPacket(), Unit::SendMeleeAttackStop(), CreatureTextMgr::SendNonChatPacket(), Unit::SendPeriodicAuraLog(), Unit::SendPetActionFeedback(), Unit::SendPetAIReaction(), Unit::SendPetTalk(), WorldObject::SendPlayMusic(), Player::SendPreparedGossip(), Spell::SendResurrectRequest(), Spell::SendSpellCooldown(), Spell::SendSpellGo(), Unit::SendSpellNonMeleeReflectLog(), Spell::SendSpellStart(), Unit::SendTeleportPacket(), WorldObject::setActive(), Unit::SetCharm(), Unit::SetCharmedBy(), Player::SetClientControl(), Unit::SetConfused(), Unit::SetControlled(), Unit::SetFaction(), Unit::SetFeared(), Unit::SetHealth(), Unit::SetHover(), Unit::SetInCombatState(), Unit::SetInCombatWith(), Unit::SetLevel(), WorldObject::SetMap(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetMinion(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), Unit::SetPhaseMask(), WorldObject::SetPositionDataUpdate(), Unit::SetPower(), Unit::setPowerType(), Unit::setRace(), Unit::SetRooted(), Unit::SetSpeed(), Unit::SetStandState(), Unit::SetStunned(), Player::SetViewpoint(), WorldObject::SetVisibilityDistanceOverride(), Spell::Spell(), Unit::SpellBaseDamageBonusDone(), Unit::SpellBaseHealingBonusDone(), Unit::SpellDamageBonusDone(), Unit::SpellDoneCritChance(), Unit::SpellHealingBonusDone(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SpellHit(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::SpellHit(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::SpellHit(), Unit::SpellHitResult(), boss_onyxia::boss_onyxiaAI::SpellHitTarget(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHitTarget(), boss_ick::boss_ickAI::SpellHitTarget(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_vezax::boss_vezaxAI::SpellHitTarget(), npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI::SpellHitTarget(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), boss_thorim::boss_thorimAI::SpellHitTarget(), boss_sindragosa::boss_sindragosaAI::SpellHitTarget(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), Unit::SpellPctDamageModsDone(), Unit::SpellPctHealingModsDone(), Unit::SpellTakenCritChance(), SmartAI::StartPath(), Unit::StopAttackFaction(), Player::StopCastingCharm(), NPCStaveQuestAI::StoreAttackerGuidValue(), WorldObject::SummonCreatureGroup(), WorldObject::SummonGameObject(), Spell::SummonGuardian(), WorldObject::SummonTrigger(), Pet::SynchronizeLevelWithOwner(), Spell::TakeAmmo(), Spell::TakeCastItem(), Spell::TakePower(), Spell::TakeReagents(), Spell::TakeRunePower(), Unit::TauntApply(), Unit::TauntFadeOut(), ToCorpse(), ToCreature(), ToDynObject(), ToGameObject(), ToPlayer(), ToUnit(), CreatureAI::TriggerAlert(), Spell::TriggerGlobalCooldown(), TempSummon::UnSummon(), Spell::update(), GameObject::Update(), Unit::Update(), SpellCastTargets::Update(), AchievementMgr::UpdateAchievementCriteria(), boss_azuregos::boss_azuregosAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), PetAI::UpdateAI(), PetAI::UpdateAllies(), Unit::UpdateAuraForGroup(), Unit::UpdateCharmAI(), Player::UpdateCharmedAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::UpdateEscortAI(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), AuraEffect::UpdatePeriodic(), Spell::UpdatePointers(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), Unit::UpdatePosition(), Unit::UpdateReactives(), Unit::UpdateSpeed(), Unit::UpdateSplineMovement(), Unit::UpdateSplinePosition(), Player::UpdateVisibilityOf(), Player::UpdateWeaponSkill(), GameObject::Use(), Spell::WriteAmmoToPacket(), Map::~Map(), SpellEvent::~SpellEvent(), Vehicle::~Vehicle(), and WorldObject::~WorldObject().
GetUInt16Value()
uint16 Object::GetUInt16Value (uint16 index, uint8 offset) const
Definition at line 325 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     ASSERT(offset < 2);
     return *(((uint16*) &m_uint32Values[index]) + offset);
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Player::_SaveCharacter().
GetUInt32Value()
uint32 Object::GetUInt32Value (uint16 index) const
Definition at line 300 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     return m_uint32Values[index];
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Player::_ApplyAmmoBonuses(), _ConcatFields(), Player::_SaveCharacter(), Player::_SaveDailyQuestStatus(), Player::_SaveSkills(), Player::_SaveStats(), Player::AddItemDurations(), Player::AddItemToBuyBackSlot(), ApplyModUInt32Value(), Unit::BuildAuraStateUpdateForTarget(), Player::CanNoReagentCast(), Player::CanUseBattlegroundObject(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckCasterAuras(), Spell::CheckItems(), Item::CheckSoulboundTradeExpire(), SpellInfo::CheckTarget(), Item::CloneItem(), Map::ConvertCorpseToBones(), Player::CreateCorpse(), boss_grand_champion::boss_grand_championAI::DamageTaken(), spell_hun_masters_call::DoCheckCast(), Player::DurabilityLoss(), Player::DurabilityPointsLoss(), Player::DurabilityRepair(), Spell::EffectDestroyAllTotems(), Spell::EffectDummy(), Spell::EffectGameObjectDamage(), Spell::EffectSummonChangeItem(), Spell::finish(), Player::GetArenaPersonalRating(), Player::GetArenaPoints(), Player::GetArenaTeamId(), Bag::GetBagSize(), Player::GetBaseSkillValue(), Unit::GetCollisionHeight(), Unit::GetCollisionWidth(), Item::GetCount(), Unit::GetCreateHealth(), Unit::GetCreateMana(), Unit::GetDisplayId(), GameObject::GetDisplayId(), Item::GetEnchantmentCharges(), Item::GetEnchantmentDuration(), Item::GetEnchantmentId(), GetEntry(), Player::GetExpertiseDodgeOrParryReduction(), Unit::GetFaction(), Player::GetFreePrimaryProfessionPoints(), Player::GetFreeTalentPoints(), Player::GetGlyphSlot(), Player::GetGuildId(), Unit::GetHealth(), Player::GetHonorPoints(), Item::GetItemSuffixFactor(), Unit::getLevel(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Player::GetMaxSkillValue(), Player::GetMoney(), Unit::GetMountID(), Unit::GetNativeDisplayId(), StaticTransport::GetPauseTime(), MotionTransport::GetPeriod(), Item::GetPlayedTime(), Unit::GetPower(), Player::GetPureMaxSkillValue(), Player::GetPureSkillValue(), Player::GetQuestSlotQuestId(), Player::GetQuestSlotState(), Player::GetQuestSlotTime(), Player::GetRank(), Player::GetRatingBonusValue(), Unit::GetResistance(), Player::GetSkillPermBonusValue(), Player::GetSkillStep(), Player::GetSkillTempBonusValue(), Player::GetSkillValue(), DynamicObject::GetSpellId(), Unit::GetStat(), Pet::GivePetXP(), Player::GiveXP(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleBuybackItem(), character_commandscript::HandleCharacterTitlesCommand(), debug_commandscript::HandleDebugGetItemValueCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugUpdateCommand(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_gen_model_visible::HandleEffectApply(), WorldSession::HandleGetMailList(), WorldSession::HandleGossipHelloOpcode(), misc_commandscript::HandleHideAreaCommand(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleLoadPetFromDBSecondCallback(), lookup_commandscript::HandleLookupTitleCommand(), modify_commandscript::HandleModifyFactionCommand(), npc_commandscript::HandleNpcInfoCommand(), AuraEffect::HandlePeriodicDummyAuraTick(), WorldSession::HandleSelfResOpcode(), WorldSession::HandleSendMail(), misc_commandscript::HandleShowAreaCommand(), WorldSession::HandleWrapItemOpcode(), npc_pet_mage_mirror_image::InitializeAI(), Totem::InitStats(), Item::IsBroken(), Spell::IsChannelActive(), Player::IsDailyQuestDone(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsFriendly(), boss_terestian_illhoof::boss_terestianAI::JustSummoned(), Unit::Kill(), Player::LoadFromDB(), Item::LoadFromDB(), Player::ModifySkillBonus(), WorldSession::moveItems(), npc_hidden_cultist::npc_hidden_cultistAI::npc_hidden_cultistAI(), spell_gen_clone_weapon_aura::OnApply(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), boss_yoggsaron_descend_portal::OnGossipHello(), Player::OnGossipSelect(), Player::PrepareGossipMenu(), Player::RemovePet(), Player::RewardHonor(), Player::SatisfyQuestDay(), Pet::SavePetToDB(), Corpse::SaveToDB(), Item::SaveToDB(), Creature::SaveToDB(), WorldSession::SendPetNameQuery(), Item::SendTimeUpdate(), Player::SetAmmo(), Player::SetDailyQuestStatus(), Player::setDeathState(), Unit::SetMinion(), Player::SetRestBonus(), Player::SetSkill(), Player::SetTitle(), netherspite_infernal::netherspite_infernalAI::SpellHit(), SmartAI::StartPath(), Player::SwapQuestSlot(), Spell::TakeAmmo(), Totem::UnSummon(), Player::UnsummonPetTemporaryIfAny(), Creature::Update(), Player::Update(), AchievementMgr::UpdateAchievementCriteria(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), Item::UpdateDuration(), Player::UpdateHonorFields(), Item::UpdatePlayedTime(), lfg::LFGMgr::UpdateRaidBrowser(), Player::UpdateSkill(), Player::UpdateSkillPro(), Player::UpdateSkillsForLevel(), Player::UpdateSkillsToMaxSkillsForLevel(), and Spell::WriteAmmoToPacket().
GetUInt64Value()
uint64 Object::GetUInt64Value (uint16 index) const
Definition at line 306 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, false));
     return *((uint64*) &(m_uint32Values[index]));
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Player::_SaveCharacter(), Player::GetQuestSlotCounter(), ArenaSpectator::HandleSpectatorWatchCommand(), HasFlag64(), RemoveFlag64(), SetFlag64(), and Player::SetQuestSlotCounter().
GetUpdateFieldData()
uint32 Object::GetUpdateFieldData (Player const * target, uint32 *& flags) const protected
Definition at line 558 of file Object.cpp.
 {
     uint32 visibleFlag = UF_FLAG_PUBLIC;
     if (target == this)
         visibleFlag |= UF_FLAG_PRIVATE;
     switch (GetTypeId())
     {
         case TYPEID_ITEM:
         case TYPEID_CONTAINER:
             flags = ItemUpdateFieldFlags;
             if (((Item*)this)->GetOwnerGUID() == target->GetGUID())
                 visibleFlag |= UF_FLAG_OWNER | UF_FLAG_ITEM_OWNER;
             break;
         case TYPEID_UNIT:
         case TYPEID_PLAYER:
             {
                 Player* plr = ToUnit()->GetCharmerOrOwnerPlayerOrPlayerItself();
                 flags = UnitUpdateFieldFlags;
                 if (ToUnit()->GetOwnerGUID() == target->GetGUID())
                     visibleFlag |= UF_FLAG_OWNER;
                 if (HasFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_SPECIALINFO))
                     if (ToUnit()->HasAuraTypeWithCaster(SPELL_AURA_EMPATHY, target->GetGUID()))
                         visibleFlag |= UF_FLAG_SPECIAL_INFO;
                 if (plr && plr->IsInSameRaidWith(target))
                     visibleFlag |= UF_FLAG_PARTY_MEMBER;
                 break;
             }
         case TYPEID_GAMEOBJECT:
             flags = GameObjectUpdateFieldFlags;
             if (ToGameObject()->GetOwnerGUID() == target->GetGUID())
                 visibleFlag |= UF_FLAG_OWNER;
             break;
         case TYPEID_DYNAMICOBJECT:
             flags = DynamicObjectUpdateFieldFlags;
             if (((DynamicObject*)this)->GetCasterGUID() == target->GetGUID())
                 visibleFlag |= UF_FLAG_OWNER;
             break;
         case TYPEID_CORPSE:
             flags = CorpseUpdateFieldFlags;
             if (ToCorpse()->GetOwnerGUID() == target->GetGUID())
                 visibleFlag |= UF_FLAG_OWNER;
             break;
         case TYPEID_OBJECT:
             break;
     }
     return visibleFlag;
 }
References CorpseUpdateFieldFlags, DynamicObjectUpdateFieldFlags, GameObjectUpdateFieldFlags, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), GetGUID(), GetTypeId(), HasFlag(), Player::IsInSameRaidWith(), ItemUpdateFieldFlags, SPELL_AURA_EMPATHY, ToCorpse(), ToGameObject(), ToUnit(), TYPEID_CONTAINER, TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_ITEM, TYPEID_OBJECT, TYPEID_PLAYER, TYPEID_UNIT, UF_FLAG_ITEM_OWNER, UF_FLAG_OWNER, UF_FLAG_PARTY_MEMBER, UF_FLAG_PRIVATE, UF_FLAG_PUBLIC, UF_FLAG_SPECIAL_INFO, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_SPECIALINFO, and UnitUpdateFieldFlags.
Referenced by BuildValuesUpdate().
GetValuesCount()
uint16 Object::GetValuesCount () const inline
Definition at line 167 of file Object.h.
 { return m_valuesCount; }
References m_valuesCount.
Referenced by debug_commandscript::HandleDebugGetItemValueCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugSetItemValueCommand(), debug_commandscript::HandleDebugSetValueCommand(), and modify_commandscript::HandleModifyBitCommand().
HasByteFlag()
bool Object::HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
Definition at line 940 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     ASSERT(offset < 4);
     return (((uint8*) &m_uint32Values[index])[offset] & flag) != 0;
 }
References ASSERT, index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Unit::_IsValidAttackTarget(), Player::GiveLevel(), WorldSession::HandlePetRename(), Unit::IsFFAPvP(), Unit::IsInSanctuary(), Unit::IsPvP(), and Pet::SavePetToDB().
HasFlag()
bool Object::HasFlag (uint16 index, uint32 flag) const
Definition at line 880 of file Object.cpp.
 {
     if (index >= m_valuesCount && !PrintIndexError(index, false))
     {
         return false;
     }
     return (m_uint32Values[index] & flag) != 0;
 }
References index, m_uint32Values, m_valuesCount, and PrintIndexError().
Referenced by Creature::_CanDetectFeignDeathOf(), Creature::_IsTargetAcceptable(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Player::_LoadItem(), Player::_SaveCharacter(), Player::ActivateTaxiPathTo(), Vehicle::AddPassenger(), Battleground::AddPlayer(), Creature::AllLootRemovedFromCorpse(), Player::ApplyEquipCooldown(), Unit::AttackerStateUpdate(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::AttackStart(), boss_sister_svalna::boss_sister_svalnaAI::AttackStart(), boss_malygos::boss_malygosAI::AttackStart(), SmartAI::AttackStart(), boss_dorothee::boss_dorotheeAI::AttackStart(), npc_halazzi_lynx::npc_halazzi_lynxAI::AttackStart(), npc_ghostly_priest::npc_ghostly_priestAI::AttackStart(), npc_phantom_mage::npc_phantom_mageAI::AttackStart(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::AttackStart(), npc_spectral_footman::npc_spectral_footmanAI::AttackStart(), npc_tortured_rifleman::npc_tortured_riflemanAI::AttackStart(), violet_hold_trashAI::AttackStart(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::AttackStart(), npc_ravenous_worg::npc_ravenous_worgAI::AttackStart(), WorldSession::BuildPartyMemberStatsChangedPacket(), Unit::BuildValuesUpdate(), npc_swarm_scarab::npc_swarm_scarabAI::CanAIAttack(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::CanAIAttack(), Creature::CanAssistTo(), PetAI::CanAttack(), Item::CanBeTraded(), Player::CanNoReagentCast(), Creature::CanStartAttack(), Unit::CanSwim(), Unit::CanUseAttackType(), Spell::CheckCast(), Spell::CheckEffectTarget(), Unit::ClearInCombat(), Player::CreateCorpse(), boss_muru::boss_muruAI::DamageTaken(), boss_black_knight::boss_black_knightAI::DamageTaken(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_bronjahm::boss_bronjahmAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), boss_malygos::boss_malygosAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken(), npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::DamageTaken(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken(), boss_essence_of_desire::boss_essence_of_desireAI::DamageTaken(), Player::DestroyItem(), npc_fos_leader::npc_fos_leaderAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_jormungarAI::DoAction(), Spell::DoSpellHitOnUnit(), RandomMovementGenerator< T >::DoUpdate(), Spell::EffectStuck(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), violet_hold_trashAI::EnterCombat(), SmartAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), GameObject::GetDestructibleState(), Unit::GetFactionReactionTo(), Player::GetNPCIfCanInteractWith(), Unit::GetReactionTo(), GetUpdateFieldData(), GetVelocity(), Player::GiveXP(), Player::HandleDrowning(), spell_gen_model_visible::HandleEffectApply(), WorldSession::HandleLogoutRequestOpcode(), WorldSession::HandleMirrorImageDataRequest(), modify_commandscript::HandleModifyBitCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleReclaimCorpseOpcode(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), Unit::HasAuraState(), Player::HasTitle(), Player::isAFK(), Unit::IsArmorer(), Unit::IsAuctioner(), Unit::IsBanker(), Unit::IsBattleMaster(), Item::IsBindedNotWith(), Player::IsDeveloper(), Player::isDND(), Unit::IsGossip(), Unit::IsGuildMaster(), Unit::IsInCombat(), Unit::IsInnkeeper(), Item::IsLocked(), Unit::IsMounted(), Unit::IsPetInCombat(), Unit::IsQuestGiver(), Unit::IsServiceProvider(), Item::IsSoulBound(), Unit::IsSpiritGuide(), Unit::IsSpiritHealer(), Unit::IsSpiritService(), Unit::IsTabardDesigner(), Unit::isTargetableForAttack(), Unit::IsTaxi(), Unit::IsTrainer(), Unit::IsVendor(), boss_novos::boss_novosAI::JustSummoned(), Player::LoadFromDB(), Item::LoadFromDB(), Condition::Meets(), Unit::ModifyAuraState(), MotionMaster::MoveCharge(), MotionMaster::MoveChase(), MotionMaster::MoveConfused(), MotionMaster::MoveDistract(), MotionMaster::MoveFall(), MotionMaster::MoveFleeing(), MotionMaster::MoveFollow(), boss_dorothee::boss_dorotheeAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), boss_professor_putricide::boss_professor_putricideAI::MoveInLineOfSight(), boss_palehoof::boss_palehoofAI::MoveInLineOfSight(), npc_massive_jormungar::npc_massive_jormungarAI::MoveInLineOfSight(), npc_ferocious_rhino::npc_ferocious_rhinoAI::MoveInLineOfSight(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::MoveInLineOfSight(), npc_frenzied_worgen::npc_frenzied_worgenAI::MoveInLineOfSight(), npc_nether_drake::npc_nether_drakeAI::MoveInLineOfSight(), Player::MoveItemToInventory(), MotionMaster::MoveLand(), MotionMaster::MovePath(), MotionMaster::MovePoint(), MotionMaster::MoveRandom(), MotionMaster::MoveSeekAssistance(), MotionMaster::MoveSeekAssistanceDistract(), MotionMaster::MoveSplinePath(), MotionMaster::MoveTakeoff(), MotionMaster::MoveTargetedHome(), npc_toc_druid::npc_toc_druidAI::myCanCast(), npc_toc_shaman::npc_toc_shamanAI::myCanCast(), npc_toc_paladin::npc_toc_paladinAI::myCanCast(), npc_toc_priest::npc_toc_priestAI::myCanCast(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::myCanCast(), npc_toc_warlock::npc_toc_warlockAI::myCanCast(), npc_toc_mage::npc_toc_mageAI::myCanCast(), npc_toc_hunter::npc_toc_hunterAI::myCanCast(), npc_toc_boomkin::npc_toc_boomkinAI::myCanCast(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::myCanCast(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_fos_leader::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_experience::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::operator()(), spell_gen_mounted_charge::PrepareSpellScript(), SmartScript::ProcessAction(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), npc_plucky::npc_pluckyAI::ReceiveEmote(), Creature::RefreshSwimmingFlag(), Player::RefundItem(), Creature::Regenerate(), npc_calvin_montague::npc_calvin_montagueAI::Reset(), npc_plucky::npc_pluckyAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), Item::SaveToDB(), FactorySelector::selectAI(), ScriptedAI::SelectSpell(), Player::SendLoot(), Player::SendPreparedGossip(), Player::SendQuestGiverStatusMultiple(), Player::SendRefundInfo(), Player::SetClientControl(), Unit::SetInCombatState(), Item::SetNotRefundable(), Unit::SetSpeed(), Player::SetTitle(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_escortAI::Start(), ToggleFlag(), Player::Update(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), npc_xt002_heart::npc_xt002_heartAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), npc_ravenous_worg::npc_ravenous_worgAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), Player::UpdateForQuestWorldObjects(), Player::UpdatePvPFlag(), Player::UpdatePvPState(), Player::UpdateTriggerVisibility(), and GameObject::Use().
HasFlag64()
bool Object::HasFlag64 (uint16 index, uint64 flag) const
Definition at line 973 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, false));
     return (GetUInt64Value(index) & flag) != 0;
 }
References ASSERT, GetUInt64Value(), index, m_valuesCount, and PrintIndexError().
Referenced by ToggleFlag64().
hasInvolvedQuest()
virtual bool Object::hasInvolvedQuest (uint32) const inline virtual
Reimplemented in Item, GameObject, and Creature.
Definition at line 170 of file Object.h.
 { return false; }
Referenced by WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestgiverRequestRewardOpcode(), and Player::SendPreparedQuest().
hasQuest()
virtual bool Object::hasQuest (uint32) const inline virtual
Reimplemented in Item, GameObject, and Creature.
Definition at line 169 of file Object.h.
 { return false; }
Referenced by WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverQueryQuestOpcode(), and Player::SendPreparedQuest().
IsInWorld()
bool Object::IsInWorld () const inline
Definition at line 93 of file Object.h.
 { return m_inWorld; }
References m_inWorld.
Referenced by Unit::_AddAura(), Player::_addSpell(), Spell::_handle_finish_phase(), Battleground::_ProcessResurrect(), Player::_SaveCharacter(), Player::_StoreItem(), Battlefield::AddOrSetPlayerToCorrectBfGroup(), Vehicle::AddPassenger(), Player::addSpell(), Map::AddToMap(), Corpse::AddToWorld(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), Pet::AddToWorld(), Unit::AddToWorld(), Unit::CalcAbsorbResist(), Aura::CanBeAppliedOn(), Unit::CleanupBeforeRemoveFromMap(), WorldObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), Aura::Create(), Map::DelayedUpdate(), WorldObject::DestroyForNearbyPlayers(), Player::DestroyItem(), Player::DestroyItemCount(), WorldSession::DoLootRelease(), UnitAI::DoMeleeAttackIfReady(), Spell::EffectAddFarsight(), Spell::EffectPersistentAA(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectSelfResurrect(), Player::EquipItem(), AuctionListItemsDelayEvent::Execute(), ConflagrateAuraStateDelayEvent::Execute(), AuraMunchingQueue::Execute(), Unit::ExecuteDelayedUnitAINotifyEvent(), Unit::ExecuteDelayedUnitRelocationEvent(), ObjectAccessor::FindPlayer(), World::FindPlayerInZone(), WorldObject::GetFloorZ(), Player::GetNextQuest(), Player::GetNPCIfCanInteractWith(), Player::GetPet(), AuraEffect::HandleAuraOpenStable(), AuraEffect::HandleAuraOverrideSpells(), AuraEffect::HandleAuraSetVehicle(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetAction(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginOpcode(), ArenaSpectator::HandleResetCommand(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSetActiveMoverOpcode(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSkirmishCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), WorldSession::HandleSpellClick(), SmartScript::IsCreature(), SmartScript::IsGameObject(), WorldObject::IsInMap(), WorldObject::IsNeverVisible(), Player::IsPetNeedBeTemporaryUnsummoned(), SmartScript::IsPlayer(), SmartScript::IsUnit(), IsValidCombatTarget(), WorldObject::IsWithinLOS(), Player::LearnCustomSpells(), Player::learnSkillRewardedSpells(), Player::learnSpell(), Player::LoadFromDB(), Player::LoadPet(), Pet::LoadPetFromDB(), Group::MasterLoot(), AchievementCriteriaData::Meets(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), boss_twin_valkyrAI::myDoMeleeAttackIfReady(), Spell::OnSpellLaunch(), Unit::OutDebugInfo(), Player::PrepareQuestMenu(), MapSessionFilter::Process(), WorldSessionFilter::Process(), Player::QuickEquipItem(), DynamicObject::Remove(), Corpse::RemoveFromWorld(), Creature::RemoveFromWorld(), TempSummon::RemoveFromWorld(), Minion::RemoveFromWorld(), Puppet::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), WorldObject::RemoveFromWorld(), Pet::RemoveFromWorld(), Player::RemoveFromWorld(), Unit::RemoveFromWorld(), Player::RemoveItem(), Vehicle::RemovePassenger(), Player::RemovePet(), Map::RemovePlayerFromMap(), WorldObject::ResetMap(), BfGraveyard::Resurrect(), AchievementMgr::SendAchievementEarned(), WorldObject::SendMessageToSet(), Map::SendObjectUpdates(), WorldObject::setActive(), Unit::SetCharm(), Unit::SetCharmedBy(), GameObject::SetGoState(), WorldObject::SetMap(), Player::SetMover(), WorldObject::SetPhaseMask(), Unit::SetPhaseMask(), Player::SetViewpoint(), WorldObject::SetWorldObject(), Spell::Spell(), Player::SplitItem(), Unit::StopMoving(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonGameObject(), Player::SwapItem(), Player::TeleportTo(), TempSummon::UnSummon(), Player::UnsummonPetTemporaryIfAny(), Map::Update(), StaticTransport::Update(), WorldSession::Update(), Creature::Update(), Puppet::Update(), Player::Update(), Unit::Update(), AchievementMgr::UpdateAchievementCriteria(), GameObject::UpdateModel(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), Group::UpdatePlayerOutOfRange(), Spell::UpdatePointers(), Player::UpdateTriggerVisibility(), and ~Object().
IsPlayer()
bool Object::IsPlayer () const inline
Definition at line 180 of file Object.h.
 { return GetTypeId() == TYPEID_PLAYER; }
References GetTypeId(), and TYPEID_PLAYER.
Referenced by Creature::AddToWorld(), Pet::AddToWorld(), Creature::CanCreatureAttack(), Unit::CanHaveThreatList(), Creature::CanSwim(), Unit::CombatStart(), Spell::EffectEnvironmentalDMG(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), spell_hun_volley_trigger::HandleFinish(), Creature::IsDungeonBoss(), Creature::IsImmuneToKnockback(), boss_majordomo::boss_majordomoAI::KilledUnit(), Creature::LoadSpellTemplateImmunity(), Unit::ProcDamageAndSpellFor(), NPCStaveQuestAI::QuestIncomplete(), Creature::Regenerate(), Unit::RemoveAllControlled(), Unit::RemoveEvadeAuras(), Pet::SavePetToDB(), NPCStaveQuestAI::UnitIsUnfair(), Unit::UnsummonAllTotems(), Creature::Update(), and Unit::Update().
isType()
bool Object::isType (uint16 mask) const inline
Definition at line 108 of file Object.h.
 { return (mask & m_objectType); }
References m_objectType.
Referenced by Map::_GetScriptUnit(), Map::_ScriptProcessDoor(), BuildCreateUpdateBlockForPlayer(), BuildMovementUpdate(), WorldObject::CanDetectStealthOf(), Aura::Create(), WorldObject::DestroyForNearbyPlayers(), DestroyForPlayer(), WorldObject::GetMapWaterOrGroundLevel(), GameObject::IsAlwaysVisibleFor(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::IsSummonedBy(), Player::RewardQuest(), Map::ScriptsProcess(), Player::SetViewpoint(), WorldObject::SummonCreature(), WorldObject::UpdateGroundPositionZ(), Player::UpdateVisibilityOf(), and ~Object().
operator=()
Object& Object::operator= (Object const &) private
PrintIndexError()
bool Object::PrintIndexError (uint32 index, bool set) const private
Definition at line 991 of file Object.cpp.
 {
     LOG_INFO("misc", "Attempt %s non-existed value field: %u (count: %u) for object typeid: %u type mask: %u",
         (set ? "set value to" : "get value from"), index, m_valuesCount, GetTypeId(), m_objectType);
     // ASSERT must fail after function call
     return false;
 }
References GetTypeId(), index, LOG_INFO, m_objectType, m_valuesCount, and set().
Referenced by AddGuidValue(), GetByteValue(), GetFloatValue(), GetGuidValue(), GetInt32Value(), GetUInt16Value(), GetUInt32Value(), GetUInt64Value(), HasByteFlag(), HasFlag(), HasFlag64(), RemoveByteFlag(), RemoveFlag(), RemoveGuidValue(), SetByteFlag(), SetByteValue(), SetFlag(), SetFloatValue(), SetGuidValue(), SetInt32Value(), SetUInt16Value(), SetUInt32Value(), SetUInt64Value(), and UpdateUInt32Value().
RemoveByteFlag()
void Object::RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
Definition at line 921 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (offset > 3)
     {
         LOG_ERROR("entities.object", "Object::RemoveByteFlag: wrong offset %u", offset);
         return;
     }
     if (uint8(m_uint32Values[index] >> (offset * 8)) & oldFlag)
     {
         m_uint32Values[index] &= ~uint32(uint32(oldFlag) << (offset * 8));
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, LOG_ERROR, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by WorldSession::HandleAreaTriggerOpcode(), AuraEffect::HandleAuraUntrackable(), AuraEffect::HandleDetectAmore(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModStealth(), WorldSession::HandlePetRename(), AuraEffect::HandlePreventResurrection(), Player::InitStatsForLevel(), Unit::RemoveStandFlags(), Player::SetGameMaster(), Player::SetIsSpectator(), Unit::SetPvP(), Player::UpdateArea(), Player::UpdateFFAPvPFlag(), and Player::UpdateFFAPvPState().
RemoveFieldNotifyFlag()
void Object::RemoveFieldNotifyFlag (uint16 flag) inline
Definition at line 175 of file Object.h.
 { _fieldNotifyFlags &= ~flag; }
References _fieldNotifyFlags.
Referenced by Group::AddMember(), Unit::SetOwnerGUID(), and Player::UpdateTriggerVisibility().
RemoveFlag()
void Object::RemoveFlag (uint16 index, uint32 oldFlag)
Definition at line 851 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     ASSERT(m_uint32Values);
     uint32 oldval = m_uint32Values[index];
     uint32 newval = oldval & ~oldFlag;
     if (oldval != newval)
     {
         m_uint32Values[index] = newval;
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Player::_LoadGroup(), Player::_LoadItem(), go_suppression_device::go_suppression_deviceAI::Activate(), spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript::ActivateSpirit(), Vehicle::AddPassenger(), ApplyModFlag(), boss_vaelastrasz::boss_vaelAI::BeginSpeech(), Player::BuildPlayerRepop(), GameObject::CastSpell(), Player::CleanupAfterTaxiFlight(), Unit::ClearInCombat(), Unit::ClearInPetCombat(), Item::ClearSoulboundTradeable(), BattlegroundIC::DestroyGate(), Unit::DisableRotate(), boss_thorim::boss_thorimAI::DisableThorim(), Unit::Dismount(), npc_fos_leader::npc_fos_leaderAI::DoAction(), npc_coren_direbrew::npc_coren_direbrewAI::DoAction(), npc_direbrew_antagonist::npc_direbrew_antagonistAI::DoAction(), npc_twilight_volunteer::npc_twilight_volunteerAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_living_constellation::npc_living_constellationAI::DoAction(), boss_broggok::boss_broggokAI::DoAction(), npc_madrigosa::npc_madrigosaAI::DoAction(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::DoAction(), boss_grand_champion::boss_grand_championAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), npc_massive_jormungar::npc_massive_jormungarAI::DoAction(), npc_ferocious_rhino::npc_ferocious_rhinoAI::DoAction(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::DoAction(), npc_frenzied_worgen::npc_frenzied_worgenAI::DoAction(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DoAction(), boss_essence_of_desire::boss_essence_of_desireAI::DoAction(), boss_essence_of_anger::boss_essence_of_angerAI::DoAction(), boss_the_lurker_below::boss_the_lurker_belowAI::DoAction(), npc_naga_distiller::npc_naga_distillerAI::DoAction(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), anchorite_karja::anchorite_karjaAI::DoAction(), exarch_orelis::exarch_orelisAI::DoAction(), boss_ichoron::boss_ichoronAI::DoExplodeCompleted(), HomeMovementGenerator< Creature >::DoFinalize(), FlightPathMovementGenerator::DoFinalize(), FleeingMovementGenerator< T >::DoFinalize(), ConfusedMovementGenerator< T >::DoFinalize(), WorldSession::DoLootRelease(), Spell::EffectResurrectPet(), Spell::EffectSkinning(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnableSara(), boss_falric::boss_falricAI::EnterCombat(), boss_marwyn::boss_marwynAI::EnterCombat(), boss_ymiron::boss_ymironAI::EnterCombat(), npc_precious::npc_preciousAI::EnterCombat(), npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), violet_hold_trashAI::EnterCombat(), boss_bronjahm::boss_bronjahmAI::EnterEvadeMode(), npc_ghostly_priest::npc_ghostly_priestAI::EnterEvadeMode(), npc_phantom_mage::npc_phantom_mageAI::EnterEvadeMode(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::EnterEvadeMode(), npc_spectral_footman::npc_spectral_footmanAI::EnterEvadeMode(), npc_tortured_rifleman::npc_tortured_riflemanAI::EnterEvadeMode(), boss_kelthuzad::boss_kelthuzadAI::EnterEvadeMode(), boss_malygos::boss_malygosAI::EnterEvadeMode(), boss_ymiron::boss_ymironAI::EnterEvadeMode(), violet_hold_trashAI::EnterEvadeMode(), npc_future_you::npc_future_youAI::EnterEvadeMode(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterEvadeMode(), UtherBatteredHiltEvent::Execute(), SACActivateEvent::Execute(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::FeignDeath(), TimedFleeingMovementGenerator::Finalize(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), AuraEffect::HandleArenaPreparation(), Pet::HandleAsynchLoadFailed(), Pet::HandleAsynchLoadSucceed(), AuraEffect::HandleAuraAllowOnlyAbility(), AuraEffect::HandleAuraCloneCaster(), AuraEffect::HandleAuraGhost(), AuraEffect::HandleAuraModDisarm(), AuraEffect::HandleAuraModFaction(), AuraEffect::HandleAuraModPacify(), AuraEffect::HandleAuraModSilence(), AuraEffect::HandleAuraModStalked(), AuraEffect::HandleAuraTrackCreatures(), AuraEffect::HandleAuraTrackResources(), AuraEffect::HandleComprehendLanguage(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectRemove(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectRemove(), spell_gen_model_visible::HandleEffectRemove(), spell_gen_creature_permanent_feign_death::HandleEffectRemove(), spell_q11396_11399_force_shield_arcane_purple_x3::HandleEffectRemove(), AuraEffect::HandleFeignDeath(), AuraEffect::HandleForceMoveForward(), WorldSession::HandleLogoutCancelOpcode(), modify_commandscript::HandleModifyBitCommand(), spell_oculus_drake_flag::spell_oculus_drake_flagAuraScript::HandleOnEffectApply(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectRemove(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleRemove(), WorldSession::HandleSetTaxiBenchmarkOpcode(), npc_cork_gizelton::npc_cork_gizeltonAI::ImmuneFlagSet(), boss_vaelastrasz::boss_vaelAI::Initialize(), Player::InitStatsForLevel(), PossessedAI::JustDied(), hyjal_trashAI::JustDied(), boss_kri::boss_kriAI::JustDied(), boss_vem::boss_vemAI::JustDied(), boss_yauj::boss_yaujAI::JustDied(), boss_volazj::boss_volazjAI::JustDied(), boss_ichoron::boss_ichoronAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_kaelthas::boss_kaelthasAI::JustDied(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), Player::LoadFromDB(), Unit::ModifyAuraState(), boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), boss_taldaram::boss_taldaramAI::MovementInform(), boss_grand_champion::boss_grand_championAI::MovementInform(), boss_sister_svalna::boss_sister_svalnaAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), boss_sartharion_dragonAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::npc_amanitar_mushroomsAI(), npc_fos_leader_second::npc_fos_leader_secondAI::npc_fos_leader_secondAI(), npc_giant_infernal::npc_giant_infernalAI::npc_giant_infernalAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), npc_announcer_toc10::OnGossipHello(), npc_experience::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_death_knight_initiate::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_arthas::OnGossipSelect(), adyen_the_lightbringer::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), npc_calvin_montague::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_battle_at_valhalas::OnQuestAccept(), npc_bessy::OnQuestAccept(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnRemove(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnRemove(), NPCStaveQuestAI::PrepareForEncounter(), Unit::RemoveCharmedBy(), Vehicle::RemovePassenger(), boss_keristrasza::boss_keristraszaAI::RemovePrison(), Player::RemoveQuestSlotState(), Player::RemoveRestFlag(), Player::RemoveRestState(), Unit::RemoveVehicleKit(), Player::RepopAtGraveyard(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_mr_smite::boss_mr_smiteAI::Reset(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::Reset(), npc_mograine::npc_mograineAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_muru::boss_muruAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::Reset(), npc_zealot_zath::npc_zealot_zathAI::Reset(), npc_arthas::npc_arthasAI::Reset(), boss_eye_of_cthun::eye_of_cthunAI::Reset(), npc_plucky::npc_pluckyAI::Reset(), boss_volazj::boss_volazjAI::Reset(), boss_anub_arak::boss_anub_arakAI::Reset(), boss_sartharion_dragonAI::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_grand_champion::boss_grand_championAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_bronjahm::boss_bronjahmAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_malygos::boss_malygosAI::Reset(), npc_crystalline_frayer::npc_crystalline_frayerAI::Reset(), boss_eregos::boss_eregosAI::Reset(), boss_urom::boss_uromAI::Reset(), boss_varos::boss_varosAI::Reset(), boss_loken::boss_lokenAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_algalon_the_observer::boss_algalon_the_observerAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), boss_mimiron::boss_mimironAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_svala::boss_svalaAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_ichoron::boss_ichoronAI::Reset(), npc_thassarian2::npc_thassarian2AI::Reset(), npc_venture_co_straggler::npc_venture_co_stragglerAI::Reset(), npc_lake_frog::npc_lake_frogAI::Reset(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::Reset(), npc_akama_shade::npc_akamaAI::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::Reset(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::Reset(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), npc_aeranas::npc_aeranasAI::Reset(), emerald_dragonAI::Reset(), npc_chicken_cluck::npc_chicken_cluckAI::Reset(), npc_doctor::npc_doctorAI::Reset(), npc_injured_patient::npc_injured_patientAI::Reset(), Player::ResetContestedPvP(), Resurrect(), hyjalAI::Retreat(), Unit::SetCharm(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SetData(), npc_ulduar_vx001::npc_ulduar_vx001AI::SetData(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SetData(), Unit::setDeathState(), Pet::setDeathState(), GameObject::SetDestructibleState(), Player::SetGameMaster(), Unit::SetInCombatState(), Player::SetIsSpectator(), Creature::SetLootRecipient(), Item::SetNotRefundable(), Unit::SetStunned(), Unit::SetSwim(), Player::SetTitle(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect(), npc_thassarian2::npc_thassarian2AI::sGossipSelect(), npc_akama_shade::npc_akamaAI::sGossipSelect(), Battlefield::ShowNpc(), boss_zuljin::boss_zuljinAI::SpawnAdds(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHit(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SpellHit(), npc_ulduar_vx001::npc_ulduar_vx001AI::SpellHit(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SpellHit(), npc_infernal_attacker::npc_infernal_attackerAI::SpellHit(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SpellHit(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit(), npc_draenei_survivor::npc_draenei_survivorAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), boss_headless_horseman_head::boss_headless_horseman_headAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), boss_black_knight::boss_black_knightAI::SpellHitTarget(), npc_belnistrasz::npc_belnistraszAI::sQuestAccept(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), npc_escortAI::Start(), instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter(), hyjalAI::StartEvent(), boss_noth::boss_nothAI::StartGroundPhase(), BattlegroundIC::StartingEventOpenDoors(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonHelpers(), GameObject::SwitchDoorOrButton(), ToggleFlag(), GameObject::Update(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), boss_taerar::boss_taerarAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_injured_patient::npc_injured_patientAI::UpdateAI(), Player::UpdatePvP(), and npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached().
RemoveFlag64()
void Object::RemoveFlag64 (uint16 index, uint64 oldFlag)
Definition at line 954 of file Object.cpp.
 {
     uint64 oldval = GetUInt64Value(index);
     uint64 newval = oldval & ~oldFlag;
     SetUInt64Value(index, newval);
 }
References GetUInt64Value(), index, and SetUInt64Value().
Referenced by ApplyModFlag64(), and ToggleFlag64().
RemoveFromObjectUpdate()
virtual void Object::RemoveFromObjectUpdate () protected pure virtual
Implemented in WorldObject, and Item.
Referenced by ClearUpdateMask().
RemoveFromWorld()
void Object::RemoveFromWorld () virtual
Reimplemented in Unit, Player, Pet, WorldObject, Bag, GameObject, DynamicObject, Puppet, Minion, TempSummon, Creature, and Corpse.
Definition at line 161 of file Object.cpp.
 {
     if (!m_inWorld)
         return;
     m_inWorld = false;
     // if we remove from world then sending changes not required
     ClearUpdateMask(true);
 }
References ClearUpdateMask(), and m_inWorld.
Referenced by Guild::BankMoveItemData::_StoreItem(), Player::_StoreItem(), Player::DestroyItem(), Player::EquipItem(), Bag::RemoveFromWorld(), WorldObject::RemoveFromWorld(), Player::RemoveFromWorld(), and Player::RemoveItemFromBuyBackSlot().
RemoveGuidValue()
bool Object::RemoveGuidValue (uint16 index, ObjectGuid value)
Definition at line 695 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, true));
     if (value && *((ObjectGuid*)&(m_uint32Values[index])) == value)
     {
         m_uint32Values[index] = 0;
         m_uint32Values[index + 1] = 0;
         _changesMask.SetBit(index);
         _changesMask.SetBit(index + 1);
         AddToObjectUpdateIfNeeded();
         return true;
     }
     return false;
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Unit::SetCharm(), Unit::SetMinion(), and Player::SetViewpoint().
SendUpdateToPlayer()
void Object::SendUpdateToPlayer (Player * player)
Definition at line 241 of file Object.cpp.
 {
     // send create update to player
     UpdateData upd;
     WorldPacket packet;
     BuildCreateUpdateBlockForPlayer(&upd, player);
     upd.BuildPacket(&packet);
     player->GetSession()->SendPacket(&packet);
 }
References BuildCreateUpdateBlockForPlayer(), UpdateData::BuildPacket(), Player::GetSession(), and WorldSession::SendPacket().
Referenced by Player::_StoreItem(), Player::DestroyItemCount(), Player::EquipItem(), WorldSession::HandleAuctionSellItem(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleSellItemOpcode(), Player::QuickEquipItem(), Player::RemoveItem(), Player::SplitItem(), Player::SwapItem(), PetAI::UpdateAI(), and Player::UpdateVisibilityOf().
SetByteFlag()
void Object::SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
Definition at line 902 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (offset > 3)
     {
         LOG_ERROR("entities.object", "Object::SetByteFlag: wrong offset %u", offset);
         return;
     }
     if (!(uint8(m_uint32Values[index] >> (offset * 8)) & newFlag))
     {
         m_uint32Values[index] |= uint32(uint32(newFlag) << (offset * 8));
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, LOG_ERROR, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by GameObject::CastSpell(), Player::Create(), Pet::CreateBaseAtTamed(), Spell::EffectRenamePet(), Player::GiveLevel(), AuraEffect::HandleAuraUntrackable(), AuraEffect::HandleDetectAmore(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModStealth(), WorldSession::HandlePlayerLoginFromDB(), AuraEffect::HandlePreventResurrection(), Player::SetGameMaster(), Player::SetIsSpectator(), Unit::SetPvP(), Unit::SetStandFlags(), Player::UpdateArea(), and Player::UpdateFFAPvPState().
SetByteValue()
void Object::SetByteValue (uint16 index, uint8 offset, uint8 value)
Definition at line 741 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (offset > 3)
     {
         LOG_ERROR("entities.object", "Object::SetByteValue: wrong offset %u", offset);
         return;
     }
     if (uint8(m_uint32Values[index] >> (offset * 8)) != value)
     {
         m_uint32Values[index] &= ~uint32(uint32(0xFF) << (offset * 8));
         m_uint32Values[index] |= uint32(uint32(value) << (offset * 8));
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References ASSERT, index, LOG_ERROR, m_valuesCount, and PrintIndexError().
Referenced by Creature::applyInhabitFlags(), Player::BuildPlayerRepop(), Player::Create(), Creature::Create(), DynamicObject::CreateDynamicObject(), boss_xt002::boss_xt002AI::DoAction(), WorldSession::HandleAlterAppearance(), modify_commandscript::HandleModifyGenderCommand(), reset_commandscript::HandleResetStatsOrLevelHelper(), WorldSession::HandleSetActionBarToggles(), Creature::InitEntry(), Creature::LoadCreaturesAddon(), Player::LoadFromDB(), Unit::RemoveCharmedBy(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::Reset(), boss_xt002::boss_xt002AI::Reset(), Creature::Respawn(), Player::ResurrectPlayer(), Player::SetBankBagSlotCount(), Player::SetBattlegroundId(), Unit::SetCharm(), Unit::SetCharmedBy(), Unit::SetDisplayId(), Player::SetDrunkValue(), Pet::SetFreeTalentPoints(), GameObject::SetGoAnimProgress(), GameObject::SetGoArtKit(), GameObject::SetGoState(), GameObject::SetGoType(), Unit::SetMinion(), Unit::setPowerType(), Player::SetRestBonus(), Unit::SetShapeshiftForm(), Unit::SetSheath(), Unit::SetStandState(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), boss_xt002::boss_xt002AI::UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), Creature::UpdateMovementFlags(), and Unit::UpdateSplineMovement().
SetEntry()
void Object::SetEntry (uint32 entry) inline
Definition at line 102 of file Object.h.
 { SetUInt32Value(OBJECT_FIELD_ENTRY, entry); }
References OBJECT_FIELD_ENTRY, and SetUInt32Value().
Referenced by Item::Create(), Bag::Create(), GameObject::Create(), StaticTransport::Create(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateMoTrans(), AuraEffect::HandleAuraDummy(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandleWrapItemOpcode(), Creature::InitEntry(), Item::LoadFromDB(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), and npc_lake_frog::npc_lake_frogAI::UpdateAI().
SetFieldNotifyFlag()
void Object::SetFieldNotifyFlag (uint16 flag) inline
Definition at line 174 of file Object.h.
 { _fieldNotifyFlags |= flag; }
References _fieldNotifyFlags.
Referenced by Group::AddMember(), Unit::SetOwnerGUID(), and Player::UpdateTriggerVisibility().
SetFlag()
void Object::SetFlag (uint16 index, uint32 newFlag)
Definition at line 836 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     uint32 oldval = m_uint32Values[index];
     uint32 newval = oldval | newFlag;
     if (oldval != newval)
     {
         m_uint32Values[index] = newval;
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Player::_LoadGroup(), Player::_StoreOrEquipNewItem(), Vehicle::AddPassenger(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals(), ApplyModFlag(), npc_doctor::npc_doctorAI::BeginEvent(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_ahune::boss_ahuneAI::boss_ahuneAI(), boss_eydis::boss_eydisAI::boss_eydisAI(), boss_fjola::boss_fjolaAI::boss_fjolaAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_ragnaros::boss_ragnarosAI::boss_ragnarosAI(), boss_the_lich_king::boss_the_lich_kingAI::boss_the_lich_kingAI(), GameObject::CastSpell(), Group::ChangeLeader(), Unit::ClearInCombat(), Player::Create(), Group::Create(), violet_hold_trashAI::CreatureStartAttackDoor(), boss_taerar::boss_taerarAI::DamageTaken(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), npc_mograine::npc_mograineAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), boss_muru::boss_muruAI::DamageTaken(), boss_eye_of_cthun::eye_of_cthunAI::DamageTaken(), boss_twinemperorsAI::DamageTaken(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), boss_black_knight::boss_black_knightAI::DamageTaken(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_bronjahm::boss_bronjahmAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_crystalline_frayer::npc_crystalline_frayerAI::DamageTaken(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken(), npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::DamageTaken(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::DamageTaken(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::DamageTaken(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken(), boss_essence_of_desire::boss_essence_of_desireAI::DamageTaken(), npc_molten_golem::npc_molten_golemAI::DamageTaken(), npc_tiger_matriarch::npc_tiger_matriarchAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), npc_calvin_montague::npc_calvin_montagueAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), go_suppression_device::go_suppression_deviceAI::Deactivate(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Deactivate(), Unit::DisableRotate(), boss_thorim::boss_thorimAI::DisableThorim(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), boss_felmyst::boss_felmystAI::DoAction(), boss_grand_champion::boss_grand_championAI::DoAction(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron::boss_yoggsaronAI::DoAction(), PetAI::DoAttack(), FlightPathMovementGenerator::DoReset(), Spell::EffectOpenLock(), Spell::EffectSkinning(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnableSara(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_mimiron::boss_mimironAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_felmyst::boss_felmystAI::EnterCombat(), boss_novos::boss_novosAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), npc_escortAI::EnterEvadeMode(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode(), boss_anubarak_trial::boss_anubarak_trialAI::EnterEvadeMode(), boss_jaraxxus::boss_jaraxxusAI::EnterEvadeMode(), boss_gormok::boss_gormokAI::EnterEvadeMode(), boss_jormungarAI::EnterEvadeMode(), boss_icehowl::boss_icehowlAI::EnterEvadeMode(), boss_cyanigosa::boss_cyanigosaAI::EnterEvadeMode(), boss_erekem::boss_erekemAI::EnterEvadeMode(), boss_ichoron::boss_ichoronAI::EnterEvadeMode(), boss_lavanthor::boss_lavanthorAI::EnterEvadeMode(), boss_moragg::boss_moraggAI::EnterEvadeMode(), boss_xevozz::boss_xevozzAI::EnterEvadeMode(), boss_zuramat::boss_zuramatAI::EnterEvadeMode(), boss_ahune::boss_ahuneAI::EnterEvadeMode(), boss_zuljin::boss_zuljinAI::EnterPhase(), UtherBatteredHiltEvent::Execute(), SACDeactivateEvent::Execute(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::FeignDeath(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleApply(), AuraEffect::HandleArenaPreparation(), Pet::HandleAsynchLoadSucceed(), AuraEffect::HandleAuraAllowOnlyAbility(), AuraEffect::HandleAuraCloneCaster(), AuraEffect::HandleAuraGhost(), AuraEffect::HandleAuraModDisarm(), AuraEffect::HandleAuraModFaction(), AuraEffect::HandleAuraModPacify(), AuraEffect::HandleAuraModSilence(), AuraEffect::HandleAuraModStalked(), AuraEffect::HandleAuraTrackCreatures(), AuraEffect::HandleAuraTrackResources(), AuraEffect::HandleComprehendLanguage(), OPvPCapturePointNA::HandleCustomSpell(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectApply(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectApply(), spell_gen_model_visible::HandleEffectApply(), spell_gen_creature_permanent_feign_death::HandleEffectApply(), spell_q11396_11399_force_shield_arcane_purple_x3::HandleEffectApply(), spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::HandleEffectRemove(), cheat_commandscript::HandleExploreCheatCommand(), AuraEffect::HandleFeignDeath(), AuraEffect::HandleForceMoveForward(), BattlefieldWG::HandleKill(), Battleground::HandleKillPlayer(), WorldSession::HandleLogoutRequestOpcode(), WorldSession::HandleMailCreateTextItem(), modify_commandscript::HandleModifyBitCommand(), WorldSession::HandleMovementOpcodes(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectApply(), WorldSession::HandleSetTaxiBenchmarkOpcode(), spell_item_draenic_pale_ale::HandleSummon(), Battlefield::HideNpc(), npc_cork_gizelton::npc_cork_gizeltonAI::ImmuneFlagSet(), boss_vaelastrasz::boss_vaelAI::Initialize(), prince_axes::prince_axesAI::Initialize(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::Initialize(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::InitializeAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::InitializeAI(), boss_kiljaeden::boss_kiljaedenAI::InitializeAI(), boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::InitializeAI(), npc_sergeant_bly::npc_sergeant_blyAI::InitializeAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::InitializeAI(), boss_taldaram::boss_taldaramAI::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::InitializeAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::InitializeAI(), Player::InitStatsForLevel(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), boss_twinemperorsAI::JustDied(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied(), socrethar::socretharAI::JustDied(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::JustReachedHome(), boss_the_lich_king::boss_the_lich_kingAI::JustReachedHome(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustSummoned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), boss_majordomo::boss_majordomoAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_vaelastrasz::boss_vaelAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), boss_broggok::boss_broggokAI::JustSummoned(), npc_varian_wrynn::npc_varian_wrynnAI::JustSummoned(), Unit::Kill(), Player::LoadFromDB(), GameObject::LoadGameObjectFromDB(), Unit::ModifyAuraState(), Unit::Mount(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_fairbanks::npc_fairbanksAI::MoveInLineOfSight(), npc_fos_leader_second::npc_fos_leader_secondAI::MovementInform(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::MovementInform(), npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::MovementInform(), npc_giant_infernal::npc_giant_infernalAI::npc_giant_infernalAI(), npc_hol_monument::npc_hol_monumentAI::npc_hol_monumentAI(), npc_madrigosa::npc_madrigosaAI::npc_madrigosaAI(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::npc_mageguard_dalaranAI(), npc_omen::npc_omenAI::npc_omenAI(), npc_pos_freed_slave::npc_pos_freed_slaveAI::npc_pos_freed_slaveAI(), npc_q24545_vegard::npc_q24545_vegardAI::npc_q24545_vegardAI(), npc_rinji::npc_rinjiAI::npc_rinjiAI(), npc_xt002_heart::npc_xt002_heartAI::npc_xt002_heartAI(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnApply(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply(), BattlefieldWG::OnBattleStart(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), go_gong_of_bethekk::OnGossipHello(), go_elune_fire::OnGossipHello(), go_palehoof_sphere::OnGossipHello(), go_main_chambers_access_panel::OnGossipHello(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), npc_experience::OnGossipSelect(), NPCStaveQuestAI::PrepareForEncounter(), PretendToDie(), npc_chicken_cluck::npc_chicken_cluckAI::ReceiveEmote(), npc_plucky::npc_pluckyAI::ReceiveEmote(), Creature::RefreshSwimmingFlag(), Player::RemovedInsignia(), Vehicle::RemovePassenger(), boss_keristrasza::boss_keristraszaAI::RemovePrison(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), npc_grimstone::npc_grimstoneAI::Reset(), boss_doomrel::boss_doomrelAI::Reset(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), npc_death_knight_initiate::npc_death_knight_initiateAI::Reset(), npc_unworthy_initiate::npc_unworthy_initiateAI::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), npc_a_special_surprise::npc_a_special_surpriseAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_corporal_keeshan::npc_corporal_keeshanAI::Reset(), npc_calvin_montague::npc_calvin_montagueAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), boss_nalorakk::boss_nalorakkAI::Reset(), npc_batrider::npc_batriderAI::Reset(), npc_coren_direbrew::npc_coren_direbrewAI::Reset(), npc_hallows_end_soh::npc_hallows_end_sohAI::Reset(), npc_ancient_wisp::npc_ancient_wispAI::Reset(), hyjalAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), npc_belnistrasz::npc_belnistraszAI::Reset(), boss_cthun::cthunAI::Reset(), npc_depth_charge::npc_depth_chargeAI::Reset(), npc_draenei_survivor::npc_draenei_survivorAI::Reset(), npc_injured_draenei::npc_injured_draeneiAI::Reset(), npc_death_ravager::npc_death_ravagerAI::Reset(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::Reset(), npc_enraged_panther::npc_enraged_pantherAI::Reset(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset(), boss_black_knight::boss_black_knightAI::Reset(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_falric::boss_falricAI::Reset(), boss_marwyn::boss_marwynAI::Reset(), boss_tyrannus::boss_tyrannusAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::Reset(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_malygos::boss_malygosAI::Reset(), boss_eregos::boss_eregosAI::Reset(), boss_urom::boss_uromAI::Reset(), boss_varos::boss_varosAI::Reset(), boss_loken::boss_lokenAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::Reset(), boss_kologarn::boss_kologarnAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), npc_massive_jormungar::npc_massive_jormungarAI::Reset(), npc_ferocious_rhino::npc_ferocious_rhinoAI::Reset(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::Reset(), npc_frenzied_worgen::npc_frenzied_worgenAI::Reset(), boss_svala::boss_svalaAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), npc_thassarian::npc_thassarianAI::Reset(), npc_thassarian2::npc_thassarian2AI::Reset(), npc_drakuru_shackles::npc_drakuru_shacklesAI::Reset(), npc_crusade_recruit::npc_crusade_recruitAI::Reset(), npc_akama_illidan::npc_akama_illidanAI::Reset(), boss_shade_of_akama::boss_shade_of_akamaAI::Reset(), npc_akama_shade::npc_akamaAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), npc_naga_distiller::npc_naga_distillerAI::Reset(), boss_broggok::boss_broggokAI::Reset(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::Reset(), boss_magtheridon::boss_magtheridonAI::Reset(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), npc_deaths_fel_cannon::npc_deaths_fel_cannonAI::Reset(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::Reset(), npc_injured_patient::npc_injured_patientAI::Reset(), Vehicle::Reset(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::ResetData(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisoner(), NPCStaveQuestAI::ResetState(), Player::ResurrectPlayer(), Player::SendLoot(), Unit::SetCharm(), Unit::SetCharmedBy(), Unit::SetContestedPvP(), boss_svala::boss_svalaAI::SetData(), Creature::setDeathState(), GameObject::SetDestructibleState(), Player::SetGameMaster(), Unit::SetInCombatState(), Player::SetIsSpectator(), Creature::SetLootRecipient(), Unit::SetMinion(), Player::SetQuestSlotState(), Player::SetRestFlag(), Player::SetRestState(), Item::SetSoulboundTradeable(), Unit::SetStunned(), Unit::SetSwim(), Player::SetTitle(), Battlefield::ShowNpc(), boss_zuljin::boss_zuljinAI::SpawnAdds(), netherspite_infernal::netherspite_infernalAI::SpellHit(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), boss_urom::boss_uromAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), boss_ionar::boss_ionarAI::Split(), boss_noth::boss_nothAI::StartBalconyPhase(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), GameObject::SwitchDoorOrButton(), ToggleFlag(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), hyjalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_tallhorn_stag::npc_tallhorn_stagAI::UpdateAI(), npc_injured_patient::npc_injured_patientAI::UpdateAI(), Creature::UpdateEntry(), Player::UpdatePvPFlag(), GameObject::Use(), npc_arthas::npc_arthasAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
SetFlag64()
void Object::SetFlag64 (uint16 index, uint64 newFlag)
Definition at line 947 of file Object.cpp.
 {
     uint64 oldval = GetUInt64Value(index);
     uint64 newval = oldval | newFlag;
     SetUInt64Value(index, newval);
 }
References GetUInt64Value(), index, and SetUInt64Value().
Referenced by Player::AddKnownCurrency(), ApplyModFlag64(), and ToggleFlag64().
SetFloatValue()
void Object::SetFloatValue (uint16 index, float value)
Definition at line 728 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (m_floatValues[index] != value)
     {
         m_floatValues[index] = value;
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_floatValues, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by ApplyModPositiveFloatValue(), ApplyModSignedFloatValue(), ApplyPercentModFloatValue(), Player::Create(), DynamicObject::CreateDynamicObject(), debug_commandscript::HandleDebugSetValueCommand(), spell_dk_dancing_rune_weapon_visual::HandleEffectApply(), spell_moorabi_mojo_frenzy::spell_moorabi_mojo_frenzy_AuraScript::HandlePeriodic(), spell_dk_dancing_rune_weapon::HandleProc(), Creature::InitEntry(), Player::InitRunes(), Player::InitStatsForLevel(), Guardian::InitStatsForLevel(), Player::LoadFromDB(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::Reset(), Unit::SetAttackTime(), Creature::SetDisplayId(), SetObjectScale(), Creature::SetObjectScale(), Player::SetObjectScale(), Unit::SetResistanceBuffMods(), SetStatFloatValue(), GameObject::SetTransportPathRotation(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), Creature::UpdateAttackPowerAndDamage(), Guardian::UpdateAttackPowerAndDamage(), Player::UpdateAttackPowerAndDamage(), Player::UpdateRuneRegen(), and Player::UpdateSpellCritChance().
SetGuidValue()
void Object::SetGuidValue (uint16 index, ObjectGuid value)
Definition at line 714 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, true));
     if (*((ObjectGuid*)&(m_uint32Values[index])) != value)
     {
         *((ObjectGuid*)&(m_uint32Values[index])) = value;
         _changesMask.SetBit(index);
         _changesMask.SetBit(index + 1);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by _Create(), Player::_StoreItem(), Player::AddItemToBuyBackSlot(), Map::ConvertCorpseToBones(), Corpse::Create(), Item::Create(), Bag::Create(), DynamicObject::CreateDynamicObject(), Player::DestroyItem(), Spell::DoCreateItem(), Player::DuelComplete(), Spell::EffectDuel(), Spell::EffectTransmitted(), boss_novos::boss_novosAI::EnterCombat(), Creature::FocusTarget(), Unit::GetCharm(), WorldSession::HandleAcceptTradeOpcode(), misc_commandscript::HandleCreatePetCommand(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandleWrapItemOpcode(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), Bag::LoadFromDB(), WorldSession::LogoutPlayer(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), Creature::ReleaseFocus(), Player::RemoveItem(), Bag::RemoveItem(), Player::RemoveItemFromBuyBackSlot(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Unit::SetCharmerGUID(), Unit::SetCreatorGUID(), Unit::SetCritterGUID(), Guild::BankTab::SetItem(), Unit::SetMinionGUID(), Item::SetOwnerGUID(), GameObject::SetOwnerGUID(), Unit::SetOwnerGUID(), Player::SetSelection(), Creature::SetTarget(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), Bag::StoreItem(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), and Player::VisualizeItem().
SetInt16Value()
void Object::SetInt16Value (uint16 index, uint8 offset, int16 value) inline
Definition at line 134 of file Object.h.
 { SetUInt16Value(index, offset, (uint16)value); }
References index, and SetUInt16Value().
SetInt32Value()
void Object::SetInt32Value (uint16 index, int32 value)
Definition at line 628 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (m_int32Values[index] != value)
     {
         m_int32Values[index] = value;
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_int32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by ApplyModInt32Value(), Player::Create(), AuraEffect::HandleAuraModFakeInebriation(), Player::InitStatsForLevel(), Player::LoadFromDB(), Item::LoadFromDB(), Item::SetItemRandomProperties(), Item::SetSpellCharges(), Creature::UpdateAttackPowerAndDamage(), Guardian::UpdateAttackPowerAndDamage(), and Player::UpdateAttackPowerAndDamage().
SetObjectScale()
virtual void Object::SetObjectScale (float scale) inline virtual
Reimplemented in Player, and Creature.
Definition at line 105 of file Object.h.
 { SetFloatValue(OBJECT_FIELD_SCALE_X, scale); }
References OBJECT_FIELD_SCALE_X, and SetFloatValue().
Referenced by Corpse::Create(), Item::Create(), Bag::Create(), GameObject::Create(), StaticTransport::Create(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateMoTrans(), AuraEffect::HandleAuraModScale(), spell_hallows_end_base_fire::spell_hallows_end_base_fire_AuraScript::HandleEffectApply(), modify_commandscript::HandleModifyScaleCommand(), Corpse::LoadCorpseFromDB(), Item::LoadFromDB(), Creature::SetObjectScale(), Player::SetObjectScale(), and boss_akilzon::boss_akilzonAI::UpdateAI().
SetStatFloatValue()
void Object::SetStatFloatValue (uint16 index, float value)
Definition at line 781 of file Object.cpp.
 {
     if (value < 0)
         value = 0.0f;
     SetFloatValue(index, value);
 }
References index, and SetFloatValue().
Referenced by spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), npc_pet_hunter_snake_trap::UpdateAI(), Player::UpdateBlockPercentage(), Player::UpdateCritPercentage(), Unit::UpdateDamagePhysical(), Guardian::UpdateDamagePhysical(), Player::UpdateDodgePercentage(), Player::UpdateManaRegen(), and Player::UpdateParryPercentage().
SetStatInt32Value()
void Object::SetStatInt32Value (uint16 index, int32 value)
Definition at line 789 of file Object.cpp.
 {
     if (value < 0)
         value = 0;
     SetUInt32Value(index, uint32(value));
 }
References index, and SetUInt32Value().
Referenced by Unit::SetMaxPower(), Unit::SetPower(), Unit::SetResistance(), Unit::SetStat(), and Player::UpdateSpellDamageAndHealingBonus().
SetUInt16Value()
void Object::SetUInt16Value (uint16 index, uint8 offset, uint16 value)
Definition at line 761 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (offset > 1)
     {
         LOG_ERROR("entities.object", "Object::SetUInt16Value: wrong offset %u", offset);
         return;
     }
     if (uint16(m_uint32Values[index] >> (offset * 16)) != value)
     {
         m_uint32Values[index] &= ~uint32(uint32(0xFFFF) << (offset * 16));
         m_uint32Values[index] |= uint32(uint32(value) << (offset * 16));
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, LOG_ERROR, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Player::ApplyEnchantment(), AuraEffect::HandleAuraOverrideSpells(), Player::LoadFromDB(), SetInt16Value(), and Player::SetVisibleItemSlot().
SetUInt32Value()
void Object::SetUInt32Value (uint16 index, uint32 value)
Definition at line 641 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     if (m_uint32Values[index] != value)
     {
         m_uint32Values[index] = value;
         _changesMask.SetBit(index);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by _Create(), Player::_LoadDailyQuestStatus(), Player::_LoadSkills(), Player::AddItemToBuyBackSlot(), ApplyModUInt32Value(), Unit::Attack(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_anzu::boss_anzuAI::boss_anzuAI(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckItems(), Item::ClearEnchantment(), Unit::ClearInCombat(), Item::CloneItem(), boss_thorim::boss_thorimAI::CloseDoors(), Map::ConvertCorpseToBones(), Player::Create(), Item::Create(), Bag::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtTamed(), Player::CreateCorpse(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateMoTrans(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), GameObject::Delete(), GameObject::DespawnOrUnsummon(), Unit::Dismount(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::DoAction(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::DoAction(), Player::DuelComplete(), Player::DurabilityPointsLoss(), Player::DurabilityRepair(), Spell::EffectDuel(), Spell::EffectResurrectPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), SmartAI::EndPath(), boss_xt002::boss_xt002AI::EnterCombat(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), BattlegroundIC::EventPlayerClickedOnFlag(), npc_unworthy_initiate::npc_unworthy_initiateAI::EventStart(), Player::GiveLevel(), Pet::GivePetLevel(), Pet::GivePetXP(), Player::GiveXP(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), Pet::HandleAsynchLoadFailed(), Pet::HandleAsynchLoadSucceed(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraModIncreaseFlightSpeed(), AuraEffect::HandleAuraTransform(), character_commandscript::HandleCharacterLevel(), misc_commandscript::HandleCreatePetCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugSet32BitCommand(), debug_commandscript::HandleDebugSetItemValueCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugUpdateCommand(), spell_dk_dancing_rune_weapon_visual::HandleEffectApply(), spell_gen_model_visible::HandleEffectApply(), spell_gen_model_visible::HandleEffectRemove(), spell_gen_baby_murloc::HandleEffectRemove(), misc_commandscript::HandleHideAreaCommand(), WorldSession::HandleMailCreateTextItem(), modify_commandscript::HandleModifyFactionCommand(), modify_commandscript::HandleModifyStandStateCommand(), AuraEffect::HandleNoReagentUseAura(), npc_commandscript::HandleNpcPlayEmoteCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcTameCommand(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetRename(), reset_commandscript::HandleResetHonorCommand(), reset_commandscript::HandleResetLevelCommand(), reset_commandscript::HandleResetStatsOrLevelHelper(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), WorldSession::HandleSelfResOpcode(), WorldSession::HandleSetTitleOpcode(), WorldSession::HandleSetWatchedFactionOpcode(), misc_commandscript::HandleShowAreaCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), WorldSession::HandleWrapItemOpcode(), Player::InitGlyphsForLevel(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), Player::InitStatsForLevel(), Guardian::InitStatsForLevel(), Unit::InitTamedPet(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::JustDied(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), Unit::Kill(), Player::KillPlayer(), Corpse::LoadCorpseFromDB(), Creature::LoadCreaturesAddon(), Creature::LoadEquipment(), Player::LoadFromDB(), Item::LoadFromDB(), Bag::LoadFromDB(), WorldSession::LogoutPlayer(), Player::ModifySkillBonus(), Unit::Mount(), WorldSession::moveItems(), boss_grand_champion::boss_grand_championAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_thassarian2::npc_thassarian2AI::MovementInform(), boss_headless_horseman::boss_headless_horsemanAI::MovementInform(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::npc_scarlet_miner_cartAI(), spell_gen_clone_weapon_aura::OnApply(), BattlefieldWG::OnBattleStart(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), boss_yoggsaron_descend_portal::OnGossipHello(), npc_ulduar_keeper::OnGossipSelect(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), npc_shandy_dalaran::OnGossipSelect(), npc_ame::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), spell_gen_clone_weapon_aura::OnRemove(), BattlegroundIC::PostUpdateImpl(), npc_hidden_cultist::npc_hidden_cultistAI::PreScript(), BfWGGameObjectBuilding::Rebuild(), Player::RemoveAmmo(), Player::RemoveItemFromBuyBackSlot(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_doomrel::boss_doomrelAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), npc_unworthy_initiate::npc_unworthy_initiateAI::Reset(), npc_eris_hevenfire::npc_eris_hevenfireAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), npc_yenniku::npc_yennikuAI::Reset(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::Reset(), boss_zuljin::boss_zuljinAI::Reset(), boss_arlokk::boss_arlokkAI::Reset(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::Reset(), npc_taretha::npc_tarethaAI::Reset(), boss_grand_champion::boss_grand_championAI::Reset(), npc_hor_leader::npc_hor_leaderAI::Reset(), boss_malygos::boss_malygosAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), npc_hidden_cultist::npc_hidden_cultistAI::Reset(), npc_thassarian2::npc_thassarian2AI::Reset(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::Reset(), npc_crusade_recruit::npc_crusade_recruitAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), npc_pet_gen_argent_pony_bridle::Reset(), npc_injured_patient::npc_injured_patientAI::Reset(), Player::ResetDailyQuestStatus(), BattlegroundSA::ResetObjs(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Player::SetAmmo(), Player::SetArenaPoints(), Player::SetArenaTeamInfoField(), Unit::SetCharmedBy(), Item::SetCount(), Unit::SetCreateHealth(), Unit::SetCreateMana(), Player::SetCurrentTitle(), Player::SetDailyQuestStatus(), npc_ulduar_vx001::npc_ulduar_vx001AI::SetData(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::SetData(), Creature::setDeathState(), Pet::setDeathState(), Player::setDeathState(), GameObject::SetDisplayId(), Unit::SetDisplayId(), Item::SetEnchantment(), Item::SetEnchantmentCharges(), Item::SetEnchantmentDuration(), SetEntry(), ScriptedAI::SetEquipmentSlots(), Unit::SetFaction(), Player::SetFreePrimaryProfessions(), Player::SetFreeTalentPoints(), Player::SetGlyph(), Player::SetGlyphSlot(), npc_eris_hevenfire::npc_eris_hevenfireAI::SetGUID(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), Unit::SetHealth(), Player::SetHonorPoints(), Player::SetInGuild(), Unit::SetLevel(), Unit::SetMaxHealth(), Player::SetMoney(), Unit::SetNativeDisplayId(), StaticTransport::SetPauseTime(), MotionTransport::SetPeriod(), CharmInfo::SetPetNumber(), Player::SetQuestSlot(), Player::SetQuestSlotTimer(), Player::SetRank(), Player::SetRestBonus(), Player::SetSkill(), SetStatInt32Value(), BattlefieldWG::SetupBattlefield(), Player::SetVisibleItemSlot(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), npc_yenniku::npc_yennikuAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), npc_escortAI::Start(), FollowerAI::StartFollow(), SmartAI::StartPath(), Player::StoreNewItem(), Map::SummonCreature(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), Player::SwapQuestSlot(), GameObject::Update(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_pet_gen_argent_pony_bridle::UpdateAI(), npc_tallhorn_stag::npc_tallhorn_stagAI::UpdateAI(), Player::UpdateArmorPenetration(), Player::UpdateDuelFlag(), Item::UpdateDuration(), Creature::UpdateEntry(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), Player::UpdateExpertise(), Player::UpdateHonorFields(), Item::UpdateItemSuffixFactor(), Item::UpdatePlayedTime(), Player::UpdateRating(), Player::UpdateShieldBlockValue(), Player::UpdateSkill(), Player::UpdateSkillPro(), Player::UpdateSkillsForLevel(), Player::UpdateSkillsToMaxSkillsForLevel(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached(), npc_captain_saeed::npc_captain_saeedAI::WaypointReached(), npc_akama_illidan::npc_akama_illidanAI::WaypointReached(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), and npc_ghoul::npc_ghoulAI::WaypointReached().
SetUInt64Value()
void Object::SetUInt64Value (uint16 index, uint64 value)
Definition at line 662 of file Object.cpp.
 {
     ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, true));
     if (*((uint64*) & (m_uint32Values[index])) != value)
     {
         m_uint32Values[index] = PAIR64_LOPART(value);
         m_uint32Values[index + 1] = PAIR64_HIPART(value);
         _changesMask.SetBit(index);
         _changesMask.SetBit(index + 1);
         AddToObjectUpdateIfNeeded();
     }
 }
References _changesMask, AddToObjectUpdateIfNeeded(), ASSERT, index, m_uint32Values, m_valuesCount, PAIR64_HIPART(), PAIR64_LOPART(), PrintIndexError(), and UpdateMask::SetBit().
Referenced by Player::Create(), titles_commandscript::HandleTitlesSetMaskCommand(), Player::LoadFromDB(), RemoveFlag64(), SetFlag64(), Player::SetQuestSlotCounter(), and boss_koralon::boss_koralonAI::UpdateAI().
ToCorpse() [1/2]
Corpse* Object::ToCorpse () inline
Definition at line 191 of file Object.h.
 { if (GetTypeId() == TYPEID_CORPSE) return reinterpret_cast<Corpse*>(this); else return nullptr; }
References GetTypeId(), and TYPEID_CORPSE.
Referenced by SpellInfo::CheckTarget(), SpellCastTargets::GetCorpseTarget(), GetUpdateFieldData(), and Acore::WorldObjectSpellTargetCheck::operator()().
ToCorpse() [2/2]
Corpse const* Object::ToCorpse () const inline
Definition at line 192 of file Object.h.
 { if (GetTypeId() == TYPEID_CORPSE) return (const Corpse*)((Corpse*)this); else return nullptr; }
References GetTypeId(), and TYPEID_CORPSE.
ToCreature() [1/2]
Creature* Object::ToCreature () inline
Definition at line 183 of file Object.h.
 { if (GetTypeId() == TYPEID_UNIT) return reinterpret_cast<Creature*>(this); else return nullptr; }
References GetTypeId(), and TYPEID_UNIT.
Referenced by Spell::_cast(), Map::_GetScriptCreature(), Map::_GetScriptCreatureSourceOrTarget(), KillRewarder::_InitXP(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), KillRewarder::_RewardKillCredit(), Vehicle::AddPassenger(), Player::AddQuestAndCheckCompletion(), Vehicle::ApplyAllImmunities(), Unit::ApplyDiminishingToDuration(), npc_escortAI::AssistPlayerInCombat(), Unit::Attack(), Unit::AttackStop(), PathGenerator::BuildPolyPath(), Unit::BuildValuesUpdate(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), Creature::CanAssistTo(), Creature::CanCreatureAttack(), WorldObject::CanDetectStealthOf(), Unit::CanHaveThreatList(), Map::CanReachPositionAndGetValidCoords(), WorldObject::CanSeeOrDetect(), CharmInfo::CharmInfo(), Player::CharmSpellInitialize(), spell_dk_death_pact::CheckCast(), Spell::CheckCast(), Spell::CheckPetCast(), spell_item_lil_phylactery::CheckProc(), SpellInfo::CheckTarget(), spell_the_lich_king_shadow_trap_periodic::spell_the_lich_king_shadow_trap_periodic_SpellScript::CheckTargetCount(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::CheckTargetCount(), Unit::ClearInCombat(), Unit::CombatStart(), Unit::CombatStartOnCast(), Unit::DealDamage(), Unit::DealDamageMods(), Unit::DealHeal(), Unit::DealMeleeDamage(), Unit::DealSpellDamage(), MotionTransport::DelayedTeleportTransport(), HostileRefMgr::deleteReferences(), spell_rotface_unstable_ooze_explosion_suicide::spell_rotface_unstable_ooze_explosion_suicide_AuraScript::DespawnSelf(), Vehicle::Dismiss(), boss_skadi_grauf::boss_skadi_graufAI::DoAction(), Spell::DoAllEffectOnTarget(), ChaseMovementGenerator< T >::DoFinalize(), Spell::DoSpellHitOnUnit(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), CreatureAI::DoZoneInCombat(), Spell::EffectCreateTamedPet(), Spell::EffectDummy(), Spell::EffectKnockBack(), Spell::EffectScriptEffect(), Spell::EffectSkinning(), Spell::EffectSummonPet(), Spell::EffectTameCreature(), Spell::EffectTaunt(), npc_rinji::npc_rinjiAI::EnterCombat(), VehicleDespawnEvent::Execute(), Unit::ExecuteDelayedUnitRelocationEvent(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::FilterTargets(), spell_kelthuzad_frost_blast::spell_kelthuzad_frost_blast_SpellScript::FilterTargets(), spell_sapphiron_frost_explosion::spell_sapphiron_frost_explosion_SpellScript::FilterTargets(), spell_dk_aotd_taunt::FilterTargets(), AssistanceMovementGenerator::Finalize(), RotateMovementGenerator::Finalize(), DistractMovementGenerator::Finalize(), AssistanceDistractMovementGenerator::Finalize(), EffectMovementGenerator::Finalize(), Spell::finish(), Acore::XP::Gain(), Unit::GetAllMinionsByEntry(), Unit::GetCreatureType(), Player::GetDefaultGossipMenuForSource(), Unit::GetFactionTemplateEntry(), WorldObject::GetGridActivationRange(), SpellScript::GetHitCreature(), boss_ick::boss_ickAI::GetKrick(), Player::GetQuestDialogStatus(), Unit::GetRandomContactPoint(), WorldObject::GetSightRange(), Unit::GetUnitBlockChance(), Unit::GetUnitDodgeChance(), Unit::GetUnitParryChance(), ObjectMgr::GetVehicleAccessoryList(), Player::GiveXP(), Group::GroupLoot(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleAfterCast(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleApply(), Pet::HandleAsynchLoadFailed(), AuraEffect::HandleAuraControlVehicle(), AuraEffect::HandleAuraModDisarm(), Aura::HandleAuraSpecificMods(), WorldSession::HandleCastSpellOpcode(), misc_commandscript::HandleCreatePetCommand(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), misc_commandscript::HandleDieCommand(), WorldSession::HandleDismissCritter(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), spell_gen_despawn_self::HandleDummy(), spell_item_lil_xt::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_item_rocket_chicken::HandleDummyTick(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectApply(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectApply(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::HandleEffectApply(), spell_gen_creature_permanent_feign_death::HandleEffectApply(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectRemove(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectRemove(), spell_dtk_raise_dead::spell_dtk_raise_dead_AuraScript::HandleEffectRemove(), spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::HandleEffectRemove(), spell_gen_creature_permanent_feign_death::HandleEffectRemove(), spell_hate_to_zero::spell_hate_to_zero_SpellScript::HandleHit(), spell_item_toxic_wasteling::HandleJump(), npc_commandscript::HandleNpcSetEntryCommand(), npc_commandscript::HandleNpcSetFactionTempIdCommand(), npc_commandscript::HandleNpcSetOriginalFaction(), npc_commandscript::HandleNpcTameCommand(), spell_warhead_fuse::spell_warhead_fuse_AuraScript::HandleOnEffectRemove(), spell_hun_taming_the_beast::HandleOnEffectRemove(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), AuraEffect::HandlePhase(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverStatusQueryOpcode(), spell_jedoga_sacrafice_beam::spell_jedoga_sacrafice_beam_AuraScript::HandleRemoval(), spell_kiljaeden_darkness::spell_kiljaeden_darkness_AuraScript::HandleRemove(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleRemove(), misc_commandscript::HandleRespawnCommand(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::HandleScript(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::HandleScript(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_q12690_burst_at_the_seams::HandleScript(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::HandleScriptEffect(), spell_volazj_whisper::spell_volazj_whisper_SpellScript::HandleScriptEffect(), spell_gluth_decimate::spell_gluth_decimate_SpellScript::HandleScriptEffect(), Unit::HandleSpellClick(), spell_q11065_wrangle_some_aether_rays_aura::if(), CharmInfo::InitCharmCreateSpells(), MotionMaster::InitDefault(), CharmInfo::InitPossessCreateSpells(), TempSummon::InitSummon(), Vehicle::InstallAccessory(), Player::isHonorOrXPTarget(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Unit::isSpellBlocked(), npc_infernal_attacker::npc_infernal_attackerAI::IsSummonedBy(), PathGenerator::IsSwimmableSegment(), WorldObject::IsWorldObject(), npc_gunship::npc_gunshipAI::JustDied(), Unit::Kill(), netherspite_infernal::netherspite_infernalAI::KilledUnit(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), Unit::MagicSpellHitResult(), Condition::Meets(), Unit::MeleeSpellHitResult(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::MoveInLineOfSight(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), MotionMaster::MoveSeekAssistance(), MotionMaster::MoveTargetedHome(), Group::NeedBeforeGreed(), ScriptMgr::OnAddPassenger(), spell_scholomance_boon_of_life::spell_scholomance_boon_of_life_AuraScript::OnApply(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnApply(), spell_systems_shutdown::spell_systems_shutdown_AuraScript::OnApply(), spell_pilgrims_bounty_serve_generic::spell_pilgrims_bounty_serve_generic_AuraScript::OnAuraRemove(), achievement_volunteer_work::OnCheck(), achievement_ive_gone_and_made_a_mess::OnCheck(), achievement_flu_shot_shortage::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_ignis_shattered::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), Player::OnGossipSelect(), SmartScript::OnInitialize(), ScriptMgr::OnInstall(), ScriptMgr::OnInstallAccessory(), spell_illidan_demon_transform1::spell_illidan_demon_transform1_AuraScript::OnPeriodic(), spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript::OnPeriodic(), spell_scholomance_boon_of_life::spell_scholomance_boon_of_life_AuraScript::OnRemove(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnRemove(), spell_systems_shutdown::spell_systems_shutdown_AuraScript::OnRemove(), spell_kaelthas_flame_strike::spell_kaelthas_flame_strike_AuraScript::OnRemove(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnReset(), ScriptMgr::OnUninstall(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), SplineHandler::operator()(), Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), DoorsGuidCheck::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), FlameLeviathanPursuedTargetSelector::operator()(), MysticBuffetTargetFilter::operator()(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::PassengerBoarded(), npc_ulduar_vx001::npc_ulduar_vx001AI::PassengerBoarded(), Unit::PetSpellFail(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), Spell::prepare(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_valkyr_ball_periodic_dummy::spell_valkyr_ball_periodic_dummyAuraScript::PrepareAuraScript(), Spell::prepareDataForTriggerSystem(), Player::PrepareGossipMenu(), spell_mage_deep_freeze::PrepareSpellScript(), SmartScript::ProcessAction(), Unit::ProcessTerrainStatusUpdate(), Unit::RemoveAllMinionsByEntry(), Map::RemoveAllObjectsInRemoveList(), Unit::RemoveCharmedBy(), Vehicle::RemovePassenger(), Unit::RestoreFaction(), CharmInfo::RestoreState(), KillRewarder::Reward(), Player::RewardHonor(), Player::RewardReputation(), Unit::RollMeleeOutcomeAgainst(), Spell::SelectImplicitCasterObjectTargets(), PetAI::SelectNextTarget(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), spell_item_sleepy_willy::SelectTarget(), spell_item_fetch_ball::SelectTarget(), Player::SendPreparedGossip(), Battlefield::SendWarningToPlayer(), WorldObject::setActive(), Unit::SetCharmedBy(), Player::SetClientControl(), Unit::SetFaction(), Unit::SetHealth(), Unit::SetInCombatState(), Unit::SetInCombatWith(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetPhaseMask(), Unit::SetPower(), Unit::setPowerType(), Unit::SpellDamageBonusDone(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::SpellHit(), boss_magus_telestra::boss_magus_telestraAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), Unit::SpellHitResult(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHitTarget(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), Player::StopCastingCharm(), Map::SummonCreature(), Unit::TauntApply(), Unit::TauntFadeOut(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TriggerWipe(), TempSummon::UnSummon(), Map::Update(), Pet::Update(), SimpleCharmedAI::UpdateAI(), Unit::UpdateCharmAI(), Player::UpdateCharmedAI(), HostileReference::updateOnlineStatus(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), Unit::UpdatePosition(), Unit::UpdateSpeed(), Unit::UpdateSplinePosition(), Player::UpdateVisibilityOf(), Player::UpdateWeaponSkill(), and Player::VehicleSpellInitialize().
ToCreature() [2/2]
Creature const* Object::ToCreature () const inline
Definition at line 184 of file Object.h.
 { if (GetTypeId() == TYPEID_UNIT) return (Creature const*)((Creature*)this); else return nullptr; }
References GetTypeId(), and TYPEID_UNIT.
ToDynObject() [1/2]
DynamicObject* Object::ToDynObject () inline
Definition at line 194 of file Object.h.
 { if (GetTypeId() == TYPEID_DYNAMICOBJECT) return reinterpret_cast<DynamicObject*>(this); else return nullptr; }
References GetTypeId(), and TYPEID_DYNAMICOBJECT.
Referenced by MotionTransport::DelayedTeleportTransport(), WorldObject::GetSightRange(), Map::Update(), StaticTransport::UpdatePassengerPositions(), and MotionTransport::UpdatePassengerPositions().
ToDynObject() [2/2]
DynamicObject const* Object::ToDynObject () const inline
Definition at line 195 of file Object.h.
 { if (GetTypeId() == TYPEID_DYNAMICOBJECT) return reinterpret_cast<DynamicObject const*>(this); else return nullptr; }
References const, GetTypeId(), and TYPEID_DYNAMICOBJECT.
ToGameObject() [1/2]
GameObject* Object::ToGameObject () inline
Definition at line 188 of file Object.h.
 { if (GetTypeId() == TYPEID_GAMEOBJECT) return reinterpret_cast<GameObject*>(this); else return nullptr; }
References GetTypeId(), and TYPEID_GAMEOBJECT.
Referenced by Map::_ScriptProcessDoor(), Player::AddQuestAndCheckCompletion(), BuildMovementUpdate(), WorldObject::CanSeeOrDetect(), MotionTransport::DelayedTeleportTransport(), Player::GetDefaultGossipMenuForSource(), SpellCastTargets::GetGOTarget(), WorldObject::GetGridActivationRange(), Player::GetQuestDialogStatus(), TempSummon::GetSummonerGameObject(), GetUpdateFieldData(), Group::GroupLoot(), gobject_commandscript::HandleGameObjectInfoCommand(), spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::HandleOpenLock(), WorldSession::HandleQuestgiverChooseRewardOpcode(), Group::NeedBeforeGreed(), SmartScript::OnInitialize(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), Player::PrepareGossipMenu(), SmartScript::ProcessAction(), BattlefieldWG::ProcessEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), Map::RemoveAllObjectsInRemoveList(), Map::ScriptsProcess(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitAreaTargets(), Spell::SelectImplicitConeTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SelectImplicitTargetObjectTargets(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), StaticTransport::UpdatePassengerPositions(), and MotionTransport::UpdatePassengerPositions().
ToGameObject() [2/2]
GameObject const* Object::ToGameObject () const inline
Definition at line 189 of file Object.h.
 { if (GetTypeId() == TYPEID_GAMEOBJECT) return (const GameObject*)((GameObject*)this); else return nullptr; }
References GetTypeId(), and TYPEID_GAMEOBJECT.
ToggleFlag()
void Object::ToggleFlag (uint16 index, uint32 flag)
Definition at line 868 of file Object.cpp.
 {
     if (HasFlag(index, flag))
     {
         RemoveFlag(index, flag);
     }
     else
     {
         SetFlag(index, flag);
     }
 }
References HasFlag(), index, RemoveFlag(), and SetFlag().
Referenced by WorldSession::HandleShowingCloakOpcode(), WorldSession::HandleShowingHelmOpcode(), WorldSession::HandleTogglePvP(), Player::ToggleAFK(), and Player::ToggleDND().
ToggleFlag64()
void Object::ToggleFlag64 (uint16 index, uint64 flag)
Definition at line 961 of file Object.cpp.
 {
     if (HasFlag64(index, flag))
     {
         RemoveFlag64(index, flag);
     }
     else
     {
         SetFlag64(index, flag);
     }
 }
References HasFlag64(), index, RemoveFlag64(), and SetFlag64().
ToPlayer() [1/2]
Player* Object::ToPlayer () inline
Definition at line 181 of file Object.h.
 { if (GetTypeId() == TYPEID_PLAYER) return reinterpret_cast<Player*>(this); else return nullptr; }
References GetTypeId(), and TYPEID_PLAYER.
Referenced by ThreatMgr::_addThreat(), Aura::_ApplyForTarget(), Spell::_cast(), Unit::_CreateAuraApplication(), Unit::_EnterVehicle(), Unit::_ExitVehicle(), Map::_GetScriptPlayer(), Map::_GetScriptPlayerSourceOrTarget(), Spell::_handle_finish_phase(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Aura::_UnapplyForTarget(), Unit::_UpdateAutoRepeatSpell(), spell_rog_cheat_death::Absorb(), spell_pal_ardent_defender::Absorb(), Unit::AddGameObject(), Vehicle::AddPassenger(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Unit::AddPetAura(), Player::AddQuest(), Creature::AddToWorld(), Pet::AddToWorld(), AuraEffect::ApplySpellMod(), Unit::Attack(), TotemAI::AttackStart(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::AttackStart(), ChatHandler::BuildChatPacket(), Unit::CalcArmorReducedDamage(), Unit::CalcSpellDuration(), spell_dk_anti_magic_zone::CalculateAmount(), spell_gen_vehicle_scaling_aura::CalculateAmount(), AuraEffect::CalculateAmount(), SpellEffectInfo::CalcValue(), PetAI::CanAttack(), Spell::cancel(), Spell::CancelGlobalCooldown(), WorldObject::CanDetect(), WorldObject::CanDetectStealthOf(), Player::CanInteractWithQuestGiver(), Spell::CanOpenLock(), Map::CanReachPositionAndGetValidCoords(), WorldObject::CanSeeOrDetect(), SpellMgr::CanSpellTriggerProcOnEvent(), Pet::CastPetAuras(), spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript::CheckCast(), spell_hun_tame_beast::CheckCast(), Spell::CheckCast(), SmartAI::CheckConditions(), VehicleAI::CheckConditions(), Spell::CheckEffectTarget(), spell_brewfest_relay_race_force_cast::spell_brewfest_relay_race_force_cast_SpellScript::CheckItem(), Spell::CheckItems(), modify_commandscript::CheckModifySpeed(), Spell::CheckPower(), spell_dk_dancing_rune_weapon::CheckProc(), spell_gen_proc_once_per_cast::CheckProc(), Spell::CheckRange(), spell_dk_raise_dead::CheckReagents(), spell_item_demon_broiled_surprise::CheckRequirement(), Spell::CheckRuneCost(), spell_q11117_catch_the_wild_wolpertinger::spell_q11117_catch_the_wild_wolpertinger_SpellScript::CheckTarget(), SpellInfo::CheckTarget(), Unit::ClearAllReactives(), Unit::ClearInCombat(), Unit::CombatStart(), Unit::CombatStartOnCast(), Unit::CombatStop(), Unit::CreateTamedPetFrom(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::DamageTaken(), npc_bartleby::npc_bartlebyAI::DamageTaken(), Unit::DealDamage(), Unit::DealHeal(), Unit::DealMeleeDamage(), Spell::Delayed(), Spell::DelayedChannel(), MotionTransport::DelayedTeleportTransport(), Unit::Dismount(), Spell::DoAllEffectOnTarget(), spell_hun_masters_call::DoCheckCast(), Spell::DoCreateItem(), Spell::DoSpellHitOnUnit(), ScriptedAI::DoTeleportPlayer(), Spell::EffectActivateObject(), Spell::EffectActivateRune(), Spell::EffectActivateSpec(), Spell::EffectAddComboPoints(), Spell::EffectAddHonor(), Spell::EffectApplyGlyph(), Spell::EffectBind(), Spell::EffectBlock(), Spell::EffectCastButtons(), Spell::EffectCharge(), Spell::EffectChargeDest(), Spell::EffectCreateItem2(), Spell::EffectCreateRandomItem(), Spell::EffectCreateTamedPet(), Spell::EffectDiscoverTaxi(), Spell::EffectDisEnchant(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectDurabilityDamage(), Spell::EffectDurabilityDamagePCT(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectEnvironmentalDMG(), Spell::EffectFeedPet(), Spell::EffectHeal(), Spell::EffectInebriate(), Spell::EffectInstaKill(), Spell::EffectJump(), Spell::EffectJumpDest(), Spell::EffectKillCredit(), Spell::EffectKillCreditPersonal(), Spell::EffectKnockBack(), Spell::EffectLeapBack(), Spell::EffectLearnPetSpell(), Spell::EffectLearnSkill(), Spell::EffectLearnSpell(), Spell::EffectMilling(), Spell::EffectOpenLock(), Spell::EffectParry(), Spell::EffectPickPocket(), Spell::EffectPlayMusic(), Spell::EffectPlaySound(), Spell::EffectProficiency(), Spell::EffectProspecting(), Spell::EffectPullTowards(), Spell::EffectQuestClear(), Spell::EffectQuestComplete(), Spell::EffectQuestFail(), Spell::EffectQuestStart(), Spell::EffectRechargeManaGem(), Spell::EffectReputation(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectResurrectPet(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSelfResurrect(), Spell::EffectSendTaxi(), Spell::EffectSkinning(), Spell::EffectSkinPlayerCorpse(), Spell::EffectSpecCount(), Spell::EffectStuck(), Spell::EffectSummonChangeItem(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Spell::EffectTameCreature(), Spell::EffectTeleportUnits(), Spell::EffectTitanGrip(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), Spell::EffectUnlearnSpecialization(), Spell::EffectUntrainTalents(), Spell::EffectWeaponDmg(), SmartAI::EndPath(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), npc_torturer_lecraft::npc_torturer_lecraftAI::EnterCombat(), Unit::EnterVehicle(), Unit::ExecuteDelayedUnitRelocationEvent(), Unit::ExitVehicle(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::FilterTargets(), Spell::finish(), Unit::GetAffectingPlayer(), Unit::GetAPMultiplier(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Unit::GetCombatRatingReduction(), Unit::GetDefenseSkillValue(), Unit::GetFactionTemplateEntry(), WorldObject::GetGridActivationRange(), SpellScript::GetHitPlayer(), Unit::GetNextRandomRaidMemberOrPet(), Unit::GetPartyMembers(), WorldObject::GetSightRange(), Unit::GetSpellModOwner(), SmartScript::GetTargets(), Unit::GetUnitBlockChance(), Unit::GetUnitDodgeChance(), Unit::GetUnitMissChance(), Unit::GetUnitParryChance(), Unit::GetWeaponSkillValue(), go_soulwell::go_soulwellAI::GossipHello(), spell_dru_berserk::HandleAfterCast(), spell_brewfest_fill_keg::spell_brewfest_fill_keg_SpellScript::HandleAfterHit(), spell_brewfest_unfill_keg::spell_brewfest_unfill_keg_SpellScript::HandleAfterHit(), spell_rog_deadly_poison::HandleAfterHit(), Pet::HandleAsynchLoadFailed(), Pet::HandleAsynchLoadSucceed(), AuraEffect::HandleAuraConvertRune(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraFeatherFall(), AuraEffect::HandleAuraHover(), AuraEffect::HandleAuraModAttackPowerOfArmor(), AuraEffect::HandleAuraModBlockPercent(), AuraEffect::HandleAuraModCritPct(), AuraEffect::HandleAuraModDecreaseSpeed(), AuraEffect::HandleAuraModDisarm(), AuraEffect::HandleAuraModDodgePercent(), AuraEffect::HandleAuraModEffectImmunity(), AuraEffect::HandleAuraModExpertise(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleAuraModIncreaseFlightSpeed(), AuraEffect::HandleAuraModIncreaseSpeed(), AuraEffect::HandleAuraModIncreaseSwimSpeed(), AuraEffect::HandleAuraModParryPercent(), AuraEffect::HandleAuraModPetTalentsPoints(), AuraEffect::HandleAuraModRangedAttackPowerOfStatPercent(), AuraEffect::HandleAuraModShapeshift(), AuraEffect::HandleAuraModSkill(), AuraEffect::HandleAuraModUseNormalSpeed(), AuraEffect::HandleAuraModWeaponCritPercent(), AuraEffect::HandleAuraOpenStable(), AuraEffect::HandleAuraOverrideSpells(), Unit::HandleAuraProc(), Unit::HandleAuraRaidProcFromChargeWithValue(), AuraEffect::HandleAuraRetainComboPoints(), AuraEffect::HandleAuraSetVehicle(), Aura::HandleAuraSpecificMods(), AuraEffect::HandleAuraTransform(), AuraEffect::HandleAuraWaterWalk(), AuraEffect::HandleBindSight(), WorldSession::HandleCastSpellOpcode(), AuraEffect::HandleChannelDeathItem(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), misc_commandscript::HandleDieCommand(), spell_gen_oracle_wolvar_reputation::HandleDummy(), spell_pos_slave_trigger_closest::spell_pos_slave_trigger_closestSpellScript::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_gen_spirit_healer_res::HandleDummy(), spell_hun_masters_call::HandleDummy(), spell_hun_readiness::HandleDummy(), spell_hun_scatter_shot::HandleDummy(), spell_item_brewfest_mount_transformation::HandleDummy(), spell_item_teach_language::HandleDummy(), spell_item_rocket_boots::HandleDummy(), spell_item_chicken_cover::HandleDummy(), spell_item_refocus::HandleDummy(), spell_mage_cold_snap::HandleDummy(), spell_mage_summon_water_elemental::HandleDummy(), spell_q10714_on_spirits_wings::HandleDummy(), spell_q6124_6129_apply_salve::HandleDummy(), spell_q12937_relief_for_the_fallen::HandleDummy(), spell_q12659_ahunaes_knife::HandleDummy(), spell_q9874_liquid_fire::HandleDummy(), spell_q9452_cast_net::HandleDummy(), spell_rog_preparation::HandleDummy(), spell_warl_life_tap::HandleDummy(), Unit::HandleDummyAuraProc(), spell_q11117_catch_the_wild_wolpertinger::spell_q11117_catch_the_wild_wolpertinger_SpellScript::HandleDummyEffect(), spell_image_of_drakuru_reagent_check::HandleDummyEffect(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_dk_master_of_ghouls::HandleEffectApply(), spell_rog_killing_spree::spell_rog_killing_spree_AuraScript::HandleEffectPeriodic(), spell_rog_prey_on_the_weak::HandleEffectPeriodic(), spell_brewfest_main_ram_buff::spell_brewfest_main_ram_buff_AuraScript::HandleEffectPeriodic(), spell_dk_master_of_ghouls::HandleEffectRemove(), AuraEffect::HandleFarSight(), AuraEffect::HandleFeignDeath(), spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::HandleFinish(), spell_the_flag_of_ownership::HandleFinish(), spell_q12014_steady_as_a_rock::HandleFinish(), AuraEffect::HandleForceReaction(), honor_commandscript::HandleHonorAddKillCommand(), spell_item_massive_seaforium_charge::HandleItemRemove(), OutdoorPvPHP::HandleKillImpl(), OutdoorPvPNA::HandleKillImpl(), OutdoorPvPZM::HandleKillImpl(), spell_q12690_burst_at_the_seams::HandleKnockBack(), WorldSession::HandleLoadPetFromDBSecondCallback(), WorldSession::HandleMirrorImageDataRequest(), AuraEffect::HandleModDamageDone(), AuraEffect::HandleModDamagePercentDone(), AuraEffect::HandleModHealingDone(), AuraEffect::HandleModHitChance(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyPhaseCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifyTalentCommand(), AuraEffect::HandleModManaRegen(), AuraEffect::HandleModPossessPet(), AuraEffect::HandleModPowerRegen(), AuraEffect::HandleModRating(), AuraEffect::HandleModRatingFromStat(), AuraEffect::HandleModSpellCritChance(), AuraEffect::HandleModSpellCritChanceShool(), AuraEffect::HandleModSpellDamagePercentFromAttackPower(), AuraEffect::HandleModSpellDamagePercentFromStat(), AuraEffect::HandleModSpellHealingPercentFromAttackPower(), AuraEffect::HandleModSpellHealingPercentFromStat(), AuraEffect::HandleModSpellHitChance(), AuraEffect::HandleModStealth(), modify_commandscript::HandleMorphResetCommand(), modify_commandscript::HandleMorphTargetCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), Unit::HandleOverrideClassScriptAuraProc(), AuraEffect::HandlePeriodicDummyAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetRename(), AuraEffect::HandlePhase(), WorldSession::HandlePlayerLoginOpcode(), Unit::HandleProcTriggerSpell(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), spell_dk_raise_dead::HandleRaiseDead(), reset_commandscript::HandleResetTalentsCommand(), spell_pvp_trinket_wotf_shared_cd::HandleScript(), spell_item_create_heart_candy::spell_item_create_heart_candy_SpellScript::HandleScript(), spell_gen_pet_summoned::HandleScript(), spell_gen_divine_storm_cd_reset::HandleScript(), spell_gen_profession_research::HandleScript(), spell_item_book_of_glyph_mastery::HandleScript(), spell_q12274_a_fall_from_grace_costume::HandleScript(), spell_q12805_lifeblood_dummy::HandleScript(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript2(), spell_item_feast::HandleScriptEffect(), spell_hun_chimera_shot::HandleScriptEffect(), AuraEffect::HandleShapeshiftBoosts(), AuraEffect::HandleShieldBlockValue(), AuraEffect::HandleSpiritOfRedemption(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets(), WorldSession::HandleTeleportTimeout(), spell_warl_drain_soul::HandleTick(), AuraEffect::HandleWaterBreathing(), Spell::HasGlobalCooldown(), Unit::haveOffhandWeapon(), spell_q11065_wrangle_some_aether_rays_aura::if(), spell_q11322_q11317_the_cleansing::if(), spell_gen_have_item_auras::if(), Spell::InitExplicitTargets(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), TempSummon::InitStats(), Guardian::InitStatsForLevel(), Pet::InitTalentForLevel(), Unit::InterruptSpell(), Player::IsAlwaysDetectableFor(), Unit::IsAlwaysDetectableFor(), Unit::IsAlwaysVisibleFor(), DisableMgr::IsDisabledFor(), SpellClickInfo::IsFitToRequirements(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Aura::IsProcTriggeredOnEvent(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), npc_kservant::npc_kservantAI::IsSummonedBy(), npc_venomhide_hatchling::npc_venomhide_hatchlingAI::IsSummonedBy(), Unit::isTargetableForAttack(), Unit::IsTriggeredAtSpellProcEvent(), ThreatCalcHelper::isValidProcess(), Unit::JumpTo(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), npc_nerubar_victim::npc_nerubar_victimAI::JustDied(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::JustDied(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::JustDied(), Unit::Kill(), boss_archimonde::boss_archimondeAI::KilledUnit(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::KilledUnit(), Unit::KnockbackFrom(), spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript::Load(), spell_rog_cheat_death::Load(), Unit::MagicSpellHitResult(), Condition::Meets(), AchievementCriteriaData::Meets(), Unit::MeleeDamageBonusDone(), Unit::MeleeSpellHitResult(), Unit::Mount(), MotionMaster::MoveFall(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight(), npc_scarlet_guard::npc_scarlet_guardAI::MoveInLineOfSight(), npc_mograine::npc_mograineAI::MoveInLineOfSight(), npc_fairbanks::npc_fairbanksAI::MoveInLineOfSight(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_brewfest_keg_thrower::npc_brewfest_keg_throwerAI::MoveInLineOfSight(), npc_brewfest_keg_reciver::npc_brewfest_keg_reciverAI::MoveInLineOfSight(), npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI::MoveInLineOfSight(), npc_winterfin_playmate::npc_winterfin_playmateAI::MoveInLineOfSight(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::MoveInLineOfSight(), npc_the_biggest_tree::npc_the_biggest_treeAI::MoveInLineOfSight(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::MoveInLineOfSight(), npc_elder_kekek::npc_elder_kekekAI::MoveInLineOfSight(), npc_the_etymidian::npc_the_etymidianAI::MoveInLineOfSight(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::MoveInLineOfSight(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::MoveInLineOfSight(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), npc_twiggy_flathead::npc_twiggy_flatheadAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_guardian_pavilion::npc_guardian_pavilionAI::MoveInLineOfSight(), npc_jungle_punch_target::npc_jungle_punch_targetAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI::MoveInLineOfSight(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::MovementInform(), MotionMaster::MoveTaxiFlight(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget(), npc_pet_mage_mirror_image::MySelectNextTarget(), Unit::NearTeleportTo(), modify_commandscript::NotifyModification(), spell_gen_clone_weapon_aura::OnApply(), achievement_sickly_gazelle::OnCheck(), achievement_wg_didnt_stand_a_chance::OnCheck(), achievement_save_the_day::OnCheck(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), spell_item_ashbringer::OnDummyEffect(), spell_mage_glyph_of_eternal_water::OnRemove(), Acore::MostHPMissingGroupInRange::operator()(), UnboundPlagueTargetSelector::operator()(), UnchainedMagicTargetSelector::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::PassengerBoarded(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::PassengerBoarded(), NPCStaveQuestAI::PlayerEligibleForReward(), Spell::prepare(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_item_titanium_seal_of_dalaran::PrepareSpellScript(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessAction(), NPCStaveQuestAI::QuestIncomplete(), npc_pet_gen_mojo::ReceiveEmote(), Unit::RemoveAllControlled(), DynamicObject::RemoveCasterViewpoint(), Unit::RemoveCharmedBy(), Unit::RemoveGameObject(), Vehicle::RemovePassenger(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), Unit::RemovePetAura(), npc_pet_gen_argent_pony_bridle::Reset(), Pet::resetTalents(), Pet::resetTalentsForAllPetsOf(), Unit::RestoreFaction(), Player::RewardHonor(), Unit::RollMeleeOutcomeAgainst(), Pet::SavePetToDB(), Map::ScriptsProcess(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitCasterDestTargets(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::SelectRandomPlayer(), npc_minigob_manabonk::npc_minigob_manabonkAI::SelectTargetInDalaran(), Unit::SendAttackStateUpdate(), Spell::SendCastResult(), Spell::SendChannelStart(), CreatureTextMgr::SendChatPacket(), spell_igb_overheat::spell_igb_overheat_AuraScript::SendClientControl(), npc_aquementas::npc_aquementasAI::SendItem(), Spell::SendLoot(), CreatureTextMgr::SendNonChatPacket(), Unit::SendPeriodicAuraLog(), Unit::SendPetActionFeedback(), Unit::SendPetAIReaction(), Spell::SendPetCastResult(), Unit::SendPetTalk(), WorldObject::SendPlayMusic(), Spell::SendSpellCooldown(), Spell::SendSpellGo(), Unit::SendSpellNonMeleeReflectLog(), Spell::SendSpellStart(), Unit::SendTameFailure(), Creature::SetCanFly(), DynamicObject::SetCasterViewpoint(), Unit::SetCharm(), Unit::SetCharmedBy(), Unit::SetConfused(), Unit::SetControlled(), spell_item_recall::SetDest(), Creature::SetDisableGravity(), Pet::SetDisplayId(), Unit::SetFeared(), Creature::SetFeatherFall(), Unit::SetHealth(), Creature::SetHover(), Unit::SetInCombatState(), Unit::SetInCombatWith(), Unit::SetLevel(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetMinion(), Player::SetMover(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), Unit::SetPhaseMask(), Unit::SetPower(), Unit::setPowerType(), Unit::SetRooted(), Unit::SetSpeed(), Unit::SetStandState(), Unit::SetStunned(), Creature::SetWaterWalking(), Spell::Spell(), Unit::SpellBaseDamageBonusDone(), Unit::SpellBaseHealingBonusDone(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), npc_yenniku::npc_yennikuAI::SpellHit(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::SpellHit(), npc_torturer_lecraft::npc_torturer_lecraftAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::SpellHit(), npc_iron_watcher::npc_iron_watcherAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_garments_of_quests::npc_garments_of_questsAI::SpellHit(), npc_greengill_slave::npc_greengill_slaveAI::SpellHit(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SpellHit(), npc_jungle_punch_target::npc_jungle_punch_targetAI::SpellHit(), npc_spitelashes::npc_spitelashesAI::SpellHit(), npc_beryl_sorcerer::npc_beryl_sorcererAI::SpellHit(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::SpellHit(), boss_ick::boss_ickAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), boss_festergut::boss_festergutAI::SpellHitTarget(), boss_rotface::boss_rotfaceAI::SpellHitTarget(), Unit::SpellPctDamageModsDone(), Unit::StopAttackFaction(), Spell::SummonGuardian(), Spell::TakeAmmo(), Spell::TakeCastItem(), Spell::TakePower(), Spell::TakeReagents(), Spell::TakeRunePower(), Unit::TauntApply(), Unit::TauntFadeOut(), Spell::TriggerGlobalCooldown(), Pet::TryLoadFromDB(), SafeUnitPointer::UnitDeleted(), Totem::UnSummon(), GameObject::Update(), Unit::Update(), SpellCastTargets::Update(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), npc_yenniku::npc_yennikuAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), PetAI::UpdateAI(), PetAI::UpdateAllies(), Unit::UpdateAuraForGroup(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), AuraEffect::UpdatePeriodic(), Spell::UpdatePointers(), Unit::UpdatePosition(), Unit::UpdateReactives(), GameObject::Use(), Acore::VisibleChangesNotifier::Visit(), and Spell::WriteAmmoToPacket().
ToPlayer() [2/2]
Player const* Object::ToPlayer () const inline
Definition at line 182 of file Object.h.
 { if (GetTypeId() == TYPEID_PLAYER) return (Player const*)((Player*)this); else return nullptr; }
References GetTypeId(), and TYPEID_PLAYER.
ToUnit() [1/2]
Unit* Object::ToUnit () inline
Definition at line 186 of file Object.h.
 { if (GetTypeId() == TYPEID_UNIT || GetTypeId() == TYPEID_PLAYER) return reinterpret_cast<Unit*>(this); else return nullptr; }
References GetTypeId(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by Map::_GetScriptUnit(), MotionTransport::AddPassenger(), WorldObject::AddToNotify(), BuildMovementUpdate(), PathGenerator::BuildPolyPath(), PathGenerator::CalculatePath(), WorldObject::CanDetect(), WorldObject::CanDetectInvisibilityOf(), WorldObject::CanDetectStealthOf(), WorldObject::CanNeverSee(), Map::CanReachPositionAndGetValidCoords(), WorldObject::CanSeeOrDetect(), Aura::CanStackWith(), Map::CheckCollisionAndGetValidCoords(), SpellInfo::CheckExplicitTarget(), SpellInfo::CheckTarget(), Aura::Create(), Unit::ExecuteDelayedUnitRelocationEvent(), spell_dk_death_pact::FilterTargets(), spell_dk_wandering_plague::FilterTargets(), spell_dru_t10_restoration_4p_bonus::FilterTargets(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::FilterTargets(), WorldObject::GetClosePoint(), Creature::getLevelForTarget(), WorldObject::GetNearPoint(), WorldObject::GetNearPoint2D(), WorldObject::GetSightRange(), TempSummon::GetSummonerUnit(), SpellCastTargets::GetUnitTarget(), GetUpdateFieldData(), spell_hun_volley_trigger::HandleFinish(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), ArenaSpectator::HandleSpectatorWatchCommand(), GameObject::IsAlwaysVisibleFor(), Condition::Meets(), spell_load_into_catapult::spell_load_into_catapult_AuraScript::OnApply(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnPeriodic(), spell_load_into_catapult::spell_load_into_catapult_AuraScript::OnRemove(), CorpseExplosionCheck::operator()(), RaiseDeadCheck::operator()(), MarkOfNatureTargetSelector::operator()(), AliveCheck::operator()(), Acore::WorldObjectSpellTargetCheck::operator()(), EarthenPowerTargetSelector::operator()(), FlashFreezeCheck::operator()(), SpectralBlastCheck::operator()(), VehicleCheck::operator()(), HasInLineCheck::operator()(), PlayerOrPetCheck::operator()(), Acore::PowerPctOrderPred::operator()(), Acore::HealthPctOrderPred::operator()(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), MotionTransport::RemovePassenger(), Map::ScriptsProcess(), Spell::SearchChainTargets(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitAreaTargets(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitCasterObjectTargets(), Spell::SelectImplicitChainTargets(), Spell::SelectImplicitChannelTargets(), Spell::SelectImplicitConeTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SelectImplicitTargetObjectTargets(), Spell::SelectImplicitTrajTargets(), WorldObject::SetPositionDataUpdate(), WorldObject::SummonGameObject(), Aura::TryRefreshStackOrCreate(), WorldObject::UpdateAllowedPositionZ(), PathGenerator::UpdateFilter(), StaticTransport::UpdatePassengerPositions(), and MotionTransport::UpdatePassengerPositions().
ToUnit() [2/2]
Unit const* Object::ToUnit () const inline
Definition at line 187 of file Object.h.
 { if (GetTypeId() == TYPEID_UNIT || GetTypeId() == TYPEID_PLAYER) return (const Unit*)((Unit*)this); else return nullptr; }
References GetTypeId(), TYPEID_PLAYER, and TYPEID_UNIT.
UpdateUInt32Value()
void Object::UpdateUInt32Value (uint16 index, uint32 value)
Definition at line 654 of file Object.cpp.
 {
     ASSERT(index < m_valuesCount || PrintIndexError(index, true));
     m_uint32Values[index] = value;
     _changesMask.SetBit(index);
 }
References _changesMask, ASSERT, index, m_uint32Values, m_valuesCount, PrintIndexError(), and UpdateMask::SetBit().
Referenced by Player::Regenerate().
Member Data Documentation
union { ... }
_changesMask
UpdateMask Object::_changesMask protected
Definition at line 224 of file Object.h.
Referenced by _InitValues(), _LoadIntoDataField(), AddGuidValue(), BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), ClearUpdateMask(), ForceValuesUpdateAtIndex(), RemoveByteFlag(), RemoveFlag(), RemoveGuidValue(), SetByteFlag(), SetFlag(), SetFloatValue(), SetGuidValue(), SetInt32Value(), Unit::SetLevel(), SetUInt16Value(), SetUInt32Value(), SetUInt64Value(), and UpdateUInt32Value().
_fieldNotifyFlags
uint16 Object::_fieldNotifyFlags protected
Definition at line 228 of file Object.h.
Referenced by BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), Object(), RemoveFieldNotifyFlag(), and SetFieldNotifyFlag().
CustomData
DataMap Object::CustomData
Definition at line 197 of file Object.h.
m_floatValues
float* Object::m_floatValues
Definition at line 221 of file Object.h.
Referenced by Unit::BuildValuesUpdate(), Unit::GetCombatReach(), GetFloatValue(), Unit::GetMeleeReach(), WorldObject::GetObjectSize(), and SetFloatValue().
m_int32Values
int32* Object::m_int32Values
Definition at line 219 of file Object.h.
Referenced by GetInt32Value(), and SetInt32Value().
m_inWorld
bool Object::m_inWorld private
Definition at line 237 of file Object.h.
Referenced by AddToObjectUpdateIfNeeded(), AddToWorld(), IsInWorld(), Object(), and RemoveFromWorld().
m_objectType
uint16 Object::m_objectType protected
Definition at line 212 of file Object.h.
Referenced by _Create(), Bag::Bag(), Corpse::Corpse(), DynamicObject::DynamicObject(), GameObject::GameObject(), isType(), Item::Item(), Object(), Player::Player(), PrintIndexError(), and Unit::Unit().
m_objectTypeId
TypeID Object::m_objectTypeId protected
Definition at line 214 of file Object.h.
Referenced by Bag::Bag(), BuildCreateUpdateBlockForPlayer(), Corpse::Corpse(), DynamicObject::DynamicObject(), GameObject::GameObject(), GetTypeId(), Item::Item(), Object(), Player::Player(), and Unit::Unit().
m_objectUpdated
bool Object::m_objectUpdated protected
Definition at line 234 of file Object.h.
Referenced by _InitValues(), AddToObjectUpdateIfNeeded(), AddToWorld(), ClearUpdateMask(), Object(), and ~Object().
m_PackGUID
PackedGuid Object::m_PackGUID private
Definition at line 239 of file Object.h.
Referenced by _Create(), and GetPackGUID().
m_uint32Values
uint32* Object::m_uint32Values
Definition at line 220 of file Object.h.
Referenced by _Create(), _InitValues(), Player::_LoadArenaTeamInfo(), _LoadIntoDataField(), AddGuidValue(), WorldObject::AddObjectToRemoveList(), AddToWorld(), BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), GameObject::CleanupsBeforeDelete(), GetByteValue(), GetGuidValue(), GetUInt16Value(), GetUInt32Value(), GetUInt64Value(), HasByteFlag(), HasFlag(), Object(), RemoveByteFlag(), RemoveFlag(), Player::RemoveFromWorld(), RemoveGuidValue(), SetByteFlag(), SetFlag(), SetGuidValue(), SetUInt16Value(), SetUInt32Value(), SetUInt64Value(), UpdateUInt32Value(), and ~Object().
m_updateFlag
uint16 Object::m_updateFlag protected
Definition at line 215 of file Object.h.
Referenced by BuildCreateUpdateBlockForPlayer(), Corpse::Corpse(), Unit::CreateVehicleKit(), DynamicObject::DynamicObject(), GameObject::GameObject(), Item::Item(), MotionTransport::MotionTransport(), Unit::RemoveVehicleKit(), StaticTransport::StaticTransport(), and Unit::Unit().
m_valuesCount
uint16 Object::m_valuesCount protected
Definition at line 226 of file Object.h.
Referenced by _InitValues(), AddGuidValue(), Bag::Bag(), BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), Corpse::Corpse(), Creature::Creature(), DynamicObject::DynamicObject(), GameObject::GameObject(), GetByteValue(), GetFloatValue(), GetGuidValue(), GetInt32Value(), WorldObject::GetObjectSize(), GetUInt16Value(), GetUInt32Value(), GetUInt64Value(), GetValuesCount(), HasByteFlag(), HasFlag(), HasFlag64(), Item::Item(), Object(), Player::Player(), PrintIndexError(), RemoveByteFlag(), RemoveFlag(), RemoveGuidValue(), SetByteFlag(), SetByteValue(), SetFlag(), SetFloatValue(), SetGuidValue(), SetInt32Value(), SetUInt16Value(), SetUInt32Value(), SetUInt64Value(), and UpdateUInt32Value().
The documentation for this class was generated from the following files:
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Object/Object.cpp