Azerotcore-wotlk: npc_love_in_air_hummel Class Reference
npc_love_in_air_hummel Class Reference
Classes
struct npc_love_in_air_hummelAI
Public Member Functions
npc_love_in_air_hummel ()
CreatureAI * GetAI (Creature *creature) const override
bool OnQuestReward (Player *, Creature *creature, const Quest *_Quest, uint32) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 333 of file love_in_air.cpp.
Constructor & Destructor Documentation
npc_love_in_air_hummel()
npc_love_in_air_hummel::npc_love_in_air_hummel () inline
Definition at line 336 of file love_in_air.cpp.
 : CreatureScript("npc_love_in_air_hummel") { }
Member Function Documentation
GetAI()
CreatureAI* npc_love_in_air_hummel::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 463 of file love_in_air.cpp.
     {
         return new npc_love_in_air_hummelAI(creature);
     }
OnQuestReward()
bool npc_love_in_air_hummel::OnQuestReward (Player * , Creature * creature, const Quest * _Quest, uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 468 of file love_in_air.cpp.
     {
         if (_Quest->GetQuestId() == QUEST_YOUVE_BEEN_SERVED)
             creature->AI()->DoAction(ACTION_START_EVENT);
         return true;
     }
References ACTION_START_EVENT, Creature::AI(), UnitAI::DoAction(), Quest::GetQuestId(), and QUEST_YOUVE_BEEN_SERVED.
The documentation for this class was generated from the following file:
src/server/scripts/Events/love_in_air.cpp