Azerotcore-wotlk: detail::dragonbox Namespace Reference
detail::dragonbox Namespace Reference
Classes
struct divtest_table_entry
struct cache_accessor
struct cache_accessor< float >
struct cache_accessor< double >
Functions
uint128_wrapper umul128 (uint64_t x, uint64_t y) FMT_NOEXCEPT
uint64_t umul128_upper64 (uint64_t x, uint64_t y) FMT_NOEXCEPT
uint64_t umul192_upper64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint32_t umul96_upper32 (uint32_t x, uint64_t y) FMT_NOEXCEPT
uint64_t umul192_middle64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint64_t umul96_lower64 (uint32_t x, uint64_t y) FMT_NOEXCEPT
int floor_log10_pow2 (int e) FMT_NOEXCEPT
int floor_log2_pow10 (int e) FMT_NOEXCEPT
int floor_log10_pow2_minus_log10_4_over_3 (int e) FMT_NOEXCEPT
bool divisible_by_power_of_2 (uint32_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_2 (uint64_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_5 (uint32_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_5 (uint64_t x, int exp) FMT_NOEXCEPT
template<int N>
bool check_divisibility_and_divide_by_pow5 (uint32_t &n) FMT_NOEXCEPT
template<int N>
uint32_t small_division_by_pow10 (uint32_t n) FMT_NOEXCEPT
uint32_t divide_by_10_to_kappa_plus_1 (uint32_t n) FMT_NOEXCEPT
uint64_t divide_by_10_to_kappa_plus_1 (uint64_t n) FMT_NOEXCEPT
template<class T >
bool is_left_endpoint_integer_shorter_interval (int exponent) FMT_NOEXCEPT
template<class T >
bool is_endpoint_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
template<class T >
bool is_center_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
FMT_INLINE int remove_trailing_zeros (uint32_t &n) FMT_NOEXCEPT
FMT_INLINE int remove_trailing_zeros (uint64_t &n) FMT_NOEXCEPT
template<class T >
FMT_INLINE decimal_fp< T > shorter_interval_case (int exponent) FMT_NOEXCEPT
template<typename T >
decimal_fp< T > to_decimal (T x) FMT_NOEXCEPT
Function Documentation
check_divisibility_and_divide_by_pow5()
template<int N> bool detail::dragonbox::check_divisibility_and_divide_by_pow5 (uint32_t & n)
Definition at line 998 of file format-inl.h.
{
   static constexpr struct {
     uint32_t magic_number;
     int bits_for_comparison;
     uint32_t threshold;
     int shift_amount;
   } infos[] = {{0xcccd, 16, 0x3333, 18}, {0xa429, 8, 0x0a, 20}};
   constexpr auto info = infos[N - 1];
   n *= info.magic_number;
   const uint32_t comparison_mask = (1u << info.bits_for_comparison) - 1;
   bool result = (n & comparison_mask) <= info.threshold;
   n >>= info.shift_amount;
   return result;
 }
Referenced by to_decimal().
divide_by_10_to_kappa_plus_1() [1/2]
uint32_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint32_t n) inline
Definition at line 1027 of file format-inl.h.
{
   return n / float_info<float>::big_divisor;
 }
Referenced by to_decimal().
divide_by_10_to_kappa_plus_1() [2/2]
uint64_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint64_t n) inline
Definition at line 1031 of file format-inl.h.
{
   return umul128_upper64(n, 0x83126e978d4fdf3c) >> 9;
 }
References umul128_upper64().
divisible_by_power_of_2() [1/2]
bool detail::dragonbox::divisible_by_power_of_2 (uint32_t x, int exp) inline
Definition at line 927 of file format-inl.h.
{
   FMT_ASSERT(exp >= 1, "");
   FMT_ASSERT(x != 0, "");
 #ifdef FMT_BUILTIN_CTZ
   return FMT_BUILTIN_CTZ(x) >= exp;
 #else
   return exp < num_bits<uint32_t>() && x == ((x >> exp) << exp);
 #endif
 }
References FMT_ASSERT, and G3D::x.
Referenced by is_center_integer().
divisible_by_power_of_2() [2/2]
bool detail::dragonbox::divisible_by_power_of_2 (uint64_t x, int exp) inline
Definition at line 936 of file format-inl.h.
{
   FMT_ASSERT(exp >= 1, "");
   FMT_ASSERT(x != 0, "");
 #ifdef FMT_BUILTIN_CTZLL
   return FMT_BUILTIN_CTZLL(x) >= exp;
 #else
   return exp < num_bits<uint64_t>() && x == ((x >> exp) << exp);
 #endif
 }
References FMT_ASSERT, and G3D::x.
divisible_by_power_of_5() [1/2]
bool detail::dragonbox::divisible_by_power_of_5 (uint32_t x, int exp) inline
Definition at line 953 of file format-inl.h.
{
   FMT_ASSERT(exp <= 10, "too large exponent");
   static constexpr const divtest_table_entry<uint32_t> divtest_table[] = {
       {0x00000001, 0xffffffff}, {0xcccccccd, 0x33333333},
       {0xc28f5c29, 0x0a3d70a3}, {0x26e978d5, 0x020c49ba},
       {0x3afb7e91, 0x0068db8b}, {0x0bcbe61d, 0x0014f8b5},
       {0x68c26139, 0x000431bd}, {0xae8d46a5, 0x0000d6bf},
       {0x22e90e21, 0x00002af3}, {0x3a2e9c6d, 0x00000897},
       {0x3ed61f49, 0x000001b7}};
   return x * divtest_table[exp].mod_inv <= divtest_table[exp].max_quotient;
 }
References FMT_ASSERT, and G3D::x.
Referenced by is_center_integer(), and is_endpoint_integer().
divisible_by_power_of_5() [2/2]
bool detail::dragonbox::divisible_by_power_of_5 (uint64_t x, int exp) inline
Definition at line 964 of file format-inl.h.
{
   FMT_ASSERT(exp <= 23, "too large exponent");
   static constexpr const divtest_table_entry<uint64_t> divtest_table[] = {
       {0x0000000000000001, 0xffffffffffffffff},
       {0xcccccccccccccccd, 0x3333333333333333},
       {0x8f5c28f5c28f5c29, 0x0a3d70a3d70a3d70},
       {0x1cac083126e978d5, 0x020c49ba5e353f7c},
       {0xd288ce703afb7e91, 0x0068db8bac710cb2},
       {0x5d4e8fb00bcbe61d, 0x0014f8b588e368f0},
       {0x790fb65668c26139, 0x000431bde82d7b63},
       {0xe5032477ae8d46a5, 0x0000d6bf94d5e57a},
       {0xc767074b22e90e21, 0x00002af31dc46118},
       {0x8e47ce423a2e9c6d, 0x0000089705f4136b},
       {0x4fa7f60d3ed61f49, 0x000001b7cdfd9d7b},
       {0x0fee64690c913975, 0x00000057f5ff85e5},
       {0x3662e0e1cf503eb1, 0x000000119799812d},
       {0xa47a2cf9f6433fbd, 0x0000000384b84d09},
       {0x54186f653140a659, 0x00000000b424dc35},
       {0x7738164770402145, 0x0000000024075f3d},
       {0xe4a4d1417cd9a041, 0x000000000734aca5},
       {0xc75429d9e5c5200d, 0x000000000170ef54},
       {0xc1773b91fac10669, 0x000000000049c977},
       {0x26b172506559ce15, 0x00000000000ec1e4},
       {0xd489e3a9addec2d1, 0x000000000002f394},
       {0x90e860bb892c8d5d, 0x000000000000971d},
       {0x502e79bf1b6f4f79, 0x0000000000001e39},
       {0xdcd618596be30fe5, 0x000000000000060b}};
   return x * divtest_table[exp].mod_inv <= divtest_table[exp].max_quotient;
 }
References FMT_ASSERT, and G3D::x.
floor_log10_pow2()
int detail::dragonbox::floor_log10_pow2 (int e) inline
Definition at line 897 of file format-inl.h.
{
   FMT_ASSERT(e <= 1700 && e >= -1700, "too large exponent");
   const int shift = 22;
   return (e * static_cast<int>(data::log10_2_significand >> (64 - shift))) >>
          shift;
 }
References FMT_ASSERT, and basic_data< T >::log10_2_significand.
Referenced by to_decimal().
floor_log10_pow2_minus_log10_4_over_3()
int detail::dragonbox::floor_log10_pow2_minus_log10_4_over_3 (int e) inline
Definition at line 915 of file format-inl.h.
{
   FMT_ASSERT(e <= 1700 && e >= -1700, "too large exponent");
   const uint64_t log10_4_over_3_fractional_digits = 0x1ffbfc2bbc780375;
   const int shift_amount = 22;
   return (e * static_cast<int>(data::log10_2_significand >>
                                (64 - shift_amount)) -
           static_cast<int>(log10_4_over_3_fractional_digits >>
                            (64 - shift_amount))) >>
          shift_amount;
 }
References FMT_ASSERT, and basic_data< T >::log10_2_significand.
Referenced by shorter_interval_case().
floor_log2_pow10()
int detail::dragonbox::floor_log2_pow10 (int e) inline
Definition at line 905 of file format-inl.h.
{
   FMT_ASSERT(e <= 1233 && e >= -1233, "too large exponent");
   const uint64_t log2_10_integer_part = 3;
   const uint64_t log2_10_fractional_digits = 0x5269e12f346e2bf9;
   const int shift_amount = 19;
   return (e * static_cast<int>(
                   (log2_10_integer_part << shift_amount) |
                   (log2_10_fractional_digits >> (64 - shift_amount)))) >>
          shift_amount;
 }
References FMT_ASSERT.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), shorter_interval_case(), and to_decimal().
is_center_integer()
template<class T > bool detail::dragonbox::is_center_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k)
Definition at line 1906 of file format-inl.h.
{
   // Exponent for 5 is negative.
   if (exponent > float_info<T>::divisibility_check_by_5_threshold) return false;
   if (exponent > float_info<T>::case_fc_upper_threshold)
     return divisible_by_power_of_5(two_f, minus_k);
   // Both exponents are nonnegative.
   if (exponent >= float_info<T>::case_fc_lower_threshold) return true;
   // Exponent for 2 is negative.
   return divisible_by_power_of_2(two_f, minus_k - exponent + 1);
 }
References divisible_by_power_of_2(), and divisible_by_power_of_5().
is_endpoint_integer()
template<class T > bool detail::dragonbox::is_endpoint_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k)
Definition at line 1895 of file format-inl.h.
{
   if (exponent < float_info<T>::case_fc_pm_half_lower_threshold) return false;
   // For k >= 0.
   if (exponent <= float_info<T>::case_fc_pm_half_upper_threshold) return true;
   // For k < 0.
   if (exponent > float_info<T>::divisibility_check_by_5_threshold) return false;
   return divisible_by_power_of_5(two_f, minus_k);
 }
References divisible_by_power_of_5().
is_left_endpoint_integer_shorter_interval()
template<class T > bool detail::dragonbox::is_left_endpoint_integer_shorter_interval (int exponent)
Definition at line 1887 of file format-inl.h.
{
   return exponent >=
              float_info<
                  T>::case_shorter_interval_left_endpoint_lower_threshold &&
          exponent <=
              float_info<T>::case_shorter_interval_left_endpoint_upper_threshold;
 }
remove_trailing_zeros() [1/2]
FMT_INLINE int detail::dragonbox::remove_trailing_zeros (uint32_t & n)
Definition at line 1919 of file format-inl.h.
{
 #ifdef FMT_BUILTIN_CTZ
   int t = FMT_BUILTIN_CTZ(n);
 #else
   int t = ctz(n);
 #endif
   if (t > float_info<float>::max_trailing_zeros)
     t = float_info<float>::max_trailing_zeros;
   const uint32_t mod_inv1 = 0xcccccccd;
   const uint32_t max_quotient1 = 0x33333333;
   const uint32_t mod_inv2 = 0xc28f5c29;
   const uint32_t max_quotient2 = 0x0a3d70a3;
   int s = 0;
   for (; s < t - 1; s += 2) {
     if (n * mod_inv2 > max_quotient2) break;
     n *= mod_inv2;
   }
   if (s < t && n * mod_inv1 <= max_quotient1) {
     n *= mod_inv1;
     ++s;
   }
   n >>= s;
   return s;
 }
Referenced by shorter_interval_case(), and to_decimal().
remove_trailing_zeros() [2/2]
FMT_INLINE int detail::dragonbox::remove_trailing_zeros (uint64_t & n)
Definition at line 1947 of file format-inl.h.
{
 #ifdef FMT_BUILTIN_CTZLL
   int t = FMT_BUILTIN_CTZLL(n);
 #else
   int t = ctzll(n);
 #endif
   if (t > float_info<double>::max_trailing_zeros)
     t = float_info<double>::max_trailing_zeros;
   // Divide by 10^8 and reduce to 32-bits
   // Since ret_value.significand <= (2^64 - 1) / 1000 < 10^17,
   // both of the quotient and the r should fit in 32-bits
   const uint32_t mod_inv1 = 0xcccccccd;
   const uint32_t max_quotient1 = 0x33333333;
   const uint64_t mod_inv8 = 0xc767074b22e90e21;
   const uint64_t max_quotient8 = 0x00002af31dc46118;
   // If the number is divisible by 1'0000'0000, work with the quotient
   if (t >= 8) {
     auto quotient_candidate = n * mod_inv8;
     if (quotient_candidate <= max_quotient8) {
       auto quotient = static_cast<uint32_t>(quotient_candidate >> 8);
       int s = 8;
       for (; s < t; ++s) {
         if (quotient * mod_inv1 > max_quotient1) break;
         quotient *= mod_inv1;
       }
       quotient >>= (s - 8);
       n = quotient;
       return s;
     }
   }
   // Otherwise, work with the remainder
   auto quotient = static_cast<uint32_t>(n / 100000000);
   auto remainder = static_cast<uint32_t>(n - 100000000 * quotient);
   if (t == 0 || remainder * mod_inv1 > max_quotient1) {
     return 0;
   }
   remainder *= mod_inv1;
   if (t == 1 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 1) + quotient * 10000000ull;
     return 1;
   }
   remainder *= mod_inv1;
   if (t == 2 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 2) + quotient * 1000000ull;
     return 2;
   }
   remainder *= mod_inv1;
   if (t == 3 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 3) + quotient * 100000ull;
     return 3;
   }
   remainder *= mod_inv1;
   if (t == 4 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 4) + quotient * 10000ull;
     return 4;
   }
   remainder *= mod_inv1;
   if (t == 5 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 5) + quotient * 1000ull;
     return 5;
   }
   remainder *= mod_inv1;
   if (t == 6 || remainder * mod_inv1 > max_quotient1) {
     n = (remainder >> 6) + quotient * 100ull;
     return 6;
   }
   remainder *= mod_inv1;
   n = (remainder >> 7) + quotient * 10ull;
   return 7;
 }
shorter_interval_case()
template<class T > FMT_INLINE decimal_fp<T> detail::dragonbox::shorter_interval_case (int exponent)
Definition at line 2033 of file format-inl.h.
{
   decimal_fp<T> ret_value;
   // Compute k and beta
   const int minus_k = floor_log10_pow2_minus_log10_4_over_3(exponent);
   const int beta_minus_1 = exponent + floor_log2_pow10(-minus_k);
   // Compute xi and zi
   using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
   const cache_entry_type cache = cache_accessor<T>::get_cached_power(-minus_k);
   auto xi = cache_accessor<T>::compute_left_endpoint_for_shorter_interval_case(
       cache, beta_minus_1);
   auto zi = cache_accessor<T>::compute_right_endpoint_for_shorter_interval_case(
       cache, beta_minus_1);
   // If the left endpoint is not an integer, increase it
   if (!is_left_endpoint_integer_shorter_interval<T>(exponent)) ++xi;
   // Try bigger divisor
   ret_value.significand = zi / 10;
   // If succeed, remove trailing zeros if necessary and return
   if (ret_value.significand * 10 >= xi) {
     ret_value.exponent = minus_k + 1;
     ret_value.exponent += remove_trailing_zeros(ret_value.significand);
     return ret_value;
   }
   // Otherwise, compute the round-up of y
   ret_value.significand =
       cache_accessor<T>::compute_round_up_for_shorter_interval_case(
           cache, beta_minus_1);
   ret_value.exponent = minus_k;
   // When tie occurs, choose one of them according to the rule
   if (exponent >= float_info<T>::shorter_interval_tie_lower_threshold &&
       exponent <= float_info<T>::shorter_interval_tie_upper_threshold) {
     ret_value.significand = ret_value.significand % 2 == 0
                                 ? ret_value.significand
                                 : ret_value.significand - 1;
   } else if (ret_value.significand < xi) {
     ++ret_value.significand;
   }
   return ret_value;
 }
References floor_log10_pow2_minus_log10_4_over_3(), floor_log2_pow10(), detail::get_cached_power(), and remove_trailing_zeros().
small_division_by_pow10()
template<int N> uint32_t detail::dragonbox::small_division_by_pow10 (uint32_t n)
Definition at line 1015 of file format-inl.h.
{
   static constexpr struct {
     uint32_t magic_number;
     int shift_amount;
     uint32_t divisor_times_10;
   } infos[] = {{0xcccd, 19, 100}, {0xa3d8, 22, 1000}};
   constexpr auto info = infos[N - 1];
   FMT_ASSERT(n <= info.divisor_times_10, "n is too large");
   return n * info.magic_number >> info.shift_amount;
 }
References FMT_ASSERT.
to_decimal()
template<typename T > decimal_fp<T> detail::dragonbox::to_decimal (T x)
Definition at line 2079 of file format-inl.h.
{
   // Step 1: integer promotion & Schubfach multiplier calculation.
   using carrier_uint = typename float_info<T>::carrier_uint;
   using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
   auto br = bit_cast<carrier_uint>(x);
   // Extract significand bits and exponent bits.
   const carrier_uint significand_mask =
       (static_cast<carrier_uint>(1) << float_info<T>::significand_bits) - 1;
   carrier_uint significand = (br & significand_mask);
   int exponent = static_cast<int>((br & exponent_mask<T>()) >>
                                   float_info<T>::significand_bits);
   if (exponent != 0) {  // Check if normal.
     exponent += float_info<T>::exponent_bias - float_info<T>::significand_bits;
     // Shorter interval case; proceed like Schubfach.
     if (significand == 0) return shorter_interval_case<T>(exponent);
     significand |=
         (static_cast<carrier_uint>(1) << float_info<T>::significand_bits);
   } else {
     // Subnormal case; the interval is always regular.
     if (significand == 0) return {0, 0};
     exponent = float_info<T>::min_exponent - float_info<T>::significand_bits;
   }
   const bool include_left_endpoint = (significand % 2 == 0);
   const bool include_right_endpoint = include_left_endpoint;
   // Compute k and beta.
   const int minus_k = floor_log10_pow2(exponent) - float_info<T>::kappa;
   const cache_entry_type cache = cache_accessor<T>::get_cached_power(-minus_k);
   const int beta_minus_1 = exponent + floor_log2_pow10(-minus_k);
   // Compute zi and deltai
   // 10^kappa <= deltai < 10^(kappa + 1)
   const uint32_t deltai = cache_accessor<T>::compute_delta(cache, beta_minus_1);
   const carrier_uint two_fc = significand << 1;
   const carrier_uint two_fr = two_fc | 1;
   const carrier_uint zi =
       cache_accessor<T>::compute_mul(two_fr << beta_minus_1, cache);
   // Step 2: Try larger divisor; remove trailing zeros if necessary
   // Using an upper bound on zi, we might be able to optimize the division
   // better than the compiler; we are computing zi / big_divisor here
   decimal_fp<T> ret_value;
   ret_value.significand = divide_by_10_to_kappa_plus_1(zi);
   uint32_t r = static_cast<uint32_t>(zi - float_info<T>::big_divisor *
                                               ret_value.significand);
   if (r > deltai) {
     goto small_divisor_case_label;
   } else if (r < deltai) {
     // Exclude the right endpoint if necessary
     if (r == 0 && !include_right_endpoint &&
         is_endpoint_integer<T>(two_fr, exponent, minus_k)) {
       --ret_value.significand;
       r = float_info<T>::big_divisor;
       goto small_divisor_case_label;
     }
   } else {
     // r == deltai; compare fractional parts
     // Check conditions in the order different from the paper
     // to take advantage of short-circuiting
     const carrier_uint two_fl = two_fc - 1;
     if ((!include_left_endpoint ||
          !is_endpoint_integer<T>(two_fl, exponent, minus_k)) &&
         !cache_accessor<T>::compute_mul_parity(two_fl, cache, beta_minus_1)) {
       goto small_divisor_case_label;
     }
   }
   ret_value.exponent = minus_k + float_info<T>::kappa + 1;
   // We may need to remove trailing zeros
   ret_value.exponent += remove_trailing_zeros(ret_value.significand);
   return ret_value;
   // Step 3: Find the significand with the smaller divisor
 small_divisor_case_label:
   ret_value.significand *= 10;
   ret_value.exponent = minus_k + float_info<T>::kappa;
   const uint32_t mask = (1u << float_info<T>::kappa) - 1;
   auto dist = r - (deltai / 2) + (float_info<T>::small_divisor / 2);
   // Is dist divisible by 2^kappa?
   if ((dist & mask) == 0) {
     const bool approx_y_parity =
         ((dist ^ (float_info<T>::small_divisor / 2)) & 1) != 0;
     dist >>= float_info<T>::kappa;
     // Is dist divisible by 5^kappa?
     if (check_divisibility_and_divide_by_pow5<float_info<T>::kappa>(dist)) {
       ret_value.significand += dist;
       // Check z^(f) >= epsilon^(f)
       // We have either yi == zi - epsiloni or yi == (zi - epsiloni) - 1,
       // where yi == zi - epsiloni if and only if z^(f) >= epsilon^(f)
       // Since there are only 2 possibilities, we only need to care about the
       // parity. Also, zi and r should have the same parity since the divisor
       // is an even number
       if (cache_accessor<T>::compute_mul_parity(two_fc, cache, beta_minus_1) !=
           approx_y_parity) {
         --ret_value.significand;
       } else {
         // If z^(f) >= epsilon^(f), we might have a tie
         // when z^(f) == epsilon^(f), or equivalently, when y is an integer
         if (is_center_integer<T>(two_fc, exponent, minus_k)) {
           ret_value.significand = ret_value.significand % 2 == 0
                                       ? ret_value.significand
                                       : ret_value.significand - 1;
         }
       }
     }
     // Is dist not divisible by 5^kappa?
     else {
       ret_value.significand += dist;
     }
   }
   // Is dist not divisible by 2^kappa?
   else {
     // Since we know dist is small, we might be able to optimize the division
     // better than the compiler; we are computing dist / small_divisor here
     ret_value.significand +=
         small_division_by_pow10<float_info<T>::kappa>(dist);
   }
   return ret_value;
 }
References check_divisibility_and_divide_by_pow5(), divide_by_10_to_kappa_plus_1(), floor_log10_pow2(), floor_log2_pow10(), detail::get_cached_power(), remove_trailing_zeros(), and G3D::x.
Referenced by detail::format_float().
umul128()
uint128_wrapper detail::dragonbox::umul128 (uint64_t x, uint64_t y) inline
Definition at line 828 of file format-inl.h.
{
 #if FMT_USE_INT128
   return static_cast<uint128_t>(x) * static_cast<uint128_t>(y);
 #elif defined(_MSC_VER) && defined(_M_X64)
   uint128_wrapper result;
   result.low_ = _umul128(x, y, &result.high_);
   return result;
 #else
   const uint64_t mask = (uint64_t(1) << 32) - uint64_t(1);
   uint64_t a = x >> 32;
   uint64_t b = x & mask;
   uint64_t c = y >> 32;
   uint64_t d = y & mask;
   uint64_t ac = a * c;
   uint64_t bc = b * c;
   uint64_t ad = a * d;
   uint64_t bd = b * d;
   uint64_t intermediate = (bd >> 32) + (ad & mask) + (bc & mask);
   return {ac + (intermediate >> 32) + (ad >> 32) + (bc >> 32),
           (intermediate << 32) + (bd & mask)};
 #endif
 }
References mpq::a, b, mpq::c, mpq::d, G3D::x, and G3D::y.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), umul128_upper64(), and umul192_upper64().
umul128_upper64()
uint64_t detail::dragonbox::umul128_upper64 (uint64_t x, uint64_t y) inline
Definition at line 856 of file format-inl.h.
{
 #if FMT_USE_INT128
   auto p = static_cast<uint128_t>(x) * static_cast<uint128_t>(y);
   return static_cast<uint64_t>(p >> 64);
 #elif defined(_MSC_VER) && defined(_M_X64)
   return __umulh(x, y);
 #else
   return umul128(x, y).high();
 #endif
 }
References detail::uint128_wrapper::high(), umul128(), G3D::x, and G3D::y.
Referenced by divide_by_10_to_kappa_plus_1(), umul192_middle64(), umul192_upper64(), and umul96_upper32().
umul192_middle64()
uint64_t detail::dragonbox::umul192_middle64 (uint64_t x, uint128_wrapper y) inline
Definition at line 883 of file format-inl.h.
{
   uint64_t g01 = x * y.high();
   uint64_t g10 = umul128_upper64(x, y.low());
   return g01 + g10;
 }
References umul128_upper64(), G3D::x, and G3D::y.
Referenced by detail::dragonbox::cache_accessor< double >::compute_mul_parity().
umul192_upper64()
uint64_t detail::dragonbox::umul192_upper64 (uint64_t x, uint128_wrapper y) inline
Definition at line 869 of file format-inl.h.
{
   uint128_wrapper g0 = umul128(x, y.high());
   g0 += umul128_upper64(x, y.low());
   return g0.high();
 }
References detail::uint128_wrapper::high(), umul128(), umul128_upper64(), G3D::x, and G3D::y.
Referenced by detail::dragonbox::cache_accessor< double >::compute_mul().
umul96_lower64()
uint64_t detail::dragonbox::umul96_lower64 (uint32_t x, uint64_t y) inline
Definition at line 891 of file format-inl.h.
{
   return x * y;
 }
References G3D::x, and G3D::y.
Referenced by detail::dragonbox::cache_accessor< float >::compute_mul_parity().
umul96_upper32()
uint32_t detail::dragonbox::umul96_upper32 (uint32_t x, uint64_t y) inline
Definition at line 877 of file format-inl.h.
{
   return static_cast<uint32_t>(umul128_upper64(x, y));
 }
References umul128_upper64(), G3D::x, and G3D::y.
Referenced by detail::dragonbox::cache_accessor< float >::compute_mul().