Azerotcore-wotlk: boss_steelbreaker::boss_steelbreakerAI Struct Reference
boss_steelbreaker::boss_steelbreakerAI Struct Reference
Public Member Functions
boss_steelbreakerAI (Creature *c)
void Reset () override
void JustReachedHome () override
void EnterCombat (Unit *who) override
void UpdatePhase ()
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void DoAction (int32 param) override
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
uint8 _phase
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 203 of file boss_assembly_of_iron.cpp.
Constructor & Destructor Documentation
boss_steelbreakerAI()
boss_steelbreaker::boss_steelbreakerAI::boss_steelbreakerAI (Creature * c) inline
Definition at line 205 of file boss_assembly_of_iron.cpp.
                                          : ScriptedAI(c)
         {
             pInstance = c->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DoAction()
void boss_steelbreaker::boss_steelbreakerAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 319 of file boss_assembly_of_iron.cpp.
         {
             if (param == ACTION_ADD_CHARGE)
                 me->CastSpell(me, SPELL_ELECTRICAL_CHARGE, true);
         }
References ACTION_ADD_CHARGE, Unit::CastSpell(), ScriptedAI::me, and SPELL_ELECTRICAL_CHARGE.
EnterCombat()
void boss_steelbreaker::boss_steelbreakerAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 231 of file boss_assembly_of_iron.cpp.
         {
             if (pInstance)
                 pInstance->SetData(TYPE_ASSEMBLY, IN_PROGRESS);
             me->setActive(true);
             me->SetInCombatWithZone();
             me->CastSpell(me, SPELL_HIGH_VOLTAGE, true);
             events.ScheduleEvent(EVENT_ENRAGE, 900000);
             UpdatePhase();
             if (!pInstance)
                 return;
             if (Creature* boss = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_STEELBREAKER + urand(0, 2))))
             {
                 switch (boss->GetEntry())
                 {
                     case NPC_STEELBREAKER:
                         boss->AI()->Talk(SAY_STEELBREAKER_AGGRO);
                         break;
                     case NPC_MOLGEIM:
                         boss->AI()->Talk(SAY_MOLGEIM_AGGRO);
                         break;
                     case NPC_BRUNDIR:
                         boss->AI()->Talk(SAY_BRUNDIR_AGGRO);
                         break;
                 }
             }
             for (uint8 i = 0; i < 3; ++i)
                 if (Creature* boss = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_STEELBREAKER + i)))
                     if (!boss->IsInCombat())
                         boss->AI()->AttackStart(who);
         }
References Unit::CastSpell(), DATA_STEELBREAKER, EVENT_ENRAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), IN_PROGRESS, ScriptedAI::me, NPC_BRUNDIR, NPC_MOLGEIM, NPC_STEELBREAKER, pInstance, SAY_BRUNDIR_AGGRO, SAY_MOLGEIM_AGGRO, SAY_STEELBREAKER_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_HIGH_VOLTAGE, TYPE_ASSEMBLY, UpdatePhase(), and urand().
JustDied()
void boss_steelbreaker::boss_steelbreakerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 289 of file boss_assembly_of_iron.cpp.
         {
             if (!pInstance)
                 return;
             if (IsEncounterComplete(pInstance, me))
             {
                 pInstance->SetData(TYPE_ASSEMBLY, DONE);
                 me->CastSpell(me, 65195, true); // credit
                 Talk(SAY_STEELBREAKER_ENCOUNTER_DEFEATED);
             }
             else
             {
                 RestoreAssemblyHealth(pInstance->GetGuidData(DATA_BRUNDIR), pInstance->GetGuidData(DATA_MOLGEIM), me);
                 me->CastSpell(me, SPELL_SUPERCHARGE, true);
                 Talk(SAY_STEELBREAKER_DEATH);
             }
         }
References Unit::CastSpell(), DATA_BRUNDIR, DATA_MOLGEIM, DONE, InstanceScript::GetGuidData(), IsEncounterComplete(), ScriptedAI::me, pInstance, RestoreAssemblyHealth(), SAY_STEELBREAKER_DEATH, SAY_STEELBREAKER_ENCOUNTER_DEFEATED, ZoneScript::SetData(), SPELL_SUPERCHARGE, CreatureAI::Talk(), and TYPE_ASSEMBLY.
JustReachedHome()
void boss_steelbreaker::boss_steelbreakerAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 225 of file boss_assembly_of_iron.cpp.
         {
             me->setActive(false);
             me->RemoveAllAuras();
         }
References ScriptedAI::me, Unit::RemoveAllAuras(), and WorldObject::setActive().
KilledUnit()
void boss_steelbreaker::boss_steelbreakerAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 308 of file boss_assembly_of_iron.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (_phase == 3)
                 me->CastSpell(me, SPELL_ELECTRICAL_CHARGE, true);
             Talk(SAY_STEELBREAKER_SLAY);
         }
References _phase, Unit::CastSpell(), Object::GetTypeId(), ScriptedAI::me, SAY_STEELBREAKER_SLAY, SPELL_ELECTRICAL_CHARGE, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_steelbreaker::boss_steelbreakerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 214 of file boss_assembly_of_iron.cpp.
         {
             me->SetLootMode(0);
             RespawnAssemblyOfIron(pInstance, me);
             _phase = 0;
             events.Reset();
             if (pInstance)
                 pInstance->SetData(TYPE_ASSEMBLY, NOT_STARTED);
         }
References _phase, ScriptedAI::me, NOT_STARTED, pInstance, RespawnAssemblyOfIron(), ZoneScript::SetData(), Creature::SetLootMode(), and TYPE_ASSEMBLY.
SpellHit()
void boss_steelbreaker::boss_steelbreakerAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 325 of file boss_assembly_of_iron.cpp.
         {
             if (spellInfo->Id == SPELL_SUPERCHARGE)
                 UpdatePhase();
         }
References SpellInfo::Id, SPELL_SUPERCHARGE, and UpdatePhase().
UpdateAI()
void boss_steelbreaker::boss_steelbreakerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 331 of file boss_assembly_of_iron.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 case EVENT_FUSION_PUNCH:
                     me->CastSpell(me->GetVictim(), SPELL_FUSION_PUNCH, false);
                     events.RepeatEvent(urand(15000, 20000));
                     break;
                 case EVENT_STATIC_DISRUPTION:
                     if (Unit* pTarget = SelectTarget(SELECT_TARGET_FARTHEST, 0, 0, true))
                         me->CastSpell(pTarget, SPELL_STATIC_DISRUPTION, false);
                     events.RepeatEvent(urand(20000, 40000));
                     break;
                 case EVENT_OVERWHELMING_POWER:
                     Talk(SAY_STEELBREAKER_POWER);
                     me->CastSpell(me->GetVictim(), SPELL_OVERWHELMING_POWER, true);
                     events.RepeatEvent(RAID_MODE(61000, 36000));
                     break;
                 case EVENT_ENRAGE:
                     Talk(SAY_STEELBREAKER_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_ENRAGE, EVENT_FUSION_PUNCH, EVENT_OVERWHELMING_POWER, EVENT_STATIC_DISRUPTION, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, ScriptedAI::RAID_MODE(), SAY_STEELBREAKER_BERSERK, SAY_STEELBREAKER_POWER, SELECT_TARGET_FARTHEST, UnitAI::SelectTarget(), SPELL_BERSERK, SPELL_FUSION_PUNCH, SPELL_OVERWHELMING_POWER, SPELL_STATIC_DISRUPTION, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
UpdatePhase()
void boss_steelbreaker::boss_steelbreakerAI::UpdatePhase () inline
Definition at line 267 of file boss_assembly_of_iron.cpp.
         {
             if (_phase >= 3)
                 return;
             ++_phase;
             switch (_phase)
             {
                 case 1:
                     events.RescheduleEvent(EVENT_FUSION_PUNCH, 15000);
                     break;
                 case 2:
                     events.RescheduleEvent(EVENT_STATIC_DISRUPTION, 20000);
                     break;
                 case 3:
                     me->ResetLootMode();
                     events.RescheduleEvent(EVENT_OVERWHELMING_POWER, 8000);
                     break;
             }
         }
References _phase, EVENT_FUSION_PUNCH, EVENT_OVERWHELMING_POWER, EVENT_STATIC_DISRUPTION, ScriptedAI::me, and Creature::ResetLootMode().
Referenced by EnterCombat(), and SpellHit().
Member Data Documentation
_phase
uint8 boss_steelbreaker::boss_steelbreakerAI::_phase
Definition at line 212 of file boss_assembly_of_iron.cpp.
Referenced by KilledUnit(), Reset(), and UpdatePhase().
events
EventMap boss_steelbreaker::boss_steelbreakerAI::events
Definition at line 210 of file boss_assembly_of_iron.cpp.
pInstance
InstanceScript* boss_steelbreaker::boss_steelbreakerAI::pInstance
Definition at line 211 of file boss_assembly_of_iron.cpp.
Referenced by boss_steelbreakerAI(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp