Azerotcore-wotlk: CreatureBaseStats Struct Reference
CreatureBaseStats Struct Reference
#include <CreatureData.h>
Public Member Functions
uint32 GenerateHealth (CreatureTemplate const *info) const
uint32 GenerateMana (CreatureTemplate const *info) const
uint32 GenerateArmor (CreatureTemplate const *info) const
float GenerateBaseDamage (CreatureTemplate const *info) const
Static Public Member Functions
static CreatureBaseStats const * GetBaseStats (uint8 level, uint8 unitClass)
Public Attributes
uint32 BaseHealth [MAX_EXPANSIONS]
uint32 BaseMana
uint32 BaseArmor
uint32 AttackPower
uint32 RangedAttackPower
float BaseDamage [MAX_EXPANSIONS]
Detailed Description
Definition at line 201 of file CreatureData.h.
Member Function Documentation
GenerateArmor()
uint32 CreatureBaseStats::GenerateArmor (CreatureTemplate const * info) const inline
Definition at line 226 of file CreatureData.h.
     {
         return uint32(ceil(BaseArmor * info->ModArmor));
     }
References BaseArmor, G3D::ceil(), and CreatureTemplate::ModArmor.
Referenced by Creature::UpdateEntry().
GenerateBaseDamage()
float CreatureBaseStats::GenerateBaseDamage (CreatureTemplate const * info) const inline
Definition at line 231 of file CreatureData.h.
     {
         return BaseDamage[info->expansion];
     }
References BaseDamage, and CreatureTemplate::expansion.
Referenced by Creature::SelectLevel().
GenerateHealth()
uint32 CreatureBaseStats::GenerateHealth (CreatureTemplate const * info) const inline
Definition at line 212 of file CreatureData.h.
     {
         return uint32(ceil(BaseHealth[info->expansion] * info->ModHealth));
     }
References BaseHealth, G3D::ceil(), CreatureTemplate::expansion, and CreatureTemplate::ModHealth.
Referenced by ObjectMgr::AddCreData(), and Creature::SelectLevel().
GenerateMana()
uint32 CreatureBaseStats::GenerateMana (CreatureTemplate const * info) const inline
Definition at line 217 of file CreatureData.h.
     {
         // Mana can be 0.
         if (!BaseMana)
             return 0;
         return uint32(ceil(BaseMana * info->ModMana));
     }
References BaseMana, G3D::ceil(), and CreatureTemplate::ModMana.
Referenced by ObjectMgr::AddCreData(), and Creature::SelectLevel().
GetBaseStats()
CreatureBaseStats const * CreatureBaseStats::GetBaseStats (uint8 level, uint8 unitClass) static
Definition at line 166 of file Creature.cpp.
 {
     return sObjectMgr->GetCreatureBaseStats(level, unitClass);
 }
References sObjectMgr.
Member Data Documentation
AttackPower
uint32 CreatureBaseStats::AttackPower
Definition at line 206 of file CreatureData.h.
Referenced by ObjectMgr::LoadCreatureClassLevelStats(), Creature::SelectLevel(), and npc_pet_hunter_snake_trap::UpdateAI().
BaseArmor
uint32 CreatureBaseStats::BaseArmor
Definition at line 205 of file CreatureData.h.
Referenced by GenerateArmor(), and ObjectMgr::LoadCreatureClassLevelStats().
BaseDamage
float CreatureBaseStats::BaseDamage[MAX_EXPANSIONS]
Definition at line 208 of file CreatureData.h.
Referenced by GenerateBaseDamage(), and ObjectMgr::LoadCreatureClassLevelStats().
BaseHealth
uint32 CreatureBaseStats::BaseHealth[MAX_EXPANSIONS]
Definition at line 203 of file CreatureData.h.
Referenced by GenerateHealth(), Guardian::InitStatsForLevel(), and ObjectMgr::LoadCreatureClassLevelStats().
BaseMana
uint32 CreatureBaseStats::BaseMana
Definition at line 204 of file CreatureData.h.
Referenced by GenerateMana(), Guardian::InitStatsForLevel(), and ObjectMgr::LoadCreatureClassLevelStats().
RangedAttackPower
uint32 CreatureBaseStats::RangedAttackPower
Definition at line 207 of file CreatureData.h.
Referenced by ObjectMgr::LoadCreatureClassLevelStats(), and Creature::SelectLevel().
The documentation for this struct was generated from the following files:
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Creature/Creature.cpp