Azerotcore-wotlk: npc_wg_demolisher_engineer Class Reference
npc_wg_demolisher_engineer Class Reference
Public Member Functions
npc_wg_demolisher_engineer ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Private Member Functions
bool canBuild (Creature *creature)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 128 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
npc_wg_demolisher_engineer()
npc_wg_demolisher_engineer::npc_wg_demolisher_engineer () inline
Definition at line 131 of file zone_wintergrasp.cpp.
 : CreatureScript("npc_wg_demolisher_engineer") { }
Member Function Documentation
canBuild()
bool npc_wg_demolisher_engineer::canBuild (Creature * creature) inline private
Definition at line 180 of file zone_wintergrasp.cpp.
     {
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (!wintergrasp)
             return false;
         switch (creature->GetEntry())
         {
             case NPC_GOBLIN_MECHANIC:
                 return (wintergrasp->GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H) > wintergrasp->GetData(BATTLEFIELD_WG_DATA_VEHICLE_H));
             case NPC_GNOMISH_ENGINEER:
                 return (wintergrasp->GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A) > wintergrasp->GetData(BATTLEFIELD_WG_DATA_VEHICLE_A));
             default:
                 return false;
         }
     }
References BATTLEFIELD_BATTLEID_WG, BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, Battlefield::GetData(), Object::GetEntry(), NPC_GNOMISH_ENGINEER, NPC_GOBLIN_MECHANIC, and sBattlefieldMgr.
Referenced by OnGossipHello(), and OnGossipSelect().
OnGossipHello()
bool npc_wg_demolisher_engineer::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 133 of file zone_wintergrasp.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (canBuild(creature))
         {
             if (player->HasAura(SPELL_CORPORAL))
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HELLO_DEMO1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
             else if (player->HasAura(SPELL_LIEUTENANT))
             {
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HELLO_DEMO1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HELLO_DEMO2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HELLO_DEMO3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
             }
         }
         else
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HELLO_DEMO4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 9);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), canBuild(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_HELLO_DEMO1, GOSSIP_HELLO_DEMO2, GOSSIP_HELLO_DEMO3, GOSSIP_HELLO_DEMO4, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::HasAura(), Unit::IsQuestGiver(), Player::PrepareQuestMenu(), SendGossipMenuFor(), SPELL_CORPORAL, and SPELL_LIEUTENANT.
OnGossipSelect()
bool npc_wg_demolisher_engineer::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 156 of file zone_wintergrasp.cpp.
     {
         CloseGossipMenuFor(player);
         if (canBuild(creature))
         {
             switch (action - GOSSIP_ACTION_INFO_DEF)
             {
                 case 0:
                     creature->CastSpell(player, SPELL_BUILD_CATAPULT_FORCE, true);
                     break;
                 case 1:
                     creature->CastSpell(player, SPELL_BUILD_DEMOLISHER_FORCE, true);
                     break;
                 case 2:
                     creature->CastSpell(player, player->GetTeamId() == TEAM_ALLIANCE ? SPELL_BUILD_SIEGE_VEHICLE_FORCE_ALLIANCE : SPELL_BUILD_SIEGE_VEHICLE_FORCE_HORDE, true);
                     break;
             }
             creature->CastSpell(creature, SPELL_ACTIVATE_CONTROL_ARMS, true);
         }
         return true;
     }
References canBuild(), Unit::CastSpell(), CloseGossipMenuFor(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, SPELL_ACTIVATE_CONTROL_ARMS, SPELL_BUILD_CATAPULT_FORCE, SPELL_BUILD_DEMOLISHER_FORCE, SPELL_BUILD_SIEGE_VEHICLE_FORCE_ALLIANCE, SPELL_BUILD_SIEGE_VEHICLE_FORCE_HORDE, and TEAM_ALLIANCE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp