Azerotcore-wotlk: lfg_commandscript Class Reference
lfg_commandscript Class Reference
Public Member Functions
lfg_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleLfgPlayerInfoCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
static bool HandleLfgGroupInfoCommand (ChatHandler *handler, Optional< PlayerIdentifier > player)
static bool HandleLfgOptionsCommand (ChatHandler *handler, Optional< uint32 > optionsArg)
static bool HandleLfgQueueInfoCommand (ChatHandler *)
static bool HandleLfgCleanCommand (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 42 of file cs_lfg.cpp.
Constructor & Destructor Documentation
lfg_commandscript()
lfg_commandscript::lfg_commandscript () inline
Definition at line 45 of file cs_lfg.cpp.
 : CommandScript("lfg_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable lfg_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 47 of file cs_lfg.cpp.
     {
         static ChatCommandTable lfgCommandTable =
         {
             { "player",  HandleLfgPlayerInfoCommand, SEC_MODERATOR,     Console::No },
             { "group",   HandleLfgGroupInfoCommand,  SEC_MODERATOR,     Console::No },
             { "queue",   HandleLfgQueueInfoCommand,  SEC_MODERATOR,     Console::Yes },
             { "clean",   HandleLfgCleanCommand,      SEC_ADMINISTRATOR, Console::Yes },
             { "options", HandleLfgOptionsCommand,    SEC_GAMEMASTER,    Console::Yes },
         };
         static ChatCommandTable commandTable =
         {
             { "lfg", lfgCommandTable },
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, and Acore::ChatCommands::Yes.
HandleLfgCleanCommand()
static bool lfg_commandscript::HandleLfgCleanCommand (ChatHandler * handler) inline static
Definition at line 124 of file cs_lfg.cpp.
     {
         handler->PSendSysMessage(LANG_LFG_CLEAN);
         sLFGMgr->Clean();
         return true;
     }
References LANG_LFG_CLEAN, ChatHandler::PSendSysMessage(), and sLFGMgr.
HandleLfgGroupInfoCommand()
static bool lfg_commandscript::HandleLfgGroupInfoCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
Definition at line 81 of file cs_lfg.cpp.
     {
         if (!player)
             player = PlayerIdentifier::FromTargetOrSelf(handler);
         if (!player)
             return false;
         Group* groupTarget = nullptr;
         if (Player* target = player->GetConnectedPlayer())
             groupTarget = target->GetGroup();
         if (!groupTarget)
         {
             handler->PSendSysMessage(LANG_LFG_NOT_IN_GROUP, player->GetName().c_str());
             return true;
         }
         ObjectGuid guid = groupTarget->GetGUID();
         std::string const& state = lfg::GetStateString(sLFGMgr->GetState(guid));
         handler->PSendSysMessage(LANG_LFG_GROUP_INFO, groupTarget->isLFGGroup(),
                                  state.c_str(), sLFGMgr->GetDungeon(guid));
         for (GroupReference* itr = groupTarget->GetFirstMember(); itr != nullptr; itr = itr->next())
             GetPlayerInfo(handler, itr->GetSource());
         return true;
     }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Group::GetFirstMember(), Group::GetGUID(), GetPlayerInfo(), lfg::GetStateString(), Group::isLFGGroup(), LANG_LFG_GROUP_INFO, LANG_LFG_NOT_IN_GROUP, GroupReference::next(), ChatHandler::PSendSysMessage(), and sLFGMgr.
HandleLfgOptionsCommand()
static bool lfg_commandscript::HandleLfgOptionsCommand (ChatHandler * handler, Optional< uint32 > optionsArg) inline static
Definition at line 108 of file cs_lfg.cpp.
     {
         if (optionsArg)
         {
             sLFGMgr->SetOptions(*optionsArg);
             handler->PSendSysMessage(LANG_LFG_OPTIONS_CHANGED);
         }
         handler->PSendSysMessage(LANG_LFG_OPTIONS, sLFGMgr->GetOptions());
         return true;
     }
References LANG_LFG_OPTIONS, LANG_LFG_OPTIONS_CHANGED, ChatHandler::PSendSysMessage(), and sLFGMgr.
HandleLfgPlayerInfoCommand()
static bool lfg_commandscript::HandleLfgPlayerInfoCommand (ChatHandler * handler, Optional< PlayerIdentifier > player) inline static
Definition at line 65 of file cs_lfg.cpp.
     {
         if (!player)
             player = PlayerIdentifier::FromTargetOrSelf(handler);
         if (!player)
             return false;
         if (Player* target = player->GetConnectedPlayer())
         {
             GetPlayerInfo(handler, target);
             return true;
         }
         return false;
     }
References Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), and GetPlayerInfo().
HandleLfgQueueInfoCommand()
static bool lfg_commandscript::HandleLfgQueueInfoCommand (ChatHandler *) inline static
Definition at line 119 of file cs_lfg.cpp.
     {
         return true;
     }
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_lfg.cpp