Azerotcore-wotlk: hyjalAI Struct Reference
hyjalAI Struct Reference
#include <hyjalAI.h>
Classes
struct Spell
Public Member Functions
hyjalAI (Creature *creature)
void Reset () override
void EnterEvadeMode () override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void SetFaction (uint32 _faction)
void Retreat ()
void SpawnVeins ()
void DeSpawnVeins ()
void JustSummoned (Creature *summoned) override
void SummonedCreatureDespawn (Creature *summoned) override
void HideNearPos (float x, float y)
void RespawnNearPos (float x, float y)
void WaypointReached (uint32 waypointId) override
void DoOverrun (uint32 faction, const uint32 diff)
void MoveInLineOfSight (Unit *who) override
void SummonCreature (uint32 entry, float Base[4][3])
void SummonNextWave (const Wave wave[18], uint32 Count, float Base[4][3])
void StartEvent (Player *player)
uint32 GetInstanceData (uint32 Event)
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid PlayerGUID
ObjectGuid BossGUID [2]
ObjectGuid VeinGUID [14]
uint32 NextWaveTimer
uint32 WaveCount
uint32 CheckTimer
uint32 Faction
uint32 EnemyCount
uint32 RetreatTimer
bool EventBegun
bool FirstBossDead
bool SecondBossDead
bool Summon
bool bRetreat
bool Debug
bool VeinsSpawned [2]
uint8 InfernalCount
SummonList Summons
bool Overrun
bool Teleported
bool WaitForTeleport
uint32 TeleportTimer
uint32 OverrunCounter
uint32 OverrunCounter2
uint32 InfernalPoint
uint32 RespawnTimer
bool DoRespawn
bool DoHide
bool IsDummy
uint32 MassTeleportTimer
bool DoMassTeleport
ObjectGuid DummyGuid
struct hyjalAI::Spell Spells [HYJAL_AI_MAX_SPELLS]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
uint32 SpellTimer [3]
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 119 of file hyjalAI.h.
Constructor & Destructor Documentation
hyjalAI()
hyjalAI::hyjalAI (Creature * creature)
Definition at line 316 of file hyjalAI.cpp.
                                    : npc_escortAI(creature), Summons(me)
 {
     instance = creature->GetInstanceScript();
     VeinsSpawned[0] = false;
     VeinsSpawned[1] = false;
     InfernalCount = 0;
     TeleportTimer = 1000;
     Overrun = false;
     Teleported = false;
     WaitForTeleport = false;
     OverrunCounter = 0;
     OverrunCounter2 = 0;
     InfernalPoint = 0;
     RespawnTimer = 10000;
     DoRespawn = false;
     DoHide = false;
     MassTeleportTimer = 0;
     DoMassTeleport = false;
 }
References DoHide, DoMassTeleport, DoRespawn, WorldObject::GetInstanceScript(), InfernalCount, instance, MassTeleportTimer, Overrun, OverrunCounter, OverrunCounter2, RespawnTimer, Teleported, TeleportTimer, VeinsSpawned, and WaitForTeleport.
Member Function Documentation
DeSpawnVeins()
void hyjalAI::DeSpawnVeins ()
Definition at line 663 of file hyjalAI.cpp.
 {
     if (Faction == 1)
     {
         Creature* unit = ObjectAccessor::GetCreature((*me), instance->GetGuidData(DATA_JAINAPROUDMOORE));
         if (!unit)return;
         hyjalAI* ai = CAST_AI(hyjalAI, unit->AI());
         if (!ai)return;
         for (uint8 i = 0; i < 7; ++i)
         {
             if (GameObject* gem = instance->instance->GetGameObject(ai->VeinGUID[i]))
                 gem->Delete();
         }
     }
     else if (Faction)
     {
         Creature* unit = ObjectAccessor::GetCreature((*me), instance->GetGuidData(DATA_THRALL));
         if (!unit)return;
         hyjalAI* ai = CAST_AI(hyjalAI, unit->AI());
         if (!ai)return;
         for (uint8 i = 7; i < 14; ++i)
         {
             if (GameObject* gem = instance->instance->GetGameObject(ai->VeinGUID[i]))
                 gem->Delete();
         }
     }
 }
References Creature::AI(), CAST_AI, DATA_JAINAPROUDMOORE, DATA_THRALL, Faction, ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), InstanceScript::instance, instance, ScriptedAI::me, and VeinGUID.
Referenced by npc_thrall::OnGossipSelect(), and StartEvent().
DoOverrun()
void hyjalAI::DoOverrun (uint32 faction, const uint32 diff)
Definition at line 972 of file hyjalAI.cpp.
 {
     npc_escortAI::UpdateAI(diff);
     if (WaitForTeleport)
     {
         if (TeleportTimer <= diff)
         {
             std::list<Creature*> creatures;
             Acore::AllFriendlyCreaturesInGrid creature_check(me);
             Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid> creature_searcher(me, creatures, creature_check);
             Cell::VisitGridObjects(me, creature_searcher, me->GetGridActivationRange());
             if (!creatures.empty())
             {
                 for (std::list<Creature*>::const_iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
                 {
                     if ((*itr) && (*itr)->IsAlive())
                     {
                         (*itr)->CastSpell(*itr, SPELL_TELEPORT_VISUAL, true);
                         (*itr)->SetFaction(FACTION_FRIENDLY); // make them friendly so mobs won't attack them
                         (*itr)->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     }
                 }
                 DoCast(me, SPELL_TELEPORT_VISUAL);
                 bRetreat = true;
                 RetreatTimer = 1000;
             }
             WaitForTeleport = false;
             Teleported = true;
         }
         TeleportTimer -= diff;
     }
     if (!Teleported)
         return;
     Overrun = false;//execute once
     switch (faction)
     {
         case 0://alliance
             for (uint8 i = 0; i < 92; ++i)//summon fires
                 me->SummonGameObject(GO_ROARING_FLAME, AllianceFirePos[i][0], AllianceFirePos[i][1], AllianceFirePos[i][2], AllianceFirePos[i][3], AllianceFirePos[i][4], AllianceFirePos[i][5], AllianceFirePos[i][6], AllianceFirePos[i][7], 0);
             for (uint8 i = 0; i < 25; ++i)//summon 25 ghouls
             {
                 uint8 r = rand() % 4;
                 Creature* unit = me->SummonCreature(GHOUL, AllianceBase[r][0] + irand(-15, 15), AllianceBase[r][1] + irand(-15, 15), AllianceBase[r][2], 0, TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             for (uint8 i = 0; i < 3; ++i)//summon 3 abominations
             {
                 uint8 r = rand() % 4;
                 Creature* unit = me->SummonCreature(ABOMINATION, AllianceBase[r][0] + irand(-15, 15), AllianceBase[r][1] + irand(-15, 15), AllianceBase[r][2], 0, TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             for (uint8 i = 0; i < 5; ++i)//summon 5 gargoyles
             {
                 Creature* unit = me->SummonCreature(GARGOYLE, AllianceOverrunGargPos[i][0], AllianceOverrunGargPos[i][1], AllianceOverrunGargPos[i][2], AllianceOverrunGargPos[i][3], TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     unit->SetHomePosition(AllianceOverrunGargPos[i][0], AllianceOverrunGargPos[i][1], AllianceOverrunGargPos[i][2], AllianceOverrunGargPos[i][3]);
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             break;
         case 1://horde
             for (uint8 i = 0; i < 65; ++i)//summon fires
                 me->SummonGameObject(GO_ROARING_FLAME, HordeFirePos[i][0], HordeFirePos[i][1], HordeFirePos[i][2], HordeFirePos[i][3], HordeFirePos[i][4], HordeFirePos[i][5], HordeFirePos[i][6], HordeFirePos[i][7], 0);
             for (uint8 i = 0; i < 26; ++i)//summon infernals
             {
                 Creature* unit = me->SummonCreature(GIANT_INFERNAL, InfernalSPWP[i][0], InfernalSPWP[i][1], InfernalSPWP[i][2], InfernalSPWP[i][3], TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     unit->SetHomePosition(InfernalSPWP[i][0], InfernalSPWP[i][1], InfernalSPWP[i][2], InfernalSPWP[i][3]);
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             for (uint8 i = 0; i < 25; ++i)//summon 25 ghouls
             {
                 uint8 r = rand() % 4;
                 Creature* unit = me->SummonCreature(GHOUL, HordeBase[r][0] + irand(-15, 15), HordeBase[r][1] + irand(-15, 15), HordeBase[r][2], 0, TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             for (uint8 i = 0; i < 5; ++i)//summon 5 abominations
             {
                 uint8 r = rand() % 4;
                 Creature* unit = me->SummonCreature(ABOMINATION, HordeBase[r][0] + irand(-15, 15), HordeBase[r][1] + irand(-15, 15), HordeBase[r][2], 0, TEMPSUMMON_MANUAL_DESPAWN, 2 * 60 * 1000);
                 if (unit)
                 {
                     CAST_AI(hyjal_trashAI, unit->AI())->faction = Faction;
                     CAST_AI(hyjal_trashAI, unit->AI())->IsOverrun = true;
                     CAST_AI(hyjal_trashAI, unit->AI())->OverrunType = i;
                     unit->setActive(true);
                 }
             }
             break;
     }
 }
References ABOMINATION, Creature::AI(), AllianceBase, AllianceFirePos, AllianceOverrunGargPos, bRetreat, CAST_AI, UnitAI::DoCast(), Faction, FACTION_FRIENDLY, GARGOYLE, WorldObject::GetGridActivationRange(), GHOUL, GIANT_INFERNAL, GO_ROARING_FLAME, HordeBase, HordeFirePos, InfernalSPWP, irand(), ScriptedAI::me, Overrun, RetreatTimer, WorldObject::setActive(), Creature::SetHomePosition(), SPELL_TELEPORT_VISUAL, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), Teleported, TeleportTimer, TEMPSUMMON_MANUAL_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, npc_escortAI::UpdateAI(), Cell::VisitGridObjects(), and WaitForTeleport.
Referenced by UpdateAI().
EnterCombat()
void hyjalAI::EnterCombat (Unit *) override virtual
Reimplemented from ScriptedAI.
Definition at line 423 of file hyjalAI.cpp.
 {
     if (IsDummy)return;
     for (uint8 i = 0; i < HYJAL_AI_MAX_SPELLS; ++i)
         if (Spells[i].Cooldown)
             SpellTimer[i] = Spells[i].Cooldown;
     Talk(ATTACKED);
 }
References ATTACKED, HYJAL_AI_MAX_SPELLS, IsDummy, SpellTimer, and CreatureAI::Talk().
EnterEvadeMode()
void hyjalAI::EnterEvadeMode () override virtual
Reimplemented from npc_escortAI.
Definition at line 409 of file hyjalAI.cpp.
 {
     if (me->GetEntry() != JAINA)
         me->RemoveAllAuras();
     me->DeleteThreatList();
     me->CombatStop(true);
     me->LoadCreaturesAddon(true);
     if (me->IsAlive())
         me->GetMotionMaster()->MoveTargetedHome();
     me->SetLootRecipient(nullptr);
 }
References Unit::CombatStop(), Unit::DeleteThreatList(), Object::GetEntry(), Unit::GetMotionMaster(), Unit::IsAlive(), JAINA, Creature::LoadCreaturesAddon(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), Unit::RemoveAllAuras(), and Creature::SetLootRecipient().
Referenced by npc_jaina_proudmoore::GetAI(), npc_thrall::GetAI(), and npc_tyrande_whisperwind::GetAI().
GetInstanceData()
uint32 hyjalAI::GetInstanceData (uint32 Event)
Definition at line 599 of file hyjalAI.cpp.
 {
     return instance->GetData(Event);
 }
References ZoneScript::GetData(), and instance.
Referenced by npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), and npc_tyrande_whisperwind::OnGossipHello().
HideNearPos()
void hyjalAI::HideNearPos (float x, float y)
Definition at line 899 of file hyjalAI.cpp.
 {
     // First get all creatures.
     std::list<Creature*> creatures;
     Acore::AllFriendlyCreaturesInGrid creature_check(me);
     Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid> creature_searcher(me, creatures, creature_check);
     Cell::VisitGridObjects(x, y, me->GetMap(), creature_searcher, me->GetGridActivationRange());
     if (!creatures.empty())
     {
         for (std::list<Creature*>::const_iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
         {
             (*itr)->SetVisible(false);
             (*itr)->SetFaction(FACTION_FRIENDLY); // make them friendly so mobs won't attack them
         }
     }
 }
References FACTION_FRIENDLY, WorldObject::GetGridActivationRange(), WorldObject::GetMap(), ScriptedAI::me, and Cell::VisitGridObjects().
Referenced by UpdateAI().
JustDied()
void hyjalAI::JustDied (Unit *) override virtual
Reimplemented from npc_escortAI.
Definition at line 878 of file hyjalAI.cpp.
 {
     if (IsDummy)return;
     me->Respawn();
     me->SetVisible(false);
     DoRespawn = true;
     RespawnTimer = 120000;
     Talk(DEATH);
     Summons.DespawnAll();//despawn all wave's summons
     //reset encounter if boss is despawned (ex: thrall is killed, boss despawns, event stucks at inprogress)
     if (instance->GetData(DATA_RAGEWINTERCHILLEVENT) == IN_PROGRESS)
         instance->SetData(DATA_RAGEWINTERCHILLEVENT, NOT_STARTED);
     if (instance->GetData(DATA_ANETHERONEVENT) == IN_PROGRESS)
         instance->SetData(DATA_ANETHERONEVENT, NOT_STARTED);
     if (instance->GetData(DATA_KAZROGALEVENT) == IN_PROGRESS)
         instance->SetData(DATA_KAZROGALEVENT, NOT_STARTED);
     if (instance->GetData(DATA_AZGALOREVENT) == IN_PROGRESS)
         instance->SetData(DATA_AZGALOREVENT, NOT_STARTED);
     instance->SetData(DATA_RESET_RAIDDAMAGE, 0);//reset damage on die
 }
References DATA_ANETHERONEVENT, DATA_AZGALOREVENT, DATA_KAZROGALEVENT, DATA_RAGEWINTERCHILLEVENT, DATA_RESET_RAIDDAMAGE, DEATH, DoRespawn, ZoneScript::GetData(), IN_PROGRESS, instance, IsDummy, ScriptedAI::me, NOT_STARTED, Creature::Respawn(), RespawnTimer, ZoneScript::SetData(), Unit::SetVisible(), and CreatureAI::Talk().
JustSummoned()
void hyjalAI::JustSummoned (Creature * summoned) override virtual
Reimplemented from ScriptedAI.
Definition at line 336 of file hyjalAI.cpp.
 {
     Summons.Summon(summoned);
 }
MoveInLineOfSight()
void hyjalAI::MoveInLineOfSight (Unit * who) override virtual
Reimplemented from npc_escortAI.
Definition at line 433 of file hyjalAI.cpp.
 {
     if (IsDummy)
         return;
     npc_escortAI::MoveInLineOfSight(who);
 }
References IsDummy, and npc_escortAI::MoveInLineOfSight().
Reset()
void hyjalAI::Reset () override virtual
Reimplemented from ScriptedAI.
Definition at line 346 of file hyjalAI.cpp.
 {
     IsDummy = false;
     me->setActive(true);
     // GUIDs
     PlayerGUID.Clear();
     BossGUID[0].Clear();
     BossGUID[1].Clear();
     // Timers
     NextWaveTimer = 10000;
     CheckTimer = 0;
     RetreatTimer = 1000;
     // Misc
     WaveCount = 0;
     EnemyCount = 0;
     // Set faction properly based on Creature entry
     switch (me->GetEntry())
     {
         case JAINA:
             Faction = 0;
             DoCast(me, SPELL_BRILLIANCE_AURA, true);
             break;
         case THRALL:
             Faction = 1;
             break;
         case TYRANDE:
             Faction = 2;
             break;
     }
     //Bools
     EventBegun = false;
     FirstBossDead = false;
     SecondBossDead = false;
     Summon = false;
     bRetreat = false;
     Debug = false;
     //Flags
     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
     //Initialize spells
     memset(Spells, 0, sizeof(Spell) * HYJAL_AI_MAX_SPELLS);
     //Reset Instance Data for trash count
     if ((!instance->GetData(DATA_ALLIANCE_RETREAT) && me->GetEntry() == JAINA) || (instance->GetData(DATA_ALLIANCE_RETREAT) && me->GetEntry() == THRALL))
     {
         //Reset World States
         instance->DoUpdateWorldState(WORLD_STATE_WAVES, 0);
         instance->DoUpdateWorldState(WORLD_STATE_ENEMY, 0);
         instance->DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, 0);
         instance->SetData(DATA_RESET_TRASH_COUNT, 0);
     }
     //Visibility
     DoHide = true;
 }
References BossGUID, bRetreat, CheckTimer, ObjectGuid::Clear(), DATA_ALLIANCE_RETREAT, DATA_RESET_TRASH_COUNT, Debug, UnitAI::DoCast(), DoHide, InstanceScript::DoUpdateWorldState(), EnemyCount, EventBegun, Faction, FirstBossDead, ZoneScript::GetData(), Object::GetEntry(), HYJAL_AI_MAX_SPELLS, instance, IsDummy, JAINA, ScriptedAI::me, NextWaveTimer, PlayerGUID, RetreatTimer, SecondBossDead, WorldObject::setActive(), ZoneScript::SetData(), Object::SetFlag(), SPELL_BRILLIANCE_AURA, Summon, THRALL, TYRANDE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, WaveCount, WORLD_STATE_ENEMY, WORLD_STATE_ENEMYCOUNT, and WORLD_STATE_WAVES.
Referenced by npc_jaina_proudmoore::GetAI(), npc_thrall::GetAI(), and npc_tyrande_whisperwind::GetAI().
RespawnNearPos()
void hyjalAI::RespawnNearPos (float x, float y)
Definition at line 918 of file hyjalAI.cpp.
 {
     Acore::RespawnDo u_do;
     Acore::WorldObjectWorker<Acore::RespawnDo> worker(me, u_do);
     Cell::VisitGridObjects(x, y, me->GetMap(), worker, me->GetGridActivationRange());
 }
References WorldObject::GetGridActivationRange(), WorldObject::GetMap(), ScriptedAI::me, and Cell::VisitGridObjects().
Referenced by UpdateAI().
Retreat()
void hyjalAI::Retreat ()
Definition at line 604 of file hyjalAI.cpp.
 {
     instance->SetData(TYPE_RETREAT, SPECIAL);
     if (Faction == 0)
     {
         instance->SetData(DATA_ALLIANCE_RETREAT, 1);
         AddWaypoint(0, JainaWPs[0][0], JainaWPs[0][1], JainaWPs[0][2]);
         AddWaypoint(1, JainaWPs[1][0], JainaWPs[1][1], JainaWPs[1][2]);
         Start(false, false);
         SetDespawnAtEnd(false);//move to center of alliance base
     }
     if (Faction == 1)
     {
         instance->SetData(DATA_HORDE_RETREAT, 1);
         Creature* JainaDummy = me->SummonCreature(JAINA, JainaDummySpawn[0][0], JainaDummySpawn[0][1], JainaDummySpawn[0][2], JainaDummySpawn[0][3], TEMPSUMMON_TIMED_DESPAWN, 60000);
         if (JainaDummy)
         {
             JainaDummy->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             CAST_AI(hyjalAI, JainaDummy->AI())->IsDummy = true;
             DummyGuid = JainaDummy->GetGUID();
         }
         AddWaypoint(0, JainaDummySpawn[1][0], JainaDummySpawn[1][1], JainaDummySpawn[1][2]);
         Start(false, false);
         SetDespawnAtEnd(false);//move to center of alliance base
     }
     SpawnVeins();
     Overrun = true;
     me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);//cant talk after overrun event started
 }
References npc_escortAI::AddWaypoint(), Creature::AI(), CAST_AI, DATA_ALLIANCE_RETREAT, DATA_HORDE_RETREAT, DummyGuid, Faction, Object::GetGUID(), instance, JAINA, JainaDummySpawn, JainaWPs, ScriptedAI::me, Overrun, Object::RemoveFlag(), ZoneScript::SetData(), npc_escortAI::SetDespawnAtEnd(), SpawnVeins(), SPECIAL, npc_escortAI::Start(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, TYPE_RETREAT, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by npc_jaina_proudmoore::OnGossipSelect(), and npc_thrall::OnGossipSelect().
SetFaction()
void hyjalAI::SetFaction (uint32 _faction) inline
Definition at line 133 of file hyjalAI.h.
     {
         Faction = _faction;
     }
References Faction.
SpawnVeins()
void hyjalAI::SpawnVeins ()
Definition at line 635 of file hyjalAI.cpp.
 {
     if (Faction == 0)
     {
         if (VeinsSpawned[0])//prevent any buggers
             return;
         for (uint8 i = 0; i < 7; ++i)
         {
             GameObject* gem = me->SummonGameObject(GO_ANCIENT_VEIN, VeinPos[i][0], VeinPos[i][1], VeinPos[i][2], VeinPos[i][3], VeinPos[i][4], VeinPos[i][5], VeinPos[i][6], VeinPos[i][7], 0);
             if (gem)
                 VeinGUID[i] = gem->GetGUID();
         }
         VeinsSpawned[0] = true;
     }
     else
     {
         if (VeinsSpawned[1])
             return;
         for (uint8 i = 7; i < 14; ++i)
         {
             GameObject* gem = me->SummonGameObject(GO_ANCIENT_VEIN, VeinPos[i][0], VeinPos[i][1], VeinPos[i][2], VeinPos[i][3], VeinPos[i][4], VeinPos[i][5], VeinPos[i][6], VeinPos[i][7], 0);
             if (gem)
                 VeinGUID[i] = gem->GetGUID();
         }
         VeinsSpawned[1] = true;
     }
 }
References Faction, Object::GetGUID(), GO_ANCIENT_VEIN, ScriptedAI::me, WorldObject::SummonGameObject(), VeinGUID, VeinPos, and VeinsSpawned.
Referenced by Retreat().
StartEvent()
void hyjalAI::StartEvent (Player * player)
Definition at line 576 of file hyjalAI.cpp.
 {
     if (!player || IsDummy || !instance)
         return;
     Talk(BEGIN);
     EventBegun = true;
     Summon = true;
     NextWaveTimer = 15000;
     CheckTimer = 5000;
     PlayerGUID = player->GetGUID();
     me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
     instance->DoUpdateWorldState(WORLD_STATE_WAVES, 0);
     instance->DoUpdateWorldState(WORLD_STATE_ENEMY, 0);
     instance->DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, 0);
     DeSpawnVeins();
 }
References BEGIN, CheckTimer, DeSpawnVeins(), InstanceScript::DoUpdateWorldState(), EventBegun, Object::GetGUID(), instance, IsDummy, ScriptedAI::me, NextWaveTimer, PlayerGUID, Object::RemoveFlag(), Summon, CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, WORLD_STATE_ENEMY, WORLD_STATE_ENEMYCOUNT, and WORLD_STATE_WAVES.
Referenced by npc_jaina_proudmoore::OnGossipSelect(), and npc_thrall::OnGossipSelect().
SummonCreature()
void hyjalAI::SummonCreature (uint32 entry, float Base[4][3])
Definition at line 441 of file hyjalAI.cpp.
 {
     uint32 random = rand() % 4;
     float SpawnLoc[3];
     for (uint8 i = 0; i < 3; ++i)
     {
         SpawnLoc[i] = Base[random][i];
     }
     Creature* creature = nullptr;
     switch (entry)
     {
         case 17906:    //GARGOYLE
             if (!FirstBossDead && (WaveCount == 1 || WaveCount == 3))
             {
                 //summon at tower
                 creature = me->SummonCreature(entry, SpawnPointSpecial[SPAWN_NEAR_TOWER][0] + irand(-20, 20), SpawnPointSpecial[SPAWN_NEAR_TOWER][1] + irand(-20, 20), SpawnPointSpecial[SPAWN_NEAR_TOWER][2] + irand(-10, 10), 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
                 if (creature)
                     CAST_AI(hyjal_trashAI, creature->AI())->useFlyPath = true;
             }
             else
             {
                 //summon at gate
                 creature = me->SummonCreature(entry, SpawnPointSpecial[SPAWN_GARG_GATE][0] + irand(-10, 10), SpawnPointSpecial[SPAWN_GARG_GATE][1] + irand(-10, 10), SpawnPointSpecial[SPAWN_GARG_GATE][2] + irand(-10, 10), 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
             }
             break;
         case 17907:    //FROST_WYRM,
             if (FirstBossDead && WaveCount == 1) //summon at gate
                 creature = me->SummonCreature(entry, SpawnPointSpecial[SPAWN_WYRM_GATE][0], SpawnPointSpecial[SPAWN_WYRM_GATE][1], SpawnPointSpecial[SPAWN_WYRM_GATE][2], 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
             else
             {
                 creature = me->SummonCreature(entry, SpawnPointSpecial[SPAWN_NEAR_TOWER][0], SpawnPointSpecial[SPAWN_NEAR_TOWER][1], SpawnPointSpecial[SPAWN_NEAR_TOWER][2], 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
                 if (creature)
                     CAST_AI(hyjal_trashAI, creature->AI())->useFlyPath = true;
             }
             break;
         case 17908:    //GIANT_INFERNAL
             ++InfernalCount;
             if (InfernalCount > 7)
                 InfernalCount = 0;
             creature = me->SummonCreature(entry, InfernalPos[InfernalCount][0], InfernalPos[InfernalCount][1], InfernalPos[InfernalCount][2], 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
             break;
         default:
             creature = me->SummonCreature(entry, SpawnLoc[0], SpawnLoc[1], SpawnLoc[2], 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 120000);
             break;
     }
     if (creature)
     {
         // Increment Enemy Count to be used in World States and instance script
         ++EnemyCount;
         creature->SetWalk(false);
         creature->setActive(true);
         switch (entry)
         {
             case NECROMANCER:
             case ABOMINATION:
             case GHOUL:
             case BANSHEE:
             case CRYPT_FIEND:
             case GARGOYLE:
             case FROST_WYRM:
             case GIANT_INFERNAL:
             case FEL_STALKER:
             case RAGE_WINTERCHILL:
             case ANETHERON:
             case KAZROGAL:
             case AZGALOR:
                 CAST_AI(hyjal_trashAI, creature->AI())->IsEvent = true;
                 break;
         }
         if (instance->GetData(DATA_RAIDDAMAGE) < MINRAIDDAMAGE)
             creature->SetDisableReputationGain(true);//no repu for solo farming
         // Check if Creature is a boss.
         if (creature->isWorldBoss())
         {
             if (!FirstBossDead)  BossGUID[0] = creature->GetGUID();
             else                BossGUID[1] = creature->GetGUID();
             CheckTimer = 5000;
         }
     }
 }
References ABOMINATION, Creature::AI(), ANETHERON, AZGALOR, BANSHEE, BossGUID, CAST_AI, CheckTimer, CRYPT_FIEND, DATA_RAIDDAMAGE, EnemyCount, FEL_STALKER, FirstBossDead, FROST_WYRM, GARGOYLE, ZoneScript::GetData(), Object::GetGUID(), GHOUL, GIANT_INFERNAL, InfernalCount, InfernalPos, instance, irand(), Creature::isWorldBoss(), KAZROGAL, ScriptedAI::me, MINRAIDDAMAGE, NECROMANCER, RAGE_WINTERCHILL, WorldObject::setActive(), Creature::SetDisableReputationGain(), Creature::SetWalk(), SPAWN_GARG_GATE, SPAWN_NEAR_TOWER, SPAWN_WYRM_GATE, SpawnLoc, SpawnPointSpecial, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, and WaveCount.
Referenced by SummonNextWave().
SummonedCreatureDespawn()
void hyjalAI::SummonedCreatureDespawn (Creature * summoned) override virtual
Reimplemented from ScriptedAI.
Definition at line 341 of file hyjalAI.cpp.
 {
     Summons.Despawn(summoned);
 }
SummonNextWave()
void hyjalAI::SummonNextWave (const Wave wave[18], uint32 Count, float Base[4][3])
Definition at line 526 of file hyjalAI.cpp.
 {
     // 1 in 4 chance we give a rally yell. Not sure if the chance is offilike.
     if (rand() % 4 == 0)
         Talk(RALLY);
     InfernalCount = 0;//reset infernal count every new wave
     EnemyCount = instance->GetData(DATA_TRASH);
     for (uint8 i = 0; i < 18; ++i)
     {
         if (wave[Count].Mob[i])
             SummonCreature(wave[Count].Mob[i], Base);
     }
     if (!wave[Count].IsBoss)
     {
         uint32 stateValue = Count + 1;
         if (FirstBossDead)
             stateValue -= 9;                                // Subtract 9 from it to give the proper wave number if we are greater than 8
         // Set world state to our current wave number
         instance->DoUpdateWorldState(WORLD_STATE_WAVES, stateValue);    // Set world state to our current wave number
         // Enable world state
         instance->DoUpdateWorldState(WORLD_STATE_ENEMY, 1);             // Enable world state
         instance->SetData(DATA_TRASH, EnemyCount);         // Send data for instance script to update count
         if (!Debug)
             NextWaveTimer = wave[Count].WaveTimer;
         else
         {
             NextWaveTimer = 15000;
             //TC_LOG_DEBUG("scripts", "HyjalAI: debug mode is enabled. Next Wave in 15 seconds");
         }
     }
     else
     {
         // Set world state for waves to 0 to disable it.
         instance->DoUpdateWorldState(WORLD_STATE_WAVES, 0);
         instance->DoUpdateWorldState(WORLD_STATE_ENEMY, 1);
         // Set World State for enemies invading to 1.
         instance->DoUpdateWorldState(WORLD_STATE_ENEMYCOUNT, 1);
         Summon = false;
     }
     CheckTimer = 5000;
 }
References CheckTimer, Acore::Count(), DATA_TRASH, Debug, InstanceScript::DoUpdateWorldState(), EnemyCount, FirstBossDead, ZoneScript::GetData(), InfernalCount, instance, NextWaveTimer, RALLY, ZoneScript::SetData(), Summon, SummonCreature(), CreatureAI::Talk(), Wave::WaveTimer, WORLD_STATE_ENEMY, WORLD_STATE_ENEMYCOUNT, and WORLD_STATE_WAVES.
Referenced by UpdateAI().
UpdateAI()
void hyjalAI::UpdateAI (uint32 diff) override virtual
Reimplemented from npc_escortAI.
Definition at line 691 of file hyjalAI.cpp.
 {
     if (IsDummy)
     {
         if (MassTeleportTimer < diff && DoMassTeleport)
         {
             DoCast(me, SPELL_MASS_TELEPORT, false);
             DoMassTeleport = false;
         }
         else MassTeleportTimer -= diff;
         return;
     }
     if (DoHide)
     {
         DoHide = false;
         switch (me->GetEntry())
         {
             case JAINA:
                 if (instance->GetData(DATA_ALLIANCE_RETREAT))
                 {
                     me->SetVisible(false);
                     HideNearPos(me->GetPositionX(), me->GetPositionY());
                     HideNearPos(5037.76f, -1889.71f);
                     for (uint8 i = 0; i < 92; ++i)//summon fires
                         me->SummonGameObject(GO_ROARING_FLAME, AllianceFirePos[i][0], AllianceFirePos[i][1], AllianceFirePos[i][2], AllianceFirePos[i][3], AllianceFirePos[i][4], AllianceFirePos[i][5], AllianceFirePos[i][6], AllianceFirePos[i][7], 0);
                 }
                 else me->SetVisible(true);
                 break;
             case THRALL: //thrall
                 if (instance->GetData(DATA_HORDE_RETREAT))
                 {
                     me->SetVisible(false);
                     HideNearPos(me->GetPositionX(), me->GetPositionY());
                     HideNearPos(5563, -2763.19f);
                     HideNearPos(5542.2f, -2629.36f);
                     for (uint8 i = 0; i < 65; ++i)//summon fires
                         me->SummonGameObject(GO_ROARING_FLAME, HordeFirePos[i][0], HordeFirePos[i][1], HordeFirePos[i][2], HordeFirePos[i][3], HordeFirePos[i][4], HordeFirePos[i][5], HordeFirePos[i][6], HordeFirePos[i][7], 0);
                 }
                 else me->SetVisible(true);
                 break;
         }
     }
     if (DoRespawn)
     {
         if (RespawnTimer <= diff)
         {
             DoRespawn = false;
             RespawnNearPos(me->GetPositionX(), me->GetPositionY());
             if (Faction == 0)
             {
                 RespawnNearPos(5037.76f, -1889.71f);
             }
             else if (Faction == 1)
             {
                 RespawnNearPos(5563, -2763.19f);
                 RespawnNearPos(5542.2f, -2629.36f);
             }
             me->SetVisible(true);
         }
         else
         {
             RespawnTimer -= diff;
             me->SetVisible(false);
         }
         return;
     }
     if (Overrun)
         DoOverrun(Faction, diff);
     if (bRetreat)
     {
         if (RetreatTimer <= diff)
         {
             IsDummy = true;
             bRetreat = false;
             HideNearPos(me->GetPositionX(), me->GetPositionY());
             switch (me->GetEntry())
             {
                 case JAINA://jaina
                     HideNearPos(5037.76f, -1889.71f);
                     break;
                 case THRALL://thrall
                     HideNearPos(5563, -2763.19f);
                     HideNearPos(5542.2f, -2629.36f);
                     HideNearPos(5603.75f, -2853.12f);
                     break;
             }
             me->SetVisible(false);
         }
         else RetreatTimer -= diff;
     }
     if (!EventBegun)
         return;
     if (Summon)
     {
         if (EnemyCount)
         {
             EnemyCount = instance->GetData(DATA_TRASH);
             if (!EnemyCount)
                 NextWaveTimer = 5000;
         }
         if (NextWaveTimer <= diff)
         {
             if (Faction == 0)
                 SummonNextWave(AllianceWaves, WaveCount, AllianceBase);
             else if (Faction == 1)
                 SummonNextWave(HordeWaves, WaveCount, HordeBase);
             ++WaveCount;
         }
         else NextWaveTimer -= diff;
     }
     if (CheckTimer <= diff)
     {
         for (uint8 i = 0; i < 2; ++i)
         {
             if (BossGUID[i])
             {
                 Unit* unit = ObjectAccessor::GetUnit(*me, BossGUID[i]);
                 if (unit && (!unit->IsAlive()))
                 {
                     if (BossGUID[i] == BossGUID[0])
                     {
                         Talk(INCOMING);
                         FirstBossDead = true;
                     }
                     else if (BossGUID[i] == BossGUID[1])
                     {
                         Talk(SUCCESS);
                         SecondBossDead = true;
                     }
                     EventBegun = false;
                     CheckTimer = 0;
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     BossGUID[i].Clear();
                     instance->DoUpdateWorldState(WORLD_STATE_ENEMY, 0); // Reset world state for enemies to disable it
                 }
             }
         }
         CheckTimer = 5000;
     }
     else CheckTimer -= diff;
     if (!UpdateVictim())
         return;
     for (uint8 i = 0; i < HYJAL_AI_MAX_SPELLS; ++i)
     {
         if (Spells[i].SpellId)
         {
             if (SpellTimer[i] <= diff)
             {
                 if (me->IsNonMeleeSpellCast(false))
                     me->InterruptNonMeleeSpells(false);
                 Unit* target = nullptr;
                 switch (Spells[i].TargetType)
                 {
                     case TARGETTYPE_SELF:
                         target = me;
                         break;
                     case TARGETTYPE_RANDOM:
                         target = SelectTarget(SELECT_TARGET_RANDOM, 0);
                         break;
                     case TARGETTYPE_VICTIM:
                         target = me->GetVictim();
                         break;
                 }
                 if (target && target->IsAlive())
                 {
                     DoCast(target, Spells[i].SpellId);
                     SpellTimer[i] = Spells[i].Cooldown;
                 }
             }
             else SpellTimer[i] -= diff;
         }
     }
     DoMeleeAttackIfReady();
 }
References AllianceBase, AllianceFirePos, AllianceWaves, BossGUID, bRetreat, CheckTimer, ObjectGuid::Clear(), DATA_ALLIANCE_RETREAT, DATA_HORDE_RETREAT, DATA_TRASH, UnitAI::DoCast(), DoHide, DoMassTeleport, UnitAI::DoMeleeAttackIfReady(), DoOverrun(), DoRespawn, InstanceScript::DoUpdateWorldState(), EnemyCount, EventBegun, Faction, FirstBossDead, ZoneScript::GetData(), Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), ObjectAccessor::GetUnit(), Unit::GetVictim(), GO_ROARING_FLAME, HideNearPos(), HordeBase, HordeFirePos, HordeWaves, HYJAL_AI_MAX_SPELLS, INCOMING, instance, Unit::InterruptNonMeleeSpells(), Unit::IsAlive(), IsDummy, Unit::IsNonMeleeSpellCast(), JAINA, MassTeleportTimer, ScriptedAI::me, NextWaveTimer, Overrun, RespawnNearPos(), RespawnTimer, RetreatTimer, SecondBossDead, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Object::SetFlag(), Unit::SetVisible(), SPELL_MASS_TELEPORT, SpellTimer, SUCCESS, Summon, WorldObject::SummonGameObject(), SummonNextWave(), CreatureAI::Talk(), TARGETTYPE_RANDOM, TARGETTYPE_SELF, TARGETTYPE_VICTIM, THRALL, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, CreatureAI::UpdateVictim(), WaveCount, and WORLD_STATE_ENEMY.
WaypointReached()
void hyjalAI::WaypointReached (uint32 waypointId) override virtual
Implements npc_escortAI.
Definition at line 925 of file hyjalAI.cpp.
 {
     if (waypointId == 1 || (waypointId == 0 && me->GetEntry() == THRALL))
     {
         me->Yell(YELL_HURRY, LANG_UNIVERSAL);
         WaitForTeleport = true;
         TeleportTimer = 20000;
         if (me->GetEntry() == JAINA)
             DoCast(me, SPELL_MASS_TELEPORT, false);
         if (me->GetEntry() == THRALL && DummyGuid)
         {
             if (Creature* creature = ObjectAccessor::GetCreature(*me, DummyGuid))
             {
                 hyjalAI* ai = CAST_AI(hyjalAI, creature->AI());
                 ai->DoMassTeleport = true;
                 ai->MassTeleportTimer = 20000;
                 creature->CastSpell(me, SPELL_MASS_TELEPORT, false);
             }
         }
         //do some talking
         //all alive guards walk near here
         // First get all creatures.
         std::list<Creature*> creatures;
         Acore::AllFriendlyCreaturesInGrid creature_check(me);
         Acore::CreatureListSearcher<Acore::AllFriendlyCreaturesInGrid> creature_searcher(me, creatures, creature_check);
         Cell::VisitGridObjects(me, creature_searcher, me->GetGridActivationRange());
         if (!creatures.empty())
         {
             for (std::list<Creature*>::const_iterator itr = creatures.begin(); itr != creatures.end(); ++itr)
             {
                 if ((*itr) && (*itr)->IsAlive() && (*itr) != me && (*itr)->GetEntry() != JAINA)
                 {
                     if (!(*itr)->IsWithinDist(me, 60))
                         (*itr)->SetWalk(false);
                     float x, y, z;
                     (*itr)->SetDefaultMovementType(IDLE_MOTION_TYPE);
                     (*itr)->GetMotionMaster()->Initialize();
                     float range = 10;
                     if (me->GetEntry() == THRALL)range = 20;
                     me->GetNearPoint(me, x, y, z, range, 0, me->GetAngle((*itr)));
                     (*itr)->GetMotionMaster()->MovePoint(0, x + irand(-5, 5), y + irand(-5, 5), me->GetPositionZ());
                 }
             }
         }
     }
 }
References CAST_AI, UnitAI::DoCast(), DoMassTeleport, DummyGuid, Position::GetAngle(), ObjectAccessor::GetCreature(), Object::GetEntry(), WorldObject::GetGridActivationRange(), WorldObject::GetNearPoint(), Position::GetPositionZ(), IDLE_MOTION_TYPE, irand(), JAINA, LANG_UNIVERSAL, MassTeleportTimer, ScriptedAI::me, SPELL_MASS_TELEPORT, TeleportTimer, THRALL, Cell::VisitGridObjects(), WaitForTeleport, Unit::Yell(), and YELL_HURRY.
Member Data Documentation
BossGUID
ObjectGuid hyjalAI::BossGUID[2]
Definition at line 163 of file hyjalAI.h.
Referenced by Reset(), SummonCreature(), and UpdateAI().
bRetreat
bool hyjalAI::bRetreat
Definition at line 177 of file hyjalAI.h.
Referenced by DoOverrun(), Reset(), and UpdateAI().
CheckTimer
uint32 hyjalAI::CheckTimer
Definition at line 168 of file hyjalAI.h.
Referenced by Reset(), StartEvent(), SummonCreature(), SummonNextWave(), and UpdateAI().
Debug
bool hyjalAI::Debug
Definition at line 178 of file hyjalAI.h.
Referenced by npc_jaina_proudmoore::OnGossipSelect(), npc_thrall::OnGossipSelect(), Reset(), and SummonNextWave().
DoHide
bool hyjalAI::DoHide
Definition at line 191 of file hyjalAI.h.
Referenced by hyjalAI(), Reset(), and UpdateAI().
DoMassTeleport
bool hyjalAI::DoMassTeleport
Definition at line 194 of file hyjalAI.h.
Referenced by hyjalAI(), UpdateAI(), and WaypointReached().
DoRespawn
bool hyjalAI::DoRespawn
Definition at line 190 of file hyjalAI.h.
Referenced by hyjalAI(), JustDied(), and UpdateAI().
DummyGuid
ObjectGuid hyjalAI::DummyGuid
Definition at line 195 of file hyjalAI.h.
Referenced by Retreat(), and WaypointReached().
EnemyCount
uint32 hyjalAI::EnemyCount
Definition at line 170 of file hyjalAI.h.
Referenced by Reset(), SummonCreature(), SummonNextWave(), and UpdateAI().
EventBegun
bool hyjalAI::EventBegun
Definition at line 173 of file hyjalAI.h.
Referenced by npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), Reset(), StartEvent(), and UpdateAI().
Faction
uint32 hyjalAI::Faction
Definition at line 169 of file hyjalAI.h.
Referenced by DeSpawnVeins(), DoOverrun(), Reset(), Retreat(), SetFaction(), SpawnVeins(), and UpdateAI().
FirstBossDead
bool hyjalAI::FirstBossDead
Definition at line 174 of file hyjalAI.h.
Referenced by npc_jaina_proudmoore::OnGossipSelect(), npc_thrall::OnGossipSelect(), Reset(), SummonCreature(), SummonNextWave(), and UpdateAI().
InfernalCount
uint8 hyjalAI::InfernalCount
Definition at line 180 of file hyjalAI.h.
Referenced by hyjalAI(), SummonCreature(), and SummonNextWave().
InfernalPoint
uint32 hyjalAI::InfernalPoint
Definition at line 188 of file hyjalAI.h.
instance
InstanceScript* hyjalAI::instance
Definition at line 160 of file hyjalAI.h.
Referenced by DeSpawnVeins(), GetInstanceData(), hyjalAI(), JustDied(), Reset(), Retreat(), StartEvent(), SummonCreature(), SummonNextWave(), and UpdateAI().
IsDummy
bool hyjalAI::IsDummy
Definition at line 192 of file hyjalAI.h.
Referenced by EnterCombat(), JustDied(), MoveInLineOfSight(), Reset(), StartEvent(), and UpdateAI().
MassTeleportTimer
uint32 hyjalAI::MassTeleportTimer
Definition at line 193 of file hyjalAI.h.
Referenced by hyjalAI(), UpdateAI(), and WaypointReached().
NextWaveTimer
uint32 hyjalAI::NextWaveTimer
Definition at line 166 of file hyjalAI.h.
Referenced by Reset(), StartEvent(), SummonNextWave(), and UpdateAI().
Overrun
bool hyjalAI::Overrun
Definition at line 182 of file hyjalAI.h.
Referenced by DoOverrun(), hyjalAI(), Retreat(), and UpdateAI().
OverrunCounter
uint32 hyjalAI::OverrunCounter
Definition at line 186 of file hyjalAI.h.
Referenced by hyjalAI().
OverrunCounter2
uint32 hyjalAI::OverrunCounter2
Definition at line 187 of file hyjalAI.h.
Referenced by hyjalAI().
PlayerGUID
ObjectGuid hyjalAI::PlayerGUID
Definition at line 162 of file hyjalAI.h.
Referenced by Reset(), and StartEvent().
RespawnTimer
uint32 hyjalAI::RespawnTimer
Definition at line 189 of file hyjalAI.h.
Referenced by hyjalAI(), JustDied(), and UpdateAI().
RetreatTimer
uint32 hyjalAI::RetreatTimer
Definition at line 171 of file hyjalAI.h.
Referenced by DoOverrun(), Reset(), and UpdateAI().
SecondBossDead
bool hyjalAI::SecondBossDead
Definition at line 175 of file hyjalAI.h.
Referenced by Reset(), and UpdateAI().
Spells
struct hyjalAI::Spell hyjalAI::Spells[HYJAL_AI_MAX_SPELLS]
Referenced by npc_jaina_proudmoore::GetAI(), and npc_thrall::GetAI().
SpellTimer
uint32 hyjalAI::SpellTimer[3] private
Definition at line 205 of file hyjalAI.h.
Referenced by EnterCombat(), and UpdateAI().
Summon
bool hyjalAI::Summon
Definition at line 176 of file hyjalAI.h.
Referenced by Reset(), StartEvent(), SummonNextWave(), and UpdateAI().
Summons
SummonList hyjalAI::Summons
Definition at line 181 of file hyjalAI.h.
Teleported
bool hyjalAI::Teleported
Definition at line 183 of file hyjalAI.h.
Referenced by DoOverrun(), and hyjalAI().
TeleportTimer
uint32 hyjalAI::TeleportTimer
Definition at line 185 of file hyjalAI.h.
Referenced by DoOverrun(), hyjalAI(), and WaypointReached().
VeinGUID
ObjectGuid hyjalAI::VeinGUID[14]
Definition at line 164 of file hyjalAI.h.
Referenced by DeSpawnVeins(), and SpawnVeins().
VeinsSpawned
bool hyjalAI::VeinsSpawned[2]
Definition at line 179 of file hyjalAI.h.
Referenced by hyjalAI(), and SpawnVeins().
WaitForTeleport
bool hyjalAI::WaitForTeleport
Definition at line 184 of file hyjalAI.h.
Referenced by DoOverrun(), hyjalAI(), and WaypointReached().
WaveCount
uint32 hyjalAI::WaveCount
Definition at line 167 of file hyjalAI.h.
Referenced by npc_jaina_proudmoore::OnGossipSelect(), npc_thrall::OnGossipSelect(), Reset(), SummonCreature(), and UpdateAI().
The documentation for this struct was generated from the following files:
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.h
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp