Azerotcore-wotlk: npc_beryl_sorcerer::npc_beryl_sorcererAI Struct Reference
npc_beryl_sorcerer::npc_beryl_sorcererAI Struct Reference
Public Member Functions
npc_beryl_sorcererAI (Creature *creature)
void Initialize ()
void Reset () override
void EnterCombat (Unit *who) override
void SpellHit (Unit *unit, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
ObjectGuid _playerGUID
bool _chainsCast
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 526 of file zone_borean_tundra.cpp.
Constructor & Destructor Documentation
npc_beryl_sorcererAI()
npc_beryl_sorcerer::npc_beryl_sorcererAI::npc_beryl_sorcererAI (Creature * creature) inline
Definition at line 528 of file zone_borean_tundra.cpp.
                                                  : CreatureAI(creature)
         {
             Initialize();
         }
References Initialize().
Member Function Documentation
EnterCombat()
void npc_beryl_sorcerer::npc_beryl_sorcererAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 545 of file zone_borean_tundra.cpp.
         {
             if (me->IsValidAttackTarget(who))
             {
                 AttackStart(who);
             }
             _events.ScheduleEvent(EVENT_FROSTBOLT, 3000, 4000);
         }
References _events, UnitAI::AttackStart(), EVENT_FROSTBOLT, Unit::IsValidAttackTarget(), CreatureAI::me, and EventMap::ScheduleEvent().
Initialize()
void npc_beryl_sorcerer::npc_beryl_sorcererAI::Initialize (void) inline
Definition at line 533 of file zone_borean_tundra.cpp.
         {
             _playerGUID.Clear();
             _chainsCast = false;
         }
References _chainsCast, _playerGUID, and ObjectGuid::Clear().
Referenced by npc_beryl_sorcererAI(), and Reset().
Reset()
void npc_beryl_sorcerer::npc_beryl_sorcererAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 539 of file zone_borean_tundra.cpp.
         {
             me->SetReactState(REACT_AGGRESSIVE);
             Initialize();
         }
References Initialize(), CreatureAI::me, REACT_AGGRESSIVE, and Creature::SetReactState().
SpellHit()
void npc_beryl_sorcerer::npc_beryl_sorcererAI::SpellHit (Unit * unit, const SpellInfo * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 555 of file zone_borean_tundra.cpp.
         {
             if (spell->Id == SPELL_ARCANE_CHAINS && !_chainsCast)
             {
                 if (Player* player = unit->ToPlayer())
                 {
                     _playerGUID = player->GetGUID();
                     _chainsCast = true;
                     _events.ScheduleEvent(EVENT_ARCANE_CHAINS, 4000);
                 }
             }
         }
References _chainsCast, _events, _playerGUID, EVENT_ARCANE_CHAINS, SpellInfo::Id, EventMap::ScheduleEvent(), SPELL_ARCANE_CHAINS, and Object::ToPlayer().
UpdateAI()
void npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI (uint32 diff) inline override virtual
Implements UnitAI.
Definition at line 568 of file zone_borean_tundra.cpp.
         {
             if (!UpdateVictim())
             {
                 return;
             }
             _events.Update(diff);
             if (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_FROSTBOLT:
                         DoCastVictim(SPELL_FROSTBOLT);
                         _events.ScheduleEvent(EVENT_FROSTBOLT, 3000, 4000);
                         break;
                     case EVENT_ARCANE_CHAINS:
                         if (me->HasAura(SPELL_ARCANE_CHAINS))
{
                             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
{
                                 me->CastSpell(player, SPELL_ARCANE_CHAINS_CHARACTER_FORCE_CAST, TriggerCastFlags(TRIGGERED_FULL_MASK & ~TRIGGERED_IGNORE_AURA_INTERRUPT_FLAGS & ~TRIGGERED_IGNORE_CAST_ITEM));
                                 player->KilledMonsterCredit(NPC_CAPTURED_BERLY_SORCERER);
                                 me->DisappearAndDie();
                             }
                         }
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, _playerGUID, Unit::CastSpell(), Creature::DisappearAndDie(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARCANE_CHAINS, EVENT_FROSTBOLT, EventMap::ExecuteEvent(), ObjectAccessor::GetPlayer(), Unit::HasAura(), CreatureAI::me, NPC_CAPTURED_BERLY_SORCERER, EventMap::ScheduleEvent(), SPELL_ARCANE_CHAINS, SPELL_ARCANE_CHAINS_CHARACTER_FORCE_CAST, SPELL_FROSTBOLT, TRIGGERED_FULL_MASK, TRIGGERED_IGNORE_AURA_INTERRUPT_FLAGS, TRIGGERED_IGNORE_CAST_ITEM, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_chainsCast
bool npc_beryl_sorcerer::npc_beryl_sorcererAI::_chainsCast private
Definition at line 604 of file zone_borean_tundra.cpp.
Referenced by Initialize(), and SpellHit().
_events
EventMap npc_beryl_sorcerer::npc_beryl_sorcererAI::_events private
Definition at line 602 of file zone_borean_tundra.cpp.
Referenced by EnterCombat(), SpellHit(), and UpdateAI().
_playerGUID
ObjectGuid npc_beryl_sorcerer::npc_beryl_sorcererAI::_playerGUID private
Definition at line 603 of file zone_borean_tundra.cpp.
Referenced by Initialize(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_borean_tundra.cpp