Azerotcore-wotlk: instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript Struct Reference
instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_gruuls_lair_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
bool SetBossState (uint32 id, EncounterState state) override
void SetData (uint32 type, uint32) override
uint32 GetData (uint32 type) const override
std::string GetSaveData () override
void Load (char const *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
uint32 _addsKilled
ObjectGuid _maulgarGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 43 of file instance_gruuls_lair.cpp.
Constructor & Destructor Documentation
instance_gruuls_lair_InstanceMapScript()
instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::instance_gruuls_lair_InstanceMapScript (Map * map) inline
Definition at line 45 of file instance_gruuls_lair.cpp.
                                                          : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTER);
             LoadDoorData(doorData);
             LoadMinionData(minionData);
             _addsKilled = 0;
         }
References _addsKilled, doorData, InstanceScript::LoadDoorData(), InstanceScript::LoadMinionData(), MAX_ENCOUNTER, minionData, and InstanceScript::SetBossNumber().
Member Function Documentation
GetData()
uint32 instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 123 of file instance_gruuls_lair.cpp.
         {
             if (type == DATA_ADDS_KILLED)
                 return _addsKilled;
             return 0;
         }
References _addsKilled, and DATA_ADDS_KILLED.
GetSaveData()
std::string instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 130 of file instance_gruuls_lair.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "G L " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::Load (char const * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 141 of file instance_gruuls_lair.cpp.
         {
             if (!str)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(str);
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'G' && dataHead2 == 'L')
             {
                 for (uint32 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_gruuls_lair.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_MAULGAR:
                     _maulgarGUID = creature->GetGUID();
                     [[fallthrough]];
                 case NPC_KROSH_FIREHAND:
                 case NPC_OLM_THE_SUMMONER:
                 case NPC_KIGGLER_THE_CRAZED:
                 case NPC_BLINDEYE_THE_SEER:
                     AddMinion(creature, true);
                     break;
             }
         }
References _maulgarGUID, InstanceScript::AddMinion(), Object::GetEntry(), Object::GetGUID(), NPC_BLINDEYE_THE_SEER, NPC_KIGGLER_THE_CRAZED, NPC_KROSH_FIREHAND, NPC_MAULGAR, and NPC_OLM_THE_SUMMONER.
OnCreatureRemove()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 70 of file instance_gruuls_lair.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_MAULGAR:
                 case NPC_KROSH_FIREHAND:
                 case NPC_OLM_THE_SUMMONER:
                 case NPC_KIGGLER_THE_CRAZED:
                 case NPC_BLINDEYE_THE_SEER:
                     AddMinion(creature, false);
                     break;
             }
         }
References InstanceScript::AddMinion(), Object::GetEntry(), NPC_BLINDEYE_THE_SEER, NPC_KIGGLER_THE_CRAZED, NPC_KROSH_FIREHAND, NPC_MAULGAR, and NPC_OLM_THE_SUMMONER.
OnGameObjectCreate()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 84 of file instance_gruuls_lair.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_MAULGAR_DOOR:
                 case GO_GRUUL_DOOR:
                     AddDoor(go, true);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_GRUUL_DOOR, and GO_MAULGAR_DOOR.
OnGameObjectRemove()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 95 of file instance_gruuls_lair.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_MAULGAR_DOOR:
                 case GO_GRUUL_DOOR:
                     AddDoor(go, false);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_GRUUL_DOOR, and GO_MAULGAR_DOOR.
SetBossState()
bool instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 106 of file instance_gruuls_lair.cpp.
         {
             if (!InstanceScript::SetBossState(id, state))
                 return false;
             if (id == DATA_MAULGAR && state == NOT_STARTED)
                 _addsKilled = 0;
             return true;
         }
References _addsKilled, DATA_MAULGAR, NOT_STARTED, and InstanceScript::SetBossState().
Referenced by Load().
SetData()
void instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
Definition at line 116 of file instance_gruuls_lair.cpp.
         {
             if (type == DATA_ADDS_KILLED)
                 if (Creature* maulgar = instance->GetCreature(_maulgarGUID))
                     maulgar->AI()->DoAction(++_addsKilled);
         }
References _addsKilled, _maulgarGUID, DATA_ADDS_KILLED, Map::GetCreature(), and InstanceScript::instance.
Member Data Documentation
_addsKilled
uint32 instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::_addsKilled protected
Definition at line 174 of file instance_gruuls_lair.cpp.
Referenced by GetData(), instance_gruuls_lair_InstanceMapScript(), SetBossState(), and SetData().
_maulgarGUID
ObjectGuid instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript::_maulgarGUID protected
Definition at line 175 of file instance_gruuls_lair.cpp.
Referenced by OnCreatureCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/GruulsLair/instance_gruuls_lair.cpp