Azerotcore-wotlk: src/common/Utilities/Timer.h File Reference
Timer.h File Reference
#include "Common.h"
#include "Duration.h"
Classes
struct IntervalTimer
struct TimeTracker
struct TimeTrackerSmall
struct PeriodicTimer
Functions
TimePoint GetApplicationStartTime ()
uint32 getMSTime ()
uint32 getMSTimeDiff (uint32 oldMSTime, uint32 newMSTime)
uint32 getMSTimeDiff (uint32 oldMSTime, TimePoint newTime)
uint32 GetMSTimeDiffToNow (uint32 oldMSTime)
Function Documentation
GetApplicationStartTime()
TimePoint GetApplicationStartTime () inline
Definition at line 24 of file Timer.h.
 {
     using namespace std::chrono;
     static const steady_clock::time_point ApplicationStartTime = steady_clock::now();
     return ApplicationStartTime;
 }
Referenced by getMSTime(), and getMSTimeDiff().
getMSTime()
uint32 getMSTime () inline
Definition at line 33 of file Timer.h.
 {
     using namespace std::chrono;
     return uint32(duration_cast<milliseconds>(steady_clock::now() - GetApplicationStartTime()).count());
 }
References count(), and GetApplicationStartTime().
Referenced by MySQLConnection::_Query(), World::_UpdateGameTime(), AuctionHouseObject::BuildListAuctionItems(), LFGUpdateRequest::call(), DisableMgr::CheckQuestDisables(), CharacterDatabaseCleaner::CleanDatabase(), BattlegroundMgr::CreateInitialBattlegrounds(), TransactionTask::Execute(), TransactionWithResultTask::Execute(), MySQLConnection::Execute(), GetMSTimeDiffToNow(), mmaps_commandscript::HandleMmapTestArea(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveUnRootAck(), FreezeDetector::Handler(), ArenaSpectator::HandleResetCommand(), PacketLog::Initialize(), OutdoorPvPMgr::InitOutdoorPvP(), WaypointMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementReferenceList(), ObjectMgr::LoadAcoreStrings(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeamMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), World::LoadAutobroadcasts(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), AchievementGlobalMgr::LoadCompletedAchievements(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), ScriptMgr::LoadDatabase(), SpellMgr::LoadDbcDataCorrections(), DisableMgr::LoadDisables(), SpellMgr::LoadEnchantCustomAttr(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectLocales(), LoadGameObjectModelList(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), World::LoadGlobalPlayerDataStore(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), GroupMgr::LoadGroups(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstances(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), LoadM2Cameras(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadPetDefaultSpells(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScriptNames(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMap(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonusess(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellInfoStore(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellSpecificAndAuraState(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), LootItemStorage::LoadStorageFromDB(), TicketMgr::LoadSurveys(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), TicketMgr::LoadTickets(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), PacketLog::LogPacket(), main(), ObjectMgr::ReturnOrDeleteOldMails(), WorldSession::SendTimeSync(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), Player::Update(), MapMgr::Update(), lfg::LFGMgr::UpdateRaidBrowser(), ObjectMgr::ValidateSpellScripts(), World::World(), and WorldUpdateLoop().
getMSTimeDiff() [1/2]
uint32 getMSTimeDiff (uint32 oldMSTime, TimePoint newTime) inline
Definition at line 53 of file Timer.h.
 {
     using namespace std::chrono;
     uint32 newMSTime = uint32(duration_cast<milliseconds>(newTime - GetApplicationStartTime()).count());
     return getMSTimeDiff(oldMSTime, newMSTime);
 }
References count(), GetApplicationStartTime(), and getMSTimeDiff().
getMSTimeDiff() [2/2]
uint32 getMSTimeDiff (uint32 oldMSTime, uint32 newMSTime) inline
Definition at line 40 of file Timer.h.
 {
     // getMSTime() have limited data range and this is case when it overflow in this tick
     if (oldMSTime > newMSTime)
     {
         return (0xFFFFFFFF - oldMSTime) + newMSTime;
     }
     else
     {
         return newMSTime - oldMSTime;
     }
 }
Referenced by MySQLConnection::_Query(), WorldObject::AddToNotify(), AuctionHouseObject::BuildListAuctionItems(), LFGUpdateRequest::call(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_AuraScript::CheckProc(), MySQLConnection::Execute(), Unit::GetDiminishing(), getMSTimeDiff(), GetMSTimeDiffToNow(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldSession::HandleBattlefieldStatusOpcode(), spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript::HandleEffectPeriodic(), mmaps_commandscript::HandleMmapTestArea(), FreezeDetector::Handler(), ArenaSpectator::HandleResetCommand(), WorldSession::HandleTimeSyncResp(), GlobalCooldownMgr::HasGlobalCooldown(), Unit::IsUnderLastManaUseEffect(), BattlegroundQueue::PlayerInvitedToBGUpdateAverageWaitTime(), boss_ignis::boss_ignisAI::SetData(), MapMgr::Update(), lfg::LFGMgr::UpdateRaidBrowser(), and WorldUpdateLoop().
GetMSTimeDiffToNow()
uint32 GetMSTimeDiffToNow (uint32 oldMSTime) inline
Definition at line 61 of file Timer.h.
 {
     return getMSTimeDiff(oldMSTime, getMSTime());
 }
References getMSTime(), and getMSTimeDiff().
Referenced by DisableMgr::CheckQuestDisables(), CharacterDatabaseCleaner::CleanDatabase(), BattlegroundMgr::CreateInitialBattlegrounds(), TransactionTask::Execute(), TransactionWithResultTask::Execute(), OutdoorPvPMgr::InitOutdoorPvP(), WaypointMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementReferenceList(), ObjectMgr::LoadAcoreStrings(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeamMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), World::LoadAutobroadcasts(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), AchievementGlobalMgr::LoadCompletedAchievements(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), ScriptMgr::LoadDatabase(), SpellMgr::LoadDbcDataCorrections(), DisableMgr::LoadDisables(), SpellMgr::LoadEnchantCustomAttr(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectLocales(), LoadGameObjectModelList(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), World::LoadGlobalPlayerDataStore(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), GroupMgr::LoadGroups(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstances(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), LoadM2Cameras(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadPetDefaultSpells(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScriptNames(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMap(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonusess(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellInfoStore(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellSpecificAndAuraState(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), LootItemStorage::LoadStorageFromDB(), TicketMgr::LoadSurveys(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), TicketMgr::LoadTickets(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), main(), ObjectMgr::ReturnOrDeleteOldMails(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), Player::Update(), and ObjectMgr::ValidateSpellScripts().