Azerotcore-wotlk: npc_tyrande_whisperwind Class Reference
npc_tyrande_whisperwind Class Reference
Public Member Functions
npc_tyrande_whisperwind ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 208 of file hyjal.cpp.
Constructor & Destructor Documentation
npc_tyrande_whisperwind()
npc_tyrande_whisperwind::npc_tyrande_whisperwind () inline
Definition at line 211 of file hyjal.cpp.
 : CreatureScript("npc_tyrande_whisperwind") { }
Member Function Documentation
GetAI()
CreatureAI* npc_tyrande_whisperwind::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 213 of file hyjal.cpp.
     {
         if (!creature->GetInstanceScript())
             return nullptr;
         hyjalAI* ai = new hyjalAI(creature);
         ai->Reset();
         ai->EnterEvadeMode();
         return ai;
     }
References hyjalAI::EnterEvadeMode(), WorldObject::GetInstanceScript(), and hyjalAI::Reset().
OnGossipHello()
bool npc_tyrande_whisperwind::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 240 of file hyjal.cpp.
     {
         hyjalAI* ai = CAST_AI(hyjalAI, creature->AI());
         uint32 AzgalorEvent = ai->GetInstanceData(DATA_AZGALOREVENT);
         // Only let them get item if Azgalor is dead.
         if (AzgalorEvent == DONE && !player->HasItemCount(ITEM_TEAR_OF_GODDESS))
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TYRANDE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         SendGossipMenuFor(player, 907, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Creature::AI(), CAST_AI, DATA_AZGALOREVENT, DONE, Object::GetGUID(), hyjalAI::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TYRANDE, GOSSIP_SENDER_MAIN, Player::HasItemCount(), ITEM_TEAR_OF_GODDESS, and SendGossipMenuFor().
OnGossipSelect()
bool npc_tyrande_whisperwind::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 224 of file hyjal.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF)
         {
             ItemPosCountVec dest;
             uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, ITEM_TEAR_OF_GODDESS, 1);
             if (msg == EQUIP_ERR_OK)
                 if (Item* item = player->StoreNewItem(dest, ITEM_TEAR_OF_GODDESS, true))
                     player->SendNewItem(item, 1, true, false, true);
             SendGossipMenuFor(player, 907, creature->GetGUID());
         }
         return true;
     }
References Player::CanStoreNewItem(), ClearGossipMenuFor(), EQUIP_ERR_OK, Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, ITEM_TEAR_OF_GODDESS, NULL_BAG, NULL_SLOT, SendGossipMenuFor(), Player::SendNewItem(), and Player::StoreNewItem().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp