Azerotcore-wotlk: Acore::WorldObjectWorker< Do > Struct Template Reference
Acore::WorldObjectWorker< Do > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectWorker (WorldObject const *searcher, Do const &_do, uint32 mapTypeMask=GRID_MAP_TYPE_MASK_ALL)
void Visit (GameObjectMapType &m)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_mapTypeMask
uint32 i_phaseMask
Do const & i_do
Detailed Description
template<class Do>
struct Acore::WorldObjectWorker< Do >
Definition at line 229 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectWorker()
template<class Do > Acore::WorldObjectWorker< Do >::WorldObjectWorker (WorldObject const * searcher, Do const & _do, uint32 mapTypeMask = GRID_MAP_TYPE_MASK_ALL) inline
Definition at line 235 of file GridNotifiers.h.
             : i_mapTypeMask(mapTypeMask), i_phaseMask(searcher->GetPhaseMask()), i_do(_do) {}
Member Function Documentation
Visit() [1/6]
template<class Do > void Acore::WorldObjectWorker< Do >::Visit (CorpseMapType & m) inline
Definition at line 264 of file GridNotifiers.h.
         {
             if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CORPSE))
                 return;
             for (CorpseMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
                 if (itr->GetSource()->InSamePhase(i_phaseMask))
                     i_do(itr->GetSource());
         }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), GRID_MAP_TYPE_MASK_CORPSE, Acore::WorldObjectWorker< Do >::i_do, Acore::WorldObjectWorker< Do >::i_mapTypeMask, and Acore::WorldObjectWorker< Do >::i_phaseMask.
Visit() [2/6]
template<class Do > void Acore::WorldObjectWorker< Do >::Visit (CreatureMapType & m) inline
Definition at line 255 of file GridNotifiers.h.
         {
             if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CREATURE))
                 return;
             for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
                 if (itr->GetSource()->InSamePhase(i_phaseMask))
                     i_do(itr->GetSource());
         }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), GRID_MAP_TYPE_MASK_CREATURE, Acore::WorldObjectWorker< Do >::i_do, Acore::WorldObjectWorker< Do >::i_mapTypeMask, and Acore::WorldObjectWorker< Do >::i_phaseMask.
Visit() [3/6]
template<class Do > void Acore::WorldObjectWorker< Do >::Visit (DynamicObjectMapType & m) inline
Definition at line 273 of file GridNotifiers.h.
         {
             if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_DYNAMICOBJECT))
                 return;
             for (DynamicObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
                 if (itr->GetSource()->InSamePhase(i_phaseMask))
                     i_do(itr->GetSource());
         }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), GRID_MAP_TYPE_MASK_DYNAMICOBJECT, Acore::WorldObjectWorker< Do >::i_do, Acore::WorldObjectWorker< Do >::i_mapTypeMask, and Acore::WorldObjectWorker< Do >::i_phaseMask.
Visit() [4/6]
template<class Do > void Acore::WorldObjectWorker< Do >::Visit (GameObjectMapType & m) inline
Definition at line 238 of file GridNotifiers.h.
         {
             if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_GAMEOBJECT))
                 return;
             for (GameObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
                 if (itr->GetSource()->InSamePhase(i_phaseMask))
                     i_do(itr->GetSource());
         }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), GRID_MAP_TYPE_MASK_GAMEOBJECT, Acore::WorldObjectWorker< Do >::i_do, Acore::WorldObjectWorker< Do >::i_mapTypeMask, and Acore::WorldObjectWorker< Do >::i_phaseMask.
Visit() [5/6]
template<class Do > template<class NOT_INTERESTED > void Acore::WorldObjectWorker< Do >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 282 of file GridNotifiers.h.
 {}
Visit() [6/6]
template<class Do > void Acore::WorldObjectWorker< Do >::Visit (PlayerMapType & m) inline
Definition at line 247 of file GridNotifiers.h.
         {
             if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_PLAYER))
                 return;
             for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
                 if (itr->GetSource()->InSamePhase(i_phaseMask))
                     i_do(itr->GetSource());
         }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), GRID_MAP_TYPE_MASK_PLAYER, Acore::WorldObjectWorker< Do >::i_do, Acore::WorldObjectWorker< Do >::i_mapTypeMask, and Acore::WorldObjectWorker< Do >::i_phaseMask.
Member Data Documentation
i_do
template<class Do > Do const& Acore::WorldObjectWorker< Do >::i_do
Definition at line 233 of file GridNotifiers.h.
Referenced by Acore::WorldObjectWorker< Do >::Visit().
i_mapTypeMask
template<class Do > uint32 Acore::WorldObjectWorker< Do >::i_mapTypeMask
Definition at line 231 of file GridNotifiers.h.
Referenced by Acore::WorldObjectWorker< Do >::Visit().
i_phaseMask
template<class Do > uint32 Acore::WorldObjectWorker< Do >::i_phaseMask
Definition at line 232 of file GridNotifiers.h.
Referenced by Acore::WorldObjectWorker< Do >::Visit().
The documentation for this struct was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h