Azerotcore-wotlk: go_elune_fire Class Reference
go_elune_fire Class Reference
Public Member Functions
go_elune_fire ()
bool OnGossipHello (Player *, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 594 of file zone_winterspring.cpp.
Constructor & Destructor Documentation
go_elune_fire()
go_elune_fire::go_elune_fire () inline
Definition at line 597 of file zone_winterspring.cpp.
 : GameObjectScript("go_elune_fire") { }
Member Function Documentation
OnGossipHello()
bool go_elune_fire::OnGossipHello (Player * , GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 599 of file zone_winterspring.cpp.
     {
         // Check if we are using the torches or the altar
         bool isAltar = false;
         if (go->GetEntry() == GO_ELUNE_ALTAR)
             isAltar = true;
         if (Creature* ranshalla = GetClosestCreatureWithEntry(go, NPC_RANSHALLA, 10.0f))
         {
             if (npc_ranshalla::npc_ranshallaAI* escortAI = dynamic_cast<npc_ranshalla::npc_ranshallaAI*>(ranshalla->AI()))
                 escortAI->DoContinueEscort(isAltar);
         }
         go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
         return false;
     }
References GAMEOBJECT_FLAGS, GetClosestCreatureWithEntry(), Object::GetEntry(), GO_ELUNE_ALTAR, GO_FLAG_NOT_SELECTABLE, NPC_RANSHALLA, and Object::SetFlag().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_winterspring.cpp