Azerotcore-wotlk: LogMessage Struct Reference
LogMessage Struct Reference
#include <LogMessage.h>
Public Member Functions
LogMessage (LogLevel _level, std::string const &_type, std::string &&_text)
LogMessage (LogLevel _level, std::string const &_type, std::string &&_text, std::string &&_param1)
LogMessage (LogMessage const &)=delete
LogMessage & operator= (LogMessage const &)=delete
std::string getTimeStr () const
uint32 Size () const
@ Returns size of the log message content in bytes
Static Public Member Functions
static std::string getTimeStr (time_t time)
Public Attributes
LogLevel const level
std::string const type
std::string const text
std::string prefix
std::string param1
time_t mtime
Detailed Description
Definition at line 26 of file LogMessage.h.
Constructor & Destructor Documentation
LogMessage() [1/3]
LogMessage::LogMessage (LogLevel _level, std::string const & _type, std::string && _text)
Definition at line 22 of file LogMessage.cpp.
     : level(_level), type(_type), text(std::forward<std::string>(_text)), mtime(time(nullptr))
 {
 }
LogMessage() [2/3]
LogMessage::LogMessage (LogLevel _level, std::string const & _type, std::string && _text, std::string && _param1)
Definition at line 27 of file LogMessage.cpp.
     : level(_level), type(_type), text(std::forward<std::string>(_text)), param1(std::forward<std::string>(_param1)), mtime(time(nullptr))
 {
 }
LogMessage() [3/3]
LogMessage::LogMessage (LogMessage const &) delete
Member Function Documentation
getTimeStr() [1/2]
std::string LogMessage::getTimeStr () const
Definition at line 39 of file LogMessage.cpp.
 {
     return getTimeStr(mtime);
 }
References mtime.
Referenced by AppenderFile::OpenFile().
getTimeStr() [2/2]
std::string LogMessage::getTimeStr (time_t time) static
Definition at line 32 of file LogMessage.cpp.
 {
     tm aTm;
     localtime_r(&time, &aTm);
     return Acore::StringFormat("%04d-%02d-%02d_%02d:%02d:%02d", aTm.tm_year + 1900, aTm.tm_mon + 1, aTm.tm_mday, aTm.tm_hour, aTm.tm_min, aTm.tm_sec);
 }
References localtime_r(), and Acore::StringFormat().
operator=()
LogMessage& LogMessage::operator= (LogMessage const &) delete
Size()
uint32 LogMessage::Size () const inline
@ Returns size of the log message content in bytes
Definition at line 45 of file LogMessage.h.
     {
         return static_cast<uint32>(prefix.size() + text.size());
     }
References prefix, and text.
Member Data Documentation
level
LogLevel const LogMessage::level
Definition at line 37 of file LogMessage.h.
Referenced by CreateAppender().
mtime
time_t LogMessage::mtime
Definition at line 42 of file LogMessage.h.
Referenced by getTimeStr().
param1
std::string LogMessage::param1
Definition at line 41 of file LogMessage.h.
prefix
std::string LogMessage::prefix
Definition at line 40 of file LogMessage.h.
Referenced by Size().
text
std::string const LogMessage::text
Definition at line 39 of file LogMessage.h.
Referenced by Size().
type
std::string const LogMessage::type
Definition at line 38 of file LogMessage.h.
The documentation for this struct was generated from the following files:
src/common/Logging/LogMessage.h
src/common/Logging/LogMessage.cpp