Azerotcore-wotlk: formatter< detail::bigint > Struct Reference
formatter< detail::bigint > Struct Reference
#include <format-inl.h>
Public Member Functions
FMT_CONSTEXPR format_parse_context::iterator parse (format_parse_context &ctx)
format_context::iterator format (const detail::bigint &n, format_context &ctx)
Detailed Description
Definition at line 2501 of file format-inl.h.
Member Function Documentation
format()
format_context::iterator formatter< detail::bigint >::format (const detail::bigint & n, format_context & ctx) inline
Definition at line 2507 of file format-inl.h.
{
     auto out = ctx.out();
     bool first = true;
     for (auto i = n.bigits_.size(); i > 0; --i) {
       auto value = n.bigits_[i - 1u];
       if (first) {
         out = format_to(out, FMT_STRING("{:x}"), value);
         first = false;
         continue;
       }
       out = format_to(out, FMT_STRING("{:08x}"), value);
     }
     if (n.exp_ > 0)
       out = format_to(out, FMT_STRING("p{}"),
                       n.exp_ * detail::bigint::bigit_bits);
     return out;
   }
References detail::bigint::bigit_bits, detail::bigint::bigits_, detail::bigint::exp_, detail::first(), FMT_STRING, format_to(), and basic_format_context< OutputIt, Char >::out().
parse()
FMT_CONSTEXPR format_parse_context::iterator formatter< detail::bigint >::parse (format_parse_context & ctx) inline
Definition at line 2502 of file format-inl.h.
{
     return ctx.begin();
   }
References basic_format_parse_context< Char, ErrorHandler >::begin().
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/format-inl.h