Azerotcore-wotlk: AsyncAuctionListingMgr Class Reference
AsyncAuctionListingMgr Class Reference
#include <AsyncAuctionListing.h>
Static Public Member Functions
static void Update (uint32 diff)
static uint32 GetDiff ()
static void ResetDiff ()
static bool IsAuctionListingAllowed ()
static void SetAuctionListingAllowed (bool a)
static std::list< AuctionListItemsDelayEvent > & GetList ()
static std::list< AuctionListItemsDelayEvent > & GetTempList ()
static std::mutex & GetLock ()
static std::mutex & GetTempLock ()
Static Private Attributes
static uint32 auctionListingDiff = 0
static bool auctionListingAllowed = false
static std::list< AuctionListItemsDelayEvent > auctionListingList
static std::list< AuctionListItemsDelayEvent > auctionListingListTemp
static std::mutex auctionListingLock
static std::mutex auctionListingTempLock
Detailed Description
Definition at line 67 of file AsyncAuctionListing.h.
Member Function Documentation
GetDiff()
static uint32 AsyncAuctionListingMgr::GetDiff () inline static
Definition at line 71 of file AsyncAuctionListing.h.
 { return auctionListingDiff; }
References auctionListingDiff.
Referenced by AuctionListingRunnable().
GetList()
static std::list<AuctionListItemsDelayEvent>& AsyncAuctionListingMgr::GetList () inline static
Definition at line 76 of file AsyncAuctionListing.h.
 { return auctionListingList; }
References auctionListingList.
Referenced by AuctionListingRunnable().
GetLock()
static std::mutex& AsyncAuctionListingMgr::GetLock () inline static
Definition at line 78 of file AsyncAuctionListing.h.
 { return auctionListingLock; }
References auctionListingLock.
Referenced by AuctionListingRunnable(), and World::Update().
GetTempList()
static std::list<AuctionListItemsDelayEvent>& AsyncAuctionListingMgr::GetTempList () inline static
Definition at line 77 of file AsyncAuctionListing.h.
 { return auctionListingListTemp; }
References auctionListingListTemp.
Referenced by AuctionListingRunnable(), and WorldSession::HandleAuctionListItems().
GetTempLock()
static std::mutex& AsyncAuctionListingMgr::GetTempLock () inline static
Definition at line 79 of file AsyncAuctionListing.h.
 { return auctionListingTempLock; }
References auctionListingTempLock.
Referenced by AuctionListingRunnable(), and WorldSession::HandleAuctionListItems().
IsAuctionListingAllowed()
static bool AsyncAuctionListingMgr::IsAuctionListingAllowed () inline static
Definition at line 73 of file AsyncAuctionListing.h.
 { return auctionListingAllowed; }
References auctionListingAllowed.
Referenced by AuctionListingRunnable(), and AuctionHouseObject::BuildListAuctionItems().
ResetDiff()
static void AsyncAuctionListingMgr::ResetDiff () inline static
Definition at line 72 of file AsyncAuctionListing.h.
 { auctionListingDiff = 0; }
References auctionListingDiff.
Referenced by AuctionListingRunnable().
SetAuctionListingAllowed()
static void AsyncAuctionListingMgr::SetAuctionListingAllowed (bool a) inline static
Definition at line 74 of file AsyncAuctionListing.h.
 { auctionListingAllowed = a; }
References auctionListingAllowed.
Referenced by World::Update().
Update()
static void AsyncAuctionListingMgr::Update (uint32 diff) inline static
Definition at line 70 of file AsyncAuctionListing.h.
 { auctionListingDiff += diff; }
References auctionListingDiff.
Referenced by World::Update().
Member Data Documentation
auctionListingAllowed
bool AsyncAuctionListingMgr::auctionListingAllowed = false static private
Definition at line 83 of file AsyncAuctionListing.h.
Referenced by IsAuctionListingAllowed(), and SetAuctionListingAllowed().
auctionListingDiff
uint32 AsyncAuctionListingMgr::auctionListingDiff = 0 static private
Definition at line 82 of file AsyncAuctionListing.h.
Referenced by GetDiff(), ResetDiff(), and Update().
auctionListingList
std::list< AuctionListItemsDelayEvent > AsyncAuctionListingMgr::auctionListingList static private
Definition at line 84 of file AsyncAuctionListing.h.
Referenced by GetList().
auctionListingListTemp
std::list< AuctionListItemsDelayEvent > AsyncAuctionListingMgr::auctionListingListTemp static private
Definition at line 85 of file AsyncAuctionListing.h.
Referenced by GetTempList().
auctionListingLock
std::mutex AsyncAuctionListingMgr::auctionListingLock static private
Definition at line 86 of file AsyncAuctionListing.h.
Referenced by GetLock().
auctionListingTempLock
std::mutex AsyncAuctionListingMgr::auctionListingTempLock static private
Definition at line 87 of file AsyncAuctionListing.h.
Referenced by GetTempLock().
The documentation for this class was generated from the following files:
src/server/game/Misc/AsyncAuctionListing.h
src/server/game/Misc/AsyncAuctionListing.cpp