Azerotcore-wotlk: boss_epoch_hunter::boss_epoch_hunterAI Struct Reference
boss_epoch_hunter::boss_epoch_hunterAI Struct Reference
Public Member Functions
boss_epoch_hunterAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 50 of file boss_epoch_hunter.cpp.
Constructor & Destructor Documentation
boss_epoch_hunterAI()
boss_epoch_hunter::boss_epoch_hunterAI::boss_epoch_hunterAI (Creature * creature) inline
Definition at line 52 of file boss_epoch_hunter.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
EnterCombat()
void boss_epoch_hunter::boss_epoch_hunterAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 60 of file boss_epoch_hunter.cpp.
         {
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_SPELL_SAND_BREATH, 8000);
             events.ScheduleEvent(EVENT_SPELL_IMPENDING_DEATH, 2000);
             events.ScheduleEvent(EVENT_SPELL_DISRUPTION, 20000);
             events.ScheduleEvent(EVENT_SPELL_WING_BUFFET, 14000);
         }
References EVENT_SPELL_DISRUPTION, EVENT_SPELL_IMPENDING_DEATH, EVENT_SPELL_SAND_BREATH, EVENT_SPELL_WING_BUFFET, SAY_AGGRO, and CreatureAI::Talk().
JustDied()
void boss_epoch_hunter::boss_epoch_hunterAI::JustDied (Unit * killer) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 76 of file boss_epoch_hunter.cpp.
         {
             if (killer == me)
                 return;
             Talk(SAY_DEATH);
             me->GetInstanceScript()->SetData(DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_EPOCH_KILLED);
             if (Creature* taretha = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(DATA_TARETHA_GUID)))
                 taretha->AI()->DoAction(me->GetEntry());
         }
References DATA_ESCORT_PROGRESS, DATA_TARETHA_GUID, ENCOUNTER_PROGRESS_EPOCH_KILLED, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), ScriptedAI::me, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
KilledUnit()
void boss_epoch_hunter::boss_epoch_hunterAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 70 of file boss_epoch_hunter.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_epoch_hunter::boss_epoch_hunterAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 56 of file boss_epoch_hunter.cpp.
         {
         }
UpdateAI()
void boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 86 of file boss_epoch_hunter.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_SAND_BREATH:
                     if (roll_chance_i(50))
                         Talk(SAY_BREATH);
                     me->CastSpell(me->GetVictim(), SPELL_SAND_BREATH, false);
                     events.ScheduleEvent(EVENT_SPELL_SAND_BREATH, 20000);
                     break;
                 case EVENT_SPELL_IMPENDING_DEATH:
                     me->CastSpell(me->GetVictim(), SPELL_IMPENDING_DEATH, false);
                     events.ScheduleEvent(EVENT_SPELL_IMPENDING_DEATH, 30000);
                     break;
                 case EVENT_SPELL_WING_BUFFET:
                     me->CastSpell(me, SPELL_WING_BUFFET, false);
                     events.ScheduleEvent(EVENT_SPELL_WING_BUFFET, 30000);
                     break;
                 case EVENT_SPELL_DISRUPTION:
                     me->CastSpell(me, SPELL_MAGIC_DISRUPTION_AURA, false);
                     events.ScheduleEvent(EVENT_SPELL_DISRUPTION, 30000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_SPELL_DISRUPTION, EVENT_SPELL_IMPENDING_DEATH, EVENT_SPELL_SAND_BREATH, EVENT_SPELL_WING_BUFFET, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, roll_chance_i(), SAY_BREATH, SPELL_IMPENDING_DEATH, SPELL_MAGIC_DISRUPTION_AURA, SPELL_SAND_BREATH, SPELL_WING_BUFFET, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_epoch_hunter::boss_epoch_hunterAI::events
Definition at line 54 of file boss_epoch_hunter.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_epoch_hunter.cpp