Azerotcore-wotlk: MalleableGooSelector Struct Reference
MalleableGooSelector Struct Reference
Public Member Functions
MalleableGooSelector (Unit const *unit)
bool operator() (Unit const *target) const
Public Attributes
const Unit * me
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 204 of file boss_professor_putricide.cpp.
Constructor & Destructor Documentation
MalleableGooSelector()
MalleableGooSelector::MalleableGooSelector (Unit const * unit) inline
Definition at line 207 of file boss_professor_putricide.cpp.
 : me(unit) {}
Member Function Documentation
operator()()
bool MalleableGooSelector::operator() (Unit const * target) const inline
Definition at line 209 of file boss_professor_putricide.cpp.
     {
         if (!me || !target || target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (me->IsWithinCombatRange(target, 7.0f))
             return false;
         return me->IsValidAttackTarget(target);
     }
References Object::GetTypeId(), Unit::IsValidAttackTarget(), Unit::IsWithinCombatRange(), me, and TYPEID_PLAYER.
Member Data Documentation
me
const Unit* MalleableGooSelector::me
Definition at line 206 of file boss_professor_putricide.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp