Azerotcore-wotlk: ChunkedData Class Reference
ChunkedData Class Reference
#include <ChunkedData.h>
Public Member Functions
ChunkedData (FILE *stream, uint32 maxLength, uint32 chunksHint=300)
ChunkedData (const std::string &file, uint32 chunksHint=300)
~ChunkedData ()
int GetFirstIndex (const std::string &name)
Chunk * GetChunkByName (const std::string &name)
void Load (uint32 maxLength, uint32 chunksHint)
Public Attributes
std::vector< Chunk * > Chunks
FILE * Stream
Detailed Description
Definition at line 24 of file ChunkedData.h.
Constructor & Destructor Documentation
ChunkedData() [1/2]
ChunkedData::ChunkedData (FILE * stream, uint32 maxLength, uint32 chunksHint = 300)
Definition at line 24 of file ChunkedData.cpp.
                                                                               :
     Stream(stream)
 {
     if (!Stream)
         return;
     Load(maxLength, chunksHint);
 }
References Load(), and Stream.
ChunkedData() [2/2]
ChunkedData::ChunkedData (const std::string & file, uint32 chunksHint = 300)
Definition at line 32 of file ChunkedData.cpp.
 {
     Stream = MPQHandler->GetFile(file);
     if (!Stream)
         return;
     Load(0, chunksHint);
 }
References mpq::file, MPQMgr::GetFile(), Load(), MPQHandler, and Stream.
~ChunkedData()
ChunkedData::~ChunkedData ()
Definition at line 83 of file ChunkedData.cpp.
 {
     for (std::vector<Chunk*>::iterator itr = Chunks.begin(); itr != Chunks.end(); ++itr)
         delete *itr;
     Chunks.clear();
     if (Stream)
         fclose(Stream);
 }
References Chunks, and Stream.
Member Function Documentation
GetChunkByName()
Chunk * ChunkedData::GetChunkByName (const std::string & name)
Definition at line 75 of file ChunkedData.cpp.
 {
     for (uint32 i = 0; i < Chunks.size(); ++i)
         if (Chunks[i]->Name == name)
             return Chunks[i];
     return nullptr;
 }
References Chunks, and name.
Referenced by DoodadHandler::DoodadHandler(), LiquidHandler::HandleNewLiquid(), WorldModelHandler::ReadDefinitions(), WorldModelGroup::ReadLiquid(), WorldModelGroup::ReadMaterials(), WorldModelHandler::ReadModelPaths(), WorldModelGroup::ReadNormals(), WorldModelGroup::ReadTriangles(), and WorldModelGroup::ReadVertices().
GetFirstIndex()
int ChunkedData::GetFirstIndex (const std::string & name)
Definition at line 67 of file ChunkedData.cpp.
 {
     for (uint32 i = 0; i < Chunks.size(); ++i)
         if (Chunks[i]->Name == name)
             return i;
     return -1;
 }
References Chunks, and name.
Load()
void ChunkedData::Load (uint32 maxLength, uint32 chunksHint)
Definition at line 40 of file ChunkedData.cpp.
 {
     if (!maxLength)
         maxLength = Utils::Size(Stream);
     Chunks.reserve(chunksHint);
     uint32 baseOffset = ftell(Stream);
     uint32 calcOffset = 0;
     while ((calcOffset + baseOffset) < Utils::Size(Stream) && (calcOffset < maxLength))
     {
         char nameBytes[5];
         uint32 read = fread(&nameBytes, sizeof(char), 4, Stream);
         nameBytes[read] = '\0';
         std::string name = std::string(nameBytes);
         // Utils::Reverse(nameBytes);
         name = std::string(name.rbegin(), name.rend());
         uint32 length;
         if (fread(&length, sizeof(uint32), 1, Stream) != 1)
             continue;
         calcOffset += 8;
         Chunks.push_back(new Chunk(name.c_str(), length, calcOffset + baseOffset, Stream));
         calcOffset += length;
         // save an extra seek at the end
         if ((calcOffset + baseOffset) < Utils::Size(Stream) && calcOffset < maxLength)
             fseek(Stream, length, SEEK_CUR);
     }
 }
References Chunks, G3D::length(), name, read, SEEK_CUR, Utils::Size(), and Stream.
Referenced by ChunkedData().
Member Data Documentation
Chunks
std::vector<Chunk*> ChunkedData::Chunks
Definition at line 35 of file ChunkedData.h.
Referenced by GetChunkByName(), GetFirstIndex(), Load(), and ~ChunkedData().
Stream
FILE* ChunkedData::Stream
Definition at line 36 of file ChunkedData.h.
Referenced by TileBuilder::BuildTiled(), ChunkedData(), Load(), and ~ChunkedData().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/ChunkedData.h
src/tools/mesh_extractor/ChunkedData.cpp