Azerotcore-wotlk: achievement_cant_do_that_while_stunned Class Reference
achievement_cant_do_that_while_stunned Class Reference
Public Member Functions
achievement_cant_do_that_while_stunned ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 953 of file boss_assembly_of_iron.cpp.
Constructor & Destructor Documentation
achievement_cant_do_that_while_stunned()
achievement_cant_do_that_while_stunned::achievement_cant_do_that_while_stunned () inline
Definition at line 956 of file boss_assembly_of_iron.cpp.
 : AchievementCriteriaScript("achievement_cant_do_that_while_stunned") {}
Member Function Documentation
OnCheck()
bool achievement_cant_do_that_while_stunned::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 958 of file boss_assembly_of_iron.cpp.
     {
         bool allow = target && target->GetAuraCount(SPELL_SUPERCHARGE) >= 2;
         if (!allow)
             return false;
         if (InstanceScript* instance = target->GetInstanceScript())
             if (Creature* cr = ObjectAccessor::GetCreature(*target, instance->GetGuidData(DATA_BRUNDIR)))
                 return cr->AI()->GetData(DATA_BRUNDIR);
         return false;
     }
References DATA_BRUNDIR, Unit::GetAuraCount(), ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and SPELL_SUPERCHARGE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp