Azerotcore-wotlk: BfGraveyard Class Reference
BfGraveyard Class Reference
#include <Battlefield.h>
Public Member Functions
BfGraveyard (Battlefield *Bf)
void GiveControlTo (TeamId team)
TeamId GetControlTeamId () const
float GetDistance (Player *player)
void Initialize (TeamId startcontrol, uint32 gy)
void SetSpirit (Creature *spirit, TeamId team)
void AddPlayer (ObjectGuid player_guid)
void RemovePlayer (ObjectGuid player_guid)
void Resurrect ()
void RelocateDeadPlayers ()
bool HasNpc (ObjectGuid guid)
bool HasPlayer (ObjectGuid guid) const
uint32 GetGraveyardId () const
Protected Attributes
TeamId m_ControlTeam
uint32 m_GraveyardId
ObjectGuid m_SpiritGuide [2]
GuidUnorderedSet m_ResurrectQueue
Battlefield * m_Bf
Detailed Description
Definition at line 146 of file Battlefield.h.
Constructor & Destructor Documentation
BfGraveyard()
BfGraveyard::BfGraveyard (Battlefield * Bf)
Definition at line 673 of file Battlefield.cpp.
 {
     m_Bf = battlefield;
     m_GraveyardId = 0;
     m_ControlTeam = TEAM_NEUTRAL;
     m_ResurrectQueue.clear();
 }
References m_Bf, m_ControlTeam, m_GraveyardId, m_ResurrectQueue, and TEAM_NEUTRAL.
Member Function Documentation
AddPlayer()
void BfGraveyard::AddPlayer (ObjectGuid player_guid)
Definition at line 705 of file Battlefield.cpp.
 {
     if (!m_ResurrectQueue.count(playerGuid))
     {
         m_ResurrectQueue.insert(playerGuid);
         if (Player* player = ObjectAccessor::FindPlayer(playerGuid))
             player->CastSpell(player, SPELL_WAITING_FOR_RESURRECT, true);
     }
 }
References ObjectAccessor::FindPlayer(), m_ResurrectQueue, and SPELL_WAITING_FOR_RESURRECT.
GetControlTeamId()
TeamId BfGraveyard::GetControlTeamId () const inline
Definition at line 153 of file Battlefield.h.
 { return m_ControlTeam; }
References m_ControlTeam.
GetDistance()
float BfGraveyard::GetDistance (Player * player)
Definition at line 699 of file Battlefield.cpp.
 {
     const GraveyardStruct* safeLoc = sGraveyard->GetGraveyard(m_GraveyardId);
     return player->GetDistance2d(safeLoc->x, safeLoc->y);
 }
References WorldObject::GetDistance2d(), m_GraveyardId, sGraveyard, GraveyardStruct::x, and GraveyardStruct::y.
GetGraveyardId()
uint32 BfGraveyard::GetGraveyardId () const inline
Definition at line 194 of file Battlefield.h.
 { return m_GraveyardId; }
References m_GraveyardId.
Referenced by Battlefield::GetClosestGraveyard().
GiveControlTo()
void BfGraveyard::GiveControlTo (TeamId team)
Definition at line 754 of file Battlefield.cpp.
 {
     m_ControlTeam = team;
     // Teleport to other graveyard, player witch were on this graveyard
     RelocateDeadPlayers();
 }
References m_ControlTeam, and RelocateDeadPlayers().
Referenced by WGWorkshop::GiveControlTo(), and WGWorkshop::UpdateGraveyardAndWorkshop().
HasNpc()
bool BfGraveyard::HasNpc (ObjectGuid guid) inline
Definition at line 177 of file Battlefield.h.
     {
         if (!m_SpiritGuide[0] && !m_SpiritGuide[1])
             return false;
         // performance
         /*if (!ObjectAccessor::FindUnit(m_SpiritGuide[0]) &&
             !ObjectAccessor::FindUnit(m_SpiritGuide[1]))
             return false;*/
         return (m_SpiritGuide[0] == guid || m_SpiritGuide[1] == guid);
     }
References m_SpiritGuide.
HasPlayer()
bool BfGraveyard::HasPlayer (ObjectGuid guid) const inline
Definition at line 191 of file Battlefield.h.
 { return m_ResurrectQueue.find(guid) != m_ResurrectQueue.end(); }
References m_ResurrectQueue.
Initialize()
void BfGraveyard::Initialize (TeamId startcontrol, uint32 gy)
Definition at line 681 of file Battlefield.cpp.
 {
     m_ControlTeam = startControl;
     m_GraveyardId = graveyardId;
 }
References m_ControlTeam, and m_GraveyardId.
Referenced by BattlefieldWG::SetupBattlefield().
RelocateDeadPlayers()
void BfGraveyard::RelocateDeadPlayers ()
Definition at line 761 of file Battlefield.cpp.
 {
     GraveyardStruct const* closestGrave = nullptr;
     for (GuidUnorderedSet::const_iterator itr = m_ResurrectQueue.begin(); itr != m_ResurrectQueue.end(); ++itr)
     {
         Player* player = ObjectAccessor::FindPlayer(*itr);
         if (!player)
             continue;
         if (closestGrave)
             player->TeleportTo(player->GetMapId(), closestGrave->x, closestGrave->y, closestGrave->z, player->GetOrientation());
         else
         {
             closestGrave = m_Bf->GetClosestGraveyard(player);
             if (closestGrave)
                 player->TeleportTo(player->GetMapId(), closestGrave->x, closestGrave->y, closestGrave->z, player->GetOrientation());
         }
     }
 }
References ObjectAccessor::FindPlayer(), Battlefield::GetClosestGraveyard(), WorldLocation::GetMapId(), Position::GetOrientation(), m_Bf, m_ResurrectQueue, Player::TeleportTo(), GraveyardStruct::x, GraveyardStruct::y, and GraveyardStruct::z.
Referenced by GiveControlTo().
RemovePlayer()
void BfGraveyard::RemovePlayer (ObjectGuid player_guid)
Definition at line 716 of file Battlefield.cpp.
 {
     m_ResurrectQueue.erase(m_ResurrectQueue.find(playerGuid));
     if (Player* player = ObjectAccessor::FindPlayer(playerGuid))
         player->RemoveAurasDueToSpell(SPELL_WAITING_FOR_RESURRECT);
 }
References ObjectAccessor::FindPlayer(), m_ResurrectQueue, and SPELL_WAITING_FOR_RESURRECT.
Resurrect()
void BfGraveyard::Resurrect ()
Definition at line 724 of file Battlefield.cpp.
 {
     if (m_ResurrectQueue.empty())
         return;
     for (GuidUnorderedSet::const_iterator itr = m_ResurrectQueue.begin(); itr != m_ResurrectQueue.end(); ++itr)
     {
         // Get player object from his guid
         Player* player = ObjectAccessor::FindPlayer(*itr);
         if (!player)
             continue;
         // Check  if the player is in world and on the good graveyard
         if (player->IsInWorld())
             if (Unit* spirit = ObjectAccessor::GetCreature(*player, m_SpiritGuide[m_ControlTeam]))
                 spirit->CastSpell(spirit, SPELL_SPIRIT_HEAL, true);
         // Resurect player
         player->CastSpell(player, SPELL_RESURRECTION_VISUAL, true);
         player->ResurrectPlayer(1.0f);
         player->CastSpell(player, 6962, true);
         player->CastSpell(player, SPELL_SPIRIT_HEAL_MANA, true);
         player->SpawnCorpseBones(false);
     }
     m_ResurrectQueue.clear();
 }
References Unit::CastSpell(), ObjectAccessor::FindPlayer(), ObjectAccessor::GetCreature(), Object::IsInWorld(), m_ControlTeam, m_ResurrectQueue, m_SpiritGuide, Player::ResurrectPlayer(), Player::SpawnCorpseBones(), SPELL_RESURRECTION_VISUAL, SPELL_SPIRIT_HEAL, and SPELL_SPIRIT_HEAL_MANA.
SetSpirit()
void BfGraveyard::SetSpirit (Creature * spirit, TeamId team)
Definition at line 687 of file Battlefield.cpp.
 {
     if (!spirit)
     {
         LOG_ERROR("bg.battlefield", "BfGraveyard::SetSpirit: Invalid Spirit.");
         return;
     }
     m_SpiritGuide[team] = spirit->GetGUID();
     spirit->SetReactState(REACT_PASSIVE);
 }
References Object::GetGUID(), LOG_ERROR, m_SpiritGuide, REACT_PASSIVE, and Creature::SetReactState().
Member Data Documentation
m_Bf
Battlefield* BfGraveyard::m_Bf protected
Definition at line 201 of file Battlefield.h.
Referenced by BfGraveyard(), BfGraveyardWG::BfGraveyardWG(), and RelocateDeadPlayers().
m_ControlTeam
TeamId BfGraveyard::m_ControlTeam protected
Definition at line 197 of file Battlefield.h.
Referenced by BfGraveyard(), GetControlTeamId(), GiveControlTo(), Initialize(), and Resurrect().
m_GraveyardId
uint32 BfGraveyard::m_GraveyardId protected
Definition at line 198 of file Battlefield.h.
Referenced by BfGraveyard(), GetDistance(), GetGraveyardId(), and Initialize().
m_ResurrectQueue
GuidUnorderedSet BfGraveyard::m_ResurrectQueue protected
Definition at line 200 of file Battlefield.h.
Referenced by AddPlayer(), BfGraveyard(), HasPlayer(), RelocateDeadPlayers(), RemovePlayer(), and Resurrect().
m_SpiritGuide
ObjectGuid BfGraveyard::m_SpiritGuide[2] protected
Definition at line 199 of file Battlefield.h.
Referenced by HasNpc(), Resurrect(), and SetSpirit().
The documentation for this class was generated from the following files:
src/server/game/Battlefield/Battlefield.h
src/server/game/Battlefield/Battlefield.cpp