Azerotcore-wotlk: npc_kayra_longmane Class Reference
npc_kayra_longmane Class Reference
Classes
struct npc_kayra_longmaneAI
Public Member Functions
npc_kayra_longmane ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 424 of file zone_zangarmarsh.cpp.
Constructor & Destructor Documentation
npc_kayra_longmane()
npc_kayra_longmane::npc_kayra_longmane () inline
Definition at line 427 of file zone_zangarmarsh.cpp.
 : CreatureScript("npc_kayra_longmane") { }
Member Function Documentation
GetAI()
CreatureAI* npc_kayra_longmane::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 480 of file zone_zangarmarsh.cpp.
     {
         return new npc_kayra_longmaneAI(creature);
     }
OnQuestAccept()
bool npc_kayra_longmane::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 468 of file zone_zangarmarsh.cpp.
     {
         if (quest->GetQuestId() == QUEST_ESCAPE_FROM)
         {
             creature->AI()->Talk(SAY_START, player);
             if (npc_escortAI* pEscortAI = CAST_AI(npc_kayra_longmane::npc_kayra_longmaneAI, creature->AI()))
                 pEscortAI->Start(false, false, player->GetGUID());
         }
         return true;
     }
References Creature::AI(), CAST_AI, Object::GetGUID(), Quest::GetQuestId(), QUEST_ESCAPE_FROM, SAY_START, and CreatureAI::Talk().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_zangarmarsh.cpp