Azerotcore-wotlk: deps/gsoap/soapStub.h File Reference
soapStub.h File Reference
#include "stdsoap2.h"
Classes
struct ns1__executeCommandResponse
struct ns1__executeCommand
struct SOAP_ENV__Header
struct SOAP_ENV__Code
struct SOAP_ENV__Detail
struct SOAP_ENV__Reason
struct SOAP_ENV__Fault
Macros
#define SOAP_TYPE_ns1__executeCommandResponse (9)
#define SOAP_TYPE_ns1__executeCommand (10)
#define SOAP_TYPE_SOAP_ENV__Header (11)
#define SOAP_TYPE_SOAP_ENV__Code (12)
#define SOAP_TYPE_SOAP_ENV__Detail (14)
#define SOAP_TYPE_SOAP_ENV__Reason (17)
#define SOAP_TYPE_SOAP_ENV__Fault (18)
#define SOAP_TYPE__XML (5)
#define SOAP_TYPE__QName (6)
#define SOAP_TYPE_byte (3)
#define SOAP_TYPE_int (1)
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (20)
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (19)
#define SOAP_TYPE_PointerToSOAP_ENV__Code (13)
#define SOAP_TYPE_PointerTostring (7)
#define SOAP_TYPE_string (4)
Typedefs
typedef char * _XML
typedef char * _QName
Functions
SOAP_FMAC5 int SOAP_FMAC6 ns1__executeCommand (struct soap *, char *command, char **result)
SOAP_FMAC5 int SOAP_FMAC6 soap_serve (struct soap *)
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request (struct soap *)
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__executeCommand (struct soap *)
Macro Definition Documentation
SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
Definition at line 209 of file soapStub.h.
SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
Definition at line 203 of file soapStub.h.
SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
Definition at line 222 of file soapStub.h.
SOAP_TYPE_int
#define SOAP_TYPE_int (1)
Definition at line 227 of file soapStub.h.
SOAP_TYPE_ns1__executeCommand
#define SOAP_TYPE_ns1__executeCommand (10)
Definition at line 59 of file soapStub.h.
SOAP_TYPE_ns1__executeCommandResponse
#define SOAP_TYPE_ns1__executeCommandResponse (9)
Definition at line 41 of file soapStub.h.
SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (13)
Definition at line 277 of file soapStub.h.
SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (19)
Definition at line 272 of file soapStub.h.
SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (20)
Definition at line 267 of file soapStub.h.
SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
Definition at line 282 of file soapStub.h.
SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (12)
Definition at line 95 of file soapStub.h.
SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (14)
Definition at line 118 of file soapStub.h.
SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (18)
Definition at line 161 of file soapStub.h.
SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (11)
Definition at line 78 of file soapStub.h.
SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (17)
Definition at line 141 of file soapStub.h.
SOAP_TYPE_string
#define SOAP_TYPE_string (4)
Definition at line 297 of file soapStub.h.
Typedef Documentation
_QName
typedef char* _QName
Definition at line 210 of file soapStub.h.
_XML
typedef char* _XML
Definition at line 204 of file soapStub.h.
Function Documentation
ns1__executeCommand()
SOAP_FMAC5 int SOAP_FMAC6 ns1__executeCommand (struct soap * soap, char * command, char ** result)
Web service operation 'ns1__executeCommand' implementation, should return SOAP_OK or error code
Definition at line 75 of file ACSoap.cpp.
 {
     // security check
     if (!soap->userid || !soap->passwd)
     {
         LOG_DEBUG("network.soap", "ACSoap: Client didn't provide login information");
         return 401;
     }
     uint32 accountId = AccountMgr::GetId(soap->userid);
     if (!accountId)
     {
         LOG_DEBUG("network", "ACSoap: Client used invalid username '%s'", soap->userid);
         return 401;
     }
     if (!AccountMgr::CheckPassword(accountId, soap->passwd))
     {
         LOG_DEBUG("network.soap", "ACSoap: invalid password for account '%s'", soap->userid);
         return 401;
     }
     if (AccountMgr::GetSecurity(accountId) < SEC_ADMINISTRATOR)
     {
         LOG_DEBUG("network.soap", "ACSoap: %s's gmlevel is too low", soap->userid);
         return 403;
     }
     if (!command || !*command)
         return soap_sender_fault(soap, "Command can not be empty", "The supplied command was an empty string");
     LOG_DEBUG("network.soap", "ACSoap: got command '%s'", command);
     SOAPCommand connection;
     // commands are executed in the world thread. We have to wait for them to be completed
     {
         // CliCommandHolder will be deleted from world, accessing after queueing is NOT save
         CliCommandHolder* cmd = new CliCommandHolder(&connection, command, &SOAPCommand::print, &SOAPCommand::commandFinished);
         sWorld->QueueCliCommand(cmd);
     }
     // Wait until the command has finished executing
     connection.finishedPromise.get_future().wait();
     // The command has finished executing already
     char* printBuffer = soap_strdup(soap, connection.m_printBuffer.c_str());
     if (connection.hasCommandSucceeded())
     {
         *result = printBuffer;
         return SOAP_OK;
     }
     else
         return soap_sender_fault(soap, printBuffer, printBuffer);
 }
References AccountMgr::CheckPassword(), SOAPCommand::commandFinished(), SOAPCommand::finishedPromise, AccountMgr::GetId(), AccountMgr::GetSecurity(), SOAPCommand::hasCommandSucceeded(), LOG_DEBUG, SOAPCommand::m_printBuffer, soap::passwd, SOAPCommand::print(), SEC_ADMINISTRATOR, SOAP_OK, soap_sender_fault(), soap_strdup(), sWorld, and soap::userid.
Referenced by soap_serve_ns1__executeCommand().
soap_serve()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve (struct soap * soap)
Definition at line 21 of file soapServer.cpp.
 {
 #ifndef WITH_FASTCGI
     soap->keep_alive = soap->max_keep_alive + 1;
 #endif
     do
     {
 #ifndef WITH_FASTCGI
         if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
             soap->keep_alive--;
 #endif
         if (soap_begin_serve(soap))
         {   if (soap->error >= SOAP_STOP)
                 continue;
             return soap->error;
         }
         if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
         {
 #ifdef WITH_FASTCGI
             soap_send_fault(soap);
 #else
             return soap_send_fault(soap);
 #endif
         }
 #ifdef WITH_FASTCGI
         soap_destroy(soap);
         soap_end(soap);
     } while (1);
 #else
     } while (soap->keep_alive);
 #endif
     return SOAP_OK;
 }
soap_serve_ns1__executeCommand()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__executeCommand (struct soap * soap)
Definition at line 65 of file soapServer.cpp.
 {   struct ns1__executeCommand soap_tmp_ns1__executeCommand;
     struct ns1__executeCommandResponse soap_tmp_ns1__executeCommandResponse;
     char * soap_tmp_string;
     soap_default_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse);
     soap_tmp_string = NULL;
     soap_tmp_ns1__executeCommandResponse.result = &soap_tmp_string;
     soap_default_ns1__executeCommand(soap, &soap_tmp_ns1__executeCommand);
     if (!soap_get_ns1__executeCommand(soap, &soap_tmp_ns1__executeCommand, "ns1:executeCommand", NULL))
         return soap->error;
     if (soap_body_end_in(soap)
      || soap_envelope_end_in(soap)
      || soap_end_recv(soap))
         return soap->error;
     soap->error = ns1__executeCommand(soap, soap_tmp_ns1__executeCommand.command, soap_tmp_ns1__executeCommandResponse.result);
     if (soap->error)
         return soap->error;
     soap->encodingStyle = NULL; /* use SOAP literal style */
     soap_serializeheader(soap);
     soap_serialize_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse);
     if (soap_begin_count(soap))
         return soap->error;
     if ((soap->mode & SOAP_IO_LENGTH))
     {   if (soap_envelope_begin_out(soap)
          || soap_putheader(soap)
          || soap_body_begin_out(soap)
          || soap_put_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse, "ns1:executeCommandResponse", "")
          || soap_body_end_out(soap)
          || soap_envelope_end_out(soap))
              return soap->error;
     };
     if (soap_end_count(soap)
      || soap_response(soap, SOAP_OK)
      || soap_envelope_begin_out(soap)
      || soap_putheader(soap)
      || soap_body_begin_out(soap)
      || soap_put_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse, "ns1:executeCommandResponse", "")
      || soap_body_end_out(soap)
      || soap_envelope_end_out(soap)
      || soap_end_send(soap))
         return soap->error;
     return soap_closesock(soap);
 }
References ns1__executeCommand::command, soap::encodingStyle, soap::error, soap::mode, ns1__executeCommand(), NULL, ns1__executeCommandResponse::result, soap_begin_count(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_default_ns1__executeCommand(), soap_default_ns1__executeCommandResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns1__executeCommand(), SOAP_IO_LENGTH, SOAP_OK, soap_put_ns1__executeCommandResponse(), soap_putheader(), soap_response(), soap_serialize_ns1__executeCommandResponse(), and soap_serializeheader().
Referenced by soap_serve_request().
soap_serve_request()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request (struct soap * soap)
Definition at line 56 of file soapServer.cpp.
 {
     (void)soap_peek_element(soap);
     if (!soap_match_tag(soap, soap->tag, "ns1:executeCommand"))
         return soap_serve_ns1__executeCommand(soap);
     return soap->error = SOAP_NO_METHOD;
 }