Azerotcore-wotlk: npc_announcer_toc10 Class Reference
npc_announcer_toc10 Class Reference
Public Member Functions
npc_announcer_toc10 ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 32 of file trial_of_the_crusader.cpp.
Constructor & Destructor Documentation
npc_announcer_toc10()
npc_announcer_toc10::npc_announcer_toc10 () inline
Definition at line 35 of file trial_of_the_crusader.cpp.
 : CreatureScript("npc_announcer_toc10") { }
Member Function Documentation
OnGossipHello()
bool npc_announcer_toc10::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 37 of file trial_of_the_crusader.cpp.
     {
         if(!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         InstanceScript* pInstance = creature->GetInstanceScript();
         if(!pInstance)
             return true;
         uint32 gossipTextId = 0;
         switch(pInstance->GetData(TYPE_INSTANCE_PROGRESS))
         {
             case INSTANCE_PROGRESS_INITIAL:
                 gossipTextId = MSG_TESTED;
                 break;
             case INSTANCE_PROGRESS_INTRO_DONE:
             case INSTANCE_PROGRESS_BEASTS_DEAD:
             case INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD:
             case INSTANCE_PROGRESS_VALKYR_DEAD:
                 gossipTextId = MSG_NEXT_STAGE;
                 break;
             case INSTANCE_PROGRESS_JARAXXUS_DEAD:
                 gossipTextId = MSG_CRUSADERS;
                 break;
             case INSTANCE_PROGRESS_DONE:
                 creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 return true;
             default:
                 return true;
         }
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, "We are ready!", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1337);
         SendGossipMenuFor(player, gossipTextId, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), ZoneScript::GetData(), Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Object::HasFlag(), INSTANCE_PROGRESS_BEASTS_DEAD, INSTANCE_PROGRESS_DONE, INSTANCE_PROGRESS_FACTION_CHAMPIONS_DEAD, INSTANCE_PROGRESS_INITIAL, INSTANCE_PROGRESS_INTRO_DONE, INSTANCE_PROGRESS_JARAXXUS_DEAD, INSTANCE_PROGRESS_VALKYR_DEAD, MSG_CRUSADERS, MSG_NEXT_STAGE, MSG_TESTED, Object::RemoveFlag(), SendGossipMenuFor(), TYPE_INSTANCE_PROGRESS, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
OnGossipSelect()
bool npc_announcer_toc10::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 73 of file trial_of_the_crusader.cpp.
     {
         if( !creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP) )
             return true;
         InstanceScript* pInstance = creature->GetInstanceScript();
         if( !pInstance )
             return true;
         if( uiAction == GOSSIP_ACTION_INFO_DEF + 1337 )
         {
             pInstance->SetData(TYPE_ANNOUNCER_GOSSIP_SELECT, 0);
             creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
         }
         CloseGossipMenuFor(player);
         return true;
     }
References CloseGossipMenuFor(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, Object::HasFlag(), Object::RemoveFlag(), ZoneScript::SetData(), TYPE_ANNOUNCER_GOSSIP_SELECT, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/trial_of_the_crusader.cpp