Azerotcore-wotlk: deps/mysqllite/include/internal/my_bit.h File Reference
my_bit.h File Reference
Functions
static uint my_bit_log2 (ulong value)
static uint my_count_bits (ulonglong v)
static uint my_count_bits_ushort (ushort v)
static uint32 my_round_up_to_next_power (uint32 v)
static uint32 my_clear_highest_bit (uint32 v)
static uint32 my_reverse_bits (uint32 key)
Variables
C_MODE_START const char _my_bits_nbits [256]
const uchar _my_bits_reverse_table [256]
Function Documentation
my_bit_log2()
static uint my_bit_log2 (ulong value) inline static
Definition at line 18 of file my_bit.h.
 {
   uint bit;
   for (bit=0 ; value > 1 ; value>>=1, bit++) ;
   return bit;
 }
my_clear_highest_bit()
static uint32 my_clear_highest_bit (uint32 v) inline static
Definition at line 83 of file my_bit.h.
 {
   uint32 w=v >> 1;
   w|= w >> 1;
   w|= w >> 2;
   w|= w >> 4;
   w|= w >> 8;
   w|= w >> 16;
   return v & w;
 }
Referenced by initialize_bucket().
my_count_bits()
static uint my_count_bits (ulonglong v) inline static
Definition at line 25 of file my_bit.h.
 {
 #if SIZEOF_LONG_LONG > 4
   /* The following code is a bit faster on 16 bit machines than if we would
      only shift v */
   ulong v2=(ulong) (v >> 32);
   return (uint) (uchar) (_my_bits_nbits[(uchar)  v] +
                          _my_bits_nbits[(uchar) (v >> 8)] +
                          _my_bits_nbits[(uchar) (v >> 16)] +
                          _my_bits_nbits[(uchar) (v >> 24)] +
                          _my_bits_nbits[(uchar) (v2)] +
                          _my_bits_nbits[(uchar) (v2 >> 8)] +
                          _my_bits_nbits[(uchar) (v2 >> 16)] +
                          _my_bits_nbits[(uchar) (v2 >> 24)]);
 #else
   return (uint) (uchar) (_my_bits_nbits[(uchar)  v] +
                          _my_bits_nbits[(uchar) (v >> 8)] +
                          _my_bits_nbits[(uchar) (v >> 16)] +
                          _my_bits_nbits[(uchar) (v >> 24)]);
 #endif
 }
References _my_bits_nbits.
my_count_bits_ushort()
static uint my_count_bits_ushort (ushort v) inline static
Definition at line 47 of file my_bit.h.
 {
   return _my_bits_nbits[v];
 }
References _my_bits_nbits.
Referenced by bitmap_bits_set().
my_reverse_bits()
static uint32 my_reverse_bits (uint32 key) inline static
Definition at line 94 of file my_bit.h.
 {
   return
     (_my_bits_reverse_table[ key      & 255] << 24) |
     (_my_bits_reverse_table[(key>> 8) & 255] << 16) |
     (_my_bits_reverse_table[(key>>16) & 255] <<  8) |
      _my_bits_reverse_table[(key>>24)      ];
 }
References _my_bits_reverse_table.
Referenced by initialize_bucket(), lf_hash_delete(), lf_hash_insert(), and lf_hash_search().
my_round_up_to_next_power()
static uint32 my_round_up_to_next_power (uint32 v) inline static
Definition at line 72 of file my_bit.h.
 {
   v--;          /* 01100000000000000000000000001010 */
   v|= v >> 1;       /* 01110000000000000000000000001111 */
   v|= v >> 2;       /* 01111100000000000000000000001111 */
   v|= v >> 4;       /* 01111111110000000000000000001111 */
   v|= v >> 8;       /* 01111111111111111100000000001111 */
   v|= v >> 16;      /* 01111111111111111111111111111111 */
   return v+1;       /* 10000000000000000000000000000000 */
 }
Referenced by next_power().
Variable Documentation
_my_bits_nbits
C_MODE_START const char _my_bits_nbits[256] extern
Definition at line 20 of file my_bit.c.
Referenced by my_count_bits(), and my_count_bits_ushort().
_my_bits_reverse_table
const uchar _my_bits_reverse_table[256] extern
Definition at line 42 of file my_bit.c.
Referenced by my_reverse_bits().