Azerotcore-wotlk: dtQueryFilterExt Class Reference
dtQueryFilterExt Class Reference
#include <DetourExtended.h>
Public Member Functions
float getCost (const float *pa, const float *pb, const dtPolyRef prevRef, const dtMeshTile *prevTile, const dtPoly *prevPoly, const dtPolyRef curRef, const dtMeshTile *curTile, const dtPoly *curPoly, const dtPolyRef nextRef, const dtMeshTile *nextTile, const dtPoly *nextPoly) const override
Public Member Functions inherited from dtQueryFilter
dtQueryFilter ()
virtual ~dtQueryFilter ()
virtual bool passFilter (const dtPolyRef ref, const dtMeshTile *tile, const dtPoly *poly) const
float getAreaCost (const int i) const
void setAreaCost (const int i, const float cost)
unsigned short getIncludeFlags () const
void setIncludeFlags (const unsigned short flags)
unsigned short getExcludeFlags () const
void setExcludeFlags (const unsigned short flags)
Detailed Description
Definition at line 10 of file DetourExtended.h.
Member Function Documentation
getCost()
float dtQueryFilterExt::getCost (const float * pa, const float * pb, const dtPolyRef prevRef, const dtMeshTile * prevTile, const dtPoly * prevPoly, const dtPolyRef curRef, const dtMeshTile * curTile, const dtPoly * curPoly, const dtPolyRef nextRef, const dtMeshTile * nextTile, const dtPoly * nextPoly) const override virtual
Returns cost to move from the beginning to the end of a line segment that is fully contained within a polygon.
Parameters
[in] pa The start position on the edge of the previous and current polygon. [(x, y, z)]
[in] pb The end position on the edge of the current and next polygon. [(x, y, z)]
[in] prevRef The reference id of the previous polygon. [opt]
[in] prevTile The tile containing the previous polygon. [opt]
[in] prevPoly The previous polygon. [opt]
[in] curRef The reference id of the current polygon.
[in] curTile The tile containing the current polygon.
[in] curPoly The current polygon.
[in] nextRef The refernece id of the next polygon. [opt]
[in] nextTile The tile containing the next polygon. [opt]
[in] nextPoly The next polygon. [opt]
Reimplemented from dtQueryFilter.
Definition at line 9 of file DetourExtended.cpp.
 {
     float startX = pa[2], startY = pa[0], startZ = pa[1];
     float destX = pb[2], destY = pb[0], destZ = pb[1];
     float slopeAngle = getSlopeAngle(startX, startY, startZ, destX, destY, destZ);
     float slopeAngleDegree = (slopeAngle * 180.0f / M_PI);
     float cost = slopeAngleDegree > 0 ? 1.0f + (1.0f * (slopeAngleDegree / 100)) : 1.0f;
     float dist = dtVdist(pa, pb);
     auto totalCost = dist * cost * getAreaCost(curPoly->getArea());
     return totalCost;
 }
References dtVdist(), dtPoly::getArea(), dtQueryFilter::getAreaCost(), getSlopeAngle(), and M_PI.
The documentation for this class was generated from the following files:
src/common/Navigation/DetourExtended.h
src/common/Navigation/DetourExtended.cpp