Azerotcore-wotlk: disable_commandscript Class Reference
disable_commandscript Class Reference
Public Member Functions
disable_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleAddDisables (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment, uint8 disableType)
static bool HandleAddDisableSpellCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableQuestCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableMapCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableBattlegroundCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableAchievementCriteriaCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableOutdoorPvPCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleAddDisableVmapCommand (ChatHandler *handler, uint32 entry, uint8 flags, std::string disableComment)
static bool HandleRemoveDisables (ChatHandler *handler, uint32 entry, uint8 disableType)
static bool HandleRemoveDisableSpellCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableQuestCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableMapCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableBattlegroundCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableAchievementCriteriaCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableOutdoorPvPCommand (ChatHandler *handler, uint32 entry)
static bool HandleRemoveDisableVmapCommand (ChatHandler *handler, uint32 entry)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 37 of file cs_disable.cpp.
Constructor & Destructor Documentation
disable_commandscript()
disable_commandscript::disable_commandscript () inline
Definition at line 40 of file cs_disable.cpp.
 : CommandScript("disable_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable disable_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 42 of file cs_disable.cpp.
     {
         static ChatCommandTable removeDisableCommandTable =
         {
             { "spell",        HandleRemoveDisableSpellCommand,        SEC_ADMINISTRATOR, Console::Yes },
             { "quest",        HandleRemoveDisableQuestCommand,        SEC_ADMINISTRATOR, Console::Yes },
             { "map",          HandleRemoveDisableMapCommand,          SEC_ADMINISTRATOR, Console::Yes },
             { "battleground", HandleRemoveDisableBattlegroundCommand, SEC_ADMINISTRATOR, Console::Yes },
             { "outdoorpvp",   HandleRemoveDisableOutdoorPvPCommand,   SEC_ADMINISTRATOR, Console::Yes },
             { "vmap",         HandleRemoveDisableVmapCommand,         SEC_ADMINISTRATOR, Console::Yes }
         };
         static ChatCommandTable addDisableCommandTable =
         {
             { "spell",        HandleAddDisableSpellCommand,           SEC_ADMINISTRATOR, Console::Yes },
             { "quest",        HandleAddDisableQuestCommand,           SEC_ADMINISTRATOR, Console::Yes },
             { "map",          HandleAddDisableMapCommand,             SEC_ADMINISTRATOR, Console::Yes },
             { "battleground", HandleAddDisableBattlegroundCommand,    SEC_ADMINISTRATOR, Console::Yes },
             { "outdoorpvp",   HandleAddDisableOutdoorPvPCommand,      SEC_ADMINISTRATOR, Console::Yes },
             { "vmap",         HandleAddDisableVmapCommand,            SEC_ADMINISTRATOR, Console::Yes }
         };
         static ChatCommandTable disableCommandTable =
         {
             { "add",    addDisableCommandTable },
             { "remove", removeDisableCommandTable }
         };
         static ChatCommandTable commandTable =
         {
             { "disable", disableCommandTable }
         };
         return commandTable;
     }
References SEC_ADMINISTRATOR, and Acore::ChatCommands::Yes.
HandleAddDisableAchievementCriteriaCommand()
static bool disable_commandscript::HandleAddDisableAchievementCriteriaCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 193 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_ACHIEVEMENT_CRITERIA);
     }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA.
HandleAddDisableBattlegroundCommand()
static bool disable_commandscript::HandleAddDisableBattlegroundCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 188 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_BATTLEGROUND);
     }
References DISABLE_TYPE_BATTLEGROUND.
HandleAddDisableMapCommand()
static bool disable_commandscript::HandleAddDisableMapCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 183 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_MAP);
     }
References DISABLE_TYPE_MAP.
HandleAddDisableOutdoorPvPCommand()
static bool disable_commandscript::HandleAddDisableOutdoorPvPCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 198 of file cs_disable.cpp.
     {
         HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_OUTDOORPVP);
         return true;
     }
References DISABLE_TYPE_OUTDOORPVP.
HandleAddDisableQuestCommand()
static bool disable_commandscript::HandleAddDisableQuestCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 178 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_QUEST);
     }
References DISABLE_TYPE_QUEST.
HandleAddDisables()
static bool disable_commandscript::HandleAddDisables (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment, uint8 disableType) inline static
Definition at line 74 of file cs_disable.cpp.
     {
         std::string disableTypeStr = "";
         switch (disableType)
         {
             case DISABLE_TYPE_SPELL:
                 {
                     if (!sSpellMgr->GetSpellInfo(entry))
                     {
                         handler->PSendSysMessage(LANG_COMMAND_NOSPELLFOUND);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "spell";
                     break;
                 }
             case DISABLE_TYPE_QUEST:
                 {
                     if (!sObjectMgr->GetQuestTemplate(entry))
                     {
                         handler->PSendSysMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "quest";
                     break;
                 }
             case DISABLE_TYPE_MAP:
                 {
                     if (!sMapStore.LookupEntry(entry))
                     {
                         handler->PSendSysMessage(LANG_COMMAND_NOMAPFOUND);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "map";
                     break;
                 }
             case DISABLE_TYPE_BATTLEGROUND:
                 {
                     if (!sBattlemasterListStore.LookupEntry(entry))
                     {
                         handler->PSendSysMessage(LANG_COMMAND_NO_BATTLEGROUND_FOUND);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "battleground";
                     break;
                 }
             case DISABLE_TYPE_OUTDOORPVP:
                 {
                     if (entry > MAX_OUTDOORPVP_TYPES)
                     {
                         handler->PSendSysMessage(LANG_COMMAND_NO_OUTDOOR_PVP_FORUND);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "outdoorpvp";
                     break;
                 }
             case DISABLE_TYPE_VMAP:
                 {
                     if (!sMapStore.LookupEntry(entry))
                     {
                         handler->PSendSysMessage(LANG_COMMAND_NOMAPFOUND);
                         handler->SetSentErrorMessage(true);
                         return false;
                     }
                     disableTypeStr = "vmap";
                     break;
                 }
             default:
                 break;
         }
         WorldDatabasePreparedStatement* stmt = nullptr;
         stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_DISABLES);
         stmt->setUInt32(0, entry);
         stmt->setUInt8(1, disableType);
         PreparedQueryResult result = WorldDatabase.Query(stmt);
         if (result)
         {
             handler->PSendSysMessage("This %s (Id: %u) is already disabled.", disableTypeStr.c_str(), entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_DISABLES);
         stmt->setUInt32(0, entry);
         stmt->setUInt8(1, disableType);
         stmt->setUInt16(2, flags);
         stmt->setString(3, disableComment);
         WorldDatabase.Execute(stmt);
         handler->PSendSysMessage("Add Disabled %s (Id: %u) for reason %s", disableTypeStr.c_str(), entry, disableComment.c_str());
         return true;
     }
References DISABLE_TYPE_BATTLEGROUND, DISABLE_TYPE_MAP, DISABLE_TYPE_OUTDOORPVP, DISABLE_TYPE_QUEST, DISABLE_TYPE_SPELL, DISABLE_TYPE_VMAP, LANG_COMMAND_NO_BATTLEGROUND_FOUND, LANG_COMMAND_NO_OUTDOOR_PVP_FORUND, LANG_COMMAND_NOMAPFOUND, LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_QUEST_NOTFOUND, MAX_OUTDOORPVP_TYPES, ChatHandler::PSendSysMessage(), sBattlemasterListStore, ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sMapStore, sObjectMgr, sSpellMgr, WORLD_INS_DISABLES, WORLD_SEL_DISABLES, and WorldDatabase.
HandleAddDisableSpellCommand()
static bool disable_commandscript::HandleAddDisableSpellCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 173 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_SPELL);
     }
References DISABLE_TYPE_SPELL.
HandleAddDisableVmapCommand()
static bool disable_commandscript::HandleAddDisableVmapCommand (ChatHandler * handler, uint32 entry, uint8 flags, std::string disableComment) inline static
Definition at line 204 of file cs_disable.cpp.
     {
         return HandleAddDisables(handler, entry, flags, disableComment, DISABLE_TYPE_VMAP);
     }
References DISABLE_TYPE_VMAP.
HandleRemoveDisableAchievementCriteriaCommand()
static bool disable_commandscript::HandleRemoveDisableAchievementCriteriaCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 279 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_ACHIEVEMENT_CRITERIA);
     }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA.
HandleRemoveDisableBattlegroundCommand()
static bool disable_commandscript::HandleRemoveDisableBattlegroundCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 274 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_BATTLEGROUND);
     }
References DISABLE_TYPE_BATTLEGROUND.
HandleRemoveDisableMapCommand()
static bool disable_commandscript::HandleRemoveDisableMapCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 269 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_MAP);
     }
References DISABLE_TYPE_MAP.
HandleRemoveDisableOutdoorPvPCommand()
static bool disable_commandscript::HandleRemoveDisableOutdoorPvPCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 284 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_OUTDOORPVP);
     }
References DISABLE_TYPE_OUTDOORPVP.
HandleRemoveDisableQuestCommand()
static bool disable_commandscript::HandleRemoveDisableQuestCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 264 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_QUEST);
     }
References DISABLE_TYPE_QUEST.
HandleRemoveDisables()
static bool disable_commandscript::HandleRemoveDisables (ChatHandler * handler, uint32 entry, uint8 disableType) inline static
Definition at line 209 of file cs_disable.cpp.
     {
         std::string disableTypeStr = "";
         switch (disableType)
         {
             case DISABLE_TYPE_SPELL:
                 disableTypeStr = "spell";
                 break;
             case DISABLE_TYPE_QUEST:
                 disableTypeStr = "quest";
                 break;
             case DISABLE_TYPE_MAP:
                 disableTypeStr = "map";
                 break;
             case DISABLE_TYPE_BATTLEGROUND:
                 disableTypeStr = "battleground";
                 break;
             case DISABLE_TYPE_ACHIEVEMENT_CRITERIA:
                 disableTypeStr = "achievement criteria";
                 break;
             case DISABLE_TYPE_OUTDOORPVP:
                 disableTypeStr = "outdoorpvp";
                 break;
             case DISABLE_TYPE_VMAP:
                 disableTypeStr = "vmap";
                 break;
         }
         WorldDatabasePreparedStatement* stmt = nullptr;
         stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_DISABLES);
         stmt->setUInt32(0, entry);
         stmt->setUInt8(1, disableType);
         PreparedQueryResult result = WorldDatabase.Query(stmt);
         if (!result)
         {
             handler->PSendSysMessage("This %s (Id: %u) is not disabled.", disableTypeStr.c_str(), entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_DISABLES);
         stmt->setUInt32(0, entry);
         stmt->setUInt8(1, disableType);
         WorldDatabase.Execute(stmt);
         handler->PSendSysMessage("Remove Disabled %s (Id: %u)", disableTypeStr.c_str(), entry);
         return true;
     }
References DISABLE_TYPE_ACHIEVEMENT_CRITERIA, DISABLE_TYPE_BATTLEGROUND, DISABLE_TYPE_MAP, DISABLE_TYPE_OUTDOORPVP, DISABLE_TYPE_QUEST, DISABLE_TYPE_SPELL, DISABLE_TYPE_VMAP, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), WORLD_DEL_DISABLES, WORLD_SEL_DISABLES, and WorldDatabase.
HandleRemoveDisableSpellCommand()
static bool disable_commandscript::HandleRemoveDisableSpellCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 259 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_SPELL);
     }
References DISABLE_TYPE_SPELL.
HandleRemoveDisableVmapCommand()
static bool disable_commandscript::HandleRemoveDisableVmapCommand (ChatHandler * handler, uint32 entry) inline static
Definition at line 289 of file cs_disable.cpp.
     {
         return HandleRemoveDisables(handler, entry, DISABLE_TYPE_VMAP);
     }
References DISABLE_TYPE_VMAP.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_disable.cpp