Azerotcore-wotlk: npc_cork_gizelton Class Reference
npc_cork_gizelton Class Reference
Classes
struct npc_cork_gizeltonAI
Public Member Functions
npc_cork_gizelton ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 68 of file zone_desolace.cpp.
Constructor & Destructor Documentation
npc_cork_gizelton()
npc_cork_gizelton::npc_cork_gizelton () inline
Definition at line 71 of file zone_desolace.cpp.
 : CreatureScript("npc_cork_gizelton") { }
Member Function Documentation
GetAI()
CreatureAI* npc_cork_gizelton::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 81 of file zone_desolace.cpp.
     {
         return new npc_cork_gizeltonAI(creature);
     }
OnQuestAccept()
bool npc_cork_gizelton::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 73 of file zone_desolace.cpp.
     {
         if (quest->GetQuestId() == QUEST_BODYGUARD_FOR_HIRE)
             creature->AI()->SetGUID(player->GetGUID(), player->GetFaction());
         return true;
     }
References Creature::AI(), Unit::GetFaction(), Object::GetGUID(), Quest::GetQuestId(), QUEST_BODYGUARD_FOR_HIRE, and UnitAI::SetGUID().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_desolace.cpp