Azerotcore-wotlk: G3D::Matrix4 Class Reference
G3D::Matrix4 Class Reference
#include <Matrix4.h>
Public Member Functions
Matrix4 (const Any &any)
Any toAny () const
Matrix4 (float r1c1, float r1c2, float r1c3, float r1c4, float r2c1, float r2c2, float r2c3, float r2c4, float r3c1, float r3c2, float r3c3, float r3c4, float r4c1, float r4c2, float r4c3, float r4c4)
Matrix4 (const float *init)
Matrix4 (const class Matrix3 &upper3x3, const class Vector3 &lastCol=Vector3::zero())
Matrix4 (const class CoordinateFrame &c)
Matrix4 (const double *init)
Matrix4 ()
class CoordinateFrame approxCoordinateFrame () const
void getPerspectiveProjectionParameters (double &left, double &right, double &bottom, double &top, double &nearval, double &farval, float updirection=-1.0f) const
float * operator[] (int r)
const float * operator[] (int r) const
operator float * ()
operator const float * () const
Matrix4 operator* (const Matrix4 &other) const
Matrix4 operator+ (const Matrix4 &other) const
class Matrix3 upper3x3 () const
class Matrix2 upper2x2 () const
class Vector3 homoMul (const class Vector3 &v, float w) const
void setRow (int r, const class Vector4 &v)
void setColumn (int c, const Vector4 &v)
const Vector4 & row (int r) const
Vector4 column (int c) const
Matrix4 operator* (const float s) const
Vector4 operator* (const Vector4 &vector) const
Matrix4 transpose () const
bool operator!= (const Matrix4 &other) const
bool operator== (const Matrix4 &other) const
float determinant () const
Matrix4 inverse () const
Matrix4 adjoint () const
Matrix4 cofactor () const
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
std::string toString () const
Static Public Member Functions
static Matrix4 diagonal (float e00, float e11, float e22, float e33)
static const Matrix4 & identity ()
static const Matrix4 & zero ()
static Matrix4 orthogonalProjection (float left, float right, float bottom, float top, float nearval, float farval, float upDirection=-1.0f)
static Matrix4 orthogonalProjection (const class Rect2D &rect, float nearval, float farval, float upDirection=-1.0f)
static Matrix4 perspectiveProjection (double left, double right, double bottom, double top, double nearval, double farval, float upDirection=-1.0f)
static Matrix4 scale (const Vector3 &v)
static Matrix4 scale (float x, float y, float z)
static Matrix4 scale (float s)
static Matrix4 translation (const Vector3 &v)
static Matrix4 translation (float x, float y, float z)
static Matrix4 yawDegrees (float deg)
static Matrix4 pitchDegrees (float deg)
static Matrix4 rollDegrees (float deg)
Private Member Functions
float subDeterminant (int excludeRow, int excludeCol) const
bool operator< (const Matrix4 &) const
bool operator> (const Matrix4 &) const
bool operator<= (const Matrix4 &) const
bool operator>= (const Matrix4 &) const
Private Attributes
float elt [4][4]
Detailed Description
A 4x4 matrix. Do not subclass. Data is initialized to 0 when default constructed.
See also
G3D::CoordinateFrame, G3D::Matrix3, G3D::Quat
Definition at line 36 of file Matrix4.h.
Constructor & Destructor Documentation
Matrix4() [1/7]
G3D::Matrix4::Matrix4 (const Any & any) explicit
Must be in one of the following forms:
Matrix4(#, #, # .... #)
Matrix4::scale(#)
Matrix4::scale(#, #, #)
Matrix4::translation(#, #, #)
Matrix4::identity()
Matrix4::rollDegrees(#)
Matrix4::pitchDegrees(#)
Matrix4::yawDegrees(#)
Definition at line 26 of file Matrix4.cpp.
{
     any.verifyNameBeginsWith("Matrix4", "CFrame", "CoordinateFrame");
     any.verifyType(Any::ARRAY);
     const std::string& name = any.name();
     if (name == "Matrix4") {
         any.verifySize(16);
         for (int r = 0; r < 4; ++r) {
             for (int c = 0; c < 4; ++c) {
                 elt[r][c] = any[r * 4 + c];
             }
         }
     } else if (name == "Matrix4::scale") {
         if (any.size() == 1) {
             *this = scale(any[0].floatValue());
         } else if (any.size() == 3) {
             *this = scale(any[0], any[1], any[2]);
         } else {
             any.verify(false, "Matrix4::scale() takes either 1 or 3 arguments");
         }
     } else if (name == "Matrix4::rollDegrees") {
         any.verifySize(1);
         *this = rollDegrees(any[0].floatValue());
     } else if (name == "Matrix4::yawDegrees") {
         any.verifySize(1);
         *this = yawDegrees(any[0].floatValue());
     } else if (name == "Matrix4::pitchDegrees") {
         any.verifySize(1);
         *this = pitchDegrees(any[0].floatValue());
     } else if (name == "Matrix4::translation") {
         if (any.size() == 3) {
             *this = translation(any[0], any[1], any[2]);
         } else {
             any.verify(false, "Matrix4::translation() requires 3 arguments");
         }
     } else if (name == "Matrix4::diagonal") {
         any.verifySize(4);
         *this = diagonal(any[0], any[1], any[2], any[3]);
     } else if (name == "Matrix4::identity") {
         *this = identity();
     } else if (beginsWith(name, "CFrame") || beginsWith(name, "CoordinateFrame")) {
         *this = CFrame(any);
     } else {
         any.verify(false, "Expected Matrix4 constructor");
     }
 }
References G3D::any(), G3D::Any::ARRAY, G3D::beginsWith(), mpq::c, diagonal(), elt, identity(), pitchDegrees(), rollDegrees(), scale(), translation(), and yawDegrees().
Matrix4() [2/7]
G3D::Matrix4::Matrix4 (float r1c1, float r1c2, float r1c3, float r1c4, float r2c1, float r2c2, float r2c3, float r2c4, float r3c1, float r3c2, float r3c3, float r3c4, float r4c1, float r4c2, float r4c3, float r4c4)
Definition at line 273 of file Matrix4.cpp.
{
     elt[0][0] = r1c1;  elt[0][1] = r1c2;  elt[0][2] = r1c3;  elt[0][3] = r1c4;
     elt[1][0] = r2c1;  elt[1][1] = r2c2;  elt[1][2] = r2c3;  elt[1][3] = r2c4;
     elt[2][0] = r3c1;  elt[2][1] = r3c2;  elt[2][2] = r3c3;  elt[2][3] = r3c4;
     elt[3][0] = r4c1;  elt[3][1] = r4c2;  elt[3][2] = r4c3;  elt[3][3] = r4c4;
 }
References elt.
Matrix4() [3/7]
G3D::Matrix4::Matrix4 (const float * init)
init should be row major.
Definition at line 287 of file Matrix4.cpp.
{
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             elt[r][c] = init[r * 4 + c];
         }
     }
 }
References mpq::c, and elt.
Matrix4() [4/7]
G3D::Matrix4::Matrix4 (const class Matrix3 & upper3x3, const class Vector3 & lastCol = Vector3::zero())
a is the upper left 3x3 submatrix and b is the upper right 3x1 submatrix. The last row of the created matrix is (0,0,0,1).
Matrix4() [5/7]
G3D::Matrix4::Matrix4 (const class CoordinateFrame & c)
Definition at line 107 of file Matrix4.cpp.
{
     for (int r = 0; r < 3; ++r) {
         for (int c = 0; c < 3; ++c) {
             elt[r][c] = cframe.rotation[r][c];
         }
         elt[r][3] = cframe.translation[r];
     }
     elt[3][0] = 0.0f;
     elt[3][1] = 0.0f;
     elt[3][2] = 0.0f;
     elt[3][3] = 1.0f;
 }
References mpq::c, elt, G3D::CoordinateFrame::rotation, and G3D::CoordinateFrame::translation.
Matrix4() [6/7]
G3D::Matrix4::Matrix4 (const double * init)
Definition at line 296 of file Matrix4.cpp.
{
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             elt[r][c] = (float)init[r * 4 + c];
         }
     }
 }
References mpq::c, and elt.
Matrix4() [7/7]
G3D::Matrix4::Matrix4 ()
Matrix4::zero()
Definition at line 305 of file Matrix4.cpp.
                  {
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             elt[r][c] = 0;
         }
     }
 }
References mpq::c, and elt.
Referenced by diagonal(), orthogonalProjection(), perspectiveProjection(), pitchDegrees(), rollDegrees(), scale(), translation(), and yawDegrees().
Member Function Documentation
adjoint()
Matrix4 G3D::Matrix4::adjoint () const
Transpose of the cofactor matrix (used in computing the inverse). Note: This is in fact only one type of adjoint. More generally, an adjoint of a matrix is any mapping of a matrix which possesses certain properties. This returns the so-called adjugate or classical adjoint.
Definition at line 431 of file Matrix4.cpp.
{
     return cofactor().transpose();
 }
References cofactor(), and transpose().
Referenced by inverse().
approxCoordinateFrame()
CoordinateFrame G3D::Matrix4::approxCoordinateFrame () const
Produces an RT transformation that nearly matches this Matrix4. Because a Matrix4 may not be precisely a rotation and translation, this may introduce error.
Definition at line 507 of file Matrix4.cpp.
{
     CoordinateFrame cframe;
     for (int r = 0; r < 3; ++r) {
         for (int c = 0; c < 3; ++c) {
             cframe.rotation[r][c] = elt[r][c];
         }
         cframe.translation[r] = elt[r][3];
     }
     // Ensure that the rotation matrix is orthonormal
     cframe.rotation.orthonormalize();
     return cframe;
 }
References mpq::c, elt, G3D::Matrix3::orthonormalize(), G3D::CoordinateFrame::rotation, and G3D::CoordinateFrame::translation.
Referenced by G3D::CoordinateFrame::CoordinateFrame().
cofactor()
Matrix4 G3D::Matrix4::cofactor () const
Definition at line 449 of file Matrix4.cpp.
{
     Matrix4 out;
     // We'll use i to incrementally compute -1 ^ (r+c)
     int i = 1;
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             // Compute the determinant of the 3x3 submatrix
             float det = subDeterminant(r, c);
             out.elt[r][c] = i * det;
             i = -i;
         }
         i = -i;
     }
     return out;
 }
References mpq::c, elt, and subDeterminant().
Referenced by adjoint(), and determinant().
column()
Vector4 G3D::Matrix4::column (int c) const
Definition at line 333 of file Matrix4.cpp.
{
     Vector4 v;
     for (int r = 0; r < 4; ++r) {
         v[r] = elt[r][c];
     }
     return v;
 }
References mpq::c, and elt.
Referenced by G3D::SplineBase::computeBasis(), and inverse().
deserialize()
void G3D::Matrix4::deserialize (class BinaryInput & b)
Definition at line 533 of file Matrix4.cpp.
{
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             elt[r][c] = b.readFloat32();
         }
     }
 }
References b, mpq::c, and elt.
determinant()
float G3D::Matrix4::determinant () const
Definition at line 424 of file Matrix4.cpp.
{
     // Determinant is the dot product of the first row and the first row
     // of cofactors (i.e. the first col of the adjoint matrix)
     return cofactor().row(0).dot(row(0));
 }
References cofactor(), G3D::Vector4::dot(), and row().
Referenced by G3D::Matrix::col4PseudoInverse(), G3D::determinant(), and G3D::Matrix::row4PseudoInverse().
diagonal()
static Matrix4 G3D::Matrix4::diagonal (float e00, float e11, float e22, float e33) inline static
Definition at line 92 of file Matrix4.h.
{
         return Matrix4(e00, 0, 0, 0,
                        0, e11, 0, 0,
                        0, 0, e22, 0,
                        0, 0, 0, e33);
     }
References Matrix4().
Referenced by Matrix4().
getPerspectiveProjectionParameters()
void G3D::Matrix4::getPerspectiveProjectionParameters (double & left, double & right, double & bottom, double & top, double & nearval, double & farval, float updirection = -1.0f) const
If this is a perspective projection matrix created by Matrix4::perspectiveProjection, extract its parameters.
Uses double precision because the operations involved in projection involve divisions that can significantly impact precision.
Definition at line 226 of file Matrix4.cpp.
{
     debugAssertM(abs(upDirection) == 1.0f, "upDirection must be -1 or +1");
     double x = elt[0][0];
     double y = elt[1][1] * upDirection;
     double a = elt[0][2];
     double b = elt[1][2] * upDirection;
     double c = elt[2][2];
     double d = elt[2][3];
     // Verify that this really is a projection matrix
     debugAssertM(elt[3][2] == -1, "Not a projection matrix");
     debugAssertM(elt[0][1] == 0, "Not a projection matrix");
     debugAssertM(elt[0][3] == 0, "Not a projection matrix");
     debugAssertM(elt[1][3] == 0, "Not a projection matrix");
     debugAssertM(elt[3][3] == 0, "Not a projection matrix");
     debugAssertM(elt[1][0] == 0, "Not a projection matrix");
     debugAssertM(elt[2][0] == 0, "Not a projection matrix");
     debugAssertM(elt[2][1] == 0, "Not a projection matrix");
     debugAssertM(elt[3][0] == 0, "Not a projection matrix");
     debugAssertM(elt[3][1] == 0, "Not a projection matrix");
     if (c == -1) {
         farval = finf();
         nearval = -d / 2.0;
     } else {
         nearval = d * ((c - 1.0) / (c + 1.0) - 1.0) / (-2.0 * (c - 1.0) / (c + 1.0));
         farval = nearval * ((c - 1.0) / (c + 1.0));
     }
     left = (a - 1.0) * nearval / x;
     right = 2.0 * nearval / x + left;
     bottom = (b - 1.0) * nearval / y;
     top = 2.0 * nearval / y + bottom;
 }
References mpq::a, G3D::abs(), b, mpq::c, mpq::d, debugAssertM, elt, G3D::finf(), align::left, align::right, G3D::x, and G3D::y.
Referenced by G3D::GCamera::GCamera().
homoMul()
Vector3 G3D::Matrix4::homoMul (const class Vector3 & v, float w) const
Homogeneous multiplication. Let k = M * [v w]^T. result = k.xyz() / k.w
Definition at line 368 of file Matrix4.cpp.
{
     Vector4 r = (*this) * Vector4(v, w);
     return r.xyz() * (1.0f / r.w);
 }
References G3D::Vector4::w, and G3D::Vector4::xyz().
Referenced by Utils::VectorTransform().
identity()
const Matrix4 & G3D::Matrix4::identity () static
Definition at line 87 of file Matrix4.cpp.
{
     static Matrix4 m(
         1, 0, 0, 0,
         0, 1, 0, 0,
         0, 0, 1, 0,
         0, 0, 0, 1);
     return m;
 }
Referenced by Matrix4().
inverse()
Matrix4 G3D::Matrix4::inverse () const
Definition at line 436 of file Matrix4.cpp.
{
     // Inverse = adjoint / determinant
     Matrix4 A = adjoint();
     // Determinant is the dot product of the first row and the first row
     // of cofactors (i.e. the first col of the adjoint matrix)
     float det = A.column(0).dot(row(0));
     return A * (1.0f / det);
 }
References adjoint(), column(), G3D::Vector4::dot(), and row().
Referenced by G3D::Matrix::col4PseudoInverse(), and G3D::Matrix::row4PseudoInverse().
operator const float *()
G3D::Matrix4::operator const float * () const inline
Definition at line 142 of file Matrix4.h.
{
         return (const float*)&elt[0][0];
     }
References elt.
operator float *()
G3D::Matrix4::operator float * () inline
Returns a row-major pointer.
Definition at line 138 of file Matrix4.h.
{
         return (float*)&elt[0][0];
     }
References elt.
operator!=()
bool G3D::Matrix4::operator!= (const Matrix4 & other) const
Definition at line 398 of file Matrix4.cpp.
{
     return ! (*this == other);
 }
operator*() [1/3]
Matrix4 G3D::Matrix4::operator* (const float s) const
Definition at line 356 of file Matrix4.cpp.
{
     Matrix4 result;
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             result.elt[r][c] = elt[r][c] * s;
         }
     }
     return result;
 }
References mpq::c, and elt.
operator*() [2/3]
Matrix4 G3D::Matrix4::operator* (const Matrix4 & other) const
Definition at line 342 of file Matrix4.cpp.
{
     Matrix4 result;
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             for (int i = 0; i < 4; ++i) {
                 result.elt[r][c] += elt[r][i] * other.elt[i][c];
             }
         }
     }
     return result;
 }
References mpq::c, and elt.
operator*() [3/3]
Vector4 G3D::Matrix4::operator* (const Vector4 & vector) const
Definition at line 374 of file Matrix4.cpp.
{
     Vector4 result(0,0,0,0);
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             result[r] += elt[r][c] * vector[c];
         }
     }
     return result;
 }
References mpq::c, and elt.
operator+()
Matrix4 G3D::Matrix4::operator+ (const Matrix4 & other) const inline
Definition at line 147 of file Matrix4.h.
{
         Matrix4 result;
         for (int r = 0; r < 4; ++r) {
             for (int c = 0; c < 4; ++c) {
                 result.elt[r][c] = elt[r][c] + other.elt[r][c];
             }
         }
         return result;
     }
References mpq::c, and elt.
operator<()
bool G3D::Matrix4::operator< (const Matrix4 &) const private
operator<=()
bool G3D::Matrix4::operator<= (const Matrix4 &) const private
operator==()
bool G3D::Matrix4::operator== (const Matrix4 & other) const
Definition at line 403 of file Matrix4.cpp.
{
     // If the bit patterns are identical, they must be
     // the same matrix.  If not, they *might* still have
     // equal elements due to floating point weirdness.
     if (memcmp(this, &other, sizeof(Matrix4)) == 0) {
         return true;
     }
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             if (elt[r][c] != other.elt[r][c]) {
                 return false;
             }
         }
     }
     return true;
 }
References mpq::c, and elt.
operator>()
bool G3D::Matrix4::operator> (const Matrix4 &) const private
operator>=()
bool G3D::Matrix4::operator>= (const Matrix4 &) const private
operator[]() [1/2]
float* G3D::Matrix4::operator[] (int r) inline
Definition at line 125 of file Matrix4.h.
{
         debugAssert(r >= 0);
         debugAssert(r < 4);
         return (float*)&elt[r];
     }
References debugAssert, and elt.
operator[]() [2/2]
const float* G3D::Matrix4::operator[] (int r) const inline
Definition at line 131 of file Matrix4.h.
{
         debugAssert(r >= 0);
         debugAssert(r < 4);
         return (const float*)&elt[r];
     }
References debugAssert, and elt.
orthogonalProjection() [1/2]
Matrix4 G3D::Matrix4::orthogonalProjection (const class Rect2D & rect, float nearval, float farval, float upDirection = -1.0f) static
Parameters
upDirection Use -1.0 for 2D Y increasing downwards (the G3D 8.x default convention), 1.0 for 2D Y increasing upwards (the G3D 7.x default and OpenGL convention)
Definition at line 147 of file Matrix4.cpp.
{
     return Matrix4::orthogonalProjection(rect.x0(), rect.x1(), rect.y1(), rect.y0(), nearval, farval, upDirection);
 }
References orthogonalProjection(), G3D::Rect2D::x0(), G3D::Rect2D::x1(), G3D::Rect2D::y0(), and G3D::Rect2D::y1().
orthogonalProjection() [2/2]
Matrix4 G3D::Matrix4::orthogonalProjection (float left, float right, float bottom, float top, float nearval, float farval, float upDirection = -1.0f) static
Constructs an orthogonal projection matrix from the given parameters. Near and far are the NEGATIVE of the near and far plane Z values (to follow OpenGL conventions).
Parameters
upDirection Use -1.0 for 2D Y increasing downwards (the G3D 8.x default convention), 1.0 for 2D Y increasing upwards (the G3D 7.x default and OpenGL convention)
Definition at line 156 of file Matrix4.cpp.
{
     // Adapted from Mesa.  Note that Microsoft (http://msdn.microsoft.com/library/default.asp?url=/library/en-us/opengl/glfunc03_8qnj.asp)
     // and Linux (http://www.xfree86.org/current/glOrtho.3.html) have different matrices shown in their documentation.
     float x, y, z;
     float tx,  ty, tz;
     x = 2.0f / (right-left);
     y = 2.0f / (top-bottom);
     z = -2.0f / (farval-nearval);
     tx = -(right+left) / (right-left);
     ty = -(top+bottom) / (top-bottom);
     tz = -(farval+nearval) / (farval-nearval);
     y  *= upDirection;
     ty *= upDirection;
     return
         Matrix4( x , 0.0f, 0.0f,  tx,
                 0.0f,  y , 0.0f,  ty,
                 0.0f, 0.0f,  z ,  tz,
                 0.0f, 0.0f, 0.0f, 1.0f);
 }
References align::left, Matrix4(), align::right, G3D::x, G3D::y, and G3D::z.
Referenced by orthogonalProjection().
perspectiveProjection()
Matrix4 G3D::Matrix4::perspectiveProjection (double left, double right, double bottom, double top, double nearval, double farval, float upDirection = -1.0f) static
Parameters
upDirection Use -1.0 for 2D Y increasing downwards (the G3D 8.x default convention), 1.0 for 2D Y increasing upwards (the G3D 7.x default and OpenGL convention)
Uses double precision because the operations involved in
projection involve divisions that can significantly impact
precision.
Definition at line 189 of file Matrix4.cpp.
{
     double x, y, a, b, c, d;
     x = (2.0*nearval) / (right-left);
     y = (2.0*nearval) / (top-bottom);
     a = (right+left) / (right-left);
     b = (top+bottom) / (top-bottom);
     if (farval >= inf()) {
        // Infinite view frustum
        c = -1.0;
        d = -2.0 * nearval;
     } else {
        c = -(farval+nearval) / (farval-nearval);
        d = -(2.0*farval*nearval) / (farval-nearval);
     }
     debugAssertM(abs(upDirection) == 1.0, "upDirection must be -1 or +1");
     y *= upDirection;
     b *= upDirection;
     return Matrix4(
         (float)x,  0,  (float)a,  0,
         0,  (float)y,  (float)b,  0,
         0,  0,  (float)c,  (float)d,
         0,  0, -1,  0);
 }
References mpq::a, G3D::abs(), b, mpq::c, mpq::d, debugAssertM, G3D::inf(), align::left, Matrix4(), align::right, G3D::x, and G3D::y.
Referenced by G3D::GCamera::getProjectUnitMatrix().
pitchDegrees()
static Matrix4 G3D::Matrix4::pitchDegrees (float deg) inline static
Definition at line 270 of file Matrix4.h.
{
         return Matrix4(Matrix3::fromAxisAngle(Vector3::unitX(), toRadians(deg)));
     }
References G3D::Matrix3::fromAxisAngle(), Matrix4(), G3D::toRadians(), and G3D::Vector3::unitX().
Referenced by Matrix4().
rollDegrees()
static Matrix4 G3D::Matrix4::rollDegrees (float deg) inline static
Definition at line 274 of file Matrix4.h.
{
         return Matrix4(Matrix3::fromAxisAngle(Vector3::unitZ(), toRadians(deg)));
     }
References G3D::Matrix3::fromAxisAngle(), Matrix4(), G3D::toRadians(), and G3D::Vector3::unitZ().
Referenced by Matrix4().
row()
const Vector4 & G3D::Matrix4::row (int r) const
Definition at line 328 of file Matrix4.cpp.
{
     return reinterpret_cast<const Vector4*>(elt[r])[0];
 }
References elt.
Referenced by determinant(), inverse(), and subDeterminant().
scale() [1/3]
static Matrix4 G3D::Matrix4::scale (const Vector3 & v) inline static
3D scale matrix
Definition at line 239 of file Matrix4.h.
{
         return Matrix4(v.x, 0, 0, 0,
                        0, v.y, 0, 0,
                        0, 0, v.z, 0,
                        0, 0, 0, 1);
     }
References Matrix4(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by Matrix4(), and scale().
scale() [2/3]
static Matrix4 G3D::Matrix4::scale (float s) inline static
3D scale matrix
Definition at line 252 of file Matrix4.h.
{
         return scale(s,s,s);
     }
References scale().
scale() [3/3]
static Matrix4 G3D::Matrix4::scale (float x, float y, float z) inline static
3D scale matrix
Definition at line 247 of file Matrix4.h.
{
         return scale(Vector3(x, y, z));
     }
References scale(), Vector3::Vector3(), G3D::x, G3D::y, and G3D::z.
serialize()
void G3D::Matrix4::serialize (class BinaryOutput & b) const
Serializes row-major
Definition at line 524 of file Matrix4.cpp.
{
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             b.writeFloat32(elt[r][c]);
         }
     }
 }
References b, mpq::c, and elt.
setColumn()
void G3D::Matrix4::setColumn (int c, const Vector4 & v)
Definition at line 321 of file Matrix4.cpp.
{
     for (int r = 0; r < 4; ++r) {
         elt[r][c] = v[r];
     }
 }
References mpq::c, and elt.
Referenced by G3D::SplineBase::computeBasis().
setRow()
void G3D::Matrix4::setRow (int r, const class Vector4 & v)
Definition at line 314 of file Matrix4.cpp.
{
     for (int c = 0; c < 4; ++c) {
         elt[r][c] = v[c];
     }
 }
References mpq::c, and elt.
subDeterminant()
float G3D::Matrix4::subDeterminant (int excludeRow, int excludeCol) const private
Computes the determinant of the 3x3 matrix that lacks excludeRow and excludeCol.
Definition at line 469 of file Matrix4.cpp.
{
     // Compute non-excluded row and column indices
     int row[3];
     int col[3];
     for (int i = 0; i < 3; ++i) {
         row[i] = i;
         col[i] = i;
         if (i >= excludeRow) {
             ++row[i];
         }
         if (i >= excludeCol) {
             ++col[i];
         }
     }
     // Compute the first row of cofactors
     float cofactor00 =
       elt[row[1]][col[1]] * elt[row[2]][col[2]] -
       elt[row[1]][col[2]] * elt[row[2]][col[1]];
     float cofactor10 =
       elt[row[1]][col[2]] * elt[row[2]][col[0]] -
       elt[row[1]][col[0]] * elt[row[2]][col[2]];
     float cofactor20 =
       elt[row[1]][col[0]] * elt[row[2]][col[1]] -
       elt[row[1]][col[1]] * elt[row[2]][col[0]];
     // Product of the first row and the cofactors along the first row
     return
       elt[row[0]][col[0]] * cofactor00 +
       elt[row[0]][col[1]] * cofactor10 +
       elt[row[0]][col[2]] * cofactor20;
 }
References elt, and row().
Referenced by cofactor().
toAny()
Any G3D::Matrix4::toAny () const
Definition at line 75 of file Matrix4.cpp.
{
     Any any(Any::ARRAY, "Matrix4");
     any.resize(16);
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             any[r * 4 + c] = elt[r][c];
         }
     }
     return any;
 }
References G3D::any(), G3D::Any::ARRAY, mpq::c, and elt.
toString()
std::string G3D::Matrix4::toString () const
Definition at line 541 of file Matrix4.cpp.
{
     return G3D::format("[%g, %g, %g, %g; %g, %g, %g, %g; %g, %g, %g, %g; %g, %g, %g, %g]",
             elt[0][0], elt[0][1], elt[0][2], elt[0][3],
             elt[1][0], elt[1][1], elt[1][2], elt[1][3],
             elt[2][0], elt[2][1], elt[2][2], elt[2][3],
             elt[3][0], elt[3][1], elt[3][2], elt[3][3]);
 }
References elt, and G3D::format().
translation() [1/2]
static Matrix4 G3D::Matrix4::translation (const Vector3 & v) inline static
3D translation matrix
Definition at line 257 of file Matrix4.h.
{
         return Matrix4(Matrix3::identity(), v);
     }
References G3D::Matrix3::identity(), and Matrix4().
Referenced by Matrix4().
translation() [2/2]
static Matrix4 G3D::Matrix4::translation (float x, float y, float z) inline static
Definition at line 261 of file Matrix4.h.
{
         return Matrix4(Matrix3::identity(), Vector3(x, y, z));
     }
References G3D::Matrix3::identity(), Matrix4(), Vector3::Vector3(), G3D::x, G3D::y, and G3D::z.
transpose()
Matrix4 G3D::Matrix4::transpose () const
Definition at line 386 of file Matrix4.cpp.
{
     Matrix4 result;
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             result.elt[c][r] = elt[r][c];
         }
     }
     return result;
 }
References mpq::c, and elt.
Referenced by adjoint().
upper2x2()
Matrix2 G3D::Matrix4::upper2x2 () const
Definition at line 141 of file Matrix4.cpp.
{
     return Matrix2(elt[0][0], elt[0][1],
                    elt[1][0], elt[1][1]);
 }
References elt.
upper3x3()
Matrix3 G3D::Matrix4::upper3x3 () const
Definition at line 134 of file Matrix4.cpp.
{
     return Matrix3(elt[0][0], elt[0][1], elt[0][2],
                    elt[1][0], elt[1][1], elt[1][2],
                    elt[2][0], elt[2][1], elt[2][2]);
 }
References elt.
yawDegrees()
static Matrix4 G3D::Matrix4::yawDegrees (float deg) inline static
Create a rotation matrix that rotates deg degrees around the Y axis
Definition at line 266 of file Matrix4.h.
{
         return Matrix4(Matrix3::fromAxisAngle(Vector3::unitY(), toRadians(deg)));
     }
References G3D::Matrix3::fromAxisAngle(), Matrix4(), G3D::toRadians(), and G3D::Vector3::unitY().
Referenced by Matrix4().
zero()
const Matrix4 & G3D::Matrix4::zero () static
Definition at line 97 of file Matrix4.cpp.
{
     static Matrix4 m(
         0, 0, 0, 0,
         0, 0, 0, 0,
         0, 0, 0, 0,
         0, 0, 0, 0);
     return m;
 }
Member Data Documentation
elt
float G3D::Matrix4::elt[4][4] private
Definition at line 39 of file Matrix4.h.
Referenced by approxCoordinateFrame(), cofactor(), column(), deserialize(), getPerspectiveProjectionParameters(), Matrix4(), operator const float *(), operator float *(), operator*(), operator+(), operator==(), operator[](), row(), serialize(), setColumn(), setRow(), subDeterminant(), toAny(), toString(), transpose(), upper2x2(), and upper3x3().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Matrix4.h
deps/g3dlite/source/Matrix4.cpp