Azerotcore-wotlk: instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript Struct Reference
instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript Struct Reference
Public Member Functions
instance_drak_tharon_keep_InstanceScript (Map *map)
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 36 of file instance_drak_tharon_keep.cpp.
Constructor & Destructor Documentation
instance_drak_tharon_keep_InstanceScript()
instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::instance_drak_tharon_keep_InstanceScript (Map * map) inline
Definition at line 38 of file instance_drak_tharon_keep.cpp.
                                                            : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTERS);
             LoadDoorData(doorData);
         }
References doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Member Function Documentation
GetSaveData()
std::string instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 70 of file instance_drak_tharon_keep.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "D K " << GetBossSaveData();
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData().
Load()
void instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 77 of file instance_drak_tharon_keep.cpp.
         {
             if( !in )
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'D' && dataHead2 == 'K')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
         }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, InstanceScript::SetBossState(), and SPECIAL.
OnGameObjectCreate()
void instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 44 of file instance_drak_tharon_keep.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_NOVOS_CRYSTAL_1:
                 case GO_NOVOS_CRYSTAL_2:
                 case GO_NOVOS_CRYSTAL_3:
                 case GO_NOVOS_CRYSTAL_4:
                     AddDoor(go, true);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_NOVOS_CRYSTAL_1, GO_NOVOS_CRYSTAL_2, GO_NOVOS_CRYSTAL_3, and GO_NOVOS_CRYSTAL_4.
OnGameObjectRemove()
void instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 57 of file instance_drak_tharon_keep.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_NOVOS_CRYSTAL_1:
                 case GO_NOVOS_CRYSTAL_2:
                 case GO_NOVOS_CRYSTAL_3:
                 case GO_NOVOS_CRYSTAL_4:
                     AddDoor(go, false);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_NOVOS_CRYSTAL_1, GO_NOVOS_CRYSTAL_2, GO_NOVOS_CRYSTAL_3, and GO_NOVOS_CRYSTAL_4.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/DraktharonKeep/instance_drak_tharon_keep.cpp