Azerotcore-wotlk: deps/jemalloc/src/tcache.c File Reference
tcache.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/safety_check.h"
#include "jemalloc/internal/sc.h"
Macros
#define JEMALLOC_TCACHE_C_
Functions
size_t tcache_salloc (tsdn_t *tsdn, const void *ptr)
void tcache_event_hard (tsd_t *tsd, tcache_t *tcache)
void * tcache_alloc_small_hard (tsdn_t *tsdn, arena_t *arena, tcache_t *tcache, cache_bin_t *tbin, szind_t binind, bool *tcache_success)
static void tbin_extents_lookup_size_check (tsdn_t *tsdn, cache_bin_t *tbin, szind_t binind, size_t nflush, extent_t **extents)
void tcache_bin_flush_small (tsd_t *tsd, tcache_t *tcache, cache_bin_t *tbin, szind_t binind, unsigned rem)
void tcache_bin_flush_large (tsd_t *tsd, cache_bin_t *tbin, szind_t binind, unsigned rem, tcache_t *tcache)
void tcache_arena_associate (tsdn_t *tsdn, tcache_t *tcache, arena_t *arena)
static void tcache_arena_dissociate (tsdn_t *tsdn, tcache_t *tcache)
void tcache_arena_reassociate (tsdn_t *tsdn, tcache_t *tcache, arena_t *arena)
bool tsd_tcache_enabled_data_init (tsd_t *tsd)
static void tcache_init (tsd_t *tsd, tcache_t *tcache, void *avail_stack)
bool tsd_tcache_data_init (tsd_t *tsd)
tcache_t * tcache_create_explicit (tsd_t *tsd)
static void tcache_flush_cache (tsd_t *tsd, tcache_t *tcache)
void tcache_flush (tsd_t *tsd)
static void tcache_destroy (tsd_t *tsd, tcache_t *tcache, bool tsd_tcache)
void tcache_cleanup (tsd_t *tsd)
void tcache_stats_merge (tsdn_t *tsdn, tcache_t *tcache, arena_t *arena)
static bool tcaches_create_prep (tsd_t *tsd)
bool tcaches_create (tsd_t *tsd, unsigned *r_ind)
static tcache_t * tcaches_elm_remove (tsd_t *tsd, tcaches_t *elm, bool allow_reinit)
void tcaches_flush (tsd_t *tsd, unsigned ind)
void tcaches_destroy (tsd_t *tsd, unsigned ind)
bool tcache_boot (tsdn_t *tsdn)
void tcache_prefork (tsdn_t *tsdn)
void tcache_postfork_parent (tsdn_t *tsdn)
void tcache_postfork_child (tsdn_t *tsdn)
Variables
bool opt_tcache = true
ssize_t opt_lg_tcache_max = LG_TCACHE_MAXCLASS_DEFAULT
cache_bin_info_t * tcache_bin_info
static unsigned stack_nelms
unsigned nhbins
size_t tcache_maxclass
tcaches_t * tcaches
static unsigned tcaches_past
static tcaches_t * tcaches_avail
static malloc_mutex_t tcaches_mtx
Macro Definition Documentation
JEMALLOC_TCACHE_C_
#define JEMALLOC_TCACHE_C_
Definition at line 1 of file tcache.c.
Function Documentation
tbin_extents_lookup_size_check()
static void tbin_extents_lookup_size_check (tsdn_t * tsdn, cache_bin_t * tbin, szind_t binind, size_t nflush, extent_t ** extents) static
Definition at line 106 of file tcache.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     /*
      * Verify that the items in the tcache all have the correct size; this
      * is useful for catching sized deallocation bugs, also to fail early
      * instead of corrupting metadata.  Since this can be turned on for opt
      * builds, avoid the branch in the loop.
      */
     szind_t szind;
     size_t sz_sum = binind * nflush;
     for (unsigned i = 0 ; i < nflush; i++) {
         rtree_extent_szind_read(tsdn, &extents_rtree,
             rtree_ctx, (uintptr_t)*(tbin->avail - 1 - i), true,
             &extents[i], &szind);
         sz_sum -= szind;
     }
     if (sz_sum != 0) {
         safety_check_fail("<jemalloc>: size mismatch in thread cache "
             "detected, likely caused by sized deallocation bugs by "
             "application. Abort.\n");
         abort();
     }
 }
References cache_bin_s::avail, extents_rtree, rtree_extent_szind_read(), safety_check_fail, and tsdn_rtree_ctx().
Referenced by tcache_bin_flush_large(), and tcache_bin_flush_small().
tcache_alloc_small_hard()
void* tcache_alloc_small_hard (tsdn_t * tsdn, arena_t * arena, tcache_t * tcache, cache_bin_t * tbin, szind_t binind, bool * tcache_success)
Definition at line 89 of file tcache.c.
{
     void *ret;
     assert(tcache->arena != NULL);
     arena_tcache_fill_small(tsdn, arena, tcache, tbin, binind,
         config_prof ? tcache->prof_accumbytes : 0);
     if (config_prof) {
         tcache->prof_accumbytes = 0;
     }
     ret = cache_bin_alloc_easy(tbin, tcache_success);
     return ret;
 }
References tcache_s::arena, arena, arena_tcache_fill_small, assert(), cache_bin_alloc_easy(), config_prof, NULL, tcache_s::prof_accumbytes, and ret.
tcache_arena_associate()
void tcache_arena_associate (tsdn_t * tsdn, tcache_t * tcache, arena_t * arena)
Definition at line 341 of file tcache.c.
{
     assert(tcache->arena == NULL);
     tcache->arena = arena;
     if (config_stats) {
         /* Link into list of extant tcaches. */
         malloc_mutex_lock(tsdn, &arena->tcache_ql_mtx);
         ql_elm_new(tcache, link);
         ql_tail_insert(&arena->tcache_ql, tcache, link);
         cache_bin_array_descriptor_init(
             &tcache->cache_bin_array_descriptor, tcache->bins_small,
             tcache->bins_large);
         ql_tail_insert(&arena->cache_bin_array_descriptor_ql,
             &tcache->cache_bin_array_descriptor, link);
         malloc_mutex_unlock(tsdn, &arena->tcache_ql_mtx);
     }
 }
References tcache_s::arena, arena, assert(), tcache_s::bins_large, tcache_s::bins_small, tcache_s::cache_bin_array_descriptor, cache_bin_array_descriptor_init(), config_stats, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ql_elm_new, ql_tail_insert, and arena_s::tcache_ql_mtx.
Referenced by tcache_arena_reassociate(), tcache_create_explicit(), and tsd_tcache_data_init().
tcache_arena_dissociate()
static void tcache_arena_dissociate (tsdn_t * tsdn, tcache_t * tcache) static
Definition at line 362 of file tcache.c.
{
     arena_t *arena = tcache->arena;
     assert(arena != NULL);
     if (config_stats) {
         /* Unlink from list of extant tcaches. */
         malloc_mutex_lock(tsdn, &arena->tcache_ql_mtx);
         if (config_debug) {
             bool in_ql = false;
             tcache_t *iter;
             ql_foreach(iter, &arena->tcache_ql, link) {
                 if (iter == tcache) {
                     in_ql = true;
                     break;
                 }
             }
             assert(in_ql);
         }
         ql_remove(&arena->tcache_ql, tcache, link);
         ql_remove(&arena->cache_bin_array_descriptor_ql,
             &tcache->cache_bin_array_descriptor, link);
         tcache_stats_merge(tsdn, tcache, arena);
         malloc_mutex_unlock(tsdn, &arena->tcache_ql_mtx);
     }
     tcache->arena = NULL;
 }
References tcache_s::arena, arena, assert(), tcache_s::cache_bin_array_descriptor, config_debug, config_stats, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ql_foreach, ql_remove, arena_s::tcache_ql_mtx, and tcache_stats_merge().
Referenced by tcache_arena_reassociate(), and tcache_destroy().
tcache_arena_reassociate()
void tcache_arena_reassociate (tsdn_t * tsdn, tcache_t * tcache, arena_t * arena)
Definition at line 389 of file tcache.c.
{
     tcache_arena_dissociate(tsdn, tcache);
     tcache_arena_associate(tsdn, tcache, arena);
 }
References arena, tcache_arena_associate(), and tcache_arena_dissociate().
tcache_bin_flush_large()
void tcache_bin_flush_large (tsd_t * tsd, cache_bin_t * tbin, szind_t binind, unsigned rem, tcache_t * tcache)
Definition at line 230 of file tcache.c.
{
     bool merged_stats = false;
     assert(binind < nhbins);
     assert((cache_bin_sz_t)rem <= tbin->ncached);
     arena_t *tcache_arena = tcache->arena;
     assert(tcache_arena != NULL);
     unsigned nflush = tbin->ncached - rem;
     VARIABLE_ARRAY(extent_t *, item_extent, nflush);
 #ifndef JEMALLOC_EXTRA_SIZE_CHECK
     /* Look up extent once per item. */
     for (unsigned i = 0 ; i < nflush; i++) {
         item_extent[i] = iealloc(tsd_tsdn(tsd), *(tbin->avail - 1 - i));
     }
 #else
     tbin_extents_lookup_size_check(tsd_tsdn(tsd), tbin, binind, nflush,
         item_extent);
 #endif
     while (nflush > 0) {
         /* Lock the arena associated with the first object. */
         extent_t *extent = item_extent[0];
         unsigned locked_arena_ind = extent_arena_ind_get(extent);
         arena_t *locked_arena = arena_get(tsd_tsdn(tsd),
             locked_arena_ind, false);
         bool idump;
         if (config_prof) {
             idump = false;
         }
         bool lock_large = !arena_is_auto(locked_arena);
         if (lock_large) {
             malloc_mutex_lock(tsd_tsdn(tsd), &locked_arena->large_mtx);
         }
         for (unsigned i = 0; i < nflush; i++) {
             void *ptr = *(tbin->avail - 1 - i);
             assert(ptr != NULL);
             extent = item_extent[i];
             if (extent_arena_ind_get(extent) == locked_arena_ind) {
                 large_dalloc_prep_junked_locked(tsd_tsdn(tsd),
                     extent);
             }
         }
         if ((config_prof || config_stats) &&
             (locked_arena == tcache_arena)) {
             if (config_prof) {
                 idump = arena_prof_accum(tsd_tsdn(tsd),
                     tcache_arena, tcache->prof_accumbytes);
                 tcache->prof_accumbytes = 0;
             }
             if (config_stats) {
                 merged_stats = true;
                 arena_stats_large_flush_nrequests_add(
                     tsd_tsdn(tsd), &tcache_arena->stats, binind,
                     tbin->tstats.nrequests);
                 tbin->tstats.nrequests = 0;
             }
         }
         if (lock_large) {
             malloc_mutex_unlock(tsd_tsdn(tsd), &locked_arena->large_mtx);
         }
         unsigned ndeferred = 0;
         for (unsigned i = 0; i < nflush; i++) {
             void *ptr = *(tbin->avail - 1 - i);
             extent = item_extent[i];
             assert(ptr != NULL && extent != NULL);
             if (extent_arena_ind_get(extent) == locked_arena_ind) {
                 large_dalloc_finish(tsd_tsdn(tsd), extent);
             } else {
                 /*
                  * This object was allocated via a different
                  * arena than the one that is currently locked.
                  * Stash the object, so that it can be handled
                  * in a future pass.
                  */
                 *(tbin->avail - 1 - ndeferred) = ptr;
                 item_extent[ndeferred] = extent;
                 ndeferred++;
             }
         }
         if (config_prof && idump) {
             prof_idump(tsd_tsdn(tsd));
         }
         arena_decay_ticks(tsd_tsdn(tsd), locked_arena, nflush -
             ndeferred);
         nflush = ndeferred;
     }
     if (config_stats && !merged_stats) {
         /*
          * The flush loop didn't happen to flush to this thread's
          * arena, so the stats didn't get merged.  Manually do so now.
          */
         arena_stats_large_flush_nrequests_add(tsd_tsdn(tsd),
             &tcache_arena->stats, binind, tbin->tstats.nrequests);
         tbin->tstats.nrequests = 0;
     }
     memmove(tbin->avail - rem, tbin->avail - tbin->ncached, rem *
         sizeof(void *));
     tbin->ncached = rem;
     if (tbin->ncached < tbin->low_water) {
         tbin->low_water = tbin->ncached;
     }
 }
References tcache_s::arena, arena_decay_ticks(), arena_get(), arena_is_auto(), arena_prof_accum(), arena_stats_large_flush_nrequests_add(), assert(), cache_bin_s::avail, config_prof, config_stats, extent_arena_ind_get(), iealloc(), large_dalloc_finish, large_dalloc_prep_junked_locked, arena_s::large_mtx, cache_bin_s::low_water, malloc_mutex_lock(), malloc_mutex_unlock(), memmove, cache_bin_s::ncached, nhbins, cache_bin_stats_s::nrequests, NULL, tcache_s::prof_accumbytes, prof_idump, ptr(), arena_s::stats, tbin_extents_lookup_size_check(), tsd_tsdn(), cache_bin_s::tstats, and VARIABLE_ARRAY.
Referenced by tcache_event_hard(), and tcache_flush_cache().
tcache_bin_flush_small()
void tcache_bin_flush_small (tsd_t * tsd, tcache_t * tcache, cache_bin_t * tbin, szind_t binind, unsigned rem)
Definition at line 134 of file tcache.c.
{
     bool merged_stats = false;
     assert(binind < SC_NBINS);
     assert((cache_bin_sz_t)rem <= tbin->ncached);
     arena_t *arena = tcache->arena;
     assert(arena != NULL);
     unsigned nflush = tbin->ncached - rem;
     VARIABLE_ARRAY(extent_t *, item_extent, nflush);
     /* Look up extent once per item. */
     if (config_opt_safety_checks) {
         tbin_extents_lookup_size_check(tsd_tsdn(tsd), tbin, binind,
             nflush, item_extent);
     } else {
         for (unsigned i = 0 ; i < nflush; i++) {
             item_extent[i] = iealloc(tsd_tsdn(tsd),
                 *(tbin->avail - 1 - i));
         }
     }
     while (nflush > 0) {
         /* Lock the arena bin associated with the first object. */
         extent_t *extent = item_extent[0];
         unsigned bin_arena_ind = extent_arena_ind_get(extent);
         arena_t *bin_arena = arena_get(tsd_tsdn(tsd), bin_arena_ind,
             false);
         unsigned binshard = extent_binshard_get(extent);
         assert(binshard < bin_infos[binind].n_shards);
         bin_t *bin = &bin_arena->bins[binind].bin_shards[binshard];
         if (config_prof && bin_arena == arena) {
             if (arena_prof_accum(tsd_tsdn(tsd), arena,
                 tcache->prof_accumbytes)) {
                 prof_idump(tsd_tsdn(tsd));
             }
             tcache->prof_accumbytes = 0;
         }
         malloc_mutex_lock(tsd_tsdn(tsd), &bin->lock);
         if (config_stats && bin_arena == arena && !merged_stats) {
             merged_stats = true;
             bin->stats.nflushes++;
             bin->stats.nrequests += tbin->tstats.nrequests;
             tbin->tstats.nrequests = 0;
         }
         unsigned ndeferred = 0;
         for (unsigned i = 0; i < nflush; i++) {
             void *ptr = *(tbin->avail - 1 - i);
             extent = item_extent[i];
             assert(ptr != NULL && extent != NULL);
             if (extent_arena_ind_get(extent) == bin_arena_ind
                 && extent_binshard_get(extent) == binshard) {
                 arena_dalloc_bin_junked_locked(tsd_tsdn(tsd),
                     bin_arena, bin, binind, extent, ptr);
             } else {
                 /*
                  * This object was allocated via a different
                  * arena bin than the one that is currently
                  * locked.  Stash the object, so that it can be
                  * handled in a future pass.
                  */
                 *(tbin->avail - 1 - ndeferred) = ptr;
                 item_extent[ndeferred] = extent;
                 ndeferred++;
             }
         }
         malloc_mutex_unlock(tsd_tsdn(tsd), &bin->lock);
         arena_decay_ticks(tsd_tsdn(tsd), bin_arena, nflush - ndeferred);
         nflush = ndeferred;
     }
     if (config_stats && !merged_stats) {
         /*
          * The flush loop didn't happen to flush to this thread's
          * arena, so the stats didn't get merged.  Manually do so now.
          */
         unsigned binshard;
         bin_t *bin = arena_bin_choose_lock(tsd_tsdn(tsd), arena, binind,
             &binshard);
         bin->stats.nflushes++;
         bin->stats.nrequests += tbin->tstats.nrequests;
         tbin->tstats.nrequests = 0;
         malloc_mutex_unlock(tsd_tsdn(tsd), &bin->lock);
     }
     memmove(tbin->avail - rem, tbin->avail - tbin->ncached, rem *
         sizeof(void *));
     tbin->ncached = rem;
     if (tbin->ncached < tbin->low_water) {
         tbin->low_water = tbin->ncached;
     }
 }
References tcache_s::arena, arena, arena_bin_choose_lock, arena_dalloc_bin_junked_locked, arena_decay_ticks(), arena_get(), arena_prof_accum(), assert(), cache_bin_s::avail, bin_infos, bins_s::bin_shards, arena_s::bins, config_opt_safety_checks, config_prof, config_stats, extent_arena_ind_get(), extent_binshard_get(), iealloc(), bin_s::lock, cache_bin_s::low_water, malloc_mutex_lock(), malloc_mutex_unlock(), memmove, cache_bin_s::ncached, bin_stats_s::nflushes, bin_stats_s::nrequests, cache_bin_stats_s::nrequests, NULL, tcache_s::prof_accumbytes, prof_idump, ptr(), SC_NBINS, bin_s::stats, tbin_extents_lookup_size_check(), tsd_tsdn(), cache_bin_s::tstats, and VARIABLE_ARRAY.
Referenced by tcache_event_hard(), and tcache_flush_cache().
tcache_boot()
bool tcache_boot (tsdn_t * tsdn)
Definition at line 733 of file tcache.c.
{
     /* If necessary, clamp opt_lg_tcache_max. */
     if (opt_lg_tcache_max < 0 || (ZU(1) << opt_lg_tcache_max) <
         SC_SMALL_MAXCLASS) {
         tcache_maxclass = SC_SMALL_MAXCLASS;
     } else {
         tcache_maxclass = (ZU(1) << opt_lg_tcache_max);
     }
     if (malloc_mutex_init(&tcaches_mtx, "tcaches", WITNESS_RANK_TCACHES,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     nhbins = sz_size2index(tcache_maxclass) + 1;
     /* Initialize tcache_bin_info. */
     tcache_bin_info = (cache_bin_info_t *)base_alloc(tsdn, b0get(), nhbins
         * sizeof(cache_bin_info_t), CACHELINE);
     if (tcache_bin_info == NULL) {
         return true;
     }
     stack_nelms = 0;
     unsigned i;
     for (i = 0; i < SC_NBINS; i++) {
         if ((bin_infos[i].nregs << 1) <= TCACHE_NSLOTS_SMALL_MIN) {
             tcache_bin_info[i].ncached_max =
                 TCACHE_NSLOTS_SMALL_MIN;
         } else if ((bin_infos[i].nregs << 1) <=
             TCACHE_NSLOTS_SMALL_MAX) {
             tcache_bin_info[i].ncached_max =
                 (bin_infos[i].nregs << 1);
         } else {
             tcache_bin_info[i].ncached_max =
                 TCACHE_NSLOTS_SMALL_MAX;
         }
         stack_nelms += tcache_bin_info[i].ncached_max;
     }
     for (; i < nhbins; i++) {
         tcache_bin_info[i].ncached_max = TCACHE_NSLOTS_LARGE;
         stack_nelms += tcache_bin_info[i].ncached_max;
     }
     return false;
 }
References b0get, base_alloc, bin_infos, CACHELINE, malloc_mutex_init, malloc_mutex_rank_exclusive, cache_bin_info_s::ncached_max, nhbins, NULL, opt_lg_tcache_max, SC_NBINS, SC_SMALL_MAXCLASS, stack_nelms, sz_size2index(), tcache_bin_info, tcache_maxclass, TCACHE_NSLOTS_LARGE, TCACHE_NSLOTS_SMALL_MAX, TCACHE_NSLOTS_SMALL_MIN, tcaches_mtx, WITNESS_RANK_TCACHES, and ZU.
tcache_cleanup()
void tcache_cleanup (tsd_t * tsd)
Definition at line 582 of file tcache.c.
{
     tcache_t *tcache = tsd_tcachep_get(tsd);
     if (!tcache_available(tsd)) {
         assert(tsd_tcache_enabled_get(tsd) == false);
         if (config_debug) {
             assert(tcache_small_bin_get(tcache, 0)->avail == NULL);
         }
         return;
     }
     assert(tsd_tcache_enabled_get(tsd));
     assert(tcache_small_bin_get(tcache, 0)->avail != NULL);
     tcache_destroy(tsd, tcache, true);
     if (config_debug) {
         tcache_small_bin_get(tcache, 0)->avail = NULL;
     }
 }
References assert(), cache_bin_s::avail, config_debug, NULL, tcache_available(), tcache_destroy(), and tcache_small_bin_get().
tcache_create_explicit()
tcache_t* tcache_create_explicit (tsd_t * tsd)
Definition at line 486 of file tcache.c.
{
     tcache_t *tcache;
     size_t size, stack_offset;
     size = sizeof(tcache_t);
     /* Naturally align the pointer stacks. */
     size = PTR_CEILING(size);
     stack_offset = size;
     size += stack_nelms * sizeof(void *);
     /* Avoid false cacheline sharing. */
     size = sz_sa2u(size, CACHELINE);
     tcache = ipallocztm(tsd_tsdn(tsd), size, CACHELINE, true, NULL, true,
         arena_get(TSDN_NULL, 0, true));
     if (tcache == NULL) {
         return NULL;
     }
     tcache_init(tsd, tcache,
         (void *)((uintptr_t)tcache + (uintptr_t)stack_offset));
     tcache_arena_associate(tsd_tsdn(tsd), tcache, arena_ichoose(tsd, NULL));
     return tcache;
 }
References arena_get(), arena_ichoose(), CACHELINE, ipallocztm(), NULL, PTR_CEILING, stack_nelms, sz_sa2u(), tcache_arena_associate(), tcache_init(), tsd_tsdn(), and TSDN_NULL.
Referenced by tcaches_create().
tcache_destroy()
static void tcache_destroy (tsd_t * tsd, tcache_t * tcache, bool tsd_tcache) static
Definition at line 546 of file tcache.c.
{
     tcache_flush_cache(tsd, tcache);
     arena_t *arena = tcache->arena;
     tcache_arena_dissociate(tsd_tsdn(tsd), tcache);
     if (tsd_tcache) {
         /* Release the avail array for the TSD embedded auto tcache. */
         void *avail_array =
             (void *)((uintptr_t)tcache_small_bin_get(tcache, 0)->avail -
             (uintptr_t)tcache_bin_info[0].ncached_max * sizeof(void *));
         idalloctm(tsd_tsdn(tsd), avail_array, NULL, NULL, true, true);
     } else {
         /* Release both the tcache struct and avail array. */
         idalloctm(tsd_tsdn(tsd), tcache, NULL, NULL, true, true);
     }
     /*
      * The deallocation and tcache flush above may not trigger decay since
      * we are on the tcache shutdown path (potentially with non-nominal
      * tsd).  Manually trigger decay to avoid pathological cases.  Also
      * include arena 0 because the tcache array is allocated from it.
      */
     arena_decay(tsd_tsdn(tsd), arena_get(tsd_tsdn(tsd), 0, false),
         false, false);
     if (arena_nthreads_get(arena, false) == 0 &&
         !background_thread_enabled()) {
         /* Force purging when no threads assigned to the arena anymore. */
         arena_decay(tsd_tsdn(tsd), arena, false, true);
     } else {
         arena_decay(tsd_tsdn(tsd), arena, false, false);
     }
 }
References tcache_s::arena, arena, arena_decay, arena_get(), arena_nthreads_get, cache_bin_s::avail, background_thread_enabled(), idalloctm(), NULL, tcache_arena_dissociate(), tcache_bin_info, tcache_flush_cache(), tcache_small_bin_get(), tsd_tsdn(), and uintptr_t.
Referenced by tcache_cleanup(), tcaches_destroy(), and tcaches_flush().
tcache_event_hard()
void tcache_event_hard (tsd_t * tsd, tcache_t * tcache)
Definition at line 41 of file tcache.c.
{
     szind_t binind = tcache->next_gc_bin;
     cache_bin_t *tbin;
     if (binind < SC_NBINS) {
         tbin = tcache_small_bin_get(tcache, binind);
     } else {
         tbin = tcache_large_bin_get(tcache, binind);
     }
     if (tbin->low_water > 0) {
         /*
          * Flush (ceiling) 3/4 of the objects below the low water mark.
          */
         if (binind < SC_NBINS) {
             tcache_bin_flush_small(tsd, tcache, tbin, binind,
                 tbin->ncached - tbin->low_water + (tbin->low_water
                 >> 2));
             /*
              * Reduce fill count by 2X.  Limit lg_fill_div such that
              * the fill count is always at least 1.
              */
             cache_bin_info_t *tbin_info = &tcache_bin_info[binind];
             if ((tbin_info->ncached_max >>
                  (tcache->lg_fill_div[binind] + 1)) >= 1) {
                 tcache->lg_fill_div[binind]++;
             }
         } else {
             tcache_bin_flush_large(tsd, tbin, binind, tbin->ncached
                 - tbin->low_water + (tbin->low_water >> 2), tcache);
         }
     } else if (tbin->low_water < 0) {
         /*
          * Increase fill count by 2X for small bins.  Make sure
          * lg_fill_div stays greater than 0.
          */
         if (binind < SC_NBINS && tcache->lg_fill_div[binind] > 1) {
             tcache->lg_fill_div[binind]--;
         }
     }
     tbin->low_water = tbin->ncached;
     tcache->next_gc_bin++;
     if (tcache->next_gc_bin == nhbins) {
         tcache->next_gc_bin = 0;
     }
 }
References tcache_s::lg_fill_div, cache_bin_s::low_water, cache_bin_s::ncached, cache_bin_info_s::ncached_max, tcache_s::next_gc_bin, nhbins, SC_NBINS, tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_bin_info, tcache_large_bin_get(), and tcache_small_bin_get().
tcache_flush()
void tcache_flush (tsd_t * tsd)
Definition at line 540 of file tcache.c.
{
     assert(tcache_available(tsd));
     tcache_flush_cache(tsd, tsd_tcachep_get(tsd));
 }
References assert(), tcache_available(), and tcache_flush_cache().
tcache_flush_cache()
static void tcache_flush_cache (tsd_t * tsd, tcache_t * tcache) static
Definition at line 512 of file tcache.c.
{
     assert(tcache->arena != NULL);
     for (unsigned i = 0; i < SC_NBINS; i++) {
         cache_bin_t *tbin = tcache_small_bin_get(tcache, i);
         tcache_bin_flush_small(tsd, tcache, tbin, i, 0);
         if (config_stats) {
             assert(tbin->tstats.nrequests == 0);
         }
     }
     for (unsigned i = SC_NBINS; i < nhbins; i++) {
         cache_bin_t *tbin = tcache_large_bin_get(tcache, i);
         tcache_bin_flush_large(tsd, tbin, i, 0, tcache);
         if (config_stats) {
             assert(tbin->tstats.nrequests == 0);
         }
     }
     if (config_prof && tcache->prof_accumbytes > 0 &&
         arena_prof_accum(tsd_tsdn(tsd), tcache->arena,
         tcache->prof_accumbytes)) {
         prof_idump(tsd_tsdn(tsd));
     }
 }
References tcache_s::arena, arena_prof_accum(), assert(), config_prof, config_stats, nhbins, cache_bin_stats_s::nrequests, NULL, tcache_s::prof_accumbytes, prof_idump, SC_NBINS, tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_large_bin_get(), tcache_small_bin_get(), tsd_tsdn(), and cache_bin_s::tstats.
Referenced by tcache_destroy(), and tcache_flush().
tcache_init()
static void tcache_init (tsd_t * tsd, tcache_t * tcache, void * avail_stack) static
Definition at line 410 of file tcache.c.
{
     memset(&tcache->link, 0, sizeof(ql_elm(tcache_t)));
     tcache->prof_accumbytes = 0;
     tcache->next_gc_bin = 0;
     tcache->arena = NULL;
     ticker_init(&tcache->gc_ticker, TCACHE_GC_INCR);
     size_t stack_offset = 0;
     assert((TCACHE_NSLOTS_SMALL_MAX & 1U) == 0);
     memset(tcache->bins_small, 0, sizeof(cache_bin_t) * SC_NBINS);
     memset(tcache->bins_large, 0, sizeof(cache_bin_t) * (nhbins - SC_NBINS));
     unsigned i = 0;
     for (; i < SC_NBINS; i++) {
         tcache->lg_fill_div[i] = 1;
         stack_offset += tcache_bin_info[i].ncached_max * sizeof(void *);
         /*
          * avail points past the available space.  Allocations will
          * access the slots toward higher addresses (for the benefit of
          * prefetch).
          */
         tcache_small_bin_get(tcache, i)->avail =
             (void **)((uintptr_t)avail_stack + (uintptr_t)stack_offset);
     }
     for (; i < nhbins; i++) {
         stack_offset += tcache_bin_info[i].ncached_max * sizeof(void *);
         tcache_large_bin_get(tcache, i)->avail =
             (void **)((uintptr_t)avail_stack + (uintptr_t)stack_offset);
     }
     assert(stack_offset == stack_nelms * sizeof(void *));
 }
References tcache_s::arena, assert(), cache_bin_s::avail, tcache_s::bins_large, tcache_s::bins_small, tcache_s::gc_ticker, tcache_s::lg_fill_div, memset, cache_bin_info_s::ncached_max, tcache_s::next_gc_bin, nhbins, NULL, tcache_s::prof_accumbytes, ql_elm(), SC_NBINS, stack_nelms, tcache_bin_info, TCACHE_GC_INCR, tcache_large_bin_get(), TCACHE_NSLOTS_SMALL_MAX, tcache_small_bin_get(), ticker_init(), and uintptr_t.
Referenced by tcache_create_explicit(), and tsd_tcache_data_init().
tcache_postfork_child()
void tcache_postfork_child (tsdn_t * tsdn)
Definition at line 794 of file tcache.c.
{
     if (!config_prof && opt_tcache) {
         malloc_mutex_postfork_child(tsdn, &tcaches_mtx);
     }
 }
References config_prof, malloc_mutex_postfork_child, opt_tcache, and tcaches_mtx.
tcache_postfork_parent()
void tcache_postfork_parent (tsdn_t * tsdn)
Definition at line 787 of file tcache.c.
{
     if (!config_prof && opt_tcache) {
         malloc_mutex_postfork_parent(tsdn, &tcaches_mtx);
     }
 }
References config_prof, malloc_mutex_postfork_parent, opt_tcache, and tcaches_mtx.
tcache_prefork()
void tcache_prefork (tsdn_t * tsdn)
Definition at line 780 of file tcache.c.
{
     if (!config_prof && opt_tcache) {
         malloc_mutex_prefork(tsdn, &tcaches_mtx);
     }
 }
References config_prof, malloc_mutex_prefork, opt_tcache, and tcaches_mtx.
tcache_salloc()
size_t tcache_salloc (tsdn_t * tsdn, const void * ptr)
Definition at line 36 of file tcache.c.
{
     return arena_salloc(tsdn, ptr);
 }
References arena_salloc(), and ptr().
tcache_stats_merge()
void tcache_stats_merge (tsdn_t * tsdn, tcache_t * tcache, arena_t * arena)
Definition at line 601 of file tcache.c.
{
     unsigned i;
     cassert(config_stats);
     /* Merge and reset tcache stats. */
     for (i = 0; i < SC_NBINS; i++) {
         cache_bin_t *tbin = tcache_small_bin_get(tcache, i);
         unsigned binshard;
         bin_t *bin = arena_bin_choose_lock(tsdn, arena, i, &binshard);
         bin->stats.nrequests += tbin->tstats.nrequests;
         malloc_mutex_unlock(tsdn, &bin->lock);
         tbin->tstats.nrequests = 0;
     }
     for (; i < nhbins; i++) {
         cache_bin_t *tbin = tcache_large_bin_get(tcache, i);
         arena_stats_large_flush_nrequests_add(tsdn, &arena->stats, i,
             tbin->tstats.nrequests);
         tbin->tstats.nrequests = 0;
     }
 }
References arena, arena_bin_choose_lock, arena_stats_large_flush_nrequests_add(), cassert(), config_stats, bin_s::lock, malloc_mutex_unlock(), nhbins, bin_stats_s::nrequests, cache_bin_stats_s::nrequests, SC_NBINS, arena_s::stats, bin_s::stats, tcache_large_bin_get(), tcache_small_bin_get(), and cache_bin_s::tstats.
Referenced by tcache_arena_dissociate().
tcaches_create()
bool tcaches_create (tsd_t * tsd, unsigned * r_ind)
Definition at line 651 of file tcache.c.
{
     witness_assert_depth(tsdn_witness_tsdp_get(tsd_tsdn(tsd)), 0);
     bool err;
     if (tcaches_create_prep(tsd)) {
         err = true;
         goto label_return;
     }
     tcache_t *tcache = tcache_create_explicit(tsd);
     if (tcache == NULL) {
         err = true;
         goto label_return;
     }
     tcaches_t *elm;
     malloc_mutex_lock(tsd_tsdn(tsd), &tcaches_mtx);
     if (tcaches_avail != NULL) {
         elm = tcaches_avail;
         tcaches_avail = tcaches_avail->next;
         elm->tcache = tcache;
         *r_ind = (unsigned)(elm - tcaches);
     } else {
         elm = &tcaches[tcaches_past];
         elm->tcache = tcache;
         *r_ind = tcaches_past;
         tcaches_past++;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), &tcaches_mtx);
     err = false;
 label_return:
     witness_assert_depth(tsdn_witness_tsdp_get(tsd_tsdn(tsd)), 0);
     return err;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), tcaches_s::next, NULL, tcaches_s::tcache, tcache_create_explicit(), tcaches, tcaches_avail, tcaches_create_prep(), tcaches_mtx, tcaches_past, tsd_tsdn(), and witness_assert_depth().
tcaches_create_prep()
static bool tcaches_create_prep (tsd_t * tsd) static
Definition at line 625 of file tcache.c.
{
     bool err;
     malloc_mutex_lock(tsd_tsdn(tsd), &tcaches_mtx);
     if (tcaches == NULL) {
         tcaches = base_alloc(tsd_tsdn(tsd), b0get(), sizeof(tcache_t *)
             * (MALLOCX_TCACHE_MAX+1), CACHELINE);
         if (tcaches == NULL) {
             err = true;
             goto label_return;
         }
     }
     if (tcaches_avail == NULL && tcaches_past > MALLOCX_TCACHE_MAX) {
         err = true;
         goto label_return;
     }
     err = false;
 label_return:
     malloc_mutex_unlock(tsd_tsdn(tsd), &tcaches_mtx);
     return err;
 }
References b0get, base_alloc, CACHELINE, malloc_mutex_lock(), malloc_mutex_unlock(), MALLOCX_TCACHE_MAX, NULL, tcaches, tcaches_avail, tcaches_mtx, tcaches_past, and tsd_tsdn().
Referenced by tcaches_create().
tcaches_destroy()
void tcaches_destroy (tsd_t * tsd, unsigned ind)
Definition at line 720 of file tcache.c.
{
     malloc_mutex_lock(tsd_tsdn(tsd), &tcaches_mtx);
     tcaches_t *elm = &tcaches[ind];
     tcache_t *tcache = tcaches_elm_remove(tsd, elm, false);
     elm->next = tcaches_avail;
     tcaches_avail = elm;
     malloc_mutex_unlock(tsd_tsdn(tsd), &tcaches_mtx);
     if (tcache != NULL) {
         tcache_destroy(tsd, tcache, false);
     }
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), tcaches_s::next, NULL, tcache_destroy(), tcaches, tcaches_avail, tcaches_elm_remove(), tcaches_mtx, and tsd_tsdn().
tcaches_elm_remove()
static tcache_t* tcaches_elm_remove (tsd_t * tsd, tcaches_t * elm, bool allow_reinit) static
Definition at line 689 of file tcache.c.
{
     malloc_mutex_assert_owner(tsd_tsdn(tsd), &tcaches_mtx);
     if (elm->tcache == NULL) {
         return NULL;
     }
     tcache_t *tcache = elm->tcache;
     if (allow_reinit) {
         elm->tcache = TCACHES_ELM_NEED_REINIT;
     } else {
         elm->tcache = NULL;
     }
     if (tcache == TCACHES_ELM_NEED_REINIT) {
         return NULL;
     }
     return tcache;
 }
References malloc_mutex_assert_owner(), NULL, tcaches_s::tcache, TCACHES_ELM_NEED_REINIT, tcaches_mtx, and tsd_tsdn().
Referenced by tcaches_destroy(), and tcaches_flush().
tcaches_flush()
void tcaches_flush (tsd_t * tsd, unsigned ind)
Definition at line 709 of file tcache.c.
{
     malloc_mutex_lock(tsd_tsdn(tsd), &tcaches_mtx);
     tcache_t *tcache = tcaches_elm_remove(tsd, &tcaches[ind], true);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tcaches_mtx);
     if (tcache != NULL) {
         /* Destroy the tcache; recreate in tcaches_get() if needed. */
         tcache_destroy(tsd, tcache, false);
     }
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), NULL, tcache_destroy(), tcaches, tcaches_elm_remove(), tcaches_mtx, and tsd_tsdn().
tsd_tcache_data_init()
bool tsd_tcache_data_init (tsd_t * tsd)
Definition at line 444 of file tcache.c.
{
     tcache_t *tcache = tsd_tcachep_get_unsafe(tsd);
     assert(tcache_small_bin_get(tcache, 0)->avail == NULL);
     size_t size = stack_nelms * sizeof(void *);
     /* Avoid false cacheline sharing. */
     size = sz_sa2u(size, CACHELINE);
     void *avail_array = ipallocztm(tsd_tsdn(tsd), size, CACHELINE, true,
         NULL, true, arena_get(TSDN_NULL, 0, true));
     if (avail_array == NULL) {
         return true;
     }
     tcache_init(tsd, tcache, avail_array);
     /*
      * Initialization is a bit tricky here.  After malloc init is done, all
      * threads can rely on arena_choose and associate tcache accordingly.
      * However, the thread that does actual malloc bootstrapping relies on
      * functional tsd, and it can only rely on a0.  In that case, we
      * associate its tcache to a0 temporarily, and later on
      * arena_choose_hard() will re-associate properly.
      */
     tcache->arena = NULL;
     arena_t *arena;
     if (!malloc_initialized()) {
         /* If in initialization, assign to a0. */
         arena = arena_get(tsd_tsdn(tsd), 0, false);
         tcache_arena_associate(tsd_tsdn(tsd), tcache, arena);
     } else {
         arena = arena_choose(tsd, NULL);
         /* This may happen if thread.tcache.enabled is used. */
         if (tcache->arena == NULL) {
             tcache_arena_associate(tsd_tsdn(tsd), tcache, arena);
         }
     }
     assert(arena == tcache->arena);
     return false;
 }
References tcache_s::arena, arena, arena_choose(), arena_get(), assert(), CACHELINE, ipallocztm(), malloc_initialized, NULL, stack_nelms, sz_sa2u(), tcache_arena_associate(), tcache_init(), tcache_small_bin_get(), tsd_tsdn(), and TSDN_NULL.
Referenced by tsd_tcache_enabled_data_init().
tsd_tcache_enabled_data_init()
bool tsd_tcache_enabled_data_init (tsd_t * tsd)
Definition at line 395 of file tcache.c.
{
     /* Called upon tsd initialization. */
     tsd_tcache_enabled_set(tsd, opt_tcache);
     tsd_slow_update(tsd);
     if (opt_tcache) {
         /* Trigger tcache init. */
         tsd_tcache_data_init(tsd);
     }
     return false;
 }
References opt_tcache, tsd_slow_update, and tsd_tcache_data_init().
Variable Documentation
nhbins
unsigned nhbins
Definition at line 19 of file tcache.c.
Referenced by tcache_bin_flush_large(), tcache_boot(), tcache_event_hard(), tcache_flush_cache(), tcache_init(), and tcache_stats_merge().
opt_lg_tcache_max
ssize_t opt_lg_tcache_max = LG_TCACHE_MAXCLASS_DEFAULT
Definition at line 14 of file tcache.c.
Referenced by tcache_boot().
opt_tcache
bool opt_tcache = true
Definition at line 13 of file tcache.c.
Referenced by tcache_postfork_child(), tcache_postfork_parent(), tcache_prefork(), and tsd_tcache_enabled_data_init().
stack_nelms
unsigned stack_nelms static
Definition at line 17 of file tcache.c.
Referenced by tcache_boot(), tcache_create_explicit(), tcache_init(), and tsd_tcache_data_init().
tcache_bin_info
cache_bin_info_t* tcache_bin_info
Definition at line 16 of file tcache.c.
Referenced by tcache_boot(), tcache_destroy(), tcache_event_hard(), and tcache_init().
tcache_maxclass
size_t tcache_maxclass
Definition at line 20 of file tcache.c.
Referenced by tcache_boot().
tcaches
tcaches_t* tcaches
Definition at line 22 of file tcache.c.
Referenced by tcaches_create(), tcaches_create_prep(), tcaches_destroy(), and tcaches_flush().
tcaches_avail
tcaches_t* tcaches_avail static
Definition at line 28 of file tcache.c.
Referenced by tcaches_create(), tcaches_create_prep(), and tcaches_destroy().
tcaches_mtx
malloc_mutex_t tcaches_mtx static
Definition at line 31 of file tcache.c.
Referenced by tcache_boot(), tcache_postfork_child(), tcache_postfork_parent(), tcache_prefork(), tcaches_create(), tcaches_create_prep(), tcaches_destroy(), tcaches_elm_remove(), and tcaches_flush().
tcaches_past
unsigned tcaches_past static
Definition at line 25 of file tcache.c.
Referenced by tcaches_create(), and tcaches_create_prep().