Azerotcore-wotlk: WorldModelDefinition Struct Reference
WorldModelDefinition Struct Reference
#include <WorldModelHandler.h>
Public Member Functions
WorldModelDefinition ()
Public Member Functions inherited from IDefinition
virtual float Scale () const
Static Public Member Functions
static WorldModelDefinition Read (FILE *file)
Public Attributes
uint32 MwidIndex
uint32 UniqueId
Vector3 UpperExtents
Vector3 LowerExtents
uint16 Flags
uint16 DoodadSet
Public Attributes inherited from IDefinition
Vector3 Position
Vector3 Rotation
Detailed Description
Definition at line 30 of file WorldModelHandler.h.
Constructor & Destructor Documentation
WorldModelDefinition()
WorldModelDefinition::WorldModelDefinition () inline
Definition at line 33 of file WorldModelHandler.h.
 {}
Member Function Documentation
Read()
WorldModelDefinition WorldModelDefinition::Read (FILE * file) static
Definition at line 28 of file WorldModelHandler.cpp.
 {
     WorldModelDefinition ret;
     int count = 0;
     count += fread(&ret.MwidIndex, sizeof(uint32), 1, file);
     count += fread(&ret.UniqueId, sizeof(uint32), 1, file);
     ret.Position = Vector3::Read(file);
     ret.Rotation = Vector3::Read(file);
     ret.UpperExtents = Vector3::Read(file);
     ret.LowerExtents = Vector3::Read(file);
     count += fread(&ret.Flags, sizeof(uint16), 1, file);
     count += fread(&ret.DoodadSet, sizeof(uint16), 1, file);
     uint32 discard;
     count += fread(&discard, sizeof(uint32), 1, file);
     if (count != 5)
         printf("WorldModelDefinition::Read: Error reading data, expected 5, read %d\n", count);
     return ret;
 }
References count(), mpq::file, printf(), Vector3::Read(), and ret.
Referenced by WorldModelHandler::ReadDefinitions(), and WDT::ReadGlobalModel().
Member Data Documentation
DoodadSet
uint16 WorldModelDefinition::DoodadSet
Definition at line 40 of file WorldModelHandler.h.
Referenced by WorldModelHandler::InsertModelGeometry().
Flags
uint16 WorldModelDefinition::Flags
Definition at line 39 of file WorldModelHandler.h.
LowerExtents
Vector3 WorldModelDefinition::LowerExtents
Definition at line 38 of file WorldModelHandler.h.
MwidIndex
uint32 WorldModelDefinition::MwidIndex
Definition at line 35 of file WorldModelHandler.h.
Referenced by WorldModelHandler::ProcessInternal().
UniqueId
uint32 WorldModelDefinition::UniqueId
Definition at line 36 of file WorldModelHandler.h.
Referenced by WorldModelHandler::ProcessInternal().
UpperExtents
Vector3 WorldModelDefinition::UpperExtents
Definition at line 37 of file WorldModelHandler.h.
The documentation for this struct was generated from the following files:
src/tools/mesh_extractor/WorldModelHandler.h
src/tools/mesh_extractor/WorldModelHandler.cpp