Azerotcore-wotlk: Acore::AnyDeadUnitObjectInRangeCheck Class Reference
Acore::AnyDeadUnitObjectInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyDeadUnitObjectInRangeCheck (Unit *searchObj, float range)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Protected Attributes
Unit const *const i_searchObj
float i_range
Detailed Description
Definition at line 580 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyDeadUnitObjectInRangeCheck()
Acore::AnyDeadUnitObjectInRangeCheck::AnyDeadUnitObjectInRangeCheck (Unit * searchObj, float range) inline
Definition at line 583 of file GridNotifiers.h.
 : i_searchObj(searchObj), i_range(range) {}
Member Function Documentation
operator()() [1/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Corpse * u)
Definition at line 359 of file GridNotifiers.cpp.
 {
     return u->GetType() != CORPSE_BONES && i_searchObj->IsWithinDistInMap(u, i_range);
 }
References CORPSE_BONES, Corpse::GetType(), i_range, i_searchObj, and WorldObject::IsWithinDistInMap().
operator()() [2/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Creature * u)
Definition at line 364 of file GridNotifiers.cpp.
 {
     return !u->IsAlive() && i_searchObj->IsWithinDistInMap(u, i_range);
 }
References i_range, i_searchObj, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
operator()() [3/4]
template<class NOT_INTERESTED > bool Acore::AnyDeadUnitObjectInRangeCheck::operator() (NOT_INTERESTED *) inline
Definition at line 587 of file GridNotifiers.h.
 { return false; }
operator()() [4/4]
bool AnyDeadUnitObjectInRangeCheck::operator() (Player * u)
Definition at line 354 of file GridNotifiers.cpp.
 {
     return !u->IsAlive() && !u->HasAuraType(SPELL_AURA_GHOST) && i_searchObj->IsWithinDistInMap(u, i_range);
 }
References Unit::HasAuraType(), i_range, i_searchObj, Unit::IsAlive(), WorldObject::IsWithinDistInMap(), and SPELL_AURA_GHOST.
Referenced by Acore::AnyDeadUnitSpellTargetInRangeCheck::operator()().
Member Data Documentation
i_range
float Acore::AnyDeadUnitObjectInRangeCheck::i_range protected
Definition at line 590 of file GridNotifiers.h.
Referenced by operator()().
i_searchObj
Unit const* const Acore::AnyDeadUnitObjectInRangeCheck::i_searchObj protected
Definition at line 589 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp