Azerotcore-wotlk: MailDraft Class Reference
MailDraft Class Reference
#include <Mail.h>
Public Member Functions
MailDraft (uint16 mailTemplateId, bool need_items=true)
MailDraft (std::string subject, std::string body)
uint16 GetMailTemplateId () const
std::string const & GetSubject () const
uint32 GetMoney () const
uint32 GetCOD () const
std::string const & GetBody () const
MailDraft & AddItem (Item *item)
MailDraft & AddMoney (uint32 money)
MailDraft & AddCOD (uint32 COD)
void SendReturnToSender (uint32 sender_acc, ObjectGuid::LowType sender_guid, ObjectGuid::LowType receiver_guid, CharacterDatabaseTransaction trans)
void SendMailTo (CharacterDatabaseTransaction trans, MailReceiver const &receiver, MailSender const &sender, MailCheckMask checked=MAIL_CHECK_MASK_NONE, uint32 deliver_delay=0, uint32 custom_expiration=0, bool deleteMailItemsFromDB=false, bool sendMail=true, int32 auctionId=0)
Private Types
typedef std::map< ObjectGuid, Item * > MailItemMap
Private Member Functions
void deleteIncludedItems (CharacterDatabaseTransaction trans, bool inDB=false)
void prepareItems (Player *receiver, CharacterDatabaseTransaction trans)
Private Attributes
uint16 m_mailTemplateId
bool m_mailTemplateItemsNeed
std::string m_subject
std::string m_body
MailItemMap m_items
uint32 m_money
uint32 m_COD
Detailed Description
Definition at line 117 of file Mail.h.
Member Typedef Documentation
MailItemMap
typedef std::map<ObjectGuid, Item*> MailDraft::MailItemMap private
Definition at line 119 of file Mail.h.
Constructor & Destructor Documentation
MailDraft() [1/2]
MailDraft::MailDraft (uint16 mailTemplateId, bool need_items = true) inline explicit
Definition at line 122 of file Mail.h.
         : m_mailTemplateId(mailTemplateId), m_mailTemplateItemsNeed(need_items), m_money(0), m_COD(0)
     {}
MailDraft() [2/2]
MailDraft::MailDraft (std::string subject, std::string body) inline
Definition at line 125 of file Mail.h.
         : m_mailTemplateId(0), m_mailTemplateItemsNeed(false), m_subject(std::move(subject)), m_body(std::move(body)), m_money(0), m_COD(0) {}
Member Function Documentation
AddCOD()
MailDraft& MailDraft::AddCOD (uint32 COD) inline
Definition at line 137 of file Mail.h.
 { m_COD = COD; return *this; }
References m_COD.
Referenced by WorldSession::HandleSendMail().
AddItem()
MailDraft & MailDraft::AddItem (Item * item)
Definition at line 92 of file Mail.cpp.
 {
     m_items[item->GetGUID()] = item;
     return *this;
 }
References Object::GetGUID(), and m_items.
Referenced by Player::_LoadInventory(), Player::AutoUnequipOffhandIfNeed(), AchievementMgr::CompletedAchievement(), Player::DeleteFromDB(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleMailReturnToSender(), misc_commandscript::HandleSendItemsCommand(), WorldSession::HandleSendMail(), prepareItems(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionWonMail(), and Player::SendItemRetrievalMail().
AddMoney()
MailDraft& MailDraft::AddMoney (uint32 money) inline
Definition at line 136 of file Mail.h.
 { m_money = money; return *this; }
References m_money.
Referenced by Player::DeleteFromDB(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleSendMail(), misc_commandscript::HandleSendMoneyCommand(), AuctionHouseMgr::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionOutbiddedMail(), and AuctionHouseMgr::SendAuctionSuccessfulMail().
deleteIncludedItems()
void MailDraft::deleteIncludedItems (CharacterDatabaseTransaction trans, bool inDB = false) private
Definition at line 124 of file Mail.cpp.
 {
     for (MailItemMap::iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
     {
         Item* item = mailItemIter->second;
         if (inDB)
         {
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ITEM_INSTANCE);
             stmt->setUInt32(0, item->GetGUID().GetCounter());
             trans->Append(stmt);
         }
         delete item;
     }
     m_items.clear();
 }
References CHAR_DEL_ITEM_INSTANCE, CharacterDatabase, ObjectGuid::GetCounter(), Object::GetGUID(), m_items, and PreparedStatementBase::setUInt32().
Referenced by SendMailTo(), and SendReturnToSender().
GetBody()
std::string const& MailDraft::GetBody () const inline
Definition at line 132 of file Mail.h.
 { return m_body; }
References m_body.
Referenced by SendMailTo().
GetCOD()
uint32 MailDraft::GetCOD () const inline
Definition at line 131 of file Mail.h.
 { return m_COD; }
References m_COD.
Referenced by SendMailTo().
GetMailTemplateId()
uint16 MailDraft::GetMailTemplateId () const inline
Definition at line 128 of file Mail.h.
 { return m_mailTemplateId; }
References m_mailTemplateId.
Referenced by SendMailTo().
GetMoney()
uint32 MailDraft::GetMoney () const inline
Definition at line 130 of file Mail.h.
 { return m_money; }
References m_money.
Referenced by SendMailTo().
GetSubject()
std::string const& MailDraft::GetSubject () const inline
Definition at line 129 of file Mail.h.
 { return m_subject; }
References m_subject.
Referenced by SendMailTo().
prepareItems()
void MailDraft::prepareItems (Player * receiver, CharacterDatabaseTransaction trans) private
Definition at line 98 of file Mail.cpp.
 {
     if (!m_mailTemplateId || !m_mailTemplateItemsNeed)
         return;
     m_mailTemplateItemsNeed = false;
     Loot mailLoot;
     // can be empty
     mailLoot.FillLoot(m_mailTemplateId, LootTemplates_Mail, receiver, true, true);
     uint32 max_slot = mailLoot.GetMaxSlotInLootFor(receiver);
     for (uint32 i = 0; m_items.size() < MAX_MAIL_ITEMS && i < max_slot; ++i)
     {
         if (LootItem* lootitem = mailLoot.LootItemInSlot(i, receiver))
         {
             if (Item* item = Item::CreateItem(lootitem->itemid, lootitem->count, receiver))
             {
                 item->SaveToDB(trans);                           // save for prevent lost at next mail load, if send fail then item will deleted
                 AddItem(item);
             }
         }
     }
 }
References AddItem(), Item::CreateItem(), Loot::FillLoot(), Loot::GetMaxSlotInLootFor(), Loot::LootItemInSlot(), LootTemplates_Mail, m_items, m_mailTemplateId, m_mailTemplateItemsNeed, and MAX_MAIL_ITEMS.
Referenced by SendMailTo().
SendMailTo()
void MailDraft::SendMailTo (CharacterDatabaseTransaction trans, MailReceiver const & receiver, MailSender const & sender, MailCheckMask checked = MAIL_CHECK_MASK_NONE, uint32 deliver_delay = 0, uint32 custom_expiration = 0, bool deleteMailItemsFromDB = false, bool sendMail = true, int32 auctionId = 0)
Definition at line 181 of file Mail.cpp.
 {
     sScriptMgr->OnBeforeMailDraftSendMailTo(this, receiver, sender, checked, deliver_delay, custom_expiration, deleteMailItemsFromDB, sendMail);
     if (deleteMailItemsFromDB) // can be changed in the hook
         deleteIncludedItems(trans, true);
     if (!sendMail) // can be changed in the hook
         return;
     Player* pReceiver = receiver.GetPlayer();               // can be nullptr
     Player* pSender = ObjectAccessor::FindPlayerByLowGUID(sender.GetSenderId());
     if (pReceiver)
         prepareItems(pReceiver, trans);                            // generate mail template items
     uint32 mailId = sObjectMgr->GenerateMailID();
     time_t deliver_time = time(nullptr) + deliver_delay;
     //expire time if COD 3 days, if no COD 30 days, if auction sale pending 1 hour
     uint32 expire_delay;
     // auction mail without any items and money
     if (sender.GetMailMessageType() == MAIL_AUCTION && m_items.empty() && !m_money)
         expire_delay = sWorld->getIntConfig(CONFIG_MAIL_DELIVERY_DELAY);
     // mail from battlemaster (rewardmarks) should last only one day
     else if (sender.GetMailMessageType() == MAIL_CREATURE && sBattlegroundMgr->GetBattleMasterBG(sender.GetSenderId()) != BATTLEGROUND_TYPE_NONE)
         expire_delay = DAY;
     // default case: expire time if COD 3 days, if no COD 30 days (or 90 days if sender is a game master)
     else
     {
         if (m_COD)
             expire_delay = 3 * DAY;
         else if (custom_expiration > 0 )
             expire_delay = custom_expiration * DAY;
         else
             expire_delay = pSender && pSender->GetSession()->GetSecurity() ? 90 * DAY : 30 * DAY;
     }
     time_t expire_time = deliver_time + expire_delay;
     // Add to DB
     uint8 index = 0;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_MAIL);
     stmt->setUInt32(  index, mailId);
     stmt->setUInt8 (++index, uint8(sender.GetMailMessageType()));
     stmt->setInt8  (++index, int8(sender.GetStationery()));
     stmt->setUInt16(++index, GetMailTemplateId());
     stmt->setUInt32(++index, sender.GetSenderId());
     stmt->setUInt32(++index, receiver.GetPlayerGUIDLow());
     stmt->setString(++index, GetSubject());
     stmt->setString(++index, GetBody());
     stmt->setBool  (++index, !m_items.empty());
     stmt->setUInt32(++index, uint32(expire_time));
     stmt->setUInt32(++index, uint32(deliver_time));
     stmt->setUInt32(++index, m_money);
     stmt->setUInt32(++index, m_COD);
     stmt->setUInt8 (++index, uint8(checked));
     stmt->setInt32(++index, auctionId);
     trans->Append(stmt);
     for (MailItemMap::const_iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
     {
         Item* pItem = mailItemIter->second;
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_MAIL_ITEM);
         stmt->setUInt32(0, mailId);
         stmt->setUInt32(1, pItem->GetGUID().GetCounter());
         stmt->setUInt32(2, receiver.GetPlayerGUIDLow());
         trans->Append(stmt);
     }
     // xinef: update global data
     sWorld->UpdateGlobalPlayerMails(receiver.GetPlayerGUIDLow(), 1);
     // For online receiver update in game mail status and data
     if (pReceiver)
     {
         pReceiver->AddNewMailDeliverTime(deliver_time);
         Mail* m = new Mail;
         m->messageID = mailId;
         m->mailTemplateId = GetMailTemplateId();
         m->subject = GetSubject();
         m->body = GetBody();
         m->money = GetMoney();
         m->COD = GetCOD();
         for (MailItemMap::const_iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
         {
             Item* item = mailItemIter->second;
             m->AddItem(item->GetGUID().GetCounter(), item->GetEntry());
         }
         m->messageType = sender.GetMailMessageType();
         m->stationery = sender.GetStationery();
         m->sender = sender.GetSenderId();
         m->receiver = receiver.GetPlayerGUIDLow();
         m->expire_time = expire_time;
         m->deliver_time = deliver_time;
         m->checked = checked;
         m->auctionId = auctionId;
         m->state = MAIL_STATE_UNCHANGED;
         pReceiver->AddMail(m);                           // to insert new mail to beginning of maillist
         if (!m_items.empty())
         {
             for (MailItemMap::iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
             {
                 pReceiver->AddMItem(mailItemIter->second);
             }
         }
     }
     else if (!m_items.empty())
     {
         CharacterDatabaseTransaction temp = CharacterDatabaseTransaction(nullptr);
         deleteIncludedItems(temp);
     }
 }
References Mail::AddItem(), Player::AddMail(), Player::AddMItem(), Player::AddNewMailDeliverTime(), Mail::auctionId, BATTLEGROUND_TYPE_NONE, Mail::body, CHAR_INS_MAIL, CHAR_INS_MAIL_ITEM, CharacterDatabase, Mail::checked, Mail::COD, CONFIG_MAIL_DELIVERY_DELAY, DAY, deleteIncludedItems(), Mail::deliver_time, Mail::expire_time, ObjectAccessor::FindPlayerByLowGUID(), GetBody(), GetCOD(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUID(), MailSender::GetMailMessageType(), GetMailTemplateId(), GetMoney(), MailReceiver::GetPlayer(), MailReceiver::GetPlayerGUIDLow(), WorldSession::GetSecurity(), MailSender::GetSenderId(), Player::GetSession(), MailSender::GetStationery(), GetSubject(), m_COD, m_items, m_money, MAIL_AUCTION, MAIL_CREATURE, MAIL_STATE_UNCHANGED, Mail::mailTemplateId, Mail::messageID, Mail::messageType, Mail::money, prepareItems(), Mail::receiver, sBattlegroundMgr, Mail::sender, PreparedStatementBase::setBool(), PreparedStatementBase::setInt32(), PreparedStatementBase::setInt8(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sObjectMgr, sScriptMgr, Mail::state, Mail::stationery, Mail::subject, and sWorld.
Referenced by Player::_LoadBrewOfTheMonth(), Player::_LoadInventory(), Player::AutoUnequipOffhandIfNeed(), AchievementMgr::CompletedAchievement(), Player::GiveLevel(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleMailTakeItem(), misc_commandscript::HandleSendItemsCommand(), WorldSession::HandleSendMail(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMoneyCommand(), CalendarMgr::RemoveEvent(), Player::RewardQuest(), AuctionHouseMgr::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionSalePendingMail(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), Player::SendItemRetrievalMail(), npc_minigob_manabonk::npc_minigob_manabonkAI::SendMailToPlayer(), and SendReturnToSender().
SendReturnToSender()
void MailDraft::SendReturnToSender (uint32 sender_acc, ObjectGuid::LowType sender_guid, ObjectGuid::LowType receiver_guid, CharacterDatabaseTransaction trans)
Definition at line 143 of file Mail.cpp.
 {
     Player* receiver = ObjectAccessor::FindPlayerByLowGUID(receiver_guid);
     uint32 rc_account = 0;
     if (!receiver)
         rc_account = sObjectMgr->GetPlayerAccountIdByGUID(receiver_guid);
     if (!receiver && !rc_account)                            // sender not exist
     {
         deleteIncludedItems(trans, true);
         return;
     }
     if (!m_items.empty())
     {
         // if item send to character at another account, then apply item delivery delay
         //needItemDelay = sender_acc != rc_account;
         // set owner to new receiver (to prevent delete item with sender char deleting)
         for (MailItemMap::iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
         {
             Item* item = mailItemIter->second;
             item->SaveToDB(trans);                      // item not in inventory and can be save standalone
             // owner in data will set at mail receive and item extracting
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ITEM_OWNER);
             stmt->setUInt32(0, receiver_guid);
             stmt->setUInt32(1, item->GetGUID().GetCounter());
             trans->Append(stmt);
         }
     }
     // xinef: WowWiki: "Return mail arrives immediately."
     // will delete item or place to receiver mail list
     SendMailTo(trans, MailReceiver(receiver, receiver_guid), MailSender(MAIL_NORMAL, sender_guid), MAIL_CHECK_MASK_RETURNED, 0);
 }
References CHAR_UPD_ITEM_OWNER, CharacterDatabase, deleteIncludedItems(), ObjectAccessor::FindPlayerByLowGUID(), ObjectGuid::GetCounter(), Object::GetGUID(), m_items, MAIL_CHECK_MASK_RETURNED, MAIL_NORMAL, Item::SaveToDB(), SendMailTo(), PreparedStatementBase::setUInt32(), and sObjectMgr.
Referenced by Player::DeleteFromDB(), and WorldSession::HandleMailReturnToSender().
Member Data Documentation
m_body
std::string MailDraft::m_body private
Definition at line 150 of file Mail.h.
Referenced by GetBody().
m_COD
uint32 MailDraft::m_COD private
Definition at line 155 of file Mail.h.
Referenced by AddCOD(), GetCOD(), and SendMailTo().
m_items
MailItemMap MailDraft::m_items private
Definition at line 152 of file Mail.h.
Referenced by AddItem(), deleteIncludedItems(), prepareItems(), SendMailTo(), and SendReturnToSender().
m_mailTemplateId
uint16 MailDraft::m_mailTemplateId private
Definition at line 147 of file Mail.h.
Referenced by GetMailTemplateId(), and prepareItems().
m_mailTemplateItemsNeed
bool MailDraft::m_mailTemplateItemsNeed private
Definition at line 148 of file Mail.h.
Referenced by prepareItems().
m_money
uint32 MailDraft::m_money private
Definition at line 154 of file Mail.h.
Referenced by AddMoney(), GetMoney(), and SendMailTo().
m_subject
std::string MailDraft::m_subject private
Definition at line 149 of file Mail.h.
Referenced by GetSubject().
The documentation for this class was generated from the following files:
src/server/game/Mails/Mail.h
src/server/game/Mails/Mail.cpp