Azerotcore-wotlk: deps/recastnavigation/Detour/Include/DetourCommon.h File Reference
DetourCommon.h File Reference
#include "DetourMath.h"
#include <stddef.h>
Functions
General helper functions
template<class T >
void dtIgnoreUnused (const T &)
template<class T >
void dtSwap (T &a, T &b)
template<class T >
T dtMin (T a, T b)
template<class T >
T dtMax (T a, T b)
template<class T >
T dtAbs (T a)
template<class T >
T dtSqr (T a)
template<class T >
T dtClamp (T v, T mn, T mx)
Vector helper functions.
void dtVcross (float *dest, const float *v1, const float *v2)
float dtVdot (const float *v1, const float *v2)
void dtVmad (float *dest, const float *v1, const float *v2, const float s)
void dtVlerp (float *dest, const float *v1, const float *v2, const float t)
void dtVadd (float *dest, const float *v1, const float *v2)
void dtVsub (float *dest, const float *v1, const float *v2)
void dtVscale (float *dest, const float *v, const float t)
void dtVmin (float *mn, const float *v)
void dtVmax (float *mx, const float *v)
void dtVset (float *dest, const float x, const float y, const float z)
void dtVcopy (float *dest, const float *a)
float dtVlen (const float *v)
float dtVlenSqr (const float *v)
float dtVdist (const float *v1, const float *v2)
float dtVdistSqr (const float *v1, const float *v2)
float dtVdist2D (const float *v1, const float *v2)
float dtVdist2DSqr (const float *v1, const float *v2)
void dtVnormalize (float *v)
bool dtVequal (const float *p0, const float *p1)
bool dtVisfinite (const float *v)
bool dtVisfinite2D (const float *v)
float dtVdot2D (const float *u, const float *v)
float dtVperp2D (const float *u, const float *v)
Computational geometry helper functions.
float dtTriArea2D (const float *a, const float *b, const float *c)
bool dtOverlapQuantBounds (const unsigned short amin[3], const unsigned short amax[3], const unsigned short bmin[3], const unsigned short bmax[3])
bool dtOverlapBounds (const float *amin, const float *amax, const float *bmin, const float *bmax)
void dtClosestPtPointTriangle (float *closest, const float *p, const float *a, const float *b, const float *c)
bool dtClosestHeightPointTriangle (const float *p, const float *a, const float *b, const float *c, float &h)
bool dtIntersectSegmentPoly2D (const float *p0, const float *p1, const float *verts, int nverts, float &tmin, float &tmax, int &segMin, int &segMax)
bool dtIntersectSegSeg2D (const float *ap, const float *aq, const float *bp, const float *bq, float &s, float &t)
bool dtPointInPolygon (const float *pt, const float *verts, const int nverts)
bool dtDistancePtPolyEdgesSqr (const float *pt, const float *verts, const int nverts, float *ed, float *et)
float dtDistancePtSegSqr2D (const float *pt, const float *p, const float *q, float &t)
void dtCalcPolyCenter (float *tc, const unsigned short *idx, int nidx, const float *verts)
bool dtOverlapPolyPoly2D (const float *polya, const int npolya, const float *polyb, const int npolyb)
Miscellanious functions.
unsigned int dtNextPow2 (unsigned int v)
unsigned int dtIlog2 (unsigned int v)
int dtAlign4 (int x)
int dtOppositeTile (int side)
void dtSwapByte (unsigned char *a, unsigned char *b)
void dtSwapEndian (unsigned short *v)
void dtSwapEndian (short *v)
void dtSwapEndian (unsigned int *v)
void dtSwapEndian (int *v)
void dtSwapEndian (float *v)
void dtRandomPointInConvexPoly (const float *pts, const int npts, float *areas, const float s, const float t, float *out)
template<typename TypeToRetrieveAs >
TypeToRetrieveAs * dtGetThenAdvanceBufferPointer (const unsigned char *&buffer, const size_t distanceToAdvance)
template<typename TypeToRetrieveAs >
TypeToRetrieveAs * dtGetThenAdvanceBufferPointer (unsigned char *&buffer, const size_t distanceToAdvance)
Function Documentation
dtAbs()
template<class T > T dtAbs (T a) inline
Returns the absolute value.
Parameters
[in] a The value.
Returns
The absolute value of the specified value.
Definition at line 63 of file DetourCommon.h.
 { return a < 0 ? -a : a; }
References mpq::a.
Referenced by dtNavMesh::findConnectingPolys(), dtNavMesh::findNearestPolyInTile(), and dtFindNearestPolyQuery::process().
dtAlign4()
int dtAlign4 (int x) inline
Definition at line 464 of file DetourCommon.h.
 { return (x+3) & ~3; }
References G3D::x.
Referenced by dtNavMesh::addTile(), dtCreateNavMeshData(), dtNavMeshDataSwapEndian(), dtNavMesh::getTileStateSize(), dtNavMesh::restoreTileState(), and dtNavMesh::storeTileState().
dtCalcPolyCenter()
void dtCalcPolyCenter (float * tc, const unsigned short * idx, int nidx, const float * verts)
Derives the centroid of a convex polygon.
Parameters
[out] tc The centroid of the polgyon. [(x, y, z)]
[in] idx The polygon indices. [(vertIndex) * nidx]
[in] nidx The number of indices in the polygon. [Limit: >= 3]
[in] verts The polygon vertices. [(x, y, z) * vertCount]
Definition at line 186 of file DetourCommon.cpp.
 {
     tc[0] = 0.0f;
     tc[1] = 0.0f;
     tc[2] = 0.0f;
     for (int j = 0; j < nidx; ++j)
     {
         const float* v = &verts[idx[j]*3];
         tc[0] += v[0];
         tc[1] += v[1];
         tc[2] += v[2];
     }
     const float s = 1.0f / nidx;
     tc[0] *= s;
     tc[1] *= s;
     tc[2] *= s;
 }
References idx.
dtClamp()
template<class T > T dtClamp (T v, T mn, T mx) inline
Clamps the value to the specified range.
Parameters
[in] v The value to clamp.
[in] mn The minimum permitted return value.
[in] mx The maximum permitted return value.
Returns
The value, clamped to the specified range.
Definition at line 75 of file DetourCommon.h.
 { return v < mn ? mn : (v > mx ? mx : v); }
Referenced by dtNavMesh::connectExtLinks(), createBVTree(), dtNavMeshQuery::queryPolygonsInTile(), and dtNavMesh::queryPolygonsInTile().
dtClosestHeightPointTriangle()
bool dtClosestHeightPointTriangle (const float * p, const float * a, const float * b, const float * c, float & h)
Derives the y-axis height of the closest point on the triangle from the specified reference point.
Parameters
[in] p The reference point from which to test. [(x, y, z)]
[in] a Vertex A of triangle ABC. [(x, y, z)]
[in] b Vertex B of triangle ABC. [(x, y, z)]
[in] c Vertex C of triangle ABC. [(x, y, z)]
[out] h The resulting height.
Definition at line 204 of file DetourCommon.cpp.
 {
     const float EPS = 1e-6f;
     float v0[3], v1[3], v2[3];
     dtVsub(v0, c, a);
     dtVsub(v1, b, a);
     dtVsub(v2, p, a);
     // Compute scaled barycentric coordinates
     float denom = v0[0] * v1[2] - v0[2] * v1[0];
     if (fabsf(denom) < EPS)
         return false;
     float u = v1[2] * v2[0] - v1[0] * v2[2];
     float v = v0[0] * v2[2] - v0[2] * v2[0];
     if (denom < 0) {
         denom = -denom;
         u = -u;
         v = -v;
     }
     // If point lies inside the triangle, return interpolated ycoord.
     if (u >= 0.0f && v >= 0.0f && (u + v) <= denom) {
         h = a[1] + (v0[1] * u + v1[1] * v) / denom;
         return true;
     }
     return false;
 }
References mpq::a, b, mpq::c, and dtVsub().
Referenced by dtNavMesh::getPolyHeight().
dtClosestPtPointTriangle()
void dtClosestPtPointTriangle (float * closest, const float * p, const float * a, const float * b, const float * c)
Derives the closest point on a triangle from the specified reference point.
Parameters
[out] closest The closest point on the triangle.
[in] p The reference point from which to test. [(x, y, z)]
[in] a Vertex A of triangle ABC. [(x, y, z)]
[in] b Vertex B of triangle ABC. [(x, y, z)]
[in] c Vertex C of triangle ABC. [(x, y, z)]
Definition at line 24 of file DetourCommon.cpp.
 {
     // Check if P in vertex region outside A
     float ab[3], ac[3], ap[3];
     dtVsub(ab, b, a);
     dtVsub(ac, c, a);
     dtVsub(ap, p, a);
     float d1 = dtVdot(ab, ap);
     float d2 = dtVdot(ac, ap);
     if (d1 <= 0.0f && d2 <= 0.0f)
     {
         // barycentric coordinates (1,0,0)
         dtVcopy(closest, a);
         return;
     }
     // Check if P in vertex region outside B
     float bp[3];
     dtVsub(bp, p, b);
     float d3 = dtVdot(ab, bp);
     float d4 = dtVdot(ac, bp);
     if (d3 >= 0.0f && d4 <= d3)
     {
         // barycentric coordinates (0,1,0)
         dtVcopy(closest, b);
         return;
     }
     // Check if P in edge region of AB, if so return projection of P onto AB
     float vc = d1*d4 - d3*d2;
     if (vc <= 0.0f && d1 >= 0.0f && d3 <= 0.0f)
     {
         // barycentric coordinates (1-v,v,0)
         float v = d1 / (d1 - d3);
         closest[0] = a[0] + v * ab[0];
         closest[1] = a[1] + v * ab[1];
         closest[2] = a[2] + v * ab[2];
         return;
     }
     // Check if P in vertex region outside C
     float cp[3];
     dtVsub(cp, p, c);
     float d5 = dtVdot(ab, cp);
     float d6 = dtVdot(ac, cp);
     if (d6 >= 0.0f && d5 <= d6)
     {
         // barycentric coordinates (0,0,1)
         dtVcopy(closest, c);
         return;
     }
     // Check if P in edge region of AC, if so return projection of P onto AC
     float vb = d5*d2 - d1*d6;
     if (vb <= 0.0f && d2 >= 0.0f && d6 <= 0.0f)
     {
         // barycentric coordinates (1-w,0,w)
         float w = d2 / (d2 - d6);
         closest[0] = a[0] + w * ac[0];
         closest[1] = a[1] + w * ac[1];
         closest[2] = a[2] + w * ac[2];
         return;
     }
     // Check if P in edge region of BC, if so return projection of P onto BC
     float va = d3*d6 - d5*d4;
     if (va <= 0.0f && (d4 - d3) >= 0.0f && (d5 - d6) >= 0.0f)
     {
         // barycentric coordinates (0,1-w,w)
         float w = (d4 - d3) / ((d4 - d3) + (d5 - d6));
         closest[0] = b[0] + w * (c[0] - b[0]);
         closest[1] = b[1] + w * (c[1] - b[1]);
         closest[2] = b[2] + w * (c[2] - b[2]);
         return;
     }
     // P inside face region. Compute Q through its barycentric coordinates (u,v,w)
     float denom = 1.0f / (va + vb + vc);
     float v = vb * denom;
     float w = vc * denom;
     closest[0] = a[0] + ab[0] * v + ac[0] * w;
     closest[1] = a[1] + ab[1] * v + ac[1] * w;
     closest[2] = a[2] + ab[2] * v + ac[2] * w;
 }
References mpq::a, b, mpq::c, d1, dtVcopy(), dtVdot(), and dtVsub().
dtDistancePtPolyEdgesSqr()
bool dtDistancePtPolyEdgesSqr (const float * pt, const float * verts, const int nverts, float * ed, float * et)
Definition at line 254 of file DetourCommon.cpp.
 {
     // TODO: Replace pnpoly with triArea2D tests?
     int i, j;
     bool c = false;
     for (i = 0, j = nverts-1; i < nverts; j = i++)
     {
         const float* vi = &verts[i*3];
         const float* vj = &verts[j*3];
         if (((vi[2] > pt[2]) != (vj[2] > pt[2])) &&
             (pt[0] < (vj[0]-vi[0]) * (pt[2]-vi[2]) / (vj[2]-vi[2]) + vi[0]) )
             c = !c;
         ed[j] = dtDistancePtSegSqr2D(pt, vj, vi, et[j]);
     }
     return c;
 }
References mpq::c, and dtDistancePtSegSqr2D().
Referenced by dtNavMeshQuery::closestPointOnPolyBoundary().
dtDistancePtSegSqr2D()
float dtDistancePtSegSqr2D (const float * pt, const float * p, const float * q, float & t)
Definition at line 170 of file DetourCommon.cpp.
 {
     float pqx = q[0] - p[0];
     float pqz = q[2] - p[2];
     float dx = pt[0] - p[0];
     float dz = pt[2] - p[2];
     float d = pqx*pqx + pqz*pqz;
     t = pqx*dx + pqz*dz;
     if (d > 0) t /= d;
     if (t < 0) t = 0;
     else if (t > 1) t = 1;
     dx = p[0] + t*pqx - pt[0];
     dz = p[2] + t*pqz - pt[2];
     return dx*dx + dz*dz;
 }
References mpq::d.
Referenced by anonymous_namespace{DetourNavMesh.cpp}::closestPointOnDetailEdges(), dtNavMesh::closestPointOnPoly(), dtDistancePtPolyEdgesSqr(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::findStraightPath(), dtNavMeshQuery::getPolyHeight(), and dtNavMeshQuery::moveAlongSurface().
dtGetThenAdvanceBufferPointer() [1/2]
template<typename TypeToRetrieveAs > TypeToRetrieveAs* dtGetThenAdvanceBufferPointer (const unsigned char *& buffer, const size_t distanceToAdvance)
Definition at line 509 of file DetourCommon.h.
 {
     TypeToRetrieveAs* returnPointer = reinterpret_cast<TypeToRetrieveAs*>(buffer);
     buffer += distanceToAdvance;
     return returnPointer;
 }
References buffer.
dtGetThenAdvanceBufferPointer() [2/2]
template<typename TypeToRetrieveAs > TypeToRetrieveAs* dtGetThenAdvanceBufferPointer (unsigned char *& buffer, const size_t distanceToAdvance)
Definition at line 517 of file DetourCommon.h.
 {
     TypeToRetrieveAs* returnPointer = reinterpret_cast<TypeToRetrieveAs*>(buffer);
     buffer += distanceToAdvance;
     return returnPointer;
 }
References buffer.
dtIgnoreUnused()
template<class T > void dtIgnoreUnused (const T &)
Used to ignore a function parameter. VS complains about unused parameters and this silences the warning.
Parameters
[in] _ Unused parameter
Definition at line 41 of file DetourCommon.h.
 { }
Referenced by dtFindNearestPolyQuery::process(), and dtCollectPolysQuery::process().
dtIlog2()
unsigned int dtIlog2 (unsigned int v) inline
Definition at line 452 of file DetourCommon.h.
 {
     unsigned int r;
     unsigned int shift;
     r = (v > 0xffff) << 4; v >>= r;
     shift = (v > 0xff) << 3; v >>= shift; r |= shift;
     shift = (v > 0xf) << 2; v >>= shift; r |= shift;
     shift = (v > 0x3) << 1; v >>= shift; r |= shift;
     r |= (v >> 1);
     return r;
 }
Referenced by dtNavMesh::init().
dtIntersectSegmentPoly2D()
bool dtIntersectSegmentPoly2D (const float * p0, const float * p1, const float * verts, int nverts, float & tmin, float & tmax, int & segMin, int & segMax)
Definition at line 110 of file DetourCommon.cpp.
 {
     static const float EPS = 0.00000001f;
     tmin = 0;
     tmax = 1;
     segMin = -1;
     segMax = -1;
     float dir[3];
     dtVsub(dir, p1, p0);
     for (int i = 0, j = nverts-1; i < nverts; j=i++)
     {
         float edge[3], diff[3];
         dtVsub(edge, &verts[i*3], &verts[j*3]);
         dtVsub(diff, p0, &verts[j*3]);
         const float n = dtVperp2D(edge, diff);
         const float d = dtVperp2D(dir, edge);
         if (fabsf(d) < EPS)
         {
             // S is nearly parallel to this edge
             if (n < 0)
                 return false;
             else
                 continue;
         }
         const float t = n / d;
         if (d < 0)
         {
             // segment S is entering across this edge
             if (t > tmin)
             {
                 tmin = t;
                 segMin = j;
                 // S enters after leaving polygon
                 if (tmin > tmax)
                     return false;
             }
         }
         else
         {
             // segment S is leaving across this edge
             if (t < tmax)
             {
                 tmax = t;
                 segMax = j;
                 // S leaves before entering polygon
                 if (tmax < tmin)
                     return false;
             }
         }
     }
     return true;
 }
References mpq::d, diff(), dtVperp2D(), and dtVsub().
Referenced by dtNavMeshQuery::findPolysAroundShape(), and dtNavMeshQuery::raycast().
dtIntersectSegSeg2D()
bool dtIntersectSegSeg2D (const float * ap, const float * aq, const float * bp, const float * bq, float & s, float & t)
Definition at line 373 of file DetourCommon.cpp.
 {
     float u[3], v[3], w[3];
     dtVsub(u,aq,ap);
     dtVsub(v,bq,bp);
     dtVsub(w,ap,bp);
     float d = vperpXZ(u,v);
     if (fabsf(d) < 1e-6f) return false;
     s = vperpXZ(v,w) / d;
     t = vperpXZ(u,w) / d;
     return true;
 }
References mpq::d, dtVsub(), and vperpXZ().
Referenced by dtNavMeshQuery::appendPortals().
dtMax()
template<class T > T dtMax (T a, T b) inline
Returns the maximum of two values.
Parameters
[in] a Value A
[in] b Value B
Returns
The maximum of the two values.
Definition at line 58 of file DetourCommon.h.
 { return a > b ? a : b; }
References mpq::a, and b.
Referenced by dtCreateNavMeshData(), dtRandomPointInConvexPoly(), dtVmax(), dtNavMesh::findConnectingPolys(), overlapSlabs(), and projectPoly().
dtMin()
template<class T > T dtMin (T a, T b) inline
Returns the minimum of two values.
Parameters
[in] a Value A
[in] b Value B
Returns
The minimum of the two values.
Definition at line 52 of file DetourCommon.h.
 { return a < b ? a : b; }
References mpq::a, and b.
Referenced by dtCreateNavMeshData(), dtVmin(), dtNavMesh::findConnectingPolys(), dtNavMeshQuery::getPathToNode(), dtNavMesh::init(), overlapSlabs(), and projectPoly().
dtNextPow2()
unsigned int dtNextPow2 (unsigned int v) inline
Definition at line 440 of file DetourCommon.h.
 {
     v--;
     v |= v >> 1;
     v |= v >> 2;
     v |= v >> 4;
     v |= v >> 8;
     v |= v >> 16;
     v++;
     return v;
 }
Referenced by dtNodePool::dtNodePool(), dtNavMeshQuery::init(), and dtNavMesh::init().
dtOppositeTile()
int dtOppositeTile (int side) inline
Definition at line 466 of file DetourCommon.h.
 { return (side+4) & 0x7; }
Referenced by dtNavMesh::addTile(), dtNavMesh::connectExtLinks(), and dtNavMesh::connectExtOffMeshLinks().
dtOverlapBounds()
bool dtOverlapBounds (const float * amin, const float * amax, const float * bmin, const float * bmax) inline
Determines if two axis-aligned bounding boxes overlap.
Parameters
[in] amin Minimum bounds of box A. [(x, y, z)]
[in] amax Maximum bounds of box A. [(x, y, z)]
[in] bmin Minimum bounds of box B. [(x, y, z)]
[in] bmax Maximum bounds of box B. [(x, y, z)]
Returns
True if the two AABB's overlap.
See also
dtOverlapQuantBounds
Definition at line 372 of file DetourCommon.h.
 {
     bool overlap = true;
     overlap = (amin[0] > bmax[0] || amax[0] < bmin[0]) ? false : overlap;
     overlap = (amin[1] > bmax[1] || amax[1] < bmin[1]) ? false : overlap;
     overlap = (amin[2] > bmax[2] || amax[2] < bmin[2]) ? false : overlap;
     return overlap;
 }
Referenced by dtNavMeshQuery::queryPolygonsInTile(), and dtNavMesh::queryPolygonsInTile().
dtOverlapPolyPoly2D()
bool dtOverlapPolyPoly2D (const float * polya, const int npolya, const float * polyb, const int npolyb)
Determines if the two convex polygons overlap on the xz-plane.
Parameters
[in] polya Polygon A vertices. [(x, y, z) * npolya]
[in] npolya The number of vertices in polygon A.
[in] polyb Polygon B vertices. [(x, y, z) * npolyb]
[in] npolyb The number of vertices in polygon B.
Returns
True if the two polygons overlap.
All vertices are projected onto the xz-plane, so the y-values are ignored.
Definition at line 294 of file DetourCommon.cpp.
 {
     const float eps = 1e-4f;
     for (int i = 0, j = npolya-1; i < npolya; j=i++)
     {
         const float* va = &polya[j*3];
         const float* vb = &polya[i*3];
         const float n[3] = { vb[2]-va[2], 0, -(vb[0]-va[0]) };
         float amin,amax,bmin,bmax;
         projectPoly(n, polya, npolya, amin,amax);
         projectPoly(n, polyb, npolyb, bmin,bmax);
         if (!overlapRange(amin,amax, bmin,bmax, eps))
         {
             // Found separating axis
             return false;
         }
     }
     for (int i = 0, j = npolyb-1; i < npolyb; j=i++)
     {
         const float* va = &polyb[j*3];
         const float* vb = &polyb[i*3];
         const float n[3] = { vb[2]-va[2], 0, -(vb[0]-va[0]) };
         float amin,amax,bmin,bmax;
         projectPoly(n, polya, npolya, amin,amax);
         projectPoly(n, polyb, npolyb, bmin,bmax);
         if (!overlapRange(amin,amax, bmin,bmax, eps))
         {
             // Found separating axis
             return false;
         }
     }
     return true;
 }
References G3D::eps(), overlapRange(), and projectPoly().
Referenced by dtNavMeshQuery::findLocalNeighbourhood().
dtOverlapQuantBounds()
bool dtOverlapQuantBounds (const unsigned short amin[3], const unsigned short amax[3], const unsigned short bmin[3], const unsigned short bmax[3]) inline
Determines if two axis-aligned bounding boxes overlap.
Parameters
[in] amin Minimum bounds of box A. [(x, y, z)]
[in] amax Maximum bounds of box A. [(x, y, z)]
[in] bmin Minimum bounds of box B. [(x, y, z)]
[in] bmax Maximum bounds of box B. [(x, y, z)]
Returns
True if the two AABB's overlap.
See also
dtOverlapBounds
Definition at line 355 of file DetourCommon.h.
 {
     bool overlap = true;
     overlap = (amin[0] > bmax[0] || amax[0] < bmin[0]) ? false : overlap;
     overlap = (amin[1] > bmax[1] || amax[1] < bmin[1]) ? false : overlap;
     overlap = (amin[2] > bmax[2] || amax[2] < bmin[2]) ? false : overlap;
     return overlap;
 }
Referenced by dtNavMeshQuery::queryPolygonsInTile(), and dtNavMesh::queryPolygonsInTile().
dtPointInPolygon()
bool dtPointInPolygon (const float * pt, const float * verts, const int nverts)
Determines if the specified point is inside the convex polygon on the xz-plane.
Parameters
[in] pt The point to check. [(x, y, z)]
[in] verts The polygon vertices. [(x, y, z) * nverts]
[in] nverts The number of vertices. [Limit: >= 3]
Returns
True if the point is inside the polygon.
All points are projected onto the xz-plane, so the y-values are ignored.
Definition at line 238 of file DetourCommon.cpp.
 {
     // TODO: Replace pnpoly with triArea2D tests?
     int i, j;
     bool c = false;
     for (i = 0, j = nverts-1; i < nverts; j = i++)
     {
         const float* vi = &verts[i*3];
         const float* vj = &verts[j*3];
         if (((vi[2] > pt[2]) != (vj[2] > pt[2])) &&
             (pt[0] < (vj[0]-vi[0]) * (pt[2]-vi[2]) / (vj[2]-vi[2]) + vi[0]) )
             c = !c;
     }
     return c;
 }
References mpq::c.
Referenced by dtNavMesh::getPolyHeight(), and dtNavMeshQuery::moveAlongSurface().
dtRandomPointInConvexPoly()
void dtRandomPointInConvexPoly (const float * pts, const int npts, float * areas, const float s, const float t, float * out)
Definition at line 332 of file DetourCommon.cpp.
 {
     // Calc triangle araes
     float areasum = 0.0f;
     for (int i = 2; i < npts; i++) {
         areas[i] = dtTriArea2D(&pts[0], &pts[(i-1)*3], &pts[i*3]);
         areasum += dtMax(0.001f, areas[i]);
     }
     // Find sub triangle weighted by area.
     const float thr = s*areasum;
     float acc = 0.0f;
     float u = 1.0f;
     int tri = npts - 1;
     for (int i = 2; i < npts; i++) {
         const float dacc = areas[i];
         if (thr >= acc && thr < (acc+dacc))
         {
             u = (thr - acc) / dacc;
             tri = i;
             break;
         }
         acc += dacc;
     }
     float v = dtMathSqrtf(t);
     const float a = 1 - v;
     const float b = (1 - u) * v;
     const float c = u * v;
     const float* pa = &pts[0];
     const float* pb = &pts[(tri-1)*3];
     const float* pc = &pts[tri*3];
     out[0] = a*pa[0] + b*pb[0] + c*pc[0];
     out[1] = a*pa[1] + b*pb[1] + c*pc[1];
     out[2] = a*pa[2] + b*pb[2] + c*pc[2];
 }
References mpq::a, b, mpq::c, dtMathSqrtf(), dtMax(), and dtTriArea2D().
Referenced by dtNavMeshQuery::findRandomPoint(), and dtNavMeshQuery::findRandomPointAroundCircle().
dtSqr()
template<class T > T dtSqr (T a) inline
Returns the square of the value.
Parameters
[in] a The value.
Returns
The square of the value.
Definition at line 68 of file DetourCommon.h.
 { return a*a; }
References mpq::a.
Referenced by dtNavMesh::baseOffMeshLinks(), dtNavMesh::connectExtOffMeshLinks(), dtVequal(), dtVnormalize(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::findStraightPath(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), overlapSlabs(), and dtNavMeshQuery::raycast().
dtSwap()
template<class T > void dtSwap (T & a, T & b) inline
Swaps the values of the two parameters.
Parameters
[in,out] a Value A
[in,out] b Value B
Definition at line 46 of file DetourCommon.h.
 { T t = a; a = b; b = t; }
References mpq::a, and b.
Referenced by dtNavMesh::connectExtLinks(), and dtNavMeshQuery::raycast().
dtSwapByte()
void dtSwapByte (unsigned char * a, unsigned char * b) inline
Definition at line 468 of file DetourCommon.h.
 {
     unsigned char tmp = *a;
     *a = *b;
     *b = tmp;
 }
References mpq::a, and b.
Referenced by dtSwapEndian().
dtSwapEndian() [1/5]
void dtSwapEndian (float * v) inline
Definition at line 499 of file DetourCommon.h.
 {
     unsigned char* x = (unsigned char*)v;
     dtSwapByte(x+0, x+3); dtSwapByte(x+1, x+2);
 }
References dtSwapByte(), and G3D::x.
dtSwapEndian() [2/5]
void dtSwapEndian (int * v) inline
Definition at line 493 of file DetourCommon.h.
 {
     unsigned char* x = (unsigned char*)v;
     dtSwapByte(x+0, x+3); dtSwapByte(x+1, x+2);
 }
References dtSwapByte(), and G3D::x.
dtSwapEndian() [3/5]
void dtSwapEndian (short * v) inline
Definition at line 481 of file DetourCommon.h.
 {
     unsigned char* x = (unsigned char*)v;
     dtSwapByte(x+0, x+1);
 }
References dtSwapByte(), and G3D::x.
dtSwapEndian() [4/5]
void dtSwapEndian (unsigned int * v) inline
Definition at line 487 of file DetourCommon.h.
 {
     unsigned char* x = (unsigned char*)v;
     dtSwapByte(x+0, x+3); dtSwapByte(x+1, x+2);
 }
References dtSwapByte(), and G3D::x.
dtSwapEndian() [5/5]
void dtSwapEndian (unsigned short * v) inline
Definition at line 475 of file DetourCommon.h.
 {
     unsigned char* x = (unsigned char*)v;
     dtSwapByte(x+0, x+1);
 }
References dtSwapByte(), and G3D::x.
Referenced by dtNavMeshDataSwapEndian(), and dtNavMeshHeaderSwapEndian().
dtTriArea2D()
float dtTriArea2D (const float * a, const float * b, const float * c) inline
Derives the signed xz-plane area of the triangle ABC, or the relationship of line AB to point C.
Parameters
[in] a Vertex A. [(x, y, z)]
[in] b Vertex B. [(x, y, z)]
[in] c Vertex C. [(x, y, z)]
Returns
The signed xz-plane area of the triangle.
The vertices are projected onto the xz-plane, so the y-values are ignored.
This is a low cost function than can be used for various purposes. Its main purpose is for point/line relationship testing.
In all cases: A value of zero indicates that all vertices are collinear or represent the same point. (On the xz-plane.)
When used for point/line relationship tests, AB usually represents a line against which the C point is to be tested. In this case:
A positive value indicates that point C is to the left of line AB, looking from A toward B.
A negative value indicates that point C is to the right of lineAB, looking from A toward B.
When used for evaluating a triangle:
The absolute value of the return value is two times the area of the triangle when it is projected onto the xz-plane.
A positive return value indicates:
The vertices are wrapped in the normal Detour wrap direction.
The triangle's 3D face normal is in the general up direction.
A negative return value indicates:
The vertices are reverse wrapped. (Wrapped opposite the normal Detour wrap direction.)
The triangle's 3D face normal is in the general down direction.
Definition at line 339 of file DetourCommon.h.
 {
     const float abx = b[0] - a[0];
     const float abz = b[2] - a[2];
     const float acx = c[0] - a[0];
     const float acz = c[2] - a[2];
     return acx*abz - abx*acz;
 }
References mpq::a, b, and mpq::c.
Referenced by dtRandomPointInConvexPoly(), dtNavMeshQuery::findRandomPoint(), dtNavMeshQuery::findRandomPointAroundCircle(), and dtNavMeshQuery::findStraightPath().
dtVadd()
void dtVadd (float * dest, const float * v1, const float * v2) inline
Performs a vector addition. (v1 + v2)
Parameters
[out] dest The result vector. [(x, y, z)]
[in] v1 The base vector. [(x, y, z)]
[in] v2 The vector to add to v1. [(x, y, z)]
Definition at line 129 of file DetourCommon.h.
 {
     dest[0] = v1[0]+v2[0];
     dest[1] = v1[1]+v2[1];
     dest[2] = v1[2]+v2[2];
 }
Referenced by dtNavMesh::findNearestPolyInTile(), dtNavMeshQuery::findPolysAroundShape(), and dtNavMeshQuery::queryPolygons().
dtVcopy()
void dtVcopy (float * dest, const float * a) inline
Performs a vector copy.
Parameters
[out] dest The result. [(x, y, z)]
[in] a The vector to copy. [(x, y, z)]
Definition at line 191 of file DetourCommon.h.
 {
     dest[0] = a[0];
     dest[1] = a[1];
     dest[2] = a[2];
 }
References mpq::a.
Referenced by dtNavMeshQuery::appendVertex(), dtNavMesh::baseOffMeshLinks(), ContinentBuilder::Build(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), dtNavMesh::closestPointOnPoly(), dtNavMeshQuery::closestPointOnPolyBoundary(), dtNavMesh::connectExtOffMeshLinks(), createBVTree(), dtClosestPtPointTriangle(), dtCreateNavMeshData(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findNearestPoly(), dtNavMesh::findNearestPolyInTile(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPoint(), dtNavMeshQuery::findRandomPointAroundCircle(), PathGenerator::FindSmoothPath(), dtNavMeshQuery::findStraightPath(), dtNavMesh::getOffMeshConnectionPolyEndPoints(), dtNavMesh::getPolyHeight(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::getPortalPoints(), PathGenerator::GetSteerTarget(), dtNavMesh::init(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), dtFindNearestPolyQuery::process(), dtNavMeshQuery::queryPolygonsInTile(), dtNavMesh::queryPolygonsInTile(), and dtNavMeshQuery::raycast().
dtVcross()
void dtVcross (float * dest, const float * v1, const float * v2) inline
Derives the cross product of two vectors. (v1 x v2)
Parameters
[out] dest The cross product. [(x, y, z)]
[in] v1 A Vector [(x, y, z)]
[in] v2 A vector [(x, y, z)]
Definition at line 85 of file DetourCommon.h.
 {
     dest[0] = v1[1]*v2[2] - v1[2]*v2[1];
     dest[1] = v1[2]*v2[0] - v1[0]*v2[2];
     dest[2] = v1[0]*v2[1] - v1[1]*v2[0];
 }
dtVdist()
float dtVdist (const float * v1, const float * v2) inline
Returns the distance between two points.
Parameters
[in] v1 A point. [(x, y, z)]
[in] v2 A point. [(x, y, z)]
Returns
The distance between the two points.
Definition at line 218 of file DetourCommon.h.
 {
     const float dx = v2[0] - v1[0];
     const float dy = v2[1] - v1[1];
     const float dz = v2[2] - v1[2];
     return dtMathSqrtf(dx*dx + dy*dy + dz*dz);
 }
References dtMathSqrtf().
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findRandomPointAroundCircle(), dtQueryFilter::getCost(), dtQueryFilterExt::getCost(), PathGenerator::GetPolyByLocation(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), and dtNavMeshQuery::updateSlicedFindPath().
dtVdist2D()
float dtVdist2D (const float * v1, const float * v2) inline
Derives the distance between the specified points on the xz-plane.
Parameters
[in] v1 A point. [(x, y, z)]
[in] v2 A point. [(x, y, z)]
Returns
The distance between the point on the xz-plane.
The vectors are projected onto the xz-plane, so the y-values are ignored.
Definition at line 244 of file DetourCommon.h.
 {
     const float dx = v2[0] - v1[0];
     const float dz = v2[2] - v1[2];
     return dtMathSqrtf(dx*dx + dz*dz);
 }
References dtMathSqrtf().
dtVdist2DSqr()
float dtVdist2DSqr (const float * v1, const float * v2) inline
Derives the square of the distance between the specified points on the xz-plane.
Parameters
[in] v1 A point. [(x, y, z)]
[in] v2 A point. [(x, y, z)]
Returns
The square of the distance between the point on the xz-plane.
Definition at line 255 of file DetourCommon.h.
 {
     const float dx = v2[0] - v1[0];
     const float dz = v2[2] - v1[2];
     return dx*dx + dz*dz;
 }
dtVdistSqr()
float dtVdistSqr (const float * v1, const float * v2) inline
Returns the square of the distance between two points.
Parameters
[in] v1 A point. [(x, y, z)]
[in] v2 A point. [(x, y, z)]
Returns
The square of the distance between the two points.
Definition at line 230 of file DetourCommon.h.
 {
     const float dx = v2[0] - v1[0];
     const float dy = v2[1] - v1[1];
     const float dz = v2[2] - v1[2];
     return dx*dx + dy*dy + dz*dz;
 }
Referenced by dtVequal(), PathGenerator::GetPathPolyByPosition(), and dtNavMeshQuery::updateSlicedFindPath().
dtVdot()
float dtVdot (const float * v1, const float * v2) inline
Derives the dot product of two vectors. (v1 . v2)
Parameters
[in] v1 A Vector [(x, y, z)]
[in] v2 A vector [(x, y, z)]
Returns
The dot product.
Definition at line 96 of file DetourCommon.h.
 {
     return v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2];
 }
Referenced by dtClosestPtPointTriangle(), and PathGenerator::FindSmoothPath().
dtVdot2D()
float dtVdot2D (const float * u, const float * v) inline
Derives the dot product of two vectors on the xz-plane. (u . v)
Parameters
[in] u A vector [(x, y, z)]
[in] v A vector [(x, y, z)]
Returns
The dot product on the xz-plane.
The vectors are projected onto the xz-plane, so the y-values are ignored.
Definition at line 314 of file DetourCommon.h.
 {
     return u[0]*v[0] + u[2]*v[2];
 }
Referenced by projectPoly().
dtVequal()
bool dtVequal (const float * p0, const float * p1) inline
Performs a 'sloppy' colocation check of the specified points.
Parameters
[in] p0 A point. [(x, y, z)]
[in] p1 A point. [(x, y, z)]
Returns
True if the points are considered to be at the same location.
Basically, this function will return true if the specified points are close enough to eachother to be considered colocated.
Definition at line 279 of file DetourCommon.h.
 {
     static const float thr = dtSqr(1.0f/16384.0f);
     const float d = dtVdistSqr(p0, p1);
     return d < thr;
 }
References mpq::d, dtSqr(), and dtVdistSqr().
Referenced by dtNavMeshQuery::appendVertex(), and dtNavMeshQuery::findStraightPath().
dtVisfinite()
bool dtVisfinite (const float * v) inline
Checks that the specified vector's components are all finite.
Parameters
[in] v A point. [(x, y, z)]
Returns
True if all of the point's components are finite, i.e. not NaN or any of the infinities.
Definition at line 290 of file DetourCommon.h.
 {
     bool result =
         dtMathIsfinite(v[0]) &&
         dtMathIsfinite(v[1]) &&
         dtMathIsfinite(v[2]);
     return result;
 }
References dtMathIsfinite().
Referenced by dtNavMeshQuery::closestPointOnPoly(), dtNavMeshQuery::closestPointOnPolyBoundary(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::findStraightPath(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), dtNavMeshQuery::queryPolygons(), and dtNavMeshQuery::raycast().
dtVisfinite2D()
bool dtVisfinite2D (const float * v) inline
Checks that the specified vector's 2D components are finite.
Parameters
[in] v A point. [(x, y, z)]
Definition at line 302 of file DetourCommon.h.
 {
     bool result = dtMathIsfinite(v[0]) && dtMathIsfinite(v[2]);
     return result;
 }
References dtMathIsfinite().
Referenced by dtNavMeshQuery::getPolyHeight().
dtVlen()
float dtVlen (const float * v) inline
Derives the scalar length of the vector.
Parameters
[in] v The vector. [(x, y, z)]
Returns
The scalar length of the vector.
Definition at line 201 of file DetourCommon.h.
 {
     return dtMathSqrtf(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
 }
References dtMathSqrtf().
dtVlenSqr()
float dtVlenSqr (const float * v) inline
Derives the square of the scalar length of the vector. (len * len)
Parameters
[in] v The vector. [(x, y, z)]
Returns
The square of the scalar length of the vector.
Definition at line 209 of file DetourCommon.h.
 {
     return v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
 }
Referenced by dtNavMesh::findNearestPolyInTile(), and dtFindNearestPolyQuery::process().
dtVlerp()
void dtVlerp (float * dest, const float * v1, const float * v2, const float t) inline
Performs a linear interpolation between two vectors. (v1 toward v2)
Parameters
[out] dest The result vector. [(x, y, x)]
[in] v1 The starting vector.
[in] v2 The destination vector.
[in] t The interpolation factor. [Limits: 0 <= value <= 1.0]
Definition at line 118 of file DetourCommon.h.
 {
     dest[0] = v1[0]+(v2[0]-v1[0])*t;
     dest[1] = v1[1]+(v2[1]-v1[1])*t;
     dest[2] = v1[2]+(v2[2]-v1[2])*t;
 }
Referenced by dtNavMeshQuery::appendPortals(), PathGenerator::BuildPolyPath(), anonymous_namespace{DetourNavMesh.cpp}::closestPointOnDetailEdges(), dtNavMesh::closestPointOnPoly(), dtNavMeshQuery::closestPointOnPolyBoundary(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::getPortalPoints(), and dtNavMeshQuery::moveAlongSurface().
dtVmad()
void dtVmad (float * dest, const float * v1, const float * v2, const float s) inline
Performs a scaled vector addition. (v1 + (v2 * s))
Parameters
[out] dest The result vector. [(x, y, z)]
[in] v1 The base vector. [(x, y, z)]
[in] v2 The vector to scale and add to v1. [(x, y, z)]
[in] s The amount to scale v2 by before adding to v1.
Definition at line 106 of file DetourCommon.h.
 {
     dest[0] = v1[0]+v2[0]*s;
     dest[1] = v1[1]+v2[1]*s;
     dest[2] = v1[2]+v2[2]*s;
 }
Referenced by PathGenerator::FindSmoothPath(), and dtNavMeshQuery::raycast().
dtVmax()
void dtVmax (float * mx, const float * v) inline
Selects the maximum value of each element from the specified vectors.
Parameters
[in,out] mx A vector. (Will be updated with the result.) [(x, y, z)]
[in] v A vector. [(x, y, z)]
Definition at line 171 of file DetourCommon.h.
 {
     mx[0] = dtMax(mx[0], v[0]);
     mx[1] = dtMax(mx[1], v[1]);
     mx[2] = dtMax(mx[2], v[2]);
 }
References dtMax().
Referenced by createBVTree(), dtNavMeshQuery::queryPolygonsInTile(), and dtNavMesh::queryPolygonsInTile().
dtVmin()
void dtVmin (float * mn, const float * v) inline
Selects the minimum value of each element from the specified vectors.
Parameters
[in,out] mn A vector. (Will be updated with the result.) [(x, y, z)]
[in] v A vector. [(x, y, z)]
Definition at line 161 of file DetourCommon.h.
 {
     mn[0] = dtMin(mn[0], v[0]);
     mn[1] = dtMin(mn[1], v[1]);
     mn[2] = dtMin(mn[2], v[2]);
 }
References dtMin().
Referenced by createBVTree(), dtNavMeshQuery::queryPolygonsInTile(), and dtNavMesh::queryPolygonsInTile().
dtVnormalize()
void dtVnormalize (float * v) inline
Normalizes the vector.
Parameters
[in,out] v The vector to normalize. [(x, y, z)]
Definition at line 264 of file DetourCommon.h.
 {
     float d = 1.0f / dtMathSqrtf(dtSqr(v[0]) + dtSqr(v[1]) + dtSqr(v[2]));
     v[0] *= d;
     v[1] *= d;
     v[2] *= d;
 }
References mpq::d, dtMathSqrtf(), and dtSqr().
Referenced by dtNavMeshQuery::findDistanceToWall(), and dtNavMeshQuery::raycast().
dtVperp2D()
float dtVperp2D (const float * u, const float * v) inline
Derives the xz-plane 2D perp product of the two vectors. (uz*vx - ux*vz)
Parameters
[in] u The LHV vector [(x, y, z)]
[in] v The RHV vector [(x, y, z)]
Returns
The dot product on the xz-plane.
The vectors are projected onto the xz-plane, so the y-values are ignored.
Definition at line 325 of file DetourCommon.h.
 {
     return u[2]*v[0] - u[0]*v[2];
 }
Referenced by dtIntersectSegmentPoly2D().
dtVscale()
void dtVscale (float * dest, const float * v, const float t) inline
Scales the vector by the specified value. (v * t)
Parameters
[out] dest The result vector. [(x, y, z)]
[in] v The vector to scale. [(x, y, z)]
[in] t The scaling factor.
Definition at line 151 of file DetourCommon.h.
 {
     dest[0] = v[0]*t;
     dest[1] = v[1]*t;
     dest[2] = v[2]*t;
 }
Referenced by dtNavMeshQuery::findPolysAroundShape().
dtVset()
void dtVset (float * dest, const float x, const float y, const float z) inline
Sets the vector elements to the specified values.
Parameters
[out] dest The result vector. [(x, y, z)]
[in] x The x-value of the vector.
[in] y The y-value of the vector.
[in] z The z-value of the vector.
Definition at line 183 of file DetourCommon.h.
 {
     dest[0] = x; dest[1] = y; dest[2] = z;
 }
References G3D::x, G3D::y, and G3D::z.
Referenced by dtNavMeshQuery::raycast().
dtVsub()
void dtVsub (float * dest, const float * v1, const float * v2) inline
Performs a vector subtraction. (v1 - v2)
Parameters
[out] dest The result vector. [(x, y, z)]
[in] v1 The base vector. [(x, y, z)]
[in] v2 The vector to subtract from v1. [(x, y, z)]
Definition at line 140 of file DetourCommon.h.
 {
     dest[0] = v1[0]-v2[0];
     dest[1] = v1[1]-v2[1];
     dest[2] = v1[2]-v2[2];
 }
Referenced by dtClosestHeightPointTriangle(), dtClosestPtPointTriangle(), dtIntersectSegmentPoly2D(), dtIntersectSegSeg2D(), dtNavMeshQuery::findDistanceToWall(), dtNavMesh::findNearestPolyInTile(), PathGenerator::FindSmoothPath(), dtFindNearestPolyQuery::process(), dtNavMeshQuery::queryPolygons(), and dtNavMeshQuery::raycast().