Azerotcore-wotlk: deps/zlib/gzclose.c File Reference
gzclose.c File Reference
#include "gzguts.h"
Functions
int ZEXPORT gzclose (gzFile file)
Function Documentation
gzclose()
int ZEXPORT gzclose (gzFile file)
Definition at line 11 of file gzclose.c.
 {
 #ifndef NO_GZCOMPRESS
     gz_statep state;
     if (file == NULL)
         return Z_STREAM_ERROR;
     state = (gz_statep)file;
     return state->mode == GZ_READ ? gzclose_r(file) : gzclose_w(file);
 #else
     return gzclose_r(file);
 #endif
 }
References mpq::file, GZ_READ, gzclose_r(), gzclose_w(), NULL, and Z_STREAM_ERROR.
Referenced by gz_compress(), gz_uncompress(), and test_gzio().