Azerotcore-wotlk: deps/mysqllite/include/internal/queues.h File Reference
queues.h File Reference
#include "my_global.h"
Classes
struct st_queue
Macros
#define queue_top(queue) ((queue)->root[1])
#define queue_element(queue, index) ((queue)->root[index+1])
#define queue_end(queue) ((queue)->root[(queue)->elements])
#define queue_replaced(queue) _downheap(queue,1)
#define queue_set_cmp_arg(queue, set_arg) (queue)->first_cmp_arg= set_arg
#define queue_set_max_at_top(queue, set_arg) (queue)->max_at_top= set_arg ? -1 : 1
#define queue_remove_all(queue) { (queue)->elements= 0; }
#define queue_is_full(queue) (queue->elements == queue->max_elements)
#define is_queue_inited(queue) ((queue)->root != 0)
Typedefs
typedef struct st_queue QUEUE
typedef int(* queue_compare) (void *, uchar *, uchar *)
Functions
int init_queue (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void *first_cmp_arg)
int init_queue_ex (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void *first_cmp_arg, uint auto_extent)
int reinit_queue (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void *first_cmp_arg)
int resize_queue (QUEUE *queue, uint max_elements)
void delete_queue (QUEUE *queue)
void queue_insert (QUEUE *queue, uchar *element)
int queue_insert_safe (QUEUE *queue, uchar *element)
uchar * queue_remove (QUEUE *queue, uint idx)
void _downheap (QUEUE *queue, uint idx)
void queue_fix (QUEUE *queue)
Macro Definition Documentation
is_queue_inited
#define is_queue_inited (queue) ((queue)->root != 0)
Definition at line 70 of file queues.h.
queue_element
#define queue_element (queue, index) ((queue)->root[index+1])
Definition at line 44 of file queues.h.
queue_end
#define queue_end (queue) ((queue)->root[(queue)->elements])
Definition at line 45 of file queues.h.
queue_is_full
#define queue_is_full (queue) (queue->elements == queue->max_elements)
Definition at line 67 of file queues.h.
queue_remove_all
#define queue_remove_all (queue) { (queue)->elements= 0; }
Definition at line 66 of file queues.h.
queue_replaced
#define queue_replaced (queue) _downheap(queue,1)
Definition at line 46 of file queues.h.
queue_set_cmp_arg
#define queue_set_cmp_arg (queue, set_arg) (queue)->first_cmp_arg= set_arg
Definition at line 47 of file queues.h.
queue_set_max_at_top
#define queue_set_max_at_top (queue, set_arg) (queue)->max_at_top= set_arg ? -1 : 1
Definition at line 48 of file queues.h.
queue_top
#define queue_top (queue) ((queue)->root[1])
Definition at line 43 of file queues.h.
Typedef Documentation
QUEUE
typedef struct st_queue QUEUE
queue_compare
typedef int(* queue_compare) (void *, uchar *, uchar *)
Definition at line 50 of file queues.h.
Function Documentation
_downheap()
void _downheap (QUEUE * queue, uint idx)
delete_queue()
void delete_queue (QUEUE * queue)
Definition at line 194 of file queues.c.
 {
   DBUG_ENTER("delete_queue");
   my_free(queue->root);
   queue->root= NULL;
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, my_free(), NULL, and st_queue::root.
Referenced by end_thr_alarm().
init_queue()
int init_queue (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void * first_cmp_arg)
Referenced by init_thr_alarm().
init_queue_ex()
int init_queue_ex (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void * first_cmp_arg, uint auto_extent)
queue_fix()
void queue_fix (QUEUE * queue)
Definition at line 361 of file queues.c.
 {
   uint i;
   for (i= queue->elements >> 1; i > 0; i--)
     _downheap(queue, i);
 }
References _downheap(), and st_queue::elements.
queue_insert()
void queue_insert (QUEUE * queue, uchar * element)
Referenced by thr_alarm(), and thr_alarm_kill().
queue_insert_safe()
int queue_insert_safe (QUEUE * queue, uchar * element)
queue_remove()
uchar* queue_remove (QUEUE * queue, uint idx)
Referenced by process_alarm_part2(), thr_alarm_kill(), and thr_end_alarm().
reinit_queue()
int reinit_queue (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, queue_compare compare, void * first_cmp_arg)
resize_queue()
int resize_queue (QUEUE * queue, uint max_elements)
Definition at line 163 of file queues.c.
 {
   uchar **new_root;
   DBUG_ENTER("resize_queue");
   if (queue->max_elements == max_elements)
     DBUG_RETURN(0);
   if ((new_root= (uchar **) my_realloc((void *)queue->root,
                       (max_elements+1)*sizeof(void*),
                       MYF(MY_WME))) == 0)
     DBUG_RETURN(1);
   set_if_smaller(queue->elements, max_elements);
   queue->max_elements= max_elements;
   queue->root= new_root;
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, st_queue::elements, st_queue::max_elements, my_realloc(), MY_WME, MYF, st_queue::root, and set_if_smaller.
Referenced by queue_insert_safe(), reinit_queue(), and resize_thr_alarm().