Azerotcore-wotlk: DoodadHandler Class Reference
DoodadHandler Class Reference
#include <DoodadHandler.h>
Public Member Functions
DoodadHandler (ADT *adt)
~DoodadHandler ()
bool IsSane ()
Public Member Functions inherited from ObjectDataHandler
ObjectDataHandler (ADT *_adt)
void ProcessMapChunk (MapChunk *chunk)
Public Attributes
std::vector< Vector3 > Vertices
std::vector< Triangle< uint32 > > Triangles
Public Attributes inherited from ObjectDataHandler
ADT * Source
Protected Member Functions
void ProcessInternal (MapChunk *chunk)
Private Member Functions
void ReadDoodadDefinitions (Chunk *chunk)
void ReadDoodadPaths (Chunk *id, Chunk *data)
void InsertModelGeometry (const DoodadDefinition &def, Model *model)
Private Attributes
std::set< uint32 > _drawn
std::vector< DoodadDefinition > * _definitions
std::vector< std::string > * _paths
Detailed Description
Definition at line 57 of file DoodadHandler.h.
Constructor & Destructor Documentation
DoodadHandler()
DoodadHandler::DoodadHandler (ADT * adt)
Definition at line 24 of file DoodadHandler.cpp.
                                        :
     ObjectDataHandler(adt), _definitions(nullptr), _paths(nullptr)
 {
     Chunk* mddf = adt->ObjectData->GetChunkByName("MDDF");
     if (mddf)
         ReadDoodadDefinitions(mddf);
     Chunk* mmid = adt->ObjectData->GetChunkByName("MMID");
     Chunk* mmdx = adt->ObjectData->GetChunkByName("MMDX");
     if (mmid && mmdx)
         ReadDoodadPaths(mmid, mmdx);
 }
References ChunkedData::GetChunkByName(), ADT::ObjectData, ReadDoodadDefinitions(), and ReadDoodadPaths().
~DoodadHandler()
DoodadHandler::~DoodadHandler ()
Definition at line 122 of file DoodadHandler.cpp.
 {
     delete _definitions;
     delete _paths;
 }
References _definitions, and _paths.
Member Function Documentation
InsertModelGeometry()
void DoodadHandler::InsertModelGeometry (const DoodadDefinition & def, Model * model) private
Definition at line 111 of file DoodadHandler.cpp.
 {
     uint32 vertOffset = Vertices.size();
     for (std::vector<Vector3>::iterator itr = model->Vertices.begin(); itr != model->Vertices.end(); ++itr)
         Vertices.push_back(Utils::TransformDoodadVertex(def, *itr)); // Vertices have to be converted based on the information from the DoodadDefinition struct
     for (std::vector<Triangle<uint16>>::iterator itr = model->Triangles.begin(); itr != model->Triangles.end(); ++itr)
         Triangles.push_back(Triangle<uint32>(Constants::TRIANGLE_TYPE_DOODAD, itr->V0 + vertOffset, itr->V1 + vertOffset, itr->V2 + vertOffset));
 }
References Utils::TransformDoodadVertex(), Constants::TRIANGLE_TYPE_DOODAD, Triangles, Model::Triangles, Vertices, and Model::Vertices.
Referenced by ProcessInternal().
IsSane()
bool DoodadHandler::IsSane () inline
Definition at line 65 of file DoodadHandler.h.
 { return _definitions && _paths; }
References _definitions, and _paths.
Referenced by ProcessInternal().
ProcessInternal()
void DoodadHandler::ProcessInternal (MapChunk * chunk) protected virtual
Implements ObjectDataHandler.
Definition at line 37 of file DoodadHandler.cpp.
 {
     if (!IsSane())
         return;
     uint32 refCount = mcnk->Header.DoodadRefs;
     FILE* stream = mcnk->Source->GetStream();
     fseek(stream, mcnk->Source->Offset + mcnk->Header.OffsetMCRF, SEEK_SET);
     for (uint32 i = 0; i < refCount; i++)
     {
         int32 index;
         int32 count;
         if ((count = fread(&index, sizeof(int32), 1, stream)) != 1)
             printf("DoodadHandler::ProcessInternal: Failed to read some data expected 1, read %d\n", count);
         if (index < 0 || uint32(index) >= _definitions->size())
             continue;
         DoodadDefinition doodad = (*_definitions)[index];
         if (_drawn.find(doodad.UniqueId) != _drawn.end())
             continue;
         _drawn.insert(doodad.UniqueId);
         if (doodad.MmidIndex >= _paths->size())
             continue;
         std::string path = (*_paths)[doodad.MmidIndex];
         Model* model = Cache->ModelCache.Get(path);
         if (!model)
         {
             model = new Model(path);
             Cache->ModelCache.Insert(path, model);
         }
         if (!model->IsCollidable)
             continue;
         Vertices.reserve(refCount * model->Vertices.size() * 0.2);
         Triangles.reserve(refCount * model->Triangles.size() * 0.2);
         InsertModelGeometry(doodad, model);
     }
     // Restore the stream position
     fseek(stream, mcnk->Source->Offset, SEEK_SET);
 }
References _definitions, _drawn, _paths, Cache, MapChunkHeader::DoodadRefs, GenericCache< K, T >::Get(), Chunk::GetStream(), MapChunk::Header, GenericCache< K, T >::Insert(), InsertModelGeometry(), Model::IsCollidable, IsSane(), DoodadDefinition::MmidIndex, CacheClass::ModelCache, Chunk::Offset, MapChunkHeader::OffsetMCRF, MapChunk::Source, Triangles, Model::Triangles, DoodadDefinition::UniqueId, Vertices, and Model::Vertices.
ReadDoodadDefinitions()
void DoodadHandler::ReadDoodadDefinitions (Chunk * chunk) private
Definition at line 79 of file DoodadHandler.cpp.
 {
     int32 count = chunk->Length / 36;
     _definitions = new std::vector<DoodadDefinition>;
     _definitions->reserve(count);
     FILE* stream = chunk->GetStream();
     for (int i = 0; i < count; i++)
     {
         DoodadDefinition def;
         def.Read(stream);
         _definitions->push_back(def);
     }
 }
References _definitions, and DoodadDefinition::Read().
Referenced by DoodadHandler().
ReadDoodadPaths()
void DoodadHandler::ReadDoodadPaths (Chunk * id, Chunk * data) private
Definition at line 93 of file DoodadHandler.cpp.
 {
     int paths = id->Length / 4;
     _paths = new std::vector<std::string>();
     _paths->reserve(paths);
     for (int i = 0; i < paths; i++)
     {
         FILE* idStream = id->GetStream();
         fseek(idStream, i * 4, SEEK_CUR);
         uint32 offset;
         if (fread(&offset, sizeof(uint32), 1, idStream) != 1)
             printf("DoodadHandler::ReadDoodadPaths: Failed to read some data expected 1, read 0\n");
         FILE* dataStream = data->GetStream();
         fseek(dataStream, offset + data->Offset, SEEK_SET);
         _paths->push_back(Utils::ReadString(dataStream));
     }
 }
References _paths, Chunk::GetStream(), Chunk::Offset, and Utils::ReadString().
Referenced by DoodadHandler().
Member Data Documentation
_definitions
std::vector<DoodadDefinition>* DoodadHandler::_definitions private
Definition at line 75 of file DoodadHandler.h.
Referenced by IsSane(), ProcessInternal(), ReadDoodadDefinitions(), and ~DoodadHandler().
_drawn
std::set<uint32> DoodadHandler::_drawn private
Definition at line 74 of file DoodadHandler.h.
Referenced by ProcessInternal().
_paths
std::vector<std::string>* DoodadHandler::_paths private
Definition at line 76 of file DoodadHandler.h.
Referenced by IsSane(), ProcessInternal(), ReadDoodadPaths(), and ~DoodadHandler().
Triangles
std::vector<Triangle<uint32> > DoodadHandler::Triangles
Definition at line 64 of file DoodadHandler.h.
Referenced by Geometry::AddAdt(), InsertModelGeometry(), and ProcessInternal().
Vertices
std::vector<Vector3> DoodadHandler::Vertices
Definition at line 63 of file DoodadHandler.h.
Referenced by Geometry::AddAdt(), InsertModelGeometry(), and ProcessInternal().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/DoodadHandler.h
src/tools/mesh_extractor/DoodadHandler.cpp