Azerotcore-wotlk: Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck Class Reference
Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyUnfriendlyNoTotemUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Definition at line 820 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyUnfriendlyNoTotemUnitInObjectRangeCheck()
Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::AnyUnfriendlyNoTotemUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
Definition at line 823 of file GridNotifiers.h.
 : i_obj(obj), i_funit(funit), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 824 of file GridNotifiers.h.
         {
             if (!u->IsAlive())
                 return false;
             if (u->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
                 return false;
             if (u->GetTypeId() == TYPEID_UNIT && (u->ToCreature()->IsTotem() || u->ToCreature()->IsTrigger() || u->ToCreature()->IsAvoidingAOE())) // pussywizard: added IsAvoidingAOE()
                 return false;
             if (!u->isTargetableForAttack(false, i_funit))
                 return false;
             return i_obj->IsWithinDistInMap(u, i_range) && !i_funit->IsFriendlyTo(u);
         }
References CREATURE_TYPE_NON_COMBAT_PET, Unit::GetCreatureType(), Object::GetTypeId(), i_funit, i_obj, i_range, Unit::IsAlive(), Creature::IsAvoidingAOE(), Unit::IsFriendlyTo(), Unit::isTargetableForAttack(), Unit::IsTotem(), Creature::IsTrigger(), WorldObject::IsWithinDistInMap(), Object::ToCreature(), and TYPEID_UNIT.
Member Data Documentation
i_funit
Unit const* Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_funit private
Definition at line 842 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_obj private
Definition at line 841 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::i_range private
Definition at line 843 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h