Azerotcore-wotlk: AreaTrigger_at_sentry_point Class Reference
AreaTrigger_at_sentry_point Class Reference
Public Member Functions
AreaTrigger_at_sentry_point ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 336 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_sentry_point()
AreaTrigger_at_sentry_point::AreaTrigger_at_sentry_point () inline
Definition at line 339 of file areatrigger_scripts.cpp.
 : AreaTriggerScript("at_sentry_point") { }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_sentry_point::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 341 of file areatrigger_scripts.cpp.
     {
         auto quest_status = player->GetQuestStatus(QUEST_MISSING_DIPLO_PT14);
         if (!player->IsAlive() || quest_status == QUEST_STATUS_NONE || quest_status == QUEST_STATUS_REWARDED)
             return false;
         if (!player->FindNearestCreature(NPC_TERVOSH, 100.0f))
         {
             if(Creature* tervosh = player->SummonCreature(NPC_TERVOSH, -3476.51f, -4105.94f, 17.1f, 5.3816f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                 tervosh->CastSpell(tervosh, SPELL_TELEPORT_VISUAL, true);
         }
         return true;
     }
References WorldObject::FindNearestCreature(), Player::GetQuestStatus(), Unit::IsAlive(), NPC_TERVOSH, QUEST_MISSING_DIPLO_PT14, QUEST_STATUS_NONE, QUEST_STATUS_REWARDED, SPELL_TELEPORT_VISUAL, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp