Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/ticker.h File Reference
ticker.h File Reference
#include "jemalloc/internal/util.h"
Classes
struct ticker_t
Functions
static void ticker_init (ticker_t *ticker, int32_t nticks)
static void ticker_copy (ticker_t *ticker, const ticker_t *other)
static int32_t ticker_read (const ticker_t *ticker)
static bool ticker_fixup (ticker_t *ticker)
static bool ticker_ticks (ticker_t *ticker, int32_t nticks)
static bool ticker_tick (ticker_t *ticker)
static bool ticker_trytick (ticker_t *ticker)
Function Documentation
ticker_copy()
static void ticker_copy (ticker_t * ticker, const ticker_t * other) inline static
Definition at line 26 of file ticker.h.
{
     *ticker = *other;
 }
Referenced by arena_tdata_get_hard().
ticker_fixup()
static bool ticker_fixup (ticker_t * ticker) static
Definition at line 59 of file ticker.h.
{
     ticker->tick = ticker->nticks;
     return true;
 }
References ticker_t::nticks, and ticker_t::tick.
Referenced by ticker_ticks().
ticker_init()
static void ticker_init (ticker_t * ticker, int32_t nticks) inline static
Definition at line 20 of file ticker.h.
{
     ticker->tick = nticks;
     ticker->nticks = nticks;
 }
References ticker_t::nticks, and ticker_t::tick.
Referenced by arena_tdata_get_hard(), and tcache_init().
ticker_read()
static int32_t ticker_read (const ticker_t * ticker) inline static
Definition at line 31 of file ticker.h.
{
     return ticker->tick;
 }
References ticker_t::tick.
ticker_tick()
static bool ticker_tick (ticker_t * ticker) inline static
Definition at line 74 of file ticker.h.
{
     return ticker_ticks(ticker, 1);
 }
References ticker_ticks().
Referenced by tcache_event().
ticker_ticks()
static bool ticker_ticks (ticker_t * ticker, int32_t nticks) inline static
Definition at line 65 of file ticker.h.
{
     ticker->tick -= nticks;
     if (unlikely(ticker->tick < 0)) {
         return ticker_fixup(ticker);
     }
     return false;
 }
References ticker_t::tick, ticker_fixup(), and unlikely.
Referenced by arena_decay_ticks(), and ticker_tick().
ticker_trytick()
static bool ticker_trytick (ticker_t * ticker) inline static
Definition at line 83 of file ticker.h.
{
     --ticker->tick;
     if (unlikely(ticker->tick < 0)) {
         return true;
     }
     return false;
 }
References ticker_t::tick, and unlikely.
Referenced by free_fastpath(), and JEMALLOC_ATTR().