Azerotcore-wotlk: Guild::BankTab Class Reference
Guild::BankTab Class Reference
Public Member Functions
BankTab (uint32 guildId, uint8 tabId)
void LoadFromDB (Field *fields)
bool LoadItemFromDB (Field *fields)
void Delete (CharacterDatabaseTransaction trans, bool removeItemsFromDB=false)
void WritePacket (WorldPacket &data) const
bool WriteSlotPacket (WorldPacket &data, uint8 slotId, bool ignoreEmpty=true) const
void WriteInfoPacket (WorldPacket &data) const
void SetInfo (std::string const &name, std::string const &icon)
void SetText (std::string const &text)
void SendText (const Guild *guild, WorldSession *session) const
Item * GetItem (uint8 slotId) const
bool SetItem (CharacterDatabaseTransaction trans, uint8 slotId, Item *pItem)
Private Attributes
uint32 m_guildId
uint8 m_tabId
Item * m_items [GUILD_BANK_MAX_SLOTS]
std::string m_name
std::string m_icon
std::string m_text
Detailed Description
Definition at line 540 of file Guild.h.
Constructor & Destructor Documentation
BankTab()
Guild::BankTab::BankTab (uint32 guildId, uint8 tabId) inline
Definition at line 543 of file Guild.h.
                                              : m_guildId(guildId), m_tabId(tabId)
         {
             memset(m_items, 0, GUILD_BANK_MAX_SLOTS * sizeof(Item*));
         }
References GUILD_BANK_MAX_SLOTS, and m_items.
Member Function Documentation
Delete()
void Guild::BankTab::Delete (CharacterDatabaseTransaction trans, bool removeItemsFromDB = false)
Definition at line 439 of file Guild.cpp.
 {
     for (uint8 slotId = 0; slotId < GUILD_BANK_MAX_SLOTS; ++slotId)
         if (Item* pItem = m_items[slotId])
         {
             pItem->RemoveFromWorld();
             if (removeItemsFromDB)
                 pItem->DeleteFromDB(trans);
             delete pItem;
             pItem = nullptr;
         }
 }
References GUILD_BANK_MAX_SLOTS.
GetItem()
Item* Guild::BankTab::GetItem (uint8 slotId) const inline
Definition at line 564 of file Guild.h.
 { return slotId < GUILD_BANK_MAX_SLOTS ?  m_items[slotId] : nullptr; }
References GUILD_BANK_MAX_SLOTS, and m_items.
Referenced by Guild::BankMoveItemData::_StoreItem().
LoadFromDB()
void Guild::BankTab::LoadFromDB (Field * fields)
Definition at line 393 of file Guild.cpp.
 {
     m_name = fields[2].GetString();
     m_icon = fields[3].GetString();
     m_text = fields[4].GetString();
 }
References Field::GetString(), and Guild::m_name.
LoadItemFromDB()
bool Guild::BankTab::LoadItemFromDB (Field * fields)
Definition at line 400 of file Guild.cpp.
 {
     uint8 slotId = fields[13].GetUInt8();
     ObjectGuid::LowType itemGuid = fields[14].GetUInt32();
     uint32 itemEntry = fields[15].GetUInt32();
     if (slotId >= GUILD_BANK_MAX_SLOTS)
     {
         LOG_ERROR("guild", "Invalid slot for item (GUID: %u, id: %u) in guild bank, skipped.", itemGuid, itemEntry);
         return false;
     }
     ItemTemplate const* proto = sObjectMgr->GetItemTemplate(itemEntry);
     if (!proto)
     {
         LOG_ERROR("guild", "Unknown item (GUID: %u, id: %u) in guild bank, skipped.", itemGuid, itemEntry);
         return false;
     }
     Item* pItem = NewItemOrBag(proto);
     if (!pItem->LoadFromDB(itemGuid, ObjectGuid::Empty, fields, itemEntry))
     {
         LOG_ERROR("guild", "Item (GUID %u, id: %u) not found in item_instance, deleting from guild bank!", itemGuid, itemEntry);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_NONEXISTENT_GUILD_BANK_ITEM);
         stmt->setUInt32(0, m_guildId);
         stmt->setUInt8 (1, m_tabId);
         stmt->setUInt8 (2, slotId);
         CharacterDatabase.Execute(stmt);
         delete pItem;
         return false;
     }
     pItem->AddToWorld();
     m_items[slotId] = pItem;
     return true;
 }
References Object::AddToWorld(), CHAR_DEL_NONEXISTENT_GUILD_BANK_ITEM, CharacterDatabase, ObjectGuid::Empty, Field::GetUInt32(), Field::GetUInt8(), GUILD_BANK_MAX_SLOTS, Item::LoadFromDB(), LOG_ERROR, NewItemOrBag(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), and sObjectMgr.
SendText()
void Guild::BankTab::SendText (const Guild * guild, WorldSession * session) const
Definition at line 572 of file Guild.cpp.
 {
     WorldPacket data(MSG_QUERY_GUILD_BANK_TEXT, 1 + m_text.size() + 1);
     data << uint8(m_tabId);
     data << m_text;
     if (session)
     {
         LOG_DEBUG("guild", "MSG_QUERY_GUILD_BANK_TEXT [%s]: Tabid: %u, Text: %s"
                        , session->GetPlayerInfo().c_str(), m_tabId, m_text.c_str());
         session->SendPacket(&data);
     }
     else
     {
         LOG_DEBUG("guild", "MSG_QUERY_GUILD_BANK_TEXT [Broadcast]: Tabid: %u, Text: %s", m_tabId, m_text.c_str());
         guild->BroadcastPacket(&data);
     }
 }
References Guild::BroadcastPacket(), WorldSession::GetPlayerInfo(), LOG_DEBUG, MSG_QUERY_GUILD_BANK_TEXT, and WorldSession::SendPacket().
SetInfo()
void Guild::BankTab::SetInfo (std::string const & name, std::string const & icon)
Definition at line 509 of file Guild.cpp.
 {
     if (m_name == name && m_icon == icon)
         return;
     m_name = name;
     m_icon = icon;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_BANK_TAB_INFO);
     stmt->setString(0, m_name);
     stmt->setString(1, m_icon);
     stmt->setUInt32(2, m_guildId);
     stmt->setUInt8 (3, m_tabId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_BANK_TAB_INFO, CharacterDatabase, Guild::m_name, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::HandleSetBankTabInfo().
SetItem()
bool Guild::BankTab::SetItem (CharacterDatabaseTransaction trans, uint8 slotId, Item * pItem)
Definition at line 542 of file Guild.cpp.
 {
     if (slotId >= GUILD_BANK_MAX_SLOTS)
         return false;
     m_items[slotId] = item;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_ITEM);
     stmt->setUInt32(0, m_guildId);
     stmt->setUInt8 (1, m_tabId);
     stmt->setUInt8 (2, slotId);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
     if (item)
     {
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_ITEM);
         stmt->setUInt32(0, m_guildId);
         stmt->setUInt8 (1, m_tabId);
         stmt->setUInt8 (2, slotId);
         stmt->setUInt32(3, item->GetGUID().GetCounter());
         CharacterDatabase.ExecuteOrAppend(trans, stmt);
         item->SetGuidValue(ITEM_FIELD_CONTAINED, ObjectGuid::Empty);
         item->SetGuidValue(ITEM_FIELD_OWNER, ObjectGuid::Empty);
         item->FSetState(ITEM_NEW);
         item->SaveToDB(trans);                                 // Not in inventory and can be saved standalone
     }
     return true;
 }
References CHAR_DEL_GUILD_BANK_ITEM, CHAR_INS_GUILD_BANK_ITEM, CharacterDatabase, ObjectGuid::Empty, Item::FSetState(), ObjectGuid::GetCounter(), Object::GetGUID(), GUILD_BANK_MAX_SLOTS, ITEM_FIELD_CONTAINED, ITEM_FIELD_OWNER, ITEM_NEW, Item::SaveToDB(), Object::SetGuidValue(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::BankMoveItemData::_StoreItem().
SetText()
void Guild::BankTab::SetText (std::string const & text)
Definition at line 525 of file Guild.cpp.
 {
     if (m_text == text)
         return;
     m_text = text;
     utf8truncate(m_text, MAX_GUILD_BANK_TAB_TEXT_LEN);          // DB and client size limitation
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_BANK_TAB_TEXT);
     stmt->setString(0, m_text);
     stmt->setUInt32(1, m_guildId);
     stmt->setUInt8 (2, m_tabId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_BANK_TAB_TEXT, CharacterDatabase, MAX_GUILD_BANK_TAB_TEXT_LEN, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), and utf8truncate().
WriteInfoPacket()
void Guild::BankTab::WriteInfoPacket (WorldPacket & data) const inline
Definition at line 554 of file Guild.h.
         {
             data << m_name;
             data << m_icon;
         }
References m_icon, and m_name.
WritePacket()
void Guild::BankTab::WritePacket (WorldPacket & data) const inline
Definition at line 452 of file Guild.cpp.
 {
     uint8 count = 0;
     size_t pos = data.wpos();
     data << uint8(0);
     for (uint8 slotId = 0; slotId < GUILD_BANK_MAX_SLOTS; ++slotId)
         if (WriteSlotPacket(data, slotId))
             ++count;
     data.put<uint8>(pos, count);
 }
References GUILD_BANK_MAX_SLOTS, ByteBuffer::put(), and ByteBuffer::wpos().
Referenced by Guild::_SendBankList().
WriteSlotPacket()
bool Guild::BankTab::WriteSlotPacket (WorldPacket & data, uint8 slotId, bool ignoreEmpty = true) const
Definition at line 467 of file Guild.cpp.
 {
     Item* pItem = GetItem(slotId);
     uint32 itemEntry = pItem ? pItem->GetEntry() : 0;
     if (!itemEntry && ignoreEmpty)
         return false;
     data << uint8(slotId);
     data << uint32(itemEntry);
     if (itemEntry)
     {
         data << uint32(0);                                  // 3.3.0 (0x00018020, 0x00018000)
         if (int32 random = pItem->GetItemRandomPropertyId())
         {
             data << int32(random);                          // Random item property id
             data << uint32(pItem->GetItemSuffixFactor());   // SuffixFactor
         }
         else
             data << int32(0);
         data << uint32(pItem->GetCount());                  // ITEM_FIELD_STACK_COUNT
         data << uint32(0);
         data << uint8(abs(pItem->GetSpellCharges()));       // Spell charges
         uint8 enchCount = 0;
         size_t enchCountPos = data.wpos();
         data << uint8(enchCount);                           // Number of enchantments
         for (uint32 i = PERM_ENCHANTMENT_SLOT; i < MAX_ENCHANTMENT_SLOT; ++i)
             if (uint32 enchId = pItem->GetEnchantmentId(EnchantmentSlot(i)))
             {
                 data << uint8(i);
                 data << uint32(enchId);
                 ++enchCount;
             }
         data.put<uint8>(enchCountPos, enchCount);
     }
     return true;
 }
References Item::GetCount(), Item::GetEnchantmentId(), Object::GetEntry(), Item::GetItemRandomPropertyId(), Item::GetItemSuffixFactor(), Item::GetSpellCharges(), MAX_ENCHANTMENT_SLOT, PERM_ENCHANTMENT_SLOT, ByteBuffer::put(), and ByteBuffer::wpos().
Referenced by Guild::_SendBankList().
Member Data Documentation
m_guildId
uint32 Guild::BankTab::m_guildId private
Definition at line 568 of file Guild.h.
m_icon
std::string Guild::BankTab::m_icon private
Definition at line 573 of file Guild.h.
Referenced by WriteInfoPacket().
m_items
Item* Guild::BankTab::m_items[GUILD_BANK_MAX_SLOTS] private
Definition at line 571 of file Guild.h.
Referenced by BankTab(), and GetItem().
m_name
std::string Guild::BankTab::m_name private
Definition at line 572 of file Guild.h.
Referenced by WriteInfoPacket().
m_tabId
uint8 Guild::BankTab::m_tabId private
Definition at line 569 of file Guild.h.
m_text
std::string Guild::BankTab::m_text private
Definition at line 574 of file Guild.h.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp