Azerotcore-wotlk: deps/mysqllite/dbug/dbug.c File Reference
dbug.c File Reference
#include <my_global.h>
#include <m_string.h>
#include <errno.h>
#include <my_pthread.h>
#include <stdarg.h>
Classes
struct link
struct settings
struct _db_code_state_
Macros
#define fnmatch(A, B, C) strcmp(A,B)
#define PRINTBUF 1024 /* Print buffer size */
#define INDENT 2 /* Indentation per trace level */
#define MAXDEPTH 200 /* Maximum trace depth default */
#define DEBUG_ON (1 << 1) /* Debug enabled */
#define FILE_ON (1 << 2) /* File name print enabled */
#define LINE_ON (1 << 3) /* Line number print enabled */
#define DEPTH_ON (1 << 4) /* Function nest level print enabled */
#define PROCESS_ON (1 << 5) /* Process name print enabled */
#define NUMBER_ON (1 << 6) /* Number each line of output */
#define PROFILE_ON (1 << 7) /* Print out profiling code */
#define PID_ON (1 << 8) /* Identify each line with process id */
#define TIMESTAMP_ON (1 << 9) /* timestamp every line of output */
#define FLUSH_ON_WRITE (1 << 10) /* Flush on every write */
#define OPEN_APPEND (1 << 11) /* Open for append */
#define TRACE_ON ((uint)1 << 31) /* Trace enabled. MUST be the highest bit!*/
#define TRACING (cs->stack->flags & TRACE_ON)
#define DEBUGGING (cs->stack->flags & DEBUG_ON)
#define PROFILING (cs->stack->flags & PROFILE_ON)
#define BOOLEAN my_bool
#define IMPORT extern /* Names defined externally */
#define EXPORT /* Allocated here, available globally */
#define AUTO auto /* Names to be allocated on stack */
#define REGISTER register /* Names to be placed in registers */
#define PROF_FILE "dbugmon.out"
#define PROF_EFMT "E\t%ld\t%s\n"
#define PROF_SFMT "S\t%lx\t%lx\t%s\n"
#define PROF_XFMT "X\t%ld\t%s\n"
#define AUTOS_REVERSE 0
#define SUBDIR 1 /* this MUST be 1 */
#define INCLUDE 2
#define EXCLUDE 4
#define MATCHED 65536
#define NOT_MATCHED 0
#define is_shared(S, V) ((S)->next && (S)->next->V == (S)->V)
#define get_code_state_if_not_set_or_return if (!cs && !((cs=code_state()))) return
#define get_code_state_or_return if (!((cs=code_state()))) return
#define ListAdd(A, B, C) ListAddDel(A,B,C,INCLUDE)
#define ListDel(A, B, C) ListAddDel(A,B,C,EXCLUDE)
#define DO_TRACE 1
#define DONT_TRACE 2
#define ENABLE_TRACE 3
#define DISABLE_TRACE 4
#define ERR_MISSING_RETURN "missing DBUG_RETURN or DBUG_VOID_RETURN macro in function \"%s\"\n"
#define ERR_OPEN "%s: can't open debug output stream \"%s\": "
#define ERR_CLOSE "%s: can't close debug file: "
#define ERR_ABORT "%s: debugger aborting because %s\n"
#define EXISTS(pathname) (FALSE) /* Assume no existance */
#define Writable(name) (TRUE)
#define Delay(A) (0)
#define framep_trace_flag(cs, frp)
#define fflags(cs) cs->stack->out_file ? ListFlags(cs->stack->functions) : TRACE_ON;
#define char_to_buf(C)
#define str_to_buf(S)
#define list_to_buf(l, f)
#define int_to_buf(i)
#define colon_to_buf
#define op_int_to_buf(C, val, def)
#define op_intf_to_buf(C, val, def, cond)
#define op_str_to_buf(C, val, cond)
#define op_list_to_buf(C, val, cond)
#define op_bool_to_buf(C, cond)
Typedefs
typedef struct _db_code_state_ CODE_STATE
Functions
static void perror ()
static struct link * ListAddDel (struct link *, const char *, const char *, int)
static struct link * ListCopy (struct link *)
static int InList (struct link *linkp, const char *cp)
static uint ListFlags (struct link *linkp)
static void FreeList (struct link *linkp)
static void DBUGOpenFile (CODE_STATE *, const char *, const char *, int)
static void DBUGCloseFile (CODE_STATE *cs, FILE *fp)
static void PushState (CODE_STATE *cs)
static void FreeState (CODE_STATE *cs, struct settings *state, int free_state)
static int DoTrace (CODE_STATE *cs)
static void DoPrefix (CODE_STATE *cs, uint line)
static char * DbugMalloc (size_t size)
static const char * BaseName (const char *pathname)
static void Indent (CODE_STATE *cs, int indent)
static void DbugFlush (CODE_STATE *)
static void DbugExit (const char *why)
static const char * DbugStrTok (const char *s)
static void DbugVfprintf (FILE *stream, const char *format, va_list args)
static CODE_STATE * code_state (void)
void _db_process_ (const char *name)
int DbugParse (CODE_STATE *cs, const char *control)
void FixTraceFlags_helper (CODE_STATE *cs, const char *func, struct _db_stack_frame_ *framep)
void FixTraceFlags (uint old_fflags, CODE_STATE *cs)
void _db_set_ (const char *control)
void _db_push_ (const char *control)
int _db_is_pushed_ ()
void _db_set_init_ (const char *control)
void _db_pop_ ()
int _db_explain_ (CODE_STATE *cs, char *buf, size_t len)
int _db_explain_init_ (char *buf, size_t len)
void _db_enter_ (const char *_func_, const char *_file_, uint _line_, struct _db_stack_frame_ *_stack_frame_)
void _db_return_ (uint _line_, struct _db_stack_frame_ *_stack_frame_)
void _db_pargs_ (uint _line_, const char *keyword)
void _db_doprnt_ (const char *format,...)
void _db_dump_ (uint _line_, const char *keyword, const unsigned char *memory, size_t length)
void _db_end_ ()
FILE * _db_fp_ (void)
BOOLEAN _db_keyword_ (CODE_STATE *cs, const char *keyword, int strict)
static void perror (char *s)
void _db_flush_ ()
void _db_suicide_ ()
void _db_lock_file_ ()
void _db_unlock_file_ ()
const char * _db_get_func_ (void)
Variables
static BOOLEAN init_done = FALSE
static struct settings init_settings
static const char * db_process = 0
my_bool _dbug_on_ = TRUE
static pthread_mutex_t THR_LOCK_dbug
Macro Definition Documentation
AUTO
#define AUTO auto /* Names to be allocated on stack */
Definition at line 151 of file dbug.c.
AUTOS_REVERSE
#define AUTOS_REVERSE 0
Definition at line 175 of file dbug.c.
BOOLEAN
#define BOOLEAN my_bool
Definition at line 143 of file dbug.c.
char_to_buf
#define char_to_buf (C)
Value:
        do {                  \
        *buf++=(C);                             \
        if (buf >= end) goto overflow;          \
      } while (0)
Definition at line 916 of file dbug.c.
colon_to_buf
#define colon_to_buf
Value:
        do {                     \
        if (buf != start) char_to_buf(':');     \
      } while(0)
Definition at line 943 of file dbug.c.
DEBUG_ON
#define DEBUG_ON (1 << 1) /* Debug enabled */
Definition at line 122 of file dbug.c.
DEBUGGING
#define DEBUGGING (cs->stack->flags & DEBUG_ON)
Definition at line 136 of file dbug.c.
Delay
#define Delay (A) (0)
Definition at line 395 of file dbug.c.
DEPTH_ON
#define DEPTH_ON (1 << 4) /* Function nest level print enabled */
Definition at line 125 of file dbug.c.
DISABLE_TRACE
#define DISABLE_TRACE 4
Definition at line 302 of file dbug.c.
DO_TRACE
#define DO_TRACE 1
Definition at line 299 of file dbug.c.
DONT_TRACE
#define DONT_TRACE 2
Definition at line 300 of file dbug.c.
ENABLE_TRACE
#define ENABLE_TRACE 3
Definition at line 301 of file dbug.c.
ERR_ABORT
#define ERR_ABORT "%s: debugger aborting because %s\n"
Definition at line 329 of file dbug.c.
ERR_CLOSE
#define ERR_CLOSE "%s: can't close debug file: "
Definition at line 328 of file dbug.c.
ERR_MISSING_RETURN
#define ERR_MISSING_RETURN "missing DBUG_RETURN or DBUG_VOID_RETURN macro in function \"%s\"\n"
Definition at line 326 of file dbug.c.
ERR_OPEN
#define ERR_OPEN "%s: can't open debug output stream \"%s\": "
Definition at line 327 of file dbug.c.
EXCLUDE
#define EXCLUDE 4
Definition at line 201 of file dbug.c.
EXISTS
#define EXISTS (pathname) (FALSE) /* Assume no existance */
Definition at line 337 of file dbug.c.
EXPORT
#define EXPORT /* Allocated here, available globally */
Definition at line 150 of file dbug.c.
fflags
#define fflags (cs) cs->stack->out_file ? ListFlags(cs->stack->functions) : TRACE_ON;
Definition at line 699 of file dbug.c.
FILE_ON
#define FILE_ON (1 << 2) /* File name print enabled */
Definition at line 123 of file dbug.c.
FLUSH_ON_WRITE
#define FLUSH_ON_WRITE (1 << 10) /* Flush on every write */
Definition at line 131 of file dbug.c.
fnmatch
#define fnmatch (A, B, C) strcmp(A,B)
Definition at line 95 of file dbug.c.
framep_trace_flag
#define framep_trace_flag (cs, frp)
Value:
                                     (frp ?                                    \
                                     frp->level & TRACE_ON :                 \
                              (ListFlags(cs->stack->functions) & INCLUDE) ?  \
                                       0 : (uint)TRACE_ON)
Definition at line 670 of file dbug.c.
get_code_state_if_not_set_or_return
#define get_code_state_if_not_set_or_return if (!cs && !((cs=code_state()))) return
Definition at line 274 of file dbug.c.
get_code_state_or_return
#define get_code_state_or_return if (!((cs=code_state()))) return
Definition at line 275 of file dbug.c.
IMPORT
#define IMPORT extern /* Names defined externally */
Definition at line 149 of file dbug.c.
INCLUDE
#define INCLUDE 2
Definition at line 200 of file dbug.c.
INDENT
#define INDENT 2 /* Indentation per trace level */
Definition at line 110 of file dbug.c.
int_to_buf
#define int_to_buf (i)
Value:
        do {                     \
        char b[50];                             \
        int10_to_str((i), b, 10);               \
        str_to_buf(b);                          \
      } while (0)
Definition at line 938 of file dbug.c.
is_shared
#define is_shared (S, V) ((S)->next && (S)->next->V == (S)->V)
Definition at line 231 of file dbug.c.
LINE_ON
#define LINE_ON (1 << 3) /* Line number print enabled */
Definition at line 124 of file dbug.c.
list_to_buf
#define list_to_buf (l, f)
Value:
        do {                 \
        struct link *listp=(l);                 \
        while (listp)                           \
        {                                       \
          if (listp->flags & (f))               \
          {                                     \
            str_to_buf(listp->str);             \
            if (listp->flags & SUBDIR)          \
              char_to_buf('/');                 \
          }                                     \
          listp=listp->next_link;               \
        }                                       \
      } while (0)
Definition at line 925 of file dbug.c.
ListAdd
#define ListAdd (A, B, C) ListAddDel(A,B,C,INCLUDE)
Definition at line 278 of file dbug.c.
ListDel
#define ListDel (A, B, C) ListAddDel(A,B,C,EXCLUDE)
Definition at line 279 of file dbug.c.
MATCHED
#define MATCHED 65536
Definition at line 203 of file dbug.c.
MAXDEPTH
#define MAXDEPTH 200 /* Maximum trace depth default */
Definition at line 111 of file dbug.c.
NOT_MATCHED
#define NOT_MATCHED 0
Definition at line 204 of file dbug.c.
NUMBER_ON
#define NUMBER_ON (1 << 6) /* Number each line of output */
Definition at line 127 of file dbug.c.
op_bool_to_buf
#define op_bool_to_buf (C, cond)
Value:
        do {            \
        if ((cond))                             \
        {                                       \
          colon_to_buf;                         \
          char_to_buf((C));                     \
        }                                       \
      } while (0)
Definition at line 988 of file dbug.c.
op_int_to_buf
#define op_int_to_buf (C, val, def)
Value:
        do {         \
        if ((val) != (def))                     \
        {                                       \
          colon_to_buf;                         \
          char_to_buf((C));                     \
          int_to_buf(val);                      \
        }                                       \
      } while (0)
Definition at line 946 of file dbug.c.
op_intf_to_buf
#define op_intf_to_buf (C, val, def, cond)
Value:
        do {  \
        if ((cond))                             \
        {                                       \
          colon_to_buf;                         \
          char_to_buf((C));                     \
          if ((val) != (def)) int_to_buf(val);  \
        }                                       \
      } while (0)
Definition at line 954 of file dbug.c.
op_list_to_buf
#define op_list_to_buf (C, val, cond)
Value:
        do {       \
        if ((cond))                             \
        {                                       \
          int f=ListFlags(val);                 \
          colon_to_buf;                         \
          char_to_buf((C));                     \
          if (f & INCLUDE)                      \
            list_to_buf(val, INCLUDE);          \
          if (f & EXCLUDE)                      \
          {                                     \
            colon_to_buf;                       \
            char_to_buf('-');                   \
            char_to_buf((C));                   \
            list_to_buf(val, EXCLUDE);          \
          }                                     \
        }                                       \
      } while (0)
Definition at line 971 of file dbug.c.
op_str_to_buf
#define op_str_to_buf (C, val, cond)
Value:
        do {        \
        if ((cond))                             \
        {                                       \
          char *s=(val);                        \
          colon_to_buf;                         \
          char_to_buf((C));                     \
          if (*s) str_to_buf(s);                \
        }                                       \
      } while (0)
Definition at line 962 of file dbug.c.
OPEN_APPEND
#define OPEN_APPEND (1 << 11) /* Open for append */
Definition at line 132 of file dbug.c.
PID_ON
#define PID_ON (1 << 8) /* Identify each line with process id */
Definition at line 129 of file dbug.c.
PRINTBUF
#define PRINTBUF 1024 /* Print buffer size */
Definition at line 109 of file dbug.c.
PROCESS_ON
#define PROCESS_ON (1 << 5) /* Process name print enabled */
Definition at line 126 of file dbug.c.
PROF_EFMT
#define PROF_EFMT "E\t%ld\t%s\n"
Definition at line 168 of file dbug.c.
PROF_FILE
#define PROF_FILE "dbugmon.out"
Definition at line 167 of file dbug.c.
PROF_SFMT
#define PROF_SFMT "S\t%lx\t%lx\t%s\n"
Definition at line 169 of file dbug.c.
PROF_XFMT
#define PROF_XFMT "X\t%ld\t%s\n"
Definition at line 170 of file dbug.c.
PROFILE_ON
#define PROFILE_ON (1 << 7) /* Print out profiling code */
Definition at line 128 of file dbug.c.
PROFILING
#define PROFILING (cs->stack->flags & PROFILE_ON)
Definition at line 137 of file dbug.c.
REGISTER
#define REGISTER register /* Names to be placed in registers */
Definition at line 152 of file dbug.c.
str_to_buf
#define str_to_buf (S)
Value:
        do {                   \
        char_to_buf(',');                       \
        buf=strnmov(buf, (S), len+1);           \
        if (buf >= end) goto overflow;          \
      } while (0)
Definition at line 920 of file dbug.c.
SUBDIR
#define SUBDIR 1 /* this MUST be 1 */
Definition at line 199 of file dbug.c.
TIMESTAMP_ON
#define TIMESTAMP_ON (1 << 9) /* timestamp every line of output */
Definition at line 130 of file dbug.c.
TRACE_ON
#define TRACE_ON ((uint)1 << 31) /* Trace enabled. MUST be the highest bit!*/
Definition at line 133 of file dbug.c.
TRACING
#define TRACING (cs->stack->flags & TRACE_ON)
Definition at line 135 of file dbug.c.
Writable
#define Writable (name) (TRUE)
Definition at line 338 of file dbug.c.
Typedef Documentation
CODE_STATE
typedef struct _db_code_state_ CODE_STATE
Function Documentation
_db_doprnt_()
void _db_doprnt_ (const char * format, ...)
Definition at line 1254 of file dbug.c.
 {
   va_list args;
   CODE_STATE *cs;
   get_code_state_or_return;
   va_start(args,format);
   if (_db_keyword_(cs, cs->u_keyword, 0))
   {
     int save_errno=errno;
     if (!cs->locked)
       pthread_mutex_lock(&THR_LOCK_dbug);
     DoPrefix(cs, cs->u_line);
     if (TRACING)
       Indent(cs, cs->level + 1);
     else
       (void) fprintf(cs->stack->out_file, "%s: ", cs->func);
     (void) fprintf(cs->stack->out_file, "%s: ", cs->u_keyword);
     DbugVfprintf(cs->stack->out_file, format, args);
     DbugFlush(cs);
     errno=save_errno;
   }
   va_end(args);
 }
References _db_keyword_(), DbugFlush(), DbugVfprintf(), DoPrefix(), errno, format(), fprintf(), _db_code_state_::func, get_code_state_or_return, Indent(), _db_code_state_::level, _db_code_state_::locked, settings::out_file, _db_code_state_::stack, THR_LOCK_dbug, TRACING, _db_code_state_::u_keyword, and _db_code_state_::u_line.
_db_dump_()
void _db_dump_ (uint _line_, const char * keyword, const unsigned char * memory, size_t length)
Definition at line 1311 of file dbug.c.
 {
   int pos;
   CODE_STATE *cs;
   get_code_state_or_return;
   if (_db_keyword_(cs, keyword, 0))
   {
     if (!cs->locked)
       pthread_mutex_lock(&THR_LOCK_dbug);
     DoPrefix(cs, _line_);
     if (TRACING)
     {
       Indent(cs, cs->level + 1);
       pos= min(max(cs->level-cs->stack->sub_level,0)*INDENT,80);
     }
     else
     {
       fprintf(cs->stack->out_file, "%s: ", cs->func);
     }
     (void) fprintf(cs->stack->out_file, "%s: Memory: 0x%lx  Bytes: (%ld)\n",
             keyword, (ulong) memory, (long) length);
     pos=0;
     while (length-- > 0)
     {
       uint tmp= *((unsigned char*) memory++);
       if ((pos+=3) >= 80)
       {
         fputc('\n',cs->stack->out_file);
         pos=3;
       }
       fputc(_dig_vec_upper[((tmp >> 4) & 15)], cs->stack->out_file);
       fputc(_dig_vec_upper[tmp & 15], cs->stack->out_file);
       fputc(' ',cs->stack->out_file);
     }
     (void) fputc('\n',cs->stack->out_file);
     DbugFlush(cs);
   }
 }
References _db_keyword_(), _dig_vec_upper, DbugFlush(), DoPrefix(), fprintf(), _db_code_state_::func, get_code_state_or_return, INDENT, Indent(), G3D::length(), _db_code_state_::level, _db_code_state_::locked, max, min, settings::out_file, pos(), _db_code_state_::stack, settings::sub_level, THR_LOCK_dbug, and TRACING.
_db_end_()
void _db_end_ (void)
Definition at line 1616 of file dbug.c.
 {
   struct settings *discard;
   static struct settings tmp;
   CODE_STATE *cs;
   /*
     Set _dbug_on_ to be able to do full reset even when DEBUGGER_OFF was
     called after dbug was initialized
   */
   _dbug_on_= 1;
   get_code_state_or_return;
   while ((discard= cs->stack))
   {
     if (discard == &init_settings)
       break;
     cs->stack= discard->next;
     FreeState(cs, discard, 1);
   }
   tmp= init_settings;
   /* Use mutex lock to make it less likely anyone access out_file */
   pthread_mutex_lock(&THR_LOCK_dbug);
   init_settings.flags=    OPEN_APPEND;
   init_settings.out_file= stderr;
   init_settings.prof_file= stderr;
   init_settings.maxdepth= 0;
   init_settings.delay= 0;
   init_settings.sub_level= 0;
   init_settings.functions= 0;
   init_settings.p_functions= 0;
   init_settings.keywords= 0;
   init_settings.processes= 0;
   pthread_mutex_unlock(&THR_LOCK_dbug);
   FreeState(cs, &tmp, 0);
 }
References _dbug_on_, settings::delay, settings::flags, FreeState(), settings::functions, get_code_state_or_return, init_settings, settings::keywords, settings::maxdepth, settings::next, OPEN_APPEND, settings::out_file, settings::p_functions, settings::processes, settings::prof_file, settings::sub_level, and THR_LOCK_dbug.
_db_enter_()
void _db_enter_ (const char * _func_, const char * _file_, uint _line_, struct _db_stack_frame_ * _stack_frame_)
Definition at line 1094 of file dbug.c.
 {
   int save_errno;
   CODE_STATE *cs;
   if (!((cs=code_state())))
   {
     _stack_frame_->level= 0; /* Set to avoid valgrind warnings if dbug is enabled later */
     _stack_frame_->prev= 0;
     return;
   }
   save_errno= errno;
   _stack_frame_->func= cs->func;
   _stack_frame_->file= cs->file;
   cs->func=  _func_;
   cs->file=  _file_;
   _stack_frame_->prev= cs->framep;
   _stack_frame_->level= ++cs->level | framep_trace_flag(cs, cs->framep);
   cs->framep= _stack_frame_;
   switch (DoTrace(cs)) {
   case ENABLE_TRACE:
     cs->framep->level|= TRACE_ON;
     if (!TRACING) break;
     /* fall through */
   case DO_TRACE:
     if (TRACING)
     {
       if (!cs->locked)
         pthread_mutex_lock(&THR_LOCK_dbug);
       DoPrefix(cs, _line_);
       Indent(cs, cs->level);
       (void) fprintf(cs->stack->out_file, ">%s\n", cs->func);
       DbugFlush(cs);                       /* This does a unlock */
     }
     break;
   case DISABLE_TRACE:
     cs->framep->level&= ~TRACE_ON;
     /* fall through */
   case DONT_TRACE:
     break;
   }
   errno=save_errno;
 }
References code_state(), DbugFlush(), DISABLE_TRACE, DO_TRACE, DONT_TRACE, DoPrefix(), DoTrace(), ENABLE_TRACE, errno, _db_code_state_::file, _db_stack_frame_::file, fprintf(), _db_code_state_::framep, framep_trace_flag, _db_code_state_::func, _db_stack_frame_::func, Indent(), _db_code_state_::level, _db_stack_frame_::level, _db_code_state_::locked, settings::out_file, _db_stack_frame_::prev, _db_code_state_::stack, THR_LOCK_dbug, TRACE_ON, and TRACING.
_db_explain_()
int _db_explain_ (CODE_STATE * cs, char * buf, size_t len)
Definition at line 996 of file dbug.c.
 {
   char *start=buf, *end=buf+len-4;
   get_code_state_if_not_set_or_return *buf=0;
   op_list_to_buf('d', cs->stack->keywords, DEBUGGING);
   op_int_to_buf ('D', cs->stack->delay, 0);
   op_list_to_buf('f', cs->stack->functions, cs->stack->functions);
   op_bool_to_buf('F', cs->stack->flags & FILE_ON);
   op_bool_to_buf('i', cs->stack->flags & PID_ON);
   op_list_to_buf('g', cs->stack->p_functions, PROFILING);
   op_bool_to_buf('L', cs->stack->flags & LINE_ON);
   op_bool_to_buf('n', cs->stack->flags & DEPTH_ON);
   op_bool_to_buf('N', cs->stack->flags & NUMBER_ON);
   op_str_to_buf(
     ((cs->stack->flags & FLUSH_ON_WRITE ? 0 : 32) |
      (cs->stack->flags & OPEN_APPEND ? 'A' : 'O')),
     cs->stack->name, cs->stack->out_file != stderr);
   op_list_to_buf('p', cs->stack->processes, cs->stack->processes);
   op_bool_to_buf('P', cs->stack->flags & PROCESS_ON);
   op_bool_to_buf('r', cs->stack->sub_level != 0);
   op_intf_to_buf('t', cs->stack->maxdepth, MAXDEPTH, TRACING);
   op_bool_to_buf('T', cs->stack->flags & TIMESTAMP_ON);
   *buf= '\0';
   return 0;
 overflow:
   *end++= '.';
   *end++= '.';
   *end++= '.';
   *end=   '\0';
   return 1;
 }
References DEBUGGING, settings::delay, DEPTH_ON, FILE_ON, settings::flags, FLUSH_ON_WRITE, settings::functions, get_code_state_if_not_set_or_return, settings::keywords, LINE_ON, MAXDEPTH, settings::maxdepth, settings::name, NUMBER_ON, op_bool_to_buf, op_int_to_buf, op_intf_to_buf, op_list_to_buf, op_str_to_buf, OPEN_APPEND, settings::out_file, settings::p_functions, PID_ON, PROCESS_ON, settings::processes, PROFILING, _db_code_state_::stack, settings::sub_level, TIMESTAMP_ON, and TRACING.
Referenced by _db_explain_init_().
_db_explain_init_()
int _db_explain_init_ (char * buf, size_t len)
Definition at line 1052 of file dbug.c.
 {
   CODE_STATE cs;
   bzero((uchar*) &cs,sizeof(cs));
   cs.stack=&init_settings;
   return _db_explain_(&cs, buf, len);
 }
References _db_explain_(), bzero, init_settings, and _db_code_state_::stack.
_db_flush_()
void _db_flush_ ()
Definition at line 2219 of file dbug.c.
 {
   CODE_STATE *cs= NULL;
   get_code_state_or_return;
   (void) fflush(cs->stack->out_file);
 }
References get_code_state_or_return, NULL, settings::out_file, and _db_code_state_::stack.
_db_fp_()
FILE* _db_fp_ (void)
Definition at line 1685 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return NULL;
   return cs->stack->out_file;
 }
_db_get_func_()
const char* _db_get_func_ (void)
Definition at line 2262 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return NULL;
   return cs->func;
 }
References _db_code_state_::func, get_code_state_or_return, and NULL.
_db_is_pushed_()
int _db_is_pushed_ (void)
Returns TRUE if session-local settings have been set.
Definition at line 838 of file dbug.c.
 {
   CODE_STATE *cs= NULL;
   get_code_state_or_return FALSE;
   return (cs->stack != &init_settings);
 }
References FALSE, get_code_state_or_return, init_settings, NULL, and _db_code_state_::stack.
_db_keyword_()
BOOLEAN _db_keyword_ (CODE_STATE * cs, const char * keyword, int strict)
Definition at line 1712 of file dbug.c.
 {
   get_code_state_if_not_set_or_return FALSE;
   strict=strict ? INCLUDE : INCLUDE|MATCHED;
   return DEBUGGING && DoTrace(cs) & DO_TRACE &&
          InList(cs->stack->keywords, keyword) & strict;
 }
References DEBUGGING, DO_TRACE, DoTrace(), FALSE, get_code_state_if_not_set_or_return, INCLUDE, InList(), settings::keywords, MATCHED, and _db_code_state_::stack.
Referenced by _db_doprnt_(), and _db_dump_().
_db_lock_file_()
void _db_lock_file_ (void)
Definition at line 2246 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   pthread_mutex_lock(&THR_LOCK_dbug);
   cs->locked=1;
 }
References get_code_state_or_return, _db_code_state_::locked, and THR_LOCK_dbug.
_db_pargs_()
void _db_pargs_ (uint _line_, const char * keyword)
Definition at line 1219 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   cs->u_line= _line_;
   cs->u_keyword= keyword;
 }
References get_code_state_or_return, _db_code_state_::u_keyword, and _db_code_state_::u_line.
_db_pop_()
void _db_pop_ (void)
Definition at line 886 of file dbug.c.
 {
   struct settings *discard;
   uint old_fflags;
   CODE_STATE *cs;
   get_code_state_or_return;
   discard= cs->stack;
   if (discard != &init_settings)
   {
     old_fflags=fflags(cs);
     cs->stack= discard->next;
     FreeState(cs, discard, 1);
     FixTraceFlags(old_fflags, cs);
   }
 }
References fflags, FixTraceFlags(), FreeState(), get_code_state_or_return, init_settings, settings::next, and _db_code_state_::stack.
_db_process_()
void _db_process_ (const char * name)
Definition at line 410 of file dbug.c.
 {
   CODE_STATE *cs;
   if (!db_process)
     db_process= name;
   get_code_state_or_return;
   cs->process= name;
 }
References db_process, get_code_state_or_return, name, and _db_code_state_::process.
_db_push_()
void _db_push_ (const char * control)
Definition at line 822 of file dbug.c.
 {
   CODE_STATE *cs;
   uint old_fflags;
   get_code_state_or_return;
   old_fflags=fflags(cs);
   PushState(cs);
   if (DbugParse(cs, control))
     FixTraceFlags(old_fflags, cs);
 }
References DbugParse(), fflags, FixTraceFlags(), get_code_state_or_return, and PushState().
_db_return_()
void _db_return_ (uint _line_, struct _db_stack_frame_ * _stack_frame_)
Definition at line 1160 of file dbug.c.
 {
   int save_errno=errno;
   uint _slevel_= _stack_frame_->level & ~TRACE_ON;
   CODE_STATE *cs;
   get_code_state_or_return;
   if (cs->framep != _stack_frame_)
   {
     char buf[512];
     my_snprintf(buf, sizeof(buf), ERR_MISSING_RETURN, cs->func);
     DbugExit(buf);
   }
   if (DoTrace(cs) & DO_TRACE)
   {
     if (TRACING)
     {
       if (!cs->locked)
         pthread_mutex_lock(&THR_LOCK_dbug);
       DoPrefix(cs, _line_);
       Indent(cs, cs->level);
       (void) fprintf(cs->stack->out_file, "<%s\n", cs->func);
       DbugFlush(cs);
     }
   }
   /*
     Check to not set level < 0. This can happen if DBUG was disabled when
     function was entered and enabled in function.
   */
   cs->level= _slevel_ != 0 ? _slevel_ - 1 : 0;
   cs->func= _stack_frame_->func;
   cs->file= _stack_frame_->file;
   if (cs->framep != NULL)
     cs->framep= cs->framep->prev;
   errno=save_errno;
 }
References DbugExit(), DbugFlush(), DO_TRACE, DoPrefix(), DoTrace(), ERR_MISSING_RETURN, errno, _db_code_state_::file, _db_stack_frame_::file, fprintf(), _db_code_state_::framep, _db_code_state_::func, _db_stack_frame_::func, get_code_state_or_return, Indent(), _db_code_state_::level, _db_stack_frame_::level, _db_code_state_::locked, my_snprintf(), NULL, settings::out_file, _db_stack_frame_::prev, _db_code_state_::stack, THR_LOCK_dbug, TRACE_ON, and TRACING.
_db_set_()
void _db_set_ (const char * control)
Definition at line 792 of file dbug.c.
 {
   CODE_STATE *cs;
   uint old_fflags;
   get_code_state_or_return;
   old_fflags=fflags(cs);
   if (cs->stack == &init_settings)
     PushState(cs);
   if (DbugParse(cs, control))
     FixTraceFlags(old_fflags, cs);
 }
References DbugParse(), fflags, FixTraceFlags(), get_code_state_or_return, init_settings, PushState(), and _db_code_state_::stack.
_db_set_init_()
void _db_set_init_ (const char * control)
Definition at line 860 of file dbug.c.
 {
   CODE_STATE tmp_cs;
   bzero((uchar*) &tmp_cs, sizeof(tmp_cs));
   tmp_cs.stack= &init_settings;
   tmp_cs.process= db_process ? db_process : "dbug";
   DbugParse(&tmp_cs, control);
 }
References bzero, db_process, DbugParse(), init_settings, _db_code_state_::process, and _db_code_state_::stack.
_db_suicide_()
void _db_suicide_ ()
Definition at line 2228 of file dbug.c.
 {
   int retval;
   sigset_t new_mask;
   sigfillset(&new_mask);
   fprintf(stderr, "SIGKILL myself\n");
   fflush(stderr);
   retval= kill(getpid(), SIGKILL);
   assert(retval == 0);
   retval= sigsuspend(&new_mask);
   fprintf(stderr, "sigsuspend returned %d errno %d \n", retval, errno);
   assert(FALSE); /* With full signal mask, we should never return here. */
 }
References assert(), errno, FALSE, and fprintf().
_db_unlock_file_()
void _db_unlock_file_ (void)
Definition at line 2254 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   cs->locked=0;
   pthread_mutex_unlock(&THR_LOCK_dbug);
 }
References get_code_state_or_return, _db_code_state_::locked, and THR_LOCK_dbug.
BaseName()
static const char * BaseName (const char * pathname) static
Definition at line 2040 of file dbug.c.
 {
   register const char *base;
   base= strrchr(pathname, FN_LIBCHAR);
   if (base++ == NullS)
     base= pathname;
   return base;
 }
References FN_LIBCHAR, and NullS.
Referenced by DoPrefix().
code_state()
static CODE_STATE* code_state (void) static
Definition at line 352 of file dbug.c.
 {
   CODE_STATE *cs, **cs_ptr;
   /*
     _dbug_on_ is reset if we don't plan to use any debug commands at all and
     we want to run on maximum speed
    */
   if (!_dbug_on_)
     return 0;
   if (!init_done)
   {
     init_done=TRUE;
     pthread_mutex_init(&THR_LOCK_dbug, NULL);
     bzero(&init_settings, sizeof(init_settings));
     init_settings.out_file=stderr;
     init_settings.flags=OPEN_APPEND;
   }
   if (!(cs_ptr= (CODE_STATE**) my_thread_var_dbug()))
     return 0;                                   /* Thread not initialised */
   if (!(cs= *cs_ptr))
   {
     cs=(CODE_STATE*) DbugMalloc(sizeof(*cs));
     bzero((uchar*) cs,sizeof(*cs));
     cs->process= db_process ? db_process : "dbug";
     cs->func="?func";
     cs->file="?file";
     cs->stack=&init_settings;
     *cs_ptr= cs;
   }
   return cs;
 }
References _dbug_on_, bzero, db_process, DbugMalloc(), settings::flags, init_done, init_settings, my_thread_var_dbug(), NULL, OPEN_APPEND, settings::out_file, THR_LOCK_dbug, and TRUE.
Referenced by _db_enter_(), and DbugExit().
DBUGCloseFile()
static void DBUGCloseFile (CODE_STATE * cs, FILE * fp) static
Definition at line 1938 of file dbug.c.
 {
   if (fp != NULL && fp != stderr && fp != stdout && fclose(fp) == EOF)
   {
     pthread_mutex_lock(&THR_LOCK_dbug);
     (void) fprintf(cs->stack->out_file, ERR_CLOSE, cs->process);
     perror("");
     DbugFlush(cs);
   }
 }
References DbugFlush(), ERR_CLOSE, fprintf(), NULL, settings::out_file, perror(), _db_code_state_::process, _db_code_state_::stack, and THR_LOCK_dbug.
Referenced by DbugParse(), and FreeState().
DbugExit()
static void DbugExit (const char * why) static
Definition at line 1969 of file dbug.c.
 {
   CODE_STATE *cs=code_state();
   (void) fprintf(stderr, ERR_ABORT, cs ? cs->process : "(null)", why);
   (void) fflush(stderr);
   DBUG_ABORT();
 }
References code_state(), DBUG_ABORT, ERR_ABORT, fprintf(), and _db_code_state_::process.
Referenced by _db_return_(), and DbugMalloc().
DbugFlush()
static void DbugFlush (CODE_STATE * cs) static
Definition at line 2204 of file dbug.c.
 {
   if (cs->stack->flags & FLUSH_ON_WRITE)
   {
     (void) fflush(cs->stack->out_file);
     if (cs->stack->delay)
       (void) Delay(cs->stack->delay);
   }
   if (!cs->locked)
     pthread_mutex_unlock(&THR_LOCK_dbug);
 } /* DbugFlush */
References settings::delay, Delay, settings::flags, FLUSH_ON_WRITE, _db_code_state_::locked, settings::out_file, _db_code_state_::stack, and THR_LOCK_dbug.
Referenced by _db_doprnt_(), _db_dump_(), _db_enter_(), _db_return_(), and DBUGCloseFile().
DbugMalloc()
static char * DbugMalloc (size_t size) static
Definition at line 1999 of file dbug.c.
 {
   register char *new_malloc;
   if (!(new_malloc= (char*) malloc(size)))
     DbugExit("out of memory");
   return new_malloc;
 }
References DbugExit().
Referenced by code_state(), ListAddDel(), ListCopy(), and PushState().
DBUGOpenFile()
static void DBUGOpenFile (CODE_STATE * cs, const char * name, const char * end, int append) static
Definition at line 1872 of file dbug.c.
 {
   REGISTER FILE *fp;
   REGISTER BOOLEAN newfile;
   if (name != NULL)
   {
     if (end)
     {
       size_t len=end-name;
       memcpy(cs->stack->name, name, len);
       cs->stack->name[len]=0;
     }
     else
     strmov(cs->stack->name,name);
     name=cs->stack->name;
     if (strcmp(name, "-") == 0)
     {
       cs->stack->out_file= stdout;
       cs->stack->flags |= FLUSH_ON_WRITE;
       cs->stack->name[0]=0;
     }
     else
     {
       if (!Writable(name))
       {
         (void) fprintf(stderr, ERR_OPEN, cs->process, name);
         perror("");
         fflush(stderr);
       }
       else
       {
         newfile= !EXISTS(name);
         if (!(fp= fopen(name, append ? "a+" : "w")))
         {
           (void) fprintf(stderr, ERR_OPEN, cs->process, name);
           perror("");
           fflush(stderr);
         }
         else
         {
           cs->stack->out_file= fp;
         }
       }
     }
   }
 }
References utf8::append(), BOOLEAN, ERR_OPEN, EXISTS, settings::flags, FLUSH_ON_WRITE, fprintf(), memcpy, name, settings::name, NULL, settings::out_file, perror(), _db_code_state_::process, REGISTER, _db_code_state_::stack, strmov(), and Writable.
Referenced by DbugParse().
DbugParse()
int DbugParse (CODE_STATE * cs, const char * control)
Definition at line 451 of file dbug.c.
 {
   const char *end;
   int rel, f_used=0;
   struct settings *stack;
   stack= cs->stack;
   if (control[0] == '-' && control[1] == '#')
     control+=2;
   rel= control[0] == '+' || control[0] == '-';
   if ((!rel || (!stack->out_file && !stack->next)))
   {
     /* Free memory associated with the state before resetting its members */
     FreeState(cs, stack, 0);
     stack->flags= 0;
     stack->delay= 0;
     stack->maxdepth= 0;
     stack->sub_level= 0;
     stack->out_file= stderr;
     stack->prof_file= NULL;
     stack->functions= NULL;
     stack->p_functions= NULL;
     stack->keywords= NULL;
     stack->processes= NULL;
   }
   else if (!stack->out_file)
   {
     stack->flags= stack->next->flags;
     stack->delay= stack->next->delay;
     stack->maxdepth= stack->next->maxdepth;
     stack->sub_level= stack->next->sub_level;
     strcpy(stack->name, stack->next->name);
     stack->prof_file= stack->next->prof_file;
     if (stack->next == &init_settings)
     {
       /*
         Never share with the global parent - it can change under your feet.
         Reset out_file to stderr to prevent sharing of trace files between
         global and session settings.
       */
       stack->out_file= stderr;
       stack->functions= ListCopy(init_settings.functions);
       stack->p_functions= ListCopy(init_settings.p_functions);
       stack->keywords= ListCopy(init_settings.keywords);
       stack->processes= ListCopy(init_settings.processes);
     }
     else
     {
       stack->out_file= stack->next->out_file;
       stack->functions= stack->next->functions;
       stack->p_functions= stack->next->p_functions;
       stack->keywords= stack->next->keywords;
       stack->processes= stack->next->processes;
     }
   }
   end= DbugStrTok(control);
   while (control < end)
   {
     int c, sign= (*control == '+') ? 1 : (*control == '-') ? -1 : 0;
     if (sign) control++;
     c= *control++;
     if (*control == ',') control++;
     /* XXX when adding new cases here, don't forget _db_explain_ ! */
     switch (c) {
     case 'd':
       if (sign < 0 && control == end)
       {
         if (!is_shared(stack, keywords))
           FreeList(stack->keywords);
         stack->keywords=NULL;
         stack->flags &= ~DEBUG_ON;
         break;
       }
       if (rel && is_shared(stack, keywords))
         stack->keywords= ListCopy(stack->keywords);
       if (sign < 0)
       {
         if (DEBUGGING)
           stack->keywords= ListDel(stack->keywords, control, end);
       break;
       }
       stack->keywords= ListAdd(stack->keywords, control, end);
       stack->flags |= DEBUG_ON;
       break;
     case 'D':
       stack->delay= atoi(control);
       break;
     case 'f':
       f_used= 1;
       if (sign < 0 && control == end)
       {
         if (!is_shared(stack,functions))
           FreeList(stack->functions);
         stack->functions=NULL;
         break;
       }
       if (rel && is_shared(stack,functions))
         stack->functions= ListCopy(stack->functions);
       if (sign < 0)
         stack->functions= ListDel(stack->functions, control, end);
       else
         stack->functions= ListAdd(stack->functions, control, end);
       break;
     case 'F':
       if (sign < 0)
         stack->flags &= ~FILE_ON;
       else
         stack->flags |= FILE_ON;
       break;
     case 'i':
       if (sign < 0)
         stack->flags &= ~PID_ON;
       else
         stack->flags |= PID_ON;
       break;
     case 'L':
       if (sign < 0)
         stack->flags &= ~LINE_ON;
       else
         stack->flags |= LINE_ON;
       break;
     case 'n':
       if (sign < 0)
         stack->flags &= ~DEPTH_ON;
       else
         stack->flags |= DEPTH_ON;
       break;
     case 'N':
       if (sign < 0)
         stack->flags &= ~NUMBER_ON;
       else
         stack->flags |= NUMBER_ON;
       break;
     case 'A':
     case 'O':
       stack->flags |= FLUSH_ON_WRITE;
       /* fall through */
     case 'a':
     case 'o':
       if (sign < 0)
       {
         if (!is_shared(stack, out_file))
           DBUGCloseFile(cs, stack->out_file);
         stack->flags &= ~FLUSH_ON_WRITE;
         stack->out_file= stderr;
         break;
       }
       if (c == 'a' || c == 'A')
         stack->flags |= OPEN_APPEND;
       else
         stack->flags &= ~OPEN_APPEND;
       if (control != end)
         DBUGOpenFile(cs, control, end, stack->flags & OPEN_APPEND);
       else
         DBUGOpenFile(cs, "-",0,0);
       break;
     case 'p':
       if (sign < 0 && control == end)
       {
         if (!is_shared(stack,processes))
           FreeList(stack->processes);
         stack->processes=NULL;
         break;
       }
       if (rel && is_shared(stack, processes))
         stack->processes= ListCopy(stack->processes);
       if (sign < 0)
         stack->processes= ListDel(stack->processes, control, end);
       else
         stack->processes= ListAdd(stack->processes, control, end);
       break;
     case 'P':
       if (sign < 0)
         stack->flags &= ~PROCESS_ON;
       else
         stack->flags |= PROCESS_ON;
       break;
     case 'r':
       stack->sub_level= cs->level;
       break;
     case 't':
       if (sign < 0)
       {
         if (control != end)
           stack->maxdepth-= atoi(control);
         else
           stack->maxdepth= 0;
       }
       else
       {
         if (control != end)
           stack->maxdepth+= atoi(control);
         else
           stack->maxdepth= MAXDEPTH;
       }
       if (stack->maxdepth > 0)
         stack->flags |= TRACE_ON;
       else
         stack->flags &= ~TRACE_ON;
       break;
     case 'T':
       if (sign < 0)
         stack->flags &= ~TIMESTAMP_ON;
       else
         stack->flags |= TIMESTAMP_ON;
       break;
     }
     if (!*end)
       break;
     control=end+1;
     end= DbugStrTok(control);
   }
   return !rel || f_used;
 }
References mpq::c, DBUGCloseFile(), DBUGOpenFile(), DbugStrTok(), DEBUG_ON, DEBUGGING, settings::delay, DEPTH_ON, FILE_ON, settings::flags, FLUSH_ON_WRITE, FreeList(), FreeState(), settings::functions, init_settings, is_shared, settings::keywords, _db_code_state_::level, LINE_ON, ListAdd, ListCopy(), ListDel, MAXDEPTH, settings::maxdepth, settings::name, settings::next, NULL, NUMBER_ON, OPEN_APPEND, settings::out_file, settings::p_functions, PID_ON, PROCESS_ON, settings::processes, settings::prof_file, _db_code_state_::stack, settings::sub_level, TIMESTAMP_ON, and TRACE_ON.
Referenced by _db_push_(), _db_set_(), and _db_set_init_().
DbugStrTok()
static const char * DbugStrTok (const char * s) static
Definition at line 2013 of file dbug.c.
 {
   while (s[0] && (s[0] != ':' ||
                   (s[1] == '\\' || s[1] == '/' || (s[1] == ':' && s++))))
     s++;
   return s;
 }
Referenced by DbugParse().
DbugVfprintf()
static void DbugVfprintf (FILE * stream, const char * format, va_list args) static
Definition at line 1285 of file dbug.c.
 {
   char cvtbuf[1024];
   (void) my_vsnprintf(cvtbuf, sizeof(cvtbuf), format, args);
   (void) fprintf(stream, "%s\n", cvtbuf);
 }
References format(), fprintf(), and my_vsnprintf().
Referenced by _db_doprnt_().
DoPrefix()
static void DoPrefix (CODE_STATE * cs, uint line) static
Definition at line 1806 of file dbug.c.
 {
   cs->lineno++;
   if (cs->stack->flags & PID_ON)
   {
     (void) fprintf(cs->stack->out_file, "%-7s: ", my_thread_name());
   }
   if (cs->stack->flags & NUMBER_ON)
     (void) fprintf(cs->stack->out_file, "%5d: ", cs->lineno);
   if (cs->stack->flags & TIMESTAMP_ON)
   {
 #ifdef __WIN__
     /* FIXME This doesn't give microseconds as in Unix case, and the resolution is
        in system ticks, 10 ms intervals. See my_getsystime.c for high res */
     SYSTEMTIME loc_t;
     GetLocalTime(&loc_t);
     (void) fprintf (cs->stack->out_file,
                     /* "%04d-%02d-%02d " */
                     "%02d:%02d:%02d.%06d ",
                     /*tm_p->tm_year + 1900, tm_p->tm_mon + 1, tm_p->tm_mday,*/
                     loc_t.wHour, loc_t.wMinute, loc_t.wSecond, loc_t.wMilliseconds);
 #else
     struct timeval tv;
     struct tm *tm_p;
     if (gettimeofday(&tv, NULL) != -1)
     {
       if ((tm_p= localtime((const time_t *)&tv.tv_sec)))
       {
         (void) fprintf (cs->stack->out_file,
                         /* "%04d-%02d-%02d " */
                         "%02d:%02d:%02d.%06d ",
                         /*tm_p->tm_year + 1900, tm_p->tm_mon + 1, tm_p->tm_mday,*/
                         tm_p->tm_hour, tm_p->tm_min, tm_p->tm_sec,
                         (int) (tv.tv_usec));
       }
     }
 #endif
   }
   if (cs->stack->flags & PROCESS_ON)
     (void) fprintf(cs->stack->out_file, "%s: ", cs->process);
   if (cs->stack->flags & FILE_ON)
     (void) fprintf(cs->stack->out_file, "%14s: ", BaseName(cs->file));
   if (cs->stack->flags & LINE_ON)
     (void) fprintf(cs->stack->out_file, "%5d: ", _line_);
   if (cs->stack->flags & DEPTH_ON)
     (void) fprintf(cs->stack->out_file, "%4d: ", cs->level);
 }
References BaseName(), DEPTH_ON, _db_code_state_::file, FILE_ON, settings::flags, fprintf(), _db_code_state_::level, LINE_ON, _db_code_state_::lineno, localtime(), my_thread_name(), NULL, NUMBER_ON, settings::out_file, PID_ON, _db_code_state_::process, PROCESS_ON, _db_code_state_::stack, and TIMESTAMP_ON.
Referenced by _db_doprnt_(), _db_dump_(), _db_enter_(), and _db_return_().
DoTrace()
static int DoTrace (CODE_STATE * cs) static
Definition at line 1667 of file dbug.c.
 {
   if ((cs->stack->maxdepth == 0 || cs->level <= cs->stack->maxdepth) &&
       InList(cs->stack->processes, cs->process) & (MATCHED|INCLUDE))
     switch(InList(cs->stack->functions, cs->func)) {
     case INCLUDE|SUBDIR:  return ENABLE_TRACE;
     case INCLUDE:         return DO_TRACE;
     case MATCHED|SUBDIR:
     case NOT_MATCHED|SUBDIR:
     case MATCHED:         return framep_trace_flag(cs, cs->framep) ?
                                            DO_TRACE : DONT_TRACE;
     case EXCLUDE:
     case NOT_MATCHED:     return DONT_TRACE;
     case EXCLUDE|SUBDIR:  return DISABLE_TRACE;
     }
   return DONT_TRACE;
 }
References DISABLE_TRACE, DO_TRACE, DONT_TRACE, ENABLE_TRACE, EXCLUDE, _db_code_state_::framep, framep_trace_flag, _db_code_state_::func, settings::functions, INCLUDE, InList(), _db_code_state_::level, MATCHED, settings::maxdepth, NOT_MATCHED, _db_code_state_::process, settings::processes, _db_code_state_::stack, and SUBDIR.
Referenced by _db_enter_(), _db_keyword_(), _db_return_(), and FixTraceFlags_helper().
FixTraceFlags()
void FixTraceFlags (uint old_fflags, CODE_STATE * cs)
Definition at line 701 of file dbug.c.
 {
   const char *func;
   uint new_fflags, traceon, level;
   struct _db_stack_frame_ *framep;
   /*
     first (a.k.a. safety) check:
     if we haven't started tracing yet, no call stack at all - we're safe.
   */
   framep=cs->framep;
   if (framep == 0)
     return;
   /*
     Ok, the tracing has started, call stack isn't empty.
     second check: does the new list have a SUBDIR rule ?
   */
   new_fflags=fflags(cs);
   if (new_fflags & SUBDIR)
     goto yuck;
   /*
     Ok, new list doesn't use SUBDIR.
     third check: we do NOT need to re-scan if
     neither old nor new lists used SUBDIR flag and if a default behavior
     (whether an unlisted function is traced) hasn't changed.
     Default behavior depends on whether there're INCLUDE elements in the list.
   */
   if (!(old_fflags & SUBDIR) && !((new_fflags^old_fflags) & INCLUDE))
     return;
   /*
     Ok, old list may've used SUBDIR, or defaults could've changed.
     fourth check: are we inside a currently active SUBDIR rule ?
     go up the call stack, if TRACE_ON flag ever changes its value - we are.
   */
   for (traceon=framep->level; framep; framep=framep->prev)
     if ((traceon ^ framep->level) & TRACE_ON)
       goto yuck;
   /*
     Ok, TRACE_ON flag doesn't change in the call stack.
     fifth check: but is the top-most value equal to a default one ?
   */
   if (((traceon & TRACE_ON) != 0) == ((new_fflags & INCLUDE) == 0))
     return;
 yuck:
   /*
     Yuck! function list was changed, and one of the currently active rules
     was possibly affected. For example, a tracing could've been enabled or
     disabled for a function somewhere up the call stack.
     To react correctly, we must go up the call stack all the way to
     the top and re-match rules to set TRACE_ON bit correctly.
     We must traverse the stack forwards, not backwards.
     That's what a recursive helper is doing.
     It'll destroy two CODE_STATE fields, save them now.
   */
   func= cs->func;
   level= cs->level;
   FixTraceFlags_helper(cs, func, cs->framep);
   /* now we only need to restore CODE_STATE fields, and we're done */
   cs->func= func;
   cs->level= level;
 }
References fflags, FixTraceFlags_helper(), _db_code_state_::framep, _db_code_state_::func, _db_stack_frame_::func, INCLUDE, _db_code_state_::level, _db_stack_frame_::level, _db_stack_frame_::prev, SUBDIR, and TRACE_ON.
Referenced by _db_pop_(), _db_push_(), and _db_set_().
FixTraceFlags_helper()
void FixTraceFlags_helper (CODE_STATE * cs, const char * func, struct _db_stack_frame_ * framep)
Definition at line 675 of file dbug.c.
 {
   if (framep->prev)
     FixTraceFlags_helper(cs, framep->func, framep->prev);
   cs->func= func;
   cs->level= framep->level & ~TRACE_ON;
   framep->level= cs->level | framep_trace_flag(cs, framep->prev);
   /*
     we don't set cs->framep correctly, even though DoTrace uses it.
     It's ok, because cs->framep may only affect DO_TRACE/DONT_TRACE return
     values, but we ignore them here anyway
   */
   switch(DoTrace(cs)) {
   case ENABLE_TRACE:
     framep->level|= TRACE_ON;
     break;
   case DISABLE_TRACE:
     framep->level&= ~TRACE_ON;
     break;
   }
 }
References DISABLE_TRACE, DoTrace(), ENABLE_TRACE, framep_trace_flag, _db_code_state_::func, _db_stack_frame_::func, _db_code_state_::level, _db_stack_frame_::level, _db_stack_frame_::prev, and TRACE_ON.
Referenced by FixTraceFlags().
FreeList()
static void FreeList (struct link * linkp) static
Definition at line 1774 of file dbug.c.
 {
   REGISTER struct link *old;
   while (linkp != NULL)
   {
     old= linkp;
     linkp= linkp->next_link;
     free((void*) old);
   }
 }
References link::next_link, NULL, and REGISTER.
Referenced by DbugParse(), and FreeState().
FreeState()
static void FreeState (CODE_STATE * cs, struct settings * state, int free_state) static
Definition at line 1573 of file dbug.c.
 {
   if (!is_shared(state, keywords))
     FreeList(state->keywords);
   if (!is_shared(state, functions))
     FreeList(state->functions);
   if (!is_shared(state, processes))
     FreeList(state->processes);
   if (!is_shared(state, p_functions))
     FreeList(state->p_functions);
   if (!is_shared(state, out_file))
     DBUGCloseFile(cs, state->out_file);
   else
     (void) fflush(state->out_file);
   if (!is_shared(state, prof_file))
     DBUGCloseFile(cs, state->prof_file);
   else
     (void) fflush(state->prof_file);
   if (free_state)
     free((void*) state);
 }
References DBUGCloseFile(), FreeList(), settings::functions, is_shared, settings::keywords, settings::out_file, settings::p_functions, settings::processes, and settings::prof_file.
Referenced by _db_end_(), _db_pop_(), and DbugParse().
Indent()
static void Indent (CODE_STATE * cs, int indent) static
Definition at line 1742 of file dbug.c.
 {
   REGISTER int count;
   indent= max(indent-1-cs->stack->sub_level,0)*INDENT;
   for (count= 0; count < indent ; count++)
   {
     if ((count % INDENT) == 0)
       fputc('|',cs->stack->out_file);
     else
       fputc(' ',cs->stack->out_file);
   }
 }
References count(), INDENT, max, settings::out_file, REGISTER, _db_code_state_::stack, and settings::sub_level.
Referenced by _db_doprnt_(), _db_dump_(), _db_enter_(), and _db_return_().
InList()
static int InList (struct link * linkp, const char * cp) static
Definition at line 1495 of file dbug.c.
 {
   int result;
   for (result=MATCHED; linkp != NULL; linkp= linkp->next_link)
   {
     if (!fnmatch(linkp->str, cp, 0))
       return linkp->flags;
     if (!(linkp->flags & EXCLUDE))
       result=NOT_MATCHED;
     if (linkp->flags & SUBDIR)
       result|=SUBDIR;
   }
   return result;
 }
References EXCLUDE, link::flags, fnmatch, MATCHED, link::next_link, NOT_MATCHED, NULL, link::str, and SUBDIR.
Referenced by _db_keyword_(), and DoTrace().
ListAddDel()
static struct link * ListAddDel (struct link * head, const char * ctlp, const char * end, int todo) static
Definition at line 1378 of file dbug.c.
 {
   const char *start;
   struct link **cur;
   size_t len;
   int subdir;
   ctlp--;
 next:
   while (++ctlp < end)
   {
     start= ctlp;
     subdir=0;
     while (ctlp < end && *ctlp != ',')
       ctlp++;
     len=ctlp-start;
     if (start[len-1] == '/')
     {
       len--;
       subdir=SUBDIR;
     }
     if (len == 0) continue;
     for (cur=&head; *cur; cur=&((*cur)->next_link))
     {
       if (!strncmp((*cur)->str, start, len))
       {
         if ((*cur)->flags & todo)  /* same action ? */
           (*cur)->flags|= subdir;  /* just merge the SUBDIR flag */
         else if (todo == EXCLUDE)
         {
           struct link *delme=*cur;
           *cur=(*cur)->next_link;
           free((void*) delme);
         }
         else
         {
           (*cur)->flags&=~(EXCLUDE & SUBDIR);
           (*cur)->flags|=INCLUDE | subdir;
         }
         goto next;
       }
     }
     *cur= (struct link *) DbugMalloc(sizeof(struct link)+len);
     memcpy((*cur)->str, start, len);
     (*cur)->str[len]=0;
     (*cur)->flags=todo | subdir;
     (*cur)->next_link=0;
   }
   return head;
 }
References DbugMalloc(), EXCLUDE, INCLUDE, memcpy, next(), link::next_link, and SUBDIR.
ListCopy()
static struct link * ListCopy (struct link * orig) static
Definition at line 1453 of file dbug.c.
 {
   struct link *new_malloc;
   struct link *head;
   size_t len;
   head= NULL;
   while (orig != NULL)
   {
     len= strlen(orig->str);
     new_malloc= (struct link *) DbugMalloc(sizeof(struct link)+len);
     memcpy(new_malloc->str, orig->str, len);
     new_malloc->str[len]= 0;
     new_malloc->flags=orig->flags;
     new_malloc->next_link= head;
     head= new_malloc;
     orig= orig->next_link;
   }
   return head;
 }
References DbugMalloc(), link::flags, memcpy, link::next_link, NULL, and link::str.
Referenced by DbugParse().
ListFlags()
static uint ListFlags (struct link * linkp) static
Definition at line 1518 of file dbug.c.
 {
   uint f;
   for (f=0; linkp != NULL; linkp= linkp->next_link)
     f|= linkp->flags;
   return f;
 }
References f(), link::flags, link::next_link, and NULL.
perror() [1/2]
static void perror () static
Referenced by MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildNavMesh(), DBUGCloseFile(), DBUGOpenFile(), file_compress(), file_uncompress(), MMAP::IntermediateValues::generateObjFile(), gz_compress(), and main().
perror() [2/2]
static void perror (char * s) static
Definition at line 2190 of file dbug.c.
 {
   if (s && *s != '\0')
     (void) fprintf(stderr, "%s: ", s);
   (void) fprintf(stderr, "<unknown system error>\n");
 }
References fprintf().
PushState()
static void PushState (CODE_STATE * cs) static
Definition at line 1546 of file dbug.c.
 {
   struct settings *new_malloc;
   new_malloc= (struct settings *) DbugMalloc(sizeof(struct settings));
   bzero(new_malloc, sizeof(struct settings));
   new_malloc->next= cs->stack;
   cs->stack= new_malloc;
 }
References bzero, DbugMalloc(), settings::next, and _db_code_state_::stack.
Referenced by _db_push_(), and _db_set_().
Variable Documentation
_dbug_on_
my_bool _dbug_on_ = TRUE
Definition at line 241 of file dbug.c.
Referenced by _db_end_(), and code_state().
db_process
const char* db_process = 0 static
Definition at line 240 of file dbug.c.
Referenced by _db_process_(), _db_set_init_(), and code_state().
init_done
BOOLEAN init_done = FALSE static
Definition at line 238 of file dbug.c.
Referenced by code_state().
init_settings
struct settings init_settings static
Definition at line 238 of file dbug.c.
Referenced by _db_end_(), _db_explain_init_(), _db_is_pushed_(), _db_pop_(), _db_set_(), _db_set_init_(), code_state(), and DbugParse().
THR_LOCK_dbug
pthread_mutex_t THR_LOCK_dbug static
Definition at line 350 of file dbug.c.
Referenced by _db_doprnt_(), _db_dump_(), _db_end_(), _db_enter_(), _db_lock_file_(), _db_return_(), _db_unlock_file_(), code_state(), DBUGCloseFile(), and DbugFlush().