Azerotcore-wotlk: GmTicket Class Reference
GmTicket Class Reference
#include <TicketMgr.h>
Public Member Functions
GmTicket ()
GmTicket (Player *player)
~GmTicket ()
bool IsClosed () const
bool IsCompleted () const
bool IsFromPlayer (ObjectGuid guid) const
bool IsAssigned () const
bool IsAssignedTo (ObjectGuid guid) const
bool IsAssignedNotTo (ObjectGuid guid) const
uint32 GetId () const
Player * GetPlayer () const
std::string const & GetPlayerName () const
std::string const & GetMessage () const
Player * GetAssignedPlayer () const
ObjectGuid GetAssignedToGUID () const
std::string GetAssignedToName () const
uint64 GetLastModifiedTime () const
GMTicketEscalationStatus GetEscalatedStatus () const
void SetEscalatedStatus (GMTicketEscalationStatus escalatedStatus)
void SetAssignedTo (ObjectGuid guid, bool isAdmin)
void SetClosedBy (ObjectGuid value)
void SetResolvedBy (ObjectGuid value)
void SetCompleted ()
void SetMessage (std::string const &message)
void SetComment (std::string const &comment)
void SetViewed ()
void SetUnassigned ()
void SetPosition (uint32 mapId, float x, float y, float z)
void SetGmAction (uint32 needResponse, bool needMoreHelp)
void AppendResponse (std::string const &response)
bool LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
void DeleteFromDB ()
void WritePacket (WorldPacket &data) const
void SendResponse (WorldSession *session) const
void TeleportTo (Player *player) const
std::string FormatMessageString (ChatHandler &handler, bool detailed=false) const
std::string FormatMessageString (ChatHandler &handler, const char *szClosedName, const char *szAssignedToName, const char *szUnassignedName, const char *szDeletedName) const
void SetChatLog (std::list< uint32 > time, std::string const &log)
std::string const & GetChatLog () const
Private Attributes
uint32 _id
ObjectGuid _playerGuid
TicketType _type
std::string _playerName
float _posX
float _posY
float _posZ
uint16 _mapId
std::string _message
uint64 _createTime
uint64 _lastModifiedTime
ObjectGuid _closedBy
ObjectGuid _resolvedBy
ObjectGuid _assignedTo
std::string _comment
bool _completed
GMTicketEscalationStatus _escalatedStatus
bool _viewed
bool _needResponse
bool _needMoreHelp
std::string _response
std::string _chatLog
Detailed Description
Definition at line 86 of file TicketMgr.h.
Constructor & Destructor Documentation
GmTicket() [1/2]
GmTicket::GmTicket ()
Definition at line 34 of file TicketMgr.cpp.
                    : _id(0), _type(TICKET_TYPE_OPEN), _posX(0), _posY(0), _posZ(0), _mapId(0), _createTime(0), _lastModifiedTime(0),
     _completed(false), _escalatedStatus(TICKET_UNASSIGNED), _viewed(false), _needResponse(false), _needMoreHelp(false) { }
GmTicket() [2/2]
GmTicket::GmTicket (Player * player)
Definition at line 37 of file TicketMgr.cpp.
                                  : _type(TICKET_TYPE_OPEN), _createTime(time(nullptr)), _lastModifiedTime(time(nullptr)),
     _completed(false), _escalatedStatus(TICKET_UNASSIGNED), _viewed(false), _needMoreHelp(false)
 {
     _id = sTicketMgr->GenerateTicketId();
     _playerName = player->GetName();
     _playerGuid = player->GetGUID();
 }
References _id, _playerGuid, _playerName, Object::GetGUID(), WorldObject::GetName(), and sTicketMgr.
~GmTicket()
GmTicket::~GmTicket ()
Definition at line 45 of file TicketMgr.cpp.
 { }
Member Function Documentation
AppendResponse()
void GmTicket::AppendResponse (std::string const & response) inline
Definition at line 141 of file TicketMgr.h.
 { _response += response; }
References _response.
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), and ticket_commandscript::HandleGMTicketCompleteCommand().
DeleteFromDB()
void GmTicket::DeleteFromDB ()
Definition at line 106 of file TicketMgr.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GM_TICKET);
     stmt->setUInt32(0, _id);
     CharacterDatabase.Execute(stmt);
 }
References _id, CHAR_DEL_GM_TICKET, CharacterDatabase, and PreparedStatementBase::setUInt32().
FormatMessageString() [1/2]
std::string GmTicket::FormatMessageString (ChatHandler & handler, bool detailed = false) const
Definition at line 159 of file TicketMgr.cpp.
 {
     time_t curTime = time(nullptr);
     std::stringstream ss;
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTGUID, _id);
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTNAME, _playerName.c_str());
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTAGECREATE, (secsToTimeString(curTime - _createTime, true)).c_str());
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTAGE, (secsToTimeString(curTime - _lastModifiedTime, true)).c_str());
     std::string name;
     if (sObjectMgr->GetPlayerNameByGUID(_assignedTo.GetCounter(), name))
         ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTASSIGNEDTO, name.c_str());
     if (detailed)
     {
         ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTMESSAGE, _message.c_str());
         if (!_comment.empty())
             ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTCOMMENT, _comment.c_str());
         if (!_response.empty())
             ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTRESPONSE, _response.c_str());
     }
     return ss.str();
 }
References _assignedTo, _comment, _createTime, _id, _lastModifiedTime, _message, _playerName, _response, ObjectGuid::GetCounter(), LANG_COMMAND_TICKETLISTAGE, LANG_COMMAND_TICKETLISTAGECREATE, LANG_COMMAND_TICKETLISTASSIGNEDTO, LANG_COMMAND_TICKETLISTCOMMENT, LANG_COMMAND_TICKETLISTGUID, LANG_COMMAND_TICKETLISTMESSAGE, LANG_COMMAND_TICKETLISTNAME, LANG_COMMAND_TICKETLISTRESPONSE, name, ChatHandler::PGetParseString(), secsToTimeString(), and sObjectMgr.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), and ticket_commandscript::HandleGMTicketUnAssignCommand().
FormatMessageString() [2/2]
std::string GmTicket::FormatMessageString (ChatHandler & handler, const char * szClosedName, const char * szAssignedToName, const char * szUnassignedName, const char * szDeletedName) const
Definition at line 184 of file TicketMgr.cpp.
 {
     std::stringstream ss;
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTGUID, _id);
     ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTNAME, _playerName.c_str());
     if (szClosedName)
         ss << handler.PGetParseString(LANG_COMMAND_TICKETCLOSED, szClosedName);
     if (szAssignedToName)
         ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTASSIGNEDTO, szAssignedToName);
     if (szUnassignedName)
         ss << handler.PGetParseString(LANG_COMMAND_TICKETLISTUNASSIGNED, szUnassignedName);
     if (szDeletedName)
         ss << handler.PGetParseString(LANG_COMMAND_TICKETDELETED, szDeletedName);
     return ss.str();
 }
References _id, _playerName, LANG_COMMAND_TICKETCLOSED, LANG_COMMAND_TICKETDELETED, LANG_COMMAND_TICKETLISTASSIGNEDTO, LANG_COMMAND_TICKETLISTGUID, LANG_COMMAND_TICKETLISTNAME, LANG_COMMAND_TICKETLISTUNASSIGNED, and ChatHandler::PGetParseString().
GetAssignedPlayer()
Player* GmTicket::GetAssignedPlayer () const inline
Definition at line 104 of file TicketMgr.h.
 { return ObjectAccessor::FindConnectedPlayer(_assignedTo); }
References _assignedTo, and ObjectAccessor::FindConnectedPlayer().
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
GetAssignedToGUID()
ObjectGuid GmTicket::GetAssignedToGUID () const inline
Definition at line 105 of file TicketMgr.h.
 { return _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
GetAssignedToName()
std::string GmTicket::GetAssignedToName () const inline
Definition at line 106 of file TicketMgr.h.
     {
         std::string name;
         // save queries if ticket is not assigned
         if (_assignedTo)
             sObjectMgr->GetPlayerNameByGUID(_assignedTo.GetCounter(), name);
         return name;
     }
References _assignedTo, ObjectGuid::GetCounter(), name, and sObjectMgr.
Referenced by ticket_commandscript::HandleGMTicketCommentCommand(), and ticket_commandscript::HandleGMTicketUnAssignCommand().
GetChatLog()
std::string const& GmTicket::GetChatLog () const inline
Definition at line 155 of file TicketMgr.h.
 { return _chatLog; }
References _chatLog.
GetEscalatedStatus()
GMTicketEscalationStatus GmTicket::GetEscalatedStatus () const inline
Definition at line 116 of file TicketMgr.h.
 { return _escalatedStatus; }
References _escalatedStatus.
Referenced by ticket_commandscript::HandleGMTicketEscalateCommand().
GetId()
uint32 GmTicket::GetId () const inline
Definition at line 100 of file TicketMgr.h.
 { return _id; }
References _id.
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), TicketMgr::AddTicket(), Player::DeleteFromDB(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), and TicketMgr::LoadTickets().
GetLastModifiedTime()
uint64 GmTicket::GetLastModifiedTime () const inline
Definition at line 115 of file TicketMgr.h.
 { return _lastModifiedTime; }
References _lastModifiedTime.
GetMessage()
std::string const& GmTicket::GetMessage () const inline
Definition at line 103 of file TicketMgr.h.
 { return _message; }
References _message.
GetPlayer()
Player* GmTicket::GetPlayer () const inline
Definition at line 101 of file TicketMgr.h.
 { return ObjectAccessor::FindConnectedPlayer(_playerGuid); }
References _playerGuid, and ObjectAccessor::FindConnectedPlayer().
Referenced by ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), and ticket_commandscript::HandleGMTicketEscalateCommand().
GetPlayerName()
std::string const& GmTicket::GetPlayerName () const inline
Definition at line 102 of file TicketMgr.h.
 { return _playerName; }
References _playerName.
IsAssigned()
bool GmTicket::IsAssigned () const inline
Definition at line 96 of file TicketMgr.h.
 { return _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand(), and IsAssignedNotTo().
IsAssignedNotTo()
bool GmTicket::IsAssignedNotTo (ObjectGuid guid) const inline
Definition at line 98 of file TicketMgr.h.
 { return IsAssigned() && !IsAssignedTo(guid); }
References IsAssigned(), and IsAssignedTo().
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), and ticket_commandscript::HandleGMTicketCompleteCommand().
IsAssignedTo()
bool GmTicket::IsAssignedTo (ObjectGuid guid) const inline
Definition at line 97 of file TicketMgr.h.
 { return guid == _assignedTo; }
References _assignedTo.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), and IsAssignedNotTo().
IsClosed()
bool GmTicket::IsClosed () const inline
Definition at line 93 of file TicketMgr.h.
 { return  _type != TICKET_TYPE_OPEN; }
References _type, and TICKET_TYPE_OPEN.
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), TicketMgr::AddTicket(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketEscalateCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), and TicketMgr::LoadTickets().
IsCompleted()
bool GmTicket::IsCompleted () const inline
Definition at line 94 of file TicketMgr.h.
 { return _completed; }
References _completed.
Referenced by ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGMTicketCreateOpcode(), ticket_commandscript::HandleGMTicketEscalateCommand(), and ticket_commandscript::HandleGMTicketGetByIdCommand().
IsFromPlayer()
bool GmTicket::IsFromPlayer (ObjectGuid guid) const inline
Definition at line 95 of file TicketMgr.h.
 { return guid == _playerGuid; }
References _playerGuid.
LoadFromDB()
bool GmTicket::LoadFromDB (Field * fields)
Definition at line 47 of file TicketMgr.cpp.
 {
     //  0    1        2       3       4          5        6      7     8     9          10            11         12         13       14        15         16        17        18         19
     // id, type, playerGuid, name, message, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, haveTicket, resolvedBy
     uint8 index = 0;
     _id                 = fields[  index].GetUInt32();
     _type               = TicketType(fields[++index].GetUInt8());
     _playerGuid         = ObjectGuid::Create<HighGuid::Player>(fields[++index].GetUInt32());
     _playerName         = fields[++index].GetString();
     _message            = fields[++index].GetString();
     _createTime         = fields[++index].GetUInt32();
     _mapId              = fields[++index].GetUInt16();
     _posX               = fields[++index].GetFloat();
     _posY               = fields[++index].GetFloat();
     _posZ               = fields[++index].GetFloat();
     _lastModifiedTime   = fields[++index].GetUInt32();
     _closedBy           = ObjectGuid::Create<HighGuid::Player>(fields[++index].GetInt32());
     _assignedTo         = ObjectGuid::Create<HighGuid::Player>(fields[++index].GetUInt32());
     _comment            = fields[++index].GetString();
     _response           = fields[++index].GetString();
     _completed          = fields[++index].GetBool();
     _escalatedStatus    = GMTicketEscalationStatus(fields[++index].GetUInt8());
     _viewed             = fields[++index].GetBool();
     _needMoreHelp       = fields[++index].GetBool();
     _resolvedBy         = ObjectGuid::Create<HighGuid::Player>(fields[++index].GetInt32());
     return true;
 }
References _assignedTo, _closedBy, _comment, _completed, _createTime, _escalatedStatus, _id, _lastModifiedTime, _mapId, _message, _needMoreHelp, _playerGuid, _playerName, _posX, _posY, _posZ, _resolvedBy, _response, _type, _viewed, Field::GetBool(), Field::GetFloat(), Field::GetString(), Field::GetUInt16(), Field::GetUInt32(), and index.
Referenced by TicketMgr::LoadTickets().
SaveToDB()
void GmTicket::SaveToDB (CharacterDatabaseTransaction trans) const
Definition at line 76 of file TicketMgr.cpp.
 {
     //  0    1       2         3          4          5        6     7     8     9           10           11          12        13        14        15         16        17         18          19
     // id, type, playerGuid, name, description, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, needMoreHelp, resolvedBy
     uint8 index = 0;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_GM_TICKET);
     stmt->setUInt32(  index, _id);
     stmt->setUInt8 (++index, uint8(_type));
     stmt->setUInt32(++index, _playerGuid.GetCounter());
     stmt->setString(++index, _playerName);
     stmt->setString(++index, _message);
     stmt->setUInt32(++index, uint32(_createTime));
     stmt->setUInt16(++index, _mapId);
     stmt->setFloat (++index, _posX);
     stmt->setFloat (++index, _posY);
     stmt->setFloat (++index, _posZ);
     stmt->setUInt32(++index, uint32(_lastModifiedTime));
     stmt->setInt32 (++index, int32(_closedBy.GetCounter()));
     stmt->setUInt32(++index, _assignedTo.GetCounter());
     stmt->setString(++index, _comment);
     stmt->setString(++index, _response);
     stmt->setBool  (++index, _completed);
     stmt->setUInt8 (++index, uint8(_escalatedStatus));
     stmt->setBool  (++index, _viewed);
     stmt->setBool  (++index, _needMoreHelp);
     stmt->setInt32 (++index, int32(_resolvedBy.GetCounter()));
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References _assignedTo, _closedBy, _comment, _completed, _createTime, _escalatedStatus, _id, _lastModifiedTime, _mapId, _message, _needMoreHelp, _playerGuid, _playerName, _posX, _posY, _posZ, _resolvedBy, _response, _type, _viewed, CHAR_REP_GM_TICKET, CharacterDatabase, ObjectGuid::GetCounter(), index, PreparedStatementBase::setBool(), PreparedStatementBase::setFloat(), PreparedStatementBase::setInt32(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), TicketMgr::AddTicket(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), and ticket_commandscript::HandleGMTicketUnAssignCommand().
SendResponse()
void GmTicket::SendResponse (WorldSession * session) const
Definition at line 132 of file TicketMgr.cpp.
 {
     WorldPacket data(SMSG_GMRESPONSE_RECEIVED);
     data << uint32(1);          // responseID
     data << uint32(_id);        // ticketID
     data << _message.c_str();
     size_t len = _response.size();
     char const* s = _response.c_str();
     for (int i = 0; i < 4; i++)
     {
         if (len)
         {
             size_t writeLen = std::min<size_t>(len, 3999);
             data.append(s, writeLen);
             len -= writeLen;
             s += writeLen;
         }
         data << uint8(0);
     }
     session->SendPacket(&data);
 }
References _id, _message, _response, WorldSession::SendPacket(), and SMSG_GMRESPONSE_RECEIVED.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetAssignedTo()
void GmTicket::SetAssignedTo (ObjectGuid guid, bool isAdmin) inline
Definition at line 119 of file TicketMgr.h.
     {
         _assignedTo = guid;
         if (isAdmin && _escalatedStatus == TICKET_IN_ESCALATION_QUEUE)
             _escalatedStatus = TICKET_ESCALATED_ASSIGNED;
         else if (_escalatedStatus == TICKET_UNASSIGNED)
             _escalatedStatus = TICKET_ASSIGNED;
     }
References _assignedTo, _escalatedStatus, TICKET_ASSIGNED, TICKET_ESCALATED_ASSIGNED, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand().
SetChatLog()
void GmTicket::SetChatLog (std::list< uint32 > time, std::string const & log)
Definition at line 238 of file TicketMgr.cpp.
 {
     std::stringstream ss(log);
     std::stringstream newss;
     std::string line;
     while (std::getline(ss, line) && !time.empty())
     {
         newss << secsToTimeString(time.front()) << ": " << line << "\n";
         time.pop_front();
     }
     _chatLog = newss.str();
 }
References _chatLog, G3D::log(), and secsToTimeString().
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetClosedBy()
void GmTicket::SetClosedBy (ObjectGuid value) inline
Definition at line 127 of file TicketMgr.h.
 { _closedBy = value; _type = TICKET_TYPE_CLOSED; }
References _closedBy, _type, and TICKET_TYPE_CLOSED.
SetComment()
void GmTicket::SetComment (std::string const & comment) inline
Definition at line 135 of file TicketMgr.h.
 { _comment = comment; }
References _comment.
Referenced by ticket_commandscript::HandleGMTicketCommentCommand().
SetCompleted()
void GmTicket::SetCompleted () inline
Definition at line 129 of file TicketMgr.h.
 { _completed = true; }
References _completed.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetEscalatedStatus()
void GmTicket::SetEscalatedStatus (GMTicketEscalationStatus escalatedStatus) inline
Definition at line 118 of file TicketMgr.h.
 { _escalatedStatus = escalatedStatus; }
References _escalatedStatus.
Referenced by ticket_commandscript::HandleGMTicketEscalateCommand().
SetGmAction()
void GmTicket::SetGmAction (uint32 needResponse, bool needMoreHelp)
Definition at line 227 of file TicketMgr.cpp.
 {
     _needResponse = (needResponse == 17);   // Requires GM response. 17 = true, 1 = false (17 is default)
     _needMoreHelp = needMoreHelp;           // Requests further GM interaction on a ticket to which a GM has already responded. Basically means "has a new ticket"
 }
References _needMoreHelp, and _needResponse.
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetMessage()
void GmTicket::SetMessage (std::string const & message) inline
Definition at line 130 of file TicketMgr.h.
     {
         _message = message;
         _lastModifiedTime = uint64(time(nullptr));
     }
References _lastModifiedTime, _message, and message().
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetPosition()
void GmTicket::SetPosition (uint32 mapId, float x, float y, float z)
Definition at line 219 of file TicketMgr.cpp.
 {
     _mapId = mapId;
     _posX = x;
     _posY = y;
     _posZ = z;
 }
References _mapId, _posX, _posY, _posZ, G3D::x, G3D::y, and G3D::z.
Referenced by WorldSession::HandleGMTicketCreateOpcode().
SetResolvedBy()
void GmTicket::SetResolvedBy (ObjectGuid value) inline
Definition at line 128 of file TicketMgr.h.
 { _resolvedBy = value; }
References _resolvedBy.
Referenced by ticket_commandscript::HandleGMTicketCompleteCommand().
SetUnassigned()
void GmTicket::SetUnassigned ()
Definition at line 200 of file TicketMgr.cpp.
 {
     _assignedTo.Clear();
     switch (_escalatedStatus)
     {
         case TICKET_ASSIGNED:
             _escalatedStatus = TICKET_UNASSIGNED;
             break;
         case TICKET_ESCALATED_ASSIGNED:
             _escalatedStatus = TICKET_IN_ESCALATION_QUEUE;
             break;
         case TICKET_UNASSIGNED:
         case TICKET_IN_ESCALATION_QUEUE:
         default:
             break;
     }
 }
References _assignedTo, _escalatedStatus, ObjectGuid::Clear(), TICKET_ASSIGNED, TICKET_ESCALATED_ASSIGNED, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
Referenced by ticket_commandscript::HandleGMTicketUnAssignCommand().
SetViewed()
void GmTicket::SetViewed () inline
Definition at line 136 of file TicketMgr.h.
 { _viewed = true; }
References _viewed.
Referenced by ticket_commandscript::HandleGMTicketGetByIdCommand(), and ticket_commandscript::HandleGMTicketGetByNameCommand().
TeleportTo()
void GmTicket::TeleportTo (Player * player) const
Definition at line 233 of file TicketMgr.cpp.
 {
     player->TeleportTo(_mapId, _posX, _posY, _posZ, 0.0f, 0);
 }
References _mapId, _posX, _posY, _posZ, and Player::TeleportTo().
Referenced by go_commandscript::HandleGoTicketCommand().
WritePacket()
void GmTicket::WritePacket (WorldPacket & data) const
Definition at line 113 of file TicketMgr.cpp.
 {
     data << uint32(GMTICKET_STATUS_HASTEXT);
     data << uint32(_id);
     data << _message;
     data << uint8(_needMoreHelp);
     data << GetAge(_lastModifiedTime);
     if (GmTicket* ticket = sTicketMgr->GetOldestOpenTicket())
         data << GetAge(ticket->GetLastModifiedTime());
     else
         data << float(0);
     // I am not sure how blizzlike this is, and we don't really have a way to find out
     data << GetAge(sTicketMgr->GetLastChange());
     data << uint8(std::min(_escalatedStatus, TICKET_IN_ESCALATION_QUEUE));                              // escalated data
     data << uint8(_viewed ? GMTICKET_OPENEDBYGM_STATUS_OPENED : GMTICKET_OPENEDBYGM_STATUS_NOT_OPENED); // whether or not it has been viewed
 }
References _escalatedStatus, _id, _lastModifiedTime, _message, _needMoreHelp, _viewed, GetAge(), GMTICKET_OPENEDBYGM_STATUS_NOT_OPENED, GMTICKET_OPENEDBYGM_STATUS_OPENED, GMTICKET_STATUS_HASTEXT, min, sTicketMgr, and TICKET_IN_ESCALATION_QUEUE.
Referenced by TicketMgr::SendTicket().
Member Data Documentation
_assignedTo
ObjectGuid GmTicket::_assignedTo private
Definition at line 171 of file TicketMgr.h.
Referenced by FormatMessageString(), GetAssignedPlayer(), GetAssignedToGUID(), GetAssignedToName(), IsAssigned(), IsAssignedTo(), LoadFromDB(), SaveToDB(), SetAssignedTo(), and SetUnassigned().
_chatLog
std::string GmTicket::_chatLog private
Definition at line 179 of file TicketMgr.h.
Referenced by GetChatLog(), and SetChatLog().
_closedBy
ObjectGuid GmTicket::_closedBy private
Definition at line 169 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), and SetClosedBy().
_comment
std::string GmTicket::_comment private
Definition at line 172 of file TicketMgr.h.
Referenced by FormatMessageString(), LoadFromDB(), SaveToDB(), and SetComment().
_completed
bool GmTicket::_completed private
Definition at line 173 of file TicketMgr.h.
Referenced by IsCompleted(), LoadFromDB(), SaveToDB(), and SetCompleted().
_createTime
uint64 GmTicket::_createTime private
Definition at line 167 of file TicketMgr.h.
Referenced by FormatMessageString(), LoadFromDB(), and SaveToDB().
_escalatedStatus
GMTicketEscalationStatus GmTicket::_escalatedStatus private
Definition at line 174 of file TicketMgr.h.
Referenced by GetEscalatedStatus(), LoadFromDB(), SaveToDB(), SetAssignedTo(), SetEscalatedStatus(), SetUnassigned(), and WritePacket().
_id
uint32 GmTicket::_id private
Definition at line 158 of file TicketMgr.h.
Referenced by DeleteFromDB(), FormatMessageString(), GetId(), GmTicket(), LoadFromDB(), SaveToDB(), SendResponse(), and WritePacket().
_lastModifiedTime
uint64 GmTicket::_lastModifiedTime private
Definition at line 168 of file TicketMgr.h.
Referenced by FormatMessageString(), GetLastModifiedTime(), LoadFromDB(), SaveToDB(), SetMessage(), and WritePacket().
_mapId
uint16 GmTicket::_mapId private
Definition at line 165 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_message
std::string GmTicket::_message private
Definition at line 166 of file TicketMgr.h.
Referenced by FormatMessageString(), GetMessage(), LoadFromDB(), SaveToDB(), SendResponse(), SetMessage(), and WritePacket().
_needMoreHelp
bool GmTicket::_needMoreHelp private
Definition at line 177 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetGmAction(), and WritePacket().
_needResponse
bool GmTicket::_needResponse private
Definition at line 176 of file TicketMgr.h.
Referenced by SetGmAction().
_playerGuid
ObjectGuid GmTicket::_playerGuid private
Definition at line 159 of file TicketMgr.h.
Referenced by GetPlayer(), GmTicket(), IsFromPlayer(), LoadFromDB(), and SaveToDB().
_playerName
std::string GmTicket::_playerName private
Definition at line 161 of file TicketMgr.h.
Referenced by FormatMessageString(), GetPlayerName(), GmTicket(), LoadFromDB(), and SaveToDB().
_posX
float GmTicket::_posX private
Definition at line 162 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_posY
float GmTicket::_posY private
Definition at line 163 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_posZ
float GmTicket::_posZ private
Definition at line 164 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetPosition(), and TeleportTo().
_resolvedBy
ObjectGuid GmTicket::_resolvedBy private
Definition at line 170 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), and SetResolvedBy().
_response
std::string GmTicket::_response private
Definition at line 178 of file TicketMgr.h.
Referenced by AppendResponse(), FormatMessageString(), LoadFromDB(), SaveToDB(), and SendResponse().
_type
TicketType GmTicket::_type private
Definition at line 160 of file TicketMgr.h.
Referenced by IsClosed(), LoadFromDB(), SaveToDB(), and SetClosedBy().
_viewed
bool GmTicket::_viewed private
Definition at line 175 of file TicketMgr.h.
Referenced by LoadFromDB(), SaveToDB(), SetViewed(), and WritePacket().
The documentation for this class was generated from the following files:
src/server/game/Tickets/TicketMgr.h
src/server/game/Tickets/TicketMgr.cpp