Azerotcore-wotlk: Acore::AnyAoETargetUnitInObjectRangeCheck Class Reference
Acore::AnyAoETargetUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyAoETargetUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
bool i_targetForPlayer
WorldObject const * i_obj
Unit const * i_funit
SpellInfo const * _spellInfo
float i_range
Detailed Description
Definition at line 968 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyAoETargetUnitInObjectRangeCheck()
Acore::AnyAoETargetUnitInObjectRangeCheck::AnyAoETargetUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
Definition at line 971 of file GridNotifiers.h.
             : i_obj(obj), i_funit(funit), _spellInfo(nullptr), i_range(range)
         {
             Unit const* check = i_funit;
             Unit const* owner = i_funit->GetOwner();
             if (owner)
                 check = owner;
             i_targetForPlayer = (check->GetTypeId() == TYPEID_PLAYER);
             if (i_obj->GetTypeId() == TYPEID_DYNAMICOBJECT)
                 _spellInfo = sSpellMgr->GetSpellInfo(((DynamicObject*)i_obj)->GetSpellId());
         }
References _spellInfo, Unit::GetOwner(), Object::GetTypeId(), i_funit, i_obj, i_targetForPlayer, sSpellMgr, TYPEID_DYNAMICOBJECT, and TYPEID_PLAYER.
Member Function Documentation
operator()()
bool Acore::AnyAoETargetUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 982 of file GridNotifiers.h.
         {
             // Check contains checks for: live, non-selectable, non-attackable flags, flight check and GM check, ignore totems
             if (u->GetTypeId() == TYPEID_UNIT && ((Creature*)u)->IsTotem())
                 return false;
             if (i_funit->_IsValidAttackTarget(u, _spellInfo, i_obj->GetTypeId() == TYPEID_DYNAMICOBJECT ? i_obj : nullptr) && i_obj->IsWithinDistInMap(u, i_range))
                 return true;
             return false;
         }
References Unit::_IsValidAttackTarget(), _spellInfo, Object::GetTypeId(), i_funit, i_obj, i_range, WorldObject::IsWithinDistInMap(), TYPEID_DYNAMICOBJECT, and TYPEID_UNIT.
Member Data Documentation
_spellInfo
SpellInfo const* Acore::AnyAoETargetUnitInObjectRangeCheck::_spellInfo private
Definition at line 997 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_funit
Unit const* Acore::AnyAoETargetUnitInObjectRangeCheck::i_funit private
Definition at line 996 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_obj
WorldObject const* Acore::AnyAoETargetUnitInObjectRangeCheck::i_obj private
Definition at line 995 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck(), and operator()().
i_range
float Acore::AnyAoETargetUnitInObjectRangeCheck::i_range private
Definition at line 998 of file GridNotifiers.h.
Referenced by operator()().
i_targetForPlayer
bool Acore::AnyAoETargetUnitInObjectRangeCheck::i_targetForPlayer private
Definition at line 994 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h