Azerotcore-wotlk: src/server/game/AuctionHouse/AuctionHouseMgr.cpp File Reference
AuctionHouseMgr.cpp File Reference
#include "AccountMgr.h"
#include "AsyncAuctionListing.h"
#include "AuctionHouseMgr.h"
#include "AvgDiffTracker.h"
#include "Common.h"
#include "DatabaseEnv.h"
#include "DBCStores.h"
#include "Item.h"
#include "Logging/Log.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "World.h"
#include "WorldPacket.h"
#include "WorldSession.h"
#include <vector>
Functions
static bool SortAuction (AuctionEntry *left, AuctionEntry *right, AuctionSortOrderVector &sortOrder, Player *player, bool checkMinBidBuyout)
Variables
constexpr auto AH_MINIMUM_DEPOSIT = 100
Function Documentation
SortAuction()
static bool SortAuction (AuctionEntry * left, AuctionEntry * right, AuctionSortOrderVector & sortOrder, Player * player, bool checkMinBidBuyout) static
Definition at line 38 of file AuctionHouseMgr.cpp.
 {
     for (auto thisOrder : sortOrder)
     {
         switch (thisOrder.sortOrder)
         {
             case AUCTION_SORT_BID:
             {
                 if (left->bid == right->bid)
                 {
                     if (checkMinBidBuyout)
                     {
                         if (left->buyout == right->buyout)
{
                             if (left->startbid == right->startbid)
{
                                 continue;
                             }
                             return thisOrder.isDesc ? left->startbid > right->startbid : left->startbid < right->startbid;
                         }
                         return thisOrder.isDesc ? left->buyout > right->buyout : left->buyout < right->buyout;
                     }
                     continue;
                 }
                 return thisOrder.isDesc ? left->bid > right->bid : left->bid < right->bid;
             }
             case AUCTION_SORT_BUYOUT:
             case AUCTION_SORT_BUYOUT_2:
             {
                 if (left->buyout == right->buyout)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? left->buyout > right->buyout : left->buyout < right->buyout;
             }
             case AUCTION_SORT_ITEM:
             {
                 ItemTemplate const* protoLeft = sObjectMgr->GetItemTemplate(left->item_template);
                 ItemTemplate const* protoRight = sObjectMgr->GetItemTemplate(right->item_template);
                 if (!protoLeft || !protoRight)
                 {
                     continue;
                 }
                 std::string leftName = protoLeft->Name1;
                 std::string rightName = protoRight->Name1;
                 if (leftName.empty() || rightName.empty())
                 {
                     continue;
                 }
                 LocaleConstant locale = LOCALE_enUS;
                 if (player && player->GetSession())
                 {
                     locale = player->GetSession()->GetSessionDbLocaleIndex();
                 }
                 if (locale > LOCALE_enUS)
                 {
                     if (ItemLocale const* leftIl = sObjectMgr->GetItemLocale(protoLeft->ItemId))
                     {
                         ObjectMgr::GetLocaleString(leftIl->Name, locale, leftName);
                     }
                     if (ItemLocale const* rightIl = sObjectMgr->GetItemLocale(protoRight->ItemId))
                     {
                         ObjectMgr::GetLocaleString(rightIl->Name, locale, rightName);
                     }
                 }
                 int result = leftName.compare(rightName);
                 if (result == 0)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? result > 0 : result < 0;
             }
             case AUCTION_SORT_MINLEVEL:
             {
                 ItemTemplate const* protoLeft  = sObjectMgr->GetItemTemplate(left->item_template);
                 ItemTemplate const* protoRight = sObjectMgr->GetItemTemplate(right->item_template);
                 if (!protoLeft || !protoRight)
                 {
                     continue;
                 }
                 if (protoLeft->RequiredLevel == protoRight->RequiredLevel)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? protoLeft->RequiredLevel > protoRight->RequiredLevel : protoLeft->RequiredLevel < protoRight->RequiredLevel;
             }
             case AUCTION_SORT_OWNER:
             {
                 std::string leftName;
                 sObjectMgr->GetPlayerNameByGUID(left->owner.GetCounter(), leftName);
                 std::string rightName;
                 sObjectMgr->GetPlayerNameByGUID(right->owner.GetCounter(), rightName);
                 int result = leftName.compare(rightName);
                 if (result == 0)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? result > 0 : result < 0;
             }
             case AUCTION_SORT_RARITY:
             {
                 ItemTemplate const* protoLeft  = sObjectMgr->GetItemTemplate(left->item_template);
                 ItemTemplate const*  protoRight = sObjectMgr->GetItemTemplate(right->item_template);
                 if (!protoLeft || !protoRight)
                 {
                     continue;
                 }
                 if (protoLeft->Quality == protoRight->Quality)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? protoLeft->Quality > protoRight->Quality : protoLeft->Quality < protoRight->Quality;
             }
             case AUCTION_SORT_STACK:
             {
                 if (left->itemCount == right->itemCount)
                 {
                     continue;
                 }
                 if (!thisOrder.isDesc)
                 {
                     return (left->itemCount < right->itemCount);
                 }
                 return (left->itemCount > right->itemCount);
             }
             case AUCTION_SORT_TIMELEFT:
             {
                 if (left->expire_time == right->expire_time)
                 {
                     continue;
                 }
                 return thisOrder.isDesc ? left->expire_time > right->expire_time : left->expire_time < right->expire_time;
             }
             case AUCTION_SORT_MINBIDBUY:
             {
                 if (left->buyout == right->buyout)
                 {
                     if (left->startbid == right->startbid)
                     {
                         continue;
                     }
                     return thisOrder.isDesc ? left->startbid > right->startbid : left->startbid < right->startbid;
                 }
                 return thisOrder.isDesc ? left->buyout > right->buyout : left->buyout < right->buyout;
             }
             case AUCTION_SORT_MAX:
                 // Such sad travis appeasement
             case AUCTION_SORT_UNK4:
             default:
                 break;
         }
     }
     return false;
 }
References AUCTION_SORT_BID, AUCTION_SORT_BUYOUT, AUCTION_SORT_BUYOUT_2, AUCTION_SORT_ITEM, AUCTION_SORT_MAX, AUCTION_SORT_MINBIDBUY, AUCTION_SORT_MINLEVEL, AUCTION_SORT_OWNER, AUCTION_SORT_RARITY, AUCTION_SORT_STACK, AUCTION_SORT_TIMELEFT, AUCTION_SORT_UNK4, ObjectMgr::GetLocaleString(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), ItemTemplate::ItemId, align::left, LOCALE_enUS, ItemTemplate::Name1, ItemTemplate::Quality, ItemTemplate::RequiredLevel, align::right, and sObjectMgr.
Referenced by AuctionHouseObject::BuildListAuctionItems().
Variable Documentation
AH_MINIMUM_DEPOSIT
constexpr auto AH_MINIMUM_DEPOSIT = 100 constexpr
Definition at line 35 of file AuctionHouseMgr.cpp.
Referenced by AuctionHouseMgr::GetAuctionDeposit().