Azerotcore-wotlk: npc_experience Class Reference
npc_experience Class Reference
Public Member Functions
npc_experience ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1964 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_experience()
npc_experience::npc_experience () inline
Definition at line 1967 of file npcs_special.cpp.
 : CreatureScript("npc_experience") { }
Member Function Documentation
OnGossipHello()
bool npc_experience::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1969 of file npcs_special.cpp.
     {
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_XP_OFF, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_XP_ON, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
         SendGossipMenuFor(player, GOSSIP_TEXT_EXP, creature);
         return true;
     }
References AddGossipItemFor(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_EXP, GOSSIP_XP_OFF, GOSSIP_XP_ON, and SendGossipMenuFor().
OnGossipSelect()
bool npc_experience::OnGossipSelect (Player * player, Creature * , uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1977 of file npcs_special.cpp.
     {
         ClearGossipMenuFor(player);
         bool noXPGain = player->HasFlag(PLAYER_FLAGS, PLAYER_FLAGS_NO_XP_GAIN);
         bool doSwitch = false;
         auto toggleXpCost = sWorld->getIntConfig(CONFIG_TOGGLE_XP_COST);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1://xp off
                 {
                     if (!noXPGain)//does gain xp
                         doSwitch = true;//switch to don't gain xp
                 }
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2://xp on
                 {
                     if (noXPGain)//doesn't gain xp
                         doSwitch = true;//switch to gain xp
                 }
                 break;
         }
         if (doSwitch)
         {
             if (!player->HasEnoughMoney(toggleXpCost))
             {
                 player->SendBuyError(BUY_ERR_NOT_ENOUGHT_MONEY, 0, 0, 0);
             }
             else if (noXPGain)
             {
                 player->ModifyMoney(-toggleXpCost);
                 player->RemoveFlag(PLAYER_FLAGS, PLAYER_FLAGS_NO_XP_GAIN);
             }
             else if (!noXPGain)
             {
                 player->ModifyMoney(-toggleXpCost);
                 player->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_NO_XP_GAIN);
             }
         }
         player->PlayerTalkClass->SendCloseGossip();
         return true;
     }
References BUY_ERR_NOT_ENOUGHT_MONEY, ClearGossipMenuFor(), CONFIG_TOGGLE_XP_COST, GOSSIP_ACTION_INFO_DEF, Player::HasEnoughMoney(), Object::HasFlag(), Player::ModifyMoney(), PLAYER_FLAGS, PLAYER_FLAGS_NO_XP_GAIN, Player::PlayerTalkClass, Object::RemoveFlag(), Player::SendBuyError(), PlayerMenu::SendCloseGossip(), Object::SetFlag(), and sWorld.
The documentation for this class was generated from the following file:
src/server/scripts/World/npcs_special.cpp