Azerotcore-wotlk: deps/mysqllite/mysys/my_error.c File Reference
my_error.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <m_string.h>
#include <stdarg.h>
#include <m_ctype.h>
Classes
struct my_err_head
Macros
#define ERRMSGSIZE (512)
Functions
void my_error (int nr, myf MyFlags,...)
void my_printf_error (uint error, const char *format, myf MyFlags,...)
void my_printv_error (uint error, const char *format, myf MyFlags, va_list ap)
void my_message (uint error, const char *str, register myf MyFlags)
int my_error_register (const char **(*get_errmsgs)(), int first, int last)
const char ** my_error_unregister (int first, int last)
void my_error_unregister_all (void)
Variables
static struct my_err_head my_errmsgs_globerrs = {NULL, get_global_errmsgs, EE_ERROR_FIRST, EE_ERROR_LAST}
static struct my_err_head * my_errmsgs_list = &my_errmsgs_globerrs
Macro Definition Documentation
ERRMSGSIZE
#define ERRMSGSIZE (512)
Definition at line 23 of file my_error.c.
Function Documentation
my_error()
void my_error (int nr, myf MyFlags, ...)
Definition at line 71 of file my_error.c.
 {
   const char *format;
   struct my_err_head *meh_p;
   va_list args;
   char ebuff[ERRMSGSIZE];
   DBUG_ENTER("my_error");
   DBUG_PRINT("my", ("nr: %d  MyFlags: %d  errno: %d", nr, MyFlags, errno));
   /* Search for the error messages array, which could contain the message. */
   for (meh_p= my_errmsgs_list; meh_p; meh_p= meh_p->meh_next)
     if (nr <= meh_p->meh_last)
       break;
   /* get the error message string. Default, if NULL or empty string (""). */
   if (! (format= (meh_p && (nr >= meh_p->meh_first)) ?
                   meh_p->get_errmsgs()[nr - meh_p->meh_first] : NULL) || ! *format)
     (void) my_snprintf (ebuff, sizeof(ebuff), "Unknown error %d", nr);
   else
   {
     va_start(args,MyFlags);
     (void) my_vsnprintf_ex(&my_charset_utf8_general_ci, ebuff,
                            sizeof(ebuff), format, args);
     va_end(args);
   }
   (*error_handler_hook)(nr, ebuff, MyFlags);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ERRMSGSIZE, errno, format(), my_err_head::get_errmsgs, my_err_head::meh_first, my_err_head::meh_last, my_err_head::meh_next, my_charset_utf8_general_ci, my_errmsgs_list, my_snprintf(), my_vsnprintf_ex(), and NULL.
Referenced by get_charset(), get_charset_by_csname(), get_charset_by_name(), init_key_cache(), my_chsize(), my_close(), my_copy(), my_copystat(), my_create_with_symlink(), my_delete(), my_dir(), my_fclose(), my_fdopen(), my_fopen(), my_fread(), my_fwrite(), my_getwd(), my_lock(), my_malloc(), my_mkdir(), my_net_read(), my_once_alloc(), my_pread(), my_pwrite(), my_read(), my_readlink(), my_real_read(), my_realloc(), my_realpath(), my_register_filename(), my_rename(), my_rename_with_symlink(), my_seek(), my_setwd(), my_stat(), my_symlink(), my_sync(), my_tell(), my_write(), net_real_write(), net_realloc(), and wait_for_free_space().
my_error_register()
int my_error_register (const char **(*)() get_errmsgs, int first, int last)
Definition at line 189 of file my_error.c.
 {
   struct my_err_head *meh_p;
   struct my_err_head **search_meh_pp;
   /* Allocate a new header structure. */
   if (! (meh_p= (struct my_err_head*) my_malloc(sizeof(struct my_err_head),
                                                 MYF(MY_WME))))
     return 1;
   meh_p->get_errmsgs= get_errmsgs;
   meh_p->meh_first= first;
   meh_p->meh_last= last;
   /* Search for the right position in the list. */
   for (search_meh_pp= &my_errmsgs_list;
        *search_meh_pp;
        search_meh_pp= &(*search_meh_pp)->meh_next)
   {
     if ((*search_meh_pp)->meh_last > first)
       break;
   }
   /* Error numbers must be unique. No overlapping is allowed. */
   if (*search_meh_pp && ((*search_meh_pp)->meh_first <= last))
   {
     my_free(meh_p);
     return 1;
   }
   /* Insert header into the chain. */
   meh_p->meh_next= *search_meh_pp;
   *search_meh_pp= meh_p;
   return 0;
 }
References detail::first(), my_err_head::get_errmsgs, my_err_head::meh_first, my_err_head::meh_last, my_err_head::meh_next, my_errmsgs_list, my_free(), my_malloc(), MY_WME, and MYF.
Referenced by init_client_errs(), and my_handler_error_register().
my_error_unregister()
const char** my_error_unregister (int first, int last)
Definition at line 246 of file my_error.c.
 {
   struct my_err_head    *meh_p;
   struct my_err_head    **search_meh_pp;
   const char            **errmsgs;
   /* Search for the registration in the list. */
   for (search_meh_pp= &my_errmsgs_list;
        *search_meh_pp;
        search_meh_pp= &(*search_meh_pp)->meh_next)
   {
     if (((*search_meh_pp)->meh_first == first) &&
         ((*search_meh_pp)->meh_last == last))
       break;
   }
   if (! *search_meh_pp)
     return NULL;
   /* Remove header from the chain. */
   meh_p= *search_meh_pp;
   *search_meh_pp= meh_p->meh_next;
   /* Save the return value and free the header. */
   errmsgs= meh_p->get_errmsgs();
   my_free(meh_p);
   return errmsgs;
 }
References detail::first(), my_err_head::get_errmsgs, my_err_head::meh_next, my_errmsgs_list, my_free(), and NULL.
Referenced by finish_client_errs(), and my_handler_error_unregister().
my_error_unregister_all()
void my_error_unregister_all (void)
Definition at line 276 of file my_error.c.
 {
   struct my_err_head *cursor, *saved_next;
   for (cursor= my_errmsgs_globerrs.meh_next; cursor != NULL; cursor= saved_next)
   {
     /* We need this ptr, but we're about to free its container, so save it. */
     saved_next= cursor->meh_next;
     my_free(cursor);
   }
   my_errmsgs_globerrs.meh_next= NULL;  /* Freed in first iteration above. */
   my_errmsgs_list= &my_errmsgs_globerrs;
 }
References my_err_head::meh_next, my_errmsgs_globerrs, my_errmsgs_list, my_free(), and NULL.
Referenced by my_end().
my_message()
void my_message (uint error, const char * str, register myf MyFlags)
Definition at line 161 of file my_error.c.
 {
   (*error_handler_hook)(error, str, MyFlags);
 }
References error().
my_printf_error()
void my_printf_error (uint error, const char * format, myf MyFlags, ...)
Definition at line 112 of file my_error.c.
 {
   va_list args;
   char ebuff[ERRMSGSIZE];
   DBUG_ENTER("my_printf_error");
   DBUG_PRINT("my", ("nr: %d  MyFlags: %d  errno: %d  Format: %s",
             error, MyFlags, errno, format));
   va_start(args,MyFlags);
   (void) my_vsnprintf_ex(&my_charset_utf8_general_ci, ebuff,
                          sizeof(ebuff), format, args);
   va_end(args);
   (*error_handler_hook)(error, ebuff, MyFlags);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ERRMSGSIZE, errno, error(), format(), my_charset_utf8_general_ci, and my_vsnprintf_ex().
my_printv_error()
void my_printv_error (uint error, const char * format, myf MyFlags, va_list ap)
Definition at line 139 of file my_error.c.
 {
   char ebuff[ERRMSGSIZE];
   DBUG_ENTER("my_printv_error");
   DBUG_PRINT("my", ("nr: %d  MyFlags: %d  errno: %d  format: %s",
             error, MyFlags, errno, format));
   (void) my_vsnprintf(ebuff, sizeof(ebuff), format, ap);
   (*error_handler_hook)(error, ebuff, MyFlags);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ERRMSGSIZE, errno, error(), format(), and my_vsnprintf().
Variable Documentation
my_errmsgs_globerrs
struct my_err_head my_errmsgs_globerrs = {NULL, get_global_errmsgs, EE_ERROR_FIRST, EE_ERROR_LAST} static
Referenced by my_error_unregister_all().
my_errmsgs_list
struct my_err_head* my_errmsgs_list = &my_errmsgs_globerrs static
Definition at line 57 of file my_error.c.
Referenced by my_error(), my_error_register(), my_error_unregister(), and my_error_unregister_all().