Azerotcore-wotlk: npc_crok_scourgebane::npc_crok_scourgebaneAI Struct Reference
npc_crok_scourgebane::npc_crok_scourgebaneAI Struct Reference
Public Member Functions
npc_crok_scourgebaneAI (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void SetGUID (ObjectGuid guid, int32 type) override
void WaypointReached (uint32 waypointId) override
void WaypointStart (uint32 waypointId) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateEscortAI (uint32) override
void UpdateAI (uint32 diff) override
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
GuidSet _aliveTrash
InstanceScript * _instance
uint32 _currentWPid
uint32 _wipeCheckTimer
bool _handledWP4
bool _isEventDone
bool _didUnderTenPercentText
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 717 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_crok_scourgebaneAI()
npc_crok_scourgebane::npc_crok_scourgebaneAI::npc_crok_scourgebaneAI (Creature * creature) inline
Definition at line 719 of file icecrown_citadel.cpp.
                                                    : npc_escortAI(creature), _instance(creature->GetInstanceScript())
         {
             SetDespawnAtEnd(false);
             SetDespawnAtFar(false);
             _isEventDone = _instance->GetBossState(DATA_SISTER_SVALNA) == DONE;
         }
References _instance, _isEventDone, DATA_SISTER_SVALNA, DONE, InstanceScript::GetBossState(), npc_escortAI::SetDespawnAtEnd(), and npc_escortAI::SetDespawnAtFar().
Member Function Documentation
CanAIAttack()
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 964 of file icecrown_citadel.cpp.
         {
             // do not see targets inside Frostwing Halls when we are not there
             return target->GetTypeId() != TYPEID_PLAYER && (me->GetPositionY() > 2660.0f) == (target->GetPositionY() > 2660.0f) && target->GetEntry() != NPC_SINDRAGOSA;
         }
References Object::GetEntry(), Position::GetPositionY(), Object::GetTypeId(), ScriptedAI::me, NPC_SINDRAGOSA, and TYPEID_PLAYER.
DamageTaken()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 866 of file icecrown_citadel.cpp.
         {
             if (HealthBelowPct(10))
             {
                 if (!_didUnderTenPercentText)
                 {
                     _didUnderTenPercentText = true;
                     if (me->GetVictim() && me->GetVictim()->GetEntry() == NPC_SISTER_SVALNA)
                         Talk(SAY_CROK_WEAKENING_SVALNA);
                     else
                         Talk(SAY_CROK_WEAKENING_GAUNTLET);
                 }
                 damage = 0;
                 me->CastSpell(me, SPELL_ICEBOUND_ARMOR, true);
                 _events.ScheduleEvent(EVENT_HEALTH_CHECK, 1000);
             }
         }
References _didUnderTenPercentText, _events, Unit::CastSpell(), EVENT_HEALTH_CHECK, Object::GetEntry(), Unit::GetVictim(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, NPC_SISTER_SVALNA, SAY_CROK_WEAKENING_GAUNTLET, SAY_CROK_WEAKENING_SVALNA, EventMap::ScheduleEvent(), SPELL_ICEBOUND_ARMOR, and CreatureAI::Talk().
DoAction()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 738 of file icecrown_citadel.cpp.
         {
             if (action == ACTION_START_GAUNTLET)
             {
                 if (_isEventDone || me->isActiveObject() || !me->IsAlive())
                     return;
                 me->setActive(true);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                 // Load Grid with Sister Svalna
                 me->GetMap()->LoadGrid(4356.71f, 2484.33f);
                 if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                     svalna->AI()->DoAction(ACTION_START_GAUNTLET);
                 for (uint32 i = 0; i < 4; ++i)
                     if (Creature* crusader = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_CAPTAIN_ARNATH + i)))
                         crusader->AI()->DoAction(ACTION_START_GAUNTLET);
                 Talk(SAY_CROK_INTRO_1);
                 _events.ScheduleEvent(EVENT_ARNATH_INTRO_2, 7000);
                 _events.ScheduleEvent(EVENT_CROK_INTRO_3, 14000);
                 _events.ScheduleEvent(EVENT_START_PATHING, 37000);
             }
             else if (action == ACTION_RESET_EVENT)
             {
                 _isEventDone = _instance->GetBossState(DATA_SISTER_SVALNA) == DONE;
                 me->setActive(false);
                 _aliveTrash.clear();
                 _currentWPid = 0;
                 _handledWP4 = false;
                 me->CombatStop();
                 me->DeleteThreatList();
             }
         }
References _aliveTrash, _currentWPid, _events, _handledWP4, _instance, _isEventDone, ACTION_RESET_EVENT, ACTION_START_GAUNTLET, Unit::CombatStop(), DATA_CAPTAIN_ARNATH, DATA_SISTER_SVALNA, Unit::DeleteThreatList(), DONE, EVENT_ARNATH_INTRO_2, EVENT_CROK_INTRO_3, EVENT_START_PATHING, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), WorldObject::isActiveObject(), Unit::IsAlive(), Map::LoadGrid(), ScriptedAI::me, SAY_CROK_INTRO_1, EventMap::ScheduleEvent(), WorldObject::setActive(), Object::SetFlag(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 726 of file icecrown_citadel.cpp.
         {
             me->SetReactState(REACT_DEFENSIVE);
             _didUnderTenPercentText = false;
             _wipeCheckTimer = 3000;
             _handledWP4 = false;
             _events.Reset();
             _events.ScheduleEvent(EVENT_SCOURGE_STRIKE, urand(7500, 12500));
             _events.ScheduleEvent(EVENT_DEATH_STRIKE, urand(25000, 30000));
         }
References _didUnderTenPercentText, _events, _handledWP4, _wipeCheckTimer, EVENT_DEATH_STRIKE, EVENT_SCOURGE_STRIKE, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetReactState(), and urand().
SetGUID()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from UnitAI.
Definition at line 773 of file icecrown_citadel.cpp.
         {
             if (type == ACTION_VRYKUL_DEATH)
             {
                 _aliveTrash.erase(guid);
                 if (_aliveTrash.empty())
                 {
                     SetEscortPaused(false);
                     if (_currentWPid == 4 && !_handledWP4)
                     {
                         _handledWP4 = true;
                         Talk(SAY_CROK_FINAL_WP);
                         if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                             svalna->AI()->DoAction(ACTION_RESURRECT_CAPTAINS);
                     }
                 }
             }
         }
References _aliveTrash, _currentWPid, _handledWP4, _instance, ACTION_RESURRECT_CAPTAINS, ACTION_VRYKUL_DEATH, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, SAY_CROK_FINAL_WP, npc_escortAI::SetEscortPaused(), and CreatureAI::Talk().
UpdateAI()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 887 of file icecrown_citadel.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             //Position pos = me->GetHomePosition();
             if (!me->isActiveObject()/* && me->GetExactDist(&pos) < 5.0f*/) // during event
                 return;
             if (_wipeCheckTimer <= diff)
             {
                 _wipeCheckTimer = 3000;
                 Player* player = nullptr;
                 Acore::AnyPlayerInObjectRangeCheck check(me, 140.0f);
                 Acore::PlayerSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, player, check);
                 Cell::VisitWorldObjects(me, searcher, 140.0f);
                 // wipe
                 if (!player || me->GetExactDist(4357.0f, 2606.0f, 350.0f) > 125.0f)
                 {
                     //Talk(SAY_CROK_DEATH);
                     FrostwingGauntletRespawner respawner;
                     Acore::CreatureWorker<FrostwingGauntletRespawner> worker(me, respawner);
                     Cell::VisitGridObjects(me, worker, 333.0f);
                     return;
                 }
             }
             else
                 _wipeCheckTimer -= diff;
             UpdateVictim();
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_ARNATH_INTRO_2:
                     if (Creature* arnath = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_CAPTAIN_ARNATH)))
                         arnath->AI()->Talk(SAY_ARNATH_INTRO_2);
                     break;
                 case EVENT_CROK_INTRO_3:
                     Talk(SAY_CROK_INTRO_3);
                     break;
                 case EVENT_START_PATHING:
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                     Start(true, true);
                     break;
                 case EVENT_SCOURGE_STRIKE:
                     DoCastVictim(SPELL_SCOURGE_STRIKE);
                     _events.ScheduleEvent(EVENT_SCOURGE_STRIKE, urand(10000, 14000));
                     break;
                 case EVENT_DEATH_STRIKE:
                     if (HealthBelowPct(20))
                         DoCastVictim(SPELL_DEATH_STRIKE);
                     _events.ScheduleEvent(EVENT_DEATH_STRIKE, urand(5000, 10000));
                     break;
                 case EVENT_HEALTH_CHECK:
                     if (HealthAbovePct(25))
                     {
                         me->RemoveAurasDueToSpell(SPELL_ICEBOUND_ARMOR);
                         _didUnderTenPercentText = false;
                     }
                     else
                     {
                         Unit::DealHeal(me, me, me->CountPctFromMaxHealth(3));
                         _events.ScheduleEvent(EVENT_HEALTH_CHECK, 1000);
                     }
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _didUnderTenPercentText, _events, _instance, _wipeCheckTimer, Unit::CountPctFromMaxHealth(), DATA_CAPTAIN_ARNATH, Unit::DealHeal(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARNATH_INTRO_2, EVENT_CROK_INTRO_3, EVENT_DEATH_STRIKE, EVENT_HEALTH_CHECK, EVENT_SCOURGE_STRIKE, EVENT_START_PATHING, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Position::GetExactDist(), InstanceScript::GetGuidData(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), ScriptedAI::HealthBelowPct(), WorldObject::isActiveObject(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_ARNATH_INTRO_2, SAY_CROK_INTRO_3, EventMap::ScheduleEvent(), SPELL_DEATH_STRIKE, SPELL_ICEBOUND_ARMOR, SPELL_SCOURGE_STRIKE, npc_escortAI::Start(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, EventMap::Update(), npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), urand(), Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
UpdateEscortAI()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateEscortAI (uint32) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 885 of file icecrown_citadel.cpp.
 {}
WaypointReached()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 792 of file icecrown_citadel.cpp.
         {
             switch (waypointId)
             {
                 // pause pathing until trash pack is cleared
                 case 0:
                     Talk(SAY_CROK_COMBAT_WP_0);
                     if (!_aliveTrash.empty())
                         SetEscortPaused(true);
                     break;
                 case 1:
                     Talk(SAY_CROK_COMBAT_WP_1);
                     if (!_aliveTrash.empty())
                         SetEscortPaused(true);
                     break;
                 case 2:
                     if (!_aliveTrash.empty())
                         SetEscortPaused(true);
                     break;
                 case 4:
                     if (_aliveTrash.empty() && !_handledWP4)
                     {
                         _handledWP4 = true;
                         Talk(SAY_CROK_FINAL_WP);
                         if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                             svalna->AI()->DoAction(ACTION_RESURRECT_CAPTAINS);
                     }
                     break;
                 default:
                     break;
             }
         }
References _aliveTrash, _handledWP4, _instance, ACTION_RESURRECT_CAPTAINS, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, SAY_CROK_COMBAT_WP_0, SAY_CROK_COMBAT_WP_1, SAY_CROK_FINAL_WP, npc_escortAI::SetEscortPaused(), and CreatureAI::Talk().
WaypointStart()
void npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart (uint32 waypointId) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 825 of file icecrown_citadel.cpp.
         {
             _currentWPid = waypointId;
             float minY = 0.0f;
             switch (waypointId)
             {
                 case 0:
                     minY = 2600.0f;
                     break;
                 case 1:
                     minY = 2550.0f;
                     if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                         svalna->AI()->DoAction(ACTION_KILL_CAPTAIN);
                     break;
                 case 2:
                     minY = 2515.0f;
                     if (Creature* svalna = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_SISTER_SVALNA)))
                         svalna->AI()->DoAction(ACTION_KILL_CAPTAIN);
                     break;
                 case 4:
                     minY = 2475.0f;
                     break;
                 default:
                     break;
             }
             if (minY)
             {
                 // get all nearby vrykul
                 std::list<Creature*> temp;
                 FrostwingVrykulSearcher check(me, 150.0f);
                 Acore::CreatureListSearcher<FrostwingVrykulSearcher> searcher(me, temp, check);
                 Cell::VisitGridObjects(me, searcher, 150.0f);
                 _aliveTrash.clear();
                 for (std::list<Creature*>::iterator itr = temp.begin(); itr != temp.end(); ++itr)
                     if ((*itr)->GetHomePosition().GetPositionY() > minY)
                         _aliveTrash.insert((*itr)->GetGUID());
             }
         }
References _aliveTrash, _currentWPid, _instance, ACTION_KILL_CAPTAIN, DATA_SISTER_SVALNA, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, and Cell::VisitGridObjects().
Member Data Documentation
_aliveTrash
GuidSet npc_crok_scourgebane::npc_crok_scourgebaneAI::_aliveTrash private
Definition at line 972 of file icecrown_citadel.cpp.
Referenced by DoAction(), SetGUID(), WaypointReached(), and WaypointStart().
_currentWPid
uint32 npc_crok_scourgebane::npc_crok_scourgebaneAI::_currentWPid private
Definition at line 974 of file icecrown_citadel.cpp.
Referenced by DoAction(), SetGUID(), and WaypointStart().
_didUnderTenPercentText
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_didUnderTenPercentText private
Definition at line 978 of file icecrown_citadel.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
_events
EventMap npc_crok_scourgebane::npc_crok_scourgebaneAI::_events private
Definition at line 971 of file icecrown_citadel.cpp.
Referenced by DamageTaken(), DoAction(), Reset(), and UpdateAI().
_handledWP4
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_handledWP4 private
Definition at line 976 of file icecrown_citadel.cpp.
Referenced by DoAction(), Reset(), SetGUID(), and WaypointReached().
_instance
InstanceScript* npc_crok_scourgebane::npc_crok_scourgebaneAI::_instance private
Definition at line 973 of file icecrown_citadel.cpp.
Referenced by DoAction(), npc_crok_scourgebaneAI(), SetGUID(), UpdateAI(), WaypointReached(), and WaypointStart().
_isEventDone
bool npc_crok_scourgebane::npc_crok_scourgebaneAI::_isEventDone private
Definition at line 977 of file icecrown_citadel.cpp.
Referenced by DoAction(), and npc_crok_scourgebaneAI().
_wipeCheckTimer
uint32 npc_crok_scourgebane::npc_crok_scourgebaneAI::_wipeCheckTimer private
Definition at line 975 of file icecrown_citadel.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp