Azerotcore-wotlk: PowerUsersSelector Struct Reference
PowerUsersSelector Struct Reference
#include <UnitAI.h>
Public Member Functions
PowerUsersSelector (Unit const *unit, Powers power, float dist, bool playerOnly)
bool operator() (Unit const *target) const
Public Attributes
Unit const * _me
Powers const _power
float const _dist
bool const _playerOnly
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 118 of file UnitAI.h.
Constructor & Destructor Documentation
PowerUsersSelector()
PowerUsersSelector::PowerUsersSelector (Unit const * unit, Powers power, float dist, bool playerOnly) inline
Definition at line 125 of file UnitAI.h.
 : _me(unit), _power(power), _dist(dist), _playerOnly(playerOnly) { }
Member Function Documentation
operator()()
bool PowerUsersSelector::operator() (Unit const * target) const inline
Definition at line 127 of file UnitAI.h.
     {
         if (!_me || !target)
             return false;
         if (target->getPowerType() != _power)
             return false;
         if (_playerOnly && target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (_dist > 0.0f && !_me->IsWithinCombatRange(target, _dist))
             return false;
         if (_dist < 0.0f && _me->IsWithinCombatRange(target, -_dist))
             return false;
         return true;
     }
References _dist, _me, _playerOnly, _power, Unit::getPowerType(), Object::GetTypeId(), Unit::IsWithinCombatRange(), and TYPEID_PLAYER.
Member Data Documentation
_dist
float const PowerUsersSelector::_dist
Definition at line 122 of file UnitAI.h.
Referenced by operator()().
_me
Unit const* PowerUsersSelector::_me
Definition at line 120 of file UnitAI.h.
Referenced by operator()().
_playerOnly
bool const PowerUsersSelector::_playerOnly
Definition at line 123 of file UnitAI.h.
Referenced by operator()().
_power
Powers const PowerUsersSelector::_power
Definition at line 121 of file UnitAI.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/game/AI/CoreAI/UnitAI.h