Azerotcore-wotlk: BattlegroundMapScript Class Reference
BattlegroundMapScript Class Reference
#include <ScriptMgr.h>
Public Member Functions
bool isAfterLoadScript () const override
void checkValidity () override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
const std::string & GetName () const
Public Member Functions inherited from MapScript< BattlegroundMap >
void checkMap ()
MapEntry const * GetEntry ()
virtual void OnCreate (BattlegroundMap *)
virtual void OnDestroy (BattlegroundMap *)
virtual void OnLoadGridMap (BattlegroundMap *, GridMap *, uint32, uint32)
virtual void OnUnloadGridMap (BattlegroundMap *, GridMap *, uint32, uint32)
virtual void OnPlayerEnter (BattlegroundMap *, Player *)
virtual void OnPlayerLeave (BattlegroundMap *, Player *)
void OnUpdate (BattlegroundMap *, uint32) override
Public Member Functions inherited from UpdatableScript< TObject >
virtual void OnUpdate (TObject *, uint32)
Protected Member Functions
BattlegroundMapScript (const char *name, uint32 mapId)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from MapScript< BattlegroundMap >
MapScript (uint32 mapId)
Protected Member Functions inherited from UpdatableScript< TObject >
UpdatableScript ()=default
Detailed Description
Definition at line 339 of file ScriptMgr.h.
Constructor & Destructor Documentation
BattlegroundMapScript()
BattlegroundMapScript::BattlegroundMapScript (const char * name, uint32 mapId) protected
Definition at line 3220 of file ScriptMgr.cpp.
     : ScriptObject(name), MapScript<BattlegroundMap>(mapId)
 {
     ScriptRegistry<BattlegroundMapScript>::AddScript(this);
 }
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
checkValidity()
void BattlegroundMapScript::checkValidity () inline override virtual
Reimplemented from ScriptObject.
Definition at line 347 of file ScriptMgr.h.
     {
         checkMap();
         if (GetEntry() && !GetEntry()->IsBattleground())
             LOG_ERROR("maps.script", "BattlegroundMapScript for map %u is invalid.", GetEntry()->MapID);
     }
References MapScript< BattlegroundMap >::checkMap(), MapScript< BattlegroundMap >::GetEntry(), and LOG_ERROR.
isAfterLoadScript()
bool BattlegroundMapScript::isAfterLoadScript () const inline override virtual
Reimplemented from ScriptObject.
Definition at line 345 of file ScriptMgr.h.
 { return true; }
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptMgr.h
src/server/game/Scripting/ScriptMgr.cpp