Azerotcore-wotlk: PlayerDumpWriter Class Reference
PlayerDumpWriter Class Reference
#include <PlayerDump.h>
Public Member Functions
PlayerDumpWriter ()
bool GetDump (uint32 guid, std::string &dump)
DumpReturn WriteDump (std::string const &file, uint32 guid)
Private Types
typedef std::set< uint32 > GUIDs
Private Member Functions
bool DumpTable (std::string &dump, uint32 guid, char const *tableFrom, char const *tableTo, DumpTableType type)
std::string GenerateWhereStr (char const *field, GUIDs const &guids, GUIDs::const_iterator &itr)
std::string GenerateWhereStr (char const *field, uint32 guid)
Private Attributes
GUIDs pets
GUIDs mails
GUIDs items
Additional Inherited Members
Protected Member Functions inherited from PlayerDump
PlayerDump ()
Detailed Description
Definition at line 69 of file PlayerDump.h.
Member Typedef Documentation
GUIDs
typedef std::set<uint32> PlayerDumpWriter::GUIDs private
Definition at line 77 of file PlayerDump.h.
Constructor & Destructor Documentation
PlayerDumpWriter()
PlayerDumpWriter::PlayerDumpWriter () inline
Definition at line 72 of file PlayerDump.h.
 {}
Member Function Documentation
DumpTable()
bool PlayerDumpWriter::DumpTable (std::string & dump, uint32 guid, char const * tableFrom, char const * tableTo, DumpTableType type) private
Definition at line 265 of file PlayerDump.cpp.
 {
     GUIDs const* guids = nullptr;
     char const* fieldname = nullptr;
     switch (type)
     {
         case DTT_ITEM:
             fieldname = "guid";
             guids = &items;
             break;
         case DTT_ITEM_GIFT:
             fieldname = "item_guid";
             guids = &items;
             break;
         case DTT_PET:
             fieldname = "owner";
             break;
         case DTT_PET_TABLE:
             fieldname = "guid";
             guids = &pets;
             break;
         case DTT_MAIL:
             fieldname = "receiver";
             break;
         case DTT_MAIL_ITEM:
             fieldname = "mail_id";
             guids = &mails;
             break;
         default:
             fieldname = "guid";
             break;
     }
     // for guid set stop if set is empty
     if (guids && guids->empty())
         return true;                                        // nothing to do
     // setup for guids case start position
     GUIDs::const_iterator guids_itr;
     if (guids)
         guids_itr = guids->begin();
     do
     {
         std::string wherestr;
         if (guids)                                           // set case, get next guids string
             wherestr = GenerateWhereStr(fieldname, *guids, guids_itr);
         else                                                // not set case, get single guid string
             wherestr = GenerateWhereStr(fieldname, guid);
         QueryResult result = CharacterDatabase.PQuery("SELECT * FROM %s WHERE %s", tableFrom, wherestr.c_str());
         if (!result)
             return true;
         do
         {
             // collect guids
             switch (type)
             {
                 case DTT_INVENTORY:
                     StoreGUID(result, 3, items);                // item guid collection (character_inventory.item)
                     break;
                 case DTT_PET:
                     StoreGUID(result, 0, pets);                 // pet petnumber collection (character_pet.id)
                     break;
                 case DTT_MAIL:
                     StoreGUID(result, 0, mails);                // mail id collection (mail.id)
                     break;
                 case DTT_MAIL_ITEM:
                     StoreGUID(result, 1, items);                // item guid collection (mail_items.item_guid)
                     break;
                 case DTT_CHARACTER:
                     {
                         if (result->GetFieldCount() <= 74)          // avoid crashes on next check
                             LOG_FATAL("entities.player.dump", "PlayerDumpWriter::DumpTable - Trying to access non-existing or wrong positioned field (`deleteInfos_Account`) in `characters` table.");
                         if (result->Fetch()[74].GetUInt32())        // characters.deleteInfos_Account - if filled error
                             return false;
                         break;
                     }
                 default:
                     break;
             }
             dump += CreateDumpString(tableTo, result);
             dump += "\n";
         } while (result->NextRow());
     } while (guids && guids_itr != guids->end());            // not set case iterate single time, set case iterate for all guids
     return true;
 }
References CharacterDatabase, CreateDumpString(), DTT_CHARACTER, DTT_INVENTORY, DTT_ITEM, DTT_ITEM_GIFT, DTT_MAIL, DTT_MAIL_ITEM, DTT_PET, DTT_PET_TABLE, GenerateWhereStr(), items, LOG_FATAL, mails, pets, and StoreGUID().
Referenced by GetDump().
GenerateWhereStr() [1/2]
std::string PlayerDumpWriter::GenerateWhereStr (char const * field, GUIDs const & guids, GUIDs::const_iterator & itr) private
Definition at line 225 of file PlayerDump.cpp.
 {
     std::ostringstream wherestr;
     wherestr << field << " IN ('";
     for (; itr != guids.end(); ++itr)
     {
         wherestr << *itr;
         if (wherestr.str().size() > MAX_QUERY_LEN - 50)      // near to max query
         {
             ++itr;
             break;
         }
         GUIDs::const_iterator itr2 = itr;
         if (++itr2 != guids.end())
             wherestr << "', '";
     }
     wherestr << "')";
     return wherestr.str();
 }
References MAX_QUERY_LEN.
Referenced by DumpTable().
GenerateWhereStr() [2/2]
std::string PlayerDumpWriter::GenerateWhereStr (char const * field, uint32 guid) private
Definition at line 218 of file PlayerDump.cpp.
 {
     std::ostringstream wherestr;
     wherestr << field << " = '" << guid << '\'';
     return wherestr.str();
 }
GetDump()
bool PlayerDumpWriter::GetDump (uint32 guid, std::string & dump)
Definition at line 358 of file PlayerDump.cpp.
 {
     dump = "";
     dump += "IMPORTANT NOTE: THIS DUMPFILE IS MADE FOR USE WITH THE 'PDUMP' COMMAND ONLY - EITHER THROUGH INGAME CHAT OR ON CONSOLE!\n";
     dump += "IMPORTANT NOTE: DO NOT apply it directly - it will irreversibly DAMAGE and CORRUPT your database! You have been warned!\n\n";
     for (int i = 0; i < DUMP_TABLE_COUNT; ++i)
         if (!DumpTable(dump, guid, dumpTables[i].name, dumpTables[i].name, dumpTables[i].type))
             return false;
     // TODO: Add instance/group..
     // TODO: Add a dump level option to skip some non-important tables
     return true;
 }
References DUMP_TABLE_COUNT, DumpTable(), dumpTables, and name.
Referenced by WriteDump().
WriteDump()
DumpReturn PlayerDumpWriter::WriteDump (std::string const & file, uint32 guid)
Definition at line 375 of file PlayerDump.cpp.
 {
     if (sWorld->getBoolConfig(CONFIG_PDUMP_NO_PATHS))
         if (strstr(file.c_str(), "\\") || strstr(file.c_str(), "/"))
             return DUMP_FILE_OPEN_ERROR;
     if (sWorld->getBoolConfig(CONFIG_PDUMP_NO_OVERWRITE))
         if (FILE* f = fopen(file.c_str(), "r"))
         {
             fclose(f);
             return DUMP_FILE_OPEN_ERROR;
         }
     FILE* fout = fopen(file.c_str(), "w");
     if (!fout)
         return DUMP_FILE_OPEN_ERROR;
     DumpReturn ret = DUMP_SUCCESS;
     std::string dump;
     if (!GetDump(guid, dump))
         ret = DUMP_CHARACTER_DELETED;
     fprintf(fout, "%s\n", dump.c_str());
     fclose(fout);
     return ret;
 }
References CONFIG_PDUMP_NO_OVERWRITE, CONFIG_PDUMP_NO_PATHS, DUMP_CHARACTER_DELETED, DUMP_FILE_OPEN_ERROR, DUMP_SUCCESS, f(), mpq::file, fprintf(), GetDump(), ret, and sWorld.
Member Data Documentation
items
GUIDs PlayerDumpWriter::items private
Definition at line 85 of file PlayerDump.h.
Referenced by DumpTable().
mails
GUIDs PlayerDumpWriter::mails private
Definition at line 84 of file PlayerDump.h.
Referenced by DumpTable().
pets
GUIDs PlayerDumpWriter::pets private
Definition at line 83 of file PlayerDump.h.
Referenced by DumpTable().
The documentation for this class was generated from the following files:
src/server/game/Tools/PlayerDump.h
src/server/game/Tools/PlayerDump.cpp