Azerotcore-wotlk: boss_thaddius_summon::boss_thaddius_summonAI Struct Reference
boss_thaddius_summon::boss_thaddius_summonAI Struct Reference
Public Member Functions
boss_thaddius_summonAI (Creature *c)
void Reset () override
void EnterEvadeMode () override
void EnterCombat (Unit *pWho) override
void DoAction (int32 param) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
uint32 pullTimer {}
uint32 visualTimer {}
bool overload
ObjectGuid myCoil
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 381 of file boss_thaddius.cpp.
Constructor & Destructor Documentation
boss_thaddius_summonAI()
boss_thaddius_summon::boss_thaddius_summonAI::boss_thaddius_summonAI (Creature * c) inline explicit
Definition at line 383 of file boss_thaddius.cpp.
                                                      : ScriptedAI(c)
         {
             pInstance = me->GetInstanceScript();
             overload = false;
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, overload, and pInstance.
Member Function Documentation
DoAction()
void boss_thaddius_summon::boss_thaddius_summonAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 454 of file boss_thaddius.cpp.
         {
             if (param == ACTION_MAGNETIC_PULL)
             {
                 pullTimer = 1;
                 me->SetControlled(true, UNIT_STATE_STUNNED);
             }
             else if (param == ACTION_RESTORE)
             {
                 if (!me->IsAlive())
                 {
                     me->Respawn();
                     me->SetInCombatWithZone();
                     Talk(me->GetEntry() == NPC_STALAGG ? EMOTE_STAL_REVIVE : EMOTE_FEUG_REVIVE);
                 }
                 else
                 {
                     me->SetHealth(me->GetMaxHealth());
                 }
             }
         }
References ACTION_MAGNETIC_PULL, ACTION_RESTORE, EMOTE_FEUG_REVIVE, EMOTE_STAL_REVIVE, Object::GetEntry(), Unit::GetMaxHealth(), Unit::IsAlive(), ScriptedAI::me, NPC_STALAGG, pullTimer, Creature::Respawn(), Unit::SetControlled(), Unit::SetHealth(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and UNIT_STATE_STUNNED.
Referenced by UpdateAI().
EnterCombat()
void boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat (Unit * pWho) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 417 of file boss_thaddius.cpp.
         {
             me->SetInCombatWithZone();
             if (Creature* cr = me->FindNearestCreature(NPC_TESLA_COIL, 150.f, true))
             {
                 myCoil = cr->GetGUID();
             }
             if (me->GetEntry() == NPC_STALAGG)
             {
                 events.ScheduleEvent(EVENT_MINION_POWER_SURGE, 10000);
                 Talk(SAY_STAL_AGGRO);
             }
             else
             {
                 events.ScheduleEvent(EVENT_MINION_STATIC_FIELD, 5000);
                 Talk(SAY_FEUG_AGGRO);
             }
             events.ScheduleEvent(EVENT_MINION_CHECK_DISTANCE, 5000);
             if (me->GetEntry() == NPC_STALAGG) // This event needs synchronisation, called for stalagg only
             {
                 events.ScheduleEvent(EVENT_MINION_MAGNETIC_PULL, 20000);
             }
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_THADDIUS_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
                 if (Creature* cr = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_THADDIUS_BOSS)))
                 {
                     cr->AI()->AttackStart(pWho);
                     cr->AddThreat(pWho, 10.0f);
                 }
             }
         }
References DATA_THADDIUS_BOSS, DATA_THADDIUS_GATE, EVENT_MINION_CHECK_DISTANCE, EVENT_MINION_MAGNETIC_PULL, EVENT_MINION_POWER_SURGE, EVENT_MINION_STATIC_FIELD, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_READY, ScriptedAI::me, myCoil, NPC_STALAGG, NPC_TESLA_COIL, pInstance, SAY_FEUG_AGGRO, SAY_STAL_AGGRO, Creature::SetInCombatWithZone(), and CreatureAI::Talk().
EnterEvadeMode()
void boss_thaddius_summon::boss_thaddius_summonAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 411 of file boss_thaddius.cpp.
         {
             me->SetControlled(false, UNIT_STATE_STUNNED);
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_STUNNED.
JustDied()
void boss_thaddius_summon::boss_thaddius_summonAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 476 of file boss_thaddius.cpp.
         {
             Talk(me->GetEntry() == NPC_STALAGG ? SAY_STAL_DEATH : SAY_FEUG_DEATH);
             Talk(me->GetEntry() == NPC_STALAGG ? EMOTE_STAL_DEATH : EMOTE_FEUG_DEATH);
             if (pInstance)
             {
                 if (Creature* cr = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_THADDIUS_BOSS)))
                 {
                     cr->AI()->DoAction(ACTION_SUMMON_DIED);
                 }
             }
         }
References ACTION_SUMMON_DIED, DATA_THADDIUS_BOSS, EMOTE_FEUG_DEATH, EMOTE_STAL_DEATH, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), ScriptedAI::me, NPC_STALAGG, pInstance, SAY_FEUG_DEATH, SAY_STAL_DEATH, and CreatureAI::Talk().
KilledUnit()
void boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 489 of file boss_thaddius.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
             if (!urand(0, 2))
             {
                 Talk(me->GetEntry() == NPC_STALAGG ? SAY_STAL_SLAY : SAY_FEUG_SLAY);
             }
         }
References DATA_IMMORTAL_FAIL, Object::GetEntry(), Object::GetTypeId(), ScriptedAI::me, NPC_STALAGG, pInstance, SAY_FEUG_SLAY, SAY_STAL_SLAY, ZoneScript::SetData(), CreatureAI::Talk(), TYPEID_PLAYER, and urand().
Reset()
void boss_thaddius_summon::boss_thaddius_summonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 396 of file boss_thaddius.cpp.
         {
             pullTimer = 0;
             visualTimer = 1;
             overload = false;
             events.Reset();
             me->SetControlled(false, UNIT_STATE_STUNNED);
             if (Creature* cr = me->FindNearestCreature(NPC_TESLA_COIL, 150.0f))
             {
                 cr->CastSpell(cr, me->GetEntry() == NPC_STALAGG ? SPELL_STALAGG_CHAIN : SPELL_FEUGEN_CHAIN, false);
                 cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                 myCoil = cr->GetGUID();
             }
         }
References WorldObject::FindNearestCreature(), Object::GetEntry(), ScriptedAI::me, myCoil, NPC_STALAGG, NPC_TESLA_COIL, overload, pullTimer, Unit::SetControlled(), SPELL_FEUGEN_CHAIN, SPELL_STALAGG_CHAIN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STATE_STUNNED, and visualTimer.
UpdateAI()
void boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 504 of file boss_thaddius.cpp.
         {
             if (visualTimer)
             {
                 visualTimer += diff;
                 if (visualTimer >= 3000)
                 {
                     visualTimer = 0;
                     if (Creature* cr = me->FindNearestCreature(NPC_TESLA_COIL, 150.0f))
                     {
                         cr->CastSpell(cr, me->GetEntry() == NPC_STALAGG ? SPELL_STALAGG_CHAIN : SPELL_FEUGEN_CHAIN, false);
                     }
                 }
             }
             if (!UpdateVictim())
                 return;
             if (pullTimer) // Disable AI during pull
             {
                 pullTimer += diff;
                 if (pullTimer >= 3000)
                 {
                     me->SetControlled(false, UNIT_STATE_STUNNED);
                     pullTimer = 0;
                 }
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_MINION_POWER_SURGE:
                     me->CastSpell(me, RAID_MODE(SPELL_POWER_SURGE_10, SPELL_POWER_SURGE_25), false);
                     events.RepeatEvent(19000);
                     break;
                 case EVENT_MINION_STATIC_FIELD:
                     me->CastSpell(me, RAID_MODE(SPELL_STATIC_FIELD_10, SPELL_STATIC_FIELD_25), false);
                     events.RepeatEvent(3000);
                     break;
                 case EVENT_MINION_MAGNETIC_PULL:
                     events.RepeatEvent(20000);
                     if (pInstance)
                     {
                         if (Creature* feugen = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FEUGEN_BOSS)))
{
                             if (!feugen->IsAlive() || !feugen->GetVictim() || !me->GetVictim())
                                 return;
                             float threatFeugen = feugen->getThreatMgr().getThreat(feugen->GetVictim());
                             float threatStalagg = me->getThreatMgr().getThreat(me->GetVictim());
                             Unit* tankFeugen = feugen->GetVictim();
                             Unit* tankStalagg = me->GetVictim();
                             feugen->getThreatMgr().modifyThreatPercent(tankFeugen, -100);
                             feugen->AddThreat(tankStalagg, threatFeugen);
                             feugen->CastSpell(tankStalagg, SPELL_MAGNETIC_PULL, true);
                             feugen->AI()->DoAction(ACTION_MAGNETIC_PULL);
                             me->getThreatMgr().modifyThreatPercent(tankStalagg, -100);
                             me->AddThreat(tankFeugen, threatStalagg);
                             me->CastSpell(tankFeugen, SPELL_MAGNETIC_PULL, true);
                             DoAction(ACTION_MAGNETIC_PULL);
                         }
                     }
                     break;
                 case EVENT_MINION_CHECK_DISTANCE:
                     if (Creature* cr = ObjectAccessor::GetCreature(*me, myCoil))
                     {
                         if (!me->GetHomePosition().IsInDist(me, 28) && me->IsInCombat())
{
                             if (!overload)
{
                                 overload = true;
                                 cr->AI()->Talk(EMOTE_TESLA_LINK_BREAKS);
                                 me->RemoveAurasDueToSpell(me->GetEntry() == NPC_STALAGG ? SPELL_STALAGG_CHAIN : SPELL_FEUGEN_CHAIN);
                                 cr->InterruptNonMeleeSpells(true);
                             }
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 1000.f, true))
{
                                 cr->CastStop(SPELL_TESLA_SHOCK);
                                 cr->CastSpell(target, SPELL_TESLA_SHOCK, true);
                             }
                             events.RepeatEvent(1500);
                             break;
                         }
                         else
{
                             overload = false;
                             cr->CastSpell(cr, me->GetEntry() == NPC_STALAGG ? SPELL_STALAGG_CHAIN : SPELL_FEUGEN_CHAIN, false);
                         }
                     }
                     events.RepeatEvent(5000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_MAGNETIC_PULL, Unit::AddThreat(), Unit::CastSpell(), DATA_FEUGEN_BOSS, DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_TESLA_LINK_BREAKS, EVENT_MINION_CHECK_DISTANCE, EVENT_MINION_MAGNETIC_PULL, EVENT_MINION_POWER_SURGE, EVENT_MINION_STATIC_FIELD, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), ThreatMgr::getThreat(), Unit::getThreatMgr(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsInCombat(), ScriptedAI::me, ThreatMgr::modifyThreatPercent(), myCoil, NPC_STALAGG, NPC_TESLA_COIL, overload, pInstance, pullTimer, ScriptedAI::RAID_MODE(), Unit::RemoveAurasDueToSpell(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetControlled(), SPELL_FEUGEN_CHAIN, SPELL_MAGNETIC_PULL, SPELL_POWER_SURGE_10, SPELL_POWER_SURGE_25, SPELL_STALAGG_CHAIN, SPELL_STATIC_FIELD_10, SPELL_STATIC_FIELD_25, SPELL_TESLA_SHOCK, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, CreatureAI::UpdateVictim(), and visualTimer.
Member Data Documentation
events
EventMap boss_thaddius_summon::boss_thaddius_summonAI::events
Definition at line 390 of file boss_thaddius.cpp.
myCoil
ObjectGuid boss_thaddius_summon::boss_thaddius_summonAI::myCoil
Definition at line 394 of file boss_thaddius.cpp.
Referenced by EnterCombat(), Reset(), and UpdateAI().
overload
bool boss_thaddius_summon::boss_thaddius_summonAI::overload
Definition at line 393 of file boss_thaddius.cpp.
Referenced by boss_thaddius_summonAI(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_thaddius_summon::boss_thaddius_summonAI::pInstance
Definition at line 389 of file boss_thaddius.cpp.
Referenced by boss_thaddius_summonAI(), EnterCombat(), JustDied(), KilledUnit(), and UpdateAI().
pullTimer
uint32 boss_thaddius_summon::boss_thaddius_summonAI::pullTimer {}
Definition at line 391 of file boss_thaddius.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
visualTimer
uint32 boss_thaddius_summon::boss_thaddius_summonAI::visualTimer {}
Definition at line 392 of file boss_thaddius.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp