Azerotcore-wotlk: boss_gloomrel Class Reference
boss_gloomrel Class Reference
Public Member Functions
boss_gloomrel ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 56 of file boss_tomb_of_seven.cpp.
Constructor & Destructor Documentation
boss_gloomrel()
boss_gloomrel::boss_gloomrel () inline
Definition at line 59 of file boss_tomb_of_seven.cpp.
 : CreatureScript("boss_gloomrel") { }
Member Function Documentation
OnGossipHello()
bool boss_gloomrel::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 90 of file boss_tomb_of_seven.cpp.
     {
         if (player->GetQuestRewardStatus(QUEST_SPECTRAL_CHALICE) == 1 && player->GetSkillValue(SKILL_MINING) >= DATA_SKILLPOINT_MIN && !player->HasSpell(SPELL_SMELT_DARK_IRON))
         {
             AddGossipItemFor(player, GOSSIP_GROOMREL, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             SendGossipMenuFor(player, SAY_QUEST_COMPLETED, creature->GetGUID());
         }
         if (player->GetQuestRewardStatus(QUEST_SPECTRAL_CHALICE) == 0 && player->GetSkillValue(SKILL_MINING) >= DATA_SKILLPOINT_MIN)
             AddGossipItemFor(player, GOSSIP_GROOMREL, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), DATA_SKILLPOINT_MIN, Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetSkillValue(), GOSSIP_ACTION_INFO_DEF, GOSSIP_GROOMREL, GOSSIP_SENDER_MAIN, Player::HasSpell(), QUEST_SPECTRAL_CHALICE, SAY_QUEST_COMPLETED, SendGossipMenuFor(), SKILL_MINING, and SPELL_SMELT_DARK_IRON.
OnGossipSelect()
bool boss_gloomrel::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 61 of file boss_tomb_of_seven.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 AddGossipItemFor(player, GOSSIP_TEXT_CONTINUE, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 11);
                 SendGossipMenuFor(player, SAY_QUEST_COMPLETED_END, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+11:
                 CloseGossipMenuFor(player);
                 player->CastSpell(player, SPELL_LEARN_SMELT, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF+2:
                 AddGossipItemFor(player, GOSSIP_TEXT_CONTINUE, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 22);
                 SendGossipMenuFor(player, SAY_QUEST_ACCEPTED, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+22:
                 CloseGossipMenuFor(player);
                 if (InstanceScript* instance = creature->GetInstanceScript())
                 {
                     //are 5 minutes expected? go template may have data to despawn when used at quest
                     instance->DoRespawnGameObject(instance->GetGuidData(DATA_GO_CHALICE), MINUTE * 5);
                 }
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_GO_CHALICE, Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_CONTINUE, MINUTE, SAY_QUEST_ACCEPTED, SAY_QUEST_COMPLETED_END, SendGossipMenuFor(), and SPELL_LEARN_SMELT.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp