Azerotcore-wotlk: WorldPacket Class Reference
WorldPacket Class Reference
#include <WorldPacket.h>
Public Member Functions
WorldPacket ()
WorldPacket (uint16 opcode, size_t res=200)
WorldPacket (WorldPacket &&packet) noexcept
WorldPacket (WorldPacket &&packet, TimePoint receivedTime)
WorldPacket (WorldPacket const &right)
WorldPacket & operator= (WorldPacket const &right)
WorldPacket & operator= (WorldPacket &&right) noexcept
WorldPacket (uint16 opcode, MessageBuffer &&buffer)
void Initialize (uint16 opcode, size_t newres=200)
uint16 GetOpcode () const
void SetOpcode (uint16 opcode)
TimePoint GetReceivedTime () const
Public Member Functions inherited from ByteBuffer
ByteBuffer ()
ByteBuffer (size_t reserve)
ByteBuffer (ByteBuffer &&buf) noexcept
ByteBuffer (ByteBuffer const &right)=default
ByteBuffer (MessageBuffer &&buffer)
virtual ~ByteBuffer ()=default
ByteBuffer & operator= (ByteBuffer const &right)
ByteBuffer & operator= (ByteBuffer &&right) noexcept
void clear ()
template<typename T >
void append (T value)
template<typename T >
void put (std::size_t pos, T value)
ByteBuffer & operator<< (bool value)
ByteBuffer & operator<< (uint8 value)
ByteBuffer & operator<< (uint16 value)
ByteBuffer & operator<< (uint32 value)
ByteBuffer & operator<< (uint64 value)
ByteBuffer & operator<< (int8 value)
ByteBuffer & operator<< (int16 value)
ByteBuffer & operator<< (int32 value)
ByteBuffer & operator<< (int64 value)
ByteBuffer & operator<< (float value)
ByteBuffer & operator<< (double value)
ByteBuffer & operator<< (std::string_view value)
ByteBuffer & operator<< (std::string const &str)
ByteBuffer & operator<< (char const *str)
ByteBuffer & operator>> (bool &value)
ByteBuffer & operator>> (uint8 &value)
ByteBuffer & operator>> (uint16 &value)
ByteBuffer & operator>> (uint32 &value)
ByteBuffer & operator>> (uint64 &value)
ByteBuffer & operator>> (int8 &value)
ByteBuffer & operator>> (int16 &value)
ByteBuffer & operator>> (int32 &value)
ByteBuffer & operator>> (int64 &value)
ByteBuffer & operator>> (float &value)
ByteBuffer & operator>> (double &value)
ByteBuffer & operator>> (std::string &value)
uint8 & operator[] (size_t const pos)
uint8 const & operator[] (size_t const pos) const
size_t rpos () const
size_t rpos (size_t rpos_)
void rfinish ()
size_t wpos () const
size_t wpos (size_t wpos_)
template<typename T >
void read_skip ()
void read_skip (size_t skip)
template<typename T >
T read ()
template<typename T >
T read (size_t pos) const
void read (uint8 *dest, size_t len)
template<size_t Size>
void read (std::array< uint8, Size > &arr)
void readPackGUID (uint64 &guid)
std::string ReadCString (bool requireValidUtf8=true)
uint32 ReadPackedTime ()
ByteBuffer & ReadPackedTime (uint32 &time)
uint8 * contents ()
uint8 const * contents () const
size_t size () const
bool empty () const
void resize (size_t newsize)
void reserve (size_t ressize)
void shrink_to_fit ()
void append (const char *src, size_t cnt)
template<class T >
void append (const T *src, size_t cnt)
void append (uint8 const *src, size_t cnt)
void append (ByteBuffer const &buffer)
template<size_t Size>
void append (std::array< uint8, Size > const &arr)
void appendPackXYZ (float x, float y, float z)
void appendPackGUID (uint64 guid)
void AppendPackedTime (time_t time)
void put (size_t pos, const uint8 *src, size_t cnt)
void print_storage () const
void textlike () const
void hexlike () const
template<>
void read_skip ()
template<>
void read_skip ()
Protected Attributes
uint16 m_opcode
TimePoint m_receivedTime
Protected Attributes inherited from ByteBuffer
size_t _rpos
size_t _wpos
std::vector< uint8 > _storage
Additional Inherited Members
Static Public Attributes inherited from ByteBuffer
constexpr static size_t DEFAULT_SIZE = 0x1000
Detailed Description
Definition at line 26 of file WorldPacket.h.
Constructor & Destructor Documentation
WorldPacket() [1/6]
WorldPacket::WorldPacket () inline
Definition at line 30 of file WorldPacket.h.
 : ByteBuffer(0), m_opcode(NULL_OPCODE) { }
WorldPacket() [2/6]
WorldPacket::WorldPacket (uint16 opcode, size_t res = 200) inline explicit
Definition at line 32 of file WorldPacket.h.
                                                           :
         ByteBuffer(res), m_opcode(opcode) { }
WorldPacket() [3/6]
WorldPacket::WorldPacket (WorldPacket && packet) inline noexcept
Definition at line 35 of file WorldPacket.h.
                                                :
         ByteBuffer(std::move(packet)), m_opcode(packet.m_opcode) { }
WorldPacket() [4/6]
WorldPacket::WorldPacket (WorldPacket && packet, TimePoint receivedTime) inline
Definition at line 38 of file WorldPacket.h.
                                                               :
         ByteBuffer(std::move(packet)), m_opcode(packet.m_opcode), m_receivedTime(receivedTime) { }
WorldPacket() [5/6]
WorldPacket::WorldPacket (WorldPacket const & right) inline
Definition at line 41 of file WorldPacket.h.
                                           :
         ByteBuffer(right), m_opcode(right.m_opcode) { }
WorldPacket() [6/6]
WorldPacket::WorldPacket (uint16 opcode, MessageBuffer && buffer) inline
Definition at line 66 of file WorldPacket.h.
                                                        :
         ByteBuffer(std::move(buffer)), m_opcode(opcode) { }
Member Function Documentation
GetOpcode()
uint16 WorldPacket::GetOpcode () const inline
Definition at line 76 of file WorldPacket.h.
 { return m_opcode; }
References m_opcode.
Referenced by WorldSession::DosProtection::EvaluateOpcode(), WorldSession::Handle_Deprecated(), WorldSession::Handle_EarlyProccess(), WorldSession::Handle_ServerSide(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleChannelDeclineInvite(), WorldSession::HandleChannelList(), WorldSession::HandleCharFactionOrRaceChange(), debug_commandscript::HandleDebugSendOpcodeCommand(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleMovementOpcodes(), PacketLog::LogPacket(), WorldSession::LogUnexpectedOpcode(), WorldSession::LogUnprocessedTail(), MapSessionFilter::Process(), WorldSessionFilter::Process(), WorldSocket::ReadDataHandler(), WorldSession::SendPacket(), WorldSocket::SendPacketAndLogOpcode(), WorldSocket::Update(), and WorldSession::Update().
GetReceivedTime()
TimePoint WorldPacket::GetReceivedTime () const inline
Definition at line 79 of file WorldPacket.h.
 { return m_receivedTime; }
References m_receivedTime.
Referenced by WorldSession::HandleTimeSyncResp().
Initialize()
void WorldPacket::Initialize (uint16 opcode, size_t newres = 200) inline
Definition at line 69 of file WorldPacket.h.
     {
         clear();
         _storage.reserve(newres);
         m_opcode = opcode;
     }
References ByteBuffer::_storage, ByteBuffer::clear(), and m_opcode.
Referenced by AddonHandler::BuildAddonPacket(), BattlegroundMgr::BuildBattlegroundListPacket(), BattlegroundMgr::BuildBattlegroundStatusPacket(), ChatHandler::BuildChatPacket(), Unit::BuildCooldownPacket(), BattlegroundMgr::BuildGroupJoinedBattlegroundPacket(), Unit::BuildHeartBeatMsg(), WorldSession::BuildPartyMemberStatsChangedPacket(), BattlegroundMgr::BuildPlayerJoinedBattlegroundPacket(), BattlegroundMgr::BuildPlayerLeftBattlegroundPacket(), BattlegroundMgr::BuildPlaySoundPacket(), BattlegroundMgr::BuildPvpLogDataPacket(), BattlegroundMgr::BuildUpdateWorldStatePacket(), ArenaSpectator::CreatePacket(), Group::Disband(), Unit::Dismount(), Battlefield::DoPlaySoundToAll(), Player::DuelComplete(), Spell::EffectBind(), AuraEffect::HandleAuraSetVehicle(), WorldSession::HandleLogoutCancelOpcode(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleReadItem(), WorldSession::HandleTurnInPetitionOpcode(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), CreatureTemplate::InitializeQueryData(), ItemTemplate::InitializeQueryData(), Quest::InitializeQueryData(), SocialMgr::MakeFriendStatusPacket(), Channel::MakeNotifyPacket(), ChannelMgr::MakeNotOnPacket(), Unit::Mount(), Acore::EmoteChatBuilder::operator()(), Group::RemoveMember(), Player::SendComboPoints(), ReputationMgr::SendForceReactions(), Player::SendInitialPacketsBeforeAddToMap(), Spell::SendInterrupted(), Player::SendSavedInstances(), WorldSession::SendTradeStatus(), Player::SetCanFly(), Creature::SetCanFly(), Player::SetDisableGravity(), Creature::SetDisableGravity(), Player::SetFeatherFall(), Creature::SetFeatherFall(), Creature::SetHover(), Player::SetHover(), Player::SetMovement(), Unit::SetSpeed(), Player::SetWaterWalking(), and Creature::SetWaterWalking().
operator=() [1/2]
WorldPacket& WorldPacket::operator= (WorldPacket && right) inline noexcept
Definition at line 55 of file WorldPacket.h.
     {
         if (this != &right)
         {
             m_opcode = right.m_opcode;
             ByteBuffer::operator=(std::move(right));
         }
         return *this;
     }
References m_opcode, and ByteBuffer::operator=().
operator=() [2/2]
WorldPacket& WorldPacket::operator= (WorldPacket const & right) inline
Definition at line 44 of file WorldPacket.h.
     {
         if (this != &right)
         {
             m_opcode = right.m_opcode;
             ByteBuffer::operator=(right);
         }
         return *this;
     }
References m_opcode, and ByteBuffer::operator=().
SetOpcode()
void WorldPacket::SetOpcode (uint16 opcode) inline
Definition at line 77 of file WorldPacket.h.
 { m_opcode = opcode; }
References m_opcode.
Referenced by UpdateData::BuildPacket(), WorldSession::HandleClientCastFlags(), gm_commandscript::HandleGMFlyCommand(), WorldSession::HandleUpdateMissileTrajectory(), Movement::MoveSplineInit::Launch(), WorldSession::SendCalendarRaidLockout(), and Movement::MoveSplineInit::Stop().
Member Data Documentation
m_opcode
uint16 WorldPacket::m_opcode protected
Definition at line 82 of file WorldPacket.h.
Referenced by GetOpcode(), Initialize(), operator=(), and SetOpcode().
m_receivedTime
TimePoint WorldPacket::m_receivedTime protected
Definition at line 83 of file WorldPacket.h.
Referenced by GetReceivedTime().
The documentation for this class was generated from the following file:
src/server/game/Server/WorldPacket.h