Azerotcore-wotlk: go_dragonflayer_cage Class Reference
go_dragonflayer_cage Class Reference
Public Member Functions
go_dragonflayer_cage ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1449 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_dragonflayer_cage()
go_dragonflayer_cage::go_dragonflayer_cage () inline
Definition at line 1452 of file go_scripts.cpp.
 : GameObjectScript("go_dragonflayer_cage") { }
Member Function Documentation
OnGossipHello()
bool go_dragonflayer_cage::OnGossipHello (Player * player, GameObject * go) inline override virtual
Todo:
prisoner should help player for a short period of time
Reimplemented from GameObjectScript.
Definition at line 1454 of file go_scripts.cpp.
     {
         go->UseDoorOrButton();
         if (player->GetQuestStatus(QUEST_PRISONERS_OF_WYRMSKULL) != QUEST_STATUS_INCOMPLETE)
             return true;
         Creature* pPrisoner = go->FindNearestCreature(NPC_PRISONER_PRIEST, 2.0f);
         if (!pPrisoner)
         {
             pPrisoner = go->FindNearestCreature(NPC_PRISONER_MAGE, 2.0f);
             if (!pPrisoner)
             {
                 pPrisoner = go->FindNearestCreature(NPC_PRISONER_WARRIOR, 2.0f);
                 if (!pPrisoner)
                     pPrisoner = go->FindNearestCreature(NPC_PRISONER_PALADIN, 2.0f);
             }
         }
         if (!pPrisoner || !pPrisoner->IsAlive())
             return true;
         Quest const* qInfo = sObjectMgr->GetQuestTemplate(QUEST_PRISONERS_OF_WYRMSKULL);
         if (qInfo)
         {
             player->KilledMonsterCredit(qInfo->RequiredNpcOrGo[0]);
             pPrisoner->DisappearAndDie();
         }
         return true;
     }
References Creature::DisappearAndDie(), WorldObject::FindNearestCreature(), Player::GetQuestStatus(), Unit::IsAlive(), Player::KilledMonsterCredit(), NPC_PRISONER_MAGE, NPC_PRISONER_PALADIN, NPC_PRISONER_PRIEST, NPC_PRISONER_WARRIOR, QUEST_PRISONERS_OF_WYRMSKULL, QUEST_STATUS_INCOMPLETE, Quest::RequiredNpcOrGo, sObjectMgr, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp