Azerotcore-wotlk: deps/mysqllite/mysys/my_once.c File Reference
my_once.c File Reference
#include "mysys_priv.h"
#include "my_static.h"
#include "mysys_err.h"
#include <m_string.h>
Functions
void * my_once_alloc (size_t Size, myf MyFlags)
char * my_once_strdup (const char *src, myf myflags)
void * my_once_memdup (const void *src, size_t len, myf myflags)
void my_once_free (void)
Function Documentation
my_once_alloc()
void* my_once_alloc (size_t Size, myf MyFlags)
Definition at line 36 of file my_once.c.
 {
   size_t get_size, max_left;
   uchar* point;
   reg1 USED_MEM *next;
   reg2 USED_MEM **prev;
   Size= ALIGN_SIZE(Size);
   prev= &my_once_root_block;
   max_left=0;
   for (next=my_once_root_block ; next && next->left < Size ; next= next->next)
   {
     if (next->left > max_left)
       max_left=next->left;
     prev= &next->next;
   }
   if (! next)
   {                     /* Time to alloc new block */
     get_size= Size+ALIGN_SIZE(sizeof(USED_MEM));
     if (max_left*4 < my_once_extra && get_size < my_once_extra)
       get_size=my_once_extra;           /* Normal alloc */
     if ((next = (USED_MEM*) malloc(get_size)) == 0)
     {
       my_errno=errno;
       if (MyFlags & (MY_FAE+MY_WME))
     my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG),get_size);
       return((uchar*) 0);
     }
     DBUG_PRINT("test",("my_once_malloc %lu byte malloced", (ulong) get_size));
     next->next= 0;
     next->size= get_size;
     next->left= get_size-ALIGN_SIZE(sizeof(USED_MEM));
     *prev=next;
   }
   point= (uchar*) ((char*) next+ (next->size-next->left));
   next->left-= Size;
   if (MyFlags & MY_ZEROFILL)
     bzero(point, Size);
   return((void*) point);
 } /* my_once_alloc */
References ALIGN_SIZE, bzero, DBUG_PRINT, EE_OUTOFMEMORY, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_once_extra, my_once_root_block, MY_WME, MY_ZEROFILL, MYF, next(), prev(), reg1, reg2, and Acore::Size().
Referenced by add_collation(), cs_alloc(), init_state_maps(), my_once_memdup(), and my_once_strdup().
my_once_free()
void my_once_free (void)
Definition at line 106 of file my_once.c.
 {
   reg1 USED_MEM *next,*old;
   DBUG_ENTER("my_once_free");
   for (next=my_once_root_block ; next ; )
   {
     old=next; next= next->next ;
     free((uchar*) old);
   }
   my_once_root_block=0;
   DBUG_VOID_RETURN;
 } /* my_once_free */
References DBUG_ENTER, DBUG_VOID_RETURN, my_once_root_block, next(), and reg1.
Referenced by my_end().
my_once_memdup()
void* my_once_memdup (const void * src, size_t len, myf myflags)
Definition at line 90 of file my_once.c.
 {
   uchar *dst= my_once_alloc(len, myflags);
   if (dst)
     memcpy(dst, src, len);
   return dst;
 }
References memcpy, and my_once_alloc().
Referenced by cs_copy_data().
my_once_strdup()
char* my_once_strdup (const char * src, myf myflags)
Definition at line 80 of file my_once.c.
 {
   size_t len= strlen(src)+1;
   uchar *dst= my_once_alloc(len, myflags);
   if (dst)
     memcpy(dst, src, len);
   return (char*) dst;
 }
References memcpy, and my_once_alloc().
Referenced by add_collation(), and cs_copy_data().