Azerotcore-wotlk: G3D::Token Class Reference
G3D::Token Class Reference
#include <TextInput.h>
Public Types
enum ExtendedType {
DOUBLE_QUOTED_TYPE , SINGLE_QUOTED_TYPE , SYMBOL_TYPE , FLOATING_POINT_TYPE ,
INTEGER_TYPE , BOOLEAN_TYPE , LINE_COMMENT_TYPE , BLOCK_COMMENT_TYPE ,
NEWLINE_TYPE , END_TYPE
}
enum Type {
STRING = DOUBLE_QUOTED_TYPE , SYMBOL = SYMBOL_TYPE , NUMBER = FLOATING_POINT_TYPE , BOOLEAN = BOOLEAN_TYPE ,
COMMENT = LINE_COMMENT_TYPE , NEWLINE = NEWLINE_TYPE , END = END_TYPE
}
Public Member Functions
Token ()
Token (Type t, ExtendedType e, const std::string &s, int L, int c, uint64 byte)
Token (Type t, ExtendedType e, const std::string &s, bool b, int L, int c, uint64 byte)
Type type () const
ExtendedType extendedType () const
const std::string & string () const
bool boolean () const
int line () const
int character () const
uint64 bytePosition () const
double number () const
Private Attributes
std::string _string
bool _bool
int _line
int _character
uint64 _bytePosition
Type _type
ExtendedType _extendedType
Friends
class TextInput
Detailed Description
For use with TextInput.
Definition at line 34 of file TextInput.h.
Member Enumeration Documentation
ExtendedType
enum G3D::Token::ExtendedType
More detailed type information than Type.
Enumerator
DOUBLE_QUOTED_TYPE
SINGLE_QUOTED_TYPE
SYMBOL_TYPE
FLOATING_POINT_TYPE
INTEGER_TYPE
BOOLEAN_TYPE
LINE_COMMENT_TYPE
BLOCK_COMMENT_TYPE
NEWLINE_TYPE
END_TYPE
Definition at line 40 of file TextInput.h.
                       {
       DOUBLE_QUOTED_TYPE,
       SINGLE_QUOTED_TYPE,
       SYMBOL_TYPE,
       FLOATING_POINT_TYPE,
       INTEGER_TYPE,
       BOOLEAN_TYPE,
       LINE_COMMENT_TYPE,
       BLOCK_COMMENT_TYPE,
       NEWLINE_TYPE,
       END_TYPE
     };
Type
enum G3D::Token::Type
Strings are enclosed in quotes, symbols are not.
Enumerator
STRING
SYMBOL
NUMBER
BOOLEAN
COMMENT
NEWLINE
END
Definition at line 56 of file TextInput.h.
               {
       STRING  = DOUBLE_QUOTED_TYPE,
       SYMBOL  = SYMBOL_TYPE,
       NUMBER  = FLOATING_POINT_TYPE,
       BOOLEAN = BOOLEAN_TYPE,
       COMMENT = LINE_COMMENT_TYPE,
       NEWLINE = NEWLINE_TYPE,
       END     = END_TYPE
     };
Constructor & Destructor Documentation
Token() [1/3]
G3D::Token::Token () inline
Definition at line 85 of file TextInput.h.
             :
         _string(""),
         _bool(false),
         _line(0),
         _character(0),
         _bytePosition(0),
         _type(END),
         _extendedType(END_TYPE) {}
Token() [2/3]
G3D::Token::Token (Type t, ExtendedType e, const std::string & s, int L, int c, uint64 byte) inline
Definition at line 94 of file TextInput.h.
         : _string(s), _bool(false), _line(L), _character(c), _bytePosition(byte), _type(t), _extendedType(e) {}
Token() [3/3]
G3D::Token::Token (Type t, ExtendedType e, const std::string & s, bool b, int L, int c, uint64 byte) inline
Definition at line 97 of file TextInput.h.
         : _string(s), _bool(b), _line(L), _character(c), _bytePosition(byte), _type(t), _extendedType(e) {}
Member Function Documentation
boolean()
bool G3D::Token::boolean () const inline
Definition at line 117 of file TextInput.h.
{
         return _bool;
     }
References _bool.
Referenced by G3D::Any::deserialize(), and G3D::TextInput::readBoolean().
bytePosition()
uint64 G3D::Token::bytePosition () const inline
Number of bytes from the beginning of the buffer that this token was parsed from. Begins at 0
Definition at line 139 of file TextInput.h.
{
         return _bytePosition;
     }
References _bytePosition.
Referenced by G3D::TextInput::readUntilDelimiterAsString().
character()
int G3D::Token::character () const inline
Starting character position in the input line from which this token was parsed. Starts at 1.
Definition at line 133 of file TextInput.h.
{
         return _character;
     }
References _character.
Referenced by G3D::Any::deserialize(), G3D::Any::deserializeBody(), G3D::Any::deserializeName(), G3D::TextInput::peekCharacterNumber(), G3D::TextInput::readBoolean(), G3D::TextInput::readComment(), G3D::TextInput::readCommentToken(), G3D::TextInput::readInteger(), G3D::TextInput::readNewline(), G3D::TextInput::readNewlineToken(), G3D::TextInput::readNumber(), G3D::TextInput::readString(), G3D::TextInput::readStringToken(), G3D::TextInput::readSymbol(), G3D::TextInput::readSymbolToken(), G3D::TextInput::readUntilDelimiterAsString(), G3D::Any::readUntilSeparatorOrClose(), and G3D::Any::Source::set().
extendedType()
ExtendedType G3D::Token::extendedType () const inline
Definition at line 104 of file TextInput.h.
{
         return _extendedType;
     }
References _extendedType.
Referenced by G3D::AnyVal::deserialize().
line()
int G3D::Token::line () const inline
Starting line of the input from which this token was parsed. Starts at 1.
Definition at line 125 of file TextInput.h.
                      {
         return _line;
     }
References _line.
Referenced by G3D::Any::deserialize(), G3D::Any::deserializeBody(), G3D::Any::deserializeName(), G3D::TextInput::nextToken(), G3D::TextInput::peekLineNumber(), G3D::TextInput::readBoolean(), G3D::TextInput::readComment(), G3D::TextInput::readCommentToken(), G3D::TextInput::readInteger(), G3D::TextInput::readNewline(), G3D::TextInput::readNewlineToken(), G3D::TextInput::readNumber(), G3D::TextInput::readString(), G3D::TextInput::readStringToken(), G3D::TextInput::readSymbol(), G3D::TextInput::readSymbolToken(), G3D::TextInput::readUntilDelimiterAsString(), G3D::Any::readUntilSeparatorOrClose(), and G3D::Any::Source::set().
number()
double G3D::Token::number () const
Return the numeric value for a number type, or zero if this is not a number type.
Definition at line 33 of file TextInput.cpp.
{
     if (_type == NUMBER) {
         return TextInput::parseNumber(_string);
     } else {
         return 0.0;
     }
 }
References _string, _type, NUMBER, and G3D::TextInput::parseNumber().
Referenced by mpq::File::__repr__(), mpq::File::__str__(), G3D::Any::deserialize(), G3D::TextInput::readInteger(), and G3D::TextInput::readNumber().
string()
const std::string& G3D::Token::string () const inline
The value of a single or double quote string (not including the quotes), the name of a symbol, or the exact textual representation of a number as parsed from the input.
Definition at line 113 of file TextInput.h.
{
         return _string;
     }
References _string.
Referenced by G3D::atClose(), G3D::AnyVal::deserialize(), G3D::XML::deserialize(), G3D::Any::deserialize(), G3D::Any::deserializeBody(), G3D::Any::deserializeComment(), G3D::Any::deserializeName(), G3D::findType(), and G3D::Any::readUntilSeparatorOrClose().
type()
Type G3D::Token::type () const inline
Definition at line 100 of file TextInput.h.
                       {
         return _type;
     }
References _type.
Referenced by G3D::atClose(), G3D::AnyVal::deserialize(), G3D::XML::deserialize(), G3D::Any::deserialize(), G3D::Any::deserializeBody(), G3D::Any::deserializeComment(), G3D::Any::deserializeName(), G3D::findType(), G3D::TextInput::readSignificant(), and G3D::Any::readUntilSeparatorOrClose().
Friends And Related Function Documentation
TextInput
friend class TextInput friend
Definition at line 68 of file TextInput.h.
Member Data Documentation
_bool
bool G3D::Token::_bool private
Definition at line 76 of file TextInput.h.
Referenced by boolean(), and G3D::TextInput::nextToken().
_bytePosition
uint64 G3D::Token::_bytePosition private
Definition at line 79 of file TextInput.h.
Referenced by bytePosition(), and G3D::TextInput::nextToken().
_character
int G3D::Token::_character private
Definition at line 78 of file TextInput.h.
Referenced by character(), G3D::TextInput::nextToken(), G3D::TextInput::readInteger(), and G3D::TextInput::readNumber().
_extendedType
ExtendedType G3D::Token::_extendedType private
Definition at line 81 of file TextInput.h.
Referenced by extendedType(), G3D::TextInput::nextToken(), G3D::TextInput::parseQuotedString(), and G3D::TextInput::readInteger().
_line
int G3D::Token::_line private
Definition at line 77 of file TextInput.h.
Referenced by line(), and G3D::TextInput::nextToken().
_string
std::string G3D::Token::_string private
Holds the actual value, which might be any type. If a number, it will be parsed at runtime.
Definition at line 74 of file TextInput.h.
Referenced by G3D::TextInput::nextToken(), number(), G3D::TextInput::parseQuotedString(), G3D::TextInput::readComment(), G3D::TextInput::readInteger(), G3D::TextInput::readNewline(), G3D::TextInput::readNumber(), G3D::TextInput::readString(), G3D::TextInput::readSymbol(), and string().
_type
Type G3D::Token::_type private
Definition at line 80 of file TextInput.h.
Referenced by G3D::TextInput::nextToken(), number(), G3D::TextInput::parseQuotedString(), G3D::TextInput::readBoolean(), G3D::TextInput::readCommentToken(), G3D::TextInput::readInteger(), G3D::TextInput::readNewlineToken(), G3D::TextInput::readNumber(), G3D::TextInput::readStringToken(), G3D::TextInput::readSymbolToken(), and type().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/TextInput.h
deps/g3dlite/source/TextInput.cpp