Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/cache_bin.h File Reference
cache_bin.h File Reference
#include "jemalloc/internal/ql.h"
Classes
struct cache_bin_stats_s
struct cache_bin_info_s
struct cache_bin_s
struct cache_bin_array_descriptor_s
Typedefs
typedef int32_t cache_bin_sz_t
typedef struct cache_bin_stats_s cache_bin_stats_t
typedef struct cache_bin_info_s cache_bin_info_t
typedef struct cache_bin_s cache_bin_t
typedef struct cache_bin_array_descriptor_s cache_bin_array_descriptor_t
Functions
static void cache_bin_array_descriptor_init (cache_bin_array_descriptor_t *descriptor, cache_bin_t *bins_small, cache_bin_t *bins_large)
JEMALLOC_ALWAYS_INLINE void * cache_bin_alloc_easy (cache_bin_t *bin, bool *success)
JEMALLOC_ALWAYS_INLINE bool cache_bin_dalloc_easy (cache_bin_t *bin, cache_bin_info_t *bin_info, void *ptr)
Typedef Documentation
cache_bin_array_descriptor_t
typedef struct cache_bin_array_descriptor_s cache_bin_array_descriptor_t
Definition at line 22 of file cache_bin.h.
cache_bin_info_t
typedef struct cache_bin_info_s cache_bin_info_t
Definition at line 22 of file cache_bin.h.
cache_bin_stats_t
typedef struct cache_bin_stats_s cache_bin_stats_t
Definition at line 22 of file cache_bin.h.
cache_bin_sz_t
typedef int32_t cache_bin_sz_t
Definition at line 22 of file cache_bin.h.
cache_bin_t
typedef struct cache_bin_s cache_bin_t
Definition at line 22 of file cache_bin.h.
Function Documentation
cache_bin_alloc_easy()
JEMALLOC_ALWAYS_INLINE void* cache_bin_alloc_easy (cache_bin_t * bin, bool * success)
Definition at line 88 of file cache_bin.h.
{
     void *ret;
     bin->ncached--;
     /*
      * Check for both bin->ncached == 0 and ncached < low_water
      * in a single branch.
      */
     if (unlikely(bin->ncached <= bin->low_water)) {
         bin->low_water = bin->ncached;
         if (bin->ncached == -1) {
             bin->ncached = 0;
             *success = false;
             return NULL;
         }
     }
     /*
      * success (instead of ret) should be checked upon the return of this
      * function.  We avoid checking (ret == NULL) because there is never a
      * null stored on the avail stack (which is unknown to the compiler),
      * and eagerly checking ret would cause pipeline stall (waiting for the
      * cacheline).
      */
     *success = true;
     ret = *(bin->avail - (bin->ncached + 1));
     return ret;
 }
References cache_bin_s::avail, cache_bin_s::low_water, cache_bin_s::ncached, NULL, ret, and unlikely.
Referenced by JEMALLOC_ATTR(), tcache_alloc_large(), tcache_alloc_small(), and tcache_alloc_small_hard().
cache_bin_array_descriptor_init()
static void cache_bin_array_descriptor_init (cache_bin_array_descriptor_t * descriptor, cache_bin_t * bins_small, cache_bin_t * bins_large) inline static
Definition at line 80 of file cache_bin.h.
{
     ql_elm_new(descriptor, link);
     descriptor->bins_small = bins_small;
     descriptor->bins_large = bins_large;
 }
References cache_bin_array_descriptor_s::bins_large, cache_bin_array_descriptor_s::bins_small, and ql_elm_new.
Referenced by arena_postfork_child(), and tcache_arena_associate().
cache_bin_dalloc_easy()
JEMALLOC_ALWAYS_INLINE bool cache_bin_dalloc_easy (cache_bin_t * bin, cache_bin_info_t * bin_info, void * ptr)
Definition at line 120 of file cache_bin.h.
{
     if (unlikely(bin->ncached == bin_info->ncached_max)) {
         return false;
     }
     assert(bin->ncached < bin_info->ncached_max);
     bin->ncached++;
     *(bin->avail - bin->ncached) = ptr;
     return true;
 }
References assert(), cache_bin_s::avail, cache_bin_s::ncached, cache_bin_info_s::ncached_max, ptr(), and unlikely.
Referenced by free_fastpath(), and tcache_dalloc_small().