Azerotcore-wotlk: RotateMovementGenerator Class Reference
RotateMovementGenerator Class Reference
#include <IdleMovementGenerator.h>
Public Member Functions
RotateMovementGenerator (uint32 time, RotateDirection direction)
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *owner) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
uint32 m_duration
uint32 m_maxDuration
RotateDirection m_direction
Detailed Description
Definition at line 35 of file IdleMovementGenerator.h.
Constructor & Destructor Documentation
RotateMovementGenerator()
RotateMovementGenerator::RotateMovementGenerator (uint32 time, RotateDirection direction) inline explicit
Definition at line 38 of file IdleMovementGenerator.h.
 : m_duration(time), m_maxDuration(time), m_direction(direction) {}
Member Function Documentation
Finalize()
void RotateMovementGenerator::Finalize (Unit * unit) override virtual
Implements MovementGenerator.
Definition at line 74 of file IdleMovementGenerator.cpp.
 {
     unit->ClearUnitState(UNIT_STATE_ROTATING);
     if (unit->GetTypeId() == TYPEID_UNIT)
         unit->ToCreature()->AI()->MovementInform(ROTATE_MOTION_TYPE, 0);
 }
References Creature::AI(), Unit::ClearUnitState(), Object::GetTypeId(), CreatureAI::MovementInform(), ROTATE_MOTION_TYPE, Object::ToCreature(), TYPEID_UNIT, and UNIT_STATE_ROTATING.
GetMovementGeneratorType()
MovementGeneratorType RotateMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
Definition at line 44 of file IdleMovementGenerator.h.
 { return ROTATE_MOTION_TYPE; }
References ROTATE_MOTION_TYPE.
Initialize()
void RotateMovementGenerator::Initialize (Unit * owner) override virtual
Implements MovementGenerator.
Definition at line 37 of file IdleMovementGenerator.cpp.
 {
     if (!owner->IsStopped())
         owner->StopMoving();
     if (owner->GetVictim())
         owner->SetInFront(owner->GetVictim());
     owner->AddUnitState(UNIT_STATE_ROTATING);
     owner->AttackStop();
 }
References Unit::AddUnitState(), Unit::AttackStop(), Unit::GetVictim(), Unit::IsStopped(), Unit::SetInFront(), Unit::StopMoving(), and UNIT_STATE_ROTATING.
Referenced by Reset().
Reset()
void RotateMovementGenerator::Reset (Unit * owner) inline override virtual
Implements MovementGenerator.
Definition at line 42 of file IdleMovementGenerator.h.
 { Initialize(owner); }
References Initialize().
Update()
bool RotateMovementGenerator::Update (Unit * owner, uint32 diff) override virtual
Implements MovementGenerator.
Definition at line 50 of file IdleMovementGenerator.cpp.
 {
     float angle = owner->GetOrientation();
     if (m_direction == ROTATE_DIRECTION_LEFT)
     {
         angle += (float)diff * static_cast<float>(M_PI * 2) / m_maxDuration;
         while (angle >= static_cast<float>(M_PI * 2)) angle -= static_cast<float>(M_PI * 2);
     }
     else
     {
         angle -= (float)diff * static_cast<float>(M_PI * 2) / m_maxDuration;
         while (angle < 0) angle += static_cast<float>(M_PI * 2);
     }
     owner->SetFacingTo(angle);
     if (m_duration > diff)
         m_duration -= diff;
     else
         return false;
     return true;
 }
References diff(), Position::GetOrientation(), m_direction, m_duration, m_maxDuration, M_PI, ROTATE_DIRECTION_LEFT, and Unit::SetFacingTo().
Member Data Documentation
m_direction
RotateDirection RotateMovementGenerator::m_direction private
Definition at line 48 of file IdleMovementGenerator.h.
Referenced by Update().
m_duration
uint32 RotateMovementGenerator::m_duration private
Definition at line 47 of file IdleMovementGenerator.h.
Referenced by Update().
m_maxDuration
uint32 RotateMovementGenerator::m_maxDuration private
Definition at line 47 of file IdleMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.h
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.cpp