Azerotcore-wotlk: adt_MH2O Class Reference
adt_MH2O Class Reference
#include <adt.h>
Classes
struct adt_LIQUID
Public Member Functions
bool prepareLoadedData ()
adt_liquid_header * getLiquidData (int x, int y)
float * getLiquidHeightMap (adt_liquid_header *h)
uint8 * getLiquidLightMap (adt_liquid_header *h)
uint32 * getLiquidFullLightMap (adt_liquid_header *h)
uint64 getLiquidShowMap (adt_liquid_header *h)
Public Attributes
union {
uint32 fcc
char fcc_txt [4]
};
uint32 size
struct adt_MH2O::adt_LIQUID liquid [ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
Detailed Description
Definition at line 200 of file adt.h.
Member Function Documentation
getLiquidData()
adt_liquid_header* adt_MH2O::getLiquidData (int x, int y) inline
Definition at line 219 of file adt.h.
     {
         if (liquid[x][y].used && liquid[x][y].offsData1)
             return (adt_liquid_header*)((uint8*)this + 8 + liquid[x][y].offsData1);
         return nullptr;
     }
References liquid, G3D::x, and G3D::y.
Referenced by ConvertADT().
getLiquidFullLightMap()
uint32* adt_MH2O::getLiquidFullLightMap (adt_liquid_header * h) inline
Definition at line 248 of file adt.h.
     {
         if (!(h->formatFlags & ADT_LIQUID_HEADER_FULL_LIGHT))
             return nullptr;
         if (h->offsData2b)
         {
             if (h->formatFlags & ADT_LIQUID_HEADER_NO_HIGHT)
                 return (uint32*)((uint8*)this + 8 + h->offsData2b);
             return (uint32*)((uint8*)this + 8 + h->offsData2b + (h->width + 1) * (h->height + 1) * 4);
         }
         return nullptr;
     }
References ADT_LIQUID_HEADER_FULL_LIGHT, ADT_LIQUID_HEADER_NO_HIGHT, adt_liquid_header::formatFlags, adt_liquid_header::height, adt_liquid_header::offsData2b, and adt_liquid_header::width.
getLiquidHeightMap()
float* adt_MH2O::getLiquidHeightMap (adt_liquid_header * h) inline
Definition at line 226 of file adt.h.
     {
         if (h->formatFlags & ADT_LIQUID_HEADER_NO_HIGHT)
             return nullptr;
         if (h->offsData2b)
             return (float*)((uint8*)this + 8 + h->offsData2b);
         return nullptr;
     }
References ADT_LIQUID_HEADER_NO_HIGHT, adt_liquid_header::formatFlags, and adt_liquid_header::offsData2b.
Referenced by ConvertADT().
getLiquidLightMap()
uint8* adt_MH2O::getLiquidLightMap (adt_liquid_header * h) inline
Definition at line 235 of file adt.h.
     {
         if (h->formatFlags & ADT_LIQUID_HEADER_FULL_LIGHT)
             return nullptr;
         if (h->offsData2b)
         {
             if (h->formatFlags & ADT_LIQUID_HEADER_NO_HIGHT)
                 return (uint8*)((uint8*)this + 8 + h->offsData2b);
             return (uint8*)((uint8*)this + 8 + h->offsData2b + (h->width + 1) * (h->height + 1) * 4);
         }
         return nullptr;
     }
References ADT_LIQUID_HEADER_FULL_LIGHT, ADT_LIQUID_HEADER_NO_HIGHT, adt_liquid_header::formatFlags, adt_liquid_header::height, adt_liquid_header::offsData2b, and adt_liquid_header::width.
Referenced by ConvertADT().
getLiquidShowMap()
uint64 adt_MH2O::getLiquidShowMap (adt_liquid_header * h) inline
Definition at line 261 of file adt.h.
     {
         if (h->offsData2a)
             return *((uint64*)((uint8*)this + 8 + h->offsData2a));
         else
             return 0xFFFFFFFFFFFFFFFFuLL;
     }
References adt_liquid_header::offsData2a.
Referenced by ConvertADT().
prepareLoadedData()
bool adt_MH2O::prepareLoadedData ()
Definition at line 115 of file adt.cpp.
 {
     if (fcc != MH2OMagic.fcc)
         return false;
     // Check liquid data
     //    for (int i=0; i<ADT_CELLS_PER_GRID;i++)
     //        for (int j=0; j<ADT_CELLS_PER_GRID;j++)
     return true;
 }
References fcc, u_map_fcc::fcc, and MH2OMagic.
Member Data Documentation
union { ... }
fcc
uint32 adt_MH2O::fcc
Definition at line 205 of file adt.h.
Referenced by prepareLoadedData().
fcc_txt
char adt_MH2O::fcc_txt[4]
Definition at line 206 of file adt.h.
liquid
struct adt_MH2O::adt_LIQUID adt_MH2O::liquid[ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
Referenced by getLiquidData().
size
uint32 adt_MH2O::size
Definition at line 208 of file adt.h.
The documentation for this class was generated from the following files:
src/tools/map_extractor/adt.h
src/tools/map_extractor/adt.cpp