Azerotcore-wotlk: deps/mysqllite/include/internal/violite.h File Reference
violite.h File Reference
#include "my_net.h"
Classes
struct st_vio
Macros
#define VIO_LOCALHOST 1 /* a localhost connection */
#define VIO_BUFFERED_READ 2 /* use buffered read */
#define VIO_READ_BUFFER_SIZE 16384 /* size of read buffer */
#define HANDLE void *
#define vio_delete(vio) (vio)->viodelete(vio)
#define vio_errno(vio) (vio)->vioerrno(vio)
#define vio_read(vio, buf, size) ((vio)->read)(vio,buf,size)
#define vio_write(vio, buf, size) ((vio)->write)(vio, buf, size)
#define vio_blocking(vio, set_blocking_mode, old_mode) (vio)->vioblocking(vio, set_blocking_mode, old_mode)
#define vio_is_blocking(vio) (vio)->is_blocking(vio)
#define vio_fastsend(vio) (vio)->fastsend(vio)
#define vio_keepalive(vio, set_keep_alive) (vio)->viokeepalive(vio, set_keep_alive)
#define vio_should_retry(vio) (vio)->should_retry(vio)
#define vio_was_interrupted(vio) (vio)->was_interrupted(vio)
#define vio_close(vio) ((vio)->vioclose)(vio)
#define vio_peer_addr(vio, buf, prt, buflen) (vio)->peer_addr(vio, buf, prt, buflen)
#define vio_timeout(vio, which, seconds) (vio)->timeout(vio, which, seconds)
#define vio_poll_read(vio, timeout) (vio)->poll_read(vio, timeout)
#define vio_is_connected(vio) (vio)->is_connected(vio)
Enumerations
enum enum_vio_type {
VIO_CLOSED , VIO_TYPE_TCPIP , VIO_TYPE_SOCKET , VIO_TYPE_NAMEDPIPE ,
VIO_TYPE_SSL , VIO_TYPE_SHARED_MEMORY
}
enum SSL_type {
SSL_TYPE_NOT_SPECIFIED = -1 , SSL_TYPE_NONE , SSL_TYPE_ANY , SSL_TYPE_X509 ,
SSL_TYPE_SPECIFIED
}
Functions
Vio * vio_new (my_socket sd, enum enum_vio_type type, uint flags)
void vio_delete (Vio *vio)
int vio_close (Vio *vio)
void vio_reset (Vio *vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags)
size_t vio_read (Vio *vio, uchar *buf, size_t size)
size_t vio_read_buff (Vio *vio, uchar *buf, size_t size)
size_t vio_write (Vio *vio, const uchar *buf, size_t size)
int vio_blocking (Vio *vio, my_bool onoff, my_bool *old_mode)
my_bool vio_is_blocking (Vio *vio)
int vio_fastsend (Vio *vio)
int vio_keepalive (Vio *vio, my_bool onoff)
my_bool vio_should_retry (Vio *vio)
my_bool vio_was_interrupted (Vio *vio)
const char * vio_description (Vio *vio)
enum enum_vio_type vio_type (Vio *vio)
int vio_errno (Vio *vio)
my_socket vio_fd (Vio *vio)
my_bool vio_peer_addr (Vio *vio, char *buf, uint16 *port, size_t buflen)
my_bool vio_poll_read (Vio *vio, uint timeout)
my_bool vio_is_connected (Vio *vio)
ssize_t vio_pending (Vio *vio)
my_bool vio_get_normalized_ip_string (const struct sockaddr *addr, int addr_length, char *ip_string, size_t ip_string_size)
int vio_getnameinfo (const struct sockaddr *sa, char *hostname, size_t hostname_size, char *port, size_t port_size, int flags)
void vio_end (void)
Macro Definition Documentation
HANDLE
#define HANDLE void *
Definition at line 59 of file violite.h.
vio_blocking
#define vio_blocking (vio , set_blocking_mode, old_mode) (vio)->vioblocking(vio, set_blocking_mode, old_mode)
Definition at line 161 of file violite.h.
VIO_BUFFERED_READ
#define VIO_BUFFERED_READ 2 /* use buffered read */
Definition at line 45 of file violite.h.
vio_close
#define vio_close (vio) ((vio)->vioclose)(vio)
Definition at line 168 of file violite.h.
vio_delete
#define vio_delete (vio) (vio)->viodelete(vio)
Definition at line 157 of file violite.h.
vio_errno
#define vio_errno (vio) (vio)->vioerrno(vio)
Definition at line 158 of file violite.h.
vio_fastsend
#define vio_fastsend (vio) (vio)->fastsend(vio)
Definition at line 164 of file violite.h.
vio_is_blocking
#define vio_is_blocking (vio) (vio)->is_blocking(vio)
Definition at line 163 of file violite.h.
vio_is_connected
#define vio_is_connected (vio) (vio)->is_connected(vio)
Definition at line 172 of file violite.h.
vio_keepalive
#define vio_keepalive (vio, set_keep_alive) (vio)->viokeepalive(vio, set_keep_alive)
Definition at line 165 of file violite.h.
VIO_LOCALHOST
#define VIO_LOCALHOST 1 /* a localhost connection */
Definition at line 44 of file violite.h.
vio_peer_addr
#define vio_peer_addr (vio, buf, prt, buflen) (vio)->peer_addr(vio, buf, prt, buflen)
Definition at line 169 of file violite.h.
vio_poll_read
#define vio_poll_read (vio, timeout) (vio)->poll_read(vio, timeout)
Definition at line 171 of file violite.h.
vio_read
#define vio_read (vio, buf, size) ((vio)->read)(vio,buf,size)
Definition at line 159 of file violite.h.
VIO_READ_BUFFER_SIZE
#define VIO_READ_BUFFER_SIZE 16384 /* size of read buffer */
Definition at line 46 of file violite.h.
vio_should_retry
#define vio_should_retry (vio) (vio)->should_retry(vio)
Definition at line 166 of file violite.h.
vio_timeout
#define vio_timeout (vio, which, seconds) (vio)->timeout(vio, which, seconds)
Definition at line 170 of file violite.h.
vio_was_interrupted
#define vio_was_interrupted (vio) (vio)->was_interrupted(vio)
Definition at line 167 of file violite.h.
vio_write
#define vio_write (vio, buf, size) ((vio)->write)(vio, buf, size)
Definition at line 160 of file violite.h.
Enumeration Type Documentation
enum_vio_type
enum enum_vio_type
Enumerator
VIO_CLOSED
VIO_TYPE_TCPIP
VIO_TYPE_SOCKET
VIO_TYPE_NAMEDPIPE
VIO_TYPE_SSL
VIO_TYPE_SHARED_MEMORY
Definition at line 37 of file violite.h.
 {
   VIO_CLOSED, VIO_TYPE_TCPIP, VIO_TYPE_SOCKET, VIO_TYPE_NAMEDPIPE,
   VIO_TYPE_SSL, VIO_TYPE_SHARED_MEMORY
 };
SSL_type
enum SSL_type
Enumerator
SSL_TYPE_NOT_SPECIFIED
SSL_TYPE_NONE
SSL_TYPE_ANY
SSL_TYPE_X509
SSL_TYPE_SPECIFIED
Definition at line 176 of file violite.h.
 {
   SSL_TYPE_NOT_SPECIFIED= -1,
   SSL_TYPE_NONE,
   SSL_TYPE_ANY,
   SSL_TYPE_X509,
   SSL_TYPE_SPECIFIED
 };
Function Documentation
vio_blocking()
int vio_blocking (Vio * vio, my_bool onoff, my_bool * old_mode)
vio_close()
int vio_close (Vio * vio)
Definition at line 273 of file viosocket.c.
 {
   int r=0;
   DBUG_ENTER("vio_close");
  if (vio->type != VIO_CLOSED)
   {
     DBUG_ASSERT(vio->type ==  VIO_TYPE_TCPIP ||
       vio->type == VIO_TYPE_SOCKET ||
       vio->type == VIO_TYPE_SSL);
     DBUG_ASSERT(vio->sd >= 0);
     if (shutdown(vio->sd, SHUT_RDWR))
       r= -1;
     if (closesocket(vio->sd))
       r= -1;
   }
   if (r)
   {
     DBUG_PRINT("vio_error", ("close() failed, error: %d",socket_errno));
     /* FIXME: error handling (not critical for MySQL) */
   }
   vio->type= VIO_CLOSED;
   vio->sd=   -1;
   DBUG_RETURN(r);
 }
References closesocket, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, socket_errno, st_vio::type, VIO_CLOSED, VIO_TYPE_SOCKET, VIO_TYPE_SSL, and VIO_TYPE_TCPIP.
vio_delete()
void vio_delete (Vio * vio)
Definition at line 269 of file vio.c.
 {
   if (!vio)
     return; /* It must be safe to delete null pointers. */
   if (vio->type != VIO_CLOSED)
     vio->vioclose(vio);
   my_free(vio->read_buffer);
   my_free(vio);
 }
References my_free(), st_vio::read_buffer, st_vio::type, VIO_CLOSED, and st_vio::vioclose.
Referenced by vio_init().
vio_description()
const char* vio_description (Vio * vio)
Definition at line 301 of file viosocket.c.
 {
   return vio->desc;
 }
References st_vio::desc.
Referenced by cli_safe_read(), end_server(), and net_clear().
vio_end()
void vio_end (void)
Definition at line 286 of file vio.c.
 {
 #ifdef HAVE_YASSL
   yaSSL_CleanUp();
 #endif
 }
Referenced by mysql_server_end().
vio_errno()
int vio_errno (Vio * vio)
vio_fastsend()
int vio_fastsend (Vio * vio)
vio_fd()
my_socket vio_fd (Vio * vio)
Definition at line 311 of file viosocket.c.
 {
   return vio->sd;
 }
References st_vio::sd.
Referenced by my_net_init().
vio_get_normalized_ip_string()
my_bool vio_get_normalized_ip_string (const struct sockaddr * addr, int addr_length, char * ip_string, size_t ip_string_size)
Return the normalized IP address string for a sock-address.
The idea is to return an IPv4-address for an IPv4-mapped and IPv4-compatible IPv6 address.
The function writes the normalized IP address to the given buffer. The buffer should have enough space, otherwise error flag is returned. The system constant INET6_ADDRSTRLEN can be used to reserve buffers of the right size.
Parameters
addr [in] sockaddr object (AF_INET or AF_INET6).
addr_length [in] length of the addr.
ip_string [out] buffer to write normalized IP address.
ip_string_size [in] size of the ip_string.
Returns
Error status.
Return values
TRUE in case of error (the ip_string buffer is not enough).
FALSE on success.
Definition at line 415 of file viosocket.c.
 {
   struct sockaddr_storage norm_addr_storage;
   struct sockaddr *norm_addr= (struct sockaddr *) &norm_addr_storage;
   int norm_addr_length;
   int err_code;
   vio_get_normalized_ip(addr, addr_length, norm_addr, &norm_addr_length);
   err_code= vio_getnameinfo(norm_addr, ip_string, ip_string_size, NULL, 0,
                             NI_NUMERICHOST);
   if (!err_code)
     return FALSE;
   DBUG_PRINT("error", ("getnameinfo() failed with %d (%s).",
                        (int) err_code,
                        (const char *) gai_strerror(err_code)));
   return TRUE;
 }
References DBUG_PRINT, FALSE, NULL, TRUE, vio_get_normalized_ip(), and vio_getnameinfo().
vio_getnameinfo()
int vio_getnameinfo (const struct sockaddr * sa, char * hostname, size_t hostname_size, char * port, size_t port_size, int flags)
This is a wrapper for the system getnameinfo(), because different OS differ in the getnameinfo() implementation:
Solaris 10 requires that the 2nd argument (salen) must match the actual size of the struct sockaddr_storage passed to it;
Mac OS X has sockaddr_in::sin_len and sockaddr_in6::sin6_len and requires them to be filled.
Definition at line 1071 of file viosocket.c.
 {
   int sa_length= 0;
   switch (sa->sa_family) {
   case AF_INET:
     sa_length= sizeof (struct sockaddr_in);
 #ifdef HAVE_SOCKADDR_IN_SIN_LEN
     ((struct sockaddr_in *) sa)->sin_len= sa_length;
 #endif /* HAVE_SOCKADDR_IN_SIN_LEN */
     break;
 #ifdef HAVE_IPV6
   case AF_INET6:
     sa_length= sizeof (struct sockaddr_in6);
 # ifdef HAVE_SOCKADDR_IN6_SIN6_LEN
     ((struct sockaddr_in6 *) sa)->sin6_len= sa_length;
 # endif /* HAVE_SOCKADDR_IN6_SIN6_LEN */
     break;
 #endif /* HAVE_IPV6 */
   }
   return getnameinfo(sa, sa_length,
                      hostname, hostname_size,
                      port, port_size,
                      flags);
 }
Referenced by vio_get_normalized_ip_string(), and vio_peer_addr().
vio_is_blocking()
my_bool vio_is_blocking (Vio * vio)
Definition at line 185 of file viosocket.c.
 {
   my_bool r;
   DBUG_ENTER("vio_is_blocking");
   r = !(vio->fcntl_mode & O_NONBLOCK);
   DBUG_PRINT("exit", ("%d", (int) r));
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, and st_vio::fcntl_mode.
Referenced by vio_should_retry().
vio_is_connected()
my_bool vio_is_connected (Vio * vio)
Determine if the endpoint of a connection is still available.
Remarks
The socket is assumed to be disconnected if an EOF condition is encountered.
Parameters
vio The VIO object.
Return values
TRUE EOF condition not found.
FALSE EOF condition is signaled.
Definition at line 645 of file viosocket.c.
 {
   uint bytes= 0;
   DBUG_ENTER("vio_is_connected");
   /* In the presence of errors the socket is assumed to be connected. */
   /*
     The first step of detecting a EOF condition is veryfing
     whether there is data to read. Data in this case would
     be the EOF.
   */
   if (vio_poll_read(vio, 0))
     DBUG_RETURN(TRUE);
   /*
     The second step is read() or recv() from the socket returning
     0 (EOF). Unfortunelly, it's not possible to call read directly
     as we could inadvertently read meaningful connection data.
     Simulate a read by retrieving the number of bytes available to
     read -- 0 meaning EOF.
   */
   if (socket_peek_read(vio, &bytes))
     DBUG_RETURN(TRUE);
 #ifdef HAVE_OPENSSL
   /* There might be buffered data at the SSL layer. */
   if (!bytes && vio->type == VIO_TYPE_SSL)
     bytes= SSL_pending((SSL*) vio->ssl_arg);
 #endif
   DBUG_RETURN(bytes ? TRUE : FALSE);
 }
References DBUG_ENTER, DBUG_RETURN, FALSE, socket_peek_read(), TRUE, st_vio::type, vio_poll_read(), and VIO_TYPE_SSL.
vio_keepalive()
int vio_keepalive (Vio * vio, my_bool onoff)
Definition at line 228 of file viosocket.c.
 {
   int r=0;
   uint opt = 0;
   DBUG_ENTER("vio_keepalive");
   DBUG_PRINT("enter", ("sd: %d  set_keep_alive: %d", vio->sd, (int)
                set_keep_alive));
   if (vio->type != VIO_TYPE_NAMEDPIPE)
   {
     if (set_keep_alive)
       opt = 1;
     r = setsockopt(vio->sd, SOL_SOCKET, SO_KEEPALIVE, (char *) &opt,
            sizeof(opt));
   }
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, st_vio::type, and VIO_TYPE_NAMEDPIPE.
vio_new()
Vio* vio_new (my_socket sd, enum enum_vio_type type, uint flags)
Definition at line 184 of file vio.c.
 {
   Vio *vio;
   DBUG_ENTER("vio_new");
   DBUG_PRINT("enter", ("sd: %d", sd));
   if ((vio = (Vio*) my_malloc(sizeof(*vio),MYF(MY_WME))))
   {
     vio_init(vio, type, sd, 0, flags);
     sprintf(vio->desc,
         (vio->type == VIO_TYPE_SOCKET ? "socket (%d)" : "TCP/IP (%d)"),
         vio->sd);
 #if !defined(__WIN__)
 #if !defined(NO_FCNTL_NONBLOCK)
     /*
       We call fcntl() to set the flags and then immediately read them back
       to make sure that we and the system are in agreement on the state of
       things.
       An example of why we need to do this is FreeBSD (and apparently some
       other BSD-derived systems, like Mac OS X), where the system sometimes
       reports that the socket is set for non-blocking when it really will
       block.
     */
     fcntl(sd, F_SETFL, 0);
     vio->fcntl_mode= fcntl(sd, F_GETFL);
 #elif defined(HAVE_SYS_IOCTL_H)         /* hpux */
     /* Non blocking sockets doesn't work good on HPUX 11.0 */
     (void) ioctl(sd,FIOSNBIO,0);
     vio->fcntl_mode &= ~O_NONBLOCK;
 #endif
 #else /* !defined(__WIN__) */
     {
       /* set to blocking mode by default */
       ulong arg=0, r;
       r = ioctlsocket(sd,FIONBIO,(void*) &arg);
       vio->fcntl_mode &= ~O_NONBLOCK;
     }
 #endif
   }
   DBUG_RETURN(vio);
 }
References arg(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::desc, st_vio::fcntl_mode, my_malloc(), MY_WME, MYF, st_vio::sd, sprintf(), st_vio::type, vio_init(), and VIO_TYPE_SOCKET.
Referenced by CLI_MYSQL_REAL_CONNECT().
vio_peer_addr()
my_bool vio_peer_addr (Vio * vio, char * ip_buffer, uint16 * port, size_t ip_buffer_size)
Return IP address and port of a VIO client socket.
The function returns an IPv4 address if IPv6 support is disabled.
The function returns an IPv4 address if the client socket is associated with an IPv4-compatible or IPv4-mapped IPv6 address. Otherwise, the native IPv6 address is returned.
Definition at line 450 of file viosocket.c.
 {
   DBUG_ENTER("vio_peer_addr");
   DBUG_PRINT("enter", ("Client socked fd: %d", (int) vio->sd));
   if (vio->localhost)
   {
     /*
       Initialize vio->remote and vio->addLen. Set vio->remote to IPv4 loopback
       address.
     */
     struct in_addr *ip4= &((struct sockaddr_in *) &(vio->remote))->sin_addr;
     vio->remote.ss_family= AF_INET;
     vio->addrLen= sizeof (struct sockaddr_in);
     ip4->s_addr= htonl(INADDR_LOOPBACK);
     /* Initialize ip_buffer and port. */
     strmov(ip_buffer, "127.0.0.1");
     *port= 0;
   }
   else
   {
     int err_code;
     char port_buffer[NI_MAXSERV];
     struct sockaddr_storage addr_storage;
     struct sockaddr *addr= (struct sockaddr *) &addr_storage;
     size_socket addr_length= sizeof (addr_storage);
     /* Get sockaddr by socked fd. */
     err_code= getpeername(vio->sd, addr, &addr_length);
     if (err_code)
     {
       DBUG_PRINT("exit", ("getpeername() gave error: %d", socket_errno));
       DBUG_RETURN(TRUE);
     }
     /* Normalize IP address. */
     vio_get_normalized_ip(addr, addr_length,
                           (struct sockaddr *) &vio->remote, &vio->addrLen);
     /* Get IP address & port number. */
     err_code= vio_getnameinfo((struct sockaddr *) &vio->remote,
                               ip_buffer, ip_buffer_size,
                               port_buffer, NI_MAXSERV,
                               NI_NUMERICHOST | NI_NUMERICSERV);
     if (err_code)
     {
       DBUG_PRINT("exit", ("getnameinfo() gave error: %s",
                           gai_strerror(err_code)));
       DBUG_RETURN(TRUE);
     }
     *port= (uint16) strtol(port_buffer, NULL, 10);
   }
   DBUG_PRINT("exit", ("Client IP address: %s; port: %d",
                       (const char *) ip_buffer,
                       (int) *port));
   DBUG_RETURN(FALSE);
 }
References st_vio::addrLen, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_vio::localhost, NULL, st_vio::remote, st_vio::sd, socket_errno, strmov(), strtol(), TRUE, vio_get_normalized_ip(), and vio_getnameinfo().
vio_pending()
ssize_t vio_pending (Vio * vio)
Number of bytes in the read buffer.
Returns
number of bytes in the read buffer or < 0 if error.
Definition at line 1044 of file viosocket.c.
 {
 #ifdef HAVE_OPENSSL
   SSL *ssl= (SSL*) vio->ssl_arg;
 #endif
   if (vio->read_pos < vio->read_end)
     return vio->read_end - vio->read_pos;
 #ifdef HAVE_OPENSSL
   if (ssl)
     return SSL_pending(ssl);
 #endif
   return 0;
 }
References endif(), if(), st_vio::read_end, and st_vio::read_pos.
vio_poll_read()
my_bool vio_poll_read (Vio * vio, uint timeout)
Indicate whether there is data to read on a given socket.
Remarks
Errors are interpreted as if there is data to read.
Parameters
sd A connected socket.
timeout Maximum time in seconds to wait.
Return values
FALSE There is data (or EOF) to read. Also FALSE if error.
TRUE There is NO data to read or timed out.
Definition at line 621 of file viosocket.c.
 {
   my_socket sd= vio->sd;
   DBUG_ENTER("vio_poll_read");
 #ifdef HAVE_OPENSSL
   if (vio->type == VIO_TYPE_SSL)
     sd= SSL_get_fd((SSL*) vio->ssl_arg);
 #endif
   DBUG_RETURN(socket_poll_read(sd, timeout));
 }
References DBUG_ENTER, DBUG_RETURN, st_vio::sd, socket_poll_read(), st_vio::type, and VIO_TYPE_SSL.
Referenced by vio_is_connected().
vio_read()
size_t vio_read (Vio * vio, uchar * buf, size_t size)
Definition at line 31 of file viosocket.c.
 {
   size_t r;
   DBUG_ENTER("vio_read");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
   /* Ensure nobody uses vio_read_buff and vio_read simultaneously */
   DBUG_ASSERT(vio->read_end == vio->read_pos);
 #ifdef __WIN__
   r = recv(vio->sd, buf, size,0);
 #else
   errno=0;                  /* For linux */
   r = read(vio->sd, buf, size);
 #endif /* __WIN__ */
 #ifndef DBUG_OFF
   if (r == (size_t) -1)
   {
     DBUG_PRINT("vio_error", ("Got error %d during read",errno));
   }
 #endif /* DBUG_OFF */
   DBUG_PRINT("exit", ("%ld", (long) r));
   DBUG_RETURN(r);
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, errno, read, st_vio::read_end, st_vio::read_pos, and st_vio::sd.
Referenced by vio_read_buff().
vio_read_buff()
size_t vio_read_buff (Vio * vio, uchar * buf, size_t size)
Definition at line 62 of file viosocket.c.
 {
   size_t rc;
 #define VIO_UNBUFFERED_READ_MIN_SIZE 2048
   DBUG_ENTER("vio_read_buff");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
   if (vio->read_pos < vio->read_end)
   {
     rc= min((size_t) (vio->read_end - vio->read_pos), size);
     memcpy(buf, vio->read_pos, rc);
     vio->read_pos+= rc;
     /*
       Do not try to read from the socket now even if rc < size:
       vio_read can return -1 due to an error or non-blocking mode, and
       the safest way to handle it is to move to a separate branch.
     */
   }
   else if (size < VIO_UNBUFFERED_READ_MIN_SIZE)
   {
     rc= vio_read(vio, (uchar*) vio->read_buffer, VIO_READ_BUFFER_SIZE);
     if (rc != 0 && rc != (size_t) -1)
     {
       if (rc > size)
       {
         vio->read_pos= vio->read_buffer + size;
         vio->read_end= vio->read_buffer + rc;
         rc= size;
       }
       memcpy(buf, vio->read_buffer, rc);
     }
   }
   else
     rc= vio_read(vio, buf, size);
   DBUG_RETURN(rc);
 #undef VIO_UNBUFFERED_READ_MIN_SIZE
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, memcpy, min, st_vio::read_buffer, st_vio::read_end, st_vio::read_pos, st_vio::sd, vio_read(), VIO_READ_BUFFER_SIZE, and VIO_UNBUFFERED_READ_MIN_SIZE.
Referenced by vio_init().
vio_reset()
void vio_reset (Vio * vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags)
Definition at line 174 of file vio.c.
 {
   my_free(vio->read_buffer);
   vio_init(vio, type, sd, hPipe, flags);
 }
References my_free(), st_vio::read_buffer, and vio_init().
vio_should_retry()
my_bool vio_should_retry (Vio * vio)
Definition at line 247 of file viosocket.c.
 {
   int en = socket_errno;
   /*
     man 2 read write
       EAGAIN or EWOULDBLOCK when a socket is a non-blocking mode means
       that the read/write would block.
     man 7 socket
       EAGAIN or EWOULDBLOCK when a socket is in a blocking mode means
       that the corresponding receiving or sending timeout was reached.
   */
   return  en == SOCKET_EINTR ||
           (!vio_is_blocking(vio) &&
             (en == SOCKET_EAGAIN || en == SOCKET_EWOULDBLOCK));
 }
References SOCKET_EAGAIN, SOCKET_EINTR, socket_errno, SOCKET_EWOULDBLOCK, and vio_is_blocking().
vio_type()
enum enum_vio_type vio_type (Vio * vio)
Definition at line 301 of file viosocket.c.
 {
   return vio->type;
 }
vio_was_interrupted()
my_bool vio_was_interrupted (Vio * vio)
vio_write()
size_t vio_write (Vio * vio, const uchar * buf, size_t size)
Definition at line 106 of file viosocket.c.
 {
   size_t r;
   DBUG_ENTER("vio_write");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
 #ifdef __WIN__
   r = send(vio->sd, buf, size,0);
 #else
   r = write(vio->sd, buf, size);
 #endif /* __WIN__ */
 #ifndef DBUG_OFF
   if (r == (size_t) -1)
   {
     DBUG_PRINT("vio_error", ("Got error on write: %d",socket_errno));
   }
 #endif /* DBUG_OFF */
   DBUG_PRINT("exit", ("%u", (uint) r));
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, socket_errno, and write.