Azerotcore-wotlk: deps/mysqllite/mysys/mf_sort.c File Reference
mf_sort.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
void my_string_ptr_sort (uchar *base, uint items, size_t size)
Function Documentation
my_string_ptr_sort()
void my_string_ptr_sort (uchar * base, uint items, size_t size)
Definition at line 21 of file mf_sort.c.
 {
 #if INT_MAX > 65536L
   uchar **ptr=0;
   if (size <= 20 && items >= 1000 && items < 100000 &&
       (ptr= (uchar**) my_malloc(items*sizeof(char*),MYF(0))))
   {
     radixsort_for_str_ptr((uchar**) base,items,size,ptr);
     my_free(ptr);
   }
   else
 #endif
   {
     if (size && items)
     {
       my_qsort2(base,items, sizeof(uchar*), get_ptr_compare(size),
                 (void*) &size);
     }
   }
 }
References get_ptr_compare(), my_free(), my_malloc(), my_qsort2(), MYF, ptr(), and radixsort_for_str_ptr().