Azerotcore-wotlk: deps/mysqllite/mysys/mf_keycaches.c File Reference
mf_keycaches.c File Reference
#include "mysys_priv.h"
#include <keycache.h>
#include <hash.h>
#include <m_string.h>
Classes
struct st_safe_hash_entry
struct st_safe_hash_with_default
Typedefs
typedef struct st_safe_hash_entry SAFE_HASH_ENTRY
typedef struct st_safe_hash_with_default SAFE_HASH
Functions
static void safe_hash_entry_free (SAFE_HASH_ENTRY *entry)
static uchar * safe_hash_entry_get (SAFE_HASH_ENTRY *entry, size_t *length, my_bool not_used __attribute__((unused)))
static my_bool safe_hash_init (SAFE_HASH *hash, uint elements, uchar *default_value)
static void safe_hash_free (SAFE_HASH *hash)
static uchar * safe_hash_search (SAFE_HASH *hash, const uchar *key, uint length)
static my_bool safe_hash_set (SAFE_HASH *hash, const uchar *key, uint length, uchar *data)
static void safe_hash_change (SAFE_HASH *hash, uchar *old_data, uchar *new_data)
my_bool multi_keycache_init (void)
void multi_keycache_free (void)
KEY_CACHE * multi_key_cache_search (uchar *key, uint length)
my_bool multi_key_cache_set (const uchar *key, uint length, KEY_CACHE *key_cache)
void multi_key_cache_change (KEY_CACHE *old_data, KEY_CACHE *new_data)
Variables
static SAFE_HASH key_cache_hash
Typedef Documentation
SAFE_HASH
typedef struct st_safe_hash_with_default SAFE_HASH
SAFE_HASH_ENTRY
typedef struct st_safe_hash_entry SAFE_HASH_ENTRY
Function Documentation
multi_key_cache_change()
void multi_key_cache_change (KEY_CACHE * old_data, KEY_CACHE * new_data)
Definition at line 357 of file mf_keycaches.c.
 {
   safe_hash_change(&key_cache_hash, (uchar*) old_data, (uchar*) new_data);
 }
References key_cache_hash, and safe_hash_change().
multi_key_cache_search()
KEY_CACHE* multi_key_cache_search (uchar * key, uint length)
Definition at line 326 of file mf_keycaches.c.
 {
   if (!key_cache_hash.hash.records)
     return dflt_key_cache;
   return (KEY_CACHE*) safe_hash_search(&key_cache_hash, key, length);
 }
References dflt_key_cache, st_safe_hash_with_default::hash, key_cache_hash, G3D::length(), st_hash::records, and safe_hash_search().
multi_key_cache_set()
my_bool multi_key_cache_set (const uchar * key, uint length, KEY_CACHE * key_cache)
Definition at line 350 of file mf_keycaches.c.
 {
   return safe_hash_set(&key_cache_hash, key, length, (uchar*) key_cache);
 }
References key_cache_hash, G3D::length(), and safe_hash_set().
multi_keycache_free()
void multi_keycache_free (void)
Definition at line 304 of file mf_keycaches.c.
 {
   safe_hash_free(&key_cache_hash);
 }
References key_cache_hash, and safe_hash_free().
multi_keycache_init()
my_bool multi_keycache_init (void)
Definition at line 298 of file mf_keycaches.c.
 {
   return safe_hash_init(&key_cache_hash, 16, (uchar*) dflt_key_cache);
 }
References dflt_key_cache, key_cache_hash, and safe_hash_init().
safe_hash_change()
static void safe_hash_change (SAFE_HASH * hash, uchar * old_data, uchar * new_data) static
Definition at line 262 of file mf_keycaches.c.
 {
   SAFE_HASH_ENTRY *entry, *next;
   DBUG_ENTER("safe_hash_set");
   rw_wrlock(&hash->mutex);
   for (entry= hash->root ; entry ; entry= next)
   {
     next= entry->next;
     if (entry->data == old_data)
     {
       if (new_data == hash->default_value)
       {
         if ((*entry->prev= entry->next))
           entry->next->prev= entry->prev;
     my_hash_delete(&hash->hash, (uchar*) entry);
       }
       else
     entry->data= new_data;
     }
   }
   rw_unlock(&hash->mutex);
   DBUG_VOID_RETURN;
 }
References st_safe_hash_entry::data, DBUG_ENTER, DBUG_VOID_RETURN, hash(), my_hash_delete(), st_safe_hash_entry::next, next(), st_safe_hash_entry::prev, rw_unlock, and rw_wrlock.
Referenced by multi_key_cache_change().
safe_hash_entry_free()
static void safe_hash_entry_free (SAFE_HASH_ENTRY * entry) static
Definition at line 69 of file mf_keycaches.c.
 {
   DBUG_ENTER("free_assign_entry");
   my_free(entry);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, and my_free().
Referenced by safe_hash_init().
safe_hash_entry_get()
static uchar* safe_hash_entry_get (SAFE_HASH_ENTRY * entry, size_t * length, my_bool not_used __attribute__(unused)) static
Definition at line 79 of file mf_keycaches.c.
 {
   *length=entry->length;
   return (uchar*) entry->key;
 }
References st_safe_hash_entry::key, G3D::length(), and st_safe_hash_entry::length.
Referenced by safe_hash_init().
safe_hash_free()
static void safe_hash_free (SAFE_HASH * hash) static
Definition at line 130 of file mf_keycaches.c.
 {
   /*
     Test if safe_hash_init succeeded. This will also guard us against multiple
     free calls.
   */
   if (hash->default_value)
   {
     my_hash_free(&hash->hash);
     rwlock_destroy(&hash->mutex);
     hash->default_value=0;
   }
 }
References hash(), my_hash_free(), and rwlock_destroy.
Referenced by multi_keycache_free().
safe_hash_init()
static my_bool safe_hash_init (SAFE_HASH * hash, uint elements, uchar * default_value) static
Definition at line 105 of file mf_keycaches.c.
 {
   DBUG_ENTER("safe_hash");
   if (my_hash_init(&hash->hash, &my_charset_bin, elements,
                    0, 0, (my_hash_get_key) safe_hash_entry_get,
                    (void (*)(void*)) safe_hash_entry_free, 0))
   {
     hash->default_value= 0;
     DBUG_RETURN(1);
   }
   my_rwlock_init(&hash->mutex, 0);
   hash->default_value= default_value;
   hash->root= 0;
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, hash(), my_charset_bin, my_hash_init, my_rwlock_init, safe_hash_entry_free(), and safe_hash_entry_get().
Referenced by multi_keycache_init().
safe_hash_search()
static uchar* safe_hash_search (SAFE_HASH * hash, const uchar * key, uint length) static
Definition at line 148 of file mf_keycaches.c.
 {
   uchar *result;
   DBUG_ENTER("safe_hash_search");
   rw_rdlock(&hash->mutex);
   result= my_hash_search(&hash->hash, key, length);
   rw_unlock(&hash->mutex);
   if (!result)
     result= hash->default_value;
   else
     result= ((SAFE_HASH_ENTRY*) result)->data;
   DBUG_PRINT("exit",("data: 0x%lx", (long) result));
   DBUG_RETURN(result);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, hash(), G3D::length(), my_hash_search(), rw_rdlock, and rw_unlock.
Referenced by multi_key_cache_search().
safe_hash_set()
static my_bool safe_hash_set (SAFE_HASH * hash, const uchar * key, uint length, uchar * data) static
Definition at line 184 of file mf_keycaches.c.
 {
   SAFE_HASH_ENTRY *entry;
   my_bool error= 0;
   DBUG_ENTER("safe_hash_set");
   DBUG_PRINT("enter",("key: %.*s  data: 0x%lx", length, key, (long) data));
   rw_wrlock(&hash->mutex);
   entry= (SAFE_HASH_ENTRY*) my_hash_search(&hash->hash, key, length);
   if (data == hash->default_value)
   {
     /*
       The key is to be associated with the default entry. In this case
       we can just delete the entry (if it existed) from the hash as a
       search will return the default entry
     */
     if (!entry)                 /* nothing to do */
       goto end;
     /* unlink entry from list */
     if ((*entry->prev= entry->next))
       entry->next->prev= entry->prev;
     my_hash_delete(&hash->hash, (uchar*) entry);
     goto end;
   }
   if (entry)
   {
     /* Entry existed;  Just change the pointer to point at the new data */
     entry->data= data;
   }
   else
   {
     if (!(entry= (SAFE_HASH_ENTRY *) my_malloc(sizeof(*entry) + length,
                            MYF(MY_WME))))
     {
       error= 1;
       goto end;
     }
     entry->key= (uchar*) (entry +1);
     memcpy((char*) entry->key, (char*) key, length);
     entry->length= length;
     entry->data= data;
     /* Link entry to list */
     if ((entry->next= hash->root))
       entry->next->prev= &entry->next;
     entry->prev= &hash->root;
     hash->root= entry;
     if (my_hash_insert(&hash->hash, (uchar*) entry))
     {
       /* This can only happen if hash got out of memory */
       my_free(entry);
       error= 1;
       goto end;
     }
   }
 end:
   rw_unlock(&hash->mutex);
   DBUG_RETURN(error);
 }
References st_safe_hash_entry::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), hash(), st_safe_hash_entry::key, G3D::length(), st_safe_hash_entry::length, memcpy, my_free(), my_hash_delete(), my_hash_insert(), my_hash_search(), my_malloc(), MY_WME, MYF, st_safe_hash_entry::next, st_safe_hash_entry::prev, rw_unlock, and rw_wrlock.
Referenced by multi_key_cache_set().
Variable Documentation
key_cache_hash
SAFE_HASH key_cache_hash static
Definition at line 295 of file mf_keycaches.c.
Referenced by multi_key_cache_change(), multi_key_cache_search(), multi_key_cache_set(), multi_keycache_free(), and multi_keycache_init().