Azerotcore-wotlk: deps/jemalloc/src/nstime.c File Reference
nstime.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/nstime.h"
#include "jemalloc/internal/assert.h"
Macros
#define BILLION UINT64_C(1000000000)
#define MILLION UINT64_C(1000000)
#define NSTIME_MONOTONIC false
Functions
void nstime_init (nstime_t *time, uint64_t ns)
void nstime_init2 (nstime_t *time, uint64_t sec, uint64_t nsec)
uint64_t nstime_ns (const nstime_t *time)
uint64_t nstime_msec (const nstime_t *time)
uint64_t nstime_sec (const nstime_t *time)
uint64_t nstime_nsec (const nstime_t *time)
void nstime_copy (nstime_t *time, const nstime_t *source)
int nstime_compare (const nstime_t *a, const nstime_t *b)
void nstime_add (nstime_t *time, const nstime_t *addend)
void nstime_iadd (nstime_t *time, uint64_t addend)
void nstime_subtract (nstime_t *time, const nstime_t *subtrahend)
void nstime_isubtract (nstime_t *time, uint64_t subtrahend)
void nstime_imultiply (nstime_t *time, uint64_t multiplier)
void nstime_idivide (nstime_t *time, uint64_t divisor)
uint64_t nstime_divide (const nstime_t *time, const nstime_t *divisor)
static void nstime_get (nstime_t *time)
static bool nstime_monotonic_impl (void)
static bool nstime_update_impl (nstime_t *time)
Variables
nstime_monotonic_t *JET_MUTABLE nstime_monotonic = nstime_monotonic_impl
nstime_update_t *JET_MUTABLE nstime_update = nstime_update_impl
Macro Definition Documentation
BILLION
#define BILLION UINT64_C(1000000000)
Definition at line 8 of file nstime.c.
MILLION
#define MILLION UINT64_C(1000000)
Definition at line 9 of file nstime.c.
NSTIME_MONOTONIC
#define NSTIME_MONOTONIC false
Definition at line 138 of file nstime.c.
Function Documentation
nstime_add()
void nstime_add (nstime_t * time, const nstime_t * addend)
Definition at line 52 of file nstime.c.
{
     assert(UINT64_MAX - time->ns >= addend->ns);
     time->ns += addend->ns;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_compare()
int nstime_compare (const nstime_t * a, const nstime_t * b)
Definition at line 47 of file nstime.c.
{
     return (a->ns > b->ns) - (a->ns < b->ns);
 }
References mpq::a, and b.
Referenced by nstime_subtract(), and nstime_update_impl().
nstime_copy()
void nstime_copy (nstime_t * time, const nstime_t * source)
Definition at line 42 of file nstime.c.
{
     *time = *source;
 }
Referenced by nstime_update_impl().
nstime_divide()
uint64_t nstime_divide (const nstime_t * time, const nstime_t * divisor)
Definition at line 95 of file nstime.c.
{
     assert(divisor->ns != 0);
     return time->ns / divisor->ns;
 }
References assert(), and nstime_t::ns.
nstime_get()
static void nstime_get (nstime_t * time) static
Definition at line 140 of file nstime.c.
{
     struct timeval tv;
     gettimeofday(&tv, NULL);
     nstime_init2(time, tv.tv_sec, tv.tv_usec * 1000);
 }
References nstime_init2(), and NULL.
Referenced by nstime_update_impl().
nstime_iadd()
void nstime_iadd (nstime_t * time, uint64_t addend)
Definition at line 59 of file nstime.c.
{
     assert(UINT64_MAX - time->ns >= addend);
     time->ns += addend;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_idivide()
void nstime_idivide (nstime_t * time, uint64_t divisor)
Definition at line 88 of file nstime.c.
{
     assert(divisor != 0);
     time->ns /= divisor;
 }
References assert(), and nstime_t::ns.
nstime_imultiply()
void nstime_imultiply (nstime_t * time, uint64_t multiplier)
Definition at line 80 of file nstime.c.
{
     assert((((time->ns | multiplier) & (UINT64_MAX << (sizeof(uint64_t) <<
         2))) == 0) || ((time->ns * multiplier) / multiplier == time->ns));
     time->ns *= multiplier;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_init()
void nstime_init (nstime_t * time, uint64_t ns)
Definition at line 12 of file nstime.c.
{
     time->ns = ns;
 }
References nstime_t::ns.
nstime_init2()
void nstime_init2 (nstime_t * time, uint64_t sec, uint64_t nsec)
Definition at line 17 of file nstime.c.
{
     time->ns = sec * BILLION + nsec;
 }
References BILLION, nstime_t::ns, and sec.
Referenced by nstime_get().
nstime_isubtract()
void nstime_isubtract (nstime_t * time, uint64_t subtrahend)
Definition at line 73 of file nstime.c.
{
     assert(time->ns >= subtrahend);
     time->ns -= subtrahend;
 }
References assert(), and nstime_t::ns.
nstime_monotonic_impl()
static bool nstime_monotonic_impl (void) static
Definition at line 149 of file nstime.c.
{
     return NSTIME_MONOTONIC;
 #undef NSTIME_MONOTONIC
 }
References NSTIME_MONOTONIC.
nstime_msec()
uint64_t nstime_msec (const nstime_t * time)
Definition at line 27 of file nstime.c.
{
     return time->ns / MILLION;
 }
References MILLION, and nstime_t::ns.
nstime_ns()
uint64_t nstime_ns (const nstime_t * time)
Definition at line 22 of file nstime.c.
{
     return time->ns;
 }
References nstime_t::ns.
nstime_nsec()
uint64_t nstime_nsec (const nstime_t * time)
Definition at line 37 of file nstime.c.
{
     return time->ns % BILLION;
 }
References BILLION, and nstime_t::ns.
nstime_sec()
uint64_t nstime_sec (const nstime_t * time)
Definition at line 32 of file nstime.c.
{
     return time->ns / BILLION;
 }
References BILLION, and nstime_t::ns.
nstime_subtract()
void nstime_subtract (nstime_t * time, const nstime_t * subtrahend)
Definition at line 66 of file nstime.c.
{
     assert(nstime_compare(time, subtrahend) >= 0);
     time->ns -= subtrahend->ns;
 }
References assert(), nstime_t::ns, and nstime_compare().
nstime_update_impl()
static bool nstime_update_impl (nstime_t * time) static
Definition at line 156 of file nstime.c.
{
     nstime_t old_time;
     nstime_copy(&old_time, time);
     nstime_get(time);
     /* Handle non-monotonic clocks. */
     if (unlikely(nstime_compare(&old_time, time) > 0)) {
         nstime_copy(time, &old_time);
         return true;
     }
     return false;
 }
References nstime_compare(), nstime_copy(), nstime_get(), and unlikely.
Variable Documentation
nstime_monotonic
nstime_monotonic_t* JET_MUTABLE nstime_monotonic = nstime_monotonic_impl
Definition at line 153 of file nstime.c.
nstime_update
nstime_update_t* JET_MUTABLE nstime_update = nstime_update_impl
Definition at line 170 of file nstime.c.