Azerotcore-wotlk: H2ORenderMask Class Reference
H2ORenderMask Class Reference
#include <Utils.h>
Public Member Functions
H2ORenderMask ()
bool ShouldRender (int x, int y)
Static Public Member Functions
static H2ORenderMask Read (FILE *stream)
Public Attributes
uint8 Mask [8]
Detailed Description
Definition at line 269 of file Utils.h.
Constructor & Destructor Documentation
H2ORenderMask()
H2ORenderMask::H2ORenderMask () inline
Definition at line 272 of file Utils.h.
 {}
Member Function Documentation
Read()
H2ORenderMask H2ORenderMask::Read (FILE * stream) static
Definition at line 478 of file Utils.cpp.
 {
     H2ORenderMask ret;
     int32 count;
     if ((count = fread(&ret.Mask, sizeof(uint8), 8, stream)) != 8)
         printf("H2OHeader::Read: Failed to read some data expected 8, read %d\n", count);
     return ret;
 }
References count(), printf(), and ret.
Referenced by LiquidHandler::HandleNewLiquid().
ShouldRender()
bool H2ORenderMask::ShouldRender (int x, int y) inline
Definition at line 275 of file Utils.h.
     {
         return (Mask[y] >> x & 1) != 0;
     }
References Mask, G3D::x, and G3D::y.
Referenced by LiquidHandler::HandleNewLiquid(), and MCNKLiquidData::IsWater().
Member Data Documentation
Mask
uint8 H2ORenderMask::Mask[8]
Definition at line 273 of file Utils.h.
Referenced by LiquidHandler::HandleNewLiquid(), and ShouldRender().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp