Azerotcore-wotlk: npc_costumed_orphan_matron Class Reference
npc_costumed_orphan_matron Class Reference
Classes
struct npc_costumed_orphan_matronAI
Public Member Functions
npc_costumed_orphan_matron ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnQuestAccept (Player *, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *pCreature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 399 of file hallows_end.cpp.
Constructor & Destructor Documentation
npc_costumed_orphan_matron()
npc_costumed_orphan_matron::npc_costumed_orphan_matron () inline
Definition at line 402 of file hallows_end.cpp.
 : CreatureScript("npc_costumed_orphan_matron") { }
Member Function Documentation
GetAI()
CreatureAI* npc_costumed_orphan_matron::GetAI (Creature * pCreature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 570 of file hallows_end.cpp.
     {
         return new npc_costumed_orphan_matronAI (pCreature);
     }
OnGossipHello()
bool npc_costumed_orphan_matron::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 510 of file hallows_end.cpp.
     {
         QuestRelationBounds pObjectQR = sObjectMgr->GetCreatureQuestRelationBounds(creature->GetEntry());
         QuestRelationBounds pObjectQIR = sObjectMgr->GetCreatureQuestInvolvedRelationBounds(creature->GetEntry());
         QuestMenu& qm = player->PlayerTalkClass->GetQuestMenu();
         qm.ClearMenu();
         for (QuestRelations::const_iterator i = pObjectQIR.first; i != pObjectQIR.second; ++i)
         {
             uint32 quest_id = i->second;
             QuestStatus status = player->GetQuestStatus(quest_id);
             if (status == QUEST_STATUS_COMPLETE)
                 qm.AddMenuItem(quest_id, 4);
             else if (status == QUEST_STATUS_INCOMPLETE)
                 qm.AddMenuItem(quest_id, 4);
         }
         for (QuestRelations::const_iterator i = pObjectQR.first; i != pObjectQR.second; ++i)
         {
             uint32 quest_id = i->second;
             Quest const* pQuest = sObjectMgr->GetQuestTemplate(quest_id);
             if (!pQuest)
                 continue;
             if (!player->CanTakeQuest(pQuest, false))
                 continue;
             else if (player->GetQuestStatus(quest_id) == QUEST_STATUS_NONE)
             {
                 switch (quest_id)
                 {
                     case QUEST_LET_THE_FIRES_COME_A:
                     case QUEST_LET_THE_FIRES_COME_H:
                         if (!creature->AI()->GetData(DATA_ALLOW_START))
                             qm.AddMenuItem(quest_id, 2);
                         break;
                     case QUEST_STOP_THE_FIRES_A:
                     case QUEST_STOP_THE_FIRES_H:
                         if (creature->AI()->GetData(DATA_ALLOW_START))
                             qm.AddMenuItem(quest_id, 2);
                         break;
                     default:
                         qm.AddMenuItem(quest_id, 2);
                         break;
                 }
             }
         }
         player->SendPreparedQuest(creature->GetGUID());
         return true;
     }
References QuestMenu::AddMenuItem(), Creature::AI(), Player::CanTakeQuest(), QuestMenu::ClearMenu(), DATA_ALLOW_START, UnitAI::GetData(), Object::GetEntry(), Object::GetGUID(), PlayerMenu::GetQuestMenu(), Player::GetQuestStatus(), Player::PlayerTalkClass, QUEST_LET_THE_FIRES_COME_A, QUEST_LET_THE_FIRES_COME_H, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_NONE, QUEST_STOP_THE_FIRES_A, QUEST_STOP_THE_FIRES_H, Player::SendPreparedQuest(), and sObjectMgr.
OnQuestAccept()
bool npc_costumed_orphan_matron::OnQuestAccept (Player * , Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 562 of file hallows_end.cpp.
     {
         if ((quest->GetQuestId() == QUEST_LET_THE_FIRES_COME_A || quest->GetQuestId() == QUEST_LET_THE_FIRES_COME_H) && !creature->AI()->GetData(DATA_ALLOW_START))
             creature->AI()->DoAction(ACTION_START_EVENT);
         return true;
     }
References ACTION_START_EVENT, Creature::AI(), DATA_ALLOW_START, UnitAI::DoAction(), UnitAI::GetData(), Quest::GetQuestId(), QUEST_LET_THE_FIRES_COME_A, and QUEST_LET_THE_FIRES_COME_H.
The documentation for this class was generated from the following file:
src/server/scripts/Events/hallows_end.cpp