Azerotcore-wotlk: boss_prince_keleseth_icc::boss_prince_kelesethAI Struct Reference
boss_prince_keleseth_icc::boss_prince_kelesethAI Struct Reference
Public Member Functions
boss_prince_kelesethAI (Creature *creature)
void InitializeAI () override
void Reset () override
void EnterCombat (Unit *who) override
void AttackStart (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void DamageDealt (Unit *target, uint32 &damage, DamageEffectType) override
void KilledUnit (Unit *victim) override
void SpellHit (Unit *, SpellInfo const *spell) override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
InstanceScript * instance
bool _isEmpowered
bool _evading
bool _canDie
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 190 of file boss_blood_prince_council.cpp.
Constructor & Destructor Documentation
boss_prince_kelesethAI()
boss_prince_keleseth_icc::boss_prince_kelesethAI::boss_prince_kelesethAI (Creature * creature) inline
Definition at line 192 of file boss_blood_prince_council.cpp.
                                                    : ScriptedAI(creature), summons(creature), instance(creature->GetInstanceScript())
         {
             if (!instance)
             {
                 me->IsAIEnabled = false;
                 me->AddUnitState(UNIT_STATE_EVADE);
             }
             _canDie = true;
         }
References _canDie, Unit::AddUnitState(), instance, Unit::IsAIEnabled, ScriptedAI::me, and UNIT_STATE_EVADE.
Member Function Documentation
AttackStart()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 280 of file boss_blood_prince_council.cpp.
         {
             ScriptedAI::AttackStartCaster(who, 10.0f);
         }
References UnitAI::AttackStartCaster().
DamageDealt()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::DamageDealt (Unit * target, uint32 & damage, DamageEffectType) inline override virtual
Reimplemented from UnitAI.
Definition at line 343 of file boss_blood_prince_council.cpp.
         {
             if (target->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (damage > RAID_MODE<uint32>(23000, 25000, 23000, 25000))
                 instance->SetData(DATA_ORB_WHISPERER_ACHIEVEMENT, 0);
         }
References DATA_ORB_WHISPERER_ACHIEVEMENT, Object::GetTypeId(), instance, ZoneScript::SetData(), and TYPEID_PLAYER.
DamageTaken()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 333 of file boss_blood_prince_council.cpp.
         {
             if (!_isEmpowered)
             {
                 if (attacker)
                     me->AddThreat(attacker, float(damage));
                 damage = 0;
             }
         }
References _isEmpowered, Unit::AddThreat(), and ScriptedAI::me.
DoAction()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 364 of file boss_blood_prince_council.cpp.
         {
             switch (action)
             {
                 case ACTION_STAND_UP:
                     summons.DespawnEntry(WORLD_TRIGGER);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                     me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                     me->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->ForceValuesUpdateAtIndex(UNIT_NPC_FLAGS);   // was in sniff. don't ask why
                     me->m_Events.AddEvent(new StandUpEvent(*me), me->m_Events.CalculateTime(1000));
                     DoAction(ACTION_REMOVE_INVOCATION);
                     me->SetHealth(1);
                     break;
                 case ACTION_CAST_INVOCATION:
                     Talk(SAY_KELESETH_INVOCATION);
                     me->CastSpell(me, SPELL_INVOCATION_OF_BLOOD_KELESETH, true);
                     me->CastSpell(me, SPELL_INVOCATION_VISUAL_ACTIVE, true);
                     _isEmpowered = true;
                     break;
                 case ACTION_REMOVE_INVOCATION:
                     _isEmpowered = false;
                     me->RemoveAurasDueToSpell(SPELL_INVOCATION_VISUAL_ACTIVE);
                     me->RemoveAurasDueToSpell(SPELL_INVOCATION_OF_BLOOD_KELESETH);
                     break;
                 default:
                     break;
             }
         }
References _isEmpowered, ACTION_CAST_INVOCATION, ACTION_REMOVE_INVOCATION, ACTION_STAND_UP, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), SummonList::DespawnEntry(), Object::ForceValuesUpdateAtIndex(), Unit::m_Events, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_KELESETH_INVOCATION, Unit::SetHealth(), Creature::SetReactState(), SPELL_INVOCATION_OF_BLOOD_KELESETH, SPELL_INVOCATION_VISUAL_ACTIVE, summons, CreatureAI::Talk(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_NPC_FLAGS, and WORLD_TRIGGER.
Referenced by EnterCombat(), EnterEvadeMode(), JustReachedHome(), and SpellHit().
EnterCombat()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 237 of file boss_blood_prince_council.cpp.
         {
             bool valid = true;
             if (Creature* keleseth = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                 if (!keleseth->IsAlive() || keleseth->IsInEvadeMode())
                     valid = false;
             if (Creature* taldaram = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                 if (!taldaram->IsAlive() || taldaram->IsInEvadeMode())
                     valid = false;
             if (Creature* valanar = instance->instance->GetCreature(instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                 if (!valanar->IsAlive() || valanar->IsInEvadeMode())
                     valid = false;
             if (!valid)
             {
                 EnterEvadeMode();
                 return;
             }
             me->RemoveAurasDueToSpell(SPELL_FEIGN_DEATH); // just in case
             me->setActive(true);
             DoZoneInCombat();
             if (!me->hasLootRecipient())
                 me->SetLootRecipient(who);
             me->LowerPlayerDamageReq(me->GetMaxHealth());
             me->SetReactState(REACT_AGGRESSIVE);
             instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me);
             if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                 if (!taldaram->IsInEvadeMode())
                     taldaram->SetInCombatWithZone();
             if (Creature* valanar = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                 if (!valanar->IsInEvadeMode())
                     valanar->SetInCombatWithZone();
             me->resetAttackTimer(BASE_ATTACK);
             DoAction(ACTION_REMOVE_INVOCATION);
             events.Reset();
             events.ScheduleEvent(EVENT_BERSERK, 600000);
             events.ScheduleEvent(EVENT_SHADOW_RESONANCE, urand(10000, 15000));
             if (IsHeroic())
                 me->AddAura(SPELL_SHADOW_PRISON, me);
         }
References ACTION_REMOVE_INVOCATION, Unit::AddAura(), BASE_ATTACK, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, DoAction(), CreatureAI::DoZoneInCombat(), ENCOUNTER_FRAME_ENGAGE, EnterEvadeMode(), EVENT_BERSERK, EVENT_SHADOW_RESONANCE, Map::GetCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), Creature::hasLootRecipient(), InstanceScript::instance, instance, ScriptedAI::IsHeroic(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Unit::resetAttackTimer(), InstanceScript::SendEncounterUnit(), WorldObject::setActive(), Creature::SetLootRecipient(), Creature::SetReactState(), SPELL_FEIGN_DEATH, SPELL_SHADOW_PRISON, and urand().
EnterEvadeMode()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 421 of file boss_blood_prince_council.cpp.
         {
             if (_evading)
                 return;
             _canDie = false;
             me->SetHealth(me->GetMaxHealth());
             DoAction(ACTION_REMOVE_INVOCATION);
             _evading = true;
             if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                 taldaram->AI()->EnterEvadeMode();
             if (Creature* valanar = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                 valanar->AI()->EnterEvadeMode();
             ScriptedAI::EnterEvadeMode();
             _evading = false;
         }
References _canDie, _evading, ACTION_REMOVE_INVOCATION, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, DoAction(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), instance, ScriptedAI::me, and Unit::SetHealth().
Referenced by EnterCombat().
InitializeAI()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 202 of file boss_blood_prince_council.cpp.
         {
             ScriptedAI::InitializeAI();
             if (me->IsAlive())
             {
                 if (Creature* c = me->SummonCreature(WORLD_TRIGGER, me->GetHomePosition()))
                 {
                     c->SetObjectScale(1.75f);
                     c->CastSpell(c, SPELL_FEIGN_DEATH, true);
                 }
                 me->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                 me->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 me->SetReactState(REACT_PASSIVE);
             }
         }
References Creature::GetHomePosition(), UnitAI::InitializeAI(), Unit::IsAlive(), ScriptedAI::me, REACT_PASSIVE, Object::SetFlag(), Creature::SetReactState(), SPELL_FEIGN_DEATH, WorldObject::SummonCreature(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and WORLD_TRIGGER.
JustDied()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 285 of file boss_blood_prince_council.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
             if (!_canDie)
             {
                 me->RemoveCorpse(false);
                 me->SetRespawnTime(10);
                 me->SaveRespawnTime();
                 Position homePos = me->GetHomePosition();
                 me->UpdatePosition(homePos);
                 me->GetMotionMaster()->Clear(false);
                 me->GetMotionMaster()->MoveIdle();
                 me->StopMovingOnCurrentPos();
                 return;
             }
             Talk(SAY_KELESETH_DEATH);
             if (Creature* taldaram = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                 if (taldaram->IsAlive())
                     Unit::Kill(taldaram, taldaram);
             if (Creature* valanar = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                 if (valanar->IsAlive())
                     Unit::Kill(valanar, valanar);
         }
References _canDie, MotionMaster::Clear(), DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, SummonList::DespawnAll(), ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), instance, Unit::Kill(), ScriptedAI::me, MotionMaster::MoveIdle(), Creature::RemoveCorpse(), Creature::SaveRespawnTime(), SAY_KELESETH_DEATH, InstanceScript::SendEncounterUnit(), Creature::SetRespawnTime(), Unit::StopMovingOnCurrentPos(), summons, CreatureAI::Talk(), and Unit::UpdatePosition().
JustReachedHome()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 319 of file boss_blood_prince_council.cpp.
         {
             _canDie = true;
             me->setActive(false);
             instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
             DoAction(ACTION_REMOVE_INVOCATION);
             me->SetHealth(1);
         }
References _canDie, ACTION_REMOVE_INVOCATION, DoAction(), ENCOUNTER_FRAME_DISENGAGE, instance, ScriptedAI::me, InstanceScript::SendEncounterUnit(), WorldObject::setActive(), and Unit::SetHealth().
Referenced by JustRespawned().
JustRespawned()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 313 of file boss_blood_prince_council.cpp.
         {
             ScriptedAI::JustRespawned();
             JustReachedHome();
         }
References JustReachedHome(), and CreatureAI::JustRespawned().
JustSummoned()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 328 of file boss_blood_prince_council.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 352 of file boss_blood_prince_council.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KELESETH_KILL);
         }
References Object::GetTypeId(), SAY_KELESETH_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 227 of file boss_blood_prince_council.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             _isEmpowered = false;
             _evading = false;
             me->SetHealth(me->GetMaxHealth());
             me->SetReactState(REACT_AGGRESSIVE);
         }
References _evading, _isEmpowered, SummonList::DespawnAll(), Unit::GetMaxHealth(), ScriptedAI::me, REACT_AGGRESSIVE, Unit::SetHealth(), Creature::SetReactState(), and summons.
SpellHit()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 358 of file boss_blood_prince_council.cpp.
         {
             if (spell->Id == 71080 && me->IsInCombat() && !me->IsInEvadeMode())
                 DoAction(ACTION_CAST_INVOCATION);
         }
References ACTION_CAST_INVOCATION, DoAction(), SpellInfo::Id, Unit::IsInCombat(), Creature::IsInEvadeMode(), and ScriptedAI::me.
UpdateAI()
void boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 395 of file boss_blood_prince_council.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     Talk(EMOTE_KELESETH_BERSERK);
                     break;
                 case EVENT_SHADOW_RESONANCE:
                     Talk(SAY_KELESETH_SPECIAL);
                     me->CastSpell(me, SPELL_SHADOW_RESONANCE, false);
                     events.ScheduleEvent(EVENT_SHADOW_RESONANCE, urand(10000, 15000));
                     break;
             }
             DoSpellAttackIfReady(_isEmpowered ? SPELL_EMPOWERED_SHADOW_LANCE : SPELL_SHADOW_LANCE);
         }
References _isEmpowered, Unit::CastSpell(), UnitAI::DoSpellAttackIfReady(), EMOTE_KELESETH_BERSERK, EVENT_BERSERK, EVENT_SHADOW_RESONANCE, Unit::HasUnitState(), ScriptedAI::me, SAY_KELESETH_SPECIAL, SPELL_BERSERK, SPELL_EMPOWERED_SHADOW_LANCE, SPELL_SHADOW_LANCE, SPELL_SHADOW_RESONANCE, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_canDie
bool boss_prince_keleseth_icc::boss_prince_kelesethAI::_canDie
Definition at line 225 of file boss_blood_prince_council.cpp.
Referenced by boss_prince_kelesethAI(), EnterEvadeMode(), JustDied(), and JustReachedHome().
_evading
bool boss_prince_keleseth_icc::boss_prince_kelesethAI::_evading
Definition at line 224 of file boss_blood_prince_council.cpp.
Referenced by EnterEvadeMode(), and Reset().
_isEmpowered
bool boss_prince_keleseth_icc::boss_prince_kelesethAI::_isEmpowered
Definition at line 223 of file boss_blood_prince_council.cpp.
Referenced by DamageTaken(), DoAction(), Reset(), and UpdateAI().
events
EventMap boss_prince_keleseth_icc::boss_prince_kelesethAI::events
Definition at line 220 of file boss_blood_prince_council.cpp.
instance
InstanceScript* boss_prince_keleseth_icc::boss_prince_kelesethAI::instance
Definition at line 222 of file boss_blood_prince_council.cpp.
Referenced by boss_prince_kelesethAI(), DamageDealt(), EnterCombat(), EnterEvadeMode(), JustDied(), and JustReachedHome().
summons
SummonList boss_prince_keleseth_icc::boss_prince_kelesethAI::summons
Definition at line 221 of file boss_blood_prince_council.cpp.
Referenced by DoAction(), JustDied(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp