Azerotcore-wotlk: src/server/game/Handlers/TradeHandler.cpp File Reference
TradeHandler.cpp File Reference
#include "Item.h"
#include "Language.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Opcodes.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SocialMgr.h"
#include "Spell.h"
#include "World.h"
#include "WorldPacket.h"
#include "WorldSession.h"
Functions
static void setAcceptTradeMode (TradeData *myTrade, TradeData *hisTrade, Item **myItems, Item **hisItems)
static void clearAcceptTradeMode (TradeData *myTrade, TradeData *hisTrade)
static void clearAcceptTradeMode (Item **myItems, Item **hisItems)
Function Documentation
clearAcceptTradeMode() [1/2]
static void clearAcceptTradeMode (Item ** myItems, Item ** hisItems) static
Definition at line 232 of file TradeHandler.cpp.
 {
     // clear 'in-trade' flag
     for (uint8 i = 0; i < TRADE_SLOT_TRADED_COUNT; ++i)
     {
         if (myItems[i])
             myItems[i]->SetInTrade(false);
         if (hisItems[i])
             hisItems[i]->SetInTrade(false);
     }
 }
References Item::SetInTrade(), and TRADE_SLOT_TRADED_COUNT.
clearAcceptTradeMode() [2/2]
static void clearAcceptTradeMode (TradeData * myTrade, TradeData * hisTrade) static
Definition at line 226 of file TradeHandler.cpp.
 {
     myTrade->SetInAcceptProcess(false);
     hisTrade->SetInAcceptProcess(false);
 }
References TradeData::SetInAcceptProcess().
Referenced by WorldSession::HandleAcceptTradeOpcode().
setAcceptTradeMode()
static void setAcceptTradeMode (TradeData * myTrade, TradeData * hisTrade, Item ** myItems, Item ** hisItems) static
Definition at line 201 of file TradeHandler.cpp.
 {
     myTrade->SetInAcceptProcess(true);
     hisTrade->SetInAcceptProcess(true);
     // store items in local list and set 'in-trade' flag
     for (uint8 i = 0; i < TRADE_SLOT_TRADED_COUNT; ++i)
     {
         if (Item* item = myTrade->GetItem(TradeSlots(i)))
         {
             LOG_DEBUG("network.opcode", "player trade item %s bag: %u slot: %u", item->GetGUID().ToString().c_str(), item->GetBagSlot(), item->GetSlot());
             //Can return nullptr
             myItems[i] = item;
             myItems[i]->SetInTrade();
         }
         if (Item* item = hisTrade->GetItem(TradeSlots(i)))
         {
             LOG_DEBUG("network.opcode", "partner trade item %s bag: %u slot: %u", item->GetGUID().ToString().c_str(), item->GetBagSlot(), item->GetSlot());
             hisItems[i] = item;
             hisItems[i]->SetInTrade();
         }
     }
 }
References TradeData::GetItem(), LOG_DEBUG, TradeData::SetInAcceptProcess(), Item::SetInTrade(), and TRADE_SLOT_TRADED_COUNT.
Referenced by WorldSession::HandleAcceptTradeOpcode().