Azerotcore-wotlk: G3D::Color1uint8 Class Reference
G3D::Color1uint8 Class Reference
#include <Color1uint8.h>
Public Member Functions
Color1uint8 ()
Color1uint8 (const uint8 _v)
Color1uint8 (const class Color1 &c)
Color1uint8 (class BinaryInput &bi)
void serialize (class BinaryOutput &bo) const
void deserialize (class BinaryInput &bi)
bool operator== (const Color1uint8 &other) const
bool operator!= (const Color1uint8 &other) const
Public Attributes
uint8 value
Private Member Functions
bool operator< (const Color1uint8 &) const
bool operator> (const Color1uint8 &) const
bool operator<= (const Color1uint8 &) const
bool operator>= (const Color1uint8 &) const
Detailed Description
Represents a Color1 as a packed integer. Convenient for creating unsigned int vertex arrays.
WARNING: Integer color formats are different than integer vertex formats. The color channels are automatically scaled by 255 (because OpenGL automatically scales integer colors back by this factor). So Color3(1,1,1) == Color3uint8(255,255,255) but Vector3(1,1,1) == Vector3int16(1,1,1).
Note: Conversion of a float32 to uint8 is accomplished by min(iFloor(f * 256)) and back to float32 by u / 255.0f. This gives equal size intervals. Consider a number line from 0 to 1 and a corresponding one from 0 to 255. If we use iRound(x * 255), then the mapping for three critical intervals are:
let s = 0.5/255
  float             int       size
[0, s)           -> 0          s
[s, s * 3)       -> 1         2*s
(1 - s, 1]       -> 255        s
If we use max(floor(x * 256), 255), then we get:
let s = 1/256
  float             int           size
[0, s)           -> 0               s
[s, 2 * s)       -> 1               s
(1 - s, 1]       -> 255             s
and the intervals are all the same size, thus giving equal precision to all values.
Definition at line 56 of file Color1uint8.h.
Constructor & Destructor Documentation
Color1uint8() [1/4]
G3D::Color1uint8::Color1uint8 () inline
Definition at line 68 of file Color1uint8.h.
 : value(0) {}
Color1uint8() [2/4]
G3D::Color1uint8::Color1uint8 (const uint8 _v) inline explicit
Definition at line 70 of file Color1uint8.h.
 : value(_v) {}
Color1uint8() [3/4]
G3D::Color1uint8::Color1uint8 (const class Color1 & c)
Definition at line 19 of file Color1uint8.cpp.
                                               : value(iClamp(iFloor(c.value * 256), 0, 255)) {
 }
Color1uint8() [4/4]
G3D::Color1uint8::Color1uint8 (class BinaryInput & bi)
Definition at line 23 of file Color1uint8.cpp.
{
     deserialize(bi);
 }
References deserialize().
Member Function Documentation
deserialize()
void G3D::Color1uint8::deserialize (class BinaryInput & bi)
Definition at line 33 of file Color1uint8.cpp.
{
     value = bi.readUInt8();
 }
References G3D::BinaryInput::readUInt8().
Referenced by Color1uint8().
operator!=()
bool G3D::Color1uint8::operator!= (const Color1uint8 & other) const inline
Definition at line 84 of file Color1uint8.h.
{
         return value != other.value;
     }
References value.
operator<()
bool G3D::Color1uint8::operator< (const Color1uint8 &) const private
operator<=()
bool G3D::Color1uint8::operator<= (const Color1uint8 &) const private
operator==()
bool G3D::Color1uint8::operator== (const Color1uint8 & other) const inline
Definition at line 80 of file Color1uint8.h.
{
         return value == other.value;
     }
References value.
operator>()
bool G3D::Color1uint8::operator> (const Color1uint8 &) const private
operator>=()
bool G3D::Color1uint8::operator>= (const Color1uint8 &) const private
serialize()
void G3D::Color1uint8::serialize (class BinaryOutput & bo) const
Definition at line 28 of file Color1uint8.cpp.
{
     bo.writeUInt8(value);
 }
References G3D::BinaryOutput::writeUInt8().
Member Data Documentation
value
uint8 G3D::Color1uint8::value
Definition at line 66 of file Color1uint8.h.
Referenced by G3D::Image3uint8::copyArray(), G3D::Image4uint8::copyArray(), G3D::Image1uint8::copyArray(), operator!=(), and operator==().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Color1uint8.h
deps/g3dlite/source/Color1uint8.cpp