Azerotcore-wotlk: at_the_beast_room Class Reference
at_the_beast_room Class Reference
Public Member Functions
at_the_beast_room ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 283 of file boss_the_beast.cpp.
Constructor & Destructor Documentation
at_the_beast_room()
at_the_beast_room::at_the_beast_room () inline
Definition at line 286 of file boss_the_beast.cpp.
 : AreaTriggerScript("at_the_beast_room") { }
Member Function Documentation
OnTrigger()
bool at_the_beast_room::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 288 of file boss_the_beast.cpp.
     {
         if (player->IsGameMaster())
         {
             return false;
         }
         if (InstanceScript* instance = player->GetInstanceScript())
         {
             if (Creature* beast = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_THE_BEAST)))
             {
                 beast->AI()->SetData(DATA_BEAST_ROOM, DATA_BEAST_ROOM);
             }
             return true;
         }
         return false;
     }
References DATA_BEAST_ROOM, DATA_THE_BEAST, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and Player::IsGameMaster().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_the_beast.cpp