Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/extent_inlines.h File Reference
extent_inlines.h File Reference
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/mutex_pool.h"
#include "jemalloc/internal/pages.h"
#include "jemalloc/internal/prng.h"
#include "jemalloc/internal/ql.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/sz.h"
Functions
static void extent_lock (tsdn_t *tsdn, extent_t *extent)
static void extent_unlock (tsdn_t *tsdn, extent_t *extent)
static void extent_lock2 (tsdn_t *tsdn, extent_t *extent1, extent_t *extent2)
static void extent_unlock2 (tsdn_t *tsdn, extent_t *extent1, extent_t *extent2)
static unsigned extent_arena_ind_get (const extent_t *extent)
static arena_t * extent_arena_get (const extent_t *extent)
static szind_t extent_szind_get_maybe_invalid (const extent_t *extent)
static szind_t extent_szind_get (const extent_t *extent)
static size_t extent_usize_get (const extent_t *extent)
static unsigned extent_binshard_get (const extent_t *extent)
static size_t extent_sn_get (const extent_t *extent)
static extent_state_t extent_state_get (const extent_t *extent)
static bool extent_zeroed_get (const extent_t *extent)
static bool extent_committed_get (const extent_t *extent)
static bool extent_dumpable_get (const extent_t *extent)
static bool extent_slab_get (const extent_t *extent)
static unsigned extent_nfree_get (const extent_t *extent)
static void * extent_base_get (const extent_t *extent)
static void * extent_addr_get (const extent_t *extent)
static size_t extent_size_get (const extent_t *extent)
static size_t extent_esn_get (const extent_t *extent)
static size_t extent_bsize_get (const extent_t *extent)
static void * extent_before_get (const extent_t *extent)
static void * extent_last_get (const extent_t *extent)
static void * extent_past_get (const extent_t *extent)
static arena_slab_data_t * extent_slab_data_get (extent_t *extent)
static const arena_slab_data_t * extent_slab_data_get_const (const extent_t *extent)
static prof_tctx_t * extent_prof_tctx_get (const extent_t *extent)
static nstime_t extent_prof_alloc_time_get (const extent_t *extent)
static void extent_arena_set (extent_t *extent, arena_t *arena)
static void extent_binshard_set (extent_t *extent, unsigned binshard)
static void extent_addr_set (extent_t *extent, void *addr)
static void extent_addr_randomize (tsdn_t *tsdn, extent_t *extent, size_t alignment)
static void extent_size_set (extent_t *extent, size_t size)
static void extent_esn_set (extent_t *extent, size_t esn)
static void extent_bsize_set (extent_t *extent, size_t bsize)
static void extent_szind_set (extent_t *extent, szind_t szind)
static void extent_nfree_set (extent_t *extent, unsigned nfree)
static void extent_nfree_binshard_set (extent_t *extent, unsigned nfree, unsigned binshard)
static void extent_nfree_inc (extent_t *extent)
static void extent_nfree_dec (extent_t *extent)
static void extent_nfree_sub (extent_t *extent, uint64_t n)
static void extent_sn_set (extent_t *extent, size_t sn)
static void extent_state_set (extent_t *extent, extent_state_t state)
static void extent_zeroed_set (extent_t *extent, bool zeroed)
static void extent_committed_set (extent_t *extent, bool committed)
static void extent_dumpable_set (extent_t *extent, bool dumpable)
static void extent_slab_set (extent_t *extent, bool slab)
static void extent_prof_tctx_set (extent_t *extent, prof_tctx_t *tctx)
static void extent_prof_alloc_time_set (extent_t *extent, nstime_t t)
static bool extent_is_head_get (extent_t *extent)
static void extent_is_head_set (extent_t *extent, bool is_head)
static void extent_init (extent_t *extent, arena_t *arena, void *addr, size_t size, bool slab, szind_t szind, size_t sn, extent_state_t state, bool zeroed, bool committed, bool dumpable, extent_head_state_t is_head)
static void extent_binit (extent_t *extent, void *addr, size_t bsize, size_t sn)
static void extent_list_init (extent_list_t *list)
static extent_t * extent_list_first (const extent_list_t *list)
static extent_t * extent_list_last (const extent_list_t *list)
static void extent_list_append (extent_list_t *list, extent_t *extent)
static void extent_list_prepend (extent_list_t *list, extent_t *extent)
static void extent_list_replace (extent_list_t *list, extent_t *to_remove, extent_t *to_insert)
static void extent_list_remove (extent_list_t *list, extent_t *extent)
static int extent_sn_comp (const extent_t *a, const extent_t *b)
static int extent_esn_comp (const extent_t *a, const extent_t *b)
static int extent_ad_comp (const extent_t *a, const extent_t *b)
static int extent_ead_comp (const extent_t *a, const extent_t *b)
static int extent_snad_comp (const extent_t *a, const extent_t *b)
static int extent_esnead_comp (const extent_t *a, const extent_t *b)
Function Documentation
extent_ad_comp()
static int extent_ad_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 460 of file extent_inlines.h.
{
     uintptr_t a_addr = (uintptr_t)extent_addr_get(a);
     uintptr_t b_addr = (uintptr_t)extent_addr_get(b);
     return (a_addr > b_addr) - (a_addr < b_addr);
 }
References mpq::a, b, extent_addr_get(), and uintptr_t.
Referenced by extent_snad_comp().
extent_addr_get()
static void* extent_addr_get (const extent_t * extent) inline static
Definition at line 133 of file extent_inlines.h.
{
     assert(extent->e_addr == PAGE_ADDR2BASE(extent->e_addr) ||
         !extent_slab_get(extent));
     return extent->e_addr;
 }
References assert(), extent_s::e_addr, extent_slab_get(), and PAGE_ADDR2BASE.
Referenced by arena_slab_reg_alloc(), arena_slab_reg_alloc_batch(), arena_slab_regind(), arena_vsalloc(), base_extent_bump_alloc_helper(), extent_ad_comp(), extent_addr_randomize(), extent_split_impl(), extent_split_interior(), extent_util_stats_verbose_get(), large_dalloc_prep_impl(), large_palloc(), large_ralloc(), large_ralloc_no_move_expand(), and large_ralloc_no_move_shrink().
extent_addr_randomize()
static void extent_addr_randomize (tsdn_t * tsdn, extent_t * extent, size_t alignment) inline static
Definition at line 216 of file extent_inlines.h.
{
     assert(extent_base_get(extent) == extent_addr_get(extent));
     if (alignment < PAGE) {
         unsigned lg_range = LG_PAGE -
             lg_floor(CACHELINE_CEILING(alignment));
         size_t r;
         if (!tsdn_null(tsdn)) {
             tsd_t *tsd = tsdn_tsd(tsdn);
             r = (size_t)prng_lg_range_u64(
                 tsd_offset_statep_get(tsd), lg_range);
         } else {
             r = prng_lg_range_zu(
                 &extent_arena_get(extent)->offset_state,
                 lg_range, true);
         }
         uintptr_t random_offset = ((uintptr_t)r) << (LG_PAGE -
             lg_range);
         extent->e_addr = (void *)((uintptr_t)extent->e_addr +
             random_offset);
         assert(ALIGNMENT_ADDR2BASE(extent->e_addr, alignment) ==
             extent->e_addr);
     }
 }
References ALIGNMENT_ADDR2BASE, assert(), CACHELINE_CEILING, extent_s::e_addr, extent_addr_get(), extent_arena_get(), extent_base_get(), lg_floor(), LG_PAGE, PAGE, prng_lg_range_u64(), prng_lg_range_zu(), tsdn_null(), tsdn_tsd(), and uintptr_t.
Referenced by extent_alloc_wrapper_hard(), extent_grow_retained(), and extent_recycle().
extent_addr_set()
static void extent_addr_set (extent_t * extent, void * addr) inline static
Definition at line 211 of file extent_inlines.h.
{
     extent->e_addr = addr;
 }
References extent_s::e_addr.
Referenced by extent_binit(), extent_dalloc_wrapper_try(), extent_destroy_wrapper(), extent_init(), and extents_dalloc().
extent_arena_get()
static arena_t* extent_arena_get (const extent_t * extent) inline static
Definition at line 48 of file extent_inlines.h.
{
     unsigned arena_ind = extent_arena_ind_get(extent);
     return (arena_t *)atomic_load_p(&arenas[arena_ind], ATOMIC_ACQUIRE);
 }
References arenas, ATOMIC_ACQUIRE, and extent_arena_ind_get().
Referenced by arena_aalloc(), arena_dalloc_small(), arena_prof_promote(), arena_ralloc_no_move(), arenas_lookup_ctl(), extent_activate_locked(), extent_addr_randomize(), extent_can_coalesce(), extent_deactivate_locked(), extent_merge_impl(), extent_recycle_extract(), extent_util_stats_verbose_get(), large_dalloc(), large_dalloc_finish(), large_dalloc_prep_junked_locked(), large_ralloc_no_move(), large_ralloc_no_move_expand(), and large_ralloc_no_move_shrink().
extent_arena_ind_get()
static unsigned extent_arena_ind_get (const extent_t * extent) inline static
Definition at line 39 of file extent_inlines.h.
{
     unsigned arena_ind = (unsigned)((extent->e_bits &
         EXTENT_BITS_ARENA_MASK) >> EXTENT_BITS_ARENA_SHIFT);
     assert(arena_ind < MALLOCX_ARENA_LIMIT);
     return arena_ind;
 }
References assert(), extent_s::e_bits, EXTENT_BITS_ARENA_MASK, EXTENT_BITS_ARENA_SHIFT, and MALLOCX_ARENA_LIMIT.
Referenced by extent_arena_get(), tcache_bin_flush_large(), and tcache_bin_flush_small().
extent_arena_set()
static void extent_arena_set (extent_t * extent, arena_t * arena) inline static
Definition at line 195 of file extent_inlines.h.
{
     unsigned arena_ind = (arena != NULL) ? arena_ind_get(arena) : ((1U <<
         MALLOCX_ARENA_BITS) - 1);
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_ARENA_MASK) |
         ((uint64_t)arena_ind << EXTENT_BITS_ARENA_SHIFT);
 }
References arena, arena_ind_get(), extent_s::e_bits, EXTENT_BITS_ARENA_MASK, EXTENT_BITS_ARENA_SHIFT, MALLOCX_ARENA_BITS, and NULL.
Referenced by extent_binit(), and extent_init().
extent_base_get()
static void* extent_base_get (const extent_t * extent) inline static
Definition at line 126 of file extent_inlines.h.
{
     assert(extent->e_addr == PAGE_ADDR2BASE(extent->e_addr) ||
         !extent_slab_get(extent));
     return PAGE_ADDR2BASE(extent->e_addr);
 }
References assert(), extent_s::e_addr, extent_slab_get(), and PAGE_ADDR2BASE.
Referenced by arena_reset(), extent_addr_randomize(), extent_before_get(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_head_no_merge(), extent_interior_deregister(), extent_interior_register(), extent_last_get(), extent_merge_impl(), extent_past_get(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_record(), extent_recycle(), extent_recycle_extract(), extent_recycle_split(), extent_rtree_leaf_elms_lookup(), extent_split_impl(), extent_split_interior(), extents_dalloc(), and extents_fit_alignment().
extent_before_get()
static void* extent_before_get (const extent_t * extent) inline static
Definition at line 155 of file extent_inlines.h.
{
     return (void *)((uintptr_t)extent_base_get(extent) - PAGE);
 }
References extent_base_get(), PAGE, and uintptr_t.
Referenced by extent_try_coalesce_impl().
extent_binit()
static void extent_binit (extent_t * extent, void * addr, size_t bsize, size_t sn) inline static
Definition at line 393 of file extent_inlines.h.
{
     extent_arena_set(extent, NULL);
     extent_addr_set(extent, addr);
     extent_bsize_set(extent, bsize);
     extent_slab_set(extent, false);
     extent_szind_set(extent, SC_NSIZES);
     extent_sn_set(extent, sn);
     extent_state_set(extent, extent_state_active);
     extent_zeroed_set(extent, true);
     extent_committed_set(extent, true);
     extent_dumpable_set(extent, true);
 }
References extent_addr_set(), extent_arena_set(), extent_bsize_set(), extent_committed_set(), extent_dumpable_set(), extent_slab_set(), extent_sn_set(), extent_state_active, extent_state_set(), extent_szind_set(), extent_zeroed_set(), NULL, and SC_NSIZES.
Referenced by base_extent_bump_alloc_helper(), and base_extent_init().
extent_binshard_get()
static unsigned extent_binshard_get (const extent_t * extent) inline static
Definition at line 75 of file extent_inlines.h.
{
     unsigned binshard = (unsigned)((extent->e_bits &
         EXTENT_BITS_BINSHARD_MASK) >> EXTENT_BITS_BINSHARD_SHIFT);
     assert(binshard < bin_infos[extent_szind_get(extent)].n_shards);
     return binshard;
 }
References assert(), bin_infos, extent_s::e_bits, EXTENT_BITS_BINSHARD_MASK, EXTENT_BITS_BINSHARD_SHIFT, and extent_szind_get().
Referenced by arena_dalloc_bin(), extent_util_stats_verbose_get(), and tcache_bin_flush_small().
extent_binshard_set()
static void extent_binshard_set (extent_t * extent, unsigned binshard) inline static
Definition at line 203 of file extent_inlines.h.
{
     /* The assertion assumes szind is set already. */
     assert(binshard < bin_infos[extent_szind_get(extent)].n_shards);
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_BINSHARD_MASK) |
         ((uint64_t)binshard << EXTENT_BITS_BINSHARD_SHIFT);
 }
References assert(), bin_infos, extent_s::e_bits, EXTENT_BITS_BINSHARD_MASK, EXTENT_BITS_BINSHARD_SHIFT, and extent_szind_get().
extent_bsize_get()
static size_t extent_bsize_get (const extent_t * extent) inline static
Definition at line 150 of file extent_inlines.h.
{
     return extent->e_bsize;
 }
References extent_s::e_bsize.
Referenced by base_auto_thp_switch(), base_extent_bump_alloc_helper(), and base_extent_bump_alloc_post().
extent_bsize_set()
static void extent_bsize_set (extent_t * extent, size_t bsize) inline static
Definition at line 254 of file extent_inlines.h.
{
     extent->e_bsize = bsize;
 }
References extent_s::e_bsize.
Referenced by extent_binit().
extent_committed_get()
static bool extent_committed_get (const extent_t * extent) inline static
Definition at line 101 of file extent_inlines.h.
{
     return (bool)((extent->e_bits & EXTENT_BITS_COMMITTED_MASK) >>
         EXTENT_BITS_COMMITTED_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_COMMITTED_MASK, and EXTENT_BITS_COMMITTED_SHIFT.
Referenced by extent_can_coalesce(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_recycle(), and extent_split_impl().
extent_committed_set()
static void extent_committed_set (extent_t * extent, bool committed) inline static
Definition at line 319 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_COMMITTED_MASK) |
         ((uint64_t)committed << EXTENT_BITS_COMMITTED_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_COMMITTED_MASK, and EXTENT_BITS_COMMITTED_SHIFT.
Referenced by extent_binit(), extent_commit_impl(), extent_decommit_wrapper(), and extent_init().
extent_dumpable_get()
static bool extent_dumpable_get (const extent_t * extent) inline static
Definition at line 107 of file extent_inlines.h.
{
     return (bool)((extent->e_bits & EXTENT_BITS_DUMPABLE_MASK) >>
         EXTENT_BITS_DUMPABLE_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_DUMPABLE_MASK, and EXTENT_BITS_DUMPABLE_SHIFT.
Referenced by extent_alloc_wrapper(), extent_dalloc_wrapper(), extent_split_impl(), extents_alloc(), and extents_dalloc().
extent_dumpable_set()
static void extent_dumpable_set (extent_t * extent, bool dumpable) inline static
Definition at line 325 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_DUMPABLE_MASK) |
         ((uint64_t)dumpable << EXTENT_BITS_DUMPABLE_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_DUMPABLE_MASK, and EXTENT_BITS_DUMPABLE_SHIFT.
Referenced by extent_binit(), and extent_init().
extent_ead_comp()
static int extent_ead_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 468 of file extent_inlines.h.
{
     uintptr_t a_eaddr = (uintptr_t)a;
     uintptr_t b_eaddr = (uintptr_t)b;
     return (a_eaddr > b_eaddr) - (a_eaddr < b_eaddr);
 }
References mpq::a, b, and uintptr_t.
Referenced by extent_esnead_comp().
extent_esn_comp()
static int extent_esn_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 452 of file extent_inlines.h.
{
     size_t a_esn = extent_esn_get(a);
     size_t b_esn = extent_esn_get(b);
     return (a_esn > b_esn) - (a_esn < b_esn);
 }
References mpq::a, b, and extent_esn_get().
Referenced by extent_esnead_comp().
extent_esn_get()
static size_t extent_esn_get (const extent_t * extent) inline static
Definition at line 145 of file extent_inlines.h.
{
     return (extent->e_size_esn & EXTENT_ESN_MASK);
 }
References extent_s::e_size_esn, and EXTENT_ESN_MASK.
Referenced by extent_esn_comp().
extent_esn_set()
static void extent_esn_set (extent_t * extent, size_t esn) inline static
Definition at line 248 of file extent_inlines.h.
{
     extent->e_size_esn = (extent->e_size_esn & ~EXTENT_ESN_MASK) | (esn &
         EXTENT_ESN_MASK);
 }
References extent_s::e_size_esn, and EXTENT_ESN_MASK.
Referenced by base_alloc_extent().
extent_esnead_comp()
static int extent_esnead_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 489 of file extent_inlines.h.
{
     int ret;
     ret = extent_esn_comp(a, b);
     if (ret != 0) {
         return ret;
     }
     ret = extent_ead_comp(a, b);
     return ret;
 }
References mpq::a, b, extent_ead_comp(), extent_esn_comp(), and ret.
extent_init()
static void extent_init (extent_t * extent, arena_t * arena, void * addr, size_t size, bool slab, szind_t szind, size_t sn, extent_state_t state, bool zeroed, bool committed, bool dumpable, extent_head_state_t is_head) inline static
Definition at line 367 of file extent_inlines.h.
{
     assert(addr == PAGE_ADDR2BASE(addr) || !slab);
     extent_arena_set(extent, arena);
     extent_addr_set(extent, addr);
     extent_size_set(extent, size);
     extent_slab_set(extent, slab);
     extent_szind_set(extent, szind);
     extent_sn_set(extent, sn);
     extent_state_set(extent, state);
     extent_zeroed_set(extent, zeroed);
     extent_committed_set(extent, committed);
     extent_dumpable_set(extent, dumpable);
     ql_elm_new(extent, ql_link);
     if (!maps_coalesce) {
         extent_is_head_set(extent, (is_head == EXTENT_IS_HEAD) ? true :
             false);
     }
     if (config_prof) {
         extent_prof_tctx_set(extent, NULL);
     }
 }
References arena, assert(), config_prof, extent_addr_set(), extent_arena_set(), extent_committed_set(), extent_dumpable_set(), EXTENT_IS_HEAD, extent_is_head_set(), extent_prof_tctx_set(), extent_size_set(), extent_slab_set(), extent_sn_set(), extent_state_set(), extent_szind_set(), extent_zeroed_set(), maps_coalesce, NULL, PAGE_ADDR2BASE, and ql_elm_new.
Referenced by extent_alloc_dss(), extent_alloc_wrapper_hard(), extent_grow_retained(), and extent_split_impl().
extent_is_head_get()
static bool extent_is_head_get (extent_t * extent) inline static
Definition at line 347 of file extent_inlines.h.
{
     if (maps_coalesce) {
         not_reached();
     }
     return (bool)((extent->e_bits & EXTENT_BITS_IS_HEAD_MASK) >>
         EXTENT_BITS_IS_HEAD_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_IS_HEAD_MASK, EXTENT_BITS_IS_HEAD_SHIFT, maps_coalesce, and not_reached.
Referenced by extent_head_no_merge().
extent_is_head_set()
static void extent_is_head_set (extent_t * extent, bool is_head) inline static
Definition at line 357 of file extent_inlines.h.
{
     if (maps_coalesce) {
         not_reached();
     }
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_IS_HEAD_MASK) |
         ((uint64_t)is_head << EXTENT_BITS_IS_HEAD_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_IS_HEAD_MASK, EXTENT_BITS_IS_HEAD_SHIFT, maps_coalesce, and not_reached.
Referenced by extent_init().
extent_last_get()
static void* extent_last_get (const extent_t * extent) inline static
Definition at line 160 of file extent_inlines.h.
{
     return (void *)((uintptr_t)extent_base_get(extent) +
         extent_size_get(extent) - PAGE);
 }
References extent_base_get(), extent_size_get(), PAGE, and uintptr_t.
Referenced by extent_rtree_leaf_elms_lookup().
extent_list_append()
static void extent_list_append (extent_list_t * list, extent_t * extent) inline static
Definition at line 422 of file extent_inlines.h.
{
     ql_tail_insert(list, extent, ql_link);
 }
References list(), and ql_tail_insert.
Referenced by arena_bin_slabs_full_insert(), arena_stash_decayed(), extents_insert_locked(), and large_palloc().
extent_list_first()
static extent_t* extent_list_first (const extent_list_t * list) inline static
Definition at line 412 of file extent_inlines.h.
{
     return ql_first(list);
 }
References list(), and ql_first.
Referenced by arena_bin_reset(), arena_decay_stashed(), arena_reset(), and extents_evict().
extent_list_init()
static void extent_list_init (extent_list_t * list) inline static
Definition at line 407 of file extent_inlines.h.
{
     ql_new(list);
 }
References list(), and ql_new.
Referenced by arena_decay_to_limit(), arena_new(), bin_init(), and ph_gen().
extent_list_last()
static extent_t* extent_list_last (const extent_list_t * list) inline static
Definition at line 417 of file extent_inlines.h.
{
     return ql_last(list, ql_link);
 }
References list(), and ql_last.
extent_list_prepend()
static void extent_list_prepend (extent_list_t * list, extent_t * extent) inline static
Definition at line 427 of file extent_inlines.h.
{
     ql_head_insert(list, extent, ql_link);
 }
References list(), and ql_head_insert.
extent_list_remove()
static void extent_list_remove (extent_list_t * list, extent_t * extent) inline static
Definition at line 439 of file extent_inlines.h.
{
     ql_remove(list, extent, ql_link);
 }
References list(), and ql_remove.
Referenced by arena_bin_slabs_full_remove(), arena_decay_stashed(), extents_remove_locked(), and large_dalloc_prep_impl().
extent_list_replace()
static void extent_list_replace (extent_list_t * list, extent_t * to_remove, extent_t * to_insert) inline static
Definition at line 432 of file extent_inlines.h.
{
     ql_after_insert(to_remove, to_insert, ql_link);
     ql_remove(list, to_remove, ql_link);
 }
References list(), ql_after_insert, and ql_remove.
extent_lock()
static void extent_lock (tsdn_t * tsdn, extent_t * extent) inline static
Definition at line 13 of file extent_inlines.h.
{
     assert(extent != NULL);
     mutex_pool_lock(tsdn, &extent_mutex_pool, (uintptr_t)extent);
 }
References assert(), extent_mutex_pool, mutex_pool_lock(), and NULL.
Referenced by extent_deregister_impl(), extent_register_impl(), and extent_rtree_leaf_elm_try_lock().
extent_lock2()
static void extent_lock2 (tsdn_t * tsdn, extent_t * extent1, extent_t * extent2) inline static
Definition at line 25 of file extent_inlines.h.
{
     assert(extent1 != NULL && extent2 != NULL);
     mutex_pool_lock2(tsdn, &extent_mutex_pool, (uintptr_t)extent1,
         (uintptr_t)extent2);
 }
References assert(), extent_mutex_pool, mutex_pool_lock2(), and NULL.
Referenced by extent_merge_impl(), and extent_split_impl().
extent_nfree_binshard_set()
static void extent_nfree_binshard_set (extent_t * extent, unsigned nfree, unsigned binshard) inline static
Definition at line 273 of file extent_inlines.h.
{
     /* The assertion assumes szind is set already. */
     assert(binshard < bin_infos[extent_szind_get(extent)].n_shards);
     extent->e_bits = (extent->e_bits &
         (~EXTENT_BITS_NFREE_MASK & ~EXTENT_BITS_BINSHARD_MASK)) |
         ((uint64_t)binshard << EXTENT_BITS_BINSHARD_SHIFT) |
         ((uint64_t)nfree << EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), bin_infos, extent_s::e_bits, EXTENT_BITS_BINSHARD_MASK, EXTENT_BITS_BINSHARD_SHIFT, EXTENT_BITS_NFREE_MASK, EXTENT_BITS_NFREE_SHIFT, and extent_szind_get().
Referenced by arena_slab_alloc().
extent_nfree_dec()
static void extent_nfree_dec (extent_t * extent) inline static
Definition at line 289 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     extent->e_bits -= ((uint64_t)1U << EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_NFREE_SHIFT, and extent_slab_get().
Referenced by arena_slab_reg_alloc().
extent_nfree_get()
static unsigned extent_nfree_get (const extent_t * extent) inline static
Definition at line 119 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     return (unsigned)((extent->e_bits & EXTENT_BITS_NFREE_MASK) >>
         EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_NFREE_MASK, EXTENT_BITS_NFREE_SHIFT, and extent_slab_get().
Referenced by arena_bin_lower_slab(), arena_bin_malloc_hard(), arena_bin_slabs_full_insert(), arena_bin_slabs_nonfull_insert(), arena_dalloc_bin_locked_impl(), arena_malloc_small(), arena_slab_reg_alloc(), arena_slab_reg_alloc_batch(), arena_slab_reg_dalloc(), arena_tcache_fill_small(), extent_util_stats_get(), and extent_util_stats_verbose_get().
extent_nfree_inc()
static void extent_nfree_inc (extent_t * extent) inline static
Definition at line 283 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     extent->e_bits += ((uint64_t)1U << EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_NFREE_SHIFT, and extent_slab_get().
Referenced by arena_slab_reg_dalloc().
extent_nfree_set()
static void extent_nfree_set (extent_t * extent, unsigned nfree) inline static
Definition at line 266 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_NFREE_MASK) |
         ((uint64_t)nfree << EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_NFREE_MASK, EXTENT_BITS_NFREE_SHIFT, and extent_slab_get().
extent_nfree_sub()
static void extent_nfree_sub (extent_t * extent, uint64_t n) inline static
Definition at line 295 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     extent->e_bits -= (n << EXTENT_BITS_NFREE_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_NFREE_SHIFT, and extent_slab_get().
Referenced by arena_slab_reg_alloc_batch().
extent_past_get()
static void* extent_past_get (const extent_t * extent) inline static
Definition at line 166 of file extent_inlines.h.
{
     return (void *)((uintptr_t)extent_base_get(extent) +
         extent_size_get(extent));
 }
References extent_base_get(), extent_size_get(), and uintptr_t.
Referenced by arena_slab_regind(), extent_split_interior(), extent_try_coalesce_impl(), and large_ralloc_no_move_expand().
extent_prof_alloc_time_get()
static nstime_t extent_prof_alloc_time_get (const extent_t * extent) inline static
Definition at line 190 of file extent_inlines.h.
{
     return extent->e_alloc_time;
 }
References extent_s::e_alloc_time.
Referenced by large_prof_alloc_time_get().
extent_prof_alloc_time_set()
static void extent_prof_alloc_time_set (extent_t * extent, nstime_t t) inline static
Definition at line 342 of file extent_inlines.h.
{
     nstime_copy(&extent->e_alloc_time, &t);
 }
References extent_s::e_alloc_time, and nstime_copy.
Referenced by large_prof_alloc_time_set().
extent_prof_tctx_get()
static prof_tctx_t* extent_prof_tctx_get (const extent_t * extent) inline static
Definition at line 184 of file extent_inlines.h.
{
     return (prof_tctx_t *)atomic_load_p(&extent->e_prof_tctx,
         ATOMIC_ACQUIRE);
 }
References ATOMIC_ACQUIRE, and extent_s::e_prof_tctx.
Referenced by large_prof_tctx_get().
extent_prof_tctx_set()
static void extent_prof_tctx_set (extent_t * extent, prof_tctx_t * tctx) inline static
Definition at line 337 of file extent_inlines.h.
{
     atomic_store_p(&extent->e_prof_tctx, tctx, ATOMIC_RELEASE);
 }
References ATOMIC_RELEASE, extent_s::e_prof_tctx, and tctx.
Referenced by extent_init(), and large_prof_tctx_set().
extent_size_get()
static size_t extent_size_get (const extent_t * extent) inline static
Definition at line 140 of file extent_inlines.h.
{
     return (extent->e_size_esn & EXTENT_SIZE_MASK);
 }
References extent_s::e_size_esn, and EXTENT_SIZE_MASK.
Referenced by arena_decay_extent(), arena_decay_stashed(), arena_extent_dalloc_large_prep(), arena_slab_alloc(), arena_slab_dalloc(), arena_stash_decayed(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_gdump_add(), extent_gdump_sub(), extent_grow_retained(), extent_interior_deregister(), extent_interior_register(), extent_last_get(), extent_merge_impl(), extent_past_get(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_record(), extent_recycle(), extent_recycle_extract(), extent_split_impl(), extent_split_interior(), extent_util_stats_get(), extent_util_stats_verbose_get(), extents_abandon_vm(), extents_dalloc(), extents_first_fit_locked(), extents_fit_alignment(), extents_insert_locked(), extents_remove_locked(), and large_ralloc_no_move_shrink().
extent_size_set()
static void extent_size_set (extent_t * extent, size_t size) inline static
Definition at line 242 of file extent_inlines.h.
{
     assert((size & ~EXTENT_SIZE_MASK) == 0);
     extent->e_size_esn = size | (extent->e_size_esn & ~EXTENT_SIZE_MASK);
 }
References assert(), extent_s::e_size_esn, and EXTENT_SIZE_MASK.
Referenced by extent_init(), extent_merge_impl(), and extent_split_impl().
extent_slab_data_get()
static arena_slab_data_t* extent_slab_data_get (extent_t * extent) inline static
Definition at line 172 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     return &extent->e_slab_data;
 }
References assert(), extent_s::e_slab_data, and extent_slab_get().
Referenced by arena_dalloc_bin_locked_impl(), arena_slab_alloc(), arena_slab_reg_alloc(), and arena_slab_reg_alloc_batch().
extent_slab_data_get_const()
static const arena_slab_data_t* extent_slab_data_get_const (const extent_t * extent) inline static
Definition at line 178 of file extent_inlines.h.
{
     assert(extent_slab_get(extent));
     return &extent->e_slab_data;
 }
References assert(), extent_s::e_slab_data, and extent_slab_get().
extent_slab_get()
static bool extent_slab_get (const extent_t * extent) inline static
Definition at line 113 of file extent_inlines.h.
{
     return (bool)((extent->e_bits & EXTENT_BITS_SLAB_MASK) >>
         EXTENT_BITS_SLAB_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_SLAB_MASK, and EXTENT_BITS_SLAB_SHIFT.
Referenced by arena_dalloc(), arena_dalloc_no_tcache(), arena_prof_alloc_time_get(), arena_prof_alloc_time_set(), arena_prof_tctx_get(), arena_prof_tctx_reset(), arena_prof_tctx_set(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_slab_alloc(), arena_vsalloc(), extent_addr_get(), extent_base_get(), extent_deregister_impl(), extent_interior_deregister(), extent_interior_register(), extent_nfree_dec(), extent_nfree_get(), extent_nfree_inc(), extent_nfree_set(), extent_nfree_sub(), extent_record(), extent_register_impl(), extent_slab_data_get(), extent_slab_data_get_const(), extent_util_stats_get(), and extent_util_stats_verbose_get().
extent_slab_set()
static void extent_slab_set (extent_t * extent, bool slab) inline static
Definition at line 331 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_SLAB_MASK) |
         ((uint64_t)slab << EXTENT_BITS_SLAB_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_SLAB_MASK, and EXTENT_BITS_SLAB_SHIFT.
Referenced by extent_binit(), extent_deregister_impl(), extent_grow_retained(), extent_init(), extent_record(), and extent_recycle().
extent_sn_comp()
static int extent_sn_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 444 of file extent_inlines.h.
{
     size_t a_sn = extent_sn_get(a);
     size_t b_sn = extent_sn_get(b);
     return (a_sn > b_sn) - (a_sn < b_sn);
 }
References mpq::a, b, and extent_sn_get().
Referenced by extent_head_no_merge(), and extent_snad_comp().
extent_sn_get()
static size_t extent_sn_get (const extent_t * extent) inline static
Definition at line 83 of file extent_inlines.h.
{
     return (size_t)((extent->e_bits & EXTENT_BITS_SN_MASK) >>
         EXTENT_BITS_SN_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_SN_MASK, and EXTENT_BITS_SN_SHIFT.
Referenced by base_alloc_impl(), base_extent_bump_alloc_helper(), extent_merge_impl(), extent_sn_comp(), and extent_split_impl().
extent_sn_set()
static void extent_sn_set (extent_t * extent, size_t sn) inline static
Definition at line 301 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_SN_MASK) |
         ((uint64_t)sn << EXTENT_BITS_SN_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_SN_MASK, and EXTENT_BITS_SN_SHIFT.
Referenced by extent_binit(), extent_init(), and extent_merge_impl().
extent_snad_comp()
static int extent_snad_comp (const extent_t * a, const extent_t * b) inline static
Definition at line 476 of file extent_inlines.h.
{
     int ret;
     ret = extent_sn_comp(a, b);
     if (ret != 0) {
         return ret;
     }
     ret = extent_ad_comp(a, b);
     return ret;
 }
References mpq::a, b, extent_ad_comp(), extent_sn_comp(), and ret.
Referenced by arena_bin_lower_slab(), and extents_first_fit_locked().
extent_state_get()
static extent_state_t extent_state_get (const extent_t * extent) inline static
Definition at line 89 of file extent_inlines.h.
{
     return (extent_state_t)((extent->e_bits & EXTENT_BITS_STATE_MASK) >>
         EXTENT_BITS_STATE_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_STATE_MASK, and EXTENT_BITS_STATE_SHIFT.
Referenced by arena_vsalloc(), extent_activate_locked(), extent_can_coalesce(), extent_dalloc_wrapper(), extent_deactivate_locked(), extent_gdump_add(), extent_gdump_sub(), extent_record(), extent_recycle(), extent_recycle_extract(), extent_split_impl(), extents_insert_locked(), and extents_remove_locked().
extent_state_set()
static void extent_state_set (extent_t * extent, extent_state_t state) inline static
Definition at line 307 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_STATE_MASK) |
         ((uint64_t)state << EXTENT_BITS_STATE_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_STATE_MASK, and EXTENT_BITS_STATE_SHIFT.
Referenced by extent_activate_locked(), extent_binit(), extent_deactivate_locked(), extent_init(), extent_try_delayed_coalesce(), and extents_evict().
extent_szind_get()
static szind_t extent_szind_get (const extent_t * extent) inline static
Definition at line 63 of file extent_inlines.h.
{
     szind_t szind = extent_szind_get_maybe_invalid(extent);
     assert(szind < SC_NSIZES); /* Never call when "invalid". */
     return szind;
 }
References assert(), extent_szind_get_maybe_invalid(), and SC_NSIZES.
Referenced by arena_dalloc(), arena_dalloc_bin(), arena_dalloc_no_tcache(), arena_dissociate_bin_slab(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_slab_reg_dalloc(), extent_binshard_get(), extent_binshard_set(), extent_nfree_binshard_set(), extent_usize_get(), extent_util_stats_get(), and extent_util_stats_verbose_get().
extent_szind_get_maybe_invalid()
static szind_t extent_szind_get_maybe_invalid (const extent_t * extent) inline static
Definition at line 55 of file extent_inlines.h.
{
     szind_t szind = (szind_t)((extent->e_bits & EXTENT_BITS_SZIND_MASK) >>
         EXTENT_BITS_SZIND_SHIFT);
     assert(szind <= SC_NSIZES);
     return szind;
 }
References assert(), extent_s::e_bits, EXTENT_BITS_SZIND_MASK, EXTENT_BITS_SZIND_SHIFT, and SC_NSIZES.
Referenced by extent_register_impl(), and extent_szind_get().
extent_szind_set()
static void extent_szind_set (extent_t * extent, szind_t szind) inline static
Definition at line 259 of file extent_inlines.h.
{
     assert(szind <= SC_NSIZES); /* SC_NSIZES means "invalid". */
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_SZIND_MASK) |
         ((uint64_t)szind << EXTENT_BITS_SZIND_SHIFT);
 }
References assert(), extent_s::e_bits, EXTENT_BITS_SZIND_MASK, EXTENT_BITS_SZIND_SHIFT, and SC_NSIZES.
Referenced by arena_prof_demote(), arena_prof_promote(), extent_binit(), extent_init(), extent_merge_impl(), extent_record(), extent_split_impl(), extent_split_interior(), and large_ralloc_no_move_expand().
extent_unlock()
static void extent_unlock (tsdn_t * tsdn, extent_t * extent) inline static
Definition at line 19 of file extent_inlines.h.
{
     assert(extent != NULL);
     mutex_pool_unlock(tsdn, &extent_mutex_pool, (uintptr_t)extent);
 }
References assert(), extent_mutex_pool, mutex_pool_unlock(), and NULL.
Referenced by extent_deregister_impl(), extent_recycle_extract(), extent_register_impl(), extent_rtree_leaf_elm_try_lock(), and extent_try_coalesce_impl().
extent_unlock2()
static void extent_unlock2 (tsdn_t * tsdn, extent_t * extent1, extent_t * extent2) inline static
Definition at line 32 of file extent_inlines.h.
{
     assert(extent1 != NULL && extent2 != NULL);
     mutex_pool_unlock2(tsdn, &extent_mutex_pool, (uintptr_t)extent1,
         (uintptr_t)extent2);
 }
References assert(), extent_mutex_pool, mutex_pool_unlock2(), and NULL.
Referenced by extent_merge_impl(), and extent_split_impl().
extent_usize_get()
static size_t extent_usize_get (const extent_t * extent) inline static
Definition at line 70 of file extent_inlines.h.
{
     return sz_index2size(extent_szind_get(extent));
 }
References extent_szind_get(), and sz_index2size().
Referenced by arena_dalloc_promoted(), arena_extent_dalloc_large_prep(), arena_extent_ralloc_large_expand(), arena_extent_ralloc_large_shrink(), arena_ralloc_no_move(), extent_util_stats_get(), extent_util_stats_verbose_get(), large_dalloc_prep_impl(), large_palloc(), large_ralloc(), large_ralloc_no_move(), large_ralloc_no_move_expand(), large_ralloc_no_move_shrink(), and large_salloc().
extent_zeroed_get()
static bool extent_zeroed_get (const extent_t * extent) inline static
Definition at line 95 of file extent_inlines.h.
{
     return (bool)((extent->e_bits & EXTENT_BITS_ZEROED_MASK) >>
         EXTENT_BITS_ZEROED_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_ZEROED_MASK, and EXTENT_BITS_ZEROED_SHIFT.
Referenced by extent_grow_retained(), extent_merge_impl(), extent_record(), extent_recycle(), and extent_split_impl().
extent_zeroed_set()
static void extent_zeroed_set (extent_t * extent, bool zeroed) inline static
Definition at line 313 of file extent_inlines.h.
{
     extent->e_bits = (extent->e_bits & ~EXTENT_BITS_ZEROED_MASK) |
         ((uint64_t)zeroed << EXTENT_BITS_ZEROED_SHIFT);
 }
References extent_s::e_bits, EXTENT_BITS_ZEROED_MASK, and EXTENT_BITS_ZEROED_SHIFT.
Referenced by extent_binit(), extent_dalloc_wrapper(), extent_grow_retained(), extent_init(), extent_merge_impl(), extent_recycle(), and extents_dalloc().