Azerotcore-wotlk: FollowMovementGenerator< T > Class Template Reference
FollowMovementGenerator< T > Class Template Reference
#include <TargetedMovementGenerator.h>
Public Member Functions
FollowMovementGenerator (Unit *target, float range, ChaseAngle angle)
~FollowMovementGenerator ()
MovementGeneratorType GetMovementGeneratorType ()
bool DoUpdate (T *, uint32)
void DoInitialize (T *)
void DoFinalize (T *)
void DoReset (T *)
void MovementInform (T *)
Unit * GetTarget () const
void unitSpeedChanged ()
bool PositionOkay (Unit *target, bool isPlayerPet, bool &targetIsMoving, uint32 diff)
float GetFollowRange () const
Public Member Functions inherited from MovementGeneratorMedium< T, FollowMovementGenerator< T > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit *target)
void stopFollowing ()
Static Public Member Functions
static void _clearUnitStateMove (T *u)
static void _addUnitStateMove (T *u)
Private Attributes
std::unique_ptr< PathGenerator > i_path
TimeTrackerSmall i_recheckPredictedDistanceTimer
bool i_recheckPredictedDistance
Optional< Position > _lastTargetPosition
Optional< Position > _lastPredictedPosition
float _range
ChaseAngle _angle
Additional Inherited Members
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
template<class T>
class FollowMovementGenerator< T >
Definition at line 74 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
FollowMovementGenerator()
template<class T > FollowMovementGenerator< T >::FollowMovementGenerator (Unit * target, float range, ChaseAngle angle) inline
Definition at line 77 of file TargetedMovementGenerator.h.
         : TargetedMovementGeneratorBase(target), i_path(nullptr), i_recheckPredictedDistanceTimer(0), i_recheckPredictedDistance(false), _range(range), _angle(angle) {}
~FollowMovementGenerator()
template<class T > FollowMovementGenerator< T >::~FollowMovementGenerator () inline
Definition at line 79 of file TargetedMovementGenerator.h.
 { }
Member Function Documentation
_addUnitStateMove()
template<class T > static void FollowMovementGenerator< T >::_addUnitStateMove (T * u) inline static
Definition at line 96 of file TargetedMovementGenerator.h.
 { u->AddUnitState(UNIT_STATE_FOLLOW_MOVE); }
References UNIT_STATE_FOLLOW_MOVE.
_clearUnitStateMove()
template<class T > static void FollowMovementGenerator< T >::_clearUnitStateMove (T * u) inline static
Definition at line 95 of file TargetedMovementGenerator.h.
 { u->ClearUnitState(UNIT_STATE_FOLLOW_MOVE); }
References UNIT_STATE_FOLLOW_MOVE.
DoFinalize()
template<class T > template void FollowMovementGenerator< T >::DoFinalize (T *)
Definition at line 483 of file TargetedMovementGenerator.cpp.
 {
     owner->ClearUnitState(UNIT_STATE_FOLLOW | UNIT_STATE_FOLLOW_MOVE);
 }
References UNIT_STATE_FOLLOW, and UNIT_STATE_FOLLOW_MOVE.
DoInitialize()
template<class T > template void FollowMovementGenerator< T >::DoInitialize (T *)
Definition at line 475 of file TargetedMovementGenerator.cpp.
 {
     i_path = nullptr;
     _lastTargetPosition.reset();
     owner->AddUnitState(UNIT_STATE_FOLLOW);
 }
References UNIT_STATE_FOLLOW.
DoReset()
template<class T > template void FollowMovementGenerator< T >::DoReset (T *)
Definition at line 489 of file TargetedMovementGenerator.cpp.
 {
     DoInitialize(owner);
 }
DoUpdate()
template<class T > template bool FollowMovementGenerator< T >::DoUpdate (T * , uint32)
Definition at line 366 of file TargetedMovementGenerator.cpp.
 {
     if (!i_target.isValid() || !i_target->IsInWorld() || !owner->IsInMap(i_target.getTarget()))
         return false;
     if (!owner || !owner->IsAlive())
         return false;
     Creature* cOwner = owner->ToCreature();
     Unit* target = i_target.getTarget();
     // the owner might be unable to move (rooted or casting), or we have lost the target, pause movement
     if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || (cOwner && owner->ToCreature()->IsMovementPreventedByCasting()))
     {
         i_path = nullptr;
         owner->StopMoving();
         _lastTargetPosition.reset();
         return true;
     }
     bool followingMaster = false;
     Pet* oPet = owner->ToPet();
     if (oPet)
     {
         if (target->GetGUID() == oPet->GetOwnerGUID())
             followingMaster = true;
     }
     bool forceDest =
         (followingMaster) || // allow pets following their master to cheat while generating paths
         (i_target->GetTypeId() == TYPEID_PLAYER && i_target->ToPlayer()->IsGameMaster()) // for .npc follow
         ; // closes "bool forceDest", that way it is more appropriate, so we can comment out crap whenever we need to
     bool targetIsMoving = false;
     if (PositionOkay(target, owner->IsGuardian() && target->GetTypeId() == TYPEID_PLAYER, targetIsMoving, time_diff))
     {
         if (owner->HasUnitState(UNIT_STATE_FOLLOW_MOVE) && owner->movespline->Finalized())
         {
             owner->ClearUnitState(UNIT_STATE_FOLLOW_MOVE);
             i_path = nullptr;
             MovementInform(owner);
             if (i_recheckPredictedDistance)
             {
                 i_recheckPredictedDistanceTimer.Reset(1000);
             }
             owner->SetFacingTo(target->GetOrientation());
         }
     }
     else
     {
         Position targetPosition = target->GetPosition();
         _lastTargetPosition = targetPosition;
         // If player is moving and their position is not updated, we need to predict position
         if (targetIsMoving)
         {
             Position predictedPosition = PredictPosition(target);
             if (_lastPredictedPosition && _lastPredictedPosition->GetExactDistSq(&predictedPosition) < 0.25f)
                 return true;
             _lastPredictedPosition = predictedPosition;
             targetPosition = predictedPosition;
             i_recheckPredictedDistance = true;
         }
         else
         {
             i_recheckPredictedDistance = false;
             i_recheckPredictedDistanceTimer.Reset(0);
         }
         if (!i_path)
             i_path = std::make_unique<PathGenerator>(owner);
         else
             i_path->Clear();
         float distance = _range - target->GetCombatReach();
         float relAngle = _angle.RelativeAngle;
         float x, y, z;
         target->GetNearPoint(owner, x, y, z, owner->GetCombatReach(), distance, target->ToAbsoluteAngle(relAngle), 0.f, &targetPosition);
         if (owner->IsHovering())
             owner->UpdateAllowedPositionZ(x, y, z);
         bool success = i_path->CalculatePath(x, y, z, forceDest);
         if (!success || (i_path->GetPathType() & PATHFIND_NOPATH && !followingMaster))
         {
             if (!owner->IsStopped())
                 owner->StopMoving();
             return true;
         }
         owner->AddUnitState(UNIT_STATE_FOLLOW_MOVE);
         Movement::MoveSplineInit init(owner);
         init.MovebyPath(i_path->GetPath());
         init.SetWalk(target->IsWalking());
         if (Optional<float> velocity = GetVelocity(owner, target, i_path->GetActualEndPosition(), owner->IsGuardian() && target->GetTypeId() == TYPEID_PLAYER))
             init.SetVelocity(*velocity);
         init.Launch();
     }
     return true;
 }
References Unit::ClearUnitState(), Unit::GetCombatReach(), Object::GetGUID(), WorldObject::GetNearPoint(), Position::GetOrientation(), Unit::GetOwnerGUID(), Position::GetPosition(), Object::GetTypeId(), GetVelocity(), Unit::IsGuardian(), Creature::IsMovementPreventedByCasting(), Unit::IsWalking(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), PATHFIND_NOPATH, PredictPosition(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), Unit::StopMoving(), Position::ToAbsoluteAngle(), Object::ToCreature(), Unit::ToPet(), TYPEID_PLAYER, UNIT_STATE_FOLLOW_MOVE, and UNIT_STATE_NOT_MOVE.
GetFollowRange()
template<class T > float FollowMovementGenerator< T >::GetFollowRange () const inline
Definition at line 98 of file TargetedMovementGenerator.h.
 { return _range; }
References FollowMovementGenerator< T >::_range.
GetMovementGeneratorType()
template<class T > MovementGeneratorType FollowMovementGenerator< T >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 81 of file TargetedMovementGenerator.h.
 { return FOLLOW_MOTION_TYPE; }
References FOLLOW_MOTION_TYPE.
GetTarget()
template<class T > Unit* FollowMovementGenerator< T >::GetTarget () const inline
Definition at line 89 of file TargetedMovementGenerator.h.
 { return i_target.getTarget(); }
References Reference< TO, FROM >::getTarget(), and TargetedMovementGeneratorBase::i_target.
Referenced by npc_commandscript::HandleNpcUnFollowCommand().
MovementInform()
template<class T > void FollowMovementGenerator< T >::MovementInform (T * owner)
Definition at line 495 of file TargetedMovementGenerator.cpp.
 {
     if (owner->GetTypeId() != TYPEID_UNIT)
         return;
     // Pass back the GUIDLow of the target. If it is pet's owner then PetAI will handle
     if (CreatureAI* AI = owner->ToCreature()->AI())
         AI->MovementInform(FOLLOW_MOTION_TYPE, i_target.getTarget()->GetGUID().GetCounter());
 }
References FOLLOW_MOTION_TYPE, and TYPEID_UNIT.
PositionOkay()
template<class T > bool FollowMovementGenerator< T >::PositionOkay (Unit * target, bool isPlayerPet, bool & targetIsMoving, uint32 diff)
Definition at line 321 of file TargetedMovementGenerator.cpp.
 {
     if (!_lastTargetPosition)
         return false;
     float exactDistSq = target->GetExactDistSq(_lastTargetPosition->GetPositionX(), _lastTargetPosition->GetPositionY(), _lastTargetPosition->GetPositionZ());
     float distanceTolerance = 0.25f;
     // For creatures, increase tolerance
     if (target->GetTypeId() == TYPEID_UNIT)
     {
         distanceTolerance += _range + _range;
     }
     if (isPlayerPet)
     {
         targetIsMoving = target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_FORWARD | MOVEMENTFLAG_BACKWARD | MOVEMENTFLAG_STRAFE_LEFT | MOVEMENTFLAG_STRAFE_RIGHT);
     }
     if (exactDistSq > distanceTolerance)
         return false;
     if (isPlayerPet)
     {
         if (!targetIsMoving)
         {
             if (i_recheckPredictedDistanceTimer.GetExpiry())
             {
                 i_recheckPredictedDistanceTimer.Update(diff);
                 if (i_recheckPredictedDistanceTimer.Passed())
                 {
                     i_recheckPredictedDistanceTimer = 0;
                     return false;
                 }
             }
             return true;
         }
         return false;
     }
     return true;
 }
References Position::GetExactDistSq(), Object::GetTypeId(), MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, MOVEMENTFLAG_BACKWARD, MOVEMENTFLAG_FORWARD, MOVEMENTFLAG_STRAFE_LEFT, MOVEMENTFLAG_STRAFE_RIGHT, and TYPEID_UNIT.
unitSpeedChanged()
template<class T > void FollowMovementGenerator< T >::unitSpeedChanged () inline virtual
Reimplemented from MovementGenerator.
Definition at line 91 of file TargetedMovementGenerator.h.
 { _lastTargetPosition.reset(); }
References FollowMovementGenerator< T >::_lastTargetPosition.
Member Data Documentation
_angle
template<class T > ChaseAngle FollowMovementGenerator< T >::_angle private
Definition at line 108 of file TargetedMovementGenerator.h.
_lastPredictedPosition
template<class T > Optional<Position> FollowMovementGenerator< T >::_lastPredictedPosition private
Definition at line 106 of file TargetedMovementGenerator.h.
_lastTargetPosition
template<class T > Optional<Position> FollowMovementGenerator< T >::_lastTargetPosition private
Definition at line 105 of file TargetedMovementGenerator.h.
Referenced by FollowMovementGenerator< T >::unitSpeedChanged().
_range
template<class T > float FollowMovementGenerator< T >::_range private
Definition at line 107 of file TargetedMovementGenerator.h.
Referenced by FollowMovementGenerator< T >::GetFollowRange().
i_path
template<class T > std::unique_ptr<PathGenerator> FollowMovementGenerator< T >::i_path private
Definition at line 101 of file TargetedMovementGenerator.h.
i_recheckPredictedDistance
template<class T > bool FollowMovementGenerator< T >::i_recheckPredictedDistance private
Definition at line 103 of file TargetedMovementGenerator.h.
i_recheckPredictedDistanceTimer
template<class T > TimeTrackerSmall FollowMovementGenerator< T >::i_recheckPredictedDistanceTimer private
Definition at line 102 of file TargetedMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp