Azerotcore-wotlk: WhoListCacheMgr Class Reference
WhoListCacheMgr Class Reference
#include <WhoListCacheMgr.h>
Public Member Functions
void Update ()
WhoListInfoVector const & GetWhoList () const
Static Public Member Functions
static WhoListCacheMgr * instance ()
Protected Attributes
WhoListInfoVector _whoListStorage
Private Member Functions
WhoListCacheMgr ()=default
~WhoListCacheMgr ()=default
WhoListCacheMgr (WhoListCacheMgr const &)=delete
WhoListCacheMgr (WhoListCacheMgr &&)=delete
WhoListCacheMgr & operator= (WhoListCacheMgr const &)=delete
WhoListCacheMgr & operator= (WhoListCacheMgr &&)=delete
Detailed Description
Definition at line 76 of file WhoListCacheMgr.h.
Constructor & Destructor Documentation
WhoListCacheMgr() [1/3]
WhoListCacheMgr::WhoListCacheMgr () private default
~WhoListCacheMgr()
WhoListCacheMgr::~WhoListCacheMgr () private default
WhoListCacheMgr() [2/3]
WhoListCacheMgr::WhoListCacheMgr (WhoListCacheMgr const &) private delete
WhoListCacheMgr() [3/3]
WhoListCacheMgr::WhoListCacheMgr (WhoListCacheMgr &&) private delete
Member Function Documentation
GetWhoList()
WhoListInfoVector const& WhoListCacheMgr::GetWhoList () const inline
Definition at line 90 of file WhoListCacheMgr.h.
 { return _whoListStorage; }
instance()
WhoListCacheMgr * WhoListCacheMgr::instance () static
Definition at line 25 of file WhoListCacheMgr.cpp.
 {
     static WhoListCacheMgr instance;
     return &instance;
 }
operator=() [1/2]
WhoListCacheMgr& WhoListCacheMgr::operator= (WhoListCacheMgr &&) private delete
operator=() [2/2]
WhoListCacheMgr& WhoListCacheMgr::operator= (WhoListCacheMgr const &) private delete
Update()
void WhoListCacheMgr::Update ()
Definition at line 31 of file WhoListCacheMgr.cpp.
 {
     // clear current list
     _whoListStorage.clear();
     _whoListStorage.reserve(sWorld->GetPlayerCount() + 1);
     for (auto const& [guid, player] : ObjectAccessor::GetPlayers())
     {
         if (!player->FindMap() || player->GetSession()->PlayerLoading())
             continue;
         std::string playerName = player->GetName();
         std::wstring widePlayerName;
         if (!Utf8toWStr(playerName, widePlayerName))
             continue;
         wstrToLower(widePlayerName);
         std::string guildName = sGuildMgr->GetGuildNameById(player->GetGuildId());
         std::wstring wideGuildName;
         if (!Utf8toWStr(guildName, wideGuildName))
             continue;
         wstrToLower(wideGuildName);
         _whoListStorage.emplace_back(player->GetGUID(), player->GetTeamId(), player->GetSession()->GetSecurity(), player->getLevel(),
             player->getClass(), player->getRace(),
             (player->IsSpectator() ? 4395 /*Dalaran*/ : player->GetZoneId()), player->getGender(), player->IsVisible(),
             widePlayerName, wideGuildName, playerName, guildName);
     }
 }
References _whoListStorage, ObjectAccessor::GetPlayers(), sGuildMgr, sWorld, Utf8toWStr(), and wstrToLower().
Member Data Documentation
_whoListStorage
WhoListInfoVector WhoListCacheMgr::_whoListStorage protected
Definition at line 93 of file WhoListCacheMgr.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/server/game/Cache/WhoListCacheMgr.h
src/server/game/Cache/WhoListCacheMgr.cpp