Azerotcore-wotlk: ActionButton Struct Reference
ActionButton Struct Reference
#include <Player.h>
Public Member Functions
ActionButton ()
ActionButtonType GetType () const
uint32 GetAction () const
void SetActionAndType (uint32 action, ActionButtonType type)
Public Attributes
uint32 packedData {0}
ActionButtonUpdateState uState {ACTIONBUTTON_NEW}
Detailed Description
Definition at line 247 of file Player.h.
Constructor & Destructor Documentation
ActionButton()
ActionButton::ActionButton () inline
Definition at line 249 of file Player.h.
 {}
Member Function Documentation
GetAction()
uint32 ActionButton::GetAction () const inline
Definition at line 256 of file Player.h.
 { return ACTION_BUTTON_ACTION(packedData); }
References ACTION_BUTTON_ACTION, and packedData.
Referenced by Spell::EffectCastButtons().
GetType()
ActionButtonType ActionButton::GetType () const inline
Definition at line 255 of file Player.h.
 { return ActionButtonType(ACTION_BUTTON_TYPE(packedData)); }
References ACTION_BUTTON_TYPE, and packedData.
Referenced by Spell::EffectCastButtons().
SetActionAndType()
void ActionButton::SetActionAndType (uint32 action, ActionButtonType type) inline
Definition at line 257 of file Player.h.
     {
         uint32 newData = action | (uint32(type) << 24);
         if (newData != packedData || uState == ACTIONBUTTON_DELETED)
         {
             packedData = newData;
             if (uState != ACTIONBUTTON_NEW)
                 uState = ACTIONBUTTON_CHANGED;
         }
     }
References ACTIONBUTTON_CHANGED, ACTIONBUTTON_DELETED, ACTIONBUTTON_NEW, packedData, and uState.
Referenced by Player::addActionButton().
Member Data Documentation
packedData
uint32 ActionButton::packedData {0}
Definition at line 251 of file Player.h.
Referenced by GetAction(), GetType(), and SetActionAndType().
uState
ActionButtonUpdateState ActionButton::uState {ACTIONBUTTON_NEW}
Definition at line 252 of file Player.h.
Referenced by SetActionAndType().
The documentation for this struct was generated from the following file:
src/server/game/Entities/Player/Player.h