Azerotcore-wotlk: G3D::AtomicInt32 Class Reference
G3D::AtomicInt32 Class Reference
#include <AtomicInt32.h>
Public Member Functions
AtomicInt32 ()
AtomicInt32 (const int32 x)
AtomicInt32 (const AtomicInt32 &x)
const AtomicInt32 & operator= (const int32 x)
void operator= (const AtomicInt32 &x)
int32 value () const
int32 add (const int32 x)
int32 sub (const int32 x)
void increment ()
int32 decrement ()
int32 compareAndSet (const int32 comperand, const int32 exchange)
Private Attributes
volatile int32 m_value
Detailed Description
An integer that may safely be used on different threads without external locking.
On Win32, Linux, FreeBSD, and Mac OS X this is implemented without locks.
BETA API This is unsupported and may change
Definition at line 29 of file AtomicInt32.h.
Constructor & Destructor Documentation
AtomicInt32() [1/3]
G3D::AtomicInt32::AtomicInt32 () inline
Initial value is undefined.
Definition at line 43 of file AtomicInt32.h.
 {}
AtomicInt32() [2/3]
G3D::AtomicInt32::AtomicInt32 (const int32 x) inline explicit
Atomic set
Definition at line 46 of file AtomicInt32.h.
{
         m_value = x;
     }
References m_value, and G3D::x.
AtomicInt32() [3/3]
G3D::AtomicInt32::AtomicInt32 (const AtomicInt32 & x) inline
Atomic set
Definition at line 51 of file AtomicInt32.h.
{
         m_value = x.m_value;
     }
References m_value, and G3D::x.
Member Function Documentation
add()
int32 G3D::AtomicInt32::add (const int32 x) inline
Returns the old value, before the add.
Definition at line 72 of file AtomicInt32.h.
{
 #       if defined(G3D_WINDOWS)
             return InterlockedExchangeAdd(&m_value, x);
 #       elif defined(G3D_LINUX) || defined(G3D_FREEBSD)
 #           if defined(__aarch64__)
                 return __sync_fetch_and_add(&m_value, x);
 #           else
                 int32 old;
                 asm volatile ("lock; xaddl %0,%1"
                     : "=r"(old), "=m"(m_value) /* outputs */
                     : "0"(x), "m"(m_value)   /* inputs */
                     : "memory", "cc");
                 return old;
 #           endif
 #       elif defined(G3D_OSX)
             int32 old = m_value;
             OSAtomicAdd32(x, &m_value);
             return old;
 #       endif
     }
References m_value, and G3D::x.
Referenced by increment(), and sub().
compareAndSet()
int32 G3D::AtomicInt32::compareAndSet (const int32 comperand, const int32 exchange) inline
Atomic test-and-set: if *this == comperand then *this := exchange else do nothing. In both cases, returns the old value of *this.
Performs an atomic comparison of this with the Comperand value. If this is equal to the Comperand value, the Exchange value is stored in this. Otherwise, no operation is performed.
Under VC6 the sign bit may be lost.
Definition at line 150 of file AtomicInt32.h.
{
 #       if defined(G3D_WINDOWS)
             return InterlockedCompareExchange(&m_value, exchange, comperand);
 #       elif defined(G3D_LINUX) || defined(G3D_FREEBSD) || defined(G3D_OSX)
 #           if defined(__aarch64__)
                 return __sync_val_compare_and_swap(&m_value, comperand, exchange);
 #           else
                 // Based on Apache Portable Runtime
                 // http://koders.com/c/fid3B6631EE94542CDBAA03E822CA780CBA1B024822.aspx
                 int32 ret;
                 asm volatile ("lock; cmpxchgl %1, %2"
                             : "=a" (ret)
                             : "r" (exchange), "m" (m_value), "0"(comperand)
                             : "memory", "cc");
                 return ret;
                 // Note that OSAtomicCompareAndSwap32 does not return a useful value for us
                 // so it can't satisfy the cmpxchgl contract.
 #           endif
 #       endif
     }
References m_value, and ret.
Referenced by G3D::Spinlock::lock(), and G3D::Spinlock::unlock().
decrement()
int32 G3D::AtomicInt32::decrement () inline
Returns zero if the result is zero after decrement, non-zero otherwise.
Definition at line 117 of file AtomicInt32.h.
                       {
 #       if defined(G3D_WINDOWS)
             // Note: returns the newly decremented value
             return InterlockedDecrement(&m_value);
 #       elif defined(G3D_LINUX)  || defined(G3D_FREEBSD)
 #           if defined(__aarch64__)
                 return __sync_sub_and_fetch(&m_value, 1);
 #           else
                 unsigned char nz;
                 asm volatile ("lock; decl %1;\n\t"
                             "setnz %%al"
                             : "=a" (nz)
                             : "m" (m_value)
                             : "memory", "cc");
                 return nz;
 #           endif
 #       elif defined(G3D_OSX)
             // Note: returns the newly decremented value
             return OSAtomicDecrement32(&m_value);
 #       endif
     }
References m_value.
Referenced by G3D::Any::dropReference().
increment()
void G3D::AtomicInt32::increment () inline
Definition at line 104 of file AtomicInt32.h.
                      {
 #       if defined(G3D_WINDOWS)
             // Note: returns the newly incremented value
             InterlockedIncrement(&m_value);
 #       elif defined(G3D_LINUX) || defined(G3D_FREEBSD)
             add(1);
 #       elif defined(G3D_OSX)
             // Note: returns the newly incremented value
             OSAtomicIncrement32(&m_value);
 #       endif
     }
References add(), and m_value.
operator=() [1/2]
void G3D::AtomicInt32::operator= (const AtomicInt32 & x) inline
Atomic set
Definition at line 62 of file AtomicInt32.h.
{
         m_value = x.m_value;
     }
References m_value, and G3D::x.
operator=() [2/2]
const AtomicInt32& G3D::AtomicInt32::operator= (const int32 x) inline
Atomic set
Definition at line 56 of file AtomicInt32.h.
{
         m_value = x;
         return *this;
     }
References m_value, and G3D::x.
sub()
int32 G3D::AtomicInt32::sub (const int32 x) inline
Returns old value.
Definition at line 100 of file AtomicInt32.h.
{
         return add(-x);
     }
References add(), and G3D::x.
value()
int32 G3D::AtomicInt32::value () const inline
Returns the current value
Definition at line 67 of file AtomicInt32.h.
{
         return m_value;
     }
References m_value.
Referenced by G3D::Map2D< Storage, Compute >::changed(), and G3D::Any::ensureMutable().
Member Data Documentation
m_value
volatile int32 G3D::AtomicInt32::m_value private
Definition at line 36 of file AtomicInt32.h.
Referenced by add(), AtomicInt32(), compareAndSet(), decrement(), increment(), operator=(), and value().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/AtomicInt32.h