Azerotcore-wotlk: ItemPosCount Struct Reference
ItemPosCount Struct Reference
#include <Player.h>
Public Member Functions
ItemPosCount (uint16 _pos, uint32 _count)
bool isContainedIn (std::vector< ItemPosCount > const &vec) const
Public Attributes
uint16 pos
uint32 count
Detailed Description
Definition at line 745 of file Player.h.
Constructor & Destructor Documentation
ItemPosCount()
ItemPosCount::ItemPosCount (uint16 _pos, uint32 _count) inline
Definition at line 747 of file Player.h.
 : pos(_pos), count(_count) {}
Member Function Documentation
isContainedIn()
bool ItemPosCount::isContainedIn (std::vector< ItemPosCount > const & vec) const
Definition at line 12338 of file Player.cpp.
 {
     for (ItemPosCountVec::const_iterator itr = vec.begin(); itr != vec.end(); ++itr)
         if (itr->pos == pos)
             return true;
     return false;
 }
References pos.
Referenced by Player::CanStoreItem_InBag(), Player::CanStoreItem_InInventorySlots(), and Player::CanStoreItem_InSpecificSlot().
Member Data Documentation
count
uint32 ItemPosCount::count
Definition at line 750 of file Player.h.
pos
uint16 ItemPosCount::pos
Definition at line 749 of file Player.h.
Referenced by isContainedIn().
The documentation for this struct was generated from the following files:
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/Player.cpp