Azerotcore-wotlk: FrozenThroneResetWorker Class Reference
FrozenThroneResetWorker Class Reference
Public Member Functions
FrozenThroneResetWorker ()
bool operator() (GameObject *go)
Detailed Description
Definition at line 458 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
FrozenThroneResetWorker()
FrozenThroneResetWorker::FrozenThroneResetWorker () inline
Definition at line 461 of file boss_the_lich_king.cpp.
 { }
Member Function Documentation
operator()()
bool FrozenThroneResetWorker::operator() (GameObject * go) inline
Definition at line 463 of file boss_the_lich_king.cpp.
     {
         switch (go->GetEntry())
         {
             case GO_ARTHAS_PLATFORM:
                 go->SetDestructibleState(GO_DESTRUCTIBLE_INTACT, nullptr, true);
                 break;
             case GO_DOODAD_ICECROWN_THRONEFROSTYWIND01:
                 go->SetGoState(GO_STATE_ACTIVE);
                 break;
             case GO_DOODAD_ICECROWN_THRONEFROSTYEDGE01:
                 go->SetGoState(GO_STATE_READY);
                 break;
             case GO_DOODAD_ICECROWN_SNOWEDGEWARNING01:
                 go->SetGoState(GO_STATE_READY);
                 break;
             case GO_DOODAD_ICESHARD_STANDING02:
             case GO_DOODAD_ICESHARD_STANDING01:
             case GO_DOODAD_ICESHARD_STANDING03:
             case GO_DOODAD_ICESHARD_STANDING04:
                 go->ResetDoorOrButton();
                 break;
             default:
                 break;
         }
         return false;
     }
References Object::GetEntry(), GO_ARTHAS_PLATFORM, GO_DESTRUCTIBLE_INTACT, GO_DOODAD_ICECROWN_SNOWEDGEWARNING01, GO_DOODAD_ICECROWN_THRONEFROSTYEDGE01, GO_DOODAD_ICECROWN_THRONEFROSTYWIND01, GO_DOODAD_ICESHARD_STANDING01, GO_DOODAD_ICESHARD_STANDING02, GO_DOODAD_ICESHARD_STANDING03, GO_DOODAD_ICESHARD_STANDING04, GO_STATE_ACTIVE, GO_STATE_READY, GameObject::ResetDoorOrButton(), GameObject::SetDestructibleState(), and GameObject::SetGoState().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp