Azerotcore-wotlk: Acore::BroadcastTextBuilder Class Reference
Acore::BroadcastTextBuilder Class Reference
#include <ChatTextBuilder.h>
Public Member Functions
BroadcastTextBuilder (WorldObject const *obj, ChatMsg msgType, uint32 textId, uint8 gender, WorldObject const *target=nullptr, uint32 achievementId=0)
void operator() (WorldPacket &data, LocaleConstant locale) const
size_t operator() (WorldPacket *data, LocaleConstant locale) const
Private Attributes
WorldObject const * _source
ChatMsg _msgType
uint32 _textId
uint8 _gender
WorldObject const * _target
uint32 _achievementId
Detailed Description
Definition at line 30 of file ChatTextBuilder.h.
Constructor & Destructor Documentation
BroadcastTextBuilder()
Acore::BroadcastTextBuilder::BroadcastTextBuilder (WorldObject const * obj, ChatMsg msgType, uint32 textId, uint8 gender, WorldObject const * target = nullptr, uint32 achievementId = 0) inline
Definition at line 33 of file ChatTextBuilder.h.
                 : _source(obj), _msgType(msgType), _textId(textId), _gender(gender), _target(target), _achievementId(achievementId) { }
Member Function Documentation
operator()() [1/2]
void Acore::BroadcastTextBuilder::operator() (WorldPacket & data, LocaleConstant locale) const
Definition at line 23 of file ChatTextBuilder.cpp.
 {
     BroadcastText const* bct = sObjectMgr->GetBroadcastText(_textId);
     ChatHandler::BuildChatPacket(data, _msgType, bct ? Language(bct->LanguageID) : LANG_UNIVERSAL, _source, _target, bct ? bct->GetText(locale, _gender) : "", _achievementId, "", locale);
 }
References _achievementId, _gender, _msgType, _source, _target, _textId, ChatHandler::BuildChatPacket(), BroadcastText::GetText(), LANG_UNIVERSAL, BroadcastText::LanguageID, and sObjectMgr.
operator()() [2/2]
size_t Acore::BroadcastTextBuilder::operator() (WorldPacket * data, LocaleConstant locale) const
Definition at line 29 of file ChatTextBuilder.cpp.
 {
     BroadcastText const* bct = sObjectMgr->GetBroadcastText(_textId);
     return ChatHandler::BuildChatPacket(*data, _msgType, bct ? Language(bct->LanguageID) : LANG_UNIVERSAL, _source, _target, bct ? bct->GetText(locale, _gender) : "", _achievementId, "", locale);
 }
References ChatHandler::BuildChatPacket(), BroadcastText::GetText(), LANG_UNIVERSAL, BroadcastText::LanguageID, and sObjectMgr.
Member Data Documentation
_achievementId
uint32 Acore::BroadcastTextBuilder::_achievementId private
Definition at line 45 of file ChatTextBuilder.h.
Referenced by operator()().
_gender
uint8 Acore::BroadcastTextBuilder::_gender private
Definition at line 43 of file ChatTextBuilder.h.
Referenced by operator()().
_msgType
ChatMsg Acore::BroadcastTextBuilder::_msgType private
Definition at line 41 of file ChatTextBuilder.h.
Referenced by operator()().
_source
WorldObject const* Acore::BroadcastTextBuilder::_source private
Definition at line 40 of file ChatTextBuilder.h.
Referenced by operator()().
_target
WorldObject const* Acore::BroadcastTextBuilder::_target private
Definition at line 44 of file ChatTextBuilder.h.
Referenced by operator()().
_textId
uint32 Acore::BroadcastTextBuilder::_textId private
Definition at line 42 of file ChatTextBuilder.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
src/server/game/Texts/ChatTextBuilder.h
src/server/game/Texts/ChatTextBuilder.cpp