Azerotcore-wotlk: npc_wg_spirit_guide Class Reference
npc_wg_spirit_guide Class Reference
Classes
struct npc_wg_spirit_guideAI
Public Member Functions
npc_wg_spirit_guide ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 198 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
npc_wg_spirit_guide()
npc_wg_spirit_guide::npc_wg_spirit_guide () inline
Definition at line 201 of file zone_wintergrasp.cpp.
 : CreatureScript("npc_wg_spirit_guide") { }
Member Function Documentation
GetAI()
CreatureAI* npc_wg_spirit_guide::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 251 of file zone_wintergrasp.cpp.
     {
         return new npc_wg_spirit_guideAI(creature);
     }
OnGossipHello()
bool npc_wg_spirit_guide::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 203 of file zone_wintergrasp.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (!wintergrasp)
             return true;
         GraveyardVect graveyard = wintergrasp->GetGraveyardVector();
         for (uint8 i = 0; i < graveyard.size(); i++)
             if (graveyard[i]->GetControlTeamId() == player->GetTeamId())
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, sObjectMgr->GetAcoreStringForDBCLocale(((BfGraveyardWG*)graveyard[i])->GetTextId()), GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + i);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), BATTLEFIELD_BATTLEID_WG, Player::GetGossipTextId(), Battlefield::GetGraveyardVector(), Object::GetGUID(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), sBattlefieldMgr, SendGossipMenuFor(), and sObjectMgr.
OnGossipSelect()
bool npc_wg_spirit_guide::OnGossipSelect (Player * player, Creature * , uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 221 of file zone_wintergrasp.cpp.
     {
         CloseGossipMenuFor(player);
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (wintergrasp)
         {
             GraveyardVect gy = wintergrasp->GetGraveyardVector();
             for (uint8 i = 0; i < gy.size(); i++)
                 if (action - GOSSIP_ACTION_INFO_DEF == i && gy[i]->GetControlTeamId() == player->GetTeamId())
                     if (GraveyardStruct const* safeLoc = sGraveyard->GetGraveyard(gy[i]->GetGraveyardId()))
                         player->TeleportTo(safeLoc->Map, safeLoc->x, safeLoc->y, safeLoc->z, 0);
         }
         return true;
     }
References BATTLEFIELD_BATTLEID_WG, CloseGossipMenuFor(), Battlefield::GetGraveyardVector(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, sBattlefieldMgr, sGraveyard, and Player::TeleportTo().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp