Azerotcore-wotlk: deps/mysqllite/mysys/mf_qsort.c File Reference
mf_qsort.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Classes
struct st_stack
Macros
#define CMP(A, B) ((*cmp)((A),(B)))
#define SWAP(A, B, size, swap_ptrs)
#define MEDIAN(low, mid, high)
#define PUSH(LOW, HIGH) {stack_ptr->low = LOW; stack_ptr++->high = HIGH;}
#define POP(LOW, HIGH) {LOW = (--stack_ptr)->low; HIGH = stack_ptr->high;}
#define STACK_SIZE (8 * sizeof(unsigned long int))
#define THRESHOLD_FOR_INSERT_SORT 10
#define SORT_RETURN return 0
Typedefs
typedef struct st_stack stack_node
Functions
qsort_t my_qsort (void *base_ptr, size_t count, size_t size, qsort_cmp cmp)
Macro Definition Documentation
CMP
#define CMP (A, B) ((*cmp)((A),(B)))
Definition at line 32 of file mf_qsort.c.
MEDIAN
#define MEDIAN (low, mid, high)
Value:
{                           \
    if (CMP(high,low) < 0)              \
      SWAP(high, low, size, ptr_cmp);           \
    if (CMP(mid, low) < 0)              \
      SWAP(mid, low, size, ptr_cmp);            \
    else if (CMP(high, mid) < 0)            \
      SWAP(mid, high, size, ptr_cmp);           \
}
Definition at line 54 of file mf_qsort.c.
POP
#define POP (LOW, HIGH) {LOW = (--stack_ptr)->low; HIGH = stack_ptr->high;}
Definition at line 72 of file mf_qsort.c.
PUSH
#define PUSH (LOW, HIGH) {stack_ptr->low = LOW; stack_ptr++->high = HIGH;}
Definition at line 71 of file mf_qsort.c.
SORT_RETURN
#define SORT_RETURN return 0
Definition at line 80 of file mf_qsort.c.
STACK_SIZE
#define STACK_SIZE (8 * sizeof(unsigned long int))
Definition at line 75 of file mf_qsort.c.
SWAP
#define SWAP (A, B, size, swap_ptrs)
Value:
do {                            \
   if (swap_ptrs)                   \
   {                            \
     reg1 char **a = (char**) (A), **b = (char**) (B);  \
     char *tmp = *a; *a++ = *b; *b++ = tmp;     \
   }                            \
   else                         \
   {                            \
     reg1 char *a = (A), *b = (B);          \
     reg3 char *end= a+size;                \
     do                         \
     {                          \
       char tmp = *a; *a++ = *b; *b++ = tmp;        \
     } while (a < end);                 \
   }                            \
} while (0)
Definition at line 35 of file mf_qsort.c.
THRESHOLD_FOR_INSERT_SORT
#define THRESHOLD_FOR_INSERT_SORT 10
Definition at line 76 of file mf_qsort.c.
Typedef Documentation
stack_node
typedef struct st_stack stack_node
Function Documentation
my_qsort()
qsort_t my_qsort (void * base_ptr, size_t count, size_t size, qsort_cmp cmp)
Definition at line 97 of file mf_qsort.c.
 {
   char *low, *high, *pivot;
   stack_node stack[STACK_SIZE], *stack_ptr;
   my_bool ptr_cmp;
   /* Handle the simple case first */
   /* This will also make the rest of the code simpler */
   if (count <= 1)
     SORT_RETURN;
   low  = (char*) base_ptr;
   high = low+ size * (count - 1);
   stack_ptr = stack + 1;
 #ifdef HAVE_purify
   /* The first element in the stack will be accessed for the last POP */
   stack[0].low=stack[0].high=0;
 #endif
   pivot = (char *) my_alloca((int) size);
   ptr_cmp= size == sizeof(char*) && !((low - (char*) 0)& (sizeof(char*)-1));
   /* The following loop sorts elements between high and low */
   do
   {
     char *low_ptr, *high_ptr, *mid;
     count=((size_t) (high - low) / size)+1;
     /* If count is small, then an insert sort is faster than qsort */
     if (count < THRESHOLD_FOR_INSERT_SORT)
     {
       for (low_ptr = low + size; low_ptr <= high; low_ptr += size)
       {
     char *ptr;
     for (ptr = low_ptr; ptr > low && CMP(ptr - size, ptr) > 0;
          ptr -= size)
       SWAP(ptr, ptr - size, size, ptr_cmp);
       }
       POP(low, high);
       continue;
     }
     /* Try to find a good middle element */
     mid= low + size * (count >> 1);
     if (count > 40)             /* Must be bigger than 24 */
     {
       size_t step = size* (count / 8);
       MEDIAN(low, low + step, low+step*2);
       MEDIAN(mid - step, mid, mid+step);
       MEDIAN(high - 2 * step, high-step, high);
       /* Put best median in 'mid' */
       MEDIAN(low+step, mid, high-step);
       low_ptr  = low;
       high_ptr = high;
     }
     else
     {
       MEDIAN(low, mid, high);
       /* The low and high argument are already in sorted against 'pivot' */
       low_ptr  = low + size;
       high_ptr = high - size;
     }
     memcpy(pivot, mid, size);
     do
     {
       while (CMP(low_ptr, pivot) < 0)
     low_ptr += size;
       while (CMP(pivot, high_ptr) < 0)
     high_ptr -= size;
       if (low_ptr < high_ptr)
       {
     SWAP(low_ptr, high_ptr, size, ptr_cmp);
     low_ptr += size;
     high_ptr -= size;
       }
       else
       {
     if (low_ptr == high_ptr)
     {
       low_ptr += size;
       high_ptr -= size;
     }
     break;
       }
     }
     while (low_ptr <= high_ptr);
     /*
       Prepare for next iteration.
        Skip partitions of size 1 as these doesn't have to be sorted
        Push the larger partition and sort the smaller one first.
        This ensures that the stack is keept small.
     */
     if ((int) (high_ptr - low) <= 0)
     {
       if ((int) (high - low_ptr) <= 0)
       {
     POP(low, high);         /* Nothing more to sort */
       }
       else
     low = low_ptr;          /* Ignore small left part. */
     }
     else if ((int) (high - low_ptr) <= 0)
       high = high_ptr;          /* Ignore small right part. */
     else if ((high_ptr - low) > (high - low_ptr))
     {
       PUSH(low, high_ptr);      /* Push larger left part */
       low = low_ptr;
     }
     else
     {
       PUSH(low_ptr, high);      /* Push larger right part */
       high = high_ptr;
     }
   } while (stack_ptr > stack);
   my_afree(pivot);
   SORT_RETURN;
 }
References CMP, count(), st_stack::high, st_stack::low, MEDIAN, memcpy, my_afree, my_alloca, POP, ptr(), ptr_cmp(), PUSH, SORT_RETURN, STACK_SIZE, SWAP, and THRESHOLD_FOR_INSERT_SORT.
Referenced by flush_cached_blocks(), and my_dir().