Azerotcore-wotlk: npc_anachronos_the_ancient::npc_anachronos_the_ancientAI Struct Reference
npc_anachronos_the_ancient::npc_anachronos_the_ancientAI Struct Reference
Public Member Functions
npc_anachronos_the_ancientAI (Creature *creature)
void Reset () override
void HandleAnimation ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 AnimationTimer
uint8 AnimationCount
ObjectGuid AnachronosQuestTriggerGUID
ObjectGuid MerithraGUID
ObjectGuid ArygosGUID
ObjectGuid CaelestraszGUID
ObjectGuid FandralGUID
ObjectGuid PlayerGUID
bool eventEnd
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 307 of file zone_silithus.cpp.
Constructor & Destructor Documentation
npc_anachronos_the_ancientAI()
npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::npc_anachronos_the_ancientAI (Creature * creature) inline
Definition at line 309 of file zone_silithus.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
HandleAnimation()
void npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation () inline
Definition at line 337 of file zone_silithus.cpp.
         {
             Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
             if (!player)
             {
                 return;
             }
             Creature* Fandral = player->FindNearestCreature(C_FANDRAL_STAGHELM, 100.0f);
             Creature* Arygos = player->FindNearestCreature(C_ARYGOS, 100.0f);
             Creature* Caelestrasz = player->FindNearestCreature(C_CAELESTRASZ, 100.0f);
             Creature* Merithra = player->FindNearestCreature(C_MERITHRA, 100.0f);
             if (!Fandral || !Arygos || !Caelestrasz || !Merithra)
                 return;
             AnimationTimer = EventAnim[AnimationCount].Timer;
             if (!eventEnd)
             {
                 switch (AnimationCount)
                 {
                     case 0:
                         Talk(ANACHRONOS_SAY_1, Fandral);
                         break;
                     case 1:
                         Fandral->SetTarget(me->GetGUID());
                         Fandral->AI()->Talk(FANDRAL_SAY_1, me);
                         break;
                     case 2:
                         Fandral->SetTarget();
                         Merithra->AI()->Talk(MERITHRA_EMOTE_1);
                         break;
                     case 3:
                         Merithra->AI()->Talk(MERITHRA_SAY_1);
                         break;
                     case 4:
                         Arygos->AI()->Talk(ARYGOS_EMOTE_1);
                         break;
                     case 5:
                         Caelestrasz->SetTarget(Fandral->GetGUID());
                         Caelestrasz->AI()->Talk(CAELESTRASZ_SAY_1);
                         break;
                     case 6:
                         Merithra->AI()->Talk(MERITHRA_SAY_2);
                         break;
                     case 7:
                         Caelestrasz->SetTarget();
                         Merithra->GetMotionMaster()->MoveCharge(-8065, 1530, 2.61f, 10);
                         break;
                     case 8:
                         Merithra->AI()->Talk(MERITHRA_YELL_1);
                         break;
                     case 9:
                         Merithra->CastSpell(Merithra, 25105, true);
                         break;
                     case 10:
                         Merithra->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                         Merithra->SetDisableGravity(true);
                         Merithra->GetMotionMaster()->MoveCharge(-8065, 1530, 6.61f, 3);
                         break;
                     case 11:
                         Merithra->CastSpell(Merithra, 24818, false);
                         break;
                     case 12:
                         Merithra->GetMotionMaster()->MoveCharge(-8100, 1530, 50, 42);
                         break;
                     case 13:
                         break;
                     case 14:
                         Arygos->AI()->Talk(ARYGOS_SAY_1);
                         Merithra->SetVisible(false);
                         break;
                     case 15:
                         Arygos->GetMotionMaster()->MoveCharge(-8065, 1530, 2.61f, 10);
                         Merithra->GetMotionMaster()->MoveCharge(-8034.535f, 1535.14f, 2.61f, 42);
                         break;
                     case 16:
                         Arygos->AI()->Talk(ARYGOS_YELL_1);
                         break;
                     case 17:
                         Arygos->CastSpell(Arygos, 25107, true);
                         break;
                     case 18:
                         Arygos->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                         Arygos->SetDisableGravity(true);
                         Arygos->GetMotionMaster()->MoveCharge(-8065, 1530, 6.61f, 42);
                         break;
                     case 19:
                         Arygos->CastSpell(Arygos, 50505, false);
                         break;
                     case 20:
                         Arygos->GetMotionMaster()->MoveCharge(-8095, 1530, 50, 42);
                         break;
                     case 21:
                         break;
                     case 22:
                         Caelestrasz->AI()->Talk(CAELESTRASZ_SAY_2, Fandral);
                         break;
                     case 23:
                         Caelestrasz->GetMotionMaster()->MoveCharge(-8065, 1530, 2.61f, 10);
                         Arygos->SetVisible(false);
                         Arygos->GetMotionMaster()->MoveCharge(-8034.535f, 1535.14f, 2.61f, 10);
                         break;
                     case 24:
                         Caelestrasz->AI()->Talk(CAELESTRASZ_YELL_1);
                         break;
                     case 25:
                         Caelestrasz->CastSpell(Caelestrasz, 25106, true);
                         break;
                     case 26:
                         Caelestrasz->HandleEmoteCommand(254);
                         Caelestrasz->SetDisableGravity(true);
                         Caelestrasz->GetMotionMaster()->MoveCharge(-8065, 1530, 7.61f, 4);
                         break;
                     case 27:
                         Caelestrasz->CastSpell(Caelestrasz, 54293, false);
                         break;
                     case 28:
                         Talk(ANACHRONOS_SAY_2, Fandral);
                         break;
                     case 29:
                         Caelestrasz->GetMotionMaster()->MoveCharge(-8095, 1530, 50, 42);
                         Fandral->AI()->Talk(FANDRAL_SAY_2);
                         break;
                     case 30:
                         break;
                     case 31:
                         Talk(ANACHRONOS_SAY_3, Fandral);
                         break;
                     case 32:
                         Caelestrasz->SetVisible(false);
                         Caelestrasz->GetMotionMaster()->MoveCharge(-8034.535f, 1535.14f, 2.61f, 42);
                         Fandral->GetMotionMaster()->MoveCharge(-8108, 1529, 2.77f, 8);
                         me->GetMotionMaster()->MoveCharge(-8113, 1525, 2.77f, 8);
                         break;//both run to the gate
                     case 33:
                         Talk(ANACHRONOS_SAY_4);
                         Caelestrasz->GetMotionMaster()->MoveCharge(-8050, 1473, 65, 15);
                         break; //Text: sands will stop
                     case 34:
                         DoCast(player, 23017, true);//Arcane Channeling
                         break;
                     case 35:
                         me->CastSpell(-8088, 1520.43f, 2.67f, 25158, true);
                         break;
                     case 36:
                         DoCast(player, 25159, true);
                         break;
                     case 37:
                         me->SummonGameObject(GO_GATE_OF_AHN_QIRAJ, -8130, 1525, 17.5f, 0, 0, 0, 0, 0, 0);
                         break;
                     case 38:
                         DoCast(player, 25166, true);
                         me->SummonGameObject(GO_GLYPH_OF_AHN_QIRAJ, -8130, 1525, 17.5f, 0, 0, 0, 0, 0, 0);
                         break;
                     case 39:
                         Talk(ANACHRONOS_SAY_5, Fandral);
                         break;
                     case 40:
                         Fandral->CastSpell(me, 25167, true);
                         break;
                     case 41:
                         Fandral->SummonGameObject(GO_ROOTS_OF_AHN_QIRAJ, -8130, 1525, 17.5f, 0, 0, 0, 0, 0, 0);
                         Fandral->AI()->Talk(FANDRAL_SAY_3);
                         break;
                     case 42:
                         me->CastStop();
                         Fandral->AI()->Talk(FANDRAL_EMOTE_1);
                         break;
                     case 43:
                         Fandral->CastStop();
                         break;
                     case 44:
                         Talk(ANACHRONOS_SAY_6);
                         break;
                     case 45:
                         Talk(ANACHRONOS_SAY_7);
                         break;
                     case 46:
                         Talk(ANACHRONOS_SAY_8);
                         me->GetMotionMaster()->MoveCharge(-8110, 1527, 2.77f, 4);
                         break;
                     case 47:
                         Talk(ANACHRONOS_EMOTE_1);
                         break;
                     case 48:
                         Fandral->AI()->Talk(FANDRAL_SAY_4, me);
                         break;
                     case 49:
                         Fandral->AI()->Talk(FANDRAL_SAY_5, me);
                         break;
                     case 50:
                         Fandral->AI()->Talk(FANDRAL_EMOTE_2);
                         Fandral->CastSpell(-8127, 1525, 17.5f, 33806, true);
                         break;
                     case 51:
{
                             uint32 entries[4] = { 15423, 15424, 15414, 15422 };
                             for (uint8 i = 0; i < 4; ++i)
{
                                 Unit* mob = player->FindNearestCreature(entries[i], 50, me);
                                 while (mob)
{
                                     mob->RemoveFromWorld();
                                     mob = player->FindNearestCreature(15423, 50, me);
                                 }
                             }
                             break;
                         }
                     case 52:
                         Fandral->GetMotionMaster()->MoveCharge(-8028.75f, 1538.795f, 2.61f, 4);
                         Fandral->AI()->Talk(ANACHRONOS_SAY_9, me);
                         break;
                     case 53:
                         Fandral->AI()->Talk(FANDRAL_SAY_6);
                         break;
                     case 54:
                         Talk(ANACHRONOS_EMOTE_2);
                         break;
                     case 55:
                         Fandral->SetVisible(false);
                         break;
                     case 56:
                         Talk(ANACHRONOS_EMOTE_3);
                         me->GetMotionMaster()->MoveCharge(-8116, 1522, 3.65f, 4);
                         break;
                     case 57:
                         me->GetMotionMaster()->MoveCharge(-8116.7f, 1527, 3.7f, 4);
                         break;
                     case 58:
                         me->GetMotionMaster()->MoveCharge(-8112.67f, 1529.9f, 2.86f, 4);
                         break;
                     case 59:
                         me->GetMotionMaster()->MoveCharge(-8117.99f, 1532.24f, 3.94f, 4);
                         break;
                     case 60:
                         Talk(ANACHRONOS_SAY_10, player);
                         me->GetMotionMaster()->MoveCharge(-8113.46f, 1524.16f, 2.89f, 4);
                         break;
                     case 61:
                         me->GetMotionMaster()->MoveCharge(-8057.1f, 1470.32f, 2.61f, 6);
                         if (player->IsInRange(me, 0, 15))
                             player->GroupEventHappens(QUEST_A_PAWN_ON_THE_ETERNAL_BOARD, me);
                         break;
                     case 62:
                         me->SetDisplayId(15500);
                         break;
                     case 63:
                         me->HandleEmoteCommand(254);
                         me->SetDisableGravity(true);
                         break;
                     case 64:
                         me->GetMotionMaster()->MoveCharge(-8000, 1400, 150, 9);
                         break;
                     case 65:
                         me->SetVisible(false);
                         if (Creature* AnachronosQuestTrigger = (ObjectAccessor::GetCreature(*me, AnachronosQuestTriggerGUID)))
{
                             Talk(ARYGOS_YELL_1);
                             AnachronosQuestTrigger->AI()->EnterEvadeMode();
                             eventEnd = true;
                         }
                         break;
                 }
             }
             ++AnimationCount;
         }
References Creature::AI(), ANACHRONOS_EMOTE_1, ANACHRONOS_EMOTE_2, ANACHRONOS_EMOTE_3, ANACHRONOS_SAY_1, ANACHRONOS_SAY_10, ANACHRONOS_SAY_2, ANACHRONOS_SAY_3, ANACHRONOS_SAY_4, ANACHRONOS_SAY_5, ANACHRONOS_SAY_6, ANACHRONOS_SAY_7, ANACHRONOS_SAY_8, ANACHRONOS_SAY_9, AnachronosQuestTriggerGUID, AnimationCount, AnimationTimer, ARYGOS_EMOTE_1, ARYGOS_SAY_1, ARYGOS_YELL_1, C_ARYGOS, C_CAELESTRASZ, C_FANDRAL_STAGHELM, C_MERITHRA, CAELESTRASZ_SAY_1, CAELESTRASZ_SAY_2, CAELESTRASZ_YELL_1, Unit::CastSpell(), Unit::CastStop(), UnitAI::DoCast(), EMOTE_ONESHOT_LIFTOFF, EventAnim, eventEnd, FANDRAL_EMOTE_1, FANDRAL_EMOTE_2, FANDRAL_SAY_1, FANDRAL_SAY_2, FANDRAL_SAY_3, FANDRAL_SAY_4, FANDRAL_SAY_5, FANDRAL_SAY_6, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Object::GetGUID(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), GO_GATE_OF_AHN_QIRAJ, GO_GLYPH_OF_AHN_QIRAJ, GO_ROOTS_OF_AHN_QIRAJ, Player::GroupEventHappens(), Unit::HandleEmoteCommand(), WorldObject::IsInRange(), ScriptedAI::me, MERITHRA_EMOTE_1, MERITHRA_SAY_1, MERITHRA_SAY_2, MERITHRA_YELL_1, MotionMaster::MoveCharge(), PlayerGUID, QUEST_A_PAWN_ON_THE_ETERNAL_BOARD, Unit::RemoveFromWorld(), Creature::SetDisableGravity(), Creature::SetDisplayId(), Creature::SetTarget(), Unit::SetVisible(), WorldObject::SummonGameObject(), CreatureAI::Talk(), and QuestCinematic::Timer.
Referenced by UpdateAI().
Reset()
void npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 322 of file zone_silithus.cpp.
         {
             AnimationTimer = 1500;
             AnimationCount = 0;
             AnachronosQuestTriggerGUID.Clear();
             MerithraGUID.Clear();
             ArygosGUID.Clear();
             CaelestraszGUID.Clear();
             FandralGUID.Clear();
             PlayerGUID.Clear();
             eventEnd = false;
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
         }
References AnachronosQuestTriggerGUID, AnimationCount, AnimationTimer, ArygosGUID, CaelestraszGUID, ObjectGuid::Clear(), eventEnd, FandralGUID, ScriptedAI::me, MerithraGUID, PlayerGUID, Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 605 of file zone_silithus.cpp.
         {
             if (AnimationTimer)
             {
                 if (AnimationTimer <= diff)
                     HandleAnimation();
                 else AnimationTimer -= diff;
             }
             if (AnimationCount < 65)
                 me->CombatStop();
             if (AnimationCount == 65 || eventEnd)
                 EnterEvadeMode();
         }
References AnimationCount, AnimationTimer, Unit::CombatStop(), CreatureAI::EnterEvadeMode(), eventEnd, HandleAnimation(), and ScriptedAI::me.
Member Data Documentation
AnachronosQuestTriggerGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::AnachronosQuestTriggerGUID
Definition at line 314 of file zone_silithus.cpp.
Referenced by HandleAnimation(), and Reset().
AnimationCount
uint8 npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::AnimationCount
Definition at line 312 of file zone_silithus.cpp.
Referenced by HandleAnimation(), Reset(), and UpdateAI().
AnimationTimer
uint32 npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::AnimationTimer
Definition at line 311 of file zone_silithus.cpp.
Referenced by HandleAnimation(), Reset(), and UpdateAI().
ArygosGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::ArygosGUID
Definition at line 316 of file zone_silithus.cpp.
Referenced by Reset().
CaelestraszGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::CaelestraszGUID
Definition at line 317 of file zone_silithus.cpp.
Referenced by Reset().
eventEnd
bool npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::eventEnd
Definition at line 320 of file zone_silithus.cpp.
Referenced by HandleAnimation(), Reset(), and UpdateAI().
FandralGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::FandralGUID
Definition at line 318 of file zone_silithus.cpp.
Referenced by Reset().
MerithraGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::MerithraGUID
Definition at line 315 of file zone_silithus.cpp.
Referenced by Reset().
PlayerGUID
ObjectGuid npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::PlayerGUID
Definition at line 319 of file zone_silithus.cpp.
Referenced by HandleAnimation(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_silithus.cpp