Azerotcore-wotlk: error_handler Struct Reference
error_handler Struct Reference
#include <core.h>
Public Member Functions
constexpr error_handler ()=default
constexpr error_handler (const error_handler &)=default
FMT_NORETURN FMT_API void on_error (const char *message)
Detailed Description
Definition at line 600 of file core.h.
Constructor & Destructor Documentation
error_handler() [1/2]
constexpr error_handler::error_handler () constexpr default
error_handler() [2/2]
constexpr error_handler::error_handler (const error_handler &) constexpr default
Member Function Documentation
on_error()
FMT_FUNC void error_handler::on_error (const char * message)
Definition at line 2552 of file format-inl.h.
{
   FMT_THROW(format_error(message));
 }
References FMT_THROW, and message().
Referenced by basic_format_context< OutputIt, Char >::on_error(), and vformat_to().
The documentation for this struct was generated from the following files:
deps/fmt/include/fmt/core.h
deps/fmt/include/fmt/format-inl.h