Azerotcore-wotlk: npc_ulduar_keeper Class Reference
npc_ulduar_keeper Class Reference
Public Member Functions
npc_ulduar_keeper ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *, Creature *creature, uint32, uint32) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 26 of file ulduar.cpp.
Constructor & Destructor Documentation
npc_ulduar_keeper()
npc_ulduar_keeper::npc_ulduar_keeper () inline
Definition at line 29 of file ulduar.cpp.
 : CreatureScript("npc_ulduar_keeper_gossip") { }
Member Function Documentation
OnGossipHello()
bool npc_ulduar_keeper::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 31 of file ulduar.cpp.
     {
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, "Lend us your aid, keeper. Together we shall defeat Yogg-Saron.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, DEFAULT_GOSSIP_MESSAGE, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), DEFAULT_GOSSIP_MESSAGE, Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_ulduar_keeper::OnGossipSelect (Player * , Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 38 of file ulduar.cpp.
     {
         creature->SetUInt32Value(UNIT_NPC_FLAGS, 0);
         uint8 _keeper = 0;
         switch (creature->GetEntry())
         {
             case NPC_FREYA_GOSSIP:
                 creature->Yell("Eonar, your servant calls for your blessing!", LANG_UNIVERSAL);
                 creature->PlayDirectSound(15535);
                 _keeper = KEEPER_FREYA;
                 break;
             case NPC_HODIR_GOSSIP:
                 creature->Yell("The veil of winter will protect you, champions!", LANG_UNIVERSAL);
                 creature->PlayDirectSound(15559);
                 _keeper = KEEPER_HODIR;
                 break;
             case NPC_MIMIRON_GOSSIP:
                 creature->Yell("Combat matrix enhanced. Behold wonderous rapidity!", LANG_UNIVERSAL);
                 creature->PlayDirectSound(15630);
                 _keeper = KEEPER_MIMIRON;
                 break;
             case NPC_THORIM_GOSSIP:
                 creature->Yell("Golganneth, lend me your strengh! Grant my mortal allies the power of thunder!", LANG_UNIVERSAL);
                 creature->PlayDirectSound(15750);
                 _keeper = KEEPER_THORIM;
                 break;
         }
         if (creature->GetInstanceScript())
         {
             creature->GetInstanceScript()->SetData(TYPE_WATCHERS, _keeper);
             creature->DespawnOrUnsummon(6000);
         }
         return true;
     }
References Creature::DespawnOrUnsummon(), Object::GetEntry(), WorldObject::GetInstanceScript(), KEEPER_FREYA, KEEPER_HODIR, KEEPER_MIMIRON, KEEPER_THORIM, LANG_UNIVERSAL, NPC_FREYA_GOSSIP, NPC_HODIR_GOSSIP, NPC_MIMIRON_GOSSIP, NPC_THORIM_GOSSIP, WorldObject::PlayDirectSound(), ZoneScript::SetData(), Object::SetUInt32Value(), TYPE_WATCHERS, UNIT_NPC_FLAGS, and Unit::Yell().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp