Azerotcore-wotlk: Acore::Impl::ChatCommands::ArgInfo< GameTele const * > Struct Reference
Acore::Impl::ChatCommands::ArgInfo< GameTele const * > Struct Reference
#include <ChatCommandArgs.h>
Static Public Member Functions
static ChatCommandResult TryConsume (GameTele const *&, ChatHandler const *, std::string_view)
Detailed Description
Definition at line 303 of file ChatCommandArgs.h.
Member Function Documentation
TryConsume()
ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< GameTele const * >::TryConsume (GameTele const *& data, ChatHandler const * handler, std::string_view args) static
Definition at line 56 of file ChatCommandArgs.cpp.
 {
     Variant<Hyperlink<tele>, std::string_view> val;
     ChatCommandResult result = ArgInfo<decltype(val)>::TryConsume(val, handler, args);
     if (!result || (data = val.visit(GameTeleVisitor())))
         return result;
     if (val.holds_alternative<Hyperlink<tele>>())
         return FormatAcoreString(handler, LANG_CMDPARSER_GAME_TELE_ID_NO_EXIST, static_cast<uint32>(std::get<Hyperlink<tele>>(val)));
     else
         return FormatAcoreString(handler, LANG_CMDPARSER_GAME_TELE_NO_EXIST, STRING_VIEW_FMT_ARG(std::get<std::string_view>(val)));
 }
References Acore::Impl::ChatCommands::FormatAcoreString(), Acore::ChatCommands::Variant< T1, Ts >::holds_alternative(), LANG_CMDPARSER_GAME_TELE_ID_NO_EXIST, LANG_CMDPARSER_GAME_TELE_NO_EXIST, STRING_VIEW_FMT_ARG, and Acore::ChatCommands::Variant< T1, Ts >::visit().
The documentation for this struct was generated from the following files:
src/server/game/Chat/ChatCommands/ChatCommandArgs.h
src/server/game/Chat/ChatCommands/ChatCommandArgs.cpp