Azerotcore-wotlk: npc_snobold_vassal::npc_snobold_vassalAI Struct Reference
npc_snobold_vassal::npc_snobold_vassalAI Struct Reference
Public Member Functions
npc_snobold_vassalAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void DoAction (int32 param) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
ObjectGuid TargetGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 87 of file boss_northrend_beasts.cpp.
Constructor & Destructor Documentation
npc_snobold_vassalAI()
npc_snobold_vassal::npc_snobold_vassalAI::npc_snobold_vassalAI (Creature * pCreature) inline
Definition at line 89 of file boss_northrend_beasts.cpp.
                                                   : ScriptedAI(pCreature)
         {
             pInstance = pCreature->GetInstanceScript();
             TargetGUID.Clear();
             me->SetReactState(REACT_PASSIVE);
         }
References ObjectGuid::Clear(), WorldObject::GetInstanceScript(), ScriptedAI::me, pInstance, REACT_PASSIVE, Creature::SetReactState(), and TargetGUID.
Member Function Documentation
AttackStart()
void npc_snobold_vassal::npc_snobold_vassalAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 114 of file boss_northrend_beasts.cpp.
         {
             if( who->GetGUID() != TargetGUID )
                 return;
             ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), Object::GetGUID(), and TargetGUID.
DoAction()
void npc_snobold_vassal::npc_snobold_vassalAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 220 of file boss_northrend_beasts.cpp.
         {
             if( param == 1 && !TargetGUID )
                 me->DespawnOrUnsummon();
         }
References Creature::DespawnOrUnsummon(), ScriptedAI::me, and TargetGUID.
EnterCombat()
void npc_snobold_vassal::npc_snobold_vassalAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 106 of file boss_northrend_beasts.cpp.
         {
             events.Reset();
             events.ScheduleEvent(EVENT_SPELL_SNOBOLLED, 1500);
             events.ScheduleEvent(EVENT_SPELL_BATTER, 5000);
             events.ScheduleEvent(EVENT_SPELL_HEAD_CRACK, 25000);
         }
References EVENT_SPELL_BATTER, EVENT_SPELL_HEAD_CRACK, and EVENT_SPELL_SNOBOLLED.
JustDied()
void npc_snobold_vassal::npc_snobold_vassalAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 210 of file boss_northrend_beasts.cpp.
         {
             if( Unit* t = ObjectAccessor::GetUnit(*me, TargetGUID))
             {
                 t->RemoveAura(SPELL_CHANGE_VEHICLE);
                 if( t->IsAlive() )
                     t->RemoveAurasDueToSpell(SPELL_SNOBOLLED);
             }
         }
References ObjectAccessor::GetUnit(), ScriptedAI::me, SPELL_CHANGE_VEHICLE, SPELL_SNOBOLLED, and TargetGUID.
MoveInLineOfSight()
void npc_snobold_vassal::npc_snobold_vassalAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 121 of file boss_northrend_beasts.cpp.
 {}
Reset()
void npc_snobold_vassal::npc_snobold_vassalAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 100 of file boss_northrend_beasts.cpp.
         {
             events.Reset();
             events.ScheduleEvent(EVENT_SPELL_FIRE_BOMB, urand(10000, 30000));
         }
References EVENT_SPELL_FIRE_BOMB, and urand().
Referenced by UpdateAI().
UpdateAI()
void npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 123 of file boss_northrend_beasts.cpp.
         {
             if( !TargetGUID && !me->GetVehicle() )
                 return;
             Unit* t = ObjectAccessor::GetUnit(*me, TargetGUID);
             if( !t && !(t = me->GetVehicleBase()) )
                 return;
             if( t->isDead() )
             {
                 t->RemoveAura(SPELL_CHANGE_VEHICLE);
                 me->RemoveAllAuras();
                 me->DeleteThreatList();
                 me->CombatStop(true);
                 me->SetHealth(me->GetMaxHealth());
                 if( pInstance )
                     if( Creature* gormok = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(TYPE_GORMOK)) )
                         if( gormok->IsAlive() )
                             if( Vehicle* vk = gormok->GetVehicleKit() )
                                 for( uint8 i = 0; i < 4; ++i )
                                     if( !vk->GetPassenger(i) )
{
                                         me->EnterVehicleUnattackable(gormok, i);
                                         Reset();
                                         break;
                                     }
                 TargetGUID.Clear();
                 return;
             }
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_SNOBOLLED:
                     if( t->GetTypeId() == TYPEID_PLAYER )
                         me->CastSpell((Unit*)nullptr, SPELL_SNOBOLLED, true);
                     break;
                 case EVENT_SPELL_BATTER:
                     if( t->GetTypeId() == TYPEID_PLAYER )
                         me->CastSpell(t, SPELL_BATTER);
                     events.RepeatEvent(urand(6000, 8000));
                     break;
                 case EVENT_SPELL_FIRE_BOMB:
                     {
                         if( t->GetTypeId() != TYPEID_PLAYER && pInstance )
{
                             GuidVector validPlayers;
                             Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                             Creature* gormok = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(TYPE_GORMOK));
                             for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
{
                                 if( Player* p = itr->GetSource() )
                                     if( p->IsAlive() && p->GetGUID() != TargetGUID && (!gormok || !p->IsWithinMeleeRange(gormok)) )
                                         validPlayers.push_back(p->GetGUID());
                             }
                             if( !validPlayers.empty() )
                                 if( Player* p = ObjectAccessor::GetPlayer(*me, validPlayers.at(urand(0, validPlayers.size() - 1))) )
                                     if( Creature* trigger = me->SummonCreature(NPC_FIRE_BOMB, *p, TEMPSUMMON_TIMED_DESPAWN, 60000) )
{
                                         me->CastSpell(trigger, SPELL_FIRE_BOMB_AURA, true); // periodic damage aura, speed 14.0f
                                         me->CastSpell(trigger, SPELL_FIRE_BOMB); // visual + initial damage 4k
                                     }
                         }
                         events.RepeatEvent(urand(20000, 30000));
                     }
                     break;
                 case EVENT_SPELL_HEAD_CRACK:
                     if( t->GetTypeId() == TYPEID_PLAYER )
                         me->CastSpell(t, SPELL_HEAD_CRACK);
                     events.RepeatEvent(urand(30000, 35000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References MapRefMgr::begin(), Unit::CastSpell(), ObjectGuid::Clear(), Unit::CombatStop(), Unit::DeleteThreatList(), diff(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), Unit::EnterVehicleUnattackable(), EVENT_SPELL_BATTER, EVENT_SPELL_FIRE_BOMB, EVENT_SPELL_HEAD_CRACK, EVENT_SPELL_SNOBOLLED, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMaxHealth(), ObjectAccessor::GetPlayer(), Map::GetPlayers(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVehicle(), Unit::GetVehicleBase(), Unit::HasUnitState(), Unit::isDead(), Unit::IsWithinMeleeRange(), ScriptedAI::me, NPC_FIRE_BOMB, pInstance, Unit::RemoveAllAuras(), Unit::RemoveAura(), Reset(), Unit::SetHealth(), SPELL_BATTER, SPELL_CHANGE_VEHICLE, SPELL_FIRE_BOMB, SPELL_FIRE_BOMB_AURA, SPELL_HEAD_CRACK, SPELL_SNOBOLLED, WorldObject::SummonCreature(), TargetGUID, TEMPSUMMON_TIMED_DESPAWN, TYPE_GORMOK, TYPEID_PLAYER, UNIT_STATE_CASTING, and urand().
Member Data Documentation
events
EventMap npc_snobold_vassal::npc_snobold_vassalAI::events
Definition at line 97 of file boss_northrend_beasts.cpp.
pInstance
InstanceScript* npc_snobold_vassal::npc_snobold_vassalAI::pInstance
Definition at line 96 of file boss_northrend_beasts.cpp.
Referenced by npc_snobold_vassalAI(), and UpdateAI().
TargetGUID
ObjectGuid npc_snobold_vassal::npc_snobold_vassalAI::TargetGUID
Definition at line 98 of file boss_northrend_beasts.cpp.
Referenced by AttackStart(), DoAction(), JustDied(), npc_snobold_vassalAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp