Azerotcore-wotlk: at_bring_your_orphan_to Class Reference
at_bring_your_orphan_to Class Reference
Public Member Functions
at_bring_your_orphan_to ()
bool OnTrigger (Player *player, AreaTrigger const *trigger) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 856 of file childrens_week.cpp.
Constructor & Destructor Documentation
at_bring_your_orphan_to()
at_bring_your_orphan_to::at_bring_your_orphan_to () inline
Definition at line 859 of file childrens_week.cpp.
 : AreaTriggerScript("at_bring_your_orphan_to") { }
Member Function Documentation
OnTrigger()
bool at_bring_your_orphan_to::OnTrigger (Player * player, AreaTrigger const * trigger) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 861 of file childrens_week.cpp.
     {
         if (player->isDead() || !player->HasAura(SPELL_ORPHAN_OUT))
             return false;
         uint32 questId = 0;
         uint32 orphanId = 0;
         switch (trigger->entry)
         {
             case AT_DOWN_AT_THE_DOCKS:
                 questId = QUEST_DOWN_AT_THE_DOCKS;
                 orphanId = ORPHAN_ORCISH;
                 break;
             case AT_GATEWAY_TO_THE_FRONTIER:
                 questId = QUEST_GATEWAY_TO_THE_FRONTIER;
                 orphanId = ORPHAN_ORCISH;
                 break;
             case AT_LORDAERON_THRONE_ROOM:
                 questId = QUEST_LORDAERON_THRONE_ROOM;
                 orphanId = ORPHAN_ORCISH;
                 break;
             case AT_BOUGHT_OF_ETERNALS:
                 questId = QUEST_BOUGHT_OF_ETERNALS;
                 orphanId = ORPHAN_HUMAN;
                 break;
             case AT_SPOOKY_LIGHTHOUSE:
                 questId = QUEST_SPOOKY_LIGHTHOUSE;
                 orphanId = ORPHAN_HUMAN;
                 break;
             case AT_STONEWROUGHT_DAM:
                 questId = QUEST_STONEWROUGHT_DAM;
                 orphanId = ORPHAN_HUMAN;
                 break;
             case AT_DARK_PORTAL:
                 questId = player->GetTeamId() == TEAM_ALLIANCE ? QUEST_DARK_PORTAL_A : QUEST_DARK_PORTAL_H;
                 orphanId = player->GetTeamId() == TEAM_ALLIANCE ? ORPHAN_DRAENEI : ORPHAN_BLOOD_ELF;
                 break;
         }
         if (questId && orphanId && getOrphanGUID(player, orphanId) && player->GetQuestStatus(questId) == QUEST_STATUS_INCOMPLETE)
             player->AreaExploredOrEventHappens(questId);
         return true;
     }
References Player::AreaExploredOrEventHappens(), AT_BOUGHT_OF_ETERNALS, AT_DARK_PORTAL, AT_DOWN_AT_THE_DOCKS, AT_GATEWAY_TO_THE_FRONTIER, AT_LORDAERON_THRONE_ROOM, AT_SPOOKY_LIGHTHOUSE, AT_STONEWROUGHT_DAM, AreaTrigger::entry, getOrphanGUID(), Player::GetQuestStatus(), Player::GetTeamId(), Unit::HasAura(), Unit::isDead(), ORPHAN_BLOOD_ELF, ORPHAN_DRAENEI, ORPHAN_HUMAN, ORPHAN_ORCISH, QUEST_BOUGHT_OF_ETERNALS, QUEST_DARK_PORTAL_A, QUEST_DARK_PORTAL_H, QUEST_DOWN_AT_THE_DOCKS, QUEST_GATEWAY_TO_THE_FRONTIER, QUEST_LORDAERON_THRONE_ROOM, QUEST_SPOOKY_LIGHTHOUSE, QUEST_STATUS_INCOMPLETE, QUEST_STONEWROUGHT_DAM, SPELL_ORPHAN_OUT, and TEAM_ALLIANCE.
The documentation for this class was generated from the following file:
src/server/scripts/Events/childrens_week.cpp