Azerotcore-wotlk: BfWGGameObjectBuilding Struct Reference
BfWGGameObjectBuilding Struct Reference
#include <BattlefieldWG.h>
Public Member Functions
BfWGGameObjectBuilding (BattlefieldWG *WG)
void Rebuild ()
void Damaged ()
void Destroyed ()
void Init (GameObject *gobj, uint32 type, uint32 worldstate, uint8 damageText, uint8 destroyText)
void UpdateCreatureAndGo ()
void UpdateTurretAttack (bool disable)
void Save ()
Public Attributes
TeamId m_Team
BattlefieldWG * m_WG
ObjectGuid m_Build
uint32 m_Type
uint32 m_WorldState
uint32 m_State
uint8 m_damagedText
uint8 m_destroyedText
GameObjectSet m_GameObjectList [2]
GuidUnorderedSet m_CreatureBottomList [2]
GuidUnorderedSet m_CreatureTopList [2]
GuidUnorderedSet m_TowerCannonBottomList
GuidUnorderedSet m_TurretTopList
Detailed Description
Definition at line 1088 of file BattlefieldWG.h.
Constructor & Destructor Documentation
BfWGGameObjectBuilding()
BfWGGameObjectBuilding::BfWGGameObjectBuilding (BattlefieldWG * WG) inline
Definition at line 1090 of file BattlefieldWG.h.
     {
         m_WG = WG;
         m_Team = TEAM_ALLIANCE;
         m_Type = 0;
         m_WorldState = 0;
         m_State = 0;
         m_damagedText = 0;
         m_destroyedText = 0;
     }
References m_damagedText, m_destroyedText, m_State, m_Team, m_Type, m_WG, m_WorldState, and TEAM_ALLIANCE.
Member Function Documentation
Damaged()
void BfWGGameObjectBuilding::Damaged () inline
Definition at line 1165 of file BattlefieldWG.h.
     {
         // Update worldstate
         m_State = BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DAMAGE - (m_Team * 3);
         m_WG->SendUpdateWorldState(m_WorldState, m_State);
         // Send warning message
         if (m_damagedText)                                       // tower damage + name
             m_WG->SendWarningToAllInZone(m_damagedText);
         for (GuidUnorderedSet::const_iterator itr = m_CreatureTopList[m_WG->GetAttackerTeam()].begin(); itr != m_CreatureTopList[m_WG->GetAttackerTeam()].end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->HideNpc(creature);
         for (GuidUnorderedSet::const_iterator itr = m_TurretTopList.begin(); itr != m_TurretTopList.end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->HideNpc(creature);
         if (m_Type == BATTLEFIELD_WG_OBJECTTYPE_TOWER)
             m_WG->UpdateDamagedTowerCount(m_WG->GetAttackerTeam());
     }
References BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DAMAGE, BATTLEFIELD_WG_OBJECTTYPE_TOWER, Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), Battlefield::HideNpc(), m_CreatureTopList, m_damagedText, m_State, m_Team, m_TurretTopList, m_Type, m_WG, m_WorldState, Battlefield::SendUpdateWorldState(), Battlefield::SendWarningToAllInZone(), and BattlefieldWG::UpdateDamagedTowerCount().
Destroyed()
void BfWGGameObjectBuilding::Destroyed () inline
Definition at line 1188 of file BattlefieldWG.h.
     {
         // Update worldstate
         m_State = BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DESTROY - (m_Team * 3);
         m_WG->SendUpdateWorldState(m_WorldState, m_State);
         // Warn players
         if (m_destroyedText)
             m_WG->SendWarningToAllInZone(m_destroyedText);
         switch (m_Type)
         {
             // Inform the global wintergrasp script of the destruction of this object
             case BATTLEFIELD_WG_OBJECTTYPE_TOWER:
                 m_WG->UpdatedDestroyedTowerCount(TeamId(m_Team), m_WG->GetGameObject(m_Build));
                 break;
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST:
                 m_WG->SetRelicInteractible(true);
                 if (GameObject* go = m_WG->GetRelic())
                     go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                 else
                     LOG_ERROR("bg.battlefield", "BattlefieldWG: Relic not found.");
                 break;
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR:
             case BATTLEFIELD_WG_OBJECTTYPE_WALL:
             case BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER:
                 m_WG->UpdatedDestroyedTowerCount(TeamId(m_Team), m_WG->GetGameObject(m_Build));
                 break;
         }
         m_WG->BrokenWallOrTower(TeamId(m_Team));
     }
References BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DESTROY, BATTLEFIELD_WG_OBJECTTYPE_DOOR, BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST, BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER, BATTLEFIELD_WG_OBJECTTYPE_TOWER, BATTLEFIELD_WG_OBJECTTYPE_WALL, BattlefieldWG::BrokenWallOrTower(), GAMEOBJECT_FLAGS, Battlefield::GetGameObject(), BattlefieldWG::GetRelic(), GO_FLAG_NOT_SELECTABLE, LOG_ERROR, m_Build, m_destroyedText, m_State, m_Team, m_Type, m_WG, m_WorldState, Battlefield::SendUpdateWorldState(), Battlefield::SendWarningToAllInZone(), BattlefieldWG::SetRelicInteractible(), and BattlefieldWG::UpdatedDestroyedTowerCount().
Init()
void BfWGGameObjectBuilding::Init (GameObject * gobj, uint32 type, uint32 worldstate, uint8 damageText, uint8 destroyText) inline
Definition at line 1221 of file BattlefieldWG.h.
     {
         if (!gobj)
         {
             return;
         }
         // GameObject associated to object
         m_Build = gobj->GetGUID();
         // Type of building (WALL/TOWER/DOOR)
         m_Type = type;
         // WorldState for client (icon on map)
         m_WorldState = worldstate;
         // NameId for Warning text
         m_damagedText = damageText;
         m_destroyedText = destroyText;
         switch (m_Type)
         {
             case BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER:
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST:
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR:
             case BATTLEFIELD_WG_OBJECTTYPE_WALL:
                 m_Team = m_WG->GetDefenderTeam();           // Objects that are part of the keep should be the defender's
                 break;
             case BATTLEFIELD_WG_OBJECTTYPE_TOWER:
                 m_Team = m_WG->GetAttackerTeam();           // The towers in the south should be the attacker's
                 break;
             default:
                 m_Team = TEAM_NEUTRAL;
                 break;
         }
         m_State = sWorld->getWorldState(m_WorldState);
         if (gobj)
         {
             switch (m_State)
             {
                 case BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT:
                 case BATTLEFIELD_WG_OBJECTSTATE_HORDE_INTACT:
                     gobj->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                     break;
                 case BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DESTROY:
                 case BATTLEFIELD_WG_OBJECTSTATE_HORDE_DESTROY:
                     gobj->SetDestructibleState(GO_DESTRUCTIBLE_DESTROYED);
                     break;
                 case BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DAMAGE:
                 case BATTLEFIELD_WG_OBJECTSTATE_HORDE_DAMAGE:
                     gobj->SetDestructibleState(GO_DESTRUCTIBLE_DAMAGED);
                     break;
             }
         }
         int32 towerid = -1;
         switch (gobj->GetEntry())
         {
             case GO_WINTERGRASP_FORTRESS_TOWER_1:
                 towerid = 0;
                 break;
             case GO_WINTERGRASP_FORTRESS_TOWER_2:
                 towerid = 1;
                 break;
             case GO_WINTERGRASP_FORTRESS_TOWER_3:
                 towerid = 2;
                 break;
             case GO_WINTERGRASP_FORTRESS_TOWER_4:
                 towerid = 3;
                 break;
             case GO_WINTERGRASP_SHADOWSIGHT_TOWER:
                 towerid = 4;
                 break;
             case GO_WINTERGRASP_WINTER_S_EDGE_TOWER:
                 towerid = 5;
                 break;
             case GO_WINTERGRASP_FLAMEWATCH_TOWER:
                 towerid = 6;
                 break;
         }
         if (towerid > 3) // Attacker towers
         {
             // Spawn associate gameobjects
             for (uint8 i = 0; i < AttackTowers[towerid - 4].nbObject; i++)
             {
                 WintergraspObjectPositionData gobData = AttackTowers[towerid - 4].GameObject[i];
                 if (GameObject* go = m_WG->SpawnGameObject(gobData.entryHorde, gobData.x, gobData.y, gobData.z, gobData.o))
                     m_GameObjectList[TEAM_HORDE].insert(go);
                 if (GameObject* go = m_WG->SpawnGameObject(gobData.entryAlliance, gobData.x, gobData.y, gobData.z, gobData.o))
                     m_GameObjectList[TEAM_ALLIANCE].insert(go);
             }
             // Spawn associate npc bottom
             for (uint8 i = 0; i < AttackTowers[towerid - 4].nbCreatureBottom; i++)
             {
                 WintergraspObjectPositionData creatureData = AttackTowers[towerid - 4].CreatureBottom[i];
                 if (Creature* creature = m_WG->SpawnCreature(creatureData.entryHorde, creatureData.x, creatureData.y, creatureData.z, creatureData.o, TEAM_HORDE))
                     m_CreatureBottomList[TEAM_HORDE].insert(creature->GetGUID());
                 if (Creature* creature = m_WG->SpawnCreature(creatureData.entryAlliance, creatureData.x, creatureData.y, creatureData.z, creatureData.o, TEAM_ALLIANCE))
                     m_CreatureBottomList[TEAM_ALLIANCE].insert(creature->GetGUID());
             }
             // Spawn associate npc top
             for (uint8 i = 0; i < AttackTowers[towerid - 4].nbCreatureTop; i++)
             {
                 WintergraspObjectPositionData creatureData = AttackTowers[towerid - 4].CreatureTop[i];
                 if (Creature* creature = m_WG->SpawnCreature(creatureData.entryHorde, creatureData.x, creatureData.y, creatureData.z, creatureData.o, TEAM_HORDE))
                     m_CreatureTopList[TEAM_HORDE].insert(creature->GetGUID());
                 if (Creature* creature = m_WG->SpawnCreature(creatureData.entryAlliance, creatureData.x, creatureData.y, creatureData.z, creatureData.o, TEAM_ALLIANCE))
                     m_CreatureTopList[TEAM_ALLIANCE].insert(creature->GetGUID());
             }
         }
         if (towerid >= 0)
         {
             // Spawn Turret bottom
             for (uint8 i = 0; i < TowerCannon[towerid].nbTowerCannonBottom; i++)
             {
                 Position turretPos = TowerCannon[towerid].TowerCannonBottom[i].GetPosition();
                 if (Creature* turret = m_WG->SpawnCreature(NPC_WINTERGRASP_TOWER_CANNON, turretPos, TEAM_ALLIANCE))
                 {
                     m_TowerCannonBottomList.insert(turret->GetGUID());
                     m_WG->HideNpc(turret);
                 }
             }
             // Spawn Turret top
             for (uint8 i = 0; i < TowerCannon[towerid].nbTurretTop; i++)
             {
                 Position towerCannonPos = TowerCannon[towerid].TurretTop[i].GetPosition();
                 if (Creature* turret = m_WG->SpawnCreature(NPC_WINTERGRASP_TOWER_CANNON, towerCannonPos, TEAM_ALLIANCE))
                 {
                     m_TurretTopList.insert(turret->GetGUID());
                     m_WG->HideNpc(turret);
                 }
             }
             UpdateCreatureAndGo();
         }
     }
References AttackTowers, BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DAMAGE, BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_DESTROY, BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT, BATTLEFIELD_WG_OBJECTSTATE_HORDE_DAMAGE, BATTLEFIELD_WG_OBJECTSTATE_HORDE_DESTROY, BATTLEFIELD_WG_OBJECTSTATE_HORDE_INTACT, BATTLEFIELD_WG_OBJECTTYPE_DOOR, BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST, BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER, BATTLEFIELD_WG_OBJECTTYPE_TOWER, BATTLEFIELD_WG_OBJECTTYPE_WALL, WintergraspTowerData::CreatureBottom, creatureData, WintergraspTowerData::CreatureTop, WintergraspObjectPositionData::entryAlliance, WintergraspObjectPositionData::entryHorde, WintergraspTowerData::GameObject, Battlefield::GetAttackerTeam(), Battlefield::GetDefenderTeam(), Object::GetEntry(), Object::GetGUID(), Position::GetPosition(), GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_REBUILDING, GO_WINTERGRASP_FLAMEWATCH_TOWER, GO_WINTERGRASP_FORTRESS_TOWER_1, GO_WINTERGRASP_FORTRESS_TOWER_2, GO_WINTERGRASP_FORTRESS_TOWER_3, GO_WINTERGRASP_FORTRESS_TOWER_4, GO_WINTERGRASP_SHADOWSIGHT_TOWER, GO_WINTERGRASP_WINTER_S_EDGE_TOWER, Battlefield::HideNpc(), m_Build, m_CreatureBottomList, m_CreatureTopList, m_damagedText, m_destroyedText, m_GameObjectList, m_State, m_Team, m_TowerCannonBottomList, m_TurretTopList, m_Type, m_WG, m_WorldState, WintergraspTowerData::nbCreatureBottom, WintergraspTowerData::nbCreatureTop, WintergraspTowerData::nbObject, WintergraspTowerCannonData::nbTowerCannonBottom, WintergraspTowerCannonData::nbTurretTop, NPC_WINTERGRASP_TOWER_CANNON, WintergraspObjectPositionData::o, GameObject::SetDestructibleState(), Battlefield::SpawnCreature(), Battlefield::SpawnGameObject(), sWorld, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, TowerCannon, WintergraspTowerCannonData::TowerCannonBottom, WintergraspTowerCannonData::TurretTop, UpdateCreatureAndGo(), WintergraspObjectPositionData::x, WintergraspObjectPositionData::y, and WintergraspObjectPositionData::z.
Referenced by BattlefieldWG::SetupBattlefield().
Rebuild()
void BfWGGameObjectBuilding::Rebuild () inline
Definition at line 1132 of file BattlefieldWG.h.
     {
         switch (m_Type)
         {
             case BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER:
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST:
             case BATTLEFIELD_WG_OBJECTTYPE_DOOR:
             case BATTLEFIELD_WG_OBJECTTYPE_WALL:
                 m_Team = m_WG->GetDefenderTeam();           // Objects that are part of the keep should be the defender's
                 break;
             case BATTLEFIELD_WG_OBJECTTYPE_TOWER:
                 m_Team = m_WG->GetAttackerTeam();           // The towers in the south should be the attacker's
                 break;
             default:
                 m_Team = TEAM_NEUTRAL;
                 break;
         }
         GameObject* go = m_WG->GetGameObject(m_Build);
         if (go)
         {
             // Rebuild gameobject
             go->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
             go->SetUInt32Value(GAMEOBJECT_FACTION, WintergraspFaction[m_Team]);
         }
         // Update worldstate
         m_State = BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT - (m_Team * 3);
         m_WG->SendUpdateWorldState(m_WorldState, m_State);
         UpdateCreatureAndGo();
     }
References BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT, BATTLEFIELD_WG_OBJECTTYPE_DOOR, BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST, BATTLEFIELD_WG_OBJECTTYPE_KEEP_TOWER, BATTLEFIELD_WG_OBJECTTYPE_TOWER, BATTLEFIELD_WG_OBJECTTYPE_WALL, GAMEOBJECT_FACTION, Battlefield::GetAttackerTeam(), Battlefield::GetDefenderTeam(), Battlefield::GetGameObject(), GO_DESTRUCTIBLE_REBUILDING, m_Build, m_State, m_Team, m_Type, m_WG, m_WorldState, Battlefield::SendUpdateWorldState(), GameObject::SetDestructibleState(), Object::SetUInt32Value(), TEAM_NEUTRAL, UpdateCreatureAndGo(), and WintergraspFaction.
Save()
void BfWGGameObjectBuilding::Save () inline
Definition at line 1435 of file BattlefieldWG.h.
     {
         sWorld->setWorldState(m_WorldState, m_State);
     }
References m_State, m_WorldState, and sWorld.
UpdateCreatureAndGo()
void BfWGGameObjectBuilding::UpdateCreatureAndGo () inline
Definition at line 1363 of file BattlefieldWG.h.
     {
         for (GuidUnorderedSet::const_iterator itr = m_CreatureTopList[m_WG->GetDefenderTeam()].begin(); itr != m_CreatureTopList[m_WG->GetDefenderTeam()].end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->HideNpc(creature);
         for (GuidUnorderedSet::const_iterator itr = m_CreatureTopList[m_WG->GetAttackerTeam()].begin(); itr != m_CreatureTopList[m_WG->GetAttackerTeam()].end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->ShowNpc(creature, true);
         for (GuidUnorderedSet::const_iterator itr = m_CreatureBottomList[m_WG->GetDefenderTeam()].begin(); itr != m_CreatureBottomList[m_WG->GetDefenderTeam()].end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->HideNpc(creature);
         for (GuidUnorderedSet::const_iterator itr = m_CreatureBottomList[m_WG->GetAttackerTeam()].begin(); itr != m_CreatureBottomList[m_WG->GetAttackerTeam()].end(); ++itr)
             if (Creature* creature = m_WG->GetCreature(*itr))
                 m_WG->ShowNpc(creature, true);
         for (GameObjectSet::const_iterator itr = m_GameObjectList[m_WG->GetDefenderTeam()].begin(); itr != m_GameObjectList[m_WG->GetDefenderTeam()].end(); ++itr)
             (*itr)->SetRespawnTime(RESPAWN_ONE_DAY);
         for (GameObjectSet::const_iterator itr = m_GameObjectList[m_WG->GetAttackerTeam()].begin(); itr != m_GameObjectList[m_WG->GetAttackerTeam()].end(); ++itr)
             (*itr)->SetRespawnTime(RESPAWN_IMMEDIATELY);
     }
References Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), Battlefield::GetDefenderTeam(), Battlefield::HideNpc(), m_CreatureBottomList, m_CreatureTopList, m_GameObjectList, m_WG, RESPAWN_IMMEDIATELY, RESPAWN_ONE_DAY, and Battlefield::ShowNpc().
Referenced by Init(), and Rebuild().
UpdateTurretAttack()
void BfWGGameObjectBuilding::UpdateTurretAttack (bool disable) inline
Definition at line 1388 of file BattlefieldWG.h.
     {
         GameObject* build = m_WG->GetGameObject(m_Build);
         if (!build)
             return;
         uint32 faction = 0;
         switch (build->GetEntry())
         {
             case GO_WINTERGRASP_FORTRESS_TOWER_1:
             case GO_WINTERGRASP_FORTRESS_TOWER_2:
             case GO_WINTERGRASP_FORTRESS_TOWER_3:
             case GO_WINTERGRASP_FORTRESS_TOWER_4:
                 faction = WintergraspFaction[m_WG->GetDefenderTeam()];
                 break;
             case GO_WINTERGRASP_SHADOWSIGHT_TOWER:
             case GO_WINTERGRASP_WINTER_S_EDGE_TOWER:
             case GO_WINTERGRASP_FLAMEWATCH_TOWER:
                 faction = WintergraspFaction[m_WG->GetAttackerTeam()];
                 break;
         }
         for (GuidUnorderedSet::const_iterator itr = m_TowerCannonBottomList.begin(); itr != m_TowerCannonBottomList.end(); ++itr)
         {
             if (Creature* creature = m_WG->GetCreature(*itr))
             {
                 creature->SetFaction(faction);
                 if (disable)
                     m_WG->HideNpc(creature);
                 else
                     m_WG->ShowNpc(creature, true);
             }
         }
         for (GuidUnorderedSet::const_iterator itr = m_TurretTopList.begin(); itr != m_TurretTopList.end(); ++itr)
         {
             if (Creature* creature = m_WG->GetCreature(*itr))
             {
                 creature->SetFaction(faction);
                 if (disable)
                     m_WG->HideNpc(creature);
                 else
                     m_WG->ShowNpc(creature, true);
             }
         }
     }
References Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), Battlefield::GetDefenderTeam(), Object::GetEntry(), Battlefield::GetGameObject(), GO_WINTERGRASP_FLAMEWATCH_TOWER, GO_WINTERGRASP_FORTRESS_TOWER_1, GO_WINTERGRASP_FORTRESS_TOWER_2, GO_WINTERGRASP_FORTRESS_TOWER_3, GO_WINTERGRASP_FORTRESS_TOWER_4, GO_WINTERGRASP_SHADOWSIGHT_TOWER, GO_WINTERGRASP_WINTER_S_EDGE_TOWER, Battlefield::HideNpc(), m_Build, m_TowerCannonBottomList, m_TurretTopList, m_WG, Battlefield::ShowNpc(), and WintergraspFaction.
Member Data Documentation
m_Build
ObjectGuid BfWGGameObjectBuilding::m_Build
Definition at line 1108 of file BattlefieldWG.h.
Referenced by Destroyed(), Init(), Rebuild(), and UpdateTurretAttack().
m_CreatureBottomList
GuidUnorderedSet BfWGGameObjectBuilding::m_CreatureBottomList[2]
Definition at line 1127 of file BattlefieldWG.h.
Referenced by Init(), and UpdateCreatureAndGo().
m_CreatureTopList
GuidUnorderedSet BfWGGameObjectBuilding::m_CreatureTopList[2]
Definition at line 1128 of file BattlefieldWG.h.
Referenced by Damaged(), Init(), and UpdateCreatureAndGo().
m_damagedText
uint8 BfWGGameObjectBuilding::m_damagedText
Definition at line 1120 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), and Init().
m_destroyedText
uint8 BfWGGameObjectBuilding::m_destroyedText
Definition at line 1121 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Destroyed(), and Init().
m_GameObjectList
GameObjectSet BfWGGameObjectBuilding::m_GameObjectList[2]
Definition at line 1124 of file BattlefieldWG.h.
Referenced by Init(), and UpdateCreatureAndGo().
m_State
uint32 BfWGGameObjectBuilding::m_State
Definition at line 1117 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), Destroyed(), Init(), Rebuild(), and Save().
m_Team
TeamId BfWGGameObjectBuilding::m_Team
Definition at line 1102 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), Destroyed(), Init(), and Rebuild().
m_TowerCannonBottomList
GuidUnorderedSet BfWGGameObjectBuilding::m_TowerCannonBottomList
Definition at line 1129 of file BattlefieldWG.h.
Referenced by Init(), and UpdateTurretAttack().
m_TurretTopList
GuidUnorderedSet BfWGGameObjectBuilding::m_TurretTopList
Definition at line 1130 of file BattlefieldWG.h.
Referenced by Damaged(), Init(), and UpdateTurretAttack().
m_Type
uint32 BfWGGameObjectBuilding::m_Type
Definition at line 1111 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), Destroyed(), Init(), and Rebuild().
m_WG
BattlefieldWG* BfWGGameObjectBuilding::m_WG
Definition at line 1105 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), Destroyed(), Init(), Rebuild(), UpdateCreatureAndGo(), and UpdateTurretAttack().
m_WorldState
uint32 BfWGGameObjectBuilding::m_WorldState
Definition at line 1114 of file BattlefieldWG.h.
Referenced by BfWGGameObjectBuilding(), Damaged(), Destroyed(), Init(), Rebuild(), and Save().
The documentation for this struct was generated from the following file:
src/server/game/Battlefield/Zones/BattlefieldWG.h