Azerotcore-wotlk: npc_commandscript Class Reference
npc_commandscript Class Reference
Public Member Functions
npc_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleNpcAddCommand (ChatHandler *handler, CreatureEntry id)
static bool HandleNpcAddVendorItemCommand (ChatHandler *handler, ItemTemplate const *item, Optional< uint32 > mc, Optional< uint32 > it, Optional< uint32 > ec, Optional< bool > addMulti)
static bool HandleNpcAddMoveCommand (ChatHandler *handler, CreatureSpawnId lowGuid)
static bool HandleNpcSetAllowMovementCommand (ChatHandler *handler)
static bool HandleNpcSetEntryCommand (ChatHandler *handler, CreatureEntry newEntryNum)
static bool HandleNpcSetLevelCommand (ChatHandler *handler, uint8 lvl)
static bool HandleNpcDeleteCommand (ChatHandler *handler)
static bool HandleNpcDeleteVendorItemCommand (ChatHandler *handler, ItemTemplate const *item, Optional< bool > addMulti)
static bool HandleNpcSetFactionIdCommand (ChatHandler *handler, uint32 factionId)
static bool HandleNpcSetFactionTempIdCommand (ChatHandler *handler, uint32 tempfaction)
static bool HandleNpcSetOriginalFaction (ChatHandler *handler)
static bool HandleNpcSetFlagCommand (ChatHandler *handler, uint32 npcFlags)
static bool HandleNpcSetDataCommand (ChatHandler *handler, uint32 data_1, uint32 data_2)
static bool HandleNpcFollowCommand (ChatHandler *handler)
static bool HandleNpcInfoCommand (ChatHandler *handler)
static bool HandleNpcNearCommand (ChatHandler *handler, Optional< float > dist)
static bool HandleNpcMoveCommand (ChatHandler *handler)
static bool HandleNpcPlayEmoteCommand (ChatHandler *handler, uint32 emote)
static bool HandleNpcSetModelCommand (ChatHandler *handler, uint32 displayId)
static bool HandleNpcSetMoveTypeCommand (ChatHandler *handler, Optional< CreatureSpawnId > lowGuid, Variant< EXACT_SEQUENCE("stay"), EXACT_SEQUENCE("random"), EXACT_SEQUENCE("way")> type, Optional< EXACT_SEQUENCE("nodel")> nodel)
static bool HandleNpcSetPhaseCommand (ChatHandler *handler, uint32 phasemask)
static bool HandleNpcSetWanderDistanceCommand (ChatHandler *handler, float option)
static bool HandleNpcSetSpawnTimeCommand (ChatHandler *handler, uint32 spawnTime)
static bool HandleNpcSayCommand (ChatHandler *handler, Tail text)
static bool HandleNpcTextEmoteCommand (ChatHandler *handler, Tail text)
static bool HandleNpcUnFollowCommand (ChatHandler *handler)
static bool HandleNpcWhisperCommand (ChatHandler *handler, std::string const &recv, Tail text)
static bool HandleNpcYellCommand (ChatHandler *handler, Tail text)
static bool HandleNpcAddTempSpawnCommand (ChatHandler *handler, CreatureEntry id)
static bool HandleNpcTameCommand (ChatHandler *handler)
static bool HandleNpcAddFormationCommand (ChatHandler *handler, ObjectGuid::LowType leaderGUID)
static bool HandleNpcSetLinkCommand (ChatHandler *handler, ObjectGuid::LowType linkguid)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 137 of file cs_npc.cpp.
Constructor & Destructor Documentation
npc_commandscript()
npc_commandscript::npc_commandscript () inline
Definition at line 140 of file cs_npc.cpp.
 : CommandScript("npc_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable npc_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 142 of file cs_npc.cpp.
     {
         static ChatCommandTable npcAddCommandTable =
         {
             { "formation",      HandleNpcAddFormationCommand,      SEC_ADMINISTRATOR, Console::No },
             { "item",           HandleNpcAddVendorItemCommand,     SEC_ADMINISTRATOR, Console::No },
             { "move",           HandleNpcAddMoveCommand,           SEC_ADMINISTRATOR, Console::No },
             { "temp",           HandleNpcAddTempSpawnCommand,      SEC_ADMINISTRATOR, Console::No },
             { "",               HandleNpcAddCommand,               SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable npcDeleteCommandTable =
         {
             { "item",           HandleNpcDeleteVendorItemCommand,  SEC_ADMINISTRATOR, Console::No },
             { "",               HandleNpcDeleteCommand,            SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable npcFollowCommandTable =
         {
             { "stop",           HandleNpcUnFollowCommand,          SEC_GAMEMASTER, Console::No },
             { "",               HandleNpcFollowCommand,            SEC_GAMEMASTER, Console::No }
         };
         static ChatCommandTable npcFactionCommandTable =
         {
             { "permanent",      HandleNpcSetFactionIdCommand,      SEC_ADMINISTRATOR, Console::No },
             { "temp",           HandleNpcSetFactionTempIdCommand,  SEC_ADMINISTRATOR, Console::No },
             { "original",       HandleNpcSetOriginalFaction,       SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable npcSetCommandTable =
         {
             { "allowmove",      HandleNpcSetAllowMovementCommand,  SEC_ADMINISTRATOR, Console::No },
             { "entry",          HandleNpcSetEntryCommand,          SEC_ADMINISTRATOR, Console::No },
             { "faction",        npcFactionCommandTable},
             { "flag",           HandleNpcSetFlagCommand,           SEC_ADMINISTRATOR, Console::No },
             { "level",          HandleNpcSetLevelCommand,          SEC_ADMINISTRATOR, Console::No },
             { "link",           HandleNpcSetLinkCommand,           SEC_ADMINISTRATOR, Console::No },
             { "model",          HandleNpcSetModelCommand,          SEC_ADMINISTRATOR, Console::No },
             { "movetype",       HandleNpcSetMoveTypeCommand,       SEC_ADMINISTRATOR, Console::No },
             { "phase",          HandleNpcSetPhaseCommand,          SEC_ADMINISTRATOR, Console::No },
             { "wanderdistance", HandleNpcSetWanderDistanceCommand, SEC_ADMINISTRATOR, Console::No },
             { "spawntime",      HandleNpcSetSpawnTimeCommand,      SEC_ADMINISTRATOR, Console::No },
             { "data",           HandleNpcSetDataCommand,           SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable npcCommandTable =
         {
             { "info",           HandleNpcInfoCommand,              SEC_GAMEMASTER, Console::No },
             { "near",           HandleNpcNearCommand,              SEC_GAMEMASTER, Console::No },
             { "move",           HandleNpcMoveCommand,              SEC_GAMEMASTER, Console::No },
             { "playemote",      HandleNpcPlayEmoteCommand,         SEC_GAMEMASTER, Console::No },
             { "say",            HandleNpcSayCommand,               SEC_GAMEMASTER, Console::No },
             { "textemote",      HandleNpcTextEmoteCommand,         SEC_GAMEMASTER, Console::No },
             { "whisper",        HandleNpcWhisperCommand,           SEC_GAMEMASTER, Console::No },
             { "yell",           HandleNpcYellCommand,              SEC_GAMEMASTER, Console::No },
             { "tame",           HandleNpcTameCommand,              SEC_GAMEMASTER, Console::No },
             { "add",            npcAddCommandTable },
             { "delete",         npcDeleteCommandTable },
             { "follow",         npcFollowCommandTable },
             { "set",            npcSetCommandTable }
         };
         static ChatCommandTable commandTable =
         {
             { "npc", npcCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleNpcAddCommand()
static bool npc_commandscript::HandleNpcAddCommand (ChatHandler * handler, CreatureEntry id) inline static
Definition at line 209 of file cs_npc.cpp.
     {
         if (!sObjectMgr->GetCreatureTemplate(id))
             return false;
         Player* chr = handler->GetSession()->GetPlayer();
         float x = chr->GetPositionX();
         float y = chr->GetPositionY();
         float z = chr->GetPositionZ();
         float o = chr->GetOrientation();
         Map* map = chr->GetMap();
         if (Transport* tt = chr->GetTransport())
             if (MotionTransport* trans = tt->ToMotionTransport())
             {
                 ObjectGuid::LowType guid = sObjectMgr->GenerateCreatureSpawnId();
                 CreatureData& data = sObjectMgr->NewOrExistCreatureData(guid);
                 data.id = id;
                 data.phaseMask = chr->GetPhaseMaskForSpawn();
                 data.posX = chr->GetTransOffsetX();
                 data.posY = chr->GetTransOffsetY();
                 data.posZ = chr->GetTransOffsetZ();
                 data.orientation = chr->GetTransOffsetO();
                 Creature* creature = trans->CreateNPCPassenger(guid, &data);
                 creature->SaveToDB(trans->GetGOInfo()->moTransport.mapID, 1 << map->GetSpawnMode(), chr->GetPhaseMaskForSpawn());
                 sObjectMgr->AddCreatureToGrid(guid, &data);
                 return true;
             }
         Creature* creature = new Creature();
         if (!creature->Create(map->GenerateLowGuid<HighGuid::Unit>(), map, chr->GetPhaseMaskForSpawn(), id, 0, x, y, z, o))
         {
             delete creature;
             return false;
         }
         creature->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), chr->GetPhaseMaskForSpawn());
         ObjectGuid::LowType spawnId = creature->GetSpawnId();
         // To call _LoadGoods(); _LoadQuests(); CreateTrainerSpells()
         // current "creature" variable is deleted and created fresh new, otherwise old values might trigger asserts or cause undefined behavior
         creature->CleanupsBeforeDelete();
         delete creature;
         creature = new Creature();
         if (!creature->LoadCreatureFromDB(spawnId, map, true, false, true))
         {
             delete creature;
             return false;
         }
         sObjectMgr->AddCreatureToGrid(spawnId, sObjectMgr->GetCreatureData(spawnId));
         return true;
     }
References Unit::CleanupsBeforeDelete(), Creature::Create(), Map::GenerateLowGuid(), Map::GetId(), WorldObject::GetMap(), Position::GetOrientation(), Player::GetPhaseMaskForSpawn(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Creature::GetSpawnId(), Map::GetSpawnMode(), WorldObject::GetTransOffsetO(), WorldObject::GetTransOffsetX(), WorldObject::GetTransOffsetY(), WorldObject::GetTransOffsetZ(), WorldObject::GetTransport(), CreatureData::id, Creature::LoadCreatureFromDB(), CreatureData::orientation, CreatureData::phaseMask, CreatureData::posX, CreatureData::posY, CreatureData::posZ, Creature::SaveToDB(), sObjectMgr, GameObject::ToMotionTransport(), and Unit.
HandleNpcAddFormationCommand()
static bool npc_commandscript::HandleNpcAddFormationCommand (ChatHandler * handler, ObjectGuid::LowType leaderGUID) inline static
Definition at line 1204 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature || !creature->GetSpawnId())
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         ObjectGuid::LowType lowguid = creature->GetSpawnId();
         if (creature->GetFormation())
         {
             handler->PSendSysMessage("Selected creature is already member of group %u", creature->GetFormation()->GetId());
             return false;
         }
         if (!lowguid)
             return false;
         Player* chr = handler->GetSession()->GetPlayer();
         FormationInfo group_member;
         group_member.follow_angle   = (creature->GetAngle(chr) - chr->GetOrientation()) * 180 / M_PI;
         group_member.follow_dist    = sqrtf(pow(chr->GetPositionX() - creature->GetPositionX(), int(2)) + pow(chr->GetPositionY() - creature->GetPositionY(), int(2)));
         group_member.leaderGUID     = leaderGUID;
         group_member.groupAI        = 0;
         sFormationMgr->CreatureGroupMap[lowguid] = group_member;
         creature->SearchFormation();
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_CREATURE_FORMATION);
         stmt->setUInt32(0, leaderGUID);
         stmt->setUInt32(1, lowguid);
         stmt->setFloat(2, group_member.follow_dist);
         stmt->setFloat(3, group_member.follow_angle);
         stmt->setUInt32(4, uint32(group_member.groupAI));
         WorldDatabase.Execute(stmt);
         handler->PSendSysMessage("Creature %u added to formation with leader %u", lowguid, leaderGUID);
         return true;
     }
References FormationInfo::follow_angle, FormationInfo::follow_dist, Position::GetAngle(), Creature::GetFormation(), CreatureGroup::GetId(), Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Creature::GetSpawnId(), FormationInfo::groupAI, LANG_SELECT_CREATURE, FormationInfo::leaderGUID, ChatHandler::PSendSysMessage(), Creature::SearchFormation(), ChatHandler::SendSysMessage(), PreparedStatementBase::setFloat(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt32(), sFormationMgr, WORLD_INS_CREATURE_FORMATION, and WorldDatabase.
HandleNpcAddMoveCommand()
static bool npc_commandscript::HandleNpcAddMoveCommand (ChatHandler * handler, CreatureSpawnId lowGuid) inline static
Definition at line 304 of file cs_npc.cpp.
     {
         // attempt check creature existence by DB data
         CreatureData const* data = sObjectMgr->GetCreatureData(lowGuid);
         if (!data)
         {
             handler->PSendSysMessage(LANG_COMMAND_CREATGUIDNOTFOUND, uint32(lowGuid));
             handler->SetSentErrorMessage(true);
             return false;
         }
         // Update movement type
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_MOVEMENT_TYPE);
         stmt->setUInt8(0, uint8(WAYPOINT_MOTION_TYPE));
         stmt->setUInt32(1, lowGuid);
         WorldDatabase.Execute(stmt);
         handler->SendSysMessage(LANG_WAYPOINT_ADDED);
         return true;
     }
References LANG_COMMAND_CREATGUIDNOTFOUND, LANG_WAYPOINT_ADDED, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sObjectMgr, WAYPOINT_MOTION_TYPE, WORLD_UPD_CREATURE_MOVEMENT_TYPE, and WorldDatabase.
HandleNpcAddTempSpawnCommand()
static bool npc_commandscript::HandleNpcAddTempSpawnCommand (ChatHandler * handler, CreatureEntry id) inline static
Definition at line 1125 of file cs_npc.cpp.
     {
         Player* chr = handler->GetSession()->GetPlayer();
         if (!id)
             return false;
         chr->SummonCreature(id, *chr, TEMPSUMMON_CORPSE_DESPAWN, 120);
         return true;
     }
References WorldSession::GetPlayer(), ChatHandler::GetSession(), WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_DESPAWN.
HandleNpcAddVendorItemCommand()
static bool npc_commandscript::HandleNpcAddVendorItemCommand (ChatHandler * handler, ItemTemplate const * item, Optional< uint32 > mc, Optional< uint32 > it, Optional< uint32 > ec, Optional< bool > addMulti) inline static
Definition at line 268 of file cs_npc.cpp.
     {
         if (!item)
         {
             handler->SendSysMessage(LANG_COMMAND_NEEDITEMSEND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Creature* vendor = handler->getSelectedCreature();
         if (!vendor)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 itemId = item->ItemId;
         uint32 maxcount = mc.value_or(0);
         uint32 incrtime = it.value_or(0);
         uint32 extendedcost = ec.value_or(0);
         uint32 vendor_entry = addMulti.value_or(false) ? handler->GetSession()->GetCurrentVendor() : vendor->GetEntry();
         if (!sObjectMgr->IsVendorItemValid(vendor_entry, itemId, maxcount, incrtime, extendedcost, handler->GetSession()->GetPlayer()))
         {
             handler->SetSentErrorMessage(true);
             return false;
         }
         sObjectMgr->AddVendorItem(vendor_entry, itemId, maxcount, incrtime, extendedcost);
         handler->PSendSysMessage(LANG_ITEM_ADDED_TO_LIST, itemId, item->Name1.c_str(), maxcount, incrtime, extendedcost);
         return true;
     }
References WorldSession::GetCurrentVendor(), Object::GetEntry(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), ItemTemplate::ItemId, LANG_COMMAND_NEEDITEMSEND, LANG_ITEM_ADDED_TO_LIST, LANG_SELECT_CREATURE, ItemTemplate::Name1, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleNpcDeleteCommand()
static bool npc_commandscript::HandleNpcDeleteCommand (ChatHandler * handler) inline static
Definition at line 389 of file cs_npc.cpp.
     {
         Creature* unit = handler->getSelectedCreature();
         if (!unit || unit->IsPet() || unit->IsTotem())
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // Delete the creature
         unit->CombatStop();
         unit->DeleteFromDB();
         unit->AddObjectToRemoveList();
         handler->SendSysMessage(LANG_COMMAND_DELCREATMESSAGE);
         return true;
     }
References WorldObject::AddObjectToRemoveList(), Unit::CombatStop(), Creature::DeleteFromDB(), ChatHandler::getSelectedCreature(), Unit::IsPet(), Unit::IsTotem(), LANG_COMMAND_DELCREATMESSAGE, LANG_SELECT_CREATURE, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleNpcDeleteVendorItemCommand()
static bool npc_commandscript::HandleNpcDeleteVendorItemCommand (ChatHandler * handler, ItemTemplate const * item, Optional< bool > addMulti) inline static
Definition at line 411 of file cs_npc.cpp.
     {
         Creature* vendor = handler->getSelectedCreature();
         if (!vendor || !vendor->IsVendor())
         {
             handler->SendSysMessage(LANG_COMMAND_VENDORSELECTION);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!item)
         {
             handler->SendSysMessage(LANG_COMMAND_NEEDITEMSEND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 itemId = item->ItemId;
         if (!sObjectMgr->RemoveVendorItem(addMulti.value_or(false) ? handler->GetSession()->GetCurrentVendor() : vendor->GetEntry(), itemId))
         {
             handler->PSendSysMessage(LANG_ITEM_NOT_IN_LIST, itemId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         handler->PSendSysMessage(LANG_ITEM_DELETED_FROM_LIST, itemId, item->Name1.c_str());
         return true;
     }
References WorldSession::GetCurrentVendor(), Object::GetEntry(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Unit::IsVendor(), ItemTemplate::ItemId, LANG_COMMAND_NEEDITEMSEND, LANG_COMMAND_VENDORSELECTION, LANG_ITEM_DELETED_FROM_LIST, LANG_ITEM_NOT_IN_LIST, ItemTemplate::Name1, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleNpcFollowCommand()
static bool npc_commandscript::HandleNpcFollowCommand (ChatHandler * handler) inline static
Definition at line 560 of file cs_npc.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->PSendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // Follow player - Using pet's default dist and angle
         creature->GetMotionMaster()->MoveFollow(player, PET_FOLLOW_DIST, creature->GetFollowAngle());
         handler->PSendSysMessage(LANG_CREATURE_FOLLOW_YOU_NOW, creature->GetName().c_str());
         return true;
     }
References Unit::GetFollowAngle(), Unit::GetMotionMaster(), WorldObject::GetName(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), LANG_CREATURE_FOLLOW_YOU_NOW, LANG_SELECT_CREATURE, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, ChatHandler::PSendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleNpcInfoCommand()
static bool npc_commandscript::HandleNpcInfoCommand (ChatHandler * handler) inline static
Definition at line 579 of file cs_npc.cpp.
     {
         Creature* target = handler->getSelectedCreature();
         if (!target)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         CreatureTemplate const* cInfo = target->GetCreatureTemplate();
         uint32 faction = target->GetFaction();
         uint32 npcflags = target->GetUInt32Value(UNIT_NPC_FLAGS);
         uint32 mechanicImmuneMask = cInfo->MechanicImmuneMask;
         uint32 spellSchoolImmuneMask = cInfo->SpellSchoolImmuneMask;
         uint32 displayid = target->GetDisplayId();
         uint32 nativeid = target->GetNativeDisplayId();
         uint32 Entry = target->GetEntry();
         int64 curRespawnDelay = target->GetRespawnTimeEx() - time(nullptr);
         if (curRespawnDelay < 0)
             curRespawnDelay = 0;
         std::string curRespawnDelayStr = secsToTimeString(uint64(curRespawnDelay), true);
         std::string defRespawnDelayStr = secsToTimeString(target->GetRespawnDelay(), true);
         handler->PSendSysMessage(LANG_NPCINFO_CHAR,  target->GetSpawnId(), target->GetGUID().GetCounter(), faction, npcflags, Entry, displayid, nativeid);
         handler->PSendSysMessage(LANG_NPCINFO_LEVEL, target->getLevel());
         handler->PSendSysMessage(LANG_NPCINFO_EQUIPMENT, target->GetCurrentEquipmentId(), target->GetOriginalEquipmentId());
         handler->PSendSysMessage(LANG_NPCINFO_HEALTH, target->GetCreateHealth(), target->GetMaxHealth(), target->GetHealth());
         handler->PSendSysMessage(LANG_NPCINFO_FLAGS, target->GetUInt32Value(UNIT_FIELD_FLAGS), target->GetUInt32Value(UNIT_FIELD_FLAGS_2), target->GetUInt32Value(UNIT_DYNAMIC_FLAGS), target->GetFaction());
         handler->PSendSysMessage(LANG_COMMAND_RAWPAWNTIMES, defRespawnDelayStr.c_str(), curRespawnDelayStr.c_str());
         handler->PSendSysMessage(LANG_NPCINFO_LOOT,  cInfo->lootid, cInfo->pickpocketLootId, cInfo->SkinLootId);
         handler->PSendSysMessage(LANG_NPCINFO_DUNGEON_ID, target->GetInstanceId());
         handler->PSendSysMessage(LANG_NPCINFO_PHASEMASK, target->GetPhaseMask());
         handler->PSendSysMessage(LANG_NPCINFO_ARMOR, target->GetArmor());
         handler->PSendSysMessage(LANG_NPCINFO_POSITION, float(target->GetPositionX()), float(target->GetPositionY()), float(target->GetPositionZ()));
         handler->PSendSysMessage(LANG_NPCINFO_AIINFO, target->GetAIName().c_str(), target->GetScriptName().c_str());
         for (uint8 i = 0; i < NPCFLAG_COUNT; i++)
         {
             if (npcflags & npcFlagTexts[i].flag)
             {
                 handler->PSendSysMessage(npcFlagTexts[i].text, npcFlagTexts[i].flag);
             }
         }
         handler->PSendSysMessage(LANG_NPCINFO_MECHANIC_IMMUNE, mechanicImmuneMask);
         for (uint8 i = 1; i < MAX_MECHANIC; ++i)
         {
             if (mechanicImmuneMask & (1 << (mechanicImmunes[i].flag - 1)))
             {
                 handler->PSendSysMessage(mechanicImmunes[i].text, mechanicImmunes[i].flag);
             }
         }
         handler->PSendSysMessage(LANG_NPCINFO_SPELL_SCHOOL_IMMUNE, spellSchoolImmuneMask);
         for (uint8 i = 0; i < MAX_SPELL_SCHOOL; ++i)
         {
             if (spellSchoolImmuneMask & (1 << spellSchoolImmunes[i].flag))
             {
                 handler->PSendSysMessage(spellSchoolImmunes[i].text, spellSchoolImmunes[i].flag);
             }
         }
         return true;
     }
References Entry, Creature::GetAIName(), Unit::GetArmor(), ObjectGuid::GetCounter(), Unit::GetCreateHealth(), Creature::GetCreatureTemplate(), Creature::GetCurrentEquipmentId(), Unit::GetDisplayId(), Object::GetEntry(), Unit::GetFaction(), Object::GetGUID(), Unit::GetHealth(), WorldObject::GetInstanceId(), Unit::getLevel(), Unit::GetMaxHealth(), Unit::GetNativeDisplayId(), Creature::GetOriginalEquipmentId(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetRespawnDelay(), Creature::GetRespawnTimeEx(), Creature::GetScriptName(), ChatHandler::getSelectedCreature(), Creature::GetSpawnId(), Object::GetUInt32Value(), LANG_COMMAND_RAWPAWNTIMES, LANG_NPCINFO_AIINFO, LANG_NPCINFO_ARMOR, LANG_NPCINFO_CHAR, LANG_NPCINFO_DUNGEON_ID, LANG_NPCINFO_EQUIPMENT, LANG_NPCINFO_FLAGS, LANG_NPCINFO_HEALTH, LANG_NPCINFO_LEVEL, LANG_NPCINFO_LOOT, LANG_NPCINFO_MECHANIC_IMMUNE, LANG_NPCINFO_PHASEMASK, LANG_NPCINFO_POSITION, LANG_NPCINFO_SPELL_SCHOOL_IMMUNE, LANG_SELECT_CREATURE, CreatureTemplate::lootid, MAX_MECHANIC, MAX_SPELL_SCHOOL, CreatureTemplate::MechanicImmuneMask, mechanicImmunes, NPCFLAG_COUNT, npcFlagTexts, CreatureTemplate::pickpocketLootId, ChatHandler::PSendSysMessage(), secsToTimeString(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), CreatureTemplate::SkinLootId, CreatureTemplate::SpellSchoolImmuneMask, spellSchoolImmunes, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, and UNIT_NPC_FLAGS.
HandleNpcMoveCommand()
static bool npc_commandscript::HandleNpcMoveCommand (ChatHandler * handler) inline static
Definition at line 694 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         ObjectGuid::LowType lowguid = creature->GetSpawnId();
         if (!creature)
             return false;
         CreatureData const* data = sObjectMgr->GetCreatureData(lowguid);
         if (!data)
         {
             handler->PSendSysMessage(LANG_COMMAND_CREATGUIDNOTFOUND, lowguid);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (handler->GetSession()->GetPlayer()->GetMapId() != data->mapid)
         {
             handler->PSendSysMessage(LANG_COMMAND_CREATUREATSAMEMAP, lowguid);
             handler->SetSentErrorMessage(true);
             return false;
         }
         float x = handler->GetSession()->GetPlayer()->GetPositionX();
         float y = handler->GetSession()->GetPlayer()->GetPositionY();
         float z = handler->GetSession()->GetPlayer()->GetPositionZ();
         float o = handler->GetSession()->GetPlayer()->GetOrientation();
         if (creature)
         {
             if (CreatureData const* data = sObjectMgr->GetCreatureData(creature->GetSpawnId()))
             {
                 const_cast<CreatureData*>(data)->posX = x;
                 const_cast<CreatureData*>(data)->posY = y;
                 const_cast<CreatureData*>(data)->posZ = z;
                 const_cast<CreatureData*>(data)->orientation = o;
             }
             creature->SetPosition(x, y, z, o);
             creature->GetMotionMaster()->Initialize();
             if (creature->IsAlive())                            // dead creature will reset movement generator at respawn
             {
                 creature->setDeathState(JUST_DIED);
                 creature->Respawn();
             }
         }
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_POSITION);
         stmt->setFloat(0, x);
         stmt->setFloat(1, y);
         stmt->setFloat(2, z);
         stmt->setFloat(3, o);
         stmt->setUInt32(4, lowguid);
         WorldDatabase.Execute(stmt);
         handler->PSendSysMessage(LANG_COMMAND_CREATUREMOVED);
         return true;
     }
References WorldLocation::GetMapId(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Creature::GetSpawnId(), MotionMaster::Initialize(), Unit::IsAlive(), JUST_DIED, LANG_COMMAND_CREATGUIDNOTFOUND, LANG_COMMAND_CREATUREATSAMEMAP, LANG_COMMAND_CREATUREMOVED, CreatureData::mapid, ChatHandler::PSendSysMessage(), Creature::Respawn(), Creature::setDeathState(), PreparedStatementBase::setFloat(), Creature::SetPosition(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt32(), sObjectMgr, WORLD_UPD_CREATURE_POSITION, and WorldDatabase.
HandleNpcNearCommand()
static bool npc_commandscript::HandleNpcNearCommand (ChatHandler * handler, Optional< float > dist) inline static
Definition at line 647 of file cs_npc.cpp.
     {
         float distance = dist.value_or(10.0f);
         uint32 count = 0;
         Player* player = handler->GetSession()->GetPlayer();
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_CREATURE_NEAREST);
         stmt->setFloat(0, player->GetPositionX());
         stmt->setFloat(1, player->GetPositionY());
         stmt->setFloat(2, player->GetPositionZ());
         stmt->setUInt32(3, player->GetMapId());
         stmt->setFloat(4, player->GetPositionX());
         stmt->setFloat(5, player->GetPositionY());
         stmt->setFloat(6, player->GetPositionZ());
         stmt->setFloat(7, distance * distance);
         stmt->setUInt32(8, player->GetPhaseMask());
         PreparedQueryResult result = WorldDatabase.Query(stmt);
         if (result)
         {
             do
             {
                 Field* fields = result->Fetch();
                 ObjectGuid::LowType guid = fields[0].GetUInt32();
                 uint32 entry = fields[1].GetUInt32();
                 float x = fields[2].GetFloat();
                 float y = fields[3].GetFloat();
                 float z = fields[4].GetFloat();
                 uint16 mapId = fields[5].GetUInt16();
                 CreatureTemplate const* creatureTemplate = sObjectMgr->GetCreatureTemplate(entry);
                 if (!creatureTemplate)
                     continue;
                 handler->PSendSysMessage(LANG_CREATURE_LIST_CHAT, guid, guid, creatureTemplate->Name.c_str(), x, y, z, mapId, "", "");
                 ++count;
             } while (result->NextRow());
         }
         handler->PSendSysMessage(LANG_COMMAND_NEAR_NPC_MESSAGE, distance, count);
         return true;
     }
References Field::GetFloat(), WorldLocation::GetMapId(), WorldObject::GetPhaseMask(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_NEAR_NPC_MESSAGE, LANG_CREATURE_LIST_CHAT, CreatureTemplate::Name, ChatHandler::PSendSysMessage(), PreparedStatementBase::setFloat(), PreparedStatementBase::setUInt32(), sObjectMgr, WORLD_SEL_CREATURE_NEAREST, and WorldDatabase.
HandleNpcPlayEmoteCommand()
static bool npc_commandscript::HandleNpcPlayEmoteCommand (ChatHandler * handler, uint32 emote) inline static
Definition at line 756 of file cs_npc.cpp.
     {
         Creature* target = handler->getSelectedCreature();
         if (!target)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         target->SetUInt32Value(UNIT_NPC_EMOTESTATE, emote);
         return true;
     }
References ChatHandler::getSelectedCreature(), LANG_SELECT_CREATURE, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Object::SetUInt32Value(), and UNIT_NPC_EMOTESTATE.
HandleNpcSayCommand()
static bool npc_commandscript::HandleNpcSayCommand (ChatHandler * handler, Tail text) inline static
Definition at line 997 of file cs_npc.cpp.
     {
         if (text.empty())
             return false;
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->Say(text, LANG_UNIVERSAL);
         // make some emotes
         switch (text.back())
         {
             case '?':   creature->HandleEmoteCommand(EMOTE_ONESHOT_QUESTION);      break;
             case '!':   creature->HandleEmoteCommand(EMOTE_ONESHOT_EXCLAMATION);   break;
             default:    creature->HandleEmoteCommand(EMOTE_ONESHOT_TALK);          break;
         }
         return true;
     }
References EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_QUESTION, EMOTE_ONESHOT_TALK, ChatHandler::getSelectedCreature(), Unit::HandleEmoteCommand(), LANG_SELECT_CREATURE, LANG_UNIVERSAL, Unit::Say(), ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleNpcSetAllowMovementCommand()
static bool npc_commandscript::HandleNpcSetAllowMovementCommand (ChatHandler * handler) inline static
Definition at line 328 of file cs_npc.cpp.
     {
         if (sWorld->getAllowMovement())
         {
             sWorld->SetAllowMovement(false);
             handler->SendSysMessage(LANG_CREATURE_MOVE_DISABLED);
         }
         else
         {
             sWorld->SetAllowMovement(true);
             handler->SendSysMessage(LANG_CREATURE_MOVE_ENABLED);
         }
         return true;
     }
References LANG_CREATURE_MOVE_DISABLED, LANG_CREATURE_MOVE_ENABLED, ChatHandler::SendSysMessage(), and sWorld.
HandleNpcSetDataCommand()
static bool npc_commandscript::HandleNpcSetDataCommand (ChatHandler * handler, uint32 data_1, uint32 data_2) inline static
Definition at line 542 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->AI()->SetData(data_1, data_2);
         std::string AIorScript = !creature->GetAIName().empty() ? "AI type: " + creature->GetAIName() : (!creature->GetScriptName().empty() ? "Script Name: " + creature->GetScriptName() : "No AI or Script Name Set");
         handler->PSendSysMessage(LANG_NPC_SETDATA, creature->GetGUID().GetCounter(), creature->GetEntry(), creature->GetName().c_str(), data_1, data_2, AIorScript.c_str());
         return true;
     }
References Creature::AI(), Creature::GetAIName(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetName(), Creature::GetScriptName(), ChatHandler::getSelectedCreature(), LANG_NPC_SETDATA, LANG_SELECT_CREATURE, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), UnitAI::SetData(), and ChatHandler::SetSentErrorMessage().
HandleNpcSetEntryCommand()
static bool npc_commandscript::HandleNpcSetEntryCommand (ChatHandler * handler, CreatureEntry newEntryNum) inline static
Definition at line 343 of file cs_npc.cpp.
     {
         if (!newEntryNum)
             return false;
         Unit* unit = handler->getSelectedUnit();
         if (!unit || unit->GetTypeId() != TYPEID_UNIT)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Creature* creature = unit->ToCreature();
         if (creature->UpdateEntry(newEntryNum))
             handler->SendSysMessage(LANG_DONE);
         else
             handler->SendSysMessage(LANG_ERROR);
         return true;
     }
References ChatHandler::getSelectedUnit(), Object::GetTypeId(), LANG_DONE, LANG_ERROR, LANG_SELECT_CREATURE, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Object::ToCreature(), TYPEID_UNIT, and Creature::UpdateEntry().
HandleNpcSetFactionIdCommand()
static bool npc_commandscript::HandleNpcSetFactionIdCommand (ChatHandler * handler, uint32 factionId) inline static
Definition at line 441 of file cs_npc.cpp.
     {
         if (!sFactionTemplateStore.LookupEntry(factionId))
         {
             handler->PSendSysMessage(LANG_WRONG_FACTION, factionId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->SetFaction(factionId);
         // Faction is set in creature_template - not inside creature
         // Update in memory..
         if (CreatureTemplate const* cinfo = creature->GetCreatureTemplate())
             const_cast<CreatureTemplate*>(cinfo)->faction = factionId;
         // ..and DB
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_FACTION);
         stmt->setUInt16(0, uint16(factionId));
         stmt->setUInt32(1, creature->GetEntry());
         WorldDatabase.Execute(stmt);
         return true;
     }
References Creature::GetCreatureTemplate(), Object::GetEntry(), ChatHandler::getSelectedCreature(), LANG_SELECT_CREATURE, LANG_WRONG_FACTION, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), Unit::SetFaction(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), sFactionTemplateStore, WORLD_UPD_CREATURE_FACTION, and WorldDatabase.
HandleNpcSetFactionTempIdCommand()
static bool npc_commandscript::HandleNpcSetFactionTempIdCommand (ChatHandler * handler, uint32 tempfaction) inline static
Definition at line 479 of file cs_npc.cpp.
     {
         Player* me = handler->GetSession()->GetPlayer();
         Unit* SelectedCreature = me->GetSelectedUnit();
         if (!SelectedCreature)
             return false;
         Creature* creature = SelectedCreature->ToCreature();
         if (!creature)
             return false;
         creature->SetFaction(tempfaction);
         return true;
     }
References WorldSession::GetPlayer(), Player::GetSelectedUnit(), ChatHandler::GetSession(), Unit::SetFaction(), and Object::ToCreature().
HandleNpcSetFlagCommand()
static bool npc_commandscript::HandleNpcSetFlagCommand (ChatHandler * handler, uint32 npcFlags) inline static
Definition at line 516 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->SetUInt32Value(UNIT_NPC_FLAGS, NPCFlags(npcFlags));
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_NPCFLAG);
         stmt->setUInt32(0, NPCFlags(npcFlags));
         stmt->setUInt32(1, creature->GetEntry());
         WorldDatabase.Execute(stmt);
         handler->SendSysMessage(LANG_VALUE_SAVED_REJOIN);
         return true;
     }
References Object::GetEntry(), ChatHandler::getSelectedCreature(), LANG_SELECT_CREATURE, LANG_VALUE_SAVED_REJOIN, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt32(), Object::SetUInt32Value(), UNIT_NPC_FLAGS, WORLD_UPD_CREATURE_NPCFLAG, and WorldDatabase.
HandleNpcSetLevelCommand()
static bool npc_commandscript::HandleNpcSetLevelCommand (ChatHandler * handler, uint8 lvl) inline static
Definition at line 364 of file cs_npc.cpp.
     {
         if (lvl < 1 || lvl > sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL) + 3)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Creature* creature = handler->getSelectedCreature();
         if (!creature || creature->IsPet())
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->SetMaxHealth(100 + 30*lvl);
         creature->SetHealth(100 + 30*lvl);
         creature->SetLevel(lvl);
         creature->SaveToDB();
         return true;
     }
References CONFIG_MAX_PLAYER_LEVEL, ChatHandler::getSelectedCreature(), Unit::IsPet(), LANG_BAD_VALUE, LANG_SELECT_CREATURE, Creature::SaveToDB(), ChatHandler::SendSysMessage(), Unit::SetHealth(), Unit::SetLevel(), Unit::SetMaxHealth(), ChatHandler::SetSentErrorMessage(), and sWorld.
HandleNpcSetLinkCommand()
static bool npc_commandscript::HandleNpcSetLinkCommand (ChatHandler * handler, ObjectGuid::LowType linkguid) inline static
Definition at line 1249 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!creature->GetSpawnId())
         {
             handler->PSendSysMessage("Selected creature %u isn't in creature table", creature->GetGUID().GetCounter());
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!sObjectMgr->SetCreatureLinkedRespawn(creature->GetSpawnId(), linkguid))
         {
             handler->PSendSysMessage("Selected creature can't link with guid '%u'", linkguid);
             handler->SetSentErrorMessage(true);
             return false;
         }
         handler->PSendSysMessage("LinkGUID '%u' added to creature with DBTableGUID: '%u'", linkguid, creature->GetSpawnId());
         return true;
     }
References ObjectGuid::GetCounter(), Object::GetGUID(), ChatHandler::getSelectedCreature(), Creature::GetSpawnId(), LANG_SELECT_CREATURE, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleNpcSetModelCommand()
static bool npc_commandscript::HandleNpcSetModelCommand (ChatHandler * handler, uint32 displayId) inline static
Definition at line 772 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature || creature->IsPet())
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!sCreatureDisplayInfoStore.LookupEntry(displayId))
         {
             handler->PSendSysMessage(LANG_COMMAND_FACTION_INVPARAM, Acore::ToString(displayId).c_str());
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->SetDisplayId(displayId);
         creature->SetNativeDisplayId(displayId);
         creature->SaveToDB();
         return true;
     }
References ChatHandler::getSelectedCreature(), Unit::IsPet(), LANG_COMMAND_FACTION_INVPARAM, LANG_SELECT_CREATURE, ChatHandler::PSendSysMessage(), Creature::SaveToDB(), sCreatureDisplayInfoStore, ChatHandler::SendSysMessage(), Creature::SetDisplayId(), Unit::SetNativeDisplayId(), ChatHandler::SetSentErrorMessage(), and Acore::ToString().
HandleNpcSetMoveTypeCommand()
static bool npc_commandscript::HandleNpcSetMoveTypeCommand (ChatHandler * handler, Optional< CreatureSpawnId > lowGuid, Variant< EXACT_SEQUENCE("stay"), EXACT_SEQUENCE("random"), EXACT_SEQUENCE("way")> type, Optional< EXACT_SEQUENCE("nodel")> nodel) inline static
HandleNpcSetMoveTypeCommand Set the movement type for an NPC.
Valid movement types are:
stay - NPC wont move
random - NPC will move randomly according to the wander_distance
way - NPC will move with given waypoints set
additional parameter: NODEL - so no waypoints are deleted, if you change the movement type
Definition at line 809 of file cs_npc.cpp.
     {
         // 3 arguments:
         // GUID (optional - you can also select the creature)
         // stay|random|way (determines the kind of movement)
         // NODEL (optional - tells the system NOT to delete any waypoints)
         //        this is very handy if you want to do waypoints, that are
         //        later switched on/off according to special events (like escort
         //        quests, etc)
         bool doNotDelete = nodel.has_value();
         ObjectGuid::LowType lowguid = 0;
         Creature* creature = nullptr;
         if (!lowGuid)                                           // case .setmovetype $move_type (with selected creature)
         {
             creature = handler->getSelectedCreature();
             if (!creature || creature->IsPet())
                 return false;
             lowguid = creature->GetSpawnId();
         }
         else                                                    // case .setmovetype #creature_guid $move_type (with selected creature)
         {
             lowguid = *lowGuid;
             if (lowguid)
                 creature = handler->GetCreatureFromPlayerMapByDbGuid(lowguid);
             // attempt check creature existence by DB data
             if (!creature)
             {
                 CreatureData const* data = sObjectMgr->GetCreatureData(lowguid);
                 if (!data)
                 {
                     handler->PSendSysMessage(LANG_COMMAND_CREATGUIDNOTFOUND, lowguid);
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
             }
             else
             {
                 lowguid = creature->GetSpawnId();
             }
         }
         // now lowguid is low guid really existed creature
         // and creature point (maybe) to this creature or nullptr
         MovementGeneratorType move_type;
         switch (type.index())
         {
             case 0:
                 move_type = IDLE_MOTION_TYPE;
                 break;
             case 1:
                 move_type = RANDOM_MOTION_TYPE;
                 break;
             case 2:
                 move_type = WAYPOINT_MOTION_TYPE;
                 break;
             default:
                 return false;
         }
         // update movement type
         //if (doNotDelete == false)
         //    WaypointMgr.DeletePath(lowguid);
         if (creature)
         {
             // update movement type
             if (!doNotDelete)
                 creature->LoadPath(0);
             creature->SetDefaultMovementType(move_type);
             creature->GetMotionMaster()->Initialize();
             if (creature->IsAlive())                            // dead creature will reset movement generator at respawn
             {
                 creature->setDeathState(JUST_DIED);
                 creature->Respawn();
             }
             creature->SaveToDB();
         }
         if (!doNotDelete)
         {
             handler->PSendSysMessage(LANG_MOVE_TYPE_SET, move_type);
         }
         else
         {
             handler->PSendSysMessage(LANG_MOVE_TYPE_SET_NODEL, move_type);
         }
         return true;
     }
References ChatHandler::GetCreatureFromPlayerMapByDbGuid(), Unit::GetMotionMaster(), ChatHandler::getSelectedCreature(), Creature::GetSpawnId(), IDLE_MOTION_TYPE, MotionMaster::Initialize(), Unit::IsAlive(), Unit::IsPet(), JUST_DIED, LANG_COMMAND_CREATGUIDNOTFOUND, LANG_MOVE_TYPE_SET, LANG_MOVE_TYPE_SET_NODEL, Creature::LoadPath(), ChatHandler::PSendSysMessage(), RANDOM_MOTION_TYPE, Creature::Respawn(), Creature::SaveToDB(), Creature::setDeathState(), Creature::SetDefaultMovementType(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and WAYPOINT_MOTION_TYPE.
HandleNpcSetOriginalFaction()
static bool npc_commandscript::HandleNpcSetOriginalFaction (ChatHandler * handler) inline static
Definition at line 498 of file cs_npc.cpp.
     {
         Player* me = handler->GetSession()->GetPlayer();
         if (!me)
             return false;
         Creature* creature = me->GetSelectedUnit()->ToCreature();
         if (!creature)
             return false;
         creature->RestoreFaction();
         return true;
     }
References WorldSession::GetPlayer(), Player::GetSelectedUnit(), ChatHandler::GetSession(), Unit::RestoreFaction(), and Object::ToCreature().
HandleNpcSetPhaseCommand()
static bool npc_commandscript::HandleNpcSetPhaseCommand (ChatHandler * handler, uint32 phasemask) inline static
Definition at line 910 of file cs_npc.cpp.
     {
         if (phasemask == 0)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->SetPhaseMask(phasemask, true);
         if (!creature->IsPet())
             creature->SaveToDB();
         return true;
     }
References ChatHandler::getSelectedCreature(), Unit::IsPet(), LANG_BAD_VALUE, LANG_SELECT_CREATURE, Creature::SaveToDB(), ChatHandler::SendSysMessage(), Unit::SetPhaseMask(), and ChatHandler::SetSentErrorMessage().
HandleNpcSetSpawnTimeCommand()
static bool npc_commandscript::HandleNpcSetSpawnTimeCommand (ChatHandler * handler, uint32 spawnTime) inline static
Definition at line 980 of file cs_npc.cpp.
     {
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
             return false;
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_SPAWN_TIME_SECS);
         stmt->setUInt32(0, spawnTime);
         stmt->setUInt32(1, creature->GetSpawnId());
         WorldDatabase.Execute(stmt);
         creature->SetRespawnDelay(spawnTime);
         handler->PSendSysMessage(LANG_COMMAND_SPAWNTIME, spawnTime);
         return true;
     }
References ChatHandler::getSelectedCreature(), Creature::GetSpawnId(), LANG_COMMAND_SPAWNTIME, ChatHandler::PSendSysMessage(), Creature::SetRespawnDelay(), PreparedStatementBase::setUInt32(), WORLD_UPD_CREATURE_SPAWN_TIME_SECS, and WorldDatabase.
HandleNpcSetWanderDistanceCommand()
static bool npc_commandscript::HandleNpcSetWanderDistanceCommand (ChatHandler * handler, float option) inline static
Definition at line 936 of file cs_npc.cpp.
     {
         if (option < 0.0f)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             return false;
         }
         MovementGeneratorType mtype = IDLE_MOTION_TYPE;
         if (option > 0.0f)
             mtype = RANDOM_MOTION_TYPE;
         Creature* creature = handler->getSelectedCreature();
         ObjectGuid::LowType guidLow = 0;
         if (creature)
             guidLow = creature->GetSpawnId();
         else
             return false;
         creature->SetWanderDistance((float)option);
         creature->SetDefaultMovementType(mtype);
         creature->GetMotionMaster()->Initialize();
         if (creature->IsAlive())                                // dead creature will reset movement generator at respawn
         {
             creature->setDeathState(JUST_DIED);
             creature->Respawn();
         }
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_UPD_CREATURE_WANDER_DISTANCE);
         stmt->setFloat(0, option);
         stmt->setUInt8(1, uint8(mtype));
         stmt->setUInt32(2, guidLow);
         WorldDatabase.Execute(stmt);
         handler->PSendSysMessage(LANG_COMMAND_WANDER_DISTANCE, option);
         return true;
     }
References Unit::GetMotionMaster(), ChatHandler::getSelectedCreature(), Creature::GetSpawnId(), IDLE_MOTION_TYPE, MotionMaster::Initialize(), Unit::IsAlive(), JUST_DIED, LANG_BAD_VALUE, LANG_COMMAND_WANDER_DISTANCE, ChatHandler::PSendSysMessage(), RANDOM_MOTION_TYPE, Creature::Respawn(), ChatHandler::SendSysMessage(), Creature::setDeathState(), Creature::SetDefaultMovementType(), PreparedStatementBase::setFloat(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), Creature::SetWanderDistance(), WORLD_UPD_CREATURE_WANDER_DISTANCE, and WorldDatabase.
HandleNpcTameCommand()
static bool npc_commandscript::HandleNpcTameCommand (ChatHandler * handler) inline static
Definition at line 1138 of file cs_npc.cpp.
     {
         Creature* creatureTarget = handler->getSelectedCreature();
         if (!creatureTarget || creatureTarget->IsPet())
         {
             handler->PSendSysMessage (LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage (true);
             return false;
         }
         Player* player = handler->GetSession()->GetPlayer();
         if (player->GetPetGUID())
         {
             handler->SendSysMessage (LANG_YOU_ALREADY_HAVE_PET);
             handler->SetSentErrorMessage (true);
             return false;
         }
         CreatureTemplate const* cInfo = creatureTarget->GetCreatureTemplate();
         if (!cInfo->IsTameable(player->CanTameExoticPets()))
         {
             handler->PSendSysMessage (LANG_CREATURE_NON_TAMEABLE, cInfo->Entry);
             handler->SetSentErrorMessage (true);
             return false;
         }
         // Everything looks OK, create new pet
         Pet* pet = player->CreateTamedPetFrom(creatureTarget);
         if (!pet)
         {
             handler->PSendSysMessage (LANG_CREATURE_NON_TAMEABLE, cInfo->Entry);
             handler->SetSentErrorMessage (true);
             return false;
         }
         // place pet before player
         float x, y, z;
         player->GetClosePoint (x, y, z, creatureTarget->GetObjectSize(), CONTACT_DISTANCE);
         pet->Relocate(x, y, z, M_PI - player->GetOrientation());
         // set pet to defensive mode by default (some classes can't control controlled pets in fact).
         pet->SetReactState(REACT_DEFENSIVE);
         // calculate proper level
         uint8 level = (creatureTarget->getLevel() < (player->getLevel() - 5)) ? (player->getLevel() - 5) : creatureTarget->getLevel();
         // prepare visual effect for levelup
         pet->SetUInt32Value(UNIT_FIELD_LEVEL, level - 1);
         // add to world
         pet->GetMap()->AddToMap(pet->ToCreature());
         // visual effect for levelup
         pet->SetUInt32Value(UNIT_FIELD_LEVEL, level);
         // caster have pet now
         player->SetMinion(pet, true);
         pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
         player->PetSpellInitialize();
         return true;
     }
References Map::AddToMap(), Player::CanTameExoticPets(), CONTACT_DISTANCE, Unit::CreateTamedPetFrom(), CreatureTemplate::Entry, WorldObject::GetClosePoint(), Creature::GetCreatureTemplate(), Unit::getLevel(), WorldObject::GetMap(), WorldObject::GetObjectSize(), Position::GetOrientation(), Unit::GetPetGUID(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Unit::IsPet(), CreatureTemplate::IsTameable(), LANG_CREATURE_NON_TAMEABLE, LANG_SELECT_CREATURE, LANG_YOU_ALREADY_HAVE_PET, PET_SAVE_AS_CURRENT, Player::PetSpellInitialize(), ChatHandler::PSendSysMessage(), REACT_DEFENSIVE, Position::Relocate(), Pet::SavePetToDB(), ChatHandler::SendSysMessage(), Unit::SetMinion(), Creature::SetReactState(), ChatHandler::SetSentErrorMessage(), Object::SetUInt32Value(), Object::ToCreature(), and UNIT_FIELD_LEVEL.
HandleNpcTextEmoteCommand()
static bool npc_commandscript::HandleNpcTextEmoteCommand (ChatHandler * handler, Tail text) inline static
Definition at line 1024 of file cs_npc.cpp.
     {
         if (text.empty())
             return false;
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->TextEmote(text);
         return true;
     }
References ChatHandler::getSelectedCreature(), LANG_SELECT_CREATURE, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and Unit::TextEmote().
HandleNpcUnFollowCommand()
static bool npc_commandscript::HandleNpcUnFollowCommand (ChatHandler * handler) inline static
Definition at line 1044 of file cs_npc.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->PSendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (/*creature->GetMotionMaster()->empty() ||*/
             creature->GetMotionMaster()->GetCurrentMovementGeneratorType() != FOLLOW_MOTION_TYPE)
         {
             handler->PSendSysMessage(LANG_CREATURE_NOT_FOLLOW_YOU, creature->GetName().c_str());
             handler->SetSentErrorMessage(true);
             return false;
         }
         FollowMovementGenerator<Creature> const* mgen = static_cast<FollowMovementGenerator<Creature> const*>((creature->GetMotionMaster()->top()));
         if (mgen->GetTarget() != player)
         {
             handler->PSendSysMessage(LANG_CREATURE_NOT_FOLLOW_YOU, creature->GetName().c_str());
             handler->SetSentErrorMessage(true);
             return false;
         }
         // reset movement
         creature->GetMotionMaster()->MovementExpired(true);
         handler->PSendSysMessage(LANG_CREATURE_NOT_FOLLOW_YOU_NOW, creature->GetName().c_str());
         return true;
     }
References FOLLOW_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), WorldObject::GetName(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), FollowMovementGenerator< T >::GetTarget(), LANG_CREATURE_NOT_FOLLOW_YOU, LANG_CREATURE_NOT_FOLLOW_YOU_NOW, LANG_SELECT_CREATURE, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and MotionMaster::top().
HandleNpcWhisperCommand()
static bool npc_commandscript::HandleNpcWhisperCommand (ChatHandler * handler, std::string const & recv, Tail text) inline static
Definition at line 1081 of file cs_npc.cpp.
     {
         if (text.empty())
             return false;
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         Player* receiver = ObjectAccessor::FindPlayerByName(recv);
         if (handler->HasLowerSecurity(receiver, ObjectGuid::Empty))
             return false;
         creature->Whisper(text, LANG_UNIVERSAL, receiver);
         return true;
     }
References ObjectGuid::Empty, ObjectAccessor::FindPlayerByName(), ChatHandler::getSelectedCreature(), ChatHandler::HasLowerSecurity(), LANG_SELECT_CREATURE, LANG_UNIVERSAL, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and Unit::Whisper().
HandleNpcYellCommand()
static bool npc_commandscript::HandleNpcYellCommand (ChatHandler * handler, Tail text) inline static
Definition at line 1103 of file cs_npc.cpp.
     {
         if (text.empty())
             return false;
         Creature* creature = handler->getSelectedCreature();
         if (!creature)
         {
             handler->SendSysMessage(LANG_SELECT_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         creature->Yell(text, LANG_UNIVERSAL);
         // make an emote
         creature->HandleEmoteCommand(EMOTE_ONESHOT_SHOUT);
         return true;
     }
References EMOTE_ONESHOT_SHOUT, ChatHandler::getSelectedCreature(), Unit::HandleEmoteCommand(), LANG_SELECT_CREATURE, LANG_UNIVERSAL, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and Unit::Yell().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_npc.cpp