Azerotcore-wotlk: IceTombSummonEvent Class Reference
IceTombSummonEvent Class Reference
Public Member Functions
IceTombSummonEvent (Unit *owner, ObjectGuid sindragosaGUID)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * _owner
ObjectGuid _sindragosaGUID
Detailed Description
Definition at line 204 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
IceTombSummonEvent()
IceTombSummonEvent::IceTombSummonEvent (Unit * owner, ObjectGuid sindragosaGUID) inline
Definition at line 207 of file boss_sindragosa.cpp.
 : _owner(owner), _sindragosaGUID(sindragosaGUID) { }
Member Function Documentation
Execute()
bool IceTombSummonEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 209 of file boss_sindragosa.cpp.
     {
         if (!_owner->IsAlive() || !_owner->HasAura(SPELL_ICE_TOMB_DAMAGE))
             return true;
         if (Creature* sindragosa = ObjectAccessor::GetCreature(*_owner, _sindragosaGUID))
         {
             if (!sindragosa->IsAlive())
                 return true;
             Position pos = _owner->GetPosition();
             _owner->UpdateGroundPositionZ(pos.m_positionX, pos.m_positionY, pos.m_positionZ);
             if (TempSummon* summon = sindragosa->SummonCreature(NPC_ICE_TOMB, pos))
             {
                 summon->AI()->SetGUID(_owner->GetGUID(), DATA_TRAPPED_PLAYER);
                 _owner->CastSpell(_owner, SPELL_ICE_TOMB_UNTARGETABLE, true);
                 if (GameObject* go = summon->SummonGameObject(GO_ICE_BLOCK, pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 0))
                 {
                     go->SetSpellId(SPELL_ICE_TOMB_DAMAGE);
                     summon->AddGameObject(go);
                 }
             }
         }
         return true;
     }
References _owner, _sindragosaGUID, Unit::CastSpell(), DATA_TRAPPED_PLAYER, ObjectAccessor::GetCreature(), Object::GetGUID(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_ICE_BLOCK, Unit::HasAura(), Unit::IsAlive(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, NPC_ICE_TOMB, SPELL_ICE_TOMB_DAMAGE, SPELL_ICE_TOMB_UNTARGETABLE, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), and WorldObject::UpdateGroundPositionZ().
Member Data Documentation
_owner
Unit* IceTombSummonEvent::_owner private
Definition at line 236 of file boss_sindragosa.cpp.
Referenced by Execute().
_sindragosaGUID
ObjectGuid IceTombSummonEvent::_sindragosaGUID private
Definition at line 237 of file boss_sindragosa.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp