Azerotcore-wotlk: spell_item_make_a_wish Class Reference
spell_item_make_a_wish Class Reference
Private Member Functions
PrepareSpellScript (spell_item_make_a_wish)
bool Load () override
bool Validate (SpellInfo const *) override
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1682 of file spell_item.cpp.
Member Function Documentation
HandleDummy()
void spell_item_make_a_wish::HandleDummy (SpellEffIndex) inline private
Definition at line 1703 of file spell_item.cpp.
     {
         Unit* caster = GetCaster();
         uint32 spellId = SPELL_MR_PINCHYS_GIFT;
         switch (urand(1, 5))
         {
             case 1:
                 spellId = SPELL_MR_PINCHYS_BLESSING;
                 break;
             case 2:
                 spellId = SPELL_SUMMON_MIGHTY_MR_PINCHY;
                 break;
             case 3:
                 spellId = SPELL_SUMMON_FURIOUS_MR_PINCHY;
                 break;
             case 4:
                 spellId = SPELL_TINY_MAGICAL_CRAWDAD;
                 break;
         }
         caster->CastSpell(caster, spellId, true, nullptr);
     }
References Unit::CastSpell(), SpellScript::GetCaster(), SPELL_MR_PINCHYS_BLESSING, SPELL_MR_PINCHYS_GIFT, SPELL_SUMMON_FURIOUS_MR_PINCHY, SPELL_SUMMON_MIGHTY_MR_PINCHY, SPELL_TINY_MAGICAL_CRAWDAD, and urand().
Referenced by Register().
Load()
bool spell_item_make_a_wish::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1686 of file spell_item.cpp.
     {
         return GetCaster()->GetTypeId() == TYPEID_PLAYER;
     }
References SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_PLAYER.
PrepareSpellScript()
spell_item_make_a_wish::PrepareSpellScript (spell_item_make_a_wish) private
Register()
void spell_item_make_a_wish::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1725 of file spell_item.cpp.
     {
         OnEffectHit += SpellEffectFn(spell_item_make_a_wish::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
     }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHit, SPELL_EFFECT_DUMMY, and SpellEffectFn.
Validate()
bool spell_item_make_a_wish::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1691 of file spell_item.cpp.
     {
         return ValidateSpellInfo(
             {
                 SPELL_MR_PINCHYS_BLESSING,
                 SPELL_SUMMON_MIGHTY_MR_PINCHY,
                 SPELL_SUMMON_FURIOUS_MR_PINCHY,
                 SPELL_TINY_MAGICAL_CRAWDAD,
                 SPELL_MR_PINCHYS_GIFT
             });
     }
References SPELL_MR_PINCHYS_BLESSING, SPELL_MR_PINCHYS_GIFT, SPELL_SUMMON_FURIOUS_MR_PINCHY, SPELL_SUMMON_MIGHTY_MR_PINCHY, SPELL_TINY_MAGICAL_CRAWDAD, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_item.cpp