Azerotcore-wotlk: deps/mysqllite/include/my_xml.h File Reference
my_xml.h File Reference
Classes
struct xml_stack_st
Macros
#define MY_XML_OK 0
#define MY_XML_ERROR 1
#define MY_XML_FLAG_RELATIVE_NAMES 1
#define MY_XML_FLAG_SKIP_TEXT_NORMALIZATION 2
Typedefs
typedef struct xml_stack_st MY_XML_PARSER
Enumerations
enum my_xml_node_type { MY_XML_NODE_TAG , MY_XML_NODE_ATTR , MY_XML_NODE_TEXT }
Functions
void my_xml_parser_create (MY_XML_PARSER *st)
void my_xml_parser_free (MY_XML_PARSER *st)
int my_xml_parse (MY_XML_PARSER *st, const char *str, size_t len)
void my_xml_set_value_handler (MY_XML_PARSER *st, int(*)(MY_XML_PARSER *, const char *, size_t len))
void my_xml_set_enter_handler (MY_XML_PARSER *st, int(*)(MY_XML_PARSER *, const char *, size_t len))
void my_xml_set_leave_handler (MY_XML_PARSER *st, int(*)(MY_XML_PARSER *, const char *, size_t len))
void my_xml_set_user_data (MY_XML_PARSER *st, void *)
size_t my_xml_error_pos (MY_XML_PARSER *st)
uint my_xml_error_lineno (MY_XML_PARSER *st)
const char * my_xml_error_string (MY_XML_PARSER *st)
Macro Definition Documentation
MY_XML_ERROR
#define MY_XML_ERROR 1
Definition at line 26 of file my_xml.h.
MY_XML_FLAG_RELATIVE_NAMES
#define MY_XML_FLAG_RELATIVE_NAMES 1
Definition at line 33 of file my_xml.h.
MY_XML_FLAG_SKIP_TEXT_NORMALIZATION
#define MY_XML_FLAG_SKIP_TEXT_NORMALIZATION 2
Definition at line 40 of file my_xml.h.
MY_XML_OK
#define MY_XML_OK 0
Definition at line 25 of file my_xml.h.
Typedef Documentation
MY_XML_PARSER
typedef struct xml_stack_st MY_XML_PARSER
Enumeration Type Documentation
my_xml_node_type
enum my_xml_node_type
Enumerator
MY_XML_NODE_TAG
MY_XML_NODE_ATTR
MY_XML_NODE_TEXT
Definition at line 42 of file my_xml.h.
 {
   MY_XML_NODE_TAG,   /* can have TAG, ATTR and TEXT children */
   MY_XML_NODE_ATTR,  /* can have TEXT children               */
   MY_XML_NODE_TEXT   /* cannot have children                 */
 };
Function Documentation
my_xml_error_lineno()
uint my_xml_error_lineno (MY_XML_PARSER * st)
Definition at line 486 of file xml.c.
 {
   uint res=0;
   const char *s;
   for (s=p->beg ; s<p->cur; s++)
   {
     if (s[0] == '\n')
       res++;
   }
   return res;
 }
References xml_stack_st::beg.
Referenced by my_read_charset_file().
my_xml_error_pos()
size_t my_xml_error_pos (MY_XML_PARSER * st)
Definition at line 474 of file xml.c.
 {
   const char *beg=p->beg;
   const char *s;
   for ( s=p->beg ; s<p->cur; s++)
   {
     if (s[0] == '\n')
       beg=s;
   }
   return (size_t) (p->cur-beg);
 }
References xml_stack_st::beg, and xml_stack_st::cur.
Referenced by my_read_charset_file().
my_xml_error_string()
const char* my_xml_error_string (MY_XML_PARSER * st)
Definition at line 468 of file xml.c.
 {
   return p->errstr;
 }
References xml_stack_st::errstr.
Referenced by my_read_charset_file().
my_xml_parse()
int my_xml_parse (MY_XML_PARSER * st, const char * str, size_t len)
Definition at line 262 of file xml.c.
 {
   p->attrend=p->attr;
   p->beg=str;
   p->cur=str;
   p->end=str+len;
   while ( p->cur < p->end )
   {
     MY_XML_ATTR a;
     if (p->cur[0] == '<')
     {
       int lex;
       int question=0;
       int exclam=0;
       lex=my_xml_scan(p,&a);
       if (MY_XML_COMMENT == lex)
         continue;
       if (lex == MY_XML_CDATA)
       {
         a.beg+= 9;
         a.end-= 3;
         my_xml_value(p, a.beg, (size_t) (a.end-a.beg));
         continue;
       }
       lex=my_xml_scan(p,&a);
       if (MY_XML_SLASH == lex)
       {
         if (MY_XML_IDENT != (lex=my_xml_scan(p,&a)))
         {
           sprintf(p->errstr,"%s unexpected (ident wanted)",lex2str(lex));
           return MY_XML_ERROR;
         }
         if (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg)))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
         goto gt;
       }
       if (MY_XML_EXCLAM == lex)
       {
         lex=my_xml_scan(p,&a);
         exclam=1;
       }
       else if (MY_XML_QUESTION == lex)
       {
         lex=my_xml_scan(p,&a);
         question=1;
       }
       if (MY_XML_IDENT == lex)
       {
         p->current_node_type= MY_XML_NODE_TAG;
         if (MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg)))
           return MY_XML_ERROR;
       }
       else
       {
         sprintf(p->errstr,"%s unexpected (ident or '/' wanted)",
         lex2str(lex));
         return MY_XML_ERROR;
       }
       while ((MY_XML_IDENT == (lex=my_xml_scan(p,&a))) ||
              ((MY_XML_STRING == lex && exclam)))
       {
         MY_XML_ATTR b;
         if (MY_XML_EQ == (lex=my_xml_scan(p,&b)))
         {
           lex=my_xml_scan(p,&b);
           if ( (lex == MY_XML_IDENT) || (lex == MY_XML_STRING) )
           {
             p->current_node_type= MY_XML_NODE_ATTR;
             if ((MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg)))  ||
                 (MY_XML_OK != my_xml_value(p,b.beg,(size_t) (b.end-b.beg)))  ||
                 (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg))))
               return MY_XML_ERROR;
           }
           else
           {
             sprintf(p->errstr,"%s unexpected (ident or string wanted)",
             lex2str(lex));
             return MY_XML_ERROR;
           }
         }
         else if (MY_XML_IDENT == lex)
         {
           p->current_node_type= MY_XML_NODE_ATTR;
           if ((MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg))) ||
               (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg))))
            return MY_XML_ERROR;
         }
         else if ((MY_XML_STRING == lex) && exclam)
         {
           /*
             We are in <!DOCTYPE>, e.g.
             <!DOCTYPE name SYSTEM "SystemLiteral">
             <!DOCTYPE name PUBLIC "PublidLiteral" "SystemLiteral">
             Just skip "SystemLiteral" and "PublicidLiteral"
           */
         }
         else
           break;
       }
       if (lex == MY_XML_SLASH)
       {
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
       }
 gt:
       if (question)
       {
         if (lex != MY_XML_QUESTION)
         {
           sprintf(p->errstr,"%s unexpected ('?' wanted)",lex2str(lex));
           return MY_XML_ERROR;
         }
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
       }
       if (exclam)
       {
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
       }
       if (lex != MY_XML_GT)
       {
         sprintf(p->errstr,"%s unexpected ('>' wanted)",lex2str(lex));
         return MY_XML_ERROR;
       }
     }
     else
     {
       a.beg=p->cur;
       for ( ; (p->cur < p->end) && (p->cur[0] != '<')  ; p->cur++);
       a.end=p->cur;
       if (!(p->flags & MY_XML_FLAG_SKIP_TEXT_NORMALIZATION))
         my_xml_norm_text(&a);
       if (a.beg != a.end)
       {
         my_xml_value(p,a.beg,(size_t) (a.end-a.beg));
       }
     }
   }
   if (p->attr[0])
   {
     sprintf(p->errstr,"unexpected END-OF-INPUT");
     return MY_XML_ERROR;
   }
   return MY_XML_OK;
 }
References mpq::a, xml_stack_st::attr, xml_stack_st::attrend, b, xml_stack_st::beg, xml_stack_st::cur, xml_stack_st::current_node_type, xml_stack_st::end, xml_stack_st::errstr, xml_stack_st::flags, lex2str(), MY_XML_CDATA, MY_XML_COMMENT, my_xml_enter(), MY_XML_EQ, MY_XML_ERROR, MY_XML_EXCLAM, MY_XML_FLAG_SKIP_TEXT_NORMALIZATION, MY_XML_GT, MY_XML_IDENT, my_xml_leave(), MY_XML_NODE_ATTR, MY_XML_NODE_TAG, my_xml_norm_text(), MY_XML_OK, MY_XML_QUESTION, my_xml_scan(), MY_XML_SLASH, MY_XML_STRING, my_xml_value(), NULL, and sprintf().
Referenced by my_parse_charset_xml().
my_xml_parser_create()
void my_xml_parser_create (MY_XML_PARSER * st)
Definition at line 428 of file xml.c.
 {
   bzero((void*)p,sizeof(p[0]));
 }
References bzero.
Referenced by my_parse_charset_xml().
my_xml_parser_free()
void my_xml_parser_free (MY_XML_PARSER * st)
Referenced by my_parse_charset_xml().
my_xml_set_enter_handler()
void my_xml_set_enter_handler (MY_XML_PARSER * st, int(*)(MY_XML_PARSER *, const char *, size_t len))
Referenced by my_parse_charset_xml().
my_xml_set_leave_handler()
void my_xml_set_leave_handler (MY_XML_PARSER * st, int(*)(MY_XML_PARSER *, const char *, size_t len))
Referenced by my_parse_charset_xml().
my_xml_set_user_data()
void my_xml_set_user_data (MY_XML_PARSER * st, void * user_data)
Definition at line 462 of file xml.c.
 {
   p->user_data=user_data;
 }
References xml_stack_st::user_data.
Referenced by my_parse_charset_xml().
my_xml_set_value_handler()
void my_xml_set_value_handler (MY_XML_PARSER * st, int(*)(MY_XML_PARSER *, const char *, size_t len))
Referenced by my_parse_charset_xml().