Azerotcore-wotlk: Acore Namespace Reference
Acore Namespace Reference
Namespaces
Asio
Banner
ChatCommands
Containers
Crypto
Encoding
Honor
Hyperlinks
Impl
Net
PlayerCommand
SpellScripts
String
XP
Classes
struct unary_function
class Runnable
class Thread
class GeneralLock
class SingleThreaded
class ObjectLevelLockable
class ClassLevelLockable
class CheckedBufferOutputIterator
class IteratorPair
Utility class to enable range for loop syntax for multimap.equal_range uses.
class SignalHandler
Handle termination signals.
class ACLogSink
class AsyncProcessResultImplementation
class AsyncProcessResult
struct has_type
struct has_type< T, std::tuple< Us... > >
struct is_tuple
struct is_tuple< std::tuple< Ts... > >
struct find_type_if
struct find_type_if< Check >
struct find_type_if< Check, T1, Ts... >
struct dependant_false
class BattlegroundChatBuilder
class Battleground2ChatBuilder
class ThreatOrderPred
class ObjectDistanceOrderPred
class PowerPctOrderPred
class HealthPctOrderPred
struct VisibleNotifier
struct VisibleChangesNotifier
struct PlayerRelocationNotifier
struct CreatureRelocationNotifier
struct AIRelocationNotifier
struct MessageDistDeliverer
struct MessageDistDelivererToHostile
struct ObjectUpdater
struct WorldObjectSearcher
struct WorldObjectLastSearcher
struct WorldObjectListSearcher
struct WorldObjectWorker
struct GameObjectSearcher
struct GameObjectLastSearcher
struct GameObjectListSearcher
struct GameObjectWorker
struct UnitSearcher
struct UnitLastSearcher
struct UnitListSearcher
struct CreatureSearcher
struct CreatureLastSearcher
struct CreatureListSearcher
struct CreatureWorker
struct PlayerSearcher
struct PlayerListSearcher
struct PlayerListSearcherWithSharedVision
struct PlayerLastSearcher
struct PlayerWorker
struct PlayerDistWorker
class AnyDeadUnitObjectInRangeCheck
class AnyDeadUnitSpellTargetInRangeCheck
class RespawnDo
class GameObjectFocusCheck
class NearestGameObjectFishingHole
class NearestGameObjectCheck
class NearestGameObjectEntryInObjectRangeCheck
class NearestGameObjectTypeInObjectRangeCheck
class MostHPMissingInRange
class FriendlyCCedInRange
class FriendlyMissingBuffInRange
class AnyUnfriendlyUnitInObjectRangeCheck
class AnyUnfriendlyNoTotemUnitInObjectRangeCheck
class AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck
class AnyFriendlyUnitInObjectRangeCheck
class AnyFriendlyNotSelfUnitInObjectRangeCheck
class AnyGroupedUnitInObjectRangeCheck
class AnyUnitInObjectRangeCheck
class NearestAttackableUnitInObjectRangeCheck
class AnyAoETargetUnitInObjectRangeCheck
class AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck
class CallOfHelpCreatureInRangeDo
struct AnyDeadUnitCheck
class NearestHostileUnitCheck
class NearestHostileUnitInAttackDistanceCheck
class NearestVisibleDetectableContestedGuardUnitCheck
class AnyAssistCreatureInRangeCheck
class NearestAssistCreatureInCreatureRangeCheck
class NearestCreatureEntryWithLiveStateInObjectRangeCheck
class AnyPlayerInObjectRangeCheck
class AnyPlayerExactPositionInGameObjectRangeCheck
class NearestPlayerInObjectRangeCheck
class AllFriendlyCreaturesInGrid
class AllGameObjectsWithEntryInRange
class AllCreaturesOfEntryInRange
class MostHPMissingGroupInRange
class AllDeadCreaturesInRange
class PlayerAtMinimumRangeAway
class GameObjectInRangeCheck
class AllWorldObjectsInRange
class ObjectTypeIdCheck
class ObjectGUIDCheck
class UnitAuraCheck
class AllWorldObjectsInExactRange
class RandomCheck
class PowerCheck
class RaidCheck
class LocalizedPacketDo
class LocalizedPacketListDo
class EmoteChatBuilder
class AbsorbAuraOrderPred
struct WorldObjectSpellTargetCheck
struct WorldObjectSpellNearbyTargetCheck
struct WorldObjectSpellAreaTargetCheck
struct WorldObjectSpellConeTargetCheck
struct WorldObjectSpellTrajTargetCheck
class BroadcastTextBuilder
class CustomChatTextBuilder
class AcoreStringChatBuilder
class WorldWorldTextBuilder
Typedefs
template<template< typename... > typename Check, typename... Ts>
using find_type_if_t = typename find_type_if< Check, Ts... >::type
Enumerations
enum Priority {
Priority_Idle , Priority_Lowest , Priority_Low , Priority_Normal ,
Priority_High , Priority_Highest , Priority_Realtime
}
Functions
void Assert (char const *file, int line, char const *function, std::string const &debugInfo, char const *message)
void Assert (char const *file, int line, char const *function, std::string const &debugInfo, char const *message, char const *format,...)
void Fatal (char const *file, int line, char const *function, char const *message,...)
void Error (char const *file, int line, char const *function, char const *message)
void Warning (char const *file, int line, char const *function, char const *message)
void Abort (char const *file, int line, char const *function)
void Abort (char const *file, int line, char const *function, char const *message,...)
void AbortHandler (int sigval)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Insert (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Insert (ContainerUnorderedMap< TypeNull, KEY_TYPE > &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class T >
bool Insert (ContainerUnorderedMap< T, KEY_TYPE > &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T >
bool Insert (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE , class KEY_TYPE >
SPECIFIC_TYPE * Find (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > const &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE >
SPECIFIC_TYPE * Find (ContainerUnorderedMap< TypeNull, KEY_TYPE > const &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class T >
SPECIFIC_TYPE * Find (ContainerUnorderedMap< T, KEY_TYPE > const &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T >
SPECIFIC_TYPE * Find (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > const &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Remove (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Remove (ContainerUnorderedMap< TypeNull, KEY_TYPE > &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class T >
bool Remove (ContainerUnorderedMap< T, KEY_TYPE > &, KEY_TYPE const &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T >
bool Remove (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &elements, KEY_TYPE const &handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Size (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > const &elements, std::size_t *size, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE >
bool Size (ContainerUnorderedMap< TypeNull, KEY_TYPE > const &, std::size_t *, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class T >
bool Size (ContainerUnorderedMap< T, KEY_TYPE > const &, std::size_t *, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T >
bool Size (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > const &elements, std::size_t *size, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
size_t Count (const ContainerMapList< SPECIFIC_TYPE > &elements, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
size_t Count (const ContainerMapList< TypeNull > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
size_t Count (const ContainerMapList< T > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
size_t Count (const ContainerMapList< TypeList< SPECIFIC_TYPE, T >> &elements, SPECIFIC_TYPE *fake)
template<class SPECIFIC_TYPE , class H , class T >
size_t Count (const ContainerMapList< TypeList< H, T >> &elements, SPECIFIC_TYPE *fake)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Insert (ContainerMapList< SPECIFIC_TYPE > &elements, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Insert (ContainerMapList< TypeNull > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
SPECIFIC_TYPE * Insert (ContainerMapList< T > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class H , class T >
SPECIFIC_TYPE * Insert (ContainerMapList< TypeList< H, T >> &elements, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
CountedPtr< SPECIFIC_TYPE > & Find (ContainerMapList< SPECIFIC_TYPE > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE >
CountedPtr< SPECIFIC_TYPE > & Find (ContainerMapList< TypeNull > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE , class T >
CountedPtr< SPECIFIC_TYPE > & Find (ContainerMapList< T > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE , class H , class T >
CountedPtr< SPECIFIC_TYPE > & Find (ContainerMapList< TypeList< H, T >> &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *fake)
template<class SPECIFIC_TYPE >
const CountedPtr< SPECIFIC_TYPE > & Find (const ContainerMapList< SPECIFIC_TYPE > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE >
const CountedPtr< SPECIFIC_TYPE > & Find (const ContainerMapList< TypeNull > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE , class T >
const CountedPtr< SPECIFIC_TYPE > & Find (const ContainerMapList< T > &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
template<class SPECIFIC_TYPE , class H , class T >
CountedPtr< SPECIFIC_TYPE > & Find (const ContainerMapList< TypeList< H, T >> &elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *fake)
template<class SPECIFIC_TYPE >
CountedPtr< SPECIFIC_TYPE > & Insert (ContainerMapList< SPECIFIC_TYPE > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE >
CountedPtr< SPECIFIC_TYPE > & Insert (ContainerMapList< TypeNull > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE , class T >
CountedPtr< SPECIFIC_TYPE > & Insert (ContainerMapList< T > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE , class H , class T >
CountedPtr< SPECIFIC_TYPE > & Insert (ContainerMapList< TypeList< H, T >> &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE >
bool Remove (ContainerMapList< SPECIFIC_TYPE > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE >
bool Remove (ContainerMapList< TypeNull > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE , class T >
bool Remove (ContainerMapList< T > &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class SPECIFIC_TYPE , class T , class H >
bool Remove (ContainerMapList< TypeList< H, T >> &elements, CountedPtr< SPECIFIC_TYPE > &obj, OBJECT_HANDLE hdl)
template<class T >
constexpr T * AddressOrSelf (T *ptr)
template<class T >
constexpr T * AddressOrSelf (T &not_ptr)
template<typename T >
auto MakeACLogSink (T &&callback) -> ACLogSink< typename std::decay< T >::type >
template<typename T >
static int CreateChildProcess (T waiter, std::string const &executable, std::vector< std::string > const &argsVector, std::string const &logger, std::string const &input, bool secure)
int StartProcess (std::string const &executable, std::vector< std::string > const &args, std::string const &logger, std::string input_file, bool secure)
std::shared_ptr< AsyncProcessResult > StartAsyncProcess (std::string executable, std::vector< std::string > args, std::string logger, std::string input_file, bool secure)
std::string SearchExecutableInPath (std::string const &filename)
template<typename Result , typename... Params>
Optional< Result > StringTo (std::string_view str, Params &&... params)
template<typename Type , typename... Params>
std::string ToString (Type &&val, Params &&... params)
template<typename Format , typename... Args>
std::string StringFormat (Format &&fmt, Args &&... args)
Default AC string format function.
template<typename... Args>
std::string StringFormatFmt (std::string_view fmt, Args &&... args)
bool IsFormatEmptyOrNull (char const *fmt)
Returns true if the given char pointer is null.
bool IsFormatEmptyOrNull (std::string_view fmt)
Returns true if the given std::string is empty.
std::vector< std::string_view > Tokenize (std::string_view str, char sep, bool keepEmpty)
std::vector< std::string_view > Tokenize (std::string &&, char, bool)=delete
std::vector< std::string_view > Tokenize (std::string const &&, char, bool)=delete
std::vector< std::string_view > Tokenize (char const *str, char sep, bool keepEmpty)
template<class T , class Tuple >
T * new_from_tuple (Tuple &&args)
template<class RET_TYPE , int CENTER_VAL>
RET_TYPE Compute (float x, float y, float center_offset, float size)
GridCoord ComputeGridCoord (float x, float y)
CellCoord ComputeCellCoord (float x, float y)
CellCoord ComputeCellCoord (float x, float y, float &x_off, float &y_off)
void NormalizeMapCoord (float &c)
bool IsValidMapCoord (float c)
bool IsValidMapCoord (float x, float y)
bool IsValidMapCoord (float x, float y, float z)
bool IsValidMapCoord (float x, float y, float z, float o)
Variables
template<typename T , typename... Us>
constexpr bool has_type_v = has_type<T, Us...>::value
template<typename... Ts>
constexpr bool is_tuple_v = is_tuple<Ts...>::value
template<typename T >
constexpr bool dependant_false_v = dependant_false<T>::value
Typedef Documentation
find_type_if_t
template<template< typename... > typename Check, typename... Ts> using Acore::find_type_if_t = typedef typename find_type_if<Check, Ts...>::type
Definition at line 66 of file Types.h.
Enumeration Type Documentation
Priority
enum Acore::Priority
Enumerator
Priority_Idle
Priority_Lowest
Priority_Low
Priority_Normal
Priority_High
Priority_Highest
Priority_Realtime
Definition at line 44 of file Threading.h.
     {
         Priority_Idle,
         Priority_Lowest,
         Priority_Low,
         Priority_Normal,
         Priority_High,
         Priority_Highest,
         Priority_Realtime,
     };
Function Documentation
Abort() [1/2]
void Acore::Abort (char const * file, int line, char const * function)
Definition at line 110 of file Errors.cpp.
     {
         std::string formattedMessage = Acore::StringFormat("\n%s:%i in %s ABORTED.\n", file, line, function);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, fprintf(), and StringFormat().
Abort() [2/2]
void Acore::Abort (char const * file, int line, char const * function, char const * message, ...)
Definition at line 118 of file Errors.cpp.
     {
         va_list args;
         va_start(args, message);
         std::string formattedMessage = StringFormat("\n%s:%i in %s ABORTED:\n", file, line, function) + FormatAssertionMessage(message, args) + '\n';
         va_end(args);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, anonymous_namespace{Errors.cpp}::FormatAssertionMessage(), fprintf(), message(), and StringFormat().
AbortHandler()
void Acore::AbortHandler (int sigval)
Definition at line 132 of file Errors.cpp.
     {
         // nothing useful to log here, no way to pass args
         std::string formattedMessage = Acore::StringFormat("Caught signal %i\n", sigval);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, fprintf(), and StringFormat().
Referenced by main().
AddressOrSelf() [1/2]
template<class T > constexpr T* Acore::AddressOrSelf (T & not_ptr) inline constexpr
Definition at line 39 of file Containers.h.
     {
         return std::addressof(not_ptr);
     }
AddressOrSelf() [2/2]
template<class T > constexpr T* Acore::AddressOrSelf (T * ptr) inline constexpr
Definition at line 33 of file Containers.h.
     {
         return ptr;
     }
References ptr().
Referenced by Acore::Containers::MapGetValuePtr().
Assert() [1/2]
void Acore::Assert (char const * file, int line, char const * function, std::string const & debugInfo, char const * message)
Definition at line 59 of file Errors.cpp.
     {
         std::string formattedMessage = Acore::StringFormat("\n%s:%i in %s ASSERTION FAILED:\n  %s\n", file, line, function, message) + debugInfo + '\n';
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, fprintf(), message(), and StringFormat().
Assert() [2/2]
void Acore::Assert (char const * file, int line, char const * function, std::string const & debugInfo, char const * message, char const * format, ...)
Definition at line 67 of file Errors.cpp.
     {
         va_list args;
         va_start(args, format);
         std::string formattedMessage = Acore::StringFormat("\n%s:%i in %s ASSERTION FAILED:\n  %s\n", file, line, function, message) + FormatAssertionMessage(format, args) + '\n' + debugInfo + '\n';
         va_end(args);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, format(), anonymous_namespace{Errors.cpp}::FormatAssertionMessage(), fprintf(), message(), and StringFormat().
Compute()
template<class RET_TYPE , int CENTER_VAL> RET_TYPE Acore::Compute (float x, float y, float center_offset, float size) inline
Definition at line 175 of file GridDefines.h.
     {
         // calculate and store temporary values in double format for having same result as same mySQL calculations
         double x_offset = (double(x) - center_offset) / size;
         double y_offset = (double(y) - center_offset) / size;
         int x_val = int(x_offset + CENTER_VAL + 0.5f);
         int y_val = int(y_offset + CENTER_VAL + 0.5f);
         return RET_TYPE(x_val, y_val);
     }
References G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::average(), G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::bilinear(), G3D::Map2D< Storage, Compute >::Map2D(), and G3D::Map2D< Storage, Compute >::nearest().
ComputeCellCoord() [1/2]
CellCoord Acore::ComputeCellCoord (float x, float y) inline
Definition at line 191 of file GridDefines.h.
     {
         return Compute<CellCoord, CENTER_GRID_CELL_ID>(x, y, CENTER_GRID_CELL_OFFSET, SIZE_OF_GRID_CELL);
     }
References CENTER_GRID_CELL_OFFSET, SIZE_OF_GRID_CELL, G3D::x, and G3D::y.
Referenced by ObjectMgr::AddCreatureToGrid(), ObjectMgr::AddGameobjectToGrid(), Map::AddPlayerToMap(), Map::AddToMap(), Cell::CalculateCellArea(), Cell::Cell(), Spell::CheckSpellFocus(), Corpse::Create(), WorldObject::GetCreaturesWithEntryInRange(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveWorldportAck(), misc_commandscript::HandleRespawnCommand(), WorldSession::HandleTextEmoteOpcode(), Corpse::LoadCorpseFromDB(), ObjectMgr::RemoveCreatureFromGrid(), ObjectMgr::RemoveGameobjectFromGrid(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), Spell::SearchTargets(), AchievementMgr::SendAchievementEarned(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), Map::SwitchGridContainers(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
ComputeCellCoord() [2/2]
CellCoord Acore::ComputeCellCoord (float x, float y, float & x_off, float & y_off) inline
Definition at line 196 of file GridDefines.h.
     {
         double x_offset = (double(x) - CENTER_GRID_CELL_OFFSET) / SIZE_OF_GRID_CELL;
         double y_offset = (double(y) - CENTER_GRID_CELL_OFFSET) / SIZE_OF_GRID_CELL;
         int x_val = int(x_offset + CENTER_GRID_CELL_ID + 0.5f);
         int y_val = int(y_offset + CENTER_GRID_CELL_ID + 0.5f);
         x_off = (float(x_offset) - x_val + CENTER_GRID_CELL_ID) * SIZE_OF_GRID_CELL;
         y_off = (float(y_offset) - y_val + CENTER_GRID_CELL_ID) * SIZE_OF_GRID_CELL;
         return CellCoord(x_val, y_val);
     }
References CENTER_GRID_CELL_ID, CENTER_GRID_CELL_OFFSET, SIZE_OF_GRID_CELL, G3D::x, and G3D::y.
ComputeGridCoord()
GridCoord Acore::ComputeGridCoord (float x, float y) inline
Definition at line 186 of file GridDefines.h.
     {
         return Compute<GridCoord, CENTER_GRID_ID>(x, y, CENTER_GRID_OFFSET, SIZE_OF_GRIDS);
     }
References CENTER_GRID_OFFSET, SIZE_OF_GRIDS, G3D::x, and G3D::y.
Referenced by MapMgr::ExistMapAndVMap(), misc_commandscript::HandleGPSCommand(), Map::IsGridLoaded(), and Map::IsRemovalGrid().
Count() [1/5]
template<class SPECIFIC_TYPE > size_t Acore::Count (const ContainerMapList< SPECIFIC_TYPE > & elements, SPECIFIC_TYPE *)
Definition at line 162 of file TypeContainerFunctions.h.
     {
         return elements._element.getSize();
     }
References ContainerMapList< OBJECT >::_element.
Referenced by _my_b_read(), _my_b_read_r(), _my_b_seq_read(), _my_b_write(), TypeMapContainer< OBJECT_TYPES >::Count(), Count(), WheatyExceptionReport::DumpTypeIndex(), Graveyard::LoadGraveyardFromDB(), my_b_append(), my_b_safe_write(), my_block_write(), my_copy(), my_fread(), my_fwrite(), my_pread(), my_pwrite(), my_quick_read(), my_quick_write(), my_read(), my_write(), and hyjalAI::SummonNextWave().
Count() [2/5]
template<class SPECIFIC_TYPE , class T > size_t Acore::Count (const ContainerMapList< T > & , SPECIFIC_TYPE *)
Definition at line 174 of file TypeContainerFunctions.h.
     {
         return 0;
     }
Count() [3/5]
template<class SPECIFIC_TYPE , class H , class T > size_t Acore::Count (const ContainerMapList< TypeList< H, T >> & elements, SPECIFIC_TYPE * fake)
Definition at line 186 of file TypeContainerFunctions.h.
     {
         return Count(elements._TailElements, fake);
     }
References Count().
Count() [4/5]
template<class SPECIFIC_TYPE , class T > size_t Acore::Count (const ContainerMapList< TypeList< SPECIFIC_TYPE, T >> & elements, SPECIFIC_TYPE * fake)
Definition at line 180 of file TypeContainerFunctions.h.
     {
         return Count(elements._elements, fake);
     }
References Count().
Count() [5/5]
template<class SPECIFIC_TYPE > size_t Acore::Count (const ContainerMapList< TypeNull > & , SPECIFIC_TYPE *)
Definition at line 168 of file TypeContainerFunctions.h.
     {
         return 0;
     }
CreateChildProcess()
template<typename T > static int Acore::CreateChildProcess (T waiter, std::string const & executable, std::vector< std::string > const & argsVector, std::string const & logger, std::string const & input, bool secure) static
Definition at line 70 of file StartProcess.cpp.
     {
         ipstream outStream;
         ipstream errStream;
         if (!secure)
         {
             LOG_TRACE(logger, "Starting process \"%s\" with arguments: \"%s\".",
                 executable.c_str(), boost::algorithm::join(argsVector, " ").c_str());
         }
         // prepare file with only read permission (boost process opens with read_write)
         std::shared_ptr<FILE> inputFile(!input.empty() ? fopen(input.c_str(), "rb") : nullptr, [](FILE* ptr)
         {
             if (ptr != nullptr)
                 fclose(ptr);
         });
         // Start the child process
         child c = [&]()
         {
             if (inputFile)
             {
                 // With binding stdin
                 return child{
                     exe = std::filesystem::absolute(executable).string(),
                     args = argsVector,
                     env = environment(boost::this_process::environment()),
                     std_in = inputFile.get(),
                     std_out = outStream,
                     std_err = errStream
                 };
             }
             else
             {
                 // Without binding stdin
                 return child{
                     exe = std::filesystem::absolute(executable).string(),
                     args = argsVector,
                     env = environment(boost::this_process::environment()),
                     std_in = boost::process::close,
                     std_out = outStream,
                     std_err = errStream
                 };
             }
         }();
         auto outInfo = MakeACLogSink([&](std::string const& msg)
         {
             LOG_INFO(logger, "%s", msg.c_str());
         });
         auto outError = MakeACLogSink([&](std::string const& msg)
         {
             LOG_ERROR(logger, "%s", msg.c_str());
         });
         copy(outStream, outInfo);
         copy(errStream, outError);
         // Call the waiter in the current scope to prevent
         // the streams from closing too early on leaving the scope.
         int const result = waiter(c);
         if (!secure)
         {
             LOG_TRACE(logger, ">> Process \"%s\" finished with return value %i.",
                 executable.c_str(), result);
         }
         return result;
     }
References mpq::c, close, detail::copy(), join(), LOG_ERROR, LOG_INFO, LOG_TRACE, MakeACLogSink(), and ptr().
Referenced by Acore::AsyncProcessResultImplementation::StartProcess(), and StartProcess().
Error()
void void void Acore::Error (char const * file, int line, char const * function, char const * message)
Definition at line 96 of file Errors.cpp.
     {
         std::string formattedMessage = Acore::StringFormat("\n%s:%i in %s ERROR:\n  %s\n", file, line, function, message);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, fprintf(), message(), and StringFormat().
Referenced by G3D::GImage::decodeBMP(), G3D::GImage::decodeICO(), G3D::GImage::decodeJPEG(), G3D::GImage::decodePCX(), G3D::GImage::decodePNG(), G3D::GImage::decodePPM(), G3D::GImage::decodePPMASCII(), G3D::GImage::decodeTGA(), G3D::GImage::encodePNG(), G3D::GImage::load(), G3D::png_error(), and G3D::GImage::resolveFormat().
Fatal()
void void Acore::Fatal (char const * file, int line, char const * function, char const * message, ...)
Definition at line 81 of file Errors.cpp.
     {
         va_list args;
         va_start(args, message);
         std::string formattedMessage = Acore::StringFormat("\n%s:%i in %s FATAL ERROR:\n", file, line, function) + FormatAssertionMessage(message, args) + '\n';
         va_end(args);
         fprintf(stderr, "%s", formattedMessage.c_str());
         fflush(stderr);
         std::this_thread::sleep_for(std::chrono::seconds(10));
         Crash(formattedMessage.c_str());
     }
References Crash, mpq::file, anonymous_namespace{Errors.cpp}::FormatAssertionMessage(), fprintf(), message(), G3D::units::seconds(), and StringFormat().
Find() [1/12]
template<class SPECIFIC_TYPE > const CountedPtr<SPECIFIC_TYPE>& Acore::Find (const ContainerMapList< SPECIFIC_TYPE > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 84 of file TypeContainerFunctionsPtr.h.
     {
         typename CountedPtr<SPECIFIC_TYPE>::iterator iter = elements._element.find(hdl);
         return (iter == elements._element.end() ? NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr) : iter->second);
     };
References ContainerMapList< OBJECT >::_element.
Find() [2/12]
template<class SPECIFIC_TYPE , class T > const CountedPtr<SPECIFIC_TYPE>& Acore::Find (const ContainerMapList< T > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 95 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);
     }
Find() [3/12]
template<class SPECIFIC_TYPE , class H , class T > CountedPtr<SPECIFIC_TYPE>& Acore::Find (const ContainerMapList< TypeList< H, T >> & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > * fake)
Definition at line 100 of file TypeContainerFunctionsPtr.h.
     {
         CountedPtr<SPECIFIC_TYPE>& t = Find(elements._elements, hdl, fake);
         if (!t)
         {
             t = Find(elements._TailElement, hdl, fake);
         }
         return t;
     }
References Find().
Find() [4/12]
template<class SPECIFIC_TYPE > const CountedPtr<SPECIFIC_TYPE>& Acore::Find (const ContainerMapList< TypeNull > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 90 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);
     }
Find() [5/12]
template<class SPECIFIC_TYPE > CountedPtr<SPECIFIC_TYPE>& Acore::Find (ContainerMapList< SPECIFIC_TYPE > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 61 of file TypeContainerFunctionsPtr.h.
     {
         typename std::map<OBJECT_HANDLE, CountedPtr<SPECIFIC_TYPE>>::iterator iter = elements._element.find(hdl);
         return (iter == elements._element.end() ? NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr) : iter->second);
     };
References ContainerMapList< OBJECT >::_element.
Find() [6/12]
template<class SPECIFIC_TYPE , class T > CountedPtr<SPECIFIC_TYPE>& Acore::Find (ContainerMapList< T > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 72 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);// this is a missed
     }
Find() [7/12]
template<class SPECIFIC_TYPE , class H , class T > CountedPtr<SPECIFIC_TYPE>& Acore::Find (ContainerMapList< TypeList< H, T >> & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > * fake)
Definition at line 77 of file TypeContainerFunctionsPtr.h.
     {
         CountedPtr<SPECIFIC_TYPE>& t = Find(elements._elements, hdl, fake);
         return (!t ? Find(elements._TailElements, hdl, fake) : t);
     }
References Find().
Find() [8/12]
template<class SPECIFIC_TYPE > CountedPtr<SPECIFIC_TYPE>& Acore::Find (ContainerMapList< TypeNull > & elements, OBJECT_HANDLE hdl, CountedPtr< SPECIFIC_TYPE > *)
Definition at line 67 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);// terminate recursion
     }
Find() [9/12]
template<class SPECIFIC_TYPE , class KEY_TYPE > SPECIFIC_TYPE* Acore::Find (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > const & elements, KEY_TYPE const & handle, SPECIFIC_TYPE *)
Definition at line 73 of file TypeContainerFunctions.h.
     {
         auto i = elements._element.find(handle);
         if (i == elements._element.end())
         {
             return nullptr;
         }
         else
         {
             return i->second;
         }
     }
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
Referenced by Find(), and TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Find().
Find() [10/12]
template<class SPECIFIC_TYPE , class KEY_TYPE , class T > SPECIFIC_TYPE* Acore::Find (ContainerUnorderedMap< T, KEY_TYPE > const & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 93 of file TypeContainerFunctions.h.
     {
         return nullptr;
     }
Find() [11/12]
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T > SPECIFIC_TYPE* Acore::Find (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > const & elements, KEY_TYPE const & handle, SPECIFIC_TYPE *)
Definition at line 99 of file TypeContainerFunctions.h.
     {
         SPECIFIC_TYPE* ret = Find(elements._elements, handle, (SPECIFIC_TYPE*)nullptr);
         return ret ? ret : Find(elements._TailElements, handle, (SPECIFIC_TYPE*)nullptr);
     }
References Find(), and ret.
Find() [12/12]
template<class SPECIFIC_TYPE , class KEY_TYPE > SPECIFIC_TYPE* Acore::Find (ContainerUnorderedMap< TypeNull, KEY_TYPE > const & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 87 of file TypeContainerFunctions.h.
     {
         return nullptr;
     }
Insert() [1/12]
template<class SPECIFIC_TYPE > CountedPtr<SPECIFIC_TYPE>& Acore::Insert (ContainerMapList< SPECIFIC_TYPE > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 112 of file TypeContainerFunctionsPtr.h.
     {
         elements._element[hdl] = obj;
         return obj;
     };
References ContainerMapList< OBJECT >::_element.
Insert() [2/12]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* Acore::Insert (ContainerMapList< SPECIFIC_TYPE > & elements, SPECIFIC_TYPE * obj)
Definition at line 193 of file TypeContainerFunctions.h.
     {
         //elements._element[hdl] = obj;
         obj->AddToGrid(elements._element);
         return obj;
     }
References ContainerMapList< OBJECT >::_element.
Insert() [3/12]
template<class SPECIFIC_TYPE , class T > SPECIFIC_TYPE* Acore::Insert (ContainerMapList< T > & , SPECIFIC_TYPE *)
Definition at line 208 of file TypeContainerFunctions.h.
     {
         return nullptr;                                        // a missed
     }
Insert() [4/12]
template<class SPECIFIC_TYPE , class T > CountedPtr<SPECIFIC_TYPE>& Acore::Insert (ContainerMapList< T > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 124 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);// a missed
     }
Insert() [5/12]
template<class SPECIFIC_TYPE , class H , class T > CountedPtr<SPECIFIC_TYPE>& Acore::Insert (ContainerMapList< TypeList< H, T >> & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 130 of file TypeContainerFunctionsPtr.h.
     {
         CountedPtr<SPECIFIC_TYPE>& t = Insert(elements._elements, obj, hdl);
         return (!t ? Insert(elements._TailElements, obj, hdl) : t);
     }
References Insert().
Insert() [6/12]
template<class SPECIFIC_TYPE , class H , class T > SPECIFIC_TYPE* Acore::Insert (ContainerMapList< TypeList< H, T >> & elements, SPECIFIC_TYPE * obj)
Definition at line 215 of file TypeContainerFunctions.h.
     {
         SPECIFIC_TYPE* t = Insert(elements._elements, obj);
         return (t != nullptr ? t : Insert(elements._TailElements, obj));
     }
References Insert().
Insert() [7/12]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* Acore::Insert (ContainerMapList< TypeNull > & , SPECIFIC_TYPE *)
Definition at line 201 of file TypeContainerFunctions.h.
     {
         return nullptr;
     }
Insert() [8/12]
template<class SPECIFIC_TYPE > CountedPtr<SPECIFIC_TYPE>& Acore::Insert (ContainerMapList< TypeNull > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 118 of file TypeContainerFunctionsPtr.h.
     {
         return NullPtr<SPECIFIC_TYPE>((SPECIFIC_TYPE*)nullptr);
     }
Insert() [9/12]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Insert (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > & elements, KEY_TYPE const & handle, SPECIFIC_TYPE * obj)
Definition at line 37 of file TypeContainerFunctions.h.
     {
         auto i = elements._element.find(handle);
         if (i == elements._element.end())
         {
             elements._element[handle] = obj;
             return true;
         }
         else
         {
             ASSERT(i->second == obj, "Object with certain key already in but objects are different!");
             return false;
         }
     }
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element, and ASSERT.
Referenced by Insert(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), and TypeMapContainer< OBJECT_TYPES >::insert().
Insert() [10/12]
template<class SPECIFIC_TYPE , class KEY_TYPE , class T > bool Acore::Insert (ContainerUnorderedMap< T, KEY_TYPE > & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 59 of file TypeContainerFunctions.h.
     {
         return false;
     }
Insert() [11/12]
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T > bool Acore::Insert (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & elements, KEY_TYPE const & handle, SPECIFIC_TYPE * obj)
Definition at line 65 of file TypeContainerFunctions.h.
     {
         bool ret = Insert(elements._elements, handle, obj);
         return ret ? ret : Insert(elements._TailElements, handle, obj);
     }
References Insert(), and ret.
Insert() [12/12]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Insert (ContainerUnorderedMap< TypeNull, KEY_TYPE > & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 53 of file TypeContainerFunctions.h.
     {
         return false;
     }
IsFormatEmptyOrNull() [1/2]
bool Acore::IsFormatEmptyOrNull (char const * fmt) inline
Returns true if the given char pointer is null.
Definition at line 46 of file StringFormat.h.
     {
         return fmt == nullptr;
     }
References fmt.
Referenced by DatabaseWorkerPool< T >::DirectExecute(), DatabaseWorkerPool< T >::DirectPExecute(), DatabaseWorkerPool< T >::Execute(), DatabaseWorkerPool< T >::PExecute(), and DatabaseWorkerPool< T >::PQuery().
IsFormatEmptyOrNull() [2/2]
bool Acore::IsFormatEmptyOrNull (std::string_view fmt) inline
Returns true if the given std::string is empty.
Definition at line 52 of file StringFormat.h.
     {
         return fmt.empty();
     }
References fmt.
IsValidMapCoord() [1/4]
bool Acore::IsValidMapCoord (float c) inline
Definition at line 216 of file GridDefines.h.
     {
         return std::isfinite(c) && (std::fabs(c) <= MAP_HALFSIZE - 0.5f);
     }
References mpq::c, isfinite(), and MAP_HALFSIZE.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), PathGenerator::CalculatePath(), Map::CheckCollisionAndGetValidCoords(), Spell::EffectJumpDest(), WorldSession::HandleMovementOpcodes(), SmartAIMgr::IsEventValid(), Position::IsPositionValid(), IsValidMapCoord(), MapMgr::IsValidMapCoord(), Creature::LoadCreatureFromDB(), Player::LoadFromDB(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadScripts(), WorldObject::MovePosition(), StaticTransport::RelocateToProgress(), Creature::SetPosition(), GameObject::SetPosition(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), and Unit::UpdatePosition().
IsValidMapCoord() [2/4]
bool Acore::IsValidMapCoord (float x, float y) inline
Definition at line 221 of file GridDefines.h.
     {
         return IsValidMapCoord(x) && IsValidMapCoord(y);
     }
References IsValidMapCoord(), G3D::x, and G3D::y.
IsValidMapCoord() [3/4]
bool Acore::IsValidMapCoord (float x, float y, float z) inline
Definition at line 226 of file GridDefines.h.
     {
         return IsValidMapCoord(x, y) && IsValidMapCoord(z);
     }
References IsValidMapCoord(), G3D::x, G3D::y, and G3D::z.
IsValidMapCoord() [4/4]
bool Acore::IsValidMapCoord (float x, float y, float z, float o) inline
Definition at line 231 of file GridDefines.h.
     {
         return IsValidMapCoord(x, y, z) && std::isfinite(o);
     }
References isfinite(), IsValidMapCoord(), G3D::x, G3D::y, and G3D::z.
MakeACLogSink()
template<typename T > auto Acore::MakeACLogSink (T && callback) -> ACLogSink<typename std::decay<T>::type>
Definition at line 63 of file StartProcess.cpp.
     {
         return { std::forward<T>(callback) };
     }
Referenced by CreateChildProcess().
new_from_tuple()
template<class T , class Tuple > T* Acore::new_from_tuple (Tuple && args)
Definition at line 59 of file Tuples.h.
     {
         return Impl::new_from_tuple<T>(std::forward<Tuple>(args), std::make_index_sequence<std::tuple_size_v<std::remove_reference_t<Tuple>>>{});
     }
NormalizeMapCoord()
void Acore::NormalizeMapCoord (float & c) inline
Definition at line 208 of file GridDefines.h.
     {
         if (c > MAP_HALFSIZE - 0.5f)
             c = MAP_HALFSIZE - 0.5f;
         else if (c < -(MAP_HALFSIZE - 0.5f))
             c = -(MAP_HALFSIZE - 0.5f);
     }
References mpq::c, and MAP_HALFSIZE.
Referenced by ConfusedMovementGenerator< T >::DoInitialize(), WorldObject::GetNearPoint2D(), WorldObject::GetRandomPoint(), CreatureGroup::LeaderMoveTo(), WaypointMgr::Load(), WorldObject::MovePosition(), and WaypointMgr::ReloadPath().
Remove() [1/8]
template<class SPECIFIC_TYPE > bool Acore::Remove (ContainerMapList< SPECIFIC_TYPE > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 137 of file TypeContainerFunctionsPtr.h.
     {
         typename std::map<OBJECT_HANDLE, CountedPtr<SPECIFIC_TYPE>>::iterator iter = elements._element.find(hdl);
         if ( iter != elements._element.end() )
         {
             elements._element.erase(iter);
             return true;
         }
         return false;                                       // found... terminate the search
     }
References ContainerMapList< OBJECT >::_element.
Remove() [2/8]
template<class SPECIFIC_TYPE , class T > bool Acore::Remove (ContainerMapList< T > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 155 of file TypeContainerFunctionsPtr.h.
     {
         return false;
     }
Remove() [3/8]
template<class SPECIFIC_TYPE , class T , class H > bool Acore::Remove (ContainerMapList< TypeList< H, T >> & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 160 of file TypeContainerFunctionsPtr.h.
     {
         // The head element is bad
         bool t = Remove(elements._elements, obj, hdl);
         return ( !t ? Remove(elements._TailElements, obj, hdl) : t );
     }
References Remove().
Remove() [4/8]
template<class SPECIFIC_TYPE > bool Acore::Remove (ContainerMapList< TypeNull > & elements, CountedPtr< SPECIFIC_TYPE > & obj, OBJECT_HANDLE hdl)
Definition at line 149 of file TypeContainerFunctionsPtr.h.
     {
         return false;
     }
Remove() [5/8]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Remove (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > & elements, KEY_TYPE const & handle, SPECIFIC_TYPE *)
Definition at line 107 of file TypeContainerFunctions.h.
     {
         elements._element.erase(handle);
         return true;
     }
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
Referenced by Remove(), and TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove().
Remove() [6/8]
template<class SPECIFIC_TYPE , class KEY_TYPE , class T > bool Acore::Remove (ContainerUnorderedMap< T, KEY_TYPE > & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 120 of file TypeContainerFunctions.h.
     {
         return false;
     }
Remove() [7/8]
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T > bool Acore::Remove (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & elements, KEY_TYPE const & handle, SPECIFIC_TYPE *)
Definition at line 126 of file TypeContainerFunctions.h.
     {
         bool ret = Remove(elements._elements, handle, (SPECIFIC_TYPE*)nullptr);
         return ret ? ret : Remove(elements._TailElements, handle, (SPECIFIC_TYPE*)nullptr);
     }
References Remove(), and ret.
Remove() [8/8]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Remove (ContainerUnorderedMap< TypeNull, KEY_TYPE > & , KEY_TYPE const & , SPECIFIC_TYPE *)
Definition at line 114 of file TypeContainerFunctions.h.
     {
         return false;
     }
SearchExecutableInPath()
AC_COMMON_API std::string Acore::SearchExecutableInPath (std::string const & filename)
Searches for the given executable in the PATH variable and returns a non-empty string when it was found.
Definition at line 258 of file StartProcess.cpp.
     {
         try
         {
             return search_path(filename).string();
         }
         catch (...)
         {
             return "";
         }
     }
Referenced by DBUpdaterUtil::CheckExecutable().
Size() [1/4]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Size (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > const & elements, std::size_t * size, SPECIFIC_TYPE *)
Definition at line 134 of file TypeContainerFunctions.h.
     {
         *size = elements._element.size();
         return true;
     }
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
Referenced by ByteBuffer::append(), BigNumber::BigNumber(), detail::fill_n(), HexStrToByteArray(), my_once_alloc(), ByteBuffer::read(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Size(), Size(), and BigNumber::ToByteArray().
Size() [2/4]
template<class SPECIFIC_TYPE , class KEY_TYPE , class T > bool Acore::Size (ContainerUnorderedMap< T, KEY_TYPE > const & , std::size_t * , SPECIFIC_TYPE *)
Definition at line 147 of file TypeContainerFunctions.h.
     {
         return false;
     }
Size() [3/4]
template<class SPECIFIC_TYPE , class KEY_TYPE , class H , class T > bool Acore::Size (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > const & elements, std::size_t * size, SPECIFIC_TYPE *)
Definition at line 153 of file TypeContainerFunctions.h.
     {
         bool ret = Size(elements._elements, size, (SPECIFIC_TYPE*)nullptr);
         return ret ? ret : Size(elements._TailElements, size, (SPECIFIC_TYPE*)nullptr);
     }
References ret, and Size().
Size() [4/4]
template<class SPECIFIC_TYPE , class KEY_TYPE > bool Acore::Size (ContainerUnorderedMap< TypeNull, KEY_TYPE > const & , std::size_t * , SPECIFIC_TYPE *)
Definition at line 141 of file TypeContainerFunctions.h.
     {
         return false;
     }
StartAsyncProcess()
AC_COMMON_API std::shared_ptr< AsyncProcessResult > Acore::StartAsyncProcess (std::string executable, std::vector< std::string > args, std::string logger, std::string input_file = "", bool secure = false)
Starts a process asynchronously with the given arguments and parameters and returns an AsyncProcessResult immediately which is set, when the process exits. When an input path is given, the file will be routed to the processes stdin. When the process is marked as secure no arguments are leaked to logs. Note that most executables expect it's name as the first argument.
Definition at line 248 of file StartProcess.cpp.
     {
         auto handle = std::make_shared<AsyncProcessResultImplementation>(
             std::move(executable), std::move(args), std::move(logger), std::move(input_file), secure);
         handle->SetFuture(std::async(std::launch::async, [handle] { return handle->StartProcess(); }));
         return handle;
     }
StartProcess()
AC_COMMON_API int Acore::StartProcess (std::string const & executable, std::vector< std::string > const & args, std::string const & logger, std::string input_file = "", bool secure = false)
Starts a process with the given arguments and parameters and will block until the process is finished. When an input path is given, the file will be routed to the processes stdin. When the process is marked as secure no arguments are leaked to logs. Note that most executables expect it's name as the first argument.
Definition at line 146 of file StartProcess.cpp.
     {
         return CreateChildProcess([](child& c) -> int
         {
             try
             {
                 c.wait();
                 return c.exit_code();
             }
             catch (...)
             {
                 return EXIT_FAILURE;
             }
         }, executable, args, logger, input_file, secure);
     }
References mpq::c, and CreateChildProcess().
Referenced by DBUpdater< T >::ApplyFile().
StringFormat()
template<typename Format , typename... Args> std::string Acore::StringFormat (Format && fmt, Args &&... args) inline
Default AC string format function.
Definition at line 18 of file StringFormat.h.
     {
         try
         {
             return fmt::sprintf(std::forward<Format>(fmt), std::forward<Args>(args)...);
         }
         catch (const fmt::format_error& formatError)
         {
             std::string error = "An error occurred formatting string \"" + std::string(fmt) + "\" : " + std::string(formatError.what());
             return error;
         }
     }
References error(), fmt, and sprintf().
Referenced by Abort(), AbortHandler(), AppenderFile::AppenderFile(), Warden::ApplyPenalty(), Assert(), SecretMgr::AttemptTransition(), ByteBufferInvalidValueException::ByteBufferInvalidValueException(), DatabaseWorkerPool< T >::DirectPExecute(), Error(), ExtractMapsFromMpq(), Fatal(), Acore::Impl::ChatCommands::FormatAcoreString(), Acore::Impl::ChatCommands::ChatCommandNode::GetAutoCompletionsFor(), Log::GetTimestampStr(), LogMessage::getTimeStr(), message_commandscript::HandleAnnounceCommand(), character_commandscript::HandleCharacterTitlesCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupTitleCommand(), server_commandscript::HandleServerDebugCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), AppenderConsole::InitColors(), DBCDatabaseLoader::Load(), MMAP::MMapMgr::loadMap(), MMAP::MMapMgr::loadMapData(), WardenCheckMgr::LoadWardenChecks(), Log::outBasic(), Log::outCommand(), Log::outDebug(), Log::outDetail(), Log::outError(), Log::outErrorDb(), Log::outMessage(), Log::outMisc(), Log::outSQLDev(), Log::outSQLDriver(), Log::outString(), TransactionBase::PAppend(), anonymous_namespace{Config.cpp}::ParseFile(), DatabaseWorkerPool< T >::PExecute(), ChatHandler::PGetParseString(), DatabaseWorkerPool< T >::PQuery(), anonymous_namespace{Config.cpp}::PrintError(), ChatHandler::PSendSysMessage(), ArenaSpectator::SendCommand(), BattlegroundQueue::SendJoinMessageArenaQueue(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume(), Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >::TryConsumeTo(), DBUpdater< T >::Update(), and Appender::write().
StringFormatFmt()
template<typename... Args> std::string Acore::StringFormatFmt (std::string_view fmt, Args &&... args) inline
Definition at line 33 of file StringFormat.h.
     {
         try
         {
             return fmt::format(fmt, std::forward<Args>(args)...);
         }
         catch (const fmt::format_error& formatError)
         {
             return fmt::format("An error occurred formatting string \"{}\": {}", fmt, formatError.what());
         }
     }
References fmt, and format().
Referenced by debug_commandscript::HandleDebugGetItemStateCommand(), LogCommandUsage(), and Acore::Banner::Show().
StringTo()
template<typename Result , typename... Params> Optional<Result> Acore::StringTo (std::string_view str, Params &&... params)
Definition at line 309 of file StringConvert.h.
     {
         return Acore::Impl::StringConvertImpl::For<Result>::FromString(str, std::forward<Params>(params)...);
     }
Tokenize() [1/4]
std::vector<std::string_view> Acore::Tokenize (char const * str, char sep, bool keepEmpty) inline
Definition at line 34 of file Tokenize.h.
 { return Tokenize(std::string_view(str ? str : ""), sep, keepEmpty); }
References Tokenize().
Tokenize() [2/4]
std::vector<std::string_view> Acore::Tokenize (std::string && , char , bool) delete
Tokenize() [3/4]
std::vector<std::string_view> Acore::Tokenize (std::string const && , char , bool) delete
Tokenize() [4/4]
std::vector< std::string_view > Acore::Tokenize (std::string_view str, char sep, bool keepEmpty)
Definition at line 20 of file Tokenize.cpp.
 {
     std::vector<std::string_view> tokens;
     size_t start = 0;
     for (size_t end = str.find(sep); end != std::string_view::npos; end = str.find(sep, start))
     {
         if (keepEmpty || (start < end))
         {
             tokens.push_back(str.substr(start, end - start));
         }
         start = end + 1;
     }
     if (keepEmpty || (start < str.length()))
     {
         tokens.push_back(str.substr(start));
     }
     return tokens;
 }
Referenced by Log::CreateAppenderFromConfig(), Log::CreateLoggerFromConfig(), WorldSession::HandleCharFactionOrRaceChangeCallback(), reload_commandscript::HandleReloadCreatureTemplateCommand(), AppenderConsole::InitColors(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandsIntoMap(), Metric::LoadFromConfigs(), MySQLConnectionInfo::MySQLConnectionInfo(), UpdateFetcher::ReceiveIncludedDirectories(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelpFor(), ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendGlobalSysMessage(), ChatHandler::SendSysMessage(), and Tokenize().
ToString()
template<typename Type , typename... Params> std::string Acore::ToString (Type && val, Params &&... params)
Definition at line 315 of file StringConvert.h.
     {
         return Acore::Impl::StringConvertImpl::For<std::decay_t<Type>>::ToString(std::forward<Type>(val), std::forward<Params>(params)...);
     }
Referenced by Item::AddToUpdateQueueOf(), Battleground::DelCreature(), Battleground::DelObject(), WorldSession::DisallowHyperlinksAndMaybeKick(), Battleground::DoorClose(), Battleground::DoorOpen(), Battleground::GetBGCreature(), Battleground::GetBGObject(), ConfigMgr::GetValueDefault(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissCritter(), WorldSession::HandleEjectPassenger(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleLfgProposalResultOpcode(), WorldSession::HandleLfgTeleportOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcSetModelCommand(), AuraEffect::HandleObsModPowerAuraTick(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicEnergizeAuraTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), AuraEffect::HandlePeriodicManaLeechAuraTick(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleWorldTeleportOpcode(), WorldSession::moveItems(), SmartScript::ProcessAction(), Item::RemoveFromUpdateQueueOf(), WorldSession::SendLfgDisabled(), WorldSession::SendLfgJoinResult(), WorldSession::SendLfgLfrList(), WorldSession::SendLfgOfferContinue(), WorldSession::SendLfgQueueStatus(), WorldSession::SendLfgRoleCheckUpdate(), WorldSession::SendLfgRoleChosen(), WorldSession::SendLfgTeleportError(), WorldSession::ValidateHyperlinksAndMaybeKick(), and Object::~Object().
Warning()
void Acore::Warning (char const * file, int line, char const * function, char const * message)
Definition at line 104 of file Errors.cpp.
     {
         fprintf(stderr, "\n%s:%i in %s WARNING:\n  %s\n",
                 file, line, function, message);
     }
References mpq::file, fprintf(), and message().
Variable Documentation
dependant_false_v
template<typename T > constexpr bool Acore::dependant_false_v = dependant_false<T>::value constexpr
Definition at line 72 of file Types.h.
has_type_v
template<typename T , typename... Us> constexpr bool Acore::has_type_v = has_type<T, Us...>::value constexpr
Definition at line 34 of file Tuples.h.
is_tuple_v
template<typename... Ts> constexpr bool Acore::is_tuple_v = is_tuple<Ts...>::value constexpr
Definition at line 47 of file Tuples.h.