Azerotcore-wotlk: deps/mysqllite/sql-common/pack.c File Reference
pack.c File Reference
#include <my_global.h>
#include <mysql_com.h>
#include <mysql.h>
Functions
ulong STDCALL net_field_length (uchar **packet)
my_ulonglong net_field_length_ll (uchar **packet)
uchar * net_store_length (uchar *packet, ulonglong length)
Function Documentation
net_field_length()
ulong STDCALL net_field_length (uchar ** packet)
Definition at line 21 of file pack.c.
 {
   reg1 uchar *pos= (uchar *)*packet;
   if (*pos < 251)
   {
     (*packet)++;
     return (ulong) *pos;
   }
   if (*pos == 251)
   {
     (*packet)++;
     return NULL_LENGTH;
   }
   if (*pos == 252)
   {
     (*packet)+=3;
     return (ulong) uint2korr(pos+1);
   }
   if (*pos == 253)
   {
     (*packet)+=4;
     return (ulong) uint3korr(pos+1);
   }
   (*packet)+=9;                 /* Must be 254 when here */
   return (ulong) uint4korr(pos+1);
 }
References NULL_LENGTH, pos(), reg1, uint2korr, uint3korr, and uint4korr.
Referenced by cli_read_query_result(), cli_read_rows(), fetch_result_bin(), fetch_result_str(), fetch_result_with_conversion(), mysql_list_processes(), read_binary_date(), read_binary_datetime(), read_binary_time(), read_one_row(), skip_result_string(), and skip_result_with_length().
net_field_length_ll()
my_ulonglong net_field_length_ll (uchar ** packet)
Definition at line 49 of file pack.c.
 {
   reg1 uchar *pos= *packet;
   if (*pos < 251)
   {
     (*packet)++;
     return (my_ulonglong) *pos;
   }
   if (*pos == 251)
   {
     (*packet)++;
     return (my_ulonglong) NULL_LENGTH;
   }
   if (*pos == 252)
   {
     (*packet)+=3;
     return (my_ulonglong) uint2korr(pos+1);
   }
   if (*pos == 253)
   {
     (*packet)+=4;
     return (my_ulonglong) uint3korr(pos+1);
   }
   (*packet)+=9;                 /* Must be 254 when here */
 #ifdef NO_CLIENT_LONGLONG
   return (my_ulonglong) uint4korr(pos+1);
 #else
   return (my_ulonglong) uint8korr(pos+1);
 #endif
 }
References NULL_LENGTH, pos(), reg1, uint2korr, uint3korr, uint4korr, and uint8korr.
Referenced by cli_read_query_result(), and opt_flush_ok_packet().
net_store_length()
uchar* net_store_length (uchar * packet, ulonglong length)
Definition at line 97 of file pack.c.
 {
   if (length < (ulonglong) LL(251))
   {
     *packet=(uchar) length;
     return packet+1;
   }
   /* 251 is reserved for NULL */
   if (length < (ulonglong) LL(65536))
   {
     *packet++=252;
     int2store(packet,(uint) length);
     return packet+2;
   }
   if (length < (ulonglong) LL(16777216))
   {
     *packet++=253;
     int3store(packet,(ulong) length);
     return packet+3;
   }
   *packet++=254;
   int8store(packet,length);
   return packet+8;
 }
References int2store, int3store, int8store, G3D::length(), and LL.
Referenced by store_param_str().