Azerotcore-wotlk: TypeContainerVisitor< VISITOR, TYPE_CONTAINER > Class Template Reference
TypeContainerVisitor< VISITOR, TYPE_CONTAINER > Class Template Reference
#include <TypeContainerVisitor.h>
Public Member Functions
TypeContainerVisitor (VISITOR &v)
void Visit (TYPE_CONTAINER &c)
void Visit (const TYPE_CONTAINER &c) const
Private Attributes
VISITOR & i_visitor
Detailed Description
template<class VISITOR, class TYPE_CONTAINER>
class TypeContainerVisitor< VISITOR, TYPE_CONTAINER >
Definition at line 84 of file TypeContainerVisitor.h.
Constructor & Destructor Documentation
TypeContainerVisitor()
template<class VISITOR , class TYPE_CONTAINER > TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::TypeContainerVisitor (VISITOR & v) inline
Definition at line 87 of file TypeContainerVisitor.h.
 : i_visitor(v) { }
Member Function Documentation
Visit() [1/2]
template<class VISITOR , class TYPE_CONTAINER > void TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit (const TYPE_CONTAINER & c) const inline
Definition at line 94 of file TypeContainerVisitor.h.
     {
         VisitorHelper(i_visitor, c);
     }
References TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor, and VisitorHelper().
Visit() [2/2]
template<class VISITOR , class TYPE_CONTAINER > void TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit (TYPE_CONTAINER & c) inline
Definition at line 89 of file TypeContainerVisitor.h.
     {
         VisitorHelper(i_visitor, c);
     }
References TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor, and VisitorHelper().
Referenced by GameEventMgr::RunSmartAIScripts().
Member Data Documentation
i_visitor
template<class VISITOR , class TYPE_CONTAINER > VISITOR& TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::i_visitor private
Definition at line 100 of file TypeContainerVisitor.h.
Referenced by TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit().
The documentation for this class was generated from the following file:
src/common/Dynamic/TypeContainerVisitor.h