Azerotcore-wotlk: boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI Struct Reference
boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI Struct Reference
Public Member Functions
boss_mekgineer_steamriggerAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void EnterCombat (Unit *) override
void SummonMechanics ()
void JustSummoned (Creature *cr) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 55 of file boss_mekgineer_steamrigger.cpp.
Constructor & Destructor Documentation
boss_mekgineer_steamriggerAI()
boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI (Creature * creature) inline
Definition at line 57 of file boss_mekgineer_steamrigger.cpp.
                                                          : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
EnterCombat()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 85 of file boss_mekgineer_steamrigger.cpp.
         {
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_SPELL_SHRINK, 20000);
             events.ScheduleEvent(EVENT_SPELL_SAW, 15000);
             events.ScheduleEvent(EVENT_SPELL_NET, 10000);
             events.ScheduleEvent(EVENT_CHECK_HP75, 5000);
             events.ScheduleEvent(EVENT_CHECK_HP50, 5000);
             events.ScheduleEvent(EVENT_CHECK_HP25, 5000);
             if (instance)
                 instance->SetData(TYPE_MEKGINEER_STEAMRIGGER, IN_PROGRESS);
         }
References EVENT_CHECK_HP25, EVENT_CHECK_HP50, EVENT_CHECK_HP75, EVENT_SPELL_NET, EVENT_SPELL_SAW, EVENT_SPELL_SHRINK, IN_PROGRESS, instance, SAY_AGGRO, ZoneScript::SetData(), CreatureAI::Talk(), and TYPE_MEKGINEER_STEAMRIGGER.
JustDied()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 72 of file boss_mekgineer_steamrigger.cpp.
         {
             Talk(SAY_DEATH);
             if (instance)
                 instance->SetData(TYPE_MEKGINEER_STEAMRIGGER, DONE);
         }
References DONE, instance, SAY_DEATH, ZoneScript::SetData(), CreatureAI::Talk(), and TYPE_MEKGINEER_STEAMRIGGER.
JustSummoned()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 110 of file boss_mekgineer_steamrigger.cpp.
         {
             cr->GetMotionMaster()->MoveFollow(me, 0.0f, 0.0f);
         }
References Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveFollow().
KilledUnit()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 79 of file boss_mekgineer_steamrigger.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 65 of file boss_mekgineer_steamrigger.cpp.
         {
             events.Reset();
             if (instance)
                 instance->SetData(TYPE_MEKGINEER_STEAMRIGGER, NOT_STARTED);
         }
References instance, NOT_STARTED, ZoneScript::SetData(), and TYPE_MEKGINEER_STEAMRIGGER.
SummonMechanics()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics () inline
Definition at line 99 of file boss_mekgineer_steamrigger.cpp.
         {
             Talk(SAY_MECHANICS);
             me->SummonCreature(NPC_STREAMRIGGER_MECHANIC, me->GetPositionX() + 15.0f, me->GetPositionY() + 15.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000);
             me->SummonCreature(NPC_STREAMRIGGER_MECHANIC, me->GetPositionX() - 15.0f, me->GetPositionY() + 15.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000);
             me->SummonCreature(NPC_STREAMRIGGER_MECHANIC, me->GetPositionX() - 15.0f, me->GetPositionY() - 15.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000);
             if (urand(0, 1))
                 me->SummonCreature(NPC_STREAMRIGGER_MECHANIC, me->GetPositionX() + 15.0f, me->GetPositionY() - 15.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000);
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_STREAMRIGGER_MECHANIC, SAY_MECHANICS, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 115 of file boss_mekgineer_steamrigger.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             switch (uint32 eventId = events.ExecuteEvent())
             {
                 case EVENT_SPELL_SHRINK:
                     me->CastSpell(me->GetVictim(), SPELL_SUPER_SHRINK_RAY, false);
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_SPELL_SAW:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1))
                         me->CastSpell(target, SPELL_SAW_BLADE, false);
                     else
                         me->CastSpell(me->GetVictim(), SPELL_SAW_BLADE, false);
                     events.RepeatEvent(15000);
                     break;
                 case EVENT_SPELL_NET:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_ELECTRIFIED_NET, false);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_CHECK_HP25:
                 case EVENT_CHECK_HP50:
                 case EVENT_CHECK_HP75:
                     if (me->HealthBelowPct(eventId * 25))
                     {
                         SummonMechanics();
                         return;
                     }
                     events.RepeatEvent(2000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_CHECK_HP25, EVENT_CHECK_HP50, EVENT_CHECK_HP75, EVENT_SPELL_NET, EVENT_SPELL_SAW, EVENT_SPELL_SHRINK, Unit::GetVictim(), Unit::HealthBelowPct(), ScriptedAI::me, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_ELECTRIFIED_NET, SPELL_SAW_BLADE, SPELL_SUPER_SHRINK_RAY, SummonMechanics(), and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::events
Definition at line 63 of file boss_mekgineer_steamrigger.cpp.
instance
InstanceScript* boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::instance
Definition at line 62 of file boss_mekgineer_steamrigger.cpp.
Referenced by boss_mekgineer_steamriggerAI(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp