Azerotcore-wotlk: MySQLPreparedStatement Class Reference
MySQLPreparedStatement Class Reference
#include <MySQLPreparedStatement.h>
Public Member Functions
MySQLPreparedStatement (MySQLStmt *stmt, std::string queryString)
~MySQLPreparedStatement ()
void BindParameters (PreparedStatementBase *stmt)
uint32 GetParameterCount () const
Protected Member Functions
void SetParameter (uint8 index, std::nullptr_t)
void SetParameter (uint8 index, bool value)
template<typename T >
void SetParameter (uint8 index, T value)
void SetParameter (uint8 index, std::string const &value)
void SetParameter (uint8 index, std::vector< uint8 > const &value)
MySQLStmt * GetSTMT ()
MySQLBind * GetBind ()
void ClearParameters ()
void AssertValidIndex (uint8 index)
std::string getQueryString () const
Protected Attributes
PreparedStatementBase * m_stmt
Private Member Functions
MySQLPreparedStatement (MySQLPreparedStatement const &right)=delete
MySQLPreparedStatement & operator= (MySQLPreparedStatement const &right)=delete
Private Attributes
MySQLStmt * m_Mstmt
uint32 m_paramCount
std::vector< bool > m_paramsSet
MySQLBind * m_bind
std::string const m_queryString
Friends
class MySQLConnection
class PreparedStatementBase
Detailed Description
Definition at line 33 of file MySQLPreparedStatement.h.
Constructor & Destructor Documentation
MySQLPreparedStatement() [1/2]
MySQLPreparedStatement::MySQLPreparedStatement (MySQLStmt * stmt, std::string queryString)
Initialize variable parameters
"If set to 1, causes mysql_stmt_store_result() to update the metadata MYSQL_FIELD->max_length value."
Definition at line 38 of file MySQLPreparedStatement.cpp.
                                                                                      :
     m_stmt(nullptr), m_Mstmt(stmt), m_bind(nullptr), m_queryString(std::move(queryString))
 {
     m_paramCount = mysql_stmt_param_count(stmt);
     m_paramsSet.assign(m_paramCount, false);
     m_bind = new MySQLBind[m_paramCount];
     memset(m_bind, 0, sizeof(MySQLBind) * m_paramCount);
     MySQLBool bool_tmp = MySQLBool(1);
     mysql_stmt_attr_set(stmt, STMT_ATTR_UPDATE_MAX_LENGTH, &bool_tmp);
 }
References m_bind, m_paramCount, and m_paramsSet.
~MySQLPreparedStatement()
MySQLPreparedStatement::~MySQLPreparedStatement ()
Definition at line 52 of file MySQLPreparedStatement.cpp.
 {
     ClearParameters();
     if (m_Mstmt->bind_result_done)
     {
         delete[] m_Mstmt->bind->length;
         delete[] m_Mstmt->bind->is_null;
     }
     mysql_stmt_close(m_Mstmt);
     delete[] m_bind;
 }
References ClearParameters(), m_bind, and m_Mstmt.
MySQLPreparedStatement() [2/2]
MySQLPreparedStatement::MySQLPreparedStatement (MySQLPreparedStatement const & right) private delete
Member Function Documentation
AssertValidIndex()
void MySQLPreparedStatement::AssertValidIndex (uint8 index) protected
Definition at line 102 of file MySQLPreparedStatement.cpp.
 {
     ASSERT(index < m_paramCount || ParamenterIndexAssertFail(m_stmt->GetIndex(), index, m_paramCount));
     if (m_paramsSet[index])
         LOG_ERROR("sql.sql", "[ERROR] Prepared Statement (id: %u) trying to bind value on already bound index (%u).", m_stmt->GetIndex(), index);
 }
References ASSERT, PreparedStatementBase::GetIndex(), LOG_ERROR, m_paramCount, m_paramsSet, m_stmt, and ParamenterIndexAssertFail().
Referenced by SetParameter().
BindParameters()
void MySQLPreparedStatement::BindParameters (PreparedStatementBase * stmt)
Definition at line 64 of file MySQLPreparedStatement.cpp.
 {
     m_stmt = stmt;     // Cross reference them for debug output
     uint8 pos = 0;
     for (PreparedStatementData const& data : stmt->GetParameters())
     {
         std::visit([&](auto&& param)
         {
             SetParameter(pos, param);
         }, data.data);
         ++pos;
     }
 #ifdef _DEBUG
     if (pos < m_paramCount)
         LOG_WARN("sql.sql", "[WARNING]: BindParameters() for statement %u did not bind all allocated parameters", stmt->GetIndex());
 #endif
 }
References PreparedStatementBase::GetIndex(), PreparedStatementBase::GetParameters(), LOG_WARN, m_paramCount, m_stmt, and SetParameter().
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
ClearParameters()
void MySQLPreparedStatement::ClearParameters () protected
Definition at line 83 of file MySQLPreparedStatement.cpp.
 {
     for (uint32 i=0; i < m_paramCount; ++i)
     {
         delete m_bind[i].length;
         m_bind[i].length = nullptr;
         delete[] (char*) m_bind[i].buffer;
         m_bind[i].buffer = nullptr;
         m_paramsSet[i] = false;
     }
 }
References m_bind, m_paramCount, and m_paramsSet.
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), and ~MySQLPreparedStatement().
GetBind()
MySQLBind* MySQLPreparedStatement::GetBind () inline protected
Definition at line 55 of file MySQLPreparedStatement.h.
 { return m_bind; }
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
GetParameterCount()
uint32 MySQLPreparedStatement::GetParameterCount () const inline
Definition at line 44 of file MySQLPreparedStatement.h.
 { return m_paramCount; }
getQueryString()
std::string MySQLPreparedStatement::getQueryString () const protected
Definition at line 181 of file MySQLPreparedStatement.cpp.
 {
     std::string queryString(m_queryString);
     size_t pos = 0;
     for (PreparedStatementData const& data : m_stmt->GetParameters())
     {
         pos = queryString.find('?', pos);
         std::string replaceStr = std::visit([&](auto&& data)
         {
             return PreparedStatementData::ToString(data);
         }, data.data);
         queryString.replace(pos, 1, replaceStr);
         pos += replaceStr.length();
     }
     return queryString;
 }
References PreparedStatementBase::GetParameters(), m_queryString, m_stmt, and PreparedStatementData::ToString().
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
GetSTMT()
MySQLStmt* MySQLPreparedStatement::GetSTMT () inline protected
Definition at line 54 of file MySQLPreparedStatement.h.
 { return m_Mstmt; }
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), and MySQLConnection::Query().
operator=()
MySQLPreparedStatement& MySQLPreparedStatement::operator= (MySQLPreparedStatement const & right) private delete
SetParameter() [1/5]
void MySQLPreparedStatement::SetParameter (uint8 index, bool value) protected
Definition at line 124 of file MySQLPreparedStatement.cpp.
 {
     SetParameter(index, uint8(value ? 1 : 0));
 }
References SetParameter().
SetParameter() [2/5]
void MySQLPreparedStatement::SetParameter (uint8 index, std::nullptr_t) protected
Definition at line 110 of file MySQLPreparedStatement.cpp.
 {
     AssertValidIndex(index);
     m_paramsSet[index] = true;
     MYSQL_BIND* param = &m_bind[index];
     param->buffer_type = MYSQL_TYPE_NULL;
     delete[] static_cast<char*>(param->buffer);
     param->buffer = nullptr;
     param->buffer_length = 0;
     param->is_null_value = 1;
     delete param->length;
     param->length = nullptr;
 }
References AssertValidIndex(), m_bind, and m_paramsSet.
Referenced by BindParameters(), and SetParameter().
SetParameter() [3/5]
void MySQLPreparedStatement::SetParameter (uint8 index, std::string const & value) protected
Definition at line 147 of file MySQLPreparedStatement.cpp.
 {
     AssertValidIndex(index);
     m_paramsSet[index] = true;
     MYSQL_BIND* param = &m_bind[index];
     uint32 len = uint32(value.size());
     param->buffer_type = MYSQL_TYPE_VAR_STRING;
     delete [] static_cast<char*>(param->buffer);
     param->buffer = new char[len];
     param->buffer_length = len;
     param->is_null_value = 0;
     delete param->length;
     param->length = new unsigned long(len);
     memcpy(param->buffer, value.c_str(), len);
 }
References AssertValidIndex(), m_bind, and m_paramsSet.
SetParameter() [4/5]
void MySQLPreparedStatement::SetParameter (uint8 index, std::vector< uint8 > const & value) protected
Definition at line 164 of file MySQLPreparedStatement.cpp.
 {
     AssertValidIndex(index);
     m_paramsSet[index] = true;
     MYSQL_BIND* param = &m_bind[index];
     uint32 len = uint32(value.size());
     param->buffer_type = MYSQL_TYPE_BLOB;
     delete [] static_cast<char*>(param->buffer);
     param->buffer = new char[len];
     param->buffer_length = len;
     param->is_null_value = 0;
     delete param->length;
     param->length = new unsigned long(len);
     memcpy(param->buffer, value.data(), len);
 }
References AssertValidIndex(), m_bind, and m_paramsSet.
SetParameter() [5/5]
template<typename T > void MySQLPreparedStatement::SetParameter (uint8 index, T value) protected
Definition at line 130 of file MySQLPreparedStatement.cpp.
 {
     AssertValidIndex(index);
     m_paramsSet[index] = true;
     MYSQL_BIND* param = &m_bind[index];
     uint32 len = uint32(sizeof(T));
     param->buffer_type = MySQLType<T>::value;
     delete[] static_cast<char*>(param->buffer);
     param->buffer = new char[len];
     param->buffer_length = 0;
     param->is_null_value = 0;
     param->length = nullptr;               // Only != NULL for strings
     param->is_unsigned = std::is_unsigned_v<T>;
     memcpy(param->buffer, &value, len);
 }
References AssertValidIndex(), m_bind, and m_paramsSet.
Friends And Related Function Documentation
MySQLConnection
friend class MySQLConnection friend
Definition at line 35 of file MySQLPreparedStatement.h.
PreparedStatementBase
friend class PreparedStatementBase friend
Definition at line 36 of file MySQLPreparedStatement.h.
Member Data Documentation
m_bind
MySQLBind* MySQLPreparedStatement::m_bind private
Definition at line 65 of file MySQLPreparedStatement.h.
Referenced by ClearParameters(), MySQLPreparedStatement(), SetParameter(), and ~MySQLPreparedStatement().
m_Mstmt
MySQLStmt* MySQLPreparedStatement::m_Mstmt private
Definition at line 62 of file MySQLPreparedStatement.h.
Referenced by ~MySQLPreparedStatement().
m_paramCount
uint32 MySQLPreparedStatement::m_paramCount private
Definition at line 63 of file MySQLPreparedStatement.h.
Referenced by AssertValidIndex(), BindParameters(), ClearParameters(), and MySQLPreparedStatement().
m_paramsSet
std::vector<bool> MySQLPreparedStatement::m_paramsSet private
Definition at line 64 of file MySQLPreparedStatement.h.
Referenced by AssertValidIndex(), ClearParameters(), MySQLPreparedStatement(), and SetParameter().
m_queryString
std::string const MySQLPreparedStatement::m_queryString private
Definition at line 66 of file MySQLPreparedStatement.h.
Referenced by getQueryString().
m_stmt
PreparedStatementBase* MySQLPreparedStatement::m_stmt protected
Definition at line 56 of file MySQLPreparedStatement.h.
Referenced by AssertValidIndex(), BindParameters(), and getQueryString().
The documentation for this class was generated from the following files:
src/server/database/Database/MySQLPreparedStatement.h
src/server/database/Database/MySQLPreparedStatement.cpp