Azerotcore-wotlk: boss_azgalor::boss_azgalorAI Struct Reference
boss_azgalor::boss_azgalorAI Struct Reference
Public Member Functions
boss_azgalorAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *) override
void WaypointReached (uint32 waypointId) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from hyjal_trashAI
hyjal_trashAI (Creature *creature)
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void DamageTaken (Unit *done_by, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 RainTimer
uint32 DoomTimer
uint32 HowlTimer
uint32 CleaveTimer
uint32 EnrageTimer
bool enraged
bool go
Public Attributes inherited from hyjal_trashAI
InstanceScript * instance
bool IsEvent
uint32 Delay
uint32 LastOverronPos
bool IsOverrun
bool SetupOverrun
uint32 OverrunType
uint8 faction
bool useFlyPath
uint32 damageTaken
float DummyTarget [3]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 54 of file boss_azgalor.cpp.
Constructor & Destructor Documentation
boss_azgalorAI()
boss_azgalor::boss_azgalorAI::boss_azgalorAI (Creature * creature) inline
Definition at line 56 of file boss_azgalor.cpp.
                                            : hyjal_trashAI(creature)
         {
             instance = creature->GetInstanceScript();
             go = false;
         }
References WorldObject::GetInstanceScript(), go, and hyjal_trashAI::instance.
Member Function Documentation
EnterCombat()
void boss_azgalor::boss_azgalorAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 85 of file boss_azgalor.cpp.
         {
             if (IsEvent)
                 instance->SetData(DATA_AZGALOREVENT, IN_PROGRESS);
             Talk(SAY_ONAGGRO);
         }
References DATA_AZGALOREVENT, IN_PROGRESS, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, SAY_ONAGGRO, ZoneScript::SetData(), and CreatureAI::Talk().
JustDied()
void boss_azgalor::boss_azgalorAI::JustDied (Unit * killer) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 108 of file boss_azgalor.cpp.
         {
             hyjal_trashAI::JustDied(killer);
             if (IsEvent)
                 instance->SetData(DATA_AZGALOREVENT, DONE);
             Talk(SAY_ONDEATH);
         }
References DATA_AZGALOREVENT, DONE, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, hyjal_trashAI::JustDied(), SAY_ONDEATH, ZoneScript::SetData(), and CreatureAI::Talk().
KilledUnit()
void boss_azgalor::boss_azgalorAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 93 of file boss_azgalor.cpp.
         {
             Talk(SAY_ONSLAY);
         }
References SAY_ONSLAY, and CreatureAI::Talk().
Reset()
void boss_azgalor::boss_azgalorAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 71 of file boss_azgalor.cpp.
         {
             damageTaken = 0;
             RainTimer = 20000;
             DoomTimer = 50000;
             HowlTimer = 30000;
             CleaveTimer = 10000;
             EnrageTimer = 600000;
             enraged = false;
             if (IsEvent)
                 instance->SetData(DATA_AZGALOREVENT, NOT_STARTED);
         }
References CleaveTimer, hyjal_trashAI::damageTaken, DATA_AZGALOREVENT, DoomTimer, enraged, EnrageTimer, HowlTimer, hyjal_trashAI::instance, hyjal_trashAI::IsEvent, NOT_STARTED, RainTimer, and ZoneScript::SetData().
UpdateAI()
void boss_azgalor::boss_azgalorAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 116 of file boss_azgalor.cpp.
         {
             if (IsEvent)
             {
                 //Must update npc_escortAI
                 npc_escortAI::UpdateAI(diff);
                 if (!go)
                 {
                     go = true;
                     AddWaypoint(0, 5492.91f,    -2404.61f,    1462.63f);
                     AddWaypoint(1, 5531.76f,    -2460.87f,    1469.55f);
                     AddWaypoint(2, 5554.58f,    -2514.66f,    1476.12f);
                     AddWaypoint(3, 5554.16f,    -2567.23f,    1479.90f);
                     AddWaypoint(4, 5540.67f,    -2625.99f,    1480.89f);
                     AddWaypoint(5, 5508.16f,    -2659.2f,    1480.15f);
                     AddWaypoint(6, 5489.62f,    -2704.05f,    1482.18f);
                     AddWaypoint(7, 5457.04f,    -2726.26f,    1485.10f);
                     Start(false, true);
                     SetDespawnAtEnd(false);
                 }
             }
             //Return since we have no target
             if (!UpdateVictim())
                 return;
             if (RainTimer <= diff)
             {
                 DoCast(SelectTarget(SELECT_TARGET_RANDOM, 0, 30, true), SPELL_RAIN_OF_FIRE);
                 RainTimer = 20000 + rand() % 15000;
             }
             else RainTimer -= diff;
             if (DoomTimer <= diff)
             {
                 DoCast(SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true), SPELL_DOOM);//never on tank
                 DoomTimer = 45000 + rand() % 5000;
             }
             else DoomTimer -= diff;
             if (HowlTimer <= diff)
             {
                 DoCast(me, SPELL_HOWL_OF_AZGALOR);
                 HowlTimer = 30000;
             }
             else HowlTimer -= diff;
             if (CleaveTimer <= diff)
             {
                 DoCastVictim(SPELL_CLEAVE);
                 CleaveTimer = 10000 + rand() % 5000;
             }
             else CleaveTimer -= diff;
             if (EnrageTimer < diff && !enraged)
             {
                 me->InterruptNonMeleeSpells(false);
                 DoCast(me, SPELL_BERSERK, true);
                 enraged = true;
                 EnrageTimer = 600000;
             }
             else EnrageTimer -= diff;
             DoMeleeAttackIfReady();
         }
References npc_escortAI::AddWaypoint(), CleaveTimer, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), DoomTimer, enraged, EnrageTimer, go, HowlTimer, Unit::InterruptNonMeleeSpells(), hyjal_trashAI::IsEvent, ScriptedAI::me, RainTimer, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), npc_escortAI::SetDespawnAtEnd(), SPELL_BERSERK, SPELL_CLEAVE, SPELL_DOOM, SPELL_HOWL_OF_AZGALOR, SPELL_RAIN_OF_FIRE, npc_escortAI::Start(), npc_escortAI::UpdateAI(), and CreatureAI::UpdateVictim().
WaypointReached()
void boss_azgalor::boss_azgalorAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 98 of file boss_azgalor.cpp.
         {
             if (waypointId == 7 && instance)
             {
                 Unit* target = ObjectAccessor::GetUnit(*me, instance->GetGuidData(DATA_THRALL));
                 if (target && target->IsAlive())
                     me->AddThreat(target, 0.0f);
             }
         }
References Unit::AddThreat(), DATA_THRALL, InstanceScript::GetGuidData(), ObjectAccessor::GetUnit(), hyjal_trashAI::instance, Unit::IsAlive(), and ScriptedAI::me.
Member Data Documentation
CleaveTimer
uint32 boss_azgalor::boss_azgalorAI::CleaveTimer
Definition at line 65 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
DoomTimer
uint32 boss_azgalor::boss_azgalorAI::DoomTimer
Definition at line 63 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
enraged
bool boss_azgalor::boss_azgalorAI::enraged
Definition at line 67 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
EnrageTimer
uint32 boss_azgalor::boss_azgalorAI::EnrageTimer
Definition at line 66 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
go
bool boss_azgalor::boss_azgalorAI::go
Definition at line 69 of file boss_azgalor.cpp.
Referenced by boss_azgalorAI(), and UpdateAI().
HowlTimer
uint32 boss_azgalor::boss_azgalorAI::HowlTimer
Definition at line 64 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
RainTimer
uint32 boss_azgalor::boss_azgalorAI::RainTimer
Definition at line 62 of file boss_azgalor.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp