Azerotcore-wotlk: deps/mysqllite/include/my_sys.h File Reference
my_sys.h File Reference
#include "my_global.h"
#include <my_pthread.h>
#include <m_ctype.h>
#include <stdarg.h>
#include <typelib.h>
#include <my_alloc.h>
#include <mysql/psi/psi.h>
Classes
struct st_record_cache
struct st_my_file_info
struct st_dynamic_array
struct st_my_tmpdir
struct st_dynamic_string
struct st_io_cache_share
struct st_io_cache
Macros
#define MEM_UNDEFINED(a, len) ((void) 0)
#define MEM_NOACCESS(a, len) ((void) 0)
#define MEM_CHECK_ADDRESSABLE(a, len) ((void) 0)
#define MEM_CHECK_DEFINED(a, len) ((void) 0)
#define MY_INIT(name) { my_progname= name; my_init(); }
#define MYSYS_ERRMSG_SIZE (512)
#define MY_FILE_ERROR ((size_t) -1)
#define MY_FFNF 1 /* Fatal if file not found */
#define MY_FNABP 2 /* Fatal if not all bytes read/writen */
#define MY_NABP 4 /* Error if not all bytes read/writen */
#define MY_FAE 8 /* Fatal if any error */
#define MY_WME 16 /* Write message on error */
#define MY_WAIT_IF_FULL 32 /* Wait and try again if disk full error */
#define MY_IGNORE_BADFD 32 /* my_sync: ignore 'bad descriptor' errors */
#define MY_SYNC_DIR 8192 /* my_create/delete/rename: sync directory */
#define MY_UNUSED 64 /* Unused (was support for RAID) */
#define MY_FULL_IO 512 /* For my_read - loop intil I/O is complete */
#define MY_DONT_CHECK_FILESIZE 128 /* Option to init_io_cache() */
#define MY_LINK_WARNING 32 /* my_redel() gives warning if links */
#define MY_COPYTIME 64 /* my_redel() copys time */
#define MY_DELETE_OLD 256 /* my_create_with_symlink() */
#define MY_RESOLVE_LINK 128 /* my_realpath(); Only resolve links */
#define MY_HOLD_ORIGINAL_MODES 128 /* my_copy() holds to file modes */
#define MY_REDEL_MAKE_BACKUP 256
#define MY_SEEK_NOT_DONE 32 /* my_lock may have to do a seek */
#define MY_DONT_WAIT 64 /* my_lock() don't wait if can't lock */
#define MY_ZEROFILL 32 /* my_malloc(), fill array with zero */
#define MY_ALLOW_ZERO_PTR 64 /* my_realloc() ; zero ptr -> malloc */
#define MY_FREE_ON_ERROR 128 /* my_realloc() ; Free old ptr on error */
#define MY_HOLD_ON_ERROR 256 /* my_realloc() ; Return old ptr on error */
#define MY_DONT_OVERWRITE_FILE 1024 /* my_copy: Don't overwrite file */
#define MY_THREADSAFE 2048 /* my_seek(): lock fd mutex */
#define MY_SYNC 4096 /* my_copy(): sync dst file */
#define MY_CHECK_ERROR 1 /* Params to my_end; Check open-close */
#define MY_GIVE_INFO 2 /* Give time info about process*/
#define MY_DONT_FREE_DBUG 4 /* Do not call DBUG_END() in my_end() */
#define ME_HIGHBYTE 8 /* Shift for colours */
#define ME_NOCUR 1 /* Don't use curses message */
#define ME_OLDWIN 2 /* Use old window */
#define ME_BELL 4 /* Ring bell then printing message */
#define ME_HOLDTANG 8 /* Don't delete last keys */
#define ME_WAITTOT 16 /* Wait for errtime secs of for a action */
#define ME_WAITTANG 32 /* Wait for a user action */
#define ME_NOREFRESH 64 /* Dont refresh screen */
#define ME_NOINPUT 128 /* Dont use the input libary */
#define ME_COLOUR1 ((1 << ME_HIGHBYTE)) /* Possibly error-colours */
#define ME_COLOUR2 ((2 << ME_HIGHBYTE))
#define ME_COLOUR3 ((3 << ME_HIGHBYTE))
#define ME_FATALERROR 1024 /* Fatal statement error */
#define MY_REPLACE_DIR 1 /* replace dir in name with 'dir' */
#define MY_REPLACE_EXT 2 /* replace extension with 'ext' */
#define MY_UNPACK_FILENAME 4 /* Unpack name (~ -> home) */
#define MY_PACK_FILENAME 8 /* Pack name (home -> ~) */
#define MY_RESOLVE_SYMLINKS 16 /* Resolve all symbolic links */
#define MY_RETURN_REAL_PATH 32 /* return full path for file */
#define MY_SAFE_PATH 64 /* Return NULL if too long path */
#define MY_RELATIVE_PATH 128 /* name is relative to 'dir' */
#define MY_APPEND_EXT 256 /* add 'ext' as additional extension*/
#define MY_SEEK_SET 0
#define MY_SEEK_CUR 1
#define MY_SEEK_END 2
#define MY_WAIT_FOR_USER_TO_FIX_PANIC 60 /* in seconds */
#define MY_WAIT_GIVE_USER_A_MESSAGE 10 /* Every 10 times of prev */
#define MIN_COMPRESS_LENGTH 50 /* Don't compress small bl. */
#define DFLT_INIT_HITS 3
#define MY_KEEP_PREALLOC 1
#define MY_MARK_BLOCKS_FREE 2 /* move used to free list and reuse them */
#define MY_ERRNO_EDOM 33
#define MY_ERRNO_ERANGE 34
#define GETDATE_DATE_TIME 1
#define GETDATE_SHORT_DATE 2
#define GETDATE_HHMMSSTIME 4
#define GETDATE_GMT 8
#define GETDATE_FIXEDLENGTH 16
#define TRASH(A, B) do{MEM_CHECK_ADDRESSABLE(A,B);MEM_UNDEFINED(A,B);} while (0)
#define DEBUG_SYNC_C(_sync_point_name_)
#define my_get_large_page_size() (0)
#define my_large_malloc(A, B) my_malloc_lock((A),(B))
#define my_large_free(A) my_free_lock((A))
#define my_alloca(SZ) my_malloc(SZ,MYF(MY_FAE))
#define my_afree(PTR) my_free(PTR)
#define MY_ALL_CHARSETS_SIZE 2048
#define my_b_clear(info) (info)->buffer=0
#define my_b_inited(info) (info)->buffer
#define my_b_EOF INT_MIN
#define my_b_read(info, Buffer, Count)
#define my_b_write(info, Buffer, Count)
#define my_b_get(info)
#define my_b_write_byte(info, chr)
#define my_b_fill_cache(info) (((info)->read_end=(info)->read_pos),(*(info)->read_function)(info,0,0))
#define my_b_tell(info)
#define my_b_get_buffer_start(info) (info)->request_pos
#define my_b_get_bytes_in_buffer(info)
#define my_b_get_pos_in_file(info) (info)->pos_in_file
#define my_b_bytes_in_cache(info)
#define my_access access
#define my_delete_allow_opened(fname, flags) my_delete((fname),(flags))
#define my_print_open_files()
#define base_name(A) (A+dirname_length(A))
#define flush_io_cache(info) my_b_flush_io_cache((info),1)
#define my_init_dynamic_array(A, B, C, D) init_dynamic_array2(A,B,NULL,C,D)
#define my_init_dynamic_array_ci(A, B, C, D) init_dynamic_array2(A,B,NULL,C,D)
#define my_init_dynamic_array2(A, B, C, D, E) init_dynamic_array2(A,B,C,D,E)
#define my_init_dynamic_array2_ci(A, B, C, D, E) init_dynamic_array2(A,B,C,D,E)
#define dynamic_array_ptr(array, array_index) ((array)->buffer+(array_index)*(array)->size_of_element)
#define dynamic_element(array, array_index, type) ((type)((array)->buffer) +(array_index))
#define push_dynamic(A, B) insert_dynamic((A),(B))
#define reset_dynamic(array) ((array)->elements= 0)
#define sort_dynamic(A, cmp) my_qsort((A)->buffer, (A)->elements, (A)->size_of_element, (cmp))
#define my_malloc_lock(A, B) my_malloc((A),(B))
#define my_free_lock(A) my_free((A))
#define alloc_root_inited(A) ((A)->min_malloc != 0)
#define ALLOC_ROOT_MIN_BLOCK_SIZE (MALLOC_OVERHEAD + sizeof(USED_MEM) + 8)
#define clear_alloc_root(A) do { (A)->free= (A)->used= (A)->pre_alloc= 0; (A)->min_malloc=0;} while(0)
#define PROT_READ 1
#define PROT_WRITE 2
#define MAP_NORESERVE 0
#define MAP_SHARED 0x0001
#define MAP_PRIVATE 0x0002
#define MAP_NOSYNC 0x0800
#define MAP_FAILED ((void *)-1)
#define MS_SYNC 0x0000
#define HAVE_MMAP
Typedefs
typedef struct st_record_cache RECORD_CACHE
typedef struct st_dynamic_array DYNAMIC_ARRAY
typedef struct st_my_tmpdir MY_TMPDIR
typedef struct st_dynamic_string DYNAMIC_STRING
typedef int(* IO_CACHE_CALLBACK) (struct st_io_cache *)
typedef struct st_io_cache_share IO_CACHE_SHARE
typedef struct st_io_cache IO_CACHE
typedef int(* qsort2_cmp) (const void *, const void *, const void *)
typedef uint32 ha_checksum
typedef int(* Process_option_func) (void *ctx, const char *group_name, const char *option)
Enumerations
enum loglevel { ERROR_LEVEL , WARNING_LEVEL , INFORMATION_LEVEL }
enum cache_type {
TYPE_NOT_SET = 0 , READ_CACHE , WRITE_CACHE , SEQ_READ_APPEND ,
READ_FIFO , READ_NET , WRITE_NET
}
enum flush_type { FLUSH_KEEP , FLUSH_RELEASE , FLUSH_IGNORE_CHANGED , FLUSH_FORCE_WRITE }
enum file_type {
UNOPEN = 0 , FILE_BY_OPEN , FILE_BY_CREATE , STREAM_BY_FOPEN ,
STREAM_BY_FDOPEN , FILE_BY_MKSTEMP , FILE_BY_DUP
}
Functions
void * my_malloc (size_t Size, myf MyFlags)
void * my_multi_malloc (myf MyFlags,...)
void * my_realloc (void *oldpoint, size_t Size, myf MyFlags)
wrapper around realloc()
void my_free (void *ptr)
void * my_memdup (const void *from, size_t length, myf MyFlags)
char * my_strdup (const char *from, myf MyFlags)
char * my_strndup (const char *from, size_t length, myf MyFlags)
int my_b_copy_to_file (IO_CACHE *cache, FILE *file)
my_off_t my_b_append_tell (IO_CACHE *info)
my_off_t my_b_safe_tell (IO_CACHE *info)
int my_copy (const char *from, const char *to, myf MyFlags)
int my_delete (const char *name, myf MyFlags)
int my_getwd (char *buf, size_t size, myf MyFlags)
int my_setwd (const char *dir, myf MyFlags)
int my_lock (File fd, int op, my_off_t start, my_off_t length, myf MyFlags)
void * my_once_alloc (size_t Size, myf MyFlags)
void my_once_free (void)
char * my_once_strdup (const char *src, myf myflags)
void * my_once_memdup (const void *src, size_t len, myf myflags)
File my_open (const char *FileName, int Flags, myf MyFlags)
File my_register_filename (File fd, const char *FileName, enum file_type type_of_file, uint error_message_number, myf MyFlags)
File my_create (const char *FileName, int CreateFlags, int AccessFlags, myf MyFlags)
int my_close (File Filedes, myf MyFlags)
int my_mkdir (const char *dir, int Flags, myf MyFlags)
int my_readlink (char *to, const char *filename, myf MyFlags)
int my_is_symlink (const char *filename)
int my_realpath (char *to, const char *filename, myf MyFlags)
File my_create_with_symlink (const char *linkname, const char *filename, int createflags, int access_flags, myf MyFlags)
int my_delete_with_symlink (const char *name, myf MyFlags)
int my_rename_with_symlink (const char *from, const char *to, myf MyFlags)
int my_symlink (const char *content, const char *linkname, myf MyFlags)
size_t my_read (File Filedes, uchar *Buffer, size_t Count, myf MyFlags)
size_t my_pread (File Filedes, uchar *Buffer, size_t Count, my_off_t offset, myf MyFlags)
int my_rename (const char *from, const char *to, myf MyFlags)
my_off_t my_seek (File fd, my_off_t pos, int whence, myf MyFlags)
my_off_t my_tell (File fd, myf MyFlags)
size_t my_write (File Filedes, const uchar *Buffer, size_t Count, myf MyFlags)
size_t my_pwrite (File Filedes, const uchar *Buffer, size_t Count, my_off_t offset, myf MyFlags)
size_t my_fread (FILE *stream, uchar *Buffer, size_t Count, myf MyFlags)
size_t my_fwrite (FILE *stream, const uchar *Buffer, size_t Count, myf MyFlags)
my_off_t my_fseek (FILE *stream, my_off_t pos, int whence, myf MyFlags)
my_off_t my_ftell (FILE *stream, myf MyFlags)
void * my_memmem (const void *haystack, size_t haystacklen, const void *needle, size_t needlelen)
int check_if_legal_filename (const char *path)
int check_if_legal_tablename (const char *path)
void init_glob_errs (void)
const char ** get_global_errmsgs ()
void wait_for_free_space (const char *filename, int errors)
FILE * my_fopen (const char *FileName, int Flags, myf MyFlags)
FILE * my_fdopen (File Filedes, const char *name, int Flags, myf MyFlags)
FILE * my_freopen (const char *path, const char *mode, FILE *stream)
int my_fclose (FILE *fd, myf MyFlags)
File my_fileno (FILE *fd)
int my_chsize (File fd, my_off_t newlength, int filler, myf MyFlags)
int my_sync (File fd, myf my_flags)
int my_sync_dir (const char *dir_name, myf my_flags)
int my_sync_dir_by_file (const char *file_name, myf my_flags)
void my_error (int nr, myf MyFlags,...)
void my_printf_error (uint my_err, const char *format, myf MyFlags,...) ATTRIBUTE_FORMAT(printf
void void my_printv_error (uint error, const char *format, myf MyFlags, va_list ap)
int my_error_register (const char **(*get_errmsgs)(), int first, int last)
const char ** my_error_unregister (int first, int last)
void my_message (uint my_err, const char *str, myf MyFlags)
void my_message_stderr (uint my_err, const char *str, myf MyFlags)
my_bool my_basic_init (void)
my_bool my_init (void)
void my_end (int infoflag)
int my_redel (const char *from, const char *to, int MyFlags)
int my_copystat (const char *from, const char *to, int MyFlags)
char * my_filename (File fd)
my_bool init_tmpdir (MY_TMPDIR *tmpdir, const char *pathlist)
char * my_tmpdir (MY_TMPDIR *tmpdir)
void free_tmpdir (MY_TMPDIR *tmpdir)
void my_remember_signal (int signal_number, sig_handler(*func)(int))
size_t dirname_part (char *to, const char *name, size_t *to_res_length)
size_t dirname_length (const char *name)
int test_if_hard_path (const char *dir_name)
my_bool has_path (const char *name)
char * convert_dirname (char *to, const char *from, const char *from_end)
void to_unix_path (char *name)
char * fn_ext (const char *name)
char * fn_same (char *toname, const char *name, int flag)
char * fn_format (char *to, const char *name, const char *dir, const char *form, uint flag)
size_t strlength (const char *str)
void pack_dirname (char *to, const char *from)
size_t normalize_dirname (char *to, const char *from)
size_t unpack_dirname (char *to, const char *from)
size_t cleanup_dirname (char *to, const char *from)
size_t system_filename (char *to, const char *from)
size_t unpack_filename (char *to, const char *from)
char * intern_filename (char *to, const char *from)
char * directory_file_name (char *dst, const char *src)
int pack_filename (char *to, const char *name, size_t max_length)
char * my_path (char *to, const char *progname, const char *own_pathname_part)
char * my_load_path (char *to, const char *path, const char *own_path_prefix)
int wild_compare (const char *str, const char *wildstr, pbool str_is_pattern)
my_bool array_append_string_unique (const char *str, const char **array, size_t size)
void get_date (char *to, int timeflag, time_t use_time)
void soundex (CHARSET_INFO *, char *out_pntr, char *in_pntr, pbool remove_garbage)
int init_record_cache (RECORD_CACHE *info, size_t cachesize, File file, size_t reclength, enum cache_type type, pbool use_async_io)
int read_cache_record (RECORD_CACHE *info, uchar *to)
int end_record_cache (RECORD_CACHE *info)
int write_cache_record (RECORD_CACHE *info, my_off_t filepos, const uchar *record, size_t length)
int flush_write_cache (RECORD_CACHE *info)
void handle_recived_signals (void)
sig_handler my_set_alarm_variable (int signo)
void my_string_ptr_sort (uchar *base, uint items, size_t size)
void radixsort_for_str_ptr (uchar *base[], uint number_of_elements, size_t size_of_element, uchar *buffer[])
qsort_t my_qsort (void *base_ptr, size_t total_elems, size_t size, qsort_cmp cmp)
qsort_t my_qsort2 (void *base_ptr, size_t total_elems, size_t size, qsort2_cmp cmp, void *cmp_argument)
qsort2_cmp get_ptr_compare (size_t)
void my_store_ptr (uchar *buff, size_t pack_length, my_off_t pos)
my_off_t my_get_ptr (uchar *ptr, size_t pack_length)
int init_io_cache (IO_CACHE *info, File file, size_t cachesize, enum cache_type type, my_off_t seek_offset, pbool use_async_io, myf cache_myflags)
my_bool reinit_io_cache (IO_CACHE *info, enum cache_type type, my_off_t seek_offset, pbool use_async_io, pbool clear_cache)
void setup_io_cache (IO_CACHE *info)
int _my_b_read (IO_CACHE *info, uchar *Buffer, size_t Count)
int _my_b_read_r (IO_CACHE *info, uchar *Buffer, size_t Count)
void init_io_cache_share (IO_CACHE *read_cache, IO_CACHE_SHARE *cshare, IO_CACHE *write_cache, uint num_threads)
void remove_io_thread (IO_CACHE *info)
int _my_b_seq_read (IO_CACHE *info, uchar *Buffer, size_t Count)
int _my_b_net_read (IO_CACHE *info, uchar *Buffer, size_t Count)
int _my_b_get (IO_CACHE *info)
int _my_b_async_read (IO_CACHE *info, uchar *Buffer, size_t Count)
int _my_b_write (IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_b_append (IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_b_safe_write (IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_block_write (IO_CACHE *info, const uchar *Buffer, size_t Count, my_off_t pos)
int my_b_flush_io_cache (IO_CACHE *info, int need_append_buffer_lock)
int end_io_cache (IO_CACHE *info)
size_t my_b_fill (IO_CACHE *info)
void my_b_seek (IO_CACHE *info, my_off_t pos)
size_t my_b_gets (IO_CACHE *info, char *to, size_t max_length)
my_off_t my_b_filelength (IO_CACHE *info)
size_t my_b_printf (IO_CACHE *info, const char *fmt,...)
size_t my_b_vprintf (IO_CACHE *info, const char *fmt, va_list ap)
my_bool open_cached_file (IO_CACHE *cache, const char *dir, const char *prefix, size_t cache_size, myf cache_myflags)
my_bool real_open_cached_file (IO_CACHE *cache)
void close_cached_file (IO_CACHE *cache)
File create_temp_file (char *to, const char *dir, const char *pfx, int mode, myf MyFlags)
my_bool init_dynamic_array2 (DYNAMIC_ARRAY *array, uint element_size, void *init_buffer, uint init_alloc, uint alloc_increment)
my_bool init_dynamic_array (DYNAMIC_ARRAY *array, uint element_size, uint init_alloc, uint alloc_increment)
my_bool insert_dynamic (DYNAMIC_ARRAY *array, uchar *element)
uchar * alloc_dynamic (DYNAMIC_ARRAY *array)
uchar * pop_dynamic (DYNAMIC_ARRAY *)
my_bool set_dynamic (DYNAMIC_ARRAY *array, uchar *element, uint array_index)
my_bool allocate_dynamic (DYNAMIC_ARRAY *array, uint max_elements)
void get_dynamic (DYNAMIC_ARRAY *array, uchar *element, uint array_index)
void delete_dynamic (DYNAMIC_ARRAY *array)
void delete_dynamic_element (DYNAMIC_ARRAY *array, uint array_index)
void freeze_size (DYNAMIC_ARRAY *array)
int get_index_dynamic (DYNAMIC_ARRAY *array, uchar *element)
my_bool init_dynamic_string (DYNAMIC_STRING *str, const char *init_str, size_t init_alloc, size_t alloc_increment)
my_bool dynstr_append (DYNAMIC_STRING *str, const char *append)
my_bool dynstr_append_mem (DYNAMIC_STRING *str, const char *append, size_t length)
my_bool dynstr_append_os_quoted (DYNAMIC_STRING *str, const char *append,...)
my_bool dynstr_set (DYNAMIC_STRING *str, const char *init_str)
my_bool dynstr_realloc (DYNAMIC_STRING *str, size_t additional_size)
my_bool dynstr_trunc (DYNAMIC_STRING *str, size_t n)
void dynstr_free (DYNAMIC_STRING *str)
void init_alloc_root (MEM_ROOT *mem_root, size_t block_size, size_t pre_alloc_size)
void * alloc_root (MEM_ROOT *mem_root, size_t Size)
void * multi_alloc_root (MEM_ROOT *mem_root,...)
void free_root (MEM_ROOT *root, myf MyFLAGS)
void set_prealloc_root (MEM_ROOT *root, char *ptr)
void reset_root_defaults (MEM_ROOT *mem_root, size_t block_size, size_t prealloc_size)
char * strdup_root (MEM_ROOT *root, const char *str)
static char * safe_strdup_root (MEM_ROOT *root, const char *str)
char * strmake_root (MEM_ROOT *root, const char *str, size_t len)
void * memdup_root (MEM_ROOT *root, const void *str, size_t len)
int get_defaults_options (int argc, char **argv, char **defaults, char **extra_defaults, char **group_suffix)
int my_load_defaults (const char *conf_file, const char **groups, int *argc, char ***argv, const char ***)
int load_defaults (const char *conf_file, const char **groups, int *argc, char ***argv)
int my_search_option_files (const char *conf_file, int *argc, char ***argv, uint *args_used, Process_option_func func, void *func_ctx, const char **default_directories)
void free_defaults (char **argv)
void my_print_default_files (const char *conf_file)
void print_defaults (const char *conf_file, const char **groups)
my_bool my_compress (uchar *, size_t *, size_t *)
my_bool my_uncompress (uchar *, size_t, size_t *)
uchar * my_compress_alloc (const uchar *packet, size_t *len, size_t *complen)
int packfrm (uchar *, size_t, uchar **, size_t *)
int unpackfrm (uchar **, size_t *, const uchar *)
ha_checksum my_checksum (ha_checksum crc, const uchar *mem, size_t count)
void my_sleep (ulong m_seconds)
ulong crc32 (ulong crc, const uchar *buf, uint len)
uint my_set_max_open_files (uint files)
void my_free_open_file_info (void)
time_t my_time (myf flags)
ulonglong my_getsystime (void)
ulonglong my_micro_time ()
ulonglong my_micro_time_and_time (time_t *time_arg)
time_t my_time_possible_from_micro (ulonglong microtime)
my_bool my_gethwaddr (uchar *to)
int my_getncpus ()
void * my_mmap (void *, size_t, int, int, int, my_off_t)
int my_munmap (void *, size_t)
int my_getpagesize (void)
int my_msync (int, void *, size_t, int)
uint get_charset_number (const char *cs_name, uint cs_flags)
uint get_collation_number (const char *name)
const char * get_charset_name (uint cs_number)
CHARSET_INFO * get_charset (uint cs_number, myf flags)
CHARSET_INFO * get_charset_by_name (const char *cs_name, myf flags)
CHARSET_INFO * get_charset_by_csname (const char *cs_name, uint cs_flags, myf my_flags)
my_bool resolve_charset (const char *cs_name, CHARSET_INFO *default_cs, CHARSET_INFO **cs)
my_bool resolve_collation (const char *cl_name, CHARSET_INFO *default_cl, CHARSET_INFO **cl)
void free_charsets (void)
char * get_charsets_dir (char *buf)
my_bool my_charset_same (CHARSET_INFO *cs1, CHARSET_INFO *cs2)
my_bool init_compiled_charsets (myf flags)
void add_compiled_collation (CHARSET_INFO *cs)
size_t escape_string_for_mysql (CHARSET_INFO *charset_info, char *to, size_t to_length, const char *from, size_t length)
size_t escape_quotes_for_mysql (CHARSET_INFO *charset_info, char *to, size_t to_length, const char *from, size_t length)
void thd_increment_bytes_sent (ulong length)
void thd_increment_bytes_received (ulong length)
void thd_increment_net_big_packet_count (ulong length)
Variables
int errno
char * home_dir
const char * my_progname
char curr_dir []
void(* error_handler_hook)(uint my_err, const char *str, myf MyFlags)
void(* fatal_error_handler_hook)(uint my_err, const char *str, myf MyFlags)
uint my_file_limit
ulong my_thread_stack_size
const char *(* proc_info_hook)(void *, const char *, const char *, const char *, const unsigned int)
MYSQL_PLUGIN_IMPORT CHARSET_INFO * default_charset_info
MYSQL_PLUGIN_IMPORT CHARSET_INFO * all_charsets [MY_ALL_CHARSETS_SIZE]
CHARSET_INFO compiled_charsets []
ulong my_file_opened
ulong my_stream_opened
ulong my_tmp_file_created
ulong my_file_total_opened
uint mysys_usage_id
my_bool my_init_done
void(* my_sigtstp_cleanup)(void)
void(*)(*) my_sigtstp_restart (void)
void(*)(*)(*) my_abort_hook (int)
MYSQL_PLUGIN_IMPORT int my_umask
int my_umask_dir
int my_recived_signals
int my_safe_to_handle_signal
int my_dont_interrupt
my_bool my_use_symdir
ulong my_default_record_cache_size
my_bool my_disable_locking
my_bool my_disable_async_io
my_bool my_disable_flush_key_blocks
my_bool my_disable_symlinks
char wild_many
char wild_one
char wild_prefix
const char * charsets_dir
const char * my_defaults_extra_file
const char * my_defaults_group_suffix
const char * my_defaults_file
my_bool timed_mutexes
struct st_my_file_info * my_file_info
const char * args_separator
struct st_mysql_file * mysql_stdin
Macro Definition Documentation
alloc_root_inited
#define alloc_root_inited (A) ((A)->min_malloc != 0)
Definition at line 799 of file my_sys.h.
ALLOC_ROOT_MIN_BLOCK_SIZE
#define ALLOC_ROOT_MIN_BLOCK_SIZE (MALLOC_OVERHEAD + sizeof(USED_MEM) + 8)
Definition at line 800 of file my_sys.h.
base_name
#define base_name (A) (A+dirname_length(A))
Definition at line 664 of file my_sys.h.
clear_alloc_root
#define clear_alloc_root (A) do { (A)->free= (A)->used= (A)->pre_alloc= 0; (A)->min_malloc=0;} while(0)
Definition at line 801 of file my_sys.h.
DEBUG_SYNC_C
#define DEBUG_SYNC_C (_sync_point_name_)
Definition at line 169 of file my_sys.h.
DFLT_INIT_HITS
#define DFLT_INIT_HITS 3
Definition at line 135 of file my_sys.h.
dynamic_array_ptr
#define dynamic_array_ptr (array, array_index) ((array)->buffer+(array_index)*(array)->size_of_element)
Definition at line 775 of file my_sys.h.
dynamic_element
#define dynamic_element (array, array_index, type) ((type)((array)->buffer) +(array_index))
Definition at line 776 of file my_sys.h.
flush_io_cache
#define flush_io_cache (info) my_b_flush_io_cache((info),1)
Definition at line 739 of file my_sys.h.
GETDATE_DATE_TIME
#define GETDATE_DATE_TIME 1
Definition at line 146 of file my_sys.h.
GETDATE_FIXEDLENGTH
#define GETDATE_FIXEDLENGTH 16
Definition at line 150 of file my_sys.h.
GETDATE_GMT
#define GETDATE_GMT 8
Definition at line 149 of file my_sys.h.
GETDATE_HHMMSSTIME
#define GETDATE_HHMMSSTIME 4
Definition at line 148 of file my_sys.h.
GETDATE_SHORT_DATE
#define GETDATE_SHORT_DATE 2
Definition at line 147 of file my_sys.h.
HAVE_MMAP
#define HAVE_MMAP
Definition at line 882 of file my_sys.h.
MAP_FAILED
#define MAP_FAILED ((void *)-1)
Definition at line 879 of file my_sys.h.
MAP_NORESERVE
#define MAP_NORESERVE 0
Definition at line 875 of file my_sys.h.
MAP_NOSYNC
#define MAP_NOSYNC 0x0800
Definition at line 878 of file my_sys.h.
MAP_PRIVATE
#define MAP_PRIVATE 0x0002
Definition at line 877 of file my_sys.h.
MAP_SHARED
#define MAP_SHARED 0x0001
Definition at line 876 of file my_sys.h.
ME_BELL
#define ME_BELL 4 /* Ring bell then printing message */
Definition at line 103 of file my_sys.h.
ME_COLOUR1
#define ME_COLOUR1 ((1 << ME_HIGHBYTE)) /* Possibly error-colours */
Definition at line 109 of file my_sys.h.
ME_COLOUR2
#define ME_COLOUR2 ((2 << ME_HIGHBYTE))
Definition at line 110 of file my_sys.h.
ME_COLOUR3
#define ME_COLOUR3 ((3 << ME_HIGHBYTE))
Definition at line 111 of file my_sys.h.
ME_FATALERROR
#define ME_FATALERROR 1024 /* Fatal statement error */
Definition at line 112 of file my_sys.h.
ME_HIGHBYTE
#define ME_HIGHBYTE 8 /* Shift for colours */
Definition at line 100 of file my_sys.h.
ME_HOLDTANG
#define ME_HOLDTANG 8 /* Don't delete last keys */
Definition at line 104 of file my_sys.h.
ME_NOCUR
#define ME_NOCUR 1 /* Don't use curses message */
Definition at line 101 of file my_sys.h.
ME_NOINPUT
#define ME_NOINPUT 128 /* Dont use the input libary */
Definition at line 108 of file my_sys.h.
ME_NOREFRESH
#define ME_NOREFRESH 64 /* Dont refresh screen */
Definition at line 107 of file my_sys.h.
ME_OLDWIN
#define ME_OLDWIN 2 /* Use old window */
Definition at line 102 of file my_sys.h.
ME_WAITTANG
#define ME_WAITTANG 32 /* Wait for a user action */
Definition at line 106 of file my_sys.h.
ME_WAITTOT
#define ME_WAITTOT 16 /* Wait for errtime secs of for a action */
Definition at line 105 of file my_sys.h.
MEM_CHECK_ADDRESSABLE
#define MEM_CHECK_ADDRESSABLE (a, len) ((void) 0)
Definition at line 40 of file my_sys.h.
MEM_CHECK_DEFINED
#define MEM_CHECK_DEFINED (a, len) ((void) 0)
Definition at line 41 of file my_sys.h.
MEM_NOACCESS
#define MEM_NOACCESS (a, len) ((void) 0)
Definition at line 39 of file my_sys.h.
MEM_UNDEFINED
#define MEM_UNDEFINED (a, len) ((void) 0)
Definition at line 38 of file my_sys.h.
MIN_COMPRESS_LENGTH
#define MIN_COMPRESS_LENGTH 50 /* Don't compress small bl. */
Definition at line 134 of file my_sys.h.
MS_SYNC
#define MS_SYNC 0x0000
Definition at line 880 of file my_sys.h.
my_access
#define my_access access
Definition at line 602 of file my_sys.h.
my_afree
#define my_afree (PTR) my_free(PTR)
Definition at line 197 of file my_sys.h.
MY_ALL_CHARSETS_SIZE
#define MY_ALL_CHARSETS_SIZE 2048
Definition at line 225 of file my_sys.h.
my_alloca
#define my_alloca (SZ) my_malloc(SZ,MYF(MY_FAE))
Definition at line 196 of file my_sys.h.
MY_ALLOW_ZERO_PTR
#define MY_ALLOW_ZERO_PTR 64 /* my_realloc() ; zero ptr -> malloc */
Definition at line 89 of file my_sys.h.
MY_APPEND_EXT
#define MY_APPEND_EXT 256 /* add 'ext' as additional extension*/
Definition at line 123 of file my_sys.h.
my_b_bytes_in_cache
#define my_b_bytes_in_cache (info)
Value:
                      (size_t) (*(info)->current_end - \
                      *(info)->current_pos)
Definition at line 538 of file my_sys.h.
my_b_clear
#define my_b_clear (info) (info)->buffer=0
Definition at line 495 of file my_sys.h.
my_b_EOF
#define my_b_EOF INT_MIN
Definition at line 497 of file my_sys.h.
my_b_fill_cache
#define my_b_fill_cache (info) (((info)->read_end=(info)->read_pos),(*(info)->read_function)(info,0,0))
Definition at line 522 of file my_sys.h.
my_b_get
#define my_b_get (info)
Value:
  ((info)->read_pos != (info)->read_end ?\
   ((info)->read_pos++, (int) (uchar) (info)->read_pos[-1]) :\
   _my_b_get(info))
Definition at line 511 of file my_sys.h.
my_b_get_buffer_start
#define my_b_get_buffer_start (info) (info)->request_pos
Definition at line 528 of file my_sys.h.
my_b_get_bytes_in_buffer
#define my_b_get_bytes_in_buffer (info)
Value:
  (char*) (info)->read_end -   \
  (char*) my_b_get_buffer_start(info)
Definition at line 529 of file my_sys.h.
my_b_get_pos_in_file
#define my_b_get_pos_in_file (info) (info)->pos_in_file
Definition at line 531 of file my_sys.h.
my_b_inited
#define my_b_inited (info) (info)->buffer
Definition at line 496 of file my_sys.h.
my_b_read
#define my_b_read (info, Buffer, Count)
Value:
  ((info)->read_pos + (Count) <= (info)->read_end ?\
   (memcpy(Buffer,(info)->read_pos,(size_t) (Count)), \
    ((info)->read_pos+=(Count)),0) :\
   (*(info)->read_function)((info),Buffer,Count))
Definition at line 499 of file my_sys.h.
my_b_tell
#define my_b_tell (info)
Value:
             ((info)->pos_in_file + \
             (size_t) (*(info)->current_pos - (info)->request_pos))
Definition at line 525 of file my_sys.h.
my_b_write
#define my_b_write (info, Buffer, Count)
Value:
 ((info)->write_pos + (Count) <=(info)->write_end ?\
  (memcpy((info)->write_pos, (Buffer), (size_t)(Count)),\
   ((info)->write_pos+=(Count)),0) : \
   (*(info)->write_function)((info),(uchar *)(Buffer),(Count)))
Definition at line 505 of file my_sys.h.
my_b_write_byte
#define my_b_write_byte (info, chr)
Value:
  (((info)->write_pos < (info)->write_end) ?\
   ((*(info)->write_pos++)=(chr)) :\
   (_my_b_write(info,0,0) , ((*(info)->write_pos++)=(chr))))
Definition at line 517 of file my_sys.h.
MY_CHECK_ERROR
#define MY_CHECK_ERROR 1 /* Params to my_end; Check open-close */
Definition at line 96 of file my_sys.h.
MY_COPYTIME
#define MY_COPYTIME 64 /* my_redel() copys time */
Definition at line 81 of file my_sys.h.
my_delete_allow_opened
#define my_delete_allow_opened (fname, flags) my_delete((fname),(flags))
Definition at line 612 of file my_sys.h.
MY_DELETE_OLD
#define MY_DELETE_OLD 256 /* my_create_with_symlink() */
Definition at line 82 of file my_sys.h.
MY_DONT_CHECK_FILESIZE
#define MY_DONT_CHECK_FILESIZE 128 /* Option to init_io_cache() */
Definition at line 79 of file my_sys.h.
MY_DONT_FREE_DBUG
#define MY_DONT_FREE_DBUG 4 /* Do not call DBUG_END() in my_end() */
Definition at line 98 of file my_sys.h.
MY_DONT_OVERWRITE_FILE
#define MY_DONT_OVERWRITE_FILE 1024 /* my_copy: Don't overwrite file */
Definition at line 92 of file my_sys.h.
MY_DONT_WAIT
#define MY_DONT_WAIT 64 /* my_lock() don't wait if can't lock */
Definition at line 87 of file my_sys.h.
MY_ERRNO_EDOM
#define MY_ERRNO_EDOM 33
Definition at line 142 of file my_sys.h.
MY_ERRNO_ERANGE
#define MY_ERRNO_ERANGE 34
Definition at line 143 of file my_sys.h.
MY_FAE
#define MY_FAE 8 /* Fatal if any error */
Definition at line 72 of file my_sys.h.
MY_FFNF
#define MY_FFNF 1 /* Fatal if file not found */
Definition at line 69 of file my_sys.h.
MY_FILE_ERROR
#define MY_FILE_ERROR ((size_t) -1)
Definition at line 66 of file my_sys.h.
MY_FNABP
#define MY_FNABP 2 /* Fatal if not all bytes read/writen */
Definition at line 70 of file my_sys.h.
my_free_lock
#define my_free_lock (A) my_free((A))
Definition at line 797 of file my_sys.h.
MY_FREE_ON_ERROR
#define MY_FREE_ON_ERROR 128 /* my_realloc() ; Free old ptr on error */
Definition at line 90 of file my_sys.h.
MY_FULL_IO
#define MY_FULL_IO 512 /* For my_read - loop intil I/O is complete */
Definition at line 78 of file my_sys.h.
my_get_large_page_size
#define my_get_large_page_size () (0)
Definition at line 177 of file my_sys.h.
MY_GIVE_INFO
#define MY_GIVE_INFO 2 /* Give time info about process*/
Definition at line 97 of file my_sys.h.
MY_HOLD_ON_ERROR
#define MY_HOLD_ON_ERROR 256 /* my_realloc() ; Return old ptr on error */
Definition at line 91 of file my_sys.h.
MY_HOLD_ORIGINAL_MODES
#define MY_HOLD_ORIGINAL_MODES 128 /* my_copy() holds to file modes */
Definition at line 84 of file my_sys.h.
MY_IGNORE_BADFD
#define MY_IGNORE_BADFD 32 /* my_sync: ignore 'bad descriptor' errors */
Definition at line 75 of file my_sys.h.
MY_INIT
#define MY_INIT (name) { my_progname= name; my_init(); }
Definition at line 53 of file my_sys.h.
my_init_dynamic_array
#define my_init_dynamic_array (A, B, C, D) init_dynamic_array2(A,B,NULL,C,D)
Definition at line 755 of file my_sys.h.
my_init_dynamic_array2
#define my_init_dynamic_array2 (A, B, C, D, E) init_dynamic_array2(A,B,C,D,E)
Definition at line 757 of file my_sys.h.
my_init_dynamic_array2_ci
#define my_init_dynamic_array2_ci (A, B, C, D, E) init_dynamic_array2(A,B,C,D,E)
Definition at line 758 of file my_sys.h.
my_init_dynamic_array_ci
#define my_init_dynamic_array_ci (A, B, C, D) init_dynamic_array2(A,B,NULL,C,D)
Definition at line 756 of file my_sys.h.
MY_KEEP_PREALLOC
#define MY_KEEP_PREALLOC 1
Definition at line 138 of file my_sys.h.
my_large_free
#define my_large_free (A) my_free_lock((A))
Definition at line 179 of file my_sys.h.
my_large_malloc
#define my_large_malloc (A, B) my_malloc_lock((A),(B))
Definition at line 178 of file my_sys.h.
MY_LINK_WARNING
#define MY_LINK_WARNING 32 /* my_redel() gives warning if links */
Definition at line 80 of file my_sys.h.
my_malloc_lock
#define my_malloc_lock (A, B) my_malloc((A),(B))
Definition at line 796 of file my_sys.h.
MY_MARK_BLOCKS_FREE
#define MY_MARK_BLOCKS_FREE 2 /* move used to free list and reuse them */
Definition at line 139 of file my_sys.h.
MY_NABP
#define MY_NABP 4 /* Error if not all bytes read/writen */
Definition at line 71 of file my_sys.h.
MY_PACK_FILENAME
#define MY_PACK_FILENAME 8 /* Pack name (home -> ~) */
Definition at line 118 of file my_sys.h.
my_print_open_files
#define my_print_open_files ()
Definition at line 654 of file my_sys.h.
MY_REDEL_MAKE_BACKUP
#define MY_REDEL_MAKE_BACKUP 256
Definition at line 85 of file my_sys.h.
MY_RELATIVE_PATH
#define MY_RELATIVE_PATH 128 /* name is relative to 'dir' */
Definition at line 122 of file my_sys.h.
MY_REPLACE_DIR
#define MY_REPLACE_DIR 1 /* replace dir in name with 'dir' */
Definition at line 115 of file my_sys.h.
MY_REPLACE_EXT
#define MY_REPLACE_EXT 2 /* replace extension with 'ext' */
Definition at line 116 of file my_sys.h.
MY_RESOLVE_LINK
#define MY_RESOLVE_LINK 128 /* my_realpath(); Only resolve links */
Definition at line 83 of file my_sys.h.
MY_RESOLVE_SYMLINKS
#define MY_RESOLVE_SYMLINKS 16 /* Resolve all symbolic links */
Definition at line 119 of file my_sys.h.
MY_RETURN_REAL_PATH
#define MY_RETURN_REAL_PATH 32 /* return full path for file */
Definition at line 120 of file my_sys.h.
MY_SAFE_PATH
#define MY_SAFE_PATH 64 /* Return NULL if too long path */
Definition at line 121 of file my_sys.h.
MY_SEEK_CUR
#define MY_SEEK_CUR 1
Definition at line 128 of file my_sys.h.
MY_SEEK_END
#define MY_SEEK_END 2
Definition at line 129 of file my_sys.h.
MY_SEEK_NOT_DONE
#define MY_SEEK_NOT_DONE 32 /* my_lock may have to do a seek */
Definition at line 86 of file my_sys.h.
MY_SEEK_SET
#define MY_SEEK_SET 0
Definition at line 127 of file my_sys.h.
MY_SYNC
#define MY_SYNC 4096 /* my_copy(): sync dst file */
Definition at line 94 of file my_sys.h.
MY_SYNC_DIR
#define MY_SYNC_DIR 8192 /* my_create/delete/rename: sync directory */
Definition at line 76 of file my_sys.h.
MY_THREADSAFE
#define MY_THREADSAFE 2048 /* my_seek(): lock fd mutex */
Definition at line 93 of file my_sys.h.
MY_UNPACK_FILENAME
#define MY_UNPACK_FILENAME 4 /* Unpack name (~ -> home) */
Definition at line 117 of file my_sys.h.
MY_UNUSED
#define MY_UNUSED 64 /* Unused (was support for RAID) */
Definition at line 77 of file my_sys.h.
MY_WAIT_FOR_USER_TO_FIX_PANIC
#define MY_WAIT_FOR_USER_TO_FIX_PANIC 60 /* in seconds */
Definition at line 132 of file my_sys.h.
MY_WAIT_GIVE_USER_A_MESSAGE
#define MY_WAIT_GIVE_USER_A_MESSAGE 10 /* Every 10 times of prev */
Definition at line 133 of file my_sys.h.
MY_WAIT_IF_FULL
#define MY_WAIT_IF_FULL 32 /* Wait and try again if disk full error */
Definition at line 74 of file my_sys.h.
MY_WME
#define MY_WME 16 /* Write message on error */
Definition at line 73 of file my_sys.h.
MY_ZEROFILL
#define MY_ZEROFILL 32 /* my_malloc(), fill array with zero */
Definition at line 88 of file my_sys.h.
MYSYS_ERRMSG_SIZE
#define MYSYS_ERRMSG_SIZE (512)
Max length of an error message generated by mysys utilities. Some mysys functions produce error messages. These mostly go to stderr. This constant defines the size of the buffer used to format the message. It should be kept in sync with MYSQL_ERRMSG_SIZE, since sometimes mysys errors are stored in the server diagnostics area, and we would like to avoid unexpected truncation.
Definition at line 64 of file my_sys.h.
PROT_READ
#define PROT_READ 1
Definition at line 873 of file my_sys.h.
PROT_WRITE
#define PROT_WRITE 2
Definition at line 874 of file my_sys.h.
push_dynamic
#define push_dynamic (A, B) insert_dynamic((A),(B))
Definition at line 777 of file my_sys.h.
reset_dynamic
#define reset_dynamic (array) ((array)->elements= 0)
Definition at line 778 of file my_sys.h.
sort_dynamic
#define sort_dynamic (A, cmp) my_qsort((A)->buffer, (A)->elements, (A)->size_of_element, (cmp))
Definition at line 779 of file my_sys.h.
TRASH
#define TRASH (A, B) do{MEM_CHECK_ADDRESSABLE(A,B);MEM_UNDEFINED(A,B);} while (0)
Definition at line 161 of file my_sys.h.
Typedef Documentation
DYNAMIC_ARRAY
typedef struct st_dynamic_array DYNAMIC_ARRAY
DYNAMIC_STRING
typedef struct st_dynamic_string DYNAMIC_STRING
ha_checksum
typedef uint32 ha_checksum
Definition at line 541 of file my_sys.h.
IO_CACHE
typedef struct st_io_cache IO_CACHE
IO_CACHE_CALLBACK
typedef int(* IO_CACHE_CALLBACK) (struct st_io_cache *)
Definition at line 343 of file my_sys.h.
IO_CACHE_SHARE
typedef struct st_io_cache_share IO_CACHE_SHARE
MY_TMPDIR
typedef struct st_my_tmpdir MY_TMPDIR
Process_option_func
typedef int(* Process_option_func) (void *ctx, const char *group_name, const char *option)
Definition at line 544 of file my_sys.h.
qsort2_cmp
typedef int(* qsort2_cmp) (const void *, const void *, const void *)
Definition at line 490 of file my_sys.h.
RECORD_CACHE
typedef struct st_record_cache RECORD_CACHE
Enumeration Type Documentation
cache_type
enum cache_type
Enumerator
TYPE_NOT_SET
READ_CACHE
WRITE_CACHE
SEQ_READ_APPEND
READ_FIFO
READ_NET
WRITE_NET
Definition at line 267 of file my_sys.h.
 {
   TYPE_NOT_SET= 0, READ_CACHE, WRITE_CACHE,
   SEQ_READ_APPEND       /* sequential read or append */,
   READ_FIFO, READ_NET,WRITE_NET};
file_type
enum file_type
Enumerator
UNOPEN
FILE_BY_OPEN
FILE_BY_CREATE
STREAM_BY_FOPEN
STREAM_BY_FDOPEN
FILE_BY_MKSTEMP
FILE_BY_DUP
Definition at line 299 of file my_sys.h.
 {
   UNOPEN = 0, FILE_BY_OPEN, FILE_BY_CREATE, STREAM_BY_FOPEN, STREAM_BY_FDOPEN,
   FILE_BY_MKSTEMP, FILE_BY_DUP
 };
flush_type
enum flush_type
Enumerator
FLUSH_KEEP
FLUSH_RELEASE
FLUSH_IGNORE_CHANGED
FLUSH_FORCE_WRITE
Definition at line 273 of file my_sys.h.
 {
   FLUSH_KEEP,           /* flush block and keep it in the cache */
   FLUSH_RELEASE,        /* flush block and remove it from the cache */
   FLUSH_IGNORE_CHANGED, /* remove block from the cache */
   /*
     As my_disable_flush_pagecache_blocks is always 0, the following option
     is strictly equivalent to FLUSH_KEEP
   */
   FLUSH_FORCE_WRITE
 };
loglevel
enum loglevel
Enumerator
ERROR_LEVEL
WARNING_LEVEL
INFORMATION_LEVEL
Definition at line 261 of file my_sys.h.
               {
    ERROR_LEVEL,
    WARNING_LEVEL,
    INFORMATION_LEVEL
 };
Function Documentation
_my_b_async_read()
int _my_b_async_read (IO_CACHE * info, uchar * Buffer, size_t Count)
Referenced by init_io_cache(), and reinit_io_cache().
_my_b_get()
int _my_b_get (IO_CACHE * info)
Definition at line 1505 of file mf_iocache.c.
 {
   uchar buff;
   IO_CACHE_CALLBACK pre_read,post_read;
   if ((pre_read = info->pre_read))
     (*pre_read)(info);
   if ((*(info)->read_function)(info,&buff,1))
     return my_b_EOF;
   if ((post_read = info->post_read))
     (*post_read)(info);
   return (int) (uchar) buff;
 }
References my_b_EOF, st_io_cache::post_read, and st_io_cache::pre_read.
_my_b_net_read()
int _my_b_net_read (IO_CACHE * info, uchar * Buffer, size_t Count)
_my_b_read()
int _my_b_read (IO_CACHE * info, uchar * Buffer, size_t Count)
_my_b_read_r()
int _my_b_read_r (IO_CACHE * info, uchar * Buffer, size_t Count)
_my_b_seq_read()
int _my_b_seq_read (IO_CACHE * info, uchar * Buffer, size_t Count)
_my_b_write()
int _my_b_write (IO_CACHE * info, const uchar * Buffer, size_t Count)
add_compiled_collation()
void add_compiled_collation (CHARSET_INFO * cs)
Definition at line 420 of file charset.c.
 {
   all_charsets[cs->number]= cs;
   cs->state|= MY_CS_AVAILABLE;
 }
References all_charsets, MY_CS_AVAILABLE, charset_info_st::number, and charset_info_st::state.
Referenced by init_compiled_charsets().
alloc_dynamic()
uchar* alloc_dynamic (DYNAMIC_ARRAY * array)
Definition at line 130 of file array.c.
 {
   if (array->elements == array->max_element)
   {
     char *new_ptr;
     if (array->buffer == (uchar *)(array + 1))
     {
       /*
         In this senerio, the buffer is statically preallocated,
         so we have to create an all-new malloc since we overflowed
       */
       if (!(new_ptr= (char *) my_malloc((array->max_element+
                                          array->alloc_increment) *
                                         array->size_of_element,
                                         MYF(MY_WME))))
         return 0;
       memcpy(new_ptr, array->buffer,
              array->elements * array->size_of_element);
     }
     else
     if (!(new_ptr=(char*) my_realloc(array->buffer,(array->max_element+
                                      array->alloc_increment)*
                                      array->size_of_element,
                                      MYF(MY_WME | MY_ALLOW_ZERO_PTR))))
       return 0;
     array->buffer= (uchar*) new_ptr;
     array->max_element+=array->alloc_increment;
   }
   return array->buffer+(array->elements++ * array->size_of_element);
 }
References array, memcpy, MY_ALLOW_ZERO_PTR, my_malloc(), my_realloc(), MY_WME, MYF, and LF_DYNARRAY::size_of_element.
Referenced by insert_dynamic(), and my_hash_insert().
alloc_root()
void* alloc_root (MEM_ROOT * mem_root, size_t Size)
Definition at line 148 of file my_alloc.c.
 {
 #if defined(HAVE_purify) && defined(EXTRA_DEBUG)
   reg1 USED_MEM *next;
   DBUG_ENTER("alloc_root");
   DBUG_PRINT("enter",("root: 0x%lx", (long) mem_root));
   DBUG_ASSERT(alloc_root_inited(mem_root));
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     if (mem_root->error_handler)
                       (*mem_root->error_handler)();
                     DBUG_SET("-d,simulate_out_of_memory");
                     DBUG_RETURN((void*) 0); /* purecov: inspected */
                   });
   length+=ALIGN_SIZE(sizeof(USED_MEM));
   if (!(next = (USED_MEM*) my_malloc(length,MYF(MY_WME | ME_FATALERROR))))
   {
     if (mem_root->error_handler)
       (*mem_root->error_handler)();
     DBUG_RETURN((uchar*) 0);            /* purecov: inspected */
   }
   next->next= mem_root->used;
   next->size= length;
   mem_root->used= next;
   DBUG_PRINT("exit",("ptr: 0x%lx", (long) (((char*) next)+
                                            ALIGN_SIZE(sizeof(USED_MEM)))));
   DBUG_RETURN((uchar*) (((char*) next)+ALIGN_SIZE(sizeof(USED_MEM))));
 #else
   size_t get_size, block_size;
   uchar* point;
   reg1 USED_MEM *next= 0;
   reg2 USED_MEM **prev;
   DBUG_ENTER("alloc_root");
   DBUG_PRINT("enter",("root: 0x%lx", (long) mem_root));
   DBUG_ASSERT(alloc_root_inited(mem_root));
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     /* Avoid reusing an already allocated block */
                     if (mem_root->error_handler)
                       (*mem_root->error_handler)();
                     DBUG_SET("-d,simulate_out_of_memory");
                     DBUG_RETURN((void*) 0); /* purecov: inspected */
                   });
   length= ALIGN_SIZE(length);
   if ((*(prev= &mem_root->free)) != NULL)
   {
     if ((*prev)->left < length &&
     mem_root->first_block_usage++ >= ALLOC_MAX_BLOCK_USAGE_BEFORE_DROP &&
     (*prev)->left < ALLOC_MAX_BLOCK_TO_DROP)
     {
       next= *prev;
       *prev= next->next;            /* Remove block from list */
       next->next= mem_root->used;
       mem_root->used= next;
       mem_root->first_block_usage= 0;
     }
     for (next= *prev ; next && next->left < length ; next= next->next)
       prev= &next->next;
   }
   if (! next)
   {                     /* Time to alloc new block */
     block_size= mem_root->block_size * (mem_root->block_num >> 2);
     get_size= length+ALIGN_SIZE(sizeof(USED_MEM));
     get_size= max(get_size, block_size);
     if (!(next = (USED_MEM*) my_malloc(get_size,MYF(MY_WME | ME_FATALERROR))))
     {
       if (mem_root->error_handler)
     (*mem_root->error_handler)();
       DBUG_RETURN((void*) 0);                      /* purecov: inspected */
     }
     mem_root->block_num++;
     next->next= *prev;
     next->size= get_size;
     next->left= get_size-ALIGN_SIZE(sizeof(USED_MEM));
     *prev=next;
   }
   point= (uchar*) ((char*) next+ (next->size-next->left));
   /*TODO: next part may be unneded due to mem_root->first_block_usage counter*/
   if ((next->left-= length) < mem_root->min_malloc)
   {                     /* Full block */
     *prev= next->next;              /* Remove block from list */
     next->next= mem_root->used;
     mem_root->used= next;
     mem_root->first_block_usage= 0;
   }
   DBUG_PRINT("exit",("ptr: 0x%lx", (ulong) point));
   DBUG_RETURN((void*) point);
 #endif
 }
References ALIGN_SIZE, ALLOC_MAX_BLOCK_TO_DROP, ALLOC_MAX_BLOCK_USAGE_BEFORE_DROP, alloc_root_inited, st_mem_root::block_num, st_mem_root::block_size, DBUG_ASSERT, DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, DBUG_SET, st_mem_root::error_handler, st_mem_root::first_block_usage, st_mem_root::free, G3D::length(), max, ME_FATALERROR, mem_root, st_mem_root::min_malloc, my_malloc(), MY_WME, MYF, next(), NULL, prev(), reg1, reg2, and st_mem_root::used.
Referenced by alloc_stmt_fields(), cli_read_binary_rows(), cli_read_rows(), copy_typelib(), handle_default_option(), init_default_directories(), memdup_root(), multi_alloc_root(), my_dir(), my_load_defaults(), my_search_option_files(), mysql_stmt_prepare(), strmake_root(), tree_insert(), and unpack_fields().
allocate_dynamic()
my_bool allocate_dynamic (DYNAMIC_ARRAY * array, uint max_elements)
Definition at line 231 of file array.c.
 {
   if (max_elements >= array->max_element)
   {
     uint size;
     uchar *new_ptr;
     size= (max_elements + array->alloc_increment)/array->alloc_increment;
     size*= array->alloc_increment;
     if (array->buffer == (uchar *)(array + 1))
     {
        /*
          In this senerio, the buffer is statically preallocated,
          so we have to create an all-new malloc since we overflowed
        */
        if (!(new_ptr= (uchar *) my_malloc(size *
                                          array->size_of_element,
                                          MYF(MY_WME))))
          return 0;
        memcpy(new_ptr, array->buffer,
               array->elements * array->size_of_element);
      }
      else
     if (!(new_ptr= (uchar*) my_realloc(array->buffer,size*
                                        array->size_of_element,
                                        MYF(MY_WME | MY_ALLOW_ZERO_PTR))))
       return TRUE;
     array->buffer= new_ptr;
     array->max_element= size;
   }
   return FALSE;
 }
References array, FALSE, if(), memcpy, MY_ALLOW_ZERO_PTR, my_malloc(), my_realloc(), MY_WME, MYF, LF_DYNARRAY::size_of_element, and TRUE.
Referenced by set_dynamic().
array_append_string_unique()
my_bool array_append_string_unique (const char * str, const char ** array, size_t size)
Append str to array, or move to the end if it already exists
Parameters
str String to be appended
array The array, terminated by a NULL element, all unused elements pre-initialized to NULL
size Size of the array; array must be terminated by a NULL pointer, so can hold size - 1 elements
Return values
FALSE Success
TRUE Failure, array is full
Definition at line 33 of file mf_arr_appstr.c.
 {
   const char **p;
   /* end points at the terminating NULL element */
   const char **end= array + size - 1;
   DBUG_ASSERT(*end == NULL);
   for (p= array; *p; ++p)
   {
     if (strcmp(*p, str) == 0)
       break;
   }
   if (p >= end)
     return TRUE;                               /* Array is full */
   DBUG_ASSERT(*p == NULL || strcmp(*p, str) == 0);
   while (*(p + 1))
   {
     *p= *(p + 1);
     ++p;
   }
   DBUG_ASSERT(p < end);
   *p= str;
   return FALSE;                                 /* Success */
 }
References array, DBUG_ASSERT, FALSE, NULL, and TRUE.
Referenced by add_directory().
check_if_legal_filename()
int check_if_legal_filename (const char * path)
check_if_legal_tablename()
int check_if_legal_tablename (const char * path)
Definition at line 148 of file my_access.c.
 {
   DBUG_ENTER("check_if_legal_tablename");
   DBUG_RETURN((reserved_map[(uchar) name[0]] & 1) &&
               (reserved_map[(uchar) name[1]] & 2) &&
               (reserved_map[(uchar) name[2]] & 4) &&
               str_list_find(&reserved_names[1], name));
 }
References DBUG_ENTER, DBUG_RETURN, reserved_map, reserved_names, and str_list_find().
cleanup_dirname()
size_t cleanup_dirname (char * to, const char * from)
Referenced by init_tmpdir().
close_cached_file()
void close_cached_file (IO_CACHE * cache)
Definition at line 98 of file mf_cache.c.
 {
   DBUG_ENTER("close_cached_file");
   if (my_b_inited(cache))
   {
     File file=cache->file;
     cache->file= -1;                /* Don't flush data */
     (void) end_io_cache(cache);
     if (file >= 0)
     {
       (void) my_close(file,MYF(0));
 #ifdef CANT_DELETE_OPEN_FILES
       if (cache->file_name)
       {
     (void) my_delete(cache->file_name,MYF(MY_WME | ME_NOINPUT));
     my_free(cache->file_name);
       }
 #endif
     }
     my_free(cache->dir);
     my_free(cache->prefix);
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, st_io_cache::dir, end_io_cache(), mpq::file, st_io_cache::file, st_io_cache::file_name, ME_NOINPUT, my_b_inited, my_close(), my_delete(), my_free(), MY_WME, MYF, and st_io_cache::prefix.
convert_dirname()
char* convert_dirname (char * to, const char * from, const char * from_end)
Definition at line 104 of file mf_dirname.c.
 {
   char *to_org=to;
 #ifdef BACKSLASH_MBTAIL
   CHARSET_INFO *fs= fs_character_set();
 #endif
   DBUG_ENTER("convert_dirname");
   /* We use -2 here, becasue we need place for the last FN_LIBCHAR */
   if (!from_end || (from_end - from) > FN_REFLEN-2)
     from_end=from+FN_REFLEN -2;
 #if FN_LIBCHAR != '/'
   {
     for (; from != from_end && *from ; from++)
     {
       if (*from == '/')
     *to++= FN_LIBCHAR;
       else
       {
 #ifdef BACKSLASH_MBTAIL
         uint l;
         if (use_mb(fs) && (l= my_ismbchar(fs, from, from + 3)))
         {
           memmove(to, from, l);
           to+= l;
           from+= l - 1;
           to_org= to; /* Don't look inside mbchar */
         }
         else
 #endif
         {
           *to++= *from;
         }
       }
     }
     *to=0;
   }
 #else
   /* This is ok even if to == from, becasue we need to cut the string */
   to= strmake(to, from, (size_t) (from_end-from));
 #endif
   /* Add FN_LIBCHAR to the end of directory path */
   if (to != to_org && (to[-1] != FN_LIBCHAR && to[-1] != FN_DEVCHAR))
   {
     *to++=FN_LIBCHAR;
     *to=0;
   }
   DBUG_RETURN(to);                              /* Pointer to end of dir */
 } /* convert_dirname */
References DBUG_ENTER, DBUG_RETURN, FN_DEVCHAR, FN_LIBCHAR, FN_REFLEN, mpq::l, memmove, my_ismbchar, strmake(), and use_mb.
Referenced by create_temp_file(), dirname_part(), fn_format(), get_charsets_dir(), my_print_default_files(), mysql_read_default_options(), and search_default_file_with_ext().
crc32()
ulong crc32 (ulong crc, const uchar * buf, uint len)
Referenced by G3D::Crypto::crc32(), deflate(), deflateResetKeep(), inflate(), my_checksum(), read_buf(), soap_begin_recv(), soap_flush(), soap_init_send(), and soap_recv_raw().
create_temp_file()
File create_temp_file (char * to, const char * dir, const char * pfx, int mode, myf MyFlags)
Referenced by inline_mysql_file_create_temp(), and real_open_cached_file().
delete_dynamic()
void delete_dynamic (DYNAMIC_ARRAY * array)
Definition at line 298 of file array.c.
 {
   /*
     Just mark as empty if we are using a static buffer
   */
   if (array->buffer == (uchar *)(array + 1))
     array->elements= 0;
   else
   if (array->buffer)
   {
     my_free(array->buffer);
     array->buffer=0;
     array->elements=array->max_element=0;
   }
 }
References array, and my_free().
Referenced by free_tmpdir(), init_tmpdir(), my_dirend(), my_hash_free(), my_load_defaults(), and mysql_close_free_options().
delete_dynamic_element()
void delete_dynamic_element (DYNAMIC_ARRAY * array, uint array_index)
Definition at line 323 of file array.c.
 {
   char *ptr= (char*) array->buffer+array->size_of_element*idx;
   array->elements--;
   memmove(ptr,ptr+array->size_of_element,
           (array->elements-idx)*array->size_of_element);
 }
References array, idx, memmove, ptr(), and LF_DYNARRAY::size_of_element.
directory_file_name()
char* directory_file_name (char * dst, const char * src)
Definition at line 196 of file my_lib.c.
 {
   /* Process as Unix format: just remove test the final slash. */
   char *end;
   if (src[0] == 0)
     src= (char*) ".";               /* Use empty as current */
   end=strmov(dst, src);
   if (end[-1] != FN_LIBCHAR)
   {
     end[0]=FN_LIBCHAR;              /* Add last '/' */
     end[1]='\0';
   }
   return dst;
 }
References FN_LIBCHAR, and strmov().
Referenced by my_dir().
dirname_length()
size_t dirname_length (const char * name)
Definition at line 21 of file mf_dirname.c.
 {
   register char *pos, *gpos;
 #ifdef BASKSLASH_MBTAIL
   CHARSET_INFO *fs= fs_character_set();
 #endif
 #ifdef FN_DEVCHAR
   if ((pos=(char*)strrchr(name,FN_DEVCHAR)) == 0)
 #endif
     pos=(char*) name-1;
   gpos= pos++;
   for ( ; *pos ; pos++)             /* Find last FN_LIBCHAR */
   {
 #ifdef BASKSLASH_MBTAIL
     uint l;
     if (use_mb(fs) && (l= my_ismbchar(fs, pos, pos + 3)))
     {
       pos+= l - 1;
       continue;
     }
 #endif
     if (*pos == FN_LIBCHAR || *pos == '/')
       gpos=pos;
   }
   return (size_t) (gpos+1-(char*) name);
 }
References FN_DEVCHAR, FN_LIBCHAR, mpq::l, my_ismbchar, pos(), and use_mb.
Referenced by dirname_part(), my_print_default_files(), and my_search_option_files().
dirname_part()
size_t dirname_part (char * to, const char * name, size_t * to_res_length)
Definition at line 63 of file mf_dirname.c.
 {
   size_t length;
   DBUG_ENTER("dirname_part");
   DBUG_PRINT("enter",("'%s'",name));
   length=dirname_length(name);
   *to_res_length= (size_t) (convert_dirname(to, name, name+length) - to);
   DBUG_RETURN(length);
 } /* dirname */
References convert_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_length(), and G3D::length().
Referenced by fn_ext(), fn_format(), fn_same(), intern_filename(), my_path(), my_rename(), and unpack_filename().
dynstr_append()
my_bool dynstr_append (DYNAMIC_STRING * str, const char * append)
Definition at line 91 of file string.c.
 {
   return dynstr_append_mem(str,append,(uint) strlen(append));
 }
References utf8::append(), and dynstr_append_mem().
dynstr_append_mem()
my_bool dynstr_append_mem (DYNAMIC_STRING * str, const char * append, size_t length)
Definition at line 97 of file string.c.
 {
   char *new_ptr;
   if (str->length+length >= str->max_length)
   {
     size_t new_length=(str->length+length+str->alloc_increment)/
       str->alloc_increment;
     new_length*=str->alloc_increment;
     if (!(new_ptr=(char*) my_realloc(str->str,new_length,MYF(MY_WME))))
       return TRUE;
     str->str=new_ptr;
     str->max_length=new_length;
   }
   memcpy(str->str + str->length,append,length);
   str->length+=length;
   str->str[str->length]=0;          /* Safety for C programs */
   return FALSE;
 }
References st_dynamic_string::alloc_increment, utf8::append(), FALSE, if(), G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
Referenced by dynstr_append(), and dynstr_append_os_quoted().
dynstr_append_os_quoted()
my_bool dynstr_append_os_quoted (DYNAMIC_STRING * str, const char * append, ...)
Definition at line 141 of file string.c.
 {
 #ifdef __WIN__
   const char *quote_str= "\"";
   const uint  quote_len= 1;
 #else
   const char *quote_str= "\'";
   const uint  quote_len= 1;
 #endif /* __WIN__ */
   my_bool ret= TRUE;
   va_list dirty_text;
   ret&= dynstr_append_mem(str, quote_str, quote_len); /* Leading quote */
   va_start(dirty_text, append);
   while (append != NullS)
   {
     const char  *cur_pos= append;
     const char *next_pos= cur_pos;
     /* Search for quote in each string and replace with escaped quote */
     while(*(next_pos= strcend(cur_pos, quote_str[0])) != '\0')
     {
       ret&= dynstr_append_mem(str, cur_pos, (uint) (next_pos - cur_pos));
       ret&= dynstr_append_mem(str ,"\\", 1);
       ret&= dynstr_append_mem(str, quote_str, quote_len);
       cur_pos= next_pos + 1;
     }
     ret&= dynstr_append_mem(str, cur_pos, (uint) (next_pos - cur_pos));
     append= va_arg(dirty_text, char *);
   }
   va_end(dirty_text);
   ret&= dynstr_append_mem(str, quote_str, quote_len); /* Trailing quote */
   return ret;
 }
References utf8::append(), dynstr_append_mem(), NullS, ret, strcend(), and TRUE.
dynstr_free()
void dynstr_free (DYNAMIC_STRING * str)
Definition at line 178 of file string.c.
 {
   my_free(str->str);
   str->str= NULL;
 }
References my_free(), NULL, and st_dynamic_string::str.
dynstr_realloc()
my_bool dynstr_realloc (DYNAMIC_STRING * str, size_t additional_size)
Definition at line 75 of file string.c.
 {
   DBUG_ENTER("dynstr_realloc");
   if (!additional_size) DBUG_RETURN(FALSE);
   if (str->length + additional_size > str->max_length)
   {
     str->max_length=((str->length + additional_size+str->alloc_increment-1)/
              str->alloc_increment)*str->alloc_increment;
     if (!(str->str=(char*) my_realloc(str->str,str->max_length,MYF(MY_WME))))
       DBUG_RETURN(TRUE);
   }
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, st_dynamic_string::length, st_dynamic_string::max_length, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
dynstr_set()
my_bool dynstr_set (DYNAMIC_STRING * str, const char * init_str)
Definition at line 50 of file string.c.
 {
   uint length=0;
   DBUG_ENTER("dynstr_set");
   if (init_str && (length= (uint) strlen(init_str)+1) > str->max_length)
   {
     str->max_length=((length+str->alloc_increment-1)/str->alloc_increment)*
       str->alloc_increment;
     if (!str->max_length)
       str->max_length=str->alloc_increment;
     if (!(str->str=(char*) my_realloc(str->str,str->max_length,MYF(MY_WME))))
       DBUG_RETURN(TRUE);
   }
   if (init_str)
   {
     str->length=length-1;
     memcpy(str->str,init_str,length);
   }
   else
     str->length=0;
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
dynstr_trunc()
my_bool dynstr_trunc (DYNAMIC_STRING * str, size_t n)
Definition at line 118 of file string.c.
 {
   str->length-=n;
   str->str[str->length]= '\0';
   return FALSE;
 }
References FALSE, st_dynamic_string::length, and st_dynamic_string::str.
end_io_cache()
int end_io_cache (IO_CACHE * info)
Definition at line 1824 of file mf_iocache.c.
 {
   int error=0;
   IO_CACHE_CALLBACK pre_close;
   DBUG_ENTER("end_io_cache");
   DBUG_PRINT("enter",("cache: 0x%lx", (ulong) info));
   /*
     Every thread must call remove_io_thread(). The last one destroys
     the share elements.
   */
   DBUG_ASSERT(!info->share || !info->share->total_threads);
   if ((pre_close=info->pre_close))
   {
     (*pre_close)(info);
     info->pre_close= 0;
   }
   if (info->alloced_buffer)
   {
     info->alloced_buffer=0;
     if (info->file != -1)           /* File doesn't exist */
       error= my_b_flush_io_cache(info,1);
     my_free(info->buffer);
     info->buffer=info->read_pos=(uchar*) 0;
   }
   if (info->type == SEQ_READ_APPEND)
   {
     /* Destroy allocated mutex */
     info->type= TYPE_NOT_SET;
     mysql_mutex_destroy(&info->append_buffer_lock);
   }
   DBUG_RETURN(error);
 } /* end_io_cache */
References st_io_cache::alloced_buffer, st_io_cache::append_buffer_lock, st_io_cache::buffer, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), st_io_cache::file, my_b_flush_io_cache(), my_free(), mysql_mutex_destroy, st_io_cache::pre_close, st_io_cache::read_pos, SEQ_READ_APPEND, st_io_cache::share, st_io_cache_share::total_threads, st_io_cache::type, and TYPE_NOT_SET.
Referenced by close_cached_file().
end_record_cache()
int end_record_cache (RECORD_CACHE * info)
escape_quotes_for_mysql()
size_t escape_quotes_for_mysql (CHARSET_INFO * charset_info, char * to, size_t to_length, const char * from, size_t length)
Definition at line 883 of file charset.c.
 {
   const char *to_start= to;
   const char *end, *to_end=to_start + (to_length ? to_length-1 : 2*length);
   my_bool overflow= FALSE;
 #ifdef USE_MB
   my_bool use_mb_flag= use_mb(charset_info);
 #endif
   for (end= from + length; from < end; from++)
   {
 #ifdef USE_MB
     int tmp_length;
     if (use_mb_flag && (tmp_length= my_ismbchar(charset_info, from, end)))
     {
       if (to + tmp_length > to_end)
       {
         overflow= TRUE;
         break;
       }
       while (tmp_length--)
     *to++= *from++;
       from--;
       continue;
     }
     /*
       We don't have the same issue here with a non-multi-byte character being
       turned into a multi-byte character by the addition of an escaping
       character, because we are only escaping the ' character with itself.
      */
 #endif
     if (*from == '\'')
     {
       if (to + 2 > to_end)
       {
         overflow= TRUE;
         break;
       }
       *to++= '\'';
       *to++= '\'';
     }
     else
     {
       if (to + 1 > to_end)
       {
         overflow= TRUE;
         break;
       }
       *to++= *from;
     }
   }
   *to= 0;
   return overflow ? (ulong)~0 : (ulong) (to - to_start);
 }
References FALSE, G3D::length(), my_ismbchar, TRUE, and use_mb.
Referenced by mysql_real_escape_string().
escape_string_for_mysql()
size_t escape_string_for_mysql (CHARSET_INFO * charset_info, char * to, size_t to_length, const char * from, size_t length)
Definition at line 743 of file charset.c.
 {
   const char *to_start= to;
   const char *end, *to_end=to_start + (to_length ? to_length-1 : 2*length);
   my_bool overflow= FALSE;
 #ifdef USE_MB
   my_bool use_mb_flag= use_mb(charset_info);
 #endif
   for (end= from + length; from < end; from++)
   {
     char escape= 0;
 #ifdef USE_MB
     int tmp_length;
     if (use_mb_flag && (tmp_length= my_ismbchar(charset_info, from, end)))
     {
       if (to + tmp_length > to_end)
       {
         overflow= TRUE;
         break;
       }
       while (tmp_length--)
     *to++= *from++;
       from--;
       continue;
     }
     /*
      If the next character appears to begin a multi-byte character, we
      escape that first byte of that apparent multi-byte character. (The
      character just looks like a multi-byte character -- if it were actually
      a multi-byte character, it would have been passed through in the test
      above.)
      Without this check, we can create a problem by converting an invalid
      multi-byte character into a valid one. For example, 0xbf27 is not
      a valid GBK character, but 0xbf5c is. (0x27 = ', 0x5c = \‍)
     */
     if (use_mb_flag && (tmp_length= my_mbcharlen(charset_info, *from)) > 1)
       escape= *from;
     else
 #endif
     switch (*from) {
     case 0:             /* Must be escaped for 'mysql' */
       escape= '0';
       break;
     case '\n':              /* Must be escaped for logs */
       escape= 'n';
       break;
     case '\r':
       escape= 'r';
       break;
     case '\\':
       escape= '\\';
       break;
     case '\'':
       escape= '\'';
       break;
     case '"':               /* Better safe than sorry */
       escape= '"';
       break;
     case '\032':            /* This gives problems on Win32 */
       escape= 'Z';
       break;
     }
     if (escape)
     {
       if (to + 2 > to_end)
       {
         overflow= TRUE;
         break;
       }
       *to++= '\\';
       *to++= escape;
     }
     else
     {
       if (to + 1 > to_end)
       {
         overflow= TRUE;
         break;
       }
       *to++= *from;
     }
   }
   *to= 0;
   return overflow ? (size_t) -1 : (size_t) (to - to_start);
 }
References G3D::escape(), FALSE, G3D::length(), my_ismbchar, my_mbcharlen, TRUE, and use_mb.
Referenced by mysql_escape_string(), and mysql_real_escape_string().
flush_write_cache()
int flush_write_cache (RECORD_CACHE * info)
fn_ext()
char* fn_ext (const char * name)
Definition at line 36 of file mf_fn_ext.c.
 {
   register const char *pos, *gpos;
   DBUG_ENTER("fn_ext");
   DBUG_PRINT("mfunkt",("name: '%s'",name));
 #if defined(FN_DEVCHAR) || defined(BASKSLASH_MBTAIL)
   {
     char buff[FN_REFLEN];
     size_t res_length;
     gpos= name+ dirname_part(buff,(char*) name, &res_length);
   }
 #else
   if (!(gpos= strrchr(name, FN_LIBCHAR)))
     gpos= name;
 #endif
   pos=strchr(gpos,FN_EXTCHAR);
   DBUG_RETURN((char*) (pos ? pos : strend(gpos)));
 } /* fn_ext */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), FN_EXTCHAR, FN_LIBCHAR, FN_REFLEN, pos(), and strend().
Referenced by find_file_in_path(), my_print_default_files(), search_default_file(), and search_default_file_with_ext().
fn_format()
char* fn_format (char * to, const char * name, const char * dir, const char * form, uint flag)
Definition at line 26 of file mf_format.c.
 {
   char dev[FN_REFLEN], buff[FN_REFLEN], *pos, *startpos;
   const char *ext;
   reg1 size_t length;
   size_t dev_length;
   DBUG_ENTER("fn_format");
   DBUG_PRINT("enter",("name: %s  dir: %s  extension: %s  flag: %d",
                name,dir,extension,flag));
   /* Copy and skip directory */
   name+=(length=dirname_part(dev, (startpos=(char *) name), &dev_length));
   if (length == 0 || (flag & MY_REPLACE_DIR))
   {
     /* Use given directory */
     convert_dirname(dev,dir,NullS);     /* Fix to this OS */
   }
   else if ((flag & MY_RELATIVE_PATH) && !test_if_hard_path(dev))
   {
     /* Put 'dir' before the given path */
     strmake(buff,dev,sizeof(buff)-1);
     pos=convert_dirname(dev,dir,NullS);
     strmake(pos,buff,sizeof(buff)-1- (int) (pos-dev));
   }
   if (flag & MY_PACK_FILENAME)
     pack_dirname(dev,dev);          /* Put in ./.. and ~/.. */
   if (flag & MY_UNPACK_FILENAME)
     (void) unpack_dirname(dev,dev);     /* Replace ~/.. with dir */
   if (!(flag & MY_APPEND_EXT) &&
       (pos= (char*) strchr(name,FN_EXTCHAR)) != NullS)
   {
     if ((flag & MY_REPLACE_EXT) == 0)       /* If we should keep old ext */
     {
       length=strlength(name);           /* Use old extension */
       ext = "";
     }
     else
     {
       length= (size_t) (pos-(char*) name);  /* Change extension */
       ext= extension;
     }
   }
   else
   {
     length=strlength(name);         /* No ext, use the now one */
     ext=extension;
   }
   if (strlen(dev)+length+strlen(ext) >= FN_REFLEN || length >= FN_LEN )
   {
     /* To long path, return original or NULL */
     size_t tmp_length;
     if (flag & MY_SAFE_PATH)
       DBUG_RETURN(NullS);
     tmp_length= strlength(startpos);
     DBUG_PRINT("error",("dev: '%s'  ext: '%s'  length: %u",dev,ext,
                         (uint) length));
     (void) strmake(to,startpos,min(tmp_length,FN_REFLEN-1));
   }
   else
   {
     if (to == startpos)
     {
       bmove(buff,(uchar*) name,length);     /* Save name for last copy */
       name=buff;
     }
     pos=strmake(strmov(to,dev),name,length);
     (void) strmov(pos,ext);         /* Don't convert extension */
   }
   /*
     If MY_RETURN_REAL_PATH and MY_RESOLVE_SYMLINK is given, only do
     realpath if the file is a symbolic link
   */
   if (flag & MY_RETURN_REAL_PATH)
     (void) my_realpath(to, to, MYF(flag & MY_RESOLVE_SYMLINKS ?
                    MY_RESOLVE_LINK: 0));
   else if (flag & MY_RESOLVE_SYMLINKS)
   {
     strmov(buff,to);
     (void) my_readlink(to, buff, MYF(0));
   }
   DBUG_RETURN(to);
 } /* fn_format */
References convert_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), FN_EXTCHAR, FN_LEN, FN_REFLEN, G3D::length(), min, MY_APPEND_EXT, MY_PACK_FILENAME, my_readlink(), my_realpath(), MY_RELATIVE_PATH, MY_REPLACE_DIR, MY_REPLACE_EXT, MY_RESOLVE_LINK, MY_RESOLVE_SYMLINKS, MY_RETURN_REAL_PATH, MY_SAFE_PATH, MY_UNPACK_FILENAME, MYF, NullS, pack_dirname(), pos(), reg1, strlength(), strmake(), strmov(), test_if_hard_path(), and unpack_dirname().
Referenced by default_local_infile_init(), fn_expand(), fn_same(), my_redel(), and search_default_file_with_ext().
fn_same()
char* fn_same (char * toname, const char * name, int flag)
Definition at line 28 of file mf_same.c.
 {
   char dev[FN_REFLEN];
   const char *ext;
   size_t dev_length;
   DBUG_ENTER("fn_same");
   DBUG_PRINT("enter",("to: %s  name: %s  flag: %d",to,name,flag));
   if ((ext=strrchr(name+dirname_part(dev, name, &dev_length),FN_EXTCHAR)) == 0)
     ext="";
   DBUG_RETURN(fn_format(to,to,dev,ext,flag));
 } /* fn_same */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), FN_EXTCHAR, fn_format(), and FN_REFLEN.
Referenced by my_rename_with_symlink().
free_charsets()
void free_charsets (void)
Definition at line 461 of file charset.c.
 {
   charsets_initialized= charsets_template;
 }
References charsets_initialized, and charsets_template.
Referenced by my_end(), and mysql_server_end().
free_defaults()
void free_defaults (char ** argv)
Definition at line 620 of file default.c.
 {
   MEM_ROOT ptr;
   memcpy(&ptr, ((char *) argv) - sizeof(ptr), sizeof(ptr));
   free_root(&ptr,MYF(0));
 }
References free_root(), memcpy, MYF, and ptr().
Referenced by mysql_read_default_options().
free_root()
void free_root (MEM_ROOT * root, myf MyFLAGS)
Definition at line 347 of file my_alloc.c.
 {
   reg1 USED_MEM *next,*old;
   DBUG_ENTER("free_root");
   DBUG_PRINT("enter",("root: 0x%lx  flags: %u", (long) root, (uint) MyFlags));
   if (MyFlags & MY_MARK_BLOCKS_FREE)
   {
     mark_blocks_free(root);
     DBUG_VOID_RETURN;
   }
   if (!(MyFlags & MY_KEEP_PREALLOC))
     root->pre_alloc=0;
   for (next=root->used; next ;)
   {
     old=next; next= next->next ;
     if (old != root->pre_alloc)
       my_free(old);
   }
   for (next=root->free ; next ;)
   {
     old=next; next= next->next;
     if (old != root->pre_alloc)
       my_free(old);
   }
   root->used=root->free=0;
   if (root->pre_alloc)
   {
     root->free=root->pre_alloc;
     root->free->left=root->pre_alloc->size-ALIGN_SIZE(sizeof(USED_MEM));
     TRASH_MEM(root->pre_alloc);
     root->free->next=0;
   }
   root->block_num= 4;
   root->first_block_usage= 0;
   DBUG_VOID_RETURN;
 }
References ALIGN_SIZE, st_mem_root::block_num, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_mem_root::first_block_usage, st_mem_root::free, st_used_mem::left, mark_blocks_free(), my_free(), MY_KEEP_PREALLOC, MY_MARK_BLOCKS_FREE, st_used_mem::next, next(), st_mem_root::pre_alloc, reg1, st_used_mem::size, TRASH_MEM, and st_mem_root::used.
Referenced by free_defaults(), free_old_query(), free_rows(), free_tree(), my_dirend(), my_load_defaults(), my_print_default_files(), mysql_client_plugin_deinit(), mysql_free_result(), mysql_stmt_close(), mysql_stmt_prepare(), mysql_stmt_store_result(), reset_stmt_handle(), and stmt_read_row_from_cursor().
free_tmpdir()
void free_tmpdir (MY_TMPDIR * tmpdir)
Definition at line 85 of file mf_tempdir.c.
 {
   uint i;
   if (!tmpdir->full_list.elements)
     return;
   for (i=0; i<=tmpdir->max; i++)
     my_free(tmpdir->list[i]);
   delete_dynamic(&tmpdir->full_list);
   mysql_mutex_destroy(&tmpdir->mutex);
 }
References delete_dynamic(), st_dynamic_array::elements, st_my_tmpdir::full_list, st_my_tmpdir::list, st_my_tmpdir::max, st_my_tmpdir::mutex, my_free(), and mysql_mutex_destroy.
freeze_size()
void freeze_size (DYNAMIC_ARRAY * array)
Definition at line 341 of file array.c.
 {
   uint elements=max(array->elements,1);
   /*
     Do nothing if we are using a static buffer
   */
   if (array->buffer == (uchar *)(array + 1))
     return;
   if (array->buffer && array->max_element != elements)
   {
     array->buffer=(uchar*) my_realloc(array->buffer,
                                      elements*array->size_of_element,
                                      MYF(MY_WME));
     array->max_element=elements;
   }
 }
References array, max, my_realloc(), MY_WME, MYF, and LF_DYNARRAY::size_of_element.
Referenced by init_tmpdir().
get_charset()
CHARSET_INFO* get_charset (uint cs_number, myf flags)
Definition at line 585 of file charset.c.
 {
   CHARSET_INFO *cs;
   if (cs_number == default_charset_info->number)
     return default_charset_info;
   my_pthread_once(&charsets_initialized, init_available_charsets);
   if (!cs_number || cs_number > array_elements(all_charsets))
     return NULL;
   cs=get_internal_charset(cs_number, flags);
   if (!cs && (flags & MY_WME))
   {
     char index_file[FN_REFLEN + sizeof(MY_CHARSET_INDEX)], cs_string[23];
     strmov(get_charsets_dir(index_file),MY_CHARSET_INDEX);
     cs_string[0]='#';
     int10_to_str(cs_number, cs_string+1, 10);
     my_error(EE_UNKNOWN_CHARSET, MYF(ME_BELL), cs_string, index_file);
   }
   return cs;
 }
References all_charsets, array_elements, charsets_initialized, default_charset_info, EE_UNKNOWN_CHARSET, FN_REFLEN, get_charsets_dir(), get_internal_charset(), init_available_charsets(), int10_to_str(), ME_BELL, MY_CHARSET_INDEX, my_error(), my_pthread_once, MY_WME, MYF, NULL, charset_info_st::number, and strmov().
get_charset_by_csname()
CHARSET_INFO* get_charset_by_csname (const char * cs_name, uint cs_flags, myf my_flags)
Definition at line 629 of file charset.c.
 {
   uint cs_number;
   CHARSET_INFO *cs;
   DBUG_ENTER("get_charset_by_csname");
   DBUG_PRINT("enter",("name: '%s'", cs_name));
   my_pthread_once(&charsets_initialized, init_available_charsets);
   cs_number= get_charset_number(cs_name, cs_flags);
   cs= cs_number ? get_internal_charset(cs_number, flags) : NULL;
   if (!cs && (flags & MY_WME))
   {
     char index_file[FN_REFLEN + sizeof(MY_CHARSET_INDEX)];
     strmov(get_charsets_dir(index_file),MY_CHARSET_INDEX);
     my_error(EE_UNKNOWN_CHARSET, MYF(ME_BELL), cs_name, index_file);
   }
   DBUG_RETURN(cs);
 }
References charsets_initialized, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_UNKNOWN_CHARSET, FN_REFLEN, get_charset_number(), get_charsets_dir(), get_internal_charset(), init_available_charsets(), ME_BELL, MY_CHARSET_INDEX, my_error(), my_pthread_once, MY_WME, MYF, NULL, and strmov().
Referenced by mysql_set_character_set(), mysql_set_character_set_with_default_collation(), and resolve_charset().
get_charset_by_name()
CHARSET_INFO* get_charset_by_name (const char * cs_name, myf flags)
Definition at line 609 of file charset.c.
 {
   uint cs_number;
   CHARSET_INFO *cs;
   my_pthread_once(&charsets_initialized, init_available_charsets);
   cs_number=get_collation_number(cs_name);
   cs= cs_number ? get_internal_charset(cs_number,flags) : NULL;
   if (!cs && (flags & MY_WME))
   {
     char index_file[FN_REFLEN + sizeof(MY_CHARSET_INDEX)];
     strmov(get_charsets_dir(index_file),MY_CHARSET_INDEX);
     my_error(EE_UNKNOWN_COLLATION, MYF(ME_BELL), cs_name, index_file);
   }
   return cs;
 }
References charsets_initialized, EE_UNKNOWN_COLLATION, FN_REFLEN, get_charsets_dir(), get_collation_number(), get_internal_charset(), init_available_charsets(), ME_BELL, MY_CHARSET_INDEX, my_error(), my_pthread_once, MY_WME, MYF, NULL, and strmov().
Referenced by mysql_set_character_set_with_default_collation(), and resolve_collation().
get_charset_name()
const char* get_charset_name (uint cs_number)
Definition at line 530 of file charset.c.
 {
   CHARSET_INFO *cs;
   my_pthread_once(&charsets_initialized, init_available_charsets);
   cs=all_charsets[charset_number];
   if (cs && (cs->number == charset_number) && cs->name )
     return (char*) cs->name;
   return (char*) "?";   /* this mimics find_type() */
 }
References all_charsets, charsets_initialized, init_available_charsets(), my_pthread_once, charset_info_st::name, and charset_info_st::number.
get_charset_number()
uint get_charset_number (const char * cs_name, uint cs_flags)
Definition at line 518 of file charset.c.
 {
   uint id;
   my_pthread_once(&charsets_initialized, init_available_charsets);
   if ((id= get_charset_number_internal(charset_name, cs_flags)))
     return id;
   if ((charset_name= get_charset_name_alias(charset_name)))
     return get_charset_number_internal(charset_name, cs_flags);
   return 0;
 }
References charsets_initialized, get_charset_name_alias(), get_charset_number_internal(), init_available_charsets(), and my_pthread_once.
Referenced by get_charset_by_csname().
get_charsets_dir()
char* get_charsets_dir (char * buf)
Definition at line 395 of file charset.c.
 {
   const char *sharedir= SHAREDIR;
   char *res;
   DBUG_ENTER("get_charsets_dir");
   if (charsets_dir != NULL)
     strmake(buf, charsets_dir, FN_REFLEN-1);
   else
   {
     if (test_if_hard_path(sharedir) ||
     is_prefix(sharedir, DEFAULT_CHARSET_HOME))
       strxmov(buf, sharedir, "/", CHARSET_DIR, NullS);
     else
       strxmov(buf, DEFAULT_CHARSET_HOME, "/", sharedir, "/", CHARSET_DIR,
           NullS);
   }
   res= convert_dirname(buf,buf,NullS);
   DBUG_PRINT("info",("charsets dir: '%s'", buf));
   DBUG_RETURN(res);
 }
References CHARSET_DIR, charsets_dir, convert_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FN_REFLEN, is_prefix(), NULL, NullS, strmake(), strxmov(), and test_if_hard_path().
Referenced by get_charset(), get_charset_by_csname(), get_charset_by_name(), get_internal_charset(), init_available_charsets(), mysql_init_character_set(), and mysql_set_character_set().
get_collation_number()
uint get_collation_number (const char * name)
Definition at line 479 of file charset.c.
 {
   uint id;
   char alias[64];
   my_pthread_once(&charsets_initialized, init_available_charsets);
   if ((id= get_collation_number_internal(name)))
     return id;
   if ((name= get_collation_name_alias(name, alias, sizeof(alias))))
     return get_collation_number_internal(name);
   return 0;
 }
References charsets_initialized, get_collation_name_alias(), get_collation_number_internal(), init_available_charsets(), and my_pthread_once.
Referenced by get_charset_by_name().
get_date()
void get_date (char * to, int timeflag, time_t use_time)
Referenced by my_redel().
get_defaults_options()
int get_defaults_options (int argc, char ** argv, char ** defaults, char ** extra_defaults, char ** group_suffix)
Definition at line 394 of file default.c.
 {
   int org_argc= argc, prev_argc= 0;
   *defaults= *extra_defaults= *group_suffix= 0;
   while (argc >= 2 && argc != prev_argc)
   {
     /* Skip program name or previously handled argument */
     argv++;
     prev_argc= argc;                            /* To check if we found */
     if (!*defaults && is_prefix(*argv,"--defaults-file="))
     {
       *defaults= *argv + sizeof("--defaults-file=")-1;
        argc--;
        continue;
     }
     if (!*extra_defaults && is_prefix(*argv,"--defaults-extra-file="))
     {
       *extra_defaults= *argv + sizeof("--defaults-extra-file=")-1;
       argc--;
       continue;
     }
     if (!*group_suffix && is_prefix(*argv, "--defaults-group-suffix="))
     {
       *group_suffix= *argv + sizeof("--defaults-group-suffix=")-1;
       argc--;
       continue;
     }
   }
   return org_argc - argc;
 }
References is_prefix().
Referenced by my_search_option_files().
get_dynamic()
void get_dynamic (DYNAMIC_ARRAY * array, uchar * element, uint array_index)
Definition at line 276 of file array.c.
 {
   if (idx >= array->elements)
   {
     DBUG_PRINT("warning",("To big array idx: %d, array size is %d",
                           idx,array->elements));
     bzero(element,array->size_of_element);
     return;
   }
   memcpy(element,array->buffer+idx*array->size_of_element,
          (size_t) array->size_of_element);
 }
References array, bzero, DBUG_PRINT, idx, memcpy, and LF_DYNARRAY::size_of_element.
get_global_errmsgs()
const char** get_global_errmsgs ()
Definition at line 116 of file errors.c.
 {
   return globerrs;
 }
References globerrs.
get_index_dynamic()
int get_index_dynamic (DYNAMIC_ARRAY * array, uchar * element)
Definition at line 371 of file array.c.
 {
   size_t ret;
   if (array->buffer > element)
     return -1;
   ret= (element - array->buffer) /  array->size_of_element;
   if (ret > array->elements)
     return -1;
   return ret;
 }
References array, if(), ret, and LF_DYNARRAY::size_of_element.
get_ptr_compare()
qsort2_cmp get_ptr_compare (size_t size)
Definition at line 59 of file ptr_cmp.c.
 {
   if (size < 4)
     return (qsort2_cmp) ptr_compare;
   switch (size & 3) {
     case 0: return (qsort2_cmp) ptr_compare_0;
     case 1: return (qsort2_cmp) ptr_compare_1;
     case 2: return (qsort2_cmp) ptr_compare_2;
     case 3: return (qsort2_cmp) ptr_compare_3;
     }
   return 0;                 /* Impossible */
 }
References ptr_compare(), ptr_compare_0(), ptr_compare_1(), ptr_compare_2(), and ptr_compare_3().
Referenced by my_string_ptr_sort().
handle_recived_signals()
void handle_recived_signals (void)
has_path()
my_bool has_path (const char * name)
Definition at line 157 of file my_getwd.c.
 {
   return test(strchr(name, FN_LIBCHAR))
 #if FN_LIBCHAR != '/'
     || test(strchr(name,'/'))
 #endif
 #ifdef FN_DEVCHAR
     || test(strchr(name, FN_DEVCHAR))
 #endif
     ;
 }
References FN_DEVCHAR, FN_LIBCHAR, and test.
init_alloc_root()
void init_alloc_root (MEM_ROOT * mem_root, size_t block_size, size_t pre_alloc_size)
Referenced by cli_read_rows(), free_old_query(), init_tree(), my_dir(), my_load_defaults(), my_print_default_files(), mysql_client_plugin_init(), and mysql_stmt_init().
init_compiled_charsets()
my_bool init_compiled_charsets (myf flags)
Referenced by init_available_charsets().
init_dynamic_array()
my_bool init_dynamic_array (DYNAMIC_ARRAY * array, uint element_size, uint init_alloc, uint alloc_increment)
Definition at line 75 of file array.c.
 {
   /* placeholder to preserve ABI */
   return my_init_dynamic_array_ci(array, element_size, init_alloc,
                                   alloc_increment);
 }
References array, and my_init_dynamic_array_ci.
Referenced by add_init_command().
init_dynamic_array2()
my_bool init_dynamic_array2 (DYNAMIC_ARRAY * array, uint element_size, void * init_buffer, uint init_alloc, uint alloc_increment)
Definition at line 43 of file array.c.
 {
   DBUG_ENTER("init_dynamic_array");
   if (!alloc_increment)
   {
     alloc_increment=max((8192-MALLOC_OVERHEAD)/element_size,16);
     if (init_alloc > 8 && alloc_increment > init_alloc * 2)
       alloc_increment=init_alloc*2;
   }
   if (!init_alloc)
   {
     init_alloc=alloc_increment;
     init_buffer= 0;
   }
   array->elements=0;
   array->max_element=init_alloc;
   array->alloc_increment=alloc_increment;
   array->size_of_element=element_size;
   if ((array->buffer= init_buffer))
     DBUG_RETURN(FALSE);
   /*
     Since the dynamic array is usable even if allocation fails here malloc
     should not throw an error
   */
   if (!(array->buffer= (uchar*) my_malloc(element_size*init_alloc, MYF(0))))
     array->max_element=0;
   DBUG_RETURN(FALSE);
 }
References array, DBUG_ENTER, DBUG_RETURN, FALSE, MALLOC_OVERHEAD, max, my_malloc(), MYF, and LF_DYNARRAY::size_of_element.
init_dynamic_string()
my_bool init_dynamic_string (DYNAMIC_STRING * str, const char * init_str, size_t init_alloc, size_t alloc_increment)
Definition at line 25 of file string.c.
 {
   size_t length;
   DBUG_ENTER("init_dynamic_string");
   if (!alloc_increment)
     alloc_increment=128;
   length=1;
   if (init_str && (length= strlen(init_str)+1) < init_alloc)
     init_alloc=((length+alloc_increment-1)/alloc_increment)*alloc_increment;
   if (!init_alloc)
     init_alloc=alloc_increment;
   if (!(str->str=(char*) my_malloc(init_alloc,MYF(MY_WME))))
     DBUG_RETURN(TRUE);
   str->length=length-1;
   if (init_str)
     memcpy(str->str,init_str,length);
   str->max_length=init_alloc;
   str->alloc_increment=alloc_increment;
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_malloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
init_glob_errs()
void init_glob_errs (void)
Definition at line 58 of file errors.c.
 {
   /* This is now done statically. */
 }
Referenced by my_basic_init().
init_io_cache()
int init_io_cache (IO_CACHE * info, File file, size_t cachesize, enum cache_type type, my_off_t seek_offset, pbool use_async_io, myf cache_myflags)
Definition at line 145 of file mf_iocache.c.
 {
   size_t min_cache;
   my_off_t pos;
   my_off_t end_of_file= ~(my_off_t) 0;
   DBUG_ENTER("init_io_cache");
   DBUG_PRINT("enter",("cache: 0x%lx  type: %d  pos: %ld",
               (ulong) info, (int) type, (ulong) seek_offset));
   info->file= file;
   info->type= TYPE_NOT_SET;     /* Don't set it until mutex are created */
   info->pos_in_file= seek_offset;
   info->pre_close = info->pre_read = info->post_read = 0;
   info->arg = 0;
   info->alloced_buffer = 0;
   info->buffer=0;
   info->seek_not_done= 0;
   if (file >= 0)
   {
     pos= mysql_file_tell(file, MYF(0));
     if ((pos == (my_off_t) -1) && (my_errno == ESPIPE))
     {
       /*
          This kind of object doesn't support seek() or tell(). Don't set a
          flag that will make us again try to seek() later and fail.
       */
       info->seek_not_done= 0;
       /*
         Additionally, if we're supposed to start somewhere other than the
         the beginning of whatever this file is, then somebody made a bad
         assumption.
       */
       DBUG_ASSERT(seek_offset == 0);
     }
     else
       info->seek_not_done= test(seek_offset != pos);
   }
   info->disk_writes= 0;
   info->share=0;
   if (!cachesize && !(cachesize= my_default_record_cache_size))
     DBUG_RETURN(1);             /* No cache requested */
   min_cache=use_async_io ? IO_SIZE*4 : IO_SIZE*2;
   if (type == READ_CACHE || type == SEQ_READ_APPEND)
   {                     /* Assume file isn't growing */
     if (!(cache_myflags & MY_DONT_CHECK_FILESIZE))
     {
       /* Calculate end of file to avoid allocating oversized buffers */
       end_of_file= mysql_file_seek(file, 0L, MY_SEEK_END, MYF(0));
       /* Need to reset seek_not_done now that we just did a seek. */
       info->seek_not_done= end_of_file == seek_offset ? 0 : 1;
       if (end_of_file < seek_offset)
     end_of_file=seek_offset;
       /* Trim cache size if the file is very small */
       if ((my_off_t) cachesize > end_of_file-seek_offset+IO_SIZE*2-1)
       {
     cachesize= (size_t) (end_of_file-seek_offset)+IO_SIZE*2-1;
     use_async_io=0;             /* No need to use async */
       }
     }
   }
   cache_myflags &= ~MY_DONT_CHECK_FILESIZE;
   if (type != READ_NET && type != WRITE_NET)
   {
     /* Retry allocating memory in smaller blocks until we get one */
     cachesize= ((cachesize + min_cache-1) & ~(min_cache-1));
     for (;;)
     {
       size_t buffer_block;
       /*
         Unset MY_WAIT_IF_FULL bit if it is set, to prevent conflict with
         MY_ZEROFILL.
       */
       myf flags= (myf) (cache_myflags & ~(MY_WME | MY_WAIT_IF_FULL));
       if (cachesize < min_cache)
     cachesize = min_cache;
       buffer_block= cachesize;
       if (type == SEQ_READ_APPEND)
     buffer_block *= 2;
       if (cachesize == min_cache)
         flags|= (myf) MY_WME;
       if ((info->buffer= (uchar*) my_malloc(buffer_block, flags)) != 0)
       {
     info->write_buffer=info->buffer;
     if (type == SEQ_READ_APPEND)
       info->write_buffer = info->buffer + cachesize;
     info->alloced_buffer=1;
     break;                  /* Enough memory found */
       }
       if (cachesize == min_cache)
     DBUG_RETURN(2);             /* Can't alloc cache */
       /* Try with less memory */
       cachesize= (cachesize*3/4 & ~(min_cache-1));
     }
   }
   DBUG_PRINT("info",("init_io_cache: cachesize = %lu", (ulong) cachesize));
   info->read_length=info->buffer_length=cachesize;
   info->myflags=cache_myflags & ~(MY_NABP | MY_FNABP);
   info->request_pos= info->read_pos= info->write_pos = info->buffer;
   if (type == SEQ_READ_APPEND)
   {
     info->append_read_pos = info->write_pos = info->write_buffer;
     info->write_end = info->write_buffer + info->buffer_length;
     mysql_mutex_init(key_IO_CACHE_append_buffer_lock,
                      &info->append_buffer_lock, MY_MUTEX_INIT_FAST);
   }
 #if defined(SAFE_MUTEX)
   else
   {
     /* Clear mutex so that safe_mutex will notice that it's not initialized */
     bzero((char*) &info->append_buffer_lock, sizeof(info));
   }
 #endif
   if (type == WRITE_CACHE)
     info->write_end=
       info->buffer+info->buffer_length- (seek_offset & (IO_SIZE-1));
   else
     info->read_end=info->buffer;        /* Nothing in cache */
   /* End_of_file may be changed by user later */
   info->end_of_file= end_of_file;
   info->error=0;
   info->type= type;
   init_functions(info);
 #ifdef HAVE_AIOWAIT
   if (use_async_io && ! my_disable_async_io)
   {
     DBUG_PRINT("info",("Using async io"));
     info->read_length/=2;
     info->read_function=_my_b_async_read;
   }
   info->inited=info->aio_result.pending=0;
 #endif
   DBUG_RETURN(0);
 }                       /* init_io_cache */
References _my_b_async_read(), st_io_cache::alloced_buffer, st_io_cache::append_buffer_lock, st_io_cache::append_read_pos, st_io_cache::arg, st_io_cache::buffer, st_io_cache::buffer_length, bzero, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_io_cache::disk_writes, st_io_cache::end_of_file, st_io_cache::error, mpq::file, st_io_cache::file, init_functions(), IO_SIZE, my_default_record_cache_size, my_disable_async_io, MY_DONT_CHECK_FILESIZE, my_errno, MY_FNABP, my_malloc(), MY_MUTEX_INIT_FAST, MY_NABP, MY_SEEK_END, MY_WAIT_IF_FULL, MY_WME, MYF, st_io_cache::myflags, mysql_file_seek, mysql_file_tell, mysql_mutex_init, pos(), st_io_cache::pos_in_file, st_io_cache::post_read, st_io_cache::pre_close, st_io_cache::pre_read, READ_CACHE, st_io_cache::read_end, st_io_cache::read_function, st_io_cache::read_length, READ_NET, st_io_cache::read_pos, st_io_cache::request_pos, st_io_cache::seek_not_done, SEQ_READ_APPEND, st_io_cache::share, test, st_io_cache::type, TYPE_NOT_SET, st_io_cache::write_buffer, WRITE_CACHE, st_io_cache::write_end, WRITE_NET, and st_io_cache::write_pos.
Referenced by open_cached_file().
init_io_cache_share()
void init_io_cache_share (IO_CACHE * read_cache, IO_CACHE_SHARE * cshare, IO_CACHE * write_cache, uint num_threads)
Definition at line 659 of file mf_iocache.c.
 {
   DBUG_ENTER("init_io_cache_share");
   DBUG_PRINT("io_cache_share", ("read_cache: 0x%lx  share: 0x%lx  "
                                 "write_cache: 0x%lx  threads: %u",
                                 (long) read_cache, (long) cshare,
                                 (long) write_cache, num_threads));
   DBUG_ASSERT(num_threads > 1);
   DBUG_ASSERT(read_cache->type == READ_CACHE);
   DBUG_ASSERT(!write_cache || (write_cache->type == WRITE_CACHE));
   mysql_mutex_init(key_IO_CACHE_SHARE_mutex,
                    &cshare->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_IO_CACHE_SHARE_cond, &cshare->cond, 0);
   mysql_cond_init(key_IO_CACHE_SHARE_cond_writer, &cshare->cond_writer, 0);
   cshare->running_threads= num_threads;
   cshare->total_threads=   num_threads;
   cshare->error=           0;    /* Initialize. */
   cshare->buffer=          read_cache->buffer;
   cshare->read_end=        NULL; /* See function comment of lock_io_cache(). */
   cshare->pos_in_file=     0;    /* See function comment of lock_io_cache(). */
   cshare->source_cache=    write_cache; /* Can be NULL. */
   read_cache->share=         cshare;
   read_cache->read_function= _my_b_read_r;
   read_cache->current_pos=   NULL;
   read_cache->current_end=   NULL;
   if (write_cache)
     write_cache->share= cshare;
   DBUG_VOID_RETURN;
 }
References _my_b_read_r(), st_io_cache_share::buffer, st_io_cache::buffer, st_io_cache_share::cond, st_io_cache_share::cond_writer, st_io_cache::current_end, st_io_cache::current_pos, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_io_cache_share::error, st_io_cache_share::mutex, MY_MUTEX_INIT_FAST, mysql_cond_init, mysql_mutex_init, NULL, st_io_cache_share::pos_in_file, READ_CACHE, st_io_cache_share::read_end, st_io_cache::read_function, st_io_cache_share::running_threads, st_io_cache::share, st_io_cache_share::source_cache, st_io_cache_share::total_threads, st_io_cache::type, and WRITE_CACHE.
init_record_cache()
int init_record_cache (RECORD_CACHE * info, size_t cachesize, File file, size_t reclength, enum cache_type type, pbool use_async_io)
init_tmpdir()
my_bool init_tmpdir (MY_TMPDIR * tmpdir, const char * pathlist)
Definition at line 25 of file mf_tempdir.c.
 {
   char *end, *copy;
   char buff[FN_REFLEN];
   DBUG_ENTER("init_tmpdir");
   DBUG_PRINT("enter", ("pathlist: %s", pathlist ? pathlist : "NULL"));
   mysql_mutex_init(key_TMPDIR_mutex, &tmpdir->mutex, MY_MUTEX_INIT_FAST);
   if (my_init_dynamic_array(&tmpdir->full_list, sizeof(char*), 1, 5))
     goto err;
   if (!pathlist || !pathlist[0])
   {
     /* Get default temporary directory */
     pathlist=getenv("TMPDIR");  /* Use this if possible */
 #if defined(__WIN__)
     if (!pathlist)
       pathlist=getenv("TEMP");
     if (!pathlist)
       pathlist=getenv("TMP");
 #endif
     if (!pathlist || !pathlist[0])
       pathlist=(char*) P_tmpdir;
   }
   do
   {
     size_t length;
     end=strcend(pathlist, DELIM);
     strmake(buff, pathlist, (uint) (end-pathlist));
     length= cleanup_dirname(buff, buff);
     if (!(copy= my_strndup(buff, length, MYF(MY_WME))) ||
         insert_dynamic(&tmpdir->full_list, (uchar*) &copy))
       DBUG_RETURN(TRUE);
     pathlist=end+1;
   }
   while (*end);
   freeze_size(&tmpdir->full_list);
   tmpdir->list=(char **)tmpdir->full_list.buffer;
   tmpdir->max=tmpdir->full_list.elements-1;
   tmpdir->cur=0;
   DBUG_RETURN(FALSE);
 err:
   delete_dynamic(&tmpdir->full_list);           /* Safe to free */
   mysql_mutex_destroy(&tmpdir->mutex);
   DBUG_RETURN(TRUE);
 }
References st_dynamic_array::buffer, cleanup_dirname(), detail::copy(), st_my_tmpdir::cur, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, delete_dynamic(), DELIM, st_dynamic_array::elements, FALSE, FN_REFLEN, freeze_size(), st_my_tmpdir::full_list, insert_dynamic(), G3D::length(), st_my_tmpdir::list, st_my_tmpdir::max, st_my_tmpdir::mutex, my_init_dynamic_array, MY_MUTEX_INIT_FAST, my_strndup(), MY_WME, MYF, mysql_mutex_destroy, mysql_mutex_init, strcend(), strmake(), and TRUE.
insert_dynamic()
my_bool insert_dynamic (DYNAMIC_ARRAY * array, uchar * element)
Definition at line 95 of file array.c.
 {
   uchar* buffer;
   if (array->elements == array->max_element)
   {                     /* Call only when nessesary */
     if (!(buffer=alloc_dynamic(array)))
       return TRUE;
   }
   else
   {
     buffer=array->buffer+(array->elements * array->size_of_element);
     array->elements++;
   }
   memcpy(buffer,element,(size_t) array->size_of_element);
   return FALSE;
 }
References alloc_dynamic(), array, buffer, FALSE, memcpy, LF_DYNARRAY::size_of_element, and TRUE.
Referenced by add_init_command(), handle_default_option(), and init_tmpdir().
intern_filename()
char* intern_filename (char * to, const char * from)
Definition at line 448 of file mf_pack.c.
 {
   size_t length, to_length;
   char buff[FN_REFLEN];
   if (from == to)
   {                     /* Dirname may destroy from */
     strmov(buff,from);
     from=buff;
   }
   length= dirname_part(to, from, &to_length);   /* Copy dirname & fix chars */
   (void) strmov(to + to_length,from+length);
   return (to);
 } /* intern_filename */
References dirname_part(), FN_REFLEN, G3D::length(), and strmov().
Referenced by my_basic_init(), my_path(), normalize_dirname(), and pack_dirname().
load_defaults()
int load_defaults (const char * conf_file, const char ** groups, int * argc, char *** argv)
Definition at line 450 of file default.c.
 {
   return my_load_defaults(conf_file, groups, argc, argv, &default_directories);
 }
References default_directories, and my_load_defaults().
memdup_root()
void* memdup_root (MEM_ROOT * root, const void * str, size_t len)
Definition at line 430 of file my_alloc.c.
 {
   char *pos;
   if ((pos=alloc_root(root,len)))
     memcpy(pos,str,len);
   return pos;
 }
References alloc_root(), memcpy, and pos().
Referenced by add_plugin().
multi_alloc_root()
void* multi_alloc_root (MEM_ROOT * mem_root, ...)
Definition at line 264 of file my_alloc.c.
 {
   va_list args;
   char **ptr, *start, *res;
   size_t tot_length, length;
   DBUG_ENTER("multi_alloc_root");
   va_start(args, root);
   tot_length= 0;
   while ((ptr= va_arg(args, char **)))
   {
     length= va_arg(args, uint);
     tot_length+= ALIGN_SIZE(length);
   }
   va_end(args);
   if (!(start= (char*) alloc_root(root, tot_length)))
     DBUG_RETURN(0);                            /* purecov: inspected */
   va_start(args, root);
   res= start;
   while ((ptr= va_arg(args, char **)))
   {
     *ptr= res;
     length= va_arg(args, uint);
     res+= ALIGN_SIZE(length);
   }
   va_end(args);
   DBUG_RETURN((void*) start);
 }
References ALIGN_SIZE, alloc_root(), DBUG_ENTER, DBUG_RETURN, G3D::length(), and ptr().
my_b_append()
int my_b_append (IO_CACHE * info, const uchar * Buffer, size_t Count)
my_b_append_tell()
my_off_t my_b_append_tell (IO_CACHE * info)
Definition at line 70 of file mf_iocache2.c.
 {
   /*
     Sometimes we want to make sure that the variable is not put into
     a register in debugging mode so we can see its value in the core
   */
 #ifndef DBUG_OFF
 # define dbug_volatile volatile
 #else
 # define dbug_volatile
 #endif
   /*
     Prevent optimizer from putting res in a register when debugging
     we need this to be able to see the value of res when the assert fails
   */
   dbug_volatile my_off_t res;
   /*
     We need to lock the append buffer mutex to keep flush_io_cache()
     from messing with the variables that we need in order to provide the
     answer to the question.
   */
   mysql_mutex_lock(&info->append_buffer_lock);
 #ifndef DBUG_OFF
   /*
     Make sure EOF is where we think it is. Note that we cannot just use
     my_tell() because we have a reader thread that could have left the
     file offset in a non-EOF location
   */
   {
     volatile my_off_t save_pos;
     save_pos = my_tell(info->file,MYF(0));
     my_seek(info->file,(my_off_t)0,MY_SEEK_END,MYF(0));
     /*
       Save the value of my_tell in res so we can see it when studying coredump
     */
     DBUG_ASSERT(info->end_of_file - (info->append_read_pos-info->write_buffer)
         == (res=my_tell(info->file,MYF(0))));
     my_seek(info->file,save_pos,MY_SEEK_SET,MYF(0));
   }
 #endif
   res = info->end_of_file + (info->write_pos-info->append_read_pos);
   mysql_mutex_unlock(&info->append_buffer_lock);
   return res;
 }
References st_io_cache::append_buffer_lock, st_io_cache::append_read_pos, DBUG_ASSERT, dbug_volatile, st_io_cache::end_of_file, st_io_cache::file, my_seek(), MY_SEEK_END, MY_SEEK_SET, my_tell(), MYF, mysql_mutex_lock, mysql_mutex_unlock, st_io_cache::write_buffer, and st_io_cache::write_pos.
Referenced by my_b_safe_tell().
my_b_copy_to_file()
int my_b_copy_to_file (IO_CACHE * cache, FILE * file)
Definition at line 50 of file mf_iocache2.c.
 {
   size_t bytes_in_cache;
   DBUG_ENTER("my_b_copy_to_file");
   /* Reinit the cache to read from the beginning of the cache */
   if (reinit_io_cache(cache, READ_CACHE, 0L, FALSE, FALSE))
     DBUG_RETURN(1);
   bytes_in_cache= my_b_bytes_in_cache(cache);
   do
   {
     if (my_fwrite(file, cache->read_pos, bytes_in_cache,
                   MYF(MY_WME | MY_NABP)) == (size_t) -1)
       DBUG_RETURN(1);
     cache->read_pos= cache->read_end;
   } while ((bytes_in_cache= my_b_fill(cache)));
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, FALSE, mpq::file, my_b_bytes_in_cache, my_b_fill(), my_fwrite(), MY_NABP, MY_WME, MYF, READ_CACHE, st_io_cache::read_end, st_io_cache::read_pos, and reinit_io_cache().
my_b_filelength()
my_off_t my_b_filelength (IO_CACHE * info)
Definition at line 280 of file mf_iocache2.c.
 {
   if (info->type == WRITE_CACHE)
     return my_b_tell(info);
   info->seek_not_done= 1;
   return my_seek(info->file, 0L, MY_SEEK_END, MYF(0));
 }
References st_io_cache::file, my_b_tell, my_seek(), MY_SEEK_END, MYF, st_io_cache::seek_not_done, st_io_cache::type, and WRITE_CACHE.
my_b_fill()
size_t my_b_fill (IO_CACHE * info)
Definition at line 196 of file mf_iocache2.c.
 {
   my_off_t pos_in_file=(info->pos_in_file+
             (size_t) (info->read_end - info->buffer));
   size_t diff_length, length, max_length;
   if (info->seek_not_done)
   {                 /* File touched, do seek */
     if (my_seek(info->file,pos_in_file,MY_SEEK_SET,MYF(0)) ==
     MY_FILEPOS_ERROR)
     {
       info->error= 0;
       return 0;
     }
     info->seek_not_done=0;
   }
   diff_length=(size_t) (pos_in_file & (IO_SIZE-1));
   max_length=(info->read_length-diff_length);
   if (max_length >= (info->end_of_file - pos_in_file))
     max_length= (size_t) (info->end_of_file - pos_in_file);
   if (!max_length)
   {
     info->error= 0;
     return 0;                   /* EOF */
   }
   if ((length= my_read(info->file,info->buffer,max_length,
                        info->myflags)) == (size_t) -1)
   {
     info->error= -1;
     return 0;
   }
   info->read_pos=info->buffer;
   info->read_end=info->buffer+length;
   info->pos_in_file=pos_in_file;
   return length;
 }
References st_io_cache::buffer, st_io_cache::end_of_file, st_io_cache::error, st_io_cache::file, IO_SIZE, G3D::length(), MY_FILEPOS_ERROR, my_read, my_seek(), MY_SEEK_SET, MYF, st_io_cache::myflags, st_io_cache::pos_in_file, st_io_cache::read_end, st_io_cache::read_length, st_io_cache::read_pos, and st_io_cache::seek_not_done.
Referenced by my_b_copy_to_file(), and my_b_gets().
my_b_flush_io_cache()
int my_b_flush_io_cache (IO_CACHE * info, int need_append_buffer_lock)
my_b_gets()
size_t my_b_gets (IO_CACHE * info, char * to, size_t max_length)
Definition at line 242 of file mf_iocache2.c.
 {
   char *start = to;
   size_t length;
   max_length--;                 /* Save place for end \0 */
   /* Calculate number of characters in buffer */
   if (!(length= my_b_bytes_in_cache(info)) &&
       !(length= my_b_fill(info)))
     return 0;
   for (;;)
   {
     uchar *pos, *end;
     if (length > max_length)
       length=max_length;
     for (pos=info->read_pos,end=pos+length ; pos < end ;)
     {
       if ((*to++ = *pos++) == '\n')
       {
     info->read_pos=pos;
     *to='\0';
     return (size_t) (to-start);
       }
     }
     if (!(max_length-=length))
     {
      /* Found enough charcters;  Return found string */
       info->read_pos=pos;
       *to='\0';
       return (size_t) (to-start);
     }
     if (!(length=my_b_fill(info)))
       return 0;
   }
 }
References G3D::length(), my_b_bytes_in_cache, my_b_fill(), pos(), and st_io_cache::read_pos.
my_b_printf()
size_t my_b_printf (IO_CACHE * info, const char * fmt, ...)
Definition at line 296 of file mf_iocache2.c.
 {
   size_t result;
   va_list args;
   va_start(args,fmt);
   result=my_b_vprintf(info, fmt, args);
   va_end(args);
   return result;
 }
References fmt, and my_b_vprintf().
my_b_safe_tell()
my_off_t my_b_safe_tell (IO_CACHE * info)
Definition at line 118 of file mf_iocache2.c.
 {
   if (unlikely(info->type == SEQ_READ_APPEND))
     return my_b_append_tell(info);
   return my_b_tell(info);
 }
References my_b_append_tell(), my_b_tell, SEQ_READ_APPEND, st_io_cache::type, and unlikely.
my_b_safe_write()
int my_b_safe_write (IO_CACHE * info, const uchar * Buffer, size_t Count)
Definition at line 1641 of file mf_iocache.c.
 {
   /*
     Sasha: We are not writing this with the ? operator to avoid hitting
     a possible compiler bug. At least gcc 2.95 cannot deal with
     several layers of ternary operators that evaluated comma(,) operator
     expressions inside - I do have a test case if somebody wants it
   */
   if (info->type == SEQ_READ_APPEND)
     return my_b_append(info, Buffer, Count);
   return my_b_write(info, Buffer, Count);
 }
References Acore::Count(), my_b_append(), my_b_write, SEQ_READ_APPEND, and st_io_cache::type.
my_b_seek()
void my_b_seek (IO_CACHE * info, my_off_t pos)
Definition at line 130 of file mf_iocache2.c.
 {
   my_off_t offset;
   DBUG_ENTER("my_b_seek");
   DBUG_PRINT("enter",("pos: %lu", (ulong) pos));
   /*
     TODO:
        Verify that it is OK to do seek in the non-append
        area in SEQ_READ_APPEND cache
      a) see if this always works
      b) see if there is a better way to make it work
   */
   if (info->type == SEQ_READ_APPEND)
     (void) flush_io_cache(info);
   offset=(pos - info->pos_in_file);
   if (info->type == READ_CACHE || info->type == SEQ_READ_APPEND)
   {
     /* TODO: explain why this works if pos < info->pos_in_file */
     if ((ulonglong) offset < (ulonglong) (info->read_end - info->buffer))
     {
       /* The read is in the current buffer; Reuse it */
       info->read_pos = info->buffer + offset;
       DBUG_VOID_RETURN;
     }
     else
     {
       /* Force a new read on next my_b_read */
       info->read_pos=info->read_end=info->buffer;
     }
   }
   else if (info->type == WRITE_CACHE)
   {
     /* If write is in current buffer, reuse it */
     if ((ulonglong) offset <
     (ulonglong) (info->write_end - info->write_buffer))
     {
       info->write_pos = info->write_buffer + offset;
       DBUG_VOID_RETURN;
     }
     (void) flush_io_cache(info);
     /* Correct buffer end so that we write in increments of IO_SIZE */
     info->write_end=(info->write_buffer+info->buffer_length-
              (pos & (IO_SIZE-1)));
   }
   info->pos_in_file=pos;
   info->seek_not_done=1;
   DBUG_VOID_RETURN;
 }
References st_io_cache::buffer, st_io_cache::buffer_length, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, flush_io_cache, IO_SIZE, pos(), st_io_cache::pos_in_file, READ_CACHE, st_io_cache::read_end, st_io_cache::read_pos, st_io_cache::seek_not_done, SEQ_READ_APPEND, st_io_cache::type, st_io_cache::write_buffer, WRITE_CACHE, st_io_cache::write_end, and st_io_cache::write_pos.
my_b_vprintf()
size_t my_b_vprintf (IO_CACHE * info, const char * fmt, va_list ap)
Todo:
Implement "#" conversion flag.
Todo:
Implement " " conversion flag.
Todo:
Implement "+" conversion flag.
Definition at line 307 of file mf_iocache2.c.
 {
   size_t out_length= 0;
   uint minimum_width; /* as yet unimplemented */
   uint minimum_width_sign;
   uint precision; /* as yet unimplemented for anything but %b */
   my_bool is_zero_padded;
   /*
     Store the location of the beginning of a format directive, for the
     case where we learn we shouldn't have been parsing a format string
     at all, and we don't want to lose the flag/precision/width/size
     information.
    */
   const char* backtrack;
   for (; *fmt != '\0'; fmt++)
   {
     /* Copy everything until '%' or end of string */
     const char *start=fmt;
     size_t length;
     for (; (*fmt != '\0') && (*fmt != '%'); fmt++) ;
     length= (size_t) (fmt - start);
     out_length+=length;
     if (my_b_write(info, (const uchar*) start, length))
       goto err;
     if (*fmt == '\0')               /* End of format */
       return out_length;
     /*
       By this point, *fmt must be a percent;  Keep track of this location and
       skip over the percent character.
     */
     DBUG_ASSERT(*fmt == '%');
     backtrack= fmt;
     fmt++;
     is_zero_padded= FALSE;
     minimum_width_sign= 1;
     minimum_width= 0;
     precision= 0;
     /* Skip if max size is used (to be compatible with printf) */
 process_flags:
     switch (*fmt)
     {
       case '-':
         minimum_width_sign= -1; fmt++; goto process_flags;
       case '0':
         is_zero_padded= TRUE; fmt++; goto process_flags;
       case '#':  fmt++; goto process_flags;
       case ' ':  fmt++; goto process_flags;
       case '+':  fmt++; goto process_flags;
     }
     if (*fmt == '*')
     {
       precision= (int) va_arg(args, int);
       fmt++;
     }
     else
     {
       while (my_isdigit(&my_charset_latin1, *fmt)) {
         minimum_width=(minimum_width * 10) + (*fmt - '0');
         fmt++;
       }
     }
     minimum_width*= minimum_width_sign;
     if (*fmt == '.')
     {
       fmt++;
       if (*fmt == '*') {
         precision= (int) va_arg(args, int);
         fmt++;
       }
       else
       {
         while (my_isdigit(&my_charset_latin1, *fmt)) {
           precision=(precision * 10) + (*fmt - '0');
           fmt++;
         }
       }
     }
     if (*fmt == 's')                /* String parameter */
     {
       reg2 char *par = va_arg(args, char *);
       size_t length2 = strlen(par);
       /* TODO: implement precision */
       out_length+= length2;
       if (my_b_write(info, (uchar*) par, length2))
     goto err;
     }
     else if (*fmt == 'b')                       /* Sized buffer parameter, only precision makes sense */
     {
       char *par = va_arg(args, char *);
       out_length+= precision;
       if (my_b_write(info, (uchar*) par, precision))
         goto err;
     }
     else if (*fmt == 'd' || *fmt == 'u')    /* Integer parameter */
     {
       register int iarg;
       size_t length2;
       char buff[17];
       iarg = va_arg(args, int);
       if (*fmt == 'd')
     length2= (size_t) (int10_to_str((long) iarg,buff, -10) - buff);
       else
         length2= (uint) (int10_to_str((long) (uint) iarg,buff,10)- buff);
       /* minimum width padding */
       if (minimum_width > length2)
       {
         char *buffz;
         buffz= my_alloca(minimum_width - length2);
         if (is_zero_padded)
           memset(buffz, '0', minimum_width - length2);
         else
           memset(buffz, ' ', minimum_width - length2);
         my_b_write(info, buffz, minimum_width - length2);
         my_afree(buffz);
       }
       out_length+= length2;
       if (my_b_write(info, (uchar*) buff, length2))
     goto err;
     }
     else if ((*fmt == 'l' && fmt[1] == 'd') || fmt[1] == 'u')
       /* long parameter */
     {
       register long iarg;
       size_t length2;
       char buff[17];
       iarg = va_arg(args, long);
       if (*++fmt == 'd')
     length2= (size_t) (int10_to_str(iarg,buff, -10) - buff);
       else
     length2= (size_t) (int10_to_str(iarg,buff,10)- buff);
       out_length+= length2;
       if (my_b_write(info, (uchar*) buff, length2))
     goto err;
     }
     else
     {
       /* %% or unknown code */
       if (my_b_write(info, (uchar*) backtrack, (size_t) (fmt-backtrack)))
         goto err;
       out_length+= fmt-backtrack;
     }
   }
   return out_length;
 err:
   return (size_t) -1;
 }
References DBUG_ASSERT, FALSE, fmt, int10_to_str(), G3D::length(), memset, my_afree, my_alloca, my_b_write, my_charset_latin1, my_isdigit, reg2, and TRUE.
Referenced by my_b_printf().
my_basic_init()
my_bool my_basic_init (void)
Perform a limited initialisation of mysys. This initialisation is sufficient to:
allocate memory,
read configuration files,
parse command lines arguments. To complete the mysys initialisation, call my_init().
Returns
0 on success
Definition at line 69 of file my_init.c.
 {
   char * str;
   if (my_basic_init_done)
     return 0;
   my_basic_init_done= 1;
   mysys_usage_id++;
   my_umask= 0660;                       /* Default umask for new files */
   my_umask_dir= 0700;                   /* Default umask for new directories */
   /* Default creation of new files */
   if ((str= getenv("UMASK")) != 0)
     my_umask= (int) (atoi_octal(str) | 0600);
   /* Default creation of new dir's */
   if ((str= getenv("UMASK_DIR")) != 0)
     my_umask_dir= (int) (atoi_octal(str) | 0700);
   init_glob_errs();
   instrumented_stdin.m_file= stdin;
   instrumented_stdin.m_psi= NULL;       /* not yet instrumented */
   mysql_stdin= & instrumented_stdin;
   if (my_thread_global_init())
     return 1;
 #if defined(SAFE_MUTEX)
   safe_mutex_global_init();     /* Must be called early */
 #endif
 #if defined(MY_PTHREAD_FASTMUTEX) && !defined(SAFE_MUTEX)
   fastmutex_global_init();              /* Must be called early */
 #endif
 #if defined(HAVE_PTHREAD_INIT)
   pthread_init();           /* Must be called before DBUG_ENTER */
 #endif
   if (my_thread_basic_global_init())
     return 1;
   /* $HOME is needed early to parse configuration files located in ~/ */
   if ((home_dir= getenv("HOME")) != 0)
     home_dir= intern_filename(home_dir_buff, home_dir);
   return 0;
 }
References atoi_octal(), home_dir, home_dir_buff, init_glob_errs(), instrumented_stdin, intern_filename(), st_mysql_file::m_file, st_mysql_file::m_psi, my_basic_init_done, my_thread_basic_global_init(), my_thread_global_init(), my_umask, my_umask_dir, mysql_stdin, mysys_usage_id, NULL, and safe_mutex_global_init().
Referenced by my_init().
my_block_write()
int my_block_write (IO_CACHE * info, const uchar * Buffer, size_t Count, my_off_t pos)
my_charset_same()
my_bool my_charset_same (CHARSET_INFO * cs1, CHARSET_INFO * cs2)
Definition at line 34 of file charset.c.
 {
   return ((cs1 == cs2) || !strcmp(cs1->csname,cs2->csname));
 }
References charset_info_st::csname.
Referenced by mysql_set_character_set_with_default_collation().
my_checksum()
ha_checksum my_checksum (ha_checksum crc, const uchar * mem, size_t count)
Definition at line 31 of file checksum.c.
 {
   return (ha_checksum)crc32((uint)crc, pos, (uint)length);
 }
References crc32(), G3D::length(), and pos().
my_chsize()
int my_chsize (File fd, my_off_t newlength, int filler, myf MyFlags)
Definition at line 40 of file my_chsize.c.
 {
   my_off_t oldsize;
   uchar buff[IO_SIZE];
   DBUG_ENTER("my_chsize");
   DBUG_PRINT("my",("fd: %d  length: %lu  MyFlags: %d",fd,(ulong) newlength,
            MyFlags));
   if ((oldsize= my_seek(fd, 0L, MY_SEEK_END, MYF(MY_WME+MY_FAE))) == newlength)
     DBUG_RETURN(0);
   DBUG_PRINT("info",("old_size: %ld", (ulong) oldsize));
   if (oldsize > newlength)
   {
 #ifdef _WIN32
     if (my_win_chsize(fd, newlength))
     {
       my_errno= errno;
       goto err;
     }
     DBUG_RETURN(0);
 #elif defined(HAVE_FTRUNCATE)
     if (ftruncate(fd, (off_t) newlength))
     {
       my_errno= errno;
       goto err;
     }
     DBUG_RETURN(0);
 #elif defined(HAVE_CHSIZE)
     if (chsize(fd, (off_t) newlength))
     {
       my_errno=errno;
       goto err;
     }
     DBUG_RETURN(0);
 #else
     /*
       Fill space between requested length and true length with 'filler'
       We should never come here on any modern machine
     */
     if (my_seek(fd, newlength, MY_SEEK_SET, MYF(MY_WME+MY_FAE))
         == MY_FILEPOS_ERROR)
     {
       goto err;
     }
     swap_variables(my_off_t, newlength, oldsize);
 #endif
   }
   /* Full file with 'filler' until it's as big as requested */
   bfill(buff, IO_SIZE, filler);
   while (newlength-oldsize > IO_SIZE)
   {
     if (my_write(fd, buff, IO_SIZE, MYF(MY_NABP)))
       goto err;
     oldsize+= IO_SIZE;
   }
   if (my_write(fd,buff,(size_t) (newlength-oldsize), MYF(MY_NABP)))
     goto err;
   DBUG_RETURN(0);
 err:
   DBUG_PRINT("error", ("errno: %d", errno));
   if (MyFlags & MY_WME)
     my_error(EE_CANT_CHSIZE, MYF(ME_BELL+ME_WAITTANG), my_errno);
   DBUG_RETURN(1);
 } /* my_chsize */
References bfill, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_CHSIZE, errno, IO_SIZE, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILEPOS_ERROR, MY_NABP, my_seek(), MY_SEEK_END, MY_SEEK_SET, MY_WME, my_write, MYF, mpq::off_t, and swap_variables.
Referenced by inline_mysql_file_chsize().
my_close()
int my_close (File Filedes, myf MyFlags)
Definition at line 67 of file my_open.c.
 {
   int err;
   DBUG_ENTER("my_close");
   DBUG_PRINT("my",("fd: %d  MyFlags: %d",fd, MyFlags));
   mysql_mutex_lock(&THR_LOCK_open);
 #ifndef _WIN32
   do
   {
     err= close(fd);
   } while (err == -1 && errno == EINTR);
 #else
   err= my_win_close(fd);
 #endif
   if (err)
   {
     DBUG_PRINT("error",("Got error %d on close",err));
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_BADCLOSE, MYF(ME_BELL+ME_WAITTANG),my_filename(fd),errno);
   }
   if ((uint) fd < my_file_limit && my_file_info[fd].type != UNOPEN)
   {
     my_free(my_file_info[fd].name);
 #if !defined(HAVE_PREAD) && !defined(_WIN32)
     mysql_mutex_destroy(&my_file_info[fd].mutex);
 #endif
     my_file_info[fd].type = UNOPEN;
   }
   my_file_opened--;
   mysql_mutex_unlock(&THR_LOCK_open);
   DBUG_RETURN(err);
 } /* my_close */
References close, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_BADCLOSE, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_file_opened, my_filename(), my_free(), MY_WME, MYF, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
Referenced by cache_remove_open_tmp(), close_cached_file(), default_local_infile_end(), inline_mysql_file_close(), my_copy(), my_create(), my_create_with_symlink(), and my_register_filename().
my_compress()
my_bool my_compress (uchar * , size_t * , size_t *)
Referenced by net_real_write().
my_compress_alloc()
uchar* my_compress_alloc (const uchar * packet, size_t * len, size_t * complen)
my_copy()
int my_copy (const char * from, const char * to, myf MyFlags)
Definition at line 52 of file my_copy.c.
 {
   size_t Count;
   my_bool new_file_stat= 0; /* 1 if we could stat "to" */
   int create_flag;
   File from_file,to_file;
   uchar buff[IO_SIZE];
   MY_STAT stat_buff,new_stat_buff;
   DBUG_ENTER("my_copy");
   DBUG_PRINT("my",("from %s to %s MyFlags %d", from, to, MyFlags));
   from_file=to_file= -1;
   DBUG_ASSERT(!(MyFlags & (MY_FNABP | MY_NABP))); /* for my_read/my_write */
   if (MyFlags & MY_HOLD_ORIGINAL_MODES)     /* Copy stat if possible */
     new_file_stat= test(my_stat((char*) to, &new_stat_buff, MYF(0)));
   if ((from_file=my_open(from,O_RDONLY | O_SHARE,MyFlags)) >= 0)
   {
     if (!my_stat(from, &stat_buff, MyFlags))
     {
       my_errno=errno;
       goto err;
     }
     if (MyFlags & MY_HOLD_ORIGINAL_MODES && new_file_stat)
       stat_buff=new_stat_buff;
     create_flag= (MyFlags & MY_DONT_OVERWRITE_FILE) ? O_EXCL : O_TRUNC;
     if ((to_file=  my_create(to,(int) stat_buff.st_mode,
                  O_WRONLY | create_flag | O_BINARY | O_SHARE,
                  MyFlags)) < 0)
       goto err;
     while ((Count=my_read(from_file, buff, sizeof(buff), MyFlags)) != 0)
     {
     if (Count == (uint) -1 ||
         my_write(to_file,buff,Count,MYF(MyFlags | MY_NABP)))
     goto err;
     }
     /* sync the destination file */
     if (MyFlags & MY_SYNC)
     {
       if (my_sync(to_file, MyFlags))
         goto err;
     }
     if (my_close(from_file,MyFlags) | my_close(to_file,MyFlags))
       DBUG_RETURN(-1);              /* Error on close */
     /* Copy modes if possible */
     if (MyFlags & MY_HOLD_ORIGINAL_MODES && !new_file_stat)
     DBUG_RETURN(0);         /* File copyed but not stat */
     /* Copy modes */
     if (chmod(to, stat_buff.st_mode & 07777))
     {
       my_errno= errno;
       if (MyFlags & (MY_FAE+MY_WME))
         my_error(EE_CHANGE_PERMISSIONS, MYF(ME_BELL+ME_WAITTANG), from, errno);
       goto err;
     }
 #if !defined(__WIN__)
     /* Copy ownership */
     if (chown(to, stat_buff.st_uid, stat_buff.st_gid))
     {
       my_errno= errno;
       if (MyFlags & (MY_FAE+MY_WME))
         my_error(EE_CHANGE_OWNERSHIP, MYF(ME_BELL+ME_WAITTANG), from, errno);
       goto err;
     }
 #endif
     if (MyFlags & MY_COPYTIME)
     {
       struct utimbuf timep;
       timep.actime  = stat_buff.st_atime;
       timep.modtime = stat_buff.st_mtime;
       (void) utime((char*) to, &timep); /* last accessed and modified times */
     }
     DBUG_RETURN(0);
   }
 err:
   if (from_file >= 0) (void) my_close(from_file,MyFlags);
   if (to_file >= 0)
   {
     (void) my_close(to_file, MyFlags);
     /* attempt to delete the to-file we've partially written */
     (void) my_delete(to, MyFlags);
   }
   DBUG_RETURN(-1);
 } /* my_copy */
References utimbuf::actime, Acore::Count(), DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CHANGE_OWNERSHIP, EE_CHANGE_PERMISSIONS, errno, IO_SIZE, ME_BELL, ME_WAITTANG, utimbuf::modtime, my_close(), MY_COPYTIME, my_create(), my_delete(), MY_DONT_OVERWRITE_FILE, my_errno, my_error(), MY_FAE, MY_FNABP, MY_HOLD_ORIGINAL_MODES, MY_NABP, my_open(), my_read, MY_STAT, my_stat(), MY_SYNC, my_sync(), MY_WME, my_write, MYF, O_BINARY, O_SHARE, and test.
my_copystat()
int my_copystat (const char * from, const char * to, int MyFlags)
Definition at line 76 of file my_redel.c.
 {
   struct stat statbuf;
   if (stat(from, &statbuf))
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_STAT, MYF(ME_BELL+ME_WAITTANG),from,errno);
     return -1;              /* Can't get stat on input file */
   }
   if ((statbuf.st_mode & S_IFMT) != S_IFREG)
     return 1;
   /* Copy modes */
   if (chmod(to, statbuf.st_mode & 07777))
   {
     my_errno= errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_CHANGE_PERMISSIONS, MYF(ME_BELL+ME_WAITTANG), from, errno);
     return -1;
   }
 #if !defined(__WIN__)
   if (statbuf.st_nlink > 1 && MyFlags & MY_LINK_WARNING)
   {
     if (MyFlags & MY_LINK_WARNING)
       my_error(EE_LINK_WARNING,MYF(ME_BELL+ME_WAITTANG),from,statbuf.st_nlink);
   }
   /* Copy ownership */
   if (chown(to, statbuf.st_uid, statbuf.st_gid))
   {
     my_errno= errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_CHANGE_OWNERSHIP, MYF(ME_BELL+ME_WAITTANG), from, errno);
     return -1;
   }
 #endif /* !__WIN__ */
   if (MyFlags & MY_COPYTIME)
   {
     struct utimbuf timep;
     timep.actime  = statbuf.st_atime;
     timep.modtime = statbuf.st_mtime;
     (void) utime((char*) to, &timep);/* Update last accessed and modified times */
   }
   return 0;
 } /* my_copystat */
References utimbuf::actime, EE_CHANGE_OWNERSHIP, EE_CHANGE_PERMISSIONS, EE_LINK_WARNING, EE_STAT, errno, ME_BELL, ME_WAITTANG, utimbuf::modtime, MY_COPYTIME, my_errno, my_error(), MY_FAE, MY_LINK_WARNING, MY_WME, and MYF.
Referenced by my_redel().
my_create()
File my_create (const char * FileName, int CreateFlags, int AccessFlags, myf MyFlags)
Definition at line 35 of file my_create.c.
 {
   int fd, rc;
   DBUG_ENTER("my_create");
   DBUG_PRINT("my",("Name: '%s' CreateFlags: %d  AccessFlags: %d  MyFlags: %d",
            FileName, CreateFlags, access_flags, MyFlags));
 #if defined(_WIN32)
   fd= my_win_open(FileName, access_flags | O_CREAT);
 #else
   fd= open((char *) FileName, access_flags | O_CREAT,
         CreateFlags ? CreateFlags : my_umask);
 #endif
   if ((MyFlags & MY_SYNC_DIR) && (fd >=0) &&
       my_sync_dir_by_file(FileName, MyFlags))
   {
     my_close(fd, MyFlags);
     fd= -1;
   }
   rc= my_register_filename(fd, FileName, FILE_BY_CREATE,
                            EE_CANTCREATEFILE, MyFlags);
   /*
     my_register_filename() may fail on some platforms even if the call to
     *open() above succeeds. In this case, don't leave the stale file because
     callers assume the file to not exist if my_create() fails, so they don't
     do any cleanups.
   */
   if (unlikely(fd >= 0 && rc < 0))
   {
     int tmp= my_errno;
     my_close(fd, MyFlags);
     my_delete(FileName, MyFlags);
     my_errno= tmp;
   }
   DBUG_RETURN(rc);
 } /* my_create */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTCREATEFILE, FILE_BY_CREATE, my_close(), my_delete(), my_errno, my_register_filename(), MY_SYNC_DIR, my_sync_dir_by_file(), my_umask, open, and unlikely.
Referenced by create_temp_file(), inline_mysql_file_create(), my_copy(), and my_create_with_symlink().
my_create_with_symlink()
File my_create_with_symlink (const char * linkname, const char * filename, int createflags, int access_flags, myf MyFlags)
Definition at line 27 of file my_symlink2.c.
 {
   File file;
   int tmp_errno;
   /* Test if we should create a link */
   int create_link;
   char abs_linkname[FN_REFLEN];
   DBUG_ENTER("my_create_with_symlink");
   DBUG_PRINT("enter", ("linkname: %s  filename: %s",
                        linkname ? linkname : "(null)",
                        filename ? filename : "(null)"));
   if (my_disable_symlinks)
   {
     DBUG_PRINT("info", ("Symlinks disabled"));
     /* Create only the file, not the link and file */
     create_link= 0;
     if (linkname)
       filename= linkname;
   }
   else
   {
     if (linkname)
       my_realpath(abs_linkname, linkname, MYF(0));
     create_link= (linkname && strcmp(abs_linkname,filename));
   }
   if (!(MyFlags & MY_DELETE_OLD))
   {
     if (!access(filename,F_OK))
     {
       my_errno= errno= EEXIST;
       my_error(EE_CANTCREATEFILE, MYF(0), filename, EEXIST);
       DBUG_RETURN(-1);
     }
     if (create_link && !access(linkname,F_OK))
     {
       my_errno= errno= EEXIST;
       my_error(EE_CANTCREATEFILE, MYF(0), linkname, EEXIST);
       DBUG_RETURN(-1);
     }
   }
   if ((file=my_create(filename, createflags, access_flags, MyFlags)) >= 0)
   {
     if (create_link)
     {
       /* Delete old link/file */
       if (MyFlags & MY_DELETE_OLD)
     my_delete(linkname, MYF(0));
       /* Create link */
       if (my_symlink(filename, linkname, MyFlags))
       {
     /* Fail, remove everything we have done */
     tmp_errno=my_errno;
     my_close(file,MYF(0));
     my_delete(filename, MYF(0));
     file= -1;
     my_errno=tmp_errno;
       }
     }
   }
   DBUG_RETURN(file);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTCREATEFILE, errno, mpq::file, FN_REFLEN, my_close(), my_create(), my_delete(), MY_DELETE_OLD, my_disable_symlinks, my_errno, my_error(), my_realpath(), my_symlink(), and MYF.
Referenced by inline_mysql_file_create_with_symlink().
my_delete()
int my_delete (const char * name, myf MyFlags)
Definition at line 20 of file my_delete.c.
 {
   int err;
   DBUG_ENTER("my_delete");
   DBUG_PRINT("my",("name %s MyFlags %d", name, MyFlags));
   if ((err = unlink(name)) == -1)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_DELETE,MYF(ME_BELL+ME_WAITTANG+(MyFlags & ME_NOINPUT)),
            name,errno);
   }
   else if ((MyFlags & MY_SYNC_DIR) &&
            my_sync_dir_by_file(name, MyFlags))
     err= -1;
   DBUG_RETURN(err);
 } /* my_delete */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_DELETE, errno, ME_BELL, ME_NOINPUT, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_SYNC_DIR, my_sync_dir_by_file(), MY_WME, and MYF.
Referenced by cache_remove_open_tmp(), close_cached_file(), create_temp_file(), inline_mysql_file_delete(), my_copy(), my_create(), my_create_with_symlink(), my_delete_with_symlink(), my_rename(), and my_rename_with_symlink().
my_delete_with_symlink()
int my_delete_with_symlink (const char * name, myf MyFlags)
Definition at line 98 of file my_symlink2.c.
 {
   char link_name[FN_REFLEN];
   int was_symlink= (!my_disable_symlinks &&
             !my_readlink(link_name, name, MYF(0)));
   int result;
   DBUG_ENTER("my_delete_with_symlink");
   if (!(result=my_delete(name, MyFlags)))
   {
     if (was_symlink)
       result=my_delete(link_name, MyFlags);
   }
   DBUG_RETURN(result);
 }
References DBUG_ENTER, DBUG_RETURN, FN_REFLEN, my_delete(), my_disable_symlinks, my_readlink(), and MYF.
Referenced by inline_mysql_file_delete_with_symlink().
my_end()
void my_end (int infoflag)
Definition at line 158 of file my_init.c.
 {
   /*
     this code is suboptimal to workaround a bug in
     Sun CC: Sun C++ 5.6 2004/06/02 for x86, and should not be
     optimized until this compiler is not in use anymore
   */
   FILE *info_file= DBUG_FILE;
   my_bool print_info= (info_file != stderr);
   if (!my_init_done)
     return;
   /*
     We do not use DBUG_ENTER here, as after cleanup DBUG is no longer
     operational, so we cannot use DBUG_RETURN.
   */
   DBUG_PRINT("info",("Shutting down: infoflag: %d  print_info: %d",
                      infoflag, print_info));
   if (!info_file)
   {
     info_file= stderr;
     print_info= 0;
   }
   if ((infoflag & MY_CHECK_ERROR) || print_info)
   {                 /* Test if some file is left open */
     if (my_file_opened | my_stream_opened)
     {
       char ebuff[512];
       my_snprintf(ebuff, sizeof(ebuff), EE(EE_OPEN_WARNING),
                   my_file_opened, my_stream_opened);
       my_message_stderr(EE_OPEN_WARNING, ebuff, ME_BELL);
       DBUG_PRINT("error", ("%s", ebuff));
       my_print_open_files();
     }
   }
   free_charsets();
   my_error_unregister_all();
   my_once_free();
   if ((infoflag & MY_GIVE_INFO) || print_info)
   {
 #ifdef HAVE_GETRUSAGE
     struct rusage rus;
 #ifdef HAVE_purify
     /* Purify assumes that rus is uninitialized after getrusage call */
     bzero((char*) &rus, sizeof(rus));
 #endif
     if (!getrusage(RUSAGE_SELF, &rus))
       fprintf(info_file,"\n\
 User time %.2f, System time %.2f\n\
 Maximum resident set size %ld, Integral resident set size %ld\n\
 Non-physical pagefaults %ld, Physical pagefaults %ld, Swaps %ld\n\
 Blocks in %ld out %ld, Messages in %ld out %ld, Signals %ld\n\
 Voluntary context switches %ld, Involuntary context switches %ld\n",
           (rus.ru_utime.tv_sec * SCALE_SEC +
            rus.ru_utime.tv_usec / SCALE_USEC) / 100.0,
           (rus.ru_stime.tv_sec * SCALE_SEC +
            rus.ru_stime.tv_usec / SCALE_USEC) / 100.0,
           rus.ru_maxrss, rus.ru_idrss,
           rus.ru_minflt, rus.ru_majflt,
           rus.ru_nswap, rus.ru_inblock, rus.ru_oublock,
           rus.ru_msgsnd, rus.ru_msgrcv, rus.ru_nsignals,
           rus.ru_nvcsw, rus.ru_nivcsw);
 #endif
 #if defined(__WIN__) && defined(_MSC_VER)
    _CrtSetReportMode( _CRT_WARN, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_WARN, _CRTDBG_FILE_STDERR );
    _CrtSetReportMode( _CRT_ERROR, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_ERROR, _CRTDBG_FILE_STDERR );
    _CrtSetReportMode( _CRT_ASSERT, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_ASSERT, _CRTDBG_FILE_STDERR );
    _CrtCheckMemory();
    _CrtDumpMemoryLeaks();
 #endif
   }
   if (!(infoflag & MY_DONT_FREE_DBUG))
   {
     DBUG_END();                /* Must be done before my_thread_end */
   }
   my_thread_end();
   my_thread_global_end();
 #if defined(SAFE_MUTEX)
   /*
     Check on destroying of mutexes. A few may be left that will get cleaned
     up by C++ destructors
   */
   safe_mutex_end((infoflag & (MY_GIVE_INFO | MY_CHECK_ERROR)) ? stderr :
                  (FILE *) 0);
 #endif /* defined(SAFE_MUTEX) */
 #ifdef __WIN__
   if (have_tcpip)
     WSACleanup();
 #endif /* __WIN__ */
   my_init_done=0;
   my_basic_init_done= 0;
 } /* my_end */
References bzero, DBUG_END, DBUG_FILE, DBUG_PRINT, EE, EE_OPEN_WARNING, fprintf(), free_charsets(), ME_BELL, my_basic_init_done, MY_CHECK_ERROR, MY_DONT_FREE_DBUG, my_error_unregister_all(), my_file_opened, MY_GIVE_INFO, my_init_done, my_message_stderr(), my_once_free(), my_print_open_files, my_snprintf(), my_stream_opened, my_thread_end(), my_thread_global_end(), safe_mutex_end(), SCALE_SEC, and SCALE_USEC.
Referenced by mysql_server_end().
my_error()
void my_error (int nr, myf MyFlags, ...)
Definition at line 71 of file my_error.c.
 {
   const char *format;
   struct my_err_head *meh_p;
   va_list args;
   char ebuff[ERRMSGSIZE];
   DBUG_ENTER("my_error");
   DBUG_PRINT("my", ("nr: %d  MyFlags: %d  errno: %d", nr, MyFlags, errno));
   /* Search for the error messages array, which could contain the message. */
   for (meh_p= my_errmsgs_list; meh_p; meh_p= meh_p->meh_next)
     if (nr <= meh_p->meh_last)
       break;
   /* get the error message string. Default, if NULL or empty string (""). */
   if (! (format= (meh_p && (nr >= meh_p->meh_first)) ?
                   meh_p->get_errmsgs()[nr - meh_p->meh_first] : NULL) || ! *format)
     (void) my_snprintf (ebuff, sizeof(ebuff), "Unknown error %d", nr);
   else
   {
     va_start(args,MyFlags);
     (void) my_vsnprintf_ex(&my_charset_utf8_general_ci, ebuff,
                            sizeof(ebuff), format, args);
     va_end(args);
   }
   (*error_handler_hook)(nr, ebuff, MyFlags);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ERRMSGSIZE, errno, format(), my_err_head::get_errmsgs, my_err_head::meh_first, my_err_head::meh_last, my_err_head::meh_next, my_charset_utf8_general_ci, my_errmsgs_list, my_snprintf(), my_vsnprintf_ex(), and NULL.
Referenced by get_charset(), get_charset_by_csname(), get_charset_by_name(), init_key_cache(), my_chsize(), my_close(), my_copy(), my_copystat(), my_create_with_symlink(), my_delete(), my_dir(), my_fclose(), my_fdopen(), my_fopen(), my_fread(), my_fwrite(), my_getwd(), my_lock(), my_malloc(), my_mkdir(), my_net_read(), my_once_alloc(), my_pread(), my_pwrite(), my_read(), my_readlink(), my_real_read(), my_realloc(), my_realpath(), my_register_filename(), my_rename(), my_rename_with_symlink(), my_seek(), my_setwd(), my_stat(), my_symlink(), my_sync(), my_tell(), my_write(), net_real_write(), net_realloc(), and wait_for_free_space().
my_error_register()
int my_error_register (const char **(*)() get_errmsgs, int first, int last)
Definition at line 189 of file my_error.c.
 {
   struct my_err_head *meh_p;
   struct my_err_head **search_meh_pp;
   /* Allocate a new header structure. */
   if (! (meh_p= (struct my_err_head*) my_malloc(sizeof(struct my_err_head),
                                                 MYF(MY_WME))))
     return 1;
   meh_p->get_errmsgs= get_errmsgs;
   meh_p->meh_first= first;
   meh_p->meh_last= last;
   /* Search for the right position in the list. */
   for (search_meh_pp= &my_errmsgs_list;
        *search_meh_pp;
        search_meh_pp= &(*search_meh_pp)->meh_next)
   {
     if ((*search_meh_pp)->meh_last > first)
       break;
   }
   /* Error numbers must be unique. No overlapping is allowed. */
   if (*search_meh_pp && ((*search_meh_pp)->meh_first <= last))
   {
     my_free(meh_p);
     return 1;
   }
   /* Insert header into the chain. */
   meh_p->meh_next= *search_meh_pp;
   *search_meh_pp= meh_p;
   return 0;
 }
References detail::first(), my_err_head::get_errmsgs, my_err_head::meh_first, my_err_head::meh_last, my_err_head::meh_next, my_errmsgs_list, my_free(), my_malloc(), MY_WME, and MYF.
Referenced by init_client_errs(), and my_handler_error_register().
my_error_unregister()
const char** my_error_unregister (int first, int last)
Definition at line 246 of file my_error.c.
 {
   struct my_err_head    *meh_p;
   struct my_err_head    **search_meh_pp;
   const char            **errmsgs;
   /* Search for the registration in the list. */
   for (search_meh_pp= &my_errmsgs_list;
        *search_meh_pp;
        search_meh_pp= &(*search_meh_pp)->meh_next)
   {
     if (((*search_meh_pp)->meh_first == first) &&
         ((*search_meh_pp)->meh_last == last))
       break;
   }
   if (! *search_meh_pp)
     return NULL;
   /* Remove header from the chain. */
   meh_p= *search_meh_pp;
   *search_meh_pp= meh_p->meh_next;
   /* Save the return value and free the header. */
   errmsgs= meh_p->get_errmsgs();
   my_free(meh_p);
   return errmsgs;
 }
References detail::first(), my_err_head::get_errmsgs, my_err_head::meh_next, my_errmsgs_list, my_free(), and NULL.
Referenced by finish_client_errs(), and my_handler_error_unregister().
my_fclose()
int my_fclose (FILE * fd, myf MyFlags)
Definition at line 227 of file my_fopen.c.
 {
   int err,file;
   DBUG_ENTER("my_fclose");
   DBUG_PRINT("my",("stream: 0x%lx  MyFlags: %d", (long) fd, MyFlags));
   mysql_mutex_lock(&THR_LOCK_open);
   file= my_fileno(fd);
 #ifndef _WIN32
   err= fclose(fd);
 #else
   err= my_win_fclose(fd);
 #endif
   if(err < 0)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_BADCLOSE, MYF(ME_BELL+ME_WAITTANG),
            my_filename(file),errno);
   }
   else
     my_stream_opened--;
   if ((uint) file < my_file_limit && my_file_info[file].type != UNOPEN)
   {
     my_file_info[file].type = UNOPEN;
     my_free(my_file_info[file].name);
   }
   mysql_mutex_unlock(&THR_LOCK_open);
   DBUG_RETURN(err);
 } /* my_fclose */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_BADCLOSE, errno, mpq::file, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_filename(), my_fileno(), my_free(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
Referenced by inline_mysql_file_fclose(), and my_fopen().
my_fdopen()
FILE* my_fdopen (File Filedes, const char * name, int Flags, myf MyFlags)
Definition at line 262 of file my_fopen.c.
 {
   FILE *fd;
   char type[5];
   DBUG_ENTER("my_fdopen");
   DBUG_PRINT("my",("Fd: %d  Flags: %d  MyFlags: %d",
            Filedes, Flags, MyFlags));
   make_ftype(type,Flags);
 #ifdef _WIN32
   fd= my_win_fdopen(Filedes, type);
 #else
   fd= fdopen(Filedes, type);
 #endif
   if (!fd)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_CANT_OPEN_STREAM, MYF(ME_BELL+ME_WAITTANG),errno);
   }
   else
   {
     mysql_mutex_lock(&THR_LOCK_open);
     my_stream_opened++;
     if ((uint) Filedes < (uint) my_file_limit)
     {
       if (my_file_info[Filedes].type != UNOPEN)
       {
         my_file_opened--;       /* File is opened with my_open ! */
       }
       else
       {
         my_file_info[Filedes].name=  my_strdup(name,MyFlags);
       }
       my_file_info[Filedes].type = STREAM_BY_FDOPEN;
     }
     mysql_mutex_unlock(&THR_LOCK_open);
   }
   DBUG_PRINT("exit",("stream: 0x%lx", (long) fd));
   DBUG_RETURN(fd);
 } /* my_fdopen */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_OPEN_STREAM, errno, make_ftype(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_file_opened, my_strdup(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, st_my_file_info::name, STREAM_BY_FDOPEN, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
my_filename()
char* my_filename (File fd)
Definition at line 26 of file my_div.c.
 {
   DBUG_ENTER("my_filename");
   if ((uint) fd >= (uint) my_file_limit)
     DBUG_RETURN((char*) "UNKNOWN");
   if (fd >= 0 && my_file_info[fd].type != UNOPEN)
   {
     DBUG_RETURN(my_file_info[fd].name);
   }
   else
     DBUG_RETURN((char*) "UNOPENED");    /* Debug message */
 }
References DBUG_ENTER, DBUG_RETURN, my_file_info, my_file_limit, and UNOPEN.
Referenced by key_cache_read(), key_cache_write(), my_close(), my_fclose(), my_fread(), my_fwrite(), my_pread(), my_pwrite(), my_read(), my_seek(), my_sync(), my_tell(), and my_write().
my_fileno()
File my_fileno (FILE * fd)
Definition at line 187 of file my_fstream.c.
 {
 #ifdef _WIN32
   return my_win_fileno(f);
 #else
  return fileno(f);
 #endif
 }
References f().
Referenced by my_fclose(), my_fopen(), my_fread(), and my_fwrite().
my_fopen()
FILE* my_fopen (const char * FileName, int Flags, myf MyFlags)
Definition at line 41 of file my_fopen.c.
 {
   FILE *fd;
   char type[5];
   DBUG_ENTER("my_fopen");
   DBUG_PRINT("my",("Name: '%s'  flags: %d  MyFlags: %d",
            filename, flags, MyFlags));
   make_ftype(type,flags);
 #ifdef _WIN32
   fd= my_win_fopen(filename, type);
 #else
   fd= fopen(filename, type);
 #endif
   if (fd != 0)
   {
     /*
       The test works if MY_NFILE < 128. The problem is that fileno() is char
       on some OS (SUNOS). Actually the filename save isn't that important
       so we can ignore if this doesn't work.
     */
     int filedesc= my_fileno(fd);
     if ((uint)filedesc >= my_file_limit)
     {
       thread_safe_increment(my_stream_opened,&THR_LOCK_open);
       DBUG_RETURN(fd);              /* safeguard */
     }
     mysql_mutex_lock(&THR_LOCK_open);
     if ((my_file_info[filedesc].name= (char*)
      my_strdup(filename,MyFlags)))
     {
       my_stream_opened++;
       my_file_total_opened++;
       my_file_info[filedesc].type= STREAM_BY_FOPEN;
       mysql_mutex_unlock(&THR_LOCK_open);
       DBUG_PRINT("exit",("stream: 0x%lx", (long) fd));
       DBUG_RETURN(fd);
     }
     mysql_mutex_unlock(&THR_LOCK_open);
     (void) my_fclose(fd,MyFlags);
     my_errno=ENOMEM;
   }
   else
     my_errno=errno;
   DBUG_PRINT("error",("Got error %d on open",my_errno));
   if (MyFlags & (MY_FFNF | MY_FAE | MY_WME))
     my_error((flags & O_RDONLY) || (flags == O_RDONLY ) ? EE_FILENOTFOUND :
          EE_CANTCREATEFILE,
          MYF(ME_BELL+ME_WAITTANG), filename, my_errno);
   DBUG_RETURN((FILE*) 0);
 } /* my_fopen */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTCREATEFILE, EE_FILENOTFOUND, errno, make_ftype(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_fclose(), MY_FFNF, my_file_info, my_file_limit, my_file_total_opened, my_fileno(), my_strdup(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, STREAM_BY_FOPEN, THR_LOCK_open, thread_safe_increment, and st_my_file_info::type.
Referenced by inline_mysql_file_fopen().
my_fread()
size_t my_fread (FILE * stream, uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 45 of file my_fstream.c.
 {
   size_t readbytes;
   DBUG_ENTER("my_fread");
   DBUG_PRINT("my",("stream: 0x%lx  Buffer: 0x%lx  Count: %u  MyFlags: %d",
            (long) stream, (long) Buffer, (uint) Count, MyFlags));
   if ((readbytes= fread(Buffer, sizeof(char), Count, stream)) != Count)
   {
     DBUG_PRINT("error",("Read only %d bytes", (int) readbytes));
     if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
     {
       if (ferror(stream))
     my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
          my_filename(my_fileno(stream)),errno);
       else
       if (MyFlags & (MY_NABP | MY_FNABP))
     my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
          my_filename(my_fileno(stream)),errno);
     }
     my_errno=errno ? errno : -1;
     if (ferror(stream) || MyFlags & (MY_NABP | MY_FNABP))
       DBUG_RETURN((size_t) -1);         /* Return with error */
   }
   if (MyFlags & (MY_NABP | MY_FNABP))
     DBUG_RETURN(0);             /* Read ok */
   DBUG_RETURN(readbytes);
 } /* my_fread */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_filename(), my_fileno(), MY_FNABP, MY_NABP, MY_WME, and MYF.
Referenced by inline_mysql_file_fread().
my_free()
void my_free (void * ptr)
Free memory allocated with my_malloc.
Remarks
Relies on free being able to handle a NULL argument.
Parameters
ptr Pointer to the memory allocated by my_malloc.
Definition at line 124 of file my_malloc.c.
 {
   DBUG_ENTER("my_free");
   DBUG_PRINT("my",("ptr: %p", ptr));
   free(ptr);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, and ptr().
Referenced by _lf_dynarray_lvalue(), add_init_command(), bitmap_free(), CLI_MYSQL_REAL_CONNECT(), cli_stmt_execute(), cli_use_result(), close_cached_file(), default_local_infile_end(), delete_dynamic(), delete_queue(), delete_tree_element(), dynstr_free(), end_io_cache(), end_key_cache(), fini_one_value(), flush_key_blocks_int(), free_root(), free_rows(), free_tmpdir(), handle_local_infile(), init_key_cache(), init_one_value(), initialize_bucket(), inline_mysql_file_fclose(), inline_mysql_file_fopen(), lf_alloc_destroy(), lf_hash_destroy(), list_free(), load_env_plugins(), my_close(), my_dir(), my_dirend(), my_error_register(), my_error_unregister(), my_error_unregister_all(), my_fclose(), my_free_open_file_info(), my_read_charset_file(), my_realloc(), my_stat(), my_string_ptr_sort(), mysql_change_user(), mysql_close(), mysql_close_free(), mysql_close_free_options(), mysql_free_result(), mysql_options(), mysql_read_default_options(), mysql_select_db(), mysql_stmt_close(), mysql_store_result(), net_end(), net_real_write(), open_cached_file(), recursive_free(), reset_root_defaults(), safe_hash_entry_free(), safe_hash_set(), setval(), thr_end_alarm(), tree_delete(), vio_delete(), and vio_reset().
my_free_open_file_info()
void my_free_open_file_info (void)
Definition at line 122 of file my_file.c.
 {
   DBUG_ENTER("my_free_file_info");
   if (my_file_info != my_file_info_default)
   {
     /* Copy data back for my_print_open_files */
     memcpy((char*) my_file_info_default, my_file_info,
            sizeof(*my_file_info_default)* MY_NFILE);
     my_free(my_file_info);
     my_file_info= my_file_info_default;
     my_file_limit= MY_NFILE;
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, memcpy, my_file_info, my_file_info_default, my_file_limit, my_free(), and MY_NFILE.
Referenced by my_set_max_open_files().
my_freopen()
FILE* my_freopen (const char * path, const char * mode, FILE * stream)
Change the file associated with a file stream.
Parameters
path Path to file.
mode Mode of the stream.
stream File stream.
Note
This function is used to redirect stdout and stderr to a file and subsequently to close and reopen that file for log rotation.
Return values
A FILE pointer on success. Otherwise, NULL.
Definition at line 202 of file my_fopen.c.
 {
   FILE *result;
 #if defined(_WIN32)
   result= my_win_freopen(path, mode, stream);
 #elif defined(__FreeBSD__)
   /*
     XXX: Once the fix is ported to the stable releases, this should
          be dependent upon the specific FreeBSD versions. Check at:
          http://www.freebsd.org/cgi/query-pr.cgi?pr=79887
   */
   if (getosreldate() > 900027)
     result= freopen(path, mode, stream);
   else
     result= my_freebsd_freopen(path, mode, stream);
 #else
   result= freopen(path, mode, stream);
 #endif
   return result;
 }
my_fseek()
my_off_t my_fseek (FILE * stream, my_off_t pos, int whence, myf MyFlags)
Referenced by inline_mysql_file_fseek().
my_ftell()
my_off_t my_ftell (FILE * stream, myf MyFlags)
Referenced by inline_mysql_file_ftell().
my_fwrite()
size_t my_fwrite (FILE * stream, const uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 89 of file my_fstream.c.
 {
   size_t writtenbytes =0;
   my_off_t seekptr;
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
   uint errors;
 #endif
   DBUG_ENTER("my_fwrite");
   DBUG_PRINT("my",("stream: 0x%lx  Buffer: 0x%lx  Count: %u  MyFlags: %d",
            (long) stream, (long) Buffer, (uint) Count, MyFlags));
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
   errors=0;
 #endif
   seekptr= ftell(stream);
   for (;;)
   {
     size_t written;
     if ((written = (size_t) fwrite((char*) Buffer,sizeof(char),
                                    Count, stream)) != Count)
     {
       DBUG_PRINT("error",("Write only %d bytes", (int) writtenbytes));
       my_errno=errno;
       if (written != (size_t) -1)
       {
     seekptr+=written;
     Buffer+=written;
     writtenbytes+=written;
     Count-=written;
       }
 #ifdef EINTR
       if (errno == EINTR)
       {
     (void) my_fseek(stream,seekptr,MY_SEEK_SET,MYF(0));
     continue;
       }
 #endif
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
       if (my_thread_var->abort)
     MyFlags&= ~ MY_WAIT_IF_FULL;        /* End if aborted by user */
       if ((errno == ENOSPC || errno == EDQUOT) &&
           (MyFlags & MY_WAIT_IF_FULL))
       {
         wait_for_free_space("[stream]", errors);
         errors++;
         (void) my_fseek(stream,seekptr,MY_SEEK_SET,MYF(0));
         continue;
       }
 #endif
       if (ferror(stream) || (MyFlags & (MY_NABP | MY_FNABP)))
       {
     if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
     {
       my_error(EE_WRITE, MYF(ME_BELL+ME_WAITTANG),
            my_filename(my_fileno(stream)),errno);
     }
     writtenbytes= (size_t) -1;        /* Return that we got error */
     break;
       }
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       writtenbytes= 0;              /* Everything OK */
     else
       writtenbytes+= written;
     break;
   }
   DBUG_RETURN(writtenbytes);
 } /* my_fwrite */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EDQUOT, EE_WRITE, errno, mpq::errors, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_filename(), my_fileno(), MY_FNABP, my_fseek(), MY_NABP, MY_SEEK_SET, my_thread_var, MY_WAIT_IF_FULL, MY_WME, MYF, and wait_for_free_space().
Referenced by inline_mysql_file_fwrite(), and my_b_copy_to_file().
my_get_ptr()
my_off_t my_get_ptr (uchar * ptr, size_t pack_length)
Definition at line 205 of file ptr_cmp.c.
 {
   my_off_t pos;
   switch (pack_length) {
 #if SIZEOF_OFF_T > 4
   case 8: pos= (my_off_t) mi_uint8korr(ptr); break;
   case 7: pos= (my_off_t) mi_uint7korr(ptr); break;
   case 6: pos= (my_off_t) mi_uint6korr(ptr); break;
   case 5: pos= (my_off_t) mi_uint5korr(ptr); break;
 #endif
   case 4: pos= (my_off_t) mi_uint4korr(ptr); break;
   case 3: pos= (my_off_t) mi_uint3korr(ptr); break;
   case 2: pos= (my_off_t) mi_uint2korr(ptr); break;
   case 1: pos= (my_off_t) *(uchar*) ptr; break;
   default: DBUG_ASSERT(0); return 0;
   }
  return pos;
 }
References DBUG_ASSERT, mi_uint2korr, mi_uint3korr, mi_uint4korr, mi_uint5korr, mi_uint6korr, mi_uint7korr, mi_uint8korr, pos(), and ptr().
my_gethwaddr()
my_bool my_gethwaddr (uchar * to)
my_getncpus()
int my_getncpus ()
Definition at line 25 of file my_getncpus.c.
 {
   if (!ncpus)
   {
 #ifdef _SC_NPROCESSORS_ONLN
     ncpus= sysconf(_SC_NPROCESSORS_ONLN);
 #elif defined(__WIN__)
     SYSTEM_INFO sysinfo;
     /*
     * We are not calling GetNativeSystemInfo here because (1) we
     * don't believe that they return different values for number
     * of processors and (2) if WOW64 limits processors for Win32
     * then we don't want to try to override that.
     */
     GetSystemInfo(&sysinfo);
     ncpus= sysinfo.dwNumberOfProcessors;
 #else
 /* unknown so play safe: assume SMP and forbid uniprocessor build */
     ncpus= 2;
 #endif
   }
   return ncpus;
 }
References ncpus.
Referenced by my_atomic_initialize().
my_getpagesize()
int my_getpagesize (void)
Definition at line 32 of file my_getpagesize.c.
 {
   return (int)8192;
 }
my_getsystime()
ulonglong my_getsystime (void)
Definition at line 28 of file my_getsystime.c.
 {
 #ifdef HAVE_CLOCK_GETTIME
   struct timespec tp;
   clock_gettime(CLOCK_REALTIME, &tp);
   return (ulonglong)tp.tv_sec*10000000+(ulonglong)tp.tv_nsec/100;
 #elif defined(__WIN__)
   LARGE_INTEGER t_cnt;
   if (query_performance_frequency)
   {
     QueryPerformanceCounter(&t_cnt);
     return ((t_cnt.QuadPart / query_performance_frequency * 10000000) +
             ((t_cnt.QuadPart % query_performance_frequency) * 10000000 /
              query_performance_frequency) + query_performance_offset);
   }
   return 0;
 #else
   /* TODO: check for other possibilities for hi-res timestamping */
   struct timeval tv;
   gettimeofday(&tv,NULL);
   return (ulonglong)tv.tv_sec*10000000+(ulonglong)tv.tv_usec*10;
 #endif
 }
References endif(), NULL, query_performance_frequency, and query_performance_offset.
my_getwd()
int my_getwd (char * buf, size_t size, myf MyFlags)
Definition at line 46 of file my_getwd.c.
 {
   char * pos;
   DBUG_ENTER("my_getwd");
   DBUG_PRINT("my",("buf: 0x%lx  size: %u  MyFlags %d",
                    (long) buf, (uint) size, MyFlags));
   if (size < 1)
     DBUG_RETURN(-1);
   if (curr_dir[0])              /* Current pos is saved here */
     (void) strmake(buf,&curr_dir[0],size-1);
   else
   {
 #if defined(HAVE_GETCWD)
     if (size < 2)
       DBUG_RETURN(-1);
     if (!getcwd(buf,(uint) (size-2)) && MyFlags & MY_WME)
     {
       my_errno=errno;
       my_error(EE_GETWD,MYF(ME_BELL+ME_WAITTANG),errno);
       DBUG_RETURN(-1);
     }
 #elif defined(HAVE_GETWD)
     {
       char pathname[MAXPATHLEN];
       getwd(pathname);
       strmake(buf,pathname,size-1);
     }
 #else
 #error "No way to get current directory"
 #endif
     if (*((pos=strend(buf))-1) != FN_LIBCHAR)  /* End with FN_LIBCHAR */
     {
       pos[0]= FN_LIBCHAR;
       pos[1]=0;
     }
     (void) strmake(&curr_dir[0],buf, (size_t) (FN_REFLEN-1));
   }
   DBUG_RETURN(0);
 } /* my_getwd */
References curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_GETWD, errno, FN_LIBCHAR, FN_REFLEN, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_WME, MYF, pos(), strend(), and strmake().
Referenced by cleanup_dirname(), fn_expand(), my_load_path(), my_path(), and pack_dirname().
my_init()
my_bool my_init (void)
Definition at line 130 of file my_init.c.
 {
   if (my_init_done)
     return 0;
   my_init_done= 1;
   if (my_basic_init())
     return 1;
   if (my_thread_global_init())
     return 1;
   {
     DBUG_ENTER("my_init");
     DBUG_PROCESS((char*) (my_progname ? my_progname : "unknown"));
     my_win_init();
     DBUG_PRINT("exit", ("home: '%s'", home_dir));
 #ifdef __WIN__
     win32_init_tcp_ip();
 #endif
     DBUG_RETURN(0);
   }
 } /* my_init */
References DBUG_ENTER, DBUG_PRINT, DBUG_PROCESS, DBUG_RETURN, home_dir, my_basic_init(), my_init_done, my_progname, my_thread_global_init(), and my_win_init.
Referenced by mysql_server_init().
my_is_symlink()
int my_is_symlink (const char * filename)
my_load_defaults()
int my_load_defaults (const char * conf_file, const char ** groups, int * argc, char *** argv, const char *** default_directories)
Definition at line 494 of file default.c.
 {
   DYNAMIC_ARRAY args;
   TYPELIB group;
   my_bool found_print_defaults= 0;
   uint args_used= 0;
   int error= 0;
   MEM_ROOT alloc;
   char *ptr,**res;
   struct handle_option_ctx ctx;
   const char **dirs;
   DBUG_ENTER("load_defaults");
   init_alloc_root(&alloc,512,0);
   if ((dirs= init_default_directories(&alloc)) == NULL)
     goto err;
   /*
     Check if the user doesn't want any default option processing
     --no-defaults is always the first option
   */
   if (*argc >= 2 && !strcmp(argv[0][1],"--no-defaults"))
   {
     /* remove the --no-defaults argument and return only the other arguments */
     uint i;
     if (!(ptr=(char*) alloc_root(&alloc,sizeof(alloc)+
                  (*argc + 1)*sizeof(char*))))
       goto err;
     res= (char**) (ptr+sizeof(alloc));
     res[0]= **argv;             /* Copy program name */
     /* set arguments separator */
     res[1]= (char *)args_separator;
     for (i=2 ; i < (uint) *argc ; i++)
       res[i]=argv[0][i];
     res[i]=0;                   /* End pointer */
     *argv=res;
     *(MEM_ROOT*) ptr= alloc;            /* Save alloc root for free */
     if (default_directories)
       *default_directories= dirs;
     DBUG_RETURN(0);
   }
   group.count=0;
   group.name= "defaults";
   group.type_names= groups;
   for (; *groups ; groups++)
     group.count++;
   if (my_init_dynamic_array(&args, sizeof(char*),*argc, 32))
     goto err;
   ctx.alloc= &alloc;
   ctx.args= &args;
   ctx.group= &group;
   if ((error= my_search_option_files(conf_file, argc, argv, &args_used,
                                      handle_default_option, (void *) &ctx,
                                      dirs)))
   {
     free_root(&alloc,MYF(0));
     DBUG_RETURN(error);
   }
   /*
     Here error contains <> 0 only if we have a fully specified conf_file
     or a forced default file
   */
   if (!(ptr=(char*) alloc_root(&alloc,sizeof(alloc)+
                    (args.elements + *argc + 1 + 1) *sizeof(char*))))
     goto err;
   res= (char**) (ptr+sizeof(alloc));
   /* copy name + found arguments + command line arguments to new array */
   res[0]= argv[0][0];  /* Name MUST be set, even by embedded library */
   memcpy((uchar*) (res+1), args.buffer, args.elements*sizeof(char*));
   /* Skip --defaults-xxx options */
   (*argc)-= args_used;
   (*argv)+= args_used;
   /*
     Check if we wan't to see the new argument list
     This options must always be the last of the default options
   */
   if (*argc >= 2 && !strcmp(argv[0][1],"--print-defaults"))
   {
     found_print_defaults=1;
     --*argc; ++*argv;               /* skip argument */
   }
   /* set arguments separator for arguments from config file and
      command line */
   res[args.elements+1]= (char *)args_separator;
   if (*argc)
     memcpy((uchar*) (res+1+args.elements+1), (char*) ((*argv)+1),
        (*argc-1)*sizeof(char*));
   res[args.elements+ *argc+1]=0;                /* last null */
   (*argc)+=args.elements+1;
   *argv= (char**) res;
   *(MEM_ROOT*) ptr= alloc;          /* Save alloc root for free */
   delete_dynamic(&args);
   if (found_print_defaults)
   {
     int i;
     printf("%s would have been started with the following arguments:\n",
        **argv);
     for (i=1 ; i < *argc ; i++)
       if ((*argv)[i] != args_separator) /* skip arguments separator */
         printf("%s ", (*argv)[i]);
     puts("");
     exit(0);
   }
   if (default_directories)
     *default_directories= dirs;
   DBUG_RETURN(0);
  err:
   fprintf(stderr,"Fatal error in defaults handling. Program aborted\n");
   exit(1);
   return 0;                 /* Keep compiler happy */
 }
References handle_option_ctx::alloc, alloc_root(), handle_option_ctx::args, args_separator, st_dynamic_array::buffer, st_typelib::count, DBUG_ENTER, DBUG_RETURN, default_directories, delete_dynamic(), st_dynamic_array::elements, error(), fprintf(), free_root(), handle_option_ctx::group, handle_default_option(), if(), init_alloc_root(), init_default_directories(), memcpy, my_init_dynamic_array, my_search_option_files(), MYF, st_typelib::name, NULL, printf(), ptr(), and st_typelib::type_names.
Referenced by load_defaults(), and mysql_read_default_options().
my_load_path()
char* my_load_path (char * to, const char * path, const char * own_path_prefix)
Definition at line 26 of file mf_loadpath.c.
 {
   char buff[FN_REFLEN];
   int is_cur;
   DBUG_ENTER("my_load_path");
   DBUG_PRINT("enter",("path: %s  prefix: %s",path,
               own_path_prefix ? own_path_prefix : ""));
   if ((path[0] == FN_HOMELIB && path[1] == FN_LIBCHAR) ||
       test_if_hard_path(path))
     (void) strnmov(buff, path, FN_REFLEN);
   else if ((is_cur=(path[0] == FN_CURLIB && path[1] == FN_LIBCHAR)) ||
        (is_prefix(path,FN_PARENTDIR)) ||
        ! own_path_prefix)
   {
     if (is_cur)
       is_cur=2;                 /* Remove current dir */
     if (! my_getwd(buff,(uint) (FN_REFLEN-strlen(path)+is_cur),MYF(0)))
       (void) strncat(buff, path+is_cur, FN_REFLEN-1);
     else
       (void) strnmov(buff, path, FN_REFLEN);            /* Return org file name */
   }
   else
     (void) strxnmov(buff, FN_REFLEN, own_path_prefix, path, NullS);
   strnmov(to, buff, FN_REFLEN);
   to[FN_REFLEN-1]= '\0';
   DBUG_PRINT("exit",("to: %s",to));
   DBUG_RETURN(to);
 } /* my_load_path */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FN_CURLIB, FN_HOMELIB, FN_LIBCHAR, FN_PARENTDIR, FN_REFLEN, is_prefix(), my_getwd(), MYF, NullS, strnmov(), strxnmov(), and test_if_hard_path().
Referenced by my_realpath().
my_lock()
int my_lock (File fd, int op, my_off_t start, my_off_t length, myf MyFlags)
Definition at line 138 of file my_lock.c.
 {
 #ifdef HAVE_FCNTL
   int value;
   ALARM_VARIABLES;
 #endif
   DBUG_ENTER("my_lock");
   DBUG_PRINT("my",("fd: %d  Op: %d  start: %ld  Length: %ld  MyFlags: %d",
            fd,locktype,(long) start,(long) length,MyFlags));
   if (my_disable_locking)
     DBUG_RETURN(0);
 #if defined(_WIN32)
   {
     int timeout_sec;
     if (MyFlags & MY_DONT_WAIT)
       timeout_sec= 0;
     else
       timeout_sec= WIN_LOCK_INFINITE;
     if (win_lock(fd, locktype, start, length, timeout_sec) == 0)
       DBUG_RETURN(0);
   }
 #else
 #if defined(HAVE_FCNTL)
   {
     struct flock lock;
     lock.l_type=   (short) locktype;
     lock.l_whence= SEEK_SET;
     lock.l_start=  (off_t) start;
     lock.l_len=    (off_t) length;
     if (MyFlags & MY_DONT_WAIT)
     {
       if (fcntl(fd,F_SETLK,&lock) != -1)    /* Check if we can lock */
     DBUG_RETURN(0);         /* Ok, file locked */
       DBUG_PRINT("info",("Was locked, trying with alarm"));
       ALARM_INIT;
       while ((value=fcntl(fd,F_SETLKW,&lock)) && ! ALARM_TEST &&
          errno == EINTR)
       {         /* Setup again so we don`t miss it */
     ALARM_REINIT;
       }
       ALARM_END;
       if (value != -1)
     DBUG_RETURN(0);
       if (errno == EINTR)
     errno=EAGAIN;
     }
     else if (fcntl(fd,F_SETLKW,&lock) != -1) /* Wait until a lock */
       DBUG_RETURN(0);
   }
 #else
   if (MyFlags & MY_SEEK_NOT_DONE)
   {
     if (my_seek(fd,start,MY_SEEK_SET,MYF(MyFlags & ~MY_SEEK_NOT_DONE))
         == MY_FILEPOS_ERROR)
     {
       /*
         If an error has occured in my_seek then we will already
         have an error code in my_errno; Just return error code.
       */
       DBUG_RETURN(-1);
     }
   }
   if (lockf(fd,locktype,length) != -1)
     DBUG_RETURN(0);
 #endif /* HAVE_FCNTL */
 #endif /* HAVE_LOCKING */
   /* We got an error. We don't want EACCES errors */
   my_errno=(errno == EACCES) ? EAGAIN : errno ? errno : -1;
   if (MyFlags & MY_WME)
   {
     if (locktype == F_UNLCK)
       my_error(EE_CANTUNLOCK,MYF(ME_BELL+ME_WAITTANG),my_errno);
     else
       my_error(EE_CANTLOCK,MYF(ME_BELL+ME_WAITTANG),my_errno);
   }
   DBUG_PRINT("error",("my_errno: %d (%d)",my_errno,errno));
   DBUG_RETURN(-1);
 } /* my_lock */
References ALARM_END, ALARM_INIT, ALARM_REINIT, ALARM_TEST, ALARM_VARIABLES, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTLOCK, EE_CANTUNLOCK, errno, G3D::length(), ME_BELL, ME_WAITTANG, my_disable_locking, MY_DONT_WAIT, my_errno, my_error(), MY_FILEPOS_ERROR, my_seek(), MY_SEEK_NOT_DONE, MY_SEEK_SET, MY_WME, MYF, mpq::off_t, and SEEK_SET.
my_malloc()
void* my_malloc (size_t size, myf my_flags)
Allocate a sized block of memory.
Parameters
size The size of the memory block in bytes.
flags Failure action modifiers (bitmasks).
Returns
A pointer to the allocated memory block, or NULL on failure.
Definition at line 28 of file my_malloc.c.
 {
   void* point;
   DBUG_ENTER("my_malloc");
   DBUG_PRINT("my",("size: %lu  my_flags: %d", (ulong) size, my_flags));
   /* Safety */
   if (!size)
     size=1;
   point= malloc(size);
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     free(point);
                     point= NULL;
                   });
   if (point == NULL)
   {
     my_errno=errno;
     if (my_flags & MY_FAE)
       error_handler_hook=fatal_error_handler_hook;
     if (my_flags & (MY_FAE+MY_WME))
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG+ME_NOREFRESH),size);
     DBUG_EXECUTE_IF("simulate_out_of_memory",
                     DBUG_SET("-d,simulate_out_of_memory"););
     if (my_flags & MY_FAE)
       exit(1);
   }
   else if (my_flags & MY_ZEROFILL)
     bzero(point, size);
   DBUG_PRINT("exit",("ptr: %p", point));
   DBUG_RETURN(point);
 }
References bzero, DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, DBUG_SET, EE_OUTOFMEMORY, errno, error_handler_hook, fatal_error_handler_hook, ME_BELL, ME_NOREFRESH, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_WME, MY_ZEROFILL, MYF, and NULL.
Referenced by _lf_alloc_new(), _lf_dynarray_lvalue(), add_init_command(), alloc_dynamic(), alloc_root(), allocate_dynamic(), bitmap_init(), cache_remove_open_tmp(), cli_read_rows(), cli_use_result(), default_local_infile_init(), flush_key_blocks_int(), handle_local_infile(), init_alloc_root(), init_dynamic_array2(), init_dynamic_string(), init_io_cache(), init_key_cache(), init_queue(), initialize_bucket(), inline_mysql_file_fopen(), list_cons(), my_dir(), my_error_register(), my_memdup(), my_multi_malloc(), my_net_init(), my_read_charset_file(), my_realloc(), my_set_max_open_files(), my_stat(), my_strdup(), my_string_ptr_sort(), my_strndup(), mysql_init(), mysql_list_fields(), mysql_stmt_init(), mysql_stmt_result_metadata(), mysql_store_result(), net_real_write(), reset_root_defaults(), safe_hash_set(), thr_alarm(), tree_insert(), vio_init(), and vio_new().
my_memdup()
void* my_memdup (const void * from, size_t length, myf MyFlags)
Definition at line 133 of file my_malloc.c.
 {
   void *ptr;
   if ((ptr= my_malloc(length,my_flags)) != 0)
     memcpy(ptr, from, length);
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by cli_stmt_execute().
my_memmem()
void* my_memmem (const void * haystack, size_t haystacklen, const void * needle, size_t needlelen)
Definition at line 26 of file my_memmem.c.
 {
   const unsigned char *cursor;
   const unsigned char *last_possible_needle_location =
     (unsigned char *)haystack + haystacklen - needlelen;
   /* Easy answers */
   if (needlelen > haystacklen) return(NULL);
   if (needle == NULL) return(NULL);
   if (haystack == NULL) return(NULL);
   if (needlelen == 0) return(NULL);
   if (haystacklen == 0) return(NULL);
   for (cursor = haystack; cursor <= last_possible_needle_location; cursor++) {
     if (memcmp(needle, cursor, needlelen) == 0) {
       return((void *) cursor);
     }
   }
   return(NULL);
 }
References NULL.
my_message()
void my_message (uint my_err, const char * str, myf MyFlags)
my_message_stderr()
void my_message_stderr (uint my_err, const char * str, myf MyFlags)
Referenced by my_end().
my_micro_time()
ulonglong my_micro_time ()
Definition at line 101 of file my_getsystime.c.
 {
 #if defined(__WIN__)
   ulonglong newtime;
   GetSystemTimeAsFileTime((FILETIME*)&newtime);
   return (newtime/10);
 #elif defined(HAVE_GETHRTIME)
   return gethrtime()/1000;
 #else
   ulonglong newtime;
   struct timeval t;
   /*
     The following loop is here because gettimeofday may fail on some systems
   */
   while (gettimeofday(&t, NULL) != 0)
   {}
   newtime= (ulonglong)t.tv_sec * 1000000 + t.tv_usec;
   return newtime;
 #endif  /* defined(__WIN__) */
 }
References endif(), and NULL.
my_micro_time_and_time()
ulonglong my_micro_time_and_time (time_t * time_arg)
Definition at line 150 of file my_getsystime.c.
 {
 #if defined(__WIN__)
   ulonglong newtime;
   GetSystemTimeAsFileTime((FILETIME*)&newtime);
   *time_arg= (time_t) ((newtime - OFFSET_TO_EPOCH) / 10000000);
   return (newtime/10);
 #elif defined(HAVE_GETHRTIME)
   /*
     Solaris has a very slow time() call. We optimize this by using the very
     fast gethrtime() call and only calling time() every 1/2 second
   */
   static hrtime_t prev_gethrtime= 0;
   static time_t cur_time= 0;
   hrtime_t cur_gethrtime;
   mysql_mutex_lock(&THR_LOCK_time);
   cur_gethrtime= gethrtime();
   /*
     Due to bugs in the Solaris (x86) implementation of gethrtime(),
     the time returned by it might not be monotonic. Don't use the
     cached time(2) value if this is a case.
   */
   if ((prev_gethrtime > cur_gethrtime) ||
       ((cur_gethrtime - prev_gethrtime) > DELTA_FOR_SECONDS))
   {
     cur_time= time(0);
     prev_gethrtime= cur_gethrtime;
   }
   *time_arg= cur_time;
   mysql_mutex_unlock(&THR_LOCK_time);
   return cur_gethrtime/1000;
 #else
   ulonglong newtime;
   struct timeval t;
   /*
     The following loop is here because gettimeofday may fail on some systems
   */
   while (gettimeofday(&t, NULL) != 0)
   {}
   *time_arg= t.tv_sec;
   newtime= (ulonglong)t.tv_sec * 1000000 + t.tv_usec;
   return newtime;
 #endif  /* defined(__WIN__) */
 }
References DELTA_FOR_SECONDS, endif(), mysql_mutex_lock, mysql_mutex_unlock, NULL, OFFSET_TO_EPOCH, and THR_LOCK_time.
Referenced by my_time().
my_mkdir()
int my_mkdir (const char * dir, int Flags, myf MyFlags)
Definition at line 24 of file my_mkdir.c.
 {
   DBUG_ENTER("my_dir");
   DBUG_PRINT("enter",("dir: %s",dir));
 #if  defined(__WIN__)
   if (mkdir((char*) dir))
 #else
   if (mkdir((char*) dir, Flags & my_umask_dir))
 #endif
   {
     my_errno=errno;
     DBUG_PRINT("error",("error %d when creating direcory %s",my_errno,dir));
     if (MyFlags & (MY_FFNF | MY_FAE | MY_WME))
       my_error(EE_CANT_MKDIR,  MYF(ME_BELL+ME_WAITTANG), dir, my_errno);
     DBUG_RETURN(-1);
   }
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_MKDIR, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FFNF, my_umask_dir, MY_WME, and MYF.
my_mmap()
void* my_mmap (void * , size_t , int , int , int , my_off_t)
my_msync()
int my_msync (int , void * , size_t , int)
my_multi_malloc()
void* my_multi_malloc (myf MyFlags, ...)
Definition at line 34 of file mulalloc.c.
 {
   va_list args;
   char **ptr,*start,*res;
   size_t tot_length,length;
   DBUG_ENTER("my_multi_malloc");
   va_start(args,myFlags);
   tot_length=0;
   while ((ptr=va_arg(args, char **)))
   {
     length=va_arg(args,uint);
     tot_length+=ALIGN_SIZE(length);
   }
   va_end(args);
   if (!(start=(char *) my_malloc(tot_length,myFlags)))
     DBUG_RETURN(0); /* purecov: inspected */
   va_start(args,myFlags);
   res=start;
   while ((ptr=va_arg(args, char **)))
   {
     *ptr=res;
     length=va_arg(args,uint);
     res+=ALIGN_SIZE(length);
   }
   va_end(args);
   DBUG_RETURN((void*) start);
 }
References ALIGN_SIZE, DBUG_ENTER, DBUG_RETURN, G3D::length(), my_malloc(), and ptr().
Referenced by CLI_MYSQL_REAL_CONNECT().
my_munmap()
int my_munmap (void * , size_t)
my_once_alloc()
void* my_once_alloc (size_t Size, myf MyFlags)
Definition at line 36 of file my_once.c.
 {
   size_t get_size, max_left;
   uchar* point;
   reg1 USED_MEM *next;
   reg2 USED_MEM **prev;
   Size= ALIGN_SIZE(Size);
   prev= &my_once_root_block;
   max_left=0;
   for (next=my_once_root_block ; next && next->left < Size ; next= next->next)
   {
     if (next->left > max_left)
       max_left=next->left;
     prev= &next->next;
   }
   if (! next)
   {                     /* Time to alloc new block */
     get_size= Size+ALIGN_SIZE(sizeof(USED_MEM));
     if (max_left*4 < my_once_extra && get_size < my_once_extra)
       get_size=my_once_extra;           /* Normal alloc */
     if ((next = (USED_MEM*) malloc(get_size)) == 0)
     {
       my_errno=errno;
       if (MyFlags & (MY_FAE+MY_WME))
     my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG),get_size);
       return((uchar*) 0);
     }
     DBUG_PRINT("test",("my_once_malloc %lu byte malloced", (ulong) get_size));
     next->next= 0;
     next->size= get_size;
     next->left= get_size-ALIGN_SIZE(sizeof(USED_MEM));
     *prev=next;
   }
   point= (uchar*) ((char*) next+ (next->size-next->left));
   next->left-= Size;
   if (MyFlags & MY_ZEROFILL)
     bzero(point, Size);
   return((void*) point);
 } /* my_once_alloc */
References ALIGN_SIZE, bzero, DBUG_PRINT, EE_OUTOFMEMORY, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_once_extra, my_once_root_block, MY_WME, MY_ZEROFILL, MYF, next(), prev(), reg1, reg2, and Acore::Size().
Referenced by add_collation(), cs_alloc(), init_state_maps(), my_once_memdup(), and my_once_strdup().
my_once_free()
void my_once_free (void)
Definition at line 106 of file my_once.c.
 {
   reg1 USED_MEM *next,*old;
   DBUG_ENTER("my_once_free");
   for (next=my_once_root_block ; next ; )
   {
     old=next; next= next->next ;
     free((uchar*) old);
   }
   my_once_root_block=0;
   DBUG_VOID_RETURN;
 } /* my_once_free */
References DBUG_ENTER, DBUG_VOID_RETURN, my_once_root_block, next(), and reg1.
Referenced by my_end().
my_once_memdup()
void* my_once_memdup (const void * src, size_t len, myf myflags)
Definition at line 90 of file my_once.c.
 {
   uchar *dst= my_once_alloc(len, myflags);
   if (dst)
     memcpy(dst, src, len);
   return dst;
 }
References memcpy, and my_once_alloc().
Referenced by cs_copy_data().
my_once_strdup()
char* my_once_strdup (const char * src, myf myflags)
Definition at line 80 of file my_once.c.
 {
   size_t len= strlen(src)+1;
   uchar *dst= my_once_alloc(len, myflags);
   if (dst)
     memcpy(dst, src, len);
   return (char*) dst;
 }
References memcpy, and my_once_alloc().
Referenced by add_collation(), and cs_copy_data().
my_open()
File my_open (const char * FileName, int Flags, myf MyFlags)
Definition at line 35 of file my_open.c.
 {
   File fd;
   DBUG_ENTER("my_open");
   DBUG_PRINT("my",("Name: '%s'  Flags: %d  MyFlags: %d",
            FileName, Flags, MyFlags));
 #if defined(_WIN32)
   fd= my_win_open(FileName, Flags);
 #elif !defined(NO_OPEN_3)
   fd = open(FileName, Flags, my_umask); /* Normal unix */
 #else
   fd = open((char *) FileName, Flags);
 #endif
   DBUG_RETURN(my_register_filename(fd, FileName, FILE_BY_OPEN,
                    EE_FILENOTFOUND, MyFlags));
 } /* my_open */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_FILENOTFOUND, FILE_BY_OPEN, my_register_filename(), my_umask, and open.
Referenced by create_temp_file(), default_local_infile_init(), inline_mysql_file_open(), and my_copy().
my_path()
char* my_path (char * to, const char * progname, const char * own_pathname_part)
Definition at line 32 of file mf_path.c.
 {
   char *start, *end, *prog;
   size_t to_length;
   DBUG_ENTER("my_path");
   start=to;                 /* Return this */
   if (progname && (dirname_part(to, progname, &to_length) ||
            find_file_in_path(to,progname) ||
            ((prog=getenv("_")) != 0 &&
                     dirname_part(to, prog, &to_length))))
   {
     (void) intern_filename(to,to);
     if (!test_if_hard_path(to))
     {
       if (!my_getwd(curr_dir,FN_REFLEN,MYF(0)))
     bchange((uchar*) to, 0, (uchar*) curr_dir, strlen(curr_dir), strlen(to)+1);
     }
   }
   else
   {
     if ((end = getenv("MY_BASEDIR_VERSION")) == 0 &&
     (end = getenv("MY_BASEDIR")) == 0)
     {
 #ifdef DEFAULT_BASEDIR
       end= (char*) DEFAULT_BASEDIR;
 #else
       end= (char*) "/my/";
 #endif
     }
     (void) intern_filename(to,end);
     to=strend(to);
     if (to != start && to[-1] != FN_LIBCHAR)
       *to++ = FN_LIBCHAR;
     (void) strmov(to,own_pathname_part);
   }
   DBUG_PRINT("exit",("to: '%s'",start));
   DBUG_RETURN(start);
 } /* my_path */
References bchange(), curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), find_file_in_path(), FN_LIBCHAR, FN_REFLEN, intern_filename(), my_getwd(), MYF, prog, strend(), strmov(), and test_if_hard_path().
my_pread()
size_t my_pread (File Filedes, uchar * Buffer, size_t Count, my_off_t offset, myf MyFlags)
Definition at line 48 of file my_pread.c.
 {
   size_t readbytes;
   int error= 0;
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
   int save_errno;
 #endif
   DBUG_ENTER("my_pread");
   DBUG_PRINT("my",("fd: %d  Seek: %llu  Buffer: %p  Count: %lu  MyFlags: %d",
              Filedes, (ulonglong)offset, Buffer, (ulong)Count, MyFlags));
   for (;;)
   {
     errno= 0;    /* Linux, Windows don't reset this on EOF/success */
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
     mysql_mutex_lock(&my_file_info[Filedes].mutex);
     readbytes= (uint) -1;
     error= (lseek(Filedes, offset, MY_SEEK_SET) == (my_off_t) -1 ||
            (readbytes= read(Filedes, Buffer, Count)) != Count);
     save_errno= errno;
     mysql_mutex_unlock(&my_file_info[Filedes].mutex);
     if (error)
       errno= save_errno;
 #else
 #if defined(_WIN32)
     readbytes= my_win_pread(Filedes, Buffer, Count, offset);
 #else
     readbytes= pread(Filedes, Buffer, Count, offset);
 #endif
     error= (readbytes != Count);
 #endif
     if(error)
     {
       my_errno= errno ? errno : -1;
       if (errno == 0 || (readbytes != (size_t) -1 &&
                       (MyFlags & (MY_NABP | MY_FNABP))))
          my_errno= HA_ERR_FILE_TOO_SHORT;
       DBUG_PRINT("warning",("Read only %d bytes off %u from %d, errno: %d",
                             (int) readbytes, (uint) Count,Filedes,my_errno));
       if ((readbytes == 0 || readbytes == (size_t) -1) && errno == EINTR)
       {
         DBUG_PRINT("debug", ("my_pread() was interrupted and returned %d",
                              (int) readbytes));
         continue;                              /* Interrupted */
       }
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         if (readbytes == (size_t) -1)
           my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
         else if (MyFlags & (MY_NABP | MY_FNABP))
           my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
       }
       if (readbytes == (size_t) -1 || (MyFlags & (MY_FNABP | MY_NABP)))
         DBUG_RETURN(MY_FILE_ERROR);         /* Return with error */
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       DBUG_RETURN(0);                      /* Read went ok; Return 0 */
     DBUG_RETURN(readbytes);                /* purecov: inspected */
   }
 } /* my_pread */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, error(), HA_ERR_FILE_TOO_SHORT, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_file_info, my_filename(), MY_FNABP, MY_NABP, MY_SEEK_SET, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, and read.
Referenced by inline_mysql_file_pread(), key_cache_read(), and read_block().
my_print_default_files()
void my_print_default_files (const char * conf_file)
Definition at line 1002 of file default.c.
 {
   const char *empty_list[]= { "", 0 };
   my_bool have_ext= fn_ext(conf_file)[0] != 0;
   const char **exts_to_use= have_ext ? empty_list : f_extensions;
   char name[FN_REFLEN], **ext;
   puts("\nDefault options are read from the following files in the given order:");
   if (dirname_length(conf_file))
     fputs(conf_file,stdout);
   else
   {
     const char **dirs;
     MEM_ROOT alloc;
     init_alloc_root(&alloc,512,0);
     if ((dirs= init_default_directories(&alloc)) == NULL)
     {
       fputs("Internal error initializing default directories list", stdout);
     }
     else
     {
       for ( ; *dirs; dirs++)
       {
         for (ext= (char**) exts_to_use; *ext; ext++)
         {
           const char *pos;
           char *end;
           if (**dirs)
             pos= *dirs;
           else if (my_defaults_extra_file)
             pos= my_defaults_extra_file;
           else
             continue;
           end= convert_dirname(name, pos, NullS);
           if (name[0] == FN_HOMELIB)    /* Add . to filenames in home */
             *end++= '.';
           strxmov(end, conf_file, *ext, " ", NullS);
           fputs(name, stdout);
         }
       }
     }
     free_root(&alloc, MYF(0));
   }
   puts("");
 }
References handle_option_ctx::alloc, convert_dirname(), dirname_length(), f_extensions, fn_ext(), FN_HOMELIB, FN_REFLEN, fputs(), free_root(), init_alloc_root(), init_default_directories(), my_defaults_extra_file, MYF, name, NULL, NullS, pos(), and strxmov().
Referenced by print_defaults().
my_printf_error()
void my_printf_error (uint my_err, const char * format, myf MyFlags, ...)
Referenced by my_os_charset_to_mysql_charset(), and wait_for_free_space().
my_printv_error()
void void my_printv_error (uint error, const char * format, myf MyFlags, va_list ap)
Definition at line 139 of file my_error.c.
 {
   char ebuff[ERRMSGSIZE];
   DBUG_ENTER("my_printv_error");
   DBUG_PRINT("my", ("nr: %d  MyFlags: %d  errno: %d  format: %s",
             error, MyFlags, errno, format));
   (void) my_vsnprintf(ebuff, sizeof(ebuff), format, ap);
   (*error_handler_hook)(error, ebuff, MyFlags);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ERRMSGSIZE, errno, error(), format(), and my_vsnprintf().
my_pwrite()
size_t my_pwrite (File Filedes, const uchar * Buffer, size_t Count, my_off_t offset, myf MyFlags)
Definition at line 136 of file my_pread.c.
 {
   size_t writtenbytes, written;
   uint errors;
   DBUG_ENTER("my_pwrite");
   DBUG_PRINT("my",("fd: %d  Seek: %llu  Buffer: %p  Count: %lu  MyFlags: %d",
              Filedes, offset, Buffer, (ulong)Count, MyFlags));
   errors= 0;
   written= 0;
   for (;;)
   {
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
     int error;
     writtenbytes= (size_t) -1;
     mysql_mutex_lock(&my_file_info[Filedes].mutex);
     error= (lseek(Filedes, offset, MY_SEEK_SET) != (my_off_t) -1 &&
             (writtenbytes= write(Filedes, Buffer, Count)) == Count);
     mysql_mutex_unlock(&my_file_info[Filedes].mutex);
     if (error)
       break;
 #elif defined (_WIN32)
     writtenbytes= my_win_pwrite(Filedes, Buffer, Count, offset);
 #else
     writtenbytes= pwrite(Filedes, Buffer, Count, offset);
 #endif
     if(writtenbytes == Count)
       break;
     my_errno= errno;
     if (writtenbytes != (size_t) -1)
     {
       written+= writtenbytes;
       Buffer+= writtenbytes;
       Count-= writtenbytes;
       offset+= writtenbytes;
     }
     DBUG_PRINT("error",("Write only %u bytes", (uint) writtenbytes));
 #ifndef NO_BACKGROUND
     if (my_thread_var->abort)
       MyFlags&= ~ MY_WAIT_IF_FULL;      /* End if aborted by user */
     if ((my_errno == ENOSPC || my_errno == EDQUOT) &&
         (MyFlags & MY_WAIT_IF_FULL))
     {
       wait_for_free_space(my_filename(Filedes), errors);
       errors++;
       continue;
     }
     if ((writtenbytes && writtenbytes != (size_t) -1) || my_errno == EINTR)
       continue;                 /* Retry */
 #endif
     if (MyFlags & (MY_NABP | MY_FNABP))
     {
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         my_error(EE_WRITE, MYF(ME_BELL | ME_WAITTANG),
                  my_filename(Filedes),my_errno);
       }
       DBUG_RETURN(MY_FILE_ERROR);       /* Error on read */
     }
     else
       break;                    /* Return bytes written */
   }
   DBUG_EXECUTE_IF("check", my_seek(Filedes, -1, SEEK_SET, MYF(0)););
   if (MyFlags & (MY_NABP | MY_FNABP))
     DBUG_RETURN(0);         /* Want only errors */
   DBUG_RETURN(writtenbytes+written); /* purecov: inspected */
 } /* my_pwrite */
References Acore::Count(), DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, EDQUOT, EE_WRITE, errno, error(), mpq::errors, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_file_info, my_filename(), MY_FNABP, MY_NABP, my_seek(), MY_SEEK_SET, my_thread_var, MY_WAIT_IF_FULL, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, SEEK_SET, wait_for_free_space(), and write.
Referenced by find_key_block(), flush_cached_blocks(), inline_mysql_file_pwrite(), and key_cache_write().
my_qsort()
qsort_t my_qsort (void * base_ptr, size_t total_elems, size_t size, qsort_cmp cmp)
Definition at line 97 of file mf_qsort.c.
 {
   char *low, *high, *pivot;
   stack_node stack[STACK_SIZE], *stack_ptr;
   my_bool ptr_cmp;
   /* Handle the simple case first */
   /* This will also make the rest of the code simpler */
   if (count <= 1)
     SORT_RETURN;
   low  = (char*) base_ptr;
   high = low+ size * (count - 1);
   stack_ptr = stack + 1;
 #ifdef HAVE_purify
   /* The first element in the stack will be accessed for the last POP */
   stack[0].low=stack[0].high=0;
 #endif
   pivot = (char *) my_alloca((int) size);
   ptr_cmp= size == sizeof(char*) && !((low - (char*) 0)& (sizeof(char*)-1));
   /* The following loop sorts elements between high and low */
   do
   {
     char *low_ptr, *high_ptr, *mid;
     count=((size_t) (high - low) / size)+1;
     /* If count is small, then an insert sort is faster than qsort */
     if (count < THRESHOLD_FOR_INSERT_SORT)
     {
       for (low_ptr = low + size; low_ptr <= high; low_ptr += size)
       {
     char *ptr;
     for (ptr = low_ptr; ptr > low && CMP(ptr - size, ptr) > 0;
          ptr -= size)
       SWAP(ptr, ptr - size, size, ptr_cmp);
       }
       POP(low, high);
       continue;
     }
     /* Try to find a good middle element */
     mid= low + size * (count >> 1);
     if (count > 40)             /* Must be bigger than 24 */
     {
       size_t step = size* (count / 8);
       MEDIAN(low, low + step, low+step*2);
       MEDIAN(mid - step, mid, mid+step);
       MEDIAN(high - 2 * step, high-step, high);
       /* Put best median in 'mid' */
       MEDIAN(low+step, mid, high-step);
       low_ptr  = low;
       high_ptr = high;
     }
     else
     {
       MEDIAN(low, mid, high);
       /* The low and high argument are already in sorted against 'pivot' */
       low_ptr  = low + size;
       high_ptr = high - size;
     }
     memcpy(pivot, mid, size);
     do
     {
       while (CMP(low_ptr, pivot) < 0)
     low_ptr += size;
       while (CMP(pivot, high_ptr) < 0)
     high_ptr -= size;
       if (low_ptr < high_ptr)
       {
     SWAP(low_ptr, high_ptr, size, ptr_cmp);
     low_ptr += size;
     high_ptr -= size;
       }
       else
       {
     if (low_ptr == high_ptr)
     {
       low_ptr += size;
       high_ptr -= size;
     }
     break;
       }
     }
     while (low_ptr <= high_ptr);
     /*
       Prepare for next iteration.
        Skip partitions of size 1 as these doesn't have to be sorted
        Push the larger partition and sort the smaller one first.
        This ensures that the stack is keept small.
     */
     if ((int) (high_ptr - low) <= 0)
     {
       if ((int) (high - low_ptr) <= 0)
       {
     POP(low, high);         /* Nothing more to sort */
       }
       else
     low = low_ptr;          /* Ignore small left part. */
     }
     else if ((int) (high - low_ptr) <= 0)
       high = high_ptr;          /* Ignore small right part. */
     else if ((high_ptr - low) > (high - low_ptr))
     {
       PUSH(low, high_ptr);      /* Push larger left part */
       low = low_ptr;
     }
     else
     {
       PUSH(low_ptr, high);      /* Push larger right part */
       high = high_ptr;
     }
   } while (stack_ptr > stack);
   my_afree(pivot);
   SORT_RETURN;
 }
References CMP, count(), st_stack::high, st_stack::low, MEDIAN, memcpy, my_afree, my_alloca, POP, ptr(), ptr_cmp(), PUSH, SORT_RETURN, STACK_SIZE, SWAP, and THRESHOLD_FOR_INSERT_SORT.
Referenced by flush_cached_blocks(), and my_dir().
my_qsort2()
qsort_t my_qsort2 (void * base_ptr, size_t total_elems, size_t size, qsort2_cmp cmp, void * cmp_argument)
Referenced by my_string_ptr_sort().
my_read()
size_t my_read (File Filedes, uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 36 of file my_read.c.
 {
   size_t readbytes, save_count;
   DBUG_ENTER("my_read");
   DBUG_PRINT("my",("fd: %d  Buffer: %p  Count: %lu  MyFlags: %d",
                    Filedes, Buffer, (ulong) Count, MyFlags));
   save_count= Count;
   for (;;)
   {
     errno= 0;                   /* Linux, Windows don't reset this on EOF/success */
 #ifdef _WIN32
     readbytes= my_win_read(Filedes, Buffer, Count);
 #else
     readbytes= read(Filedes, Buffer, Count);
 #endif
     if (readbytes != Count)
     {
       my_errno= errno;
       if (errno == 0 || (readbytes != (size_t) -1 &&
                          (MyFlags & (MY_NABP | MY_FNABP))))
         my_errno= HA_ERR_FILE_TOO_SHORT;
       DBUG_PRINT("warning",("Read only %d bytes off %lu from %d, errno: %d",
                             (int) readbytes, (ulong) Count, Filedes,
                             my_errno));
       if ((readbytes == 0 || (int) readbytes == -1) && errno == EINTR)
       {
         DBUG_PRINT("debug", ("my_read() was interrupted and returned %ld",
                              (long) readbytes));
         continue;                              /* Interrupted */
       }
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         if (readbytes == (size_t) -1)
           my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
         else if (MyFlags & (MY_NABP | MY_FNABP))
           my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
       }
       if (readbytes == (size_t) -1 ||
           ((MyFlags & (MY_FNABP | MY_NABP)) && !(MyFlags & MY_FULL_IO)))
         DBUG_RETURN(MY_FILE_ERROR); /* Return with error */
       if (readbytes != (size_t) -1 && (MyFlags & MY_FULL_IO))
       {
         Buffer+= readbytes;
         Count-= readbytes;
         continue;
       }
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       readbytes= 0;         /* Ok on read */
     else if (MyFlags & MY_FULL_IO)
       readbytes= save_count;
     break;
   }
   DBUG_RETURN(readbytes);
 } /* my_read */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, HA_ERR_FILE_TOO_SHORT, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_filename(), MY_FNABP, MY_FULL_IO, MY_NABP, MY_WME, MYF, and read.
my_readlink()
int my_readlink (char * to, const char * filename, myf MyFlags)
Definition at line 35 of file my_symlink.c.
 {
 #ifndef HAVE_READLINK
   strmov(to,filename);
   return 1;
 #else
   int result=0;
   int length;
   DBUG_ENTER("my_readlink");
   if ((length=readlink(filename, to, FN_REFLEN-1)) < 0)
   {
     /* Don't give an error if this wasn't a symlink */
     if ((my_errno=errno) == EINVAL)
     {
       result= 1;
       strmov(to,filename);
     }
     else
     {
       if (MyFlags & MY_WME)
     my_error(EE_CANT_READLINK, MYF(0), filename, errno);
       result= -1;
     }
   }
   else
     to[length]=0;
   DBUG_PRINT("exit" ,("result: %d", result));
   DBUG_RETURN(result);
 #endif /* HAVE_READLINK */
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_READLINK, errno, FN_REFLEN, G3D::length(), my_errno, my_error(), MY_WME, MYF, readlink, and strmov().
Referenced by fn_format(), my_delete_with_symlink(), and my_rename_with_symlink().
my_realloc()
void* my_realloc (void * oldpoint, size_t size, myf my_flags)
wrapper around realloc()
Parameters
oldpoint pointer to currently allocated area
size new size requested, must be >0
my_flags flags
Note
if size==0 realloc() may return NULL; my_realloc() treats this as an error which is not the intention of realloc()
Definition at line 74 of file my_malloc.c.
 {
   void *point;
   DBUG_ENTER("my_realloc");
   DBUG_PRINT("my",("ptr: %p  size: %lu  my_flags: %d", oldpoint,
                    (ulong) size, my_flags));
   DBUG_ASSERT(size > 0);
   if (!oldpoint && (my_flags & MY_ALLOW_ZERO_PTR))
     DBUG_RETURN(my_malloc(size, my_flags));
 #ifdef USE_HALLOC
   if (!(point = malloc(size)))
   {
     if (my_flags & MY_FREE_ON_ERROR)
       my_free(oldpoint);
     if (my_flags & MY_HOLD_ON_ERROR)
       DBUG_RETURN(oldpoint);
     my_errno=errno;
     if (my_flags & MY_FAE+MY_WME)
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG),size);
   }
   else
   {
     memcpy(point,oldpoint,size);
     free(oldpoint);
   }
 #else
   if ((point= realloc(oldpoint, size)) == NULL)
   {
     if (my_flags & MY_FREE_ON_ERROR)
       my_free(oldpoint);
     if (my_flags & MY_HOLD_ON_ERROR)
       DBUG_RETURN(oldpoint);
     my_errno=errno;
     if (my_flags & (MY_FAE+MY_WME))
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG), size);
   }
 #endif
   DBUG_PRINT("exit",("ptr: %p", point));
   DBUG_RETURN(point);
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_OUTOFMEMORY, errno, ME_BELL, ME_WAITTANG, memcpy, MY_ALLOW_ZERO_PTR, my_errno, my_error(), MY_FAE, my_free(), MY_FREE_ON_ERROR, MY_HOLD_ON_ERROR, my_malloc(), MY_WME, MYF, and NULL.
Referenced by alloc_dynamic(), allocate_dynamic(), dynstr_append_mem(), dynstr_realloc(), dynstr_set(), freeze_size(), net_realloc(), and resize_queue().
my_realpath()
int my_realpath (char * to, const char * filename, myf MyFlags)
Definition at line 121 of file my_symlink.c.
 {
 #if defined(HAVE_REALPATH) && !defined(HAVE_BROKEN_REALPATH)
   int result=0;
   char buff[BUFF_LEN];
   char *ptr;
   DBUG_ENTER("my_realpath");
   DBUG_PRINT("info",("executing realpath"));
   if ((ptr=realpath(filename,buff)))
       strmake(to,ptr,FN_REFLEN-1);
   else
   {
     /*
       Realpath didn't work;  Use my_load_path() which is a poor substitute
       original name but will at least be able to resolve paths that starts
       with '.'.
     */
     DBUG_PRINT("error",("realpath failed with errno: %d", errno));
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_REALPATH, MYF(0), filename, my_errno);
     my_load_path(to, filename, NullS);
     result= -1;
   }
   DBUG_RETURN(result);
 #else
 #ifdef _WIN32
   int ret= GetFullPathName(filename,FN_REFLEN,
                            to,
                            NULL);
   if (ret == 0 || ret > FN_REFLEN)
   {
     if (ret > FN_REFLEN)
       my_errno= ENAMETOOLONG;
     else
       my_errno= EACCES;
     if (MyFlags & MY_WME)
       my_error(EE_REALPATH, MYF(0), filename, my_errno);
       return -1;
   }
 #else
   my_load_path(to, filename, NullS);
 #endif
   return 0;
 #endif
 }
References BUFF_LEN, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_REALPATH, errno, FN_REFLEN, my_errno, my_error(), my_load_path(), MY_WME, MYF, NULL, NullS, ptr(), ret, and strmake().
Referenced by fn_format(), my_create_with_symlink(), and mysql_read_default_options().
my_redel()
int my_redel (const char * from, const char * to, int MyFlags)
Definition at line 42 of file my_redel.c.
 {
   int error=1;
   DBUG_ENTER("my_redel");
   DBUG_PRINT("my",("org_name: '%s' tmp_name: '%s'  MyFlags: %d",
            org_name,tmp_name,MyFlags));
   if (my_copystat(org_name,tmp_name,MyFlags) < 0)
     goto end;
   if (MyFlags & MY_REDEL_MAKE_BACKUP)
   {
     char name_buff[FN_REFLEN+20];
     char ext[20];
     ext[0]='-';
     get_date(ext+1,2+4,(time_t) 0);
     strmov(strend(ext),REDEL_EXT);
     if (my_rename(org_name, fn_format(name_buff, org_name, "", ext, 2),
           MyFlags))
       goto end;
   }
   else if (my_delete_allow_opened(org_name, MyFlags))
       goto end;
   if (my_rename(tmp_name,org_name,MyFlags))
     goto end;
   error=0;
 end:
   DBUG_RETURN(error);
 } /* my_redel */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), fn_format(), FN_REFLEN, get_date(), my_copystat(), my_delete_allow_opened, MY_REDEL_MAKE_BACKUP, my_rename(), REDEL_EXT, strend(), and strmov().
my_register_filename()
File my_register_filename (File fd, const char * FileName, enum file_type type_of_file, uint error_message_number, myf MyFlags)
Definition at line 120 of file my_open.c.
 {
   DBUG_ENTER("my_register_filename");
   if ((int) fd >= MY_FILE_MIN)
   {
     if ((uint) fd >= my_file_limit)
     {
 #if !defined(HAVE_PREAD)
       my_errno= EMFILE;
 #else
       thread_safe_increment(my_file_opened,&THR_LOCK_open);
       DBUG_RETURN(fd);              /* safeguard */
 #endif
     }
     else
     {
       mysql_mutex_lock(&THR_LOCK_open);
       if ((my_file_info[fd].name = (char*) my_strdup(FileName,MyFlags)))
       {
         my_file_opened++;
         my_file_total_opened++;
         my_file_info[fd].type = type_of_file;
 #if !defined(HAVE_PREAD) && !defined(_WIN32)
         mysql_mutex_init(key_my_file_info_mutex, &my_file_info[fd].mutex,
                          MY_MUTEX_INIT_FAST);
 #endif
         mysql_mutex_unlock(&THR_LOCK_open);
         DBUG_PRINT("exit",("fd: %d",fd));
         DBUG_RETURN(fd);
       }
       mysql_mutex_unlock(&THR_LOCK_open);
       my_errno= ENOMEM;
     }
     (void) my_close(fd, MyFlags);
   }
   else
     my_errno= errno;
   DBUG_PRINT("error",("Got error %d on open", my_errno));
   if (MyFlags & (MY_FFNF | MY_FAE | MY_WME))
   {
     if (my_errno == EMFILE)
       error_message_number= EE_OUT_OF_FILERESOURCES;
     DBUG_PRINT("error",("print err: %d",error_message_number));
     my_error(error_message_number, MYF(ME_BELL+ME_WAITTANG),
              FileName, my_errno);
   }
   DBUG_RETURN(-1);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_OUT_OF_FILERESOURCES, errno, ME_BELL, ME_WAITTANG, my_close(), my_errno, my_error(), MY_FAE, MY_FFNF, my_file_info, my_file_limit, MY_FILE_MIN, my_file_opened, my_file_total_opened, MY_MUTEX_INIT_FAST, my_strdup(), MY_WME, MYF, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, thread_safe_increment, and st_my_file_info::type.
Referenced by create_temp_file(), my_create(), and my_open().
my_remember_signal()
void my_remember_signal (int signal_number, sig_handler(*)(int) func)
my_rename()
int my_rename (const char * from, const char * to, myf MyFlags)
Definition at line 24 of file my_rename.c.
 {
   int error = 0;
   DBUG_ENTER("my_rename");
   DBUG_PRINT("my",("from %s to %s MyFlags %d", from, to, MyFlags));
 #if defined(HAVE_FILE_VERSIONS)
   {             /* Check that there isn't a old file */
     int save_errno;
     MY_STAT my_stat_result;
     save_errno=my_errno;
     if (my_stat(to,&my_stat_result,MYF(0)))
     {
       my_errno=EEXIST;
       error= -1;
       if (MyFlags & MY_FAE+MY_WME)
     my_error(EE_LINK, MYF(ME_BELL+ME_WAITTANG),from,to,my_errno);
       DBUG_RETURN(error);
     }
     my_errno=save_errno;
   }
 #endif
 #if defined(HAVE_RENAME)
 #if defined(__WIN__)
   /*
     On windows we can't rename over an existing file:
     Remove any conflicting files:
   */
   (void) my_delete(to, MYF(0));
 #endif
   if (rename(from,to))
 #else
   if (link(from, to) || unlink(from))
 #endif
   {
     my_errno=errno;
     error = -1;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_LINK, MYF(ME_BELL+ME_WAITTANG),from,to,my_errno);
   }
   else if (MyFlags & MY_SYNC_DIR)
   {
 #ifdef NEED_EXPLICIT_SYNC_DIR
     /* do only the needed amount of syncs: */
     char dir_from[FN_REFLEN], dir_to[FN_REFLEN];
     size_t dir_from_length, dir_to_length;
     dirname_part(dir_from, from, &dir_from_length);
     dirname_part(dir_to, to, &dir_to_length);
     if (my_sync_dir(dir_from, MyFlags) ||
         (strcmp(dir_from, dir_to) &&
          my_sync_dir(dir_to, MyFlags)))
       error= -1;
 #endif
   }
   DBUG_RETURN(error);
 } /* my_rename */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), EE_LINK, endif(), errno, error(), FN_REFLEN, ME_BELL, ME_WAITTANG, my_delete(), my_errno, my_error(), MY_FAE, MY_STAT, my_stat(), MY_SYNC_DIR, my_sync_dir(), MY_WME, and MYF.
Referenced by inline_mysql_file_rename(), my_redel(), and my_rename_with_symlink().
my_rename_with_symlink()
int my_rename_with_symlink (const char * from, const char * to, myf MyFlags)
Definition at line 124 of file my_symlink2.c.
 {
 #ifndef HAVE_READLINK
   return my_rename(from, to, MyFlags);
 #else
   char link_name[FN_REFLEN], tmp_name[FN_REFLEN];
   int was_symlink= (!my_disable_symlinks &&
             !my_readlink(link_name, from, MYF(0)));
   int result=0;
   int name_is_different;
   DBUG_ENTER("my_rename_with_symlink");
   if (!was_symlink)
     DBUG_RETURN(my_rename(from, to, MyFlags));
   /* Change filename that symlink pointed to */
   strmov(tmp_name, to);
   fn_same(tmp_name,link_name,1);        /* Copy dir */
   name_is_different= strcmp(link_name, tmp_name);
   if (name_is_different && !access(tmp_name, F_OK))
   {
     my_errno= EEXIST;
     if (MyFlags & MY_WME)
       my_error(EE_CANTCREATEFILE, MYF(0), tmp_name, EEXIST);
     DBUG_RETURN(1);
   }
   /* Create new symlink */
   if (my_symlink(tmp_name, to, MyFlags))
     DBUG_RETURN(1);
   /*
     Rename symlinked file if the base name didn't change.
     This can happen if you use this function where 'from' and 'to' has
     the same basename and different directories.
    */
   if (name_is_different && my_rename(link_name, tmp_name, MyFlags))
   {
     int save_errno=my_errno;
     my_delete(to, MyFlags);         /* Remove created symlink */
     my_errno=save_errno;
     DBUG_RETURN(1);
   }
   /* Remove original symlink */
   if (my_delete(from, MyFlags))
   {
     int save_errno=my_errno;
     /* Remove created link */
     my_delete(to, MyFlags);
     /* Rename file back */
     if (strcmp(link_name, tmp_name))
       (void) my_rename(tmp_name, link_name, MyFlags);
     my_errno=save_errno;
     result= 1;
   }
   DBUG_RETURN(result);
 #endif /* HAVE_READLINK */
 }
References DBUG_ENTER, DBUG_RETURN, EE_CANTCREATEFILE, FN_REFLEN, fn_same(), my_delete(), my_disable_symlinks, my_errno, my_error(), my_readlink(), my_rename(), my_symlink(), MY_WME, MYF, and strmov().
Referenced by inline_mysql_file_rename_with_symlink().
my_search_option_files()
int my_search_option_files (const char * conf_file, int * argc, char *** argv, uint * args_used, Process_option_func func, void * func_ctx, const char ** default_directories)
copy group
Construct new group
Definition at line 208 of file default.c.
 {
   const char **dirs, *forced_default_file, *forced_extra_defaults;
   int error= 0;
   DBUG_ENTER("my_search_option_files");
   /* Check if we want to force the use a specific default file */
   *args_used+= get_defaults_options(*argc - *args_used, *argv + *args_used,
                                     (char **) &forced_default_file,
                                     (char **) &forced_extra_defaults,
                                     (char **) &my_defaults_group_suffix);
   if (! my_defaults_group_suffix)
     my_defaults_group_suffix= getenv(STRINGIFY_ARG(DEFAULT_GROUP_SUFFIX_ENV));
   if (forced_extra_defaults && !defaults_already_read)
   {
     int error= fn_expand(forced_extra_defaults, my_defaults_extra_file_buffer);
     if (error)
       DBUG_RETURN(error);
     my_defaults_extra_file= my_defaults_extra_file_buffer;
   }
   if (forced_default_file && !defaults_already_read)
   {
     int error= fn_expand(forced_default_file, my_defaults_file_buffer);
     if (error)
       DBUG_RETURN(error);
     my_defaults_file= my_defaults_file_buffer;
   }
   defaults_already_read= TRUE;
   /*
     We can only handle 'defaults-group-suffix' if we are called from
     load_defaults() as otherwise we can't know the type of 'func_ctx'
   */
   if (my_defaults_group_suffix && func == handle_default_option)
   {
     /* Handle --defaults-group-suffix= */
     uint i;
     const char **extra_groups;
     const size_t instance_len= strlen(my_defaults_group_suffix);
     struct handle_option_ctx *ctx= (struct handle_option_ctx*) func_ctx;
     char *ptr;
     TYPELIB *group= ctx->group;
     if (!(extra_groups=
       (const char**)alloc_root(ctx->alloc,
                                    (2*group->count+1)*sizeof(char*))))
       DBUG_RETURN(2);
     for (i= 0; i < group->count; i++)
     {
       size_t len;
       extra_groups[i]= group->type_names[i];
       len= strlen(extra_groups[i]);
       if (!(ptr= alloc_root(ctx->alloc, (uint) (len+instance_len+1))))
        DBUG_RETURN(2);
       extra_groups[i+group->count]= ptr;
       memcpy(ptr, extra_groups[i], len);
       memcpy(ptr+len, my_defaults_group_suffix, instance_len+1);
     }
     group->count*= 2;
     group->type_names= extra_groups;
     group->type_names[group->count]= 0;
   }
   if (my_defaults_file)
   {
     if ((error= search_default_file_with_ext(func, func_ctx, "", "",
                                              my_defaults_file, 0)) < 0)
       goto err;
     if (error > 0)
     {
       fprintf(stderr, "Could not open required defaults file: %s\n",
               my_defaults_file);
       goto err;
     }
   }
   else if (dirname_length(conf_file))
   {
     if ((error= search_default_file(func, func_ctx, NullS, conf_file)) < 0)
       goto err;
   }
   else
   {
     for (dirs= default_directories ; *dirs; dirs++)
     {
       if (**dirs)
       {
     if (search_default_file(func, func_ctx, *dirs, conf_file) < 0)
       goto err;
       }
       else if (my_defaults_extra_file)
       {
         if ((error= search_default_file_with_ext(func, func_ctx, "", "",
                                                 my_defaults_extra_file, 0)) < 0)
       goto err;             /* Fatal error */
         if (error > 0)
         {
           fprintf(stderr, "Could not open required defaults file: %s\n",
                   my_defaults_extra_file);
           goto err;
         }
       }
     }
   }
   DBUG_RETURN(0);
 err:
   fprintf(stderr,"Fatal error in defaults handling. Program aborted\n");
   DBUG_RETURN(1);
 }
References handle_option_ctx::alloc, alloc_root(), st_typelib::count, DBUG_ENTER, DBUG_RETURN, default_directories, defaults_already_read, dirname_length(), error(), fn_expand(), fprintf(), get_defaults_options(), handle_option_ctx::group, handle_default_option(), memcpy, my_defaults_extra_file, my_defaults_extra_file_buffer, my_defaults_file, my_defaults_file_buffer, my_defaults_group_suffix, NullS, ptr(), search_default_file(), search_default_file_with_ext(), STRINGIFY_ARG, TRUE, and st_typelib::type_names.
Referenced by my_load_defaults().
my_seek()
my_off_t my_seek (File fd, my_off_t pos, int whence, myf MyFlags)
Definition at line 46 of file my_seek.c.
 {
   os_off_t newpos= -1;
   DBUG_ENTER("my_seek");
   DBUG_PRINT("my",("fd: %d Pos: %llu  Whence: %d  MyFlags: %d",
            fd, (ulonglong) pos, whence, MyFlags));
   DBUG_ASSERT(pos != MY_FILEPOS_ERROR);     /* safety check */
   /*
       Make sure we are using a valid file descriptor!
   */
   DBUG_ASSERT(fd != -1);
 #if defined (_WIN32)
   newpos= my_win_lseek(fd, pos, whence);
 #else
   newpos= lseek(fd, pos, whence);
 #endif
   if (newpos == (os_off_t) -1)
   {
     my_errno= errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SEEK, MYF(0), my_filename(fd), my_errno);
     DBUG_PRINT("error", ("lseek: %llu  errno: %d", (ulonglong) newpos, errno));
     DBUG_RETURN(MY_FILEPOS_ERROR);
   }
   if ((my_off_t) newpos != pos)
   {
     DBUG_PRINT("exit",("pos: %llu", (ulonglong) newpos));
   }
   DBUG_RETURN((my_off_t) newpos);
 } /* my_seek */
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SEEK, errno, my_errno, my_error(), my_filename(), MY_FILEPOS_ERROR, MY_WME, MYF, and pos().
Referenced by inline_mysql_file_seek(), my_b_append_tell(), my_b_filelength(), my_b_fill(), my_chsize(), my_lock(), my_pwrite(), and my_tell().
my_set_alarm_variable()
sig_handler my_set_alarm_variable (int signo)
my_set_max_open_files()
uint my_set_max_open_files (uint files)
Definition at line 94 of file my_file.c.
 {
   struct st_my_file_info *tmp;
   DBUG_ENTER("my_set_max_open_files");
   DBUG_PRINT("enter",("files: %u  my_file_limit: %u", files, my_file_limit));
   files+= MY_FILE_MIN;
   files= set_max_open_files(min(files, OS_FILE_LIMIT));
   if (files <= MY_NFILE)
     DBUG_RETURN(files);
   if (!(tmp= (struct st_my_file_info*) my_malloc(sizeof(*tmp) * files,
                          MYF(MY_WME))))
     DBUG_RETURN(MY_NFILE);
   /* Copy any initialized files */
   memcpy((char*) tmp, (char*) my_file_info,
          sizeof(*tmp) * min(my_file_limit, files));
   bzero((char*) (tmp + my_file_limit),
         max((int) (files- my_file_limit), 0)*sizeof(*tmp));
   my_free_open_file_info();         /* Free if already allocated */
   my_file_info= tmp;
   my_file_limit= files;
   DBUG_PRINT("exit",("files: %u", files));
   DBUG_RETURN(files);
 }
References bzero, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, files, max, memcpy, min, my_file_info, my_file_limit, MY_FILE_MIN, my_free_open_file_info(), my_malloc(), MY_NFILE, MY_WME, MYF, OS_FILE_LIMIT, and set_max_open_files().
my_setwd()
int my_setwd (const char * dir, myf MyFlags)
Definition at line 91 of file my_getwd.c.
 {
   int res;
   size_t length;
   char *start, *pos;
   DBUG_ENTER("my_setwd");
   DBUG_PRINT("my",("dir: '%s'  MyFlags %d", dir, MyFlags));
   start=(char *) dir;
   if (! dir[0] || (dir[0] == FN_LIBCHAR && dir[1] == 0))
     dir=FN_ROOTDIR;
   if ((res=chdir((char*) dir)) != 0)
   {
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_SETWD,MYF(ME_BELL+ME_WAITTANG),start,errno);
   }
   else
   {
     if (test_if_hard_path(start))
     {                       /* Hard pathname */
       pos= strmake(&curr_dir[0],start,(size_t) FN_REFLEN-1);
       if (pos[-1] != FN_LIBCHAR)
       {
     length=(uint) (pos-(char*) curr_dir);
     curr_dir[length]=FN_LIBCHAR;        /* must end with '/' */
     curr_dir[length+1]='\0';
       }
     }
     else
       curr_dir[0]='\0';             /* Don't save name */
   }
   DBUG_RETURN(res);
 } /* my_setwd */
References curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_SETWD, errno, FN_LIBCHAR, FN_REFLEN, FN_ROOTDIR, G3D::length(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_WME, MYF, pos(), strmake(), and test_if_hard_path().
my_sleep()
void my_sleep (ulong m_seconds)
Definition at line 21 of file my_sleep.c.
 {
 #if defined(__WIN__)
   Sleep(m_seconds/1000+1);      /* Sleep() has millisecond arg */
 #elif defined(HAVE_SELECT)
   struct timeval t;
   t.tv_sec=  m_seconds / 1000000L;
   t.tv_usec= m_seconds % 1000000L;
   select(0,0,0,0,&t); /* sleep */
 #else
   uint sec=    (uint) (m_seconds / 1000000L);
   ulong start= (ulong) time((time_t*) 0);
   while ((ulong) time((time_t*) 0) < start+sec);
 #endif
 }
References sec.
my_store_ptr()
void my_store_ptr (uchar * buff, size_t pack_length, my_off_t pos)
Definition at line 187 of file ptr_cmp.c.
 {
   switch (pack_length) {
 #if SIZEOF_OFF_T > 4
   case 8: mi_int8store(buff,pos); break;
   case 7: mi_int7store(buff,pos); break;
   case 6: mi_int6store(buff,pos); break;
   case 5: mi_int5store(buff,pos); break;
 #endif
   case 4: mi_int4store(buff,pos); break;
   case 3: mi_int3store(buff,pos); break;
   case 2: mi_int2store(buff,pos); break;
   case 1: buff[0]= (uchar) pos; break;
   default: DBUG_ASSERT(0);
   }
   return;
 }
References DBUG_ASSERT, mi_int2store, mi_int3store, mi_int4store, mi_int5store, mi_int6store, mi_int7store, mi_int8store, and pos().
my_strdup()
char* my_strdup (const char * from, myf MyFlags)
Definition at line 142 of file my_malloc.c.
 {
   char *ptr;
   size_t length= strlen(from)+1;
   if ((ptr= (char*) my_malloc(length, my_flags)))
     memcpy(ptr, from, length);
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by add_init_command(), CLI_MYSQL_REAL_CONNECT(), get_tty_password(), init_one_value(), load_env_plugins(), my_fdopen(), my_fopen(), my_register_filename(), mysql_autodetect_character_set(), mysql_change_user(), mysql_init_character_set(), mysql_options(), mysql_read_default_options(), mysql_select_db(), open_cached_file(), send_client_reply_packet(), and setval().
my_string_ptr_sort()
void my_string_ptr_sort (uchar * base, uint items, size_t size)
Definition at line 21 of file mf_sort.c.
 {
 #if INT_MAX > 65536L
   uchar **ptr=0;
   if (size <= 20 && items >= 1000 && items < 100000 &&
       (ptr= (uchar**) my_malloc(items*sizeof(char*),MYF(0))))
   {
     radixsort_for_str_ptr((uchar**) base,items,size,ptr);
     my_free(ptr);
   }
   else
 #endif
   {
     if (size && items)
     {
       my_qsort2(base,items, sizeof(uchar*), get_ptr_compare(size),
                 (void*) &size);
     }
   }
 }
References get_ptr_compare(), my_free(), my_malloc(), my_qsort2(), MYF, ptr(), and radixsort_for_str_ptr().
my_strndup()
char* my_strndup (const char * from, size_t length, myf MyFlags)
Definition at line 152 of file my_malloc.c.
 {
   char *ptr;
   if ((ptr= (char*) my_malloc(length+1, my_flags)))
   {
     memcpy(ptr, from, length);
     ptr[length]= 0;
   }
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by init_tmpdir().
my_symlink()
int my_symlink (const char * content, const char * linkname, myf MyFlags)
Definition at line 70 of file my_symlink.c.
 {
 #ifndef HAVE_READLINK
   return 0;
 #else
   int result;
   DBUG_ENTER("my_symlink");
   DBUG_PRINT("enter",("content: %s  linkname: %s", content, linkname));
   result= 0;
   if (symlink(content, linkname))
   {
     result= -1;
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SYMLINK, MYF(0), linkname, content, errno);
   }
   else if ((MyFlags & MY_SYNC_DIR) && my_sync_dir_by_file(linkname, MyFlags))
     result= -1;
   DBUG_RETURN(result);
 #endif /* HAVE_READLINK */
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SYMLINK, errno, my_errno, my_error(), MY_SYNC_DIR, my_sync_dir_by_file(), MY_WME, and MYF.
Referenced by my_create_with_symlink(), and my_rename_with_symlink().
my_sync()
int my_sync (File fd, myf my_flags)
Definition at line 43 of file my_sync.c.
 {
   int res;
   DBUG_ENTER("my_sync");
   DBUG_PRINT("my",("Fd: %d  my_flags: %d", fd, my_flags));
   do
   {
 #if defined(F_FULLFSYNC)
     /*
       In Mac OS X >= 10.3 this call is safer than fsync() (it forces the
       disk's cache and guarantees ordered writes).
     */
     if (!(res= fcntl(fd, F_FULLFSYNC, 0)))
       break; /* ok */
     /* Some file systems don't support F_FULLFSYNC and fail above: */
     DBUG_PRINT("info",("fcntl(F_FULLFSYNC) failed, falling back"));
 #endif
 #if defined(HAVE_FDATASYNC) && HAVE_DECL_FDATASYNC
     res= fdatasync(fd);
 #elif defined(HAVE_FSYNC)
     res= fsync(fd);
 #elif defined(_WIN32)
     res= my_win_fsync(fd);
 #else
 #error Cannot find a way to sync a file, durability in danger
     res= 0;                 /* No sync (strange OS) */
 #endif
   } while (res == -1 && errno == EINTR);
   if (res)
   {
     int er= errno;
     if (!(my_errno= er))
       my_errno= -1;                             /* Unknown error */
     if ((my_flags & MY_IGNORE_BADFD) &&
         (er == EBADF || er == EINVAL || er == EROFS))
     {
       DBUG_PRINT("info", ("ignoring errno %d", er));
       res= 0;
     }
     else if (my_flags & MY_WME)
       my_error(EE_SYNC, MYF(ME_BELL+ME_WAITTANG), my_filename(fd), my_errno);
   }
   DBUG_RETURN(res);
 } /* my_sync */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_SYNC, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), my_filename(), MY_IGNORE_BADFD, MY_WME, and MYF.
Referenced by inline_mysql_file_sync(), and my_copy().
my_sync_dir()
int my_sync_dir (const char * dir_name, myf my_flags)
Referenced by my_rename().
my_sync_dir_by_file()
int my_sync_dir_by_file (const char * file_name, myf my_flags)
Referenced by my_create(), my_delete(), and my_symlink().
my_tell()
my_off_t my_tell (File fd, myf MyFlags)
Definition at line 82 of file my_seek.c.
 {
   os_off_t pos;
   DBUG_ENTER("my_tell");
   DBUG_PRINT("my",("fd: %d  MyFlags: %d",fd, MyFlags));
   DBUG_ASSERT(fd >= 0);
 #if defined (HAVE_TELL) && !defined (_WIN32)
   pos= tell(fd);
 #else
   pos= my_seek(fd, 0L, MY_SEEK_CUR,0);
 #endif
   if (pos == (os_off_t) -1)
   {
     my_errno= errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SEEK, MYF(0), my_filename(fd), my_errno);
     DBUG_PRINT("error", ("tell: %llu  errno: %d", (ulonglong) pos, my_errno));
   }
   DBUG_PRINT("exit",("pos: %llu", (ulonglong) pos));
   DBUG_RETURN((my_off_t) pos);
 } /* my_tell */
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SEEK, errno, my_errno, my_error(), my_filename(), my_seek(), MY_SEEK_CUR, MY_WME, MYF, and pos().
Referenced by inline_mysql_file_tell(), and my_b_append_tell().
my_time()
time_t my_time (myf flags)
Referenced by check_time_range(), fetch_datetime_with_conversion(), get_date(), my_init_time(), process_alarm_part2(), thr_alarm(), thr_alarm_info(), TIME_to_ulonglong(), TIME_to_ulonglong_date(), TIME_to_ulonglong_datetime(), TIME_to_ulonglong_time(), and wait_for_data().
my_time_possible_from_micro()
time_t my_time_possible_from_micro (ulonglong microtime)
my_tmpdir()
char* my_tmpdir (MY_TMPDIR * tmpdir)
Definition at line 73 of file mf_tempdir.c.
 {
   char *dir;
   if (!tmpdir->max)
     return tmpdir->list[0];
   mysql_mutex_lock(&tmpdir->mutex);
   dir=tmpdir->list[tmpdir->cur];
   tmpdir->cur= (tmpdir->cur == tmpdir->max) ? 0 : tmpdir->cur+1;
   mysql_mutex_unlock(&tmpdir->mutex);
   return dir;
 }
References st_my_tmpdir::cur, st_my_tmpdir::list, st_my_tmpdir::max, st_my_tmpdir::mutex, mysql_mutex_lock, and mysql_mutex_unlock.
my_uncompress()
my_bool my_uncompress (uchar * , size_t , size_t *)
Referenced by my_net_read().
my_write()
size_t my_write (File Filedes, const uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 23 of file my_write.c.
 {
   size_t writtenbytes, written;
   uint errors;
   DBUG_ENTER("my_write");
   DBUG_PRINT("my",("fd: %d  Buffer: %p  Count: %lu  MyFlags: %d",
            Filedes, Buffer, (ulong) Count, MyFlags));
   errors= 0; written= 0;
   /* The behavior of write(fd, buf, 0) is not portable */
   if (unlikely(!Count))
     DBUG_RETURN(0);
   for (;;)
   {
 #ifdef _WIN32
     writtenbytes= my_win_write(Filedes, Buffer, Count);
 #else
     writtenbytes= write(Filedes, Buffer, Count);
 #endif
     if (writtenbytes == Count)
       break;
     if (writtenbytes != (size_t) -1)
     {                       /* Safeguard */
       written+= writtenbytes;
       Buffer+= writtenbytes;
       Count-= writtenbytes;
     }
     my_errno= errno;
     DBUG_PRINT("error",("Write only %ld bytes, error: %d",
             (long) writtenbytes, my_errno));
 #ifndef NO_BACKGROUND
     if (my_thread_var->abort)
       MyFlags&= ~ MY_WAIT_IF_FULL;      /* End if aborted by user */
     if ((my_errno == ENOSPC || my_errno == EDQUOT) &&
         (MyFlags & MY_WAIT_IF_FULL))
     {
       wait_for_free_space(my_filename(Filedes), errors);
       errors++;
       continue;
     }
     if ((writtenbytes == 0 || writtenbytes == (size_t) -1))
     {
       if (my_errno == EINTR)
       {
         DBUG_PRINT("debug", ("my_write() was interrupted and returned %ld",
                              (long) writtenbytes));
         continue;                               /* Interrupted */
       }
       if (!writtenbytes && !errors++)       /* Retry once */
       {
         /* We may come here if the file quota is exeeded */
         errno= EFBIG;               /* Assume this is the error */
         continue;
       }
     }
     else
       continue;                 /* Retry */
 #endif
     if (MyFlags & (MY_NABP | MY_FNABP))
     {
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
     my_error(EE_WRITE, MYF(ME_BELL+ME_WAITTANG),
          my_filename(Filedes),my_errno);
       }
       DBUG_RETURN(MY_FILE_ERROR);       /* Error on read */
     }
     else
       break;                    /* Return bytes written */
   }
   if (MyFlags & (MY_NABP | MY_FNABP))
     DBUG_RETURN(0);         /* Want only errors */
   DBUG_RETURN(writtenbytes+written);
 } /* my_write */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EDQUOT, EE_WRITE, errno, mpq::errors, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_filename(), MY_FNABP, MY_NABP, my_thread_var, MY_WAIT_IF_FULL, MY_WME, MYF, unlikely, wait_for_free_space(), and write.
normalize_dirname()
size_t normalize_dirname (char * to, const char * from)
Convert a directory name to a format which can be compared as strings
Parameters
to result buffer, FN_REFLEN chars in length; may be == from
from 'packed' directory name, in whatever format
Returns
size of the normalized name
Ensures that last char is FN_LIBCHAR, unless it is FN_DEVCHAR
Uses cleanup_dirname
It does not expand ~/ (although, see cleanup_dirname). Nor does it do any case folding. All case-insensitive normalization should be done by the caller.
Definition at line 291 of file mf_pack.c.
 {
   size_t length;
   char buff[FN_REFLEN];
   DBUG_ENTER("normalize_dirname");
   /*
     Despite the name, this actually converts the name to the system's
     format (TODO: name this properly).
   */
   (void) intern_filename(buff, from);
   length= strlen(buff);         /* Fix that '/' is last */
   if (length &&
 #ifdef FN_DEVCHAR
       buff[length - 1] != FN_DEVCHAR &&
 #endif
       buff[length - 1] != FN_LIBCHAR && buff[length - 1] != '/')
   {
     /* we need reserve 2 bytes for the trailing slash and the zero */
     if (length >= sizeof (buff) - 1)
       length= sizeof (buff) - 2;
     buff[length]= FN_LIBCHAR;
     buff[length + 1]= '\0';
   }
   length=cleanup_dirname(to, buff);
   DBUG_RETURN(length);
 }
References cleanup_dirname(), DBUG_ENTER, DBUG_RETURN, endif(), FN_DEVCHAR, FN_LIBCHAR, FN_REFLEN, intern_filename(), and G3D::length().
Referenced by add_directory(), and unpack_dirname().
open_cached_file()
my_bool open_cached_file (IO_CACHE * cache, const char * dir, const char * prefix, size_t cache_size, myf cache_myflags)
Definition at line 60 of file mf_cache.c.
 {
   DBUG_ENTER("open_cached_file");
   cache->dir=    dir ? my_strdup(dir,MYF(cache_myflags & MY_WME)) : (char*) 0;
   cache->prefix= (prefix ? my_strdup(prefix,MYF(cache_myflags & MY_WME)) :
          (char*) 0);
   cache->file_name=0;
   cache->buffer=0;              /* Mark that not open */
   if (!init_io_cache(cache,-1,cache_size,WRITE_CACHE,0L,0,
              MYF(cache_myflags | MY_NABP)))
   {
     DBUG_RETURN(0);
   }
   my_free(cache->dir);
   my_free(cache->prefix);
   DBUG_RETURN(1);
 }
References st_io_cache::buffer, DBUG_ENTER, DBUG_RETURN, st_io_cache::dir, st_io_cache::file_name, init_io_cache(), my_free(), MY_NABP, my_strdup(), MY_WME, MYF, st_io_cache::prefix, and WRITE_CACHE.
pack_dirname()
void pack_dirname (char * to, const char * from)
Definition at line 28 of file mf_pack.c.
 {
   int cwd_err;
   size_t d_length,length,UNINIT_VAR(buff_length);
   char * start;
   char buff[FN_REFLEN];
   DBUG_ENTER("pack_dirname");
   (void) intern_filename(to,from);      /* Change to intern name */
 #ifdef FN_DEVCHAR
   if ((start=strrchr(to,FN_DEVCHAR)) != 0)  /* Skip device part */
     start++;
   else
 #endif
     start=to;
   if (!(cwd_err= my_getwd(buff,FN_REFLEN,MYF(0))))
   {
     buff_length= strlen(buff);
     d_length= (size_t) (start-to);
     if ((start == to ||
      (buff_length == d_length && !memcmp(buff,start,d_length))) &&
     *start != FN_LIBCHAR && *start)
     {                       /* Put current dir before */
       bchange((uchar*) to, d_length, (uchar*) buff, buff_length, strlen(to)+1);
     }
   }
   if ((d_length= cleanup_dirname(to,to)) != 0)
   {
     length=0;
     if (home_dir)
     {
       length= strlen(home_dir);
       if (home_dir[length-1] == FN_LIBCHAR)
     length--;               /* Don't test last '/' */
     }
     if (length > 1 && length < d_length)
     {                       /* test if /xx/yy -> ~/yy */
       if (memcmp(to,home_dir,length) == 0 && to[length] == FN_LIBCHAR)
       {
     to[0]=FN_HOMELIB;           /* Filename begins with ~ */
     (void) strmov_overlapp(to+1,to+length);
       }
     }
     if (! cwd_err)
     {                       /* Test if cwd is ~/... */
       if (length > 1 && length < buff_length)
       {
     if (memcmp(buff,home_dir,length) == 0 && buff[length] == FN_LIBCHAR)
     {
       buff[0]=FN_HOMELIB;
       (void) strmov_overlapp(buff+1,buff+length);
     }
       }
       if (is_prefix(to,buff))
       {
     length= strlen(buff);
     if (to[length])
       (void) strmov_overlapp(to,to+length); /* Remove everything before */
     else
     {
       to[0]= FN_CURLIB;         /* Put ./ instead of cwd */
       to[1]= FN_LIBCHAR;
       to[2]= '\0';
     }
       }
     }
   }
   DBUG_PRINT("exit",("to: '%s'",to));
   DBUG_VOID_RETURN;
 } /* pack_dirname */
References bchange(), cleanup_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, FN_CURLIB, FN_DEVCHAR, FN_HOMELIB, FN_LIBCHAR, FN_REFLEN, home_dir, intern_filename(), is_prefix(), G3D::length(), my_getwd(), MYF, strmov_overlapp, and UNINIT_VAR.
Referenced by fn_format().
pack_filename()
int pack_filename (char * to, const char * name, size_t max_length)
packfrm()
int packfrm (uchar * , size_t , uchar ** , size_t *)
pop_dynamic()
uchar* pop_dynamic (DYNAMIC_ARRAY * array)
Definition at line 174 of file array.c.
 {
   if (array->elements)
     return array->buffer+(--array->elements * array->size_of_element);
   return 0;
 }
References array, and LF_DYNARRAY::size_of_element.
Referenced by my_hash_delete().
print_defaults()
void print_defaults (const char * conf_file, const char ** groups)
Definition at line 1051 of file default.c.
 {
   const char **groups_save= groups;
   my_print_default_files(conf_file);
   fputs("The following groups are read:",stdout);
   for ( ; *groups ; groups++)
   {
     fputc(' ',stdout);
     fputs(*groups,stdout);
   }
   if (my_defaults_group_suffix)
   {
     groups= groups_save;
     for ( ; *groups ; groups++)
     {
       fputc(' ',stdout);
       fputs(*groups,stdout);
       fputs(my_defaults_group_suffix,stdout);
     }
   }
   puts("\nThe following options may be given as the first argument:\n\
 --print-defaults        Print the program argument list and exit.\n\
 --no-defaults           Don't read default options from any option file.\n\
 --defaults-file=#       Only read default options from the given file #.\n\
 --defaults-extra-file=# Read this file after the global files are read.");
 }
References fputs(), my_defaults_group_suffix, and my_print_default_files().
radixsort_for_str_ptr()
void radixsort_for_str_ptr (uchar * base[], uint number_of_elements, size_t size_of_element, uchar * buffer[])
Referenced by my_string_ptr_sort().
read_cache_record()
int read_cache_record (RECORD_CACHE * info, uchar * to)
real_open_cached_file()
my_bool real_open_cached_file (IO_CACHE * cache)
Definition at line 81 of file mf_cache.c.
 {
   char name_buff[FN_REFLEN];
   int error=1;
   DBUG_ENTER("real_open_cached_file");
   if ((cache->file=create_temp_file(name_buff, cache->dir, cache->prefix,
                     (O_RDWR | O_BINARY | O_TRUNC |
                      O_TEMPORARY | O_SHORT_LIVED),
                     MYF(MY_WME))) >= 0)
   {
     error=0;
     cache_remove_open_tmp(cache, name_buff);
   }
   DBUG_RETURN(error);
 }
References cache_remove_open_tmp(), create_temp_file(), DBUG_ENTER, DBUG_RETURN, st_io_cache::dir, error(), st_io_cache::file, FN_REFLEN, MY_WME, MYF, O_BINARY, O_SHORT_LIVED, O_TEMPORARY, and st_io_cache::prefix.
Referenced by my_b_flush_io_cache().
reinit_io_cache()
my_bool reinit_io_cache (IO_CACHE * info, enum cache_type type, my_off_t seek_offset, pbool use_async_io, pbool clear_cache)
Referenced by my_b_copy_to_file().
remove_io_thread()
void remove_io_thread (IO_CACHE * info)
Definition at line 716 of file mf_iocache.c.
 {
   IO_CACHE_SHARE *cshare= cache->share;
   uint total;
   DBUG_ENTER("remove_io_thread");
   /* If the writer goes, it needs to flush the write cache. */
   if (cache == cshare->source_cache)
     flush_io_cache(cache);
   mysql_mutex_lock(&cshare->mutex);
   DBUG_PRINT("io_cache_share", ("%s: 0x%lx",
                                 (cache == cshare->source_cache) ?
                                 "writer" : "reader", (long) cache));
   /* Remove from share. */
   total= --cshare->total_threads;
   DBUG_PRINT("io_cache_share", ("remaining threads: %u", total));
   /* Detach from share. */
   cache->share= NULL;
   /* If the writer goes, let the readers know. */
   if (cache == cshare->source_cache)
   {
     DBUG_PRINT("io_cache_share", ("writer leaves"));
     cshare->source_cache= NULL;
   }
   /* If all threads are waiting for me to join the lock, wake them. */
   if (!--cshare->running_threads)
   {
     DBUG_PRINT("io_cache_share", ("the last running thread leaves, wake all"));
     mysql_cond_signal(&cshare->cond_writer);
     mysql_cond_broadcast(&cshare->cond);
   }
   mysql_mutex_unlock(&cshare->mutex);
   if (!total)
   {
     DBUG_PRINT("io_cache_share", ("last thread removed, destroy share"));
     mysql_cond_destroy (&cshare->cond_writer);
     mysql_cond_destroy (&cshare->cond);
     mysql_mutex_destroy(&cshare->mutex);
   }
   DBUG_VOID_RETURN;
 }
References st_io_cache_share::cond, st_io_cache_share::cond_writer, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, flush_io_cache, st_io_cache_share::mutex, mysql_cond_broadcast, mysql_cond_destroy, mysql_cond_signal, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, NULL, st_io_cache_share::running_threads, st_io_cache::share, st_io_cache_share::source_cache, and st_io_cache_share::total_threads.
reset_root_defaults()
void reset_root_defaults (MEM_ROOT * mem_root, size_t block_size, size_t prealloc_size)
resolve_charset()
my_bool resolve_charset (const char * cs_name, CHARSET_INFO * default_cs, CHARSET_INFO ** cs)
Resolve character set by the character set name (utf8, latin1, ...).
The function tries to resolve character set by the specified name. If there is character set with the given name, it is assigned to the "cs" parameter and FALSE is returned. If there is no such character set, "default_cs" is assigned to the "cs" and TRUE is returned.
Parameters
[in] cs_name Character set name.
[in] default_cs Default character set.
[out] cs Variable to store character set.
Returns
FALSE if character set was resolved successfully; TRUE if there is no character set with given name.
Definition at line 670 of file charset.c.
 {
   *cs= get_charset_by_csname(cs_name, MY_CS_PRIMARY, MYF(0));
   if (*cs == NULL)
   {
     *cs= default_cs;
     return TRUE;
   }
   return FALSE;
 }
References FALSE, get_charset_by_csname(), MY_CS_PRIMARY, MYF, NULL, and TRUE.
resolve_collation()
my_bool resolve_collation (const char * cl_name, CHARSET_INFO * default_cl, CHARSET_INFO ** cl)
Resolve collation by the collation name (utf8_general_ci, ...).
The function tries to resolve collation by the specified name. If there is collation with the given name, it is assigned to the "cl" parameter and FALSE is returned. If there is no such collation, "default_cl" is assigned to the "cl" and TRUE is returned.
Parameters
[out] cl Variable to store collation.
[in] cl_name Collation name.
[in] default_cl Default collation.
Returns
FALSE if collation was resolved successfully; TRUE if there is no collation with given name.
Definition at line 702 of file charset.c.
 {
   *cl= get_charset_by_name(cl_name, MYF(0));
   if (*cl == NULL)
   {
     *cl= default_cl;
     return TRUE;
   }
   return FALSE;
 }
References FALSE, get_charset_by_name(), MYF, NULL, and TRUE.
safe_strdup_root()
static char* safe_strdup_root (MEM_ROOT * root, const char * str) inline static
Definition at line 811 of file my_sys.h.
 {
   return str ? strdup_root(root, str) : 0;
 }
References strdup_root().
set_dynamic()
my_bool set_dynamic (DYNAMIC_ARRAY * array, uchar * element, uint array_index)
Definition at line 199 of file array.c.
 {
   if (idx >= array->elements)
   {
     if (idx >= array->max_element && allocate_dynamic(array, idx))
       return TRUE;
     bzero((uchar*) (array->buffer+array->elements*array->size_of_element),
       (idx - array->elements)*array->size_of_element);
     array->elements=idx+1;
   }
   memcpy(array->buffer+(idx * array->size_of_element),element,
      (size_t) array->size_of_element);
   return FALSE;
 }
References allocate_dynamic(), array, bzero, FALSE, idx, memcpy, LF_DYNARRAY::size_of_element, and TRUE.
set_prealloc_root()
void set_prealloc_root (MEM_ROOT * root, char * ptr)
Definition at line 390 of file my_alloc.c.
 {
   USED_MEM *next;
   for (next=root->used; next ; next=next->next)
   {
     if ((char*) next <= ptr && (char*) next + next->size > ptr)
     {
       root->pre_alloc=next;
       return;
     }
   }
   for (next=root->free ; next ; next=next->next)
   {
     if ((char*) next <= ptr && (char*) next + next->size > ptr)
     {
       root->pre_alloc=next;
       return;
     }
   }
 }
References st_mem_root::free, next(), st_mem_root::pre_alloc, ptr(), and st_mem_root::used.
setup_io_cache()
void setup_io_cache (IO_CACHE * info)
Definition at line 79 of file mf_iocache.c.
 {
   /* Ensure that my_b_tell() and my_b_bytes_in_cache works */
   if (info->type == WRITE_CACHE)
   {
     info->current_pos= &info->write_pos;
     info->current_end= &info->write_end;
   }
   else
   {
     info->current_pos= &info->read_pos;
     info->current_end= &info->read_end;
   }
 }
References st_io_cache::current_end, st_io_cache::current_pos, st_io_cache::read_end, st_io_cache::read_pos, st_io_cache::type, WRITE_CACHE, st_io_cache::write_end, and st_io_cache::write_pos.
Referenced by init_functions().
soundex()
void soundex (CHARSET_INFO * , char * out_pntr, char * in_pntr, pbool remove_garbage)
strdup_root()
char* strdup_root (MEM_ROOT * root, const char * str)
Definition at line 412 of file my_alloc.c.
 {
   return strmake_root(root, str, strlen(str));
 }
References strmake_root().
Referenced by copy_typelib(), my_dir(), safe_strdup_root(), and unpack_fields().
strlength()
size_t strlength (const char * str)
Definition at line 119 of file mf_format.c.
 {
   reg1 const char * pos;
   reg2 const char * found;
   DBUG_ENTER("strlength");
   pos= found= str;
   while (*pos)
   {
     if (*pos != ' ')
     {
       while (*++pos && *pos != ' ') {};
       if (!*pos)
       {
     found=pos;          /* String ends here */
     break;
       }
     }
     found=pos;
     while (*++pos == ' ') {};
   }
   DBUG_RETURN((size_t) (found - str));
 } /* strlength */
References DBUG_ENTER, DBUG_RETURN, pos(), reg1, and reg2.
Referenced by fn_format().
strmake_root()
char* strmake_root (MEM_ROOT * root, const char * str, size_t len)
Definition at line 418 of file my_alloc.c.
 {
   char *pos;
   if ((pos=alloc_root(root,len+1)))
   {
     memcpy(pos,str,len);
     pos[len]=0;
   }
   return pos;
 }
References alloc_root(), memcpy, and pos().
Referenced by add_directory(), alloc_stmt_fields(), copy_typelib(), strdup_root(), and unpack_fields().
system_filename()
size_t system_filename (char * to, const char * from)
Definition at line 441 of file mf_pack.c.
 {
   return (size_t) (strmake(to,from,FN_REFLEN-1)-to);
 }
References FN_REFLEN, and strmake().
Referenced by unpack_dirname(), and unpack_filename().
test_if_hard_path()
int test_if_hard_path (const char * dir_name)
Referenced by fn_format(), get_charsets_dir(), my_load_path(), and my_path().
thd_increment_bytes_received()
void thd_increment_bytes_received (ulong length)
Referenced by my_real_read().
thd_increment_bytes_sent()
void thd_increment_bytes_sent (ulong length)
thd_increment_net_big_packet_count()
void thd_increment_net_big_packet_count (ulong length)
to_unix_path()
void to_unix_path (char * name)
unpack_dirname()
size_t unpack_dirname (char * to, const char * from)
Fixes a directory name so that can be used by open()
Parameters
to Result buffer, FN_REFLEN characters. May be == from
from 'Packed' directory name (may contain ~)
Uses normalize_dirname()
Expands ~/... to home_dir/...
Resolves MySQL's fake "foo.sym" symbolic directory names (if USE_SYMDIR)
Changes a UNIX filename to system filename (replaces / with \ on windows)
Returns
Length of new directory name (= length of to)
Definition at line 338 of file mf_pack.c.
 {
   size_t length, h_length;
   char buff[FN_REFLEN+1+4],*suffix,*tilde_expansion;
   DBUG_ENTER("unpack_dirname");
   length= normalize_dirname(buff, from);
   if (buff[0] == FN_HOMELIB)
   {
     suffix=buff+1; tilde_expansion=expand_tilde(&suffix);
     if (tilde_expansion)
     {
       length-= (size_t) (suffix-buff)-1;
       if (length+(h_length= strlen(tilde_expansion)) <= FN_REFLEN)
       {
     if ((h_length > 0) && (tilde_expansion[h_length-1] == FN_LIBCHAR))
       h_length--;
     if (buff+h_length < suffix)
       bmove(buff+h_length,suffix,length);
     else
       bmove_upp((uchar*) buff+h_length+length, (uchar*) suffix+length, length);
     bmove(buff,tilde_expansion,h_length);
       }
     }
   }
 #ifdef USE_SYMDIR
   if (my_use_symdir)
     symdirget(buff);
 #endif
   DBUG_RETURN(system_filename(to,buff));    /* Fix for open */
 } /* unpack_dirname */
References bmove_upp(), DBUG_ENTER, DBUG_RETURN, expand_tilde(), FN_HOMELIB, FN_LIBCHAR, FN_REFLEN, G3D::length(), my_use_symdir, normalize_dirname(), and system_filename().
Referenced by fn_format(), and unpack_filename().
unpack_filename()
size_t unpack_filename (char * to, const char * from)
Definition at line 418 of file mf_pack.c.
 {
   size_t length, n_length, buff_length;
   char buff[FN_REFLEN];
   DBUG_ENTER("unpack_filename");
   length=dirname_part(buff, from, &buff_length);/* copy & convert dirname */
   n_length=unpack_dirname(buff,buff);
   if (n_length+strlen(from+length) < FN_REFLEN)
   {
     (void) strmov(buff+n_length,from+length);
     length= system_filename(to,buff);       /* Fix to usably filename */
   }
   else
     length= system_filename(to,from);       /* Fix to usably filename */
   DBUG_RETURN(length);
 } /* unpack_filename */
References DBUG_ENTER, DBUG_RETURN, dirname_part(), FN_REFLEN, G3D::length(), strmov(), system_filename(), and unpack_dirname().
unpackfrm()
int unpackfrm (uchar ** , size_t * , const uchar *)
wait_for_free_space()
void wait_for_free_space (const char * filename, int errors)
Definition at line 102 of file errors.c.
 {
   if (errors == 0)
     my_error(EE_DISK_FULL,MYF(ME_BELL | ME_NOREFRESH),
              filename,my_errno,MY_WAIT_FOR_USER_TO_FIX_PANIC);
   if (!(errors % MY_WAIT_GIVE_USER_A_MESSAGE))
     my_printf_error(EE_DISK_FULL,
                     "Retry in %d secs. Message reprinted in %d secs",
                     MYF(ME_BELL | ME_NOREFRESH),
                     MY_WAIT_FOR_USER_TO_FIX_PANIC,
                     MY_WAIT_GIVE_USER_A_MESSAGE * MY_WAIT_FOR_USER_TO_FIX_PANIC );
   (void) sleep(MY_WAIT_FOR_USER_TO_FIX_PANIC);
 }
References EE_DISK_FULL, mpq::errors, ME_BELL, ME_NOREFRESH, my_errno, my_error(), my_printf_error(), MY_WAIT_FOR_USER_TO_FIX_PANIC, MY_WAIT_GIVE_USER_A_MESSAGE, and MYF.
Referenced by my_fwrite(), my_pwrite(), and my_write().
wild_compare()
int wild_compare (const char * str, const char * wildstr, pbool str_is_pattern)
write_cache_record()
int write_cache_record (RECORD_CACHE * info, my_off_t filepos, const uchar * record, size_t length)
Variable Documentation
all_charsets
MYSQL_PLUGIN_IMPORT CHARSET_INFO* all_charsets[MY_ALL_CHARSETS_SIZE] extern
Definition at line 417 of file charset.c.
Referenced by add_collation(), add_compiled_collation(), get_charset(), get_charset_name(), get_charset_number_internal(), get_collation_number_internal(), get_internal_charset(), and init_available_charsets().
args_separator
const char* args_separator extern
arguments separator
load_defaults() loads arguments from config file and put them before the arguments from command line, this separator is used to separate the arguments loaded from config file and arguments user provided on command line.
Options with value loaded from config file are always in the form '–option=value', while for command line options, the value can be given as the next argument. Thus we used a separator so that handle_options() can distinguish them.
Note: any other places that does not need to distinguish them should skip the separator.
The content of arguments separator does not matter, one should only check the pointer, use "----args-separator----" here to ease debug if someone misused it.
See BUG#25192
Definition at line 66 of file default.c.
Referenced by handle_options(), my_load_defaults(), and mysql_read_default_options().
charsets_dir
const char* charsets_dir extern
Definition at line 354 of file charset.c.
Referenced by get_charsets_dir(), mysql_get_character_set_info(), mysql_set_character_set(), and mysql_set_character_set_with_default_collation().
compiled_charsets
CHARSET_INFO compiled_charsets[] extern
Definition at line 6605 of file ctype-extra.c.
Referenced by init_compiled_charsets().
curr_dir
char curr_dir[] extern
Definition at line 30 of file my_static.c.
Referenced by cleanup_dirname(), my_getwd(), my_path(), and my_setwd().
default_charset_info
MYSQL_PLUGIN_IMPORT CHARSET_INFO* default_charset_info extern
Definition at line 418 of file charset.c.
Referenced by get_charset(), and mysql_escape_string().
errno
int errno extern
Referenced by _db_doprnt_(), _db_enter_(), _db_return_(), _db_suicide_(), _my_b_write(), buffered_file::buffered_file(), cache_remove_open_tmp(), CLI_MYSQL_REAL_CONNECT(), client_mpvio_write_packet(), buffered_file::close(), G3D::BinaryOutput::commit(), create_temp_file(), end_server(), G3D::errnoToString(), eval_num_suffix(), buffered_file::fileno(), flush_cached_blocks(), flush_key_blocks_int(), detail::fwrite_fully(), get_errno(), MMAP::getDirContents(), key_cache_insert(), main(), my_chsize(), my_close(), my_connect(), my_copy(), my_copystat(), my_create_with_symlink(), my_delete(), my_dir(), my_error(), my_fclose(), my_fdopen(), my_fopen(), my_fread(), my_fwrite(), my_getwd(), my_lock(), my_malloc(), my_mkdir(), my_once_alloc(), my_osmaperr(), my_pread(), my_printf_error(), my_printv_error(), my_pwrite(), my_quick_read(), my_quick_write(), my_read(), my_readlink(), my_realloc(), my_realpath(), my_register_filename(), my_rename(), my_seek(), my_setwd(), my_stat(), my_symlink(), my_sync(), my_tell(), my_write(), obtain_malloc_conf(), prof_log_stop(), run_plugin_auth(), send_client_reply_packet(), set_errno(), SetProcessPriority(), str2int(), mpq::MPQException::this(), vio_blocking(), vio_read(), vprint(), wait_for_data(), and buffered_file::~buffered_file().
error_handler_hook
void(* error_handler_hook) (uint my_err, const char *str, myf MyFlags) (uint my_err, const char * str, myf MyFlags) extern
Definition at line 72 of file my_static.c.
Referenced by my_malloc().
fatal_error_handler_hook
void(* fatal_error_handler_hook) (uint my_err, const char *str, myf MyFlags) (uint my_err, const char * str, myf MyFlags) extern
Definition at line 74 of file my_static.c.
Referenced by my_malloc().
home_dir
char* home_dir extern
Definition at line 28 of file my_static.c.
Referenced by cleanup_dirname(), expand_tilde(), my_basic_init(), my_init(), pack_dirname(), and test_if_hard_path().
my_abort_hook
void(*)(*)(*) my_abort_hook(int) (int)
Definition at line 237 of file my_sys.h.
my_default_record_cache_size
ulong my_default_record_cache_size extern
Definition at line 46 of file my_static.c.
Referenced by init_io_cache().
my_defaults_extra_file
const char* my_defaults_extra_file extern
Definition at line 69 of file default.c.
Referenced by my_print_default_files(), and my_search_option_files().
my_defaults_file
const char* my_defaults_file extern
Definition at line 67 of file default.c.
Referenced by my_search_option_files().
my_defaults_group_suffix
const char* my_defaults_group_suffix extern
Definition at line 68 of file default.c.
Referenced by my_search_option_files(), and print_defaults().
my_disable_async_io
my_bool my_disable_async_io
Definition at line 250 of file my_sys.h.
Referenced by init_io_cache(), and reinit_io_cache().
my_disable_flush_key_blocks
my_bool my_disable_flush_key_blocks
Definition at line 251 of file my_sys.h.
Referenced by flush_key_blocks_int().
my_disable_locking
my_bool my_disable_locking extern
Definition at line 104 of file my_static.c.
Referenced by my_lock().
my_disable_symlinks
my_bool my_disable_symlinks
Definition at line 251 of file my_sys.h.
Referenced by my_create_with_symlink(), my_delete_with_symlink(), and my_rename_with_symlink().
my_dont_interrupt
int my_dont_interrupt
Definition at line 246 of file my_sys.h.
my_file_info
struct st_my_file_info* my_file_info extern
Definition at line 38 of file my_static.c.
Referenced by my_close(), my_fclose(), my_fdopen(), my_filename(), my_fopen(), my_free_open_file_info(), my_pread(), my_pwrite(), my_register_filename(), and my_set_max_open_files().
my_file_limit
uint my_file_limit extern
Definition at line 37 of file my_static.c.
Referenced by my_close(), my_fclose(), my_fdopen(), my_filename(), my_fopen(), my_free_open_file_info(), my_register_filename(), and my_set_max_open_files().
my_file_opened
ulong my_file_opened extern
Definition at line 32 of file my_static.c.
Referenced by my_close(), my_end(), my_fdopen(), and my_register_filename().
my_file_total_opened
ulong my_file_total_opened extern
Definition at line 33 of file my_static.c.
Referenced by my_fopen(), and my_register_filename().
my_init_done
my_bool my_init_done extern
Definition at line 39 of file my_init.c.
Referenced by my_end(), my_init(), and mysql_server_init().
my_progname
const char* my_progname extern
Definition at line 29 of file my_static.c.
Referenced by handle_options(), my_init(), my_message_stderr(), my_real_read(), my_time(), net_real_write(), and setval().
my_recived_signals
int my_recived_signals
Definition at line 244 of file my_sys.h.
my_safe_to_handle_signal
int my_safe_to_handle_signal
Definition at line 245 of file my_sys.h.
my_sigtstp_cleanup
void(* my_sigtstp_cleanup) (void) (void) extern
my_sigtstp_restart
void(*)(*) my_sigtstp_restart(void) (void)
Definition at line 237 of file my_sys.h.
my_stream_opened
ulong my_stream_opened
Definition at line 231 of file my_sys.h.
Referenced by my_end(), my_fclose(), my_fdopen(), and my_fopen().
my_thread_stack_size
ulong my_thread_stack_size extern
Definition at line 43 of file my_init.c.
Referenced by my_thread_init().
my_tmp_file_created
ulong my_tmp_file_created
Definition at line 231 of file my_sys.h.
Referenced by create_temp_file().
my_umask
MYSQL_PLUGIN_IMPORT int my_umask extern
Definition at line 34 of file my_static.c.
Referenced by my_basic_init(), my_create(), and my_open().
my_umask_dir
int my_umask_dir extern
Definition at line 34 of file my_static.c.
Referenced by my_basic_init(), and my_mkdir().
my_use_symdir
my_bool my_use_symdir extern
Definition at line 239 of file mf_pack.c.
Referenced by unpack_dirname().
mysql_stdin
struct st_mysql_file* mysql_stdin extern
Definition at line 56 of file my_init.c.
Referenced by my_basic_init().
mysys_usage_id
uint mysys_usage_id extern
Definition at line 42 of file my_init.c.
Referenced by my_basic_init().
proc_info_hook
const char*(* proc_info_hook) (void *, const char *, const char *, const char *, const unsigned int) (void * , const char * , const char * , const char * , const unsigned int) extern
Definition at line 87 of file my_static.c.
timed_mutexes
my_bool timed_mutexes extern
Definition at line 25 of file my_static.c.
wild_many
char wild_many extern
Definition at line 23 of file mf_wcomp.c.
Referenced by wild_compare().
wild_one
char wild_one
Definition at line 252 of file my_sys.h.
wild_prefix
char wild_prefix
Definition at line 252 of file my_sys.h.