Azerotcore-wotlk: anonymous_namespace{BattlegroundSpamProtect.cpp} Namespace Reference
anonymous_namespace{BattlegroundSpamProtect.cpp} Namespace Reference
Functions
void AddTime (ObjectGuid guid)
uint32 GetTime (ObjectGuid guid)
bool IsCorrectDelay (ObjectGuid guid)
Variables
std::unordered_map< ObjectGuid, uint32 > _players
Function Documentation
AddTime()
void anonymous_namespace{BattlegroundSpamProtect.cpp}::AddTime (ObjectGuid guid)
Definition at line 28 of file BattlegroundSpamProtect.cpp.
     {
         _players.insert_or_assign(guid, sWorld->GetGameTime());
     }
References _players, and sWorld.
Referenced by BGSpamProtect::CanAnnounce().
GetTime()
uint32 anonymous_namespace{BattlegroundSpamProtect.cpp}::GetTime (ObjectGuid guid)
Definition at line 33 of file BattlegroundSpamProtect.cpp.
     {
         auto const& itr = _players.find(guid);
         if (itr != _players.end())
         {
             return itr->second;
         }
         return 0;
     }
References _players.
Referenced by IsCorrectDelay().
IsCorrectDelay()
bool anonymous_namespace{BattlegroundSpamProtect.cpp}::IsCorrectDelay (ObjectGuid guid)
Definition at line 44 of file BattlegroundSpamProtect.cpp.
     {
         // Skip if spam time < 30 secs (default)
         return sWorld->GetGameTime() - GetTime(guid) >= sWorld->getIntConfig(CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY);
     }
References CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY, GetTime(), and sWorld.
Referenced by BGSpamProtect::CanAnnounce().
Variable Documentation
_players
std::unordered_map<ObjectGuid , uint32 > anonymous_namespace{BattlegroundSpamProtect.cpp}::_players
Definition at line 26 of file BattlegroundSpamProtect.cpp.
Referenced by AddTime(), and GetTime().