Azerotcore-wotlk: deps/gsoap/soapH.h File Reference
soapH.h File Reference
#include "soapStub.h"
Macros
#define SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_ns1__executeCommand_DEFINED
#define SOAP_TYPE_ns1__executeCommandResponse_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerTostring_DEFINED
#define SOAP_TYPE__QName_DEFINED
#define soap__QName2s(soap, a) soap_QName2s(soap, (a))
#define soap_s2_QName(soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
#define soap_instantiate__QName soap_instantiate_string
#define soap_new__QName soap_new_string
#define SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE_string_DEFINED
#define soap_string2s(soap, a) (a)
#define soap_s2string(soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
Functions
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap *, const void *, int)
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap *)
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap *)
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement (struct soap *, const char *, int *)
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap *, const void *, const char *, int, int)
SOAP_FMAC3 void *SOAP_FMAC4 soap_dupelement (struct soap *, const void *, int)
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void *, int)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap *)
SOAP_FMAC3 void *SOAP_FMAC4 soap_instantiate (struct soap *, int, const char *, const char *, size_t *)
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap *soap, struct soap_clist *)
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int, int)
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap *, int, int, void *, size_t, const void *, void **)
void soap_default_byte (struct soap *soap, char *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap *, const char *, int, const char *, const char *)
SOAP_FMAC3 char *SOAP_FMAC4 soap_in_byte (struct soap *, const char *, char *, const char *)
SOAP_FMAC3 char *SOAP_FMAC4 soap_new_byte (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap *, const char *, const char *, const char *)
int soap_write_byte (struct soap *soap, char const *p)
int soap_PUT_byte (struct soap *soap, const char *URL, char const *p)
int soap_PATCH_byte (struct soap *soap, const char *URL, char const *p)
int soap_POST_send_byte (struct soap *soap, const char *URL, char const *p)
SOAP_FMAC3 char *SOAP_FMAC4 soap_get_byte (struct soap *, char *, const char *, const char *)
int soap_read_byte (struct soap *soap, char *p)
int soap_GET_byte (struct soap *soap, const char *URL, char *p)
int soap_POST_recv_byte (struct soap *soap, char *p)
void soap_default_int (struct soap *soap, int *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap *, const char *, int, const int *, const char *)
SOAP_FMAC3 int *SOAP_FMAC4 soap_in_int (struct soap *, const char *, int *, const char *)
SOAP_FMAC3 int *SOAP_FMAC4 soap_new_int (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap *, const int *, const char *, const char *)
int soap_write_int (struct soap *soap, int const *p)
int soap_PUT_int (struct soap *soap, const char *URL, int const *p)
int soap_PATCH_int (struct soap *soap, const char *URL, int const *p)
int soap_POST_send_int (struct soap *soap, const char *URL, int const *p)
SOAP_FMAC3 int *SOAP_FMAC4 soap_get_int (struct soap *, int *, const char *, const char *)
int soap_read_int (struct soap *soap, int *p)
int soap_GET_int (struct soap *soap, const char *URL, int *p)
int soap_POST_recv_int (struct soap *soap, int *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap *, struct SOAP_ENV__Fault *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap *, const struct SOAP_ENV__Fault *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap *, const char *, int, const struct SOAP_ENV__Fault *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap *, const char *, struct SOAP_ENV__Fault *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Fault *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault (struct soap *soap, int n=-1)
struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault (struct soap *soap)
struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault (struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap *, const struct SOAP_ENV__Fault *, const char *, const char *)
int soap_write_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault const *p)
int soap_PUT_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault const *p)
int soap_PATCH_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault const *p)
int soap_POST_send_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault const *p)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap *, struct SOAP_ENV__Fault *, const char *, const char *)
int soap_read_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *p)
int soap_GET_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault *p)
int soap_POST_recv_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap *, const struct SOAP_ENV__Reason *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap *, const char *, int, const struct SOAP_ENV__Reason *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap *, const char *, struct SOAP_ENV__Reason *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Reason *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason (struct soap *soap, int n=-1)
struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason (struct soap *soap)
struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason (struct soap *soap, char *SOAP_ENV__Text)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap *, const struct SOAP_ENV__Reason *, const char *, const char *)
int soap_write_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason const *p)
int soap_PUT_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason const *p)
int soap_PATCH_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason const *p)
int soap_POST_send_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason const *p)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *, const char *, const char *)
int soap_read_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *p)
int soap_GET_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason *p)
int soap_POST_recv_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap *, const struct SOAP_ENV__Detail *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap *, const char *, int, const struct SOAP_ENV__Detail *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap *, const char *, struct SOAP_ENV__Detail *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Detail *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail (struct soap *soap, int n=-1)
struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail (struct soap *soap, int __type, void *fault)
struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail (struct soap *soap, char *__any, int __type, void *fault)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap *, const struct SOAP_ENV__Detail *, const char *, const char *)
int soap_write_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail const *p)
int soap_PUT_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail const *p)
int soap_PATCH_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail const *p)
int soap_POST_send_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail const *p)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *, const char *, const char *)
int soap_read_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *p)
int soap_GET_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail *p)
int soap_POST_recv_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap *, const struct SOAP_ENV__Code *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap *, const char *, int, const struct SOAP_ENV__Code *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap *, const char *, struct SOAP_ENV__Code *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Code *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code (struct soap *soap, int n=-1)
struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code (struct soap *soap)
struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code (struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap *, const struct SOAP_ENV__Code *, const char *, const char *)
int soap_write_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code const *p)
int soap_PUT_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code const *p)
int soap_PATCH_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code const *p)
int soap_POST_send_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code const *p)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *, const char *, const char *)
int soap_read_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *p)
int soap_GET_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code *p)
int soap_POST_recv_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap *, struct SOAP_ENV__Header *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap *, const struct SOAP_ENV__Header *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap *, const char *, int, const struct SOAP_ENV__Header *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap *, const char *, struct SOAP_ENV__Header *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Header *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header (struct soap *soap, int n=-1)
struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header (struct soap *soap)
struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap *, const struct SOAP_ENV__Header *, const char *, const char *)
int soap_write_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header const *p)
int soap_PUT_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header const *p)
int soap_PATCH_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header const *p)
int soap_POST_send_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header const *p)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap *, struct SOAP_ENV__Header *, const char *, const char *)
int soap_read_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *p)
int soap_GET_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header *p)
int soap_POST_recv_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap *, struct ns1__executeCommand *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap *, const struct ns1__executeCommand *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap *, const char *, int, const struct ns1__executeCommand *, const char *)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap *, const char *, struct ns1__executeCommand *, const char *)
SOAP_FMAC1 struct ns1__executeCommand *SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap *, int, const char *, const char *, size_t *)
struct ns1__executeCommand * soap_new_ns1__executeCommand (struct soap *soap, int n=-1)
struct ns1__executeCommand * soap_new_req_ns1__executeCommand (struct soap *soap)
struct ns1__executeCommand * soap_new_set_ns1__executeCommand (struct soap *soap, char *command)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap *, const struct ns1__executeCommand *, const char *, const char *)
int soap_write_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand const *p)
int soap_PUT_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand const *p)
int soap_PATCH_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand const *p)
int soap_POST_send_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand const *p)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap *, struct ns1__executeCommand *, const char *, const char *)
int soap_read_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *p)
int soap_GET_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand *p)
int soap_POST_recv_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap *, struct ns1__executeCommandResponse *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap *, const struct ns1__executeCommandResponse *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap *, const char *, int, const struct ns1__executeCommandResponse *, const char *)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap *, const char *, struct ns1__executeCommandResponse *, const char *)
SOAP_FMAC1 struct ns1__executeCommandResponse *SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap *, int, const char *, const char *, size_t *)
struct ns1__executeCommandResponse * soap_new_ns1__executeCommandResponse (struct soap *soap, int n=-1)
struct ns1__executeCommandResponse * soap_new_req_ns1__executeCommandResponse (struct soap *soap)
struct ns1__executeCommandResponse * soap_new_set_ns1__executeCommandResponse (struct soap *soap, char **result)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap *, const struct ns1__executeCommandResponse *, const char *, const char *)
int soap_write_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse const *p)
int soap_PUT_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse const *p)
int soap_PATCH_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse const *p)
int soap_POST_send_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse const *p)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap *, struct ns1__executeCommandResponse *, const char *, const char *)
int soap_read_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *p)
int soap_GET_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse *p)
int soap_POST_recv_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap *, const char *, int, struct SOAP_ENV__Reason *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap *, const char *, struct SOAP_ENV__Reason **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap *, const char *, int, struct SOAP_ENV__Detail *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap *, const char *, struct SOAP_ENV__Detail **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap *, const char *, int, struct SOAP_ENV__Code *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap *, const char *, struct SOAP_ENV__Code **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap *, char **const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap *, const char *, int, char **const *, const char *)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_in_PointerTostring (struct soap *, const char *, char ***, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap *, char **const *, const char *, const char *)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_get_PointerTostring (struct soap *, char ***, const char *, const char *)
void soap_default__QName (struct soap *soap, char **a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap *, char *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap *, const char *, int, char *const *, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in__QName (struct soap *, const char *, char **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap *, char *const *, const char *, const char *)
int soap_write__QName (struct soap *soap, char *const *p)
int soap_PUT__QName (struct soap *soap, const char *URL, char *const *p)
int soap_PATCH__QName (struct soap *soap, const char *URL, char *const *p)
int soap_POST_send__QName (struct soap *soap, const char *URL, char *const *p)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get__QName (struct soap *, char **, const char *, const char *)
int soap_read__QName (struct soap *soap, char **p)
int soap_GET__QName (struct soap *soap, const char *URL, char **p)
int soap_POST_recv__QName (struct soap *soap, char **p)
void soap_default_string (struct soap *soap, char **a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap *, char *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap *, const char *, int, char *const *, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in_string (struct soap *, const char *, char **, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_new_string (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap *, char *const *, const char *, const char *)
int soap_write_string (struct soap *soap, char *const *p)
int soap_PUT_string (struct soap *soap, const char *URL, char *const *p)
int soap_PATCH_string (struct soap *soap, const char *URL, char *const *p)
int soap_POST_send_string (struct soap *soap, const char *URL, char *const *p)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get_string (struct soap *, char **, const char *, const char *)
int soap_read_string (struct soap *soap, char **p)
int soap_GET_string (struct soap *soap, const char *URL, char **p)
int soap_POST_recv_string (struct soap *soap, char **p)
Macro Definition Documentation
soap__QName2s
#define soap__QName2s (soap, a) soap_QName2s(soap, (a))
Definition at line 966 of file soapH.h.
soap_instantiate__QName
#define soap_instantiate__QName soap_instantiate_string
Definition at line 972 of file soapH.h.
soap_new__QName
#define soap_new__QName soap_new_string
Definition at line 975 of file soapH.h.
soap_s2_QName
#define soap_s2_QName (soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
Definition at line 969 of file soapH.h.
soap_s2string
#define soap_s2string (soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
Definition at line 1059 of file soapH.h.
soap_string2s
#define soap_string2s (soap, a) (a)
Definition at line 1056 of file soapH.h.
SOAP_TYPE__QName_DEFINED
#define SOAP_TYPE__QName_DEFINED
Definition at line 953 of file soapH.h.
SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE__XML_DEFINED
Definition at line 1039 of file soapH.h.
SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_byte_DEFINED
Definition at line 49 of file soapH.h.
SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_int_DEFINED
Definition at line 126 of file soapH.h.
SOAP_TYPE_ns1__executeCommand_DEFINED
#define SOAP_TYPE_ns1__executeCommand_DEFINED
Definition at line 717 of file soapH.h.
SOAP_TYPE_ns1__executeCommandResponse_DEFINED
#define SOAP_TYPE_ns1__executeCommandResponse_DEFINED
Definition at line 811 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
Definition at line 933 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
Definition at line 920 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
Definition at line 907 of file soapH.h.
SOAP_TYPE_PointerTostring_DEFINED
#define SOAP_TYPE_PointerTostring_DEFINED
Definition at line 944 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
Definition at line 523 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
Definition at line 417 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
Definition at line 205 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
Definition at line 623 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
Definition at line 319 of file soapH.h.
SOAP_TYPE_string_DEFINED
#define SOAP_TYPE_string_DEFINED
Definition at line 1043 of file soapH.h.
Function Documentation
soap_default__QName()
void soap_default__QName (struct soap * soap, char ** a) inline
Definition at line 955 of file soapH.h.
 {
     (void)soap; /* appease -Wall -Werror */
 #ifdef SOAP_DEFAULT__QName
     *a = SOAP_DEFAULT__QName;
 #else
     *a = (char *)0;
 #endif
 }
References mpq::a.
Referenced by soap_default_SOAP_ENV__Code(), and soap_default_SOAP_ENV__Fault().
soap_default_byte()
void soap_default_byte (struct soap * soap, char * a) inline
Definition at line 51 of file soapH.h.
 {
     (void)soap; /* appease -Wall -Werror */
 #ifdef SOAP_DEFAULT_byte
     *a = SOAP_DEFAULT_byte;
 #else
     *a = (char)0;
 #endif
 }
References mpq::a.
Referenced by soap_new_byte().
soap_default_int()
void soap_default_int (struct soap * soap, int * a) inline
Definition at line 128 of file soapH.h.
 {
     (void)soap; /* appease -Wall -Werror */
 #ifdef SOAP_DEFAULT_int
     *a = SOAP_DEFAULT_int;
 #else
     *a = (int)0;
 #endif
 }
References mpq::a.
Referenced by soap_new_int().
soap_default_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * a)
Definition at line 1261 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     soap_default_string(soap, &a->command);
 }
References mpq::a, and soap_default_string().
Referenced by soap_in_ns1__executeCommand(), soap_new_req_ns1__executeCommand(), soap_new_set_ns1__executeCommand(), soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_default_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * a)
Definition at line 1364 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     a->result = NULL;
 }
References mpq::a, and NULL.
Referenced by soap_in_ns1__executeCommandResponse(), soap_new_req_ns1__executeCommandResponse(), soap_new_set_ns1__executeCommandResponse(), soap_read_ns1__executeCommandResponse(), and soap_serve_ns1__executeCommand().
soap_default_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * a)
Definition at line 1047 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     soap_default__QName(soap, &a->SOAP_ENV__Value);
     a->SOAP_ENV__Subcode = NULL;
 }
References mpq::a, NULL, and soap_default__QName().
Referenced by soap_in_SOAP_ENV__Code(), soap_new_req_SOAP_ENV__Code(), soap_new_set_SOAP_ENV__Code(), and soap_read_SOAP_ENV__Code().
soap_default_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * a)
Definition at line 929 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     a->__any = NULL;
     a->__type = 0;
     a->fault = NULL;
 }
References mpq::a, and NULL.
Referenced by soap_in_SOAP_ENV__Detail(), soap_new_req_SOAP_ENV__Detail(), soap_new_set_SOAP_ENV__Detail(), and soap_read_SOAP_ENV__Detail().
soap_default_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * a)
Definition at line 623 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     soap_default__QName(soap, &a->faultcode);
     soap_default_string(soap, &a->faultstring);
     soap_default_string(soap, &a->faultactor);
     a->detail = NULL;
     a->SOAP_ENV__Code = NULL;
     a->SOAP_ENV__Reason = NULL;
     soap_default_string(soap, &a->SOAP_ENV__Node);
     soap_default_string(soap, &a->SOAP_ENV__Role);
     a->SOAP_ENV__Detail = NULL;
 }
References mpq::a, NULL, soap_default__QName(), and soap_default_string().
Referenced by soap_in_SOAP_ENV__Fault(), soap_new_req_SOAP_ENV__Fault(), soap_new_set_SOAP_ENV__Fault(), and soap_read_SOAP_ENV__Fault().
soap_default_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * a)
Definition at line 1167 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 }
References mpq::a.
Referenced by soap_in_SOAP_ENV__Header(), soap_instantiate_ns1__executeCommandResponse(), soap_new_req_SOAP_ENV__Header(), soap_new_set_SOAP_ENV__Header(), and soap_read_SOAP_ENV__Header().
soap_default_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * a)
Definition at line 820 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
     soap_default_string(soap, &a->SOAP_ENV__Text);
 }
References mpq::a, and soap_default_string().
Referenced by soap_in_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Reason(), soap_new_set_SOAP_ENV__Reason(), and soap_read_SOAP_ENV__Reason().
soap_default_string()
void soap_default_string (struct soap * soap, char ** a) inline
Definition at line 1045 of file soapH.h.
 {
     (void)soap; /* appease -Wall -Werror */
 #ifdef SOAP_DEFAULT_string
     *a = SOAP_DEFAULT_string;
 #else
     *a = (char *)0;
 #endif
 }
References mpq::a.
Referenced by soap_default_ns1__executeCommand(), soap_default_SOAP_ENV__Fault(), soap_default_SOAP_ENV__Reason(), and soap_new_string().
soap_delelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void * ptr, int type)
Definition at line 377 of file soapC.cpp.
 {(void)ptr; (void)type; /* appease -Wall -Werror */
 }
References ptr().
soap_dupelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_dupelement (struct soap * soap, const void * ptr, int type)
Definition at line 365 of file soapC.cpp.
 {(void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
     return NULL;
 }
References NULL, and ptr().
soap_fbase()
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int t, int b)
Definition at line 486 of file soapC.cpp.
 {
     (void)t; (void)b; /* appease -Wall -Werror */
     return 0;
 }
References b.
soap_fdelete()
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap * soap, struct soap_clist * p)
Definition at line 416 of file soapC.cpp.
 {
     (void)soap; /* appease -Wall -Werror */
     if (!p->ptr)
         return SOAP_OK;
     switch (p->type)
     {
     case SOAP_TYPE_ns1__executeCommandResponse:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct ns1__executeCommandResponse*>(p->ptr), struct ns1__executeCommandResponse);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct ns1__executeCommandResponse*>(p->ptr), struct ns1__executeCommandResponse);
         break;
     case SOAP_TYPE_ns1__executeCommand:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct ns1__executeCommand*>(p->ptr), struct ns1__executeCommand);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct ns1__executeCommand*>(p->ptr), struct ns1__executeCommand);
         break;
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Header:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct SOAP_ENV__Header*>(p->ptr), struct SOAP_ENV__Header);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct SOAP_ENV__Header*>(p->ptr), struct SOAP_ENV__Header);
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Code:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct SOAP_ENV__Code*>(p->ptr), struct SOAP_ENV__Code);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct SOAP_ENV__Code*>(p->ptr), struct SOAP_ENV__Code);
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Detail:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct SOAP_ENV__Detail*>(p->ptr), struct SOAP_ENV__Detail);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct SOAP_ENV__Detail*>(p->ptr), struct SOAP_ENV__Detail);
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Reason:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct SOAP_ENV__Reason*>(p->ptr), struct SOAP_ENV__Reason);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct SOAP_ENV__Reason*>(p->ptr), struct SOAP_ENV__Reason);
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Fault:
         if (p->size < 0)
             SOAP_DELETE(soap, static_cast<struct SOAP_ENV__Fault*>(p->ptr), struct SOAP_ENV__Fault);
         else
             SOAP_DELETE_ARRAY(soap, static_cast<struct SOAP_ENV__Fault*>(p->ptr), struct SOAP_ENV__Fault);
         break;
 #endif
     default:
         return SOAP_ERR;
     }
     return SOAP_OK;
 }
References soap_clist::ptr, soap_clist::size, SOAP_DELETE, SOAP_DELETE_ARRAY, SOAP_ERR, SOAP_OK, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, SOAP_TYPE_SOAP_ENV__Reason, and soap_clist::type.
soap_finsert()
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap * soap, int t, int tt, void * p, size_t index, const void * q, void ** x)
Definition at line 501 of file soapC.cpp.
 {
     (void)soap; (void)t; (void)p; (void)index; (void)q; (void)x; /* appease -Wall -Werror */
     switch (tt)
     {
     case SOAP_TYPE_ns1__executeCommandResponse:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct ns1__executeCommandResponse type=%d location=%p object=%p\n", t, p, q));
         *(struct ns1__executeCommandResponse*)p = *(struct ns1__executeCommandResponse*)q;
         break;
     case SOAP_TYPE_ns1__executeCommand:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct ns1__executeCommand type=%d location=%p object=%p\n", t, p, q));
         *(struct ns1__executeCommand*)p = *(struct ns1__executeCommand*)q;
         break;
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Header:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct SOAP_ENV__Header type=%d location=%p object=%p\n", t, p, q));
         *(struct SOAP_ENV__Header*)p = *(struct SOAP_ENV__Header*)q;
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Code:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct SOAP_ENV__Code type=%d location=%p object=%p\n", t, p, q));
         *(struct SOAP_ENV__Code*)p = *(struct SOAP_ENV__Code*)q;
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Detail:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct SOAP_ENV__Detail type=%d location=%p object=%p\n", t, p, q));
         *(struct SOAP_ENV__Detail*)p = *(struct SOAP_ENV__Detail*)q;
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Reason:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct SOAP_ENV__Reason type=%d location=%p object=%p\n", t, p, q));
         *(struct SOAP_ENV__Reason*)p = *(struct SOAP_ENV__Reason*)q;
         break;
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Fault:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Copy struct SOAP_ENV__Fault type=%d location=%p object=%p\n", t, p, q));
         *(struct SOAP_ENV__Fault*)p = *(struct SOAP_ENV__Fault*)q;
         break;
 #endif
     default:
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Could not insert type=%d in %d\n", t, tt));
     }
 }
References DBGLOG, index, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, SOAP_TYPE_SOAP_ENV__Reason, TEST(), and G3D::x.
Referenced by soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_get__QName()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get__QName (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1724 of file soapC.cpp.
 {
     if ((p = soap_in__QName(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in__QName().
Referenced by soap_read__QName().
soap_GET__QName()
int soap_GET__QName (struct soap * soap, const char * URL, char ** p) inline
Definition at line 1023 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read__QName(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read__QName().
soap_get_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_get_byte (struct soap * soap, char * p, const char * tag, const char * type)
Definition at line 579 of file soapC.cpp.
 {
     if ((p = soap_in_byte(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_byte().
Referenced by soap_read_byte().
soap_GET_byte()
int soap_GET_byte (struct soap * soap, const char * URL, char * p) inline
Definition at line 110 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_byte(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_byte().
soap_get_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_get_int (struct soap * soap, int * p, const char * tag, const char * type)
Definition at line 613 of file soapC.cpp.
 {
     if ((p = soap_in_int(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_int().
Referenced by soap_read_int().
soap_GET_int()
int soap_GET_int (struct soap * soap, const char * URL, int * p) inline
Definition at line 187 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_int(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_int().
soap_get_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p, const char * tag, const char * type)
Definition at line 1356 of file soapC.cpp.
 {
     if ((p = soap_in_ns1__executeCommand(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_ns1__executeCommand().
Referenced by soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_GET_ns1__executeCommand()
int soap_GET_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand * p) inline
Definition at line 795 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_ns1__executeCommand(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_ns1__executeCommand().
soap_get_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p, const char * tag, const char * type)
Definition at line 1459 of file soapC.cpp.
 {
     if ((p = soap_in_ns1__executeCommandResponse(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_ns1__executeCommandResponse().
Referenced by soap_read_ns1__executeCommandResponse().
soap_GET_ns1__executeCommandResponse()
int soap_GET_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse * p) inline
Definition at line 889 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_ns1__executeCommandResponse(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_ns1__executeCommandResponse().
soap_get_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code ** p, const char * tag, const char * type)
Definition at line 1634 of file soapC.cpp.
 {
     if ((p = soap_in_PointerToSOAP_ENV__Code(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_PointerToSOAP_ENV__Code().
soap_get_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail ** p, const char * tag, const char * type)
Definition at line 1573 of file soapC.cpp.
 {
     if ((p = soap_in_PointerToSOAP_ENV__Detail(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_PointerToSOAP_ENV__Detail().
soap_get_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason ** p, const char * tag, const char * type)
Definition at line 1515 of file soapC.cpp.
 {
     if ((p = soap_in_PointerToSOAP_ENV__Reason(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_PointerToSOAP_ENV__Reason().
soap_get_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_get_PointerTostring (struct soap * soap, char *** p, const char * tag, const char * type)
Definition at line 1690 of file soapC.cpp.
 {
     if ((p = soap_in_PointerTostring(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_PointerTostring().
soap_get_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p, const char * tag, const char * type)
Definition at line 1155 of file soapC.cpp.
 {
     if ((p = soap_in_SOAP_ENV__Code(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_SOAP_ENV__Code().
Referenced by soap_read_SOAP_ENV__Code().
soap_GET_SOAP_ENV__Code()
int soap_GET_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code * p) inline
Definition at line 603 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Code(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_SOAP_ENV__Code().
soap_get_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p, const char * tag, const char * type)
Definition at line 1035 of file soapC.cpp.
 {
     if ((p = soap_in_SOAP_ENV__Detail(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_SOAP_ENV__Detail().
Referenced by soap_read_SOAP_ENV__Detail().
soap_GET_SOAP_ENV__Detail()
int soap_GET_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail * p) inline
Definition at line 503 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Detail(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_SOAP_ENV__Detail().
soap_get_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p, const char * tag, const char * type)
Definition at line 808 of file soapC.cpp.
 {
     if ((p = soap_in_SOAP_ENV__Fault(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_SOAP_ENV__Fault().
Referenced by soap_read_SOAP_ENV__Fault().
soap_GET_SOAP_ENV__Fault()
int soap_GET_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault * p) inline
Definition at line 299 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Fault(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_SOAP_ENV__Fault().
soap_get_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p, const char * tag, const char * type)
Definition at line 1251 of file soapC.cpp.
 {
     if ((p = soap_in_SOAP_ENV__Header(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_SOAP_ENV__Header().
Referenced by soap_read_SOAP_ENV__Header().
soap_GET_SOAP_ENV__Header()
int soap_GET_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header * p) inline
Definition at line 699 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Header(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_SOAP_ENV__Header().
soap_get_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p, const char * tag, const char * type)
Definition at line 917 of file soapC.cpp.
 {
     if ((p = soap_in_SOAP_ENV__Reason(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_SOAP_ENV__Reason().
Referenced by soap_read_SOAP_ENV__Reason().
soap_GET_SOAP_ENV__Reason()
int soap_GET_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason * p) inline
Definition at line 397 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Reason(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_SOAP_ENV__Reason().
soap_get_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get_string (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1766 of file soapC.cpp.
 {
     if ((p = soap_in_string(soap, tag, p, type)))
         if (soap_getindependent(soap))
             return NULL;
     return p;
 }
References NULL, soap_getindependent(), and soap_in_string().
Referenced by soap_read_string().
soap_GET_string()
int soap_GET_string (struct soap * soap, const char * URL, char ** p) inline
Definition at line 1109 of file soapH.h.
 {
     if (soap_GET(soap, URL, NULL) || ::soap_read_string(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References NULL, soap_closesock(), soap_GET(), and soap_read_string().
soap_getelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_getelement (struct soap * soap, const char * tag, int * type)
Definition at line 181 of file soapC.cpp.
 {   (void)type;
     if (soap_peek_element(soap))
         return NULL;
 #ifndef WITH_NOIDREF
     if (!*soap->id || !(*type = soap_lookup_type(soap, soap->id)))
         *type = soap_lookup_type(soap, soap->href);
     switch (*type)
     {
     case SOAP_TYPE_byte:
         return soap_in_byte(soap, tag, NULL, "xsd:byte");
     case SOAP_TYPE_int:
         return soap_in_int(soap, tag, NULL, "xsd:int");
     case SOAP_TYPE_ns1__executeCommand:
         return soap_in_ns1__executeCommand(soap, tag, NULL, "ns1:executeCommand");
     case SOAP_TYPE_ns1__executeCommandResponse:
         return soap_in_ns1__executeCommandResponse(soap, tag, NULL, "ns1:executeCommandResponse");
     case SOAP_TYPE_PointerTostring:
         return soap_in_PointerTostring(soap, tag, NULL, "xsd:string");
     case SOAP_TYPE__QName:
     {   char **s;
         s = soap_in__QName(soap, tag, NULL, "xsd:QName");
         return s ? *s : NULL;
     }
     case SOAP_TYPE_string:
     {   char **s;
         s = soap_in_string(soap, tag, NULL, "xsd:string");
         return s ? *s : NULL;
     }
     default:
 #else
     *type = 0;
 #endif
     {   const char *t = soap->type;
         if (!*t)
             t = soap->tag;
         if (!soap_match_tag(soap, t, "xsd:byte"))
         {   *type = SOAP_TYPE_byte;
             return soap_in_byte(soap, tag, NULL, NULL);
         }
         if (!soap_match_tag(soap, t, "xsd:int"))
         {   *type = SOAP_TYPE_int;
             return soap_in_int(soap, tag, NULL, NULL);
         }
         if (!soap_match_tag(soap, t, "ns1:executeCommand"))
         {   *type = SOAP_TYPE_ns1__executeCommand;
             return soap_in_ns1__executeCommand(soap, tag, NULL, NULL);
         }
         if (!soap_match_tag(soap, t, "ns1:executeCommandResponse"))
         {   *type = SOAP_TYPE_ns1__executeCommandResponse;
             return soap_in_ns1__executeCommandResponse(soap, tag, NULL, NULL);
         }
         if (!soap_match_tag(soap, t, "xsd:QName"))
         {   char **s;
             *type = SOAP_TYPE__QName;
             s = soap_in__QName(soap, tag, NULL, NULL);
             return s ? *s : NULL;
         }
         if (!soap_match_tag(soap, t, "xsd:string"))
         {   char **s;
             *type = SOAP_TYPE_string;
             s = soap_in_string(soap, tag, NULL, NULL);
             return s ? *s : NULL;
         }
         t = soap->tag;
 #ifndef WITH_NOIDREF
     }
 #endif
     }
     soap->error = SOAP_TAG_MISMATCH;
     return NULL;
 }
References soap::href, soap::id, NULL, soap_lookup_type(), and soap_peek_element().
Referenced by soap_getindependent(), soap_ignore_element(), and soap_in_SOAP_ENV__Detail().
soap_getindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap * soap)
Definition at line 162 of file soapC.cpp.
 {
     int t;
     if (soap->version == 1)
     {   for (;;)
         {   if (!soap_getelement(soap, NULL, &t))
                 if ((soap->error && soap->error != SOAP_TAG_MISMATCH) || soap_ignore_element(soap))
                     break;
         }
     }
     if (soap->error == SOAP_NO_TAG || soap->error == SOAP_EOF)
         soap->error = SOAP_OK;
     return soap->error;
 }
References soap::error, NULL, SOAP_EOF, soap_getelement(), soap_ignore_element(), SOAP_NO_TAG, SOAP_OK, SOAP_TAG_MISMATCH, and soap::version.
Referenced by soap_get__QName(), soap_get_byte(), soap_get_int(), soap_get_ns1__executeCommand(), soap_get_ns1__executeCommandResponse(), soap_get_PointerToSOAP_ENV__Code(), soap_get_PointerToSOAP_ENV__Detail(), soap_get_PointerToSOAP_ENV__Reason(), soap_get_PointerTostring(), soap_get_SOAP_ENV__Code(), soap_get_SOAP_ENV__Detail(), soap_get_SOAP_ENV__Fault(), soap_get_SOAP_ENV__Header(), soap_get_SOAP_ENV__Reason(), and soap_get_string().
soap_ignore_element()
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap * soap)
Definition at line 258 of file soapC.cpp.
 {
     if (!soap_peek_element(soap))
     {   int t;
         DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Unexpected element '%s' in input at level = %u body = %d)\n", soap->tag, soap->level, soap->body));
         if (soap->mustUnderstand && !soap->other && !soap->fignore)
             return soap->error = SOAP_MUSTUNDERSTAND;
         if (((soap->mode & SOAP_XML_STRICT) && !soap->fignore && soap->part != SOAP_IN_HEADER) || !soap_match_tag(soap, soap->tag, "SOAP-ENV:"))
         {   DBGLOG(TEST, SOAP_MESSAGE(fdebug, "REJECTING element '%s'\n", soap->tag));
             return soap->error = SOAP_TAG_MISMATCH;
         }
         if (!*soap->id || !soap_getelement(soap, NULL, &t))
         {   soap->peeked = 0;
             if (soap->fignore)
                 soap->error = soap->fignore(soap, soap->tag);
             else
                 soap->error = SOAP_OK;
             DBGLOG(TEST, if (!soap->error) SOAP_MESSAGE(fdebug, "IGNORING element '%s'\n", soap->tag));
             if (!soap->error && soap->body && soap_ignore(soap))
                 return soap->error;
         }
     }
     return soap->error;
 }
References soap::body, DBGLOG, soap::error, soap::fignore, soap::id, soap::level, soap::mode, soap::mustUnderstand, NULL, soap::other, soap::part, soap::peeked, soap_getelement(), soap_ignore(), SOAP_IN_HEADER, soap_match_tag(), SOAP_MUSTUNDERSTAND, SOAP_OK, soap_peek_element(), SOAP_TAG_MISMATCH, SOAP_XML_STRICT, soap::tag, and TEST().
Referenced by soap_getindependent(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_in__QName()
SOAP_FMAC3 char* * SOAP_FMAC4 soap_in__QName (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1711 of file soapC.cpp.
 {
     a = soap_instring(soap, tag, a, type, SOAP_TYPE__QName, 2, 0, -1, NULL);
     return a;
 }
References mpq::a, NULL, soap_instring(), and SOAP_TYPE__QName.
Referenced by soap_get__QName(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Fault(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_in_byte (struct soap * soap, const char * tag, char * a, const char * type)
Definition at line 558 of file soapC.cpp.
 {
     a = soap_inbyte(soap, tag, a, type, SOAP_TYPE_byte);
     return a;
 }
References mpq::a, soap_inbyte(), and SOAP_TYPE_byte.
Referenced by soap_get_byte(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_in_int (struct soap * soap, const char * tag, int * a, const char * type)
Definition at line 592 of file soapC.cpp.
 {
     a = soap_inint(soap, tag, a, type, SOAP_TYPE_int);
     return a;
 }
References mpq::a, soap_inint(), and SOAP_TYPE_int.
Referenced by soap_get_int(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap * soap, const char * tag, struct ns1__executeCommand * a, const char * type)
Definition at line 1285 of file soapC.cpp.
 {
     size_t soap_flag_command = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct ns1__executeCommand*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__executeCommand, sizeof(struct ns1__executeCommand), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_ns1__executeCommand(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_command && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "command", (char**)&a->command, "xsd:string"))
                 {   soap_flag_command--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct ns1__executeCommand *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommand, sizeof(struct ns1__executeCommand), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_ns1__executeCommand(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_in_string(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_get_ns1__executeCommand(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap * soap, const char * tag, struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1388 of file soapC.cpp.
 {
     size_t soap_flag_result = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct ns1__executeCommandResponse*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__executeCommandResponse, sizeof(struct ns1__executeCommandResponse), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_ns1__executeCommandResponse(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_result && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerTostring(soap, "result", &a->result, "xsd:string"))
                 {   soap_flag_result--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct ns1__executeCommandResponse *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_ns1__executeCommandResponse, sizeof(struct ns1__executeCommandResponse), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_ns1__executeCommandResponse(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_in_PointerTostring(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_get_ns1__executeCommandResponse(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code ** a, const char * type)
Definition at line 1605 of file soapC.cpp.
 {
     (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_in(soap, tag, 1, NULL))
         return NULL;
     if (!a)
         if (!(a = (struct SOAP_ENV__Code **)soap_malloc(soap, sizeof(struct SOAP_ENV__Code *))))
             return NULL;
     *a = NULL;
     if (!soap->null && *soap->href != '#')
     {   soap_revert(soap);
         if (!(*a = soap_in_SOAP_ENV__Code(soap, tag, *a, type)))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Code **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::href, soap::null, NULL, soap_element_begin_in(), soap_element_end_in(), soap_id_lookup(), soap_in_SOAP_ENV__Code(), soap_malloc(), soap_revert(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_PointerToSOAP_ENV__Code(), soap_in_SOAP_ENV__Code(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail ** a, const char * type)
Definition at line 1544 of file soapC.cpp.
 {
     (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_in(soap, tag, 1, NULL))
         return NULL;
     if (!a)
         if (!(a = (struct SOAP_ENV__Detail **)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail *))))
             return NULL;
     *a = NULL;
     if (!soap->null && *soap->href != '#')
     {   soap_revert(soap);
         if (!(*a = soap_in_SOAP_ENV__Detail(soap, tag, *a, type)))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Detail **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::href, soap::null, NULL, soap_element_begin_in(), soap_element_end_in(), soap_id_lookup(), soap_in_SOAP_ENV__Detail(), soap_malloc(), soap_revert(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_PointerToSOAP_ENV__Detail(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason ** a, const char * type)
Definition at line 1486 of file soapC.cpp.
 {
     (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_in(soap, tag, 1, NULL))
         return NULL;
     if (!a)
         if (!(a = (struct SOAP_ENV__Reason **)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason *))))
             return NULL;
     *a = NULL;
     if (!soap->null && *soap->href != '#')
     {   soap_revert(soap);
         if (!(*a = soap_in_SOAP_ENV__Reason(soap, tag, *a, type)))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Reason **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::href, soap::null, NULL, soap_element_begin_in(), soap_element_end_in(), soap_id_lookup(), soap_in_SOAP_ENV__Reason(), soap_malloc(), soap_revert(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_PointerToSOAP_ENV__Reason(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_in_PointerTostring (struct soap * soap, const char * tag, char *** a, const char * type)
Definition at line 1661 of file soapC.cpp.
 {
     (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_in(soap, tag, 1, NULL))
         return NULL;
     if (!a)
         if (!(a = (char ***)soap_malloc(soap, sizeof(char **))))
             return NULL;
     *a = NULL;
     if (!soap->null && *soap->href != '#')
     {   soap_revert(soap);
         if (!(*a = soap_in_string(soap, tag, *a, type)))
             return NULL;
     }
     else
     {   a = (char ***)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_string, sizeof(char *), 1, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::href, soap::null, NULL, soap_element_begin_in(), soap_element_end_in(), soap_id_lookup(), soap_in_string(), soap_malloc(), soap_revert(), and SOAP_TYPE_string.
Referenced by soap_get_PointerTostring(), soap_in_ns1__executeCommandResponse(), and soap_instantiate_SOAP_ENV__Fault().
soap_in_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code * a, const char * type)
Definition at line 1077 of file soapC.cpp.
 {
     size_t soap_flag_SOAP_ENV__Value = 1;
     size_t soap_flag_SOAP_ENV__Subcode = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct SOAP_ENV__Code*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_SOAP_ENV__Code(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_SOAP_ENV__Value && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in__QName(soap, "SOAP-ENV:Value", (char**)&a->SOAP_ENV__Value, "xsd:QName"))
                 {   soap_flag_SOAP_ENV__Value--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Subcode && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", &a->SOAP_ENV__Subcode, ""))
                 {   soap_flag_SOAP_ENV__Subcode--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Code *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_SOAP_ENV__Code(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_SOAP_ENV__Code(), and soap_in_PointerToSOAP_ENV__Code().
soap_in_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail * a, const char * type)
Definition at line 957 of file soapC.cpp.
 {
     size_t soap_flag___any = 1;
     size_t soap_flag_fault = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct SOAP_ENV__Detail*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_SOAP_ENV__Detail(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_fault && soap->error == SOAP_TAG_MISMATCH)
             {   if ((a->fault = soap_getelement(soap, "fault", &a->__type)))
                 {   soap_flag_fault = 0;
                     continue;
                 }
             }
             if (soap_flag___any && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_inliteral(soap, "-any", (char**)&a->__any))
                 {   soap_flag___any--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Detail *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_SOAP_ENV__Detail(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_getelement(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_inliteral(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_SOAP_ENV__Detail(), and soap_in_PointerToSOAP_ENV__Detail().
soap_in_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap * soap, const char * tag, struct SOAP_ENV__Fault * a, const char * type)
Definition at line 681 of file soapC.cpp.
 {
     size_t soap_flag_faultcode = 1;
     size_t soap_flag_faultstring = 1;
     size_t soap_flag_faultactor = 1;
     size_t soap_flag_detail = 1;
     size_t soap_flag_SOAP_ENV__Code = 1;
     size_t soap_flag_SOAP_ENV__Reason = 1;
     size_t soap_flag_SOAP_ENV__Node = 1;
     size_t soap_flag_SOAP_ENV__Role = 1;
     size_t soap_flag_SOAP_ENV__Detail = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct SOAP_ENV__Fault*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_SOAP_ENV__Fault(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_faultcode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in__QName(soap, "faultcode", (char**)&a->faultcode, "xsd:QName"))
                 {   soap_flag_faultcode--;
                     continue;
                 }
             }
             if (soap_flag_faultstring && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "faultstring", (char**)&a->faultstring, "xsd:string"))
                 {   soap_flag_faultstring--;
                     continue;
                 }
             }
             if (soap_flag_faultactor && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "faultactor", (char**)&a->faultactor, "xsd:string"))
                 {   soap_flag_faultactor--;
                     continue;
                 }
             }
             if (soap_flag_detail && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerToSOAP_ENV__Detail(soap, "detail", &a->detail, ""))
                 {   soap_flag_detail--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Code && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", &a->SOAP_ENV__Code, ""))
                 {   soap_flag_SOAP_ENV__Code--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Reason && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", &a->SOAP_ENV__Reason, ""))
                 {   soap_flag_SOAP_ENV__Reason--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Node && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "SOAP-ENV:Node", (char**)&a->SOAP_ENV__Node, "xsd:string"))
                 {   soap_flag_SOAP_ENV__Node--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Role && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "SOAP-ENV:Role", (char**)&a->SOAP_ENV__Role, "xsd:string"))
                 {   soap_flag_SOAP_ENV__Role--;
                     continue;
                 }
             }
             if (soap_flag_SOAP_ENV__Detail && soap->error == SOAP_TAG_MISMATCH)
             {   if (soap_in_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", &a->SOAP_ENV__Detail, ""))
                 {   soap_flag_SOAP_ENV__Detail--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Fault *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_SOAP_ENV__Fault(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), soap_in_PointerToSOAP_ENV__Detail(), soap_in_PointerToSOAP_ENV__Reason(), soap_in_string(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_get_SOAP_ENV__Fault().
soap_in_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap * soap, const char * tag, struct SOAP_ENV__Header * a, const char * type)
Definition at line 1187 of file soapC.cpp.
 {
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct SOAP_ENV__Header*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_SOAP_ENV__Header(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Header *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Header, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_SOAP_ENV__Header(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_get_SOAP_ENV__Header(), and soap_getheader().
soap_in_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason * a, const char * type)
Definition at line 846 of file soapC.cpp.
 {
     size_t soap_flag_SOAP_ENV__Text = 1;
     if (soap_element_begin_in(soap, tag, 0, NULL))
         return NULL;
     (void)type; /* appease -Wall -Werror */
     a = (struct SOAP_ENV__Reason*)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), NULL, NULL, NULL, NULL);
     if (!a)
         return NULL;
     soap_default_SOAP_ENV__Reason(soap, a);
     if (soap->body && *soap->href != '#')
     {
         for (;;)
         {   soap->error = SOAP_TAG_MISMATCH;
             if (soap_flag_SOAP_ENV__Text && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
             {   if (soap_in_string(soap, "SOAP-ENV:Text", (char**)&a->SOAP_ENV__Text, "xsd:string"))
                 {   soap_flag_SOAP_ENV__Text--;
                     continue;
                 }
             }
             if (soap->error == SOAP_TAG_MISMATCH)
                 soap->error = soap_ignore_element(soap);
             if (soap->error == SOAP_NO_TAG)
                 break;
             if (soap->error)
                 return NULL;
         }
         if (soap_element_end_in(soap, tag))
             return NULL;
     }
     else
     {   a = (struct SOAP_ENV__Reason *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Reason, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, soap_finsert, NULL);
         if (soap->body && soap_element_end_in(soap, tag))
             return NULL;
     }
     return a;
 }
References mpq::a, soap::body, soap::error, soap::href, soap::id, NULL, soap_default_SOAP_ENV__Reason(), soap_element_begin_in(), soap_element_end_in(), soap_finsert(), soap_id_enter(), soap_id_forward(), soap_ignore_element(), soap_in_string(), SOAP_NO_TAG, SOAP_TAG_MISMATCH, and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_SOAP_ENV__Reason(), and soap_in_PointerToSOAP_ENV__Reason().
soap_in_string()
SOAP_FMAC3 char* * SOAP_FMAC4 soap_in_string (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1745 of file soapC.cpp.
 {
     a = soap_instring(soap, tag, a, type, SOAP_TYPE_string, 1, 0, -1, NULL);
     return a;
 }
References mpq::a, NULL, soap_instring(), and SOAP_TYPE_string.
Referenced by soap_get_string(), soap_in_ns1__executeCommand(), soap_in_PointerTostring(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Reason(), and soap_instantiate_SOAP_ENV__Fault().
soap_instantiate()
SOAP_FMAC3 void* SOAP_FMAC4 soap_instantiate (struct soap * soap, int t, const char * type, const char * arrayType, size_t * n)
Definition at line 384 of file soapC.cpp.
 {   (void)type;
     switch (t)
     {
     case SOAP_TYPE_ns1__executeCommandResponse:
         return (void*)soap_instantiate_ns1__executeCommandResponse(soap, -1, type, arrayType, n);
     case SOAP_TYPE_ns1__executeCommand:
         return (void*)soap_instantiate_ns1__executeCommand(soap, -1, type, arrayType, n);
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Header:
         return (void*)soap_instantiate_SOAP_ENV__Header(soap, -1, type, arrayType, n);
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Code:
         return (void*)soap_instantiate_SOAP_ENV__Code(soap, -1, type, arrayType, n);
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Detail:
         return (void*)soap_instantiate_SOAP_ENV__Detail(soap, -1, type, arrayType, n);
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Reason:
         return (void*)soap_instantiate_SOAP_ENV__Reason(soap, -1, type, arrayType, n);
 #endif
 #ifndef WITH_NOGLOBAL
     case SOAP_TYPE_SOAP_ENV__Fault:
         return (void*)soap_instantiate_SOAP_ENV__Fault(soap, -1, type, arrayType, n);
 #endif
     }
     return NULL;
 }
References NULL, soap_instantiate_ns1__executeCommand(), soap_instantiate_ns1__executeCommandResponse(), soap_instantiate_SOAP_ENV__Code(), soap_instantiate_SOAP_ENV__Detail(), soap_instantiate_SOAP_ENV__Fault(), soap_instantiate_SOAP_ENV__Header(), soap_instantiate_SOAP_ENV__Reason(), SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
soap_instantiate_ns1__executeCommand()
SOAP_FMAC1 struct ns1__executeCommand* SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 71 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_ns1__executeCommand(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct ns1__executeCommand *p;
     size_t k = sizeof(struct ns1__executeCommand);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_ns1__executeCommand, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct ns1__executeCommand);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct ns1__executeCommand, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct ns1__executeCommand location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
Referenced by soap_instantiate(), and soap_new_ns1__executeCommand().
soap_instantiate_ns1__executeCommandResponse()
SOAP_FMAC1 struct ns1__executeCommandResponse* SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 53 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_ns1__executeCommandResponse(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct ns1__executeCommandResponse *p;
     size_t k = sizeof(struct ns1__executeCommandResponse);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_ns1__executeCommandResponse, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct ns1__executeCommandResponse);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct ns1__executeCommandResponse, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct ns1__executeCommandResponse location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
References soap::header, soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
Referenced by soap_instantiate(), and soap_new_ns1__executeCommandResponse().
soap_instantiate_SOAP_ENV__Code()
SOAP_FMAC1 struct SOAP_ENV__Code* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 110 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_SOAP_ENV__Code(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct SOAP_ENV__Code *p;
     size_t k = sizeof(struct SOAP_ENV__Code);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_SOAP_ENV__Code, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct SOAP_ENV__Code);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct SOAP_ENV__Code, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct SOAP_ENV__Code location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Code().
soap_instantiate_SOAP_ENV__Detail()
SOAP_FMAC1 struct SOAP_ENV__Detail* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 133 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_SOAP_ENV__Detail(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct SOAP_ENV__Detail *p;
     size_t k = sizeof(struct SOAP_ENV__Detail);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_SOAP_ENV__Detail, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct SOAP_ENV__Detail);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct SOAP_ENV__Detail, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct SOAP_ENV__Detail location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
References NULL, and soap_faultstring().
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Detail().
soap_instantiate_SOAP_ENV__Fault()
SOAP_FMAC1 struct SOAP_ENV__Fault* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 189 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_SOAP_ENV__Fault(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct SOAP_ENV__Fault *p;
     size_t k = sizeof(struct SOAP_ENV__Fault);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_SOAP_ENV__Fault, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct SOAP_ENV__Fault);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct SOAP_ENV__Fault, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct SOAP_ENV__Fault location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
References NULL, soap_in__QName(), soap_in_byte(), soap_in_int(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_PointerTostring(), soap_in_string(), soap_match_tag(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, SOAP_TYPE_string, soap::tag, and soap::type.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Fault().
soap_instantiate_SOAP_ENV__Header()
SOAP_FMAC1 struct SOAP_ENV__Header* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 87 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_SOAP_ENV__Header(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct SOAP_ENV__Header *p;
     size_t k = sizeof(struct SOAP_ENV__Header);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_SOAP_ENV__Header, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct SOAP_ENV__Header);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct SOAP_ENV__Header, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct SOAP_ENV__Header location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Header().
soap_instantiate_SOAP_ENV__Reason()
SOAP_FMAC1 struct SOAP_ENV__Reason* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Friend allocator
Definition at line 153 of file soapC.cpp.
 {
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_instantiate_SOAP_ENV__Reason(%p, %d, %s, %s)\n", (void*)soap, n, type?type:"", arrayType?arrayType:""));
     (void)type; (void)arrayType; /* appease -Wall -Werror */
     struct SOAP_ENV__Reason *p;
     size_t k = sizeof(struct SOAP_ENV__Reason);
     struct soap_clist *cp = soap_link(soap, SOAP_TYPE_SOAP_ENV__Reason, n, soap_fdelete);
     if (!cp && soap && n != SOAP_NO_LINK_TO_DELETE)
         return NULL;
     if (n < 0)
     {   p = SOAP_NEW(soap, struct SOAP_ENV__Reason);
     }
     else
     {   p = SOAP_NEW_ARRAY(soap, struct SOAP_ENV__Reason, n);
         k *= n;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Instantiated struct SOAP_ENV__Reason location=%p n=%d\n", (void*)p, n));
     if (size)
         *size = k;
     if (!p)
         soap->error = SOAP_EOM;
     else if (cp)
         cp->ptr = (void*)p;
     return p;
 }
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Reason().
soap_markelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap * soap, const void * ptr, int type)
Definition at line 334 of file soapC.cpp.
 {
     (void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
     switch (type)
     {
     case SOAP_TYPE_ns1__executeCommand:
         soap_serialize_ns1__executeCommand(soap, (const struct ns1__executeCommand *)ptr);
         break;
     case SOAP_TYPE_ns1__executeCommandResponse:
         soap_serialize_ns1__executeCommandResponse(soap, (const struct ns1__executeCommandResponse *)ptr);
         break;
     case SOAP_TYPE_PointerTostring:
         soap_serialize_PointerTostring(soap, (char **const*)ptr);
         break;
     case SOAP_TYPE__QName:
         soap_serialize_string(soap, (char*const*)(void*)&ptr);
         break;
     case SOAP_TYPE_string:
         soap_serialize_string(soap, (char*const*)(void*)&ptr);
         break;
     }
 }
References ptr(), soap_serialize_ns1__executeCommand(), soap_serialize_ns1__executeCommandResponse(), soap_serialize_PointerTostring(), soap_serialize_string(), SOAP_TYPE__QName, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_serialize_SOAP_ENV__Detail().
soap_new_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_new_byte (struct soap * soap, int n = -1)
Definition at line 564 of file soapC.cpp.
 {
     char *a = static_cast<char *>(soap_malloc(soap, (n = (n < 0 ? 1 : n)) * sizeof(char)));
     for (char *p = a; p && n--; ++p)
         soap_default_byte(soap, p);
     return a;
 }
References mpq::a, soap_default_byte(), and soap_malloc().
soap_new_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_new_int (struct soap * soap, int n = -1)
Definition at line 598 of file soapC.cpp.
 {
     int *a = static_cast<int *>(soap_malloc(soap, (n = (n < 0 ? 1 : n)) * sizeof(int)));
     for (int *p = a; p && n--; ++p)
         soap_default_int(soap, p);
     return a;
 }
References mpq::a, soap_default_int(), and soap_malloc().
soap_new_ns1__executeCommand()
struct ns1__executeCommand* soap_new_ns1__executeCommand (struct soap * soap, int n = -1) inline
Definition at line 724 of file soapH.h.
 {
     return soap_instantiate_ns1__executeCommand(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_ns1__executeCommand().
Referenced by soap_new_req_ns1__executeCommand(), and soap_new_set_ns1__executeCommand().
soap_new_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_ns1__executeCommandResponse (struct soap * soap, int n = -1) inline
Definition at line 818 of file soapH.h.
 {
     return soap_instantiate_ns1__executeCommandResponse(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_ns1__executeCommandResponse().
Referenced by soap_new_req_ns1__executeCommandResponse(), and soap_new_set_ns1__executeCommandResponse().
soap_new_req_ns1__executeCommand()
struct ns1__executeCommand* soap_new_req_ns1__executeCommand (struct soap * soap) inline
Definition at line 729 of file soapH.h.
 {
     struct ns1__executeCommand *_p = ::soap_new_ns1__executeCommand(soap);
     if (_p)
     {   ::soap_default_ns1__executeCommand(soap, _p);
     }
     return _p;
 }
References soap_default_ns1__executeCommand(), and soap_new_ns1__executeCommand().
soap_new_req_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_req_ns1__executeCommandResponse (struct soap * soap) inline
Definition at line 823 of file soapH.h.
 {
     struct ns1__executeCommandResponse *_p = ::soap_new_ns1__executeCommandResponse(soap);
     if (_p)
     {   ::soap_default_ns1__executeCommandResponse(soap, _p);
     }
     return _p;
 }
References soap_default_ns1__executeCommandResponse(), and soap_new_ns1__executeCommandResponse().
soap_new_req_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_req_SOAP_ENV__Code (struct soap * soap) inline
Definition at line 535 of file soapH.h.
 {
     struct SOAP_ENV__Code *_p = ::soap_new_SOAP_ENV__Code(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Code(soap, _p);
     }
     return _p;
 }
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
soap_new_req_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_req_SOAP_ENV__Detail (struct soap * soap, int __type, void * fault) inline
Definition at line 429 of file soapH.h.
 {
     struct SOAP_ENV__Detail *_p = ::soap_new_SOAP_ENV__Detail(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Detail(soap, _p);
         _p->__type = __type;
         _p->fault = fault;
     }
     return _p;
 }
References SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
soap_new_req_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_req_SOAP_ENV__Fault (struct soap * soap) inline
Definition at line 217 of file soapH.h.
 {
     struct SOAP_ENV__Fault *_p = ::soap_new_SOAP_ENV__Fault(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Fault(soap, _p);
     }
     return _p;
 }
References soap_default_SOAP_ENV__Fault(), and soap_new_SOAP_ENV__Fault().
soap_new_req_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_req_SOAP_ENV__Header (struct soap * soap) inline
Definition at line 635 of file soapH.h.
 {
     struct SOAP_ENV__Header *_p = ::soap_new_SOAP_ENV__Header(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Header(soap, _p);
     }
     return _p;
 }
References soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
soap_new_req_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_req_SOAP_ENV__Reason (struct soap * soap) inline
Definition at line 331 of file soapH.h.
 {
     struct SOAP_ENV__Reason *_p = ::soap_new_SOAP_ENV__Reason(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Reason(soap, _p);
     }
     return _p;
 }
References soap_default_SOAP_ENV__Reason(), and soap_new_SOAP_ENV__Reason().
soap_new_set_ns1__executeCommand()
struct ns1__executeCommand* soap_new_set_ns1__executeCommand (struct soap * soap, char * command) inline
Definition at line 739 of file soapH.h.
 {
     struct ns1__executeCommand *_p = ::soap_new_ns1__executeCommand(soap);
     if (_p)
     {   ::soap_default_ns1__executeCommand(soap, _p);
         _p->command = command;
     }
     return _p;
 }
References ns1__executeCommand::command, soap_default_ns1__executeCommand(), and soap_new_ns1__executeCommand().
soap_new_set_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_set_ns1__executeCommandResponse (struct soap * soap, char ** result) inline
Definition at line 833 of file soapH.h.
 {
     struct ns1__executeCommandResponse *_p = ::soap_new_ns1__executeCommandResponse(soap);
     if (_p)
     {   ::soap_default_ns1__executeCommandResponse(soap, _p);
         _p->result = result;
     }
     return _p;
 }
References ns1__executeCommandResponse::result, soap_default_ns1__executeCommandResponse(), and soap_new_ns1__executeCommandResponse().
soap_new_set_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_set_SOAP_ENV__Code (struct soap * soap, char * SOAP_ENV__Value, struct SOAP_ENV__Code * SOAP_ENV__Subcode) inline
Definition at line 545 of file soapH.h.
 {
     struct SOAP_ENV__Code *_p = ::soap_new_SOAP_ENV__Code(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Code(soap, _p);
         _p->SOAP_ENV__Value = SOAP_ENV__Value;
         _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode;
     }
     return _p;
 }
References soap_default_SOAP_ENV__Code(), SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, and soap_new_SOAP_ENV__Code().
soap_new_set_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_set_SOAP_ENV__Detail (struct soap * soap, char * __any, int __type, void * fault) inline
Definition at line 443 of file soapH.h.
 {
     struct SOAP_ENV__Detail *_p = ::soap_new_SOAP_ENV__Detail(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Detail(soap, _p);
         _p->__any = __any;
         _p->__type = __type;
         _p->fault = fault;
     }
     return _p;
 }
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
soap_new_set_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_set_SOAP_ENV__Fault (struct soap * soap, char * faultcode, char * faultstring, char * faultactor, struct SOAP_ENV__Detail * detail, struct SOAP_ENV__Code * SOAP_ENV__Code, struct SOAP_ENV__Reason * SOAP_ENV__Reason, char * SOAP_ENV__Node, char * SOAP_ENV__Role, struct SOAP_ENV__Detail * SOAP_ENV__Detail) inline
Definition at line 227 of file soapH.h.
 {
     struct SOAP_ENV__Fault *_p = ::soap_new_SOAP_ENV__Fault(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Fault(soap, _p);
         _p->faultcode = faultcode;
         _p->faultstring = faultstring;
         _p->faultactor = faultactor;
         _p->detail = detail;
         _p->SOAP_ENV__Code = SOAP_ENV__Code;
         _p->SOAP_ENV__Reason = SOAP_ENV__Reason;
         _p->SOAP_ENV__Node = SOAP_ENV__Node;
         _p->SOAP_ENV__Role = SOAP_ENV__Role;
         _p->SOAP_ENV__Detail = SOAP_ENV__Detail;
     }
     return _p;
 }
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default_SOAP_ENV__Fault(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, and soap_new_SOAP_ENV__Fault().
soap_new_set_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_set_SOAP_ENV__Header (struct soap * soap) inline
Definition at line 645 of file soapH.h.
 {
     struct SOAP_ENV__Header *_p = ::soap_new_SOAP_ENV__Header(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Header(soap, _p);
     }
     return _p;
 }
References soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
soap_new_set_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_set_SOAP_ENV__Reason (struct soap * soap, char * SOAP_ENV__Text) inline
Definition at line 341 of file soapH.h.
 {
     struct SOAP_ENV__Reason *_p = ::soap_new_SOAP_ENV__Reason(soap);
     if (_p)
     {   ::soap_default_SOAP_ENV__Reason(soap, _p);
         _p->SOAP_ENV__Text = SOAP_ENV__Text;
     }
     return _p;
 }
References soap_default_SOAP_ENV__Reason(), SOAP_ENV__Reason::SOAP_ENV__Text, and soap_new_SOAP_ENV__Reason().
soap_new_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_SOAP_ENV__Code (struct soap * soap, int n = -1) inline
Definition at line 530 of file soapH.h.
 {
     return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_SOAP_ENV__Code().
Referenced by soap_fault(), soap_faultsubcode(), soap_new_req_SOAP_ENV__Code(), and soap_new_set_SOAP_ENV__Code().
soap_new_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_SOAP_ENV__Detail (struct soap * soap, int n = -1) inline
Definition at line 424 of file soapH.h.
 {
     return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_SOAP_ENV__Detail().
Referenced by soap_faultdetail(), soap_new_req_SOAP_ENV__Detail(), and soap_new_set_SOAP_ENV__Detail().
soap_new_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_SOAP_ENV__Fault (struct soap * soap, int n = -1) inline
Definition at line 212 of file soapH.h.
 {
     return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_SOAP_ENV__Fault().
Referenced by soap_fault(), soap_new_req_SOAP_ENV__Fault(), and soap_new_set_SOAP_ENV__Fault().
soap_new_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_SOAP_ENV__Header (struct soap * soap, int n = -1) inline
Definition at line 630 of file soapH.h.
 {
     return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_SOAP_ENV__Header().
Referenced by soap_instantiate_ns1__executeCommandResponse(), soap_new_req_SOAP_ENV__Header(), and soap_new_set_SOAP_ENV__Header().
soap_new_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_SOAP_ENV__Reason (struct soap * soap, int n = -1) inline
Definition at line 326 of file soapH.h.
 {
     return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL);
 }
References NULL, and soap_instantiate_SOAP_ENV__Reason().
Referenced by soap_fault(), soap_new_req_SOAP_ENV__Reason(), and soap_new_set_SOAP_ENV__Reason().
soap_new_string()
SOAP_FMAC3 char* * SOAP_FMAC4 soap_new_string (struct soap * soap, int n = -1)
Definition at line 1751 of file soapC.cpp.
 {
     char * *a = static_cast<char * *>(soap_malloc(soap, (n = (n < 0 ? 1 : n)) * sizeof(char *)));
     for (char * *p = a; p && n--; ++p)
         soap_default_string(soap, p);
     return a;
 }
References mpq::a, soap_default_string(), and soap_malloc().
soap_out__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1706 of file soapC.cpp.
 {
     return soap_outstring(soap, tag, id, a, type, SOAP_TYPE__QName);
 }
References mpq::a, soap_outstring(), and SOAP_TYPE__QName.
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put__QName().
soap_out_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap * soap, const char * tag, int id, const char * a, const char * type)
Definition at line 553 of file soapC.cpp.
 {
     return soap_outbyte(soap, tag, id, a, type, SOAP_TYPE_byte);
 }
References mpq::a, soap_outbyte(), and SOAP_TYPE_byte.
Referenced by soap_put_byte(), and soap_putelement().
soap_out_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap * soap, const char * tag, int id, const int * a, const char * type)
Definition at line 587 of file soapC.cpp.
 {
     return soap_outint(soap, tag, id, a, type, SOAP_TYPE_int);
 }
References mpq::a, soap_outint(), and SOAP_TYPE_int.
Referenced by soap_put_int(), and soap_putelement().
soap_out_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap * soap, const char * tag, int id, const struct ns1__executeCommand * a, const char * type)
Definition at line 1275 of file soapC.cpp.
 {
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__executeCommand), type))
         return soap->error;
     if (soap_out_string(soap, "command", -1, (char*const*)&a->command, ""))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_out_string(), and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_put_ns1__executeCommand(), and soap_putelement().
soap_out_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap * soap, const char * tag, int id, const struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1378 of file soapC.cpp.
 {
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__executeCommandResponse), type))
         return soap->error;
     if (soap_out_PointerTostring(soap, "result", -1, &a->result, ""))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_out_PointerTostring(), and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_put_ns1__executeCommandResponse(), and soap_putelement().
soap_out_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Code *const * a, const char * type)
Definition at line 1594 of file soapC.cpp.
 {
     char *mark;
     id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Code, &mark);
     if (id < 0)
         return soap->error;
     (void)soap_out_SOAP_ENV__Code(soap, tag, id, *a, type);
     soap_unmark(soap, mark);
     return soap->error;
 }
References mpq::a, soap::error, NULL, soap_element_id(), soap_out_SOAP_ENV__Code(), SOAP_TYPE_SOAP_ENV__Code, and soap_unmark().
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Code().
soap_out_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Detail *const * a, const char * type)
Definition at line 1536 of file soapC.cpp.
 {
     id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Detail, NULL);
     if (id < 0)
         return soap->error;
     return soap_out_SOAP_ENV__Detail(soap, tag, id, *a, type);
 }
References mpq::a, soap::error, NULL, soap_element_id(), soap_out_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Detail().
soap_out_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Reason *const * a, const char * type)
Definition at line 1478 of file soapC.cpp.
 {
     id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Reason, NULL);
     if (id < 0)
         return soap->error;
     return soap_out_SOAP_ENV__Reason(soap, tag, id, *a, type);
 }
References mpq::a, soap::error, NULL, soap_element_id(), soap_out_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Reason().
soap_out_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap * soap, const char * tag, int id, char **const * a, const char * type)
Definition at line 1653 of file soapC.cpp.
 {
     id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_string, NULL);
     if (id < 0)
         return soap->error;
     return soap_out_string(soap, tag, id, *a, type);
 }
References mpq::a, soap::error, NULL, soap_element_id(), soap_out_string(), and SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommandResponse(), soap_put_PointerTostring(), and soap_putelement().
soap_out_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Code * a, const char * type)
Definition at line 1063 of file soapC.cpp.
 {
     const char *soap_tmp_SOAP_ENV__Value;
     soap_tmp_SOAP_ENV__Value = soap_QName2s(soap, a->SOAP_ENV__Value);
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Code), type))
         return soap->error;
     if (soap_out__QName(soap, "SOAP-ENV:Value", -1, (char*const*)(void*)&soap_tmp_SOAP_ENV__Value, ""))
         return soap->error;
     if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", -1, &a->SOAP_ENV__Subcode, ""))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, if(), soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), soap_QName2s(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_out_PointerToSOAP_ENV__Code(), and soap_put_SOAP_ENV__Code().
soap_out_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Detail * a, const char * type)
Definition at line 945 of file soapC.cpp.
 {
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Detail), type))
         return soap->error;
     if (soap_outliteral(soap, "-any", (char*const*)&a->__any, NULL))
         return soap->error;
     if (soap_putelement(soap, a->fault, "fault", -1, a->__type))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, NULL, soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_outliteral(), soap_putelement(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_PointerToSOAP_ENV__Detail(), and soap_put_SOAP_ENV__Detail().
soap_out_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Fault * a, const char * type)
Definition at line 653 of file soapC.cpp.
 {
     const char *soap_tmp_faultcode;
     soap_tmp_faultcode = soap_QName2s(soap, a->faultcode);
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Fault), type))
         return soap->error;
     if (soap_out__QName(soap, "faultcode", -1, (char*const*)(void*)&soap_tmp_faultcode, ""))
         return soap->error;
     if (soap_out_string(soap, "faultstring", -1, (char*const*)&a->faultstring, ""))
         return soap->error;
     if (soap_out_string(soap, "faultactor", -1, (char*const*)&a->faultactor, ""))
         return soap->error;
     if (soap_out_PointerToSOAP_ENV__Detail(soap, "detail", -1, &a->detail, ""))
         return soap->error;
     if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", -1, &a->SOAP_ENV__Code, ""))
         return soap->error;
     if (soap_out_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", -1, &a->SOAP_ENV__Reason, ""))
         return soap->error;
     if (soap_out_string(soap, "SOAP-ENV:Node", -1, (char*const*)&a->SOAP_ENV__Node, ""))
         return soap->error;
     if (soap_out_string(soap, "SOAP-ENV:Role", -1, (char*const*)&a->SOAP_ENV__Role, ""))
         return soap->error;
     if (soap_out_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", -1, &a->SOAP_ENV__Detail, ""))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, if(), soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), soap_out_PointerToSOAP_ENV__Detail(), soap_out_PointerToSOAP_ENV__Reason(), soap_out_string(), soap_QName2s(), and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_put_SOAP_ENV__Fault().
soap_out_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Header * a, const char * type)
Definition at line 1179 of file soapC.cpp.
 {
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Header), type))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), and SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_put_SOAP_ENV__Header(), and soap_putheader().
soap_out_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Reason * a, const char * type)
Definition at line 834 of file soapC.cpp.
 {
     (void)soap; (void)tag; (void)id; (void)a; (void)type; /* appease -Wall -Werror */
     if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Reason), type))
         return soap->error;
     if (soap->lang)
         soap_set_attr(soap, "xml:lang", soap->lang, 1);
     if (soap_out_string(soap, "SOAP-ENV:Text", -1, (char*const*)&a->SOAP_ENV__Text, ""))
         return soap->error;
     return soap_element_end_out(soap, tag);
 }
References mpq::a, soap::error, soap::lang, soap_element_begin_out(), soap_element_end_out(), soap_embedded_id(), soap_out_string(), soap_set_attr(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_PointerToSOAP_ENV__Reason(), and soap_put_SOAP_ENV__Reason().
soap_out_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1740 of file soapC.cpp.
 {
     return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_string);
 }
References mpq::a, soap_outstring(), and SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommand(), soap_out_PointerTostring(), soap_out_SOAP_ENV__Fault(), soap_out_SOAP_ENV__Reason(), soap_put_string(), and soap_putelement().
soap_PATCH__QName()
int soap_PATCH__QName (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 997 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put__QName(), and soap_recv_empty_response().
soap_PATCH_byte()
int soap_PATCH_byte (struct soap * soap, const char * URL, char const * p) inline
Definition at line 84 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_byte(), and soap_recv_empty_response().
soap_PATCH_int()
int soap_PATCH_int (struct soap * soap, const char * URL, int const * p) inline
Definition at line 161 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_int(), and soap_recv_empty_response().
soap_PATCH_ns1__executeCommand()
int soap_PATCH_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand const * p) inline
Definition at line 768 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommand(soap, p), 0) || ::soap_put_ns1__executeCommand(soap, p, "ns1:executeCommand", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_ns1__executeCommand(), soap_recv_empty_response(), and soap_serialize_ns1__executeCommand().
soap_PATCH_ns1__executeCommandResponse()
int soap_PATCH_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse const * p) inline
Definition at line 862 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommandResponse(soap, p), 0) || ::soap_put_ns1__executeCommandResponse(soap, p, "ns1:executeCommandResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_ns1__executeCommandResponse(), soap_recv_empty_response(), and soap_serialize_ns1__executeCommandResponse().
soap_PATCH_SOAP_ENV__Code()
int soap_PATCH_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code const * p) inline
Definition at line 576 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_SOAP_ENV__Code(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Code().
soap_PATCH_SOAP_ENV__Detail()
int soap_PATCH_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail const * p) inline
Definition at line 476 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_SOAP_ENV__Detail(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Detail().
soap_PATCH_SOAP_ENV__Fault()
int soap_PATCH_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault const * p) inline
Definition at line 272 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_SOAP_ENV__Fault(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Fault().
soap_PATCH_SOAP_ENV__Header()
int soap_PATCH_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header const * p) inline
Definition at line 672 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_SOAP_ENV__Header(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Header().
soap_PATCH_SOAP_ENV__Reason()
int soap_PATCH_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason const * p) inline
Definition at line 370 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_SOAP_ENV__Reason(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Reason().
soap_PATCH_string()
int soap_PATCH_string (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1083 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PATCH(), soap_put_string(), and soap_recv_empty_response().
soap_POST_recv__QName()
int soap_POST_recv__QName (struct soap * soap, char ** p) inline
Definition at line 1030 of file soapH.h.
 {
     if (::soap_read__QName(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read__QName().
soap_POST_recv_byte()
int soap_POST_recv_byte (struct soap * soap, char * p) inline
Definition at line 117 of file soapH.h.
 {
     if (::soap_read_byte(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_byte().
soap_POST_recv_int()
int soap_POST_recv_int (struct soap * soap, int * p) inline
Definition at line 194 of file soapH.h.
 {
     if (::soap_read_int(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_int().
soap_POST_recv_ns1__executeCommand()
int soap_POST_recv_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p) inline
Definition at line 802 of file soapH.h.
 {
     if (::soap_read_ns1__executeCommand(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_ns1__executeCommand().
soap_POST_recv_ns1__executeCommandResponse()
int soap_POST_recv_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p) inline
Definition at line 896 of file soapH.h.
 {
     if (::soap_read_ns1__executeCommandResponse(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_ns1__executeCommandResponse().
soap_POST_recv_SOAP_ENV__Code()
int soap_POST_recv_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p) inline
Definition at line 610 of file soapH.h.
 {
     if (::soap_read_SOAP_ENV__Code(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_SOAP_ENV__Code().
soap_POST_recv_SOAP_ENV__Detail()
int soap_POST_recv_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p) inline
Definition at line 510 of file soapH.h.
 {
     if (::soap_read_SOAP_ENV__Detail(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_SOAP_ENV__Detail().
soap_POST_recv_SOAP_ENV__Fault()
int soap_POST_recv_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p) inline
Definition at line 306 of file soapH.h.
 {
     if (::soap_read_SOAP_ENV__Fault(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_SOAP_ENV__Fault().
soap_POST_recv_SOAP_ENV__Header()
int soap_POST_recv_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p) inline
Definition at line 706 of file soapH.h.
 {
     if (::soap_read_SOAP_ENV__Header(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_SOAP_ENV__Header().
soap_POST_recv_SOAP_ENV__Reason()
int soap_POST_recv_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p) inline
Definition at line 404 of file soapH.h.
 {
     if (::soap_read_SOAP_ENV__Reason(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_SOAP_ENV__Reason().
soap_POST_recv_string()
int soap_POST_recv_string (struct soap * soap, char ** p) inline
Definition at line 1116 of file soapH.h.
 {
     if (::soap_read_string(soap, p))
         return soap_closesock(soap);
     return soap_closesock(soap);
 }
References soap_closesock(), and soap_read_string().
soap_POST_send__QName()
int soap_POST_send__QName (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1005 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), and soap_put__QName().
soap_POST_send_byte()
int soap_POST_send_byte (struct soap * soap, const char * URL, char const * p) inline
Definition at line 92 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), and soap_put_byte().
soap_POST_send_int()
int soap_POST_send_int (struct soap * soap, const char * URL, int const * p) inline
Definition at line 169 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), and soap_put_int().
soap_POST_send_ns1__executeCommand()
int soap_POST_send_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand const * p) inline
Definition at line 776 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommand(soap, p), 0) || ::soap_put_ns1__executeCommand(soap, p, "ns1:executeCommand", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_ns1__executeCommand(), and soap_serialize_ns1__executeCommand().
soap_POST_send_ns1__executeCommandResponse()
int soap_POST_send_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse const * p) inline
Definition at line 870 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommandResponse(soap, p), 0) || ::soap_put_ns1__executeCommandResponse(soap, p, "ns1:executeCommandResponse", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_ns1__executeCommandResponse(), and soap_serialize_ns1__executeCommandResponse().
soap_POST_send_SOAP_ENV__Code()
int soap_POST_send_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code const * p) inline
Definition at line 584 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Code().
soap_POST_send_SOAP_ENV__Detail()
int soap_POST_send_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail const * p) inline
Definition at line 484 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_SOAP_ENV__Detail(), and soap_serialize_SOAP_ENV__Detail().
soap_POST_send_SOAP_ENV__Fault()
int soap_POST_send_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault const * p) inline
Definition at line 280 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Fault().
soap_POST_send_SOAP_ENV__Header()
int soap_POST_send_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header const * p) inline
Definition at line 680 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_SOAP_ENV__Header(), and soap_serialize_SOAP_ENV__Header().
soap_POST_send_SOAP_ENV__Reason()
int soap_POST_send_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason const * p) inline
Definition at line 378 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), soap_put_SOAP_ENV__Reason(), and soap_serialize_SOAP_ENV__Reason().
soap_POST_send_string()
int soap_POST_send_string (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1091 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_POST(), and soap_put_string().
soap_put__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1717 of file soapC.cpp.
 {
     if (soap_out__QName(soap, tag ? tag : "QName", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out__QName(), and soap_putindependent().
Referenced by soap_PATCH__QName(), soap_POST_send__QName(), soap_PUT__QName(), and soap_write__QName().
soap_PUT__QName()
int soap_PUT__QName (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 989 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put__QName(), and soap_recv_empty_response().
soap_put_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap * soap, const char * a, const char * tag, const char * type)
Definition at line 572 of file soapC.cpp.
 {
     if (soap_out_byte(soap, tag ? tag : "byte", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_byte(), and soap_putindependent().
Referenced by soap_PATCH_byte(), soap_POST_send_byte(), soap_PUT_byte(), and soap_write_byte().
soap_PUT_byte()
int soap_PUT_byte (struct soap * soap, const char * URL, char const * p) inline
Definition at line 76 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_byte(), and soap_recv_empty_response().
soap_put_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap * soap, const int * a, const char * tag, const char * type)
Definition at line 606 of file soapC.cpp.
 {
     if (soap_out_int(soap, tag ? tag : "int", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_int(), and soap_putindependent().
Referenced by soap_PATCH_int(), soap_POST_send_int(), soap_PUT_int(), and soap_write_int().
soap_PUT_int()
int soap_PUT_int (struct soap * soap, const char * URL, int const * p) inline
Definition at line 153 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_int(), and soap_recv_empty_response().
soap_put_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a, const char * tag, const char * type)
Definition at line 1349 of file soapC.cpp.
 {
     if (soap_out_ns1__executeCommand(soap, tag ? tag : "ns1:executeCommand", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_ns1__executeCommand(), and soap_putindependent().
Referenced by soap_PATCH_ns1__executeCommand(), soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_PUT_ns1__executeCommand()
int soap_PUT_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand const * p) inline
Definition at line 760 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommand(soap, p), 0) || ::soap_put_ns1__executeCommand(soap, p, "ns1:executeCommand", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_ns1__executeCommand(), soap_recv_empty_response(), and soap_serialize_ns1__executeCommand().
soap_put_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a, const char * tag, const char * type)
Definition at line 1452 of file soapC.cpp.
 {
     if (soap_out_ns1__executeCommandResponse(soap, tag ? tag : "ns1:executeCommandResponse", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_ns1__executeCommandResponse(), and soap_putindependent().
Referenced by soap_PATCH_ns1__executeCommandResponse(), soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_PUT_ns1__executeCommandResponse()
int soap_PUT_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse const * p) inline
Definition at line 854 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns1__executeCommandResponse(soap, p), 0) || ::soap_put_ns1__executeCommandResponse(soap, p, "ns1:executeCommandResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_ns1__executeCommandResponse(), soap_recv_empty_response(), and soap_serialize_ns1__executeCommandResponse().
soap_put_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a, const char * tag, const char * type)
Definition at line 1627 of file soapC.cpp.
 {
     if (soap_out_PointerToSOAP_ENV__Code(soap, tag ? tag : "SOAP-ENV:Code", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_PointerToSOAP_ENV__Code(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a, const char * tag, const char * type)
Definition at line 1566 of file soapC.cpp.
 {
     if (soap_out_PointerToSOAP_ENV__Detail(soap, tag ? tag : "SOAP-ENV:Detail", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_PointerToSOAP_ENV__Detail(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a, const char * tag, const char * type)
Definition at line 1508 of file soapC.cpp.
 {
     if (soap_out_PointerToSOAP_ENV__Reason(soap, tag ? tag : "SOAP-ENV:Reason", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_PointerToSOAP_ENV__Reason(), and soap_putindependent().
soap_put_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap * soap, char **const * a, const char * tag, const char * type)
Definition at line 1683 of file soapC.cpp.
 {
     if (soap_out_PointerTostring(soap, tag ? tag : "string", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_PointerTostring(), and soap_putindependent().
soap_put_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a, const char * tag, const char * type)
Definition at line 1148 of file soapC.cpp.
 {
     if (soap_out_SOAP_ENV__Code(soap, tag ? tag : "SOAP-ENV:Code", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_SOAP_ENV__Code(), and soap_putindependent().
Referenced by soap_PATCH_SOAP_ENV__Code(), soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_PUT_SOAP_ENV__Code()
int soap_PUT_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code const * p) inline
Definition at line 568 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_SOAP_ENV__Code(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Code().
soap_put_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a, const char * tag, const char * type)
Definition at line 1028 of file soapC.cpp.
 {
     if (soap_out_SOAP_ENV__Detail(soap, tag ? tag : "SOAP-ENV:Detail", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_SOAP_ENV__Detail(), and soap_putindependent().
Referenced by soap_PATCH_SOAP_ENV__Detail(), soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_PUT_SOAP_ENV__Detail()
int soap_PUT_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail const * p) inline
Definition at line 468 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_SOAP_ENV__Detail(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Detail().
soap_put_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a, const char * tag, const char * type)
Definition at line 801 of file soapC.cpp.
 {
     if (soap_out_SOAP_ENV__Fault(soap, tag ? tag : "SOAP-ENV:Fault", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_SOAP_ENV__Fault(), and soap_putindependent().
Referenced by soap_PATCH_SOAP_ENV__Fault(), soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_putfault(), and soap_write_SOAP_ENV__Fault().
soap_PUT_SOAP_ENV__Fault()
int soap_PUT_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault const * p) inline
Definition at line 264 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_SOAP_ENV__Fault(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Fault().
soap_put_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a, const char * tag, const char * type)
Definition at line 1244 of file soapC.cpp.
 {
     if (soap_out_SOAP_ENV__Header(soap, tag ? tag : "SOAP-ENV:Header", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_SOAP_ENV__Header(), and soap_putindependent().
Referenced by soap_PATCH_SOAP_ENV__Header(), soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), and soap_write_SOAP_ENV__Header().
soap_PUT_SOAP_ENV__Header()
int soap_PUT_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header const * p) inline
Definition at line 664 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_SOAP_ENV__Header(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Header().
soap_put_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a, const char * tag, const char * type)
Definition at line 910 of file soapC.cpp.
 {
     if (soap_out_SOAP_ENV__Reason(soap, tag ? tag : "SOAP-ENV:Reason", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_SOAP_ENV__Reason(), and soap_putindependent().
Referenced by soap_PATCH_SOAP_ENV__Reason(), soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_PUT_SOAP_ENV__Reason()
int soap_PUT_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason const * p) inline
Definition at line 362 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_SOAP_ENV__Reason(), soap_recv_empty_response(), and soap_serialize_SOAP_ENV__Reason().
soap_put_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1759 of file soapC.cpp.
 {
     if (soap_out_string(soap, tag ? tag : "string", -2, a, type))
         return soap->error;
     return soap_putindependent(soap);
 }
References mpq::a, soap::error, soap_out_string(), and soap_putindependent().
Referenced by soap_PATCH_string(), soap_POST_send_string(), soap_PUT_string(), and soap_write_string().
soap_PUT_string()
int soap_PUT_string (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1075 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
         return soap_closesock(soap);
     return SOAP_OK;
 }
References NULL, soap_closesock(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_PUT(), soap_put_string(), and soap_recv_empty_response().
soap_putelement()
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap * soap, const void * ptr, const char * tag, int id, int type)
Definition at line 301 of file soapC.cpp.
 {   (void)tag;
     switch (type)
     {
     case SOAP_TYPE_byte:
         return soap_out_byte(soap, tag, id, (const char *)ptr, "xsd:byte");
     case SOAP_TYPE_int:
         return soap_out_int(soap, tag, id, (const int *)ptr, "xsd:int");
     case SOAP_TYPE_ns1__executeCommand:
         return soap_out_ns1__executeCommand(soap, tag, id, (const struct ns1__executeCommand *)ptr, "ns1:executeCommand");
     case SOAP_TYPE_ns1__executeCommandResponse:
         return soap_out_ns1__executeCommandResponse(soap, tag, id, (const struct ns1__executeCommandResponse *)ptr, "ns1:executeCommandResponse");
     case SOAP_TYPE_PointerTostring:
         return soap_out_PointerTostring(soap, tag, id, (char **const*)ptr, "xsd:string");
     case SOAP_TYPE__QName:
         return soap_out_string(soap, tag, id, (char*const*)(void*)&ptr, "xsd:QName");
     case SOAP_TYPE_string:
         return soap_out_string(soap, tag, id, (char*const*)(void*)&ptr, "xsd:string");
     case 0:
         return SOAP_OK;
     }
     DBGLOG(TEST, SOAP_MESSAGE(fdebug, "soap_putelement '%s' failed for type %d in soapC.cpp\n", tag ? tag : "", type));
     return soap_element_empty(soap, tag); /* unknown type to serialize */
 }
References DBGLOG, ptr(), soap_element_empty(), SOAP_OK, soap_out_byte(), soap_out_int(), soap_out_ns1__executeCommand(), soap_out_ns1__executeCommandResponse(), soap_out_PointerTostring(), soap_out_string(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, SOAP_TYPE_string, and TEST().
Referenced by soap_out_SOAP_ENV__Detail(), and soap_putindependent().
soap_putindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap * soap)
Definition at line 284 of file soapC.cpp.
 {
     int i;
     struct soap_plist *pp;
     if (soap->version == 1 && soap->encodingStyle && !(soap->mode & (SOAP_XML_TREE | SOAP_XML_GRAPH)))
         for (i = 0; i < SOAP_PTRHASH; i++)
             for (pp = soap->pht[i]; pp; pp = pp->next)
                 if (pp->mark1 == 2 || pp->mark2 == 2)
                     if (soap_putelement(soap, pp->ptr, SOAP_MULTIREFTAG, pp->id, pp->type))
                         return soap->error;
     return SOAP_OK;
 }
References soap::encodingStyle, soap::error, soap_plist::id, soap_plist::mark1, soap_plist::mark2, soap::mode, soap_plist::next, soap::pht, soap_plist::ptr, SOAP_MULTIREFTAG, SOAP_OK, SOAP_PTRHASH, soap_putelement(), SOAP_XML_GRAPH, SOAP_XML_TREE, soap_plist::type, and soap::version.
Referenced by soap_put__QName(), soap_put_byte(), soap_put_int(), soap_put_ns1__executeCommand(), soap_put_ns1__executeCommandResponse(), soap_put_PointerToSOAP_ENV__Code(), soap_put_PointerToSOAP_ENV__Detail(), soap_put_PointerToSOAP_ENV__Reason(), soap_put_PointerTostring(), soap_put_SOAP_ENV__Code(), soap_put_SOAP_ENV__Detail(), soap_put_SOAP_ENV__Fault(), soap_put_SOAP_ENV__Header(), soap_put_SOAP_ENV__Reason(), and soap_put_string().
soap_read__QName()
int soap_read__QName (struct soap * soap, char ** p) inline
Definition at line 1014 of file soapH.h.
 {
     if (p)
     {   if (soap_begin_recv(soap) || ::soap_get__QName(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_end_recv(), soap_get__QName(), and SOAP_OK.
Referenced by soap_GET__QName(), and soap_POST_recv__QName().
soap_read_byte()
int soap_read_byte (struct soap * soap, char * p) inline
Definition at line 101 of file soapH.h.
 {
     if (p)
     {   if (soap_begin_recv(soap) || ::soap_get_byte(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_end_recv(), soap_get_byte(), and SOAP_OK.
Referenced by soap_GET_byte(), and soap_POST_recv_byte().
soap_read_int()
int soap_read_int (struct soap * soap, int * p) inline
Definition at line 178 of file soapH.h.
 {
     if (p)
     {   if (soap_begin_recv(soap) || ::soap_get_int(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_end_recv(), soap_get_int(), and SOAP_OK.
Referenced by soap_GET_int(), and soap_POST_recv_int().
soap_read_ns1__executeCommand()
int soap_read_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p) inline
Definition at line 785 of file soapH.h.
 {
     if (p)
     {   ::soap_default_ns1__executeCommand(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_ns1__executeCommand(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_ns1__executeCommand(), soap_end_recv(), soap_get_ns1__executeCommand(), and SOAP_OK.
Referenced by soap_GET_ns1__executeCommand(), and soap_POST_recv_ns1__executeCommand().
soap_read_ns1__executeCommandResponse()
int soap_read_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p) inline
Definition at line 879 of file soapH.h.
 {
     if (p)
     {   ::soap_default_ns1__executeCommandResponse(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_ns1__executeCommandResponse(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_ns1__executeCommandResponse(), soap_end_recv(), soap_get_ns1__executeCommandResponse(), and SOAP_OK.
Referenced by soap_GET_ns1__executeCommandResponse(), and soap_POST_recv_ns1__executeCommandResponse().
soap_read_SOAP_ENV__Code()
int soap_read_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p) inline
Definition at line 593 of file soapH.h.
 {
     if (p)
     {   ::soap_default_SOAP_ENV__Code(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Code(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_SOAP_ENV__Code(), soap_end_recv(), soap_get_SOAP_ENV__Code(), and SOAP_OK.
Referenced by soap_GET_SOAP_ENV__Code(), and soap_POST_recv_SOAP_ENV__Code().
soap_read_SOAP_ENV__Detail()
int soap_read_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p) inline
Definition at line 493 of file soapH.h.
 {
     if (p)
     {   ::soap_default_SOAP_ENV__Detail(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Detail(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_SOAP_ENV__Detail(), soap_end_recv(), soap_get_SOAP_ENV__Detail(), and SOAP_OK.
Referenced by soap_GET_SOAP_ENV__Detail(), and soap_POST_recv_SOAP_ENV__Detail().
soap_read_SOAP_ENV__Fault()
int soap_read_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p) inline
Definition at line 289 of file soapH.h.
 {
     if (p)
     {   ::soap_default_SOAP_ENV__Fault(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Fault(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_SOAP_ENV__Fault(), soap_end_recv(), soap_get_SOAP_ENV__Fault(), and SOAP_OK.
Referenced by soap_GET_SOAP_ENV__Fault(), and soap_POST_recv_SOAP_ENV__Fault().
soap_read_SOAP_ENV__Header()
int soap_read_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p) inline
Definition at line 689 of file soapH.h.
 {
     if (p)
     {   ::soap_default_SOAP_ENV__Header(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Header(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_SOAP_ENV__Header(), soap_end_recv(), soap_get_SOAP_ENV__Header(), and SOAP_OK.
Referenced by soap_GET_SOAP_ENV__Header(), and soap_POST_recv_SOAP_ENV__Header().
soap_read_SOAP_ENV__Reason()
int soap_read_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p) inline
Definition at line 387 of file soapH.h.
 {
     if (p)
     {   ::soap_default_SOAP_ENV__Reason(soap, p);
         if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Reason(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_default_SOAP_ENV__Reason(), soap_end_recv(), soap_get_SOAP_ENV__Reason(), and SOAP_OK.
Referenced by soap_GET_SOAP_ENV__Reason(), and soap_POST_recv_SOAP_ENV__Reason().
soap_read_string()
int soap_read_string (struct soap * soap, char ** p) inline
Definition at line 1100 of file soapH.h.
 {
     if (p)
     {   if (soap_begin_recv(soap) || ::soap_get_string(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, NULL, soap_begin_recv(), soap_end_recv(), soap_get_string(), and SOAP_OK.
Referenced by soap_GET_string(), and soap_POST_recv_string().
soap_serialize__QName()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap * soap, char *const * a)
Definition at line 1698 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     (void)soap_reference(soap, *a, SOAP_TYPE__QName);
 #endif
 }
References mpq::a, soap_reference(), and SOAP_TYPE__QName.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a)
Definition at line 1267 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_serialize_string(soap, (char*const*)&a->command);
 #endif
 }
References mpq::a, and soap_serialize_string().
Referenced by soap_markelement(), soap_PATCH_ns1__executeCommand(), soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_serialize_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a)
Definition at line 1370 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_serialize_PointerTostring(soap, &a->result);
 #endif
 }
References mpq::a, and soap_serialize_PointerTostring().
Referenced by soap_markelement(), soap_PATCH_ns1__executeCommandResponse(), soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_serialize_PointerToSOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a)
Definition at line 1585 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Code))
         soap_serialize_SOAP_ENV__Code(soap, *a);
 #endif
 }
References mpq::a, soap_reference(), soap_serialize_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a)
Definition at line 1527 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Detail))
         soap_serialize_SOAP_ENV__Detail(soap, *a);
 #endif
 }
References mpq::a, soap_reference(), soap_serialize_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a)
Definition at line 1469 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Reason))
         soap_serialize_SOAP_ENV__Reason(soap, *a);
 #endif
 }
References mpq::a, soap_reference(), soap_serialize_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerTostring()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap * soap, char **const * a)
Definition at line 1644 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     if (!soap_reference(soap, *a, SOAP_TYPE_string))
         soap_serialize_string(soap, *a);
 #endif
 }
References mpq::a, soap_reference(), soap_serialize_string(), and SOAP_TYPE_string.
Referenced by soap_markelement(), and soap_serialize_ns1__executeCommandResponse().
soap_serialize_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a)
Definition at line 1054 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_serialize__QName(soap, (char*const*)&a->SOAP_ENV__Value);
     soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Subcode);
 #endif
 }
References mpq::a, soap_serialize__QName(), and soap_serialize_PointerToSOAP_ENV__Code().
Referenced by soap_PATCH_SOAP_ENV__Code(), soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_serialize_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a)
Definition at line 937 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_markelement(soap, a->fault, a->__type);
 #endif
 }
References mpq::a, and soap_markelement().
Referenced by soap_PATCH_SOAP_ENV__Detail(), soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_serialize_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a)
Definition at line 637 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_serialize__QName(soap, (char*const*)&a->faultcode);
     soap_serialize_string(soap, (char*const*)&a->faultstring);
     soap_serialize_string(soap, (char*const*)&a->faultactor);
     soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->detail);
     soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
     soap_serialize_PointerToSOAP_ENV__Reason(soap, &a->SOAP_ENV__Reason);
     soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Node);
     soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Role);
     soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->SOAP_ENV__Detail);
 #endif
 }
References mpq::a, soap_serialize__QName(), soap_serialize_PointerToSOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_serialize_string().
Referenced by soap_PATCH_SOAP_ENV__Fault(), soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_serializefault(), and soap_write_SOAP_ENV__Fault().
soap_serialize_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a)
Definition at line 1172 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
 #endif
 }
References mpq::a.
Referenced by soap_PATCH_SOAP_ENV__Header(), soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), soap_serializeheader(), and soap_write_SOAP_ENV__Header().
soap_serialize_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a)
Definition at line 826 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     soap_serialize_string(soap, (char*const*)&a->SOAP_ENV__Text);
 #endif
 }
References mpq::a, and soap_serialize_string().
Referenced by soap_PATCH_SOAP_ENV__Reason(), soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_serialize_string()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap * soap, char *const * a)
Definition at line 1732 of file soapC.cpp.
 {
     (void)soap; (void)a; /* appease -Wall -Werror */
 #ifndef WITH_NOIDREF
     (void)soap_reference(soap, *a, SOAP_TYPE_string);
 #endif
 }
References mpq::a, soap_reference(), and SOAP_TYPE_string.
Referenced by soap_markelement(), soap_serialize_ns1__executeCommand(), soap_serialize_PointerTostring(), soap_serialize_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Reason().
soap_write__QName()
int soap_write__QName (struct soap * soap, char *const * p) inline
Definition at line 979 of file soapH.h.
 {
     soap_free_temp(soap);
     if (p)
     {   if (soap_begin_send(soap) || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, and soap_put__QName().
soap_write_byte()
int soap_write_byte (struct soap * soap, char const * p) inline
Definition at line 66 of file soapH.h.
 {
     soap_free_temp(soap);
     if (p)
     {   if (soap_begin_send(soap) || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, and soap_put_byte().
soap_write_int()
int soap_write_int (struct soap * soap, int const * p) inline
Definition at line 143 of file soapH.h.
 {
     soap_free_temp(soap);
     if (p)
     {   if (soap_begin_send(soap) || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, and soap_put_int().
soap_write_ns1__executeCommand()
int soap_write_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand const * p) inline
Definition at line 752 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_ns1__executeCommand(soap, p), 0) || ::soap_put_ns1__executeCommand(soap, p, "ns1:executeCommand", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_ns1__executeCommand(), and soap_serialize_ns1__executeCommand().
soap_write_ns1__executeCommandResponse()
int soap_write_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse const * p) inline
Definition at line 846 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_ns1__executeCommandResponse(soap, p), 0) || ::soap_put_ns1__executeCommandResponse(soap, p, "ns1:executeCommandResponse", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_ns1__executeCommandResponse(), and soap_serialize_ns1__executeCommandResponse().
soap_write_SOAP_ENV__Code()
int soap_write_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code const * p) inline
Definition at line 560 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Code().
soap_write_SOAP_ENV__Detail()
int soap_write_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail const * p) inline
Definition at line 460 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_SOAP_ENV__Detail(), and soap_serialize_SOAP_ENV__Detail().
soap_write_SOAP_ENV__Fault()
int soap_write_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault const * p) inline
Definition at line 256 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Fault().
soap_write_SOAP_ENV__Header()
int soap_write_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header const * p) inline
Definition at line 656 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_SOAP_ENV__Header(), and soap_serialize_SOAP_ENV__Header().
soap_write_SOAP_ENV__Reason()
int soap_write_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason const * p) inline
Definition at line 354 of file soapH.h.
 {
     soap_free_temp(soap);
     if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap))
             return soap->error;
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, soap_put_SOAP_ENV__Reason(), and soap_serialize_SOAP_ENV__Reason().
soap_write_string()
int soap_write_string (struct soap * soap, char *const * p) inline
Definition at line 1065 of file soapH.h.
 {
     soap_free_temp(soap);
     if (p)
     {   if (soap_begin_send(soap) || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap))
             return soap->error;
     }
     return SOAP_OK;
 }
References soap::error, soap_begin_send(), soap_end_send(), soap_free_temp(), SOAP_OK, and soap_put_string().