Azerotcore-wotlk: npc_weegli_blastfuse::npc_weegli_blastfuseAI Struct Reference
npc_weegli_blastfuse::npc_weegli_blastfuseAI Struct Reference
Public Member Functions
npc_weegli_blastfuseAI (Creature *creature)
void InitializeAI () override
void Reset () override
void AttackStart (Unit *victim) override
void UpdateAI (uint32 diff) override
void JustReachedHome () override
void MovementInform (uint32 type, uint32) override
void DestroyDoor ()
void sGossipSelect (Player *player, uint32, uint32 gossipListId) override
void sGossipHello (Player *player) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 Bomb_Timer
uint32 LandMine_Timer
uint32 outroTimer
uint8 outroStage
bool destroyingDoor
InstanceScript * instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 329 of file zulfarrak.cpp.
Constructor & Destructor Documentation
npc_weegli_blastfuseAI()
npc_weegli_blastfuse::npc_weegli_blastfuseAI::npc_weegli_blastfuseAI (Creature * creature) inline
Definition at line 331 of file zulfarrak.cpp.
                                                    : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             destroyingDoor = false;
             outroTimer = 2000;
             outroStage = 0;
         }
References destroyingDoor, WorldObject::GetInstanceScript(), instance, outroStage, and outroTimer.
Member Function Documentation
AttackStart()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 358 of file zulfarrak.cpp.
         {
             AttackStartCaster(victim, 10);//keep back & toss bombs/shoot
         }
References UnitAI::AttackStartCaster().
DestroyDoor()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor () inline
Definition at line 469 of file zulfarrak.cpp.
         {
             if (me->IsAlive())
             {
                 me->SetFaction(FACTION_FRIENDLY);
                 me->SetWalk(false);
                 me->GetMotionMaster()->MovePoint(0, { 1858.57f, 1146.35f, 14.745f, 3.85f });
                 me->SetHomePosition(1858.57f, 1146.35f, 14.745f, 3.85f);
                 Talk(SAY_WEEGLI_OK_I_GO);
                 instance->SetData(DATA_PYRAMID, PYRAMID_DESTROY_GATES);
                 if (Creature* sergeantBly = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BLY)))
                 {
                     sergeantBly->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 }
             }
         }
References DATA_PYRAMID, FACTION_FRIENDLY, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), instance, Unit::IsAlive(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_BLY, PYRAMID_DESTROY_GATES, SAY_WEEGLI_OK_I_GO, ZoneScript::SetData(), Unit::SetFaction(), Creature::SetHomePosition(), Creature::SetWalk(), CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by sGossipSelect().
InitializeAI()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 346 of file zulfarrak.cpp.
         {
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             Reset();
         }
References ScriptedAI::me, Reset(), Object::SetFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
JustReachedHome()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 428 of file zulfarrak.cpp.
         {
             if (instance->GetData(DATA_PYRAMID) == PYRAMID_CAGES_OPEN)
             {
                 instance->SetData(DATA_PYRAMID, PYRAMID_ARRIVED_AT_STAIR);
                 Talk(SAY_WEEGLI_OHNO);
             }
             else if (instance->GetData(DATA_PYRAMID) == PYRAMID_KILLED_ALL_TROLLS)
             {
                 instance->SetData(DATA_PYRAMID, PYRAMID_MOVED_DOWNSTAIRS);
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             }
             else if (instance->GetData(DATA_PYRAMID) == PYRAMID_DESTROY_GATES)
             {
                 destroyingDoor = true;
             }
         }
References DATA_PYRAMID, destroyingDoor, ZoneScript::GetData(), instance, ScriptedAI::me, PYRAMID_ARRIVED_AT_STAIR, PYRAMID_CAGES_OPEN, PYRAMID_DESTROY_GATES, PYRAMID_KILLED_ALL_TROLLS, PYRAMID_MOVED_DOWNSTAIRS, SAY_WEEGLI_OHNO, ZoneScript::SetData(), Object::SetFlag(), CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
MovementInform()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 446 of file zulfarrak.cpp.
         {
             if (type != POINT_MOTION_TYPE)
             {
                 return;
             }
             if (instance->GetData(DATA_PYRAMID) == PYRAMID_CAGES_OPEN)
             {
                 instance->SetData(DATA_PYRAMID, PYRAMID_ARRIVED_AT_STAIR);
                 Talk(SAY_WEEGLI_OHNO);
             }
             else if (instance->GetData(DATA_PYRAMID) == PYRAMID_KILLED_ALL_TROLLS)
             {
                 instance->SetData(DATA_PYRAMID, PYRAMID_MOVED_DOWNSTAIRS);
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             }
             else if (instance->GetData(DATA_PYRAMID) == PYRAMID_DESTROY_GATES)
             {
                 destroyingDoor = true;
             }
         }
References DATA_PYRAMID, destroyingDoor, ZoneScript::GetData(), instance, ScriptedAI::me, POINT_MOTION_TYPE, PYRAMID_ARRIVED_AT_STAIR, PYRAMID_CAGES_OPEN, PYRAMID_DESTROY_GATES, PYRAMID_KILLED_ALL_TROLLS, PYRAMID_MOVED_DOWNSTAIRS, SAY_WEEGLI_OHNO, ZoneScript::SetData(), Object::SetFlag(), CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Reset()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 352 of file zulfarrak.cpp.
         {
             Bomb_Timer     = 10000;
             LandMine_Timer = 30000;
         }
References Bomb_Timer, and LandMine_Timer.
Referenced by InitializeAI().
sGossipHello()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipHello (Player * player) inline override virtual
Reimplemented from UnitAI.
Definition at line 499 of file zulfarrak.cpp.
         {
             switch (instance->GetData(DATA_PYRAMID))
             {
                 case PYRAMID_MOVED_DOWNSTAIRS:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_WEEGLI, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                     SendGossipMenuFor(player, 1514, me->GetGUID());  //if event can proceed to end
                     break;
                 case PYRAMID_NOT_STARTED:
                     SendGossipMenuFor(player, 1511, me->GetGUID());  //if event not started
                     break;
                 default:
                     SendGossipMenuFor(player, 1513, me->GetGUID());  //if event are in progress
             }
         }
References AddGossipItemFor(), DATA_PYRAMID, ZoneScript::GetData(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, GOSSIP_WEEGLI, instance, ScriptedAI::me, PYRAMID_MOVED_DOWNSTAIRS, PYRAMID_NOT_STARTED, and SendGossipMenuFor().
sGossipSelect()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipSelect (Player * player, uint32 , uint32 gossipListId) inline override virtual
Reimplemented from UnitAI.
Definition at line 486 of file zulfarrak.cpp.
         {
             uint32 const action = player->PlayerTalkClass->GetGossipOptionAction(gossipListId);
             ClearGossipMenuFor(player);
             if (action == GOSSIP_ACTION_INFO_DEF + 1)
             {
                 CloseGossipMenuFor(player);
                 //here we make him run to door, set the charge and run away off to nowhere
                 DestroyDoor();
             }
         }
References ClearGossipMenuFor(), CloseGossipMenuFor(), DestroyDoor(), PlayerMenu::GetGossipOptionAction(), GOSSIP_ACTION_INFO_DEF, and Player::PlayerTalkClass.
UpdateAI()
void npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 363 of file zulfarrak.cpp.
         {
             if (!UpdateVictim())
             {
                 if (destroyingDoor)
                 {
                     if (outroTimer <= diff)
                     {
                         switch (outroStage)
{
                             case 0:
                                 DoCastSelf(SPELL_WEEGLIS_BARREL);
                                 outroTimer = 2000;
                                 ++outroStage;
                                 break;
                             case 1:
                                 me->GetMotionMaster()->MovePoint(2, 1871.18f, 1100.f, 8.88f);
                                 Talk(SAY_WEEGLI_OUT_OF_HERE);
                                 me->DespawnOrUnsummon(8000);
                                 instance->SetData(DATA_PYRAMID, PYRAMID_GATES_DESTROYED);
                                 destroyingDoor = false;
                                 break;
                         }
                     }
                     else
                     {
                         outroTimer -= diff;
                     }
                 }
                 return;
             }
             if (Bomb_Timer <= diff)
             {
                 DoCastVictim(SPELL_BOMB);
                 Bomb_Timer = 10000;
             }
             else
             {
                 Bomb_Timer -= diff;
             }
             if (LandMine_Timer <= diff)
             {
                 DoCastSelf(SPELL_GOBLIN_LAND_MINE);
                 LandMine_Timer = 30000;
             }
             else
             {
                 LandMine_Timer -= diff;
             }
             if (me->isAttackReady() && !me->IsWithinMeleeRange(me->GetVictim()))
             {
                 DoCastVictim(SPELL_SHOOT);
                 me->SetSheath(SHEATH_STATE_RANGED);
             }
             else
             {
                 me->SetSheath(SHEATH_STATE_MELEE);
                 DoMeleeAttackIfReady();
             }
         }
References Bomb_Timer, DATA_PYRAMID, Creature::DespawnOrUnsummon(), destroyingDoor, UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), Unit::GetMotionMaster(), Unit::GetVictim(), instance, Unit::isAttackReady(), Unit::IsWithinMeleeRange(), LandMine_Timer, ScriptedAI::me, MotionMaster::MovePoint(), outroStage, outroTimer, PYRAMID_GATES_DESTROYED, SAY_WEEGLI_OUT_OF_HERE, ZoneScript::SetData(), Unit::SetSheath(), SHEATH_STATE_MELEE, SHEATH_STATE_RANGED, SPELL_BOMB, SPELL_GOBLIN_LAND_MINE, SPELL_SHOOT, SPELL_WEEGLIS_BARREL, CreatureAI::Talk(), and CreatureAI::UpdateVictim().
Member Data Documentation
Bomb_Timer
uint32 npc_weegli_blastfuse::npc_weegli_blastfuseAI::Bomb_Timer
Definition at line 339 of file zulfarrak.cpp.
Referenced by Reset(), and UpdateAI().
destroyingDoor
bool npc_weegli_blastfuse::npc_weegli_blastfuseAI::destroyingDoor
Definition at line 343 of file zulfarrak.cpp.
Referenced by JustReachedHome(), MovementInform(), npc_weegli_blastfuseAI(), and UpdateAI().
instance
InstanceScript* npc_weegli_blastfuse::npc_weegli_blastfuseAI::instance
Definition at line 344 of file zulfarrak.cpp.
Referenced by DestroyDoor(), JustReachedHome(), MovementInform(), npc_weegli_blastfuseAI(), sGossipHello(), and UpdateAI().
LandMine_Timer
uint32 npc_weegli_blastfuse::npc_weegli_blastfuseAI::LandMine_Timer
Definition at line 340 of file zulfarrak.cpp.
Referenced by Reset(), and UpdateAI().
outroStage
uint8 npc_weegli_blastfuse::npc_weegli_blastfuseAI::outroStage
Definition at line 342 of file zulfarrak.cpp.
Referenced by npc_weegli_blastfuseAI(), and UpdateAI().
outroTimer
uint32 npc_weegli_blastfuse::npc_weegli_blastfuseAI::outroTimer
Definition at line 341 of file zulfarrak.cpp.
Referenced by npc_weegli_blastfuseAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp