Azerotcore-wotlk: Acore::WorldObjectSpellConeTargetCheck Struct Reference
Acore::WorldObjectSpellConeTargetCheck Struct Reference
#include <Spell.h>
Public Member Functions
WorldObjectSpellConeTargetCheck (float coneAngle, float range, Unit *caster, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellAreaTargetCheck
WorldObjectSpellAreaTargetCheck (float range, Position const *position, Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellTargetCheck
WorldObjectSpellTargetCheck (Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
~WorldObjectSpellTargetCheck ()
bool operator() (WorldObject *target)
Public Attributes
float _coneAngle
Public Attributes inherited from Acore::WorldObjectSpellAreaTargetCheck
float _range
Position const * _position
Public Attributes inherited from Acore::WorldObjectSpellTargetCheck
Unit * _caster
Unit * _referer
SpellInfo const * _spellInfo
SpellTargetCheckTypes _targetSelectionType
ConditionSourceInfo * _condSrcInfo
ConditionList * _condList
Detailed Description
Definition at line 807 of file Spell.h.
Constructor & Destructor Documentation
WorldObjectSpellConeTargetCheck()
Acore::WorldObjectSpellConeTargetCheck::WorldObjectSpellConeTargetCheck (float coneAngle, float range, Unit * caster, SpellInfo const * spellInfo, SpellTargetCheckTypes selectionType, ConditionList * condList)
Definition at line 8533 of file Spell.cpp.
         : WorldObjectSpellAreaTargetCheck(range, caster, caster, caster, spellInfo, selectionType, condList), _coneAngle(coneAngle)
     {
     }
Member Function Documentation
operator()()
bool Acore::WorldObjectSpellConeTargetCheck::operator() (WorldObject * target)
Definition at line 8539 of file Spell.cpp.
     {
         if (_spellInfo->HasAttribute(SPELL_ATTR0_CU_CONE_BACK))
         {
             if (!_caster->isInBack(target, _coneAngle))
                 return false;
         }
         else if (_spellInfo->HasAttribute(SPELL_ATTR0_CU_CONE_LINE))
         {
             if (!_caster->HasInLine(target, _caster->GetObjectSize()))
                 return false;
         }
         else
         {
             if (!_caster->isInFront(target, _coneAngle))
                 return false;
         }
         return WorldObjectSpellAreaTargetCheck::operator ()(target);
     }
References Acore::WorldObjectSpellTargetCheck::_caster, _coneAngle, Acore::WorldObjectSpellTargetCheck::_spellInfo, WorldObject::GetObjectSize(), SpellInfo::HasAttribute(), Position::HasInLine(), WorldObject::isInBack(), WorldObject::isInFront(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), SPELL_ATTR0_CU_CONE_BACK, and SPELL_ATTR0_CU_CONE_LINE.
Member Data Documentation
_coneAngle
float Acore::WorldObjectSpellConeTargetCheck::_coneAngle
Definition at line 809 of file Spell.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
src/server/game/Spells/Spell.h
src/server/game/Spells/Spell.cpp