Azerotcore-wotlk: src/common/Configuration/BuiltInConfig.cpp File Reference
BuiltInConfig.cpp File Reference
#include "BuiltInConfig.h"
#include "Config.h"
#include "GitRevision.h"
Functions
template<typename Fn >
static std::string GetStringWithDefaultValueFromFunction (std::string const &key, Fn getter)
Function Documentation
GetStringWithDefaultValueFromFunction()
template<typename Fn > static std::string GetStringWithDefaultValueFromFunction (std::string const & key, Fn getter) static
Definition at line 23 of file BuiltInConfig.cpp.
 {
     std::string const value = sConfigMgr->GetOption<std::string>(key, "");
     return value.empty() ? getter() : value;
 }
References sConfigMgr.
Referenced by BuiltInConfig::GetBuildDirectory(), BuiltInConfig::GetCMakeCommand(), BuiltInConfig::GetMySQLExecutable(), and BuiltInConfig::GetSourceDirectory().