Azerotcore-wotlk: deps/SFMT/SFMT-sse2-msc.h File Reference
SFMT-sse2-msc.h File Reference
SIMD oriented Fast Mersenne Twister(SFMT) for Intel SSE2 for MSC.
Macros
#define SFMT_SSE2_MSC_H
Functions
static void mm_recursion (__m128i *r, __m128i a, __m128i b, __m128i c, __m128i *d)
void sfmt_gen_rand_all (sfmt_t *sfmt)
static void gen_rand_array (sfmt_t *sfmt, w128_t *array, int size)
Detailed Description
SIMD oriented Fast Mersenne Twister(SFMT) for Intel SSE2 for MSC.
Author
Mutsuo Saito (Hiroshima University)
Makoto Matsumoto (Hiroshima University)
Note
We assume LITTLE ENDIAN in this file
Copyright (C) 2006, 2007 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. All rights reserved. Copyright (C) 2013 Mutsuo Saito, Makoto Matsumoto and Hiroshima University.
The new BSD License is applied to this software, see LICENSE.txt
Definition in file SFMT-sse2-msc.h.
Macro Definition Documentation
SFMT_SSE2_MSC_H
#define SFMT_SSE2_MSC_H
Definition at line 20 of file SFMT-sse2-msc.h.
Function Documentation
gen_rand_array()
static void gen_rand_array (sfmt_t * sfmt, w128_t * array, int size) static
This function fills the user-specified array with pseudorandom integers.
Parameters
sfmt SFMT internal state.
array an 128-bit array to be filled by pseudorandom numbers.
size number of 128-bit pseudorandom numbers to be generated.
Definition at line 282 of file SFMT-sse2-msc.h.
 {
     int i, j;
     __m128i r1, r2;
     w128_t * pstate = sfmt->state;
     r1 = pstate[SFMT_N - 2].si;
     r2 = pstate[SFMT_N - 1].si;
     for (i = 0; i < SFMT_N - SFMT_POS1; i++) {
         mm_recursion(&array[i].si, pstate[i].si,
                      pstate[i + SFMT_POS1].si, r1, &r2);
         r1 = r2;
         r2 = array[i].si;
     }
     for (; i < SFMT_N; i++) {
         mm_recursion(&array[i].si, pstate[i].si,
                      array[i + SFMT_POS1 - SFMT_N].si, r1, &r2);
         r1 = r2;
         r2 = array[i].si;
     }
     for (; i < size - SFMT_N; i++) {
         mm_recursion(&array[i].si, array[i - SFMT_N].si,
                      array[i + SFMT_POS1 - SFMT_N].si, r1, &r2);
         r1 = r2;
         r2 = array[i].si;
     }
     for (j = 0; j < 2 * SFMT_N - size; j++) {
         pstate[j] = array[j + size - SFMT_N];
     }
     for (; i < size; i++, j++) {
         mm_recursion(&array[i].si, array[i - SFMT_N].si,
                      array[i + SFMT_POS1 - SFMT_N].si, r1, &r2);
         r1 = r2;
         r2 = array[i].si;
         pstate[j] = array[i];
     }
 }
References array, mm_recursion(), SFMT_N, SFMT_POS1, and SFMT_T::state.
mm_recursion()
static void mm_recursion (__m128i * r, __m128i a, __m128i b, __m128i c, __m128i * d) inline static
This function represents the recursion formula.
Parameters
r an output
a a 128-bit part of the interal state array
b a 128-bit part of the interal state array
c a 128-bit part of the interal state array
d a 128-bit part of the interal state array
Definition at line 231 of file SFMT-sse2-msc.h.
 {
     __m128i v, x, y, z;
     y = _mm_srli_epi32(b, SFMT_SR1);
     z = _mm_srli_si128(c, SFMT_SR2);
     v = _mm_slli_epi32(*d, SFMT_SL1);
     z = _mm_xor_si128(z, a);
     z = _mm_xor_si128(z, v);
     x = _mm_slli_si128(a, SFMT_SL2);
     y = _mm_and_si128(y, sse2_param_mask.si);
     z = _mm_xor_si128(z, x);
     z = _mm_xor_si128(z, y);
     *r = z;
 }
References mpq::a, b, mpq::c, mpq::d, SFMT_SL1, SFMT_SL2, SFMT_SR1, SFMT_SR2, G3D::x, G3D::y, and G3D::z.
Referenced by gen_rand_array(), and sfmt_gen_rand_all().
sfmt_gen_rand_all()
void sfmt_gen_rand_all (sfmt_t * sfmt)
This function fills the internal state array with pseudorandom integers.
Parameters
sfmt SFMT internal state
Definition at line 253 of file SFMT-sse2-msc.h.
{
     int i;
     __m128i r1, r2;
     w128_t * pstate = sfmt->state;
     r1 = pstate[SFMT_N - 2].si;
     r2 = pstate[SFMT_N - 1].si;
     for (i = 0; i < SFMT_N - SFMT_POS1; i++) {
         mm_recursion(&pstate[i].si, pstate[i].si,
                      pstate[i + SFMT_POS1].si, r1, &r2);
         r1 = r2;
         r2 = pstate[i].si;
     }
     for (; i < SFMT_N; i++) {
         mm_recursion(&pstate[i].si, pstate[i].si,
                      pstate[i + SFMT_POS1 - SFMT_N].si,
                      r1, &r2);
         r1 = r2;
         r2 = pstate[i].si;
     }
 }
References mm_recursion(), SFMT_N, SFMT_POS1, and SFMT_T::state.