Azerotcore-wotlk: G3D::units Namespace Reference
G3D::units Namespace Reference
Functions
float nanometers ()
float micrometers ()
float millimeters ()
float centimeters ()
float meters ()
float kilometers ()
float inches ()
float feet ()
float yards ()
float miles ()
float radians ()
float degrees ()
float nanoseconds ()
float milliseconds ()
float seconds ()
float minutes ()
float hours ()
float days ()
float years ()
float kilograms ()
float newtons ()
float watts ()
float joules ()
float steradians ()
Detailed Description
Use using namespace G3D::units; to include all units into your program. The units system is specifically designed not to be general but to support commonly used units efficiently and clearly. See http://en.wikipedia.org/wiki/SI_prefix for interesting facts about SI/metric units and full definitions.
Function Documentation
centimeters()
float G3D::units::centimeters () inline
0.01 m
Definition at line 38 of file units.h.
{
     return 0.01f;
 }
days()
float G3D::units::days () inline
86400 s
Definition at line 112 of file units.h.
                     {
     return 86400.0f;
 }
Referenced by character_commandscript::HandleCharacterDeletedPurgeCommand(), my_system_gmt_sec(), and secsToTimeString().
degrees()
float G3D::units::degrees () inline
pi/180
Definition at line 80 of file units.h.
{
     return 0.0174532925f;
 }
Referenced by Utils::ToRadians().
feet()
float G3D::units::feet () inline
0.3048 m
Definition at line 58 of file units.h.
                     {
     return 0.3048f;
 }
hours()
float G3D::units::hours () inline
3600 s
Definition at line 107 of file units.h.
                      {
     return 3600.0f;
 }
Referenced by secsToTimeString().
inches()
float G3D::units::inches () inline
0.0254 m
Definition at line 53 of file units.h.
                       {
     return 0.0254f;
 }
joules()
float G3D::units::joules () inline
SI unit of energy: J = N*m
Definition at line 143 of file units.h.
                       {
     return 1.0;
 }
kilograms()
float G3D::units::kilograms () inline
SI unit of mass
Definition at line 124 of file units.h.
{
     return 1.0f;
 }
kilometers()
float G3D::units::kilometers () inline
1000 m
Definition at line 48 of file units.h.
{
     return 1000.0f;
 }
meters()
float G3D::units::meters () inline
SI base unit of distance measure.
Definition at line 43 of file units.h.
                       {
     return 1.0f;
 }
micrometers()
float G3D::units::micrometers () inline
1e-6 m
Definition at line 28 of file units.h.
{
     return 1e-6f;
 }
miles()
float G3D::units::miles () inline
1609.344 m
Definition at line 68 of file units.h.
                      {
     return 1609.344f;
 }
millimeters()
float G3D::units::millimeters () inline
0.001 m
Definition at line 33 of file units.h.
{
     return 0.001f;
 }
milliseconds()
float G3D::units::milliseconds () inline
1e-3 s
Definition at line 92 of file units.h.
{
     return 1e-3f;
 }
Referenced by MMAP::MapBuilder::buildAllMaps(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_second(), TaskScheduler::RandomDurationBetween(), NetworkThread< SocketType >::Run(), G3D::System::sleep(), Acore::Thread::Sleep(), NetworkThread< SocketType >::Update(), and TaskScheduler::Update().
minutes()
float G3D::units::minutes () inline
60 s
Definition at line 102 of file units.h.
{
     return 60.0f;
 }
Referenced by WorldSession::HandleMessagechatOpcode(), AchievementGlobalMgr::IsRealmCompleted(), KeepDatabaseAliveHandler(), main(), and secsToTimeString().
nanometers()
float G3D::units::nanometers () inline
1e-9 m
Definition at line 23 of file units.h.
{
     return 1e-9f;
 }
nanoseconds()
float G3D::units::nanoseconds () inline
1e-9 s
Definition at line 87 of file units.h.
{
     return 1e-9f;
 }
newtons()
float G3D::units::newtons () inline
1 kg m / s^2
Definition at line 131 of file units.h.
{
     return 1.0f;
 }
radians()
float G3D::units::radians () inline
SI base unit of angular measure.
Definition at line 75 of file units.h.
{
     return 1.0f;
 }
seconds()
float G3D::units::seconds () inline
Base unit of time
Definition at line 97 of file units.h.
{
     return 1.0;
 }
Referenced by MySQLConnection::_HandleMySQLErrno(), BanExpiryHandler(), ContinentBuilder::Build(), Acore::Fatal(), get_milliseconds(), WorldSocket::HandlePing(), FreezeDetector::Handler(), QueryCallback::InvokeIfReady(), SQLQueryHolderCallback::InvokeIfReady(), TransactionCallback::InvokeIfReady(), main(), my_init_time(), Metric::ScheduleOverallStatusLog(), Metric::ScheduleSend(), FreezeDetector::Start(), and RealmList::UpdateRealms().
steradians()
float G3D::units::steradians () inline
Unit of solid angle measure. A sphere subtends 4 * pi sr.
Definition at line 148 of file units.h.
{
     return 1.0;
 }
watts()
float G3D::units::watts () inline
SI unit of power: W = J/s
Definition at line 138 of file units.h.
                      {
     return 1.0;
 }
yards()
float G3D::units::yards () inline
0.9144 m
Definition at line 63 of file units.h.
                      {
     return 0.9144f;
 }
years()
float G3D::units::years () inline
31556926 s
Definition at line 117 of file units.h.
                      {
     return 31556926.0f;
 }