Azerotcore-wotlk: G3D::Vector2 Class Reference
G3D::Vector2 Class Reference
#include <Vector2.h>
Public Member Functions
Vector2 (const Any &any)
Any toAny () const
Vector2 ()
Vector2 (class TextInput &t)
Vector2 (class BinaryInput &b)
Vector2 (float x, float y)
Vector2 (float coordinate[2])
Vector2 (double coordinate[2])
Vector2 (const Vector2 &other)
Vector2 (const Vector2int16 &other)
Vector2 (const Vector2unorm16 &other)
Vector2 (const Vector2int32 &other)
Vector2 & operator= (const Any &a)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
void serialize (class TextOutput &t) const
void deserialize (class TextInput &t)
float & operator[] (int i)
const float & operator[] (int i) const
Vector2 & operator= (const Vector2 &other)
bool operator== (const Vector2 &other) const
bool operator!= (const Vector2 &other) const
size_t hashCode () const
bool fuzzyEq (const Vector2 &other) const
bool fuzzyNe (const Vector2 &other) const
bool isFinite () const
bool isNaN () const
bool isZero () const
bool isUnit () const
Vector2 operator+ (const Vector2 &v) const
Vector2 operator- (const Vector2 &v) const
Vector2 operator* (float s) const
Vector2 pow (float p) const
Vector2 operator* (const Vector2 &v) const
Vector2 operator/ (const Vector2 &v) const
Vector2 operator/ (float s) const
Vector2 operator- () const
float sum () const
Vector2 lerp (const Vector2 &v, float alpha) const
Vector2 clamp (const Vector2 &low, const Vector2 &high) const
Vector2 clamp (float low, float high) const
Vector2 & operator+= (const Vector2 &)
Vector2 & operator-= (const Vector2 &)
Vector2 & operator*= (float)
Vector2 & operator/= (float)
Vector2 & operator*= (const Vector2 &)
Vector2 & operator/= (const Vector2 &)
float length () const
Vector2 direction () const
Vector2 directionOrZero () const
Vector2 fastDirection () const
float squaredLength () const
float dot (const Vector2 &s) const
Vector2 abs () const
Vector2 min (const Vector2 &v) const
Vector2 max (const Vector2 &v) const
Vector2 maxAbs (const Vector2 &v) const
Vector2 minAbs (const Vector2 &v) const
std::string toString () const
Vector2 xx () const
Vector2 yx () const
Vector2 xy () const
Vector2 yy () const
Vector3 xxx () const
Vector3 yxx () const
Vector3 xyx () const
Vector3 yyx () const
Vector3 xxy () const
Vector3 yxy () const
Vector3 xyy () const
Vector3 yyy () const
Vector4 xxxx () const
Vector4 yxxx () const
Vector4 xyxx () const
Vector4 yyxx () const
Vector4 xxyx () const
Vector4 yxyx () const
Vector4 xyyx () const
Vector4 yyyx () const
Vector4 xxxy () const
Vector4 yxxy () const
Vector4 xyxy () const
Vector4 yyxy () const
Vector4 xxyy () const
Vector4 yxyy () const
Vector4 xyyy () const
Vector4 yyyy () const
Static Public Member Functions
static Vector2 random (Random &r=Random::common())
static const Vector2 & zero ()
static const Vector2 & one ()
static const Vector2 & unitX ()
static const Vector2 & unitY ()
static const Vector2 & inf ()
static const Vector2 & nan ()
static const Vector2 & minFinite ()
static const Vector2 & maxFinite ()
Public Attributes
float x
float y
Private Member Functions
bool operator< (const Vector2 &) const
bool operator> (const Vector2 &) const
bool operator<= (const Vector2 &) const
bool operator>= (const Vector2 &) const
Detailed Description
Do not subclass– this implementation makes assumptions about the memory layout.
Definition at line 40 of file Vector2.h.
Constructor & Destructor Documentation
Vector2() [1/11]
G3D::Vector2::Vector2 (const Any & any)
Parameters
any Must either Vector2(#, #) or Vector2 {x = #, y = #}
Definition at line 33 of file Vector2.cpp.
{
     any.verifyName("Vector2", "Point2");
     any.verifyType(Any::TABLE, Any::ARRAY);
     any.verifySize(2);
     if (any.type() == Any::ARRAY) {
         x = any[0];
         y = any[1];
     } else {
         // Table
         x = any["x"];
         y = any["y"];
     }
 }
References G3D::any(), G3D::Any::ARRAY, G3D::Any::TABLE, x, and y.
Vector2() [2/11]
G3D::Vector2::Vector2 () inline
Creates the zero vector
Definition at line 282 of file Vector2.h.
                          : x(0.0f), y(0.0f) {
 }
Referenced by abs(), clamp(), max(), maxAbs(), min(), minAbs(), operator*(), operator+(), operator-(), operator/(), operator=(), pow(), random(), xx(), xy(), yx(), and yy().
Vector2() [3/11]
G3D::Vector2::Vector2 (class TextInput & t)
Vector2() [4/11]
G3D::Vector2::Vector2 (class BinaryInput & b)
Definition at line 114 of file Vector2.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Vector2() [5/11]
G3D::Vector2::Vector2 (float x, float y) inline
Definition at line 286 of file Vector2.h.
                                           : x(_x), y(_y) {
 }
Vector2() [6/11]
G3D::Vector2::Vector2 (float coordinate[2]) inline
Definition at line 290 of file Vector2.h.
{
     x = afCoordinate[0];
     y = afCoordinate[1];
 }
References x, and y.
Vector2() [7/11]
G3D::Vector2::Vector2 (double coordinate[2]) inline
Definition at line 297 of file Vector2.h.
{
     x = (float)afCoordinate[0];
     y = (float)afCoordinate[1];
 }
References x, and y.
Vector2() [8/11]
G3D::Vector2::Vector2 (const Vector2 & other) inline
Definition at line 303 of file Vector2.h.
{
     x = rkVector.x;
     y = rkVector.y;
 }
References x, and y.
Vector2() [9/11]
G3D::Vector2::Vector2 (const Vector2int16 & other) inline
Definition at line 309 of file Vector2.h.
                                               : x(v.x), y(v.y) {
 }
Vector2() [10/11]
G3D::Vector2::Vector2 (const Vector2unorm16 & other) inline
Definition at line 311 of file Vector2.h.
                                                 : x(float(v.x)), y(float(v.y)) {
 }
Vector2() [11/11]
G3D::Vector2::Vector2 (const Vector2int32 & other) explicit
Definition at line 29 of file Vector2.cpp.
                                           : x((float)other.x), y((float)other.y) {
 }
Member Function Documentation
abs()
Vector2 G3D::Vector2::abs () const inline
Componentwise absolute value
Definition at line 184 of file Vector2.h.
{
         return Vector2(fabs(x), fabs(y));
     }
References Vector2(), x, and y.
clamp() [1/2]
Vector2 G3D::Vector2::clamp (const Vector2 & low, const Vector2 & high) const inline
Definition at line 137 of file Vector2.h.
{
         return Vector2(
             G3D::clamp(x, low.x, high.x),
             G3D::clamp(y, low.y, high.y));
     }
References G3D::clamp(), Vector2(), x, and y.
Referenced by G3D::clamp().
clamp() [2/2]
Vector2 G3D::Vector2::clamp (float low, float high) const inline
Definition at line 143 of file Vector2.h.
{
         return Vector2(
             (float)G3D::clamp(x, low, high),
             (float)G3D::clamp(y, low, high));
     }
References G3D::clamp(), Vector2(), x, and y.
deserialize() [1/2]
void G3D::Vector2::deserialize (class BinaryInput & b)
Definition at line 119 of file Vector2.cpp.
{
     x = b.readFloat32();
     y = b.readFloat32();
 }
References b, x, and y.
Referenced by G3D::Rect2D::deserialize(), G3D::GCamera::deserialize(), G3D::deserialize(), and Vector2().
deserialize() [2/2]
void G3D::Vector2::deserialize (class TextInput & t)
Definition at line 131 of file Vector2.cpp.
{
     t.readSymbol("(");
     x = (float)t.readNumber();
     t.readSymbol(",");
     y = (float)t.readNumber();
     t.readSymbol(")");
 }
References G3D::TextInput::readNumber(), G3D::TextInput::readSymbol(), x, and y.
direction()
Vector2 G3D::Vector2::direction () const inline
Returns a unit-length version of this vector. Returns nan if length is almost zero.
Definition at line 424 of file Vector2.h.
{
     float lenSquared = x * x + y * y;
     if (lenSquared != 1.0f) {
         return *this / sqrtf(lenSquared);
     } else {
         return *this;
     }
 }
References x, and y.
Referenced by fastDirection().
directionOrZero()
Vector2 G3D::Vector2::directionOrZero () const inline
Returns Vector2::zero() is magnitude is almost zero, otherwise returns unit-length vector.
Definition at line 434 of file Vector2.h.
{
     float mag = length();
     if (mag < 0.0000001f) {
         return Vector2::zero();
     } else if (mag < 1.00001f && mag > 0.99999f) {
         return *this;
     } else {
         return *this * (1.0f / mag);
     }
 }
References length(), and zero().
dot()
float G3D::Vector2::dot (const Vector2 & s) const inline
Definition at line 446 of file Vector2.h.
{
     return x*rkVector.x + y*rkVector.y;
 }
References x, and y.
Referenced by G3D::LineSegment2D::closestPoint(), G3D::Box2D::computeAxes(), G3D::Box2D::contains(), and G3D::Box2D::overlaps1Way().
fastDirection()
Vector2 G3D::Vector2::fastDirection () const inline
Potentially less accurate but faster than direction(). Only works if System::hasSSE is true.
Definition at line 176 of file Vector2.h.
{
         return direction();
     }
References direction().
fuzzyEq()
bool G3D::Vector2::fuzzyEq (const Vector2 & other) const inline
Definition at line 464 of file Vector2.h.
{
     return G3D::fuzzyEq((*this - other).squaredLength(), 0);
 }
References G3D::fuzzyEq(), and squaredLength().
fuzzyNe()
bool G3D::Vector2::fuzzyNe (const Vector2 & other) const inline
Definition at line 470 of file Vector2.h.
{
     return G3D::fuzzyNe((*this - other).squaredLength(), 0);
 }
References G3D::fuzzyNe(), and squaredLength().
hashCode()
size_t G3D::Vector2::hashCode () const
Definition at line 106 of file Vector2.cpp.
{
     unsigned int xhash = (*(int*)(void*)(&x));
     unsigned int yhash = (*(int*)(void*)(&y));
     return xhash + (yhash * 37);
 }
References x, and y.
Referenced by HashTrait< G3D::Vector2 >::hashCode().
inf()
const Vector2 & G3D::Vector2::inf () static
Definition at line 82 of file Vector2.cpp.
{
     static Vector2 v(G3D::finf(), G3D::finf());
     return v;
 }
References G3D::finf().
Referenced by G3D::Rect2D::inf(), and G3D::LineSegment2D::intersection().
isFinite()
bool G3D::Vector2::isFinite () const inline
Returns true if this vector has finite length
Definition at line 476 of file Vector2.h.
{
     return G3D::isFinite(x) && G3D::isFinite(y);
 }
References G3D::isFinite(), x, and y.
Referenced by G3D::Rect2D::isFinite().
isNaN()
bool G3D::Vector2::isNaN () const inline
True if any field is NaN
Definition at line 95 of file Vector2.h.
{
         return G3D::isNaN(x) || G3D::isNaN(y);
     }
References G3D::isNaN(), x, and y.
Referenced by G3D::Rect2D::isEmpty().
isUnit()
bool G3D::Vector2::isUnit () const inline
Returns true if this vector has length == 1
Definition at line 488 of file Vector2.h.
{
     return G3D::fuzzyEq(squaredLength(), 1.0f);
 }
References G3D::fuzzyEq(), and squaredLength().
isZero()
bool G3D::Vector2::isZero () const inline
Returns true if this vector has length == 0
Definition at line 482 of file Vector2.h.
{
     return G3D::fuzzyEq(fabsf(x) + fabsf(y), 0.0f);
 }
References G3D::fuzzyEq(), x, and y.
length()
float G3D::Vector2::length () const inline
Magnitude of the vector
Definition at line 419 of file Vector2.h.
{
     return sqrtf(x*x + y*y);
 }
References x, and y.
Referenced by directionOrZero(), G3D::LineSegment2D::fromTwoPoints(), G3D::length(), and G3D::normalize().
lerp()
Vector2 G3D::Vector2::lerp (const Vector2 & v, float alpha) const inline
Linear interpolation
Definition at line 133 of file Vector2.h.
{
         return (*this) + (v - *this) * alpha;
     }
Referenced by G3D::Rect2D::clipSide2D(), G3D::Rect2D::lerp(), and G3D::lerp().
max()
Vector2 G3D::Vector2::max (const Vector2 & v) const inline
Component-wise maximum
Definition at line 458 of file Vector2.h.
{
     return Vector2(G3D::max(v.x, x), G3D::max(v.y, y));
 }
References G3D::max(), Vector2(), x, and y.
Referenced by G3D::Rect2D::intersect(), G3D::max(), G3D::Rect2D::merge(), and G3D::Rect2D::xyxy().
maxAbs()
Vector2 G3D::Vector2::maxAbs (const Vector2 & v) const inline
Component-wise argmax(abs(), v.abs()).
For the larger magnitude vector, simply use (a.squaredMagnitude() > b.squaredMagnitude) ? a : b.
See also
max
Definition at line 199 of file Vector2.h.
{
         return Vector2(::fabsf(x) > ::fabsf(v.x) ? x : v.x, ::fabsf(y) > ::fabsf(v.y) ? y : v.y);
     }
References Vector2(), x, and y.
maxFinite()
const Vector2 & G3D::Vector2::maxFinite () static
Largest representable vector
Definition at line 100 of file Vector2.cpp.
{
     static Vector2 v(FLT_MAX, FLT_MAX);
     return v;
 }
References FLT_MAX.
min()
Vector2 G3D::Vector2::min (const Vector2 & v) const inline
Component-wise minimum
Definition at line 452 of file Vector2.h.
{
     return Vector2(G3D::min(v.x, x), G3D::min(v.y, y));
 }
References G3D::min(), Vector2(), x, and y.
Referenced by G3D::Rect2D::intersect(), G3D::Rect2D::merge(), G3D::min(), and G3D::Rect2D::xyxy().
minAbs()
Vector2 G3D::Vector2::minAbs (const Vector2 & v) const inline
Component-wise argmin(abs(), v.abs()).
For the smaller magnitude vector, simply use (a.squaredMagnitude() < b.squaredMagnitude) ? a : b.
See also
max
Definition at line 208 of file Vector2.h.
{
         return Vector2(::fabsf(x) < ::fabsf(v.x) ? x : v.x, ::fabsf(y) < ::fabsf(v.y) ? y : v.y);
     }
References Vector2(), x, and y.
minFinite()
const Vector2 & G3D::Vector2::minFinite () static
smallest (most negative) representable vector
Definition at line 94 of file Vector2.cpp.
{
     static Vector2 v(-FLT_MAX, -FLT_MAX);
     return v;
 }
References FLT_MAX.
nan()
const Vector2 & G3D::Vector2::nan () static
Definition at line 88 of file Vector2.cpp.
{
     static Vector2 v(G3D::fnan(), G3D::fnan());
     return v;
 }
References G3D::fnan().
one()
const Vector2 & G3D::Vector2::one () static
Definition at line 62 of file Vector2.cpp.
{
     static const Vector2 v(1, 1); return v;
 }
operator!=()
bool G3D::Vector2::operator!= (const Vector2 & other) const inline
Definition at line 336 of file Vector2.h.
{
     return ( x != rkVector.x || y != rkVector.y);
 }
References x, and y.
operator*() [1/2]
Vector2 G3D::Vector2::operator* (const Vector2 & v) const inline
Array (pointwise) multiplication
Definition at line 403 of file Vector2.h.
{
     return Vector2(x * rkVector.x, y * rkVector.y);
 }
References Vector2(), x, and y.
operator*() [2/2]
Vector2 G3D::Vector2::operator* (float s) const inline
Definition at line 351 of file Vector2.h.
{
     return Vector2(fScalar*x, fScalar*y);
 }
References Vector2(), x, and y.
operator*=() [1/2]
Vector2 & G3D::Vector2::operator*= (const Vector2 & rkVector) inline
Definition at line 388 of file Vector2.h.
{
     x *= rkVector.x;
     y *= rkVector.y;
     return *this;
 }
References x, and y.
operator*=() [2/2]
Vector2 & G3D::Vector2::operator*= (float fScalar) inline
Definition at line 379 of file Vector2.h.
{
     x *= fScalar;
     y *= fScalar;
     return *this;
 }
References x, and y.
operator+()
Vector2 G3D::Vector2::operator+ (const Vector2 & v) const inline
Definition at line 341 of file Vector2.h.
{
     return Vector2(x + rkVector.x, y + rkVector.y);
 }
References Vector2(), x, and y.
operator+=()
Vector2 & G3D::Vector2::operator+= (const Vector2 & rkVector) inline
Definition at line 363 of file Vector2.h.
{
     x += rkVector.x;
     y += rkVector.y;
     return *this;
 }
References x, and y.
operator-() [1/2]
Vector2 G3D::Vector2::operator- () const inline
Unary minus
Definition at line 357 of file Vector2.h.
{
     return Vector2( -x, -y);
 }
References Vector2(), x, and y.
operator-() [2/2]
Vector2 G3D::Vector2::operator- (const Vector2 & v) const inline
Definition at line 346 of file Vector2.h.
{
     return Vector2(x - rkVector.x, y - rkVector.y);
 }
References Vector2(), x, and y.
operator-=()
Vector2 & G3D::Vector2::operator-= (const Vector2 & rkVector) inline
Definition at line 371 of file Vector2.h.
{
     x -= rkVector.x;
     y -= rkVector.y;
     return *this;
 }
References x, and y.
operator/() [1/2]
Vector2 G3D::Vector2::operator/ (const Vector2 & v) const inline
Array division
Definition at line 409 of file Vector2.h.
{
     return Vector2(x / rkVector.x, y / rkVector.y);
 }
References Vector2(), x, and y.
operator/() [2/2]
Vector2 G3D::Vector2::operator/ (float s) const
Definition at line 162 of file Vector2.cpp.
{
     return *this * (1.0f / k);
 }
operator/=() [1/2]
Vector2 & G3D::Vector2::operator/= (const Vector2 & rkVector) inline
Definition at line 396 of file Vector2.h.
{
     x /= rkVector.x;
     y /= rkVector.y;
     return *this;
 }
References x, and y.
operator/=() [2/2]
Vector2 & G3D::Vector2::operator/= (float k)
Definition at line 166 of file Vector2.cpp.
{
     this->x /= k;
     this->y /= k;
     return *this;
 }
References x, and y.
operator<()
bool G3D::Vector2::operator< (const Vector2 &) const private
operator<=()
bool G3D::Vector2::operator<= (const Vector2 &) const private
operator=() [1/2]
Vector2 & G3D::Vector2::operator= (const Any & a)
Definition at line 49 of file Vector2.cpp.
{
     *this = Vector2(a);
     return *this;
 }
References mpq::a, and Vector2().
operator=() [2/2]
Vector2 & G3D::Vector2::operator= (const Vector2 & other) inline
Definition at line 324 of file Vector2.h.
{
     x = rkVector.x;
     y = rkVector.y;
     return *this;
 }
References x, and y.
operator==()
bool G3D::Vector2::operator== (const Vector2 & other) const inline
Definition at line 331 of file Vector2.h.
{
     return ( x == rkVector.x && y == rkVector.y);
 }
References x, and y.
operator>()
bool G3D::Vector2::operator> (const Vector2 &) const private
operator>=()
bool G3D::Vector2::operator>= (const Vector2 &) const private
operator[]() [1/2]
float & G3D::Vector2::operator[] (int i) inline
Definition at line 314 of file Vector2.h.
{
     return ((float*)this)[i];
 }
operator[]() [2/2]
const float & G3D::Vector2::operator[] (int i) const inline
Definition at line 319 of file Vector2.h.
{
     return ((float*)this)[i];
 }
pow()
Vector2 G3D::Vector2::pow (float p) const inline
Raise each component of this vector to a power
Definition at line 111 of file Vector2.h.
{
         return Vector2(powf(x, p), powf(y, p));
     }
References Vector2(), x, and y.
random()
Vector2 G3D::Vector2::random (G3D::Random & r = Random::common()) static
Uniformly distributed random vector on the unit sphere
Definition at line 150 of file Vector2.cpp.
{
     Vector2 result;
     do {
         result = Vector2(r.uniform(-1, 1), r.uniform(-1, 1));
     } while (result.squaredLength() >= 1.0f);
     return result.direction();
 }
References G3D::Random::uniform(), and Vector2().
serialize() [1/2]
void G3D::Vector2::serialize (class BinaryOutput & b) const
Definition at line 125 of file Vector2.cpp.
{
     b.writeFloat32(x);
     b.writeFloat32(y);
 }
References b, x, and y.
Referenced by G3D::Rect2D::serialize(), G3D::GCamera::serialize(), and G3D::serialize().
serialize() [2/2]
void G3D::Vector2::serialize (class TextOutput & t) const
Definition at line 140 of file Vector2.cpp.
{
    t.writeSymbol("(");
    t.writeNumber(x);
    t.writeSymbol(",");
    t.writeNumber(y);
    t.writeSymbol(")");
 }
References G3D::TextOutput::writeNumber(), G3D::TextOutput::writeSymbol(), x, and y.
squaredLength()
float G3D::Vector2::squaredLength () const inline
Definition at line 414 of file Vector2.h.
{
     return x*x + y*y;
 }
References x, and y.
Referenced by G3D::Box2D::computeAxes(), fuzzyEq(), fuzzyNe(), and isUnit().
sum()
float G3D::Vector2::sum () const inline
x + y
Definition at line 126 of file Vector2.h.
{
         return x + y;
     }
References x, and y.
toAny()
Any G3D::Vector2::toAny () const
Converts the Vector2 to an Any.
Definition at line 55 of file Vector2.cpp.
{
     Any any(Any::ARRAY, "Vector2");
     any.append(x, y);
     return any;
 }
References G3D::any(), G3D::Any::ARRAY, x, and y.
toString()
std::string G3D::Vector2::toString () const
Definition at line 175 of file Vector2.cpp.
{
     return G3D::format("(%g, %g)", x, y);
 }
References G3D::format(), x, and y.
unitX()
const Vector2 & G3D::Vector2::unitX () static
Definition at line 72 of file Vector2.cpp.
{
     static Vector2 v(1, 0);
     return v;
 }
unitY()
const Vector2 & G3D::Vector2::unitY () static
Definition at line 77 of file Vector2.cpp.
{
     static Vector2 v(0, 1);
     return v;
 }
xx()
Vector2 G3D::Vector2::xx () const
Definition at line 181 of file Vector2.cpp.
 { return Vector2       (x, x); }
References Vector2(), and x.
xxx()
Vector3 G3D::Vector2::xxx () const
Definition at line 188 of file Vector2.cpp.
 { return Vector3       (x, x, x); }
References x.
xxxx()
Vector4 G3D::Vector2::xxxx () const
Definition at line 199 of file Vector2.cpp.
 { return Vector4       (x, x, x, x); }
References x.
xxxy()
Vector4 G3D::Vector2::xxxy () const
Definition at line 207 of file Vector2.cpp.
 { return Vector4       (x, x, x, y); }
References x, and y.
xxy()
Vector3 G3D::Vector2::xxy () const
Definition at line 192 of file Vector2.cpp.
 { return Vector3       (x, x, y); }
References x, and y.
xxyx()
Vector4 G3D::Vector2::xxyx () const
Definition at line 203 of file Vector2.cpp.
 { return Vector4       (x, x, y, x); }
References x, and y.
xxyy()
Vector4 G3D::Vector2::xxyy () const
Definition at line 211 of file Vector2.cpp.
 { return Vector4       (x, x, y, y); }
References x, and y.
xy()
Vector2 G3D::Vector2::xy () const
Definition at line 183 of file Vector2.cpp.
 { return Vector2       (x, y); }
References Vector2(), x, and y.
Referenced by G3D::Box2D::Box2D().
xyx()
Vector3 G3D::Vector2::xyx () const
Definition at line 190 of file Vector2.cpp.
 { return Vector3       (x, y, x); }
References x, and y.
xyxx()
Vector4 G3D::Vector2::xyxx () const
Definition at line 201 of file Vector2.cpp.
 { return Vector4       (x, y, x, x); }
References x, and y.
xyxy()
Vector4 G3D::Vector2::xyxy () const
Definition at line 209 of file Vector2.cpp.
 { return Vector4       (x, y, x, y); }
References x, and y.
xyy()
Vector3 G3D::Vector2::xyy () const
Definition at line 194 of file Vector2.cpp.
 { return Vector3       (x, y, y); }
References x, and y.
xyyx()
Vector4 G3D::Vector2::xyyx () const
Definition at line 205 of file Vector2.cpp.
 { return Vector4       (x, y, y, x); }
References x, and y.
xyyy()
Vector4 G3D::Vector2::xyyy () const
Definition at line 213 of file Vector2.cpp.
 { return Vector4       (x, y, y, y); }
References x, and y.
yx()
Vector2 G3D::Vector2::yx () const
Definition at line 182 of file Vector2.cpp.
 { return Vector2       (y, x); }
References Vector2(), x, and y.
Referenced by G3D::LineSegment2D::intersection().
yxx()
Vector3 G3D::Vector2::yxx () const
Definition at line 189 of file Vector2.cpp.
 { return Vector3       (y, x, x); }
References x, and y.
yxxx()
Vector4 G3D::Vector2::yxxx () const
Definition at line 200 of file Vector2.cpp.
 { return Vector4       (y, x, x, x); }
References x, and y.
yxxy()
Vector4 G3D::Vector2::yxxy () const
Definition at line 208 of file Vector2.cpp.
 { return Vector4       (y, x, x, y); }
References x, and y.
yxy()
Vector3 G3D::Vector2::yxy () const
Definition at line 193 of file Vector2.cpp.
 { return Vector3       (y, x, y); }
References x, and y.
yxyx()
Vector4 G3D::Vector2::yxyx () const
Definition at line 204 of file Vector2.cpp.
 { return Vector4       (y, x, y, x); }
References x, and y.
yxyy()
Vector4 G3D::Vector2::yxyy () const
Definition at line 212 of file Vector2.cpp.
 { return Vector4       (y, x, y, y); }
References x, and y.
yy()
Vector2 G3D::Vector2::yy () const
Definition at line 184 of file Vector2.cpp.
 { return Vector2       (y, y); }
References Vector2(), and y.
yyx()
Vector3 G3D::Vector2::yyx () const
Definition at line 191 of file Vector2.cpp.
 { return Vector3       (y, y, x); }
References x, and y.
yyxx()
Vector4 G3D::Vector2::yyxx () const
Definition at line 202 of file Vector2.cpp.
 { return Vector4       (y, y, x, x); }
References x, and y.
yyxy()
Vector4 G3D::Vector2::yyxy () const
Definition at line 210 of file Vector2.cpp.
 { return Vector4       (y, y, x, y); }
References x, and y.
yyy()
Vector3 G3D::Vector2::yyy () const
Definition at line 195 of file Vector2.cpp.
 { return Vector3       (y, y, y); }
References y.
yyyx()
Vector4 G3D::Vector2::yyyx () const
Definition at line 206 of file Vector2.cpp.
 { return Vector4       (y, y, y, x); }
References x, and y.
yyyy()
Vector4 G3D::Vector2::yyyy () const
Definition at line 214 of file Vector2.cpp.
 { return Vector4       (y, y, y, y); }
References y.
zero()
const Vector2 & G3D::Vector2::zero () static
Definition at line 67 of file Vector2.cpp.
{
     static Vector2 v(0, 0);
     return v;
 }
Referenced by directionOrZero(), G3D::Rect2D::extent(), and G3D::Rect2D::wh().
Member Data Documentation
x
float G3D::Vector2::x
Definition at line 49 of file Vector2.h.
Referenced by abs(), G3D::abs(), G3D::all(), G3D::any(), G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::bilinear(), clamp(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Rect2D::contains(), G3D::ConvexPolygon2D::contains(), G3D::Rect2D::corner(), deserialize(), G3D::AnyVal::deserialize(), direction(), dot(), G3D::GCamera::getProjectPixelMatrix(), G3D::GCamera::getProjectUnitMatrix(), hashCode(), G3D::LineSegment2D::intersection(), G3D::Rect2D::intersects(), G3D::Rect2D::intersectsOrTouches(), isFinite(), isNaN(), isZero(), length(), max(), maxAbs(), min(), minAbs(), G3D::Map2D< Storage, Compute >::nearest(), operator!=(), G3D::Rect2D::operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), pow(), G3D::Rect2D::randomPoint(), serialize(), G3D::Vector4::set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::GCamera::unproject(), Vector2(), G3D::Vector4::Vector4(), G3D::Rect2D::width(), G3D::BinaryOutput::writeVector2(), G3D::Rect2D::x0(), G3D::Rect2D::x0y1(), G3D::Rect2D::x1(), G3D::Rect2D::x1y0(), xx(), xxx(), xxxx(), xxxy(), xxy(), xxyx(), xxyy(), xy(), G3D::Rect2D::xywh(), xyx(), xyxx(), xyxy(), G3D::Rect2D::xyxy(), xyy(), xyyx(), xyyy(), yx(), yxx(), yxxx(), yxxy(), yxy(), yxyx(), yxyy(), yyx(), yyxx(), yyxy(), and yyyx().
y
float G3D::Vector2::y
Definition at line 50 of file Vector2.h.
Referenced by abs(), G3D::abs(), G3D::all(), G3D::any(), G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::bilinear(), clamp(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Rect2D::contains(), G3D::ConvexPolygon2D::contains(), G3D::Rect2D::corner(), deserialize(), G3D::AnyVal::deserialize(), direction(), dot(), G3D::GCamera::getProjectPixelMatrix(), G3D::GCamera::getProjectUnitMatrix(), hashCode(), G3D::Rect2D::height(), G3D::LineSegment2D::intersection(), G3D::Rect2D::intersects(), G3D::Rect2D::intersectsOrTouches(), isFinite(), isNaN(), isZero(), length(), max(), maxAbs(), min(), minAbs(), G3D::Map2D< Storage, Compute >::nearest(), operator!=(), G3D::Rect2D::operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), pow(), G3D::Rect2D::randomPoint(), serialize(), G3D::Vector4::set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::GCamera::unproject(), Vector2(), G3D::Vector4::Vector4(), G3D::BinaryOutput::writeVector2(), G3D::Rect2D::x0y1(), G3D::Rect2D::x1y0(), xxxy(), xxy(), xxyx(), xxyy(), xy(), G3D::Rect2D::xywh(), xyx(), xyxx(), xyxy(), G3D::Rect2D::xyxy(), xyy(), xyyx(), xyyy(), G3D::Rect2D::y0(), G3D::Rect2D::y1(), yx(), yxx(), yxxx(), yxxy(), yxy(), yxyx(), yxyy(), yy(), yyx(), yyxx(), yyxy(), yyy(), yyyx(), and yyyy().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Vector2.h
deps/g3dlite/source/Vector2.cpp