Azerotcore-wotlk: deps/jemalloc/src/safety_check.c File Reference
safety_check.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
Functions
void safety_check_set_abort (void(*abort_fn)(const char *))
void safety_check_fail (const char *format,...)
Variables
static void(* safety_check_abort)(const char *message)
Function Documentation
safety_check_fail()
void safety_check_fail (const char * format, ...)
Definition at line 10 of file safety_check.c.
{
     char buf[MALLOC_PRINTF_BUFSIZE];
     va_list ap;
     va_start(ap, format);
     malloc_vsnprintf(buf, MALLOC_PRINTF_BUFSIZE, format, ap);
     va_end(ap);
     if (safety_check_abort == NULL) {
         malloc_write(buf);
         abort();
     } else {
         safety_check_abort(buf);
     }
 }
References format(), MALLOC_PRINTF_BUFSIZE, malloc_vsnprintf, malloc_write, NULL, and safety_check_abort.
Referenced by safety_check_verify_redzone().
safety_check_set_abort()
void safety_check_set_abort (void(*)(const char *) abort_fn)
Definition at line 6 of file safety_check.c.
{
     safety_check_abort = abort_fn;
 }
References safety_check_abort.
Variable Documentation
safety_check_abort
void(* safety_check_abort) (const char *message) (const char * message) static
Definition at line 4 of file safety_check.c.
Referenced by safety_check_fail(), and safety_check_set_abort().