Azerotcore-wotlk: Quest Class Reference
Quest Class Reference
#include <QuestDef.h>
Public Types
typedef std::vector< int32 > PrevQuests
typedef std::vector< uint32 > PrevChainQuests
Public Member Functions
Quest (Field *questRecord)
void LoadQuestDetails (Field *fields)
void LoadQuestRequestItems (Field *fields)
void LoadQuestOfferReward (Field *fields)
void LoadQuestTemplateAddon (Field *fields)
uint32 XPValue (Player *player) const
bool HasFlag (uint32 flag) const
void SetFlag (uint32 flag)
bool HasSpecialFlag (uint32 flag) const
void SetSpecialFlag (uint32 flag)
uint32 GetQuestId () const
uint32 GetQuestMethod () const
int32 GetZoneOrSort () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
int32 GetQuestLevel () const
uint32 GetType () const
uint32 GetRequiredClasses () const
uint32 GetAllowableRaces () const
uint32 GetRequiredSkill () const
uint32 GetRequiredSkillValue () const
uint32 GetRepObjectiveFaction () const
int32 GetRepObjectiveValue () const
uint32 GetRepObjectiveFaction2 () const
int32 GetRepObjectiveValue2 () const
uint32 GetRequiredMinRepFaction () const
int32 GetRequiredMinRepValue () const
uint32 GetRequiredMaxRepFaction () const
int32 GetRequiredMaxRepValue () const
uint32 GetSuggestedPlayers () const
uint32 GetTimeAllowed () const
int32 GetPrevQuestId () const
uint32 GetNextQuestId () const
int32 GetExclusiveGroup () const
uint32 GetNextQuestInChain () const
uint32 GetCharTitleId () const
uint32 GetPlayersSlain () const
uint32 GetBonusTalents () const
int32 GetRewArenaPoints () const
uint32 GetXPId () const
uint32 GetSrcItemId () const
uint32 GetSrcItemCount () const
uint32 GetSrcSpell () const
std::string const & GetTitle () const
std::string const & GetDetails () const
std::string const & GetObjectives () const
std::string const & GetOfferRewardText () const
std::string const & GetRequestItemsText () const
std::string const & GetAreaDescription () const
std::string const & GetCompletedText () const
int32 GetRewOrReqMoney (Player *player=nullptr) const
uint32 GetRewHonorAddition () const
float GetRewHonorMultiplier () const
uint32 GetRewMoneyMaxLevel () const
uint32 GetRewSpell () const
int32 GetRewSpellCast () const
uint32 GetRewMailTemplateId () const
uint32 GetRewMailDelaySecs () const
uint32 GetRewMailSenderEntry () const
uint32 GetPOIContinent () const
float GetPOIx () const
float GetPOIy () const
uint32 GetPointOpt () const
uint32 GetIncompleteEmote () const
uint32 GetCompleteEmote () const
bool IsRepeatable () const
bool IsAutoAccept () const
bool IsAutoComplete () const
uint32 GetFlags () const
bool IsDaily () const
bool IsWeekly () const
bool IsMonthly () const
bool IsSeasonal () const
bool IsDailyOrWeekly () const
bool IsRaidQuest (Difficulty difficulty) const
bool IsAllowedInRaid (Difficulty difficulty) const
bool IsDFQuest () const
bool IsPVPQuest () const
uint32 CalculateHonorGain (uint8 level) const
uint32 GetReqItemsCount () const
uint32 GetReqCreatureOrGOcount () const
uint32 GetRewChoiceItemsCount () const
uint32 GetRewItemsCount () const
void InitializeQueryData ()
void SetEventIdForQuest (uint16 eventId)
uint16 GetEventIdForQuest () const
Public Attributes
std::string ObjectiveText [QUEST_OBJECTIVES_COUNT]
uint32 RequiredItemId [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 RequiredItemCount [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 ItemDrop [QUEST_SOURCE_ITEM_IDS_COUNT]
uint32 ItemDropQuantity [QUEST_SOURCE_ITEM_IDS_COUNT]
int32 RequiredNpcOrGo [QUEST_OBJECTIVES_COUNT]
uint32 RequiredNpcOrGoCount [QUEST_OBJECTIVES_COUNT]
uint32 RewardChoiceItemId [QUEST_REWARD_CHOICES_COUNT]
uint32 RewardChoiceItemCount [QUEST_REWARD_CHOICES_COUNT]
uint32 RewardItemId [QUEST_REWARDS_COUNT]
uint32 RewardItemIdCount [QUEST_REWARDS_COUNT]
uint32 RewardFactionId [QUEST_REPUTATIONS_COUNT]
int32 RewardFactionValueId [QUEST_REPUTATIONS_COUNT]
int32 RewardFactionValueIdOverride [QUEST_REPUTATIONS_COUNT]
uint32 DetailsEmote [QUEST_EMOTE_COUNT]
uint32 DetailsEmoteDelay [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmote [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmoteDelay [QUEST_EMOTE_COUNT]
PrevQuests prevQuests
PrevChainQuests prevChainQuests
WorldPacket queryData
Protected Attributes
uint32 Id
uint32 Method
int32 ZoneOrSort
uint32 MinLevel
int32 Level
uint32 Type
uint32 AllowableRaces
uint32 RequiredFactionId1
int32 RequiredFactionValue1
uint32 RequiredFactionId2
int32 RequiredFactionValue2
uint32 SuggestedPlayers
uint32 TimeAllowed
uint32 Flags
uint32 RewardTitleId
uint32 RequiredPlayerKills
uint32 RewardTalents
int32 RewardArenaPoints
uint32 RewardNextQuest
uint32 RewardXPDifficulty
uint32 StartItem
std::string Title
std::string Details
std::string Objectives
std::string OfferRewardText
std::string RequestItemsText
std::string AreaDescription
std::string CompletedText
uint32 RewardHonor
float RewardKillHonor
int32 RewardMoney
uint32 RewardMoneyDifficulty
uint32 RewardBonusMoney
uint32 RewardDisplaySpell
int32 RewardSpell
uint32 POIContinent
float POIx
float POIy
uint32 POIPriority
uint32 EmoteOnIncomplete
uint32 EmoteOnComplete
uint32 MaxLevel = 0
uint32 RequiredClasses = 0
uint32 SourceSpellid = 0
int32 PrevQuestId = 0
uint32 NextQuestId = 0
int32 ExclusiveGroup = 0
uint32 RewardMailTemplateId = 0
uint32 RewardMailDelay = 0
uint32 RequiredSkillId = 0
uint32 RequiredSkillPoints = 0
uint32 RequiredMinRepFaction = 0
int32 RequiredMinRepValue = 0
uint32 RequiredMaxRepFaction = 0
int32 RequiredMaxRepValue = 0
uint32 StartItemCount = 0
uint32 RewardMailSenderEntry = 0
uint32 SpecialFlags = 0
Private Attributes
uint32 _reqItemsCount
uint32 _reqCreatureOrGOcount
uint32 _rewChoiceItemsCount
uint32 _rewItemsCount
uint16 _eventIdForQuest
Friends
class ObjectMgr
Detailed Description
Definition at line 204 of file QuestDef.h.
Member Typedef Documentation
PrevChainQuests
typedef std::vector<uint32> Quest::PrevChainQuests
Definition at line 320 of file QuestDef.h.
PrevQuests
typedef std::vector<int32> Quest::PrevQuests
Definition at line 318 of file QuestDef.h.
Constructor & Destructor Documentation
Quest()
Quest::Quest (Field * questRecord)
Definition at line 24 of file QuestDef.cpp.
 {
     EmoteOnIncomplete = 0;
     EmoteOnComplete = 0;
     _reqItemsCount = 0;
     _reqCreatureOrGOcount = 0;
     _rewItemsCount = 0;
     _rewChoiceItemsCount = 0;
     Id = questRecord[0].GetUInt32();
     Method = questRecord[1].GetUInt8();
     Level = questRecord[2].GetInt16();
     MinLevel = questRecord[3].GetUInt8();
     ZoneOrSort = questRecord[4].GetInt16();
     Type = questRecord[5].GetUInt16();
     SuggestedPlayers = questRecord[6].GetUInt8();
     TimeAllowed = questRecord[7].GetUInt32();
     AllowableRaces = questRecord[8].GetUInt16();
     RequiredFactionId1 = questRecord[9].GetUInt16();
     RequiredFactionId2 = questRecord[10].GetUInt16();
     RequiredFactionValue1 = questRecord[11].GetInt32();
     RequiredFactionValue2 = questRecord[12].GetInt32();
     RewardNextQuest = questRecord[13].GetUInt32();
     RewardXPDifficulty = questRecord[14].GetUInt8();
     RewardMoney = questRecord[15].GetInt32();
     RewardMoneyDifficulty = questRecord[16].GetUInt32();
     RewardBonusMoney = questRecord[17].GetUInt32();
     RewardDisplaySpell = questRecord[18].GetUInt32();
     RewardSpell = questRecord[19].GetInt32();
     RewardHonor = questRecord[20].GetUInt32();
     RewardKillHonor = questRecord[21].GetFloat();
     StartItem = questRecord[22].GetUInt32();
     Flags = questRecord[23].GetUInt32();
     RewardTitleId = questRecord[24].GetUInt8();
     RequiredPlayerKills = questRecord[25].GetUInt8();
     RewardTalents = questRecord[26].GetUInt8();
     RewardArenaPoints = questRecord[27].GetUInt16();
     for (int i = 0; i < QUEST_REWARDS_COUNT; ++i)
     {
         RewardItemId[i] = questRecord[28 + i * 2].GetUInt32();
         RewardItemIdCount[i] = questRecord[29 + i * 2].GetUInt16();
         if (RewardItemId[i])
             ++_rewItemsCount;
     }
     for (int i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
     {
         RewardChoiceItemId[i] = questRecord[36 + i * 2].GetUInt32();
         RewardChoiceItemCount[i] = questRecord[37 + i * 2].GetUInt16();
         if (RewardChoiceItemId[i])
             ++_rewChoiceItemsCount;
     }
     for (int i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)
     {
         RewardFactionId[i] = questRecord[48 + i * 3].GetUInt16();
         RewardFactionValueId[i] = questRecord[49 + i * 3].GetInt32();
         RewardFactionValueIdOverride[i] = questRecord[50 + i * 3].GetInt32();
     }
     POIContinent = questRecord[63].GetUInt16();
     POIx = questRecord[64].GetFloat();
     POIy = questRecord[65].GetFloat();
     POIPriority = questRecord[66].GetUInt32();
     Title = questRecord[67].GetString();
     Objectives = questRecord[68].GetString();
     Details = questRecord[69].GetString();
     AreaDescription = questRecord[70].GetString();
     CompletedText = questRecord[71].GetString();
     for (int i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
     {
         RequiredNpcOrGo[i] = questRecord[72 + i].GetInt32();
         RequiredNpcOrGoCount[i] = questRecord[76 + i].GetUInt16();
         ObjectiveText[i] = questRecord[101 + i].GetString();
         if (RequiredNpcOrGo[i])
             ++_reqCreatureOrGOcount;
     }
     for (int i = 0; i < QUEST_SOURCE_ITEM_IDS_COUNT; ++i)
     {
         ItemDrop[i] = questRecord[80 + i].GetUInt32();
         ItemDropQuantity[i] = questRecord[84 + i].GetUInt16();
     }
     for (int i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; ++i)
     {
         RequiredItemId[i] = questRecord[88 + i].GetUInt32();
         RequiredItemCount[i] = questRecord[94 + i].GetUInt16();
         if (RequiredItemId[i])
             ++_reqItemsCount;
     }
     // int8 Unknown0 = questRecord[100].GetUInt8();
     // int32 VerifiedBuild = questRecord[105].GetInt32();
     for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
     {
         DetailsEmote[i] = 0;
         DetailsEmoteDelay[i] = 0;
         OfferRewardEmote[i] = 0;
         OfferRewardEmoteDelay[i] = 0;
     }
     _eventIdForQuest = 0;
 }
References _eventIdForQuest, _reqCreatureOrGOcount, _reqItemsCount, _rewChoiceItemsCount, _rewItemsCount, AllowableRaces, AreaDescription, CompletedText, Details, DetailsEmote, DetailsEmoteDelay, EmoteOnComplete, EmoteOnIncomplete, Flags, Field::GetFloat(), Field::GetInt16(), Field::GetInt32(), Field::GetString(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), Id, ItemDrop, ItemDropQuantity, Level, Method, MinLevel, Objectives, ObjectiveText, OfferRewardEmote, OfferRewardEmoteDelay, POIContinent, POIPriority, POIx, POIy, QUEST_EMOTE_COUNT, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, QUEST_SOURCE_ITEM_IDS_COUNT, RequiredFactionId1, RequiredFactionId2, RequiredFactionValue1, RequiredFactionValue2, RequiredItemCount, RequiredItemId, RequiredNpcOrGo, RequiredNpcOrGoCount, RequiredPlayerKills, RewardArenaPoints, RewardBonusMoney, RewardChoiceItemCount, RewardChoiceItemId, RewardDisplaySpell, RewardFactionId, RewardFactionValueId, RewardFactionValueIdOverride, RewardHonor, RewardItemId, RewardItemIdCount, RewardKillHonor, RewardMoney, RewardMoneyDifficulty, RewardNextQuest, RewardSpell, RewardTalents, RewardTitleId, RewardXPDifficulty, StartItem, SuggestedPlayers, TimeAllowed, Title, Type, and ZoneOrSort.
Member Function Documentation
CalculateHonorGain()
uint32 Quest::CalculateHonorGain (uint8 level) const
Definition at line 280 of file QuestDef.cpp.
 {
     if (level > GT_MAX_LEVEL)
         level = GT_MAX_LEVEL;
     uint32 honor = 0;
     if (GetRewHonorAddition() > 0 || GetRewHonorMultiplier() > 0.0f)
     {
         // values stored from 0.. for 1...
         TeamContributionPointsEntry const* tc = sTeamContributionPointsStore.LookupEntry(level);
         if (!tc)
             return 0;
         honor = uint32(tc->value * GetRewHonorMultiplier() * 0.1000000014901161);
         // Xinef: exactly this is calculated above, however with higher precision...
         //honor += Acore::Honor::hk_honor_at_level(level, GetRewHonorMultiplier());
         honor += GetRewHonorAddition();
     }
     return honor;
 }
References GetRewHonorAddition(), GetRewHonorMultiplier(), GT_MAX_LEVEL, sTeamContributionPointsStore, and TeamContributionPointsEntry::value.
Referenced by Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and Player::SendQuestReward().
GetAllowableRaces()
uint32 Quest::GetAllowableRaces () const inline
Definition at line 231 of file QuestDef.h.
 { return AllowableRaces; }
References AllowableRaces.
Referenced by Player::SatisfyQuestRace().
GetAreaDescription()
std::string const& Quest::GetAreaDescription () const inline
Definition at line 261 of file QuestDef.h.
 { return AreaDescription; }
References AreaDescription.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetBonusTalents()
uint32 Quest::GetBonusTalents () const inline
Definition at line 250 of file QuestDef.h.
 { return RewardTalents; }
References RewardTalents.
Referenced by Player::_LoadQuestStatusRewarded(), InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetCharTitleId()
uint32 Quest::GetCharTitleId () const inline
Definition at line 248 of file QuestDef.h.
 { return RewardTitleId; }
References RewardTitleId.
Referenced by Player::_LoadQuestStatusRewarded(), InitializeQueryData(), ObjectMgr::LoadQuests(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetCompletedText()
std::string const& Quest::GetCompletedText () const inline
Definition at line 262 of file QuestDef.h.
 { return CompletedText; }
References CompletedText.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetCompleteEmote()
uint32 Quest::GetCompleteEmote () const inline
Definition at line 277 of file QuestDef.h.
 { return EmoteOnComplete; }
References EmoteOnComplete.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetDetails()
std::string const& Quest::GetDetails () const inline
Definition at line 257 of file QuestDef.h.
 { return Details; }
References Details.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetEventIdForQuest()
uint16 Quest::GetEventIdForQuest () const inline
Definition at line 327 of file QuestDef.h.
 { return _eventIdForQuest; }
References _eventIdForQuest.
Referenced by Player::SatisfyQuestSeasonal(), and Player::SetSeasonalQuestStatus().
GetExclusiveGroup()
int32 Quest::GetExclusiveGroup () const inline
Definition at line 246 of file QuestDef.h.
 { return ExclusiveGroup; }
References ExclusiveGroup.
Referenced by Player::SatisfyQuestExclusiveGroup(), and Player::SatisfyQuestPreviousQuest().
GetFlags()
uint32 Quest::GetFlags () const inline
Definition at line 281 of file QuestDef.h.
 { return Flags; }
References Flags.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetIncompleteEmote()
uint32 Quest::GetIncompleteEmote () const inline
Definition at line 276 of file QuestDef.h.
 { return EmoteOnIncomplete; }
References EmoteOnIncomplete.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetMaxLevel()
uint32 Quest::GetMaxLevel () const inline
Definition at line 227 of file QuestDef.h.
 { return MaxLevel; }
References MaxLevel.
Referenced by Player::SatisfyQuestLevel().
GetMinLevel()
uint32 Quest::GetMinLevel () const inline
Definition at line 226 of file QuestDef.h.
 { return MinLevel; }
References MinLevel.
Referenced by Player::CanSeeStartQuest(), InitializeQueryData(), Player::SatisfyQuestLevel(), and PlayerMenu::SendQuestQueryResponse().
GetNextQuestId()
uint32 Quest::GetNextQuestId () const inline
Definition at line 245 of file QuestDef.h.
 { return NextQuestId; }
References NextQuestId.
Referenced by ObjectMgr::LoadQuests().
GetNextQuestInChain()
uint32 Quest::GetNextQuestInChain () const inline
Definition at line 247 of file QuestDef.h.
 { return RewardNextQuest; }
References RewardNextQuest.
Referenced by Player::GetNextQuest(), InitializeQueryData(), Player::SatisfyQuestNextChain(), and PlayerMenu::SendQuestQueryResponse().
GetObjectives()
std::string const& Quest::GetObjectives () const inline
Definition at line 258 of file QuestDef.h.
 { return Objectives; }
References Objectives.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetOfferRewardText()
std::string const& Quest::GetOfferRewardText () const inline
Definition at line 259 of file QuestDef.h.
 { return OfferRewardText; }
References OfferRewardText.
Referenced by PlayerMenu::SendQuestGiverOfferReward().
GetPlayersSlain()
uint32 Quest::GetPlayersSlain () const inline
Definition at line 249 of file QuestDef.h.
 { return RequiredPlayerKills; }
References RequiredPlayerKills.
Referenced by Player::CanCompleteQuest(), InitializeQueryData(), Player::KilledPlayerCredit(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestUpdateAddPlayer().
GetPOIContinent()
uint32 Quest::GetPOIContinent () const inline
Definition at line 272 of file QuestDef.h.
 { return POIContinent; }
References POIContinent.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPointOpt()
uint32 Quest::GetPointOpt () const inline
Definition at line 275 of file QuestDef.h.
 { return POIPriority; }
References POIPriority.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPOIx()
float Quest::GetPOIx () const inline
Definition at line 273 of file QuestDef.h.
 { return POIx; }
References POIx.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPOIy()
float Quest::GetPOIy () const inline
Definition at line 274 of file QuestDef.h.
 { return POIy; }
References POIy.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetPrevQuestId()
int32 Quest::GetPrevQuestId () const inline
Definition at line 244 of file QuestDef.h.
 { return PrevQuestId; }
References PrevQuestId.
Referenced by ObjectMgr::LoadQuests().
GetQuestId()
uint32 Quest::GetQuestId () const inline
Definition at line 223 of file QuestDef.h.
 { return Id; }
References Id.
Referenced by Player::AddQuest(), Player::AddQuestAndCheckCompletion(), Player::AdjustQuestReqItemCount(), Player::CanRewardQuest(), Player::CanSeeStartQuest(), Player::CanTakeQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), npc_escortAI::JustDied(), FollowerAI::JustDied(), ObjectMgr::LoadQuests(), Condition::Meets(), QuestApprenticeAnglerPlayerScript::OnPlayerCompleteQuest(), npc_cos_chromie_start::OnQuestAccept(), npc_cos_chromie_middle::OnQuestAccept(), npc_costumed_orphan_matron::OnQuestAccept(), npc_chicken_cluck::OnQuestAccept(), npc_steward_of_time::OnQuestAccept(), npc_kernobee::OnQuestAccept(), npc_koltira_deathweaver::OnQuestAccept(), pyrewood_ambush::OnQuestAccept(), npc_daphne_stilwell::OnQuestAccept(), npc_mikhail::OnQuestAccept(), npc_kerlonian::OnQuestAccept(), npc_prospector_remtravel::OnQuestAccept(), npc_tooga::OnQuestAccept(), npc_gilthares::OnQuestAccept(), npc_lakota_windsong::OnQuestAccept(), npc_paoka_swiftmountain::OnQuestAccept(), npc_ringo::OnQuestAccept(), npc_engineer_helice::OnQuestAccept(), npc_maghar_captive::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_maxx_a_million_escort::OnQuestAccept(), npc_earthmender_wilda::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_ranger_lilatha::OnQuestAccept(), npc_deathstalker_erland::OnQuestAccept(), npc_bartleby::OnQuestAccept(), npc_tyrion::OnQuestAccept(), npc_calvin_montague::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_shenthul::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_wizzlecrank_shredder::OnQuestAccept(), npc_ame::OnQuestAccept(), npc_ranshalla::OnQuestAccept(), npc_lurgglbr::OnQuestAccept(), npc_mootoo_the_younger::OnQuestAccept(), npc_bonker_togglevolt::OnQuestAccept(), npc_emily::OnQuestAccept(), npc_apothecary_hanes::OnQuestAccept(), npc_battle_at_valhalas::OnQuestAccept(), npc_finklestein::OnQuestAccept(), npc_bessy::OnQuestAccept(), npc_karynaku::OnQuestAccept(), npc_isla_starmane::OnQuestAccept(), npc_kayra_longmane::OnQuestAccept(), npc_doctor::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), npc_chicken_cluck::OnQuestComplete(), npc_love_in_air_hummel::OnQuestReward(), npc_rocknot::OnQuestReward(), npc_thrall_bfu::OnQuestReward(), npc_lady_sylvanas_windrunner::OnQuestReward(), npc_elder_clearwater::OnQuestReward(), npc_riggle_bassbait::OnQuestReward(), Player::PrettyPrintRequirementsQuestList(), SmartGameObjectAI::QuestAccept(), SmartGameObjectAI::QuestReward(), Player::RewardQuest(), Player::SatisfyQuestConditions(), Player::SatisfyQuestDay(), Player::SatisfyQuestExclusiveGroup(), Player::SatisfyQuestMonth(), Player::SatisfyQuestSeasonal(), Player::SatisfyQuestStatus(), Player::SatisfyQuestWeek(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestReward(), Player::SendQuestUpdateAddCreatureOrGo(), Player::SendQuestUpdateAddPlayer(), npc_belnistrasz::npc_belnistraszAI::sQuestAccept(), SmartAI::sQuestAccept(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::sQuestAccept(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_muglash::npc_muglashAI::sQuestAccept(), npc_magwin::npc_magwinAI::sQuestAccept(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::sQuestAccept(), SmartAI::sQuestReward(), and npc_escortAI::Start().
GetQuestLevel()
int32 Quest::GetQuestLevel () const inline
Definition at line 228 of file QuestDef.h.
 { return Level; }
References Level.
Referenced by Player::GetQuestLevel(), InitializeQueryData(), Player::PrettyPrintRequirementsQuestList(), and PlayerMenu::SendQuestQueryResponse().
GetQuestMethod()
uint32 Quest::GetQuestMethod () const inline
Definition at line 224 of file QuestDef.h.
 { return Method; }
References Method.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), InitializeQueryData(), ObjectMgr::LoadQuests(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveFaction()
uint32 Quest::GetRepObjectiveFaction () const inline
Definition at line 234 of file QuestDef.h.
 { return RequiredFactionId1; }
References RequiredFactionId1.
Referenced by Player::AddQuest(), Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveFaction2()
uint32 Quest::GetRepObjectiveFaction2 () const inline
Definition at line 236 of file QuestDef.h.
 { return RequiredFactionId2; }
References RequiredFactionId2.
Referenced by Player::AddQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::SatisfyQuestReputation(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveValue()
int32 Quest::GetRepObjectiveValue () const inline
Definition at line 235 of file QuestDef.h.
 { return RequiredFactionValue1; }
References RequiredFactionValue1.
Referenced by Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRepObjectiveValue2()
int32 Quest::GetRepObjectiveValue2 () const inline
Definition at line 237 of file QuestDef.h.
 { return RequiredFactionValue2; }
References RequiredFactionValue2.
Referenced by quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::SatisfyQuestReputation(), and PlayerMenu::SendQuestQueryResponse().
GetReqCreatureOrGOcount()
uint32 Quest::GetReqCreatureOrGOcount () const inline
Definition at line 314 of file QuestDef.h.
 { return _reqCreatureOrGOcount; }
References _reqCreatureOrGOcount.
GetReqItemsCount()
uint32 Quest::GetReqItemsCount () const inline
Definition at line 313 of file QuestDef.h.
 { return _reqItemsCount; }
References _reqItemsCount.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequestItemsText()
std::string const& Quest::GetRequestItemsText () const inline
Definition at line 260 of file QuestDef.h.
 { return RequestItemsText; }
References RequestItemsText.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequiredClasses()
uint32 Quest::GetRequiredClasses () const inline
Definition at line 230 of file QuestDef.h.
 { return RequiredClasses; }
References RequiredClasses.
Referenced by Player::SatisfyQuestClass().
GetRequiredMaxRepFaction()
uint32 Quest::GetRequiredMaxRepFaction () const inline
Definition at line 240 of file QuestDef.h.
 { return RequiredMaxRepFaction; }
References RequiredMaxRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMaxRepValue()
int32 Quest::GetRequiredMaxRepValue () const inline
Definition at line 241 of file QuestDef.h.
 { return RequiredMaxRepValue; }
References RequiredMaxRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepFaction()
uint32 Quest::GetRequiredMinRepFaction () const inline
Definition at line 238 of file QuestDef.h.
 { return RequiredMinRepFaction; }
References RequiredMinRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepValue()
int32 Quest::GetRequiredMinRepValue () const inline
Definition at line 239 of file QuestDef.h.
 { return RequiredMinRepValue; }
References RequiredMinRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredSkill()
uint32 Quest::GetRequiredSkill () const inline
Definition at line 232 of file QuestDef.h.
 { return RequiredSkillId; }
References RequiredSkillId.
Referenced by Player::SatisfyQuestSkill().
GetRequiredSkillValue()
uint32 Quest::GetRequiredSkillValue () const inline
Definition at line 233 of file QuestDef.h.
 { return RequiredSkillPoints; }
References RequiredSkillPoints.
Referenced by Player::SatisfyQuestSkill().
GetRewArenaPoints()
int32 Quest::GetRewArenaPoints () const inline
Definition at line 251 of file QuestDef.h.
 {return RewardArenaPoints; }
References RewardArenaPoints.
Referenced by InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewChoiceItemsCount()
uint32 Quest::GetRewChoiceItemsCount () const inline
Definition at line 315 of file QuestDef.h.
 { return _rewChoiceItemsCount; }
References _rewChoiceItemsCount.
Referenced by Player::CanRewardQuest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewHonorAddition()
uint32 Quest::GetRewHonorAddition () const inline
Definition at line 264 of file QuestDef.h.
 { return RewardHonor; }
References RewardHonor.
Referenced by CalculateHonorGain(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRewHonorMultiplier()
float Quest::GetRewHonorMultiplier () const inline
Definition at line 265 of file QuestDef.h.
 { return RewardKillHonor; }
References RewardKillHonor.
Referenced by CalculateHonorGain(), InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetRewItemsCount()
uint32 Quest::GetRewItemsCount () const inline
Definition at line 316 of file QuestDef.h.
 { return _rewItemsCount; }
References _rewItemsCount.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewMailDelaySecs()
uint32 Quest::GetRewMailDelaySecs () const inline
Definition at line 270 of file QuestDef.h.
 { return RewardMailDelay; }
References RewardMailDelay.
Referenced by Player::RewardQuest().
GetRewMailSenderEntry()
uint32 Quest::GetRewMailSenderEntry () const inline
Definition at line 271 of file QuestDef.h.
 { return RewardMailSenderEntry; }
References RewardMailSenderEntry.
Referenced by Player::RewardQuest().
GetRewMailTemplateId()
uint32 Quest::GetRewMailTemplateId () const inline
Definition at line 269 of file QuestDef.h.
 { return RewardMailTemplateId; }
References RewardMailTemplateId.
Referenced by Player::RewardQuest().
GetRewMoneyMaxLevel()
uint32 Quest::GetRewMoneyMaxLevel () const
Definition at line 237 of file QuestDef.cpp.
 {
     if (HasFlag(QUEST_FLAGS_NO_MONEY_FROM_XP))
         return 0;
     return static_cast<int32>(RewardBonusMoney * sWorld->getRate(RATE_REWARD_BONUS_MONEY) * sWorld->getRate(RATE_DROP_MONEY));
 }
References HasFlag(), QUEST_FLAGS_NO_MONEY_FROM_XP, RATE_DROP_MONEY, RATE_REWARD_BONUS_MONEY, RewardBonusMoney, and sWorld.
Referenced by InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewOrReqMoney()
int32 Quest::GetRewOrReqMoney (Player * player = nullptr) const
Definition at line 218 of file QuestDef.cpp.
 {
     int32 rewardedMoney = RewardMoney;
     if (rewardedMoney < 0)
     {
         return rewardedMoney;
     }
     if (player && RewardMoneyDifficulty)
     {
         if (uint32 questRewardedMoney = sObjectMgr->GetQuestMoneyReward(player->getLevel(), RewardMoneyDifficulty))
         {
             rewardedMoney = questRewardedMoney;
         }
     }
     return static_cast<int32>(rewardedMoney * sWorld->getRate(RATE_DROP_MONEY));
 }
References Unit::getLevel(), RATE_DROP_MONEY, RewardMoney, RewardMoneyDifficulty, sObjectMgr, and sWorld.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), quest_commandscript::HandleQuestComplete(), InitializeQueryData(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), and Player::SendQuestReward().
GetRewSpell()
uint32 Quest::GetRewSpell () const inline
Definition at line 267 of file QuestDef.h.
 { return RewardDisplaySpell; }
References RewardDisplaySpell.
Referenced by InitializeQueryData(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetRewSpellCast()
int32 Quest::GetRewSpellCast () const inline
Definition at line 268 of file QuestDef.h.
 { return RewardSpell; }
References RewardSpell.
Referenced by InitializeQueryData(), Player::learnQuestRewardedSpells(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
GetSrcItemCount()
uint32 Quest::GetSrcItemCount () const inline
Definition at line 254 of file QuestDef.h.
 { return StartItemCount; }
References StartItemCount.
Referenced by Player::CanAddQuest(), Player::GiveQuestSourceItem(), and Player::TakeQuestSourceItem().
GetSrcItemId()
uint32 Quest::GetSrcItemId () const inline
Definition at line 253 of file QuestDef.h.
 { return StartItem; }
References StartItem.
Referenced by Player::CanAddQuest(), Player::GiveQuestSourceItem(), InitializeQueryData(), PlayerMenu::SendQuestQueryResponse(), and Player::TakeQuestSourceItem().
GetSrcSpell()
uint32 Quest::GetSrcSpell () const inline
Definition at line 255 of file QuestDef.h.
 { return SourceSpellid; }
References SourceSpellid.
GetSuggestedPlayers()
uint32 Quest::GetSuggestedPlayers () const inline
Definition at line 242 of file QuestDef.h.
 { return SuggestedPlayers; }
References SuggestedPlayers.
Referenced by InitializeQueryData(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetTimeAllowed()
uint32 Quest::GetTimeAllowed () const inline
Definition at line 243 of file QuestDef.h.
 { return TimeAllowed; }
References TimeAllowed.
Referenced by Player::AddQuest().
GetTitle()
std::string const& Quest::GetTitle () const inline
Definition at line 256 of file QuestDef.h.
 { return Title; }
References Title.
Referenced by InitializeQueryData(), Player::PrettyPrintRequirementsQuestList(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
GetType()
uint32 Quest::GetType () const inline
Definition at line 229 of file QuestDef.h.
 { return Type; }
References Type.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetXPId()
uint32 Quest::GetXPId () const inline
Definition at line 252 of file QuestDef.h.
 { return RewardXPDifficulty; }
References RewardXPDifficulty.
Referenced by InitializeQueryData(), and PlayerMenu::SendQuestQueryResponse().
GetZoneOrSort()
int32 Quest::GetZoneOrSort () const inline
Definition at line 225 of file QuestDef.h.
 { return ZoneOrSort; }
References ZoneOrSort.
Referenced by InitializeQueryData(), Player::KilledPlayerCredit(), Player::RewardQuest(), PlayerMenu::SendQuestQueryResponse(), and AchievementMgr::UpdateAchievementCriteria().
HasFlag()
bool Quest::HasFlag (uint32 flag) const inline
Definition at line 216 of file QuestDef.h.
 { return (Flags & flag) != 0; }
References Flags.
Referenced by Player::AddQuest(), Player::CanShareQuest(), Player::CompleteQuest(), Spell::EffectQuestClear(), GetRewMoneyMaxLevel(), quest_commandscript::HandleQuestRemove(), Player::HasPvPForcingQuest(), InitializeQueryData(), IsAutoComplete(), Player::RewardQuest(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
HasSpecialFlag()
bool Quest::HasSpecialFlag (uint32 flag) const inline
Definition at line 219 of file QuestDef.h.
 { return (SpecialFlags & flag) != 0; }
References SpecialFlags.
Referenced by Player::_LoadQuestStatus(), Player::AddQuest(), Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), Player::KillCreditGO(), Player::KilledMonsterCredit(), Player::KilledPlayerCredit(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuests(), ObjectMgr::LoadScripts(), Player::SatisfyQuestTimed(), and Player::TalkedToCreature().
InitializeQueryData()
void Quest::InitializeQueryData ()
Definition at line 303 of file QuestDef.cpp.
 {
     queryData.Initialize(SMSG_QUEST_QUERY_RESPONSE, 1);
     queryData << uint32(GetQuestId());                    // quest id
     queryData << uint32(GetQuestMethod());                // Accepted values: 0, 1 or 2. 0 == IsAutoComplete() (skip objectives/details)
     queryData << uint32(GetQuestLevel());                 // may be -1, static data, in other cases must be used dynamic level: Player::GetQuestLevel (0 is not known, but assuming this is no longer valid for quest intended for client)
     queryData << uint32(GetMinLevel());                   // min level
     queryData << uint32(GetZoneOrSort());                 // zone or sort to display in quest log
     queryData << uint32(GetType());                       // quest type
     queryData << uint32(GetSuggestedPlayers());           // suggested players count
     queryData << uint32(GetRepObjectiveFaction());        // shown in quest log as part of quest objective
     queryData << uint32(GetRepObjectiveValue());          // shown in quest log as part of quest objective
     queryData << uint32(GetRepObjectiveFaction2());       // shown in quest log as part of quest objective OPPOSITE faction
     queryData << uint32(GetRepObjectiveValue2());         // shown in quest log as part of quest objective OPPOSITE faction
     queryData << uint32(GetNextQuestInChain());           // client will request this quest from NPC, if not 0
     queryData << uint32(GetXPId());                       // used for calculating rewarded experience
     if (HasFlag(QUEST_FLAGS_HIDDEN_REWARDS))
         queryData << uint32(0);                           // Hide money rewarded
     else
         queryData << int32(GetRewOrReqMoney());           // reward money (below max lvl)
     queryData << uint32(GetRewMoneyMaxLevel());           // used in XP calculation at client
     queryData << uint32(GetRewSpell());                   // reward spell, this spell will display (icon) (casted if RewSpellCast == 0)
     queryData << int32(GetRewSpellCast());                // casted spell
     // rewarded honor points
     queryData << uint32(GetRewHonorAddition());
     queryData << float(GetRewHonorMultiplier());
     queryData << uint32(GetSrcItemId());                  // source item id
     queryData << uint32(GetFlags() & 0xFFFF);             // quest flags
     queryData << uint32(GetCharTitleId());                // CharTitleId, new 2.4.0, player gets this title (id from CharTitles)
     queryData << uint32(GetPlayersSlain());               // players slain
     queryData << uint32(GetBonusTalents());               // bonus talents
     queryData << uint32(GetRewArenaPoints());             // bonus arena points
     queryData << uint32(0);                                      // review rep show mask
     if (HasFlag(QUEST_FLAGS_HIDDEN_REWARDS))
     {
         for (uint32 i = 0; i < QUEST_REWARDS_COUNT; ++i)
             queryData << uint32(0) << uint32(0);
         for (uint32 i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
             queryData << uint32(0) << uint32(0);
     }
     else
     {
         for (uint32 i = 0; i < QUEST_REWARDS_COUNT; ++i)
         {
             queryData << uint32(RewardItemId[i]);
             queryData << uint32(RewardItemIdCount[i]);
         }
         for (uint32 i = 0; i < QUEST_REWARD_CHOICES_COUNT; ++i)
         {
             queryData << uint32(RewardChoiceItemId[i]);
             queryData << uint32(RewardChoiceItemCount[i]);
         }
     }
     for (uint32 i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)        // reward factions ids
         queryData << uint32(RewardFactionId[i]);
     for (uint32 i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)        // columnid+1 QuestFactionReward.dbc?
         queryData << int32(RewardFactionValueId[i]);
     for (int i = 0; i < QUEST_REPUTATIONS_COUNT; ++i)           // unk (0)
         queryData << int32(RewardFactionValueIdOverride[i]);
     queryData << GetPOIContinent();
     queryData << GetPOIx();
     queryData << GetPOIy();
     queryData << GetPointOpt();
     queryData << GetTitle();
     queryData << GetObjectives();
     queryData << GetDetails();
     queryData << GetAreaDescription();
     queryData << GetCompletedText();                                  // display in quest objectives window once all objectives are completed
     for (uint32 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
     {
         if (RequiredNpcOrGo[i] < 0)
             queryData << uint32((RequiredNpcOrGo[i] * (-1)) | 0x80000000);    // client expects gameobject template id in form (id|0x80000000)
         else
             queryData << uint32(RequiredNpcOrGo[i]);
         queryData << uint32(RequiredNpcOrGoCount[i]);
         queryData << uint32(ItemDrop[i]);
         queryData << uint32(0);                                  // req source count?
     }
     for (uint32 i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; ++i)
     {
         queryData << uint32(RequiredItemId[i]);
         queryData << uint32(RequiredItemCount[i]);
     }
     for (uint32 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
         queryData << ObjectiveText[i];
 }
References GetAreaDescription(), GetBonusTalents(), GetCharTitleId(), GetCompletedText(), GetDetails(), GetFlags(), GetMinLevel(), GetNextQuestInChain(), GetObjectives(), GetPlayersSlain(), GetPOIContinent(), GetPointOpt(), GetPOIx(), GetPOIy(), GetQuestId(), GetQuestLevel(), GetQuestMethod(), GetRepObjectiveFaction(), GetRepObjectiveFaction2(), GetRepObjectiveValue(), GetRepObjectiveValue2(), GetRewArenaPoints(), GetRewHonorAddition(), GetRewHonorMultiplier(), GetRewMoneyMaxLevel(), GetRewOrReqMoney(), GetRewSpell(), GetRewSpellCast(), GetSrcItemId(), GetSuggestedPlayers(), GetTitle(), GetType(), GetXPId(), GetZoneOrSort(), HasFlag(), WorldPacket::Initialize(), ItemDrop, ObjectiveText, queryData, QUEST_FLAGS_HIDDEN_REWARDS, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, RequiredItemCount, RequiredItemId, RequiredNpcOrGo, RequiredNpcOrGoCount, RewardChoiceItemCount, RewardChoiceItemId, RewardFactionId, RewardFactionValueId, RewardFactionValueIdOverride, RewardItemId, RewardItemIdCount, and SMSG_QUEST_QUERY_RESPONSE.
IsAllowedInRaid()
bool Quest::IsAllowedInRaid (Difficulty difficulty) const
Definition at line 272 of file QuestDef.cpp.
 {
     if (IsRaidQuest(difficulty))
         return true;
     return sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_RAID);
 }
References CONFIG_QUEST_IGNORE_RAID, IsRaidQuest(), and sWorld.
Referenced by Player::HasQuestForGO(), Player::HasQuestForItem(), Player::KilledMonsterCredit(), and Player::KilledPlayerCredit().
IsAutoAccept()
bool Quest::IsAutoAccept () const
Definition at line 245 of file QuestDef.cpp.
 {
     return sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_ACCEPT) ? false : (Flags & QUEST_FLAGS_AUTO_ACCEPT);
 }
References CONFIG_QUEST_IGNORE_AUTO_ACCEPT, false, Flags, QUEST_FLAGS_AUTO_ACCEPT, and sWorld.
IsAutoComplete()
bool Quest::IsAutoComplete () const
Definition at line 250 of file QuestDef.cpp.
 {
     return sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_COMPLETE) ? false : HasFlag(QUEST_FLAGS_AUTOCOMPLETE);
 }
References CONFIG_QUEST_IGNORE_AUTO_COMPLETE, false, HasFlag(), QUEST_FLAGS_AUTOCOMPLETE, and sWorld.
Referenced by Player::CanCompleteQuest(), Player::CanRewardQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), npc_wg_quest_giver::OnGossipHello(), and Player::PrepareQuestMenu().
IsDaily()
bool Quest::IsDaily () const inline
Definition at line 282 of file QuestDef.h.
 { return Flags & QUEST_FLAGS_DAILY; }
References Flags, and QUEST_FLAGS_DAILY.
Referenced by npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), PoolMgr::LoadFromDB(), Player::RewardQuest(), Player::RewardReputation(), and Player::SatisfyQuestDay().
IsDailyOrWeekly()
bool Quest::IsDailyOrWeekly () const inline
Definition at line 286 of file QuestDef.h.
 { return Flags & (QUEST_FLAGS_DAILY | QUEST_FLAGS_WEEKLY); }
References Flags, QUEST_FLAGS_DAILY, and QUEST_FLAGS_WEEKLY.
Referenced by npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), and PoolMgr::LoadFromDB().
IsDFQuest()
bool Quest::IsDFQuest () const inline
Definition at line 289 of file QuestDef.h.
 { return SpecialFlags & QUEST_SPECIAL_FLAGS_DF_QUEST; }
References QUEST_SPECIAL_FLAGS_DF_QUEST, and SpecialFlags.
Referenced by Player::CanRewardQuest(), Player::RewardQuest(), and Player::SatisfyQuestDay().
IsMonthly()
bool Quest::IsMonthly () const inline
Definition at line 284 of file QuestDef.h.
 { return SpecialFlags & QUEST_SPECIAL_FLAGS_MONTHLY; }
References QUEST_SPECIAL_FLAGS_MONTHLY, and SpecialFlags.
Referenced by Player::RewardQuest(), Player::RewardReputation(), and Player::SatisfyQuestMonth().
IsPVPQuest()
bool Quest::IsPVPQuest () const inline
Definition at line 290 of file QuestDef.h.
 { return Type == QUEST_TYPE_PVP; }
References QUEST_TYPE_PVP, and Type.
Referenced by Player::KilledMonsterCredit().
IsRaidQuest()
bool Quest::IsRaidQuest (Difficulty difficulty) const
Definition at line 255 of file QuestDef.cpp.
 {
     switch (Type)
     {
         case QUEST_TYPE_RAID:
             return true;
         case QUEST_TYPE_RAID_10:
             return !(difficulty & RAID_DIFFICULTY_MASK_25MAN);
         case QUEST_TYPE_RAID_25:
             return difficulty & RAID_DIFFICULTY_MASK_25MAN;
         default:
             break;
     }
     return false;
 }
References QUEST_TYPE_RAID, QUEST_TYPE_RAID_10, QUEST_TYPE_RAID_25, RAID_DIFFICULTY_MASK_25MAN, and Type.
Referenced by IsAllowedInRaid().
IsRepeatable()
bool Quest::IsRepeatable () const inline
Definition at line 278 of file QuestDef.h.
 { return SpecialFlags & QUEST_SPECIAL_FLAGS_REPEATABLE; }
References QUEST_SPECIAL_FLAGS_REPEATABLE, and SpecialFlags.
Referenced by Player::CanCompleteQuest(), npc_wg_quest_giver::GetDialogStatus(), Player::GetQuestDialogStatus(), Player::GetQuestRewardStatus(), IsSeasonal(), Player::RewardReputation(), and Player::SatisfyQuestExclusiveGroup().
IsSeasonal()
bool Quest::IsSeasonal () const inline
Definition at line 285 of file QuestDef.h.
 { return (ZoneOrSort == -QUEST_SORT_SEASONAL || ZoneOrSort == -QUEST_SORT_SPECIAL || ZoneOrSort == -QUEST_SORT_LUNAR_FESTIVAL || ZoneOrSort == -QUEST_SORT_MIDSUMMER || ZoneOrSort == -QUEST_SORT_BREWFEST || ZoneOrSort == -QUEST_SORT_LOVE_IS_IN_THE_AIR || ZoneOrSort == -QUEST_SORT_NOBLEGARDEN) && !IsRepeatable(); }
References IsRepeatable(), QUEST_SORT_BREWFEST, QUEST_SORT_LOVE_IS_IN_THE_AIR, QUEST_SORT_LUNAR_FESTIVAL, QUEST_SORT_MIDSUMMER, QUEST_SORT_NOBLEGARDEN, QUEST_SORT_SEASONAL, QUEST_SORT_SPECIAL, and ZoneOrSort.
Referenced by Player::CanCompleteQuest(), Player::GetQuestRewardStatus(), Player::RewardQuest(), Player::SatisfyQuestExclusiveGroup(), Player::SatisfyQuestPreviousQuest(), and Player::SatisfyQuestSeasonal().
IsWeekly()
bool Quest::IsWeekly () const inline
Definition at line 283 of file QuestDef.h.
 { return Flags & QUEST_FLAGS_WEEKLY; }
References Flags, and QUEST_FLAGS_WEEKLY.
Referenced by Player::RewardQuest(), Player::RewardReputation(), Player::SatisfyQuestWeek(), and npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI().
LoadQuestDetails()
void Quest::LoadQuestDetails (Field * fields)
Definition at line 136 of file QuestDef.cpp.
 {
     for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
         DetailsEmote[i] = fields[1 + i].GetUInt16();
     for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
         DetailsEmoteDelay[i] = fields[5 + i].GetUInt32();
 }
References DetailsEmote, DetailsEmoteDelay, and QUEST_EMOTE_COUNT.
LoadQuestOfferReward()
void Quest::LoadQuestOfferReward (Field * fields)
Definition at line 152 of file QuestDef.cpp.
 {
     for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
         OfferRewardEmote[i] = fields[1 + i].GetUInt16();
     for (int i = 0; i < QUEST_EMOTE_COUNT; ++i)
         OfferRewardEmoteDelay[i] = fields[5 + i].GetUInt32();
     OfferRewardText = fields[9].GetString();
 }
References Field::GetString(), OfferRewardEmote, OfferRewardEmoteDelay, OfferRewardText, and QUEST_EMOTE_COUNT.
LoadQuestRequestItems()
void Quest::LoadQuestRequestItems (Field * fields)
Definition at line 145 of file QuestDef.cpp.
 {
     EmoteOnComplete = fields[1].GetUInt16();
     EmoteOnIncomplete = fields[2].GetUInt16();
     RequestItemsText = fields[3].GetString();
 }
References EmoteOnComplete, EmoteOnIncomplete, Field::GetString(), Field::GetUInt16(), and RequestItemsText.
LoadQuestTemplateAddon()
void Quest::LoadQuestTemplateAddon (Field * fields)
Definition at line 163 of file QuestDef.cpp.
 {
     MaxLevel = fields[1].GetUInt8();
     RequiredClasses = fields[2].GetUInt32();
     SourceSpellid = fields[3].GetUInt32();
     PrevQuestId = fields[4].GetInt32();
     NextQuestId = fields[5].GetUInt32();
     ExclusiveGroup = fields[6].GetInt32();
     RewardMailTemplateId = fields[7].GetUInt32();
     RewardMailDelay = fields[8].GetUInt32();
     RequiredSkillId = fields[9].GetUInt16();
     RequiredSkillPoints = fields[10].GetUInt16();
     RequiredMinRepFaction = fields[11].GetUInt16();
     RequiredMaxRepFaction = fields[12].GetUInt16();
     RequiredMinRepValue = fields[13].GetInt32();
     RequiredMaxRepValue = fields[14].GetInt32();
     StartItemCount = fields[15].GetUInt8();
     RewardMailSenderEntry = fields[16].GetUInt32();
     SpecialFlags = fields[17].GetUInt8();
     if (SpecialFlags & QUEST_SPECIAL_FLAGS_AUTO_ACCEPT)
         Flags |= QUEST_FLAGS_AUTO_ACCEPT;
 }
References ExclusiveGroup, Flags, Field::GetInt32(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), MaxLevel, NextQuestId, PrevQuestId, QUEST_FLAGS_AUTO_ACCEPT, QUEST_SPECIAL_FLAGS_AUTO_ACCEPT, RequiredClasses, RequiredMaxRepFaction, RequiredMaxRepValue, RequiredMinRepFaction, RequiredMinRepValue, RequiredSkillId, RequiredSkillPoints, RewardMailDelay, RewardMailSenderEntry, RewardMailTemplateId, SourceSpellid, SpecialFlags, and StartItemCount.
SetEventIdForQuest()
void Quest::SetEventIdForQuest (uint16 eventId) inline
Definition at line 326 of file QuestDef.h.
 { _eventIdForQuest = eventId; }
References _eventIdForQuest.
Referenced by GameEventMgr::LoadFromDB().
SetFlag()
void Quest::SetFlag (uint32 flag) inline
Definition at line 217 of file QuestDef.h.
 { Flags |= flag; }
References Flags.
SetSpecialFlag()
void Quest::SetSpecialFlag (uint32 flag) inline
Definition at line 220 of file QuestDef.h.
 { SpecialFlags |= flag; }
References SpecialFlags.
Referenced by ObjectMgr::LoadQuests().
XPValue()
uint32 Quest::XPValue (Player * player) const
Definition at line 187 of file QuestDef.cpp.
 {
     if (player)
     {
         int32 quest_level = (Level == -1 ? player->getLevel() : Level);
         const QuestXPEntry* xpentry = sQuestXPStore.LookupEntry(quest_level);
         if (!xpentry)
             return 0;
         int32 diffFactor = 2 * (quest_level - player->getLevel()) + 20;
         if (diffFactor < 1)
             diffFactor = 1;
         else if (diffFactor > 10)
             diffFactor = 10;
         uint32 xp = diffFactor * xpentry->Exp[RewardXPDifficulty] / 10;
         if (xp <= 100)
             xp = 5 * ((xp + 2) / 5);
         else if (xp <= 500)
             xp = 10 * ((xp + 5) / 10);
         else if (xp <= 1000)
             xp = 25 * ((xp + 12) / 25);
         else
             xp = 50 * ((xp + 25) / 50);
         return xp;
     }
     return 0;
 }
References QuestXPEntry::Exp, Unit::getLevel(), Level, RewardXPDifficulty, and sQuestXPStore.
Referenced by WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
Friends And Related Function Documentation
ObjectMgr
friend class ObjectMgr friend
Definition at line 206 of file QuestDef.h.
Member Data Documentation
_eventIdForQuest
uint16 Quest::_eventIdForQuest private
Definition at line 336 of file QuestDef.h.
Referenced by GetEventIdForQuest(), Quest(), and SetEventIdForQuest().
_reqCreatureOrGOcount
uint32 Quest::_reqCreatureOrGOcount private
Definition at line 332 of file QuestDef.h.
Referenced by GetReqCreatureOrGOcount(), and Quest().
_reqItemsCount
uint32 Quest::_reqItemsCount private
Definition at line 331 of file QuestDef.h.
Referenced by GetReqItemsCount(), and Quest().
_rewChoiceItemsCount
uint32 Quest::_rewChoiceItemsCount private
Definition at line 333 of file QuestDef.h.
Referenced by GetRewChoiceItemsCount(), and Quest().
_rewItemsCount
uint32 Quest::_rewItemsCount private
Definition at line 334 of file QuestDef.h.
Referenced by GetRewItemsCount(), and Quest().
AllowableRaces
uint32 Quest::AllowableRaces protected
Definition at line 346 of file QuestDef.h.
Referenced by GetAllowableRaces(), ObjectMgr::LoadQuests(), and Quest().
AreaDescription
std::string Quest::AreaDescription protected
Definition at line 366 of file QuestDef.h.
Referenced by GetAreaDescription(), and Quest().
CompletedText
std::string Quest::CompletedText protected
Definition at line 367 of file QuestDef.h.
Referenced by GetCompletedText(), and Quest().
Details
std::string Quest::Details protected
Definition at line 362 of file QuestDef.h.
Referenced by GetDetails(), and Quest().
DetailsEmote
uint32 Quest::DetailsEmote[QUEST_EMOTE_COUNT]
Definition at line 308 of file QuestDef.h.
Referenced by LoadQuestDetails(), Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
DetailsEmoteDelay
uint32 Quest::DetailsEmoteDelay[QUEST_EMOTE_COUNT]
Definition at line 309 of file QuestDef.h.
Referenced by LoadQuestDetails(), Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
EmoteOnComplete
uint32 Quest::EmoteOnComplete protected
Definition at line 380 of file QuestDef.h.
Referenced by GetCompleteEmote(), LoadQuestRequestItems(), and Quest().
EmoteOnIncomplete
uint32 Quest::EmoteOnIncomplete protected
Definition at line 379 of file QuestDef.h.
Referenced by GetIncompleteEmote(), LoadQuestRequestItems(), and Quest().
ExclusiveGroup
int32 Quest::ExclusiveGroup = 0 protected
Definition at line 388 of file QuestDef.h.
Referenced by GetExclusiveGroup(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
Flags
uint32 Quest::Flags protected
Definition at line 353 of file QuestDef.h.
Referenced by GetFlags(), HasFlag(), IsAutoAccept(), IsDaily(), IsDailyOrWeekly(), IsWeekly(), ObjectMgr::LoadQuests(), LoadQuestTemplateAddon(), Quest(), and SetFlag().
Id
uint32 Quest::Id protected
Definition at line 340 of file QuestDef.h.
Referenced by GetQuestId(), and Quest().
ItemDrop
uint32 Quest::ItemDrop[QUEST_SOURCE_ITEM_IDS_COUNT]
Definition at line 297 of file QuestDef.h.
Referenced by Player::HasQuestForItem(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), and PlayerMenu::SendQuestQueryResponse().
ItemDropQuantity
uint32 Quest::ItemDropQuantity[QUEST_SOURCE_ITEM_IDS_COUNT]
Definition at line 298 of file QuestDef.h.
Referenced by Player::HasQuestForItem(), ObjectMgr::LoadQuests(), Quest(), and Player::RewardQuest().
Level
int32 Quest::Level protected
Definition at line 344 of file QuestDef.h.
Referenced by GetQuestLevel(), Quest(), and XPValue().
MaxLevel
uint32 Quest::MaxLevel = 0 protected
Definition at line 383 of file QuestDef.h.
Referenced by GetMaxLevel(), and LoadQuestTemplateAddon().
Method
uint32 Quest::Method protected
Definition at line 341 of file QuestDef.h.
Referenced by GetQuestMethod(), and Quest().
MinLevel
uint32 Quest::MinLevel protected
Definition at line 343 of file QuestDef.h.
Referenced by GetMinLevel(), and Quest().
NextQuestId
uint32 Quest::NextQuestId = 0 protected
Definition at line 387 of file QuestDef.h.
Referenced by GetNextQuestId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
Objectives
std::string Quest::Objectives protected
Definition at line 363 of file QuestDef.h.
Referenced by GetObjectives(), and Quest().
ObjectiveText
std::string Quest::ObjectiveText[QUEST_OBJECTIVES_COUNT]
Definition at line 294 of file QuestDef.h.
Referenced by InitializeQueryData(), Quest(), and PlayerMenu::SendQuestQueryResponse().
OfferRewardEmote
uint32 Quest::OfferRewardEmote[QUEST_EMOTE_COUNT]
Definition at line 310 of file QuestDef.h.
Referenced by LoadQuestOfferReward(), Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardEmoteDelay
uint32 Quest::OfferRewardEmoteDelay[QUEST_EMOTE_COUNT]
Definition at line 311 of file QuestDef.h.
Referenced by LoadQuestOfferReward(), Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardText
std::string Quest::OfferRewardText protected
Definition at line 364 of file QuestDef.h.
Referenced by GetOfferRewardText(), and LoadQuestOfferReward().
POIContinent
uint32 Quest::POIContinent protected
Definition at line 375 of file QuestDef.h.
Referenced by GetPOIContinent(), and Quest().
POIPriority
uint32 Quest::POIPriority protected
Definition at line 378 of file QuestDef.h.
Referenced by GetPointOpt(), and Quest().
POIx
float Quest::POIx protected
Definition at line 376 of file QuestDef.h.
Referenced by GetPOIx(), and Quest().
POIy
float Quest::POIy protected
Definition at line 377 of file QuestDef.h.
Referenced by GetPOIy(), and Quest().
prevChainQuests
PrevChainQuests Quest::prevChainQuests
Definition at line 321 of file QuestDef.h.
Referenced by Player::SatisfyQuestPrevChain().
PrevQuestId
int32 Quest::PrevQuestId = 0 protected
Definition at line 386 of file QuestDef.h.
Referenced by GetPrevQuestId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
prevQuests
PrevQuests Quest::prevQuests
Definition at line 319 of file QuestDef.h.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestPreviousQuest().
queryData
WorldPacket Quest::queryData
Definition at line 323 of file QuestDef.h.
Referenced by InitializeQueryData().
RequestItemsText
std::string Quest::RequestItemsText protected
Definition at line 365 of file QuestDef.h.
Referenced by GetRequestItemsText(), and LoadQuestRequestItems().
RequiredClasses
uint32 Quest::RequiredClasses = 0 protected
Definition at line 384 of file QuestDef.h.
Referenced by GetRequiredClasses(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredFactionId1
uint32 Quest::RequiredFactionId1 protected
Definition at line 347 of file QuestDef.h.
Referenced by GetRepObjectiveFaction(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionId2
uint32 Quest::RequiredFactionId2 protected
Definition at line 349 of file QuestDef.h.
Referenced by GetRepObjectiveFaction2(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionValue1
int32 Quest::RequiredFactionValue1 protected
Definition at line 348 of file QuestDef.h.
Referenced by GetRepObjectiveValue(), ObjectMgr::LoadQuests(), and Quest().
RequiredFactionValue2
int32 Quest::RequiredFactionValue2 protected
Definition at line 350 of file QuestDef.h.
Referenced by GetRepObjectiveValue2(), ObjectMgr::LoadQuests(), and Quest().
RequiredItemCount
uint32 Quest::RequiredItemCount[QUEST_ITEM_OBJECTIVES_COUNT]
Definition at line 296 of file QuestDef.h.
Referenced by Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForItem(), InitializeQueryData(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerMenu::SendQuestQueryResponse().
RequiredItemId
uint32 Quest::RequiredItemId[QUEST_ITEM_OBJECTIVES_COUNT]
Definition at line 295 of file QuestDef.h.
Referenced by Player::AddQuestAndCheckCompletion(), Player::AdjustQuestReqItemCount(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForItem(), InitializeQueryData(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestQueryResponse(), and Player::TakeQuestSourceItem().
RequiredMaxRepFaction
uint32 Quest::RequiredMaxRepFaction = 0 protected
Definition at line 395 of file QuestDef.h.
Referenced by GetRequiredMaxRepFaction(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMaxRepValue
int32 Quest::RequiredMaxRepValue = 0 protected
Definition at line 396 of file QuestDef.h.
Referenced by GetRequiredMaxRepValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMinRepFaction
uint32 Quest::RequiredMinRepFaction = 0 protected
Definition at line 393 of file QuestDef.h.
Referenced by GetRequiredMinRepFaction(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredMinRepValue
int32 Quest::RequiredMinRepValue = 0 protected
Definition at line 394 of file QuestDef.h.
Referenced by GetRequiredMinRepValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredNpcOrGo
int32 Quest::RequiredNpcOrGo[QUEST_OBJECTIVES_COUNT]
Definition at line 299 of file QuestDef.h.
Referenced by Player::CanCompleteQuest(), Player::GetReqKillOrCastCurrentCount(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForGO(), InitializeQueryData(), ConditionMgr::isConditionTypeValid(), Player::KillCreditGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), go_dragonflayer_cage::OnGossipHello(), Quest(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestUpdateAddCreatureOrGo(), npc_jungle_punch_target::npc_jungle_punch_targetAI::SpellHit(), and Player::TalkedToCreature().
RequiredNpcOrGoCount
uint32 Quest::RequiredNpcOrGoCount[QUEST_OBJECTIVES_COUNT]
Definition at line 300 of file QuestDef.h.
Referenced by Player::CanCompleteQuest(), quest_commandscript::HandleQuestComplete(), Player::HasQuestForGO(), InitializeQueryData(), ConditionMgr::isConditionTypeValid(), Player::KillCreditGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), Quest(), PlayerMenu::SendQuestQueryResponse(), Player::SendQuestUpdateAddCreatureOrGo(), and Player::TalkedToCreature().
RequiredPlayerKills
uint32 Quest::RequiredPlayerKills protected
Definition at line 355 of file QuestDef.h.
Referenced by GetPlayersSlain(), ObjectMgr::LoadQuests(), and Quest().
RequiredSkillId
uint32 Quest::RequiredSkillId = 0 protected
Definition at line 391 of file QuestDef.h.
Referenced by GetRequiredSkill(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RequiredSkillPoints
uint32 Quest::RequiredSkillPoints = 0 protected
Definition at line 392 of file QuestDef.h.
Referenced by GetRequiredSkillValue(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardArenaPoints
int32 Quest::RewardArenaPoints protected
Definition at line 357 of file QuestDef.h.
Referenced by GetRewArenaPoints(), and Quest().
RewardBonusMoney
uint32 Quest::RewardBonusMoney protected
Definition at line 372 of file QuestDef.h.
Referenced by GetRewMoneyMaxLevel(), and Quest().
RewardChoiceItemCount
uint32 Quest::RewardChoiceItemCount[QUEST_REWARD_CHOICES_COUNT]
Definition at line 302 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardChoiceItemId
uint32 Quest::RewardChoiceItemId[QUEST_REWARD_CHOICES_COUNT]
Definition at line 301 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardDisplaySpell
uint32 Quest::RewardDisplaySpell protected
Definition at line 373 of file QuestDef.h.
Referenced by GetRewSpell(), ObjectMgr::LoadQuests(), and Quest().
RewardFactionId
uint32 Quest::RewardFactionId[QUEST_REPUTATIONS_COUNT]
Definition at line 305 of file QuestDef.h.
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardFactionValueId
int32 Quest::RewardFactionValueId[QUEST_REPUTATIONS_COUNT]
Definition at line 306 of file QuestDef.h.
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardFactionValueIdOverride
int32 Quest::RewardFactionValueIdOverride[QUEST_REPUTATIONS_COUNT]
Definition at line 307 of file QuestDef.h.
Referenced by InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardHonor
uint32 Quest::RewardHonor protected
Definition at line 368 of file QuestDef.h.
Referenced by GetRewHonorAddition(), and Quest().
RewardItemId
uint32 Quest::RewardItemId[QUEST_REWARDS_COUNT]
Definition at line 303 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardItemIdCount
uint32 Quest::RewardItemIdCount[QUEST_REWARDS_COUNT]
Definition at line 304 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), InitializeQueryData(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestQueryResponse().
RewardKillHonor
float Quest::RewardKillHonor protected
Definition at line 369 of file QuestDef.h.
Referenced by GetRewHonorMultiplier(), and Quest().
RewardMailDelay
uint32 Quest::RewardMailDelay = 0 protected
Definition at line 390 of file QuestDef.h.
Referenced by GetRewMailDelaySecs(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMailSenderEntry
uint32 Quest::RewardMailSenderEntry = 0 protected
Definition at line 398 of file QuestDef.h.
Referenced by GetRewMailSenderEntry(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMailTemplateId
uint32 Quest::RewardMailTemplateId = 0 protected
Definition at line 389 of file QuestDef.h.
Referenced by GetRewMailTemplateId(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
RewardMoney
int32 Quest::RewardMoney protected
Definition at line 370 of file QuestDef.h.
Referenced by GetRewOrReqMoney(), and Quest().
RewardMoneyDifficulty
uint32 Quest::RewardMoneyDifficulty protected
Definition at line 371 of file QuestDef.h.
Referenced by GetRewOrReqMoney(), and Quest().
RewardNextQuest
uint32 Quest::RewardNextQuest protected
Definition at line 358 of file QuestDef.h.
Referenced by GetNextQuestInChain(), ObjectMgr::LoadQuests(), and Quest().
RewardSpell
int32 Quest::RewardSpell protected
Definition at line 374 of file QuestDef.h.
Referenced by GetRewSpellCast(), ObjectMgr::LoadQuests(), and Quest().
RewardTalents
uint32 Quest::RewardTalents protected
Definition at line 356 of file QuestDef.h.
Referenced by GetBonusTalents(), and Quest().
RewardTitleId
uint32 Quest::RewardTitleId protected
Definition at line 354 of file QuestDef.h.
Referenced by GetCharTitleId(), ObjectMgr::LoadQuests(), and Quest().
RewardXPDifficulty
uint32 Quest::RewardXPDifficulty protected
Definition at line 359 of file QuestDef.h.
Referenced by GetXPId(), Quest(), and XPValue().
SourceSpellid
uint32 Quest::SourceSpellid = 0 protected
Definition at line 385 of file QuestDef.h.
Referenced by GetSrcSpell(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
SpecialFlags
uint32 Quest::SpecialFlags = 0 protected
Definition at line 399 of file QuestDef.h.
Referenced by HasSpecialFlag(), IsDFQuest(), IsMonthly(), IsRepeatable(), ObjectMgr::LoadQuests(), LoadQuestTemplateAddon(), and SetSpecialFlag().
StartItem
uint32 Quest::StartItem protected
Definition at line 360 of file QuestDef.h.
Referenced by GetSrcItemId(), ObjectMgr::LoadQuests(), and Quest().
StartItemCount
uint32 Quest::StartItemCount = 0 protected
Definition at line 397 of file QuestDef.h.
Referenced by GetSrcItemCount(), ObjectMgr::LoadQuests(), and LoadQuestTemplateAddon().
SuggestedPlayers
uint32 Quest::SuggestedPlayers protected
Definition at line 351 of file QuestDef.h.
Referenced by GetSuggestedPlayers(), and Quest().
TimeAllowed
uint32 Quest::TimeAllowed protected
Definition at line 352 of file QuestDef.h.
Referenced by GetTimeAllowed(), ObjectMgr::LoadQuests(), and Quest().
Title
std::string Quest::Title protected
Definition at line 361 of file QuestDef.h.
Referenced by GetTitle(), and Quest().
Type
uint32 Quest::Type protected
Definition at line 345 of file QuestDef.h.
Referenced by GetType(), IsPVPQuest(), IsRaidQuest(), and Quest().
ZoneOrSort
int32 Quest::ZoneOrSort protected
Definition at line 342 of file QuestDef.h.
Referenced by GetZoneOrSort(), IsSeasonal(), ObjectMgr::LoadQuests(), and Quest().
The documentation for this class was generated from the following files:
src/server/game/Quests/QuestDef.h
src/server/game/Quests/QuestDef.cpp