Azerotcore-wotlk: G3D::Spinlock Class Reference
G3D::Spinlock Class Reference
A mutual exclusion lock that busy-waits when locking.
#include <GMutex.h>
Public Member Functions
Spinlock ()
bool lock ()
void unlock ()
Private Attributes
AtomicInt32 x
Detailed Description
A mutual exclusion lock that busy-waits when locking.
On a machine with one (significant) thread per processor core, a Spinlock may be substantially faster than a mutex.
See also
G3D::GThread, G3D::GMutex, G3D::AtomicInt32
Definition at line 36 of file GMutex.h.
Constructor & Destructor Documentation
Spinlock()
G3D::Spinlock::Spinlock () inline
Definition at line 43 of file GMutex.h.
 : x(0) {}
Member Function Documentation
lock()
bool G3D::Spinlock::lock () inline
Busy waits until the lock is unlocked, then locks it exclusively. Returns true if the lock succeeded on the first try (indicating no contention).
Unlike a G3D::GMutex, a single thread cannot re-enter Spinlock::lock() that it already locked.
Definition at line 52 of file GMutex.h.
{
         bool first = true;
         while (x.compareAndSet(0, 1) == 1) {
             first = false;
 #           ifdef G3D_WINDOWS
                 Sleep(0);
 #           else
                 usleep(0);
 #           endif
         }
         return first;
     }
References G3D::AtomicInt32::compareAndSet(), detail::first(), and x.
Referenced by G3D::Random::generate(), and G3D::BufferPool::lock().
unlock()
void G3D::Spinlock::unlock () inline
Definition at line 65 of file GMutex.h.
{
         x.compareAndSet(1, 0);
     }
References G3D::AtomicInt32::compareAndSet(), and x.
Referenced by G3D::Random::generate(), and G3D::BufferPool::unlock().
Member Data Documentation
x
AtomicInt32 G3D::Spinlock::x private
Definition at line 39 of file GMutex.h.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/GMutex.h