Azerotcore-wotlk: deps/mysqllite/mysys/my_malloc.c File Reference
my_malloc.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <m_string.h>
Functions
void * my_malloc (size_t size, myf my_flags)
void * my_realloc (void *oldpoint, size_t size, myf my_flags)
wrapper around realloc()
void my_free (void *ptr)
void * my_memdup (const void *from, size_t length, myf my_flags)
char * my_strdup (const char *from, myf my_flags)
char * my_strndup (const char *from, size_t length, myf my_flags)
Function Documentation
my_free()
void my_free (void * ptr)
Free memory allocated with my_malloc.
Remarks
Relies on free being able to handle a NULL argument.
Parameters
ptr Pointer to the memory allocated by my_malloc.
Definition at line 124 of file my_malloc.c.
 {
   DBUG_ENTER("my_free");
   DBUG_PRINT("my",("ptr: %p", ptr));
   free(ptr);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, and ptr().
Referenced by _lf_dynarray_lvalue(), add_init_command(), bitmap_free(), CLI_MYSQL_REAL_CONNECT(), cli_stmt_execute(), cli_use_result(), close_cached_file(), default_local_infile_end(), delete_dynamic(), delete_queue(), delete_tree_element(), dynstr_free(), end_io_cache(), end_key_cache(), fini_one_value(), flush_key_blocks_int(), free_root(), free_rows(), free_tmpdir(), handle_local_infile(), init_key_cache(), init_one_value(), initialize_bucket(), inline_mysql_file_fclose(), inline_mysql_file_fopen(), lf_alloc_destroy(), lf_hash_destroy(), list_free(), load_env_plugins(), my_close(), my_dir(), my_dirend(), my_error_register(), my_error_unregister(), my_error_unregister_all(), my_fclose(), my_free_open_file_info(), my_read_charset_file(), my_realloc(), my_stat(), my_string_ptr_sort(), mysql_change_user(), mysql_close(), mysql_close_free(), mysql_close_free_options(), mysql_free_result(), mysql_options(), mysql_read_default_options(), mysql_select_db(), mysql_stmt_close(), mysql_store_result(), net_end(), net_real_write(), open_cached_file(), recursive_free(), reset_root_defaults(), safe_hash_entry_free(), safe_hash_set(), setval(), thr_end_alarm(), tree_delete(), vio_delete(), and vio_reset().
my_malloc()
void* my_malloc (size_t size, myf my_flags)
Allocate a sized block of memory.
Parameters
size The size of the memory block in bytes.
flags Failure action modifiers (bitmasks).
Returns
A pointer to the allocated memory block, or NULL on failure.
Definition at line 28 of file my_malloc.c.
 {
   void* point;
   DBUG_ENTER("my_malloc");
   DBUG_PRINT("my",("size: %lu  my_flags: %d", (ulong) size, my_flags));
   /* Safety */
   if (!size)
     size=1;
   point= malloc(size);
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     free(point);
                     point= NULL;
                   });
   if (point == NULL)
   {
     my_errno=errno;
     if (my_flags & MY_FAE)
       error_handler_hook=fatal_error_handler_hook;
     if (my_flags & (MY_FAE+MY_WME))
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG+ME_NOREFRESH),size);
     DBUG_EXECUTE_IF("simulate_out_of_memory",
                     DBUG_SET("-d,simulate_out_of_memory"););
     if (my_flags & MY_FAE)
       exit(1);
   }
   else if (my_flags & MY_ZEROFILL)
     bzero(point, size);
   DBUG_PRINT("exit",("ptr: %p", point));
   DBUG_RETURN(point);
 }
References bzero, DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, DBUG_SET, EE_OUTOFMEMORY, errno, error_handler_hook, fatal_error_handler_hook, ME_BELL, ME_NOREFRESH, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_WME, MY_ZEROFILL, MYF, and NULL.
Referenced by _lf_alloc_new(), _lf_dynarray_lvalue(), add_init_command(), alloc_dynamic(), alloc_root(), allocate_dynamic(), bitmap_init(), cache_remove_open_tmp(), cli_read_rows(), cli_use_result(), default_local_infile_init(), flush_key_blocks_int(), handle_local_infile(), init_alloc_root(), init_dynamic_array2(), init_dynamic_string(), init_io_cache(), init_key_cache(), init_queue(), initialize_bucket(), inline_mysql_file_fopen(), list_cons(), my_dir(), my_error_register(), my_memdup(), my_multi_malloc(), my_net_init(), my_read_charset_file(), my_realloc(), my_set_max_open_files(), my_stat(), my_strdup(), my_string_ptr_sort(), my_strndup(), mysql_init(), mysql_list_fields(), mysql_stmt_init(), mysql_stmt_result_metadata(), mysql_store_result(), net_real_write(), reset_root_defaults(), safe_hash_set(), thr_alarm(), tree_insert(), vio_init(), and vio_new().
my_memdup()
void* my_memdup (const void * from, size_t length, myf my_flags)
Definition at line 133 of file my_malloc.c.
 {
   void *ptr;
   if ((ptr= my_malloc(length,my_flags)) != 0)
     memcpy(ptr, from, length);
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by cli_stmt_execute().
my_realloc()
void* my_realloc (void * oldpoint, size_t size, myf my_flags)
wrapper around realloc()
Parameters
oldpoint pointer to currently allocated area
size new size requested, must be >0
my_flags flags
Note
if size==0 realloc() may return NULL; my_realloc() treats this as an error which is not the intention of realloc()
Definition at line 74 of file my_malloc.c.
 {
   void *point;
   DBUG_ENTER("my_realloc");
   DBUG_PRINT("my",("ptr: %p  size: %lu  my_flags: %d", oldpoint,
                    (ulong) size, my_flags));
   DBUG_ASSERT(size > 0);
   if (!oldpoint && (my_flags & MY_ALLOW_ZERO_PTR))
     DBUG_RETURN(my_malloc(size, my_flags));
 #ifdef USE_HALLOC
   if (!(point = malloc(size)))
   {
     if (my_flags & MY_FREE_ON_ERROR)
       my_free(oldpoint);
     if (my_flags & MY_HOLD_ON_ERROR)
       DBUG_RETURN(oldpoint);
     my_errno=errno;
     if (my_flags & MY_FAE+MY_WME)
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG),size);
   }
   else
   {
     memcpy(point,oldpoint,size);
     free(oldpoint);
   }
 #else
   if ((point= realloc(oldpoint, size)) == NULL)
   {
     if (my_flags & MY_FREE_ON_ERROR)
       my_free(oldpoint);
     if (my_flags & MY_HOLD_ON_ERROR)
       DBUG_RETURN(oldpoint);
     my_errno=errno;
     if (my_flags & (MY_FAE+MY_WME))
       my_error(EE_OUTOFMEMORY, MYF(ME_BELL+ME_WAITTANG), size);
   }
 #endif
   DBUG_PRINT("exit",("ptr: %p", point));
   DBUG_RETURN(point);
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_OUTOFMEMORY, errno, ME_BELL, ME_WAITTANG, memcpy, MY_ALLOW_ZERO_PTR, my_errno, my_error(), MY_FAE, my_free(), MY_FREE_ON_ERROR, MY_HOLD_ON_ERROR, my_malloc(), MY_WME, MYF, and NULL.
Referenced by alloc_dynamic(), allocate_dynamic(), dynstr_append_mem(), dynstr_realloc(), dynstr_set(), freeze_size(), net_realloc(), and resize_queue().
my_strdup()
char* my_strdup (const char * from, myf my_flags)
Definition at line 142 of file my_malloc.c.
 {
   char *ptr;
   size_t length= strlen(from)+1;
   if ((ptr= (char*) my_malloc(length, my_flags)))
     memcpy(ptr, from, length);
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by add_init_command(), CLI_MYSQL_REAL_CONNECT(), get_tty_password(), init_one_value(), load_env_plugins(), my_fdopen(), my_fopen(), my_register_filename(), mysql_autodetect_character_set(), mysql_change_user(), mysql_init_character_set(), mysql_options(), mysql_read_default_options(), mysql_select_db(), open_cached_file(), send_client_reply_packet(), and setval().
my_strndup()
char* my_strndup (const char * from, size_t length, myf my_flags)
Definition at line 152 of file my_malloc.c.
 {
   char *ptr;
   if ((ptr= (char*) my_malloc(length+1, my_flags)))
   {
     memcpy(ptr, from, length);
     ptr[length]= 0;
   }
   return ptr;
 }
References G3D::length(), memcpy, my_malloc(), and ptr().
Referenced by init_tmpdir().