Azerotcore-wotlk: npc_mc_core_hound::npc_mc_core_houndAI Struct Reference
npc_mc_core_hound::npc_mc_core_houndAI Struct Reference
Public Member Functions
npc_mc_core_houndAI (Creature *creature)
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
InstanceScript * instance
uint32 serratedBiteTimer
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 45 of file molten_core.cpp.
Constructor & Destructor Documentation
npc_mc_core_houndAI()
npc_mc_core_hound::npc_mc_core_houndAI::npc_mc_core_houndAI (Creature * creature) inline
Definition at line 47 of file molten_core.cpp.
                                                 :
             CreatureAI(creature),
             instance(creature->GetInstanceScript()),
             serratedBiteTimer(3000)
         {
         }
Member Function Documentation
DamageTaken()
void npc_mc_core_hound::npc_mc_core_houndAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 59 of file molten_core.cpp.
         {
             // Prevent receiving any extra damage if Hound is playing dead
             if (me->HasAura(SPELL_PLAY_DEAD))
             {
                 damage = 0;
                 return;
             }
             else if (me->GetHealth() <= damage)
             {
                 damage = 0;
                 Talk(EMOTE_SMOLDERING);
                 DoCastSelf(SPELL_PLAY_DEAD);
             }
         }
References UnitAI::DoCastSelf(), EMOTE_SMOLDERING, Unit::GetHealth(), Unit::HasAura(), CreatureAI::me, SPELL_PLAY_DEAD, and CreatureAI::Talk().
Reset()
void npc_mc_core_hound::npc_mc_core_houndAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 54 of file molten_core.cpp.
         {
             serratedBiteTimer = 3000;
         }
References serratedBiteTimer.
UpdateAI()
void npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI (uint32 diff) inline override virtual
Implements UnitAI.
Definition at line 75 of file molten_core.cpp.
         {
             if (!UpdateVictim())
             {
                 return;
             }
             if (me->HasUnitState(UNIT_STATE_CASTING) || me->HasAura(SPELL_PLAY_DEAD))
             {
                 return;
             }
             if (serratedBiteTimer <= diff)
             {
                 DoCastVictim(SPELL_SERRATED_BITE);
                 serratedBiteTimer = urand(5000, 6000);
             }
             else
             {
                 serratedBiteTimer -= diff;
             }
             DoMeleeAttackIfReady();
         }
References UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), Unit::HasAura(), Unit::HasUnitState(), CreatureAI::me, serratedBiteTimer, SPELL_PLAY_DEAD, SPELL_SERRATED_BITE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
instance
InstanceScript* npc_mc_core_hound::npc_mc_core_houndAI::instance private
Definition at line 101 of file molten_core.cpp.
serratedBiteTimer
uint32 npc_mc_core_hound::npc_mc_core_houndAI::serratedBiteTimer private
Definition at line 102 of file molten_core.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/molten_core.cpp