Azerotcore-wotlk: npc_oculus_drakegiver Class Reference
npc_oculus_drakegiver Class Reference
Classes
struct npc_oculus_drakegiverAI
Public Member Functions
npc_oculus_drakegiver ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipHello (Player *player, Creature *creature) override
void StoreEssence (Player *player, uint32 itemId)
void RemoveEssence (Player *player, uint32 itemId)
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Public Attributes
std::unordered_map< ObjectGuid, bool > openedMenu
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 75 of file oculus.cpp.
Constructor & Destructor Documentation
npc_oculus_drakegiver()
npc_oculus_drakegiver::npc_oculus_drakegiver () inline
Definition at line 80 of file oculus.cpp.
 : CreatureScript("npc_oculus_drakegiver") { }
Member Function Documentation
GetAI()
CreatureAI* npc_oculus_drakegiver::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 82 of file oculus.cpp.
     {
         return GetOculusAI<npc_oculus_drakegiverAI>(creature);
     }
OnGossipHello()
bool npc_oculus_drakegiver::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 168 of file oculus.cpp.
     {
         if(creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if(creature->GetInstanceScript()->GetData(DATA_DRAKOS) == DONE)
         {
             switch (creature->GetEntry())
             {
             case NPC_VERDISA:
                 AddGossipItemFor(player, 9573, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 if (player->HasItemCount(ITEM_AMBER_ESSENCE))
                 {
                     AddGossipItemFor(player, 9573, 2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 }
                 else if (player->HasItemCount(ITEM_RUBY_ESSENCE))
                 {
                     AddGossipItemFor(player, 9573, 3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 }
                 else if (!player->HasItemCount(ITEM_EMERALD_ESSENCE))
                 {
                     AddGossipItemFor(player, 9573, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 }
                 AddGossipItemFor(player, 9573, 4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                 SendGossipMenuFor(player, GOSSIP_TEXTID_VERDISA1, creature->GetGUID());
                 break;
             case NPC_BELGARISTRASZ:
                 if (HAS_ESSENCE(player))
                 {
                     openedMenu[player->GetGUID()] = true;
                 }
                 if (!openedMenu[player->GetGUID()])
                 {
                     AddGossipItemFor(player, 9708, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                     SendGossipMenuFor(player, GOSSIP_TEXTID_DRAKES, creature->GetGUID());
                 }
                 else
                 {
                     OnGossipSelect(player, creature, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 }
                 break;
             case NPC_ETERNOS:
                 AddGossipItemFor(player, 9574, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 if (player->HasItemCount(ITEM_EMERALD_ESSENCE))
                 {
                     AddGossipItemFor(player, 9574, 2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 }
                 else if (player->HasItemCount(ITEM_RUBY_ESSENCE))
                 {
                     AddGossipItemFor(player, 9574, 3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 }
                 else if (!player->HasItemCount(ITEM_AMBER_ESSENCE))
                 {
                     AddGossipItemFor(player, 9574, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 }
                 AddGossipItemFor(player, 9574, 4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                 SendGossipMenuFor(player, GOSSIP_TEXTID_ETERNOS1, creature->GetGUID());
                 break;
             }
         }
         return true;
     }
References AddGossipItemFor(), DATA_DRAKOS, DONE, ZoneScript::GetData(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, GOSSIP_TEXTID_DRAKES, GOSSIP_TEXTID_ETERNOS1, GOSSIP_TEXTID_VERDISA1, HAS_ESSENCE, Player::HasItemCount(), Unit::IsQuestGiver(), ITEM_AMBER_ESSENCE, ITEM_EMERALD_ESSENCE, ITEM_RUBY_ESSENCE, NPC_BELGARISTRASZ, NPC_ETERNOS, NPC_VERDISA, OnGossipSelect(), openedMenu, Player::PrepareQuestMenu(), and SendGossipMenuFor().
OnGossipSelect()
bool npc_oculus_drakegiver::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 251 of file oculus.cpp.
     {
         ClearGossipMenuFor(player);
         switch(creature->GetEntry())
         {
         case NPC_VERDISA:
             switch(uiAction)
             {
             case GOSSIP_ACTION_INFO_DEF:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_VERDISA2, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 4:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_VERDISA3, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 RemoveEssence(player, ITEM_AMBER_ESSENCE);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 RemoveEssence(player, ITEM_RUBY_ESSENCE);
                 break;
             }
             StoreEssence(player, ITEM_EMERALD_ESSENCE);
             CloseGossipMenuFor(player);
             break;
         case NPC_BELGARISTRASZ:
             switch(uiAction)
             {
             case GOSSIP_ACTION_INFO_DEF:
                 openedMenu[player->GetGUID()] = true;
                 if (player->HasItemCount(ITEM_AMBER_ESSENCE))
                 {
                     AddGossipItemFor(player, 9575, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 }
                 else if (player->HasItemCount(ITEM_EMERALD_ESSENCE))
                 {
                     AddGossipItemFor(player, 9575, 2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 }
                 else if (!player->HasItemCount(ITEM_RUBY_ESSENCE))
                 {
                     AddGossipItemFor(player, 9575, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 }
                 AddGossipItemFor(player, 9575, 3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                 SendGossipMenuFor(player, GOSSIP_TEXTID_BELGARISTRASZ1, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 4:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_BELGARISTRASZ2, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 RemoveEssence(player, ITEM_AMBER_ESSENCE);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 RemoveEssence(player, ITEM_EMERALD_ESSENCE);
                 break;
             }
             StoreEssence(player, ITEM_RUBY_ESSENCE);
             CloseGossipMenuFor(player);
             break;
         case NPC_ETERNOS:
             switch (uiAction)
             {
             case GOSSIP_ACTION_INFO_DEF:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_ETERNOS2, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 4:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_ETERNOS3, creature->GetGUID());
                 return true;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 RemoveEssence(player, ITEM_EMERALD_ESSENCE);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 RemoveEssence(player, ITEM_RUBY_ESSENCE);
                 break;
             }
             StoreEssence(player, ITEM_AMBER_ESSENCE);
             CloseGossipMenuFor(player);
             break;
         }
         return true;
     }
References AddGossipItemFor(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetEntry(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, GOSSIP_TEXTID_BELGARISTRASZ1, GOSSIP_TEXTID_BELGARISTRASZ2, GOSSIP_TEXTID_ETERNOS2, GOSSIP_TEXTID_ETERNOS3, GOSSIP_TEXTID_VERDISA2, GOSSIP_TEXTID_VERDISA3, Player::HasItemCount(), ITEM_AMBER_ESSENCE, ITEM_EMERALD_ESSENCE, ITEM_RUBY_ESSENCE, NPC_BELGARISTRASZ, NPC_ETERNOS, NPC_VERDISA, openedMenu, RemoveEssence(), SendGossipMenuFor(), and StoreEssence().
Referenced by OnGossipHello().
RemoveEssence()
void npc_oculus_drakegiver::RemoveEssence (Player * player, uint32 itemId) inline
Definition at line 246 of file oculus.cpp.
     {
         player->DestroyItemCount(itemId, 1, true);
     }
References Player::DestroyItemCount().
Referenced by OnGossipSelect().
StoreEssence()
void npc_oculus_drakegiver::StoreEssence (Player * player, uint32 itemId) inline
Definition at line 233 of file oculus.cpp.
     {
         ItemPosCountVec dest;
         uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, itemId, 1);
         if (msg == EQUIP_ERR_OK)
         {
             if (Item* item = player->StoreNewItem(dest, itemId, true))
             {
                 player->SendNewItem(item, 1, true, true);
             }
         }
     }
References Player::CanStoreNewItem(), EQUIP_ERR_OK, NULL_BAG, NULL_SLOT, Player::SendNewItem(), and Player::StoreNewItem().
Referenced by OnGossipSelect().
Member Data Documentation
openedMenu
std::unordered_map<ObjectGuid, bool> npc_oculus_drakegiver::openedMenu
Definition at line 78 of file oculus.cpp.
Referenced by OnGossipHello(), and OnGossipSelect().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp