Azerotcore-wotlk: MPQArchive Class Reference
MPQArchive Class Reference
#include <mpq_libmpq04.h>
Public Member Functions
MPQArchive (const char *filename)
~MPQArchive ()
void close ()
void GetFileListTo (vector< string > &filelist)
MPQArchive (const char *filename)
void close ()
void GetFileListTo (std::vector< std::string > &filelist)
MPQArchive (const char *filename)
void close ()
void GetFileListTo (vector< string > &filelist)
Public Attributes
mpq_archive_s * mpq_a
std::vector< std::string > Files
Detailed Description
Definition at line 31 of file mpq_libmpq04.h.
Constructor & Destructor Documentation
MPQArchive() [1/3]
MPQArchive::MPQArchive (const char * filename)
Definition at line 24 of file mpq_libmpq.cpp.
 {
     int result = libmpq__archive_open(&mpq_a, filename, -1);
     printf("Opening %s\n", filename);
     if (result)
     {
         switch (result)
         {
             case LIBMPQ_ERROR_OPEN :
                 printf("Error opening archive '%s': Does file really exist?\n", filename);
                 break;
             case LIBMPQ_ERROR_FORMAT :            /* bad file format */
                 printf("Error opening archive '%s': Bad file format\n", filename);
                 break;
             case LIBMPQ_ERROR_SEEK :         /* seeking in file failed */
                 printf("Error opening archive '%s': Seeking in file failed\n", filename);
                 break;
             case LIBMPQ_ERROR_READ :              /* Read error in archive */
                 printf("Error opening archive '%s': Read error in archive\n", filename);
                 break;
             case LIBMPQ_ERROR_MALLOC :               /* maybe not enough memory? :) */
                 printf("Error opening archive '%s': Maybe not enough memory\n", filename);
                 break;
             default:
                 printf("Error opening archive '%s': Unknown error\n", filename);
                 break;
         }
         return;
     }
     gOpenArchives.push_front(this);
 }
References gOpenArchives, libmpq__archive_open(), LIBMPQ_ERROR_FORMAT, LIBMPQ_ERROR_MALLOC, LIBMPQ_ERROR_OPEN, LIBMPQ_ERROR_READ, LIBMPQ_ERROR_SEEK, mpq_a, and printf().
~MPQArchive()
MPQArchive::~MPQArchive () inline
Definition at line 37 of file mpq_libmpq04.h.
 { close(); }
References close.
MPQArchive() [2/3]
MPQArchive::MPQArchive (const char * filename)
MPQArchive() [3/3]
MPQArchive::MPQArchive (const char * filename)
Member Function Documentation
close() [1/3]
void MPQArchive::close ()
Definition at line 56 of file mpq_libmpq.cpp.
 {
     //gOpenArchives.erase(erase(&mpq_a);
     libmpq__archive_close(mpq_a);
 }
References libmpq__archive_close(), and mpq_a.
close() [2/3]
void MPQArchive::close ()
close() [3/3]
void MPQArchive::close ()
GetFileListTo() [1/3]
void MPQArchive::GetFileListTo (std::vector< std::string > & filelist) inline
Definition at line 40 of file MPQ.h.
     {
         uint32_t filenum;
         if (libmpq__file_number(mpq_a, "(listfile)", &filenum)) return;
         libmpq__off_t size, transferred;
         libmpq__file_unpacked_size(mpq_a, filenum, &size);
         char* buffer = new char[size + 1];
         buffer[size] = '\0';
         libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
         char seps[] = "\n";
         char* token;
         token = strtok( buffer, seps );
         uint32 counter = 0;
         while ((token != nullptr) && (counter < size))
         {
             //cout << token << endl;
             token[strlen(token) - 1] = 0;
             std::string s = token;
             filelist.push_back(s);
             counter += strlen(token) + 2;
             token = strtok(nullptr, seps);
         }
         delete[] buffer;
     }
References buffer, libmpq__file_number(), libmpq__file_read(), libmpq__file_unpacked_size(), and mpq_a.
GetFileListTo() [2/3]
void MPQArchive::GetFileListTo (vector< string > & filelist) inline
Definition at line 40 of file mpq_libmpq04.h.
     {
         uint32_t filenum;
         if (libmpq__file_number(mpq_a, "(listfile)", &filenum)) return;
         libmpq__off_t size, transferred;
         libmpq__file_unpacked_size(mpq_a, filenum, &size);
         char* buffer = new char[size + 1];
         buffer[size] = '\0';
         libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
         char seps[] = "\n";
         char* token;
         token = strtok( buffer, seps );
         uint32 counter = 0;
         while ((token != nullptr) && (counter < size))
         {
             //cout << token << endl;
             token[strlen(token) - 1] = 0;
             string s = token;
             filelist.push_back(s);
             counter += strlen(token) + 2;
             token = strtok(nullptr, seps);
         }
         delete[] buffer;
     }
References buffer, libmpq__file_number(), libmpq__file_read(), and libmpq__file_unpacked_size().
GetFileListTo() [3/3]
void MPQArchive::GetFileListTo (vector< string > & filelist) inline
Definition at line 39 of file mpq_libmpq04.h.
     {
         uint32_t filenum;
         if (libmpq__file_number(mpq_a, "(listfile)", &filenum)) return;
         libmpq__off_t size, transferred;
         libmpq__file_unpacked_size(mpq_a, filenum, &size);
         char* buffer = new char[size + 1];
         buffer[size] = '\0';
         libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
         char seps[] = "\n";
         char* token;
         token = strtok( buffer, seps );
         uint32 counter = 0;
         while ((token != nullptr) && (counter < size))
         {
             //cout << token << endl;
             token[strlen(token) - 1] = 0;
             string s = token;
             filelist.push_back(s);
             counter += strlen(token) + 2;
             token = strtok(nullptr, seps);
         }
         delete[] buffer;
     }
References buffer, libmpq__file_number(), libmpq__file_read(), and libmpq__file_unpacked_size().
Member Data Documentation
Files
std::vector<std::string> MPQArchive::Files
Definition at line 35 of file MPQ.h.
mpq_a
mpq_archive_s * MPQArchive::mpq_a
Definition at line 34 of file mpq_libmpq04.h.
Referenced by close(), GetFileListTo(), and MPQArchive().
The documentation for this class was generated from the following files:
src/tools/map_extractor/mpq_libmpq04.h
src/tools/mesh_extractor/MPQ.h
src/tools/map_extractor/mpq_libmpq.cpp
src/tools/mesh_extractor/MPQ.cpp