Azerotcore-wotlk: CasterAI Class Reference
CasterAI Class Reference
#include <CombatAI.h>
Public Member Functions
CasterAI (Creature *c)
void InitializeAI () override
void AttackStart (Unit *victim) override
void UpdateAI (uint32 diff) override
void EnterCombat (Unit *) override
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void Reset () override
void JustDied (Unit *killer) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
float m_attackDist
Additional Inherited Members
Static Public Member Functions inherited from CombatAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 56 of file CombatAI.h.
Constructor & Destructor Documentation
CasterAI()
CasterAI::CasterAI (Creature * c) inline explicit
Definition at line 59 of file CombatAI.h.
 : CombatAI(c) { m_attackDist = MELEE_RANGE; }
References m_attackDist, and MELEE_RANGE.
Member Function Documentation
AttackStart()
void CasterAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from UnitAI.
Definition at line 61 of file CombatAI.h.
 { AttackStartCaster(victim, m_attackDist); }
References UnitAI::AttackStartCaster(), and m_attackDist.
Referenced by npc_pet_mage_mirror_image::MySelectNextTarget().
EnterCombat()
void CasterAI::EnterCombat (Unit * who) override virtual
Reimplemented from CombatAI.
Definition at line 117 of file CombatAI.cpp.
 {
     if (spells.empty())
         return;
     uint32 spell = rand() % spells.size();
     uint32 count = 0;
     for (SpellVct::iterator itr = spells.begin(); itr != spells.end(); ++itr, ++count)
     {
         if (AISpellInfo[*itr].condition == AICOND_AGGRO)
             me->CastSpell(who, *itr, false);
         else if (AISpellInfo[*itr].condition == AICOND_COMBAT)
         {
             uint32 cooldown = GetAISpellInfo(*itr)->realCooldown;
             if (count == spell)
             {
                 DoCast(spells[spell]);
                 cooldown += me->GetCurrentSpellCastTime(*itr);
             }
             events.ScheduleEvent(*itr, cooldown);
         }
     }
 }
References AICOND_AGGRO, AICOND_COMBAT, UnitAI::AISpellInfo, Unit::CastSpell(), UnitAI::DoCast(), GetAISpellInfo(), Unit::GetCurrentSpellCastTime(), if(), CreatureAI::me, and AISpellInfoType::realCooldown.
InitializeAI()
void CasterAI::InitializeAI () override virtual
Reimplemented from CombatAI.
Reimplemented in npc_pet_mage_mirror_image.
Definition at line 105 of file CombatAI.cpp.
 {
     CombatAI::InitializeAI();
     m_attackDist = 30.0f;
     for (SpellVct::iterator itr = spells.begin(); itr != spells.end(); ++itr)
         if (AISpellInfo[*itr].condition == AICOND_COMBAT && m_attackDist > GetAISpellInfo(*itr)->maxRange)
             m_attackDist = GetAISpellInfo(*itr)->maxRange;
     if (m_attackDist == 30.0f)
         m_attackDist = MELEE_RANGE;
 }
References AICOND_COMBAT, UnitAI::AISpellInfo, GetAISpellInfo(), if(), CombatAI::InitializeAI(), m_attackDist, AISpellInfoType::maxRange, and MELEE_RANGE.
Referenced by npc_pet_mage_mirror_image::InitializeAI().
UpdateAI()
void CasterAI::UpdateAI (uint32 diff) override virtual
Reimplemented from CombatAI.
Reimplemented in npc_pet_mage_mirror_image.
Definition at line 141 of file CombatAI.cpp.
 {
     if (!UpdateVictim())
         return;
     events.Update(diff);
     if (me->GetVictim()->HasBreakableByDamageCrowdControlAura(me))
     {
         me->InterruptNonMeleeSpells(false);
         return;
     }
     if (me->HasUnitState(UNIT_STATE_CASTING))
         return;
     if (uint32 spellId = events.ExecuteEvent())
     {
         DoCast(spellId);
         uint32 casttime = me->GetCurrentSpellCastTime(spellId);
         events.ScheduleEvent(spellId, (casttime ? casttime : 500) + GetAISpellInfo(spellId)->realCooldown);
     }
 }
References UnitAI::DoCast(), GetAISpellInfo(), Unit::GetCurrentSpellCastTime(), Unit::GetVictim(), Unit::HasBreakableByDamageCrowdControlAura(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), CreatureAI::me, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
m_attackDist
float CasterAI::m_attackDist private
Definition at line 65 of file CombatAI.h.
Referenced by AttackStart(), CasterAI(), and InitializeAI().
The documentation for this class was generated from the following files:
src/server/game/AI/CoreAI/CombatAI.h
src/server/game/AI/CoreAI/CombatAI.cpp