Azerotcore-wotlk: boss_urom::boss_uromAI Struct Reference
boss_urom::boss_uromAI Struct Reference
Public Member Functions
boss_uromAI (Creature *c)
uint8 GetPhaseByCurrentPosition ()
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
void JustSummoned (Creature *pSummon) override
void LeaveCombat ()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, const SpellInfo *spell) override
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
bool lock
float x
float y
float z
int32 releaseLockTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 101 of file boss_urom.cpp.
Constructor & Destructor Documentation
boss_uromAI()
boss_urom::boss_uromAI::boss_uromAI (Creature * c) inline
Definition at line 103 of file boss_urom.cpp.
                                  : ScriptedAI(c)
         {
             pInstance = c->GetInstanceScript();
         }
References mpq::c, and pInstance.
Member Function Documentation
AttackStart()
void boss_urom::boss_uromAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 191 of file boss_urom.cpp.
         {
             if( lock )
                 return;
             if (me->GetDistance(1103.0f, 1049.0f, 510.0f) < 55.0f)
                 ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), WorldObject::GetDistance(), lock, and ScriptedAI::me.
EnterCombat()
void boss_urom::boss_uromAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 144 of file boss_urom.cpp.
         {
             if( lock )
                 return;
             uint8 phase = GetPhaseByCurrentPosition();
             if( phase == 3 )
             {
                 Talk(SAY_AGGRO);
                 if( pInstance )
                     pInstance->SetData(DATA_UROM, IN_PROGRESS);
                 me->SetInCombatWithZone();
                 me->SetHomePosition(cords[0][0], cords[0][1], cords[0][2], cords[0][3]);
                 if( me->FindCurrentSpellBySpellId(SPELL_EVOCATION) )
                     me->InterruptNonMeleeSpells(false);
                 events.RescheduleEvent(EVENT_FROSTBOMB, urand(7000, 11000));
                 events.RescheduleEvent(EVENT_TELEPORT_TO_CENTER, urand(30000, 35000));
                 events.RescheduleEvent(EVENT_TIME_BOMB, urand(20000, 25000));
             }
             else
             {
                 lock = true;
                 switch( phase )
                 {
                     case 0:
                         Talk(SAY_SUMMON_1);
                         me->InterruptNonMeleeSpells(false);
                         me->CastSpell(me, SPELL_SUMMON_MENAGERIE_1, false);
                         break;
                     case 1:
                         Talk(SAY_SUMMON_2);
                         me->InterruptNonMeleeSpells(false);
                         me->CastSpell(me, SPELL_SUMMON_MENAGERIE_2, false);
                         break;
                     case 2:
                         Talk(SAY_SUMMON_3);
                         me->InterruptNonMeleeSpells(false);
                         me->CastSpell(me, SPELL_SUMMON_MENAGERIE_3, false);
                         break;
                 }
             }
         }
References Unit::CastSpell(), cords, DATA_UROM, EVENT_FROSTBOMB, EVENT_TELEPORT_TO_CENTER, EVENT_TIME_BOMB, Unit::FindCurrentSpellBySpellId(), GetPhaseByCurrentPosition(), IN_PROGRESS, Unit::InterruptNonMeleeSpells(), lock, ScriptedAI::me, pInstance, SAY_AGGRO, SAY_SUMMON_1, SAY_SUMMON_2, SAY_SUMMON_3, ZoneScript::SetData(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), SPELL_EVOCATION, SPELL_SUMMON_MENAGERIE_1, SPELL_SUMMON_MENAGERIE_2, SPELL_SUMMON_MENAGERIE_3, CreatureAI::Talk(), and urand().
EnterEvadeMode()
void boss_urom::boss_uromAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 363 of file boss_urom.cpp.
         {
             me->SetCanFly(false);
             me->SetDisableGravity(false);
             me->SetControlled(false, UNIT_STATE_ROOT);
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Creature::SetCanFly(), Unit::SetControlled(), Creature::SetDisableGravity(), and UNIT_STATE_ROOT.
GetPhaseByCurrentPosition()
uint8 boss_urom::boss_uromAI::GetPhaseByCurrentPosition () inline
Definition at line 114 of file boss_urom.cpp.
         {
             for (uint8 i = 0; i < 4; ++i)
                 if (me->GetDistance(cords[i][0], cords[i][1], cords[i][2]) < 20.0f)
                     return i;
             return 0;
         }
References cords, WorldObject::GetDistance(), and ScriptedAI::me.
Referenced by EnterCombat(), and SpellHit().
JustDied()
void boss_urom::boss_uromAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 218 of file boss_urom.cpp.
         {
             Talk(SAY_DEATH);
             if (pInstance)
             {
                 pInstance->SetData(DATA_UROM, DONE);
             }
             me->SetCanFly(false);
             me->SetDisableGravity(false);
             me->NearTeleportTo(x, y, z, 0.0f);
         }
References DATA_UROM, DONE, ScriptedAI::me, Unit::NearTeleportTo(), pInstance, SAY_DEATH, Creature::SetCanFly(), ZoneScript::SetData(), Creature::SetDisableGravity(), CreatureAI::Talk(), x, y, and z.
JustSummoned()
void boss_urom::boss_uromAI::JustSummoned (Creature * pSummon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 200 of file boss_urom.cpp.
         {
             pSummon->SetInCombatWithZone();
             if( Unit* v = pSummon->SelectVictim() )
                 if( pSummon->AI() )
                     pSummon->AI()->AttackStart(v);
         }
References Creature::AI(), UnitAI::AttackStart(), Creature::SelectVictim(), and Creature::SetInCombatWithZone().
KilledUnit()
void boss_urom::boss_uromAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 230 of file boss_urom.cpp.
         {
             Talk(SAY_PLAYER_KILL);
         }
References SAY_PLAYER_KILL, and CreatureAI::Talk().
LeaveCombat()
void boss_urom::boss_uromAI::LeaveCombat () inline
Definition at line 208 of file boss_urom.cpp.
         {
             me->RemoveAllAuras();
             me->DeleteThreatList();
             me->CombatStop(true);
             me->LoadCreaturesAddon(true);
             me->SetLootRecipient(nullptr);
             me->ResetPlayerDamageReq();
         }
References Unit::CombatStop(), Unit::DeleteThreatList(), Creature::LoadCreaturesAddon(), ScriptedAI::me, Unit::RemoveAllAuras(), Creature::ResetPlayerDamageReq(), and Creature::SetLootRecipient().
Referenced by SpellHit(), and UpdateAI().
MoveInLineOfSight()
void boss_urom::boss_uromAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 298 of file boss_urom.cpp.
 {}
Reset()
void boss_urom::boss_uromAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 123 of file boss_urom.cpp.
         {
             if (pInstance)
             {
                 pInstance->SetData(DATA_UROM, NOT_STARTED);
                 if( pInstance->GetData(DATA_VAROS) != DONE )
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 else
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             }
             me->CastSpell(me, SPELL_EVOCATION, true);
             events.Reset();
             lock = false;
             x = 0.0f;
             y = 0.0f;
             z = 0.0f;
             releaseLockTimer = 0;
             me->ApplySpellImmune(0, IMMUNITY_ID, 49838, true);
         }
References Unit::ApplySpellImmune(), Unit::CastSpell(), DATA_UROM, DATA_VAROS, DONE, ZoneScript::GetData(), IMMUNITY_ID, lock, ScriptedAI::me, NOT_STARTED, pInstance, releaseLockTimer, Object::RemoveFlag(), ZoneScript::SetData(), Object::SetFlag(), SPELL_EVOCATION, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, x, y, and z.
SpellHit()
void boss_urom::boss_uromAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 235 of file boss_urom.cpp.
         {
             switch( spell->Id )
             {
                 case SPELL_SUMMON_MENAGERIE_1:
                     {
                         for( uint8 i = 0; i < 4; ++i )
                             me->SummonCreature(summons[0][i], cords[0][0] + ((i % 2) ? 4.0f : -4.0f), cords[0][1] + (i < 2 ? 4.0f : -4.0f), cords[0][2], 0.0f, TEMPSUMMON_TIMED_DESPAWN, 300000);
                         uint8 phase = GetPhaseByCurrentPosition();
                         me->SetHomePosition(cords[phase + 1][0], cords[phase + 1][1], cords[phase + 1][2], cords[phase + 1][3]);
                         me->DestroyForNearbyPlayers();
                         LeaveCombat();
                         me->CastSpell(me, SPELL_EVOCATION, true);
                         releaseLockTimer = 1;
                     }
                     break;
                 case SPELL_SUMMON_MENAGERIE_2:
                     {
                         for( uint8 i = 0; i < 4; ++i )
                             me->SummonCreature(summons[1][i], cords[1][0] + ((i % 2) ? 4.0f : -4.0f), cords[1][1] + (i < 2 ? 4.0f : -4.0f), cords[1][2], 0.0f, TEMPSUMMON_TIMED_DESPAWN, 300000);
                         uint8 phase = GetPhaseByCurrentPosition();
                         me->SetHomePosition(cords[phase + 1][0], cords[phase + 1][1], cords[phase + 1][2], cords[phase + 1][3]);
                         me->DestroyForNearbyPlayers();
                         LeaveCombat();
                         me->CastSpell(me, SPELL_EVOCATION, true);
                         releaseLockTimer = 1;
                     }
                     break;
                 case SPELL_SUMMON_MENAGERIE_3:
                     {
                         for( uint8 i = 0; i < 4; ++i )
                             me->SummonCreature(summons[2][i], cords[2][0] + ((i % 2) ? 4.0f : -4.0f), cords[2][1] + (i < 2 ? 4.0f : -4.0f), cords[2][2], 0.0f, TEMPSUMMON_TIMED_DESPAWN, 300000);
                         uint8 phase = GetPhaseByCurrentPosition();
                         me->SetHomePosition(cords[phase + 1][0], cords[phase + 1][1], cords[phase + 1][2], cords[phase + 1][3]);
                         me->DestroyForNearbyPlayers();
                         LeaveCombat();
                         me->CastSpell(me, SPELL_EVOCATION, true);
                         releaseLockTimer = 1;
                     }
                     break;
                 case SPELL_TELEPORT:
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MoveIdle();
                     me->StopMoving();
                     me->SetControlled(true, UNIT_STATE_ROOT);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetCanFly(true);
                     me->SetDisableGravity(true);
                     me->NearTeleportTo(1103.69f, 1048.76f, 512.279f, 1.16f);
                     Talk(SAY_ARCANE_EXPLOSION);
                     Talk(EMOTE_ARCANE_EXPLOSION);
                     //At this point we are still in casting state so we need to clear it for DoCastAOE not to fail
                     me->ClearUnitState(UNIT_STATE_CASTING);
                     DoCastAOE(DUNGEON_MODE(SPELL_EMPOWERED_ARCANE_EXPLOSION_N, SPELL_EMPOWERED_ARCANE_EXPLOSION_H));
                     me->AddUnitState(UNIT_STATE_CASTING);
                     events.RescheduleEvent(EVENT_TELE_BACK, DUNGEON_MODE(9000, 7000));
                 default:
                     break;
             }
         }
References Unit::AddUnitState(), Unit::CastSpell(), MotionMaster::Clear(), Unit::ClearUnitState(), cords, WorldObject::DestroyForNearbyPlayers(), UnitAI::DoCastAOE(), ScriptedAI::DUNGEON_MODE(), EMOTE_ARCANE_EXPLOSION, EVENT_TELE_BACK, Unit::GetMotionMaster(), GetPhaseByCurrentPosition(), SpellInfo::Id, LeaveCombat(), ScriptedAI::me, MotionMaster::MoveIdle(), Unit::NearTeleportTo(), releaseLockTimer, SAY_ARCANE_EXPLOSION, Creature::SetCanFly(), Unit::SetControlled(), Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetHomePosition(), SPELL_EMPOWERED_ARCANE_EXPLOSION_H, SPELL_EMPOWERED_ARCANE_EXPLOSION_N, SPELL_EVOCATION, SPELL_SUMMON_MENAGERIE_1, SPELL_SUMMON_MENAGERIE_2, SPELL_SUMMON_MENAGERIE_3, SPELL_TELEPORT, Unit::StopMoving(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, and UNIT_STATE_ROOT.
UpdateAI()
void boss_urom::boss_uromAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 300 of file boss_urom.cpp.
         {
             if( releaseLockTimer )
             {
                 if( releaseLockTimer >= 5000 )
                 {
                     lock = false;
                     if (me->IsInCombat())
                     {
                         LeaveCombat();
                         me->CastSpell(me, SPELL_EVOCATION, true);
                     }
                     releaseLockTimer = 0;
                 }
                 else
                     releaseLockTimer += diff;
             }
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             DoMeleeAttackIfReady();
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_FROSTBOMB:
                     if( Unit* v = me->GetVictim() )
                         me->CastSpell(v, SPELL_FROSTBOMB, false);
                     events.RepeatEvent(urand(7000, 11000));
                     break;
                 case EVENT_TIME_BOMB:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true) )
                         DoCast(target, DUNGEON_MODE(SPELL_TIME_BOMB_N, SPELL_TIME_BOMB_H));
                     events.RepeatEvent(urand(20000, 25000));
                     break;
                 case EVENT_TELEPORT_TO_CENTER:
                     x = me->GetPositionX();
                     y = me->GetPositionY();
                     z = me->GetPositionZ();
                     me->CastSpell(me, SPELL_TELEPORT, false);
                     events.RepeatEvent(urand(25000, 30000));
                     events.DelayEvents(10000);
                     break;
                 case EVENT_TELE_BACK:
                     me->GetMotionMaster()->MoveIdle();
                     me->DisableSpline();
                     me->SetCanFly(false);
                     me->SetDisableGravity(false);
                     me->NearTeleportTo(x, y, z, 0.0f);
                     me->SetControlled(false, UNIT_STATE_ROOT);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     break;
             }
         }
References Unit::CastSpell(), diff(), Unit::DisableSpline(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DUNGEON_MODE(), EVENT_FROSTBOMB, EVENT_TELE_BACK, EVENT_TELEPORT_TO_CENTER, EVENT_TIME_BOMB, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsInCombat(), LeaveCombat(), lock, ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), Unit::NearTeleportTo(), releaseLockTimer, Object::RemoveFlag(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetCanFly(), Unit::SetControlled(), Creature::SetDisableGravity(), SPELL_EVOCATION, SPELL_FROSTBOMB, SPELL_TELEPORT, SPELL_TIME_BOMB_H, SPELL_TIME_BOMB_N, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), urand(), x, y, and z.
Member Data Documentation
events
EventMap boss_urom::boss_uromAI::events
Definition at line 109 of file boss_urom.cpp.
lock
bool boss_urom::boss_uromAI::lock
Definition at line 110 of file boss_urom.cpp.
Referenced by AttackStart(), EnterCombat(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_urom::boss_uromAI::pInstance
Definition at line 108 of file boss_urom.cpp.
Referenced by boss_uromAI(), EnterCombat(), JustDied(), and Reset().
releaseLockTimer
int32 boss_urom::boss_uromAI::releaseLockTimer
Definition at line 112 of file boss_urom.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
x
float boss_urom::boss_uromAI::x
Definition at line 111 of file boss_urom.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
y
float boss_urom::boss_uromAI::y
Definition at line 111 of file boss_urom.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
z
float boss_urom::boss_uromAI::z
Definition at line 111 of file boss_urom.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp