Azerotcore-wotlk: npc_shandy_dalaran Class Reference
npc_shandy_dalaran Class Reference
Classes
struct npc_shandy_dalaranAI
Public Member Functions
npc_shandy_dalaran ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 136 of file zone_dalaran.cpp.
Constructor & Destructor Documentation
npc_shandy_dalaran()
npc_shandy_dalaran::npc_shandy_dalaran () inline
Definition at line 139 of file zone_dalaran.cpp.
 : CreatureScript("npc_shandy_dalaran") { }
Member Function Documentation
GetAI()
CreatureAI* npc_shandy_dalaran::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 271 of file zone_dalaran.cpp.
     {
         return new npc_shandy_dalaranAI(creature);
     }
OnGossipHello()
bool npc_shandy_dalaran::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 240 of file zone_dalaran.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (player->GetQuestStatus(QUEST_SUITABLE_DISGUISE_A) == QUEST_STATUS_INCOMPLETE ||
                 player->GetQuestStatus(QUEST_SUITABLE_DISGUISE_H) == QUEST_STATUS_INCOMPLETE)
         {
             if(player->GetTeamId() == TEAM_ALLIANCE)
                 AddGossipItemFor(player, 0, "Arcanist Tybalin said you might be able to lend me a certain tabard.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
             else
                 AddGossipItemFor(player, 0, "Magister Hathorel said you might be able to lend me a certain tabard.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, QUEST_SUITABLE_DISGUISE_A, QUEST_SUITABLE_DISGUISE_H, SendGossipMenuFor(), and TEAM_ALLIANCE.
OnGossipSelect()
bool npc_shandy_dalaran::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 258 of file zone_dalaran.cpp.
     {
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF:
                 CloseGossipMenuFor(player);
                 creature->SetUInt32Value(UNIT_NPC_FLAGS, 0);
                 creature->AI()->SetData(ACTION_SHANDY_INTRO, 0);
                 break;
         }
         return true;
     }
References ACTION_SHANDY_INTRO, Creature::AI(), CloseGossipMenuFor(), GOSSIP_ACTION_INFO_DEF, UnitAI::SetData(), Object::SetUInt32Value(), and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_dalaran.cpp