Azerotcore-wotlk: soap_plugin Struct Reference
soap_plugin Struct Reference
#include <stdsoap2.h>
Public Attributes
struct soap_plugin * next
const char * id
void * data
int(* fcopy)(struct soap *soap, struct soap_plugin *dst, struct soap_plugin *src)
void(* fdelete)(struct soap *soap, struct soap_plugin *p)
Detailed Description
Definition at line 3027 of file stdsoap2.h.
Member Data Documentation
data
void* soap_plugin::data
Definition at line 3031 of file stdsoap2.h.
Referenced by fplugin(), and soap_register_plugin_arg().
fcopy
int(* soap_plugin::fcopy) (struct soap *soap, struct soap_plugin *dst, struct soap_plugin *src)
Definition at line 3032 of file stdsoap2.h.
Referenced by soap_copy_context(), soap_done(), and soap_register_plugin_arg().
fdelete
void(* soap_plugin::fdelete) (struct soap *soap, struct soap_plugin *p)
Definition at line 3033 of file stdsoap2.h.
Referenced by soap_done(), and soap_register_plugin_arg().
id
const char* soap_plugin::id
Definition at line 3030 of file stdsoap2.h.
Referenced by fplugin(), soap_copy_context(), soap_done(), and soap_register_plugin_arg().
next
struct soap_plugin* soap_plugin::next
Definition at line 3029 of file stdsoap2.h.
Referenced by fplugin(), soap_copy_context(), soap_done(), and soap_register_plugin_arg().
The documentation for this struct was generated from the following file:
deps/gsoap/stdsoap2.h