Azerotcore-wotlk: achievement_share_the_love Class Reference
achievement_share_the_love Class Reference
Public Member Functions
achievement_share_the_love ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 274 of file boss_gal_darah.cpp.
Constructor & Destructor Documentation
achievement_share_the_love()
achievement_share_the_love::achievement_share_the_love () inline
Definition at line 277 of file boss_gal_darah.cpp.
                                  : AchievementCriteriaScript("achievement_share_the_love")
     {
     }
Member Function Documentation
OnCheck()
bool achievement_share_the_love::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 281 of file boss_gal_darah.cpp.
     {
         if (!target)
             return false;
         return target->GetAI()->GetData(target->GetEntry()) >= 5;
     }
References Unit::GetAI(), UnitAI::GetData(), and Object::GetEntry().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Gundrak/boss_gal_darah.cpp