Azerotcore-wotlk: G3D::MeshEdgeTable::Iterator Class Reference
G3D::MeshEdgeTable::Iterator Class Reference
Public Member Functions
int i0 () const
int i1 () const
FaceIndexArray & faceIndex ()
Iterator & operator++ ()
bool isValid () const
bool hasMore () const
Private Member Functions
Iterator (ET &a)
Private Attributes
int m_i0
int m_p
ET & m_array
EdgeArray * m_edgeArray
bool m_end
Friends
class MeshEdgeTable
Detailed Description
Definition at line 83 of file MeshAlgAdjacency.cpp.
Constructor & Destructor Documentation
Iterator()
G3D::MeshEdgeTable::Iterator::Iterator (ET & a) inline private
Definition at line 139 of file MeshAlgAdjacency.cpp.
                         : m_i0(-1), m_p(-1),  m_array(a), m_edgeArray(NULL), m_end(false) {
             ++(*this);
         }
Member Function Documentation
faceIndex()
FaceIndexArray& G3D::MeshEdgeTable::Iterator::faceIndex () inline
Definition at line 104 of file MeshAlgAdjacency.cpp.
{
             return (*m_edgeArray)[m_p].faceIndexArray;
         }
References m_edgeArray, and m_p.
Referenced by G3D::MeshAlg::computeAdjacency().
hasMore()
bool G3D::MeshEdgeTable::Iterator::hasMore () const inline
Deprecated:
Use isValid
Definition at line 133 of file MeshAlgAdjacency.cpp.
{
             return ! m_end;
         }
References m_end.
i0()
int G3D::MeshEdgeTable::Iterator::i0 () const inline
Definition at line 96 of file MeshAlgAdjacency.cpp.
{
             return m_i0;
         }
References m_i0.
Referenced by G3D::MeshAlg::computeAdjacency().
i1()
int G3D::MeshEdgeTable::Iterator::i1 () const inline
Definition at line 100 of file MeshAlgAdjacency.cpp.
{
             return (*m_edgeArray)[m_p].i1;
         }
References m_edgeArray, and m_p.
Referenced by G3D::MeshAlg::computeAdjacency().
isValid()
bool G3D::MeshEdgeTable::Iterator::isValid () const inline
Definition at line 128 of file MeshAlgAdjacency.cpp.
{
             return ! m_end;
         }
References m_end.
Referenced by G3D::MeshAlg::computeAdjacency().
operator++()
Iterator& G3D::MeshEdgeTable::Iterator::operator++ () inline
Definition at line 108 of file MeshAlgAdjacency.cpp.
{
             if ((m_i0 >= 0) && (m_p < m_edgeArray->size() - 1)) {
                 ++m_p;
             } else {
                 // Skip over elements with no face array
                 do {
                     ++m_i0;
                     if (m_i0 == m_array.size()) {
                         m_end = true;
                         return *this;
                     } else {
                         m_edgeArray = &m_array[m_i0];
                         m_p = 0;
                     }
                 } while (m_edgeArray->size() == 0);
             }
             return *this;
         }
References m_array, m_edgeArray, m_end, m_i0, m_p, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::SmallArray< T, N >::size().
Friends And Related Function Documentation
MeshEdgeTable
friend class MeshEdgeTable friend
Definition at line 84 of file MeshAlgAdjacency.cpp.
Member Data Documentation
m_array
ET& G3D::MeshEdgeTable::Iterator::m_array private
Definition at line 90 of file MeshAlgAdjacency.cpp.
Referenced by operator++().
m_edgeArray
EdgeArray* G3D::MeshEdgeTable::Iterator::m_edgeArray private
Definition at line 91 of file MeshAlgAdjacency.cpp.
Referenced by faceIndex(), i1(), and operator++().
m_end
bool G3D::MeshEdgeTable::Iterator::m_end private
Definition at line 92 of file MeshAlgAdjacency.cpp.
Referenced by hasMore(), isValid(), and operator++().
m_i0
int G3D::MeshEdgeTable::Iterator::m_i0 private
Definition at line 87 of file MeshAlgAdjacency.cpp.
Referenced by i0(), and operator++().
m_p
int G3D::MeshEdgeTable::Iterator::m_p private
Pair index
Definition at line 89 of file MeshAlgAdjacency.cpp.
Referenced by faceIndex(), i1(), and operator++().
The documentation for this class was generated from the following file:
deps/g3dlite/source/MeshAlgAdjacency.cpp