Azerotcore-wotlk: deps/recastnavigation/Detour/Source/DetourNavMeshBuilder.cpp File Reference
DetourNavMeshBuilder.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include "DetourNavMesh.h"
#include "DetourCommon.h"
#include "DetourMath.h"
#include "DetourNavMeshBuilder.h"
#include "DetourAlloc.h"
#include "DetourAssert.h"
Classes
struct BVItem
Functions
static int compareItemX (const void *va, const void *vb)
static int compareItemY (const void *va, const void *vb)
static int compareItemZ (const void *va, const void *vb)
static void calcExtends (BVItem *items, const int, const int imin, const int imax, unsigned short *bmin, unsigned short *bmax)
int longestAxis (unsigned short x, unsigned short y, unsigned short z)
static void subdivide (BVItem *items, int nitems, int imin, int imax, int &curNode, dtBVNode *nodes)
static int createBVTree (dtNavMeshCreateParams *params, dtBVNode *nodes, int)
static unsigned char classifyOffMeshPoint (const float *pt, const float *bmin, const float *bmax)
bool dtCreateNavMeshData (dtNavMeshCreateParams *params, unsigned char **outData, int *outDataSize)
bool dtNavMeshHeaderSwapEndian (unsigned char *data, const int)
bool dtNavMeshDataSwapEndian (unsigned char *data, const int)
Variables
static unsigned short MESH_NULL_IDX = 0xffff
Function Documentation
calcExtends()
static void calcExtends (BVItem * items, const int , const int imin, const int imax, unsigned short * bmin, unsigned short * bmax) static
Definition at line 73 of file DetourNavMeshBuilder.cpp.
 {
     bmin[0] = items[imin].bmin[0];
     bmin[1] = items[imin].bmin[1];
     bmin[2] = items[imin].bmin[2];
     bmax[0] = items[imin].bmax[0];
     bmax[1] = items[imin].bmax[1];
     bmax[2] = items[imin].bmax[2];
     for (int i = imin+1; i < imax; ++i)
     {
         const BVItem& it = items[i];
         if (it.bmin[0] < bmin[0]) bmin[0] = it.bmin[0];
         if (it.bmin[1] < bmin[1]) bmin[1] = it.bmin[1];
         if (it.bmin[2] < bmin[2]) bmin[2] = it.bmin[2];
         if (it.bmax[0] > bmax[0]) bmax[0] = it.bmax[0];
         if (it.bmax[1] > bmax[1]) bmax[1] = it.bmax[1];
         if (it.bmax[2] > bmax[2]) bmax[2] = it.bmax[2];
     }
 }
References BVItem::bmax, and BVItem::bmin.
Referenced by subdivide().
classifyOffMeshPoint()
static unsigned char classifyOffMeshPoint (const float * pt, const float * bmin, const float * bmax) static
Definition at line 243 of file DetourNavMeshBuilder.cpp.
 {
     static const unsigned char XP = 1<<0;
     static const unsigned char ZP = 1<<1;
     static const unsigned char XM = 1<<2;
     static const unsigned char ZM = 1<<3;
     unsigned char outcode = 0;
     outcode |= (pt[0] >= bmax[0]) ? XP : 0;
     outcode |= (pt[2] >= bmax[2]) ? ZP : 0;
     outcode |= (pt[0] < bmin[0])  ? XM : 0;
     outcode |= (pt[2] < bmin[2])  ? ZM : 0;
     switch (outcode)
     {
     case XP: return 0;
     case XP|ZP: return 1;
     case ZP: return 2;
     case XM|ZP: return 3;
     case XM: return 4;
     case XM|ZM: return 5;
     case ZM: return 6;
     case XP|ZM: return 7;
     };
     return 0xff;
 }
Referenced by dtCreateNavMeshData().
compareItemX()
static int compareItemX (const void * va, const void * vb) static
Definition at line 40 of file DetourNavMeshBuilder.cpp.
 {
     const BVItem* a = (const BVItem*)va;
     const BVItem* b = (const BVItem*)vb;
     if (a->bmin[0] < b->bmin[0])
         return -1;
     if (a->bmin[0] > b->bmin[0])
         return 1;
     return 0;
 }
References mpq::a, and b.
Referenced by subdivide().
compareItemY()
static int compareItemY (const void * va, const void * vb) static
Definition at line 51 of file DetourNavMeshBuilder.cpp.
 {
     const BVItem* a = (const BVItem*)va;
     const BVItem* b = (const BVItem*)vb;
     if (a->bmin[1] < b->bmin[1])
         return -1;
     if (a->bmin[1] > b->bmin[1])
         return 1;
     return 0;
 }
References mpq::a, and b.
Referenced by subdivide().
compareItemZ()
static int compareItemZ (const void * va, const void * vb) static
Definition at line 62 of file DetourNavMeshBuilder.cpp.
 {
     const BVItem* a = (const BVItem*)va;
     const BVItem* b = (const BVItem*)vb;
     if (a->bmin[2] < b->bmin[2])
         return -1;
     if (a->bmin[2] > b->bmin[2])
         return 1;
     return 0;
 }
References mpq::a, and b.
Referenced by subdivide().
createBVTree()
static int createBVTree (dtNavMeshCreateParams * params, dtBVNode * nodes, int) static
Definition at line 171 of file DetourNavMeshBuilder.cpp.
 {
     // Build tree
     float quantFactor = 1 / params->cs;
     BVItem* items = (BVItem*)dtAlloc(sizeof(BVItem)*params->polyCount, DT_ALLOC_TEMP);
     for (int i = 0; i < params->polyCount; i++)
     {
         BVItem& it = items[i];
         it.i = i;
         // Calc polygon bounds. Use detail meshes if available.
         if (params->detailMeshes)
         {
             int vb = (int)params->detailMeshes[i*4+0];
             int ndv = (int)params->detailMeshes[i*4+1];
             float bmin[3];
             float bmax[3];
             const float* dv = &params->detailVerts[vb*3];
             dtVcopy(bmin, dv);
             dtVcopy(bmax, dv);
             for (int j = 1; j < ndv; j++)
             {
                 dtVmin(bmin, &dv[j * 3]);
                 dtVmax(bmax, &dv[j * 3]);
             }
             // BV-tree uses cs for all dimensions
             it.bmin[0] = (unsigned short)dtClamp((int)((bmin[0] - params->bmin[0])*quantFactor), 0, 0xffff);
             it.bmin[1] = (unsigned short)dtClamp((int)((bmin[1] - params->bmin[1])*quantFactor), 0, 0xffff);
             it.bmin[2] = (unsigned short)dtClamp((int)((bmin[2] - params->bmin[2])*quantFactor), 0, 0xffff);
             it.bmax[0] = (unsigned short)dtClamp((int)((bmax[0] - params->bmin[0])*quantFactor), 0, 0xffff);
             it.bmax[1] = (unsigned short)dtClamp((int)((bmax[1] - params->bmin[1])*quantFactor), 0, 0xffff);
             it.bmax[2] = (unsigned short)dtClamp((int)((bmax[2] - params->bmin[2])*quantFactor), 0, 0xffff);
         }
         else
         {
             const unsigned short* p = &params->polys[i*params->nvp * 2];
             it.bmin[0] = it.bmax[0] = params->verts[p[0] * 3 + 0];
             it.bmin[1] = it.bmax[1] = params->verts[p[0] * 3 + 1];
             it.bmin[2] = it.bmax[2] = params->verts[p[0] * 3 + 2];
             for (int j = 1; j < params->nvp; ++j)
             {
                 if (p[j] == MESH_NULL_IDX) break;
                 unsigned short x = params->verts[p[j] * 3 + 0];
                 unsigned short y = params->verts[p[j] * 3 + 1];
                 unsigned short z = params->verts[p[j] * 3 + 2];
                 if (x < it.bmin[0]) it.bmin[0] = x;
                 if (y < it.bmin[1]) it.bmin[1] = y;
                 if (z < it.bmin[2]) it.bmin[2] = z;
                 if (x > it.bmax[0]) it.bmax[0] = x;
                 if (y > it.bmax[1]) it.bmax[1] = y;
                 if (z > it.bmax[2]) it.bmax[2] = z;
             }
             // Remap y
             it.bmin[1] = (unsigned short)dtMathFloorf((float)it.bmin[1] * params->ch / params->cs);
             it.bmax[1] = (unsigned short)dtMathCeilf((float)it.bmax[1] * params->ch / params->cs);
         }
     }
     int curNode = 0;
     subdivide(items, params->polyCount, 0, params->polyCount, curNode, nodes);
     dtFree(items);
     return curNode;
 }
References BVItem::bmax, dtNavMeshCreateParams::bmin, BVItem::bmin, dtNavMeshCreateParams::ch, dtNavMeshCreateParams::cs, dtNavMeshCreateParams::detailMeshes, dtNavMeshCreateParams::detailVerts, DT_ALLOC_TEMP, dtAlloc(), dtClamp(), dtFree(), dtMathCeilf(), dtMathFloorf(), dtVcopy(), dtVmax(), dtVmin(), BVItem::i, MESH_NULL_IDX, dtNavMeshCreateParams::nvp, dtNavMeshCreateParams::polyCount, dtNavMeshCreateParams::polys, subdivide(), dtNavMeshCreateParams::verts, G3D::x, G3D::y, and G3D::z.
Referenced by dtCreateNavMeshData().
dtNavMeshDataSwapEndian()
bool dtNavMeshDataSwapEndian (unsigned char * data, const int dataSize)
Warning
This function assumes that the header is in the correct endianess already. Call dtNavMeshHeaderSwapEndian() first on the data if the data is expected to be in wrong endianess to start with. Call dtNavMeshHeaderSwapEndian() after the data has been swapped if converting from native to foreign endianess.
Definition at line 712 of file DetourNavMeshBuilder.cpp.
 {
     // Make sure the data is in right format.
     dtMeshHeader* header = (dtMeshHeader*)data;
     if (header->magic != DT_NAVMESH_MAGIC)
         return false;
     if (header->version != DT_NAVMESH_VERSION)
         return false;
     // Patch header pointers.
     const int headerSize = dtAlign4(sizeof(dtMeshHeader));
     const int vertsSize = dtAlign4(sizeof(float)*3*header->vertCount);
     const int polysSize = dtAlign4(sizeof(dtPoly)*header->polyCount);
     const int linksSize = dtAlign4(sizeof(dtLink)*(header->maxLinkCount));
     const int detailMeshesSize = dtAlign4(sizeof(dtPolyDetail)*header->detailMeshCount);
     const int detailVertsSize = dtAlign4(sizeof(float)*3*header->detailVertCount);
     const int detailTrisSize = dtAlign4(sizeof(unsigned char)*4*header->detailTriCount);
     const int bvtreeSize = dtAlign4(sizeof(dtBVNode)*header->bvNodeCount);
     const int offMeshLinksSize = dtAlign4(sizeof(dtOffMeshConnection)*header->offMeshConCount);
     unsigned char* d = data + headerSize;
     float* verts = dtGetThenAdvanceBufferPointer<float>(d, vertsSize);
     dtPoly* polys = dtGetThenAdvanceBufferPointer<dtPoly>(d, polysSize);
     d += linksSize; // Ignore links; they technically should be endian-swapped but all their data is overwritten on load anyway.
     //dtLink* links = dtGetThenAdvanceBufferPointer<dtLink>(d, linksSize);
     dtPolyDetail* detailMeshes = dtGetThenAdvanceBufferPointer<dtPolyDetail>(d, detailMeshesSize);
     float* detailVerts = dtGetThenAdvanceBufferPointer<float>(d, detailVertsSize);
     d += detailTrisSize; // Ignore detail tris; single bytes can't be endian-swapped.
     //unsigned char* detailTris = dtGetThenAdvanceBufferPointer<unsigned char>(d, detailTrisSize);
     dtBVNode* bvTree = dtGetThenAdvanceBufferPointer<dtBVNode>(d, bvtreeSize);
     dtOffMeshConnection* offMeshCons = dtGetThenAdvanceBufferPointer<dtOffMeshConnection>(d, offMeshLinksSize);
     // Vertices
     for (int i = 0; i < header->vertCount*3; ++i)
     {
         dtSwapEndian(&verts[i]);
     }
     // Polys
     for (int i = 0; i < header->polyCount; ++i)
     {
         dtPoly* p = &polys[i];
         // poly->firstLink is update when tile is added, no need to swap.
         for (int j = 0; j < DT_VERTS_PER_POLYGON; ++j)
         {
             dtSwapEndian(&p->verts[j]);
             dtSwapEndian(&p->neis[j]);
         }
         dtSwapEndian(&p->flags);
     }
     // Links are rebuild when tile is added, no need to swap.
     // Detail meshes
     for (int i = 0; i < header->detailMeshCount; ++i)
     {
         dtPolyDetail* pd = &detailMeshes[i];
         dtSwapEndian(&pd->vertBase);
         dtSwapEndian(&pd->triBase);
     }
     // Detail verts
     for (int i = 0; i < header->detailVertCount*3; ++i)
     {
         dtSwapEndian(&detailVerts[i]);
     }
     // BV-tree
     for (int i = 0; i < header->bvNodeCount; ++i)
     {
         dtBVNode* node = &bvTree[i];
         for (int j = 0; j < 3; ++j)
         {
             dtSwapEndian(&node->bmin[j]);
             dtSwapEndian(&node->bmax[j]);
         }
         dtSwapEndian(&node->i);
     }
     // Off-mesh Connections.
     for (int i = 0; i < header->offMeshConCount; ++i)
     {
         dtOffMeshConnection* con = &offMeshCons[i];
         for (int j = 0; j < 6; ++j)
             dtSwapEndian(&con->pos[j]);
         dtSwapEndian(&con->rad);
         dtSwapEndian(&con->poly);
     }
     return true;
 }
References dtBVNode::bmax, dtBVNode::bmin, dtMeshHeader::bvNodeCount, mpq::d, dtMeshHeader::detailMeshCount, dtMeshHeader::detailTriCount, dtMeshHeader::detailVertCount, DT_NAVMESH_MAGIC, DT_NAVMESH_VERSION, DT_VERTS_PER_POLYGON, dtAlign4(), dtSwapEndian(), dtPoly::flags, dtBVNode::i, dtMeshHeader::magic, dtMeshHeader::maxLinkCount, dtPoly::neis, dtMeshHeader::offMeshConCount, dtOffMeshConnection::poly, dtMeshHeader::polyCount, dtOffMeshConnection::pos, dtOffMeshConnection::rad, dtPolyDetail::triBase, dtMeshHeader::version, dtPolyDetail::vertBase, dtMeshHeader::vertCount, and dtPoly::verts.
dtNavMeshHeaderSwapEndian()
bool dtNavMeshHeaderSwapEndian (unsigned char * data, const int dataSize)
Swaps the endianess of the tile data's header (dtMeshHeader).
Parameters
[in,out] data The tile data array.
[in] dataSize The size of the data array.
Definition at line 660 of file DetourNavMeshBuilder.cpp.
 {
     dtMeshHeader* header = (dtMeshHeader*)data;
     int swappedMagic = DT_NAVMESH_MAGIC;
     int swappedVersion = DT_NAVMESH_VERSION;
     dtSwapEndian(&swappedMagic);
     dtSwapEndian(&swappedVersion);
     if ((header->magic != DT_NAVMESH_MAGIC || header->version != DT_NAVMESH_VERSION) &&
         (header->magic != swappedMagic || header->version != swappedVersion))
     {
         return false;
     }
     dtSwapEndian(&header->magic);
     dtSwapEndian(&header->version);
     dtSwapEndian(&header->x);
     dtSwapEndian(&header->y);
     dtSwapEndian(&header->layer);
     dtSwapEndian(&header->userId);
     dtSwapEndian(&header->polyCount);
     dtSwapEndian(&header->vertCount);
     dtSwapEndian(&header->maxLinkCount);
     dtSwapEndian(&header->detailMeshCount);
     dtSwapEndian(&header->detailVertCount);
     dtSwapEndian(&header->detailTriCount);
     dtSwapEndian(&header->bvNodeCount);
     dtSwapEndian(&header->offMeshConCount);
     dtSwapEndian(&header->offMeshBase);
     dtSwapEndian(&header->walkableHeight);
     dtSwapEndian(&header->walkableRadius);
     dtSwapEndian(&header->walkableClimb);
     dtSwapEndian(&header->bmin[0]);
     dtSwapEndian(&header->bmin[1]);
     dtSwapEndian(&header->bmin[2]);
     dtSwapEndian(&header->bmax[0]);
     dtSwapEndian(&header->bmax[1]);
     dtSwapEndian(&header->bmax[2]);
     dtSwapEndian(&header->bvQuantFactor);
     // Freelist index and pointers are updated when tile is added, no need to swap.
     return true;
 }
References dtMeshHeader::bmax, dtMeshHeader::bmin, dtMeshHeader::bvNodeCount, dtMeshHeader::bvQuantFactor, dtMeshHeader::detailMeshCount, dtMeshHeader::detailTriCount, dtMeshHeader::detailVertCount, DT_NAVMESH_MAGIC, DT_NAVMESH_VERSION, dtSwapEndian(), dtMeshHeader::layer, dtMeshHeader::magic, dtMeshHeader::maxLinkCount, dtMeshHeader::offMeshBase, dtMeshHeader::offMeshConCount, dtMeshHeader::polyCount, dtMeshHeader::userId, dtMeshHeader::version, dtMeshHeader::vertCount, dtMeshHeader::walkableClimb, dtMeshHeader::walkableHeight, dtMeshHeader::walkableRadius, dtMeshHeader::x, and dtMeshHeader::y.
longestAxis()
int longestAxis (unsigned short x, unsigned short y, unsigned short z) inline
Definition at line 97 of file DetourNavMeshBuilder.cpp.
 {
     int axis = 0;
     unsigned short maxVal = x;
     if (y > maxVal)
     {
         axis = 1;
         maxVal = y;
     }
     if (z > maxVal)
     {
         axis = 2;
     }
     return axis;
 }
References G3D::x, G3D::y, and G3D::z.
Referenced by subdivide().
subdivide()
static void subdivide (BVItem * items, int nitems, int imin, int imax, int & curNode, dtBVNode * nodes) static
Definition at line 113 of file DetourNavMeshBuilder.cpp.
 {
     int inum = imax - imin;
     int icur = curNode;
     dtBVNode& node = nodes[curNode++];
     if (inum == 1)
     {
         // Leaf
         node.bmin[0] = items[imin].bmin[0];
         node.bmin[1] = items[imin].bmin[1];
         node.bmin[2] = items[imin].bmin[2];
         node.bmax[0] = items[imin].bmax[0];
         node.bmax[1] = items[imin].bmax[1];
         node.bmax[2] = items[imin].bmax[2];
         node.i = items[imin].i;
     }
     else
     {
         // Split
         calcExtends(items, nitems, imin, imax, node.bmin, node.bmax);
         int axis = longestAxis(node.bmax[0] - node.bmin[0],
                                node.bmax[1] - node.bmin[1],
                                node.bmax[2] - node.bmin[2]);
         if (axis == 0)
         {
             // Sort along x-axis
             qsort(items+imin, inum, sizeof(BVItem), compareItemX);
         }
         else if (axis == 1)
         {
             // Sort along y-axis
             qsort(items+imin, inum, sizeof(BVItem), compareItemY);
         }
         else
         {
             // Sort along z-axis
             qsort(items+imin, inum, sizeof(BVItem), compareItemZ);
         }
         int isplit = imin+inum/2;
         // Left
         subdivide(items, nitems, imin, isplit, curNode, nodes);
         // Right
         subdivide(items, nitems, isplit, imax, curNode, nodes);
         int iescape = curNode - icur;
         // Negative index means escape.
         node.i = -iescape;
     }
 }
References dtBVNode::bmax, BVItem::bmax, dtBVNode::bmin, BVItem::bmin, calcExtends(), compareItemX(), compareItemY(), compareItemZ(), dtBVNode::i, BVItem::i, and longestAxis().
Referenced by createBVTree().
Variable Documentation
MESH_NULL_IDX
unsigned short MESH_NULL_IDX = 0xffff static
Definition at line 30 of file DetourNavMeshBuilder.cpp.
Referenced by createBVTree(), and dtCreateNavMeshData().