Azerotcore-wotlk: formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > > Struct Template Reference
formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > > Struct Template Reference
#include <ranges.h>
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
FormatContext::iterator format (const T &values, FormatContext &ctx)
Public Attributes
formatting_range< Char > formatting
Detailed Description
template<typename T, typename Char>
struct formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >
Definition at line 333 of file ranges.h.
Member Function Documentation
format()
template<typename T , typename Char > template<typename FormatContext > FormatContext::iterator formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >::format (const T & values, FormatContext & ctx) inline
Definition at line 351 of file ranges.h.
{
     auto out = detail::copy(formatting.prefix, ctx.out());
     size_t i = 0;
     auto view = detail::range_to_view<T>::view(values);
     auto it = view.begin();
     auto end = view.end();
     for (; it != end; ++it) {
       if (i > 0) out = detail::write_delimiter(out);
       out = detail::write_range_entry<Char>(out, *it);
       ++i;
     }
     return detail::copy(formatting.postfix, out);
   }
References detail::copy(), formatting_range< Char, Enable >::postfix, formatting_range< Char, Enable >::prefix, and detail::write_delimiter().
parse()
template<typename T , typename Char > template<typename ParseContext > FMT_CONSTEXPR auto formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 346 of file ranges.h.
{
     return formatting.parse(ctx);
   }
References formatting_range< Char, Enable >::parse().
Member Data Documentation
formatting
template<typename T , typename Char > formatting_range<Char> formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >::formatting
Definition at line 343 of file ranges.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/ranges.h