Azerotcore-wotlk: deps/mysqllite/strings/llstr.c File Reference
llstr.c File Reference
#include <my_global.h>
#include "m_string.h"
Functions
char * llstr (longlong value, char *buff)
char * ullstr (longlong value, char *buff)
Function Documentation
llstr()
char* llstr (longlong value, char * buff)
Definition at line 30 of file llstr.c.
 {
   longlong10_to_str(value,buff,-10);
   return buff;
 }
References longlong10_to_str().
Referenced by getopt_ll_limit_value(), and my_print_variables().
ullstr()
char* ullstr (longlong value, char * buff)
Definition at line 36 of file llstr.c.
 {
   longlong10_to_str(value,buff,10);
   return buff;
 }
References longlong10_to_str().
Referenced by getopt_ull_limit_value().