Azerotcore-wotlk: npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI Struct Reference
npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI Struct Reference
Public Member Functions
npc_ulduar_expedition_engineerAI (Creature *pCreature)
void Reset () override
void SetData (uint32 id, uint32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
bool working
uint16 timer
ObjectGuid fixingGUID
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 801 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
npc_ulduar_expedition_engineerAI()
npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::npc_ulduar_expedition_engineerAI (Creature * pCreature) inline
Definition at line 803 of file boss_razorscale.cpp.
                                                               : NullCreatureAI(pCreature)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
Reset()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 813 of file boss_razorscale.cpp.
         {
             working = false;
             timer = 0;
             fixingGUID.Clear();
         }
References ObjectGuid::Clear(), fixingGUID, timer, and working.
Referenced by SetData(), and UpdateAI().
SetData()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 820 of file boss_razorscale.cpp.
         {
             switch (id)
             {
                 case 1: // start/resume repairing
                     working = true;
                     timer = 0;
                     fixingGUID.Clear();
                     break;
                 case 2: // stop repairing
                     Reset();
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STAND);
                     me->GetMotionMaster()->MoveTargetedHome();
                     break;
             }
         }
References ObjectGuid::Clear(), EMOTE_STATE_STAND, fixingGUID, Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MoveTargetedHome(), Reset(), Object::SetUInt32Value(), timer, UNIT_NPC_EMOTESTATE, and working.
UpdateAI()
void npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 837 of file boss_razorscale.cpp.
         {
             if (working)
             {
                 if (timer <= diff)
                 {
                     timer = 3000;
                     if (fixingGUID)
                     {
                         if (Creature* c = ObjectAccessor::GetCreature(*me, fixingGUID))
                             if (me->GetExactDist2dSq(c) <= 25.0f)
{
                                 if( me->GetUInt32Value(UNIT_NPC_EMOTESTATE) != EMOTE_STATE_WORK )
                                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_WORK);
                                 if (fabs(me->GetOrientation() - me->GetAngle(c)) > M_PI / 4)
                                     me->SetFacingToObject(c);
                                 c->AI()->SetData(2, 0);
                                 if (c->AI()->GetData(2))
                                     fixingGUID.Clear();
                             }
                     }
                     if (!fixingGUID)
                     {
                         Creature* razorscale = nullptr;
                         if( ObjectGuid rsGUID = pInstance->GetGuidData(TYPE_RAZORSCALE) )
                             razorscale = ObjectAccessor::GetCreature(*me, rsGUID);
                         if( !razorscale || !razorscale->IsInCombat() )
{
                             Reset();
                             me->GetMotionMaster()->MoveTargetedHome();
                             return;
                         }
                         for( int i = 0; i < 4; ++i )
                             if( ObjectGuid fs_GUID = pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_1 + i) )
                                 if( Creature* fs = ObjectAccessor::GetCreature(*me, fs_GUID) )
                                     if (!fs->AI()->GetData(2))
{
                                         float a = rand_norm() * M_PI;
                                         me->GetMotionMaster()->MovePoint(0, fs->GetPositionX() + 3.0f * cos(a), fs->GetPositionY() + 3.0f * sin(a), fs->GetPositionZ());
                                         fixingGUID = fs->GetGUID();
                                         return;
                                     }
                         Reset(); // all harpoons repaired
                         me->GetMotionMaster()->MoveTargetedHome();
                     }
                 }
                 else
                     timer -= diff;
             }
             else if (me->GetUInt32Value(UNIT_NPC_EMOTESTATE) == EMOTE_STATE_WORK)
                 me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STAND);
         }
References ObjectGuid::Clear(), DATA_HARPOON_FIRE_STATE_1, EMOTE_STATE_STAND, EMOTE_STATE_WORK, fixingGUID, Position::GetAngle(), ObjectAccessor::GetCreature(), Position::GetExactDist2dSq(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Object::GetUInt32Value(), Unit::IsInCombat(), CreatureAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTargetedHome(), pInstance, rand_norm(), Reset(), Unit::SetFacingToObject(), Object::SetUInt32Value(), timer, TYPE_RAZORSCALE, UNIT_NPC_EMOTESTATE, and working.
Member Data Documentation
fixingGUID
ObjectGuid npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::fixingGUID
Definition at line 811 of file boss_razorscale.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
pInstance
InstanceScript* npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::pInstance
Definition at line 808 of file boss_razorscale.cpp.
Referenced by npc_ulduar_expedition_engineerAI(), and UpdateAI().
timer
uint16 npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::timer
Definition at line 810 of file boss_razorscale.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
working
bool npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::working
Definition at line 809 of file boss_razorscale.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp