Azerotcore-wotlk: LiquidHeader Class Reference
LiquidHeader Class Reference
#include <Utils.h>
Public Member Functions
LiquidHeader ()
Static Public Member Functions
static LiquidHeader Read (FILE *stream)
Public Attributes
uint32 CountXVertices
uint32 CountYVertices
uint32 Width
uint32 Height
Vector3 BaseLocation
uint16 MaterialId
Detailed Description
Definition at line 240 of file Utils.h.
Constructor & Destructor Documentation
LiquidHeader()
LiquidHeader::LiquidHeader () inline
Definition at line 243 of file Utils.h.
 {}
Member Function Documentation
Read()
LiquidHeader LiquidHeader::Read (FILE * stream) static
Definition at line 423 of file Utils.cpp.
 {
     LiquidHeader ret;
     int count = 0;
     count += fread(&ret.CountXVertices, sizeof(uint32), 1, stream);
     count += fread(&ret.CountYVertices, sizeof(uint32), 1, stream);
     count += fread(&ret.Width, sizeof(uint32), 1, stream);
     count += fread(&ret.Height, sizeof(uint32), 1, stream);
     ret.BaseLocation = Vector3::Read(stream);
     count += fread(&ret.MaterialId, sizeof(uint16), 1, stream);
     if (count != 5)
         printf("LiquidHeader::Read: Failed to read some data expected 5, read %d\n", count);
     return ret;
 }
References count(), printf(), Vector3::Read(), and ret.
Referenced by WorldModelGroup::ReadLiquid().
Member Data Documentation
BaseLocation
Vector3 LiquidHeader::BaseLocation
Definition at line 248 of file Utils.h.
Referenced by WorldModelHandler::InsertModelGeometry().
CountXVertices
uint32 LiquidHeader::CountXVertices
Definition at line 244 of file Utils.h.
Referenced by LiquidData::Read().
CountYVertices
uint32 LiquidHeader::CountYVertices
Definition at line 245 of file Utils.h.
Referenced by LiquidData::Read().
Height
uint32 LiquidHeader::Height
Definition at line 247 of file Utils.h.
Referenced by WorldModelHandler::InsertModelGeometry(), and LiquidData::Read().
MaterialId
uint16 LiquidHeader::MaterialId
Definition at line 249 of file Utils.h.
Width
uint32 LiquidHeader::Width
Definition at line 246 of file Utils.h.
Referenced by WorldModelHandler::InsertModelGeometry(), and LiquidData::Read().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp