Azerotcore-wotlk: SpellScriptLoader Class Reference
SpellScriptLoader Class Reference
#include <ScriptMgr.h>
Public Member Functions
bool IsDatabaseBound () const override
virtual SpellScript * GetSpellScript () const
virtual AuraScript * GetAuraScript () const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
SpellScriptLoader (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 136 of file ScriptMgr.h.
Constructor & Destructor Documentation
SpellScriptLoader()
SpellScriptLoader::SpellScriptLoader (const char * name) protected
Definition at line 3184 of file ScriptMgr.cpp.
     : ScriptObject(name)
 {
     ScriptRegistry<SpellScriptLoader>::AddScript(this);
 }
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
GetAuraScript()
virtual AuraScript* SpellScriptLoader::GetAuraScript () const inline virtual
Reimplemented in spell_rog_killing_spree, spell_q10923_evil_draws_near_periodic, spell_q10929_fumping, spell_q10930_big_bone_worm, spell_q10563_q10596_to_legion_hold, spell_npc22275_crystal_prison, spell_ragin_flames_inferno, spell_the_eye_countercharge, spell_kaelthas_flame_strike, spell_kaelthas_burn, spell_kaelthas_remote_toy, spell_astromancer_solarian_transform, spell_astromancer_wrath_of_the_astromancer, spell_alar_dive_bomb, spell_alar_ember_blast_death, spell_alar_flame_quills, spell_botanica_shift_form, spell_botanica_call_of_the_falcon, spell_arcatraz_soul_steal, spell_tsh_shadow_sear, spell_magtheridon_shadow_grasp, spell_broggok_poison_cloud, spell_gruul_ground_slam_trigger, spell_gen_allergies, spell_serpentshrine_cavern_coilfang_water, spell_serpentshrine_cavern_infection, spell_serpentshrine_cavern_serpentshrine_parasite_trigger, spell_serpentshrine_cavern_serpentshrine_parasite, spell_lurker_below_spout, spell_leotheras_demon_link, spell_leotheras_insidious_whisper, spell_lady_vashj_magic_barrier, spell_hydross_mark_of_hydross, spell_hydross_cleansing_field_command, spell_hydross_cleansing_field_aura, spell_karathress_power_of_caribdis, spell_mark_of_kazzak, spell_black_temple_dementia, spell_black_temple_curse_of_vitality, spell_black_temple_consuming_strikes, spell_black_temple_spell_absorption, spell_black_temple_shadow_inferno, spell_black_temple_charge_rage, spell_black_temple_wyvern_sting, spell_black_temple_skeleton_shot, spell_black_temple_curse_of_the_bleakheart, spell_black_template_harpooners_mark, spell_illidari_council_deadly_strike, spell_illidari_council_reflective_shield, spell_illidari_council_balance_of_power, spell_teron_gorefiend_shadowy_construct, spell_teron_gorefiend_spiritual_vengeance, spell_teron_gorefiend_spirit_lance, spell_teron_gorefiend_shadow_of_death, spell_shade_of_akama_shade_soul_channel, spell_reliquary_of_souls_spite, spell_reliquary_of_souls_aura_of_anger, spell_reliquary_of_souls_aura_of_desire, spell_reliquary_of_souls_fixate, spell_reliquary_of_souls_aura_of_suffering, spell_mother_shahraz_fatal_attraction_aura, spell_mother_shahraz_saber_lash, spell_mother_shahraz_beam_periodic, spell_mother_shahraz_random_periodic, spell_illidan_cage_trap_stun, spell_illidan_demon_transform2, spell_illidan_demon_transform1, spell_illidan_tear_of_azzinoth_summon_channel, spell_illidan_parasitic_shadowfiend_trigger, spell_illidan_parasitic_shadowfiend, spell_auchenai_possess, spell_wintergrasp_hide_small_elementals, spell_close_rift, spell_q13003_thursting_hodirs_spear, spell_charge_shield_bomber, spell_warhead_fuse, spell_z_check, spell_infected_worgen_bite, spell_q12243_fire_upon_the_waters, spell_q11919_q11940_drake_hunt, spell_destroy_door_seal, spell_optic_link, spell_flame_warder_meteor_fists, spell_koralon_meteor_fists, spell_voa_overcharge, spell_svala_ritual_strike, spell_ticking_time_bomb, spell_frost_tomb, spell_ulduar_arachnopod_damaged, spell_ulduar_energy_sap, spell_yogg_saron_grim_reprisal, spell_yogg_saron_sanity_well, spell_yogg_saron_insane, spell_yogg_saron_empowered, spell_yogg_saron_protective_gaze, spell_yogg_saron_shadow_beacon, spell_yogg_saron_brain_link, spell_yogg_saron_malady_of_the_mind, spell_xt002_searing_light_spawn_life_spark, spell_xt002_gravity_bomb_aura, spell_thorim_trash_impale, spell_thorim_lightning_pillar_P2, spell_mimiron_p3wx2_laser_barrage, spell_mimiron_rapid_burst, spell_kologarn_stone_shout, spell_ulduar_stone_grip, spell_ignis_slag_pot, spell_ignis_scorch, spell_hodir_starlight, spell_hodir_toasty_fire, spell_hodir_storm_cloud, spell_hodir_storm_power, spell_hodir_flash_freeze, spell_hodir_biting_cold_player_aura, spell_hodir_biting_cold_main_aura, spell_saronite_vapors_dummy, spell_mark_of_the_faceless_periodic, spell_aura_of_despair, spell_shield_generator, spell_transitus_shield_beam, spell_orbital_supports, spell_vehicle_circuit_overload, spell_tar_blaze, spell_systems_shutdown, spell_load_into_catapult, spell_assembly_rune_of_summoning, spell_shield_of_runes, spell_algalon_remove_phase, spell_algalon_collapse, spell_algalon_phase_punch, spell_hos_dark_matter, spell_oculus_drake_flag, spell_oculus_rider_aura, spell_oculus_soar, spell_oculus_evasive_charges, spell_oculus_ride_ruby_emerald_amber_drake_que, spell_oculus_dream_funnel, spell_oculus_temporal_rift, spell_oculus_evasive_maneuvers, spell_oculus_stop_time, spell_boss_magus_telestra_summon_telestra_clones, spell_kelthuzad_detonate_mana, spell_grobbulus_mutating_injection, spell_four_horsemen_mark, spell_ioc_parachute_ic, spell_ioc_repair_turret, spell_icc_yh_volley, spell_icc_yf_frozen_orb, spell_icc_dark_reckoning, spell_icc_web_wrap, spell_icc_stoneform, spell_valithria_suppression, spell_dreamwalker_summon_suppresser, spell_dreamwalker_decay_periodic_timer, spell_dreamwalker_mana_void, spell_dreamwalker_nightmare_cloud, spell_the_lich_king_soul_rip, spell_the_lich_king_dark_hunger, spell_the_lich_king_lights_favor, spell_the_lich_king_harvest_soul, spell_the_lich_king_vile_spirits, spell_the_lich_king_soul_reaper, spell_the_lich_king_shadow_trap_visual, spell_the_lich_king_necrotic_plague_jump, spell_the_lich_king_necrotic_plague, spell_the_lich_king_infest, spell_frostwarden_handler_focus_fire, spell_sindragosa_soul_preservation, spell_sindragosa_ice_tomb, spell_sindragosa_frost_beacon, spell_sindragosa_instability, spell_sindragosa_permeating_chill, spell_sindragosa_unchained_magic, spell_rotface_unstable_ooze_explosion_suicide, spell_rotface_mutated_infection, spell_putricide_mutated_transformation_dismiss, spell_putricide_mutation_init, spell_putricide_unbound_plague_dmg, spell_putricide_mutated_plague, spell_putricide_gaseous_bloat, spell_putricide_grow_stacker, spell_deathwhisper_mana_barrier, spell_igb_on_gunship_deck, spell_igb_overheat, spell_igb_periodic_trigger_with_power_cost, spell_igb_explosion_main, spell_igb_rocket_pack_useable, spell_igb_rocket_pack, spell_festergut_blighted_spores, spell_deathbringer_blood_power, spell_deathbringer_blood_link_blood_beast_aura, spell_deathbringer_blood_link_aura, spell_blood_queen_essence_of_the_blood_queen, spell_blood_queen_frenzied_bloodthirst, spell_blood_queen_pact_of_the_darkfallen_dmg, spell_valanar_kinetic_bomb_absorb, spell_valanar_kinetic_bomb, spell_blood_council_shadow_prison, spell_sladran_grip_of_sladran, spell_moorabi_mojo_frenzy, spell_pos_glacial_strike, spell_pos_blight, spell_pos_empowered_blizzard, spell_exploding_orb_auto_grow, spell_krick_explosive_barrage, spell_hor_gunship_cannon_fire, spell_hor_shared_suffering, spell_shield_of_bones, spell_wailing_souls_periodic, spell_bronjahm_soulstorm_visual, spell_bronjahm_soulstorm_channel_ooc, spell_dtk_raise_dead, spell_trollgore_corpse_explode, spell_tharon_ja_dummy, spell_tharon_ja_curse_of_life, spell_novos_crystal_handler_death, spell_dred_grievious_bite, spell_valkyr_ball_periodic_dummy, spell_valkyr_touch, spell_valkyr_essence, spell_toc25_mistress_kiss, spell_faction_champion_warl_unstable_affliction, spell_gen_leeching_swarm, spell_pursuing_spikes, spell_reflective_shield, spell_halion_twilight_cutter_periodic, spell_halion_leave_twilight_realm, spell_halion_twilight_realm, spell_halion_twilight_phasing, spell_halion_marks, spell_halion_combustion_consumption, spell_halion_meteor_strike_spread, spell_halion_meteor_strike_marker, spell_azjol_nerub_web_wrap, spell_hadronox_leech_poison, spell_hadronox_summon_periodic, spell_azjol_nerub_carrion_beetels, spell_shadow_sickle_periodic_damage, spell_jedoga_sacrafice_beam, spell_mount_check, spell_black_morass_corrupt_medivh, spell_boss_salramm_steal_flesh, spell_mark_of_kazrogal, spell_pilgrims_bounty_food, spell_pilgrims_bounty_serve_generic, spell_midsummer_torch_quest, spell_midsummer_ribbon_pole, spell_gen_crab_disguise, spell_gen_aura_service_uniform, spell_love_is_in_the_air_romantic_picnic, spell_love_in_air_periodic_perfumes, spell_love_in_air_perfume_immune, spell_hallows_end_base_fire, spell_direbrew_disarm, spell_barreled_control_aura, spell_send_mug_control_aura, spell_brewfest_reveler_transform, spell_brewfest_ram_fatigue, spell_brewfest_main_ram_buff, spell_threatening_gaze, spell_hexlord_unstable_affliction, spell_uldaman_stoned, spell_entropius_void_zone_visual, spell_muru_darkness, spell_muru_summon_blood_elves_periodic, spell_kiljaeden_armageddon_periodic, spell_kiljaeden_vengeance_of_the_blue_flight, spell_kiljaeden_darkness, spell_kiljaeden_shadow_spike, spell_kalecgos_spectral_realm, spell_kalecgos_curse_of_boundless_agony, spell_felmyst_fog_of_corruption_charm, spell_temple_of_atal_hakkar_hex_of_jammal_an, spell_shadowfang_keep_forsaken_skills, spell_shadowfang_keep_haunting_spirits, spell_scholomance_boon_of_life, spell_scholomance_fixate, spell_chapter5_light_of_dawn_aura, spell_karazhan_overload, spell_karazhan_brittle_bones, spell_midnight_fixate, spell_mc_play_dead, spell_majordomo_separation_nexiety, spell_garr_separation_nexiety, spell_geddon_armageddon, spell_geddon_inferno, spell_vael_burning_adrenaline, GenericSpellAndAuraScriptLoader< Ts >, and spell_amanitar_remove_mushroom_power.
Definition at line 148 of file ScriptMgr.h.
 { return nullptr; }
Referenced by ScriptMgr::CreateAuraScripts().
GetSpellScript()
virtual SpellScript* SpellScriptLoader::GetSpellScript () const inline virtual
Reimplemented in spell_mark_of_nature, spell_dream_fog_sleep, spell_rog_killing_spree, spell_q11515_fel_siphon_dummy, spell_q55_sacred_cleansing, spell_q10898_skywing, spell_q10923_evil_draws_near_visual, spell_q10923_evil_draws_near_summon, spell_q10036_torgos, spell_q10929_fumping, spell_q10930_big_bone_worm, spell_q10612_10613_the_fel_and_the_furious, spell_q10935_the_exorcism_of_colonel_jules, spell_oscillating_field, spell_capacitus_polarity_shift, spell_capacitus_polarity_charge, spell_kaelthas_summon_nether_vapor, spell_kaelthas_nether_beam, spell_kaelthas_gravity_lapse, spell_kaelthas_mind_control, spell_kaelthas_resurrection, spell_kaelthas_summon_weapons, spell_kaelthas_kael_phase_two, spell_alar_ember_blast, spell_commander_sarannis_summon_reinforcements, spell_tsh_shoot_flame_arrow, spell_tsh_shadow_bolt, spell_magtheridon_blaze, spell_vazruden_call_nazan, spell_vazruden_fireball, spell_gruul_shatter_effect, spell_gruul_shatter, spell_gruul_ground_slam, spell_serpentshrine_cavern_serpentshrine_parasite_trigger, spell_morogrim_tidewalker_water_globule_new_target, spell_morogrim_tidewalker_watery_grave, spell_lurker_below_spout_cone, spell_leotheras_clear_consuming_madness, spell_leotheras_insidious_whisper, spell_leotheras_chaos_blast, spell_leotheras_whirlwind, spell_lady_vashj_spore_drop_effect, spell_lady_vashj_summon_sporebat, spell_lady_vashj_remove_tainted_cores, spell_black_temple_bloodbolt, spell_black_template_free_friend, spell_illidari_council_judgement, spell_illidari_council_empyreal_balance, spell_najentus_hurl_spine, spell_najentus_needle_spine, spell_shade_of_akama_akama_soul_expel, spell_reliquary_of_souls_fixate, spell_mother_shahraz_fatal_attraction_dummy, spell_mother_shahraz_fatal_attraction, spell_illidan_cage_trap, spell_illidan_found_target, spell_illidan_flame_burst, spell_illidan_shadow_prison, spell_illidan_glaive_throw, spell_illidan_parasitic_shadowfiend_trigger, spell_illidan_draw_soul, spell_gurtogg_eject, spell_gurtogg_bloodboil, spell_murmur_thundering_storm, spell_murmur_sonic_boom_effect, spell_wg_reduce_damage_by_distance, spell_wintergrasp_water, spell_wintergrasp_portal, spell_wintergrasp_rp_gg, spell_wintergrasp_create_vehicle, spell_wintergrasp_force_building, spell_q13007_iron_colossus, spell_shango_tracks, spell_q12589_shoot_rjr, spell_q12620_the_lifewarden_wrath, spell_q12726_song_of_wind_and_water, spell_onslaught_or_call_bone_gryphon, spell_anti_air_rocket_bomber, spell_fight_fire_bomber, spell_charge_shield_bomber, spell_switch_infragreen_bomber_station, spell_warhead_detonate, spell_vehicle_warhead_fuse, spell_shredder_delivery, spell_q12096_q12092_bark, spell_q12096_q12092_dummy, spell_q24545_aod_special, spell_q12478_frostmourne_cavern, spell_q11719_bloodspore_ruination_45997, spell_arcane_chains_character_force_cast, spell_voa_flaming_cinder, spell_voa_lightning_nova, spell_archavon_rock_shards, spell_svala_ritual_strike, spell_yogg_saron_target_selectors, spell_yogg_saron_in_the_maws_of_the_old_god, spell_yogg_saron_empowering_shadows, spell_yogg_saron_sanity_reduce, spell_yogg_saron_insane_periodic_trigger, spell_yogg_saron_lunatic_gaze, spell_yogg_saron_titanic_storm, spell_yogg_saron_destabilization_matrix, spell_yogg_saron_brain_link, spell_xt002_searing_light_spawn_life_spark, spell_xt002_gravity_bomb_damage, spell_xt002_gravity_bomb_aura, spell_xt002_tympanic_tantrum, spell_kologarn_stone_shout, spell_ulduar_squeezed_lifeless, spell_ulduar_stone_grip_cast_target, spell_ignis_grab_initial, spell_hodir_flash_freeze, spell_hodir_periodic_icicle, spell_hodir_shatter_chest, spell_saronite_vapors_damage, spell_mark_of_the_faceless_drainhealth, spell_demolisher_ride_vehicle, spell_thorims_hammer, spell_vehicle_grab_pyrite, spell_vehicle_throw_passenger, spell_pursue, spell_auto_repair, spell_auriaya_sentinel_blast, spell_assembly_meltdown, spell_algalon_supermassive_fail, spell_algalon_big_bang, spell_algalon_cosmic_smash_damage, spell_algalon_trigger_3_adds, spell_krystallus_shatter_effect, spell_krystallus_shatter, spell_loken_pulsing_shockwave, spell_oculus_call_ruby_emerald_amber_drake, spell_oculus_touch_the_nightmare, spell_oculus_shock_lance, spell_boss_magus_telestra_gravity_well, spell_eoe_ph3_surge_of_power, spell_thaddius_polarity_shift, spell_thaddius_pos_neg_charge, spell_sapphiron_frost_explosion, spell_kelthuzad_frost_blast, spell_grobbulus_poison, spell_gothik_shadow_bolt_volley, spell_gluth_decimate, spell_ioc_launch, spell_ioc_gunship_portal, spell_ioc_bomb_blast_criteria, spell_trigger_spell_from_caster, spell_icc_shattered_bones, spell_icc_yd_summon_undead, spell_stinky_precious_decimate, spell_icc_soul_missile, spell_svalna_remove_spear, spell_svalna_revive_champion, spell_icc_harvest_blight_specimen, spell_frost_giant_death_plague, spell_icc_geist_alarm, spell_icc_sprit_alarm, spell_dreamwalker_summon_suppresser_effect, spell_dreamwalker_summoner, spell_dreamwalker_twisted_nightmares, spell_dreamwalker_summon_portal, spell_the_lich_king_trigger_vile_spirit, spell_the_lich_king_summon_spirit_bomb, spell_the_lich_king_restore_soul, spell_the_lich_king_vile_spirit_damage_target_search, spell_the_lich_king_vile_spirit_move_target_search, spell_the_lich_king_vile_spirits_visual, spell_the_lich_king_life_siphon, spell_the_lich_king_cast_back_to_caster, spell_the_lich_king_valkyr_target_search, spell_the_lich_king_teleport_to_frostmourne_hc, spell_the_lich_king_summon_into_air, spell_the_lich_king_defile, spell_the_lich_king_raging_spirit, spell_the_lich_king_ice_burst_target_search, spell_the_lich_king_shadow_trap_periodic, spell_the_lich_king_necrotic_plague_jump, spell_the_lich_king_play_movie, spell_the_lich_king_jump_remove_aura, spell_the_lich_king_jump, spell_the_lich_king_quake, spell_sindragosa_frost_breath, spell_frostwarden_handler_focus_fire, spell_frostwarden_handler_order_whelp, spell_rimefang_icy_blast, spell_sindragosa_mystic_buffet, spell_sindragosa_ice_tomb, spell_sindragosa_ice_tomb_filter, spell_sindragosa_icy_grip_jump, spell_sindragosa_icy_grip, spell_sindragosa_unchained_magic, spell_sindragosa_s_fury, spell_rotface_unstable_ooze_explosion, spell_rotface_unstable_ooze_explosion_init, spell_rotface_large_ooze_buff_combine, spell_rotface_large_ooze_combine, spell_rotface_little_ooze_combine, spell_rotface_mutated_infection, spell_putricide_regurgitated_ooze, spell_putricide_eat_ooze, spell_putricide_mutated_transformation_dmg, spell_putricide_mutated_transformation, spell_putricide_mutation_init, spell_putricide_clear_aura_effect_value, spell_putricide_choking_gas_bomb, spell_putricide_unbound_plague, spell_putricide_ooze_eruption_searcher, spell_putricide_ooze_channel, spell_putricide_tear_gas_effect, spell_putricide_unstable_experiment, spell_putricide_slime_puddle_spawn, spell_putricide_slime_puddle, spell_marrowgar_bone_slice, spell_marrowgar_bone_storm, spell_marrowgar_coldflame_bonestorm, spell_marrowgar_bone_spike_graveyard, spell_marrowgar_coldflame, spell_igb_below_zero, spell_igb_rocket_artillery_explosion, spell_igb_rocket_artillery, spell_igb_burning_pitch, spell_igb_burning_pitch_selector, spell_igb_incinerating_blast, spell_igb_cannon_blast, spell_igb_teleport_players_on_victory, spell_igb_explosion, spell_igb_gunship_fall_teleport, spell_igb_check_for_players, spell_igb_teleport_to_enemy_ship, spell_festergut_gastric_bloat, spell_festergut_pungent_blight, spell_deathbringer_boiling_blood, spell_deathbringer_blood_nova_targeting, spell_deathbringer_blood_power, spell_deathbringer_blood_link, spell_blood_queen_presence_of_the_darkfallen, spell_blood_queen_swarming_shadows_floor_dmg, spell_blood_queen_vampiric_bite, spell_blood_queen_bloodbolt, spell_blood_queen_pact_of_the_darkfallen_dmg_target, spell_blood_queen_pact_of_the_darkfallen, spell_blood_council_summon_shadow_resonance, spell_valanar_kinetic_bomb_summon, spell_valanar_kinetic_bomb_knockback, spell_valanar_kinetic_bomb, spell_taldaram_ball_of_inferno_flame, spell_taldaram_summon_flame_ball, spell_taldaram_glittering_sparks, spell_blood_council_shadow_prison_damage, spell_galdarah_transform, spell_galdarah_impaling_charge, spell_drakkari_colossus_face_me, spell_drakkari_colossus_surge, spell_drakkari_colossus_emerge, spell_pos_rimefang_frost_nova, spell_pos_slave_trigger_closest, spell_garfrost_permafrost, spell_bronjahm_soulstorm_targeting, spell_bronjahm_magic_bane, spell_dtk_summon_random_drakkari, spell_trollgore_invader_taunt, spell_trollgore_consume, spell_tharon_ja_clear_gift_of_tharon_ja, spell_novos_summon_minions, spell_novos_despawn_crystal_handler, spell_dred_raptor_call, spell_mistress_kiss_area, spell_gen_leeching_swarm_dmg, spell_toc5_light_rain, spell_eadric_radiance, spell_ruby_sanctum_rallying_shout, spell_saviana_conflagration_throwback, spell_saviana_conflagration_init, spell_halion_twilight_mending, spell_halion_twilight_division, spell_halion_summon_exit_portals, spell_halion_twilight_cutter, spell_halion_twilight_phasing, spell_halion_clear_debuffs, spell_halion_damage_aoe_summon, spell_halion_blazing_aura, spell_halion_meteor_strike_targeting, spell_baltharus_enervating_brand_trigger, spell_sartharion_lava_strike, spell_azjol_nerub_fixate, spell_azjol_nerub_impale_summon, spell_azjol_nerub_pound, spell_prince_taldaram_flame_sphere_summon, spell_prince_taldaram_conjure_flame_sphere, spell_random_lightning_visual_effect, spell_volazj_whisper, spell_herald_volzaj_insanity, spell_ahn_kahet_swarmer_aura, spell_zulfarrak_unlocking, spell_zulfarrak_summon_zulfarrak_zombies, spell_gordunni_trap, spell_energize_aoe, spell_ooze_zap_channel_end, spell_ooze_zap, spell_voodoo, spell_voljin_war_drums, spell_skeram_arcane_explosion, spell_egg_explosion, spell_mark_of_kazrogal, spell_hand_of_death, spell_finger_of_death, spell_red_sky_effect, spell_winter_veil_shoot_air_rifle, spell_winter_veil_racer_slam_hit, spell_winter_veil_racer_rocket_slam, spell_winter_wondervolt_trap, spell_winter_veil_mistletoe, spell_pilgrims_bounty_food, spell_pilgrims_bounty_turkey_tracker, spell_pilgrims_bounty_feast_on_generic, spell_pilgrims_bounty_pass_generic, spell_midsummer_juggling_torch, spell_midsummer_fling_torch, spell_item_create_heart_candy, spell_hallows_end_bucket_lands, spell_hallows_end_tricky_treat, spell_hallows_end_candy, spell_hallows_end_trick_or_treat, spell_hallows_end_put_costume, spell_hallows_end_trick, spell_request_second_mug, spell_send_mug_target_picker, spell_direbrew_summon_mole_machine_target_picker, spell_brewfest_relay_race_force_cast, spell_brewfest_add_mug, spell_brewfest_toss_mug, spell_brewfest_unfill_keg, spell_brewfest_fill_keg, spell_q11117_catch_the_wild_wolpertinger, spell_brewfest_apple_trap, spell_banging_the_gong, spell_blight_worm_ingest, spell_bh_cleanse_quel_delar, spell_razelikh_teleport_group, spell_uldaman_boss_agro_archaedas, spell_uldaman_sub_boss_agro_keepers, spell_cataclysm_breath, spell_entropius_black_hole_effect, spell_entropius_negative_energy, spell_kiljaeden_dragon_breath, spell_kiljaeden_armageddon_missile, spell_kiljaeden_power_of_the_blue_flight, spell_kiljaeden_flame_dart, spell_kiljaeden_sinister_reflection_clone, spell_kiljaeden_sinister_reflection, spell_kalecgos_spectral_realm_dummy, spell_kalecgos_spectral_blast_dummy, spell_felmyst_open_brutallus_back_doors, spell_felmyst_fog_of_corruption, spell_eredar_twins_blaze, spell_eredar_twins_handle_touch, spell_eredar_twins_apply_flame_touched, spell_eredar_twins_apply_dark_touched, spell_brutallus_burn, spell_madrigosa_deactivate_barrier, spell_madrigosa_activate_barrier, spell_temple_of_atal_hakkar_awaken_the_soulflayer, spell_kormok_summon_bone_minions, spell_kormok_summon_bone_mages, spell_chapter5_rebuke, spell_q12779_an_end_to_all_things, spell_q12698_the_gift_that_keeps_on_giving, spell_item_gift_of_the_harvester, spell_q12641_death_comes_from_on_high_summon_ghouls, spell_mt_phoenix_burn, spell_karazhan_blink, spell_moroes_vanish, spell_gnomeregan_radiation_bolt, spell_shazzrah_gate_dummy, spell_summon_ragnaros, spell_hate_to_zero, spell_magmadar_lava_bomb, spell_garr_frenzy, spell_egg_event, GenericSpellAndAuraScriptLoader< Ts >, and spell_bwl_shadowflame.
Definition at line 145 of file ScriptMgr.h.
 { return nullptr; }
Referenced by ScriptMgr::CreateSpellScripts().
IsDatabaseBound()
bool SpellScriptLoader::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
Definition at line 142 of file ScriptMgr.h.
 { return true; }
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptMgr.h
src/server/game/Scripting/ScriptMgr.cpp