Azerotcore-wotlk: ScalingStatValuesEntry Struct Reference
ScalingStatValuesEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
uint32 getssdMultiplier (uint32 mask) const
uint32 getArmorMod (uint32 mask) const
uint32 getDPSMod (uint32 mask) const
uint32 getSpellBonus (uint32 mask) const
uint32 getFeralBonus (uint32 mask) const
Public Attributes
uint32 Id
uint32 Level
uint32 ssdMultiplier [4]
uint32 armorMod [4]
uint32 dpsMod [6]
uint32 spellPower
uint32 ssdMultiplier2
uint32 ssdMultiplier3
uint32 armorMod2 [5]
Detailed Description
Definition at line 1412 of file DBCStructure.h.
Member Function Documentation
getArmorMod()
uint32 ScalingStatValuesEntry::getArmorMod (uint32 mask) const inline
Definition at line 1438 of file DBCStructure.h.
     {
         if (mask & 0x00F801E0)
         {
             if (mask & 0x00000020) return armorMod[0];      // Cloth shoulder
             if (mask & 0x00000040) return armorMod[1];      // Leather shoulder
             if (mask & 0x00000080) return armorMod[2];      // Mail shoulder
             if (mask & 0x00000100) return armorMod[3];      // Plate shoulder
             if (mask & 0x00080000) return armorMod2[0];      // cloak
             if (mask & 0x00100000) return armorMod2[1];      // cloth
             if (mask & 0x00200000) return armorMod2[2];      // leather
             if (mask & 0x00400000) return armorMod2[3];      // mail
             if (mask & 0x00800000) return armorMod2[4];      // plate
         }
         return 0;
     }
References armorMod, and armorMod2.
Referenced by Player::_ApplyItemBonuses().
getDPSMod()
uint32 ScalingStatValuesEntry::getDPSMod (uint32 mask) const inline
Definition at line 1456 of file DBCStructure.h.
     {
         if (mask & 0x7E00)
         {
             if (mask & 0x00000200) return dpsMod[0];        // Weapon 1h
             if (mask & 0x00000400) return dpsMod[1];        // Weapon 2h
             if (mask & 0x00000800) return dpsMod[2];        // Caster dps 1h
             if (mask & 0x00001000) return dpsMod[3];        // Caster dps 2h
             if (mask & 0x00002000) return dpsMod[4];        // Ranged
             if (mask & 0x00004000) return dpsMod[5];        // Wand
         }
         return 0;
     }
References dpsMod.
Referenced by Player::_ApplyItemBonuses(), and Player::_ApplyWeaponDamage().
getFeralBonus()
uint32 ScalingStatValuesEntry::getFeralBonus (uint32 mask) const inline
Definition at line 1476 of file DBCStructure.h.
     {
         if (mask & 0x00010000) return 0;                    // not used?
         return 0;
     }
Referenced by Player::_ApplyItemBonuses().
getSpellBonus()
uint32 ScalingStatValuesEntry::getSpellBonus (uint32 mask) const inline
Definition at line 1470 of file DBCStructure.h.
     {
         if (mask & 0x00008000) return spellPower;
         return 0;
     }
References spellPower.
Referenced by Player::_ApplyItemBonuses().
getssdMultiplier()
uint32 ScalingStatValuesEntry::getssdMultiplier (uint32 mask) const inline
Definition at line 1424 of file DBCStructure.h.
     {
         if (mask & 0x4001F)
         {
             if (mask & 0x00000001) return ssdMultiplier[0]; // Shoulder
             if (mask & 0x00000002) return ssdMultiplier[1]; // Trinket
             if (mask & 0x00000004) return ssdMultiplier[2]; // Weapon1H
             if (mask & 0x00000008) return ssdMultiplier2;
             if (mask & 0x00000010) return ssdMultiplier[3]; // Ranged
             if (mask & 0x00040000) return ssdMultiplier3;
         }
         return 0;
     }
References ssdMultiplier, ssdMultiplier2, and ssdMultiplier3.
Referenced by Player::_ApplyItemBonuses().
Member Data Documentation
armorMod
uint32 ScalingStatValuesEntry::armorMod[4]
Definition at line 1417 of file DBCStructure.h.
Referenced by getArmorMod().
armorMod2
uint32 ScalingStatValuesEntry::armorMod2[5]
Definition at line 1422 of file DBCStructure.h.
Referenced by getArmorMod().
dpsMod
uint32 ScalingStatValuesEntry::dpsMod[6]
Definition at line 1418 of file DBCStructure.h.
Referenced by getDPSMod().
Id
uint32 ScalingStatValuesEntry::Id
Definition at line 1414 of file DBCStructure.h.
Level
uint32 ScalingStatValuesEntry::Level
Definition at line 1415 of file DBCStructure.h.
spellPower
uint32 ScalingStatValuesEntry::spellPower
Definition at line 1419 of file DBCStructure.h.
Referenced by getSpellBonus().
ssdMultiplier
uint32 ScalingStatValuesEntry::ssdMultiplier[4]
Definition at line 1416 of file DBCStructure.h.
Referenced by getssdMultiplier().
ssdMultiplier2
uint32 ScalingStatValuesEntry::ssdMultiplier2
Definition at line 1420 of file DBCStructure.h.
Referenced by getssdMultiplier().
ssdMultiplier3
uint32 ScalingStatValuesEntry::ssdMultiplier3
Definition at line 1421 of file DBCStructure.h.
Referenced by getssdMultiplier().
The documentation for this struct was generated from the following file:
src/server/shared/DataStores/DBCStructure.h