Azerotcore-wotlk: spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript Class Reference
spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_herald_volzaj_insanity_SpellScript)
bool Load () override
void HandleDummyEffect (std::list< WorldObject * > &targets)
void HandleAfterCast ()
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 362 of file boss_herald_volazj.cpp.
Member Function Documentation
HandleAfterCast()
void spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleAfterCast () inline private
Definition at line 448 of file boss_herald_volazj.cpp.
         {
             GetCaster()->ToCreature()->AI()->SetData(DATA_SET_INSANITY_PHASE, 1);
         }
References Creature::AI(), DATA_SET_INSANITY_PHASE, SpellScript::GetCaster(), UnitAI::SetData(), and Object::ToCreature().
Referenced by Register().
HandleDummyEffect()
void spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect (std::list< WorldObject * > & targets) inline private
Definition at line 368 of file boss_herald_volazj.cpp.
         {
             Unit* caster = GetCaster();
             if (!caster)
             {
                 targets.clear();
                 return;
             }
             if (!targets.empty())
             {
                 targets.remove_if([this](WorldObject* targetObj) -> bool
                 {
                     return !targetObj || targetObj->GetTypeId() != TYPEID_PLAYER || !targetObj->ToPlayer()->IsInCombatWith(GetCaster()) ||
                             targetObj->GetDistance(GetCaster()) >= (MAX_VISIBILITY_DISTANCE * 2);
                 });
             }
             if (targets.empty())
             {
                 return;
             }
             // Start channel visual and set self as unnattackable
             caster->ToCreature()->AI()->Talk(SAY_INSANITY);
             caster->CastSpell(caster, SPELL_WHISPER_INSANITY, true);
             caster->RemoveAllAuras();
             caster->CastSpell(caster, INSANITY_VISUAL, true);
             caster->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             caster->SetControlled(true, UNIT_STATE_STUNNED);
             // Handle phase effect
             uint32 insanityCounter = 0;
             std::list<WorldObject*>::const_iterator itr = targets.begin();
             while (itr != targets.end() && insanityCounter < MAX_INSANITY_TARGETS)
             {
                 WorldObject* targetObj = *itr;
                 if (!targetObj)
                 {
                     continue;
                 }
                 Player* plrTarget = targetObj->ToPlayer();
                 // This should never happen, spell has attribute SPELL_ATTR3_ONLY_TARGET_PLAYERS
                 if (!plrTarget)
                 {
                     continue;
                 }
                 // phase mask
                 plrTarget->CastSpell(plrTarget, InsanitySpells.at(insanityCounter), true);
                 // Summon clone
                 for (std::list<WorldObject*>::const_iterator itr2 = targets.begin(); itr2 != targets.end(); ++itr2)
                 {
                     // Should not make clone of current player target
                     Player const* plrClone = *itr2 ? (*itr2)->ToPlayer() : nullptr;
                     if (!plrClone || plrClone == plrTarget)
                     {
                         continue;
                     }
                     if (Unit* summon = caster->SummonCreature(NPC_TWISTED_VISAGE, plrClone->GetPosition(), TEMPSUMMON_CORPSE_DESPAWN, 0))
                     {
                         summon->AddThreat(plrTarget, 0.0f);
                         summon->SetInCombatWith(plrTarget);
                         plrTarget->SetInCombatWith(summon);
                         plrTarget->CastSpell(summon, SPELL_CLONE_PLAYER, true);
                         summon->SetPhaseMask(1 | (1 << (4 + insanityCounter)), true);
                         summon->SetUInt32Value(UNIT_FIELD_MINDAMAGE, plrClone->GetUInt32Value(UNIT_FIELD_MINDAMAGE));
                         summon->SetUInt32Value(UNIT_FIELD_MAXDAMAGE, plrClone->GetUInt32Value(UNIT_FIELD_MAXDAMAGE));
                     }
                 }
                 ++insanityCounter;
                 ++itr;
             }
         }
References Unit::AddThreat(), Creature::AI(), Unit::CastSpell(), SpellScript::GetCaster(), WorldObject::GetDistance(), Position::GetPosition(), Object::GetTypeId(), Object::GetUInt32Value(), INSANITY_VISUAL, InsanitySpells, Unit::IsInCombatWith(), MAX_INSANITY_TARGETS, MAX_VISIBILITY_DISTANCE, NPC_TWISTED_VISAGE, Unit::RemoveAllAuras(), SAY_INSANITY, Unit::SetControlled(), Object::SetFlag(), Unit::SetInCombatWith(), SPELL_CLONE_PLAYER, SPELL_WHISPER_INSANITY, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_DESPAWN, Object::ToCreature(), Object::ToPlayer(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FIELD_MAXDAMAGE, UNIT_FIELD_MINDAMAGE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STATE_STUNNED.
Referenced by Register().
Load()
bool spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 366 of file boss_herald_volazj.cpp.
 { return GetCaster()->GetTypeId() == TYPEID_UNIT; }
References SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_UNIT.
PrepareSpellScript()
spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::PrepareSpellScript (spell_herald_volzaj_insanity_SpellScript) private
Register()
void spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 453 of file boss_herald_volazj.cpp.
         {
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect, EFFECT_0, TARGET_UNIT_SRC_AREA_ENEMY);
             AfterCast += SpellCastFn(spell_herald_volzaj_insanity_SpellScript::HandleAfterCast);
         }
References SpellScript::AfterCast, EFFECT_0, HandleAfterCast(), HandleDummyEffect(), SpellScript::OnObjectAreaTargetSelect, SpellCastFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ENEMY.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_herald_volazj.cpp