Azerotcore-wotlk: GridObject< T > Class Template Reference
GridObject< T > Class Template Reference
#include <Object.h>
Public Member Functions
bool IsInGrid () const
void AddToGrid (GridRefMgr< T > &m)
void RemoveFromGrid ()
Private Attributes
GridReference< T > _gridRef
Detailed Description
template<class T>
class GridObject< T >
Definition at line 610 of file Object.h.
Member Function Documentation
AddToGrid()
template<class T > void GridObject< T >::AddToGrid (GridRefMgr< T > & m) inline
Definition at line 614 of file Object.h.
 { ASSERT(!IsInGrid()); _gridRef.link(&m, (T*)this); }
References GridObject< T >::_gridRef, ASSERT, GridObject< T >::IsInGrid(), and Reference< TO, FROM >::link().
Referenced by AddObjectHelper().
IsInGrid()
template<class T > bool GridObject< T >::IsInGrid () const inline
Definition at line 613 of file Object.h.
 { return _gridRef.isValid(); }
References GridObject< T >::_gridRef, and Reference< TO, FROM >::isValid().
Referenced by GridObject< T >::AddToGrid(), Map::RemoveCorpse(), GridObject< T >::RemoveFromGrid(), and Map::RemovePlayerFromMap().
RemoveFromGrid()
template<class T > void GridObject< T >::RemoveFromGrid () inline
Definition at line 615 of file Object.h.
 { ASSERT(IsInGrid()); _gridRef.unlink(); }
References GridObject< T >::_gridRef, ASSERT, GridObject< T >::IsInGrid(), and Reference< TO, FROM >::unlink().
Referenced by Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Map::PlayerRelocation(), Map::RemovePlayerFromMap(), and Map::SwitchGridContainers().
Member Data Documentation
_gridRef
template<class T > GridReference<T> GridObject< T >::_gridRef private
Definition at line 617 of file Object.h.
Referenced by GridObject< T >::AddToGrid(), GridObject< T >::IsInGrid(), and GridObject< T >::RemoveFromGrid().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/Object.h