Azerotcore-wotlk: mmaps_commandscript Class Reference
mmaps_commandscript Class Reference
Public Member Functions
mmaps_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleMmapPathCommand (ChatHandler *handler, Optional< std::string > para)
static bool HandleMmapLocCommand (ChatHandler *handler)
static bool HandleMmapLoadedTilesCommand (ChatHandler *handler)
static bool HandleMmapStatsCommand (ChatHandler *handler)
static bool HandleMmapTestArea (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 41 of file cs_mmaps.cpp.
Constructor & Destructor Documentation
mmaps_commandscript()
mmaps_commandscript::mmaps_commandscript () inline
Definition at line 44 of file cs_mmaps.cpp.
 : CommandScript("mmaps_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable mmaps_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 46 of file cs_mmaps.cpp.
     {
         static ChatCommandTable mmapCommandTable =
         {
             { "loadedtiles", HandleMmapLoadedTilesCommand, SEC_ADMINISTRATOR, Console::No },
             { "loc",         HandleMmapLocCommand,         SEC_ADMINISTRATOR, Console::No },
             { "path",        HandleMmapPathCommand,        SEC_ADMINISTRATOR, Console::No },
             { "stats",       HandleMmapStatsCommand,       SEC_ADMINISTRATOR, Console::No },
             { "testarea",    HandleMmapTestArea,           SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "mmap", mmapCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, and SEC_ADMINISTRATOR.
HandleMmapLoadedTilesCommand()
static bool mmaps_commandscript::HandleMmapLoadedTilesCommand (ChatHandler * handler) inline static
Definition at line 188 of file cs_mmaps.cpp.
     {
         uint32 mapid = handler->GetSession()->GetPlayer()->GetMapId();
         dtNavMesh const* navmesh = MMAP::MMapFactory::createOrGetMMapMgr()->GetNavMesh(mapid);
         dtNavMeshQuery const* navmeshquery = MMAP::MMapFactory::createOrGetMMapMgr()->GetNavMeshQuery(mapid, handler->GetSession()->GetPlayer()->GetInstanceId());
         if (!navmesh || !navmeshquery)
         {
             handler->PSendSysMessage("NavMesh not loaded for current map.");
             return true;
         }
         handler->PSendSysMessage("mmap loadedtiles:");
         for (int32 i = 0; i < navmesh->getMaxTiles(); ++i)
         {
             dtMeshTile const* tile = navmesh->getTile(i);
             if (!tile || !tile->header)
                 continue;
             handler->PSendSysMessage("[%02i, %02i]", tile->header->x, tile->header->y);
         }
         return true;
     }
References MMAP::MMapFactory::createOrGetMMapMgr(), WorldObject::GetInstanceId(), WorldLocation::GetMapId(), MMAP::MMapMgr::GetNavMesh(), MMAP::MMapMgr::GetNavMeshQuery(), WorldSession::GetPlayer(), ChatHandler::GetSession(), and ChatHandler::PSendSysMessage().
HandleMmapLocCommand()
static bool mmaps_commandscript::HandleMmapLocCommand (ChatHandler * handler) inline static
Definition at line 125 of file cs_mmaps.cpp.
     {
         handler->PSendSysMessage("mmap tileloc:");
         // grid tile location
         Player* player = handler->GetSession()->GetPlayer();
         int32 gx = 32 - player->GetPositionX() / SIZE_OF_GRIDS;
         int32 gy = 32 - player->GetPositionY() / SIZE_OF_GRIDS;
         handler->PSendSysMessage("%03u%02i%02i.mmtile", player->GetMapId(), gx, gy);
         handler->PSendSysMessage("gridloc [%i, %i]", gy, gx);
         // calculate navmesh tile location
         dtNavMesh const* navmesh = MMAP::MMapFactory::createOrGetMMapMgr()->GetNavMesh(handler->GetSession()->GetPlayer()->GetMapId());
         dtNavMeshQuery const* navmeshquery = MMAP::MMapFactory::createOrGetMMapMgr()->GetNavMeshQuery(handler->GetSession()->GetPlayer()->GetMapId(), player->GetInstanceId());
         if (!navmesh || !navmeshquery)
         {
             handler->PSendSysMessage("NavMesh not loaded for current map.");
             return true;
         }
         float const* min = navmesh->getParams()->orig;
         float x, y, z;
         player->GetPosition(x, y, z);
         float location[VERTEX_SIZE] = {y, z, x};
         float extents[VERTEX_SIZE] = {3.0f, 5.0f, 3.0f};
         int32 tilex = int32((y - min[0]) / SIZE_OF_GRIDS);
         int32 tiley = int32((x - min[2]) / SIZE_OF_GRIDS);
         handler->PSendSysMessage("Calc   [%02i, %02i]", tilex, tiley);
         // navmesh poly -> navmesh tile location
         dtQueryFilterExt filter = dtQueryFilterExt();
         dtPolyRef polyRef = INVALID_POLYREF;
         if (dtStatusFailed(navmeshquery->findNearestPoly(location, extents, &filter, &polyRef, nullptr)))
         {
             handler->PSendSysMessage("Dt     [??,??] (invalid poly, probably no tile loaded)");
             return true;
         }
         if (polyRef == INVALID_POLYREF)
             handler->PSendSysMessage("Dt     [??, ??] (invalid poly, probably no tile loaded)");
         else
         {
             dtMeshTile const* tile;
             dtPoly const* poly;
             if (dtStatusSucceed(navmesh->getTileAndPolyByRef(polyRef, &tile, &poly)))
             {
                 if (tile)
                 {
                     handler->PSendSysMessage("Dt     [%02i,%02i]", tile->header->x, tile->header->y);
                     return false;
                 }
             }
             handler->PSendSysMessage("Dt     [??,??] (no tile loaded)");
         }
         return true;
     }
References MMAP::MMapFactory::createOrGetMMapMgr(), WorldObject::GetInstanceId(), WorldLocation::GetMapId(), MMAP::MMapMgr::GetNavMesh(), MMAP::MMapMgr::GetNavMeshQuery(), WorldSession::GetPlayer(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), ChatHandler::GetSession(), INVALID_POLYREF, ChatHandler::PSendSysMessage(), SIZE_OF_GRIDS, and VERTEX_SIZE.
HandleMmapPathCommand()
static bool mmaps_commandscript::HandleMmapPathCommand (ChatHandler * handler, Optional< std::string > para) inline static
Definition at line 64 of file cs_mmaps.cpp.
     {
         if (!MMAP::MMapFactory::createOrGetMMapMgr()->GetNavMesh(handler->GetSession()->GetPlayer()->GetMapId()))
         {
             handler->PSendSysMessage("NavMesh not loaded for current map.");
             return true;
         }
         handler->PSendSysMessage("mmap path:");
         // units
         Player* player = handler->GetSession()->GetPlayer();
         Unit* target = handler->getSelectedUnit();
         if (!player || !target)
         {
             handler->PSendSysMessage("Invalid target/source selection.");
             return true;
         }
         bool useStraightPath = false;
         if (StringStartsWith("true", *para))
             useStraightPath = true;
         bool useRaycast = false;
         if (StringStartsWith("line", *para) || StringStartsWith("ray", *para) || StringStartsWith("raycast", *para))
         {
             useRaycast = true;
         }
         // unit locations
         float x, y, z;
         player->GetPosition(x, y, z);
         // path
         PathGenerator path(target);
         path.SetUseStraightPath(useStraightPath);
         path.SetUseRaycast(useRaycast);
         bool result = path.CalculatePath(x, y, z, false);
         Movement::PointsArray const& pointPath = path.GetPath();
         handler->PSendSysMessage("%s's path to %s:", target->GetName().c_str(), player->GetName().c_str());
         handler->PSendSysMessage("Building: %s", useStraightPath ? "StraightPath" : useRaycast ? "Raycast" : "SmoothPath");
         handler->PSendSysMessage("Result: %s - Length: " SZFMTD " - Type: %u", (result ? "true" : "false"), pointPath.size(), path.GetPathType());
         G3D::Vector3 const& start = path.GetStartPosition();
         G3D::Vector3 const& end = path.GetEndPosition();
         G3D::Vector3 const& actualEnd = path.GetActualEndPosition();
         handler->PSendSysMessage("StartPosition     (%.3f, %.3f, %.3f)", start.x, start.y, start.z);
         handler->PSendSysMessage("EndPosition       (%.3f, %.3f, %.3f)", end.x, end.y, end.z);
         handler->PSendSysMessage("ActualEndPosition (%.3f, %.3f, %.3f)", actualEnd.x, actualEnd.y, actualEnd.z);
         if (!player->IsGameMaster())
             handler->PSendSysMessage("Enable GM mode to see the path points.");
         for (auto i : pointPath)
             player->SummonCreature(VISUAL_WAYPOINT, i.x, i.y, i.z, 0, TEMPSUMMON_TIMED_DESPAWN, 9000);
         return true;
     }
References PathGenerator::CalculatePath(), MMAP::MMapFactory::createOrGetMMapMgr(), PathGenerator::GetActualEndPosition(), PathGenerator::GetEndPosition(), WorldLocation::GetMapId(), WorldObject::GetName(), PathGenerator::GetPath(), PathGenerator::GetPathType(), WorldSession::GetPlayer(), Position::GetPosition(), ChatHandler::getSelectedUnit(), ChatHandler::GetSession(), PathGenerator::GetStartPosition(), Player::IsGameMaster(), ChatHandler::PSendSysMessage(), PathGenerator::SetUseRaycast(), PathGenerator::SetUseStraightPath(), StringStartsWith(), WorldObject::SummonCreature(), SZFMTD, TEMPSUMMON_TIMED_DESPAWN, and VISUAL_WAYPOINT.
HandleMmapStatsCommand()
static bool mmaps_commandscript::HandleMmapStatsCommand (ChatHandler * handler) inline static
Definition at line 213 of file cs_mmaps.cpp.
     {
         handler->PSendSysMessage("mmap stats:");
         //handler->PSendSysMessage("  global mmap pathfinding is %sabled", DisableMgr::IsPathfindingEnabled(mapId) ? "en" : "dis");
         MMAP::MMapMgr* manager = MMAP::MMapFactory::createOrGetMMapMgr();
         handler->PSendSysMessage(" %u maps loaded with %u tiles overall", manager->getLoadedMapsCount(), manager->getLoadedTilesCount());
         dtNavMesh const* navmesh = manager->GetNavMesh(handler->GetSession()->GetPlayer()->GetMapId());
         if (!navmesh)
         {
             handler->PSendSysMessage("NavMesh not loaded for current map.");
             return true;
         }
         uint32 tileCount = 0;
         uint32 nodeCount = 0;
         uint32 polyCount = 0;
         uint32 vertCount = 0;
         uint32 triCount = 0;
         uint32 triVertCount = 0;
         uint32 dataSize = 0;
         for (int32 i = 0; i < navmesh->getMaxTiles(); ++i)
         {
             dtMeshTile const* tile = navmesh->getTile(i);
             if (!tile || !tile->header)
                 continue;
             tileCount++;
             nodeCount += tile->header->bvNodeCount;
             polyCount += tile->header->polyCount;
             vertCount += tile->header->vertCount;
             triCount += tile->header->detailTriCount;
             triVertCount += tile->header->detailVertCount;
             dataSize += tile->dataSize;
         }
         handler->PSendSysMessage("Navmesh stats:");
         handler->PSendSysMessage(" %u tiles loaded", tileCount);
         handler->PSendSysMessage(" %u BVTree nodes", nodeCount);
         handler->PSendSysMessage(" %u polygons (%u vertices)", polyCount, vertCount);
         handler->PSendSysMessage(" %u triangles (%u vertices)", triCount, triVertCount);
         handler->PSendSysMessage(" %.2f MB of data (not including pointers)", ((float)dataSize / sizeof(unsigned char)) / 1048576);
         return true;
     }
References MMAP::MMapFactory::createOrGetMMapMgr(), MMAP::MMapMgr::getLoadedMapsCount(), MMAP::MMapMgr::getLoadedTilesCount(), WorldLocation::GetMapId(), MMAP::MMapMgr::GetNavMesh(), WorldSession::GetPlayer(), ChatHandler::GetSession(), and ChatHandler::PSendSysMessage().
HandleMmapTestArea()
static bool mmaps_commandscript::HandleMmapTestArea (ChatHandler * handler) inline static
Definition at line 260 of file cs_mmaps.cpp.
     {
         float radius = 40.0f;
         WorldObject* object = handler->GetSession()->GetPlayer();
         // Get Creatures
         std::list<Creature*> creatureList;
         Acore::AnyUnitInObjectRangeCheck go_check(object, radius);
         Acore::CreatureListSearcher<Acore::AnyUnitInObjectRangeCheck> go_search(object, creatureList, go_check);
         Cell::VisitGridObjects(object, go_search, radius);
         if (!creatureList.empty())
         {
             handler->PSendSysMessage("Found " SZFMTD " Creatures.", creatureList.size());
             uint32 paths = 0;
             uint32 uStartTime = getMSTime();
             float gx, gy, gz;
             object->GetPosition(gx, gy, gz);
             for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
             {
                 PathGenerator path(*itr);
                 path.CalculatePath(gx, gy, gz);
                 ++paths;
             }
             uint32 uPathLoadTime = getMSTimeDiff(uStartTime, getMSTime());
             handler->PSendSysMessage("Generated %i paths in %i ms", paths, uPathLoadTime);
         }
         else
             handler->PSendSysMessage("No creatures in %f yard range.", radius);
         return true;
     }
References PathGenerator::CalculatePath(), getMSTime(), getMSTimeDiff(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::PSendSysMessage(), SZFMTD, and Cell::VisitGridObjects().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_mmaps.cpp