Azerotcore-wotlk: ValithriaDespawner Class Reference
ValithriaDespawner Class Reference
Public Member Functions
ValithriaDespawner (Creature *creature)
bool Execute (uint64, uint32) override
void operator() (Creature *creature) const
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _creature
Detailed Description
Definition at line 212 of file boss_valithria_dreamwalker.cpp.
Constructor & Destructor Documentation
ValithriaDespawner()
ValithriaDespawner::ValithriaDespawner (Creature * creature) inline explicit
Definition at line 215 of file boss_valithria_dreamwalker.cpp.
                                                     : _creature(creature)
     {
     }
Member Function Documentation
Execute()
bool ValithriaDespawner::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 219 of file boss_valithria_dreamwalker.cpp.
     {
         Acore::CreatureWorker<ValithriaDespawner> worker(_creature, *this);
         Cell::VisitGridObjects(_creature, worker, 333.0f);
         _creature->AI()->Reset();
         _creature->setActive(false);
         return true;
     }
References _creature, Creature::AI(), UnitAI::Reset(), WorldObject::setActive(), and Cell::VisitGridObjects().
operator()()
void ValithriaDespawner::operator() (Creature * creature) const inline
Definition at line 228 of file boss_valithria_dreamwalker.cpp.
     {
         switch (creature->GetEntry())
         {
             case NPC_VALITHRIA_DREAMWALKER:
                 if (InstanceScript* instance = creature->GetInstanceScript())
                     instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, creature);
                 break;
             case NPC_THE_LICH_KING_VALITHRIA:
                 if (creature->IsAlive())
                     creature->AI()->Reset();
                 return;
             case NPC_BLAZING_SKELETON:
             case NPC_SUPPRESSER:
             case NPC_BLISTERING_ZOMBIE:
             case NPC_GLUTTONOUS_ABOMINATION:
             case NPC_MANA_VOID:
             case NPC_COLUMN_OF_FROST:
             case NPC_ROT_WORM:
                 creature->DespawnOrUnsummon();
                 return;
             case NPC_RISEN_ARCHMAGE:
                 if (!creature->GetSpawnId())
                 {
                     creature->DespawnOrUnsummon();
                     return;
                 }
                 break;
             default:
                 return;
         }
         uint32 corpseDelay = creature->GetCorpseDelay();
         uint32 respawnDelay = creature->GetRespawnDelay();
         creature->SetCorpseDelay(1);
         creature->SetRespawnDelay(10);
         if (CreatureData const* data = creature->GetCreatureData())
             creature->SetPosition(data->posX, data->posY, data->posZ, data->orientation);
         if (!creature->IsAlive())
         {
             creature->RemoveCorpse(false);
             creature->SetRespawnTime(11);
         }
         else
             creature->DespawnOrUnsummon();
         creature->SetCorpseDelay(corpseDelay);
         creature->SetRespawnDelay(respawnDelay);
     }
References Creature::AI(), Creature::DespawnOrUnsummon(), ENCOUNTER_FRAME_DISENGAGE, Creature::GetCorpseDelay(), Creature::GetCreatureData(), Object::GetEntry(), WorldObject::GetInstanceScript(), Creature::GetRespawnDelay(), Creature::GetSpawnId(), Unit::IsAlive(), NPC_BLAZING_SKELETON, NPC_BLISTERING_ZOMBIE, NPC_COLUMN_OF_FROST, NPC_GLUTTONOUS_ABOMINATION, NPC_MANA_VOID, NPC_RISEN_ARCHMAGE, NPC_ROT_WORM, NPC_SUPPRESSER, NPC_THE_LICH_KING_VALITHRIA, NPC_VALITHRIA_DREAMWALKER, Creature::RemoveCorpse(), UnitAI::Reset(), Creature::SetCorpseDelay(), Creature::SetPosition(), Creature::SetRespawnDelay(), and Creature::SetRespawnTime().
Member Data Documentation
_creature
Creature* ValithriaDespawner::_creature private
Definition at line 280 of file boss_valithria_dreamwalker.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp