Azerotcore-wotlk: boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI Struct Reference
boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI Struct Reference
Public Member Functions
boss_yoggsaron_neltharionAI (Creature *c)
void Reset () override
void NextStep (const uint32 time)
void Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId)
void PlaySound (uint32 soundId)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _running
int32 _checkTimer
uint8 _step
ObjectGuid _yoggGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2125 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaron_neltharionAI()
boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::boss_yoggsaron_neltharionAI (Creature * c) inline
Definition at line 2127 of file boss_yoggsaron.cpp.
 : ScriptedAI(c) { }
Member Function Documentation
NextStep()
void boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::NextStep (const uint32 time) inline
Definition at line 2143 of file boss_yoggsaron.cpp.
         {
             _step++;
             _checkTimer = time;
         }
References _checkTimer, and _step.
Referenced by UpdateAI().
PlaySound()
void boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::PlaySound (uint32 soundId) inline
Definition at line 2172 of file boss_yoggsaron.cpp.
         {
             WorldPacket data(SMSG_PLAY_SOUND, 4);
             data << uint32(soundId);
             me->SendMessageToSetInRange(&data, 90, false);
         }
References ScriptedAI::me, WorldObject::SendMessageToSetInRange(), and SMSG_PLAY_SOUND.
Referenced by Say().
Reset()
void boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2134 of file boss_yoggsaron.cpp.
         {
             _running = true;
             _checkTimer = 0;
             _step = 0;
             if (me->GetInstanceScript())
                 _yoggGUID = me->GetInstanceScript()->GetGuidData(TYPE_YOGGSARON);
         }
References _checkTimer, _running, _step, _yoggGUID, InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), ScriptedAI::me, and TYPE_YOGGSARON.
Say()
void boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId) inline
Definition at line 2149 of file boss_yoggsaron.cpp.
         {
             Creature* creature = !guid ? ObjectAccessor::GetCreature(*me, guid) : me;
             if (!creature)
                 return;
             WorldPacket data;
             if (creature->GetGUID() != _yoggGUID)
             {
                 ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                 creature->SendMessageToSetInRange(&data, 90, true);
             }
             else if (Creature* cr = me->SummonTrigger(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() - 5, 0, 5000))
             {
                 ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                 cr->SendMessageToSetInRange(&data, 90, true);
             }
             else
                 return;
             PlaySound(soundId);
         }
References _yoggGUID, ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_YELL, ObjectAccessor::GetCreature(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, ScriptedAI::me, PlaySound(), WorldObject::SendMessageToSetInRange(), and WorldObject::SummonTrigger().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2179 of file boss_yoggsaron.cpp.
         {
             if (!_running)
                 return;
             if (_checkTimer != 0)
             {
                 _checkTimer -= diff;
                 if (_checkTimer < 0 )
                     _checkTimer = 0;
             }
             else
                 switch (_step)
                 {
                     case 0:
                         NextStep(5000);
                         break;
                     case 1:
                         Say("It is done... All have been given that which must be given. I now seal the Dragon Soul forever...", ObjectGuid::Empty, false, NEL_1);
                         NextStep(10000);
                         break;
                     case 2:
                         if (Creature* cr = me->FindNearestCreature(NPC_YSERA, 50))
                             Say("That terrible glow... should that be?", cr->GetGUID(), false, YSE_1);
                         NextStep(4000);
                         break;
                     case 3:
                         Say("For it to be as it must, yes.", ObjectGuid::Empty, false, NEL_2);
                         NextStep(4000);
                         break;
                     case 4:
                         if (Creature* cr = me->FindNearestCreature(NPC_MALYGOS, 50))
                             Say("It is a weapon like no other. It must be like no other.", cr->GetGUID(), false, MAL_1);
                         NextStep(8000);
                         break;
                     case 5:
                         Say("His brood learned their lesson before too long, you shall soon learn yours!", _yoggGUID, false, YS_V2_1);
                         _running = false;
                         break;
                 }
         }
References _checkTimer, _running, _step, _yoggGUID, diff(), ObjectGuid::Empty, WorldObject::FindNearestCreature(), MAL_1, ScriptedAI::me, NEL_1, NEL_2, NextStep(), NPC_MALYGOS, NPC_YSERA, Say(), YS_V2_1, and YSE_1.
Member Data Documentation
_checkTimer
int32 boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::_checkTimer
Definition at line 2130 of file boss_yoggsaron.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
_running
bool boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::_running
Definition at line 2129 of file boss_yoggsaron.cpp.
Referenced by Reset(), and UpdateAI().
_step
uint8 boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::_step
Definition at line 2131 of file boss_yoggsaron.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
_yoggGUID
ObjectGuid boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::_yoggGUID
Definition at line 2132 of file boss_yoggsaron.cpp.
Referenced by Reset(), Say(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp