Azerotcore-wotlk: npc_the_biggest_tree::npc_the_biggest_treeAI Struct Reference
npc_the_biggest_tree::npc_the_biggest_treeAI Struct Reference
Public Member Functions
npc_the_biggest_treeAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 timer
uint8 phase
ObjectGuid playerGUID
ObjectGuid orphanGUID
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 345 of file childrens_week.cpp.
Constructor & Destructor Documentation
npc_the_biggest_treeAI()
npc_the_biggest_tree::npc_the_biggest_treeAI::npc_the_biggest_treeAI (Creature * creature) inline
Definition at line 347 of file childrens_week.cpp.
                                                    : ScriptedAI(creature)
         {
             me->SetDisplayId(DISPLAY_INVISIBLE);
         }
References DISPLAY_INVISIBLE, ScriptedAI::me, and Creature::SetDisplayId().
Member Function Documentation
MoveInLineOfSight()
void npc_the_biggest_tree::npc_the_biggest_treeAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 360 of file childrens_week.cpp.
         {
             if (!phase && who && who->GetDistance2d(me) < 10.0f)
                 if (Player* player = who->ToPlayer())
                     if (player->GetQuestStatus(QUEST_THE_BIGGEST_TREE_EVER) == QUEST_STATUS_INCOMPLETE)
                     {
                         playerGUID = player->GetGUID();
                         orphanGUID = getOrphanGUID(player, ORPHAN_ORACLE);
                         if (orphanGUID)
                             phase = 1;
                     }
         }
References WorldObject::GetDistance2d(), getOrphanGUID(), ScriptedAI::me, ORPHAN_ORACLE, orphanGUID, playerGUID, QUEST_STATUS_INCOMPLETE, QUEST_THE_BIGGEST_TREE_EVER, and Object::ToPlayer().
Reset()
void npc_the_biggest_tree::npc_the_biggest_treeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 352 of file childrens_week.cpp.
         {
             timer = 1000;
             phase = 0;
             playerGUID.Clear();
             orphanGUID.Clear();
         }
References ObjectGuid::Clear(), orphanGUID, playerGUID, and timer.
Referenced by UpdateAI().
UpdateAI()
void npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 373 of file childrens_week.cpp.
         {
             if (!phase)
                 return;
             if (timer <= diff)
             {
                 Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
                 Creature* orphan = ObjectAccessor::GetCreature(*me, orphanGUID);
                 if (!orphan || !player)
                 {
                     Reset();
                     return;
                 }
                 switch (phase)
                 {
                     case 1:
                         orphan->GetMotionMaster()->MovePoint(0, me->GetPositionX() + cos(me->GetOrientation()) * 5, me->GetPositionY() + sin(me->GetOrientation()) * 5, me->GetPositionZ());
                         timer = 2000;
                         break;
                     case 2:
                         orphan->SetFacingToObject(me);
                         orphan->AI()->Talk(TEXT_ORACLE_ORPHAN_4);
                         timer = 5000;
                         break;
                     case 3:
                         player->GroupEventHappens(QUEST_THE_BIGGEST_TREE_EVER, me);
                         orphan->GetMotionMaster()->MoveFollow(player, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);
                         Reset();
                         return;
                 }
                 ++phase;
             }
             else
                 timer -= diff;
         }
References Creature::AI(), diff(), ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Position::GetOrientation(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GroupEventHappens(), ScriptedAI::me, MotionMaster::MoveFollow(), MotionMaster::MovePoint(), orphanGUID, PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, phase, playerGUID, QUEST_THE_BIGGEST_TREE_EVER, Reset(), Unit::SetFacingToObject(), CreatureAI::Talk(), TEXT_ORACLE_ORPHAN_4, and timer.
Member Data Documentation
orphanGUID
ObjectGuid npc_the_biggest_tree::npc_the_biggest_treeAI::orphanGUID private
Definition at line 416 of file childrens_week.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateAI().
phase
uint8 npc_the_biggest_tree::npc_the_biggest_treeAI::phase private
Definition at line 414 of file childrens_week.cpp.
Referenced by UpdateAI().
playerGUID
ObjectGuid npc_the_biggest_tree::npc_the_biggest_treeAI::playerGUID private
Definition at line 415 of file childrens_week.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateAI().
timer
uint32 npc_the_biggest_tree::npc_the_biggest_treeAI::timer private
Definition at line 413 of file childrens_week.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/childrens_week.cpp