Azerotcore-wotlk: Acore::NearestGameObjectFishingHole Class Reference
Acore::NearestGameObjectFishingHole Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestGameObjectFishingHole (WorldObject const &obj, float range)
bool operator() (GameObject *go)
Private Member Functions
NearestGameObjectFishingHole (NearestGameObjectFishingHole const &)
Private Attributes
WorldObject const & i_obj
float i_range
Detailed Description
Definition at line 647 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestGameObjectFishingHole() [1/2]
Acore::NearestGameObjectFishingHole::NearestGameObjectFishingHole (WorldObject const & obj, float range) inline
Definition at line 650 of file GridNotifiers.h.
 : i_obj(obj), i_range(range) {}
NearestGameObjectFishingHole() [2/2]
Acore::NearestGameObjectFishingHole::NearestGameObjectFishingHole (NearestGameObjectFishingHole const &) private
Member Function Documentation
operator()()
bool Acore::NearestGameObjectFishingHole::operator() (GameObject * go) inline
Definition at line 651 of file GridNotifiers.h.
         {
             if (go->GetGOInfo()->type == GAMEOBJECT_TYPE_FISHINGHOLE && go->isSpawned() && i_obj.IsWithinDistInMap(go, i_range) && i_obj.IsWithinDistInMap(go, (float)go->GetGOInfo()->fishinghole.radius))
             {
                 i_range = i_obj.GetDistance(go);
                 return true;
             }
             return false;
         }
References GameObjectTemplate::fishinghole, GAMEOBJECT_TYPE_FISHINGHOLE, WorldObject::GetDistance(), GameObject::GetGOInfo(), i_obj, i_range, GameObject::isSpawned(), WorldObject::IsWithinDistInMap(), and GameObjectTemplate::type.
Member Data Documentation
i_obj
WorldObject const& Acore::NearestGameObjectFishingHole::i_obj private
Definition at line 661 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestGameObjectFishingHole::i_range private
Definition at line 662 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h