Azerotcore-wotlk: AuctionHouseMgr Class Reference
AuctionHouseMgr Class Reference
#include <AuctionHouseMgr.h>
Public Types
typedef std::unordered_map< ObjectGuid, Item * > ItemMap
Public Member Functions
AuctionHouseObject * GetAuctionsMap (uint32 factionTemplateId)
AuctionHouseObject * GetAuctionsMapByHouseId (uint8 auctionHouseId)
AuctionHouseObject * GetBidsMap (uint32 factionTemplateId)
Item * GetAItem (ObjectGuid itemGuid)
void SendAuctionWonMail (AuctionEntry *auction, CharacterDatabaseTransaction trans, bool sendNotification=true, bool updateAchievementCriteria=true, bool sendMail=true)
void SendAuctionSalePendingMail (AuctionEntry *auction, CharacterDatabaseTransaction trans, bool sendMail=true)
void SendAuctionSuccessfulMail (AuctionEntry *auction, CharacterDatabaseTransaction trans, bool sendNotification=true, bool updateAchievementCriteria=true, bool sendMail=true)
void SendAuctionExpiredMail (AuctionEntry *auction, CharacterDatabaseTransaction trans, bool sendNotification=true, bool sendMail=true)
void SendAuctionOutbiddedMail (AuctionEntry *auction, uint32 newPrice, Player *newBidder, CharacterDatabaseTransaction trans, bool sendNotification=true, bool sendMail=true)
void SendAuctionCancelledToBidderMail (AuctionEntry *auction, CharacterDatabaseTransaction trans, bool sendMail=true)
void LoadAuctionItems ()
void LoadAuctions ()
void AddAItem (Item *it)
bool RemoveAItem (ObjectGuid itemGuid, bool deleteFromDB=false, CharacterDatabaseTransaction *trans=nullptr)
void Update ()
Static Public Member Functions
static AuctionHouseMgr * instance ()
static uint32 GetAuctionDeposit (AuctionHouseEntry const *entry, uint32 time, Item *pItem, uint32 count)
static AuctionHouseEntry const * GetAuctionHouseEntry (uint32 factionTemplateId)
static AuctionHouseEntry const * GetAuctionHouseEntryFromHouse (uint8 houseId)
Private Member Functions
AuctionHouseMgr ()
~AuctionHouseMgr ()
Private Attributes
AuctionHouseObject mHordeAuctions
AuctionHouseObject mAllianceAuctions
AuctionHouseObject mNeutralAuctions
ItemMap mAitems
Detailed Description
Definition at line 174 of file AuctionHouseMgr.h.
Member Typedef Documentation
ItemMap
typedef std::unordered_map<ObjectGuid, Item*> AuctionHouseMgr::ItemMap
Definition at line 181 of file AuctionHouseMgr.h.
Constructor & Destructor Documentation
AuctionHouseMgr()
AuctionHouseMgr::AuctionHouseMgr () private
Definition at line 217 of file AuctionHouseMgr.cpp.
 {
 }
~AuctionHouseMgr()
AuctionHouseMgr::~AuctionHouseMgr () private
Definition at line 221 of file AuctionHouseMgr.cpp.
 {
     for (ItemMap::iterator itr = mAitems.begin(); itr != mAitems.end(); ++itr)
         delete itr->second;
 }
References mAitems.
Member Function Documentation
AddAItem()
void AuctionHouseMgr::AddAItem (Item * it)
Definition at line 565 of file AuctionHouseMgr.cpp.
 {
     ASSERT(it);
     ASSERT(mAitems.find(it->GetGUID()) == mAitems.end());
     mAitems[it->GetGUID()] = it;
 }
References ASSERT, Object::GetGUID(), and mAitems.
Referenced by LoadAuctionItems().
GetAItem()
Item* AuctionHouseMgr::GetAItem (ObjectGuid itemGuid) inline
Definition at line 189 of file AuctionHouseMgr.h.
     {
         ItemMap::const_iterator itr = mAitems.find(itemGuid);
         if (itr != mAitems.end())
             return itr->second;
         return nullptr;
     }
References mAitems.
Referenced by SendAuctionExpiredMail(), and SendAuctionWonMail().
GetAuctionDeposit()
uint32 AuctionHouseMgr::GetAuctionDeposit (AuctionHouseEntry const * entry, uint32 time, Item * pItem, uint32 count) static
Definition at line 268 of file AuctionHouseMgr.cpp.
 {
     uint32 MSV = pItem->GetTemplate()->SellPrice;
     if (MSV <= 0)
         return AH_MINIMUM_DEPOSIT * sWorld->getRate(RATE_AUCTION_DEPOSIT);
     float multiplier = CalculatePct(float(entry->depositPercent), 3);
     uint32 timeHr = (((time / 60) / 60) / 12);
     uint32 deposit = uint32(((multiplier * MSV * count / 3) * timeHr * 3) * sWorld->getRate(RATE_AUCTION_DEPOSIT));
     LOG_DEBUG("auctionHouse", "MSV:        %u", MSV);
     LOG_DEBUG("auctionHouse", "Items:      %u", count);
     LOG_DEBUG("auctionHouse", "Multiplier: %f", multiplier);
     LOG_DEBUG("auctionHouse", "Deposit:    %u", deposit);
     if (deposit < AH_MINIMUM_DEPOSIT * sWorld->getRate(RATE_AUCTION_DEPOSIT))
         return AH_MINIMUM_DEPOSIT * sWorld->getRate(RATE_AUCTION_DEPOSIT);
     else
         return deposit;
 }
References AH_MINIMUM_DEPOSIT, CalculatePct(), AuctionHouseEntry::depositPercent, Item::GetTemplate(), LOG_DEBUG, RATE_AUCTION_DEPOSIT, ItemTemplate::SellPrice, and sWorld.
GetAuctionHouseEntry()
AuctionHouseEntry const * AuctionHouseMgr::GetAuctionHouseEntry (uint32 factionTemplateId) static
Definition at line 597 of file AuctionHouseMgr.cpp.
 {
     uint32 houseid = AUCTIONHOUSE_NEUTRAL; // goblin auction house
     if (!sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION))
     {
         //FIXME: found way for proper auctionhouse selection by another way
         // AuctionHouse.dbc have faction field with _player_ factions associated with auction house races.
         // but no easy way convert creature faction to player race faction for specific city
         FactionTemplateEntry const* u_entry = sFactionTemplateStore.LookupEntry(factionTemplateId);
         if (!u_entry)
             houseid = AUCTIONHOUSE_NEUTRAL; // goblin auction house
         else if (u_entry->ourMask & FACTION_MASK_ALLIANCE)
             houseid = AUCTIONHOUSE_ALLIANCE; // human auction house
         else if (u_entry->ourMask & FACTION_MASK_HORDE)
             houseid = AUCTIONHOUSE_HORDE; // orc auction house
         else
             houseid = AUCTIONHOUSE_NEUTRAL; // goblin auction house
     }
     return sAuctionHouseStore.LookupEntry(houseid);
 }
References AUCTIONHOUSE_ALLIANCE, AUCTIONHOUSE_HORDE, AUCTIONHOUSE_NEUTRAL, CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION, FACTION_MASK_ALLIANCE, FACTION_MASK_HORDE, FactionTemplateEntry::ourMask, sAuctionHouseStore, sFactionTemplateStore, and sWorld.
Referenced by WorldSession::HandleAuctionSellItem(), and WorldSession::SendAuctionHello().
GetAuctionHouseEntryFromHouse()
AuctionHouseEntry const * AuctionHouseMgr::GetAuctionHouseEntryFromHouse (uint8 houseId) static
Definition at line 620 of file AuctionHouseMgr.cpp.
 {
     return (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION)) ? sAuctionHouseStore.LookupEntry(AUCTIONHOUSE_NEUTRAL) : sAuctionHouseStore.LookupEntry(houseId);
 }
References AUCTIONHOUSE_NEUTRAL, CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION, sAuctionHouseStore, and sWorld.
Referenced by AuctionEntry::LoadFromDB().
GetAuctionsMap()
AuctionHouseObject * AuctionHouseMgr::GetAuctionsMap (uint32 factionTemplateId)
Definition at line 233 of file AuctionHouseMgr.cpp.
 {
     if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION))
         return &mNeutralAuctions;
     // team have linked auction houses
     FactionTemplateEntry const* u_entry = sFactionTemplateStore.LookupEntry(factionTemplateId);
     if (!u_entry)
         return &mNeutralAuctions;
     else if (u_entry->ourMask & FACTION_MASK_ALLIANCE)
         return &mAllianceAuctions;
     else if (u_entry->ourMask & FACTION_MASK_HORDE)
         return &mHordeAuctions;
     return &mNeutralAuctions;
 }
References CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION, FACTION_MASK_ALLIANCE, FACTION_MASK_HORDE, mAllianceAuctions, mHordeAuctions, mNeutralAuctions, FactionTemplateEntry::ourMask, sFactionTemplateStore, and sWorld.
GetAuctionsMapByHouseId()
AuctionHouseObject * AuctionHouseMgr::GetAuctionsMapByHouseId (uint8 auctionHouseId)
Definition at line 250 of file AuctionHouseMgr.cpp.
 {
     if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION))
         return &mNeutralAuctions;
     switch(auctionHouseId)
     {
         case AUCTIONHOUSE_ALLIANCE:
             return &mAllianceAuctions;
         case AUCTIONHOUSE_HORDE:
             return &mHordeAuctions;
             break;
     }
     return &mNeutralAuctions;
 }
References AUCTIONHOUSE_ALLIANCE, AUCTIONHOUSE_HORDE, CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION, mAllianceAuctions, mHordeAuctions, mNeutralAuctions, and sWorld.
Referenced by LoadAuctions().
GetBidsMap()
AuctionHouseObject* AuctionHouseMgr::GetBidsMap (uint32 factionTemplateId)
instance()
AuctionHouseMgr * AuctionHouseMgr::instance () static
Definition at line 227 of file AuctionHouseMgr.cpp.
 {
     static AuctionHouseMgr instance;
     return &instance;
 }
LoadAuctionItems()
void AuctionHouseMgr::LoadAuctionItems ()
Definition at line 471 of file AuctionHouseMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     // need to clear in case we are reloading
     if (!mAitems.empty())
     {
         for (ItemMap::iterator itr = mAitems.begin(); itr != mAitems.end(); ++itr)
             delete itr->second;
         mAitems.clear();
     }
     // data needs to be at first place for Item::LoadFromDB
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_AUCTION_ITEMS);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 auction items. DB table `auctionhouse` or `item_instance` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         ObjectGuid::LowType item_guid = fields[11].GetUInt32();
         uint32 item_template = fields[12].GetUInt32();
         ItemTemplate const* proto = sObjectMgr->GetItemTemplate(item_template);
         if (!proto)
         {
             LOG_ERROR("auctionHouse", "AuctionHouseMgr::LoadAuctionItems: Unknown item (GUID: %u id: #%u) in auction, skipped.", item_guid, item_template);
             continue;
         }
         Item* item = NewItemOrBag(proto);
         if (!item->LoadFromDB(item_guid, ObjectGuid::Empty, fields, item_template))
         {
             delete item;
             continue;
         }
         AddAItem(item);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u auction items in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References AddAItem(), CHAR_SEL_AUCTION_ITEMS, CharacterDatabase, ObjectGuid::Empty, getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), Item::LoadFromDB(), LOG_ERROR, LOG_INFO, mAitems, NewItemOrBag(), and sObjectMgr.
LoadAuctions()
void AuctionHouseMgr::LoadAuctions ()
Definition at line 526 of file AuctionHouseMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_AUCTIONS);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 auctions. DB table `auctionhouse` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     do
     {
         Field* fields = result->Fetch();
         AuctionEntry* aItem = new AuctionEntry();
         if (!aItem->LoadFromDB(fields))
         {
             aItem->DeleteFromDB(trans);
             delete aItem;
             continue;
         }
         GetAuctionsMapByHouseId(aItem->houseId)->AddAuction(aItem);
         count++;
     } while (result->NextRow());
     CharacterDatabase.CommitTransaction(trans);
     LOG_INFO("server.loading", ">> Loaded %u auctions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References AuctionHouseObject::AddAuction(), CHAR_SEL_AUCTIONS, CharacterDatabase, AuctionEntry::DeleteFromDB(), GetAuctionsMapByHouseId(), getMSTime(), GetMSTimeDiffToNow(), AuctionEntry::houseId, AuctionEntry::LoadFromDB(), and LOG_INFO.
RemoveAItem()
bool AuctionHouseMgr::RemoveAItem (ObjectGuid itemGuid, bool deleteFromDB = false, CharacterDatabaseTransaction * trans = nullptr)
Definition at line 572 of file AuctionHouseMgr.cpp.
 {
     ItemMap::iterator i = mAitems.find(itemGuid);
     if (i == mAitems.end())
         return false;
     if (deleteFromDB)
     {
         ASSERT(trans);
         i->second->FSetState(ITEM_REMOVED);
         i->second->SaveToDB(*trans);
     }
     mAitems.erase(i);
     return true;
 }
References ASSERT, ITEM_REMOVED, and mAitems.
SendAuctionCancelledToBidderMail()
void AuctionHouseMgr::SendAuctionCancelledToBidderMail (AuctionEntry * auction, CharacterDatabaseTransaction trans, bool sendMail = true)
Definition at line 452 of file AuctionHouseMgr.cpp.
 {
     Player* bidder = ObjectAccessor::FindConnectedPlayer(auction->bidder);
     uint32 bidder_accId = 0;
     if (!bidder)
         bidder_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->bidder.GetCounter());
     // bidder exist
     if (bidder || bidder_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail(this, auction, bidder, bidder_accId, sendMail);
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_CANCELLED_TO_BIDDER), AuctionEntry::BuildAuctionMailBody(auction->owner, auction->bid, auction->buyout, auction->deposit))
             .AddMoney(auction->bid)
             .SendMailTo(trans, MailReceiver(bidder, auction->bidder.GetCounter()), auction, MAIL_CHECK_MASK_COPIED);
     }
 }
References MailDraft::AddMoney(), AUCTION_CANCELLED_TO_BIDDER, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, AuctionEntry::deposit, ObjectAccessor::FindConnectedPlayer(), ObjectGuid::GetCounter(), MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, MailDraft::SendMailTo(), sObjectMgr, and sScriptMgr.
SendAuctionExpiredMail()
void AuctionHouseMgr::SendAuctionExpiredMail (AuctionEntry * auction, CharacterDatabaseTransaction trans, bool sendNotification = true, bool sendMail = true)
Definition at line 400 of file AuctionHouseMgr.cpp.
 {
     //return an item in auction to its owner by mail
     Item* pItem = GetAItem(auction->item_guid);
     if (!pItem)
         return;
     Player* owner = ObjectAccessor::FindConnectedPlayer(auction->owner);
     uint32 owner_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->owner.GetCounter());
     // owner exist
     if (owner || owner_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionExpiredMail(this, auction, owner, owner_accId, sendNotification, sendMail);
         if (owner && sendNotification) // can be changed in the hook
             owner->GetSession()->SendAuctionOwnerNotification(auction);
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_EXPIRED), AuctionEntry::BuildAuctionMailBody(ObjectGuid::Empty, 0, auction->buyout, auction->deposit))
             .AddItem(pItem)
             .SendMailTo(trans, MailReceiver(owner, auction->owner.GetCounter()), auction, MAIL_CHECK_MASK_COPIED, 0);
     }
     else
         sAuctionMgr->RemoveAItem(auction->item_guid, true, &trans);
 }
References MailDraft::AddItem(), AUCTION_EXPIRED, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, AuctionEntry::deposit, ObjectGuid::Empty, ObjectAccessor::FindConnectedPlayer(), GetAItem(), ObjectGuid::GetCounter(), Player::GetSession(), AuctionEntry::item_guid, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, sAuctionMgr, WorldSession::SendAuctionOwnerNotification(), MailDraft::SendMailTo(), sObjectMgr, and sScriptMgr.
SendAuctionOutbiddedMail()
void AuctionHouseMgr::SendAuctionOutbiddedMail (AuctionEntry * auction, uint32 newPrice, Player * newBidder, CharacterDatabaseTransaction trans, bool sendNotification = true, bool sendMail = true)
Definition at line 428 of file AuctionHouseMgr.cpp.
 {
     Player* oldBidder = ObjectAccessor::FindConnectedPlayer(auction->bidder);
     uint32 oldBidder_accId = 0;
     if (!oldBidder)
         oldBidder_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->bidder.GetCounter());
     // old bidder exist
     if (oldBidder || oldBidder_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail(this, auction, oldBidder, oldBidder_accId, newBidder, newPrice, sendNotification, sendMail);
         if (oldBidder && newBidder && sendNotification) // can be changed in the hook
             oldBidder->GetSession()->SendAuctionBidderNotification(auction->GetHouseId(), auction->Id, newBidder->GetGUID(), newPrice, auction->GetAuctionOutBid(), auction->item_template);
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_OUTBIDDED), AuctionEntry::BuildAuctionMailBody(auction->owner, auction->bid, auction->buyout, auction->deposit, auction->GetAuctionCut()))
             .AddMoney(auction->bid)
             .SendMailTo(trans, MailReceiver(oldBidder, auction->bidder.GetCounter()), auction, MAIL_CHECK_MASK_COPIED);
     }
 }
References MailDraft::AddMoney(), AUCTION_OUTBIDDED, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, AuctionEntry::deposit, ObjectAccessor::FindConnectedPlayer(), AuctionEntry::GetAuctionCut(), AuctionEntry::GetAuctionOutBid(), ObjectGuid::GetCounter(), Object::GetGUID(), AuctionEntry::GetHouseId(), Player::GetSession(), AuctionEntry::Id, AuctionEntry::item_template, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, WorldSession::SendAuctionBidderNotification(), MailDraft::SendMailTo(), sObjectMgr, and sScriptMgr.
SendAuctionSalePendingMail()
void AuctionHouseMgr::SendAuctionSalePendingMail (AuctionEntry * auction, CharacterDatabaseTransaction trans, bool sendMail = true)
Definition at line 333 of file AuctionHouseMgr.cpp.
 {
     Player* owner = ObjectAccessor::FindConnectedPlayer(auction->owner);
     uint32 owner_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->owner.GetCounter());
     // owner exist (online or offline)
     if (owner || owner_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionSalePendingMail(this, auction, owner, owner_accId, sendMail);
         uint32 deliveryDelay = sWorld->getIntConfig(CONFIG_MAIL_DELIVERY_DELAY);
         ByteBuffer timePacker;
         timePacker.AppendPackedTime(time_t(time(nullptr) + deliveryDelay));
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_SALE_PENDING),
                 AuctionEntry::BuildAuctionMailBody(auction->bidder, auction->bid, auction->buyout, auction->deposit, auction->GetAuctionCut(), deliveryDelay, timePacker.read<uint32>()))
             .SendMailTo(trans, MailReceiver(owner, auction->owner.GetCounter()), auction, MAIL_CHECK_MASK_COPIED, 0, 0, false, true, -static_cast<int32>(auction->Id));
     }
 }
References ByteBuffer::AppendPackedTime(), AUCTION_SALE_PENDING, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, CONFIG_MAIL_DELIVERY_DELAY, AuctionEntry::deposit, ObjectAccessor::FindConnectedPlayer(), AuctionEntry::GetAuctionCut(), ObjectGuid::GetCounter(), AuctionEntry::Id, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, ByteBuffer::read(), MailDraft::SendMailTo(), sObjectMgr, sScriptMgr, and sWorld.
SendAuctionSuccessfulMail()
void AuctionHouseMgr::SendAuctionSuccessfulMail (AuctionEntry * auction, CharacterDatabaseTransaction trans, bool sendNotification = true, bool updateAchievementCriteria = true, bool sendMail = true)
Definition at line 355 of file AuctionHouseMgr.cpp.
 {
     Player* owner = ObjectAccessor::FindConnectedPlayer(auction->owner);
     uint32 owner_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->owner.GetCounter());
     // owner exist
     if (owner || owner_accId)
     {
         uint32 profit = auction->bid + auction->deposit - auction->GetAuctionCut();
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail(this, auction, owner, owner_accId, profit, sendNotification, updateAchievementCriteria, sendMail);
         if (owner)
         {
             if (updateAchievementCriteria) // can be changed in the hook
             {
                 owner->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, profit);
                 owner->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, auction->bid);
             }
             if (sendNotification) // can be changed in the hook
                 owner->GetSession()->SendAuctionOwnerNotification(auction);
         }
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_SUCCESSFUL), AuctionEntry::BuildAuctionMailBody(auction->bidder, auction->bid, auction->buyout, auction->deposit, auction->GetAuctionCut()))
             .AddMoney(profit)
             .SendMailTo(trans, MailReceiver(owner, auction->owner.GetCounter()), auction, MAIL_CHECK_MASK_COPIED, sWorld->getIntConfig(CONFIG_MAIL_DELIVERY_DELAY), 0, false, true, auction->Id);
         if (auction->bid >= 500 * GOLD)
             if (const GlobalPlayerData* gpd = sWorld->GetGlobalPlayerData(auction->bidder.GetCounter()))
             {
                 Player* bidder = ObjectAccessor::FindConnectedPlayer(auction->bidder);
                 std::string owner_name = "";
                 uint8 owner_level = 0;
                 if (const GlobalPlayerData* gpd_owner = sWorld->GetGlobalPlayerData(auction->owner.GetCounter()))
                 {
                     owner_name = gpd_owner->name;
                     owner_level = gpd_owner->level;
                 }
                 CharacterDatabase.PExecute("INSERT INTO log_money VALUES(%u, %u, \"%s\", \"%s\", %u, \"%s\", %u, \"<AH> profit: %ug, bidder: %s %u lvl (guid: %u), seller: %s %u lvl (guid: %u), item %u (%u)\", NOW())",
                     gpd->accountId, auction->bidder.GetCounter(), gpd->name.c_str(), bidder ? bidder->GetSession()->GetRemoteAddress().c_str() : "", owner_accId, owner_name.c_str(), auction->bid, (profit / GOLD), gpd->name.c_str(), gpd->level, auction->bidder.GetCounter(), owner_name.c_str(), owner_level, auction->owner.GetCounter(), auction->item_template, auction->itemCount);
             }
     }
 }
References ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, MailDraft::AddMoney(), AUCTION_SUCCESSFUL, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, CharacterDatabase, CONFIG_MAIL_DELIVERY_DELAY, AuctionEntry::deposit, ObjectAccessor::FindConnectedPlayer(), AuctionEntry::GetAuctionCut(), ObjectGuid::GetCounter(), WorldSession::GetRemoteAddress(), Player::GetSession(), GOLD, AuctionEntry::Id, AuctionEntry::item_template, AuctionEntry::itemCount, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, WorldSession::SendAuctionOwnerNotification(), MailDraft::SendMailTo(), sObjectMgr, sScriptMgr, sWorld, and Player::UpdateAchievementCriteria().
SendAuctionWonMail()
void AuctionHouseMgr::SendAuctionWonMail (AuctionEntry * auction, CharacterDatabaseTransaction trans, bool sendNotification = true, bool updateAchievementCriteria = true, bool sendMail = true)
Definition at line 291 of file AuctionHouseMgr.cpp.
 {
     Item* pItem = GetAItem(auction->item_guid);
     if (!pItem)
         return;
     uint32 bidder_accId = 0;
     Player* bidder = ObjectAccessor::FindConnectedPlayer(auction->bidder);
     if (bidder)
         bidder_accId = bidder->GetSession()->GetAccountId();
     else
         bidder_accId = sObjectMgr->GetPlayerAccountIdByGUID(auction->bidder.GetCounter());
     // receiver exist
     if (bidder || bidder_accId)
     {
         sScriptMgr->OnBeforeAuctionHouseMgrSendAuctionWonMail(this, auction, bidder, bidder_accId, sendNotification, updateAchievementCriteria, sendMail);
         // set owner to bidder (to prevent delete item with sender char deleting)
         // owner in `data` will set at mail receive and item extracting
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ITEM_OWNER);
         stmt->setUInt32(0, auction->bidder.GetCounter());
         stmt->setUInt32(1, pItem->GetGUID().GetCounter());
         trans->Append(stmt);
         if (bidder)
         {
             if (sendNotification) // can be changed in the hook
                 bidder->GetSession()->SendAuctionBidderNotification(auction->GetHouseId(), auction->Id, auction->bidder, 0, 0, auction->item_template);
             // FIXME: for offline player need also
             if (updateAchievementCriteria) // can be changed in the hook
                 bidder->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, 1);
         }
         if (sendMail) // can be changed in the hook
             MailDraft(auction->BuildAuctionMailSubject(AUCTION_WON), AuctionEntry::BuildAuctionMailBody(auction->owner, auction->bid, auction->buyout))
             .AddItem(pItem)
             .SendMailTo(trans, MailReceiver(bidder, auction->bidder.GetCounter()), auction, MAIL_CHECK_MASK_COPIED);
     }
     else
         sAuctionMgr->RemoveAItem(auction->item_guid, true, &trans);
 }
References ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, MailDraft::AddItem(), AUCTION_WON, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::BuildAuctionMailBody(), AuctionEntry::BuildAuctionMailSubject(), AuctionEntry::buyout, CHAR_UPD_ITEM_OWNER, CharacterDatabase, ObjectAccessor::FindConnectedPlayer(), WorldSession::GetAccountId(), GetAItem(), ObjectGuid::GetCounter(), Object::GetGUID(), AuctionEntry::GetHouseId(), Player::GetSession(), AuctionEntry::Id, AuctionEntry::item_guid, AuctionEntry::item_template, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, sAuctionMgr, WorldSession::SendAuctionBidderNotification(), MailDraft::SendMailTo(), PreparedStatementBase::setUInt32(), sObjectMgr, sScriptMgr, and Player::UpdateAchievementCriteria().
Update()
void AuctionHouseMgr::Update ()
Definition at line 589 of file AuctionHouseMgr.cpp.
 {
     sScriptMgr->OnBeforeAuctionHouseMgrUpdate();
     mHordeAuctions.Update();
     mAllianceAuctions.Update();
     mNeutralAuctions.Update();
 }
References mAllianceAuctions, mHordeAuctions, mNeutralAuctions, sScriptMgr, and AuctionHouseObject::Update().
Member Data Documentation
mAitems
ItemMap AuctionHouseMgr::mAitems private
Definition at line 225 of file AuctionHouseMgr.h.
Referenced by AddAItem(), GetAItem(), LoadAuctionItems(), RemoveAItem(), and ~AuctionHouseMgr().
mAllianceAuctions
AuctionHouseObject AuctionHouseMgr::mAllianceAuctions private
Definition at line 222 of file AuctionHouseMgr.h.
Referenced by GetAuctionsMap(), GetAuctionsMapByHouseId(), and Update().
mHordeAuctions
AuctionHouseObject AuctionHouseMgr::mHordeAuctions private
Definition at line 221 of file AuctionHouseMgr.h.
Referenced by GetAuctionsMap(), GetAuctionsMapByHouseId(), and Update().
mNeutralAuctions
AuctionHouseObject AuctionHouseMgr::mNeutralAuctions private
Definition at line 223 of file AuctionHouseMgr.h.
Referenced by GetAuctionsMap(), GetAuctionsMapByHouseId(), and Update().
The documentation for this class was generated from the following files:
src/server/game/AuctionHouse/AuctionHouseMgr.h
src/server/game/AuctionHouse/AuctionHouseMgr.cpp