Azerotcore-wotlk: CliHandler Class Reference
CliHandler Class Reference
#include <Chat.h>
Public Types
using Print = void(void *, std::string_view)
Public Member Functions
CliHandler (void *callbackArg, Print *zprint)
char const * GetAcoreString (uint32 entry) const override
void SendSysMessage (std::string_view, bool escapeCharacters) override
bool ParseCommands (std::string_view str) override
std::string GetNameLink () const override
bool needReportToTarget (Player *chr) const override
LocaleConstant GetSessionDbcLocale () const override
int GetSessionDbLocaleIndex () const override
Public Member Functions inherited from ChatHandler
ChatHandler (WorldSession *session)
virtual ~ChatHandler ()
void SendSysMessage (uint32 entry)
template<typename... Args>
void PSendSysMessage (char const *fmt, Args &&... args)
template<typename... Args>
void PSendSysMessage (uint32 entry, Args &&... args)
template<typename... Args>
std::string PGetParseString (uint32 entry, Args &&... args) const
bool _ParseCommands (std::string_view text)
void SendGlobalSysMessage (const char *str)
virtual bool IsHumanReadable () const
bool HasLowerSecurity (Player *target, ObjectGuid guid=ObjectGuid::Empty, bool strong=false)
bool HasLowerSecurityAccount (WorldSession *target, uint32 account, bool strong=false)
void SendGlobalGMSysMessage (const char *str)
Player * getSelectedPlayer ()
Creature * getSelectedCreature ()
Unit * getSelectedUnit ()
WorldObject * getSelectedObject ()
Player * getSelectedPlayerOrSelf ()
char * extractKeyFromLink (char *text, char const *linkType, char **something1=nullptr)
char * extractKeyFromLink (char *text, char const *const *linkTypes, int *found_idx, char **something1=nullptr)
char * extractQuotedArg (char *args)
uint32 extractSpellIdFromLink (char *text)
ObjectGuid::LowType extractLowGuidFromLink (char *text, HighGuid &guidHigh)
bool GetPlayerGroupAndGUIDByName (const char *cname, Player *&player, Group *&group, ObjectGuid &guid, bool offline=false)
std::string extractPlayerNameFromLink (char *text)
bool extractPlayerTarget (char *args, Player **player, ObjectGuid *player_guid=nullptr, std::string *player_name=nullptr)
std::string playerLink (std::string const &name) const
std::string GetNameLink (Player *chr) const
GameObject * GetNearbyGameObject ()
GameObject * GetObjectFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
Creature * GetCreatureFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
bool HasSentErrorMessage () const
void SetSentErrorMessage (bool val)
bool IsConsole () const
Player * GetPlayer () const
WorldSession * GetSession ()
bool IsAvailable (uint32 securityLevel) const
Private Attributes
void * m_callbackArg
Print * m_print
Additional Inherited Members
Static Public Member Functions inherited from ChatHandler
static size_t BuildChatPacket (WorldPacket &data, ChatMsg chatType, Language language, ObjectGuid senderGUID, ObjectGuid receiverGUID, std::string_view message, uint8 chatTag, std::string const &senderName="", std::string const &receiverName="", uint32 achievementId=0, bool gmMessage=false, std::string const &channelName="")
static size_t BuildChatPacket (WorldPacket &data, ChatMsg chatType, Language language, WorldObject const *sender, WorldObject const *receiver, std::string_view message, uint32 achievementId=0, std::string const &channelName="", LocaleConstant locale=DEFAULT_LOCALE)
static char * LineFromMessage (char *&pos)
Protected Member Functions inherited from ChatHandler
ChatHandler ()
Detailed Description
Definition at line 134 of file Chat.h.
Member Typedef Documentation
Print
using CliHandler::Print = void(void*, std::string_view)
Definition at line 137 of file Chat.h.
Constructor & Destructor Documentation
CliHandler()
CliHandler::CliHandler (void * callbackArg, Print * zprint) inline explicit
Definition at line 138 of file Chat.h.
 : m_callbackArg(callbackArg), m_print(zprint) { }
Member Function Documentation
GetAcoreString()
char const * CliHandler::GetAcoreString (uint32 entry) const override virtual
Reimplemented from ChatHandler.
Definition at line 802 of file Chat.cpp.
 {
     return sObjectMgr->GetAcoreStringForDBCLocale(entry);
 }
References sObjectMgr.
Referenced by GetNameLink().
GetNameLink()
std::string CliHandler::GetNameLink () const override virtual
Reimplemented from ChatHandler.
Definition at line 825 of file Chat.cpp.
 {
     return GetAcoreString(LANG_CONSOLE_COMMAND);
 }
References GetAcoreString(), and LANG_CONSOLE_COMMAND.
GetSessionDbcLocale()
LocaleConstant CliHandler::GetSessionDbcLocale () const override virtual
Reimplemented from ChatHandler.
Definition at line 879 of file Chat.cpp.
 {
     return sWorld->GetDefaultDbcLocale();
 }
References sWorld.
GetSessionDbLocaleIndex()
int CliHandler::GetSessionDbLocaleIndex () const override virtual
Reimplemented from ChatHandler.
Definition at line 884 of file Chat.cpp.
 {
     return sObjectMgr->GetDBCLocaleIndex();
 }
References sObjectMgr.
needReportToTarget()
bool CliHandler::needReportToTarget (Player * chr) const override virtual
Reimplemented from ChatHandler.
Definition at line 830 of file Chat.cpp.
 {
     return true;
 }
ParseCommands()
bool CliHandler::ParseCommands (std::string_view str) override virtual
Reimplemented from ChatHandler.
Definition at line 813 of file Chat.cpp.
 {
     if (str.empty())
         return false;
     // Console allows using commands both with and without leading indicator
     if (str[0] == '.' || str[0] == '!')
         str = str.substr(1);
     return _ParseCommands(str);
 }
References ChatHandler::_ParseCommands().
Referenced by World::ProcessCliCommands().
SendSysMessage()
void CliHandler::SendSysMessage (std::string_view str, bool escapeCharacters) override virtual
Reimplemented from ChatHandler.
Definition at line 807 of file Chat.cpp.
 {
     m_print(m_callbackArg, str);
     m_print(m_callbackArg, "\r\n");
 }
References m_callbackArg, and m_print.
Member Data Documentation
m_callbackArg
void* CliHandler::m_callbackArg private
Definition at line 150 of file Chat.h.
Referenced by SendSysMessage().
m_print
Print* CliHandler::m_print private
Definition at line 151 of file Chat.h.
Referenced by SendSysMessage().
The documentation for this class was generated from the following files:
src/server/game/Chat/Chat.h
src/server/game/Chat/Chat.cpp