Azerotcore-wotlk: WorldObjectChangeAccumulator Struct Reference
WorldObjectChangeAccumulator Struct Reference
Public Member Functions
WorldObjectChangeAccumulator (WorldObject &obj, UpdateDataMapType &d, UpdatePlayerSet &p)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (DynamicObjectMapType &m)
void BuildPacket (Player *player)
template<class SKIP >
void Visit (GridRefMgr< SKIP > &)
Public Attributes
UpdateDataMapType & i_updateDatas
UpdatePlayerSet & i_playerSet
WorldObject & i_object
Detailed Description
Definition at line 3049 of file Object.cpp.
Constructor & Destructor Documentation
WorldObjectChangeAccumulator()
WorldObjectChangeAccumulator::WorldObjectChangeAccumulator (WorldObject & obj, UpdateDataMapType & d, UpdatePlayerSet & p) inline
Definition at line 3054 of file Object.cpp.
                                                                                              : i_updateDatas(d), i_playerSet(p), i_object(obj)
     {
         i_playerSet.clear();
     }
References i_playerSet.
Member Function Documentation
BuildPacket()
void WorldObjectChangeAccumulator::BuildPacket (Player * player) inline
Definition at line 3109 of file Object.cpp.
     {
         // Only send update once to a player
         if (i_playerSet.find(player->GetGUID()) == i_playerSet.end() && player->HaveAtClient(&i_object))
         {
             i_object.BuildFieldsUpdate(player, i_updateDatas);
             i_playerSet.insert(player->GetGUID());
         }
     }
References Object::BuildFieldsUpdate(), Object::GetGUID(), Player::HaveAtClient(), i_object, i_playerSet, and i_updateDatas.
Referenced by Visit().
Visit() [1/4]
void WorldObjectChangeAccumulator::Visit (CreatureMapType & m) inline
Definition at line 3076 of file Object.cpp.
     {
         Creature* source = nullptr;
         for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
         {
             source = iter->GetSource();
             if (source->HasSharedVision())
             {
                 SharedVisionList::const_iterator it = source->GetSharedVisionList().begin();
                 for (; it != source->GetSharedVisionList().end(); ++it)
                     BuildPacket(*it);
             }
         }
     }
References GridRefMgr< OBJECT >::begin(), BuildPacket(), GridRefMgr< OBJECT >::end(), Unit::GetSharedVisionList(), and Unit::HasSharedVision().
Visit() [2/4]
void WorldObjectChangeAccumulator::Visit (DynamicObjectMapType & m) inline
Definition at line 3091 of file Object.cpp.
     {
         DynamicObject* source = nullptr;
         for (DynamicObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
         {
             source = iter->GetSource();
             ObjectGuid guid = source->GetCasterGUID();
             if (guid)
             {
                 //Caster may be nullptr if DynObj is in removelist
                 if (Player* caster = ObjectAccessor::FindPlayer(guid))
                     if (caster->GetGuidValue(PLAYER_FARSIGHT) == source->GetGUID())
                         BuildPacket(caster);
             }
         }
     }
References GridRefMgr< OBJECT >::begin(), BuildPacket(), GridRefMgr< OBJECT >::end(), ObjectAccessor::FindPlayer(), DynamicObject::GetCasterGUID(), Object::GetGUID(), and PLAYER_FARSIGHT.
Visit() [3/4]
template<class SKIP > void WorldObjectChangeAccumulator::Visit (GridRefMgr< SKIP > &) inline
Definition at line 3119 of file Object.cpp.
 {}
Visit() [4/4]
void WorldObjectChangeAccumulator::Visit (PlayerMapType & m) inline
Definition at line 3058 of file Object.cpp.
     {
         Player* source = nullptr;
         for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
         {
             source = iter->GetSource();
             BuildPacket(source);
             if (source->HasSharedVision())
             {
                 SharedVisionList::const_iterator it = source->GetSharedVisionList().begin();
                 for (; it != source->GetSharedVisionList().end(); ++it)
                     BuildPacket(*it);
             }
         }
     }
References GridRefMgr< OBJECT >::begin(), BuildPacket(), GridRefMgr< OBJECT >::end(), Unit::GetSharedVisionList(), and Unit::HasSharedVision().
Member Data Documentation
i_object
WorldObject& WorldObjectChangeAccumulator::i_object
Definition at line 3053 of file Object.cpp.
Referenced by BuildPacket().
i_playerSet
UpdatePlayerSet& WorldObjectChangeAccumulator::i_playerSet
Definition at line 3052 of file Object.cpp.
Referenced by BuildPacket(), and WorldObjectChangeAccumulator().
i_updateDatas
UpdateDataMapType& WorldObjectChangeAccumulator::i_updateDatas
Definition at line 3051 of file Object.cpp.
Referenced by BuildPacket().
The documentation for this struct was generated from the following file:
src/server/game/Entities/Object/Object.cpp