Azerotcore-wotlk: boss_ossirian::boss_ossirianAI Struct Reference
boss_ossirian::boss_ossirianAI Struct Reference
Public Member Functions
boss_ossirianAI (Creature *creature)
void Reset () override
void SpellHit (Unit *caster, SpellInfo const *spell) override
void DoAction (int32 action) override
void EnterCombat (Unit *) override
void KilledUnit (Unit *) override
void EnterEvadeMode () override
void JustDied (Unit *) override
void Cleanup ()
void SpawnNextCrystal ()
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid TriggerGUID
ObjectGuid CrystalGUID
uint8 CrystalIterator
bool SaidIntro
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 87 of file boss_ossirian.cpp.
Constructor & Destructor Documentation
boss_ossirianAI()
boss_ossirian::boss_ossirianAI::boss_ossirianAI (Creature * creature) inline
Definition at line 89 of file boss_ossirian.cpp.
                                             : BossAI(creature, DATA_OSSIRIAN)
         {
             SaidIntro = false;
         }
References SaidIntro.
Member Function Documentation
Cleanup()
void boss_ossirian::boss_ossirianAI::Cleanup () inline
Definition at line 175 of file boss_ossirian.cpp.
         {
             if (GameObject* Crystal = me->GetMap()->GetGameObject(CrystalGUID))
                 Crystal->Use(me);
         }
References CrystalGUID, Map::GetGameObject(), WorldObject::GetMap(), and ScriptedAI::me.
Referenced by EnterEvadeMode(), and JustDied().
DoAction()
void boss_ossirian::boss_ossirianAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 120 of file boss_ossirian.cpp.
         {
             if (action == ACTION_TRIGGER_WEAKNESS)
                 if (Creature* Trigger = me->GetMap()->GetCreature(TriggerGUID))
                     if (!Trigger->HasUnitState(UNIT_STATE_CASTING))
                         Trigger->CastSpell(Trigger, SpellWeakness[urand(0, 4)], false);
         }
References ACTION_TRIGGER_WEAKNESS, Map::GetCreature(), WorldObject::GetMap(), ScriptedAI::me, SpellWeakness, TriggerGUID, UNIT_STATE_CASTING, and urand().
EnterCombat()
void boss_ossirian::boss_ossirianAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 128 of file boss_ossirian.cpp.
         {
             _EnterCombat();
             events.Reset();
             events.ScheduleEvent(EVENT_SILENCE, 30000);
             events.ScheduleEvent(EVENT_CYCLONE, 20000);
             events.ScheduleEvent(EVENT_STOMP, 30000);
             DoCast(me, SPELL_SUPREME);
             Talk(SAY_AGGRO);
             Map* map = me->GetMap();
             if (!map->IsDungeon())
                 return;
             WorldPacket data(SMSG_WEATHER, (4 + 4 + 4));
             data << uint32(WEATHER_STATE_HEAVY_SANDSTORM) << float(1) << uint8(0);
             map->SendToPlayers(&data);
             for (uint8 i = 0; i < NUM_TORNADOS; ++i)
             {
                 Position Point = me->GetRandomPoint(RoomCenter, RoomRadius);
                 if (Creature* Tornado = me->GetMap()->SummonCreature(NPC_SAND_VORTEX, Point))
                     Tornado->CastSpell(Tornado, SPELL_SAND_STORM, true);
             }
             SpawnNextCrystal();
         }
References BossAI::_EnterCombat(), UnitAI::DoCast(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_STOMP, WorldObject::GetMap(), WorldObject::GetRandomPoint(), Map::IsDungeon(), ScriptedAI::me, NPC_SAND_VORTEX, NUM_TORNADOS, RoomCenter, RoomRadius, SAY_AGGRO, Map::SendToPlayers(), SMSG_WEATHER, SpawnNextCrystal(), SPELL_SAND_STORM, SPELL_SUPREME, Map::SummonCreature(), CreatureAI::Talk(), and WEATHER_STATE_HEAVY_SANDSTORM.
EnterEvadeMode()
void boss_ossirian::boss_ossirianAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 162 of file boss_ossirian.cpp.
         {
             Cleanup();
             summons.DespawnAll();
             BossAI::EnterEvadeMode();
         }
References Cleanup(), SummonList::DespawnAll(), CreatureAI::EnterEvadeMode(), and BossAI::summons.
JustDied()
void boss_ossirian::boss_ossirianAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 169 of file boss_ossirian.cpp.
         {
             Cleanup();
             _JustDied();
         }
References BossAI::_JustDied(), and Cleanup().
KilledUnit()
void boss_ossirian::boss_ossirianAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 157 of file boss_ossirian.cpp.
         {
             Talk(SAY_SLAY);
         }
References SAY_SLAY, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_ossirian::boss_ossirianAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 202 of file boss_ossirian.cpp.
         {
             if (!SaidIntro)
             {
                 Talk(SAY_INTRO);
                 SaidIntro = true;
             }
             BossAI::MoveInLineOfSight(who);
         }
References CreatureAI::MoveInLineOfSight(), SaidIntro, SAY_INTRO, and CreatureAI::Talk().
Reset()
void boss_ossirian::boss_ossirianAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 99 of file boss_ossirian.cpp.
         {
             _Reset();
             CrystalIterator = 0;
             TriggerGUID.Clear();
             CrystalGUID.Clear();
         }
References BossAI::_Reset(), ObjectGuid::Clear(), CrystalGUID, CrystalIterator, and TriggerGUID.
SpawnNextCrystal()
void boss_ossirian::boss_ossirianAI::SpawnNextCrystal () inline
Definition at line 181 of file boss_ossirian.cpp.
         {
             if (CrystalIterator == NUM_CRYSTALS)
                 CrystalIterator = 0;
             if (Creature* Trigger = me->GetMap()->SummonCreature(NPC_OSSIRIAN_TRIGGER, CrystalCoordinates[CrystalIterator]))
             {
                 TriggerGUID = Trigger->GetGUID();
                 if (GameObject* Crystal = Trigger->SummonGameObject(GO_OSSIRIAN_CRYSTAL,
                                           CrystalCoordinates[CrystalIterator].GetPositionX(),
                                           CrystalCoordinates[CrystalIterator].GetPositionY(),
                                           CrystalCoordinates[CrystalIterator].GetPositionZ(),
                                           0, 0, 0, 0, 0, uint32(-1)))
                 {
                     CrystalGUID = Crystal->GetGUID();
                     ++CrystalIterator;
                     Crystal->SetOwnerGUID(ObjectGuid::Empty);
                 }
             }
         }
References CrystalCoordinates, CrystalGUID, CrystalIterator, ObjectGuid::Empty, WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_OSSIRIAN_CRYSTAL, ScriptedAI::me, NPC_OSSIRIAN_TRIGGER, NUM_CRYSTALS, Map::SummonCreature(), WorldObject::SummonGameObject(), and TriggerGUID.
Referenced by EnterCombat(), and SpellHit().
SpellHit()
void boss_ossirian::boss_ossirianAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 107 of file boss_ossirian.cpp.
         {
             for (uint8 i = 0; i < NUM_WEAKNESS; ++i)
             {
                 if (spell->Id == SpellWeakness[i])
                 {
                     me->RemoveAurasDueToSpell(SPELL_SUPREME);
                     ((TempSummon*)caster)->UnSummon();
                     SpawnNextCrystal();
                 }
             }
         }
References SpellInfo::Id, ScriptedAI::me, NUM_WEAKNESS, Unit::RemoveAurasDueToSpell(), SpawnNextCrystal(), SPELL_SUPREME, and SpellWeakness.
UpdateAI()
void boss_ossirian::boss_ossirianAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 213 of file boss_ossirian.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             // No kiting!
             if (me->GetDistance(me->GetVictim()) > 60.00f && me->GetDistance(me->GetVictim()) < 120.00f)
                 DoCastVictim(SPELL_SUMMON);
             bool ApplySupreme = true;
             if (me->HasAura(SPELL_SUPREME))
                 ApplySupreme = false;
             else
             {
                 for (uint8 i = 0; i < NUM_WEAKNESS; ++i)
                 {
                     if (me->HasAura(SpellWeakness[i]))
                     {
                         ApplySupreme = false;
                         break;
                     }
                 }
             }
             if (ApplySupreme)
             {
                 DoCast(me, SPELL_SUPREME);
                 Talk(SAY_SUPREME);
             }
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SILENCE:
                         DoCast(me, SPELL_SILENCE);
                         events.ScheduleEvent(EVENT_SILENCE, urand(20000, 30000));
                         break;
                     case EVENT_CYCLONE:
                         DoCastVictim(SPELL_CYCLONE);
                         events.ScheduleEvent(EVENT_CYCLONE, 20000);
                         break;
                     case EVENT_STOMP:
                         DoCast(me, SPELL_STOMP);
                         events.ScheduleEvent(EVENT_STOMP, 30000);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_CYCLONE, EVENT_SILENCE, EVENT_STOMP, WorldObject::GetDistance(), Unit::GetVictim(), Unit::HasAura(), ScriptedAI::me, NUM_WEAKNESS, SAY_SUPREME, SPELL_CYCLONE, SPELL_SILENCE, SPELL_STOMP, SPELL_SUMMON, SPELL_SUPREME, SpellWeakness, CreatureAI::Talk(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
CrystalGUID
ObjectGuid boss_ossirian::boss_ossirianAI::CrystalGUID
Definition at line 95 of file boss_ossirian.cpp.
Referenced by Cleanup(), Reset(), and SpawnNextCrystal().
CrystalIterator
uint8 boss_ossirian::boss_ossirianAI::CrystalIterator
Definition at line 96 of file boss_ossirian.cpp.
Referenced by Reset(), and SpawnNextCrystal().
SaidIntro
bool boss_ossirian::boss_ossirianAI::SaidIntro
Definition at line 97 of file boss_ossirian.cpp.
Referenced by boss_ossirianAI(), and MoveInLineOfSight().
TriggerGUID
ObjectGuid boss_ossirian::boss_ossirianAI::TriggerGUID
Definition at line 94 of file boss_ossirian.cpp.
Referenced by DoAction(), Reset(), and SpawnNextCrystal().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp