Azerotcore-wotlk: at_icc_saurfang_portal Class Reference
at_icc_saurfang_portal Class Reference
Public Member Functions
at_icc_saurfang_portal ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 2262 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
at_icc_saurfang_portal()
at_icc_saurfang_portal::at_icc_saurfang_portal () inline
Definition at line 2265 of file icecrown_citadel.cpp.
 : AreaTriggerScript("at_icc_saurfang_portal") { }
Member Function Documentation
OnTrigger()
bool at_icc_saurfang_portal::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 2267 of file icecrown_citadel.cpp.
     {
         InstanceScript* instance = player->GetInstanceScript();
         if (!instance || instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE)
             return true;
         Position destPos = {4126.35f, 2769.23f, 350.963f, 0.0f};
         if (instance->GetData(DATA_COLDFLAME_JETS) == NOT_STARTED)
         {
             // save original player position
             float x, y, z, o;
             player->GetPosition(x, y, z, o);
             // move player to preload grid and be able to select nearby npcs
             player->GetMap()->PlayerRelocation(player, destPos.GetPositionX(), destPos.GetPositionY(), destPos.GetPositionZ(), destPos.GetOrientation());
             instance->SetData(DATA_COLDFLAME_JETS, IN_PROGRESS);
             std::list<Creature*> traps;
             GetCreatureListWithEntryInGrid(traps, player, NPC_FROST_FREEZE_TRAP, 120.0f);
             traps.sort(Acore::ObjectDistanceOrderPred(player));
             bool instant = false;
             for (std::list<Creature*>::iterator itr = traps.begin(); itr != traps.end(); ++itr)
             {
                 (*itr)->AI()->DoAction(instant ? 1000 : 11000);
                 instant = !instant;
             }
             // restore original position
             player->GetMap()->PlayerRelocation(player, x, y, z, o);
         }
         player->TeleportTo(631, destPos.GetPositionX(), destPos.GetPositionY(), destPos.GetPositionZ(), destPos.GetOrientation());
         return true;
     }
References DATA_COLDFLAME_JETS, DATA_DEATHBRINGER_SAURFANG, DONE, InstanceScript::GetBossState(), GetCreatureListWithEntryInGrid(), ZoneScript::GetData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IN_PROGRESS, NOT_STARTED, NPC_FROST_FREEZE_TRAP, Map::PlayerRelocation(), ZoneScript::SetData(), and Player::TeleportTo().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp