Azerotcore-wotlk: npc_coren_direbrew::npc_coren_direbrewAI Struct Reference
npc_coren_direbrew::npc_coren_direbrewAI Struct Reference
Public Member Functions
npc_coren_direbrewAI (Creature *creature)
void sGossipSelect (Player *player, uint32 menuId, uint32 gossipListId) override
bool CanBeSeen (Player const *player) override
void Reset () override
void MoveInLineOfSight (Unit *who) override
void JustSummoned (Creature *creature) override
void DoAction (int32 action) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustDied (Unit *) override
void SummonSister (uint32 entry)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
SummonList _summons
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1732 of file brewfest.cpp.
Constructor & Destructor Documentation
npc_coren_direbrewAI()
npc_coren_direbrew::npc_coren_direbrewAI::npc_coren_direbrewAI (Creature * creature) inline
Definition at line 1734 of file brewfest.cpp.
 : ScriptedAI(creature), _summons(me) {}
Member Function Documentation
CanBeSeen()
bool npc_coren_direbrew::npc_coren_direbrewAI::CanBeSeen (Player const * player) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1754 of file brewfest.cpp.
         {
             if (player->IsGameMaster())
             {
                 return true;
             }
             Group const* group = player->GetGroup();
             return group && sLFGMgr->GetDungeon(group->GetGUID()) == lfg::LFG_DUNGEON_COREN_DIREBREW;
         }
References Player::GetGroup(), Group::GetGUID(), Player::IsGameMaster(), lfg::LFG_DUNGEON_COREN_DIREBREW, and sLFGMgr.
DamageTaken()
void npc_coren_direbrew::npc_coren_direbrewAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1820 of file brewfest.cpp.
         {
             if (me->HealthBelowPctDamaged(66, damage) && _events.IsInPhase(PHASE_ONE))
             {
                 _events.SetPhase(PHASE_TWO);
                 SummonSister(NPC_ILSA_DIREBREW);
             }
             else if (me->HealthBelowPctDamaged(33, damage) && _events.IsInPhase(PHASE_TWO))
             {
                 _events.SetPhase(PHASE_THREE);
                 SummonSister(NPC_URSULA_DIREBREW);
             }
         }
References _events, Unit::HealthBelowPctDamaged(), EventMap::IsInPhase(), ScriptedAI::me, NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, PHASE_ONE, PHASE_THREE, PHASE_TWO, EventMap::SetPhase(), and SummonSister().
DoAction()
void npc_coren_direbrew::npc_coren_direbrewAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1803 of file brewfest.cpp.
         {
             if (action == ACTION_START_FIGHT)
             {
                 _events.SetPhase(PHASE_ONE);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                 me->SetFaction(FACTION_GOBLIN_DARK_IRON_BAR_PATRON);
                 DoZoneInCombat();
                 EntryCheckPredicate pred(NPC_ANTAGONIST);
                 _summons.DoAction(ACTION_ANTAGONIST_HOSTILE, pred);
                 _events.ScheduleEvent(EVENT_SUMMON_MOLE_MACHINE, 15 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_DIREBREW_DISARM, 20 * IN_MILLISECONDS);
             }
         }
References _events, _summons, ACTION_ANTAGONIST_HOSTILE, ACTION_START_FIGHT, SummonList::DoAction(), CreatureAI::DoZoneInCombat(), EVENT_DIREBREW_DISARM, EVENT_SUMMON_MOLE_MACHINE, FACTION_GOBLIN_DARK_IRON_BAR_PATRON, IN_MILLISECONDS, ScriptedAI::me, NPC_ANTAGONIST, PHASE_ONE, Object::RemoveFlag(), EventMap::ScheduleEvent(), Unit::SetFaction(), EventMap::SetPhase(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Referenced by sGossipSelect().
JustDied()
void npc_coren_direbrew::npc_coren_direbrewAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1846 of file brewfest.cpp.
         {
             _events.Reset();
             _summons.DespawnAll();
             Map::PlayerList const& players = me->GetMap()->GetPlayers();
             if (!players.isEmpty())
             {
                 if (Group* group = players.begin()->GetSource()->GetGroup())
                 {
                     if (group->isLFGGroup())
                     {
                         sLFGMgr->FinishDungeon(group->GetGUID(), 287, me->GetMap());
                     }
                 }
             }
         }
References _events, _summons, MapRefMgr::begin(), SummonList::DespawnAll(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::isEmpty(), ScriptedAI::me, EventMap::Reset(), and sLFGMgr.
JustSummoned()
void npc_coren_direbrew::npc_coren_direbrewAI::JustSummoned (Creature * creature) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1798 of file brewfest.cpp.
         {
             _summons.Summon(creature);
         }
References _summons, and SummonList::Summon().
MoveInLineOfSight()
void npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1786 of file brewfest.cpp.
         {
             if (!_events.IsInPhase(PHASE_ALL) || who->GetTypeId() != TYPEID_PLAYER)
             {
                 return;
             }
             _events.SetPhase(PHASE_INTRO);
             _events.ScheduleEvent(EVENT_INTRO_1, 6 * IN_MILLISECONDS, 0, PHASE_INTRO);
             Talk(SAY_INTRO);
         }
References _events, EVENT_INTRO_1, Object::GetTypeId(), IN_MILLISECONDS, EventMap::IsInPhase(), PHASE_ALL, PHASE_INTRO, SAY_INTRO, EventMap::ScheduleEvent(), EventMap::SetPhase(), CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void npc_coren_direbrew::npc_coren_direbrewAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1765 of file brewfest.cpp.
         {
             _events.Reset();
             _summons.DespawnAll();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             me->SetFaction(FACTION_FRIENDLY);
             _events.SetPhase(PHASE_ALL);
             for (uint8 i = 0; i < MAX_ANTAGONISTS; ++i)
             {
                 me->SummonCreature(NPC_ANTAGONIST, AntagonistPos[i], TEMPSUMMON_DEAD_DESPAWN);
             }
             std::list<GameObject*> machines;
             GetGameObjectListWithEntryInGrid(machines, me, GO_MACHINE_SUMMONER, 60.f);
             for (GameObject* go : machines)
             {
                 go->Delete();
             }
         }
References _events, _summons, AntagonistPos, SummonList::DespawnAll(), FACTION_FRIENDLY, GetGameObjectListWithEntryInGrid(), GO_MACHINE_SUMMONER, MAX_ANTAGONISTS, ScriptedAI::me, NPC_ANTAGONIST, PHASE_ALL, EventMap::Reset(), Unit::SetFaction(), Object::SetFlag(), EventMap::SetPhase(), WorldObject::SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
sGossipSelect()
void npc_coren_direbrew::npc_coren_direbrewAI::sGossipSelect (Player * player, uint32 menuId, uint32 gossipListId) inline override virtual
Reimplemented from UnitAI.
Definition at line 1736 of file brewfest.cpp.
         {
             if (menuId != GOSSIP_ID)
             {
                 return;
             }
             if (gossipListId == GOSSIP_OPTION_FIGHT)
             {
                 Talk(SAY_INSULT, player);
                 DoAction(ACTION_START_FIGHT);
             }
             else if (gossipListId == GOSSIP_OPTION_APOLOGIZE)
             {
                 CloseGossipMenuFor(player);
             }
         }
References ACTION_START_FIGHT, CloseGossipMenuFor(), DoAction(), GOSSIP_ID, GOSSIP_OPTION_APOLOGIZE, GOSSIP_OPTION_FIGHT, SAY_INSULT, and CreatureAI::Talk().
SummonedCreatureDies()
void npc_coren_direbrew::npc_coren_direbrewAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1834 of file brewfest.cpp.
         {
             if (summon->GetEntry() == NPC_ILSA_DIREBREW)
             {
                 _events.ScheduleEvent(EVENT_RESPAWN_ILSA, 1 * IN_MILLISECONDS);
             }
             else if (summon->GetEntry() == NPC_URSULA_DIREBREW)
             {
                 _events.ScheduleEvent(EVENT_RESPAWN_URSULA, 1 * IN_MILLISECONDS);
             }
         }
References _events, EVENT_RESPAWN_ILSA, EVENT_RESPAWN_URSULA, Object::GetEntry(), IN_MILLISECONDS, NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, and EventMap::ScheduleEvent().
SummonSister()
void npc_coren_direbrew::npc_coren_direbrewAI::SummonSister (uint32 entry) inline
Definition at line 1864 of file brewfest.cpp.
         {
             if (Creature* sister = me->SummonCreature(entry, me->GetPosition(), TEMPSUMMON_DEAD_DESPAWN))
             {
                 DoZoneInCombat(sister);
             }
         }
References CreatureAI::DoZoneInCombat(), Position::GetPosition(), ScriptedAI::me, WorldObject::SummonCreature(), and TEMPSUMMON_DEAD_DESPAWN.
Referenced by DamageTaken(), and UpdateAI().
UpdateAI()
void npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1872 of file brewfest.cpp.
         {
             if (!UpdateVictim() && !_events.IsInPhase(PHASE_INTRO))
             {
                 return;
             }
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 return;
             }
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_INTRO_1:
                         Talk(SAY_INTRO1);
                         _events.ScheduleEvent(EVENT_INTRO_2, 4 * IN_MILLISECONDS, 0, PHASE_INTRO);
                         break;
                     case EVENT_INTRO_2:
                     {
                         EntryCheckPredicate pred(NPC_ANTAGONIST);
                         _summons.DoAction(ACTION_ANTAGONIST_SAY_1, pred);
                         _events.ScheduleEvent(EVENT_INTRO_3, 3 * IN_MILLISECONDS, 0, PHASE_INTRO);
                         break;
                     }
                     case EVENT_INTRO_3:
                     {
                         Talk(SAY_INTRO2);
                         EntryCheckPredicate pred(NPC_ANTAGONIST);
                         _summons.DoAction(ACTION_ANTAGONIST_SAY_2, pred);
                         break;
                     }
                     case EVENT_RESPAWN_ILSA:
                         SummonSister(NPC_ILSA_DIREBREW);
                         break;
                     case EVENT_RESPAWN_URSULA:
                         SummonSister(NPC_URSULA_DIREBREW);
                         break;
                     case EVENT_SUMMON_MOLE_MACHINE:
                     {
                         me->CastCustomSpell(SPELL_MOLE_MACHINE_TARGET_PICKER, SPELLVALUE_MAX_TARGETS, 1, nullptr, true);
                         _events.RepeatEvent(15 * IN_MILLISECONDS);
                         break;
                     }
                     case EVENT_DIREBREW_DISARM:
                         DoCastSelf(SPELL_DIREBREW_DISARM_PRE_CAST, true);
                         _events.RepeatEvent(20 * IN_MILLISECONDS);
                         break;
                     default:
                         break;
                 }
                 if (me->HasUnitState(UNIT_STATE_CASTING))
                 {
                     return;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, _summons, ACTION_ANTAGONIST_SAY_1, ACTION_ANTAGONIST_SAY_2, Unit::CastCustomSpell(), diff(), SummonList::DoAction(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EVENT_DIREBREW_DISARM, EVENT_INTRO_1, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_RESPAWN_ILSA, EVENT_RESPAWN_URSULA, EVENT_SUMMON_MOLE_MACHINE, EventMap::ExecuteEvent(), Unit::HasUnitState(), IN_MILLISECONDS, EventMap::IsInPhase(), ScriptedAI::me, NPC_ANTAGONIST, NPC_ILSA_DIREBREW, NPC_URSULA_DIREBREW, PHASE_INTRO, EventMap::RepeatEvent(), SAY_INTRO1, SAY_INTRO2, EventMap::ScheduleEvent(), SPELL_DIREBREW_DISARM_PRE_CAST, SPELL_MOLE_MACHINE_TARGET_PICKER, SPELLVALUE_MAX_TARGETS, SummonSister(), CreatureAI::Talk(), UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events
EventMap npc_coren_direbrew::npc_coren_direbrewAI::_events private
Definition at line 1938 of file brewfest.cpp.
Referenced by DamageTaken(), DoAction(), JustDied(), MoveInLineOfSight(), Reset(), SummonedCreatureDies(), and UpdateAI().
_summons
SummonList npc_coren_direbrew::npc_coren_direbrewAI::_summons private
Definition at line 1939 of file brewfest.cpp.
Referenced by DoAction(), JustDied(), JustSummoned(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/brewfest.cpp