Azerotcore-wotlk: npc_varian_wrynn Class Reference
npc_varian_wrynn Class Reference
Classes
struct npc_varian_wrynnAI
Public Member Functions
npc_varian_wrynn ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 937 of file zone_undercity.cpp.
Constructor & Destructor Documentation
npc_varian_wrynn()
npc_varian_wrynn::npc_varian_wrynn () inline
Definition at line 940 of file zone_undercity.cpp.
 : CreatureScript("npc_varian_wrynn") { }
Member Function Documentation
GetAI()
CreatureAI* npc_varian_wrynn::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 2078 of file zone_undercity.cpp.
     {
         return new npc_varian_wrynnAI(creature);
     }
OnGossipHello()
bool npc_varian_wrynn::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 968 of file zone_undercity.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (player->GetQuestStatus(QUEST_BATTLE_A) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_WRYNN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, GOSSIP_WRYNN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_BATTLE_A, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_varian_wrynn::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 942 of file zone_undercity.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 CloseGossipMenuFor(player);
                 if (auto ai = CAST_AI(npc_varian_wrynn::npc_varian_wrynnAI, creature->AI()))
                 {
                     ai->Start(true, true, player->GetGUID());
                     if (Creature* jaina = GetClosestCreatureWithEntry(creature, NPC_JAINA, 50.0f))
                         ai->jainaGUID = jaina->GetGUID();
                     else
                         ai->jainaGUID.Clear();
                     ai->SetDespawnAtEnd(false);
                     ai->SetDespawnAtFar(false);
                 }
                 break;
         }
         return true;
     }
References Creature::AI(), CAST_AI, ClearGossipMenuFor(), CloseGossipMenuFor(), GetClosestCreatureWithEntry(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, and NPC_JAINA.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_undercity.cpp