Azerotcore-wotlk: deps/mysqllite/include/typelib.h File Reference
typelib.h File Reference
#include "my_alloc.h"
Classes
struct st_typelib
Typedefs
typedef struct st_typelib TYPELIB
Functions
my_ulonglong find_typeset (char *x, TYPELIB *typelib, int *error_position)
int find_type_or_exit (const char *x, TYPELIB *typelib, const char *option)
int find_type (char *x, const TYPELIB *typelib, unsigned int full_name)
void make_type (char *to, unsigned int nr, TYPELIB *typelib)
const char * get_type (TYPELIB *typelib, unsigned int nr)
TYPELIB * copy_typelib (MEM_ROOT *root, TYPELIB *from)
my_ulonglong find_set_from_flags (const TYPELIB *lib, unsigned int default_name, my_ulonglong cur_set, my_ulonglong default_set, const char *str, unsigned int length, char **err_pos, unsigned int *err_len)
Variables
TYPELIB sql_protocol_typelib
Typedef Documentation
TYPELIB
typedef struct st_typelib TYPELIB
Function Documentation
copy_typelib()
TYPELIB* copy_typelib (MEM_ROOT * root, TYPELIB * from)
Create a copy of a specified TYPELIB structure.
Parameters
root pointer to a MEM_ROOT object for allocations
from pointer to a source TYPELIB structure
Return values
pointer to the new TYPELIB structure on successful copy
NULL otherwise
Definition at line 216 of file typelib.c.
 {
   TYPELIB *to;
   uint i;
   if (!from)
     return NULL;
   if (!(to= (TYPELIB*) alloc_root(root, sizeof(TYPELIB))))
     return NULL;
   if (!(to->type_names= (const char **)
         alloc_root(root, (sizeof(char *) + sizeof(int)) * (from->count + 1))))
     return NULL;
   to->type_lengths= (unsigned int *)(to->type_names + from->count + 1);
   to->count= from->count;
   if (from->name)
   {
     if (!(to->name= strdup_root(root, from->name)))
       return NULL;
   }
   else
     to->name= NULL;
   for (i= 0; i < from->count; i++)
   {
     if (!(to->type_names[i]= strmake_root(root, from->type_names[i],
                                           from->type_lengths[i])))
       return NULL;
     to->type_lengths[i]= from->type_lengths[i];
   }
   to->type_names[to->count]= NULL;
   to->type_lengths[to->count]= 0;
   return to;
 }
References alloc_root(), st_typelib::count, st_typelib::name, NULL, strdup_root(), strmake_root(), st_typelib::type_lengths, and st_typelib::type_names.
find_set_from_flags()
my_ulonglong find_set_from_flags (const TYPELIB * lib, uint default_name, my_ulonglong cur_set, my_ulonglong default_set, const char * str, uint length, char ** err_pos, uint * err_len)
Parse and apply a set of flag assingments
Parameters
lib Flag names
default_name Number of "default" in the typelib
cur_set Current set of flags (start from this state)
default_set Default set of flags (use this for assign-default keyword and flag=default assignments)
str String to be parsed
length Length of the string
err_pos OUT If error, set to point to start of wrong set string NULL on success
err_len OUT If error, set to the length of wrong set string
Parse a set of flag assignments, that is, parse a string in form:
param_name1=value1,param_name2=value2,...
where the names are specified in the TYPELIB, and each value can be either 'on','off', or 'default'. Setting the same name twice is not allowed.
Besides param=val assignments, we support the "default" keyword (keyword #default_name in the typelib). It can be used one time, if specified it causes us to build the new set over the default_set rather than cur_set value.
Note
it's not charset aware
Return values
Parsed set value if (*errpos == NULL), otherwise undefined
Definition at line 320 of file typelib.c.
 {
   const char *end= str + length;
   my_ulonglong flags_to_set= 0, flags_to_clear= 0, res;
   my_bool set_defaults= 0;
   *err_pos= 0;                  /* No error yet */
   if (str != end)
   {
     const char *start= str;
     for (;;)
     {
       const char *pos= start;
       uint flag_no, value;
       if (!(flag_no= parse_name(lib, &pos, end)))
         goto err;
       if (flag_no == default_name)
       {
         /* Using 'default' twice isn't allowed. */
         if (set_defaults)
           goto err;
         set_defaults= TRUE;
       }
       else
       {
         my_ulonglong bit=  (1ULL << (flag_no - 1));
         /* parse the '=on|off|default' */
         if ((flags_to_clear | flags_to_set) & bit ||
             pos >= end || *pos++ != '=' ||
             !(value= parse_name(&on_off_default_typelib, &pos, end)))
           goto err;
         if (value == 1) /* this is '=off' */
           flags_to_clear|= bit;
         else if (value == 2) /* this is '=on' */
           flags_to_set|= bit;
         else /* this is '=default'  */
         {
           if (default_set & bit)
             flags_to_set|= bit;
           else
             flags_to_clear|= bit;
         }
       }
       if (pos >= end)
         break;
       if (*pos++ != ',')
         goto err;
       start=pos;
       continue;
    err:
       *err_pos= (char*)start;
       *err_len= end - start;
       break;
     }
   }
   res= set_defaults? default_set : cur_set;
   res|= flags_to_set;
   res&= ~flags_to_clear;
   return res;
 }
References G3D::length(), on_off_default_typelib, parse_name(), pos(), and TRUE.
Referenced by setval().
find_type()
int find_type (char * x, const TYPELIB * typelib, uint full_name)
Search after a string in a list of strings. Endspace in x is not compared.
Parameters
x String to find
lib TYPELIB (struct of pointer to values + count)
full_name bitmap of what to do If & 1 accept only whole names If & 2 don't expand if half field If & 4 allow #number# as type If & 8 use ',' as string terminator
Note
If part, uniq field is found and full_name == 0 then x is expanded to full field.
Return values
-1 Too many matching values
0 No matching value
>0 Offset+1 in typelib for matched string
Definition at line 71 of file typelib.c.
 {
   int find,pos;
   int UNINIT_VAR(findpos);                       /* guarded by find */
   reg1 char * i;
   reg2 const char *j;
   DBUG_ENTER("find_type");
   DBUG_PRINT("enter",("x: '%s'  lib: 0x%lx", x, (long) typelib));
   if (!typelib->count)
   {
     DBUG_PRINT("exit",("no count"));
     DBUG_RETURN(0);
   }
   find=0;
   for (pos=0 ; (j=typelib->type_names[pos]) ; pos++)
   {
     for (i=x ;
         *i && (!(full_name & 8) || !is_field_separator(*i)) &&
         my_toupper(&my_charset_latin1,*i) ==
             my_toupper(&my_charset_latin1,*j) ; i++, j++) ;
     if (! *j)
     {
       while (*i == ' ')
     i++;                    /* skip_end_space */
       if (! *i || ((full_name & 8) && is_field_separator(*i)))
     DBUG_RETURN(pos+1);
     }
     if ((!*i && (!(full_name & 8) || !is_field_separator(*i))) &&
         (!*j || !(full_name & 1)))
     {
       find++;
       findpos=pos;
     }
   }
   if (find == 0 && (full_name & 4) && x[0] == '#' && strend(x)[-1] == '#' &&
       (findpos=atoi(x+1)-1) >= 0 && (uint) findpos < typelib->count)
     find=1;
   else if (find == 0 || ! x[0])
   {
     DBUG_PRINT("exit",("Couldn't find type"));
     DBUG_RETURN(0);
   }
   else if (find != 1 || (full_name & 1))
   {
     DBUG_PRINT("exit",("Too many possybilities"));
     DBUG_RETURN(-1);
   }
   if (!(full_name & 2))
     (void) strmov(x,typelib->type_names[findpos]);
   DBUG_RETURN(findpos+1);
 } /* find_type */
References st_typelib::count, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, find(), is_field_separator, my_charset_latin1, my_toupper, pos(), reg1, reg2, strend(), strmov(), st_typelib::type_names, UNINIT_VAR, and G3D::x.
Referenced by find_type_or_exit(), find_typeset(), handle_default_option(), mysql_read_default_options(), parse_name(), and setval().
find_type_or_exit()
int find_type_or_exit (const char * x, TYPELIB * typelib, const char * option)
Definition at line 25 of file typelib.c.
 {
   int res;
   const char **ptr;
   if ((res= find_type((char *) x, typelib, 2)) <= 0)
   {
     ptr= typelib->type_names;
     if (!*x)
       fprintf(stderr, "No option given to %s\n", option);
     else
       fprintf(stderr, "Unknown option to %s: %s\n", option, x);
     fprintf(stderr, "Alternatives are: '%s'", *ptr);
     while (*++ptr)
       fprintf(stderr, ",'%s'", *ptr);
     fprintf(stderr, "\n");
     exit(1);
   }
   return res;
 }
References find_type(), fprintf(), ptr(), st_typelib::type_names, and G3D::x.
find_typeset()
my_ulonglong find_typeset (char * x, TYPELIB * lib, int * err)
Create an integer value to represent the supplied comma-seperated string where each string in the TYPELIB denotes a bit position.
Parameters
x string to decompose
lib TYPELIB (struct of pointer to values + count)
err index (not char position) of string element which was not found or 0 if there was no error
Return values
a integer representation of the supplied string
Definition at line 172 of file typelib.c.
 {
   my_ulonglong result;
   int find;
   char *i;
   DBUG_ENTER("find_set");
   DBUG_PRINT("enter",("x: '%s'  lib: 0x%lx", x, (long) lib));
   if (!lib->count)
   {
     DBUG_PRINT("exit",("no count"));
     DBUG_RETURN(0);
   }
   result= 0;
   *err= 0;
   while (*x)
   {
     (*err)++;
     i= x;
     while (*x && !is_field_separator(*x))
       x++;
     if (x[0] && x[1])      /* skip separator if found */
       x++;
     if ((find= find_type(i, lib, 2 | 8) - 1) < 0)
       DBUG_RETURN(0);
     result|= (ULL(1) << find);
   }
   *err= 0;
   DBUG_RETURN(result);
 } /* find_set */
References st_typelib::count, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, find(), find_type(), is_field_separator, ULL, and G3D::x.
Referenced by setval().
get_type()
const char* get_type (TYPELIB * typelib, uint nr)
Get type
Note
first type is 0
Definition at line 151 of file typelib.c.
 {
   if (nr < (uint) typelib->count && typelib->type_names)
     return(typelib->type_names[nr]);
   return "?";
 }
References st_typelib::count, and st_typelib::type_names.
Referenced by make_type(), and my_print_variables().
make_type()
void make_type (char * to, unsigned int nr, TYPELIB * typelib)
Variable Documentation
sql_protocol_typelib
TYPELIB sql_protocol_typelib extern
Definition at line 1159 of file client.c.
Referenced by mysql_read_default_options().