Azerotcore-wotlk: src/common/Common.cpp File Reference
Common.cpp File Reference
#include "Common.h"
Functions
LocaleConstant GetLocaleByName (const std::string &name)
void CleanStringForMysqlQuery (std::string &str)
Variables
char const * localeNames [TOTAL_LOCALES]
Function Documentation
CleanStringForMysqlQuery()
void CleanStringForMysqlQuery (std::string & str)
Definition at line 44 of file Common.cpp.
 {
     std::string::size_type n = 0;
     while ((n = str.find('\\')) != str.npos) { str.erase(n, 1); }
     while ((n = str.find('"')) != str.npos) { str.erase(n, 1); }
     while ((n = str.find('\'')) != str.npos) { str.erase(n, 1); }
 }
Referenced by WorldSession::HandleMailTakeItem(), WorldSession::HandleSendMail(), and Map::LogEncounterFinished().
GetLocaleByName()
LocaleConstant GetLocaleByName (const std::string & name)
Definition at line 33 of file Common.cpp.
 {
     for (uint32 i = 0; i < TOTAL_LOCALES; ++i)
         if (name == localeNames[i])
         {
             return LocaleConstant(i);
         }
     return LOCALE_enUS;                                     // including enGB case
 }
References LOCALE_enUS, localeNames, and TOTAL_LOCALES.
Referenced by AuthSession::HandleLogonProof(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadCreatureLocales(), CreatureTextMgr::LoadCreatureTextLocales(), ObjectMgr::LoadGameObjectLocales(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestRequestItemsLocale(), AchievementGlobalMgr::LoadRewardLocales(), and AuthSession::LogonChallengeCallback().
Variable Documentation
localeNames
char const* localeNames[TOTAL_LOCALES]
Initial value:
=
{
    "enUS",
    "koKR",
    "frFR",
    "deDE",
    "zhCN",
    "zhTW",
    "esES",
    "esMX",
    "ruRU"
}
Definition at line 20 of file Common.cpp.
Referenced by World::DetectDBCLang(), GetLocaleByName(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTitleCommand(), server_commandscript::HandleServerDebugCommand(), and LoadDBC().