Azerotcore-wotlk: deps/mysqllite/mysys/my_pthread.c File Reference
my_pthread.c File Reference
#include "mysys_priv.h"
#include <signal.h>
#include <m_string.h>
#include <thr_alarm.h>
Macros
#define DONT_REMAP_PTHREAD_FUNCTIONS
#define SCHED_POLICY SCHED_OTHER
Functions
struct tm * localtime_r (const time_t *clock, struct tm *res)
struct tm * gmtime_r (const time_t *clock, struct tm *res)
void px_handle_sig (int sig)
void sigwait_setup (sigset_t *set)
int sigwait (sigset_t *setp, int *sigp)
int pthread_dummy (int ret)
Variables
uint thd_lib_detected = 0
int my_pthread_create_detached =1
mysql_mutex_t LOCK_localtime_r
static sigset_t sigwait_set
static sigset_t rev_sigwait_set
static sigset_t px_recd
Macro Definition Documentation
DONT_REMAP_PTHREAD_FUNCTIONS
#define DONT_REMAP_PTHREAD_FUNCTIONS
Definition at line 18 of file my_pthread.c.
SCHED_POLICY
#define SCHED_POLICY SCHED_OTHER
Definition at line 28 of file my_pthread.c.
Function Documentation
gmtime_r()
struct tm* gmtime_r (const time_t * clock, struct tm * res)
Definition at line 92 of file my_pthread.c.
 {
   struct tm *tmp;
   mysql_mutex_lock(&LOCK_localtime_r);
   tmp= gmtime(clock);
   *res= *tmp;
   mysql_mutex_unlock(&LOCK_localtime_r);
   return res;
 }
References gmtime(), LOCK_localtime_r, mysql_mutex_lock, and mysql_mutex_unlock.
localtime_r()
struct tm* localtime_r (const time_t * clock, struct tm * res)
Definition at line 75 of file my_pthread.c.
 {
   struct tm *tmp;
   mysql_mutex_lock(&LOCK_localtime_r);
   tmp=localtime(clock);
   *res= *tmp;
   mysql_mutex_unlock(&LOCK_localtime_r);
   return res;
 }
References localtime(), LOCK_localtime_r, mysql_mutex_lock, and mysql_mutex_unlock.
Referenced by Player::_LoadBrewOfTheMonth(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::AllowStart(), ByteBuffer::AppendPackedTime(), get_date(), World::GetNextTimeWithDayAndHour(), World::GetNextTimeWithMonthAndHour(), Log::GetTimestampStr(), LogMessage::getTimeStr(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), guild_commandscript::HandleGuildInfoCommand(), misc_commandscript::HandleMuteInfoHelper(), localtime(), AchievementCriteriaData::Meets(), my_init_time(), my_system_gmt_sec(), Weather::ReGenerate(), GameEventMgr::SetHolidayEventTime(), soap_dateTime2s(), TimeBreakdown(), TimeToHumanReadable(), TimeToTimestampStr(), go_bells::go_bellsAI::UpdateAI(), npc_elder_clearwater::npc_elder_clearwaterAI::UpdateAI(), and npc_riggle_bassbait::npc_riggle_bassbaitAI::UpdateAI().
pthread_dummy()
int pthread_dummy (int ret)
Definition at line 466 of file my_pthread.c.
 {
   return ret;
 }
References ret.
px_handle_sig()
void px_handle_sig (int sig)
Definition at line 126 of file my_pthread.c.
 {
   sigaddset(&px_recd, sig);
 }
References px_recd.
Referenced by sigwait_setup().
sigwait()
int sigwait (sigset_t * setp, int * sigp)
Definition at line 172 of file my_pthread.c.
 {
   if (memcmp(setp,&sigwait_set,sizeof(sigwait_set)))
     sigwait_setup(setp);            /* Init or change of set */
   for (;;)
   {
     /*
       This is a fast, not 100% portable implementation to find the signal.
       Because the handler is blocked there should be at most 1 bit set, but
       the specification on this is somewhat shady so we use a set instead a
       single variable.
       */
     ulong *ptr= (ulong*) &px_recd;
     ulong *end=ptr+sizeof(px_recd)/sizeof(ulong);
     for ( ; ptr != end ; ptr++)
     {
       if (*ptr)
       {
     ulong set= *ptr;
     int found= (int) ((char*) ptr - (char*) &px_recd)*8+1;
     while (!(set & 1))
     {
       found++;
       set>>=1;
     }
     *sigp=found;
     sigdelset(&px_recd,found);
     return 0;
       }
     }
     sigsuspend(&rev_sigwait_set);
   }
   return 0;
 }
References ptr(), px_recd, rev_sigwait_set, set(), sigwait_set, and sigwait_setup().
sigwait_setup()
void sigwait_setup (sigset_t * set)
Definition at line 132 of file my_pthread.c.
 {
   int i;
   struct sigaction sact,sact1;
   sigset_t unblock_mask;
   sact.sa_flags = 0;
   sact.sa_handler = px_handle_sig;
   memcpy(&sact.sa_mask, set, sizeof(*set));    /* handler isn't thread_safe */
   sigemptyset(&unblock_mask);
   pthread_sigmask(SIG_UNBLOCK,(sigset_t*) 0,&rev_sigwait_set);
   for (i = 1; i <= sizeof(sigwait_set)*8; i++)
   {
     if (sigismember(set,i))
     {
       sigdelset(&rev_sigwait_set,i);
       if (!sigismember(&sigwait_set,i))
     sigaction(i, &sact, (struct sigaction*) 0);
     }
     else
     {
       sigdelset(&px_recd,i);            /* Don't handle this */
       if (sigismember(&sigwait_set,i))
       {                     /* Remove the old handler */
     sigaddset(&unblock_mask,i);
     sigdelset(&rev_sigwait_set,i);
     sact1.sa_flags = 0;
     sact1.sa_handler = SIG_DFL;
     sigemptyset(&sact1.sa_mask);
     sigaction(i, &sact1, 0);
       }
     }
   }
   memcpy(&sigwait_set, set, sizeof(*set));
   pthread_sigmask(SIG_BLOCK,(sigset_t*) set,(sigset_t*) 0);
   pthread_sigmask(SIG_UNBLOCK,&unblock_mask,(sigset_t*) 0);
 }
References memcpy, px_handle_sig(), px_recd, rev_sigwait_set, set(), and sigwait_set.
Referenced by sigwait().
Variable Documentation
LOCK_localtime_r
mysql_mutex_t LOCK_localtime_r extern
Definition at line 35 of file my_thr_init.c.
Referenced by gmtime_r(), localtime_r(), my_thread_global_end(), and my_thread_global_init().
my_pthread_create_detached
int my_pthread_create_detached =1
Definition at line 52 of file my_pthread.c.
px_recd
sigset_t px_recd static
Definition at line 124 of file my_pthread.c.
Referenced by px_handle_sig(), sigwait(), and sigwait_setup().
rev_sigwait_set
sigset_t rev_sigwait_set static
Definition at line 124 of file my_pthread.c.
Referenced by sigwait(), and sigwait_setup().
sigwait_set
sigset_t sigwait_set static
Definition at line 124 of file my_pthread.c.
Referenced by sigwait(), and sigwait_setup().
thd_lib_detected
uint thd_lib_detected = 0
Definition at line 31 of file my_pthread.c.
Referenced by init_thr_alarm(), my_thread_global_init(), and process_alarm().