Azerotcore-wotlk: boss_kaelthas::boss_kaelthasAI Struct Reference
boss_kaelthas::boss_kaelthasAI Struct Reference
Public Member Functions
boss_kaelthasAI (Creature *creature)
void PrepareAdvisors ()
void SetData (uint32 type, uint32 data) override
void SetRoomState (GOState state)
void Reset () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void EnterCombat (Unit *who) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustDied (Unit *killer) override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 phase
EventMap events2
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 188 of file boss_kaelthas.cpp.
Constructor & Destructor Documentation
boss_kaelthasAI()
boss_kaelthas::boss_kaelthasAI::boss_kaelthasAI (Creature * creature) inline
Definition at line 190 of file boss_kaelthas.cpp.
 : BossAI(creature, DATA_KAELTHAS) { }
Member Function Documentation
AttackStart()
void boss_kaelthas::boss_kaelthasAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 248 of file boss_kaelthas.cpp.
         {
             if (phase == PHASE_FINAL && events.GetNextEventTime(EVENT_GRAVITY_LAPSE_END) == 0)
                 BossAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), EVENT_GRAVITY_LAPSE_END, and PHASE_FINAL.
Referenced by MovementInform(), and UpdateAI().
CheckEvadeIfOutOfCombatArea()
bool boss_kaelthas::boss_kaelthasAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
Definition at line 715 of file boss_kaelthas.cpp.
         {
             return me->GetHomePosition().GetExactDist2d(me) > 165.0f || !SelectTargetFromPlayerList(165.0f);
         }
References Creature::GetHomePosition(), ScriptedAI::me, and ScriptedAI::SelectTargetFromPlayerList().
EnterCombat()
void boss_kaelthas::boss_kaelthasAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 266 of file boss_kaelthas.cpp.
         {
             BossAI::EnterCombat(who);
         }
References BossAI::EnterCombat().
JustDied()
void boss_kaelthas::boss_kaelthasAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 322 of file boss_kaelthas.cpp.
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
             Talk(SAY_DEATH);
             BossAI::JustDied(killer);
         }
References BossAI::JustDied(), ScriptedAI::me, Object::RemoveFlag(), SAY_DEATH, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
JustSummoned()
void boss_kaelthas::boss_kaelthasAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 277 of file boss_kaelthas.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_NETHER_VAPOR)
                 summon->GetMotionMaster()->MoveRandom(20.0f);
         }
References Object::GetEntry(), Unit::GetMotionMaster(), MotionMaster::MoveRandom(), NPC_NETHER_VAPOR, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_kaelthas::boss_kaelthasAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 271 of file boss_kaelthas.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_kaelthas::boss_kaelthasAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 254 of file boss_kaelthas.cpp.
         {
             if (phase == PHASE_NONE && who->GetTypeId() == TYPEID_PLAYER && me->IsValidAttackTarget(who))
             {
                 phase = PHASE_SINGLE_ADVISOR;
                 me->SetInCombatWithZone();
                 Talk(SAY_INTRO);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE11, 23000);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE12, 30000);
             }
         }
References EVENT_PREFIGHT_PHASE11, EVENT_PREFIGHT_PHASE12, events2, Object::GetTypeId(), Unit::IsValidAttackTarget(), ScriptedAI::me, PHASE_NONE, PHASE_SINGLE_ADVISOR, SAY_INTRO, EventMap::ScheduleEvent(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_kaelthas::boss_kaelthasAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 330 of file boss_kaelthas.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (point == POINT_MIDDLE)
             {
                 events2.ScheduleEvent(EVENT_SCENE_1, 0);
                 events2.ScheduleEvent(EVENT_SCENE_2, 2500);
                 events2.ScheduleEvent(EVENT_SCENE_3, 4000);
                 events2.ScheduleEvent(EVENT_SCENE_4, 7000);
                 events2.ScheduleEvent(EVENT_SCENE_5, 10000);
                 events2.ScheduleEvent(EVENT_SCENE_6, 14000);
                 events2.ScheduleEvent(EVENT_SCENE_7, 17500);
                 events2.ScheduleEvent(EVENT_SCENE_8, 19000);
                 events2.ScheduleEvent(EVENT_SCENE_9, 22000); // two first lightnings + aura
                 events2.ScheduleEvent(EVENT_SCENE_10, 22800); // two
                 events2.ScheduleEvent(EVENT_SCENE_11, 23600); // two
                 events2.ScheduleEvent(EVENT_SCENE_12, 24500); // two
                 events2.ScheduleEvent(EVENT_SCENE_13, 24800); // two
                 events2.ScheduleEvent(EVENT_SCENE_14, 25300); // two
                 events2.ScheduleEvent(EVENT_SCENE_15, 32000); // full power
                 events2.ScheduleEvent(EVENT_SCENE_16, 36000); // remove lightnings + aura, move down
             }
             else if (point == POINT_START_LAST_PHASE)
             {
                 me->SetDisableGravity(false);
                 me->SetWalk(false);
                 me->RemoveAurasDueToSpell(SPELL_KAEL_FULL_POWER);
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                 events.SetTimer(60000);
                 events.ScheduleEvent(EVENT_SPELL_FIREBALL, 0);
                 events.ScheduleEvent(EVENT_SPELL_FLAMESTRIKE, 10000);
                 events.ScheduleEvent(EVENT_SPELL_SUMMON_PHOENIX, 20000);
                 events.ScheduleEvent(EVENT_SPELL_GRAVITY_LAPSE, 5000);
                 if (me->GetVictim())
                 {
                     me->SetTarget(me->GetVictim()->GetGUID());
                     AttackStart(me->GetVictim());
                 }
             }
         }
References AttackStart(), EVENT_SCENE_1, EVENT_SCENE_10, EVENT_SCENE_11, EVENT_SCENE_12, EVENT_SCENE_13, EVENT_SCENE_14, EVENT_SCENE_15, EVENT_SCENE_16, EVENT_SCENE_2, EVENT_SCENE_3, EVENT_SCENE_4, EVENT_SCENE_5, EVENT_SCENE_6, EVENT_SCENE_7, EVENT_SCENE_8, EVENT_SCENE_9, EVENT_SPELL_FIREBALL, EVENT_SPELL_FLAMESTRIKE, EVENT_SPELL_GRAVITY_LAPSE, EVENT_SPELL_SUMMON_PHOENIX, events2, Object::GetGUID(), Unit::GetVictim(), ScriptedAI::me, POINT_MIDDLE, POINT_MOTION_TYPE, POINT_START_LAST_PHASE, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Creature::SetReactState(), Creature::SetTarget(), Creature::SetWalk(), SPELL_KAEL_FULL_POWER, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
PrepareAdvisors()
void boss_kaelthas::boss_kaelthasAI::PrepareAdvisors () inline
Definition at line 195 of file boss_kaelthas.cpp.
         {
             for (uint8 i = DATA_KAEL_ADVISOR1; i <= DATA_KAEL_ADVISOR4; ++i)
                 if (Creature* advisor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(i)))
                 {
                     advisor->Respawn(true);
                     advisor->StopMovingOnCurrentPos();
                     advisor->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     advisor->SetReactState(REACT_PASSIVE);
                     summons.Summon(advisor);
                 }
         }
References DATA_KAEL_ADVISOR1, DATA_KAEL_ADVISOR4, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, REACT_PASSIVE, SummonList::Summon(), BossAI::summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by UpdateAI().
Reset()
void boss_kaelthas::boss_kaelthasAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 233 of file boss_kaelthas.cpp.
         {
             BossAI::Reset();
             events2.Reset();
             events2.ScheduleEvent(EVENT_GATHER_ADVISORS, 1000);
             phase = PHASE_NONE;
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_HOVER, true);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
             SetRoomState(GO_STATE_READY);
             me->SetDisableGravity(false);
             me->SetWalk(false);
         }
References Unit::ApplySpellImmune(), EVENT_GATHER_ADVISORS, events2, GO_STATE_READY, IMMUNITY_STATE, ScriptedAI::me, PHASE_NONE, Object::RemoveFlag(), EventMap::Reset(), BossAI::Reset(), EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Object::SetFlag(), SetRoomState(), Creature::SetWalk(), SPELL_AURA_HOVER, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
SetData()
void boss_kaelthas::boss_kaelthasAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 208 of file boss_kaelthas.cpp.
         {
             if (type == DATA_RESURRECT_CAST && data == DATA_RESURRECT_CAST)
             {
                 for (SummonList::const_iterator i = summons.begin(); i != summons.end(); ++i)
                     if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                         if (summon->GetSpawnId())
{
                             summon->SetReactState(REACT_PASSIVE);
                             summon->setDeathState(JUST_RESPAWNED);
                             summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         }
             }
         }
References SummonList::begin(), DATA_RESURRECT_CAST, SummonList::end(), ObjectAccessor::GetCreature(), JUST_RESPAWNED, ScriptedAI::me, REACT_PASSIVE, BossAI::summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
SetRoomState()
void boss_kaelthas::boss_kaelthasAI::SetRoomState (GOState state) inline
Definition at line 223 of file boss_kaelthas.cpp.
         {
             if (GameObject* window = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_BRIDGE_WINDOW)))
                 window->SetGoState(state);
             if (GameObject* window = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_KAEL_STATUE_RIGHT)))
                 window->SetGoState(state);
             if (GameObject* window = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_KAEL_STATUE_LEFT)))
                 window->SetGoState(state);
         }
References ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_BRIDGE_WINDOW, GO_KAEL_STATUE_LEFT, GO_KAEL_STATUE_RIGHT, BossAI::instance, and ScriptedAI::me.
Referenced by Reset(), and UpdateAI().
SummonedCreatureDies()
void boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 284 of file boss_kaelthas.cpp.
         {
             if (phase == PHASE_FINAL)
                 return;
             if (summon->GetSpawnId() && phase == PHASE_ALL_ADVISORS)
             {
                 for (SummonList::const_iterator i = summons.begin(); i != summons.end(); ++i)
                     if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                         if (summon->GetSpawnId() && summon->IsAlive())
                             return;
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE71, 2000);
                 return;
             }
             if (summon->GetEntry() == NPC_THALADRED)
             {
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE21, 2000);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE22, 14500);
             }
             else if (summon->GetEntry() == NPC_LORD_SANGUINAR)
             {
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE31, 2000);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE32, 9000);
             }
             else if (summon->GetEntry() == NPC_CAPERNIAN)
             {
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE41, 2000);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE42, 10400);
             }
             else if (summon->GetEntry() == NPC_TELONICUS)
             {
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE51, 3000);
                 events2.ScheduleEvent(EVENT_PREFIGHT_PHASE52, 9000);
             }
         }
References SummonList::begin(), SummonList::end(), EVENT_PREFIGHT_PHASE21, EVENT_PREFIGHT_PHASE22, EVENT_PREFIGHT_PHASE31, EVENT_PREFIGHT_PHASE32, EVENT_PREFIGHT_PHASE41, EVENT_PREFIGHT_PHASE42, EVENT_PREFIGHT_PHASE51, EVENT_PREFIGHT_PHASE52, EVENT_PREFIGHT_PHASE71, events2, ObjectAccessor::GetCreature(), Object::GetEntry(), Creature::GetSpawnId(), Unit::IsAlive(), ScriptedAI::me, NPC_CAPERNIAN, NPC_LORD_SANGUINAR, NPC_TELONICUS, NPC_THALADRED, PHASE_ALL_ADVISORS, PHASE_FINAL, EventMap::ScheduleEvent(), and BossAI::summons.
UpdateAI()
void boss_kaelthas::boss_kaelthasAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 374 of file boss_kaelthas.cpp.
         {
             if (EnterEvadeIfOutOfCombatArea())
                 return;
             events2.Update(diff);
             switch (events2.ExecuteEvent())
             {
                 case EVENT_GATHER_ADVISORS:
                     PrepareAdvisors();
                     break;
                 case EVENT_PREFIGHT_PHASE11:
                     Talk(SAY_INTRO_THALADRED);
                     break;
                 case EVENT_PREFIGHT_PHASE12:
                     if (Creature* advisor = summons.GetCreatureWithEntry(NPC_THALADRED))
                     {
                         advisor->SetReactState(REACT_AGGRESSIVE);
                         advisor->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                             advisor->AI()->AttackStart(target);
                         advisor->SetInCombatWithZone();
                         advisor->AI()->Talk(SAY_THALADRED_AGGRO);
                     }
                     break;
                 case EVENT_PREFIGHT_PHASE21:
                     Talk(SAY_INTRO_SANGUINAR);
                     break;
                 case EVENT_PREFIGHT_PHASE22:
                     if (Creature* advisor = summons.GetCreatureWithEntry(NPC_LORD_SANGUINAR))
                     {
                         advisor->SetReactState(REACT_AGGRESSIVE);
                         advisor->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                             advisor->AI()->AttackStart(target);
                         advisor->SetInCombatWithZone();
                         advisor->AI()->Talk(SAY_SANGUINAR_AGGRO);
                     }
                     break;
                 case EVENT_PREFIGHT_PHASE31:
                     Talk(SAY_INTRO_CAPERNIAN);
                     break;
                 case EVENT_PREFIGHT_PHASE32:
                     if (Creature* advisor = summons.GetCreatureWithEntry(NPC_CAPERNIAN))
                     {
                         advisor->SetReactState(REACT_AGGRESSIVE);
                         advisor->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                             advisor->AI()->AttackStart(target);
                         advisor->SetInCombatWithZone();
                         advisor->AI()->Talk(SAY_CAPERNIAN_AGGRO);
                     }
                     break;
                 case EVENT_PREFIGHT_PHASE41:
                     Talk(SAY_INTRO_TELONICUS);
                     break;
                 case EVENT_PREFIGHT_PHASE42:
                     if (Creature* advisor = summons.GetCreatureWithEntry(NPC_TELONICUS))
                     {
                         advisor->SetReactState(REACT_AGGRESSIVE);
                         advisor->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                             advisor->AI()->AttackStart(target);
                         advisor->SetInCombatWithZone();
                         advisor->AI()->Talk(SAY_TELONICUS_AGGRO);
                     }
                     break;
                 case EVENT_PREFIGHT_PHASE51:
                     Talk(SAY_PHASE2_WEAPON);
                     me->CastSpell(me, SPELL_SUMMON_WEAPONS, false);
                     phase = PHASE_WEAPONS;
                     break;
                 case EVENT_PREFIGHT_PHASE52:
                     for (SummonList::const_iterator i = summons.begin(); i != summons.end(); ++i)
                     {
                         if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                             if (!summon->GetSpawnId())
{
                                 summon->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                                 summon->SetInCombatWithZone();
                                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                                     summon->AI()->AttackStart(target);
                             }
                     }
                     events2.ScheduleEvent(EVENT_PREFIGHT_PHASE61, 2 * MINUTE * IN_MILLISECONDS);
                     events2.ScheduleEvent(EVENT_PREFIGHT_PHASE62, 2 * MINUTE * IN_MILLISECONDS + 6000);
                     events2.ScheduleEvent(EVENT_PREFIGHT_PHASE63, 2 * MINUTE * IN_MILLISECONDS + 12000);
                     break;
                 case EVENT_PREFIGHT_PHASE61:
                     phase = PHASE_ALL_ADVISORS;
                     Talk(SAY_PHASE3_ADVANCE);
                     break;
                 case EVENT_PREFIGHT_PHASE62:
                     me->CastSpell(me, SPELL_RESURRECTION, false);
                     break;
                 case EVENT_PREFIGHT_PHASE63:
                     for (SummonList::const_iterator i = summons.begin(); i != summons.end(); ++i)
                         if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                             if (summon->GetSpawnId())
{
                                 summon->SetReactState(REACT_AGGRESSIVE);
                                 summon->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                                 summon->SetInCombatWithZone();
                                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                                     summon->AI()->AttackStart(target);
                             }
                     events2.ScheduleEvent(EVENT_PREFIGHT_PHASE71, 3 * MINUTE * IN_MILLISECONDS);
                     break;
                 case EVENT_PREFIGHT_PHASE71:
                     events2.CancelEvent(EVENT_PREFIGHT_PHASE71);
                     Talk(SAY_PHASE4_INTRO2);
                     phase = PHASE_FINAL;
                     DoResetThreat();
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         AttackStart(target);
                     events2.Reset();
                     events.Reset();
                     events.ScheduleEvent(EVENT_SPELL_FIREBALL, 1000);
                     events.ScheduleEvent(EVENT_SPELL_FLAMESTRIKE, 15000);
                     events.ScheduleEvent(EVENT_SPELL_SUMMON_PHOENIX, 30000);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_1, 20000);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_2, 40000);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_3, 60000);
                     events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_SCENE_1:
                     me->SetTarget();
                     me->SetFacingTo(M_PI);
                     me->SetWalk(true);
                     Talk(SAY_PHASE5_NUTS);
                     break;
                 case EVENT_SCENE_2:
                     me->SetTarget();
                     me->CastSpell(me, SPELL_KAEL_EXPLODES1, true);
                     me->CastSpell(me, SPELL_KAEL_GAINING_POWER, false);
                     me->SetDisableGravity(true);
                     break;
                 case EVENT_SCENE_3:
                     me->SetTarget();
                     for (uint8 i = 0; i < 2; ++i)
                         if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, triggersPos[i], TEMPSUMMON_TIMED_DESPAWN, 60000))
                             trigger->CastSpell(me, SPELL_NETHERBEAM1 + i, false);
                     me->GetMotionMaster()->MovePoint(POINT_AIR, me->GetPositionX(), me->GetPositionY(), 76.0f, false, true);
                     me->CastSpell(me, SPELL_GROW, true);
                     break;
                 case EVENT_SCENE_4:
                     me->SetTarget();
                     me->CastSpell(me, SPELL_GROW, true);
                     me->CastSpell(me, SPELL_KAEL_EXPLODES2, true);
                     me->CastSpell(me, SPELL_NETHERBEAM_AURA1, true);
                     for (uint8 i = 0; i < 2; ++i)
                         if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, triggersPos[i + 2], TEMPSUMMON_TIMED_DESPAWN, 60000))
                             trigger->CastSpell(me, SPELL_NETHERBEAM1 + i, false);
                     break;
                 case EVENT_SCENE_5:
                     me->SetTarget();
                     me->CastSpell(me, SPELL_GROW, true);
                     me->CastSpell(me, SPELL_KAEL_EXPLODES3, true);
                     me->CastSpell(me, SPELL_NETHERBEAM_AURA2, true);
                     for (uint8 i = 0; i < 2; ++i)
                         if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, triggersPos[i + 4], TEMPSUMMON_TIMED_DESPAWN, 60000))
                             trigger->CastSpell(me, SPELL_NETHERBEAM1 + i, false);
                     break;
                 case EVENT_SCENE_6:
                     me->CastSpell(me, SPELL_GROW, true);
                     me->CastSpell(me, SPELL_KAEL_EXPLODES4, true);
                     me->CastSpell(me, SPELL_NETHERBEAM_AURA3, true);
                     break;
                 case EVENT_SCENE_7:
                     SetRoomState(GO_STATE_ACTIVE);
                     me->SetUnitMovementFlags(MOVEMENTFLAG_HOVER | MOVEMENTFLAG_WALKING | MOVEMENTFLAG_DISABLE_GRAVITY);
                     me->SendMovementFlagUpdate();
                     break;
                 case EVENT_SCENE_8:
                     summons.DespawnEntry(WORLD_TRIGGER);
                     me->RemoveAurasDueToSpell(SPELL_NETHERBEAM_AURA1);
                     me->RemoveAurasDueToSpell(SPELL_NETHERBEAM_AURA2);
                     me->RemoveAurasDueToSpell(SPELL_NETHERBEAM_AURA3);
                     me->CastSpell(me, SPELL_KAEL_EXPLODES5, true);
                     me->CastSpell(me, SPELL_FLOATING_DROWNED, false);
                     //me->CastSpell(me, SPELL_KEAL_STUNNED, true);
                     break;
                 case EVENT_SCENE_9:
                     me->CastSpell(me, 52241, true); // WRONG VISUAL, ZOMG!
                     me->CastSpell(me, 34807, true);
                     me->SummonCreature(NPC_WORLD_TRIGGER, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000);
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() + 5, me->GetPositionY(), me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM1, true);
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() - 5, me->GetPositionY(), me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM2, true);
                     break;
                 case EVENT_SCENE_10:
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() - 5, me->GetPositionY() - 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM3, true);
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() + 5, me->GetPositionY() + 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM1, true);
                     break;
                 case EVENT_SCENE_11:
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX(), me->GetPositionY() + 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM2, true);
                     break;
                 case EVENT_SCENE_12:
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX(), me->GetPositionY() - 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM3, true);
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() + 5, me->GetPositionY() - 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM1, true);
                     break;
                 case EVENT_SCENE_13:
                     if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX() - 5, me->GetPositionY() + 5, me->GetPositionZ() + 15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                         trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM2, true);
                     break;
                 case EVENT_SCENE_14:
                     //if (Creature* trigger = me->SummonCreature(WORLD_TRIGGER, me->GetPositionX()-5, me->GetPositionY()+5, me->GetPositionZ()+15.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000))
                     //  trigger->CastSpell(me, SPELL_PURE_NETHER_BEAM3, true);
                     break;
                 case EVENT_SCENE_15:
                     me->RemoveAurasDueToSpell(SPELL_FLOATING_DROWNED);
                     me->RemoveAurasDueToSpell(SPELL_KEAL_STUNNED);
                     me->CastSpell(me, SPELL_KAEL_FULL_POWER, false);
                     me->CastSpell(me, 36709, true);
                     me->CastSpell(me, 36201, true);
                     me->CastSpell(me, 36290, true);
                     me->CastSpell(me, 36291, true);
                     me->SetUnitMovementFlags(MOVEMENTFLAG_DISABLE_GRAVITY | MOVEMENTFLAG_WALKING);
                     me->SendMovementFlagUpdate();
                     break;
                 case EVENT_SCENE_16:
                     summons.DespawnEntry(WORLD_TRIGGER);
                     me->RemoveAurasDueToSpell(52241); // WRONG VISUAL, ZOMG!
                     me->GetMotionMaster()->MovePoint(POINT_START_LAST_PHASE, me->GetHomePosition(), false, true);
                     break;
             }
             if (!events2.Empty())
                 return;
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_SEQ_1:
                     events.ScheduleEvent(EVENT_SPELL_MIND_CONTROL, 0);
                     events.ScheduleEvent(EVENT_SPELL_ARCANE_DISRUPTION, 3000);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_1, 50000);
                     break;
                 case EVENT_SPELL_SEQ_2:
                     events.ScheduleEvent(EVENT_SPELL_MIND_CONTROL, 3000);
                     events.ScheduleEvent(EVENT_SPELL_ARCANE_DISRUPTION, 6000);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_2, 50000);
                     break;
                 case EVENT_SPELL_SEQ_3:
                     Talk(SAY_PYROBLAST);
                     me->CastSpell(me, SPELL_SHOCK_BARRIER, false);
                     events.ScheduleEvent(EVENT_SPELL_SEQ_3, 50000);
                     events.DelayEvents(10000);
                     events.ScheduleEvent(EVENT_SPELL_PYROBLAST, 0);
                     events.ScheduleEvent(EVENT_SPELL_PYROBLAST, 4000);
                     events.ScheduleEvent(EVENT_SPELL_PYROBLAST, 8000);
                     break;
                 case EVENT_SPELL_SHOCK_BARRIER:
                     me->CastSpell(me, SPELL_SHOCK_BARRIER, false);
                     break;
                 case EVENT_SPELL_FIREBALL:
                     me->CastSpell(me->GetVictim(), SPELL_FIREBALL, false);
                     events.ScheduleEvent(EVENT_SPELL_FIREBALL, roll_chance_i(70) ? 2000 : 4000);
                     break;
                 case EVENT_SPELL_PYROBLAST:
                     me->CastSpell(me->GetVictim(), SPELL_PYROBLAST, false);
                     break;
                 case EVENT_SPELL_FLAMESTRIKE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_FLAME_STRIKE, false);
                     events.ScheduleEvent(EVENT_SPELL_FLAMESTRIKE, 20000);
                     break;
                 case EVENT_SPELL_ARCANE_DISRUPTION:
                     me->CastSpell(me, SPELL_ARCANE_DISRUPTION, false);
                     break;
                 case EVENT_SPELL_MIND_CONTROL:
                     if (roll_chance_i(50))
                         Talk(SAY_MINDCONTROL);
                     me->CastCustomSpell(SPELL_MIND_CONTROL, SPELLVALUE_MAX_TARGETS, 3, me, false);
                     break;
                 case EVENT_SPELL_SUMMON_PHOENIX:
                     Talk(SAY_SUMMON_PHOENIX);
                     me->CastSpell(me, SPELL_PHOENIX, false);
                     events.ScheduleEvent(EVENT_SPELL_SUMMON_PHOENIX, 40000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(51))
                     {
                         events.Reset();
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         me->SetReactState(REACT_PASSIVE);
                         me->GetMotionMaster()->MovePoint(POINT_MIDDLE, me->GetHomePosition(), true, true);
                         me->ClearUnitState(UNIT_STATE_MELEE_ATTACKING);
                         me->SendMeleeAttackStop();
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_SPELL_GRAVITY_LAPSE:
                     events.DelayEvents(30000);
                     me->setAttackTimer(BASE_ATTACK, 30000);
                     events.ScheduleEvent(EVENT_SPELL_GRAVITY_LAPSE, 90000);
                     events.ScheduleEvent(EVENT_GRAVITY_LAPSE_END, 32000);
                     events.ScheduleEvent(EVENT_SPELL_SHOCK_BARRIER, 20000);
                     events.ScheduleEvent(EVENT_SPELL_SHOCK_BARRIER, 10000);
                     events.ScheduleEvent(EVENT_SPELL_NETHER_BEAM, 4000);
                     events.ScheduleEvent(EVENT_SPELL_NETHER_VAPOR, 0);
                     me->CastSpell(me, SPELL_SHOCK_BARRIER, false);
                     me->CastSpell(me, SPELL_GRAVITY_LAPSE, false);
                     me->SetTarget();
                     me->GetMotionMaster()->Clear();
                     me->StopMoving();
                     Talk(SAY_GRAVITYLAPSE);
                     break;
                 case EVENT_SPELL_NETHER_VAPOR:
                     me->CastSpell(me, SPELL_SUMMON_NETHER_VAPOR, false);
                     break;
                 case EVENT_SPELL_NETHER_BEAM:
                     me->CastSpell(me, SPELL_NETHER_BEAM, false);
                     events.ScheduleEvent(EVENT_SPELL_NETHER_BEAM, 4000);
                     break;
                 case EVENT_GRAVITY_LAPSE_END:
                     summons.DespawnEntry(NPC_NETHER_VAPOR);
                     events.CancelEvent(EVENT_SPELL_NETHER_BEAM);
                     me->SetTarget(me->GetVictim()->GetGUID());
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     break;
             }
             DoMeleeAttackIfReady();
         }
References AttackStart(), BASE_ATTACK, SummonList::begin(), EventMap::CancelEvent(), Unit::CastCustomSpell(), Unit::CastSpell(), MotionMaster::Clear(), Unit::ClearUnitState(), SummonList::DespawnEntry(), diff(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), EventMap::Empty(), SummonList::end(), ScriptedAI::EnterEvadeIfOutOfCombatArea(), EVENT_CHECK_HEALTH, EVENT_GATHER_ADVISORS, EVENT_GRAVITY_LAPSE_END, EVENT_PREFIGHT_PHASE11, EVENT_PREFIGHT_PHASE12, EVENT_PREFIGHT_PHASE21, EVENT_PREFIGHT_PHASE22, EVENT_PREFIGHT_PHASE31, EVENT_PREFIGHT_PHASE32, EVENT_PREFIGHT_PHASE41, EVENT_PREFIGHT_PHASE42, EVENT_PREFIGHT_PHASE51, EVENT_PREFIGHT_PHASE52, EVENT_PREFIGHT_PHASE61, EVENT_PREFIGHT_PHASE62, EVENT_PREFIGHT_PHASE63, EVENT_PREFIGHT_PHASE71, EVENT_SCENE_1, EVENT_SCENE_10, EVENT_SCENE_11, EVENT_SCENE_12, EVENT_SCENE_13, EVENT_SCENE_14, EVENT_SCENE_15, EVENT_SCENE_16, EVENT_SCENE_2, EVENT_SCENE_3, EVENT_SCENE_4, EVENT_SCENE_5, EVENT_SCENE_6, EVENT_SCENE_7, EVENT_SCENE_8, EVENT_SCENE_9, EVENT_SPELL_ARCANE_DISRUPTION, EVENT_SPELL_FIREBALL, EVENT_SPELL_FLAMESTRIKE, EVENT_SPELL_GRAVITY_LAPSE, EVENT_SPELL_MIND_CONTROL, EVENT_SPELL_NETHER_BEAM, EVENT_SPELL_NETHER_VAPOR, EVENT_SPELL_PYROBLAST, EVENT_SPELL_SEQ_1, EVENT_SPELL_SEQ_2, EVENT_SPELL_SEQ_3, EVENT_SPELL_SHOCK_BARRIER, EVENT_SPELL_SUMMON_PHOENIX, events2, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), Object::GetGUID(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), GO_STATE_ACTIVE, Unit::HasUnitState(), Unit::HealthBelowPct(), IN_MILLISECONDS, M_PI, ScriptedAI::me, MINUTE, MotionMaster::MoveChase(), MOVEMENTFLAG_DISABLE_GRAVITY, MOVEMENTFLAG_HOVER, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NPC_CAPERNIAN, NPC_LORD_SANGUINAR, NPC_NETHER_VAPOR, NPC_TELONICUS, NPC_THALADRED, NPC_WORLD_TRIGGER, PHASE_ALL_ADVISORS, PHASE_FINAL, PHASE_WEAPONS, POINT_AIR, POINT_MIDDLE, POINT_START_LAST_PHASE, PrepareAdvisors(), REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), EventMap::Reset(), roll_chance_i(), SAY_CAPERNIAN_AGGRO, SAY_GRAVITYLAPSE, SAY_INTRO_CAPERNIAN, SAY_INTRO_SANGUINAR, SAY_INTRO_TELONICUS, SAY_INTRO_THALADRED, SAY_MINDCONTROL, SAY_PHASE2_WEAPON, SAY_PHASE3_ADVANCE, SAY_PHASE4_INTRO2, SAY_PHASE5_NUTS, SAY_PYROBLAST, SAY_SANGUINAR_AGGRO, SAY_SUMMON_PHOENIX, SAY_TELONICUS_AGGRO, SAY_THALADRED_AGGRO, EventMap::ScheduleEvent(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Unit::setAttackTimer(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Object::SetFlag(), Creature::SetReactState(), SetRoomState(), Creature::SetTarget(), Unit::SetUnitMovementFlags(), Creature::SetWalk(), SPELL_ARCANE_DISRUPTION, SPELL_FIREBALL, SPELL_FLAME_STRIKE, SPELL_FLOATING_DROWNED, SPELL_GRAVITY_LAPSE, SPELL_GROW, SPELL_KAEL_EXPLODES1, SPELL_KAEL_EXPLODES2, SPELL_KAEL_EXPLODES3, SPELL_KAEL_EXPLODES4, SPELL_KAEL_EXPLODES5, SPELL_KAEL_FULL_POWER, SPELL_KAEL_GAINING_POWER, SPELL_KEAL_STUNNED, SPELL_MIND_CONTROL, SPELL_NETHER_BEAM, SPELL_NETHERBEAM1, SPELL_NETHERBEAM_AURA1, SPELL_NETHERBEAM_AURA2, SPELL_NETHERBEAM_AURA3, SPELL_PHOENIX, SPELL_PURE_NETHER_BEAM1, SPELL_PURE_NETHER_BEAM2, SPELL_PURE_NETHER_BEAM3, SPELL_PYROBLAST, SPELL_RESURRECTION, SPELL_SHOCK_BARRIER, SPELL_SUMMON_NETHER_VAPOR, SPELL_SUMMON_WEAPONS, SPELLVALUE_MAX_TARGETS, Unit::StopMoving(), WorldObject::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, triggersPos, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, UNIT_STATE_MELEE_ATTACKING, EventMap::Update(), CreatureAI::UpdateVictim(), and WORLD_TRIGGER.
Member Data Documentation
events2
EventMap boss_kaelthas::boss_kaelthasAI::events2
Definition at line 193 of file boss_kaelthas.cpp.
Referenced by MoveInLineOfSight(), MovementInform(), Reset(), SummonedCreatureDies(), and UpdateAI().
phase
uint8 boss_kaelthas::boss_kaelthasAI::phase
Definition at line 192 of file boss_kaelthas.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp