Azerotcore-wotlk: list_commandscript Class Reference
list_commandscript Class Reference
Public Member Functions
list_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleListCreatureCommand (ChatHandler *handler, Variant< Hyperlink< creature_entry >, uint32 > creatureId, Optional< uint32 > countArg)
static bool HandleListItemCommand (ChatHandler *handler, Variant< Hyperlink< item >, uint32 > itemArg, Optional< uint32 > countArg)
static bool HandleListObjectCommand (ChatHandler *handler, Variant< Hyperlink< gameobject_entry >, uint32 > gameObjectId, Optional< uint32 > countArg)
static bool HandleListAllAurasCommand (ChatHandler *handler)
static bool HandleListAurasByIdCommand (ChatHandler *handler, uint32 spellId)
static bool HandleListAurasByNameCommand (ChatHandler *handler, WTail namePart)
static bool ListAurasCommand (ChatHandler *handler, Optional< uint32 > spellId, std::wstring namePart)
static bool ShouldListAura (SpellInfo const *spellInfo, Optional< uint32 > spellId, std::wstring namePart, uint8 locale)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 42 of file cs_list.cpp.
Constructor & Destructor Documentation
list_commandscript()
list_commandscript::list_commandscript () inline
Definition at line 45 of file cs_list.cpp.
 : CommandScript("list_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable list_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 47 of file cs_list.cpp.
     {
         static ChatCommandTable listAurasCommandTable =
         {
             { "",         HandleListAllAurasCommand,    SEC_MODERATOR, Console::No  },
             { "id",       HandleListAurasByIdCommand,   SEC_MODERATOR, Console::No  },
             { "name",     HandleListAurasByNameCommand, SEC_MODERATOR, Console::No  },
         };
         static ChatCommandTable listCommandTable =
         {
             { "creature", HandleListCreatureCommand,    SEC_MODERATOR, Console::Yes },
             { "item",     HandleListItemCommand,        SEC_MODERATOR, Console::Yes },
             { "object",   HandleListObjectCommand,      SEC_MODERATOR, Console::Yes },
             { "auras",    listAurasCommandTable },
         };
         static ChatCommandTable commandTable =
         {
             { "list", listCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_MODERATOR, and Acore::ChatCommands::Yes.
HandleListAllAurasCommand()
static bool list_commandscript::HandleListAllAurasCommand (ChatHandler * handler) inline static
Definition at line 443 of file cs_list.cpp.
     {
         return ListAurasCommand(handler, {}, {});
     }
HandleListAurasByIdCommand()
static bool list_commandscript::HandleListAurasByIdCommand (ChatHandler * handler, uint32 spellId) inline static
Definition at line 448 of file cs_list.cpp.
     {
         return ListAurasCommand(handler, spellId, {});
     }
HandleListAurasByNameCommand()
static bool list_commandscript::HandleListAurasByNameCommand (ChatHandler * handler, WTail namePart) inline static
Definition at line 453 of file cs_list.cpp.
     {
         return ListAurasCommand(handler, {}, namePart);
     }
HandleListCreatureCommand()
static bool list_commandscript::HandleListCreatureCommand (ChatHandler * handler, Variant< Hyperlink< creature_entry >, uint32 > creatureId, Optional< uint32 > countArg) inline static
Definition at line 70 of file cs_list.cpp.
     {
         CreatureTemplate const* cInfo = sObjectMgr->GetCreatureTemplate(creatureId);
         if (!cInfo)
         {
             handler->PSendSysMessage(LANG_COMMAND_INVALIDCREATUREID, uint32(creatureId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 count = countArg.value_or(10);
         if (count == 0)
             return false;
         QueryResult result;
         uint32 creatureCount = 0;
         result = WorldDatabase.PQuery("SELECT COUNT(guid) FROM creature WHERE id='%u'", uint32(creatureId));
         if (result)
             creatureCount = (*result)[0].GetUInt64();
         if (handler->GetSession())
         {
             Player* player = handler->GetSession()->GetPlayer();
             result = WorldDatabase.PQuery("SELECT guid, position_x, position_y, position_z, map, (POW(position_x - '%f', 2) + POW(position_y - '%f', 2) + POW(position_z - '%f', 2)) AS order_ FROM creature WHERE id = '%u' ORDER BY order_ ASC LIMIT %u",
                                           player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), uint32(creatureId), count);
         }
         else
             result = WorldDatabase.PQuery("SELECT guid, position_x, position_y, position_z, map FROM creature WHERE id = '%u' LIMIT %u",
                                           uint32(creatureId), count);
         if (result)
         {
             do
             {
                 Field* fields               = result->Fetch();
                 ObjectGuid::LowType guid    = fields[0].GetUInt32();
                 float x                     = fields[1].GetFloat();
                 float y                     = fields[2].GetFloat();
                 float z                     = fields[3].GetFloat();
                 uint16 mapId                = fields[4].GetUInt16();
                 bool liveFound = false;
                 // Get map (only support base map from console)
                 Map* thisMap;
                 if (handler->GetSession())
                     thisMap = handler->GetSession()->GetPlayer()->GetMap();
                 else
                     thisMap = sMapMgr->FindBaseNonInstanceMap(mapId);
                 // If map found, try to find active version of this creature
                 if (thisMap)
                 {
                     auto const creBounds = thisMap->GetCreatureBySpawnIdStore().equal_range(guid);
                     if (creBounds.first != creBounds.second)
                     {
                         for (std::unordered_multimap<uint32, Creature*>::const_iterator itr = creBounds.first; itr != creBounds.second;)
{
                             if (handler->GetSession())
                                 handler->PSendSysMessage(LANG_CREATURE_LIST_CHAT, guid, guid, cInfo->Name.c_str(), x, y, z, mapId, itr->second->GetGUID().ToString().c_str(), itr->second->IsAlive() ? "*" : " ");
                             else
                                 handler->PSendSysMessage(LANG_CREATURE_LIST_CONSOLE, guid, cInfo->Name.c_str(), x, y, z, mapId, itr->second->GetGUID().ToString().c_str(), itr->second->IsAlive() ? "*" : " ");
                             ++itr;
                         }
                         liveFound = true;
                     }
                 }
                 if (!liveFound)
                 {
                     if (handler->GetSession())
                         handler->PSendSysMessage(LANG_CREATURE_LIST_CHAT, guid, guid, cInfo->Name.c_str(), x, y, z, mapId, "", "");
                     else
                         handler->PSendSysMessage(LANG_CREATURE_LIST_CONSOLE, guid, cInfo->Name.c_str(), x, y, z, mapId, "", "");
                 }
             }
             while (result->NextRow());
         }
         handler->PSendSysMessage(LANG_COMMAND_LISTCREATUREMESSAGE, uint32(creatureId), creatureCount);
         return true;
     }
References Map::GetCreatureBySpawnIdStore(), Field::GetFloat(), WorldObject::GetMap(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_INVALIDCREATUREID, LANG_COMMAND_LISTCREATUREMESSAGE, LANG_CREATURE_LIST_CHAT, LANG_CREATURE_LIST_CONSOLE, CreatureTemplate::Name, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sMapMgr, sObjectMgr, and WorldDatabase.
HandleListItemCommand()
static bool list_commandscript::HandleListItemCommand (ChatHandler * handler, Variant< Hyperlink< item >, uint32 > itemArg, Optional< uint32 > countArg) inline static
Definition at line 155 of file cs_list.cpp.
     {
         uint32 itemId = 0;
         uint32 count = countArg.value_or(10);
         if (itemArg.holds_alternative<Hyperlink<item>>())
         {
             itemId = itemArg.get<Hyperlink<item>>()->Item->ItemId;
         }
         else
         {
             itemId = itemArg.get<uint32>();
         }
         if (!count || !itemId)
             return false;
         PreparedQueryResult result;
         // inventory case
         uint32 inventoryCount = 0;
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_INVENTORY_COUNT_ITEM);
         stmt->setUInt32(0, itemId);
         result = CharacterDatabase.Query(stmt);
         if (result)
             inventoryCount = (*result)[0].GetUInt64();
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY);
         stmt->setUInt32(0, itemId);
         stmt->setUInt32(1, count);
         result = CharacterDatabase.Query(stmt);
         if (result)
         {
             do
             {
                 Field* fields           = result->Fetch();
                 uint32 itemGuid         = fields[0].GetUInt32();
                 uint32 itemBag          = fields[1].GetUInt32();
                 uint8 itemSlot          = fields[2].GetUInt8();
                 uint32 ownerGuid        = fields[3].GetUInt32();
                 uint32 ownerAccountId   = fields[4].GetUInt32();
                 std::string ownerName   = fields[5].GetString();
                 char const* itemPos = nullptr;
                 if (Player::IsEquipmentPos(itemBag, itemSlot))
                     itemPos = "[equipped]";
                 else if (Player::IsInventoryPos(itemBag, itemSlot))
                     itemPos = "[in inventory]";
                 else if (Player::IsBankPos(itemBag, itemSlot))
                     itemPos = "[in bank]";
                 else
                     itemPos = "";
                 handler->PSendSysMessage(LANG_ITEMLIST_SLOT, itemGuid, ownerName.c_str(), ownerGuid, ownerAccountId, itemPos);
             }
             while (result->NextRow());
             uint32 resultCount = uint32(result->GetRowCount());
             if (count > resultCount)
                 count -= resultCount;
             else
                 count = 0;
         }
         // mail case
         uint32 mailCount = 0;
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_MAIL_COUNT_ITEM);
         stmt->setUInt32(0, itemId);
         result = CharacterDatabase.Query(stmt);
         if (result)
             mailCount = (*result)[0].GetUInt64();
         if (count > 0)
         {
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_MAIL_ITEMS_BY_ENTRY);
             stmt->setUInt32(0, itemId);
             stmt->setUInt32(1, count);
             result = CharacterDatabase.Query(stmt);
         }
         else
             result = PreparedQueryResult(nullptr);
         if (result)
         {
             do
             {
                 Field* fields                   = result->Fetch();
                 ObjectGuid::LowType itemGuid    = fields[0].GetUInt32();
                 ObjectGuid::LowType itemSender  = fields[1].GetUInt32();
                 uint32 itemReceiver             = fields[2].GetUInt32();
                 uint32 itemSenderAccountId      = fields[3].GetUInt32();
                 std::string itemSenderName      = fields[4].GetString();
                 uint32 itemReceiverAccount      = fields[5].GetUInt32();
                 std::string itemReceiverName    = fields[6].GetString();
                 char const* itemPos = "[in mail]";
                 handler->PSendSysMessage(LANG_ITEMLIST_MAIL, itemGuid, itemSenderName.c_str(), itemSender, itemSenderAccountId, itemReceiverName.c_str(), itemReceiver, itemReceiverAccount, itemPos);
             }
             while (result->NextRow());
             uint32 resultCount = uint32(result->GetRowCount());
             if (count > resultCount)
                 count -= resultCount;
             else
                 count = 0;
         }
         // auction case
         uint32 auctionCount = 0;
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_AUCTIONHOUSE_COUNT_ITEM);
         stmt->setUInt32(0, itemId);
         result = CharacterDatabase.Query(stmt);
         if (result)
             auctionCount = (*result)[0].GetUInt64();
         if (count > 0)
         {
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_AUCTIONHOUSE_ITEM_BY_ENTRY);
             stmt->setUInt32(0, itemId);
             stmt->setUInt32(1, count);
             result = CharacterDatabase.Query(stmt);
         }
         else
             result = PreparedQueryResult(nullptr);
         if (result)
         {
             do
             {
                 Field* fields           = result->Fetch();
                 uint32 itemGuid         = fields[0].GetUInt32();
                 uint32 owner            = fields[1].GetUInt32();
                 uint32 ownerAccountId   = fields[2].GetUInt32();
                 std::string ownerName   = fields[3].GetString();
                 char const* itemPos = "[in auction]";
                 handler->PSendSysMessage(LANG_ITEMLIST_AUCTION, itemGuid, ownerName.c_str(), owner, ownerAccountId, itemPos);
             }
             while (result->NextRow());
         }
         // guild bank case
         uint32 guildCount = 0;
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_GUILD_BANK_COUNT_ITEM);
         stmt->setUInt32(0, itemId);
         result = CharacterDatabase.Query(stmt);
         if (result)
             guildCount = (*result)[0].GetUInt64();
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_GUILD_BANK_ITEM_BY_ENTRY);
         stmt->setUInt32(0, itemId);
         stmt->setUInt32(1, count);
         result = CharacterDatabase.Query(stmt);
         if (result)
         {
             do
             {
                 Field* fields = result->Fetch();
                 uint32 itemGuid = fields[0].GetUInt32();
                 uint32 guildGuid = fields[1].GetUInt32();
                 std::string guildName = fields[2].GetString();
                 char const* itemPos = "[in guild bank]";
                 handler->PSendSysMessage(LANG_ITEMLIST_GUILD, itemGuid, guildName.c_str(), guildGuid, itemPos);
             }
             while (result->NextRow());
             uint32 resultCount = uint32(result->GetRowCount());
             if (count > resultCount)
                 count -= resultCount;
             else
                 count = 0;
         }
         if (inventoryCount + mailCount + auctionCount + guildCount == 0)
         {
             handler->SendSysMessage(LANG_COMMAND_NOITEMFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         handler->PSendSysMessage(LANG_COMMAND_LISTITEMMESSAGE, itemId, inventoryCount + mailCount + auctionCount + guildCount, inventoryCount, mailCount, auctionCount, guildCount);
         return true;
     }
References CHAR_SEL_AUCTIONHOUSE_COUNT_ITEM, CHAR_SEL_AUCTIONHOUSE_ITEM_BY_ENTRY, CHAR_SEL_CHAR_INVENTORY_COUNT_ITEM, CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY, CHAR_SEL_GUILD_BANK_COUNT_ITEM, CHAR_SEL_GUILD_BANK_ITEM_BY_ENTRY, CHAR_SEL_MAIL_COUNT_ITEM, CHAR_SEL_MAIL_ITEMS_BY_ENTRY, CharacterDatabase, Field::GetString(), Field::GetUInt32(), Field::GetUInt8(), Player::IsBankPos(), Player::IsEquipmentPos(), Player::IsInventoryPos(), LANG_COMMAND_LISTITEMMESSAGE, LANG_COMMAND_NOITEMFOUND, LANG_ITEMLIST_AUCTION, LANG_ITEMLIST_GUILD, LANG_ITEMLIST_MAIL, LANG_ITEMLIST_SLOT, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and PreparedStatementBase::setUInt32().
HandleListObjectCommand()
static bool list_commandscript::HandleListObjectCommand (ChatHandler * handler, Variant< Hyperlink< gameobject_entry >, uint32 > gameObjectId, Optional< uint32 > countArg) inline static
Definition at line 357 of file cs_list.cpp.
     {
         GameObjectTemplate const* gInfo = sObjectMgr->GetGameObjectTemplate(gameObjectId);
         if (!gInfo)
         {
             handler->PSendSysMessage(LANG_COMMAND_LISTOBJINVALIDID, uint32(gameObjectId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 count = countArg.value_or(10);
         if (count == 0)
             return false;
         QueryResult result;
         uint32 objectCount = 0;
         result = WorldDatabase.PQuery("SELECT COUNT(guid) FROM gameobject WHERE id='%u'", uint32(gameObjectId));
         if (result)
             objectCount = (*result)[0].GetUInt64();
         if (handler->GetSession())
         {
             Player* player = handler->GetSession()->GetPlayer();
             result = WorldDatabase.PQuery("SELECT guid, position_x, position_y, position_z, map, id, (POW(position_x - '%f', 2) + POW(position_y - '%f', 2) + POW(position_z - '%f', 2)) AS order_ FROM gameobject WHERE id = '%u' ORDER BY order_ ASC LIMIT %u",
                                           player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), uint32(gameObjectId), count);
         }
         else
             result = WorldDatabase.PQuery("SELECT guid, position_x, position_y, position_z, map, id FROM gameobject WHERE id = '%u' LIMIT %u",
                                           uint32(gameObjectId), count);
         if (result)
         {
             do
             {
                 Field* fields               = result->Fetch();
                 ObjectGuid::LowType guid    = fields[0].GetUInt32();
                 float x                     = fields[1].GetFloat();
                 float y                     = fields[2].GetFloat();
                 float z                     = fields[3].GetFloat();
                 uint16 mapId                = fields[4].GetUInt16();
                 uint32 entry                = fields[5].GetUInt32();
                 bool liveFound = false;
                 // Get map (only support base map from console)
                 Map* thisMap;
                 if (handler->GetSession())
                     thisMap = handler->GetSession()->GetPlayer()->GetMap();
                 else
                     thisMap = sMapMgr->FindBaseNonInstanceMap(mapId);
                 // If map found, try to find active version of this object
                 if (thisMap)
                 {
                     auto const goBounds = thisMap->GetGameObjectBySpawnIdStore().equal_range(guid);
                     if (goBounds.first != goBounds.second)
                     {
                         for (std::unordered_multimap<uint32, GameObject*>::const_iterator itr = goBounds.first; itr != goBounds.second;)
{
                             if (handler->GetSession())
                                 handler->PSendSysMessage(LANG_GO_LIST_CHAT, guid, entry, guid, gInfo->name.c_str(), x, y, z, mapId, itr->second->GetGUID().ToString().c_str(), itr->second->isSpawned() ? "*" : " ");
                             else
                                 handler->PSendSysMessage(LANG_GO_LIST_CONSOLE, guid, gInfo->name.c_str(), x, y, z, mapId, itr->second->GetGUID().ToString().c_str(), itr->second->isSpawned() ? "*" : " ");
                             ++itr;
                         }
                         liveFound = true;
                     }
                 }
                 if (!liveFound)
                 {
                     if (handler->GetSession())
                         handler->PSendSysMessage(LANG_GO_LIST_CHAT, guid, entry, guid, gInfo->name.c_str(), x, y, z, mapId, "", "");
                     else
                         handler->PSendSysMessage(LANG_GO_LIST_CONSOLE, guid, gInfo->name.c_str(), x, y, z, mapId, "", "");
                 }
             }
             while (result->NextRow());
         }
         handler->PSendSysMessage(LANG_COMMAND_LISTOBJMESSAGE, uint32(gameObjectId), objectCount);
         return true;
     }
References Field::GetFloat(), Map::GetGameObjectBySpawnIdStore(), WorldObject::GetMap(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_LISTOBJINVALIDID, LANG_COMMAND_LISTOBJMESSAGE, LANG_GO_LIST_CHAT, LANG_GO_LIST_CONSOLE, GameObjectTemplate::name, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sMapMgr, sObjectMgr, and WorldDatabase.
ListAurasCommand()
static bool list_commandscript::ListAurasCommand (ChatHandler * handler, Optional< uint32 > spellId, std::wstring namePart) inline static
Definition at line 458 of file cs_list.cpp.
     {
         Unit* unit = handler->getSelectedUnit();
         if (!unit)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         wstrToLower(namePart);
         char const* talentStr = handler->GetAcoreString(LANG_TALENT);
         char const* passiveStr = handler->GetAcoreString(LANG_PASSIVE);
         Unit::AuraApplicationMap const& auras = unit->GetAppliedAuras();
         handler->PSendSysMessage(LANG_COMMAND_TARGET_LISTAURAS, auras.size());
         for (auto const& [aurId, aurApp] : auras)
         {
             bool talent = GetTalentSpellCost(aurApp->GetBase()->GetId()) > 0;
             Aura const* aura = aurApp->GetBase();
             char const* name = aura->GetSpellInfo()->SpellName[handler->GetSessionDbcLocale()];
             if (!ShouldListAura(aura->GetSpellInfo(), spellId, namePart, handler->GetSessionDbcLocale()))
                 continue;
             std::ostringstream ss_name;
             ss_name << "|cffffffff|Hspell:" << aura->GetId() << "|h[" << name << "]|h|r";
             handler->PSendSysMessage(LANG_COMMAND_TARGET_AURADETAIL, aura->GetId(), (handler->GetSession() ? ss_name.str().c_str() : name),
                                      aurApp->GetEffectMask(), aura->GetCharges(), aura->GetStackAmount(), aurApp->GetSlot(),
                                      aura->GetDuration(), aura->GetMaxDuration(), (aura->IsPassive() ? passiveStr : ""),
                                      (talent ? talentStr : ""), aura->GetCasterGUID().IsPlayer() ? "player" : "creature",
                                      aura->GetCasterGUID().GetCounter());
         }
         for (uint16 i = 0; i < TOTAL_AURAS; ++i)
         {
             Unit::AuraEffectList const& auraList = unit->GetAuraEffectsByType(AuraType(i));
             if (auraList.empty())
                 continue;
             bool sizeLogged = false;
             for (AuraEffect const* effect : auraList)
             {
                 if (!ShouldListAura(effect->GetSpellInfo(), spellId, namePart, handler->GetSessionDbcLocale()))
                     continue;
                 if (!sizeLogged)
                 {
                     sizeLogged = true;
                     handler->PSendSysMessage(LANG_COMMAND_TARGET_LISTAURATYPE, auraList.size(), i);
                 }
                 handler->PSendSysMessage(LANG_COMMAND_TARGET_AURASIMPLE, effect->GetId(), effect->GetEffIndex(), effect->GetAmount());
             }
         }
         return true;
     }
References ChatHandler::GetAcoreString(), Unit::GetAppliedAuras(), Unit::GetAuraEffectsByType(), Aura::GetCasterGUID(), Aura::GetCharges(), ObjectGuid::GetCounter(), Aura::GetDuration(), Aura::GetId(), Aura::GetMaxDuration(), ChatHandler::getSelectedUnit(), ChatHandler::GetSession(), ChatHandler::GetSessionDbcLocale(), Aura::GetSpellInfo(), Aura::GetStackAmount(), GetTalentSpellCost(), Aura::IsPassive(), ObjectGuid::IsPlayer(), LANG_COMMAND_TARGET_AURADETAIL, LANG_COMMAND_TARGET_AURASIMPLE, LANG_COMMAND_TARGET_LISTAURAS, LANG_COMMAND_TARGET_LISTAURATYPE, LANG_PASSIVE, LANG_SELECT_CHAR_OR_CREATURE, LANG_TALENT, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), SpellInfo::SpellName, TOTAL_AURAS, and wstrToLower().
ShouldListAura()
static bool list_commandscript::ShouldListAura (SpellInfo const * spellInfo, Optional< uint32 > spellId, std::wstring namePart, uint8 locale) inline static
Definition at line 521 of file cs_list.cpp.
     {
         if (spellId)
             return spellInfo->Id == spellId;
         if (!namePart.empty())
         {
             std::string name = spellInfo->SpellName[locale];
             return Utf8FitTo(name, namePart);
         }
         return true;
     }
References SpellInfo::Id, SpellInfo::SpellName, and Utf8FitTo().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_list.cpp