Azerotcore-wotlk: src/server/scripts/World/npc_professions.cpp File Reference
npc_professions.cpp File Reference
#include "Player.h"
#include "ScriptedCreature.h"
#include "ScriptedGossip.h"
#include "ScriptMgr.h"
#include "SpellInfo.h"
#include "WorldSession.h"
Classes
class npc_prof_alchemy
class npc_prof_blacksmith
class npc_engineering_tele_trinket
class npc_prof_leather
class npc_prof_tailor
class go_evil_book_for_dummies
Macros
#define TALK_MUST_UNLEARN_WEAPON "You must forget your weapon type specialty before I can help you. Go to Everlook in Winterspring and seek help there."
#define TALK_HAMMER_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the hammersmith."
#define TALK_AXE_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the axesmith."
#define TALK_SWORD_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the swordsmith."
#define TALK_HAMMER_UNLEARN "Forgetting your Hammersmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Hammersmithing to create!"
#define TALK_AXE_UNLEARN "Forgetting your Axesmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Axesmithing to create!"
#define TALK_SWORD_UNLEARN "Forgetting your Swordsmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Swordsmithing to create!"
#define GOSSIP_SENDER_LEARN 50
#define GOSSIP_SENDER_UNLEARN 51
#define GOSSIP_SENDER_CHECK 52
#define GOSSIP_LEARN_POTION "Please teach me how to become a Master of Potions, Lauranna"
#define GOSSIP_UNLEARN_POTION "I wish to unlearn Potion Mastery"
#define GOSSIP_LEARN_TRANSMUTE "Please teach me how to become a Master of Transmutations, Zarevhi"
#define GOSSIP_UNLEARN_TRANSMUTE "I wish to unlearn Transmutation Mastery"
#define GOSSIP_LEARN_ELIXIR "Please teach me how to become a Master of Elixirs, Lorokeem"
#define GOSSIP_UNLEARN_ELIXIR "I wish to unlearn Elixir Mastery"
#define BOX_UNLEARN_ALCHEMY_SPEC "Do you really want to unlearn your alchemy specialty and lose all associated recipes? \n Cost: "
#define GOSSIP_WEAPON_LEARN "Please teach me how to become a Weaponsmith"
#define GOSSIP_WEAPON_UNLEARN "I wish to unlearn the art of Weaponsmithing"
#define GOSSIP_ARMOR_LEARN "Please teach me how to become a Armorsmith"
#define GOSSIP_ARMOR_UNLEARN "I wish to unlearn the art of Armorsmithing"
#define GOSSIP_UNLEARN_SMITH_SPEC "I wish to unlearn my blacksmith specialty"
#define BOX_UNLEARN_ARMORORWEAPON "Do you really want to unlearn your blacksmith specialty and lose all associated recipes? \n Cost: "
#define GOSSIP_LEARN_HAMMER "Please teach me how to become a Hammersmith, Lilith"
#define GOSSIP_UNLEARN_HAMMER "I wish to unlearn Hammersmithing"
#define GOSSIP_LEARN_AXE "Please teach me how to become a Axesmith, Kilram"
#define GOSSIP_UNLEARN_AXE "I wish to unlearn Axesmithing"
#define GOSSIP_LEARN_SWORD "Please teach me how to become a Swordsmith, Seril"
#define GOSSIP_UNLEARN_SWORD "I wish to unlearn Swordsmithing"
#define BOX_UNLEARN_WEAPON_SPEC "Do you really want to unlearn your weaponsmith specialty and lose all associated recipes? \n Cost: "
#define GOSSIP_LEARN_DRAGON "I wish to learn Dragonscale Leatherworking"
#define GOSSIP_LEARN_ELEMENTAL "I wish to learn Elemental Leatherworking"
#define GOSSIP_LEARN_TRIBAL "I wish to learn Tribal Leatherworking"
#define GOSSIP_LEARN_SPELLFIRE "Please teach me how to become a Spellcloth tailor"
#define GOSSIP_UNLEARN_SPELLFIRE "I wish to unlearn Spellfire Tailoring"
#define GOSSIP_LEARN_MOONCLOTH "Please teach me how to become a Mooncloth tailor"
#define GOSSIP_UNLEARN_MOONCLOTH "I wish to unlearn Mooncloth Tailoring"
#define GOSSIP_LEARN_SHADOWEAVE "Please teach me how to become a Shadoweave tailor"
#define GOSSIP_UNLEARN_SHADOWEAVE "I wish to unlearn Shadoweave Tailoring"
#define BOX_UNLEARN_TAILOR_SPEC "Do you really want to unlearn your tailoring specialty and lose all associated recipes? \n Cost: "
#define GOSSIP_LEARN_GOBLIN "I am absolutely certain that i want to learn Goblin engineering"
#define GOSSIP_LEARN_GNOMISH "I am absolutely certain that i want to learn Gnomish engineering"
#define GOSSIP_UNLEARN_GOBLIN "I wish to unlearn Goblin engineering"
#define GOSSIP_UNLEARN_GNOMISH "I wish to unlearn Gnomish engineering"
#define BOX_UNLEARN_ENGIN_SPEC "Do you really want to unlearn your engineering specialty and lose all associated recipes? \n Cost: "
#define BOX_LEARN_ENGIN_SPEC "Do you really want to learn this engineering specialty? \n Cost: "
#define GOSSIP_ITEM_ZAP "This Dimensional Imploder sounds dangerous! How can I make one?"
#define GOSSIP_ITEM_JHORDY "I must build a beacon for this marvelous device!"
#define GOSSIP_ITEM_KABLAM "[PH] Unknown"
Enumerations
enum ProfessionSpells {
S_WEAPON = 9787 , S_ARMOR = 9788 , S_HAMMER = 17040 , S_AXE = 17041 ,
S_SWORD = 17039 , S_LEARN_WEAPON = 9789 , S_LEARN_ARMOR = 9790 , S_LEARN_HAMMER = 39099 ,
S_LEARN_AXE = 39098 , S_LEARN_SWORD = 39097 , S_UNLEARN_WEAPON = 36436 , S_UNLEARN_ARMOR = 36435 ,
S_UNLEARN_HAMMER = 36441 , S_UNLEARN_AXE = 36439 , S_UNLEARN_SWORD = 36438 , S_REP_ARMOR = 17451 ,
S_REP_WEAPON = 17452 , REP_ARMOR = 46 , REP_WEAPON = 289 , REP_HAMMER = 569 ,
REP_AXE = 570 , REP_SWORD = 571 , S_DRAGON = 10656 , S_ELEMENTAL = 10658 ,
S_TRIBAL = 10660 , S_LEARN_DRAGON = 10657 , S_LEARN_ELEMENTAL = 10659 , S_LEARN_TRIBAL = 10661 ,
S_UNLEARN_DRAGON = 36434 , S_UNLEARN_ELEMENTAL = 36328 , S_UNLEARN_TRIBAL = 36433 , S_GOBLIN = 20222 ,
S_GNOMISH = 20219 , S_LEARN_GOBLIN = 20221 , S_LEARN_GNOMISH = 20220 , S_SPELLFIRE = 26797 ,
S_MOONCLOTH = 26798 , S_SHADOWEAVE = 26801 , S_UNLEARN_GOBLIN = 68334 , S_UNLEARN_GNOMISH = 68333 ,
S_LEARN_SPELLFIRE = 26796 , S_LEARN_MOONCLOTH = 26799 , S_LEARN_SHADOWEAVE = 26800 , S_UNLEARN_SPELLFIRE = 41299 ,
S_UNLEARN_MOONCLOTH = 41558 , S_UNLEARN_SHADOWEAVE = 41559 , S_TRANSMUTE = 28672 , S_ELIXIR = 28677 ,
S_POTION = 28675 , S_LEARN_TRANSMUTE = 28674 , S_LEARN_ELIXIR = 28678 , S_LEARN_POTION = 28676 ,
S_UNLEARN_TRANSMUTE = 41565 , S_UNLEARN_ELIXIR = 41564 , S_UNLEARN_POTION = 41563
}
enum SpecializationTrainers {
N_TRAINER_TRANSMUTE = 22427 , N_TRAINER_ELIXIR = 19052 , N_TRAINER_POTION = 17909 , N_TRAINER_SMITHOMNI1 = 11145 ,
N_TRAINER_SMITHOMNI2 = 11176 , N_TRAINER_WEAPON1 = 11146 , N_TRAINER_WEAPON2 = 11178 , N_TRAINER_ARMOR1 = 5164 ,
N_TRAINER_ARMOR2 = 11177 , N_TRAINER_HAMMER = 11191 , N_TRAINER_AXE = 11192 , N_TRAINER_SWORD = 11193 ,
N_TRAINER_DRAGON1 = 7866 , N_TRAINER_DRAGON2 = 7867 , N_TRAINER_ELEMENTAL1 = 7868 , N_TRAINER_ELEMENTAL2 = 7869 ,
N_TRAINER_TRIBAL1 = 7870 , N_TRAINER_TRIBAL2 = 7871 , N_TRAINER_SPELLFIRE = 22213 , N_TRAINER_MOONCLOTH = 22208 ,
N_TRAINER_SHADOWEAVE = 22212
}
enum SpecializationQuests { Q_MASTER_TRANSMUTE = 10899 , Q_MASTER_ELIXIR = 10902 , Q_MASTER_POTION = 10897 }
enum EngineeringTrinkets {
NPC_ZAP = 14742 , NPC_JHORDY = 14743 , NPC_KABLAM = 21493 , NPC_SMILES = 21494 ,
SPELL_LEARN_TO_EVERLOOK = 23490 , SPELL_LEARN_TO_GADGET = 23491 , SPELL_LEARN_TO_AREA52 = 36956 , SPELL_LEARN_TO_TOSHLEY = 36957 ,
SPELL_TO_EVERLOOK = 23486 , SPELL_TO_GADGET = 23489 , SPELL_TO_AREA52 = 36954 , SPELL_TO_TOSHLEY = 36955
}
Functions
int32 DoLearnCost (Player *)
int32 DoHighUnlearnCost (Player *)
int32 DoMedUnlearnCost (Player *player)
int32 DoLowUnlearnCost (Player *player)
bool EquippedOk (Player *player, uint32 spellId)
void ProfessionUnlearnSpells (Player *player, uint32 type)
void ProcessCastaction (Player *player, Creature *creature, uint32 spellId, uint32 triggeredSpellId, int32 cost)
void ProcessUnlearnAction (Player *player, Creature *creature, uint32 spellId, uint32 alternativeSpellId, int32 cost)
void AddSC_npc_professions ()
Macro Definition Documentation
BOX_LEARN_ENGIN_SPEC
#define BOX_LEARN_ENGIN_SPEC "Do you really want to learn this engineering specialty? \n Cost: "
Definition at line 109 of file npc_professions.cpp.
BOX_UNLEARN_ALCHEMY_SPEC
#define BOX_UNLEARN_ALCHEMY_SPEC "Do you really want to unlearn your alchemy specialty and lose all associated recipes? \n Cost: "
Definition at line 71 of file npc_professions.cpp.
BOX_UNLEARN_ARMORORWEAPON
#define BOX_UNLEARN_ARMORORWEAPON "Do you really want to unlearn your blacksmith specialty and lose all associated recipes? \n Cost: "
Definition at line 79 of file npc_professions.cpp.
BOX_UNLEARN_ENGIN_SPEC
#define BOX_UNLEARN_ENGIN_SPEC "Do you really want to unlearn your engineering specialty and lose all associated recipes? \n Cost: "
Definition at line 108 of file npc_professions.cpp.
BOX_UNLEARN_TAILOR_SPEC
#define BOX_UNLEARN_TAILOR_SPEC "Do you really want to unlearn your tailoring specialty and lose all associated recipes? \n Cost: "
Definition at line 101 of file npc_professions.cpp.
BOX_UNLEARN_WEAPON_SPEC
#define BOX_UNLEARN_WEAPON_SPEC "Do you really want to unlearn your weaponsmith specialty and lose all associated recipes? \n Cost: "
Definition at line 88 of file npc_professions.cpp.
GOSSIP_ARMOR_LEARN
#define GOSSIP_ARMOR_LEARN "Please teach me how to become a Armorsmith"
Definition at line 75 of file npc_professions.cpp.
GOSSIP_ARMOR_UNLEARN
#define GOSSIP_ARMOR_UNLEARN "I wish to unlearn the art of Armorsmithing"
Definition at line 76 of file npc_professions.cpp.
GOSSIP_ITEM_JHORDY
#define GOSSIP_ITEM_JHORDY "I must build a beacon for this marvelous device!"
Definition at line 847 of file npc_professions.cpp.
GOSSIP_ITEM_KABLAM
#define GOSSIP_ITEM_KABLAM "[PH] Unknown"
Definition at line 848 of file npc_professions.cpp.
GOSSIP_ITEM_ZAP
#define GOSSIP_ITEM_ZAP "This Dimensional Imploder sounds dangerous! How can I make one?"
Definition at line 846 of file npc_professions.cpp.
GOSSIP_LEARN_AXE
#define GOSSIP_LEARN_AXE "Please teach me how to become a Axesmith, Kilram"
Definition at line 83 of file npc_professions.cpp.
GOSSIP_LEARN_DRAGON
#define GOSSIP_LEARN_DRAGON "I wish to learn Dragonscale Leatherworking"
Definition at line 90 of file npc_professions.cpp.
GOSSIP_LEARN_ELEMENTAL
#define GOSSIP_LEARN_ELEMENTAL "I wish to learn Elemental Leatherworking"
Definition at line 91 of file npc_professions.cpp.
GOSSIP_LEARN_ELIXIR
#define GOSSIP_LEARN_ELIXIR "Please teach me how to become a Master of Elixirs, Lorokeem"
Definition at line 68 of file npc_professions.cpp.
GOSSIP_LEARN_GNOMISH
#define GOSSIP_LEARN_GNOMISH "I am absolutely certain that i want to learn Gnomish engineering"
Definition at line 104 of file npc_professions.cpp.
GOSSIP_LEARN_GOBLIN
#define GOSSIP_LEARN_GOBLIN "I am absolutely certain that i want to learn Goblin engineering"
Definition at line 103 of file npc_professions.cpp.
GOSSIP_LEARN_HAMMER
#define GOSSIP_LEARN_HAMMER "Please teach me how to become a Hammersmith, Lilith"
Definition at line 81 of file npc_professions.cpp.
GOSSIP_LEARN_MOONCLOTH
#define GOSSIP_LEARN_MOONCLOTH "Please teach me how to become a Mooncloth tailor"
Definition at line 96 of file npc_professions.cpp.
GOSSIP_LEARN_POTION
#define GOSSIP_LEARN_POTION "Please teach me how to become a Master of Potions, Lauranna"
Definition at line 64 of file npc_professions.cpp.
GOSSIP_LEARN_SHADOWEAVE
#define GOSSIP_LEARN_SHADOWEAVE "Please teach me how to become a Shadoweave tailor"
Definition at line 98 of file npc_professions.cpp.
GOSSIP_LEARN_SPELLFIRE
#define GOSSIP_LEARN_SPELLFIRE "Please teach me how to become a Spellcloth tailor"
Definition at line 94 of file npc_professions.cpp.
GOSSIP_LEARN_SWORD
#define GOSSIP_LEARN_SWORD "Please teach me how to become a Swordsmith, Seril"
Definition at line 85 of file npc_professions.cpp.
GOSSIP_LEARN_TRANSMUTE
#define GOSSIP_LEARN_TRANSMUTE "Please teach me how to become a Master of Transmutations, Zarevhi"
Definition at line 66 of file npc_professions.cpp.
GOSSIP_LEARN_TRIBAL
#define GOSSIP_LEARN_TRIBAL "I wish to learn Tribal Leatherworking"
Definition at line 92 of file npc_professions.cpp.
GOSSIP_SENDER_CHECK
#define GOSSIP_SENDER_CHECK 52
Definition at line 58 of file npc_professions.cpp.
GOSSIP_SENDER_LEARN
#define GOSSIP_SENDER_LEARN 50
Definition at line 56 of file npc_professions.cpp.
GOSSIP_SENDER_UNLEARN
#define GOSSIP_SENDER_UNLEARN 51
Definition at line 57 of file npc_professions.cpp.
GOSSIP_UNLEARN_AXE
#define GOSSIP_UNLEARN_AXE "I wish to unlearn Axesmithing"
Definition at line 84 of file npc_professions.cpp.
GOSSIP_UNLEARN_ELIXIR
#define GOSSIP_UNLEARN_ELIXIR "I wish to unlearn Elixir Mastery"
Definition at line 69 of file npc_professions.cpp.
GOSSIP_UNLEARN_GNOMISH
#define GOSSIP_UNLEARN_GNOMISH "I wish to unlearn Gnomish engineering"
Definition at line 106 of file npc_professions.cpp.
GOSSIP_UNLEARN_GOBLIN
#define GOSSIP_UNLEARN_GOBLIN "I wish to unlearn Goblin engineering"
Definition at line 105 of file npc_professions.cpp.
GOSSIP_UNLEARN_HAMMER
#define GOSSIP_UNLEARN_HAMMER "I wish to unlearn Hammersmithing"
Definition at line 82 of file npc_professions.cpp.
GOSSIP_UNLEARN_MOONCLOTH
#define GOSSIP_UNLEARN_MOONCLOTH "I wish to unlearn Mooncloth Tailoring"
Definition at line 97 of file npc_professions.cpp.
GOSSIP_UNLEARN_POTION
#define GOSSIP_UNLEARN_POTION "I wish to unlearn Potion Mastery"
Definition at line 65 of file npc_professions.cpp.
GOSSIP_UNLEARN_SHADOWEAVE
#define GOSSIP_UNLEARN_SHADOWEAVE "I wish to unlearn Shadoweave Tailoring"
Definition at line 99 of file npc_professions.cpp.
GOSSIP_UNLEARN_SMITH_SPEC
#define GOSSIP_UNLEARN_SMITH_SPEC "I wish to unlearn my blacksmith specialty"
Definition at line 78 of file npc_professions.cpp.
GOSSIP_UNLEARN_SPELLFIRE
#define GOSSIP_UNLEARN_SPELLFIRE "I wish to unlearn Spellfire Tailoring"
Definition at line 95 of file npc_professions.cpp.
GOSSIP_UNLEARN_SWORD
#define GOSSIP_UNLEARN_SWORD "I wish to unlearn Swordsmithing"
Definition at line 86 of file npc_professions.cpp.
GOSSIP_UNLEARN_TRANSMUTE
#define GOSSIP_UNLEARN_TRANSMUTE "I wish to unlearn Transmutation Mastery"
Definition at line 67 of file npc_professions.cpp.
GOSSIP_WEAPON_LEARN
#define GOSSIP_WEAPON_LEARN "Please teach me how to become a Weaponsmith"
Definition at line 73 of file npc_professions.cpp.
GOSSIP_WEAPON_UNLEARN
#define GOSSIP_WEAPON_UNLEARN "I wish to unlearn the art of Weaponsmithing"
Definition at line 74 of file npc_professions.cpp.
TALK_AXE_LEARN
#define TALK_AXE_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the axesmith."
Definition at line 45 of file npc_professions.cpp.
TALK_AXE_UNLEARN
#define TALK_AXE_UNLEARN "Forgetting your Axesmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Axesmithing to create!"
Definition at line 49 of file npc_professions.cpp.
TALK_HAMMER_LEARN
#define TALK_HAMMER_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the hammersmith."
Definition at line 44 of file npc_professions.cpp.
TALK_HAMMER_UNLEARN
#define TALK_HAMMER_UNLEARN "Forgetting your Hammersmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Hammersmithing to create!"
Definition at line 48 of file npc_professions.cpp.
TALK_MUST_UNLEARN_WEAPON
#define TALK_MUST_UNLEARN_WEAPON "You must forget your weapon type specialty before I can help you. Go to Everlook in Winterspring and seek help there."
Definition at line 42 of file npc_professions.cpp.
TALK_SWORD_LEARN
#define TALK_SWORD_LEARN "Ah, a seasoned veteran you once were. I know you are capable, you merely need to ask and I shall teach you the way of the swordsmith."
Definition at line 46 of file npc_professions.cpp.
TALK_SWORD_UNLEARN
#define TALK_SWORD_UNLEARN "Forgetting your Swordsmithing skill is not something to do lightly. If you choose to abandon it you will forget all recipes that require Swordsmithing to create!"
Definition at line 50 of file npc_professions.cpp.
Enumeration Type Documentation
EngineeringTrinkets
enum EngineeringTrinkets
Enumerator
NPC_ZAP
NPC_JHORDY
NPC_KABLAM
NPC_SMILES
SPELL_LEARN_TO_EVERLOOK
SPELL_LEARN_TO_GADGET
SPELL_LEARN_TO_AREA52
SPELL_LEARN_TO_TOSHLEY
SPELL_TO_EVERLOOK
SPELL_TO_GADGET
SPELL_TO_AREA52
SPELL_TO_TOSHLEY
Definition at line 828 of file npc_professions.cpp.
 {
     NPC_ZAP                     = 14742,
     NPC_JHORDY                  = 14743,
     NPC_KABLAM                  = 21493,
     NPC_SMILES                  = 21494,
     SPELL_LEARN_TO_EVERLOOK     = 23490,
     SPELL_LEARN_TO_GADGET       = 23491,
     SPELL_LEARN_TO_AREA52       = 36956,
     SPELL_LEARN_TO_TOSHLEY      = 36957,
     SPELL_TO_EVERLOOK           = 23486,
     SPELL_TO_GADGET             = 23489,
     SPELL_TO_AREA52             = 36954,
     SPELL_TO_TOSHLEY            = 36955,
 };
ProfessionSpells
enum ProfessionSpells
Enumerator
S_WEAPON
S_ARMOR
S_HAMMER
S_AXE
S_SWORD
S_LEARN_WEAPON
S_LEARN_ARMOR
S_LEARN_HAMMER
S_LEARN_AXE
S_LEARN_SWORD
S_UNLEARN_WEAPON
S_UNLEARN_ARMOR
S_UNLEARN_HAMMER
S_UNLEARN_AXE
S_UNLEARN_SWORD
S_REP_ARMOR
S_REP_WEAPON
REP_ARMOR
REP_WEAPON
REP_HAMMER
REP_AXE
REP_SWORD
S_DRAGON
S_ELEMENTAL
S_TRIBAL
S_LEARN_DRAGON
S_LEARN_ELEMENTAL
S_LEARN_TRIBAL
S_UNLEARN_DRAGON
S_UNLEARN_ELEMENTAL
S_UNLEARN_TRIBAL
S_GOBLIN
S_GNOMISH
S_LEARN_GOBLIN
S_LEARN_GNOMISH
S_SPELLFIRE
S_MOONCLOTH
S_SHADOWEAVE
S_UNLEARN_GOBLIN
S_UNLEARN_GNOMISH
S_LEARN_SPELLFIRE
S_LEARN_MOONCLOTH
S_LEARN_SHADOWEAVE
S_UNLEARN_SPELLFIRE
S_UNLEARN_MOONCLOTH
S_UNLEARN_SHADOWEAVE
S_TRANSMUTE
S_ELIXIR
S_POTION
S_LEARN_TRANSMUTE
S_LEARN_ELIXIR
S_LEARN_POTION
S_UNLEARN_TRANSMUTE
S_UNLEARN_ELIXIR
S_UNLEARN_POTION
Definition at line 114 of file npc_professions.cpp.
 {
     S_WEAPON                = 9787,
     S_ARMOR                 = 9788,
     S_HAMMER                = 17040,
     S_AXE                   = 17041,
     S_SWORD                 = 17039,
     S_LEARN_WEAPON          = 9789,
     S_LEARN_ARMOR           = 9790,
     S_LEARN_HAMMER          = 39099,
     S_LEARN_AXE             = 39098,
     S_LEARN_SWORD           = 39097,
     S_UNLEARN_WEAPON        = 36436,
     S_UNLEARN_ARMOR         = 36435,
     S_UNLEARN_HAMMER        = 36441,
     S_UNLEARN_AXE           = 36439,
     S_UNLEARN_SWORD         = 36438,
     S_REP_ARMOR             = 17451,
     S_REP_WEAPON            = 17452,
     REP_ARMOR               = 46,
     REP_WEAPON              = 289,
     REP_HAMMER              = 569,
     REP_AXE                 = 570,
     REP_SWORD               = 571,
     S_DRAGON                = 10656,
     S_ELEMENTAL             = 10658,
     S_TRIBAL                = 10660,
     S_LEARN_DRAGON          = 10657,
     S_LEARN_ELEMENTAL       = 10659,
     S_LEARN_TRIBAL          = 10661,
     S_UNLEARN_DRAGON        = 36434,
     S_UNLEARN_ELEMENTAL     = 36328,
     S_UNLEARN_TRIBAL        = 36433,
     S_GOBLIN                = 20222,
     S_GNOMISH               = 20219,
     S_LEARN_GOBLIN          = 20221,
     S_LEARN_GNOMISH         = 20220,
     S_SPELLFIRE             = 26797,
     S_MOONCLOTH             = 26798,
     S_SHADOWEAVE            = 26801,
     S_UNLEARN_GOBLIN        = 68334,
     S_UNLEARN_GNOMISH       = 68333,
     S_LEARN_SPELLFIRE       = 26796,
     S_LEARN_MOONCLOTH       = 26799,
     S_LEARN_SHADOWEAVE      = 26800,
     S_UNLEARN_SPELLFIRE     = 41299,
     S_UNLEARN_MOONCLOTH     = 41558,
     S_UNLEARN_SHADOWEAVE    = 41559,
     S_TRANSMUTE             = 28672,
     S_ELIXIR                = 28677,
     S_POTION                = 28675,
     S_LEARN_TRANSMUTE       = 28674,
     S_LEARN_ELIXIR          = 28678,
     S_LEARN_POTION          = 28676,
     S_UNLEARN_TRANSMUTE     = 41565,
     S_UNLEARN_ELIXIR        = 41564,
     S_UNLEARN_POTION        = 41563,
 };
SpecializationQuests
enum SpecializationQuests
Enumerator
Q_MASTER_TRANSMUTE
Q_MASTER_ELIXIR
Q_MASTER_POTION
Definition at line 226 of file npc_professions.cpp.
 {
     /* Alchemy */
     Q_MASTER_TRANSMUTE      = 10899,
     Q_MASTER_ELIXIR         = 10902,
     Q_MASTER_POTION         = 10897,
 };
SpecializationTrainers
enum SpecializationTrainers
Enumerator
N_TRAINER_TRANSMUTE
N_TRAINER_ELIXIR
N_TRAINER_POTION
N_TRAINER_SMITHOMNI1
N_TRAINER_SMITHOMNI2
N_TRAINER_WEAPON1
N_TRAINER_WEAPON2
N_TRAINER_ARMOR1
N_TRAINER_ARMOR2
N_TRAINER_HAMMER
N_TRAINER_AXE
N_TRAINER_SWORD
N_TRAINER_DRAGON1
N_TRAINER_DRAGON2
N_TRAINER_ELEMENTAL1
N_TRAINER_ELEMENTAL2
N_TRAINER_TRIBAL1
N_TRAINER_TRIBAL2
N_TRAINER_SPELLFIRE
N_TRAINER_MOONCLOTH
N_TRAINER_SHADOWEAVE
Definition at line 191 of file npc_professions.cpp.
 {
     /* Alchemy */
     N_TRAINER_TRANSMUTE     = 22427, // Zarevhi
     N_TRAINER_ELIXIR        = 19052, // Lorokeem
     N_TRAINER_POTION        = 17909, // Lauranna Thar'well
     /* Blacksmithing */
     N_TRAINER_SMITHOMNI1    = 11145, // Myolor Sunderfury
     N_TRAINER_SMITHOMNI2    = 11176, // Krathok Moltenfist
     N_TRAINER_WEAPON1       = 11146, // Ironus Coldsteel
     N_TRAINER_WEAPON2       = 11178, // Borgosh Corebender
     N_TRAINER_ARMOR1        = 5164, // Grumnus Steelshaper
     N_TRAINER_ARMOR2        = 11177, // Okothos Ironrager
     N_TRAINER_HAMMER        = 11191, // Lilith the Lithe
     N_TRAINER_AXE           = 11192, // Kilram
     N_TRAINER_SWORD         = 11193, // Seril Scourgebane
     /* Leatherworking */
     N_TRAINER_DRAGON1       = 7866, // Peter Galen
     N_TRAINER_DRAGON2       = 7867, // Thorkaf Dragoneye
     N_TRAINER_ELEMENTAL1    = 7868, // Sarah Tanner
     N_TRAINER_ELEMENTAL2    = 7869, // Brumn Winterhoof
     N_TRAINER_TRIBAL1       = 7870, // Caryssia Moonhunter
     N_TRAINER_TRIBAL2       = 7871, // Se'Jib
     /* Tailoring */
     N_TRAINER_SPELLFIRE     = 22213, // Gidge Spellweaver
     N_TRAINER_MOONCLOTH     = 22208, // Nasmara Moonsong
     N_TRAINER_SHADOWEAVE    = 22212, // Andrion Darkspinner
 };
Function Documentation
AddSC_npc_professions()
void AddSC_npc_professions ()
Definition at line 1314 of file npc_professions.cpp.
 {
     new npc_prof_alchemy();
     new npc_prof_blacksmith();
     new npc_engineering_tele_trinket();
     new npc_prof_leather();
     new npc_prof_tailor();
     new go_evil_book_for_dummies();
 }
Referenced by AddWorldScripts().
DoHighUnlearnCost()
int32 DoHighUnlearnCost (Player *)
Definition at line 243 of file npc_professions.cpp.
 {
     return 1500000;
 }
Referenced by go_evil_book_for_dummies::OnGossipHello(), npc_prof_alchemy::SendActionMenu(), npc_prof_tailor::SendActionMenu(), go_evil_book_for_dummies::SendActionMenu(), npc_prof_alchemy::SendConfirmUnlearn(), npc_prof_tailor::SendConfirmUnlearn(), and go_evil_book_for_dummies::SendConfirmUnlearn().
DoLearnCost()
int32 DoLearnCost (Player *)
Definition at line 238 of file npc_professions.cpp.
 {
     return 200000;
 }
Referenced by go_evil_book_for_dummies::OnGossipHello(), npc_prof_alchemy::SendActionMenu(), npc_prof_tailor::SendActionMenu(), and go_evil_book_for_dummies::SendActionMenu().
DoLowUnlearnCost()
int32 DoLowUnlearnCost (Player * player)
Definition at line 259 of file npc_professions.cpp.
 {
     uint8 level = player->getLevel();
     if (level < 66)
         return 50000;
     else
         return 100000;
 }
References Unit::getLevel().
Referenced by npc_prof_blacksmith::SendActionMenu(), and npc_prof_blacksmith::SendConfirmUnlearn().
DoMedUnlearnCost()
int32 DoMedUnlearnCost (Player * player)
Definition at line 248 of file npc_professions.cpp.
 {
     uint8 level = player->getLevel();
     if (level < 51)
         return 250000;
     else if (level < 66)
         return 500000;
     else
         return 1000000;
 }
References Unit::getLevel().
Referenced by npc_prof_blacksmith::SendActionMenu(), and npc_prof_blacksmith::SendConfirmUnlearn().
EquippedOk()
bool EquippedOk (Player * player, uint32 spellId)
Definition at line 268 of file npc_professions.cpp.
 {
     SpellInfo const* spell = sSpellMgr->GetSpellInfo(spellId);
     if (!spell)
         return false;
     for (uint8 i = 0; i < 3; ++i)
     {
         uint32 reqSpell = spell->Effects[i].TriggerSpell;
         if (!reqSpell)
             continue;
         Item* item = nullptr;
         for (uint8 j = EQUIPMENT_SLOT_START; j < EQUIPMENT_SLOT_END; ++j)
         {
             item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, j);
             if (item && item->GetTemplate()->RequiredSpell == reqSpell)
             {
                 //player has item equipped that require specialty. Not allow to unlearn, player has to unequip first
                 LOG_DEBUG("scripts.ai", "Player attempt to unlearn spell %u, but item %u is equipped.", reqSpell, item->GetEntry());
                 return false;
             }
         }
     }
     return true;
 }
References SpellInfo::Effects, EQUIPMENT_SLOT_END, EQUIPMENT_SLOT_START, Object::GetEntry(), Player::GetItemByPos(), Item::GetTemplate(), INVENTORY_SLOT_BAG_0, LOG_DEBUG, ItemTemplate::RequiredSpell, and sSpellMgr.
Referenced by ProcessUnlearnAction().
ProcessCastaction()
void ProcessCastaction (Player * player, Creature * creature, uint32 spellId, uint32 triggeredSpellId, int32 cost)
Definition at line 392 of file npc_professions.cpp.
 {
     if ((!spellId || !player->HasSpell(spellId)) && player->HasEnoughMoney(cost))
     {
         player->CastSpell(player, triggeredSpellId, true);
         player->ModifyMoney(-cost);
         // xinef: save spells!
         player->SaveToDB(false, false);
     }
     else
         player->SendBuyError(BUY_ERR_NOT_ENOUGHT_MONEY, creature, 0, 0);
     CloseGossipMenuFor(player);
 }
References BUY_ERR_NOT_ENOUGHT_MONEY, Unit::CastSpell(), CloseGossipMenuFor(), Player::HasEnoughMoney(), Player::HasSpell(), Player::ModifyMoney(), Player::SaveToDB(), and Player::SendBuyError().
Referenced by npc_prof_alchemy::SendActionMenu(), npc_prof_blacksmith::SendActionMenu(), npc_prof_leather::SendActionMenu(), npc_prof_tailor::SendActionMenu(), and go_evil_book_for_dummies::SendActionMenu().
ProcessUnlearnAction()
void ProcessUnlearnAction (Player * player, Creature * creature, uint32 spellId, uint32 alternativeSpellId, int32 cost)
Definition at line 407 of file npc_professions.cpp.
 {
     if (EquippedOk(player, spellId))
     {
         if (player->HasEnoughMoney(cost))
         {
             player->CastSpell(player, spellId, true);
             ProfessionUnlearnSpells(player, spellId);
             player->ModifyMoney(-cost);
             if (alternativeSpellId)
                 creature->CastSpell(player, alternativeSpellId, true);
             // xinef: save spells!
             player->SaveToDB(false, false);
         }
         else
             player->SendBuyError(BUY_ERR_NOT_ENOUGHT_MONEY, creature, 0, 0);
     }
     else
         player->SendEquipError(EQUIP_ERR_CANT_DO_RIGHT_NOW, nullptr, nullptr);
     CloseGossipMenuFor(player);
 }
References BUY_ERR_NOT_ENOUGHT_MONEY, Unit::CastSpell(), CloseGossipMenuFor(), EQUIP_ERR_CANT_DO_RIGHT_NOW, EquippedOk(), Player::HasEnoughMoney(), Player::ModifyMoney(), ProfessionUnlearnSpells(), Player::SaveToDB(), Player::SendBuyError(), and Player::SendEquipError().
Referenced by npc_prof_alchemy::SendActionMenu(), npc_prof_blacksmith::SendActionMenu(), npc_prof_tailor::SendActionMenu(), and go_evil_book_for_dummies::SendActionMenu().
ProfessionUnlearnSpells()
void ProfessionUnlearnSpells (Player * player, uint32 type)
Definition at line 299 of file npc_professions.cpp.
 {
     switch (type)
     {
         case S_UNLEARN_WEAPON:                              // S_UNLEARN_WEAPON
             player->removeSpell(36125, SPEC_MASK_ALL, false);                     // Light Earthforged Blade
             player->removeSpell(36128, SPEC_MASK_ALL, false);                     // Light Emberforged Hammer
             player->removeSpell(36126, SPEC_MASK_ALL, false);                     // Light Skyforged Axe
             break;
         case S_UNLEARN_ARMOR:                               // S_UNLEARN_ARMOR
             player->removeSpell(36122, SPEC_MASK_ALL, false);                     // Earthforged Leggings
             player->removeSpell(36129, SPEC_MASK_ALL, false);                     // Heavy Earthforged Breastplate
             player->removeSpell(36130, SPEC_MASK_ALL, false);                     // Stormforged Hauberk
             player->removeSpell(34533, SPEC_MASK_ALL, false);                     // Breastplate of Kings
             player->removeSpell(34529, SPEC_MASK_ALL, false);                     // Nether Chain Shirt
             player->removeSpell(34534, SPEC_MASK_ALL, false);                     // Bulwark of Kings
             player->removeSpell(36257, SPEC_MASK_ALL, false);                     // Bulwark of the Ancient Kings
             player->removeSpell(36256, SPEC_MASK_ALL, false);                     // Embrace of the Twisting Nether
             player->removeSpell(34530, SPEC_MASK_ALL, false);                     // Twisting Nether Chain Shirt
             player->removeSpell(36124, SPEC_MASK_ALL, false);                     // Windforged Leggings
             break;
         case S_UNLEARN_HAMMER:                              // S_UNLEARN_HAMMER
             player->removeSpell(36262, SPEC_MASK_ALL, false);                     // Dragonstrike
             player->removeSpell(34546, SPEC_MASK_ALL, false);                     // Dragonmaw
             player->removeSpell(34545, SPEC_MASK_ALL, false);                     // Drakefist Hammer
             player->removeSpell(36136, SPEC_MASK_ALL, false);                     // Lavaforged Warhammer
             player->removeSpell(34547, SPEC_MASK_ALL, false);                     // Thunder
             player->removeSpell(34567, SPEC_MASK_ALL, false);                     // Deep Thunder
             player->removeSpell(36263, SPEC_MASK_ALL, false);                     // Stormherald
             player->removeSpell(36137, SPEC_MASK_ALL, false);                     // Great Earthforged Hammer
             break;
         case S_UNLEARN_AXE:                                 // S_UNLEARN_AXE
             player->removeSpell(36260, SPEC_MASK_ALL, false);                     // Wicked Edge of the Planes
             player->removeSpell(34562, SPEC_MASK_ALL, false);                     // Black Planar Edge
             player->removeSpell(34541, SPEC_MASK_ALL, false);                     // The Planar Edge
             player->removeSpell(36134, SPEC_MASK_ALL, false);                     // Stormforged Axe
             player->removeSpell(36135, SPEC_MASK_ALL, false);                     // Skyforged Great Axe
             player->removeSpell(36261, SPEC_MASK_ALL, false);                     // Bloodmoon
             player->removeSpell(34543, SPEC_MASK_ALL, false);                     // Lunar Crescent
             player->removeSpell(34544, SPEC_MASK_ALL, false);                     // Mooncleaver
             break;
         case S_UNLEARN_SWORD:                               // S_UNLEARN_SWORD
             player->removeSpell(36258, SPEC_MASK_ALL, false);                     // Blazefury
             player->removeSpell(34537, SPEC_MASK_ALL, false);                     // Blazeguard
             player->removeSpell(34535, SPEC_MASK_ALL, false);                     // Fireguard
             player->removeSpell(36131, SPEC_MASK_ALL, false);                     // Windforged Rapier
             player->removeSpell(36133, SPEC_MASK_ALL, false);                     // Stoneforged Claymore
             player->removeSpell(34538, SPEC_MASK_ALL, false);                     // Lionheart Blade
             player->removeSpell(34540, SPEC_MASK_ALL, false);                     // Lionheart Champion
             player->removeSpell(36259, SPEC_MASK_ALL, false);                     // Lionheart Executioner
             break;
         case S_UNLEARN_DRAGON:                              // S_UNLEARN_DRAGON
             player->removeSpell(36076, SPEC_MASK_ALL, false);                     // Dragonstrike Leggings
             player->removeSpell(36079, SPEC_MASK_ALL, false);                     // Golden Dragonstrike Breastplate
             player->removeSpell(35576, SPEC_MASK_ALL, false);                     // Ebon Netherscale Belt
             player->removeSpell(35577, SPEC_MASK_ALL, false);                     // Ebon Netherscale Bracers
             player->removeSpell(35575, SPEC_MASK_ALL, false);                     // Ebon Netherscale Breastplate
             player->removeSpell(35582, SPEC_MASK_ALL, false);                     // Netherstrike Belt
             player->removeSpell(35584, SPEC_MASK_ALL, false);                     // Netherstrike Bracers
             player->removeSpell(35580, SPEC_MASK_ALL, false);                     // Netherstrike Breastplate
             break;
         case S_UNLEARN_ELEMENTAL:                           // S_UNLEARN_ELEMENTAL
             player->removeSpell(36074, SPEC_MASK_ALL, false);                     // Blackstorm Leggings
             player->removeSpell(36077, SPEC_MASK_ALL, false);                     // Primalstorm Breastplate
             player->removeSpell(35590, SPEC_MASK_ALL, false);                     // Primalstrike Belt
             player->removeSpell(35591, SPEC_MASK_ALL, false);                     // Primalstrike Bracers
             player->removeSpell(35589, SPEC_MASK_ALL, false);                     // Primalstrike Vest
             break;
         case S_UNLEARN_TRIBAL:                              // S_UNLEARN_TRIBAL
             player->removeSpell(35585, SPEC_MASK_ALL, false);                     // Windhawk Hauberk
             player->removeSpell(35587, SPEC_MASK_ALL, false);                     // Windhawk Belt
             player->removeSpell(35588, SPEC_MASK_ALL, false);                     // Windhawk Bracers
             player->removeSpell(36075, SPEC_MASK_ALL, false);                     // Wildfeather Leggings
             player->removeSpell(36078, SPEC_MASK_ALL, false);                     // Living Crystal Breastplate
             break;
         case S_UNLEARN_SPELLFIRE:                           // S_UNLEARN_SPELLFIRE
             player->removeSpell(26752, SPEC_MASK_ALL, false);                     // Spellfire Belt
             player->removeSpell(26753, SPEC_MASK_ALL, false);                     // Spellfire Gloves
             player->removeSpell(26754, SPEC_MASK_ALL, false);                     // Spellfire Robe
             break;
         case S_UNLEARN_MOONCLOTH:                           // S_UNLEARN_MOONCLOTH
             player->removeSpell(26760, SPEC_MASK_ALL, false);                     // Primal Mooncloth Belt
             player->removeSpell(26761, SPEC_MASK_ALL, false);                     // Primal Mooncloth Shoulders
             player->removeSpell(26762, SPEC_MASK_ALL, false);                     // Primal Mooncloth Robe
             break;
         case S_UNLEARN_SHADOWEAVE:                          // S_UNLEARN_SHADOWEAVE
             player->removeSpell(26756, SPEC_MASK_ALL, false);                     // Frozen Shadoweave Shoulders
             player->removeSpell(26757, SPEC_MASK_ALL, false);                     // Frozen Shadoweave Boots
             player->removeSpell(26758, SPEC_MASK_ALL, false);                     // Frozen Shadoweave Robe
             break;
     }
 }
References Player::removeSpell(), S_UNLEARN_ARMOR, S_UNLEARN_AXE, S_UNLEARN_DRAGON, S_UNLEARN_ELEMENTAL, S_UNLEARN_HAMMER, S_UNLEARN_MOONCLOTH, S_UNLEARN_SHADOWEAVE, S_UNLEARN_SPELLFIRE, S_UNLEARN_SWORD, S_UNLEARN_TRIBAL, S_UNLEARN_WEAPON, and SPEC_MASK_ALL.
Referenced by ProcessUnlearnAction().