Azerotcore-wotlk: at_tyrannus_event_starter Class Reference
at_tyrannus_event_starter Class Reference
Public Member Functions
at_tyrannus_event_starter ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1540 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
at_tyrannus_event_starter()
at_tyrannus_event_starter::at_tyrannus_event_starter () inline
Definition at line 1543 of file pit_of_saron.cpp.
 : AreaTriggerScript("at_tyrannus_event_starter") { }
Member Function Documentation
OnTrigger()
bool at_tyrannus_event_starter::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1545 of file pit_of_saron.cpp.
     {
         InstanceScript* inst = player->GetInstanceScript();
         if (!inst)
             return false;
         if (inst->GetData(DATA_INSTANCE_PROGRESS) < INSTANCE_PROGRESS_AFTER_TUNNEL_WARN)
             return false;
         if (inst->GetData(DATA_GARFROST) == DONE && inst->GetData(DATA_ICK) == DONE && inst->GetData(DATA_TYRANNUS) != DONE && !inst->GetGuidData(DATA_MARTIN_OR_GORKUN_GUID))
         {
             if (Creature* c = inst->instance->SummonCreature(NPC_GORKUN_IRONSKULL_2, TSSpawnPos))
                 c->GetMotionMaster()->MovePoint(0, TSMidPos);
             inst->SetData(DATA_INSTANCE_PROGRESS, INSTANCE_PROGRESS_TYRANNUS_INTRO);
         }
         return false;
     }
References DATA_GARFROST, DATA_ICK, DATA_INSTANCE_PROGRESS, DATA_MARTIN_OR_GORKUN_GUID, DATA_TYRANNUS, DONE, ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), InstanceScript::instance, INSTANCE_PROGRESS_AFTER_TUNNEL_WARN, INSTANCE_PROGRESS_TYRANNUS_INTRO, NPC_GORKUN_IRONSKULL_2, ZoneScript::SetData(), Map::SummonCreature(), TSMidPos, and TSSpawnPos.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp