Azerotcore-wotlk: WorldPackets Namespace Reference
WorldPackets Namespace Reference
Namespaces
Strings
Classes
class Packet
class ServerPacket
class ClientPacket
class InvalidStringValueException
class InvalidUtf8ValueException
class InvalidHyperlinkException
class IllegalHyperlinkException
class String
class PacketArrayMaxCapacityException
class Array
class CompactArray
Functions
void CheckCompactArrayMaskOverflow (std::size_t index, std::size_t limit)
template<typename T >
ByteBuffer & operator<< (ByteBuffer &data, CompactArray< T > const &v)
template<typename T >
ByteBuffer & operator>> (ByteBuffer &data, CompactArray< T > &v)
Function Documentation
CheckCompactArrayMaskOverflow()
void WorldPackets::CheckCompactArrayMaskOverflow (std::size_t index, std::size_t limit)
Definition at line 67 of file PacketUtilities.cpp.
 {
     ASSERT(index < limit, "Attempted to insert " SZFMTD " values into CompactArray but it can only hold " SZFMTD, index, limit);
 }
References ASSERT, and SZFMTD.
Referenced by WorldPackets::CompactArray< T >::Insert().
operator<<()
template<typename T > ByteBuffer& WorldPackets::operator<< (ByteBuffer & data, CompactArray< T > const & v)
Definition at line 264 of file PacketUtilities.h.
     {
         uint32 mask = v.GetMask();
         data << uint32(mask);
         for (std::size_t i = 0; i < v.GetSize(); ++i)
         {
             if (mask & (1 << i))
             {
                 data << v[i];
             }
         }
         return data;
     }
References WorldPackets::CompactArray< T >::GetMask(), and WorldPackets::CompactArray< T >::GetSize().
operator>>()
template<typename T > ByteBuffer& WorldPackets::operator>> (ByteBuffer & data, CompactArray< T > & v)
Definition at line 281 of file PacketUtilities.h.
     {
         uint32 mask;
         data >> mask;
         for (std::size_t index = 0; mask != 0; mask >>= 1, ++index)
         {
             if ((mask & 1) != 0)
             {
                 v.Insert(index, data.read<T>());
             }
         }
         return data;
     }
References WorldPackets::CompactArray< T >::Insert(), and ByteBuffer::read().