Azerotcore-wotlk: SavingSystemMgr Class Reference
SavingSystemMgr Class Reference
#include <SavingSystem.h>
Static Public Member Functions
static void Update (uint32 diff)
static uint32 GetSavingCurrentValue ()
static uint32 GetSavingMaxValue ()
static void IncreaseSavingCurrentValue (uint32 inc)
static uint32 IncreaseSavingMaxValue (uint32 inc)
static void InsertToSavingSkipListIfNeeded (uint32 id)
Static Protected Attributes
static uint32 m_savingCurrentValue = 0
static uint32 m_savingMaxValueAssigned = 0
static uint32 m_savingDiffSum = 0
static std::list< uint32 > m_savingSkipList
static std::mutex _savingLock
Detailed Description
Definition at line 27 of file SavingSystem.h.
Member Function Documentation
GetSavingCurrentValue()
static uint32 SavingSystemMgr::GetSavingCurrentValue () inline static
Definition at line 32 of file SavingSystem.h.
 { return m_savingCurrentValue; } // modified only during single thread
References m_savingCurrentValue.
Referenced by Update(), and Player::Update().
GetSavingMaxValue()
static uint32 SavingSystemMgr::GetSavingMaxValue () inline static
Definition at line 33 of file SavingSystem.h.
 { return m_savingMaxValueAssigned; } // modified only during single thread
References m_savingMaxValueAssigned.
Referenced by Update().
IncreaseSavingCurrentValue()
static void SavingSystemMgr::IncreaseSavingCurrentValue (uint32 inc) inline static
Definition at line 34 of file SavingSystem.h.
 { m_savingCurrentValue += inc; } // used and modified only during single thread
References m_savingCurrentValue.
Referenced by Update().
IncreaseSavingMaxValue()
static uint32 SavingSystemMgr::IncreaseSavingMaxValue (uint32 inc) inline static
Definition at line 35 of file SavingSystem.h.
 { std::lock_guard<std::mutex> guard(_savingLock); return (m_savingMaxValueAssigned += inc); }
References _savingLock, and m_savingMaxValueAssigned.
Referenced by Player::Player(), and Player::SaveToDB().
InsertToSavingSkipListIfNeeded()
static void SavingSystemMgr::InsertToSavingSkipListIfNeeded (uint32 id) inline static
Definition at line 36 of file SavingSystem.h.
 { if (id > m_savingCurrentValue) { std::lock_guard<std::mutex> guard(_savingLock); m_savingSkipList.push_back(id); } }
References _savingLock, m_savingCurrentValue, and m_savingSkipList.
Referenced by WorldSession::LogoutPlayer(), and Player::SaveToDB().
Update()
void SavingSystemMgr::Update (uint32 diff) static
Definition at line 27 of file SavingSystem.cpp.
 {
     if (GetSavingMaxValue() > GetSavingCurrentValue())
     {
         const uint32 step = 120;
         float multiplicator;
         uint32 playerCount = sWorld->GetPlayerCount();
         if (!playerCount)
         {
             m_savingCurrentValue = 0;
             m_savingMaxValueAssigned = 0;
             m_savingDiffSum = 0;
             m_savingSkipList.clear();
             return;
         }
         if (GetSavingMaxValue() - GetSavingCurrentValue() > playerCount + m_savingSkipList.size()) // this should not happen, but just in case
             m_savingMaxValueAssigned = m_savingCurrentValue + playerCount + m_savingSkipList.size();
         if (playerCount <= 1500) // every 2min
             multiplicator = 1000.0f / playerCount;
         else if (playerCount <= 2500) // every 3min
             multiplicator = 1500.0f / playerCount;
         else if (playerCount <= 2750) // every 4min
             multiplicator = 2000.0f / playerCount;
         else if (playerCount <= 3000) // every 6min
             multiplicator = 3000.0f / playerCount;
         else if (playerCount <= 3250) // every 7min
             multiplicator = 3500.0f / playerCount;
         else // every 8min
             multiplicator = 4000.0f / playerCount;
         m_savingDiffSum += diff;
         while (m_savingDiffSum >= (uint32)(step * multiplicator))
         {
             IncreaseSavingCurrentValue(1);
             while (m_savingSkipList.size() && *(m_savingSkipList.begin()) <= GetSavingCurrentValue())
             {
                 IncreaseSavingCurrentValue(1);
                 m_savingSkipList.pop_front();
             }
             m_savingDiffSum -= (uint32)(step * multiplicator);
             if (GetSavingCurrentValue() > GetSavingMaxValue())
             {
                 m_savingDiffSum = 0;
                 break;
             }
             if (m_savingDiffSum > 60000)
                 m_savingDiffSum = 60000;
         }
     }
 }
References GetSavingCurrentValue(), GetSavingMaxValue(), IncreaseSavingCurrentValue(), m_savingCurrentValue, m_savingDiffSum, m_savingMaxValueAssigned, m_savingSkipList, and sWorld.
Referenced by World::Update().
Member Data Documentation
_savingLock
std::mutex SavingSystemMgr::_savingLock static protected
Definition at line 43 of file SavingSystem.h.
Referenced by IncreaseSavingMaxValue(), and InsertToSavingSkipListIfNeeded().
m_savingCurrentValue
uint32 SavingSystemMgr::m_savingCurrentValue = 0 static protected
Definition at line 39 of file SavingSystem.h.
Referenced by GetSavingCurrentValue(), IncreaseSavingCurrentValue(), InsertToSavingSkipListIfNeeded(), and Update().
m_savingDiffSum
uint32 SavingSystemMgr::m_savingDiffSum = 0 static protected
Definition at line 41 of file SavingSystem.h.
Referenced by Update().
m_savingMaxValueAssigned
uint32 SavingSystemMgr::m_savingMaxValueAssigned = 0 static protected
Definition at line 40 of file SavingSystem.h.
Referenced by GetSavingMaxValue(), IncreaseSavingMaxValue(), and Update().
m_savingSkipList
std::list< uint32 > SavingSystemMgr::m_savingSkipList static protected
Definition at line 42 of file SavingSystem.h.
Referenced by InsertToSavingSkipListIfNeeded(), and Update().
The documentation for this class was generated from the following files:
src/server/game/Misc/SavingSystem.h
src/server/game/Misc/SavingSystem.cpp