Azerotcore-wotlk: Acore::AIRelocationNotifier Struct Reference
Acore::AIRelocationNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
AIRelocationNotifier (Unit &unit)
template<class T >
void Visit (GridRefMgr< T > &)
void Visit (CreatureMapType &)
Public Attributes
Unit & i_unit
bool isCreature
Detailed Description
Definition at line 88 of file GridNotifiers.h.
Constructor & Destructor Documentation
AIRelocationNotifier()
Acore::AIRelocationNotifier::AIRelocationNotifier (Unit & unit) inline explicit
Definition at line 92 of file GridNotifiers.h.
 : i_unit(unit), isCreature(unit.GetTypeId() == TYPEID_UNIT)  {}
Member Function Documentation
Visit() [1/2]
void AIRelocationNotifier::Visit (CreatureMapType & m)
Definition at line 197 of file GridNotifiers.cpp.
 {
     bool self = isCreature && !((Creature*)(&i_unit))->IsMoveInLineOfSightStrictlyDisabled();
     for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Creature* c = iter->GetSource();
         // NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION does not guarantee that unit will do it itself (because distance is also checked), but screw it, it's not that important
         if (!c->isNeedNotify(NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION) && !c->IsMoveInLineOfSightStrictlyDisabled())
             CreatureUnitRelocationWorker(c, &i_unit);
         if (self)
             CreatureUnitRelocationWorker((Creature*)&i_unit, c);
     }
 }
References GridRefMgr< OBJECT >::begin(), mpq::c, CreatureUnitRelocationWorker(), GridRefMgr< OBJECT >::end(), i_unit, isCreature, NOTIFY_AI_RELOCATION, and NOTIFY_VISIBILITY_CHANGED.
Visit() [2/2]
template<class T > void Acore::AIRelocationNotifier::Visit (GridRefMgr< T > &) inline
Definition at line 93 of file GridNotifiers.h.
 {}
Member Data Documentation
i_unit
Unit& Acore::AIRelocationNotifier::i_unit
Definition at line 90 of file GridNotifiers.h.
Referenced by Visit().
isCreature
bool Acore::AIRelocationNotifier::isCreature
Definition at line 91 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp