Azerotcore-wotlk: PossessedAI Class Reference
PossessedAI Class Reference
#include <PassiveAI.h>
Public Member Functions
PossessedAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *target) override
void UpdateAI (uint32) override
void EnterEvadeMode () override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Additional Inherited Members
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 36 of file PassiveAI.h.
Constructor & Destructor Documentation
PossessedAI()
PossessedAI::PossessedAI (Creature * c) explicit
Definition at line 23 of file PassiveAI.cpp.
 : CreatureAI(c) { me->SetReactState(REACT_PASSIVE); }
References CreatureAI::me, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void PossessedAI::AttackStart (Unit * target) override virtual
Reimplemented from UnitAI.
Definition at line 32 of file PassiveAI.cpp.
 {
     me->Attack(target, true);
 }
References Unit::Attack(), and CreatureAI::me.
EnterEvadeMode()
void PossessedAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 44 of file PassiveAI.h.
 {}
JustDied()
void PossessedAI::JustDied (Unit *) override virtual
Reimplemented from CreatureAI.
Definition at line 48 of file PassiveAI.cpp.
 {
     // We died while possessed, disable our loot
     me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
 }
References CreatureAI::me, Object::RemoveFlag(), UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_LOOTABLE.
KilledUnit()
void PossessedAI::KilledUnit (Unit * victim) override virtual
Reimplemented from CreatureAI.
Definition at line 54 of file PassiveAI.cpp.
 {
     // We killed a creature, disable victim's loot
     //if (victim->GetTypeId() == TYPEID_UNIT)
     //    victim->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
 }
MoveInLineOfSight()
void PossessedAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 41 of file PassiveAI.h.
 {}
Permissible()
static int PossessedAI::Permissible (const Creature *) inline static
Definition at line 49 of file PassiveAI.h.
 { return PERMIT_BASE_IDLE;  }
References PERMIT_BASE_IDLE.
UpdateAI()
void PossessedAI::UpdateAI (uint32) override virtual
Implements UnitAI.
Definition at line 37 of file PassiveAI.cpp.
 {
     if (me->GetVictim())
     {
         if (!me->IsValidAttackTarget(me->GetVictim()))
             me->AttackStop();
         else
             DoMeleeAttackIfReady();
     }
 }
References Unit::AttackStop(), UnitAI::DoMeleeAttackIfReady(), Unit::GetVictim(), Unit::IsValidAttackTarget(), and CreatureAI::me.
The documentation for this class was generated from the following files:
src/server/game/AI/CoreAI/PassiveAI.h
src/server/game/AI/CoreAI/PassiveAI.cpp