Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_b.h File Reference
jemalloc_internal_inlines_b.h File Reference
#include "jemalloc/internal/rtree.h"
Functions
static arena_t * arena_choose_impl (tsd_t *tsd, arena_t *arena, bool internal)
static arena_t * arena_choose (tsd_t *tsd, arena_t *arena)
static arena_t * arena_ichoose (tsd_t *tsd, arena_t *arena)
static bool arena_is_auto (arena_t *arena)
JEMALLOC_ALWAYS_INLINE extent_t * iealloc (tsdn_t *tsdn, const void *ptr)
Function Documentation
arena_choose()
static arena_t* arena_choose (tsd_t * tsd, arena_t * arena) inline static
Definition at line 62 of file jemalloc_internal_inlines_b.h.
{
     return arena_choose_impl(tsd, arena, false);
 }
References arena, and arena_choose_impl().
Referenced by arena_choose_maybe_huge(), CTL_RO_NL_GEN(), tcache_alloc_large(), tcache_alloc_small(), and tsd_tcache_data_init().
arena_choose_impl()
static arena_t* arena_choose_impl (tsd_t * tsd, arena_t * arena, bool internal) inline static
Definition at line 8 of file jemalloc_internal_inlines_b.h.
{
     arena_t *ret;
     if (arena != NULL) {
         return arena;
     }
     /* During reentrancy, arena 0 is the safest bet. */
     if (unlikely(tsd_reentrancy_level_get(tsd) > 0)) {
         return arena_get(tsd_tsdn(tsd), 0, true);
     }
     ret = internal ? tsd_iarena_get(tsd) : tsd_arena_get(tsd);
     if (unlikely(ret == NULL)) {
         ret = arena_choose_hard(tsd, internal);
         assert(ret);
         if (tcache_available(tsd)) {
             tcache_t *tcache = tcache_get(tsd);
             if (tcache->arena != NULL) {
                 /* See comments in tcache_data_init().*/
                 assert(tcache->arena ==
                     arena_get(tsd_tsdn(tsd), 0, false));
                 if (tcache->arena != ret) {
                     tcache_arena_reassociate(tsd_tsdn(tsd),
                         tcache, ret);
                 }
             } else {
                 tcache_arena_associate(tsd_tsdn(tsd), tcache,
                     ret);
             }
         }
     }
     /*
      * Note that for percpu arena, if the current arena is outside of the
      * auto percpu arena range, (i.e. thread is assigned to a manually
      * managed arena), then percpu arena is skipped.
      */
     if (have_percpu_arena && PERCPU_ARENA_ENABLED(opt_percpu_arena) &&
         !internal && (arena_ind_get(ret) <
         percpu_arena_ind_limit(opt_percpu_arena)) && (ret->last_thd !=
         tsd_tsdn(tsd))) {
         unsigned ind = percpu_arena_choose();
         if (arena_ind_get(ret) != ind) {
             percpu_arena_update(tsd, ind);
             ret = tsd_arena_get(tsd);
         }
         ret->last_thd = tsd_tsdn(tsd);
     }
     return ret;
 }
References tcache_s::arena, arena, arena_choose_hard, arena_get(), arena_ind_get(), assert(), have_percpu_arena, NULL, opt_percpu_arena, percpu_arena_choose(), PERCPU_ARENA_ENABLED, percpu_arena_ind_limit(), percpu_arena_update(), ret, tcache_arena_associate, tcache_arena_reassociate, tcache_available(), tcache_get(), tsd_tsdn(), and unlikely.
Referenced by arena_choose(), and arena_ichoose().
arena_ichoose()
static arena_t* arena_ichoose (tsd_t * tsd, arena_t * arena) inline static
Definition at line 67 of file jemalloc_internal_inlines_b.h.
{
     return arena_choose_impl(tsd, arena, true);
 }
References arena, and arena_choose_impl().
Referenced by ckh_grow(), ckh_new(), ckh_shrink(), prof_lookup(), and tcache_create_explicit().
arena_is_auto()
static bool arena_is_auto (arena_t * arena) inline static
Definition at line 72 of file jemalloc_internal_inlines_b.h.
{
     assert(narenas_auto > 0);
     return (arena_ind_get(arena) < manual_arena_base);
 }
References arena, arena_ind_get(), assert(), manual_arena_base, and narenas_auto.
Referenced by arena_bin_malloc_hard(), arena_bin_slabs_full_insert(), arena_bin_slabs_full_remove(), arena_choose_maybe_huge(), arena_i_reset_destroy_helper(), arena_init_locked(), iallocztm(), idalloctm(), ipallocztm(), large_dalloc_prep_impl(), large_palloc(), and tcache_bin_flush_large().
iealloc()
JEMALLOC_ALWAYS_INLINE extent_t* iealloc (tsdn_t * tsdn, const void * ptr)
Definition at line 79 of file jemalloc_internal_inlines_b.h.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     return rtree_extent_read(tsdn, &extents_rtree, rtree_ctx,
         (uintptr_t)ptr, true);
 }
References extents_rtree, ptr(), rtree_extent_read(), and tsdn_rtree_ctx().
Referenced by arena_aalloc(), arena_dalloc_large(), arena_dalloc_large_no_tcache(), arena_dalloc_promoted(), arena_dalloc_small(), arena_prof_alloc_time_get(), arena_prof_alloc_time_set(), arena_prof_tctx_get(), arena_prof_tctx_reset(), arena_prof_tctx_set(), arena_ralloc_no_move(), arenas_lookup_ctl(), extent_merge_default(), extent_util_stats_get(), extent_util_stats_verbose_get(), large_ralloc(), tcache_bin_flush_large(), and tcache_bin_flush_small().