Azerotcore-wotlk: AreaTrigger_at_scent_larkorwi Class Reference
AreaTrigger_at_scent_larkorwi Class Reference
Public Member Functions
AreaTrigger_at_scent_larkorwi ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 173 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_scent_larkorwi()
AreaTrigger_at_scent_larkorwi::AreaTrigger_at_scent_larkorwi () inline
Definition at line 176 of file areatrigger_scripts.cpp.
         : AreaTriggerScript("at_scent_larkorwi")
     {
     }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_scent_larkorwi::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 181 of file areatrigger_scripts.cpp.
     {
         if (!player->isDead() && player->GetQuestStatus(QUEST_SCENT_OF_LARKORWI) == QUEST_STATUS_INCOMPLETE)
         {
             if (!player->FindNearestCreature(NPC_LARKORWI_MATE, 15))
                 player->SummonCreature(NPC_LARKORWI_MATE, player->GetPositionX() + 5, player->GetPositionY(), player->GetPositionZ(), 3.3f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 100000);
         }
         return false;
     }
References WorldObject::FindNearestCreature(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), Unit::isDead(), NPC_LARKORWI_MATE, QUEST_SCENT_OF_LARKORWI, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp