Azerotcore-wotlk: npc_rocknot Class Reference
npc_rocknot Class Reference
Classes
struct npc_rocknotAI
Public Member Functions
npc_rocknot ()
bool OnQuestReward (Player *, Creature *creature, Quest const *quest, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 481 of file blackrock_depths.cpp.
Constructor & Destructor Documentation
npc_rocknot()
npc_rocknot::npc_rocknot () inline
Definition at line 484 of file blackrock_depths.cpp.
 : CreatureScript("npc_rocknot") { }
Member Function Documentation
GetAI()
CreatureAI* npc_rocknot::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 516 of file blackrock_depths.cpp.
     {
         return GetBlackrockDepthsAI<npc_rocknotAI>(creature);
     }
OnQuestReward()
bool npc_rocknot::OnQuestReward (Player * , Creature * creature, Quest const * quest, uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 486 of file blackrock_depths.cpp.
     {
         InstanceScript* instance = creature->GetInstanceScript();
         if (!instance)
             return true;
         if (instance->GetData(TYPE_BAR) == DONE || instance->GetData(TYPE_BAR) == SPECIAL)
             return true;
         if (quest->GetQuestId() == QUEST_ALE)
         {
             if (instance->GetData(TYPE_BAR) != IN_PROGRESS)
                 instance->SetData(TYPE_BAR, IN_PROGRESS);
             instance->SetData(TYPE_BAR, SPECIAL);
             //keep track of amount in instance script, returns SPECIAL if amount ok and event in progress
             if (instance->GetData(TYPE_BAR) == SPECIAL)
             {
                 creature->AI()->Talk(SAY_GOT_BEER);
                 creature->CastSpell(creature, SPELL_DRUNKEN_RAGE, false);
                 if (npc_escortAI* escortAI = CAST_AI(npc_rocknot::npc_rocknotAI, creature->AI()))
                     escortAI->Start(false, false);
             }
         }
         return true;
     }
References Creature::AI(), CAST_AI, Unit::CastSpell(), DONE, ZoneScript::GetData(), WorldObject::GetInstanceScript(), Quest::GetQuestId(), IN_PROGRESS, QUEST_ALE, SAY_GOT_BEER, ZoneScript::SetData(), SPECIAL, SPELL_DRUNKEN_RAGE, CreatureAI::Talk(), and TYPE_BAR.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp