Azerotcore-wotlk: npc_ulduar_expedition_commander Class Reference
npc_ulduar_expedition_commander Class Reference
Classes
struct npc_ulduar_expedition_commanderAI
Public Member Functions
npc_ulduar_expedition_commander ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 601 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
npc_ulduar_expedition_commander()
npc_ulduar_expedition_commander::npc_ulduar_expedition_commander () inline
Definition at line 604 of file boss_razorscale.cpp.
 : CreatureScript("npc_ulduar_expedition_commander") { }
Member Function Documentation
GetAI()
CreatureAI* npc_ulduar_expedition_commander::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 659 of file boss_razorscale.cpp.
     {
         return GetUlduarAI<npc_ulduar_expedition_commanderAI>(creature);
     }
OnGossipHello()
bool npc_ulduar_expedition_commander::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 606 of file boss_razorscale.cpp.
     {
         if (!player || !creature)
             return true;
         InstanceScript* instance = creature->GetInstanceScript();
         if (!instance)
             return true;
         if (instance->GetData(TYPE_RAZORSCALE) == DONE)
             return true;
         Creature* razorscale = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(TYPE_RAZORSCALE));
         if (!razorscale || razorscale->IsInCombat())
             return true;
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, TEXT_GOSSIP_ACTION, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, 40100, creature);
         return true;
     }
References AddGossipItemFor(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::IsInCombat(), SendGossipMenuFor(), TEXT_GOSSIP_ACTION, and TYPE_RAZORSCALE.
OnGossipSelect()
bool npc_ulduar_expedition_commander::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 627 of file boss_razorscale.cpp.
     {
         if (!player || !creature)
             return true;
         if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
         {
             InstanceScript* instance = creature->GetInstanceScript();
             if (!instance || instance->GetData(TYPE_RAZORSCALE) == DONE)
                 return true;
             Creature* razorscale = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(TYPE_RAZORSCALE));
             if (razorscale && !razorscale->IsInCombat())
             {
                 // reset npcs NPC_HARPOON_FIRE_STATE
                 for (uint8 i = 0; i < 4; ++i)
                     if (Creature* hfs = ObjectAccessor::GetCreature(*creature, instance->GetGuidData(DATA_HARPOON_FIRE_STATE_1 + i)))
                         hfs->AI()->SetData(1, 0);
                 if (razorscale->AI())
                 {
                     razorscale->AI()->AttackStart(player);
                     razorscale->GetMotionMaster()->MoveIdle();
                     razorscale->GetMotionMaster()->MovePoint(POINT_RAZORSCALE_INIT, 588.0f, -178.0f, 490.0f, false, false);
                 }
             }
         }
         player->PlayerTalkClass->SendCloseGossip();
         return true;
     }
References Creature::AI(), UnitAI::AttackStart(), DATA_HARPOON_FIRE_STATE_1, DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, Unit::IsInCombat(), MotionMaster::MoveIdle(), MotionMaster::MovePoint(), Player::PlayerTalkClass, POINT_RAZORSCALE_INIT, PlayerMenu::SendCloseGossip(), and TYPE_RAZORSCALE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp