Azerotcore-wotlk: WMOGroupHeader Class Reference
WMOGroupHeader Class Reference
#include <Utils.h>
Public Member Functions
WMOGroupHeader ()
Static Public Member Functions
static WMOGroupHeader Read (FILE *stream)
Public Attributes
uint32 OffsetGroupName
uint32 OffsetDescriptiveName
uint32 Flags
Vector3 BoundingBox [2]
uint32 OffsetPortals
uint32 CountPortals
uint16 CountBatches [4]
uint8 Fogs [4]
uint32 LiquidTypeRelated
uint32 WmoId
Detailed Description
Definition at line 324 of file Utils.h.
Constructor & Destructor Documentation
WMOGroupHeader()
WMOGroupHeader::WMOGroupHeader () inline
Definition at line 327 of file Utils.h.
 {}
Member Function Documentation
Read()
WMOGroupHeader WMOGroupHeader::Read (FILE * stream) static
Definition at line 543 of file Utils.cpp.
 {
     WMOGroupHeader ret;
     int count = 0;
     count += fread(&ret.OffsetGroupName, sizeof(uint32), 1, stream);
     count += fread(&ret.OffsetDescriptiveName, sizeof(uint32), 1, stream);
     count += fread(&ret.Flags, sizeof(uint32), 1, stream);
     ret.BoundingBox[0] = Vector3::Read(stream);
     ret.BoundingBox[1] = Vector3::Read(stream);
     count += fread(&ret.OffsetPortals, sizeof(uint32), 1, stream);
     count += fread(&ret.CountPortals, sizeof(uint32), 1, stream);
     count += fread(&ret.CountBatches, sizeof(uint16), 4, stream);
     count += fread(&ret.Fogs, sizeof(uint8), 4, stream);
     count += fread(&ret.LiquidTypeRelated, sizeof(uint32), 1, stream);
     count += fread(&ret.WmoId, sizeof(uint32), 1, stream);
     if (count != 15)
         printf("WMOGroupHeader::Read: Failed to read some data expected 15, read %d\n", count);
     return ret;
 }
References count(), printf(), Vector3::Read(), and ret.
Referenced by WorldModelGroup::ReadHeader().
Member Data Documentation
BoundingBox
Vector3 WMOGroupHeader::BoundingBox[2]
Definition at line 332 of file Utils.h.
Referenced by ExtractGameobjectModels().
CountBatches
uint16 WMOGroupHeader::CountBatches[4]
Definition at line 335 of file Utils.h.
CountPortals
uint32 WMOGroupHeader::CountPortals
Definition at line 334 of file Utils.h.
Flags
uint32 WMOGroupHeader::Flags
Definition at line 331 of file Utils.h.
Referenced by ExtractGameobjectModels().
Fogs
uint8 WMOGroupHeader::Fogs[4]
Definition at line 336 of file Utils.h.
LiquidTypeRelated
uint32 WMOGroupHeader::LiquidTypeRelated
Definition at line 337 of file Utils.h.
OffsetDescriptiveName
uint32 WMOGroupHeader::OffsetDescriptiveName
Definition at line 330 of file Utils.h.
OffsetGroupName
uint32 WMOGroupHeader::OffsetGroupName
Definition at line 329 of file Utils.h.
OffsetPortals
uint32 WMOGroupHeader::OffsetPortals
Definition at line 333 of file Utils.h.
WmoId
uint32 WMOGroupHeader::WmoId
Definition at line 338 of file Utils.h.
Referenced by ExtractGameobjectModels().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp