Azerotcore-wotlk: go_the_pearl_of_the_depths Class Reference
go_the_pearl_of_the_depths Class Reference
Public Member Functions
go_the_pearl_of_the_depths ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 255 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
go_the_pearl_of_the_depths()
go_the_pearl_of_the_depths::go_the_pearl_of_the_depths () inline
Definition at line 258 of file zone_dragonblight.cpp.
 : GameObjectScript("go_the_pearl_of_the_depths") { }
Member Function Documentation
OnGossipHello()
bool go_the_pearl_of_the_depths::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 260 of file zone_dragonblight.cpp.
     {
         if(!player || !go)
             return true;
         Creature* t = player->FindNearestCreature(NPC_CONVERSING_WITH_THE_DEPTHS_TRIGGER, 10.0f, true);
         if(t && t->AI() && CAST_AI(npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, t->AI()))
             if(!CAST_AI(npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, t->AI())->running)
                 CAST_AI(npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, t->AI())->Start(player->GetGUID());
         return true;
     }
References Creature::AI(), CAST_AI, WorldObject::FindNearestCreature(), Object::GetGUID(), and NPC_CONVERSING_WITH_THE_DEPTHS_TRIGGER.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp