Azerotcore-wotlk: spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript Class Reference
spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_svalna_revive_champion_SpellScript)
void RemoveAliveTarget (std::list< WorldObject * > &targets)
void Land (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2167 of file icecrown_citadel.cpp.
Member Function Documentation
Land()
void spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land (SpellEffIndex) inline private
Definition at line 2177 of file icecrown_citadel.cpp.
         {
             Creature* caster = GetCaster()->ToCreature();
             if (!caster)
                 return;
             Position pos = caster->GetNearPosition(5.0f, 0.0f);
             pos.m_positionZ = caster->GetMap()->GetHeight(caster->GetPhaseMask(), pos.GetPositionX(), pos.GetPositionY(), caster->GetPositionZ(), true, 50.0f);
             pos.m_positionZ += 0.1f;
             caster->SendMeleeAttackStop(caster->GetVictim());
             caster->GetMotionMaster()->MoveLand(POINT_LAND, pos, 7.0f);
         }
References SpellScript::GetCaster(), Map::GetHeight(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetNearPosition(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Position::m_positionZ, MotionMaster::MoveLand(), POINT_LAND, Unit::SendMeleeAttackStop(), and Object::ToCreature().
Referenced by Register().
PrepareSpellScript()
spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::PrepareSpellScript (spell_svalna_revive_champion_SpellScript) private
Register()
void spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2190 of file icecrown_citadel.cpp.
         {
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_svalna_revive_champion_SpellScript::RemoveAliveTarget, EFFECT_0, TARGET_UNIT_DEST_AREA_ENTRY);
             OnEffectHit += SpellEffectFn(spell_svalna_revive_champion_SpellScript::Land, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
         }
References EFFECT_0, Land(), SpellScript::OnEffectHit, SpellScript::OnObjectAreaTargetSelect, RemoveAliveTarget(), SPELL_EFFECT_SCRIPT_EFFECT, SpellEffectFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_DEST_AREA_ENTRY.
RemoveAliveTarget()
void spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::RemoveAliveTarget (std::list< WorldObject * > & targets) inline private
Definition at line 2171 of file icecrown_citadel.cpp.
         {
             targets.remove_if(AliveCheck());
             Acore::Containers::RandomResize(targets, 2);
         }
References Acore::Containers::RandomResize().
Referenced by Register().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp