Azerotcore-wotlk: Acore::Impl::ChatCommands::FilteredCommandListIterator Struct Reference
Acore::Impl::ChatCommands::FilteredCommandListIterator Struct Reference
Public Member Functions
FilteredCommandListIterator (ChatSubCommandMap const &map, ChatHandler const &handler, std::string_view token)
decltype(auto) operator* () const
decltype(auto) operator-> () const
FilteredCommandListIterator & operator++ ()
operator bool () const
bool operator! () const
Private Member Functions
void _skip ()
Private Attributes
ChatHandler const & _handler
std::string_view const _token
ChatSubCommandMap::const_iterator _it
ChatSubCommandMap::const_iterator _end
Detailed Description
Definition at line 238 of file ChatCommand.cpp.
Constructor & Destructor Documentation
FilteredCommandListIterator()
Acore::Impl::ChatCommands::FilteredCommandListIterator::FilteredCommandListIterator (ChatSubCommandMap const & map, ChatHandler const & handler, std::string_view token) inline
Definition at line 241 of file ChatCommand.cpp.
                 : _handler{ handler }, _token{ token }, _it{ map.lower_bound(token) }, _end{ map.end() }
             {
                 _skip();
             }
References _skip().
Member Function Documentation
_skip()
void Acore::Impl::ChatCommands::FilteredCommandListIterator::_skip () inline private
Definition at line 259 of file ChatCommand.cpp.
             {
                 if ((_it != _end) && !StringStartsWithI(_it->first, _token))
                     _it = _end;
                 while ((_it != _end) && !_it->second.IsVisible(_handler))
                 {
                     ++_it;
                     if ((_it != _end) && !StringStartsWithI(_it->first, _token))
                         _it = _end;
                 }
             }
References _end, _handler, _it, _token, and StringStartsWithI().
Referenced by FilteredCommandListIterator(), and operator++().
operator bool()
Acore::Impl::ChatCommands::FilteredCommandListIterator::operator bool () const inline explicit
Definition at line 255 of file ChatCommand.cpp.
 { return (_it != _end); }
References _end, and _it.
operator!()
bool Acore::Impl::ChatCommands::FilteredCommandListIterator::operator! () const inline
Definition at line 256 of file ChatCommand.cpp.
 { return !static_cast<bool>(*this); }
operator*()
decltype(auto) Acore::Impl::ChatCommands::FilteredCommandListIterator::operator* () const inline
Definition at line 247 of file ChatCommand.cpp.
 { return _it.operator*(); }
References _it.
operator++()
FilteredCommandListIterator& Acore::Impl::ChatCommands::FilteredCommandListIterator::operator++ () inline
Definition at line 249 of file ChatCommand.cpp.
             {
                 ++_it;
                 _skip();
                 return *this;
             }
References _it, and _skip().
operator->()
decltype(auto) Acore::Impl::ChatCommands::FilteredCommandListIterator::operator-> () const inline
Definition at line 248 of file ChatCommand.cpp.
 { return _it.operator->(); }
References _it.
Member Data Documentation
_end
ChatSubCommandMap::const_iterator Acore::Impl::ChatCommands::FilteredCommandListIterator::_end private
Definition at line 273 of file ChatCommand.cpp.
Referenced by _skip(), and operator bool().
_handler
ChatHandler const& Acore::Impl::ChatCommands::FilteredCommandListIterator::_handler private
Definition at line 271 of file ChatCommand.cpp.
Referenced by _skip().
_it
ChatSubCommandMap::const_iterator Acore::Impl::ChatCommands::FilteredCommandListIterator::_it private
Definition at line 273 of file ChatCommand.cpp.
Referenced by _skip(), operator bool(), operator*(), operator++(), and operator->().
_token
std::string_view const Acore::Impl::ChatCommands::FilteredCommandListIterator::_token private
Definition at line 272 of file ChatCommand.cpp.
Referenced by _skip().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommand.cpp