Azerotcore-wotlk: PackedGuid Class Reference
PackedGuid Class Reference
#include <ObjectGuid.h>
Public Member Functions
PackedGuid ()
PackedGuid (uint64 guid)
PackedGuid (ObjectGuid guid)
void Set (uint64 guid)
void Set (ObjectGuid guid)
std::size_t size () const
Private Attributes
ByteBuffer _packedGuid
Friends
ByteBuffer & operator<< (ByteBuffer &buf, PackedGuid const &guid)
Detailed Description
Definition at line 264 of file ObjectGuid.h.
Constructor & Destructor Documentation
PackedGuid() [1/3]
PackedGuid::PackedGuid () inline explicit
Definition at line 269 of file ObjectGuid.h.
 : _packedGuid(PACKED_GUID_MIN_BUFFER_SIZE) { _packedGuid.appendPackGUID(0); }
References _packedGuid, and ByteBuffer::appendPackGUID().
PackedGuid() [2/3]
PackedGuid::PackedGuid (uint64 guid) inline explicit
Definition at line 270 of file ObjectGuid.h.
 : _packedGuid(PACKED_GUID_MIN_BUFFER_SIZE) { _packedGuid.appendPackGUID(guid); }
References _packedGuid, and ByteBuffer::appendPackGUID().
PackedGuid() [3/3]
PackedGuid::PackedGuid (ObjectGuid guid) inline explicit
Definition at line 271 of file ObjectGuid.h.
 : _packedGuid(PACKED_GUID_MIN_BUFFER_SIZE) { _packedGuid.appendPackGUID(guid.GetRawValue()); }
References _packedGuid, ByteBuffer::appendPackGUID(), and ObjectGuid::GetRawValue().
Member Function Documentation
Set() [1/2]
void PackedGuid::Set (ObjectGuid guid) inline
Definition at line 274 of file ObjectGuid.h.
 { _packedGuid.wpos(0); _packedGuid.appendPackGUID(guid.GetRawValue()); }
References _packedGuid, ByteBuffer::appendPackGUID(), ObjectGuid::GetRawValue(), and ByteBuffer::wpos().
Set() [2/2]
void PackedGuid::Set (uint64 guid) inline
Definition at line 273 of file ObjectGuid.h.
 { _packedGuid.wpos(0); _packedGuid.appendPackGUID(guid); }
References _packedGuid, ByteBuffer::appendPackGUID(), and ByteBuffer::wpos().
Referenced by Object::_Create().
size()
std::size_t PackedGuid::size () const inline
Definition at line 276 of file ObjectGuid.h.
 { return _packedGuid.size(); }
References _packedGuid, and ByteBuffer::size().
Referenced by AuraEffect::HandleAuraSetVehicle(), WorldSession::HandleInspectOpcode(), npc_gunship::npc_gunshipAI::JustDied(), Player::SendAutoRepeatCancel(), Player::SendComboPoints(), Player::SetClientControl(), and npc_eye_of_acherus::npc_eye_of_acherusAI::SetControl().
Friends And Related Function Documentation
operator<<
ByteBuffer& operator<< (ByteBuffer & buf, PackedGuid const & guid) friend
Definition at line 81 of file ObjectGuid.cpp.
 {
     buf.append(guid._packedGuid);
     return buf;
 }
Member Data Documentation
_packedGuid
ByteBuffer PackedGuid::_packedGuid private
Definition at line 279 of file ObjectGuid.h.
Referenced by PackedGuid(), Set(), and size().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/ObjectGuid.h