Azerotcore-wotlk: Reference< TO, FROM > Class Template Reference
Reference< TO, FROM > Class Template Reference abstract
#include <Reference.h>
Public Member Functions
Reference ()
virtual ~Reference ()=default
void link (TO *toObj, FROM *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< TO, FROM > * next ()
Reference< TO, FROM > const * next () const
Reference< TO, FROM > * prev ()
Reference< TO, FROM > const * prev () const
Reference< TO, FROM > * nocheck_next ()
Reference< TO, FROM > const * nocheck_next () const
Reference< TO, FROM > * nocheck_prev ()
Reference< TO, FROM > const * nocheck_prev () const
TO * operator-> () const
TO * getTarget () const
FROM * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
virtual void targetObjectBuildLink ()=0
virtual void targetObjectDestroyLink ()=0
virtual void sourceObjectDestroyLink ()=0
Private Attributes
TO * iRefTo
FROM * iRefFrom
Detailed Description
template<class TO, class FROM>
class Reference< TO, FROM >
Definition at line 26 of file Reference.h.
Constructor & Destructor Documentation
Reference()
template<class TO , class FROM > Reference< TO, FROM >::Reference () inline
Definition at line 41 of file Reference.h.
 { iRefTo = nullptr; iRefFrom = nullptr; }
References Reference< TO, FROM >::iRefFrom, and Reference< TO, FROM >::iRefTo.
~Reference()
template<class TO , class FROM > virtual Reference< TO, FROM >::~Reference () virtual default
Member Function Documentation
GetSource()
template<class TO , class FROM > FROM* Reference< TO, FROM >::GetSource () const inline
Definition at line 97 of file Reference.h.
 { return iRefFrom; }
References Reference< TO, FROM >::iRefFrom.
Referenced by Group::CanJoinBattlegroundQueue(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), npc_arthas::npc_arthasAI::DoAction(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), HostileRefMgr::setOnlineOfflineState(), Unit::SetPhaseMask(), HostileRefMgr::threatAssist(), Map::Update(), npc_arthas::npc_arthasAI::UpdateAI(), and HostileRefMgr::UpdateVisibility().
getTarget()
template<class TO , class FROM > TO* Reference< TO, FROM >::getTarget () const inline
Definition at line 95 of file Reference.h.
 { return iRefTo; }
References Reference< TO, FROM >::iRefTo.
Referenced by InstanceMap::CannotEnter(), BattlegroundMap::CannotEnter(), Player::GetGroup(), ThreatMgr::getHostilTarget(), Player::GetOriginalGroup(), ChaseMovementGenerator< T >::GetTarget(), FollowMovementGenerator< T >::GetTarget(), and ThreatContainer::selectNextVictim().
invalidate()
template<class TO , class FROM > void Reference< TO, FROM >::invalidate () inline
Definition at line 72 of file Reference.h.
     {
         sourceObjectDestroyLink();
         delink();
         iRefTo = nullptr;
     }
References LinkedListElement::delink(), Reference< TO, FROM >::iRefTo, and Reference< TO, FROM >::sourceObjectDestroyLink().
isValid()
template<class TO , class FROM > bool Reference< TO, FROM >::isValid () const inline
Definition at line 79 of file Reference.h.
     {
         return iRefTo != nullptr;
     }
References Reference< TO, FROM >::iRefTo.
Referenced by Group::CountTheRoll(), GridObject< T >::IsInGrid(), and Reference< TO, FROM >::link().
link()
template<class TO , class FROM > void Reference< TO, FROM >::link (TO * toObj, FROM * fromObj) inline
Definition at line 45 of file Reference.h.
     {
         ASSERT(fromObj);                                // fromObj MUST not be nullptr
         if (isValid())
         {
             unlink();
         }
         if (toObj != nullptr)
         {
             iRefTo = toObj;
             iRefFrom = fromObj;
             targetObjectBuildLink();
         }
     }
References ASSERT, Reference< TO, FROM >::iRefFrom, Reference< TO, FROM >::iRefTo, Reference< TO, FROM >::isValid(), Reference< TO, FROM >::targetObjectBuildLink(), and Reference< TO, FROM >::unlink().
Referenced by GridObject< T >::AddToGrid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::link(), Player::RemoveFromBattlegroundOrBattlefieldRaid(), Player::SetBattlegroundOrBattlefieldRaid(), Player::SetGroup(), Player::SetMap(), Player::SetOriginalGroup(), and TargetedMovementGeneratorBase::TargetedMovementGeneratorBase().
next() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* Reference< TO, FROM >::next () inline
Definition at line 84 of file Reference.h.
 { return ((Reference<TO, FROM>*) LinkedListElement::next()); }
References LinkedListElement::next().
Referenced by GroupReference::next(), and MapReference::next().
next() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* Reference< TO, FROM >::next () const inline
Definition at line 85 of file Reference.h.
 { return ((Reference<TO, FROM> const*) LinkedListElement::next()); }
References LinkedListElement::next().
nocheck_next() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* Reference< TO, FROM >::nocheck_next () inline
Definition at line 89 of file Reference.h.
 { return ((Reference<TO, FROM>*) LinkedListElement::nocheck_next()); }
References LinkedListElement::nocheck_next().
nocheck_next() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* Reference< TO, FROM >::nocheck_next () const inline
Definition at line 90 of file Reference.h.
 { return ((Reference<TO, FROM> const*) LinkedListElement::nocheck_next()); }
References LinkedListElement::nocheck_next().
nocheck_prev() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* Reference< TO, FROM >::nocheck_prev () inline
Definition at line 91 of file Reference.h.
 { return ((Reference<TO, FROM>*) LinkedListElement::nocheck_prev()); }
References LinkedListElement::nocheck_prev().
Referenced by MapReference::nocheck_prev(), and MapReference::nockeck_prev().
nocheck_prev() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* Reference< TO, FROM >::nocheck_prev () const inline
Definition at line 92 of file Reference.h.
 { return ((Reference<TO, FROM> const*) LinkedListElement::nocheck_prev()); }
References LinkedListElement::nocheck_prev().
operator->()
template<class TO , class FROM > TO* Reference< TO, FROM >::operator-> () const inline
Definition at line 94 of file Reference.h.
 { return iRefTo; }
References Reference< TO, FROM >::iRefTo.
prev() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* Reference< TO, FROM >::prev () inline
Definition at line 86 of file Reference.h.
 { return ((Reference<TO, FROM>*) LinkedListElement::prev()); }
References LinkedListElement::prev().
prev() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* Reference< TO, FROM >::prev () const inline
Definition at line 87 of file Reference.h.
 { return ((Reference<TO, FROM> const*) LinkedListElement::prev()); }
References LinkedListElement::prev().
sourceObjectDestroyLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::sourceObjectDestroyLink () protected pure virtual
Implemented in FollowerReference, MapReference, LootValidatorRef, GroupReference, GridReference< OBJECT >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, and HostileReference.
Referenced by Reference< TO, FROM >::invalidate().
targetObjectBuildLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::targetObjectBuildLink () protected pure virtual
Implemented in FollowerReference, MapReference, GroupReference, GridReference< OBJECT >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, HostileReference, and Roll.
Referenced by Reference< TO, FROM >::link().
targetObjectDestroyLink()
template<class TO , class FROM > virtual void Reference< TO, FROM >::targetObjectDestroyLink () protected pure virtual
Implemented in FollowerReference, MapReference, LootValidatorRef, GroupReference, GridReference< OBJECT >, GridReference< T >, GridReference< NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > >, and HostileReference.
Referenced by Reference< TO, FROM >::unlink().
unlink()
template<class TO , class FROM > void Reference< TO, FROM >::unlink () inline
Definition at line 62 of file Reference.h.
     {
         targetObjectDestroyLink();
         delink();
         iRefTo = nullptr;
         iRefFrom = nullptr;
     }
References LinkedListElement::delink(), Reference< TO, FROM >::iRefFrom, Reference< TO, FROM >::iRefTo, and Reference< TO, FROM >::targetObjectDestroyLink().
Referenced by Reference< TO, FROM >::link(), Player::RemoveFromBattlegroundOrBattlefieldRaid(), GridObject< T >::RemoveFromGrid(), Player::ResetMap(), Player::SetBattlegroundOrBattlefieldRaid(), Player::SetGroup(), and Player::SetOriginalGroup().
Member Data Documentation
iRefFrom
template<class TO , class FROM > FROM* Reference< TO, FROM >::iRefFrom private
Definition at line 30 of file Reference.h.
Referenced by Reference< TO, FROM >::GetSource(), Reference< TO, FROM >::link(), Reference< TO, FROM >::Reference(), and Reference< TO, FROM >::unlink().
iRefTo
template<class TO , class FROM > TO* Reference< TO, FROM >::iRefTo private
Definition at line 29 of file Reference.h.
Referenced by Reference< TO, FROM >::getTarget(), Reference< TO, FROM >::invalidate(), Reference< TO, FROM >::isValid(), Reference< TO, FROM >::link(), Reference< TO, FROM >::operator->(), Reference< TO, FROM >::Reference(), and Reference< TO, FROM >::unlink().
The documentation for this class was generated from the following file:
src/common/Dynamic/LinkedReference/Reference.h