Azerotcore-wotlk: LockedQueue< T, StorageType > Class Template Reference
LockedQueue< T, StorageType > Class Template Reference
#include <LockedQueue.h>
Public Member Functions
LockedQueue ()
Create a LockedQueue.
virtual ~LockedQueue ()
Destroy a LockedQueue.
void add (const T &item)
Adds an item to the queue.
template<class Iterator >
void readd (Iterator begin, Iterator end)
Adds items back to front of the queue.
bool next (T &result)
Gets the next result in the queue, if any.
template<class Checker >
bool next (T &result, Checker &check)
T & peek (bool autoUnlock=false)
Peeks at the top of the queue. Check if the queue is empty before calling! Remember to unlock after use if autoUnlock == false.
void cancel ()
Cancels the queue.
bool cancelled ()
Checks if the queue is cancelled.
void lock ()
Locks the queue for access.
void unlock ()
Unlocks the queue.
void pop_front ()
! Calls pop_front of the queue
bool empty ()
! Checks if we're empty or not with locks held
Private Attributes
std::mutex _lock
Lock access to the queue.
StorageType _queue
Storage backing the queue.
volatile bool _canceled
Cancellation flag.
Detailed Description
template<class T, typename StorageType = std::deque<T>>
class LockedQueue< T, StorageType >
Definition at line 25 of file LockedQueue.h.
Constructor & Destructor Documentation
LockedQueue()
template<class T , typename StorageType = std::deque<T>> LockedQueue< T, StorageType >::LockedQueue () inline
Create a LockedQueue.
Definition at line 39 of file LockedQueue.h.
         : _canceled(false)
     {
     }
~LockedQueue()
template<class T , typename StorageType = std::deque<T>> virtual LockedQueue< T, StorageType >::~LockedQueue () inline virtual
Destroy a LockedQueue.
Definition at line 45 of file LockedQueue.h.
     {
     }
Member Function Documentation
add()
template<class T , typename StorageType = std::deque<T>> void LockedQueue< T, StorageType >::add (const T & item) inline
Adds an item to the queue.
Definition at line 50 of file LockedQueue.h.
     {
         lock();
         _queue.push_back(item);
         unlock();
     }
References LockedQueue< T, StorageType >::_queue, LockedQueue< T, StorageType >::lock(), and LockedQueue< T, StorageType >::unlock().
Referenced by World::AddSession(), World::QueueCliCommand(), and WorldSession::QueuePacket().
cancel()
template<class T , typename StorageType = std::deque<T>> void LockedQueue< T, StorageType >::cancel () inline
Cancels the queue.
Definition at line 119 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         _canceled = true;
     }
References LockedQueue< T, StorageType >::_canceled, LockedQueue< T, StorageType >::_lock, and LockedQueue< T, StorageType >::lock().
cancelled()
template<class T , typename StorageType = std::deque<T>> bool LockedQueue< T, StorageType >::cancelled () inline
Checks if the queue is cancelled.
Definition at line 127 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         return _canceled;
     }
References LockedQueue< T, StorageType >::_canceled, LockedQueue< T, StorageType >::_lock, and LockedQueue< T, StorageType >::lock().
empty()
template<class T , typename StorageType = std::deque<T>> bool LockedQueue< T, StorageType >::empty () inline
! Checks if we're empty or not with locks held
Definition at line 153 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         return _queue.empty();
     }
References LockedQueue< T, StorageType >::_lock, LockedQueue< T, StorageType >::_queue, and LockedQueue< T, StorageType >::lock().
lock()
template<class T , typename StorageType = std::deque<T>> void LockedQueue< T, StorageType >::lock () inline
Locks the queue for access.
Definition at line 134 of file LockedQueue.h.
     {
         this->_lock.lock();
     }
Referenced by LockedQueue< T, StorageType >::add(), LockedQueue< T, StorageType >::cancel(), LockedQueue< T, StorageType >::cancelled(), LockedQueue< T, StorageType >::empty(), LockedQueue< T, StorageType >::next(), LockedQueue< T, StorageType >::peek(), LockedQueue< T, StorageType >::pop_front(), and LockedQueue< T, StorageType >::readd().
next() [1/2]
template<class T , typename StorageType = std::deque<T>> bool LockedQueue< T, StorageType >::next (T & result) inline
Gets the next result in the queue, if any.
Definition at line 68 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         if (_queue.empty())
         {
             return false;
         }
         result = _queue.front();
         _queue.pop_front();
         return true;
     }
References LockedQueue< T, StorageType >::_lock, LockedQueue< T, StorageType >::_queue, and LockedQueue< T, StorageType >::lock().
Referenced by World::ProcessCliCommands(), WorldSession::Update(), World::UpdateSessions(), World::~World(), and WorldSession::~WorldSession().
next() [2/2]
template<class T , typename StorageType = std::deque<T>> template<class Checker > bool LockedQueue< T, StorageType >::next (T & result, Checker & check) inline
Definition at line 84 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         if (_queue.empty())
         {
             return false;
         }
         result = _queue.front();
         if (!check.Process(result))
         {
             return false;
         }
         _queue.pop_front();
         return true;
     }
References LockedQueue< T, StorageType >::_lock, LockedQueue< T, StorageType >::_queue, and LockedQueue< T, StorageType >::lock().
peek()
template<class T , typename StorageType = std::deque<T>> T& LockedQueue< T, StorageType >::peek (bool autoUnlock = false) inline
Peeks at the top of the queue. Check if the queue is empty before calling! Remember to unlock after use if autoUnlock == false.
Definition at line 104 of file LockedQueue.h.
     {
         lock();
         T& result = _queue.front();
         if (autoUnlock)
         {
             unlock();
         }
         return result;
     }
References LockedQueue< T, StorageType >::_queue, LockedQueue< T, StorageType >::lock(), and LockedQueue< T, StorageType >::unlock().
pop_front()
template<class T , typename StorageType = std::deque<T>> void LockedQueue< T, StorageType >::pop_front () inline
! Calls pop_front of the queue
Definition at line 146 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         _queue.pop_front();
     }
References LockedQueue< T, StorageType >::_lock, LockedQueue< T, StorageType >::_queue, and LockedQueue< T, StorageType >::lock().
readd()
template<class T , typename StorageType = std::deque<T>> template<class Iterator > void LockedQueue< T, StorageType >::readd (Iterator begin, Iterator end) inline
Adds items back to front of the queue.
Definition at line 61 of file LockedQueue.h.
     {
         std::lock_guard<std::mutex> lock(_lock);
         _queue.insert(_queue.begin(), begin, end);
     }
References LockedQueue< T, StorageType >::_lock, LockedQueue< T, StorageType >::_queue, and LockedQueue< T, StorageType >::lock().
Referenced by WorldSession::Update().
unlock()
template<class T , typename StorageType = std::deque<T>> void LockedQueue< T, StorageType >::unlock () inline
Unlocks the queue.
Definition at line 140 of file LockedQueue.h.
     {
         this->_lock.unlock();
     }
Referenced by LockedQueue< T, StorageType >::add(), and LockedQueue< T, StorageType >::peek().
Member Data Documentation
_canceled
template<class T , typename StorageType = std::deque<T>> volatile bool LockedQueue< T, StorageType >::_canceled private
Cancellation flag.
Definition at line 34 of file LockedQueue.h.
Referenced by LockedQueue< T, StorageType >::cancel(), and LockedQueue< T, StorageType >::cancelled().
_lock
template<class T , typename StorageType = std::deque<T>> std::mutex LockedQueue< T, StorageType >::_lock private
Lock access to the queue.
Definition at line 28 of file LockedQueue.h.
Referenced by LockedQueue< T, StorageType >::cancel(), LockedQueue< T, StorageType >::cancelled(), LockedQueue< T, StorageType >::empty(), LockedQueue< T, StorageType >::next(), LockedQueue< T, StorageType >::pop_front(), and LockedQueue< T, StorageType >::readd().
_queue
template<class T , typename StorageType = std::deque<T>> StorageType LockedQueue< T, StorageType >::_queue private
Storage backing the queue.
Definition at line 31 of file LockedQueue.h.
Referenced by LockedQueue< T, StorageType >::add(), LockedQueue< T, StorageType >::empty(), LockedQueue< T, StorageType >::next(), LockedQueue< T, StorageType >::peek(), LockedQueue< T, StorageType >::pop_front(), and LockedQueue< T, StorageType >::readd().
The documentation for this class was generated from the following file:
src/common/Threading/LockedQueue.h