Azerotcore-wotlk: boss_thorim_sif::boss_thorim_sifAI Struct Reference
boss_thorim_sif::boss_thorim_sifAI Struct Reference
Public Member Functions
boss_thorim_sifAI (Creature *pCreature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void Reset () override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _allowCast
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 837 of file boss_thorim.cpp.
Constructor & Destructor Documentation
boss_thorim_sifAI()
boss_thorim_sif::boss_thorim_sifAI::boss_thorim_sifAI (Creature * pCreature) inline
Definition at line 839 of file boss_thorim.cpp.
 : ScriptedAI(pCreature) { }
Member Function Documentation
AttackStart()
void boss_thorim_sif::boss_thorim_sifAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 842 of file boss_thorim.cpp.
 {}
DoAction()
void boss_thorim_sif::boss_thorim_sifAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 854 of file boss_thorim.cpp.
         {
             if (param == ACTION_SIF_START_TALK)
                 events.ScheduleEvent(EVENT_SIF_START_TALK, 9000);
             else if (param == ACTION_SIF_START_DOMINION)
             {
                 if (me->GetInstanceScript())
                     if (Creature* cr = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_THORIM)))
                         me->CastSpell(cr, SPELL_TOUCH_OF_DOMINION, false);
                 events.ScheduleEvent(EVENT_SIF_FINISH_DOMINION, 150000);
             }
             else if (param == ACTION_SIF_JOIN_FIGHT)
             {
                 me->InterruptNonMeleeSpells(false);
                 events.ScheduleEvent(EVENT_SIF_JOIN_TALK, 9000);
                 events.CancelEvent(EVENT_SIF_START_TALK);
                 events.CancelEvent(EVENT_SIF_FINISH_DOMINION);
             }
             else if (param == ACTION_SIF_TRANSFORM)
             {
                 me->CastSpell(me, SPELL_SIF_TRANSFORM, true);
                 me->DespawnOrUnsummon(5000);
                 events.Reset();
                 _allowCast = false;
             }
         }
References _allowCast, ACTION_SIF_JOIN_FIGHT, ACTION_SIF_START_DOMINION, ACTION_SIF_START_TALK, ACTION_SIF_TRANSFORM, Unit::CastSpell(), Creature::DespawnOrUnsummon(), EVENT_SIF_FINISH_DOMINION, EVENT_SIF_JOIN_TALK, EVENT_SIF_START_TALK, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, SPELL_SIF_TRANSFORM, SPELL_TOUCH_OF_DOMINION, and TYPE_THORIM.
MoveInLineOfSight()
void boss_thorim_sif::boss_thorim_sifAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 841 of file boss_thorim.cpp.
 {}
Reset()
void boss_thorim_sif::boss_thorim_sifAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 847 of file boss_thorim.cpp.
         {
             events.Reset();
             me->SetReactState(REACT_PASSIVE);
             _allowCast = false;
         }
References _allowCast, ScriptedAI::me, REACT_PASSIVE, and Creature::SetReactState().
UpdateAI()
void boss_thorim_sif::boss_thorim_sifAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 882 of file boss_thorim.cpp.
         {
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SIF_FINISH_DOMINION:
                     me->PlayDirectSound(SOUND_SIF_DESPAWN);
                     me->Yell("This pathetic morons are harmless. Relive my station, dispose of them!", LANG_UNIVERSAL);
                     me->DespawnOrUnsummon(5000);
                     break;
                 case EVENT_SIF_START_TALK:
                     me->Yell("Thorim, my lord, why else would these invaders have come into your sanctum but to slay you? They must be stopped!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_SIF_START);
                     break;
                 case EVENT_SIF_JOIN_TALK:
                     me->PlayDirectSound(SOUND_SIF_EVENT);
                     me->Yell("Impossible! Lord Thorim, I will bring your foes a frigid death!", LANG_UNIVERSAL);
                     events.ScheduleEvent(EVENT_SIF_FROST_NOVA_START, 1000);
                     events.ScheduleEvent(EVENT_SIF_FROSTBOLT_VALLEY, 11000);
                     events.ScheduleEvent(EVENT_SIF_BLIZZARD, 15000);
                     break;
                 case EVENT_SIF_FROSTBOLT_VALLEY:
                     me->CastSpell(me, SPELL_FROSTBOLT_VALLEY, false);
                     events.RepeatEvent(13000);
                     return;
                 case EVENT_SIF_BLIZZARD:
                     me->SummonCreature(NPC_SIF_BLIZZARD, 2108.7f, -280.04f, 419.42f, 0, TEMPSUMMON_TIMED_DESPAWN, 30000);
                     events.RepeatEvent(30000);
                     return;
                 case EVENT_SIF_FROST_NOVA_START:
                     me->NearTeleportTo(2108 + urand(0, 42), -238 - irand(0, 46), 420.02f, me->GetAngle(&Middle));
                     events.RepeatEvent(20000);
                     events.DelayEvents(5001);
                     events.ScheduleEvent(EVENT_SIF_FROST_NOVA_CAST, 2500);
                     _allowCast = false;
                     return;
                 case EVENT_SIF_FROST_NOVA_CAST:
                     _allowCast = true;
                     me->CastSpell(me, SPELL_FROST_NOVA, false);
                     return;
             }
             // has casting check before event select (return in events)
             if (_allowCast)
                 if (Player* target = SelectTargetFromPlayerList(70))
                 {
                     me->CastSpell(target, SPELL_FROSTBOLT, false);
                     me->StopMoving();
                 }
         }
References _allowCast, Unit::CastSpell(), Creature::DespawnOrUnsummon(), diff(), EVENT_SIF_BLIZZARD, EVENT_SIF_FINISH_DOMINION, EVENT_SIF_FROST_NOVA_CAST, EVENT_SIF_FROST_NOVA_START, EVENT_SIF_FROSTBOLT_VALLEY, EVENT_SIF_JOIN_TALK, EVENT_SIF_START_TALK, Position::GetAngle(), Unit::HasUnitState(), irand(), LANG_UNIVERSAL, ScriptedAI::me, Middle, Unit::NearTeleportTo(), NPC_SIF_BLIZZARD, WorldObject::PlayDirectSound(), ScriptedAI::SelectTargetFromPlayerList(), SOUND_SIF_DESPAWN, SOUND_SIF_EVENT, SOUND_SIF_START, SPELL_FROST_NOVA, SPELL_FROSTBOLT, SPELL_FROSTBOLT_VALLEY, Unit::StopMoving(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, urand(), and Unit::Yell().
Member Data Documentation
_allowCast
bool boss_thorim_sif::boss_thorim_sifAI::_allowCast
Definition at line 844 of file boss_thorim.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
events
EventMap boss_thorim_sif::boss_thorim_sifAI::events
Definition at line 845 of file boss_thorim.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp