Azerotcore-wotlk: IntervalTimer Struct Reference
IntervalTimer Struct Reference
#include <Timer.h>
Public Member Functions
IntervalTimer ()
void Update (time_t diff)
bool Passed ()
void Reset ()
void SetCurrent (time_t current)
void SetInterval (time_t interval)
time_t GetInterval () const
time_t GetCurrent () const
Private Attributes
time_t _interval {0}
time_t _current {0}
Detailed Description
Definition at line 66 of file Timer.h.
Constructor & Destructor Documentation
IntervalTimer()
IntervalTimer::IntervalTimer () inline
Definition at line 69 of file Timer.h.
     {
     }
Member Function Documentation
GetCurrent()
time_t IntervalTimer::GetCurrent () const inline
Definition at line 111 of file Timer.h.
     {
         return _current;
     }
References _current.
Referenced by World::GetNextWhoListUpdateDelaySecs(), and Weather::Update().
GetInterval()
time_t IntervalTimer::GetInterval () const inline
Definition at line 106 of file Timer.h.
     {
         return _interval;
     }
References _interval.
Referenced by World::GetNextWhoListUpdateDelaySecs(), and Weather::Weather().
Passed()
bool IntervalTimer::Passed () inline
Definition at line 83 of file Timer.h.
     {
         return _current >= _interval;
     }
References _current, and _interval.
Referenced by Weather::Update().
Reset()
void IntervalTimer::Reset () inline
Definition at line 88 of file Timer.h.
     {
         if (_current >= _interval)
         {
             _current %= _interval;
         }
     }
References _current, and _interval.
Referenced by World::ForceGameEventUpdate(), World::LoadConfigSettings(), MapMgr::SetMapUpdateInterval(), Weather::Update(), and World::Update().
SetCurrent()
void IntervalTimer::SetCurrent (time_t current) inline
Definition at line 96 of file Timer.h.
     {
         _current = current;
     }
References _current.
Referenced by World::RemoveOldCorpses(), World::SetInitialWorldSettings(), Weather::Update(), World::Update(), and MapMgr::Update().
SetInterval()
void IntervalTimer::SetInterval (time_t interval) inline
Definition at line 101 of file Timer.h.
     {
         _interval = interval;
     }
References _interval.
Referenced by World::ForceGameEventUpdate(), World::LoadConfigSettings(), MapMgr::MapMgr(), World::SetInitialWorldSettings(), MapMgr::SetMapUpdateInterval(), World::Update(), and Weather::Weather().
Update()
void IntervalTimer::Update (time_t diff) inline
Definition at line 74 of file Timer.h.
     {
         _current += diff;
         if (_current < 0)
         {
             _current = 0;
         }
     }
References _current, and diff().
Referenced by Weather::Update(), and World::Update().
Member Data Documentation
_current
time_t IntervalTimer::_current {0} private
Definition at line 118 of file Timer.h.
Referenced by GetCurrent(), Passed(), Reset(), SetCurrent(), and Update().
_interval
time_t IntervalTimer::_interval {0} private
Definition at line 117 of file Timer.h.
Referenced by GetInterval(), Passed(), Reset(), and SetInterval().
The documentation for this struct was generated from the following file:
src/common/Utilities/Timer.h