Azerotcore-wotlk: instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript Struct Reference
instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript Struct Reference
Public Member Functions
instance_blackfathom_deeps_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounters [MAX_ENCOUNTERS]
ObjectGuid _akumaiPortalGUID
uint8 _requiredDeaths
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 32 of file instance_blackfathom_deeps.cpp.
Constructor & Destructor Documentation
instance_blackfathom_deeps_InstanceMapScript()
instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::instance_blackfathom_deeps_InstanceMapScript (Map * map) inline
Definition at line 34 of file instance_blackfathom_deeps.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetSaveData()
std::string instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 108 of file instance_blackfathom_deeps.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "B L " << _encounters[0] << ' ' << _encounters[1] << ' ' << _encounters[2] << ' ' << _encounters[3] << ' ' << _encounters[4] << ' ' << _encounters[5];
             return saveStream.str();
         }
References _encounters.
Initialize()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 36 of file instance_blackfathom_deeps.cpp.
         {
             memset(&_encounters, 0, sizeof(_encounters));
             _requiredDeaths = 0;
         }
References _encounters, _requiredDeaths, and memset.
Load()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 115 of file instance_blackfathom_deeps.cpp.
         {
             if (!in)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'B' && dataHead2 == 'L')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     loadStream >> _encounters[i];
                     if (_encounters[i] == IN_PROGRESS)
                         _encounters[i] = NOT_STARTED;
                 }
             }
         }
References _encounters, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnCreatureCreate()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 42 of file instance_blackfathom_deeps.cpp.
         {
             if (creature->IsSummon() && (creature->GetEntry() == NPC_BARBED_CRUSTACEAN || creature->GetEntry() == NPC_AKU_MAI_SERVANT ||
                                          creature->GetEntry() == NPC_MURKSHALLOW_SOFTSHELL || creature->GetEntry() == NPC_AKU_MAI_SNAPJAW))
                 ++_requiredDeaths;
         }
References _requiredDeaths, Object::GetEntry(), Unit::IsSummon(), NPC_AKU_MAI_SERVANT, NPC_AKU_MAI_SNAPJAW, NPC_BARBED_CRUSTACEAN, and NPC_MURKSHALLOW_SOFTSHELL.
OnGameObjectCreate()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 60 of file instance_blackfathom_deeps.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_FIRE_OF_AKU_MAI_1:
                 case GO_FIRE_OF_AKU_MAI_2:
                 case GO_FIRE_OF_AKU_MAI_3:
                 case GO_FIRE_OF_AKU_MAI_4:
                     if (_encounters[gameobject->GetEntry() - GO_FIRE_OF_AKU_MAI_1 + 1] == DONE)
                     {
                         gameobject->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                         gameobject->SetGoState(GO_STATE_ACTIVE);
                     }
                     break;
                 case GO_SHRINE_OF_GELIHAST:
                     if (_encounters[TYPE_GELIHAST] == DONE)
                         gameobject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case GO_ALTAR_OF_THE_DEEPS:
                     if (_encounters[TYPE_AKU_MAI] == DONE)
                         gameobject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case GO_AKU_MAI_DOOR:
                     if (_encounters[TYPE_FIRE1] == DONE && _encounters[TYPE_FIRE2] == DONE && _encounters[TYPE_FIRE3] == DONE && _encounters[TYPE_FIRE4] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     _akumaiPortalGUID = gameobject->GetGUID();
                     break;
             }
         }
References _akumaiPortalGUID, _encounters, DONE, ObjectGuid::Empty, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetGUID(), GO_AKU_MAI_DOOR, GO_ALTAR_OF_THE_DEEPS, GO_FIRE_OF_AKU_MAI_1, GO_FIRE_OF_AKU_MAI_2, GO_FIRE_OF_AKU_MAI_3, GO_FIRE_OF_AKU_MAI_4, GO_FLAG_IN_USE, GO_FLAG_NOT_SELECTABLE, GO_SHRINE_OF_GELIHAST, GO_STATE_ACTIVE, InstanceScript::HandleGameObject(), Object::RemoveFlag(), Object::SetFlag(), GameObject::SetGoState(), TYPE_AKU_MAI, TYPE_FIRE1, TYPE_FIRE2, TYPE_FIRE3, TYPE_FIRE4, and TYPE_GELIHAST.
OnUnitDeath()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 49 of file instance_blackfathom_deeps.cpp.
         {
             if (unit->IsSummon() && (unit->GetEntry() == NPC_BARBED_CRUSTACEAN || unit->GetEntry() == NPC_AKU_MAI_SERVANT ||
                                      unit->GetEntry() == NPC_MURKSHALLOW_SOFTSHELL || unit->GetEntry() == NPC_AKU_MAI_SNAPJAW))
             {
                 if (--_requiredDeaths == 0)
                     if (_encounters[TYPE_FIRE1] == DONE && _encounters[TYPE_FIRE2] == DONE && _encounters[TYPE_FIRE3] == DONE && _encounters[TYPE_FIRE4] == DONE)
                         HandleGameObject(_akumaiPortalGUID, true);
             }
         }
References _akumaiPortalGUID, _encounters, _requiredDeaths, DONE, Object::GetEntry(), InstanceScript::HandleGameObject(), Unit::IsSummon(), NPC_AKU_MAI_SERVANT, NPC_AKU_MAI_SNAPJAW, NPC_BARBED_CRUSTACEAN, NPC_MURKSHALLOW_SOFTSHELL, TYPE_FIRE1, TYPE_FIRE2, TYPE_FIRE3, and TYPE_FIRE4.
SetData()
void instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 90 of file instance_blackfathom_deeps.cpp.
         {
             switch (type)
             {
                 case TYPE_GELIHAST:
                 case TYPE_FIRE1:
                 case TYPE_FIRE2:
                 case TYPE_FIRE3:
                 case TYPE_FIRE4:
                 case TYPE_AKU_MAI:
                     _encounters[type] = data;
                     break;
             }
             if (data == DONE)
                 SaveToDB();
         }
References _encounters, DONE, InstanceScript::SaveToDB(), TYPE_AKU_MAI, TYPE_FIRE1, TYPE_FIRE2, TYPE_FIRE3, TYPE_FIRE4, and TYPE_GELIHAST.
Member Data Documentation
_akumaiPortalGUID
ObjectGuid instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_akumaiPortalGUID private
Definition at line 136 of file instance_blackfathom_deeps.cpp.
Referenced by OnGameObjectCreate(), and OnUnitDeath().
_encounters
uint32 instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Definition at line 135 of file instance_blackfathom_deeps.cpp.
Referenced by GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), OnUnitDeath(), and SetData().
_requiredDeaths
uint8 instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::_requiredDeaths private
Definition at line 137 of file instance_blackfathom_deeps.cpp.
Referenced by Initialize(), OnCreatureCreate(), and OnUnitDeath().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/BlackfathomDeeps/instance_blackfathom_deeps.cpp