Azerotcore-wotlk: deps/mysqllite/include/mysql/client_plugin.h File Reference
client_plugin.h File Reference
#include <stdarg.h>
#include <stdlib.h>
#include <mysql/plugin_auth_common.h>
Classes
struct st_mysql_client_plugin
struct st_mysql_client_plugin_AUTHENTICATION
Macros
#define MYSQL_CLIENT_PLUGIN_INCLUDED
#define MYSQL_CLIENT_reserved1 0
#define MYSQL_CLIENT_reserved2 1
#define MYSQL_CLIENT_AUTHENTICATION_PLUGIN 2
#define MYSQL_CLIENT_AUTHENTICATION_PLUGIN_INTERFACE_VERSION 0x0100
#define MYSQL_CLIENT_MAX_PLUGINS 3
#define mysql_declare_client_plugin(X)
#define mysql_end_client_plugin }
#define MYSQL_CLIENT_PLUGIN_HEADER
Functions
struct st_mysql_client_plugin * mysql_load_plugin (struct st_mysql *mysql, const char *name, int type, int argc,...)
struct st_mysql_client_plugin * mysql_load_plugin_v (struct st_mysql *mysql, const char *name, int type, int argc, va_list args)
struct st_mysql_client_plugin * mysql_client_find_plugin (struct st_mysql *mysql, const char *name, int type)
struct st_mysql_client_plugin * mysql_client_register_plugin (struct st_mysql *mysql, struct st_mysql_client_plugin *plugin)
int STDCALL mysql_plugin_options (struct st_mysql_client_plugin *plugin, const char *option, const void *value)
Detailed Description
MySQL Client Plugin API
This file defines the API for plugins that work on the client side
Definition in file client_plugin.h.
Macro Definition Documentation
MYSQL_CLIENT_AUTHENTICATION_PLUGIN
#define MYSQL_CLIENT_AUTHENTICATION_PLUGIN 2
Definition at line 34 of file client_plugin.h.
MYSQL_CLIENT_AUTHENTICATION_PLUGIN_INTERFACE_VERSION
#define MYSQL_CLIENT_AUTHENTICATION_PLUGIN_INTERFACE_VERSION 0x0100
Definition at line 36 of file client_plugin.h.
MYSQL_CLIENT_MAX_PLUGINS
#define MYSQL_CLIENT_MAX_PLUGINS 3
Definition at line 38 of file client_plugin.h.
MYSQL_CLIENT_PLUGIN_HEADER
#define MYSQL_CLIENT_PLUGIN_HEADER
Value:
  int type;                                             \
  unsigned int interface_version;                       \
  const char *name;                                     \
  const char *author;                                   \
  const char *desc;                                     \
  unsigned int version[3];                              \
  const char *license;                                  \
  void *mysql_api;                                      \
  int (*init)(char *, size_t, int, va_list);            \
  int (*deinit)();                                      \
  int (*options)(const char *option, const void *);
Definition at line 48 of file client_plugin.h.
MYSQL_CLIENT_PLUGIN_INCLUDED
#define MYSQL_CLIENT_PLUGIN_INCLUDED
Definition at line 24 of file client_plugin.h.
MYSQL_CLIENT_reserved1
#define MYSQL_CLIENT_reserved1 0
Definition at line 32 of file client_plugin.h.
MYSQL_CLIENT_reserved2
#define MYSQL_CLIENT_reserved2 1
Definition at line 33 of file client_plugin.h.
mysql_declare_client_plugin
#define mysql_declare_client_plugin (X)
Value:
     MYSQL_PLUGIN_EXPORT struct st_mysql_client_plugin_ ## X        \
        _mysql_client_plugin_declaration_ = {   \
          MYSQL_CLIENT_ ## X ## _PLUGIN,        \
          MYSQL_CLIENT_ ## X ## _PLUGIN_INTERFACE_VERSION,
Definition at line 40 of file client_plugin.h.
mysql_end_client_plugin
#define mysql_end_client_plugin }
Definition at line 45 of file client_plugin.h.
Function Documentation
mysql_client_find_plugin()
struct st_mysql_client_plugin* mysql_client_find_plugin (struct st_mysql * mysql, const char * name, int type)
finds an already loaded plugin by name, or loads it, if necessary
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded
Return values
a pointer to the plugin, or NULL in case of a failure
Definition at line 432 of file client_plugin.c.
 {
   struct st_mysql_client_plugin *p;
   DBUG_ENTER ("mysql_client_find_plugin");
   DBUG_PRINT ("entry", ("name=%s, type=%d", name, type));
   if (is_not_initialized(mysql, name))
     DBUG_RETURN (NULL);
   if (type < 0 || type >= MYSQL_CLIENT_MAX_PLUGINS)
   {
     set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD, unknown_sqlstate,
                              ER(CR_AUTH_PLUGIN_CANNOT_LOAD), name,
                              "invalid type");
   }
   if ((p= find_plugin(name, type)))
   {
     DBUG_PRINT ("leave", ("found %p", p));
     DBUG_RETURN (p);
   }
   /* not found, load it */
   p= mysql_load_plugin(mysql, name, type, 0);
   DBUG_PRINT ("leave", ("loaded %p", p));
   DBUG_RETURN (p);
 }
References CR_AUTH_PLUGIN_CANNOT_LOAD, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, find_plugin(), is_not_initialized(), MYSQL_CLIENT_MAX_PLUGINS, mysql_load_plugin(), name, NULL, set_mysql_extended_error(), and unknown_sqlstate.
Referenced by run_plugin_auth().
mysql_client_register_plugin()
struct st_mysql_client_plugin* mysql_client_register_plugin (struct st_mysql * mysql, struct st_mysql_client_plugin * plugin)
adds a plugin structure to the list of loaded plugins
This is useful if an application has the necessary functionality (for example, a special load data handler) statically linked into the application binary. It can use this function to register the plugin directly, avoiding the need to factor it out into a shared object.
Parameters
mysql MYSQL structure. It is only used for error reporting
plugin an st_mysql_client_plugin structure to register
Return values
a pointer to the plugin, or NULL in case of a failure
Definition at line 287 of file client_plugin.c.
 {
   if (is_not_initialized(mysql, plugin->name))
     return NULL;
   pthread_mutex_lock(&LOCK_load_client_plugin);
   /* make sure the plugin wasn't loaded meanwhile */
   if (find_plugin(plugin->name, plugin->type))
   {
     set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD,
                              unknown_sqlstate, ER(CR_AUTH_PLUGIN_CANNOT_LOAD),
                              plugin->name, "it is already loaded");
     plugin= NULL;
   }
   else
     plugin= add_plugin(mysql, plugin, 0, 0, 0);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   return plugin;
 }
References add_plugin(), CR_AUTH_PLUGIN_CANNOT_LOAD, ER, find_plugin(), is_not_initialized(), LOCK_load_client_plugin, NULL, set_mysql_extended_error(), and unknown_sqlstate.
mysql_load_plugin()
struct st_mysql_client_plugin* mysql_load_plugin (struct st_mysql * mysql, const char * name, int type, int argc, ...)
loads a plugin and initializes it
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded, -1 to disable type check
argc number of arguments to pass to the plugin initialization function
... arguments for the plugin initialization function
Return values
a pointer to the loaded plugin, or NULL in case of a failure
Definition at line 420 of file client_plugin.c.
 {
   struct st_mysql_client_plugin *p;
   va_list args;
   va_start(args, argc);
   p= mysql_load_plugin_v(mysql, name, type, argc, args);
   va_end(args);
   return p;
 }
References mysql_load_plugin_v(), and name.
Referenced by load_env_plugins(), and mysql_client_find_plugin().
mysql_load_plugin_v()
struct st_mysql_client_plugin* mysql_load_plugin_v (struct st_mysql * mysql, const char * name, int type, int argc, va_list args)
loads a plugin and initializes it, taking va_list as an argument
This is the same as mysql_load_plugin, but take va_list instead of a list of arguments.
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded, -1 to disable type check
argc number of arguments to pass to the plugin initialization function
args arguments for the plugin initialization function
Return values
a pointer to the loaded plugin, or NULL in case of a failure
Definition at line 312 of file client_plugin.c.
 {
   const char *errmsg;
   char dlpath[FN_REFLEN+1];
   void *sym, *dlhandle;
   struct st_mysql_client_plugin *plugin;
 #ifdef _WIN32
   char win_errormsg[2048];
 #endif
   DBUG_ENTER ("mysql_load_plugin_v");
   DBUG_PRINT ("entry", ("name=%s type=%d int argc=%d", name, type, argc));
   if (is_not_initialized(mysql, name))
   {
     DBUG_PRINT ("leave", ("mysql not initialized"));
     DBUG_RETURN (NULL);
   }
   pthread_mutex_lock(&LOCK_load_client_plugin);
   /* make sure the plugin wasn't loaded meanwhile */
   if (type >= 0 && find_plugin(name, type))
   {
     errmsg= "it is already loaded";
     goto err;
   }
   /* Compile dll path */
   strxnmov(dlpath, sizeof(dlpath) - 1,
            mysql->options.extension && mysql->options.extension->plugin_dir ?
            mysql->options.extension->plugin_dir : PLUGINDIR, "/",
            name, SO_EXT, NullS);
   DBUG_PRINT ("info", ("dlopeninig %s", dlpath));
   /* Open new dll handle */
   if (!(dlhandle= dlopen(dlpath, RTLD_NOW)))
   {
 #if defined(__APPLE__)
     /* Apple supports plugins with .so also, so try this as well */
     strxnmov(dlpath, sizeof(dlpath) - 1,
              mysql->options.extension && mysql->options.extension->plugin_dir ?
              mysql->options.extension->plugin_dir : PLUGINDIR, "/",
              name, ".so", NullS);
     if ((dlhandle= dlopen(dlpath, RTLD_NOW)))
       goto have_plugin;
 #endif
     DBUG_PRINT ("info", ("failed to dlopen"));
 #ifdef _WIN32
     if(FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,
                   0, GetLastError(), 0, win_errormsg, 2048, NULL))
       errmsg= win_errormsg;
     else
       errmsg= "";
 #else
     errmsg= dlerror();
 #endif
     goto err;
   }
 #if defined(__APPLE__)
 have_plugin:
 #endif
   if (!(sym= dlsym(dlhandle, plugin_declarations_sym)))
   {
     errmsg= "not a plugin";
     dlclose(dlhandle);
     goto err;
   }
   plugin= (struct st_mysql_client_plugin*)sym;
   if (type >=0 && type != plugin->type)
   {
     errmsg= "type mismatch";
     goto err;
   }
   if (strcmp(name, plugin->name))
   {
     errmsg= "name mismatch";
     goto err;
   }
   if (type < 0 && find_plugin(name, plugin->type))
   {
     errmsg= "it is already loaded";
     goto err;
   }
   plugin= add_plugin(mysql, plugin, dlhandle, argc, args);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   DBUG_PRINT ("leave", ("plugin loaded ok"));
   DBUG_RETURN (plugin);
 err:
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   DBUG_PRINT ("leave", ("plugin load error : %s", errmsg));
   set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD, unknown_sqlstate,
                            ER(CR_AUTH_PLUGIN_CANNOT_LOAD), name, errmsg);
   DBUG_RETURN (NULL);
 }
References add_plugin(), CR_AUTH_PLUGIN_CANNOT_LOAD, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dlerror, ER, st_mysql_options::extension, find_plugin(), FN_REFLEN, is_not_initialized(), LOCK_load_client_plugin, name, NULL, NullS, st_mysql::options, plugin_declarations_sym, st_mysql_options_extention::plugin_dir, set_mysql_extended_error(), SO_EXT, strxnmov(), and unknown_sqlstate.
Referenced by mysql_load_plugin().
mysql_plugin_options()
int STDCALL mysql_plugin_options (struct st_mysql_client_plugin * plugin, const char * option, const void * value)
set plugin options
Can be used to set extra options and affect behavior for a plugin. This function may be called multiple times to set several options
Parameters
plugin an st_mysql_client_plugin structure
option a string which specifies the option to set
value value for the option.
Return values
0 on success, 1 in case of failure
Definition at line 462 of file client_plugin.c.
 {
   DBUG_ENTER("mysql_plugin_options");
   /* does the plugin support options call? */
   if (!plugin || !plugin->options)
     DBUG_RETURN(1);
   DBUG_RETURN(plugin->options(option, value));
 }
References DBUG_ENTER, and DBUG_RETURN.