Azerotcore-wotlk: deps/jemalloc/src/chunk_dss.c File Reference
chunk_dss.c File Reference
#include "jemalloc/internal/jemalloc_internal.h"
Macros
#define JEMALLOC_CHUNK_DSS_C_
Functions
static void * chunk_dss_sbrk (intptr_t increment)
dss_prec_t chunk_dss_prec_get (void)
bool chunk_dss_prec_set (dss_prec_t dss_prec)
void * chunk_alloc_dss (size_t size, size_t alignment, bool *zero)
bool chunk_in_dss (void *chunk)
bool chunk_dss_boot (void)
void chunk_dss_prefork (void)
void chunk_dss_postfork_parent (void)
void chunk_dss_postfork_child (void)
Variables
const char * dss_prec_names []
static dss_prec_t dss_prec_default = DSS_PREC_DEFAULT
static malloc_mutex_t dss_mtx
static void * dss_base
static void * dss_prev
static void * dss_max
Macro Definition Documentation
JEMALLOC_CHUNK_DSS_C_
#define JEMALLOC_CHUNK_DSS_C_
Definition at line 1 of file chunk_dss.c.
Function Documentation
chunk_alloc_dss()
void* chunk_alloc_dss (size_t size, size_t alignment, bool * zero)
Definition at line 69 of file chunk_dss.c.
 {
     void *ret;
     cassert(config_dss);
     assert(size > 0 && (size & chunksize_mask) == 0);
     assert(alignment > 0 && (alignment & chunksize_mask) == 0);
     /*
      * sbrk() uses a signed increment argument, so take care not to
      * interpret a huge allocation request as a negative increment.
      */
     if ((intptr_t)size < 0)
         return (NULL);
     malloc_mutex_lock(&dss_mtx);
     if (dss_prev != (void *)-1) {
         size_t gap_size, cpad_size;
         void *cpad, *dss_next;
         intptr_t incr;
         /*
          * The loop is necessary to recover from races with other
          * threads that are using the DSS for something other than
          * malloc.
          */
         do {
             /* Get the current end of the DSS. */
             dss_max = chunk_dss_sbrk(0);
             /*
              * Calculate how much padding is necessary to
              * chunk-align the end of the DSS.
              */
             gap_size = (chunksize - CHUNK_ADDR2OFFSET(dss_max)) &
                 chunksize_mask;
             /*
              * Compute how much chunk-aligned pad space (if any) is
              * necessary to satisfy alignment.  This space can be
              * recycled for later use.
              */
             cpad = (void *)((uintptr_t)dss_max + gap_size);
             ret = (void *)ALIGNMENT_CEILING((uintptr_t)dss_max,
                 alignment);
             cpad_size = (uintptr_t)ret - (uintptr_t)cpad;
             dss_next = (void *)((uintptr_t)ret + size);
             if ((uintptr_t)ret < (uintptr_t)dss_max ||
                 (uintptr_t)dss_next < (uintptr_t)dss_max) {
                 /* Wrap-around. */
                 malloc_mutex_unlock(&dss_mtx);
                 return (NULL);
             }
             incr = gap_size + cpad_size + size;
             dss_prev = chunk_dss_sbrk(incr);
             if (dss_prev == dss_max) {
                 /* Success. */
                 dss_max = dss_next;
                 malloc_mutex_unlock(&dss_mtx);
                 if (cpad_size != 0)
                     chunk_unmap(cpad, cpad_size);
                 if (*zero) {
                     VALGRIND_MAKE_MEM_UNDEFINED(ret, size);
                     memset(ret, 0, size);
                 }
                 return (ret);
             }
         } while (dss_prev != (void *)-1);
     }
     malloc_mutex_unlock(&dss_mtx);
     return (NULL);
 }
References ALIGNMENT_CEILING, assert(), cassert(), chunk_dss_sbrk(), chunk_unmap(), chunksize, chunksize_mask, config_dss, dss_max, dss_mtx, dss_prev, malloc_mutex_lock(), malloc_mutex_unlock(), memset, NULL, ret, uintptr_t, VALGRIND_MAKE_MEM_UNDEFINED, and G3D::zero().
Referenced by chunk_alloc().
chunk_dss_boot()
bool chunk_dss_boot (void)
Definition at line 160 of file chunk_dss.c.
 {
     cassert(config_dss);
     if (malloc_mutex_init(&dss_mtx))
         return (true);
     dss_base = chunk_dss_sbrk(0);
     dss_prev = dss_base;
     dss_max = dss_base;
     return (false);
 }
References cassert(), chunk_dss_sbrk(), config_dss, dss_base, dss_max, dss_mtx, dss_prev, and malloc_mutex_init.
Referenced by chunk_boot().
chunk_dss_postfork_child()
void chunk_dss_postfork_child (void)
Definition at line 191 of file chunk_dss.c.
 {
     if (config_dss)
         malloc_mutex_postfork_child(&dss_mtx);
 }
References config_dss, dss_mtx, and malloc_mutex_postfork_child.
Referenced by chunk_postfork_child().
chunk_dss_postfork_parent()
void chunk_dss_postfork_parent (void)
Definition at line 183 of file chunk_dss.c.
 {
     if (config_dss)
         malloc_mutex_postfork_parent(&dss_mtx);
 }
References config_dss, dss_mtx, and malloc_mutex_postfork_parent.
Referenced by chunk_postfork_parent().
chunk_dss_prec_get()
dss_prec_t chunk_dss_prec_get (void)
Definition at line 44 of file chunk_dss.c.
 {
     dss_prec_t ret;
     if (config_dss == false)
         return (dss_prec_disabled);
     malloc_mutex_lock(&dss_mtx);
     ret = dss_prec_default;
     malloc_mutex_unlock(&dss_mtx);
     return (ret);
 }
References config_dss, dss_mtx, dss_prec_default, dss_prec_disabled, malloc_mutex_lock(), malloc_mutex_unlock(), and ret.
chunk_dss_prec_set()
bool chunk_dss_prec_set (dss_prec_t dss_prec)
Definition at line 57 of file chunk_dss.c.
 {
     if (config_dss == false)
         return (true);
     malloc_mutex_lock(&dss_mtx);
     dss_prec_default = dss_prec;
     malloc_mutex_unlock(&dss_mtx);
     return (false);
 }
References config_dss, dss_mtx, dss_prec_default, malloc_mutex_lock(), and malloc_mutex_unlock().
chunk_dss_prefork()
void chunk_dss_prefork (void)
Definition at line 175 of file chunk_dss.c.
 {
     if (config_dss)
         malloc_mutex_prefork(&dss_mtx);
 }
References config_dss, dss_mtx, and malloc_mutex_prefork.
Referenced by chunk_prefork().
chunk_dss_sbrk()
static void* chunk_dss_sbrk (intptr_t increment) static
Definition at line 32 of file chunk_dss.c.
 {
 #ifdef JEMALLOC_HAVE_SBRK
     return (sbrk(increment));
 #else
     not_implemented();
     return (NULL);
 #endif
 }
References not_implemented, and NULL.
Referenced by chunk_alloc_dss(), and chunk_dss_boot().
chunk_in_dss()
bool chunk_in_dss (void * chunk)
Definition at line 142 of file chunk_dss.c.
 {
     bool ret;
     cassert(config_dss);
     malloc_mutex_lock(&dss_mtx);
     if ((uintptr_t)chunk >= (uintptr_t)dss_base
         && (uintptr_t)chunk < (uintptr_t)dss_max)
         ret = true;
     else
         ret = false;
     malloc_mutex_unlock(&dss_mtx);
     return (ret);
 }
References cassert(), config_dss, dss_base, dss_max, dss_mtx, malloc_mutex_lock(), malloc_mutex_unlock(), and ret.
Referenced by chunk_unmap(), huge_dalloc_junk(), and huge_ralloc().
Variable Documentation
dss_base
void* dss_base static
Definition at line 23 of file chunk_dss.c.
Referenced by chunk_dss_boot(), and chunk_in_dss().
dss_max
void* dss_max static
Definition at line 27 of file chunk_dss.c.
Referenced by chunk_alloc_dss(), chunk_dss_boot(), and chunk_in_dss().
dss_mtx
malloc_mutex_t dss_mtx static
Definition at line 20 of file chunk_dss.c.
Referenced by chunk_alloc_dss(), chunk_dss_boot(), chunk_dss_postfork_child(), chunk_dss_postfork_parent(), chunk_dss_prec_get(), chunk_dss_prec_set(), chunk_dss_prefork(), and chunk_in_dss().
dss_prec_default
dss_prec_t dss_prec_default = DSS_PREC_DEFAULT static
Definition at line 14 of file chunk_dss.c.
Referenced by chunk_dss_prec_get(), and chunk_dss_prec_set().
dss_prec_names
const char* dss_prec_names[]
Initial value:
= {
    "disabled",
    "primary",
    "secondary",
    "N/A"
}
Definition at line 6 of file chunk_dss.c.
dss_prev
void* dss_prev static
Definition at line 25 of file chunk_dss.c.
Referenced by chunk_alloc_dss(), chunk_dss_boot(), and extent_alloc_dss().