Azerotcore-wotlk: G3D::Matrix3 Class Reference
G3D::Matrix3 Class Reference
#include <Matrix3.h>
Public Member Functions
Matrix3 (const Any &any)
Any toAny () const
Matrix3 ()
Matrix3 (class BinaryInput &b)
Matrix3 (const float aafEntry[3][3])
Matrix3 (const Matrix3 &rkMatrix)
Matrix3 (float fEntry00, float fEntry01, float fEntry02, float fEntry10, float fEntry11, float fEntry12, float fEntry20, float fEntry21, float fEntry22)
bool fuzzyEq (const Matrix3 &b) const
Matrix3 (const class Quat &q)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
bool isRightHanded () const
void set (float fEntry00, float fEntry01, float fEntry02, float fEntry10, float fEntry11, float fEntry12, float fEntry20, float fEntry21, float fEntry22)
float * operator[] (int iRow)
const float * operator[] (int iRow) const
operator float * ()
operator const float * () const
Vector3 column (int c) const
const Vector3 & row (int r) const
void setColumn (int iCol, const Vector3 &vector)
void setRow (int iRow, const Vector3 &vector)
Matrix3 & operator= (const Matrix3 &rkMatrix)
bool operator== (const Matrix3 &rkMatrix) const
bool operator!= (const Matrix3 &rkMatrix) const
Matrix3 operator+ (const Matrix3 &rkMatrix) const
Matrix3 operator- (const Matrix3 &rkMatrix) const
Matrix3 operator* (const Matrix3 &rkMatrix) const
Matrix3 operator- () const
Matrix3 & operator+= (const Matrix3 &rkMatrix)
Matrix3 & operator-= (const Matrix3 &rkMatrix)
Matrix3 & operator*= (const Matrix3 &rkMatrix)
Vector3 operator* (const Vector3 &v) const
Matrix3 operator* (float fScalar) const
Matrix3 & operator*= (float k)
Matrix3 & operator/= (float k)
bool isOrthonormal () const
Matrix3 transpose () const
bool inverse (Matrix3 &rkInverse, float fTolerance=1e-06f) const
Matrix3 inverse (float fTolerance=1e-06f) const
float determinant () const
void singularValueDecomposition (Matrix3 &rkL, Vector3 &rkS, Matrix3 &rkR) const
void singularValueComposition (const Matrix3 &rkL, const Vector3 &rkS, const Matrix3 &rkR)
void orthonormalize ()
void qDUDecomposition (Matrix3 &rkQ, Vector3 &rkD, Vector3 &rkU) const
void polarDecomposition (Matrix3 &R, Matrix3 &S) const
float spectralNorm () const
float squaredFrobeniusNorm () const
float frobeniusNorm () const
float l1Norm () const
float lInfNorm () const
float diffOneNorm (const Matrix3 &y) const
void toAxisAngle (Vector3 &rkAxis, float &rfRadians) const
bool toEulerAnglesXYZ (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
bool toEulerAnglesXZY (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
bool toEulerAnglesYXZ (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
bool toEulerAnglesYZX (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
bool toEulerAnglesZXY (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
bool toEulerAnglesZYX (float &rfYAngle, float &rfPAngle, float &rfRAngle) const
void eigenSolveSymmetric (float afEigenvalue[3], Vector3 akEigenvector[3]) const
std::string toString () const
Static Public Member Functions
static Matrix3 fromColumns (const Vector3 &c0, const Vector3 &c1, const Vector3 &c2)
static Matrix3 fromRows (const Vector3 &r0, const Vector3 &r1, const Vector3 &r2)
static Matrix3 diagonal (float e00, float e11, float e22)
static void mul (const Matrix3 &A, const Matrix3 &B, Matrix3 &out)
static void transpose (const Matrix3 &A, Matrix3 &out)
static Matrix3 fromDiagonal (const Vector3 &d)
static Matrix3 fromAxisAngle (const Vector3 &rkAxis, float fRadians)
static Matrix3 fromUnitAxisAngle (const Vector3 &rkAxis, float fRadians)
static Matrix3 fromEulerAnglesXYZ (float fYAngle, float fPAngle, float fRAngle)
static Matrix3 fromEulerAnglesXZY (float fYAngle, float fPAngle, float fRAngle)
static Matrix3 fromEulerAnglesYXZ (float fYAngle, float fPAngle, float fRAngle)
static Matrix3 fromEulerAnglesYZX (float fYAngle, float fPAngle, float fRAngle)
static Matrix3 fromEulerAnglesZXY (float fYAngle, float fPAngle, float fRAngle)
static Matrix3 fromEulerAnglesZYX (float fYAngle, float fPAngle, float fRAngle)
static void tensorProduct (const Vector3 &rkU, const Vector3 &rkV, Matrix3 &rkProduct)
static const Matrix3 & zero ()
static const Matrix3 & identity ()
Static Public Attributes
static const float EPSILON = 1e-06f
Protected Member Functions
void tridiagonal (float afDiag[3], float afSubDiag[3])
bool qLAlgorithm (float afDiag[3], float afSubDiag[3])
Static Protected Member Functions
static void bidiagonalize (Matrix3 &kA, Matrix3 &kL, Matrix3 &kR)
static void golubKahanStep (Matrix3 &kA, Matrix3 &kL, Matrix3 &kR)
static float maxCubicRoot (float afCoeff[3])
Static Protected Attributes
static const float ms_fSvdEpsilon = 1e-04f
static const int ms_iSvdMaxIterations = 32
Private Member Functions
bool operator< (const Matrix3 &) const
bool operator> (const Matrix3 &) const
bool operator<= (const Matrix3 &) const
bool operator>= (const Matrix3 &) const
Static Private Member Functions
static void _mul (const Matrix3 &A, const Matrix3 &B, Matrix3 &out)
static void _transpose (const Matrix3 &A, Matrix3 &out)
Private Attributes
float elt [3][3]
Friends
Vector3 operator* (const Vector3 &rkVector, const Matrix3 &rkMatrix)
Matrix3 operator* (double fScalar, const Matrix3 &rkMatrix)
Matrix3 operator* (float fScalar, const Matrix3 &rkMatrix)
Matrix3 operator* (int fScalar, const Matrix3 &rkMatrix)
Detailed Description
A 3x3 matrix. Do not subclass. Data is unitializd when default constructed.
Definition at line 37 of file Matrix3.h.
Constructor & Destructor Documentation
Matrix3() [1/7]
G3D::Matrix3::Matrix3 (const Any & any)
Must be in one of the following forms:
Matrix3(#, #, # .... #)
Matrix3::fromAxisAngle(#, #)
Matrix3::diagonal(#, #, #)
Matrix3::identity()
Definition at line 29 of file Matrix3.cpp.
{
     any.verifyName("Matrix3");
     any.verifyType(Any::ARRAY);
     if (any.nameEquals("Matrix3::fromAxisAngle")) {
         any.verifySize(2);
         *this = fromAxisAngle(Vector3(any[0]), any[1].floatValue());
     } else if (any.nameEquals("Matrix3::diagonal")) {
         any.verifySize(3);
         *this = diagonal(any[0], any[1], any[2]);
     } else if (any.nameEquals("Matrix3::identity")) {
         *this = identity();
     } else {
         any.verifySize(9);
         for (int r = 0; r < 3; ++r) {
             for (int c = 0; c < 3; ++c) {
                 elt[r][c] = any[r * 3 + c];
             }
         }
     }
 }
References G3D::any(), G3D::Any::ARRAY, mpq::c, diagonal(), elt, fromAxisAngle(), and identity().
Matrix3() [2/7]
G3D::Matrix3::Matrix3 () inline
Initial values are undefined for performance.
See also
Matrix3::zero, Matrix3::identity, Matrix3::fromAxisAngle, etc.
Definition at line 83 of file Matrix3.h.
 {}
Referenced by diagonal(), and fromDiagonal().
Matrix3() [3/7]
G3D::Matrix3::Matrix3 (class BinaryInput & b)
Definition at line 79 of file Matrix3.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Matrix3() [4/7]
G3D::Matrix3::Matrix3 (const float aafEntry[3][3])
Definition at line 146 of file Matrix3.cpp.
{
     memcpy(elt, aafEntry, 9*sizeof(float));
 }
References elt, and memcpy.
Matrix3() [5/7]
G3D::Matrix3::Matrix3 (const Matrix3 & rkMatrix)
Definition at line 151 of file Matrix3.cpp.
{
     memcpy(elt, rkMatrix.elt, 9*sizeof(float));
 }
References elt, and memcpy.
Matrix3() [6/7]
G3D::Matrix3::Matrix3 (float fEntry00, float fEntry01, float fEntry02, float fEntry10, float fEntry11, float fEntry12, float fEntry20, float fEntry21, float fEntry22)
Definition at line 156 of file Matrix3.cpp.
{
     set(fEntry00, fEntry01, fEntry02,
         fEntry10, fEntry11, fEntry12,
         fEntry20, fEntry21, fEntry22);
 }
References set().
Matrix3() [7/7]
G3D::Matrix3::Matrix3 (const class Quat & q)
Constructs a matrix from a quaternion. [Graphics] Gems II, p. 351–354 [Implementation] from Watt and Watt, pg 362
Member Function Documentation
_mul()
void G3D::Matrix3::_mul (const Matrix3 & A, const Matrix3 & B, Matrix3 & out) static private
Multiplication where out != A and out != B
Definition at line 1869 of file Matrix3.cpp.
{
     const float* ARowPtr = A.elt[0];
     float* outRowPtr     = out.elt[0];
         outRowPtr[0] =
             ARowPtr[0] * B.elt[0][0] +
             ARowPtr[1] * B.elt[1][0] +
             ARowPtr[2] * B.elt[2][0];
         outRowPtr[1] =
             ARowPtr[0] * B.elt[0][1] +
             ARowPtr[1] * B.elt[1][1] +
             ARowPtr[2] * B.elt[2][1];
         outRowPtr[2] =
             ARowPtr[0] * B.elt[0][2] +
             ARowPtr[1] * B.elt[1][2] +
             ARowPtr[2] * B.elt[2][2];
     ARowPtr       = A.elt[1];
     outRowPtr     = out.elt[1];
         outRowPtr[0] =
             ARowPtr[0] * B.elt[0][0] +
             ARowPtr[1] * B.elt[1][0] +
             ARowPtr[2] * B.elt[2][0];
         outRowPtr[1] =
             ARowPtr[0] * B.elt[0][1] +
             ARowPtr[1] * B.elt[1][1] +
             ARowPtr[2] * B.elt[2][1];
         outRowPtr[2] =
             ARowPtr[0] * B.elt[0][2] +
             ARowPtr[1] * B.elt[1][2] +
             ARowPtr[2] * B.elt[2][2];
     ARowPtr       = A.elt[2];
     outRowPtr     = out.elt[2];
         outRowPtr[0] =
             ARowPtr[0] * B.elt[0][0] +
             ARowPtr[1] * B.elt[1][0] +
             ARowPtr[2] * B.elt[2][0];
         outRowPtr[1] =
             ARowPtr[0] * B.elt[0][1] +
             ARowPtr[1] * B.elt[1][1] +
             ARowPtr[2] * B.elt[2][1];
         outRowPtr[2] =
             ARowPtr[0] * B.elt[0][2] +
             ARowPtr[1] * B.elt[1][2] +
             ARowPtr[2] * B.elt[2][2];
 }
References elt.
Referenced by mul().
_transpose()
void G3D::Matrix3::_transpose (const Matrix3 & A, Matrix3 & out) static private
Definition at line 1919 of file Matrix3.cpp.
{
     out[0][0] = A.elt[0][0];
     out[0][1] = A.elt[1][0];
     out[0][2] = A.elt[2][0];
     out[1][0] = A.elt[0][1];
     out[1][1] = A.elt[1][1];
     out[1][2] = A.elt[2][1];
     out[2][0] = A.elt[0][2];
     out[2][1] = A.elt[1][2];
     out[2][2] = A.elt[2][2];
 }
References elt.
Referenced by transpose().
bidiagonalize()
void G3D::Matrix3::bidiagonalize (Matrix3 & kA, Matrix3 & kL, Matrix3 & kR) static protected
Definition at line 470 of file Matrix3.cpp.
{
     float afV[3], afW[3];
     float fLength, fSign, fT1, fInvT1, fT2;
     bool bIdentity;
     // map first column to (*,0,0)
     fLength = sqrt(kA[0][0] * kA[0][0] + kA[1][0] * kA[1][0] +
                          kA[2][0] * kA[2][0]);
     if ( fLength > 0.0 ) {
         fSign = (kA[0][0] > 0.0 ? 1.0f : -1.0f);
         fT1 = (float)kA[0][0] + fSign * fLength;
         fInvT1 = 1.0f / fT1;
         afV[1] = kA[1][0] * fInvT1;
         afV[2] = kA[2][0] * fInvT1;
         fT2 = -2.0f / (1.0f + afV[1] * afV[1] + afV[2] * afV[2]);
         afW[0] = fT2 * (kA[0][0] + kA[1][0] * afV[1] + kA[2][0] * afV[2]);
         afW[1] = fT2 * (kA[0][1] + kA[1][1] * afV[1] + kA[2][1] * afV[2]);
         afW[2] = fT2 * (kA[0][2] + kA[1][2] * afV[1] + kA[2][2] * afV[2]);
         kA[0][0] += afW[0];
         kA[0][1] += afW[1];
         kA[0][2] += afW[2];
         kA[1][1] += afV[1] * afW[1];
         kA[1][2] += afV[1] * afW[2];
         kA[2][1] += afV[2] * afW[1];
         kA[2][2] += afV[2] * afW[2];
         kL[0][0] = 1.0f + fT2;
         kL[0][1] = kL[1][0] = fT2 * afV[1];
         kL[0][2] = kL[2][0] = fT2 * afV[2];
         kL[1][1] = 1.0f + fT2 * afV[1] * afV[1];
         kL[1][2] = kL[2][1] = fT2 * afV[1] * afV[2];
         kL[2][2] = 1.0f + fT2 * afV[2] * afV[2];
         bIdentity = false;
     } else {
         kL = Matrix3::identity();
         bIdentity = true;
     }
     // map first row to (*,*,0)
     fLength = sqrt(kA[0][1] * kA[0][1] + kA[0][2] * kA[0][2]);
     if ( fLength > 0.0 ) {
         fSign = (kA[0][1] > 0.0 ? 1.0f : -1.0f);
         fT1 = kA[0][1] + fSign * fLength;
         afV[2] = kA[0][2] / fT1;
         fT2 = -2.0f / (1.0f + afV[2] * afV[2]);
         afW[0] = fT2 * (kA[0][1] + kA[0][2] * afV[2]);
         afW[1] = fT2 * (kA[1][1] + kA[1][2] * afV[2]);
         afW[2] = fT2 * (kA[2][1] + kA[2][2] * afV[2]);
         kA[0][1] += afW[0];
         kA[1][1] += afW[1];
         kA[1][2] += afW[1] * afV[2];
         kA[2][1] += afW[2];
         kA[2][2] += afW[2] * afV[2];
         kR[0][0] = 1.0f;
         kR[0][1] = kR[1][0] = 0.0f;
         kR[0][2] = kR[2][0] = 0.0f;
         kR[1][1] = 1.0f + fT2;
         kR[1][2] = kR[2][1] = fT2 * afV[2];
         kR[2][2] = 1.0f + fT2 * afV[2] * afV[2];
     } else {
         kR = Matrix3::identity();
     }
     // map second column to (*,*,0)
     fLength = sqrt(kA[1][1] * kA[1][1] + kA[2][1] * kA[2][1]);
     if ( fLength > 0.0 ) {
         fSign = (kA[1][1] > 0.0 ? 1.0f : -1.0f);
         fT1 = kA[1][1] + fSign * fLength;
         afV[2] = kA[2][1] / fT1;
         fT2 = -2.0f / (1.0f + afV[2] * afV[2]);
         afW[1] = fT2 * (kA[1][1] + kA[2][1] * afV[2]);
         afW[2] = fT2 * (kA[1][2] + kA[2][2] * afV[2]);
         kA[1][1] += afW[1];
         kA[1][2] += afW[2];
         kA[2][2] += afV[2] * afW[2];
         float fA = 1.0f + fT2;
         float fB = fT2 * afV[2];
         float fC = 1.0f + fB * afV[2];
         if ( bIdentity ) {
             kL[0][0] = 1.0;
             kL[0][1] = kL[1][0] = 0.0;
             kL[0][2] = kL[2][0] = 0.0;
             kL[1][1] = fA;
             kL[1][2] = kL[2][1] = fB;
             kL[2][2] = fC;
         } else {
             for (int iRow = 0; iRow < 3; ++iRow) {
                 float fTmp0 = kL[iRow][1];
                 float fTmp1 = kL[iRow][2];
                 kL[iRow][1] = fA * fTmp0 + fB * fTmp1;
                 kL[iRow][2] = fB * fTmp0 + fC * fTmp1;
             }
         }
     }
 }
References identity().
Referenced by singularValueDecomposition().
column()
Vector3 G3D::Matrix3::column (int c) const
Definition at line 203 of file Matrix3.cpp.
{
     assert((0 <= iCol) && (iCol < 3));
     return Vector3(elt[0][iCol], elt[1][iCol],
                    elt[2][iCol]);
 }
References assert(), and elt.
Referenced by G3D::CoordinateFrame::getHeading(), isOrthonormal(), isRightHanded(), G3D::CoordinateFrame::leftVector(), G3D::CoordinateFrame::lookVector(), G3D::CoordinateFrame::rightVector(), and G3D::CoordinateFrame::upVector().
deserialize()
void G3D::Matrix3::deserialize (class BinaryInput & b)
Definition at line 182 of file Matrix3.cpp.
{
     int r,c;
     for (c = 0; c < 3; ++c) {
         for (r = 0; r < 3; ++r) {
             elt[r][c] = b.readFloat32();
         }
     }
 }
References b, mpq::c, and elt.
Referenced by G3D::CoordinateFrame::deserialize(), and Matrix3().
determinant()
float G3D::Matrix3::determinant () const
Definition at line 453 of file Matrix3.cpp.
{
     float fCofactor00 = elt[1][1] * elt[2][2] -
                        elt[1][2] * elt[2][1];
     float fCofactor10 = elt[1][2] * elt[2][0] -
                        elt[1][0] * elt[2][2];
     float fCofactor20 = elt[1][0] * elt[2][1] -
                        elt[1][1] * elt[2][0];
     float fDet =
         elt[0][0] * fCofactor00 +
         elt[0][1] * fCofactor10 +
         elt[0][2] * fCofactor20;
     return fDet;
 }
References elt.
Referenced by G3D::Matrix::col3PseudoInverse(), G3D::determinant(), G3D::CoordinateFrame::pointToObjectSpace(), and G3D::Matrix::row3PseudoInverse().
diagonal()
static Matrix3 G3D::Matrix3::diagonal (float e00, float e11, float e22) inline static
Definition at line 99 of file Matrix3.h.
{
         return Matrix3(e00, 0, 0,
                        0, e11, 0,
                        0, 0, e22);
     }
References Matrix3().
Referenced by Matrix3().
diffOneNorm()
float G3D::Matrix3::diffOneNorm (const Matrix3 & y) const
Definition at line 1246 of file Matrix3.cpp.
{
     float oneNorm = 0;
     for (int c = 0; c < 3; ++c){
       float f = fabs(elt[0][c] - y[0][c]) + fabs(elt[1][c] - y[1][c])
     + fabs(elt[2][c] - y[2][c]);
       if (f > oneNorm) {
     oneNorm = f;
       }
     }
     return oneNorm;
 }
References mpq::c, elt, f(), and G3D::y.
Referenced by polarDecomposition().
eigenSolveSymmetric()
void G3D::Matrix3::eigenSolveSymmetric (float afEigenvalue[3], Vector3 akEigenvector[3]) const
eigensolver, matrix must be symmetric
Definition at line 1825 of file Matrix3.cpp.
{
     Matrix3 kMatrix = *this;
     float afSubDiag[3];
     kMatrix.tridiagonal(afEigenvalue, afSubDiag);
     kMatrix.qLAlgorithm(afEigenvalue, afSubDiag);
     for (int i = 0; i < 3; ++i) {
         akEigenvector[i][0] = kMatrix[0][i];
         akEigenvector[i][1] = kMatrix[1][i];
         akEigenvector[i][2] = kMatrix[2][i];
     }
     // make eigenvectors form a right--handed system
     Vector3 kCross = akEigenvector[1].cross(akEigenvector[2]);
     float fDet = akEigenvector[0].dot(kCross);
     if ( fDet < 0.0 ) {
         akEigenvector[2][0] = - akEigenvector[2][0];
         akEigenvector[2][1] = - akEigenvector[2][1];
         akEigenvector[2][2] = - akEigenvector[2][2];
     }
 }
References G3D::Vector3::cross(), G3D::Vector3::dot(), qLAlgorithm(), and tridiagonal().
frobeniusNorm()
float G3D::Matrix3::frobeniusNorm () const
Definition at line 1210 of file Matrix3.cpp.
{
     return sqrtf(squaredFrobeniusNorm());
 }
References squaredFrobeniusNorm().
fromAxisAngle()
Matrix3 G3D::Matrix3::fromAxisAngle (const Vector3 & rkAxis, float fRadians) static
See also
fromUnitAxisAngle
Definition at line 1346 of file Matrix3.cpp.
{
     return fromUnitAxisAngle(_axis.direction(), fRadians);
 }
References G3D::Vector3::direction(), and fromUnitAxisAngle().
Referenced by Matrix3(), G3D::Matrix4::pitchDegrees(), G3D::Matrix4::rollDegrees(), G3D::UprightFrame::toCoordinateFrame(), and G3D::Matrix4::yawDegrees().
fromColumns()
static Matrix3 G3D::Matrix3::fromColumns (const Vector3 & c0, const Vector3 & c1, const Vector3 & c2) inline static
Definition at line 59 of file Matrix3.h.
{
         Matrix3 m;
         for (int r = 0; r < 3; ++r) {
             m.elt[r][0] = c0[r];
             m.elt[r][1] = c1[r];
             m.elt[r][2] = c2[r];
         }
         return m;
     }
References elt.
fromDiagonal()
static Matrix3 G3D::Matrix3::fromDiagonal (const Vector3 & d) inline static
Definition at line 297 of file Matrix3.h.
{
         return Matrix3(d.x, 0, 0,
                        0, d.y, 0,
                        0, 0, d.z);
     }
References mpq::d, and Matrix3().
fromEulerAnglesXYZ()
Matrix3 G3D::Matrix3::fromEulerAnglesXYZ (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1557 of file Matrix3.cpp.
{
     float fCos, fSin;
     fCos = cosf(fYAngle);
     fSin = sinf(fYAngle);
     Matrix3 kXMat(1.0f, 0.0f, 0.0f, 0.0f, fCos, -fSin, 0.0, fSin, fCos);
     fCos = cosf(fPAngle);
     fSin = sinf(fPAngle);
     Matrix3 kYMat(fCos, 0.0f, fSin, 0.0f, 1.0f, 0.0f, -fSin, 0.0f, fCos);
     fCos = cosf(fRAngle);
     fSin = sinf(fRAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0f, fSin, fCos, 0.0f, 0.0f, 0.0f, 1.0f);
     return kXMat * (kYMat * kZMat);
 }
Referenced by MMAP::TerrainBuilder::loadVMap(), and Utils::TransformDoodadVertex().
fromEulerAnglesXZY()
Matrix3 G3D::Matrix3::fromEulerAnglesXZY (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1577 of file Matrix3.cpp.
{
     float fCos, fSin;
     fCos = cosf(fYAngle);
     fSin = sinf(fYAngle);
     Matrix3 kXMat(1.0, 0.0, 0.0, 0.0, fCos, -fSin, 0.0, fSin, fCos);
     fCos = cosf(fPAngle);
     fSin = sinf(fPAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0, fSin, fCos, 0.0, 0.0, 0.0, 1.0);
     fCos = cosf(fRAngle);
     fSin = sinf(fRAngle);
     Matrix3 kYMat(fCos, 0.0, fSin, 0.0, 1.0, 0.0, -fSin, 0.0, fCos);
     return kXMat * (kZMat * kYMat);
 }
fromEulerAnglesYXZ()
Matrix3 G3D::Matrix3::fromEulerAnglesYXZ (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1598 of file Matrix3.cpp.
                    {
     float fCos, fSin;
     fCos = cos(fYAngle);
     fSin = sin(fYAngle);
     Matrix3 kYMat(fCos, 0.0f, fSin, 0.0f, 1.0f, 0.0f, -fSin, 0.0f, fCos);
     fCos = cos(fPAngle);
     fSin = sin(fPAngle);
     Matrix3 kXMat(1.0f, 0.0f, 0.0f, 0.0f, fCos, -fSin, 0.0f, fSin, fCos);
     fCos = cos(fRAngle);
     fSin = sin(fRAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0f, fSin, fCos, 0.0f, 0.0f, 0.0f, 1.0f);
     return kYMat * (kXMat * kZMat);
 }
Referenced by G3D::CoordinateFrame::fromXYZYPRRadians().
fromEulerAnglesYZX()
Matrix3 G3D::Matrix3::fromEulerAnglesYZX (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1621 of file Matrix3.cpp.
                    {
     float fCos, fSin;
     fCos = cos(fYAngle);
     fSin = sin(fYAngle);
     Matrix3 kYMat(fCos, 0.0f, fSin, 0.0f, 1.0f, 0.0f, -fSin, 0.0f, fCos);
     fCos = cos(fPAngle);
     fSin = sin(fPAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0f, fSin, fCos, 0.0f, 0.0f, 0.0f, 1.0f);
     fCos = cos(fRAngle);
     fSin = sin(fRAngle);
     Matrix3 kXMat(1.0f, 0.0f, 0.0f, 0.0f, fCos, -fSin, 0.0f, fSin, fCos);
     return kYMat * (kZMat * kXMat);
 }
fromEulerAnglesZXY()
Matrix3 G3D::Matrix3::fromEulerAnglesZXY (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1644 of file Matrix3.cpp.
{
     float fCos, fSin;
     fCos = cos(fYAngle);
     fSin = sin(fYAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0, fSin, fCos, 0.0, 0.0, 0.0, 1.0);
     fCos = cos(fPAngle);
     fSin = sin(fPAngle);
     Matrix3 kXMat(1.0, 0.0, 0.0, 0.0, fCos, -fSin, 0.0, fSin, fCos);
     fCos = cos(fRAngle);
     fSin = sin(fRAngle);
     Matrix3 kYMat(fCos, 0.0, fSin, 0.0, 1.0, 0.0, -fSin, 0.0, fCos);
     return kZMat * (kXMat * kYMat);
 }
fromEulerAnglesZYX()
Matrix3 G3D::Matrix3::fromEulerAnglesZYX (float fYAngle, float fPAngle, float fRAngle) static
Definition at line 1664 of file Matrix3.cpp.
{
     float fCos, fSin;
     fCos = cos(fYAngle);
     fSin = sin(fYAngle);
     Matrix3 kZMat(fCos, -fSin, 0.0, fSin, fCos, 0.0, 0.0, 0.0, 1.0);
     fCos = cos(fPAngle);
     fSin = sin(fPAngle);
     Matrix3 kYMat(fCos, 0.0, fSin, 0.0, 1.0, 0.0, -fSin, 0.0, fCos);
     fCos = cos(fRAngle);
     fSin = sin(fRAngle);
     Matrix3 kXMat(1.0, 0.0, 0.0, 0.0, fCos, -fSin, 0.0, fSin, fCos);
     return kZMat * (kYMat * kXMat);
 }
Referenced by Doodad::ExtractSet(), VMAP::ModelPosition::init(), GameObjectModel::initialize(), VMAP::ModelInstance::ModelInstance(), GameObject::SetLocalRotationAngles(), and GameObjectModel::UpdatePosition().
fromRows()
static Matrix3 G3D::Matrix3::fromRows (const Vector3 & r0, const Vector3 & r1, const Vector3 & r2) inline static
Definition at line 69 of file Matrix3.h.
{
         Matrix3 m;
         for (int c = 0; c < 3; ++c) {
             m.elt[0][c] = r0[c];
             m.elt[1][c] = r1[c];
             m.elt[2][c] = r2[c];
         }
         return m;
     }
References mpq::c, and elt.
fromUnitAxisAngle()
Matrix3 G3D::Matrix3::fromUnitAxisAngle (const Vector3 & rkAxis, float fRadians) static
Assumes that rkAxis has unit length
Definition at line 1350 of file Matrix3.cpp.
{
     debugAssertM(axis.isUnit(), "Matrix3::fromUnitAxisAngle requires ||axis|| = 1");
     Matrix3 m;
     float fCos  = cos(fRadians);
     float fSin  = sin(fRadians);
     float fOneMinusCos = 1.0f - fCos;
     float fX2   = square(axis.x);
     float fY2   = square(axis.y);
     float fZ2   = square(axis.z);
     float fXYM  = axis.x * axis.y * fOneMinusCos;
     float fXZM  = axis.x * axis.z * fOneMinusCos;
     float fYZM  = axis.y * axis.z * fOneMinusCos;
     float fXSin = axis.x * fSin;
     float fYSin = axis.y * fSin;
     float fZSin = axis.z * fSin;
     m.elt[0][0] = fX2 * fOneMinusCos + fCos;
     m.elt[0][1] = fXYM - fZSin;
     m.elt[0][2] = fXZM + fYSin;
     m.elt[1][0] = fXYM + fZSin;
     m.elt[1][1] = fY2 * fOneMinusCos + fCos;
     m.elt[1][2] = fYZM - fXSin;
     m.elt[2][0] = fXZM - fYSin;
     m.elt[2][1] = fYZM + fXSin;
     m.elt[2][2] = fZ2 * fOneMinusCos + fCos;
     return m;
 }
References debugAssertM, elt, G3D::Vector3::isUnit(), G3D::square(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by fromAxisAngle().
fuzzyEq()
bool G3D::Matrix3::fuzzyEq (const Matrix3 & b) const
Definition at line 83 of file Matrix3.cpp.
{
     for (int r = 0; r < 3; ++r) {
         for (int c = 0; c < 3; ++c) {
             if (! G3D::fuzzyEq(elt[r][c], b[r][c])) {
                 return false;
             }
         }
     }
     return true;
 }
References b, mpq::c, elt, and G3D::fuzzyEq().
golubKahanStep()
void G3D::Matrix3::golubKahanStep (Matrix3 & kA, Matrix3 & kL, Matrix3 & kR) static protected
Definition at line 577 of file Matrix3.cpp.
{
     float fT11 = kA[0][1] * kA[0][1] + kA[1][1] * kA[1][1];
     float fT22 = kA[1][2] * kA[1][2] + kA[2][2] * kA[2][2];
     float fT12 = kA[1][1] * kA[1][2];
     float fTrace = fT11 + fT22;
     float fDiff = fT11 - fT22;
     float fDiscr = sqrt(fDiff * fDiff + 4.0f * fT12 * fT12);
     float fRoot1 = 0.5f * (fTrace + fDiscr);
     float fRoot2 = 0.5f * (fTrace - fDiscr);
     // adjust right
     float fY = kA[0][0] - (G3D::abs(fRoot1 - fT22) <=
                           G3D::abs(fRoot2 - fT22) ? fRoot1 : fRoot2);
     float fZ = kA[0][1];
     float fInvLength = 1.0f / sqrt(fY * fY + fZ * fZ);
     float fSin = fZ * fInvLength;
     float fCos = -fY * fInvLength;
     float fTmp0 = kA[0][0];
     float fTmp1 = kA[0][1];
     kA[0][0] = fCos * fTmp0 - fSin * fTmp1;
     kA[0][1] = fSin * fTmp0 + fCos * fTmp1;
     kA[1][0] = -fSin * kA[1][1];
     kA[1][1] *= fCos;
     int iRow;
     for (iRow = 0; iRow < 3; ++iRow) {
         fTmp0 = kR[0][iRow];
         fTmp1 = kR[1][iRow];
         kR[0][iRow] = fCos * fTmp0 - fSin * fTmp1;
         kR[1][iRow] = fSin * fTmp0 + fCos * fTmp1;
     }
     // adjust left
     fY = kA[0][0];
     fZ = kA[1][0];
     fInvLength = 1.0f / sqrt(fY * fY + fZ * fZ);
     fSin = fZ * fInvLength;
     fCos = -fY * fInvLength;
     kA[0][0] = fCos * kA[0][0] - fSin * kA[1][0];
     fTmp0 = kA[0][1];
     fTmp1 = kA[1][1];
     kA[0][1] = fCos * fTmp0 - fSin * fTmp1;
     kA[1][1] = fSin * fTmp0 + fCos * fTmp1;
     kA[0][2] = -fSin * kA[1][2];
     kA[1][2] *= fCos;
     int iCol;
     for (iCol = 0; iCol < 3; ++iCol) {
         fTmp0 = kL[iCol][0];
         fTmp1 = kL[iCol][1];
         kL[iCol][0] = fCos * fTmp0 - fSin * fTmp1;
         kL[iCol][1] = fSin * fTmp0 + fCos * fTmp1;
     }
     // adjust right
     fY = kA[0][1];
     fZ = kA[0][2];
     fInvLength = 1.0f / sqrt(fY * fY + fZ * fZ);
     fSin = fZ * fInvLength;
     fCos = -fY * fInvLength;
     kA[0][1] = fCos * kA[0][1] - fSin * kA[0][2];
     fTmp0 = kA[1][1];
     fTmp1 = kA[1][2];
     kA[1][1] = fCos * fTmp0 - fSin * fTmp1;
     kA[1][2] = fSin * fTmp0 + fCos * fTmp1;
     kA[2][1] = -fSin * kA[2][2];
     kA[2][2] *= fCos;
     for (iRow = 0; iRow < 3; ++iRow) {
         fTmp0 = kR[1][iRow];
         fTmp1 = kR[2][iRow];
         kR[1][iRow] = fCos * fTmp0 - fSin * fTmp1;
         kR[2][iRow] = fSin * fTmp0 + fCos * fTmp1;
     }
     // adjust left
     fY = kA[1][1];
     fZ = kA[2][1];
     fInvLength = 1.0f / sqrt(fY * fY + fZ * fZ);
     fSin = fZ * fInvLength;
     fCos = -fY * fInvLength;
     kA[1][1] = fCos * kA[1][1] - fSin * kA[2][1];
     fTmp0 = kA[1][2];
     fTmp1 = kA[2][2];
     kA[1][2] = fCos * fTmp0 - fSin * fTmp1;
     kA[2][2] = fSin * fTmp0 + fCos * fTmp1;
     for (iCol = 0; iCol < 3; ++iCol) {
         fTmp0 = kL[iCol][1];
         fTmp1 = kL[iCol][2];
         kL[iCol][1] = fCos * fTmp0 - fSin * fTmp1;
         kL[iCol][2] = fSin * fTmp0 + fCos * fTmp1;
     }
 }
References G3D::abs().
Referenced by singularValueDecomposition().
identity()
const Matrix3 & G3D::Matrix3::identity () static
Definition at line 70 of file Matrix3.cpp.
{
     static Matrix3 m(1, 0, 0, 0, 1, 0, 0, 0, 1);
     return m;
 }
Referenced by bidiagonalize(), G3D::CoordinateFrame::fuzzyIsIdentity(), G3D::CoordinateFrame::isIdentity(), Matrix3(), polarDecomposition(), G3D::Box::toAny(), and G3D::Matrix4::translation().
inverse() [1/2]
Matrix3 G3D::Matrix3::inverse (float fTolerance = 1e-06f) const
Definition at line 446 of file Matrix3.cpp.
{
     Matrix3 kInverse = Matrix3::zero();
     inverse(kInverse, fTolerance);
     return kInverse;
 }
References inverse(), and zero().
inverse() [2/2]
bool G3D::Matrix3::inverse (Matrix3 & rkInverse, float fTolerance = 1e-06f) const
Definition at line 404 of file Matrix3.cpp.
{
     // Invert a 3x3 using cofactors.  This is about 8 times faster than
     // the Numerical Recipes code which uses Gaussian elimination.
     rkInverse[0][0] = elt[1][1] * elt[2][2] -
                       elt[1][2] * elt[2][1];
     rkInverse[0][1] = elt[0][2] * elt[2][1] -
                       elt[0][1] * elt[2][2];
     rkInverse[0][2] = elt[0][1] * elt[1][2] -
                       elt[0][2] * elt[1][1];
     rkInverse[1][0] = elt[1][2] * elt[2][0] -
                       elt[1][0] * elt[2][2];
     rkInverse[1][1] = elt[0][0] * elt[2][2] -
                       elt[0][2] * elt[2][0];
     rkInverse[1][2] = elt[0][2] * elt[1][0] -
                       elt[0][0] * elt[1][2];
     rkInverse[2][0] = elt[1][0] * elt[2][1] -
                       elt[1][1] * elt[2][0];
     rkInverse[2][1] = elt[0][1] * elt[2][0] -
                       elt[0][0] * elt[2][1];
     rkInverse[2][2] = elt[0][0] * elt[1][1] -
                       elt[0][1] * elt[1][0];
     float fDet =
         elt[0][0] * rkInverse[0][0] +
         elt[0][1] * rkInverse[1][0] +
         elt[0][2] * rkInverse[2][0];
     if ( G3D::abs(fDet) <= fTolerance )
         return false;
     float fInvDet = 1.0f / fDet;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol)
             rkInverse[iRow][iCol] *= fInvDet;
     }
     return true;
 }
References G3D::abs(), and elt.
Referenced by G3D::Matrix::col3PseudoInverse(), G3D::Box::contains(), GameObjectModel::initialize(), inverse(), VMAP::ModelInstance::ModelInstance(), G3D::Matrix::row3PseudoInverse(), and GameObjectModel::UpdatePosition().
isOrthonormal()
bool G3D::Matrix3::isOrthonormal () const
Returns true if the rows and column L2 norms are 1.0 and the rows are orthogonal.
Definition at line 107 of file Matrix3.cpp.
{
     const Vector3& X = column(0);
     const Vector3& Y = column(1);
     const Vector3& Z = column(2);
     return
         (G3D::fuzzyEq(X.dot(Y), 0.0f) &&
          G3D::fuzzyEq(Y.dot(Z), 0.0f) &&
          G3D::fuzzyEq(X.dot(Z), 0.0f) &&
          G3D::fuzzyEq(X.squaredMagnitude(), 1.0f) &&
          G3D::fuzzyEq(Y.squaredMagnitude(), 1.0f) &&
          G3D::fuzzyEq(Z.squaredMagnitude(), 1.0f));
 }
References column(), G3D::fuzzyEq(), X, Y, and Z.
isRightHanded()
bool G3D::Matrix3::isRightHanded () const
Returns true if column(0).cross(column(1)).dot(column(2)) > 0.
Definition at line 95 of file Matrix3.cpp.
{
     const Vector3& X = column(0);
     const Vector3& Y = column(1);
     const Vector3& Z = column(2);
     const Vector3& W = X.cross(Y);
     return W.dot(Z) > 0.0f;
 }
References column(), G3D::Vector3::dot(), X, Y, and Z.
l1Norm()
float G3D::Matrix3::l1Norm () const
Definition at line 1215 of file Matrix3.cpp.
{
     // The one norm of a matrix is the max column sum in absolute value.
     float oneNorm = 0;
     for (int c = 0; c < 3; ++c) {
       float f = fabs(elt[0][c])+ fabs(elt[1][c]) + fabs(elt[2][c]);
       if (f > oneNorm) {
     oneNorm = f;
       }
     }
     return oneNorm;
 }
References mpq::c, elt, and f().
Referenced by polarDecomposition().
lInfNorm()
float G3D::Matrix3::lInfNorm () const
Definition at line 1230 of file Matrix3.cpp.
{
     // The infinity norm of a matrix is the max row sum in absolute value.
     float infNorm = 0;
     for (int r = 0; r < 3; ++r) {
       float f = fabs(elt[r][0]) + fabs(elt[r][1])+ fabs(elt[r][2]);
       if (f > infNorm) {
     infNorm = f;
       }
     }
     return infNorm;
 }
References elt, and f().
Referenced by polarDecomposition().
maxCubicRoot()
float G3D::Matrix3::maxCubicRoot (float afCoeff[3]) static protected
Definition at line 1106 of file Matrix3.cpp.
{
     // Spectral norm is for A^T*A, so characteristic polynomial
     // P(x) = c[0]+c[1]*x+c[2]*x^2+x^3 has three positive float roots.
     // This yields the assertions c[0] < 0 and c[2]*c[2] >= 3*c[1].
     // quick out for uniform scale (triple root)
     const float fOneThird = 1.0f / 3.0f;
     const float fEpsilon = 1e-06f;
     float fDiscr = afCoeff[2] * afCoeff[2] - 3.0f * afCoeff[1];
     if ( fDiscr <= fEpsilon )
         return -fOneThird*afCoeff[2];
     // Compute an upper bound on roots of P(x).  This assumes that A^T*A
     // has been scaled by its largest entry.
     float fX = 1.0f;
     float fPoly = afCoeff[0] + fX * (afCoeff[1] + fX * (afCoeff[2] + fX));
     if ( fPoly < 0.0f ) {
         // uses a matrix norm to find an upper bound on maximum root
         fX = (float)G3D::abs(afCoeff[0]);
         float fTmp = 1.0f + (float)G3D::abs(afCoeff[1]);
         if ( fTmp > fX )
             fX = fTmp;
         fTmp = 1.0f + (float)G3D::abs(afCoeff[2]);
         if ( fTmp > fX )
             fX = fTmp;
     }
     // Newton's method to find root
     float fTwoC2 = 2.0f * afCoeff[2];
     for (int i = 0; i < 16; ++i) {
         fPoly = afCoeff[0] + fX * (afCoeff[1] + fX * (afCoeff[2] + fX));
         if ( G3D::abs(fPoly) <= fEpsilon )
             return fX;
         float fDeriv = afCoeff[1] + fX * (fTwoC2 + 3.0f * fX);
         fX -= fPoly / fDeriv;
     }
     return fX;
 }
References G3D::abs().
Referenced by spectralNorm().
mul()
static void G3D::Matrix3::mul (const Matrix3 & A, const Matrix3 & B, Matrix3 & out) inline static
Optimized implementation of out = A * B. It is safe (but slow) to call with A, B, and out possibly pointer equal to one another.
Definition at line 213 of file Matrix3.h.
{
         if ((&out == &A) || (&out == &B)) {
             // We need a temporary anyway, so revert to the stack method.
             out = A * B;
         } else {
             // Optimized in-place multiplication.
             _mul(A, B, out);
         }
     }
References _mul().
operator const float *()
G3D::Matrix3::operator const float * () const inline
Definition at line 137 of file Matrix3.h.
{
         return (const float*)&elt[0][0];
     }
References elt.
operator float *()
G3D::Matrix3::operator float * () inline
Definition at line 133 of file Matrix3.h.
{
         return (float*)&elt[0][0];
     }
References elt.
operator!=()
bool G3D::Matrix3::operator!= (const Matrix3 & rkMatrix) const
Definition at line 245 of file Matrix3.cpp.
{
     return !operator==(rkMatrix);
 }
References operator==().
operator*() [1/3]
Matrix3 G3D::Matrix3::operator* (const Matrix3 & rkMatrix) const
Matrix-matrix multiply
Definition at line 278 of file Matrix3.cpp.
{
     Matrix3 kProd;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kProd.elt[iRow][iCol] =
                 elt[iRow][0] * rkMatrix.elt[0][iCol] +
                 elt[iRow][1] * rkMatrix.elt[1][iCol] +
                 elt[iRow][2] * rkMatrix.elt[2][iCol];
         }
     }
     return kProd;
 }
References elt.
operator*() [2/3]
Vector3 G3D::Matrix3::operator* (const Vector3 & v) const inline
matrix * vector [3x3 * 3x1 = 3x1]
Definition at line 170 of file Matrix3.h.
{
         Vector3 kProd;
         for (int r = 0; r < 3; ++r) {
             kProd[r] =
                 elt[r][0] * v[0] +
                 elt[r][1] * v[1] +
                 elt[r][2] * v[2];
         }
         return kProd;
     }
References elt.
operator*() [3/3]
Matrix3 G3D::Matrix3::operator* (float fScalar) const
matrix * scalar
Definition at line 342 of file Matrix3.cpp.
{
     Matrix3 kProd;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kProd[iRow][iCol] = fScalar * elt[iRow][iCol];
         }
     }
     return kProd;
 }
References elt.
operator*=() [1/2]
Matrix3 & G3D::Matrix3::operator*= (const Matrix3 & rkMatrix)
Definition at line 313 of file Matrix3.cpp.
{
     Matrix3 mulMat;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             mulMat.elt[iRow][iCol] =
                 elt[iRow][0] * rkMatrix.elt[0][iCol] +
                 elt[iRow][1] * rkMatrix.elt[1][iCol] +
                 elt[iRow][2] * rkMatrix.elt[2][iCol];
         }
     }
     *this = mulMat;
     return *this;
 }
References elt.
operator*=() [2/2]
Matrix3 & G3D::Matrix3::operator*= (float k)
Definition at line 358 of file Matrix3.cpp.
{
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             elt[iRow][iCol] *= fScalar;
         }
     }
     return *this;
 }
References elt.
operator+()
Matrix3 G3D::Matrix3::operator+ (const Matrix3 & rkMatrix) const
Definition at line 250 of file Matrix3.cpp.
{
     Matrix3 kSum;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kSum.elt[iRow][iCol] = elt[iRow][iCol] +
                                           rkMatrix.elt[iRow][iCol];
         }
     }
     return kSum;
 }
References elt.
operator+=()
Matrix3 & G3D::Matrix3::operator+= (const Matrix3 & rkMatrix)
Definition at line 293 of file Matrix3.cpp.
{
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             elt[iRow][iCol] = elt[iRow][iCol] + rkMatrix.elt[iRow][iCol];
         }
     }
     return *this;
 }
References elt.
operator-() [1/2]
Matrix3 G3D::Matrix3::operator- () const
Definition at line 329 of file Matrix3.cpp.
{
     Matrix3 kNeg;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kNeg[iRow][iCol] = -elt[iRow][iCol];
         }
     }
     return kNeg;
 }
References elt.
operator-() [2/2]
Matrix3 G3D::Matrix3::operator- (const Matrix3 & rkMatrix) const
Definition at line 264 of file Matrix3.cpp.
{
     Matrix3 kDiff;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kDiff.elt[iRow][iCol] = elt[iRow][iCol] -
                                            rkMatrix.elt[iRow][iCol];
         }
     }
     return kDiff;
 }
References elt.
operator-=()
Matrix3 & G3D::Matrix3::operator-= (const Matrix3 & rkMatrix)
Definition at line 303 of file Matrix3.cpp.
{
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             elt[iRow][iCol] = elt[iRow][iCol] - rkMatrix.elt[iRow][iCol];
         }
     }
     return *this;
 }
References elt.
operator/=()
Matrix3 & G3D::Matrix3::operator/= (float k)
Definition at line 354 of file Matrix3.cpp.
{
     return *this *= (1.0f / fScalar);
 }
operator<()
bool G3D::Matrix3::operator< (const Matrix3 &) const private
operator<=()
bool G3D::Matrix3::operator<= (const Matrix3 &) const private
operator=()
Matrix3& G3D::Matrix3::operator= (const Matrix3 & rkMatrix) inline
Definition at line 148 of file Matrix3.h.
{
         memcpy(elt, rkMatrix.elt, 9 * sizeof(float));
         return *this;
     }
References elt, and memcpy.
operator==()
bool G3D::Matrix3::operator== (const Matrix3 & rkMatrix) const
Definition at line 233 of file Matrix3.cpp.
{
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             if ( elt[iRow][iCol] != rkMatrix.elt[iRow][iCol] )
                 return false;
         }
     }
     return true;
 }
References elt.
Referenced by operator!=().
operator>()
bool G3D::Matrix3::operator> (const Matrix3 &) const private
operator>=()
bool G3D::Matrix3::operator>= (const Matrix3 &) const private
operator[]() [1/2]
float* G3D::Matrix3::operator[] (int iRow) inline
Member access, allows use of construct mat[r][c]
Definition at line 121 of file Matrix3.h.
{
         debugAssert(iRow >= 0);
         debugAssert(iRow < 3);
         return (float*)&elt[iRow][0];
     }
References debugAssert, and elt.
operator[]() [2/2]
const float* G3D::Matrix3::operator[] (int iRow) const inline
Definition at line 127 of file Matrix3.h.
{
         debugAssert(iRow >= 0);
         debugAssert(iRow < 3);
         return (const float*)&elt[iRow][0];
     }
References debugAssert, and elt.
orthonormalize()
void G3D::Matrix3::orthonormalize ()
Gram-Schmidt orthonormalization (applied to columns of rotation matrix)
Definition at line 838 of file Matrix3.cpp.
{
     // Algorithm uses Gram-Schmidt orthogonalization.  If 'this' matrix is
     // M = [m0|m1|m2], then orthonormal output matrix is Q = [q0|q1|q2],
     //
     //   q0 = m0/|m0|
     //   q1 = (m1-(q0*m1)q0)/|m1-(q0*m1)q0|
     //   q2 = (m2-(q0*m2)q0-(q1*m2)q1)/|m2-(q0*m2)q0-(q1*m2)q1|
     //
     // where |V| indicates length of vector V and A*B indicates dot
     // product of vectors A and B.
     // compute q0
     float fInvLength = 1.0f / sqrt(elt[0][0] * elt[0][0]
                                        + elt[1][0] * elt[1][0] +
                                        elt[2][0] * elt[2][0]);
     elt[0][0] *= fInvLength;
     elt[1][0] *= fInvLength;
     elt[2][0] *= fInvLength;
     // compute q1
     float fDot0 =
         elt[0][0] * elt[0][1] +
         elt[1][0] * elt[1][1] +
         elt[2][0] * elt[2][1];
     elt[0][1] -= fDot0 * elt[0][0];
     elt[1][1] -= fDot0 * elt[1][0];
     elt[2][1] -= fDot0 * elt[2][0];
     fInvLength = 1.0f / sqrt(elt[0][1] * elt[0][1] +
                                   elt[1][1] * elt[1][1] +
                                   elt[2][1] * elt[2][1]);
     elt[0][1] *= fInvLength;
     elt[1][1] *= fInvLength;
     elt[2][1] *= fInvLength;
     // compute q2
     float fDot1 =
         elt[0][1] * elt[0][2] +
         elt[1][1] * elt[1][2] +
         elt[2][1] * elt[2][2];
     fDot0 =
         elt[0][0] * elt[0][2] +
         elt[1][0] * elt[1][2] +
         elt[2][0] * elt[2][2];
     elt[0][2] -= fDot0 * elt[0][0] + fDot1 * elt[0][1];
     elt[1][2] -= fDot0 * elt[1][0] + fDot1 * elt[1][1];
     elt[2][2] -= fDot0 * elt[2][0] + fDot1 * elt[2][1];
     fInvLength = 1.0f / sqrt(elt[0][2] * elt[0][2] +
                                   elt[1][2] * elt[1][2] +
                                   elt[2][2] * elt[2][2]);
     elt[0][2] *= fInvLength;
     elt[1][2] *= fInvLength;
     elt[2][2] *= fInvLength;
 }
References elt.
Referenced by G3D::Matrix4::approxCoordinateFrame().
polarDecomposition()
void G3D::Matrix3::polarDecomposition (Matrix3 & R, Matrix3 & S) const
Polar decomposition of a matrix. Based on pseudocode from Nicholas J Higham, "Computing the Polar Decomposition – with Applications Siam Journal of Science and Statistical Computing, Vol 7, No. 4, October 1986.
Decomposes A into R*S, where R is orthogonal and S is symmetric.
Ken Shoemake's "Matrix animation and polar decomposition" in Proceedings of the conference on Graphics interface '92 seems to be better known in the world of graphics, but Higham's version uses a scaling constant that can lead to faster convergence than Shoemake's when the initial matrix is far from orthogonal.
Definition at line 1015 of file Matrix3.cpp.
{
     /*
       Polar decomposition of a matrix. Based on pseudocode from
       Nicholas J Higham, "Computing the Polar Decomposition -- with
       Applications Siam Journal of Science and Statistical Computing, Vol 7, No. 4,
       October 1986.
       Decomposes A into R*S, where R is orthogonal and S is symmetric.
       Ken Shoemake's "Matrix animation and polar decomposition"
       in Proceedings of the conference on Graphics interface '92
       seems to be better known in the world of graphics, but Higham's version
       uses a scaling constant that can lead to faster convergence than
       Shoemake's when the initial matrix is far from orthogonal.
     */
     Matrix3 X = *this;
     Matrix3 tmp = X.inverse();
     Matrix3 Xit = tmp.transpose();
     int iter = 0;
     const int MAX_ITERS = 100;
     const double eps = 50 * std::numeric_limits<float>::epsilon();
     const float BigEps = 50.0f * (float)eps;
     /* Higham suggests using OneNorm(Xit-X) < eps * OneNorm(X)
      * as the convergence criterion, but OneNorm(X) should quickly
      * settle down to something between 1 and 1.7, so just comparing
      * with eps seems sufficient.
      *--------------------------------------------------------------- */
     double resid = X.diffOneNorm(Xit);
     while (resid > eps && iter < MAX_ITERS) {
       tmp = X.inverse();
       Xit = tmp.transpose();
       if (resid < BigEps) {
     // close enough use simple iteration
     X += Xit;
     X *= 0.5f;
       }
       else {
     // not close to convergence, compute acceleration factor
         float gamma = sqrt( sqrt(
                   (Xit.l1Norm()* Xit.lInfNorm())/(X.l1Norm()*X.lInfNorm()) ) );
     X *= 0.5f * gamma;
     tmp = Xit;
     tmp *= 0.5f / gamma;
     X += tmp;
       }
       resid = X.diffOneNorm(Xit);
       ++iter;
     }
     R = X;
     tmp = R.transpose();
     S = tmp * (*this);
     // S := (S + S^t)/2 one more time to make sure it is symmetric
     tmp = S.transpose();
     S += tmp;
     S *= 0.5f;
 #ifdef G3D_DEBUG
     // Check iter limit
     assert(iter < MAX_ITERS);
     // Check A = R*S
     tmp = R*S;
     resid = tmp.diffOneNorm(*this);
     assert(resid < eps);
     // Check R is orthogonal
     tmp = R*R.transpose();
     resid = tmp.diffOneNorm(Matrix3::identity());
     assert(resid < eps);
     // Check that S is symmetric
     tmp = S.transpose();
     resid = tmp.diffOneNorm(S);
     assert(resid < eps);
 #endif
 }
References assert(), diffOneNorm(), G3D::eps(), identity(), l1Norm(), lInfNorm(), transpose(), and X.
qDUDecomposition()
void G3D::Matrix3::qDUDecomposition (Matrix3 & rkQ, Vector3 & rkD, Vector3 & rkU) const
orthogonal Q, diagonal D, upper triangular U stored as (u01,u02,u12)
Definition at line 901 of file Matrix3.cpp.
{
     // Factor M = QR = QDU where Q is orthogonal, D is diagonal,
     // and U is upper triangular with ones on its diagonal.  Algorithm uses
     // Gram-Schmidt orthogonalization (the QR algorithm).
     //
     // If M = [ m0 | m1 | m2 ] and Q = [ q0 | q1 | q2 ], then
     //
     //   q0 = m0/|m0|
     //   q1 = (m1-(q0*m1)q0)/|m1-(q0*m1)q0|
     //   q2 = (m2-(q0*m2)q0-(q1*m2)q1)/|m2-(q0*m2)q0-(q1*m2)q1|
     //
     // where |V| indicates length of vector V and A*B indicates dot
     // product of vectors A and B.  The matrix R has entries
     //
     //   r00 = q0*m0  r01 = q0*m1  r02 = q0*m2
     //   r10 = 0      r11 = q1*m1  r12 = q1*m2
     //   r20 = 0      r21 = 0      r22 = q2*m2
     //
     // so D = diag(r00,r11,r22) and U has entries u01 = r01/r00,
     // u02 = r02/r00, and u12 = r12/r11.
     // Q = rotation
     // D = scaling
     // U = shear
     // D stores the three diagonal entries r00, r11, r22
     // U stores the entries U[0] = u01, U[1] = u02, U[2] = u12
     // build orthogonal matrix Q
     float fInvLength = 1.0f / sqrt(elt[0][0] * elt[0][0]
                                        + elt[1][0] * elt[1][0] +
                                        elt[2][0] * elt[2][0]);
     kQ[0][0] = elt[0][0] * fInvLength;
     kQ[1][0] = elt[1][0] * fInvLength;
     kQ[2][0] = elt[2][0] * fInvLength;
     float fDot = kQ[0][0] * elt[0][1] + kQ[1][0] * elt[1][1] +
                 kQ[2][0] * elt[2][1];
     kQ[0][1] = elt[0][1] - fDot * kQ[0][0];
     kQ[1][1] = elt[1][1] - fDot * kQ[1][0];
     kQ[2][1] = elt[2][1] - fDot * kQ[2][0];
     fInvLength = 1.0f / sqrt(kQ[0][1] * kQ[0][1] + kQ[1][1] * kQ[1][1] +
                                   kQ[2][1] * kQ[2][1]);
     kQ[0][1] *= fInvLength;
     kQ[1][1] *= fInvLength;
     kQ[2][1] *= fInvLength;
     fDot = kQ[0][0] * elt[0][2] + kQ[1][0] * elt[1][2] +
            kQ[2][0] * elt[2][2];
     kQ[0][2] = elt[0][2] - fDot * kQ[0][0];
     kQ[1][2] = elt[1][2] - fDot * kQ[1][0];
     kQ[2][2] = elt[2][2] - fDot * kQ[2][0];
     fDot = kQ[0][1] * elt[0][2] + kQ[1][1] * elt[1][2] +
            kQ[2][1] * elt[2][2];
     kQ[0][2] -= fDot * kQ[0][1];
     kQ[1][2] -= fDot * kQ[1][1];
     kQ[2][2] -= fDot * kQ[2][1];
     fInvLength = 1.0f / sqrt(kQ[0][2] * kQ[0][2] + kQ[1][2] * kQ[1][2] +
                                   kQ[2][2] * kQ[2][2]);
     kQ[0][2] *= fInvLength;
     kQ[1][2] *= fInvLength;
     kQ[2][2] *= fInvLength;
     // guarantee that orthogonal matrix has determinant 1 (no reflections)
     float fDet = kQ[0][0] * kQ[1][1] * kQ[2][2] + kQ[0][1] * kQ[1][2] * kQ[2][0] +
                 kQ[0][2] * kQ[1][0] * kQ[2][1] - kQ[0][2] * kQ[1][1] * kQ[2][0] -
                 kQ[0][1] * kQ[1][0] * kQ[2][2] - kQ[0][0] * kQ[1][2] * kQ[2][1];
     if ( fDet < 0.0 ) {
         for (int iRow = 0; iRow < 3; ++iRow)
             for (int iCol = 0; iCol < 3; ++iCol)
                 kQ[iRow][iCol] = -kQ[iRow][iCol];
     }
     // build "right" matrix R
     Matrix3 kR;
     kR[0][0] = kQ[0][0] * elt[0][0] + kQ[1][0] * elt[1][0] +
                kQ[2][0] * elt[2][0];
     kR[0][1] = kQ[0][0] * elt[0][1] + kQ[1][0] * elt[1][1] +
                kQ[2][0] * elt[2][1];
     kR[1][1] = kQ[0][1] * elt[0][1] + kQ[1][1] * elt[1][1] +
                kQ[2][1] * elt[2][1];
     kR[0][2] = kQ[0][0] * elt[0][2] + kQ[1][0] * elt[1][2] +
                kQ[2][0] * elt[2][2];
     kR[1][2] = kQ[0][1] * elt[0][2] + kQ[1][1] * elt[1][2] +
                kQ[2][1] * elt[2][2];
     kR[2][2] = kQ[0][2] * elt[0][2] + kQ[1][2] * elt[1][2] +
                kQ[2][2] * elt[2][2];
     // the scaling component
     kD[0] = kR[0][0];
     kD[1] = kR[1][1];
     kD[2] = kR[2][2];
     // the shear component
     float fInvD0 = 1.0f / kD[0];
     kU[0] = kR[0][1] * fInvD0;
     kU[1] = kR[0][2] * fInvD0;
     kU[2] = kR[1][2] / kD[1];
 }
References elt.
qLAlgorithm()
bool G3D::Matrix3::qLAlgorithm (float afDiag[3], float afSubDiag[3]) protected
Definition at line 1740 of file Matrix3.cpp.
{
     // QL iteration with implicit shifting to reduce matrix from tridiagonal
     // to diagonal
     for (int i0 = 0; i0 < 3; ++i0) {
         const int iMaxIter = 32;
         int iIter;
         for (iIter = 0; iIter < iMaxIter; ++iIter) {
             int i1;
             for (i1 = i0; i1 <= 1; ++i1) {
                 float fSum = float(G3D::abs(afDiag[i1]) +
                             G3D::abs(afDiag[i1 + 1]));
                 if ( G3D::abs(afSubDiag[i1]) + fSum == fSum )
                     break;
             }
             if ( i1 == i0 )
                 break;
             float fTmp0 = (afDiag[i0 + 1] - afDiag[i0]) / (2.0f * afSubDiag[i0]);
             float fTmp1 = sqrt(fTmp0 * fTmp0 + 1.0f);
             if ( fTmp0 < 0.0 )
                 fTmp0 = afDiag[i1] - afDiag[i0] + afSubDiag[i0] / (fTmp0 - fTmp1);
             else
                 fTmp0 = afDiag[i1] - afDiag[i0] + afSubDiag[i0] / (fTmp0 + fTmp1);
             float fSin = 1.0;
             float fCos = 1.0;
             float fTmp2 = 0.0;
             for (int i2 = i1 - 1; i2 >= i0; i2--) {
                 float fTmp3 = fSin * afSubDiag[i2];
                 float fTmp4 = fCos * afSubDiag[i2];
                 if (G3D::abs(fTmp3) >= G3D::abs(fTmp0)) {
                     fCos = fTmp0 / fTmp3;
                     fTmp1 = sqrt(fCos * fCos + 1.0f);
                     afSubDiag[i2 + 1] = fTmp3 * fTmp1;
                     fSin = 1.0f / fTmp1;
                     fCos *= fSin;
                 } else {
                     fSin = fTmp3 / fTmp0;
                     fTmp1 = sqrt(fSin * fSin + 1.0f);
                     afSubDiag[i2 + 1] = fTmp0 * fTmp1;
                     fCos = 1.0f / fTmp1;
                     fSin *= fCos;
                 }
                 fTmp0 = afDiag[i2 + 1] - fTmp2;
                 fTmp1 = (afDiag[i2] - fTmp0) * fSin + 2.0f * fTmp4 * fCos;
                 fTmp2 = fSin * fTmp1;
                 afDiag[i2 + 1] = fTmp0 + fTmp2;
                 fTmp0 = fCos * fTmp1 - fTmp4;
                 for (int iRow = 0; iRow < 3; ++iRow) {
                     fTmp3 = elt[iRow][i2 + 1];
                     elt[iRow][i2 + 1] = fSin * elt[iRow][i2] +
                                                fCos * fTmp3;
                     elt[iRow][i2] = fCos * elt[iRow][i2] -
                                            fSin * fTmp3;
                 }
             }
             afDiag[i0] -= fTmp2;
             afSubDiag[i0] = fTmp0;
             afSubDiag[i1] = 0.0;
         }
         if ( iIter == iMaxIter ) {
             // should not get here under normal circumstances
             return false;
         }
     }
     return true;
 }
References G3D::abs(), and elt.
Referenced by eigenSolveSymmetric().
row()
const Vector3 & G3D::Matrix3::row (int r) const
Definition at line 210 of file Matrix3.cpp.
{
     assert((0 <= iRow) && (iRow < 3));
     return *reinterpret_cast<const Vector3*>(elt[iRow]);
 }
References assert(), and elt.
serialize()
void G3D::Matrix3::serialize (class BinaryOutput & b) const
Definition at line 192 of file Matrix3.cpp.
{
     int r,c;
     for (c = 0; c < 3; ++c) {
         for (r = 0; r < 3; ++r) {
             b.writeFloat32(elt[r][c]);
         }
     }
 }
References b, mpq::c, and elt.
Referenced by G3D::CoordinateFrame::serialize().
set()
void G3D::Matrix3::set (float fEntry00, float fEntry01, float fEntry02, float fEntry10, float fEntry11, float fEntry12, float fEntry20, float fEntry21, float fEntry22)
Sets all elements.
Definition at line 165 of file Matrix3.cpp.
{
     elt[0][0] = fEntry00;
     elt[0][1] = fEntry01;
     elt[0][2] = fEntry02;
     elt[1][0] = fEntry10;
     elt[1][1] = fEntry11;
     elt[1][2] = fEntry12;
     elt[2][0] = fEntry20;
     elt[2][1] = fEntry21;
     elt[2][2] = fEntry22;
 }
References elt.
Referenced by Matrix3().
setColumn()
void G3D::Matrix3::setColumn (int iCol, const Vector3 & vector)
Definition at line 216 of file Matrix3.cpp.
{
     debugAssert((iCol >= 0) && (iCol < 3));
     elt[0][iCol] = vector.x;
     elt[1][iCol] = vector.y;
     elt[2][iCol] = vector.z;
 }
References debugAssert, elt, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by G3D::Capsule::getReferenceFrame(), G3D::Cylinder::getReferenceFrame(), and G3D::CoordinateFrame::lookAt().
setRow()
void G3D::Matrix3::setRow (int iRow, const Vector3 & vector)
Definition at line 224 of file Matrix3.cpp.
{
     debugAssert((iRow >= 0) && (iRow < 3));
     elt[iRow][0] = vector.x;
     elt[iRow][1] = vector.y;
     elt[iRow][2] = vector.z;
 }
References debugAssert, elt, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
singularValueComposition()
void G3D::Matrix3::singularValueComposition (const Matrix3 & rkL, const Vector3 & rkS, const Matrix3 & rkR)
singular value decomposition
Definition at line 815 of file Matrix3.cpp.
{
     int iRow, iCol;
     Matrix3 kTmp;
     // product S*R
     for (iRow = 0; iRow < 3; ++iRow) {
         for (iCol = 0; iCol < 3; ++iCol)
             kTmp[iRow][iCol] = kS[iRow] * kR[iRow][iCol];
     }
     // product L*S*R
     for (iRow = 0; iRow < 3; ++iRow) {
         for (iCol = 0; iCol < 3; ++iCol) {
             elt[iRow][iCol] = 0.0;
             for (int iMid = 0; iMid < 3; ++iMid)
                 elt[iRow][iCol] += kL[iRow][iMid] * kTmp[iMid][iCol];
         }
     }
 }
References elt.
singularValueDecomposition()
void G3D::Matrix3::singularValueDecomposition (Matrix3 & rkL, Vector3 & rkS, Matrix3 & rkR) const
singular value decomposition
Definition at line 708 of file Matrix3.cpp.
{
     int iRow, iCol;
     Matrix3 kA = *this;
     bidiagonalize(kA, kL, kR);
     for (int i = 0; i < ms_iSvdMaxIterations; ++i) {
         float fTmp, fTmp0, fTmp1;
         float fSin0, fCos0, fTan0;
         float fSin1, fCos1, fTan1;
         bool bTest1 = (G3D::abs(kA[0][1]) <=
                        ms_fSvdEpsilon * (G3D::abs(kA[0][0]) + G3D::abs(kA[1][1])));
         bool bTest2 = (G3D::abs(kA[1][2]) <=
                        ms_fSvdEpsilon * (G3D::abs(kA[1][1]) + G3D::abs(kA[2][2])));
         if ( bTest1 ) {
             if ( bTest2 ) {
                 kS[0] = kA[0][0];
                 kS[1] = kA[1][1];
                 kS[2] = kA[2][2];
                 break;
             } else {
                 // 2x2 closed form factorization
                 fTmp = (kA[1][1] * kA[1][1] - kA[2][2] * kA[2][2] +
                         kA[1][2] * kA[1][2]) / (kA[1][2] * kA[2][2]);
                 fTan0 = 0.5f * (fTmp + sqrt(fTmp * fTmp + 4.0f));
                 fCos0 = 1.0f / sqrt(1.0f + fTan0 * fTan0);
                 fSin0 = fTan0 * fCos0;
                 for (iCol = 0; iCol < 3; ++iCol) {
                     fTmp0 = kL[iCol][1];
                     fTmp1 = kL[iCol][2];
                     kL[iCol][1] = fCos0 * fTmp0 - fSin0 * fTmp1;
                     kL[iCol][2] = fSin0 * fTmp0 + fCos0 * fTmp1;
                 }
                 fTan1 = (kA[1][2] - kA[2][2] * fTan0) / kA[1][1];
                 fCos1 = 1.0f / sqrt(1.0f + fTan1 * fTan1);
                 fSin1 = -fTan1 * fCos1;
                 for (iRow = 0; iRow < 3; ++iRow) {
                     fTmp0 = kR[1][iRow];
                     fTmp1 = kR[2][iRow];
                     kR[1][iRow] = fCos1 * fTmp0 - fSin1 * fTmp1;
                     kR[2][iRow] = fSin1 * fTmp0 + fCos1 * fTmp1;
                 }
                 kS[0] = kA[0][0];
                 kS[1] = fCos0 * fCos1 * kA[1][1] -
                         fSin1 * (fCos0 * kA[1][2] - fSin0 * kA[2][2]);
                 kS[2] = fSin0 * fSin1 * kA[1][1] +
                         fCos1 * (fSin0 * kA[1][2] + fCos0 * kA[2][2]);
                 break;
             }
         } else {
             if ( bTest2 ) {
                 // 2x2 closed form factorization
                 fTmp = (kA[0][0] * kA[0][0] + kA[1][1] * kA[1][1] -
                         kA[0][1] * kA[0][1]) / (kA[0][1] * kA[1][1]);
                 fTan0 = 0.5f * ( -fTmp + sqrt(fTmp * fTmp + 4.0f));
                 fCos0 = 1.0f / sqrt(1.0f + fTan0 * fTan0);
                 fSin0 = fTan0 * fCos0;
                 for (iCol = 0; iCol < 3; ++iCol) {
                     fTmp0 = kL[iCol][0];
                     fTmp1 = kL[iCol][1];
                     kL[iCol][0] = fCos0 * fTmp0 - fSin0 * fTmp1;
                     kL[iCol][1] = fSin0 * fTmp0 + fCos0 * fTmp1;
                 }
                 fTan1 = (kA[0][1] - kA[1][1] * fTan0) / kA[0][0];
                 fCos1 = 1.0f / sqrt(1.0f + fTan1 * fTan1);
                 fSin1 = -fTan1 * fCos1;
                 for (iRow = 0; iRow < 3; ++iRow) {
                     fTmp0 = kR[0][iRow];
                     fTmp1 = kR[1][iRow];
                     kR[0][iRow] = fCos1 * fTmp0 - fSin1 * fTmp1;
                     kR[1][iRow] = fSin1 * fTmp0 + fCos1 * fTmp1;
                 }
                 kS[0] = fCos0 * fCos1 * kA[0][0] -
                         fSin1 * (fCos0 * kA[0][1] - fSin0 * kA[1][1]);
                 kS[1] = fSin0 * fSin1 * kA[0][0] +
                         fCos1 * (fSin0 * kA[0][1] + fCos0 * kA[1][1]);
                 kS[2] = kA[2][2];
                 break;
             } else {
                 golubKahanStep(kA, kL, kR);
             }
         }
     }
     // positize diagonal
     for (iRow = 0; iRow < 3; ++iRow) {
         if ( kS[iRow] < 0.0 ) {
             kS[iRow] = -kS[iRow];
             for (iCol = 0; iCol < 3; ++iCol)
                 kR[iRow][iCol] = -kR[iRow][iCol];
         }
     }
 }
References G3D::abs(), bidiagonalize(), golubKahanStep(), ms_fSvdEpsilon, and ms_iSvdMaxIterations.
spectralNorm()
float G3D::Matrix3::spectralNorm () const
Matrix norms.
Definition at line 1157 of file Matrix3.cpp.
{
     Matrix3 kP;
     int iRow, iCol;
     float fPmax = 0.0;
     for (iRow = 0; iRow < 3; ++iRow) {
         for (iCol = 0; iCol < 3; ++iCol) {
             kP[iRow][iCol] = 0.0;
             for (int iMid = 0; iMid < 3; ++iMid) {
                 kP[iRow][iCol] +=
                     elt[iMid][iRow] * elt[iMid][iCol];
             }
             if ( kP[iRow][iCol] > fPmax )
                 fPmax = kP[iRow][iCol];
         }
     }
     float fInvPmax = 1.0f / fPmax;
     for (iRow = 0; iRow < 3; ++iRow) {
         for (iCol = 0; iCol < 3; ++iCol)
             kP[iRow][iCol] *= fInvPmax;
     }
     float afCoeff[3];
     afCoeff[0] = -(kP[0][0] * (kP[1][1] * kP[2][2] - kP[1][2] * kP[2][1]) +
                    kP[0][1] * (kP[2][0] * kP[1][2] - kP[1][0] * kP[2][2]) +
                    kP[0][2] * (kP[1][0] * kP[2][1] - kP[2][0] * kP[1][1]));
     afCoeff[1] = kP[0][0] * kP[1][1] - kP[0][1] * kP[1][0] +
                  kP[0][0] * kP[2][2] - kP[0][2] * kP[2][0] +
                  kP[1][1] * kP[2][2] - kP[1][2] * kP[2][1];
     afCoeff[2] = -(kP[0][0] + kP[1][1] + kP[2][2]);
     float fRoot = maxCubicRoot(afCoeff);
     float fNorm = sqrt(fPmax * fRoot);
     return fNorm;
 }
References elt, and maxCubicRoot().
squaredFrobeniusNorm()
float G3D::Matrix3::squaredFrobeniusNorm () const
Definition at line 1198 of file Matrix3.cpp.
{
     float norm2 = 0;
     const float* e = &elt[0][0];
     for (int i = 0; i < 9; ++i){
       norm2 += (*e) * (*e);
     }
     return norm2;
 }
References elt.
Referenced by frobeniusNorm().
tensorProduct()
void G3D::Matrix3::tensorProduct (const Vector3 & rkU, const Vector3 & rkV, Matrix3 & rkProduct) static
Definition at line 1851 of file Matrix3.cpp.
{
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             rkProduct[iRow][iCol] = rkU[iRow] * rkV[iCol];
         }
     }
 }
toAny()
Any G3D::Matrix3::toAny () const
Definition at line 53 of file Matrix3.cpp.
{
     Any any(Any::ARRAY, "Matrix3");
     any.resize(9);
     for (int r = 0; r < 3; ++r) {
         for (int c = 0; c < 3; ++c) {
             any[r * 3 + c] = elt[r][c];
         }
     }
     return any;
 }
References G3D::any(), G3D::Any::ARRAY, mpq::c, and elt.
toAxisAngle()
void G3D::Matrix3::toAxisAngle (Vector3 & rkAxis, float & rfRadians) const
matrix must be orthonormal
Definition at line 1262 of file Matrix3.cpp.
{
     //
     // Let (x,y,z) be the unit-length axis and let A be an angle of rotation.
     // The rotation matrix is R = I + sin(A)*P + (1-cos(A))*P^2 (Rodrigues' formula) where
     // I is the identity and
     //
     //       +-        -+
     //   P = |  0 -z +y |
     //       | +z  0 -x |
     //       | -y +x  0 |
     //       +-        -+
     //
     // If A > 0, R represents a counterclockwise rotation about the axis in
     // the sense of looking from the tip of the axis vector towards the
     // origin.  Some algebra will show that
     //
     //   cos(A) = (trace(R)-1)/2  and  R - R^t = 2*sin(A)*P
     //
     // In the event that A = pi, R-R^t = 0 which prevents us from extracting
     // the axis through P.  Instead note that R = I+2*P^2 when A = pi, so
     // P^2 = (R-I)/2.  The diagonal entries of P^2 are x^2-1, y^2-1, and
     // z^2-1.  We can solve these for axis (x,y,z).  Because the angle is pi,
     // it does not matter which sign you choose on the square roots.
     float fTrace = elt[0][0] + elt[1][1] + elt[2][2];
     float fCos = 0.5f * (fTrace - 1.0f);
     rfRadians = (float)G3D::aCos(fCos);  // in [0,PI]
     if ( rfRadians > 0.0 ) {
         if ( rfRadians < pi() ) {
             rkAxis.x = elt[2][1] - elt[1][2];
             rkAxis.y = elt[0][2] - elt[2][0];
             rkAxis.z = elt[1][0] - elt[0][1];
             rkAxis = rkAxis.direction();
         } else {
             // angle is PI
             float fHalfInverse;
             if ( elt[0][0] >= elt[1][1] ) {
                 // r00 >= r11
                 if ( elt[0][0] >= elt[2][2] ) {
                     // r00 is maximum diagonal term
                     rkAxis.x = 0.5f * sqrt(elt[0][0] -
                                                 elt[1][1] - elt[2][2] + 1.0f);
                     fHalfInverse = 0.5f / rkAxis.x;
                     rkAxis.y = fHalfInverse * elt[0][1];
                     rkAxis.z = fHalfInverse * elt[0][2];
                 } else {
                     // r22 is maximum diagonal term
                     rkAxis.z = 0.5f * sqrt(elt[2][2] -
                                                 elt[0][0] - elt[1][1] + 1.0f);
                     fHalfInverse = 0.5f / rkAxis.z;
                     rkAxis.x = fHalfInverse * elt[0][2];
                     rkAxis.y = fHalfInverse * elt[1][2];
                 }
             } else {
                 // r11 > r00
                 if ( elt[1][1] >= elt[2][2] ) {
                     // r11 is maximum diagonal term
                     rkAxis.y = 0.5f * sqrt(elt[1][1] -
                                                 elt[0][0] - elt[2][2] + 1.0f);
                     fHalfInverse = 0.5f / rkAxis.y;
                     rkAxis.x = fHalfInverse * elt[0][1];
                     rkAxis.z = fHalfInverse * elt[1][2];
                 } else {
                     // r22 is maximum diagonal term
                     rkAxis.z = 0.5f * sqrt(elt[2][2] -
                                                 elt[0][0] - elt[1][1] + 1.0f);
                     fHalfInverse = 0.5f / rkAxis.z;
                     rkAxis.x = fHalfInverse * elt[0][2];
                     rkAxis.y = fHalfInverse * elt[1][2];
                 }
             }
         }
     } else {
         // The angle is 0 and the matrix is the identity.  Any axis will
         // work, so just use the x-axis.
         rkAxis.x = 1.0;
         rkAxis.y = 0.0;
         rkAxis.z = 0.0;
     }
 }
References G3D::aCos(), G3D::Vector3::direction(), elt, G3D::pi(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
toEulerAnglesXYZ()
bool G3D::Matrix3::toEulerAnglesXYZ (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
The matrix must be orthonormal. The decomposition is yaw*pitch*roll where yaw is rotation about the Up vector, pitch is rotation about the right axis, and roll is rotation about the Direction axis.
Definition at line 1383 of file Matrix3.cpp.
{
     // rot =  cy*cz          -cy*sz           sy
     //        cz*sx*sy+cx*sz  cx*cz-sx*sy*sz -cy*sx
     //       -cx*cz*sy+sx*sz  cz*sx+cx*sy*sz  cx*cy
     if ( elt[0][2] < 1.0f ) {
         if ( elt[0][2] > -1.0f ) {
             rfXAngle = (float) G3D::aTan2( -elt[1][2], elt[2][2]);
             rfYAngle = (float) G3D::aSin(elt[0][2]);
             rfZAngle = (float) G3D::aTan2( -elt[0][1], elt[0][0]);
             return true;
         } else {
             // WARNING.  Not unique.  XA - ZA = -atan2(r10,r11)
             rfXAngle = -(float)G3D::aTan2(elt[1][0], elt[1][1]);
             rfYAngle = -(float)halfPi();
             rfZAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  XAngle + ZAngle = atan2(r10,r11)
         rfXAngle = (float)G3D::aTan2(elt[1][0], elt[1][1]);
         rfYAngle = (float)halfPi();
         rfZAngle = 0.0f;
         return false;
     }
 }
References G3D::aSin(), G3D::aTan2(), elt, and G3D::halfPi().
toEulerAnglesXZY()
bool G3D::Matrix3::toEulerAnglesXZY (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
Definition at line 1412 of file Matrix3.cpp.
{
     // rot =  cy*cz          -sz              cz*sy
     //        sx*sy+cx*cy*sz  cx*cz          -cy*sx+cx*sy*sz
     //       -cx*sy+cy*sx*sz  cz*sx           cx*cy+sx*sy*sz
     if ( elt[0][1] < 1.0f ) {
         if ( elt[0][1] > -1.0f ) {
             rfXAngle = (float) G3D::aTan2(elt[2][1], elt[1][1]);
             rfZAngle = (float) asin( -elt[0][1]);
             rfYAngle = (float) G3D::aTan2(elt[0][2], elt[0][0]);
             return true;
         } else {
             // WARNING.  Not unique.  XA - YA = atan2(r20,r22)
             rfXAngle = (float)G3D::aTan2(elt[2][0], elt[2][2]);
             rfZAngle = (float)halfPi();
             rfYAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  XA + YA = atan2(-r20,r22)
         rfXAngle = (float)G3D::aTan2( -elt[2][0], elt[2][2]);
         rfZAngle = -(float)halfPi();
         rfYAngle = 0.0f;
         return false;
     }
 }
References G3D::aTan2(), elt, and G3D::halfPi().
toEulerAnglesYXZ()
bool G3D::Matrix3::toEulerAnglesYXZ (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
Definition at line 1441 of file Matrix3.cpp.
{
     // rot =  cy*cz+sx*sy*sz  cz*sx*sy-cy*sz  cx*sy
     //        cx*sz           cx*cz          -sx
     //       -cz*sy+cy*sx*sz  cy*cz*sx+sy*sz  cx*cy
     if ( elt[1][2] < 1.0 ) {
         if ( elt[1][2] > -1.0 ) {
             rfYAngle = (float) G3D::aTan2(elt[0][2], elt[2][2]);
             rfXAngle = (float) asin( -elt[1][2]);
             rfZAngle = (float) G3D::aTan2(elt[1][0], elt[1][1]);
             return true;
         } else {
             // WARNING.  Not unique.  YA - ZA = atan2(r01,r00)
             rfYAngle = (float)G3D::aTan2(elt[0][1], elt[0][0]);
             rfXAngle = (float)halfPi();
             rfZAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  YA + ZA = atan2(-r01,r00)
         rfYAngle = (float)G3D::aTan2( -elt[0][1], elt[0][0]);
         rfXAngle = -(float)halfPi();
         rfZAngle = 0.0f;
         return false;
     }
 }
References G3D::aTan2(), elt, and G3D::halfPi().
Referenced by G3D::CoordinateFrame::getXYZYPRRadians().
toEulerAnglesYZX()
bool G3D::Matrix3::toEulerAnglesYZX (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
Definition at line 1470 of file Matrix3.cpp.
{
     // rot =  cy*cz           sx*sy-cx*cy*sz  cx*sy+cy*sx*sz
     //        sz              cx*cz          -cz*sx
     //       -cz*sy           cy*sx+cx*sy*sz  cx*cy-sx*sy*sz
     if ( elt[1][0] < 1.0 ) {
         if ( elt[1][0] > -1.0 ) {
             rfYAngle = (float) G3D::aTan2( -elt[2][0], elt[0][0]);
             rfZAngle = (float) asin(elt[1][0]);
             rfXAngle = (float) G3D::aTan2( -elt[1][2], elt[1][1]);
             return true;
         } else {
             // WARNING.  Not unique.  YA - XA = -atan2(r21,r22);
             rfYAngle = -(float)G3D::aTan2(elt[2][1], elt[2][2]);
             rfZAngle = -(float)halfPi();
             rfXAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  YA + XA = atan2(r21,r22)
         rfYAngle = (float)G3D::aTan2(elt[2][1], elt[2][2]);
         rfZAngle = (float)halfPi();
         rfXAngle = 0.0f;
         return false;
     }
 }
References G3D::aTan2(), elt, and G3D::halfPi().
toEulerAnglesZXY()
bool G3D::Matrix3::toEulerAnglesZXY (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
Definition at line 1499 of file Matrix3.cpp.
{
     // rot =  cy*cz-sx*sy*sz -cx*sz           cz*sy+cy*sx*sz
     //        cz*sx*sy+cy*sz  cx*cz          -cy*cz*sx+sy*sz
     //       -cx*sy           sx              cx*cy
     if ( elt[2][1] < 1.0 ) {
         if ( elt[2][1] > -1.0 ) {
             rfZAngle = (float) G3D::aTan2( -elt[0][1], elt[1][1]);
             rfXAngle = (float) asin(elt[2][1]);
             rfYAngle = (float) G3D::aTan2( -elt[2][0], elt[2][2]);
             return true;
         } else {
             // WARNING.  Not unique.  ZA - YA = -atan(r02,r00)
             rfZAngle = -(float)G3D::aTan2(elt[0][2], elt[0][0]);
             rfXAngle = -(float)halfPi();
             rfYAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  ZA + YA = atan2(r02,r00)
         rfZAngle = (float)G3D::aTan2(elt[0][2], elt[0][0]);
         rfXAngle = (float)halfPi();
         rfYAngle = 0.0f;
         return false;
     }
 }
References G3D::aTan2(), elt, and G3D::halfPi().
toEulerAnglesZYX()
bool G3D::Matrix3::toEulerAnglesZYX (float & rfYAngle, float & rfPAngle, float & rfRAngle) const
Definition at line 1528 of file Matrix3.cpp.
{
     // rot =  cy*cz           cz*sx*sy-cx*sz  cx*cz*sy+sx*sz
     //        cy*sz           cx*cz+sx*sy*sz -cz*sx+cx*sy*sz
     //       -sy              cy*sx           cx*cy
     if ( elt[2][0] < 1.0 ) {
         if ( elt[2][0] > -1.0 ) {
             rfZAngle = atan2f(elt[1][0], elt[0][0]);
             rfYAngle = asinf(-elt[2][0]);
             rfXAngle = atan2f(elt[2][1], elt[2][2]);
             return true;
         } else {
             // WARNING.  Not unique.  ZA - XA = -atan2(r01,r02)
             rfZAngle = -(float)G3D::aTan2(elt[0][1], elt[0][2]);
             rfYAngle = (float)halfPi();
             rfXAngle = 0.0f;
             return false;
         }
     } else {
         // WARNING.  Not unique.  ZA + XA = atan2(-r01,-r02)
         rfZAngle = (float)G3D::aTan2( -elt[0][1], -elt[0][2]);
         rfYAngle = -(float)halfPi();
         rfXAngle = 0.0f;
         return false;
     }
 }
References G3D::aTan2(), elt, and G3D::halfPi().
toString()
std::string G3D::Matrix3::toString () const
Definition at line 1932 of file Matrix3.cpp.
{
     return G3D::format("[%g, %g, %g; %g, %g, %g; %g, %g, %g]",
             elt[0][0], elt[0][1], elt[0][2],
             elt[1][0], elt[1][1], elt[1][2],
             elt[2][0], elt[2][1], elt[2][2]);
 }
References elt, and G3D::format().
transpose() [1/2]
Matrix3 G3D::Matrix3::transpose () const
Definition at line 391 of file Matrix3.cpp.
{
     Matrix3 kTranspose;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kTranspose[iRow][iCol] = elt[iCol][iRow];
         }
     }
     return kTranspose;
 }
References elt.
transpose() [2/2]
static void G3D::Matrix3::transpose (const Matrix3 & A, Matrix3 & out) inline static
Optimized implementation of out = A.transpose(). It is safe (but slow) to call with A and out possibly pointer equal to one another.
Note that A.transpose() * v can be computed more efficiently as v * A.
Definition at line 233 of file Matrix3.h.
{
         if (&A == &out) {
             out = A.transpose();
         } else {
             _transpose(A, out);
         }
     }
References _transpose(), and transpose().
Referenced by G3D::CoordinateFrame::inverse(), polarDecomposition(), and transpose().
tridiagonal()
void G3D::Matrix3::tridiagonal (float afDiag[3], float afSubDiag[3]) protected
Definition at line 1684 of file Matrix3.cpp.
{
     // Householder reduction T = Q^t M Q
     //   Input:
     //     mat, symmetric 3x3 matrix M
     //   Output:
     //     mat, orthogonal matrix Q
     //     diag, diagonal entries of T
     //     subd, subdiagonal entries of T (T is symmetric)
     float fA = elt[0][0];
     float fB = elt[0][1];
     float fC = elt[0][2];
     float fD = elt[1][1];
     float fE = elt[1][2];
     float fF = elt[2][2];
     afDiag[0] = fA;
     afSubDiag[2] = 0.0;
     if ( G3D::abs(fC) >= EPSILON ) {
         float fLength = sqrt(fB * fB + fC * fC);
         float fInvLength = 1.0f / fLength;
         fB *= fInvLength;
         fC *= fInvLength;
         float fQ = 2.0f * fB * fE + fC * (fF - fD);
         afDiag[1] = fD + fC * fQ;
         afDiag[2] = fF - fC * fQ;
         afSubDiag[0] = fLength;
         afSubDiag[1] = fE - fB * fQ;
         elt[0][0] = 1.0;
         elt[0][1] = 0.0;
         elt[0][2] = 0.0;
         elt[1][0] = 0.0;
         elt[1][1] = fB;
         elt[1][2] = fC;
         elt[2][0] = 0.0;
         elt[2][1] = fC;
         elt[2][2] = -fB;
     } else {
         afDiag[1] = fD;
         afDiag[2] = fF;
         afSubDiag[0] = fB;
         afSubDiag[1] = fE;
         elt[0][0] = 1.0;
         elt[0][1] = 0.0;
         elt[0][2] = 0.0;
         elt[1][0] = 0.0;
         elt[1][1] = 1.0;
         elt[1][2] = 0.0;
         elt[2][0] = 0.0;
         elt[2][1] = 0.0;
         elt[2][2] = 1.0;
     }
 }
References G3D::abs(), elt, and EPSILON.
Referenced by eigenSolveSymmetric().
zero()
const Matrix3 & G3D::Matrix3::zero () static
Definition at line 65 of file Matrix3.cpp.
{
     static Matrix3 m(0, 0, 0, 0, 0, 0, 0, 0, 0);
     return m;
 }
Referenced by inverse(), and G3D::Quat::toRotationMatrix().
Friends And Related Function Documentation
operator* [1/4]
Vector3 operator* (const Vector3 & rkVector, const Matrix3 & rkMatrix) friend
vector * matrix [1x3 * 3x3 = 1x3]
v * M == M.transpose() * v
Definition at line 386 of file Matrix3.h.
{
     Vector3 kProd;
     for (int r = 0; r < 3; ++r) {
         kProd[r] =
             rkPoint[0] * rkMatrix.elt[0][r] +
             rkPoint[1] * rkMatrix.elt[1][r] +
             rkPoint[2] * rkMatrix.elt[2][r];
     }
     return kProd;
 }
operator* [2/4]
Matrix3 operator* (double fScalar, const Matrix3 & rkMatrix) friend
scalar * matrix
Definition at line 370 of file Matrix3.cpp.
{
     Matrix3 kProd;
     for (int iRow = 0; iRow < 3; ++iRow) {
         for (int iCol = 0; iCol < 3; ++iCol) {
             kProd[iRow][iCol] = (float)fScalar * rkMatrix.elt[iRow][iCol];
         }
     }
     return kProd;
 }
operator* [3/4]
Matrix3 operator* (float fScalar, const Matrix3 & rkMatrix) friend
Definition at line 382 of file Matrix3.cpp.
{
     return (double)fScalar * rkMatrix;
 }
operator* [4/4]
Matrix3 operator* (int fScalar, const Matrix3 & rkMatrix) friend
Definition at line 387 of file Matrix3.cpp.
{
     return (double)fScalar * rkMatrix;
 }
Member Data Documentation
elt
float G3D::Matrix3::elt[3][3] private
Definition at line 41 of file Matrix3.h.
Referenced by _mul(), _transpose(), column(), deserialize(), determinant(), diffOneNorm(), fromColumns(), fromRows(), fromUnitAxisAngle(), fuzzyEq(), inverse(), l1Norm(), lInfNorm(), Matrix3(), operator const float *(), operator float *(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator==(), operator[](), orthonormalize(), qDUDecomposition(), qLAlgorithm(), row(), serialize(), set(), setColumn(), setRow(), singularValueComposition(), spectralNorm(), squaredFrobeniusNorm(), toAny(), toAxisAngle(), toEulerAnglesXYZ(), toEulerAnglesXZY(), toEulerAnglesYXZ(), toEulerAnglesYZX(), toEulerAnglesZXY(), toEulerAnglesZYX(), toString(), transpose(), and tridiagonal().
EPSILON
const float G3D::Matrix3::EPSILON = 1e-06f static
Definition at line 341 of file Matrix3.h.
Referenced by tridiagonal().
ms_fSvdEpsilon
const float G3D::Matrix3::ms_fSvdEpsilon = 1e-04f static protected
Definition at line 371 of file Matrix3.h.
Referenced by singularValueDecomposition().
ms_iSvdMaxIterations
const int G3D::Matrix3::ms_iSvdMaxIterations = 32 static protected
Definition at line 372 of file Matrix3.h.
Referenced by singularValueDecomposition().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Matrix3.h
deps/g3dlite/source/Matrix3.cpp