Azerotcore-wotlk: achievement_split_personality Class Reference
achievement_split_personality Class Reference
Public Member Functions
achievement_split_personality ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 327 of file boss_magus_telestra.cpp.
Constructor & Destructor Documentation
achievement_split_personality()
achievement_split_personality::achievement_split_personality () inline
Definition at line 330 of file boss_magus_telestra.cpp.
                                     : AchievementCriteriaScript("achievement_split_personality")
     {
     }
Member Function Documentation
OnCheck()
bool achievement_split_personality::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 334 of file boss_magus_telestra.cpp.
     {
         if (!target)
             return false;
         return target->GetAI()->GetData(target->GetEntry());
     }
References Unit::GetAI(), UnitAI::GetData(), and Object::GetEntry().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp