Azerotcore-wotlk: src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp File Reference
instance_naxxramas.cpp File Reference
#include "CellImpl.h"
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "naxxramas.h"
#include "PassiveAI.h"
#include "ScriptedCreature.h"
#include "ScriptMgr.h"
Classes
class instance_naxxramas
struct instance_naxxramas::instance_naxxramas_InstanceMapScript
class boss_naxxramas_misc
struct boss_naxxramas_misc::boss_naxxramas_miscAI
Functions
uint8 GetEruptionSection (float x, float y)
void AddSC_instance_naxxramas ()
Variables
const float HeiganPos [2] = {2796, -3707}
const float HeiganEruptionSlope [3]
Function Documentation
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
Definition at line 1224 of file instance_naxxramas.cpp.
 {
     new instance_naxxramas();
     new boss_naxxramas_misc();
 }
Referenced by AddNorthrendScripts().
GetEruptionSection()
uint8 GetEruptionSection (float x, float y) inline
Definition at line 34 of file instance_naxxramas.cpp.
 {
     y -= HeiganPos[1];
     if (y < 1.0f)
         return 0;
     x -= HeiganPos[0];
     if (x > -1.0f)
         return 3;
     float slope = y / x;
     for (uint32 i = 0; i < 3; ++i)
     {
         if (slope > HeiganEruptionSlope[i])
             return i;
     }
     return 3;
 }
References HeiganEruptionSlope, and HeiganPos.
Referenced by instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), and instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove().
Variable Documentation
HeiganEruptionSlope
const float HeiganEruptionSlope[3]
Initial value:
=
{
    (-3685 - HeiganPos[1]) / (2724 - HeiganPos[0]),
    (-3647 - HeiganPos[1]) / (2749 - HeiganPos[0]),
    (-3637 - HeiganPos[1]) / (2771 - HeiganPos[0]),
}
Definition at line 27 of file instance_naxxramas.cpp.
Referenced by GetEruptionSection().
HeiganPos
const float HeiganPos[2] = {2796, -3707}
Definition at line 26 of file instance_naxxramas.cpp.
Referenced by GetEruptionSection().