Azerotcore-wotlk: VehicleCheck Class Reference
VehicleCheck Class Reference
Public Member Functions
bool operator() (WorldObject *unit)
Detailed Description
Definition at line 2431 of file boss_the_lich_king.cpp.
Member Function Documentation
operator()()
bool VehicleCheck::operator() (WorldObject * unit) inline
Definition at line 2434 of file boss_the_lich_king.cpp.
     {
         return (unit->GetTypeId() != TYPEID_UNIT && unit->GetTypeId() != TYPEID_PLAYER) || unit->ToUnit()->GetVehicle();
     }
References Object::GetTypeId(), Unit::GetVehicle(), Object::ToUnit(), TYPEID_PLAYER, and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp