Azerotcore-wotlk: deps/g3dlite/include/G3D/Quat.h File Reference
Quat.h File Reference
#include "G3D/platform.h"
#include "G3D/g3dmath.h"
#include "G3D/Vector3.h"
#include "G3D/Matrix3.h"
#include <string>
Classes
class G3D::Quat
Namespaces
G3D
Functions
Quat G3D::exp (const Quat &q)
Quat G3D::log (const Quat &q)
G3D::Quat G3D::operator* (double s, const G3D::Quat &q)
G3D::Quat G3D::operator* (float s, const G3D::Quat &q)
G3D::Quat pow (const G3D::Quat &q, double x)
Detailed Description
Quaternion
\maintainer Morgan McGuire, http://graphics.cs.williams.edu
\created 2002-01-23 \edited 2011-05-10
Definition in file Quat.h.
Function Documentation
pow()
G3D::Quat pow (const G3D::Quat & q, double x) inline
Definition at line 761 of file Quat.h.
{
     return q.pow((float)x);
 }
References G3D::Quat::pow(), and G3D::x.
Referenced by G3D::Capsule::area(), G3D::PrecomputedRandom::cosPowHemi(), G3D::Random::cosPowHemi(), Spell::EffectJumpDest(), G3D::exp2(), BattlegroundSA::GetClosestGraveyard(), getSlopeAngle(), spell_hodir_biting_cold_player_aura::spell_hodir_biting_cold_player_aura_AuraScript::HandleEffectPeriodic(), npc_commandscript::HandleNpcAddFormationCommand(), spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript::HandlePeriodic(), spell_putricide_mutated_plague::spell_putricide_mutated_plague_AuraScript::HandleTriggerSpell(), spell_karazhan_overload::spell_karazhan_overload_AuraScript::PeriodicTick(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), spell_saronite_vapors_dummy::spell_saronite_vapors_dummy_AuraScript::PrepareAuraScript(), Player::SendLoot(), G3D::signedPow(), GameObject::Use(), and G3D::Capsule::volume().