Azerotcore-wotlk: SafeUnitPointer Class Reference
SafeUnitPointer Class Reference
#include <Unit.h>
Public Member Functions
SafeUnitPointer (Unit *defVal)
SafeUnitPointer (const SafeUnitPointer &)
void Initialize (Unit *defVal)
~SafeUnitPointer ()
void SetPointedTo (Unit *u)
void UnitDeleted ()
Unit * operator-> () const
void operator= (Unit *u)
operator Unit * () const
Private Attributes
Unit * ptr
Unit * defaultValue
Detailed Description
Definition at line 1401 of file Unit.h.
Constructor & Destructor Documentation
SafeUnitPointer() [1/2]
SafeUnitPointer::SafeUnitPointer (Unit * defVal) inline explicit
Definition at line 1404 of file Unit.h.
 :  ptr(defVal), defaultValue(defVal) {}
SafeUnitPointer() [2/2]
SafeUnitPointer::SafeUnitPointer (const SafeUnitPointer &) inline
Definition at line 1405 of file Unit.h.
 { ABORT(); }
References ABORT.
~SafeUnitPointer()
SafeUnitPointer::~SafeUnitPointer ()
Definition at line 3823 of file Unit.cpp.
 {
     if (ptr != defaultValue && ptr) ptr->RemovePointedBy(this);
     ptr = defaultValue;
 }
References defaultValue, ptr, and Unit::RemovePointedBy().
Member Function Documentation
Initialize()
void SafeUnitPointer::Initialize (Unit * defVal) inline
Definition at line 1406 of file Unit.h.
 { defaultValue = defVal; ptr = defVal; }
References defaultValue, and ptr.
Referenced by Player::Player().
operator Unit *()
SafeUnitPointer::operator Unit * () const inline
Definition at line 1412 of file Unit.h.
 { return ptr; }
References ptr.
operator->()
Unit* SafeUnitPointer::operator-> () const inline
Definition at line 1410 of file Unit.h.
 { return ptr; }
References ptr.
operator=()
void SafeUnitPointer::operator= (Unit * u) inline
Definition at line 1411 of file Unit.h.
 { SetPointedTo(u); }
References SetPointedTo().
SetPointedTo()
void SafeUnitPointer::SetPointedTo (Unit * u)
Definition at line 3829 of file Unit.cpp.
 {
     if (ptr != defaultValue && ptr) ptr->RemovePointedBy(this);
     ptr = u;
     if (ptr != defaultValue && ptr) ptr->AddPointedBy(this);
 }
References Unit::AddPointedBy(), defaultValue, ptr, and Unit::RemovePointedBy().
Referenced by operator=().
UnitDeleted()
void SafeUnitPointer::UnitDeleted ()
Definition at line 3836 of file Unit.cpp.
 {
     LOG_INFO("misc", "SafeUnitPointer::UnitDeleted !!!");
     if (defaultValue)
     {
         if (Player* p = defaultValue->ToPlayer())
         {
             LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (A1) - %s, %u, %u, %u, %u, %u, %u, %u",
                 p->GetGUID().ToString().c_str(), p->GetMapId(), p->GetInstanceId(), p->FindMap()->GetId(), p->IsInWorld() ? 1 : 0, p->IsDuringRemoveFromWorld() ? 1 : 0, p->IsBeingTeleported() ? 1 : 0, p->isBeingLoaded() ? 1 : 0);
             if (ptr)
                 LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (A2)");
             p->GetSession()->KickPlayer("Unit deleted");
         }
     }
     else if (ptr)
         LOG_INFO("misc", "SafeUnitPointer::UnitDeleted (B1)");
     ptr = defaultValue;
 }
References defaultValue, LOG_INFO, ptr, and Object::ToPlayer().
Member Data Documentation
defaultValue
Unit* SafeUnitPointer::defaultValue private
Definition at line 1415 of file Unit.h.
Referenced by Initialize(), SetPointedTo(), UnitDeleted(), and ~SafeUnitPointer().
ptr
Unit* SafeUnitPointer::ptr private
Definition at line 1414 of file Unit.h.
Referenced by Initialize(), operator Unit *(), operator->(), SetPointedTo(), UnitDeleted(), and ~SafeUnitPointer().
The documentation for this class was generated from the following files:
src/server/game/Entities/Unit/Unit.h
src/server/game/Entities/Unit/Unit.cpp