Azerotcore-wotlk: deps/mysqllite/mysys/mf_pack.c File Reference
mf_pack.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
static char * expand_tilde (char **path)
void pack_dirname (char *to, const char *from)
size_t cleanup_dirname (register char *to, const char *from)
size_t normalize_dirname (char *to, const char *from)
size_t unpack_dirname (char *to, const char *from)
size_t unpack_filename (char *to, const char *from)
size_t system_filename (char *to, const char *from)
char * intern_filename (char *to, const char *from)
Variables
my_bool my_use_symdir =0
Function Documentation
cleanup_dirname()
size_t cleanup_dirname (register char * to, const char * from)
Definition at line 123 of file mf_pack.c.
 {
   reg5 size_t length;
   reg2 char * pos;
   reg3 char * from_ptr;
   reg4 char * start;
   char parent[5],               /* for "FN_PARENTDIR" */
        buff[FN_REFLEN+1],*end_parentdir;
 #ifdef BACKSLASH_MBTAIL
   CHARSET_INFO *fs= fs_character_set();
 #endif
   DBUG_ENTER("cleanup_dirname");
   DBUG_PRINT("enter",("from: '%s'",from));
   start=buff;
   from_ptr=(char *) from;
 #ifdef FN_DEVCHAR
   if ((pos=strrchr(from_ptr,FN_DEVCHAR)) != 0)
   {                     /* Skip device part */
     length=(size_t) (pos-from_ptr)+1;
     start=strnmov(buff,from_ptr,length); from_ptr+=length;
   }
 #endif
   parent[0]=FN_LIBCHAR;
   length=(size_t) (strmov(parent+1,FN_PARENTDIR)-parent);
   for (pos=start ; (*pos= *from_ptr++) != 0 ; pos++)
   {
 #ifdef BACKSLASH_MBTAIL
     uint l;
     if (use_mb(fs) && (l= my_ismbchar(fs, from_ptr - 1, from_ptr + 2)))
     {
       for (l-- ; l ; *++pos= *from_ptr++, l--);
       start= pos + 1; /* Don't look inside multi-byte char */
       continue;
     }
 #endif
     if (*pos == '/')
       *pos = FN_LIBCHAR;
     if (*pos == FN_LIBCHAR)
     {
       if ((size_t) (pos-start) > length && memcmp(pos-length,parent,length) == 0)
       {                     /* If .../../; skip prev */
     pos-=length;
     if (pos != start)
     {                    /* not /../ */
       pos--;
       if (*pos == FN_HOMELIB && (pos == start || pos[-1] == FN_LIBCHAR))
       {
         if (!home_dir)
         {
           pos+=length+1;            /* Don't unpack ~/.. */
           continue;
         }
         pos=strmov(buff,home_dir)-1;    /* Unpacks ~/.. */
         if (*pos == FN_LIBCHAR)
           pos--;                /* home ended with '/' */
       }
       if (*pos == FN_CURLIB && (pos == start || pos[-1] == FN_LIBCHAR))
       {
         if (my_getwd(curr_dir,FN_REFLEN,MYF(0)))
         {
           pos+=length+1;            /* Don't unpack ./.. */
           continue;
         }
         pos=strmov(buff,curr_dir)-1;    /* Unpacks ./.. */
         if (*pos == FN_LIBCHAR)
           pos--;                /* home ended with '/' */
       }
       end_parentdir=pos;
       while (pos >= start && *pos != FN_LIBCHAR)    /* remove prev dir */
         pos--;
           if (pos[1] == FN_HOMELIB ||
               (pos > start && memcmp(pos, parent, length) == 0))
       {                 /* Don't remove ~user/ */
         pos=strmov(end_parentdir+1,parent);
         *pos=FN_LIBCHAR;
         continue;
       }
     }
       }
       else if ((size_t) (pos-start) == length-1 &&
            !memcmp(start,parent+1,length-1))
     start=pos;              /* Starts with "../" */
       else if (pos-start > 0 && pos[-1] == FN_LIBCHAR)
       {
 #ifdef FN_NETWORK_DRIVES
     if (pos-start != 1)
 #endif
       pos--;            /* Remove dupplicate '/' */
       }
       else if (pos-start > 1 && pos[-1] == FN_CURLIB && pos[-2] == FN_LIBCHAR)
     pos-=2;                 /* Skip /./ */
       else if (pos > buff+1 && pos[-1] == FN_HOMELIB && pos[-2] == FN_LIBCHAR)
       {                 /* Found ..../~/  */
     buff[0]=FN_HOMELIB;
     buff[1]=FN_LIBCHAR;
     start=buff; pos=buff+1;
       }
     }
   }
   (void) strmov(to,buff);
   DBUG_PRINT("exit",("to: '%s'",to));
   DBUG_RETURN((size_t) (pos-buff));
 } /* cleanup_dirname */
References curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FN_CURLIB, FN_DEVCHAR, FN_HOMELIB, FN_LIBCHAR, FN_PARENTDIR, FN_REFLEN, home_dir, mpq::l, G3D::length(), my_getwd(), my_ismbchar, MYF, pos(), reg2, reg3, reg4, reg5, strmov(), strnmov(), and use_mb.
Referenced by normalize_dirname(), and pack_dirname().
expand_tilde()
static char * expand_tilde (char ** path) static
Definition at line 375 of file mf_pack.c.
 {
   if (path[0][0] == FN_LIBCHAR)
     return home_dir;            /* ~/ expanded to home */
 #ifdef HAVE_GETPWNAM
   {
     char *str,save;
     struct passwd *user_entry;
     if (!(str=strchr(*path,FN_LIBCHAR)))
       str=strend(*path);
     save= *str; *str= '\0';
     user_entry=getpwnam(*path);
     *str=save;
     endpwent();
     if (user_entry)
     {
       *path=str;
       return user_entry->pw_dir;
     }
   }
 #endif
   return (char *) 0;
 }
References FN_LIBCHAR, home_dir, and strend().
Referenced by unpack_dirname().
intern_filename()
char* intern_filename (char * to, const char * from)
Definition at line 448 of file mf_pack.c.
 {
   size_t length, to_length;
   char buff[FN_REFLEN];
   if (from == to)
   {                     /* Dirname may destroy from */
     strmov(buff,from);
     from=buff;
   }
   length= dirname_part(to, from, &to_length);   /* Copy dirname & fix chars */
   (void) strmov(to + to_length,from+length);
   return (to);
 } /* intern_filename */
References dirname_part(), FN_REFLEN, G3D::length(), and strmov().
Referenced by my_basic_init(), my_path(), normalize_dirname(), and pack_dirname().
normalize_dirname()
size_t normalize_dirname (char * to, const char * from)
Convert a directory name to a format which can be compared as strings
Parameters
to result buffer, FN_REFLEN chars in length; may be == from
from 'packed' directory name, in whatever format
Returns
size of the normalized name
Ensures that last char is FN_LIBCHAR, unless it is FN_DEVCHAR
Uses cleanup_dirname
It does not expand ~/ (although, see cleanup_dirname). Nor does it do any case folding. All case-insensitive normalization should be done by the caller.
Definition at line 291 of file mf_pack.c.
 {
   size_t length;
   char buff[FN_REFLEN];
   DBUG_ENTER("normalize_dirname");
   /*
     Despite the name, this actually converts the name to the system's
     format (TODO: name this properly).
   */
   (void) intern_filename(buff, from);
   length= strlen(buff);         /* Fix that '/' is last */
   if (length &&
 #ifdef FN_DEVCHAR
       buff[length - 1] != FN_DEVCHAR &&
 #endif
       buff[length - 1] != FN_LIBCHAR && buff[length - 1] != '/')
   {
     /* we need reserve 2 bytes for the trailing slash and the zero */
     if (length >= sizeof (buff) - 1)
       length= sizeof (buff) - 2;
     buff[length]= FN_LIBCHAR;
     buff[length + 1]= '\0';
   }
   length=cleanup_dirname(to, buff);
   DBUG_RETURN(length);
 }
References cleanup_dirname(), DBUG_ENTER, DBUG_RETURN, endif(), FN_DEVCHAR, FN_LIBCHAR, FN_REFLEN, intern_filename(), and G3D::length().
Referenced by add_directory(), and unpack_dirname().
pack_dirname()
void pack_dirname (char * to, const char * from)
Definition at line 28 of file mf_pack.c.
 {
   int cwd_err;
   size_t d_length,length,UNINIT_VAR(buff_length);
   char * start;
   char buff[FN_REFLEN];
   DBUG_ENTER("pack_dirname");
   (void) intern_filename(to,from);      /* Change to intern name */
 #ifdef FN_DEVCHAR
   if ((start=strrchr(to,FN_DEVCHAR)) != 0)  /* Skip device part */
     start++;
   else
 #endif
     start=to;
   if (!(cwd_err= my_getwd(buff,FN_REFLEN,MYF(0))))
   {
     buff_length= strlen(buff);
     d_length= (size_t) (start-to);
     if ((start == to ||
      (buff_length == d_length && !memcmp(buff,start,d_length))) &&
     *start != FN_LIBCHAR && *start)
     {                       /* Put current dir before */
       bchange((uchar*) to, d_length, (uchar*) buff, buff_length, strlen(to)+1);
     }
   }
   if ((d_length= cleanup_dirname(to,to)) != 0)
   {
     length=0;
     if (home_dir)
     {
       length= strlen(home_dir);
       if (home_dir[length-1] == FN_LIBCHAR)
     length--;               /* Don't test last '/' */
     }
     if (length > 1 && length < d_length)
     {                       /* test if /xx/yy -> ~/yy */
       if (memcmp(to,home_dir,length) == 0 && to[length] == FN_LIBCHAR)
       {
     to[0]=FN_HOMELIB;           /* Filename begins with ~ */
     (void) strmov_overlapp(to+1,to+length);
       }
     }
     if (! cwd_err)
     {                       /* Test if cwd is ~/... */
       if (length > 1 && length < buff_length)
       {
     if (memcmp(buff,home_dir,length) == 0 && buff[length] == FN_LIBCHAR)
     {
       buff[0]=FN_HOMELIB;
       (void) strmov_overlapp(buff+1,buff+length);
     }
       }
       if (is_prefix(to,buff))
       {
     length= strlen(buff);
     if (to[length])
       (void) strmov_overlapp(to,to+length); /* Remove everything before */
     else
     {
       to[0]= FN_CURLIB;         /* Put ./ instead of cwd */
       to[1]= FN_LIBCHAR;
       to[2]= '\0';
     }
       }
     }
   }
   DBUG_PRINT("exit",("to: '%s'",to));
   DBUG_VOID_RETURN;
 } /* pack_dirname */
References bchange(), cleanup_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, FN_CURLIB, FN_DEVCHAR, FN_HOMELIB, FN_LIBCHAR, FN_REFLEN, home_dir, intern_filename(), is_prefix(), G3D::length(), my_getwd(), MYF, strmov_overlapp, and UNINIT_VAR.
Referenced by fn_format().
system_filename()
size_t system_filename (char * to, const char * from)
Definition at line 441 of file mf_pack.c.
 {
   return (size_t) (strmake(to,from,FN_REFLEN-1)-to);
 }
References FN_REFLEN, and strmake().
Referenced by unpack_dirname(), and unpack_filename().
unpack_dirname()
size_t unpack_dirname (char * to, const char * from)
Fixes a directory name so that can be used by open()
Parameters
to Result buffer, FN_REFLEN characters. May be == from
from 'Packed' directory name (may contain ~)
Uses normalize_dirname()
Expands ~/... to home_dir/...
Resolves MySQL's fake "foo.sym" symbolic directory names (if USE_SYMDIR)
Changes a UNIX filename to system filename (replaces / with \ on windows)
Returns
Length of new directory name (= length of to)
Definition at line 338 of file mf_pack.c.
 {
   size_t length, h_length;
   char buff[FN_REFLEN+1+4],*suffix,*tilde_expansion;
   DBUG_ENTER("unpack_dirname");
   length= normalize_dirname(buff, from);
   if (buff[0] == FN_HOMELIB)
   {
     suffix=buff+1; tilde_expansion=expand_tilde(&suffix);
     if (tilde_expansion)
     {
       length-= (size_t) (suffix-buff)-1;
       if (length+(h_length= strlen(tilde_expansion)) <= FN_REFLEN)
       {
     if ((h_length > 0) && (tilde_expansion[h_length-1] == FN_LIBCHAR))
       h_length--;
     if (buff+h_length < suffix)
       bmove(buff+h_length,suffix,length);
     else
       bmove_upp((uchar*) buff+h_length+length, (uchar*) suffix+length, length);
     bmove(buff,tilde_expansion,h_length);
       }
     }
   }
 #ifdef USE_SYMDIR
   if (my_use_symdir)
     symdirget(buff);
 #endif
   DBUG_RETURN(system_filename(to,buff));    /* Fix for open */
 } /* unpack_dirname */
References bmove_upp(), DBUG_ENTER, DBUG_RETURN, expand_tilde(), FN_HOMELIB, FN_LIBCHAR, FN_REFLEN, G3D::length(), my_use_symdir, normalize_dirname(), and system_filename().
Referenced by fn_format(), and unpack_filename().
unpack_filename()
size_t unpack_filename (char * to, const char * from)
Definition at line 418 of file mf_pack.c.
 {
   size_t length, n_length, buff_length;
   char buff[FN_REFLEN];
   DBUG_ENTER("unpack_filename");
   length=dirname_part(buff, from, &buff_length);/* copy & convert dirname */
   n_length=unpack_dirname(buff,buff);
   if (n_length+strlen(from+length) < FN_REFLEN)
   {
     (void) strmov(buff+n_length,from+length);
     length= system_filename(to,buff);       /* Fix to usably filename */
   }
   else
     length= system_filename(to,from);       /* Fix to usably filename */
   DBUG_RETURN(length);
 } /* unpack_filename */
References DBUG_ENTER, DBUG_RETURN, dirname_part(), FN_REFLEN, G3D::length(), strmov(), system_filename(), and unpack_dirname().
Variable Documentation
my_use_symdir
my_bool my_use_symdir =0
Definition at line 239 of file mf_pack.c.
Referenced by unpack_dirname().