Azerotcore-wotlk: spell_dk_death_grip Class Reference
spell_dk_death_grip Class Reference
Private Member Functions
PrepareSpellScript (spell_dk_death_grip)
SpellCastResult CheckCast ()
uint32 EntryCheck (uint32 entry)
void HandleBaseDummy (SpellEffIndex)
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1263 of file spell_dk.cpp.
Member Function Documentation
CheckCast()
SpellCastResult spell_dk_death_grip::CheckCast () inline private
Definition at line 1267 of file spell_dk.cpp.
     {
         Unit* caster = GetCaster();
         Unit* target = GetExplTargetUnit();
         if (target->GetTypeId() == TYPEID_PLAYER && caster->GetExactDist(target) < 8.0f) // xinef: should be 8.0f, but we have to add target size (1.5f)
             return SPELL_FAILED_TOO_CLOSE;
         if (caster->HasUnitState(UNIT_STATE_JUMPING) || caster->HasUnitMovementFlag(MOVEMENTFLAG_FALLING))
             return SPELL_FAILED_MOVING;
         return SPELL_CAST_OK;
     }
References SpellScript::GetCaster(), Position::GetExactDist(), SpellScript::GetExplTargetUnit(), Object::GetTypeId(), Unit::HasUnitMovementFlag(), Unit::HasUnitState(), MOVEMENTFLAG_FALLING, SPELL_CAST_OK, SPELL_FAILED_MOVING, SPELL_FAILED_TOO_CLOSE, TYPEID_PLAYER, and UNIT_STATE_JUMPING.
Referenced by Register().
EntryCheck()
uint32 spell_dk_death_grip::EntryCheck (uint32 entry) inline private
Definition at line 1281 of file spell_dk.cpp.
     {
         Creature* targetCreature = GetHitCreature();
         switch (targetCreature->GetEntry())
         {
             //Alliance Faction Champions
             case 34461:
             case 34460:
             case 34469:
             case 34467:
             case 34468:
             case 34465:
             case 34471:
             case 34466:
             case 34473:
             case 34472:
             case 34470:
             case 34463:
             case 34474:
             case 34475:
             //Horde Faction Champions
             case 34458:
             case 34451:
             case 34459:
             case 34448:
             case 34449:
             case 34445:
             case 34456:
             case 34447:
             case 34441:
             case 34454:
             case 34444:
             case 34455:
             case 34450:
             case 34453:
                 return entry;
                 break;
         }
         return 0;
     }
References Object::GetEntry(), and SpellScript::GetHitCreature().
Referenced by HandleBaseDummy().
HandleBaseDummy()
void spell_dk_death_grip::HandleBaseDummy (SpellEffIndex) inline private
Definition at line 1324 of file spell_dk.cpp.
     {
         Unit* caster = GetCaster();
         Unit* target = GetHitUnit();
         Unit* baseTarget = GetExplTargetUnit();
         Creature* targetCreature = GetHitCreature();
         if (caster != target)
         {
             if (targetCreature && (targetCreature->isWorldBoss() || targetCreature->IsDungeonBoss()) && targetCreature->GetEntry() != EntryCheck(targetCreature->GetEntry()))
             {
                 return;
             }
             else
             {
                 caster->CastSpell(target, 49560, true);
                 const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(1766); // Rogue kick
                 if (!target->IsImmunedToSpellEffect(spellInfo, EFFECT_0))
                     target->InterruptNonMeleeSpells(true);
             }
         }
         else
             baseTarget->CastSpell(caster, 49560, true);
     }
References Unit::CastSpell(), EFFECT_0, EntryCheck(), SpellScript::GetCaster(), Object::GetEntry(), SpellScript::GetExplTargetUnit(), SpellScript::GetHitCreature(), SpellScript::GetHitUnit(), Unit::InterruptNonMeleeSpells(), Creature::IsDungeonBoss(), Unit::IsImmunedToSpellEffect(), Creature::isWorldBoss(), and sSpellMgr.
Referenced by Register().
HandleDummy()
void spell_dk_death_grip::HandleDummy (SpellEffIndex) inline private
Definition at line 1349 of file spell_dk.cpp.
     {
         float casterZ = GetCaster()->GetPositionZ(); // for Ring of Valor
         WorldLocation gripPos = *GetExplTargetDest();
         if (Unit* target = GetHitUnit())
             if (!target->HasAuraType(SPELL_AURA_DEFLECT_SPELLS) || target->HasUnitState(UNIT_STATE_STUNNED)) // Deterrence
             {
                 if (target != GetCaster())
                 {
                     const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(1766); // Rogue kick
                     if (!target->IsImmunedToSpellEffect(spellInfo, EFFECT_0))
                         target->InterruptNonMeleeSpells(false, 0, false);
                 }
                 if (target->GetMapId() == 618) // for Ring of Valor
                     gripPos.m_positionZ = std::max(casterZ + 0.2f, 28.5f);
                 target->CastSpell(gripPos.GetPositionX(), gripPos.GetPositionY(), gripPos.GetPositionZ(), 57604, true);
             }
     }
References EFFECT_0, SpellScript::GetCaster(), SpellScript::GetExplTargetDest(), SpellScript::GetHitUnit(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::m_positionZ, SPELL_AURA_DEFLECT_SPELLS, sSpellMgr, and UNIT_STATE_STUNNED.
Referenced by Register().
PrepareSpellScript()
spell_dk_death_grip::PrepareSpellScript (spell_dk_death_grip) private
Register()
void spell_dk_death_grip::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1370 of file spell_dk.cpp.
     {
         if (m_scriptSpellId == 49576) // xinef: base death grip, add pvp range restriction
         {
             OnCheckCast += SpellCheckCastFn(spell_dk_death_grip::CheckCast);
             OnEffectHitTarget += SpellEffectFn(spell_dk_death_grip::HandleBaseDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
         }
         else
             OnEffectHitTarget += SpellEffectFn(spell_dk_death_grip::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
     }
References CheckCast(), EFFECT_0, HandleBaseDummy(), HandleDummy(), _SpellScript::m_scriptSpellId, SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, SpellCheckCastFn, and SpellEffectFn.
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_dk.cpp