Azerotcore-wotlk: Loot Struct Reference
Loot Struct Reference
#include <LootMgr.h>
Public Member Functions
QuestItemMap const & GetPlayerQuestItems () const
QuestItemMap const & GetPlayerFFAItems () const
QuestItemMap const & GetPlayerNonQuestNonFFAConditionalItems () const
Loot (uint32 _gold=0)
~Loot ()
void addLootValidatorRef (LootValidatorRef *pLootValidatorRef)
void clear ()
bool empty () const
bool isLooted () const
void NotifyItemRemoved (uint8 lootIndex)
void NotifyQuestItemRemoved (uint8 questIndex)
void NotifyMoneyRemoved ()
void AddLooter (ObjectGuid GUID)
void RemoveLooter (ObjectGuid GUID)
void generateMoneyLoot (uint32 minAmount, uint32 maxAmount)
bool FillLoot (uint32 lootId, LootStore const &store, Player *lootOwner, bool personal, bool noEmptyError=false, uint16 lootMode=LOOT_MODE_DEFAULT, WorldObject *lootSource=nullptr)
void AddItem (LootStoreItem const &item)
LootItem * LootItemInSlot (uint32 lootslot, Player *player, QuestItem **qitem=nullptr, QuestItem **ffaitem=nullptr, QuestItem **conditem=nullptr)
uint32 GetMaxSlotInLootFor (Player *player) const
bool hasItemForAll () const
bool hasItemFor (Player *player) const
bool hasOverThresholdItem () const
void FillNotNormalLootFor (Player *player)
Public Attributes
std::vector< LootItem > items
std::vector< LootItem > quest_items
uint32 gold
uint8 unlootedCount {0}
ObjectGuid roundRobinPlayer
ObjectGuid lootOwnerGUID
LootType loot_type {LOOT_NONE}
ObjectGuid containerGUID
GameObject * sourceGameObject {nullptr}
Private Types
typedef GuidSet PlayersLootingSet
Private Member Functions
QuestItemList * FillFFALoot (Player *player)
QuestItemList * FillQuestLoot (Player *player)
QuestItemList * FillNonQuestNonFFAConditionalLoot (Player *player)
Private Attributes
PlayersLootingSet PlayersLooting
QuestItemMap PlayerQuestItems
QuestItemMap PlayerFFAItems
QuestItemMap PlayerNonQuestNonFFAConditionalItems
LootValidatorRefMgr i_LootValidatorRefMgr
Friends
ByteBuffer & operator<< (ByteBuffer &b, LootView const &lv)
Detailed Description
Definition at line 312 of file LootMgr.h.
Member Typedef Documentation
PlayersLootingSet
typedef GuidSet Loot::PlayersLootingSet private
Definition at line 393 of file LootMgr.h.
Constructor & Destructor Documentation
Loot()
Loot::Loot (uint32 _gold = 0) inline
Definition at line 332 of file LootMgr.h.
 : gold(_gold) { }
~Loot()
Loot::~Loot () inline
Definition at line 333 of file LootMgr.h.
 { clear(); }
References clear().
Member Function Documentation
AddItem()
void Loot::AddItem (LootStoreItem const & item)
Definition at line 487 of file LootMgr.cpp.
 {
     ItemTemplate const* proto = sObjectMgr->GetItemTemplate(item.itemid);
     if (!proto)
         return;
     uint32 count = urand(item.mincount, item.maxcount);
     uint32 stacks = count / proto->GetMaxStackSize() + (count % proto->GetMaxStackSize() ? 1 : 0);
     std::vector<LootItem>& lootItems = item.needs_quest ? quest_items : items;
     uint32 limit = item.needs_quest ? MAX_NR_QUEST_ITEMS : MAX_NR_LOOT_ITEMS;
     for (uint32 i = 0; i < stacks && lootItems.size() < limit; ++i)
     {
         LootItem generatedLoot(item);
         generatedLoot.count = std::min(count, proto->GetMaxStackSize());
         generatedLoot.itemIndex = lootItems.size();
         lootItems.push_back(generatedLoot);
         count -= proto->GetMaxStackSize();
         // In some cases, a dropped item should be visible/lootable only for some players in group
         bool canSeeItemInLootWindow = false;
         if (auto player = ObjectAccessor::FindPlayer(lootOwnerGUID))
         {
             if (auto group = player->GetGroup())
             {
                 for (auto itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
                 {
                     if (auto member = itr->GetSource())
                     {
                         if (generatedLoot.AllowedForPlayer(member))
{
                             canSeeItemInLootWindow = true;
                             break;
                         }
                     }
                 }
             }
             else if (generatedLoot.AllowedForPlayer(player))
             {
                 canSeeItemInLootWindow = true;
             }
         }
         if (!canSeeItemInLootWindow)
         {
             LOG_DEBUG("loot", "Skipping ++unlootedCount for unlootable item: %u", item.itemid);
             continue;
         }
         // non-conditional one-player only items are counted here,
         // free for all items are counted in FillFFALoot(),
         // non-ffa conditionals are counted in FillNonQuestNonFFAConditionalLoot()
         if (!item.needs_quest && item.conditions.empty() && !(proto->Flags & ITEM_FLAG_MULTI_DROP))
             ++unlootedCount;
     }
 }
References LootItem::AllowedForPlayer(), LootStoreItem::conditions, count(), LootItem::count, ObjectAccessor::FindPlayer(), ItemTemplate::Flags, Player::GetGroup(), ItemTemplate::GetMaxStackSize(), ITEM_FLAG_MULTI_DROP, LootStoreItem::itemid, LootItem::itemIndex, items, LOG_DEBUG, lootOwnerGUID, MAX_NR_LOOT_ITEMS, MAX_NR_QUEST_ITEMS, LootStoreItem::maxcount, min, LootStoreItem::mincount, LootStoreItem::needs_quest, quest_items, sObjectMgr, unlootedCount, and urand().
Referenced by LootTemplate::Process(), and LootTemplate::LootGroup::Process().
AddLooter()
void Loot::AddLooter (ObjectGuid GUID) inline
Definition at line 372 of file LootMgr.h.
 { PlayersLooting.insert(GUID); }
References PlayersLooting.
Referenced by Player::SendLoot().
addLootValidatorRef()
void Loot::addLootValidatorRef (LootValidatorRef * pLootValidatorRef) inline
Definition at line 336 of file LootMgr.h.
     {
         i_LootValidatorRefMgr.insertFirst(pLootValidatorRef);
     }
References i_LootValidatorRefMgr, and LinkedListHead::insertFirst().
Referenced by Roll::targetObjectBuildLink().
clear()
void Loot::clear () inline
Definition at line 342 of file LootMgr.h.
     {
         for (QuestItemMap::const_iterator itr = PlayerQuestItems.begin(); itr != PlayerQuestItems.end(); ++itr)
             delete itr->second;
         PlayerQuestItems.clear();
         for (QuestItemMap::const_iterator itr = PlayerFFAItems.begin(); itr != PlayerFFAItems.end(); ++itr)
             delete itr->second;
         PlayerFFAItems.clear();
         for (QuestItemMap::const_iterator itr = PlayerNonQuestNonFFAConditionalItems.begin(); itr != PlayerNonQuestNonFFAConditionalItems.end(); ++itr)
             delete itr->second;
         PlayerNonQuestNonFFAConditionalItems.clear();
         PlayersLooting.clear();
         items.clear();
         quest_items.clear();
         gold = 0;
         unlootedCount = 0;
         roundRobinPlayer.Clear();
         i_LootValidatorRefMgr.clearReferences();
         loot_type = LOOT_NONE;
     }
References ObjectGuid::Clear(), RefMgr< TO, FROM >::clearReferences(), gold, i_LootValidatorRefMgr, items, LOOT_NONE, loot_type, PlayerFFAItems, PlayerNonQuestNonFFAConditionalItems, PlayerQuestItems, PlayersLooting, quest_items, roundRobinPlayer, and unlootedCount.
Referenced by NPCStaveQuestAI::ClearLootIfUnfair(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), WorldSession::DoLootRelease(), GameObject::GetFishLoot(), GameObject::GetFishLootJunk(), Unit::Kill(), Creature::RemoveCorpse(), Player::SendLoot(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), GameObject::Update(), and ~Loot().
empty()
bool Loot::empty () const inline
Definition at line 366 of file LootMgr.h.
 { return items.empty() && gold == 0; }
References gold, and items.
Referenced by GameObject::GetFishLoot(), GameObject::GetFishLootJunk(), gobject_commandscript::HandleGameObjectInfoCommand(), Unit::Kill(), and Player::SendLoot().
FillFFALoot()
QuestItemList * Loot::FillFFALoot (Player * player) private
Definition at line 635 of file LootMgr.cpp.
 {
     QuestItemList* ql = new QuestItemList();
     for (uint8 i = 0; i < items.size(); ++i)
     {
         LootItem& item = items[i];
         if (!item.is_looted && item.freeforall && item.AllowedForPlayer(player))
         {
             ql->push_back(QuestItem(i));
             ++unlootedCount;
         }
     }
     if (ql->empty())
     {
         delete ql;
         return nullptr;
     }
     PlayerFFAItems[player->GetGUID()] = ql;
     return ql;
 }
References LootItem::AllowedForPlayer(), LootItem::freeforall, Object::GetGUID(), LootItem::is_looted, items, PlayerFFAItems, and unlootedCount.
Referenced by FillNotNormalLootFor().
FillLoot()
bool Loot::FillLoot (uint32 lootId, LootStore const & store, Player * lootOwner, bool personal, bool noEmptyError = false, uint16 lootMode = LOOT_MODE_DEFAULT, WorldObject * lootSource = nullptr)
Definition at line 546 of file LootMgr.cpp.
 {
     // Must be provided
     if (!lootOwner)
         return false;
     lootOwnerGUID = lootOwner->GetGUID();
     LootTemplate const* tab = store.GetLootFor(lootId);
     if (!tab)
     {
         if (!noEmptyError)
             LOG_ERROR("sql.sql", "Table '%s' loot id #%u used but it doesn't have records.", store.GetName(), lootId);
         return false;
     }
     items.reserve(MAX_NR_LOOT_ITEMS);
     quest_items.reserve(MAX_NR_QUEST_ITEMS);
     tab->Process(*this, store, lootMode, lootOwner);          // Processing is done there, callback via Loot::AddItem()
     sScriptMgr->OnAfterLootTemplateProcess(this, tab, store, lootOwner, personal, noEmptyError, lootMode);
     // Setting access rights for group loot case
     Group* group = lootOwner->GetGroup();
     if (!personal && group)
     {
         roundRobinPlayer = lootOwner->GetGUID();
         for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
         {
             if (Player* player = itr->GetSource()) // should actually be looted object instead of lootOwner but looter has to be really close so doesnt really matter
             {
                 if (player->IsAtLootRewardDistance(lootSource ? lootSource : lootOwner))
                 {
                     FillNotNormalLootFor(player);
                 }
             }
         }
         for (uint8 i = 0; i < items.size(); ++i)
         {
             if (ItemTemplate const* proto = sObjectMgr->GetItemTemplate(items[i].itemid))
                 if (proto->Quality < uint32(group->GetLootThreshold()))
                     items[i].is_underthreshold = true;
         }
     }
     // ... for personal loot
     else
         FillNotNormalLootFor(lootOwner);
     return true;
 }
References FillNotNormalLootFor(), Group::GetFirstMember(), Player::GetGroup(), Object::GetGUID(), LootStore::GetLootFor(), Group::GetLootThreshold(), LootStore::GetName(), Player::IsAtLootRewardDistance(), items, LOG_ERROR, lootOwnerGUID, MAX_NR_LOOT_ITEMS, MAX_NR_QUEST_ITEMS, GroupReference::next(), LootTemplate::Process(), quest_items, roundRobinPlayer, sObjectMgr, and sScriptMgr.
Referenced by Player::AutoStoreLoot(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), GameObject::GetFishLoot(), GameObject::GetFishLootJunk(), Unit::Kill(), MailDraft::prepareItems(), Player::SendLoot(), and boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies().
FillNonQuestNonFFAConditionalLoot()
QuestItemList * Loot::FillNonQuestNonFFAConditionalLoot (Player * player) private
Definition at line 696 of file LootMgr.cpp.
 {
     QuestItemList* ql = new QuestItemList();
     for (uint8 i = 0; i < items.size(); ++i)
     {
         LootItem& item = items[i];
         if (!item.is_looted && !item.freeforall && (item.AllowedForPlayer(player) || (item.follow_loot_rules && player->GetGroup() && ((player->GetGroup()->GetLootMethod() == MASTER_LOOT && player->GetGroup()->GetMasterLooterGuid() == player->GetGUID()) || player->GetGroup()->GetLootMethod() != MASTER_LOOT ))))
         {
             item.AddAllowedLooter(player);
             if (!item.conditions.empty())
             {
                 ql->push_back(QuestItem(i));
                 if (!item.is_counted)
                 {
                     ++unlootedCount;
                     item.is_counted = true;
                 }
             }
         }
     }
     if (ql->empty())
     {
         delete ql;
         return nullptr;
     }
     PlayerNonQuestNonFFAConditionalItems[player->GetGUID()] = ql;
     return ql;
 }
References LootItem::AddAllowedLooter(), LootItem::AllowedForPlayer(), LootItem::conditions, LootItem::follow_loot_rules, LootItem::freeforall, Player::GetGroup(), Object::GetGUID(), Group::GetLootMethod(), Group::GetMasterLooterGuid(), LootItem::is_counted, LootItem::is_looted, items, MASTER_LOOT, PlayerNonQuestNonFFAConditionalItems, and unlootedCount.
Referenced by FillNotNormalLootFor().
FillNotNormalLootFor()
void Loot::FillNotNormalLootFor (Player * player)
Definition at line 601 of file LootMgr.cpp.
 {
     ObjectGuid playerGuid = player->GetGUID();
     QuestItemMap::const_iterator qmapitr = PlayerQuestItems.find(playerGuid);
     if (qmapitr == PlayerQuestItems.end())
         FillQuestLoot(player);
     qmapitr = PlayerFFAItems.find(playerGuid);
     if (qmapitr == PlayerFFAItems.end())
         FillFFALoot(player);
     qmapitr = PlayerNonQuestNonFFAConditionalItems.find(playerGuid);
     if (qmapitr == PlayerNonQuestNonFFAConditionalItems.end())
         FillNonQuestNonFFAConditionalLoot(player);
     // Process currency items
     uint32 max_slot = GetMaxSlotInLootFor(player);
     LootItem const* item = nullptr;
     uint32 itemsSize = uint32(items.size());
     for (uint32 i = 0; i < max_slot; ++i)
     {
         if (i < items.size())
             item = &items[i];
         else
             item = &quest_items[i - itemsSize];
         if (!item->is_looted && item->freeforall && item->AllowedForPlayer(player))
             if (ItemTemplate const* proto = sObjectMgr->GetItemTemplate(item->itemid))
                 if (proto->IsCurrencyToken())
                     player->StoreLootItem(i, this);
     }
 }
References LootItem::AllowedForPlayer(), FillFFALoot(), FillNonQuestNonFFAConditionalLoot(), FillQuestLoot(), LootItem::freeforall, Object::GetGUID(), GetMaxSlotInLootFor(), LootItem::is_looted, LootItem::itemid, items, PlayerFFAItems, PlayerNonQuestNonFFAConditionalItems, PlayerQuestItems, quest_items, sObjectMgr, and Player::StoreLootItem().
Referenced by FillLoot(), and LootItemStorage::LoadStoredLoot().
FillQuestLoot()
QuestItemList * Loot::FillQuestLoot (Player * player) private
Definition at line 658 of file LootMgr.cpp.
 {
     if (items.size() == MAX_NR_LOOT_ITEMS)
         return nullptr;
     QuestItemList* ql = new QuestItemList();
     for (uint8 i = 0; i < quest_items.size(); ++i)
     {
         LootItem& item = quest_items[i];
         if (!item.is_looted && (item.AllowedForPlayer(player, false, false) || (item.follow_loot_rules && player->GetGroup() && ((player->GetGroup()->GetLootMethod() == MASTER_LOOT && player->GetGroup()->GetMasterLooterGuid() == player->GetGUID()) || player->GetGroup()->GetLootMethod() != MASTER_LOOT ))))
         {
             ql->push_back(QuestItem(i));
             // quest items get blocked when they first appear in a
             // player's quest vector
             //
             // increase once if one looter only, looter-times if free for all
             if (item.freeforall || !item.is_blocked)
                 ++unlootedCount;
             if (!player->GetGroup() || (player->GetGroup()->GetLootMethod() != GROUP_LOOT && player->GetGroup()->GetLootMethod() != ROUND_ROBIN))
                 item.is_blocked = true;
             if (items.size() + ql->size() == MAX_NR_LOOT_ITEMS)
                 break;
         }
     }
     if (ql->empty())
     {
         delete ql;
         return nullptr;
     }
     PlayerQuestItems[player->GetGUID()] = ql;
     return ql;
 }
References LootItem::AllowedForPlayer(), LootItem::follow_loot_rules, LootItem::freeforall, Player::GetGroup(), Object::GetGUID(), Group::GetLootMethod(), Group::GetMasterLooterGuid(), GROUP_LOOT, LootItem::is_blocked, LootItem::is_looted, items, MASTER_LOOT, MAX_NR_LOOT_ITEMS, PlayerQuestItems, quest_items, ROUND_ROBIN, and unlootedCount.
Referenced by FillNotNormalLootFor().
generateMoneyLoot()
void Loot::generateMoneyLoot (uint32 minAmount, uint32 maxAmount)
Definition at line 795 of file LootMgr.cpp.
 {
     if (maxAmount > 0)
     {
         if (maxAmount <= minAmount)
             gold = uint32(maxAmount * sWorld->getRate(RATE_DROP_MONEY));
         else if ((maxAmount - minAmount) < 32700)
             gold = uint32(urand(minAmount, maxAmount) * sWorld->getRate(RATE_DROP_MONEY));
         else
             gold = uint32(urand(minAmount >> 8, maxAmount >> 8) * sWorld->getRate(RATE_DROP_MONEY)) << 8;
     }
 }
References gold, RATE_DROP_MONEY, sWorld, and urand().
Referenced by Unit::Kill(), and Player::SendLoot().
GetMaxSlotInLootFor()
uint32 Loot::GetMaxSlotInLootFor (Player * player) const
Definition at line 873 of file LootMgr.cpp.
 {
     QuestItemMap::const_iterator itr = PlayerQuestItems.find(player->GetGUID());
     return items.size() + (itr != PlayerQuestItems.end() ?  itr->second->size() : 0);
 }
References Object::GetGUID(), items, and PlayerQuestItems.
Referenced by Player::AutoStoreLoot(), FillNotNormalLootFor(), and MailDraft::prepareItems().
GetPlayerFFAItems()
QuestItemMap const& Loot::GetPlayerFFAItems () const inline
Definition at line 317 of file LootMgr.h.
 { return PlayerFFAItems; }
References PlayerFFAItems.
Referenced by hasItemFor().
GetPlayerNonQuestNonFFAConditionalItems()
QuestItemMap const& Loot::GetPlayerNonQuestNonFFAConditionalItems () const inline
Definition at line 318 of file LootMgr.h.
 { return PlayerNonQuestNonFFAConditionalItems; }
References PlayerNonQuestNonFFAConditionalItems.
Referenced by hasItemFor().
GetPlayerQuestItems()
QuestItemMap const& Loot::GetPlayerQuestItems () const inline
Definition at line 316 of file LootMgr.h.
 { return PlayerQuestItems; }
References PlayerQuestItems.
Referenced by hasItemFor(), and Player::StoreLootItem().
hasItemFor()
bool Loot::hasItemFor (Player * player) const
Definition at line 894 of file LootMgr.cpp.
 {
     QuestItemMap const& lootPlayerQuestItems = GetPlayerQuestItems();
     QuestItemMap::const_iterator q_itr = lootPlayerQuestItems.find(player->GetGUID());
     if (q_itr != lootPlayerQuestItems.end())
     {
         QuestItemList* q_list = q_itr->second;
         for (QuestItemList::const_iterator qi = q_list->begin(); qi != q_list->end(); ++qi)
         {
             const LootItem& item = quest_items[qi->index];
             if (!qi->is_looted && !item.is_looted)
                 return true;
         }
     }
     QuestItemMap const& lootPlayerFFAItems = GetPlayerFFAItems();
     QuestItemMap::const_iterator ffa_itr = lootPlayerFFAItems.find(player->GetGUID());
     if (ffa_itr != lootPlayerFFAItems.end())
     {
         QuestItemList* ffa_list = ffa_itr->second;
         for (QuestItemList::const_iterator fi = ffa_list->begin(); fi != ffa_list->end(); ++fi)
         {
             const LootItem& item = items[fi->index];
             if (!fi->is_looted && !item.is_looted)
                 return true;
         }
     }
     QuestItemMap const& lootPlayerNonQuestNonFFAConditionalItems = GetPlayerNonQuestNonFFAConditionalItems();
     QuestItemMap::const_iterator nn_itr = lootPlayerNonQuestNonFFAConditionalItems.find(player->GetGUID());
     if (nn_itr != lootPlayerNonQuestNonFFAConditionalItems.end())
     {
         QuestItemList* conditional_list = nn_itr->second;
         for (QuestItemList::const_iterator ci = conditional_list->begin(); ci != conditional_list->end(); ++ci)
         {
             const LootItem& item = items[ci->index];
             if (!ci->is_looted && !item.is_looted)
                 return true;
         }
     }
     return false;
 }
References Object::GetGUID(), GetPlayerFFAItems(), GetPlayerNonQuestNonFFAConditionalItems(), GetPlayerQuestItems(), LootItem::is_looted, items, and quest_items.
Referenced by Player::isAllowedToLoot().
hasItemForAll()
bool Loot::hasItemForAll () const
Definition at line 879 of file LootMgr.cpp.
 {
     // Gold is always lootable
     if (gold)
     {
         return true;
     }
     for (LootItem const& item : items)
         if (!item.is_looted && !item.freeforall && item.conditions.empty())
             return true;
     return false;
 }
References gold, and items.
Referenced by Player::isAllowedToLoot().
hasOverThresholdItem()
bool Loot::hasOverThresholdItem () const
Definition at line 939 of file LootMgr.cpp.
 {
     for (uint8 i = 0; i < items.size(); ++i)
     {
         if (!items[i].is_looted && !items[i].is_underthreshold && !items[i].freeforall)
             return true;
     }
     return false;
 }
References items.
Referenced by Player::isAllowedToLoot(), and Group::SendLooter().
isLooted()
bool Loot::isLooted () const inline
Definition at line 367 of file LootMgr.h.
 { return gold == 0 && unlootedCount == 0; }
References gold, and unlootedCount.
Referenced by LootItemStorage::AddNewStoredLoot(), Spell::CheckCast(), Group::CountTheRoll(), WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), gobject_commandscript::HandleGameObjectInfoCommand(), WorldSession::HandleLootMoneyOpcode(), Player::isAllowedToLoot(), and Player::SendLoot().
LootItemInSlot()
LootItem * Loot::LootItemInSlot (uint32 lootslot, Player * player, QuestItem ** qitem = nullptr, QuestItem ** ffaitem = nullptr, QuestItem ** conditem = nullptr)
Definition at line 808 of file LootMgr.cpp.
 {
     LootItem* item = nullptr;
     bool is_looted = true;
     if (lootSlot >= items.size())
     {
         uint32 questSlot = lootSlot - items.size();
         QuestItemMap::const_iterator itr = PlayerQuestItems.find(player->GetGUID());
         if (itr != PlayerQuestItems.end() && questSlot < itr->second->size())
         {
             QuestItem* qitem2 = &itr->second->at(questSlot);
             if (qitem)
                 *qitem = qitem2;
             item = &quest_items[qitem2->index];
             if (item->follow_loot_rules && !item->AllowedForPlayer(player)) // pussywizard: such items (follow_loot_rules) are added to every player, but not everyone is allowed, check it here
                 return nullptr;
             is_looted = qitem2->is_looted;
         }
     }
     else
     {
         item = &items[lootSlot];
         is_looted = item->is_looted;
         if (item->freeforall)
         {
             QuestItemMap::const_iterator itr = PlayerFFAItems.find(player->GetGUID());
             if (itr != PlayerFFAItems.end())
             {
                 for (QuestItemList::const_iterator iter = itr->second->begin(); iter != itr->second->end(); ++iter)
                     if (iter->index == lootSlot)
                     {
                         QuestItem* ffaitem2 = (QuestItem*) & (*iter);
                         if (ffaitem)
                             *ffaitem = ffaitem2;
                         is_looted = ffaitem2->is_looted;
                         break;
                     }
             }
         }
         else if (!item->conditions.empty())
         {
             QuestItemMap::const_iterator itr = PlayerNonQuestNonFFAConditionalItems.find(player->GetGUID());
             if (itr != PlayerNonQuestNonFFAConditionalItems.end())
             {
                 for (QuestItemList::const_iterator iter = itr->second->begin(); iter != itr->second->end(); ++iter)
                 {
                     if (iter->index == lootSlot)
                     {
                         QuestItem* conditem2 = (QuestItem*) & (*iter);
                         if (conditem)
                             *conditem = conditem2;
                         is_looted = conditem2->is_looted;
                         break;
                     }
                 }
             }
         }
     }
     if (is_looted)
         return nullptr;
     return item;
 }
References LootItem::AllowedForPlayer(), LootItem::conditions, LootItem::follow_loot_rules, LootItem::freeforall, Object::GetGUID(), QuestItem::index, LootItem::is_looted, QuestItem::is_looted, items, PlayerFFAItems, PlayerNonQuestNonFFAConditionalItems, PlayerQuestItems, and quest_items.
Referenced by Player::AutoStoreLoot(), MailDraft::prepareItems(), and Player::StoreLootItem().
NotifyItemRemoved()
void Loot::NotifyItemRemoved (uint8 lootIndex)
Definition at line 730 of file LootMgr.cpp.
 {
     // notify all players that are looting this that the item was removed
     // convert the index to the slot the player sees
     PlayersLootingSet::iterator i_next;
     for (PlayersLootingSet::iterator i = PlayersLooting.begin(); i != PlayersLooting.end(); i = i_next)
     {
         i_next = i;
         ++i_next;
         if (Player* player = ObjectAccessor::FindPlayer(*i))
             player->SendNotifyLootItemRemoved(lootIndex);
         else
             PlayersLooting.erase(i);
     }
 }
References ObjectAccessor::FindPlayer(), PlayersLooting, and Player::SendNotifyLootItemRemoved().
Referenced by Group::CountTheRoll(), WorldSession::HandleLootMasterGiveOpcode(), and Player::StoreLootItem().
NotifyMoneyRemoved()
void Loot::NotifyMoneyRemoved ()
Definition at line 746 of file LootMgr.cpp.
 {
     // notify all players that are looting this that the money was removed
     PlayersLootingSet::iterator i_next;
     for (PlayersLootingSet::iterator i = PlayersLooting.begin(); i != PlayersLooting.end(); i = i_next)
     {
         i_next = i;
         ++i_next;
         if (Player* player = ObjectAccessor::FindPlayer(*i))
             player->SendNotifyLootMoneyRemoved();
         else
             PlayersLooting.erase(i);
     }
 }
References ObjectAccessor::FindPlayer(), PlayersLooting, and Player::SendNotifyLootMoneyRemoved().
Referenced by WorldSession::HandleLootMoneyOpcode().
NotifyQuestItemRemoved()
void Loot::NotifyQuestItemRemoved (uint8 questIndex)
Definition at line 761 of file LootMgr.cpp.
 {
     // when a free for all questitem is looted
     // all players will get notified of it being removed
     // (other questitems can be looted by each group member)
     // bit inefficient but isn't called often
     PlayersLootingSet::iterator i_next;
     for (PlayersLootingSet::iterator i = PlayersLooting.begin(); i != PlayersLooting.end(); i = i_next)
     {
         i_next = i;
         ++i_next;
         if (Player* player = ObjectAccessor::FindPlayer(*i))
         {
             QuestItemMap::const_iterator pq = PlayerQuestItems.find(player->GetGUID());
             if (pq != PlayerQuestItems.end() && pq->second)
             {
                 // find where/if the player has the given item in it's vector
                 QuestItemList& pql = *pq->second;
                 uint8 j;
                 for (j = 0; j < pql.size(); ++j)
                     if (pql[j].index == questIndex)
                         break;
                 if (j < pql.size())
                     player->SendNotifyLootItemRemoved(items.size() + j);
             }
         }
         else
             PlayersLooting.erase(i);
     }
 }
References ObjectAccessor::FindPlayer(), Object::GetGUID(), index, items, PlayerQuestItems, PlayersLooting, and Player::SendNotifyLootItemRemoved().
Referenced by Player::StoreLootItem().
RemoveLooter()
void Loot::RemoveLooter (ObjectGuid GUID) inline
Definition at line 373 of file LootMgr.h.
 { PlayersLooting.erase(GUID); }
References PlayersLooting.
Referenced by WorldSession::DoLootRelease().
Friends And Related Function Documentation
operator<<
ByteBuffer& operator<< (ByteBuffer & b, LootView const & lv) friend
Definition at line 961 of file LootMgr.cpp.
 {
     if (lv.permission == NONE_PERMISSION)
     {
         b << uint32(0);                                     //gold
         b << uint8(0);                                      // item count
         return b;                                           // nothing output more
     }
     Loot& l = lv.loot;
     uint8 itemsShown = 0;
     b << uint32(l.gold);                                    //gold
     size_t count_pos = b.wpos();                            // pos of item count byte
     b << uint8(0);                                          // item count placeholder
     switch (lv.permission)
     {
         case GROUP_PERMISSION:
         case MASTER_PERMISSION:
         case RESTRICTED_PERMISSION:
             {
                 bool isMasterLooter = lv.viewer->GetGroup() && lv.viewer->GetGroup()->GetMasterLooterGuid() == lv.viewer->GetGUID();
                 // if you are not the round-robin group looter, you can only see
                 // blocked rolled items and quest items, and !ffa items
                 for (uint8 i = 0; i < l.items.size(); ++i)
                 {
                     if (!l.items[i].is_looted && !l.items[i].freeforall && (l.items[i].conditions.empty() || isMasterLooter) && l.items[i].AllowedForPlayer(lv.viewer))
                     {
                         uint8 slot_type = 0;
                         if (l.items[i].is_blocked) // for ML & restricted is_blocked = !is_underthreshold
{
                             switch (lv.permission)
{
                                 case GROUP_PERMISSION:
                                     slot_type = LOOT_SLOT_TYPE_ROLL_ONGOING;
                                     break;
                                 case MASTER_PERMISSION:
{
                                         if (lv.viewer->GetGroup())
{
                                             if (lv.viewer->GetGroup()->GetMasterLooterGuid() == lv.viewer->GetGUID())
                                                 slot_type = LOOT_SLOT_TYPE_MASTER;
                                             else
                                                 slot_type = LOOT_SLOT_TYPE_LOCKED;
                                         }
                                         break;
                                     }
                                 case RESTRICTED_PERMISSION:
                                     slot_type = LOOT_SLOT_TYPE_LOCKED;
                                     break;
                                 default:
                                     continue;
                             }
                         }
                         else if (l.items[i].rollWinnerGUID)
{
                             if (l.items[i].rollWinnerGUID == lv.viewer->GetGUID())
                                 slot_type = LOOT_SLOT_TYPE_OWNER;
                             else
                                 continue;
                         }
                         else if (!l.roundRobinPlayer || lv.viewer->GetGUID() == l.roundRobinPlayer || !l.items[i].is_underthreshold)
{
                             // no round robin owner or he has released the loot
                             // or it IS the round robin group owner
                             // => item is lootable
                             slot_type = LOOT_SLOT_TYPE_ALLOW_LOOT;
                         }
                         else
                             // item shall not be displayed.
                             continue;
                         b << uint8(i) << l.items[i];
                         b << uint8(slot_type);
                         ++itemsShown;
                     }
                 }
                 break;
             }
         case ROUND_ROBIN_PERMISSION:
             {
                 for (uint8 i = 0; i < l.items.size(); ++i)
                 {
                     if (!l.items[i].is_looted && !l.items[i].freeforall && l.items[i].conditions.empty() && l.items[i].AllowedForPlayer(lv.viewer))
                     {
                         if (l.roundRobinPlayer && lv.viewer->GetGUID() != l.roundRobinPlayer)
                             // item shall not be displayed.
                             continue;
                         b << uint8(i) << l.items[i];
                         b << uint8(LOOT_SLOT_TYPE_ALLOW_LOOT);
                         ++itemsShown;
                     }
                 }
                 break;
             }
         case ALL_PERMISSION:
         case OWNER_PERMISSION:
             {
                 uint8 slot_type = lv.permission == OWNER_PERMISSION ? LOOT_SLOT_TYPE_OWNER : LOOT_SLOT_TYPE_ALLOW_LOOT;
                 for (uint8 i = 0; i < l.items.size(); ++i)
                 {
                     if (!l.items[i].is_looted && !l.items[i].freeforall && l.items[i].conditions.empty() && l.items[i].AllowedForPlayer(lv.viewer))
                     {
                         b << uint8(i) << l.items[i];
                         b << uint8(slot_type);
                         ++itemsShown;
                     }
                 }
                 break;
             }
         default:
             return b;
     }
     LootSlotType slotType = lv.permission == OWNER_PERMISSION ? LOOT_SLOT_TYPE_OWNER : LOOT_SLOT_TYPE_ALLOW_LOOT;
     // Xinef: items that do not follow loot rules need this
     LootSlotType partySlotType = lv.permission == MASTER_PERMISSION ? LOOT_SLOT_TYPE_MASTER : slotType;
     QuestItemMap const& lootPlayerQuestItems = l.GetPlayerQuestItems();
     QuestItemMap::const_iterator q_itr = lootPlayerQuestItems.find(lv.viewer->GetGUID());
     if (q_itr != lootPlayerQuestItems.end())
     {
         QuestItemList* q_list = q_itr->second;
         for (QuestItemList::const_iterator qi = q_list->begin(); qi != q_list->end(); ++qi)
         {
             LootItem& item = l.quest_items[qi->index];
             if (!qi->is_looted && !item.is_looted)
             {
                 bool showInLoot = true;
                 bool hasQuestForItem = lv.viewer->HasQuestForItem(item.itemid, 0, false, &showInLoot);
                 if (!hasQuestForItem)
                 {
                     if (!showInLoot)
                     {
                         const_cast<QuestItem*>(&(*qi))->is_looted = true;
                         if (!item.freeforall)
{
                             item.is_looted = true;
                         }
                         continue;
                     }
                     b << uint8(l.items.size() + (qi - q_list->begin()));
                     b << item;
                     b << uint8(lv.permission == MASTER_PERMISSION ? LOOT_SLOT_TYPE_MASTER : LOOT_SLOT_TYPE_LOCKED);
                 }
                 else
                 {
                     b << uint8(l.items.size() + (qi - q_list->begin()));
                     b << item;
                     if (item.follow_loot_rules)
                     {
                         switch (lv.permission)
{
                             case MASTER_PERMISSION:
                                 b << uint8(LOOT_SLOT_TYPE_MASTER);
                                 break;
                             case RESTRICTED_PERMISSION:
                                 b << (item.is_blocked ? uint8(LOOT_SLOT_TYPE_LOCKED) : uint8(slotType));
                                 break;
                             case GROUP_PERMISSION:
                             case ROUND_ROBIN_PERMISSION:
                                 if (!item.is_blocked)
                                     b << uint8(LOOT_SLOT_TYPE_ALLOW_LOOT);
                                 else
                                     b << uint8(LOOT_SLOT_TYPE_ROLL_ONGOING);
                                 break;
                             default:
                                 b << uint8(slotType);
                                 break;
                         }
                     }
                     else if (!item.freeforall)
                         b << uint8(partySlotType);
                     else
                         b << uint8(slotType);
                 }
                 ++itemsShown;
             }
         }
     }
     QuestItemMap const& lootPlayerFFAItems = l.GetPlayerFFAItems();
     QuestItemMap::const_iterator ffa_itr = lootPlayerFFAItems.find(lv.viewer->GetGUID());
     if (ffa_itr != lootPlayerFFAItems.end())
     {
         QuestItemList* ffa_list = ffa_itr->second;
         for (QuestItemList::const_iterator fi = ffa_list->begin(); fi != ffa_list->end(); ++fi)
         {
             LootItem& item = l.items[fi->index];
             if (!fi->is_looted && !item.is_looted)
             {
                 b << uint8(fi->index);
                 b << item;
                 // Xinef: Here are FFA items, so dont use owner permision
                 b << uint8(LOOT_SLOT_TYPE_ALLOW_LOOT /*slotType*/);
                 ++itemsShown;
             }
         }
     }
     QuestItemMap const& lootPlayerNonQuestNonFFAConditionalItems = l.GetPlayerNonQuestNonFFAConditionalItems();
     QuestItemMap::const_iterator nn_itr = lootPlayerNonQuestNonFFAConditionalItems.find(lv.viewer->GetGUID());
     if (nn_itr != lootPlayerNonQuestNonFFAConditionalItems.end())
     {
         QuestItemList* conditional_list = nn_itr->second;
         for (QuestItemList::const_iterator ci = conditional_list->begin(); ci != conditional_list->end(); ++ci)
         {
             LootItem& item = l.items[ci->index];
             if (!ci->is_looted && !item.is_looted)
             {
                 b << uint8(ci->index);
                 b << item;
                 if (item.follow_loot_rules)
                 {
                     switch (lv.permission)
                     {
                         case MASTER_PERMISSION:
                             b << uint8(LOOT_SLOT_TYPE_MASTER);
                             break;
                         case RESTRICTED_PERMISSION:
                             b << (item.is_blocked ? uint8(LOOT_SLOT_TYPE_LOCKED) : uint8(slotType));
                             break;
                         case GROUP_PERMISSION:
                         case ROUND_ROBIN_PERMISSION:
                             if (!item.is_blocked)
                                 b << uint8(LOOT_SLOT_TYPE_ALLOW_LOOT);
                             else
                                 b << uint8(LOOT_SLOT_TYPE_ROLL_ONGOING);
                             break;
                         default:
                             b << uint8(slotType);
                             break;
                     }
                 }
                 else if (!item.freeforall)
                     b << uint8(partySlotType);
                 else
                     b << uint8(slotType);
                 ++itemsShown;
             }
         }
     }
     //update number of items shown
     b.put<uint8>(count_pos, itemsShown);
     return b;
 }
Member Data Documentation
containerGUID
ObjectGuid Loot::containerGUID
Definition at line 329 of file LootMgr.h.
Referenced by LootItemStorage::AddNewStoredLoot(), WorldSession::HandleLootMoneyOpcode(), LootItemStorage::LoadStoredLoot(), Player::SendLoot(), and Player::StoreLootItem().
gold
uint32 Loot::gold
Definition at line 322 of file LootMgr.h.
Referenced by LootItemStorage::AddNewStoredLoot(), clear(), empty(), generateMoneyLoot(), WorldSession::HandleLootMoneyOpcode(), hasItemForAll(), isLooted(), LootItemStorage::LoadStoredLoot(), Player::RemovedInsignia(), and Player::SendLoot().
i_LootValidatorRefMgr
LootValidatorRefMgr Loot::i_LootValidatorRefMgr private
Definition at line 400 of file LootMgr.h.
Referenced by addLootValidatorRef(), and clear().
items
std::vector<LootItem> Loot::items
Definition at line 320 of file LootMgr.h.
Referenced by AddItem(), LootItemStorage::AddNewStoredLoot(), clear(), Group::CountRollVote(), Group::CountTheRoll(), empty(), FillFFALoot(), FillLoot(), FillNonQuestNonFFAConditionalLoot(), FillNotNormalLootFor(), FillQuestLoot(), GetMaxSlotInLootFor(), Group::GroupLoot(), WorldSession::HandleLootMasterGiveOpcode(), hasItemFor(), hasItemForAll(), hasOverThresholdItem(), LootItemStorage::LoadStoredLoot(), LootItemInSlot(), Group::MasterLoot(), Group::NeedBeforeGreed(), NotifyQuestItemRemoved(), and LootGroupInvalidSelector::operator()().
loot_type
LootType Loot::loot_type {LOOT_NONE}
Definition at line 326 of file LootMgr.h.
Referenced by clear(), WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMoneyOpcode(), Player::SendLoot(), and Player::UpdateLootAchievements().
lootOwnerGUID
ObjectGuid Loot::lootOwnerGUID
Definition at line 325 of file LootMgr.h.
Referenced by AddItem(), and FillLoot().
PlayerFFAItems
QuestItemMap Loot::PlayerFFAItems private
Definition at line 396 of file LootMgr.h.
Referenced by clear(), FillFFALoot(), FillNotNormalLootFor(), GetPlayerFFAItems(), and LootItemInSlot().
PlayerNonQuestNonFFAConditionalItems
QuestItemMap Loot::PlayerNonQuestNonFFAConditionalItems private
Definition at line 397 of file LootMgr.h.
Referenced by clear(), FillNonQuestNonFFAConditionalLoot(), FillNotNormalLootFor(), GetPlayerNonQuestNonFFAConditionalItems(), and LootItemInSlot().
PlayerQuestItems
QuestItemMap Loot::PlayerQuestItems private
Definition at line 395 of file LootMgr.h.
Referenced by clear(), FillNotNormalLootFor(), FillQuestLoot(), GetMaxSlotInLootFor(), GetPlayerQuestItems(), LootItemInSlot(), and NotifyQuestItemRemoved().
PlayersLooting
PlayersLootingSet Loot::PlayersLooting private
Definition at line 394 of file LootMgr.h.
Referenced by AddLooter(), clear(), NotifyItemRemoved(), NotifyMoneyRemoved(), NotifyQuestItemRemoved(), and RemoveLooter().
quest_items
std::vector<LootItem> Loot::quest_items
Definition at line 321 of file LootMgr.h.
Referenced by AddItem(), clear(), Group::CountTheRoll(), FillLoot(), FillNotNormalLootFor(), FillQuestLoot(), Group::GroupLoot(), WorldSession::HandleLootMasterGiveOpcode(), hasItemFor(), LootItemStorage::LoadStoredLoot(), LootItemInSlot(), Group::MasterLoot(), and Group::NeedBeforeGreed().
roundRobinPlayer
ObjectGuid Loot::roundRobinPlayer
Definition at line 324 of file LootMgr.h.
Referenced by clear(), WorldSession::DoLootRelease(), FillLoot(), Player::isAllowedToLoot(), and Player::StoreLootItem().
sourceGameObject
GameObject* Loot::sourceGameObject {nullptr}
Definition at line 330 of file LootMgr.h.
Referenced by GameObject::GameObject().
unlootedCount
uint8 Loot::unlootedCount {0}
Definition at line 323 of file LootMgr.h.
Referenced by AddItem(), clear(), Group::CountTheRoll(), FillFFALoot(), FillNonQuestNonFFAConditionalLoot(), FillQuestLoot(), WorldSession::HandleLootMasterGiveOpcode(), isLooted(), LootItemStorage::LoadStoredLoot(), LootItemStorage::RemoveStoredLootItem(), LootItemStorage::RemoveStoredLootMoney(), Player::SendLoot(), and Player::StoreLootItem().
The documentation for this struct was generated from the following files:
src/server/game/Loot/LootMgr.h
src/server/game/Loot/LootMgr.cpp