Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/mutex.h File Reference
mutex.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/mutex_prof.h"
#include "jemalloc/internal/tsd.h"
#include "jemalloc/internal/witness.h"
Classes
struct malloc_mutex_s
Macros
#define MALLOC_MUTEX_MAX_SPIN 250
#define MALLOC_MUTEX_LOCK(m) pthread_mutex_lock(&(m)->lock)
#define MALLOC_MUTEX_UNLOCK(m) pthread_mutex_unlock(&(m)->lock)
#define MALLOC_MUTEX_TRYLOCK(m) (pthread_mutex_trylock(&(m)->lock) != 0)
#define LOCK_PROF_DATA_INITIALIZER
#define MALLOC_MUTEX_TYPE PTHREAD_MUTEX_DEFAULT
#define MALLOC_MUTEX_INITIALIZER
#define isthreaded true
Typedefs
typedef struct malloc_mutex_s malloc_mutex_t
Enumerations
enum malloc_mutex_lock_order_t { malloc_mutex_rank_exclusive , malloc_mutex_address_ordered }
Functions
bool malloc_mutex_init (malloc_mutex_t *mutex, const char *name, witness_rank_t rank, malloc_mutex_lock_order_t lock_order)
void malloc_mutex_prefork (tsdn_t *tsdn, malloc_mutex_t *mutex)
void malloc_mutex_postfork_parent (tsdn_t *tsdn, malloc_mutex_t *mutex)
void malloc_mutex_postfork_child (tsdn_t *tsdn, malloc_mutex_t *mutex)
bool malloc_mutex_boot (void)
void malloc_mutex_prof_data_reset (tsdn_t *tsdn, malloc_mutex_t *mutex)
void malloc_mutex_lock_slow (malloc_mutex_t *mutex)
static void malloc_mutex_lock_final (malloc_mutex_t *mutex)
static bool malloc_mutex_trylock_final (malloc_mutex_t *mutex)
static void mutex_owner_stats_update (tsdn_t *tsdn, malloc_mutex_t *mutex)
static bool malloc_mutex_trylock (tsdn_t *tsdn, malloc_mutex_t *mutex)
static void malloc_mutex_prof_merge (mutex_prof_data_t *sum, mutex_prof_data_t *data)
static void malloc_mutex_lock (tsdn_t *tsdn, malloc_mutex_t *mutex)
static void malloc_mutex_unlock (tsdn_t *tsdn, malloc_mutex_t *mutex)
static void malloc_mutex_assert_owner (tsdn_t *tsdn, malloc_mutex_t *mutex)
static void malloc_mutex_assert_not_owner (tsdn_t *tsdn, malloc_mutex_t *mutex)
static void malloc_mutex_prof_read (tsdn_t *tsdn, mutex_prof_data_t *data, malloc_mutex_t *mutex)
static void malloc_mutex_prof_accum (tsdn_t *tsdn, mutex_prof_data_t *data, malloc_mutex_t *mutex)
Macro Definition Documentation
isthreaded
#define isthreaded true
Definition at line 140 of file mutex.h.
LOCK_PROF_DATA_INITIALIZER
#define LOCK_PROF_DATA_INITIALIZER
Value:
    {NSTIME_ZERO_INITIALIZER, NSTIME_ZERO_INITIALIZER, 0, 0, 0,     \
        ATOMIC_INIT(0), 0, NULL, 0}
Definition at line 96 of file mutex.h.
MALLOC_MUTEX_INITIALIZER
#define MALLOC_MUTEX_INITIALIZER
Value:
     {{{LOCK_PROF_DATA_INITIALIZER, PTHREAD_MUTEX_INITIALIZER, ATOMIC_INIT(false)}},    \
      WITNESS_INITIALIZER("mutex", WITNESS_RANK_OMIT)}
Definition at line 130 of file mutex.h.
MALLOC_MUTEX_LOCK
#define MALLOC_MUTEX_LOCK (m) pthread_mutex_lock(&(m)->lock)
Definition at line 91 of file mutex.h.
MALLOC_MUTEX_MAX_SPIN
#define MALLOC_MUTEX_MAX_SPIN 250
Definition at line 74 of file mutex.h.
MALLOC_MUTEX_TRYLOCK
#define MALLOC_MUTEX_TRYLOCK (m) (pthread_mutex_trylock(&(m)->lock) != 0)
Definition at line 93 of file mutex.h.
MALLOC_MUTEX_TYPE
#define MALLOC_MUTEX_TYPE PTHREAD_MUTEX_DEFAULT
Definition at line 124 of file mutex.h.
MALLOC_MUTEX_UNLOCK
#define MALLOC_MUTEX_UNLOCK (m) pthread_mutex_unlock(&(m)->lock)
Definition at line 92 of file mutex.h.
Typedef Documentation
malloc_mutex_t
typedef struct malloc_mutex_s malloc_mutex_t
Definition at line 1 of file mutex.h.
Enumeration Type Documentation
malloc_mutex_lock_order_t
enum malloc_mutex_lock_order_t
Enumerator
malloc_mutex_rank_exclusive
malloc_mutex_address_ordered
Definition at line 9 of file mutex.h.
              {
     /* Can only acquire one mutex of a given witness rank at a time. */
     malloc_mutex_rank_exclusive,
     /*
      * Can acquire multiple mutexes of the same witness rank, but in
      * address-ascending order only.
      */
     malloc_mutex_address_ordered
 } malloc_mutex_lock_order_t;
Function Documentation
malloc_mutex_assert_not_owner()
static void malloc_mutex_assert_not_owner (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 244 of file mutex.h.
{
     witness_assert_not_owner(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
 }
References malloc_mutex_s::witness, and witness_assert_not_owner().
Referenced by arena_decay_tick(), extent_alloc_retained(), mutex_pool_assert_not_held(), and prof_tctx_destroy().
malloc_mutex_assert_owner()
static void malloc_mutex_assert_owner (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 239 of file mutex.h.
{
     witness_assert_owner(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
 }
References malloc_mutex_s::witness, and witness_assert_owner().
Referenced by arena_decay_to_limit(), arena_maybe_decay(), arena_stats_add_u64(), arena_stats_add_zu(), arena_stats_read_u64(), arena_stats_read_zu(), arena_stats_sub_u64(), arena_stats_sub_zu(), background_thread_enabled_set(), background_thread_wakeup_time_set(), base_auto_thp_switch(), base_extent_alloc(), extent_grow_retained(), extents_fit_locked(), extents_insert_locked(), extents_remove_locked(), large_dalloc_prep_impl(), malloc_init_hard_cleanup(), malloc_mutex_prof_accum(), malloc_mutex_prof_data_reset(), malloc_mutex_prof_read(), mutex_pool_assert_owner(), prof_dump_gctx(), prof_log_bt_index(), prof_log_thr_index(), prof_tctx_destroy(), prof_tctx_dump_iter(), prof_tctx_finish_iter(), prof_tctx_merge_gctx(), prof_tctx_merge_iter(), prof_tctx_merge_tdata(), prof_tctx_should_destroy(), prof_tdata_destroy_locked(), prof_tdata_should_destroy(), prof_try_log(), and tcaches_elm_remove().
malloc_mutex_boot()
bool malloc_mutex_boot (void)
Definition at line 211 of file mutex.c.
{
 #ifdef JEMALLOC_MUTEX_INIT_CB
     postpone_init = false;
     while (postponed_mutexes != NULL) {
         if (_pthread_mutex_init_calloc_cb(&postponed_mutexes->lock,
             bootstrap_calloc) != 0) {
             return true;
         }
         postponed_mutexes = postponed_mutexes->postponed_next;
     }
 #endif
     return false;
 }
References bootstrap_calloc, malloc_mutex_s::lock, and NULL.
malloc_mutex_init()
bool malloc_mutex_init (malloc_mutex_t * mutex, const char * name, witness_rank_t rank, malloc_mutex_lock_order_t lock_order)
Definition at line 135 of file mutex.c.
{
     mutex_prof_data_init(&mutex->prof_data);
 #ifdef _WIN32
 #  if _WIN32_WINNT >= 0x0600
     InitializeSRWLock(&mutex->lock);
 #  else
     if (!InitializeCriticalSectionAndSpinCount(&mutex->lock,
         _CRT_SPINCOUNT)) {
         return true;
     }
 #  endif
 #elif (defined(JEMALLOC_OS_UNFAIR_LOCK))
        mutex->lock = OS_UNFAIR_LOCK_INIT;
 #elif (defined(JEMALLOC_MUTEX_INIT_CB))
     if (postpone_init) {
         mutex->postponed_next = postponed_mutexes;
         postponed_mutexes = mutex;
     } else {
         if (_pthread_mutex_init_calloc_cb(&mutex->lock,
             bootstrap_calloc) != 0) {
             return true;
         }
     }
 #else
     pthread_mutexattr_t attr;
     if (pthread_mutexattr_init(&attr) != 0) {
         return true;
     }
     pthread_mutexattr_settype(&attr, MALLOC_MUTEX_TYPE);
     if (pthread_mutex_init(&mutex->lock, &attr) != 0) {
         pthread_mutexattr_destroy(&attr);
         return true;
     }
     pthread_mutexattr_destroy(&attr);
 #endif
     if (config_debug) {
         mutex->lock_order = lock_order;
         if (lock_order == malloc_mutex_address_ordered) {
             witness_init(&mutex->witness, name, rank,
                 mutex_addr_comp, mutex);
         } else {
             witness_init(&mutex->witness, name, rank, NULL, NULL);
         }
     }
     return false;
 }
References _CRT_SPINCOUNT, bootstrap_calloc, config_debug, malloc_mutex_s::lock, malloc_mutex_s::lock_order, malloc_mutex_address_ordered, MALLOC_MUTEX_TYPE, mutex_addr_comp(), mutex_prof_data_init(), NULL, malloc_mutex_s::prof_data, malloc_mutex_s::witness, and witness_init.
Referenced by malloc_mutex_postfork_child().
malloc_mutex_lock()
static void malloc_mutex_lock (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 217 of file mutex.h.
{
     witness_assert_not_owner(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
     if (isthreaded) {
         if (malloc_mutex_trylock_final(mutex)) {
             malloc_mutex_lock_slow(mutex);
             atomic_store_b(&mutex->locked, true, ATOMIC_RELAXED);
         }
         mutex_owner_stats_update(tsdn, mutex);
     }
     witness_lock(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
 }
References ATOMIC_RELAXED, isthreaded, malloc_mutex_s::locked, malloc_mutex_lock_slow(), malloc_mutex_trylock_final(), mutex_owner_stats_update(), malloc_mutex_s::witness, witness_assert_not_owner(), and witness_lock().
Referenced by arena_bin_choose_lock(), arena_bin_nonfull_slab_get(), arena_bin_reset(), arena_choose_hard(), arena_dalloc_bin(), arena_dalloc_bin_slab(), arena_decay_impl(), arena_decay_ms_set(), arena_decay_to_limit(), arena_i_decay(), arena_i_dss_ctl(), arena_i_extent_hooks_ctl(), arena_i_index(), arena_i_initialized_ctl(), arena_i_retain_grow_limit_ctl(), arena_init(), arena_reset(), arena_reset_finish_background_thread(), arena_reset_prepare_background_thread(), arena_retain_grow_limit_get_set(), arena_stats_lock(), arena_stats_merge(), arenas_create_ctl(), arenas_lookup_ctl(), arenas_narenas_ctl(), background_thread_boot1(), background_thread_ctl(), base_alloc_impl(), base_block_alloc(), base_extent_alloc(), base_stats_get(), bin_stats_merge(), chunk_alloc(), chunk_alloc_dss(), chunk_dealloc(), chunk_dss_prec_get(), chunk_dss_prec_set(), chunk_in_dss(), chunk_record(), chunk_recycle(), ctl_init(), epoch_ctl(), experimental_arenas_i_index(), experimental_arenas_i_pactivep_ctl(), extent_alloc(), extent_alloc_retained(), extent_coalesce(), extent_dalloc(), extent_deactivate(), extent_hooks_set(), extent_record(), extent_recycle_extract(), extent_util_stats_verbose_get(), extents_evict(), hook_install(), hook_remove(), huge_dalloc(), huge_palloc(), huge_prof_ctx_get(), huge_prof_ctx_set(), huge_salloc(), if(), large_dalloc_prep_impl(), large_palloc(), malloc_init_hard(), malloc_init_hard_a0(), malloc_init_hard_needed(), malloc_mutex_prefork(), max_background_threads_ctl(), mutex_pool_lock(), mutex_pool_lock2(), narenas_total_get(), prof_accum_add(), prof_accum_cancel(), prof_active_get(), prof_active_set(), prof_dump(), prof_dump_gctx_prep(), prof_dump_header_impl(), prof_dump_prep(), prof_enter(), prof_fdump(), prof_free_sampled_object(), prof_gctx_dump_iter(), prof_gctx_finish(), prof_gctx_merge_iter(), prof_gctx_try_destroy(), prof_gdump(), prof_gdump_get(), prof_gdump_set(), prof_idump(), prof_log_start(), prof_log_stop(), prof_lookup(), prof_lookup_global(), prof_malloc_sample_object(), prof_mdump(), prof_reset(), prof_tctx_destroy(), prof_tctx_merge_tdata(), prof_tdata_destroy(), prof_tdata_detach(), prof_tdata_expire(), prof_tdata_init_impl(), prof_tdata_merge_iter(), prof_thr_uid_alloc(), prof_thread_active_init_get(), prof_thread_active_init_set(), prof_try_log(), rtree_leaf_init(), rtree_node_init(), stats_arenas_i_index(), stats_print_atexit(), tcache_arena_associate(), tcache_arena_dissociate(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcaches_create(), tcaches_create_prep(), tcaches_destroy(), tcaches_flush(), tsd_add_nominal(), tsd_force_recompute(), tsd_init_check_recursion(), tsd_init_finish(), and tsd_remove_nominal().
malloc_mutex_lock_final()
static void malloc_mutex_lock_final (malloc_mutex_t * mutex) inline static
Definition at line 154 of file mutex.h.
{
     MALLOC_MUTEX_LOCK(mutex);
     atomic_store_b(&mutex->locked, true, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, malloc_mutex_s::locked, and MALLOC_MUTEX_LOCK.
Referenced by malloc_mutex_lock_slow().
malloc_mutex_lock_slow()
void malloc_mutex_lock_slow (malloc_mutex_t * mutex)
Definition at line 47 of file mutex.c.
{
     mutex_prof_data_t *data = &mutex->prof_data;
     nstime_t before = NSTIME_ZERO_INITIALIZER;
     if (ncpus == 1) {
         goto label_spin_done;
     }
     int cnt = 0, max_cnt = MALLOC_MUTEX_MAX_SPIN;
     do {
         spin_cpu_spinwait();
         if (!atomic_load_b(&mutex->locked, ATOMIC_RELAXED)
                     && !malloc_mutex_trylock_final(mutex)) {
             data->n_spin_acquired++;
             return;
         }
     } while (cnt++ < max_cnt);
     if (!config_stats) {
         /* Only spin is useful when stats is off. */
         malloc_mutex_lock_final(mutex);
         return;
     }
 label_spin_done:
     nstime_update(&before);
     /* Copy before to after to avoid clock skews. */
     nstime_t after;
     nstime_copy(&after, &before);
     uint32_t n_thds = atomic_fetch_add_u32(&data->n_waiting_thds, 1,
         ATOMIC_RELAXED) + 1;
     /* One last try as above two calls may take quite some cycles. */
     if (!malloc_mutex_trylock_final(mutex)) {
         atomic_fetch_sub_u32(&data->n_waiting_thds, 1, ATOMIC_RELAXED);
         data->n_spin_acquired++;
         return;
     }
     /* True slow path. */
     malloc_mutex_lock_final(mutex);
     /* Update more slow-path only counters. */
     atomic_fetch_sub_u32(&data->n_waiting_thds, 1, ATOMIC_RELAXED);
     nstime_update(&after);
     nstime_t delta;
     nstime_copy(&delta, &after);
     nstime_subtract(&delta, &before);
     data->n_wait_times++;
     nstime_add(&data->tot_wait_time, &delta);
     if (nstime_compare(&data->max_wait_time, &delta) < 0) {
         nstime_copy(&data->max_wait_time, &delta);
     }
     if (n_thds > data->max_n_thds) {
         data->max_n_thds = n_thds;
     }
 }
References ATOMIC_RELAXED, config_stats, malloc_mutex_s::locked, malloc_mutex_lock_final(), MALLOC_MUTEX_MAX_SPIN, malloc_mutex_trylock_final(), ncpus, nstime_add, nstime_compare, nstime_copy, nstime_subtract, nstime_update, NSTIME_ZERO_INITIALIZER, malloc_mutex_s::prof_data, and spin_cpu_spinwait().
Referenced by malloc_mutex_lock().
malloc_mutex_postfork_child()
void malloc_mutex_postfork_child (tsdn_t * tsdn, malloc_mutex_t * mutex)
Definition at line 195 of file mutex.c.
{
 #ifdef JEMALLOC_MUTEX_INIT_CB
     malloc_mutex_unlock(tsdn, mutex);
 #else
     if (malloc_mutex_init(mutex, mutex->witness.name,
         mutex->witness.rank, mutex->lock_order)) {
         malloc_printf("<jemalloc>: Error re-initializing mutex in "
             "child\n");
         if (opt_abort) {
             abort();
         }
     }
 #endif
 }
References malloc_mutex_s::lock_order, malloc_mutex_init(), malloc_mutex_unlock(), malloc_printf, witness_s::name, opt_abort, witness_s::rank, and malloc_mutex_s::witness.
malloc_mutex_postfork_parent()
void malloc_mutex_postfork_parent (tsdn_t * tsdn, malloc_mutex_t * mutex)
Definition at line 190 of file mutex.c.
{
     malloc_mutex_unlock(tsdn, mutex);
 }
References malloc_mutex_unlock().
malloc_mutex_prefork()
void malloc_mutex_prefork (tsdn_t * tsdn, malloc_mutex_t * mutex)
Definition at line 185 of file mutex.c.
{
     malloc_mutex_lock(tsdn, mutex);
 }
References malloc_mutex_lock().
malloc_mutex_prof_accum()
static void malloc_mutex_prof_accum (tsdn_t * tsdn, mutex_prof_data_t * data, malloc_mutex_t * mutex) inline static
Definition at line 267 of file mutex.h.
{
     mutex_prof_data_t *source = &mutex->prof_data;
     /* Can only read holding the mutex. */
     malloc_mutex_assert_owner(tsdn, mutex);
     nstime_add(&data->tot_wait_time, &source->tot_wait_time);
     if (nstime_compare(&source->max_wait_time, &data->max_wait_time) > 0) {
         nstime_copy(&data->max_wait_time, &source->max_wait_time);
     }
     data->n_wait_times += source->n_wait_times;
     data->n_spin_acquired += source->n_spin_acquired;
     if (data->max_n_thds < source->max_n_thds) {
         data->max_n_thds = source->max_n_thds;
     }
     /* n_wait_thds is not reported. */
     atomic_store_u32(&data->n_waiting_thds, 0, ATOMIC_RELAXED);
     data->n_owner_switches += source->n_owner_switches;
     data->n_lock_ops += source->n_lock_ops;
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), mutex_prof_data_t::max_n_thds, mutex_prof_data_t::max_wait_time, mutex_prof_data_t::n_lock_ops, mutex_prof_data_t::n_owner_switches, mutex_prof_data_t::n_spin_acquired, mutex_prof_data_t::n_wait_times, nstime_add, nstime_compare, nstime_copy, malloc_mutex_s::prof_data, and mutex_prof_data_t::tot_wait_time.
Referenced by bin_stats_merge().
malloc_mutex_prof_data_reset()
void malloc_mutex_prof_data_reset (tsdn_t * tsdn, malloc_mutex_t * mutex)
Definition at line 113 of file mutex.c.
{
     malloc_mutex_assert_owner(tsdn, mutex);
     mutex_prof_data_init(&mutex->prof_data);
 }
References malloc_mutex_assert_owner(), mutex_prof_data_init(), and malloc_mutex_s::prof_data.
malloc_mutex_prof_merge()
static void malloc_mutex_prof_merge (mutex_prof_data_t * sum, mutex_prof_data_t * data) inline static
Definition at line 194 of file mutex.h.
{
     nstime_add(&sum->tot_wait_time, &data->tot_wait_time);
     if (nstime_compare(&sum->max_wait_time, &data->max_wait_time) < 0) {
         nstime_copy(&sum->max_wait_time, &data->max_wait_time);
     }
     sum->n_wait_times += data->n_wait_times;
     sum->n_spin_acquired += data->n_spin_acquired;
     if (sum->max_n_thds < data->max_n_thds) {
         sum->max_n_thds = data->max_n_thds;
     }
     uint32_t cur_n_waiting_thds = atomic_load_u32(&sum->n_waiting_thds,
         ATOMIC_RELAXED);
     uint32_t new_n_waiting_thds = cur_n_waiting_thds + atomic_load_u32(
         &data->n_waiting_thds, ATOMIC_RELAXED);
     atomic_store_u32(&sum->n_waiting_thds, new_n_waiting_thds,
         ATOMIC_RELAXED);
     sum->n_owner_switches += data->n_owner_switches;
     sum->n_lock_ops += data->n_lock_ops;
 }
References ATOMIC_RELAXED, mutex_prof_data_t::max_n_thds, mutex_prof_data_t::max_wait_time, mutex_prof_data_t::n_lock_ops, mutex_prof_data_t::n_owner_switches, mutex_prof_data_t::n_spin_acquired, mutex_prof_data_t::n_wait_times, mutex_prof_data_t::n_waiting_thds, nstime_add, nstime_compare, nstime_copy, and mutex_prof_data_t::tot_wait_time.
Referenced by ctl_arena_stats_sdmerge().
malloc_mutex_prof_read()
static void malloc_mutex_prof_read (tsdn_t * tsdn, mutex_prof_data_t * data, malloc_mutex_t * mutex) inline static
Definition at line 250 of file mutex.h.
{
     mutex_prof_data_t *source = &mutex->prof_data;
     /* Can only read holding the mutex. */
     malloc_mutex_assert_owner(tsdn, mutex);
     /*
      * Not *really* allowed (we shouldn't be doing non-atomic loads of
      * atomic data), but the mutex protection makes this safe, and writing
      * a member-for-member copy is tedious for this situation.
      */
     *data = *source;
     /* n_wait_thds is not reported (modified w/o locking). */
     atomic_store_u32(&data->n_waiting_thds, 0, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), and malloc_mutex_s::prof_data.
Referenced by arena_stats_merge(), and ctl_refresh().
malloc_mutex_trylock()
static bool malloc_mutex_trylock (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 178 of file mutex.h.
{
     witness_assert_not_owner(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
     if (isthreaded) {
         if (malloc_mutex_trylock_final(mutex)) {
             atomic_store_b(&mutex->locked, true, ATOMIC_RELAXED);
             return true;
         }
         mutex_owner_stats_update(tsdn, mutex);
     }
     witness_lock(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
     return false;
 }
References ATOMIC_RELAXED, isthreaded, malloc_mutex_s::locked, malloc_mutex_trylock_final(), mutex_owner_stats_update(), malloc_mutex_s::witness, witness_assert_not_owner(), and witness_lock().
Referenced by arena_decay_impl().
malloc_mutex_trylock_final()
static bool malloc_mutex_trylock_final (malloc_mutex_t * mutex) inline static
Definition at line 160 of file mutex.h.
{
     return MALLOC_MUTEX_TRYLOCK(mutex);
 }
References MALLOC_MUTEX_TRYLOCK.
Referenced by malloc_mutex_lock(), malloc_mutex_lock_slow(), and malloc_mutex_trylock().
malloc_mutex_unlock()
static void malloc_mutex_unlock (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 230 of file mutex.h.
{
     atomic_store_b(&mutex->locked, false, ATOMIC_RELAXED);
     witness_unlock(tsdn_witness_tsdp_get(tsdn), &mutex->witness);
     if (isthreaded) {
         MALLOC_MUTEX_UNLOCK(mutex);
     }
 }
References ATOMIC_RELAXED, isthreaded, malloc_mutex_s::locked, MALLOC_MUTEX_UNLOCK, malloc_mutex_s::witness, and witness_unlock().
Referenced by arena_bin_nonfull_slab_get(), arena_bin_reset(), arena_choose_hard(), arena_dalloc_bin(), arena_dalloc_bin_slab(), arena_decay_impl(), arena_decay_ms_set(), arena_decay_to_limit(), arena_i_decay(), arena_i_dss_ctl(), arena_i_extent_hooks_ctl(), arena_i_index(), arena_i_initialized_ctl(), arena_i_retain_grow_limit_ctl(), arena_init(), arena_malloc_small(), arena_reset(), arena_reset_finish_background_thread(), arena_reset_prepare_background_thread(), arena_retain_grow_limit_get_set(), arena_stats_merge(), arena_stats_unlock(), arena_tcache_fill_small(), arenas_create_ctl(), arenas_lookup_ctl(), arenas_narenas_ctl(), background_thread_boot1(), background_thread_ctl(), base_alloc_impl(), base_block_alloc(), base_extent_alloc(), base_stats_get(), bin_stats_merge(), chunk_alloc(), chunk_alloc_dss(), chunk_dealloc(), chunk_dss_prec_get(), chunk_dss_prec_set(), chunk_in_dss(), chunk_record(), chunk_recycle(), ctl_init(), epoch_ctl(), experimental_arenas_i_index(), experimental_arenas_i_pactivep_ctl(), extent_alloc(), extent_alloc_retained(), extent_coalesce(), extent_dalloc(), extent_deactivate(), extent_grow_retained(), extent_hooks_set(), extent_record(), extent_recycle_extract(), extent_util_stats_verbose_get(), extents_evict(), hook_install(), hook_remove(), huge_dalloc(), huge_palloc(), huge_prof_ctx_get(), huge_prof_ctx_set(), huge_salloc(), if(), large_dalloc_prep_impl(), large_palloc(), malloc_init_hard(), malloc_init_hard_a0(), malloc_init_hard_cleanup(), malloc_init_hard_needed(), malloc_mutex_postfork_child(), malloc_mutex_postfork_parent(), max_background_threads_ctl(), mutex_pool_unlock(), mutex_pool_unlock2(), narenas_total_get(), prof_accum_add(), prof_accum_cancel(), prof_active_get(), prof_active_set(), prof_dump(), prof_dump_gctx_prep(), prof_dump_header_impl(), prof_dump_prep(), prof_fdump(), prof_free_sampled_object(), prof_gctx_dump_iter(), prof_gctx_finish(), prof_gctx_merge_iter(), prof_gctx_try_destroy(), prof_gdump(), prof_gdump_get(), prof_gdump_set(), prof_idump(), prof_leave(), prof_log_start(), prof_log_stop(), prof_lookup(), prof_lookup_global(), prof_malloc_sample_object(), prof_mdump(), prof_reset(), prof_tctx_destroy(), prof_tctx_merge_tdata(), prof_tdata_destroy(), prof_tdata_detach(), prof_tdata_expire(), prof_tdata_init_impl(), prof_tdata_merge_iter(), prof_thr_uid_alloc(), prof_thread_active_init_get(), prof_thread_active_init_set(), prof_try_log(), rtree_leaf_init(), rtree_node_init(), stats_arenas_i_index(), stats_print_atexit(), tcache_arena_associate(), tcache_arena_dissociate(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_stats_merge(), tcaches_create(), tcaches_create_prep(), tcaches_destroy(), tcaches_flush(), tsd_add_nominal(), tsd_force_recompute(), tsd_init_check_recursion(), tsd_init_finish(), and tsd_remove_nominal().
mutex_owner_stats_update()
static void mutex_owner_stats_update (tsdn_t * tsdn, malloc_mutex_t * mutex) inline static
Definition at line 165 of file mutex.h.
{
     if (config_stats) {
         mutex_prof_data_t *data = &mutex->prof_data;
         data->n_lock_ops++;
         if (data->prev_owner != tsdn) {
             data->prev_owner = tsdn;
             data->n_owner_switches++;
         }
     }
 }
References config_stats, and malloc_mutex_s::prof_data.
Referenced by malloc_mutex_lock(), and malloc_mutex_trylock().