Azerotcore-wotlk: go_scourge_enclosure Class Reference
go_scourge_enclosure Class Reference
Public Member Functions
go_scourge_enclosure ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 882 of file zone_zuldrak.cpp.
Constructor & Destructor Documentation
go_scourge_enclosure()
go_scourge_enclosure::go_scourge_enclosure () inline
Definition at line 885 of file zone_zuldrak.cpp.
 : GameObjectScript("go_scourge_enclosure") { }
Member Function Documentation
OnGossipHello()
bool go_scourge_enclosure::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 887 of file zone_zuldrak.cpp.
     {
         go->UseDoorOrButton();
         if (player->GetQuestStatus(QUEST_OUR_ONLY_HOPE) == QUEST_STATUS_INCOMPLETE)
         {
             Creature* gymerDummy = go->FindNearestCreature(NPC_GYMER_DUMMY, 20.0f);
             if (gymerDummy)
             {
                 player->KilledMonsterCredit(gymerDummy->GetEntry(), gymerDummy->GetGUID());
                 gymerDummy->CastSpell(gymerDummy, SPELL_GYMER_LOCK_EXPLOSION, true);
                 gymerDummy->DespawnOrUnsummon();
             }
         }
         return true;
     }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), WorldObject::FindNearestCreature(), Object::GetEntry(), Object::GetGUID(), Player::GetQuestStatus(), Player::KilledMonsterCredit(), NPC_GYMER_DUMMY, QUEST_OUR_ONLY_HOPE, QUEST_STATUS_INCOMPLETE, SPELL_GYMER_LOCK_EXPLOSION, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_zuldrak.cpp