Azerotcore-wotlk: TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > Class Template Reference
TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > Class Template Reference
#include <TypeContainer.h>
Public Member Functions
template<class SPECIFIC_TYPE >
bool Insert (KEY_TYPE const &handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
bool Remove (KEY_TYPE const &handle)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Find (KEY_TYPE const &handle)
template<class SPECIFIC_TYPE >
std::size_t Size () const
ContainerUnorderedMap< OBJECT_TYPES, KEY_TYPE > & GetElements ()
ContainerUnorderedMap< OBJECT_TYPES, KEY_TYPE > const & GetElements () const
Private Attributes
ContainerUnorderedMap< OBJECT_TYPES, KEY_TYPE > _elements
Detailed Description
template<class OBJECT_TYPES, class KEY_TYPE>
class TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >
Definition at line 131 of file TypeContainer.h.
Member Function Documentation
Find()
template<class OBJECT_TYPES , class KEY_TYPE > template<class SPECIFIC_TYPE > SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Find (KEY_TYPE const & handle) inline
Definition at line 147 of file TypeContainer.h.
     {
         return Acore::Find(_elements, handle, (SPECIFIC_TYPE*)nullptr);
     }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements, and Acore::Find().
Referenced by Map::GetCorpse(), Map::GetCreature(), Map::GetDynamicObject(), Map::GetGameObject(), and Map::GetPet().
GetElements() [1/2]
template<class OBJECT_TYPES , class KEY_TYPE > ContainerUnorderedMap<OBJECT_TYPES, KEY_TYPE>& TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::GetElements () inline
Definition at line 160 of file TypeContainer.h.
 { return _elements; }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements.
GetElements() [2/2]
template<class OBJECT_TYPES , class KEY_TYPE > ContainerUnorderedMap<OBJECT_TYPES, KEY_TYPE> const& TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::GetElements () const inline
Definition at line 161 of file TypeContainer.h.
 { return _elements; }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements.
Insert()
template<class OBJECT_TYPES , class KEY_TYPE > template<class SPECIFIC_TYPE > bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert (KEY_TYPE const & handle, SPECIFIC_TYPE * obj) inline
Definition at line 135 of file TypeContainer.h.
     {
         return Acore::Insert(_elements, handle, obj);
     }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements, and Acore::Insert().
Referenced by Corpse::AddToWorld(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), and Pet::AddToWorld().
Remove()
template<class OBJECT_TYPES , class KEY_TYPE > template<class SPECIFIC_TYPE > bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove (KEY_TYPE const & handle) inline
Definition at line 141 of file TypeContainer.h.
     {
         return Acore::Remove(_elements, handle, (SPECIFIC_TYPE*)nullptr);
     }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements, and Acore::Remove().
Referenced by Corpse::RemoveFromWorld(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), and Pet::RemoveFromWorld().
Size()
template<class OBJECT_TYPES , class KEY_TYPE > template<class SPECIFIC_TYPE > std::size_t TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Size () const inline
Definition at line 153 of file TypeContainer.h.
     {
         std::size_t size = 0;
         Acore::Size(_elements, &size, (SPECIFIC_TYPE*)nullptr);
         return size;
     }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements, and Acore::Size().
Member Data Documentation
_elements
template<class OBJECT_TYPES , class KEY_TYPE > ContainerUnorderedMap<OBJECT_TYPES, KEY_TYPE> TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::_elements private
Definition at line 164 of file TypeContainer.h.
Referenced by TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Find(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::GetElements(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), and TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Size().
The documentation for this class was generated from the following file:
src/common/Dynamic/TypeContainer.h