Azerotcore-wotlk: Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck Class Reference
Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestCreatureEntryWithLiveStateInObjectRangeCheck (WorldObject const &obj, uint32 entry, bool alive, float range)
bool operator() (Creature *u)
Private Member Functions
NearestCreatureEntryWithLiveStateInObjectRangeCheck (NearestCreatureEntryWithLiveStateInObjectRangeCheck const &)
Private Attributes
WorldObject const & i_obj
uint32 i_entry
bool i_alive
float i_range
Detailed Description
Definition at line 1208 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestCreatureEntryWithLiveStateInObjectRangeCheck() [1/2]
Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::NearestCreatureEntryWithLiveStateInObjectRangeCheck (WorldObject const & obj, uint32 entry, bool alive, float range) inline
Definition at line 1211 of file GridNotifiers.h.
             : i_obj(obj), i_entry(entry), i_alive(alive), i_range(range) {}
NearestCreatureEntryWithLiveStateInObjectRangeCheck() [2/2]
Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::NearestCreatureEntryWithLiveStateInObjectRangeCheck (NearestCreatureEntryWithLiveStateInObjectRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator() (Creature * u) inline
Definition at line 1214 of file GridNotifiers.h.
         {
             if (u->GetEntry() == i_entry && u->IsAlive() == i_alive && i_obj.IsWithinDistInMap(u, i_range))
             {
                 i_range = i_obj.GetDistance(u);         // use found unit range as new range limit for next check
                 return true;
             }
             return false;
         }
References WorldObject::GetDistance(), Object::GetEntry(), i_alive, i_entry, i_obj, i_range, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_alive
bool Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::i_alive private
Definition at line 1226 of file GridNotifiers.h.
Referenced by operator()().
i_entry
uint32 Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::i_entry private
Definition at line 1225 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const& Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::i_obj private
Definition at line 1224 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::i_range private
Definition at line 1227 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h