Azerotcore-wotlk: PetAura Class Reference
PetAura Class Reference
#include <SpellMgr.h>
Public Member Functions
PetAura ()
PetAura (uint32 petEntry, uint32 aura, bool _removeOnChangePet, int _damage)
uint32 GetAura (uint32 petEntry) const
void AddAura (uint32 petEntry, uint32 aura)
bool IsRemovedOnChangePet () const
int32 GetDamage () const
Private Types
typedef std::unordered_map< uint32, uint32 > PetAuraMap
Private Attributes
PetAuraMap auras
bool removeOnChangePet {false}
int32 damage {0}
Detailed Description
Definition at line 453 of file SpellMgr.h.
Member Typedef Documentation
PetAuraMap
typedef std::unordered_map<uint32, uint32> PetAura::PetAuraMap private
Definition at line 456 of file SpellMgr.h.
Constructor & Destructor Documentation
PetAura() [1/2]
PetAura::PetAura () inline
Definition at line 459 of file SpellMgr.h.
     {
         auras.clear();
     }
References auras.
PetAura() [2/2]
PetAura::PetAura (uint32 petEntry, uint32 aura, bool _removeOnChangePet, int _damage) inline
Definition at line 464 of file SpellMgr.h.
                                                                                 :
         removeOnChangePet(_removeOnChangePet), damage(_damage)
     {
         auras[petEntry] = aura;
     }
References auras.
Member Function Documentation
AddAura()
void PetAura::AddAura (uint32 petEntry, uint32 aura) inline
Definition at line 481 of file SpellMgr.h.
     {
         auras[petEntry] = aura;
     }
References auras.
GetAura()
uint32 PetAura::GetAura (uint32 petEntry) const inline
Definition at line 470 of file SpellMgr.h.
     {
         PetAuraMap::const_iterator itr = auras.find(petEntry);
         if (itr != auras.end())
             return itr->second;
         PetAuraMap::const_iterator itr2 = auras.find(0);
         if (itr2 != auras.end())
             return itr2->second;
         return 0;
     }
References auras.
Referenced by Unit::CastPetAura(), and Unit::RemovePetAura().
GetDamage()
int32 PetAura::GetDamage () const inline
Definition at line 491 of file SpellMgr.h.
     {
         return damage;
     }
References damage.
Referenced by Unit::CastPetAura().
IsRemovedOnChangePet()
bool PetAura::IsRemovedOnChangePet () const inline
Definition at line 486 of file SpellMgr.h.
     {
         return removeOnChangePet;
     }
References removeOnChangePet.
Referenced by Pet::CastPetAuras().
Member Data Documentation
auras
PetAuraMap PetAura::auras private
Definition at line 497 of file SpellMgr.h.
Referenced by AddAura(), GetAura(), and PetAura().
damage
int32 PetAura::damage {0} private
Definition at line 499 of file SpellMgr.h.
Referenced by GetDamage().
removeOnChangePet
bool PetAura::removeOnChangePet {false} private
Definition at line 498 of file SpellMgr.h.
Referenced by IsRemovedOnChangePet().
The documentation for this class was generated from the following file:
src/server/game/Spells/SpellMgr.h