Azerotcore-wotlk: boss_flame_leviathan::boss_flame_leviathanAI Struct Reference
boss_flame_leviathan::boss_flame_leviathanAI Struct Reference
Public Member Functions
boss_flame_leviathanAI (Creature *pCreature)
void BindPlayers ()
void RadioSay (const char *text, uint32 soundId)
void ActivateTowers ()
void TurnGates (bool _start, bool _death)
void TurnHealStations (bool _apply)
void ScheduleEvents ()
void SummonTowerHelpers (uint8 towerId)
void JustReachedHome () override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void InitializeAI () override
void Reset () override
uint32 GetData (uint32 param) const override
void UpdateAI (uint32 diff) override
void DoAction (int32 action) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
Vehicle * vehicle
EventMap events
SummonList summons
uint32 _startTimer
uint32 _speakTimer
uint8 _towersCount
bool _shutdown
uint32 _destroyedTurretCount
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 198 of file boss_flame_leviathan.cpp.
Constructor & Destructor Documentation
boss_flame_leviathanAI()
boss_flame_leviathan::boss_flame_leviathanAI::boss_flame_leviathanAI (Creature * pCreature) inline
Definition at line 200 of file boss_flame_leviathan.cpp.
                                                     : ScriptedAI(pCreature), vehicle(me->GetVehicleKit()), summons(me)
         {
             m_pInstance = pCreature->GetInstanceScript();
             assert(vehicle);
         }
References WorldObject::GetInstanceScript(), m_pInstance, and vehicle.
Member Function Documentation
ActivateTowers()
void boss_flame_leviathan::boss_flame_leviathanAI::ActivateTowers ()
Definition at line 507 of file boss_flame_leviathan.cpp.
 {
     _towersCount = 0;
     me->ResetLootMode();
     for (uint32 i = EVENT_TOWER_OF_LIFE_DESTROYED; i <= EVENT_TOWER_OF_FLAMES_DESTROYED; ++i)
     {
         if (m_pInstance->GetData(i))
         {
             ++_towersCount;
             me->AddLootMode(1 << _towersCount);
             switch (i)
             {
                 case EVENT_TOWER_OF_LIFE_DESTROYED:
                     me->AddAura(SPELL_TOWER_OF_LIFE, me);
                     events.RescheduleEvent(EVENT_FREYA, 30000);
                     break;
                 case EVENT_TOWER_OF_STORM_DESTROYED:
                     me->AddAura(SPELL_TOWER_OF_STORMS, me);
                     events.RescheduleEvent(EVENT_THORIMS_HAMMER, 60000);
                     break;
                 case EVENT_TOWER_OF_FROST_DESTROYED:
                     me->AddAura(SPELL_TOWER_OF_FROST, me);
                     events.RescheduleEvent(EVENT_HODIRS_FURY, 20000);
                     break;
                 case EVENT_TOWER_OF_FLAMES_DESTROYED:
                     me->AddAura(SPELL_TOWER_OF_FLAMES, me);
                     events.RescheduleEvent(EVENT_MIMIRONS_INFERNO, 42000);
                     break;
             }
         }
     }
 }
References EVENT_FREYA, EVENT_HODIRS_FURY, EVENT_MIMIRONS_INFERNO, EVENT_THORIMS_HAMMER, EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, SPELL_TOWER_OF_FLAMES, SPELL_TOWER_OF_FROST, SPELL_TOWER_OF_LIFE, and SPELL_TOWER_OF_STORMS.
Referenced by EnterCombat().
AttackStart()
void boss_flame_leviathan::boss_flame_leviathanAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 248 of file boss_flame_leviathan.cpp.
         {
             if (Unit* veh = who->GetVehicleBase())
                 ScriptedAI::AttackStart(veh);
             else
                 ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), and Unit::GetVehicleBase().
BindPlayers()
void boss_flame_leviathan::boss_flame_leviathanAI::BindPlayers ()
Definition at line 491 of file boss_flame_leviathan.cpp.
 {
     me->GetMap()->ToInstanceMap()->PermBindAllPlayers();
 }
References WorldObject::GetMap(), ScriptedAI::me, InstanceMap::PermBindAllPlayers(), and Map::ToInstanceMap().
Referenced by EnterCombat().
DoAction()
void boss_flame_leviathan::boss_flame_leviathanAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 475 of file boss_flame_leviathan.cpp.
         {
             if (action == ACTION_DESTROYED_TURRET)
             {
                 ++_destroyedTurretCount;
                 if (_destroyedTurretCount == RAID_MODE<uint32>(2, 4))
                 {
                     _destroyedTurretCount = 0;
                     me->CastSpell(me, SPELL_SYSTEMS_SHUTDOWN, true);
                 }
             }
         }
References _destroyedTurretCount, ACTION_DESTROYED_TURRET, Unit::CastSpell(), ScriptedAI::me, and SPELL_SYSTEMS_SHUTDOWN.
EnterCombat()
void boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 256 of file boss_flame_leviathan.cpp.
         {
             ScheduleEvents();
             Talk(FLAME_LEVIATHAN_SAY_AGGRO);
             me->setActive(true);
             me->SetHomePosition(322.4f, -14.3f, 409.8f, 3.23f);
             TurnGates(true, false);
             TurnHealStations(false);
             ActivateTowers();
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_LEVIATHAN, SPECIAL);
             BindPlayers();
             me->SetInCombatWithZone();
         }
References ActivateTowers(), BindPlayers(), FLAME_LEVIATHAN_SAY_AGGRO, m_pInstance, ScriptedAI::me, ScheduleEvents(), WorldObject::setActive(), ZoneScript::SetData(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), SPECIAL, CreatureAI::Talk(), TurnGates(), TurnHealStations(), and TYPE_LEVIATHAN.
GetData()
uint32 boss_flame_leviathan::boss_flame_leviathanAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 320 of file boss_flame_leviathan.cpp.
         {
             if (param == DATA_GET_TOWER_COUNT)
                 return _towersCount;
             if (param == DATA_GET_SHUTDOWN)
                 return !_shutdown;
             return 0;
         }
References _shutdown, _towersCount, DATA_GET_SHUTDOWN, and DATA_GET_TOWER_COUNT.
InitializeAI()
void boss_flame_leviathan::boss_flame_leviathanAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 273 of file boss_flame_leviathan.cpp.
         {
             if (m_pInstance && m_pInstance->GetData(TYPE_LEVIATHAN) == SPECIAL)
             {
                 me->SetHomePosition(322.4f, -14.3f, 409.8f, 3.23f);
                 me->UpdatePosition(322.4f, -14.3f, 409.8f, 3.23f);
                 me->StopMovingOnCurrentPos();
             }
             ScriptedAI::InitializeAI();
         }
References ZoneScript::GetData(), UnitAI::InitializeAI(), m_pInstance, ScriptedAI::me, Creature::SetHomePosition(), SPECIAL, Unit::StopMovingOnCurrentPos(), TYPE_LEVIATHAN, and Unit::UpdatePosition().
JustDied()
void boss_flame_leviathan::boss_flame_leviathanAI::JustDied (Unit *) override virtual
Reimplemented from ScriptedAI.
Definition at line 628 of file boss_flame_leviathan.cpp.
 {
     // Despawn Lashers, do before summons clear
     summons.DoAction(ACTION_DESPAWN_ADDS);
     summons.DespawnAll();
     if (m_pInstance)
     {
         m_pInstance->SetData(TYPE_LEVIATHAN, DONE);
         m_pInstance->SetData(DATA_VEHICLE_SPAWN, VEHICLE_POS_NONE);
     }
     Talk(FLAME_LEVIATHAN_SAY_DEATH);
     TurnGates(false, true);
     BindPlayers();
 }
References ACTION_DESPAWN_ADDS, DATA_VEHICLE_SPAWN, DONE, FLAME_LEVIATHAN_SAY_DEATH, summons, TYPE_LEVIATHAN, and VEHICLE_POS_NONE.
JustReachedHome()
void boss_flame_leviathan::boss_flame_leviathanAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 227 of file boss_flame_leviathan.cpp.
         {
             // For achievement
             if (m_pInstance)
                 m_pInstance->SetData(DATA_UNBROKEN_ACHIEVEMENT, 0);
             me->setActive(false);
         }
References DATA_UNBROKEN_ACHIEVEMENT, m_pInstance, ScriptedAI::me, WorldObject::setActive(), and ZoneScript::SetData().
JustSummoned()
void boss_flame_leviathan::boss_flame_leviathanAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 236 of file boss_flame_leviathan.cpp.
         {
             if (cr->GetEntry() != NPC_FLAME_LEVIATHAN_TURRET && cr->GetEntry() != NPC_SEAT)
                 summons.Summon(cr);
         }
References Object::GetEntry(), NPC_FLAME_LEVIATHAN_TURRET, NPC_SEAT, SummonList::Summon(), and summons.
KilledUnit()
void boss_flame_leviathan::boss_flame_leviathanAI::KilledUnit (Unit * who) override virtual
Reimplemented from ScriptedAI.
Definition at line 646 of file boss_flame_leviathan.cpp.
 {
     if (who == me->GetVictim())
         events.RescheduleEvent(EVENT_PURSUE, 0);
     if (who->GetTypeId() == TYPEID_PLAYER)
         Talk(FLAME_LEVIATHAN_SAY_SLAY);
 }
References EVENT_PURSUE, FLAME_LEVIATHAN_SAY_SLAY, Object::GetTypeId(), Unit::GetVictim(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_flame_leviathan::boss_flame_leviathanAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 235 of file boss_flame_leviathan.cpp.
 {}
RadioSay()
void boss_flame_leviathan::boss_flame_leviathanAI::RadioSay (const char * text, uint32 soundId)
Definition at line 496 of file boss_flame_leviathan.cpp.
 {
     if (Creature* r = me->SummonCreature(NPC_BRANN_RADIO, me->GetPositionX() - 150, me->GetPositionY(), me->GetPositionZ(), me->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN, 5000))
     {
         WorldPacket data;
         ChatHandler::BuildChatPacket(data, CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, r, nullptr, text);
         r->SendMessageToSetInRange(&data, 200, true);
         r->PlayDirectSound(soundId);
     }
 }
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, NPC_BRANN_RADIO, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by UpdateAI().
Reset()
void boss_flame_leviathan::boss_flame_leviathanAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 285 of file boss_flame_leviathan.cpp.
         {
             // Special immunity case
             me->CastSpell(me, SPELL_INVIS_AND_STEALTH_DETECT, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, true);
             summons.DoAction(ACTION_DESPAWN_ADDS);
             summons.DespawnAll();
             events.Reset();
             _shutdown = false;
             _startTimer = 1;
             _speakTimer = 0;
             _towersCount = 0;
             _destroyedTurretCount = 0;
             if (m_pInstance)
             {
                 if (m_pInstance->GetData(TYPE_LEVIATHAN) != SPECIAL)
                 {
                     m_pInstance->SetData(TYPE_LEVIATHAN, NOT_STARTED);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 }
                 else
                 {
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     m_pInstance->SetData(DATA_VEHICLE_SPAWN, VEHICLE_POS_LEVIATHAN);
                     _startTimer = 0;
                 }
             }
             TurnGates(false, false);
             TurnHealStations(true);
         }
References _destroyedTurretCount, _shutdown, _speakTimer, _startTimer, _towersCount, ACTION_DESPAWN_ADDS, Unit::ApplySpellImmune(), Unit::CastSpell(), DATA_VEHICLE_SPAWN, SummonList::DespawnAll(), SummonList::DoAction(), ZoneScript::GetData(), IMMUNITY_STATE, m_pInstance, ScriptedAI::me, NOT_STARTED, Object::RemoveFlag(), ZoneScript::SetData(), Object::SetFlag(), SPECIAL, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, SPELL_INVIS_AND_STEALTH_DETECT, summons, TurnGates(), TurnHealStations(), TYPE_LEVIATHAN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and VEHICLE_POS_LEVIATHAN.
ScheduleEvents()
void boss_flame_leviathan::boss_flame_leviathanAI::ScheduleEvents ()
Definition at line 599 of file boss_flame_leviathan.cpp.
 {
     events.RescheduleEvent(EVENT_MISSILE, 5000);
     events.RescheduleEvent(EVENT_VENT, 20000);
     events.RescheduleEvent(EVENT_SPEED, 15000);
     events.RescheduleEvent(EVENT_SUMMON, 10000);
     events.RescheduleEvent(EVENT_SOUND_BEGINNING, 10000);
     events.RescheduleEvent(EVENT_POSITION_CHECK, 5000);
     events.RescheduleEvent(EVENT_PURSUE, 0);
 }
References EVENT_MISSILE, EVENT_POSITION_CHECK, EVENT_PURSUE, EVENT_SOUND_BEGINNING, EVENT_SPEED, EVENT_SUMMON, and EVENT_VENT.
Referenced by EnterCombat().
SpellHit()
void boss_flame_leviathan::boss_flame_leviathanAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) override virtual
Reimplemented from ScriptedAI.
Definition at line 611 of file boss_flame_leviathan.cpp.
 {
     if (spellInfo->Id == SPELL_SYSTEMS_SHUTDOWN)
     {
         _shutdown = true; // ACHIEVEMENT
         Talk(FLAME_LEVIATHAN_EMOTE_OVERLOAD);
         Talk(FLAME_LEVIATHAN_EMOTE_REPAIR);
         Talk(FLAME_LEVIATHAN_SAY_OVERLOAD);
         events.DelayEvents(20 * IN_MILLISECONDS + 1);
         events.ScheduleEvent(EVENT_REINSTALL, 20 * IN_MILLISECONDS);
     }
     else if (spellInfo->Id == 62522 /*SPELL_ELECTROSHOCK*/)
         me->InterruptNonMeleeSpells(false);
 }
References EVENT_REINSTALL, FLAME_LEVIATHAN_EMOTE_OVERLOAD, FLAME_LEVIATHAN_EMOTE_REPAIR, FLAME_LEVIATHAN_SAY_OVERLOAD, SpellInfo::Id, IN_MILLISECONDS, and SPELL_SYSTEMS_SHUTDOWN.
SpellHitTarget()
void boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget (Unit * target, SpellInfo const * spell) override virtual
Reimplemented from ScriptedAI.
Definition at line 685 of file boss_flame_leviathan.cpp.
 {
     if (spell->Id != SPELL_PURSUED)
         return;
     for (SeatMap::const_iterator itr = target->GetVehicleKit()->Seats.begin(); itr != target->GetVehicleKit()->Seats.end(); ++itr)
     {
         if (Player* passenger = ObjectAccessor::GetPlayer(*me, itr->second.Passenger.Guid))
         {
             Talk(FLAME_LEVIATHAN_EMOTE_PURSUE, passenger);
             return;
         }
     }
 }
References FLAME_LEVIATHAN_EMOTE_PURSUE, ObjectAccessor::GetPlayer(), Unit::GetVehicleKit(), SpellInfo::Id, Vehicle::Seats, and SPELL_PURSUED.
SummonedCreatureDespawn()
void boss_flame_leviathan::boss_flame_leviathanAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 242 of file boss_flame_leviathan.cpp.
 { summons.Despawn(cr); }
References SummonList::Despawn(), and summons.
SummonTowerHelpers()
void boss_flame_leviathan::boss_flame_leviathanAI::SummonTowerHelpers (uint8 towerId)
Definition at line 655 of file boss_flame_leviathan.cpp.
 {
     if (towerId == TOWER_OF_LIFE)
     {
         me->SummonCreature(NPC_FREYA_WARD_TARGET, 374, -141, 411, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD, 374, -141, 411 + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD_TARGET, 382.9f, 74, 411.6f, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD, 382.9f, 74, 411.6f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD_TARGET, 159.4f, 64.1f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD, 159.4f, 64.1f, 409.8f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD_TARGET, 157.7f, -140.26f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_FREYA_WARD, 157.7f, -140.26f, 409.8f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
     }
     else if (towerId == TOWER_OF_FROST)
     {
         me->SummonCreature(NPC_HODIRS_FURY_TARGET, 343.4f, -77.5f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
         me->SummonCreature(NPC_HODIRS_FURY_TARGET, 222, 41, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
     }
     else if (towerId == TOWER_OF_FLAMES)
     {
         me->SummonCreature(NPC_MIMIRONS_INFERNO_TARGET, 364.4f, -9.7f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
         //me->SummonCreature(NPC_MIMIRONS_INFERNO, 364.4f, -9.7f, 409.8f+40, 0, TEMPSUMMON_MANUAL_DESPAWN);
     }
     else if (towerId == TOWER_OF_STORMS)
     {
         for (uint8 i = 0; i < 8; ++i)
             me->SummonCreature(NPC_THORIM_HAMMER_TARGET, 157 + rand() % 200, -140 + rand() % 200, 409.8f, 0, TEMPSUMMON_TIMED_DESPAWN, 24000);
     }
 }
References NPC_FREYA_WARD, NPC_FREYA_WARD_TARGET, NPC_HODIRS_FURY_TARGET, NPC_MIMIRONS_INFERNO_TARGET, NPC_THORIM_HAMMER_TARGET, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TOWER_OF_FLAMES, TOWER_OF_FROST, TOWER_OF_LIFE, and TOWER_OF_STORMS.
Referenced by UpdateAI().
TurnGates()
void boss_flame_leviathan::boss_flame_leviathanAI::TurnGates (bool _start, bool _death)
Definition at line 541 of file boss_flame_leviathan.cpp.
 {
     if (!m_pInstance)
         return;
     if (_start)
     {
         // first one is ALWAYS turned on, unless leviathan is beaten
         GameObject* go = nullptr;
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_LIGHTNING_WALL2))))
             go->SetGoState(GO_STATE_READY);
         if (m_pInstance->GetData(TYPE_LEVIATHAN) == NOT_STARTED)
             if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_LEVIATHAN_DOORS))))
                 go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
     }
     else
     {
         GameObject* go = nullptr;
         if (_death)
             if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_LIGHTNING_WALL1))))
                 go->SetGoState(GO_STATE_ACTIVE);
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_LIGHTNING_WALL2))))
             go->SetGoState(GO_STATE_ACTIVE);
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_LEVIATHAN_DOORS))))
         {
             if (m_pInstance->GetData(TYPE_LEVIATHAN) == SPECIAL || m_pInstance->GetData(TYPE_LEVIATHAN) == DONE)
                 go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
             else
                 go->SetGoState(GO_STATE_READY);
         }
     }
 }
References DATA_LIGHTNING_WALL1, DATA_LIGHTNING_WALL2, DONE, ObjectAccessor::GetGameObject(), GO_LEVIATHAN_DOORS, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, NOT_STARTED, GameObject::SetGoState(), SPECIAL, and TYPE_LEVIATHAN.
Referenced by EnterCombat(), and Reset().
TurnHealStations()
void boss_flame_leviathan::boss_flame_leviathanAI::TurnHealStations (bool _apply)
Definition at line 577 of file boss_flame_leviathan.cpp.
 {
     if (!m_pInstance)
         return;
     GameObject* go = nullptr;
     if (_apply)
     {
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_REPAIR_STATION1))))
             go->SetLootState(GO_READY);
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_REPAIR_STATION2))))
             go->SetLootState(GO_READY);
     }
     else
     {
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_REPAIR_STATION1))))
             go->SetLootState(GO_ACTIVATED);
         if ((go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(DATA_REPAIR_STATION2))))
             go->SetLootState(GO_ACTIVATED);
     }
 }
References DATA_REPAIR_STATION1, DATA_REPAIR_STATION2, ObjectAccessor::GetGameObject(), GO_ACTIVATED, GO_READY, and GameObject::SetLootState().
Referenced by EnterCombat(), and Reset().
UpdateAI()
void boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 330 of file boss_flame_leviathan.cpp.
         {
             // THIS IS USED ONLY FOR FIRST ENGAGE!
             if (_startTimer)
             {
                 _startTimer += diff;
                 if (_startTimer >= 4000)
                 {
                     // Colossus dead, players in range
                     if (me->FindNearestCreature(NPC_ULDUAR_COLOSSUS, 250.0f, true) || !SelectTargetFromPlayerList(250.0f))
                         _startTimer = 1;
                     else
                     {
                         _startTimer = 0;
                         _speakTimer = 1;
                     }
                 }
                 return;
             }
             if (_speakTimer)
             {
                 _speakTimer += diff;
                 if (_speakTimer <= 10000)
                 {
                     RadioSay("You've done it! You've broken the defenses of Ulduar. In a few moments, we will be dropping in to...", RSOUND_L1);
                     _speakTimer = 10000;
                 }
                 else if (_speakTimer > 16000 && _speakTimer < 20000)
                 {
                     _speakTimer = 20000;
                     RadioSay("What is that? Be careful! Something's headed your way!", RSOUND_L2);
                 }
                 else if (_speakTimer > 24000 && _speakTimer < 40000)
                 {
                     _speakTimer = 40000;
                     RadioSay("Quicly! Evasive action! Evasive act--", RSOUND_L3);
                 }
                 else if (_speakTimer > 41000 && _speakTimer < 60000)
                 {
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SendMonsterMove(380.4f, -14.3f, 409.8f, 2000);
                     me->UpdatePosition(380.4f, -14.3f, 409.8f, me->GetOrientation());
                     _speakTimer = 60000;
                 }
                 else if (_speakTimer > 61500)
                 {
                     me->SetInCombatWithZone();
                     if (!me->GetVictim())
                     {
                         me->CastSpell(me, SPELL_PURSUED, false);
                         events.RescheduleEvent(EVENT_PURSUE, 31000);
                     }
                     _speakTimer = 0;
                 }
                 return;
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_POSITION_CHECK:
                     if (me->GetPositionX() > 450 || me->GetPositionX() < 120)
                     {
                         EnterEvadeMode();
                         return;
                     }
                     events.RepeatEvent(5000);
                     break;
                 case EVENT_PURSUE:
                     Talk(FLAME_LEVIATHAN_SAY_PURSUE);
                     me->CastSpell(me, SPELL_PURSUED, false);
                     events.RescheduleEvent(EVENT_PURSUE, 31000);
                     return;
                 case EVENT_SPEED:
                     me->CastSpell(me, SPELL_GATHERING_SPEED, false);
                     events.RepeatEvent(15000);
                     return;
                 case EVENT_MISSILE:
                     me->CastSpell(me, SPELL_MISSILE_BARRAGE, true);
                     events.RepeatEvent(4000);
                     return;
                 case EVENT_VENT:
                     me->CastSpell(me, SPELL_FLAME_VENTS, false);
                     events.RepeatEvent(20000);
                     return;
                 case EVENT_SUMMON:
                     if(summons.size() < 20)
                         if (Creature* lift = DoSummonFlyer(NPC_MECHANOLIFT, me, 30.0f, 50.0f, 0))
                             lift->GetMotionMaster()->MoveRandom(100);
                     events.RepeatEvent(4000);
                     return;
                 case EVENT_SOUND_BEGINNING:
                     if (_towersCount)
                         Talk(FLAME_LEVIATHAN_SAY_HARDMODE);
                     else
                         Talk(FLAME_LEVIATHAN_SAY_TOWER_NONE);
                     return;
                 case EVENT_REINSTALL:
                     for (uint8 i = RAID_MODE(0, 2); i < 4; ++i)
                         if (Unit* seat = vehicle->GetPassenger(i))
                             if (seat->GetTypeId() == TYPEID_UNIT)
                                 seat->ToCreature()->AI()->EnterEvadeMode();
                     me->TextEmote("Flame Leviathan reactivated. Resumming combat functions.", nullptr, true);
                     return;
                 case EVENT_THORIMS_HAMMER:
                     SummonTowerHelpers(TOWER_OF_STORMS);
                     events.RepeatEvent(60000 + rand() % 60000);
                     me->TextEmote("Flame Leviathan activates Thorim's Hammer.", nullptr, true);
                     Talk(FLAME_LEVIATHAN_SAY_TOWER_STORM);
                     return;
                 case EVENT_FREYA:
                     SummonTowerHelpers(TOWER_OF_LIFE);
                     me->TextEmote("Flame Leviathan activates Freya's Ward.", nullptr, true);
                     Talk(FLAME_LEVIATHAN_SAY_TOWER_NATURE);
                     return;
                 case EVENT_MIMIRONS_INFERNO:
                     SummonTowerHelpers(TOWER_OF_FLAMES);
                     me->TextEmote("Flame Leviathan activates Mimiron's Inferno.", nullptr, true);
                     Talk(FLAME_LEVIATHAN_SAY_TOWER_FLAME);
                     return;
                 case EVENT_HODIRS_FURY:
                     SummonTowerHelpers(TOWER_OF_FROST);
                     me->TextEmote("Flame Leviathan activates Hodir's Fury.", nullptr, true);
                     Talk(FLAME_LEVIATHAN_SAY_TOWER_FROST);
                     return;
             }
             if(me->isAttackReady() && !me->HasUnitState(UNIT_STATE_STUNNED))
             {
                 if(me->IsWithinCombatRange(me->GetVictim(), 15.0f))
                 {
                     me->CastSpell(me->GetVictim(), SPELL_BATTERING_RAM, false);
                     me->resetAttackTimer();
                 }
             }
         }
References _speakTimer, _startTimer, _towersCount, Unit::CastSpell(), CreatureAI::DoSummonFlyer(), CreatureAI::EnterEvadeMode(), EVENT_FREYA, EVENT_HODIRS_FURY, EVENT_MIMIRONS_INFERNO, EVENT_MISSILE, EVENT_POSITION_CHECK, EVENT_PURSUE, EVENT_REINSTALL, EVENT_SOUND_BEGINNING, EVENT_SPEED, EVENT_SUMMON, EVENT_THORIMS_HAMMER, EVENT_VENT, WorldObject::FindNearestCreature(), FLAME_LEVIATHAN_SAY_HARDMODE, FLAME_LEVIATHAN_SAY_PURSUE, FLAME_LEVIATHAN_SAY_TOWER_FLAME, FLAME_LEVIATHAN_SAY_TOWER_FROST, FLAME_LEVIATHAN_SAY_TOWER_NATURE, FLAME_LEVIATHAN_SAY_TOWER_NONE, FLAME_LEVIATHAN_SAY_TOWER_STORM, Position::GetOrientation(), Vehicle::GetPassenger(), Position::GetPositionX(), Unit::GetVictim(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinCombatRange(), ScriptedAI::me, NPC_MECHANOLIFT, NPC_ULDUAR_COLOSSUS, RadioSay(), ScriptedAI::RAID_MODE(), Object::RemoveFlag(), Unit::resetAttackTimer(), RSOUND_L1, RSOUND_L2, RSOUND_L3, ScriptedAI::SelectTargetFromPlayerList(), Unit::SendMonsterMove(), Creature::SetInCombatWithZone(), SummonList::size(), SPELL_BATTERING_RAM, SPELL_FLAME_VENTS, SPELL_GATHERING_SPEED, SPELL_MISSILE_BARRAGE, SPELL_PURSUED, summons, SummonTowerHelpers(), CreatureAI::Talk(), Unit::TextEmote(), TOWER_OF_FLAMES, TOWER_OF_FROST, TOWER_OF_LIFE, TOWER_OF_STORMS, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, Unit::UpdatePosition(), CreatureAI::UpdateVictim(), and vehicle.
Member Data Documentation
_destroyedTurretCount
uint32 boss_flame_leviathan::boss_flame_leviathanAI::_destroyedTurretCount
Definition at line 215 of file boss_flame_leviathan.cpp.
Referenced by DoAction(), and Reset().
_shutdown
bool boss_flame_leviathan::boss_flame_leviathanAI::_shutdown
Definition at line 214 of file boss_flame_leviathan.cpp.
Referenced by GetData(), and Reset().
_speakTimer
uint32 boss_flame_leviathan::boss_flame_leviathanAI::_speakTimer
Definition at line 212 of file boss_flame_leviathan.cpp.
Referenced by Reset(), and UpdateAI().
_startTimer
uint32 boss_flame_leviathan::boss_flame_leviathanAI::_startTimer
Definition at line 211 of file boss_flame_leviathan.cpp.
Referenced by Reset(), and UpdateAI().
_towersCount
uint8 boss_flame_leviathan::boss_flame_leviathanAI::_towersCount
Definition at line 213 of file boss_flame_leviathan.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
events
EventMap boss_flame_leviathan::boss_flame_leviathanAI::events
Definition at line 208 of file boss_flame_leviathan.cpp.
m_pInstance
InstanceScript* boss_flame_leviathan::boss_flame_leviathanAI::m_pInstance
Definition at line 206 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI(), EnterCombat(), InitializeAI(), JustReachedHome(), and Reset().
summons
SummonList boss_flame_leviathan::boss_flame_leviathanAI::summons
Definition at line 209 of file boss_flame_leviathan.cpp.
Referenced by JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
vehicle
Vehicle* boss_flame_leviathan::boss_flame_leviathanAI::vehicle
Definition at line 207 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp