Azerotcore-wotlk: G3D::Map2D< Storage, Compute > Class Template Reference
G3D::Map2D< Storage, Compute > Class Template Reference
#include <Map2D.h>
Public Types
typedef Storage StorageType
typedef Compute ComputeType
typedef Map2D< Storage, Compute > Type
typedef shared_ptr< Map2D > Ref
Public Member Functions
const Storage & fastGet (int x, int y) const
void fastSet (int x, int y, const Storage &v)
void resize (uint32 newW, uint32 newH)
bool changed ()
void setChanged (bool c)
Storage * getCArray ()
const Storage * getCArray () const
Array< Storage > & getArray ()
const Array< Storage > & getArray () const
bool inBounds (int x, int y) const
bool inBounds (const Vector2int16 &v) const
const Storage & get (int x, int y, WrapMode wrap) const
const Storage & get (int x, int y) const
const Storage & get (const Vector2int16 &p) const
const Storage & get (const Vector2int16 &p, WrapMode wrap) const
Storage & get (int x, int y, WrapMode wrap)
Storage & get (int x, int y)
Storage & get (const Vector2int16 &p)
void set (const Vector2int16 &p, const Storage &v)
void set (int x, int y, const Storage &v, WrapMode wrap)
void set (int x, int y, const Storage &v)
void setAll (const Storage &v)
template<class T >
void set (const shared_ptr< Map2D< Storage, T > > &src)
void maybeFlipVertical (bool flip)
virtual void flipVertical ()
virtual void flipHorizontal ()
virtual void crop (int newX, int newY, int newW, int newH)
virtual void crop (const Rect2D &rect)
Compute nearest (float x, float y, WrapMode wrap) const
Compute nearest (float x, float y) const
Compute nearest (const Vector2 &p) const
Compute average () const
Compute bilinear (float x, float y, WrapMode wrap) const
Compute bilinear (float x, float y) const
Compute bilinear (const Vector2 &p) const
Compute bilinear (const Vector2 &p, WrapMode wrap) const
Compute bicubic (float x, float y, WrapMode wrap) const
Compute bicubic (float x, float y) const
Compute bicubic (const Vector2 &p, WrapMode wrap) const
Compute bicubic (const Vector2 &p) const
int32 width () const
int32 height () const
Vector2int16 size () const
Rect2D rect2DBounds () const
size_t sizeInMemory () const
WrapMode wrapMode () const
void setWrapMode (WrapMode m)
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static Ref create (int w=0, int h=0, WrapMode wrap=WrapMode::ERROR)
Public Attributes
GMutex mutex
Protected Member Functions
const Storage & slowGet (int x, int y, WrapMode wrap)
Compute bicubic (const Compute *ctrl, double s) const
Map2D (int w, int h, WrapMode wrap)
Protected Attributes
Storage ZERO
uint32 w
uint32 h
WrapMode _wrapMode
AtomicInt32 m_changed
Array< Storage > data
Detailed Description
template<typename Storage, typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type>
class G3D::Map2D< Storage, Compute >
Map of values across a discrete 2D plane. Can be thought of as a generic class for 2D images, allowing flexibility as to pixel format and convenient methods. In fact, the "pixels" can be any values on a grid that can be sensibly interpolated–RGB colors, scalars, 4D vectors, and so on.
Other "image" classes in G3D:
G3D::GImage - Supports file formats, fast, Color3uint8 and Color4uint8 formats. No interpolation.
G3D::shared_ptr<Texture> - Represents image on the graphics card (not directly readable on the CPU). Supports 2D, 3D, and a variety of interpolation methods, loads file formats.
G3D::Image3 - A subclass of Map2D<Color3> that supports image loading and saving and conversion to Texture.
G3D::Image4 - A subclass of Map2D<Color4> that supports image loading and saving and conversion to Texture.
G3D::Image3uint8 - A subclass of Map2D<Color3uint8> that supports image loading and saving and conversion to Texture.
G3D::Image4uint8 - A subclass of Map2D<Color4uint8> that supports image loading and saving and conversion to Texture.
There are two type parameters– the first (@ Storage) is the type used to store the "pixel" values efficiently and the second (Compute) is the type operated on by computation. The Compute::Compute(Storage&) constructor is used to convert between storage and computation types. Storage is often an integer version of Compute, for example Map2D<double, uint8>. By default, the computation type is:
   Storage       Computation
   uint8          float32
   uint16         float32
   uint32         float64
   uint64         float64
   int8           float32
   int16          float32
   int32          float64
   int64          float64
   float32        float64
   float64        float64
   Vector2        Vector2
   Vector2int16   Vector2
   Vector3        Vector3
   Vector3int16   Vector3
   Vector4        Vector4
   Color3         Color3
   Color3uint8    Color3
   Color4         Color4
   Color4uint8    Color4
Any other storage type defaults to itself as the computation type.
The computation type can be any that supports lerp, +, -, *, /, and an empty constructor.
Assign value:
im->set(x, y, 7); or im->get(x, y) = 7;
Read value:
int c = im(x, y);
Can also sample with nearest neighbor, bilinear, and bicubic interpolation.
Sampling follows OpenGL conventions, where pixel values represent grid points and (0.5, 0.5) is half-way between two vertical and two horizontal grid points.
To draw an image of dimensions w x h with nearest neighbor sampling, render pixels from [0, 0] to [w - 1, h - 1].
Under the WrapMode::CLAMP wrap mode, the value of bilinear interpolation becomes constant outside [1, w - 2] horizontally. Nearest neighbor interpolation is constant outside [0, w - 1] and bicubic outside [3, w - 4]. The class does not offer quadratic interpolation because the interpolation filter could not center over a pixel.
Author
Morgan McGuire, http://graphics.cs.williams.edu
Definition at line 171 of file Map2D.h.
Member Typedef Documentation
ComputeType
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> typedef Compute G3D::Map2D< Storage, Compute >::ComputeType
Definition at line 182 of file Map2D.h.
Ref
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> typedef shared_ptr<Map2D> G3D::Map2D< Storage, Compute >::Ref
Definition at line 184 of file Map2D.h.
StorageType
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> typedef Storage G3D::Map2D< Storage, Compute >::StorageType
Definition at line 181 of file Map2D.h.
Type
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> typedef Map2D<Storage, Compute> G3D::Map2D< Storage, Compute >::Type
Definition at line 183 of file Map2D.h.
Constructor & Destructor Documentation
Map2D()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> G3D::Map2D< Storage, Compute >::Map2D (int w, int h, WrapMode wrap) inline protected
Definition at line 284 of file Map2D.h.
                                        : w(0), h(0), _wrapMode(wrap), m_changed(1) {
         ZERO = Storage(Compute(Storage()) * 0);
         resize(w, h);
     }
References Acore::Compute(), G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::resize(), G3D::Map2D< Storage, Compute >::w, and G3D::Map2D< Storage, Compute >::ZERO.
Referenced by G3D::Map2D< Storage, Compute >::create().
Member Function Documentation
average()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::average () const inline
Returns the average value of all elements of the map
Definition at line 539 of file Map2D.h.
{
         if ((w == 0) || (h == 0)) {
             return ZERO;
         }
         // To avoid overflows, compute the average of row averages
         Compute rowSum = ZERO;
         for (unsigned int y = 0; y < h; ++y) {
             Compute sum = ZERO;
             int offset = y * w;
             for (unsigned int x = 0; x < w; ++x) {
                 sum += Compute(data[offset + x]);
             }
             rowSum += sum * (1.0f / w);
         }
         return rowSum * (1.0f / h);
     }
References Acore::Compute(), G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::w, G3D::x, G3D::y, and G3D::Map2D< Storage, Compute >::ZERO.
bicubic() [1/5]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bicubic (const Compute * ctrl, double s) const inline protected
Given four control points and a value on the range [0, 1) evaluates the Catmull-rom spline between the times of the middle two control points
Definition at line 251 of file Map2D.h.
{
         // f = B * S * ctrl'
         // B matrix: Catmull-Rom spline basis
         static const double B[4][4] = {
             { 0.0, -0.5,  1.0, -0.5},
             { 1.0,  0.0, -2.5,  1.5},
             { 0.0,  0.5,  2.0, -1.5},
             { 0.0,  0.0, -0.5,  0.5}};
         // S: Powers of the fraction
         double S[4];
         double s2 = s * s;
         S[0] = 1.0;
         S[1] = s;
         S[2] = s2;
         S[3] = s2 * s;
         Compute sum(ZERO);
         for (int c = 0; c < 4; ++c) {
             double coeff = 0.0;
             for (int power = 0; power < 4; ++power) {
                 coeff += B[c][power] * S[power];
             }
             sum += ctrl[c] * coeff;
         }
         return sum;
     }
References mpq::c, Acore::Compute(), and G3D::Map2D< Storage, Compute >::ZERO.
Referenced by G3D::Map2D< Storage, Compute >::bicubic().
bicubic() [2/5]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bicubic (const Vector2 & p) const inline
Definition at line 634 of file Map2D.h.
{
         return bicubic(p.x, p.y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::bicubic(), G3D::Vector2::x, and G3D::Vector2::y.
bicubic() [3/5]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bicubic (const Vector2 & p, WrapMode wrap) const inline
Definition at line 630 of file Map2D.h.
{
         return bicubic(p.x, p.y, wrap);
     }
References G3D::Map2D< Storage, Compute >::bicubic(), G3D::wrap(), G3D::Vector2::x, and G3D::Vector2::y.
bicubic() [4/5]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bicubic (float x, float y) const inline
Definition at line 626 of file Map2D.h.
{
         return bicubic(x, y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::bicubic(), G3D::x, and G3D::y.
bicubic() [5/5]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bicubic (float x, float y, WrapMode wrap) const inline
Uses Catmull-Rom splines to interpolate between grid values. Guaranteed to match nearest(x, y) at integers.
Definition at line 604 of file Map2D.h.
{
         int i = iFloor(x);
         int j = iFloor(y);
         float fX = x - i;
         float fY = y - j;
         Compute vsample[4];
         for (int v = 0; v < 4; ++v) {
             // Horizontal interpolation
             Compute hsample[4];
             for (int u = 0; u < 4; ++u) {
                 hsample[u] = Compute(get(i + u - 1, j + v - 1, wrap));
             }
             vsample[v] = bicubic(hsample, fX);
         }
         //  Vertical interpolation
         return bicubic(vsample, fY);
     }
References G3D::Map2D< Storage, Compute >::bicubic(), Acore::Compute(), G3D::Map2D< Storage, Compute >::get(), G3D::iFloor(), G3D::wrap(), G3D::x, and G3D::y.
bilinear() [1/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bilinear (const Vector2 & p) const inline
Definition at line 592 of file Map2D.h.
{
         return bilinear(p.x, p.y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::bilinear(), G3D::Vector2::x, and G3D::Vector2::y.
bilinear() [2/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bilinear (const Vector2 & p, WrapMode wrap) const inline
Definition at line 596 of file Map2D.h.
{
         return bilinear(p.x, p.y, wrap);
     }
References G3D::Map2D< Storage, Compute >::bilinear(), G3D::wrap(), G3D::Vector2::x, and G3D::Vector2::y.
bilinear() [3/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bilinear (float x, float y) const inline
Definition at line 588 of file Map2D.h.
{
         return bilinear(x, y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::bilinear(), G3D::x, and G3D::y.
bilinear() [4/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::bilinear (float x, float y, WrapMode wrap) const inline
Needs to access elements from (floor(x), floor(y)) to (floor(x) + 1, floor(y) + 1) and will use the wrap mode appropriately (possibly generating out of bounds errors).
Guaranteed to match nearest(x, y) at integers.
Definition at line 566 of file Map2D.h.
{
         const int i = iFloor(x);
         const int j = iFloor(y);
         const float fX = x - i;
         const float fY = y - j;
         // Horizontal interpolation, first row
         const Compute& t0 = get(i, j, wrap);
         const Compute& t1 = get(i + 1, j, wrap);
         // Horizontal interpolation, second row
         const Compute& t2 = get(i, j + 1, wrap);
         const Compute& t3 = get(i + 1, j + 1, wrap);
         const Compute& A = lerp(t0, t1, fX);
         const Compute& B = lerp(t2, t3, fX);
         // Vertical interpolation
         return lerp(A, B, fY);
     }
References Acore::Compute(), G3D::Map2D< Storage, Compute >::get(), G3D::iFloor(), G3D::lerp(), G3D::wrap(), G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::bilinear().
changed()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> bool G3D::Map2D< Storage, Compute >::changed () inline
Returns true if this map has been written to since the last call to setChanged(false). This is useful if you are caching a texture map other value that must be recomputed whenever this changes.
Definition at line 318 of file Map2D.h.
                    {
         return m_changed.value() != 0;
     }
References G3D::Map2D< Storage, Compute >::m_changed, and G3D::AtomicInt32::value().
create()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> static Ref G3D::Map2D< Storage, Compute >::create (int w = 0, int h = 0, WrapMode wrap = WrapMode::ERROR) inline static
Definition at line 298 of file Map2D.h.
{
         return Ref(new Map2D(w, h, wrap));
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::Map2D(), G3D::Map2D< Storage, Compute >::w, and G3D::wrap().
crop() [1/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> virtual void G3D::Map2D< Storage, Compute >::crop (const Rect2D & rect) inline virtual
iRounds to the nearest x0 and y0.
Definition at line 517 of file Map2D.h.
{
         crop(iRound(rect.x0()), iRound(rect.y0()), iRound(rect.x1()) - iRound(rect.x0()), iRound(rect.y1()) - iRound(rect.y0()));
     }
References G3D::Map2D< Storage, Compute >::crop(), G3D::iRound(), G3D::Rect2D::x0(), G3D::Rect2D::x1(), G3D::Rect2D::y0(), and G3D::Rect2D::y1().
crop() [2/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> virtual void G3D::Map2D< Storage, Compute >::crop (int newX, int newY, int newW, int newH) inline virtual
Crops this map so that it only contains pixels between (x, y) and (x + w - 1, y + h - 1) inclusive.
Definition at line 499 of file Map2D.h.
{
         alwaysAssertM(newX + newW <= (int)w, "Cannot grow when cropping");
         alwaysAssertM(newY + newH <= (int)h, "Cannot grow when cropping");
         alwaysAssertM(newX >= 0 && newY >= 0, "Origin out of bounds.");
         // Always safe to copy towards the upper left, provided
         // that we're iterating towards the lower right.  This lets us avoid
         // reallocating the underlying array.
         for (int y = 0; y < newH; ++y) {
             for (int x = 0; x < newW; ++x) {
                 data[x + y * newW] = data[(x + newX) + (y + newY) * w];
             }
         }
         resize(newW, newH);
     }
References alwaysAssertM, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::resize(), G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::crop().
fastGet()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::fastGet (int x, int y) const inline
Unsafe access to the underlying data structure with no wrapping support; requires that (x, y) is in bounds.
Definition at line 235 of file Map2D.h.
{
         debugAssert(((uint32)x < w) && ((uint32)y < h));
         return data[x + y * w];
     }
References debugAssert, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::slowGet().
fastSet()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::fastSet (int x, int y, const Storage & v) inline
Unsafe access to the underlying data structure with no wrapping support; requires that (x, y) is in bounds.
Definition at line 241 of file Map2D.h.
{
         debugAssert(((uint32)x < w) && ((uint32)y < h));
         data[x + y * w] = v;
     }
References debugAssert, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
flipHorizontal()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> virtual void G3D::Map2D< Storage, Compute >::flipHorizontal () inline virtual
Definition at line 481 of file Map2D.h.
{
         int halfWidth = w / 2;
         Storage* d = data.getCArray();
         for (int x = 0; x < halfWidth; ++x) {
             for (int y = 0; y < (int)h; ++y) {
                 int i1 = y * w + x;
                 int i2 = y * w + (w - x - 1);
                 Storage temp = d[i1];
                 d[i1] = d[i2];
                 d[i2] = temp;
             }
         }
         setChanged(true);
     }
References mpq::d, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::setChanged(), G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
flipVertical()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> virtual void G3D::Map2D< Storage, Compute >::flipVertical () inline virtual
Definition at line 464 of file Map2D.h.
{
         int halfHeight = h/2;
         Storage* d = data.getCArray();
         for (int y = 0; y < halfHeight; ++y) {
             int o1 = y * w;
             int o2 = (h - y - 1) * w;
             for (int x = 0; x < (int)w; ++x) {
                 int i1 = o1 + x;
                 int i2 = o2 + x;
                 Storage temp = d[i1];
                 d[i1] = d[i2];
                 d[i2] = temp;
             }
         }
         setChanged(true);
     }
References mpq::d, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::setChanged(), G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::maybeFlipVertical().
get() [1/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Storage& G3D::Map2D< Storage, Compute >::get (const Vector2int16 & p) inline
Definition at line 412 of file Map2D.h.
{
         return get(p.x, p.y);
     }
References G3D::Map2D< Storage, Compute >::get().
get() [2/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::get (const Vector2int16 & p) const inline
Definition at line 386 of file Map2D.h.
{
         return get(p.x, p.y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, and G3D::Map2D< Storage, Compute >::get().
get() [3/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::get (const Vector2int16 & p, WrapMode wrap) const inline
Definition at line 390 of file Map2D.h.
{
         return get(p.x, p.y, wrap);
     }
References G3D::Map2D< Storage, Compute >::get(), and G3D::wrap().
get() [4/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Storage& G3D::Map2D< Storage, Compute >::get (int x, int y) inline
Definition at line 403 of file Map2D.h.
{
         return const_cast<Storage&>(const_cast<const Type*>(this)->get(x, y));
 #       ifndef G3D_WINDOWS
             // gcc gives a useless warning that the above code might reach the end of the function;
             // we use this line to supress the warning.
             return ZERO;
 #       endif
     }
References G3D::Map2D< Storage, Compute >::get(), G3D::x, G3D::y, and G3D::Map2D< Storage, Compute >::ZERO.
get() [5/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::get (int x, int y) const inline
Definition at line 382 of file Map2D.h.
{
         return get(x, y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::get(), G3D::x, and G3D::y.
get() [6/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Storage& G3D::Map2D< Storage, Compute >::get (int x, int y, WrapMode wrap) inline
Definition at line 394 of file Map2D.h.
{
         return const_cast<Storage&>(const_cast<const Type*>(this)->get(x, y, wrap));
 #       ifndef G3D_WINDOWS
             // gcc gives a useless warning that the above code might reach the end of the function;
             // we use this line to supress the warning.
             return ZERO;
 #       endif
     }
References G3D::Map2D< Storage, Compute >::get(), G3D::wrap(), G3D::x, G3D::y, and G3D::Map2D< Storage, Compute >::ZERO.
get() [7/7]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::get (int x, int y, WrapMode wrap) const inline
Get the value at (x, y).
Note that the type of image->get(x, y) is the storage type, not the computation type. If the constructor promoting Storage to Compute rescales values (as, for example Color3(Color3uint8&) does), this will not match the value returned by Map2D::nearest.
Definition at line 367 of file Map2D.h.
{
         if (((uint32)x < w) && ((uint32)y < h)) {
             return data[x + y * w];
         } else {
             // Remove the const to allow a slowGet on this object
             // (we're returning a const reference so this is ok)
             return const_cast<Type*>(this)->slowGet(x, y, wrap);
         }
 #       ifndef G3D_WINDOWS
             // gcc gives a useless warning that the above code might reach the end of the function;
             // we use this line to supress the warning.
             return ZERO;
 #       endif
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::slowGet(), G3D::Map2D< Storage, Compute >::w, G3D::wrap(), G3D::x, G3D::y, and G3D::Map2D< Storage, Compute >::ZERO.
Referenced by G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::bilinear(), G3D::Map2D< Storage, Compute >::get(), and G3D::Map2D< Storage, Compute >::nearest().
getArray() [1/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Array<Storage>& G3D::Map2D< Storage, Compute >::getArray () inline
Row-major array. You should call setChanged(true) if you mutate the array.
Definition at line 340 of file Map2D.h.
{
         return data;
     }
References G3D::Map2D< Storage, Compute >::data.
getArray() [2/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Array<Storage>& G3D::Map2D< Storage, Compute >::getArray () const inline
Definition at line 345 of file Map2D.h.
{
         return data;
     }
References G3D::Map2D< Storage, Compute >::data.
getCArray() [1/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Storage* G3D::Map2D< Storage, Compute >::getCArray () inline
Returns a pointer to the underlying row-major data. There is no padding at the end of the row. Be careful–this will be reallocated during a resize. You should call setChanged(true) if you mutate the array.
Definition at line 329 of file Map2D.h.
{
         return data.getCArray();
     }
getCArray() [2/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage* G3D::Map2D< Storage, Compute >::getCArray () const inline
Definition at line 334 of file Map2D.h.
{
         return data.getCArray();
     }
height()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> int32 G3D::Map2D< Storage, Compute >::height () const inline
Pixel height
Definition at line 645 of file Map2D.h.
{
         return (int32)h;
     }
References G3D::Map2D< Storage, Compute >::h.
Referenced by G3D::Map2D< Storage, Compute >::set().
inBounds() [1/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> bool G3D::Map2D< Storage, Compute >::inBounds (const Vector2int16 & v) const inline
is (x, y) strictly within the image bounds, or will it trigger some kind of wrap mode
Definition at line 355 of file Map2D.h.
{
         return inBounds(v.x, v.y);
     }
References G3D::Map2D< Storage, Compute >::inBounds().
inBounds() [2/2]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> bool G3D::Map2D< Storage, Compute >::inBounds (int x, int y) const inline
is (x, y) strictly within the image bounds, or will it trigger some kind of wrap mode
Definition at line 350 of file Map2D.h.
{
         return (((uint32)x < w) && ((uint32)y < h));
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::w, G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::inBounds().
maybeFlipVertical()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::maybeFlipVertical (bool flip) inline
flips if flip is true
Definition at line 458 of file Map2D.h.
{
         if (flip) {
             flipVertical();
         }
     }
References G3D::Map2D< Storage, Compute >::flipVertical().
nearest() [1/3]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::nearest (const Vector2 & p) const inline
Definition at line 534 of file Map2D.h.
{
         return nearest(p.x, p.y);
     }
References G3D::Map2D< Storage, Compute >::nearest(), G3D::Vector2::x, and G3D::Vector2::y.
nearest() [2/3]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::nearest (float x, float y) const inline
Definition at line 530 of file Map2D.h.
{
         return nearest(x, y, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::nearest(), G3D::x, and G3D::y.
nearest() [3/3]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Compute G3D::Map2D< Storage, Compute >::nearest (float x, float y, WrapMode wrap) const inline
Returns the nearest neighbor. Pixel values are considered to be at the upper left corner, so image->nearest(x, y) == image(x, y)
Definition at line 524 of file Map2D.h.
{
         int ix = iRound(x);
         int iy = iRound(y);
         return Compute(get(ix, iy, wrap));
     }
References Acore::Compute(), G3D::Map2D< Storage, Compute >::get(), G3D::iRound(), G3D::wrap(), G3D::x, and G3D::y.
Referenced by G3D::Map2D< Storage, Compute >::nearest().
rect2DBounds()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Rect2D G3D::Map2D< Storage, Compute >::rect2DBounds () const inline
Rectangle from (0, 0) to (w, h)
Definition at line 656 of file Map2D.h.
{
         return Rect2D::xywh(0, 0, w, h);
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::w, and G3D::Rect2D::xywh().
resize()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::resize (uint32 newW, uint32 newH) inline
Resizes without clearing, leaving garbage.
Definition at line 304 of file Map2D.h.
{
         if ((newW != w) || (newH != h)) {
             w = newW;
             h = newH;
             data.resize(w * h);
             setChanged(true);
         }
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::setChanged(), and G3D::Map2D< Storage, Compute >::w.
Referenced by G3D::Map2D< Storage, Compute >::crop(), and G3D::Map2D< Storage, Compute >::Map2D().
set() [1/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> template<class T > void G3D::Map2D< Storage, Compute >::set (const shared_ptr< Map2D< Storage, T > > & src) inline
Copy values from src, which must have the same size
Definition at line 446 of file Map2D.h.
{
         debugAssert(src->width() == width());
         debugAssert(src->height() == height());
         const Array<Storage>& s = src->data;
         int N = w * h;
         for (int i = 0; i < N; ++i) {
             data[i] = s[i];
         }
         setChanged(true);
     }
References G3D::Array< T, MIN_ELEMENTS >::data, debugAssert, G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::height(), G3D::Map2D< Storage, Compute >::setChanged(), G3D::Map2D< Storage, Compute >::w, and G3D::Map2D< Storage, Compute >::width().
set() [2/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::set (const Vector2int16 & p, const Storage & v) inline
Sets the changed flag to true
Definition at line 417 of file Map2D.h.
{
         set(p.x, p.y, v);
     }
Referenced by G3D::Map2D< Storage, Compute >::set().
set() [3/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::set (int x, int y, const Storage & v) inline
Definition at line 432 of file Map2D.h.
{
         set(x, y, v, _wrapMode);
     }
References G3D::Map2D< Storage, Compute >::_wrapMode, G3D::Map2D< Storage, Compute >::set(), G3D::x, and G3D::y.
set() [4/4]
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::set (int x, int y, const Storage & v, WrapMode wrap) inline
Sets the changed flag to true
Definition at line 422 of file Map2D.h.
{
         setChanged(true);
         if (((uint32)x < w) && ((uint32)y < h)) {
             // In bounds, wrapping isn't an issue.
             data[x + y * w] = v;
         } else {
             const_cast<Storage&>(slowGet(x, y, wrap)) = v;
         }
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Map2D< Storage, Compute >::setChanged(), G3D::Map2D< Storage, Compute >::slowGet(), G3D::Map2D< Storage, Compute >::w, G3D::wrap(), G3D::x, and G3D::y.
setAll()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::setAll (const Storage & v) inline
Definition at line 437 of file Map2D.h.
{
         for(int i = 0; i < data.size(); ++i) {
             data[i] = v;
         }
         setChanged(true);
     }
References G3D::Map2D< Storage, Compute >::setChanged().
setChanged()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::setChanged (bool c) inline
Set/unset the changed flag.
Definition at line 323 of file Map2D.h.
{
         m_changed = c ? 1 : 0;
     }
References mpq::c, and G3D::Map2D< Storage, Compute >::m_changed.
Referenced by G3D::Map2D< Storage, Compute >::flipHorizontal(), G3D::Map2D< Storage, Compute >::flipVertical(), G3D::Map2D< Storage, Compute >::resize(), G3D::Map2D< Storage, Compute >::set(), and G3D::Map2D< Storage, Compute >::setAll().
setWrapMode()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> void G3D::Map2D< Storage, Compute >::setWrapMode (WrapMode m) inline
Definition at line 671 of file Map2D.h.
{
         _wrapMode = m;
     }
References G3D::Map2D< Storage, Compute >::_wrapMode.
size()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Vector2int16 G3D::Map2D< Storage, Compute >::size () const inline
Dimensions in pixels
Definition at line 651 of file Map2D.h.
{
         return Vector2int16(w, h);
     }
References G3D::Map2D< Storage, Compute >::h, G3D::Vector2int16, and G3D::Map2D< Storage, Compute >::w.
sizeInMemory()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> size_t G3D::Map2D< Storage, Compute >::sizeInMemory () const inline
Number of bytes occupied by the image data and this structure
Definition at line 661 of file Map2D.h.
{
         return data.size() * sizeof(Storage) + sizeof(*this);
     }
slowGet()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> const Storage& G3D::Map2D< Storage, Compute >::slowGet (int x, int y, WrapMode wrap) inline protected
Handles the exceptional cases from get
Definition at line 205 of file Map2D.h.
{
         switch (wrap) {
         case WrapMode::CLAMP:
             return fastGet(iClamp(x, 0, w - 1), iClamp(y, 0, h - 1));
         case WrapMode::TILE:
             return fastGet(iWrap(x, w), iWrap(y, h));
         case WrapMode::ZERO:
             return ZERO;
         case WrapMode::ERROR:
             alwaysAssertM(((uint32)x < w) && ((uint32)y < h),
                 format("Index out of bounds: (%d, %d), w = %d, h = %d",
                 x, y, w, h));
             // intentionally fall through
         case WrapMode::IGNORE:
             // intentionally fall through
         default:
             {
                 static Storage temp;
                 return temp;
             }
         }
     }
References alwaysAssertM, G3D::WrapMode::CLAMP, G3D::WrapMode::ERROR, G3D::Map2D< Storage, Compute >::fastGet(), G3D::format(), G3D::Map2D< Storage, Compute >::h, G3D::iClamp(), G3D::WrapMode::IGNORE, G3D::iWrap(), G3D::WrapMode::TILE, G3D::Map2D< Storage, Compute >::w, G3D::wrap(), G3D::x, G3D::y, G3D::Map2D< Storage, Compute >::ZERO, and G3D::WrapMode::ZERO.
Referenced by G3D::Map2D< Storage, Compute >::get(), and G3D::Map2D< Storage, Compute >::set().
width()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> int32 G3D::Map2D< Storage, Compute >::width () const inline
Pixel width
Definition at line 639 of file Map2D.h.
{
         return (int32)w;
     }
References G3D::Map2D< Storage, Compute >::w.
Referenced by G3D::Map2D< Storage, Compute >::set().
wrapMode()
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> WrapMode G3D::Map2D< Storage, Compute >::wrapMode () const inline
Definition at line 666 of file Map2D.h.
{
         return _wrapMode;
     }
References G3D::Map2D< Storage, Compute >::_wrapMode.
Member Data Documentation
_wrapMode
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> WrapMode G3D::Map2D< Storage, Compute >::_wrapMode protected
Definition at line 196 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::bilinear(), G3D::Map2D< Storage, Compute >::get(), G3D::Map2D< Storage, Compute >::nearest(), G3D::Map2D< Storage, Compute >::set(), G3D::Map2D< Storage, Compute >::setWrapMode(), and G3D::Map2D< Storage, Compute >::wrapMode().
data
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Array<Storage> G3D::Map2D< Storage, Compute >::data protected
Definition at line 202 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::getArray().
h
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> uint32 G3D::Map2D< Storage, Compute >::h protected
Height, in pixels.
Definition at line 194 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::average(), G3D::Map2D< Storage, Compute >::create(), G3D::Map2D< Storage, Compute >::crop(), G3D::Map2D< Storage, Compute >::fastGet(), G3D::Map2D< Storage, Compute >::fastSet(), G3D::Map2D< Storage, Compute >::flipHorizontal(), G3D::Map2D< Storage, Compute >::flipVertical(), G3D::Map2D< Storage, Compute >::get(), G3D::Map2D< Storage, Compute >::height(), G3D::Map2D< Storage, Compute >::inBounds(), G3D::Map2D< Storage, Compute >::Map2D(), G3D::Map2D< Storage, Compute >::rect2DBounds(), G3D::Map2D< Storage, Compute >::resize(), G3D::Map2D< Storage, Compute >::set(), G3D::Map2D< Storage, Compute >::size(), and G3D::Map2D< Storage, Compute >::slowGet().
m_changed
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> AtomicInt32 G3D::Map2D< Storage, Compute >::m_changed protected
0 if no mutating method has been invoked since the last call to setChanged();
Definition at line 200 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::changed(), and G3D::Map2D< Storage, Compute >::setChanged().
mutex
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> GMutex G3D::Map2D< Storage, Compute >::mutex
Although Map2D is not threadsafe (except for the setChanged() method), you can use this mutex to create your own threadsafe access to a Map2D. Not used by the default implementation.
Definition at line 296 of file Map2D.h.
w
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> uint32 G3D::Map2D< Storage, Compute >::w protected
Width, in pixels.
Definition at line 191 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::average(), G3D::Map2D< Storage, Compute >::create(), G3D::Map2D< Storage, Compute >::crop(), G3D::Map2D< Storage, Compute >::fastGet(), G3D::Map2D< Storage, Compute >::fastSet(), G3D::Map2D< Storage, Compute >::flipHorizontal(), G3D::Map2D< Storage, Compute >::flipVertical(), G3D::Map2D< Storage, Compute >::get(), G3D::Map2D< Storage, Compute >::inBounds(), G3D::Map2D< Storage, Compute >::Map2D(), G3D::Map2D< Storage, Compute >::rect2DBounds(), G3D::Map2D< Storage, Compute >::resize(), G3D::Map2D< Storage, Compute >::set(), G3D::Map2D< Storage, Compute >::size(), G3D::Map2D< Storage, Compute >::slowGet(), and G3D::Map2D< Storage, Compute >::width().
ZERO
template<typename Storage , typename Compute = typename G3D::_internal::_GetComputeType<Storage>::Type> Storage G3D::Map2D< Storage, Compute >::ZERO protected
Definition at line 188 of file Map2D.h.
Referenced by G3D::Map2D< Storage, Compute >::average(), G3D::Map2D< Storage, Compute >::bicubic(), G3D::Map2D< Storage, Compute >::get(), G3D::Map2D< Storage, Compute >::Map2D(), and G3D::Map2D< Storage, Compute >::slowGet().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Map2D.h