Azerotcore-wotlk: G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node Class Reference
G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node Class Reference
#include <PointKDTree.h>
Public Member Functions
Node ()
Node (const Node &other)
Node (const Array< Handle > &pt)
~Node ()
bool isLeaf () const
void getHandles (Array< Handle > &handleArray) const
void verifyNode (const Vector3 &lo, const Vector3 &hi)
Node * findDeepestContainingNode (const Vector3 &point)
void getIntersectingMembers (const AABox &sphereBounds, const Sphere &sphere, Array< T > &members) const
void getIntersectingMembers (const AABox &box, const Sphere &sphere, Array< T > &members, bool useSphere) const
void assignSplitBounds (const AABox &myBounds)
Static Public Member Functions
static void serializeStructure (const Node *n, BinaryOutput &bo)
static Node * deserializeStructure (BinaryInput &bi)
Public Attributes
AABox splitBounds
Vector3::Axis splitAxis
float splitLocation
Node * child [2]
Array< Handle > valueArray
Detailed Description
template<class T, class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>>
class G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node
Definition at line 149 of file PointKDTree.h.
Constructor & Destructor Documentation
Node() [1/3]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node () inline
Creates node with NULL children
Definition at line 176 of file PointKDTree.h.
                {
             splitAxis     = Vector3::X_AXIS;
             splitLocation = 0;
             splitBounds   = AABox(-Vector3::inf(), Vector3::inf());
             for (int i = 0; i < 2; ++i) {
                 child[i] = NULL;
             }
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::Vector3::inf(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, and G3D::Vector3::X_AXIS.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure().
Node() [2/3]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node (const Node & other) inline
Doesn't clone children.
Definition at line 188 of file PointKDTree.h.
                                 : valueArray(other.valueArray) {
             splitAxis       = other.splitAxis;
             splitLocation   = other.splitLocation;
             splitBounds     = other.splitBounds;
             for (int i = 0; i < 2; ++i) {
                 child[i] = NULL;
             }
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation.
Node() [3/3]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node (const Array< Handle > & pt) inline
Copies the specified subarray of pt into point, NULLs the children. Assumes a second pass will set splitBounds.
Definition at line 199 of file PointKDTree.h.
{
             splitAxis     = Vector3::X_AXIS;
             splitLocation = 0;
             for (int i = 0; i < 2; ++i) {
                 child[i] = NULL;
             }
             valueArray = pt;
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray, and G3D::Vector3::X_AXIS.
~Node()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::~Node () inline
Deletes the children (but not the values)
Definition at line 210 of file PointKDTree.h.
                 {
             for (int i = 0; i < 2; ++i) {
                 delete child[i];
             }
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child.
Member Function Documentation
assignSplitBounds()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds (const AABox & myBounds) inline
Recurse through the tree, assigning splitBounds fields.
Definition at line 397 of file PointKDTree.h.
{
             splitBounds = myBounds;
 #           ifdef G3D_DEBUG
                 if (child[0] || child[1]) {
                     debugAssert(splitBounds.high()[splitAxis] > splitLocation);
                     debugAssert(splitBounds.low()[splitAxis] < splitLocation);
                 }
 #           endif
             AABox childBounds[2];
             myBounds.split(splitAxis, splitLocation, childBounds[0], childBounds[1]);
             for (int c = 0; c < 2; ++c) {
                 if (child[c]) {
                     child[c]->assignSplitBounds(childBounds[c]);
                 }
             }
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), mpq::c, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, debugAssert, G3D::AABox::high(), G3D::AABox::low(), G3D::AABox::split(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance().
deserializeStructure()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> static Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure (BinaryInput & bi) inline static
Clears the member table
Definition at line 291 of file PointKDTree.h.
{
             if (bi.readUInt8() == 0) {
                 return NULL;
             } else {
                 Node* n = new Node();
                 n->splitBounds.deserialize(bi);
                 deserialize(n->splitAxis, bi);
                 n->splitLocation = bi.readFloat32();
                 for (int c = 0; c < 2; ++c) {
                     n->child[c] = deserializeStructure(bi);
                 }
                 return n;
             }
         }
References mpq::c, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::AABox::deserialize(), G3D::deserialize(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), NULL, G3D::BinaryInput::readFloat32(), G3D::BinaryInput::readUInt8(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::deserializeStructure().
findDeepestContainingNode()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode (const Vector3 & point) inline
Returns the deepest node that completely contains bounds.
Definition at line 307 of file PointKDTree.h.
{
             // See which side of the splitting plane the bounds are on
             if (point[splitAxis] < splitLocation) {
                 // Point is on the low side.  Recurse into the child
                 // if it exists.
                 if (child[0] != NULL) {
                     return child[0]->findDeepestContainingNode(point);
                 }
             } else if (point[splitAxis] > splitLocation) {
                 // Point is on the high side, recurse into the child
                 // if it exists.
                 if (child[1] != NULL) {
                     return child[1]->findDeepestContainingNode(point);
                 }
             }
             // There was no containing child, so this node is the
             // deepest containing node.
             return this;
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert().
getHandles()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles (Array< Handle > & handleArray) const inline
Recursively appends all handles and children's handles to the array.
Definition at line 227 of file PointKDTree.h.
{
             handleArray.append(valueArray);
             for (int i = 0; i < 2; ++i) {
                 if (child[i] != NULL) {
                     child[i]->getHandles(handleArray);
                 }
             }
         }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles(), NULL, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles().
getIntersectingMembers() [1/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers (const AABox & box, const Sphere & sphere, Array< T > & members, bool useSphere) const inline
Appends all members that intersect the box. If useSphere is true, members are tested against the sphere instead.
Implemented using both box and sphere tests to simplify the implementation of a future beginSphereInteresection iterator using the same underlying BoxIterator class.
Definition at line 369 of file PointKDTree.h.
{
             // Test all values at this node
             for (int v = 0; v < valueArray.size(); ++v) {
                 if ((useSphere && sphere.contains(valueArray[v].position())) ||
                     (! useSphere && box.contains(valueArray[v].position()))) {
                     members.append(valueArray[v].value);
                 }
             }
             // If the left child overlaps the box, recurse into it
             if ((child[0] != NULL) && (box.low()[splitAxis] < splitLocation)) {
                 child[0]->getIntersectingMembers(box, sphere, members, useSphere);
             }
             // If the right child overlaps the box, recurse into it
             if ((child[1] != NULL) && (box.high()[splitAxis] > splitLocation)) {
                 child[1]->getIntersectingMembers(box, sphere, members, useSphere);
             }
         }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::AABox::contains(), G3D::Sphere::contains(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::AABox::high(), G3D::AABox::low(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
getIntersectingMembers() [2/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers (const AABox & sphereBounds, const Sphere & sphere, Array< T > & members) const inline
Appends all members that intersect the box. If useSphere is true, members are tested against the sphere instead.
Definition at line 331 of file PointKDTree.h.
{
             // Test all values at this node.  Extract the
             // underlying C array for speed
             const int N = valueArray.size();
             const Handle* handleArray = valueArray.getCArray();
             const float r2 = square(sphere.radius);
             // Copy the sphere center so that it is on the stack near the radius
             const Vector3 center = sphere.center;
             for (int v = 0; v < N; ++v) {
                 if ((center - handleArray[v].position()).squaredLength() <= r2) {
                     members.append(handleArray[v].value);
                 }
             }
             // If the left child overlaps the box, recurse into it
             if (child[0] && (sphereBounds.low()[splitAxis] < splitLocation)) {
                 child[0]->getIntersectingMembers(sphereBounds, sphere, members);
             }
             // If the right child overlaps the box, recurse into it
             if (child[1] && (sphereBounds.high()[splitAxis] > splitLocation)) {
                 child[1]->getIntersectingMembers(sphereBounds, sphere, members);
             }
         }
References G3D::Array< T, MIN_ELEMENTS >::append(), align::center, G3D::Sphere::center, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::AABox::high(), G3D::AABox::low(), G3D::Sphere::radius, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, G3D::square(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers().
isLeaf()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::isLeaf () const inline
Returns true if this node is a leaf (no children)
Definition at line 218 of file PointKDTree.h.
{
             return (child[0] == NULL) && (child[1] == NULL);
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, and NULL.
serializeStructure()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> static void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure (const Node * n, BinaryOutput & bo) inline static
Stores the locations of the splitting planes (the structure but not the content) so that the tree can be quickly rebuilt from a previous configuration without calling balance.
Definition at line 276 of file PointKDTree.h.
{
             if (n == NULL) {
                 bo.writeUInt8(0);
             } else {
                 bo.writeUInt8(1);
                 n->splitBounds.serialize(bo);
                 serialize(n->splitAxis, bo);
                 bo.writeFloat32(n->splitLocation);
                 for (int c = 0; c < 2; ++c) {
                     serializeStructure(n->child[c], bo);
                 }
             }
         }
References mpq::c, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, NULL, G3D::AABox::serialize(), G3D::serialize(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, G3D::BinaryOutput::writeFloat32(), and G3D::BinaryOutput::writeUInt8().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::serializeStructure().
verifyNode()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode (const Vector3 & lo, const Vector3 & hi) inline
Definition at line 237 of file PointKDTree.h.
{
             //        debugPrintf("Verifying: split %d @ %f [%f, %f, %f], [%f, %f, %f]\n",
             //                splitAxis, splitLocation, lo.x, lo.y, lo.z, hi.x, hi.y, hi.z);
             debugAssert(lo == splitBounds.low());
             debugAssert(hi == splitBounds.high());
 #           ifdef G3D_DEBUG
             for (int i = 0; i < valueArray.length(); ++i) {
                 const Vector3& b = valueArray[i].position();
                 debugAssert(splitBounds.contains(b));
             }
 #           endif
             if (child[0] || child[1]) {
                 debugAssert(lo[splitAxis] < splitLocation);
                 debugAssert(hi[splitAxis] > splitLocation);
             }
             Vector3 newLo = lo;
             newLo[splitAxis] = splitLocation;
             Vector3 newHi = hi;
             newHi[splitAxis] = splitLocation;
             if (child[0] != NULL) {
                 child[0]->verifyNode(lo, newHi);
             }
             if (child[1] != NULL) {
                 child[1]->verifyNode(newLo, hi);
             }
         }
References b, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child, G3D::AABox::contains(), debugAssert, G3D::AABox::high(), G3D::AABox::low(), NULL, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation, G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray, and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
Member Data Documentation
child
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Node* G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::child[2]
child[0] contains all values strictly smaller than splitLocation along splitAxis.
child[1] contains all values strictly larger.
Both may be NULL if there are not enough values to bother recursing.
Definition at line 170 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::isLeaf(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::~Node().
splitAxis
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Vector3::Axis G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitAxis
Definition at line 156 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
splitBounds
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> AABox G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitBounds
Spatial bounds on all values at this node and its children, based purely on the parent's splitting planes. May be infinite
Definition at line 154 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
splitLocation
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> float G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::splitLocation
Location along the specified axis
Definition at line 159 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
valueArray
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Array<Handle> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::valueArray
Values if this is a leaf node).
Definition at line 173 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator*(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointKDTree.h