Azerotcore-wotlk: Acore::ChatCommands::Hyperlink< linktag > Struct Template Reference
Acore::ChatCommands::Hyperlink< linktag > Struct Template Reference
#include <ChatCommandTags.h>
Public Types
using value_type = typename linktag::value_type
using storage_type = advstd::remove_cvref_t< value_type >
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
operator value_type () const
value_type operator* () const
storage_type const * operator-> () const
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args)
Private Attributes
storage_type val
Detailed Description
template<typename linktag>
struct Acore::ChatCommands::Hyperlink< linktag >
Definition at line 204 of file ChatCommandTags.h.
Member Typedef Documentation
storage_type
template<typename linktag > using Acore::ChatCommands::Hyperlink< linktag >::storage_type = advstd::remove_cvref_t<value_type>
Definition at line 207 of file ChatCommandTags.h.
value_type
template<typename linktag > using Acore::ChatCommands::Hyperlink< linktag >::value_type = typename linktag::value_type
Definition at line 206 of file ChatCommandTags.h.
Member Function Documentation
operator value_type()
template<typename linktag > Acore::ChatCommands::Hyperlink< linktag >::operator value_type () const inline
Definition at line 209 of file ChatCommandTags.h.
 { return val; }
References Acore::ChatCommands::Hyperlink< linktag >::val.
operator*()
template<typename linktag > value_type Acore::ChatCommands::Hyperlink< linktag >::operator* () const inline
Definition at line 210 of file ChatCommandTags.h.
 { return val; }
References Acore::ChatCommands::Hyperlink< linktag >::val.
operator->()
template<typename linktag > storage_type const* Acore::ChatCommands::Hyperlink< linktag >::operator-> () const inline
Definition at line 211 of file ChatCommandTags.h.
 { return &val; }
References Acore::ChatCommands::Hyperlink< linktag >::val.
TryConsume()
template<typename linktag > ChatCommandResult Acore::ChatCommands::Hyperlink< linktag >::TryConsume (ChatHandler const * handler, std::string_view args) inline
Definition at line 213 of file ChatCommandTags.h.
         {
             Acore::Hyperlinks::HyperlinkInfo info = Acore::Hyperlinks::ParseSingleHyperlink(args);
             // invalid hyperlinks cannot be consumed
             if (!info)
                 return std::nullopt;
             // check if we got the right tag
             if (info.tag != linktag::tag())
                 return std::nullopt;
             // store value
             if (!linktag::StoreTo(val, info.data))
                 return Acore::Impl::ChatCommands::GetAcoreString(handler, LANG_CMDPARSER_LINKDATA_INVALID);
             // finally, skip any potential delimiters
             auto [token, next] = Acore::Impl::ChatCommands::tokenize(info.tail);
             if (token.empty()) /* empty token = first character is delimiter, skip past it */
                 return next;
             else
                 return info.tail;
         }
References Acore::Hyperlinks::HyperlinkInfo::data, Acore::Impl::ChatCommands::GetAcoreString(), LANG_CMDPARSER_LINKDATA_INVALID, Acore::Hyperlinks::ParseSingleHyperlink(), Acore::Hyperlinks::HyperlinkInfo::tag, Acore::Hyperlinks::HyperlinkInfo::tail, Acore::Impl::ChatCommands::tokenize(), and Acore::ChatCommands::Hyperlink< linktag >::val.
Member Data Documentation
val
template<typename linktag > storage_type Acore::ChatCommands::Hyperlink< linktag >::val private
Definition at line 237 of file ChatCommandTags.h.
Referenced by Acore::ChatCommands::Hyperlink< linktag >::operator value_type(), Acore::ChatCommands::Hyperlink< linktag >::operator*(), Acore::ChatCommands::Hyperlink< linktag >::operator->(), and Acore::ChatCommands::Hyperlink< linktag >::TryConsume().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandTags.h