Azerotcore-wotlk: ChatHandler Class Reference
ChatHandler Class Reference
#include <Chat.h>
Public Member Functions
ChatHandler (WorldSession *session)
virtual ~ChatHandler ()
virtual char const * GetAcoreString (uint32 entry) const
virtual void SendSysMessage (std::string_view str, bool escapeCharacters=false)
void SendSysMessage (uint32 entry)
template<typename... Args>
void PSendSysMessage (char const *fmt, Args &&... args)
template<typename... Args>
void PSendSysMessage (uint32 entry, Args &&... args)
template<typename... Args>
std::string PGetParseString (uint32 entry, Args &&... args) const
bool _ParseCommands (std::string_view text)
virtual bool ParseCommands (std::string_view text)
void SendGlobalSysMessage (const char *str)
virtual bool IsHumanReadable () const
virtual std::string GetNameLink () const
virtual bool needReportToTarget (Player *chr) const
virtual LocaleConstant GetSessionDbcLocale () const
virtual int GetSessionDbLocaleIndex () const
bool HasLowerSecurity (Player *target, ObjectGuid guid=ObjectGuid::Empty, bool strong=false)
bool HasLowerSecurityAccount (WorldSession *target, uint32 account, bool strong=false)
void SendGlobalGMSysMessage (const char *str)
Player * getSelectedPlayer ()
Creature * getSelectedCreature ()
Unit * getSelectedUnit ()
WorldObject * getSelectedObject ()
Player * getSelectedPlayerOrSelf ()
char * extractKeyFromLink (char *text, char const *linkType, char **something1=nullptr)
char * extractKeyFromLink (char *text, char const *const *linkTypes, int *found_idx, char **something1=nullptr)
char * extractQuotedArg (char *args)
uint32 extractSpellIdFromLink (char *text)
ObjectGuid::LowType extractLowGuidFromLink (char *text, HighGuid &guidHigh)
bool GetPlayerGroupAndGUIDByName (const char *cname, Player *&player, Group *&group, ObjectGuid &guid, bool offline=false)
std::string extractPlayerNameFromLink (char *text)
bool extractPlayerTarget (char *args, Player **player, ObjectGuid *player_guid=nullptr, std::string *player_name=nullptr)
std::string playerLink (std::string const &name) const
std::string GetNameLink (Player *chr) const
GameObject * GetNearbyGameObject ()
GameObject * GetObjectFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
Creature * GetCreatureFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
bool HasSentErrorMessage () const
void SetSentErrorMessage (bool val)
bool IsConsole () const
Player * GetPlayer () const
WorldSession * GetSession ()
bool IsAvailable (uint32 securityLevel) const
Static Public Member Functions
static size_t BuildChatPacket (WorldPacket &data, ChatMsg chatType, Language language, ObjectGuid senderGUID, ObjectGuid receiverGUID, std::string_view message, uint8 chatTag, std::string const &senderName="", std::string const &receiverName="", uint32 achievementId=0, bool gmMessage=false, std::string const &channelName="")
static size_t BuildChatPacket (WorldPacket &data, ChatMsg chatType, Language language, WorldObject const *sender, WorldObject const *receiver, std::string_view message, uint32 achievementId=0, std::string const &channelName="", LocaleConstant locale=DEFAULT_LOCALE)
static char * LineFromMessage (char *&pos)
Protected Member Functions
ChatHandler ()
Private Attributes
WorldSession * m_session
bool sentErrorMessage
Detailed Description
Definition at line 37 of file Chat.h.
Constructor & Destructor Documentation
ChatHandler() [1/2]
ChatHandler::ChatHandler (WorldSession * session) inline explicit
Definition at line 40 of file Chat.h.
 : m_session(session), sentErrorMessage(false) {}
~ChatHandler()
virtual ChatHandler::~ChatHandler () inline virtual
Definition at line 41 of file Chat.h.
 { }
ChatHandler() [2/2]
ChatHandler::ChatHandler () inline explicit protected
Definition at line 125 of file Chat.h.
 : m_session(nullptr), sentErrorMessage(false) {}      // for CLI subclass
Member Function Documentation
_ParseCommands()
bool ChatHandler::_ParseCommands (std::string_view text)
Definition at line 159 of file Chat.cpp.
 {
     if (Acore::ChatCommands::TryExecuteCommand(*this, text))
         return true;
     // Pretend commands don't exist for regular players
     if (m_session && AccountMgr::IsPlayerAccount(m_session->GetSecurity()) && !sWorld->getBoolConfig(CONFIG_ALLOW_PLAYER_COMMANDS))
         return false;
     // Send error message for GMs
     PSendSysMessage(LANG_CMD_INVALID, STRING_VIEW_FMT_ARG(text));
     SetSentErrorMessage(true);
     return true;
 }
References CONFIG_ALLOW_PLAYER_COMMANDS, WorldSession::GetSecurity(), AccountMgr::IsPlayerAccount(), LANG_CMD_INVALID, m_session, PSendSysMessage(), SetSentErrorMessage(), STRING_VIEW_FMT_ARG, sWorld, and Acore::ChatCommands::TryExecuteCommand().
Referenced by CliHandler::ParseCommands(), and ParseCommands().
BuildChatPacket() [1/2]
size_t ChatHandler::BuildChatPacket (WorldPacket & data, ChatMsg chatType, Language language, ObjectGuid senderGUID, ObjectGuid receiverGUID, std::string_view message, uint8 chatTag, std::string const & senderName = "", std::string const & receiverName = "", uint32 achievementId = 0, bool gmMessage = false, std::string const & channelName = "") static
Definition at line 197 of file Chat.cpp.
 {
     size_t receiverGUIDPos = 0;
     data.Initialize(!gmMessage ? SMSG_MESSAGECHAT : SMSG_GM_MESSAGECHAT);
     data << uint8(chatType);
     data << int32(language);
     data << senderGUID;
     data << uint32(0);  // some flags
     switch (chatType)
     {
         case CHAT_MSG_MONSTER_SAY:
         case CHAT_MSG_MONSTER_PARTY:
         case CHAT_MSG_MONSTER_YELL:
         case CHAT_MSG_MONSTER_WHISPER:
         case CHAT_MSG_MONSTER_EMOTE:
         case CHAT_MSG_RAID_BOSS_EMOTE:
         case CHAT_MSG_RAID_BOSS_WHISPER:
         case CHAT_MSG_BATTLENET:
             data << uint32(senderName.length() + 1);
             data << senderName;
             receiverGUIDPos = data.wpos();
             data << receiverGUID;
             if (receiverGUID && !receiverGUID.IsPlayer() && !receiverGUID.IsPet())
             {
                 data << uint32(receiverName.length() + 1);
                 data << receiverName;
             }
             break;
         case CHAT_MSG_WHISPER_FOREIGN:
             data << uint32(senderName.length() + 1);
             data << senderName;
             receiverGUIDPos = data.wpos();
             data << receiverGUID;
             break;
         case CHAT_MSG_BG_SYSTEM_NEUTRAL:
         case CHAT_MSG_BG_SYSTEM_ALLIANCE:
         case CHAT_MSG_BG_SYSTEM_HORDE:
             receiverGUIDPos = data.wpos();
             data << receiverGUID;
             if (receiverGUID && !receiverGUID.IsPlayer())
             {
                 data << uint32(receiverName.length() + 1);
                 data << receiverName;
             }
             break;
         case CHAT_MSG_ACHIEVEMENT:
         case CHAT_MSG_GUILD_ACHIEVEMENT:
             receiverGUIDPos = data.wpos();
             data << receiverGUID;
             break;
         default:
             if (gmMessage)
             {
                 data << uint32(senderName.length() + 1);
                 data << senderName;
             }
             if (chatType == CHAT_MSG_CHANNEL)
             {
                 ASSERT(channelName.length() > 0);
                 data << channelName;
             }
             receiverGUIDPos = data.wpos();
             data << receiverGUID;
             break;
     }
     data << uint32(message.length() + 1);
     data << message;
     data << uint8(chatTag);
     if (chatType == CHAT_MSG_ACHIEVEMENT || chatType == CHAT_MSG_GUILD_ACHIEVEMENT)
         data << uint32(achievementId);
     return receiverGUIDPos;
 }
References ASSERT, CHAT_MSG_ACHIEVEMENT, CHAT_MSG_BATTLENET, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, CHAT_MSG_BG_SYSTEM_NEUTRAL, CHAT_MSG_CHANNEL, CHAT_MSG_GUILD_ACHIEVEMENT, CHAT_MSG_MONSTER_EMOTE, CHAT_MSG_MONSTER_PARTY, CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_WHISPER, CHAT_MSG_MONSTER_YELL, CHAT_MSG_RAID_BOSS_EMOTE, CHAT_MSG_RAID_BOSS_WHISPER, CHAT_MSG_WHISPER_FOREIGN, WorldPacket::Initialize(), message(), SMSG_GM_MESSAGECHAT, SMSG_MESSAGECHAT, and ByteBuffer::wpos().
Referenced by Guild::BroadcastToGuild(), BuildChatPacket(), Acore::BattlegroundChatBuilder::do_helper(), Acore::WorldWorldTextBuilder::do_helper(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), WorldSession::HandleChatIgnoredOpcode(), debug_commandscript::HandleDebugSendChatMsgCommand(), WorldSession::HandleMessagechatOpcode(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), Acore::Battleground2ChatBuilder::operator()(), Acore::BroadcastTextBuilder::operator()(), Acore::CustomChatTextBuilder::operator()(), Acore::AcoreStringChatBuilder::operator()(), CreatureTextBuilder::operator()(), PlayerTextBuilder::operator()(), boss_flame_leviathan::boss_flame_leviathanAI::RadioSay(), npc_brann_radio::npc_brann_radioAI::Say(), Channel::Say(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), Player::Say(), SendGlobalGMSysMessage(), SendGlobalSysMessage(), World::SendGlobalText(), SendSysMessage(), Battleground::SendWarningToAll(), World::SendZoneText(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), boss_ick::boss_ickAI::SpellHitTarget(), Player::TextEmote(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), boss_garfrost::boss_garfrostAI::UpdateAI(), Player::Whisper(), Unit::Whisper(), Player::Yell(), and Battleground::YellToAll().
BuildChatPacket() [2/2]
size_t ChatHandler::BuildChatPacket (WorldPacket & data, ChatMsg chatType, Language language, WorldObject const * sender, WorldObject const * receiver, std::string_view message, uint32 achievementId = 0, std::string const & channelName = "", LocaleConstant locale = DEFAULT_LOCALE) static
Definition at line 277 of file Chat.cpp.
 {
     ObjectGuid senderGUID;
     std::string senderName = "";
     uint8 chatTag = 0;
     bool gmMessage = false;
     ObjectGuid receiverGUID;
     std::string receiverName = "";
     if (sender)
     {
         senderGUID = sender->GetGUID();
         senderName = sender->GetNameForLocaleIdx(locale);
         if (Player const* playerSender = sender->ToPlayer())
         {
             chatTag = playerSender->GetChatTag();
             gmMessage = playerSender->IsGameMaster();
         }
     }
     if (receiver)
     {
         receiverGUID = receiver->GetGUID();
         receiverName = receiver->GetNameForLocaleIdx(locale);
     }
     return BuildChatPacket(data, chatType, language, senderGUID, receiverGUID, message, chatTag, senderName, receiverName, achievementId, gmMessage, channelName);
 }
References BuildChatPacket(), Object::GetGUID(), WorldObject::GetNameForLocaleIdx(), message(), and Object::ToPlayer().
extractKeyFromLink() [1/2]
char * ChatHandler::extractKeyFromLink (char * text, char const *const * linkTypes, int * found_idx, char ** something1 = nullptr)
Definition at line 416 of file Chat.cpp.
 {
     // skip empty
     if (!text)
         return nullptr;
     // skip spaces
     while (*text == ' ' || *text == '\t' || *text == '\b')
         ++text;
     if (!*text)
         return nullptr;
     // return non link case
     if (text[0] != '|')
         return strtok(text, " ");
     // [name] Shift-click form |color|linkType:key|h[name]|h|r
     // or
     // [name] Shift-click form |color|linkType:key:something1:...:somethingN|h[name]|h|r
     // or
     // [name] Shift-click form |linkType:key|h[name]|h|r
     char* tail;
     if (text[1] == 'c')
     {
         char* check = strtok(text, "|");                    // skip color
         if (!check)
             return nullptr;                                    // end of data
         tail = strtok(nullptr, "");                            // tail
     }
     else
         tail = text + 1;                                    // skip first |
     char* cLinkType = strtok(tail, ":");                    // linktype
     if (!cLinkType)
         return nullptr;                                        // end of data
     for (int i = 0; linkTypes[i]; ++i)
     {
         if (strcmp(cLinkType, linkTypes[i]) == 0)
         {
             char* cKeys = strtok(nullptr, "|");                // extract keys and values
             char* cKeysTail = strtok(nullptr, "");
             char* cKey = strtok(cKeys, ":|");               // extract key
             if (something1)
                 *something1 = strtok(nullptr, ":|");           // extract something
             strtok(cKeysTail, "]");                         // restart scan tail and skip name with possible spaces
             strtok(nullptr, " ");                              // skip link tail (to allow continue strtok(nullptr, s) use after return from function
             if (found_idx)
                 *found_idx = i;
             return cKey;
         }
     }
     strtok(nullptr, " ");                                      // skip link tail (to allow continue strtok(nullptr, s) use after return from function
     SendSysMessage(LANG_WRONG_LINK_TYPE);
     return nullptr;
 }
References LANG_WRONG_LINK_TYPE, and SendSysMessage().
extractKeyFromLink() [2/2]
char * ChatHandler::extractKeyFromLink (char * text, char const * linkType, char ** something1 = nullptr)
Definition at line 368 of file Chat.cpp.
 {
     // skip empty
     if (!text)
         return nullptr;
     // skip spaces
     while (*text == ' ' || *text == '\t' || *text == '\b')
         ++text;
     if (!*text)
         return nullptr;
     // return non link case
     if (text[0] != '|')
         return strtok(text, " ");
     // [name] Shift-click form |color|linkType:key|h[name]|h|r
     // or
     // [name] Shift-click form |color|linkType:key:something1:...:somethingN|h[name]|h|r
     char* check = strtok(text, "|");                        // skip color
     if (!check)
         return nullptr;                                        // end of data
     char* cLinkType = strtok(nullptr, ":");                    // linktype
     if (!cLinkType)
         return nullptr;                                        // end of data
     if (strcmp(cLinkType, linkType) != 0)
     {
         strtok(nullptr, " ");                                  // skip link tail (to allow continue strtok(nullptr, s) use after retturn from function
         SendSysMessage(LANG_WRONG_LINK_TYPE);
         return nullptr;
     }
     char* cKeys = strtok(nullptr, "|");                        // extract keys and values
     char* cKeysTail = strtok(nullptr, "");
     char* cKey = strtok(cKeys, ":|");                       // extract key
     if (something1)
         *something1 = strtok(nullptr, ":|");                   // extract something
     strtok(cKeysTail, "]");                                 // restart scan tail and skip name with possible spaces
     strtok(nullptr, " ");                                      // skip link tail (to allow continue strtok(nullptr, s) use after return from function
     return cKey;
 }
References LANG_WRONG_LINK_TYPE, and SendSysMessage().
Referenced by extractLowGuidFromLink(), extractPlayerNameFromLink(), extractSpellIdFromLink(), misc_commandscript::HandleAddItemCommand(), misc_commandscript::HandleAddItemSetCommand(), modify_commandscript::HandleModifyFactionCommand(), modify_commandscript::HandleModifyRepCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), and misc_commandscript::HandleSetSkillCommand().
extractLowGuidFromLink()
ObjectGuid::LowType ChatHandler::extractLowGuidFromLink (char * text, HighGuid & guidHigh)
Definition at line 612 of file Chat.cpp.
 {
     int type = 0;
     // |color|Hcreature:creature_guid|h[name]|h|r
     // |color|Hgameobject:go_guid|h[name]|h|r
     // |color|Hplayer:name|h[name]|h|r
     char* idS = extractKeyFromLink(text, guidKeys, &type);
     if (!idS)
         return 0;
     switch (type)
     {
         case SPELL_LINK_PLAYER:
             {
                 guidHigh = HighGuid::Player;
                 std::string name = idS;
                 if (!normalizePlayerName(name))
                     return 0;
                 if (Player* player = ObjectAccessor::FindPlayerByName(name, false))
                     return player->GetGUID().GetCounter();
                 if (ObjectGuid guid = sObjectMgr->GetPlayerGUIDByName(name))
                     return guid.GetCounter();
                 return 0;
             }
         case SPELL_LINK_CREATURE:
             {
                 guidHigh = HighGuid::Unit;
                 ObjectGuid::LowType lowguid = (uint32)atol(idS);
                 if (sObjectMgr->GetCreatureData(lowguid))
                     return lowguid;
                 else
                     return 0;
             }
         case SPELL_LINK_GAMEOBJECT:
             {
                 guidHigh = HighGuid::GameObject;
                 ObjectGuid::LowType lowguid = (uint32)atol(idS);
                 if (sObjectMgr->GetGOData(lowguid))
                     return lowguid;
                 else
                     return 0;
             }
     }
     // unknown type?
     return 0;
 }
References extractKeyFromLink(), ObjectAccessor::FindPlayerByName(), GameObject, guidKeys, normalizePlayerName(), Player, sObjectMgr, SPELL_LINK_CREATURE, SPELL_LINK_GAMEOBJECT, SPELL_LINK_PLAYER, and Unit.
Referenced by misc_commandscript::HandleGetDistanceCommand(), and misc_commandscript::HandleGPSCommand().
extractPlayerNameFromLink()
std::string ChatHandler::extractPlayerNameFromLink (char * text)
Definition at line 669 of file Chat.cpp.
 {
     // |color|Hplayer:name|h[name]|h|r
     char* name_str = extractKeyFromLink(text, "Hplayer");
     if (!name_str)
         return "";
     std::string name = name_str;
     if (!normalizePlayerName(name))
         return "";
     return name;
 }
References extractKeyFromLink(), and normalizePlayerName().
Referenced by extractPlayerTarget().
extractPlayerTarget()
bool ChatHandler::extractPlayerTarget (char * args, Player ** player, ObjectGuid * player_guid = nullptr, std::string * player_name = nullptr)
Definition at line 683 of file Chat.cpp.
 {
     if (args && *args)
     {
         std::string name = extractPlayerNameFromLink(args);
         if (name.empty())
         {
             SendSysMessage(LANG_PLAYER_NOT_FOUND);
             SetSentErrorMessage(true);
             return false;
         }
         Player* pl = ObjectAccessor::FindPlayerByName(name, false);
         // if allowed player pointer
         if (player)
             *player = pl;
         // if need guid value from DB (in name case for check player existence)
         ObjectGuid guid = !pl && (player_guid || player_name) ? sObjectMgr->GetPlayerGUIDByName(name) : ObjectGuid::Empty;
         // if allowed player guid (if no then only online players allowed)
         if (player_guid)
             *player_guid = pl ? pl->GetGUID() : guid;
         if (player_name)
             *player_name = pl || guid ? name : "";
     }
     else
     {
         // populate strtok buffer to prevent crashes
         static char dummy[1] = "";
         strtok(dummy, "");
         Player* pl = getSelectedPlayer();
         // if allowed player pointer
         if (player)
             *player = pl;
         // if allowed player guid (if no then only online players allowed)
         if (player_guid)
             *player_guid = pl ? pl->GetGUID() : ObjectGuid::Empty;
         if (player_name)
             *player_name = pl ? pl->GetName() : "";
     }
     // some from req. data must be provided (note: name is empty if player not exist)
     if ((!player || !*player) && (!player_guid || !*player_guid) && (!player_name || player_name->empty()))
     {
         SendSysMessage(LANG_PLAYER_NOT_FOUND);
         SetSentErrorMessage(true);
         return false;
     }
     return true;
 }
References ObjectGuid::Empty, extractPlayerNameFromLink(), ObjectAccessor::FindPlayerByName(), Object::GetGUID(), WorldObject::GetName(), getSelectedPlayer(), LANG_PLAYER_NOT_FOUND, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by misc_commandscript::HandleAppearCommand(), misc_commandscript::HandleCombatStopCommand(), misc_commandscript::HandleGearRepairCommand(), misc_commandscript::HandleGroupListCommand(), misc_commandscript::HandleGroupSummonCommand(), guild_commandscript::HandleGuildCreateCommand(), guild_commandscript::HandleGuildInviteCommand(), guild_commandscript::HandleGuildUninviteCommand(), misc_commandscript::HandleKickPlayerCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandleRecallCommand(), reset_commandscript::HandleResetAchievementsCommand(), reset_commandscript::HandleResetHonorCommand(), reset_commandscript::HandleResetLevelCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetStatsCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleReviveCommand(), misc_commandscript::HandleSendItemsCommand(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMessageCommand(), misc_commandscript::HandleSendMoneyCommand(), misc_commandscript::HandleSummonCommand(), misc_commandscript::HandleUnmuteCommand(), and misc_commandscript::HandleUnstuckCommand().
extractQuotedArg()
char * ChatHandler::extractQuotedArg (char * args)
Definition at line 741 of file Chat.cpp.
 {
     if (!*args)
         return nullptr;
     if (*args == '"')
         return strtok(args + 1, "\"");
     else
     {
         // skip spaces
         while (*args == ' ')
         {
             args += 1;
             continue;
         }
         // return nullptr if we reached the end of the string
         if (!*args)
             return nullptr;
         // since we skipped all spaces, we expect another token now
         if (*args == '"')
         {
             // return an empty string if there are 2 "" in a row.
             // strtok doesn't handle this case
             if (*(args + 1) == '"')
             {
                 strtok(args, " ");
                 static char arg[1];
                 arg[0] = '\0';
                 return arg;
             }
             else
                 return strtok(args + 1, "\"");
         }
         else
             return nullptr;
     }
 }
Referenced by guild_commandscript::HandleGuildCreateCommand(), guild_commandscript::HandleGuildDeleteCommand(), guild_commandscript::HandleGuildInviteCommand(), misc_commandscript::HandleSendItemsCommand(), misc_commandscript::HandleSendMailCommand(), and misc_commandscript::HandleSendMoneyCommand().
extractSpellIdFromLink()
uint32 ChatHandler::extractSpellIdFromLink (char * text)
Definition at line 543 of file Chat.cpp.
 {
     // number or [name] Shift-click form |color|Henchant:recipe_spell_id|h[prof_name: recipe_name]|h|r
     // number or [name] Shift-click form |color|Hglyph:glyph_slot_id:glyph_prop_id|h[%s]|h|r
     // number or [name] Shift-click form |color|Hspell:spell_id|h[name]|h|r
     // number or [name] Shift-click form |color|Htalent:talent_id, rank|h[name]|h|r
     // number or [name] Shift-click form |color|Htrade:spell_id, skill_id, max_value, cur_value|h[name]|h|r
     int type = 0;
     char* param1_str = nullptr;
     char* idS = extractKeyFromLink(text, spellKeys, &type, &param1_str);
     if (!idS)
         return 0;
     uint32 id = (uint32)atol(idS);
     switch (type)
     {
         case SPELL_LINK_SPELL:
             return id;
         case SPELL_LINK_TALENT:
             {
                 // talent
                 TalentEntry const* talentEntry = sTalentStore.LookupEntry(id);
                 if (!talentEntry)
                     return 0;
                 int32 rank = param1_str ? (uint32)atol(param1_str) : 0;
                 if (rank >= MAX_TALENT_RANK)
                     return 0;
                 if (rank < 0)
                     rank = 0;
                 return talentEntry->RankID[rank];
             }
         case SPELL_LINK_ENCHANT:
         case SPELL_LINK_TRADE:
             return id;
         case SPELL_LINK_GLYPH:
             {
                 uint32 glyph_prop_id = param1_str ? (uint32)atol(param1_str) : 0;
                 GlyphPropertiesEntry const* glyphPropEntry = sGlyphPropertiesStore.LookupEntry(glyph_prop_id);
                 if (!glyphPropEntry)
                     return 0;
                 return glyphPropEntry->SpellId;
             }
     }
     // unknown type?
     return 0;
 }
References extractKeyFromLink(), MAX_TALENT_RANK, TalentEntry::RankID, sGlyphPropertiesStore, SPELL_LINK_ENCHANT, SPELL_LINK_GLYPH, SPELL_LINK_SPELL, SPELL_LINK_TALENT, SPELL_LINK_TRADE, GlyphPropertiesEntry::SpellId, spellKeys, and sTalentStore.
Referenced by misc_commandscript::HandleAuraCommand(), misc_commandscript::HandleCooldownCommand(), misc_commandscript::HandlePetLearnCommand(), misc_commandscript::HandlePetUnlearnCommand(), and misc_commandscript::HandleUnAuraCommand().
GetAcoreString()
char const * ChatHandler::GetAcoreString (uint32 entry) const virtual
Reimplemented in CliHandler.
Definition at line 47 of file Chat.cpp.
 {
     return m_session->GetAcoreString(entry);
 }
References WorldSession::GetAcoreString(), and m_session.
Referenced by tele_commandscript::DoNameTeleport(), Acore::Impl::ChatCommands::GetAcoreString(), message_commandscript::HandleAnnounceCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanInfoHelper(), ban_commandscript::HandleBanInfoIPCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), misc_commandscript::HandleCooldownCommand(), event_commandscript::HandleEventActiveListCommand(), event_commandscript::HandleEventInfoCommand(), message_commandscript::HandleGMNotifyCommand(), gm_commandscript::HandleGMVisibleCommand(), misc_commandscript::HandleKickPlayerCommand(), lookup_commandscript::HandleLookupEventCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupMapCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTitleCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyRepCommand(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandleNearGraveCommand(), message_commandscript::HandleNotifyCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandleSummonCommand(), message_commandscript::HandleWhispersCommand(), list_commandscript::ListAurasCommand(), and SendSysMessage().
GetCreatureFromPlayerMapByDbGuid()
Creature * ChatHandler::GetCreatureFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
Definition at line 493 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     // Select the first alive creature or a dead one if not found
     Creature* creature = nullptr;
     auto bounds = m_session->GetPlayer()->GetMap()->GetCreatureBySpawnIdStore().equal_range(lowguid);
     for (auto it = bounds.first; it != bounds.second; ++it)
     {
         creature = it->second;
         if (it->second->IsAlive())
             break;
     }
     return creature;
 }
References Map::GetCreatureBySpawnIdStore(), WorldObject::GetMap(), WorldSession::GetPlayer(), and m_session.
Referenced by misc_commandscript::HandleGetDistanceCommand(), misc_commandscript::HandleGPSCommand(), and npc_commandscript::HandleNpcSetMoveTypeCommand().
GetNameLink() [1/2]
virtual std::string ChatHandler::GetNameLink () const inline virtual
Reimplemented in CliHandler.
Definition at line 84 of file Chat.h.
 { return GetNameLink(m_session->GetPlayer()); }
References GetNameLink().
Referenced by modify_commandscript::CheckModifySpeed(), tele_commandscript::DoNameTeleport(), GetNameLink(), misc_commandscript::HandleAddItemCommand(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterLevel(), character_commandscript::HandleCharacterRenameCommand(), misc_commandscript::HandleCooldownCommand(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleGearRepairCommand(), gm_commandscript::HandleGMFlyCommand(), misc_commandscript::HandleGroupSummonCommand(), learn_commandscript::HandleLearnAllDefaultCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), modify_commandscript::HandleModifyArenaCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), misc_commandscript::HandleRecallCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleSendMessageCommand(), misc_commandscript::HandleSetSkillCommand(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), and modify_commandscript::NotifyModification().
GetNameLink() [2/2]
std::string ChatHandler::GetNameLink (Player * chr) const
Definition at line 797 of file Chat.cpp.
 {
     return playerLink(chr->GetName());
 }
References WorldObject::GetName(), and playerLink().
GetNearbyGameObject()
GameObject * ChatHandler::GetNearbyGameObject ()
Definition at line 480 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     Player* pl = m_session->GetPlayer();
     GameObject* obj = nullptr;
     Acore::NearestGameObjectCheck check(*pl);
     Acore::GameObjectLastSearcher<Acore::NearestGameObjectCheck> searcher(pl, obj, check);
     Cell::VisitGridObjects(pl, searcher, SIZE_OF_GRIDS);
     return obj;
 }
References WorldSession::GetPlayer(), m_session, SIZE_OF_GRIDS, and Cell::VisitGridObjects().
Referenced by getSelectedObject(), and debug_commandscript::HandleDebugSendOpcodeCommand().
GetObjectFromPlayerMapByDbGuid()
GameObject * ChatHandler::GetObjectFromPlayerMapByDbGuid (ObjectGuid::LowType lowguid)
Definition at line 512 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     auto bounds = m_session->GetPlayer()->GetMap()->GetGameObjectBySpawnIdStore().equal_range(lowguid);
     if (bounds.first != bounds.second)
         return bounds.first->second;
     return nullptr;
 }
References Map::GetGameObjectBySpawnIdStore(), WorldObject::GetMap(), WorldSession::GetPlayer(), and m_session.
Referenced by gobject_commandscript::HandleGameObjectActivateCommand(), gobject_commandscript::HandleGameObjectDeleteCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectSetPhaseCommand(), gobject_commandscript::HandleGameObjectSetStateCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGetDistanceCommand(), and misc_commandscript::HandleGPSCommand().
GetPlayer()
Player * ChatHandler::GetPlayer () const
Definition at line 42 of file Chat.cpp.
 {
     return m_session ? m_session->GetPlayer() : nullptr;
 }
References WorldSession::GetPlayer(), and m_session.
Referenced by Acore::ChatCommands::PlayerIdentifier::FromSelf(), Acore::ChatCommands::PlayerIdentifier::FromTarget(), debug_commandscript::HandleDebugEnterVehicleCommand(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugGetItemValueCommand(), debug_commandscript::HandleDebugItemExpireCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugMoveflagsCommand(), debug_commandscript::HandleDebugPlayMovieCommand(), debug_commandscript::HandleDebugPlayMusicCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), debug_commandscript::HandleDebugSendBuyErrorCommand(), debug_commandscript::HandleDebugSendChatMsgCommand(), debug_commandscript::HandleDebugSendEquipErrorCommand(), debug_commandscript::HandleDebugSendQuestInvalidMsgCommand(), debug_commandscript::HandleDebugSendQuestPartyMsgCommand(), debug_commandscript::HandleDebugSendSellErrorCommand(), debug_commandscript::HandleDebugSetItemValueCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), debug_commandscript::HandleDebugUpdateWorldStateCommand(), gm_commandscript::HandleGMOffCommand(), gm_commandscript::HandleGMOnCommand(), and Acore::PlayerCommand::HandleLearnSpellCommand().
GetPlayerGroupAndGUIDByName()
bool ChatHandler::GetPlayerGroupAndGUIDByName (const char * cname, Player *& player, Group *& group, ObjectGuid & guid, bool offline = false)
Definition at line 835 of file Chat.cpp.
 {
     player = nullptr;
     guid = ObjectGuid::Empty;
     if (cname)
     {
         std::string name = cname;
         if (!name.empty())
         {
             if (!normalizePlayerName(name))
             {
                 PSendSysMessage(LANG_PLAYER_NOT_FOUND);
                 SetSentErrorMessage(true);
                 return false;
             }
             player = ObjectAccessor::FindPlayerByName(name, false);
             if (offline)
                 guid = sObjectMgr->GetPlayerGUIDByName(name.c_str());
         }
     }
     if (player)
     {
         group = player->GetGroup();
         if (!guid || !offline)
             guid = player->GetGUID();
     }
     else
     {
         if (getSelectedPlayer())
             player = getSelectedPlayer();
         else
             player = m_session->GetPlayer();
         if (!guid || !offline)
             guid  = player->GetGUID();
         group = player->GetGroup();
     }
     return true;
 }
References ObjectGuid::Empty, ObjectAccessor::FindPlayerByName(), Player::GetGroup(), Object::GetGUID(), WorldSession::GetPlayer(), getSelectedPlayer(), LANG_PLAYER_NOT_FOUND, m_session, normalizePlayerName(), PSendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by misc_commandscript::HandleGroupDisbandCommand(), misc_commandscript::HandleGroupJoinCommand(), misc_commandscript::HandleGroupLeaderCommand(), and misc_commandscript::HandleGroupRemoveCommand().
getSelectedCreature()
Creature * ChatHandler::getSelectedCreature ()
Definition at line 342 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     return ObjectAccessor::GetCreatureOrPetOrVehicle(*m_session->GetPlayer(), m_session->GetPlayer()->GetTarget());
 }
References ObjectAccessor::GetCreatureOrPetOrVehicle(), WorldSession::GetPlayer(), Unit::GetTarget(), and m_session.
Referenced by cast_commandscript::HandleCastBackCommand(), cast_commandscript::HandleCastTargetCommad(), misc_commandscript::HandleComeToMeCommand(), misc_commandscript::HandleCreatePetCommand(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugThreatListCommand(), modify_commandscript::HandleModifyFactionCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcPlayEmoteCommand(), npc_commandscript::HandleNpcSayCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcSetLevelCommand(), npc_commandscript::HandleNpcSetLinkCommand(), npc_commandscript::HandleNpcSetModelCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetPhaseCommand(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), npc_commandscript::HandleNpcTameCommand(), npc_commandscript::HandleNpcTextEmoteCommand(), npc_commandscript::HandleNpcUnFollowCommand(), npc_commandscript::HandleNpcWhisperCommand(), npc_commandscript::HandleNpcYellCommand(), reset_commandscript::HandleResetTalentsCommand(), wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), and wp_commandscript::HandleWpUnLoadCommand().
getSelectedObject()
WorldObject * ChatHandler::getSelectedObject ()
Definition at line 329 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     ObjectGuid guid = m_session->GetPlayer()->GetTarget();
     if (!guid)
         return GetNearbyGameObject();
     return ObjectAccessor::GetUnit(*m_session->GetPlayer(), guid);
 }
References GetNearbyGameObject(), WorldSession::GetPlayer(), Unit::GetTarget(), ObjectAccessor::GetUnit(), and m_session.
Referenced by debug_commandscript::HandleDebugSet32BitCommand(), debug_commandscript::HandleDebugSetValueCommand(), and gobject_commandscript::HandleGameObjectInfoCommand().
getSelectedPlayer()
Player * ChatHandler::getSelectedPlayer ()
Definition at line 306 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     ObjectGuid selected = m_session->GetPlayer()->GetTarget();
     if (!selected)
         return m_session->GetPlayer();
     return ObjectAccessor::FindConnectedPlayer(selected);
 }
References ObjectAccessor::FindConnectedPlayer(), WorldSession::GetPlayer(), Unit::GetTarget(), and m_session.
Referenced by extractPlayerTarget(), GetPlayerGroupAndGUIDByName(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), achievement_commandscript::HandleAchievementAddCommand(), achievement_commandscript::HandleAchievementCheckAllCommand(), misc_commandscript::HandleAddItemCommand(), misc_commandscript::HandleAddItemSetCommand(), misc_commandscript::HandleCooldownCommand(), debug_commandscript::HandleDebugGetItemStateCommand(), deserter_commandscript::HandleDeserterAdd(), deserter_commandscript::HandleDeserterRemove(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleFreezeCommand(), gm_commandscript::HandleGMFlyCommand(), misc_commandscript::HandleHideAreaCommand(), honor_commandscript::HandleHonorAddCommand(), honor_commandscript::HandleHonorUpdateCommand(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), learn_commandscript::HandleLearnAllRecipesCommand(), learn_commandscript::HandleLearnCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTitleCommand(), misc_commandscript::HandleMaxSkillCommand(), modify_commandscript::HandleModifyArenaCommand(), modify_commandscript::HandleModifyDrunkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifySpellCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), misc_commandscript::HandleSaveCommand(), misc_commandscript::HandleSetSkillCommand(), misc_commandscript::HandleShowAreaCommand(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), misc_commandscript::HandleUnFreezeCommand(), and learn_commandscript::HandleUnLearnCommand().
getSelectedPlayerOrSelf()
Player * ChatHandler::getSelectedPlayerOrSelf ()
Definition at line 350 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     ObjectGuid selected = m_session->GetPlayer()->GetTarget();
     if (!selected)
         return m_session->GetPlayer();
     // first try with selected target
     Player* targetPlayer = ObjectAccessor::FindConnectedPlayer(selected);
     // if the target is not a player, then return self
     if (!targetPlayer)
         targetPlayer = m_session->GetPlayer();
     return targetPlayer;
 }
References ObjectAccessor::FindConnectedPlayer(), WorldSession::GetPlayer(), Unit::GetTarget(), and m_session.
Referenced by character_commandscript::HandleCharacterCheckBagCommand(), character_commandscript::HandleCharacterCheckProfessionCommand(), misc_commandscript::HandleGearStatsCommand(), guild_commandscript::HandleGuildInfoCommand(), lookup_commandscript::HandleLookupPlayerIpCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyMountCommand(), modify_commandscript::HandleModifySpeedCommand(), and modify_commandscript::HandleModifySwimCommand().
getSelectedUnit()
Unit * ChatHandler::getSelectedUnit ()
Definition at line 318 of file Chat.cpp.
 {
     if (!m_session)
         return nullptr;
     if (Unit* selected = m_session->GetPlayer()->GetSelectedUnit())
         return selected;
     return m_session->GetPlayer();
 }
References WorldSession::GetPlayer(), Player::GetSelectedUnit(), and m_session.
Referenced by misc_commandscript::HandleAuraCommand(), misc_commandscript::HandleBindSightCommand(), cast_commandscript::HandleCastCommand(), cast_commandscript::HandleCastDestCommand(), cast_commandscript::HandleCastSelfCommand(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugAnimCommand(), debug_commandscript::HandleDebugEnterVehicleCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugLoSCommand(), debug_commandscript::HandleDebugMoveflagsCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSetAuraStateCommand(), debug_commandscript::HandleDebugSetVehicleIdCommand(), debug_commandscript::HandleDebugUnitStateCommand(), debug_commandscript::HandleDebugUpdateCommand(), misc_commandscript::HandleDieCommand(), misc_commandscript::HandleFreezeCommand(), misc_commandscript::HandleGetDistanceCommand(), misc_commandscript::HandleGPSCommand(), honor_commandscript::HandleHonorAddKillCommand(), mmaps_commandscript::HandleMmapPathCommand(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyPhaseCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifyTalentCommand(), modify_commandscript::HandleMorphResetCommand(), modify_commandscript::HandleMorphTargetCommand(), misc_commandscript::HandleMovegensCommand(), npc_commandscript::HandleNpcSetEntryCommand(), misc_commandscript::HandlePossessCommand(), misc_commandscript::HandleRespawnCommand(), misc_commandscript::HandleUnAuraCommand(), misc_commandscript::HandleUnFreezeCommand(), misc_commandscript::HandleUnPossessCommand(), and list_commandscript::ListAurasCommand().
GetSession()
WorldSession* ChatHandler::GetSession () inline
Definition at line 122 of file Chat.h.
 { return m_session; }
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), go_commandscript::DoTeleport(), account_commandscript::HandleAccount2FARemoveCommand(), account_commandscript::HandleAccount2FASetupCommand(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountCommand(), account_commandscript::HandleAccountCreateCommand(), account_commandscript::HandleAccountLockCountryCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountPasswordCommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), misc_commandscript::HandleAddItemCommand(), misc_commandscript::HandleAddItemSetCommand(), misc_commandscript::HandleAppearCommand(), arena_commandscript::HandleArenaLookupCommand(), misc_commandscript::HandleBagsClearCommand(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), misc_commandscript::HandleBindSightCommand(), cast_commandscript::HandleCastBackCommand(), cast_commandscript::HandleCastCommand(), cast_commandscript::HandleCastDistCommand(), cheat_commandscript::HandleCasttimeCheatCommand(), misc_commandscript::HandleChangeWeather(), character_commandscript::HandleCharacterCheckBankCommand(), character_commandscript::HandleCharacterDeletedListHelper(), character_commandscript::HandleCharacterLevelCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), cheat_commandscript::HandleCheatStatusCommand(), misc_commandscript::HandleComeToMeCommand(), cheat_commandscript::HandleCoolDownCheatCommand(), misc_commandscript::HandleCooldownCommand(), misc_commandscript::HandleCreatePetCommand(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugAreaTriggersCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugLoSCommand(), debug_commandscript::HandleDebugPlayCinematicCommand(), debug_commandscript::HandleDebugSendChannelNotifyCommand(), debug_commandscript::HandleDebugSendChatMsgCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSendSetPhaseShiftCommand(), debug_commandscript::HandleDebugSendSpellFailCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), debug_commandscript::HandleDebugUnitStateCommand(), misc_commandscript::HandleDevCommand(), misc_commandscript::HandleDieCommand(), misc_commandscript::HandleDismountCommand(), event_commandscript::HandleEventActiveListCommand(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleFreezeCommand(), gobject_commandscript::HandleGameObjectActivateCommand(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectDeleteCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGetDistanceCommand(), gm_commandscript::HandleGMChatCommand(), gm_commandscript::HandleGMFlyCommand(), gm_commandscript::HandleGMListFullCommand(), gm_commandscript::HandleGMListIngameCommand(), message_commandscript::HandleGMNameAnnounceCommand(), gm_commandscript::HandleGMOffCommand(), gm_commandscript::HandleGMOnCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), gm_commandscript::HandleGMVisibleCommand(), cheat_commandscript::HandleGodModeCheatCommand(), go_commandscript::HandleGoGraveyardCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoTicketCommand(), go_commandscript::HandleGoXYZCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupSummonCommand(), misc_commandscript::HandleGUIDCommand(), honor_commandscript::HandleHonorAddKillCommand(), instance_commandscript::HandleInstanceGetBossStateCommand(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceSaveDataCommand(), instance_commandscript::HandleInstanceSetBossStateCommand(), instance_commandscript::HandleInstanceUnbindCommand(), misc_commandscript::HandleItemMoveCommand(), misc_commandscript::HandleKickPlayerCommand(), learn_commandscript::HandleLearnAllCraftsCommand(), learn_commandscript::HandleLearnAllGMCommand(), learn_commandscript::HandleLearnAllLangCommand(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), learn_commandscript::HandleLearnAllMySpellsCommand(), learn_commandscript::HandleLearnAllMyTalentsCommand(), character_commandscript::HandleLevelUpCommand(), misc_commandscript::HandleLinkGraveCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupCreatureCommand(), lookup_commandscript::HandleLookupEventCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupMapCommand(), lookup_commandscript::HandleLookupObjectCommand(), lookup_commandscript::HandleLookupPlayerIpCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTeleCommand(), lookup_commandscript::HandleLookupTitleCommand(), misc_commandscript::HandleMailBoxCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), mmaps_commandscript::HandleMmapTestArea(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyPhaseCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifyStandStateCommand(), modify_commandscript::HandleModifySwimCommand(), modify_commandscript::HandleMorphResetCommand(), modify_commandscript::HandleMorphTargetCommand(), misc_commandscript::HandleMuteCommand(), message_commandscript::HandleNameAnnounceCommand(), misc_commandscript::HandleNearGraveCommand(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddTempSpawnCommand(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), npc_commandscript::HandleNpcSetFactionTempIdCommand(), npc_commandscript::HandleNpcSetOriginalFaction(), npc_commandscript::HandleNpcTameCommand(), npc_commandscript::HandleNpcUnFollowCommand(), misc_commandscript::HandlePetLearnCommand(), misc_commandscript::HandlePetUnlearnCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandlePossessCommand(), cheat_commandscript::HandlePowerCheatCommand(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleRespawnCommand(), misc_commandscript::HandleSaveCommand(), misc_commandscript::HandleSendItemsCommand(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMoneyCommand(), server_commandscript::HandleServerInfoCommand(), spectator_commandscript::HandleSpectatorLeaveCommand(), spectator_commandscript::HandleSpectatorResetCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), spectator_commandscript::HandleSpectatorVersionCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), misc_commandscript::HandleSummonCommand(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleAddCommand(), tele_commandscript::HandleTeleCommand(), misc_commandscript::HandleUnbindSightCommand(), misc_commandscript::HandleUnPossessCommand(), misc_commandscript::HandleUnstuckCommand(), cheat_commandscript::HandleWaterWalkCheatCommand(), message_commandscript::HandleWhispersCommand(), wp_commandscript::HandleWpAddCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), list_commandscript::ListAurasCommand(), and Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().
GetSessionDbcLocale()
LocaleConstant ChatHandler::GetSessionDbcLocale () const virtual
Reimplemented in CliHandler.
Definition at line 787 of file Chat.cpp.
 {
     return m_session->GetSessionDbcLocale();
 }
References WorldSession::GetSessionDbcLocale(), and m_session.
Referenced by character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTitleCommand(), modify_commandscript::HandleModifyRepCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandleSetSkillCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), and list_commandscript::ListAurasCommand().
GetSessionDbLocaleIndex()
int ChatHandler::GetSessionDbLocaleIndex () const virtual
Reimplemented in CliHandler.
Definition at line 792 of file Chat.cpp.
 {
     return m_session->GetSessionDbLocaleIndex();
 }
References WorldSession::GetSessionDbLocaleIndex(), and m_session.
Referenced by lookup_commandscript::HandleLookupCreatureCommand(), lookup_commandscript::HandleLookupItemCommand(), lookup_commandscript::HandleLookupObjectCommand(), and lookup_commandscript::HandleLookupQuestCommand().
HasLowerSecurity()
bool ChatHandler::HasLowerSecurity (Player * target, ObjectGuid guid = ObjectGuid::Empty, bool strong = false)
Definition at line 58 of file Chat.cpp.
 {
     WorldSession* target_session = nullptr;
     uint32 target_account = 0;
     if (target)
         target_session = target->GetSession();
     else if (guid)
         target_account = sObjectMgr->GetPlayerAccountIdByGUID(guid.GetCounter());
     if (!target_session && !target_account)
     {
         SendSysMessage(LANG_PLAYER_NOT_FOUND);
         SetSentErrorMessage(true);
         return true;
     }
     return HasLowerSecurityAccount(target_session, target_account, strong);
 }
References ObjectGuid::GetCounter(), Player::GetSession(), HasLowerSecurityAccount(), LANG_PLAYER_NOT_FOUND, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by modify_commandscript::CheckModifySpeed(), tele_commandscript::DoNameTeleport(), misc_commandscript::HandleAppearCommand(), character_commandscript::HandleCharacterRenameCommand(), misc_commandscript::HandleCombatStopCommand(), misc_commandscript::HandleDamageCommand(), misc_commandscript::HandleDieCommand(), misc_commandscript::HandleGearRepairCommand(), misc_commandscript::HandleGroupSummonCommand(), honor_commandscript::HandleHonorAddCommand(), honor_commandscript::HandleHonorAddKillCommand(), honor_commandscript::HandleHonorUpdateCommand(), misc_commandscript::HandleKickPlayerCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyMountCommand(), modify_commandscript::HandleModifyPhaseCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), modify_commandscript::HandleModifyTalentCommand(), modify_commandscript::HandleMorphResetCommand(), modify_commandscript::HandleMorphTargetCommand(), misc_commandscript::HandleMuteCommand(), npc_commandscript::HandleNpcWhisperCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandleRecallCommand(), misc_commandscript::HandleSummonCommand(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), and misc_commandscript::HandleUnmuteCommand().
HasLowerSecurityAccount()
bool ChatHandler::HasLowerSecurityAccount (WorldSession * target, uint32 account, bool strong = false)
Definition at line 78 of file Chat.cpp.
 {
     uint32 target_sec;
     // allow everything from console and RA console
     if (!m_session)
         return false;
     // ignore only for non-players for non strong checks (when allow apply command at least to same sec level)
     if (!AccountMgr::IsPlayerAccount(m_session->GetSecurity()) && !strong && !sWorld->getBoolConfig(CONFIG_GM_LOWER_SECURITY))
         return false;
     if (target)
         target_sec = target->GetSecurity();
     else if (target_account)
         target_sec = AccountMgr::GetSecurity(target_account, realm.Id.Realm);
     else
         return true;                                        // caller must report error for (target == nullptr && target_account == 0)
     AccountTypes target_ac_sec = AccountTypes(target_sec);
     if (m_session->GetSecurity() < target_ac_sec || (strong && m_session->GetSecurity() <= target_ac_sec))
     {
         SendSysMessage(LANG_YOURS_SECURITY_IS_LOW);
         SetSentErrorMessage(true);
         return true;
     }
     return false;
 }
References CONFIG_GM_LOWER_SECURITY, WorldSession::GetSecurity(), AccountMgr::GetSecurity(), Realm::Id, AccountMgr::IsPlayerAccount(), LANG_YOURS_SECURITY_IS_LOW, m_session, realm, RealmHandle::Realm, SendSysMessage(), SetSentErrorMessage(), and sWorld.
Referenced by account_commandscript::HandleAccountDeleteCommand(), account_commandscript::HandleAccountSet2FACommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetPasswordCommand(), and HasLowerSecurity().
HasSentErrorMessage()
bool ChatHandler::HasSentErrorMessage () const inline
Definition at line 117 of file Chat.h.
 { return sentErrorMessage; }
Referenced by World::ProcessCliCommands(), and Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().
IsAvailable()
bool ChatHandler::IsAvailable (uint32 securityLevel) const
Definition at line 52 of file Chat.cpp.
 {
     // check security level only for simple  command (without child commands)
     return m_session->GetSecurity() >= AccountTypes(securityLevel);
 }
References WorldSession::GetSecurity(), and m_session.
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::IsInvokerVisible().
IsConsole()
bool ChatHandler::IsConsole () const inline
Definition at line 120 of file Chat.h.
 { return (m_session == nullptr); }
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::IsInvokerVisible(), and Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().
IsHumanReadable()
virtual bool ChatHandler::IsHumanReadable () const inline virtual
Definition at line 83 of file Chat.h.
 { return true; }
LineFromMessage()
static char* ChatHandler::LineFromMessage (char *& pos) inline static
Definition at line 51 of file Chat.h.
 { char* start = strtok(pos, "\n"); pos = nullptr; return start; }
Referenced by World::SendGlobalText().
needReportToTarget()
bool ChatHandler::needReportToTarget (Player * chr) const virtual
Reimplemented in CliHandler.
Definition at line 781 of file Chat.cpp.
 {
     Player* pl = m_session->GetPlayer();
     return pl != chr && pl->IsVisibleGloballyFor(chr);
 }
References WorldSession::GetPlayer(), Player::IsVisibleGloballyFor(), and m_session.
Referenced by tele_commandscript::DoNameTeleport(), character_commandscript::HandleCharacterLevel(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleGearRepairCommand(), misc_commandscript::HandleGroupSummonCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), misc_commandscript::HandleSummonCommand(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), and modify_commandscript::NotifyModification().
ParseCommands()
bool ChatHandler::ParseCommands (std::string_view text) virtual
Reimplemented in CliHandler.
Definition at line 174 of file Chat.cpp.
 {
     ASSERT(!text.empty());
     // chat case (.command or !command format)
     if ((text[0] != '!') && (text[0] != '.'))
         return false;
     // ignore single . and ! in line
     if (text.length() < 2)
         return false;
     // ignore messages staring from many dots.
     if (text[1] == text[0])
         return false;
     // ignore messages with separator after .
     if (text[1] == Acore::Impl::ChatCommands::COMMAND_DELIMITER)
         return false;
     return _ParseCommands(text.substr(1));
 }
References _ParseCommands(), ASSERT, and Acore::Impl::ChatCommands::COMMAND_DELIMITER.
PGetParseString()
template<typename... Args> std::string ChatHandler::PGetParseString (uint32 entry, Args &&... args) const inline
Definition at line 72 of file Chat.h.
     {
         return Acore::StringFormat(GetAcoreString(entry), std::forward<Args>(args)...);
     }
References Acore::Impl::ChatCommands::GetAcoreString(), and Acore::StringFormat().
Referenced by GmTicket::FormatMessageString(), ticket_commandscript::HandleGMTicketCommentCommand(), and ticket_commandscript::HandleGMTicketCompleteCommand().
playerLink()
std::string ChatHandler::playerLink (std::string const & name) const inline
Definition at line 111 of file Chat.h.
 { return m_session ? "|cffffffff|Hplayer:" + name + "|h[" + name + "]|h|r" : name; }
Referenced by tele_commandscript::DoNameTeleport(), GetNameLink(), misc_commandscript::HandleAppearCommand(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterLevelCommand(), character_commandscript::HandleCharacterRenameCommand(), character_commandscript::HandleLevelUpCommand(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandlePInfoCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleSendItemsCommand(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMoneyCommand(), misc_commandscript::HandleSummonCommand(), and misc_commandscript::HandleUnmuteCommand().
PSendSysMessage() [1/2]
template<typename... Args> void ChatHandler::PSendSysMessage (char const * fmt, Args &&... args) inline
Definition at line 60 of file Chat.h.
     {
         SendSysMessage(Acore::StringFormat(fmt, std::forward<Args>(args)...).c_str());
     }
References Acore::StringFormat().
Referenced by ticket_commandscript::_HandleGMTicketResponseAppendCommand(), _ParseCommands(), Player::AddItem(), modify_commandscript::CheckModifySpeed(), cast_commandscript::CheckSpellExistsAndIsValid(), AchievementMgr::CompletedAchievement(), tele_commandscript::DoNameTeleport(), go_commandscript::DoTeleport(), GetPlayerGroupAndGUIDByName(), GetPlayerInfo(), account_commandscript::HandleAccount2FASetupCommand(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountCommand(), account_commandscript::HandleAccountCreateCommand(), account_commandscript::HandleAccountDeleteCommand(), account_commandscript::HandleAccountLockCountryCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountOnlineListCommand(), account_commandscript::HandleAccountRemoveLockCountryCommand(), account_commandscript::HandleAccountSet2FACommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), account_commandscript::HandleAccountSetPasswordCommand(), disable_commandscript::HandleAddDisables(), misc_commandscript::HandleAddItemCommand(), misc_commandscript::HandleAddItemSetCommand(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleAreaTriggerOpcode(), arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), arena_commandscript::HandleArenaDisbandCommand(), arena_commandscript::HandleArenaInfoCommand(), arena_commandscript::HandleArenaLookupCommand(), arena_commandscript::HandleArenaRenameCommand(), misc_commandscript::HandleAuraCommand(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), ban_commandscript::HandleBanInfoAccountCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanInfoHelper(), ban_commandscript::HandleBanInfoIPCommand(), ban_commandscript::HandleBanListAccountCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleCharacterAuraFrozen(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCheckBagCommand(), character_commandscript::HandleCharacterCheckProfessionCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterDeletedListHelper(), character_commandscript::HandleCharacterDeletedRestoreHelper(), character_commandscript::HandleCharacterEraseCommand(), character_commandscript::HandleCharacterLevel(), character_commandscript::HandleCharacterLevelCommand(), character_commandscript::HandleCharacterRenameCommand(), character_commandscript::HandleCharacterTitlesCommand(), cheat_commandscript::HandleCheatStatusCommand(), misc_commandscript::HandleCooldownCommand(), misc_commandscript::HandleCreatePetCommand(), debug_commandscript::HandleDebugAnimCommand(), debug_commandscript::HandleDebugAreaTriggersCommand(), debug_commandscript::HandleDebugEnterVehicleCommand(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugGetItemValueCommand(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugLoSCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugMoveflagsCommand(), debug_commandscript::HandleDebugPlayCinematicCommand(), debug_commandscript::HandleDebugPlayMovieCommand(), debug_commandscript::HandleDebugPlayMusicCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSet32BitCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugSetVehicleIdCommand(), debug_commandscript::HandleDebugThreatListCommand(), debug_commandscript::HandleDebugUpdateCommand(), event_commandscript::HandleEventActiveListCommand(), event_commandscript::HandleEventInfoCommand(), event_commandscript::HandleEventStartCommand(), event_commandscript::HandleEventStopCommand(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleFreezeCommand(), gobject_commandscript::HandleGameObjectActivateCommand(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectDeleteCommand(), gobject_commandscript::HandleGameObjectInfoCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectSetPhaseCommand(), gobject_commandscript::HandleGameObjectSetStateCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGearRepairCommand(), misc_commandscript::HandleGearStatsCommand(), misc_commandscript::HandleGetDistanceCommand(), gm_commandscript::HandleGMFlyCommand(), gm_commandscript::HandleGMListFullCommand(), gm_commandscript::HandleGMListIngameCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), gm_commandscript::HandleGMVisibleCommand(), go_commandscript::HandleGoGraveyardCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoTaxinodeCommand(), go_commandscript::HandleGoTriggerCommand(), go_commandscript::HandleGoXYZCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupJoinCommand(), misc_commandscript::HandleGroupListCommand(), misc_commandscript::HandleGroupSummonCommand(), misc_commandscript::HandleGUIDCommand(), guild_commandscript::HandleGuildInfoCommand(), instance_commandscript::HandleInstanceGetBossStateCommand(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceSaveDataCommand(), instance_commandscript::HandleInstanceSetBossStateCommand(), instance_commandscript::HandleInstanceStatsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), misc_commandscript::HandleKickPlayerCommand(), learn_commandscript::HandleLearnAllDefaultCommand(), learn_commandscript::HandleLearnAllRecipesCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), character_commandscript::HandleLevelUpCommand(), lfg_commandscript::HandleLfgCleanCommand(), lfg_commandscript::HandleLfgGroupInfoCommand(), lfg_commandscript::HandleLfgOptionsCommand(), misc_commandscript::HandleLinkGraveCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListItemCommand(), list_commandscript::HandleListObjectCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupCreatureCommand(), lookup_commandscript::HandleLookupEventCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupMapCommand(), lookup_commandscript::HandleLookupObjectCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTeleCommand(), lookup_commandscript::HandleLookupTitleCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), mmaps_commandscript::HandleMmapTestArea(), modify_commandscript::HandleModifyArenaCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFactionCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), misc_commandscript::HandleMovegensCommand(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandleMuteInfoCommand(), misc_commandscript::HandleMuteInfoHelper(), misc_commandscript::HandleNearGraveCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetLinkCommand(), npc_commandscript::HandleNpcSetModelCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), npc_commandscript::HandleNpcTameCommand(), npc_commandscript::HandleNpcUnFollowCommand(), character_commandscript::HandlePDumpLoadCommand(), character_commandscript::HandlePDumpWriteCommand(), misc_commandscript::HandlePetLearnCommand(), misc_commandscript::HandlePetUnlearnCommand(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandlePlayAllCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), misc_commandscript::HandleRecallCommand(), reload_commandscript::HandleReloadAllScriptsCommand(), reload_commandscript::HandleReloadCreatureTemplateCommand(), disable_commandscript::HandleRemoveDisables(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleSendItemsCommand(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMessageCommand(), misc_commandscript::HandleSendMoneyCommand(), server_commandscript::HandleServerDebugCommand(), server_commandscript::HandleServerInfoCommand(), server_commandscript::HandleServerMotdCommand(), server_commandscript::HandleServerSetMotdCommand(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSetSkillCommand(), misc_commandscript::HandleSkirmishCommand(), spectator_commandscript::HandleSpectatorCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleStringCommand(), misc_commandscript::HandleSummonCommand(), WorldSession::HandleSummonResponseOpcode(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), ticket_commandscript::HandleToggleGMTicketSystem(), ban_commandscript::HandleUnBanHelper(), misc_commandscript::HandleUnFreezeCommand(), misc_commandscript::HandleUnmuteCommand(), message_commandscript::HandleWhispersCommand(), wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpEventCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpReloadCommand(), wp_commandscript::HandleWpShowCommand(), wp_commandscript::HandleWpUnLoadCommand(), ObjectMgr::IsVendorItemValid(), Channel::JoinChannel(), Channel::KickOrBan(), list_commandscript::ListAurasCommand(), lookup_commandscript::LookupPlayerSearchCommand(), modify_commandscript::NotifyModification(), npc_icc_buff_switcher::OnGossipSelect(), Player::PrettyPrintRequirementsAchievementsList(), Player::PrettyPrintRequirementsItemsList(), Player::PrettyPrintRequirementsQuestList(), Player::RewardHonor(), Player::Satisfy(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelp(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelpFor(), BattlegroundQueue::SendJoinMessageArenaQueue(), BattlegroundQueue::SendMessageBGQueue(), Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand(), character_commandscript::ValidatePDumpTarget(), and Player::Whisper().
PSendSysMessage() [2/2]
template<typename... Args> void ChatHandler::PSendSysMessage (uint32 entry, Args &&... args) inline
Definition at line 66 of file Chat.h.
     {
         SendSysMessage(PGetParseString(entry, std::forward<Args>(args)...).c_str());
     }
SendGlobalGMSysMessage()
void ChatHandler::SendGlobalGMSysMessage (const char * str)
Definition at line 144 of file Chat.cpp.
 {
     WorldPacket data;
     for (std::string_view line : Acore::Tokenize(str, '\n', true))
     {
         BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, line);
         sWorld->SendGlobalGMMessage(&data);
     }
 }
References BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, sWorld, and Acore::Tokenize().
Referenced by bf_commandscript::HandleBattlefieldEnable(), bf_commandscript::HandleBattlefieldEnd(), bf_commandscript::HandleBattlefieldStart(), bf_commandscript::HandleBattlefieldSwitch(), bf_commandscript::HandleBattlefieldTimer(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), reload_commandscript::HandleReloadAchievementCriteriaDataCommand(), reload_commandscript::HandleReloadAchievementRewardCommand(), reload_commandscript::HandleReloadAcoreStringCommand(), reload_commandscript::HandleReloadAllLootCommand(), reload_commandscript::HandleReloadAllQuestCommand(), reload_commandscript::HandleReloadAllScriptsCommand(), reload_commandscript::HandleReloadAreaTriggerCommand(), reload_commandscript::HandleReloadAreaTriggerTavernCommand(), reload_commandscript::HandleReloadAreaTriggerTeleportCommand(), reload_commandscript::HandleReloadAuctionsCommand(), reload_commandscript::HandleReloadAutobroadcastCommand(), reload_commandscript::HandleReloadBattlegroundTemplate(), reload_commandscript::HandleReloadBroadcastTextCommand(), reload_commandscript::HandleReloadCommandCommand(), reload_commandscript::HandleReloadConditions(), reload_commandscript::HandleReloadConfigCommand(), reload_commandscript::HandleReloadCreatureQuestEnderCommand(), reload_commandscript::HandleReloadCreatureQuestStarterCommand(), reload_commandscript::HandleReloadCreatureTemplateCommand(), reload_commandscript::HandleReloadCreatureText(), reload_commandscript::HandleReloadDisablesCommand(), reload_commandscript::HandleReloadDungeonAccessCommand(), reload_commandscript::HandleReloadEventScriptsCommand(), reload_commandscript::HandleReloadGameGraveyardCommand(), reload_commandscript::HandleReloadGameGraveyardZoneCommand(), reload_commandscript::HandleReloadGameTeleCommand(), reload_commandscript::HandleReloadGOQuestEnderCommand(), reload_commandscript::HandleReloadGOQuestStarterCommand(), reload_commandscript::HandleReloadGossipMenuCommand(), reload_commandscript::HandleReloadGossipMenuOptionCommand(), reload_commandscript::HandleReloadItemEnchantementsCommand(), reload_commandscript::HandleReloadItemSetNamesCommand(), reload_commandscript::HandleReloadLfgRewardsCommand(), reload_commandscript::HandleReloadLinkedRespawnCommand(), reload_commandscript::HandleReloadLocalesAchievementRewardCommand(), reload_commandscript::HandleReloadLocalesCreatureCommand(), reload_commandscript::HandleReloadLocalesCreatureTextCommand(), reload_commandscript::HandleReloadLocalesGameobjectCommand(), reload_commandscript::HandleReloadLocalesGossipMenuOptionCommand(), reload_commandscript::HandleReloadLocalesItemCommand(), reload_commandscript::HandleReloadLocalesItemSetNameCommand(), reload_commandscript::HandleReloadLocalesNpcTextCommand(), reload_commandscript::HandleReloadLocalesPageTextCommand(), reload_commandscript::HandleReloadLocalesPointsOfInterestCommand(), reload_commandscript::HandleReloadLocalesQuestCommand(), reload_commandscript::HandleReloadLocalesQuestOfferRewardCommand(), reload_commandscript::HandleReloadLocalesQuestRequestItemsCommand(), reload_commandscript::HandleReloadLootTemplatesCreatureCommand(), reload_commandscript::HandleReloadLootTemplatesDisenchantCommand(), reload_commandscript::HandleReloadLootTemplatesFishingCommand(), reload_commandscript::HandleReloadLootTemplatesGameobjectCommand(), reload_commandscript::HandleReloadLootTemplatesItemCommand(), reload_commandscript::HandleReloadLootTemplatesMailCommand(), reload_commandscript::HandleReloadLootTemplatesMillingCommand(), reload_commandscript::HandleReloadLootTemplatesPickpocketingCommand(), reload_commandscript::HandleReloadLootTemplatesProspectingCommand(), reload_commandscript::HandleReloadLootTemplatesReferenceCommand(), reload_commandscript::HandleReloadLootTemplatesSkinningCommand(), reload_commandscript::HandleReloadLootTemplatesSpellCommand(), reload_commandscript::HandleReloadMailLevelRewardCommand(), reload_commandscript::HandleReloadNpcTrainerCommand(), reload_commandscript::HandleReloadNpcVendorCommand(), reload_commandscript::HandleReloadOnKillReputationCommand(), reload_commandscript::HandleReloadPageTextsCommand(), reload_commandscript::HandleReloadPointsOfInterestCommand(), reload_commandscript::HandleReloadQuestAreaTriggersCommand(), reload_commandscript::HandleReloadQuestPOICommand(), reload_commandscript::HandleReloadQuestTemplateCommand(), reload_commandscript::HandleReloadReservedNameCommand(), reload_commandscript::HandleReloadSkillDiscoveryTemplateCommand(), reload_commandscript::HandleReloadSkillExtraItemTemplateCommand(), reload_commandscript::HandleReloadSkillFishingBaseLevelCommand(), reload_commandscript::HandleReloadSkillPerfectItemTemplateCommand(), reload_commandscript::HandleReloadSmartScripts(), reload_commandscript::HandleReloadSpellAreaCommand(), reload_commandscript::HandleReloadSpellBonusesCommand(), reload_commandscript::HandleReloadSpellClickSpellsCommand(), reload_commandscript::HandleReloadSpellGroupsCommand(), reload_commandscript::HandleReloadSpellGroupStackRulesCommand(), reload_commandscript::HandleReloadSpellLinkedSpellCommand(), reload_commandscript::HandleReloadSpellPetAurasCommand(), reload_commandscript::HandleReloadSpellProcEventCommand(), reload_commandscript::HandleReloadSpellProcsCommand(), reload_commandscript::HandleReloadSpellRequiredCommand(), reload_commandscript::HandleReloadSpellScriptsCommand(), reload_commandscript::HandleReloadSpellTargetPositionCommand(), reload_commandscript::HandleReloadSpellThreatsCommand(), reload_commandscript::HandleReloadVehicleAccessoryCommand(), reload_commandscript::HandleReloadVehicleTemplateAccessoryCommand(), reload_commandscript::HandleReloadWardenactionCommand(), reload_commandscript::HandleReloadWpCommand(), and reload_commandscript::HandleReloadWpScriptsCommand().
SendGlobalSysMessage()
void ChatHandler::SendGlobalSysMessage (const char * str)
Definition at line 134 of file Chat.cpp.
 {
     WorldPacket data;
     for (std::string_view line : Acore::Tokenize(str, '\n', true))
     {
         BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, line);
         sWorld->SendGlobalMessage(&data);
     }
 }
References BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, sWorld, and Acore::Tokenize().
Referenced by reload_commandscript::HandleReloadReputationRewardRateCommand(), and reload_commandscript::HandleReloadReputationSpilloverTemplateCommand().
SendSysMessage() [1/2]
void ChatHandler::SendSysMessage (std::string_view str, bool escapeCharacters = false) virtual
Reimplemented in CliHandler.
Definition at line 108 of file Chat.cpp.
 {
     std::string msg{ str };
     // Replace every "|" with "||" in msg
     if (escapeCharacters && msg.find('|') != std::string::npos)
     {
         std::vector<std::string_view> tokens = Acore::Tokenize(msg, '|', true);
         std::ostringstream stream;
         for (size_t i = 0; i < tokens.size() - 1; ++i)
             stream << tokens[i] << "||";
         stream << tokens[tokens.size() - 1];
         msg = stream.str();
     }
     WorldPacket data;
     for (std::string_view line : Acore::Tokenize(str, '\n', true))
     {
         BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, line);
         m_session->SendPacket(&data);
     }
 }
References BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, m_session, WorldSession::SendPacket(), and Acore::Tokenize().
Referenced by modify_commandscript::CheckModifySpeed(), extractKeyFromLink(), extractPlayerTarget(), account_commandscript::HandleAccount2FARemoveCommand(), account_commandscript::HandleAccount2FASetupCommand(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountCreateCommand(), account_commandscript::HandleAccountLockCountryCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountOnlineListCommand(), account_commandscript::HandleAccountPasswordCommand(), account_commandscript::HandleAccountRemoveLockCountryCommand(), account_commandscript::HandleAccountSet2FACommand(), account_commandscript::HandleAccountSetGmLevelCommand(), account_commandscript::HandleAccountSetPasswordCommand(), achievement_commandscript::HandleAchievementAddCommand(), achievement_commandscript::HandleAchievementCheckAllCommand(), misc_commandscript::HandleAppearCommand(), arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), arena_commandscript::HandleArenaDisbandCommand(), arena_commandscript::HandleArenaRenameCommand(), misc_commandscript::HandleAuraCommand(), misc_commandscript::HandleBagsClearCommand(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), WorldSession::HandleCancelMountAuraOpcode(), cast_commandscript::HandleCastBackCommand(), cast_commandscript::HandleCastCommand(), cast_commandscript::HandleCastDestCommand(), cast_commandscript::HandleCastSelfCommand(), cast_commandscript::HandleCastTargetCommad(), cheat_commandscript::HandleCasttimeCheatCommand(), misc_commandscript::HandleChangeWeather(), WorldSession::HandleCharacterAuraFrozen(), character_commandscript::HandleCharacterDeletedDeleteCommand(), character_commandscript::HandleCharacterDeletedListCommand(), character_commandscript::HandleCharacterDeletedListHelper(), character_commandscript::HandleCharacterDeletedRestoreCommand(), character_commandscript::HandleCharacterRenameCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), cheat_commandscript::HandleCheatStatusCommand(), misc_commandscript::HandleCombatStopCommand(), misc_commandscript::HandleComeToMeCommand(), cheat_commandscript::HandleCoolDownCheatCommand(), misc_commandscript::HandleCooldownCommand(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugDummyCommand(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), debug_commandscript::HandleDebugSendLargePacketCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSet32BitCommand(), debug_commandscript::HandleDebugSetAuraStateCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugThreatListCommand(), debug_commandscript::HandleDebugUpdateCommand(), deserter_commandscript::HandleDeserterAdd(), deserter_commandscript::HandleDeserterRemove(), misc_commandscript::HandleDevCommand(), misc_commandscript::HandleDieCommand(), misc_commandscript::HandleDismountCommand(), event_commandscript::HandleEventActiveListCommand(), event_commandscript::HandleEventInfoCommand(), event_commandscript::HandleEventStartCommand(), event_commandscript::HandleEventStopCommand(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleFreezeCommand(), gobject_commandscript::HandleGameObjectSetPhaseCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), misc_commandscript::HandleGetDistanceCommand(), gm_commandscript::HandleGMChatCommand(), gm_commandscript::HandleGMListFullCommand(), gm_commandscript::HandleGMListIngameCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketEscalateCommand(), ticket_commandscript::HandleGMTicketGetByIdCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), ticket_commandscript::HandleGMTicketResetCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), go_commandscript::HandleGoCreatureCIdCommand(), go_commandscript::HandleGoCreatureSpawnIdCommand(), cheat_commandscript::HandleGodModeCheatCommand(), go_commandscript::HandleGoGameObjectGOIdCommand(), go_commandscript::HandleGoGameObjectSpawnIdCommand(), go_commandscript::HandleGoTicketCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupSummonCommand(), misc_commandscript::HandleGUIDCommand(), guild_commandscript::HandleGuildCreateCommand(), misc_commandscript::HandleHideAreaCommand(), honor_commandscript::HandleHonorAddCommand(), honor_commandscript::HandleHonorAddKillCommand(), honor_commandscript::HandleHonorUpdateCommand(), misc_commandscript::HandleInventoryCountCommand(), misc_commandscript::HandleKickPlayerCommand(), learn_commandscript::HandleLearnAllCraftsCommand(), learn_commandscript::HandleLearnAllGMCommand(), learn_commandscript::HandleLearnAllLangCommand(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), learn_commandscript::HandleLearnAllMySpellsCommand(), learn_commandscript::HandleLearnAllMyTalentsCommand(), learn_commandscript::HandleLearnAllRecipesCommand(), learn_commandscript::HandleLearnCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), list_commandscript::HandleListItemCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupCreatureCommand(), lookup_commandscript::HandleLookupEventCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupMapCommand(), lookup_commandscript::HandleLookupObjectCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTeleCommand(), lookup_commandscript::HandleLookupTitleCommand(), misc_commandscript::HandleMaxSkillCommand(), modify_commandscript::HandleModifyArenaCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFactionCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyMountCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), modify_commandscript::HandleModifyTalentCommand(), misc_commandscript::HandleMovegensCommand(), misc_commandscript::HandleMuteCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcPlayEmoteCommand(), npc_commandscript::HandleNpcSayCommand(), npc_commandscript::HandleNpcSetAllowMovementCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetEntryCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcSetLevelCommand(), npc_commandscript::HandleNpcSetLinkCommand(), npc_commandscript::HandleNpcSetModelCommand(), npc_commandscript::HandleNpcSetPhaseCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), npc_commandscript::HandleNpcTameCommand(), npc_commandscript::HandleNpcTextEmoteCommand(), npc_commandscript::HandleNpcWhisperCommand(), npc_commandscript::HandleNpcYellCommand(), cheat_commandscript::HandlePowerCheatCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), reload_commandscript::HandleReloadEventScriptsCommand(), reload_commandscript::HandleReloadSpellScriptsCommand(), reload_commandscript::HandleReloadWardenactionCommand(), reload_commandscript::HandleReloadWpScriptsCommand(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleRespawnCommand(), misc_commandscript::HandleSaveAllCommand(), misc_commandscript::HandleSaveCommand(), server_commandscript::HandleServerDebugCommand(), server_commandscript::HandleServerExitCommand(), server_commandscript::HandleServerSetClosedCommand(), misc_commandscript::HandleSetSkillCommand(), misc_commandscript::HandleShowAreaCommand(), spectator_commandscript::HandleSpectatorLeaveCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleStringCommand(), tele_commandscript::HandleTeleAddCommand(), tele_commandscript::HandleTeleCommand(), tele_commandscript::HandleTeleDelCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), misc_commandscript::HandleUnAuraCommand(), ban_commandscript::HandleUnBanCharacterCommand(), ban_commandscript::HandleUnBanHelper(), misc_commandscript::HandleUnFreezeCommand(), learn_commandscript::HandleUnLearnCommand(), Acore::PlayerCommand::HandleUnlearnSpellCommand(), misc_commandscript::HandleUnmuteCommand(), cheat_commandscript::HandleWaterWalkCheatCommand(), message_commandscript::HandleWhispersCommand(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), HasLowerSecurity(), HasLowerSecurityAccount(), list_commandscript::ListAurasCommand(), Player::Satisfy(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelp(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelpFor(), Acore::Impl::ChatCommands::SendErrorMessageToHandler(), SendSysMessage(), TicketMgr::ShowClosedList(), TicketMgr::ShowEscalatedList(), TicketMgr::ShowList(), and Player::Whisper().
SendSysMessage() [2/2]
void ChatHandler::SendSysMessage (uint32 entry)
Definition at line 154 of file Chat.cpp.
 {
     SendSysMessage(GetAcoreString(entry));
 }
References GetAcoreString(), and SendSysMessage().
SetSentErrorMessage()
void ChatHandler::SetSentErrorMessage (bool val) inline
Definition at line 118 of file Chat.h.
 { sentErrorMessage = val; }
Referenced by _ParseCommands(), modify_commandscript::CheckModifySpeed(), cast_commandscript::CheckSpellExistsAndIsValid(), tele_commandscript::DoNameTeleport(), go_commandscript::DoTeleport(), extractPlayerTarget(), GetPlayerGroupAndGUIDByName(), account_commandscript::HandleAccount2FARemoveCommand(), account_commandscript::HandleAccount2FASetupCommand(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountCreateCommand(), account_commandscript::HandleAccountDeleteCommand(), account_commandscript::HandleAccountLockCountryCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountPasswordCommand(), account_commandscript::HandleAccountRemoveLockCountryCommand(), account_commandscript::HandleAccountSet2FACommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), account_commandscript::HandleAccountSetPasswordCommand(), achievement_commandscript::HandleAchievementAddCommand(), achievement_commandscript::HandleAchievementCheckAllCommand(), disable_commandscript::HandleAddDisables(), misc_commandscript::HandleAddItemCommand(), misc_commandscript::HandleAddItemSetCommand(), misc_commandscript::HandleAppearCommand(), arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), arena_commandscript::HandleArenaDisbandCommand(), arena_commandscript::HandleArenaInfoCommand(), arena_commandscript::HandleArenaRenameCommand(), misc_commandscript::HandleAuraCommand(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), ban_commandscript::HandleBanInfoAccountCommand(), cast_commandscript::HandleCastBackCommand(), cast_commandscript::HandleCastCommand(), cast_commandscript::HandleCastDestCommand(), cast_commandscript::HandleCastSelfCommand(), cast_commandscript::HandleCastTargetCommad(), misc_commandscript::HandleChangeWeather(), character_commandscript::HandleCharacterDeletedDeleteCommand(), character_commandscript::HandleCharacterDeletedListCommand(), character_commandscript::HandleCharacterDeletedRestoreCommand(), character_commandscript::HandleCharacterRenameCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), misc_commandscript::HandleCombatStopCommand(), misc_commandscript::HandleComeToMeCommand(), misc_commandscript::HandleCooldownCommand(), misc_commandscript::HandleCreatePetCommand(), misc_commandscript::HandleDamageCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugPlayCinematicCommand(), debug_commandscript::HandleDebugPlayMovieCommand(), debug_commandscript::HandleDebugPlayMusicCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugSet32BitCommand(), debug_commandscript::HandleDebugSetAuraStateCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugUpdateCommand(), deserter_commandscript::HandleDeserterAdd(), deserter_commandscript::HandleDeserterRemove(), misc_commandscript::HandleDevCommand(), misc_commandscript::HandleDieCommand(), misc_commandscript::HandleDismountCommand(), event_commandscript::HandleEventActiveListCommand(), event_commandscript::HandleEventInfoCommand(), event_commandscript::HandleEventStartCommand(), event_commandscript::HandleEventStopCommand(), cheat_commandscript::HandleExploreCheatCommand(), misc_commandscript::HandleFreezeCommand(), gobject_commandscript::HandleGameObjectActivateCommand(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectDeleteCommand(), gobject_commandscript::HandleGameObjectInfoCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectSetPhaseCommand(), gobject_commandscript::HandleGameObjectSetStateCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGetDistanceCommand(), gm_commandscript::HandleGMChatCommand(), go_commandscript::HandleGoCreatureCIdCommand(), go_commandscript::HandleGoCreatureSpawnIdCommand(), go_commandscript::HandleGoGameObjectGOIdCommand(), go_commandscript::HandleGoGameObjectSpawnIdCommand(), go_commandscript::HandleGoGraveyardCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoTaxinodeCommand(), go_commandscript::HandleGoTriggerCommand(), go_commandscript::HandleGoXYZCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupSummonCommand(), misc_commandscript::HandleGUIDCommand(), guild_commandscript::HandleGuildCreateCommand(), misc_commandscript::HandleHideAreaCommand(), honor_commandscript::HandleHonorAddCommand(), honor_commandscript::HandleHonorAddKillCommand(), honor_commandscript::HandleHonorUpdateCommand(), instance_commandscript::HandleInstanceGetBossStateCommand(), instance_commandscript::HandleInstanceSaveDataCommand(), instance_commandscript::HandleInstanceSetBossStateCommand(), instance_commandscript::HandleInstanceStatsCommand(), misc_commandscript::HandleInventoryCountCommand(), misc_commandscript::HandleKickPlayerCommand(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), learn_commandscript::HandleLearnCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), misc_commandscript::HandleLinkGraveCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListItemCommand(), list_commandscript::HandleListObjectCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), misc_commandscript::HandleMaxSkillCommand(), modify_commandscript::HandleModifyArenaCommand(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBitCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyEnergyCommand(), modify_commandscript::HandleModifyFactionCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifyGenderCommand(), modify_commandscript::HandleModifyHonorCommand(), modify_commandscript::HandleModifyHPCommand(), modify_commandscript::HandleModifyManaCommand(), modify_commandscript::HandleModifyMoneyCommand(), modify_commandscript::HandleModifyMountCommand(), modify_commandscript::HandleModifyRageCommand(), modify_commandscript::HandleModifyRepCommand(), modify_commandscript::HandleModifyRunicPowerCommand(), modify_commandscript::HandleModifyScaleCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySpellCommand(), modify_commandscript::HandleModifySwimCommand(), modify_commandscript::HandleModifyTalentCommand(), misc_commandscript::HandleMovegensCommand(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandleMuteInfoCommand(), misc_commandscript::HandleNearGraveCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcAddVendorItemCommand(), npc_commandscript::HandleNpcDeleteCommand(), npc_commandscript::HandleNpcDeleteVendorItemCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcPlayEmoteCommand(), npc_commandscript::HandleNpcSayCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetEntryCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcSetLevelCommand(), npc_commandscript::HandleNpcSetLinkCommand(), npc_commandscript::HandleNpcSetModelCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetPhaseCommand(), npc_commandscript::HandleNpcTameCommand(), npc_commandscript::HandleNpcTextEmoteCommand(), npc_commandscript::HandleNpcUnFollowCommand(), npc_commandscript::HandleNpcWhisperCommand(), npc_commandscript::HandleNpcYellCommand(), character_commandscript::HandlePDumpLoadCommand(), character_commandscript::HandlePDumpWriteCommand(), misc_commandscript::HandlePetLearnCommand(), misc_commandscript::HandlePetUnlearnCommand(), misc_commandscript::HandlePlayAllCommand(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), misc_commandscript::HandleRecallCommand(), reload_commandscript::HandleReloadAllScriptsCommand(), reload_commandscript::HandleReloadCommandCommand(), reload_commandscript::HandleReloadEventScriptsCommand(), reload_commandscript::HandleReloadSpellScriptsCommand(), reload_commandscript::HandleReloadWardenactionCommand(), reload_commandscript::HandleReloadWpScriptsCommand(), disable_commandscript::HandleRemoveDisables(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetTalentsCommand(), misc_commandscript::HandleRespawnCommand(), misc_commandscript::HandleSendItemsCommand(), server_commandscript::HandleServerSetClosedCommand(), misc_commandscript::HandleSetSkillCommand(), misc_commandscript::HandleShowAreaCommand(), misc_commandscript::HandleSkirmishCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), tele_commandscript::HandleTeleCommand(), tele_commandscript::HandleTeleDelCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), misc_commandscript::HandleUnAuraCommand(), ban_commandscript::HandleUnBanCharacterCommand(), ban_commandscript::HandleUnBanHelper(), learn_commandscript::HandleUnLearnCommand(), misc_commandscript::HandleUnmuteCommand(), message_commandscript::HandleWhispersCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpShowCommand(), HasLowerSecurity(), HasLowerSecurityAccount(), list_commandscript::ListAurasCommand(), lookup_commandscript::LookupPlayerSearchCommand(), Acore::Impl::ChatCommands::SendErrorMessageToHandler(), Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand(), and character_commandscript::ValidatePDumpTarget().
Member Data Documentation
m_session
WorldSession* ChatHandler::m_session private
Definition at line 128 of file Chat.h.
Referenced by _ParseCommands(), GetAcoreString(), GetCreatureFromPlayerMapByDbGuid(), GetNearbyGameObject(), GetObjectFromPlayerMapByDbGuid(), GetPlayer(), GetPlayerGroupAndGUIDByName(), getSelectedCreature(), getSelectedObject(), getSelectedPlayer(), getSelectedPlayerOrSelf(), getSelectedUnit(), GetSessionDbcLocale(), GetSessionDbLocaleIndex(), HasLowerSecurityAccount(), IsAvailable(), needReportToTarget(), and SendSysMessage().
sentErrorMessage
bool ChatHandler::sentErrorMessage private
Definition at line 131 of file Chat.h.
The documentation for this class was generated from the following files:
src/server/game/Chat/Chat.h
src/server/game/Chat/Chat.cpp