Azerotcore-wotlk: value< Context > Class Template Reference
value< Context > Class Template Reference
#include <core.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
constexpr FMT_INLINE value ()
constexpr FMT_INLINE value (int val)
constexpr FMT_INLINE value (unsigned val)
constexpr FMT_INLINE value (long long val)
constexpr FMT_INLINE value (unsigned long long val)
FMT_INLINE value (int128_t val)
FMT_INLINE value (uint128_t val)
FMT_INLINE value (float val)
FMT_INLINE value (double val)
FMT_INLINE value (long double val)
constexpr FMT_INLINE value (bool val)
constexpr FMT_INLINE value (char_type val)
FMT_CONSTEXPR FMT_INLINE value (const char_type *val)
FMT_CONSTEXPR FMT_INLINE value (basic_string_view< char_type > val)
FMT_INLINE value (const void *val)
FMT_INLINE value (const named_arg_info< char_type > *args, size_t size)
template<typename T >
FMT_CONSTEXPR FMT_INLINE value (const T &val)
Public Attributes
union {
monostate no_value
int int_value
unsigned uint_value
long long long_long_value
unsigned long long ulong_long_value
int128_t int128_value
uint128_t uint128_value
bool bool_value
char_type char_value
float float_value
double double_value
long double long_double_value
const void * pointer
string_value< char_type > string
custom_value< Context > custom
named_arg_value< char_type > named_args
};
Static Private Member Functions
template<typename T , typename Formatter >
static void format_custom_arg (const void *arg, typename Context::parse_context_type &parse_ctx, Context &ctx)
Detailed Description
template<typename Context>
class value< Context >
Definition at line 1120 of file core.h.
Member Typedef Documentation
char_type
template<typename Context > using value< Context >::char_type = typename Context::char_type
Definition at line 1122 of file core.h.
Constructor & Destructor Documentation
value() [1/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value () inline constexpr
Definition at line 1143 of file core.h.
 : no_value() {}
Referenced by ansi_color_escape< Char >::ansi_color_escape(), G3D::Color1::Color1(), format_uint(), AchievementCriteriaData::IsValid(), AchievementCriteriaData::Meets(), and detail::dynamic_arg_list::push().
value() [2/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (int val) inline constexpr
Definition at line 1144 of file core.h.
 : int_value(val) {}
value() [3/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (unsigned val) inline constexpr
Definition at line 1145 of file core.h.
 : uint_value(val) {}
value() [4/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (long long val) inline constexpr
Definition at line 1146 of file core.h.
 : long_long_value(val) {}
value() [5/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (unsigned long long val) inline constexpr
Definition at line 1147 of file core.h.
 : ulong_long_value(val) {}
value() [6/17]
template<typename Context > FMT_INLINE value< Context >::value (int128_t val) inline
Definition at line 1148 of file core.h.
 : int128_value(val) {}
value() [7/17]
template<typename Context > FMT_INLINE value< Context >::value (uint128_t val) inline
Definition at line 1149 of file core.h.
 : uint128_value(val) {}
value() [8/17]
template<typename Context > FMT_INLINE value< Context >::value (float val) inline
Definition at line 1150 of file core.h.
 : float_value(val) {}
value() [9/17]
template<typename Context > FMT_INLINE value< Context >::value (double val) inline
Definition at line 1151 of file core.h.
 : double_value(val) {}
value() [10/17]
template<typename Context > FMT_INLINE value< Context >::value (long double val) inline
Definition at line 1152 of file core.h.
 : long_double_value(val) {}
value() [11/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (bool val) inline constexpr
Definition at line 1153 of file core.h.
 : bool_value(val) {}
value() [12/17]
template<typename Context > constexpr FMT_INLINE value< Context >::value (char_type val) inline constexpr
Definition at line 1154 of file core.h.
 : char_value(val) {}
value() [13/17]
template<typename Context > FMT_CONSTEXPR FMT_INLINE value< Context >::value (const char_type * val) inline
Definition at line 1155 of file core.h.
{
     string.data = val;
     if (is_constant_evaluated()) string.size = {};
   }
References is_constant_evaluated().
value() [14/17]
template<typename Context > FMT_CONSTEXPR FMT_INLINE value< Context >::value (basic_string_view< char_type > val) inline
Definition at line 1159 of file core.h.
{
     string.data = val.data();
     string.size = val.size();
   }
References basic_string_view< Char >::data(), and basic_string_view< Char >::size().
value() [15/17]
template<typename Context > FMT_INLINE value< Context >::value (const void * val) inline
Definition at line 1163 of file core.h.
 : pointer(val) {}
value() [16/17]
template<typename Context > FMT_INLINE value< Context >::value (const named_arg_info< char_type > * args, size_t size) inline
Definition at line 1164 of file core.h.
       : named_args{args, size} {}
value() [17/17]
template<typename Context > template<typename T > FMT_CONSTEXPR FMT_INLINE value< Context >::value (const T & val) inline
Definition at line 1167 of file core.h.
{
     custom.value = &val;
     // Get the formatter type through the context to allow different contexts
     // have different extension points, e.g. `formatter<T>` for `format` and
     // `printf_formatter<T>` for `printf`.
     custom.format = format_custom_arg<
         T, conditional_t<has_formatter<T, Context>::value,
                          typename Context::template formatter_type<T>,
                          fallback_formatter<T, char_type>>>;
   }
References value< Context >::custom, and value< Context >::format_custom_arg().
Member Function Documentation
format_custom_arg()
template<typename Context > template<typename T , typename Formatter > static void value< Context >::format_custom_arg (const void * arg, typename Context::parse_context_type & parse_ctx, Context & ctx) inline static private
Definition at line 1181 of file core.h.
{
     Formatter f;
     parse_ctx.advance_to(f.parse(parse_ctx));
     ctx.advance_to(f.format(*static_cast<const T*>(arg), ctx));
   }
References arg(), and f().
Referenced by value< Context >::value().
Member Data Documentation
union { ... }
bool_value
template<typename Context > bool value< Context >::bool_value
Definition at line 1132 of file core.h.
char_value
template<typename Context > char_type value< Context >::char_value
Definition at line 1133 of file core.h.
custom
template<typename Context > custom_value<Context> value< Context >::custom
Definition at line 1139 of file core.h.
Referenced by value< Context >::value().
double_value
template<typename Context > double value< Context >::double_value
Definition at line 1135 of file core.h.
float_value
template<typename Context > float value< Context >::float_value
Definition at line 1134 of file core.h.
int128_value
template<typename Context > int128_t value< Context >::int128_value
Definition at line 1130 of file core.h.
int_value
template<typename Context > int value< Context >::int_value
Definition at line 1126 of file core.h.
long_double_value
template<typename Context > long double value< Context >::long_double_value
Definition at line 1136 of file core.h.
long_long_value
template<typename Context > long long value< Context >::long_long_value
Definition at line 1128 of file core.h.
named_args
template<typename Context > named_arg_value<char_type> value< Context >::named_args
Definition at line 1140 of file core.h.
no_value
template<typename Context > monostate value< Context >::no_value
Definition at line 1125 of file core.h.
pointer
template<typename Context > const void* value< Context >::pointer
Definition at line 1137 of file core.h.
string
template<typename Context > string_value<char_type> value< Context >::string
Definition at line 1138 of file core.h.
uint128_value
template<typename Context > uint128_t value< Context >::uint128_value
Definition at line 1131 of file core.h.
uint_value
template<typename Context > unsigned value< Context >::uint_value
Definition at line 1127 of file core.h.
ulong_long_value
template<typename Context > unsigned long long value< Context >::ulong_long_value
Definition at line 1129 of file core.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h