Azerotcore-wotlk: SpellCastTargets Class Reference
SpellCastTargets Class Reference
#include <Spell.h>
Public Member Functions
SpellCastTargets ()
~SpellCastTargets ()
void Read (ByteBuffer &data, Unit *caster)
void Write (ByteBuffer &data)
uint32 GetTargetMask () const
void SetTargetMask (uint32 newMask)
void SetTargetFlag (SpellCastTargetFlags flag)
ObjectGuid GetUnitTargetGUID () const
Unit * GetUnitTarget () const
void SetUnitTarget (Unit *target)
ObjectGuid GetGOTargetGUID () const
GameObject * GetGOTarget () const
void SetGOTarget (GameObject *target)
ObjectGuid GetCorpseTargetGUID () const
Corpse * GetCorpseTarget () const
void SetCorpseTarget (Corpse *target)
WorldObject * GetObjectTarget () const
ObjectGuid GetObjectTargetGUID () const
void RemoveObjectTarget ()
ObjectGuid GetItemTargetGUID () const
Item * GetItemTarget () const
uint32 GetItemTargetEntry () const
void SetItemTarget (Item *item)
void SetTradeItemTarget (Player *caster)
void UpdateTradeSlotItem ()
SpellDestination const * GetSrc () const
Position const * GetSrcPos () const
void SetSrc (float x, float y, float z)
void SetSrc (Position const &pos)
void SetSrc (WorldObject const &wObj)
void ModSrc (Position const &pos)
void RemoveSrc ()
SpellDestination const * GetDst () const
WorldLocation const * GetDstPos () const
void SetDst (float x, float y, float z, float orientation, uint32 mapId=MAPID_INVALID)
void SetDst (Position const &pos)
void SetDst (WorldObject const &wObj)
void SetDst (SpellDestination const &spellDest)
void SetDst (SpellCastTargets const &spellTargets)
void ModDst (Position const &pos)
void ModDst (SpellDestination const &spellDest)
void RemoveDst ()
bool HasSrc () const
bool HasDst () const
bool HasTraj () const
float GetElevation () const
void SetElevation (float elevation)
float GetSpeed () const
void SetSpeed (float speed)
float GetDist2d () const
float GetSpeedXY () const
float GetSpeedZ () const
void Update (Unit *caster)
void OutDebug () const
void SetObjectTargetChannel (ObjectGuid targetGUID)
void SetDstChannel (SpellDestination const &spellDest)
WorldObject * GetObjectTargetChannel (Unit *caster) const
bool HasDstChannel () const
SpellDestination const * GetDstChannel () const
Private Attributes
uint32 m_targetMask
WorldObject * m_objectTarget
Item * m_itemTarget
ObjectGuid m_objectTargetGUID
ObjectGuid m_itemTargetGUID
uint32 m_itemTargetEntry
SpellDestination m_src
SpellDestination m_dst
float m_elevation
float m_speed
std::string m_strTarget
SpellDestination m_dstChannel
ObjectGuid m_objectTargetGUIDChannel
Detailed Description
Definition at line 108 of file Spell.h.
Constructor & Destructor Documentation
SpellCastTargets()
SpellCastTargets::SpellCastTargets ()
Definition at line 114 of file Spell.cpp.
                                    : m_elevation(0), m_speed(0), m_strTarget()
 {
     m_objectTarget = nullptr;
     m_itemTarget = nullptr;
     m_itemTargetEntry  = 0;
     m_targetMask = 0;
 }
References m_itemTarget, m_itemTargetEntry, m_objectTarget, and m_targetMask.
~SpellCastTargets()
SpellCastTargets::~SpellCastTargets ()
Definition at line 124 of file Spell.cpp.
 {
 }
Member Function Documentation
GetCorpseTarget()
Corpse * SpellCastTargets::GetCorpseTarget () const
Definition at line 296 of file Spell.cpp.
 {
     if (m_objectTarget)
         return m_objectTarget->ToCorpse();
     return nullptr;
 }
References m_objectTarget, and Object::ToCorpse().
Referenced by Spell::SelectEffectTypeImplicitTargets().
GetCorpseTargetGUID()
ObjectGuid SpellCastTargets::GetCorpseTargetGUID () const
Definition at line 283 of file Spell.cpp.
 {
     switch (m_objectTargetGUID.GetHigh())
     {
         case HighGuid::Corpse:
             return m_objectTargetGUID;
         default:
             break;
     }
     return ObjectGuid::Empty;
 }
References Corpse, ObjectGuid::Empty, ObjectGuid::GetHigh(), and m_objectTargetGUID.
Referenced by Spell::CheckEffectTarget().
GetDist2d()
float SpellCastTargets::GetDist2d () const inline
Definition at line 173 of file Spell.h.
 { return m_src._position.GetExactDist2d(&m_dst._position); }
References SpellDestination::_position, Position::GetExactDist2d(), m_dst, and m_src.
Referenced by Spell::CalculateDelayMomentForDst(), and Spell::SelectImplicitTrajTargets().
GetDst()
SpellDestination const * SpellCastTargets::GetDst () const
Definition at line 398 of file Spell.cpp.
 {
     return &m_dst;
 }
References m_dst.
Referenced by Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTrajTargets(), and Spell::SelectSpellTargets().
GetDstChannel()
SpellDestination const * SpellCastTargets::GetDstChannel () const
Definition at line 476 of file Spell.cpp.
 {
     return &m_dstChannel;
 }
References m_dstChannel.
Referenced by Spell::SelectImplicitChannelTargets().
GetDstPos()
WorldLocation const * SpellCastTargets::GetDstPos () const
Definition at line 403 of file Spell.cpp.
 {
     return &m_dst._position;
 }
References SpellDestination::_position, and m_dst.
Referenced by Spell::CalculateDelayMomentForDst(), Spell::CheckCast(), Spell::CheckEffectTarget(), Spell::CheckRange(), SpellScript::GetExplTargetDest(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Spell::SelectImplicitAreaTargets(), and Spell::SelectImplicitTrajTargets().
GetElevation()
float SpellCastTargets::GetElevation () const inline
Definition at line 168 of file Spell.h.
 { return m_elevation; }
References m_elevation.
Referenced by spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), Spell::SelectImplicitTrajTargets(), and Spell::SendSpellGo().
GetGOTarget()
GameObject * SpellCastTargets::GetGOTarget () const
Definition at line 266 of file Spell.cpp.
 {
     if (m_objectTarget)
         return m_objectTarget->ToGameObject();
     return nullptr;
 }
References m_objectTarget, and Object::ToGameObject().
Referenced by Spell::CheckCast(), Spell::CheckRange(), SpellScript::GetExplTargetGObj(), WorldSession::HandleCastSpellOpcode(), Spell::OnSpellLaunch(), and Spell::SelectEffectTypeImplicitTargets().
GetGOTargetGUID()
ObjectGuid SpellCastTargets::GetGOTargetGUID () const
Definition at line 251 of file Spell.cpp.
 {
     switch (m_objectTargetGUID.GetHigh())
     {
         case HighGuid::Transport:
         case HighGuid::Mo_Transport:
         case HighGuid::GameObject:
             return m_objectTargetGUID;
         default:
             break;
     }
     return ObjectGuid::Empty;
 }
References ObjectGuid::Empty, GameObject, ObjectGuid::GetHigh(), m_objectTargetGUID, Mo_Transport, and Transport.
GetItemTarget()
Item* SpellCastTargets::GetItemTarget () const inline
Definition at line 139 of file Spell.h.
 { return m_itemTarget; }
References m_itemTarget.
Referenced by Spell::_cast(), Spell::CheckCast(), Spell::CheckItems(), Spell::EffectSummonChangeItem(), SpellScript::GetExplTargetItem(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitTargetObjectTargets(), and Spell::TakeCastItem().
GetItemTargetEntry()
uint32 SpellCastTargets::GetItemTargetEntry () const inline
Definition at line 140 of file Spell.h.
 { return m_itemTargetEntry; }
References m_itemTargetEntry.
Referenced by Spell::CheckItems(), and Spell::TakeReagents().
GetItemTargetGUID()
ObjectGuid SpellCastTargets::GetItemTargetGUID () const inline
Definition at line 138 of file Spell.h.
 { return m_itemTargetGUID; }
References m_itemTargetGUID.
Referenced by Spell::CheckCast(), and Spell::CheckItems().
GetObjectTarget()
WorldObject * SpellCastTargets::GetObjectTarget () const
Definition at line 313 of file Spell.cpp.
 {
     return m_objectTarget;
 }
References m_objectTarget.
Referenced by Spell::_cast(), Spell::CheckCast(), SpellScript::GetExplTargetWorldObject(), Spell::InitExplicitTargets(), Spell::prepare(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitTargetDestTargets(), and Spell::SelectImplicitTargetObjectTargets().
GetObjectTargetChannel()
WorldObject * SpellCastTargets::GetObjectTargetChannel (Unit * caster) const
Definition at line 466 of file Spell.cpp.
 {
     return m_objectTargetGUIDChannel ? ((m_objectTargetGUIDChannel == caster->GetGUID()) ? caster : ObjectAccessor::GetWorldObject(*caster, m_objectTargetGUIDChannel)) : nullptr;
 }
References Object::GetGUID(), ObjectAccessor::GetWorldObject(), and m_objectTargetGUIDChannel.
Referenced by Spell::SelectImplicitChannelTargets().
GetObjectTargetGUID()
ObjectGuid SpellCastTargets::GetObjectTargetGUID () const
Definition at line 318 of file Spell.cpp.
 {
     return m_objectTargetGUID;
 }
References m_objectTargetGUID.
Referenced by Spell::_cast(), and Spell::SendChannelStart().
GetSpeed()
float SpellCastTargets::GetSpeed () const inline
Definition at line 170 of file Spell.h.
 { return m_speed; }
References m_speed.
GetSpeedXY()
float SpellCastTargets::GetSpeedXY () const inline
Definition at line 174 of file Spell.h.
 { return m_speed * cos(m_elevation); }
References m_elevation, and m_speed.
Referenced by Spell::CalculateDelayMomentForDst(), and spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript().
GetSpeedZ()
float SpellCastTargets::GetSpeedZ () const inline
Definition at line 175 of file Spell.h.
 { return m_speed * sin(m_elevation); }
References m_elevation, and m_speed.
Referenced by spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript().
GetSrc()
SpellDestination const * SpellCastTargets::GetSrc () const
Definition at line 359 of file Spell.cpp.
 {
     return &m_src;
 }
References m_src.
GetSrcPos()
Position const * SpellCastTargets::GetSrcPos () const
Definition at line 364 of file Spell.cpp.
 {
     return &m_src._position;
 }
References SpellDestination::_position, and m_src.
Referenced by WorldSession::HandleUpdateMissileTrajectory(), Spell::SelectImplicitAreaTargets(), and Spell::SelectImplicitTrajTargets().
GetTargetMask()
uint32 SpellCastTargets::GetTargetMask () const inline
Definition at line 117 of file Spell.h.
 { return m_targetMask; }
References m_targetMask.
Referenced by Spell::_cast(), Spell::CheckCast(), HasDst(), HasSrc(), Spell::prepare(), and Spell::SendSpellGo().
GetUnitTarget()
Unit * SpellCastTargets::GetUnitTarget () const
Definition at line 234 of file Spell.cpp.
 {
     if (m_objectTarget)
         return m_objectTarget->ToUnit();
     return nullptr;
 }
References m_objectTarget, and Object::ToUnit().
Referenced by Spell::_cast(), Spell::_handle_finish_phase(), Spell::CheckCast(), Spell::CheckItems(), Spell::CheckPetCast(), Spell::CheckRange(), Spell::DoSpellHitOnUnit(), Spell::EffectTeleportUnits(), Spell::EffectTriggerSpell(), SpellScript::GetExplTargetUnit(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), item_gor_dreks_ointment::OnUse(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectExplicitTargets(), Spell::SelectImplicitAreaTargets(), Spell::SelectImplicitNearbyTargets(), and Spell::update().
GetUnitTargetGUID()
ObjectGuid SpellCastTargets::GetUnitTargetGUID () const
Definition at line 218 of file Spell.cpp.
 {
     switch (m_objectTargetGUID.GetHigh())
     {
         case HighGuid::Player:
         case HighGuid::Vehicle:
         case HighGuid::Unit:
         case HighGuid::Pet:
             return m_objectTargetGUID;
         default:
             break;
     }
     return ObjectGuid::Empty;
 }
References ObjectGuid::Empty, ObjectGuid::GetHigh(), m_objectTargetGUID, Pet, Player, Unit, and Vehicle.
Referenced by Spell::DoAllEffectOnTarget(), Spell::TakePower(), and Spell::update().
HasDst()
bool SpellCastTargets::HasDst () const inline
Definition at line 165 of file Spell.h.
 { return GetTargetMask() & TARGET_FLAG_DEST_LOCATION; }
References GetTargetMask(), and TARGET_FLAG_DEST_LOCATION.
Referenced by Spell::CalculateDelayMomentForDst(), Spell::CheckCast(), Spell::CheckDst(), Spell::CheckEffectTarget(), Spell::CheckRange(), Spell::EffectBind(), Spell::EffectChargeDest(), Spell::EffectJumpDest(), Spell::EffectKnockBack(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTeleportUnits(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), SpellScript::GetExplTargetDest(), Spell::handle_delayed(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Spell::InitExplicitTargets(), Spell::prepare(), Spell::SelectSpellTargets(), Update(), and Spell::UpdatePointers().
HasDstChannel()
bool SpellCastTargets::HasDstChannel () const
Definition at line 471 of file Spell.cpp.
 {
     return m_dstChannel._position.GetExactDist(0, 0, 0) > 0.001f;
 }
References SpellDestination::_position, Position::GetExactDist(), and m_dstChannel.
Referenced by Spell::SelectImplicitChannelTargets().
HasSrc()
bool SpellCastTargets::HasSrc () const inline
Definition at line 164 of file Spell.h.
 { return GetTargetMask() & TARGET_FLAG_SOURCE_LOCATION; }
References GetTargetMask(), and TARGET_FLAG_SOURCE_LOCATION.
Referenced by Spell::CheckSrc(), WorldSession::HandleUpdateMissileTrajectory(), Spell::InitExplicitTargets(), and Update().
HasTraj()
bool SpellCastTargets::HasTraj () const inline
Definition at line 166 of file Spell.h.
 { return m_speed != 0; }
References m_speed.
Referenced by Spell::CalculateDelayMomentForDst(), Spell::CheckRange(), Spell::SelectImplicitTrajTargets(), and Spell::SendSpellGo().
ModDst() [1/2]
void SpellCastTargets::ModDst (Position const & pos)
Definition at line 438 of file Spell.cpp.
 {
     ASSERT(m_targetMask & TARGET_FLAG_DEST_LOCATION);
     m_dst.Relocate(pos);
 }
References ASSERT, m_dst, m_targetMask, SpellDestination::Relocate(), and TARGET_FLAG_DEST_LOCATION.
Referenced by WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Spell::SelectImplicitDestDestTargets(), and Spell::SelectImplicitTrajTargets().
ModDst() [2/2]
void SpellCastTargets::ModDst (SpellDestination const & spellDest)
Definition at line 444 of file Spell.cpp.
 {
     ASSERT(m_targetMask & TARGET_FLAG_DEST_LOCATION);
     m_dst = spellDest;
 }
References ASSERT, m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
ModSrc()
void SpellCastTargets::ModSrc (Position const & pos)
Definition at line 387 of file Spell.cpp.
 {
     ASSERT(m_targetMask & TARGET_FLAG_SOURCE_LOCATION);
     m_src.Relocate(pos);
 }
References ASSERT, m_src, m_targetMask, SpellDestination::Relocate(), and TARGET_FLAG_SOURCE_LOCATION.
Referenced by WorldSession::HandleUpdateMissileTrajectory().
OutDebug()
void SpellCastTargets::OutDebug () const
Definition at line 534 of file Spell.cpp.
 {
     if (!m_targetMask)
         LOG_INFO("spells", "No targets");
     LOG_INFO("spells", "target mask: %u", m_targetMask);
     if (m_targetMask & (TARGET_FLAG_UNIT_MASK | TARGET_FLAG_CORPSE_MASK | TARGET_FLAG_GAMEOBJECT_MASK))
         LOG_INFO("spells", "Object target: %s", m_objectTargetGUID.ToString().c_str());
     if (m_targetMask & TARGET_FLAG_ITEM)
         LOG_INFO("spells", "Item target: %s", m_itemTargetGUID.ToString().c_str());
     if (m_targetMask & TARGET_FLAG_TRADE_ITEM)
         LOG_INFO("spells", "Trade item target: %s", m_itemTargetGUID.ToString().c_str());
     if (m_targetMask & TARGET_FLAG_SOURCE_LOCATION)
         LOG_INFO("spells", "Source location: transport guid: %s trans offset: %s position: %s",
             m_src._transportGUID.ToString().c_str(), m_src._transportOffset.ToString().c_str(), m_src._position.ToString().c_str());
     if (m_targetMask & TARGET_FLAG_DEST_LOCATION)
         LOG_INFO("spells", "Destination location: transport guid: %s trans offset: %s position: %s",
             m_dst._transportGUID.ToString().c_str(), m_dst._transportOffset.ToString().c_str(), m_dst._position.ToString().c_str());
     if (m_targetMask & TARGET_FLAG_STRING)
         LOG_INFO("spells", "String: %s", m_strTarget.c_str());
     LOG_INFO("spells", "speed: %f", m_speed);
     LOG_INFO("spells", "elevation: %f", m_elevation);
 }
References SpellDestination::_position, SpellDestination::_transportGUID, SpellDestination::_transportOffset, LOG_INFO, m_dst, m_elevation, m_itemTargetGUID, m_objectTargetGUID, m_speed, m_src, m_strTarget, m_targetMask, TARGET_FLAG_CORPSE_MASK, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT_MASK, TARGET_FLAG_ITEM, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_STRING, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT_MASK, Position::ToString(), and ObjectGuid::ToString().
Read()
void SpellCastTargets::Read (ByteBuffer & data, Unit * caster)
Definition at line 128 of file Spell.cpp.
 {
     data >> m_targetMask;
     if (m_targetMask == TARGET_FLAG_NONE)
         return;
     if (m_targetMask & (TARGET_FLAG_UNIT | TARGET_FLAG_UNIT_MINIPET | TARGET_FLAG_GAMEOBJECT | TARGET_FLAG_CORPSE_ENEMY | TARGET_FLAG_CORPSE_ALLY))
         data >> m_objectTargetGUID.ReadAsPacked();
     if (m_targetMask & (TARGET_FLAG_ITEM | TARGET_FLAG_TRADE_ITEM))
         data >> m_itemTargetGUID.ReadAsPacked();
     if (m_targetMask & TARGET_FLAG_SOURCE_LOCATION)
     {
         data >> m_src._transportGUID.ReadAsPacked();
         if (m_src._transportGUID)
             data >> m_src._transportOffset.PositionXYZStream();
         else
             data >> m_src._position.PositionXYZStream();
     }
     else
     {
         m_src._transportGUID = caster->GetTransGUID();
         if (m_src._transportGUID)
             m_src._transportOffset.Relocate(caster->GetTransOffsetX(), caster->GetTransOffsetY(), caster->GetTransOffsetZ(), caster->GetTransOffsetO());
         else
             m_src._position.Relocate(caster);
     }
     if (m_targetMask & TARGET_FLAG_DEST_LOCATION)
     {
         data >> m_dst._transportGUID.ReadAsPacked();
         if (m_dst._transportGUID)
             data >> m_dst._transportOffset.PositionXYZStream();
         else
             data >> m_dst._position.PositionXYZStream();
     }
     else
     {
         m_dst._transportGUID = caster->GetTransGUID();
         if (m_dst._transportGUID)
             m_dst._transportOffset.Relocate(caster->GetTransOffsetX(), caster->GetTransOffsetY(), caster->GetTransOffsetZ(), caster->GetTransOffsetO());
         else
             m_dst._position.Relocate(caster);
     }
     if (m_targetMask & TARGET_FLAG_STRING)
         data >> m_strTarget;
     Update(caster);
 }
References SpellDestination::_position, SpellDestination::_transportGUID, SpellDestination::_transportOffset, Unit::GetTransGUID(), WorldObject::GetTransOffsetO(), WorldObject::GetTransOffsetX(), WorldObject::GetTransOffsetY(), WorldObject::GetTransOffsetZ(), m_dst, m_itemTargetGUID, m_objectTargetGUID, m_src, m_strTarget, m_targetMask, Position::PositionXYZStream(), ObjectGuid::ReadAsPacked(), Position::Relocate(), TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_NONE, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_STRING, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_MINIPET, and Update().
Referenced by WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetCastSpellOpcode(), and WorldSession::HandleUseItemOpcode().
RemoveDst()
void SpellCastTargets::RemoveDst ()
Definition at line 450 of file Spell.cpp.
 {
     m_targetMask &= ~(TARGET_FLAG_DEST_LOCATION);
 }
References m_targetMask, and TARGET_FLAG_DEST_LOCATION.
Referenced by Spell::InitExplicitTargets().
RemoveObjectTarget()
void SpellCastTargets::RemoveObjectTarget ()
Definition at line 323 of file Spell.cpp.
 {
     m_objectTarget = nullptr;
     m_objectTargetGUID.Clear();
     m_targetMask &= ~(TARGET_FLAG_UNIT_MASK | TARGET_FLAG_CORPSE_MASK | TARGET_FLAG_GAMEOBJECT_MASK);
 }
References ObjectGuid::Clear(), m_objectTarget, m_objectTargetGUID, m_targetMask, TARGET_FLAG_CORPSE_MASK, TARGET_FLAG_GAMEOBJECT_MASK, and TARGET_FLAG_UNIT_MASK.
Referenced by Spell::InitExplicitTargets().
RemoveSrc()
void SpellCastTargets::RemoveSrc ()
Definition at line 393 of file Spell.cpp.
 {
     m_targetMask &= ~(TARGET_FLAG_SOURCE_LOCATION);
 }
References m_targetMask, and TARGET_FLAG_SOURCE_LOCATION.
Referenced by Spell::InitExplicitTargets().
SetCorpseTarget()
void SpellCastTargets::SetCorpseTarget (Corpse * target)
Definition at line 303 of file Spell.cpp.
 {
     if (!target)
         return;
     m_objectTarget = target;
     m_objectTargetGUID = target->GetGUID();
     m_targetMask |= TARGET_FLAG_CORPSE_MASK;
 }
References Object::GetGUID(), m_objectTarget, m_objectTargetGUID, m_targetMask, and TARGET_FLAG_CORPSE_MASK.
SetDst() [1/5]
void SpellCastTargets::SetDst (float x, float y, float z, float orientation, uint32 mapId = MAPID_INVALID)
Definition at line 408 of file Spell.cpp.
 {
     m_dst = SpellDestination(x, y, z, orientation, mapId);
     m_targetMask |= TARGET_FLAG_DEST_LOCATION;
 }
References m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
Referenced by spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), Unit::CastSpell(), Spell::CheckDst(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), spell_dk_raise_dead::HandleRaiseDead(), Spell::InitExplicitTargets(), spell_quest_dragonmaw_race_generic::RelocateDest(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitChannelTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SelectImplicitTargetDestTargets(), and SpellScript::SetExplTargetDest().
SetDst() [2/5]
void SpellCastTargets::SetDst (Position const & pos)
Definition at line 414 of file Spell.cpp.
 {
     m_dst = SpellDestination(pos);
     m_targetMask |= TARGET_FLAG_DEST_LOCATION;
 }
References m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
SetDst() [3/5]
void SpellCastTargets::SetDst (SpellCastTargets const & spellTargets)
Definition at line 432 of file Spell.cpp.
 {
     m_dst = spellTargets.m_dst;
     m_targetMask |= TARGET_FLAG_DEST_LOCATION;
 }
References m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
SetDst() [4/5]
void SpellCastTargets::SetDst (SpellDestination const & spellDest)
Definition at line 426 of file Spell.cpp.
 {
     m_dst = spellDest;
     m_targetMask |= TARGET_FLAG_DEST_LOCATION;
 }
References m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
SetDst() [5/5]
void SpellCastTargets::SetDst (WorldObject const & wObj)
Definition at line 420 of file Spell.cpp.
 {
     m_dst = SpellDestination(wObj);
     m_targetMask |= TARGET_FLAG_DEST_LOCATION;
 }
References m_dst, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
SetDstChannel()
void SpellCastTargets::SetDstChannel (SpellDestination const & spellDest)
Definition at line 461 of file Spell.cpp.
 {
     m_dstChannel = spellDest;
 }
References m_dstChannel.
Referenced by AuraEffect::HandlePeriodicTriggerSpellAuraTick(), and AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick().
SetElevation()
void SpellCastTargets::SetElevation (float elevation) inline
Definition at line 169 of file Spell.h.
 { m_elevation = elevation; }
References m_elevation.
Referenced by WorldSession::HandleClientCastFlags(), and WorldSession::HandleUpdateMissileTrajectory().
SetGOTarget()
void SpellCastTargets::SetGOTarget (GameObject * target)
Definition at line 273 of file Spell.cpp.
 {
     if (!target)
         return;
     m_objectTarget = target;
     m_objectTargetGUID = target->GetGUID();
     m_targetMask |= TARGET_FLAG_GAMEOBJECT;
 }
References Object::GetGUID(), m_objectTarget, m_objectTargetGUID, m_targetMask, and TARGET_FLAG_GAMEOBJECT.
Referenced by Unit::CastSpell().
SetItemTarget()
void SpellCastTargets::SetItemTarget (Item * item)
Definition at line 330 of file Spell.cpp.
 {
     if (!item)
         return;
     m_itemTarget = item;
     m_itemTargetGUID = item->GetGUID();
     m_itemTargetEntry = item->GetEntry();
     m_targetMask |= TARGET_FLAG_ITEM;
 }
References Object::GetEntry(), Object::GetGUID(), m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_targetMask, and TARGET_FLAG_ITEM.
Referenced by Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemTmp(), Spell::EffectSummonChangeItem(), Spell::TakeCastItem(), and Spell::TakeReagents().
SetObjectTargetChannel()
void SpellCastTargets::SetObjectTargetChannel (ObjectGuid targetGUID)
Definition at line 456 of file Spell.cpp.
 {
     m_objectTargetGUIDChannel = targetGUID;
 }
References m_objectTargetGUIDChannel.
Referenced by AuraEffect::HandlePeriodicTriggerSpellAuraTick(), and AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick().
SetSpeed()
void SpellCastTargets::SetSpeed (float speed) inline
Definition at line 171 of file Spell.h.
 { m_speed = speed; }
References m_speed.
Referenced by WorldSession::HandleClientCastFlags(), and WorldSession::HandleUpdateMissileTrajectory().
SetSrc() [1/3]
void SpellCastTargets::SetSrc (float x, float y, float z)
Definition at line 369 of file Spell.cpp.
 {
     m_src = SpellDestination(x, y, z);
     m_targetMask |= TARGET_FLAG_SOURCE_LOCATION;
 }
References m_src, m_targetMask, and TARGET_FLAG_SOURCE_LOCATION.
Referenced by Spell::CheckSrc(), Spell::InitExplicitTargets(), and Spell::SelectEffectImplicitTargets().
SetSrc() [2/3]
void SpellCastTargets::SetSrc (Position const & pos)
Definition at line 375 of file Spell.cpp.
 {
     m_src = SpellDestination(pos);
     m_targetMask |= TARGET_FLAG_SOURCE_LOCATION;
 }
References m_src, m_targetMask, and TARGET_FLAG_SOURCE_LOCATION.
SetSrc() [3/3]
void SpellCastTargets::SetSrc (WorldObject const & wObj)
Definition at line 381 of file Spell.cpp.
 {
     m_src = SpellDestination(wObj);
     m_targetMask |= TARGET_FLAG_SOURCE_LOCATION;
 }
References m_src, m_targetMask, and TARGET_FLAG_SOURCE_LOCATION.
SetTargetFlag()
void SpellCastTargets::SetTargetFlag (SpellCastTargetFlags flag) inline
Definition at line 120 of file Spell.h.
 { m_targetMask |= flag; }
References m_targetMask.
Referenced by Spell::SelectSpellTargets().
SetTargetMask()
void SpellCastTargets::SetTargetMask (uint32 newMask) inline
Definition at line 118 of file Spell.h.
 { m_targetMask = newMask; }
References m_targetMask.
SetTradeItemTarget()
void SpellCastTargets::SetTradeItemTarget (Player * caster)
Definition at line 341 of file Spell.cpp.
 {
     m_itemTargetGUID.Set(uint64(TRADE_SLOT_NONTRADED));
     m_itemTargetEntry = 0;
     m_targetMask |= TARGET_FLAG_TRADE_ITEM;
     Update(caster);
 }
References m_itemTargetEntry, m_itemTargetGUID, m_targetMask, ObjectGuid::Set(), TARGET_FLAG_TRADE_ITEM, TRADE_SLOT_NONTRADED, and Update().
Referenced by WorldSession::HandleAcceptTradeOpcode().
SetUnitTarget()
void SpellCastTargets::SetUnitTarget (Unit * target)
Definition at line 241 of file Spell.cpp.
 {
     if (!target)
         return;
     m_objectTarget = target;
     m_objectTargetGUID = target->GetGUID();
     m_targetMask |= TARGET_FLAG_UNIT;
 }
References Object::GetGUID(), m_objectTarget, m_objectTargetGUID, m_targetMask, and TARGET_FLAG_UNIT.
Referenced by Unit::CastCustomSpell(), Unit::CastSpell(), Spell::CheckPetCast(), Spell::EffectForceCast(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(), Spell::InitExplicitTargets(), Spell::SelectExplicitTargets(), Spell::SelectImplicitNearbyTargets(), and PetAI::UpdateAI().
Update()
void SpellCastTargets::Update (Unit * caster)
Definition at line 481 of file Spell.cpp.
 {
     m_objectTarget = m_objectTargetGUID ? ((m_objectTargetGUID == caster->GetGUID()) ? caster : ObjectAccessor::GetWorldObject(*caster, m_objectTargetGUID)) : nullptr;
     m_itemTarget = nullptr;
     if (caster->GetTypeId() == TYPEID_PLAYER)
     {
         Player* player = caster->ToPlayer();
         if (m_targetMask & TARGET_FLAG_ITEM)
             m_itemTarget = player->GetItemByGuid(m_itemTargetGUID);
         else if (m_targetMask & TARGET_FLAG_TRADE_ITEM)
             if (m_itemTargetGUID.GetRawValue() == TRADE_SLOT_NONTRADED) // here it is not guid but slot. Also prevents hacking slots
                 if (TradeData* pTrade = player->GetTradeData())
                     m_itemTarget = pTrade->GetTraderData()->GetItem(TRADE_SLOT_NONTRADED);
         if (m_itemTarget)
             m_itemTargetEntry = m_itemTarget->GetEntry();
     }
     // update positions by transport move
     if (HasSrc() && m_src._transportGUID)
     {
         if (WorldObject* transport = ObjectAccessor::GetWorldObject(*caster, m_src._transportGUID))
         {
             m_src._position.Relocate(transport);
             m_src._position.RelocateOffset(m_src._transportOffset);
         }
     }
     if (HasDst() && m_dst._transportGUID)
     {
         if (WorldObject* transport = ObjectAccessor::GetWorldObject(*caster, m_dst._transportGUID))
         {
             m_dst._position.Relocate(transport);
             m_dst._position.RelocateOffset(m_dst._transportOffset);
         }
     }
 }
References SpellDestination::_position, SpellDestination::_transportGUID, SpellDestination::_transportOffset, Object::GetEntry(), Object::GetGUID(), Player::GetItemByGuid(), ObjectGuid::GetRawValue(), Player::GetTradeData(), Object::GetTypeId(), ObjectAccessor::GetWorldObject(), HasDst(), HasSrc(), m_dst, m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_objectTarget, m_objectTargetGUID, m_src, m_targetMask, Position::Relocate(), Position::RelocateOffset(), TARGET_FLAG_ITEM, TARGET_FLAG_TRADE_ITEM, Object::ToPlayer(), TRADE_SLOT_NONTRADED, and TYPEID_PLAYER.
Referenced by Read(), SetTradeItemTarget(), and Spell::UpdatePointers().
UpdateTradeSlotItem()
void SpellCastTargets::UpdateTradeSlotItem ()
Definition at line 350 of file Spell.cpp.
 {
     if (m_itemTarget && (m_targetMask & TARGET_FLAG_TRADE_ITEM))
     {
         m_itemTargetGUID = m_itemTarget->GetGUID();
         m_itemTargetEntry = m_itemTarget->GetEntry();
     }
 }
References Object::GetEntry(), Object::GetGUID(), m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_targetMask, and TARGET_FLAG_TRADE_ITEM.
Referenced by Spell::_cast().
Write()
void SpellCastTargets::Write (ByteBuffer & data)
Definition at line 181 of file Spell.cpp.
 {
     data << uint32(m_targetMask);
     if (m_targetMask & (TARGET_FLAG_UNIT | TARGET_FLAG_CORPSE_ALLY | TARGET_FLAG_GAMEOBJECT | TARGET_FLAG_CORPSE_ENEMY | TARGET_FLAG_UNIT_MINIPET))
         data << m_objectTargetGUID.WriteAsPacked();
     if (m_targetMask & (TARGET_FLAG_ITEM | TARGET_FLAG_TRADE_ITEM))
     {
         if (m_itemTarget)
             data << m_itemTarget->GetPackGUID();
         else
             data << uint8(0);
     }
     if (m_targetMask & TARGET_FLAG_SOURCE_LOCATION)
     {
         data << m_src._transportGUID.WriteAsPacked(); // relative position guid here - transport for example
         if (m_src._transportGUID)
             data << m_src._transportOffset.PositionXYZStream();
         else
             data << m_src._position.PositionXYZStream();
     }
     if (m_targetMask & TARGET_FLAG_DEST_LOCATION)
     {
         data << m_dst._transportGUID.WriteAsPacked(); // relative position guid here - transport for example
         if (m_dst._transportGUID)
             data << m_dst._transportOffset.PositionXYZStream();
         else
             data << m_dst._position.PositionXYZStream();
     }
     if (m_targetMask & TARGET_FLAG_STRING)
         data << m_strTarget;
 }
References SpellDestination::_position, SpellDestination::_transportGUID, SpellDestination::_transportOffset, Object::GetPackGUID(), m_dst, m_itemTarget, m_objectTargetGUID, m_src, m_strTarget, m_targetMask, Position::PositionXYZStream(), TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_STRING, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_MINIPET, and ObjectGuid::WriteAsPacked().
Referenced by Spell::SendSpellGo(), and Spell::SendSpellStart().
Member Data Documentation
m_dst
SpellDestination SpellCastTargets::m_dst private
Definition at line 200 of file Spell.h.
Referenced by GetDist2d(), GetDst(), GetDstPos(), ModDst(), OutDebug(), Read(), SetDst(), Update(), and Write().
m_dstChannel
SpellDestination SpellCastTargets::m_dstChannel private
Definition at line 206 of file Spell.h.
Referenced by GetDstChannel(), HasDstChannel(), and SetDstChannel().
m_elevation
float SpellCastTargets::m_elevation private
Definition at line 202 of file Spell.h.
Referenced by GetElevation(), GetSpeedXY(), GetSpeedZ(), OutDebug(), and SetElevation().
m_itemTarget
Item* SpellCastTargets::m_itemTarget private
Definition at line 192 of file Spell.h.
Referenced by GetItemTarget(), SetItemTarget(), SpellCastTargets(), Update(), UpdateTradeSlotItem(), and Write().
m_itemTargetEntry
uint32 SpellCastTargets::m_itemTargetEntry private
Definition at line 197 of file Spell.h.
Referenced by GetItemTargetEntry(), SetItemTarget(), SetTradeItemTarget(), SpellCastTargets(), Update(), and UpdateTradeSlotItem().
m_itemTargetGUID
ObjectGuid SpellCastTargets::m_itemTargetGUID private
Definition at line 196 of file Spell.h.
Referenced by GetItemTargetGUID(), OutDebug(), Read(), SetItemTarget(), SetTradeItemTarget(), Update(), and UpdateTradeSlotItem().
m_objectTarget
WorldObject* SpellCastTargets::m_objectTarget private
Definition at line 191 of file Spell.h.
Referenced by GetCorpseTarget(), GetGOTarget(), GetObjectTarget(), GetUnitTarget(), RemoveObjectTarget(), SetCorpseTarget(), SetGOTarget(), SetUnitTarget(), SpellCastTargets(), and Update().
m_objectTargetGUID
ObjectGuid SpellCastTargets::m_objectTargetGUID private
Definition at line 195 of file Spell.h.
Referenced by GetCorpseTargetGUID(), GetGOTargetGUID(), GetObjectTargetGUID(), GetUnitTargetGUID(), OutDebug(), Read(), RemoveObjectTarget(), SetCorpseTarget(), SetGOTarget(), SetUnitTarget(), Update(), and Write().
m_objectTargetGUIDChannel
ObjectGuid SpellCastTargets::m_objectTargetGUIDChannel private
Definition at line 207 of file Spell.h.
Referenced by GetObjectTargetChannel(), and SetObjectTargetChannel().
m_speed
float SpellCastTargets::m_speed private
Definition at line 202 of file Spell.h.
Referenced by GetSpeed(), GetSpeedXY(), GetSpeedZ(), HasTraj(), OutDebug(), and SetSpeed().
m_src
SpellDestination SpellCastTargets::m_src private
Definition at line 199 of file Spell.h.
Referenced by GetDist2d(), GetSrc(), GetSrcPos(), ModSrc(), OutDebug(), Read(), SetSrc(), Update(), and Write().
m_strTarget
std::string SpellCastTargets::m_strTarget private
Definition at line 203 of file Spell.h.
Referenced by OutDebug(), Read(), and Write().
m_targetMask
uint32 SpellCastTargets::m_targetMask private
Definition at line 188 of file Spell.h.
Referenced by GetTargetMask(), ModDst(), ModSrc(), OutDebug(), Read(), RemoveDst(), RemoveObjectTarget(), RemoveSrc(), SetCorpseTarget(), SetDst(), SetGOTarget(), SetItemTarget(), SetSrc(), SetTargetFlag(), SetTargetMask(), SetTradeItemTarget(), SetUnitTarget(), SpellCastTargets(), Update(), UpdateTradeSlotItem(), and Write().
The documentation for this class was generated from the following files:
src/server/game/Spells/Spell.h
src/server/game/Spells/Spell.cpp