Azerotcore-wotlk: npc_wg_queue Class Reference
npc_wg_queue Class Reference
Classes
struct npc_wg_queueAI
Public Member Functions
npc_wg_queue ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *, uint32, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 272 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
npc_wg_queue()
npc_wg_queue::npc_wg_queue () inline
Definition at line 275 of file zone_wintergrasp.cpp.
 : CreatureScript("npc_wg_queue") { }
Member Function Documentation
GetAI()
CreatureAI* npc_wg_queue::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 385 of file zone_wintergrasp.cpp.
     {
         return new npc_wg_queueAI(creature);
     }
OnGossipHello()
bool npc_wg_queue::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 277 of file zone_wintergrasp.cpp.
     {
         if (!sWorld->getBoolConfig(CONFIG_MINIGOB_MANABONK))
             return false;
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (!wintergrasp)
             return true;
         if (wintergrasp->IsWarTime())
         {
             AddGossipItemFor(player, GOSSIP_ICON_CHAT_19, "Queue for Wintergrasp.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
             SendGossipMenuFor(player, wintergrasp->GetDefenderTeam() ? WG_NPCQUEUE_TEXT_H_WAR : WG_NPCQUEUE_TEXT_A_WAR, creature->GetGUID());
         }
         else
         {
             uint32 timer = wintergrasp->GetTimer() / 1000;
             player->SendUpdateWorldState(4354, time(nullptr) + timer);
             if (timer < 15 * MINUTE)
             {
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, "Queue for Wintergrasp.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 SendGossipMenuFor(player, wintergrasp->GetDefenderTeam() ? WG_NPCQUEUE_TEXT_H_QUEUE : WG_NPCQUEUE_TEXT_A_QUEUE, creature->GetGUID());
             }
             else
                 SendGossipMenuFor(player, wintergrasp->GetDefenderTeam() ? WG_NPCQUEUE_TEXT_H_NOWAR : WG_NPCQUEUE_TEXT_A_NOWAR, creature->GetGUID());
         }
         return true;
     }
References AddGossipItemFor(), BATTLEFIELD_BATTLEID_WG, CONFIG_MINIGOB_MANABONK, Battlefield::GetDefenderTeam(), Object::GetGUID(), Battlefield::GetTimer(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ICON_CHAT_19, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Battlefield::IsWarTime(), MINUTE, Player::PrepareQuestMenu(), sBattlefieldMgr, SendGossipMenuFor(), Player::SendUpdateWorldState(), sWorld, WG_NPCQUEUE_TEXT_A_NOWAR, WG_NPCQUEUE_TEXT_A_QUEUE, WG_NPCQUEUE_TEXT_A_WAR, WG_NPCQUEUE_TEXT_H_NOWAR, WG_NPCQUEUE_TEXT_H_QUEUE, and WG_NPCQUEUE_TEXT_H_WAR.
OnGossipSelect()
bool npc_wg_queue::OnGossipSelect (Player * player, Creature * , uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 309 of file zone_wintergrasp.cpp.
     {
         CloseGossipMenuFor(player);
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (!wintergrasp)
             return true;
         if (wintergrasp->IsWarTime())
             wintergrasp->InvitePlayerToWar(player);
         else
         {
             uint32 timer = wintergrasp->GetTimer() / 1000;
             if (timer < 15 * MINUTE)
                 wintergrasp->InvitePlayerToQueue(player);
         }
         return true;
     }
References BATTLEFIELD_BATTLEID_WG, CloseGossipMenuFor(), Battlefield::GetTimer(), Battlefield::InvitePlayerToQueue(), Battlefield::InvitePlayerToWar(), Battlefield::IsWarTime(), MINUTE, and sBattlefieldMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp