Azerotcore-wotlk: deps/mysqllite/mysys/mf_same.c File Reference
mf_same.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
char * fn_same (char *to, const char *name, int flag)
Function Documentation
fn_same()
char* fn_same (char * to, const char * name, int flag)
Definition at line 28 of file mf_same.c.
 {
   char dev[FN_REFLEN];
   const char *ext;
   size_t dev_length;
   DBUG_ENTER("fn_same");
   DBUG_PRINT("enter",("to: %s  name: %s  flag: %d",to,name,flag));
   if ((ext=strrchr(name+dirname_part(dev, name, &dev_length),FN_EXTCHAR)) == 0)
     ext="";
   DBUG_RETURN(fn_format(to,to,dev,ext,flag));
 } /* fn_same */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), FN_EXTCHAR, fn_format(), and FN_REFLEN.
Referenced by my_rename_with_symlink().