Azerotcore-wotlk: G3D::Set< T, HashFunc, EqualsFunc > Class Template Reference
G3D::Set< T, HashFunc, EqualsFunc > Class Template Reference
#include <Set.h>
Classes
class Iterator
Public Member Functions
void clearAndSetMemoryManager (const MemoryManager::Ref &m)
virtual ~Set ()
int size () const
bool contains (const T &member) const
bool insert (const T &member)
bool remove (const T &member)
bool getRemove (const T &member, T &removed)
const T * getPointer (const T &member) const
Array< T > getMembers () const
void getMembers (Array< T > &keyArray) const
void clear ()
void deleteAll ()
Iterator begin () const
const Iterator end () const
Private Attributes
Table< T, bool, HashFunc, EqualsFunc > memberTable
Detailed Description
template<class T, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>>
class G3D::Set< T, HashFunc, EqualsFunc >
An unordered data structure that has at most one of each element. Provides O(1) time insert, remove, and member test (contains).
Set uses G3D::Table internally, which means that the template type T must define a hashCode and operator== function. See G3D::Table for a discussion of these functions.
Definition at line 34 of file Set.h.
Constructor & Destructor Documentation
~Set()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> virtual G3D::Set< T, HashFunc, EqualsFunc >::~Set () inline virtual
Definition at line 48 of file Set.h.
 {}
Referenced by G3D::AnyTableReader::AnyTableReader().
Member Function Documentation
begin()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Iterator G3D::Set< T, HashFunc, EqualsFunc >::begin () const inline
C++ STL style iterator method. Returns the first member.
Use preincrement (++entry) to get to the next element.
Do not modify the set while iterating.
Definition at line 177 of file Set.h.
{
         return Iterator(memberTable.begin());
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::_internal::Welder::getIndex().
clear()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::Set< T, HashFunc, EqualsFunc >::clear () inline
Definition at line 101 of file Set.h.
                  {
         memberTable.clear();
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::Set< T, HashFunc, EqualsFunc >::deleteAll().
clearAndSetMemoryManager()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::Set< T, HashFunc, EqualsFunc >::clearAndSetMemoryManager (const MemoryManager::Ref & m) inline
Definition at line 44 of file Set.h.
{
         memberTable.clearAndSetMemoryManager(m);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
contains()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::Set< T, HashFunc, EqualsFunc >::contains (const T & member) const inline
Definition at line 54 of file Set.h.
{
         return memberTable.containsKey(member);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::AnyTableReader::containsUnread(), G3D::AnyTableReader::getIfPresent(), and G3D::TextInput::nextToken().
deleteAll()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::Set< T, HashFunc, EqualsFunc >::deleteAll () inline
Definition at line 105 of file Set.h.
                       {
         getMembers().deleteAll();
         clear();
     }
References G3D::Set< T, HashFunc, EqualsFunc >::clear(), and G3D::Set< T, HashFunc, EqualsFunc >::getMembers().
end()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> const Iterator G3D::Set< T, HashFunc, EqualsFunc >::end () const inline
C++ STL style iterator method. Returns one after the last iterator element.
Definition at line 186 of file Set.h.
{
         return Iterator(memberTable.end());
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::_internal::Welder::getIndex().
getMembers() [1/2]
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Array<T> G3D::Set< T, HashFunc, EqualsFunc >::getMembers () const inline
Definition at line 93 of file Set.h.
{
         return memberTable.getKeys();
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by BIHWrap< T, BoundsFunc >::balance(), G3D::Set< T, HashFunc, EqualsFunc >::deleteAll(), and G3D::getFileOrDirListZip().
getMembers() [2/2]
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::Set< T, HashFunc, EqualsFunc >::getMembers (Array< T > & keyArray) const inline
Definition at line 97 of file Set.h.
{
         memberTable.getKeys(keyArray);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
getPointer()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> const T* G3D::Set< T, HashFunc, EqualsFunc >::getPointer (const T & member) const inline
If a value that is EqualsFunc to member is present, returns a pointer to the version stored in the data structure, otherwise returns NULL.
Definition at line 89 of file Set.h.
{
         return memberTable.getKeyPointer(member);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
getRemove()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::Set< T, HashFunc, EqualsFunc >::getRemove (const T & member, T & removed) inline
If member is present, sets removed to the element being removed and returns true. Otherwise returns false and does not write to removed. This is useful when building efficient hashed data structures that wrap Set.
Definition at line 81 of file Set.h.
{
         bool ignore;
         return memberTable.getRemove(member, removed, ignore);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
insert()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::Set< T, HashFunc, EqualsFunc >::insert (const T & member) inline
Inserts into the table if not already present. Returns true if this is the first time the element was added.
Definition at line 62 of file Set.h.
{
         bool isNew = false;
         memberTable.getCreate(member, isNew) = true;
         return isNew;
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::FileSystem::Dir::computeZipListing(), G3D::AnyTableReader::get(), G3D::_internal::Welder::getIndex(), BIHWrap< T, BoundsFunc >::insert(), G3D::FileSystem::markFileUsed(), G3D::AnyTableReader::operator[](), and G3D::TextInput::Settings::Settings().
remove()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::Set< T, HashFunc, EqualsFunc >::remove (const T & member) inline
Returns true if the element was present and removed. Returns false if the element was not present.
Definition at line 72 of file Set.h.
{
         return memberTable.remove(member);
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by BIHWrap< T, BoundsFunc >::remove().
size()
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> int G3D::Set< T, HashFunc, EqualsFunc >::size () const inline
Definition at line 50 of file Set.h.
                      {
         return (int)memberTable.size();
     }
References G3D::Set< T, HashFunc, EqualsFunc >::memberTable.
Referenced by G3D::AnyTableReader::hasMore(), and G3D::TextInput::nextToken().
Member Data Documentation
memberTable
template<class T , class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Table<T, bool, HashFunc, EqualsFunc> G3D::Set< T, HashFunc, EqualsFunc >::memberTable private
If an object is a member, it is contained in this table.
Definition at line 40 of file Set.h.
Referenced by G3D::Set< T, HashFunc, EqualsFunc >::begin(), G3D::Set< T, HashFunc, EqualsFunc >::clear(), G3D::Set< T, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::Set< T, HashFunc, EqualsFunc >::contains(), G3D::Set< T, HashFunc, EqualsFunc >::end(), G3D::Set< T, HashFunc, EqualsFunc >::getMembers(), G3D::Set< T, HashFunc, EqualsFunc >::getPointer(), G3D::Set< T, HashFunc, EqualsFunc >::getRemove(), G3D::Set< T, HashFunc, EqualsFunc >::insert(), G3D::Set< T, HashFunc, EqualsFunc >::remove(), and G3D::Set< T, HashFunc, EqualsFunc >::size().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Set.h