Azerotcore-wotlk: text_style Class Reference
text_style Class Reference
#include <color.h>
Public Member Functions
FMT_CONSTEXPR text_style (emphasis em=emphasis()) FMT_NOEXCEPT
FMT_CONSTEXPR text_style & operator|= (const text_style &rhs)
FMT_DEPRECATED_NONMSVC FMT_CONSTEXPR text_style & operator&= (const text_style &rhs)
FMT_CONSTEXPR bool has_foreground () const FMT_NOEXCEPT
FMT_CONSTEXPR bool has_background () const FMT_NOEXCEPT
FMT_CONSTEXPR bool has_emphasis () const FMT_NOEXCEPT
FMT_CONSTEXPR detail::color_type get_foreground () const FMT_NOEXCEPT
FMT_CONSTEXPR detail::color_type get_background () const FMT_NOEXCEPT
FMT_CONSTEXPR emphasis get_emphasis () const FMT_NOEXCEPT
Private Member Functions
FMT_CONSTEXPR text_style (bool is_foreground, detail::color_type text_color) FMT_NOEXCEPT
FMT_CONSTEXPR text_style & and_assign (const text_style &rhs)
Private Attributes
detail::color_type foreground_color
detail::color_type background_color
bool set_foreground_color
bool set_background_color
emphasis ems
Friends
FMT_CONSTEXPR text_style operator| (text_style lhs, const text_style &rhs)
FMT_DEPRECATED_NONMSVC friend FMT_CONSTEXPR text_style operator& (text_style lhs, const text_style &rhs)
FMT_CONSTEXPR_DECL text_style fg (detail::color_type foreground) FMT_NOEXCEPT
FMT_CONSTEXPR_DECL text_style bg (detail::color_type background) FMT_NOEXCEPT
Detailed Description
A text style consisting of foreground and background colors and emphasis.
Definition at line 236 of file color.h.
Constructor & Destructor Documentation
text_style() [1/2]
FMT_CONSTEXPR text_style::text_style (emphasis em = emphasis()) inline
Definition at line 238 of file color.h.
       : set_foreground_color(),
         set_background_color(),
         ems(em) {}
text_style() [2/2]
FMT_CONSTEXPR text_style::text_style (bool is_foreground, detail::color_type text_color) inline private
Definition at line 305 of file color.h.
       : set_foreground_color(),
         set_background_color(),
         ems() {
     if (is_foreground) {
       foreground_color = text_color;
       set_foreground_color = true;
     } else {
       background_color = text_color;
       set_background_color = true;
     }
   }
References background_color, foreground_color, set_background_color, and set_foreground_color.
Member Function Documentation
and_assign()
FMT_CONSTEXPR text_style& text_style::and_assign (const text_style & rhs) inline private
Definition at line 320 of file color.h.
{
     if (!set_foreground_color) {
       set_foreground_color = rhs.set_foreground_color;
       foreground_color = rhs.foreground_color;
     } else if (rhs.set_foreground_color) {
       if (!foreground_color.is_rgb || !rhs.foreground_color.is_rgb)
         FMT_THROW(format_error("can't AND a terminal color"));
       foreground_color.value.rgb_color &= rhs.foreground_color.value.rgb_color;
     }
     if (!set_background_color) {
       set_background_color = rhs.set_background_color;
       background_color = rhs.background_color;
     } else if (rhs.set_background_color) {
       if (!background_color.is_rgb || !rhs.background_color.is_rgb)
         FMT_THROW(format_error("can't AND a terminal color"));
       background_color.value.rgb_color &= rhs.background_color.value.rgb_color;
     }
     ems = static_cast<emphasis>(static_cast<uint8_t>(ems) &
                                 static_cast<uint8_t>(rhs.ems));
     return *this;
   }
References background_color, ems, FMT_THROW, foreground_color, set_background_color, and set_foreground_color.
Referenced by operator&=().
get_background()
FMT_CONSTEXPR detail::color_type text_style::get_background () const inline
Definition at line 295 of file color.h.
{
     FMT_ASSERT(has_background(), "no background specified for this style");
     return background_color;
   }
References background_color, FMT_ASSERT, and has_background().
Referenced by vformat_to().
get_emphasis()
FMT_CONSTEXPR emphasis text_style::get_emphasis () const inline
Definition at line 299 of file color.h.
{
     FMT_ASSERT(has_emphasis(), "no emphasis specified for this style");
     return ems;
   }
References ems, FMT_ASSERT, and has_emphasis().
Referenced by vformat_to().
get_foreground()
FMT_CONSTEXPR detail::color_type text_style::get_foreground () const inline
Definition at line 291 of file color.h.
{
     FMT_ASSERT(has_foreground(), "no foreground specified for this style");
     return foreground_color;
   }
References FMT_ASSERT, foreground_color, and has_foreground().
Referenced by vformat_to().
has_background()
FMT_CONSTEXPR bool text_style::has_background () const inline
Definition at line 285 of file color.h.
{
     return set_background_color;
   }
References set_background_color.
Referenced by get_background(), and vformat_to().
has_emphasis()
FMT_CONSTEXPR bool text_style::has_emphasis () const inline
Definition at line 288 of file color.h.
{
     return static_cast<uint8_t>(ems) != 0;
   }
References ems.
Referenced by get_emphasis(), and vformat_to().
has_foreground()
FMT_CONSTEXPR bool text_style::has_foreground () const inline
Definition at line 282 of file color.h.
{
     return set_foreground_color;
   }
References set_foreground_color.
Referenced by get_foreground(), and vformat_to().
operator&=()
FMT_DEPRECATED_NONMSVC FMT_CONSTEXPR text_style& text_style::operator&= (const text_style & rhs) inline
Definition at line 272 of file color.h.
{
     return and_assign(rhs);
   }
References and_assign().
operator|=()
FMT_CONSTEXPR text_style& text_style::operator|= (const text_style & rhs) inline
Definition at line 243 of file color.h.
{
     if (!set_foreground_color) {
       set_foreground_color = rhs.set_foreground_color;
       foreground_color = rhs.foreground_color;
     } else if (rhs.set_foreground_color) {
       if (!foreground_color.is_rgb || !rhs.foreground_color.is_rgb)
         FMT_THROW(format_error("can't OR a terminal color"));
       foreground_color.value.rgb_color |= rhs.foreground_color.value.rgb_color;
     }
     if (!set_background_color) {
       set_background_color = rhs.set_background_color;
       background_color = rhs.background_color;
     } else if (rhs.set_background_color) {
       if (!background_color.is_rgb || !rhs.background_color.is_rgb)
         FMT_THROW(format_error("can't OR a terminal color"));
       background_color.value.rgb_color |= rhs.background_color.value.rgb_color;
     }
     ems = static_cast<emphasis>(static_cast<uint8_t>(ems) |
                                 static_cast<uint8_t>(rhs.ems));
     return *this;
   }
References background_color, ems, FMT_THROW, foreground_color, set_background_color, and set_foreground_color.
Friends And Related Function Documentation
bg
FMT_CONSTEXPR_DECL text_style bg (detail::color_type background) friend
Creates a text style from the background color.
Definition at line 363 of file color.h.
{
   return text_style(false, background);
 }
fg
FMT_CONSTEXPR_DECL text_style fg (detail::color_type foreground) friend
Creates a text style from the foreground (text) color.
Definition at line 358 of file color.h.
{
   return text_style(true, foreground);
 }
operator&
FMT_DEPRECATED_NONMSVC friend FMT_CONSTEXPR text_style operator& (text_style lhs, const text_style & rhs) friend
Definition at line 278 of file color.h.
{
     return lhs.and_assign(rhs);
   }
operator|
FMT_CONSTEXPR text_style operator| (text_style lhs, const text_style & rhs) friend
Definition at line 267 of file color.h.
{
     return lhs |= rhs;
   }
Member Data Documentation
background_color
detail::color_type text_style::background_color private
Definition at line 351 of file color.h.
Referenced by and_assign(), get_background(), operator|=(), and text_style().
ems
emphasis text_style::ems private
Definition at line 354 of file color.h.
Referenced by and_assign(), get_emphasis(), has_emphasis(), and operator|=().
foreground_color
detail::color_type text_style::foreground_color private
Definition at line 350 of file color.h.
Referenced by and_assign(), get_foreground(), operator|=(), and text_style().
set_background_color
bool text_style::set_background_color private
Definition at line 353 of file color.h.
Referenced by and_assign(), has_background(), operator|=(), and text_style().
set_foreground_color
bool text_style::set_foreground_color private
Definition at line 352 of file color.h.
Referenced by and_assign(), has_foreground(), operator|=(), and text_style().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/color.h