Azerotcore-wotlk: Acore::NearestHostileUnitInAttackDistanceCheck Class Reference
Acore::NearestHostileUnitInAttackDistanceCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestHostileUnitInAttackDistanceCheck (Creature const *creature, float dist)
bool operator() (Unit *u)
Private Member Functions
NearestHostileUnitInAttackDistanceCheck (NearestHostileUnitInAttackDistanceCheck const &)
Private Attributes
Creature const * me
float m_range
Detailed Description
Definition at line 1100 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestHostileUnitInAttackDistanceCheck() [1/2]
Acore::NearestHostileUnitInAttackDistanceCheck::NearestHostileUnitInAttackDistanceCheck (Creature const * creature, float dist) inline explicit
Definition at line 1103 of file GridNotifiers.h.
 : me(creature), m_range(dist) {}
NearestHostileUnitInAttackDistanceCheck() [2/2]
Acore::NearestHostileUnitInAttackDistanceCheck::NearestHostileUnitInAttackDistanceCheck (NearestHostileUnitInAttackDistanceCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestHostileUnitInAttackDistanceCheck::operator() (Unit * u) inline
Definition at line 1104 of file GridNotifiers.h.
         {
             if (!me->IsWithinDistInMap(u, m_range, true, false))
                 return false;
             if (!me->CanStartAttack(u))
                 return false;
             m_range = me->GetDistance(u);   // use found unit range as new range limit for next check
             return true;
         }
References Creature::CanStartAttack(), WorldObject::GetDistance(), WorldObject::IsWithinDistInMap(), m_range, and me.
Member Data Documentation
m_range
float Acore::NearestHostileUnitInAttackDistanceCheck::m_range private
Definition at line 1117 of file GridNotifiers.h.
Referenced by operator()().
me
Creature const* Acore::NearestHostileUnitInAttackDistanceCheck::me private
Definition at line 1116 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h