Azerotcore-wotlk: boss_illidan_stormrage::boss_illidan_stormrageAI Struct Reference
boss_illidan_stormrage::boss_illidan_stormrageAI Struct Reference
Public Member Functions
boss_illidan_stormrageAI (Creature *creature)
void Reset () override
void EnterEvadeMode () override
bool CanAIAttack (const Unit *target) const override
void DoAction (int32 param) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void SummonedCreatureDespawn (Creature *summon) override
void MovementInform (uint32 type, uint32 id) override
void ScheduleNormalEvents (uint8 phase)
void EnterCombat (Unit *who) override
void AttackStart (Unit *victim) override
void MoveInLineOfSight (Unit *) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events2
uint8 beamPosId
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 215 of file boss_illidan.cpp.
Constructor & Destructor Documentation
boss_illidan_stormrageAI()
boss_illidan_stormrage::boss_illidan_stormrageAI::boss_illidan_stormrageAI (Creature * creature) inline
Definition at line 217 of file boss_illidan.cpp.
                                                      : BossAI(creature, DATA_ILLIDAN_STORMRAGE)
         {
         }
Member Function Documentation
AttackStart()
void boss_illidan_stormrage::boss_illidan_stormrageAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 334 of file boss_illidan.cpp.
         {
             if (victim && me->Attack(victim, true))
                 me->GetMotionMaster()->MoveChase(victim, events.GetNextEventTime(EVENT_REMOVE_DEMON_FORM) != 0 ? 35.0f : 0.0f);
         }
References Unit::Attack(), EVENT_REMOVE_DEMON_FORM, Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveChase().
Referenced by UpdateAI().
CanAIAttack()
bool boss_illidan_stormrage::boss_illidan_stormrageAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 243 of file boss_illidan.cpp.
         {
             return target->GetEntry() != NPC_AKAMA && target->GetEntry() != NPC_MAIEV_SHADOWSONG;
         }
References Object::GetEntry(), NPC_AKAMA, and NPC_MAIEV_SHADOWSONG.
CheckEvadeIfOutOfCombatArea()
bool boss_illidan_stormrage::boss_illidan_stormrageAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
Definition at line 704 of file boss_illidan.cpp.
         {
             return me->GetHomePosition().GetExactDist(me) > 90.0f || !SelectTargetFromPlayerList(80.0f);
         }
References Creature::GetHomePosition(), ScriptedAI::me, and ScriptedAI::SelectTargetFromPlayerList().
DamageTaken()
void boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 359 of file boss_illidan.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 // xinef: do not allow to start outro when transforming
                 if (events.GetNextEventTime(EVENT_FINISH_TRANSFORM))
                     return;
                 if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 {
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         maiev->StopMovingOnCurrentPos();
                         maiev->GetMotionMaster()->Clear();
                         maiev->SetReactState(REACT_PASSIVE);
                         maiev->SetFullHealth();
                         maiev->RemoveAllAuras();
                         maiev->CombatStop();
                     }
                     if (events.GetNextEventTime(EVENT_REMOVE_DEMON_FORM) != 0)
                     {
                         me->CastSpell(me, SPELL_DEMON_TRANSFORM_1, true);
                         events2.ScheduleEvent(EVENT_OUTRO_DEMON, 12000);
                     }
                     else
                     {
                         me->CastSpell(me, SPELL_TELEPORT_MAIEV, true);
                         me->CastSpell(me, SPELL_DEATH, true);
                         events2.ScheduleEvent(EVENT_OUTRO_1, 1000);
                     }
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         maiev->SetTarget(me->GetGUID());
                         maiev->SetFacingToObject(me);
                     }
                     events.Reset();
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 }
             }
         }
References Unit::CastSpell(), EVENT_FINISH_TRANSFORM, EVENT_OUTRO_1, EVENT_OUTRO_DEMON, EVENT_REMOVE_DEMON_FORM, events2, SummonList::GetCreatureWithEntry(), Object::GetGUID(), Unit::GetHealth(), Object::HasFlag(), ScriptedAI::me, NPC_MAIEV_SHADOWSONG, REACT_PASSIVE, EventMap::ScheduleEvent(), Object::SetFlag(), SPELL_DEATH, SPELL_DEMON_TRANSFORM_1, SPELL_TELEPORT_MAIEV, BossAI::summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_illidan_stormrage::boss_illidan_stormrageAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 248 of file boss_illidan.cpp.
         {
             if (param == ACTION_ILLIDAN_CAGED)
             {
                 me->RemoveAurasDueToSpell(SPELL_FRENZY);
                 events.Reset();
                 events.ScheduleEvent(EVENT_PHASE_4_START, 16000);
             }
         }
References ACTION_ILLIDAN_CAGED, EVENT_PHASE_4_START, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), and SPELL_FRENZY.
EnterCombat()
void boss_illidan_stormrage::boss_illidan_stormrageAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 324 of file boss_illidan.cpp.
         {
             summons.DespawnAll();
             BossAI::EnterCombat(who);
             ScheduleNormalEvents(1);
             events.ScheduleEvent(EVENT_SPELL_BERSERK, 25 * MINUTE * IN_MILLISECONDS);
             events.ScheduleEvent(EVENT_SUMMON_MINIONS, 1000);
             events.ScheduleEvent(EVENT_PHASE_2_START, 1000);
         }
References SummonList::DespawnAll(), BossAI::EnterCombat(), EVENT_PHASE_2_START, EVENT_SPELL_BERSERK, EVENT_SUMMON_MINIONS, IN_MILLISECONDS, MINUTE, ScheduleNormalEvents(), and BossAI::summons.
EnterEvadeMode()
void boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 235 of file boss_illidan.cpp.
         {
             BossAI::EnterEvadeMode();
             if (Creature* akama = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_AKAMA)))
                 akama->AI()->EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, and NPC_AKAMA.
JustDied()
void boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 342 of file boss_illidan.cpp.
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
             summons.DespawnEntry(NPC_PARASITIC_SHADOWFIEND);
             instance->SetBossState(DATA_ILLIDAN_STORMRAGE, DONE);
             instance->SaveToDB();
         }
References DATA_ILLIDAN_STORMRAGE, SummonList::DespawnEntry(), DONE, BossAI::instance, ScriptedAI::me, NPC_PARASITIC_SHADOWFIEND, Object::RemoveFlag(), InstanceScript::SaveToDB(), InstanceScript::SetBossState(), BossAI::summons, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
JustSummoned()
void boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 258 of file boss_illidan.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_ILLIDAN_DB_TARGET)
                 me->CastSpell(summon, SPELL_EYE_BLAST, false);
             else if (summon->GetEntry() == NPC_MAIEV_SHADOWSONG)
             {
                 me->SetTarget(summon->GetGUID());
                 me->SetFacingToObject(summon);
                 summon->SetFacingToObject(me);
                 summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 summon->SetReactState(REACT_PASSIVE);
                 summon->CastSpell(summon, SPELL_TELEPORT_VISUAL_ONLY, true);
             }
         }
References Unit::CastSpell(), Object::GetEntry(), Object::GetGUID(), ScriptedAI::me, NPC_ILLIDAN_DB_TARGET, NPC_MAIEV_SHADOWSONG, REACT_PASSIVE, Unit::SetFacingToObject(), Object::SetFlag(), Creature::SetReactState(), Creature::SetTarget(), SPELL_EYE_BLAST, SPELL_TELEPORT_VISUAL_ONLY, SummonList::Summon(), BossAI::summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
KilledUnit()
void boss_illidan_stormrage::boss_illidan_stormrageAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 350 of file boss_illidan.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_ILLIDAN_KILL);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SAY_ILLIDAN_KILL, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_illidan_stormrage::boss_illidan_stormrageAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 340 of file boss_illidan.cpp.
 { }
MovementInform()
void boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 284 of file boss_illidan.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (id == POINT_ILLIDAN_HOVER)
             {
                 if (events2.GetNextEventTime(EVENT_START_PHASE_2_END) == 0)
                 {
                     events.ScheduleEvent(EVENT_PHASE_2_SUMMON2, 2000);
                     events.ScheduleEvent(EVENT_PHASE_2_CHANGE_POS, 6000);
                     events.ScheduleEvent(EVENT_PHASE_2_EYE_BEAM, 15000, GROUP_PHASE_2_ABILITY);
                     events2.ScheduleEvent(EVENT_START_PHASE_2_END, 10000);
                 }
                 me->SetFacingTo(me->GetAngle(676.02f, 305.45f));
             }
             else if (id == POINT_ILLIDAN_MIDDLE)
             {
                 EntryCheckPredicate pred(NPC_BLADE_OF_AZZINOTH);
                 summons.DoAction(ACTION_RETURN_BLADE, pred);
                 events.ScheduleEvent(EVENT_START_PHASE_2_WEAPON, 1500);
                 events.ScheduleEvent(EVENT_START_PHASE_3_LAND, 4000);
             }
         }
References ACTION_RETURN_BLADE, SummonList::DoAction(), EVENT_PHASE_2_CHANGE_POS, EVENT_PHASE_2_EYE_BEAM, EVENT_PHASE_2_SUMMON2, EVENT_START_PHASE_2_END, EVENT_START_PHASE_2_WEAPON, EVENT_START_PHASE_3_LAND, events2, Position::GetAngle(), EventMap::GetNextEventTime(), GROUP_PHASE_2_ABILITY, ScriptedAI::me, NPC_BLADE_OF_AZZINOTH, POINT_ILLIDAN_HOVER, POINT_ILLIDAN_MIDDLE, POINT_MOTION_TYPE, EventMap::ScheduleEvent(), Unit::SetFacingTo(), and BossAI::summons.
Reset()
void boss_illidan_stormrage::boss_illidan_stormrageAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 224 of file boss_illidan.cpp.
         {
             BossAI::Reset();
             events2.Reset();
             me->SetDisableGravity(false);
             me->CastSpell(me, SPELL_DUAL_WIELD, true);
             me->LoadEquipment(0, true);
             me->SetUInt32Value(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             beamPosId = urand(0, 3);
         }
References beamPosId, Unit::CastSpell(), events2, Creature::LoadEquipment(), ScriptedAI::me, EventMap::Reset(), BossAI::Reset(), Creature::SetDisableGravity(), Object::SetUInt32Value(), SPELL_DUAL_WIELD, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and urand().
ScheduleNormalEvents()
void boss_illidan_stormrage::boss_illidan_stormrageAI::ScheduleNormalEvents (uint8 phase) inline
Definition at line 309 of file boss_illidan.cpp.
         {
             events.ScheduleEvent(EVENT_SPELL_FLAME_CRASH, 15000);
             events.ScheduleEvent(EVENT_SPELL_DRAW_SOUL, 30000);
             events.ScheduleEvent(EVENT_SPELL_PARASITIC_SHADOWFIEND, 20000);
             events.ScheduleEvent(EVENT_SAY_TAUNT, 40000);
             if (phase >= 3)
             {
                 events.ScheduleEvent(EVENT_PHASE_4_START, 60000);
                 events.ScheduleEvent(EVENT_SPELL_AGONIZING_FLAMES, 10000);
             }
             if (phase >= 5)
                 events.ScheduleEvent(EVENT_SPELL_FRENZY, 40000);
         }
References EVENT_PHASE_4_START, EVENT_SAY_TAUNT, EVENT_SPELL_AGONIZING_FLAMES, EVENT_SPELL_DRAW_SOUL, EVENT_SPELL_FLAME_CRASH, EVENT_SPELL_FRENZY, and EVENT_SPELL_PARASITIC_SHADOWFIEND.
Referenced by EnterCombat(), and UpdateAI().
SummonedCreatureDespawn()
void boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 279 of file boss_illidan.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and BossAI::summons.
SummonedCreatureDies()
void boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 274 of file boss_illidan.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and BossAI::summons.
UpdateAI()
void boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 405 of file boss_illidan.cpp.
         {
             events2.Update(diff);
             switch (events2.ExecuteEvent())
             {
                 case EVENT_SUMMON_MINIONS2:
                     if (Creature* akama = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_AKAMA)))
                         akama->AI()->DoAction(ACTION_FIGHT_MINIONS);
                     break;
                 case EVENT_PHASE_2_EYE_BEAM_START:
                     Talk(SAY_ILLIDAN_EYE_BLAST);
                     if (Creature* trigger = summons.GetCreatureWithEntry(NPC_ILLIDAN_DB_TARGET))
                         trigger->GetMotionMaster()->MovePoint(0, eyeBeamPos[beamPosId + MAX_EYE_BEAM_POS], false, true);
                     break;
                 case EVENT_PHASE_2_INTERRUPT:
                     me->InterruptNonMeleeSpells(false);
                     break;
                 case EVENT_START_PHASE_2_END:
                     summons.RemoveNotExisting();
                     if (!summons.HasEntry(NPC_FLAME_OF_AZZINOTH))
                     {
                         events.Reset();
                         events2.Reset();
                         me->InterruptNonMeleeSpells(false);
                         me->GetMotionMaster()->MovePoint(POINT_ILLIDAN_MIDDLE, 676.02f, 305.45f, 353.6f);
                         break;
                     }
                     events2.ScheduleEvent(EVENT_START_PHASE_2_END, 1000);
                     break;
                 case EVENT_OUTRO_DEMON:
                     me->CastSpell(me, SPELL_TELEPORT_MAIEV, true);
                     me->CastSpell(me, SPELL_DEATH, true);
                     events2.ScheduleEvent(EVENT_OUTRO_1, 1000);
                     break;
                 case EVENT_OUTRO_1:
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         maiev->SetTarget(me->GetGUID());
                         maiev->SetFacingToObject(me);
                         maiev->AI()->DoAction(ACTION_MAIEV_OUTRO);
                         maiev->AI()->Talk(SAY_MAIEV_SHADOWSONG_ILLIDAN3);
                     }
                     if (Creature* akama = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_AKAMA)))
                     {
                         akama->AI()->DoAction(ACTION_ILLIDAN_DEAD);
                         akama->SetTarget(me->GetGUID());
                         akama->GetMotionMaster()->MovePoint(0, 695.63f, 306.63f, 354.26f);
                     }
                     events2.ScheduleEvent(EVENT_OUTRO_2, 6000);
                     break;
                 case EVENT_OUTRO_2:
                     Talk(SAY_ILLIDAN_MAIEV3);
                     events2.ScheduleEvent(EVENT_OUTRO_3, 17000);
                     break;
                 case EVENT_OUTRO_3:
                     Unit::Kill(nullptr, me);
                     break;
             }
             EnterEvadeIfOutOfCombatArea();
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SUMMON_MINIONS:
                     if (me->HealthBelowPct(90))
                     {
                         Talk(SAY_ILLIDAN_MINION);
                         events2.ScheduleEvent(EVENT_SUMMON_MINIONS2, 10000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_SUMMON_MINIONS, 1000);
                     break;
                 // ///////////////////////////
                 // PHASE 1, 3, 5
                 // ///////////////////////////
                 case EVENT_SPELL_BERSERK:
                     Talk(SAY_ILLIDAN_ENRAGE);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
                 case EVENT_SPELL_FLAME_CRASH:
                     me->CastSpell(me->GetVictim(), SPELL_FLAME_CRASH, false);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_CRASH, 25000);
                     break;
                 case EVENT_SPELL_DRAW_SOUL:
                     me->CastSpell(me->GetVictim(), SPELL_DRAW_SOUL, false);
                     events.ScheduleEvent(EVENT_SPELL_DRAW_SOUL, 40000);
                     break;
                 case EVENT_SPELL_PARASITIC_SHADOWFIEND:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_PARASITIC_SHADOWFIEND, false);
                     events.ScheduleEvent(EVENT_SPELL_PARASITIC_SHADOWFIEND, 30000);
                     break;
                 case EVENT_SAY_TAUNT:
                     Talk(SAY_ILLIDAN_TAUNT);
                     events.ScheduleEvent(EVENT_SAY_TAUNT, urand(30000, 60000));
                     break;
                 case EVENT_SPELL_FRENZY:
                     Talk(SAY_ILLIDAN_FRENZY);
                     me->CastSpell(me, SPELL_FRENZY, false);
                     break;
                 case EVENT_SPELL_AGONIZING_FLAMES:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_AGONIZING_FLAMES, false);
                     break;
                 case EVENT_PHASE_5_START:
                     if (me->HealthBelowPct(30))
                     {
                         me->CastSpell(me, SPELL_SHADOW_PRISON, true);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                         Talk(SAY_ILLIDAN_MAIEV1);
                         events.Reset();
                         events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000);
                         events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000);
                         events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000);
                         events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000);
                         events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_PHASE_5_START, 1000);
                     break;
                 case EVENT_PHASE_5_SCENE1:
                     me->CastSpell(me, SPELL_SUMMON_MAIEV, true);
                     break;
                 case EVENT_PHASE_5_SCENE2:
                     Talk(SAY_ILLIDAN_MAIEV2);
                     break;
                 case EVENT_PHASE_5_SCENE3:
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                         maiev->AI()->Talk(SAY_MAIEV_SHADOWSONG_ILLIDAN2);
                     break;
                 case EVENT_PHASE_5_SCENE4:
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                         maiev->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                     break;
                 case EVENT_PHASE_5_SCENE5:
                     me->SetTarget(me->GetVictim()->GetGUID());
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         maiev->SetReactState(REACT_AGGRESSIVE);
                         maiev->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         maiev->AI()->AttackStart(me);
                     }
                     ScheduleNormalEvents(5);
                     break;
                 // ///////////////////////////
                 // PHASE 2
                 // ///////////////////////////
                 case EVENT_PHASE_2_START:
                     if (me->HealthBelowPct(65))
                     {
                         if (events2.GetNextEventTime(EVENT_SUMMON_MINIONS2) != 0)
                             events2.RescheduleEvent(EVENT_SUMMON_MINIONS2, 0);
                         Talk(SAY_ILLIDAN_TAKEOFF);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->SetTarget();
                         me->GetMotionMaster()->Clear();
                         me->StopMovingOnCurrentPos();
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                         me->SetDisableGravity(true);
                         events.Reset();
                         events.ScheduleEvent(EVENT_PHASE_2_SUMMON1, 6000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_PHASE_2_START, 1000);
                     break;
                 case EVENT_PHASE_2_SUMMON1:
                     me->LoadEquipment(1, true);
                     me->GetMotionMaster()->MovePoint(POINT_ILLIDAN_HOVER, 727.875f, 305.365f, 356.0f, false, true);
                     break;
                 case EVENT_PHASE_2_SUMMON2:
                     Talk(SAY_ILLIDAN_SUMMONFLAMES);
                     me->LoadEquipment(0, true);
                     me->CastSpell(me, SPELL_THROW_GLAIVE, false);
                     me->CastSpell(me, SPELL_THROW_GLAIVE2, false);
                     break;
                 case EVENT_PHASE_2_CHANGE_POS:
                     beamPosId = (beamPosId + 1) % MAX_EYE_BEAM_POS;
                     events.ScheduleEvent(EVENT_SPELL_FIREBALL, 8000, GROUP_PHASE_2_ABILITY);
                     events.ScheduleEvent(EVENT_SPELL_DARK_BARRAGE, 18000, GROUP_PHASE_2_ABILITY);
                     events.ScheduleEvent(EVENT_PHASE_2_EYE_BEAM, urand(25000, 50000), GROUP_PHASE_2_ABILITY);
                     me->GetMotionMaster()->MovePoint(POINT_ILLIDAN_HOVER, airHoverPos[beamPosId], false, true);
                     break;
                 case EVENT_PHASE_2_EYE_BEAM:
                     me->SummonCreature(NPC_ILLIDAN_DB_TARGET, eyeBeamPos[beamPosId], TEMPSUMMON_TIMED_DESPAWN, 15000);
                     events.CancelEventGroup(GROUP_PHASE_2_ABILITY);
                     events.ScheduleEvent(EVENT_PHASE_2_CHANGE_POS, 20000);
                     events2.ScheduleEvent(EVENT_PHASE_2_EYE_BEAM_START, 2000);
                     events2.ScheduleEvent(EVENT_PHASE_2_INTERRUPT, 20000);
                     break;
                 case EVENT_SPELL_FIREBALL:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_FIREBALL, false);
                     events.ScheduleEvent(EVENT_SPELL_FIREBALL, 2200, GROUP_PHASE_2_ABILITY);
                     break;
                 case EVENT_SPELL_DARK_BARRAGE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_DARK_BARRAGE, false);
                     events.ScheduleEvent(EVENT_SPELL_DARK_BARRAGE, 30000, GROUP_PHASE_2_ABILITY);
                     break;
                 case EVENT_START_PHASE_2_WEAPON:
                     me->LoadEquipment(1, true);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                     me->SetDisableGravity(false);
                     break;
                 case EVENT_START_PHASE_3_LAND:
                     me->getThreatMgr().resetAllAggro();
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->SetTarget(me->GetVictim()->GetGUID());
                     AttackStart(me->GetVictim());
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     ScheduleNormalEvents(3);
                     events.ScheduleEvent(EVENT_PHASE_5_START, 1000);
                     break;
                 // ///////////////////////////
                 // PHASE 4
                 // ///////////////////////////
                 case EVENT_PHASE_4_START:
                     me->CastSpell(me, SPELL_DEMON_TRANSFORM_1, true);
                     me->getThreatMgr().resetAllAggro();
                     me->GetMotionMaster()->MoveChase(me->GetVictim(), 35.0f);
                     events.Reset();
                     events.ScheduleEvent(EVENT_SPELL_SHADOW_BLAST, 11000);
                     events.ScheduleEvent(EVENT_MOVE_MAIEV, 5000);
                     events.ScheduleEvent(EVENT_FINISH_TRANSFORM, 10500);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_BURST, 21000);
                     events.ScheduleEvent(EVENT_SPELL_SHADOW_DEMONS, 36000);
                     events.ScheduleEvent(EVENT_REMOVE_DEMON_FORM, 60000);
                     break;
                 case EVENT_SPELL_SHADOW_BLAST:
                     me->CastSpell(me->GetVictim(), SPELL_SHADOW_BLAST, false);
                     events.ScheduleEvent(EVENT_SPELL_SHADOW_BLAST, 2200);
                     break;
                 case EVENT_SPELL_FLAME_BURST:
                     me->CastSpell(me, SPELL_FLAME_BURST, false);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_BURST, 22000);
                     break;
                 case EVENT_SPELL_SHADOW_DEMONS:
                     me->CastSpell(me, SPELL_SUMMON_SHADOW_DEMON, false);
                     break;
                 case EVENT_REMOVE_DEMON_FORM:
                     me->CastSpell(me, SPELL_DEMON_TRANSFORM_1, true);
                     me->getThreatMgr().resetAllAggro();
                     events.Reset();
                     if (summons.HasEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         ScheduleNormalEvents(5);
                         events.DelayEvents(11000);
                         events.ScheduleEvent(EVENT_MOVE_MAIEV, 10000);
                         events.ScheduleEvent(EVENT_FINISH_TRANSFORM, 10500);
                     }
                     else
                     {
                         ScheduleNormalEvents(3);
                         events.ScheduleEvent(EVENT_PHASE_5_START, 1000);
                         events.DelayEvents(11000);
                         events.ScheduleEvent(EVENT_FINISH_TRANSFORM, 10500);
                     }
                     break;
                 case EVENT_MOVE_MAIEV:
                     if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                     {
                         if (events.GetNextEventTime(EVENT_REMOVE_DEMON_FORM) != 0)
{
                             maiev->AI()->DoAction(ACTION_MAIEV_SET_DIST30);
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, -25.0f, true))
                                 maiev->GetMotionMaster()->MoveCharge(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 7.0f, 0);
                             else
                                 maiev->GetMotionMaster()->MoveCharge(678.04f, 378.34f, 353.0f, 7.0f, 0);
                         }
                         else
{
                             maiev->AI()->DoAction(ACTION_MAIEV_SET_DIST0);
                             maiev->GetMotionMaster()->MoveChase(me, 0.0f);
                         }
                     }
                     break;
                 case EVENT_FINISH_TRANSFORM:
                     me->GetMotionMaster()->MoveChase(me->GetVictim(), events.GetNextEventTime(EVENT_REMOVE_DEMON_FORM) != 0 ? 35.0f : 0.0f);
                     break;
             }
             if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                 DoMeleeAttackIfReady();
         }
References ACTION_FIGHT_MINIONS, ACTION_ILLIDAN_DEAD, ACTION_MAIEV_OUTRO, ACTION_MAIEV_SET_DIST0, ACTION_MAIEV_SET_DIST30, airHoverPos, AttackStart(), beamPosId, Unit::CastSpell(), MotionMaster::Clear(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_LAND, EMOTE_ONESHOT_LIFTOFF, EMOTE_ONESHOT_ROAR, ScriptedAI::EnterEvadeIfOutOfCombatArea(), EVENT_FINISH_TRANSFORM, EVENT_MOVE_MAIEV, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_OUTRO_DEMON, EVENT_PHASE_2_CHANGE_POS, EVENT_PHASE_2_EYE_BEAM, EVENT_PHASE_2_EYE_BEAM_START, EVENT_PHASE_2_INTERRUPT, EVENT_PHASE_2_START, EVENT_PHASE_2_SUMMON1, EVENT_PHASE_2_SUMMON2, EVENT_PHASE_4_START, EVENT_PHASE_5_SCENE1, EVENT_PHASE_5_SCENE2, EVENT_PHASE_5_SCENE3, EVENT_PHASE_5_SCENE4, EVENT_PHASE_5_SCENE5, EVENT_PHASE_5_START, EVENT_REMOVE_DEMON_FORM, EVENT_SAY_TAUNT, EVENT_SPELL_AGONIZING_FLAMES, EVENT_SPELL_BERSERK, EVENT_SPELL_DARK_BARRAGE, EVENT_SPELL_DRAW_SOUL, EVENT_SPELL_FIREBALL, EVENT_SPELL_FLAME_BURST, EVENT_SPELL_FLAME_CRASH, EVENT_SPELL_FRENZY, EVENT_SPELL_PARASITIC_SHADOWFIEND, EVENT_SPELL_SHADOW_BLAST, EVENT_SPELL_SHADOW_DEMONS, EVENT_START_PHASE_2_END, EVENT_START_PHASE_2_WEAPON, EVENT_START_PHASE_3_LAND, EVENT_SUMMON_MINIONS, EVENT_SUMMON_MINIONS2, events2, EventMap::ExecuteEvent(), eyeBeamPos, ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), Object::GetGUID(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), EventMap::GetNextEventTime(), Unit::getThreatMgr(), Unit::GetVictim(), GROUP_PHASE_2_ABILITY, Unit::HandleEmoteCommand(), SummonList::HasEntry(), Object::HasFlag(), Unit::HasUnitState(), Unit::HealthBelowPct(), BossAI::instance, Unit::InterruptNonMeleeSpells(), Unit::Kill(), Creature::LoadEquipment(), MAX_EYE_BEAM_POS, ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MovePoint(), NPC_AKAMA, NPC_FLAME_OF_AZZINOTH, NPC_ILLIDAN_DB_TARGET, NPC_MAIEV_SHADOWSONG, POINT_ILLIDAN_HOVER, POINT_ILLIDAN_MIDDLE, REACT_AGGRESSIVE, Object::RemoveFlag(), SummonList::RemoveNotExisting(), EventMap::RescheduleEvent(), EventMap::Reset(), ThreatMgr::resetAllAggro(), SAY_ILLIDAN_ENRAGE, SAY_ILLIDAN_EYE_BLAST, SAY_ILLIDAN_FRENZY, SAY_ILLIDAN_MAIEV1, SAY_ILLIDAN_MAIEV2, SAY_ILLIDAN_MAIEV3, SAY_ILLIDAN_MINION, SAY_ILLIDAN_SUMMONFLAMES, SAY_ILLIDAN_TAKEOFF, SAY_ILLIDAN_TAUNT, SAY_MAIEV_SHADOWSONG_ILLIDAN2, SAY_MAIEV_SHADOWSONG_ILLIDAN3, EventMap::ScheduleEvent(), ScheduleNormalEvents(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetTarget(), SPELL_AGONIZING_FLAMES, SPELL_BERSERK, SPELL_DARK_BARRAGE, SPELL_DEATH, SPELL_DEMON_TRANSFORM_1, SPELL_DRAW_SOUL, SPELL_FIREBALL, SPELL_FLAME_BURST, SPELL_FLAME_CRASH, SPELL_FRENZY, SPELL_PARASITIC_SHADOWFIEND, SPELL_SHADOW_BLAST, SPELL_SHADOW_PRISON, SPELL_SUMMON_MAIEV, SPELL_SUMMON_SHADOW_DEMON, SPELL_TELEPORT_MAIEV, SPELL_THROW_GLAIVE, SPELL_THROW_GLAIVE2, Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
beamPosId
uint8 boss_illidan_stormrage::boss_illidan_stormrageAI::beamPosId
Definition at line 222 of file boss_illidan.cpp.
Referenced by Reset(), and UpdateAI().
events2
EventMap boss_illidan_stormrage::boss_illidan_stormrageAI::events2
Definition at line 221 of file boss_illidan.cpp.
Referenced by DamageTaken(), MovementInform(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_illidan.cpp