Azerotcore-wotlk: deps/mysqllite/mysys/mf_dirname.c File Reference
mf_dirname.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Macros
#define FN_DEVCHAR '\0' /* For easier code */
Functions
size_t dirname_length (const char *name)
size_t dirname_part (char *to, const char *name, size_t *to_res_length)
char * convert_dirname (char *to, const char *from, const char *from_end)
Macro Definition Documentation
FN_DEVCHAR
#define FN_DEVCHAR '\0' /* For easier code */
Definition at line 101 of file mf_dirname.c.
Function Documentation
convert_dirname()
char* convert_dirname (char * to, const char * from, const char * from_end)
Definition at line 104 of file mf_dirname.c.
 {
   char *to_org=to;
 #ifdef BACKSLASH_MBTAIL
   CHARSET_INFO *fs= fs_character_set();
 #endif
   DBUG_ENTER("convert_dirname");
   /* We use -2 here, becasue we need place for the last FN_LIBCHAR */
   if (!from_end || (from_end - from) > FN_REFLEN-2)
     from_end=from+FN_REFLEN -2;
 #if FN_LIBCHAR != '/'
   {
     for (; from != from_end && *from ; from++)
     {
       if (*from == '/')
     *to++= FN_LIBCHAR;
       else
       {
 #ifdef BACKSLASH_MBTAIL
         uint l;
         if (use_mb(fs) && (l= my_ismbchar(fs, from, from + 3)))
         {
           memmove(to, from, l);
           to+= l;
           from+= l - 1;
           to_org= to; /* Don't look inside mbchar */
         }
         else
 #endif
         {
           *to++= *from;
         }
       }
     }
     *to=0;
   }
 #else
   /* This is ok even if to == from, becasue we need to cut the string */
   to= strmake(to, from, (size_t) (from_end-from));
 #endif
   /* Add FN_LIBCHAR to the end of directory path */
   if (to != to_org && (to[-1] != FN_LIBCHAR && to[-1] != FN_DEVCHAR))
   {
     *to++=FN_LIBCHAR;
     *to=0;
   }
   DBUG_RETURN(to);                              /* Pointer to end of dir */
 } /* convert_dirname */
References DBUG_ENTER, DBUG_RETURN, FN_DEVCHAR, FN_LIBCHAR, FN_REFLEN, mpq::l, memmove, my_ismbchar, strmake(), and use_mb.
Referenced by create_temp_file(), dirname_part(), fn_format(), get_charsets_dir(), my_print_default_files(), mysql_read_default_options(), and search_default_file_with_ext().
dirname_length()
size_t dirname_length (const char * name)
Definition at line 21 of file mf_dirname.c.
 {
   register char *pos, *gpos;
 #ifdef BASKSLASH_MBTAIL
   CHARSET_INFO *fs= fs_character_set();
 #endif
 #ifdef FN_DEVCHAR
   if ((pos=(char*)strrchr(name,FN_DEVCHAR)) == 0)
 #endif
     pos=(char*) name-1;
   gpos= pos++;
   for ( ; *pos ; pos++)             /* Find last FN_LIBCHAR */
   {
 #ifdef BASKSLASH_MBTAIL
     uint l;
     if (use_mb(fs) && (l= my_ismbchar(fs, pos, pos + 3)))
     {
       pos+= l - 1;
       continue;
     }
 #endif
     if (*pos == FN_LIBCHAR || *pos == '/')
       gpos=pos;
   }
   return (size_t) (gpos+1-(char*) name);
 }
References FN_DEVCHAR, FN_LIBCHAR, mpq::l, my_ismbchar, pos(), and use_mb.
Referenced by dirname_part(), my_print_default_files(), and my_search_option_files().
dirname_part()
size_t dirname_part (char * to, const char * name, size_t * to_res_length)
Definition at line 63 of file mf_dirname.c.
 {
   size_t length;
   DBUG_ENTER("dirname_part");
   DBUG_PRINT("enter",("'%s'",name));
   length=dirname_length(name);
   *to_res_length= (size_t) (convert_dirname(to, name, name+length) - to);
   DBUG_RETURN(length);
 } /* dirname */
References convert_dirname(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_length(), and G3D::length().
Referenced by fn_ext(), fn_format(), fn_same(), intern_filename(), my_path(), my_rename(), and unpack_filename().