Azerotcore-wotlk: npc_finklestein::npc_finklesteinAI Struct Reference
npc_finklestein::npc_finklesteinAI Struct Reference
Public Member Functions
npc_finklesteinAI (Creature *creature)
void ClearPlayerOnTask (ObjectGuid guid)
bool IsPlayerOnTask (ObjectGuid guid)
void RightClickCauldron (ObjectGuid guid)
void StartNextTask (ObjectGuid playerGUID, uint32 counter)
uint32 SelectRandomCode (uint32 counter)
uint32 GetTaskCounter (uint32 itemcode)
uint32 GetTaskAura (uint32 itemcode)
uint32 GetTaskItemEntry (uint32 itemcode)
const char * GetTaskItemName (uint32 itemcode)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
std::map< ObjectGuid, uint32 > questList
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 50 of file zone_zuldrak.cpp.
Constructor & Destructor Documentation
npc_finklesteinAI()
npc_finklestein::npc_finklesteinAI::npc_finklesteinAI (Creature * creature) inline
Definition at line 52 of file zone_zuldrak.cpp.
 : ScriptedAI(creature) {}
Member Function Documentation
ClearPlayerOnTask()
void npc_finklestein::npc_finklesteinAI::ClearPlayerOnTask (ObjectGuid guid) inline
Definition at line 56 of file zone_zuldrak.cpp.
         {
             std::map<ObjectGuid, uint32>::iterator itr = questList.find(guid);
             if (itr != questList.end())
                 questList.erase(itr);
         }
References questList.
GetTaskAura()
uint32 npc_finklestein::npc_finklesteinAI::GetTaskAura (uint32 itemcode) inline
Definition at line 170 of file zone_zuldrak.cpp.
 { return AA_AURA_ID[itemcode % 100]; }
References AA_AURA_ID.
Referenced by RightClickCauldron(), and StartNextTask().
GetTaskCounter()
uint32 npc_finklestein::npc_finklesteinAI::GetTaskCounter (uint32 itemcode) inline
Definition at line 169 of file zone_zuldrak.cpp.
 { return itemcode / 100; }
Referenced by RightClickCauldron().
GetTaskItemEntry()
uint32 npc_finklestein::npc_finklesteinAI::GetTaskItemEntry (uint32 itemcode) inline
Definition at line 171 of file zone_zuldrak.cpp.
 { return AA_ITEM_ENTRY[itemcode % 100]; }
References AA_ITEM_ENTRY.
Referenced by RightClickCauldron().
GetTaskItemName()
const char* npc_finklestein::npc_finklesteinAI::GetTaskItemName (uint32 itemcode) inline
Definition at line 172 of file zone_zuldrak.cpp.
 { return AA_ITEM_NAME[itemcode % 100]; }
References AA_ITEM_NAME.
Referenced by StartNextTask().
IsPlayerOnTask()
bool npc_finklestein::npc_finklesteinAI::IsPlayerOnTask (ObjectGuid guid) inline
Definition at line 63 of file zone_zuldrak.cpp.
         {
             std::map<ObjectGuid, uint32>::const_iterator itr = questList.find(guid);
             return itr != questList.end();
         }
References questList.
RightClickCauldron()
void npc_finklestein::npc_finklesteinAI::RightClickCauldron (ObjectGuid guid) inline
Definition at line 69 of file zone_zuldrak.cpp.
         {
             if (questList.empty())
                 return;
             std::map<ObjectGuid, uint32>::iterator itr = questList.find(guid);
             if (itr == questList.end())
                 return;
             Player* player = ObjectAccessor::GetPlayer(*me, guid);
             if (player)
             {
                 uint32 itemCode = itr->second;
                 uint32 itemEntry = GetTaskItemEntry(itemCode);
                 uint32 auraId = GetTaskAura(itemCode);
                 uint32 counter = GetTaskCounter(itemCode);
                 if (player->HasAura(auraId))
                 {
                     // player still has aura, but no item. Skip
                     if (!player->HasItemCount(itemEntry))
                         return;
                     // if we are here, all is ok (aura and item present)
                     player->DestroyItemCount(itemEntry, 1, true);
                     player->RemoveAurasDueToSpell(auraId);
                     if (counter < 6)
                     {
                         StartNextTask(player->GetGUID(), counter + 1);
                         return;
                     }
                     else
                         player->KilledMonsterCredit(28248);
                 }
                 else
                 {
                     // if we are here, it means we failed :(
                     player->SetQuestStatus(QUEST_ALCHEMIST_APPRENTICE, QUEST_STATUS_FAILED);
                 }
             }
             questList.erase(itr);
         }
References Player::DestroyItemCount(), Object::GetGUID(), ObjectAccessor::GetPlayer(), GetTaskAura(), GetTaskCounter(), GetTaskItemEntry(), Unit::HasAura(), Player::HasItemCount(), Player::KilledMonsterCredit(), ScriptedAI::me, QUEST_ALCHEMIST_APPRENTICE, QUEST_STATUS_FAILED, questList, Unit::RemoveAurasDueToSpell(), Player::SetQuestStatus(), and StartNextTask().
SelectRandomCode()
uint32 npc_finklestein::npc_finklesteinAI::SelectRandomCode (uint32 counter) inline
Definition at line 167 of file zone_zuldrak.cpp.
 { return (counter * 100 + urand(0, 23)); }
References urand().
Referenced by StartNextTask().
StartNextTask()
void npc_finklestein::npc_finklesteinAI::StartNextTask (ObjectGuid playerGUID, uint32 counter) inline
Definition at line 114 of file zone_zuldrak.cpp.
         {
             if (counter > 6)
                 return;
             Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
             if (!player)
                 return;
             // Generate Item Code
             uint32 itemCode = SelectRandomCode(counter);
             questList[playerGUID] = itemCode;
             // Decode Item Entry, Get Item Name, Generate Emotes
             //uint32 itemEntry = GetTaskItemEntry(itemCode);
             uint32 auraId = GetTaskAura(itemCode);
             const char* itemName = GetTaskItemName(itemCode);
             switch (counter)
             {
                 case 1:
                     me->TextEmote("Quickly, get me some...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
                 case 2:
                     me->TextEmote("Find me some...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
                 case 3:
                     me->TextEmote("I think it needs...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
                 case 4:
                     me->TextEmote("Alright, now fetch me some...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
                 case 5:
                     me->TextEmote("Before it thickens, we must add...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
                 case 6:
                     me->TextEmote("It's thickening! Quickly get me some...", player, true);
                     me->TextEmote(itemName, player, true);
                     me->CastSpell(player, auraId, true);
                     break;
             }
         }
References Unit::CastSpell(), ObjectAccessor::GetPlayer(), GetTaskAura(), GetTaskItemName(), ScriptedAI::me, questList, SelectRandomCode(), and Unit::TextEmote().
Referenced by RightClickCauldron().
Member Data Documentation
questList
std::map<ObjectGuid, uint32> npc_finklestein::npc_finklesteinAI::questList
Definition at line 54 of file zone_zuldrak.cpp.
Referenced by ClearPlayerOnTask(), IsPlayerOnTask(), RightClickCauldron(), and StartNextTask().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_zuldrak.cpp