Azerotcore-wotlk: npc_varian_wrynn::npc_varian_wrynnAI Struct Reference
npc_varian_wrynn::npc_varian_wrynnAI Struct Reference
Public Member Functions
npc_varian_wrynnAI (Creature *creature)
void EnterEvadeMode () override
void Reset () override
void JustSummoned (Creature *summonedCreature) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateWorldState (Map *map, uint32 id, uint32 state)
void SetHoldState (bool bOnHold)
void JumpToNextStep (uint32 uiTimer)
void SpawnWave (uint32 waveId)
void WaypointReached (uint32 waypointId) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool bStepping
bool summoned
uint32 step
uint32 phaseTimer
uint32 whirlwindTimer
ObjectGuid jainaGUID
ObjectGuid putressGUID
ObjectGuid blightWormGUID
ObjectGuid khanokGUID
ObjectGuid thrallGUID
ObjectGuid sylvanasGUID
ObjectGuid generatorGUID [GENERATOR_MAXCOUNT]
ObjectGuid allianceForcesGUID [ALLIANCE_FORCE_MAXCOUNT]
ObjectGuid hordeForcesGUID [HORDE_FORCE_MAXCOUNT]
GuidVector allianceGuardsGUID
EventMap _events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 981 of file zone_undercity.cpp.
Constructor & Destructor Documentation
npc_varian_wrynnAI()
npc_varian_wrynn::npc_varian_wrynnAI::npc_varian_wrynnAI (Creature * creature) inline
Definition at line 983 of file zone_undercity.cpp.
                                                : npc_escortAI(creature)
         {
             allianceGuardsGUID.clear();
         }
References allianceGuardsGUID.
Member Function Documentation
EnterEvadeMode()
void npc_varian_wrynn::npc_varian_wrynnAI::EnterEvadeMode () inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1010 of file zone_undercity.cpp.
         {
             me->DeleteThreatList();
             me->CombatStop(true);
             me->SetLootRecipient(nullptr);
             if (HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 AddEscortState(STATE_ESCORT_RETURNING);
                 ReturnToLastPoint();
             }
             else
             {
                 me->GetMotionMaster()->MoveTargetedHome();
                 Reset();
             }
         }
References npc_escortAI::AddEscortState(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), npc_escortAI::HasEscortState(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), Reset(), npc_escortAI::ReturnToLastPoint(), Creature::SetLootRecipient(), STATE_ESCORT_ESCORTING, and STATE_ESCORT_RETURNING.
JumpToNextStep()
void npc_varian_wrynn::npc_varian_wrynnAI::JumpToNextStep (uint32 uiTimer) inline
Definition at line 1164 of file zone_undercity.cpp.
         {
             phaseTimer = uiTimer;
             ++step;
         }
References phaseTimer, and step.
Referenced by UpdateAI().
JustSummoned()
void npc_varian_wrynn::npc_varian_wrynnAI::JustSummoned (Creature * summonedCreature) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1111 of file zone_undercity.cpp.
         {
             switch (summonedCreature->GetEntry())
             {
                 case NPC_GENERATOR:
                     summonedCreature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     summonedCreature->ApplySpellImmune(0, IMMUNITY_ID, SPELL_WRYNN_BUFF, true);
                     summonedCreature->ApplySpellImmune(0, IMMUNITY_ID, SPELL_THRALL_BUFF, true);
                     summonedCreature->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                     break;
                 default:
                     break;
             }
         }
References Unit::ApplySpellImmune(), Object::GetEntry(), IMMUNITY_ID, NPC_GENERATOR, Object::SetFlag(), SPELL_SYLVANAS_BUFF, SPELL_THRALL_BUFF, SPELL_WRYNN_BUFF, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void npc_varian_wrynn::npc_varian_wrynnAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1028 of file zone_undercity.cpp.
         {
             if (!HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 me->SetCorpseDelay(1);
                 me->SetRespawnTime(1);
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 bStepping = false;
                 step = 0;
                 phaseTimer = 0;
                 jainaGUID.Clear();
                 _events.ScheduleEvent(EVENT_WHIRLWIND, 5 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_HEROIC_LEAP, 10 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_AGGRO_JAINA, 2 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_WRYNN_BUFF, 2 * IN_MILLISECONDS);
                 me->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                 if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                 {
                     putress->DespawnOrUnsummon();
                     putressGUID.Clear();
                 }
                 if (Creature* blightWorm = ObjectAccessor::GetCreature(*me, blightWormGUID))
                 {
                     blightWorm->DespawnOrUnsummon();
                     blightWormGUID.Clear();
                 }
                 if (Creature* khanok = ObjectAccessor::GetCreature(*me, khanokGUID))
                 {
                     khanok->DespawnOrUnsummon();
                     khanokGUID.Clear();
                 }
                 if (Creature* thrall = ObjectAccessor::GetCreature(*me, thrallGUID))
                 {
                     thrall->DespawnOrUnsummon();
                     thrallGUID.Clear();
                 }
                 if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasGUID))
                 {
                     sylvanas->DespawnOrUnsummon();
                     sylvanasGUID.Clear();
                 }
                 for (uint8 i = 0; i < GENERATOR_MAXCOUNT; ++i)
                 {
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, generatorGUID[i]))
                     {
                         generatorGUID[i].Clear();
                         temp->DespawnOrUnsummon();
                     }
                 }
                 for (uint8 i = 0; i < ALLIANCE_FORCE_MAXCOUNT; ++i)
                 {
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, allianceForcesGUID[i]))
                     {
                         allianceForcesGUID[i].Clear();
                         temp->DespawnOrUnsummon();
                     }
                 }
                 for (ObjectGuid const& guid : allianceGuardsGUID)
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, guid))
                         temp->DespawnOrUnsummon();
                 allianceGuardsGUID.clear();
                 for (uint8 i = 0; i < HORDE_FORCE_MAXCOUNT; ++i)
                 {
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, hordeForcesGUID[i]))
                     {
                         hordeForcesGUID[i].Clear();
                         temp->DespawnOrUnsummon();
                     }
                 }
             }
         }
References _events, ALLIANCE_FORCE_MAXCOUNT, allianceForcesGUID, allianceGuardsGUID, Unit::ApplySpellImmune(), blightWormGUID, bStepping, ObjectGuid::Clear(), EVENT_AGGRO_JAINA, EVENT_HEROIC_LEAP, EVENT_WHIRLWIND, EVENT_WRYNN_BUFF, GENERATOR_MAXCOUNT, generatorGUID, ObjectAccessor::GetCreature(), npc_escortAI::HasEscortState(), HORDE_FORCE_MAXCOUNT, hordeForcesGUID, IMMUNITY_ID, IN_MILLISECONDS, jainaGUID, khanokGUID, ScriptedAI::me, phaseTimer, putressGUID, EventMap::ScheduleEvent(), Creature::SetCorpseDelay(), Object::SetFlag(), Creature::SetRespawnTime(), SPELL_SYLVANAS_BUFF, STATE_ESCORT_ESCORTING, step, sylvanasGUID, thrallGUID, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by EnterEvadeMode().
SetHoldState()
void npc_varian_wrynn::npc_varian_wrynnAI::SetHoldState (bool bOnHold) inline
Definition at line 1159 of file zone_undercity.cpp.
         {
             SetEscortPaused(bOnHold);
         }
References npc_escortAI::SetEscortPaused().
Referenced by WaypointReached().
SpawnWave()
void npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave (uint32 waveId) inline
Definition at line 1170 of file zone_undercity.cpp.
         {
             switch (waveId)
             {
                 case 0:
                     me->SummonCreature(NPC_GUARDIAN, AllianceSpawn[0].x, AllianceSpawn[0].y, AllianceSpawn[0].z, TEMPSUMMON_DEAD_DESPAWN);
                     break;
                 case 1:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                     {
                         switch (urand(0, 12))
{
                             case 0:
                                 me->SummonCreature(NPC_DREADLORD, AllianceSpawn[1].x + rand32() % 5, AllianceSpawn[1].y + rand32() % 5, AllianceSpawn[1].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                             case 2:
                             case 3:
                                 me->SummonCreature(NPC_DOCTOR, AllianceSpawn[1].x + rand32() % 5, AllianceSpawn[1].y + rand32() % 5, AllianceSpawn[1].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 4:
                             case 5:
                             case 6:
                                 me->SummonCreature(NPC_FELBEAST, AllianceSpawn[1].x + rand32() % 5, AllianceSpawn[1].y + rand32() % 5, AllianceSpawn[1].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 7:
                             case 8:
                             case 9:
                                 me->SummonCreature(NPC_BETRAYER, AllianceSpawn[1].x + rand32() % 5, AllianceSpawn[1].y + rand32() % 5, AllianceSpawn[1].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 10:
                             case 11:
                             case 12:
                                 me->SummonCreature(NPC_COLLABORATOR, AllianceSpawn[1].x + rand32() % 5, AllianceSpawn[1].y + rand32() % 5, AllianceSpawn[1].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 2:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                     {
                         switch (urand(0, 3))
{
                             case 0:
                                 me->SummonCreature(NPC_COLLABORATOR, AllianceSpawn[2].x - rand32() % 5, AllianceSpawn[2].y - rand32() % 5, AllianceSpawn[2].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DOCTOR, AllianceSpawn[2].x - rand32() % 5, AllianceSpawn[2].y - rand32() % 5, AllianceSpawn[2].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 2:
                                 me->SummonCreature(NPC_FELBEAST, AllianceSpawn[2].x - rand32() % 5, AllianceSpawn[2].y - rand32() % 5, AllianceSpawn[2].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 3:
                                 me->SummonCreature(NPC_BETRAYER, AllianceSpawn[2].x - rand32() % 5, AllianceSpawn[2].y - rand32() % 5, AllianceSpawn[2].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 3:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                     {
                         switch (urand(0, 4))
{
                             case 0:
                                 me->SummonCreature(NPC_GUARDIAN, AllianceSpawn[3].x - rand32() % 5, AllianceSpawn[3].y - rand32() % 5, AllianceSpawn[3].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                             case 2:
                                 me->SummonCreature(NPC_CHEMIST, AllianceSpawn[3].x - rand32() % 5, AllianceSpawn[3].y - rand32() % 5, AllianceSpawn[3].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 3:
                             case 4:
                                 me->SummonCreature(NPC_DOCTOR, AllianceSpawn[3].x - rand32() % 5, AllianceSpawn[3].y - rand32() % 5, AllianceSpawn[3].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 4:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                     {
                         switch (urand(0, 5))
{
                             case 0:
                                 if (Unit* temp = me->SummonCreature(NPC_DOCTOR, AllianceSpawn[4].x - rand32() % 5, AllianceSpawn[4].y - rand32() % 5, AllianceSpawn[4].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                             case 1:
                                 if (Unit* temp = me->SummonCreature(NPC_CHEMIST, AllianceSpawn[4].x - rand32() % 5, AllianceSpawn[4].y - rand32() % 5, AllianceSpawn[4].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                             case 2:
                                 if (Unit* temp = me->SummonCreature(NPC_BETRAYER, AllianceSpawn[4].x - rand32() % 5, AllianceSpawn[4].y - rand32() % 5, AllianceSpawn[4].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                             case 3:
                                 if (Unit* temp = me->SummonCreature(NPC_DOCTOR, AllianceSpawn[5].x - rand32() % 5, AllianceSpawn[5].y - rand32() % 5, AllianceSpawn[5].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                             case 4:
                                 if (Unit* temp = me->SummonCreature(NPC_CHEMIST, AllianceSpawn[5].x - rand32() % 5, AllianceSpawn[5].y - rand32() % 5, AllianceSpawn[5].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                             case 5:
                                 if (Unit* temp = me->SummonCreature(NPC_BETRAYER, AllianceSpawn[5].x - rand32() % 5, AllianceSpawn[5].y - rand32() % 5, AllianceSpawn[5].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                                 break;
                         }
                     }
                     break;
                 case 5:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                         if (Unit* temp = me->SummonCreature(NPC_GUARDIAN, AllianceSpawn[6].x - rand32() % 5, AllianceSpawn[6].y - rand32() % 5, AllianceSpawn[6].z, TEMPSUMMON_DEAD_DESPAWN))
                             temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), false);
                     break;
                 case 6:
                     if (Unit* temp = me->SummonCreature(NPC_BLIGHTWORM, AllianceSpawn[7].x, AllianceSpawn[7].y, AllianceSpawn[7].z, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         blightWormGUID = temp->GetGUID();
                         temp->AddThreat(me, 100.0f);
                         me->AddThreat(temp, 100.0f);
                         if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                             temp->AddThreat(jaina, 100.0f);
                             jaina->AddThreat(temp, 100.0f);
                         }
                     }
                     if (Unit* temp = me->SummonCreature(NPC_KHANOK, HordeSpawn[0].x, HordeSpawn[0].y, HordeSpawn[0].z, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         khanokGUID = temp->GetGUID();
                         if (Creature* khanok = ObjectAccessor::GetCreature(*me, khanokGUID))
                             khanok->setDeathState(JUST_DIED);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_PUTRESS, AllianceSpawn[12].x, AllianceSpawn[12].y, AllianceSpawn[12].z, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         putressGUID = temp->GetGUID();
                         temp->CastSpell(temp, SPELL_PUTRESS_CASTING_STATE);
                     }
                     for (uint8 i = 0; i < GENERATOR_MAXCOUNT; ++i)
                     {
                         switch (i)
{
                             case 0:
                                 if (Unit* temp = me->SummonCreature(NPC_GENERATOR, 1433.142212f, 402.493835f, -80.515945f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     generatorGUID[i] = temp->GetGUID();
                                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                         temp->CastSpell(putress, SPELL_BLIGHT_EMPOWERMENT);
                                 }
                                 break;
                             case 1:
                                 if (Unit* temp = me->SummonCreature(NPC_GENERATOR, 1428.677979f, 399.753418f, -79.141609f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     generatorGUID[i] = temp->GetGUID();
                                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                         temp->CastSpell(putress, SPELL_BLIGHT_EMPOWERMENT, false, 0, 0, generatorGUID[0]);
                                 }
                                 break;
                             case 2:
                                 if (Unit* temp = me->SummonCreature(NPC_GENERATOR, 1425.163330f, 402.268951f, -79.299744f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     generatorGUID[i] = temp->GetGUID();
                                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                         temp->CastSpell(putress, SPELL_BLIGHT_EMPOWERMENT, false, 0, 0, generatorGUID[0]);
                                 }
                                 break;
                             case 3:
                                 if (Unit* temp = me->SummonCreature(NPC_GENERATOR, 1427.323242f, 406.853088f, -78.195641f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     generatorGUID[i] = temp->GetGUID();
                                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                         temp->CastSpell(putress, SPELL_BLIGHT_EMPOWERMENT, false, 0, 0, generatorGUID[0]);
                                 }
                                 break;
                             case 4:
                                 if (Unit* temp = me->SummonCreature(NPC_GENERATOR, 1432.465210f, 407.460022f, -81.689384f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     generatorGUID[i] = temp->GetGUID();
                                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                         temp->CastSpell(putress, SPELL_BLIGHT_EMPOWERMENT, false, 0, 0, generatorGUID[0]);
                                 }
                                 break;
                         }
                     }
                     break;
                 case 7:
                     if (Unit* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[8].x, AllianceSpawn[8].y, AllianceSpawn[8].z, 0, TEMPSUMMON_TIMED_DESPAWN, 90000))
                     {
                         allianceGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePath(NPC_SW_SOLDIER * 10, false);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[8].x, AllianceSpawn[8].y, AllianceSpawn[8].z, 0, TEMPSUMMON_TIMED_DESPAWN, 90000))
                     {
                         allianceGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePath((NPC_SW_SOLDIER * 10) + 1, false);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[8].x, AllianceSpawn[8].y, AllianceSpawn[8].z, 0, TEMPSUMMON_TIMED_DESPAWN, 90000))
                     {
                         allianceGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePath((NPC_SW_SOLDIER * 10) + 2, false);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[8].x, AllianceSpawn[8].y, AllianceSpawn[8].z, 0, TEMPSUMMON_TIMED_DESPAWN, 90000))
                     {
                         allianceGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePath((NPC_SW_SOLDIER * 10) + 3, false);
                     }
                     break;
                 case 8:
                     break;
                 case 9:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                         me->SummonCreature(NPC_GUARDIAN, AllianceSpawn[10].x + rand32() % 13, AllianceSpawn[10].y + rand32() % 13, AllianceSpawn[10].z, TEMPSUMMON_DEAD_DESPAWN);
                     break;
                 case 10:
                     if (Unit* temp = me->SummonCreature(NPC_DREADLORD, AllianceSpawn[11].x, AllianceSpawn[11].y, AllianceSpawn[11].z, TEMPSUMMON_DEAD_DESPAWN))
                     {
                         temp->GetMotionMaster()->MovePath(NPC_DREADLORD * 10, false);
                         temp->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
                         temp->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, true);
                     }
                     break;
                 case 11:
                     for (uint8 i = 0; i < WAVE_MAXCOUNT; ++i)
                     {
                         switch (urand(0, 3))
{
                             case 0:
                                 if (Unit* temp = me->SummonCreature(NPC_EXPERIMENT, AllianceSpawn[13].x + rand32() % 5, AllianceSpawn[13].y + rand32() % 5, AllianceSpawn[13].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                                 break;
                             case 1:
                                 if (Unit* temp = me->SummonCreature(NPC_EXPERIMENT, AllianceSpawn[14].x + rand32() % 5, AllianceSpawn[14].y + rand32() % 5, AllianceSpawn[14].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                                 break;
                             case 2:
                                 if (Unit* temp = me->SummonCreature(NPC_EXPERIMENT, AllianceSpawn[15].x + rand32() % 5, AllianceSpawn[15].y + rand32() % 5, AllianceSpawn[15].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                                 break;
                             case 3:
                                 if (Unit* temp = me->SummonCreature(NPC_EXPERIMENT, AllianceSpawn[16].x + rand32() % 5, AllianceSpawn[16].y + rand32() % 5, AllianceSpawn[16].z, TEMPSUMMON_DEAD_DESPAWN))
                                     temp->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                                 break;
                         }
                     }
                     break;
                 case 12:
                     if (Creature* temp = me->SummonCreature(NPC_THRALL, AllianceSpawn[17].x, AllianceSpawn[17].y, AllianceSpawn[17].z, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         thrallGUID = temp->GetGUID();
                         temp->SetReactState(REACT_PASSIVE);
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                         temp->CastSpell(temp, SPELL_THRALL_BUFF);
                         temp->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                     }
                     if (Creature* temp = me->SummonCreature(NPC_SYLVANAS, AllianceSpawn[18].x, AllianceSpawn[18].y, AllianceSpawn[18].z, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         sylvanasGUID = temp->GetGUID();
                         temp->SetReactState(REACT_PASSIVE);
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                         temp->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                     }
                     for (uint8 i = 0; i < HORDE_FORCE_MAXCOUNT; ++i)
                     {
                         if (Creature* temp = me->SummonCreature(NPC_HORDE_SOLDIER, AllianceSpawn[i + 19].x, AllianceSpawn[i + 19].y, AllianceSpawn[i + 19].z, TEMPSUMMON_MANUAL_DESPAWN))
{
                             hordeForcesGUID[i] = temp->GetGUID();
                             temp->SetReactState(REACT_PASSIVE);
                             temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                             temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                             temp->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                         }
                     }
                     break;
                 case 13:
                     for (uint8 i = 0; i < ALLIANCE_FORCE_MAXCOUNT; ++i)
                     {
                         if (Unit* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[i + 25].x, AllianceSpawn[i + 25].y, AllianceSpawn[i + 25].z, AllianceSpawn[i + 25].o, TEMPSUMMON_MANUAL_DESPAWN))
{
                             allianceForcesGUID[i] = temp->GetGUID();
                             temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                             temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                             temp->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                         }
                     }
                     break;
             }
         }
References Unit::AddThreat(), ALLIANCE_FORCE_MAXCOUNT, allianceForcesGUID, allianceGuardsGUID, AllianceSpawn, blightWormGUID, EMOTE_STATE_READY2H, GENERATOR_MAXCOUNT, generatorGUID, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), HORDE_FORCE_MAXCOUNT, hordeForcesGUID, HordeSpawn, IMMUNITY_EFFECT, jainaGUID, JUST_DIED, khanokGUID, ScriptedAI::me, MotionMaster::MovePath(), MotionMaster::MovePoint(), NPC_BETRAYER, NPC_BLIGHTWORM, NPC_CHEMIST, NPC_COLLABORATOR, NPC_DOCTOR, NPC_DREADLORD, NPC_EXPERIMENT, NPC_FELBEAST, NPC_GENERATOR, NPC_GUARDIAN, NPC_HORDE_SOLDIER, NPC_KHANOK, NPC_PUTRESS, NPC_SW_SOLDIER, NPC_SYLVANAS, NPC_THRALL, Location::o, putressGUID, rand32(), REACT_PASSIVE, SPELL_BLIGHT_EMPOWERMENT, SPELL_EFFECT_KNOCK_BACK, SPELL_EFFECT_KNOCK_BACK_DEST, SPELL_PUTRESS_CASTING_STATE, SPELL_THRALL_BUFF, WorldObject::SummonCreature(), sylvanasGUID, TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, thrallGUID, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_EMOTESTATE, urand(), WAVE_MAXCOUNT, G3D::x, Location::x, G3D::y, Location::y, G3D::z, and Location::z.
Referenced by UpdateAI().
SummonedCreatureDies()
void npc_varian_wrynn::npc_varian_wrynnAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1126 of file zone_undercity.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_BLIGHTWORM:
                     UpdateWorldState(me->GetMap(), WORLD_STATE_SEWERS_FIGHT_A, 0);
                     UpdateWorldState(me->GetMap(), WORLD_STATE_SEWERS_DONE_A, 1);
                     bStepping = true;
                     break;
                 case NPC_PUTRESS:
                     UpdateWorldState(me->GetMap(), WORLD_STATE_APOTHECARIUM_FIGHT_A, 0);
                     UpdateWorldState(me->GetMap(), WORLD_STATE_APOTHECARIUM_DONE_A, 1);
                     bStepping = true;
                     break;
                 default:
                     break;
             }
         }
References bStepping, Object::GetEntry(), WorldObject::GetMap(), ScriptedAI::me, NPC_BLIGHTWORM, NPC_PUTRESS, UpdateWorldState(), WORLD_STATE_APOTHECARIUM_DONE_A, WORLD_STATE_APOTHECARIUM_FIGHT_A, WORLD_STATE_SEWERS_DONE_A, and WORLD_STATE_SEWERS_FIGHT_A.
UpdateAI()
void npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1527 of file zone_undercity.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             if (bStepping)
             {
                 if (phaseTimer <= diff)
                 {
                     switch (step)
                     {
                         //Preparation
                         case 0:
                             me->setActive(true);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_MANHUNT_COUNTDOWN_A, 1);
                             Talk(WRYNN_SAY_PREP_1);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 1:
                             Talk(WRYNN_SAY_PREP_2);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 2:
                             Talk(WRYNN_SAY_PREP_3);
                             JumpToNextStep(20 * IN_MILLISECONDS);
                             break;
                         case 3:
                             Talk(WRYNN_SAY_PREP_4);
                             JumpToNextStep(20 * IN_MILLISECONDS);
                             break;
                         case 4:
                             UpdateWorldState(me->GetMap(), WORLD_STATE_MANHUNT_COUNTDOWN_A, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_MANHUNT_STARTS_A, 1);
                             Talk(WRYNN_SAY_PREP_5);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 5:
                             DoCast(me, SPELL_WRYNN_BUFF);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 6:
                             Talk(WRYNN_SAY_PREP_6);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 7:
                             SetEscortPaused(false);
                             JumpToNextStep(1.5 * IN_MILLISECONDS);
                             break;
                         case 8:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->MovePath(NPC_JAINA * 10, false);
                                 jaina->setActive(true);
                             }
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         //Sewers
                         case 9:
                             Talk(WRYNN_SAY_SEWERS_1);
                             SpawnWave(0);
                             SpawnWave(1);
                             SpawnWave(2);
                             SpawnWave(3);
                             JumpToNextStep(9500);
                             break;
                         case 10:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                                 jaina->AI()->Talk(JAINA_SAY_SEWERS_1);
                             JumpToNextStep(2 * IN_MILLISECONDS);
                             break;
                         case 11:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                                 jaina->AI()->DoCast(SPELL_JAINA_BUFF);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 12:
                             SetEscortPaused(false);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_MANHUNT_STARTS_A, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_SEWERS_FIGHT_A, 1);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 13:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->MoveFollow(me, 5, PET_FOLLOW_ANGLE);
                                 jaina->SetReactState(REACT_AGGRESSIVE);
                                 jaina->SetFaction(FACTION_ESCORT_N_NEUTRAL_ACTIVE);
                             }
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 14:
                             Talk(WRYNN_SAY_SEWERS_2);
                             JumpToNextStep(3.5 * IN_MILLISECONDS);
                             break;
                         case 15:
                             SpawnWave(4);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 16:
                             SpawnWave(5);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 17:
                             SpawnWave(4);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 18:
                             SpawnWave(4);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 19:
                             SpawnWave(5);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 20:
                             SpawnWave(6);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 21:
                             Talk(WRYNN_SAY_SEWERS_3);
                             SpawnWave(7);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 22:
                             Talk(WRYNN_SAY_SEWERS_4);
                             SetRun(false);
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->Clear();
                                 jaina->GetMotionMaster()->MoveFollow(me, 1, 0);
                             }
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 23:
                             bStepping = false;
                             SetEscortPaused(false);
                             JumpToNextStep(0);
                             break;
                         //Apothecarium
                         case 24:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                                 jaina->AI()->Talk(JAINA_SAY_APO_1);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 25:
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 26:
                             me->SetStandState(UNIT_STAND_STATE_KNEEL);
                             me->SetTarget(khanokGUID);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 27:
                             Talk(WRYNN_SAY_APO_1);
                             JumpToNextStep(12 * IN_MILLISECONDS);
                             break;
                         case 28:
                             Talk(WRYNN_SAY_APO_2);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 29:
                             Talk(WRYNN_SAY_APO_3);
                             JumpToNextStep(1.5 * IN_MILLISECONDS);
                             break;
                         case 30:
                             UpdateWorldState(me->GetMap(), WORLD_STATE_APOTHECARIUM_FIGHT_A, 1);
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_1);
                             if (Player* player = GetPlayerForEscort())
                                 player->PlayDirectSound(SOUND_PUTRESS, player);
                             SpawnWave(9);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 31:
                             SetRun(true);
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                                 jaina->GetMotionMaster()->MoveFollow(me, 1, 0);
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 32:
                             Talk(WRYNN_SAY_APO_4);
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 33:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 34:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 35:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 36:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 37:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 38:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 39:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 40:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 41:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 42:
                             SpawnWave(10);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 43:
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 44:
                             Talk(WRYNN_SAY_APO_5);
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->Clear();
                                 jaina->GetMotionMaster()->MovePoint(0, AllianceWP[7].x, AllianceWP[7].y, AllianceWP[7].z, false);
                             }
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 45:
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 46:
                             Talk(WRYNN_SAY_APO_6);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 47:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_3);
                             SpawnWave(11);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 48:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_4);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 49:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_5);
                             SpawnWave(11);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 50:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_6);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 51:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                                 putress->AI()->Talk(PUTRESS_SAY_7);
                             SpawnWave(11);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 52:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
{
                                 putress->AI()->Talk(PUTRESS_SAY_8);
                                 putress->AI()->DoCast(SPELL_BLIGHT_OVERLOAD);
                             }
                             JumpToNextStep(0.5 * IN_MILLISECONDS);
                             break;
                         case 53:
                             if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
{
                                 putress->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 putress->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 putress->AddThreat(me, 100.0f);
                                 me->AddThreat(putress, 100.0f);
                                 putress->RemoveAura(SPELL_PUTRESS_CASTING_STATE);
                             }
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 54:
                             Talk(WRYNN_SAY_APO_7);
                             SetRun(false);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 55:
                             if (ObjectAccessor::GetCreature(*me, putressGUID))
                                 me->SetTarget(putressGUID);
                             Talk(WRYNN_SAY_APO_8);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 56:
                             Talk(WRYNN_SAY_APO_9);
                             me->RemoveStandFlags(UNIT_STAND_STATE_KNEEL);
                             me->SetStandFlags(UNIT_STAND_STATE_STAND);
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 57:
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 58:
                             Talk(WRYNN_SAY_APO_10);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 59:
                             Talk(WRYNN_SAY_APO_11);
                             JumpToNextStep(7.5 * IN_MILLISECONDS);
                             break;
                         case 60:
                             Talk(WRYNN_SAY_APO_12);
                             SpawnWave(12); // thrall sylvanas horde soldiers
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 61:
                             if (Creature* thrall = ObjectAccessor::GetCreature(*me, thrallGUID))
                                 thrall->AI()->Talk(THRALL_SAY_THRONE_A_1);
                             if (Player* player = GetPlayerForEscort())
                                 player->PlayDirectSound(SOUND_THRALL_1, player);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 62:
                             if (Creature* thrall = ObjectAccessor::GetCreature(*me, thrallGUID))
                                 thrall->AI()->Talk(THRALL_SAY_THRONE_A_2);
                             if (Player* player = GetPlayerForEscort())
                                 player->PlayDirectSound(SOUND_THRALL_2, player);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 63:
                             Talk(WRYNN_SAY_THRONE_1);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 64:
                             Talk(WRYNN_SAY_THRONE_2);
                             JumpToNextStep(1.5 * IN_MILLISECONDS);
                             break;
                         case 65:
                             SetRun(true);
                             SetEscortPaused(false);
                             JumpToNextStep(0.25 * IN_MILLISECONDS);
                             break;
                         case 66:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                                 jaina->AI()->Talk(JAINA_SAY_THRONE_1);
                             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 67:
                             Talk(WRYNN_SAY_THRONE_3);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 68:
                             Talk(WRYNN_SAY_THRONE_4);
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->MovePoint(0, AllianceWP[8].x, AllianceWP[8].y, AllianceWP[8].z);
                                 jaina->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 jaina->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                             }
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 69:
                             Talk(WRYNN_SAY_THRONE_5);
                             SpawnWave(13); //alliance soldiers
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 70:
                             Talk(WRYNN_SAY_THRONE_6);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 71:
                             Talk(WRYNN_SAY_THRONE_7);
                             JumpToNextStep(16.5 * IN_MILLISECONDS);
                             break;
                         case 72:
                             Talk(WRYNN_SAY_THRONE_8);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 73:
                             Talk(WRYNN_SAY_THRONE_9);
                             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                             if (Creature* thrall = ObjectAccessor::GetCreature(*me, thrallGUID))
{
                                 thrall->SetReactState(REACT_AGGRESSIVE);
                                 thrall->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 thrall->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 thrall->AddThreat(me, 100.0f);
                                 me->AddThreat(thrall, 100.0f);
                                 thrall->AI()->AttackStart(me);
                             }
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasGUID))
{
                                 sylvanas->SetReactState(REACT_AGGRESSIVE);
                                 sylvanas->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 sylvanas->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 sylvanas->AddThreat(me, 100.0f);
                                 sylvanas->AI()->AttackStart(me);
                                 me->AddThreat(sylvanas, 100.0f);
                             }
                             for (uint8 i = 0; i < HORDE_FORCE_MAXCOUNT; ++i)
{
                                 if (Creature* temp = ObjectAccessor::GetCreature(*me, hordeForcesGUID[i]))
{
                                     temp->SetReactState(REACT_AGGRESSIVE);
                                     temp->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                     temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 }
                             }
                             for (uint8 i = 0; i < ALLIANCE_FORCE_MAXCOUNT; ++i)
{
                                 if (Creature* temp = ObjectAccessor::GetCreature(*me, allianceForcesGUID[i]))
{
                                     if (Creature* temp2 = ObjectAccessor::GetCreature(*me, hordeForcesGUID[i]))
{
                                         temp->SetReactState(REACT_AGGRESSIVE);
                                         temp2->SetReactState(REACT_AGGRESSIVE);
                                         temp->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                                         temp2->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                                         temp->AddThreat(temp2, 100.0f);
                                         temp->AI()->AttackStart(temp2);
                                         temp2->AddThreat(temp, 100.0f);
                                     }
                                 }
                             }
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 74:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->GetMotionMaster()->MovePoint(0, AllianceWP[9].x, AllianceWP[9].y, AllianceWP[9].z);
                                 jaina->AI()->Talk(JAINA_SAY_THRONE_2);
                             }
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 75:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->AI()->DoCastAOE(SPELL_DEEPFREEZE);
                                 jaina->AI()->Talk(JAINA_SAY_THRONE_3);
                             }
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 76:
                             std::list<Creature*> HelperList;
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_SW_SOLDIER, 100.0f);
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_HORDE_SOLDIER, 100.0f);
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_JAINA, 100.0f);
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_SYLVANAS, 100.0f);
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_THRALL, 100.0f);
                             if (!HelperList.empty())
                                 for (std::list<Creature*>::iterator itr = HelperList.begin(); itr != HelperList.end(); itr++)
                                     (*itr)->DespawnOrUnsummon();
                             if (Map* map = me->GetMap())
{
                                 Map::PlayerList const& PlayerList = map->GetPlayers();
                                 for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
{
                                     if (Player* player = i->GetSource())
{
                                         if (me->IsInRange(player, 0.0f, 50.0f))
{
                                             if (player->GetTeamId() == TEAM_ALLIANCE)
{
                                                 player->RemoveAura(SPELL_WRYNN_BUFF);
                                                 player->RemoveAura(SPELL_JAINA_BUFF);
                                                 player->CompleteQuest(QUEST_BATTLE_A);
                                                 player->NearTeleportTo(-8445.213867f, 337.384277f, 121.746056f, 5.401534f, false);
                                             }
                                         }
                                     }
                                 }
                             }
                             UpdateWorldState(me->GetMap(), WORLD_STATE_MANHUNT_STARTS_A, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_SEWERS_DONE_A, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_APOTHECARIUM_DONE_A, 0);
                             me->DespawnOrUnsummon();
                             break;
                     }
                 }
                 else phaseTimer -= diff;
             }
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_WHIRLWIND:
                         DoCast(me, SPELL_WHIRLWIND);
                         _events.ScheduleEvent(EVENT_WHIRLWIND, 20 * IN_MILLISECONDS);
                         break;
                     case EVENT_HEROIC_LEAP:
                         DoCastVictim(SPELL_HEROIC_LEAP);
                         _events.ScheduleEvent(EVENT_HEROIC_LEAP, urand(15, 30) * IN_MILLISECONDS);
                         break;
                     case EVENT_AGGRO_JAINA:
                         if (me->GetVictim())
{
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
{
                                 jaina->AI()->AttackStart(me->GetVictim());
                             }
                         }
                         DoCast(me, SPELL_THUNDER);
                         _events.ScheduleEvent(EVENT_AGGRO_JAINA, 2 * IN_MILLISECONDS);
                         break;
                     case EVENT_WRYNN_BUFF:
                         DoCast(me, SPELL_WRYNN_BUFF);
                         _events.ScheduleEvent(EVENT_WRYNN_BUFF, 10 * IN_MILLISECONDS);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, Unit::AddThreat(), ALLIANCE_FORCE_MAXCOUNT, allianceForcesGUID, AllianceWP, MapRefMgr::begin(), bStepping, Creature::DespawnOrUnsummon(), diff(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EVENT_AGGRO_JAINA, EVENT_HEROIC_LEAP, EVENT_WHIRLWIND, EVENT_WRYNN_BUFF, EventMap::ExecuteEvent(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, ObjectAccessor::GetCreature(), WorldObject::GetCreatureListWithEntryInGrid(), WorldObject::GetMap(), npc_escortAI::GetPlayerForEscort(), Unit::GetVictim(), Unit::HasUnitState(), HORDE_FORCE_MAXCOUNT, hordeForcesGUID, IN_MILLISECONDS, WorldObject::IsInRange(), JAINA_SAY_APO_1, JAINA_SAY_SEWERS_1, JAINA_SAY_THRONE_1, JAINA_SAY_THRONE_2, JAINA_SAY_THRONE_3, jainaGUID, JumpToNextStep(), khanokGUID, ScriptedAI::me, NPC_HORDE_SOLDIER, NPC_JAINA, NPC_SW_SOLDIER, NPC_SYLVANAS, NPC_THRALL, PET_FOLLOW_ANGLE, phaseTimer, PUTRESS_SAY_1, PUTRESS_SAY_3, PUTRESS_SAY_4, PUTRESS_SAY_5, PUTRESS_SAY_6, PUTRESS_SAY_7, PUTRESS_SAY_8, putressGUID, QUEST_BATTLE_A, REACT_AGGRESSIVE, Object::RemoveFlag(), Unit::RemoveStandFlags(), EventMap::ScheduleEvent(), WorldObject::setActive(), npc_escortAI::SetEscortPaused(), Object::SetFlag(), npc_escortAI::SetRun(), Unit::SetStandFlags(), Unit::SetStandState(), Creature::SetTarget(), SOUND_PUTRESS, SOUND_THRALL_1, SOUND_THRALL_2, SpawnWave(), SPELL_BLIGHT_OVERLOAD, SPELL_DEEPFREEZE, SPELL_HEROIC_LEAP, SPELL_JAINA_BUFF, SPELL_PUTRESS_CASTING_STATE, SPELL_THUNDER, SPELL_WHIRLWIND, SPELL_WRYNN_BUFF, step, sylvanasGUID, CreatureAI::Talk(), TEAM_ALLIANCE, THRALL_SAY_THRONE_A_1, THRALL_SAY_THRONE_A_2, thrallGUID, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, EventMap::Update(), npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), UpdateWorldState(), urand(), WORLD_STATE_APOTHECARIUM_DONE_A, WORLD_STATE_APOTHECARIUM_FIGHT_A, WORLD_STATE_MANHUNT_COUNTDOWN_A, WORLD_STATE_MANHUNT_STARTS_A, WORLD_STATE_SEWERS_DONE_A, WORLD_STATE_SEWERS_FIGHT_A, WRYNN_SAY_APO_1, WRYNN_SAY_APO_10, WRYNN_SAY_APO_11, WRYNN_SAY_APO_12, WRYNN_SAY_APO_2, WRYNN_SAY_APO_3, WRYNN_SAY_APO_4, WRYNN_SAY_APO_5, WRYNN_SAY_APO_6, WRYNN_SAY_APO_7, WRYNN_SAY_APO_8, WRYNN_SAY_APO_9, WRYNN_SAY_PREP_1, WRYNN_SAY_PREP_2, WRYNN_SAY_PREP_3, WRYNN_SAY_PREP_4, WRYNN_SAY_PREP_5, WRYNN_SAY_PREP_6, WRYNN_SAY_SEWERS_1, WRYNN_SAY_SEWERS_2, WRYNN_SAY_SEWERS_3, WRYNN_SAY_SEWERS_4, WRYNN_SAY_THRONE_1, WRYNN_SAY_THRONE_2, WRYNN_SAY_THRONE_3, WRYNN_SAY_THRONE_4, WRYNN_SAY_THRONE_5, WRYNN_SAY_THRONE_6, WRYNN_SAY_THRONE_7, WRYNN_SAY_THRONE_8, WRYNN_SAY_THRONE_9, G3D::x, G3D::y, and G3D::z.
UpdateWorldState()
void npc_varian_wrynn::npc_varian_wrynnAI::UpdateWorldState (Map * map, uint32 id, uint32 state) inline
Definition at line 1145 of file zone_undercity.cpp.
         {
             Map::PlayerList const& players = map->GetPlayers();
             if (!players.isEmpty())
             {
                 for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                 {
                     if (Player* player = itr->GetSource())
                         player->SendUpdateWorldState(id, state);
                 }
             }
         }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), and LinkedListHead::isEmpty().
Referenced by SummonedCreatureDies(), and UpdateAI().
WaypointReached()
void npc_varian_wrynn::npc_varian_wrynnAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 1459 of file zone_undercity.cpp.
         {
             switch (waypointId)
             {
                 case 0:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 2:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 38:
                     if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                     {
                         jaina->GetMotionMaster()->Clear();
                         jaina->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                         jaina->SetReactState(REACT_AGGRESSIVE);
                     }
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 45:
                     SetHoldState(true);
                     bStepping = true;
                     if (Creature* jaina = ObjectAccessor::GetCreature(*me, jainaGUID))
                     {
                         jaina->GetMotionMaster()->Clear();
                         jaina->GetMotionMaster()->MovePoint(0, AllianceWP[6].x, AllianceWP[6].y, AllianceWP[6].z);
                     }
                     break;
                 case 46:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 48:
                     if (Creature* putress = ObjectAccessor::GetCreature(*me, putressGUID))
                         putress->AI()->Talk(PUTRESS_SAY_2);
                     if (Player* player = GetPlayerForEscort())
                         player->PlayDirectSound(SOUND_PUTRESS, player);
                     break;
                 case 50:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 63:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 65:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 66:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 87:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 88:
                     SetHoldState(true);
                     bStepping = true;
                     break;
             }
         }
References AllianceWP, bStepping, ObjectAccessor::GetCreature(), npc_escortAI::GetPlayerForEscort(), jainaGUID, ScriptedAI::me, PUTRESS_SAY_2, putressGUID, REACT_AGGRESSIVE, SetHoldState(), SOUND_PUTRESS, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, G3D::x, G3D::y, and G3D::z.
Member Data Documentation
_events
EventMap npc_varian_wrynn::npc_varian_wrynnAI::_events
Definition at line 1008 of file zone_undercity.cpp.
Referenced by Reset(), and UpdateAI().
allianceForcesGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::allianceForcesGUID[ALLIANCE_FORCE_MAXCOUNT]
Definition at line 1004 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
allianceGuardsGUID
GuidVector npc_varian_wrynn::npc_varian_wrynnAI::allianceGuardsGUID
Definition at line 1006 of file zone_undercity.cpp.
Referenced by npc_varian_wrynnAI(), Reset(), and SpawnWave().
blightWormGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::blightWormGUID
Definition at line 998 of file zone_undercity.cpp.
Referenced by Reset(), and SpawnWave().
bStepping
bool npc_varian_wrynn::npc_varian_wrynnAI::bStepping
Definition at line 988 of file zone_undercity.cpp.
Referenced by Reset(), SummonedCreatureDies(), UpdateAI(), and WaypointReached().
generatorGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::generatorGUID[GENERATOR_MAXCOUNT]
Definition at line 1003 of file zone_undercity.cpp.
Referenced by Reset(), and SpawnWave().
hordeForcesGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::hordeForcesGUID[HORDE_FORCE_MAXCOUNT]
Definition at line 1005 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
jainaGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::jainaGUID
Definition at line 996 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), UpdateAI(), and WaypointReached().
khanokGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::khanokGUID
Definition at line 999 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
phaseTimer
uint32 npc_varian_wrynn::npc_varian_wrynnAI::phaseTimer
Definition at line 992 of file zone_undercity.cpp.
Referenced by JumpToNextStep(), Reset(), and UpdateAI().
putressGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::putressGUID
Definition at line 997 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), UpdateAI(), and WaypointReached().
step
uint32 npc_varian_wrynn::npc_varian_wrynnAI::step
Definition at line 991 of file zone_undercity.cpp.
Referenced by JumpToNextStep(), Reset(), and UpdateAI().
summoned
bool npc_varian_wrynn::npc_varian_wrynnAI::summoned
Definition at line 989 of file zone_undercity.cpp.
sylvanasGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::sylvanasGUID
Definition at line 1001 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
thrallGUID
ObjectGuid npc_varian_wrynn::npc_varian_wrynnAI::thrallGUID
Definition at line 1000 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
whirlwindTimer
uint32 npc_varian_wrynn::npc_varian_wrynnAI::whirlwindTimer
Definition at line 994 of file zone_undercity.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/zone_undercity.cpp