Azerotcore-wotlk: Guardian Class Reference
Guardian Class Reference
#include <TemporarySummon.h>
Public Member Functions
Guardian (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
void InitStats (uint32 duration) override
bool InitStatsForLevel (uint8 level)
void InitSummon () override
bool UpdateStats (Stats stat) override
bool UpdateAllStats () override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers power) override
void UpdateAttackPowerAndDamage (bool ranged=false) override
void UpdateDamagePhysical (WeaponAttackType attType) override
Public Member Functions inherited from Minion
Minion (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
void RemoveFromWorld () override
Unit * GetOwner () const
float GetFollowAngle () const override
void SetFollowAngle (float angle)
bool IsPetGhoul () const
bool IsGuardianPet () const
void setDeathState (DeathState s, bool despawn=false) override
Public Member Functions inherited from TempSummon
TempSummon (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
~TempSummon () override=default
void Update (uint32 time) override
virtual void UnSummon (uint32 msTime=0)
void SetTempSummonType (TempSummonType type)
void SaveToDB (uint32, uint8, uint32) override
WorldObject * GetSummoner () const
Unit * GetSummonerUnit () const
Creature * GetSummonerCreatureBase () const
GameObject * GetSummonerGameObject () const
ObjectGuid GetSummonerGUID ()
TempSummonType const & GetSummonType ()
uint32 GetTimer ()
void SetTimer (uint32 t)
Public Member Functions inherited from Creature
Creature (bool isWorldObject=false)
~Creature () override
void AddToWorld () override
void SetObjectScale (float scale) override
void SetDisplayId (uint32 modelId) override
void DisappearAndDie ()
bool isVendorWithIconSpeak () const
bool Create (ObjectGuid::LowType guidlow, Map *map, uint32 phaseMask, uint32 Entry, uint32 vehId, float x, float y, float z, float ang, const CreatureData *data=nullptr)
bool LoadCreaturesAddon (bool reload=false)
void SelectLevel (bool changelevel=true)
void LoadEquipment (int8 id=1, bool force=false)
ObjectGuid::LowType GetSpawnId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
void SetCorpseDelay (uint32 delay)
uint32 GetCorpseDelay () const
bool IsRacialLeader () const
bool IsCivilian () const
bool IsTrigger () const
bool IsGuard () const
bool CanWalk () const
bool CanSwim () const override
This method check the current flag/status of a creature and its inhabit type.
bool CanEnterWater () const override
bool CanFly () const override
bool CanHover () const
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
void InitializeReactState ()
bool isCanInteractWithBattleMaster (Player *player, bool msg) const
bool isCanTrainingAndResetTalentsOf (Player *player) const
bool IsValidTrainerForPlayer (Player *player, uint32 *npcFlags=nullptr) const
bool CanCreatureAttack (Unit const *victim, bool skipDistCheck=false) const
void LoadSpellTemplateImmunity ()
bool IsImmunedToSpell (SpellInfo const *spellInfo) override
bool HasMechanicTemplateImmunity (uint32 mask) const
bool IsImmunedToSpellEffect (SpellInfo const *spellInfo, uint32 index) const override
bool isElite () const
bool isWorldBoss () const
bool IsDungeonBoss () const
bool IsImmuneToKnockback () const
bool IsAvoidingAOE () const
uint8 getLevelForTarget (WorldObject const *target) const override
bool IsInEvadeMode () const
bool IsEvadingAttacks () const
bool AIM_Initialize (CreatureAI *ai=nullptr)
void Motion_Initialize ()
CreatureAI * AI () const
bool SetWalk (bool enable) override
bool SetDisableGravity (bool disable, bool packetOnly=false) override
bool SetSwim (bool enable) override
bool SetCanFly (bool enable, bool packetOnly=false) override
bool SetWaterWalking (bool enable, bool packetOnly=false) override
bool SetFeatherFall (bool enable, bool packetOnly=false) override
bool SetHover (bool enable, bool packetOnly=false) override
bool HasSpellFocus (Spell const *focusSpell=nullptr) const
uint32 GetShieldBlockValue () const override
SpellSchoolMask GetMeleeDamageSchoolMask () const override
void SetMeleeDamageSchool (SpellSchools school)
void _AddCreatureSpellCooldown (uint32 spell_id, uint16 categoryId, uint32 end_time)
void AddSpellCooldown (uint32 spell_id, uint32, uint32 end_time, bool needSendToClient=false, bool forceSendToSpectator=false) override
bool HasSpellCooldown (uint32 spell_id) const override
uint32 GetSpellCooldown (uint32 spell_id) const
void ProhibitSpellSchool (SpellSchoolMask idSchoolMask, uint32 unTimeMs) override
bool IsSpellProhibited (SpellSchoolMask idSchoolMask) const
bool HasSpell (uint32 spellID) const override
void UpdateMovementFlags ()
bool UpdateEntry (uint32 entry, const CreatureData *data=nullptr, bool changelevel=true)
void UpdateResistances (uint32 school) override
void CalculateMinMaxDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, float &minDamage, float &maxDamage) override
void SetCanDualWield (bool value) override
int8 GetOriginalEquipmentId () const
uint8 GetCurrentEquipmentId ()
void SetCurrentEquipmentId (uint8 id)
float GetSpellDamageMod (int32 Rank)
VendorItemData const * GetVendorItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
TrainerSpellData const * GetTrainerSpells () const
CreatureTemplate const * GetCreatureTemplate () const
CreatureData const * GetCreatureData () const
void SetDetectionDistance (float dist)
CreatureAddon const * GetCreatureAddon () const
std::string GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
bool LoadFromDB (ObjectGuid::LowType guid, Map *map, bool allowDuplicate=false)
bool LoadCreatureFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true, bool gridLoad=false, bool allowDuplicate=false)
void SaveToDB ()
virtual void DeleteFromDB ()
ObjectGuid GetLootRecipientGUID () const
Player * GetLootRecipient () const
ObjectGuid::LowType GetLootRecipientGroupGUID () const
Group * GetLootRecipientGroup () const
bool hasLootRecipient () const
bool isTappedBy (Player const *player) const
bool CanGeneratePickPocketLoot () const
void SetPickPocketLootTime ()
void ResetPickPocketLootTime ()
void SetLootRecipient (Unit *unit, bool withGroup=true)
void AllLootRemovedFromCorpse ()
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
SpellInfo const * reachWithSpellAttack (Unit *victim)
SpellInfo const * reachWithSpellCure (Unit *victim)
bool CanStartAttack (Unit const *u) const
float GetAggroRange (Unit const *target) const
float GetAttackDistance (Unit const *player) const
float GetDetectionRange () const
void SendAIReaction (AiReaction reactionType)
Unit * SelectNearestTarget (float dist=0, bool playerOnly=false) const
Unit * SelectNearestTargetInAttackDistance (float dist) const
void DoFleeToGetAssistance ()
void CallForHelp (float fRadius)
void CallAssistance (Unit *target=nullptr)
void SetNoCallAssistance (bool val)
void SetNoSearchAssistance (bool val)
bool HasSearchedAssistance ()
bool CanAssistTo (const Unit *u, const Unit *enemy, bool checkfaction=true) const
bool _IsTargetAcceptable (const Unit *target) const
bool CanIgnoreFeignDeath () const
bool _CanDetectFeignDeathOf (const Unit *target) const
void UpdateMoveInLineOfSightState ()
bool IsMoveInLineOfSightDisabled ()
bool IsMoveInLineOfSightStrictlyDisabled ()
MovementGeneratorType GetDefaultMovementType () const
void SetDefaultMovementType (MovementGeneratorType mgt)
void RemoveCorpse (bool setSpawnTime=true, bool skipVisibility=false)
void DespawnOrUnsummon (Milliseconds msTimeToDespawn, Seconds forcedRespawnTimer)
void DespawnOrUnsummon (uint32 msTimeToDespawn=0)
void DespawnOnEvade ()
void RespawnOnEvade ()
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn (bool force=false)
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay)
float GetWanderDistance () const
void SetWanderDistance (float dist)
void SendZoneUnderAttackMessage (Player *attacker)
Send a message to LocalDefense channel for players opposition team in the zone.
void SetInCombatWithZone ()
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool isRegeneratingHealth ()
void SetRegeneratingHealth (bool c)
virtual uint8 GetPetAutoSpellSize () const
virtual uint32 GetPetAutoSpellOnPos (uint8 pos) const
void SetCannotReachTarget (bool cannotReach)
bool CanNotReachTarget () const
bool IsNotReachable () const
bool IsNotReachableAndNeedRegen () const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
void SetHomePosition (float x, float y, float z, float o)
void SetHomePosition (const Position &pos)
void GetHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetHomePosition () const
void SetTransportHomePosition (float x, float y, float z, float o)
void SetTransportHomePosition (const Position &pos)
void GetTransportHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetTransportHomePosition () const
uint32 GetWaypointPath () const
void LoadPath (uint32 pathid)
uint32 GetCurrentWaypointID () const
void UpdateWaypointID (uint32 wpID)
void SearchFormation ()
CreatureGroup const * GetFormation () const
CreatureGroup * GetFormation ()
void SetFormation (CreatureGroup *formation)
Unit * SelectVictim ()
void SetDisableReputationGain (bool disable)
bool IsReputationGainDisabled () const
bool IsDamageEnoughForLootingAndReward () const
void LowerPlayerDamageReq (uint32 unDamage)
void ResetPlayerDamageReq ()
uint32 GetOriginalEntry () const
void SetOriginalEntry (uint32 entry)
void SetTarget (ObjectGuid guid=ObjectGuid::Empty) override
void FocusTarget (Spell const *focusSpell, WorldObject const *target)
void ReleaseFocus (Spell const *focusSpell)
bool IsMovementPreventedByCasting () const override
time_t GetLastDamagedTime () const
std::shared_ptr< time_t > const & GetLastDamagedTimePtr () const
void SetLastDamagedTime (time_t val)
void SetLastDamagedTimePtr (std::shared_ptr< time_t > const &val)
bool IsFreeToMove ()
bool HasSwimmingFlagOutOfCombat () const
void RefreshSwimmingFlag (bool recheck=false)
void SetAssistanceTimer (uint32 value)
Public Member Functions inherited from Unit
~Unit () override
UnitAI * GetAI ()
void SetAI (UnitAI *newAI)
void AddToWorld () override
void RemoveFromWorld () override
void CleanupBeforeRemoveFromMap (bool finalCleanup)
void CleanupsBeforeDelete (bool finalCleanup=true) override
DiminishingLevels GetDiminishing (DiminishingGroup group)
void IncrDiminishing (DiminishingGroup group)
float ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, int32 limitduration)
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
void ClearDiminishings ()
float GetSpellMaxRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
float GetSpellMinRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
void Update (uint32 time) override
void setAttackTimer (WeaponAttackType type, int32 time)
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
int32 getAttackTimer (WeaponAttackType type) const
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
bool haveOffhandWeapon () const
bool CanDualWield () const
float GetCombatReach () const override
float GetMeleeReach () const
bool IsWithinRange (Unit const *obj, float dist) const
bool IsWithinCombatRange (const Unit *obj, float dist2compare) const
bool IsWithinMeleeRange (const Unit *obj, float dist=0.f) const
float GetMeleeRange (Unit const *target) const
bool GetRandomContactPoint (const Unit *target, float &x, float &y, float &z, bool force=false) const
void _addAttacker (Unit *pAttacker)
void _removeAttacker (Unit *pAttacker)
Unit * getAttackerForHelper () const
bool Attack (Unit *victim, bool meleeAttack)
void CastStop (uint32 except_spellid=0, bool withInstant=true)
bool AttackStop ()
void RemoveAllAttackers ()
AttackerSet const & getAttackers () const
bool GetMeleeAttackPoint (Unit *attacker, Position &pos)
bool isAttackingPlayer () const
Unit * GetVictim () const
void CombatStop (bool includingCast=false)
void CombatStopWithPets (bool includingCast=false)
void StopAttackFaction (uint32 faction_id)
Unit * SelectNearbyTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
Unit * SelectNearbyNoTotemTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
void SendMeleeAttackStop (Unit *victim=nullptr)
void SendMeleeAttackStart (Unit *victim, Player *sendTo=nullptr)
void AddUnitState (uint32 f)
bool HasUnitState (const uint32 f) const
void ClearUnitState (uint32 f)
uint32 GetUnitState () const
bool CanFreeMove () const
uint32 HasUnitTypeMask (uint32 mask) const
void AddUnitTypeMask (uint32 mask)
uint32 GetUnitTypeMask () const
bool IsSummon () const
bool IsGuardian () const
bool IsControllableGuardian () const
bool IsPet () const
bool IsHunterPet () const
bool IsTotem () const
bool IsVehicle () const
uint8 getLevel () const
uint8 getLevelForTarget (WorldObject const *) const override
void SetLevel (uint8 lvl, bool showLevelChange=true)
uint8 getRace (bool original=false) const
void setRace (uint8 race)
uint32 getRaceMask () const
uint8 getClass () const
uint32 getClassMask () const
uint8 getGender () const
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
uint32 GetArmor () const
void SetArmor (int32 val)
uint32 GetResistance (SpellSchools school) const
uint32 GetResistance (SpellSchoolMask mask) const
void SetResistance (SpellSchools school, int32 val)
uint32 GetHealth () const
uint32 GetMaxHealth () const
bool IsFullHealth () const
bool HealthBelowPct (int32 pct) const
bool HealthBelowPctDamaged (int32 pct, uint32 damage) const
bool HealthAbovePct (int32 pct) const
bool HealthAbovePctHealed (int32 pct, uint32 heal) const
float GetHealthPct () const
uint32 CountPctFromMaxHealth (int32 pct) const
uint32 CountPctFromCurHealth (int32 pct) const
float GetPowerPct (Powers power) const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetFullHealth ()
int32 ModifyHealth (int32 val)
int32 GetHealthGain (int32 dVal)
Powers getPowerType () const
void setPowerType (Powers power)
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
void SetPower (Powers power, uint32 val)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 val)
int32 ModifyPowerPct (Powers power, float pct, bool apply=true)
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint32 GetFaction () const
void SetFaction (uint32 faction)
FactionTemplateEntry const * GetFactionTemplateEntry () const
ReputationRank GetReactionTo (Unit const *target) const
ReputationRank GetFactionReactionTo (FactionTemplateEntry const *factionTemplateEntry, Unit const *target) const
bool IsHostileTo (Unit const *unit) const
bool IsHostileToPlayers () const
bool IsFriendlyTo (Unit const *unit) const
bool IsNeutralToAll () const
bool IsInPartyWith (Unit const *unit) const
bool IsInRaidWith (Unit const *unit) const
void GetPartyMembers (std::list< Unit * > &units)
bool IsContestedGuard () const
bool IsInSanctuary () const
bool IsPvP () const
bool IsFFAPvP () const
void SetPvP (bool state)
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
void SetStandState (uint8 state)
void SetStandFlags (uint8 flags)
void RemoveStandFlags (uint8 flags)
bool IsMounted () const
uint32 GetMountID () const
void Mount (uint32 mount, uint32 vehicleId=0, uint32 creatureEntry=0)
void Dismount ()
uint16 GetMaxSkillValueForLevel (Unit const *target=nullptr) const
void ProcDamageAndSpell (Unit *victim, uint32 procAttacker, uint32 procVictim, uint32 procEx, uint32 amount, WeaponAttackType attType=BASE_ATTACK, SpellInfo const *procSpellInfo=nullptr, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void ProcDamageAndSpellFor (bool isVictim, Unit *target, uint32 procFlag, uint32 procExtra, WeaponAttackType attType, SpellInfo const *procSpellInfo, uint32 damage, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void GetProcAurasTriggeredOnEvent (std::list< AuraApplication * > &aurasTriggeringProc, std::list< AuraApplication * > *procAuras, ProcEventInfo eventInfo)
void TriggerAurasProcOnEvent (CalcDamageInfo &damageInfo)
void TriggerAurasProcOnEvent (std::list< AuraApplication * > *myProcAuras, std::list< AuraApplication * > *targetProcAuras, Unit *actionTarget, uint32 typeMaskActor, uint32 typeMaskActionTarget, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell *spell, DamageInfo *damageInfo, HealInfo *healInfo)
void TriggerAurasProcOnEvent (ProcEventInfo &eventInfo, std::list< AuraApplication * > &procAuras)
void HandleEmoteCommand (uint32 anim_id)
void AttackerStateUpdate (Unit *victim, WeaponAttackType attType=BASE_ATTACK, bool extra=false)
void CalculateMeleeDamage (Unit *victim, uint32 damage, CalcDamageInfo *damageInfo, WeaponAttackType attackType=BASE_ATTACK, const bool sittingVictim=false)
void DealMeleeDamage (CalcDamageInfo *damageInfo, bool durabilityLoss)
void HandleProcExtraAttackFor (Unit *victim)
void CalculateSpellDamageTaken (SpellNonMeleeDamage *damageInfo, int32 damage, SpellInfo const *spellInfo, WeaponAttackType attackType=BASE_ATTACK, bool crit=false)
void DealSpellDamage (SpellNonMeleeDamage *damageInfo, bool durabilityLoss)
float GetMeleeCritChanceReduction () const
float GetRangedCritChanceReduction () const
float GetSpellCritChanceReduction () const
uint32 GetMeleeCritDamageReduction (uint32 damage) const
uint32 GetRangedCritDamageReduction (uint32 damage) const
uint32 GetSpellCritDamageReduction (uint32 damage) const
uint32 GetMeleeDamageReduction (uint32 damage) const
uint32 GetRangedDamageReduction (uint32 damage) const
uint32 GetSpellDamageReduction (uint32 damage) const
float MeleeSpellMissChance (const Unit *victim, WeaponAttackType attType, int32 skillDiff, uint32 spellId) const
SpellMissInfo MeleeSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo MagicSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo SpellHitResult (Unit *victim, SpellInfo const *spell, bool canReflect=false)
float GetUnitDodgeChance () const
float GetUnitParryChance () const
float GetUnitBlockChance () const
float GetUnitMissChance (WeaponAttackType attType) const
float GetUnitCriticalChance (WeaponAttackType attackType, const Unit *victim) const
int32 GetMechanicResistChance (const SpellInfo *spell)
bool CanUseAttackType (uint8 attacktype) const
uint32 GetShieldBlockValue (uint32 soft_cap, uint32 hard_cap) const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM, const SpellInfo *spellProto) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType, int32 crit_chance, int32 miss_chance, int32 dodge_chance, int32 parry_chance, int32 block_chance) const
bool IsVendor () const
bool IsTrainer () const
bool IsQuestGiver () const
bool IsGossip () const
bool IsTaxi () const
bool IsGuildMaster () const
bool IsBattleMaster () const
bool IsBanker () const
bool IsInnkeeper () const
bool IsSpiritHealer () const
bool IsSpiritGuide () const
bool IsTabardDesigner () const
bool IsAuctioner () const
bool IsArmorer () const
bool IsServiceProvider () const
bool IsSpiritService () const
bool IsCritter () const
bool IsInFlight () const
bool IsInCombat () const
bool IsInCombatWith (Unit const *who) const
bool IsPetInCombat () const
void CombatStart (Unit *target, bool initialAggro=true)
void CombatStartOnCast (Unit *target, bool initialAggro=true, uint32 duration=0)
void SetInCombatState (bool PvP, Unit *enemy=nullptr, uint32 duration=0)
void SetInCombatWith (Unit *enemy, uint32 duration=0)
void ClearInCombat ()
void ClearInPetCombat ()
uint32 GetCombatTimer () const
bool HasAuraTypeWithFamilyFlags (AuraType auraType, uint32 familyName, uint32 familyFlags) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura=0) const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr) const
bool HasStealthAura () const
bool HasInvisibilityAura () const
bool isFeared () const
bool isInRoots () const
bool IsPolymorphed () const
bool isFrozen () const
bool isTargetableForAttack (bool checkFakeDeath=true, Unit const *byWho=nullptr) const
bool IsValidAttackTarget (Unit const *target) const
bool _IsValidAttackTarget (Unit const *target, SpellInfo const *bySpell, WorldObject const *obj=nullptr) const
bool IsValidAssistTarget (Unit const *target) const
bool _IsValidAssistTarget (Unit const *target, SpellInfo const *bySpell) const
virtual bool IsInWater () const
virtual bool IsUnderWater () const
bool isInAccessiblePlaceFor (Creature const *c) const
void SendHealSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, uint32 OverHeal, uint32 Absorb, bool critical=false)
int32 HealBySpell (HealInfo &healInfo, bool critical=false)
void SendEnergizeSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
void EnergizeBySpell (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
SpellCastResult CastSpell (SpellCastTargets const &targets, SpellInfo const *spellInfo, CustomSpellValues const *value, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (GameObject *go, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (Unit *victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, CustomSpellValues const &value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
Aura * AddAura (uint32 spellId, Unit *target)
Aura * AddAura (SpellInfo const *spellInfo, uint8 effMask, Unit *target)
void SetAuraStack (uint32 spellId, Unit *target, uint32 stack)
void SendPlaySpellVisual (uint32 id)
void SendPlaySpellImpact (ObjectGuid guid, uint32 id)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, uint32 spellId, uint32 cooldown)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, PacketCooldowns const &cooldowns)
void DeMorph ()
void SendAttackStateUpdate (CalcDamageInfo *damageInfo)
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, uint8 SwingType, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, uint32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
void SendSpellNonMeleeReflectLog (SpellNonMeleeDamage *log, Unit *attacker)
void SendSpellNonMeleeDamageLog (Unit *target, SpellInfo const *spellInfo, uint32 Damage, SpellSchoolMask damageSchoolMask, uint32 AbsorbedDamage, uint32 Resist, bool PhysicalDamage, uint32 Blocked, bool CriticalHit=false)
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo)
void SendSpellMiss (Unit *target, uint32 spellID, SpellMissInfo missInfo)
void SendSpellDamageResist (Unit *target, uint32 spellId)
void SendSpellDamageImmune (Unit *target, uint32 spellId)
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool vehicleTeleport=false, bool withPet=false, bool removeTransport=false)
void SendTameFailure (uint8 result)
void SendTeleportPacket (Position &pos)
virtual bool UpdatePosition (float x, float y, float z, float ang, bool teleport=false)
bool UpdatePosition (const Position &pos, bool teleport=false)
void UpdateOrientation (float orientation)
Only server-side orientation update, does not broadcast to client.
void UpdateHeight (float newZ)
Only server-side height update, does not broadcast to client.
void KnockbackFrom (float x, float y, float speedXY, float speedZ)
void JumpTo (float speedXY, float speedZ, bool forward=true)
void JumpTo (WorldObject *obj, float speedZ)
void SendMonsterMove (float NewPosX, float NewPosY, float NewPosZ, uint32 TransitTime, SplineFlags sf=SPLINEFLAG_WALK_MODE)
void MonsterMoveWithSpeed (float x, float y, float z, float speed)
void SendMovementFlagUpdate (bool self=false)
void SendMovementWaterWalking (Player *sendTo)
void SendMovementFeatherFall (Player *sendTo)
void SendMovementHover (Player *sendTo)
void SetInFront (WorldObject const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *object)
void SendChangeCurrentVictimOpcode (HostileReference *pHostileReference)
void SendClearThreatListOpcode ()
void SendRemoveFromThreatListOpcode (HostileReference *pHostileReference)
void SendThreatListUpdate ()
void SendClearTarget ()
void BuildHeartBeatMsg (WorldPacket *data) const
bool IsAlive () const
bool isDying () const
bool isDead () const
DeathState getDeathState ()
ObjectGuid GetOwnerGUID () const
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetCreatorGUID () const
void SetCreatorGUID (ObjectGuid creator)
ObjectGuid GetMinionGUID () const
void SetMinionGUID (ObjectGuid guid)
ObjectGuid GetCharmerGUID () const
void SetCharmerGUID (ObjectGuid owner)
ObjectGuid GetCharmGUID () const
void SetPetGUID (ObjectGuid guid)
ObjectGuid GetPetGUID () const
void SetCritterGUID (ObjectGuid guid)
ObjectGuid GetCritterGUID () const
bool IsControlledByPlayer () const
bool IsCreatedByPlayer () const
ObjectGuid GetCharmerOrOwnerGUID () const
ObjectGuid GetCharmerOrOwnerOrOwnGUID () const
bool IsCharmedOwnedByPlayerOrPlayer () const
Player * GetSpellModOwner () const
Unit * GetOwner () const
Guardian * GetGuardianPet () const
Minion * GetFirstMinion () const
Unit * GetCharmer () const
Unit * GetCharm () const
Unit * GetCharmerOrOwner () const
Unit * GetCharmerOrOwnerOrSelf () const
Player * GetCharmerOrOwnerPlayerOrPlayerItself () const
Player * GetAffectingPlayer () const
void SetMinion (Minion *minion, bool apply)
void GetAllMinionsByEntry (std::list< Creature * > &Minions, uint32 entry)
void RemoveAllMinionsByEntry (uint32 entry)
void SetCharm (Unit *target, bool apply)
Unit * GetNextRandomRaidMemberOrPet (float radius)
bool SetCharmedBy (Unit *charmer, CharmType type, AuraApplication const *aurApp=nullptr)
void RemoveCharmedBy (Unit *charmer)
void RestoreFaction ()
Unit * GetFirstControlled () const
void RemoveAllControlled (bool onDeath=false)
bool IsCharmed () const
bool isPossessed () const
bool isPossessedByPlayer () const
bool isPossessing () const
bool isPossessing (Unit *u) const
CharmInfo * GetCharmInfo ()
CharmInfo * InitCharmInfo ()
void DeleteCharmInfo ()
void UpdateCharmAI ()
SharedVisionList const & GetSharedVisionList ()
void AddPlayerToVision (Player *player)
void RemovePlayerFromVision (Player *player)
bool HasSharedVision () const
void RemoveBindSightAuras ()
void RemoveCharmAuras ()
Pet * CreateTamedPetFrom (Creature *creatureTarget, uint32 spell_id=0)
Pet * CreateTamedPetFrom (uint32 creatureEntry, uint32 spell_id=0)
bool InitTamedPet (Pet *pet, uint8 level, uint32 spell_id)
Aura * _TryStackingOrRefreshingExistingAura (SpellInfo const *newAura, uint8 effMask, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, bool periodicReset=false)
void _AddAura (UnitAura *aura, Unit *caster)
AuraApplication * _CreateAuraApplication (Aura *aura, uint8 effMask)
void _ApplyAuraEffect (Aura *aura, uint8 effIndex)
void _ApplyAura (AuraApplication *aurApp, uint8 effMask)
void _UnapplyAura (AuraApplicationMap::iterator &i, AuraRemoveMode removeMode)
void _UnapplyAura (AuraApplication *aurApp, AuraRemoveMode removeMode)
void _RemoveNoStackAuraApplicationsDueToAura (Aura *aura)
void _RemoveNoStackAurasDueToAura (Aura *aura)
bool _IsNoStackAuraDueToAura (Aura *appliedAura, Aura *existingAura) const
void _RegisterAuraEffect (AuraEffect *aurEff, bool apply)
AuraMap & GetOwnedAuras ()
AuraMap const & GetOwnedAuras () const
void RemoveOwnedAura (AuraMap::iterator &i, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (Aura *aura, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, Aura *except=nullptr) const
AuraApplicationMap & GetAppliedAuras ()
AuraApplicationMap const & GetAppliedAuras () const
void RemoveAura (AuraApplicationMap::iterator &i, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (AuraApplication *aurApp, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (Aura *aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAppliedAuras (std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (std::function< bool(Aura const *)> const &check)
void RemoveAppliedAuras (uint32 spellId, std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (uint32 spellId, std::function< bool(Aura const *)> const &check)
void RemoveAurasDueToSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraFromStack (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellByDispel (uint32 spellId, uint32 dispellerSpellId, ObjectGuid casterGUID, Unit *dispeller, uint8 chargesRemoved=1)
void RemoveAurasDueToSpellBySteal (uint32 spellId, ObjectGuid casterGUID, Unit *stealer)
void RemoveAurasDueToItemSpell (uint32 spellId, ObjectGuid castItemGuid)
void RemoveAurasByType (AuraType auraType, ObjectGuid casterGUID=ObjectGuid::Empty, Aura *except=nullptr, bool negative=true, bool positive=true)
void RemoveNotOwnSingleTargetAuras ()
void RemoveAurasWithInterruptFlags (uint32 flag, uint32 except=0)
void RemoveAurasWithAttribute (uint32 flags)
void RemoveAurasWithFamily (SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID)
void RemoveAurasWithMechanic (uint32 mechanic_mask, AuraRemoveMode removemode=AURA_REMOVE_BY_DEFAULT, uint32 except=0)
void RemoveMovementImpairingAuras (bool withRoot)
void RemoveAurasByShapeShift ()
void RemoveAreaAurasDueToLeaveWorld ()
void RemoveAllAuras ()
void RemoveArenaAuras ()
void RemoveAllAurasOnDeath ()
void RemoveAllAurasRequiringDeadTarget ()
void RemoveAllAurasExceptType (AuraType type)
void RemoveEvadeAuras ()
void DelayOwnedAuras (uint32 spellId, ObjectGuid caster, int32 delaytime)
void _RemoveAllAuraStatMods ()
void _ApplyAllAuraStatMods ()
AuraEffectList const & GetAuraEffectsByType (AuraType type) const
AuraList & GetSingleCastAuras ()
AuraList const & GetSingleCastAuras () const
AuraEffect * GetAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectOfRankedSpell (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectDummy (uint32 spellid) const
AuraEffect * GetDummyAuraEffect (SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraApplication * GetAuraApplication (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
AuraApplication * GetAuraApplicationOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAuraOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
void GetDispellableAuraList (Unit *caster, uint32 dispelMask, DispelChargesList &dispelList)
bool HasAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid caster=ObjectGuid::Empty) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
bool HasAuraType (AuraType auraType) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasAuraTypeWithMiscvalue (AuraType auratype, int32 miscvalue) const
bool HasAuraTypeWithAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
bool HasAuraTypeWithValue (AuraType auratype, int32 value) const
bool HasNegativeAuraWithInterruptFlag (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasVisibleAuraType (AuraType auraType) const
bool HasNegativeAuraWithAttribute (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasAuraWithMechanic (uint32 mechanicMask) const
AuraEffect * IsScriptOverriden (SpellInfo const *spell, int32 script) const
uint32 GetDiseasesByCaster (ObjectGuid casterGUID, uint8 mode=0)
uint32 GetDoTsByCaster (ObjectGuid casterGUID) const
int32 GetTotalAuraModifierAreaExclusive (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype)
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask, const AuraEffect *except=nullptr) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetTotalAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetTotalAuraMultiplierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxPositiveAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxNegativeAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetResistanceBuffMods (SpellSchools school, bool positive) const
void SetResistanceBuffMods (SpellSchools school, bool positive, float val)
void ApplyResistanceBuffModsMod (SpellSchools school, bool positive, float val, bool apply)
void ApplyResistanceBuffModsPercentMod (SpellSchools school, bool positive, float val, bool apply)
void InitStatBuffMods ()
void ApplyStatBuffMod (Stats stat, float val, bool apply)
void ApplyStatPercentBuffMod (Stats stat, float val, bool apply)
void SetCreateStat (Stats stat, float val)
void SetCreateHealth (uint32 val)
uint32 GetCreateHealth () const
void SetCreateMana (uint32 val)
uint32 GetCreateMana () const
uint32 GetCreatePowers (Powers power) const
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
float GetCreateStat (Stats stat) const
void SetCurrentCastedSpell (Spell *pSpell)
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool withInstant=true, bool bySelf=false)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
bool IsNonMeleeSpellCast (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool isAutoshoot=false, bool skipInstant=true) const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spellid=0, bool withInstant=true, bool bySelf=false)
bool CanMoveDuringChannel () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * GetCurrentSpell (uint32 spellType) const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
int32 GetCurrentSpellCastTime (uint32 spell_id) const
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsInFeralForm () const
bool IsInDisallowedMountForm () const
bool HandleStatModifier (UnitMods unitMod, UnitModifierType modifierType, float amount, bool apply)
void SetModifierValue (UnitMods unitMod, UnitModifierType modifierType, float value)
float GetModifierValue (UnitMods unitMod, UnitModifierType modifierType) const
float GetTotalStatValue (Stats stat, float additionalValue=0.0f) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
Stats GetStatByAuraGroup (UnitMods unitMod) const
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
bool CanModifyStats () const
void SetCanModifyStats (bool modifyStats)
virtual void UpdateAllResistances ()
float GetTotalAttackPowerValue (WeaponAttackType attType, Unit *pVictim=nullptr) const
float GetWeaponDamageRange (WeaponAttackType attType, WeaponDamageRange type) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, bool addTotalPct)
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
bool isInFrontInMap (Unit const *target, float distance, float arc=M_PI) const
bool isInBackInMap (Unit const *target, float distance, float arc=M_PI) const
bool IsVisible () const
void SetVisible (bool x)
void SetModelVisible (bool on)
uint32 GetPhaseByAuras () const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false) override
bool CanHaveThreatList () const
void AddThreat (Unit *victim, float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void DeleteThreatList ()
void TauntApply (Unit *victim)
void TauntFadeOut (Unit *taunter)
ThreatMgr & getThreatMgr ()
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefMgr & getHostileRefMgr ()
VisibleAuraMap const * GetVisibleAuras ()
AuraApplication * GetVisibleAura (uint8 slot)
void SetVisibleAura (uint8 slot, AuraApplication *aur)
void RemoveVisibleAura (uint8 slot)
uint32 GetInterruptMask () const
void AddInterruptMask (uint32 mask)
void UpdateInterruptMask ()
uint32 GetDisplayId ()
uint32 GetNativeDisplayId () const
void RestoreDisplayId ()
void SetNativeDisplayId (uint32 modelId)
void setTransForm (uint32 spellid)
uint32 getTransForm () const
void _RegisterDynObject (DynamicObject *dynObj)
void _UnregisterDynObject (DynamicObject *dynObj)
DynamicObject * GetDynObject (uint32 spellId)
void RemoveDynObject (uint32 spellId)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
void ModifyAuraState (AuraStateType flag, bool apply)
uint32 BuildAuraStateUpdateForTarget (Unit *target) const
bool HasAuraState (AuraStateType flag, SpellInfo const *spellProto=nullptr, Unit const *Caster=nullptr) const
void UnsummonAllTotems (bool onDeath=false)
Unit * GetMagicHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo)
Unit * GetMeleeHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo=nullptr)
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask, bool isDoT=false)
float SpellPctDamageModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellDamageBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellDamageBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseHealingBonusTaken (SpellSchoolMask schoolMask)
float SpellPctHealingModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellHealingBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellHealingBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, uint32 stack=1)
uint32 MeleeDamageBonusDone (Unit *pVictim, uint32 damage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
uint32 MeleeDamageBonusTaken (Unit *attacker, uint32 pdamage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
bool isSpellBlocked (Unit *victim, SpellInfo const *spellProto, WeaponAttackType attackType=BASE_ATTACK)
bool isBlockCritical ()
float SpellDoneCritChance (Unit const *, SpellInfo const *spellProto, SpellSchoolMask schoolMask, WeaponAttackType attackType, bool skipEffectCheck) const
float SpellTakenCritChance (Unit const *caster, SpellInfo const *spellProto, SpellSchoolMask schoolMask, float doneChance, WeaponAttackType attackType, bool skipEffectCheck) const
void SetLastManaUse (uint32 spellCastTime)
bool IsUnderLastManaUseEffect () const
void SetContestedPvP (Player *attackedPlayer=nullptr, bool lookForNearContestedGuards=true)
uint32 GetCastingTimeForBonus (SpellInfo const *spellProto, DamageEffectType damagetype, uint32 CastingTime) const
float CalculateDefaultCoefficient (SpellInfo const *spellInfo, DamageEffectType damagetype) const
void CastDelayedSpellWithPeriodicAmount (Unit *caster, uint32 spellId, AuraType auraType, int32 addAmount, uint8 effectIndex=0)
void ApplySpellImmune (uint32 spellId, uint32 op, uint32 type, bool apply, SpellImmuneBlockType blockType=SPELL_BLOCK_TYPE_ALL)
void ApplySpellDispelImmunity (const SpellInfo *spellProto, DispelType type, bool apply)
bool IsImmunedToDamage (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamage (SpellInfo const *spellInfo) const
bool IsImmunedToSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToSchool (SpellInfo const *spellInfo) const
bool IsImmunedToDamageOrSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamageOrSchool (SpellInfo const *spellInfo) const
void UpdateSpeed (UnitMoveType mtype, bool forced)
float GetSpeed (UnitMoveType mtype) const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeed (UnitMoveType mtype, float rate, bool forced=false)
void SetSpeedRate (UnitMoveType mtype, float rate)
float ApplyEffectModifiers (SpellInfo const *spellProto, uint8 effect_index, float value) const
int32 CalculateSpellDamage (Unit const *target, SpellInfo const *spellProto, uint8 effect_index, int32 const *basePoints=nullptr) const
int32 CalcSpellDuration (SpellInfo const *spellProto)
int32 ModSpellDuration (SpellInfo const *spellProto, Unit const *target, int32 duration, bool positive, uint32 effectMask)
void ModSpellCastTime (SpellInfo const *spellProto, int32 &castTime, Spell *spell=nullptr)
float CalculateLevelPenalty (SpellInfo const *spellProto) const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
MotionMaster * GetMotionMaster ()
const MotionMaster * GetMotionMaster () const
bool IsStopped () const
void StopMoving ()
-------—End of Pet responses methods-------—
void StopMovingOnCurrentPos ()
void AddUnitMovementFlag (uint32 f)
void RemoveUnitMovementFlag (uint32 f)
bool HasUnitMovementFlag (uint32 f) const
uint32 GetUnitMovementFlags () const
void SetUnitMovementFlags (uint32 f)
void AddExtraUnitMovementFlag (uint16 f)
void RemoveExtraUnitMovementFlag (uint16 f)
uint16 HasExtraUnitMovementFlag (uint16 f) const
uint16 GetExtraUnitMovementFlags () const
void SetExtraUnitMovementFlags (uint16 f)
void SetControlled (bool apply, UnitState state)
void DisableRotate (bool apply)
void DisableSpline ()
void AddComboPointHolder (ObjectGuid lowguid)
void RemoveComboPointHolder (ObjectGuid lowguid)
void ClearComboPointHolders ()
void SendPetActionFeedback (uint8 msg)
-------—Pet responses methods--------------—
void SendPetTalk (uint32 pettalk)
void SendPetAIReaction (ObjectGuid guid)
void propagateSpeedChange ()
-------—End of Pet responses methods-------—
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
void UpdateAuraForGroup (uint8 slot)
bool CanProc ()
void SetCantProc (bool apply)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void CastPetAura (PetAura const *aura)
bool IsPetAura (Aura const *aura)
uint32 GetModelForForm (ShapeshiftForm form) const
uint32 GetModelForTotem (PlayerTotemType totemType)
void SetRedirectThreat (ObjectGuid guid, uint32 pct)
void ResetRedirectThreat ()
void ModifyRedirectThreat (int32 amount)
uint32 GetRedirectThreatPercent ()
Unit * GetRedirectThreatTarget () const
bool CreateVehicleKit (uint32 id, uint32 creatureEntry)
void RemoveVehicleKit ()
Vehicle * GetVehicleKit () const
Vehicle * GetVehicle () const
bool IsOnVehicle (const Unit *vehicle) const
Unit * GetVehicleBase () const
Creature * GetVehicleCreatureBase () const
ObjectGuid GetTransGUID () const override
TransportBase * GetDirectTransport () const
Returns the transport this unit is on directly (if on vehicle and transport, return vehicle)
bool HandleSpellClick (Unit *clicker, int8 seatId=-1)
void EnterVehicle (Unit *base, int8 seatId=-1)
void EnterVehicleUnattackable (Unit *base, int8 seatId=-1)
void ExitVehicle (Position const *exitPosition=nullptr)
void ChangeSeat (int8 seatId, bool next=true)
void _ExitVehicle (Position const *exitPosition=nullptr)
void _EnterVehicle (Vehicle *vehicle, int8 seatId, AuraApplication const *aurApp=nullptr)
void BuildMovementPacket (ByteBuffer *data) const
bool IsLevitating () const
bool IsWalking () const
bool isMoving () const
bool isTurning () const
bool IsHovering () const
bool isSwimming () const
bool IsFlying () const
bool IsFalling () const
float GetHoverHeight () const
void RewardRage (uint32 damage, uint32 weaponSpeedHitFactor, bool attacker)
void OutDebugInfo () const
virtual bool isBeingLoaded () const
bool IsDuringRemoveFromWorld () const
Pet * ToPet ()
Totem * ToTotem ()
TempSummon * ToTempSummon ()
const TempSummon * ToTempSummon () const
void AddPointedBy (SafeUnitPointer *sup)
void RemovePointedBy (SafeUnitPointer *sup)
void ExecuteDelayedUnitRelocationEvent ()
void ExecuteDelayedUnitAINotifyEvent ()
virtual bool HasSpellItemCooldown (uint32, uint32) const
bool CanApplyResilience () const
void PetSpellFail (const SpellInfo *spellInfo, Unit *target, uint32 result)
int32 CalculateAOEDamageReduction (int32 damage, uint32 schoolMask, Unit *caster) const
ObjectGuid GetTarget () const
void SetInstantCast (bool set)
bool CanInstantCast () const
virtual void Talk (std::string_view text, ChatMsg msgType, Language language, float textRange, WorldObject const *target)
virtual void Say (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void Yell (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void TextEmote (std::string_view text, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (std::string_view text, Language language, Player *target, bool isBossWhisper=false)
virtual void Talk (uint32 textId, ChatMsg msgType, float textRange, WorldObject const *target)
virtual void Say (uint32 textId, WorldObject const *target=nullptr)
virtual void Yell (uint32 textId, WorldObject const *target=nullptr)
virtual void TextEmote (uint32 textId, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (uint32 textId, Player *target, bool isBossWhisper=false)
float GetCollisionHeight () const override
Return collision height sent to client.
float GetCollisionWidth () const override
this method gets the diameter of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
float GetCollisionRadius () const override
this method gets the radius of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
void ProcessPositionDataChanged (PositionFullTerrainStatus const &data) override
virtual void ProcessTerrainStatusUpdate ()
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< Creature >
bool IsInGrid () const
void AddToGrid (GridRefMgr< Creature > &m)
void RemoveFromGrid ()
Additional Inherited Members
Public Types inherited from Unit
typedef std::unordered_set< Unit * > AttackerSet
typedef std::set< Unit * > ControlSet
typedef std::multimap< uint32, Aura * > AuraMap
typedef std::pair< AuraMap::const_iterator, AuraMap::const_iterator > AuraMapBounds
typedef std::pair< AuraMap::iterator, AuraMap::iterator > AuraMapBoundsNonConst
typedef std::multimap< uint32, AuraApplication * > AuraApplicationMap
typedef std::pair< AuraApplicationMap::const_iterator, AuraApplicationMap::const_iterator > AuraApplicationMapBounds
typedef std::pair< AuraApplicationMap::iterator, AuraApplicationMap::iterator > AuraApplicationMapBoundsNonConst
typedef std::multimap< AuraStateType, AuraApplication * > AuraStateAurasMap
typedef std::pair< AuraStateAurasMap::const_iterator, AuraStateAurasMap::const_iterator > AuraStateAurasMapBounds
typedef std::list< AuraEffect * > AuraEffectList
typedef std::list< Aura * > AuraList
typedef std::list< AuraApplication * > AuraApplicationList
typedef std::list< DiminishingReturn > Diminishing
typedef GuidUnorderedSet ComboPointHolderSet
typedef std::map< uint8, AuraApplication * > VisibleAuraMap
typedef std::set< PetAura const * > PetAuraSet
Static Public Member Functions inherited from Creature
static float _GetDamageMod (int32 Rank)
Static Public Member Functions inherited from Unit
static float GetEffectiveResistChance (Unit const *owner, SpellSchoolMask schoolMask, Unit const *victim, SpellInfo const *spellInfo=nullptr)
static void DealDamageMods (Unit const *victim, uint32 &damage, uint32 *absorb)
static uint32 DealDamage (Unit *attacker, Unit *victim, uint32 damage, CleanDamage const *cleanDamage=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *spellProto=nullptr, bool durabilityLoss=true, bool allowGM=false)
static void Kill (Unit *killer, Unit *victim, bool durabilityLoss=true, WeaponAttackType attackType=BASE_ATTACK, SpellInfo const *spellProto=nullptr)
static int32 DealHeal (Unit *healer, Unit *victim, uint32 addhealth)
static void ApplyResilience (const Unit *victim, float *crit, int32 *damage, bool isCrit, CombatRating type)
static uint32 SpellCriticalDamageBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static uint32 SpellCriticalHealingBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static bool IsDamageReducedByArmor (SpellSchoolMask damageSchoolMask, SpellInfo const *spellInfo=nullptr, uint8 effIndex=MAX_SPELL_EFFECTS)
static uint32 CalcArmorReducedDamage (Unit const *attacker, Unit const *victim, const uint32 damage, SpellInfo const *spellInfo, uint8 attackerLevel=0, WeaponAttackType attackType=MAX_ATTACK)
static void CalcAbsorbResist (DamageInfo &dmgInfo, bool Splited=false)
static void CalcHealAbsorb (HealInfo &healInfo)
static void HandleSafeUnitPointersOnDelete (Unit *thisUnit)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes inherited from TempSummon
const SummonPropertiesEntry *const m_Properties
Public Attributes inherited from Creature
struct {
::Spell const * Spell = nullptr
uint32 Delay = 0
ObjectGuid Target
float Orientation = 0.0f
} _spellFocusInfo
Loot loot
uint32 m_spells [MAX_CREATURE_SPELLS]
CreatureSpellCooldowns m_CreatureSpellCooldowns
uint32 m_ProhibitSchoolTime [7]
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
uint32 m_PlayerDamageReq
float m_SightDistance
float m_CombatDistance
bool m_isTempWorldObject
uint32 m_moveCircleMovementTime = MOVE_CIRCLE_CHECK_INTERVAL
uint32 m_moveBackwardsMovementTime = MOVE_BACKWARDS_CHECK_INTERVAL
Public Attributes inherited from Unit
uint32 m_extraAttacks
bool m_canDualWield
ControlSet m_Controlled
SafeUnitPointer m_movedByPlayer
ObjectGuid m_SummonSlot [MAX_SUMMON_SLOT]
ObjectGuid m_ObjectSlot [MAX_GAMEOBJECT_SLOT]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
int32 m_baseSpellCritChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
EventProcessor m_Events
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_lastSanctuaryTime
PetAuraSet m_petAuras
bool IsAIEnabled
bool NeedChangeAI
bool m_ControlledByPlayer
bool m_CreatedByPlayer
std::set< SafeUnitPointer * > SafeUnitPointerSet
Position m_last_notify_position
uint32 m_last_notify_mstime
uint16 m_delayed_unit_relocation_timer
uint16 m_delayed_unit_ai_notify_timer
bool bRequestForcedVisibilityUpdate
Movement::MoveSpline * movespline
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes inherited from Creature
static constexpr uint32 MOVE_CIRCLE_CHECK_INTERVAL = 3000
static constexpr uint32 MOVE_BACKWARDS_CHECK_INTERVAL = 2000
Protected Types inherited from Unit
typedef std::list< DynamicObject * > DynObjectList
typedef GuidList GameObjectList
typedef std::map< ObjectGuid, float > CharmThreatMap
Protected Member Functions inherited from Creature
bool CreateFromProto (ObjectGuid::LowType guidlow, uint32 Entry, uint32 vehId, const CreatureData *data=nullptr)
bool InitEntry (uint32 entry, const CreatureData *data=nullptr)
void RegenerateHealth ()
void Regenerate (Powers power)
bool IsInvisibleDueToDespawn () const override
bool CanAlwaysSee (WorldObject const *obj) const override
Protected Member Functions inherited from Unit
Unit (bool isWorldObject)
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const override
void _UpdateSpells (uint32 time)
void _DeleteRemovedAuras ()
void _UpdateAutoRepeatSpell ()
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsAlwaysDetectableFor (WorldObject const *seer) const override
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Static Protected Member Functions inherited from Creature
static float _GetHealthMod (int32 Rank)
Protected Attributes inherited from Minion
const ObjectGuid m_owner
float m_followAngle
Protected Attributes inherited from Creature
VendorItemCounts m_vendorItemCounts
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
time_t m_corpseRemoveTime
Timers.
time_t m_respawnTime
time_t m_respawnedTime
uint32 m_respawnDelay
uint32 m_corpseDelay
float m_wanderDistance
uint16 m_transportCheckTimer
uint32 lootPickPocketRestoreTime
ReactStates m_reactState
MovementGeneratorType m_defaultMovementType
ObjectGuid::LowType m_spawnId
For new or temporary creatures is 0 for saved it is lowguid.
uint8 m_equipmentId
int8 m_originalEquipmentId
uint8 m_originalAnimTier
bool m_AlreadyCallAssistance
bool m_AlreadySearchedAssistance
bool m_regenHealth
bool m_AI_locked
SpellSchoolMask m_meleeDamageSchoolMask
uint32 m_originalEntry
bool m_moveInLineOfSightDisabled
bool m_moveInLineOfSightStrictlyDisabled
Position m_homePosition
Position m_transportHomePosition
bool DisableReputationGain
CreatureTemplate const * m_creatureInfo
CreatureData const * m_creatureData
float m_detectionDistance
uint16 m_LootMode
Protected Attributes inherited from Unit
UnitAI * i_AI
UnitAI * i_disabledAI
uint8 m_realRace
uint8 m_race
bool m_AutoRepeatFirstCast
int32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
AttackerSet m_attackers
Unit * m_attacking
DeathState m_deathState
int32 m_procDeep
DynObjectList m_dynObj
GameObjectList m_gameObj
uint32 m_transform
Spell * m_currentSpells [CURRENT_MAX_SPELL]
AuraMap m_ownedAuras
AuraApplicationMap m_appliedAuras
AuraList m_removedAuras
AuraMap::iterator m_auraUpdateIterator
uint32 m_removedAurasCount
AuraEffectList m_modAuras [TOTAL_AURAS]
AuraList m_scAuras
AuraApplicationList m_interruptableAuras
AuraStateAurasMap m_auraStateAuras
uint32 m_interruptMask
float m_auraModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_END]
float m_weaponDamage [MAX_ATTACK][2]
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
SharedVisionList m_sharedVision
MotionMaster * i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
int32 m_regenTimer
ThreatMgr m_ThreatMgr
CharmThreatMap _charmThreatInfo
Vehicle * m_vehicle
Vehicle * m_vehicleKit
uint32 m_unitTypeMask
LiquidTypeEntry const * _lastLiquid
bool m_applyResilience
bool _instantCast
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Detailed Description
Definition at line 85 of file TemporarySummon.h.
Constructor & Destructor Documentation
Guardian()
Guardian::Guardian (SummonPropertiesEntry const * properties, ObjectGuid owner, bool isWorldObject)
Definition at line 364 of file TemporarySummon.cpp.
                                                                                                 : Minion(properties, owner, isWorldObject)
 {
     m_unitTypeMask |= UNIT_MASK_GUARDIAN;
     if (properties && properties->Type == SUMMON_TYPE_PET)
     {
         m_unitTypeMask |= UNIT_MASK_CONTROLABLE_GUARDIAN;
         InitCharmInfo();
     }
 }
References Unit::InitCharmInfo(), Unit::m_unitTypeMask, SUMMON_TYPE_PET, SummonPropertiesEntry::Type, UNIT_MASK_CONTROLABLE_GUARDIAN, and UNIT_MASK_GUARDIAN.
Member Function Documentation
InitStats()
void Guardian::InitStats (uint32 duration) override virtual
Reimplemented from Minion.
Definition at line 374 of file TemporarySummon.cpp.
 {
     Minion::InitStats(duration);
     Unit* m_owner = GetOwner();
     InitStatsForLevel(m_owner->getLevel());
     if (m_owner->GetTypeId() == TYPEID_PLAYER && HasUnitTypeMask(UNIT_MASK_CONTROLABLE_GUARDIAN))
         m_charmInfo->InitCharmCreateSpells();
     SetReactState(REACT_AGGRESSIVE);
 }
References Minion::GetOwner(), ObjectGuid::GetTypeId(), Unit::HasUnitTypeMask(), CharmInfo::InitCharmCreateSpells(), Minion::InitStats(), InitStatsForLevel(), Unit::m_charmInfo, Minion::m_owner, REACT_AGGRESSIVE, Creature::SetReactState(), TYPEID_PLAYER, and UNIT_MASK_CONTROLABLE_GUARDIAN.
InitStatsForLevel()
bool Guardian::InitStatsForLevel (uint8 level)
Definition at line 748 of file Pet.cpp.
 {
     CreatureTemplate const* cinfo = GetCreatureTemplate();
     ASSERT(cinfo);
     SetLevel(petlevel);
     SetCanModifyStats(true);
     Unit* owner = GetOwner();
     if (!owner) // just to be sure, asynchronous now
     {
         DespawnOrUnsummon(1000);
         return false;
     }
     //Determine pet type
     PetType petType = MAX_PET_TYPE;
     if (owner->GetTypeId() == TYPEID_PLAYER)
     {
         sScriptMgr->OnBeforeGuardianInitStatsForLevel(owner->ToPlayer(), this, cinfo, petType);
         if (IsPet())
         {
             if (petType == MAX_PET_TYPE)
             {
                 // The petType was not overwritten by the hook, continue with default initialization
                 if (owner->getClass() == CLASS_WARLOCK ||
                         owner->getClass() == CLASS_SHAMAN ||          // Fire Elemental
                         owner->getClass() == CLASS_DEATH_KNIGHT ||    // Risen Ghoul
                         owner->getClass() == CLASS_MAGE)              // Water Elemental with glyph
                     petType = SUMMON_PET;
                 else if (owner->getClass() == CLASS_HUNTER)
                 {
                     petType = HUNTER_PET;
                 }
             }
             if (petType == HUNTER_PET)
                 m_unitTypeMask |= UNIT_MASK_HUNTER_PET;
             else if (petType != SUMMON_PET)
                 LOG_ERROR("entities.pet", "Unknown type pet %u is summoned by player class %u", GetEntry(), owner->getClass());
         }
     }
     uint32 creature_ID = (petType == HUNTER_PET) ? 1 : cinfo->Entry;
     SetMeleeDamageSchool(SpellSchools(cinfo->dmgschool));
     SetModifierValue(UNIT_MOD_ARMOR, BASE_VALUE, float(petlevel * 50));
     uint32 attackTime = BASE_ATTACK_TIME;
     if (owner->getClass() != CLASS_HUNTER && cinfo->BaseAttackTime >= 1000)
         attackTime = cinfo->BaseAttackTime;
     SetAttackTime(BASE_ATTACK, attackTime);
     SetAttackTime(OFF_ATTACK, attackTime);
     SetAttackTime(RANGED_ATTACK, BASE_ATTACK_TIME);
     SetFloatValue(UNIT_MOD_CAST_SPEED, 1.0f);
     //scale
     CreatureFamilyEntry const* cFamily = sCreatureFamilyStore.LookupEntry(cinfo->family);
     if (cFamily && cFamily->minScale > 0.0f && petType == HUNTER_PET)
     {
         float scale;
         if (getLevel() >= cFamily->maxScaleLevel)
             scale = 1.0f;
         else if (getLevel() <= cFamily->minScaleLevel)
             scale = 0.5f;
         else
             scale = 0.5f + 0.5f * float(getLevel() - cFamily->minScaleLevel) / float(cFamily->maxScaleLevel  - cFamily->minScaleLevel);
         SetObjectScale(scale);
     }
     // Resistance
     // xinef: hunter pets should not inherit template resistances
     if (!IsHunterPet())
         for (uint8 i = SPELL_SCHOOL_HOLY; i < MAX_SPELL_SCHOOL; ++i)
             SetModifierValue(UnitMods(UNIT_MOD_RESISTANCE_START + i), BASE_VALUE, float(cinfo->resistance[i]));
     //health, mana, armor and resistance
     PetLevelInfo const* pInfo = sObjectMgr->GetPetLevelInfo(creature_ID, petlevel);
     if (pInfo)                                      // exist in DB
     {
         SetCreateHealth(pInfo->health);
         SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, (float)pInfo->health);
         if (petType != HUNTER_PET) //hunter pet use focus
         {
             SetCreateMana(pInfo->mana);
             SetModifierValue(UNIT_MOD_MANA, BASE_VALUE, (float)pInfo->mana);
         }
         if (pInfo->armor > 0)
             SetModifierValue(UNIT_MOD_ARMOR, BASE_VALUE, float(pInfo->armor));
         for (uint8 stat = 0; stat < MAX_STATS; ++stat)
             SetCreateStat(Stats(stat), float(pInfo->stats[stat]));
     }
     else                                            // not exist in DB, use some default fake data
     {
         // remove elite bonuses included in DB values
         CreatureBaseStats const* stats = sObjectMgr->GetCreatureBaseStats(petlevel, cinfo->unit_class);
         // xinef: multiply base values by creature_template factors!
         float factorHealth = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModHealth) : cinfo->ModHealth;
         float factorMana = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModMana) : cinfo->ModMana;
         SetCreateHealth(std::max<uint32>(1, stats->BaseHealth[cinfo->expansion]*factorHealth));
         SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, GetCreateHealth());
         SetCreateMana(stats->BaseMana * factorMana);
         SetModifierValue(UNIT_MOD_MANA, BASE_VALUE, GetCreateMana());
         // xinef: added some multipliers so debuffs can affect pets in any way...
         SetCreateStat(STAT_STRENGTH, 22 + 2 * petlevel);
         SetCreateStat(STAT_AGILITY, 22 + 1.5f * petlevel);
         SetCreateStat(STAT_STAMINA, 25 + 2 * petlevel);
         SetCreateStat(STAT_INTELLECT, 28 + 2 * petlevel);
         SetCreateStat(STAT_SPIRIT, 27 + 1.5f * petlevel);
     }
     switch (petType)
     {
         case HUNTER_PET:
             {
                 SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
                 SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
                 SetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP, uint32(sObjectMgr->GetXPForLevel(petlevel)* sWorld->getRate(RATE_XP_PET_NEXT_LEVEL)));
                 break;
             }
         case SUMMON_PET:
             {
                 if (pInfo)
                 {
                     SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(pInfo->min_dmg));
                     SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(pInfo->max_dmg));
                 }
                 else
                 {
                     SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
                     SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
                 }
                 switch(GetEntry())
                 {
                     case NPC_FELGUARD:
{
                             // xinef: Glyph of Felguard, so ugly im crying... no appropriate spell
                             if (AuraEffect* aurEff = owner->GetAuraEffectDummy(SPELL_GLYPH_OF_FELGUARD))
                                 SetModifierValue(UNIT_MOD_ATTACK_POWER, TOTAL_PCT, 1.0f + float(aurEff->GetAmount() / 100.0f));
                             break;
                         }
                     case NPC_WATER_ELEMENTAL_PERM:
{
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_MAGE_PET_SCALING_01, this);
                             AddAura(SPELL_MAGE_PET_SCALING_02, this);
                             AddAura(SPELL_MAGE_PET_SCALING_03, this);
                             AddAura(SPELL_MAGE_PET_SCALING_04, this);
                             break;
                         }
                 }
                 break;
             }
         default:
             {
                 switch (GetEntry())
                 {
                     case NPC_FIRE_ELEMENTAL:
{
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 3.5f - petlevel));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 3.5f + petlevel));
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_FIRE_ELEMENTAL_SCALING_01, this);
                             AddAura(SPELL_FIRE_ELEMENTAL_SCALING_02, this);
                             AddAura(SPELL_FIRE_ELEMENTAL_SCALING_03, this);
                             AddAura(SPELL_FIRE_ELEMENTAL_SCALING_04, this);
                             break;
                         }
                     case NPC_EARTH_ELEMENTAL:
{
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 2.0f - petlevel));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 2.0f + petlevel));
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_EARTH_ELEMENTAL_SCALING_01, this);
                             AddAura(SPELL_EARTH_ELEMENTAL_SCALING_02, this);
                             AddAura(SPELL_EARTH_ELEMENTAL_SCALING_03, this);
                             AddAura(SPELL_EARTH_ELEMENTAL_SCALING_04, this);
                             break;
                         }
                     case NPC_INFERNAL:
{
                             float highAmt = petlevel / 11.0f;
                             float lowAmt = petlevel / 12.0f;
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, lowAmt * lowAmt * lowAmt);
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, highAmt * highAmt * highAmt);
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_05, this);
                             AddAura(SPELL_INFERNAL_SCALING_01, this);
                             AddAura(SPELL_INFERNAL_SCALING_02, this);
                             AddAura(SPELL_INFERNAL_SCALING_03, this);
                             AddAura(SPELL_INFERNAL_SCALING_04, this);
                             break;
                         }
                     case NPC_DOOMGUARD:
{
                             float highAmt = petlevel / 11.0f;
                             float lowAmt = petlevel / 12.0f;
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, lowAmt * lowAmt * lowAmt);
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, highAmt * highAmt * highAmt);
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_01, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_02, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_03, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_04, this);
                             AddAura(SPELL_WARLOCK_PET_SCALING_05, this);
                             break;
                         }
                     case NPC_WATER_ELEMENTAL_TEMP:
{
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_MAGE_PET_SCALING_01, this);
                             AddAura(SPELL_MAGE_PET_SCALING_02, this);
                             AddAura(SPELL_MAGE_PET_SCALING_03, this);
                             AddAura(SPELL_MAGE_PET_SCALING_04, this);
                             break;
                         }
                     case NPC_TREANT: //force of nature
{
                             if (!pInfo)
                                 SetCreateHealth(30 + 30 * petlevel);
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 2.5f - petlevel));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 2.5f + petlevel));
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_TREANT_SCALING_01, this);
                             AddAura(SPELL_TREANT_SCALING_02, this);
                             AddAura(SPELL_TREANT_SCALING_03, this);
                             AddAura(SPELL_TREANT_SCALING_04, this);
                             break;
                         }
                     case NPC_SHADOWFIEND:
{
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 2.5f - petlevel));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 2.5f + petlevel));
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_SHADOWFIEND_SCALING_01, this);
                             AddAura(SPELL_SHADOWFIEND_SCALING_02, this);
                             AddAura(SPELL_SHADOWFIEND_SCALING_03, this);
                             AddAura(SPELL_SHADOWFIEND_SCALING_04, this);
                             break;
                         }
                     case NPC_FERAL_SPIRIT:
{
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 4.0f - petlevel));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 4.0f + petlevel));
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_FERAL_SPIRIT_SPIRIT_HUNT, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_FERAL_SPIRIT_SCALING_01, this);
                             AddAura(SPELL_FERAL_SPIRIT_SCALING_02, this);
                             AddAura(SPELL_FERAL_SPIRIT_SCALING_03, this);
                             break;
                         }
                     case NPC_MIRROR_IMAGE: // Mirror Image
{
                             SetDisplayId(owner->GetDisplayId());
                             if (!pInfo)
{
                                 SetCreateMana(28 + 30 * petlevel);
                                 SetCreateHealth(28 + 10 * petlevel);
                             }
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_MAGE_PET_SCALING_01, this);
                             AddAura(SPELL_MAGE_PET_SCALING_02, this);
                             AddAura(SPELL_MAGE_PET_SCALING_03, this);
                             AddAura(SPELL_MAGE_PET_SCALING_04, this);
                             break;
                         }
                     case NPC_EBON_GARGOYLE: // Ebon Gargoyle
{
                             if (!pInfo)
{
                                 SetCreateMana(28 + 10 * petlevel);
                                 SetCreateHealth(28 + 30 * petlevel);
                             }
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_DK_PET_SCALING_01, this);
                             AddAura(SPELL_DK_PET_SCALING_02, this);
                             AddAura(SPELL_DK_PET_SCALING_03, this);
                             break;
                         }
                     case NPC_BLOODWORM:
{
                             // Xinef: Hit / Expertise scaling
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             SetCreateHealth(4 * petlevel);
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - 30 - (petlevel / 4) + owner->GetTotalAttackPowerValue(BASE_ATTACK) * 0.006f));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel - 30 + (petlevel / 4) + owner->GetTotalAttackPowerValue(BASE_ATTACK) * 0.006f));
                             SetReactState(REACT_DEFENSIVE);
                             break;
                         }
                     case NPC_ARMY_OF_THE_DEAD:
{
                             AddAura(SPELL_HUNTER_PET_SCALING_04, this);
                             AddAura(SPELL_DK_PET_SCALING_01, this);
                             AddAura(SPELL_DK_PET_SCALING_02, this);
                             AddAura(SPELL_DK_PET_SCALING_03, this);
                             AddAura(SPELL_PET_AVOIDANCE, this);
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
                             break;
                         }
                     case NPC_GENERIC_IMP:
                     case NPC_GENERIC_VOIDWALKER:
{
                             SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
                             SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
                             break;
                         }
                 }
                 break;
             }
     }
     // Can be summon and guardian
     if (GetEntry() == NPC_RISEN_GHOUL)
     {
         // 100% energy after summon
         SetPower(POWER_ENERGY, GetMaxPower(POWER_ENERGY));
         // xinef: fixes orc death knight command racial
         if (owner->getRace() == RACE_ORC)
             CastSpell(this, SPELL_ORC_RACIAL_COMMAND, true, nullptr, nullptr, owner->GetGUID());
         // Avoidance, Night of the Dead
         if (Aura* aur = AddAura(SPELL_NIGHT_OF_THE_DEAD_AVOIDANCE, this))
             if (AuraEffect* aurEff = owner->GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_DEATHKNIGHT, 2718, 0))
                 if (aur->GetEffect(0))
                     aur->GetEffect(0)->SetAmount(-aurEff->GetSpellInfo()->Effects[EFFECT_2].CalcValue());
         AddAura(SPELL_HUNTER_PET_SCALING_04, this);
         // Added to perm ghoul by default
         if (!IsPet())
         {
             AddAura(SPELL_DK_PET_SCALING_01, this);
             AddAura(SPELL_DK_PET_SCALING_02, this);
         }
     }
     sScriptMgr->OnInitStatsForLevel(this, petlevel);
     UpdateAllStats();
     SetFullHealth();
     SetPower(POWER_MANA, GetMaxPower(POWER_MANA));
     if (owner->GetTypeId() == TYPEID_PLAYER)
         sScriptMgr->OnAfterGuardianInitStatsForLevel(owner->ToPlayer(), this);
     return true;
 }
References Unit::AddAura(), PetLevelInfo::armor, ASSERT, BASE_ATTACK, BASE_ATTACK_TIME, BASE_VALUE, CreatureTemplate::BaseAttackTime, CreatureBaseStats::BaseHealth, CreatureBaseStats::BaseMana, Unit::CastSpell(), CLASS_DEATH_KNIGHT, CLASS_HUNTER, CLASS_MAGE, CLASS_SHAMAN, CLASS_WARLOCK, Creature::DespawnOrUnsummon(), CreatureTemplate::dmgschool, EFFECT_2, CreatureTemplate::Entry, CreatureTemplate::expansion, CreatureTemplate::family, Unit::GetAuraEffect(), Unit::GetAuraEffectDummy(), Unit::getClass(), Unit::GetCreateHealth(), Unit::GetCreateMana(), Creature::GetCreatureTemplate(), Unit::GetDisplayId(), Object::GetEntry(), Object::GetGUID(), Unit::getLevel(), Unit::GetMaxPower(), Minion::GetOwner(), Unit::getRace(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), PetLevelInfo::health, HUNTER_PET, Unit::IsHunterPet(), Unit::IsPet(), LOG_ERROR, Unit::m_unitTypeMask, PetLevelInfo::mana, PetLevelInfo::max_dmg, MAX_PET_TYPE, MAX_SPELL_SCHOOL, MAX_STATS, MAXDAMAGE, CreatureFamilyEntry::maxScaleLevel, PetLevelInfo::min_dmg, MINDAMAGE, CreatureFamilyEntry::minScale, CreatureFamilyEntry::minScaleLevel, CreatureTemplate::ModHealth, CreatureTemplate::ModMana, NPC_ARMY_OF_THE_DEAD, NPC_BLOODWORM, NPC_DOOMGUARD, NPC_EARTH_ELEMENTAL, NPC_EBON_GARGOYLE, NPC_FELGUARD, NPC_FERAL_SPIRIT, NPC_FIRE_ELEMENTAL, NPC_GENERIC_IMP, NPC_GENERIC_VOIDWALKER, NPC_INFERNAL, NPC_MIRROR_IMAGE, NPC_RISEN_GHOUL, NPC_SHADOWFIEND, NPC_TREANT, NPC_WATER_ELEMENTAL_PERM, NPC_WATER_ELEMENTAL_TEMP, OFF_ATTACK, POWER_ENERGY, POWER_MANA, RACE_ORC, RANGED_ATTACK, RATE_XP_PET_NEXT_LEVEL, REACT_DEFENSIVE, CreatureTemplate::resistance, sCreatureFamilyStore, Unit::SetAttackTime(), Unit::SetBaseWeaponDamage(), Unit::SetCanModifyStats(), Unit::SetCreateHealth(), Unit::SetCreateMana(), Unit::SetCreateStat(), Creature::SetDisplayId(), Object::SetFloatValue(), Unit::SetFullHealth(), Unit::SetLevel(), Creature::SetMeleeDamageSchool(), Unit::SetModifierValue(), Creature::SetObjectScale(), Unit::SetPower(), Creature::SetReactState(), Object::SetUInt32Value(), sObjectMgr, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_DK_PET_SCALING_01, SPELL_DK_PET_SCALING_02, SPELL_DK_PET_SCALING_03, SPELL_EARTH_ELEMENTAL_SCALING_01, SPELL_EARTH_ELEMENTAL_SCALING_02, SPELL_EARTH_ELEMENTAL_SCALING_03, SPELL_EARTH_ELEMENTAL_SCALING_04, SPELL_FERAL_SPIRIT_SCALING_01, SPELL_FERAL_SPIRIT_SCALING_02, SPELL_FERAL_SPIRIT_SCALING_03, SPELL_FERAL_SPIRIT_SPIRIT_HUNT, SPELL_FIRE_ELEMENTAL_SCALING_01, SPELL_FIRE_ELEMENTAL_SCALING_02, SPELL_FIRE_ELEMENTAL_SCALING_03, SPELL_FIRE_ELEMENTAL_SCALING_04, SPELL_GLYPH_OF_FELGUARD, SPELL_HUNTER_PET_SCALING_04, SPELL_INFERNAL_SCALING_01, SPELL_INFERNAL_SCALING_02, SPELL_INFERNAL_SCALING_03, SPELL_INFERNAL_SCALING_04, SPELL_MAGE_PET_SCALING_01, SPELL_MAGE_PET_SCALING_02, SPELL_MAGE_PET_SCALING_03, SPELL_MAGE_PET_SCALING_04, SPELL_NIGHT_OF_THE_DEAD_AVOIDANCE, SPELL_ORC_RACIAL_COMMAND, SPELL_PET_AVOIDANCE, SPELL_SCHOOL_HOLY, SPELL_SHADOWFIEND_SCALING_01, SPELL_SHADOWFIEND_SCALING_02, SPELL_SHADOWFIEND_SCALING_03, SPELL_SHADOWFIEND_SCALING_04, SPELL_TREANT_SCALING_01, SPELL_TREANT_SCALING_02, SPELL_TREANT_SCALING_03, SPELL_TREANT_SCALING_04, SPELL_WARLOCK_PET_SCALING_01, SPELL_WARLOCK_PET_SCALING_02, SPELL_WARLOCK_PET_SCALING_03, SPELL_WARLOCK_PET_SCALING_04, SPELL_WARLOCK_PET_SCALING_05, SPELLFAMILY_DEATHKNIGHT, sScriptMgr, STAT_AGILITY, STAT_INTELLECT, STAT_SPIRIT, STAT_STAMINA, STAT_STRENGTH, PetLevelInfo::stats, SUMMON_PET, sWorld, Object::ToPlayer(), TOTAL_PCT, TYPEID_PLAYER, CreatureTemplate::unit_class, UNIT_FIELD_PETNEXTLEVELEXP, UNIT_MASK_HUNTER_PET, UNIT_MOD_ARMOR, UNIT_MOD_ATTACK_POWER, UNIT_MOD_CAST_SPEED, UNIT_MOD_HEALTH, UNIT_MOD_MANA, UNIT_MOD_RESISTANCE_START, and UpdateAllStats().
Referenced by Pet::GivePetLevel(), Pet::HandleAsynchLoadFailed(), misc_commandscript::HandleCreatePetCommand(), InitStats(), and Unit::InitTamedPet().
InitSummon()
void Guardian::InitSummon () override virtual
Reimplemented from TempSummon.
Definition at line 387 of file TemporarySummon.cpp.
 {
     TempSummon::InitSummon();
     Unit* m_owner = GetOwner();
     if (m_owner->GetTypeId() == TYPEID_PLAYER
             && m_owner->GetMinionGUID() == GetGUID()
             && !m_owner->GetCharmGUID())
         m_owner->ToPlayer()->CharmSpellInitialize();
 }
References Object::GetGUID(), Minion::GetOwner(), ObjectGuid::GetTypeId(), TempSummon::InitSummon(), Minion::m_owner, and TYPEID_PLAYER.
UpdateAllStats()
bool Guardian::UpdateAllStats () override virtual
Reimplemented from Creature.
Definition at line 1147 of file StatSystem.cpp.
 {
     for (uint8 i = STAT_STRENGTH; i < MAX_STATS; ++i)
         UpdateStats(Stats(i));
     for (uint8 i = POWER_MANA; i < MAX_POWERS; ++i)
         UpdateMaxPower(Powers(i));
     UpdateAllResistances();
     return true;
 }
References MAX_POWERS, MAX_STATS, POWER_MANA, STAT_STRENGTH, Unit::UpdateAllResistances(), UpdateMaxPower(), and UpdateStats().
Referenced by InitStatsForLevel().
UpdateArmor()
void Guardian::UpdateArmor () override virtual
Reimplemented from Creature.
Definition at line 1159 of file StatSystem.cpp.
 {
     float value = GetModifierValue(UNIT_MOD_ARMOR, BASE_VALUE);
     value *= GetModifierValue(UNIT_MOD_ARMOR, BASE_PCT);
     value += std::max<float>(GetStat(STAT_AGILITY) - GetCreateStat(STAT_AGILITY), 0.0f) * 2.0f;
     value += GetModifierValue(UNIT_MOD_ARMOR, TOTAL_VALUE);
     value *= GetModifierValue(UNIT_MOD_ARMOR, TOTAL_PCT);
     SetArmor(int32(value));
 }
References BASE_PCT, BASE_VALUE, Unit::GetCreateStat(), Unit::GetModifierValue(), Unit::GetStat(), Unit::SetArmor(), STAT_AGILITY, TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_ARMOR.
Referenced by UpdateStats().
UpdateAttackPowerAndDamage()
void Guardian::UpdateAttackPowerAndDamage (bool ranged = false) override virtual
Reimplemented from Creature.
Definition at line 1248 of file StatSystem.cpp.
 {
     if (ranged)
         return;
     float val = 0.0f;
     UnitMods unitMod = UNIT_MOD_ATTACK_POWER;
     if (GetEntry() == NPC_IMP)                                     // imp's attack power
         val = GetStat(STAT_STRENGTH) - 10.0f;
     else if (IsPetGhoul())                                         // DK's ghoul attack power
         val = 589 /*xinef: base ap!*/ + GetStat(STAT_STRENGTH) + GetStat(STAT_AGILITY);
     else
         val = 2 * GetStat(STAT_STRENGTH) - 20.0f;
     SetModifierValue(unitMod, BASE_VALUE, val);
     //in BASE_VALUE of UNIT_MOD_ATTACK_POWER for creatures we store data of meleeattackpower field in DB
     float base_attPower  = GetModifierValue(unitMod, BASE_VALUE) * GetModifierValue(unitMod, BASE_PCT);
     float attPowerMod = GetModifierValue(unitMod, TOTAL_VALUE);
     float attPowerMultiplier = GetModifierValue(unitMod, TOTAL_PCT) - 1.0f;
     //UNIT_FIELD_(RANGED)_ATTACK_POWER field
     SetInt32Value(UNIT_FIELD_ATTACK_POWER, (int32)base_attPower);
     //UNIT_FIELD_(RANGED)_ATTACK_POWER_MODS field
     SetInt32Value(UNIT_FIELD_ATTACK_POWER_MODS, (int32)attPowerMod);
     //UNIT_FIELD_(RANGED)_ATTACK_POWER_MULTIPLIER field
     SetFloatValue(UNIT_FIELD_ATTACK_POWER_MULTIPLIER, attPowerMultiplier);
     //automatically update weapon damage after attack power modification
     UpdateDamagePhysical(BASE_ATTACK);
 }
References BASE_ATTACK, BASE_PCT, BASE_VALUE, Object::GetEntry(), Unit::GetModifierValue(), Unit::GetStat(), Minion::IsPetGhoul(), NPC_IMP, Object::SetFloatValue(), Object::SetInt32Value(), Unit::SetModifierValue(), STAT_AGILITY, STAT_STRENGTH, TOTAL_PCT, TOTAL_VALUE, UNIT_FIELD_ATTACK_POWER, UNIT_FIELD_ATTACK_POWER_MODS, UNIT_FIELD_ATTACK_POWER_MULTIPLIER, UNIT_MOD_ATTACK_POWER, and UpdateDamagePhysical().
Referenced by UpdateStats().
UpdateDamagePhysical()
void Guardian::UpdateDamagePhysical (WeaponAttackType attType) override virtual
Reimplemented from Unit.
Definition at line 1281 of file StatSystem.cpp.
 {
     if (attType > BASE_ATTACK)
         return;
     UnitMods unitMod = UNIT_MOD_DAMAGE_MAINHAND;
     float att_speed = float(GetAttackTime(BASE_ATTACK)) / 1000.0f;
     float base_value  = GetModifierValue(unitMod, BASE_VALUE) + GetTotalAttackPowerValue(attType) / 14.0f * att_speed;
     float base_pct    = GetModifierValue(unitMod, BASE_PCT);
     float total_value = GetModifierValue(unitMod, TOTAL_VALUE);
     float total_pct   = GetModifierValue(unitMod, TOTAL_PCT);
     float weapon_mindamage = GetWeaponDamageRange(BASE_ATTACK, MINDAMAGE);
     float weapon_maxdamage = GetWeaponDamageRange(BASE_ATTACK, MAXDAMAGE);
     float mindamage = ((base_value + weapon_mindamage) * base_pct + total_value) * total_pct;
     float maxdamage = ((base_value + weapon_maxdamage) * base_pct + total_value) * total_pct;
     if (mindamage < 0.0f || mindamage > 10000000.0f)
         mindamage = BASE_MINDAMAGE;
     if (maxdamage < 0.0f || maxdamage > 10000000.0f)
         maxdamage = BASE_MAXDAMAGE;
     if (mindamage > maxdamage)
         mindamage = maxdamage;
     //  Pet's base damage changes depending on happiness
     if (IsHunterPet() && attType == BASE_ATTACK)
     {
         switch (ToPet()->GetHappinessState())
         {
             case HAPPY:
                 // 125% of normal damage
                 mindamage = mindamage * 1.25f;
                 maxdamage = maxdamage * 1.25f;
                 break;
             case CONTENT:
                 // 100% of normal damage, nothing to modify
                 break;
             case UNHAPPY:
                 // 75% of normal damage
                 mindamage = mindamage * 0.75f;
                 maxdamage = maxdamage * 0.75f;
                 break;
         }
     }
     SetStatFloatValue(UNIT_FIELD_MINDAMAGE, mindamage);
     SetStatFloatValue(UNIT_FIELD_MAXDAMAGE, maxdamage);
 }
References BASE_ATTACK, BASE_MAXDAMAGE, BASE_MINDAMAGE, BASE_PCT, BASE_VALUE, CONTENT, Unit::GetAttackTime(), Pet::GetHappinessState(), Unit::GetModifierValue(), Unit::GetTotalAttackPowerValue(), Unit::GetWeaponDamageRange(), HAPPY, Unit::IsHunterPet(), MAXDAMAGE, MINDAMAGE, Object::SetStatFloatValue(), Unit::ToPet(), TOTAL_PCT, TOTAL_VALUE, UNHAPPY, UNIT_FIELD_MAXDAMAGE, UNIT_FIELD_MINDAMAGE, and UNIT_MOD_DAMAGE_MAINHAND.
Referenced by UpdateAttackPowerAndDamage().
UpdateMaxHealth()
void Guardian::UpdateMaxHealth () override virtual
Reimplemented from Creature.
Definition at line 1169 of file StatSystem.cpp.
 {
     UnitMods unitMod = UNIT_MOD_HEALTH;
     float stamina = std::max<float>(GetStat(STAT_STAMINA) - GetCreateStat(STAT_STAMINA), 0.0f);
     float multiplicator;
     switch (GetEntry())
     {
         case NPC_IMP:
             multiplicator = 8.4f;
             break;
         case NPC_WATER_ELEMENTAL_TEMP:
             multiplicator = 7.5f;
             break;
         case NPC_WATER_ELEMENTAL_PERM:
             multiplicator = 7.5f;
             break;
         case NPC_VOIDWALKER:
             multiplicator = 11.0f;
             break;
         case NPC_SUCCUBUS:
             multiplicator = 9.1f;
             break;
         case NPC_FELHUNTER:
             multiplicator = 9.5f;
             break;
         case NPC_FELGUARD:
             multiplicator = 11.0f;
             break;
         case NPC_BLOODWORM:
             multiplicator = 1.0f;
             break;
         default:
             multiplicator = 10.0f;
             break;
     }
     float value = GetModifierValue(unitMod, BASE_VALUE);// xinef: Do NOT add base health TWICE + GetCreateHealth();
     value *= GetModifierValue(unitMod, BASE_PCT);
     value += GetModifierValue(unitMod, TOTAL_VALUE) + stamina * multiplicator;
     value *= GetModifierValue(unitMod, TOTAL_PCT);
     SetMaxHealth((uint32)value);
 }
References BASE_PCT, BASE_VALUE, Unit::GetCreateStat(), Object::GetEntry(), Unit::GetModifierValue(), Unit::GetStat(), NPC_BLOODWORM, NPC_FELGUARD, NPC_FELHUNTER, NPC_IMP, NPC_SUCCUBUS, NPC_VOIDWALKER, NPC_WATER_ELEMENTAL_PERM, NPC_WATER_ELEMENTAL_TEMP, Unit::SetMaxHealth(), STAT_STAMINA, TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_HEALTH.
Referenced by UpdateStats().
UpdateMaxPower()
void Guardian::UpdateMaxPower (Powers power) override virtual
Reimplemented from Creature.
Definition at line 1214 of file StatSystem.cpp.
 {
     UnitMods unitMod = UnitMods(static_cast<uint16>(UNIT_MOD_POWER_START) + power);
     float addValue = (power == POWER_MANA) ? std::max<float>(GetStat(STAT_INTELLECT) - GetCreateStat(STAT_INTELLECT), 0.0f) : 0.0f;
     float multiplicator = 15.0f;
     switch (GetEntry())
     {
         case NPC_IMP:
         case NPC_WATER_ELEMENTAL_TEMP:
         case NPC_WATER_ELEMENTAL_PERM:
             multiplicator = 4.95f;
             break;
         case NPC_VOIDWALKER:
         case NPC_SUCCUBUS:
         case NPC_FELHUNTER:
         case NPC_FELGUARD:
             multiplicator = 11.5f;
             break;
         default:
             multiplicator = 15.0f;
             break;
     }
     // xinef: Do NOT add base mana TWICE
     float value = GetModifierValue(unitMod, BASE_VALUE) + (power != POWER_MANA ? GetCreatePowers(power) : 0);
     value *= GetModifierValue(unitMod, BASE_PCT);
     value += GetModifierValue(unitMod, TOTAL_VALUE) + addValue * multiplicator;
     value *= GetModifierValue(unitMod, TOTAL_PCT);
     SetMaxPower(power, uint32(value));
 }
References BASE_PCT, BASE_VALUE, Unit::GetCreatePowers(), Unit::GetCreateStat(), Object::GetEntry(), Unit::GetModifierValue(), Unit::GetStat(), NPC_FELGUARD, NPC_FELHUNTER, NPC_IMP, NPC_SUCCUBUS, NPC_VOIDWALKER, NPC_WATER_ELEMENTAL_PERM, NPC_WATER_ELEMENTAL_TEMP, POWER_MANA, Unit::SetMaxPower(), STAT_INTELLECT, TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_POWER_START.
Referenced by UpdateAllStats(), and UpdateStats().
UpdateStats()
bool Guardian::UpdateStats (Stats stat) override virtual
Reimplemented from Creature.
Definition at line 1118 of file StatSystem.cpp.
 {
     if (stat >= MAX_STATS)
         return false;
     float value = GetTotalStatValue(stat);
     SetStat(stat, int32(value));
     switch (stat)
     {
         case STAT_STRENGTH:
             UpdateAttackPowerAndDamage();
             break;
         case STAT_AGILITY:
             UpdateArmor();
             break;
         case STAT_STAMINA:
             UpdateMaxHealth();
             break;
         case STAT_INTELLECT:
             UpdateMaxPower(POWER_MANA);
             break;
         case STAT_SPIRIT:
             break;
     }
     return true;
 }
References Unit::GetTotalStatValue(), MAX_STATS, POWER_MANA, Unit::SetStat(), STAT_AGILITY, STAT_INTELLECT, STAT_SPIRIT, STAT_STAMINA, STAT_STRENGTH, UpdateArmor(), UpdateAttackPowerAndDamage(), UpdateMaxHealth(), and UpdateMaxPower().
Referenced by UpdateAllStats().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/TemporarySummon.h
src/server/game/Entities/Creature/TemporarySummon.cpp
src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Unit/StatSystem.cpp