Azerotcore-wotlk: npc_still_at_it_trigger::npc_still_at_it_triggerAI Struct Reference
npc_still_at_it_trigger::npc_still_at_it_triggerAI Struct Reference
Public Member Functions
npc_still_at_it_triggerAI (Creature *pCreature)
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void Say (const char *text)
void Start ()
void CheckAction (uint8 a, ObjectGuid guid)
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool running
bool success
ObjectGuid playerGUID
ObjectGuid thunderbrewGUID
int32 tensecstimer
int32 timer
uint8 stepcount
uint8 currentstep
uint8 expectedaction
uint8 playeraction
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 306 of file zone_sholazar_basin.cpp.
Constructor & Destructor Documentation
npc_still_at_it_triggerAI()
npc_still_at_it_trigger::npc_still_at_it_triggerAI::npc_still_at_it_triggerAI (Creature * pCreature) inline
Definition at line 319 of file zone_sholazar_basin.cpp.
 : NullCreatureAI(pCreature) {}
Member Function Documentation
CheckAction()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction (uint8 a, ObjectGuid guid) inline
Definition at line 356 of file zone_sholazar_basin.cpp.
         {
             if (guid != playerGUID)
                 return;
             if (a == expectedaction)
             {
                 currentstep++;
                 uint8 s = urand(0, 2);
                 if (Creature* th = ObjectAccessor::GetCreature(*me, thunderbrewGUID))
                     th->HandleEmoteCommand(EMOTE_ONESHOT_CHEER_NO_SHEATHE);
                 switch (s)
                 {
                     case 0:
                         Say(MCM_TEXT_CORRECT1);
                         break;
                     case 1:
                         Say(MCM_TEXT_CORRECT2);
                         break;
                     default:
                         Say(MCM_TEXT_CORRECT3);
                         break;
                 }
                 if (currentstep >= stepcount)
                 {
                     Say(MCM_TEXT_SUCCESS1);
                     success = true;
                     timer = 3000;
                 }
                 else
                 {
                     expectedaction = 0;
                     timer = 3000;
                 }
             }
             else
             {
                 Say(MCM_TEXT_FAILED);
                 Reset();
             }
         }
References currentstep, EMOTE_ONESHOT_CHEER_NO_SHEATHE, expectedaction, ObjectAccessor::GetCreature(), MCM_TEXT_CORRECT1, MCM_TEXT_CORRECT2, MCM_TEXT_CORRECT3, MCM_TEXT_FAILED, MCM_TEXT_SUCCESS1, CreatureAI::me, playerGUID, Reset(), Say(), stepcount, success, thunderbrewGUID, timer, and urand().
Referenced by SpellHit().
DamageTaken()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 335 of file zone_sholazar_basin.cpp.
         {
             damage = 0;
         }
Reset()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 321 of file zone_sholazar_basin.cpp.
         {
             running = false;
             success = false;
             playerGUID.Clear();
             thunderbrewGUID.Clear();
             tensecstimer = 0;
             timer = 0;
             stepcount = 0;
             currentstep = 0;
             expectedaction = 0;
             playeraction = 0;
         }
References ObjectGuid::Clear(), currentstep, expectedaction, playeraction, playerGUID, running, stepcount, success, tensecstimer, thunderbrewGUID, and timer.
Referenced by CheckAction(), Say(), and UpdateAI().
Say()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::Say (const char * text) inline
Definition at line 340 of file zone_sholazar_basin.cpp.
         {
             if (Creature* th = ObjectAccessor::GetCreature(*me, thunderbrewGUID))
                 th->Say(text, LANG_UNIVERSAL);
             else
                 Reset();
         }
References ObjectAccessor::GetCreature(), LANG_UNIVERSAL, CreatureAI::me, Reset(), and thunderbrewGUID.
Referenced by CheckAction(), Start(), and UpdateAI().
SpellHit()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 401 of file zone_sholazar_basin.cpp.
         {
             if (running)
             {
                 uint8 a = 0;
                 switch (spellInfo->Id)
                 {
                     case 51931:
                         a = 4;
                         break;
                     case 51932:
                         a = 3;
                         break;
                     case 51933:
                         a = 5;
                         break;
                 }
                 CheckAction(a, caster->GetGUID());
             }
         }
References CheckAction(), and running.
Start()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::Start () inline
Definition at line 348 of file zone_sholazar_basin.cpp.
         {
             timer = 5000;
             running = true;
             stepcount = urand(5, 10);
             Say(MCM_TEXT_START);
         }
References MCM_TEXT_START, running, Say(), stepcount, timer, and urand().
UpdateAI()
void npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 423 of file zone_sholazar_basin.cpp.
         {
             if (running)
             {
                 if (timer)
                 {
                     timer -= diff;
                     if( timer < 0 )
                         timer = 0;
                 }
                 else if ( success)
                 {
                     Say(MCM_TEXT_SUCCESS2);
                     me->SummonGameObject(190643, 5546.55f, 5768.0f, -78.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 60000);
                     Reset();
                 }
                 else if (expectedaction != 0) // didn't make it in 10 seconds
                 {
                     Say(MCM_TEXT_FAILED);
                     Reset();
                 }
                 else // it's time to rand next move
                 {
                     expectedaction = urand(1, 5);
                     switch (expectedaction)
                     {
                         case 1:
                             Say(MCM_TEXT_PRESSURE);
                             break;
                         case 2:
                             Say(MCM_TEXT_HEAT);
                             break;
                         case 3:
                             Say(MCM_TEXT_BANANA);
                             break;
                         case 4:
                             Say(MCM_TEXT_ORANGE);
                             break;
                         case 5:
                             Say(MCM_TEXT_PAPAYA);
                             break;
                     }
                     timer = 10000;
                 }
             }
         }
References expectedaction, MCM_TEXT_BANANA, MCM_TEXT_FAILED, MCM_TEXT_HEAT, MCM_TEXT_ORANGE, MCM_TEXT_PAPAYA, MCM_TEXT_PRESSURE, MCM_TEXT_SUCCESS2, CreatureAI::me, Reset(), running, Say(), success, WorldObject::SummonGameObject(), timer, and urand().
Member Data Documentation
currentstep
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::currentstep
Definition at line 315 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), and Reset().
expectedaction
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::expectedaction
Definition at line 316 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), Reset(), and UpdateAI().
playeraction
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::playeraction
Definition at line 317 of file zone_sholazar_basin.cpp.
Referenced by Reset().
playerGUID
ObjectGuid npc_still_at_it_trigger::npc_still_at_it_triggerAI::playerGUID
Definition at line 310 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), and Reset().
running
bool npc_still_at_it_trigger::npc_still_at_it_triggerAI::running
Definition at line 308 of file zone_sholazar_basin.cpp.
Referenced by Reset(), SpellHit(), Start(), and UpdateAI().
stepcount
uint8 npc_still_at_it_trigger::npc_still_at_it_triggerAI::stepcount
Definition at line 314 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), Reset(), and Start().
success
bool npc_still_at_it_trigger::npc_still_at_it_triggerAI::success
Definition at line 309 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), Reset(), and UpdateAI().
tensecstimer
int32 npc_still_at_it_trigger::npc_still_at_it_triggerAI::tensecstimer
Definition at line 312 of file zone_sholazar_basin.cpp.
Referenced by Reset().
thunderbrewGUID
ObjectGuid npc_still_at_it_trigger::npc_still_at_it_triggerAI::thunderbrewGUID
Definition at line 311 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), Reset(), and Say().
timer
int32 npc_still_at_it_trigger::npc_still_at_it_triggerAI::timer
Definition at line 313 of file zone_sholazar_basin.cpp.
Referenced by CheckAction(), Reset(), Start(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_sholazar_basin.cpp