Azerotcore-wotlk: item_nether_wraith_beacon Class Reference
item_nether_wraith_beacon Class Reference
Public Member Functions
item_nether_wraith_beacon ()
bool OnUse (Player *player, Item *, SpellCastTargets const &) override
Public Member Functions inherited from ItemScript
bool IsDatabaseBound () const override
virtual bool OnQuestAccept (Player *, Item *, Quest const *)
virtual bool OnRemove (Player *, Item *)
virtual bool OnCastItemCombatSpell (Player *, Unit *, SpellInfo const *, Item *)
virtual bool OnExpire (Player *, ItemTemplate const *)
virtual void OnGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from ItemScript
ItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 87 of file item_scripts.cpp.
Constructor & Destructor Documentation
item_nether_wraith_beacon()
item_nether_wraith_beacon::item_nether_wraith_beacon () inline
Definition at line 90 of file item_scripts.cpp.
 : ItemScript("item_nether_wraith_beacon") { }
Member Function Documentation
OnUse()
bool item_nether_wraith_beacon::OnUse (Player * player, Item * , SpellCastTargets const &) inline override virtual
Reimplemented from ItemScript.
Definition at line 92 of file item_scripts.cpp.
     {
         if (player->GetQuestStatus(10832) == QUEST_STATUS_INCOMPLETE)
         {
             if (Creature* nether = player->SummonCreature(22408, player->GetPositionX(), player->GetPositionY() + 20, player->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 180000))
                 nether->AI()->AttackStart(player);
             if (Creature* nether = player->SummonCreature(22408, player->GetPositionX(), player->GetPositionY() - 20, player->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 180000))
                 nether->AI()->AttackStart(player);
         }
         return false;
     }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
The documentation for this class was generated from the following file:
src/server/scripts/World/item_scripts.cpp