Azerotcore-wotlk: Model Class Reference
Model Class Reference
#include <Model.h>
Public Member Functions
Model (std::string path)
~Model ()
void ReadVertices ()
void ReadBoundingTriangles ()
void ReadBoundingNormals ()
bool open ()
bool ConvertToVMAPModel (char const *outfilename)
Model (std::string &filename)
~Model ()
Public Attributes
ModelHeader Header
std::vector< Vector3 > Vertices
std::vector< Vector3 > Normals
std::vector< Triangle< uint16 > > Triangles
bool IsCollidable
FILE * Stream
bool IsBad
ModelHeader header
Vec3D * vertices
uint16 * indices
Private Member Functions
void _unload ()
Private Attributes
std::string filename
Detailed Description
Definition at line 23 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model (std::string path)
Definition at line 22 of file Model.cpp.
                              : IsCollidable(false), IsBad(false)
 {
     Stream = MPQHandler->GetFile(Utils::FixModelPath(path));
     if (!Stream)
     {
         IsBad = true;
         return;
     }
     Header.Read(Stream);
     if (Header.OffsetBoundingNormals > 0 && Header.OffsetBoundingVertices > 0 &&
             Header.OffsetBoundingTriangles > 0 && Header.BoundingRadius > 0.0f)
     {
         IsCollidable = true;
         ReadVertices();
         ReadBoundingNormals();
         ReadBoundingTriangles();
     }
 }
References ModelHeader::BoundingRadius, Utils::FixModelPath(), MPQMgr::GetFile(), Header, IsBad, IsCollidable, MPQHandler, ModelHeader::OffsetBoundingNormals, ModelHeader::OffsetBoundingTriangles, ModelHeader::OffsetBoundingVertices, ModelHeader::Read(), ReadBoundingNormals(), ReadBoundingTriangles(), ReadVertices(), and Stream.
~Model() [1/2]
Model::~Model ()
Definition at line 41 of file Model.cpp.
 {
     if (Stream)
         fclose(Stream);
 }
References Stream.
Model() [2/2]
Model::Model (std::string & filename)
Definition at line 29 of file model.cpp.
                                 : filename(filename), header(), vertices(nullptr), indices(nullptr)
 {
 }
~Model() [2/2]
Model::~Model () inline
Definition at line 52 of file model.h.
 { _unload(); }
References _unload().
Member Function Documentation
_unload()
void Model::_unload () inline private
Definition at line 35 of file model.h.
     {
         delete[] vertices;
         delete[] indices;
         vertices = nullptr;
         indices = nullptr;
     }
References indices, and vertices.
Referenced by open(), and ~Model().
ConvertToVMAPModel()
bool Model::ConvertToVMAPModel (char const * outfilename)
Definition at line 71 of file model.cpp.
 {
     int N[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
     FILE* output = fopen(outfilename, "wb");
     if (!output)
     {
         printf("Can't create the output file '%s'\n", outfilename);
         return false;
     }
     fwrite(VMAP::RAW_VMAP_MAGIC, 8, 1, output);
     uint32 nVertices = header.nBoundingVertices;
     fwrite(&nVertices, sizeof(int), 1, output);
     uint32 nofgroups = 1;
     fwrite(&nofgroups, sizeof(uint32), 1, output);
     fwrite(N, 4 * 3, 1, output); // rootwmoid, flags, groupid
     fwrite(N, sizeof(float), 3 * 2, output); //bbox, only needed for WMO currently
     fwrite(N, 4, 1, output); // liquidflags
     fwrite("GRP ", 4, 1, output);
     uint32 branches = 1;
     int wsize;
     wsize = sizeof(branches) + sizeof(uint32) * branches;
     fwrite(&wsize, sizeof(int), 1, output);
     fwrite(&branches, sizeof(branches), 1, output);
     uint32 nIndexes = header.nBoundingTriangles;
     fwrite(&nIndexes, sizeof(uint32), 1, output);
     fwrite("INDX", 4, 1, output);
     wsize = sizeof(uint32) + sizeof(unsigned short) * nIndexes;
     fwrite(&wsize, sizeof(int), 1, output);
     fwrite(&nIndexes, sizeof(uint32), 1, output);
     if (nIndexes > 0)
     {
         for (uint32 i = 0; i < nIndexes; ++i)
         {
             if ((i % 3) - 1 == 0 && i + 1 < nIndexes)
             {
                 uint16 tmp = indices[i];
                 indices[i] = indices[i + 1];
                 indices[i + 1] = tmp;
             }
         }
         fwrite(indices, sizeof(unsigned short), nIndexes, output);
     }
     fwrite("VERT", 4, 1, output);
     wsize = sizeof(int) + sizeof(float) * 3 * nVertices;
     fwrite(&wsize, sizeof(int), 1, output);
     fwrite(&nVertices, sizeof(int), 1, output);
     if (nVertices > 0)
     {
         for (uint32 vpos = 0; vpos < nVertices; ++vpos)
         {
             float tmp = vertices[vpos].y;
             vertices[vpos].y = -vertices[vpos].z;
             vertices[vpos].z = tmp;
         }
         fwrite(vertices, sizeof(float) * 3, nVertices, output);
     }
     fclose(output);
     return true;
 }
References header, indices, ModelHeader::nBoundingTriangles, ModelHeader::nBoundingVertices, printf(), VMAP::RAW_VMAP_MAGIC, vertices, Vec3D::y, and Vec3D::z.
Referenced by ExtractSingleModel().
open()
bool Model::open ()
Definition at line 33 of file model.cpp.
 {
     MPQFile f(filename.c_str());
     if (f.isEof())
     {
         f.close();
         // Do not show this error on console to avoid confusion, the extractor can continue working even if some models fail to load
         //printf("Error loading model %s\n", filename.c_str());
         return false;
     }
     _unload();
     memcpy(&header, f.getBuffer(), sizeof(ModelHeader));
     if (header.nBoundingTriangles > 0)
     {
         f.seek(0);
         f.seekRelative(header.ofsBoundingVertices);
         vertices = new Vec3D[header.nBoundingVertices];
         f.read(vertices, header.nBoundingVertices * 12);
         for (uint32 i = 0; i < header.nBoundingVertices; i++)
             vertices[i] = fixCoordSystem(vertices[i]);
         f.seek(0);
         f.seekRelative(header.ofsBoundingTriangles);
         indices = new uint16[header.nBoundingTriangles];
         f.read(indices, header.nBoundingTriangles * 2);
         f.close();
     }
     else
     {
         //printf("not included %s\n", filename.c_str());
         f.close();
         return false;
     }
     return true;
 }
References _unload(), f(), filename, fixCoordSystem(), header, indices, memcpy, ModelHeader::nBoundingTriangles, ModelHeader::nBoundingVertices, ModelHeader::ofsBoundingTriangles, ModelHeader::ofsBoundingVertices, and vertices.
Referenced by ExtractSingleModel().
ReadBoundingNormals()
void Model::ReadBoundingNormals ()
Definition at line 77 of file Model.cpp.
 {
     fseek(Stream, Header.OffsetBoundingNormals, SEEK_SET);
     Normals.reserve(Header.CountBoundingNormals);
     for (uint32 i = 0; i < Header.CountBoundingNormals; i++)
         Normals.push_back(Vector3::Read(Stream));
 }
References ModelHeader::CountBoundingNormals, Header, Normals, ModelHeader::OffsetBoundingNormals, Vector3::Read(), SEEK_SET, and Stream.
Referenced by Model().
ReadBoundingTriangles()
void Model::ReadBoundingTriangles ()
Definition at line 59 of file Model.cpp.
 {
     fseek(Stream, Header.OffsetBoundingTriangles, SEEK_SET);
     Triangles.reserve(Header.CountBoundingTriangles / 3);
     for (uint32 i = 0; i < Header.CountBoundingTriangles / 3; i++)
     {
         Triangle<uint16> tri;
         tri.Type = Constants::TRIANGLE_TYPE_DOODAD;
         int count = 0;
         count += fread(&tri.V0, sizeof(uint16), 1, Stream);
         count += fread(&tri.V1, sizeof(uint16), 1, Stream);
         count += fread(&tri.V2, sizeof(uint16), 1, Stream);
         if (count != 3)
             printf("Model::ReadBoundingTriangles: Error reading data, expected 3, read %d\n", count);
         Triangles.push_back(tri);
     }
 }
References count(), ModelHeader::CountBoundingTriangles, Header, ModelHeader::OffsetBoundingTriangles, printf(), SEEK_SET, Stream, Constants::TRIANGLE_TYPE_DOODAD, Triangles, Triangle< T >::Type, Triangle< T >::V0, Triangle< T >::V1, and Triangle< T >::V2.
Referenced by Model().
ReadVertices()
void Model::ReadVertices ()
Definition at line 47 of file Model.cpp.
 {
     fseek(Stream, Header.OffsetBoundingVertices, SEEK_SET);
     Vertices.reserve(Header.CountBoundingVertices);
     for (uint32 i = 0; i < Header.CountBoundingVertices; ++i)
     {
         Vertices.push_back(Vector3::Read(Stream));
         if (Constants::ToWoWCoords)
             Vertices[i] = Utils::ToWoWCoords(Vertices[i]);
     }
 }
References ModelHeader::CountBoundingVertices, Header, ModelHeader::OffsetBoundingVertices, Vector3::Read(), SEEK_SET, Stream, Constants::ToWoWCoords, Utils::ToWoWCoords(), and Vertices.
Referenced by Model().
Member Data Documentation
filename
std::string Model::filename private
Definition at line 42 of file model.h.
Referenced by open().
Header
ModelHeader Model::Header
Definition at line 32 of file Model.h.
Referenced by ExtractGameobjectModels(), Model(), ReadBoundingNormals(), ReadBoundingTriangles(), and ReadVertices().
header
ModelHeader Model::header
Definition at line 44 of file model.h.
Referenced by ConvertToVMAPModel(), and open().
indices
uint16* Model::indices
Definition at line 46 of file model.h.
Referenced by _unload(), ConvertToVMAPModel(), and open().
IsBad
bool Model::IsBad
Definition at line 38 of file Model.h.
Referenced by ExtractGameobjectModels(), and Model().
IsCollidable
bool Model::IsCollidable
Definition at line 36 of file Model.h.
Referenced by WorldModelHandler::InsertModelGeometry(), Model(), and DoodadHandler::ProcessInternal().
Normals
std::vector<Vector3> Model::Normals
Definition at line 34 of file Model.h.
Referenced by ReadBoundingNormals().
Stream
FILE* Model::Stream
Definition at line 37 of file Model.h.
Referenced by Model(), ReadBoundingNormals(), ReadBoundingTriangles(), ReadVertices(), and ~Model().
Triangles
std::vector<Triangle<uint16> > Model::Triangles
Definition at line 35 of file Model.h.
Referenced by ExtractGameobjectModels(), DoodadHandler::InsertModelGeometry(), WorldModelHandler::InsertModelGeometry(), DoodadHandler::ProcessInternal(), and ReadBoundingTriangles().
Vertices
std::vector<Vector3> Model::Vertices
Definition at line 33 of file Model.h.
Referenced by ExtractGameobjectModels(), DoodadHandler::InsertModelGeometry(), WorldModelHandler::InsertModelGeometry(), DoodadHandler::ProcessInternal(), and ReadVertices().
vertices
Vec3D* Model::vertices
Definition at line 45 of file model.h.
Referenced by _unload(), ConvertToVMAPModel(), and open().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Model.h
src/tools/mesh_extractor/Model.cpp