Azerotcore-wotlk: Vector3 Struct Reference
Vector3 Struct Reference
#include <Utils.h>
Public Member Functions
Vector3 ()
Vector3 (float X, float Y, float Z)
Vector3 operator+ (Vector3 const &other) const
Vector3 operator- (Vector3 const &other) const
template<typename T >
Vector3 operator* (T s) const
Static Public Member Functions
static Vector3 Read (FILE *file)
Public Attributes
float x
float y
float z
Detailed Description
Definition at line 37 of file Utils.h.
Constructor & Destructor Documentation
Vector3() [1/2]
Vector3::Vector3 () inline
Definition at line 39 of file Utils.h.
 {}
Referenced by operator*(), operator+(), operator-(), G3D::Matrix4::scale(), and G3D::Matrix4::translation().
Vector3() [2/2]
Vector3::Vector3 (float X, float Y, float Z) inline
Definition at line 40 of file Utils.h.
 : x(X), y(Y), z(Z) {}
Member Function Documentation
operator*()
template<typename T > Vector3 Vector3::operator* (T s) const inline
Definition at line 56 of file Utils.h.
     {
         return Vector3(x * s, y * s, z * s);
     }
References Vector3(), x, y, and z.
operator+()
Vector3 Vector3::operator+ (Vector3 const & other) const inline
Definition at line 45 of file Utils.h.
     {
         return Vector3(x + other.x, y + other.y, z + other.z);
     }
References Vector3(), x, y, and z.
operator-()
Vector3 Vector3::operator- (Vector3 const & other) const inline
Definition at line 50 of file Utils.h.
     {
         return Vector3(x - other.x, y - other.y, z - other.z);
     }
References Vector3(), x, y, and z.
Read()
Vector3 Vector3::Read (FILE * file) static
Definition at line 156 of file Utils.cpp.
 {
     Vector3 ret;
     if (fread(&ret, sizeof(Vector3), 1, file) != 1)
         printf("Vector3::Read: Failed to read some data expected 1, read 0\n");
     return ret;
 }
References mpq::file, printf(), and ret.
Referenced by WorldModelDefinition::Read(), DoodadDefinition::Read(), MapChunkHeader::Read(), ModelHeader::Read(), WorldModelHeader::Read(), DoodadInstance::Read(), LiquidHeader::Read(), WMOGroupHeader::Read(), Model::ReadBoundingNormals(), WorldModelGroup::ReadNormals(), Model::ReadVertices(), and WorldModelGroup::ReadVertices().
Member Data Documentation
x
float Vector3::x
Definition at line 41 of file Utils.h.
Referenced by MapChunk::GenerateVertices(), Geometry::GetRawData(), LiquidHandler::HandleNewLiquid(), main(), operator*(), operator+(), operator-(), TileBuilder::OutputDebugVertices(), Utils::ToRecast(), Utils::TransformDoodadVertex(), and Utils::TransformWmoDoodad().
y
float Vector3::y
Definition at line 42 of file Utils.h.
Referenced by MapChunk::GenerateVertices(), Geometry::GetRawData(), LiquidHandler::HandleNewLiquid(), main(), operator*(), operator+(), operator-(), TileBuilder::OutputDebugVertices(), Utils::ToRecast(), Utils::TransformDoodadVertex(), and Utils::TransformWmoDoodad().
z
float Vector3::z
Definition at line 43 of file Utils.h.
Referenced by MapChunk::GenerateVertices(), Utils::GetLiquidVert(), Geometry::GetRawData(), LiquidHandler::HandleNewLiquid(), main(), operator*(), operator+(), operator-(), TileBuilder::OutputDebugVertices(), Utils::ToRecast(), Utils::TransformDoodadVertex(), and Utils::TransformWmoDoodad().
The documentation for this struct was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp