Azerotcore-wotlk: G3D::Sphere Class Reference
G3D::Sphere Class Reference
#include <Sphere.h>
Public Member Functions
Sphere ()
Sphere (float radius)
Sphere (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Sphere (const class Any &a)
Any toAny () const
Sphere (const Point3 &center, float radius)
virtual ~Sphere ()
bool operator== (const Sphere &other) const
bool operator!= (const Sphere &other) const
bool contains (const Point3 &point) const
bool contains (const Sphere &other) const
bool culledBy (const class Plane *plane, int numPlanes, int32 &cullingPlaneIndex, const uint32 testMask, uint32 &childMask) const
bool culledBy (const class Plane *plane, int numPlanes, int32 &cullingPlaneIndex=dummy, const uint32 testMask=0xFFFFFFFF) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex, const uint32 testMask, uint32 &childMask) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex=dummy, const uint32 testMask=0xFFFFFFFF) const
virtual std::string toString () const
float volume () const
float area () const
Point3 randomSurfacePoint () const
Point3 randomInteriorPoint () const
void getBounds (class AABox &out) const
bool intersects (const Sphere &other) const
Sphere operator+ (const Vector3 &v) const
Sphere operator- (const Vector3 &v) const
void merge (const Sphere &s)
Static Public Member Functions
static const Sphere & inf ()
Public Attributes
Point3 center
float radius
Static Private Attributes
static int32 dummy
Detailed Description
Sphere.
Definition at line 24 of file Sphere.h.
Constructor & Destructor Documentation
Sphere() [1/5]
G3D::Sphere::Sphere () inline
Definition at line 33 of file Sphere.h.
              : center(Point3::zero()), radius(0) {
     }
Referenced by operator+(), and operator-().
Sphere() [2/5]
G3D::Sphere::Sphere (float radius) inline explicit
Definition at line 36 of file Sphere.h.
 : radius(radius) {}
Sphere() [3/5]
G3D::Sphere::Sphere (class BinaryInput & b)
Definition at line 50 of file Sphere.cpp.
{
     deserialize(b);
 }
References b, and G3D::deserialize().
Sphere() [4/5]
G3D::Sphere::Sphere (const class Any & a) explicit
Format is one of:
Sphere(point, radius)
Sphere(radius)
Sphere() [5/5]
G3D::Sphere::Sphere (const Point3 & center, float radius) inline
Definition at line 50 of file Sphere.h.
                             : center(center), radius(radius) {
     }
~Sphere()
virtual G3D::Sphere::~Sphere () inline virtual
Definition at line 55 of file Sphere.h.
 {}
Member Function Documentation
area()
float G3D::Sphere::area () const
Definition at line 247 of file Sphere.cpp.
{
     return (float)pi() * 4.0f * powf((float)radius, 2.0f);
 }
References G3D::pi().
contains() [1/2]
bool G3D::Sphere::contains (const Point3 & point) const
Returns true if point is less than or equal to radius away from the center.
Definition at line 79 of file Sphere.cpp.
{
     float distance = (center - point).squaredMagnitude();
     return distance <= square(radius);
 }
References align::center, G3D::distance(), and G3D::square().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance(), G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedTriangle(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), and merge().
contains() [2/2]
bool G3D::Sphere::contains (const Sphere & other) const
Definition at line 85 of file Sphere.cpp.
{
     float distance = (center - other.center).squaredMagnitude();
     return (radius >= other.radius) && (distance <= square(radius - other.radius));
 }
References align::center, center, G3D::distance(), radius, and G3D::square().
culledBy() [1/4]
bool G3D::Sphere::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex, const uint32 testMask, uint32 & childMask) const
See AABox::culledBy
culledBy() [2/4]
bool G3D::Sphere::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex = dummy, const uint32 testMask = 0xFFFFFFFF) const
Conservative culling test that does not produce a mask for children.
culledBy() [3/4]
bool G3D::Sphere::culledBy (const class Plane * plane, int numPlanes, int32 & cullingPlaneIndex, const uint32 testMask, uint32 & childMask) const
Deprecated:
Use culledBy(Array<Plane>&)
culledBy() [4/4]
bool G3D::Sphere::culledBy (const class Plane * plane, int numPlanes, int32 & cullingPlaneIndex = dummy, const uint32 testMask = 0xFFFFFFFF) const
Deprecated:
Use culledBy(Array<Plane>&)
deserialize()
void G3D::Sphere::deserialize (class BinaryInput & b)
Definition at line 61 of file Sphere.cpp.
{
     center.deserialize(b);
     radius = (float)b.readFloat64();
 }
References b, and align::center.
getBounds()
void G3D::Sphere::getBounds (class AABox & out) const
Definition at line 252 of file Sphere.cpp.
{
     Vector3 extent(radius, radius, radius);
     out = AABox(center - extent, center + extent);
 }
References align::center.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::getBoundingBox(), BoundsTrait< class G3D::Sphere >::getBounds(), BoundsTrait< class G3D::Sphere * >::getBounds(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers().
inf()
const Sphere & G3D::Sphere::inf () static
Returns the infinite sphere.
Definition at line 67 of file Sphere.cpp.
{
     static const Sphere s(Point3::zero(), finf());
     return s;
 }
References G3D::finf(), and G3D::zero().
intersects()
bool G3D::Sphere::intersects (const Sphere & other) const
Definition at line 91 of file Sphere.cpp.
{
     return (other.center - center).length() <= (radius + other.radius);
 }
References align::center, center, and radius.
merge()
void G3D::Sphere::merge (const Sphere & s)
Sets this to the smallest sphere that encapsulates both
Definition at line 96 of file Sphere.cpp.
{
     if (other.contains(*this)) {
         *this = other;
     } else if (! contains(other)) {
         // The farthest distance is along the axis between the centers, which
         // must not be colocated since neither contains the other.
         Vector3 toMe = center - other.center;
         // Get a point on the axis from each
         toMe = toMe.direction();
         const Vector3& A = center + toMe * radius;
         const Vector3& B = other.center - toMe * other.radius;
         // Now just bound the A->B segment
         center = (A + B) * 0.5f;
         radius = (A - B).length();
     }
     // (if this contains other, we're done)
 }
References align::center, center, contains(), contains(), G3D::Vector3::direction(), G3D::length(), and radius.
operator!=()
bool G3D::Sphere::operator!= (const Sphere & other) const inline
Definition at line 64 of file Sphere.h.
{
         return !((center == other.center) && (radius == other.radius));
     }
References center, and radius.
operator+()
Sphere G3D::Sphere::operator+ (const Vector3 & v) const inline
Translates the sphere
Definition at line 133 of file Sphere.h.
{
         return Sphere(center + v, radius);
     }
References center, radius, and Sphere().
operator-()
Sphere G3D::Sphere::operator- (const Vector3 & v) const inline
Translates the sphere
Definition at line 138 of file Sphere.h.
{
         return Sphere(center - v, radius);
     }
References center, radius, and Sphere().
operator==()
bool G3D::Sphere::operator== (const Sphere & other) const inline
Definition at line 60 of file Sphere.h.
{
         return (center == other.center) && (radius == other.radius);
     }
References center, and radius.
randomInteriorPoint()
Vector3 G3D::Sphere::randomInteriorPoint () const
Uniformly distributed on the interior (includes surface)
Definition at line 230 of file Sphere.cpp.
{
     Vector3 result;
     do {
         result = Vector3(uniformRandom(-1, 1),
                          uniformRandom(-1, 1),
                          uniformRandom(-1, 1));
     } while (result.squaredMagnitude() >= 1.0f);
     return result * radius + center;
 }
References align::center, and G3D::uniformRandom().
Referenced by G3D::Capsule::randomInteriorPoint().
randomSurfacePoint()
Vector3 G3D::Sphere::randomSurfacePoint () const
Uniformly distributed on the surface.
Definition at line 225 of file Sphere.cpp.
{
     return Vector3::random() * radius + center;
 }
References align::center.
Referenced by G3D::Capsule::getRandomSurfacePoint().
serialize()
void G3D::Sphere::serialize (class BinaryOutput & b) const
Definition at line 55 of file Sphere.cpp.
{
     center.serialize(b);
     b.writeFloat64(radius);
 }
References b, and align::center.
toAny()
Any G3D::Sphere::toAny () const
Definition at line 39 of file Sphere.cpp.
{
     Any a(Any::ARRAY, "Sphere");
     if (center != Point3::zero()) {
         a.append(center);
     }
     a.append(radius);
     return a;
 }
References mpq::a, align::center, and G3D::zero().
toString()
std::string G3D::Sphere::toString () const virtual
Definition at line 73 of file Sphere.cpp.
{
     return format("Sphere(<%g, %g, %g>, %g)",
                   center.x, center.y, center.z, radius);
 }
References align::center, and format().
volume()
float G3D::Sphere::volume () const
Definition at line 242 of file Sphere.cpp.
{
     return (float)pi() * (4.0f / 3.0f) * powf((float)radius, 3.0f);
 }
References G3D::pi().
Member Data Documentation
center
Point3 G3D::Sphere::center
Definition at line 30 of file Sphere.h.
Referenced by G3D::CollisionDetection::bounceDirection(), G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedBox(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedRectangle(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedSphere(), G3D::MeshAlg::computeBounds(), contains(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidBox(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidSphere(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedTriangle(), G3D::AABox::getBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), HashTrait< G3D::Sphere >::hashCode(), G3D::AABox::intersects(), intersects(), G3D::LineSegment::intersectsSolidSphere(), merge(), G3D::CollisionDetection::movingSpherePassesThroughFixedSphere(), operator!=(), operator+(), operator-(), operator==(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedSphere(), and G3D::CollisionDetection::slideDirection().
dummy
int32 G3D::Sphere::dummy static private
Definition at line 27 of file Sphere.h.
radius
float G3D::Sphere::radius
Definition at line 31 of file Sphere.h.
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedSphere(), contains(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidBox(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidSphere(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedTriangle(), G3D::AABox::getBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), HashTrait< G3D::Sphere >::hashCode(), G3D::AABox::intersects(), intersects(), G3D::LineSegment::intersectsSolidSphere(), merge(), G3D::CollisionDetection::movingSpherePassesThroughFixedSphere(), operator!=(), operator+(), operator-(), operator==(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedSphere().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Sphere.h
deps/g3dlite/source/Sphere.cpp