Azerotcore-wotlk: DynamicTreeLocationInfoCallback Struct Reference
DynamicTreeLocationInfoCallback Struct Reference
Public Member Functions
DynamicTreeLocationInfoCallback (uint32 phaseMask)
void operator() (G3D::Vector3 const &p, GameObjectModel const &obj)
VMAP::LocationInfo & GetLocationInfo ()
GameObjectModel const * GetHitModel () const
Private Attributes
uint32 _phaseMask
VMAP::LocationInfo _locationInfo
GameObjectModel const * _hitModel
Detailed Description
Definition at line 184 of file DynamicTree.cpp.
Constructor & Destructor Documentation
DynamicTreeLocationInfoCallback()
DynamicTreeLocationInfoCallback::DynamicTreeLocationInfoCallback (uint32 phaseMask) inline
Definition at line 186 of file DynamicTree.cpp.
         : _phaseMask(phaseMask), _hitModel(nullptr) {}
Member Function Documentation
GetHitModel()
GameObjectModel const* DynamicTreeLocationInfoCallback::GetHitModel () const inline
Definition at line 199 of file DynamicTree.cpp.
     {
         return _hitModel;
     }
References _hitModel.
Referenced by DynamicMapTree::GetAreaAndLiquidData().
GetLocationInfo()
VMAP::LocationInfo& DynamicTreeLocationInfoCallback::GetLocationInfo () inline
Definition at line 195 of file DynamicTree.cpp.
     {
         return _locationInfo;
     }
References _locationInfo.
Referenced by DynamicMapTree::GetAreaAndLiquidData().
operator()()
void DynamicTreeLocationInfoCallback::operator() (G3D::Vector3 const & p, GameObjectModel const & obj) inline
Definition at line 189 of file DynamicTree.cpp.
     {
         if (obj.GetLocationInfo(p, _locationInfo, _phaseMask))
             _hitModel = &obj;
     }
References _hitModel, _locationInfo, _phaseMask, and GameObjectModel::GetLocationInfo().
Member Data Documentation
_hitModel
GameObjectModel const* DynamicTreeLocationInfoCallback::_hitModel private
Definition at line 207 of file DynamicTree.cpp.
Referenced by GetHitModel(), and operator()().
_locationInfo
VMAP::LocationInfo DynamicTreeLocationInfoCallback::_locationInfo private
Definition at line 206 of file DynamicTree.cpp.
Referenced by GetLocationInfo(), and operator()().
_phaseMask
uint32 DynamicTreeLocationInfoCallback::_phaseMask private
Definition at line 205 of file DynamicTree.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/common/Collision/DynamicTree.cpp