Azerotcore-wotlk: npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI Struct Reference
npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI Struct Reference
Public Member Functions
npc_enslaved_proto_drakeAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
bool _setData
EventMap _events
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 117 of file utgarde_keep.cpp.
Constructor & Destructor Documentation
npc_enslaved_proto_drakeAI()
npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::npc_enslaved_proto_drakeAI (Creature * creature) inline
Definition at line 119 of file utgarde_keep.cpp.
                                                        : ScriptedAI(creature)
         {
             _setData = false;
         }
References _setData.
Member Function Documentation
MovementInform()
void npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 132 of file utgarde_keep.cpp.
         {
             if (type == WAYPOINT_MOTION_TYPE && id == POINT_LAST)
             {
                 me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.25f);
                 if (Vehicle* v = me->GetVehicleKit())
                     if (Unit* p = v->GetPassenger(0))
                         if (Creature* rider = p->ToCreature())
                             rider->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.25f);
                 me->SetCanFly(false);
                 me->SetDisableGravity(false);
                 me->SetFacingTo(0.25f);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             }
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleKit(), ScriptedAI::me, POINT_LAST, Object::RemoveFlag(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHomePosition(), Object::ToCreature(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and WAYPOINT_MOTION_TYPE.
Reset()
void npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 124 of file utgarde_keep.cpp.
         {
             _events.Reset();
             _events.ScheduleEvent(EVENT_REND, urand(2000, 3000));
             _events.ScheduleEvent(EVENT_FLAME_BREATH, urand(5500, 7000));
             _events.ScheduleEvent(EVENT_KNOCKAWAY, urand(3500, 6000));
         }
References _events, EVENT_FLAME_BREATH, EVENT_KNOCKAWAY, EVENT_REND, EventMap::Reset(), EventMap::ScheduleEvent(), and urand().
SetData()
void npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 149 of file utgarde_keep.cpp.
         {
             if (type == TYPE_PROTODRAKE_AT && data == DATA_PROTODRAKE_MOVE && !_setData && me->IsAlive() && me->GetDistance(protodrakeCheckPos) < 10.0f)
             {
                 _setData = true;
                 me->SetCanFly(true);
                 me->SetDisableGravity(true);
                 me->GetMotionMaster()->MovePath(PATH_PROTODRAKE, false);
             }
         }
References _setData, DATA_PROTODRAKE_MOVE, WorldObject::GetDistance(), Unit::GetMotionMaster(), Unit::IsAlive(), ScriptedAI::me, MotionMaster::MovePath(), PATH_PROTODRAKE, protodrakeCheckPos, Creature::SetCanFly(), Creature::SetDisableGravity(), and TYPE_PROTODRAKE_AT.
UpdateAI()
void npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 160 of file utgarde_keep.cpp.
         {
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventid = _events.ExecuteEvent())
             {
                 switch (eventid)
                 {
                     case EVENT_REND:
                         DoCast(SPELL_REND);
                         _events.ScheduleEvent(EVENT_REND, urand(15000, 20000));
                         break;
                     case EVENT_FLAME_BREATH:
                         DoCast(SPELL_FLAME_BREATH);
                         _events.ScheduleEvent(EVENT_FLAME_BREATH, urand(11000, 12000));
                         break;
                     case EVENT_KNOCKAWAY:
                         DoCast(SPELL_KNOCK_AWAY);
                         _events.ScheduleEvent(EVENT_KNOCKAWAY, urand(7000, 8500));
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EVENT_FLAME_BREATH, EVENT_KNOCKAWAY, EVENT_REND, EventMap::ExecuteEvent(), Unit::HasUnitState(), ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_FLAME_BREATH, SPELL_KNOCK_AWAY, SPELL_REND, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::_events private
Definition at line 196 of file utgarde_keep.cpp.
Referenced by Reset(), and UpdateAI().
_setData
bool npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::_setData private
Definition at line 195 of file utgarde_keep.cpp.
Referenced by npc_enslaved_proto_drakeAI(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/utgarde_keep.cpp