Azerotcore-wotlk: boss_ionar::boss_ionarAI Struct Reference
boss_ionar::boss_ionarAI Struct Reference
Public Member Functions
boss_ionarAI (Creature *creature)
void Reset () override
void ScheduleEvents (bool spark)
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void SpellHit (Unit *, const SpellInfo *spell) override
void Split ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 HealthCheck
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 78 of file boss_ionar.cpp.
Constructor & Destructor Documentation
boss_ionarAI()
boss_ionar::boss_ionarAI::boss_ionarAI (Creature * creature) inline
Definition at line 80 of file boss_ionar.cpp.
                                          : ScriptedAI(creature), summons(creature)
         {
             m_pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
EnterCombat()
void boss_ionar::boss_ionarAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 115 of file boss_ionar.cpp.
         {
             me->SetInCombatWithZone();
             Talk(SAY_AGGRO);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_IONAR, IN_PROGRESS);
             ScheduleEvents(false);
         }
References IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_AGGRO, ScheduleEvents(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and TYPE_IONAR.
JustDied()
void boss_ionar::boss_ionarAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 126 of file boss_ionar.cpp.
         {
             Talk(SAY_DEATH);
             summons.DespawnAll();
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_IONAR, DONE);
         }
References SummonList::DespawnAll(), DONE, m_pInstance, SAY_DEATH, ZoneScript::SetData(), summons, CreatureAI::Talk(), and TYPE_IONAR.
KilledUnit()
void boss_ionar::boss_ionarAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 136 of file boss_ionar.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_ionar::boss_ionarAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 90 of file boss_ionar.cpp.
         {
             HealthCheck = 50;
             events.Reset();
             summons.DespawnAll();
             me->SetVisible(true);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_IONAR, NOT_STARTED);
             // Ionar is immune to nature damage
             me->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NATURE, true);
         }
References Unit::ApplySpellImmune(), SummonList::DespawnAll(), HealthCheck, IMMUNITY_DAMAGE, m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), Unit::SetVisible(), SPELL_SCHOOL_MASK_NATURE, summons, and TYPE_IONAR.
ScheduleEvents()
void boss_ionar::boss_ionarAI::ScheduleEvents (bool spark) inline
Definition at line 105 of file boss_ionar.cpp.
         {
             events.SetPhase(1);
             if (!spark)
                 events.RescheduleEvent(EVENT_CHECK_HEALTH, 1000, 0, 1);
             events.RescheduleEvent(EVENT_BALL_LIGHTNING, 10000, 0, 1);
             events.RescheduleEvent(EVENT_STATIC_OVERLOAD, 5000, 0, 1);
         }
References EVENT_BALL_LIGHTNING, EVENT_CHECK_HEALTH, and EVENT_STATIC_OVERLOAD.
Referenced by EnterCombat(), and UpdateAI().
SpellHit()
void boss_ionar::boss_ionarAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 144 of file boss_ionar.cpp.
         {
             if (spell->Id == SPELL_DISPERSE)
                 Split();
         }
References SpellInfo::Id, SPELL_DISPERSE, and Split().
Split()
void boss_ionar::boss_ionarAI::Split () inline
Definition at line 150 of file boss_ionar.cpp.
         {
             Talk(SAY_SPLIT);
             Creature* spark;
             for (uint8 i = 0; i < 5; ++i)
             {
                 if ((spark = me->SummonCreature(NPC_SPARK_OF_IONAR, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 20000)))
                 {
                     summons.Summon(spark);
                     spark->CastSpell(spark, me->GetMap()->IsHeroic() ? SPELL_SPARK_VISUAL_TRIGGER_H : SPELL_SPARK_VISUAL_TRIGGER_N, true);
                     spark->CastSpell(spark, SPELL_RANDOM_LIGHTNING, true);
                     spark->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                     spark->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0);
                     if (Player* tgt = SelectTargetFromPlayerList(100))
                         spark->GetMotionMaster()->MoveFollow(tgt, 0.0f, 0.0f, MOTION_SLOT_CONTROLLED);
                 }
             }
             me->SetVisible(false);
             me->SetControlled(true, UNIT_STATE_STUNNED);
             events.SetPhase(2);
             events.ScheduleEvent(EVENT_CALL_SPARKS, 15000, 0, 2);
         }
References Unit::CastSpell(), EVENT_CALL_SPARKS, WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::IsHeroic(), ScriptedAI::me, MOTION_SLOT_CONTROLLED, MotionMaster::MoveFollow(), NPC_SPARK_OF_IONAR, SAY_SPLIT, ScriptedAI::SelectTargetFromPlayerList(), Unit::SetControlled(), Object::SetFlag(), Creature::SetHomePosition(), Unit::SetVisible(), SPELL_RANDOM_LIGHTNING, SPELL_SPARK_VISUAL_TRIGGER_H, SPELL_SPARK_VISUAL_TRIGGER_N, SummonList::Summon(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PACIFIED, and UNIT_STATE_STUNNED.
Referenced by SpellHit().
UpdateAI()
void boss_ionar::boss_ionarAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 177 of file boss_ionar.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BALL_LIGHTNING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, me->GetMap()->IsHeroic() ? SPELL_BALL_LIGHTNING_H : SPELL_BALL_LIGHTNING_N, false);
                     events.RepeatEvent(10000 + rand() % 1000);
                     break;
                 case EVENT_STATIC_OVERLOAD:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, me->GetMap()->IsHeroic() ? SPELL_STATIC_OVERLOAD_H : SPELL_STATIC_OVERLOAD_N, false);
                     events.RepeatEvent(5000 + rand() % 1000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (HealthBelowPct(HealthCheck))
                         me->CastSpell(me, SPELL_DISPERSE, false);
                     events.RepeatEvent(1000);
                     return;
                 case EVENT_CALL_SPARKS:
                     {
                         EntryCheckPredicate pred(NPC_SPARK_OF_IONAR);
                         summons.DoAction(ACTION_CALLBACK, pred);
                         events.ScheduleEvent(EVENT_RESTORE, 2000, 0, 2);
                         return;
                     }
                 case EVENT_RESTORE:
                     EntryCheckPredicate pred(NPC_SPARK_OF_IONAR);
                     summons.DoAction(ACTION_SPARK_DESPAWN, pred);
                     me->SetVisible(true);
                     me->SetControlled(false, UNIT_STATE_STUNNED);
                     ScheduleEvents(true);
                     return;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_CALLBACK, ACTION_SPARK_DESPAWN, Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), EVENT_BALL_LIGHTNING, EVENT_CALL_SPARKS, EVENT_CHECK_HEALTH, EVENT_RESTORE, EVENT_STATIC_OVERLOAD, WorldObject::GetMap(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), HealthCheck, Map::IsHeroic(), ScriptedAI::me, NPC_SPARK_OF_IONAR, ScheduleEvents(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetControlled(), Unit::SetVisible(), SPELL_BALL_LIGHTNING_H, SPELL_BALL_LIGHTNING_N, SPELL_DISPERSE, SPELL_STATIC_OVERLOAD_H, SPELL_STATIC_OVERLOAD_N, summons, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_ionar::boss_ionarAI::events
Definition at line 86 of file boss_ionar.cpp.
HealthCheck
uint8 boss_ionar::boss_ionarAI::HealthCheck
Definition at line 88 of file boss_ionar.cpp.
Referenced by Reset(), and UpdateAI().
m_pInstance
InstanceScript* boss_ionar::boss_ionarAI::m_pInstance
Definition at line 85 of file boss_ionar.cpp.
Referenced by boss_ionarAI(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_ionar::boss_ionarAI::summons
Definition at line 87 of file boss_ionar.cpp.
Referenced by JustDied(), Reset(), Split(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_ionar.cpp