Azerotcore-wotlk: Acore::ChatCommands::ExactSequence< chars > Struct Template Reference
Acore::ChatCommands::ExactSequence< chars > Struct Template Reference
#include <ChatCommandTags.h>
Public Types
using value_type = void
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args) const
Static Private Attributes
static constexpr std::array< char, sizeof...(chars)> _storage = { chars... }
static constexpr std::string_view _string = { _storage.data(), std::string_view::traits_type::length(_storage.data()) }
Detailed Description
template<char... chars>
struct Acore::ChatCommands::ExactSequence< chars >
Definition at line 89 of file ChatCommandTags.h.
Member Typedef Documentation
value_type
template<char... chars> using Acore::ChatCommands::ExactSequence< chars >::value_type = void
Definition at line 91 of file ChatCommandTags.h.
Member Function Documentation
TryConsume()
template<char... chars> ChatCommandResult Acore::ChatCommands::ExactSequence< chars >::TryConsume (ChatHandler const * handler, std::string_view args) const inline
Definition at line 93 of file ChatCommandTags.h.
         {
             if (args.empty())
                 return std::nullopt;
             std::string_view start = args.substr(0, _string.length());
             if (StringEqualI(start, _string))
             {
                 auto [remainingToken, tail] = Acore::Impl::ChatCommands::tokenize(args.substr(_string.length()));
                 if (remainingToken.empty()) // if this is not empty, then we did not consume the full token
                     return tail;
                 start = args.substr(0, _string.length() + remainingToken.length());
             }
             return Acore::Impl::ChatCommands::FormatAcoreString(handler, LANG_CMDPARSER_EXACT_SEQ_MISMATCH, STRING_VIEW_FMT_ARG(_string), STRING_VIEW_FMT_ARG(start));
         }
References Acore::ChatCommands::ExactSequence< chars >::_string, Acore::Impl::ChatCommands::FormatAcoreString(), LANG_CMDPARSER_EXACT_SEQ_MISMATCH, STRING_VIEW_FMT_ARG, StringEqualI(), and Acore::Impl::ChatCommands::tokenize().
Member Data Documentation
_storage
template<char... chars> constexpr std::array<char, sizeof...(chars)> Acore::ChatCommands::ExactSequence< chars >::_storage = { chars... } static constexpr private
Definition at line 109 of file ChatCommandTags.h.
_string
template<char... chars> constexpr std::string_view Acore::ChatCommands::ExactSequence< chars >::_string = { _storage.data(), std::string_view::traits_type::length(_storage.data()) } static constexpr private
Definition at line 111 of file ChatCommandTags.h.
Referenced by Acore::ChatCommands::ExactSequence< chars >::TryConsume().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandTags.h