Azerotcore-wotlk: at_malfurion_stormrage Class Reference
at_malfurion_stormrage Class Reference
Public Member Functions
at_malfurion_stormrage ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 211 of file instance_sunken_temple.cpp.
Constructor & Destructor Documentation
at_malfurion_stormrage()
at_malfurion_stormrage::at_malfurion_stormrage () inline
Definition at line 214 of file instance_sunken_temple.cpp.
 : AreaTriggerScript("at_malfurion_stormrage") { }
Member Function Documentation
OnTrigger()
bool at_malfurion_stormrage::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 216 of file instance_sunken_temple.cpp.
     {
         if (player->GetInstanceScript() && !player->FindNearestCreature(NPC_MALFURION_STORMRAGE, 15.0f) &&
                 player->GetQuestStatus(QUEST_THE_CHARGE_OF_DRAGONFLIGHTS) == QUEST_STATUS_REWARDED && player->GetQuestStatus(QUEST_ERANIKUS_TYRANT_OF_DREAMS) != QUEST_STATUS_REWARDED)
             player->SummonCreature(NPC_MALFURION_STORMRAGE, player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), -1.52f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 100000);
         return false;
     }
References WorldObject::FindNearestCreature(), WorldObject::GetInstanceScript(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), NPC_MALFURION_STORMRAGE, QUEST_ERANIKUS_TYRANT_OF_DREAMS, QUEST_STATUS_REWARDED, QUEST_THE_CHARGE_OF_DRAGONFLIGHTS, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_DEAD_DESPAWN.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp