Azerotcore-wotlk: Log Class Reference
Log Class Reference
#include <Log.h>
Public Member Functions
void Initialize ()
void LoadFromConfig ()
void Close ()
bool ShouldLog (std::string const &type, LogLevel level) const
bool SetLogLevel (std::string const &name, int32 level, bool isLogger=true)
template<typename Format , typename... Args>
void outMessage (std::string const &filter, LogLevel const level, Format &&fmt, Args &&... args)
template<typename... Args>
void outMessageFmt (std::string const &filter, LogLevel const level, std::string_view fmt, Args &&... args)
template<typename Format , typename... Args>
void outCommand (uint32 account, Format &&fmt, Args &&... args)
void outCharDump (char const *str, uint32 account_id, uint64 guid, char const *name)
void SetRealmId (uint32 id)
template<class AppenderImpl >
void RegisterAppender ()
std::string const & GetLogsDir () const
std::string const & GetLogsTimestamp () const
template<typename Format , typename... Args>
void outString (Format &&fmt, Args &&... args)
void outString ()
template<typename Format , typename... Args>
void outError (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outErrorDb (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outBasic (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outDetail (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outSQLDev (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outSQLDriver (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outMisc (Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void outDebug (DebugLogFilters filter, Format &&fmt, Args &&... args)
Static Public Member Functions
static Log * instance ()
Private Types
typedef std::unordered_map< std::string, Logger > LoggerMap
Private Member Functions
Log ()
~Log ()
Log (Log const &)=delete
Log (Log &&)=delete
Log & operator= (Log const &)=delete
Log & operator= (Log &&)=delete
void write (std::unique_ptr< LogMessage > &&msg) const
Logger const * GetLoggerByType (std::string const &type) const
Appender * GetAppenderByName (std::string_view name)
uint8 NextAppenderId ()
void CreateAppenderFromConfig (std::string const &name)
void CreateLoggerFromConfig (std::string const &name)
void ReadAppendersFromConfig ()
void ReadLoggersFromConfig ()
void RegisterAppender (uint8 index, AppenderCreatorFn appenderCreateFn)
void outMessage (std::string const &filter, LogLevel level, std::string &&message)
void _outMessageFmt (std::string const &filter, LogLevel level, std::string &&message)
void outCommand (std::string &&message, std::string &&param1)
Static Private Member Functions
static std::string GetTimestampStr ()
Private Attributes
std::unordered_map< uint8, AppenderCreatorFn > appenderFactory
std::unordered_map< uint8, std::unique_ptr< Appender > > appenders
std::unordered_map< std::string, std::unique_ptr< Logger > > loggers
uint8 AppenderId
LogLevel highestLogLevel
std::string m_logsDir
std::string m_logsTimestamp
DebugLogFilters _debugLogMask
Detailed Description
Definition at line 42 of file Log.h.
Member Typedef Documentation
LoggerMap
typedef std::unordered_map<std::string, Logger> Log::LoggerMap private
Definition at line 44 of file Log.h.
Constructor & Destructor Documentation
Log() [1/3]
Log::Log () private
Definition at line 32 of file Log.cpp.
          : AppenderId(0), highestLogLevel(LOG_LEVEL_FATAL)
 {
     m_logsTimestamp = "_" + GetTimestampStr();
     RegisterAppender<AppenderConsole>();
     RegisterAppender<AppenderFile>();
 }
References GetTimestampStr(), and m_logsTimestamp.
~Log()
Log::~Log () private
Definition at line 39 of file Log.cpp.
 {
     Close();
 }
References Close().
Log() [2/3]
Log::Log (Log const &) private delete
Log() [3/3]
Log::Log (Log &&) private delete
Member Function Documentation
_outMessageFmt()
void Log::_outMessageFmt (std::string const & filter, LogLevel level, std::string && message) private
Definition at line 236 of file Log.cpp.
 {
     write(std::make_unique<LogMessage>(level, filter, std::move(message)));
 }
References message(), and write().
Referenced by outMessageFmt().
Close()
void Log::Close ()
Definition at line 364 of file Log.cpp.
 {
     loggers.clear();
     appenders.clear();
 }
References appenders, and loggers.
Referenced by LoadFromConfig(), ReadLoggersFromConfig(), and ~Log().
CreateAppenderFromConfig()
void Log::CreateAppenderFromConfig (std::string const & name) private
Definition at line 60 of file Log.cpp.
 {
     if (appenderName.empty())
     {
         return;
     }
     // Format = type, level, flags, optional1, optional2
     // if type = File. optional1 = file and option2 = mode
     // if type = Console. optional1 = Color
     std::string options = sConfigMgr->GetStringDefault(appenderName, "");
     std::vector<std::string_view> tokens = Acore::Tokenize(options, ',', true);
     size_t const size = tokens.size();
     std::string name = appenderName.substr(9);
     if (size < 2)
     {
         fprintf(stderr, "Log::CreateAppenderFromConfig: Wrong configuration for appender %s. Config line: %s\n", name.c_str(), options.c_str());
         return;
     }
     AppenderFlags flags = APPENDER_FLAGS_NONE;
     AppenderType type = AppenderType(Acore::StringTo<uint8>(tokens[0]).value_or(APPENDER_INVALID));
     LogLevel level = LogLevel(Acore::StringTo<uint8>(tokens[1]).value_or(LOG_LEVEL_INVALID));
     auto factoryFunction = appenderFactory.find(type);
     if (factoryFunction == appenderFactory.end())
     {
         fprintf(stderr, "Log::CreateAppenderFromConfig: Unknown type '%s' for appender %s\n", std::string(tokens[0]).c_str(), name.c_str());
         return;
     }
     if (level > NUM_ENABLED_LOG_LEVELS)
     {
         fprintf(stderr, "Log::CreateAppenderFromConfig: Wrong Log Level '%s' for appender %s\n", std::string(tokens[1]).c_str(), name.c_str());
         return;
     }
     if (size > 2)
     {
         if (Optional<uint8> flagsVal = Acore::StringTo<uint8>(tokens[2]))
         {
             flags = AppenderFlags(*flagsVal);
         }
         else
         {
             fprintf(stderr, "Log::CreateAppenderFromConfig: Unknown flags '%s' for appender %s\n", std::string(tokens[2]).c_str(), name.c_str());
             return;
         }
     }
     try
     {
         Appender* appender = factoryFunction->second(NextAppenderId(), name, level, flags, tokens);
         appenders[appender->getId()].reset(appender);
     }
     catch (InvalidAppenderArgsException const& iaae)
     {
         fprintf(stderr, "%s\n", iaae.what());
     }
 }
References APPENDER_FLAGS_NONE, APPENDER_INVALID, appenderFactory, appenders, fprintf(), LOG_LEVEL_INVALID, name, NextAppenderId(), NUM_ENABLED_LOG_LEVELS, sConfigMgr, and Acore::Tokenize().
Referenced by ReadAppendersFromConfig().
CreateLoggerFromConfig()
void Log::CreateLoggerFromConfig (std::string const & name) private
Definition at line 124 of file Log.cpp.
 {
     if (appenderName.empty())
     {
         return;
     }
     LogLevel level = LOG_LEVEL_DISABLED;
     std::string options = sConfigMgr->GetStringDefault(appenderName, "");
     std::string name = appenderName.substr(7);
     if (options.empty())
     {
         fprintf(stderr, "Log::CreateLoggerFromConfig: Missing config option Logger.%s\n", name.c_str());
         return;
     }
     std::vector<std::string_view> tokens = Acore::Tokenize(options, ',', true);
     if (tokens.size() != 2)
     {
         fprintf(stderr, "Log::CreateLoggerFromConfig: Wrong config option Logger.%s=%s\n", name.c_str(), options.c_str());
         return;
     }
     std::unique_ptr<Logger>& logger = loggers[name];
     if (logger)
     {
         fprintf(stderr, "Error while configuring Logger %s. Already defined\n", name.c_str());
         return;
     }
     level = LogLevel(Acore::StringTo<uint8>(tokens[0]).value_or(LOG_LEVEL_INVALID));
     if (level > NUM_ENABLED_LOG_LEVELS)
     {
         fprintf(stderr, "Log::CreateLoggerFromConfig: Wrong Log Level '%s' for logger %s\n", std::string(tokens[0]).c_str(), name.c_str());
         return;
     }
     if (level > highestLogLevel)
     {
         highestLogLevel = level;
     }
     logger = std::make_unique<Logger>(name, level);
     //fprintf(stdout, "Log::CreateLoggerFromConfig: Created Logger %s, Level %u\n", name.c_str(), level);
     for (std::string_view appendName : Acore::Tokenize(tokens[1], ' ', false))
     {
         if (Appender* appender = GetAppenderByName(appendName))
         {
             logger->addAppender(appender->getId(), appender);
             //fprintf(stdout, "Log::CreateLoggerFromConfig: Added Appender %s to Logger %s\n", appender->getName().c_str(), name.c_str());
         }
         else
         {
             fprintf(stderr, "Error while configuring Appender %s in Logger %s. Appender does not exist\n", std::string(appendName).c_str(), name.c_str());
         }
     }
 }
References fprintf(), GetAppenderByName(), highestLogLevel, LOG_LEVEL_DISABLED, LOG_LEVEL_INVALID, loggers, name, NUM_ENABLED_LOG_LEVELS, sConfigMgr, and Acore::Tokenize().
Referenced by ReadLoggersFromConfig().
GetAppenderByName()
Appender * Log::GetAppenderByName (std::string_view name) private
Definition at line 49 of file Log.cpp.
 {
     auto it = appenders.begin();
     while (it != appenders.end() && it->second && it->second->getName() != name)
     {
         ++it;
     }
     return it == appenders.end() ? nullptr : it->second.get();
 }
References appenders, and name.
Referenced by CreateLoggerFromConfig(), and SetLogLevel().
GetLoggerByType()
Logger const * Log::GetLoggerByType (std::string const & type) const private
Definition at line 253 of file Log.cpp.
 {
     auto it = loggers.find(type);
     if (it != loggers.end())
     {
         return it->second.get();
     }
     if (type == LOGGER_ROOT)
     {
         return nullptr;
     }
     std::string parentLogger = LOGGER_ROOT;
     size_t found = type.find_last_of('.');
     if (found != std::string::npos)
     {
         parentLogger = type.substr(0, found);
     }
     return GetLoggerByType(parentLogger);
 }
References LOGGER_ROOT, and loggers.
Referenced by ShouldLog(), and write().
GetLogsDir()
std::string const& Log::GetLogsDir () const inline
Definition at line 96 of file Log.h.
 { return m_logsDir; }
References m_logsDir.
GetLogsTimestamp()
std::string const& Log::GetLogsTimestamp () const inline
Definition at line 97 of file Log.h.
 { return m_logsTimestamp; }
References m_logsTimestamp.
GetTimestampStr()
std::string Log::GetTimestampStr () static private
Definition at line 276 of file Log.cpp.
 {
     time_t tt = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
     std::tm aTm;
     localtime_r(&tt, &aTm);
     //       YYYY   year
     //       MM     month (2 digits 01-12)
     //       DD     day (2 digits 01-31)
     //       HH     hour (2 digits 00-23)
     //       MM     minutes (2 digits 00-59)
     //       SS     seconds (2 digits 00-59)
     return Acore::StringFormat("%04d-%02d-%02d_%02d-%02d-%02d",
         aTm.tm_year + 1900, aTm.tm_mon + 1, aTm.tm_mday, aTm.tm_hour, aTm.tm_min, aTm.tm_sec);
 }
References localtime_r(), and Acore::StringFormat().
Referenced by Log().
Initialize()
void Log::Initialize ()
Definition at line 398 of file Log.cpp.
 {
     LoadFromConfig();
 }
References LoadFromConfig().
instance()
Log * Log::instance () static
Definition at line 392 of file Log.cpp.
 {
     static Log instance;
     return &instance;
 }
LoadFromConfig()
void Log::LoadFromConfig ()
Definition at line 403 of file Log.cpp.
 {
     Close();
     highestLogLevel = LOG_LEVEL_FATAL;
     AppenderId = 0;
     m_logsDir = sConfigMgr->GetOption<std::string>("LogsDir", "", false);
     if (!m_logsDir.empty())
         if ((m_logsDir.at(m_logsDir.length() - 1) != '/') && (m_logsDir.at(m_logsDir.length() - 1) != '\\'))
         {
             m_logsDir.push_back('/');
         }
     ReadAppendersFromConfig();
     ReadLoggersFromConfig();
     _debugLogMask = DebugLogFilters(sConfigMgr->GetOption<uint32>("DebugLogMask", LOG_FILTER_NONE, false));
 }
References _debugLogMask, AppenderId, Close(), highestLogLevel, LOG_FILTER_NONE, LOG_LEVEL_FATAL, m_logsDir, ReadAppendersFromConfig(), ReadLoggersFromConfig(), and sConfigMgr.
Referenced by Initialize().
NextAppenderId()
uint8 Log::NextAppenderId () private
Definition at line 44 of file Log.cpp.
 {
     return AppenderId++;
 }
References AppenderId.
Referenced by CreateAppenderFromConfig(), and ReadLoggersFromConfig().
operator=() [1/2]
Log& Log::operator= (Log &&) private delete
operator=() [2/2]
Log& Log::operator= (Log const &) private delete
outBasic()
template<typename Format , typename... Args> void Log::outBasic (Format && fmt, Args &&... args) inline
Definition at line 129 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), and Acore::StringFormat().
outCharDump()
void Log::outCharDump (char const * str, uint32 account_id, uint64 guid, char const * name)
Definition at line 336 of file Log.cpp.
 {
     if (!str || !ShouldLog("entities.player.dump", LOG_LEVEL_INFO))
     {
         return;
     }
     std::ostringstream ss;
     ss << "== START DUMP == (account: " << accountId << " guid: " << guid << " name: " << name
        << ")\n" << str << "\n== END DUMP ==\n";
     std::unique_ptr<LogMessage> msg(new LogMessage(LOG_LEVEL_INFO, "entities.player.dump", ss.str()));
     std::ostringstream param;
     param << guid << '_' << name;
     msg->param1 = param.str();
     write(std::move(msg));
 }
References LOG_LEVEL_INFO, name, ShouldLog(), and write().
outCommand() [1/2]
void Log::outCommand (std::string && message, std::string && param1) private
Definition at line 241 of file Log.cpp.
 {
     write(std::make_unique<LogMessage>(LOG_LEVEL_INFO, "commands.gm", std::move(message), std::move(param1)));
 }
References LOG_LEVEL_INFO, message(), and write().
outCommand() [2/2]
template<typename Format , typename... Args> void Log::outCommand (uint32 account, Format && fmt, Args &&... args) inline
Definition at line 76 of file Log.h.
     {
         if (!ShouldLog("commands.gm", LOG_LEVEL_INFO))
         {
             return;
         }
         outCommand(Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...), std::to_string(account));
     }
References fmt, LOG_LEVEL_INFO, ShouldLog(), Acore::StringFormat(), and to_string().
outDebug()
template<typename Format , typename... Args> void Log::outDebug (DebugLogFilters filter, Format && fmt, Args &&... args) inline
Definition at line 169 of file Log.h.
     {
         if (!(_debugLogMask & filter))
         {
             return;
         }
         if (!ShouldLog("server", LOG_LEVEL_DEBUG))
         {
             return;
         }
         outMessage("server", LOG_LEVEL_DEBUG, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References _debugLogMask, fmt, LOG_LEVEL_DEBUG, outMessage(), ShouldLog(), and Acore::StringFormat().
outDetail()
template<typename Format , typename... Args> void Log::outDetail (Format && fmt, Args &&... args) inline
Definition at line 135 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), and Acore::StringFormat().
outError()
template<typename Format , typename... Args> void Log::outError (Format && fmt, Args &&... args) inline
Definition at line 112 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_ERROR, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_ERROR, outMessage(), and Acore::StringFormat().
outErrorDb()
template<typename Format , typename... Args> void Log::outErrorDb (Format && fmt, Args &&... args) inline
Definition at line 118 of file Log.h.
     {
         if (!ShouldLog("sql.sql", LOG_LEVEL_ERROR))
         {
             return;
         }
         outMessage("sql.sql", LOG_LEVEL_ERROR, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_ERROR, outMessage(), ShouldLog(), and Acore::StringFormat().
outMessage() [1/2]
template<typename Format , typename... Args> void Log::outMessage (std::string const & filter, LogLevel const level, Format && fmt, Args &&... args) inline
Definition at line 64 of file Log.h.
     {
         outMessage(filter, level, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, and Acore::StringFormat().
Referenced by outBasic(), outDebug(), outDetail(), outError(), outErrorDb(), outMisc(), outSQLDev(), outSQLDriver(), and outString().
outMessage() [2/2]
void Log::outMessage (std::string const & filter, LogLevel level, std::string && message) private
Definition at line 231 of file Log.cpp.
 {
     write(std::make_unique<LogMessage>(level, filter, std::move(message)));
 }
References message(), and write().
outMessageFmt()
template<typename... Args> void Log::outMessageFmt (std::string const & filter, LogLevel const level, std::string_view fmt, Args &&... args) inline
Definition at line 70 of file Log.h.
     {
         _outMessageFmt(filter, level, fmt::format(fmt, std::forward<Args>(args)...));
     }
References _outMessageFmt(), fmt, and format().
outMisc()
template<typename Format , typename... Args> void Log::outMisc (Format && fmt, Args &&... args) inline
Definition at line 163 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), and Acore::StringFormat().
outSQLDev()
template<typename Format , typename... Args> void Log::outSQLDev (Format && fmt, Args &&... args) inline
Definition at line 141 of file Log.h.
     {
         if (!ShouldLog("sql.dev", LOG_LEVEL_INFO))
         {
             return;
         }
         outMessage("sql.dev", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), ShouldLog(), and Acore::StringFormat().
outSQLDriver()
template<typename Format , typename... Args> void Log::outSQLDriver (Format && fmt, Args &&... args) inline
Definition at line 152 of file Log.h.
     {
         if (!ShouldLog("sql.driver", LOG_LEVEL_INFO))
         {
             return;
         }
         outMessage("sql.driver", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), ShouldLog(), and Acore::StringFormat().
outString() [1/2]
void Log::outString () inline
Definition at line 106 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_INFO, " ");
     }
References LOG_LEVEL_INFO, and outMessage().
outString() [2/2]
template<typename Format , typename... Args> void Log::outString (Format && fmt, Args &&... args) inline
Definition at line 101 of file Log.h.
     {
         outMessage("server", LOG_LEVEL_INFO, Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...));
     }
References fmt, LOG_LEVEL_INFO, outMessage(), and Acore::StringFormat().
ReadAppendersFromConfig()
void Log::ReadAppendersFromConfig () private
Definition at line 186 of file Log.cpp.
 {
     std::vector<std::string> keys = sConfigMgr->GetKeysByString("Appender.");
     for (std::string const& appenderName : keys)
     {
         CreateAppenderFromConfig(appenderName);
     }
 }
References CreateAppenderFromConfig(), and sConfigMgr.
Referenced by LoadFromConfig().
ReadLoggersFromConfig()
void Log::ReadLoggersFromConfig () private
Definition at line 195 of file Log.cpp.
 {
     std::vector<std::string> keys = sConfigMgr->GetKeysByString("Logger.");
     for (std::string const& loggerName : keys)
     {
         CreateLoggerFromConfig(loggerName);
     }
     // Bad config configuration, creating default config
     if (loggers.find(LOGGER_ROOT) == loggers.end())
     {
         fprintf(stderr, "Wrong Loggers configuration. Review your Logger config section.\n"
                         "Creating default loggers [root (Error), server (Info)] to console\n");
         Close(); // Clean any Logger or Appender created
         AppenderConsole* appender = new AppenderConsole(NextAppenderId(), "Console", LOG_LEVEL_DEBUG, APPENDER_FLAGS_NONE, {});
         appenders[appender->getId()].reset(appender);
         Logger* rootLogger = new Logger(LOGGER_ROOT, LOG_LEVEL_ERROR);
         rootLogger->addAppender(appender->getId(), appender);
         loggers[LOGGER_ROOT].reset(rootLogger);
         Logger* serverLogger = new Logger("server", LOG_LEVEL_INFO);
         serverLogger->addAppender(appender->getId(), appender);
         loggers["server"].reset(serverLogger);
     }
 }
References Logger::addAppender(), APPENDER_FLAGS_NONE, appenders, Close(), CreateLoggerFromConfig(), fprintf(), LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, LOGGER_ROOT, loggers, NextAppenderId(), and sConfigMgr.
Referenced by LoadFromConfig().
RegisterAppender() [1/2]
template<class AppenderImpl > void Log::RegisterAppender () inline
Definition at line 91 of file Log.h.
     {
         RegisterAppender(AppenderImpl::type, &CreateAppender<AppenderImpl>);
     }
RegisterAppender() [2/2]
void Log::RegisterAppender (uint8 index, AppenderCreatorFn appenderCreateFn) private
Definition at line 224 of file Log.cpp.
 {
     auto itr = appenderFactory.find(index);
     ASSERT(itr == appenderFactory.end());
     appenderFactory[index] = appenderCreateFn;
 }
References appenderFactory, ASSERT, and index.
SetLogLevel()
bool Log::SetLogLevel (std::string const & name, int32 level, bool isLogger = true)
Definition at line 293 of file Log.cpp.
 {
     if (newLeveli < 0)
     {
         return false;
     }
     LogLevel newLevel = LogLevel(newLeveli);
     if (isLogger)
     {
         auto it = loggers.begin();
         while (it != loggers.end() && it->second->getName() != name)
         {
             ++it;
         }
         if (it == loggers.end())
         {
             return false;
         }
         it->second->setLogLevel(newLevel);
         if (newLevel != LOG_LEVEL_DISABLED && newLevel > highestLogLevel)
         {
             highestLogLevel = newLevel;
         }
     }
     else
     {
         Appender* appender = GetAppenderByName(name);
         if (!appender)
         {
             return false;
         }
         appender->setLogLevel(newLevel);
     }
     return true;
 }
References GetAppenderByName(), highestLogLevel, LOG_LEVEL_DISABLED, loggers, and name.
SetRealmId()
void Log::SetRealmId (uint32 id)
Definition at line 356 of file Log.cpp.
 {
     for (std::pair<uint8 const, std::unique_ptr<Appender>>& appender : appenders)
     {
         appender.second->setRealmId(id);
     }
 }
References appenders.
ShouldLog()
bool Log::ShouldLog (std::string const & type, LogLevel level) const
Definition at line 370 of file Log.cpp.
 {
     // TODO: Use cache to store "Type.sub1.sub2": "Type" equivalence, should
     // Speed up in cases where requesting "Type.sub1.sub2" but only configured
     // Logger "Type"
     // Don't even look for a logger if the LogLevel is higher than the highest log levels across all loggers
     if (level > highestLogLevel)
     {
         return false;
     }
     Logger const* logger = GetLoggerByType(type);
     if (!logger)
     {
         return false;
     }
     LogLevel logLevel = logger->getLogLevel();
     return logLevel != LOG_LEVEL_DISABLED && logLevel >= level;
 }
References GetLoggerByType(), Logger::getLogLevel(), highestLogLevel, and LOG_LEVEL_DISABLED.
Referenced by outCharDump(), outCommand(), outDebug(), outErrorDb(), outSQLDev(), and outSQLDriver().
write()
void Log::write (std::unique_ptr< LogMessage > && msg) const private
Definition at line 246 of file Log.cpp.
 {
     Logger const* logger = GetLoggerByType(msg->type);
     logger->write(msg.get());
 }
References GetLoggerByType(), and Logger::write().
Referenced by _outMessageFmt(), outCharDump(), outCommand(), and outMessage().
Member Data Documentation
_debugLogMask
DebugLogFilters Log::_debugLogMask private
Definition at line 210 of file Log.h.
Referenced by LoadFromConfig(), and outDebug().
appenderFactory
std::unordered_map<uint8, AppenderCreatorFn> Log::appenderFactory private
Definition at line 200 of file Log.h.
Referenced by CreateAppenderFromConfig(), and RegisterAppender().
AppenderId
uint8 Log::AppenderId private
Definition at line 203 of file Log.h.
Referenced by LoadFromConfig(), and NextAppenderId().
appenders
std::unordered_map<uint8, std::unique_ptr<Appender> > Log::appenders private
Definition at line 201 of file Log.h.
Referenced by Close(), CreateAppenderFromConfig(), GetAppenderByName(), ReadLoggersFromConfig(), and SetRealmId().
highestLogLevel
LogLevel Log::highestLogLevel private
Definition at line 204 of file Log.h.
Referenced by CreateLoggerFromConfig(), LoadFromConfig(), SetLogLevel(), and ShouldLog().
loggers
std::unordered_map<std::string, std::unique_ptr<Logger> > Log::loggers private
Definition at line 202 of file Log.h.
Referenced by Close(), CreateLoggerFromConfig(), GetLoggerByType(), ReadLoggersFromConfig(), and SetLogLevel().
m_logsDir
std::string Log::m_logsDir private
Definition at line 206 of file Log.h.
Referenced by GetLogsDir(), and LoadFromConfig().
m_logsTimestamp
std::string Log::m_logsTimestamp private
Definition at line 207 of file Log.h.
Referenced by GetLogsTimestamp(), and Log().
The documentation for this class was generated from the following files:
src/common/Logging/Log.h
src/common/Logging/Log.cpp