Azerotcore-wotlk: Guild::RankInfo Class Reference
Guild::RankInfo Class Reference
Public Member Functions
RankInfo ()
RankInfo (uint32 guildId)
RankInfo (uint32 guildId, uint8 rankId, std::string const &name, uint32 rights, uint32 money)
void LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
void WritePacket (WorldPacket &data) const
uint8 GetId () const
std::string const & GetName () const
void SetName (std::string const &name)
uint32 GetRights () const
void SetRights (uint32 rights)
int32 GetBankMoneyPerDay () const
void SetBankMoneyPerDay (uint32 money)
int8 GetBankTabRights (uint8 tabId) const
int32 GetBankTabSlotsPerDay (uint8 tabId) const
void SetBankTabSlotsAndRights (GuildBankRightsAndSlots rightsAndSlots, bool saveToDB)
void CreateMissingTabsIfNeeded (uint8 ranks, CharacterDatabaseTransaction trans, bool logOnCreate=false)
Private Attributes
uint32 m_guildId
uint8 m_rankId
std::string m_name
uint32 m_rights
uint32 m_bankMoneyPerDay
GuildBankRightsAndSlots m_bankTabRightsAndSlots [GUILD_BANK_MAX_TABS]
Detailed Description
Definition at line 492 of file Guild.h.
Constructor & Destructor Documentation
RankInfo() [1/3]
Guild::RankInfo::RankInfo () inline
Definition at line 495 of file Guild.h.
 : m_guildId(0), m_rankId(GUILD_RANK_NONE), m_rights(GR_RIGHT_EMPTY), m_bankMoneyPerDay(0) { }
RankInfo() [2/3]
Guild::RankInfo::RankInfo (uint32 guildId) inline
Definition at line 496 of file Guild.h.
 : m_guildId(guildId), m_rankId(GUILD_RANK_NONE), m_rights(GR_RIGHT_EMPTY), m_bankMoneyPerDay(0) { }
RankInfo() [3/3]
Guild::RankInfo::RankInfo (uint32 guildId, uint8 rankId, std::string const & name, uint32 rights, uint32 money) inline
Definition at line 497 of file Guild.h.
                                                                                                    :
             m_guildId(guildId), m_rankId(rankId), m_name(name), m_rights(rights),
             m_bankMoneyPerDay(rankId != GR_GUILDMASTER ? money : GUILD_WITHDRAW_MONEY_UNLIMITED) { }
Member Function Documentation
CreateMissingTabsIfNeeded()
void Guild::RankInfo::CreateMissingTabsIfNeeded (uint8 ranks, CharacterDatabaseTransaction trans, bool logOnCreate = false)
Definition at line 285 of file Guild.cpp.
 {
     for (uint8 i = 0; i < tabs; ++i)
     {
         GuildBankRightsAndSlots& rightsAndSlots = m_bankTabRightsAndSlots[i];
         if (rightsAndSlots.GetTabId() == i)
             continue;
         rightsAndSlots.SetTabId(i);
         if (m_rankId == GR_GUILDMASTER)
             rightsAndSlots.SetGuildMasterValues();
         if (logOnCreate)
             LOG_ERROR("guild", "Guild %u has broken Tab %u for rank %u. Created default tab.", m_guildId, i, m_rankId);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_RIGHT);
         stmt->setUInt32(0, m_guildId);
         stmt->setUInt8(1, i);
         stmt->setUInt8(2, m_rankId);
         stmt->setUInt8(3, rightsAndSlots.GetRights());
         stmt->setUInt32(4, rightsAndSlots.GetSlots());
         trans->Append(stmt);
     }
 }
References CHAR_INS_GUILD_BANK_RIGHT, CharacterDatabase, GuildBankRightsAndSlots::GetRights(), GuildBankRightsAndSlots::GetSlots(), GuildBankRightsAndSlots::GetTabId(), GR_GUILDMASTER, LOG_ERROR, GuildBankRightsAndSlots::SetGuildMasterValues(), GuildBankRightsAndSlots::SetTabId(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::_CreateRank(), and Guild::Validate().
GetBankMoneyPerDay()
int32 Guild::RankInfo::GetBankMoneyPerDay () const inline
Definition at line 513 of file Guild.h.
 { return m_bankMoneyPerDay; }
References m_bankMoneyPerDay.
GetBankTabRights()
int8 Guild::RankInfo::GetBankTabRights (uint8 tabId) const inline
Definition at line 517 of file Guild.h.
         {
             return tabId < GUILD_BANK_MAX_TABS ? m_bankTabRightsAndSlots[tabId].GetRights() : 0;
         }
References GuildBankRightsAndSlots::GetRights(), GUILD_BANK_MAX_TABS, and m_bankTabRightsAndSlots.
GetBankTabSlotsPerDay()
int32 Guild::RankInfo::GetBankTabSlotsPerDay (uint8 tabId) const inline
Definition at line 522 of file Guild.h.
         {
             return tabId < GUILD_BANK_MAX_TABS ? m_bankTabRightsAndSlots[tabId].GetSlots() : 0;
         }
References GuildBankRightsAndSlots::GetSlots(), GUILD_BANK_MAX_TABS, and m_bankTabRightsAndSlots.
GetId()
uint8 Guild::RankInfo::GetId () const inline
Definition at line 505 of file Guild.h.
 { return m_rankId; }
References m_rankId.
Referenced by Guild::Validate().
GetName()
std::string const& Guild::RankInfo::GetName () const inline
Definition at line 507 of file Guild.h.
 { return m_name; }
References m_name.
GetRights()
uint32 Guild::RankInfo::GetRights () const inline
Definition at line 510 of file Guild.h.
 { return m_rights; }
References m_rights.
LoadFromDB()
void Guild::RankInfo::LoadFromDB (Field * fields)
Definition at line 264 of file Guild.cpp.
 {
     m_rankId            = fields[1].GetUInt8();
     m_name              = fields[2].GetString();
     m_rights            = fields[3].GetUInt32();
     m_bankMoneyPerDay   = fields[4].GetUInt32();
     if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
         m_rights |= GR_RIGHT_ALL;
 }
References Field::GetString(), Field::GetUInt32(), Field::GetUInt8(), GR_GUILDMASTER, GR_RIGHT_ALL, and Guild::m_name.
Referenced by Guild::LoadRankFromDB().
SaveToDB()
void Guild::RankInfo::SaveToDB (CharacterDatabaseTransaction trans) const
Definition at line 274 of file Guild.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_RANK);
     stmt->setUInt32(0, m_guildId);
     stmt->setUInt8 (1, m_rankId);
     stmt->setString(2, m_name);
     stmt->setUInt32(3, m_rights);
     stmt->setUInt32(4, m_bankMoneyPerDay);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References CHAR_INS_GUILD_RANK, CharacterDatabase, Guild::m_name, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::_CreateRank().
SetBankMoneyPerDay()
void Guild::RankInfo::SetBankMoneyPerDay (uint32 money)
Definition at line 355 of file Guild.cpp.
 {
     if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
         money = uint32(GUILD_WITHDRAW_MONEY_UNLIMITED);
     if (m_bankMoneyPerDay == money)
         return;
     m_bankMoneyPerDay = money;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_BANK_MONEY);
     stmt->setUInt32(0, money);
     stmt->setUInt8 (1, m_rankId);
     stmt->setUInt32(2, m_guildId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_RANK_BANK_MONEY, CharacterDatabase, GR_GUILDMASTER, GUILD_WITHDRAW_MONEY_UNLIMITED, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
SetBankTabSlotsAndRights()
void Guild::RankInfo::SetBankTabSlotsAndRights (GuildBankRightsAndSlots rightsAndSlots, bool saveToDB)
Definition at line 372 of file Guild.cpp.
 {
     if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
         rightsAndSlots.SetGuildMasterValues();
     GuildBankRightsAndSlots& guildBR = m_bankTabRightsAndSlots[rightsAndSlots.GetTabId()];
     guildBR = rightsAndSlots;
     if (saveToDB)
     {
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_RIGHT);
         stmt->setUInt32(0, m_guildId);
         stmt->setUInt8 (1, guildBR.GetTabId());
         stmt->setUInt8 (2, m_rankId);
         stmt->setUInt8 (3, guildBR.GetRights());
         stmt->setUInt32(4, guildBR.GetSlots());
         CharacterDatabase.Execute(stmt);
     }
 }
References CHAR_INS_GUILD_BANK_RIGHT, CharacterDatabase, GuildBankRightsAndSlots::GetRights(), GuildBankRightsAndSlots::GetSlots(), GuildBankRightsAndSlots::GetTabId(), GR_GUILDMASTER, GuildBankRightsAndSlots::SetGuildMasterValues(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
SetName()
void Guild::RankInfo::SetName (std::string const & name)
Definition at line 324 of file Guild.cpp.
 {
     if (m_name == name)
         return;
     m_name = name;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_NAME);
     stmt->setString(0, m_name);
     stmt->setUInt8 (1, m_rankId);
     stmt->setUInt32(2, m_guildId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_RANK_NAME, CharacterDatabase, Guild::m_name, name, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
SetRights()
void Guild::RankInfo::SetRights (uint32 rights)
Definition at line 338 of file Guild.cpp.
 {
     if (m_rankId == GR_GUILDMASTER)                     // Prevent loss of leader rights
         rights = GR_RIGHT_ALL;
     if (m_rights == rights)
         return;
     m_rights = rights;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_RANK_RIGHTS);
     stmt->setUInt32(0, m_rights);
     stmt->setUInt8 (1, m_rankId);
     stmt->setUInt32(2, m_guildId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_RANK_RIGHTS, CharacterDatabase, GR_GUILDMASTER, GR_RIGHT_ALL, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
WritePacket()
void Guild::RankInfo::WritePacket (WorldPacket & data) const
Definition at line 310 of file Guild.cpp.
 {
     data << uint32(m_rights);
     if (m_bankMoneyPerDay == GUILD_WITHDRAW_MONEY_UNLIMITED)
         data << uint32(GUILD_WITHDRAW_MONEY_UNLIMITED);
     else
         data << uint32(m_bankMoneyPerDay);
     for (uint8 i = 0; i < GUILD_BANK_MAX_TABS; ++i)
     {
         data << uint32(m_bankTabRightsAndSlots[i].GetRights());
         data << uint32(m_bankTabRightsAndSlots[i].GetSlots());
     }
 }
References GUILD_BANK_MAX_TABS, and GUILD_WITHDRAW_MONEY_UNLIMITED.
Member Data Documentation
m_bankMoneyPerDay
uint32 Guild::RankInfo::m_bankMoneyPerDay private
Definition at line 536 of file Guild.h.
Referenced by GetBankMoneyPerDay().
m_bankTabRightsAndSlots
GuildBankRightsAndSlots Guild::RankInfo::m_bankTabRightsAndSlots[GUILD_BANK_MAX_TABS] private
Definition at line 537 of file Guild.h.
Referenced by GetBankTabRights(), and GetBankTabSlotsPerDay().
m_guildId
uint32 Guild::RankInfo::m_guildId private
Definition at line 531 of file Guild.h.
m_name
std::string Guild::RankInfo::m_name private
Definition at line 534 of file Guild.h.
Referenced by GetName().
m_rankId
uint8 Guild::RankInfo::m_rankId private
Definition at line 533 of file Guild.h.
Referenced by GetId().
m_rights
uint32 Guild::RankInfo::m_rights private
Definition at line 535 of file Guild.h.
Referenced by GetRights().
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp