Azerotcore-wotlk: G3D::FileSystem Class Reference
G3D::FileSystem Class Reference
#include <FileSystem.h>
Classes
class Dir
class Entry
class ListSettings
Public Member Functions
void setCacheLifetime (float t)
Static Public Member Functions
static void init ()
static void cleanup ()
static bool inZipfile (const std::string &path, std::string &zipfile)
static void clearCache (const std::string &path="")
static FILE * fopen (const char *filename, const char *mode)
static void fclose (FILE *f)
static bool inZipfile (const std::string &path)
static void removeFile (const std::string &path)
Delete this file. No effect if path does not exist.
static bool isZipfile (const std::string &path)
static float cacheLifetime ()
static void createDirectory (const std::string &path)
static std::string currentDirectory ()
static void copyFile (const std::string &srcPath, const std::string &dstPath)
static bool exists (const std::string &f, bool trustCache=true, bool caseSensitive=true)
static bool isDirectory (const std::string &path)
static bool isFile (const std::string &path)
static std::string resolve (const std::string &path, const std::string &cwd=currentDirectory())
static bool isNewer (const std::string &src, const std::string &dst)
static int64 size (const std::string &path)
static void list (const std::string &spec, Array< std::string > &result, const ListSettings &listSettings=ListSettings())
static void getFiles (const std::string &spec, Array< std::string > &result, bool includeParentPath=false)
static void getDirectories (const std::string &spec, Array< std::string > &result, bool includeParentPath=false)
static void markFileUsed (const std::string &filename)
static const Set< std::string > & usedFiles ()
Private Types
enum Type { UNKNOWN , FILE_TYPE , DIR_TYPE }
Private Member Functions
Dir & getContents (const std::string &path, bool forceUpdate)
FileSystem ()
bool _inZipfile (const std::string &path, std::string &zipfile)
void _clearCache (const std::string &path)
bool _inZipfile (const std::string &path)
void _setCacheLifetime (float t)
float _cacheLifetime () const
void _createDirectory (const std::string &path)
bool _exists (const std::string &f, bool trustCache=true, bool caseSensitive=true)
bool _isDirectory (const std::string &path)
bool _isFile (const std::string &path)
void _copyFile (const std::string &srcPath, const std::string &dstPath)
std::string _resolve (const std::string &path, const std::string &cwd=currentDirectory())
bool _isNewer (const std::string &src, const std::string &dst)
std::string _currentDirectory ()
int64 _size (const std::string &path)
void listHelper (const std::string &shortSpec, const std::string &parentPath, Array< std::string > &result, const ListSettings &settings)
void _list (const std::string &spec, Array< std::string > &result, const ListSettings &listSettings=ListSettings())
bool _isZipfile (const std::string &path)
void _getFiles (const std::string &spec, Array< std::string > &result, bool includeParentPath=false)
void _getDirectories (const std::string &spec, Array< std::string > &result, bool includeParentPath=false)
FILE * _fopen (const char *filename, const char *mode)
void _removeFile (const std::string &path)
Delete this file. No effect if path does not exist.
Static Private Member Functions
static FileSystem & instance ()
Private Attributes
Array< std::string > m_winDrive
float m_cacheLifetime
Table< std::string, Dir > m_cache
Static Private Attributes
static GMutex mutex
Detailed Description
OS-independent file system layer that optimizes the performance of queries by caching and prefetching.
This class uses the following definitions:
"file" = document that can be opened for reading or writing
"directory" = folder containing files and other directories
"node" = file or directory
"path" = string identifying a (see the FSPath class)
"zipfile" = a compressed file storing an archive of files and directories in the zip format
In G3D, Zipfiles are transparently treated as if they were directories, provided:
The zipfile name contains an extension (e.g., map.pk3, files.zip)
There are no nested zipfiles
All FileSystem routines invoke FilePath::expandEnvironmentVariables if the input contains a '$'.
The extension requirement allows G3D to quickly identify whether a path could enter a zipfile without forcing it to open all parent directories for reading.
See also
FilePath
Definition at line 46 of file FileSystem.h.
Member Enumeration Documentation
Type
enum G3D::FileSystem::Type private
Enumerator
UNKNOWN
Not yet checked
FILE_TYPE
DIR_TYPE
Definition at line 86 of file FileSystem.h.
               {
         UNKNOWN,
         FILE_TYPE,
         DIR_TYPE
     };
Constructor & Destructor Documentation
FileSystem()
G3D::FileSystem::FileSystem () private
Don't allow public construction.
Definition at line 69 of file FileSystem.cpp.
 : m_cacheLifetime(10) {}
Referenced by init().
Member Function Documentation
_cacheLifetime()
float G3D::FileSystem::_cacheLifetime () const inline private
A cache is used to optimize repeated calls. A cache entry is considered valid for this many seconds after it has been checked.
Definition at line 168 of file FileSystem.h.
{
         return m_cacheLifetime;
     }
References m_cacheLifetime.
Referenced by cacheLifetime().
_clearCache()
void G3D::FileSystem::_clearCache (const std::string & path) private
Clears old cache entries so that exists() and list() will reflect recent changes to the file system.
Parameters
path Clear only path and its subdirectories ("" means clear the entire cache)
Definition at line 337 of file FileSystem.cpp.
{
     const std::string& path = FilePath::expandEnvironmentVariables(_path);
     if ((path == "") || FilePath::isRoot(path)) {
         m_cache.clear();
     } else {
         Array<std::string> keys;
         m_cache.getKeys(keys);
         const std::string& prefix =
 #           ifdef G3D_WINDOWS
                 toLower(FilePath::canonicalize(FilePath::removeTrailingSlash(_resolve(path))));
 #           else
                 FilePath::canonicalize(FilePath::removeTrailingSlash(_resolve(path)));
 #           endif
         const std::string& prefixSlash = prefix + "/";
         for (int k = 0; k < keys.size(); ++k) {
             const std::string& key = keys[k];
             if ((key == prefix) || beginsWith(key, prefixSlash)) {
                 m_cache.remove(keys[k]);
             }
         }
     }
 }
References _resolve(), G3D::beginsWith(), G3D::FilePath::canonicalize(), G3D::FilePath::expandEnvironmentVariables(), G3D::FilePath::isRoot(), m_cache, G3D::FilePath::removeTrailingSlash(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::toLower().
Referenced by _copyFile(), _createDirectory(), _fopen(), _removeFile(), and clearCache().
_copyFile()
void G3D::FileSystem::_copyFile (const std::string & srcPath, const std::string & dstPath) private
Parameters
srcPath Must name a file.
dstPath Must not contain a zipfile.
Flushes the cache.
Definition at line 424 of file FileSystem.cpp.
{
     const std::string& source = FilePath::expandEnvironmentVariables(_source);
     const std::string& dest = FilePath::expandEnvironmentVariables(_dest);
 #   ifdef G3D_WINDOWS
         // TODO: handle case where srcPath is in a zipfile
         CopyFileA(source.c_str(), dest.c_str(), FALSE);
         _clearCache(FilePath::parent(_resolve(dest)));
 #   else
         // Read it all in, then dump it out
         BinaryInput  in(source, G3D_LITTLE_ENDIAN);
         BinaryOutput out(dest, G3D_LITTLE_ENDIAN);
         out.writeBytes(in.getCArray(), in.size());
         out.commit(false);
 #   endif
 }
References _clearCache(), _resolve(), G3D::BinaryOutput::commit(), G3D::FilePath::expandEnvironmentVariables(), FALSE, G3D::G3D_LITTLE_ENDIAN, G3D::BinaryInput::getCArray(), G3D::FilePath::parent(), G3D::BinaryInput::size(), and G3D::BinaryOutput::writeBytes().
Referenced by copyFile().
_createDirectory()
void G3D::FileSystem::_createDirectory (const std::string & path) private
Creates the directory named, including any subdirectories that do not already exist.
The directory must not be inside a zipfile.
Flushes the cache.
Definition at line 369 of file FileSystem.cpp.
{
     const std::string& dir = FilePath::expandEnvironmentVariables(_dir);
     if (dir == "") {
         return;
     }
     std::string d = _resolve(dir);
     // Add a trailing / if there isn't one.
     switch (d[d.size() - 1]) {
     case '/':
     case '\\':
         break;
     default:
         d += "/";
     }
     // If it already exists, do nothing
     if (_exists(FilePath::removeTrailingSlash(d))) {
         return;
     }
     // Parse the name apart
     std::string root, base, ext;
     Array<std::string> path;
     std::string lead;
     FilePath::parse(d, root, path, base, ext);
     debugAssert(base == "");
     debugAssert(ext == "");
     // Begin with an extra period so "c:\" becomes "c:\.\" after
     // appending a path and "c:" becomes "c:.\", not root: "c:\"
     std::string p = root + ".";
     // Create any intermediate that doesn't exist
     for (int i = 0; i < path.size(); ++i) {
         p += "/" + path[i];
         if (! _exists(p)) {
             // Windows only requires one argument to mkdir,
             // where as unix also requires the permissions.
 #           ifndef G3D_WINDOWS
                 mkdir(p.c_str(), 0777);
 #           else
                 _mkdir(p.c_str());
 #           endif
         }
     }
     _clearCache(FilePath::parent(FilePath::removeTrailingSlash(d)));
 }
References _clearCache(), _exists(), _resolve(), mpq::d, debugAssert, G3D::FilePath::expandEnvironmentVariables(), G3D::FilePath::parent(), G3D::FilePath::parse(), G3D::FilePath::removeTrailingSlash(), and G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by createDirectory().
_currentDirectory()
std::string G3D::FileSystem::_currentDirectory () private
The current working directory (cwd). Only ends in a slash if this is the root of the file system.
Definition at line 542 of file FileSystem.cpp.
{
     static const int N = 2048;
     char buffer[N];
     (void)_getcwd(buffer, N);
     return std::string(buffer);
 }
References _getcwd.
Referenced by currentDirectory().
_exists()
bool G3D::FileSystem::_exists (const std::string & f, bool trustCache = true, bool caseSensitive = true) private
Returns true if a node named f exists.
Parameters
f If f contains wildcards, the function returns true if any file matches those wildcards. Wildcards may only appear in the base or ext, not the path. Environment variables beginning with dollar signs (e.g., in "$G3DDATA/cubemap"), with optional parens ("$(G3DDATA)") are automatically expanded in f. Default share names on Windows (e.g., "\\mycomputer\c$") are correctly distinguished from empty environment variables.
trustCache If true, uses the cache for optimizing repeated calls in the same parent directory.
caseSensitive If true, the match must have exactly the same case for the base and extension. If false, case is ignored. The default on Windows is false and the default on other operating systems is true.
Definition at line 441 of file FileSystem.cpp.
{
     const std::string& f = FilePath::expandEnvironmentVariables(_f);
     if (FilePath::isRoot(f)) {
 #       ifdef G3D_WINDOWS
             const std::string& winname = toLower(f.substr(0, 1)) + ":\\";
             return _drives().contains(winname);
 #       else
             return true;
 #       endif
     }
     const std::string& path = FilePath::removeTrailingSlash(f);
     const std::string& parentPath = FilePath::parent(path);
     const bool forceUpdate = ! trustCache;
     const Dir& entry = getContents(parentPath, forceUpdate);
     if (FilePath::containsWildcards(f)) {
         if (! entry.exists) {
             // The directory didn't exist, so neither do its contents
             return false;
         }
         const std::string& pattern = FilePath::baseExt(path);
         // See if any element of entry matches the wild card
         for (int i = 0; i < entry.nodeArray.size(); ++i) {
             if (FilePath::matches(entry.nodeArray[i].name, pattern, caseSensitive)) {
                 return true;
             }
         }
         // Could not find a match
         return false;
     } else {
         return entry.exists && entry.contains(FilePath::baseExt(path), caseSensitive);
     }
 }
References G3D::FilePath::baseExt(), G3D::FileSystem::Dir::contains(), G3D::FilePath::containsWildcards(), G3D::FileSystem::Dir::exists, G3D::FilePath::expandEnvironmentVariables(), f(), getContents(), G3D::FilePath::isRoot(), G3D::FilePath::matches(), G3D::FileSystem::Dir::nodeArray, G3D::FilePath::parent(), G3D::FilePath::removeTrailingSlash(), and G3D::toLower().
Referenced by _createDirectory(), and exists().
_fopen()
FILE * G3D::FileSystem::_fopen (const char * filename, const char * mode) private
Same as the C standard library fopen, but updates the file cache to acknowledge the new file on a write operation.
Definition at line 321 of file FileSystem.cpp.
{
     const std::string& filename = FilePath::canonicalize(FilePath::expandEnvironmentVariables(_filename));
     for (const char* m = mode; *m != '\0'; ++m) {
         if (*m == 'w') {
             // Purge the cache entry for the parent of this directory
             _clearCache(FilePath::parent(_resolve(filename)));
             break;
         }
     }
     markFileUsed(filename);
     return ::fopen(filename.c_str(), mode);
 }
References _clearCache(), anonymous_namespace{Config.cpp}::_filename, _resolve(), G3D::FilePath::canonicalize(), G3D::FilePath::expandEnvironmentVariables(), markFileUsed(), and G3D::FilePath::parent().
Referenced by fopen().
_getDirectories()
void G3D::FileSystem::_getDirectories (const std::string & spec, Array< std::string > & result, bool includeParentPath = false) inline private
list() directories
Definition at line 226 of file FileSystem.h.
{
         ListSettings set;
         set.includeParentPath = includeParentPath;
         set.directories = true;
         set.files = false;
         return list(spec, result, set);
     }
References list(), and set().
Referenced by getDirectories().
_getFiles()
void G3D::FileSystem::_getFiles (const std::string & spec, Array< std::string > & result, bool includeParentPath = false) inline private
list() files
Definition at line 217 of file FileSystem.h.
{
         ListSettings set;
         set.includeParentPath = includeParentPath;
         set.directories = false;
         set.files = true;
         return list(spec, result, set);
     }
References list(), and set().
Referenced by getFiles().
_inZipfile() [1/2]
bool G3D::FileSystem::_inZipfile (const std::string & path) inline private
Returns true if some sub-path of path is a zipfile.
If the path itself is a zipfile, returns false.
Parameters
zipfile The part of path that was the zipfile
Definition at line 158 of file FileSystem.h.
{
         std::string ignore;
         return inZipfile(path, ignore);
     }
References inZipfile().
_inZipfile() [2/2]
bool G3D::FileSystem::_inZipfile (const std::string & path, std::string & zipfile) private
Returns true if some sub-path of path is a zipfile.
If the path itself is a zipfile, returns false.
Parameters
zipfile The part of path that was the zipfile
Definition at line 261 of file FileSystem.cpp.
{
     const std::string& path = FilePath::expandEnvironmentVariables(_path);
     // Reject trivial cases before parsing
     // Look at all sub-paths containing periods.
     // For each, ask if it is a zipfile.
     size_t current = 0;
     current = path.find('.', current);
     while (current != std::string::npos) {
         // xxxxx/foo.zip/yyyyy
         current = path.find('.', current);
         // Look forward for the next slash
         size_t s = findSlash(path, current);
         if (s == std::string::npos) {
             // No more slashes
             return false;
         }
         z = path.substr(0, s);
         if (_isZipfile(z)) {
             return true;
         }
         current = s + 1;
     }
     z = "";
     return false;
 }
References _isZipfile(), G3D::FilePath::expandEnvironmentVariables(), G3D::findSlash(), and G3D::z.
Referenced by inZipfile().
_isDirectory()
bool G3D::FileSystem::_isDirectory (const std::string & path) private
Known bug: does not work inside zipfiles
Definition at line 483 of file FileSystem.cpp.
{
     const std::string& filename = FilePath::expandEnvironmentVariables(_filename);
     // TODO: work with zipfiles and cache
     struct _stat st;
     const bool exists = _stat(FilePath::removeTrailingSlash(filename).c_str(), &st) != -1;
     return exists && ((st.st_mode & S_IFDIR) != 0);
 }
References anonymous_namespace{Config.cpp}::_filename, _stat, exists(), G3D::FilePath::expandEnvironmentVariables(), and G3D::FilePath::removeTrailingSlash().
Referenced by isDirectory().
_isFile()
bool G3D::FileSystem::_isFile (const std::string & path) inline private
Known bug: does not work inside zipfiles
Definition at line 188 of file FileSystem.h.
{
         return ! isDirectory(path);
     }
References isDirectory().
Referenced by isFile().
_isNewer()
bool G3D::FileSystem::_isNewer (const std::string & src, const std::string & dst) private
Returns true if dst does not exist or src is newer than dst, according to their time stamps.
Known bug: does not work inside zipfiles.
Definition at line 565 of file FileSystem.cpp.
{
     const std::string& src = FilePath::expandEnvironmentVariables(_src);
     const std::string& dst = FilePath::expandEnvironmentVariables(_dst);
     // TODO: work with cache and zipfiles
     struct _stat sts;
     bool sexists = _stat(src.c_str(), &sts) != -1;
     struct _stat dts;
     bool dexists = _stat(dst.c_str(), &dts) != -1;
     return sexists && ((! dexists) || (sts.st_mtime > dts.st_mtime));
 }
References _stat, and G3D::FilePath::expandEnvironmentVariables().
Referenced by isNewer().
_isZipfile()
bool G3D::FileSystem::_isZipfile (const std::string & path) private
Returns true if path is a file that is a zipfile. Note that G3D requires zipfiles to have some extension, although it is not required to be "zip"
Definition at line 296 of file FileSystem.cpp.
{
     const std::string& filename = FilePath::canonicalize(FilePath::expandEnvironmentVariables(_filename));
     FILE* f = fopen(FilePath::removeTrailingSlash(filename).c_str(), "r");
     if (f == NULL) {
         return false;
     }
     uint8 header[4];
     (void)fread(header, 4, 1, f);
     const uint8 zipHeader[4] = {0x50, 0x4b, 0x03, 0x04};
     for (int i = 0; i < 4; ++i) {
         if (header[i] != zipHeader[i]) {
             fclose(f);
             return false;
         }
     }
     fclose(f);
     return true;
 }
References anonymous_namespace{Config.cpp}::_filename, G3D::FilePath::canonicalize(), G3D::FilePath::expandEnvironmentVariables(), f(), fclose(), fopen(), NULL, and G3D::FilePath::removeTrailingSlash().
Referenced by _inZipfile(), and isZipfile().
_list()
void G3D::FileSystem::_list (const std::string & spec, Array< std::string > & result, const ListSettings & listSettings = ListSettings()) private
Appends all nodes matching spec to the result array.
Wildcards can only appear to the right of the last slash in spec.
The names will not contain parent paths unless includePath == true. These may be relative to the current directory unless spec is fully qualified (can be done with resolveFilename).
Definition at line 665 of file FileSystem.cpp.
{
     const std::string& spec = FilePath::expandEnvironmentVariables(_spec);
     const std::string& shortSpec = FilePath::baseExt(spec);
     const std::string& parentPath = FilePath::parent(spec);
     listHelper(shortSpec, parentPath, result, settings);
 }
References G3D::FilePath::baseExt(), G3D::FilePath::expandEnvironmentVariables(), listHelper(), and G3D::FilePath::parent().
Referenced by list().
_removeFile()
void G3D::FileSystem::_removeFile (const std::string & path) private
Delete this file. No effect if path does not exist.
Parameters
path May contain wildcards. May not be inside a zipfile.
Definition at line 492 of file FileSystem.cpp.
{
     alwaysAssertM(! inZipfile(path), "Cannot invoke removeFile() on files inside zipfiles.");
     Array<std::string> files;
     getFiles(path, files, true);
     for (int i = 0; i < files.size(); ++i) {
         const std::string& filename = files[i];
         int retval = ::remove(filename.c_str());
         (void)retval;
     }
     // Remove from cache
     _clearCache(FilePath::parent(path));
 }
References _clearCache(), alwaysAssertM, files, getFiles(), inZipfile(), and G3D::FilePath::parent().
Referenced by removeFile().
_resolve()
std::string G3D::FileSystem::_resolve (const std::string & path, const std::string & cwd = currentDirectory()) private
Fully qualifies a filename.
The filename may contain wildcards, in which case the wildcards will be preserved in the returned value.
Parameters
cwd The directory to treat as the "current" directory when resolving a relative path. The default value is the actual current directory. (G3D::Any::sourceDirectory is a common alternative)
Definition at line 508 of file FileSystem.cpp.
{
     const std::string& filename = FilePath::expandEnvironmentVariables(_filename);
     const std::string& cwd = FilePath::expandEnvironmentVariables(_cwd);
     if (filename.size() >= 1) {
         if (isSlash(filename[0])) {
             // Already resolved
             return filename;
         } else {
             #ifdef G3D_WINDOWS
                 if ((filename.size() >= 2) && (filename[1] == ':')) {
                     // There is a drive spec on the front.
                     if ((filename.size() >= 3) && isSlash(filename[2])) {
                         // Already fully qualified
                         return filename;
                     } else {
                         // The drive spec is relative to the
                         // working directory on that drive.
                         debugAssertM(false, "Files of the form d:path are"
                                      " not supported (use a fully qualified"
                                      " name).");
                         return filename;
                     }
                 }
             #endif
         }
     }
     // Prepend the working directory.
     return FilePath::concat(cwd, filename);
 }
References anonymous_namespace{Config.cpp}::_filename, G3D::FilePath::concat(), debugAssertM, G3D::FilePath::expandEnvironmentVariables(), and G3D::isSlash().
Referenced by _clearCache(), _copyFile(), _createDirectory(), _fopen(), and resolve().
_setCacheLifetime()
void G3D::FileSystem::_setCacheLifetime (float t) private
Set the cacheLifetime().
Parameters
t in seconds
Definition at line 364 of file FileSystem.cpp.
{
     m_cacheLifetime = t;
 }
References m_cacheLifetime.
Referenced by setCacheLifetime().
_size()
int64 G3D::FileSystem::_size (const std::string & path) private
Returns the length of the file in bytes, or -1 if the file could not be opened.
Definition at line 580 of file FileSystem.cpp.
{
     const std::string& filename = FilePath::canonicalize(FilePath::expandEnvironmentVariables(_filename));
     struct stat64 st;
     int result = stat64(filename.c_str(), &st);
     if (result == -1) {
 #if _HAVE_ZIP /* G3DFIX: Use ZIP-library only if defined */
         std::string zip, contents;
         if (zipfileExists(filename, zip, contents)) {
             int64 requiredMem;
             struct zip *z = zip_open( zip.c_str(), ZIP_CHECKCONS, NULL );
             debugAssertM(z != NULL, zip + ": zip open failed.");
             {
                 struct zip_stat info;
                 zip_stat_init( &info );    // Docs unclear if zip_stat_init is required.
                 int success = zip_stat( z, contents.c_str(), ZIP_FL_NOCASE, &info );
                 (void) success;
                 debugAssertM(success == 0, zip + ": " + contents + ": zip stat failed.");
                 requiredMem = info.size;
             }
             zip_close(z);
             return requiredMem;
         } else {
 #endif
             return -1;
 #if _HAVE_ZIP /* G3DFIX: Use ZIP-library only if defined */
          }
 #endif
     }
     return st.st_size;
 }
References anonymous_namespace{Config.cpp}::_filename, G3D::FilePath::canonicalize(), debugAssertM, G3D::FilePath::expandEnvironmentVariables(), NULL, G3D::z, and G3D::zipfileExists().
Referenced by size().
cacheLifetime()
static float G3D::FileSystem::cacheLifetime () inline static
A cache is used to optimize repeated calls. A cache entry is considered valid for this many seconds after it has been checked.
Definition at line 341 of file FileSystem.h.
{
         mutex.lock();
         float f = instance()._cacheLifetime();
         mutex.unlock();
         return f;
     }
References _cacheLifetime(), f(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by getContents().
cleanup()
void G3D::FileSystem::cleanup () static
Destroy the common instance.
Definition at line 62 of file FileSystem.cpp.
{
     if (common != NULL) {
         delete common;
         common = NULL;
     }
 }
References G3D::common, and NULL.
clearCache()
static void G3D::FileSystem::clearCache (const std::string & path = "") inline static
Clears old cache entries so that exists() and list() will reflect recent changes to the file system.
Parameters
path Clear only path and its subdirectories ("" means clear the entire cache)
Definition at line 273 of file FileSystem.h.
{
         mutex.lock();
         instance()._clearCache(path);
         mutex.unlock();
     }
References _clearCache(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
copyFile()
static void G3D::FileSystem::copyFile (const std::string & srcPath, const std::string & dstPath) inline static
Parameters
srcPath Must name a file.
dstPath Must not contain a zipfile.
Flushes the cache.
Definition at line 378 of file FileSystem.h.
{
         mutex.lock();
         instance()._copyFile(srcPath, dstPath);
         mutex.unlock();
     }
References _copyFile(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
createDirectory()
static void G3D::FileSystem::createDirectory (const std::string & path) inline static
Creates the directory named, including any subdirectories that do not already exist.
The directory must not be inside a zipfile.
Flushes the cache.
Definition at line 356 of file FileSystem.h.
{
         mutex.lock();
         instance()._createDirectory(path);
         mutex.unlock();
     }
References _createDirectory(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by G3D::BinaryOutput::commit(), G3D::TextOutput::commit(), and G3D::writeWholeFile().
currentDirectory()
static std::string G3D::FileSystem::currentDirectory () inline static
The current working directory (cwd). Only ends in a slash if this is the root of the file system.
Definition at line 364 of file FileSystem.h.
{
         mutex.lock();
         const std::string& s = instance()._currentDirectory();
         mutex.unlock();
         return s;
     }
References _currentDirectory(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by G3D::System::findDataFile().
exists()
static bool G3D::FileSystem::exists (const std::string & f, bool trustCache = true, bool caseSensitive = true) inline static
Returns true if a node named f exists.
Parameters
f If f contains wildcards, the function returns true if any file matches those wildcards. Wildcards may only appear in the base or ext, not the path. Environment variables beginning with dollar signs (e.g., in "$G3DDATA/cubemap"), with optional parens ("$(G3DDATA)") are automatically expanded in f. Default share names on Windows (e.g., "\\mycomputer\c$") are correctly distinguished from empty environment variables.
trustCache If true, uses the cache for optimizing repeated calls in the same parent directory.
caseSensitive If true, the match must have exactly the same case for the base and extension. If false, case is ignored. The default on Windows is false and the default on other operating systems is true.
Definition at line 401 of file FileSystem.h.
           {
         mutex.lock();
         bool e = instance()._exists(f, trustCache, caseSensitive);
         mutex.unlock();
         return e;
     }
References _exists(), f(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _isDirectory(), G3D::BinaryOutput::commit(), G3D::TextOutput::commit(), G3D::FileSystem::Dir::computeZipListing(), G3D::createDirectory(), G3D::Any::deserialize(), G3D::determineFileOrDirList(), G3D::System::findDataFile(), getContents(), G3D::Any::loadIfExists(), G3D::readWholeFile(), G3D::Any::resolveStringAsFilename(), G3D::writeWholeFile(), and G3D::zipfileExists().
fclose()
static void G3D::FileSystem::fclose (FILE * f) inline static
Definition at line 290 of file FileSystem.h.
{
         mutex.lock();
         ::fclose(f);
         mutex.unlock();
     }
References f(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _isZipfile(), G3D::BinaryInput::BinaryInput(), G3D::BinaryOutput::commit(), G3D::TextOutput::commit(), G3D::readWholeFile(), G3D::TextInput::TextInput(), G3D::writeWholeFile(), and G3D::Log::~Log().
fopen()
static FILE* G3D::FileSystem::fopen (const char * filename, const char * mode) inline static
Same as the C standard library fopen, but updates the file cache to acknowledge the new file on a write operation.
Definition at line 282 of file FileSystem.h.
{
         mutex.lock();
         FILE* f = instance()._fopen(filename, mode);
         mutex.unlock();
         return f;
     }
References _fopen(), f(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _isZipfile(), G3D::BinaryInput::BinaryInput(), G3D::BinaryOutput::commit(), G3D::TextOutput::commit(), G3D::Log::Log(), G3D::readWholeFile(), G3D::BinaryOutput::reserveBytesWhenOutOfMemory(), G3D::TextInput::TextInput(), and G3D::writeWholeFile().
getContents()
FileSystem::Dir & G3D::FileSystem::getContents (const std::string & path, bool forceUpdate) private
Update the cache entry for path if it is not already present.
Parameters
forceUpdate If true, always override the current cache value.
Definition at line 147 of file FileSystem.cpp.
{
     const std::string& key =
 #   if defined(G3D_WINDOWS)
         FilePath::canonicalize(FilePath::removeTrailingSlash(toLower(FilePath::canonicalize(resolve(path)))));
 #   else
         FilePath::canonicalize(FilePath::removeTrailingSlash(FilePath::canonicalize(resolve(path))));
 #   endif
     RealTime now = System::time();
     Dir& dir = m_cache.getCreate(key);
     if ((now > dir.lastChecked + cacheLifetime()) || forceUpdate) {
         dir = Dir();
         // Out of date: update
         dir.lastChecked = now;
 #       ifdef G3D_WINDOWS
             // On windows, we have to use GetFileAttributes (http://msdn.microsoft.com/en-us/library/aa364944(v=vs.85).aspx) instead of
             // stat in order to work with network shares
             const DWORD st = GetFileAttributesA(key.c_str());
             const bool exists = (st != INVALID_FILE_ATTRIBUTES);
             const bool isDirectory = (st & FILE_ATTRIBUTE_DIRECTORY) != 0;
 #       else
             struct _stat st;
             const bool exists = _stat(key.c_str(), &st) != -1;
             const bool isDirectory = (st.st_mode & S_IFDIR) != 0;
 #       endif
         // Does this path exist on the real filesystem?
         if (exists && isDirectory) {
             // Is this path actually a directory?
             if (isDirectory) {
                 dir.exists = true;
                 // Update contents
 #               ifdef G3D_WINDOWS
                     const std::string& filespec = FilePath::concat(key, "*");
                     struct _finddata_t fileinfo;
                     intptr_t handle = _findfirst(filespec.c_str(), &fileinfo);
                     debugAssert(handle != -1);
                     int result = 0;
                     do {
                         if ((strcmp(fileinfo.name, ".") != 0) && (strcmp(fileinfo.name, "..") != 0)) {
                             Entry& e = dir.nodeArray.next();
                             e.name = fileinfo.name;
                             if ((fileinfo.attrib & _A_SUBDIR) != 0) {
                                 e.type = DIR_TYPE;
                             } else {
                                 e.type = FILE_TYPE;
                             }
                         }
                         result = _findnext(handle, &fileinfo);
                     } while (result == 0);
                     _findclose(handle);
 #               else
                     DIR* listing = opendir(key.c_str());
                     debugAssertM(listing, "opendir failed on '" + key + "'");
                     struct dirent* entry = readdir(listing);
                     while (entry != NULL) {
                         if ((strcmp(entry->d_name, "..") != 0) && (strcmp(entry->d_name, ".") != 0)) {
                             Entry& e = dir.nodeArray.next();
                             e.name = entry->d_name;
 #                           ifdef _DIRENT_HAVE_D_TYPE
                                 // Not all POSIX systems support this field
                                 // http://www.delorie.com/gnu/docs/glibc/libc_270.html
                                 switch (entry->d_type) {
                                 case DT_DIR:
                                     e.type = DIR_TYPE;
                                     break;
                                 case DT_REG:
                                     e.type = FILE_TYPE;
                                     break;
                                 case DT_UNKNOWN:
                                 default:
                                     e.type = UNKNOWN;
                                     break;
                                 }
 #                           endif
                         }
                         entry = readdir(listing);
                     }
                     closedir(listing);
                     listing = NULL;
                     entry = NULL;
 #               endif
             }
         } else {
             std::string zip;
             if (exists && isZipfile(path)) {
                 // This is a zipfile; get its root
                 dir.isZipfile = true;
                 dir.computeZipListing(path, "");
             } else if (inZipfile(path, zip)) {
                 // There is a zipfile somewhere in the path.  Does
                 // the rest of the path exist inside the zipfile?
                 dir.inZipfile = true;
                 dir.computeZipListing(zip, path.substr(zip.length() + 1));
             }
         }
     }
     return dir;
 }
References _stat, cacheLifetime(), G3D::FilePath::canonicalize(), closedir(), G3D::FileSystem::Dir::computeZipListing(), G3D::FilePath::concat(), dirent::d_name, debugAssert, debugAssertM, DIR_TYPE, G3D::FileSystem::Dir::exists, exists(), FILE_TYPE, G3D::FileSystem::Dir::inZipfile, inZipfile(), isDirectory(), G3D::FileSystem::Dir::isZipfile, isZipfile(), G3D::FileSystem::Dir::lastChecked, m_cache, G3D::FileSystem::Entry::name, fileinfo::name, G3D::FileSystem::Dir::nodeArray, NULL, opendir(), readdir(), G3D::FilePath::removeTrailingSlash(), resolve(), G3D::System::time(), G3D::toLower(), G3D::FileSystem::Entry::type, and UNKNOWN.
Referenced by _exists(), and listHelper().
getDirectories()
static void G3D::FileSystem::getDirectories (const std::string & spec, Array< std::string > & result, bool includeParentPath = false) inline static
list() directories
Definition at line 496 of file FileSystem.h.
{
         mutex.lock();
         instance()._getDirectories(spec, result, includeParentPath);
         mutex.unlock();
     }
References _getDirectories(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
getFiles()
static void G3D::FileSystem::getFiles (const std::string & spec, Array< std::string > & result, bool includeParentPath = false) inline static
list() files
Definition at line 488 of file FileSystem.h.
{
         mutex.lock();
         instance()._getFiles(spec, result, includeParentPath);
         mutex.unlock();
     }
References _getFiles(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _removeFile(), and G3D::generateFilenameBase().
init()
void G3D::FileSystem::init () static
Create the common instance.
Definition at line 55 of file FileSystem.cpp.
                       {
     if (common == NULL) {
         common = new FileSystem();
     }
 }
References G3D::common, FileSystem(), and NULL.
Referenced by instance().
instance()
FileSystem & G3D::FileSystem::instance () static private
Definition at line 49 of file FileSystem.cpp.
{
     init();
     return *common;
 }
References G3D::common, and init().
Referenced by cacheLifetime(), clearCache(), copyFile(), createDirectory(), currentDirectory(), exists(), fopen(), getDirectories(), getFiles(), inZipfile(), isDirectory(), isFile(), isNewer(), isZipfile(), list(), removeFile(), resolve(), setCacheLifetime(), and size().
inZipfile() [1/2]
static bool G3D::FileSystem::inZipfile (const std::string & path) inline static
Returns true if some sub-path of path is a zipfile.
If the path itself is a zipfile, returns false.
Definition at line 300 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._inZipfile(path);
         mutex.unlock();
         return b;
     }
References _inZipfile(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
inZipfile() [2/2]
static bool G3D::FileSystem::inZipfile (const std::string & path, std::string & zipfile) inline static
Returns true if some sub-path of path is a zipfile.
If the path itself is a zipfile, returns false.
Parameters
zipfile The part of path that was the zipfile
Definition at line 264 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._inZipfile(path, zipfile);
         mutex.unlock();
         return b;
     }
References _inZipfile(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _inZipfile(), _removeFile(), G3D::BinaryInput::BinaryInput(), getContents(), G3D::readWholeFile(), and G3D::TextInput::TextInput().
isDirectory()
static bool G3D::FileSystem::isDirectory (const std::string & path) inline static
Known bug: does not work inside zipfiles
Definition at line 416 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._isDirectory(path);
         mutex.unlock();
         return b;
     }
References _isDirectory(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _isFile(), getContents(), and listHelper().
isFile()
static bool G3D::FileSystem::isFile (const std::string & path) inline static
Known bug: does not work inside zipfiles
Definition at line 425 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._isFile(path);
         mutex.unlock();
         return b;
     }
References _isFile(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
isNewer()
static bool G3D::FileSystem::isNewer (const std::string & src, const std::string & dst) inline static
Returns true if dst does not exist or src is newer than dst, according to their time stamps.
Known bug: does not work inside zipfiles.
Definition at line 453 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._isNewer(src, dst);
         mutex.unlock();
         return b;
     }
References _isNewer(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
isZipfile()
static bool G3D::FileSystem::isZipfile (const std::string & path) inline static
Returns true if path is a file that is a zipfile. Note that G3D requires zipfiles to have some extension, although it is not required to be "zip"
Definition at line 323 of file FileSystem.h.
{
         mutex.lock();
         bool b = instance()._isZipfile(path);
         mutex.unlock();
         return b;
     }
References _isZipfile(), b, instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by G3D::determineFileOrDirList(), getContents(), and G3D::zipfileExists().
list()
static void G3D::FileSystem::list (const std::string & spec, Array< std::string > & result, const ListSettings & listSettings = ListSettings()) inline static
Appends all nodes matching spec to the result array.
Wildcards can only appear to the right of the last slash in spec.
The names will not contain parent paths unless includePath == true. These may be relative to the current directory unless spec is fully qualified (can be done with resolveFilename).
Definition at line 479 of file FileSystem.h.
{
         mutex.lock();
         instance()._list(spec, result, listSettings);
         mutex.unlock();
     }
References _list(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _getDirectories(), and _getFiles().
listHelper()
void G3D::FileSystem::listHelper (const std::string & shortSpec, const std::string & parentPath, Array< std::string > & result, const ListSettings & settings) private
Called from list()
Definition at line 616 of file FileSystem.cpp.
{
     Dir& dir = getContents(parentPath, false);
     if (! dir.exists) {
         return;
     }
     for (int i = 0; i < dir.nodeArray.size(); ++i) {
         Entry& entry = dir.nodeArray[i];
         // See if it matches the spec
         if (FilePath::matches(entry.name, shortSpec, settings.caseSensitive)) {
             if ((entry.type == UNKNOWN) &&
                 (! (settings.files && settings.directories) ||
                  settings.recursive)) {
                 // Update the type: it is unknown and we'll need to branch onit below
                 entry.type = isDirectory(FilePath::concat(parentPath, entry.name)) ? DIR_TYPE : FILE_TYPE;
             }
             if ((settings.files && settings.directories) ||
                 (settings.files && (entry.type == FILE_TYPE)) ||
                 (settings.directories && (entry.type == DIR_TYPE))) {
                 if (settings.includeParentPath) {
                     result.append(FilePath::concat(parentPath, entry.name));
                 } else {
                     result.append(entry.name);
                 }
             }
         } // match
         if (settings.recursive) {
             if (entry.type == UNKNOWN) {
                 entry.type = isDirectory(FilePath::concat(parentPath, entry.name)) ? DIR_TYPE : FILE_TYPE;
             }
             if (entry.type == DIR_TYPE) {
                 listHelper(shortSpec, FilePath::concat(parentPath, entry.name), result, settings);
             }
         }
     } // for
 }
References G3D::FilePath::concat(), DIR_TYPE, G3D::FileSystem::Dir::exists, FILE_TYPE, getContents(), isDirectory(), G3D::FilePath::matches(), G3D::FileSystem::Entry::name, G3D::FileSystem::Dir::nodeArray, G3D::FileSystem::Entry::type, and UNKNOWN.
Referenced by _list().
markFileUsed()
void G3D::FileSystem::markFileUsed (const std::string & filename) static
Adds filename to usedFiles(). This is called automatically by open() and all G3D routines that open files.
Definition at line 553 of file FileSystem.cpp.
{
     mutex.lock();
     _filesUsed.insert(filename);
     mutex.unlock();
 }
References G3D::_filesUsed, G3D::Set< T, HashFunc, EqualsFunc >::insert(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by _fopen(), G3D::BinaryInput::BinaryInput(), and G3D::readWholeFile().
removeFile()
static void G3D::FileSystem::removeFile (const std::string & path) inline static
Delete this file. No effect if path does not exist.
Parameters
path May contain wildcards. May not be inside a zipfile.
Definition at line 314 of file FileSystem.h.
{
         mutex.lock();
         instance()._removeFile(path);
         mutex.unlock();
     }
References _removeFile(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
resolve()
static std::string G3D::FileSystem::resolve (const std::string & path, const std::string & cwd = currentDirectory()) inline static
Fully qualifies a filename.
The filename may contain wildcards, in which case the wildcards will be preserved in the returned value.
Parameters
cwd The directory to treat as the "current" directory when resolving a relative path. The default value is the actual current directory. (G3D::Any::sourceDirectory is a common alternative)
Definition at line 440 of file FileSystem.h.
{
         mutex.lock();
         const std::string& s = instance()._resolve(path, cwd);
         mutex.unlock();
         return s;
     }
References _resolve(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by G3D::Any::deserialize(), getContents(), G3D::Any::load(), and G3D::Any::resolveStringAsFilename().
setCacheLifetime()
void G3D::FileSystem::setCacheLifetime (float t) inline
Set the cacheLifetime().
Parameters
t in seconds
Definition at line 333 of file FileSystem.h.
{
         mutex.lock();
         instance()._setCacheLifetime(t);
         mutex.unlock();
     }
References _setCacheLifetime(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
size()
static int64 G3D::FileSystem::size (const std::string & path) inline static
Returns the length of the file in bytes, or -1 if the file could not be opened.
Definition at line 462 of file FileSystem.h.
{
         mutex.lock();
         int64 i = instance()._size(path);
         mutex.unlock();
         return i;
     }
References _size(), instance(), G3D::GMutex::lock(), mutex, and G3D::GMutex::unlock().
Referenced by G3D::BinaryInput::BinaryInput(), G3D::readWholeFile(), and G3D::TextInput::TextInput().
usedFiles()
const Set< std::string > & G3D::FileSystem::usedFiles () static
All files that have been marked by markFileUsed(). GApp automatically prints this list to log.txt. It is useful for finding the dependencies of your program automatically.
Definition at line 560 of file FileSystem.cpp.
{
     return _filesUsed;
 }
References G3D::_filesUsed.
Member Data Documentation
m_cache
Table<std::string, Dir> G3D::FileSystem::m_cache private
Maps path names (without trailing slashes, except for the file system root) to contents. On Windows, all paths are lowercase
Definition at line 133 of file FileSystem.h.
Referenced by _clearCache(), and getContents().
m_cacheLifetime
float G3D::FileSystem::m_cacheLifetime private
Definition at line 84 of file FileSystem.h.
Referenced by _cacheLifetime(), and _setCacheLifetime().
m_winDrive
Array<std::string> G3D::FileSystem::m_winDrive private
Drive letters. Only used on windows, but defined on all platforms to help avoid breaking the Windows build when compiling on another platform.
Definition at line 82 of file FileSystem.h.
mutex
GMutex G3D::FileSystem::mutex static private
Definition at line 143 of file FileSystem.h.
Referenced by cacheLifetime(), clearCache(), copyFile(), createDirectory(), currentDirectory(), exists(), fclose(), fopen(), getDirectories(), getFiles(), inZipfile(), isDirectory(), isFile(), isNewer(), isZipfile(), list(), markFileUsed(), removeFile(), resolve(), setCacheLifetime(), and size().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/FileSystem.h
deps/g3dlite/source/FileSystem.cpp