Azerotcore-wotlk: SlaveRunEvent Class Reference
SlaveRunEvent Class Reference
Public Member Functions
SlaveRunEvent (Creature &owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
Detailed Description
Definition at line 1378 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
SlaveRunEvent()
SlaveRunEvent::SlaveRunEvent (Creature & owner) inline
Definition at line 1381 of file pit_of_saron.cpp.
 : _owner(owner) { }
Member Function Documentation
Execute()
bool SlaveRunEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 1383 of file pit_of_saron.cpp.
     {
         uint32 pointId = 0;
         float minDist = _owner.GetExactDist2dSq(&slaveFreePos[pointId]);
         for (uint32 i = 1; i < 4; ++i)
         {
             float dist = _owner.GetExactDist2dSq(&slaveFreePos[i]);
             if (dist < minDist)
             {
                 minDist = dist;
                 pointId = i;
             }
         }
         if (minDist < 200.0f * 200.0f)
             _owner.GetMotionMaster()->MovePoint(0, slaveFreePos[pointId], true, false);
         return true;
     }
References _owner, Position::GetExactDist2dSq(), Unit::GetMotionMaster(), MotionMaster::MovePoint(), and slaveFreePos.
Member Data Documentation
_owner
Creature& SlaveRunEvent::_owner private
Definition at line 1402 of file pit_of_saron.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp