Azerotcore-wotlk: npc_freya_ward::npc_freya_wardAI Struct Reference
npc_freya_ward::npc_freya_wardAI Struct Reference
Public Member Functions
npc_freya_wardAI (Creature *c)
void Reset () override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void UpdateAI (uint32 diff) override
void DoAction (int32 param) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
uint32 _castTimer
bool _summoned
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 898 of file boss_flame_leviathan.cpp.
Constructor & Destructor Documentation
npc_freya_wardAI()
npc_freya_ward::npc_freya_wardAI::npc_freya_wardAI (Creature * c) inline
Definition at line 900 of file boss_flame_leviathan.cpp.
                                       : NullCreatureAI(c), summons(c)
         {
         }
Member Function Documentation
DoAction()
void npc_freya_ward::npc_freya_wardAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 960 of file boss_flame_leviathan.cpp.
         {
             if (param == ACTION_DESPAWN_ADDS)
                 summons.DespawnAll();
         }
References ACTION_DESPAWN_ADDS, and summons.
JustSummoned()
void npc_freya_ward::npc_freya_wardAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
Definition at line 921 of file boss_flame_leviathan.cpp.
         {
             _summoned = true;
             summons.Summon(cr);
         }
References summons.
Reset()
void npc_freya_ward::npc_freya_wardAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 908 of file boss_flame_leviathan.cpp.
         {
             _summoned = false;
             _castTimer = 25000;
             summons.DespawnAll();
             if (Creature* cr = me->FindNearestCreature(NPC_FREYA_WARD_TARGET, 60.0f, true))
                 if (Aura* aur = cr->AddAura(SPELL_FREYA_DUMMY_GREEN, cr))
                 {
                     aur->SetMaxDuration(-1);
                     aur->SetDuration(-1);
                 }
         }
References WorldObject::FindNearestCreature(), NPC_FREYA_WARD_TARGET, SPELL_FREYA_DUMMY_GREEN, and summons.
SummonedCreatureDespawn()
void npc_freya_ward::npc_freya_wardAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
Definition at line 927 of file boss_flame_leviathan.cpp.
 { summons.Despawn(cr); }
References summons.
UpdateAI()
void npc_freya_ward::npc_freya_wardAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 929 of file boss_flame_leviathan.cpp.
         {
             if (_summoned)
             {
                 for (SummonList::const_iterator itr = summons.begin(); itr != summons.end();)
                 {
                     Creature* summon = ObjectAccessor::GetCreature(*me, *itr);
                     ++itr;
                     if (summon)
                     {
                         summon->ToTempSummon()->SetTempSummonType(TEMPSUMMON_MANUAL_DESPAWN);
                         if (Unit* target = summon->SelectNearestTarget(200.0f))
                             summon->AI()->AttackStart(target);
                     }
                 }
                 _summoned = false;
             }
             _castTimer += diff;
             if (_castTimer >= 29 * IN_MILLISECONDS)
             {
                 if (Creature* cr = me->FindNearestCreature(NPC_FREYA_WARD_TARGET, 60.0f, true))
                 {
                     me->CastSpell(cr, SPELL_FREYA_WARD, false);
                     me->CastSpell(cr, 62947 /*SPELL_FREYA_WARD_SECOND_SUMMON*/, false);
                 }
                 _castTimer = 0;
             }
         }
References Creature::AI(), UnitAI::AttackStart(), WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), IN_MILLISECONDS, NPC_FREYA_WARD_TARGET, Creature::SelectNearestTarget(), TempSummon::SetTempSummonType(), SPELL_FREYA_WARD, summons, TEMPSUMMON_MANUAL_DESPAWN, and Unit::ToTempSummon().
Member Data Documentation
_castTimer
uint32 npc_freya_ward::npc_freya_wardAI::_castTimer
Definition at line 905 of file boss_flame_leviathan.cpp.
_summoned
bool npc_freya_ward::npc_freya_wardAI::_summoned
Definition at line 906 of file boss_flame_leviathan.cpp.
summons
SummonList npc_freya_ward::npc_freya_wardAI::summons
Definition at line 904 of file boss_flame_leviathan.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp