Azerotcore-wotlk: deps/zlib/crc32.c File Reference
crc32.c File Reference
#include "zutil.h"
#include "crc32.h"
Macros
#define local static
#define TBLS 1
#define DO1 crc = crc_table[0][((int)crc ^ (*buf++)) & 0xff] ^ (crc >> 8)
#define DO8 DO1; DO1; DO1; DO1; DO1; DO1; DO1; DO1
#define GF2_DIM 32 /* dimension of GF(2) vectors (length of CRC) */
Functions
unsigned long gf2_matrix_times OF ((unsigned long *mat, unsigned long vec))
void gf2_matrix_square OF ((unsigned long *square, unsigned long *mat))
uLong crc32_combine_ OF ((uLong crc1, uLong crc2, z_off64_t len2))
const z_crc_t FAR *ZEXPORT get_crc_table ()
unsigned long ZEXPORT crc32 (unsigned long crc, const unsigned char FAR *buf, uInt len)
unsigned long gf2_matrix_times (unsigned long *mat, unsigned long vec)
void gf2_matrix_square (unsigned long *square, unsigned long *mat)
uLong crc32_combine_ (uLong crc1, uLong crc2, z_off64_t len2)
uLong ZEXPORT crc32_combine (uLong crc1, uLong crc2, z_off_t len2)
uLong ZEXPORT crc32_combine64 (uLong crc1, uLong crc2, z_off64_t len2)
Macro Definition Documentation
DO1
#define DO1 crc = crc_table[0][((int)crc ^ (*buf++)) & 0xff] ^ (crc >> 8)
Definition at line 200 of file crc32.c.
DO8
#define DO8 DO1; DO1; DO1; DO1; DO1; DO1; DO1; DO1
Definition at line 201 of file crc32.c.
GF2_DIM
#define GF2_DIM 32 /* dimension of GF(2) vectors (length of CRC) */
Definition at line 324 of file crc32.c.
local
#define local static
Definition at line 33 of file crc32.c.
TBLS
#define TBLS 1
Definition at line 46 of file crc32.c.
Function Documentation
crc32()
unsigned long ZEXPORT crc32 (unsigned long crc, const unsigned char FAR * buf, uInt len)
Definition at line 204 of file crc32.c.
 {
     if (buf == Z_NULL) return 0UL;
 #ifdef DYNAMIC_CRC_TABLE
     if (crc_table_empty)
         make_crc_table();
 #endif /* DYNAMIC_CRC_TABLE */
 #ifdef BYFOUR
     if (sizeof(void *) == sizeof(ptrdiff_t)) {
         z_crc_t endian;
         endian = 1;
         if (*((unsigned char *)(&endian)))
             return crc32_little(crc, buf, len);
         else
             return crc32_big(crc, buf, len);
     }
 #endif /* BYFOUR */
     crc = crc ^ 0xffffffffUL;
     while (len >= 8) {
         DO8;
         len -= 8;
     }
     if (len) do {
         DO1;
     } while (--len);
     return crc ^ 0xffffffffUL;
 }
References DO1, DO8, and Z_NULL.
crc32_combine()
uLong ZEXPORT crc32_combine (uLong crc1, uLong crc2, z_off_t len2)
Definition at line 411 of file crc32.c.
 {
     return crc32_combine_(crc1, crc2, len2);
 }
References crc32_combine_().
crc32_combine64()
uLong ZEXPORT crc32_combine64 (uLong crc1, uLong crc2, z_off64_t len2)
Definition at line 419 of file crc32.c.
 {
     return crc32_combine_(crc1, crc2, len2);
 }
References crc32_combine_().
crc32_combine_()
uLong crc32_combine_ (uLong crc1, uLong crc2, z_off64_t len2)
Definition at line 355 of file crc32.c.
 {
     int n;
     unsigned long row;
     unsigned long even[GF2_DIM];    /* even-power-of-two zeros operator */
     unsigned long odd[GF2_DIM];     /* odd-power-of-two zeros operator */
     /* degenerate case (also disallow negative lengths) */
     if (len2 <= 0)
         return crc1;
     /* put operator for one zero bit in odd */
     odd[0] = 0xedb88320UL;          /* CRC-32 polynomial */
     row = 1;
     for (n = 1; n < GF2_DIM; n++) {
         odd[n] = row;
         row <<= 1;
     }
     /* put operator for two zero bits in even */
     gf2_matrix_square(even, odd);
     /* put operator for four zero bits in odd */
     gf2_matrix_square(odd, even);
     /* apply len2 zeros to crc1 (first square will put the operator for one
        zero byte, eight zero bits, in even) */
     do {
         /* apply zeros operator for this bit of len2 */
         gf2_matrix_square(even, odd);
         if (len2 & 1)
             crc1 = gf2_matrix_times(even, crc1);
         len2 >>= 1;
         /* if no more bits set, then done */
         if (len2 == 0)
             break;
         /* another iteration of the loop with odd and even swapped */
         gf2_matrix_square(odd, even);
         if (len2 & 1)
             crc1 = gf2_matrix_times(odd, crc1);
         len2 >>= 1;
         /* if no more bits set, then done */
     } while (len2 != 0);
     /* return combined crc */
     crc1 ^= crc2;
     return crc1;
 }
References GF2_DIM, gf2_matrix_square(), and gf2_matrix_times().
Referenced by crc32_combine(), and crc32_combine64().
get_crc_table()
const z_crc_t FAR* ZEXPORT get_crc_table ()
Definition at line 190 of file crc32.c.
 {
 #ifdef DYNAMIC_CRC_TABLE
     if (crc_table_empty)
         make_crc_table();
 #endif /* DYNAMIC_CRC_TABLE */
     return (const z_crc_t FAR *)crc_table;
 }
References crc_table, and FAR.
gf2_matrix_square()
void gf2_matrix_square (unsigned long * square, unsigned long * mat)
Definition at line 344 of file crc32.c.
 {
     int n;
     for (n = 0; n < GF2_DIM; n++)
         square[n] = gf2_matrix_times(mat, mat[n]);
 }
References GF2_DIM, gf2_matrix_times(), and G3D::square().
Referenced by crc32_combine_().
gf2_matrix_times()
unsigned long gf2_matrix_times (unsigned long * mat, unsigned long vec)
Definition at line 327 of file crc32.c.
 {
     unsigned long sum;
     sum = 0;
     while (vec) {
         if (vec & 1)
             sum ^= *mat;
         vec >>= 1;
         mat++;
     }
     return sum;
 }
Referenced by crc32_combine_(), and gf2_matrix_square().
OF() [1/3]
uLong crc32_combine_ OF ((uLong crc1, uLong crc2, z_off64_t len2))
OF() [2/3]
unsigned long gf2_matrix_times OF ((unsigned long *mat, unsigned long vec))
OF() [3/3]
void gf2_matrix_square OF ((unsigned long *square, unsigned long *mat))