Azerotcore-wotlk: src/server/game/Entities/Object/ObjectDefines.h File Reference
ObjectDefines.h File Reference
#include "Define.h"
Macros
#define CONTACT_DISTANCE 0.5f
#define INTERACTION_DISTANCE 5.5f
#define ATTACK_DISTANCE 5.0f
#define MAX_SEARCHER_DISTANCE 150.0f
#define MAX_VISIBILITY_DISTANCE 250.0f
#define VISIBILITY_INC_FOR_GOBJECTS 30.0f
#define VISIBILITY_COMPENSATION 15.0f
#define SPELL_SEARCHER_COMPENSATION 30.0f
#define VISIBILITY_DIST_WINTERGRASP 175.0f
#define SIGHT_RANGE_UNIT 50.0f
#define DEFAULT_VISIBILITY_DISTANCE 90.0f
#define DEFAULT_VISIBILITY_INSTANCE 120.0f
#define DEFAULT_VISIBILITY_BGARENAS 150.0f
#define DEFAULT_WORLD_OBJECT_SIZE 0.388999998569489f
#define DEFAULT_COMBAT_REACH 1.5f
#define MIN_MELEE_REACH 2.0f
#define NOMINAL_MELEE_RANGE 5.0f
#define MELEE_RANGE (NOMINAL_MELEE_RANGE - MIN_MELEE_REACH * 2)
#define DEFAULT_COLLISION_HEIGHT 2.03128f
Functions
uint32 PAIR64_HIPART (uint64 x)
uint32 PAIR64_LOPART (uint64 x)
uint16 MAKE_PAIR16 (uint8 l, uint8 h)
uint32 MAKE_PAIR32 (uint16 l, uint16 h)
uint16 PAIR32_HIPART (uint32 x)
uint16 PAIR32_LOPART (uint32 x)
Macro Definition Documentation
ATTACK_DISTANCE
#define ATTACK_DISTANCE 5.0f
Definition at line 25 of file ObjectDefines.h.
CONTACT_DISTANCE
#define CONTACT_DISTANCE 0.5f
Definition at line 23 of file ObjectDefines.h.
DEFAULT_COLLISION_HEIGHT
#define DEFAULT_COLLISION_HEIGHT 2.03128f
Definition at line 42 of file ObjectDefines.h.
DEFAULT_COMBAT_REACH
#define DEFAULT_COMBAT_REACH 1.5f
Definition at line 38 of file ObjectDefines.h.
DEFAULT_VISIBILITY_BGARENAS
#define DEFAULT_VISIBILITY_BGARENAS 150.0f
Definition at line 35 of file ObjectDefines.h.
DEFAULT_VISIBILITY_DISTANCE
#define DEFAULT_VISIBILITY_DISTANCE 90.0f
Definition at line 33 of file ObjectDefines.h.
DEFAULT_VISIBILITY_INSTANCE
#define DEFAULT_VISIBILITY_INSTANCE 120.0f
Definition at line 34 of file ObjectDefines.h.
DEFAULT_WORLD_OBJECT_SIZE
#define DEFAULT_WORLD_OBJECT_SIZE 0.388999998569489f
Definition at line 37 of file ObjectDefines.h.
INTERACTION_DISTANCE
#define INTERACTION_DISTANCE 5.5f
Definition at line 24 of file ObjectDefines.h.
MAX_SEARCHER_DISTANCE
#define MAX_SEARCHER_DISTANCE 150.0f
Definition at line 26 of file ObjectDefines.h.
MAX_VISIBILITY_DISTANCE
#define MAX_VISIBILITY_DISTANCE 250.0f
Definition at line 27 of file ObjectDefines.h.
MELEE_RANGE
#define MELEE_RANGE (NOMINAL_MELEE_RANGE - MIN_MELEE_REACH * 2)
Definition at line 41 of file ObjectDefines.h.
MIN_MELEE_REACH
#define MIN_MELEE_REACH 2.0f
Definition at line 39 of file ObjectDefines.h.
NOMINAL_MELEE_RANGE
#define NOMINAL_MELEE_RANGE 5.0f
Definition at line 40 of file ObjectDefines.h.
SIGHT_RANGE_UNIT
#define SIGHT_RANGE_UNIT 50.0f
Definition at line 32 of file ObjectDefines.h.
SPELL_SEARCHER_COMPENSATION
#define SPELL_SEARCHER_COMPENSATION 30.0f
Definition at line 30 of file ObjectDefines.h.
VISIBILITY_COMPENSATION
#define VISIBILITY_COMPENSATION 15.0f
Definition at line 29 of file ObjectDefines.h.
VISIBILITY_DIST_WINTERGRASP
#define VISIBILITY_DIST_WINTERGRASP 175.0f
Definition at line 31 of file ObjectDefines.h.
VISIBILITY_INC_FOR_GOBJECTS
#define VISIBILITY_INC_FOR_GOBJECTS 30.0f
Definition at line 28 of file ObjectDefines.h.
Function Documentation
MAKE_PAIR16()
uint16 MAKE_PAIR16 (uint8 l, uint8 h) inline
Definition at line 62 of file ObjectDefines.h.
 {
     return uint16(l | (uint16(h) << 8));
 }
References mpq::l.
Referenced by ObjectMgr::GetCreatureBaseStats(), and ObjectMgr::LoadCreatureClassLevelStats().
MAKE_PAIR32()
uint32 MAKE_PAIR32 (uint16 l, uint16 h) inline
Definition at line 67 of file ObjectDefines.h.
 {
     return uint32(l | (uint32(h) << 16));
 }
References mpq::l.
Referenced by Player::_LoadSkills(), ObjectMgr::AddCreatureToGrid(), ObjectMgr::AddGameobjectToGrid(), GossipMenu::AddMenuItem(), ObjectMgr::GetCellObjectGuids(), ObjectMgr::GetDungeonEncounterList(), InstanceSaveMgr::GetExtendedResetTimeFor(), GetMapDifficultyData(), ObjectMgr::GetMapObjectGuids(), InstanceSaveMgr::GetResetTimeFor(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadInstanceEncounters(), Player::PrepareGossipMenu(), ObjectMgr::RemoveCreatureFromGrid(), ObjectMgr::RemoveGameobjectFromGrid(), InstanceSaveMgr::SetExtendedResetTimeFor(), InstanceSaveMgr::SetResetTimeFor(), Player::SetSkill(), and Player::UpdateHonorFields().
PAIR32_HIPART()
uint16 PAIR32_HIPART (uint32 x) inline
Definition at line 72 of file ObjectDefines.h.
 {
     return (uint16)((x >> 16) & 0x0000FFFF);
 }
References G3D::x.
Referenced by Player::GetSkillStep(), WorldSession::HandleCalendarGetCalendar(), and InstanceSaveMgr::LoadResetTimes().
PAIR32_LOPART()
uint16 PAIR32_LOPART (uint32 x) inline
Definition at line 77 of file ObjectDefines.h.
 {
     return (uint16)(x & 0x0000FFFF);
 }
References G3D::x.
Referenced by WorldSession::HandleCalendarGetCalendar(), InstanceSaveMgr::LoadResetTimes(), and Player::UpdateHonorFields().
PAIR64_HIPART()
uint32 PAIR64_HIPART (uint64 x) inline
Definition at line 52 of file ObjectDefines.h.
 {
     return (uint32)((x >> 32) & UI64LIT(0x00000000FFFFFFFF));
 }
References UI64LIT, and G3D::x.
Referenced by Object::SetUInt64Value().
PAIR64_LOPART()
uint32 PAIR64_LOPART (uint64 x) inline
Definition at line 57 of file ObjectDefines.h.
 {
     return (uint32)(x & UI64LIT(0x00000000FFFFFFFF));
 }
References UI64LIT, and G3D::x.
Referenced by Object::SetUInt64Value().