Azerotcore-wotlk: BattlegroundQueue::SelectionPool Class Reference
BattlegroundQueue::SelectionPool Class Reference
#include <BattlegroundQueue.h>
Public Member Functions
SelectionPool ()
void Init ()
bool AddGroup (GroupQueueInfo *ginfo, uint32 desiredCount)
bool KickGroup (uint32 size)
uint32 GetPlayerCount () const
Public Attributes
GroupsQueueType SelectedGroups
Private Attributes
uint32 PlayerCount
Detailed Description
Definition at line 113 of file BattlegroundQueue.h.
Constructor & Destructor Documentation
SelectionPool()
BattlegroundQueue::SelectionPool::SelectionPool () inline
Definition at line 116 of file BattlegroundQueue.h.
 : PlayerCount(0) {};
Member Function Documentation
AddGroup()
bool BattlegroundQueue::SelectionPool::AddGroup (GroupQueueInfo * ginfo, uint32 desiredCount)
Definition at line 113 of file BattlegroundQueue.cpp.
 {
     // add if we don't exceed desiredCount
     if (!ginfo->IsInvitedToBGInstanceGUID && desiredCount >= PlayerCount + ginfo->Players.size())
     {
         SelectedGroups.push_back(ginfo);
         PlayerCount += ginfo->Players.size();
         return true;
     }
     return PlayerCount < desiredCount;
 }
References GroupQueueInfo::IsInvitedToBGInstanceGUID, and GroupQueueInfo::Players.
Referenced by BattlegroundQueue::CheckPremadeMatch().
GetPlayerCount()
uint32 BattlegroundQueue::SelectionPool::GetPlayerCount () const inline
Definition at line 120 of file BattlegroundQueue.h.
 { return PlayerCount; }
References PlayerCount.
Referenced by BattlegroundQueue::CheckNormalMatch(), BattlegroundQueue::CheckPremadeMatch(), BattlegroundQueue::FillPlayersToBG(), and BattlegroundQueue::FillPlayersToBGWithSpecific().
Init()
void BattlegroundQueue::SelectionPool::Init ()
Definition at line 74 of file BattlegroundQueue.cpp.
 {
     SelectedGroups.clear();
     PlayerCount = 0;
 }
References PlayerCount, and SelectedGroups.
Referenced by BattlegroundQueue::CheckPremadeMatch(), BattlegroundQueue::CheckSkirmishForSameFaction(), BattlegroundQueue::FillPlayersToBG(), and BattlegroundQueue::FillPlayersToBGWithSpecific().
KickGroup()
bool BattlegroundQueue::SelectionPool::KickGroup (uint32 size)
Definition at line 81 of file BattlegroundQueue.cpp.
 {
     if (SelectedGroups.empty())
         return false;
     // find last group with proper size or largest
     bool foundProper = false;
     auto groupToKick = SelectedGroups.begin();
     for (auto itr = groupToKick; itr != SelectedGroups.end(); ++itr)
     {
         // if proper size - overwrite to kick last one
         if (abs(int32((*itr)->Players.size()) - (int32)size) <= 1)
         {
             groupToKick = itr;
             foundProper = true;
         }
         else if (!foundProper && (*itr)->Players.size() >= (*groupToKick)->Players.size())
             groupToKick = itr;
     }
     // remove selected from pool
     GroupQueueInfo* ginfo = (*groupToKick);
     SelectedGroups.erase(groupToKick);
     PlayerCount -= ginfo->Players.size();
     if (foundProper)
         return false;
     return (ginfo->Players.size() > size);
 }
References GroupQueueInfo::Players.
Member Data Documentation
PlayerCount
uint32 BattlegroundQueue::SelectionPool::PlayerCount private
Definition at line 124 of file BattlegroundQueue.h.
Referenced by GetPlayerCount(), and Init().
SelectedGroups
GroupsQueueType BattlegroundQueue::SelectionPool::SelectedGroups
Definition at line 122 of file BattlegroundQueue.h.
Referenced by BattlegroundQueue::CheckSkirmishForSameFaction(), and Init().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/BattlegroundQueue.h
src/server/game/Battlegrounds/BattlegroundQueue.cpp