Azerotcore-wotlk: Acore::XP Namespace Reference
Acore::XP Namespace Reference
Functions
uint8 GetGrayLevel (uint8 pl_level)
XPColorChar GetColorCode (uint8 pl_level, uint8 mob_level)
uint8 GetZeroDifference (uint8 pl_level)
uint32 BaseGain (uint8 pl_level, uint8 mob_level, ContentLevels content)
uint32 Gain (Player *player, Unit *unit, bool isBattleGround=false)
float xp_in_group_rate (uint32 count, bool isRaid)
Function Documentation
BaseGain()
uint32 Acore::XP::BaseGain (uint8 pl_level, uint8 mob_level, ContentLevels content)
Definition at line 24 of file Formulas.cpp.
 {
     uint32 baseGain;
     uint32 nBaseExp;
     switch (content)
     {
     case CONTENT_1_60:
         nBaseExp = 45;
         break;
     case CONTENT_61_70:
         nBaseExp = 235;
         break;
     case CONTENT_71_80:
         nBaseExp = 580;
         break;
     default:
         LOG_ERROR("misc", "BaseGain: Unsupported content level %u", content);
         nBaseExp = 45;
         break;
     }
     if (mob_level >= pl_level)
     {
         uint8 nLevelDiff = mob_level - pl_level;
         if (nLevelDiff > 4)
             nLevelDiff = 4;
         baseGain = ((pl_level * 5 + nBaseExp) * (20 + nLevelDiff) / 10 + 1) / 2;
     }
     else
     {
         uint8 gray_level = GetGrayLevel(pl_level);
         if (mob_level > gray_level)
         {
             uint8 ZD = GetZeroDifference(pl_level);
             baseGain = (pl_level * 5 + nBaseExp) * (ZD + mob_level - pl_level) / ZD;
         }
         else
             baseGain = 0;
     }
     //sScriptMgr->OnBaseGainCalculation(baseGain, pl_level, mob_level, content); // pussywizard: optimization
     return baseGain;
 }
References CONTENT_1_60, CONTENT_61_70, CONTENT_71_80, GetGrayLevel(), GetZeroDifference(), LOG_ERROR, and ZD.
Referenced by Gain(), and TEST().
Gain()
uint32 Acore::XP::Gain (Player * player, Unit * unit, bool isBattleGround = false)
Definition at line 70 of file Formulas.cpp.
 {
     Creature* creature = unit->ToCreature();
     uint32 gain = 0;
     if (!creature || (!creature->IsTotem() && !creature->IsPet() && !creature->IsCritter() &&
         !(creature->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_NO_XP)))
     {
         float xpMod = 1.0f;
         gain = BaseGain(player->getLevel(), unit->getLevel(), GetContentLevelsForMapAndZone(unit->GetMapId(), unit->GetZoneId()));
         if (gain && creature)
         {
             if (creature->isElite())
             {
                 // Elites in instances have a 2.75x XP bonus instead of the regular 2x world bonus.
                 if (unit->GetMap() && unit->GetMap()->IsDungeon())
                     xpMod *= 2.75f;
                 else
                     xpMod *= 2.0f;
             }
             xpMod *= creature->GetCreatureTemplate()->ModExperience;
         }
         xpMod *= isBattleGround ? sWorld->getRate(RATE_XP_BG_KILL) : sWorld->getRate(RATE_XP_KILL);
         // if players dealt less than 50% of the damage and were credited anyway (due to CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ), scale XP gained appropriately (linear scaling)
         if (creature && creature->m_PlayerDamageReq)
         {
             xpMod *= 1.0f - 2.0f * creature->m_PlayerDamageReq / creature->GetMaxHealth();
         }
         gain = uint32(gain * xpMod);
     }
     //sScriptMgr->OnGainCalculation(gain, player, u); // pussywizard: optimization
     return gain;
 }
References BaseGain(), CREATURE_FLAG_EXTRA_NO_XP, CreatureTemplate::flags_extra, GetContentLevelsForMapAndZone(), Creature::GetCreatureTemplate(), Unit::getLevel(), WorldObject::GetMap(), WorldLocation::GetMapId(), Unit::GetMaxHealth(), WorldObject::GetZoneId(), Unit::IsCritter(), Map::IsDungeon(), Creature::isElite(), Unit::IsPet(), Unit::IsTotem(), Creature::m_PlayerDamageReq, CreatureTemplate::ModExperience, RATE_XP_BG_KILL, RATE_XP_KILL, sWorld, and Object::ToCreature().
Referenced by KillRewarder::_InitXP().
GetColorCode()
XPColorChar Acore::XP::GetColorCode (uint8 pl_level, uint8 mob_level) inline
Definition at line 58 of file Formulas.h.
     {
         XPColorChar color;
         if (mob_level >= pl_level + 5)
             color = XP_RED;
         else if (mob_level >= pl_level + 3)
             color = XP_ORANGE;
         else if (mob_level >= pl_level - 2)
             color = XP_YELLOW;
         else if (mob_level > GetGrayLevel(pl_level))
             color = XP_GREEN;
         else
             color = XP_GRAY;
         //sScriptMgr->OnColorCodeCalculation(color, pl_level, mob_level); // pussywizard: optimization
         return color;
     }
References GetGrayLevel(), XP_GRAY, XP_GREEN, XP_ORANGE, XP_RED, and XP_YELLOW.
Referenced by TEST().
GetGrayLevel()
uint8 Acore::XP::GetGrayLevel (uint8 pl_level) inline
Definition at line 41 of file Formulas.h.
     {
         uint8 level;
         if (pl_level <= 5)
             level = 0;
         else if (pl_level <= 39)
             level = pl_level - 5 - pl_level / 10;
         else if (pl_level <= 59)
             level = pl_level - 1 - pl_level / 5;
         else
             level = pl_level - 9;
         //sScriptMgr->OnGrayLevelCalculation(level, pl_level); // pussywizard: optimization
         return level;
     }
Referenced by KillRewarder::_InitGroupData(), BaseGain(), Player::CalculateReputationGain(), GetColorCode(), Player::isHonorOrXPTarget(), Player::RewardHonor(), TEST(), and Player::UpdateCombatSkills().
GetZeroDifference()
uint8 Acore::XP::GetZeroDifference (uint8 pl_level) inline
Definition at line 77 of file Formulas.h.
     {
         uint8 diff;
         if (pl_level < 8)
             diff = 5;
         else if (pl_level < 10)
             diff = 6;
         else if (pl_level < 12)
             diff = 7;
         else if (pl_level < 16)
             diff = 8;
         else if (pl_level < 20)
             diff = 9;
         else if (pl_level < 30)
             diff = 11;
         else if (pl_level < 40)
             diff = 12;
         else if (pl_level < 45)
             diff = 13;
         else if (pl_level < 50)
             diff = 14;
         else if (pl_level < 55)
             diff = 15;
         else if (pl_level < 60)
             diff = 16;
         else
             diff = 17;
         //sScriptMgr->OnZeroDifferenceCalculation(diff, pl_level); // pussywizard: optimization
         return diff;
     }
References diff().
Referenced by BaseGain(), and TEST().
xp_in_group_rate()
float Acore::XP::xp_in_group_rate (uint32 count, bool isRaid) inline
Definition at line 114 of file Formulas.h.
     {
         float rate;
         if (isRaid)
         {
             // FIXME: Must apply decrease modifiers depending on raid size.
             rate = 1.0f;
         }
         else
         {
             switch (count)
             {
             case 0:
             case 1:
             case 2:
                 rate = 1.0f;
                 break;
             case 3:
                 rate = 1.166f;
                 break;
             case 4:
                 rate = 1.3f;
                 break;
             case 5:
             default:
                 rate = 1.4f;
             }
         }
         //sScriptMgr->OnGroupRateCalculation(rate, count, isRaid); // pussywizard: optimization
         return rate;
     }
References count().
Referenced by KillRewarder::_RewardGroup().