Azerotcore-wotlk: reset_commandscript Class Reference
reset_commandscript Class Reference
Public Member Functions
reset_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleResetAchievementsCommand (ChatHandler *handler, char const *args)
static bool HandleResetHonorCommand (ChatHandler *handler, char const *args)
static bool HandleResetStatsOrLevelHelper (Player *player)
static bool HandleResetLevelCommand (ChatHandler *handler, char const *args)
static bool HandleResetSpellsCommand (ChatHandler *handler, char const *args)
static bool HandleResetStatsCommand (ChatHandler *handler, char const *args)
static bool HandleResetTalentsCommand (ChatHandler *handler, char const *args)
static bool HandleResetAllCommand (ChatHandler *handler, char const *args)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 39 of file cs_reset.cpp.
Constructor & Destructor Documentation
reset_commandscript()
reset_commandscript::reset_commandscript () inline
Definition at line 42 of file cs_reset.cpp.
 : CommandScript("reset_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable reset_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 44 of file cs_reset.cpp.
     {
         static ChatCommandTable resetCommandTable =
         {
             { "achievements",   SEC_CONSOLE,        true,  &HandleResetAchievementsCommand,     "" },
             { "honor",          SEC_ADMINISTRATOR,  true,  &HandleResetHonorCommand,            "" },
             { "level",          SEC_ADMINISTRATOR,  true,  &HandleResetLevelCommand,            "" },
             { "spells",         SEC_ADMINISTRATOR,  true,  &HandleResetSpellsCommand,           "" },
             { "stats",          SEC_ADMINISTRATOR,  true,  &HandleResetStatsCommand,            "" },
             { "talents",        SEC_ADMINISTRATOR,  true,  &HandleResetTalentsCommand,          "" },
             { "all",            SEC_CONSOLE,        true,  &HandleResetAllCommand,              "" }
         };
         static ChatCommandTable commandTable =
         {
             { "reset",          SEC_ADMINISTRATOR,  true, nullptr,                              "", resetCommandTable }
         };
         return commandTable;
     }
References SEC_ADMINISTRATOR, and SEC_CONSOLE.
HandleResetAchievementsCommand()
static bool reset_commandscript::HandleResetAchievementsCommand (ChatHandler * handler, char const * args) inline static
Definition at line 63 of file cs_reset.cpp.
     {
         Player* target;
         ObjectGuid targetGuid;
         if (!handler->extractPlayerTarget((char*)args, &target, &targetGuid))
             return false;
         if (target)
             target->ResetAchievements();
         else
             AchievementMgr::DeleteFromDB(targetGuid.GetCounter());
         return true;
     }
References AchievementMgr::DeleteFromDB(), ChatHandler::extractPlayerTarget(), ObjectGuid::GetCounter(), and Player::ResetAchievements().
HandleResetAllCommand()
static bool reset_commandscript::HandleResetAllCommand (ChatHandler * handler, char const * args) inline static
Definition at line 269 of file cs_reset.cpp.
     {
         if (!*args)
             return false;
         std::string caseName = args;
         AtLoginFlags atLogin;
         // Command specially created as single command to prevent using short case names
         if (caseName == "spells")
         {
             atLogin = AT_LOGIN_RESET_SPELLS;
             sWorld->SendWorldText(LANG_RESETALL_SPELLS);
             if (!handler->GetSession())
                 handler->SendSysMessage(LANG_RESETALL_SPELLS);
         }
         else if (caseName == "talents")
         {
             atLogin = AtLoginFlags(AT_LOGIN_RESET_TALENTS | AT_LOGIN_RESET_PET_TALENTS);
             sWorld->SendWorldText(LANG_RESETALL_TALENTS);
             if (!handler->GetSession())
                 handler->SendSysMessage(LANG_RESETALL_TALENTS);
         }
         else
         {
             handler->PSendSysMessage(LANG_RESETALL_UNKNOWN_CASE, args);
             handler->SetSentErrorMessage(true);
             return false;
         }
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ALL_AT_LOGIN_FLAGS);
         stmt->setUInt16(0, uint16(atLogin));
         CharacterDatabase.Execute(stmt);
         std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
         HashMapHolder<Player>::MapType const& plist = ObjectAccessor::GetPlayers();
         for (HashMapHolder<Player>::MapType::const_iterator itr = plist.begin(); itr != plist.end(); ++itr)
             itr->second->SetAtLoginFlag(atLogin);
         return true;
     }
References AT_LOGIN_RESET_PET_TALENTS, AT_LOGIN_RESET_SPELLS, AT_LOGIN_RESET_TALENTS, CHAR_UPD_ALL_AT_LOGIN_FLAGS, CharacterDatabase, ObjectAccessor::GetPlayers(), ChatHandler::GetSession(), LANG_RESETALL_SPELLS, LANG_RESETALL_TALENTS, LANG_RESETALL_UNKNOWN_CASE, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt16(), and sWorld.
HandleResetHonorCommand()
static bool reset_commandscript::HandleResetHonorCommand (ChatHandler * handler, char const * args) inline static
Definition at line 78 of file cs_reset.cpp.
     {
         Player* target;
         if (!handler->extractPlayerTarget((char*)args, &target))
             return false;
         target->SetHonorPoints(0);
         target->SetUInt32Value(PLAYER_FIELD_KILLS, 0);
         target->SetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, 0);
         target->SetUInt32Value(PLAYER_FIELD_TODAY_CONTRIBUTION, 0);
         target->SetUInt32Value(PLAYER_FIELD_YESTERDAY_CONTRIBUTION, 0);
         target->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL);
         return true;
     }
References ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ChatHandler::extractPlayerTarget(), PLAYER_FIELD_KILLS, PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, PLAYER_FIELD_TODAY_CONTRIBUTION, PLAYER_FIELD_YESTERDAY_CONTRIBUTION, Player::SetHonorPoints(), Object::SetUInt32Value(), and Player::UpdateAchievementCriteria().
HandleResetLevelCommand()
static bool reset_commandscript::HandleResetLevelCommand (ChatHandler * handler, char const * args) inline static
Definition at line 126 of file cs_reset.cpp.
     {
         Player* target;
         if (!handler->extractPlayerTarget((char*)args, &target))
             return false;
         if (!HandleResetStatsOrLevelHelper(target))
             return false;
         uint8 oldLevel = target->getLevel();
         // set starting level
         uint32 startLevel = target->getClass() != CLASS_DEATH_KNIGHT
                             ? sWorld->getIntConfig(CONFIG_START_PLAYER_LEVEL)
                             : sWorld->getIntConfig(CONFIG_START_HEROIC_PLAYER_LEVEL);
         target->_ApplyAllLevelScaleItemMods(false);
         target->SetLevel(startLevel);
         target->InitRunes();
         target->InitStatsForLevel(true);
         target->InitTaxiNodesForLevel();
         target->InitGlyphsForLevel();
         target->InitTalentForLevel();
         target->SetUInt32Value(PLAYER_XP, 0);
         target->_ApplyAllLevelScaleItemMods(true);
         // reset level for pet
         if (Pet* pet = target->GetPet())
             pet->SynchronizeLevelWithOwner();
         sScriptMgr->OnPlayerLevelChanged(target, oldLevel);
         return true;
     }
References Player::_ApplyAllLevelScaleItemMods(), CLASS_DEATH_KNIGHT, CONFIG_START_HEROIC_PLAYER_LEVEL, CONFIG_START_PLAYER_LEVEL, ChatHandler::extractPlayerTarget(), Unit::getClass(), Unit::getLevel(), Player::GetPet(), Player::InitGlyphsForLevel(), Player::InitRunes(), Player::InitStatsForLevel(), Player::InitTalentForLevel(), Player::InitTaxiNodesForLevel(), PLAYER_XP, Unit::SetLevel(), Object::SetUInt32Value(), sScriptMgr, and sWorld.
HandleResetSpellsCommand()
static bool reset_commandscript::HandleResetSpellsCommand (ChatHandler * handler, char const * args) inline static
Definition at line 162 of file cs_reset.cpp.
     {
         Player* target;
         ObjectGuid targetGuid;
         std::string targetName;
         if (!handler->extractPlayerTarget((char*)args, &target, &targetGuid, &targetName))
             return false;
         if (target)
         {
             target->resetSpells(/* bool myClassOnly */);
             ChatHandler(target->GetSession()).SendSysMessage(LANG_RESET_SPELLS);
             if (!handler->GetSession() || handler->GetSession()->GetPlayer() != target)
                 handler->PSendSysMessage(LANG_RESET_SPELLS_ONLINE, handler->GetNameLink(target).c_str());
         }
         else
         {
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ADD_AT_LOGIN_FLAG);
             stmt->setUInt16(0, uint16(AT_LOGIN_RESET_SPELLS));
             stmt->setUInt32(1, targetGuid.GetCounter());
             CharacterDatabase.Execute(stmt);
             handler->PSendSysMessage(LANG_RESET_SPELLS_OFFLINE, targetName.c_str());
         }
         return true;
     }
References AT_LOGIN_RESET_SPELLS, CHAR_UPD_ADD_AT_LOGIN_FLAG, CharacterDatabase, ChatHandler::extractPlayerTarget(), ObjectGuid::GetCounter(), ChatHandler::GetNameLink(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Player::GetSession(), LANG_RESET_SPELLS, LANG_RESET_SPELLS_OFFLINE, LANG_RESET_SPELLS_ONLINE, ChatHandler::PSendSysMessage(), Player::resetSpells(), ChatHandler::SendSysMessage(), PreparedStatementBase::setUInt16(), and PreparedStatementBase::setUInt32().
HandleResetStatsCommand()
static bool reset_commandscript::HandleResetStatsCommand (ChatHandler * handler, char const * args) inline static
Definition at line 191 of file cs_reset.cpp.
     {
         Player* target;
         if (!handler->extractPlayerTarget((char*)args, &target))
             return false;
         if (!HandleResetStatsOrLevelHelper(target))
             return false;
         target->InitRunes();
         target->InitStatsForLevel(true);
         target->InitTaxiNodesForLevel();
         target->InitGlyphsForLevel();
         target->InitTalentForLevel();
         return true;
     }
References ChatHandler::extractPlayerTarget(), Player::InitGlyphsForLevel(), Player::InitRunes(), Player::InitStatsForLevel(), Player::InitTalentForLevel(), and Player::InitTaxiNodesForLevel().
HandleResetStatsOrLevelHelper()
static bool reset_commandscript::HandleResetStatsOrLevelHelper (Player * player) inline static
Definition at line 94 of file cs_reset.cpp.
     {
         ChrClassesEntry const* classEntry = sChrClassesStore.LookupEntry(player->getClass());
         if (!classEntry)
         {
             LOG_ERROR("dbc", "Class %u not found in DBC (Wrong DBC files?)", player->getClass());
             return false;
         }
         uint8 powerType = classEntry->powerType;
         // reset m_form if no aura
         if (!player->HasAuraType(SPELL_AURA_MOD_SHAPESHIFT))
             player->SetShapeshiftForm(FORM_NONE);
         player->SetFactionForRace(player->getRace());
         player->SetUInt32Value(UNIT_FIELD_BYTES_0, ((player->getRace()) | (player->getClass() << 8) | (player->getGender() << 16) | (powerType << 24)));
         // reset only if player not in some form;
         if (player->GetShapeshiftForm() == FORM_NONE)
             player->InitDisplayIds();
         player->SetByteValue(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_PVP);
         player->SetUInt32Value(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
         //-1 is default value
         player->SetUInt32Value(PLAYER_FIELD_WATCHED_FACTION_INDEX, uint32(-1));
         return true;
     }
References FORM_NONE, Unit::getClass(), Unit::getGender(), Unit::getRace(), Unit::GetShapeshiftForm(), Unit::HasAuraType(), Player::InitDisplayIds(), LOG_ERROR, PLAYER_FIELD_WATCHED_FACTION_INDEX, ChrClassesEntry::powerType, sChrClassesStore, Object::SetByteValue(), Player::SetFactionForRace(), Unit::SetShapeshiftForm(), Object::SetUInt32Value(), SPELL_AURA_MOD_SHAPESHIFT, UNIT_BYTE2_FLAG_PVP, UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
HandleResetTalentsCommand()
static bool reset_commandscript::HandleResetTalentsCommand (ChatHandler * handler, char const * args) inline static
Definition at line 209 of file cs_reset.cpp.
     {
         Player* target;
         ObjectGuid targetGuid;
         std::string targetName;
         if (!handler->extractPlayerTarget((char*)args, &target, &targetGuid, &targetName))
         {
             // Try reset talents as Hunter Pet
             Creature* creature = handler->getSelectedCreature();
             if (!*args && creature && creature->IsPet())
             {
                 Unit* owner = creature->GetOwner();
                 if (owner && owner->GetTypeId() == TYPEID_PLAYER && creature->ToPet()->IsPermanentPetFor(owner->ToPlayer()))
                 {
                     creature->ToPet()->resetTalents();
                     owner->ToPlayer()->SendTalentsInfoData(true);
                     ChatHandler(owner->ToPlayer()->GetSession()).SendSysMessage(LANG_RESET_PET_TALENTS);
                     if (!handler->GetSession() || handler->GetSession()->GetPlayer() != owner->ToPlayer())
                         handler->PSendSysMessage(LANG_RESET_PET_TALENTS_ONLINE, handler->GetNameLink(owner->ToPlayer()).c_str());
                 }
                 return true;
             }
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (target)
         {
             target->resetTalents(true);
             target->SendTalentsInfoData(false);
             ChatHandler(target->GetSession()).SendSysMessage(LANG_RESET_TALENTS);
             if (!handler->GetSession() || handler->GetSession()->GetPlayer() != target)
                 handler->PSendSysMessage(LANG_RESET_TALENTS_ONLINE, handler->GetNameLink(target).c_str());
             Pet* pet = target->GetPet();
             Pet::resetTalentsForAllPetsOf(target, pet);
             if (pet)
                 target->SendTalentsInfoData(true);
             return true;
         }
         else if (targetGuid)
         {
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_ADD_AT_LOGIN_FLAG);
             stmt->setUInt16(0, uint16(AT_LOGIN_NONE | AT_LOGIN_RESET_PET_TALENTS));
             stmt->setUInt32(1, targetGuid.GetCounter());
             CharacterDatabase.Execute(stmt);
             std::string nameLink = handler->playerLink(targetName);
             handler->PSendSysMessage(LANG_RESET_TALENTS_OFFLINE, nameLink.c_str());
             return true;
         }
         handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
         handler->SetSentErrorMessage(true);
         return false;
     }
References AT_LOGIN_NONE, AT_LOGIN_RESET_PET_TALENTS, CHAR_UPD_ADD_AT_LOGIN_FLAG, CharacterDatabase, ChatHandler::extractPlayerTarget(), ObjectGuid::GetCounter(), ChatHandler::GetNameLink(), Unit::GetOwner(), Player::GetPet(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), Player::GetSession(), Object::GetTypeId(), Pet::IsPermanentPetFor(), Unit::IsPet(), LANG_NO_CHAR_SELECTED, LANG_RESET_PET_TALENTS, LANG_RESET_PET_TALENTS_ONLINE, LANG_RESET_TALENTS, LANG_RESET_TALENTS_OFFLINE, LANG_RESET_TALENTS_ONLINE, ChatHandler::playerLink(), ChatHandler::PSendSysMessage(), Pet::resetTalents(), Player::resetTalents(), Pet::resetTalentsForAllPetsOf(), ChatHandler::SendSysMessage(), Player::SendTalentsInfoData(), ChatHandler::SetSentErrorMessage(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), Unit::ToPet(), Object::ToPlayer(), and TYPEID_PLAYER.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_reset.cpp