Azerotcore-wotlk: boss_emeriss::boss_emerissAI Struct Reference
boss_emeriss::boss_emerissAI Struct Reference
Public Member Functions
boss_emerissAI (Creature *creature)
void Reset () override
void KilledUnit (Unit *who) override
void EnterCombat (Unit *who) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void ExecuteEvent (uint32 eventId) override
Public Member Functions inherited from emerald_dragonAI
emerald_dragonAI (Creature *creature)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from WorldBossAI
WorldBossAI (Creature *creature)
~WorldBossAI () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint8 _stage
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from WorldBossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from WorldBossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 459 of file boss_emerald_dragons.cpp.
Constructor & Destructor Documentation
boss_emerissAI()
boss_emeriss::boss_emerissAI::boss_emerissAI (Creature * creature) inline
Definition at line 461 of file boss_emerald_dragons.cpp.
                                            : emerald_dragonAI(creature)
         {
         }
Member Function Documentation
DamageTaken()
void boss_emeriss::boss_emerissAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 485 of file boss_emerald_dragons.cpp.
         {
             if (!HealthAbovePct(100 - 25 * _stage))
             {
                 Talk(SAY_EMERISS_CAST_CORRUPTION);
                 DoCast(me, SPELL_CORRUPTION_OF_EARTH, true);
                 ++_stage;
             }
         }
References _stage, UnitAI::DoCast(), ScriptedAI::HealthAbovePct(), ScriptedAI::me, SAY_EMERISS_CAST_CORRUPTION, SPELL_CORRUPTION_OF_EARTH, and CreatureAI::Talk().
EnterCombat()
void boss_emeriss::boss_emerissAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from WorldBossAI.
Definition at line 479 of file boss_emerald_dragons.cpp.
         {
             Talk(SAY_EMERISS_AGGRO);
             WorldBossAI::EnterCombat(who);
         }
References WorldBossAI::EnterCombat(), SAY_EMERISS_AGGRO, and CreatureAI::Talk().
ExecuteEvent()
void boss_emeriss::boss_emerissAI::ExecuteEvent (uint32 eventId) inline override virtual
Reimplemented from emerald_dragonAI.
Definition at line 495 of file boss_emerald_dragons.cpp.
         {
             switch (eventId)
             {
                 case EVENT_VOLATILE_INFECTION:
                     DoCastVictim(SPELL_VOLATILE_INFECTION);
                     events.ScheduleEvent(EVENT_VOLATILE_INFECTION, 120000);
                     break;
                 default:
                     emerald_dragonAI::ExecuteEvent(eventId);
                     break;
             }
         }
References UnitAI::DoCastVictim(), EVENT_VOLATILE_INFECTION, emerald_dragonAI::ExecuteEvent(), and SPELL_VOLATILE_INFECTION.
KilledUnit()
void boss_emeriss::boss_emerissAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from emerald_dragonAI.
Definition at line 472 of file boss_emerald_dragons.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER)
                 DoCast(who, SPELL_PUTRID_MUSHROOM, true);
             emerald_dragonAI::KilledUnit(who);
         }
References UnitAI::DoCast(), Object::GetTypeId(), emerald_dragonAI::KilledUnit(), SPELL_PUTRID_MUSHROOM, and TYPEID_PLAYER.
Reset()
void boss_emeriss::boss_emerissAI::Reset () inline override virtual
Reimplemented from emerald_dragonAI.
Definition at line 465 of file boss_emerald_dragons.cpp.
         {
             _stage = 1;
             emerald_dragonAI::Reset();
             events.ScheduleEvent(EVENT_VOLATILE_INFECTION, 12000);
         }
References _stage, EVENT_VOLATILE_INFECTION, and emerald_dragonAI::Reset().
Member Data Documentation
_stage
uint8 boss_emeriss::boss_emerissAI::_stage private
Definition at line 510 of file boss_emerald_dragons.cpp.
Referenced by DamageTaken(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/World/boss_emerald_dragons.cpp