Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/base_externs.h File Reference
base_externs.h File Reference
Functions
base_t * b0get (void)
base_t * base_new (tsdn_t *tsdn, unsigned ind, extent_hooks_t *extent_hooks)
void base_delete (tsdn_t *tsdn, base_t *base)
extent_hooks_t * base_extent_hooks_get (base_t *base)
extent_hooks_t * base_extent_hooks_set (base_t *base, extent_hooks_t *extent_hooks)
void * base_alloc (tsdn_t *tsdn, base_t *base, size_t size, size_t alignment)
extent_t * base_alloc_extent (tsdn_t *tsdn, base_t *base)
void base_stats_get (tsdn_t *tsdn, base_t *base, size_t *allocated, size_t *resident, size_t *mapped, size_t *n_thp)
void base_prefork (tsdn_t *tsdn, base_t *base)
void base_postfork_parent (tsdn_t *tsdn, base_t *base)
void base_postfork_child (tsdn_t *tsdn, base_t *base)
bool base_boot (tsdn_t *tsdn)
Variables
metadata_thp_mode_t opt_metadata_thp
const char * metadata_thp_mode_names []
Function Documentation
b0get()
base_t* b0get (void)
Definition at line 345 of file base.c.
             {
     return b0;
 }
References b0.
base_alloc()
void* base_alloc (tsdn_t * tsdn, base_t * base, size_t size, size_t alignment)
Definition at line 464 of file base.c.
{
     return base_alloc_impl(tsdn, base, size, alignment, NULL);
 }
References base_alloc_impl(), and NULL.
base_alloc_extent()
extent_t* base_alloc_extent (tsdn_t * tsdn, base_t * base)
Definition at line 469 of file base.c.
{
     size_t esn;
     extent_t *extent = base_alloc_impl(tsdn, base, sizeof(extent_t),
         CACHELINE, &esn);
     if (extent == NULL) {
         return NULL;
     }
     extent_esn_set(extent, esn);
     return extent;
 }
References base_alloc_impl(), CACHELINE, extent_esn_set(), and NULL.
base_boot()
bool base_boot (tsdn_t * tsdn)
Definition at line 511 of file base.c.
{
     b0 = base_new(tsdn, 0, (extent_hooks_t *)&extent_hooks_default);
     return (b0 == NULL);
 }
References b0, base_new(), extent_hooks_default, and NULL.
base_delete()
void base_delete (tsdn_t * tsdn, base_t * base)
Definition at line 396 of file base.c.
{
     extent_hooks_t *extent_hooks = base_extent_hooks_get(base);
     base_block_t *next = base->blocks;
     do {
         base_block_t *block = next;
         next = block->next;
         base_unmap(tsdn, extent_hooks, base_ind_get(base), block,
             block->size);
     } while (next != NULL);
 }
References base_extent_hooks_get(), base_ind_get(), base_unmap(), base_s::blocks, next(), and NULL.
base_extent_hooks_get()
extent_hooks_t* base_extent_hooks_get (base_t * base)
Definition at line 408 of file base.c.
{
     return (extent_hooks_t *)atomic_load_p(&base->extent_hooks,
         ATOMIC_ACQUIRE);
 }
References ATOMIC_ACQUIRE, and base_s::extent_hooks.
Referenced by base_delete(), base_extent_alloc(), and base_extent_hooks_set().
base_extent_hooks_set()
extent_hooks_t* base_extent_hooks_set (base_t * base, extent_hooks_t * extent_hooks)
Definition at line 414 of file base.c.
{
     extent_hooks_t *old_extent_hooks = base_extent_hooks_get(base);
     atomic_store_p(&base->extent_hooks, extent_hooks, ATOMIC_RELEASE);
     return old_extent_hooks;
 }
References ATOMIC_RELEASE, base_extent_hooks_get(), and base_s::extent_hooks.
base_new()
base_t* base_new (tsdn_t * tsdn, unsigned ind, extent_hooks_t * extent_hooks)
Definition at line 350 of file base.c.
{
     pszind_t pind_last = 0;
     size_t extent_sn_next = 0;
     base_block_t *block = base_block_alloc(tsdn, NULL, extent_hooks, ind,
         &pind_last, &extent_sn_next, sizeof(base_t), QUANTUM);
     if (block == NULL) {
         return NULL;
     }
     size_t gap_size;
     size_t base_alignment = CACHELINE;
     size_t base_size = ALIGNMENT_CEILING(sizeof(base_t), base_alignment);
     base_t *base = (base_t *)base_extent_bump_alloc_helper(&block->extent,
         &gap_size, base_size, base_alignment);
     base->ind = ind;
     atomic_store_p(&base->extent_hooks, extent_hooks, ATOMIC_RELAXED);
     if (malloc_mutex_init(&base->mtx, "base", WITNESS_RANK_BASE,
         malloc_mutex_rank_exclusive)) {
         base_unmap(tsdn, extent_hooks, ind, block, block->size);
         return NULL;
     }
     base->pind_last = pind_last;
     base->extent_sn_next = extent_sn_next;
     base->blocks = block;
     base->auto_thp_switched = false;
     for (szind_t i = 0; i < SC_NSIZES; i++) {
         extent_heap_new(&base->avail[i]);
     }
     if (config_stats) {
         base->allocated = sizeof(base_block_t);
         base->resident = PAGE_CEILING(sizeof(base_block_t));
         base->mapped = block->size;
         base->n_thp = (opt_metadata_thp == metadata_thp_always) &&
             metadata_thp_madvise() ? HUGEPAGE_CEILING(sizeof(base_block_t))
             >> LG_HUGEPAGE : 0;
         assert(base->allocated <= base->resident);
         assert(base->resident <= base->mapped);
         assert(base->n_thp << LG_HUGEPAGE <= base->mapped);
     }
     base_extent_bump_alloc_post(base, &block->extent, gap_size, base,
         base_size);
     return base;
 }
References ALIGNMENT_CEILING, base_s::allocated, assert(), ATOMIC_RELAXED, base_s::auto_thp_switched, base_s::avail, base_block_alloc(), base_extent_bump_alloc_helper(), base_extent_bump_alloc_post(), base_unmap(), base_s::blocks, CACHELINE, config_stats, extent_heap_new, base_s::extent_hooks, base_s::extent_sn_next, HUGEPAGE_CEILING, base_s::ind, malloc_mutex_init, malloc_mutex_rank_exclusive, base_s::mapped, metadata_thp_always, metadata_thp_madvise(), base_s::mtx, base_s::n_thp, NULL, opt_metadata_thp, PAGE_CEILING, base_s::pind_last, QUANTUM, base_s::resident, SC_NSIZES, and WITNESS_RANK_BASE.
Referenced by base_boot().
base_postfork_child()
void base_postfork_child (tsdn_t * tsdn, base_t * base)
Definition at line 506 of file base.c.
{
     malloc_mutex_postfork_child(tsdn, &base->mtx);
 }
References malloc_mutex_postfork_child, and base_s::mtx.
base_postfork_parent()
void base_postfork_parent (tsdn_t * tsdn, base_t * base)
Definition at line 501 of file base.c.
{
     malloc_mutex_postfork_parent(tsdn, &base->mtx);
 }
References malloc_mutex_postfork_parent, and base_s::mtx.
base_prefork()
void base_prefork (tsdn_t * tsdn, base_t * base)
Definition at line 496 of file base.c.
{
     malloc_mutex_prefork(tsdn, &base->mtx);
 }
References malloc_mutex_prefork, and base_s::mtx.
base_stats_get()
void base_stats_get (tsdn_t * tsdn, base_t * base, size_t * allocated, size_t * resident, size_t * mapped, size_t * n_thp)
Definition at line 481 of file base.c.
{
     cassert(config_stats);
     malloc_mutex_lock(tsdn, &base->mtx);
     assert(base->allocated <= base->resident);
     assert(base->resident <= base->mapped);
     *allocated = base->allocated;
     *resident = base->resident;
     *mapped = base->mapped;
     *n_thp = base->n_thp;
     malloc_mutex_unlock(tsdn, &base->mtx);
 }
References base_s::allocated, assert(), cassert(), config_stats, malloc_mutex_lock(), malloc_mutex_unlock(), base_s::mapped, base_s::mtx, base_s::n_thp, and base_s::resident.
Variable Documentation
metadata_thp_mode_names
const char* metadata_thp_mode_names[] extern
Definition at line 17 of file base.c.
opt_metadata_thp
metadata_thp_mode_t opt_metadata_thp extern
Definition at line 15 of file base.c.
Referenced by base_auto_thp_switch(), base_block_alloc(), base_extent_alloc(), base_extent_bump_alloc_post(), and base_new().