Azerotcore-wotlk: G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator Class Reference
G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator Class Reference
#include <PointHashGrid.h>
Public Member Functions
bool operator!= (const BoxIterator &other) const
bool operator== (const BoxIterator &other) const
BoxIterator & operator++ ()
BoxIterator operator++ (int)
const Value & operator* () const
const Value * operator-> () const
operator Value * () const
bool hasMore () const
bool isValid () const
Private Member Functions
void advanceCell ()
void advance ()
BoxIterator ()
BoxIterator (const ThisType *grid, bool exact, const AABox &box)
const Value & value () const
const Vector3 & position () const
BoxIterator & operator= (const BoxIterator &)
Private Attributes
bool m_isEnd
const ThisType * m_grid
Vector3int32 m_lo
Vector3int32 m_hi
bool m_exact
AABox m_box
Vector3int32 m_current
Cell * m_cell
int m_arrayIndex
const int m_epoch
Friends
class ThisType
class SphereIterator
Detailed Description
template<class Value, class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>>
class G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator
Definition at line 526 of file PointHashGrid.h.
Constructor & Destructor Documentation
BoxIterator() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator () inline private
End iterator
Definition at line 610 of file PointHashGrid.h.
 : m_isEnd(true), m_grid(NULL), m_exact(true), m_current(0,0,0), m_cell(NULL), m_arrayIndex(0), m_epoch(0) {}
BoxIterator() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator (const ThisType * grid, bool exact, const AABox & box) inline private
Begin iterator
Definition at line 613 of file PointHashGrid.h.
                                                                         :
             m_isEnd(false),
             m_grid(grid),
             m_exact(exact),
             m_box(box),
             m_current(-1, 0 ,0),
             m_cell(NULL),
             m_arrayIndex(0),
             m_epoch(grid->m_epoch) {
             m_grid->getCellCoord(box.low(), m_lo);
             m_grid->getCellCoord(box.high(), m_hi);
             // Get to the first value
             m_current = m_lo;
             // Back up one so that advancing takes us to the first
             --m_current.x;
             advance();
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::AABox::high(), G3D::AABox::low(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_current, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_grid, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_hi, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_lo.
Member Function Documentation
advance()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance () inline private
Advance to the next value
Definition at line 585 of file PointHashGrid.h.
{
             debugAssert(! m_isEnd);
             do {
                 ++m_arrayIndex;
                 bool inConstructor = (m_cell == NULL);
                 if (inConstructor || m_arrayIndex >= m_cell->size()) {
                     advanceCell();
                     m_arrayIndex = 0;
                     if (m_isEnd) {
                         // Ran out of values
                         return;
                     }
                     debugAssert(m_cell != NULL);
                 }
                 // Advance until we have a value that can be returned, either
                 // because we don't care about exactness or because it is
                 // guaranteed to be within the box.
             } while (m_exact && ! m_box.contains(position()));
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), G3D::AABox::contains(), debugAssert, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_arrayIndex, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_box, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_exact, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd, NULL, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position(), and G3D::SmallArray< T, N >::size().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++().
advanceCell()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell () inline private
Called from advance()
Definition at line 562 of file PointHashGrid.h.
{
             do {
                 ++m_current.x;
                 if (m_current.x > m_hi.x) {
                     m_current.x = m_lo.x;
                     ++m_current.y;
                     if (m_current.y > m_hi.y) {
                         m_current.y = m_lo.y;
                         ++m_current.z;
                         if (m_current.z > m_hi.z) {
                             m_isEnd = true;
                             return;
                         }
                     }
                 }
                 // Pick up the new cell
                 m_cell = m_grid->m_data.getPointer(m_current);
                 // Keep advancing if the cell does not exist
             } while ((m_cell == NULL) || (m_cell->size() == 0));
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_current, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_grid, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_hi, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_lo, NULL, and G3D::SmallArray< T, N >::size().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance().
hasMore()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::hasMore () const inline
Deprecated:
Use isValid
Definition at line 687 of file PointHashGrid.h.
{
             return ! m_isEnd;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
isValid()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::isValid () const inline
Definition at line 691 of file PointHashGrid.h.
{
             return ! m_isEnd;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance().
operator Value *()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator Value * () const inline
Definition at line 684 of file PointHashGrid.h.
 { return &value(); }
operator!=()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator!= (const BoxIterator & other) const inline
Definition at line 649 of file PointHashGrid.h.
{
             if (other.m_isEnd && m_isEnd) {
                 return false;
             } else {
                 return (m_isEnd         != other.m_isEnd) ||
                     (m_cell          != other.m_cell) ||
                     (m_arrayIndex    != other.m_arrayIndex);
             }
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_arrayIndex, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
operator*()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator* () const inline
Definition at line 682 of file PointHashGrid.h.
 { return  value(); }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value().
operator++() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> BoxIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++ () inline
Preincrement
Definition at line 664 of file PointHashGrid.h.
{
             debugAssert(! m_isEnd);
             debugAssertM(m_epoch == m_grid->m_epoch,
                          "It is illegal to mutate the HashGrid "
                          "while iterating through it.");
             advance();
             return *this;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), debugAssert, debugAssertM, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_epoch, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_grid, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
operator++() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> BoxIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++ (int) inline
Post increment (slower)
Definition at line 676 of file PointHashGrid.h.
{
             Iterator old = *this;
             ++(*this);
             return old;
         }
operator->()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value* G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator-> () const inline
Definition at line 683 of file PointHashGrid.h.
 { return &value(); }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value().
operator=()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> BoxIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator= (const BoxIterator &) private
operator==()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator== (const BoxIterator & other) const inline
Definition at line 659 of file PointHashGrid.h.
{
             return !(*this != other);
         }
position()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Vector3& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position () const inline private
Used by SphereIterator::advance()
Definition at line 639 of file PointHashGrid.h.
{
             debugAssert(! m_isEnd);
             return (*m_cell)[m_arrayIndex].position;
         }
References debugAssert, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_arrayIndex, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance().
value()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value () const inline private
Definition at line 633 of file PointHashGrid.h.
{
             debugAssert(! m_isEnd);
             return (*m_cell)[m_arrayIndex].value;
         }
References debugAssert, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_arrayIndex, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd.
Referenced by G3D::PointHashGrid< G3D::_internal::VNTi >::BoxIterator::operator G3D::_internal::VNTi *(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator*(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator->().
Friends And Related Function Documentation
SphereIterator
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> friend class SphereIterator friend
Definition at line 529 of file PointHashGrid.h.
ThisType
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> friend class ThisType friend
Definition at line 528 of file PointHashGrid.h.
Member Data Documentation
m_arrayIndex
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_arrayIndex private
Index within m_cell of the current value
Definition at line 556 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator!=(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value().
m_box
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> AABox G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_box private
The underlying box in 3D space
Definition at line 545 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance().
m_cell
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Cell* G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_cell private
The current cell.
Definition at line 553 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator!=(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value().
m_current
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Vector3int32 G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_current private
The iterator winds through the 3D grid between m_lo and (m_lo + m_extent) in Z,Y,X-major order. This is the index keeping track of how far it has come
Definition at line 550 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator().
m_epoch
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_epoch private
Definition at line 558 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++().
m_exact
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_exact private
If true, test values against m_box before returning them.
Definition at line 542 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance().
m_grid
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const ThisType* G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_grid private
Definition at line 533 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++().
m_hi
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Vector3int32 G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_hi private
Upper bound on the boxes covered, inclusive.
Definition at line 539 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator().
m_isEnd
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_isEnd private
Definition at line 531 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::hasMore(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::isValid(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator!=(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::operator++(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::value().
m_lo
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Vector3int32 G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::m_lo private
Lower bound on the boxes covered, inclusive.
Definition at line 536 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointHashGrid.h