Azerotcore-wotlk: instance_zulfarrak::instance_zulfarrak_InstanceMapScript Struct Reference
instance_zulfarrak::instance_zulfarrak_InstanceMapScript Struct Reference
Public Member Functions
instance_zulfarrak_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *gameobject) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 data) const override
void Update (uint32 diff) override
void MoveNPCIfAlive (uint32 entry, float x, float y, float z, float o)
void SpawnPyramidWave (uint32 wave)
bool IsWaveAllDead ()
void SendAddsUpStairs (uint32 count)
std::string GetSaveData () override
void Load (const char *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid EndDoorGUID
ObjectGuid BlyGUID
ObjectGuid WeegliGUID
ObjectGuid OroGUID
ObjectGuid RavenGUID
ObjectGuid MurtaGUID
ObjectGuid ShadowpriestGUID
GuidList addsAtBase
GuidList movedadds
uint32 GahzrillaSummoned
uint32 PyramidPhase
uint32 major_wave_Timer
uint32 minor_wave_Timer
uint32 addGroupSize
uint32 waypoint
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 112 of file instance_zulfarrak.cpp.
Constructor & Destructor Documentation
instance_zulfarrak_InstanceMapScript()
instance_zulfarrak::instance_zulfarrak_InstanceMapScript::instance_zulfarrak_InstanceMapScript (Map * map) inline
Definition at line 114 of file instance_zulfarrak.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetData()
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 219 of file instance_zulfarrak.cpp.
         {
             switch (type)
             {
                 case DATA_PYRAMID:
                     return PyramidPhase;
                 case DATA_GAHZRILLA:
                     return GahzrillaSummoned;
             }
             return 0;
         }
References DATA_GAHZRILLA, DATA_PYRAMID, GahzrillaSummoned, and PyramidPhase.
GetGuidData()
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 232 of file instance_zulfarrak.cpp.
         {
             switch (data)
             {
                 case NPC_BLY:
                     return BlyGUID;
                 case NPC_RAVEN:
                     return RavenGUID;
                 case NPC_ORO:
                     return OroGUID;
                 case NPC_WEEGLI:
                     return WeegliGUID;
                 case NPC_MURTA:
                     return MurtaGUID;
                 case NPC_SHADOWPRIEST_SEZZZIZ:
                     return ShadowpriestGUID;
                 case GO_END_DOOR:
                     return EndDoorGUID;
             }
             return ObjectGuid::Empty;
         }
References BlyGUID, ObjectGuid::Empty, EndDoorGUID, GO_END_DOOR, MurtaGUID, NPC_BLY, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_SHADOWPRIEST_SEZZZIZ, NPC_WEEGLI, OroGUID, RavenGUID, ShadowpriestGUID, and WeegliGUID.
Referenced by MoveNPCIfAlive().
GetSaveData()
std::string instance_zulfarrak::instance_zulfarrak_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 443 of file instance_zulfarrak.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "Z F " << PyramidPhase << ' ' << GahzrillaSummoned;
             return saveStream.str();
         }
References GahzrillaSummoned, and PyramidPhase.
Initialize()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 134 of file instance_zulfarrak.cpp.
         {
             GahzrillaSummoned = NOT_STARTED;
             PyramidPhase = 0;
             major_wave_Timer = 0;
             minor_wave_Timer = 0;
             addGroupSize = 0;
             waypoint = 0;
         }
References addGroupSize, GahzrillaSummoned, major_wave_Timer, minor_wave_Timer, NOT_STARTED, PyramidPhase, and waypoint.
IsWaveAllDead()
bool instance_zulfarrak::instance_zulfarrak_InstanceMapScript::IsWaveAllDead () inline
Definition at line 401 of file instance_zulfarrak.cpp.
         {
             for (GuidList::iterator itr = addsAtBase.begin(); itr != addsAtBase.end(); ++itr)
             {
                 if (Creature* add = instance->GetCreature((*itr)))
                 {
                     if (add->IsAlive())
                     {
                         return false;
                     }
                 }
             }
             for (GuidList::iterator itr = movedadds.begin(); itr != movedadds.end(); ++itr)
             {
                 if (Creature* add = instance->GetCreature(((*itr))))
                 {
                     if (add->IsAlive())
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References addsAtBase, Map::GetCreature(), InstanceScript::instance, and movedadds.
Referenced by Update().
Load()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::Load (const char * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 450 of file instance_zulfarrak.cpp.
         {
             if (!str)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'Z' && dataHead2 == 'F')
             {
                 loadStream >> PyramidPhase;
                 loadStream >> GahzrillaSummoned;
             }
         }
References GahzrillaSummoned, and PyramidPhase.
MoveNPCIfAlive()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::MoveNPCIfAlive (uint32 entry, float x, float y, float z, float o) inline
Definition at line 362 of file instance_zulfarrak.cpp.
         {
            if (Creature* npc = instance->GetCreature(GetGuidData(entry)))
            {
                if (npc->IsAlive())
                {
                     npc->SetWalk(true);
                     npc->GetMotionMaster()->MovePoint(1, { x, y, z, o } );
                     npc->SetHomePosition(x, y, z, o);
                }
             }
         }
References Map::GetCreature(), GetGuidData(), and InstanceScript::instance.
Referenced by Update().
OnCreatureCreate()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 145 of file instance_zulfarrak.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_BLY:
                     BlyGUID = creature->GetGUID();
                     creature->SetReactState(REACT_PASSIVE); // starts out passive (in a cage)
                     break;
                 case NPC_RAVEN:
                     RavenGUID = creature->GetGUID();
                     creature->SetReactState(REACT_PASSIVE);// starts out passive (in a cage)
                     break;
                 case NPC_ORO:
                     OroGUID = creature->GetGUID();
                     creature->SetReactState(REACT_PASSIVE);// starts out passive (in a cage)
                     break;
                 case NPC_WEEGLI:
                     WeegliGUID = creature->GetGUID();
                     creature->SetReactState(REACT_PASSIVE);// starts out passive (in a cage)
                     break;
                 case NPC_MURTA:
                     MurtaGUID = creature->GetGUID();
                     creature->SetReactState(REACT_PASSIVE);// starts out passive (in a cage)
                     break;
                 case NPC_SHADOWPRIEST_SEZZZIZ:
                     ShadowpriestGUID = creature->GetGUID();
                     break;
                 default:
                     break;
             }
         }
References BlyGUID, Object::GetEntry(), Object::GetGUID(), MurtaGUID, NPC_BLY, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_SHADOWPRIEST_SEZZZIZ, NPC_WEEGLI, OroGUID, RavenGUID, REACT_PASSIVE, Creature::SetReactState(), ShadowpriestGUID, and WeegliGUID.
OnGameObjectCreate()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 177 of file instance_zulfarrak.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_END_DOOR:
                     EndDoorGUID = gameobject->GetGUID();
                     if (PyramidPhase == PYRAMID_DONE)
                     {
                         HandleGameObject(gameobject->GetGUID(), true, gameobject);
                     }
                     break;
                 default:
                     break;
             }
         }
References EndDoorGUID, Object::GetEntry(), Object::GetGUID(), GO_END_DOOR, InstanceScript::HandleGameObject(), PYRAMID_DONE, and PyramidPhase.
OnUnitDeath()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 193 of file instance_zulfarrak.cpp.
         {
             if (unit->GetEntry() == NPC_BLY)
             {
                 PyramidPhase = PYRAMID_DONE;
                 SaveToDB();
             }
         }
References Object::GetEntry(), NPC_BLY, PYRAMID_DONE, PyramidPhase, and InstanceScript::SaveToDB().
SendAddsUpStairs()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SendAddsUpStairs (uint32 count) inline
Definition at line 428 of file instance_zulfarrak.cpp.
         {
             //pop a add from list, send him up the stairs...
             for (uint32 addCount = 0; addCount < count && !addsAtBase.empty(); addCount++)
             {
                 if (Creature* add = instance->GetCreature(*addsAtBase.begin()))
                 {
                     add->GetMotionMaster()->MovePath(PATH_ADDS, false);
                     movedadds.push_back(add->GetGUID());
                 }
                 addsAtBase.erase(addsAtBase.begin());
             }
         }
References addsAtBase, Map::GetCreature(), InstanceScript::instance, movedadds, and PATH_ADDS.
Referenced by Update().
SetData()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 202 of file instance_zulfarrak.cpp.
         {
             switch (type)
             {
                 case DATA_PYRAMID:
                     PyramidPhase = data;
                     break;
                 case DATA_GAHZRILLA:
                     GahzrillaSummoned = data;
                     break;
                 default:
                     break;
             }
             SaveToDB();
         }
References DATA_GAHZRILLA, DATA_PYRAMID, GahzrillaSummoned, PyramidPhase, and InstanceScript::SaveToDB().
Referenced by Update().
SpawnPyramidWave()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave (uint32 wave) inline
Definition at line 375 of file instance_zulfarrak.cpp.
         {
             for (uint32 i = 0; i < pyramidSpawnTotal; i++)
             {
                 if (pyramidSpawns[i].waveID == wave)
                 {
                     float orientation = 4.78f;
                     if (pyramidSpawns[i].creatureID == NPC_SHADOWPRIEST_SEZZZIZ || pyramidSpawns[i].creatureID == NPC_NEKRUM_GUTCHEWER)
                     {
                         orientation = 1.32f;
                     }
                     Position pos = { pyramidSpawns[i].pos.GetPositionX(), pyramidSpawns[i].pos.GetPositionY(), 8.87f, orientation };
                     if (TempSummon* ts = instance->SummonCreature(pyramidSpawns[i].creatureID, pos))
                     {
                         addsAtBase.push_back(ts->GetGUID());
                         if (pyramidSpawns[i].creatureID != NPC_SHADOWPRIEST_SEZZZIZ && pyramidSpawns[i].creatureID != NPC_NEKRUM_GUTCHEWER)
{
                             ts->GetMotionMaster()->MoveRandom(10);
                         }
                     }
                 }
             }
         }
References addsAtBase, PyramidEventData::creatureID, Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, NPC_NEKRUM_GUTCHEWER, NPC_SHADOWPRIEST_SEZZZIZ, PyramidEventData::pos, pyramidSpawns, pyramidSpawnTotal, and Map::SummonCreature().
Referenced by Update().
Update()
void instance_zulfarrak::instance_zulfarrak_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 255 of file instance_zulfarrak.cpp.
         {
             switch (PyramidPhase)
             {
                 case PYRAMID_NOT_STARTED:
                 case PYRAMID_KILLED_ALL_TROLLS:
                 case PYRAMID_MOVED_DOWNSTAIRS:
                 case PYRAMID_DESTROY_GATES:
                 case PYRAMID_GATES_DESTROYED:
                 case PYRAMID_DONE:
                     break;
                 case PYRAMID_ARRIVED_AT_STAIR:
                     SpawnPyramidWave(1);
                     SetData(DATA_PYRAMID, PYRAMID_WAVE_1);
                     major_wave_Timer = 2 * MINUTE * IN_MILLISECONDS;
                     minor_wave_Timer = 0;
                     addGroupSize = 2;
                     break;
                 case PYRAMID_WAVE_1:
                     if (IsWaveAllDead())
                     {
                         SetData(DATA_PYRAMID, PYRAMID_PRE_WAVE_2);
                         major_wave_Timer = 10 * IN_MILLISECONDS; //give players a few seconds before wave 2 starts to rebuff
                     }
                     else
                     {
                         if (minor_wave_Timer <= diff)
{
                             SendAddsUpStairs(addGroupSize++);
                             minor_wave_Timer = 10 * IN_MILLISECONDS;
                         }
                         else
{
                             minor_wave_Timer -= diff;
                         }
                     }
                     break;
                 case PYRAMID_PRE_WAVE_2:
                     if (major_wave_Timer <= diff)
                     {
                         // beginning 2nd wave!
                         SpawnPyramidWave(2);
                         SetData(DATA_PYRAMID, PYRAMID_WAVE_2);
                         minor_wave_Timer = 0;
                         addGroupSize = 2;
                     }
                     else
                     {
                         major_wave_Timer -= diff;
                     }
                     break;
                 case PYRAMID_WAVE_2:
                     if (IsWaveAllDead())
                     {
                         SpawnPyramidWave(3);
                         SetData(DATA_PYRAMID, PYRAMID_PRE_WAVE_3);
                         major_wave_Timer = 5 * IN_MILLISECONDS; //give NPCs time to return to their home spots
                     }
                     else
                     {
                         if (minor_wave_Timer <= diff)
{
                             SendAddsUpStairs(addGroupSize++);
                             minor_wave_Timer = 10 * IN_MILLISECONDS;
                         }
                         else
{
                             minor_wave_Timer -= diff;
                         }
                     }
                     break;
                 case PYRAMID_PRE_WAVE_3:
                     if (major_wave_Timer <= diff)
                     {
                         // move NPCs to bottom of stair
                         MoveNPCIfAlive(NPC_BLY, 1887.92f, 1228.179f, 9.98f, 4.78f);
                         MoveNPCIfAlive(NPC_MURTA, 1891.57f, 1228.68f, 9.69f, 4.78f);
                         MoveNPCIfAlive(NPC_ORO, 1897.23f, 1228.34f, 9.43f, 4.78f);
                         MoveNPCIfAlive(NPC_RAVEN, 1883.68f, 1227.95f, 9.543f, 4.78f);
                         MoveNPCIfAlive(NPC_WEEGLI, 1878.02f, 1227.65f, 9.485f, 4.78f);
                         SetData(DATA_PYRAMID, PYRAMID_WAVE_3);
                         if (Creature* sergeantBlye = instance->GetCreature(BlyGUID))
{
                             sergeantBlye->AI()->Talk(SAY_BLY_FORWARD);
                         }
                     }
                     else
                     {
                         major_wave_Timer -= diff;
                     }
                     break;
                 case PYRAMID_WAVE_3:
                     if (IsWaveAllDead()) // move NPCS to their final positions
                     {
                         SetData(DATA_PYRAMID, PYRAMID_KILLED_ALL_TROLLS);
                         MoveNPCIfAlive(NPC_BLY, 1883.82f, 1200.83f, 8.87f, 1.32f);
                         MoveNPCIfAlive(NPC_MURTA, 1891.83f, 1201.45f, 8.87f, 1.32f);
                         MoveNPCIfAlive(NPC_ORO, 1894.50f, 1204.40f, 8.87f, 1.32f);
                         MoveNPCIfAlive(NPC_RAVEN, 1874.11f, 1206.17f, 8.87f, 1.32f);
                         MoveNPCIfAlive(NPC_WEEGLI, 1877.52f, 1199.63f, 8.87f, 1.32f);
                     }
                     break;
                 default:
                     break;
             };
         }
References addGroupSize, BlyGUID, DATA_PYRAMID, Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, IsWaveAllDead(), major_wave_Timer, minor_wave_Timer, MINUTE, MoveNPCIfAlive(), NPC_BLY, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_WEEGLI, PYRAMID_ARRIVED_AT_STAIR, PYRAMID_DESTROY_GATES, PYRAMID_DONE, PYRAMID_GATES_DESTROYED, PYRAMID_KILLED_ALL_TROLLS, PYRAMID_MOVED_DOWNSTAIRS, PYRAMID_NOT_STARTED, PYRAMID_PRE_WAVE_2, PYRAMID_PRE_WAVE_3, PYRAMID_WAVE_1, PYRAMID_WAVE_2, PYRAMID_WAVE_3, PyramidPhase, SAY_BLY_FORWARD, SendAddsUpStairs(), SetData(), and SpawnPyramidWave().
Member Data Documentation
addGroupSize
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::addGroupSize
Definition at line 131 of file instance_zulfarrak.cpp.
Referenced by Initialize(), and Update().
addsAtBase
GuidList instance_zulfarrak::instance_zulfarrak_InstanceMapScript::addsAtBase
Definition at line 124 of file instance_zulfarrak.cpp.
Referenced by IsWaveAllDead(), SendAddsUpStairs(), and SpawnPyramidWave().
BlyGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::BlyGUID
Definition at line 117 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
EndDoorGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::EndDoorGUID
Definition at line 116 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
GahzrillaSummoned
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::GahzrillaSummoned
Definition at line 127 of file instance_zulfarrak.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and SetData().
major_wave_Timer
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::major_wave_Timer
Definition at line 129 of file instance_zulfarrak.cpp.
Referenced by Initialize(), and Update().
minor_wave_Timer
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::minor_wave_Timer
Definition at line 130 of file instance_zulfarrak.cpp.
Referenced by Initialize(), and Update().
movedadds
GuidList instance_zulfarrak::instance_zulfarrak_InstanceMapScript::movedadds
Definition at line 125 of file instance_zulfarrak.cpp.
Referenced by IsWaveAllDead(), and SendAddsUpStairs().
MurtaGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::MurtaGUID
Definition at line 121 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
OroGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OroGUID
Definition at line 119 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
PyramidPhase
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::PyramidPhase
Definition at line 128 of file instance_zulfarrak.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), OnUnitDeath(), SetData(), and Update().
RavenGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::RavenGUID
Definition at line 120 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
ShadowpriestGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::ShadowpriestGUID
Definition at line 122 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
waypoint
uint32 instance_zulfarrak::instance_zulfarrak_InstanceMapScript::waypoint
Definition at line 132 of file instance_zulfarrak.cpp.
Referenced by Initialize().
WeegliGUID
ObjectGuid instance_zulfarrak::instance_zulfarrak_InstanceMapScript::WeegliGUID
Definition at line 118 of file instance_zulfarrak.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/ZulFarrak/instance_zulfarrak.cpp