Azerotcore-wotlk: go_wind_stone::go_wind_stoneAI Struct Reference
go_wind_stone::go_wind_stoneAI Struct Reference
Public Member Functions
go_wind_stoneAI (GameObject *go)
bool GossipHello (Player *player, bool reportUse) override
bool GossipSelect (Player *player, uint32 sender, uint32 action) override
void SummonNPC (GameObject *go, Player *player, uint32 npc, uint32 spellId)
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 1008 of file zone_silithus.cpp.
Constructor & Destructor Documentation
go_wind_stoneAI()
go_wind_stone::go_wind_stoneAI::go_wind_stoneAI (GameObject * go) inline
Definition at line 1010 of file zone_silithus.cpp.
 : GameObjectAI(go) {}
Member Function Documentation
GossipHello()
bool go_wind_stone::go_wind_stoneAI::GossipHello (Player * player, bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1012 of file zone_silithus.cpp.
         {
             if (reportUse)
             {
                 uint32 gossipId         = me->GetGOInfo()->GetGossipMenuId();
                 bool   _twilightSetAura = (player->HasAura(AURA_TWILIGHT_SET, player->GetGUID()) ? true : false);
                 bool   _medallionAura   = (player->HasAura(AURA_MEDALLION, player->GetGUID()) ? true : false);
                 bool   _ringAura        = (player->HasAura(AURA_RING, player->GetGUID()) ? true : false);
                 switch (gossipId)
                 {
                 case GOSSIPID_LESSER_WS:
                 {
                     if (!_twilightSetAura)
                         me->CastSpell(player, SPELL_PUNISHMENT);
                     break;
                 }
                 case GOSSIPID_WS:
                 {
                     if (!_twilightSetAura || !_medallionAura)
                         me->CastSpell(player, SPELL_PUNISHMENT);
                     break;
                 }
                 case GOSSIPID_GREATER_WS:
                 {
                     if (!_twilightSetAura || !_medallionAura || !_ringAura)
                         me->CastSpell(player, SPELL_PUNISHMENT);
                     break;
                 }
                 default:
                     break;
                 }
             }
             return false;
         }
References AURA_MEDALLION, AURA_RING, AURA_TWILIGHT_SET, Object::GetGUID(), GOSSIPID_GREATER_WS, GOSSIPID_LESSER_WS, GOSSIPID_WS, Unit::HasAura(), and SPELL_PUNISHMENT.
GossipSelect()
bool go_wind_stone::go_wind_stoneAI::GossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1048 of file zone_silithus.cpp.
         {
             player->PlayerTalkClass->SendCloseGossip();
             if (sender == GOSSIPID_LESSER_WS)
             {
                 switch (action)
                 {
                 case 0:
                     SummonNPC(me, player, RAND(NPC_TEMPLAR_WATER, NPC_TEMPLAR_FIRE, NPC_TEMPLAR_EARTH, NPC_TEMPLAR_AIR), SPELL_TEMPLAR_RANDOM);
                     break;
                 case 1:
                     SummonNPC(me, player, NPC_TEMPLAR_FIRE, SPELL_TEMPLAR_FIRE);
                     break;
                 case 2:
                     SummonNPC(me, player, NPC_TEMPLAR_WATER, SPELL_TEMPLAR_WATER);
                     break;
                 case 3:
                     SummonNPC(me, player, NPC_TEMPLAR_EARTH, SPELL_TEMPLAR_EARTH);
                     break;
                 case 4:
                     SummonNPC(me, player, NPC_TEMPLAR_AIR, SPELL_TEMPLAR_AIR);
                     break;
                 default:
                     break;
                 }
             }
             else if (sender == GOSSIPID_WS)
             {
                 switch (action)
                 {
                 case 0:
                     SummonNPC(me, player, RAND(NPC_DUKE_WATER, NPC_DUKE_FIRE, NPC_DUKE_EARTH, NPC_DUKE_AIR), SPELL_DUKE_RANDOM);
                     break;
                 case 1:
                     SummonNPC(me, player, NPC_DUKE_FIRE, SPELL_DUKE_FIRE);
                     break;
                 case 2:
                     SummonNPC(me, player, NPC_DUKE_WATER, SPELL_DUKE_WATER);
                     break;
                 case 3:
                     SummonNPC(me, player, NPC_DUKE_EARTH, SPELL_DUKE_EARTH);
                     break;
                 case 4:
                     SummonNPC(me, player, NPC_DUKE_AIR, SPELL_DUKE_AIR);
                     break;
                 default:
                     break;
                 }
             }
             else if (sender == GOSSIPID_GREATER_WS)
             {
                 switch (action)
                 {
                 case 0:
                     SummonNPC(me, player, RAND(NPC_ROYAL_WATER, NPC_ROYAL_FIRE, NPC_ROYAL_EARTH, NPC_ROYAL_AIR), SPELL_ROYAL_RANDOM);
                     break;
                 case 1:
                     SummonNPC(me, player, NPC_ROYAL_FIRE, SPELL_ROYAL_FIRE);
                     break;
                 case 2:
                     SummonNPC(me, player, NPC_ROYAL_WATER, SPELL_ROYAL_WATER);
                     break;
                 case 3:
                     SummonNPC(me, player, NPC_ROYAL_EARTH, SPELL_ROYAL_EARTH);
                     break;
                 case 4:
                     SummonNPC(me, player, NPC_ROYAL_AIR, SPELL_ROYAL_AIR);
                     break;
                 default:
                     break;
                 }
             }
             return false;
         }
References GOSSIPID_GREATER_WS, GOSSIPID_LESSER_WS, GOSSIPID_WS, NPC_DUKE_AIR, NPC_DUKE_EARTH, NPC_DUKE_FIRE, NPC_DUKE_WATER, NPC_ROYAL_AIR, NPC_ROYAL_EARTH, NPC_ROYAL_FIRE, NPC_ROYAL_WATER, NPC_TEMPLAR_AIR, NPC_TEMPLAR_EARTH, NPC_TEMPLAR_FIRE, NPC_TEMPLAR_WATER, Player::PlayerTalkClass, RAND(), PlayerMenu::SendCloseGossip(), SPELL_DUKE_AIR, SPELL_DUKE_EARTH, SPELL_DUKE_FIRE, SPELL_DUKE_RANDOM, SPELL_DUKE_WATER, SPELL_ROYAL_AIR, SPELL_ROYAL_EARTH, SPELL_ROYAL_FIRE, SPELL_ROYAL_RANDOM, SPELL_ROYAL_WATER, SPELL_TEMPLAR_AIR, SPELL_TEMPLAR_EARTH, SPELL_TEMPLAR_FIRE, SPELL_TEMPLAR_RANDOM, and SPELL_TEMPLAR_WATER.
SummonNPC()
void go_wind_stone::go_wind_stoneAI::SummonNPC (GameObject * go, Player * player, uint32 npc, uint32 spellId) inline
Definition at line 1124 of file zone_silithus.cpp.
         {
             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
             if (!spellInfo)
                 return;
             SpellInfo const* spellInfoTrigger = sSpellMgr->GetSpellInfo(spellInfo->Effects[EFFECT_0].TriggerSpell);
             if (!spellInfoTrigger)
                 return;
             Spell*          spell  = new Spell(player, spellInfoTrigger, TRIGGERED_NONE);
             SpellCastResult result = spell->CheckCast(true);
             delete spell;
             if (result != SPELL_CAST_OK)
             {
                 if (result == SPELL_FAILED_REAGENTS)
                 {
                     std::string accountName;
                     AccountMgr::GetName(player->GetSession()->GetAccountId(), accountName);
                     sBan->BanAccount(accountName, "0s", "Wind Stone exploit", "Server");
                 }
                 return;
             }
             player->CastSpell(player, spellInfoTrigger->Id, false);
             TempSummon* summons = go->SummonCreature(npc, go->GetPositionX(), go->GetPositionY(), go->GetPositionZ(), player->GetOrientation() - M_PI, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 10 * 60 * 1000);
             summons->CastSpell(summons, SPELL_SPAWN_IN, false);
             summons->AI()->Talk(SAY_ON_SPAWN_IN);
             summons->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             summons->SendMeleeAttackStart(player);
             summons->CombatStart(player);
         }
References Unit::CastSpell(), Spell::CheckCast(), EFFECT_0, SpellInfo::Effects, WorldSession::GetAccountId(), AccountMgr::GetName(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetSession(), SpellInfo::Id, SAY_ON_SPAWN_IN, sBan, SPELL_CAST_OK, SPELL_FAILED_REAGENTS, SPELL_SPAWN_IN, sSpellMgr, WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, TRIGGERED_NONE, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_silithus.cpp