Azerotcore-wotlk: Acore::FriendlyCCedInRange Class Reference
Acore::FriendlyCCedInRange Class Reference
#include <GridNotifiers.h>
Public Member Functions
FriendlyCCedInRange (Unit const *obj, float range)
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
Detailed Description
Definition at line 759 of file GridNotifiers.h.
Constructor & Destructor Documentation
FriendlyCCedInRange()
Acore::FriendlyCCedInRange::FriendlyCCedInRange (Unit const * obj, float range) inline
Definition at line 762 of file GridNotifiers.h.
 : i_obj(obj), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::FriendlyCCedInRange::operator() (Unit * u) inline
Definition at line 763 of file GridNotifiers.h.
         {
             if (u->IsAlive() && u->IsInCombat() && !i_obj->IsHostileTo(u) && i_obj->IsWithinDistInMap(u, i_range) &&
                     (u->isFeared() || u->IsCharmed() || u->isFrozen() || u->HasUnitState(UNIT_STATE_STUNNED) || u->HasUnitState(UNIT_STATE_CONFUSED)))
             {
                 return true;
             }
             return false;
         }
References Unit::HasUnitState(), i_obj, i_range, Unit::IsAlive(), Unit::IsCharmed(), Unit::isFeared(), Unit::isFrozen(), Unit::IsHostileTo(), Unit::IsInCombat(), WorldObject::IsWithinDistInMap(), UNIT_STATE_CONFUSED, and UNIT_STATE_STUNNED.
Member Data Documentation
i_obj
Unit const* Acore::FriendlyCCedInRange::i_obj private
Definition at line 773 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::FriendlyCCedInRange::i_range private
Definition at line 774 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h