Azerotcore-wotlk: npc_simone Class Reference
npc_simone Class Reference
Classes
struct npc_simoneAI
Public Member Functions
npc_simone ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 507 of file npc_stave_of_ancients.cpp.
Constructor & Destructor Documentation
npc_simone()
npc_simone::npc_simone () inline
Definition at line 510 of file npc_stave_of_ancients.cpp.
 : CreatureScript("npc_simone") { }
Member Function Documentation
GetAI()
CreatureAI* npc_simone::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 512 of file npc_stave_of_ancients.cpp.
     {
         return new npc_simoneAI(creature);
     }
OnGossipHello()
bool npc_simone::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 811 of file npc_stave_of_ancients.cpp.
     {
         if (player->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS) == QUEST_STATUS_INCOMPLETE && !player->HasItemCount(SIMONE_HEAD, 1, true))
         {
             uint32 gossipMenuId = creature->GetCreatureTemplate()->GossipMenuId;
             AddGossipItemFor(player, gossipMenuId, GOSSIP_EVENT_START_OPTION_ID, GOSSIP_SENDER_MAIN, 0);
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Creature::GetCreatureTemplate(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_EVENT_START_OPTION_ID, GOSSIP_SENDER_MAIN, CreatureTemplate::GossipMenuId, Player::HasItemCount(), QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, SendGossipMenuFor(), and SIMONE_HEAD.
OnGossipSelect()
bool npc_simone::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 800 of file npc_stave_of_ancients.cpp.
     {
         CloseGossipMenuFor(player);
         if (creature->AI() && CAST_AI(npc_simone::npc_simoneAI, creature->AI()))
         {
             CAST_AI(npc_simone::npc_simoneAI, creature->AI())->ScheduleEncounterStart(player->GetGUID());
         }
         return true;
     }
References Creature::AI(), CAST_AI, CloseGossipMenuFor(), and Object::GetGUID().
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_stave_of_ancients.cpp