Azerotcore-wotlk: item_captured_frog Class Reference
item_captured_frog Class Reference
Public Member Functions
item_captured_frog ()
bool OnUse (Player *player, Item *item, SpellCastTargets const &) override
Public Member Functions inherited from ItemScript
bool IsDatabaseBound () const override
virtual bool OnQuestAccept (Player *, Item *, Quest const *)
virtual bool OnRemove (Player *, Item *)
virtual bool OnCastItemCombatSpell (Player *, Unit *, SpellInfo const *, Item *)
virtual bool OnExpire (Player *, ItemTemplate const *)
virtual void OnGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from ItemScript
ItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 228 of file item_scripts.cpp.
Constructor & Destructor Documentation
item_captured_frog()
item_captured_frog::item_captured_frog () inline
Definition at line 231 of file item_scripts.cpp.
 : ItemScript("item_captured_frog") { }
Member Function Documentation
OnUse()
bool item_captured_frog::OnUse (Player * player, Item * item, SpellCastTargets const &) inline override virtual
Reimplemented from ItemScript.
Definition at line 233 of file item_scripts.cpp.
     {
         if (player->GetQuestStatus(QUEST_THE_PERFECT_SPIES) == QUEST_STATUS_INCOMPLETE)
         {
             if (player->FindNearestCreature(NPC_VANIRAS_SENTRY_TOTEM, 10.0f))
                 return false;
             else
                 player->SendEquipError(EQUIP_ERR_OUT_OF_RANGE, item, nullptr);
         }
         else
             player->SendEquipError(EQUIP_ERR_CANT_DO_RIGHT_NOW, item, nullptr);
         return true;
     }
References EQUIP_ERR_CANT_DO_RIGHT_NOW, EQUIP_ERR_OUT_OF_RANGE, WorldObject::FindNearestCreature(), Player::GetQuestStatus(), NPC_VANIRAS_SENTRY_TOTEM, QUEST_STATUS_INCOMPLETE, QUEST_THE_PERFECT_SPIES, and Player::SendEquipError().
The documentation for this class was generated from the following file:
src/server/scripts/World/item_scripts.cpp