Azerotcore-wotlk: ShadowTrapLKTargetSelector Struct Reference
ShadowTrapLKTargetSelector Struct Reference
Public Member Functions
ShadowTrapLKTargetSelector (Creature *source, bool playerOnly=true, bool reqLOS=false, float maxDist=0.0f)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
bool _playerOnly
bool _reqLOS
float _maxDist
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 373 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
ShadowTrapLKTargetSelector()
ShadowTrapLKTargetSelector::ShadowTrapLKTargetSelector (Creature * source, bool playerOnly = true, bool reqLOS = false, float maxDist = 0.0f) inline
Definition at line 376 of file boss_the_lich_king.cpp.
 : _source(source), _playerOnly(playerOnly), _reqLOS(reqLOS), _maxDist(maxDist) { }
Member Function Documentation
operator()()
bool ShadowTrapLKTargetSelector::operator() (Unit const * target) const inline
Definition at line 377 of file boss_the_lich_king.cpp.
     {
         if (!target)
             return false;
         if (!target->IsAlive())
             return false;
         if (_playerOnly && target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (_maxDist && _source->GetExactDist(target) > _maxDist)
             return false;
         if (_reqLOS && !_source->IsWithinLOSInMap(target))
             return false;
         return true;
     }
References _maxDist, _playerOnly, _reqLOS, _source, Position::GetExactDist(), Object::GetTypeId(), Unit::IsAlive(), WorldObject::IsWithinLOSInMap(), and TYPEID_PLAYER.
Member Data Documentation
_maxDist
float ShadowTrapLKTargetSelector::_maxDist private
Definition at line 396 of file boss_the_lich_king.cpp.
Referenced by operator()().
_playerOnly
bool ShadowTrapLKTargetSelector::_playerOnly private
Definition at line 394 of file boss_the_lich_king.cpp.
Referenced by operator()().
_reqLOS
bool ShadowTrapLKTargetSelector::_reqLOS private
Definition at line 395 of file boss_the_lich_king.cpp.
Referenced by operator()().
_source
Creature const* ShadowTrapLKTargetSelector::_source private
Definition at line 393 of file boss_the_lich_king.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp