Azerotcore-wotlk: go_shadowforge_brazier Class Reference
go_shadowforge_brazier Class Reference
Public Member Functions
go_shadowforge_brazier ()
bool OnGossipHello (Player *, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 32 of file blackrock_depths.cpp.
Constructor & Destructor Documentation
go_shadowforge_brazier()
go_shadowforge_brazier::go_shadowforge_brazier () inline
Definition at line 35 of file blackrock_depths.cpp.
 : GameObjectScript("go_shadowforge_brazier") { }
Member Function Documentation
OnGossipHello()
bool go_shadowforge_brazier::OnGossipHello (Player * , GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 37 of file blackrock_depths.cpp.
     {
         if (InstanceScript* instance = go->GetInstanceScript())
         {
             GameObject* northBrazier = ObjectAccessor::GetGameObject(*go, instance->GetGuidData(DATA_SF_BRAZIER_N));
             GameObject* southBrazier = ObjectAccessor::GetGameObject(*go, instance->GetGuidData(DATA_SF_BRAZIER_S));
             if (!northBrazier || !southBrazier)
             {
                 return false;
             }
             // Check if the opposite brazier is lit - if it is, open the gates.
             if ((go->GetGUID() == northBrazier->GetGUID() && southBrazier->GetGoState() == GO_STATE_ACTIVE)
                 || (go->GetGUID() == southBrazier->GetGUID() && northBrazier->GetGoState() == GO_STATE_ACTIVE))
             {
                 if (instance->GetData(TYPE_LYCEUM) == IN_PROGRESS)
                 {
                     instance->SetData(TYPE_LYCEUM, DONE);
                 }
                 else
                 {
                     instance->SetData(TYPE_LYCEUM, IN_PROGRESS);
                 }
                 if (Creature* magmus = ObjectAccessor::GetCreature(*go, instance->GetGuidData(DATA_MAGMUS)))
                 {
                     if (magmus->IsAlive())
                     {
                         magmus->AI()->Talk(SAY_MAGMUS_BRAZIER_LIT);
                     }
                 }
                 instance->HandleGameObject(instance->GetGuidData(DATA_GOLEM_DOOR_N), true);
                 instance->HandleGameObject(instance->GetGuidData(DATA_GOLEM_DOOR_S), true);
             }
         }
         return false;
     }
References DATA_GOLEM_DOOR_N, DATA_GOLEM_DOOR_S, DATA_MAGMUS, DATA_SF_BRAZIER_N, DATA_SF_BRAZIER_S, DONE, ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), GameObject::GetGoState(), Object::GetGUID(), WorldObject::GetInstanceScript(), GO_STATE_ACTIVE, IN_PROGRESS, SAY_MAGMUS_BRAZIER_LIT, and TYPE_LYCEUM.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp