Azerotcore-wotlk: npc_q24545_lich_king::npc_q24545_lich_kingAI Struct Reference
npc_q24545_lich_king::npc_q24545_lich_kingAI Struct Reference
Public Member Functions
npc_q24545_lich_kingAI (Creature *c)
void CleanAll (bool fromReset=true)
void Reset () override
void SetGUID (ObjectGuid guid, int32) override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 758 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
npc_q24545_lich_kingAI()
npc_q24545_lich_king::npc_q24545_lich_kingAI::npc_q24545_lich_kingAI (Creature * c) inline
Definition at line 760 of file zone_dragonblight.cpp.
                                             : NullCreatureAI(c), summons(me)
         {
         }
Member Function Documentation
CleanAll()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll (bool fromReset = true) inline
Definition at line 768 of file zone_dragonblight.cpp.
         {
             if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
                 c->RemoveAllAuras();
             if (fromReset)
             {
                 if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                     c->DespawnOrUnsummon(1);
                 if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                     c->RemoveAllAuras();
             }
             if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_2, 150.0f, true))
                 c->DespawnOrUnsummon(1);
             if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_1, 150.0f))
                 go->Delete();
             if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_2, 150.0f))
                 go->Delete();
             WretchedGhoulCleaner cleaner;
             Acore::CreatureWorker<WretchedGhoulCleaner> worker(me, cleaner);
             Cell::VisitGridObjects(me, worker, 150.0f);
         }
References WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GO_SAC_LIGHTS_VENGEANCE_1, GO_SAC_LIGHTS_VENGEANCE_2, CreatureAI::me, NPC_SAC_LIGHTS_VENGEANCE, NPC_SAC_LIGHTS_VENGEANCE_BUNNY, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, NPC_SAC_LIGHTS_VENGEANCE_VEH_2, and Cell::VisitGridObjects().
Referenced by Reset(), and UpdateAI().
JustSummoned()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1030 of file zone_dragonblight.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
Reset()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 790 of file zone_dragonblight.cpp.
         {
             events.Reset();
             events.ScheduleEvent(998, 10000);
             events.ScheduleEvent(999, 0);
             events.ScheduleEvent(1, 3000);
             summons.DespawnAll();
             playerGUID.Clear();
             CleanAll();
             me->setActive(false);
             me->SetWalk(true);
             me->SetVisible(false);
             me->RemoveAllAuras();
             me->InterruptNonMeleeSpells(true);
             float x, y, z, o;
             me->GetHomePosition(x, y, z, o);
             me->UpdatePosition(x, y, z, o, true);
             me->StopMovingOnCurrentPos();
             me->GetMotionMaster()->Clear();
         }
References CleanAll(), ObjectGuid::Clear(), MotionMaster::Clear(), SummonList::DespawnAll(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), CreatureAI::me, playerGUID, Unit::RemoveAllAuras(), WorldObject::setActive(), Unit::SetVisible(), Creature::SetWalk(), Unit::StopMovingOnCurrentPos(), summons, and Unit::UpdatePosition().
Referenced by UpdateAI().
SetData()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 824 of file zone_dragonblight.cpp.
         {
             if (!playerGUID || type != data)
                 return;
             if (data == 1)
                 events.ScheduleEvent(15, 0);
             else if (data == 2)
             {
                 if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_2, 150.0f))
                     go->Delete();
                 if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                 {
                     c->CastSpell(c, SPELL_SAC_HAMMER_SHIELD, true);
                     c->CastSpell(c, SPELL_SAC_SUMMON_GO_3, true);
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                         p->KnockbackFrom(c->GetPositionX(), c->GetPositionY(), 5.0f, 3.0f);
                 }
                 events.ScheduleEvent(18, 3000);
             }
             else if (data == 3)
             {
                 if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                 {
                     c->RemoveAllAuras();
                     c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                     if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_3, 150.0f))
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     playerGUID.Clear();
                     events.RescheduleEvent(2, 60000);
                 }
             }
         }
References ObjectGuid::Clear(), WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, ObjectAccessor::GetPlayer(), GO_FLAG_NOT_SELECTABLE, GO_SAC_LIGHTS_VENGEANCE_2, GO_SAC_LIGHTS_VENGEANCE_3, CreatureAI::me, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, playerGUID, SPELL_SAC_HAMMER_SHIELD, SPELL_SAC_HOLY_ZONE_AURA, and SPELL_SAC_SUMMON_GO_3.
SetGUID()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SetGUID (ObjectGuid guid, int32) inline override virtual
Reimplemented from UnitAI.
Definition at line 813 of file zone_dragonblight.cpp.
         {
             if (playerGUID || events.GetNextEventTime(998) || events.GetNextEventTime(2))
                 return;
             me->setActive(true);
             playerGUID = guid;
             events.ScheduleEvent(2, 900000);
             events.ScheduleEvent(3, 0);
         }
References CreatureAI::me, playerGUID, and WorldObject::setActive().
SpellHitTarget()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1040 of file zone_dragonblight.cpp.
         {
             if (spell->Id == SPELL_SAC_REPEL_HAMMER && target->GetTypeId() == TYPEID_UNIT)
             {
                 target->CastSpell((Unit*)nullptr, SPELL_SAC_THROW_HAMMER, true);
                 target->ToCreature()->DespawnOrUnsummon(1);
                 if (Unit* c = target->GetVehicleBase())
                     c->RemoveAurasDueToSpell(SPELL_SAC_HOLY_ZONE_AURA);
             }
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), Object::GetTypeId(), Unit::GetVehicleBase(), SpellInfo::Id, SPELL_SAC_HOLY_ZONE_AURA, SPELL_SAC_REPEL_HAMMER, SPELL_SAC_THROW_HAMMER, Object::ToCreature(), and TYPEID_UNIT.
SummonedCreatureDespawn()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1035 of file zone_dragonblight.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 857 of file zone_dragonblight.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 998: // ensure everything is cleaned up
                     CleanAll(false);
                     break;
                 case 999: // apply holy aura
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                         if (Creature* l = me->SummonCreature(NPC_SAC_LIGHTS_VENGEANCE, *c, TEMPSUMMON_MANUAL_DESPAWN))
{
                             l->CastSpell(c, SPELL_SAC_VEHICLE_CONTROL_AURA, true);
                             c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                         }
                     break;
                 case 1: // check player
                     if (playerGUID)
                     {
                         bool valid = false;
                         if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                             if (p->IsAlive() && p->GetPhaseMask() & 2 && p->GetExactDistSq(me) < 100.0f * 100.0f && !p->IsGameMaster())
                                 valid = true;
                         if (!valid)
{
                             Reset();
                             return;
                         }
                     }
                     events.ScheduleEvent(1, 3000);
                     break;
                 case 2: // reset timer
                     Reset();
                     break;
                 case 3: // start event
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                     {
                         me->CastSpell(p, SPELL_SAC_STUN, true);
                         me->SetVisible(true);
                         Movement::PointsArray path;
                         path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                         path.push_back(G3D::Vector3(4825.35f, -582.99f, 164.83f));
                         path.push_back(G3D::Vector3(4813.38f, -580.94f, 162.62f));
                         me->GetMotionMaster()->MoveSplinePath(&path);
                         events.ScheduleEvent(4, 10000);
                     }
                     break;
                 case 4: // talk 0
                     Talk(0);
                     events.ScheduleEvent(5, 6000);
                     break;
                 case 5: // talk 1
                     Talk(1);
                     events.ScheduleEvent(6, 4000);
                     events.ScheduleEvent(7, 11000);
                     break;
                 case 6: // repel hammer
                     me->CastSpell((Unit*)nullptr, SPELL_SAC_REPEL_HAMMER, false);
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
                         c->CastSpell(c, SPELL_SAC_BLUE_EXPLOSION, true);
                     events.ScheduleEvent(65, 3500);
                     break;
                 case 65: // spawn hammer go
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
                     {
                         c->CastSpell(c, SPELL_SAC_HOLY_ZONE_AURA, true);
                         c->CastSpell(c, SPELL_SAC_SUMMON_GO_1, true);
                     }
                     break;
                 case 7: // talk 2
                     Talk(2);
                     events.ScheduleEvent(8, 8000);
                     events.ScheduleEvent(9, 11500);
                     break;
                 case 8: // summon ghouls
                     me->CastSpell((Unit*)nullptr, SPELL_SAC_SUMMON_GHOULS_AURA, false);
                     break;
                 case 9: // talk 3
                     Talk(3);
                     events.ScheduleEvent(10, 10000);
                     break;
                 case 10: // summon vegard
                     me->SummonCreature(NPC_SAC_VEGARD_1, 4812.12f, -586.08f, 162.49f, 3.14f, TEMPSUMMON_MANUAL_DESPAWN);
                     events.ScheduleEvent(11, 4000);
                     events.ScheduleEvent(12, 5000);
                     break;
                 case 11: // vagard shield
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                         c->CastSpell(c, SPELL_SAC_SHIELD_OF_THE_LICH_KING, false);
                     break;
                 case 12: // talk 4
                     Talk(4);
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                         me->CastSpell(p, SPELL_SAC_ZAP_PLAYER, false);
                     events.ScheduleEvent(13, 3500);
                     events.ScheduleEvent(14, 6000);
                     break;
                 case 13: // despawn
                     me->CastSpell(me, SPELL_SAC_LK_DESPAWN_ANIM, false);
                     break;
                 case 14: // vagard talk 0
                     me->SetVisible(false);
                     me->RemoveAllAuras();
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                     {
                         c->AI()->Talk(0);
                         c->CastSpell(c, SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA, false);
                     }
                     if (GameObject* go = me->FindNearestGameObject(GO_SAC_LIGHTS_VENGEANCE_1, 150.0f))
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case 15: // remove light
                     if (Creature* x = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_2, 150.0f, true))
                         if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_BUNNY, 150.0f, true))
{
                             c->RemoveAurasDueToSpell(SPELL_SAC_HOLY_ZONE_AURA);
                             if (Creature* l = me->SummonCreature(NPC_SAC_LIGHTS_VENGEANCE, *c, TEMPSUMMON_MANUAL_DESPAWN))
{
                                 x->SetCanFly(true);
                                 x->SetDisableGravity(true);
                                 x->SetHover(true);
                                 x->NearTeleportTo(4812.09f, -585.55f, 172.03f, 3.75f);
                                 l->EnterVehicle(x, 1);
                                 //l->ClearUnitState(UNIT_STATE_ONVEHICLE);
                                 l->CastSpell(l, SPELL_SAC_HOLY_BOMB_VISUAL, false);
                                 l->AddAura(SPELL_SAC_HOLY_BOMB_VISUAL, l);
                                 events.ScheduleEvent(16, 5000);
                             }
                         }
                     break;
                 case 16: // add aura to kill ghouls
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                         c->CastSpell(c, SPELL_SAC_ZAP_GHOULS_AURA, true);
                     if (Creature* c = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                         c->RemoveAurasDueToSpell(SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA);
                     events.ScheduleEvent(17, 12000);
                     break;
                 case 17: // kill vegard
                     {
                         WretchedGhoulCleaner cleaner;
                         Acore::CreatureWorker<WretchedGhoulCleaner> worker(me, cleaner);
                         Cell::VisitGridObjects(me, worker, 150.0f);
                         if (Creature* c = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE, 150.0f, true))
                             if (Creature* v = me->FindNearestCreature(NPC_SAC_VEGARD_1, 50.0f, true))
                                 if (Creature* b = me->FindNearestCreature(NPC_SAC_LIGHTS_VENGEANCE_VEH_1, 150.0f, true))
{
                                     c->CastSpell(v, SPELL_SAC_KILL_VEGARD, true);
                                     v->SetDisplayId(11686);
                                     v->DespawnOrUnsummon(1000);
                                     b->CastSpell(b, SPELL_SAC_HOLY_BOMB_EXPLOSION, true);
                                     b->CastSpell(b, SPELL_SAC_SUMMON_GO_2, true);
                                     if (Unit* vb = c->GetVehicleBase())
{
                                         if (Unit* pass = vb->GetVehicleKit()->GetPassenger(0))
                                             if (pass->GetTypeId() == TYPEID_UNIT)
                                                 pass->ToCreature()->DespawnOrUnsummon(1);
                                         vb->RemoveAllAuras();
                                         vb->ToCreature()->DespawnOrUnsummon(1);
                                     }
                                     c->ToCreature()->DespawnOrUnsummon(1);
                                 }
                     }
                     break;
                 case 18: // summon vegard
                     me->CastSpell(me, SPELL_SAC_SUMMON_VEGARD_SKELETON, true);
                     break;
             }
         }
References Unit::CastSpell(), CleanAll(), WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, Unit::GetMotionMaster(), Vehicle::GetPassenger(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleBase(), Unit::GetVehicleKit(), GO_FLAG_NOT_SELECTABLE, GO_SAC_LIGHTS_VENGEANCE_1, CreatureAI::me, MotionMaster::MoveSplinePath(), NPC_SAC_LIGHTS_VENGEANCE, NPC_SAC_LIGHTS_VENGEANCE_BUNNY, NPC_SAC_LIGHTS_VENGEANCE_VEH_1, NPC_SAC_LIGHTS_VENGEANCE_VEH_2, NPC_SAC_VEGARD_1, playerGUID, Unit::RemoveAllAuras(), Reset(), Unit::SetVisible(), SPELL_SAC_BLUE_EXPLOSION, SPELL_SAC_HOLY_BOMB_EXPLOSION, SPELL_SAC_HOLY_BOMB_VISUAL, SPELL_SAC_HOLY_ZONE_AURA, SPELL_SAC_KILL_VEGARD, SPELL_SAC_LK_DESPAWN_ANIM, SPELL_SAC_REPEL_HAMMER, SPELL_SAC_SHIELD_OF_THE_LICH_KING, SPELL_SAC_STUN, SPELL_SAC_SUMMON_GHOULS_AURA, SPELL_SAC_SUMMON_GO_1, SPELL_SAC_SUMMON_GO_2, SPELL_SAC_SUMMON_VEGARD_SKELETON, SPELL_SAC_VEGARD_SUMMON_GHOULS_AURA, SPELL_SAC_VEHICLE_CONTROL_AURA, SPELL_SAC_ZAP_GHOULS_AURA, SPELL_SAC_ZAP_PLAYER, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_MANUAL_DESPAWN, TYPEID_UNIT, and Cell::VisitGridObjects().
Member Data Documentation
events
EventMap npc_q24545_lich_king::npc_q24545_lich_kingAI::events
Definition at line 764 of file zone_dragonblight.cpp.
playerGUID
ObjectGuid npc_q24545_lich_king::npc_q24545_lich_kingAI::playerGUID
Definition at line 766 of file zone_dragonblight.cpp.
Referenced by Reset(), SetData(), SetGUID(), and UpdateAI().
summons
SummonList npc_q24545_lich_king::npc_q24545_lich_kingAI::summons
Definition at line 765 of file zone_dragonblight.cpp.
Referenced by JustSummoned(), Reset(), and SummonedCreatureDespawn().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp