Azerotcore-wotlk: G3D::Vector4int8 Class Reference
G3D::Vector4int8 Class Reference
#include <Vector4int8.h>
Public Member Functions
Vector4int8 ()
Vector4int8 (const Vector4 &source)
Vector4int8 (const Vector3 &source, int8 w)
Vector4int8 (int8 x, int8 y, int8 z, int8 w)
Vector4int8 (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
operator int8 * ()
operator const int8 * () const
int8 & operator[] (int i)
const int8 & operator[] (int i) const
Vector4int8 & operator= (const Vector4int8 &other)
bool operator== (const Vector4int8 &other) const
bool operator!= (const Vector4int8 &other) const
unsigned int hashCode () const
Public Attributes
int8 x
int8 y
int8 z
int8 w
Private Member Functions
bool operator< (const Vector4int8 &) const
bool operator> (const Vector4int8 &) const
bool operator<= (const Vector4int8 &) const
bool operator>= (const Vector4int8 &) const
uint32 & asInt32 ()
const uint32 & asInt32 () const
Detailed Description
Homogeneous vector stored efficiently in four signed int8s.
Definition at line 30 of file Vector4int8.h.
Constructor & Destructor Documentation
Vector4int8() [1/5]
G3D::Vector4int8::Vector4int8 () inline
Definition at line 51 of file Vector4int8.h.
 : x(0), y(0), z(0), w(0) {}
Vector4int8() [2/5]
G3D::Vector4int8::Vector4int8 (const Vector4 & source) explicit
Multiplies the source by 127 and clamps to (-128, 127) when converting
Definition at line 25 of file Vector4int8.cpp.
{
     x = iClamp(iRound(source.x), -128, 127);
     y = iClamp(iRound(source.y), -128, 127);
     z = iClamp(iRound(source.z), -128, 127);
     w = iClamp(iRound(source.w), -128, 127);
 }
References G3D::iClamp(), G3D::iRound(), G3D::Vector4::w, w, G3D::Vector4::x, x, G3D::Vector4::y, y, G3D::Vector4::z, and z.
Vector4int8() [3/5]
G3D::Vector4int8::Vector4int8 (const Vector3 & source, int8 w) explicit
Multiplies the source by 127 and clamps to (-128, 127) when converting
Definition at line 32 of file Vector4int8.cpp.
                                                       : w(w) {
     x = iClamp(iRound(source.x), -128, 127);
     y = iClamp(iRound(source.y), -128, 127);
     z = iClamp(iRound(source.z), -128, 127);
 }
References G3D::iClamp(), G3D::iRound(), G3D::Vector3::x, x, G3D::Vector3::y, y, G3D::Vector3::z, and z.
Vector4int8() [4/5]
G3D::Vector4int8::Vector4int8 (int8 x, int8 y, int8 z, int8 w) inline
Definition at line 59 of file Vector4int8.h.
 : x(x), y(y), z(z), w(w) {}
Vector4int8() [5/5]
G3D::Vector4int8::Vector4int8 (class BinaryInput & b) explicit
Definition at line 38 of file Vector4int8.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Member Function Documentation
asInt32() [1/2]
uint32& G3D::Vector4int8::asInt32 () inline private
For fast operations, treat this packed data structure as an int32
Definition at line 41 of file Vector4int8.h.
{
         return *reinterpret_cast<uint32*>(this);
     }
Referenced by hashCode(), operator=(), and operator==().
asInt32() [2/2]
const uint32& G3D::Vector4int8::asInt32 () const inline private
Definition at line 45 of file Vector4int8.h.
{
         return *reinterpret_cast<const uint32*>(this);
     }
deserialize()
void G3D::Vector4int8::deserialize (class BinaryInput & b)
Definition at line 50 of file Vector4int8.cpp.
{
     x = b.readInt8();
     y = b.readInt8();
     z = b.readInt8();
     w = b.readInt8();
 }
References b, w, x, y, and z.
Referenced by Vector4int8().
hashCode()
unsigned int G3D::Vector4int8::hashCode () const inline
Definition at line 105 of file Vector4int8.h.
{
         return asInt32();
     }
References asInt32().
operator const int8 *()
G3D::Vector4int8::operator const int8 * () const inline
Definition at line 72 of file Vector4int8.h.
{
         return reinterpret_cast<const int8*>(this);
     }
operator int8 *()
G3D::Vector4int8::operator int8 * () inline
Definition at line 68 of file Vector4int8.h.
{
         return reinterpret_cast<int8*>(this);
     }
operator!=()
bool G3D::Vector4int8::operator!= (const Vector4int8 & other) const inline
Definition at line 101 of file Vector4int8.h.
{
         return ! (*this == other);
     }
operator<()
bool G3D::Vector4int8::operator< (const Vector4int8 &) const private
operator<=()
bool G3D::Vector4int8::operator<= (const Vector4int8 &) const private
operator=()
Vector4int8& G3D::Vector4int8::operator= (const Vector4int8 & other) inline
Definition at line 92 of file Vector4int8.h.
{
         asInt32() = other.asInt32();
         return *this;
     }
References asInt32().
operator==()
bool G3D::Vector4int8::operator== (const Vector4int8 & other) const inline
Definition at line 97 of file Vector4int8.h.
{
         return asInt32() == other.asInt32();
     }
References asInt32().
operator>()
bool G3D::Vector4int8::operator> (const Vector4int8 &) const private
operator>=()
bool G3D::Vector4int8::operator>= (const Vector4int8 &) const private
operator[]() [1/2]
int8& G3D::Vector4int8::operator[] (int i) inline
Definition at line 81 of file Vector4int8.h.
{
         debugAssert(i >= 0 && i <= 4);
         return ((int8*)this)[i];
     }
References debugAssert.
operator[]() [2/2]
const int8& G3D::Vector4int8::operator[] (int i) const inline
Definition at line 86 of file Vector4int8.h.
{
         debugAssert(i >= 0 && i <= 4);
         return ((const int8*)this)[i];
     }
References debugAssert.
serialize()
void G3D::Vector4int8::serialize (class BinaryOutput & b) const
Definition at line 42 of file Vector4int8.cpp.
{
     // Intentionally write individual bytes to avoid endian issues
     b.writeInt8(x);
     b.writeInt8(y);
     b.writeInt8(z);
     b.writeInt8(w);
 }
References b, w, x, y, and z.
Member Data Documentation
w
int8 G3D::Vector4int8::w
Definition at line 66 of file Vector4int8.h.
Referenced by deserialize(), serialize(), and Vector4int8().
x
int8 G3D::Vector4int8::x
Definition at line 66 of file Vector4int8.h.
Referenced by deserialize(), serialize(), and Vector4int8().
y
int8 G3D::Vector4int8::y
Definition at line 66 of file Vector4int8.h.
Referenced by deserialize(), serialize(), and Vector4int8().
z
int8 G3D::Vector4int8::z
Definition at line 66 of file Vector4int8.h.
Referenced by deserialize(), serialize(), and Vector4int8().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Vector4int8.h
deps/g3dlite/source/Vector4int8.cpp