Azerotcore-wotlk: npc_cos_chromie_middle Class Reference
npc_cos_chromie_middle Class Reference
Public Member Functions
npc_cos_chromie_middle ()
bool OnQuestAccept (Player *, Creature *creature, const Quest *pQuest) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1455 of file culling_of_stratholme.cpp.
Constructor & Destructor Documentation
npc_cos_chromie_middle()
npc_cos_chromie_middle::npc_cos_chromie_middle () inline
Definition at line 1458 of file culling_of_stratholme.cpp.
 : CreatureScript("npc_cos_chromie_middle") { }
Member Function Documentation
OnGossipHello()
bool npc_cos_chromie_middle::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1482 of file culling_of_stratholme.cpp.
     {
         if (creature->IsQuestGiver())
         {
             player->PrepareQuestMenu(creature->GetGUID());
             player->SendPreparedQuest(creature->GetGUID());
         }
         if (!creature->GetInstanceScript() || creature->GetInstanceScript()->GetData(DATA_ARTHAS_EVENT) != COS_PROGRESS_CRATES_FOUND)
             return true;
         return false;
     }
References COS_PROGRESS_CRATES_FOUND, DATA_ARTHAS_EVENT, ZoneScript::GetData(), Object::GetGUID(), WorldObject::GetInstanceScript(), Unit::IsQuestGiver(), Player::PrepareQuestMenu(), and Player::SendPreparedQuest().
OnGossipSelect()
bool npc_cos_chromie_middle::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1470 of file culling_of_stratholme.cpp.
     {
         if (!creature->GetInstanceScript() || creature->GetInstanceScript()->GetData(DATA_ARTHAS_EVENT) != COS_PROGRESS_CRATES_FOUND)
             return true;
         // We can start event:)
         if (player->PlayerTalkClass->GetGossipMenu().GetMenuId() == 9612)
             creature->GetInstanceScript()->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_START_INTRO);
         return false;
     }
References COS_PROGRESS_CRATES_FOUND, COS_PROGRESS_START_INTRO, DATA_ARTHAS_EVENT, ZoneScript::GetData(), PlayerMenu::GetGossipMenu(), WorldObject::GetInstanceScript(), GossipMenu::GetMenuId(), Player::PlayerTalkClass, and ZoneScript::SetData().
OnQuestAccept()
bool npc_cos_chromie_middle::OnQuestAccept (Player * , Creature * creature, const Quest * pQuest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1460 of file culling_of_stratholme.cpp.
     {
         if (pQuest->GetQuestId() == QUEST_A_ROYAL_ESCORT)
             if (InstanceScript* pInstance = creature->GetInstanceScript())
                 if (pInstance->GetData(DATA_ARTHAS_EVENT) == COS_PROGRESS_CRATES_FOUND)
                     pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_START_INTRO);
         return true;
     }
References COS_PROGRESS_CRATES_FOUND, COS_PROGRESS_START_INTRO, DATA_ARTHAS_EVENT, WorldObject::GetInstanceScript(), Quest::GetQuestId(), and QUEST_A_ROYAL_ESCORT.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp