Azerotcore-wotlk: File Instrumentation
File Instrumentation
Instrumentation Interface
Classes
struct st_mysql_file
Macros
#define mysql_file_fgets(P1, P2, F) inline_mysql_file_fgets(P1, P2, F)
#define mysql_file_fgetc(F) inline_mysql_file_fgetc(F)
#define mysql_file_fputs(P1, F) inline_mysql_file_fputs(P1, F)
#define mysql_file_fputc(P1, F) inline_mysql_file_fputc(P1, F)
#define mysql_file_fprintf inline_mysql_file_fprintf
#define mysql_file_vfprintf(F, P1, P2) inline_mysql_file_vfprintf(F, P1, P2)
#define mysql_file_fflush(F) inline_mysql_file_fflush(F)
#define mysql_file_feof(F) inline_mysql_file_feof(F)
#define mysql_file_fstat(FN, S, FL) inline_mysql_file_fstat(FN, S, FL)
#define mysql_file_stat(K, FN, S, FL) inline_mysql_file_stat(FN, S, FL)
#define mysql_file_chsize(F, P1, P2, P3) inline_mysql_file_chsize(F, P1, P2, P3)
#define mysql_file_fopen(K, N, F1, F2) inline_mysql_file_fopen(N, F1, F2)
#define mysql_file_fclose(FD, FL) inline_mysql_file_fclose(FD, FL)
#define mysql_file_fread(FD, P1, P2, P3) inline_mysql_file_fread(FD, P1, P2, P3)
#define mysql_file_fwrite(FD, P1, P2, P3) inline_mysql_file_fwrite(FD, P1, P2, P3)
#define mysql_file_fseek(FD, P, W, F) inline_mysql_file_fseek(FD, P, W, F)
#define mysql_file_ftell(FD, F) inline_mysql_file_ftell(FD, F)
#define mysql_file_create(K, N, F1, F2, F3) inline_mysql_file_create(N, F1, F2, F3)
#define mysql_file_create_temp(K, T, D, P, M, F) inline_mysql_file_create_temp(T, D, P, M, F)
#define mysql_file_open(K, N, F1, F2) inline_mysql_file_open(N, F1, F2)
#define mysql_file_close(FD, F) inline_mysql_file_close(FD, F)
#define mysql_file_read(FD, B, S, F) inline_mysql_file_read(FD, B, S, F)
#define mysql_file_write(FD, B, S, F) inline_mysql_file_write(FD, B, S, F)
#define mysql_file_pread(FD, B, S, O, F) inline_mysql_file_pread(FD, B, S, O, F)
#define mysql_file_pwrite(FD, B, S, O, F) inline_mysql_file_pwrite(FD, B, S, O, F)
#define mysql_file_seek(FD, P, W, F) inline_mysql_file_seek(FD, P, W, F)
#define mysql_file_tell(FD, F) inline_mysql_file_tell(FD, F)
#define mysql_file_delete(K, P1, P2) inline_mysql_file_delete(P1, P2)
#define mysql_file_rename(K, P1, P2, P3) inline_mysql_file_rename(P1, P2, P3)
#define mysql_file_create_with_symlink(K, P1, P2, P3, P4, P5) inline_mysql_file_create_with_symlink(P1, P2, P3, P4, P5)
#define mysql_file_delete_with_symlink(K, P1, P2) inline_mysql_file_delete_with_symlink(P1, P2)
#define mysql_file_rename_with_symlink(K, P1, P2, P3) inline_mysql_file_rename_with_symlink(P1, P2, P3)
#define mysql_file_sync(P1, P2) inline_mysql_file_sync(P1, P2)
Typedefs
typedef struct st_mysql_file MYSQL_FILE
Functions
static char * inline_mysql_file_fgets (char *str, int size, MYSQL_FILE *file)
static int inline_mysql_file_fgetc (MYSQL_FILE *file)
static int inline_mysql_file_fputs (const char *str, MYSQL_FILE *file)
static int inline_mysql_file_fputc (char c, MYSQL_FILE *file)
static int inline_mysql_file_fprintf (MYSQL_FILE *file, const char *format,...)
static int inline_mysql_file_vfprintf (MYSQL_FILE *file, const char *format, va_list args)
static int inline_mysql_file_fflush (MYSQL_FILE *file)
static int inline_mysql_file_feof (MYSQL_FILE *file)
static int inline_mysql_file_fstat (int filenr, MY_STAT *stat_area, myf flags)
static MY_STAT * inline_mysql_file_stat (const char *path, MY_STAT *stat_area, myf flags)
static int inline_mysql_file_chsize (File file, my_off_t newlength, int filler, myf flags)
static MYSQL_FILE * inline_mysql_file_fopen (const char *filename, int flags, myf myFlags)
static int inline_mysql_file_fclose (MYSQL_FILE *file, myf flags)
static size_t inline_mysql_file_fread (MYSQL_FILE *file, uchar *buffer, size_t count, myf flags)
static size_t inline_mysql_file_fwrite (MYSQL_FILE *file, const uchar *buffer, size_t count, myf flags)
static my_off_t inline_mysql_file_fseek (MYSQL_FILE *file, my_off_t pos, int whence, myf flags)
static my_off_t inline_mysql_file_ftell (MYSQL_FILE *file, myf flags)
static File inline_mysql_file_create (const char *filename, int create_flags, int access_flags, myf myFlags)
static File inline_mysql_file_create_temp (char *to, const char *dir, const char *pfx, int mode, myf myFlags)
static File inline_mysql_file_open (const char *filename, int flags, myf myFlags)
static int inline_mysql_file_close (File file, myf flags)
static size_t inline_mysql_file_read (File file, uchar *buffer, size_t count, myf flags)
static size_t inline_mysql_file_write (File file, const uchar *buffer, size_t count, myf flags)
static size_t inline_mysql_file_pread (File file, uchar *buffer, size_t count, my_off_t offset, myf flags)
static size_t inline_mysql_file_pwrite (File file, const uchar *buffer, size_t count, my_off_t offset, myf flags)
static my_off_t inline_mysql_file_seek (File file, my_off_t pos, int whence, myf flags)
static my_off_t inline_mysql_file_tell (File file, myf flags)
static int inline_mysql_file_delete (const char *name, myf flags)
static int inline_mysql_file_rename (const char *from, const char *to, myf flags)
static File inline_mysql_file_create_with_symlink (const char *linkname, const char *filename, int create_flags, int access_flags, myf flags)
static int inline_mysql_file_delete_with_symlink (const char *name, myf flags)
static int inline_mysql_file_rename_with_symlink (const char *from, const char *to, myf flags)
static int inline_mysql_file_sync (File fd, myf flags)
Detailed Description
Macro Definition Documentation
mysql_file_chsize
#define mysql_file_chsize (F, P1, P2, P3) inline_mysql_file_chsize(F, P1, P2, P3)
Instrumented chsize. mysql_file_chsize is a replacement for my_chsize.
Definition at line 177 of file mysql_file.h.
mysql_file_close
#define mysql_file_close (FD, F) inline_mysql_file_close(FD, F)
Instrumented close. mysql_file_close is a replacement for my_close.
Definition at line 314 of file mysql_file.h.
mysql_file_create
#define mysql_file_create (K, N, F1, F2, F3) inline_mysql_file_create(N, F1, F2, F3)
Instrumented create. mysql_file_create is a replacement for my_create.
Definition at line 275 of file mysql_file.h.
mysql_file_create_temp
#define mysql_file_create_temp (K, T, D, P, M, F) inline_mysql_file_create_temp(T, D, P, M, F)
Instrumented create_temp_file. mysql_file_create_temp is a replacement for create_temp_file.
Definition at line 288 of file mysql_file.h.
mysql_file_create_with_symlink
#define mysql_file_create_with_symlink (K, P1, P2, P3, P4, P5) inline_mysql_file_create_with_symlink(P1, P2, P3, P4, P5)
Instrumented create with symbolic link. mysql_file_create_with_symlink is a replacement for my_create_with_symlink.
Definition at line 433 of file mysql_file.h.
mysql_file_delete
#define mysql_file_delete (K, P1, P2) inline_mysql_file_delete(P1, P2)
Instrumented delete. mysql_file_delete is a replacement for my_delete.
Definition at line 405 of file mysql_file.h.
mysql_file_delete_with_symlink
#define mysql_file_delete_with_symlink (K, P1, P2) inline_mysql_file_delete_with_symlink(P1, P2)
Instrumented delete with symbolic link. mysql_file_delete_with_symlink is a replacement for my_delete_with_symlink.
Definition at line 447 of file mysql_file.h.
mysql_file_fclose
#define mysql_file_fclose (FD, FL) inline_mysql_file_fclose(FD, FL)
Instrumented fclose. mysql_file_fclose is a replacement for my_fclose. Without the instrumentation, this call will have the same behavior as the undocumented and possibly platform specific my_fclose(NULL, ...) behavior. With the instrumentation, mysql_fclose(NULL, ...) will safely return 0, which is an extension compared to my_fclose and is therefore compliant. mysql_fclose is on purpose not implementing
DBUG_ASSERT(file != NULL)
, since doing so could introduce regressions.
Definition at line 210 of file mysql_file.h.
mysql_file_feof
#define mysql_file_feof (F) inline_mysql_file_feof(F)
Instrumented feof. mysql_file_feof is a replacement for feof.
Definition at line 140 of file mysql_file.h.
mysql_file_fflush
#define mysql_file_fflush (F) inline_mysql_file_fflush(F)
Instrumented fflush. mysql_file_fflush is a replacement for fflush.
Definition at line 131 of file mysql_file.h.
mysql_file_fgetc
#define mysql_file_fgetc (F) inline_mysql_file_fgetc(F)
Instrumented fgetc. mysql_file_fgetc is a replacement for fgetc.
Definition at line 73 of file mysql_file.h.
mysql_file_fgets
#define mysql_file_fgets (P1, P2, F) inline_mysql_file_fgets(P1, P2, F)
Instrumented fgets. mysql_file_fgets is a replacement for fgets.
Definition at line 61 of file mysql_file.h.
mysql_file_fopen
#define mysql_file_fopen (K, N, F1, F2) inline_mysql_file_fopen(N, F1, F2)
Instrumented fopen. mysql_file_fopen is a replacement for my_fopen.
Definition at line 190 of file mysql_file.h.
mysql_file_fprintf
#define mysql_file_fprintf inline_mysql_file_fprintf
Instrumented fprintf. mysql_file_fprintf is a replacement for fprintf.
Definition at line 107 of file mysql_file.h.
mysql_file_fputc
#define mysql_file_fputc (P1, F) inline_mysql_file_fputc(P1, F)
Instrumented fputc. mysql_file_fputc is a replacement for fputc.
Definition at line 98 of file mysql_file.h.
mysql_file_fputs
#define mysql_file_fputs (P1, F) inline_mysql_file_fputs(P1, F)
Instrumented fputs. mysql_file_fputs is a replacement for fputs.
Definition at line 85 of file mysql_file.h.
mysql_file_fread
#define mysql_file_fread (FD, P1, P2, P3) inline_mysql_file_fread(FD, P1, P2, P3)
Instrumented fread. mysql_file_fread is a replacement for my_fread.
Definition at line 223 of file mysql_file.h.
mysql_file_fseek
#define mysql_file_fseek (FD, P, W, F) inline_mysql_file_fseek(FD, P, W, F)
Instrumented fseek. mysql_file_fseek is a replacement for my_fseek.
Definition at line 249 of file mysql_file.h.
mysql_file_fstat
#define mysql_file_fstat (FN, S, FL) inline_mysql_file_fstat(FN, S, FL)
Instrumented fstat. mysql_file_fstat is a replacement for my_fstat.
Definition at line 151 of file mysql_file.h.
mysql_file_ftell
#define mysql_file_ftell (FD, F) inline_mysql_file_ftell(FD, F)
Instrumented ftell. mysql_file_ftell is a replacement for my_ftell.
Definition at line 262 of file mysql_file.h.
mysql_file_fwrite
#define mysql_file_fwrite (FD, P1, P2, P3) inline_mysql_file_fwrite(FD, P1, P2, P3)
Instrumented fwrite. mysql_file_fwrite is a replacement for my_fwrite.
Definition at line 236 of file mysql_file.h.
mysql_file_open
#define mysql_file_open (K, N, F1, F2) inline_mysql_file_open(N, F1, F2)
Instrumented open. mysql_file_open is a replacement for my_open.
Definition at line 301 of file mysql_file.h.
mysql_file_pread
#define mysql_file_pread (FD, B, S, O, F) inline_mysql_file_pread(FD, B, S, O, F)
Instrumented pread. mysql_pread is a replacement for my_pread.
Definition at line 353 of file mysql_file.h.
mysql_file_pwrite
#define mysql_file_pwrite (FD, B, S, O, F) inline_mysql_file_pwrite(FD, B, S, O, F)
Instrumented pwrite. mysql_file_pwrite is a replacement for my_pwrite.
Definition at line 366 of file mysql_file.h.
mysql_file_read
#define mysql_file_read (FD, B, S, F) inline_mysql_file_read(FD, B, S, F)
Instrumented read. mysql_read is a replacement for my_read.
Definition at line 327 of file mysql_file.h.
mysql_file_rename
#define mysql_file_rename (K, P1, P2, P3) inline_mysql_file_rename(P1, P2, P3)
Instrumented rename. mysql_file_rename is a replacement for my_rename.
Definition at line 418 of file mysql_file.h.
mysql_file_rename_with_symlink
#define mysql_file_rename_with_symlink (K, P1, P2, P3) inline_mysql_file_rename_with_symlink(P1, P2, P3)
Instrumented rename with symbolic link. mysql_file_rename_with_symlink is a replacement for my_rename_with_symlink.
Definition at line 461 of file mysql_file.h.
mysql_file_seek
#define mysql_file_seek (FD, P, W, F) inline_mysql_file_seek(FD, P, W, F)
Instrumented seek. mysql_file_seek is a replacement for my_seek.
Definition at line 379 of file mysql_file.h.
mysql_file_stat
#define mysql_file_stat (K, FN, S, FL) inline_mysql_file_stat(FN, S, FL)
Instrumented stat. mysql_file_stat is a replacement for my_stat.
Definition at line 164 of file mysql_file.h.
mysql_file_sync
#define mysql_file_sync (P1, P2) inline_mysql_file_sync(P1, P2)
Instrumented file sync. mysql_file_sync is a replacement for my_sync.
Definition at line 474 of file mysql_file.h.
mysql_file_tell
#define mysql_file_tell (FD, F) inline_mysql_file_tell(FD, F)
Instrumented tell. mysql_file_tell is a replacement for my_tell.
Definition at line 392 of file mysql_file.h.
mysql_file_vfprintf
#define mysql_file_vfprintf (F, P1, P2) inline_mysql_file_vfprintf(F, P1, P2)
Instrumented vfprintf. mysql_file_vfprintf is a replacement for vfprintf.
Definition at line 118 of file mysql_file.h.
mysql_file_write
#define mysql_file_write (FD, B, S, F) inline_mysql_file_write(FD, B, S, F)
Instrumented write. mysql_file_write is a replacement for my_write.
Definition at line 340 of file mysql_file.h.
Typedef Documentation
MYSQL_FILE
typedef struct st_mysql_file MYSQL_FILE
Type of an instrumented file. MYSQL_FILE is a drop-in replacement for FILE.
See also
mysql_file_open
Definition at line 1 of file mysql_file.h.
Function Documentation
inline_mysql_file_chsize()
static int inline_mysql_file_chsize (File file, my_off_t newlength, int filler, myf flags) inline static
Definition at line 758 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file,
                                                           PSI_FILE_CHSIZE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) newlength, src_file,
                                   src_line);
   }
 #endif
   result= my_chsize(file, newlength, filler, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) newlength);
 #endif
   return result;
 }
References mpq::file, likely, my_chsize(), NULL, and PSI_server.
inline_mysql_file_close()
static int inline_mysql_file_close (File file, myf flags) inline static
Definition at line 1055 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file,
                                                           PSI_FILE_CLOSE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_close(file, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, my_close(), NULL, and PSI_server.
inline_mysql_file_create()
static File inline_mysql_file_create (const char * filename, int create_flags, int access_flags, myf myFlags) inline static
Definition at line 980 of file mysql_file.h.
 {
   File file;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_CREATE,
                                                     filename, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_open_wait(locker, src_file, src_line);
   }
 #endif
   file= my_create(filename, create_flags, access_flags, myFlags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_open_wait_and_bind_to_descriptor(locker, file);
 #endif
   return file;
 }
References mpq::file, likely, my_create(), NULL, and PSI_server.
inline_mysql_file_create_temp()
static File inline_mysql_file_create_temp (char * to, const char * dir, const char * pfx, int mode, myf myFlags) inline static
Definition at line 1007 of file mysql_file.h.
 {
   File file;
   /*
     TODO: This event is instrumented, but not timed.
     The problem is that the file name is now known
     before the create_temp_file call.
   */
   file= create_temp_file(to, dir, pfx, mode, myFlags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server != NULL))
     PSI_server->create_file(key, to, file);
 #endif
   return file;
 }
References create_temp_file(), mpq::file, likely, NULL, and PSI_server.
inline_mysql_file_create_with_symlink()
static File inline_mysql_file_create_with_symlink (const char * linkname, const char * filename, int create_flags, int access_flags, myf flags) inline static
Definition at line 1323 of file mysql_file.h.
 {
   File file;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_CREATE,
                                                     filename, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_open_wait(locker, src_file, src_line);
   }
 #endif
   file= my_create_with_symlink(linkname, filename, create_flags, access_flags,
                                flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_open_wait_and_bind_to_descriptor(locker, file);
 #endif
   return file;
 }
References mpq::file, likely, my_create_with_symlink(), NULL, and PSI_server.
inline_mysql_file_delete()
static int inline_mysql_file_delete (const char * name, myf flags) inline static
Definition at line 1269 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_DELETE,
                                                     name, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_delete(name, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_delete(), name, NULL, and PSI_server.
inline_mysql_file_delete_with_symlink()
static int inline_mysql_file_delete_with_symlink (const char * name, myf flags) inline static
Definition at line 1352 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_DELETE,
                                                     name, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_delete_with_symlink(name, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_delete_with_symlink(), name, NULL, and PSI_server.
inline_mysql_file_fclose()
static int inline_mysql_file_fclose (MYSQL_FILE * file, myf flags) inline static
Definition at line 826 of file mysql_file.h.
 {
   int result= 0;
   if (likely(file != NULL))
   {
 #ifdef HAVE_PSI_INTERFACE
     struct PSI_file_locker *locker= NULL;
     PSI_file_locker_state state;
     DBUG_ASSERT(file != NULL);
     if (likely(PSI_server && file->m_psi))
     {
       locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                         PSI_FILE_STREAM_CLOSE);
       if (likely(locker != NULL))
         PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
     }
 #endif
     result= my_fclose(file->m_file, flags);
 #ifdef HAVE_PSI_INTERFACE
     if (likely(locker != NULL))
       PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
     my_free(file);
   }
   return result;
 }
References DBUG_ASSERT, mpq::file, likely, my_fclose(), my_free(), NULL, and PSI_server.
inline_mysql_file_feof()
static int inline_mysql_file_feof (MYSQL_FILE * file) inline static
Definition at line 696 of file mysql_file.h.
 {
   /* Not instrumented, there is no wait involved */
   return feof(file->m_file);
 }
References mpq::file.
inline_mysql_file_fflush()
static int inline_mysql_file_fflush (MYSQL_FILE * file) inline static
Definition at line 670 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_FLUSH);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= fflush(file->m_file);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, NULL, and PSI_server.
inline_mysql_file_fgetc()
static int inline_mysql_file_fgetc (MYSQL_FILE * file) inline static
Definition at line 529 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_READ);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 1, src_file, src_line);
   }
 #endif
   result= fgetc(file->m_file);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 1);
 #endif
   return result;
 }
References mpq::file, likely, NULL, and PSI_server.
inline_mysql_file_fgets()
static char* inline_mysql_file_fgets (char * str, int size, MYSQL_FILE * file) inline static
Definition at line 502 of file mysql_file.h.
 {
   char *result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_READ);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) size, src_file, src_line);
   }
 #endif
   result= fgets(str, size, file->m_file);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, result ? strlen(result) : 0);
 #endif
   return result;
 }
References mpq::file, likely, NULL, and PSI_server.
inline_mysql_file_fopen()
static MYSQL_FILE* inline_mysql_file_fopen (const char * filename, int flags, myf myFlags) inline static
Definition at line 786 of file mysql_file.h.
 {
   MYSQL_FILE *that;
   that= (MYSQL_FILE*) my_malloc(sizeof(MYSQL_FILE), MYF(MY_WME));
   if (likely(that != NULL))
   {
     that->m_psi= NULL;
     {
 #ifdef HAVE_PSI_INTERFACE
       struct PSI_file_locker *locker= NULL;
       PSI_file_locker_state state;
       if (likely(PSI_server != NULL))
       {
         locker= PSI_server->get_thread_file_name_locker
           (&state, key, PSI_FILE_STREAM_OPEN, filename, that);
         if (likely(locker != NULL))
           that->m_psi= PSI_server->start_file_open_wait(locker, src_file,
                                                         src_line);
       }
 #endif
       that->m_file= my_fopen(filename, flags, myFlags);
 #ifdef HAVE_PSI_INTERFACE
       if (likely(locker != NULL))
         PSI_server->end_file_open_wait(locker);
 #endif
       if (unlikely(that->m_file == NULL))
       {
         my_free(that);
         return NULL;
       }
     }
   }
   return that;
 }
References likely, st_mysql_file::m_file, st_mysql_file::m_psi, my_fopen(), my_free(), my_malloc(), MY_WME, MYF, NULL, PSI_server, and unlikely.
inline_mysql_file_fprintf()
static int inline_mysql_file_fprintf (MYSQL_FILE * file, const char * format, ...) inline static
Definition at line 614 of file mysql_file.h.
 {
   /*
     TODO: figure out how to pass src_file and src_line from the caller.
   */
   int result;
   va_list args;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, __FILE__, __LINE__);
   }
 #endif
   va_start(args, format);
   result= vfprintf(file->m_file, format, args);
   va_end(args);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) result);
 #endif
   return result;
 }
References mpq::file, format(), likely, NULL, PSI_server, and vfprintf().
inline_mysql_file_fputc()
static int inline_mysql_file_fputc (char c, MYSQL_FILE * file) inline static
Definition at line 587 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 1, src_file, src_line);
   }
 #endif
   result= fputc(c, file->m_file);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 1);
 #endif
   return result;
 }
References mpq::c, mpq::file, likely, NULL, and PSI_server.
inline_mysql_file_fputs()
static int inline_mysql_file_fputs (const char * str, MYSQL_FILE * file) inline static
Definition at line 556 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   size_t bytes= 0;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_WRITE);
     if (likely(locker != NULL))
     {
       bytes= str ? strlen(str) : 0;
       PSI_server->start_file_wait(locker, bytes, src_file, src_line);
     }
   }
 #endif
   result= fputs(str, file->m_file);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, bytes);
 #endif
   return result;
 }
References mpq::file, fputs(), likely, NULL, and PSI_server.
inline_mysql_file_fread()
static size_t inline_mysql_file_fread (MYSQL_FILE * file, uchar * buffer, size_t count, myf flags) inline static
Definition at line 858 of file mysql_file.h.
 {
   size_t result= 0;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_READ);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_fread(file->m_file, buffer, count, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_read;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_read= (result == 0) ? count : 0;
     else
       bytes_read= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_read);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, my_fread(), MY_NABP, NULL, and PSI_server.
inline_mysql_file_fseek()
static my_off_t inline_mysql_file_fseek (MYSQL_FILE * file, my_off_t pos, int whence, myf flags) inline static
Definition at line 926 of file mysql_file.h.
 {
   my_off_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_SEEK);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_fseek(file->m_file, pos, whence, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, my_fseek(), NULL, pos(), and PSI_server.
inline_mysql_file_fstat()
static int inline_mysql_file_fstat (int filenr, MY_STAT * stat_area, myf flags) inline static
Definition at line 703 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, filenr,
                                                           PSI_FILE_FSTAT);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_fstat(filenr, stat_area, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_fstat(), NULL, and PSI_server.
inline_mysql_file_ftell()
static my_off_t inline_mysql_file_ftell (MYSQL_FILE * file, myf flags) inline static
Definition at line 953 of file mysql_file.h.
 {
   my_off_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_TELL);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_ftell(file->m_file, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, my_ftell(), NULL, and PSI_server.
inline_mysql_file_fwrite()
static size_t inline_mysql_file_fwrite (MYSQL_FILE * file, const uchar * buffer, size_t count, myf flags) inline static
Definition at line 892 of file mysql_file.h.
 {
   size_t result= 0;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_fwrite(file->m_file, buffer, count, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_written;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_written= (result == 0) ? count : 0;
     else
       bytes_written= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_written);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, my_fwrite(), MY_NABP, NULL, and PSI_server.
inline_mysql_file_open()
static File inline_mysql_file_open (const char * filename, int flags, myf myFlags) inline static
Definition at line 1028 of file mysql_file.h.
 {
   File file;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_OPEN,
                                                     filename, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_open_wait(locker, src_file, src_line);
   }
 #endif
   file= my_open(filename, flags, myFlags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_open_wait_and_bind_to_descriptor(locker, file);
 #endif
   return file;
 }
References mpq::file, likely, my_open(), NULL, and PSI_server.
inline_mysql_file_pread()
static size_t inline_mysql_file_pread (File file, uchar * buffer, size_t count, my_off_t offset, myf flags) inline static
Definition at line 1150 of file mysql_file.h.
 {
   size_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file, PSI_FILE_READ);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_pread(file, buffer, count, offset, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_read;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_read= (result == 0) ? count : 0;
     else
       bytes_read= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_read);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, MY_NABP, my_pread(), NULL, and PSI_server.
inline_mysql_file_pwrite()
static size_t inline_mysql_file_pwrite (File file, const uchar * buffer, size_t count, my_off_t offset, myf flags) inline static
Definition at line 1183 of file mysql_file.h.
 {
   size_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file,
                                                           PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_pwrite(file, buffer, count, offset, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_written;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_written= (result == 0) ? count : 0;
     else
       bytes_written= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_written);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, MY_NABP, my_pwrite(), NULL, and PSI_server.
inline_mysql_file_read()
static size_t inline_mysql_file_read (File file, uchar * buffer, size_t count, myf flags) inline static
Definition at line 1082 of file mysql_file.h.
 {
   size_t result= 0;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file,
                                                           PSI_FILE_READ);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_read(file, buffer, count, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_read;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_read= (result == 0) ? count : 0;
     else
       bytes_read= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_read);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, MY_NABP, my_read, NULL, and PSI_server.
inline_mysql_file_rename()
static int inline_mysql_file_rename (const char * from, const char * to, myf flags) inline static
Definition at line 1296 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_RENAME,
                                                     to, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_rename(from, to, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_rename(), NULL, and PSI_server.
inline_mysql_file_rename_with_symlink()
static int inline_mysql_file_rename_with_symlink (const char * from, const char * to, myf flags) inline static
Definition at line 1379 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state, key, PSI_FILE_RENAME,
                                                     to, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_rename_with_symlink(from, to, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_rename_with_symlink(), NULL, and PSI_server.
inline_mysql_file_seek()
static my_off_t inline_mysql_file_seek (File file, my_off_t pos, int whence, myf flags) inline static
Definition at line 1217 of file mysql_file.h.
 {
   my_off_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file, PSI_FILE_SEEK);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_seek(file, pos, whence, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, my_seek(), NULL, pos(), and PSI_server.
inline_mysql_file_stat()
static MY_STAT* inline_mysql_file_stat (const char * path, MY_STAT * stat_area, myf flags) inline static
Definition at line 730 of file mysql_file.h.
 {
   MY_STAT *result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_name_locker(&state,
                                                     key, PSI_FILE_STAT,
                                                     path, &locker);
     if (likely(locker != NULL))
       PSI_server->start_file_open_wait(locker, src_file, src_line);
   }
 #endif
   result= my_stat(path, stat_area, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, MY_STAT, my_stat(), NULL, and PSI_server.
inline_mysql_file_sync()
static int inline_mysql_file_sync (File fd, myf flags) inline static
Definition at line 1406 of file mysql_file.h.
 {
   int result= 0;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, fd, PSI_FILE_SYNC);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_sync(fd, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References likely, my_sync(), NULL, and PSI_server.
inline_mysql_file_tell()
static my_off_t inline_mysql_file_tell (File file, myf flags) inline static
Definition at line 1243 of file mysql_file.h.
 {
   my_off_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file, PSI_FILE_TELL);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= my_tell(file, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) 0);
 #endif
   return result;
 }
References mpq::file, likely, my_tell(), NULL, and PSI_server.
inline_mysql_file_vfprintf()
static int inline_mysql_file_vfprintf (MYSQL_FILE * file, const char * format, va_list args) inline static
Definition at line 643 of file mysql_file.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server && file->m_psi))
   {
     locker= PSI_server->get_thread_file_stream_locker(&state, file->m_psi,
                                                       PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, (size_t) 0, src_file, src_line);
   }
 #endif
   result= vfprintf(file->m_file, format, args);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_file_wait(locker, (size_t) result);
 #endif
   return result;
 }
References mpq::file, format(), likely, NULL, PSI_server, and vfprintf().
inline_mysql_file_write()
static size_t inline_mysql_file_write (File file, const uchar * buffer, size_t count, myf flags) inline static
Definition at line 1116 of file mysql_file.h.
 {
   size_t result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_file_locker *locker= NULL;
   PSI_file_locker_state state;
   if (likely(PSI_server != NULL))
   {
     locker= PSI_server->get_thread_file_descriptor_locker(&state, file,
                                                           PSI_FILE_WRITE);
     if (likely(locker != NULL))
       PSI_server->start_file_wait(locker, count, src_file, src_line);
   }
 #endif
   result= my_write(file, buffer, count, flags);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
   {
     size_t bytes_written;
     if (flags & (MY_NABP | MY_FNABP))
       bytes_written= (result == 0) ? count : 0;
     else
       bytes_written= (result != MY_FILE_ERROR) ? result : 0;
     PSI_server->end_file_wait(locker, bytes_written);
   }
 #endif
   return result;
 }
References count(), mpq::file, likely, MY_FILE_ERROR, MY_FNABP, MY_NABP, my_write, NULL, and PSI_server.