Azerotcore-wotlk: boss_veklor::boss_veklorAI Struct Reference
boss_veklor::boss_veklorAI Struct Reference
Public Member Functions
bool IAmVeklor () override
boss_veklorAI (Creature *creature)
void Reset () override
void CastSpellOnBug (Creature *target) override
void UpdateAI (uint32 diff) override
void AttackStart (Unit *who) override
Public Member Functions inherited from boss_twinemperorsAI
boss_twinemperorsAI (Creature *creature)
void TwinReset ()
Creature * GetOtherBoss ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterCombat (Unit *who) override
void SpellHit (Unit *caster, const SpellInfo *entry) override
void TryHealBrother (uint32 diff)
void TeleportToMyBrother ()
void SetAfterTeleport ()
bool TryActivateAfterTTelep (uint32 diff)
void MoveInLineOfSight (Unit *who) override
Creature * RespawnNearbyBugsAndGetOne ()
void HandleBugs (uint32 diff)
void CheckEnrage (uint32 diff)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 ShadowBolt_Timer
uint32 Blizzard_Timer
uint32 ArcaneBurst_Timer
uint32 Scorpions_Timer
int Rand
int RandX
Creature * Summoned
Public Attributes inherited from boss_twinemperorsAI
InstanceScript * instance
uint32 Heal_Timer
uint32 Teleport_Timer
bool AfterTeleport
uint32 AfterTeleportTimer
bool DontYellWhenDead
uint32 Abuse_Bug_Timer
uint32 BugsTimer
bool tspellcast
uint32 EnrageTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 478 of file boss_twinemperors.cpp.
Constructor & Destructor Documentation
boss_veklorAI()
boss_veklor::boss_veklorAI::boss_veklorAI (Creature * creature) inline
Definition at line 481 of file boss_twinemperors.cpp.
 : boss_twinemperorsAI(creature) { }
Member Function Documentation
AttackStart()
void boss_veklor::boss_veklorAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 577 of file boss_twinemperors.cpp.
         {
             if (!who)
                 return;
             if (who->isTargetableForAttack())
             {
                 // VL doesn't melee
                 if (me->Attack(who, false))
                 {
                     me->GetMotionMaster()->MoveChase(who, VEKLOR_DIST, 0);
                     me->AddThreat(who, 0.0f);
                 }
             }
         }
References Unit::AddThreat(), Unit::Attack(), Unit::GetMotionMaster(), Unit::isTargetableForAttack(), ScriptedAI::me, MotionMaster::MoveChase(), and VEKLOR_DIST.
CastSpellOnBug()
void boss_veklor::boss_veklorAI::CastSpellOnBug (Creature * target) inline override virtual
Implements boss_twinemperorsAI.
Definition at line 504 of file boss_twinemperors.cpp.
         {
             target->SetFaction(FACTION_MONSTER);
             target->AddAura(SPELL_EXPLODEBUG, target);
             target->SetFullHealth();
         }
References Unit::AddAura(), FACTION_MONSTER, Unit::SetFaction(), Unit::SetFullHealth(), and SPELL_EXPLODEBUG.
IAmVeklor()
bool boss_veklor::boss_veklorAI::IAmVeklor () inline override virtual
Implements boss_twinemperorsAI.
Definition at line 480 of file boss_twinemperors.cpp.
 {return true;}
Reset()
void boss_veklor::boss_veklorAI::Reset () inline override virtual
Implements boss_twinemperorsAI.
Definition at line 492 of file boss_twinemperors.cpp.
         {
             TwinReset();
             ShadowBolt_Timer = 0;
             Blizzard_Timer = urand(15000, 20000);
             ArcaneBurst_Timer = 1000;
             Scorpions_Timer = urand(7000, 14000);
             //Added. Can be removed if its included in DB.
             me->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
         }
References Unit::ApplySpellImmune(), ArcaneBurst_Timer, Blizzard_Timer, IMMUNITY_DAMAGE, ScriptedAI::me, Scorpions_Timer, ShadowBolt_Timer, SPELL_SCHOOL_MASK_NORMAL, boss_twinemperorsAI::TwinReset(), and urand().
UpdateAI()
void boss_veklor::boss_veklorAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 511 of file boss_twinemperors.cpp.
         {
             //Return since we have no target
             if (!UpdateVictim())
                 return;
             // reset arcane burst after teleport - we need to do this because
             // when VL jumps to VN's location there will be a warrior who will get only 2s to run away
             // which is almost impossible
             if (AfterTeleport)
                 ArcaneBurst_Timer = 5000;
             if (!TryActivateAfterTTelep(diff))
                 return;
             //ShadowBolt_Timer
             if (ShadowBolt_Timer <= diff)
             {
                 if (!me->IsWithinDist(me->GetVictim(), 45.0f))
                     me->GetMotionMaster()->MoveChase(me->GetVictim(), VEKLOR_DIST, 0);
                 else
                     DoCastVictim(SPELL_SHADOWBOLT);
                 ShadowBolt_Timer = 2000;
             }
             else ShadowBolt_Timer -= diff;
             //Blizzard_Timer
             if (Blizzard_Timer <= diff)
             {
                 Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 45, true);
                 if (target)
                 {
                     DoCast(target, SPELL_BLIZZARD);
                 }
                 Blizzard_Timer = 15000 + rand() % 15000;
             }
             else Blizzard_Timer -= diff;
             if (ArcaneBurst_Timer <= diff)
             {
                 Unit* mvic;
                 if ((mvic = SelectTarget(SELECT_TARGET_NEAREST, 0, NOMINAL_MELEE_RANGE, true)) != nullptr)
                 {
                     DoCast(mvic, SPELL_ARCANEBURST);
                     ArcaneBurst_Timer = 5000;
                 }
             }
             else ArcaneBurst_Timer -= diff;
             HandleBugs(diff);
             //Heal brother when 60yrds close
             TryHealBrother(diff);
             //Teleporting to brother
             if (Teleport_Timer <= diff)
             {
                 TeleportToMyBrother();
             }
             else Teleport_Timer -= diff;
             CheckEnrage(diff);
             //VL doesn't melee
             //DoMeleeAttackIfReady();
         }
References boss_twinemperorsAI::AfterTeleport, ArcaneBurst_Timer, Blizzard_Timer, boss_twinemperorsAI::CheckEnrage(), diff(), UnitAI::DoCast(), UnitAI::DoCastVictim(), Unit::GetMotionMaster(), Unit::GetVictim(), boss_twinemperorsAI::HandleBugs(), WorldObject::IsWithinDist(), ScriptedAI::me, MotionMaster::MoveChase(), NOMINAL_MELEE_RANGE, SELECT_TARGET_NEAREST, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ShadowBolt_Timer, SPELL_ARCANEBURST, SPELL_BLIZZARD, SPELL_SHADOWBOLT, boss_twinemperorsAI::Teleport_Timer, boss_twinemperorsAI::TeleportToMyBrother(), boss_twinemperorsAI::TryActivateAfterTTelep(), boss_twinemperorsAI::TryHealBrother(), CreatureAI::UpdateVictim(), and VEKLOR_DIST.
Member Data Documentation
ArcaneBurst_Timer
uint32 boss_veklor::boss_veklorAI::ArcaneBurst_Timer
Definition at line 485 of file boss_twinemperors.cpp.
Referenced by Reset(), and UpdateAI().
Blizzard_Timer
uint32 boss_veklor::boss_veklorAI::Blizzard_Timer
Definition at line 484 of file boss_twinemperors.cpp.
Referenced by Reset(), and UpdateAI().
Rand
int boss_veklor::boss_veklorAI::Rand
Definition at line 487 of file boss_twinemperors.cpp.
RandX
int boss_veklor::boss_veklorAI::RandX
Definition at line 488 of file boss_twinemperors.cpp.
Scorpions_Timer
uint32 boss_veklor::boss_veklorAI::Scorpions_Timer
Definition at line 486 of file boss_twinemperors.cpp.
Referenced by Reset().
ShadowBolt_Timer
uint32 boss_veklor::boss_veklorAI::ShadowBolt_Timer
Definition at line 483 of file boss_twinemperors.cpp.
Referenced by Reset(), and UpdateAI().
Summoned
Creature* boss_veklor::boss_veklorAI::Summoned
Definition at line 490 of file boss_twinemperors.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp