Azerotcore-wotlk: Acore::AnyDeadUnitSpellTargetInRangeCheck Class Reference
Acore::AnyDeadUnitSpellTargetInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyDeadUnitSpellTargetInRangeCheck (Unit *searchObj, float range, SpellInfo const *spellInfo, SpellTargetCheckTypes check)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Public Member Functions inherited from Acore::AnyDeadUnitObjectInRangeCheck
AnyDeadUnitObjectInRangeCheck (Unit *searchObj, float range)
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Protected Attributes
SpellInfo const * i_spellInfo
WorldObjectSpellTargetCheck i_check
Protected Attributes inherited from Acore::AnyDeadUnitObjectInRangeCheck
Unit const *const i_searchObj
float i_range
Detailed Description
Definition at line 593 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyDeadUnitSpellTargetInRangeCheck()
Acore::AnyDeadUnitSpellTargetInRangeCheck::AnyDeadUnitSpellTargetInRangeCheck (Unit * searchObj, float range, SpellInfo const * spellInfo, SpellTargetCheckTypes check) inline
Definition at line 596 of file GridNotifiers.h.
             : AnyDeadUnitObjectInRangeCheck(searchObj, range), i_spellInfo(spellInfo), i_check(searchObj, searchObj, spellInfo, check, nullptr)
         {}
Member Function Documentation
operator()() [1/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Corpse * u)
Definition at line 374 of file GridNotifiers.cpp.
 {
     return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
 }
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
operator()() [2/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Creature * u)
Definition at line 379 of file GridNotifiers.cpp.
 {
     return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
 }
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
operator()() [3/4]
template<class NOT_INTERESTED > bool Acore::AnyDeadUnitSpellTargetInRangeCheck::operator() (NOT_INTERESTED *) inline
Definition at line 602 of file GridNotifiers.h.
 { return false; }
operator()() [4/4]
bool AnyDeadUnitSpellTargetInRangeCheck::operator() (Player * u)
Definition at line 369 of file GridNotifiers.cpp.
 {
     return AnyDeadUnitObjectInRangeCheck::operator()(u) && i_check(u);
 }
References i_check, and Acore::AnyDeadUnitObjectInRangeCheck::operator()().
Member Data Documentation
i_check
WorldObjectSpellTargetCheck Acore::AnyDeadUnitSpellTargetInRangeCheck::i_check protected
Definition at line 605 of file GridNotifiers.h.
Referenced by operator()().
i_spellInfo
SpellInfo const* Acore::AnyDeadUnitSpellTargetInRangeCheck::i_spellInfo protected
Definition at line 604 of file GridNotifiers.h.
The documentation for this class was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp