Azerotcore-wotlk: boss_four_horsemen::boss_four_horsemenAI Struct Reference
boss_four_horsemen::boss_four_horsemenAI Struct Reference
Public Member Functions
boss_four_horsemenAI (Creature *c)
void MoveToCorner ()
bool IsInRoom ()
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void AttackStart (Unit *who) override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void EnterCombat (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
uint8 currentWaypoint {}
uint8 movementPhase {}
uint8 horsemanId
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 130 of file boss_four_horsemen.cpp.
Constructor & Destructor Documentation
boss_four_horsemenAI()
boss_four_horsemen::boss_four_horsemenAI::boss_four_horsemenAI (Creature * c) inline explicit
Definition at line 132 of file boss_four_horsemen.cpp.
                                                    : BossAI(c, BOSS_HORSEMAN)
         {
             pInstance = me->GetInstanceScript();
             switch (me->GetEntry())
             {
                 case NPC_SIR_ZELIEK:
                     horsemanId = HORSEMAN_ZELIEK;
                     break;
                 case NPC_LADY_BLAUMEUX:
                     horsemanId = HORSEMAN_BLAUMEUX;
                     break;
                 case NPC_BARON_RIVENDARE:
                     horsemanId = HORSEMAN_RIVENDARE;
                     break;
                 case NPC_THANE_KORTHAZZ:
                     horsemanId = HORSEMAN_KORTHAZZ;
                     break;
             }
         }
References Object::GetEntry(), WorldObject::GetInstanceScript(), HORSEMAN_BLAUMEUX, HORSEMAN_KORTHAZZ, HORSEMAN_RIVENDARE, HORSEMAN_ZELIEK, horsemanId, ScriptedAI::me, NPC_BARON_RIVENDARE, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, NPC_THANE_KORTHAZZ, and pInstance.
Member Function Documentation
AttackStart()
void boss_four_horsemen::boss_four_horsemenAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 245 of file boss_four_horsemen.cpp.
         {
             if (movementPhase == MOVE_PHASE_FINISHED)
             {
                 if (me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK)
                 {
                     me->Attack(who, false);
                 }
                 else
                 {
                     ScriptedAI::AttackStart(who);
                 }
             }
         }
References Unit::Attack(), ScriptedAI::AttackStart(), Object::GetEntry(), ScriptedAI::me, MOVE_PHASE_FINISHED, movementPhase, NPC_LADY_BLAUMEUX, and NPC_SIR_ZELIEK.
EnterCombat()
void boss_four_horsemen::boss_four_horsemenAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 295 of file boss_four_horsemen.cpp.
         {
             BossAI::EnterCombat(who);
             if (movementPhase == MOVE_PHASE_NONE)
             {
                 Talk(SAY_AGGRO);
                 me->SetReactState(REACT_PASSIVE);
                 movementPhase = MOVE_PHASE_STARTED;
                 me->SetSpeed(MOVE_RUN, me->GetSpeedRate(MOVE_RUN), true);
                 MoveToCorner();
             }
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
             }
         }
References DATA_HORSEMEN_GATE, BossAI::EnterCombat(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetSpeedRate(), GO_STATE_READY, ScriptedAI::me, MOVE_PHASE_NONE, MOVE_PHASE_STARTED, MOVE_RUN, movementPhase, MoveToCorner(), pInstance, REACT_PASSIVE, SAY_AGGRO, Creature::SetReactState(), Unit::SetSpeed(), and CreatureAI::Talk().
IsInRoom()
bool boss_four_horsemen::boss_four_horsemenAI::IsInRoom () inline
Definition at line 178 of file boss_four_horsemen.cpp.
         {
             if (me->GetExactDist(2535.1f, -2968.7f, 241.3f) > 100.0f)
             {
                 EnterEvadeMode();
                 return false;
             }
             return true;
         }
References CreatureAI::EnterEvadeMode(), Position::GetExactDist(), and ScriptedAI::me.
Referenced by UpdateAI().
JustDied()
void boss_four_horsemen::boss_four_horsemenAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 272 of file boss_four_horsemen.cpp.
         {
             BossAI::JustDied(killer);
             if (pInstance)
             {
                 if (pInstance->GetBossState(BOSS_HORSEMAN) == DONE)
                 {
                     if (!me->GetMap()->GetPlayers().isEmpty())
                     {
                         if (Player* player = me->GetMap()->GetPlayers().getFirst()->GetSource())
{
                             player->SummonGameObject(RAID_MODE(GO_HORSEMEN_CHEST_10, GO_HORSEMEN_CHEST_25), 2514.8f, -2944.9f, 245.55f, 5.51f, 0, 0, 0, 0, 0);
                         }
                     }
                     if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                     {
                         go->SetGoState(GO_STATE_ACTIVE);
                     }
                 }
             }
             Talk(SAY_DEATH);
         }
References BOSS_HORSEMAN, DATA_HORSEMEN_GATE, DONE, InstanceScript::GetBossState(), MapRefMgr::getFirst(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), GO_HORSEMEN_CHEST_10, GO_HORSEMEN_CHEST_25, GO_STATE_ACTIVE, LinkedListHead::isEmpty(), BossAI::JustDied(), ScriptedAI::me, pInstance, ScriptedAI::RAID_MODE(), SAY_DEATH, and CreatureAI::Talk().
KilledUnit()
void boss_four_horsemen::boss_four_horsemenAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 260 of file boss_four_horsemen.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
             if (pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, Object::GetTypeId(), pInstance, SAY_SLAY, ZoneScript::SetData(), CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_four_horsemen::boss_four_horsemenAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 219 of file boss_four_horsemen.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             // final waypoint
             if (id % 3 == 2)
             {
                 movementPhase = MOVE_PHASE_FINISHED;
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->SetInCombatWithZone();
                 if (!UpdateVictim())
                 {
                     EnterEvadeMode();
                     return;
                 }
                 if (me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK)
                 {
                     me->GetMotionMaster()->Clear(false);
                     me->GetMotionMaster()->MoveIdle();
                 }
                 return;
             }
             currentWaypoint = id + 1;
         }
References MotionMaster::Clear(), currentWaypoint, CreatureAI::EnterEvadeMode(), Object::GetEntry(), Unit::GetMotionMaster(), ScriptedAI::me, MOVE_PHASE_FINISHED, MotionMaster::MoveIdle(), movementPhase, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, POINT_MOTION_TYPE, REACT_AGGRESSIVE, Creature::SetInCombatWithZone(), Creature::SetReactState(), and CreatureAI::UpdateVictim().
MoveToCorner()
void boss_four_horsemen::boss_four_horsemenAI::MoveToCorner () inline
Definition at line 158 of file boss_four_horsemen.cpp.
         {
             switch(me->GetEntry())
             {
                 case NPC_THANE_KORTHAZZ:
                     currentWaypoint = 0;
                     break;
                 case NPC_LADY_BLAUMEUX:
                     currentWaypoint = 3;
                     break;
                 case NPC_BARON_RIVENDARE:
                     currentWaypoint = 6;
                     break;
                 case NPC_SIR_ZELIEK:
                     currentWaypoint = 9;
                     break;
             }
             me->GetMotionMaster()->MovePoint(currentWaypoint, WaypointPositions[currentWaypoint]);
         }
References currentWaypoint, Object::GetEntry(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_BARON_RIVENDARE, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, NPC_THANE_KORTHAZZ, and WaypointPositions.
Referenced by EnterCombat().
Reset()
void boss_four_horsemen::boss_four_horsemenAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 188 of file boss_four_horsemen.cpp.
         {
             BossAI::Reset();
             me->SetPosition(me->GetHomePosition());
             movementPhase = MOVE_PHASE_NONE;
             currentWaypoint = 0;
             me->SetReactState(REACT_AGGRESSIVE);
             events.Reset();
             events.RescheduleEvent(EVENT_MARK_CAST, 24000);
             events.RescheduleEvent(EVENT_BERSERK, 600000);
             if ((me->GetEntry() != NPC_LADY_BLAUMEUX && me->GetEntry() != NPC_SIR_ZELIEK))
             {
                 events.RescheduleEvent(EVENT_PRIMARY_SPELL, 10000 + rand() % 5000);
             }
             else
             {
                 events.RescheduleEvent(EVENT_PUNISH, 5000);
                 events.RescheduleEvent(EVENT_SECONDARY_SPELL, 15000);
             }
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_HORSEMEN_GATE)))
                 {
                     if (pInstance->GetBossState(BOSS_GOTHIK) == DONE)
                     {
                         go->SetGoState(GO_STATE_ACTIVE);
                     }
                 }
             }
         }
References BOSS_GOTHIK, currentWaypoint, DATA_HORSEMEN_GATE, DONE, EVENT_BERSERK, EVENT_MARK_CAST, EVENT_PRIMARY_SPELL, EVENT_PUNISH, EVENT_SECONDARY_SPELL, InstanceScript::GetBossState(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), WorldObject::GetMap(), GO_STATE_ACTIVE, ScriptedAI::me, MOVE_PHASE_NONE, movementPhase, NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, pInstance, REACT_AGGRESSIVE, BossAI::Reset(), Creature::SetPosition(), and Creature::SetReactState().
UpdateAI()
void boss_four_horsemen::boss_four_horsemenAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 315 of file boss_four_horsemen.cpp.
         {
             if (movementPhase == MOVE_PHASE_STARTED && currentWaypoint)
             {
                 me->GetMotionMaster()->MovePoint(currentWaypoint, WaypointPositions[currentWaypoint]);
                 currentWaypoint = 0;
             }
             if (!IsInRoom())
                 return;
             if (movementPhase < MOVE_PHASE_FINISHED || !UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_MARK_CAST:
                     me->CastSpell(me, TABLE_SPELL_MARK[horsemanId], false);
                     events.RepeatEvent((me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK) ? 15000 : 12000);
                     return;
                 case EVENT_BERSERK:
                     Talk(SAY_SPECIAL);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     return;
                 case EVENT_PRIMARY_SPELL:
                     Talk(SAY_TAUNT);
                     me->CastSpell(me->GetVictim(), RAID_MODE(TABLE_SPELL_PRIMARY_10[horsemanId], TABLE_SPELL_PRIMARY_25[horsemanId]), false);
                     events.RepeatEvent(15000);
                     return;
                 case EVENT_PUNISH:
                     if (!SelectTarget(SELECT_TARGET_NEAREST, 0, 45.0f, true))
                     {
                         me->CastSpell(me, TABLE_SPELL_PUNISH[horsemanId], false);
                         Talk(EMOTE_RAGECAST);
                     }
                     events.RepeatEvent(2010);
                     return;
                 case EVENT_SECONDARY_SPELL:
                     me->CastSpell(me->GetVictim(), RAID_MODE(TABLE_SPELL_SECONDARY_10[horsemanId], TABLE_SPELL_SECONDARY_25[horsemanId]), false);
                     events.RepeatEvent(15000);
                     return;
             }
             if ((me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK))
             {
                 if (Unit* target = SelectTarget(SELECT_TARGET_NEAREST, 0, 45.0f, true))
                 {
                     me->CastSpell(target, RAID_MODE(TABLE_SPELL_PRIMARY_10[horsemanId], TABLE_SPELL_PRIMARY_25[horsemanId]), false);
                 }
             }
             else
             {
                 DoMeleeAttackIfReady();
             }
         }
References Unit::CastSpell(), currentWaypoint, UnitAI::DoMeleeAttackIfReady(), EMOTE_RAGECAST, EVENT_BERSERK, EVENT_MARK_CAST, EVENT_PRIMARY_SPELL, EVENT_PUNISH, EVENT_SECONDARY_SPELL, Object::GetEntry(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasUnitState(), horsemanId, IsInRoom(), ScriptedAI::me, MOVE_PHASE_FINISHED, MOVE_PHASE_STARTED, movementPhase, MotionMaster::MovePoint(), NPC_LADY_BLAUMEUX, NPC_SIR_ZELIEK, ScriptedAI::RAID_MODE(), SAY_SPECIAL, SAY_TAUNT, SELECT_TARGET_NEAREST, UnitAI::SelectTarget(), SPELL_BERSERK, TABLE_SPELL_MARK, TABLE_SPELL_PRIMARY_10, TABLE_SPELL_PRIMARY_25, TABLE_SPELL_PUNISH, TABLE_SPELL_SECONDARY_10, TABLE_SPELL_SECONDARY_25, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and WaypointPositions.
Member Data Documentation
currentWaypoint
uint8 boss_four_horsemen::boss_four_horsemenAI::currentWaypoint {}
Definition at line 154 of file boss_four_horsemen.cpp.
Referenced by MovementInform(), MoveToCorner(), Reset(), and UpdateAI().
events
EventMap boss_four_horsemen::boss_four_horsemenAI::events
Definition at line 152 of file boss_four_horsemen.cpp.
horsemanId
uint8 boss_four_horsemen::boss_four_horsemenAI::horsemanId
Definition at line 156 of file boss_four_horsemen.cpp.
Referenced by boss_four_horsemenAI(), and UpdateAI().
movementPhase
uint8 boss_four_horsemen::boss_four_horsemenAI::movementPhase {}
Definition at line 155 of file boss_four_horsemen.cpp.
Referenced by AttackStart(), EnterCombat(), MovementInform(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_four_horsemen::boss_four_horsemenAI::pInstance
Definition at line 153 of file boss_four_horsemen.cpp.
Referenced by boss_four_horsemenAI(), EnterCombat(), JustDied(), KilledUnit(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp