Azerotcore-wotlk: AccountActionIpLogger Class Reference
AccountActionIpLogger Class Reference
Public Member Functions
AccountActionIpLogger ()
void OnAccountLogin (uint32 accountId) override
void OnFailedAccountLogin (uint32 accountId) override
void OnPasswordChange (uint32 accountId) override
void OnFailedPasswordChange (uint32 accountId) override
void OnEmailChange (uint32 accountId) override
void OnFailedEmailChange (uint32 accountId) override
void AccountIPLogAction (uint32 accountId, IPLoggingTypes aType)
Public Member Functions inherited from AccountScript
virtual void OnLastIpUpdate (uint32, std::string)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AccountScript
AccountScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 44 of file action_ip_logger.cpp.
Constructor & Destructor Documentation
AccountActionIpLogger()
AccountActionIpLogger::AccountActionIpLogger () inline
Definition at line 47 of file action_ip_logger.cpp.
 : AccountScript("AccountActionIpLogger") { }
Member Function Documentation
AccountIPLogAction()
void AccountActionIpLogger::AccountIPLogAction (uint32 accountId, IPLoggingTypes aType) inline
Definition at line 91 of file action_ip_logger.cpp.
     {
         if (!sWorld->getBoolConfig(CONFIG_IP_BASED_ACTION_LOGGING))
             return;
         // Action IP Logger is only intialized if config is set up
         // Else, this script isn't loaded in the first place: We require no config check.
         // We declare all the required variables
         uint32 playerGuid = accountId;
         uint32 characterGuid = 0;
         std::string systemNote = "ERROR"; // "ERROR" is a placeholder here. We change it later.
         // With this switch, we change systemNote so that we have a more accurate phrasing of what type it is.
         // Avoids Magicnumbers in SQL table
         switch (aType)
         {
             case ACCOUNT_LOGIN:
                 systemNote = "Logged on Successful AccountLogin";
                 break;
             case ACCOUNT_FAIL_LOGIN:
                 systemNote = "Logged on Failed AccountLogin";
                 break;
             case ACCOUNT_CHANGE_PW:
                 systemNote = "Logged on Successful Account Password Change";
                 break;
             case ACCOUNT_CHANGE_PW_FAIL:
                 systemNote = "Logged on Failed Account Password Change";
                 break;
             case ACCOUNT_CHANGE_EMAIL:
                 systemNote = "Logged on Successful Account Email Change";
                 break;
             case ACCOUNT_CHANGE_EMAIL_FAIL:
                 systemNote = "Logged on Failed Account Email Change";
                 break;
             /*case ACCOUNT_LOGOUT:
                 systemNote = "Logged on AccountLogout"; //Can not be logged
                 break;*/
             // Neither should happen. Ever. Period. If it does, call Ghostbusters and all your local software defences to investigate.
             case UNKNOWN_ACTION:
             default:
                 systemNote = "ERROR! Unknown action!";
                 break;
         }
         // Once we have done everything, we can insert the new log.
         // Seeing as the time differences should be minimal, we do not get unixtime and the timestamp right now;
         // Rather, we let it be added with the SQL query.
         if (aType != ACCOUNT_FAIL_LOGIN)
         {
             // As we can assume most account actions are NOT failed login, so this is the more accurate check.
             // For those, we need last_ip...
             LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_ALDL_IP_LOGGING);
             stmt->setUInt32(0, playerGuid);
             stmt->setUInt32(1, characterGuid);
             stmt->setUInt8(2, aType);
             stmt->setUInt32(3, playerGuid);
             stmt->setString(4, systemNote.c_str());
             LoginDatabase.Execute(stmt);
         }
         else // ... but for failed login, we query last_attempt_ip from account table. Which we do with an unique query
         {
             LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_FACL_IP_LOGGING);
             stmt->setUInt32(0, playerGuid);
             stmt->setUInt32(1, characterGuid);
             stmt->setUInt8(2, aType);
             stmt->setUInt32(3, playerGuid);
             stmt->setString(4, systemNote.c_str());
             LoginDatabase.Execute(stmt);
         }
         return;
     }
References ACCOUNT_CHANGE_EMAIL, ACCOUNT_CHANGE_EMAIL_FAIL, ACCOUNT_CHANGE_PW, ACCOUNT_CHANGE_PW_FAIL, ACCOUNT_FAIL_LOGIN, ACCOUNT_LOGIN, CONFIG_IP_BASED_ACTION_LOGGING, LOGIN_INS_ALDL_IP_LOGGING, LOGIN_INS_FACL_IP_LOGGING, LoginDatabase, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sWorld, and UNKNOWN_ACTION.
Referenced by OnAccountLogin(), OnEmailChange(), OnFailedAccountLogin(), OnFailedEmailChange(), OnFailedPasswordChange(), and OnPasswordChange().
OnAccountLogin()
void AccountActionIpLogger::OnAccountLogin (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 51 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_LOGIN);
     }
References ACCOUNT_LOGIN, and AccountIPLogAction().
OnEmailChange()
void AccountActionIpLogger::OnEmailChange (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 77 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_CHANGE_EMAIL); // ... they get logged by gm command logger anyway
     }
References ACCOUNT_CHANGE_EMAIL, and AccountIPLogAction().
OnFailedAccountLogin()
void AccountActionIpLogger::OnFailedAccountLogin (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 58 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_FAIL_LOGIN);
     }
References ACCOUNT_FAIL_LOGIN, and AccountIPLogAction().
OnFailedEmailChange()
void AccountActionIpLogger::OnFailedEmailChange (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 83 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_CHANGE_EMAIL_FAIL);
     }
References ACCOUNT_CHANGE_EMAIL_FAIL, and AccountIPLogAction().
OnFailedPasswordChange()
void AccountActionIpLogger::OnFailedPasswordChange (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 70 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_CHANGE_PW_FAIL);
     }
References ACCOUNT_CHANGE_PW_FAIL, and AccountIPLogAction().
OnPasswordChange()
void AccountActionIpLogger::OnPasswordChange (uint32 accountId) inline override virtual
Reimplemented from AccountScript.
Definition at line 64 of file action_ip_logger.cpp.
     {
         AccountIPLogAction(accountId, ACCOUNT_CHANGE_PW);
     }
References ACCOUNT_CHANGE_PW, and AccountIPLogAction().
The documentation for this class was generated from the following file:
src/server/scripts/World/action_ip_logger.cpp