Azerotcore-wotlk: HostileRefMgr Class Reference
HostileRefMgr Class Reference
#include <HostileRefMgr.h>
Public Member Functions
HostileRefMgr (Unit *owner)
~HostileRefMgr () override
Unit * GetOwner ()
void threatAssist (Unit *victim, float baseThreat, SpellInfo const *threatSpell=nullptr)
void addTempThreat (float threat, bool apply)
void addThreatPercent (int32 percent)
void deleteReferences (bool removeFromMap=false)
void deleteReferencesForFaction (uint32 faction)
void deleteReferencesOutOfRange (float range)
HostileReference * getFirst ()
void updateThreatTables ()
void setOnlineOfflineState (bool isOnline)
void setOnlineOfflineState (Unit *creature, bool isOnline)
void deleteReference (Unit *creature)
void UpdateVisibility (bool checkThreat)
Public Member Functions inherited from RefMgr< Unit, ThreatMgr >
RefMgr ()=default
virtual ~RefMgr ()
Reference< Unit, ThreatMgr > * getFirst ()
Reference< Unit, ThreatMgr > const * getFirst () const
Reference< Unit, ThreatMgr > * getLast ()
Reference< Unit, ThreatMgr > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Attributes
Unit * iOwner
Additional Inherited Members
Public Types inherited from RefMgr< Unit, ThreatMgr >
typedef LinkedListHead::Iterator< Reference< Unit, ThreatMgr > > iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Detailed Description
Definition at line 31 of file HostileRefMgr.h.
Constructor & Destructor Documentation
HostileRefMgr()
HostileRefMgr::HostileRefMgr (Unit * owner) inline explicit
Definition at line 36 of file HostileRefMgr.h.
 { iOwner = owner; }
References iOwner.
~HostileRefMgr()
HostileRefMgr::~HostileRefMgr () override
Definition at line 25 of file HostileRefMgr.cpp.
 {
     deleteReferences();
 }
References deleteReferences().
Member Function Documentation
addTempThreat()
void HostileRefMgr::addTempThreat (float threat, bool apply)
Definition at line 54 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         if (apply)
         {
             if (ref->getTempThreatModifier() == 0.0f)
                 ref->addTempThreat(threat);
         }
         else
             ref->resetTempThreat();
         ref = ref->next();
     }
 }
References HostileReference::addTempThreat(), ByteConverter::apply(), getFirst(), HostileReference::getTempThreatModifier(), HostileReference::next(), and HostileReference::resetTempThreat().
Referenced by AuraEffect::HandleAuraModTotalThreat().
addThreatPercent()
void HostileRefMgr::addThreatPercent (int32 percent)
Definition at line 74 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         ref->addThreatPercent(percent);
         ref = ref->next();
     }
 }
References HostileReference::addThreatPercent(), getFirst(), and HostileReference::next().
Referenced by Spell::EffectSanctuary(), and AuraEffect::HandleFeignDeath().
deleteReference()
void HostileRefMgr::deleteReference (Unit * creature)
Definition at line 169 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         if (ref->GetSource()->GetOwner() == creature)
         {
             ref->removeReference();
             delete ref;
             break;
         }
         ref = nextRef;
     }
 }
References getFirst(), ThreatMgr::GetOwner(), Reference< TO, FROM >::GetSource(), HostileReference::next(), and HostileReference::removeReference().
deleteReferences()
void HostileRefMgr::deleteReferences (bool removeFromMap = false)
Definition at line 114 of file HostileRefMgr.cpp.
 {
     std::vector<Creature*> creaturesToEvade;
     HostileReference* ref = getFirst();
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         ref->removeReference();
         if (removeFromMap)
         {
             if (ThreatMgr const* threatMgr = ref->GetSource())
             {
                 if (threatMgr->areThreatListsEmpty())
                 {
                     if (Creature* creature = threatMgr->GetOwner()->ToCreature())
                     {
                         creaturesToEvade.push_back(creature);
                     }
                 }
             }
         }
         delete ref;
         ref = nextRef;
     }
     for (Creature* creature : creaturesToEvade)
     {
         creature->AI()->EnterEvadeMode();
     }
 }
References getFirst(), Unit::GetOwner(), Reference< TO, FROM >::GetSource(), HostileReference::next(), HostileReference::removeReference(), and Object::ToCreature().
Referenced by PetAI::_stopAttack(), Unit::CleanupBeforeRemoveFromMap(), Battleground::EndBattleground(), misc_commandscript::HandleCombatStopCommand(), AuraEffect::HandleFeignDeath(), WorldSession::HandleMoveWorldportAck(), Unit::Kill(), WorldSession::LogoutPlayer(), Map::RemovePlayerFromMap(), Unit::setDeathState(), and ~HostileRefMgr().
deleteReferencesForFaction()
void HostileRefMgr::deleteReferencesForFaction (uint32 faction)
Definition at line 151 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         if (ref->GetSource()->GetOwner()->GetFactionTemplateEntry()->faction == faction)
         {
             ref->removeReference();
             delete ref;
         }
         ref = nextRef;
     }
 }
References FactionTemplateEntry::faction, Unit::GetFactionTemplateEntry(), getFirst(), ThreatMgr::GetOwner(), Reference< TO, FROM >::GetSource(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Unit::StopAttackFaction().
deleteReferencesOutOfRange()
void HostileRefMgr::deleteReferencesOutOfRange (float range)
Definition at line 188 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     range = range * range;
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         Unit* owner = ref->GetSource()->GetOwner();
         if (!owner->isActiveObject() && owner->GetExactDist2dSq(GetOwner()) > range)
         {
             ref->removeReference();
             delete ref;
         }
         ref = nextRef;
     }
 }
References Position::GetExactDist2dSq(), getFirst(), GetOwner(), ThreatMgr::GetOwner(), Reference< TO, FROM >::GetSource(), WorldObject::isActiveObject(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Player::Update().
getFirst()
HostileReference* HostileRefMgr::getFirst () inline
Definition at line 60 of file HostileRefMgr.h.
 { return ((HostileReference*) RefMgr<Unit, ThreatMgr>::getFirst()); }
Referenced by addTempThreat(), addThreatPercent(), deleteReference(), deleteReferences(), deleteReferencesForFaction(), deleteReferencesOutOfRange(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), setOnlineOfflineState(), Unit::SetPhaseMask(), threatAssist(), Map::Update(), updateThreatTables(), and UpdateVisibility().
GetOwner()
Unit* HostileRefMgr::GetOwner () inline
Definition at line 39 of file HostileRefMgr.h.
 { return iOwner; }
References iOwner.
Referenced by deleteReferencesOutOfRange().
setOnlineOfflineState() [1/2]
void HostileRefMgr::setOnlineOfflineState (bool isOnline)
Definition at line 87 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         ref->setOnlineOfflineState(isOnline);
         ref = ref->next();
     }
 }
References getFirst(), HostileReference::next(), and HostileReference::setOnlineOfflineState().
Referenced by Player::CleanupAfterTaxiFlight(), FlightPathMovementGenerator::DoFinalize(), FlightPathMovementGenerator::DoReset(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset(), Player::SetGameMaster(), and Unit::SetPhaseMask().
setOnlineOfflineState() [2/2]
void HostileRefMgr::setOnlineOfflineState (Unit * creature, bool isOnline)
Definition at line 208 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         if (ref->GetSource()->GetOwner() == creature)
         {
             ref->setOnlineOfflineState(isOnline);
             break;
         }
         ref = nextRef;
     }
 }
References getFirst(), ThreatMgr::GetOwner(), Reference< TO, FROM >::GetSource(), HostileReference::next(), and HostileReference::setOnlineOfflineState().
threatAssist()
void HostileRefMgr::threatAssist (Unit * victim, float baseThreat, SpellInfo const * threatSpell = nullptr)
Definition at line 35 of file HostileRefMgr.cpp.
 {
     if (getSize() == 0)
         return;
     HostileReference* ref = getFirst();
     float threat = ThreatCalcHelper::calcThreat(victim, iOwner, baseThreat, (threatSpell ? threatSpell->GetSchoolMask() : SPELL_SCHOOL_MASK_NORMAL), threatSpell);
     threat /= getSize();
     while (ref)
     {
         if (ThreatCalcHelper::isValidProcess(victim, ref->GetSource()->GetOwner(), threatSpell))
             ref->GetSource()->doAddThreat(victim, threat);
         ref = ref->next();
     }
 }
References ThreatCalcHelper::calcThreat(), ThreatMgr::doAddThreat(), getFirst(), ThreatMgr::GetOwner(), SpellInfo::GetSchoolMask(), LinkedListHead::getSize(), Reference< TO, FROM >::GetSource(), iOwner, ThreatCalcHelper::isValidProcess(), HostileReference::next(), and SPELL_SCHOOL_MASK_NORMAL.
Referenced by Spell::DoAllEffectOnTarget(), Spell::DoSpellHitOnUnit(), Spell::EffectDispel(), Spell::EffectDispelMechanic(), Unit::EnergizeBySpell(), AuraEffect::HandleObsModPowerAuraTick(), AuraEffect::HandlePeriodicEnergizeAuraTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), and Spell::HandleThreatSpells().
updateThreatTables()
void HostileRefMgr::updateThreatTables ()
Definition at line 100 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         ref->updateOnlineStatus();
         ref = ref->next();
     }
 }
References getFirst(), HostileReference::next(), and HostileReference::updateOnlineStatus().
Referenced by Player::SetInWater().
UpdateVisibility()
void HostileRefMgr::UpdateVisibility (bool checkThreat)
Definition at line 225 of file HostileRefMgr.cpp.
 {
     HostileReference* ref = getFirst();
     while (ref)
     {
         HostileReference* nextRef = ref->next();
         if ((!checkThreat || ref->GetSource()->getThreatList().size() <= 1))
         {
             nextRef = ref->next();
             ref->removeReference();
             delete ref;
         }
         ref = nextRef;
     }
 }
References getFirst(), Reference< TO, FROM >::GetSource(), ThreatMgr::getThreatList(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Spell::EffectSanctuary().
Member Data Documentation
iOwner
Unit* HostileRefMgr::iOwner private
Definition at line 34 of file HostileRefMgr.h.
Referenced by GetOwner(), HostileRefMgr(), and threatAssist().
The documentation for this class was generated from the following files:
src/server/game/Combat/HostileRefMgr.h
src/server/game/Combat/HostileRefMgr.cpp