Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/prng.h File Reference
prng.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/bit_util.h"
Macros
#define PRNG_A_32 UINT32_C(1103515241)
#define PRNG_C_32 UINT32_C(12347)
#define PRNG_A_64 UINT64_C(6364136223846793005)
#define PRNG_C_64 UINT64_C(1442695040888963407)
Functions
JEMALLOC_ALWAYS_INLINE uint32_t prng_state_next_u32 (uint32_t state)
JEMALLOC_ALWAYS_INLINE uint64_t prng_state_next_u64 (uint64_t state)
JEMALLOC_ALWAYS_INLINE size_t prng_state_next_zu (size_t state)
JEMALLOC_ALWAYS_INLINE uint32_t prng_lg_range_u32 (atomic_u32_t *state, unsigned lg_range, bool atomic)
JEMALLOC_ALWAYS_INLINE uint64_t prng_lg_range_u64 (uint64_t *state, unsigned lg_range)
JEMALLOC_ALWAYS_INLINE size_t prng_lg_range_zu (atomic_zu_t *state, unsigned lg_range, bool atomic)
JEMALLOC_ALWAYS_INLINE uint32_t prng_range_u32 (atomic_u32_t *state, uint32_t range, bool atomic)
JEMALLOC_ALWAYS_INLINE uint64_t prng_range_u64 (uint64_t *state, uint64_t range)
JEMALLOC_ALWAYS_INLINE size_t prng_range_zu (atomic_zu_t *state, size_t range, bool atomic)
Macro Definition Documentation
PRNG_A_32
#define PRNG_A_32 UINT32_C(1103515241)
Definition at line 29 of file prng.h.
PRNG_A_64
#define PRNG_A_64 UINT64_C(6364136223846793005)
Definition at line 32 of file prng.h.
PRNG_C_32
#define PRNG_C_32 UINT32_C(12347)
Definition at line 30 of file prng.h.
PRNG_C_64
#define PRNG_C_64 UINT64_C(1442695040888963407)
Definition at line 33 of file prng.h.
Function Documentation
prng_lg_range_u32()
JEMALLOC_ALWAYS_INLINE uint32_t prng_lg_range_u32 (atomic_u32_t * state, unsigned lg_range, bool atomic)
Definition at line 67 of file prng.h.
{
     uint32_t ret, state0, state1;
     assert(lg_range > 0);
     assert(lg_range <= 32);
     state0 = atomic_load_u32(state, ATOMIC_RELAXED);
     if (atomic) {
         do {
             state1 = prng_state_next_u32(state0);
         } while (!atomic_compare_exchange_weak_u32(state, &state0,
             state1, ATOMIC_RELAXED, ATOMIC_RELAXED));
     } else {
         state1 = prng_state_next_u32(state0);
         atomic_store_u32(state, state1, ATOMIC_RELAXED);
     }
     ret = state1 >> (32 - lg_range);
     return ret;
 }
References assert(), ATOMIC_RELAXED, prng_state_next_u32(), and ret.
Referenced by prng_range_u32().
prng_lg_range_u64()
JEMALLOC_ALWAYS_INLINE uint64_t prng_lg_range_u64 (uint64_t * state, unsigned lg_range)
Definition at line 90 of file prng.h.
{
     uint64_t ret, state1;
     assert(lg_range > 0);
     assert(lg_range <= 64);
     state1 = prng_state_next_u64(*state);
     *state = state1;
     ret = state1 >> (64 - lg_range);
     return ret;
 }
References assert(), prng_state_next_u64(), and ret.
Referenced by ckh_evict_reloc_insert(), ckh_try_bucket_insert(), extent_addr_randomize(), prng_range_u64(), and prof_sample_threshold_update().
prng_lg_range_zu()
JEMALLOC_ALWAYS_INLINE size_t prng_lg_range_zu (atomic_zu_t * state, unsigned lg_range, bool atomic)
Definition at line 104 of file prng.h.
{
     size_t ret, state0, state1;
     assert(lg_range > 0);
     assert(lg_range <= ZU(1) << (3 + LG_SIZEOF_PTR));
     state0 = atomic_load_zu(state, ATOMIC_RELAXED);
     if (atomic) {
         do {
             state1 = prng_state_next_zu(state0);
         } while (atomic_compare_exchange_weak_zu(state, &state0,
             state1, ATOMIC_RELAXED, ATOMIC_RELAXED));
     } else {
         state1 = prng_state_next_zu(state0);
         atomic_store_zu(state, state1, ATOMIC_RELAXED);
     }
     ret = state1 >> ((ZU(1) << (3 + LG_SIZEOF_PTR)) - lg_range);
     return ret;
 }
References assert(), ATOMIC_RELAXED, prng_state_next_zu(), ret, and ZU.
Referenced by extent_addr_randomize(), and prng_range_zu().
prng_range_u32()
JEMALLOC_ALWAYS_INLINE uint32_t prng_range_u32 (atomic_u32_t * state, uint32_t range, bool atomic)
Definition at line 132 of file prng.h.
{
     uint32_t ret;
     unsigned lg_range;
     assert(range > 1);
     /* Compute the ceiling of lg(range). */
     lg_range = ffs_u32(pow2_ceil_u32(range)) - 1;
     /* Generate a result in [0..range) via repeated trial. */
     do {
         ret = prng_lg_range_u32(state, lg_range, atomic);
     } while (ret >= range);
     return ret;
 }
References assert(), ffs_u32(), pow2_ceil_u32(), prng_lg_range_u32(), and ret.
prng_range_u64()
JEMALLOC_ALWAYS_INLINE uint64_t prng_range_u64 (uint64_t * state, uint64_t range)
Definition at line 150 of file prng.h.
{
     uint64_t ret;
     unsigned lg_range;
     assert(range > 1);
     /* Compute the ceiling of lg(range). */
     lg_range = ffs_u64(pow2_ceil_u64(range)) - 1;
     /* Generate a result in [0..range) via repeated trial. */
     do {
         ret = prng_lg_range_u64(state, lg_range);
     } while (ret >= range);
     return ret;
 }
References assert(), ffs_u64(), pow2_ceil_u64(), prng_lg_range_u64(), and ret.
Referenced by arena_decay_deadline_init().
prng_range_zu()
JEMALLOC_ALWAYS_INLINE size_t prng_range_zu (atomic_zu_t * state, size_t range, bool atomic)
Definition at line 168 of file prng.h.
{
     size_t ret;
     unsigned lg_range;
     assert(range > 1);
     /* Compute the ceiling of lg(range). */
     lg_range = ffs_u64(pow2_ceil_u64(range)) - 1;
     /* Generate a result in [0..range) via repeated trial. */
     do {
         ret = prng_lg_range_zu(state, lg_range, atomic);
     } while (ret >= range);
     return ret;
 }
References assert(), ffs_u64(), pow2_ceil_u64(), prng_lg_range_zu(), and ret.
prng_state_next_u32()
JEMALLOC_ALWAYS_INLINE uint32_t prng_state_next_u32 (uint32_t state)
Definition at line 36 of file prng.h.
{
     return (state * PRNG_A_32) + PRNG_C_32;
 }
References PRNG_A_32, and PRNG_C_32.
Referenced by prng_lg_range_u32().
prng_state_next_u64()
JEMALLOC_ALWAYS_INLINE uint64_t prng_state_next_u64 (uint64_t state)
Definition at line 41 of file prng.h.
{
     return (state * PRNG_A_64) + PRNG_C_64;
 }
References PRNG_A_64, and PRNG_C_64.
Referenced by prng_lg_range_u64().
prng_state_next_zu()
JEMALLOC_ALWAYS_INLINE size_t prng_state_next_zu (size_t state)
Definition at line 46 of file prng.h.
{
 #if LG_SIZEOF_PTR == 2
     return (state * PRNG_A_32) + PRNG_C_32;
 #elif LG_SIZEOF_PTR == 3
     return (state * PRNG_A_64) + PRNG_C_64;
 #else
 #error Unsupported pointer size
 #endif
 }
References PRNG_A_32, PRNG_A_64, PRNG_C_32, and PRNG_C_64.
Referenced by prng_lg_range_zu().