Azerotcore-wotlk: SmartScriptHolder Struct Reference
SmartScriptHolder Struct Reference
#include <SmartScriptMgr.h>
Public Member Functions
SmartScriptHolder ()
uint32 GetScriptType () const
uint32 GetEventType () const
uint32 GetActionType () const
uint32 GetTargetType () const
Public Attributes
int32 entryOrGuid
SmartScriptType source_type
uint32 event_id
uint32 link
SmartEvent event
SmartAction action
SmartTarget target
uint32 timer
bool active
bool runOnce
bool enableTimed
Detailed Description
Definition at line 1707 of file SmartScriptMgr.h.
Constructor & Destructor Documentation
SmartScriptHolder()
SmartScriptHolder::SmartScriptHolder () inline
Definition at line 1709 of file SmartScriptMgr.h.
                         : entryOrGuid(0), source_type(SMART_SCRIPT_TYPE_CREATURE)
         , event_id(0), link(0), event(), action(), target(), timer(0), active(false), runOnce(false)
         , enableTimed(false) {}
Member Function Documentation
GetActionType()
uint32 SmartScriptHolder::GetActionType () const inline
Definition at line 1725 of file SmartScriptMgr.h.
 { return (uint32)action.type; }
References action, and SmartAction::type.
Referenced by SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::NotNULL(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetEventType()
uint32 SmartScriptHolder::GetEventType () const inline
Definition at line 1724 of file SmartScriptMgr.h.
 { return (uint32)event.type; }
Referenced by SmartScript::InitTimer(), SmartAIMgr::IsEventValid(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetScriptType()
uint32 SmartScriptHolder::GetScriptType () const inline
Definition at line 1723 of file SmartScriptMgr.h.
 { return (uint32)source_type; }
References source_type.
Referenced by SmartScript::InstallTemplate(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::NotNULL(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
GetTargetType()
uint32 SmartScriptHolder::GetTargetType () const inline
Definition at line 1726 of file SmartScriptMgr.h.
 { return (uint32)target.type; }
References target, and SmartTarget::type.
Referenced by SmartScript::GetTargets(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartScript::ProcessAction(), and SmartScript::ProcessEvent().
Member Data Documentation
action
SmartAction SmartScriptHolder::action
Definition at line 1719 of file SmartScriptMgr.h.
Referenced by SmartScript::CreateSmartEvent(), GetActionType(), SmartScript::InstallTemplate(), SmartAIMgr::IsEventValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartScript::ProcessAction(), SmartScript::SetScript9(), and SmartScript::UpdateTimer().
active
bool SmartScriptHolder::active
Definition at line 1729 of file SmartScriptMgr.h.
Referenced by SmartScript::CheckTimer(), SmartScript::InitTimer(), SmartScript::ProcessEvent(), SmartScript::RecalcTimer(), and SmartScript::UpdateTimer().
enableTimed
bool SmartScriptHolder::enableTimed
Definition at line 1731 of file SmartScriptMgr.h.
Referenced by SmartScript::UpdateTimer().
entryOrGuid
int32 SmartScriptHolder::entryOrGuid
Definition at line 1713 of file SmartScriptMgr.h.
Referenced by SmartScript::InstallTemplate(), SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartAIMgr::NotNULL(), SmartScript::ProcessAction(), SmartScript::ProcessTimedAction(), and SmartScript::SetScript9().
event
SmartEvent SmartScriptHolder::event
Definition at line 1718 of file SmartScriptMgr.h.
Referenced by SmartScript::CreateSmartEvent(), SmartScript::InitTimer(), SmartAIMgr::IsEventValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), and SmartScript::UpdateTimer().
event_id
uint32 SmartScriptHolder::event_id
Definition at line 1715 of file SmartScriptMgr.h.
Referenced by SmartAIMgr::IsAreaTriggerValid(), SmartAIMgr::IsCreatureValid(), SmartAIMgr::IsEmoteValid(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsGameObjectValid(), SmartAIMgr::IsItemValid(), SmartAIMgr::IsMinMaxValid(), SmartAIMgr::IsQuestValid(), SmartAIMgr::IsSoundValid(), SmartAIMgr::IsSpellValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::IsTextEmoteValid(), SmartAIMgr::LoadSmartAIFromDB(), SmartAIMgr::NotNULL(), SmartScript::ProcessTimedAction(), and SmartScript::UpdateTimer().
link
uint32 SmartScriptHolder::link
Definition at line 1716 of file SmartScriptMgr.h.
Referenced by SmartAIMgr::IsEventValid(), and SmartAIMgr::LoadSmartAIFromDB().
runOnce
bool SmartScriptHolder::runOnce
Definition at line 1730 of file SmartScriptMgr.h.
Referenced by SmartScript::ProcessAction(), and SmartScript::ProcessEvent().
source_type
SmartScriptType SmartScriptHolder::source_type
Definition at line 1714 of file SmartScriptMgr.h.
Referenced by SmartScript::CreateSmartEvent(), GetScriptType(), SmartAIMgr::LoadSmartAIFromDB(), and SmartScript::ProcessTimedAction().
target
SmartTarget SmartScriptHolder::target
Definition at line 1720 of file SmartScriptMgr.h.
Referenced by SmartScript::CreateSmartEvent(), SmartScript::GetTargets(), GetTargetType(), SmartScript::InstallTemplate(), SmartAIMgr::IsEventValid(), SmartAIMgr::IsTargetValid(), SmartAIMgr::LoadSmartAIFromDB(), and SmartScript::ProcessAction().
timer
uint32 SmartScriptHolder::timer
Definition at line 1728 of file SmartScriptMgr.h.
Referenced by SmartScript::RecalcTimer(), and SmartScript::UpdateTimer().
The documentation for this struct was generated from the following file:
src/server/game/AI/SmartScripts/SmartScriptMgr.h