Azerotcore-wotlk: npc_hallows_end_soh::npc_hallows_end_sohAI Struct Reference
npc_hallows_end_soh::npc_hallows_end_sohAI Struct Reference
Public Member Functions
npc_hallows_end_sohAI (Creature *creature)
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *) override
void DoAction (int32 param) override
void GetPosToLand (float &x, float &y, float &z)
void Reset () override
void EnterEvadeMode () override
uint32 GetData (uint32) const override
void UpdateAI (uint32 diff) override
void CastFires (bool intial)
void FinishEvent (bool failed)
void MovementInform (uint32 type, uint32 point) override
void JustDied (Unit *) override
void CompleteQuest ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
uint32 playerCount
uint32 counter
GuidList unitList
int32 pos
TaskScheduler scheduler
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 658 of file hallows_end.cpp.
Constructor & Destructor Documentation
npc_hallows_end_sohAI()
npc_hallows_end_soh::npc_hallows_end_sohAI::npc_hallows_end_sohAI (Creature * creature) inline
Definition at line 660 of file hallows_end.cpp.
                                                   : ScriptedAI(creature)
         {
             pos = 0;
             counter = 0;
             unitList.clear();
             me->CastSpell(me, SPELL_HORSEMAN_MOUNT, true);
             me->SetSpeed(MOVE_WALK, 3.0f, true);
         }
References Unit::CastSpell(), counter, ScriptedAI::me, MOVE_WALK, pos, Unit::SetSpeed(), SPELL_HORSEMAN_MOUNT, and unitList.
Member Function Documentation
CastFires()
void npc_hallows_end_soh::npc_hallows_end_sohAI::CastFires (bool intial) inline
Definition at line 859 of file hallows_end.cpp.
         {
             std::vector<Unit*> tmpList;
             for (ObjectGuid const& guid : unitList)
             {
                 if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                 {
                     if (!c->HasAuraType(SPELL_AURA_PERIODIC_DUMMY))
                     {
                         tmpList.push_back(c);
                     }
                 }
             }
             if (tmpList.empty())
             {
                 return;
             }
             std::list<Player*> players;
             Acore::AnyPlayerInObjectRangeCheck checker(me, 60.f);
             Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, players, checker);
             Cell::VisitWorldObjects(me, searcher, 60.f);
             if (players.empty())
             {
                 return;
             }
             playerCount = static_cast<uint32>(players.size()) - 1;
             if (!intial)
             {
                 float playerRate = std::max(0.f, 0.5f - playerCount * 0.25f);
                 // If there are more burning triggers than players, do not cast next fire
                 if (tmpList.size() < unitList.size() * playerRate)
                 {
                     return;
                 }
             }
             else
                 playerCount += 1;
             uint32 sizeCount = (playerCount / 3) + 1;
             if (intial && playerCount > 0)
             {
                 sizeCount += playerCount % 2;
             }
             Acore::Containers::RandomResize(tmpList, sizeCount);
             for (Unit* trigger : tmpList)
                 me->CastSpell(trigger, SPELL_START_FIRE, true);
         }
References Unit::CastSpell(), ObjectAccessor::GetUnit(), ScriptedAI::me, playerCount, Acore::Containers::RandomResize(), SPELL_AURA_PERIODIC_DUMMY, SPELL_START_FIRE, unitList, and Cell::VisitWorldObjects().
Referenced by UpdateAI().
CompleteQuest()
void npc_hallows_end_soh::npc_hallows_end_sohAI::CompleteQuest () inline
Definition at line 955 of file hallows_end.cpp.
         {
             float radius = 100.0f;
             std::list<Player*> players;
             Acore::AnyPlayerInObjectRangeCheck checker(me, radius);
             Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, players, checker);
             Cell::VisitWorldObjects(me, searcher, radius);
             for (Player* player : players)
             {
                 player->AreaExploredOrEventHappens(QUEST_STOP_THE_FIRES_H);
                 player->AreaExploredOrEventHappens(QUEST_STOP_THE_FIRES_A);
                 player->AreaExploredOrEventHappens(QUEST_LET_THE_FIRES_COME_H);
                 player->AreaExploredOrEventHappens(QUEST_LET_THE_FIRES_COME_A);
             }
         }
References ScriptedAI::me, QUEST_LET_THE_FIRES_COME_A, QUEST_LET_THE_FIRES_COME_H, QUEST_STOP_THE_FIRES_A, QUEST_STOP_THE_FIRES_H, and Cell::VisitWorldObjects().
Referenced by JustDied().
DoAction()
void npc_hallows_end_soh::npc_hallows_end_sohAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 699 of file hallows_end.cpp.
         {
             pos = param;
         }
References pos.
EnterCombat()
void npc_hallows_end_soh::npc_hallows_end_sohAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 676 of file hallows_end.cpp.
         {
             scheduler.Schedule(6s, [this](TaskContext context)
             {
                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 30.f, true))
                 {
                     me->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION, false);
                     target->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION_SOUND, true);
                     Talk(TALK_SHADE_CONFLAGRATION);
                 }
                 context.Repeat(12s);
             })
             .Schedule(7s, [this](TaskContext context)
             {
                 DoCastVictim(SPELL_HORSEMAN_CLEAVE, true);
                 context.Repeat(8s);
             });
         }
References Unit::CastSpell(), UnitAI::DoCastVictim(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), scheduler, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_HORSEMAN_CLEAVE, SPELL_HORSEMAN_CONFLAGRATION, SPELL_HORSEMAN_CONFLAGRATION_SOUND, CreatureAI::Talk(), and TALK_SHADE_CONFLAGRATION.
EnterEvadeMode()
void npc_hallows_end_soh::npc_hallows_end_sohAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 769 of file hallows_end.cpp.
         {
             me->DespawnOrUnsummon(1);
         }
References Creature::DespawnOrUnsummon(), and ScriptedAI::me.
FinishEvent()
void npc_hallows_end_soh::npc_hallows_end_sohAI::FinishEvent (bool failed) inline
Definition at line 913 of file hallows_end.cpp.
         {
             if (failed)
             {
                 Talk(TALK_SHADE_FAILED);
                 for (ObjectGuid const& guid : unitList)
                     if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                         c->RemoveAllAuras();
                 me->DespawnOrUnsummon(1);
             }
             else
             {
                 Talk(TALK_SHADE_DEFEATED);
                 float x, y, z;
                 GetPosToLand(x, y, z);
                 me->GetMotionMaster()->Clear();
                 me->GetMotionMaster()->MoveIdle();
                 me->GetMotionMaster()->MovePoint(8, x, y, z);
             }
         }
References MotionMaster::Clear(), Creature::DespawnOrUnsummon(), Unit::GetMotionMaster(), GetPosToLand(), ObjectAccessor::GetUnit(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), CreatureAI::Talk(), TALK_SHADE_DEFEATED, TALK_SHADE_FAILED, and unitList.
Referenced by UpdateAI().
GetData()
uint32 npc_hallows_end_soh::npc_hallows_end_sohAI::GetData (uint32) const inline override virtual
Reimplemented from UnitAI.
Definition at line 774 of file hallows_end.cpp.
         {
             return playerCount;
         }
References playerCount.
GetPosToLand()
void npc_hallows_end_soh::npc_hallows_end_sohAI::GetPosToLand (float & x, float & y, float & z) inline
Definition at line 704 of file hallows_end.cpp.
         {
             switch (pos)
             {
                 case 235431:
                     x = -9445.1f;
                     y = 63.27f;
                     z = 58.16f;
                     break;
                 case 235432:
                     x = -5616.30f;
                     y = -481.89f;
                     z = 398.99f;
                     break;
                 case 235433:
                     x = -4198.1f;
                     y = -12509.13f;
                     z = 46.6f;
                     break;
                 case 235434:
                     x = 360.9f;
                     y = -4735.5f;
                     z = 11.773f;
                     break;
                 case 235435:
                     x = 2229.4f;
                     y = 263.1f;
                     z = 36.13f;
                     break;
                 case 235436:
                     x = 9532.9f;
                     y = -6833.8f;
                     z = 18.5f;
                     break;
                 default:
                     x = 0;
                     y = 0;
                     z = 0;
                     break;
             }
         }
References pos.
Referenced by FinishEvent(), and JustDied().
JustDied()
void npc_hallows_end_soh::npc_hallows_end_sohAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 946 of file hallows_end.cpp.
         {
             Talk(TALK_SHADE_DEATH);
             float x, y, z;
             GetPosToLand(x, y, z);
             me->CastSpell(x, y, z, SPELL_SUMMON_LANTERN, true);
             CompleteQuest();
         }
References Unit::CastSpell(), CompleteQuest(), GetPosToLand(), ScriptedAI::me, SPELL_SUMMON_LANTERN, CreatureAI::Talk(), and TALK_SHADE_DEATH.
MoveInLineOfSight()
void npc_hallows_end_soh::npc_hallows_end_sohAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 697 of file hallows_end.cpp.
 {}
MovementInform()
void npc_hallows_end_soh::npc_hallows_end_sohAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 935 of file hallows_end.cpp.
         {
             if (type == POINT_MOTION_TYPE && point == 8)
             {
                 me->RemoveAllAuras();
                 me->SetCanFly(false);
                 me->SetDisableGravity(false);
                 events.ScheduleEvent(4, 2000);
             }
         }
References ScriptedAI::me, POINT_MOTION_TYPE, Unit::RemoveAllAuras(), Creature::SetCanFly(), and Creature::SetDisableGravity().
Reset()
void npc_hallows_end_soh::npc_hallows_end_sohAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 746 of file hallows_end.cpp.
         {
             playerCount = 0;
             unitList.clear();
             std::list<Creature*> temp;
             me->GetCreaturesWithEntryInRange(temp, 100.0f, NPC_FIRE_TRIGGER);
             for (std::list<Creature*>::const_iterator itr = temp.begin(); itr != temp.end(); ++itr)
             {
                 unitList.push_back((*itr)->GetGUID());
             }
             events.ScheduleEvent(1, 3000);
             events.ScheduleEvent(2, 25000);
             events.ScheduleEvent(2, 43000);
             events.ScheduleEvent(3, 63000);
             me->SetReactState(REACT_PASSIVE);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetCanFly(true);
             me->SetDisableGravity(true);
         }
References WorldObject::GetCreaturesWithEntryInRange(), ScriptedAI::me, NPC_FIRE_TRIGGER, playerCount, REACT_PASSIVE, Creature::SetCanFly(), Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and unitList.
UpdateAI()
void npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 779 of file hallows_end.cpp.
         {
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 1:
                     Talk(TALK_SHADE_PREPARE);
                     break;
                 case 2:
                     {
                         CastFires(true);
                         break;
                     }
                 case 3:
                     {
                         bool checkBurningTriggers = false;
                         for (ObjectGuid const& guid : unitList)
                             if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                                 if (c->HasAuraType(SPELL_AURA_PERIODIC_DUMMY))
{
                                     checkBurningTriggers = true;
                                     break;
                                 }
                         if (!checkBurningTriggers)
{
                             FinishEvent(false);
                             return;
                         }
                         counter++;
                         if (counter > 21)
{
                             bool failed = false;
                             for (ObjectGuid const& guid : unitList)
                                 if (Unit* c = ObjectAccessor::GetUnit(*me, guid))
                                     if (c->HasAuraType(SPELL_AURA_PERIODIC_DUMMY))
{
                                         failed = true;
                                         break;
                                     }
                             FinishEvent(failed);
                             return;
                         }
                         if (counter == 5)
{
                             Talk(TALK_SHADE_START_EVENT);
                         }
                         else if (counter == 15)
{
                             Talk(TALK_SHADE_MORE_FIRES);
                         }
                         CastFires(false);
                         events.RepeatEvent(15000);
                         break;
                     }
                     case 4:
                     {
                         me->SetUInt32Value(UNIT_FIELD_FLAGS, 0);
                         me->SetReactState(REACT_AGGRESSIVE);
                         if (Unit* target = me->SelectNearestPlayer(30.0f))
                             AttackStart(target);
                         break;
                     }
             }
             if (!UpdateVictim())
                 return;
             scheduler.Update(diff, [this]
             {
                 DoMeleeAttackIfReady();
             });
         }
References ScriptedAI::AttackStart(), CastFires(), counter, UnitAI::DoMeleeAttackIfReady(), FinishEvent(), ObjectAccessor::GetUnit(), Unit::HasUnitState(), ScriptedAI::me, REACT_AGGRESSIVE, scheduler, WorldObject::SelectNearestPlayer(), Creature::SetReactState(), Object::SetUInt32Value(), SPELL_AURA_PERIODIC_DUMMY, CreatureAI::Talk(), TALK_SHADE_MORE_FIRES, TALK_SHADE_PREPARE, TALK_SHADE_START_EVENT, UNIT_FIELD_FLAGS, UNIT_STATE_CASTING, unitList, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
counter
uint32 npc_hallows_end_soh::npc_hallows_end_sohAI::counter
Definition at line 671 of file hallows_end.cpp.
Referenced by npc_hallows_end_sohAI(), and UpdateAI().
events
EventMap npc_hallows_end_soh::npc_hallows_end_sohAI::events
Definition at line 669 of file hallows_end.cpp.
playerCount
uint32 npc_hallows_end_soh::npc_hallows_end_sohAI::playerCount
Definition at line 670 of file hallows_end.cpp.
Referenced by CastFires(), GetData(), and Reset().
pos
int32 npc_hallows_end_soh::npc_hallows_end_sohAI::pos
Definition at line 673 of file hallows_end.cpp.
Referenced by DoAction(), GetPosToLand(), and npc_hallows_end_sohAI().
scheduler
TaskScheduler npc_hallows_end_soh::npc_hallows_end_sohAI::scheduler
Definition at line 674 of file hallows_end.cpp.
Referenced by EnterCombat(), and UpdateAI().
unitList
GuidList npc_hallows_end_soh::npc_hallows_end_sohAI::unitList
Definition at line 672 of file hallows_end.cpp.
Referenced by CastFires(), FinishEvent(), npc_hallows_end_sohAI(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/hallows_end.cpp