Azerotcore-wotlk: G3D::Log Class Reference
G3D::Log Class Reference
#include <Log.h>
Public Member Functions
Log (const std::string &filename="log.txt", int stripFromStackBottom=0)
virtual ~Log ()
FILE * getFile () const
void section (const std::string &s)
void __cdecl printf (const char *fmt,...) G3D_CHECK_PRINTF_METHOD_ARGS
void __cdecl vprintf (const char *, va_list argPtr) G3D_CHECK_VPRINTF_METHOD_ARGS
void __cdecl lazyvprintf (const char *, va_list argPtr) G3D_CHECK_VPRINTF_METHOD_ARGS
void print (const std::string &s)
void println (const std::string &s)
Static Public Member Functions
static Log * common ()
static std::string getCommonLogFilename ()
Public Attributes
int stripFromStackBottom
Private Attributes
FILE * logFile
std::string filename
Static Private Attributes
static Log * commonLog = NULL
Detailed Description
System log for debugging purposes. The first log opened is the "common log" and can be accessed with the static method common(). If you access common() and a common log does not yet exist, one is created for you.
Definition at line 48 of file Log.h.
Constructor & Destructor Documentation
Log()
Log::Log (const std::string & filename = "log.txt", int stripFromStackBottom = 0)
Parameters
stripFromStackBottom Number of call stacks to strip from the bottom of the stack when printing a trace. Useful for hiding routines like "main" and "WinMain". If the specified file cannot be opened for some reason, tries to open "c:/tmp/log.txt" or "c:/temp/log.txt" instead.
Definition at line 42 of file Log.cpp.
                                                             :
     stripFromStackBottom(stripFromStackBottom) {
     this->filename = filename;
     logFile = FileSystem::fopen(filename.c_str(), "w");
     if (logFile == NULL) {
         std::string drive, base, ext;
         Array<std::string> path;
         parseFilename(filename, drive, path, base, ext);
         std::string logName = base + ((ext != "") ? ("." + ext) : "");
         // Write time is greater than 1ms.  This may be a network drive.... try another file.
         #ifdef G3D_WINDOWS
             logName = std::string(std::getenv("TEMP")) + logName;
         #else
             logName = std::string("/tmp/") + logName;
         #endif
         logFile = FileSystem::fopen(logName.c_str(), "w");
     }
     // Use a large buffer (although we flush in logPrintf)
     setvbuf(logFile, NULL, _IOFBF, 2048);
     fprintf(logFile, "Application Log\n");
     time_t t;
     time(&t);
     fprintf(logFile, "Start: %s\n", ctime(&t));
     fflush(logFile);
     if (commonLog == NULL) {
         commonLog = this;
     }
 }
References commonLog, filename, G3D::FileSystem::fopen(), fprintf(), logFile, NULL, and G3D::parseFilename().
Referenced by common().
~Log()
Log::~Log () virtual
Definition at line 80 of file Log.cpp.
           {
     section("Shutdown");
     println("Closing log file");
     // Make sure we don't leave a dangling pointer
     if (Log::commonLog == this) {
         Log::commonLog = NULL;
     }
     if (logFile) {
         FileSystem::fclose(logFile);
     }
 }
References commonLog, G3D::FileSystem::fclose(), logFile, NULL, println(), and section().
Member Function Documentation
common()
Log * Log::common () static
Definition at line 100 of file Log.cpp.
                  {
     if (commonLog == NULL) {
         commonLog = new Log();
     }
     return commonLog;
 }
References commonLog, Log(), and NULL.
Referenced by G3D::NetworkDevice::bind(), G3D::NetworkDevice::closesocket(), G3D::GImage::decodePCX(), getCommonLogFilename(), G3D::increaseBufferSize(), G3D::LightweightConduit::LightweightConduit(), G3D::NetAddress::localHostAddresses(), G3D::NetworkDevice::localHostAddresses(), G3D::NetworkDevice::localHostName(), G3D::logLazyPrintf(), G3D::logPrintf(), G3D::NetListener::NetListener(), G3D::png_warning(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), G3D::NetListener::waitForConnection(), and G3D::LightweightConduit::waitingMessageType().
getCommonLogFilename()
std::string Log::getCommonLogFilename () static
Definition at line 108 of file Log.cpp.
{
     return common()->filename;
 }
References common(), and filename.
getFile()
FILE * Log::getFile () const
Returns the handle to the file log.
Definition at line 95 of file Log.cpp.
{
     return logFile;
 }
References logFile.
lazyvprintf()
void __cdecl Log::lazyvprintf (const char * fmt, va_list argPtr)
Does not flush
Definition at line 133 of file Log.cpp.
{
     vfprintf(logFile, fmt, argPtr);
 }
References fmt, logFile, and vfprintf().
Referenced by G3D::logLazyPrintf().
print()
void Log::print (const std::string & s)
Definition at line 138 of file Log.cpp.
{
     fprintf(logFile, "%s", s.c_str());
     fflush(logFile);
 }
References fprintf(), and logFile.
Referenced by G3D::LightweightConduit::LightweightConduit(), G3D::NetListener::NetListener(), printf(), and G3D::ReliableConduit::ReliableConduit().
printf()
void __cdecl Log::printf (const char * fmt, ...)
Given arguments like printf, writes characters to the debug text overlay.
Definition at line 119 of file Log.cpp.
{
     va_list arg_list;
     va_start(arg_list, fmt);
     print(vformat(fmt, arg_list));
     va_end(arg_list);
 }
References fmt, print(), and G3D::vformat().
Referenced by G3D::NetworkDevice::bind(), G3D::NetworkDevice::closesocket(), G3D::GImage::decodePCX(), G3D::increaseBufferSize(), G3D::LightweightConduit::LightweightConduit(), G3D::NetAddress::localHostAddresses(), G3D::NetworkDevice::localHostAddresses(), G3D::NetworkDevice::localHostName(), G3D::NetListener::NetListener(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::LightweightConduit::sendBuffer(), and G3D::NetListener::waitForConnection().
println()
void Log::println (const std::string & s)
Definition at line 144 of file Log.cpp.
{
     fprintf(logFile, "%s\n", s.c_str());
     fflush(logFile);
 }
References fprintf(), and logFile.
Referenced by G3D::NetworkDevice::bind(), G3D::GImage::decodePCX(), G3D::increaseBufferSize(), G3D::LightweightConduit::LightweightConduit(), G3D::NetListener::NetListener(), G3D::png_warning(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), G3D::NetListener::waitForConnection(), G3D::LightweightConduit::waitingMessageType(), and ~Log().
section()
void Log::section (const std::string & s)
Marks the beginning of a logfile section.
Definition at line 113 of file Log.cpp.
{
     fprintf(logFile, "_____________________________________________________\n");
     fprintf(logFile, "\n    ###    %s    ###\n\n", s.c_str());
 }
References fprintf(), and logFile.
Referenced by ~Log().
vprintf()
void __cdecl Log::vprintf (const char * fmt, va_list argPtr)
Definition at line 127 of file Log.cpp.
{
     vfprintf(logFile, fmt, argPtr);
     fflush(logFile);
 }
References fmt, logFile, and vfprintf().
Referenced by G3D::logPrintf().
Member Data Documentation
commonLog
Log * Log::commonLog = NULL static private
Definition at line 58 of file Log.h.
Referenced by common(), Log(), and ~Log().
filename
std::string G3D::Log::filename private
Definition at line 56 of file Log.h.
Referenced by getCommonLogFilename(), and Log().
logFile
FILE* G3D::Log::logFile private
Log messages go here.
Definition at line 54 of file Log.h.
Referenced by getFile(), lazyvprintf(), Log(), print(), println(), section(), vprintf(), and ~Log().
stripFromStackBottom
int G3D::Log::stripFromStackBottom
Definition at line 61 of file Log.h.
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Log.h
deps/g3dlite/source/Log.cpp