Azerotcore-wotlk: src/server/game/Handlers/GuildHandler.cpp File Reference
GuildHandler.cpp File Reference
#include "Guild.h"
#include "GuildMgr.h"
#include "Log.h"
#include "ObjectMgr.h"
#include "Opcodes.h"
#include "SocialMgr.h"
#include "World.h"
#include "WorldPacket.h"
#include "WorldSession.h"
Functions
void cleanStr (std::string &str)
Function Documentation
cleanStr()
void cleanStr (std::string & str)
Definition at line 29 of file GuildHandler.cpp.
 {
     str.erase(remove(str.begin(), str.end(), '|'), str.end());
 }
Referenced by WorldSession::HandleGuildAddRankOpcode(), WorldSession::HandleGuildBankUpdateTab(), WorldSession::HandleGuildChangeInfoTextOpcode(), WorldSession::HandleGuildMOTDOpcode(), WorldSession::HandleGuildRankOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), and WorldSession::HandleSetGuildBankTabText().