Azerotcore-wotlk: npc_prof_blacksmith Class Reference
npc_prof_blacksmith Class Reference
Public Member Functions
npc_prof_blacksmith ()
bool HasWeaponSub (Player *player)
bool OnGossipHello (Player *player, Creature *creature) override
void SendActionMenu (Player *player, Creature *creature, uint32 action)
void SendConfirmLearn (Player *player, Creature *creature, uint32 action)
void SendConfirmUnlearn (Player *player, Creature *creature, uint32 action)
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 599 of file npc_professions.cpp.
Constructor & Destructor Documentation
npc_prof_blacksmith()
npc_prof_blacksmith::npc_prof_blacksmith () inline
Definition at line 602 of file npc_professions.cpp.
 : CreatureScript("npc_prof_blacksmith") { }
Member Function Documentation
HasWeaponSub()
bool npc_prof_blacksmith::HasWeaponSub (Player * player) inline
Definition at line 604 of file npc_professions.cpp.
     {
         return (player->HasSpell(S_HAMMER) || player->HasSpell(S_AXE) || player->HasSpell(S_SWORD));
     }
References Player::HasSpell(), S_AXE, S_HAMMER, and S_SWORD.
Referenced by OnGossipHello(), and SendActionMenu().
OnGossipHello()
bool npc_prof_blacksmith::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 609 of file npc_professions.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (creature->IsVendor())
             AddGossipItemFor(player, GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         uint32 creatureId = creature->GetEntry();
         //WEAPONSMITH & ARMORSMITH
         if (player->GetBaseSkillValue(SKILL_BLACKSMITHING) >= 225)
         {
             if (player->GetQuestRewardStatus(5284) || player->GetQuestRewardStatus(5302) || player->GetQuestRewardStatus(5283) || player->GetQuestStatus(5301))
             {
                 switch (creatureId)
                 {
                     case N_TRAINER_SMITHOMNI1:                                     //Myolor Sunderfury
                     case N_TRAINER_SMITHOMNI2:                                     //Krathok Moltenfist
                         if (!player->HasSpell(S_ARMOR) && !player->HasSpell(S_WEAPON))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ARMOR_LEARN,   GOSSIP_SENDER_MAIN,          GOSSIP_ACTION_INFO_DEF + 1);
                         if (!player->HasSpell(S_WEAPON) && !player->HasSpell(S_ARMOR))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_WEAPON_LEARN,  GOSSIP_SENDER_MAIN,          GOSSIP_ACTION_INFO_DEF + 2);
                         break;
                     case N_TRAINER_WEAPON1:                                     //Ironus Coldsteel
                     case N_TRAINER_WEAPON2:                                     //Borgosh Corebender
                         if (player->HasSpell(S_WEAPON))
{
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_WEAPON_UNLEARN,    GOSSIP_SENDER_UNLEARN,   GOSSIP_ACTION_INFO_DEF + 3);
                             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                         }
                         break;
                     case N_TRAINER_ARMOR1:                                      //Grumnus Steelshaper
                     case N_TRAINER_ARMOR2:                                     //Okothos Ironrager
                         if (player->HasSpell(S_ARMOR))
{
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ARMOR_UNLEARN,     GOSSIP_SENDER_UNLEARN,   GOSSIP_ACTION_INFO_DEF + 4);
                             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                         }
                         break;
                 }
             }
         }
         //WEAPONSMITH SPEC
         if (player->HasSpell(S_WEAPON) && player->getLevel() > 49 && player->GetBaseSkillValue(SKILL_BLACKSMITHING) >= 250)
         {
             switch (creatureId)
             {
                 case N_TRAINER_HAMMER:                                     //Lilith the Lithe
                     if (!HasWeaponSub(player))
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_HAMMER,       GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 5);
                     if (player->HasSpell(S_HAMMER))
                     {
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_HAMMER,     GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 8);
                         AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                     }
                     break;
                 case N_TRAINER_AXE:                                     //Kilram
                     if (!HasWeaponSub(player))
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_AXE,          GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 6);
                     if (player->HasSpell(S_AXE))
                     {
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_AXE,        GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 9);
                         AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                     }
                     break;
                 case N_TRAINER_SWORD:                                     //Seril Scourgebane
                     if (!HasWeaponSub(player))
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SWORD,        GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 7);
                     if (player->HasSpell(S_SWORD))
                     {
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_SWORD,      GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 10);
                         AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                     }
                     break;
             }
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetBaseSkillValue(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Unit::getLevel(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, GOSSIP_ARMOR_LEARN, GOSSIP_ARMOR_UNLEARN, GOSSIP_ICON_CHAT, GOSSIP_ICON_TRAINER, GOSSIP_ICON_VENDOR, GOSSIP_LEARN_AXE, GOSSIP_LEARN_HAMMER, GOSSIP_LEARN_SWORD, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_TEXT_TRAIN, GOSSIP_UNLEARN_AXE, GOSSIP_UNLEARN_HAMMER, GOSSIP_UNLEARN_SWORD, GOSSIP_WEAPON_LEARN, GOSSIP_WEAPON_UNLEARN, Player::HasSpell(), HasWeaponSub(), Unit::IsQuestGiver(), Unit::IsVendor(), N_TRAINER_ARMOR1, N_TRAINER_ARMOR2, N_TRAINER_AXE, N_TRAINER_HAMMER, N_TRAINER_SMITHOMNI1, N_TRAINER_SMITHOMNI2, N_TRAINER_SWORD, N_TRAINER_WEAPON1, N_TRAINER_WEAPON2, Player::PrepareQuestMenu(), S_ARMOR, S_AXE, S_HAMMER, S_SWORD, S_WEAPON, SendGossipMenuFor(), and SKILL_BLACKSMITHING.
OnGossipSelect()
bool npc_prof_blacksmith::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 799 of file npc_professions.cpp.
     {
         ClearGossipMenuFor(player);
         switch (sender)
         {
             case GOSSIP_SENDER_MAIN:
                 SendActionMenu(player, creature, action);
                 break;
             case GOSSIP_SENDER_LEARN:
                 SendConfirmLearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_UNLEARN:
                 SendConfirmUnlearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_CHECK:
                 SendActionMenu(player, creature, action);
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), GOSSIP_SENDER_CHECK, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, SendActionMenu(), SendConfirmLearn(), and SendConfirmUnlearn().
SendActionMenu()
void npc_prof_blacksmith::SendActionMenu (Player * player, Creature * creature, uint32 action) inline
Definition at line 690 of file npc_professions.cpp.
     {
         switch (action)
         {
             case GOSSIP_ACTION_TRADE:
                 player->GetSession()->SendListInventory(creature->GetGUID());
                 break;
             case GOSSIP_ACTION_TRAIN:
                 player->GetSession()->SendTrainerList(creature->GetGUID());
                 break;
             //Learn Armor/Weapon
             case GOSSIP_ACTION_INFO_DEF + 1:
                 ProcessCastaction(player, creature, S_ARMOR, S_LEARN_ARMOR, 0);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 ProcessCastaction(player, creature, S_WEAPON, S_LEARN_WEAPON, 0);
                 break;
             //Unlearn Armor/Weapon
             case GOSSIP_ACTION_INFO_DEF + 3:
                 if (HasWeaponSub(player))
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                 else
                     ProcessUnlearnAction(player, creature, S_UNLEARN_WEAPON, S_REP_ARMOR, DoLowUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 4:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_ARMOR, S_REP_WEAPON, DoLowUnlearnCost(player));
                 break;
             //Learn Hammer/Axe/Sword
             case GOSSIP_ACTION_INFO_DEF + 5:
                 ProcessCastaction(player, creature, S_HAMMER, S_LEARN_HAMMER, 0);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 6:
                 ProcessCastaction(player, creature, S_AXE, S_LEARN_AXE, 0);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 7:
                 ProcessCastaction(player, creature, S_SWORD, S_LEARN_SWORD, 0);
                 break;
             //Unlearn Hammer/Axe/Sword
             case GOSSIP_ACTION_INFO_DEF + 8:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_HAMMER, 0, DoMedUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 9:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_AXE, 0, DoMedUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 10:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_SWORD, 0, DoMedUnlearnCost(player));
                 break;
         }
     }
References DoLowUnlearnCost(), DoMedUnlearnCost(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, HasWeaponSub(), ProcessCastaction(), ProcessUnlearnAction(), S_ARMOR, S_AXE, S_HAMMER, S_LEARN_ARMOR, S_LEARN_AXE, S_LEARN_HAMMER, S_LEARN_SWORD, S_LEARN_WEAPON, S_REP_ARMOR, S_REP_WEAPON, S_SWORD, S_UNLEARN_ARMOR, S_UNLEARN_AXE, S_UNLEARN_HAMMER, S_UNLEARN_SWORD, S_UNLEARN_WEAPON, S_WEAPON, SendGossipMenuFor(), WorldSession::SendListInventory(), and WorldSession::SendTrainerList().
Referenced by OnGossipSelect().
SendConfirmLearn()
void npc_prof_blacksmith::SendConfirmLearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 740 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_HAMMER:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_HAMMER, GOSSIP_SENDER_CHECK, action);
                     //unknown textID (TALK_HAMMER_LEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_AXE:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_AXE,    GOSSIP_SENDER_CHECK, action);
                     //unknown textID (TALK_AXE_LEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_SWORD:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SWORD,  GOSSIP_SENDER_CHECK, action);
                     //unknown textID (TALK_SWORD_LEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ICON_CHAT, GOSSIP_LEARN_AXE, GOSSIP_LEARN_HAMMER, GOSSIP_LEARN_SWORD, GOSSIP_SENDER_CHECK, N_TRAINER_AXE, N_TRAINER_HAMMER, N_TRAINER_SWORD, and SendGossipMenuFor().
Referenced by OnGossipSelect().
SendConfirmUnlearn()
void npc_prof_blacksmith::SendConfirmUnlearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 765 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_WEAPON1:                                     //Ironus Coldsteel
                 case N_TRAINER_WEAPON2:                                     //Borgosh Corebender
                 case N_TRAINER_ARMOR1:                                      //Grumnus Steelshaper
                 case N_TRAINER_ARMOR2:                                     //Okothos Ironrager
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_SMITH_SPEC, GOSSIP_SENDER_CHECK, action, BOX_UNLEARN_ARMORORWEAPON, DoLowUnlearnCost(player), false);
                     //unknown textID (TALK_UNLEARN_AXEORWEAPON)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_HAMMER:
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_HAMMER, GOSSIP_SENDER_CHECK, action,    BOX_UNLEARN_WEAPON_SPEC, DoMedUnlearnCost(player), false);
                     //unknown textID (TALK_HAMMER_UNLEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_AXE:
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_AXE, GOSSIP_SENDER_CHECK, action,       BOX_UNLEARN_WEAPON_SPEC, DoMedUnlearnCost(player), false);
                     //unknown textID (TALK_AXE_UNLEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_SWORD:
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_SWORD, GOSSIP_SENDER_CHECK, action,     BOX_UNLEARN_WEAPON_SPEC, DoMedUnlearnCost(player), false);
                     //unknown textID (TALK_SWORD_UNLEARN)
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), BOX_UNLEARN_ARMORORWEAPON, BOX_UNLEARN_WEAPON_SPEC, DoLowUnlearnCost(), DoMedUnlearnCost(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_SENDER_CHECK, GOSSIP_UNLEARN_AXE, GOSSIP_UNLEARN_HAMMER, GOSSIP_UNLEARN_SMITH_SPEC, GOSSIP_UNLEARN_SWORD, N_TRAINER_ARMOR1, N_TRAINER_ARMOR2, N_TRAINER_AXE, N_TRAINER_HAMMER, N_TRAINER_SWORD, N_TRAINER_WEAPON1, N_TRAINER_WEAPON2, and SendGossipMenuFor().
Referenced by OnGossipSelect().
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_professions.cpp