Azerotcore-wotlk: enumutils_describe Namespace Reference
enumutils_describe Namespace Reference
Functions
def strescape (str)
def processFile (path, filename)
Variables
tuple notice = ()
EnumPattern = compile(r'//\s*EnumUtils: DESCRIBE THIS(?:\s*\‍(in ([^\‍)]+)\‍))?\s+enum\s+([0-9A-Za-z]+)[^\n]*\s*{([^}]+)};')
EnumValuesPattern = compile(r'\s+\S.+?(,|$)[^\n]*')
EnumValueNamePattern = compile(r'^\s*([a-zA-Z0-9_]+)', flags=MULTILINE)
EnumValueSkipLinePattern = compile(r'^\s*//')
EnumValueCommentPattern = compile(r'//,?[ \t]*([^\n]+)$')
CommentMatchFormat = compile(r'^(((TITLE +(.+?))|(DESCRIPTION +(.+?))) *){1,2}$')
CommentSkipFormat = compile(r'^SKIP *$')
FilenamePattern = compile(r'^(.+)\.h$')
nameMatch = FilenamePattern.match(n)
Function Documentation
processFile()
def enumutils_describe.processFile (path, filename)
Definition at line 45 of file enumutils_describe.py.
 def processFile(path, filename):
     input = open('%s/%s.h' % (path, filename),'r')
     if input is None:
         print('Failed to open %s.h' % filename)
         return
     file = input.read()
     enums = []
     for enum in EnumPattern.finditer(file):
         prefix = enum.group(1) or ''
         name = enum.group(2)
         values = []
         for value in EnumValuesPattern.finditer(enum.group(3)):
             valueData = value.group(0)
             valueNameMatch = EnumValueNamePattern.search(valueData)
             if valueNameMatch is None:
                 if EnumValueSkipLinePattern.search(valueData) is None:
                     print('Name of value not found: %s' % repr(valueData))
                 continue
             valueName = valueNameMatch.group(1)
             valueCommentMatch = EnumValueCommentPattern.search(valueData)
             valueComment = None
             if valueCommentMatch:
                 valueComment = valueCommentMatch.group(1)
             valueTitle = None
             valueDescription = None
             if valueComment is not None:
                 if CommentSkipFormat.match(valueComment) is not None:
                     continue
                 commentMatch = CommentMatchFormat.match(valueComment)
                 if commentMatch is not None:
                     valueTitle = commentMatch.group(4)
                     valueDescription = commentMatch.group(6)
                 else:
                     valueDescription = valueComment
             if valueTitle is None:
                 valueTitle = valueName
             if valueDescription is None:
                 valueDescription = ''
             values.append((valueName, valueTitle, valueDescription))
         enums.append((prefix + name, prefix, values))
         print('%s.h: Enum %s parsed with %d values' % (filename, name, len(values)))
     if not enums:
         return
     print('Done parsing %s.h (in %s)\n' % (filename, path))
     output = open('%s/enuminfo_%s.cpp' % (path, filename), 'w')
     if output is None:
         print('Failed to create enuminfo_%s.cpp' % filename)
         return
     # write output file
     output.write(notice)
     output.write('#include "%s.h"\n' % filename)
     output.write('#include "Define.h"\n')
     output.write('#include "SmartEnum.h"\n')
     output.write('#include <stdexcept>\n')
     output.write('\n')
     output.write('namespace Acore::Impl::EnumUtilsImpl\n')
     output.write('{\n')
     for name, prefix, values in enums:
         tag = ('data for enum \'%s\' in \'%s.h\' auto-generated' % (name, filename))
         output.write('\n')
         output.write('/*' + ('*'*(len(tag)+2)) + '*\\\n')
         output.write('|* ' + tag + ' *|\n')
         output.write('\\*' + ('*'*(len(tag)+2)) + '*/\n')
         output.write('template <>\n')
         output.write('AC_API_EXPORT EnumText EnumUtils<%s>::ToString(%s value)\n' % (name, name))
         output.write('{\n')
         output.write('    switch (value)\n')
         output.write('    {\n')
         for label, title, description in values:
             output.write('        case %s: return { %s, %s, %s };\n' % (prefix + label, strescape(label), strescape(title), strescape(description)))
         output.write('        default: throw std::out_of_range("value");\n')
         output.write('    }\n')
         output.write('}\n')
         output.write('\n')
         output.write('template <>\n')
         output.write('AC_API_EXPORT size_t EnumUtils<%s>::Count() { return %d; }\n' % (name, len(values)))
         output.write('\n')
         output.write('template <>\n')
         output.write('AC_API_EXPORT %s EnumUtils<%s>::FromIndex(size_t index)\n' % (name, name))
         output.write('{\n')
         output.write('    switch (index)\n')
         output.write('    {\n')
         for (i, (label, title, description)) in enumerate(values):
             output.write('        case %d: return %s;\n' % (i, prefix + label))
         output.write('        default: throw std::out_of_range("index");\n')
         output.write('    }\n')
         output.write('}\n')
         output.write('\n')
         output.write('template <>\n')
         output.write('AC_API_EXPORT size_t EnumUtils<%s>::ToIndex(%s value)\n' % (name, name))
         output.write('{\n')
         output.write('    switch (value)\n')
         output.write('    {\n')
         for (i, (label, title, description)) in enumerate(values):
             output.write('        case %s: return %d;\n' % (prefix + label, i))
         output.write('        default: throw std::out_of_range("value");\n')
         output.write('    }\n')
         output.write('}\n')
     output.write('}\n')
References open, print(), and strescape().
strescape()
def enumutils_describe.strescape (str)
Definition at line 36 of file enumutils_describe.py.
 def strescape(str):
     res = ''
     for char in str:
         if char in ('\\', '"') or not (32 <= ord(char) < 127):
             res += ('\\%03o' % ord(char))
         else:
             res += char
     return '"' + res + '"'
Referenced by processFile().
Variable Documentation
CommentMatchFormat
enumutils_describe.CommentMatchFormat = compile(r'^(((TITLE +(.+?))|(DESCRIPTION +(.+?))) *){1,2}$')
Definition at line 33 of file enumutils_describe.py.
CommentSkipFormat
enumutils_describe.CommentSkipFormat = compile(r'^SKIP *$')
Definition at line 34 of file enumutils_describe.py.
EnumPattern
enumutils_describe.EnumPattern = compile(r'//\s*EnumUtils: DESCRIBE THIS(?:\s*\‍(in ([^\‍)]+)\‍))?\s+enum\s+([0-9A-Za-z]+)[^\n]*\s*{([^}]+)};')
Definition at line 28 of file enumutils_describe.py.
EnumValueCommentPattern
enumutils_describe.EnumValueCommentPattern = compile(r'//,?[ \t]*([^\n]+)$')
Definition at line 32 of file enumutils_describe.py.
EnumValueNamePattern
enumutils_describe.EnumValueNamePattern = compile(r'^\s*([a-zA-Z0-9_]+)', flags=MULTILINE)
Definition at line 30 of file enumutils_describe.py.
EnumValueSkipLinePattern
enumutils_describe.EnumValueSkipLinePattern = compile(r'^\s*//')
Definition at line 31 of file enumutils_describe.py.
EnumValuesPattern
enumutils_describe.EnumValuesPattern = compile(r'\s+\S.+?(,|$)[^\n]*')
Definition at line 29 of file enumutils_describe.py.
FilenamePattern
enumutils_describe.FilenamePattern = compile(r'^(.+)\.h$')
Definition at line 158 of file enumutils_describe.py.
nameMatch
enumutils_describe.nameMatch = FilenamePattern.match(n)
Definition at line 161 of file enumutils_describe.py.
notice
tuple enumutils_describe.notice = ()
Definition at line 4 of file enumutils_describe.py.