Azerotcore-wotlk: deps/mysqllite/mysys/lf_hash.c File Reference
lf_hash.c File Reference
#include <my_global.h>
#include <m_string.h>
#include <my_sys.h>
#include <my_bit.h>
#include <lf.h>
Classes
struct LF_SLIST
struct CURSOR
Macros
#define PTR(V) (LF_SLIST *)((V) & (~(intptr)1))
#define DELETED(V) ((V) & 1)
#define MAX_LOAD 1.0 /* average number of elements in a bucket */
Functions
static int lfind (LF_SLIST *volatile *head, CHARSET_INFO *cs, uint32 hashnr, const uchar *key, uint keylen, CURSOR *cursor, LF_PINS *pins)
static LF_SLIST * linsert (LF_SLIST *volatile *head, CHARSET_INFO *cs, LF_SLIST *node, LF_PINS *pins, uint flags)
static int ldelete (LF_SLIST *volatile *head, CHARSET_INFO *cs, uint32 hashnr, const uchar *key, uint keylen, LF_PINS *pins)
static LF_SLIST * lsearch (LF_SLIST *volatile *head, CHARSET_INFO *cs, uint32 hashnr, const uchar *key, uint keylen, LF_PINS *pins)
static const uchar * hash_key (const LF_HASH *hash, const uchar *record, size_t *length)
static uint calc_hash (LF_HASH *hash, const uchar *key, uint keylen)
static int initialize_bucket (LF_HASH *, LF_SLIST *volatile *, uint, LF_PINS *)
void lf_hash_init (LF_HASH *hash, uint element_size, uint flags, uint key_offset, uint key_length, my_hash_get_key get_key, CHARSET_INFO *charset)
void lf_hash_destroy (LF_HASH *hash)
int lf_hash_insert (LF_HASH *hash, LF_PINS *pins, const void *data)
int lf_hash_delete (LF_HASH *hash, LF_PINS *pins, const void *key, uint keylen)
void * lf_hash_search (LF_HASH *hash, LF_PINS *pins, const void *key, uint keylen)
Variables
static const uchar * dummy_key = (uchar*)""
Macro Definition Documentation
DELETED
#define DELETED (V) ((V) & 1)
Definition at line 58 of file lf_hash.c.
MAX_LOAD
#define MAX_LOAD 1.0 /* average number of elements in a bucket */
Definition at line 296 of file lf_hash.c.
PTR
#define PTR (V) (LF_SLIST *)((V) & (~(intptr)1))
Definition at line 57 of file lf_hash.c.
Function Documentation
calc_hash()
static uint calc_hash (LF_HASH * hash, const uchar * key, uint keylen) inline static
Definition at line 288 of file lf_hash.c.
 {
   ulong nr1= 1, nr2= 4;
   hash->charset->coll->hash_sort(hash->charset, (uchar*) key, keylen,
                                  &nr1, &nr2);
   return nr1 & INT_MAX32;
 }
References hash(), and INT_MAX32.
Referenced by lf_hash_delete(), lf_hash_insert(), and lf_hash_search().
hash_key()
static const uchar* hash_key (const LF_HASH * hash, const uchar * record, size_t * length) inline static
Definition at line 273 of file lf_hash.c.
 {
   if (hash->get_key)
     return (*hash->get_key)(record, length, 0);
   *length= hash->key_length;
   return record + hash->key_offset;
 }
References hash(), and G3D::length().
Referenced by lf_hash_insert().
initialize_bucket()
static int initialize_bucket (LF_HASH * hash, LF_SLIST *volatile * node, uint bucket, LF_PINS * pins) static
Definition at line 473 of file lf_hash.c.
 {
   uint parent= my_clear_highest_bit(bucket);
   LF_SLIST *dummy= (LF_SLIST *)my_malloc(sizeof(LF_SLIST), MYF(MY_WME));
   LF_SLIST **tmp= 0, *cur;
   LF_SLIST * volatile *el= _lf_dynarray_lvalue(&hash->array, parent);
   if (unlikely(!el || !dummy))
     return -1;
   if (*el == NULL && bucket &&
       unlikely(initialize_bucket(hash, el, parent, pins)))
     return -1;
   dummy->hashnr= my_reverse_bits(bucket) | 0; /* dummy node */
   dummy->key= dummy_key;
   dummy->keylen= 0;
   if ((cur= linsert(el, hash->charset, dummy, pins, LF_HASH_UNIQUE)))
   {
     my_free(dummy);
     dummy= cur;
   }
   my_atomic_casptr((void **)node, (void **)&tmp, dummy);
   /*
     note that if the CAS above failed (after linsert() succeeded),
     it would mean that some other thread has executed linsert() for
     the same dummy node, its linsert() failed, it picked up our
     dummy node (in "dummy= cur") and executed the same CAS as above.
     Which means that even if CAS above failed we don't need to retry,
     and we should not free(dummy) - there's no memory leak here
   */
   return 0;
 }
References _lf_dynarray_lvalue(), dummy_key, hash(), LF_SLIST::hashnr, LF_SLIST::key, LF_SLIST::keylen, LF_HASH_UNIQUE, linsert(), my_clear_highest_bit(), my_free(), my_malloc(), my_reverse_bits(), MY_WME, MYF, NULL, pins, and unlikely.
Referenced by lf_hash_delete(), lf_hash_insert(), and lf_hash_search().
ldelete()
static int ldelete (LF_SLIST *volatile * head, CHARSET_INFO * cs, uint32 hashnr, const uchar * key, uint keylen, LF_PINS * pins) static
Definition at line 202 of file lf_hash.c.
 {
   CURSOR cursor;
   int res;
   for (;;)
   {
     if (!lfind(head, cs, hashnr, key, keylen, &cursor, pins))
     {
       res= 1; /* not found */
       break;
     }
     else
     {
       /* mark the node deleted */
       if (my_atomic_casptr((void **)&(cursor.curr->link),
                            (void **)&cursor.next,
                            (void *)(((intptr)cursor.next) | 1)))
       {
         /* and remove it from the list */
         if (my_atomic_casptr((void **)cursor.prev,
                              (void **)&cursor.curr, cursor.next))
           _lf_alloc_free(pins, cursor.curr);
         else
         {
           /*
             somebody already "helped" us and removed the node ?
             Let's check if we need to help that someone too!
             (to ensure the number of "set DELETED flag" actions
             is equal to the number of "remove from the list" actions)
           */
           lfind(head, cs, hashnr, key, keylen, &cursor, pins);
         }
         res= 0;
         break;
       }
     }
   }
   _lf_unpin(pins, 0);
   _lf_unpin(pins, 1);
   _lf_unpin(pins, 2);
   return res;
 }
References _lf_alloc_free, _lf_unpin, CURSOR::curr, lfind(), LF_SLIST::link, CURSOR::next, pins, and CURSOR::prev.
Referenced by lf_hash_delete().
lf_hash_delete()
int lf_hash_delete (LF_HASH * hash, LF_PINS * pins, const void * key, uint keylen)
Definition at line 409 of file lf_hash.c.
 {
   LF_SLIST * volatile *el;
   uint bucket, hashnr= calc_hash(hash, (uchar *)key, keylen);
   bucket= hashnr % hash->size;
   lf_rwlock_by_pins(pins);
   el= _lf_dynarray_lvalue(&hash->array, bucket);
   if (unlikely(!el))
     return -1;
   /*
     note that we still need to initialize_bucket here,
     we cannot return "node not found", because an old bucket of that
     node may've been split and the node was assigned to a new bucket
     that was never accessed before and thus is not initialized.
   */
   if (*el == NULL && unlikely(initialize_bucket(hash, el, bucket, pins)))
     return -1;
   if (ldelete(el, hash->charset, my_reverse_bits(hashnr) | 1,
               (uchar *)key, keylen, pins))
   {
     lf_rwunlock_by_pins(pins);
     return 1;
   }
   my_atomic_add32(&hash->count, -1);
   lf_rwunlock_by_pins(pins);
   return 0;
 }
References _lf_dynarray_lvalue(), calc_hash(), hash(), initialize_bucket(), ldelete(), lf_rwlock_by_pins, lf_rwunlock_by_pins, my_reverse_bits(), NULL, pins, and unlikely.
lf_hash_destroy()
void lf_hash_destroy (LF_HASH * hash)
Definition at line 331 of file lf_hash.c.
 {
   LF_SLIST *el, **head= (LF_SLIST **)_lf_dynarray_value(&hash->array, 0);
   if (unlikely(!head))
     return;
   el= *head;
   while (el)
   {
     intptr next= el->link;
     if (el->hashnr & 1)
       lf_alloc_direct_free(&hash->alloc, el); /* normal node */
     else
       my_free(el); /* dummy node */
     el= (LF_SLIST *)next;
   }
   lf_alloc_destroy(&hash->alloc);
   lf_dynarray_destroy(&hash->array);
 }
References _lf_dynarray_value(), hash(), LF_SLIST::hashnr, lf_alloc_destroy(), lf_alloc_direct_free, lf_dynarray_destroy(), LF_SLIST::link, my_free(), next(), and unlikely.
lf_hash_init()
void lf_hash_init (LF_HASH * hash, uint element_size, uint flags, uint key_offset, uint key_length, my_hash_get_key get_key, CHARSET_INFO * charset)
Definition at line 313 of file lf_hash.c.
 {
   lf_alloc_init(&hash->alloc, sizeof(LF_SLIST)+element_size,
                 offsetof(LF_SLIST, key));
   lf_dynarray_init(&hash->array, sizeof(LF_SLIST *));
   hash->size= 1;
   hash->count= 0;
   hash->element_size= element_size;
   hash->flags= flags;
   hash->charset= charset ? charset : &my_charset_bin;
   hash->key_offset= key_offset;
   hash->key_length= key_length;
   hash->get_key= get_key;
   DBUG_ASSERT(get_key ? !key_offset && !key_length : key_length);
 }
References DBUG_ASSERT, hash(), lf_alloc_init(), lf_dynarray_init(), my_charset_bin, and offsetof.
lf_hash_insert()
int lf_hash_insert (LF_HASH * hash, LF_PINS * pins, const void * data)
Definition at line 365 of file lf_hash.c.
 {
   int csize, bucket, hashnr;
   LF_SLIST *node, * volatile *el;
   lf_rwlock_by_pins(pins);
   node= (LF_SLIST *)_lf_alloc_new(pins);
   if (unlikely(!node))
     return -1;
   memcpy(node+1, data, hash->element_size);
   node->key= hash_key(hash, (uchar *)(node+1), &node->keylen);
   hashnr= calc_hash(hash, node->key, node->keylen);
   bucket= hashnr % hash->size;
   el= _lf_dynarray_lvalue(&hash->array, bucket);
   if (unlikely(!el))
     return -1;
   if (*el == NULL && unlikely(initialize_bucket(hash, el, bucket, pins)))
     return -1;
   node->hashnr= my_reverse_bits(hashnr) | 1; /* normal node */
   if (linsert(el, hash->charset, node, pins, hash->flags))
   {
     _lf_alloc_free(pins, node);
     lf_rwunlock_by_pins(pins);
     return 1;
   }
   csize= hash->size;
   if ((my_atomic_add32(&hash->count, 1)+1.0) / csize > MAX_LOAD)
     my_atomic_cas32(&hash->size, &csize, csize*2);
   lf_rwunlock_by_pins(pins);
   return 0;
 }
References _lf_alloc_free, _lf_alloc_new(), _lf_dynarray_lvalue(), calc_hash(), hash(), hash_key(), LF_SLIST::hashnr, initialize_bucket(), LF_SLIST::key, LF_SLIST::keylen, lf_rwlock_by_pins, lf_rwunlock_by_pins, linsert(), MAX_LOAD, memcpy, my_reverse_bits(), NULL, pins, and unlikely.
lf_hash_search()
void* lf_hash_search (LF_HASH * hash, LF_PINS * pins, const void * key, uint keylen)
Definition at line 448 of file lf_hash.c.
 {
   LF_SLIST * volatile *el, *found;
   uint bucket, hashnr= calc_hash(hash, (uchar *)key, keylen);
   bucket= hashnr % hash->size;
   lf_rwlock_by_pins(pins);
   el= _lf_dynarray_lvalue(&hash->array, bucket);
   if (unlikely(!el))
     return MY_ERRPTR;
   if (*el == NULL && unlikely(initialize_bucket(hash, el, bucket, pins)))
     return MY_ERRPTR;
   found= lsearch(el, hash->charset, my_reverse_bits(hashnr) | 1,
                  (uchar *)key, keylen, pins);
   lf_rwunlock_by_pins(pins);
   return found ? found+1 : 0;
 }
References _lf_dynarray_lvalue(), calc_hash(), hash(), initialize_bucket(), lf_rwlock_by_pins, lf_rwunlock_by_pins, lsearch(), MY_ERRPTR, my_reverse_bits(), NULL, pins, and unlikely.
lfind()
static int lfind (LF_SLIST *volatile * head, CHARSET_INFO * cs, uint32 hashnr, const uchar * key, uint keylen, CURSOR * cursor, LF_PINS * pins) static
Definition at line 73 of file lf_hash.c.
 {
   uint32       cur_hashnr;
   const uchar  *cur_key;
   uint         cur_keylen;
   intptr       link;
 retry:
   cursor->prev= (intptr *)head;
   do { /* PTR() isn't necessary below, head is a dummy node */
     cursor->curr= (LF_SLIST *)(*cursor->prev);
     _lf_pin(pins, 1, cursor->curr);
   } while (*cursor->prev != (intptr)cursor->curr && LF_BACKOFF);
   for (;;)
   {
     if (unlikely(!cursor->curr))
       return 0; /* end of the list */
     do {
       /* QQ: XXX or goto retry ? */
       link= cursor->curr->link;
       cursor->next= PTR(link);
       _lf_pin(pins, 0, cursor->next);
     } while (link != cursor->curr->link && LF_BACKOFF);
     cur_hashnr= cursor->curr->hashnr;
     cur_key= cursor->curr->key;
     cur_keylen= cursor->curr->keylen;
     if (*cursor->prev != (intptr)cursor->curr)
     {
       (void)LF_BACKOFF;
       goto retry;
     }
     if (!DELETED(link))
     {
       if (cur_hashnr >= hashnr)
       {
         int r= 1;
         if (cur_hashnr > hashnr ||
             (r= my_strnncoll(cs, (uchar*) cur_key, cur_keylen, (uchar*) key,
                              keylen)) >= 0)
           return !r;
       }
       cursor->prev= &(cursor->curr->link);
       _lf_pin(pins, 2, cursor->curr);
     }
     else
     {
       /*
         we found a deleted node - be nice, help the other thread
         and remove this deleted node
       */
       if (my_atomic_casptr((void **)cursor->prev,
                            (void **)&cursor->curr, cursor->next))
         _lf_alloc_free(pins, cursor->curr);
       else
       {
         (void)LF_BACKOFF;
         goto retry;
       }
     }
     cursor->curr= cursor->next;
     _lf_pin(pins, 1, cursor->curr);
   }
 }
References _lf_alloc_free, _lf_pin, CURSOR::curr, DELETED, LF_SLIST::hashnr, LF_SLIST::key, LF_SLIST::keylen, LF_BACKOFF, LF_SLIST::link, my_strnncoll, CURSOR::next, pins, CURSOR::prev, PTR, and unlikely.
Referenced by ldelete(), linsert(), and lsearch().
linsert()
static LF_SLIST* linsert (LF_SLIST *volatile * head, CHARSET_INFO * cs, LF_SLIST * node, LF_PINS * pins, uint flags) static
Definition at line 151 of file lf_hash.c.
 {
   CURSOR         cursor;
   int            res;
   for (;;)
   {
     if (lfind(head, cs, node->hashnr, node->key, node->keylen,
               &cursor, pins) &&
         (flags & LF_HASH_UNIQUE))
     {
       res= 0; /* duplicate found */
       break;
     }
     else
     {
       node->link= (intptr)cursor.curr;
       DBUG_ASSERT(node->link != (intptr)node); /* no circular references */
       DBUG_ASSERT(cursor.prev != &node->link); /* no circular references */
       if (my_atomic_casptr((void **)cursor.prev, (void **)&cursor.curr, node))
       {
         res= 1; /* inserted ok */
         break;
       }
     }
   }
   _lf_unpin(pins, 0);
   _lf_unpin(pins, 1);
   _lf_unpin(pins, 2);
   /*
     Note that cursor.curr is not pinned here and the pointer is unreliable,
     the object may dissapear anytime. But if it points to a dummy node, the
     pointer is safe, because dummy nodes are never freed - initialize_bucket()
     uses this fact.
   */
   return res ? 0 : cursor.curr;
 }
References _lf_unpin, CURSOR::curr, DBUG_ASSERT, LF_SLIST::hashnr, LF_SLIST::key, LF_SLIST::keylen, LF_HASH_UNIQUE, lfind(), LF_SLIST::link, pins, and CURSOR::prev.
Referenced by initialize_bucket(), and lf_hash_insert().
lsearch()
static LF_SLIST* lsearch (LF_SLIST *volatile * head, CHARSET_INFO * cs, uint32 hashnr, const uchar * key, uint keylen, LF_PINS * pins) static
Definition at line 260 of file lf_hash.c.
 {
   CURSOR cursor;
   int res= lfind(head, cs, hashnr, key, keylen, &cursor, pins);
   if (res)
     _lf_pin(pins, 2, cursor.curr);
   _lf_unpin(pins, 0);
   _lf_unpin(pins, 1);
   return res ? cursor.curr : 0;
 }
References _lf_pin, _lf_unpin, CURSOR::curr, lfind(), and pins.
Referenced by lf_hash_search().
Variable Documentation
dummy_key
const uchar* dummy_key = (uchar*)"" static
Definition at line 466 of file lf_hash.c.
Referenced by initialize_bucket().