Azerotcore-wotlk: npc_razael_and_lyana Class Reference
npc_razael_and_lyana Class Reference
Public Member Functions
npc_razael_and_lyana ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 327 of file zone_howling_fjord.cpp.
Constructor & Destructor Documentation
npc_razael_and_lyana()
npc_razael_and_lyana::npc_razael_and_lyana () inline
Definition at line 330 of file zone_howling_fjord.cpp.
 : CreatureScript("npc_razael_and_lyana") { }
Member Function Documentation
OnGossipHello()
bool npc_razael_and_lyana::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 332 of file zone_howling_fjord.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (player->GetQuestStatus(QUEST_REPORTS_FROM_THE_FIELD) == QUEST_STATUS_INCOMPLETE)
             switch (creature->GetEntry())
             {
                 case NPC_RAZAEL:
                     if (!player->GetReqKillOrCastCurrentCount(QUEST_REPORTS_FROM_THE_FIELD, NPC_RAZAEL))
                     {
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_RAZAEL_REPORT, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                         SendGossipMenuFor(player, GOSSIP_TEXTID_RAZAEL1, creature->GetGUID());
                         return true;
                     }
                     break;
                 case NPC_LYANA:
                     if (!player->GetReqKillOrCastCurrentCount(QUEST_REPORTS_FROM_THE_FIELD, NPC_LYANA))
                     {
                         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LYANA_REPORT, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                         SendGossipMenuFor(player, GOSSIP_TEXTID_LYANA1, creature->GetGUID());
                         return true;
                     }
                     break;
             }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), Player::GetReqKillOrCastCurrentCount(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_LYANA_REPORT, GOSSIP_RAZAEL_REPORT, GOSSIP_SENDER_MAIN, GOSSIP_TEXTID_LYANA1, GOSSIP_TEXTID_RAZAEL1, Unit::IsQuestGiver(), NPC_LYANA, NPC_RAZAEL, Player::PrepareQuestMenu(), QUEST_REPORTS_FROM_THE_FIELD, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_razael_and_lyana::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 361 of file zone_howling_fjord.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_RAZAEL2, creature->GetGUID());
                 player->TalkedToCreature(NPC_RAZAEL, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 SendGossipMenuFor(player, GOSSIP_TEXTID_LYANA2, creature->GetGUID());
                 player->TalkedToCreature(NPC_LYANA, creature->GetGUID());
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_TEXTID_LYANA2, GOSSIP_TEXTID_RAZAEL2, NPC_LYANA, NPC_RAZAEL, SendGossipMenuFor(), and Player::TalkedToCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_howling_fjord.cpp