Azerotcore-wotlk: WaypointMovementGenerator< Creature > Class Reference
WaypointMovementGenerator< Creature > Class Reference
#include <WaypointMovementGenerator.h>
Public Member Functions
WaypointMovementGenerator (uint32 _path_id=0, bool _repeating=true)
~WaypointMovementGenerator ()
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoReset (Creature *)
bool DoUpdate (Creature *, uint32 diff)
void MovementInform (Creature *)
MovementGeneratorType GetMovementGeneratorType ()
void LoadPath (Creature *)
Public Member Functions inherited from MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from PathMovementBase< Creature, WaypointPath const * >
PathMovementBase ()
PathMovementBase (WaypointPath const * path)
virtual ~PathMovementBase ()
uint32 GetCurrentNode () const
Private Member Functions
void Stop (int32 time)
bool Stopped ()
bool CanMove (int32 diff)
void OnArrived (Creature *)
bool StartMove (Creature *)
void StartMoveNow (Creature *creature)
Private Attributes
TimeTrackerSmall i_nextMoveTime
bool m_isArrivalDone
uint32 path_id
bool repeating
Additional Inherited Members
Protected Attributes inherited from PathMovementBase< Creature, WaypointPath const * >
WaypointPath const * i_path
uint32 i_currentNode
Detailed Description
Definition at line 53 of file WaypointMovementGenerator.h.
Constructor & Destructor Documentation
WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::WaypointMovementGenerator (uint32 _path_id = 0, bool _repeating = true) inline
Definition at line 57 of file WaypointMovementGenerator.h.
         : PathMovementBase((WaypointPath const*)nullptr), i_nextMoveTime(0), m_isArrivalDone(false), path_id(_path_id), repeating(_repeating)  {}
~WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::~WaypointMovementGenerator () inline
Definition at line 59 of file WaypointMovementGenerator.h.
 { i_path = nullptr; }
Member Function Documentation
CanMove()
bool WaypointMovementGenerator< Creature >::CanMove (int32 diff) inline private
Definition at line 77 of file WaypointMovementGenerator.h.
     {
         i_nextMoveTime.Update(diff);
         return i_nextMoveTime.Passed();
     }
DoFinalize()
void WaypointMovementGenerator< Creature >::DoFinalize (Creature * creature)
Definition at line 55 of file WaypointMovementGenerator.cpp.
 {
     creature->ClearUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     creature->SetWalk(false);
 }
References Unit::ClearUnitState(), Creature::SetWalk(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoInitialize()
void WaypointMovementGenerator< Creature >::DoInitialize (Creature * creature)
Definition at line 49 of file WaypointMovementGenerator.cpp.
 {
     LoadPath(creature);
     creature->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
 }
References Unit::AddUnitState(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoReset()
void WaypointMovementGenerator< Creature >::DoReset (Creature * creature)
Definition at line 61 of file WaypointMovementGenerator.cpp.
 {
     creature->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     StartMoveNow(creature);
 }
References Unit::AddUnitState(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoUpdate()
bool WaypointMovementGenerator< Creature >::DoUpdate (Creature * creature, uint32 diff)
Definition at line 205 of file WaypointMovementGenerator.cpp.
 {
     // Waypoint movement can be switched on/off
     // This is quite handy for escort quests and other stuff
     if (creature->HasUnitState(UNIT_STATE_NOT_MOVE) || creature->IsMovementPreventedByCasting())
     {
         creature->StopMoving();
         Stop(1000);
         return true;
     }
     // prevent a crash at empty waypoint path.
     if (!i_path || i_path->empty())
         return false;
     // Xinef: Dont allow dead creatures to move
     if (!creature->IsAlive())
         return false;
     if (Stopped())
     {
         if (CanMove(diff))
             return StartMove(creature);
     }
     else
     {
         if (creature->IsStopped())
             Stop(sWorld->getIntConfig(CONFIG_WAYPOINT_MOVEMENT_STOP_TIME_FOR_PLAYER) * IN_MILLISECONDS);
         else
         {
             bool finished = creature->movespline->Finalized();
             // xinef: code to detect pre-empetively if we should start movement to next waypoint
             // xinef: do not start pre-empetive movement if current node has delay or we are ending waypoint movement
             //if (!finished && !i_path->at(i_currentNode)->delay && ((i_currentNode != i_path->size() - 1) || repeating))
             //    finished = (creature->movespline->_Spline().length(creature->movespline->_currentSplineIdx() + 1) - creature->movespline->timePassed()) < 200;
             if (finished)
             {
                 OnArrived(creature);
                 return StartMove(creature);
             }
         }
     }
     return true;
 }
References CONFIG_WAYPOINT_MOVEMENT_STOP_TIME_FOR_PLAYER, Movement::MoveSpline::Finalized(), Unit::HasUnitState(), IN_MILLISECONDS, Unit::IsAlive(), Creature::IsMovementPreventedByCasting(), Unit::IsStopped(), Unit::movespline, Unit::StopMoving(), sWorld, and UNIT_STATE_NOT_MOVE.
GetMovementGeneratorType()
MovementGeneratorType WaypointMovementGenerator< Creature >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 67 of file WaypointMovementGenerator.h.
 { return WAYPOINT_MOTION_TYPE; }
References WAYPOINT_MOTION_TYPE.
LoadPath()
void WaypointMovementGenerator< Creature >::LoadPath (Creature * creature)
Definition at line 31 of file WaypointMovementGenerator.cpp.
 {
     if (!path_id)
         path_id = creature->GetWaypointPath();
     i_path = sWaypointMgr->GetPath(path_id);
     if (!i_path)
     {
         // No movement found for entry
         LOG_ERROR("sql.sql", "WaypointMovementGenerator::LoadPath: creature %s (%s) doesn't have waypoint path id: %u",
             creature->GetName().c_str(), creature->GetGUID().ToString().c_str(), path_id);
         return;
     }
     StartMoveNow(creature);
 }
References Object::GetGUID(), WorldObject::GetName(), Creature::GetWaypointPath(), LOG_ERROR, sWaypointMgr, and ObjectGuid::ToString().
MovementInform()
void WaypointMovementGenerator< Creature >::MovementInform (Creature * creature)
Definition at line 251 of file WaypointMovementGenerator.cpp.
 {
     if (creature->AI())
         creature->AI()->MovementInform(WAYPOINT_MOTION_TYPE, i_currentNode);
 }
References Creature::AI(), CreatureAI::MovementInform(), and WAYPOINT_MOTION_TYPE.
OnArrived()
void WaypointMovementGenerator< Creature >::OnArrived (Creature * creature) private
Definition at line 67 of file WaypointMovementGenerator.cpp.
 {
     if (!i_path || i_path->empty())
         return;
     if (m_isArrivalDone)
         return;
     creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
     m_isArrivalDone = true;
     if (i_path->at(i_currentNode)->event_id && urand(0, 99) < i_path->at(i_currentNode)->event_chance)
     {
         LOG_DEBUG("maps.script", "Creature movement start script %u at point %u for %s.",
             i_path->at(i_currentNode)->event_id, i_currentNode, creature->GetGUID().ToString().c_str());
         creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
         creature->GetMap()->ScriptsStart(sWaypointScripts, i_path->at(i_currentNode)->event_id, creature, nullptr);
     }
     // Inform script
     MovementInform(creature);
     creature->UpdateWaypointID(i_currentNode);
     if (i_path->at(i_currentNode)->delay)
     {
         creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
         Stop(i_path->at(i_currentNode)->delay);
     }
 }
References Unit::ClearUnitState(), Object::GetGUID(), WorldObject::GetMap(), LOG_DEBUG, Map::ScriptsStart(), sWaypointScripts, ObjectGuid::ToString(), UNIT_STATE_ROAMING_MOVE, Creature::UpdateWaypointID(), and urand().
StartMove()
bool WaypointMovementGenerator< Creature >::StartMove (Creature * creature) private
If creature is on transport, we assume waypoints set in DB are already transport offsets
Do not use formationDest here, MoveTo requires transport offsets due to DisableTransportPathTransformations() call but formationDest contains global coordinates
Accepts angles such as 0.00001 and -0.00001, 0 must be ignored, default value in waypoint table
Definition at line 96 of file WaypointMovementGenerator.cpp.
 {
     if (!i_path || i_path->empty())
         return false;
     // Xinef: Dont allow dead creatures to move
     if (!creature->IsAlive())
         return false;
     if (Stopped())
         return true;
     bool transportPath = creature->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && creature->GetTransGUID();
     if (m_isArrivalDone)
     {
         // Xinef: not true... update this at every waypoint!
         //if ((i_currentNode == i_path->size() - 1) && !repeating) // If that's our last waypoint
         {
             float x = i_path->at(i_currentNode)->x;
             float y = i_path->at(i_currentNode)->y;
             float z = i_path->at(i_currentNode)->z;
             float o = creature->GetOrientation();
             if (!transportPath)
                 creature->SetHomePosition(x, y, z, o);
             else
             {
                 if (Transport* trans = (creature->GetTransport() ? creature->GetTransport()->ToMotionTransport() : nullptr))
                 {
                     o -= trans->GetOrientation();
                     creature->SetTransportHomePosition(x, y, z, o);
                     trans->CalculatePassengerPosition(x, y, z, &o);
                     creature->SetHomePosition(x, y, z, o);
                 }
                 else
                     transportPath = false;
                 // else if (vehicle) - this should never happen, vehicle offsets are const
             }
         }
         // Xinef: moved the upper IF here
         if ((i_currentNode == i_path->size() - 1) && !repeating) // If that's our last waypoint
         {
             creature->GetMotionMaster()->Initialize();
             return false;
         }
         i_currentNode = (i_currentNode + 1) % i_path->size();
     }
     // xinef: do not initialize motion if we got stunned in movementinform
     if (creature->HasUnitState(UNIT_STATE_NOT_MOVE) || creature->IsMovementPreventedByCasting())
     {
         return true;
     }
     WaypointData const* node = i_path->at(i_currentNode);
     m_isArrivalDone = false;
     creature->AddUnitState(UNIT_STATE_ROAMING_MOVE);
     Movement::Location formationDest(node->x, node->y, node->z, 0.0f);
     Movement::MoveSplineInit init(creature);
     if (transportPath)
     {
         init.DisableTransportPathTransformations();
         if (TransportBase* trans = creature->GetDirectTransport())
             trans->CalculatePassengerPosition(formationDest.x, formationDest.y, formationDest.z, &formationDest.orientation);
     }
     float z = node->z;
     creature->UpdateAllowedPositionZ(node->x, node->y, z);
     init.MoveTo(node->x, node->y, z, true, true);
     if (node->orientation && node->delay)
         init.SetFacing(node->orientation);
     switch (node->move_type)
     {
         case WAYPOINT_MOVE_TYPE_LAND:
             init.SetAnimation(Movement::ToGround);
             break;
         case WAYPOINT_MOVE_TYPE_TAKEOFF:
             init.SetAnimation(Movement::ToFly);
             break;
         case WAYPOINT_MOVE_TYPE_RUN:
             init.SetWalk(false);
             break;
         case WAYPOINT_MOVE_TYPE_WALK:
             init.SetWalk(true);
             break;
     }
     init.Launch();
     //Call for creature group update
     if (creature->GetFormation() && creature->GetFormation()->getLeader() == creature)
         creature->GetFormation()->LeaderMoveTo(formationDest.x, formationDest.y, formationDest.z, node->move_type == WAYPOINT_MOVE_TYPE_RUN);
     return true;
 }
References Unit::AddUnitState(), WaypointData::delay, Movement::MoveSplineInit::DisableTransportPathTransformations(), Unit::GetDirectTransport(), Creature::GetFormation(), CreatureGroup::getLeader(), Unit::GetMotionMaster(), Position::GetOrientation(), Unit::GetTransGUID(), WorldObject::GetTransport(), Unit::HasUnitMovementFlag(), Unit::HasUnitState(), MotionMaster::Initialize(), Unit::IsAlive(), Creature::IsMovementPreventedByCasting(), Movement::MoveSplineInit::Launch(), CreatureGroup::LeaderMoveTo(), WaypointData::move_type, MOVEMENTFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), Movement::Location::orientation, WaypointData::orientation, Movement::MoveSplineInit::SetAnimation(), Movement::MoveSplineInit::SetFacing(), Creature::SetHomePosition(), Creature::SetTransportHomePosition(), Movement::MoveSplineInit::SetWalk(), Movement::ToFly, Movement::ToGround, GameObject::ToMotionTransport(), UNIT_STATE_NOT_MOVE, UNIT_STATE_ROAMING_MOVE, WorldObject::UpdateAllowedPositionZ(), WAYPOINT_MOVE_TYPE_LAND, WAYPOINT_MOVE_TYPE_RUN, WAYPOINT_MOVE_TYPE_TAKEOFF, WAYPOINT_MOVE_TYPE_WALK, WaypointData::x, WaypointData::y, and WaypointData::z.
StartMoveNow()
void WaypointMovementGenerator< Creature >::StartMoveNow (Creature * creature) inline private
Definition at line 86 of file WaypointMovementGenerator.h.
     {
         i_nextMoveTime.Reset(0);
         StartMove(creature);
     }
Stop()
void WaypointMovementGenerator< Creature >::Stop (int32 time) inline private
Definition at line 73 of file WaypointMovementGenerator.h.
 { i_nextMoveTime.Reset(time);}
Stopped()
bool WaypointMovementGenerator< Creature >::Stopped () inline private
Definition at line 75 of file WaypointMovementGenerator.h.
 { return !i_nextMoveTime.Passed();}
Member Data Documentation
i_nextMoveTime
TimeTrackerSmall WaypointMovementGenerator< Creature >::i_nextMoveTime private
Definition at line 92 of file WaypointMovementGenerator.h.
m_isArrivalDone
bool WaypointMovementGenerator< Creature >::m_isArrivalDone private
Definition at line 93 of file WaypointMovementGenerator.h.
path_id
uint32 WaypointMovementGenerator< Creature >::path_id private
Definition at line 94 of file WaypointMovementGenerator.h.
repeating
bool WaypointMovementGenerator< Creature >::repeating private
Definition at line 95 of file WaypointMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp