Azerotcore-wotlk: G3D::MD5Hash Class Reference
G3D::MD5Hash Class Reference
#include <Crypto.h>
Public Member Functions
MD5Hash ()
MD5Hash (class BinaryInput &b)
void rotateBytes ()
void rotateBytes (int n)
uint8 & operator[] (int i)
const uint8 & operator[] (int i) const
bool operator== (const MD5Hash &other) const
bool operator!= (const MD5Hash &other) const
void deserialize (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
Static Public Member Functions
static size_t hashCode (const MD5Hash &key)
Private Attributes
uint8 value [16]
Detailed Description
See G3D::Crypto::md5
Definition at line 22 of file Crypto.h.
Constructor & Destructor Documentation
MD5Hash() [1/2]
G3D::MD5Hash::MD5Hash () inline
Definition at line 29 of file Crypto.h.
               {
         for (int i = 0; i < 16; ++i) {
             value[i] = 0;
         }
     }
MD5Hash() [2/2]
G3D::MD5Hash::MD5Hash (class BinaryInput & b) explicit
Definition at line 21 of file Crypto_md5.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Member Function Documentation
deserialize()
void G3D::MD5Hash::deserialize (class BinaryInput & b)
Definition at line 26 of file Crypto_md5.cpp.
{
     b.readBytes(value, 16);
 }
References b.
Referenced by MD5Hash().
hashCode()
static size_t G3D::MD5Hash::hashCode (const MD5Hash & key) inline static
Definition at line 79 of file Crypto.h.
{
         size_t h = 0;
         for (int i = 0; i < 4; ++i) {
             const int x = i * 4;
             h ^= (((uint32)key.value[x + 0]) << 24) |
                 (((uint32)key.value[x + 1]) << 16) |
                 (((uint32)key.value[x + 2]) << 8) |
                 ((uint32)key.value[x + 3]);
         }
         return h;
     }
References value, and G3D::x.
operator!=()
bool G3D::MD5Hash::operator!= (const MD5Hash & other) const inline
Definition at line 71 of file Crypto.h.
{
         return !(*this == other);
     }
operator==()
bool G3D::MD5Hash::operator== (const MD5Hash & other) const inline
Definition at line 63 of file Crypto.h.
{
         bool match = true;
         for (int i = 0; i < 16; ++i) {
             match = match && (other.value[i] == value[i]);
         }
         return match;
     }
References value.
operator[]() [1/2]
uint8& G3D::MD5Hash::operator[] (int i) inline
Definition at line 55 of file Crypto.h.
{
         return value[i];
     }
operator[]() [2/2]
const uint8& G3D::MD5Hash::operator[] (int i) const inline
Definition at line 59 of file Crypto.h.
{
         return value[i];
     }
rotateBytes() [1/2]
void G3D::MD5Hash::rotateBytes () inline
Rotates the bytes once
Definition at line 38 of file Crypto.h.
{
         uint8 temp = value[0];
         for (int i = 0; i < 15; ++i) {
             value[i] = value[i + 1];
         }
         value[15] = temp;
     }
rotateBytes() [2/2]
void G3D::MD5Hash::rotateBytes (int n) inline
Rotates by n bytes
Definition at line 47 of file Crypto.h.
{
         uint8 temp[16];
         System::memcpy(temp, value, 16);
         for (int i = 0; i < 16; ++i) {
             value[i] = value[(i + n) & 15];
         }
     }
References G3D::System::memcpy().
serialize()
void G3D::MD5Hash::serialize (class BinaryOutput & b) const
Definition at line 31 of file Crypto_md5.cpp.
{
     b.writeBytes(value, 16);
 }
References b.
Member Data Documentation
value
uint8 G3D::MD5Hash::value[16] private
Definition at line 25 of file Crypto.h.
Referenced by hashCode(), and operator==().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Crypto.h
deps/g3dlite/source/Crypto_md5.cpp