Azerotcore-wotlk: G3D::AnyVal Class Reference
G3D::AnyVal Class Reference
#include <AnyVal.h>
Classes
class CorruptText
class Exception
class IndexOutOfBounds
class KeyNotFound
class WrongType
Public Types
enum Type {
NIL , NUMBER , BOOLEAN , STRING ,
VECTOR2 , VECTOR3 , VECTOR4 , MATRIX2 ,
MATRIX3 , MATRIX4 , QUAT , COORDINATEFRAME ,
COORDINATEFRAME2D , CFRAME = COORDINATEFRAME , CFRAME2D = COORDINATEFRAME2D , COLOR1 ,
COLOR3 , COLOR4 , RECT2D , AABOX2D = RECT2D ,
AABOX , ARRAY , TABLE
}
Public Member Functions
AnyVal ()
AnyVal (G3D::TextInput &t)
void load (const std::string &filename)
void save (const std::string &filename) const
AnyVal (double)
‍** Deserialize *‍/
AnyVal (int)
AnyVal (bool)
AnyVal (const G3D::Vector2 &)
AnyVal (const G3D::Vector3 &)
AnyVal (const G3D::Vector4 &)
AnyVal (const G3D::Color1 &)
AnyVal (const G3D::Color3 &)
AnyVal (const G3D::Color4 &)
AnyVal (const std::string &)
AnyVal (const char *)
AnyVal (const G3D::Quat &)
AnyVal (const G3D::Rect2D &)
AnyVal (const G3D::AABox &)
AnyVal (const G3D::CoordinateFrame &)
AnyVal (const G3D::Matrix2 &)
AnyVal (const G3D::Matrix3 &)
AnyVal (const G3D::Matrix4 &)
AnyVal (const AnyVal &)
AnyVal (Type arrayOrTable)
AnyVal & operator= (const AnyVal &)
~AnyVal ()
Type type () const
bool isNil () const
void serialize (G3D::TextOutput &t) const
void deserialize (G3D::TextInput &t)
const AnyVal & operator[] (int) const
void append (const AnyVal &)
AnyVal & operator[] (int)
const AnyVal & get (int i, const AnyVal &defaultVal) const
const AnyVal & get (int i) const
const AnyVal & get (const std::string &key, const AnyVal &defaultVal) const
const AnyVal & get (const std::string &key) const
const AnyVal & operator[] (const std::string &) const
AnyVal & operator[] (const std::string &)
const AnyVal & operator[] (const char *) const
AnyVal & operator[] (const char *)
double number () const
double number (double defaultVal) const
operator double () const
operator float () const
bool boolean () const
bool boolean (bool b) const
operator bool () const
const std::string & string () const
const std::string & string (const std::string &defaultVal) const
operator const std::string & () const
const G3D::Rect2D & rect2D () const
const G3D::Rect2D & rect2D (const G3D::Rect2D &defaultVal) const
operator const Rect2D & () const
const G3D::AABox & aabox () const
const G3D::AABox & aabox (const G3D::AABox &defaultVal) const
operator const AABox & () const
const G3D::Vector2 & vector2 () const
const G3D::Vector2 & vector2 (const G3D::Vector2 &defaultVal) const
operator const Vector2 & () const
const G3D::Vector3 & vector3 () const
const G3D::Vector3 & vector3 (const G3D::Vector3 &defaultVal) const
operator const Vector3 & ()
const G3D::Vector4 & vector4 () const
const G3D::Vector4 & vector4 (const G3D::Vector4 &defaultVal) const
operator const Vector4 & () const
const G3D::Color1 & color1 () const
const G3D::Color1 & color1 (const G3D::Color1 &defaultVal) const
const G3D::Color3 & color3 () const
const G3D::Color3 & color3 (const G3D::Color3 &defaultVal) const
operator const Color3 & () const
const G3D::Color4 & color4 () const
const G3D::Color4 & color4 (const G3D::Color4 &defaultVal) const
operator const Color4 & () const
const G3D::CoordinateFrame & coordinateFrame () const
const G3D::CoordinateFrame & coordinateFrame (const G3D::CoordinateFrame &defaultVal) const
operator const CoordinateFrame & () const
const G3D::Matrix2 & matrix2 () const
const G3D::Matrix2 & matrix2 (const G3D::Matrix2 &defaultVal) const
operator const Matrix2 & () const
const G3D::Matrix3 & matrix3 () const
const G3D::Matrix3 & matrix3 (const G3D::Matrix3 &defaultVal) const
operator const Matrix3 & () const
const G3D::Matrix4 & matrix4 () const
const G3D::Matrix4 & matrix4 (const G3D::Matrix4 &defaultVal) const
operator const Matrix4 & () const
const G3D::Quat & quat () const
const G3D::Quat & quat (const G3D::Quat &defaultVal) const
operator const Quat & () const
std::string toString () const
int size () const
void getKeys (G3D::Array< std::string > &) const
Static Public Member Functions
static AnyVal fromFile (const std::string &filename)
Private Member Functions
void deleteValue ()
void * copyValue () const
void makeMutable ()
bool isShared () const
bool isSharedType () const
Private Attributes
Type m_type
void * m_value
int * m_referenceCount
Detailed Description
Deprecated:
Use the G3D::Any class instead. This is only provided for backwards compatibility to G3D 7.xx.
A generic value, useful for defining property trees that can be loaded from and saved to disk. The values are intentionally restricted to a small set.
When written to files, the syntax is as follows. Note that you can nest arrays and tables in order to create full tree (i.e., XML-like) structures as configuration files:
NULL Nil
double The number in printf double format
bool true or false
std::string The string in double-quotes (")
Rect2D R(x0,y0,x1,y1)
Color1 C1(value)
Color3 C3(r,g,b)
Color4 C4(r,g,b,a)
Vector2 V2(x,y)
Vector3 V3(x,y,z)
Vector4 V4(x,y,z,w)
Quat V(x,y,z,w)
AABox AAB(low Vector3, high Vector3)
Matrix2 M2(r0c0, r0c1,
r1c0, r1c1)
Matrix3 M3(r0c0, r0c1, r0c2,
r1c0, r1c1, r1c2,
r2c0, r2c1, r2c2)
Matrix4 M4(r0c0, r0c1, r0c2, r0c3,
r1c0, r1c1, r1c2, r1c3,
r2c0, r2c1, r2c2, r2c3,
r3c0, r3c1, r3c2, r3c3)
CoordinateFrame CF(r0c0, r0c1, r0c2, r0c3,
r1c0, r1c1, r1c2, r1c3,
r2c0, r2c1, r2c2, r2c3)
CoordinateFrame
CF(V3(x, y, z), yaw deg, pitch deg, optional roll deg)
Array [element0, element1, ... , elementn-1]
Table {symbol0 = value0
symbol1 = value1
...
symboln-1 = valuen-1}
See also boost::any for a more general purpose but slightly harder to use "any" for C++.
The semantics of operator[] and the get() methods are slightly different; operator[] acts more like a scripting language that automatically extends arrays and tables instead of generating errors. get() has more strict semantics, like a C++ class.
AnyVal uses copy-on-mutate, so that AnyVal a = b semantically copies b (like int a = b would), although in practice it delays the copy until one is mutated so that it is still fast to "copy" large arrays and tables.
Reading example:
    AnyVal property = AnyVal::fromFile("c:/tmp/test.txt"));
    Vector3 vel = property["angular velocity"]
    Using defaults to handle errors:
       If there was no "enabled" value, this will return the default instead of failing
    bool enabled = property["enabled"].boolean(true);
Writing to a file:
    AnyVal dict(AnyVal::TABLE);
    dict["enabled"] = AnyVal(true);
    dict["weight"] = 100;
    dict["angular velocity"] = Vector3(1, -3, 4.5);
    TextOutput t("c:/tmp/test.txt");
    dict.serialize(t);
    t.commit();
Example of a data file:
   {
      heights = [1, 17, 32]
      model =
        {
           color = C3(1, 1, 1)
           filename = "foo.md2"
        }
      position = V3(23, 14, 0)
      name = "Elmer"
   }
What's the difference from boost::any?
I think that AnyVal will be easier for novice C++ users. It addresses the problem that even though G3D::TextInput makes reading configuration files extremely simple, many people still don't use it. So AnyVal makes it ridiculously simple to read and write a tree of G3D types to a file.
AnyVal:
{
AnyVal tree(TextInput("config.txt"));
bool enabled = tree.get("enabled", false);
Vector3 direction = tree.get("direction", Vector3::zero());
...
}
boost:
{
bool enabled = false;
Vector3 direction;
Table<boost::any> tree;
 ...write lots of file parsing code...
   if (tree.containsKey("enabled")) {
      const boost::any& val = tree["enabled"];
      try {
        enabled = any_cast<bool>(val);
      } catch(const boost::bad_any_cast &) {
      }
    }
   if (tree.containsKey("direction")) {
      const boost::any& val = tree["direction"];
      try {
        direction = any_cast<Vector3>(val);
      } catch(const boost::bad_any_cast &) {
      }
    }
   ...
}
Deprecated:
Definition at line 182 of file AnyVal.h.
Member Enumeration Documentation
Type
enum G3D::AnyVal::Type
Array and table values are all Any.
Enumerator
NIL
NUMBER
BOOLEAN
STRING
VECTOR2
VECTOR3
VECTOR4
MATRIX2
MATRIX3
MATRIX4
QUAT
COORDINATEFRAME
COORDINATEFRAME2D
CFRAME
CFRAME2D
COLOR1
COLOR3
COLOR4
RECT2D
AABOX2D
AABOX
ARRAY
TABLE
Definition at line 186 of file AnyVal.h.
               {
         NIL,
         NUMBER,
         BOOLEAN,
         STRING,
         VECTOR2,
         VECTOR3,
         VECTOR4,
         MATRIX2,
         MATRIX3,
         MATRIX4,
         QUAT,
         COORDINATEFRAME,
         COORDINATEFRAME2D,
         CFRAME = COORDINATEFRAME,
         CFRAME2D = COORDINATEFRAME2D,
         COLOR1,
         COLOR3,
         COLOR4,
         RECT2D,
         AABOX2D = RECT2D,
         AABOX,
         ARRAY,
         TABLE};
Constructor & Destructor Documentation
AnyVal() [1/22]
G3D::AnyVal::AnyVal ()
Definition at line 51 of file AnyVal.cpp.
                : m_type(NIL), m_value(NULL), m_referenceCount(NULL) {
 }
Referenced by deserialize(), fromFile(), and operator[]().
AnyVal() [2/22]
G3D::AnyVal::AnyVal (G3D::TextInput & t) explicit
Deserialize
Definition at line 59 of file AnyVal.cpp.
                               : m_type(NIL), m_value(NULL), m_referenceCount(NULL) {
     deserialize(t);
 }
References deserialize().
AnyVal() [3/22]
G3D::AnyVal::AnyVal (double v)
‍** Deserialize *‍/
Construct a number
Definition at line 69 of file AnyVal.cpp.
                        : m_type(NUMBER), m_referenceCount(NULL) {
     m_value = new double(v);
 }
References m_value.
AnyVal() [4/22]
G3D::AnyVal::AnyVal (int v)
Definition at line 74 of file AnyVal.cpp.
                     : m_type(NUMBER), m_referenceCount(NULL) {
     m_value = new double(v);
 }
References m_value.
AnyVal() [5/22]
G3D::AnyVal::AnyVal (bool b)
Definition at line 55 of file AnyVal.cpp.
                      : m_type(BOOLEAN), m_value(new bool(b)), m_referenceCount(NULL) {
 }
AnyVal() [6/22]
G3D::AnyVal::AnyVal (const G3D::Vector2 & v)
Definition at line 89 of file AnyVal.cpp.
                                : m_type(VECTOR2), m_referenceCount(NULL) {
     m_value = new Vector2(v);
 }
References m_value.
AnyVal() [7/22]
G3D::AnyVal::AnyVal (const G3D::Vector3 & v)
Definition at line 94 of file AnyVal.cpp.
                                : m_type(VECTOR3), m_referenceCount(NULL) {
     m_value = new Vector3(v);
 }
References m_value.
AnyVal() [8/22]
G3D::AnyVal::AnyVal (const G3D::Vector4 & v)
Definition at line 99 of file AnyVal.cpp.
                                : m_type(VECTOR4), m_referenceCount(NULL) {
     m_value = new Vector4(v);
 }
References m_value.
AnyVal() [9/22]
G3D::AnyVal::AnyVal (const G3D::Color1 & v)
Definition at line 104 of file AnyVal.cpp.
                               : m_type(COLOR1), m_referenceCount(NULL) {
     m_value = new Color1(v);
 }
References m_value.
AnyVal() [10/22]
G3D::AnyVal::AnyVal (const G3D::Color3 & v)
Definition at line 109 of file AnyVal.cpp.
                               : m_type(COLOR3), m_referenceCount(NULL) {
     m_value = new Color3(v);
 }
References m_value.
AnyVal() [11/22]
G3D::AnyVal::AnyVal (const G3D::Color4 & v)
Definition at line 114 of file AnyVal.cpp.
                               : m_type(COLOR4), m_referenceCount(NULL) {
     m_value = new Color4(v);
 }
References m_value.
AnyVal() [12/22]
G3D::AnyVal::AnyVal (const std::string & v)
Definition at line 119 of file AnyVal.cpp.
                                  : m_type(STRING), m_referenceCount(NULL) {
     m_value = new std::string(v);
 }
References m_value.
AnyVal() [13/22]
G3D::AnyVal::AnyVal (const char * v)
Definition at line 124 of file AnyVal.cpp.
                             : m_type(STRING), m_referenceCount(NULL) {
     m_value = new std::string(v);
 }
References m_value.
AnyVal() [14/22]
G3D::AnyVal::AnyVal (const G3D::Quat & v)
Definition at line 129 of file AnyVal.cpp.
                             : m_type(QUAT), m_referenceCount(NULL) {
     m_value = new Quat(v);
 }
References m_value.
AnyVal() [15/22]
G3D::AnyVal::AnyVal (const G3D::Rect2D & v)
Definition at line 79 of file AnyVal.cpp.
                               : m_type(RECT2D), m_referenceCount(NULL) {
     m_value = new Rect2D(v);
 }
References m_value.
AnyVal() [16/22]
G3D::AnyVal::AnyVal (const G3D::AABox & v)
Definition at line 84 of file AnyVal.cpp.
                              : m_type(AABOX), m_referenceCount(NULL) {
     m_value = new AABox(v);
 }
References m_value.
AnyVal() [17/22]
G3D::AnyVal::AnyVal (const G3D::CoordinateFrame & v)
Definition at line 134 of file AnyVal.cpp.
                                        : m_type(COORDINATEFRAME), m_referenceCount(NULL) {
     m_value = new CoordinateFrame(v);
 }
References m_value.
AnyVal() [18/22]
G3D::AnyVal::AnyVal (const G3D::Matrix2 & v)
Definition at line 139 of file AnyVal.cpp.
                                : m_type(MATRIX2), m_referenceCount(NULL) {
     m_value = new Matrix2(v);
 }
References m_value.
AnyVal() [19/22]
G3D::AnyVal::AnyVal (const G3D::Matrix3 & v)
Definition at line 143 of file AnyVal.cpp.
                                : m_type(MATRIX3), m_referenceCount(NULL) {
     m_value = new Matrix3(v);
 }
References m_value.
AnyVal() [20/22]
G3D::AnyVal::AnyVal (const G3D::Matrix4 & v)
Definition at line 148 of file AnyVal.cpp.
                                : m_type(MATRIX4), m_referenceCount(NULL) {
     m_value = new Matrix4(v);
 }
References m_value.
AnyVal() [21/22]
G3D::AnyVal::AnyVal (const AnyVal & c)
Definition at line 153 of file AnyVal.cpp.
                               : m_type(NIL), m_value(NULL), m_referenceCount(NULL) {
     *this = c;
 }
References mpq::c.
AnyVal() [22/22]
G3D::AnyVal::AnyVal (Type arrayOrTable)
Definition at line 158 of file AnyVal.cpp.
                                 : m_type(NIL), m_value(NULL), m_referenceCount(new int(1)) {
     // TODO: make AnyVal::createArray()
     switch (arrayOrTable) {
     case ARRAY:
         m_type = ARRAY;
         m_value = new Array<AnyVal>();
         break;
     case TABLE:
         m_type = TABLE;
         m_value = new Table<std::string, AnyVal>();
         break;
     default:
         debugAssertM(false, "Cannot construct AnyVal from constants except ARRAY or TABLE.");
     }
 }
References ARRAY, debugAssertM, m_type, m_value, and TABLE.
~AnyVal()
G3D::AnyVal::~AnyVal ()
Frees the underlying storage
Definition at line 177 of file AnyVal.cpp.
                 {
     deleteValue();
 }
References deleteValue().
Member Function Documentation
aabox() [1/2]
const AABox & G3D::AnyVal::aabox () const
Definition at line 1105 of file AnyVal.cpp.
{
     if (m_type != AABOX) {
         throw WrongType(AABOX, m_type);
     }
     return *(AABox*)m_value;
 }
References AABOX, m_type, and m_value.
Referenced by operator const AABox &(), and serialize().
aabox() [2/2]
const AABox & G3D::AnyVal::aabox (const G3D::AABox & defaultVal) const
Definition at line 1114 of file AnyVal.cpp.
{
     if (m_type != AABOX) {
         return defaultVal;
     } else {
         return *(AABox*)m_value;
     }
 }
References AABOX, m_type, and m_value.
append()
void G3D::AnyVal::append (const AnyVal & v)
Extend this array by one element.
Definition at line 948 of file AnyVal.cpp.
{
     if (m_type != ARRAY) {
         throw WrongType(ARRAY, m_type);
     }
     makeMutable();
     Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
     a.append(v);
 }
References mpq::a, ARRAY, m_type, m_value, and makeMutable().
boolean() [1/2]
bool G3D::AnyVal::boolean () const
Definition at line 1033 of file AnyVal.cpp.
{
     if (m_type != BOOLEAN) {
         throw WrongType(BOOLEAN, m_type);
     }
     return *(bool*)m_value;
 }
References BOOLEAN, m_type, and m_value.
Referenced by operator bool().
boolean() [2/2]
bool G3D::AnyVal::boolean (bool b) const
Definition at line 1042 of file AnyVal.cpp.
{
     if (m_type != BOOLEAN) {
         return defaultVal;
     }
     return *(bool*)m_value;
 }
References BOOLEAN, m_type, and m_value.
color1() [1/2]
const Color1 & G3D::AnyVal::color1 () const
Definition at line 1123 of file AnyVal.cpp.
{
     if (m_type != COLOR1) {
         throw WrongType(COLOR1, m_type);
     }
     return *(Color1*)m_value;
 }
References COLOR1, m_type, and m_value.
color1() [2/2]
const Color1 & G3D::AnyVal::color1 (const G3D::Color1 & defaultVal) const
Definition at line 1132 of file AnyVal.cpp.
{
     if (m_type != COLOR1) {
         return defaultVal;
     } else {
         return *(Color1*)m_value;
     }
 }
References COLOR1, m_type, and m_value.
color3() [1/2]
const Color3 & G3D::AnyVal::color3 () const
Definition at line 1141 of file AnyVal.cpp.
{
     if (m_type != COLOR3) {
         throw WrongType(COLOR3, m_type);
     }
     return *(Color3*)m_value;
 }
References COLOR3, m_type, and m_value.
Referenced by operator const Color3 &().
color3() [2/2]
const Color3 & G3D::AnyVal::color3 (const G3D::Color3 & defaultVal) const
Definition at line 1150 of file AnyVal.cpp.
{
     if (m_type != COLOR3) {
         return defaultVal;
     } else {
         return *(Color3*)m_value;
     }
 }
References COLOR3, m_type, and m_value.
color4() [1/2]
const Color4 & G3D::AnyVal::color4 () const
Definition at line 1159 of file AnyVal.cpp.
{
     if (m_type != COLOR4) {
         throw WrongType(COLOR4, m_type);
     }
     return *(Color4*)m_value;
 }
References COLOR4, m_type, and m_value.
Referenced by operator const Color4 &().
color4() [2/2]
const Color4 & G3D::AnyVal::color4 (const G3D::Color4 & defaultVal) const
Definition at line 1168 of file AnyVal.cpp.
{
     if (m_type != COLOR4) {
         return defaultVal;
     } else {
         return *(Color4*)m_value;
     }
 }
References COLOR4, m_type, and m_value.
coordinateFrame() [1/2]
const CoordinateFrame & G3D::AnyVal::coordinateFrame () const
Definition at line 1231 of file AnyVal.cpp.
{
     if (m_type != COORDINATEFRAME) {
         throw WrongType(COORDINATEFRAME, m_type);
     }
     return *(CoordinateFrame*)m_value;
 }
References COORDINATEFRAME, m_type, and m_value.
Referenced by operator const CoordinateFrame &().
coordinateFrame() [2/2]
const CoordinateFrame & G3D::AnyVal::coordinateFrame (const G3D::CoordinateFrame & defaultVal) const
Definition at line 1240 of file AnyVal.cpp.
{
     if (m_type != COORDINATEFRAME) {
         return defaultVal;
     } else {
         return *(CoordinateFrame*)m_value;
     }
 }
References COORDINATEFRAME, m_type, and m_value.
copyValue()
void * G3D::AnyVal::copyValue () const private
Returns a copy of the value.
Definition at line 300 of file AnyVal.cpp.
{
   switch (m_type) {
     case NIL:
         return NULL;
     case NUMBER:
         return new double(*(double*)m_value);
     case BOOLEAN:
         return new bool(*(bool*)m_value);
     case STRING:
         return new std::string(*(std::string*)m_value);
     case RECT2D:
         return new Rect2D(*(Rect2D*)m_value);
     case AABOX:
         return new AABox(*(AABox*)m_value);
     case VECTOR2:
         return new Vector2(*(Vector2*)m_value);
     case VECTOR3:
         return new Vector3(*(Vector3*)m_value);
     case VECTOR4:
         return new Vector4(*(Vector4*)m_value);
     case MATRIX2:
         return new Matrix2(*(Matrix2*)m_value);
     case MATRIX3:
         return new Matrix3(*(Matrix3*)m_value);
     case MATRIX4:
         return new Matrix4(*(Matrix4*)m_value);
     case QUAT:
         return new Quat(*(Quat*)m_value);
     case COORDINATEFRAME:
         return new CoordinateFrame(*(CoordinateFrame*)m_value);
     case COLOR1:
         return new Color1(*(Color1*)m_value);
     case COLOR3:
         return new Color3(*(Color3*)m_value);
     case COLOR4:
         return new Color4(*(Color4*)m_value);
     case ARRAY:
         return new Array<AnyVal>(*(Array<AnyVal>*)m_value);
     case TABLE:
         return new Table<std::string, AnyVal>(*(Table<std::string, AnyVal>*)m_value);
     default:
         debugAssertM(false, "Internal error: no assignment operator for this type.");
         return NULL;
     }
 }
References AABOX, ARRAY, bool, BOOLEAN, COLOR1, COLOR3, COLOR4, COORDINATEFRAME, debugAssertM, m_type, m_value, MATRIX2, MATRIX3, MATRIX4, NIL, NULL, NUMBER, QUAT, RECT2D, STRING, TABLE, VECTOR2, VECTOR3, and VECTOR4.
Referenced by makeMutable(), and operator=().
deleteValue()
void G3D::AnyVal::deleteValue () private
Decrements the reference count (if there is one). If the reference count is zero or does not exist. Calls delete on m_value and sets it to NULL.
Definition at line 182 of file AnyVal.cpp.
{
     if (m_referenceCount) {
         --(*m_referenceCount);
         if (*m_referenceCount <= 0) {
             delete m_referenceCount;
             m_referenceCount = NULL;
             // Pass through and delete the real object now
         } else {
             // Someone else is holding a reference, so we can't delete
             // the object.
             m_referenceCount = NULL;
             return;
         }
     }
     switch (m_type) {
     case NIL:
         // Nothing to do
         break;
     case NUMBER:
         delete (double*)m_value;
         break;
     case BOOLEAN:
         delete (bool*)m_value;
         break;
     case STRING:
         delete (std::string*)m_value;
         break;
     case RECT2D:
         delete (Rect2D*)m_value;
         break;
     case AABOX:
         delete (AABox*)m_value;
         break;
     case VECTOR2:
         delete (Vector2*)m_value;
         break;
     case VECTOR3:
         delete (Vector3*)m_value;
         break;
     case VECTOR4:
         delete (Vector4*)m_value;
         break;
     case MATRIX2:
         delete (Matrix2*)m_value;
         break;
     case MATRIX3:
         delete (Matrix3*)m_value;
         break;
     case MATRIX4:
         delete (Matrix4*)m_value;
         break;
     case QUAT:
         delete (Quat*)m_value;
         break;
     case COORDINATEFRAME:
         delete (CoordinateFrame*)m_value;
         break;
     case COLOR1:
         delete (Color1*)m_value;
         break;
     case COLOR3:
         delete (Color3*)m_value;
         break;
     case COLOR4:
         delete (Color4*)m_value;
         break;
     case ARRAY:
         delete (Array<AnyVal>*)m_value;
         break;
     case TABLE:
         delete (Table<std::string, AnyVal>*)m_value;
         break;
     default:
         debugAssertM(false, "Internal error: no destructor for this type.");
     }
     m_value = NULL;
 }
References AABOX, ARRAY, BOOLEAN, COLOR1, COLOR3, COLOR4, COORDINATEFRAME, debugAssertM, m_referenceCount, m_type, m_value, MATRIX2, MATRIX3, MATRIX4, NIL, NULL, NUMBER, QUAT, RECT2D, STRING, TABLE, VECTOR2, VECTOR3, and VECTOR4.
Referenced by deserialize(), operator=(), and ~AnyVal().
deserialize()
void G3D::AnyVal::deserialize (G3D::TextInput & t)
Definition at line 571 of file AnyVal.cpp.
{
     deleteValue();
     m_type = NIL;
     m_value = NULL;
     if (! t.hasMore()) {
         return;
     }
     switch (t.peek().type()) {
     case Token::END:
         // should never get here because of the hasMore check above
         return;
         break;
     case Token::NUMBER:
         m_type = NUMBER;
         m_value = new double(t.readNumber());
         break;
     case Token::STRING:
         m_type = STRING;
         m_value = new std::string(t.readString());
         break;
     case Token::NEWLINE:
         m_type = STRING;
         m_value = new std::string(t.readNewline());
         break;
     case Token::COMMENT:
         m_type = STRING;
         m_value = new std::string(t.readComment());
         break;
     case Token::BOOLEAN:
         m_type = BOOLEAN;
         m_value = new bool(t.readBoolean());
         break;
     case Token::SYMBOL:
         {
             std::string s = t.readSymbol();
             if (s == "NIL") {
                 break;
             } else if (s == "true") {
                 m_type = BOOLEAN;
                 m_value = new bool(true);
             } else if (s == "false") {
                 m_type = BOOLEAN;
                 m_value = new bool(false);
             } else if (s == "R") {
                 m_type = RECT2D;
                 t.readSymbol("(");
                 float x,y,w,h;
                 x = (float)t.readNumber();
                 t.readSymbol(",");
                 y = (float)t.readNumber();
                 t.readSymbol(",");
                 w = (float)t.readNumber();
                 t.readSymbol(",");
                 h = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Rect2D(Rect2D::xywh(x, y, w, h));
             } else if (s == "AAB") {
                 m_type = AABOX;
                 Vector3 v[2];
                 t.readSymbol("(");
                 for (int i = 0; i < 2; ++i) {
                     t.readSymbols("V3", "(");
                     v[i].x = (float)t.readNumber();
                     t.readSymbol(",");
                     v[i].y = (float)t.readNumber();
                     t.readSymbol(",");
                     v[i].z = (float)t.readNumber();
                     t.readSymbol(",");
                     if (i == 0) {
                         t.readSymbol(",");
                     }
                 }
                 t.readSymbol(")");
                 m_value = new AABox(v[0], v[1]);
             } else if (s == "V2") {
                 t.readSymbol("(");
                 Vector2 v;
                 v.x = (float)t.readNumber();
                 t.readSymbol(",");
                 v.y = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Vector2(v);
                 m_type = VECTOR2;
             } else if (s == "V3") {
                 t.readSymbol("(");
                 Vector3 v;
                 v.x = (float)t.readNumber();
                 t.readSymbol(",");
                 v.y = (float)t.readNumber();
                 t.readSymbol(",");
                 v.z = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Vector3(v);
                 m_type = VECTOR3;
             } else if (s == "V4") {
                 t.readSymbol("(");
                 Vector4 v;
                 v.x = (float)t.readNumber();
                 t.readSymbol(",");
                 v.y = (float)t.readNumber();
                 t.readSymbol(",");
                 v.z = (float)t.readNumber();
                 t.readSymbol(",");
                 v.w = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Vector4(v);
                 m_type = VECTOR4;
             } else if (s == "M2") {
                 t.readSymbol("(");
                 Matrix2 m;
                 for (int r = 0; r < 2; ++r) {
                     for (int c = 0; c < 2; ++c) {
                         m[r][c] = (float)t.readNumber();
                         if ((c != 1) || (r != 1)) {
                             t.readSymbol(",");
                         }
                     }
                 }
                 t.readSymbol(")");
                 m_value = new Matrix2(m);
                 m_type = MATRIX2;
             } else if (s == "M3") {
                 t.readSymbol("(");
                 Matrix3 m;
                 for (int r = 0; r < 3; ++r) {
                     for (int c = 0; c < 3; ++c) {
                         m[r][c] = (float)t.readNumber();
                         if ((c != 2) || (r != 2)) {
                             t.readSymbol(",");
                         }
                     }
                 }
                 t.readSymbol(")");
                 m_value = new Matrix3(m);
                 m_type = MATRIX3;
             } else if (s == "M4") {
                 t.readSymbol("(");
                 Matrix4 m;
                 for (int r = 0; r < 4; ++r) {
                     for (int c = 0; c < 4; ++c) {
                         m[r][c] = (float)t.readNumber();
                         if ((c != 3) || (r != 3)) {
                             t.readSymbol(",");
                         }
                     }
                 }
                 t.readSymbol(")");
                 m_value = new Matrix4(m);
                 m_type = MATRIX4;
             } else if (s == "Q") {
                 t.readSymbol("(");
                 Quat q;
                 q.x = (float)t.readNumber();
                 t.readSymbol(",");
                 q.y = (float)t.readNumber();
                 t.readSymbol(",");
                 q.z = (float)t.readNumber();
                 t.readSymbol(",");
                 q.w = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Quat(q);
                 m_type = QUAT;
             } else if (s == "CF") {
                 t.readSymbol("(");
                 CoordinateFrame m;
                 if (t.peek().type() == Token::SYMBOL) {
                     // Angle format
                     float x, y, z, yaw, roll, pitch;
                     t.readSymbols("V3", "(");
                     x = (float)t.readNumber();
                     t.readSymbol(",");
                     y = (float)t.readNumber();
                     t.readSymbol(",");
                     z = (float)t.readNumber();
                     t.readSymbols(")", ",");
                     yaw = (float)t.readNumber();
                     t.readSymbol(",");
                     pitch = (float)t.readNumber();
                     roll = 0;
                     if (t.peek().string() == ",") {
                         t.readSymbol(",");
                         roll = (float)t.readNumber();
                     }
                     m = CoordinateFrame::fromXYZYPRDegrees(x, y, z, yaw, pitch, roll);
                 } else {
                     // Matrix format
                     for (int r = 0; r < 3; ++r) {
                         for (int c = 0; c < 3; ++c) {
                             m.rotation[r][c] = (float)t.readNumber();
                         }
                         m.translation[r] = (float)t.readNumber();
                         if (r != 2) {
                             t.readSymbol(",");
                         }
                     }
                 }
                 t.readSymbol(")");
                 m_value = new CoordinateFrame(m);
                 m_type = COORDINATEFRAME;
             } else if (s == "C1") {
                 t.readSymbol("(");
                 float v = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Color1(v);
                 m_type = COLOR1;
             } else if (s == "C3") {
                 t.readSymbol("(");
                 Color3 c;
                 c.r = (float)t.readNumber();
                 t.readSymbol(",");
                 c.g = (float)t.readNumber();
                 t.readSymbol(",");
                 c.b = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Color3(c);
                 m_type = COLOR3;
             } else if (s == "C4") {
                 t.readSymbol("(");
                 Color4 c;
                 c.r = (float)t.readNumber();
                 t.readSymbol(",");
                 c.g = (float)t.readNumber();
                 t.readSymbol(",");
                 c.b = (float)t.readNumber();
                 t.readSymbol(",");
                 c.a = (float)t.readNumber();
                 t.readSymbol(")");
                 m_value = new Color4(c);
                 m_type = COLOR4;
             } else if (s == "[") {
                 // Array
                 m_type = ARRAY;
                 m_value = new Array<AnyVal>();
                 m_referenceCount = new int(1);
                 Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
                 Token peek = t.peek();
                 while ((peek.type() != Token::SYMBOL) || (peek.string() != "]")) {
                     // Avoid copying large objects
                     a.next().deserialize(t);
                     peek = t.peek();
                     if (peek.type() != Token::SYMBOL) {
                         throw CorruptText("Expected ',' or ']'", peek);
                     } else if (peek.string() == ",") {
                         t.readSymbol(",");
                     } else if (peek.string() != "]") {
                         throw CorruptText("Missing ']'", peek);
                     }
                 }
                 t.readSymbol("]");
             } else if (s == "{") {
                 // Table
                 m_type = TABLE;
                 m_value = new Table<std::string, AnyVal>();
                 m_referenceCount = new int(1);
                 Table<std::string, AnyVal>& a = *(Table<std::string, AnyVal>*)m_value;
                 Token peek = t.peek();
                 while ((peek.type() != Token::SYMBOL) || (peek.string() != "}")) {
                     std::string key;
                     // Get the name
                     if (peek.type() == Token::SYMBOL) {
                         key = t.readSymbol();
                     } else if (peek.extendedType() == Token::SINGLE_QUOTED_TYPE) {
                         key = t.readString();
                     } else {
                         throw CorruptText("Expected name inside table", peek);
                     }
                     t.readSymbol("=");
                     // Avoid copying large values
                     a.set(key, AnyVal());
                     a[key].deserialize(t);
                     peek = t.peek();
                     if ((peek.type() != Token::SYMBOL) && (peek.extendedType() != Token::SINGLE_QUOTED_TYPE)) {
                         throw CorruptText("Missing expected name or '}'", peek);
                     }
                 }
                 t.readSymbol("}");
             } else {
                 throw CorruptText("Invalid value type.", t.peek());
             } // dispatch on symbol type
         } // scope
         break;
     }
 }
References mpq::a, AABOX, AnyVal(), ARRAY, bool, BOOLEAN, G3D::Token::BOOLEAN, mpq::c, COLOR1, COLOR3, COLOR4, G3D::Token::COMMENT, COORDINATEFRAME, deleteValue(), G3D::Token::END, G3D::Token::extendedType(), G3D::CoordinateFrame::fromXYZYPRDegrees(), G3D::TextInput::hasMore(), m_referenceCount, m_type, m_value, MATRIX2, MATRIX3, MATRIX4, G3D::Token::NEWLINE, NIL, NULL, NUMBER, G3D::Token::NUMBER, G3D::TextInput::peek(), QUAT, G3D::TextInput::readBoolean(), G3D::TextInput::readComment(), G3D::TextInput::readNewline(), G3D::TextInput::readNumber(), G3D::TextInput::readString(), G3D::TextInput::readSymbol(), G3D::TextInput::readSymbols(), RECT2D, G3D::CoordinateFrame::rotation, G3D::Token::SINGLE_QUOTED_TYPE, STRING, G3D::Token::STRING, G3D::Token::string(), G3D::Token::SYMBOL, TABLE, G3D::CoordinateFrame::translation, G3D::Token::type(), VECTOR2, VECTOR3, VECTOR4, G3D::Quat::w, G3D::Vector4::w, G3D::Quat::x, G3D::Vector2::x, G3D::x, G3D::Vector3::x, G3D::Vector4::x, G3D::Rect2D::xywh(), G3D::Quat::y, G3D::Vector2::y, G3D::y, G3D::Vector3::y, G3D::Vector4::y, G3D::Quat::z, G3D::Vector3::z, G3D::z, and G3D::Vector4::z.
Referenced by AnyVal().
fromFile()
AnyVal G3D::AnyVal::fromFile (const std::string & filename) static
Definition at line 33 of file AnyVal.cpp.
{
     TextInput t(filename);
     return AnyVal(t);
 }
References AnyVal().
Referenced by load().
get() [1/4]
const AnyVal & G3D::AnyVal::get (const std::string & key) const
Throws KeyNotFound exception if the key is not present.
Definition at line 1335 of file AnyVal.cpp.
{
     if (m_type != TABLE) {
         throw WrongType(TABLE, m_type);
     }
     const Table<std::string, AnyVal>& t = *(const Table<std::string, AnyVal>*)m_value;
     if (t.containsKey(key)) {
         return t[key];
     } else {
         throw KeyNotFound(key);
     }
 }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), m_type, m_value, and TABLE.
get() [2/4]
const AnyVal & G3D::AnyVal::get (const std::string & key, const AnyVal & defaultVal) const
Returns defaultVal if this is not a TABLE or the key is not found.
Definition at line 1320 of file AnyVal.cpp.
{
     if (m_type != TABLE) {
         return defaultVal;
     }
     const Table<std::string, AnyVal>& t = *(const Table<std::string, AnyVal>*)m_value;
     if (t.containsKey(key)) {
         return t[key];
     } else {
         return defaultVal;
     }
 }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), m_type, m_value, and TABLE.
get() [3/4]
const AnyVal & G3D::AnyVal::get (int i) const
If out of bounds, IndexOutOfBounds is thrown.
Definition at line 1365 of file AnyVal.cpp.
{
     if (m_type != ARRAY) {
         throw WrongType(ARRAY, m_type);
     }
     const Array<AnyVal>& a = *(const Array<AnyVal>*)m_value;
     if ((i >= 0) && (i < a.size())) {
         return a[i];
     } else {
         throw IndexOutOfBounds(i, a.size());
     }
 }
References mpq::a, ARRAY, m_type, and m_value.
get() [4/4]
const AnyVal & G3D::AnyVal::get (int i, const AnyVal & defaultVal) const
If i is out of bounds or this is not an ARRAY, defaultVal is returned.
Definition at line 1350 of file AnyVal.cpp.
{
     if (m_type != ARRAY) {
         return defaultVal;
     }
     const Array<AnyVal>& a = *(const Array<AnyVal>*)m_value;
     if ((i >= 0) && (i < a.size())) {
         return a[i];
     } else {
         return defaultVal;
     }
 }
References mpq::a, ARRAY, m_type, and m_value.
getKeys()
void G3D::AnyVal::getKeys (G3D::Array< std::string > & keys) const
For a table, returns the keys.
Definition at line 959 of file AnyVal.cpp.
{
     if (m_type != TABLE) {
         throw WrongType(TABLE, m_type);
     }
     const Table<std::string, AnyVal>& t = *(const Table<std::string, AnyVal>*)m_value;
     t.getKeys(keys);
 }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), m_type, m_value, and TABLE.
isNil()
bool G3D::AnyVal::isNil () const inline
Definition at line 343 of file AnyVal.h.
{
         return type() == NIL;
     }
References NIL, and type().
isShared()
bool G3D::AnyVal::isShared () const inline private
True if this is a shared value between multiple instances.
Definition at line 279 of file AnyVal.h.
{
         return m_referenceCount && (*m_referenceCount > 1);
     }
References m_referenceCount.
isSharedType()
bool G3D::AnyVal::isSharedType () const inline private
True when m_value is a double pointer
Definition at line 284 of file AnyVal.h.
{
         return (m_type == TABLE) || (m_type == ARRAY);
     }
References ARRAY, m_type, and TABLE.
Referenced by operator=().
load()
void G3D::AnyVal::load (const std::string & filename)
Definition at line 39 of file AnyVal.cpp.
{
     *this = fromFile(filename);
 }
References fromFile().
makeMutable()
void G3D::AnyVal::makeMutable () private
Assumes isSharedType. Ensures that this has a unique reference
Definition at line 1024 of file AnyVal.cpp.
{
     if (*m_referenceCount > 1) {
         // This is a shared instance
         --(*m_referenceCount);
         m_referenceCount = new int(1);
         m_value = copyValue();
     }
 }
References copyValue(), m_referenceCount, and m_value.
Referenced by append(), and operator[]().
matrix2() [1/2]
const Matrix2 & G3D::AnyVal::matrix2 () const
Definition at line 1257 of file AnyVal.cpp.
{
     if (m_type != MATRIX2) {
         throw WrongType(MATRIX2, m_type);
     }
     return *(Matrix2*)m_value;
 }
References m_type, m_value, and MATRIX2.
Referenced by operator const Matrix2 &().
matrix2() [2/2]
const Matrix2 & G3D::AnyVal::matrix2 (const G3D::Matrix2 & defaultVal) const
Definition at line 1248 of file AnyVal.cpp.
{
     if (m_type != MATRIX2) {
         return defaultVal;
     } else {
         return *(Matrix2*)m_value;
     }
 }
References m_type, m_value, and MATRIX2.
matrix3() [1/2]
const Matrix3 & G3D::AnyVal::matrix3 () const
Definition at line 1275 of file AnyVal.cpp.
{
     if (m_type != MATRIX3) {
         throw WrongType(MATRIX3, m_type);
     }
     return *(Matrix3*)m_value;
 }
References m_type, m_value, and MATRIX3.
Referenced by operator const Matrix3 &().
matrix3() [2/2]
const Matrix3 & G3D::AnyVal::matrix3 (const G3D::Matrix3 & defaultVal) const
Definition at line 1266 of file AnyVal.cpp.
{
     if (m_type != MATRIX3) {
         return defaultVal;
     } else {
         return *(Matrix3*)m_value;
     }
 }
References m_type, m_value, and MATRIX3.
matrix4() [1/2]
const Matrix4 & G3D::AnyVal::matrix4 () const
Definition at line 1293 of file AnyVal.cpp.
{
     if (m_type != MATRIX4) {
         throw WrongType(MATRIX4, m_type);
     }
     return *(Matrix4*)m_value;
 }
References m_type, m_value, and MATRIX4.
Referenced by operator const Matrix4 &().
matrix4() [2/2]
const Matrix4 & G3D::AnyVal::matrix4 (const G3D::Matrix4 & defaultVal) const
Definition at line 1284 of file AnyVal.cpp.
{
     if (m_type != MATRIX4) {
         return defaultVal;
     } else {
         return *(Matrix4*)m_value;
     }
 }
References m_type, m_value, and MATRIX4.
number() [1/2]
double G3D::AnyVal::number () const
If this value is not a number throws a WrongType exception.
Definition at line 1069 of file AnyVal.cpp.
{
     if (m_type != NUMBER) {
         throw WrongType(NUMBER, m_type);
     }
     return *(double*)m_value;
 }
References m_type, m_value, and NUMBER.
Referenced by mpq::File::__repr__(), mpq::File::__str__(), operator double(), and operator float().
number() [2/2]
double G3D::AnyVal::number (double defaultVal) const
If this value is not a number, returns defaultVal.
Definition at line 1078 of file AnyVal.cpp.
{
     if (m_type != NUMBER) {
         return defaultVal;
     } else {
         return *(double*)m_value;
     }
 }
References m_type, m_value, and NUMBER.
Referenced by mpq::File::__repr__(), and mpq::File::__str__().
operator bool()
G3D::AnyVal::operator bool () const inline
Definition at line 403 of file AnyVal.h.
{
         return boolean();
     }
References boolean().
operator const AABox &()
G3D::AnyVal::operator const AABox & () const inline
Definition at line 424 of file AnyVal.h.
{
         return aabox();
     }
References aabox().
operator const Color3 &()
G3D::AnyVal::operator const Color3 & () const inline
Definition at line 455 of file AnyVal.h.
{
         return color3();
     }
References color3().
operator const Color4 &()
G3D::AnyVal::operator const Color4 & () const inline
Definition at line 462 of file AnyVal.h.
{
         return color4();
     }
References color4().
operator const CoordinateFrame &()
G3D::AnyVal::operator const CoordinateFrame & () const inline
Definition at line 469 of file AnyVal.h.
{
         return coordinateFrame();
     }
References coordinateFrame().
operator const Matrix2 &()
G3D::AnyVal::operator const Matrix2 & () const inline
Definition at line 476 of file AnyVal.h.
{
         return matrix2();
     }
References matrix2().
operator const Matrix3 &()
G3D::AnyVal::operator const Matrix3 & () const inline
Definition at line 483 of file AnyVal.h.
{
         return matrix3();
     }
References matrix3().
operator const Matrix4 &()
G3D::AnyVal::operator const Matrix4 & () const inline
Definition at line 490 of file AnyVal.h.
{
         return matrix4();
     }
References matrix4().
operator const Quat &()
G3D::AnyVal::operator const Quat & () const inline
Definition at line 497 of file AnyVal.h.
{
         return quat();
     }
References quat().
operator const Rect2D &()
G3D::AnyVal::operator const Rect2D & () const inline
Definition at line 417 of file AnyVal.h.
{
         return rect2D();
     }
References rect2D().
operator const std::string &()
G3D::AnyVal::operator const std::string & () const inline
Definition at line 410 of file AnyVal.h.
{
         return string();
     }
References string().
operator const Vector2 &()
G3D::AnyVal::operator const Vector2 & () const inline
Definition at line 431 of file AnyVal.h.
{
         return vector2();
     }
References vector2().
operator const Vector3 &()
G3D::AnyVal::operator const Vector3 & () inline
Definition at line 438 of file AnyVal.h.
{
         return vector3();
     }
References vector3().
operator const Vector4 &()
G3D::AnyVal::operator const Vector4 & () const inline
Definition at line 445 of file AnyVal.h.
{
         return vector4();
     }
References vector4().
operator double()
G3D::AnyVal::operator double () const inline
Definition at line 392 of file AnyVal.h.
{
         return number();
     }
References number().
operator float()
G3D::AnyVal::operator float () const inline
Definition at line 396 of file AnyVal.h.
{
         return (float)number();
     }
References number().
operator=()
AnyVal & G3D::AnyVal::operator= (const AnyVal & v)
Definition at line 282 of file AnyVal.cpp.
{
     deleteValue();
     m_type = v.m_type;
     m_referenceCount = v.m_referenceCount;
     if (isSharedType()) {
         ++(*m_referenceCount);
         m_value = v.m_value;
     } else {
         m_value = v.copyValue();
     }
     return *this;
 }
References copyValue(), deleteValue(), isSharedType(), m_referenceCount, m_type, and m_value.
operator[]() [1/6]
AnyVal & G3D::AnyVal::operator[] (const char * key)
Table reference. If the element does not exist, it is created.
Definition at line 906 of file AnyVal.cpp.
{
     return this->operator[]((std::string)key);
 }
References operator[]().
operator[]() [2/6]
const AnyVal & G3D::AnyVal::operator[] (const char * key) const
Table reference
Definition at line 911 of file AnyVal.cpp.
{
     return this->operator[]((std::string)key);
 }
References operator[]().
operator[]() [3/6]
AnyVal & G3D::AnyVal::operator[] (const std::string & key)
Table reference. If the element does not exist, it is created.
Definition at line 916 of file AnyVal.cpp.
{
     if (m_type != TABLE) {
         throw WrongType(TABLE, m_type);
     }
     makeMutable();
     Table<std::string, AnyVal>& t = *(Table<std::string, AnyVal>*)m_value;
     if (! t.containsKey(key)) {
         t.set(key, AnyVal());
     }
     return t[key];
 }
References AnyVal(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), m_type, m_value, makeMutable(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), and TABLE.
operator[]() [4/6]
const AnyVal & G3D::AnyVal::operator[] (const std::string & key) const
Table reference
Definition at line 933 of file AnyVal.cpp.
{
     if (m_type != TABLE) {
         throw WrongType(TABLE, m_type);
     }
     const Table<std::string, AnyVal>& t = *(const Table<std::string, AnyVal>*)m_value;
     if (! t.containsKey(key)) {
         throw KeyNotFound(key);
     }
     return t[key];
 }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), m_type, m_value, and TABLE.
operator[]() [5/6]
AnyVal & G3D::AnyVal::operator[] (int i)
If the index is out of bounds, the array is resized. If the index is negative, IndexOutOfBounds is thrown.
Definition at line 989 of file AnyVal.cpp.
{
     if (m_type != ARRAY) {
         throw WrongType(ARRAY, m_type);
     }
     makeMutable();
     Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
     if (i < 0) {
         throw IndexOutOfBounds(i, a.size());
     }
     if (a.size() <= i) {
         a.resize(i + 1);
     }
     return a[i];
 }
References mpq::a, ARRAY, m_type, m_value, and makeMutable().
operator[]() [6/6]
const AnyVal & G3D::AnyVal::operator[] (int i) const
Array dereference. If the index is out of bounds, IndexOutOfBounds is thrown
Definition at line 1009 of file AnyVal.cpp.
{
     if (m_type != ARRAY) {
         throw WrongType(ARRAY, m_type);
     }
     const Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
     if (a.size() <= i || i < 0) {
         throw IndexOutOfBounds(i, a.size());
     }
     return a[i];
 }
References mpq::a, ARRAY, m_type, and m_value.
Referenced by operator[]().
quat() [1/2]
const Quat & G3D::AnyVal::quat () const
Definition at line 1311 of file AnyVal.cpp.
{
     if (m_type != QUAT) {
         throw WrongType(QUAT, m_type);
     }
     return *(Quat*)m_value;
 }
References m_type, m_value, and QUAT.
Referenced by operator const Quat &().
quat() [2/2]
const Quat & G3D::AnyVal::quat (const G3D::Quat & defaultVal) const
Definition at line 1302 of file AnyVal.cpp.
{
     if (m_type != QUAT) {
         return defaultVal;
     } else {
         return *(Quat*)m_value;
     }
 }
References m_type, m_value, and QUAT.
rect2D() [1/2]
const Rect2D & G3D::AnyVal::rect2D () const
Definition at line 1087 of file AnyVal.cpp.
{
     if (m_type != RECT2D) {
         throw WrongType(RECT2D, m_type);
     }
     return *(Rect2D*)m_value;
 }
References m_type, m_value, and RECT2D.
Referenced by operator const Rect2D &().
rect2D() [2/2]
const Rect2D & G3D::AnyVal::rect2D (const G3D::Rect2D & defaultVal) const
Definition at line 1096 of file AnyVal.cpp.
{
     if (m_type != RECT2D) {
         return defaultVal;
     } else {
         return *(Rect2D*)m_value;
     }
 }
References m_type, m_value, and RECT2D.
save()
void G3D::AnyVal::save (const std::string & filename) const
Definition at line 44 of file AnyVal.cpp.
{
     TextOutput t(filename);
     serialize(t);
     t.commit();
 }
References G3D::TextOutput::commit(), and serialize().
serialize()
void G3D::AnyVal::serialize (G3D::TextOutput & t) const
Definition at line 389 of file AnyVal.cpp.
{
     switch (m_type) {
     case NIL:
         t.writeSymbol("Nil");
         break;
     case NUMBER:
         t.printf("%g", *(double*)m_value);
         break;
     case BOOLEAN:
         t.writeBoolean(*(bool*)m_value);
         break;
     case STRING:
         t.writeString(*(std::string*)m_value);
         break;
     case RECT2D:
         t.printf("R(%g, %g, %g, %g)", ((Rect2D*)m_value)->x0(), ((Rect2D*)m_value)->y0(),
                  ((Rect2D*)m_value)->width(), ((Rect2D*)m_value)->height());
         break;
     case AABOX:
         t.printf("AAB(V3(%g, %g, %g), V3(%g, %g, %g))",
                  aabox().low().x,
                  aabox().low().y,
                  aabox().low().z,
                  aabox().high().x,
                  aabox().high().y,
                  aabox().high().z);
         break;
     case VECTOR2:
         t.printf("V2(%g, %g)", ((Vector2*)m_value)->x, ((Vector2*)m_value)->y);
         break;
     case VECTOR3:
         t.printf("V3(%g, %g, %g)", ((Vector3*)m_value)->x, ((Vector3*)m_value)->y, ((Vector3*)m_value)->z);
         break;
     case VECTOR4:
         t.printf("V4(%g, %g, %g, %g)", ((Vector4*)m_value)->x, ((Vector4*)m_value)->y, ((Vector4*)m_value)->z, ((Vector4*)m_value)->w);
         break;
     case MATRIX2:
         {
             const Matrix2& m = *(Matrix2*)m_value;
             t.printf("M2(\n");
             t.pushIndent();
             t.printf("%10.5f, %10.5f,\n%10.5f, %10.5f)",
                      m[0][0], m[0][1],
                      m[1][0], m[1][1]);
             t.popIndent();
         }
         break;
     case MATRIX3:
         {
             const Matrix3& m = *(Matrix3*)m_value;
             t.printf("M3(\n");
             t.pushIndent();
             t.printf("%10.5f, %10.5f, %10.5f,\n%10.5f, %10.5f, %10.5f,\n%10.5f, %10.5f, %10.5f)",
                 m[0][0], m[0][1], m[0][2],
                 m[1][0], m[1][1], m[1][2],
                 m[2][0], m[2][1], m[2][2]);
             t.popIndent();
         }
         break;
     case MATRIX4:
         {
             const Matrix4& m = *(Matrix4*)m_value;
             t.printf("M4(\n");
             t.pushIndent();
             t.printf(
                 "%10.5f, %10.5f, %10.5f, %10.5f,\n"
                 "%10.5f, %10.5f, %10.5f, %10.5f,\n"
                 "%10.5f, %10.5f, %10.5f, %10.5f,\n"
                 "%10.5f, %10.5f, %10.5f, %10.5f)",
                 m[0][0], m[0][1], m[0][2], m[0][3],
                 m[1][0], m[1][1], m[1][2], m[1][3],
                 m[2][0], m[2][1], m[2][2], m[2][3],
                 m[3][0], m[3][1], m[3][2], m[3][3]);
             t.popIndent();
         }
         break;
     case QUAT:
         t.printf("Q(%g, %g, %g, %g)", ((Quat*)m_value)->x, ((Quat*)m_value)->y, ((Quat*)m_value)->z, ((Quat*)m_value)->w);
         break;
     case COORDINATEFRAME:
         {
             const CoordinateFrame& c = *(CoordinateFrame*)m_value;
             float x,y,z,yaw,pitch,roll;
             c.getXYZYPRDegrees(x,y,z,yaw,pitch,roll);
             t.printf("CF(V3(%g,%g,%g), %g, %g, %g)", x, y, z, yaw, pitch, roll);
             /*
             t.pushIndent();
             t.printf(
                 "CF(\n%10.5f, %10.5f, %10.5f,   %10.5f,\n"
                 "%10.5f, %10.5f, %10.5f,   %10.5f,\n"
                 "%10.5f, %10.5f, %10.5f,   %10.5f)",
                 c.rotation[0][0], c.rotation[0][1], c.rotation[0][2], c.translation.x,
                 c.rotation[1][0], c.rotation[1][1], c.rotation[1][2], c.translation.y,
                 c.rotation[2][0], c.rotation[2][1], c.rotation[2][2], c.translation.z);
             t.popIndent();
             */
         }
         break;
     case COLOR1:
         t.printf("C1(%g)", ((Color1*)m_value)->value);
         break;
     case COLOR3:
         t.printf("C3(%g, %g, %g)", ((Color3*)m_value)->r, ((Color3*)m_value)->g, ((Color3*)m_value)->b);
         break;
     case COLOR4:
         t.printf("C4(%g, %g, %g, %g)", ((Color4*)m_value)->r, ((Color4*)m_value)->g, ((Color4*)m_value)->b, ((Color4*)m_value)->a);
         break;
     case ARRAY:
         {
             const Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
             t.printf("[\n");
             t.pushIndent();
                 for (int i = 0; i < a.size(); ++i) {
                     a[i].serialize(t);
                     if (i != a.size() - 1) {
                         t.printf(", \n");
                     }
                 }
             t.printf("]");
             t.popIndent();
         }
         break;
     case TABLE:
         {
             const Table<std::string, AnyVal>& a = *(Table<std::string, AnyVal>*)m_value;
             t.printf("{\n");
             t.pushIndent();
                 Table<std::string, AnyVal>::Iterator i = a.begin();
                 const Table<std::string, AnyVal>::Iterator end = a.end();
                 while (i != end) {
                     // Quote names that are not legal C++ identifiers
                     if (! legalIdentifier(i->key)) {
                         t.printf("'%s' ", i->key.c_str());
                     } else {
                         t.writeSymbol(i->key);
                     }
                     t.printf("= ");
                     i->value.serialize(t);
                     if (i != end) {
                         t.printf("\n");
                     }
                     ++i;
                 }
             t.popIndent();
             t.printf("}");
         }
         break;
     default:
         debugAssertM(false, "Internal error: no serialize method for this type.");
     }
 }
References mpq::a, AABOX, aabox(), ARRAY, b, BOOLEAN, mpq::c, COLOR1, COLOR3, COLOR4, COORDINATEFRAME, debugAssertM, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::legalIdentifier(), m_type, m_value, MATRIX2, MATRIX3, MATRIX4, NIL, NUMBER, G3D::TextOutput::popIndent(), G3D::TextOutput::printf(), G3D::TextOutput::pushIndent(), QUAT, RECT2D, STRING, TABLE, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value, VECTOR2, VECTOR3, VECTOR4, width, G3D::TextOutput::writeBoolean(), G3D::TextOutput::writeString(), G3D::TextOutput::writeSymbol(), G3D::x, G3D::y, and G3D::z.
Referenced by save(), and toString().
size()
int G3D::AnyVal::size () const
Number of elements for an array or table.
Definition at line 969 of file AnyVal.cpp.
{
     switch (m_type) {
     case TABLE:
         {
             const Table<std::string, AnyVal>& t = *(const Table<std::string, AnyVal>*)m_value;
             return t.size();
         }
     case ARRAY:
         {
             const Array<AnyVal>& a = *(Array<AnyVal>*)m_value;
             return a.size();
         }
     default:
         throw WrongType(ARRAY, m_type);
     }
 }
References mpq::a, ARRAY, m_type, m_value, G3D::Table< Key, Value, HashFunc, EqualsFunc >::size(), and TABLE.
string() [1/2]
const std::string & G3D::AnyVal::string () const
Definition at line 1051 of file AnyVal.cpp.
{
     if (m_type != STRING) {
         throw WrongType(STRING, m_type);
     }
     return *(std::string*)m_value;
 }
References m_type, m_value, and STRING.
Referenced by operator const std::string &().
string() [2/2]
const std::string & G3D::AnyVal::string (const std::string & defaultVal) const
Definition at line 1060 of file AnyVal.cpp.
{
     if (m_type != STRING) {
         return defaultVal;
     } else {
         return *(std::string*)m_value;
     }
 }
References m_type, m_value, and STRING.
toString()
std::string G3D::AnyVal::toString () const
Definition at line 563 of file AnyVal.cpp.
{
     TextOutput t;
     serialize(t);
     std::string s;
     t.commitString(s);
     return s;
 }
References G3D::TextOutput::commitString(), and serialize().
type()
AnyVal::Type G3D::AnyVal::type () const
Definition at line 365 of file AnyVal.cpp.
{
     return m_type;
 }
References m_type.
Referenced by isNil().
vector2() [1/2]
const Vector2 & G3D::AnyVal::vector2 () const
Definition at line 1177 of file AnyVal.cpp.
{
     if (m_type != VECTOR2) {
         throw WrongType(VECTOR2, m_type);
     }
     return *(Vector2*)m_value;
 }
References m_type, m_value, and VECTOR2.
Referenced by operator const Vector2 &().
vector2() [2/2]
const Vector2 & G3D::AnyVal::vector2 (const G3D::Vector2 & defaultVal) const
Definition at line 1186 of file AnyVal.cpp.
{
     if (m_type != VECTOR2) {
         return defaultVal;
     } else {
         return *(Vector2*)m_value;
     }
 }
References m_type, m_value, and VECTOR2.
vector3() [1/2]
const Vector3 & G3D::AnyVal::vector3 () const
Definition at line 1195 of file AnyVal.cpp.
{
     if (m_type != VECTOR3) {
         throw WrongType(VECTOR3, m_type);
     }
     return *(Vector3*)m_value;
 }
References m_type, m_value, and VECTOR3.
Referenced by operator const Vector3 &().
vector3() [2/2]
const Vector3 & G3D::AnyVal::vector3 (const G3D::Vector3 & defaultVal) const
Definition at line 1204 of file AnyVal.cpp.
{
     if (m_type != VECTOR3) {
         return defaultVal;
     } else {
         return *(Vector3*)m_value;
     }
 }
References m_type, m_value, and VECTOR3.
vector4() [1/2]
const Vector4 & G3D::AnyVal::vector4 () const
Definition at line 1213 of file AnyVal.cpp.
{
     if (m_type != VECTOR4) {
         throw WrongType(VECTOR4, m_type);
     }
     return *(Vector4*)m_value;
 }
References m_type, m_value, and VECTOR4.
Referenced by operator const Vector4 &().
vector4() [2/2]
const Vector4 & G3D::AnyVal::vector4 (const G3D::Vector4 & defaultVal) const
Definition at line 1222 of file AnyVal.cpp.
{
     if (m_type != VECTOR4) {
         return defaultVal;
     } else {
         return *(Vector4*)m_value;
     }
 }
References m_type, m_value, and VECTOR4.
Member Data Documentation
m_referenceCount
int* G3D::AnyVal::m_referenceCount private
For table and array types, *m_value is shared between multiple instances. Mutation is allowed only if the reference count is exactly 1, otherwise the mutating instance must copy the value. This is not used for other types.
Definition at line 264 of file AnyVal.h.
Referenced by deleteValue(), deserialize(), isShared(), makeMutable(), and operator=().
m_type
Type G3D::AnyVal::m_type private
Definition at line 256 of file AnyVal.h.
Referenced by aabox(), AnyVal(), append(), boolean(), color1(), color3(), color4(), coordinateFrame(), copyValue(), deleteValue(), deserialize(), get(), getKeys(), isSharedType(), matrix2(), matrix3(), matrix4(), number(), operator=(), operator[](), quat(), rect2D(), serialize(), size(), string(), type(), vector2(), vector3(), and vector4().
m_value
void* G3D::AnyVal::m_value private
Definition at line 257 of file AnyVal.h.
Referenced by aabox(), AnyVal(), append(), boolean(), color1(), color3(), color4(), coordinateFrame(), copyValue(), deleteValue(), deserialize(), get(), getKeys(), makeMutable(), matrix2(), matrix3(), matrix4(), number(), operator=(), operator[](), quat(), rect2D(), serialize(), size(), string(), vector2(), vector3(), and vector4().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/AnyVal.h
deps/g3dlite/source/AnyVal.cpp