Azerotcore-wotlk: FlameLeviathanPursuedTargetSelector Class Reference
FlameLeviathanPursuedTargetSelector Class Reference
Public Member Functions
FlameLeviathanPursuedTargetSelector ()
bool operator() (WorldObject *target) const
Private Types
enum Area { AREA_FORMATION_GROUNDS = 4652 }
Detailed Description
Definition at line 1597 of file boss_flame_leviathan.cpp.
Member Enumeration Documentation
Area
enum FlameLeviathanPursuedTargetSelector::Area private
Enumerator
AREA_FORMATION_GROUNDS
Definition at line 1599 of file boss_flame_leviathan.cpp.
     {
         AREA_FORMATION_GROUNDS = 4652,
     };
Constructor & Destructor Documentation
FlameLeviathanPursuedTargetSelector()
FlameLeviathanPursuedTargetSelector::FlameLeviathanPursuedTargetSelector () inline explicit
Definition at line 1605 of file boss_flame_leviathan.cpp.
 {};
Member Function Documentation
operator()()
bool FlameLeviathanPursuedTargetSelector::operator() (WorldObject * target) const inline
No players, only vehicles (todo: check if blizzlike)
NPC entries must match
NPC must be a valid vehicle installation
Entity needs to be in appropriate area
Vehicle must be in use by player
Definition at line 1607 of file boss_flame_leviathan.cpp.
     {
         Creature* creatureTarget = target->ToCreature();
         if (!creatureTarget)
             return true;
         if (creatureTarget->GetEntry() != NPC_SALVAGED_DEMOLISHER && creatureTarget->GetEntry() != NPC_SALVAGED_SIEGE_ENGINE)
             return true;
         Vehicle* vehicle = creatureTarget->GetVehicleKit();
         if (!vehicle)
             return true;
         if (target->GetAreaId() != AREA_FORMATION_GROUNDS)
             return true;
         bool playerFound = false;
         for (SeatMap::const_iterator itr = vehicle->Seats.begin(); itr != vehicle->Seats.end() && !playerFound; ++itr)
             if (itr->second.Passenger.Guid.IsPlayer())
                 playerFound = true;
         return !playerFound;
     }
References WorldObject::GetAreaId(), Object::GetEntry(), Unit::GetVehicleKit(), NPC_SALVAGED_DEMOLISHER, NPC_SALVAGED_SIEGE_ENGINE, Vehicle::Seats, and Object::ToCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp