Azerotcore-wotlk: titles_commandscript Class Reference
titles_commandscript Class Reference
Public Member Functions
titles_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleTitlesCurrentCommand (ChatHandler *handler, Variant< Hyperlink< title >, uint16 > titleId)
static bool HandleTitlesAddCommand (ChatHandler *handler, Variant< Hyperlink< title >, uint16 > titleId)
static bool HandleTitlesRemoveCommand (ChatHandler *handler, Variant< Hyperlink< title >, uint16 > titleId)
static bool HandleTitlesSetMaskCommand (ChatHandler *handler, uint64 mask)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 33 of file cs_titles.cpp.
Constructor & Destructor Documentation
titles_commandscript()
titles_commandscript::titles_commandscript () inline
Definition at line 36 of file cs_titles.cpp.
 : CommandScript("titles_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable titles_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 38 of file cs_titles.cpp.
     {
         static ChatCommandTable titlesSetCommandTable =
         {
             { "mask", HandleTitlesSetMaskCommand, SEC_GAMEMASTER, Console::No },
         };
         static ChatCommandTable titlesCommandTable =
         {
             { "add",     HandleTitlesAddCommand,     SEC_GAMEMASTER, Console::No },
             { "current", HandleTitlesCurrentCommand, SEC_GAMEMASTER, Console::No },
             { "remove",  HandleTitlesRemoveCommand,  SEC_GAMEMASTER, Console::No },
             { "set",     titlesSetCommandTable },
         };
         static ChatCommandTable commandTable =
         {
             { "titles", titlesCommandTable },
         };
         return commandTable;
     }
References Acore::ChatCommands::No, and SEC_GAMEMASTER.
HandleTitlesAddCommand()
static bool titles_commandscript::HandleTitlesAddCommand (ChatHandler * handler, Variant< Hyperlink< title >, uint16 > titleId) inline static
Definition at line 91 of file cs_titles.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
             return false;
         CharTitlesEntry const* titleInfo = sCharTitlesStore.LookupEntry(titleId);
         if (!titleInfo)
         {
             handler->PSendSysMessage(LANG_INVALID_TITLE_ID, uint32(titleId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         std::string tNameLink = handler->GetNameLink(target);
         std::string titleNameStr = Acore::StringFormat(target->getGender() == GENDER_MALE ? titleInfo->nameMale[handler->GetSessionDbcLocale()] : titleInfo->nameFemale[handler->GetSessionDbcLocale()], target->GetName());
         target->SetTitle(titleInfo);
         handler->PSendSysMessage(LANG_TITLE_ADD_RES, uint32(titleId), titleNameStr, tNameLink);
         return true;
     }
References ObjectGuid::Empty, GENDER_MALE, Unit::getGender(), WorldObject::GetName(), ChatHandler::GetNameLink(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSessionDbcLocale(), ChatHandler::HasLowerSecurity(), LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_ADD_RES, CharTitlesEntry::nameFemale, CharTitlesEntry::nameMale, ChatHandler::PSendSysMessage(), sCharTitlesStore, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Player::SetTitle(), and Acore::StringFormat().
HandleTitlesCurrentCommand()
static bool titles_commandscript::HandleTitlesCurrentCommand (ChatHandler * handler, Variant< Hyperlink< title >, uint16 > titleId) inline static
Definition at line 58 of file cs_titles.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
             return false;
         CharTitlesEntry const* titleInfo = sCharTitlesStore.LookupEntry(titleId);
         if (!titleInfo)
         {
             handler->PSendSysMessage(LANG_INVALID_TITLE_ID, uint32(titleId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         std::string tNameLink = handler->GetNameLink(target);
         std::string titleNameStr = Acore::StringFormat(target->getGender() == GENDER_MALE ? titleInfo->nameMale[handler->GetSessionDbcLocale()] : titleInfo->nameFemale[handler->GetSessionDbcLocale()], target->GetName());
         target->SetTitle(titleInfo);
         target->SetUInt32Value(PLAYER_CHOSEN_TITLE, titleInfo->bit_index);
         handler->PSendSysMessage(LANG_TITLE_CURRENT_RES, uint32(titleId), titleNameStr, tNameLink);
         return true;
     }
References CharTitlesEntry::bit_index, ObjectGuid::Empty, GENDER_MALE, Unit::getGender(), WorldObject::GetName(), ChatHandler::GetNameLink(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSessionDbcLocale(), ChatHandler::HasLowerSecurity(), LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_CURRENT_RES, CharTitlesEntry::nameFemale, CharTitlesEntry::nameMale, PLAYER_CHOSEN_TITLE, ChatHandler::PSendSysMessage(), sCharTitlesStore, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Player::SetTitle(), Object::SetUInt32Value(), and Acore::StringFormat().
HandleTitlesRemoveCommand()
static bool titles_commandscript::HandleTitlesRemoveCommand (ChatHandler * handler, Variant< Hyperlink< title >, uint16 > titleId) inline static
Definition at line 122 of file cs_titles.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
             return false;
         CharTitlesEntry const* titleInfo = sCharTitlesStore.LookupEntry(titleId);
         if (!titleInfo)
         {
             handler->PSendSysMessage(LANG_INVALID_TITLE_ID, uint32(titleId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         target->SetTitle(titleInfo, true);
         std::string tNameLink = handler->GetNameLink(target);
         std::string titleNameStr = Acore::StringFormat(target->getGender() == GENDER_MALE ? titleInfo->nameMale[handler->GetSessionDbcLocale()] : titleInfo->nameFemale[handler->GetSessionDbcLocale()], target->GetName());
         handler->PSendSysMessage(LANG_TITLE_REMOVE_RES, uint32(titleId), titleNameStr, tNameLink);
         if (!target->HasTitle(target->GetInt32Value(PLAYER_CHOSEN_TITLE)))
         {
             target->SetUInt32Value(PLAYER_CHOSEN_TITLE, 0);
             handler->PSendSysMessage(LANG_CURRENT_TITLE_RESET, tNameLink);
         }
         return true;
     }
References ObjectGuid::Empty, GENDER_MALE, Unit::getGender(), Object::GetInt32Value(), WorldObject::GetName(), ChatHandler::GetNameLink(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSessionDbcLocale(), ChatHandler::HasLowerSecurity(), Player::HasTitle(), LANG_CURRENT_TITLE_RESET, LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_REMOVE_RES, CharTitlesEntry::nameFemale, CharTitlesEntry::nameMale, PLAYER_CHOSEN_TITLE, ChatHandler::PSendSysMessage(), sCharTitlesStore, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Player::SetTitle(), Object::SetUInt32Value(), and Acore::StringFormat().
HandleTitlesSetMaskCommand()
static bool titles_commandscript::HandleTitlesSetMaskCommand (ChatHandler * handler, uint64 mask) inline static
Definition at line 161 of file cs_titles.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
             return false;
         uint64 titles2 = mask;
         for (uint32 i = 1; i < sCharTitlesStore.GetNumRows(); ++i)
             if (CharTitlesEntry const* tEntry = sCharTitlesStore.LookupEntry(i))
                 titles2 &= ~(uint64(1) << tEntry->bit_index);
         mask &= ~titles2;                                     // remove non-existing titles
         target->SetUInt64Value(PLAYER__FIELD_KNOWN_TITLES, mask);
         handler->SendSysMessage(LANG_DONE);
         if (!target->HasTitle(target->GetInt32Value(PLAYER_CHOSEN_TITLE)))
         {
             target->SetUInt32Value(PLAYER_CHOSEN_TITLE, 0);
             handler->PSendSysMessage(LANG_CURRENT_TITLE_RESET, handler->GetNameLink(target));
         }
         return true;
     }
References ObjectGuid::Empty, Object::GetInt32Value(), ChatHandler::GetNameLink(), ChatHandler::getSelectedPlayer(), ChatHandler::HasLowerSecurity(), Player::HasTitle(), LANG_CURRENT_TITLE_RESET, LANG_DONE, LANG_NO_CHAR_SELECTED, PLAYER__FIELD_KNOWN_TITLES, PLAYER_CHOSEN_TITLE, ChatHandler::PSendSysMessage(), sCharTitlesStore, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), Object::SetUInt32Value(), and Object::SetUInt64Value().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_titles.cpp