Azerotcore-wotlk: Acore::FriendlyMissingBuffInRange Class Reference
Acore::FriendlyMissingBuffInRange Class Reference
#include <GridNotifiers.h>
Public Member Functions
FriendlyMissingBuffInRange (Unit const *obj, float range, uint32 spellid)
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 i_spell
Detailed Description
Definition at line 777 of file GridNotifiers.h.
Constructor & Destructor Documentation
FriendlyMissingBuffInRange()
Acore::FriendlyMissingBuffInRange::FriendlyMissingBuffInRange (Unit const * obj, float range, uint32 spellid) inline
Definition at line 780 of file GridNotifiers.h.
                                                                                  : i_obj(obj), i_range(range)
         {
             i_spell = spellid;
             if( SpellInfo const* spell = sSpellMgr->GetSpellInfo(spellid) )
                 if( SpellInfo const* newSpell = sSpellMgr->GetSpellForDifficultyFromSpell(spell, const_cast<Unit*>(obj)) )
                     i_spell = newSpell->Id;
         }
References i_spell, and sSpellMgr.
Member Function Documentation
operator()()
bool Acore::FriendlyMissingBuffInRange::operator() (Unit * u) inline
Definition at line 787 of file GridNotifiers.h.
         {
             if (u->IsAlive() && u->IsInCombat() && !i_obj->IsHostileTo(u) && i_obj->IsWithinDistInMap(u, i_range) &&
                     !(u->HasAura(i_spell)))
             {
                 return true;
             }
             return false;
         }
References Unit::HasAura(), i_obj, i_range, i_spell, Unit::IsAlive(), Unit::IsHostileTo(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_obj
Unit const* Acore::FriendlyMissingBuffInRange::i_obj private
Definition at line 797 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::FriendlyMissingBuffInRange::i_range private
Definition at line 798 of file GridNotifiers.h.
Referenced by operator()().
i_spell
uint32 Acore::FriendlyMissingBuffInRange::i_spell private
Definition at line 799 of file GridNotifiers.h.
Referenced by FriendlyMissingBuffInRange(), and operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h