Azerotcore-wotlk: npc_prof_tailor Class Reference
npc_prof_tailor Class Reference
Public Member Functions
npc_prof_tailor ()
bool HasTailorSpell (Player *player)
bool OnGossipHello (Player *player, Creature *creature) override
void SendActionMenu (Player *player, Creature *creature, uint32 action)
void SendConfirmLearn (Player *player, Creature *creature, uint32 action)
void SendConfirmUnlearn (Player *player, Creature *creature, uint32 action)
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1041 of file npc_professions.cpp.
Constructor & Destructor Documentation
npc_prof_tailor()
npc_prof_tailor::npc_prof_tailor () inline
Definition at line 1044 of file npc_professions.cpp.
 : CreatureScript("npc_prof_tailor") { }
Member Function Documentation
HasTailorSpell()
bool npc_prof_tailor::HasTailorSpell (Player * player) inline
Definition at line 1046 of file npc_professions.cpp.
     {
         return (player->HasSpell(S_MOONCLOTH) || player->HasSpell(S_SHADOWEAVE) || player->HasSpell(S_SPELLFIRE));
     }
References Player::HasSpell(), S_MOONCLOTH, S_SHADOWEAVE, and S_SPELLFIRE.
Referenced by OnGossipHello().
OnGossipHello()
bool npc_prof_tailor::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1051 of file npc_professions.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (creature->IsVendor())
             AddGossipItemFor(player, GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         //TAILORING SPEC
         if (player->HasSkill(SKILL_TAILORING) && player->GetBaseSkillValue(SKILL_TAILORING) >= 350 && player->getLevel() > 59)
         {
             if (player->GetQuestRewardStatus(10831) || player->GetQuestRewardStatus(10832) || player->GetQuestRewardStatus(10833))
             {
                 switch (creature->GetEntry())
                 {
                     case N_TRAINER_SPELLFIRE:                                 //Gidge Spellweaver
                         if (!HasTailorSpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SPELLFIRE,    GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 1);
                         if (player->HasSpell(S_SPELLFIRE))
{
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_SPELLFIRE,  GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 4);
                             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                         }
                         break;
                     case N_TRAINER_MOONCLOTH:                                 //Nasmara Moonsong
                         if (!HasTailorSpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_MOONCLOTH,    GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 2);
                         if (player->HasSpell(S_MOONCLOTH))
{
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_MOONCLOTH,  GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 5);
                             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                         }
                         break;
                     case N_TRAINER_SHADOWEAVE:                                 //Andrion Darkspinner
                         if (!HasTailorSpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SHADOWEAVE,   GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 3);
                         if (player->HasSpell(S_SHADOWEAVE))
{
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_SHADOWEAVE, GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 6);
                             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN,      GOSSIP_SENDER_MAIN,     GOSSIP_ACTION_TRAIN);
                         }
                         break;
                 }
             }
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetBaseSkillValue(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Unit::getLevel(), Player::GetQuestRewardStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, GOSSIP_ICON_CHAT, GOSSIP_ICON_TRAINER, GOSSIP_ICON_VENDOR, GOSSIP_LEARN_MOONCLOTH, GOSSIP_LEARN_SHADOWEAVE, GOSSIP_LEARN_SPELLFIRE, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_TEXT_TRAIN, GOSSIP_UNLEARN_MOONCLOTH, GOSSIP_UNLEARN_SHADOWEAVE, GOSSIP_UNLEARN_SPELLFIRE, Player::HasSkill(), Player::HasSpell(), HasTailorSpell(), Unit::IsQuestGiver(), Unit::IsVendor(), N_TRAINER_MOONCLOTH, N_TRAINER_SHADOWEAVE, N_TRAINER_SPELLFIRE, Player::PrepareQuestMenu(), S_MOONCLOTH, S_SHADOWEAVE, S_SPELLFIRE, SendGossipMenuFor(), and SKILL_TAILORING.
OnGossipSelect()
bool npc_prof_tailor::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1184 of file npc_professions.cpp.
     {
         ClearGossipMenuFor(player);
         switch (sender)
         {
             case GOSSIP_SENDER_MAIN:
                 SendActionMenu(player, creature, action);
                 break;
             case GOSSIP_SENDER_LEARN:
                 SendConfirmLearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_UNLEARN:
                 SendConfirmUnlearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_CHECK:
                 SendActionMenu(player, creature, action);
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), GOSSIP_SENDER_CHECK, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, SendActionMenu(), SendConfirmLearn(), and SendConfirmUnlearn().
SendActionMenu()
void npc_prof_tailor::SendActionMenu (Player * player, Creature * creature, uint32 action) inline
Definition at line 1101 of file npc_professions.cpp.
     {
         switch (action)
         {
             case GOSSIP_ACTION_TRADE:
                 player->GetSession()->SendListInventory(creature->GetGUID());
                 break;
             case GOSSIP_ACTION_TRAIN:
                 player->GetSession()->SendTrainerList(creature->GetGUID());
                 break;
             //Learn Tailor
             case GOSSIP_ACTION_INFO_DEF + 1:
                 ProcessCastaction(player, creature, S_SPELLFIRE, S_LEARN_SPELLFIRE, DoLearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 ProcessCastaction(player, creature, S_MOONCLOTH, S_LEARN_MOONCLOTH, DoLearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 ProcessCastaction(player, creature, S_SHADOWEAVE, S_LEARN_SHADOWEAVE, DoLearnCost(player));
                 break;
             //Unlearn Tailor
             case GOSSIP_ACTION_INFO_DEF + 4:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_SPELLFIRE, 0, DoHighUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 5:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_MOONCLOTH, 0, DoHighUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 6:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_SHADOWEAVE, 0, DoHighUnlearnCost(player));
                 break;
         }
     }
References DoHighUnlearnCost(), DoLearnCost(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, ProcessCastaction(), ProcessUnlearnAction(), S_LEARN_MOONCLOTH, S_LEARN_SHADOWEAVE, S_LEARN_SPELLFIRE, S_MOONCLOTH, S_SHADOWEAVE, S_SPELLFIRE, S_UNLEARN_MOONCLOTH, S_UNLEARN_SHADOWEAVE, S_UNLEARN_SPELLFIRE, WorldSession::SendListInventory(), and WorldSession::SendTrainerList().
Referenced by OnGossipSelect().
SendConfirmLearn()
void npc_prof_tailor::SendConfirmLearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 1134 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_SPELLFIRE:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SPELLFIRE, GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_MOONCLOTH:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_MOONCLOTH,    GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_SHADOWEAVE:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_SHADOWEAVE,  GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ICON_CHAT, GOSSIP_LEARN_MOONCLOTH, GOSSIP_LEARN_SHADOWEAVE, GOSSIP_LEARN_SPELLFIRE, GOSSIP_SENDER_CHECK, N_TRAINER_MOONCLOTH, N_TRAINER_SHADOWEAVE, N_TRAINER_SPELLFIRE, and SendGossipMenuFor().
Referenced by OnGossipSelect().
SendConfirmUnlearn()
void npc_prof_tailor::SendConfirmUnlearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 1159 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_SPELLFIRE:                                     //Gidge Spellweaver
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_SPELLFIRE, GOSSIP_SENDER_CHECK, action, BOX_UNLEARN_TAILOR_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_MOONCLOTH:                                     //Nasmara Moonsong
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_MOONCLOTH, GOSSIP_SENDER_CHECK, action, BOX_UNLEARN_TAILOR_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_SHADOWEAVE:                                     //Andrion Darkspinner
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_SHADOWEAVE, GOSSIP_SENDER_CHECK, action, BOX_UNLEARN_TAILOR_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), BOX_UNLEARN_TAILOR_SPEC, DoHighUnlearnCost(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_SENDER_CHECK, GOSSIP_UNLEARN_MOONCLOTH, GOSSIP_UNLEARN_SHADOWEAVE, GOSSIP_UNLEARN_SPELLFIRE, N_TRAINER_MOONCLOTH, N_TRAINER_SHADOWEAVE, N_TRAINER_SPELLFIRE, and SendGossipMenuFor().
Referenced by OnGossipSelect().
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_professions.cpp