Azerotcore-wotlk: go_soulwell::go_soulwellAI Struct Reference
go_soulwell::go_soulwellAI Struct Reference
Public Member Functions
go_soulwellAI (GameObject *go)
bool GossipHello (Player *player, bool reportUse) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
uint32 _stoneSpell
uint32 _stoneId
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 1344 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_soulwellAI()
go_soulwell::go_soulwellAI::go_soulwellAI (GameObject * go) inline
Definition at line 1346 of file go_scripts.cpp.
                                       : GameObjectAI(go)
         {
             _stoneSpell = 0;
             _stoneId = 0;
             switch (go->GetEntry())
             {
                 case GO_SOUL_WELL_R1:
                     _stoneSpell = SPELL_CREATE_MASTER_HEALTH_STONE_R0;
                     if (Unit* owner = go->GetOwner())
                     {
                         if (owner->HasAura(SPELL_IMPROVED_HEALTH_STONE_R1))
                             _stoneSpell = SPELL_CREATE_MASTER_HEALTH_STONE_R1;
                         else if (owner->HasAura(SPELL_CREATE_MASTER_HEALTH_STONE_R2))
                             _stoneSpell = SPELL_CREATE_MASTER_HEALTH_STONE_R2;
                     }
                     break;
                 case GO_SOUL_WELL_R2:
                     _stoneSpell = SPELL_CREATE_FEL_HEALTH_STONE_R0;
                     if (Unit* owner = go->GetOwner())
                     {
                         if (owner->HasAura(SPELL_IMPROVED_HEALTH_STONE_R1))
                             _stoneSpell = SPELL_CREATE_FEL_HEALTH_STONE_R1;
                         else if (owner->HasAura(SPELL_CREATE_MASTER_HEALTH_STONE_R2))
                             _stoneSpell = SPELL_CREATE_FEL_HEALTH_STONE_R2;
                     }
                     break;
             }
             if (_stoneSpell == 0) // Should never happen
                 return;
             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(_stoneSpell);
             if (!spellInfo)
                 return;
             _stoneId = spellInfo->Effects[EFFECT_0].ItemType;
         }
References _stoneId, _stoneSpell, EFFECT_0, SpellInfo::Effects, Object::GetEntry(), GameObject::GetOwner(), GO_SOUL_WELL_R1, GO_SOUL_WELL_R2, SPELL_CREATE_FEL_HEALTH_STONE_R0, SPELL_CREATE_FEL_HEALTH_STONE_R1, SPELL_CREATE_FEL_HEALTH_STONE_R2, SPELL_CREATE_MASTER_HEALTH_STONE_R0, SPELL_CREATE_MASTER_HEALTH_STONE_R1, SPELL_CREATE_MASTER_HEALTH_STONE_R2, SPELL_IMPROVED_HEALTH_STONE_R1, and sSpellMgr.
Member Function Documentation
GossipHello()
bool go_soulwell::go_soulwellAI::GossipHello (Player * player, bool reportUse) inline override virtual
Due to the fact that this GameObject triggers CMSG_GAMEOBJECT_USE and CMSG_GAMEOBJECT_REPORT_USE, this GossipHello hook is called twice. The script's handling is fine as it won't remove two charges on the well. We have to find how to segregate REPORT_USE and USE.
Reimplemented from GameObjectAI.
Definition at line 1387 of file go_scripts.cpp.
         {
             if (reportUse)
                 return false;
             Unit* owner = me->GetOwner();
             if (_stoneSpell == 0 || _stoneId == 0)
             {
                 if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(_stoneSpell))
                     Spell::SendCastResult(player, spell, 0, SPELL_FAILED_ERROR);
                 return true;
             }
             if (!owner || owner->GetTypeId() != TYPEID_PLAYER || !player->IsInSameRaidWith(owner->ToPlayer()))
             {
                 if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(_stoneSpell))
                     Spell::SendCastResult(player, spell, 0, SPELL_FAILED_TARGET_NOT_IN_RAID);
                 return true;
             }
             // Don't try to add a stone if we already have one.
             if (player->HasItemCount(_stoneId))
             {
                 if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(_stoneSpell))
                     Spell::SendCastResult(player, spell, 0, SPELL_FAILED_TOO_MANY_OF_ITEM);
                 return true;
             }
             player->CastSpell(player, _stoneSpell, false);
             // Item has to actually be created to remove a charge on the well.
             if (player->HasItemCount(_stoneId))
                 me->AddUse();
             return true;
         }
References _stoneId, _stoneSpell, GameObject::AddUse(), Unit::CastSpell(), GameObject::GetOwner(), Object::GetTypeId(), Player::HasItemCount(), Player::IsInSameRaidWith(), GameObjectAI::me, Spell::SendCastResult(), SPELL_FAILED_ERROR, SPELL_FAILED_TARGET_NOT_IN_RAID, SPELL_FAILED_TOO_MANY_OF_ITEM, sSpellMgr, Object::ToPlayer(), and TYPEID_PLAYER.
Member Data Documentation
_stoneId
uint32 go_soulwell::go_soulwellAI::_stoneId private
Definition at line 1426 of file go_scripts.cpp.
Referenced by go_soulwellAI(), and GossipHello().
_stoneSpell
uint32 go_soulwell::go_soulwellAI::_stoneSpell private
Definition at line 1425 of file go_scripts.cpp.
Referenced by go_soulwellAI(), and GossipHello().
The documentation for this struct was generated from the following file:
src/server/scripts/World/go_scripts.cpp