Azerotcore-wotlk: npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI Struct Reference
npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI Struct Reference
Public Member Functions
npc_icc_nerubar_broodkeeperAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void EnterCombat (Unit *) override
void JustReachedHome () override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool _didWebBeam
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 3319 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_icc_nerubar_broodkeeperAI()
npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::npc_icc_nerubar_broodkeeperAI (Creature * creature) inline
Definition at line 3321 of file icecrown_citadel.cpp.
                                                           : ScriptedAI(creature)
         {
             me->SetDisableGravity(true);
             _didWebBeam = false;
             me->m_SightDistance = 100.0f; // for MoveInLineOfSight distance
         }
References _didWebBeam, Creature::m_SightDistance, ScriptedAI::me, and Creature::SetDisableGravity().
Member Function Documentation
EnterCombat()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 3360 of file icecrown_citadel.cpp.
         {
             me->CallForHelp(15.0f);
         }
References Creature::CallForHelp(), and ScriptedAI::me.
JustReachedHome()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 3365 of file icecrown_citadel.cpp.
         {
             if (me->IsLevitating())
             {
                 me->SetDisableGravity(false);
                 me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
             }
         }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsLevitating(), ScriptedAI::me, Unit::NearTeleportTo(), and Creature::SetDisableGravity().
MoveInLineOfSight()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3340 of file icecrown_citadel.cpp.
         {
             if (!_didWebBeam && who->GetTypeId() == TYPEID_PLAYER && me->GetExactDist2d(who) < 70.0f)
             {
                 _didWebBeam = true;
                 float nx = me->GetPositionX();
                 float ny = me->GetPositionY();
                 float nz = me->GetFloorZ();
                 me->SetHomePosition(nx, ny, nz, me->GetOrientation());
                 me->CastSpell(me, SPELL_WEB_BEAM, false);
                 me->GetMotionMaster()->MovePoint(1, nx, ny, nz, false);
                 return;
             }
             if (me->IsLevitating())
                 return;
             ScriptedAI::MoveInLineOfSight(who);
         }
References _didWebBeam, Unit::CastSpell(), Position::GetExactDist2d(), WorldObject::GetFloorZ(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Object::GetTypeId(), Unit::IsLevitating(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), MotionMaster::MovePoint(), Creature::SetHomePosition(), SPELL_WEB_BEAM, and TYPEID_PLAYER.
MovementInform()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 3374 of file icecrown_citadel.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == 1)
             {
                 if (me->IsLevitating())
                 {
                     me->SetDisableGravity(false);
                     me->SetOrientation(0.0f);
                     me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
                     me->ClearUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                 }
             }
         }
References Unit::ClearUnitState(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsLevitating(), ScriptedAI::me, Unit::NearTeleportTo(), POINT_MOTION_TYPE, Creature::SetDisableGravity(), Position::SetOrientation(), and UNIT_STATE_NO_ENVIRONMENT_UPD.
Reset()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 3331 of file icecrown_citadel.cpp.
         {
             events.Reset();
             events.ScheduleEvent(1, urand(3000, 10000)); // Crypt Scarabs
             events.ScheduleEvent(2, urand(15000, 25000)); // Dark Mending
             events.ScheduleEvent(3, urand(8000, 15000)); // Web Wrap
             me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
         }
References Unit::AddUnitState(), ScriptedAI::me, UNIT_STATE_NO_ENVIRONMENT_UPD, and urand().
UpdateAI()
void npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 3388 of file icecrown_citadel.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     me->CastSpell(me->GetVictim(), 70965, false);
                     events.RepeatEvent(urand(20000, 30000));
                     break;
                 case 2:
                     me->CastSpell(me->GetVictim(), 71020, false);
                     events.RepeatEvent(urand(20000, 30000));
                     break;
                 case 3:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f, true))
                         me->CastSpell(target, 70980, false);
                     events.RepeatEvent(urand(20000, 30000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_didWebBeam
bool npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::_didWebBeam
Definition at line 3329 of file icecrown_citadel.cpp.
Referenced by MoveInLineOfSight(), and npc_icc_nerubar_broodkeeperAI().
events
EventMap npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::events
Definition at line 3328 of file icecrown_citadel.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp