Azerotcore-wotlk: npc_crusade_persuaded::npc_crusade_persuadedAI Struct Reference
npc_crusade_persuaded::npc_crusade_persuadedAI Struct Reference
Public Member Functions
npc_crusade_persuadedAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void JustDied (Unit *killer) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 speechTimer
uint32 speechCounter
ObjectGuid playerGUID
Additional Inherited Members
Static Public Member Functions inherited from CombatAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 55 of file chapter2.cpp.
Constructor & Destructor Documentation
npc_crusade_persuadedAI()
npc_crusade_persuaded::npc_crusade_persuadedAI::npc_crusade_persuadedAI (Creature * creature) inline
Definition at line 57 of file chapter2.cpp.
 : CombatAI(creature) { }
Member Function Documentation
EnterCombat()
void npc_crusade_persuaded::npc_crusade_persuadedAI::EnterCombat (Unit *) inline override virtual
Reimplemented from CombatAI.
Definition at line 72 of file chapter2.cpp.
         {
             if (roll_chance_i(33))
                 Talk(SAY_AGGRO);
         }
References roll_chance_i(), SAY_AGGRO, and CreatureAI::Talk().
Reset()
void npc_crusade_persuaded::npc_crusade_persuadedAI::Reset () inline override virtual
Reimplemented from CombatAI.
Definition at line 63 of file chapter2.cpp.
         {
             speechTimer = 0;
             speechCounter = 0;
             playerGUID.Clear();
             me->SetReactState(REACT_AGGRESSIVE);
             me->RestoreFaction();
         }
References ObjectGuid::Clear(), CreatureAI::me, playerGUID, REACT_AGGRESSIVE, Unit::RestoreFaction(), Creature::SetReactState(), speechCounter, and speechTimer.
SpellHit()
void npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 78 of file chapter2.cpp.
         {
             if (spell->Id == SPELL_PERSUASIVE_STRIKE && caster->GetTypeId() == TYPEID_PLAYER && me->IsAlive() && !speechCounter)
             {
                 if (Player* player = caster->ToPlayer())
                 {
                     if (player->GetQuestStatus(QUEST_HOW_TO_WIN_FRIENDS) == QUEST_STATUS_INCOMPLETE)
                     {
                         playerGUID = player->GetGUID();
                         speechTimer = 1000;
                         speechCounter = 1;
                         me->SetFaction(player->GetFaction());
                         me->CombatStop(true);
                         me->GetMotionMaster()->MoveIdle();
                         me->SetReactState(REACT_PASSIVE);
                         DoCastAOE(SPELL_THREAT_PULSE, true);
                         sCreatureTextMgr->SendChat(me, SAY_PERSUADE_RAND, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
                         Talk(SAY_CRUSADER);
                     }
                 }
             }
         }
References CHAT_MSG_ADDON, Unit::CombatStop(), UnitAI::DoCastAOE(), Unit::GetMotionMaster(), Object::GetTypeId(), SpellInfo::Id, Unit::IsAlive(), LANG_ADDON, CreatureAI::me, MotionMaster::MoveIdle(), playerGUID, QUEST_HOW_TO_WIN_FRIENDS, QUEST_STATUS_INCOMPLETE, REACT_PASSIVE, SAY_CRUSADER, SAY_PERSUADE_RAND, sCreatureTextMgr, Unit::SetFaction(), Creature::SetReactState(), speechCounter, speechTimer, SPELL_PERSUASIVE_STRIKE, SPELL_THREAT_PULSE, CreatureAI::Talk(), TEAM_NEUTRAL, TEXT_RANGE_NORMAL, Object::ToPlayer(), and TYPEID_PLAYER.
UpdateAI()
void npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from CombatAI.
Definition at line 102 of file chapter2.cpp.
         {
             if (speechCounter)
             {
                 if (speechTimer <= diff)
                 {
                     Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
                     if (!player)
                     {
                         EnterEvadeMode();
                         return;
                     }
                     switch (speechCounter)
                     {
                         case 1:
                             Talk(SAY_PERSUADED1);
                             speechTimer = 8000;
                             break;
                         case 2:
                             Talk(SAY_PERSUADED2);
                             speechTimer = 8000;
                             break;
                         case 3:
                             Talk(SAY_PERSUADED3);
                             speechTimer = 8000;
                             break;
                         case 4:
                             Talk(SAY_PERSUADED4);
                             speechTimer = 8000;
                             break;
                         case 5:
                             sCreatureTextMgr->SendChat(me, SAY_PERSUADED5, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
                             speechTimer = 8000;
                             break;
                         case 6:
                             Talk(SAY_PERSUADED6);
                             Unit::Kill(player, me);
                             speechCounter = 0;
                             player->GroupEventHappens(QUEST_HOW_TO_WIN_FRIENDS, me);
                             return;
                     }
                     ++speechCounter;
                     DoCastAOE(SPELL_THREAT_PULSE, true);
                 }
                 else
                     speechTimer -= diff;
                 return;
             }
             CombatAI::UpdateAI(diff);
         }
References CHAT_MSG_ADDON, diff(), UnitAI::DoCastAOE(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetPlayer(), Player::GroupEventHappens(), Unit::Kill(), LANG_ADDON, CreatureAI::me, playerGUID, QUEST_HOW_TO_WIN_FRIENDS, SAY_PERSUADED1, SAY_PERSUADED2, SAY_PERSUADED3, SAY_PERSUADED4, SAY_PERSUADED5, SAY_PERSUADED6, sCreatureTextMgr, speechCounter, speechTimer, SPELL_THREAT_PULSE, CreatureAI::Talk(), TEAM_NEUTRAL, TEXT_RANGE_NORMAL, and CombatAI::UpdateAI().
Member Data Documentation
playerGUID
ObjectGuid npc_crusade_persuaded::npc_crusade_persuadedAI::playerGUID
Definition at line 61 of file chapter2.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
speechCounter
uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::speechCounter
Definition at line 60 of file chapter2.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
speechTimer
uint32 npc_crusade_persuaded::npc_crusade_persuadedAI::speechTimer
Definition at line 59 of file chapter2.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp