Azerotcore-wotlk: buffered_file Class Reference
buffered_file Class Reference
#include <os.h>
Public Member Functions
buffered_file (const buffered_file &)=delete
void operator= (const buffered_file &)=delete
buffered_file () FMT_NOEXCEPT
FMT_API ~buffered_file () FMT_NOEXCEPT
buffered_file (buffered_file &&other) FMT_NOEXCEPT
buffered_file & operator= (buffered_file &&other)
FMT_API buffered_file (cstring_view filename, cstring_view mode)
FMT_API void close ()
FILE * get () const FMT_NOEXCEPT
FMT_API int() fileno () const
void vprint (string_view format_str, format_args args)
template<typename... Args>
void print (string_view format_str, const Args &... args)
Private Member Functions
buffered_file (FILE *f)
Private Attributes
FILE * file_
Friends
class file
Detailed Description
Definition at line 224 of file os.h.
Constructor & Destructor Documentation
buffered_file() [1/5]
buffered_file::buffered_file (FILE * f) inline explicit private
Definition at line 230 of file os.h.
 : file_(f) {}
buffered_file() [2/5]
buffered_file::buffered_file (const buffered_file &) delete
buffered_file() [3/5]
buffered_file::buffered_file () inline
Definition at line 237 of file os.h.
 : file_(nullptr) {}
~buffered_file()
FMT_BEGIN_NAMESPACE buffered_file::~buffered_file ()
Definition at line 186 of file os.cc.
{
   if (file_ && FMT_SYSTEM(fclose(file_)) != 0)
     report_system_error(errno, "cannot close file");
 }
References errno, file_, FMT_SYSTEM, and report_system_error().
buffered_file() [4/5]
buffered_file::buffered_file (buffered_file && other) inline
Definition at line 243 of file os.h.
                                                     : file_(other.file_) {
     other.file_ = nullptr;
   }
buffered_file() [5/5]
buffered_file::buffered_file (cstring_view filename, cstring_view mode)
Definition at line 191 of file os.cc.
{
   FMT_RETRY_VAL(file_, FMT_SYSTEM(fopen(filename.c_str(), mode.c_str())),
                 nullptr);
   if (!file_)
     FMT_THROW(system_error(errno, "cannot open file {}", filename.c_str()));
 }
References basic_cstring_view< Char >::c_str(), errno, file_, FMT_RETRY_VAL, FMT_SYSTEM, FMT_THROW, and system_error().
Member Function Documentation
close()
void buffered_file::close ()
Definition at line 198 of file os.cc.
{
   if (!file_) return;
   int result = FMT_SYSTEM(fclose(file_));
   file_ = nullptr;
   if (result != 0) FMT_THROW(system_error(errno, "cannot close file"));
 }
References errno, file_, FMT_SYSTEM, FMT_THROW, and system_error().
Referenced by operator=().
fileno()
int buffered_file::fileno () const
Definition at line 208 of file os.cc.
{
   int fd = FMT_POSIX_CALL(fileno FMT_ARGS(file_));
   if (fd == -1) FMT_THROW(system_error(errno, "cannot get file descriptor"));
   return fd;
 }
References errno, file_, FMT_ARGS, FMT_POSIX_CALL, FMT_THROW, and system_error().
get()
FILE* buffered_file::get () const inline
Definition at line 261 of file os.h.
 { return file_; }
References file_.
operator=() [1/2]
buffered_file& buffered_file::operator= (buffered_file && other) inline
Definition at line 247 of file os.h.
{
     close();
     file_ = other.file_;
     other.file_ = nullptr;
     return *this;
   }
References close(), and file_.
operator=() [2/2]
void buffered_file::operator= (const buffered_file &) delete
print()
template<typename... Args> void buffered_file::print (string_view format_str, const Args &... args) inline
Definition at line 272 of file os.h.
{
     vprint(format_str, fmt::make_format_args(args...));
   }
References make_format_args(), and vprint().
vprint()
void buffered_file::vprint (string_view format_str, format_args args) inline
Definition at line 267 of file os.h.
{
     fmt::vprint(file_, format_str, args);
   }
References file_, and vprint().
Referenced by print().
Friends And Related Function Documentation
file
friend class file friend
Definition at line 228 of file os.h.
Member Data Documentation
file_
FILE* buffered_file::file_ private
Definition at line 226 of file os.h.
Referenced by buffered_file(), close(), fileno(), get(), operator=(), vprint(), and ~buffered_file().
The documentation for this class was generated from the following files:
deps/fmt/include/fmt/os.h
deps/fmt/src/os.cc