Azerotcore-wotlk: RedirectThreatInfo Struct Reference
RedirectThreatInfo Struct Reference
#include <Unit.h>
Public Member Functions
RedirectThreatInfo ()
ObjectGuid GetTargetGUID () const
uint32 GetThreatPct () const
void Set (ObjectGuid guid, uint32 pct)
void ModifyThreatPct (int32 amount)
Public Attributes
ObjectGuid _targetGUID
uint32 _threatPct {0}
Detailed Description
Definition at line 1075 of file Unit.h.
Constructor & Destructor Documentation
RedirectThreatInfo()
RedirectThreatInfo::RedirectThreatInfo () inline
Definition at line 1077 of file Unit.h.
 { }
Member Function Documentation
GetTargetGUID()
ObjectGuid RedirectThreatInfo::GetTargetGUID () const inline
Definition at line 1081 of file Unit.h.
 { return _targetGUID; }
References _targetGUID.
Referenced by Unit::GetRedirectThreatTarget().
GetThreatPct()
uint32 RedirectThreatInfo::GetThreatPct () const inline
Definition at line 1082 of file Unit.h.
 { return _threatPct; }
References _threatPct.
Referenced by Unit::GetRedirectThreatPercent().
ModifyThreatPct()
void RedirectThreatInfo::ModifyThreatPct (int32 amount) inline
Definition at line 1090 of file Unit.h.
     {
         amount += _threatPct;
         _threatPct = uint32(std::max(0, amount));
     }
References _threatPct, and max.
Referenced by Unit::ModifyRedirectThreat().
Set()
void RedirectThreatInfo::Set (ObjectGuid guid, uint32 pct) inline
Definition at line 1084 of file Unit.h.
     {
         _targetGUID = guid;
         _threatPct = pct;
     }
References _targetGUID, and _threatPct.
Referenced by Unit::SetRedirectThreat().
Member Data Documentation
_targetGUID
ObjectGuid RedirectThreatInfo::_targetGUID
Definition at line 1078 of file Unit.h.
Referenced by GetTargetGUID(), and Set().
_threatPct
uint32 RedirectThreatInfo::_threatPct {0}
Definition at line 1079 of file Unit.h.
Referenced by GetThreatPct(), ModifyThreatPct(), and Set().
The documentation for this struct was generated from the following file:
src/server/game/Entities/Unit/Unit.h