Azerotcore-wotlk: achievement_ignis_shattered Class Reference
achievement_ignis_shattered Class Reference
Public Member Functions
achievement_ignis_shattered ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 564 of file boss_ignis.cpp.
Constructor & Destructor Documentation
achievement_ignis_shattered()
achievement_ignis_shattered::achievement_ignis_shattered () inline
Definition at line 567 of file boss_ignis.cpp.
 : AchievementCriteriaScript("achievement_ignis_shattered") {}
Member Function Documentation
OnCheck()
bool achievement_ignis_shattered::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 569 of file boss_ignis.cpp.
     {
         if (!target || target->GetTypeId() != TYPEID_UNIT)
             return false;
         return !!target->ToCreature()->AI()->GetData(1337);
     }
References Creature::AI(), UnitAI::GetData(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp