Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/bit_util.h File Reference
bit_util.h File Reference
#include "jemalloc/internal/assert.h"
Macros
#define BIT_UTIL_INLINE static inline
#define LG_FLOOR_1(x) 0
#define LG_FLOOR_2(x) (x < (1ULL << 1) ? LG_FLOOR_1(x) : 1 + LG_FLOOR_1(x >> 1))
#define LG_FLOOR_4(x) (x < (1ULL << 2) ? LG_FLOOR_2(x) : 2 + LG_FLOOR_2(x >> 2))
#define LG_FLOOR_8(x) (x < (1ULL << 4) ? LG_FLOOR_4(x) : 4 + LG_FLOOR_4(x >> 4))
#define LG_FLOOR_16(x) (x < (1ULL << 8) ? LG_FLOOR_8(x) : 8 + LG_FLOOR_8(x >> 8))
#define LG_FLOOR_32(x) (x < (1ULL << 16) ? LG_FLOOR_16(x) : 16 + LG_FLOOR_16(x >> 16))
#define LG_FLOOR_64(x) (x < (1ULL << 32) ? LG_FLOOR_32(x) : 32 + LG_FLOOR_32(x >> 32))
#define LG_FLOOR(x) LG_FLOOR_64((x))
#define LG_CEIL(x) (LG_FLOOR(x) + (((x) & ((x) - 1)) == 0 ? 0 : 1))
Functions
BIT_UTIL_INLINE unsigned ffs_llu (unsigned long long bitmap)
BIT_UTIL_INLINE unsigned ffs_lu (unsigned long bitmap)
BIT_UTIL_INLINE unsigned ffs_u (unsigned bitmap)
BIT_UTIL_INLINE size_t cfs_lu (unsigned long *bitmap)
BIT_UTIL_INLINE unsigned ffs_zu (size_t bitmap)
BIT_UTIL_INLINE unsigned ffs_u64 (uint64_t bitmap)
BIT_UTIL_INLINE unsigned ffs_u32 (uint32_t bitmap)
BIT_UTIL_INLINE uint64_t pow2_ceil_u64 (uint64_t x)
BIT_UTIL_INLINE uint32_t pow2_ceil_u32 (uint32_t x)
BIT_UTIL_INLINE size_t pow2_ceil_zu (size_t x)
BIT_UTIL_INLINE unsigned lg_floor (size_t x)
BIT_UTIL_INLINE unsigned lg_ceil (size_t x)
Macro Definition Documentation
BIT_UTIL_INLINE
#define BIT_UTIL_INLINE static inline
Definition at line 6 of file bit_util.h.
LG_CEIL
#define LG_CEIL (x) (LG_FLOOR(x) + (((x) & ((x) - 1)) == 0 ? 0 : 1))
Definition at line 237 of file bit_util.h.
LG_FLOOR
#define LG_FLOOR (x) LG_FLOOR_64((x))
Definition at line 234 of file bit_util.h.
LG_FLOOR_1
#define LG_FLOOR_1 (x) 0
Definition at line 224 of file bit_util.h.
LG_FLOOR_16
#define LG_FLOOR_16 (x) (x < (1ULL << 8) ? LG_FLOOR_8(x) : 8 + LG_FLOOR_8(x >> 8))
Definition at line 228 of file bit_util.h.
LG_FLOOR_2
#define LG_FLOOR_2 (x) (x < (1ULL << 1) ? LG_FLOOR_1(x) : 1 + LG_FLOOR_1(x >> 1))
Definition at line 225 of file bit_util.h.
LG_FLOOR_32
#define LG_FLOOR_32 (x) (x < (1ULL << 16) ? LG_FLOOR_16(x) : 16 + LG_FLOOR_16(x >> 16))
Definition at line 229 of file bit_util.h.
LG_FLOOR_4
#define LG_FLOOR_4 (x) (x < (1ULL << 2) ? LG_FLOOR_2(x) : 2 + LG_FLOOR_2(x >> 2))
Definition at line 226 of file bit_util.h.
LG_FLOOR_64
#define LG_FLOOR_64 (x) (x < (1ULL << 32) ? LG_FLOOR_32(x) : 32 + LG_FLOOR_32(x >> 32))
Definition at line 230 of file bit_util.h.
LG_FLOOR_8
#define LG_FLOOR_8 (x) (x < (1ULL << 4) ? LG_FLOOR_4(x) : 4 + LG_FLOOR_4(x >> 4))
Definition at line 227 of file bit_util.h.
Function Documentation
cfs_lu()
BIT_UTIL_INLINE size_t cfs_lu (unsigned long * bitmap)
Definition at line 43 of file bit_util.h.
{
     size_t bit = ffs_lu(*bitmap) - 1;
     *bitmap ^= ZU(1) << bit;
     return bit;
 }
References ffs_lu(), and ZU.
Referenced by arena_slab_reg_alloc_batch().
ffs_llu()
BIT_UTIL_INLINE unsigned ffs_llu (unsigned long long bitmap)
Definition at line 16 of file bit_util.h.
{
     return JEMALLOC_INTERNAL_FFSLL(bitmap);
 }
Referenced by ffs_u64(), and ffs_zu().
ffs_lu()
BIT_UTIL_INLINE unsigned ffs_lu (unsigned long bitmap)
Definition at line 21 of file bit_util.h.
{
     return JEMALLOC_INTERNAL_FFSL(bitmap);
 }
Referenced by bitmap_ffu(), bitmap_sfu(), cfs_lu(), ffs_u64(), and ffs_zu().
ffs_u()
BIT_UTIL_INLINE unsigned ffs_u (unsigned bitmap)
Definition at line 26 of file bit_util.h.
{
     return JEMALLOC_INTERNAL_FFS(bitmap);
 }
Referenced by ffs_u32(), and ffs_zu().
ffs_u32()
BIT_UTIL_INLINE unsigned ffs_u32 (uint32_t bitmap)
Definition at line 74 of file bit_util.h.
{
 #if LG_SIZEOF_INT == 2
     return ffs_u(bitmap);
 #else
 #error No implementation for 32-bit ffs()
 #endif
     return ffs_u(bitmap);
 }
References ffs_u().
Referenced by prng_range_u32().
ffs_u64()
BIT_UTIL_INLINE unsigned ffs_u64 (uint64_t bitmap)
Definition at line 63 of file bit_util.h.
{
 #if LG_SIZEOF_LONG == 3
     return ffs_lu(bitmap);
 #elif LG_SIZEOF_LONG_LONG == 3
     return ffs_llu(bitmap);
 #else
 #error No implementation for 64-bit ffs()
 #endif
 }
References ffs_llu(), and ffs_lu().
Referenced by prng_range_u64(), and prng_range_zu().
ffs_zu()
BIT_UTIL_INLINE unsigned ffs_zu (size_t bitmap)
Definition at line 50 of file bit_util.h.
                       {
 #if LG_SIZEOF_PTR == LG_SIZEOF_INT
     return ffs_u(bitmap);
 #elif LG_SIZEOF_PTR == LG_SIZEOF_LONG
     return ffs_lu(bitmap);
 #elif LG_SIZEOF_PTR == LG_SIZEOF_LONG_LONG
     return ffs_llu(bitmap);
 #else
 #error No implementation for size_t ffs()
 #endif
 }
References ffs_llu(), ffs_lu(), and ffs_u().
Referenced by lg_floor(), and pages_map().
lg_ceil()
BIT_UTIL_INLINE unsigned lg_ceil (size_t x)
Definition at line 217 of file bit_util.h.
                   {
     return lg_floor(x) + ((x & (x - 1)) == 0 ? 0 : 1);
 }
References lg_floor(), and G3D::x.
Referenced by size_classes(), sz_s2u_compute(), and sz_size2index_compute().
lg_floor()
BIT_UTIL_INLINE unsigned lg_floor (size_t x)
Definition at line 197 of file bit_util.h.
                    {
     assert(x != 0);
     x |= (x >> 1);
     x |= (x >> 2);
     x |= (x >> 4);
     x |= (x >> 8);
     x |= (x >> 16);
 #if (LG_SIZEOF_PTR == 3)
     x |= (x >> 32);
 #endif
     if (x == SIZE_T_MAX) {
         return (8 << LG_SIZEOF_PTR) - 1;
     }
     x++;
     return ffs_zu(x) - 2;
 }
References assert(), ffs_zu(), SIZE_T_MAX, and G3D::x.
Referenced by extent_addr_randomize(), lg_ceil(), sz_psz2ind(), sz_psz2u(), sz_s2u_compute(), and sz_size2index_compute().
pow2_ceil_u32()
BIT_UTIL_INLINE uint32_t pow2_ceil_u32 (uint32_t x)
Definition at line 114 of file bit_util.h.
{
 #if ((defined(__i386__) || defined(JEMALLOC_HAVE_BUILTIN_CLZ)) && (!defined(__s390__)))
     if(unlikely(x <= 1)) {
         return x;
     }
     size_t msb_on_index;
 #if (defined(__i386__))
     asm ("bsr %1, %0"
             : "=r"(msb_on_index) // Outputs.
             : "r"(x-1)           // Inputs.
         );
 #elif (defined(JEMALLOC_HAVE_BUILTIN_CLZ))
     msb_on_index = (31 ^ __builtin_clz(x - 1));
 #endif
     assert(msb_on_index < 31);
     return 1U << (msb_on_index + 1);
 #else
     x--;
     x |= x >> 1;
     x |= x >> 2;
     x |= x >> 4;
     x |= x >> 8;
     x |= x >> 16;
     x++;
     return x;
 #endif
 }
References assert(), unlikely, and G3D::x.
Referenced by pow2_ceil_zu(), and prng_range_u32().
pow2_ceil_u64()
BIT_UTIL_INLINE uint64_t pow2_ceil_u64 (uint64_t x)
Definition at line 84 of file bit_util.h.
{
 #if (defined(__amd64__) || defined(__x86_64__) || defined(JEMALLOC_HAVE_BUILTIN_CLZ))
     if(unlikely(x <= 1)) {
         return x;
     }
     size_t msb_on_index;
 #if (defined(__amd64__) || defined(__x86_64__))
     asm ("bsrq %1, %0"
             : "=r"(msb_on_index) // Outputs.
             : "r"(x-1)           // Inputs.
         );
 #elif (defined(JEMALLOC_HAVE_BUILTIN_CLZ))
     msb_on_index = (63 ^ __builtin_clzll(x - 1));
 #endif
     assert(msb_on_index < 63);
     return 1ULL << (msb_on_index + 1);
 #else
     x--;
     x |= x >> 1;
     x |= x >> 2;
     x |= x >> 4;
     x |= x >> 8;
     x |= x >> 16;
     x |= x >> 32;
     x++;
     return x;
 #endif
 }
References assert(), unlikely, and G3D::x.
Referenced by pow2_ceil_zu(), prng_range_u64(), and prng_range_zu().
pow2_ceil_zu()
BIT_UTIL_INLINE size_t pow2_ceil_zu (size_t x)
Definition at line 144 of file bit_util.h.
{
 #if (LG_SIZEOF_PTR == 3)
     return pow2_ceil_u64(x);
 #else
     return pow2_ceil_u32(x);
 #endif
 }
References pow2_ceil_u32(), pow2_ceil_u64(), and G3D::x.
Referenced by sz_s2u_compute(), and sz_size2index_compute().