Azerotcore-wotlk: src/server/game/Entities/Object/ObjectGuid.cpp File Reference
ObjectGuid.cpp File Reference
#include "ObjectGuid.h"
#include "Log.h"
#include "World.h"
#include <sstream>
#include <iomanip>
Macros
#define GUID_TRAIT_INSTANTIATE_GUID(HIGH_GUID) template class ObjectGuidGenerator< HIGH_GUID >;
Functions
ByteBuffer & operator<< (ByteBuffer &buf, ObjectGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, ObjectGuid &guid)
ByteBuffer & operator<< (ByteBuffer &buf, PackedGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, PackedGuidReader const &guid)
Macro Definition Documentation
GUID_TRAIT_INSTANTIATE_GUID
#define GUID_TRAIT_INSTANTIATE_GUID (HIGH_GUID) template class ObjectGuidGenerator< HIGH_GUID >;
Definition at line 99 of file ObjectGuid.cpp.
Function Documentation
operator<<() [1/2]
ByteBuffer& operator<< (ByteBuffer & buf, ObjectGuid const & guid)
Definition at line 69 of file ObjectGuid.cpp.
 {
     buf << uint64(guid.GetRawValue());
     return buf;
 }
References ObjectGuid::GetRawValue().
operator<<() [2/2]
ByteBuffer& operator<< (ByteBuffer & buf, PackedGuid const & guid)
Definition at line 81 of file ObjectGuid.cpp.
 {
     buf.append(guid._packedGuid);
     return buf;
 }
operator>>() [1/2]
ByteBuffer& operator>> (ByteBuffer & buf, ObjectGuid & guid)
Definition at line 75 of file ObjectGuid.cpp.
 {
     guid.Set(buf.read<uint64>());
     return buf;
 }
References ByteBuffer::read(), and ObjectGuid::Set().
operator>>() [2/2]
ByteBuffer& operator>> (ByteBuffer & buf, PackedGuidReader const & guid)
Definition at line 87 of file ObjectGuid.cpp.
 {
     buf.readPackGUID(reinterpret_cast<uint64&>(guid.Guid));
     return buf;
 }
References PackedGuidReader::Guid, and ByteBuffer::readPackGUID().