Azerotcore-wotlk: Thread Instrumentation
Thread Instrumentation
Instrumentation Interface
Classes
struct st_mysql_mutex
struct st_mysql_rwlock
struct st_mysql_prlock
struct st_mysql_cond
Macros
#define mysql_mutex_assert_owner(M) safe_mutex_assert_owner(&(M)->m_mutex)
#define mysql_mutex_assert_not_owner(M) safe_mutex_assert_not_owner(&(M)->m_mutex)
#define mysql_prlock_assert_write_owner(M) rw_pr_lock_assert_write_owner(&(M)->m_prlock)
#define mysql_prlock_assert_not_write_owner(M) rw_pr_lock_assert_not_write_owner(&(M)->m_prlock)
#define mysql_mutex_init(K, M, A) inline_mysql_mutex_init(M, A)
#define mysql_mutex_destroy(M) inline_mysql_mutex_destroy(M)
#define mysql_mutex_lock(M) inline_mysql_mutex_lock(M)
#define mysql_mutex_trylock(M) inline_mysql_mutex_trylock(M)
#define mysql_mutex_unlock(M) inline_mysql_mutex_unlock(M)
#define mysql_rwlock_init(K, RW) inline_mysql_rwlock_init(RW)
#define mysql_prlock_init(K, RW) inline_mysql_prlock_init(RW)
#define mysql_rwlock_destroy(RW) inline_mysql_rwlock_destroy(RW)
#define mysql_prlock_destroy(RW) inline_mysql_prlock_destroy(RW)
#define mysql_rwlock_rdlock(RW) inline_mysql_rwlock_rdlock(RW)
#define mysql_prlock_rdlock(RW) inline_mysql_prlock_rdlock(RW)
#define mysql_rwlock_wrlock(RW) inline_mysql_rwlock_wrlock(RW)
#define mysql_prlock_wrlock(RW) inline_mysql_prlock_wrlock(RW)
#define mysql_rwlock_tryrdlock(RW) inline_mysql_rwlock_tryrdlock(RW)
#define mysql_rwlock_trywrlock(RW) inline_mysql_rwlock_trywrlock(RW)
#define mysql_rwlock_unlock(RW) inline_mysql_rwlock_unlock(RW)
#define mysql_prlock_unlock(RW) inline_mysql_prlock_unlock(RW)
#define mysql_cond_init(K, C, A) inline_mysql_cond_init(C, A)
#define mysql_cond_destroy(C) inline_mysql_cond_destroy(C)
#define mysql_cond_wait(C, M) inline_mysql_cond_wait(C, M)
#define mysql_cond_timedwait(C, M, W) inline_mysql_cond_timedwait(C, M, W)
#define mysql_cond_signal(C) inline_mysql_cond_signal(C)
#define mysql_cond_broadcast(C) inline_mysql_cond_broadcast(C)
#define mysql_thread_create(K, P1, P2, P3, P4) pthread_create(P1, P2, P3, P4)
#define mysql_thread_set_psi_id(I) do {} while (0)
Typedefs
typedef struct st_mysql_mutex mysql_mutex_t
typedef struct st_mysql_rwlock mysql_rwlock_t
typedef struct st_mysql_prlock mysql_prlock_t
typedef struct st_mysql_cond mysql_cond_t
Functions
static int inline_mysql_mutex_init (mysql_mutex_t *that, const pthread_mutexattr_t *attr)
static int inline_mysql_mutex_destroy (mysql_mutex_t *that)
static int inline_mysql_mutex_lock (mysql_mutex_t *that)
static int inline_mysql_mutex_trylock (mysql_mutex_t *that)
static int inline_mysql_mutex_unlock (mysql_mutex_t *that)
static int inline_mysql_rwlock_init (mysql_rwlock_t *that)
static int inline_mysql_prlock_init (mysql_prlock_t *that)
static int inline_mysql_rwlock_destroy (mysql_rwlock_t *that)
static int inline_mysql_prlock_destroy (mysql_prlock_t *that)
static int inline_mysql_rwlock_rdlock (mysql_rwlock_t *that)
static int inline_mysql_prlock_rdlock (mysql_prlock_t *that)
static int inline_mysql_rwlock_wrlock (mysql_rwlock_t *that)
static int inline_mysql_prlock_wrlock (mysql_prlock_t *that)
static int inline_mysql_rwlock_tryrdlock (mysql_rwlock_t *that)
static int inline_mysql_rwlock_trywrlock (mysql_rwlock_t *that)
static int inline_mysql_rwlock_unlock (mysql_rwlock_t *that)
static int inline_mysql_prlock_unlock (mysql_prlock_t *that)
static int inline_mysql_cond_init (mysql_cond_t *that, const pthread_condattr_t *attr)
static int inline_mysql_cond_destroy (mysql_cond_t *that)
static int inline_mysql_cond_wait (mysql_cond_t *that, mysql_mutex_t *mutex)
static int inline_mysql_cond_timedwait (mysql_cond_t *that, mysql_mutex_t *mutex, struct timespec *abstime)
static int inline_mysql_cond_signal (mysql_cond_t *that)
static int inline_mysql_cond_broadcast (mysql_cond_t *that)
Detailed Description
Macro Definition Documentation
mysql_cond_broadcast
#define mysql_cond_broadcast (C) inline_mysql_cond_broadcast(C)
Instrumented cond_broadcast. mysql_cond_broadcast is a drop-in replacement for pthread_cond_broadcast.
Definition at line 512 of file mysql_thread.h.
mysql_cond_destroy
#define mysql_cond_destroy (C) inline_mysql_cond_destroy(C)
Instrumented cond_destroy. mysql_cond_destroy is a drop-in replacement for pthread_cond_destroy.
Definition at line 470 of file mysql_thread.h.
mysql_cond_init
#define mysql_cond_init (K, C, A) inline_mysql_cond_init(C, A)
Instrumented cond_init. mysql_cond_init is a replacement for pthread_cond_init.
Parameters
C The cond to initialize
K The PSI_cond_key for this instrumented cond
A Condition attributes
Definition at line 462 of file mysql_thread.h.
mysql_cond_signal
#define mysql_cond_signal (C) inline_mysql_cond_signal(C)
Instrumented cond_signal. mysql_cond_signal is a drop-in replacement for pthread_cond_signal.
Definition at line 504 of file mysql_thread.h.
mysql_cond_timedwait
#define mysql_cond_timedwait (C, M, W) inline_mysql_cond_timedwait(C, M, W)
Instrumented cond_timedwait. mysql_cond_timedwait is a drop-in replacement for pthread_cond_timedwait.
Definition at line 495 of file mysql_thread.h.
mysql_cond_wait
#define mysql_cond_wait (C, M) inline_mysql_cond_wait(C, M)
Instrumented cond_wait. mysql_cond_wait is a drop-in replacement for pthread_cond_wait.
Definition at line 481 of file mysql_thread.h.
mysql_mutex_assert_not_owner
#define mysql_mutex_assert_not_owner (M) safe_mutex_assert_not_owner(&(M)->m_mutex)
Wrapper, to use safe_mutex_assert_not_owner with instrumented mutexes. mysql_mutex_assert_not_owner is a drop-in replacement for safe_mutex_assert_not_owner.
Definition at line 213 of file mysql_thread.h.
mysql_mutex_assert_owner
#define mysql_mutex_assert_owner (M) safe_mutex_assert_owner(&(M)->m_mutex)
Wrapper, to use safe_mutex_assert_owner with instrumented mutexes. mysql_mutex_assert_owner is a drop-in replacement for safe_mutex_assert_owner.
Definition at line 204 of file mysql_thread.h.
mysql_mutex_destroy
#define mysql_mutex_destroy (M) inline_mysql_mutex_destroy(M)
Instrumented mutex_destroy. mysql_mutex_destroy is a drop-in replacement for pthread_mutex_destroy.
Definition at line 261 of file mysql_thread.h.
mysql_mutex_init
#define mysql_mutex_init (K, M, A) inline_mysql_mutex_init(M, A)
Instrumented mutex_init. mysql_mutex_init is a replacement for pthread_mutex_init.
Parameters
K The PSI_mutex_key for this instrumented mutex
M The mutex to initialize
A Mutex attributes
Definition at line 246 of file mysql_thread.h.
mysql_mutex_lock
#define mysql_mutex_lock (M) inline_mysql_mutex_lock(M)
Instrumented mutex_lock. mysql_mutex_lock is a drop-in replacement for pthread_mutex_lock.
Parameters
M The mutex to lock
Definition at line 276 of file mysql_thread.h.
mysql_mutex_trylock
#define mysql_mutex_trylock (M) inline_mysql_mutex_trylock(M)
Instrumented mutex_lock. mysql_mutex_trylock is a drop-in replacement for pthread_mutex_trylock.
Definition at line 291 of file mysql_thread.h.
mysql_mutex_unlock
#define mysql_mutex_unlock (M) inline_mysql_mutex_unlock(M)
Instrumented mutex_unlock. mysql_mutex_unlock is a drop-in replacement for pthread_mutex_unlock.
Definition at line 304 of file mysql_thread.h.
mysql_prlock_assert_not_write_owner
#define mysql_prlock_assert_not_write_owner (M) rw_pr_lock_assert_not_write_owner(&(M)->m_prlock)
Definition at line 221 of file mysql_thread.h.
mysql_prlock_assert_write_owner
#define mysql_prlock_assert_write_owner (M) rw_pr_lock_assert_write_owner(&(M)->m_prlock)
Wrappers for instrumented prlock objects.
Definition at line 218 of file mysql_thread.h.
mysql_prlock_destroy
#define mysql_prlock_destroy (RW) inline_mysql_prlock_destroy(RW)
Instrumented rw_pr_destroy. mysql_prlock_destroy is a drop-in replacement for rw_pr_destroy.
Definition at line 349 of file mysql_thread.h.
mysql_prlock_init
#define mysql_prlock_init (K, RW) inline_mysql_prlock_init(RW)
Instrumented rw_pr_init. mysql_prlock_init is a replacement for rw_pr_init.
Parameters
K The PSI_rwlock_key for this instrumented prlock
RW The prlock to initialize
Definition at line 332 of file mysql_thread.h.
mysql_prlock_rdlock
#define mysql_prlock_rdlock (RW) inline_mysql_prlock_rdlock(RW)
Instrumented rw_pr_rdlock. mysql_prlock_rdlock is a drop-in replacement for rw_pr_rdlock.
Definition at line 375 of file mysql_thread.h.
mysql_prlock_unlock
#define mysql_prlock_unlock (RW) inline_mysql_prlock_unlock(RW)
Instrumented rw_pr_unlock. mysql_prlock_unlock is a drop-in replacement for rw_pr_unlock.
Definition at line 449 of file mysql_thread.h.
mysql_prlock_wrlock
#define mysql_prlock_wrlock (RW) inline_mysql_prlock_wrlock(RW)
Instrumented rw_pr_wrlock. mysql_prlock_wrlock is a drop-in replacement for rw_pr_wrlock.
Definition at line 403 of file mysql_thread.h.
mysql_rwlock_destroy
#define mysql_rwlock_destroy (RW) inline_mysql_rwlock_destroy(RW)
Instrumented rwlock_destroy. mysql_rwlock_destroy is a drop-in replacement for pthread_rwlock_destroy.
Definition at line 341 of file mysql_thread.h.
mysql_rwlock_init
#define mysql_rwlock_init (K, RW) inline_mysql_rwlock_init(RW)
Instrumented rwlock_init. mysql_rwlock_init is a replacement for pthread_rwlock_init. Note that pthread_rwlockattr_t is not supported in MySQL.
Parameters
K The PSI_rwlock_key for this instrumented rwlock
RW The rwlock to initialize
Definition at line 319 of file mysql_thread.h.
mysql_rwlock_rdlock
#define mysql_rwlock_rdlock (RW) inline_mysql_rwlock_rdlock(RW)
Instrumented rwlock_rdlock. mysql_rwlock_rdlock is a drop-in replacement for pthread_rwlock_rdlock.
Definition at line 361 of file mysql_thread.h.
mysql_rwlock_tryrdlock
#define mysql_rwlock_tryrdlock (RW) inline_mysql_rwlock_tryrdlock(RW)
Instrumented rwlock_tryrdlock. mysql_rwlock_tryrdlock is a drop-in replacement for pthread_rwlock_tryrdlock.
Definition at line 417 of file mysql_thread.h.
mysql_rwlock_trywrlock
#define mysql_rwlock_trywrlock (RW) inline_mysql_rwlock_trywrlock(RW)
Instrumented rwlock_trywrlock. mysql_rwlock_trywrlock is a drop-in replacement for pthread_rwlock_trywrlock.
Definition at line 431 of file mysql_thread.h.
mysql_rwlock_unlock
#define mysql_rwlock_unlock (RW) inline_mysql_rwlock_unlock(RW)
Instrumented rwlock_unlock. mysql_rwlock_unlock is a drop-in replacement for pthread_rwlock_unlock.
Definition at line 441 of file mysql_thread.h.
mysql_rwlock_wrlock
#define mysql_rwlock_wrlock (RW) inline_mysql_rwlock_wrlock(RW)
Instrumented rwlock_wrlock. mysql_rwlock_wrlock is a drop-in replacement for pthread_rwlock_wrlock.
Definition at line 389 of file mysql_thread.h.
mysql_thread_create
#define mysql_thread_create (K, P1, P2, P3, P4) pthread_create(P1, P2, P3, P4)
Instrumented pthread_create. This function creates both the thread instrumentation and a thread. mysql_thread_create is a replacement for pthread_create. The parameter P4 (or, if it is NULL, P1) will be used as the instrumented thread "indentity". Providing a P1 / P4 parameter with a different value for each call will on average improve performances, since this thread identity value is used internally to randomize access to data and prevent contention. This is optional, and the improvement is not guaranteed, only statistical.
Parameters
K The PSI_thread_key for this instrumented thread
P1 pthread_create parameter 1
P2 pthread_create parameter 2
P3 pthread_create parameter 3
P4 pthread_create parameter 4
Definition at line 536 of file mysql_thread.h.
mysql_thread_set_psi_id
#define mysql_thread_set_psi_id (I) do {} while (0)
Set the thread indentifier for the instrumentation.
Parameters
I The thread identifier
Definition at line 548 of file mysql_thread.h.
Typedef Documentation
mysql_cond_t
typedef struct st_mysql_cond mysql_cond_t
Type of an instrumented condition. mysql_cond_t is a drop-in replacement for pthread_cond_t.
See also
mysql_cond_init
mysql_cond_wait
mysql_cond_timedwait
mysql_cond_signal
mysql_cond_broadcast
mysql_cond_destroy
Definition at line 1 of file mysql_thread.h.
mysql_mutex_t
typedef struct st_mysql_mutex mysql_mutex_t
Type of an instrumented mutex. mysql_mutex_t is a drop-in replacement for pthread_mutex_t.
See also
mysql_mutex_assert_owner
mysql_mutex_assert_not_owner
mysql_mutex_init
mysql_mutex_lock
mysql_mutex_unlock
mysql_mutex_destroy
Definition at line 1 of file mysql_thread.h.
mysql_prlock_t
typedef struct st_mysql_prlock mysql_prlock_t
Type of an instrumented prlock. A prlock is a read write lock that 'prefers readers' (pr). mysql_prlock_t is a drop-in replacement for rw_pr_lock_t.
See also
mysql_prlock_init
mysql_prlock_rdlock
mysql_prlock_wrlock
mysql_prlock_unlock
mysql_prlock_destroy
Definition at line 1 of file mysql_thread.h.
mysql_rwlock_t
typedef struct st_mysql_rwlock mysql_rwlock_t
Type of an instrumented rwlock. mysql_rwlock_t is a drop-in replacement for pthread_rwlock_t.
See also
mysql_rwlock_init
mysql_rwlock_rdlock
mysql_rwlock_tryrdlock
mysql_rwlock_wrlock
mysql_rwlock_trywrlock
mysql_rwlock_unlock
mysql_rwlock_destroy
Definition at line 1 of file mysql_thread.h.
Function Documentation
inline_mysql_cond_broadcast()
static int inline_mysql_cond_broadcast (mysql_cond_t * that) inline static
Definition at line 1029 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
     PSI_server->broadcast_cond(that->m_psi);
 #endif
   result= pthread_cond_broadcast(&that->m_cond);
   return result;
 }
References likely, st_mysql_cond::m_cond, st_mysql_cond::m_psi, and PSI_server.
inline_mysql_cond_destroy()
static int inline_mysql_cond_destroy (mysql_cond_t * that) inline static
Definition at line 947 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
   {
     PSI_server->destroy_cond(that->m_psi);
     that->m_psi= NULL;
   }
 #endif
   return pthread_cond_destroy(&that->m_cond);
 }
References likely, st_mysql_cond::m_cond, st_mysql_cond::m_psi, NULL, and PSI_server.
inline_mysql_cond_init()
static int inline_mysql_cond_init (mysql_cond_t * that, const pthread_condattr_t * attr) inline static
Definition at line 931 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   that->m_psi= (PSI_server ? PSI_server->init_cond(key, &that->m_cond)
                            : NULL);
 #else
   that->m_psi= NULL;
 #endif
   return pthread_cond_init(&that->m_cond, attr);
 }
References NULL, and PSI_server.
inline_mysql_cond_signal()
static int inline_mysql_cond_signal (mysql_cond_t * that) inline static
Definition at line 1017 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
     PSI_server->signal_cond(that->m_psi);
 #endif
   result= pthread_cond_signal(&that->m_cond);
   return result;
 }
References likely, st_mysql_cond::m_cond, st_mysql_cond::m_psi, and PSI_server.
inline_mysql_cond_timedwait()
static int inline_mysql_cond_timedwait (mysql_cond_t * that, mysql_mutex_t * mutex, struct timespec * abstime) inline static
Definition at line 988 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_cond_locker *locker= NULL;
   PSI_cond_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_cond_locker(&state, that->m_psi, mutex->m_psi,
                                                PSI_COND_TIMEDWAIT);
     if (likely(locker != NULL))
       PSI_server->start_cond_wait(locker, src_file, src_line);
   }
 #endif
   result= pthread_cond_timedwait(&that->m_cond, &mutex->m_mutex, abstime);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_cond_wait(locker, result);
 #endif
   return result;
 }
References likely, st_mysql_cond::m_cond, st_mysql_mutex::m_mutex, st_mysql_mutex::m_psi, st_mysql_cond::m_psi, NULL, and PSI_server.
inline_mysql_cond_wait()
static int inline_mysql_cond_wait (mysql_cond_t * that, mysql_mutex_t * mutex) inline static
Definition at line 960 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_cond_locker *locker= NULL;
   PSI_cond_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_cond_locker(&state, that->m_psi, mutex->m_psi,
                                                PSI_COND_WAIT);
     if (likely(locker != NULL))
       PSI_server->start_cond_wait(locker, src_file, src_line);
   }
 #endif
   result= pthread_cond_wait(&that->m_cond, &mutex->m_mutex);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_cond_wait(locker, result);
 #endif
   return result;
 }
References likely, st_mysql_cond::m_cond, st_mysql_cond::m_psi, NULL, and PSI_server.
inline_mysql_mutex_destroy()
static int inline_mysql_mutex_destroy (mysql_mutex_t * that) inline static
Definition at line 575 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
   {
     PSI_server->destroy_mutex(that->m_psi);
     that->m_psi= NULL;
   }
 #endif
 #ifdef SAFE_MUTEX
   return safe_mutex_destroy(&that->m_mutex, src_file, src_line);
 #else
   return pthread_mutex_destroy(&that->m_mutex);
 #endif
 }
References likely, NULL, PSI_server, and safe_mutex_destroy().
inline_mysql_mutex_init()
static int inline_mysql_mutex_init (mysql_mutex_t * that, const pthread_mutexattr_t * attr) inline static
Definition at line 551 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   that->m_psi= PSI_server ? PSI_server->init_mutex(key, &that->m_mutex)
                           : NULL;
 #else
   that->m_psi= NULL;
 #endif
 #ifdef SAFE_MUTEX
   return safe_mutex_init(&that->m_mutex, attr, src_file, src_line);
 #else
   return pthread_mutex_init(&that->m_mutex, attr);
 #endif
 }
References NULL, PSI_server, and safe_mutex_init().
inline_mysql_mutex_lock()
static int inline_mysql_mutex_lock (mysql_mutex_t * that) inline static
Definition at line 596 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_mutex_locker *locker= NULL;
   PSI_mutex_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_mutex_locker(&state, that->m_psi, PSI_MUTEX_LOCK);
     if (likely(locker != NULL))
       PSI_server->start_mutex_wait(locker, src_file, src_line);
   }
 #endif
 #ifdef SAFE_MUTEX
   result= safe_mutex_lock(&that->m_mutex, FALSE, src_file, src_line);
 #else
   result= pthread_mutex_lock(&that->m_mutex);
 #endif
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_mutex_wait(locker, result);
 #endif
   return result;
 }
References FALSE, likely, NULL, PSI_server, and safe_mutex_lock().
inline_mysql_mutex_trylock()
static int inline_mysql_mutex_trylock (mysql_mutex_t * that) inline static
Definition at line 626 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_mutex_locker *locker= NULL;
   PSI_mutex_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_mutex_locker(&state, that->m_psi, PSI_MUTEX_TRYLOCK);
     if (likely(locker != NULL))
       PSI_server->start_mutex_wait(locker, src_file, src_line);
   }
 #endif
 #ifdef SAFE_MUTEX
   result= safe_mutex_lock(&that->m_mutex, TRUE, src_file, src_line);
 #else
   result= pthread_mutex_trylock(&that->m_mutex);
 #endif
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_mutex_wait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, safe_mutex_lock(), and TRUE.
inline_mysql_mutex_unlock()
static int inline_mysql_mutex_unlock (mysql_mutex_t * that) inline static
Definition at line 656 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
     PSI_server->unlock_mutex(that->m_psi);
 #endif
 #ifdef SAFE_MUTEX
   result= safe_mutex_unlock(&that->m_mutex, src_file, src_line);
 #else
   result= pthread_mutex_unlock(&that->m_mutex);
 #endif
   return result;
 }
References likely, PSI_server, and safe_mutex_unlock().
inline_mysql_prlock_destroy()
static int inline_mysql_prlock_destroy (mysql_prlock_t * that) inline static
Definition at line 725 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
   {
     PSI_server->destroy_rwlock(that->m_psi);
     that->m_psi= NULL;
   }
 #endif
   return rw_pr_destroy(&that->m_prlock);
 }
References likely, st_mysql_prlock::m_prlock, st_mysql_prlock::m_psi, NULL, PSI_server, and rw_pr_destroy().
inline_mysql_prlock_init()
static int inline_mysql_prlock_init (mysql_prlock_t * that) inline static
Definition at line 695 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   that->m_psi= (PSI_server ? PSI_server->init_rwlock(key, &that->m_prlock)
                            : NULL);
 #else
   that->m_psi= NULL;
 #endif
   return rw_pr_init(&that->m_prlock);
 }
References NULL, PSI_server, and rw_pr_init().
inline_mysql_prlock_rdlock()
static int inline_mysql_prlock_rdlock (mysql_prlock_t * that) inline static
Definition at line 767 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_READLOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_rdwait(locker, src_file, src_line);
   }
 #endif
   result= rw_pr_rdlock(&that->m_prlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_rdwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_pr_rdlock().
inline_mysql_prlock_unlock()
static int inline_mysql_prlock_unlock (mysql_prlock_t * that) inline static
Definition at line 918 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
     PSI_server->unlock_rwlock(that->m_psi);
 #endif
   result= rw_pr_unlock(&that->m_prlock);
   return result;
 }
References likely, st_mysql_prlock::m_prlock, st_mysql_prlock::m_psi, PSI_server, and rw_pr_unlock().
inline_mysql_prlock_wrlock()
static int inline_mysql_prlock_wrlock (mysql_prlock_t * that) inline static
Definition at line 823 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_WRITELOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_wrwait(locker, src_file, src_line);
   }
 #endif
   result= rw_pr_wrlock(&that->m_prlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_wrwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_pr_wrlock().
inline_mysql_rwlock_destroy()
static int inline_mysql_rwlock_destroy (mysql_rwlock_t * that) inline static
Definition at line 711 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
   {
     PSI_server->destroy_rwlock(that->m_psi);
     that->m_psi= NULL;
   }
 #endif
   return rwlock_destroy(&that->m_rwlock);
 }
References likely, st_mysql_rwlock::m_psi, st_mysql_rwlock::m_rwlock, NULL, PSI_server, and rwlock_destroy.
inline_mysql_rwlock_init()
static int inline_mysql_rwlock_init (mysql_rwlock_t * that) inline static
Definition at line 676 of file mysql_thread.h.
 {
 #ifdef HAVE_PSI_INTERFACE
   that->m_psi= (PSI_server ? PSI_server->init_rwlock(key, &that->m_rwlock)
                            : NULL);
 #else
   that->m_psi= NULL;
 #endif
   /*
     pthread_rwlockattr_t is not used in MySQL.
   */
   return my_rwlock_init(&that->m_rwlock, NULL);
 }
References my_rwlock_init, NULL, and PSI_server.
inline_mysql_rwlock_rdlock()
static int inline_mysql_rwlock_rdlock (mysql_rwlock_t * that) inline static
Definition at line 739 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_READLOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_rdwait(locker, src_file, src_line);
   }
 #endif
   result= rw_rdlock(&that->m_rwlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_rdwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_rdlock.
inline_mysql_rwlock_tryrdlock()
static int inline_mysql_rwlock_tryrdlock (mysql_rwlock_t * that) inline static
Definition at line 851 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_TRYREADLOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_rdwait(locker, src_file, src_line);
   }
 #endif
   result= rw_tryrdlock(&that->m_rwlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_rdwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_tryrdlock.
inline_mysql_rwlock_trywrlock()
static int inline_mysql_rwlock_trywrlock (mysql_rwlock_t * that) inline static
Definition at line 878 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_TRYWRITELOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_wrwait(locker, src_file, src_line);
   }
 #endif
   result= rw_trywrlock(&that->m_rwlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_wrwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_trywrlock.
inline_mysql_rwlock_unlock()
static int inline_mysql_rwlock_unlock (mysql_rwlock_t * that) inline static
Definition at line 905 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   if (likely(PSI_server && that->m_psi))
     PSI_server->unlock_rwlock(that->m_psi);
 #endif
   result= rw_unlock(&that->m_rwlock);
   return result;
 }
References likely, st_mysql_rwlock::m_psi, st_mysql_rwlock::m_rwlock, PSI_server, and rw_unlock.
inline_mysql_rwlock_wrlock()
static int inline_mysql_rwlock_wrlock (mysql_rwlock_t * that) inline static
Definition at line 795 of file mysql_thread.h.
 {
   int result;
 #ifdef HAVE_PSI_INTERFACE
   struct PSI_rwlock_locker *locker= NULL;
   PSI_rwlock_locker_state state;
   if (likely(PSI_server && that->m_psi))
   {
     locker= PSI_server->get_thread_rwlock_locker(&state, that->m_psi,
                                                  PSI_RWLOCK_WRITELOCK);
     if (likely(locker != NULL))
       PSI_server->start_rwlock_wrwait(locker, src_file, src_line);
   }
 #endif
   result= rw_wrlock(&that->m_rwlock);
 #ifdef HAVE_PSI_INTERFACE
   if (likely(locker != NULL))
     PSI_server->end_rwlock_wrwait(locker, result);
 #endif
   return result;
 }
References likely, NULL, PSI_server, and rw_wrlock.