Azerotcore-wotlk: Acore::Containers Namespace Reference
Acore::Containers Namespace Reference
Functions
template<class C >
void RandomResize (C &container, std::size_t requestedSize)
template<class C , class Predicate >
void RandomResize (C &container, Predicate &&predicate, std::size_t requestedSize)
template<class C >
auto SelectRandomContainerElement (C const &container) -> typename std::add_const< decltype(*std::begin(container))>::type &
template<class C >
auto SelectRandomWeightedContainerElement (C const &container, std::vector< double > weights) -> decltype(std::begin(container))
template<class C , class Fn >
auto SelectRandomWeightedContainerElement (C const &container, Fn weightExtractor) -> decltype(std::begin(container))
template<class M >
auto MapGetValuePtr (M &map, typename M::key_type const &key) -> decltype(AddressOrSelf(map.find(key) ->second))
template<class C >
void RandomShuffle (C &container)
template<class K , class V , template< class, class, class... > class M, class... Rest>
void MultimapErasePair (M< K, V, Rest... > &multimap, K const &key, V const &value)
template<typename Container , typename Predicate >
std::enable_if_t< std::is_move_assignable_v< decltype(*std::declval< Container >).begin())>, void > EraseIf (Container &c, Predicate p)
template<typename Container , typename Predicate >
std::enable_if_t<!std::is_move_assignable_v< decltype(*std::declval< Container >).begin())>, void > EraseIf (Container &c, Predicate p)
template<class M >
auto MapEqualRange (M &map, typename M::key_type const &key) -> IteratorPair< decltype(map.begin())>
Function Documentation
EraseIf() [1/2]
template<typename Container , typename Predicate > std::enable_if_t<std::is_move_assignable_v<decltype(*std::declval<Container>).begin())>, void> Acore::Containers::EraseIf (Container & c, Predicate p)
Definition at line 230 of file Containers.h.
     {
         auto wpos = c.begin();
         for (auto rpos = c.begin(), end = c.end(); rpos != end; ++rpos)
         {
             if (!p(*rpos))
             {
                 if (rpos != wpos)
                 {
                     std::swap(*rpos, *wpos);
                 }
                 ++wpos;
             }
         }
         c.erase(wpos, c.end());
     }
References mpq::c, and swap().
Referenced by WardenWin::RequestChecks().
EraseIf() [2/2]
template<typename Container , typename Predicate > std::enable_if_t<!std::is_move_assignable_v<decltype(*std::declval<Container>).begin())>, void> Acore::Containers::EraseIf (Container & c, Predicate p)
Definition at line 248 of file Containers.h.
     {
         for (auto it = c.begin(); it != c.end();)
         {
             if (p(*it))
             {
                 it = c.erase(it);
             }
             else
             {
                 ++it;
             }
         }
     }
References mpq::c.
MapEqualRange()
template<class M > auto Acore::Containers::MapEqualRange (M & map, typename M::key_type const & key) -> IteratorPair<decltype(map.begin())> inline
Definition at line 49 of file IteratorPair.h.
         {
             return { map.equal_range(key) };
         }
MapGetValuePtr()
template<class M > auto Acore::Containers::MapGetValuePtr (M & map, typename M::key_type const & key) -> decltype(AddressOrSelf(map.find(key)->second)) inline
Returns a pointer to mapped value (or the value itself if map stores pointers)
Definition at line 193 of file Containers.h.
     {
         auto itr = map.find(key);
         return itr != map.end() ? AddressOrSelf(itr->second) : nullptr;
     }
References Acore::AddressOrSelf().
MultimapErasePair()
template<class K , class V , template< class, class, class... > class M, class... Rest> void Acore::Containers::MultimapErasePair (M< K, V, Rest... > & multimap, K const & key, V const & value)
Definition at line 213 of file Containers.h.
     {
         auto range = multimap.equal_range(key);
         for (auto itr = range.first; itr != range.second;)
         {
             if (itr->second == value)
             {
                 itr = multimap.erase(itr);
             }
             else
             {
                 ++itr;
             }
         }
     }
Referenced by Creature::RemoveFromWorld(), and GameObject::RemoveFromWorld().
RandomResize() [1/2]
template<class C , class Predicate > void Acore::Containers::RandomResize (C & container, Predicate && predicate, std::size_t requestedSize)
First use predicate filter
Definition at line 115 of file Containers.h.
     {
         C containerCopy;
         std::copy_if(std::begin(container), std::end(container), std::inserter(containerCopy, std::end(containerCopy)), predicate);
         if (requestedSize)
         {
             RandomResize(containerCopy, requestedSize);
         }
         container = std::move(containerCopy);
     }
References RandomResize().
RandomResize() [2/2]
template<class C > void Acore::Containers::RandomResize (C & container, std::size_t requestedSize)
Definition at line 81 of file Containers.h.
     {
         static_assert(std::is_base_of<std::forward_iterator_tag, typename std::iterator_traits<typename C::iterator>::iterator_category>::value, "Invalid container passed to Acore::Containers::RandomResize");
         if (std::size(container) <= requestedSize)
         {
             return;
         }
         auto keepIt = std::begin(container), curIt = std::begin(container);
         uint32 elementsToKeep = requestedSize, elementsToProcess = std::size(container);
         while (elementsToProcess)
         {
             // this element has chance (elementsToKeep / elementsToProcess) of being kept
             if (urand(1, elementsToProcess) <= elementsToKeep)
             {
                 if (keepIt != curIt)
                 {
                     *keepIt = std::move(*curIt);
                 }
                 ++keepIt;
                 --elementsToKeep;
             }
             ++curIt;
             --elementsToProcess;
         }
         container.erase(keepIt, std::end(container));
     }
References urand().
Referenced by npc_hallows_end_soh::npc_hallows_end_sohAI::CastFires(), spell_pal_divine_storm_dummy::CountTargets(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::FilterTargets(), spell_kalecgos_spectral_blast_dummy::spell_kalecgos_spectral_blast_dummy_SpellScript::FilterTargets(), spell_entropius_negative_energy::spell_entropius_negative_energy_SpellScript::FilterTargets(), spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::FilterTargets(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::FilterTargets(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::FilterTargets(), spell_hodir_periodic_icicle::spell_hodir_periodic_icicle_SpellScript::FilterTargets(), spell_q24545_aod_special::spell_q24545_aod_special_SpellScript::FilterTargets(), spell_dru_starfall_dummy::FilterTargets(), spell_gen_select_target_count::FilterTargets(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_SpellScript::FilterTargets(), spell_morogrim_tidewalker_water_globule_new_target::spell_morogrim_tidewalker_water_globule_new_target_SpellScript::FilterTargets(), spell_tsh_shoot_flame_arrow::spell_tsh_shoot_flame_arrow_SpellScript::FilterTargets(), SmartScript::GetTargets(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::HandleScriptEffect(), boss_priestess_delrissa::boss_priestess_delrissaAI::InitializeAI(), spell_dreamwalker_summon_suppresser::spell_dreamwalker_summon_suppresser_AuraScript::PeriodicTick(), SmartScript::ProcessAction(), RandomResize(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::RemoveAliveTarget(), Spell::SelectImplicitAreaTargets(), Spell::SelectImplicitConeTargets(), spell_igb_explosion::spell_igb_explosion_SpellScript::SelectTarget(), UnitAI::SelectTargetList(), PoolGroup< T >::SpawnObject(), boss_moam::boss_moamAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), and boss_hodir::boss_hodirAI::UpdateAI().
RandomShuffle()
template<class C > void Acore::Containers::RandomShuffle (C & container) inline
Definition at line 207 of file Containers.h.
     {
         std::shuffle(std::begin(container), std::end(container), RandomEngine::Instance());
     }
References RandomEngine::Instance().
SelectRandomContainerElement()
template<class C > auto Acore::Containers::SelectRandomContainerElement (C const & container) -> typename std::add_const<decltype(*std::begin(container))>::type& inline
Definition at line 135 of file Containers.h.
     {
         auto it = std::begin(container);
         std::advance(it, urand(0, uint32(std::size(container)) - 1));
         return *it;
     }
References utf8::advance(), and urand().
Referenced by lfg::LFGQueue::CheckCompatibility(), spell_dk_corpse_explosion::CheckTargets(), spell_dk_raise_dead::CheckTargets(), Spell::EffectEnergize(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), spell_send_mug_target_picker::spell_send_mug_target_picker_SpellScript::FilterTargets(), spell_deathbringer_boiling_blood::spell_deathbringer_boiling_blood_SpellScript::FilterTargets(), spell_igb_burning_pitch_selector::spell_igb_burning_pitch_selector_SpellScript::FilterTargets(), spell_rotface_mutated_infection::spell_rotface_mutated_infection_SpellScript::FilterTargets(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::FilterTargets(), spell_dreamwalker_summoner::spell_dreamwalker_summoner_SpellScript::FilterTargets(), spell_pursue::spell_pursue_SpellScript::FilterTargets(), boss_moroes::boss_moroesAI::GetRandomGuest(), spell_rog_killing_spree::spell_rog_killing_spree_AuraScript::HandleEffectPeriodic(), spell_frostwarden_handler_order_whelp::spell_frostwarden_handler_order_whelp_SpellScript::HandleForcedCast(), misc_commandscript::HandleSkirmishCommand(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), spell_mistress_kiss_area::spell_mistress_kiss_area_SpellScript::PrepareSpellScript(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), LootTemplate::LootGroup::Roll(), Unit::SelectNearbyNoTotemTarget(), Unit::SelectNearbyTarget(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::SelectRandomPlayer(), spell_igb_rocket_artillery::spell_igb_rocket_artillery_SpellScript::SelectRandomTarget(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::SelectTarget(), npc_minigob_manabonk::npc_minigob_manabonkAI::SelectTargetInDalaran(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetPositionTraps(), PoolGroup< T >::SpawnObject(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), GameObject::Update(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), and npc_phase_hunter::npc_phase_hunterAI::UpdateAI().
SelectRandomWeightedContainerElement() [1/2]
template<class C , class Fn > auto Acore::Containers::SelectRandomWeightedContainerElement (C const & container, Fn weightExtractor) -> decltype(std::begin(container))
Definition at line 168 of file Containers.h.
     {
         std::vector<double> weights;
         weights.reserve(std::size(container));
         double weightSum = 0.0;
         for (auto& val : container)
         {
             double weight = weightExtractor(val);
             weights.push_back(weight);
             weightSum += weight;
         }
         if (weightSum <= 0.0)
         {
             weights.assign(std::size(container), 1.0);
         }
         return SelectRandomWeightedContainerElement(container, weights);
     }
References SelectRandomWeightedContainerElement().
SelectRandomWeightedContainerElement() [2/2]
template<class C > auto Acore::Containers::SelectRandomWeightedContainerElement (C const & container, std::vector< double > weights) -> decltype(std::begin(container)) inline
Definition at line 152 of file Containers.h.
     {
         auto it = std::begin(container);
         std::advance(it, urandweighted(weights.size(), weights.data()));
         return it;
     }
References utf8::advance(), and urandweighted().
Referenced by BattlegroundMgr::GetRandomBG(), and SelectRandomWeightedContainerElement().