Azerotcore-wotlk: deps/mysqllite/strings/xml.c File Reference
xml.c File Reference
#include "my_global.h"
#include "m_string.h"
#include "my_xml.h"
Classes
struct xml_attr_st
Macros
#define MY_XML_UNKNOWN 'U'
#define MY_XML_EOF 'E'
#define MY_XML_STRING 'S'
#define MY_XML_IDENT 'I'
#define MY_XML_EQ '='
#define MY_XML_LT '<'
#define MY_XML_GT '>'
#define MY_XML_SLASH '/'
#define MY_XML_COMMENT 'C'
#define MY_XML_TEXT 'T'
#define MY_XML_QUESTION '?'
#define MY_XML_EXCLAM '!'
#define MY_XML_CDATA 'D'
#define MY_XML_ID0 0x01 /* Identifier initial character */
#define MY_XML_ID1 0x02 /* Identifier medial character */
#define MY_XML_SPC 0x08 /* Spacing character */
#define my_xml_is_space(c) (my_xml_ctype[(uchar) (c)] & MY_XML_SPC)
#define my_xml_is_id0(c) (my_xml_ctype[(uchar) (c)] & MY_XML_ID0)
#define my_xml_is_id1(c) (my_xml_ctype[(uchar) (c)] & MY_XML_ID1)
Typedefs
typedef struct xml_attr_st MY_XML_ATTR
Functions
static const char * lex2str (int lex)
static void my_xml_norm_text (MY_XML_ATTR *a)
static int my_xml_scan (MY_XML_PARSER *p, MY_XML_ATTR *a)
static int my_xml_value (MY_XML_PARSER *st, const char *str, size_t len)
static int my_xml_enter (MY_XML_PARSER *st, const char *str, size_t len)
static void mstr (char *s, const char *src, size_t l1, size_t l2)
static int my_xml_leave (MY_XML_PARSER *p, const char *str, size_t slen)
int my_xml_parse (MY_XML_PARSER *p, const char *str, size_t len)
void my_xml_parser_create (MY_XML_PARSER *p)
void my_xml_parser_free (MY_XML_PARSER *p __attribute__((unused)))
void my_xml_set_value_handler (MY_XML_PARSER *p, int(*action)(MY_XML_PARSER *p, const char *s, size_t l))
void my_xml_set_enter_handler (MY_XML_PARSER *p, int(*action)(MY_XML_PARSER *p, const char *s, size_t l))
void my_xml_set_leave_handler (MY_XML_PARSER *p, int(*action)(MY_XML_PARSER *p, const char *s, size_t l))
void my_xml_set_user_data (MY_XML_PARSER *p, void *user_data)
const char * my_xml_error_string (MY_XML_PARSER *p)
size_t my_xml_error_pos (MY_XML_PARSER *p)
uint my_xml_error_lineno (MY_XML_PARSER *p)
Variables
static char my_xml_ctype [256]
Macro Definition Documentation
MY_XML_CDATA
#define MY_XML_CDATA 'D'
Definition at line 33 of file xml.c.
MY_XML_COMMENT
#define MY_XML_COMMENT 'C'
Definition at line 29 of file xml.c.
MY_XML_EOF
#define MY_XML_EOF 'E'
Definition at line 22 of file xml.c.
MY_XML_EQ
#define MY_XML_EQ '='
Definition at line 25 of file xml.c.
MY_XML_EXCLAM
#define MY_XML_EXCLAM '!'
Definition at line 32 of file xml.c.
MY_XML_GT
#define MY_XML_GT '>'
Definition at line 27 of file xml.c.
MY_XML_ID0
#define MY_XML_ID0 0x01 /* Identifier initial character */
Definition at line 45 of file xml.c.
MY_XML_ID1
#define MY_XML_ID1 0x02 /* Identifier medial character */
Definition at line 46 of file xml.c.
MY_XML_IDENT
#define MY_XML_IDENT 'I'
Definition at line 24 of file xml.c.
my_xml_is_id0
#define my_xml_is_id0 (c) (my_xml_ctype[(uchar) (c)] & MY_XML_ID0)
Definition at line 78 of file xml.c.
my_xml_is_id1
#define my_xml_is_id1 (c) (my_xml_ctype[(uchar) (c)] & MY_XML_ID1)
Definition at line 79 of file xml.c.
my_xml_is_space
#define my_xml_is_space (c) (my_xml_ctype[(uchar) (c)] & MY_XML_SPC)
Definition at line 77 of file xml.c.
MY_XML_LT
#define MY_XML_LT '<'
Definition at line 26 of file xml.c.
MY_XML_QUESTION
#define MY_XML_QUESTION '?'
Definition at line 31 of file xml.c.
MY_XML_SLASH
#define MY_XML_SLASH '/'
Definition at line 28 of file xml.c.
MY_XML_SPC
#define MY_XML_SPC 0x08 /* Spacing character */
Definition at line 47 of file xml.c.
MY_XML_STRING
#define MY_XML_STRING 'S'
Definition at line 23 of file xml.c.
MY_XML_TEXT
#define MY_XML_TEXT 'T'
Definition at line 30 of file xml.c.
MY_XML_UNKNOWN
#define MY_XML_UNKNOWN 'U'
Definition at line 21 of file xml.c.
Typedef Documentation
MY_XML_ATTR
typedef struct xml_attr_st MY_XML_ATTR
Function Documentation
lex2str()
static const char* lex2str (int lex) static
Definition at line 82 of file xml.c.
 {
   switch(lex)
   {
     case MY_XML_EOF:      return "END-OF-INPUT";
     case MY_XML_STRING:   return "STRING";
     case MY_XML_IDENT:    return "IDENT";
     case MY_XML_CDATA:    return "CDATA";
     case MY_XML_EQ:       return "'='";
     case MY_XML_LT:       return "'<'";
     case MY_XML_GT:       return "'>'";
     case MY_XML_SLASH:    return "'/'";
     case MY_XML_COMMENT:  return "COMMENT";
     case MY_XML_TEXT:     return "TEXT";
     case MY_XML_QUESTION: return "'?'";
     case MY_XML_EXCLAM:   return "'!'";
   }
   return "unknown token";
 }
References MY_XML_CDATA, MY_XML_COMMENT, MY_XML_EOF, MY_XML_EQ, MY_XML_EXCLAM, MY_XML_GT, MY_XML_IDENT, MY_XML_LT, MY_XML_QUESTION, MY_XML_SLASH, MY_XML_STRING, and MY_XML_TEXT.
Referenced by my_xml_parse(), and my_xml_scan().
mstr()
static void mstr (char * s, const char * src, size_t l1, size_t l2) static
Definition at line 216 of file xml.c.
 {
   l1 = l1<l2 ? l1 : l2;
   memcpy(s,src,l1);
   s[l1]='\0';
 }
References memcpy.
Referenced by my_xml_leave().
my_xml_enter()
static int my_xml_enter (MY_XML_PARSER * st, const char * str, size_t len) static
Definition at line 194 of file xml.c.
 {
   if ((size_t) (st->attrend-st->attr+len+1) > sizeof(st->attr))
   {
     sprintf(st->errstr,"To deep XML");
     return MY_XML_ERROR;
   }
   if (st->attrend > st->attr)
   {
     st->attrend[0]= '/';
     st->attrend++;
   }
   memcpy(st->attrend,str,len);
   st->attrend+=len;
   st->attrend[0]='\0';
   if (st->flags & MY_XML_FLAG_RELATIVE_NAMES)
     return st->enter ? st->enter(st, str, len) : MY_XML_OK;
   else
     return st->enter ?  st->enter(st,st->attr,st->attrend-st->attr) : MY_XML_OK;
 }
References xml_stack_st::attr, xml_stack_st::attrend, xml_stack_st::enter, xml_stack_st::errstr, xml_stack_st::flags, memcpy, MY_XML_ERROR, MY_XML_FLAG_RELATIVE_NAMES, MY_XML_OK, and sprintf().
Referenced by my_xml_parse().
my_xml_error_lineno()
uint my_xml_error_lineno (MY_XML_PARSER * p)
Definition at line 486 of file xml.c.
 {
   uint res=0;
   const char *s;
   for (s=p->beg ; s<p->cur; s++)
   {
     if (s[0] == '\n')
       res++;
   }
   return res;
 }
References xml_stack_st::beg.
Referenced by my_read_charset_file().
my_xml_error_pos()
size_t my_xml_error_pos (MY_XML_PARSER * p)
Definition at line 474 of file xml.c.
 {
   const char *beg=p->beg;
   const char *s;
   for ( s=p->beg ; s<p->cur; s++)
   {
     if (s[0] == '\n')
       beg=s;
   }
   return (size_t) (p->cur-beg);
 }
References xml_stack_st::beg, and xml_stack_st::cur.
Referenced by my_read_charset_file().
my_xml_error_string()
const char* my_xml_error_string (MY_XML_PARSER * p)
Definition at line 468 of file xml.c.
 {
   return p->errstr;
 }
References xml_stack_st::errstr.
Referenced by my_read_charset_file().
my_xml_leave()
static int my_xml_leave (MY_XML_PARSER * p, const char * str, size_t slen) static
Definition at line 224 of file xml.c.
 {
   char *e;
   size_t glen;
   char s[32];
   char g[32];
   int  rc;
   /* Find previous '/' or beginning */
   for (e=p->attrend; (e>p->attr) && (e[0] != '/') ; e--);
   glen = (size_t) ((e[0] == '/') ? (p->attrend-e-1) : p->attrend-e);
   if (str && (slen != glen))
   {
     mstr(s,str,sizeof(s)-1,slen);
     if (glen)
     {
       mstr(g,e+1,sizeof(g)-1,glen),
       sprintf(p->errstr,"'</%s>' unexpected ('</%s>' wanted)",s,g);
     }
     else
       sprintf(p->errstr,"'</%s>' unexpected (END-OF-INPUT wanted)", s);
     return MY_XML_ERROR;
   }
   if (p->flags & MY_XML_FLAG_RELATIVE_NAMES)
     rc= p->leave_xml ? p->leave_xml(p, str, slen) : MY_XML_OK;
   else
     rc= (p->leave_xml ?  p->leave_xml(p,p->attr,p->attrend-p->attr) :
          MY_XML_OK);
   *e='\0';
   p->attrend=e;
   return rc;
 }
References xml_stack_st::attr, xml_stack_st::attrend, xml_stack_st::errstr, xml_stack_st::flags, xml_stack_st::leave_xml, mstr(), MY_XML_ERROR, MY_XML_FLAG_RELATIVE_NAMES, MY_XML_OK, and sprintf().
Referenced by my_xml_parse().
my_xml_norm_text()
static void my_xml_norm_text (MY_XML_ATTR * a) static
Definition at line 102 of file xml.c.
 {
   for ( ; (a->beg < a->end) && my_xml_is_space(a->beg[0]) ; a->beg++ );
   for ( ; (a->beg < a->end) && my_xml_is_space(a->end[-1]) ; a->end-- );
 }
References mpq::a, and my_xml_is_space.
Referenced by my_xml_parse(), and my_xml_scan().
my_xml_parse()
int my_xml_parse (MY_XML_PARSER * p, const char * str, size_t len)
Definition at line 262 of file xml.c.
 {
   p->attrend=p->attr;
   p->beg=str;
   p->cur=str;
   p->end=str+len;
   while ( p->cur < p->end )
   {
     MY_XML_ATTR a;
     if (p->cur[0] == '<')
     {
       int lex;
       int question=0;
       int exclam=0;
       lex=my_xml_scan(p,&a);
       if (MY_XML_COMMENT == lex)
         continue;
       if (lex == MY_XML_CDATA)
       {
         a.beg+= 9;
         a.end-= 3;
         my_xml_value(p, a.beg, (size_t) (a.end-a.beg));
         continue;
       }
       lex=my_xml_scan(p,&a);
       if (MY_XML_SLASH == lex)
       {
         if (MY_XML_IDENT != (lex=my_xml_scan(p,&a)))
         {
           sprintf(p->errstr,"%s unexpected (ident wanted)",lex2str(lex));
           return MY_XML_ERROR;
         }
         if (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg)))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
         goto gt;
       }
       if (MY_XML_EXCLAM == lex)
       {
         lex=my_xml_scan(p,&a);
         exclam=1;
       }
       else if (MY_XML_QUESTION == lex)
       {
         lex=my_xml_scan(p,&a);
         question=1;
       }
       if (MY_XML_IDENT == lex)
       {
         p->current_node_type= MY_XML_NODE_TAG;
         if (MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg)))
           return MY_XML_ERROR;
       }
       else
       {
         sprintf(p->errstr,"%s unexpected (ident or '/' wanted)",
         lex2str(lex));
         return MY_XML_ERROR;
       }
       while ((MY_XML_IDENT == (lex=my_xml_scan(p,&a))) ||
              ((MY_XML_STRING == lex && exclam)))
       {
         MY_XML_ATTR b;
         if (MY_XML_EQ == (lex=my_xml_scan(p,&b)))
         {
           lex=my_xml_scan(p,&b);
           if ( (lex == MY_XML_IDENT) || (lex == MY_XML_STRING) )
           {
             p->current_node_type= MY_XML_NODE_ATTR;
             if ((MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg)))  ||
                 (MY_XML_OK != my_xml_value(p,b.beg,(size_t) (b.end-b.beg)))  ||
                 (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg))))
               return MY_XML_ERROR;
           }
           else
           {
             sprintf(p->errstr,"%s unexpected (ident or string wanted)",
             lex2str(lex));
             return MY_XML_ERROR;
           }
         }
         else if (MY_XML_IDENT == lex)
         {
           p->current_node_type= MY_XML_NODE_ATTR;
           if ((MY_XML_OK != my_xml_enter(p,a.beg,(size_t) (a.end-a.beg))) ||
               (MY_XML_OK != my_xml_leave(p,a.beg,(size_t) (a.end-a.beg))))
            return MY_XML_ERROR;
         }
         else if ((MY_XML_STRING == lex) && exclam)
         {
           /*
             We are in <!DOCTYPE>, e.g.
             <!DOCTYPE name SYSTEM "SystemLiteral">
             <!DOCTYPE name PUBLIC "PublidLiteral" "SystemLiteral">
             Just skip "SystemLiteral" and "PublicidLiteral"
           */
         }
         else
           break;
       }
       if (lex == MY_XML_SLASH)
       {
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
       }
 gt:
       if (question)
       {
         if (lex != MY_XML_QUESTION)
         {
           sprintf(p->errstr,"%s unexpected ('?' wanted)",lex2str(lex));
           return MY_XML_ERROR;
         }
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
         lex=my_xml_scan(p,&a);
       }
       if (exclam)
       {
         if (MY_XML_OK != my_xml_leave(p,NULL,0))
           return MY_XML_ERROR;
       }
       if (lex != MY_XML_GT)
       {
         sprintf(p->errstr,"%s unexpected ('>' wanted)",lex2str(lex));
         return MY_XML_ERROR;
       }
     }
     else
     {
       a.beg=p->cur;
       for ( ; (p->cur < p->end) && (p->cur[0] != '<')  ; p->cur++);
       a.end=p->cur;
       if (!(p->flags & MY_XML_FLAG_SKIP_TEXT_NORMALIZATION))
         my_xml_norm_text(&a);
       if (a.beg != a.end)
       {
         my_xml_value(p,a.beg,(size_t) (a.end-a.beg));
       }
     }
   }
   if (p->attr[0])
   {
     sprintf(p->errstr,"unexpected END-OF-INPUT");
     return MY_XML_ERROR;
   }
   return MY_XML_OK;
 }
References mpq::a, xml_stack_st::attr, xml_stack_st::attrend, b, xml_stack_st::beg, xml_stack_st::cur, xml_stack_st::current_node_type, xml_stack_st::end, xml_stack_st::errstr, xml_stack_st::flags, lex2str(), MY_XML_CDATA, MY_XML_COMMENT, my_xml_enter(), MY_XML_EQ, MY_XML_ERROR, MY_XML_EXCLAM, MY_XML_FLAG_SKIP_TEXT_NORMALIZATION, MY_XML_GT, MY_XML_IDENT, my_xml_leave(), MY_XML_NODE_ATTR, MY_XML_NODE_TAG, my_xml_norm_text(), MY_XML_OK, MY_XML_QUESTION, my_xml_scan(), MY_XML_SLASH, MY_XML_STRING, my_xml_value(), NULL, and sprintf().
Referenced by my_parse_charset_xml().
my_xml_parser_create()
void my_xml_parser_create (MY_XML_PARSER * p)
Definition at line 428 of file xml.c.
 {
   bzero((void*)p,sizeof(p[0]));
 }
References bzero.
Referenced by my_parse_charset_xml().
my_xml_parser_free()
void my_xml_parser_free (MY_XML_PARSER *p __attribute__(unused))
Definition at line 434 of file xml.c.
 {
 }
my_xml_scan()
static int my_xml_scan (MY_XML_PARSER * p, MY_XML_ATTR * a) static
Definition at line 109 of file xml.c.
 {
   int lex;
   for (; ( p->cur < p->end) && my_xml_is_space(p->cur[0]) ;  p->cur++);
   if (p->cur >= p->end)
   {
     a->beg=p->end;
     a->end=p->end;
     lex=MY_XML_EOF;
     goto ret;
   }
   a->beg=p->cur;
   a->end=p->cur;
   if ((p->end - p->cur > 3) && !memcmp(p->cur,"<!--",4))
   {
     for (; (p->cur < p->end) && memcmp(p->cur, "-->", 3); p->cur++)
     {}
     if (!memcmp(p->cur, "-->", 3))
       p->cur+=3;
     a->end=p->cur;
     lex=MY_XML_COMMENT;
   }
   else if (!memcmp(p->cur, "<![CDATA[",9))
   {
     p->cur+= 9;
     for (; p->cur < p->end - 2 ; p->cur++)
     {
       if (p->cur[0] == ']' && p->cur[1] == ']' && p->cur[2] == '>')
       {
         p->cur+= 3;
         a->end= p->cur;
         break;
       }
     }
     lex= MY_XML_CDATA;
   }
   else if (strchr("?=/<>!",p->cur[0]))
   {
     p->cur++;
     a->end=p->cur;
     lex=a->beg[0];
   }
   else if ( (p->cur[0] == '"') || (p->cur[0] == '\'') )
   {
     p->cur++;
     for (; ( p->cur < p->end ) && (p->cur[0] != a->beg[0]); p->cur++)
     {}
     a->end=p->cur;
     if (a->beg[0] == p->cur[0])p->cur++;
     a->beg++;
     if (!(p->flags & MY_XML_FLAG_SKIP_TEXT_NORMALIZATION))
       my_xml_norm_text(a);
     lex=MY_XML_STRING;
   }
   else if (my_xml_is_id0(p->cur[0]))
   {
     p->cur++;
     while (p->cur < p->end && my_xml_is_id1(p->cur[0]))
       p->cur++;
     a->end=p->cur;
     my_xml_norm_text(a);
     lex=MY_XML_IDENT;
   }
   else
     lex= MY_XML_UNKNOWN;
 #if 0
   printf("LEX=%s[%d]\n",lex2str(lex),a->end-a->beg);
 #endif
 ret:
   return lex;
 }
References mpq::a, xml_stack_st::cur, xml_stack_st::end, xml_stack_st::flags, lex2str(), MY_XML_CDATA, MY_XML_COMMENT, MY_XML_EOF, MY_XML_FLAG_SKIP_TEXT_NORMALIZATION, MY_XML_IDENT, my_xml_is_id0, my_xml_is_id1, my_xml_is_space, my_xml_norm_text(), MY_XML_STRING, MY_XML_UNKNOWN, printf(), and ret.
Referenced by my_xml_parse().
my_xml_set_enter_handler()
void my_xml_set_enter_handler (MY_XML_PARSER * p, int(*)(MY_XML_PARSER *p, const char *s, size_t l) action)
Definition at line 446 of file xml.c.
 {
   p->enter=action;
 }
References xml_stack_st::enter.
my_xml_set_leave_handler()
void my_xml_set_leave_handler (MY_XML_PARSER * p, int(*)(MY_XML_PARSER *p, const char *s, size_t l) action)
Definition at line 454 of file xml.c.
 {
   p->leave_xml=action;
 }
References xml_stack_st::leave_xml.
my_xml_set_user_data()
void my_xml_set_user_data (MY_XML_PARSER * p, void * user_data)
Definition at line 462 of file xml.c.
 {
   p->user_data=user_data;
 }
References xml_stack_st::user_data.
Referenced by my_parse_charset_xml().
my_xml_set_value_handler()
void my_xml_set_value_handler (MY_XML_PARSER * p, int(*)(MY_XML_PARSER *p, const char *s, size_t l) action)
Definition at line 439 of file xml.c.
 {
   p->value=action;
 }
References xml_stack_st::value.
my_xml_value()
static int my_xml_value (MY_XML_PARSER * st, const char * str, size_t len) static
Definition at line 188 of file xml.c.
 {
   return (st->value) ? (st->value)(st,str,len) : MY_XML_OK;
 }
References MY_XML_OK, and xml_stack_st::value.
Referenced by my_xml_parse().
Variable Documentation
my_xml_ctype
char my_xml_ctype[256] static
Initial value:
=
{
  0,0,0,0,0,0,0,0,0,8,8,0,0,8,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  8,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,
  2,2,2,2,2,2,2,2,2,2,3,0,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,0,0,0,0,3,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
}
Definition at line 57 of file xml.c.