Azerotcore-wotlk: npc_cult_adherent::npc_cult_adherentAI Struct Reference
npc_cult_adherent::npc_cult_adherentAI Struct Reference
Public Member Functions
npc_cult_adherentAI (Creature *creature)
void Reset () override
void SpellHit (Unit *, SpellInfo const *spell) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * _instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 785 of file boss_lady_deathwhisper.cpp.
Constructor & Destructor Documentation
npc_cult_adherentAI()
npc_cult_adherent::npc_cult_adherentAI::npc_cult_adherentAI (Creature * creature) inline
Definition at line 787 of file boss_lady_deathwhisper.cpp.
 : ScriptedAI(creature), _instance(creature->GetInstanceScript()) {}
Member Function Documentation
EnterCombat()
void npc_cult_adherent::npc_cult_adherentAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 832 of file boss_lady_deathwhisper.cpp.
 { DoZoneInCombat(); }
References CreatureAI::DoZoneInCombat().
Reset()
void npc_cult_adherent::npc_cult_adherentAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 792 of file boss_lady_deathwhisper.cpp.
         {
             events.Reset();
             events.ScheduleEvent(EVENT_SPELL_ADHERENT_FROST_FEVER, urand(10000, 12000));
             events.ScheduleEvent(EVENT_SPELL_ADHERENT_DEATHCHILL, urand(14000, 16000));
             events.ScheduleEvent(EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR, urand(14000, 16000));
             events.ScheduleEvent(EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT, urand(32000, 39000));
         }
References EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR, EVENT_SPELL_ADHERENT_DEATHCHILL, EVENT_SPELL_ADHERENT_FROST_FEVER, EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT, and urand().
Referenced by UpdateAI().
SpellHit()
void npc_cult_adherent::npc_cult_adherentAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 801 of file boss_lady_deathwhisper.cpp.
         {
             switch (spell->Id)
             {
                 case SPELL_DARK_EMPOWERMENT:
                     me->UpdateEntry(NPC_EMPOWERED_ADHERENT);
                     break;
                 case SPELL_DARK_EMPOWERMENT_T:
                     me->InterruptNonMeleeSpells(true);
                     me->CastSpell(me, SPELL_DARK_EMPOWERMENT, false);
                     break;
                 case SPELL_DARK_MARTYRDOM_T:
                     me->SetReactState(REACT_PASSIVE);
                     me->InterruptNonMeleeSpells(true);
                     ApplyMechanicImmune(me, true);
                     me->AttackStop();
                     me->GetMotionMaster()->MovementExpired();
                     me->GetMotionMaster()->MoveIdle();
                     me->StopMoving();
                     me->CastSpell(me, SPELL_DARK_MARTYRDOM_ADHERENT, false);
                     break;
                 case SPELL_DARK_MARTYRDOM_ADHERENT:
                 case SPELL_DARK_MARTYRDOM_ADHERENT_10H:
                 case SPELL_DARK_MARTYRDOM_ADHERENT_25N:
                 case SPELL_DARK_MARTYRDOM_ADHERENT_25H:
                     ApplyMechanicImmune(me, false);
                     events.ScheduleEvent(EVENT_SPELL_CULTIST_DARK_MARTYRDOM, 5); // Visual purposes only.
                     break;
             }
         }
References ApplyMechanicImmune(), Unit::AttackStop(), Unit::CastSpell(), EVENT_SPELL_CULTIST_DARK_MARTYRDOM, Unit::GetMotionMaster(), SpellInfo::Id, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), NPC_EMPOWERED_ADHERENT, REACT_PASSIVE, Creature::SetReactState(), SPELL_DARK_EMPOWERMENT, SPELL_DARK_EMPOWERMENT_T, SPELL_DARK_MARTYRDOM_ADHERENT, SPELL_DARK_MARTYRDOM_ADHERENT_10H, SPELL_DARK_MARTYRDOM_ADHERENT_25H, SPELL_DARK_MARTYRDOM_ADHERENT_25N, SPELL_DARK_MARTYRDOM_T, Unit::StopMoving(), and Creature::UpdateEntry().
UpdateAI()
void npc_cult_adherent::npc_cult_adherentAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 834 of file boss_lady_deathwhisper.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_ADHERENT_FROST_FEVER:
                     me->CastSpell(me->GetVictim(), SPELL_FROST_FEVER, false);
                     events.RepeatEvent(urand(9000, 13000));
                     break;
                 case EVENT_SPELL_ADHERENT_DEATHCHILL:
                     if (me->GetEntry() == NPC_EMPOWERED_ADHERENT)
                         me->CastSpell(me->GetVictim(), SPELL_DEATHCHILL_BLAST, false);
                     else
                         me->CastSpell(me->GetVictim(), SPELL_DEATHCHILL_BOLT, false);
                     events.RepeatEvent(urand(9000, 13000));
                     break;
                 case EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1))
                         me->CastSpell(target, SPELL_CURSE_OF_TORPOR, false);
                     events.RepeatEvent(urand(9000, 13000));
                     break;
                 case EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT:
                     me->CastSpell(me, SPELL_SHORUD_OF_THE_OCCULT, false);
                     events.RepeatEvent(urand(27000, 32000));
                     break;
                 case EVENT_CULTIST_DARK_MARTYRDOM_REVIVE:
                     me->RemoveAurasDueToSpell(SPELL_PERMANENT_FEIGN_DEATH);
                     me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                     me->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
                     me->UpdateEntry(NPC_REANIMATED_ADHERENT);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED | UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT | UNIT_FLAG_NOT_SELECTABLE);
                     me->SetReactState(REACT_AGGRESSIVE);
                     DoZoneInCombat(me);
                     me->CastSpell(me, SPELL_ADHERENT_S_DETERMINATION);
                     if (Creature* ladyDeathwhisper = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_LADY_DEATHWHISPER)))
                         ladyDeathwhisper->AI()->Talk(SAY_ANIMATE_DEAD);
                     break;
                 case EVENT_SPELL_CULTIST_DARK_MARTYRDOM:
                     me->CastSpell(me, SPELL_PERMANENT_FEIGN_DEATH, true);
                     me->CastSpell(me, SPELL_CLEAR_ALL_DEBUFFS, true);
                     me->CastSpell(me, SPELL_FULL_HEAL, true);
                     me->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                     me->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED | UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT | UNIT_FLAG_NOT_SELECTABLE);
                     Reset();
                     events.ScheduleEvent(EVENT_CULTIST_DARK_MARTYRDOM_REVIVE, 6000);
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _instance, Unit::CastSpell(), DATA_LADY_DEATHWHISPER, UnitAI::DoMeleeAttackIfReady(), CreatureAI::DoZoneInCombat(), EVENT_CULTIST_DARK_MARTYRDOM_REVIVE, EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR, EVENT_SPELL_ADHERENT_DEATHCHILL, EVENT_SPELL_ADHERENT_FROST_FEVER, EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT, EVENT_SPELL_CULTIST_DARK_MARTYRDOM, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, NPC_EMPOWERED_ADHERENT, NPC_REANIMATED_ADHERENT, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), Reset(), SAY_ANIMATE_DEAD, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Object::SetFlag(), Creature::SetReactState(), SPELL_ADHERENT_S_DETERMINATION, SPELL_CLEAR_ALL_DEBUFFS, SPELL_CURSE_OF_TORPOR, SPELL_DEATHCHILL_BLAST, SPELL_DEATHCHILL_BOLT, SPELL_FROST_FEVER, SPELL_FULL_HEAL, SPELL_PERMANENT_FEIGN_DEATH, SPELL_SHORUD_OF_THE_OCCULT, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_FLAG_STUNNED, UNIT_STATE_CASTING, Creature::UpdateEntry(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_instance
InstanceScript* npc_cult_adherent::npc_cult_adherentAI::_instance
Definition at line 790 of file boss_lady_deathwhisper.cpp.
Referenced by UpdateAI().
events
EventMap npc_cult_adherent::npc_cult_adherentAI::events
Definition at line 789 of file boss_lady_deathwhisper.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp