Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/large_externs.h File Reference
large_externs.h File Reference
#include "jemalloc/internal/hook.h"
Typedefs
typedef void() large_dalloc_junk_t(void *, size_t)
typedef void() large_dalloc_maybe_junk_t(void *, size_t)
Functions
void * large_malloc (tsdn_t *tsdn, arena_t *arena, size_t usize, bool zero)
void * large_palloc (tsdn_t *tsdn, arena_t *arena, size_t usize, size_t alignment, bool zero)
bool large_ralloc_no_move (tsdn_t *tsdn, extent_t *extent, size_t usize_min, size_t usize_max, bool zero)
void * large_ralloc (tsdn_t *tsdn, arena_t *arena, void *ptr, size_t usize, size_t alignment, bool zero, tcache_t *tcache, hook_ralloc_args_t *hook_args)
void large_dalloc_prep_junked_locked (tsdn_t *tsdn, extent_t *extent)
void large_dalloc_finish (tsdn_t *tsdn, extent_t *extent)
void large_dalloc (tsdn_t *tsdn, extent_t *extent)
size_t large_salloc (tsdn_t *tsdn, const extent_t *extent)
prof_tctx_t * large_prof_tctx_get (tsdn_t *tsdn, const extent_t *extent)
void large_prof_tctx_set (tsdn_t *tsdn, extent_t *extent, prof_tctx_t *tctx)
void large_prof_tctx_reset (tsdn_t *tsdn, extent_t *extent)
nstime_t large_prof_alloc_time_get (const extent_t *extent)
void large_prof_alloc_time_set (extent_t *extent, nstime_t time)
Variables
large_dalloc_junk_t *JET_MUTABLE large_dalloc_junk
large_dalloc_maybe_junk_t *JET_MUTABLE large_dalloc_maybe_junk
Typedef Documentation
large_dalloc_junk_t
typedef void() large_dalloc_junk_t(void *, size_t)
Definition at line 15 of file large_externs.h.
large_dalloc_maybe_junk_t
typedef void() large_dalloc_maybe_junk_t(void *, size_t)
Definition at line 18 of file large_externs.h.
Function Documentation
large_dalloc()
void large_dalloc (tsdn_t * tsdn, extent_t * extent)
Definition at line 360 of file large.c.
{
     arena_t *arena = extent_arena_get(extent);
     large_dalloc_prep_impl(tsdn, arena, extent, false);
     large_dalloc_finish_impl(tsdn, arena, extent);
     arena_decay_tick(tsdn, arena);
 }
References arena, arena_decay_tick(), extent_arena_get(), large_dalloc_finish_impl(), and large_dalloc_prep_impl().
large_dalloc_finish()
void large_dalloc_finish (tsdn_t * tsdn, extent_t * extent)
Definition at line 355 of file large.c.
{
     large_dalloc_finish_impl(tsdn, extent_arena_get(extent), extent);
 }
References extent_arena_get(), and large_dalloc_finish_impl().
large_dalloc_prep_junked_locked()
void large_dalloc_prep_junked_locked (tsdn_t * tsdn, extent_t * extent)
Definition at line 350 of file large.c.
{
     large_dalloc_prep_impl(tsdn, extent_arena_get(extent), extent, true);
 }
References extent_arena_get(), and large_dalloc_prep_impl().
large_malloc()
void* large_malloc (tsdn_t * tsdn, arena_t * arena, size_t usize, bool zero)
Definition at line 14 of file large.c.
{
     assert(usize == sz_s2u(usize));
     return large_palloc(tsdn, arena, usize, CACHELINE, zero);
 }
References arena, assert(), CACHELINE, large_palloc(), sz_s2u(), and G3D::zero().
Referenced by large_ralloc_move_helper().
large_palloc()
void* large_palloc (tsdn_t * tsdn, arena_t * arena, size_t usize, size_t alignment, bool zero)
Definition at line 21 of file large.c.
                {
     size_t ausize;
     extent_t *extent;
     bool is_zeroed;
     UNUSED bool idump JEMALLOC_CC_SILENCE_INIT(false);
     assert(!tsdn_null(tsdn) || arena != NULL);
     ausize = sz_sa2u(usize, alignment);
     if (unlikely(ausize == 0 || ausize > SC_LARGE_MAXCLASS)) {
         return NULL;
     }
     if (config_fill && unlikely(opt_zero)) {
         zero = true;
     }
     /*
      * Copy zero into is_zeroed and pass the copy when allocating the
      * extent, so that it is possible to make correct junk/zero fill
      * decisions below, even if is_zeroed ends up true when zero is false.
      */
     is_zeroed = zero;
     if (likely(!tsdn_null(tsdn))) {
         arena = arena_choose_maybe_huge(tsdn_tsd(tsdn), arena, usize);
     }
     if (unlikely(arena == NULL) || (extent = arena_extent_alloc_large(tsdn,
         arena, usize, alignment, &is_zeroed)) == NULL) {
         return NULL;
     }
     /* See comments in arena_bin_slabs_full_insert(). */
     if (!arena_is_auto(arena)) {
         /* Insert extent into large. */
         malloc_mutex_lock(tsdn, &arena->large_mtx);
         extent_list_append(&arena->large, extent);
         malloc_mutex_unlock(tsdn, &arena->large_mtx);
     }
     if (config_prof && arena_prof_accum(tsdn, arena, usize)) {
         prof_idump(tsdn);
     }
     if (zero) {
         assert(is_zeroed);
     } else if (config_fill && unlikely(opt_junk_alloc)) {
         memset(extent_addr_get(extent), JEMALLOC_ALLOC_JUNK,
             extent_usize_get(extent));
     }
     arena_decay_tick(tsdn, arena);
     return extent_addr_get(extent);
 }
References arena, arena_choose_maybe_huge(), arena_decay_tick(), arena_extent_alloc_large, arena_is_auto(), arena_prof_accum(), assert(), config_fill, config_prof, extent_addr_get(), extent_list_append(), extent_usize_get(), JEMALLOC_ALLOC_JUNK, JEMALLOC_CC_SILENCE_INIT, arena_s::large, arena_s::large_mtx, likely, malloc_mutex_lock(), malloc_mutex_unlock(), memset, NULL, opt_junk_alloc, opt_zero, prof_idump, SC_LARGE_MAXCLASS, sz_sa2u(), tsdn_null(), tsdn_tsd(), unlikely, UNUSED, and G3D::zero().
Referenced by large_malloc(), and large_ralloc_move_helper().
large_prof_alloc_time_get()
nstime_t large_prof_alloc_time_get (const extent_t * extent)
Definition at line 388 of file large.c.
{
     return extent_prof_alloc_time_get(extent);
 }
References extent_prof_alloc_time_get().
large_prof_alloc_time_set()
void large_prof_alloc_time_set (extent_t * extent, nstime_t time)
Definition at line 393 of file large.c.
{
     extent_prof_alloc_time_set(extent, t);
 }
References extent_prof_alloc_time_set().
large_prof_tctx_get()
prof_tctx_t* large_prof_tctx_get (tsdn_t * tsdn, const extent_t * extent)
Definition at line 373 of file large.c.
{
     return extent_prof_tctx_get(extent);
 }
References extent_prof_tctx_get().
large_prof_tctx_reset()
void large_prof_tctx_reset (tsdn_t * tsdn, extent_t * extent)
Definition at line 383 of file large.c.
{
     large_prof_tctx_set(tsdn, extent, (prof_tctx_t *)(uintptr_t)1U);
 }
References large_prof_tctx_set().
large_prof_tctx_set()
void large_prof_tctx_set (tsdn_t * tsdn, extent_t * extent, prof_tctx_t * tctx)
Definition at line 378 of file large.c.
{
     extent_prof_tctx_set(extent, tctx);
 }
References extent_prof_tctx_set(), and tctx.
Referenced by large_prof_tctx_reset().
large_ralloc()
void* large_ralloc (tsdn_t * tsdn, arena_t * arena, void * ptr, size_t usize, size_t alignment, bool zero, tcache_t * tcache, hook_ralloc_args_t * hook_args)
Definition at line 274 of file large.c.
{
     extent_t *extent = iealloc(tsdn, ptr);
     size_t oldusize = extent_usize_get(extent);
     /* The following should have been caught by callers. */
     assert(usize > 0 && usize <= SC_LARGE_MAXCLASS);
     /* Both allocation sizes must be large to avoid a move. */
     assert(oldusize >= SC_LARGE_MINCLASS
         && usize >= SC_LARGE_MINCLASS);
     /* Try to avoid moving the allocation. */
     if (!large_ralloc_no_move(tsdn, extent, usize, usize, zero)) {
         hook_invoke_expand(hook_args->is_realloc
             ? hook_expand_realloc : hook_expand_rallocx, ptr, oldusize,
             usize, (uintptr_t)ptr, hook_args->args);
         return extent_addr_get(extent);
     }
     /*
      * usize and old size are different enough that we need to use a
      * different size class.  In that case, fall back to allocating new
      * space and copying.
      */
     void *ret = large_ralloc_move_helper(tsdn, arena, usize, alignment,
         zero);
     if (ret == NULL) {
         return NULL;
     }
     hook_invoke_alloc(hook_args->is_realloc
         ? hook_alloc_realloc : hook_alloc_rallocx, ret, (uintptr_t)ret,
         hook_args->args);
     hook_invoke_dalloc(hook_args->is_realloc
         ? hook_dalloc_realloc : hook_dalloc_rallocx, ptr, hook_args->args);
     size_t copysize = (usize < oldusize) ? usize : oldusize;
     memcpy(ret, extent_addr_get(extent), copysize);
     isdalloct(tsdn, extent_addr_get(extent), oldusize, tcache, NULL, true);
     return ret;
 }
References arena, hook_ralloc_args_s::args, assert(), extent_addr_get(), extent_usize_get(), hook_alloc_rallocx, hook_alloc_realloc, hook_dalloc_rallocx, hook_dalloc_realloc, hook_expand_rallocx, hook_expand_realloc, hook_invoke_alloc, hook_invoke_dalloc, hook_invoke_expand, iealloc(), hook_ralloc_args_s::is_realloc, isdalloct(), large_ralloc_move_helper(), large_ralloc_no_move(), memcpy, NULL, ptr(), ret, SC_LARGE_MAXCLASS, SC_LARGE_MINCLASS, and G3D::zero().
large_ralloc_no_move()
bool large_ralloc_no_move (tsdn_t * tsdn, extent_t * extent, size_t usize_min, size_t usize_max, bool zero)
Definition at line 219 of file large.c.
{
     size_t oldusize = extent_usize_get(extent);
     /* The following should have been caught by callers. */
     assert(usize_min > 0 && usize_max <= SC_LARGE_MAXCLASS);
     /* Both allocation sizes must be large to avoid a move. */
     assert(oldusize >= SC_LARGE_MINCLASS
         && usize_max >= SC_LARGE_MINCLASS);
     if (usize_max > oldusize) {
         /* Attempt to expand the allocation in-place. */
         if (!large_ralloc_no_move_expand(tsdn, extent, usize_max,
             zero)) {
             arena_decay_tick(tsdn, extent_arena_get(extent));
             return false;
         }
         /* Try again, this time with usize_min. */
         if (usize_min < usize_max && usize_min > oldusize &&
             large_ralloc_no_move_expand(tsdn, extent, usize_min,
             zero)) {
             arena_decay_tick(tsdn, extent_arena_get(extent));
             return false;
         }
     }
     /*
      * Avoid moving the allocation if the existing extent size accommodates
      * the new size.
      */
     if (oldusize >= usize_min && oldusize <= usize_max) {
         arena_decay_tick(tsdn, extent_arena_get(extent));
         return false;
     }
     /* Attempt to shrink the allocation in-place. */
     if (oldusize > usize_max) {
         if (!large_ralloc_no_move_shrink(tsdn, extent, usize_max)) {
             arena_decay_tick(tsdn, extent_arena_get(extent));
             return false;
         }
     }
     return true;
 }
References arena_decay_tick(), assert(), extent_arena_get(), extent_usize_get(), large_ralloc_no_move_expand(), large_ralloc_no_move_shrink(), SC_LARGE_MAXCLASS, SC_LARGE_MINCLASS, and G3D::zero().
Referenced by large_ralloc().
large_salloc()
size_t large_salloc (tsdn_t * tsdn, const extent_t * extent)
Definition at line 368 of file large.c.
{
     return extent_usize_get(extent);
 }
References extent_usize_get().
Variable Documentation
large_dalloc_junk
large_dalloc_junk_t* JET_MUTABLE large_dalloc_junk extern
Definition at line 78 of file large.c.
Referenced by large_dalloc_maybe_junk_impl().
large_dalloc_maybe_junk
large_dalloc_maybe_junk_t* JET_MUTABLE large_dalloc_maybe_junk extern
Definition at line 92 of file large.c.
Referenced by large_dalloc_prep_impl(), and large_ralloc_no_move_shrink().