Azerotcore-wotlk: CharacterActionIpLogger Class Reference
CharacterActionIpLogger Class Reference
Public Member Functions
CharacterActionIpLogger ()
void OnCreate (Player *player) override
void OnLogin (Player *player) override
void OnLogout (Player *player) override
void CharacterIPLogAction (Player *player, IPLoggingTypes aType)
Logs a number of actions done by players with an IP.
Public Member Functions inherited from PlayerScript
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnCreatureKill (Player *, Creature *)
virtual void OnCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnLevelChanged (Player *, uint8)
virtual void OnFreeTalentPointsChanged (Player *, uint32)
virtual void OnTalentsReset (Player *, bool)
virtual void OnBeforeUpdate (Player *, uint32)
virtual void OnUpdate (Player *, uint32)
virtual void OnMoneyChanged (Player *, int32 &)
virtual void OnGiveXP (Player *, uint32 &, Unit *)
virtual void OnReputationChange (Player *, uint32, int32 &, bool)
virtual void OnReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnLearnSpell (Player *, uint32)
virtual void OnForgotSpell (Player *, uint32)
virtual void OnDuelRequest (Player *, Player *)
virtual void OnDuelStart (Player *, Player *)
virtual void OnDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnChat (Player *, uint32, uint32, std::string &)
virtual void OnBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnEmote (Player *, uint32)
virtual void OnTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnSpellCast (Player *, Spell *, bool)
virtual void OnLoadFromDB (Player *)
virtual void OnDelete (ObjectGuid, uint32)
virtual void OnFailedDelete (ObjectGuid, uint32)
virtual void OnSave (Player *)
virtual void OnBindToInstance (Player *, Difficulty, uint32, bool)
virtual void OnUpdateZone (Player *, uint32, uint32)
virtual void OnUpdateArea (Player *, uint32, uint32)
virtual void OnMapChanged (Player *)
virtual bool OnBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnUpdateFaction (Player *)
virtual void OnAddToBattleground (Player *, Battleground *)
virtual void OnQueueRandomDungeon (Player *, uint32 &)
virtual void OnRemoveFromBattleground (Player *, Battleground *)
virtual void OnAchiComplete (Player *, AchievementEntry const *)
virtual bool OnBeforeAchiComplete (Player *, AchievementEntry const *)
virtual void OnCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnAchiSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void GetCustomGetArenaTeamId (const Player *, uint8, uint32 &) const
virtual void GetCustomArenaPersonalRating (const Player *, uint8, uint32 &) const
virtual void OnGetMaxPersonalArenaRatingRequirement (const Player *, uint32, uint32 &) const
virtual void OnLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnCreateItem (Player *, Item *, uint32)
virtual void OnQuestRewardItem (Player *, Item *, uint32)
virtual bool OnBeforeQuestComplete (Player *, uint32)
virtual void OnBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnAfterUpdateMaxHealth (Player *, float &)
virtual void OnBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnFirstLogin (Player *)
virtual bool CanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool CanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool CanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool CanGroupInvite (Player *, std::string &)
virtual bool CanGroupAccept (Player *, Group *)
virtual bool CanSellItem (Player *, Item *, Creature *)
virtual bool CanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void PetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void PetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnRewardKillRewarder (Player *, bool, float &)
virtual bool CanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool CanRepopAtGraveyard (Player *)
virtual void OnGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool CanAreaExploreAndOutdoor (Player *)
virtual void OnVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual bool CanArmorDamageModifier (Player *)
virtual void OnGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool CanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool CanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool CanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool CanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool CanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool CanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool CanUnequipItem (Player *, uint16, bool)
virtual bool CanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool CanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool CanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnGetQuestRate (Player *, float &)
virtual bool PassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool CheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool NotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool NotVisibleGloballyFor (Player *, Player const *)
virtual void OnGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnIsFFAPvP (Player *, bool &)
virtual void OnIsPvP (Player *, bool &)
virtual void OnGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool NotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool CanJoinLfg (Player *, uint8, lfg::LfgDungeonSet &, const std::string &)
virtual bool CanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool CanInitTrade (Player *, Player *)
virtual void OnSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void AnticheatSetSkipOnePacketForASH (Player *, bool)
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from PlayerScript
PlayerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 167 of file action_ip_logger.cpp.
Constructor & Destructor Documentation
CharacterActionIpLogger()
CharacterActionIpLogger::CharacterActionIpLogger () inline
Definition at line 170 of file action_ip_logger.cpp.
 : PlayerScript("CharacterActionIpLogger") { }
Member Function Documentation
CharacterIPLogAction()
void CharacterActionIpLogger::CharacterIPLogAction (Player * player, IPLoggingTypes aType) inline
Logs a number of actions done by players with an IP.
Definition at line 199 of file action_ip_logger.cpp.
     {
         if (!sWorld->getBoolConfig(CONFIG_IP_BASED_ACTION_LOGGING))
             return;
         // Action IP Logger is only intialized if config is set up
         // Else, this script isn't loaded in the first place: We require no config check.
         // We declare all the required variables
         uint32 playerGuid = player->GetSession()->GetAccountId();
         ObjectGuid::LowType characterGuid = player->GetGUID().GetCounter();
         const std::string currentIp = player->GetSession()->GetRemoteAddress();
         std::string systemNote = "ERROR"; // "ERROR" is a placeholder here. We change it...
         // ... with this switch, so that we have a more accurate phrasing of what type it is
         switch (aType)
         {
             case CHARACTER_CREATE:
                 systemNote = "Logged on CharacterCreate";
                 break;
             case CHARACTER_LOGIN:
                 systemNote = "Logged on CharacterLogin";
                 break;
             case CHARACTER_LOGOUT:
                 systemNote = "Logged on CharacterLogout";
                 break;
             case CHARACTER_DELETE:
                 systemNote = "Logged on CharacterDelete";
                 break;
             case CHARACTER_FAILED_DELETE:
                 systemNote = "Logged on Failed CharacterDelete";
                 break;
             // Neither should happen. Ever. Period. If it does, call Mythbusters.
             case UNKNOWN_ACTION:
             default:
                 systemNote = "ERROR! Unknown action!";
                 break;
         }
         // Once we have done everything, we can insert the new log.
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_CHAR_IP_LOGGING);
         stmt->setUInt32(0, playerGuid);
         stmt->setUInt32(1, characterGuid);
         stmt->setUInt8(2, aType);
         stmt->setString(3, currentIp.c_str()); // We query the ip here.
         stmt->setString(4, systemNote.c_str());
         // Seeing as the time differences should be minimal, we do not get unixtime and the timestamp right now;
         // Rather, we let it be added with the SQL query.
         LoginDatabase.Execute(stmt);
         return;
     }
References CHARACTER_CREATE, CHARACTER_DELETE, CHARACTER_FAILED_DELETE, CHARACTER_LOGIN, CHARACTER_LOGOUT, CONFIG_IP_BASED_ACTION_LOGGING, WorldSession::GetAccountId(), ObjectGuid::GetCounter(), Object::GetGUID(), WorldSession::GetRemoteAddress(), Player::GetSession(), LOGIN_INS_CHAR_IP_LOGGING, LoginDatabase, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sWorld, and UNKNOWN_ACTION.
Referenced by OnCreate(), OnLogin(), and OnLogout().
OnCreate()
void CharacterActionIpLogger::OnCreate (Player * player) inline override virtual
Reimplemented from PlayerScript.
Definition at line 173 of file action_ip_logger.cpp.
     {
         CharacterIPLogAction(player, CHARACTER_CREATE);
     }
References CHARACTER_CREATE, and CharacterIPLogAction().
OnLogin()
void CharacterActionIpLogger::OnLogin (Player * player) inline override virtual
Reimplemented from PlayerScript.
Definition at line 179 of file action_ip_logger.cpp.
     {
         CharacterIPLogAction(player, CHARACTER_LOGIN);
     }
References CHARACTER_LOGIN, and CharacterIPLogAction().
OnLogout()
void CharacterActionIpLogger::OnLogout (Player * player) inline override virtual
Reimplemented from PlayerScript.
Definition at line 185 of file action_ip_logger.cpp.
     {
         CharacterIPLogAction(player, CHARACTER_LOGOUT);
     }
References CHARACTER_LOGOUT, and CharacterIPLogAction().
The documentation for this class was generated from the following file:
src/server/scripts/World/action_ip_logger.cpp