Azerotcore-wotlk: achievement_commandscript Class Reference
achievement_commandscript Class Reference
Public Member Functions
achievement_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleAchievementAddCommand (ChatHandler *handler, AchievementEntry const *achievementEntry)
static bool HandleAchievementCheckAllCommand (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 33 of file cs_achievement.cpp.
Constructor & Destructor Documentation
achievement_commandscript()
achievement_commandscript::achievement_commandscript () inline
Definition at line 36 of file cs_achievement.cpp.
 : CommandScript("achievement_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable achievement_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 38 of file cs_achievement.cpp.
     {
         static ChatCommandTable achievementCommandTable =
         {
             { "add",      HandleAchievementAddCommand,      SEC_GAMEMASTER,    Console::No },
             { "checkall", HandleAchievementCheckAllCommand, SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "achievement", achievementCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleAchievementAddCommand()
static bool achievement_commandscript::HandleAchievementAddCommand (ChatHandler * handler, AchievementEntry const * achievementEntry) inline static
Definition at line 52 of file cs_achievement.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         target->CompletedAchievement(achievementEntry);
         return true;
     }
References Player::CompletedAchievement(), ChatHandler::getSelectedPlayer(), LANG_NO_CHAR_SELECTED, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleAchievementCheckAllCommand()
static bool achievement_commandscript::HandleAchievementCheckAllCommand (ChatHandler * handler) inline static
Definition at line 66 of file cs_achievement.cpp.
     {
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         target->CheckAllAchievementCriteria();
         return true;
     }
References Player::CheckAllAchievementCriteria(), ChatHandler::getSelectedPlayer(), LANG_NO_CHAR_SELECTED, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_achievement.cpp