Azerotcore-wotlk: GameObject Class Reference
GameObject Class Reference
#include <GameObject.h>
Public Member Functions
GameObject ()
~GameObject () override
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const override
void AddToWorld () override
void RemoveFromWorld () override
void CleanupsBeforeDelete (bool finalCleanup=true) override
virtual bool Create (ObjectGuid::LowType guidlow, uint32 name_id, Map *map, uint32 phaseMask, float x, float y, float z, float ang, G3D::Quat const &rotation, uint32 animprogress, GOState go_state, uint32 artKit=0)
void Update (uint32 p_time) override
GameObjectTemplate const * GetGOInfo () const
GameObjectTemplateAddon const * GetTemplateAddon () const
GameObjectData const * GetGOData () const
GameObjectValue const * GetGOValue () const
bool IsTransport () const
bool IsDestructibleBuilding () const
ObjectGuid::LowType GetSpawnId () const
void SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
void SetLocalRotation (G3D::Quat const &rot)
void SetTransportPathRotation (float qx, float qy, float qz, float qw)
G3D::Quat const & GetLocalRotation () const
int64 GetPackedLocalRotation () const
G3D::Quat GetWorldRotation () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
void SaveToDB (bool saveAddon=false)
void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask, bool saveAddon=false)
bool LoadFromDB (ObjectGuid::LowType guid, Map *map)
bool LoadGameObjectFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true)
void DeleteFromDB ()
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetOwnerGUID () const
Unit * GetOwner () const
void SetSpellId (uint32 id)
uint32 GetSpellId () const
time_t GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (int32 respawn)
void SetRespawnDelay (int32 respawn)
void Respawn ()
bool isSpawned () const
bool isSpawnedByDefault () const
void SetSpawnedByDefault (bool b)
uint32 GetRespawnDelay () const
void Refresh ()
void DespawnOrUnsummon (Milliseconds delay=0ms, Seconds forcedRespawnTime=0s)
void Delete ()
void GetFishLoot (Loot *loot, Player *loot_owner)
void GetFishLootJunk (Loot *loot, Player *loot_owner)
GameobjectTypes GetGoType () const
void SetGoType (GameobjectTypes type)
GOState GetGoState () const
void SetGoState (GOState state)
uint8 GetGoArtKit () const
void SetGoArtKit (uint8 artkit)
uint8 GetGoAnimProgress () const
void SetGoAnimProgress (uint8 animprogress)
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void EnableCollision (bool enable)
void Use (Unit *user)
LootState getLootState () const
void SetLootState (LootState s, Unit *unit=nullptr)
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
void AddToSkillupList (ObjectGuid playerGuid)
bool IsInSkillupList (ObjectGuid playerGuid) const
void ClearSkillupList ()
void AddUniqueUse (Player *player)
void AddUse ()
uint32 GetUseCount () const
uint32 GetUniqueUseCount () const
void SaveRespawnTime () override
void SaveRespawnTime (uint32 forceDelay)
Player * GetLootRecipient () const
Group * GetLootRecipientGroup () const
void SetLootRecipient (Creature *creature)
void SetLootRecipient (Map *map)
bool IsLootAllowedFor (Player const *player) const
bool HasLootRecipient () const
void SetLootGenerationTime ()
uint32 GetLootGenerationTime () const
GameObject * GetLinkedTrap ()
void SetLinkedTrap (GameObject *linkedTrap)
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool ActivateToQuest (Player *target) const
void UseDoorOrButton (uint32 time_to_restore=0, bool alternative=false, Unit *user=nullptr)
void ResetDoorOrButton ()
void TriggeringLinkedGameObject (uint32 trapEntry, Unit *target)
bool IsNeverVisible () const override
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsInvisibleDueToDespawn () const override
uint8 getLevelForTarget (WorldObject const *target) const override
GameObject * LookupFishingHoleAround (float range)
void CastSpell (Unit *target, uint32 spell)
void SendCustomAnim (uint32 anim)
bool IsInRange (float x, float y, float z, float radius) const
void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr) override
void ModifyHealth (int32 change, Unit *attackerOrHealer=nullptr, uint32 spellId=0)
void SetDestructibleBuildingModifyState (bool allow)
void SetDestructibleState (GameObjectDestructibleState state, Player *eventInvoker=nullptr, bool setHealth=false)
GameObjectDestructibleState GetDestructibleState () const
void EventInform (uint32 eventId)
virtual uint32 GetScriptId () const
GameObjectAI * AI () const
std::string GetAIName () const
void SetDisplayId (uint32 displayid)
uint32 GetDisplayId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr) const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
bool IsStaticTransport () const
bool IsMotionTransport () const
Transport * ToTransport ()
Transport const * ToTransport () const
StaticTransport * ToStaticTransport ()
StaticTransport const * ToStaticTransport () const
MotionTransport * ToMotionTransport ()
MotionTransport const * ToMotionTransport () const
float GetStationaryX () const override
float GetStationaryY () const override
float GetStationaryZ () const override
float GetStationaryO () const override
float GetInteractionDistance () const
void UpdateModelPosition ()
bool IsAtInteractDistance (Position const &pos, float radius) const
bool IsAtInteractDistance (Player const *player, SpellInfo const *spell=nullptr) const
bool IsWithinDistInMap (Player const *player) const
SpellInfo const * GetSpellForLock (Player const *player) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< GameObject >
bool IsInGrid () const
void AddToGrid (GridRefMgr< GameObject > &m)
void RemoveFromGrid ()
Static Public Member Functions
static void SetGoArtKit (uint8 artkit, GameObject *go, ObjectGuid::LowType lowguid=0)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes
Loot loot
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
GameObjectModel * m_model
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes
static std::unordered_map< int, goEventFlag > gameObjectToEventFlag = { }
Protected Types
typedef std::map< uint32, ObjectGuid > ChairSlotAndUser
Protected Member Functions
bool AIM_Initialize ()
GameObjectModel * CreateModel ()
void UpdateModel ()
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Protected Attributes
uint32 m_spellId
time_t m_respawnTime
uint32 m_respawnDelayTime
uint32 m_despawnDelay
Seconds m_despawnRespawnTime
LootState m_lootState
bool m_spawnedByDefault
uint32 m_cooldownTime
GuidList m_SkillupList
ObjectGuid m_ritualOwnerGUID
GuidSet m_unique_users
uint32 m_usetimes
ChairSlotAndUser ChairListSlots
ObjectGuid::LowType m_spawnId
For new or temporary gameobjects is 0 for saved it is lowguid.
GameObjectTemplate const * m_goInfo
GameObjectData const * m_goData
GameObjectValue m_goValue
bool m_allowModifyDestructibleBuilding
int64 m_packedRotation
G3D::Quat m_localRotation
Position m_stationaryPosition
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
uint16 m_LootMode
uint32 m_lootGenerationTime
ObjectGuid m_linkedTrap
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
void CheckRitualList ()
void ClearRitualList ()
void RemoveFromOwner ()
void SwitchDoorOrButton (bool activate, bool alternative=false)
void UpdatePackedRotation ()
bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool, bool) const override
Object distance/size - overridden from Object::_IsWithinDist. Needs to take in account proper GO size.
Private Attributes
GameObjectAI * m_AI
Detailed Description
Definition at line 743 of file GameObject.h.
Member Typedef Documentation
ChairSlotAndUser
typedef std::map<uint32, ObjectGuid> GameObject::ChairSlotAndUser protected
Definition at line 1000 of file GameObject.h.
Constructor & Destructor Documentation
GameObject()
GameObject::GameObject () explicit
Definition at line 45 of file GameObject.cpp.
                        : WorldObject(false), MovableMapObject(),
     m_model(nullptr), m_goValue(), m_AI(nullptr)
 {
     m_objectType |= TYPEMASK_GAMEOBJECT;
     m_objectTypeId = TYPEID_GAMEOBJECT;
     m_updateFlag = (UPDATEFLAG_LOWGUID | UPDATEFLAG_STATIONARY_POSITION | UPDATEFLAG_POSITION | UPDATEFLAG_ROTATION);
     m_valuesCount = GAMEOBJECT_END;
     m_respawnTime = 0;
     m_respawnDelayTime = 300;
     m_despawnDelay = 0;
     m_despawnRespawnTime = 0s;
     m_lootState = GO_NOT_READY;
     m_spawnedByDefault = true;
     m_allowModifyDestructibleBuilding = true;
     m_usetimes = 0;
     m_spellId = 0;
     m_cooldownTime = 0;
     m_goInfo = nullptr;
     m_goData = nullptr;
     m_packedRotation = 0;
     m_spawnId = 0;
     m_lootRecipientGroup = 0;
     m_groupLootTimer = 0;
     lootingGroupLowGUID = 0;
     m_lootGenerationTime = 0;
     ResetLootMode(); // restore default loot mode
     loot.sourceGameObject = this;
     m_stationaryPosition.Relocate(0.0f, 0.0f, 0.0f, 0.0f);
 }
References GAMEOBJECT_END, GO_NOT_READY, loot, lootingGroupLowGUID, m_allowModifyDestructibleBuilding, m_cooldownTime, m_despawnDelay, m_despawnRespawnTime, m_goData, m_goInfo, m_groupLootTimer, m_lootGenerationTime, m_lootRecipientGroup, m_lootState, Object::m_objectType, Object::m_objectTypeId, m_packedRotation, m_respawnDelayTime, m_respawnTime, m_spawnedByDefault, m_spawnId, m_spellId, m_stationaryPosition, Object::m_updateFlag, m_usetimes, Object::m_valuesCount, Position::Relocate(), ResetLootMode(), Loot::sourceGameObject, TYPEID_GAMEOBJECT, TYPEMASK_GAMEOBJECT, UPDATEFLAG_LOWGUID, UPDATEFLAG_POSITION, UPDATEFLAG_ROTATION, and UPDATEFLAG_STATIONARY_POSITION.
Referenced by Create(), and MotionTransport::CreateGOPassenger().
~GameObject()
GameObject::~GameObject () override
Definition at line 80 of file GameObject.cpp.
 {
     delete m_AI;
     delete m_model;
     //if (m_uint32Values)                                      // field array can be not exist if GameOBject not loaded
     //    CleanupsBeforeDelete();
 }
References m_AI, and m_model.
Member Function Documentation
_IsWithinDist()
bool GameObject::_IsWithinDist (WorldObject const * obj, float dist2compare, bool , bool) const inline override private virtual
Object distance/size - overridden from Object::_IsWithinDist. Needs to take in account proper GO size.
Following check does check 3d distance
Reimplemented from WorldObject.
Definition at line 1028 of file GameObject.h.
     {
         dist2compare += obj->GetObjectSize();
         return IsInRange(obj->GetPositionX(), obj->GetPositionY(), obj->GetPositionZ(), dist2compare);
     }
References WorldObject::GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and IsInRange().
ActivateToQuest()
bool GameObject::ActivateToQuest (Player * target) const
Definition at line 1237 of file GameObject.cpp.
 {
     if (target->HasQuestForGO(GetEntry()))
         return true;
     if (!GetGOInfo()->IsGameObjectForQuests())
         return false;
     switch (GetGoType())
     {
         case GAMEOBJECT_TYPE_QUESTGIVER:
             {
                 GameObject* go = const_cast<GameObject*>(this);
                 QuestGiverStatus questStatus = target->GetQuestDialogStatus(go);
                 if (questStatus > DIALOG_STATUS_UNAVAILABLE)
                     return true;
                 break;
             }
         case GAMEOBJECT_TYPE_CHEST:
             {
                 // scan GO chest with loot including quest items
                 if (LootTemplates_Gameobject.HaveQuestLootForPlayer(GetGOInfo()->GetLootId(), target))
                 {
                     //TODO: fix this hack
                     //look for battlegroundAV for some objects which are only activated after mine gots captured by own team
                     if (GetEntry() == BG_AV_OBJECTID_MINE_N || GetEntry() == BG_AV_OBJECTID_MINE_S)
                         if (Battleground* bg = target->GetBattleground())
                             if (bg->GetBgTypeID(true) == BATTLEGROUND_AV && !bg->ToBattlegroundAV()->PlayerCanDoMineQuest(GetEntry(), target->GetTeamId()))
                                 return false;
                     return true;
                 }
                 break;
             }
         case GAMEOBJECT_TYPE_GENERIC:
             {
                 if (GetGOInfo()->_generic.questID == -1 || target->GetQuestStatus(GetGOInfo()->_generic.questID) == QUEST_STATUS_INCOMPLETE)
                     return true;
                 break;
             }
         case GAMEOBJECT_TYPE_SPELL_FOCUS:
             {
                 if (GetGOInfo()->spellFocus.questID > 0 && target->GetQuestStatus(GetGOInfo()->spellFocus.questID) == QUEST_STATUS_INCOMPLETE)
                     return true;
                 break;
             }
         case GAMEOBJECT_TYPE_GOOBER:
             {
                 if (GetGOInfo()->goober.questId == -1 || target->GetQuestStatus(GetGOInfo()->goober.questId) == QUEST_STATUS_INCOMPLETE)
                     return true;
                 break;
             }
         default:
             break;
     }
     return false;
 }
References GameObjectTemplate::_generic, BATTLEGROUND_AV, bg(), BG_AV_OBJECTID_MINE_N, BG_AV_OBJECTID_MINE_S, DIALOG_STATUS_UNAVAILABLE, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, Player::GetBattleground(), Object::GetEntry(), GetGOInfo(), GetGoType(), Player::GetQuestDialogStatus(), Player::GetQuestStatus(), Player::GetTeamId(), GameObjectTemplate::goober, Player::HasQuestForGO(), LootStore::HaveQuestLootForPlayer(), LootTemplates_Gameobject, QUEST_STATUS_INCOMPLETE, GameObjectTemplate::questId, GameObjectTemplate::questID, and GameObjectTemplate::spellFocus.
Referenced by BuildValuesUpdate().
AddLootMode()
void GameObject::AddLootMode (uint16 lootMode) inline
Definition at line 853 of file GameObject.h.
 { m_LootMode |= lootMode; }
References m_LootMode.
AddToSkillupList()
void GameObject::AddToSkillupList (ObjectGuid playerGuid) inline
Definition at line 857 of file GameObject.h.
 { m_SkillupList.push_back(playerGuid); }
References m_SkillupList.
Referenced by Spell::EffectOpenLock().
AddToWorld()
void GameObject::AddToWorld () override virtual
Register the gameobject for guid lookup
Reimplemented from Object.
Definition at line 143 of file GameObject.cpp.
 {
     if (!IsInWorld())
     {
         if (m_zoneScript)
             m_zoneScript->OnGameObjectCreate(this);
         GetMap()->GetObjectsStore().Insert<GameObject>(GetGUID(), this);
         if (m_spawnId)
             GetMap()->GetGameObjectBySpawnIdStore().insert(std::make_pair(m_spawnId, this));
         if (m_model)
         {
             m_model->UpdatePosition();
             GetMap()->InsertGameObjectModel(*m_model);
         }
         EnableCollision(GetGoState() == GO_STATE_READY || IsTransport()); // pussywizard: this startOpen is unneeded here, collision depends entirely on GOState
         WorldObject::AddToWorld();
 #ifdef ELUNA
         sEluna->OnAddToWorld(this);
 #endif
     }
 }
References WorldObject::AddToWorld(), EnableCollision(), Map::GetGameObjectBySpawnIdStore(), GetGoState(), Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), GO_STATE_READY, TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), Map::InsertGameObjectModel(), Object::IsInWorld(), IsTransport(), m_model, m_spawnId, WorldObject::m_zoneScript, ZoneScript::OnGameObjectCreate(), and GameObjectModel::UpdatePosition().
Referenced by AddObjectHelper(), and Map::AddToMap().
AddUniqueUse()
void GameObject::AddUniqueUse (Player * player)
Definition at line 837 of file GameObject.cpp.
 {
     AddUse();
     m_unique_users.insert(player->GetGUID());
 }
References AddUse(), Object::GetGUID(), and m_unique_users.
Referenced by Spell::EffectTransmitted(), and Use().
AddUse()
void GameObject::AddUse () inline
Definition at line 869 of file GameObject.h.
 { ++m_usetimes; }
References m_usetimes.
Referenced by AddUniqueUse(), WorldSession::DoLootRelease(), go_soulwell::go_soulwellAI::GossipHello(), go_simon_cluster::OnGossipHello(), and Use().
AI()
GameObjectAI* GameObject::AI () const inline
Definition at line 938 of file GameObject.h.
 { return m_AI; }
References m_AI.
Referenced by Player::AddQuestAndCheckCompletion(), Spell::DoAllEffectOnTarget(), EventInform(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGossipSelectOptionOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), Spell::SendLoot(), SetLootState(), MotionTransport::Update(), Update(), and Use().
AIM_Initialize()
bool GameObject::AIM_Initialize () protected
Definition at line 88 of file GameObject.cpp.
 {
     if (m_AI)
         delete m_AI;
     m_AI = FactorySelector::SelectGameObjectAI(this);
     if (!m_AI)
         return false;
     m_AI->InitializeAI();
     return true;
 }
References GameObjectAI::InitializeAI(), m_AI, and FactorySelector::SelectGameObjectAI().
Referenced by Create(), StaticTransport::Create(), MotionTransport::Update(), and Update().
BuildValuesUpdate()
void GameObject::BuildValuesUpdate (uint8 updatetype, ByteBuffer * data, Player * target) const override virtual
Reimplemented from Object.
Definition at line 2540 of file GameObject.cpp.
 {
     if (!target)
         return;
     bool forcedFlags = GetGoType() == GAMEOBJECT_TYPE_CHEST && GetGOInfo()->chest.groupLootRules && HasLootRecipient();
     bool targetIsGM = target->IsGameMaster() && AccountMgr::IsGMAccount(target->GetSession()->GetSecurity());
     ByteBuffer fieldBuffer;
     UpdateMask updateMask;
     updateMask.SetCount(m_valuesCount);
     uint32* flags = GameObjectUpdateFieldFlags;
     uint32 visibleFlag = UF_FLAG_PUBLIC;
     if (GetOwnerGUID() == target->GetGUID())
         visibleFlag |= UF_FLAG_OWNER;
     for (uint16 index = 0; index < m_valuesCount; ++index)
     {
         if (_fieldNotifyFlags & flags[index] ||
                 ((updateType == UPDATETYPE_VALUES ? _changesMask.GetBit(index) : m_uint32Values[index]) && (flags[index] & visibleFlag)) ||
                 (index == GAMEOBJECT_FLAGS && forcedFlags))
         {
             updateMask.SetBit(index);
             if (index == GAMEOBJECT_DYNAMIC)
             {
                 uint16 dynFlags = 0;
                 int16 pathProgress = -1;
                 switch (GetGoType())
                 {
                     case GAMEOBJECT_TYPE_QUESTGIVER:
                         if (ActivateToQuest(target))
                             dynFlags |= GO_DYNFLAG_LO_ACTIVATE;
                         break;
                     case GAMEOBJECT_TYPE_CHEST:
                     case GAMEOBJECT_TYPE_GOOBER:
                         if (ActivateToQuest(target))
                             dynFlags |= GO_DYNFLAG_LO_ACTIVATE | GO_DYNFLAG_LO_SPARKLE;
                         else if (targetIsGM)
                             dynFlags |= GO_DYNFLAG_LO_ACTIVATE;
                         break;
                     case GAMEOBJECT_TYPE_SPELL_FOCUS:
                     case GAMEOBJECT_TYPE_GENERIC:
                         if (ActivateToQuest(target))
                             dynFlags |= GO_DYNFLAG_LO_SPARKLE;
                         break;
                     case GAMEOBJECT_TYPE_TRANSPORT:
                         if (const StaticTransport* t = ToStaticTransport())
                             if (t->GetPauseTime())
{
                                 if (GetGoState() == GO_STATE_READY)
{
                                     if (t->GetPathProgress() >= t->GetPauseTime()) // if not, send 100% progress
                                         pathProgress = int16(float(t->GetPathProgress() - t->GetPauseTime()) / float(t->GetPeriod() - t->GetPauseTime()) * 65535.0f);
                                 }
                                 else
{
                                     if (t->GetPathProgress() <= t->GetPauseTime()) // if not, send 100% progress
                                         pathProgress = int16(float(t->GetPathProgress()) / float(t->GetPauseTime()) * 65535.0f);
                                 }
                             }
                         // else it's ignored
                         break;
                     case GAMEOBJECT_TYPE_MO_TRANSPORT:
                         if (const MotionTransport* t = ToMotionTransport())
                             pathProgress = int16(float(t->GetPathProgress()) / float(t->GetPeriod()) * 65535.0f);
                         break;
                     default:
                         break;
                 }
                 fieldBuffer << uint16(dynFlags);
                 fieldBuffer << int16(pathProgress);
             }
             else if (index == GAMEOBJECT_FLAGS)
             {
                 uint32 goFlags = m_uint32Values[GAMEOBJECT_FLAGS];
                 if (GetGoType() == GAMEOBJECT_TYPE_CHEST && GetGOInfo() && GetGOInfo()->chest.groupLootRules && !IsLootAllowedFor(target))
                 {
                     goFlags |= GO_FLAG_LOCKED | GO_FLAG_NOT_SELECTABLE;
                 }
                 fieldBuffer << goFlags;
             }
             else
                 fieldBuffer << m_uint32Values[index];                // other cases
         }
     }
     *data << uint8(updateMask.GetBlockCount());
     updateMask.AppendToPacket(data);
     data->append(fieldBuffer);
 }
References Object::_changesMask, Object::_fieldNotifyFlags, ActivateToQuest(), UpdateMask::AppendToPacket(), GameObjectTemplate::chest, GAMEOBJECT_DYNAMIC, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_TRANSPORT, GameObjectUpdateFieldFlags, UpdateMask::GetBit(), UpdateMask::GetBlockCount(), GetGOInfo(), GetGoState(), GetGoType(), Object::GetGUID(), GetOwnerGUID(), WorldSession::GetSecurity(), Player::GetSession(), GO_DYNFLAG_LO_ACTIVATE, GO_DYNFLAG_LO_SPARKLE, GO_FLAG_LOCKED, GO_FLAG_NOT_SELECTABLE, GO_STATE_READY, GameObjectTemplate::groupLootRules, HasLootRecipient(), index, Player::IsGameMaster(), AccountMgr::IsGMAccount(), IsLootAllowedFor(), Object::m_uint32Values, Object::m_valuesCount, UpdateMask::SetBit(), UpdateMask::SetCount(), ToMotionTransport(), ToStaticTransport(), UF_FLAG_OWNER, UF_FLAG_PUBLIC, and UPDATETYPE_VALUES.
CastSpell()
void GameObject::CastSpell (Unit * target, uint32 spell)
Definition at line 1995 of file GameObject.cpp.
 {
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
     if (!spellInfo)
         return;
     bool self = false;
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (spellInfo->Effects[i].TargetA.GetTarget() == TARGET_UNIT_CASTER)
         {
             self = true;
             break;
         }
     }
     if (self)
     {
         if (target)
             target->CastSpell(target, spellInfo, true);
         return;
     }
     //summon world trigger
     Creature* trigger = SummonTrigger(GetPositionX(), GetPositionY(), GetPositionZ(), 0, spellInfo->CalcCastTime() + 2000, true);
     if (!trigger)
         return;
     if (Unit* owner = GetOwner())
     {
         trigger->SetLevel(owner->getLevel(), false);
         trigger->SetFaction(owner->GetFaction());
         // needed for GO casts for proper target validation checks
         trigger->SetOwnerGUID(owner->GetGUID());
         // xinef: fixes some duel bugs with traps]
         if (owner->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED))
             trigger->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
         if (owner->IsFFAPvP())
             trigger->SetByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_FFA_PVP);
         // xinef: Remove Immunity flags
         trigger->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         // xinef: set proper orientation, fixes cast against stealthed targets
         if (target)
             trigger->SetInFront(target);
         trigger->CastSpell(target ? target : trigger, spellInfo, true, 0, 0, owner->GetGUID());
     }
     else
     {
         // xinef: set faction of gameobject, if no faction - assume hostile
         trigger->SetFaction(GetTemplateAddon() && GetTemplateAddon()->faction ? GetTemplateAddon()->faction : 14);
         // Set owner guid for target if no owner availble - needed by trigger auras
         // - trigger gets despawned and there's no caster avalible (see AuraEffect::TriggerSpell())
         // xinef: set proper orientation, fixes cast against stealthed targets
         if (target)
             trigger->SetInFront(target);
         trigger->CastSpell(target ? target : trigger, spellInfo, true, 0, 0, target ? target->GetGUID() : ObjectGuid::Empty);
     }
 }
References SpellInfo::CalcCastTime(), Unit::CastSpell(), SpellInfo::Effects, ObjectGuid::Empty, Object::GetGUID(), GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetTemplateAddon(), MAX_SPELL_EFFECTS, Object::RemoveFlag(), Object::SetByteFlag(), Unit::SetFaction(), Object::SetFlag(), Unit::SetInFront(), Unit::SetLevel(), Unit::SetOwnerGUID(), sSpellMgr, WorldObject::SummonTrigger(), TARGET_UNIT_CASTER, UNIT_BYTE2_FLAG_FFA_PVP, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnGameObjectCreate(), go_harpoon_canon::OnGossipHello(), go_amberpine_outhouse::OnGossipSelect(), SmartScript::ProcessAction(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), Update(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), go_witherbark_totem_bundle::go_witherbark_totem_bundleAI::UpdateAI(), and Use().
CheckRitualList()
void GameObject::CheckRitualList () private
Definition at line 204 of file GameObject.cpp.
 {
     if (m_unique_users.empty())
         return;
     for (GuidSet::iterator itr = m_unique_users.begin(); itr != m_unique_users.end();)
     {
         if (*itr == GetOwnerGUID())
         {
             ++itr;
             continue;
         }
         bool erase = true;
         if (Player* channeler = ObjectAccessor::GetPlayer(*this, *itr))
             if (Spell* spell = channeler->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                 if (spell->m_spellInfo->Id == GetGOInfo()->summoningRitual.animSpell)
                     erase = false;
         if (erase)
             m_unique_users.erase(itr++);
         else
             ++itr;
     }
 }
References GameObjectTemplate::animSpell, CURRENT_CHANNELED_SPELL, GetGOInfo(), GetOwnerGUID(), ObjectAccessor::GetPlayer(), and m_unique_users.
Referenced by Update(), and Use().
CleanupsBeforeDelete()
void GameObject::CleanupsBeforeDelete (bool finalCleanup = true) override virtual
Reimplemented from WorldObject.
Reimplemented in StaticTransport, and MotionTransport.
Definition at line 107 of file GameObject.cpp.
 {
     if (GetTransport() && !ToTransport())
     {
         GetTransport()->RemovePassenger(this);
         SetTransport(nullptr);
         m_movementInfo.transport.Reset();
         m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
     }
     if (IsInWorld())
         RemoveFromWorld();
     if (m_uint32Values)                                      // field array can be not exist if GameOBject not loaded
         RemoveFromOwner();
 }
References WorldObject::GetTransport(), Object::IsInWorld(), WorldObject::m_movementInfo, Object::m_uint32Values, MOVEMENTFLAG_ONTRANSPORT, RemoveFromOwner(), RemoveFromWorld(), MovementInfo::RemoveMovementFlag(), Transport::RemovePassenger(), MovementInfo::TransportInfo::Reset(), WorldObject::SetTransport(), ToTransport(), and MovementInfo::transport.
Referenced by MotionTransport::CleanupsBeforeDelete(), and StaticTransport::CleanupsBeforeDelete().
ClearRitualList()
void GameObject::ClearRitualList () private
Definition at line 230 of file GameObject.cpp.
 {
     uint32 animSpell = GetGOInfo()->summoningRitual.animSpell;
     if (!animSpell || m_unique_users.empty())
         return;
     for (ObjectGuid const& guid : m_unique_users)
     {
         if (Player* channeler = ObjectAccessor::GetPlayer(*this, guid))
             if (Spell* spell = channeler->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                 if (spell->m_spellInfo->Id == animSpell)
                 {
                     spell->SendChannelUpdate(0);
                     spell->finish();
                 }
     }
     m_unique_users.clear();
 }
References CURRENT_CHANNELED_SPELL, GetGOInfo(), ObjectAccessor::GetPlayer(), m_unique_users, and GameObjectTemplate::summoningRitual.
Referenced by Delete(), and Update().
ClearSkillupList()
void GameObject::ClearSkillupList () inline
Definition at line 866 of file GameObject.h.
 { m_SkillupList.clear(); }
References m_SkillupList.
Create()
bool GameObject::Create (ObjectGuid::LowType guidlow, uint32 name_id, Map * map, uint32 phaseMask, float x, float y, float z, float ang, G3D::Quat const & rotation, uint32 animprogress, GOState go_state, uint32 artKit = 0) virtual
Reimplemented in StaticTransport.
Definition at line 250 of file GameObject.cpp.
 {
     ASSERT(map);
     SetMap(map);
     Relocate(x, y, z, ang);
     m_stationaryPosition.Relocate(x, y, z, ang);
     if (!IsPositionValid())
     {
         LOG_ERROR("entities.gameobject", "Gameobject (GUID: %u Entry: %u) not created. Suggested coordinates isn't valid (X: %f Y: %f)", guidlow, name_id, x, y);
         return false;
     }
     SetPhaseMask(phaseMask, false);
     UpdatePositionData();
     SetZoneScript();
     if (m_zoneScript)
     {
         name_id = m_zoneScript->GetGameObjectEntry(guidlow, name_id);
         if (!name_id)
             return false;
     }
     GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(name_id);
     if (!goinfo)
     {
         LOG_ERROR("sql.sql", "Gameobject (GUID: %u Entry: %u) not created: non-existing entry in `gameobject_template`. Map: %u (X: %f Y: %f Z: %f)", guidlow, name_id, map->GetId(), x, y, z);
         return false;
     }
     Object::_Create(guidlow, goinfo->entry, HighGuid::GameObject);
     m_goInfo = goinfo;
     if (goinfo->type >= MAX_GAMEOBJECT_TYPE)
     {
         LOG_ERROR("sql.sql", "Gameobject (GUID: %u Entry: %u) not created: non-existing GO type '%u' in `gameobject_template`. It will crash client if created.", guidlow, name_id, goinfo->type);
         return false;
     }
     GameObjectAddon const* addon = sObjectMgr->GetGameObjectAddon(GetSpawnId());
     // hackfix for the hackfix down below
     switch (goinfo->entry)
     {
         // excluded ids from the hackfix below
         // used switch since there should be more
         case 181233: // maexxna portal effect
         case 181575: // maexxna portal
             SetLocalRotation(rotation);
             break;
         default:
             // xinef: hackfix - but make it possible to use original WorldRotation (using special gameobject addon data)
             // pussywizard: temporarily calculate WorldRotation from orientation, do so until values in db are correct
             if (addon && addon->invisibilityType == INVISIBILITY_GENERAL && addon->InvisibilityValue == 0)
             {
                 SetLocalRotation(rotation);
             }
             else
             {
                 SetLocalRotationAngles(NormalizeOrientation(GetOrientation()), 0.0f, 0.0f);
             }
             break;
     }
     // pussywizard: no PathRotation for normal gameobjects
     SetTransportPathRotation(0.0f, 0.0f, 0.0f, 1.0f);
     SetObjectScale(goinfo->size);
     if (GameObjectTemplateAddon const* templateAddon = GetTemplateAddon())
     {
         SetUInt32Value(GAMEOBJECT_FACTION, templateAddon->faction);
         SetUInt32Value(GAMEOBJECT_FLAGS, templateAddon->flags);
     }
     SetEntry(goinfo->entry);
     // set name for logs usage, doesn't affect anything ingame
     SetName(goinfo->name);
     // GAMEOBJECT_BYTES_1, index at 0, 1, 2 and 3
     SetGoType(GameobjectTypes(goinfo->type));
     SetGoState(go_state);
     SetGoArtKit(artKit);
     SetDisplayId(goinfo->displayId);
     if (!m_model)
         m_model = CreateModel();
     switch (goinfo->type)
     {
         case GAMEOBJECT_TYPE_FISHINGHOLE:
             SetGoAnimProgress(animprogress);
             m_goValue.FishingHole.MaxOpens = urand(GetGOInfo()->fishinghole.minSuccessOpens, GetGOInfo()->fishinghole.maxSuccessOpens);
             break;
         case GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING:
             m_goValue.Building.Health = goinfo->building.intactNumHits + goinfo->building.damagedNumHits;
             m_goValue.Building.MaxHealth = m_goValue.Building.Health;
             SetGoAnimProgress(255);
             break;
         case GAMEOBJECT_TYPE_FISHINGNODE:
             SetGoAnimProgress(0);
             break;
         case GAMEOBJECT_TYPE_TRAP:
             if (GetGOInfo()->trap.stealthed)
             {
                 m_stealth.AddFlag(STEALTH_TRAP);
                 m_stealth.AddValue(STEALTH_TRAP, 70);
             }
             if (GetGOInfo()->trap.invisible)
             {
                 m_invisibility.AddFlag(INVISIBILITY_TRAP);
                 m_invisibility.AddValue(INVISIBILITY_TRAP, 300);
             }
             break;
         default:
             SetGoAnimProgress(animprogress);
             break;
     }
     if (addon)
     {
         if (addon->InvisibilityValue)
         {
             m_invisibility.AddFlag(addon->invisibilityType);
             m_invisibility.AddValue(addon->invisibilityType, addon->InvisibilityValue);
         }
     }
     LastUsedScriptID = GetGOInfo()->ScriptId;
     AIM_Initialize();
     if (uint32 linkedEntry = GetGOInfo()->GetLinkedGameObjectEntry())
     {
         GameObject* linkedGO = new GameObject();
         if (linkedGO->Create(map->GenerateLowGuid<HighGuid::GameObject>(), linkedEntry, map, phaseMask, x, y, z, ang, rotation, 255, GO_STATE_READY))
         {
             SetLinkedTrap(linkedGO);
             map->AddToMap(linkedGO);
         }
         else
         {
             delete linkedGO;
         }
     }
     // Check if GameObject is Large
     if (goinfo->IsLargeGameObject())
         SetVisibilityDistanceOverride(true);
     return true;
 }
References Object::_Create(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), Map::AddToMap(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), AIM_Initialize(), ASSERT, GameObjectTemplate::building, GameObjectValue::Building, Create(), CreateModel(), GameObjectTemplate::displayId, GameObjectTemplate::entry, GameObjectValue::FishingHole, GameObject(), GameObject, GAMEOBJECT_FACTION, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_TRAP, Map::GenerateLowGuid(), ZoneScript::GetGameObjectEntry(), GetGOInfo(), Map::GetId(), Position::GetOrientation(), GetSpawnId(), GetTemplateAddon(), GO_STATE_READY, GameObjectValue::Health, INVISIBILITY_GENERAL, INVISIBILITY_TRAP, GameObjectAddon::invisibilityType, GameObjectAddon::InvisibilityValue, GameObjectTemplate::invisible, GameObjectTemplate::IsLargeGameObject(), Position::IsPositionValid(), WorldObject::LastUsedScriptID, LOG_ERROR, m_goInfo, m_goValue, WorldObject::m_invisibility, m_model, m_stationaryPosition, WorldObject::m_stealth, WorldObject::m_zoneScript, MAX_GAMEOBJECT_TYPE, GameObjectValue::MaxHealth, GameObjectValue::MaxOpens, GameObjectTemplate::maxSuccessOpens, GameObjectTemplate::minSuccessOpens, GameObjectTemplate::name, Position::NormalizeOrientation(), Position::Relocate(), GameObjectTemplate::ScriptId, SetDisplayId(), Object::SetEntry(), SetGoAnimProgress(), SetGoArtKit(), SetGoState(), SetGoType(), SetLinkedTrap(), SetLocalRotation(), SetLocalRotationAngles(), WorldObject::SetMap(), WorldObject::SetName(), Object::SetObjectScale(), SetPhaseMask(), SetTransportPathRotation(), Object::SetUInt32Value(), WorldObject::SetVisibilityDistanceOverride(), WorldObject::SetZoneScript(), GameObjectTemplate::size, sObjectMgr, STEALTH_TRAP, GameObjectTemplate::stealthed, GameObjectTemplate::type, WorldObject::UpdatePositionData(), urand(), G3D::x, G3D::y, and G3D::z.
Referenced by Battleground::AddObject(), Create(), Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), OutdoorPvPSI::HandleDropFlag(), gobject_commandscript::HandleGameObjectAddCommand(), LoadGameObjectFromDB(), Battlefield::SpawnGameObject(), WorldObject::SummonGameObject(), and Map::SummonGameObject().
CreateModel()
GameObjectModel * GameObject::CreateModel () protected
Definition at line 2738 of file GameObject.cpp.
 {
     return GameObjectModel::Create(std::make_unique<GameObjectModelOwnerImpl>(this), sWorld->GetDataPath());
 }
References GameObjectModel::Create(), and sWorld.
Referenced by Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), and UpdateModel().
Delete()
void GameObject::Delete ()
Definition at line 889 of file GameObject.cpp.
 {
     SetLootState(GO_NOT_READY);
     RemoveFromOwner();
     SendObjectDeSpawnAnim(GetGUID());
     SetGoState(GO_STATE_READY);
     if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
         SetUInt32Value(GAMEOBJECT_FLAGS, addon->flags);
     // Xinef: if ritual gameobject is removed, clear anim spells
     if (GetGOInfo()->type == GAMEOBJECT_TYPE_SUMMONING_RITUAL)
         ClearRitualList();
     uint32 poolid = m_spawnId ? sPoolMgr->IsPartOfAPool<GameObject>(m_spawnId) : 0;
     if (poolid)
         sPoolMgr->UpdatePool<GameObject>(poolid, m_spawnId);
     else
         AddObjectToRemoveList();
 }
References WorldObject::AddObjectToRemoveList(), ClearRitualList(), GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_SUMMONING_RITUAL, GetGOInfo(), Object::GetGUID(), GetTemplateAddon(), GO_NOT_READY, GO_STATE_READY, m_spawnId, RemoveFromOwner(), WorldObject::SendObjectDeSpawnAnim(), SetGoState(), SetLootState(), Object::SetUInt32Value(), and sPoolMgr.
Referenced by MotionTransport::DelayedTeleportTransport(), OPvPCapturePoint::DelCapturePoint(), OPvPCapturePoint::DelObject(), OutdoorPvPSI::HandleCustomSpell(), instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript::OnGameObjectCreate(), go_ulduar_working_harpoon::OnGossipHello(), Unit::RemoveAllGameObjects(), Unit::RemoveGameObject(), Update(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::UpdateAI(), and Use().
DeleteFromDB()
void GameObject::DeleteFromDB ()
Definition at line 1097 of file GameObject.cpp.
 {
     GetMap()->RemoveGORespawnTime(m_spawnId);
     sObjectMgr->DeleteGOData(m_spawnId);
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_GAMEOBJECT);
     stmt->setUInt32(0, m_spawnId);
     WorldDatabase.Execute(stmt);
     stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_EVENT_GAMEOBJECT);
     stmt->setUInt32(0, m_spawnId);
     WorldDatabase.Execute(stmt);
 }
References WorldObject::GetMap(), m_spawnId, Map::RemoveGORespawnTime(), PreparedStatementBase::setUInt32(), sObjectMgr, WORLD_DEL_EVENT_GAMEOBJECT, WORLD_DEL_GAMEOBJECT, and WorldDatabase.
DespawnOrUnsummon()
void GameObject::DespawnOrUnsummon (Milliseconds delay = 0ms, Seconds forcedRespawnTime = 0s)
Definition at line 843 of file GameObject.cpp.
 {
     if (delay > 0ms)
     {
         if (!m_despawnDelay || m_despawnDelay > delay.count())
         {
             m_despawnDelay = delay.count();
             m_despawnRespawnTime = forceRespawnTime;
         }
     }
     else
     {
         if (m_goData)
         {
             int32 const respawnDelay = (forceRespawnTime > 0s) ? forceRespawnTime.count() : m_goData->spawntimesecs;
             SetRespawnTime(respawnDelay);
         }
        // Respawn is handled by the gameobject itself.
        // If we delete it from world, it simply never respawns...
        // Uncomment this and remove the following lines if dynamic spawn is implemented.
        // Delete();
         {
             SetLootState(GO_JUST_DEACTIVATED);
             SendObjectDeSpawnAnim(GetGUID());
             SetGoState(GO_STATE_READY);
             if (GameObject* trap = GetLinkedTrap())
             {
                 trap->DespawnOrUnsummon();
             }
             if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
             {
                 SetUInt32Value(GAMEOBJECT_FLAGS, addon->flags);
             }
             uint32 poolid = m_spawnId ? sPoolMgr->IsPartOfAPool<GameObject>(m_spawnId) : 0;
             if (poolid)
             {
                 sPoolMgr->UpdatePool<GameObject>(poolid, m_spawnId);
             }
         }
     }
 }
References GAMEOBJECT_FLAGS, Object::GetGUID(), GetLinkedTrap(), GetTemplateAddon(), GO_JUST_DEACTIVATED, GO_STATE_READY, m_despawnDelay, m_despawnRespawnTime, m_goData, m_spawnId, WorldObject::SendObjectDeSpawnAnim(), SetGoState(), SetLootState(), SetRespawnTime(), Object::SetUInt32Value(), GameObjectData::spawntimesecs, and sPoolMgr.
Referenced by spell_item_crystal_prison_dummy_dnd::HandleDummy(), instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate(), SmartScript::ProcessAction(), and Update().
EnableCollision()
void GameObject::EnableCollision (bool enable)
Definition at line 2419 of file GameObject.cpp.
 {
     if (!m_model)
         return;
     /*if (enable && !GetMap()->ContainsGameObjectModel(*m_model))
         GetMap()->InsertGameObjectModel(*m_model);*/
     uint32 phaseMask = 0;
     if (enable && !DisableMgr::IsDisabledFor(DISABLE_TYPE_GO_LOS, GetEntry(), nullptr))
         phaseMask = GetPhaseMask();
     m_model->enable(phaseMask);
 }
References DISABLE_TYPE_GO_LOS, GameObjectModel::enable(), Object::GetEntry(), WorldObject::GetPhaseMask(), DisableMgr::IsDisabledFor(), and m_model.
Referenced by AddToWorld(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), SetDestructibleState(), SetGoState(), and SetPhaseMask().
EventInform()
void GameObject::EventInform (uint32 eventId)
Definition at line 2100 of file GameObject.cpp.
 {
     if (!eventId)
         return;
     if (AI())
         AI()->EventInform(eventId);
     if (m_zoneScript)
         m_zoneScript->ProcessEvent(this, eventId);
 }
References AI(), GameObjectAI::EventInform(), WorldObject::m_zoneScript, and ZoneScript::ProcessEvent().
Referenced by MotionTransport::DoEventIfAny(), SetDestructibleState(), and Use().
GetAIName()
std::string GameObject::GetAIName () const
Definition at line 102 of file GameObject.cpp.
 {
     return sObjectMgr->GetGameObjectTemplate(GetEntry())->AIName;
 }
References Object::GetEntry(), and sObjectMgr.
Referenced by SmartScript::IsSmartGO(), SmartGameObjectAI::Permissible(), GameObjectAI::Permissible(), and FactorySelector::SelectGameObjectAI().
GetDestructibleState()
GameObjectDestructibleState GameObject::GetDestructibleState () const inline
Definition at line 926 of file GameObject.h.
     {
         if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_DESTROYED))
             return GO_DESTRUCTIBLE_DESTROYED;
         if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED))
             return GO_DESTRUCTIBLE_DAMAGED;
         return GO_DESTRUCTIBLE_INTACT;
     }
References GAMEOBJECT_FLAGS, GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_INTACT, GO_FLAG_DAMAGED, GO_FLAG_DESTROYED, and Object::HasFlag().
Referenced by ModifyHealth().
GetDisplayId()
uint32 GameObject::GetDisplayId () const inline
Definition at line 942 of file GameObject.h.
 { return GetUInt32Value(GAMEOBJECT_DISPLAYID); }
References GAMEOBJECT_DISPLAYID, and Object::GetUInt32Value().
Referenced by GameObjectModelOwnerImpl::GetDisplayId(), and spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::HandleOpenLock().
GetFishLoot()
void GameObject::GetFishLoot (Loot * loot, Player * loot_owner)
Definition at line 912 of file GameObject.cpp.
 {
     fishloot->clear();
     uint32 zone, subzone;
     uint32 defaultzone = 1;
     GetZoneAndAreaId(zone, subzone);
     // if subzone loot exist use it
     fishloot->FillLoot(subzone, LootTemplates_Fishing, loot_owner, true, true);
     if (fishloot->empty())  //use this becase if zone or subzone has set LOOT_MODE_JUNK_FISH,Even if no normal drop, fishloot->FillLoot return true. it wrong.
     {
         //subzone no result,use zone loot
         fishloot->FillLoot(zone, LootTemplates_Fishing, loot_owner, true, true);
         //use zone 1 as default, somewhere fishing got nothing,becase subzone and zone not set, like Off the coast of Storm Peaks.
         if (fishloot->empty())
             fishloot->FillLoot(defaultzone, LootTemplates_Fishing, loot_owner, true, true);
     }
 }
References Loot::clear(), Loot::empty(), Loot::FillLoot(), WorldObject::GetZoneAndAreaId(), and LootTemplates_Fishing.
Referenced by Player::SendLoot().
GetFishLootJunk()
void GameObject::GetFishLootJunk (Loot * loot, Player * loot_owner)
Definition at line 932 of file GameObject.cpp.
 {
     fishloot->clear();
     uint32 zone, subzone;
     uint32 defaultzone = 1;
     GetZoneAndAreaId(zone, subzone);
     // if subzone loot exist use it
     fishloot->FillLoot(subzone, LootTemplates_Fishing, loot_owner, true, true, LOOT_MODE_JUNK_FISH);
     if (fishloot->empty())  //use this becase if zone or subzone has normal mask drop, then fishloot->FillLoot return true.
     {
         //use zone loot
         fishloot->FillLoot(zone, LootTemplates_Fishing, loot_owner, true, true, LOOT_MODE_JUNK_FISH);
         if (fishloot->empty())
             //use zone 1 as default
             fishloot->FillLoot(defaultzone, LootTemplates_Fishing, loot_owner, true, true, LOOT_MODE_JUNK_FISH);
     }
 }
References Loot::clear(), Loot::empty(), Loot::FillLoot(), WorldObject::GetZoneAndAreaId(), LOOT_MODE_JUNK_FISH, and LootTemplates_Fishing.
Referenced by Player::SendLoot().
GetGoAnimProgress()
uint8 GameObject::GetGoAnimProgress () const inline
Definition at line 837 of file GameObject.h.
 { return GetByteValue(GAMEOBJECT_BYTES_1, 3); }
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by Spell::EffectDummy(), SaveToDB(), Update(), and Use().
GetGoArtKit()
uint8 GameObject::GetGoArtKit () const inline
Definition at line 835 of file GameObject.h.
 { return GetByteValue(GAMEOBJECT_BYTES_1, 2); }
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by SaveToDB().
GetGOData()
GameObjectData const* GameObject::GetGOData () const inline
Definition at line 759 of file GameObject.h.
 { return m_goData; }
References m_goData.
Referenced by GetScriptId(), gobject_commandscript::HandleGameObjectMoveCommand(), and SetGoArtKit().
GetGOInfo()
GameObjectTemplate const* GameObject::GetGOInfo () const inline
Definition at line 757 of file GameObject.h.
 { return m_goInfo; }
References m_goInfo.
Referenced by ActivateToQuest(), BuildValuesUpdate(), Spell::CheckCast(), CheckRitualList(), ClearRitualList(), Create(), StaticTransport::Create(), Delete(), WorldSession::DoLootRelease(), Spell::EffectOpenLock(), MotionTransport::EnableMovement(), BattlegroundSA::EventPlayerDamagedGO(), Player::GetDefaultGossipMenuForSource(), GetScriptId(), GetSpellForLock(), GetStationaryO(), GetStationaryX(), GetStationaryY(), GetStationaryZ(), GetTemplateAddon(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), WorldSession::HandleAlterAppearance(), OutdoorPvPSI::HandleCustomSpell(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), OPvPCapturePoint::HandlePlayerEnter(), OPvPCapturePoint::HandlePlayerLeave(), IsAtInteractDistance(), IsDestructibleBuilding(), IsMotionTransport(), IsNeverVisible(), IsStaticTransport(), IsTransport(), LoadGameObjectFromDB(), MotionTransport::LoadStaticPassengers(), ModifyHealth(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), icecrown_citadel_teleport::OnGossipHello(), go_simon_cluster::OnGossipHello(), go_apexis_relic::OnGossipHello(), go_skull_pile::OnGossipHello(), Acore::NearestGameObjectFishingHole::operator()(), Acore::GameObjectInRangeCheck::operator()(), Acore::GameObjectFocusCheck::operator()(), RemoveFromOwner(), Creature::SaveToDB(), SaveToDB(), BfCapturePoint::SendChangePhase(), OPvPCapturePoint::SendChangePhase(), Player::SendLoot(), Spell::SendLoot(), BfCapturePoint::SetCapturePointData(), ToMotionTransport(), ToStaticTransport(), ToTransport(), BfCapturePoint::Update(), OPvPCapturePoint::Update(), MotionTransport::Update(), Update(), UpdateVisibilityOf_helper(), Use(), and UseDoorOrButton().
GetGoState()
GOState GameObject::GetGoState () const inline
Definition at line 833 of file GameObject.h.
 { return GOState(GetByteValue(GAMEOBJECT_BYTES_1, 0)); }
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by Map::_ScriptProcessDoor(), go_suppression_device::go_suppression_deviceAI::Activate(), AddToWorld(), BuildValuesUpdate(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), GameObjectModelOwnerImpl::GetPhaseMask(), gobject_commandscript::HandleGameObjectInfoCommand(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate(), go_shadowforge_brazier::OnGossipHello(), SaveToDB(), SwitchDoorOrButton(), MotionTransport::Update(), StaticTransport::Update(), Update(), and go_suppression_device::go_suppression_deviceAI::UpdateAI().
GetGoType()
GameobjectTypes GameObject::GetGoType () const inline
Definition at line 831 of file GameObject.h.
 { return GameobjectTypes(GetByteValue(GAMEOBJECT_BYTES_1, 1)); }
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by Map::_ScriptProcessDoor(), ActivateToQuest(), Spell::AddGOTarget(), BuildValuesUpdate(), WorldSession::DoLootRelease(), InstanceScript::DoUseDoorOrButton(), Spell::EffectSummonObjectWild(), GetInteractionDistance(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleMovementOpcodes(), IsAtInteractDistance(), IsNeverVisible(), OutdoorPvP::OnGameObjectCreate(), OutdoorPvP::OnGameObjectRemove(), go_resonite_cask::OnGossipHello(), go_gilded_brazier::OnGossipHello(), go_tablet_of_the_seven::OnGossipHello(), go_sacred_fire_of_life::OnGossipHello(), go_fel_crystalforge::OnGossipHello(), go_bashir_crystalforge::OnGossipHello(), Acore::NearestGameObjectTypeInObjectRangeCheck::operator()(), Player::PrepareGossipMenu(), Map::ScriptsProcess(), Spell::SendLoot(), Player::SendQuestGiverStatusMultiple(), SetDestructibleState(), Update(), and Use().
GetGOValue()
GameObjectValue const* GameObject::GetGOValue () const inline
Definition at line 760 of file GameObject.h.
 { return &m_goValue; }
References m_goValue.
Referenced by WorldSession::DoLootRelease(), and Transport::GetPathProgress().
GetInteractionDistance()
float GameObject::GetInteractionDistance () const
Definition at line 2668 of file GameObject.cpp.
 {
     switch (GetGoType())
     {
         case GAMEOBJECT_TYPE_AREADAMAGE:
             return 0.0f;
         case GAMEOBJECT_TYPE_QUESTGIVER:
         case GAMEOBJECT_TYPE_TEXT:
         case GAMEOBJECT_TYPE_FLAGSTAND:
         case GAMEOBJECT_TYPE_FLAGDROP:
         case GAMEOBJECT_TYPE_MINI_GAME:
             return 5.5555553f;
         case GAMEOBJECT_TYPE_BINDER:
             return 10.0f;
         case GAMEOBJECT_TYPE_CHAIR:
         case GAMEOBJECT_TYPE_BARBER_CHAIR:
             return 3.0f;
         case GAMEOBJECT_TYPE_FISHINGNODE:
             return 100.0f;
         case GAMEOBJECT_TYPE_FISHINGHOLE:
             return 20.0f + CONTACT_DISTANCE; // max spell range
         case GAMEOBJECT_TYPE_CAMERA:
         case GAMEOBJECT_TYPE_MAP_OBJECT:
         case GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY:
         case GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING:
         case GAMEOBJECT_TYPE_DOOR:
             return 5.0f;
         // Following values are not blizzlike
         case GAMEOBJECT_TYPE_GUILD_BANK:
         case GAMEOBJECT_TYPE_MAILBOX:
             // Successful mailbox interaction is rather critical to the client, failing it will start a minute-long cooldown until the next mail query may be executed.
             // And since movement info update is not sent with mailbox interaction query, server may find the player outside of interaction range. Thus we increase it.
             return 10.0f; // 5.0f is blizzlike
         default:
             return INTERACTION_DISTANCE;
     }
 }
References CONTACT_DISTANCE, GAMEOBJECT_TYPE_AREADAMAGE, GAMEOBJECT_TYPE_BARBER_CHAIR, GAMEOBJECT_TYPE_BINDER, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GUILD_BANK, GAMEOBJECT_TYPE_MAILBOX, GAMEOBJECT_TYPE_MAP_OBJECT, GAMEOBJECT_TYPE_MINI_GAME, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_TEXT, GetGoType(), and INTERACTION_DISTANCE.
Referenced by IsAtInteractDistance().
getLevelForTarget()
uint8 GameObject::getLevelForTarget (WorldObject const * target) const inline override virtual
Reimplemented from WorldObject.
Definition at line 906 of file GameObject.h.
     {
         if (Unit* owner = GetOwner())
             return owner->getLevelForTarget(target);
         return 1;
     }
References GetOwner().
GetLinkedTrap()
GameObject * GameObject::GetLinkedTrap ()
Definition at line 2535 of file GameObject.cpp.
 {
     return ObjectAccessor::GetGameObject(*this, m_linkedTrap);
 }
References ObjectAccessor::GetGameObject(), and m_linkedTrap.
Referenced by DespawnOrUnsummon(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), RemoveFromWorld(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset(), TriggeringLinkedGameObject(), and Update().
GetLocalRotation()
G3D::Quat const& GameObject::GetLocalRotation () const inline
Definition at line 771 of file GameObject.h.
 { return m_localRotation; }
References m_localRotation.
Referenced by GetWorldRotation().
GetLootGenerationTime()
uint32 GameObject::GetLootGenerationTime () const inline
Definition at line 888 of file GameObject.h.
 { return m_lootGenerationTime; }
References m_lootGenerationTime.
Referenced by Player::SendLoot().
GetLootMode()
uint16 GameObject::GetLootMode () const inline
Definition at line 850 of file GameObject.h.
 { return m_LootMode; }
References m_LootMode.
Referenced by gobject_commandscript::HandleGameObjectInfoCommand(), and Player::SendLoot().
GetLootRecipient()
Player * GameObject::GetLootRecipient () const
Definition at line 2447 of file GameObject.cpp.
 {
     if (!m_lootRecipient)
         return nullptr;
     return ObjectAccessor::FindConnectedPlayer(m_lootRecipient);
 }
References ObjectAccessor::FindConnectedPlayer(), and m_lootRecipient.
GetLootRecipientGroup()
Group * GameObject::GetLootRecipientGroup () const
Definition at line 2454 of file GameObject.cpp.
 {
     if (!m_lootRecipientGroup)
         return nullptr;
     return sGroupMgr->GetGroupByGUID(m_lootRecipientGroup);
 }
References m_lootRecipientGroup, and sGroupMgr.
Referenced by IsLootAllowedFor().
getLootState()
LootState GameObject::getLootState () const inline
Definition at line 846 of file GameObject.h.
 { return m_lootState; }
References m_lootState.
Referenced by InstanceScript::DoUseDoorOrButton(), gobject_commandscript::HandleGameObjectInfoCommand(), Player::SendLoot(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), and Use().
GetNameForLocaleIdx()
std::string const & GameObject::GetNameForLocaleIdx (LocaleConstant locale_idx) const override virtual
Reimplemented from WorldObject.
Definition at line 2121 of file GameObject.cpp.
 {
     if (loc_idx != DEFAULT_LOCALE)
     {
         uint8 uloc_idx = uint8(loc_idx);
         if (GameObjectLocale const* cl = sObjectMgr->GetGameObjectLocale(GetEntry()))
             if (cl->Name.size() > uloc_idx && !cl->Name[uloc_idx].empty())
                 return cl->Name[uloc_idx];
     }
     return GetName();
 }
References DEFAULT_LOCALE, Object::GetEntry(), WorldObject::GetName(), and sObjectMgr.
GetOwner()
Unit * GameObject::GetOwner () const
Definition at line 1148 of file GameObject.cpp.
 {
     return ObjectAccessor::GetUnit(*this, GetOwnerGUID());
 }
References GetOwnerGUID(), and ObjectAccessor::GetUnit().
Referenced by CastSpell(), Spell::EffectOpenLock(), getLevelForTarget(), go_soulwell::go_soulwellAI::go_soulwellAI(), go_soulwell::go_soulwellAI::GossipHello(), IsAlwaysVisibleFor(), TriggeringLinkedGameObject(), Update(), and Use().
GetOwnerGUID()
ObjectGuid GameObject::GetOwnerGUID () const inline
Definition at line 794 of file GameObject.h.
 { return GetGuidValue(OBJECT_FIELD_CREATED_BY); }
References Object::GetGuidValue(), and OBJECT_FIELD_CREATED_BY.
Referenced by Unit::AddGameObject(), BuildValuesUpdate(), CheckRitualList(), WorldSession::DoLootRelease(), GetOwner(), SmartScript::GetTargets(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMoneyOpcode(), IsAlwaysVisibleFor(), RemoveFromOwner(), Unit::RemoveGameObject(), Player::SendLoot(), SetOwnerGUID(), Update(), and Use().
GetPackedLocalRotation()
int64 GameObject::GetPackedLocalRotation () const inline
Definition at line 772 of file GameObject.h.
 { return m_packedRotation; }
References m_packedRotation.
GetRespawnDelay()
uint32 GameObject::GetRespawnDelay () const inline
Definition at line 825 of file GameObject.h.
 { return m_respawnDelayTime; }
References m_respawnDelayTime.
Referenced by gobject_commandscript::HandleGameObjectTargetCommand(), and Player::SendLoot().
GetRespawnPosition()
void GameObject::GetRespawnPosition (float & x, float & y, float & z, float * ori = nullptr) const
Definition at line 2636 of file GameObject.cpp.
 {
     if (m_spawnId)
     {
         if (GameObjectData const* data = sObjectMgr->GetGOData(m_spawnId))
         {
             x = data->posX;
             y = data->posY;
             z = data->posZ;
             if (ori)
                 *ori = data->orientation;
             return;
         }
     }
     x = GetPositionX();
     y = GetPositionY();
     z = GetPositionZ();
     if (ori)
         *ori = GetOrientation();
 }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), m_spawnId, sObjectMgr, G3D::x, G3D::y, and G3D::z.
GetRespawnTime()
time_t GameObject::GetRespawnTime () const inline
Definition at line 804 of file GameObject.h.
 { return m_respawnTime; }
References m_respawnTime.
Referenced by spell_q9452_cast_net::CheckCast(), Spell::EffectDummy(), and Player::SendLoot().
GetRespawnTimeEx()
time_t GameObject::GetRespawnTimeEx () const inline
Definition at line 805 of file GameObject.h.
     {
         time_t now = time(nullptr);
         if (m_respawnTime > now)
             return m_respawnTime;
         else
             return now;
     }
References m_respawnTime.
Referenced by gobject_commandscript::HandleGameObjectTargetCommand().
GetScriptId()
uint32 GameObject::GetScriptId () const virtual
Definition at line 2112 of file GameObject.cpp.
 {
     if (GameObjectData const* gameObjectData = GetGOData())
         return gameObjectData->ScriptId;
     return GetGOInfo()->ScriptId;
 }
References GetGOData(), GetGOInfo(), and GameObjectTemplate::ScriptId.
Referenced by ScriptMgr::GetDialogStatus(), ScriptMgr::GetGameObjectAI(), WorldSession::HandleGossipSelectOptionOpcode(), ScriptMgr::OnAddCreaturePassenger(), ScriptMgr::OnAddPassenger(), ScriptMgr::OnGameObjectDamaged(), ScriptMgr::OnGameObjectDestroyed(), ScriptMgr::OnGameObjectLootStateChanged(), ScriptMgr::OnGameObjectStateChanged(), ScriptMgr::OnGameObjectUpdate(), ScriptMgr::OnGossipHello(), ScriptMgr::OnGossipSelect(), ScriptMgr::OnGossipSelectCode(), ScriptMgr::OnQuestAccept(), ScriptMgr::OnQuestReward(), ScriptMgr::OnRelocate(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnTransportUpdate(), and FactorySelector::SelectGameObjectAI().
GetSpawnId()
ObjectGuid::LowType GameObject::GetSpawnId () const inline
Definition at line 765 of file GameObject.h.
 { return m_spawnId; }
References m_spawnId.
Referenced by Create(), WorldSession::DoLootRelease(), SmartScript::GetScript(), gobject_commandscript::HandleGameObjectDeleteCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), OPvPCapturePoint::HandleOpenGo(), OutdoorPvP::OnGameObjectCreate(), and OutdoorPvP::OnGameObjectRemove().
GetSpellForLock()
SpellInfo const * GameObject::GetSpellForLock (Player const * player) const
Definition at line 2790 of file GameObject.cpp.
 {
     if (!player)
     {
         return nullptr;
     }
     uint32 lockId = GetGOInfo()->GetLockId();
     if (!lockId)
     {
         return nullptr;
     }
     LockEntry const* lock = sLockStore.LookupEntry(lockId);
     if (!lock)
     {
         return nullptr;
     }
     for (uint8 i = 0; i < MAX_LOCK_CASE; ++i)
     {
         if (!lock->Type[i])
         {
             continue;
         }
         if (lock->Type[i] == LOCK_KEY_SPELL)
         {
             if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(lock->Index[i]))
             {
                 return spell;
             }
         }
         if (lock->Type[i] != LOCK_KEY_SKILL)
         {
             break;
         }
         for (auto&& playerSpell : player->GetSpellMap())
         {
             if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(playerSpell.first))
             {
                 for (auto&& effect : spell->Effects)
                 {
                     if (effect.Effect == SPELL_EFFECT_OPEN_LOCK && ((uint32) effect.MiscValue) == lock->Index[i])
                     {
                         if (effect.CalcValue(player) >= int32(lock->Skill[i]))
{
                             return spell;
                         }
                     }
                 }
             }
         }
     }
     return nullptr;
 }
References GetGOInfo(), GameObjectTemplate::GetLockId(), Player::GetSpellMap(), LockEntry::Index, LOCK_KEY_SKILL, LOCK_KEY_SPELL, MAX_LOCK_CASE, LockEntry::Skill, sLockStore, SPELL_EFFECT_OPEN_LOCK, sSpellMgr, and LockEntry::Type.
Referenced by IsAtInteractDistance().
GetSpellId()
uint32 GameObject::GetSpellId () const inline
Definition at line 802 of file GameObject.h.
 { return m_spellId;}
References m_spellId.
Referenced by Unit::AddGameObject(), Unit::RemoveGameObject(), and Update().
GetStationaryO()
float GameObject::GetStationaryO () const inline override virtual
Reimplemented from WorldObject.
Definition at line 965 of file GameObject.h.
 { if (GetGOInfo()->type != GAMEOBJECT_TYPE_MO_TRANSPORT) return m_stationaryPosition.GetOrientation(); return GetOrientation(); }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetOrientation(), and m_stationaryPosition.
Referenced by StaticTransport::RelocateToProgress().
GetStationaryX()
float GameObject::GetStationaryX () const inline override virtual
Reimplemented from WorldObject.
Definition at line 962 of file GameObject.h.
 { if (GetGOInfo()->type != GAMEOBJECT_TYPE_MO_TRANSPORT) return m_stationaryPosition.GetPositionX(); return GetPositionX(); }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionX(), and m_stationaryPosition.
Referenced by StaticTransport::RelocateToProgress().
GetStationaryY()
float GameObject::GetStationaryY () const inline override virtual
Reimplemented from WorldObject.
Definition at line 963 of file GameObject.h.
 { if (GetGOInfo()->type != GAMEOBJECT_TYPE_MO_TRANSPORT) return m_stationaryPosition.GetPositionY(); return GetPositionY(); }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionY(), and m_stationaryPosition.
Referenced by StaticTransport::RelocateToProgress().
GetStationaryZ()
float GameObject::GetStationaryZ () const inline override virtual
Reimplemented from WorldObject.
Definition at line 964 of file GameObject.h.
 { if (GetGOInfo()->type != GAMEOBJECT_TYPE_MO_TRANSPORT) return m_stationaryPosition.GetPositionZ(); return GetPositionZ(); }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionZ(), and m_stationaryPosition.
Referenced by StaticTransport::RelocateToProgress().
GetTemplateAddon()
GameObjectTemplateAddon const * GameObject::GetTemplateAddon () const
Definition at line 822 of file GameObject.cpp.
 {
     return sObjectMgr->GetGameObjectTemplateAddon(GetGOInfo()->entry);
 }
References GetGOInfo(), and sObjectMgr.
Referenced by CastSpell(), Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), Delete(), DespawnOrUnsummon(), Player::SendLoot(), and Update().
GetUniqueUseCount()
uint32 GameObject::GetUniqueUseCount () const inline
Definition at line 872 of file GameObject.h.
 { return m_unique_users.size(); }
References m_unique_users.
Referenced by Update(), and Use().
GetUseCount()
uint32 GameObject::GetUseCount () const inline
Definition at line 871 of file GameObject.h.
 { return m_usetimes; }
References m_usetimes.
Referenced by WorldSession::DoLootRelease().
GetWorldRotation()
G3D::Quat GameObject::GetWorldRotation () const
Definition at line 2174 of file GameObject.cpp.
 {
     G3D::Quat localRotation = GetLocalRotation();
     if (Transport* transport = GetTransport())
     {
         G3D::Quat worldRotation = transport->GetWorldRotation();
         G3D::Quat worldRotationQuat(worldRotation.x, worldRotation.y, worldRotation.z, worldRotation.w);
         G3D::Quat localRotationQuat(localRotation.x, localRotation.y, localRotation.z, localRotation.w);
         G3D::Quat resultRotation = localRotationQuat * worldRotationQuat;
         return G3D::Quat(resultRotation.x, resultRotation.y, resultRotation.z, resultRotation.w);
     }
     return localRotation;
 }
References GetLocalRotation(), WorldObject::GetTransport(), G3D::Quat::w, G3D::Quat::x, G3D::Quat::y, and G3D::Quat::z.
Referenced by IsAtInteractDistance().
hasInvolvedQuest()
bool GameObject::hasInvolvedQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1125 of file GameObject.cpp.
 {
     QuestRelationBounds qir = sObjectMgr->GetGOQuestInvolvedRelationBounds(GetEntry());
     for (QuestRelations::const_iterator itr = qir.first; itr != qir.second; ++itr)
     {
         if (itr->second == quest_id)
             return true;
     }
     return false;
 }
References Object::GetEntry(), and sObjectMgr.
HasLootMode()
bool GameObject::HasLootMode (uint16 lootMode) const inline
Definition at line 851 of file GameObject.h.
 { return m_LootMode & lootMode; }
References m_LootMode.
HasLootRecipient()
bool GameObject::HasLootRecipient () const inline
Definition at line 884 of file GameObject.h.
 { return m_lootRecipient || m_lootRecipientGroup; }
References m_lootRecipient, and m_lootRecipientGroup.
Referenced by BuildValuesUpdate().
hasQuest()
bool GameObject::hasQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1114 of file GameObject.cpp.
 {
     QuestRelationBounds qr = sObjectMgr->GetGOQuestRelationBounds(GetEntry());
     for (QuestRelations::const_iterator itr = qr.first; itr != qr.second; ++itr)
     {
         if (itr->second == quest_id)
             return true;
     }
     return false;
 }
References Object::GetEntry(), qr, and sObjectMgr.
IsAlwaysVisibleFor()
bool GameObject::IsAlwaysVisibleFor (WorldObject const * seer) const override virtual
Reimplemented from WorldObject.
Definition at line 1173 of file GameObject.cpp.
 {
     if (WorldObject::IsAlwaysVisibleFor(seer))
         return true;
     if (IsTransport() || IsDestructibleBuilding())
         return true;
     if (!seer)
         return false;
     // Always seen by owner and friendly units
     if (ObjectGuid guid = GetOwnerGUID())
     {
         if (seer->GetGUID() == guid)
             return true;
         Unit* owner = GetOwner();
         if (owner)
         {
             if (seer->isType(TYPEMASK_UNIT) && owner->IsFriendlyTo(seer->ToUnit()))
                 return true;
         }
     }
     return false;
 }
References Object::GetGUID(), GetOwner(), GetOwnerGUID(), WorldObject::IsAlwaysVisibleFor(), IsDestructibleBuilding(), Unit::IsFriendlyTo(), IsTransport(), Object::isType(), Object::ToUnit(), and TYPEMASK_UNIT.
IsAtInteractDistance() [1/2]
bool GameObject::IsAtInteractDistance (Player const * player, SpellInfo const * spell = nullptr) const
Definition at line 2743 of file GameObject.cpp.
 {
     if (spell || (spell = GetSpellForLock(player)))
     {
         float maxRange = spell->GetMaxRange(spell->IsPositive());
         if (GetGoType() == GAMEOBJECT_TYPE_SPELL_FOCUS)
         {
             return maxRange * maxRange >= GetExactDistSq(player);
         }
         if (sGameObjectDisplayInfoStore.LookupEntry(GetGOInfo()->displayId))
         {
             return IsAtInteractDistance(*player, maxRange);
         }
     }
     return IsAtInteractDistance(*player, GetInteractionDistance());
 }
References GAMEOBJECT_TYPE_SPELL_FOCUS, Position::GetExactDistSq(), GetGOInfo(), GetGoType(), GetInteractionDistance(), SpellInfo::GetMaxRange(), GetSpellForLock(), IsAtInteractDistance(), SpellInfo::IsPositive(), and sGameObjectDisplayInfoStore.
IsAtInteractDistance() [2/2]
bool GameObject::IsAtInteractDistance (Position const & pos, float radius) const
Definition at line 2763 of file GameObject.cpp.
 {
     if (GameObjectDisplayInfoEntry const* displayInfo = sGameObjectDisplayInfoStore.LookupEntry(GetGOInfo()->displayId))
     {
         float scale = GetObjectScale();
         float minX = displayInfo->minX * scale - radius;
         float minY = displayInfo->minY * scale - radius;
         float minZ = displayInfo->minZ * scale - radius;
         float maxX = displayInfo->maxX * scale + radius;
         float maxY = displayInfo->maxY * scale + radius;
         float maxZ = displayInfo->maxZ * scale + radius;
         G3D::Quat worldRotation = GetWorldRotation();
         G3D::Quat worldRotationQuat(worldRotation.x, worldRotation.y, worldRotation.z, worldRotation.w);
         return G3D::CoordinateFrame {{worldRotationQuat}, {GetPositionX(), GetPositionY(), GetPositionZ()}}.toWorldSpace(G3D::Box {{minX, minY, minZ}, {maxX, maxY, maxZ}}).contains({pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ()});
     }
     return GetExactDist(&pos) <= radius;
 }
References contains(), Position::GetExactDist(), GetGOInfo(), Object::GetObjectScale(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetWorldRotation(), pos(), sGameObjectDisplayInfoStore, G3D::Quat::w, G3D::Quat::x, G3D::Quat::y, and G3D::Quat::z.
Referenced by IsAtInteractDistance(), and IsWithinDistInMap().
IsDestructibleBuilding()
bool GameObject::IsDestructibleBuilding () const
Definition at line 1141 of file GameObject.cpp.
 {
     GameObjectTemplate const* gInfo = GetGOInfo();
     if (!gInfo) return false;
     return gInfo->type == GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING;
 }
References GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetGOInfo(), and GameObjectTemplate::type.
Referenced by IsAlwaysVisibleFor(), and ModifyHealth().
IsInRange()
bool GameObject::IsInRange (float x, float y, float z, float radius) const
Check if the distance between the 2 objects is 0, can happen if both objects are on the same position. The code below this check wont crash if dist is 0 because 0/0 in float operations is valid, and returns infinite
Definition at line 2063 of file GameObject.cpp.
 {
     GameObjectDisplayInfoEntry const* info = sGameObjectDisplayInfoStore.LookupEntry(m_goInfo->displayId);
     if (!info)
         return IsWithinDist3d(x, y, z, radius);
     float sinA = sin(GetOrientation());
     float cosA = cos(GetOrientation());
     float dx = x - GetPositionX();
     float dy = y - GetPositionY();
     float dz = z - GetPositionZ();
     float dist = sqrt(dx * dx + dy * dy);
     if (G3D::fuzzyEq(dist, 0.0f))
         return true;
     float scale = GetObjectScale();
     float sinB = dx / dist;
     float cosB = dy / dist;
     dx = dist * (cosA * cosB + sinA * sinB);
     dy = dist * (cosA * sinB - sinA * cosB);
     return dx < (info->maxX * scale) + radius && dx > (info->minX * scale) - radius
            && dy < (info->maxY * scale) + radius && dy > (info->minY * scale) - radius
            && dz < (info->maxZ * scale) + radius && dz > (info->minZ * scale) - radius;
 }
References GameObjectTemplate::displayId, G3D::fuzzyEq(), Object::GetObjectScale(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::IsWithinDist3d(), m_goInfo, GameObjectDisplayInfoEntry::maxX, GameObjectDisplayInfoEntry::maxY, GameObjectDisplayInfoEntry::maxZ, GameObjectDisplayInfoEntry::minX, GameObjectDisplayInfoEntry::minY, GameObjectDisplayInfoEntry::minZ, sGameObjectDisplayInfoStore, G3D::x, G3D::y, and G3D::z.
Referenced by _IsWithinDist(), Acore::GameObjectInRangeCheck::operator()(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), and Acore::WorldObjectSpellAreaTargetCheck::operator()().
IsInSkillupList()
bool GameObject::IsInSkillupList (ObjectGuid playerGuid) const inline
Definition at line 858 of file GameObject.h.
     {
         for (ObjectGuid const& guid : m_SkillupList)
             if (guid == playerGuid)
                 return true;
         return false;
     }
References m_SkillupList.
Referenced by Spell::EffectOpenLock().
IsInvisibleDueToDespawn()
bool GameObject::IsInvisibleDueToDespawn () const override virtual
Reimplemented from WorldObject.
Definition at line 1201 of file GameObject.cpp.
 {
     if (WorldObject::IsInvisibleDueToDespawn())
         return true;
     // Despawned
     if (!isSpawned())
         return true;
     return false;
 }
References WorldObject::IsInvisibleDueToDespawn(), and isSpawned().
IsLootAllowedFor()
bool GameObject::IsLootAllowedFor (Player const * player) const
Definition at line 2517 of file GameObject.cpp.
 {
     if (!m_lootRecipient && !m_lootRecipientGroup)
         return true;
     if (player->GetGUID() == m_lootRecipient)
         return true;
     if (player->HasPendingBind())
         return false;
     Group const* playerGroup = player->GetGroup();
     if (!playerGroup || playerGroup != GetLootRecipientGroup()) // if we dont have a group we arent the recipient
         return false;                                           // if go doesnt have group bound it means it was solo killed by someone else
     return true;
 }
References Player::GetGroup(), Object::GetGUID(), GetLootRecipientGroup(), Player::HasPendingBind(), m_lootRecipient, and m_lootRecipientGroup.
Referenced by BuildValuesUpdate().
IsMotionTransport()
bool GameObject::IsMotionTransport () const inline
Definition at line 951 of file GameObject.h.
 { return GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT; }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), and GameObjectTemplate::type.
IsNeverVisible()
bool GameObject::IsNeverVisible () const override virtual
Reimplemented from WorldObject.
Definition at line 1162 of file GameObject.cpp.
 {
     if (WorldObject::IsNeverVisible())
         return true;
     if (GetGoType() == GAMEOBJECT_TYPE_SPELL_FOCUS && GetGOInfo()->spellFocus.serverOnly == 1)
         return true;
     return false;
 }
References GAMEOBJECT_TYPE_SPELL_FOCUS, GetGOInfo(), GetGoType(), WorldObject::IsNeverVisible(), and GameObjectTemplate::serverOnly.
isSpawned()
bool GameObject::isSpawned () const inline
Definition at line 817 of file GameObject.h.
     {
         return m_respawnDelayTime == 0 ||
                (m_respawnTime > 0 && !m_spawnedByDefault) ||
                (m_respawnTime == 0 && m_spawnedByDefault);
     }
References m_respawnDelayTime, m_respawnTime, and m_spawnedByDefault.
Referenced by spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), SmartGameObjectAI::InitializeAI(), IsInvisibleDueToDespawn(), GameObjectModelOwnerImpl::IsSpawned(), Acore::NearestGameObjectFishingHole::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::GameObjectFocusCheck::operator()(), Refresh(), Map::ScriptsProcess(), Spell::SendLoot(), Update(), and go_tadpole_cage::go_tadpole_cageAI::UpdateAI().
isSpawnedByDefault()
bool GameObject::isSpawnedByDefault () const inline
Definition at line 823 of file GameObject.h.
 { return m_spawnedByDefault; }
References m_spawnedByDefault.
Referenced by GameEventMgr::GameEventSpawn(), Player::SendLoot(), PoolGroup< T >::Spawn1Object(), and Update().
IsStaticTransport()
bool GameObject::IsStaticTransport () const inline
Definition at line 950 of file GameObject.h.
 { return GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT; }
References GAMEOBJECT_TYPE_TRANSPORT, GetGOInfo(), and GameObjectTemplate::type.
IsTransport()
bool GameObject::IsTransport () const
Definition at line 1136 of file GameObject.cpp.
 {
     return GetGOInfo() && (GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT || GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT);
 }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_TRANSPORT, GetGOInfo(), and GameObjectTemplate::type.
Referenced by AddToWorld(), GameObjectModelOwnerImpl::GetPhaseMask(), IsAlwaysVisibleFor(), and SetGoState().
IsWithinDistInMap() [1/2]
bool GameObject::IsWithinDistInMap (Player const * player) const
Definition at line 2785 of file GameObject.cpp.
 {
     return IsInMap(player) && InSamePhase(player) && IsAtInteractDistance(player);
 }
References WorldObject::InSamePhase(), IsAtInteractDistance(), and WorldObject::IsInMap().
Referenced by WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleLootMoneyOpcode(), Acore::GameObjectFocusCheck::operator()(), Player::SendLoot(), BfCapturePoint::Update(), and OPvPCapturePoint::Update().
IsWithinDistInMap() [2/2]
bool WorldObject::IsWithinDistInMap
Definition at line 749 of file Object.cpp.
 {
     return obj && IsInMap(obj) && InSamePhase(obj) && _IsWithinDist(obj, dist2compare, is3D, useBoundingRadius);
 }
LoadFromDB()
bool GameObject::LoadFromDB (ObjectGuid::LowType guid, Map * map) inline
Definition at line 780 of file GameObject.h.
 { return LoadGameObjectFromDB(guid, map, false); }
References LoadGameObjectFromDB().
Referenced by LoadHelper().
LoadGameObjectFromDB()
bool GameObject::LoadGameObjectFromDB (ObjectGuid::LowType guid, Map * map, bool addToMap = true)
Definition at line 1032 of file GameObject.cpp.
 {
     GameObjectData const* data = sObjectMgr->GetGOData(spawnId);
     if (!data)
     {
         LOG_ERROR("sql.sql", "Gameobject (GUID: %u) not found in table `gameobject`, can't load. ", spawnId);
         return false;
     }
     uint32 entry = data->id;
     //uint32 map_id = data->mapid;                          // already used before call
     uint32 phaseMask = data->phaseMask;
     float x = data->posX;
     float y = data->posY;
     float z = data->posZ;
     float ang = data->orientation;
     uint32 animprogress = data->animprogress;
     GOState go_state = data->go_state;
     uint32 artKit = data->artKit;
     m_spawnId = spawnId;
     if (!Create(map->GenerateLowGuid<HighGuid::GameObject>(), entry, map, phaseMask, x, y, z, ang, data->rotation, animprogress, go_state, artKit))
         return false;
     if (data->spawntimesecs >= 0)
     {
         m_spawnedByDefault = true;
         if (!GetGOInfo()->GetDespawnPossibility() && !GetGOInfo()->IsDespawnAtAction())
         {
             SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NODESPAWN);
             m_respawnDelayTime = 0;
             m_respawnTime = 0;
         }
         else
         {
             m_respawnDelayTime = data->spawntimesecs;
             m_respawnTime = GetMap()->GetGORespawnTime(m_spawnId);
             // ready to respawn
             if (m_respawnTime && m_respawnTime <= time(nullptr))
             {
                 m_respawnTime = 0;
                 GetMap()->RemoveGORespawnTime(m_spawnId);
             }
         }
     }
     else
     {
         m_spawnedByDefault = false;
         m_respawnDelayTime = -data->spawntimesecs;
         m_respawnTime = 0;
     }
     m_goData = data;
     if (addToMap && !GetMap()->AddToMap(this))
         return false;
     return true;
 }
References Create(), GameObject, GAMEOBJECT_FLAGS, Map::GenerateLowGuid(), GetGOInfo(), Map::GetGORespawnTime(), WorldObject::GetMap(), GO_FLAG_NODESPAWN, LOG_ERROR, m_goData, m_respawnDelayTime, m_respawnTime, m_spawnedByDefault, m_spawnId, Map::RemoveGORespawnTime(), Object::SetFlag(), sObjectMgr, G3D::x, G3D::y, and G3D::z.
Referenced by ObjectMgr::AddGOData(), MotionTransport::CreateGOPassenger(), GameEventMgr::GameEventSpawn(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), LoadFromDB(), and PoolGroup< T >::Spawn1Object().
LookupFishingHoleAround()
GameObject * GameObject::LookupFishingHoleAround (float range)
Definition at line 1318 of file GameObject.cpp.
 {
     GameObject* ok = nullptr;
     Acore::NearestGameObjectFishingHole u_check(*this, range);
     Acore::GameObjectSearcher<Acore::NearestGameObjectFishingHole> checker(this, ok, u_check);
     Cell::VisitGridObjects(this, checker, range);
     return ok;
 }
References Cell::VisitGridObjects().
Referenced by Use().
ModifyHealth()
void GameObject::ModifyHealth (int32 change, Unit * attackerOrHealer = nullptr, uint32 spellId = 0)
Definition at line 2191 of file GameObject.cpp.
 {
     if (!IsDestructibleBuilding())
         return;
     if (!m_goValue.Building.MaxHealth || !change)
         return;
     if (!m_allowModifyDestructibleBuilding)
         change = 0;
     // prevent double destructions of the same object
     if (change < 0 && !m_goValue.Building.Health)
         return;
     if (int32(m_goValue.Building.Health) + change <= 0)
         m_goValue.Building.Health = 0;
     else if (int32(m_goValue.Building.Health) + change >= int32(m_goValue.Building.MaxHealth))
         m_goValue.Building.Health = m_goValue.Building.MaxHealth;
     else
         m_goValue.Building.Health += change;
     // Set the health bar, value = 255 * healthPct;
     SetGoAnimProgress(m_goValue.Building.Health * 255 / m_goValue.Building.MaxHealth);
     Player* player = attackerOrHealer->GetCharmerOrOwnerPlayerOrPlayerItself();
     // dealing damage, send packet
     // TODO: is there any packet for healing?
     if (player)
     {
         WorldPacket data(SMSG_DESTRUCTIBLE_BUILDING_DAMAGE, 8 + 8 + 8 + 4 + 4);
         data << GetPackGUID();
         data << attackerOrHealer->GetPackGUID();
         data << player->GetPackGUID();
         data << uint32(-change);                    // change  < 0 triggers SPELL_BUILDING_HEAL combat log event
         // change >= 0 triggers SPELL_BUILDING_DAMAGE event
         data << uint32(spellId);
         player->GetSession()->SendPacket(&data);
     }
     GameObjectDestructibleState newState = GetDestructibleState();
     if (!m_goValue.Building.Health)
         newState = GO_DESTRUCTIBLE_DESTROYED;
     else if (m_goValue.Building.Health <= GetGOInfo()->building.damagedNumHits)
         newState = GO_DESTRUCTIBLE_DAMAGED;
     else if (m_goValue.Building.Health == m_goValue.Building.MaxHealth)
         newState = GO_DESTRUCTIBLE_INTACT;
     if (newState == GetDestructibleState())
         return;
     SetDestructibleState(newState, player, false);
 }
References GameObjectValue::Building, GameObjectTemplate::damagedNumHits, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), GetDestructibleState(), GetGOInfo(), Object::GetPackGUID(), Player::GetSession(), GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_INTACT, GameObjectValue::Health, IsDestructibleBuilding(), m_allowModifyDestructibleBuilding, m_goValue, GameObjectValue::MaxHealth, WorldSession::SendPacket(), SetDestructibleState(), SetGoAnimProgress(), and SMSG_DESTRUCTIBLE_BUILDING_DAMAGE.
Referenced by Spell::EffectGameObjectDamage(), and Spell::EffectGameObjectRepair().
Refresh()
void GameObject::Refresh ()
Definition at line 827 of file GameObject.cpp.
 {
     // not refresh despawned not casted GO (despawned casted GO destroyed in all cases anyway)
     if (m_respawnTime > 0 && m_spawnedByDefault)
         return;
     if (isSpawned())
         GetMap()->AddToMap(this);
 }
References Map::AddToMap(), WorldObject::GetMap(), isSpawned(), m_respawnTime, and m_spawnedByDefault.
Referenced by BattlegroundSA::ResetObjs().
RemoveFromOwner()
void GameObject::RemoveFromOwner () private
Definition at line 124 of file GameObject.cpp.
 {
     ObjectGuid ownerGUID = GetOwnerGUID();
     if (!ownerGUID)
         return;
     if (Unit* owner = ObjectAccessor::GetUnit(*this, ownerGUID))
     {
         owner->RemoveGameObject(this, false);
         ASSERT(!GetOwnerGUID());
         return;
     }
     LOG_FATAL("entities.gameobject", "Delete GameObject (%s Entry: %u SpellId %u LinkedGO %u) that lost references to owner %s GO list. Crash possible later.",
         GetGUID().ToString().c_str(), GetGOInfo()->entry, m_spellId, GetGOInfo()->GetLinkedGameObjectEntry(), ownerGUID.ToString().c_str());
     SetOwnerGUID(ObjectGuid::Empty);
 }
References ASSERT, ObjectGuid::Empty, GetGOInfo(), Object::GetGUID(), GetOwnerGUID(), ObjectAccessor::GetUnit(), LOG_FATAL, m_spellId, SetOwnerGUID(), Position::ToString(), and ObjectGuid::ToString().
Referenced by CleanupsBeforeDelete(), Delete(), RemoveFromWorld(), and Use().
RemoveFromWorld()
void GameObject::RemoveFromWorld () override virtual
Remove the gameobject from the accessor
Reimplemented from Object.
Definition at line 170 of file GameObject.cpp.
 {
     if (IsInWorld())
     {
 #ifdef ELUNA
         sEluna->OnRemoveFromWorld(this);
 #endif
         if (m_zoneScript)
             m_zoneScript->OnGameObjectRemove(this);
         RemoveFromOwner();
         if (m_model)
             if (GetMap()->ContainsGameObjectModel(*m_model))
                 GetMap()->RemoveGameObjectModel(*m_model);
         if (Transport* transport = GetTransport())
             transport->RemovePassenger(this, true);
         // If linked trap exists, despawn it
         if (GameObject* linkedTrap = GetLinkedTrap())
         {
             linkedTrap->Delete();
         }
         WorldObject::RemoveFromWorld();
         if (m_spawnId)
             Acore::Containers::MultimapErasePair(GetMap()->GetGameObjectBySpawnIdStore(), m_spawnId, this);
         GetMap()->GetObjectsStore().Remove<GameObject>(GetGUID());
     }
 }
References Object::GetGUID(), GetLinkedTrap(), WorldObject::GetMap(), Map::GetObjectsStore(), WorldObject::GetTransport(), Object::IsInWorld(), m_model, m_spawnId, WorldObject::m_zoneScript, Acore::Containers::MultimapErasePair(), ZoneScript::OnGameObjectRemove(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), RemoveFromOwner(), WorldObject::RemoveFromWorld(), and Map::RemoveGameObjectModel().
Referenced by CleanupsBeforeDelete(), BattlegroundIC::PostUpdateImpl(), Map::RemoveFromMap(), and Map::UnloadAll().
RemoveLootMode()
void GameObject::RemoveLootMode (uint16 lootMode) inline
Definition at line 854 of file GameObject.h.
 { m_LootMode &= ~lootMode; }
References m_LootMode.
ResetDoorOrButton()
void GameObject::ResetDoorOrButton ()
Definition at line 1329 of file GameObject.cpp.
 {
     if (m_lootState == GO_READY || m_lootState == GO_JUST_DEACTIVATED)
         return;
     SwitchDoorOrButton(false);
     SetLootState(GO_JUST_DEACTIVATED);
     m_cooldownTime = 0;
 }
References GO_JUST_DEACTIVATED, GO_READY, m_cooldownTime, m_lootState, SetLootState(), and SwitchDoorOrButton().
Referenced by InstanceScript::DoUseDoorOrButton(), go_bristlelimb_cage::OnGossipHello(), FrozenThroneResetWorker::operator()(), Update(), and npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI().
ResetLootMode()
void GameObject::ResetLootMode () inline
Definition at line 855 of file GameObject.h.
 { m_LootMode = LOOT_MODE_DEFAULT; }
References LOOT_MODE_DEFAULT, and m_LootMode.
Referenced by GameObject().
Respawn()
void GameObject::Respawn ()
Definition at line 1228 of file GameObject.cpp.
 {
     if (m_spawnedByDefault && m_respawnTime > 0)
     {
         m_respawnTime = time(nullptr);
         GetMap()->RemoveGORespawnTime(m_spawnId);
     }
 }
References WorldObject::GetMap(), m_respawnTime, m_spawnedByDefault, m_spawnId, and Map::RemoveGORespawnTime().
Referenced by Acore::RespawnDo::operator()().
SaveRespawnTime() [1/2]
void GameObject::SaveRespawnTime () inline override virtual
Reimplemented from WorldObject.
Definition at line 874 of file GameObject.h.
 { SaveRespawnTime(0); }
References SaveRespawnTime().
Referenced by Map::RemoveFromMap(), SaveRespawnTime(), and Update().
SaveRespawnTime() [2/2]
void GameObject::SaveRespawnTime (uint32 forceDelay)
Definition at line 1153 of file GameObject.cpp.
 {
     if (m_goData && m_goData->dbData && (forceDelay || m_respawnTime > time(nullptr)) && m_spawnedByDefault)
     {
         time_t respawnTime = forceDelay ? time(nullptr) + forceDelay : m_respawnTime;
         GetMap()->SaveGORespawnTime(m_spawnId, respawnTime);
     }
 }
References GameObjectData::dbData, WorldObject::GetMap(), m_goData, m_respawnTime, m_spawnedByDefault, m_spawnId, and Map::SaveGORespawnTime().
SaveToDB() [1/2]
void GameObject::SaveToDB (bool saveAddon = false)
Definition at line 952 of file GameObject.cpp.
 {
     // this should only be used when the gameobject has already been loaded
     // preferably after adding to map, because mapid may not be valid otherwise
     GameObjectData const* data = sObjectMgr->GetGOData(m_spawnId);
     if (!data)
     {
         LOG_ERROR("entities.gameobject", "GameObject::SaveToDB failed, cannot get gameobject data!");
         return;
     }
     SaveToDB(GetMapId(), data->spawnMask, data->phaseMask, saveAddon);
 }
References WorldLocation::GetMapId(), LOG_ERROR, m_spawnId, and sObjectMgr.
SaveToDB() [2/2]
void GameObject::SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask, bool saveAddon = false)
Definition at line 966 of file GameObject.cpp.
 {
     const GameObjectTemplate* goI = GetGOInfo();
     if (!goI)
         return;
     if (!m_spawnId)
         m_spawnId = sObjectMgr->GenerateGameObjectSpawnId();
     // update in loaded data (changing data only in this place)
     GameObjectData& data = sObjectMgr->NewGOData(m_spawnId);
     data.id = GetEntry();
     data.mapid = mapid;
     data.phaseMask = phaseMask;
     data.posX = GetPositionX();
     data.posY = GetPositionY();
     data.posZ = GetPositionZ();
     data.orientation = GetOrientation();
     data.rotation = m_localRotation;
     data.spawntimesecs = m_spawnedByDefault ? m_respawnDelayTime : -(int32)m_respawnDelayTime;
     data.animprogress = GetGoAnimProgress();
     data.go_state = GetGoState();
     data.spawnMask = spawnMask;
     data.artKit = GetGoArtKit();
     // Update in DB
     WorldDatabaseTransaction trans = WorldDatabase.BeginTransaction();
     uint8 index = 0;
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_GAMEOBJECT);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_GAMEOBJECT);
     stmt->setUInt32(index++, m_spawnId);
     stmt->setUInt32(index++, GetEntry());
     stmt->setUInt16(index++, uint16(mapid));
     stmt->setUInt8(index++, spawnMask);
     stmt->setUInt32(index++, GetPhaseMask());
     stmt->setFloat(index++, GetPositionX());
     stmt->setFloat(index++, GetPositionY());
     stmt->setFloat(index++, GetPositionZ());
     stmt->setFloat(index++, GetOrientation());
     stmt->setFloat(index++, m_localRotation.x);
     stmt->setFloat(index++, m_localRotation.y);
     stmt->setFloat(index++, m_localRotation.z);
     stmt->setFloat(index++, m_localRotation.w);
     stmt->setInt32(index++, int32(m_respawnDelayTime));
     stmt->setUInt8(index++, GetGoAnimProgress());
     stmt->setUInt8(index++, uint8(GetGoState()));
     trans->Append(stmt);
     if (saveAddon && !sObjectMgr->GetGameObjectAddon(m_spawnId))
     {
         index = 0;
         stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_GAMEOBJECT_ADDON);
         stmt->setUInt32(index++, m_spawnId);
         trans->Append(stmt);
     }
     WorldDatabase.CommitTransaction(trans);
 }
References Object::GetEntry(), GetGoAnimProgress(), GetGoArtKit(), GetGOInfo(), GetGoState(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), index, m_localRotation, m_respawnDelayTime, m_spawnedByDefault, m_spawnId, PreparedStatementBase::setFloat(), PreparedStatementBase::setInt32(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sObjectMgr, G3D::Quat::w, WORLD_DEL_GAMEOBJECT, WORLD_INS_GAMEOBJECT, WORLD_INS_GAMEOBJECT_ADDON, WorldDatabase, G3D::Quat::x, G3D::Quat::y, and G3D::Quat::z.
SendCustomAnim()
void GameObject::SendCustomAnim (uint32 anim)
Definition at line 2055 of file GameObject.cpp.
 {
     WorldPacket data(SMSG_GAMEOBJECT_CUSTOM_ANIM, 8 + 4);
     data << GetGUID();
     data << uint32(anim);
     SendMessageToSet(&data, true);
 }
References Object::GetGUID(), WorldObject::SendMessageToSet(), and SMSG_GAMEOBJECT_CUSTOM_ANIM.
Referenced by spell_banging_the_gong::spell_banging_the_gong_SpellScript::Activate(), Spell::EffectDummy(), go_gong_of_bethekk::OnGossipHello(), brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul(), Update(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), and Use().
SendMessageToSetInRange()
void GameObject::SendMessageToSetInRange (WorldPacket * data, float dist, bool , bool includeMargin = false, Player const * skipped_rcvr = nullptr) override virtual
Reimplemented from WorldObject.
Definition at line 2091 of file GameObject.cpp.
 {
     dist += GetObjectSize();
     if (includeMargin)
         dist += VISIBILITY_COMPENSATION * 2.0f; // pussywizard: to ensure everyone receives all important packets
     Acore::MessageDistDeliverer notifier(this, data, dist, false, skipped_rcvr);
     Cell::VisitWorldObjects(this, notifier, dist);
 }
References WorldObject::GetObjectSize(), VISIBILITY_COMPENSATION, and Cell::VisitWorldObjects().
SetDestructibleBuildingModifyState()
void GameObject::SetDestructibleBuildingModifyState (bool allow) inline
Definition at line 923 of file GameObject.h.
 { m_allowModifyDestructibleBuilding = allow; }
References m_allowModifyDestructibleBuilding.
SetDestructibleState()
void GameObject::SetDestructibleState (GameObjectDestructibleState state, Player * eventInvoker = nullptr, bool setHealth = false)
Definition at line 2247 of file GameObject.cpp.
 {
     // the user calling this must know he is already operating on destructible gameobject
     ASSERT(GetGoType() == GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING);
     switch (state)
     {
         case GO_DESTRUCTIBLE_INTACT:
             RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED | GO_FLAG_DESTROYED);
             SetDisplayId(m_goInfo->displayId);
             if (setHealth)
             {
                 m_goValue.Building.Health = m_goValue.Building.MaxHealth;
                 SetGoAnimProgress(255);
             }
             EnableCollision(true);
             break;
         case GO_DESTRUCTIBLE_DAMAGED:
             {
 #ifdef ELUNA
                 sEluna->OnDamaged(this, eventInvoker);
 #endif
                 EventInform(m_goInfo->building.damagedEvent);
                 sScriptMgr->OnGameObjectDamaged(this, eventInvoker);
                 if (BattlegroundMap* bgMap = GetMap()->ToBattlegroundMap())
                     if (Battleground* bg = bgMap->GetBG())
                         bg->EventPlayerDamagedGO(eventInvoker, this, m_goInfo->building.damagedEvent);
                 RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_DESTROYED);
                 SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED);
                 uint32 modelId = m_goInfo->building.damagedDisplayId;
                 if (DestructibleModelDataEntry const* modelData = sDestructibleModelDataStore.LookupEntry(m_goInfo->building.destructibleData))
                     if (modelData->DamagedDisplayId)
                         modelId = modelData->DamagedDisplayId;
                 SetDisplayId(modelId);
                 if (setHealth)
                 {
                     m_goValue.Building.Health = m_goInfo->building.damagedNumHits;
                     uint32 maxHealth = m_goValue.Building.MaxHealth;
                     // in this case current health is 0 anyway so just prevent crashing here
                     if (!maxHealth)
                         maxHealth = 1;
                     SetGoAnimProgress(m_goValue.Building.Health * 255 / maxHealth);
                 }
                 break;
             }
         case GO_DESTRUCTIBLE_DESTROYED:
             {
 #ifdef ELUNA
                 sEluna->OnDestroyed(this, eventInvoker);
 #endif
                 sScriptMgr->OnGameObjectDestroyed(this, eventInvoker);
                 EventInform(m_goInfo->building.destroyedEvent);
                 if (BattlegroundMap* bgMap = GetMap()->ToBattlegroundMap())
                 {
                     if (Battleground* bg = bgMap->GetBG())
                     {
                         bg->EventPlayerDamagedGO(eventInvoker, this, m_goInfo->building.destroyedEvent);
                         bg->DestroyGate(eventInvoker, this);
                     }
                 }
                 RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED);
                 SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_DESTROYED);
                 uint32 modelId = m_goInfo->building.destroyedDisplayId;
                 if (DestructibleModelDataEntry const* modelData = sDestructibleModelDataStore.LookupEntry(m_goInfo->building.destructibleData))
                     if (modelData->DestroyedDisplayId)
                         modelId = modelData->DestroyedDisplayId;
                 SetDisplayId(modelId);
                 if (setHealth)
                 {
                     m_goValue.Building.Health = 0;
                     SetGoAnimProgress(0);
                 }
                 EnableCollision(false);
                 break;
             }
         case GO_DESTRUCTIBLE_REBUILDING:
             {
                 EventInform(m_goInfo->building.rebuildingEvent);
                 RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED | GO_FLAG_DESTROYED);
                 uint32 modelId = m_goInfo->displayId;
                 if (DestructibleModelDataEntry const* modelData = sDestructibleModelDataStore.LookupEntry(m_goInfo->building.destructibleData))
                     if (modelData->RebuildingDisplayId)
                         modelId = modelData->RebuildingDisplayId;
                 SetDisplayId(modelId);
                 // restores to full health
                 if (setHealth)
                 {
                     m_goValue.Building.Health = m_goValue.Building.MaxHealth;
                     SetGoAnimProgress(255);
                 }
                 EnableCollision(true);
                 break;
             }
     }
 }
References ASSERT, bg(), GameObjectTemplate::building, GameObjectValue::Building, GameObjectTemplate::displayId, EnableCollision(), EventInform(), GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetGoType(), WorldObject::GetMap(), GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_INTACT, GO_DESTRUCTIBLE_REBUILDING, GO_FLAG_DAMAGED, GO_FLAG_DESTROYED, GameObjectValue::Health, m_goInfo, m_goValue, GameObjectValue::MaxHealth, Object::RemoveFlag(), sDestructibleModelDataStore, SetDisplayId(), Object::SetFlag(), SetGoAnimProgress(), and sScriptMgr.
Referenced by Spell::EffectGameObjectSetDestructionState(), BfWGGameObjectBuilding::Init(), ModifyHealth(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::OnGameObjectCreate(), FrozenThroneResetWorker::operator()(), BattlegroundIC::PostUpdateImpl(), and BfWGGameObjectBuilding::Rebuild().
SetDisplayId()
void GameObject::SetDisplayId (uint32 displayid)
Definition at line 2405 of file GameObject.cpp.
 {
     SetUInt32Value(GAMEOBJECT_DISPLAYID, displayid);
     UpdateModel();
 }
References GAMEOBJECT_DISPLAYID, Object::SetUInt32Value(), and UpdateModel().
Referenced by Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), and SetDestructibleState().
SetGoAnimProgress()
void GameObject::SetGoAnimProgress (uint8 animprogress) inline
Definition at line 838 of file GameObject.h.
 { SetByteValue(GAMEOBJECT_BYTES_1, 3, animprogress); }
References GAMEOBJECT_BYTES_1, and Object::SetByteValue().
Referenced by Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), ModifyHealth(), and SetDestructibleState().
SetGoArtKit() [1/2]
void GameObject::SetGoArtKit (uint8 artkit)
Definition at line 1353 of file GameObject.cpp.
 {
     SetByteValue(GAMEOBJECT_BYTES_1, 2, kit);
     GameObjectData* data = const_cast<GameObjectData*>(sObjectMgr->GetGOData(m_spawnId));
     if (data)
         data->artKit = kit;
 }
References GAMEOBJECT_BYTES_1, m_spawnId, Object::SetByteValue(), and sObjectMgr.
Referenced by Create(), StaticTransport::Create(), and SetGoArtKit().
SetGoArtKit() [2/2]
void GameObject::SetGoArtKit (uint8 artkit, GameObject * go, ObjectGuid::LowType lowguid = 0) static
Definition at line 1361 of file GameObject.cpp.
 {
     const GameObjectData* data = nullptr;
     if (go)
     {
         go->SetGoArtKit(artkit);
         data = go->GetGOData();
     }
     else if (lowguid)
         data = sObjectMgr->GetGOData(lowguid);
     if (data)
         const_cast<GameObjectData*>(data)->artKit = artkit;
 }
References GetGOData(), SetGoArtKit(), and sObjectMgr.
SetGoState()
void GameObject::SetGoState (GOState state)
Definition at line 2376 of file GameObject.cpp.
 {
     SetByteValue(GAMEOBJECT_BYTES_1, 0, state);
 #ifdef ELUNA
     sEluna->OnGameObjectStateChanged(this, state);
 #endif
     sScriptMgr->OnGameObjectStateChanged(this, state);
     if (m_model)
     {
         if (!IsInWorld())
             return;
         // pussywizard: this startOpen is unneeded here, collision depends entirely on current GOState
         EnableCollision(state == GO_STATE_READY || IsTransport());
         // pussywizard: commented out everything below
         // startOpen determines whether we are going to add or remove the LoS on activation
         /*bool startOpen = (GetGoType() == GAMEOBJECT_TYPE_DOOR || GetGoType() == GAMEOBJECT_TYPE_BUTTON ? GetGOInfo()->door.startOpen : false);
         if (GetGOData() && GetGOData()->go_state == GO_STATE_READY)
             startOpen = !startOpen;
         if (state == GO_STATE_ACTIVE || state == GO_STATE_ACTIVE_ALTERNATIVE)
             EnableCollision(startOpen);
         else if (state == GO_STATE_READY)
             EnableCollision(!startOpen);*/
     }
 }
References EnableCollision(), GAMEOBJECT_BYTES_1, GO_STATE_READY, Object::IsInWorld(), IsTransport(), m_model, Object::SetByteValue(), and sScriptMgr.
Referenced by go_suppression_device::go_suppression_deviceAI::Activate(), boss_thorim::boss_thorimAI::CloseDoors(), Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), boss_thorim::boss_thorimAI::DamageTaken(), go_suppression_device::go_suppression_deviceAI::Deactivate(), Delete(), DespawnOrUnsummon(), InstanceScript::HandleGameObject(), instance_deadmines::instance_deadmines_InstanceMapScript::OnGameObjectCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnGameObjectCreate(), instance_gundrak::instance_gundrak_InstanceMapScript::OnGameObjectCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnGameObjectCreate(), instance_stratholme::instance_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnGameObjectCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::OnGameObjectCreate(), instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::OnGameObjectCreate(), go_palehoof_sphere::OnGossipHello(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), go_bristlelimb_cage::OnGossipHello(), go_corkis_prison::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), npc_natrualist_bite::OnGossipSelect(), instance_ulduar::instance_ulduar_InstanceMapScript::OpenIfDone(), FrozenThroneResetWorker::operator()(), BattlegroundIC::StartingEventOpenDoors(), SwitchDoorOrButton(), brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul(), boss_flame_leviathan::boss_flame_leviathanAI::TurnGates(), MotionTransport::Update(), Update(), InstanceScript::UpdateDoorState(), BattlegroundRV::UpdatePillars(), and Use().
SetGoType()
void GameObject::SetGoType (GameobjectTypes type) inline
Definition at line 832 of file GameObject.h.
 { SetByteValue(GAMEOBJECT_BYTES_1, 1, type); }
References GAMEOBJECT_BYTES_1, and Object::SetByteValue().
Referenced by Create(), StaticTransport::Create(), and MotionTransport::CreateMoTrans().
SetLinkedTrap()
void GameObject::SetLinkedTrap (GameObject * linkedTrap) inline
Definition at line 891 of file GameObject.h.
 { m_linkedTrap = linkedTrap->GetGUID(); }
References Object::GetGUID(), and m_linkedTrap.
Referenced by Create().
SetLocalRotation()
void GameObject::SetLocalRotation (G3D::Quat const & rot)
Definition at line 2147 of file GameObject.cpp.
 {
     G3D::Quat rotation;
     // Temporary solution for gameobjects that have no rotation data in DB:
     if (G3D::fuzzyEq(rot.z, 0.f) && G3D::fuzzyEq(rot.w, 0.f))
         rotation = G3D::Quat::fromAxisAngleRotation(G3D::Vector3::unitZ(), GetOrientation());
     else
         rotation = rot;
     rotation.unitize();
     m_localRotation = rotation;
     UpdatePackedRotation();
 }
References G3D::Quat::fromAxisAngleRotation(), G3D::fuzzyEq(), Position::GetOrientation(), m_localRotation, G3D::Quat::unitize(), G3D::Vector3::unitZ(), UpdatePackedRotation(), G3D::Quat::w, and G3D::Quat::z.
Referenced by Create(), MotionTransport::CreateMoTrans(), and SetLocalRotationAngles().
SetLocalRotationAngles()
void GameObject::SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
Definition at line 2169 of file GameObject.cpp.
 {
     SetLocalRotation(G3D::Quat(G3D::Matrix3::fromEulerAnglesZYX(z_rot, y_rot, x_rot)));
 }
References G3D::Matrix3::fromEulerAnglesZYX(), and SetLocalRotation().
Referenced by Create(), and StaticTransport::Create().
SetLootGenerationTime()
void GameObject::SetLootGenerationTime () inline
Definition at line 887 of file GameObject.h.
 { m_lootGenerationTime = time(nullptr); }
References m_lootGenerationTime.
Referenced by Player::SendLoot().
SetLootMode()
void GameObject::SetLootMode (uint16 lootMode) inline
Definition at line 852 of file GameObject.h.
 { m_LootMode = lootMode; }
References m_LootMode.
Referenced by instance_dire_maul::instance_dire_maul_InstanceMapScript::OnGameObjectCreate().
SetLootRecipient() [1/2]
void GameObject::SetLootRecipient (Creature * creature)
Definition at line 2461 of file GameObject.cpp.
 {
     // set the player whose group should receive the right
     // to loot the creature after it dies
     // should be set to nullptr after the loot disappears
     if (!creature)
     {
         m_lootRecipient.Clear();
         m_lootRecipientGroup = 0;
         ResetAllowedLooters();
         return;
     }
     m_lootRecipient = creature->GetLootRecipientGUID();
     m_lootRecipientGroup = creature->GetLootRecipientGroupGUID();
     SetAllowedLooters(creature->GetAllowedLooters());
 }
References ObjectGuid::Clear(), WorldObject::GetAllowedLooters(), Creature::GetLootRecipientGroupGUID(), Creature::GetLootRecipientGUID(), m_lootRecipient, m_lootRecipientGroup, WorldObject::ResetAllowedLooters(), and WorldObject::SetAllowedLooters().
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate().
SetLootRecipient() [2/2]
void GameObject::SetLootRecipient (Map * map)
Definition at line 2479 of file GameObject.cpp.
 {
     Group* group = nullptr;
     Map::PlayerList const& PlayerList = map->GetPlayers();
     for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
     {
         if (Player* groupMember = i->GetSource())
         {
             if (groupMember->IsGameMaster() || groupMember->IsSpectator())
             {
                 continue;
             }
             if (!m_lootRecipient)
             {
                 m_lootRecipient = groupMember->GetGUID();
             }
             Group* memberGroup = groupMember->GetGroup();
             if (memberGroup && !group)
             {
                 group = memberGroup;
                 m_lootRecipientGroup = group->GetGUID().GetCounter();
             }
             if (memberGroup == group)
             {
                 AddAllowedLooter(groupMember->GetGUID());
             }
         }
     }
     if (!group)
     {
         AddAllowedLooter(m_lootRecipient);
     }
 }
References WorldObject::AddAllowedLooter(), MapRefMgr::begin(), MapRefMgr::end(), ObjectGuid::GetCounter(), Group::GetGUID(), Map::GetPlayers(), m_lootRecipient, and m_lootRecipientGroup.
SetLootState()
void GameObject::SetLootState (LootState s, Unit * unit = nullptr)
Definition at line 2351 of file GameObject.cpp.
 {
     m_lootState = state;
 #ifdef ELUNA
     sEluna->OnLootStateChanged(this, state);
 #endif
     AI()->OnStateChanged(state, unit);
     sScriptMgr->OnGameObjectLootStateChanged(this, state, unit);
     // pussywizard: lootState has nothing to do with collision, it depends entirely on GOState. Loot state is for timed close/open door and respawning, which then sets GOState
     /*if (m_model)
     {
         // startOpen determines whether we are going to add or remove the LoS on activation
         bool startOpen = (GetGoType() == GAMEOBJECT_TYPE_DOOR || GetGoType() == GAMEOBJECT_TYPE_BUTTON ? GetGOInfo()->door.startOpen : false);
         // Use the current go state
         if (GetGoState() == GO_STATE_ACTIVE)
             startOpen = !startOpen;
         if (state == GO_ACTIVATED || state == GO_JUST_DEACTIVATED)
             EnableCollision(startOpen);
         else if (state == GO_READY)
             EnableCollision(!startOpen);
     }*/
 }
References AI(), m_lootState, GameObjectAI::OnStateChanged(), and sScriptMgr.
Referenced by go_suppression_device::go_suppression_deviceAI::Activate(), Delete(), DespawnOrUnsummon(), WorldSession::DoLootRelease(), Spell::EffectOpenLock(), spell_q9452_cast_net::HandleActiveObject(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate(), go_massive_seaforium_charge::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), go_suppression_device::go_suppression_deviceAI::OnLootStateChanged(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset(), ResetDoorOrButton(), Map::ScriptsProcess(), Player::SendLoot(), boss_flame_leviathan::boss_flame_leviathanAI::TurnHealStations(), Update(), Use(), and UseDoorOrButton().
SetOwnerGUID()
void GameObject::SetOwnerGUID (ObjectGuid owner) inline
Definition at line 784 of file GameObject.h.
     {
         // Owner already found and different than expected owner - remove object from old owner
         if (owner && GetOwnerGUID() && GetOwnerGUID() != owner)
         {
             ABORT();
         }
         m_spawnedByDefault = false;                     // all object with owner is despawned after delay
         SetGuidValue(OBJECT_FIELD_CREATED_BY, owner);
     }
References ABORT, GetOwnerGUID(), m_spawnedByDefault, OBJECT_FIELD_CREATED_BY, and Object::SetGuidValue().
Referenced by Unit::AddGameObject(), Spell::EffectTransmitted(), Unit::RemoveAllGameObjects(), RemoveFromOwner(), Unit::RemoveGameObject(), and Use().
SetPhaseMask()
void GameObject::SetPhaseMask (uint32 newPhaseMask, bool update) override virtual
Reimplemented from WorldObject.
Definition at line 2411 of file GameObject.cpp.
 {
     WorldObject::SetPhaseMask(newPhaseMask, update);
     if (m_model && m_model->isEnabled())
         EnableCollision(true);
 }
References EnableCollision(), GameObjectModel::isEnabled(), m_model, and WorldObject::SetPhaseMask().
Referenced by Create(), StaticTransport::Create(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate(), and instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate().
SetPosition() [1/2]
void GameObject::SetPosition (const Position & pos) inline
Definition at line 948 of file GameObject.h.
 { SetPosition(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation()); }
References pos(), and SetPosition().
Referenced by SetPosition().
SetPosition() [2/2]
void GameObject::SetPosition (float x, float y, float z, float o)
Definition at line 2658 of file GameObject.cpp.
 {
     // pussywizard: do not call for MotionTransport and other gobjects not in grid
     if (!Acore::IsValidMapCoord(x, y, z, o))
         return;
     GetMap()->GameObjectRelocation(this, x, y, z, o);
 }
References Map::GameObjectRelocation(), WorldObject::GetMap(), Acore::IsValidMapCoord(), G3D::x, G3D::y, and G3D::z.
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate().
SetRespawnDelay()
void GameObject::SetRespawnDelay (int32 respawn)
Definition at line 1223 of file GameObject.cpp.
 {
     m_respawnDelayTime = respawn > 0 ? respawn : 0;
 }
References m_respawnDelayTime.
Referenced by SetRespawnTime().
SetRespawnTime()
void GameObject::SetRespawnTime (int32 respawn)
Definition at line 1213 of file GameObject.cpp.
 {
     m_respawnTime = respawn > 0 ? time(nullptr) + respawn : 0;
     SetRespawnDelay(respawn);
     if (respawn && !m_spawnedByDefault)
     {
         UpdateObjectVisibility(true);
     }
 }
References m_respawnTime, m_spawnedByDefault, SetRespawnDelay(), and WorldObject::UpdateObjectVisibility().
Referenced by OPvPCapturePoint::DelCapturePoint(), OPvPCapturePoint::DelObject(), DespawnOrUnsummon(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectOpenLock(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), spell_q9452_cast_net::HandleActiveObject(), OutdoorPvPSI::HandleCustomSpell(), OutdoorPvPSI::HandleDropFlag(), gobject_commandscript::HandleGameObjectAddCommand(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), go_ulduar_working_harpoon::OnGossipHello(), Unit::RemoveAllGameObjects(), Unit::RemoveGameObject(), Map::ScriptsProcess(), BattlegroundIC::SetupBattleground(), WorldObject::SummonGameObject(), Map::SummonGameObject(), and Update().
SetSpawnedByDefault()
void GameObject::SetSpawnedByDefault (bool b) inline
Definition at line 824 of file GameObject.h.
 { m_spawnedByDefault = b; }
References b, and m_spawnedByDefault.
Referenced by WorldObject::SummonGameObject(), and Map::SummonGameObject().
SetSpellId()
void GameObject::SetSpellId (uint32 id) inline
Definition at line 797 of file GameObject.h.
     {
         m_spawnedByDefault = false;                     // all summoned object is despawned after delay
         m_spellId = id;
     }
References m_spawnedByDefault, and m_spellId.
Referenced by Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), WorldObject::SummonGameObject(), Map::SummonGameObject(), and Use().
SetTransportPathRotation()
void GameObject::SetTransportPathRotation (float qx, float qy, float qz, float qw)
Definition at line 2161 of file GameObject.cpp.
 {
     SetFloatValue(GAMEOBJECT_PARENTROTATION + 0, qx);
     SetFloatValue(GAMEOBJECT_PARENTROTATION + 1, qy);
     SetFloatValue(GAMEOBJECT_PARENTROTATION + 2, qz);
     SetFloatValue(GAMEOBJECT_PARENTROTATION + 3, qw);
 }
References GAMEOBJECT_PARENTROTATION, and Object::SetFloatValue().
Referenced by Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), and BattlegroundSA::ResetObjs().
SwitchDoorOrButton()
void GameObject::SwitchDoorOrButton (bool activate, bool alternative = false) private
Definition at line 1376 of file GameObject.cpp.
 {
     if (activate)
         SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
     else
         RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
     if (GetGoState() == GO_STATE_READY)                      //if closed -> open
         SetGoState(alternative ? GO_STATE_ACTIVE_ALTERNATIVE : GO_STATE_ACTIVE);
     else                                                    //if open -> close
         SetGoState(GO_STATE_READY);
 }
References alternative, GAMEOBJECT_FLAGS, GetGoState(), GO_FLAG_IN_USE, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, Object::RemoveFlag(), Object::SetFlag(), and SetGoState().
Referenced by ResetDoorOrButton(), and UseDoorOrButton().
ToMotionTransport() [1/2]
MotionTransport* GameObject::ToMotionTransport () inline
Definition at line 959 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT) return reinterpret_cast<MotionTransport*>(this); else return nullptr; }
References GAMEOBJECT_TYPE_MO_TRANSPORT, and GetGOInfo().
Referenced by BuildValuesUpdate(), ResetEncounterEvent::Execute(), npc_commandscript::HandleNpcAddCommand(), npc_gunship::npc_gunshipAI::JustDied(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), Map::RemoveAllObjectsInRemoveList(), Creature::SaveToDB(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), WaypointMovementGenerator< Creature >::StartMove(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), and npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI().
ToMotionTransport() [2/2]
MotionTransport const* GameObject::ToMotionTransport () const inline
Definition at line 960 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT) return reinterpret_cast<MotionTransport const*>(this); else return nullptr; }
References const, GAMEOBJECT_TYPE_MO_TRANSPORT, and GetGOInfo().
ToStaticTransport() [1/2]
StaticTransport* GameObject::ToStaticTransport () inline
Definition at line 956 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT) return reinterpret_cast<StaticTransport*>(this); else return nullptr; }
References GAMEOBJECT_TYPE_TRANSPORT, and GetGOInfo().
Referenced by BuildValuesUpdate(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), and instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update().
ToStaticTransport() [2/2]
StaticTransport const* GameObject::ToStaticTransport () const inline
Definition at line 957 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT) return reinterpret_cast<StaticTransport const*>(this); else return nullptr; }
References const, GAMEOBJECT_TYPE_TRANSPORT, and GetGOInfo().
ToTransport() [1/2]
Transport* GameObject::ToTransport () inline
Definition at line 953 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT || GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT) return reinterpret_cast<Transport*>(this); else return nullptr; }
References GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_TRANSPORT, and GetGOInfo().
Referenced by MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Object::BuildMovementUpdate(), CleanupsBeforeDelete(), Map::GetTransport(), Player::LoadFromDB(), npc_gunship_boarding_addAI::MovementInform(), MotionTransport::RemovePassenger(), and StaticTransport::RemovePassenger().
ToTransport() [2/2]
Transport const* GameObject::ToTransport () const inline
Definition at line 954 of file GameObject.h.
 { if (GetGOInfo()->type == GAMEOBJECT_TYPE_MO_TRANSPORT || GetGOInfo()->type == GAMEOBJECT_TYPE_TRANSPORT) return reinterpret_cast<Transport const*>(this); else return nullptr; }
References const, GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_TRANSPORT, and GetGOInfo().
TriggeringLinkedGameObject()
void GameObject::TriggeringLinkedGameObject (uint32 trapEntry, Unit * target)
Definition at line 1295 of file GameObject.cpp.
 {
     GameObjectTemplate const* trapInfo = sObjectMgr->GetGameObjectTemplate(trapEntry);
     if (!trapInfo || trapInfo->type != GAMEOBJECT_TYPE_TRAP)
         return;
     SpellInfo const* trapSpell = sSpellMgr->GetSpellInfo(trapInfo->trap.spellId);
     if (!trapSpell)                                          // checked at load already
         return;
     // xinef: wtf, many spells have range 0 but radius > 0
     float range = float(target->GetSpellMaxRangeForTarget(GetOwner(), trapSpell));
     if (range < 1.0f)
         range = 5.0f;
     // found correct GO
     // xinef: we should use the trap (checks for despawn type)
     if (GameObject* trapGO = GetLinkedTrap())
     {
         trapGO->Use(target); // trapGO->CastSpell(target, trapInfo->trap.spellId);
     }
 }
References GAMEOBJECT_TYPE_TRAP, GetLinkedTrap(), GetOwner(), Unit::GetSpellMaxRangeForTarget(), sObjectMgr, sSpellMgr, GameObjectTemplate::trap, and GameObjectTemplate::type.
Referenced by Spell::SendLoot(), and Use().
Update()
void GameObject::Update (uint32 p_time) override virtual
Todo:
This is activation radius. Casting radius must be selected from spell data.
Todo:
Move activated state code to GO_ACTIVATED, in this place just check for activation and set state.
If this is summoned by a spell with ie. SPELL_EFFECT_SUMMON_OBJECT_WILD, with or without owner, we check respawn criteria based on spell The GetOwnerGUID() check is mostly for compatibility with hacky scripts - 99% of the time summoning should be done trough spells.
Reimplemented from WorldObject.
Reimplemented in StaticTransport, and MotionTransport.
Definition at line 408 of file GameObject.cpp.
 {
 #ifdef ELUNA
     sEluna->UpdateAI(this, diff);
 #endif
     if (AI())
         AI()->UpdateAI(diff);
     else if (!AIM_Initialize())
         LOG_ERROR("entities.gameobject", "Could not initialize GameObjectAI");
     if (m_despawnDelay)
     {
         if (m_despawnDelay > diff)
         {
             m_despawnDelay -= diff;
         }
         else
         {
             m_despawnDelay = 0;
             DespawnOrUnsummon(0ms, m_despawnRespawnTime);
         }
     }
     switch (m_lootState)
     {
         case GO_NOT_READY:
             {
                 switch (GetGoType())
                 {
                     case GAMEOBJECT_TYPE_TRAP:
{
                             // Arming Time for GAMEOBJECT_TYPE_TRAP (6)
                             GameObjectTemplate const* goInfo = GetGOInfo();
                             // Bombs
                             if (goInfo->trap.type == 2)
                                 m_cooldownTime = World::GetGameTimeMS() + 10 * IN_MILLISECONDS; // Hardcoded tooltip value
                             else if (GetOwner())
                                 m_cooldownTime = World::GetGameTimeMS() + goInfo->trap.startDelay * IN_MILLISECONDS;
                             m_lootState = GO_READY;
                             break;
                         }
                     case GAMEOBJECT_TYPE_FISHINGNODE:
{
                             // fishing code (bobber ready)
                             if (time(nullptr) > m_respawnTime - FISHING_BOBBER_READY_TIME)
{
                                 // splash bobber (bobber ready now)
                                 Unit* caster = GetOwner();
                                 if (caster && caster->GetTypeId() == TYPEID_PLAYER)
{
                                     SetGoState(GO_STATE_ACTIVE);
                                     SetUInt32Value(GAMEOBJECT_FLAGS, GO_FLAG_NODESPAWN);
                                     UpdateData udata;
                                     WorldPacket packet;
                                     BuildValuesUpdateBlockForPlayer(&udata, caster->ToPlayer());
                                     udata.BuildPacket(&packet);
                                     caster->ToPlayer()->GetSession()->SendPacket(&packet);
                                     SendCustomAnim(GetGoAnimProgress());
                                 }
                                 m_lootState = GO_READY;                 // can be successfully open with some chance
                             }
                             return;
                         }
                     case GAMEOBJECT_TYPE_SUMMONING_RITUAL:
{
                             if (World::GetGameTimeMS() < m_cooldownTime)
                                 return;
                             GameObjectTemplate const* info = GetGOInfo();
                             if (info->summoningRitual.animSpell)
{
                                 // xinef: if ritual requires animation, ensure that all users performs channel
                                 CheckRitualList();
                             }
                             if (GetUniqueUseCount() < info->summoningRitual.reqParticipants)
{
                                 SetLootState(GO_READY);
                                 return;
                             }
                             bool triggered = info->summoningRitual.animSpell;
                             Unit* owner = GetOwner();
                             Unit* spellCaster = owner ? owner : ObjectAccessor::GetPlayer(*this, m_ritualOwnerGUID);
                             if (!spellCaster)
{
                                 SetLootState(GO_JUST_DEACTIVATED);
                                 return;
                             }
                             uint32 spellId = info->summoningRitual.spellId;
                             if (spellId == 62330)                       // GO store nonexistent spell, replace by expected
{
                                 // spell have reagent and mana cost but it not expected use its
                                 // it triggered spell in fact casted at currently channeled GO
                                 spellId = 61993;
                                 triggered = true;
                             }
                             // Cast casterTargetSpell at a random GO user
                             // on the current DB there is only one gameobject that uses this (Ritual of Doom)
                             // and its required target number is 1 (outter for loop will run once)
                             if (info->summoningRitual.casterTargetSpell && info->summoningRitual.casterTargetSpell != 1) // No idea why this field is a bool in some cases
                                 for (uint32 i = 0; i < info->summoningRitual.casterTargetSpellTargets; i++)
                                     // m_unique_users can contain only player GUIDs
                                     if (Player* target = ObjectAccessor::GetPlayer(*this, Acore::Containers::SelectRandomContainerElement(m_unique_users)))
                                         spellCaster->CastSpell(target, info->summoningRitual.casterTargetSpell, true);
                             // finish owners spell
                             // xinef: properly process event cooldowns
                             if (owner)
{
                                 if (Spell* spell = owner->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
{
                                     spell->SendChannelUpdate(0);
                                     spell->finish(false);
                                 }
                             }
                             // can be deleted now
                             if (!info->summoningRitual.ritualPersistent)
                                 SetLootState(GO_JUST_DEACTIVATED);
                             else
                                 SetLootState(GO_READY);
                             ClearRitualList();
                             spellCaster->CastSpell(spellCaster, spellId, triggered);
                             return;
                         }
                     default:
                         m_lootState = GO_READY;                         // for other GOis same switched without delay to GO_READY
                         break;
                 }
                 // NO BREAK for switch (m_lootState)
                 [[fallthrough]];
             }
         case GO_READY:
             {
                 if (m_respawnTime > 0)                          // timer on
                 {
                     time_t now = time(nullptr);
                     if (m_respawnTime <= now)            // timer expired
                     {
                         ObjectGuid dbtableHighGuid = ObjectGuid::Create<HighGuid::GameObject>(GetEntry(), m_spawnId);
                         time_t linkedRespawntime = GetMap()->GetLinkedRespawnTime(dbtableHighGuid);
                         if (linkedRespawntime)             // Can't respawn, the master is dead
{
                             ObjectGuid targetGuid = sObjectMgr->GetLinkedRespawnGuid(dbtableHighGuid);
                             if (targetGuid == dbtableHighGuid) // if linking self, never respawn (check delayed to next day)
                                 SetRespawnTime(DAY);
                             else
                                 m_respawnTime = (now > linkedRespawntime ? now : linkedRespawntime) + urand(5, MINUTE); // else copy time from master and add a little
                             SaveRespawnTime(); // also save to DB immediately
                             return;
                         }
                         m_respawnTime = 0;
                         m_SkillupList.clear();
                         m_usetimes = 0;
                         switch (GetGoType())
{
                             case GAMEOBJECT_TYPE_FISHINGNODE:   //  can't fish now
{
                                     Unit* caster = GetOwner();
                                     if (caster && caster->GetTypeId() == TYPEID_PLAYER)
{
                                         caster->ToPlayer()->RemoveGameObject(this, false);
                                         WorldPacket data(SMSG_FISH_ESCAPED, 0);
                                         caster->ToPlayer()->GetSession()->SendPacket(&data);
                                     }
                                     // can be delete
                                     m_lootState = GO_JUST_DEACTIVATED;
                                     return;
                                 }
                             case GAMEOBJECT_TYPE_DOOR:
                             case GAMEOBJECT_TYPE_BUTTON:
                                 //we need to open doors if they are closed (add there another condition if this code breaks some usage, but it need to be here for battlegrounds)
                                 if (GetGoState() != GO_STATE_READY)
                                     ResetDoorOrButton();
                                 break;
                             case GAMEOBJECT_TYPE_FISHINGHOLE:
                                 // Initialize a new max fish count on respawn
                                 m_goValue.FishingHole.MaxOpens = urand(GetGOInfo()->fishinghole.minSuccessOpens, GetGOInfo()->fishinghole.maxSuccessOpens);
                                 break;
                             default:
                                 break;
                         }
                         if (!m_spawnedByDefault)        // despawn timer
{
                             // can be despawned or destroyed
                             SetLootState(GO_JUST_DEACTIVATED);
                             return;
                         }
                         // Xinef: Call AI Reset (required for example in SmartAI to clear one time events)
                         if (AI())
                             AI()->Reset();
                         // respawn timer
                         uint32 poolid = m_spawnId ? sPoolMgr->IsPartOfAPool<GameObject>(m_spawnId) : 0;
                         if (poolid)
                             sPoolMgr->UpdatePool<GameObject>(poolid, m_spawnId);
                         else
                             GetMap()->AddToMap(this);
                     }
                 }
                 if (isSpawned())
                 {
                     // traps can have time and can not have
                     GameObjectTemplate const* goInfo = GetGOInfo();
                     if (goInfo->type == GAMEOBJECT_TYPE_TRAP)
                     {
                         if (World::GetGameTimeMS() < m_cooldownTime)
                             break;
                         // Type 2 - Bomb (will go away after casting it's spell)
                         if (goInfo->trap.type == 2)
{
                             if (goInfo->trap.spellId)
                                 CastSpell(nullptr, goInfo->trap.spellId);  // FIXME: null target won't work for target type 1
                             SetLootState(GO_JUST_DEACTIVATED);
                             break;
                         }
                         // Type 0 despawns after being triggered, type 1 does not.
                         bool isBattlegroundTrap = false;
                         float radius = float(goInfo->trap.diameter) * 0.5f;
                         if (!goInfo->trap.diameter)
{
                             // Cast in other case (at some triggering/linked go/etc explicit call)
                             if (goInfo->trap.cooldown != 3 || m_respawnTime > 0)
                                 break;
                             // Battleground gameobjects have data2 == 0 && data5 == 3
                             isBattlegroundTrap = true;
                             radius = 3.f;
                         }
                         // Type 0 and 1 - trap (type 0 will not get removed after casting a spell)
                         Unit* owner = GetOwner();
                         Unit* target = nullptr;                            // pointer to appropriate target if found any
                         // Note: this hack with search required until GO casting not implemented
                         // search unfriendly creature
                         if (owner)                    // hunter trap
{
                             Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck checker(this, owner, radius);
                             Acore::UnitSearcher<Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck> searcher(this, target, checker);
                             Cell::VisitAllObjects(this, searcher, radius);
                         }
                         else                                        // environmental trap
{
                             // environmental damage spells already have around enemies targeting but this not help in case not existed GO casting support
                             // affect only players
                             Player* player = nullptr;
                             Acore::AnyPlayerInObjectRangeCheck checker(this, radius, true, true);
                             Acore::PlayerSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(this, player, checker);
                             Cell::VisitWorldObjects(this, searcher, radius);
                             target = player;
                         }
                         if (target)
{
                             // some traps do not have spell but should be triggered
                             if (goInfo->trap.spellId)
                                 CastSpell(target, goInfo->trap.spellId);
                             m_cooldownTime = World::GetGameTimeMS() + (goInfo->trap.cooldown ? goInfo->trap.cooldown :  uint32(4)) * IN_MILLISECONDS; // template or 4 seconds
                             if (goInfo->trap.type == 1)
                                 SetLootState(GO_JUST_DEACTIVATED);
                             if (isBattlegroundTrap && target->GetTypeId() == TYPEID_PLAYER)
{
                                 // battleground gameobjects case
                                 if (target->ToPlayer()->InBattleground())
                                     if (Battleground* bg = target->ToPlayer()->GetBattleground())
                                         bg->HandleTriggerBuff(this);
                             }
                         }
                     }
                     else if (uint32 max_charges = goInfo->GetCharges())
                     {
                         if (m_usetimes >= max_charges)
{
                             m_usetimes = 0;
                             SetLootState(GO_JUST_DEACTIVATED);      // can be despawned or destroyed
                         }
                     }
                 }
                 break;
             }
         case GO_ACTIVATED:
             {
                 switch (GetGoType())
                 {
                     case GAMEOBJECT_TYPE_DOOR:
                     case GAMEOBJECT_TYPE_BUTTON:
                         if (GetGOInfo()->GetAutoCloseTime() && World::GetGameTimeMS() >= m_cooldownTime)
                             ResetDoorOrButton();
                         break;
                     case GAMEOBJECT_TYPE_GOOBER:
                         if (World::GetGameTimeMS() >= m_cooldownTime)
{
                             RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                             SetLootState(GO_JUST_DEACTIVATED);
                         }
                         break;
                     case GAMEOBJECT_TYPE_CHEST:
                         if (m_groupLootTimer)
{
                             if (m_groupLootTimer <= diff)
{
                                 Group* group = sGroupMgr->GetGroupByGUID(lootingGroupLowGUID);
                                 if (group)
                                     group->EndRoll(&loot, GetMap());
                                 m_groupLootTimer = 0;
                                 lootingGroupLowGUID = 0;
                             }
                             else m_groupLootTimer -= diff;
                         }
                     default:
                         break;
                 }
                 break;
             }
         case GO_JUST_DEACTIVATED:
             {
                 // If nearby linked trap exists, despawn it
                 if (GameObject* linkedTrap = GetLinkedTrap())
                 {
                     linkedTrap->DespawnOrUnsummon();
                 }
                 //if Gameobject should cast spell, then this, but some GOs (type = 10) should be destroyed
                 if (GetGoType() == GAMEOBJECT_TYPE_GOOBER)
                 {
                     SetGoState(GO_STATE_READY);
                     //any return here in case battleground traps
                     // Xinef: Do not return here for summoned gos that should be deleted few lines below
                     // Xinef: Battleground objects are treated as spawned by default
                     if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
                         if ((addon->flags & GO_FLAG_NODESPAWN) && isSpawnedByDefault())
                             return;
                 }
                 loot.clear();
                 if (GetSpellId() || GetOwnerGUID())
                 {
                     //Don't delete spell spawned chests, which are not consumed on loot
                     if (m_respawnTime > 0 && GetGoType() == GAMEOBJECT_TYPE_CHEST && !GetGOInfo()->IsDespawnAtAction())
                     {
                         UpdateObjectVisibility();
                         SetLootState(GO_READY);
                     }
                     else
                     {
                         SetRespawnTime(0);
                         Delete();
                     }
                     return;
                 }
                 SetLootState(GO_READY);
                 //burning flags in some battlegrounds, if you find better condition, just add it
                 if (GetGOInfo()->IsDespawnAtAction() || GetGoAnimProgress() > 0)
                 {
                     SendObjectDeSpawnAnim(GetGUID());
                     //reset flags
                     if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
                         SetUInt32Value(GAMEOBJECT_FLAGS, addon->flags);
                 }
                 if (!m_respawnDelayTime)
                     return;
                 if (!m_spawnedByDefault)
                 {
                     m_respawnTime = 0;
                     DestroyForNearbyPlayers(); // xinef: old UpdateObjectVisibility();
                     return;
                 }
                 m_respawnTime = time(nullptr) + m_respawnDelayTime;
                 // if option not set then object will be saved at grid unload
                 if (GetMap()->IsDungeon())
                     SaveRespawnTime();
                 DestroyForNearbyPlayers(); // xinef: old UpdateObjectVisibility();
                 break;
             }
     }
     sScriptMgr->OnGameObjectUpdate(this, diff);
 }
References Map::AddToMap(), AI(), AIM_Initialize(), bg(), UpdateData::BuildPacket(), Object::BuildValuesUpdateBlockForPlayer(), Unit::CastSpell(), CastSpell(), CheckRitualList(), Loot::clear(), ClearRitualList(), CURRENT_CHANNELED_SPELL, DAY, Delete(), DespawnOrUnsummon(), WorldObject::DestroyForNearbyPlayers(), diff(), Group::EndRoll(), FISHING_BOBBER_READY_TIME, GameObjectValue::FishingHole, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_SUMMONING_RITUAL, GAMEOBJECT_TYPE_TRAP, Player::GetBattleground(), GameObjectTemplate::GetCharges(), Unit::GetCurrentSpell(), Object::GetEntry(), World::GetGameTimeMS(), GetGoAnimProgress(), GetGOInfo(), GetGoState(), GetGoType(), Object::GetGUID(), Map::GetLinkedRespawnTime(), GetLinkedTrap(), WorldObject::GetMap(), GetOwner(), GetOwnerGUID(), ObjectAccessor::GetPlayer(), Player::GetSession(), GetSpellId(), GetTemplateAddon(), Object::GetTypeId(), GetUniqueUseCount(), GO_ACTIVATED, GO_FLAG_IN_USE, GO_FLAG_NODESPAWN, GO_JUST_DEACTIVATED, GO_NOT_READY, GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, IN_MILLISECONDS, Player::InBattleground(), isSpawned(), isSpawnedByDefault(), LOG_ERROR, loot, lootingGroupLowGUID, m_cooldownTime, m_despawnDelay, m_despawnRespawnTime, m_goValue, m_groupLootTimer, m_lootState, m_respawnDelayTime, m_respawnTime, m_ritualOwnerGUID, m_SkillupList, m_spawnedByDefault, m_spawnId, m_unique_users, m_usetimes, GameObjectValue::MaxOpens, GameObjectTemplate::maxSuccessOpens, GameObjectTemplate::minSuccessOpens, MINUTE, Object::RemoveFlag(), Unit::RemoveGameObject(), GameObjectAI::Reset(), ResetDoorOrButton(), SaveRespawnTime(), Acore::Containers::SelectRandomContainerElement(), SendCustomAnim(), WorldObject::SendObjectDeSpawnAnim(), WorldSession::SendPacket(), SetGoState(), SetLootState(), SetRespawnTime(), Object::SetUInt32Value(), sGroupMgr, SMSG_FISH_ESCAPED, sObjectMgr, sPoolMgr, sScriptMgr, GameObjectTemplate::summoningRitual, Object::ToPlayer(), GameObjectTemplate::trap, GameObjectTemplate::type, TYPEID_PLAYER, GameObjectAI::UpdateAI(), WorldObject::UpdateObjectVisibility(), urand(), Cell::VisitAllObjects(), and Cell::VisitWorldObjects().
Referenced by StaticTransport::Update().
UpdateModel()
void GameObject::UpdateModel () protected
Definition at line 2434 of file GameObject.cpp.
 {
     if (!IsInWorld())
         return;
     if (m_model)
         if (GetMap()->ContainsGameObjectModel(*m_model))
             GetMap()->RemoveGameObjectModel(*m_model);
     delete m_model;
     m_model = CreateModel();
     if (m_model)
         GetMap()->InsertGameObjectModel(*m_model);
 }
References CreateModel(), WorldObject::GetMap(), Map::InsertGameObjectModel(), Object::IsInWorld(), m_model, and Map::RemoveGameObjectModel().
Referenced by SetDisplayId().
UpdateModelPosition()
void GameObject::UpdateModelPosition ()
Definition at line 2706 of file GameObject.cpp.
 {
     if (!m_model)
         return;
     if (GetMap()->ContainsGameObjectModel(*m_model))
     {
         GetMap()->RemoveGameObjectModel(*m_model);
         m_model->UpdatePosition();
         GetMap()->InsertGameObjectModel(*m_model);
     }
 }
References WorldObject::GetMap(), Map::InsertGameObjectModel(), m_model, Map::RemoveGameObjectModel(), and GameObjectModel::UpdatePosition().
Referenced by Map::GameObjectRelocation(), and MotionTransport::UpdatePosition().
UpdatePackedRotation()
void GameObject::UpdatePackedRotation () private
Definition at line 2134 of file GameObject.cpp.
 {
     static const int32 PACK_YZ = 1 << 20;
     static const int32 PACK_X = PACK_YZ << 1;
     static const int32 PACK_YZ_MASK = (PACK_YZ << 1) - 1;
     static const int32 PACK_X_MASK = (PACK_X << 1) - 1;
     int8 w_sign = (m_localRotation.w >= 0.f ? 1 : -1);
     int64 x = int32(m_localRotation.x * PACK_X)  * w_sign & PACK_X_MASK;
     int64 y = int32(m_localRotation.y * PACK_YZ) * w_sign & PACK_YZ_MASK;
     int64 z = int32(m_localRotation.z * PACK_YZ) * w_sign & PACK_YZ_MASK;
     m_packedRotation = z | (y << 21) | (x << 42);
 }
References m_localRotation, m_packedRotation, G3D::Quat::w, G3D::Quat::x, G3D::x, G3D::Quat::y, G3D::y, G3D::Quat::z, and G3D::z.
Referenced by SetLocalRotation().
Use()
void GameObject::Use (Unit * user)
Definition at line 1389 of file GameObject.cpp.
 {
     // Xinef: we cannot use go with not selectable flags
     if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE))
         return;
     // by default spell caster is user
     Unit* spellCaster = user;
     uint32 spellId = 0;
     bool triggered = false;
     bool tmpfish = false;
     if (Player* playerUser = user->ToPlayer())
     {
 #ifdef ELUNA
         if (sEluna->OnGossipHello(playerUser, this))
             return;
 #endif
         if (sScriptMgr->OnGossipHello(playerUser, this))
             return;
         if (AI()->GossipHello(playerUser, false))
             return;
     }
     // If cooldown data present in template
     if (uint32 cooldown = GetGOInfo()->GetCooldown())
     {
         if (World::GetGameTimeMS() < m_cooldownTime)
             return;
         m_cooldownTime = World::GetGameTimeMS() + cooldown * IN_MILLISECONDS;
     }
     switch (GetGoType())
     {
         case GAMEOBJECT_TYPE_DOOR:                          //0
             //doors/buttons never really despawn, only reset to default state/flags
             UseDoorOrButton(0, false, user);
             return;
         case GAMEOBJECT_TYPE_BUTTON:                        //1
             //doors/buttons never really despawn, only reset to default state/flags
             UseDoorOrButton(0, false, user);
             // Xinef: properly link possible traps
             if (uint32 trapEntry = GetGOInfo()->button.linkedTrap)
                 TriggeringLinkedGameObject(trapEntry, user);
             return;
         case GAMEOBJECT_TYPE_QUESTGIVER:                    //2
             {
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 player->PrepareGossipMenu(this, GetGOInfo()->questgiver.gossipID, true);
                 player->SendPreparedGossip(this);
                 return;
             }
         case GAMEOBJECT_TYPE_TRAP:                          //6
             {
                 GameObjectTemplate const* goInfo = GetGOInfo();
                 if (goInfo->trap.spellId)
                     CastSpell(user, goInfo->trap.spellId);
                 m_cooldownTime = World::GetGameTimeMS() + (goInfo->trap.cooldown ? goInfo->trap.cooldown :  uint32(4)) * IN_MILLISECONDS; // template or 4 seconds
                 if (goInfo->trap.type == 1)         // Deactivate after trigger
                     SetLootState(GO_JUST_DEACTIVATED);
                 return;
             }
         //Sitting: Wooden bench, chairs enzz
         case GAMEOBJECT_TYPE_CHAIR:                         //7
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 if (!info)
                     return;
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 if (ChairListSlots.empty())        // this is called once at first chair use to make list of available slots
                 {
                     if (info->chair.slots > 0)     // sometimes chairs in DB have error in fields and we dont know number of slots
                         for (uint32 i = 0; i < info->chair.slots; ++i)
                             ChairListSlots[i].Clear(); // Last user of current slot set to 0 (none sit here yet)
                     else
                         ChairListSlots[0].Clear();     // error in DB, make one default slot
                 }
                 Player* player = user->ToPlayer();
                 // a chair may have n slots. we have to calculate their positions and teleport the player to the nearest one
                 float lowestDist = DEFAULT_VISIBILITY_DISTANCE;
                 uint32 nearest_slot = 0;
                 float x_lowest = GetPositionX();
                 float y_lowest = GetPositionY();
                 // the object orientation + 1/2 pi
                 // every slot will be on that straight line
                 float orthogonalOrientation = GetOrientation() + M_PI * 0.5f;
                 // find nearest slot
                 bool found_free_slot = false;
                 for (ChairSlotAndUser::iterator itr = ChairListSlots.begin(); itr != ChairListSlots.end(); ++itr)
                 {
                     // the distance between this slot and the center of the go - imagine a 1D space
                     float relativeDistance = (info->size * itr->first) - (info->size * (info->chair.slots - 1) / 2.0f);
                     float x_i = GetPositionX() + relativeDistance * cos(orthogonalOrientation);
                     float y_i = GetPositionY() + relativeDistance * sin(orthogonalOrientation);
                     if (itr->second)
                     {
                         if (Player* ChairUser = ObjectAccessor::GetPlayer(*this, itr->second))
{
                             if (ChairUser->IsSitState() && ChairUser->getStandState() != UNIT_STAND_STATE_SIT && ChairUser->GetExactDist2d(x_i, y_i) < 0.1f)
                                 continue;        // This seat is already occupied by ChairUser. NOTE: Not sure if the ChairUser->getStandState() != UNIT_STAND_STATE_SIT check is required.
                             else
                                 itr->second.Clear(); // This seat is unoccupied.
                         }
                         else
                             itr->second.Clear();     // The seat may of had an occupant, but they're offline.
                     }
                     found_free_slot = true;
                     // calculate the distance between the player and this slot
                     float thisDistance = player->GetDistance2d(x_i, y_i);
                     if (thisDistance <= lowestDist)
                     {
                         nearest_slot = itr->first;
                         lowestDist = thisDistance;
                         x_lowest = x_i;
                         y_lowest = y_i;
                     }
                 }
                 if (found_free_slot)
                 {
                     ChairSlotAndUser::iterator itr = ChairListSlots.find(nearest_slot);
                     if (itr != ChairListSlots.end())
                     {
                         itr->second = player->GetGUID(); //this slot in now used by player
                         player->TeleportTo(GetMapId(), x_lowest, y_lowest, GetPositionZ(), GetOrientation(), TELE_TO_NOT_LEAVE_TRANSPORT | TELE_TO_NOT_LEAVE_COMBAT | TELE_TO_NOT_UNSUMMON_PET);
                         player->SetStandState(UNIT_STAND_STATE_SIT_LOW_CHAIR + info->chair.height);
                         return;
                     }
                 }
                 return;
             }
         //big gun, its a spell/aura
         case GAMEOBJECT_TYPE_GOOBER:                        //10
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 // xinef: Goober cannot be used with this flag, skip
                 if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE))
                     return;
                 if (user->GetTypeId() == TYPEID_PLAYER)
                 {
                     Player* player = user->ToPlayer();
                     if (info->goober.pageId)                    // show page...
                     {
                         WorldPacket data(SMSG_GAMEOBJECT_PAGETEXT, 8);
                         data << GetGUID();
                         player->GetSession()->SendPacket(&data);
                     }
                     else if (info->goober.gossipID)
                     {
                         player->PrepareGossipMenu(this, info->goober.gossipID);
                         player->SendPreparedGossip(this);
                     }
                     if (info->goober.eventId)
                     {
                         LOG_DEBUG("maps.script", "Goober ScriptStart id %u for GO entry %u (spawnId %u).", info->goober.eventId, GetEntry(), m_spawnId);
                         GetMap()->ScriptsStart(sEventScripts, info->goober.eventId, player, this);
                         EventInform(info->goober.eventId);
                     }
                     // possible quest objective for active quests
                     if (info->goober.questId && sObjectMgr->GetQuestTemplate(info->goober.questId))
                     {
                         //Quest require to be active for GO using
                         if (player->GetQuestStatus(info->goober.questId) != QUEST_STATUS_INCOMPLETE)
                             break;
                     }
                     if (Battleground* bg = player->GetBattleground())
                         bg->EventPlayerUsedGO(player, this);
                     if (Group* group = player->GetGroup())
                     {
                         for (GroupReference const* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
{
                             if (Player* member = itr->GetSource())
{
                                 if (member->IsAtGroupRewardDistance(this))
{
                                     member->KillCreditGO(info->entry, GetGUID());
                                 }
                             }
                         }
                     }
                     else
                     {
                         player->KillCreditGO(info->entry, GetGUID());
                     }
                 }
                 if (uint32 trapEntry = info->goober.linkedTrapId)
                     TriggeringLinkedGameObject(trapEntry, user);
                 if (info->GetAutoCloseTime())
                 {
                     SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                     SetLootState(GO_ACTIVATED, user);
                     if (!info->goober.customAnim)
                         SetGoState(GO_STATE_ACTIVE);
                 }
                 // this appear to be ok, however others exist in addition to this that should have custom (ex: 190510, 188692, 187389)
                 if (info->goober.customAnim)
                     SendCustomAnim(GetGoAnimProgress());
                 m_cooldownTime = World::GetGameTimeMS() + info->GetAutoCloseTime();
                 // cast this spell later if provided
                 spellId = info->goober.spellId;
                 spellCaster = user;
                 tmpfish = true;
                 break;
             }
         case GAMEOBJECT_TYPE_CAMERA:                        //13
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 if (!info)
                     return;
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 if (info->camera.cinematicId)
                     player->SendCinematicStart(info->camera.cinematicId);
                 if (info->camera.eventID)
                     GetMap()->ScriptsStart(sEventScripts, info->camera.eventID, player, this);
                 return;
             }
         //fishing bobber
         case GAMEOBJECT_TYPE_FISHINGNODE:                   //17
             {
                 Player* player = user->ToPlayer();
                 if (!player)
                     return;
                 if (player->GetGUID() != GetOwnerGUID())
                     return;
                 switch (getLootState())
                 {
                     case GO_READY:                              // ready for loot
{
                             uint32 zone, subzone;
                             GetZoneAndAreaId(zone, subzone);
                             int32 zone_skill = sObjectMgr->GetFishingBaseSkillLevel(subzone);
                             if (!zone_skill)
                                 zone_skill = sObjectMgr->GetFishingBaseSkillLevel(zone);
                             //provide error, no fishable zone or area should be 0
                             if (!zone_skill)
                                 LOG_ERROR("sql.sql", "Fishable areaId %u are not properly defined in `skill_fishing_base_level`.", subzone);
                             int32 skill = player->GetSkillValue(SKILL_FISHING);
                             int32 chance;
                             if (skill < zone_skill)
{
                                 chance = int32(pow((double)skill / zone_skill, 2) * 100);
                                 if (chance < 1)
                                     chance = 1;
                             }
                             else
                                 chance = 100;
                             int32 roll = irand(1, 100);
                             LOG_DEBUG("entities.gameobject", "Fishing check (skill: %i zone min skill: %i chance %i roll: %i", skill, zone_skill, chance, roll);
                             // but you will likely cause junk in areas that require a high fishing skill (not yet implemented)
                             if (chance >= roll)
{
                                 player->UpdateFishingSkill();
                                 //TODO: I do not understand this hack. Need some explanation.
                                 // prevent removing GO at spell cancel
                                 RemoveFromOwner();
                                 SetOwnerGUID(player->GetGUID());
                                 SetSpellId(0); // prevent removing unintended auras at Unit::RemoveGameObject
                                 //TODO: find reasonable value for fishing hole search
                                 GameObject* ok = LookupFishingHoleAround(20.0f + CONTACT_DISTANCE);
                                 if (ok)
{
                                     ok->Use(player);
                                     SetLootState(GO_JUST_DEACTIVATED);
                                 }
                                 else
                                     player->SendLoot(GetGUID(), LOOT_FISHING);
                             }
                             else // else: junk
                                 player->SendLoot(GetGUID(), LOOT_FISHING_JUNK);
                             tmpfish = true;
                             break;
                         }
                     case GO_JUST_DEACTIVATED:                   // nothing to do, will be deleted at next update
                         break;
                     default:
{
                             SetLootState(GO_JUST_DEACTIVATED);
                             WorldPacket data(SMSG_FISH_NOT_HOOKED, 0);
                             player->GetSession()->SendPacket(&data);
                             break;
                         }
                 }
                 if(tmpfish)
                     player->FinishSpell(CURRENT_CHANNELED_SPELL, true);
                 else
                     player->InterruptSpell(CURRENT_CHANNELED_SPELL, true, true, true);
                 return;
             }
         case GAMEOBJECT_TYPE_SUMMONING_RITUAL:              //18
             {
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 Unit* owner = GetOwner();
                 GameObjectTemplate const* info = GetGOInfo();
                 // ritual owner is set for GO's without owner (not summoned)
                 if (!m_ritualOwnerGUID && !owner)
                     m_ritualOwnerGUID = player->GetGUID();
                 if (owner)
                 {
                     if (owner->GetTypeId() != TYPEID_PLAYER)
                         return;
                     // accept only use by player from same group as owner, excluding owner itself (unique use already added in spell effect)
                     if (player == owner->ToPlayer() || (info->summoningRitual.castersGrouped && !player->IsInSameRaidWith(owner->ToPlayer())))
                         return;
                     // expect owner to already be channeling, so if not...
                     if (!owner->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                         return;
                 }
                 else
                 {
                     Player* ritualOwner = ObjectAccessor::GetPlayer(*this, m_ritualOwnerGUID);
                     if (!ritualOwner)
                         return;
                     if (player != ritualOwner && (info->summoningRitual.castersGrouped && !player->IsInSameRaidWith(ritualOwner)))
                         return;
                 }
                 if (info->summoningRitual.animSpell)
                 {
                     // xinef: if ritual requires animation, ensure that all users performs channel
                     CheckRitualList();
                     // xinef: all participants found
                     if (GetUniqueUseCount() == info->summoningRitual.reqParticipants)
                         return;
                     player->CastSpell(player, info->summoningRitual.animSpell, true);
                 }
                 AddUniqueUse(player);
                 // full amount unique participants including original summoner
                 if (GetUniqueUseCount() == info->summoningRitual.reqParticipants)
                 {
                     SetLootState(GO_NOT_READY);
                     // can be deleted now, if
                     if (!info->summoningRitual.animSpell)
                         m_cooldownTime = 0;
                     else // channel ready, maintain this
                         m_cooldownTime = World::GetGameTimeMS() + 5 * IN_MILLISECONDS;
                 }
                 return;
             }
         case GAMEOBJECT_TYPE_SPELLCASTER:                   //22
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 if (!info)
                     return;
                 if (info->spellcaster.partyOnly)
                 {
                     Player const* caster = ObjectAccessor::FindConnectedPlayer(GetOwnerGUID());
                     if (!caster || user->GetTypeId() != TYPEID_PLAYER || !user->ToPlayer()->IsInSameRaidWith(caster))
                         return;
                 }
                 user->RemoveAurasByType(SPELL_AURA_MOUNTED);
                 spellId = info->spellcaster.spellId;
                 AddUse();
                 break;
             }
         case GAMEOBJECT_TYPE_MEETINGSTONE:                  //23
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 Player* targetPlayer = ObjectAccessor::FindPlayer(player->GetTarget());
                 // accept only use by player from same raid as caster, except caster itself
                 if (!targetPlayer || targetPlayer == player || !targetPlayer->IsInSameRaidWith(player))
                     return;
                 //required lvl checks!
                 uint8 level = player->getLevel();
                 if (level < info->meetingstone.minLevel)
                     return;
                 level = targetPlayer->getLevel();
                 if (level < info->meetingstone.minLevel)
                     return;
                 if (info->entry == 194097)
                     spellId = 61994;                            // Ritual of Summoning
                 else
                     spellId = 59782;                            // Summoning Stone Effect
                 break;
             }
         case GAMEOBJECT_TYPE_FLAGSTAND:                     // 24
             {
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 if (player->CanUseBattlegroundObject(this))
                 {
                     // in battleground check
                     Battleground* bg = player->GetBattleground();
                     if (!bg)
                         return;
                     if (player->GetVehicle())
                         return;
                     player->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
                     player->RemoveAurasByType(SPELL_AURA_MOD_INVISIBILITY);
                     // BG flag click
                     // AB:
                     // 15001
                     // 15002
                     // 15003
                     // 15004
                     // 15005
                     bg->EventPlayerClickedOnFlag(player, this);
                     return;                                     //we don;t need to delete flag ... it is despawned!
                 }
                 break;
             }
         case GAMEOBJECT_TYPE_FISHINGHOLE:                   // 25
             {
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 player->SendLoot(GetGUID(), LOOT_FISHINGHOLE);
                 player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, GetGOInfo()->entry);
                 return;
             }
         case GAMEOBJECT_TYPE_FLAGDROP:                      // 26
             {
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 if (player->CanUseBattlegroundObject(this))
                 {
                     // in battleground check
                     Battleground* bg = player->GetBattleground();
                     if (!bg)
                         return;
                     if (player->GetVehicle())
                         return;
                     player->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
                     player->RemoveAurasByType(SPELL_AURA_MOD_INVISIBILITY);
                     // BG flag dropped
                     // WS:
                     // 179785 - Silverwing Flag
                     // 179786 - Warsong Flag
                     // EotS:
                     // 184142 - Netherstorm Flag
                     GameObjectTemplate const* info = GetGOInfo();
                     if (info)
                     {
                         if (GameObject::gameObjectToEventFlag.find(info->entry) != GameObject::gameObjectToEventFlag.end())
{
                             GameObject::gameObjectToEventFlag[info->entry](player, this, bg);
                         }
                         else
{
                             switch (info->entry)
{
                                 case 179785:                        // Silverwing Flag
                                 case 179786:                        // Warsong Flag
                                     if (bg->GetBgTypeID(true) == BATTLEGROUND_WS)
                                         bg->EventPlayerClickedOnFlag(player, this);
                                     break;
                                 case 184142:                        // Netherstorm Flag
                                     if (bg->GetBgTypeID(true) == BATTLEGROUND_EY)
                                         bg->EventPlayerClickedOnFlag(player, this);
                                     break;
                             }
                         }
                     }
                     //this cause to call return, all flags must be deleted here!!
                     spellId = 0;
                     Delete();
                 }
                 break;
             }
         case GAMEOBJECT_TYPE_BARBER_CHAIR:                  //32
             {
                 GameObjectTemplate const* info = GetGOInfo();
                 if (!info)
                     return;
                 if (user->GetTypeId() != TYPEID_PLAYER)
                     return;
                 Player* player = user->ToPlayer();
                 // fallback, will always work
                 player->TeleportTo(GetMapId(), GetPositionX(), GetPositionY(), GetPositionZ(), GetOrientation(), TELE_TO_NOT_LEAVE_TRANSPORT | TELE_TO_NOT_LEAVE_COMBAT | TELE_TO_NOT_UNSUMMON_PET);
                 WorldPacket data(SMSG_ENABLE_BARBER_SHOP, 0);
                 player->GetSession()->SendPacket(&data);
                 player->SetStandState(UNIT_STAND_STATE_SIT_LOW_CHAIR + info->barberChair.chairheight);
                 return;
             }
         default:
             if (GetGoType() >= MAX_GAMEOBJECT_TYPE)
                 LOG_ERROR("entities.gameobject", "GameObject::Use(): unit (%s, name: %s) tries to use object (%s, name: %s) of unknown type (%u)",
                                user->GetGUID().ToString().c_str(), user->GetName().c_str(), GetGUID().ToString().c_str(),  GetGOInfo()->name.c_str(), GetGoType());
             break;
     }
     if (!spellId)
         return;
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
     if (!spellInfo)
     {
         if (user->GetTypeId() != TYPEID_PLAYER || !sOutdoorPvPMgr->HandleCustomSpell(user->ToPlayer(), spellId, this))
             LOG_ERROR("entities.gameobject", "WORLD: unknown spell id %u at use action for gameobject (Entry: %u GoType: %u)", spellId, GetEntry(), GetGoType());
         else
             LOG_DEBUG("outdoorpvp", "WORLD: %u non-dbc spell was handled by OutdoorPvP", spellId);
         return;
     }
     if (Player* player = user->ToPlayer())
         sOutdoorPvPMgr->HandleCustomSpell(player, spellId, this);
     if (spellCaster)
         spellCaster->CastSpell(user, spellInfo, triggered);
     else
         CastSpell(user, spellId);
 }
References ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, AddUniqueUse(), AddUse(), AI(), GameObjectTemplate::barberChair, BATTLEGROUND_EY, BATTLEGROUND_WS, bg(), GameObjectTemplate::camera, Player::CanUseBattlegroundObject(), Unit::CastSpell(), CastSpell(), GameObjectTemplate::chair, ChairListSlots, CheckRitualList(), CONTACT_DISTANCE, CURRENT_CHANNELED_SPELL, DEFAULT_VISIBILITY_DISTANCE, Delete(), GameObjectTemplate::entry, EventInform(), find(), ObjectAccessor::FindConnectedPlayer(), ObjectAccessor::FindPlayer(), Unit::FinishSpell(), GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_BARBER_CHAIR, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_MEETINGSTONE, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELLCASTER, GAMEOBJECT_TYPE_SUMMONING_RITUAL, GAMEOBJECT_TYPE_TRAP, gameObjectToEventFlag, GameObjectTemplate::GetAutoCloseTime(), Player::GetBattleground(), Unit::GetCurrentSpell(), WorldObject::GetDistance2d(), Object::GetEntry(), World::GetGameTimeMS(), GetGoAnimProgress(), GetGOInfo(), GetGoType(), Player::GetGroup(), Object::GetGUID(), Unit::getLevel(), getLootState(), WorldObject::GetMap(), WorldLocation::GetMapId(), WorldObject::GetName(), Position::GetOrientation(), GetOwner(), GetOwnerGUID(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), Player::GetSession(), Player::GetSkillValue(), Unit::GetTarget(), Object::GetTypeId(), GetUniqueUseCount(), Unit::GetVehicle(), WorldObject::GetZoneAndAreaId(), GO_ACTIVATED, GO_FLAG_IN_USE, GO_FLAG_NOT_SELECTABLE, GO_JUST_DEACTIVATED, GO_NOT_READY, GO_READY, GO_STATE_ACTIVE, GameObjectTemplate::goober, GameObjectTemplate::gossipID, Object::HasFlag(), IN_MILLISECONDS, Unit::InterruptSpell(), irand(), Player::IsInSameRaidWith(), Player::KillCreditGO(), GameObjectTemplate::linkedTrap, LOG_DEBUG, LOG_ERROR, LookupFishingHoleAround(), LOOT_FISHING, LOOT_FISHING_JUNK, LOOT_FISHINGHOLE, m_cooldownTime, M_PI, m_ritualOwnerGUID, m_spawnId, MAX_GAMEOBJECT_TYPE, name, GroupReference::next(), pow(), Player::PrepareGossipMenu(), QUEST_STATUS_INCOMPLETE, Unit::RemoveAurasByType(), RemoveFromOwner(), Map::ScriptsStart(), Player::SendCinematicStart(), SendCustomAnim(), Player::SendLoot(), WorldSession::SendPacket(), Player::SendPreparedGossip(), Object::SetFlag(), SetGoState(), SetLootState(), SetOwnerGUID(), SetSpellId(), Unit::SetStandState(), sEventScripts, GameObjectTemplate::size, SKILL_FISHING, SMSG_ENABLE_BARBER_SHOP, SMSG_FISH_NOT_HOOKED, SMSG_GAMEOBJECT_PAGETEXT, sObjectMgr, sOutdoorPvPMgr, SPELL_AURA_MOD_INVISIBILITY, SPELL_AURA_MOD_STEALTH, SPELL_AURA_MOUNTED, GameObjectTemplate::spellcaster, sScriptMgr, sSpellMgr, GameObjectTemplate::summoningRitual, TELE_TO_NOT_LEAVE_COMBAT, TELE_TO_NOT_LEAVE_TRANSPORT, TELE_TO_NOT_UNSUMMON_PET, Player::TeleportTo(), Object::ToPlayer(), Position::ToString(), ObjectGuid::ToString(), GameObjectTemplate::trap, TriggeringLinkedGameObject(), TYPEID_PLAYER, UNIT_STAND_STATE_SIT, UNIT_STAND_STATE_SIT_LOW_CHAIR, Player::UpdateAchievementCriteria(), Player::UpdateFishingSkill(), Use(), and UseDoorOrButton().
Referenced by Spell::EffectActivateObject(), spell_q9452_cast_net::HandleActiveObject(), Spell::SendLoot(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), and Use().
UseDoorOrButton()
void GameObject::UseDoorOrButton (uint32 time_to_restore = 0, bool alternative = false, Unit * user = nullptr)
Definition at line 1339 of file GameObject.cpp.
 {
     if (m_lootState != GO_READY)
         return;
     if (!time_to_restore)
         time_to_restore = GetGOInfo()->GetAutoCloseTime();
     SwitchDoorOrButton(true, alternative);
     SetLootState(GO_ACTIVATED, user);
     m_cooldownTime = World::GetGameTimeMS() + time_to_restore;
 }
References alternative, GameObjectTemplate::GetAutoCloseTime(), World::GetGameTimeMS(), GetGOInfo(), GO_ACTIVATED, GO_READY, m_cooldownTime, m_lootState, SetLootState(), and SwitchDoorOrButton().
Referenced by Map::_ScriptProcessDoor(), WorldSession::DoLootRelease(), InstanceScript::DoUseDoorOrButton(), instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate(), instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate(), go_broggok_lever::OnGossipHello(), go_ravager_cage::OnGossipHello(), go_panther_cage::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_warmaul_prison::OnGossipHello(), go_scourge_cage::OnGossipHello(), go_jotunheim_cage::OnGossipHello(), go_dragonflayer_cage::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), go_thorim_lever::OnGossipHello(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset(), Spell::SendLoot(), and Use().
Member Data Documentation
ChairListSlots
ChairSlotAndUser GameObject::ChairListSlots protected
Definition at line 1001 of file GameObject.h.
Referenced by Use().
gameObjectToEventFlag
std::unordered_map< int, goEventFlag > GameObject::gameObjectToEventFlag = { } static
Definition at line 979 of file GameObject.h.
Referenced by Use().
loot
Loot GameObject::loot
Definition at line 877 of file GameObject.h.
Referenced by WorldSession::DoLootRelease(), GameObject(), WorldSession::HandleAutostoreLootItemOpcode(), gobject_commandscript::HandleGameObjectInfoCommand(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMoneyOpcode(), Player::SendLoot(), and Update().
lootingGroupLowGUID
uint32 GameObject::lootingGroupLowGUID
Definition at line 886 of file GameObject.h.
Referenced by GameObject(), and Update().
m_AI
GameObjectAI* GameObject::m_AI private
Definition at line 1034 of file GameObject.h.
Referenced by AI(), AIM_Initialize(), and ~GameObject().
m_allowModifyDestructibleBuilding
bool GameObject::m_allowModifyDestructibleBuilding protected
Definition at line 1007 of file GameObject.h.
Referenced by GameObject(), ModifyHealth(), and SetDestructibleBuildingModifyState().
m_cooldownTime
uint32 GameObject::m_cooldownTime protected
Definition at line 992 of file GameObject.h.
Referenced by GameObject(), ResetDoorOrButton(), Update(), Use(), and UseDoorOrButton().
m_despawnDelay
uint32 GameObject::m_despawnDelay protected
Definition at line 988 of file GameObject.h.
Referenced by DespawnOrUnsummon(), GameObject(), and Update().
m_despawnRespawnTime
Seconds GameObject::m_despawnRespawnTime protected
Definition at line 989 of file GameObject.h.
Referenced by DespawnOrUnsummon(), GameObject(), and Update().
m_goData
GameObjectData const* GameObject::m_goData protected
Definition at line 1005 of file GameObject.h.
Referenced by DespawnOrUnsummon(), GameObject(), GetGOData(), LoadGameObjectFromDB(), and SaveRespawnTime().
m_goInfo
GameObjectTemplate const* GameObject::m_goInfo protected
Definition at line 1004 of file GameObject.h.
Referenced by MotionTransport::CalculateSegmentPos(), Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), GameObject(), GetGOInfo(), IsInRange(), and SetDestructibleState().
m_goValue
GameObjectValue GameObject::m_goValue protected
Definition at line 1006 of file GameObject.h.
Referenced by Create(), StaticTransport::Create(), GetGOValue(), StaticTransport::GetPeriod(), ModifyHealth(), StaticTransport::RelocateToProgress(), SetDestructibleState(), Transport::SetPathProgress(), StaticTransport::Update(), and Update().
m_groupLootTimer
uint32 GameObject::m_groupLootTimer
Definition at line 885 of file GameObject.h.
Referenced by GameObject(), and Update().
m_linkedTrap
ObjectGuid GameObject::m_linkedTrap protected
Definition at line 1018 of file GameObject.h.
Referenced by GetLinkedTrap(), and SetLinkedTrap().
m_localRotation
G3D::Quat GameObject::m_localRotation protected
Definition at line 1010 of file GameObject.h.
Referenced by GetLocalRotation(), SaveToDB(), SetLocalRotation(), and UpdatePackedRotation().
m_lootGenerationTime
uint32 GameObject::m_lootGenerationTime protected
Definition at line 1016 of file GameObject.h.
Referenced by GameObject(), GetLootGenerationTime(), and SetLootGenerationTime().
m_LootMode
uint16 GameObject::m_LootMode protected
Definition at line 1015 of file GameObject.h.
Referenced by AddLootMode(), GetLootMode(), HasLootMode(), RemoveLootMode(), ResetLootMode(), and SetLootMode().
m_lootRecipient
ObjectGuid GameObject::m_lootRecipient protected
Definition at line 1013 of file GameObject.h.
Referenced by GetLootRecipient(), HasLootRecipient(), IsLootAllowedFor(), and SetLootRecipient().
m_lootRecipientGroup
ObjectGuid::LowType GameObject::m_lootRecipientGroup protected
Definition at line 1014 of file GameObject.h.
Referenced by GameObject(), GetLootRecipientGroup(), HasLootRecipient(), IsLootAllowedFor(), and SetLootRecipient().
m_lootState
LootState GameObject::m_lootState protected
Definition at line 990 of file GameObject.h.
Referenced by GameObject(), getLootState(), ResetDoorOrButton(), SetLootState(), Update(), and UseDoorOrButton().
m_model
GameObjectModel* GameObject::m_model
Definition at line 944 of file GameObject.h.
Referenced by AddToWorld(), Create(), StaticTransport::Create(), MotionTransport::CreateMoTrans(), EnableCollision(), RemoveFromWorld(), SetGoState(), SetPhaseMask(), UpdateModel(), UpdateModelPosition(), and ~GameObject().
m_packedRotation
int64 GameObject::m_packedRotation protected
Definition at line 1009 of file GameObject.h.
Referenced by GameObject(), GetPackedLocalRotation(), and UpdatePackedRotation().
m_respawnDelayTime
uint32 GameObject::m_respawnDelayTime protected
Definition at line 987 of file GameObject.h.
Referenced by GameObject(), GetRespawnDelay(), isSpawned(), LoadGameObjectFromDB(), SaveToDB(), SetRespawnDelay(), and Update().
m_respawnTime
time_t GameObject::m_respawnTime protected
Definition at line 986 of file GameObject.h.
Referenced by GameObject(), GetRespawnTime(), GetRespawnTimeEx(), isSpawned(), LoadGameObjectFromDB(), Refresh(), Respawn(), SaveRespawnTime(), SetRespawnTime(), and Update().
m_ritualOwnerGUID
ObjectGuid GameObject::m_ritualOwnerGUID protected
Definition at line 996 of file GameObject.h.
Referenced by Update(), and Use().
m_SkillupList
GuidList GameObject::m_SkillupList protected
Definition at line 994 of file GameObject.h.
Referenced by AddToSkillupList(), ClearSkillupList(), IsInSkillupList(), and Update().
m_spawnedByDefault
bool GameObject::m_spawnedByDefault protected
Definition at line 991 of file GameObject.h.
Referenced by GameObject(), isSpawned(), isSpawnedByDefault(), LoadGameObjectFromDB(), Refresh(), Respawn(), SaveRespawnTime(), SaveToDB(), SetOwnerGUID(), SetRespawnTime(), SetSpawnedByDefault(), SetSpellId(), and Update().
m_spawnId
ObjectGuid::LowType GameObject::m_spawnId protected
For new or temporary gameobjects is 0 for saved it is lowguid.
Definition at line 1003 of file GameObject.h.
Referenced by AddToWorld(), Delete(), DeleteFromDB(), DespawnOrUnsummon(), GameObject(), GetRespawnPosition(), GetSpawnId(), LoadGameObjectFromDB(), RemoveFromWorld(), Respawn(), SaveRespawnTime(), SaveToDB(), SetGoArtKit(), Update(), and Use().
m_spellId
uint32 GameObject::m_spellId protected
Definition at line 985 of file GameObject.h.
Referenced by GameObject(), GetSpellId(), RemoveFromOwner(), and SetSpellId().
m_stationaryPosition
Position GameObject::m_stationaryPosition protected
Definition at line 1011 of file GameObject.h.
Referenced by Create(), StaticTransport::Create(), GameObject(), GetStationaryO(), GetStationaryX(), GetStationaryY(), and GetStationaryZ().
m_unique_users
GuidSet GameObject::m_unique_users protected
Definition at line 997 of file GameObject.h.
Referenced by AddUniqueUse(), CheckRitualList(), ClearRitualList(), GetUniqueUseCount(), and Update().
m_usetimes
uint32 GameObject::m_usetimes protected
Definition at line 998 of file GameObject.h.
Referenced by AddUse(), GameObject(), GetUseCount(), and Update().
The documentation for this class was generated from the following files:
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/GameObject/GameObject.cpp