Azerotcore-wotlk: boss_ahune::boss_ahuneAI Struct Reference
boss_ahune::boss_ahuneAI Struct Reference
Public Member Functions
boss_ahuneAI (Creature *c)
bool CanBeSeen (Player const *player) override
void StartPhase1 ()
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void EnterEvadeMode () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
ObjectGuid InvokerGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 90 of file boss_ahune.cpp.
Constructor & Destructor Documentation
boss_ahuneAI()
boss_ahune::boss_ahuneAI::boss_ahuneAI (Creature * c) inline
Definition at line 92 of file boss_ahune.cpp.
                                   : ScriptedAI(c), summons(me)
         {
             SetCombatMovement(false);
             SetEquipmentSlots(false, 54806, EQUIP_UNEQUIP, EQUIP_UNEQUIP);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             InvokerGUID.Clear();
             events.Reset();
             events.RescheduleEvent(EVENT_EMERGE, 12000);
             events.RescheduleEvent(EVENT_INVOKER_SAY_1, 1000);
             events.RescheduleEvent(EVENT_SUMMON_TOTEMS, 4000);
         }
References ObjectGuid::Clear(), EQUIP_UNEQUIP, EVENT_EMERGE, EVENT_INVOKER_SAY_1, EVENT_SUMMON_TOTEMS, InvokerGUID, ScriptedAI::me, ScriptedAI::SetCombatMovement(), ScriptedAI::SetEquipmentSlots(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Member Function Documentation
CanBeSeen()
bool boss_ahune::boss_ahuneAI::CanBeSeen (Player const * player) inline override virtual
Reimplemented from CreatureAI.
Definition at line 108 of file boss_ahune.cpp.
         {
             if (player->IsGameMaster())
             {
                 return true;
             }
             Group const* group = player->GetGroup();
             return group && sLFGMgr->GetDungeon(group->GetGUID()) == lfg::LFG_DUNGEON_FROST_LORD_AHUNE;
         }
References Player::GetGroup(), Group::GetGUID(), Player::IsGameMaster(), lfg::LFG_DUNGEON_FROST_LORD_AHUNE, and sLFGMgr.
EnterCombat()
void boss_ahune::boss_ahuneAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 128 of file boss_ahune.cpp.
         {
             DoZoneInCombat();
             events.Reset();
             StartPhase1();
         }
References CreatureAI::DoZoneInCombat(), and StartPhase1().
EnterEvadeMode()
void boss_ahune::boss_ahuneAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 263 of file boss_ahune.cpp.
         {
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             events.Reset();
             summons.DespawnAll();
             me->DespawnOrUnsummon(1);
             ScriptedAI::EnterEvadeMode();
         }
References SummonList::DespawnAll(), Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Object::SetFlag(), summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by UpdateAI().
JustDied()
void boss_ahune::boss_ahuneAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 296 of file boss_ahune.cpp.
         {
             summons.DespawnAll();
             me->DespawnOrUnsummon(15000);
             if (GameObject* chest = me->SummonGameObject(187892, MinionSummonPos.GetPositionX(), MinionSummonPos.GetPositionY(), MinionSummonPos.GetPositionZ(), M_PI / 2, 0.0f, 0.0f, 0.0f, 0.0f, 900000000)) // loot
                 me->RemoveGameObject(chest, false);
             bool finished = false;
             Map::PlayerList const& players = me->GetMap()->GetPlayers();
             if (!players.isEmpty())
                 for (Map::PlayerList::const_iterator i = players.begin(); i != players.end(); ++i)
                     if (Player* player = i->GetSource())
                     {
                         player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, 25740, 1, me);
                         if (player->GetGroup() && !finished)
{
                             finished = true;
                             sLFGMgr->FinishDungeon(player->GetGroup()->GetGUID(), lfg::LFG_DUNGEON_FROST_LORD_AHUNE, me->FindMap());
                         }
                     }
         }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, MapRefMgr::begin(), SummonList::DespawnAll(), Creature::DespawnOrUnsummon(), MapRefMgr::end(), WorldObject::FindMap(), WorldObject::GetMap(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LinkedListHead::isEmpty(), lfg::LFG_DUNGEON_FROST_LORD_AHUNE, M_PI, ScriptedAI::me, MinionSummonPos, Unit::RemoveGameObject(), sLFGMgr, WorldObject::SummonGameObject(), and summons.
JustSummoned()
void boss_ahune::boss_ahuneAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 273 of file boss_ahune.cpp.
         {
             if (summon)
             {
                 summons.Summon(summon);
                 summon->SetInCombatWithZone();
             }
         }
References Creature::SetInCombatWithZone(), SummonList::Summon(), and summons.
MoveInLineOfSight()
void boss_ahune::boss_ahuneAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 261 of file boss_ahune.cpp.
 {}
StartPhase1()
void boss_ahune::boss_ahuneAI::StartPhase1 () inline
Definition at line 119 of file boss_ahune.cpp.
         {
             me->CastSpell(me, SPELL_AHUNES_SHIELD, true);
             events.RescheduleEvent(EVENT_TOTEMS_ATTACK, 80000);
             events.RescheduleEvent(EVENT_SPELL_COLD_SLAP, 1200);
             events.RescheduleEvent(EVENT_SPELL_SUMMON_HAILSTONE, 2000);
             events.RescheduleEvent(EVENT_SPELL_SUMMON_COLDWAVE, 5000);
         }
References Unit::CastSpell(), EVENT_SPELL_COLD_SLAP, EVENT_SPELL_SUMMON_COLDWAVE, EVENT_SPELL_SUMMON_HAILSTONE, EVENT_TOTEMS_ATTACK, ScriptedAI::me, and SPELL_AHUNES_SHIELD.
Referenced by EnterCombat(), and UpdateAI().
SummonedCreatureDespawn()
void boss_ahune::boss_ahuneAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 282 of file boss_ahune.cpp.
         {
             if (summon && summon->GetEntry() == NPC_FROZEN_CORE)
             {
                 if (summon->GetHealth() > 0)
                 {
                     me->SetHealth(summon->GetHealth());
                     summon->CastSpell(summon, SPELL_AHUNE_RESURFACES, true);
                 }
                 else
                     Unit::Kill(me, me, false);
             }
         }
References Unit::CastSpell(), Object::GetEntry(), Unit::GetHealth(), Unit::Kill(), ScriptedAI::me, NPC_FROZEN_CORE, Unit::SetHealth(), and SPELL_AHUNE_RESURFACES.
UpdateAI()
void boss_ahune::boss_ahuneAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 135 of file boss_ahune.cpp.
         {
             if (!UpdateVictim() && !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_EMERGE:
                     me->SetVisible(true);
                     me->CastSpell(me, SPELL_EMERGE_0, false);
                     events.RescheduleEvent(EVENT_ATTACK, 2000);
                     break;
                 case EVENT_SUMMON_TOTEMS:
                     for (uint8 i = 0; i < 3; ++i)
                         DoSummon(NPC_TOTEM, TotemPos[i], 10 * 60 * 1000, TEMPSUMMON_TIMED_DESPAWN);
                     break;
                 case EVENT_INVOKER_SAY_1:
                     if (Player* plr = ObjectAccessor::GetPlayer(*me, InvokerGUID))
                     {
                         plr->Say("The Ice Stone has melted!", LANG_UNIVERSAL);
                         plr->CastSpell(plr, SPELL_MAKE_BONFIRE, true);
                     }
                     events.RescheduleEvent(EVENT_INVOKER_SAY_2, 2000);
                     break;
                 case EVENT_INVOKER_SAY_2:
                     if (Player* plr = ObjectAccessor::GetPlayer(*me, InvokerGUID))
                         plr->Say("Ahune, your strength grows no more!", LANG_UNIVERSAL);
                     events.RescheduleEvent(EVENT_INVOKER_SAY_3, 2000);
                     break;
                 case EVENT_INVOKER_SAY_3:
                     if (Player* plr = ObjectAccessor::GetPlayer(*me, InvokerGUID))
                         plr->Say("Your frozen reign will not come to pass!", LANG_UNIVERSAL);
                     break;
                 case EVENT_ATTACK:
                     events.Reset();
                     if (Player* plr = ObjectAccessor::GetPlayer(*me, InvokerGUID))
                         AttackStart(plr);
                     me->SetInCombatWithZone();
                     if (!me->IsInCombat())
                     {
                         EnterEvadeMode();
                         return;
                     }
                     else
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     break;
                 case EVENT_TOTEMS_ATTACK:
                     for (uint8 i = 0; i < 3; ++i)
                         if (Creature* bunny = me->FindNearestCreature(NPC_TOTEM_BUNNY_1 + i, 150.0f, true))
                             bunny->CastSpell(me, SPELL_TOTEM_BEAM, false);
                     events.RescheduleEvent(EVENT_SUBMERGE, 10000);
                     break;
                 case EVENT_SUBMERGE:
                     me->TextEmote(TEXT_RETREAT, nullptr, true);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->CastSpell(me, SPELL_SUBMERGE_0, true);
                     me->CastSpell(me, SPELL_SELF_STUN, true);
                     if (Creature* c = DoSummon(NPC_FROZEN_CORE, *me, 24000, TEMPSUMMON_TIMED_DESPAWN))
                     {
                         c->SetHealth(me->GetHealth());
                     }
                     events.Reset();
                     events.RescheduleEvent(EVENT_COMBAT_EMERGE, 25000);
                     events.RescheduleEvent(EVENT_EMERGE_WARNING, 20000);
                     break;
                 case EVENT_EMERGE_WARNING:
                     me->TextEmote(TEXT_RESURFACE, nullptr, true);
                     break;
                 case EVENT_COMBAT_EMERGE:
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->RemoveAura(SPELL_SELF_STUN);
                     me->CastSpell(me, SPELL_EMERGE_0, false);
                     // me->CastSpell(me, SPELL_AHUNE_RESURFACES, true); // done in SummonedCreatureDespawn
                     me->RemoveAura(SPELL_SUBMERGE_0);
                     StartPhase1();
                     break;
                 case EVENT_SPELL_COLD_SLAP:
                     if (Unit* target = SelectTarget(SELECT_TARGET_NEAREST, 0, 5.0f, true))
                         if (target->GetPositionZ() < me->GetPositionZ() + 6.0f)
{
                             int32 dmg = urand(5500, 6000);
                             me->CastCustomSpell(target, SPELL_COLD_SLAP, &dmg, nullptr, nullptr, false);
                             float x, y, z;
                             target->GetNearPoint(target, x, y, z, target->GetObjectSize(), 30.0f, target->GetAngle(me->GetPositionX(), me->GetPositionY()) + M_PI);
                             target->GetMotionMaster()->MoveJump(x, y, z + 20.0f, 10.0f, 20.0f);
                         }
                     events.RepeatEvent(1500);
                     break;
                 case EVENT_SPELL_SUMMON_HAILSTONE:
                     {
                         float dist = (float)urand(3, 10);
                         float angle = rand_norm() * 2 * M_PI;
                         me->CastSpell(MinionSummonPos.GetPositionX() + cos(angle)*dist, MinionSummonPos.GetPositionY() + sin(angle)*dist, MinionSummonPos.GetPositionZ(), SPELL_SUMMON_HAILSTONE, false);
                         events.RepeatEvent(30000);
                     }
                     break;
                 case EVENT_SPELL_SUMMON_COLDWAVE:
                     for (uint8 i = 0; i < 2; ++i)
                     {
                         float dist = (float)urand(3, 10);
                         float angle = rand_norm() * 2 * M_PI;
                         me->CastSpell(MinionSummonPos.GetPositionX() + cos(angle)*dist, MinionSummonPos.GetPositionY() + sin(angle)*dist, MinionSummonPos.GetPositionZ(), SPELL_SUMMON_COLDWAVE, false);
                     }
                     {
                         float dist = (float)urand(3, 10);
                         float angle = rand_norm() * 2 * M_PI;
                         me->CastSpell(MinionSummonPos.GetPositionX() + cos(angle)*dist, MinionSummonPos.GetPositionY() + sin(angle)*dist, MinionSummonPos.GetPositionZ(), SPELL_SUMMON_FROSTWIND, false);
                     }
                     events.RepeatEvent(6000);
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ScriptedAI::AttackStart(), mpq::c, Unit::CastCustomSpell(), Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::DoSummon(), EnterEvadeMode(), EVENT_ATTACK, EVENT_COMBAT_EMERGE, EVENT_EMERGE, EVENT_EMERGE_WARNING, EVENT_INVOKER_SAY_1, EVENT_INVOKER_SAY_2, EVENT_INVOKER_SAY_3, EVENT_SPELL_COLD_SLAP, EVENT_SPELL_SUMMON_COLDWAVE, EVENT_SPELL_SUMMON_HAILSTONE, EVENT_SUBMERGE, EVENT_SUMMON_TOTEMS, EVENT_TOTEMS_ATTACK, WorldObject::FindNearestCreature(), Unit::GetHealth(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::HasFlag(), Unit::HasUnitState(), InvokerGUID, Unit::IsInCombat(), LANG_UNIVERSAL, M_PI, ScriptedAI::me, MinionSummonPos, NPC_FROZEN_CORE, NPC_TOTEM, NPC_TOTEM_BUNNY_1, rand_norm(), Unit::RemoveAura(), Object::RemoveFlag(), SELECT_TARGET_NEAREST, UnitAI::SelectTarget(), Object::SetFlag(), Creature::SetInCombatWithZone(), Unit::SetVisible(), SPELL_COLD_SLAP, SPELL_EMERGE_0, SPELL_MAKE_BONFIRE, SPELL_SELF_STUN, SPELL_SUBMERGE_0, SPELL_SUMMON_COLDWAVE, SPELL_SUMMON_FROSTWIND, SPELL_SUMMON_HAILSTONE, SPELL_TOTEM_BEAM, StartPhase1(), TEMPSUMMON_TIMED_DESPAWN, TEXT_RESURFACE, TEXT_RETREAT, Unit::TextEmote(), TotemPos, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), G3D::x, G3D::y, and G3D::z.
Member Data Documentation
events
EventMap boss_ahune::boss_ahuneAI::events
Definition at line 104 of file boss_ahune.cpp.
InvokerGUID
ObjectGuid boss_ahune::boss_ahuneAI::InvokerGUID
Definition at line 106 of file boss_ahune.cpp.
Referenced by boss_ahuneAI(), and UpdateAI().
summons
SummonList boss_ahune::boss_ahuneAI::summons
Definition at line 105 of file boss_ahune.cpp.
Referenced by EnterEvadeMode(), JustDied(), and JustSummoned().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp