Azerotcore-wotlk: deps/mysqllite/include/internal/my_rdtsc.h File Reference
my_rdtsc.h File Reference
Classes
struct my_timer_unit_info
struct my_timer_info
Macros
#define MY_TIMER_ROUTINE_ASM_X86 1
#define MY_TIMER_ROUTINE_ASM_X86_64 2
#define MY_TIMER_ROUTINE_RDTSCLL 3
#define MY_TIMER_ROUTINE_ASM_X86_WIN 4
#define MY_TIMER_ROUTINE_RDTSC 5
#define MY_TIMER_ROUTINE_ASM_IA64 6
#define MY_TIMER_ROUTINE_ASM_PPC 7
#define MY_TIMER_ROUTINE_SGI_CYCLE 8
#define MY_TIMER_ROUTINE_GETHRTIME 9
#define MY_TIMER_ROUTINE_READ_REAL_TIME 10
#define MY_TIMER_ROUTINE_CLOCK_GETTIME 11
#define MY_TIMER_ROUTINE_NXGETTIME 12
#define MY_TIMER_ROUTINE_GETTIMEOFDAY 13
#define MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER 14
#define MY_TIMER_ROUTINE_GETTICKCOUNT 15
#define MY_TIMER_ROUTINE_TIME 16
#define MY_TIMER_ROUTINE_TIMES 17
#define MY_TIMER_ROUTINE_FTIME 18
#define MY_TIMER_ROUTINE_ASM_PPC64 19
#define MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC64 20
#define MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC32 21
#define MY_TIMER_ROUTINE_ASM_SUNPRO_I386 22
#define MY_TIMER_ROUTINE_ASM_GCC_SPARC64 23
#define MY_TIMER_ROUTINE_ASM_GCC_SPARC32 24
#define MY_TIMER_ROUTINE_MACH_ABSOLUTE_TIME 25
#define MY_TIMER_ROUTINE_GETSYSTEMTIMEASFILETIME 26
#define MY_TIMER_ROUTINE_ASM_SUNPRO_X86_64 27
Typedefs
typedef struct my_timer_info MY_TIMER_INFO
Functions
C_MODE_START ulonglong my_timer_cycles (void)
ulonglong my_timer_nanoseconds (void)
ulonglong my_timer_microseconds (void)
ulonglong my_timer_milliseconds (void)
ulonglong my_timer_ticks (void)
void my_timer_init (MY_TIMER_INFO *mti)
Macro Definition Documentation
MY_TIMER_ROUTINE_ASM_GCC_SPARC32
#define MY_TIMER_ROUTINE_ASM_GCC_SPARC32 24
Definition at line 123 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_GCC_SPARC64
#define MY_TIMER_ROUTINE_ASM_GCC_SPARC64 23
Definition at line 122 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_IA64
#define MY_TIMER_ROUTINE_ASM_IA64 6
Definition at line 105 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_PPC
#define MY_TIMER_ROUTINE_ASM_PPC 7
Definition at line 106 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_PPC64
#define MY_TIMER_ROUTINE_ASM_PPC64 19
Definition at line 118 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_SUNPRO_I386
#define MY_TIMER_ROUTINE_ASM_SUNPRO_I386 22
Definition at line 121 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC32
#define MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC32 21
Definition at line 120 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC64
#define MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC64 20
Definition at line 119 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_SUNPRO_X86_64
#define MY_TIMER_ROUTINE_ASM_SUNPRO_X86_64 27
Definition at line 126 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_X86
#define MY_TIMER_ROUTINE_ASM_X86 1
Definition at line 100 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_X86_64
#define MY_TIMER_ROUTINE_ASM_X86_64 2
Definition at line 101 of file my_rdtsc.h.
MY_TIMER_ROUTINE_ASM_X86_WIN
#define MY_TIMER_ROUTINE_ASM_X86_WIN 4
Definition at line 103 of file my_rdtsc.h.
MY_TIMER_ROUTINE_CLOCK_GETTIME
#define MY_TIMER_ROUTINE_CLOCK_GETTIME 11
Definition at line 110 of file my_rdtsc.h.
MY_TIMER_ROUTINE_FTIME
#define MY_TIMER_ROUTINE_FTIME 18
Definition at line 117 of file my_rdtsc.h.
MY_TIMER_ROUTINE_GETHRTIME
#define MY_TIMER_ROUTINE_GETHRTIME 9
Definition at line 108 of file my_rdtsc.h.
MY_TIMER_ROUTINE_GETSYSTEMTIMEASFILETIME
#define MY_TIMER_ROUTINE_GETSYSTEMTIMEASFILETIME 26
Definition at line 125 of file my_rdtsc.h.
MY_TIMER_ROUTINE_GETTICKCOUNT
#define MY_TIMER_ROUTINE_GETTICKCOUNT 15
Definition at line 114 of file my_rdtsc.h.
MY_TIMER_ROUTINE_GETTIMEOFDAY
#define MY_TIMER_ROUTINE_GETTIMEOFDAY 13
Definition at line 112 of file my_rdtsc.h.
MY_TIMER_ROUTINE_MACH_ABSOLUTE_TIME
#define MY_TIMER_ROUTINE_MACH_ABSOLUTE_TIME 25
Definition at line 124 of file my_rdtsc.h.
MY_TIMER_ROUTINE_NXGETTIME
#define MY_TIMER_ROUTINE_NXGETTIME 12
Definition at line 111 of file my_rdtsc.h.
MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER
#define MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER 14
Definition at line 113 of file my_rdtsc.h.
MY_TIMER_ROUTINE_RDTSC
#define MY_TIMER_ROUTINE_RDTSC 5
Definition at line 104 of file my_rdtsc.h.
MY_TIMER_ROUTINE_RDTSCLL
#define MY_TIMER_ROUTINE_RDTSCLL 3
Definition at line 102 of file my_rdtsc.h.
MY_TIMER_ROUTINE_READ_REAL_TIME
#define MY_TIMER_ROUTINE_READ_REAL_TIME 10
Definition at line 109 of file my_rdtsc.h.
MY_TIMER_ROUTINE_SGI_CYCLE
#define MY_TIMER_ROUTINE_SGI_CYCLE 8
Definition at line 107 of file my_rdtsc.h.
MY_TIMER_ROUTINE_TIME
#define MY_TIMER_ROUTINE_TIME 16
Definition at line 115 of file my_rdtsc.h.
MY_TIMER_ROUTINE_TIMES
#define MY_TIMER_ROUTINE_TIMES 17
Definition at line 116 of file my_rdtsc.h.
Typedef Documentation
MY_TIMER_INFO
typedef struct my_timer_info MY_TIMER_INFO
Definition at line 1 of file my_rdtsc.h.
Function Documentation
my_timer_cycles()
C_MODE_START ulonglong my_timer_cycles (void)
A cycle timer.
Returns
the current timer value, in cycles.
Definition at line 134 of file my_rdtsc.c.
 {
 #if defined(__GNUC__) && defined(__i386__)
   /* This works much better if compiled with "gcc -O3". */
   ulonglong result;
   __asm__ __volatile__ ("rdtsc" : "=A" (result));
   return result;
 #elif defined(__SUNPRO_C) && defined(__i386)
   __asm("rdtsc");
 #elif defined(__GNUC__) && defined(__x86_64__)
   ulonglong result;
   __asm__ __volatile__ ("rdtsc\n\t" \
                         "shlq $32,%%rdx\n\t" \
                         "orq %%rdx,%%rax"
                         : "=a" (result) :: "%edx");
   return result;
 #elif defined(HAVE_ASM_MSR_H) && defined(HAVE_RDTSCLL)
   {
     ulonglong result;
     rdtscll(result);
     return result;
   }
 #elif defined(_WIN32) && defined(_M_IX86)
   __asm {rdtsc};
 #elif defined(_WIN64) && defined(_M_X64)
   /* For 64-bit Windows: unsigned __int64 __rdtsc(); */
   return __rdtsc();
 #elif defined(__INTEL_COMPILER) && defined(__ia64__) && defined(HAVE_IA64INTRIN_H)
   return (ulonglong) __getReg(_IA64_REG_AR_ITC); /* (3116) */
 #elif defined(__GNUC__) && defined(__ia64__)
   {
     ulonglong result;
     __asm __volatile__ ("mov %0=ar.itc" : "=r" (result));
     return result;
   }
 #elif defined(__GNUC__) && (defined(__powerpc__) || defined(__POWERPC__) || (defined(_POWER) && defined(_AIX52))) && (defined(__64BIT__) || defined(_ARCH_PPC64))
   {
     ulonglong result;
     __asm __volatile__ ("mftb %0" : "=r" (result));
     return result;
   }
 #elif defined(__GNUC__) && (defined(__powerpc__) || defined(__POWERPC__) || (defined(_POWER) && defined(_AIX52))) && (!defined(__64BIT__) && !defined(_ARCH_PPC64))
   {
     /*
       mftbu means "move from time-buffer-upper to result".
       The loop is saying: x1=upper, x2=lower, x3=upper,
       if x1!=x3 there was an overflow so repeat.
     */
     unsigned int x1, x2, x3;
     ulonglong result;
     for (;;)
     {
        __asm __volatile__ ( "mftbu %0" : "=r"(x1) );
        __asm __volatile__ ( "mftb %0" : "=r"(x2) );
        __asm __volatile__ ( "mftbu %0" : "=r"(x3) );
        if (x1 == x3) break;
     }
     result = x1;
     return ( result << 32 ) | x2;
   }
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__sparcv9) && defined(_LP64) && !defined(__SunOS_5_7)
   return (my_timer_cycles_il_sparc64());
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(_ILP32) && !defined(__SunOS_5_7)
   return (my_timer_cycles_il_sparc32());
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__i386) && defined(_ILP32)
   /* This is probably redundant for __SUNPRO_C. */
   return (my_timer_cycles_il_i386());
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__x86_64) && defined(_LP64)
   return (my_timer_cycles_il_x86_64());
 #elif defined(__GNUC__) && defined(__sparcv9) && defined(_LP64)  && (__GNUC__>2)
   {
     ulonglong result;
     __asm __volatile__ ("rd %%tick,%0" : "=r" (result));
     return result;
   }
 #elif defined(__GNUC__) && defined(__sparc__) && !defined(_LP64) && (__GNUC__>2)
   {
       union {
               ulonglong wholeresult;
               struct {
                       ulong high;
                       ulong low;
               }       splitresult;
       } result;
     __asm __volatile__ ("rd %%tick,%1; srlx %1,32,%0" : "=r" (result.splitresult.high), "=r" (result.splitresult.low));
     return result.wholeresult;
   }
 #elif defined(__sgi) && defined(HAVE_CLOCK_GETTIME) && defined(CLOCK_SGI_CYCLE)
   {
     struct timespec tp;
     clock_gettime(CLOCK_SGI_CYCLE, &tp);
     return (ulonglong) tp.tv_sec * 1000000000 + (ulonglong) tp.tv_nsec;
   }
 #elif defined(HAVE_SYS_TIMES_H) && defined(HAVE_GETHRTIME)
   /* gethrtime may appear as either cycle or nanosecond counter */
   return (ulonglong) gethrtime();
 #else
   return 0;
 #endif
 }
Referenced by my_timer_init(), and my_timer_init_frequency().
my_timer_init()
void my_timer_init (MY_TIMER_INFO * mti)
Timer initialization function.
Parameters
[out] mti the timer characteristics.
Definition at line 493 of file my_rdtsc.c.
 {
   ulonglong (*best_timer)(void);
   ulonglong best_timer_overhead;
   ulonglong time1, time2;
   int i;
   /* cycles */
   mti->cycles.frequency= 1000000000;
 #if defined(__GNUC__) && defined(__i386__)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_X86;
 #elif defined(__SUNPRO_C) && defined(__i386)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_X86;
 #elif defined(__GNUC__) && defined(__x86_64__)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_X86_64;
 #elif defined(HAVE_ASM_MSR_H) && defined(HAVE_RDTSCLL)
   mti->cycles.routine= MY_TIMER_ROUTINE_RDTSCLL;
 #elif defined(_WIN32) && defined(_M_IX86)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_X86_WIN;
 #elif defined(_WIN64) && defined(_M_X64)
   mti->cycles.routine= MY_TIMER_ROUTINE_RDTSC;
 #elif defined(__INTEL_COMPILER) && defined(__ia64__) && defined(HAVE_IA64INTRIN_H)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_IA64;
 #elif defined(__GNUC__) && defined(__ia64__)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_IA64;
 #elif defined(__GNUC__) && (defined(__powerpc__) || defined(__POWERPC__) || (defined(_POWER) && defined(_AIX52))) && (defined(__64BIT__) || defined(_ARCH_PPC64))
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_PPC64;
 #elif defined(__GNUC__) && (defined(__powerpc__) || defined(__POWERPC__) || (defined(_POWER) && defined(_AIX52))) && (!defined(__64BIT__) && !defined(_ARCH_PPC64))
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_PPC;
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__sparcv9) && defined(_LP64) && !defined(__SunOS_5_7)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC64;
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(_ILP32) && !defined(__SunOS_5_7)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC32;
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__i386) && defined(_ILP32)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_SUNPRO_I386;
 #elif (defined(__SUNPRO_CC) || defined(__SUNPRO_C)) && defined(__x86_64) && defined(_LP64)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_SUNPRO_X86_64;
 #elif defined(__GNUC__) && defined(__sparcv9) && defined(_LP64) && (__GNUC__>2)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_GCC_SPARC64;
 #elif defined(__GNUC__) && defined(__sparc__) && !defined(_LP64) && (__GNUC__>2)
   mti->cycles.routine= MY_TIMER_ROUTINE_ASM_GCC_SPARC32;
 #elif defined(__sgi) && defined(HAVE_CLOCK_GETTIME) && defined(CLOCK_SGI_CYCLE)
   mti->cycles.routine= MY_TIMER_ROUTINE_SGI_CYCLE;
 #elif defined(HAVE_SYS_TIMES_H) && defined(HAVE_GETHRTIME)
   mti->cycles.routine= MY_TIMER_ROUTINE_GETHRTIME;
 #else
   mti->cycles.routine= 0;
 #endif
   if (!mti->cycles.routine || !my_timer_cycles())
   {
     mti->cycles.routine= 0;
     mti->cycles.resolution= 0;
     mti->cycles.frequency= 0;
     mti->cycles.overhead= 0;
   }
   /* nanoseconds */
   mti->nanoseconds.frequency=  1000000000; /* initial assumption */
 #if defined(HAVE_READ_REAL_TIME)
   mti->nanoseconds.routine= MY_TIMER_ROUTINE_READ_REAL_TIME;
 #elif defined(HAVE_SYS_TIMES_H) && defined(HAVE_GETHRTIME)
   mti->nanoseconds.routine= MY_TIMER_ROUTINE_GETHRTIME;
 #elif defined(HAVE_CLOCK_GETTIME)
   mti->nanoseconds.routine= MY_TIMER_ROUTINE_CLOCK_GETTIME;
 #elif defined(__APPLE__) && defined(__MACH__)
   mti->nanoseconds.routine= MY_TIMER_ROUTINE_MACH_ABSOLUTE_TIME;
 #else
   mti->nanoseconds.routine= 0;
 #endif
   if (!mti->nanoseconds.routine || !my_timer_nanoseconds())
   {
     mti->nanoseconds.routine= 0;
     mti->nanoseconds.resolution= 0;
     mti->nanoseconds.frequency= 0;
     mti->nanoseconds.overhead= 0;
   }
   /* microseconds */
   mti->microseconds.frequency= 1000000; /* initial assumption */
 #if defined(HAVE_GETTIMEOFDAY)
    mti->microseconds.routine= MY_TIMER_ROUTINE_GETTIMEOFDAY;
 #elif defined(_WIN32)
   {
     LARGE_INTEGER li;
     /* Windows: typical frequency = 3579545, actually 1/3 microsecond. */
     if (!QueryPerformanceFrequency(&li))
       mti->microseconds.routine= 0;
     else
     {
       mti->microseconds.frequency= li.QuadPart;
       mti->microseconds.routine= MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER;
     }
   }
 #else
   mti->microseconds.routine= 0;
 #endif
   if (!mti->microseconds.routine || !my_timer_microseconds())
   {
     mti->microseconds.routine= 0;
     mti->microseconds.resolution= 0;
     mti->microseconds.frequency= 0;
     mti->microseconds.overhead= 0;
   }
   /* milliseconds */
   mti->milliseconds.frequency= 1000; /* initial assumption */
 #if defined(HAVE_SYS_TIMEB_H) && defined(HAVE_FTIME)
   mti->milliseconds.routine= MY_TIMER_ROUTINE_FTIME;
 #elif defined(_WIN32)
   mti->milliseconds.routine= MY_TIMER_ROUTINE_GETSYSTEMTIMEASFILETIME;
 #elif defined(HAVE_TIME)
   mti->milliseconds.routine= MY_TIMER_ROUTINE_TIME;
 #else
   mti->milliseconds.routine= 0;
 #endif
   if (!mti->milliseconds.routine || !my_timer_milliseconds())
   {
     mti->milliseconds.routine= 0;
     mti->milliseconds.resolution= 0;
     mti->milliseconds.frequency= 0;
     mti->milliseconds.overhead= 0;
   }
   /* ticks */
   mti->ticks.frequency= 100; /* permanent assumption */
 #if defined(HAVE_SYS_TIMES_H) && defined(HAVE_TIMES)
   mti->ticks.routine= MY_TIMER_ROUTINE_TIMES;
 #elif defined(_WIN32)
   mti->ticks.routine= MY_TIMER_ROUTINE_GETTICKCOUNT;
 #else
   mti->ticks.routine= 0;
 #endif
   if (!mti->ticks.routine || !my_timer_ticks())
   {
     mti->ticks.routine= 0;
     mti->ticks.resolution= 0;
     mti->ticks.frequency= 0;
     mti->ticks.overhead= 0;
   }
   /*
     Calculate overhead in terms of the timer that
     gives the best resolution: cycles or nanoseconds.
     I doubt it ever will be as bad as microseconds.
   */
   if (mti->cycles.routine)
     best_timer= &my_timer_cycles;
   else
   {
     if (mti->nanoseconds.routine)
     {
       best_timer= &my_timer_nanoseconds;
     }
     else
       best_timer= &my_timer_microseconds;
   }
   /* best_timer_overhead = least of 20 calculations */
   for (i= 0, best_timer_overhead= 1000000000; i < 20; ++i)
   {
     time1= best_timer();
     time2= best_timer() - time1;
     if (best_timer_overhead > time2)
       best_timer_overhead= time2;
   }
   if (mti->cycles.routine)
     my_timer_init_overhead(&mti->cycles.overhead,
                            best_timer,
                            &my_timer_cycles,
                            best_timer_overhead);
   if (mti->nanoseconds.routine)
     my_timer_init_overhead(&mti->nanoseconds.overhead,
                            best_timer,
                            &my_timer_nanoseconds,
                            best_timer_overhead);
   if (mti->microseconds.routine)
     my_timer_init_overhead(&mti->microseconds.overhead,
                            best_timer,
                            &my_timer_microseconds,
                            best_timer_overhead);
   if (mti->milliseconds.routine)
     my_timer_init_overhead(&mti->milliseconds.overhead,
                            best_timer,
                            &my_timer_milliseconds,
                            best_timer_overhead);
   if (mti->ticks.routine)
     my_timer_init_overhead(&mti->ticks.overhead,
                            best_timer,
                            &my_timer_ticks,
                            best_timer_overhead);
 /*
   Calculate resolution for nanoseconds or microseconds
   or milliseconds, by seeing if it's always divisible
   by 1000, and by noticing how much jumping occurs.
   For ticks, just assume the resolution is 1.
 */
   if (mti->cycles.routine)
     mti->cycles.resolution= 1;
   if (mti->nanoseconds.routine)
     mti->nanoseconds.resolution=
     my_timer_init_resolution(&my_timer_nanoseconds, 20000);
   if (mti->microseconds.routine)
     mti->microseconds.resolution=
     my_timer_init_resolution(&my_timer_microseconds, 20);
   if (mti->milliseconds.routine)
   {
     if (mti->milliseconds.routine == MY_TIMER_ROUTINE_TIME)
       mti->milliseconds.resolution= 1000;
     else
       mti->milliseconds.resolution=
       my_timer_init_resolution(&my_timer_milliseconds, 0);
   }
   if (mti->ticks.routine)
     mti->ticks.resolution= 1;
 /*
   Calculate cycles frequency,
   if we have both a cycles routine and a microseconds routine.
   In tests, this usually results in a figure within 2% of
   what "cat /proc/cpuinfo" says.
   If the microseconds routine is QueryPerformanceCounter
   (i.e. it's Windows), and the microseconds frequency is >
   500,000,000 (i.e. it's Windows Server so it uses RDTSC)
   and the microseconds resolution is > 100 (i.e. dreadful),
   then calculate cycles frequency = microseconds frequency.
 */
   if (mti->cycles.routine
   &&  mti->microseconds.routine)
   {
     if (mti->microseconds.routine ==
     MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER
     &&  mti->microseconds.frequency > 500000000
     &&  mti->microseconds.resolution > 100)
       mti->cycles.frequency= mti->microseconds.frequency;
     else
     {
       ulonglong time1, time2;
       time1= my_timer_init_frequency(mti);
       /* Repeat once in case there was an interruption. */
       time2= my_timer_init_frequency(mti);
       if (time1 < time2) mti->cycles.frequency= time1;
       else mti->cycles.frequency= time2;
     }
   }
 /*
   Calculate milliseconds frequency =
   (cycles-frequency/#-of-cycles) * #-of-milliseconds,
   if we have both a milliseconds routine and a cycles
   routine.
   This will be inaccurate if milliseconds resolution > 1.
   This is probably only useful when testing new platforms.
 */
   if (mti->milliseconds.routine
   &&  mti->milliseconds.resolution < 1000
   &&  mti->microseconds.routine
   &&  mti->cycles.routine)
   {
     int i;
     ulonglong time1, time2, time3, time4;
     time1= my_timer_cycles();
     time2= my_timer_milliseconds();
     time3= time2; /* Avoids a Microsoft/IBM compiler warning */
     for (i= 0; i < MY_TIMER_ITERATIONS * 1000; ++i)
     {
       time3= my_timer_milliseconds();
       if (time3 - time2 > 10) break;
     }
     time4= my_timer_cycles();
     mti->milliseconds.frequency=
     (mti->cycles.frequency * (time3 - time2)) / (time4 - time1);
   }
 /*
   Calculate ticks.frequency =
   (cycles-frequency/#-of-cycles * #-of-ticks,
   if we have both a ticks routine and a cycles
   routine,
   This is probably only useful when testing new platforms.
 */
   if (mti->ticks.routine
   &&  mti->microseconds.routine
   &&  mti->cycles.routine)
   {
     int i;
     ulonglong time1, time2, time3, time4;
     time1= my_timer_cycles();
     time2= my_timer_ticks();
     time3= time2; /* Avoids a Microsoft/IBM compiler warning */
     for (i= 0; i < MY_TIMER_ITERATIONS * 1000; ++i)
     {
       time3= my_timer_ticks();
       if (time3 - time2 > 10) break;
     }
     time4= my_timer_cycles();
     mti->ticks.frequency=
     (mti->cycles.frequency * (time3 - time2)) / (time4 - time1);
   }
 }
References my_timer_info::cycles, my_timer_unit_info::frequency, my_timer_info::microseconds, my_timer_cycles(), my_timer_nanoseconds(), MY_TIMER_ROUTINE_ASM_GCC_SPARC32, MY_TIMER_ROUTINE_ASM_GCC_SPARC64, MY_TIMER_ROUTINE_ASM_IA64, MY_TIMER_ROUTINE_ASM_PPC, MY_TIMER_ROUTINE_ASM_PPC64, MY_TIMER_ROUTINE_ASM_SUNPRO_I386, MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC32, MY_TIMER_ROUTINE_ASM_SUNPRO_SPARC64, MY_TIMER_ROUTINE_ASM_SUNPRO_X86_64, MY_TIMER_ROUTINE_ASM_X86, MY_TIMER_ROUTINE_ASM_X86_64, MY_TIMER_ROUTINE_ASM_X86_WIN, MY_TIMER_ROUTINE_CLOCK_GETTIME, MY_TIMER_ROUTINE_GETHRTIME, MY_TIMER_ROUTINE_GETTIMEOFDAY, MY_TIMER_ROUTINE_MACH_ABSOLUTE_TIME, MY_TIMER_ROUTINE_QUERYPERFORMANCECOUNTER, MY_TIMER_ROUTINE_RDTSC, MY_TIMER_ROUTINE_RDTSCLL, MY_TIMER_ROUTINE_READ_REAL_TIME, MY_TIMER_ROUTINE_SGI_CYCLE, my_timer_info::nanoseconds, my_timer_unit_info::overhead, my_timer_unit_info::resolution, and my_timer_unit_info::routine.
my_timer_microseconds()
ulonglong my_timer_microseconds (void)
A microseconds timer.
Returns
the current timer value, in microseconds.
Definition at line 287 of file my_rdtsc.c.
 {
 #if defined(HAVE_GETTIMEOFDAY)
   {
     static ulonglong last_value= 0;
     struct timeval tv;
     if (gettimeofday(&tv, NULL) == 0)
       last_value= (ulonglong) tv.tv_sec * 1000000 + (ulonglong) tv.tv_usec;
     else
     {
       /*
         There are reports that gettimeofday(2) can have intermittent failures
         on some platform, see for example Bug#36819.
         We are not trying again or looping, just returning the best value possible
         under the circumstances ...
       */
       last_value++;
     }
     return last_value;
   }
 #elif defined(_WIN32)
   {
     /* QueryPerformanceCounter usually works with about 1/3 microsecond. */
     LARGE_INTEGER t_cnt;
     QueryPerformanceCounter(&t_cnt);
     return (ulonglong) t_cnt.QuadPart;
   }
 #else
   return 0;
 #endif
 }
References NULL.
Referenced by my_timer_init_frequency().
my_timer_milliseconds()
ulonglong my_timer_milliseconds (void)
A millisecond timer.
Returns
the current timer value, in milliseconds.
Definition at line 327 of file my_rdtsc.c.
 {
 #if defined(HAVE_SYS_TIMEB_H) && defined(HAVE_FTIME)
   /* ftime() is obsolete but maybe the platform is old */
   struct timeb ft;
   ftime(&ft);
   return (ulonglong)ft.time * 1000 + (ulonglong)ft.millitm;
 #elif defined(HAVE_TIME)
   return (ulonglong) time(NULL) * 1000;
 #elif defined(_WIN32)
    FILETIME ft;
    GetSystemTimeAsFileTime( &ft );
    return ((ulonglong)ft.dwLowDateTime +
                   (((ulonglong)ft.dwHighDateTime) << 32))/10000;
 #else
   return 0;
 #endif
 }
References NULL.
my_timer_nanoseconds()
ulonglong my_timer_nanoseconds (void)
A namoseconds timer.
Returns
the current timer value, in nanoseconds.
Definition at line 247 of file my_rdtsc.c.
 {
 #if defined(HAVE_READ_REAL_TIME)
   {
     timebasestruct_t tr;
     read_real_time(&tr, TIMEBASE_SZ);
     return (ulonglong) tr.tb_high * 1000000000 + (ulonglong) tr.tb_low;
   }
 #elif defined(HAVE_SYS_TIMES_H) && defined(HAVE_GETHRTIME)
   /* SunOS 5.10+, Solaris, HP-UX: hrtime_t gethrtime(void) */
   return (ulonglong) gethrtime();
 #elif defined(HAVE_CLOCK_GETTIME) && defined(CLOCK_REALTIME)
   {
     struct timespec tp;
     clock_gettime(CLOCK_REALTIME, &tp);
     return (ulonglong) tp.tv_sec * 1000000000 + (ulonglong) tp.tv_nsec;
   }
 #elif defined(__APPLE__) && defined(__MACH__)
   {
     ulonglong tm;
     static mach_timebase_info_data_t timebase_info= {0,0};
     if (timebase_info.denom == 0)
       (void) mach_timebase_info(&timebase_info);
     tm= mach_absolute_time();
     return (tm * timebase_info.numer) / timebase_info.denom;
   }
 #else
   return 0;
 #endif
 }
Referenced by my_timer_init().
my_timer_ticks()
ulonglong my_timer_ticks (void)
A ticks timer.
Returns
the current timer value, in ticks.
Definition at line 352 of file my_rdtsc.c.
 {
 #if defined(HAVE_SYS_TIMES_H) && defined(HAVE_TIMES)
   {
     struct tms times_buf;
     return (ulonglong) times(&times_buf);
   }
 #elif defined(_WIN32)
   return (ulonglong) GetTickCount();
 #else
   return 0;
 #endif
 }