Azerotcore-wotlk: deps/mysqllite/mysys/base64.c File Reference
base64.c File Reference
#include <my_global.h>
#include <m_string.h>
#include <m_ctype.h>
#include <base64.h>
Macros
#define SKIP_SPACE(src, i, size)
Functions
int base64_needed_encoded_length (int length_of_data)
int base64_needed_decoded_length (int length_of_encoded_data)
int base64_encode (const void *src, size_t src_len, char *dst)
static uint pos (unsigned char c)
int base64_decode (const char *src_base, size_t len, void *dst, const char **end_ptr)
Variables
static char base64_table []
Macro Definition Documentation
SKIP_SPACE
#define SKIP_SPACE (src, i, size)
Value:
{                                                               \
  while (i < size && my_isspace(&my_charset_latin1, * src))     \
  {                                                             \
    i++;                                                        \
    src++;                                                      \
  }                                                             \
  if (i == size)                                                \
  {                                                             \
    break;                                                      \
  }                                                             \
}
Definition at line 110 of file base64.c.
Function Documentation
base64_decode()
int base64_decode (const char * src_base, size_t len, void * dst, const char ** end_ptr)
Definition at line 155 of file base64.c.
 {
   char b[3];
   size_t i= 0;
   char *dst_base= (char *)dst;
   char const *src= src_base;
   char *d= dst_base;
   size_t j;
   while (i < len)
   {
     unsigned c= 0;
     size_t mark= 0;
     SKIP_SPACE(src, i, len);
     c += pos(*src++);
     c <<= 6;
     i++;
     SKIP_SPACE(src, i, len);
     c += pos(*src++);
     c <<= 6;
     i++;
     SKIP_SPACE(src, i, len);
     if (*src != '=')
       c += pos(*src++);
     else
     {
       src += 2;                /* There should be two bytes padding */
       i= len;
       mark= 2;
       c <<= 6;
       goto end;
     }
     c <<= 6;
     i++;
     SKIP_SPACE(src, i, len);
     if (*src != '=')
       c += pos(*src++);
     else
     {
       src += 1;                 /* There should be one byte padding */
       i= len;
       mark= 1;
       goto end;
     }
     i++;
   end:
     b[0]= (c >> 16) & 0xff;
     b[1]= (c >>  8) & 0xff;
     b[2]= (c >>  0) & 0xff;
     for (j=0; j<3-mark; j++)
       *d++= b[j];
   }
   if (end_ptr != NULL)
     *end_ptr= src;
   /*
     The variable 'i' is set to 'len' when padding has been read, so it
     does not actually reflect the number of bytes read from 'src'.
    */
   return i != len ? -1 : (int) (d - dst_base);
 }
References b, mpq::c, mpq::d, NULL, pos(), and SKIP_SPACE.
base64_encode()
int base64_encode (const void * src, size_t src_len, char * dst)
Definition at line 56 of file base64.c.
 {
   const unsigned char *s= (const unsigned char*)src;
   size_t i= 0;
   size_t len= 0;
   for (; i < src_len; len += 4)
   {
     unsigned c;
     if (len == 76)
     {
       len= 0;
       *dst++= '\n';
     }
     c= s[i++];
     c <<= 8;
     if (i < src_len)
       c += s[i];
     c <<= 8;
     i++;
     if (i < src_len)
       c += s[i];
     i++;
     *dst++= base64_table[(c >> 18) & 0x3f];
     *dst++= base64_table[(c >> 12) & 0x3f];
     if (i > (src_len + 1))
       *dst++= '=';
     else
       *dst++= base64_table[(c >> 6) & 0x3f];
     if (i > src_len)
       *dst++= '=';
     else
       *dst++= base64_table[(c >> 0) & 0x3f];
   }
   *dst= '\0';
   return 0;
 }
References base64_table, and mpq::c.
base64_needed_decoded_length()
int base64_needed_decoded_length (int length_of_encoded_data)
Definition at line 42 of file base64.c.
 {
   return (int) ceil(length_of_encoded_data * 3 / 4);
 }
References G3D::ceil().
base64_needed_encoded_length()
int base64_needed_encoded_length (int length_of_data)
Definition at line 29 of file base64.c.
 {
   int nb_base64_chars;
   nb_base64_chars= (length_of_data + 2) / 3 * 4;
   return
     nb_base64_chars +            /* base64 char incl padding */
     (nb_base64_chars - 1)/ 76 +  /* newlines */
     1;                           /* NUL termination of string */
 }
pos()
static uint pos (unsigned char c) inline static
Definition at line 104 of file base64.c.
 {
   return (uint) (strchr(base64_table, c) - base64_table);
 }
References base64_table, and mpq::c.
Referenced by Battleground::_CheckSafePositions(), _db_dump_(), Unit::_ExitVehicle(), Guild::BankMoveItemData::_ReserveSpace(), Guild::BankMoveItemData::_StoreItem(), Player::_StoreItem(), dtNavMeshQuery::appendVertex(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), base64_decode(), Player::BeginCinematic(), MySQLPreparedStatement::BindParameters(), Player::BuildPlayerTalentsInfoData(), buildPolyDetail(), ByteBufferPositionException::ByteBufferPositionException(), ByteBufferSourceException::ByteBufferSourceException(), BZ2_decompress(), dtNavMesh::calcTileLoc(), ScriptMgr::CanSaveEquipNewItem(), ScriptMgr::CanUnequipItem(), Player::CanUnequipItem(), check_scramble_323(), Acore::Hyperlinks::CheckAllLinks(), Spell::CheckCast(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), cleanup_dirname(), cli_read_prepare_result(), cli_read_query_result(), cli_safe_read(), anonymous_namespace{DetourNavMesh.cpp}::closestPointOnDetailEdges(), dtNavMesh::closestPointOnPoly(), dtNavMeshQuery::closestPointOnPoly(), dtNavMeshQuery::closestPointOnPolyBoundary(), G3D::CollisionDetection::collisionTimeForMovingPointFixedBox(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedBox(), ConvertADT(), VMAP::VMapMgr2::convertPositionToInternalRep(), DynamicObject::CreateDynamicObject(), boss_headless_horseman::boss_headless_horsemanAI::DamageTaken(), decimal_round(), decode_distance(), G3D::GImage::decodeTGA(), dirname_length(), Acore::WorldWorldTextBuilder::do_helper(), tele_commandscript::DoNameTeleport(), CreatureAI::DoSummon(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), CreatureAI::DoSummonFlyer(), go_commandscript::DoTeleport(), Player::DurabilityRepair(), Spell::EffectCharge(), Spell::EffectChargeDest(), Spell::EffectPullTowards(), Spell::EffectStuck(), Spell::EffectSummonChangeItem(), Spell::EffectSummonType(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), Player::EquipItem(), Player::EquipNewItem(), VehicleDespawnEvent::Execute(), IceTombSummonEvent::Execute(), fill_memory_blocks_mt(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::FillPositions(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), find_file_in_path(), find_set_from_flags(), find_type(), fixNULLfields(), flush_key_blocks_int(), flush_one_result(), fn_ext(), fn_format(), get_password(), Position::GetAbsoluteAngle(), VMAP::VMapMgr2::GetAreaAndLiquidData(), MapMgr::GetAreaId(), VMAP::StaticMapTree::GetAreaInfo(), VMAP::VMapMgr2::GetAreaInfo(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getCellCoord(), WorldObject::GetDistance(), Position::GetExactDist(), Position::GetExactDist2d(), Position::GetExactDist2dSq(), Position::GetExactDistSq(), WorldObject::GetFirstCollisionPosition(), VMAP::VMapMgr2::getHeight(), WorldObject::GetHitSpherePointFor(), Player::GetItemByPos(), VMAP::WmoLiquid::GetLiquidHeight(), VMAP::GroupModel::GetLiquidLevel(), VMAP::VMapMgr2::GetLiquidLevel(), VMAP::StaticMapTree::GetLocationInfo(), Unit::GetMeleeAttackPoint(), WorldObject::GetNearPosition(), Creature::GetPetAutoSpellOnPos(), Pet::GetPetAutoSpellOnPos(), dtNavMesh::getPolyHeight(), dtNavMeshQuery::getPolyHeight(), MySQLPreparedStatement::getQueryString(), WorldObject::GetRandomNearPosition(), WorldObject::GetRandomPoint(), Position::GetRelativeAngle(), GetTalentSpellCost(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::getValidRandomPosition(), MapMgr::GetZoneId(), handle_options(), WorldSession::HandleDestroyItemOpcode(), spell_moroes_vanish::spell_moroes_vanish_SpellScript::HandleDummy(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::HandleEvent(), gobject_commandscript::HandleGameObjectMoveCommand(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleMessagechatOpcode(), spell_gen_haunted::HandleOnEffectHit(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_rimefang_icy_blast::spell_rimefang_icy_blast_SpellScript::HandleTriggerMissile(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), hashcmp(), init_io_cache(), GameObjectModel::initialize(), inline_mysql_file_fseek(), inline_mysql_file_seek(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), GameObject::IsAtInteractDistance(), Player::IsBagPos(), Player::IsBankPos(), Player::IsEquipmentPos(), Position::IsInDist(), Position::IsInDist2d(), ScriptedAI::IsInRoom(), VMAP::GroupModel::IsInsideObject(), Player::IsInventoryPos(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), MapMgr::IsValidMapCoord(), Player::IsValidPos(), WorldObject::IsWithinDist2d(), WorldObject::IsWithinDist3d(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), Movement::MoveSplineInit::Launch(), ChatHandler::LineFromMessage(), Acore::WorldWorldTextBuilder::lineFromMessage(), Channel::List(), lock_io_cache(), main(), memdup_root(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), SpellCastTargets::ModDst(), SpellCastTargets::ModSrc(), MotionMaster::MoveBackwards(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveJump(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), WorldObject::MovePosition(), WorldObject::MovePositionToFirstCollision(), MotionMaster::MoveTakeoff(), my_b_gets(), my_b_seek(), my_block_write(), my_charpos_8bit(), my_checksum(), my_fseek(), my_ftell(), my_get_ptr(), my_getwd(), my_hash_delete(), my_hash_first_from_hash_value(), my_hash_insert(), my_hash_next(), my_hash_rec_mask(), my_hash_sort_8bit_bin(), my_hash_sort_bin(), my_hash_update(), my_print_default_files(), my_real_read(), my_seek(), my_setwd(), my_store_ptr(), my_tell(), mysql_get_server_version(), mysql_list_processes(), Unit::NearTeleportTo(), net_field_length(), net_field_length_ll(), net_real_write(), net_store_datetime(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnPlayerEnter(), ByteBuffer::operator[](), basic_string_view< Char >::operator[](), opt_flush_ok_packet(), parse_name(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), G3D::GLight::point(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), PredictPosition(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), ByteBuffer::put(), Player::QuickEquipItem(), rcMarkCylinderArea(), ByteBuffer::read(), read_binary_date(), read_binary_datetime(), read_binary_time(), read_one_row(), WorldSession::ReadAddonsInfo(), ReadBuild(), reinit_io_cache(), Position::Relocate(), SpellDestination::Relocate(), StaticTransport::RelocateToProgress(), Utils::Replace(), Spell::SearchTargets(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTargetDestTargets(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SelectPosition(), CreatureTextMgr::SendChat(), World::SendGlobalText(), Warden::SendModuleToClient(), sendMTFValues(), Unit::SendTeleportPacket(), instance_gundrak::instance_gundrak_InstanceMapScript::SetBossState(), Player::SetClientControl(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData(), spell_item_recall::SetDest(), SpellCastTargets::SetDst(), Creature::SetHomePosition(), Creature::SetPosition(), GameObject::SetPosition(), SpellCastTargets::SetSrc(), Creature::SetTransportHomePosition(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::SetVictimPos(), soap_getposition(), sort_locks(), Battlefield::SpawnCreature(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::spawnVoidTraveler(), SpellDestination::SpellDestination(), boss_gothik::boss_gothikAI::SpellHit(), G3D::GLight::spot(), G3D::GLight::spotTarget(), npc_stillpine_capitive::npc_stillpine_capitiveAI::StartMoving(), Movement::MoveSplineInit::Stop(), store_param_null(), store_param_time(), store_param_type(), Guild::BankMoveItemData::StoreItem(), Player::StoreItem(), stripLineInvisibleChars(), strlength(), strmake_root(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Summon(), Map::SummonCreature(), WorldObject::SummonCreature(), Spell::SummonGuardian(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), boss_amanitar::boss_amanitarAI::SummonMushroom(), Player::SummonPet(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), boss_netherspite::boss_netherspiteAI::SummonPortals(), test_gzio(), thr_lock_merge_status(), thr_multi_unlock(), spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::ThrowNextTorch(), unpack_fields(), MotionTransport::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_mechanar::instance_mechanar_InstanceMapScript::Update(), npc_cyclone::npc_cycloneAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), npc_doomfire_targetting::npc_doomfire_targettingAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), GameObjectModel::UpdatePosition(), Player::UpdatePosition(), Unit::UpdatePosition(), Unit::UpdateSplinePosition(), WheatyExceptionReport::WheatyUnhandledExceptionFilter(), Guild::BankTab::WritePacket(), and Movement::PacketBuilder::WriteStopMovement().
Variable Documentation
base64_table
char base64_table[] static
Initial value:
= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                             "abcdefghijklmnopqrstuvwxyz"
                             "0123456789+/"
Definition at line 23 of file base64.c.
Referenced by base64_encode(), and pos().