Azerotcore-wotlk: MapEntry Struct Reference
MapEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
uint32 Expansion () const
bool IsDungeon () const
bool IsNonRaidDungeon () const
bool Instanceable () const
bool IsRaid () const
bool IsBattleground () const
bool IsBattleArena () const
bool IsBattlegroundOrArena () const
bool IsWorldMap () const
bool GetEntrancePos (int32 &mapid, float &x, float &y) const
bool IsContinent () const
bool IsDynamicDifficultyMap () const
Public Attributes
uint32 MapID
uint32 map_type
uint32 Flags
char const * name [16]
uint32 linked_zone
uint32 multimap_id
int32 entrance_map
float entrance_x
float entrance_y
uint32 addon
uint32 unk_time
uint32 maxPlayers
Detailed Description
Definition at line 1270 of file DBCStructure.h.
Member Function Documentation
Expansion()
uint32 MapEntry::Expansion () const inline
Definition at line 1295 of file DBCStructure.h.
 { return addon; }
References addon.
Referenced by Player::_LoadHomeBind(), GetContentLevelsForMapAndZone(), Player::LoadFromDB(), and Player::TeleportTo().
GetEntrancePos()
bool MapEntry::GetEntrancePos (int32 & mapid, float & x, float & y) const inline
Definition at line 1306 of file DBCStructure.h.
     {
         if (entrance_map < 0)
             return false;
         mapid = entrance_map;
         x = entrance_x;
         y = entrance_y;
         return true;
     }
References entrance_map, entrance_x, and entrance_y.
Referenced by Map::GetEntrancePos().
Instanceable()
bool MapEntry::Instanceable () const inline
Definition at line 1299 of file DBCStructure.h.
 { return map_type == MAP_INSTANCE || map_type == MAP_RAID || map_type == MAP_BATTLEGROUND || map_type == MAP_ARENA; }
References MAP_ARENA, MAP_BATTLEGROUND, MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by Player::_LoadHomeBind(), InstanceSaveMgr::_ResetOrWarnAll(), MapMgr::CreateBaseMap(), misc_commandscript::HandleSkirmishCommand(), Map::Instanceable(), Player::LoadFromDB(), ObjectMgr::LoadLinkedRespawn(), ObjectMgr::SetCreatureLinkedRespawn(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), and Player::TeleportTo().
IsBattleArena()
bool MapEntry::IsBattleArena () const inline
Definition at line 1302 of file DBCStructure.h.
 { return map_type == MAP_ARENA; }
References MAP_ARENA, and map_type.
Referenced by SpellInfo::CheckLocation(), Map::IsBattleArena(), and Player::TeleportTo().
IsBattleground()
bool MapEntry::IsBattleground () const inline
Definition at line 1301 of file DBCStructure.h.
 { return map_type == MAP_BATTLEGROUND; }
References MAP_BATTLEGROUND, and map_type.
Referenced by SpellInfo::CheckLocation(), and Map::IsBattleground().
IsBattlegroundOrArena()
bool MapEntry::IsBattlegroundOrArena () const inline
Definition at line 1303 of file DBCStructure.h.
 { return map_type == MAP_BATTLEGROUND || map_type == MAP_ARENA; }
References MAP_ARENA, MAP_BATTLEGROUND, and map_type.
Referenced by Graveyard::GetClosestGraveyard(), WorldSession::HandleMoveWorldportAck(), tele_commandscript::HandleTeleCommand(), tele_commandscript::HandleTeleGroupCommand(), Map::IsBattlegroundOrArena(), Player::LoadFromDB(), and Player::TeleportTo().
IsContinent()
bool MapEntry::IsContinent () const inline
Definition at line 1316 of file DBCStructure.h.
     {
         return MapID == 0 || MapID == 1 || MapID == 530 || MapID == 571;
     }
References MapID.
IsDungeon()
bool MapEntry::IsDungeon () const inline
Definition at line 1297 of file DBCStructure.h.
 { return map_type == MAP_INSTANCE || map_type == MAP_RAID; }
References MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by Spell::CheckCast(), ObjectMgr::GetGoBackTrigger(), WorldSession::HandleMoveWorldportAck(), DisableMgr::IsDisabledFor(), Map::IsDungeon(), MapMgr::IsValidMAP(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), lfg::LFGPlayerScript::OnBindToInstance(), and MapMgr::PlayerCannotEnter().
IsDynamicDifficultyMap()
bool MapEntry::IsDynamicDifficultyMap () const inline
Definition at line 1321 of file DBCStructure.h.
 { return Flags & MAP_FLAG_DYNAMIC_DIFFICULTY; }
References Flags, and MAP_FLAG_DYNAMIC_DIFFICULTY.
IsNonRaidDungeon()
bool MapEntry::IsNonRaidDungeon () const inline
Definition at line 1298 of file DBCStructure.h.
 { return map_type == MAP_INSTANCE; }
References MAP_INSTANCE, and map_type.
Referenced by Map::IsNonRaidDungeon(), and Player::LoadFromDB().
IsRaid()
bool MapEntry::IsRaid () const inline
Definition at line 1300 of file DBCStructure.h.
 { return map_type == MAP_RAID; }
References MAP_RAID, and map_type.
Referenced by InstanceSaveMgr::AddInstanceSave(), SpellInfo::CheckLocation(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandleSetSavedInstanceExtend(), lfg::LFGMgr::InitializeLockedDungeons(), DisableMgr::IsDisabledFor(), Map::IsRaid(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), MapMgr::PlayerCannotEnter(), Player::ResetInstances(), Group::ResetInstances(), and Player::Satisfy().
IsWorldMap()
bool MapEntry::IsWorldMap () const inline
Definition at line 1304 of file DBCStructure.h.
 { return map_type == MAP_COMMON; }
References MAP_COMMON, and map_type.
Member Data Documentation
addon
uint32 MapEntry::addon
Definition at line 1290 of file DBCStructure.h.
Referenced by Expansion().
entrance_map
int32 MapEntry::entrance_map
Definition at line 1286 of file DBCStructure.h.
Referenced by Graveyard::GetClosestGraveyard(), GetEntrancePos(), and ObjectMgr::GetGoBackTrigger().
entrance_x
float MapEntry::entrance_x
Definition at line 1287 of file DBCStructure.h.
Referenced by Graveyard::GetClosestGraveyard(), and GetEntrancePos().
entrance_y
float MapEntry::entrance_y
Definition at line 1288 of file DBCStructure.h.
Referenced by Graveyard::GetClosestGraveyard(), and GetEntrancePos().
Flags
uint32 MapEntry::Flags
Definition at line 1275 of file DBCStructure.h.
Referenced by IsDynamicDifficultyMap().
linked_zone
uint32 MapEntry::linked_zone
Definition at line 1279 of file DBCStructure.h.
Referenced by Map::GetAreaId(), and Map::GetFullTerrainStatusForPosition().
map_type
uint32 MapEntry::map_type
Definition at line 1274 of file DBCStructure.h.
Referenced by InstanceSaveMgr::AddInstanceSave(), InstanceSave::GetResetTimeForDB(), Instanceable(), IsBattleArena(), IsBattleground(), IsBattlegroundOrArena(), DisableMgr::IsDisabledFor(), IsDungeon(), IsNonRaidDungeon(), IsRaid(), IsWorldMap(), DisableMgr::LoadDisables(), and Pet::setDeathState().
MapID
uint32 MapEntry::MapID
Definition at line 1272 of file DBCStructure.h.
Referenced by Map::GetId(), WorldSession::HandleMoveWorldportAck(), IsContinent(), MapMgr::PlayerCannotEnter(), and World::SetInitialWorldSettings().
maxPlayers
uint32 MapEntry::maxPlayers
Definition at line 1292 of file DBCStructure.h.
Referenced by InstanceMap::GetMaxPlayers().
multimap_id
uint32 MapEntry::multimap_id
Definition at line 1284 of file DBCStructure.h.
name
char const* MapEntry::name[16]
Definition at line 1277 of file DBCStructure.h.
Referenced by Map::GetMapName(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandlePInfoCommand(), and MapMgr::PlayerCannotEnter().
unk_time
uint32 MapEntry::unk_time
Definition at line 1291 of file DBCStructure.h.
The documentation for this struct was generated from the following file:
src/server/shared/DataStores/DBCStructure.h