Azerotcore-wotlk: achievement_watch_him_die Class Reference
achievement_watch_him_die Class Reference
Public Member Functions
achievement_watch_him_die ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 231 of file boss_krikthir_the_gatewatcher.cpp.
Constructor & Destructor Documentation
achievement_watch_him_die()
achievement_watch_him_die::achievement_watch_him_die () inline
Definition at line 234 of file boss_krikthir_the_gatewatcher.cpp.
                                 : AchievementCriteriaScript("achievement_watch_him_die")
     {
     }
Member Function Documentation
OnCheck()
bool achievement_watch_him_die::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 238 of file boss_krikthir_the_gatewatcher.cpp.
     {
         if (!target)
             return false;
         return target->GetAI()->GetData(target->GetEntry());
     }
References Unit::GetAI(), UnitAI::GetData(), and Object::GetEntry().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_krikthir_the_gatewatcher.cpp