Azerotcore-wotlk: Acore::Crypto::ARC4 Class Reference
Acore::Crypto::ARC4 Class Reference
#include <ARC4.h>
Public Member Functions
ARC4 ()
~ARC4 ()
void Init (uint8 const *seed, size_t len)
template<typename Container >
void Init (Container const &c)
void UpdateData (uint8 *data, size_t len)
template<typename Container >
void UpdateData (Container &c)
Private Attributes
EVP_CIPHER_CTX * _ctx
Detailed Description
Definition at line 27 of file ARC4.h.
Constructor & Destructor Documentation
ARC4()
Acore::Crypto::ARC4::ARC4 ()
Definition at line 21 of file ARC4.cpp.
     : _ctx(EVP_CIPHER_CTX_new())
 {
     EVP_CIPHER_CTX_init(_ctx);
     int result = EVP_EncryptInit_ex(_ctx, EVP_rc4(), nullptr, nullptr, nullptr);
     ASSERT(result == 1);
 }
References _ctx, and ASSERT.
~ARC4()
Acore::Crypto::ARC4::~ARC4 ()
Definition at line 29 of file ARC4.cpp.
 {
     EVP_CIPHER_CTX_free(_ctx);
 }
Member Function Documentation
Init() [1/2]
template<typename Container > void Acore::Crypto::ARC4::Init (Container const & c) inline
Definition at line 35 of file ARC4.h.
 { Init(std::data(c), std::size(c)); }
References Init().
Referenced by Init().
Init() [2/2]
void Acore::Crypto::ARC4::Init (uint8 const * seed, size_t len)
Definition at line 34 of file ARC4.cpp.
 {
     int result1 = EVP_CIPHER_CTX_set_key_length(_ctx, len);
     ASSERT(result1 == 1);
     int result2 = EVP_EncryptInit_ex(_ctx, nullptr, nullptr, seed, nullptr);
     ASSERT(result2 == 1);
 }
References ASSERT.
Referenced by WardenMac::HandleHashResult(), WardenWin::HandleHashResult(), AuthCrypt::Init(), WardenMac::Init(), and WardenWin::Init().
UpdateData() [1/2]
template<typename Container > void Acore::Crypto::ARC4::UpdateData (Container & c) inline
Definition at line 39 of file ARC4.h.
 { UpdateData(std::data(c), std::size(c)); }
References UpdateData().
Referenced by UpdateData().
UpdateData() [2/2]
void Acore::Crypto::ARC4::UpdateData (uint8 * data, size_t len)
Definition at line 42 of file ARC4.cpp.
 {
     int outlen = 0;
     int result1 = EVP_EncryptUpdate(_ctx, data, &outlen, data, len);
     ASSERT(result1 == 1);
     int result2 = EVP_EncryptFinal_ex(_ctx, data, &outlen);
     ASSERT(result2 == 1);
 }
References ASSERT.
Referenced by Warden::DecryptData(), AuthCrypt::DecryptRecv(), Warden::EncryptData(), AuthCrypt::EncryptSend(), and AuthCrypt::Init().
Member Data Documentation
_ctx
EVP_CIPHER_CTX* Acore::Crypto::ARC4::_ctx private
Definition at line 41 of file ARC4.h.
Referenced by ARC4().
The documentation for this class was generated from the following files:
src/common/Cryptography/ARC4.h
src/common/Cryptography/ARC4.cpp