Azerotcore-wotlk: basic_string_view< Char > Class Template Reference
basic_string_view< Char > Class Template Reference
#include <core.h>
Public Types
using value_type = Char
using iterator = const Char *
Public Member Functions
constexpr basic_string_view () FMT_NOEXCEPT
constexpr basic_string_view (const Char *s, size_t count) FMT_NOEXCEPT
FMT_CONSTEXPR_CHAR_TRAITS FMT_INLINE basic_string_view (const Char *s)
template<typename Traits , typename Alloc >
FMT_CONSTEXPR basic_string_view (const std::basic_string< Char, Traits, Alloc > &s) FMT_NOEXCEPT
template<typename S , FMT_ENABLE_IF(std::is_same< S, detail::std_string_view< Char >>::value) >
FMT_CONSTEXPR basic_string_view (S s) FMT_NOEXCEPT
constexpr auto data () const -> const Char *
constexpr auto size () const -> size_t
constexpr auto begin () const -> iterator
constexpr auto end () const -> iterator
constexpr auto operator[] (size_t pos) const -> const Char &
FMT_CONSTEXPR void remove_prefix (size_t n)
FMT_CONSTEXPR_CHAR_TRAITS auto compare (basic_string_view other) const -> int
Private Attributes
const Char * data_
size_t size_
Friends
FMT_CONSTEXPR_CHAR_TRAITS friend auto operator== (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator!= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator< (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator<= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator> (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator>= (basic_string_view lhs, basic_string_view rhs) -> bool
Detailed Description
template<typename Char>
class basic_string_view< Char >
An implementation of std::basic_string_view for pre-C++17. It provides a subset of the API. fmt::basic_string_view is used for format strings even if std::string_view is available to prevent issues when a library is compiled with a different -std option than the client code (which is not recommended).
Definition at line 436 of file core.h.
Member Typedef Documentation
iterator
template<typename Char > using basic_string_view< Char >::iterator = const Char*
Definition at line 443 of file core.h.
value_type
template<typename Char > using basic_string_view< Char >::value_type = Char
Definition at line 442 of file core.h.
Constructor & Destructor Documentation
basic_string_view() [1/5]
template<typename Char > constexpr basic_string_view< Char >::basic_string_view () inline constexpr
Definition at line 445 of file core.h.
 : data_(nullptr), size_(0) {}
basic_string_view() [2/5]
template<typename Char > constexpr basic_string_view< Char >::basic_string_view (const Char * s, size_t count) inline constexpr
Constructs a string reference object from a C string and a size.
Definition at line 448 of file core.h.
       : data_(s),
         size_(count) {}
basic_string_view() [3/5]
template<typename Char > FMT_CONSTEXPR_CHAR_TRAITS FMT_INLINE basic_string_view< Char >::basic_string_view (const Char * s) inline
\rst Constructs a string reference object from a C string computing the size with std::char_traits<Char>::length. \endrst
Definition at line 460 of file core.h.
                                    : data_(s) {
     if (detail::const_check(std::is_same<Char, char>::value &&
                             !detail::is_constant_evaluated()))
       size_ = std::strlen(reinterpret_cast<const char*>(s));
     else
       size_ = std::char_traits<Char>::length(s);
   }
References const_check(), is_constant_evaluated(), G3D::length(), and basic_string_view< Char >::size_.
basic_string_view() [4/5]
template<typename Char > template<typename Traits , typename Alloc > FMT_CONSTEXPR basic_string_view< Char >::basic_string_view (const std::basic_string< Char, Traits, Alloc > & s) inline
Constructs a string reference from a std::basic_string object.
Definition at line 470 of file core.h.
       : data_(s.data()),
         size_(s.size()) {}
basic_string_view() [5/5]
template<typename Char > template<typename S , FMT_ENABLE_IF(std::is_same< S, detail::std_string_view< Char >>::value) > FMT_CONSTEXPR basic_string_view< Char >::basic_string_view (S s) inline
Definition at line 477 of file core.h.
                                                     : data_(s.data()),
                                                       size_(s.size()) {}
Member Function Documentation
begin()
template<typename Char > constexpr auto basic_string_view< Char >::begin () const -> iterator inline constexpr
Definition at line 486 of file core.h.
 { return data_; }
References basic_string_view< Char >::data_.
Referenced by copy_unit(), and formatter< std::chrono::duration< Rep, Period >, Char >::format().
compare()
template<typename Char > FMT_CONSTEXPR_CHAR_TRAITS auto basic_string_view< Char >::compare (basic_string_view< Char > other) const -> int inline
Definition at line 499 of file core.h.
{
     size_t str_size = size_ < other.size_ ? size_ : other.size_;
     int result = std::char_traits<Char>::compare(data_, other.data_, str_size);
     if (result == 0)
       result = size_ == other.size_ ? 0 : (size_ < other.size_ ? -1 : 1);
     return result;
   }
References basic_string_view< Char >::data_, and basic_string_view< Char >::size_.
data()
template<typename Char > constexpr auto basic_string_view< Char >::data () const -> const Char* inline constexpr
Returns a pointer to the string data.
Definition at line 481 of file core.h.
 { return data_; }
References basic_string_view< Char >::data_.
Referenced by detail::code_point_index(), detail_exported::compile_string_to_view(), detail::compute_width(), detail::for_each_codepoint(), parse_format_string(), detail::print(), value< Context >::value(), write(), and write_int_localized().
end()
template<typename Char > constexpr auto basic_string_view< Char >::end () const -> iterator inline constexpr
Definition at line 487 of file core.h.
 { return data_ + size_; }
References basic_string_view< Char >::data_, and basic_string_view< Char >::size_.
Referenced by copy_unit(), and formatter< std::chrono::duration< Rep, Period >, Char >::format().
operator[]()
template<typename Char > constexpr auto basic_string_view< Char >::operator[] (size_t pos) const -> const Char& inline constexpr
Definition at line 489 of file core.h.
{
     return data_[pos];
   }
References basic_string_view< Char >::data_, and pos().
remove_prefix()
template<typename Char > FMT_CONSTEXPR void basic_string_view< Char >::remove_prefix (size_t n) inline
Definition at line 493 of file core.h.
{
     data_ += n;
     size_ -= n;
   }
References basic_string_view< Char >::data_, and basic_string_view< Char >::size_.
Referenced by Acore::Hyperlinks::ParseSingleHyperlink().
size()
template<typename Char > constexpr auto basic_string_view< Char >::size () const -> size_t inline constexpr
Returns the string size.
Definition at line 484 of file core.h.
 { return size_; }
References basic_string_view< Char >::size_.
Referenced by detail::code_point_index(), detail_exported::compile_string_to_view(), detail::compute_width(), detail::for_each_codepoint(), fill_t< Char >::operator=(), parse_format_string(), detail::print(), value< Context >::value(), write(), and write_int_localized().
Friends And Related Function Documentation
operator!=
template<typename Char > auto operator!= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 512 of file core.h.
{
     return lhs.compare(rhs) != 0;
   }
operator<
template<typename Char > auto operator< (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 515 of file core.h.
{
     return lhs.compare(rhs) < 0;
   }
operator<=
template<typename Char > auto operator<= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 518 of file core.h.
{
     return lhs.compare(rhs) <= 0;
   }
operator==
template<typename Char > FMT_CONSTEXPR_CHAR_TRAITS friend auto operator== (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 507 of file core.h.
               {
     return lhs.compare(rhs) == 0;
   }
operator>
template<typename Char > auto operator> (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 521 of file core.h.
{
     return lhs.compare(rhs) > 0;
   }
operator>=
template<typename Char > auto operator>= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 524 of file core.h.
{
     return lhs.compare(rhs) >= 0;
   }
Member Data Documentation
data_
template<typename Char > const Char* basic_string_view< Char >::data_ private
Definition at line 438 of file core.h.
Referenced by basic_string_view< Char >::begin(), basic_string_view< Char >::compare(), basic_string_view< Char >::data(), basic_string_view< Char >::end(), basic_string_view< Char >::operator[](), and basic_string_view< Char >::remove_prefix().
size_
template<typename Char > size_t basic_string_view< Char >::size_ private
Definition at line 439 of file core.h.
Referenced by basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::compare(), basic_string_view< Char >::end(), basic_string_view< Char >::remove_prefix(), and basic_string_view< Char >::size().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h