Azerotcore-wotlk: npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI Struct Reference
npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI Struct Reference
Public Member Functions
npc_pet_dk_ebon_gargoyleAI (Creature *creature)
void MovementInform (uint32 type, uint32 point) override
void InitializeAI () override
void MySelectNextTarget ()
void AttackStart (Unit *who) override
void RemoveTargetAura ()
void Reset () override
void FlyAway ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
ObjectGuid _targetGUID
uint32 _despawnTimer
uint32 _selectionTimer
uint32 _initialCastTimer
bool _despawning
bool _initialSelection
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 47 of file pet_dk.cpp.
Constructor & Destructor Documentation
npc_pet_dk_ebon_gargoyleAI()
npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::npc_pet_dk_ebon_gargoyleAI (Creature * creature) inline
Definition at line 49 of file pet_dk.cpp.
                                                        : ScriptedAI(creature)
         {
             _despawnTimer = 36000; // 30 secs + 4 fly out + 2 initial attack timer
             _despawning = false;
             _initialSelection = true;
             _targetGUID.Clear();
         }
References _despawning, _despawnTimer, _initialSelection, _targetGUID, and ObjectGuid::Clear().
Member Function Documentation
AttackStart()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 115 of file pet_dk.cpp.
         {
             RemoveTargetAura();
             _targetGUID = who->GetGUID();
             me->AddAura(SPELL_DK_SUMMON_GARGOYLE_1, who);
             ScriptedAI::AttackStart(who);
         }
References _targetGUID, Unit::AddAura(), ScriptedAI::AttackStart(), Object::GetGUID(), ScriptedAI::me, RemoveTargetAura(), and SPELL_DK_SUMMON_GARGOYLE_1.
FlyAway()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway () inline
Definition at line 137 of file pet_dk.cpp.
         {
             RemoveTargetAura();
             // Stop Fighting
             me->CombatStop(true);
             me->ApplyModFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, true);
             // Sanctuary
             me->CastSpell(me, SPELL_DK_SANCTUARY, true);
             me->SetReactState(REACT_PASSIVE);
             me->SetSpeed(MOVE_FLIGHT, 1.0f, true);
             me->SetSpeed(MOVE_RUN, 1.0f, true);
             float x = me->GetPositionX() + 20 * cos(me->GetOrientation());
             float y = me->GetPositionY() + 20 * sin(me->GetOrientation());
             float z = me->GetPositionZ() + 40;
             me->DisableSpline();
             me->GetMotionMaster()->Clear(false);
             me->GetMotionMaster()->MoveCharge(x, y, z, 7.0f, 1);
             me->SetCanFly(true);
             me->SetDisableGravity(true);
             _despawning = true;
         }
References _despawning, Object::ApplyModFlag(), Unit::CastSpell(), MotionMaster::Clear(), Unit::CombatStop(), Unit::DisableSpline(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MOVE_FLIGHT, MOVE_RUN, MotionMaster::MoveCharge(), REACT_PASSIVE, RemoveTargetAura(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), Unit::SetSpeed(), SPELL_DK_SANCTUARY, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by UpdateAI().
InitializeAI()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 66 of file pet_dk.cpp.
         {
             ScriptedAI::InitializeAI();
             Unit* owner = me->GetOwner();
             if (!owner)
                 return;
             // Xinef: Night of the Dead avoidance
             if (Aura* aur = me->GetAura(SPELL_DK_NIGHT_OF_THE_DEAD))
                 if (AuraEffect* aurEff = owner->GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_DEATHKNIGHT, 2718, 0))
                 {
                     if (aur->GetEffect(0))
                     {
                         aur->GetEffect(0)->SetAmount(-aurEff->GetSpellInfo()->Effects[EFFECT_2].CalcValue());
                     }
                 }
             me->SetCanFly(true);
             me->SetDisableGravity(true);
             float tz = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), true, MAX_FALL_DISTANCE);
             me->GetMotionMaster()->MoveCharge(me->GetPositionX(), me->GetPositionY(), tz, 7.0f, 1);
             me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
             _selectionTimer = 2000;
             _initialCastTimer = 0;
         }
References _initialCastTimer, _selectionTimer, Unit::AddUnitState(), EFFECT_2, Unit::GetAura(), Unit::GetAuraEffect(), WorldObject::GetMapHeight(), Unit::GetMotionMaster(), Unit::GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), UnitAI::InitializeAI(), MAX_FALL_DISTANCE, ScriptedAI::me, MotionMaster::MoveCharge(), Creature::SetCanFly(), Creature::SetDisableGravity(), SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_DK_NIGHT_OF_THE_DEAD, SPELLFAMILY_DEATHKNIGHT, and UNIT_STATE_NO_ENVIRONMENT_UPD.
MovementInform()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 57 of file pet_dk.cpp.
         {
             if (type == POINT_MOTION_TYPE && point == 1)
             {
                 me->SetCanFly(false);
                 me->SetDisableGravity(false);
             }
         }
References ScriptedAI::me, POINT_MOTION_TYPE, Creature::SetCanFly(), and Creature::SetDisableGravity().
MySelectNextTarget()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget () inline
Definition at line 93 of file pet_dk.cpp.
         {
             Unit* owner = me->GetOwner();
             if (owner && owner->GetTypeId() == TYPEID_PLAYER && (!me->GetVictim() || me->GetVictim()->IsImmunedToSpell(sSpellMgr->GetSpellInfo(51963)) || !me->IsValidAttackTarget(me->GetVictim()) || !owner->CanSeeOrDetect(me->GetVictim())))
             {
                 Unit* selection = owner->ToPlayer()->GetSelectedUnit();
                 if (selection && selection != me->GetVictim() && me->IsValidAttackTarget(selection))
                 {
                     me->GetMotionMaster()->Clear(false);
                     SetGazeOn(selection);
                 }
                 else if (!me->GetVictim() || !owner->CanSeeOrDetect(me->GetVictim()))
                 {
                     me->CombatStop(true);
                     me->GetMotionMaster()->Clear(false);
                     me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, 0.0f);
                     RemoveTargetAura();
                 }
             }
         }
References WorldObject::CanSeeOrDetect(), MotionMaster::Clear(), Unit::CombatStop(), Unit::GetMotionMaster(), Unit::GetOwner(), Player::GetSelectedUnit(), Object::GetTypeId(), Unit::GetVictim(), Unit::IsImmunedToSpell(), Unit::IsValidAttackTarget(), ScriptedAI::me, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, RemoveTargetAura(), CreatureAI::SetGazeOn(), sSpellMgr, Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by Reset(), and UpdateAI().
RemoveTargetAura()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::RemoveTargetAura () inline
Definition at line 123 of file pet_dk.cpp.
         {
             if (Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID))
                 target->RemoveAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetGUID());
         }
References _targetGUID, Object::GetGUID(), ObjectAccessor::GetUnit(), ScriptedAI::me, and SPELL_DK_SUMMON_GARGOYLE_1.
Referenced by AttackStart(), FlyAway(), and MySelectNextTarget().
Reset()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 129 of file pet_dk.cpp.
         {
             _selectionTimer = 0;
             me->SetReactState(REACT_PASSIVE);
             MySelectNextTarget();
         }
References _selectionTimer, ScriptedAI::me, MySelectNextTarget(), REACT_PASSIVE, and Creature::SetReactState().
UpdateAI()
void npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 164 of file pet_dk.cpp.
         {
             if (_initialSelection)
             {
                 _initialSelection = false;
                 // Find victim of Summon Gargoyle spell
                 std::list<Unit*> targets;
                 Acore::AnyUnfriendlyUnitInObjectRangeCheck u_check(me, me, 50);
                 Acore::UnitListSearcher<Acore::AnyUnfriendlyUnitInObjectRangeCheck> searcher(me, targets, u_check);
                 Cell::VisitAllObjects(me, searcher, 50.0f);
                 for (std::list<Unit*>::const_iterator iter = targets.begin(); iter != targets.end(); ++iter)
                     if ((*iter)->GetAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetOwnerGUID()))
                     {
                         (*iter)->RemoveAura(SPELL_DK_SUMMON_GARGOYLE_1, me->GetOwnerGUID());
                         SetGazeOn(*iter);
                         _targetGUID = (*iter)->GetGUID();
                         break;
                     }
             }
             if (_despawnTimer > 4000)
             {
                 _despawnTimer -= diff;
                 if (!UpdateVictimWithGaze())
                 {
                     MySelectNextTarget();
                     return;
                 }
                 _initialCastTimer += diff;
                 _selectionTimer += diff;
                 if (_selectionTimer >= 1000)
                 {
                     MySelectNextTarget();
                     _selectionTimer = 0;
                 }
                 if (_initialCastTimer >= 2000 && !me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_LOST_CONTROL) && me->GetMotionMaster()->GetMotionSlotType(MOTION_SLOT_CONTROLLED) == NULL_MOTION_TYPE)
                     me->CastSpell(me->GetVictim(), 51963, false);
             }
             else
             {
                 if (!_despawning)
                     FlyAway();
                 if (_despawnTimer > diff)
                     _despawnTimer -= diff;
                 else
                     me->DespawnOrUnsummon();
             }
         }
References _despawning, _despawnTimer, _initialCastTimer, _initialSelection, _selectionTimer, _targetGUID, Unit::CastSpell(), Creature::DespawnOrUnsummon(), FlyAway(), Unit::GetMotionMaster(), MotionMaster::GetMotionSlotType(), Unit::GetOwnerGUID(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, MOTION_SLOT_CONTROLLED, MySelectNextTarget(), NULL_MOTION_TYPE, CreatureAI::SetGazeOn(), SPELL_DK_SUMMON_GARGOYLE_1, UNIT_STATE_CASTING, UNIT_STATE_LOST_CONTROL, CreatureAI::UpdateVictimWithGaze(), and Cell::VisitAllObjects().
Member Data Documentation
_despawning
bool npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_despawning private
Definition at line 219 of file pet_dk.cpp.
Referenced by FlyAway(), npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_despawnTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_despawnTimer private
Definition at line 216 of file pet_dk.cpp.
Referenced by npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_initialCastTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_initialCastTimer private
Definition at line 218 of file pet_dk.cpp.
Referenced by InitializeAI(), and UpdateAI().
_initialSelection
bool npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_initialSelection private
Definition at line 220 of file pet_dk.cpp.
Referenced by npc_pet_dk_ebon_gargoyleAI(), and UpdateAI().
_selectionTimer
uint32 npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_selectionTimer private
Definition at line 217 of file pet_dk.cpp.
Referenced by InitializeAI(), Reset(), and UpdateAI().
_targetGUID
ObjectGuid npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::_targetGUID private
Definition at line 215 of file pet_dk.cpp.
Referenced by AttackStart(), npc_pet_dk_ebon_gargoyleAI(), RemoveTargetAura(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Pet/pet_dk.cpp