Azerotcore-wotlk: boss_the_lich_king::boss_the_lich_kingAI Struct Reference
boss_the_lich_king::boss_the_lich_kingAI Struct Reference
Public Member Functions
boss_the_lich_kingAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void EnterCombat (Unit *target) override
void JustReachedHome () override
bool CanAIAttack (Unit const *target) const override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void SpellHit (Unit *, SpellInfo const *spell) override
void SpellHitTarget (Unit *, SpellInfo const *spell) override
void MovementInform (uint32 type, uint32 pointId) override
void UpdateAI (uint32 diff) override
uint32 GetData (uint32 type) const override
void SetData (uint32 type, uint32 value) override
void EnterEvadeMode () override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 _phase
uint32 _necroticPlagueStack
uint32 _vileSpiritExplosions
uint16 _positionCheckTimer
uint32 _lastTalkTimeKill
uint32 _lastTalkTimeBuff
bool _bFrostmournePhase
bool _bFordringMustFallYell
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 628 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
boss_the_lich_kingAI()
boss_the_lich_king::boss_the_lich_kingAI::boss_the_lich_kingAI (Creature * creature) inline
Definition at line 630 of file boss_the_lich_king.cpp.
                                                  : BossAI(creature, DATA_THE_LICH_KING)
         {
             me->AddAura(SPELL_EMOTE_SIT_NO_SHEATH, me);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             me->SetReactState(REACT_PASSIVE);
         }
References Unit::AddAura(), ScriptedAI::me, REACT_PASSIVE, Object::SetFlag(), Creature::SetReactState(), SPELL_EMOTE_SIT_NO_SHEATH, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Member Function Documentation
CanAIAttack()
bool boss_the_lich_king::boss_the_lich_kingAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 711 of file boss_the_lich_king.cpp.
         {
             return me->IsVisible() && IsValidPlatformTarget(target) && !target->GetVehicle();
         }
References Unit::GetVehicle(), IsValidPlatformTarget(), Unit::IsVisible(), and ScriptedAI::me.
DamageTaken()
void boss_the_lich_king::boss_the_lich_kingAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 763 of file boss_the_lich_king.cpp.
         {
             if (!attacker || (_bFrostmournePhase && attacker->GetExactDistSq(495.708f, -2523.76f, 1049.95f) > 40.0f * 40.0f)) // frostmourne room, prevent exploiting (tele hack to get back and damage him)
             {
                 damage = 0;
                 return;
             }
             if (_phase == PHASE_ONE && !HealthAbovePct(70) && !me->HasUnitState(UNIT_STATE_CASTING))
             {
                 _phase = PHASE_TRANSITION;
                 me->SetReactState(REACT_PASSIVE);
                 me->AttackStop();
                 events.CancelEventGroup(EVENT_GROUP_ABILITIES);
                 me->InterruptNonMeleeSpells(false);
                 me->GetMotionMaster()->MovePoint(POINT_CENTER_1, CenterPosition);
                 return;
             }
             if (_phase == PHASE_TWO && !HealthAbovePct(40) && !me->HasUnitState(UNIT_STATE_CASTING))
             {
                 _phase = PHASE_TRANSITION;
                 me->SetReactState(REACT_PASSIVE);
                 me->AttackStop();
                 events.CancelEventGroup(EVENT_GROUP_ABILITIES);
                 me->InterruptNonMeleeSpells(false);
                 me->GetMotionMaster()->MovePoint(POINT_CENTER_2, CenterPosition);
                 return;
             }
             if (_phase == PHASE_THREE && HealthBelowPct(10) && !me->HasUnitState(UNIT_STATE_CASTING))
             {
                 _phase = PHASE_OUTRO;
                 EntryCheckPredicate pred(NPC_STRANGULATE_VEHICLE);
                 summons.DoAction(ACTION_TELEPORT_BACK, pred);
                 events.Reset();
                 summons.DespawnAll();
                 me->SetReactState(REACT_PASSIVE);
                 me->AttackStop();
                 me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_FURY_OF_FROSTMOURNE);
                 me->InterruptNonMeleeSpells(true);
                 me->CastSpell((Unit*)nullptr, SPELL_FURY_OF_FROSTMOURNE, false);
                 me->SetWalk(true);
                 if (Creature* tirion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_HIGHLORD_TIRION_FORDRING)))
                     tirion->AI()->DoAction(ACTION_OUTRO);
                 return;
             }
             if (_phase == PHASE_OUTRO)
             {
                 if (!me->IsLevitating())
                     damage = me->GetHealth() > 1 ? 1 : 0;
                 else if (damage >= me->GetHealth()) // dying...
                 {
                     damage = me->GetHealth() - 1;
                     me->SetDisableGravity(false);
                     me->SendMonsterMove(me->GetPositionX() + 0.25f, me->GetPositionY(), 840.86f, 300, SPLINEFLAG_FALLING);
                     me->m_positionZ = 840.86f;
                     me->SetOrientation(0.0f);
                     if (Creature* frostmourne = me->FindNearestCreature(NPC_FROSTMOURNE_TRIGGER, 50.0f))
                         frostmourne->DespawnOrUnsummon(1);
                     if (Creature* terenas = me->FindNearestCreature(NPC_TERENAS_MENETHIL_OUTRO, 50.0f))
                         terenas->DespawnOrUnsummon(1);
                     me->m_Events.AddEvent(new LichKingDeathEvent(*me), me->m_Events.CalculateTime(2500)); // die after spinning anim is over, so death anim is visible
                     me->m_Events.AddEvent(new LichKingMovieEvent(*me), me->m_Events.CalculateTime(11500));
                 }
                 if (!_bFordringMustFallYell && me->GetHealth() < 500000)
                 {
                     _bFordringMustFallYell = true;
                     if (Creature* tirion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_HIGHLORD_TIRION_FORDRING)))
                     {
                         tirion->Yell("The Lich King must fall!", LANG_UNIVERSAL);
                         tirion->PlayDirectSound(17389);
                     }
                 }
             }
             else if (damage >= me->GetHealth())
                 damage = me->GetHealth() - 1;
         }
References _bFordringMustFallYell, _bFrostmournePhase, _phase, ACTION_OUTRO, ACTION_TELEPORT_BACK, EventProcessor::AddEvent(), AREA_THE_FROZEN_THRONE, Unit::AttackStop(), EventProcessor::CalculateTime(), Unit::CastSpell(), CenterPosition, DATA_HIGHLORD_TIRION_FORDRING, SummonList::DespawnAll(), SummonList::DoAction(), EVENT_GROUP_ABILITIES, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Position::GetExactDistSq(), InstanceScript::GetGuidData(), Unit::GetHealth(), WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), ScriptedAI::HealthBelowPct(), BossAI::instance, Unit::InterruptNonMeleeSpells(), Unit::IsLevitating(), LANG_UNIVERSAL, Unit::m_Events, Position::m_positionZ, ScriptedAI::me, MotionMaster::MovePoint(), MUSIC_FURY_OF_FROSTMOURNE, NPC_FROSTMOURNE_TRIGGER, NPC_STRANGULATE_VEHICLE, NPC_TERENAS_MENETHIL_OUTRO, PHASE_ONE, PHASE_OUTRO, PHASE_THREE, PHASE_TRANSITION, PHASE_TWO, POINT_CENTER_1, POINT_CENTER_2, REACT_PASSIVE, Unit::SendMonsterMove(), Creature::SetDisableGravity(), Position::SetOrientation(), Creature::SetReactState(), Creature::SetWalk(), Map::SetZoneMusic(), SPELL_FURY_OF_FROSTMOURNE, SPLINEFLAG_FALLING, BossAI::summons, and UNIT_STATE_CASTING.
DoAction()
void boss_the_lich_king::boss_the_lich_kingAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 730 of file boss_the_lich_king.cpp.
         {
             switch (action)
             {
                 case ACTION_RESTORE_LIGHT:
                     me->GetMap()->SetZoneOverrideLight(AREA_THE_FROZEN_THRONE, 0, 5s);
                     me->GetMap()->SetZoneWeather(AREA_THE_FROZEN_THRONE, WEATHER_STATE_FINE, 0.5f);
                     break;
                 case ACTION_START_ATTACK:
                     events.ScheduleEvent(EVENT_START_ATTACK, 5250);
                     break;
                 case ACTION_BREAK_FROSTMOURNE:
                     me->CastSpell((Unit*)nullptr, SPELL_SUMMON_BROKEN_FROSTMOURNE, true);
                     me->CastSpell((Unit*)nullptr, SPELL_SUMMON_BROKEN_FROSTMOURNE_2, false);
                     SetEquipmentSlots(false, EQUIP_BROKEN_FROSTMOURNE);
                     if (Creature* tirion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_HIGHLORD_TIRION_FORDRING)))
                         tirion->AI()->DoAction(ACTION_BREAK_FROSTMOURNE);
                     break;
                 case ACTION_TELEPORT_BACK:
                     {
                         if (_phase == PHASE_FROSTMOURNE)
                             events.RescheduleEvent(EVENT_START_ATTACK, 1000);
                         EntryCheckPredicate pred(NPC_STRANGULATE_VEHICLE);
                         summons.DoAction(ACTION_TELEPORT_BACK, pred);
                         if (!IsHeroic() && _phase != PHASE_OUTRO && me->IsInCombat() && _lastTalkTimeBuff + 5 <= time(nullptr))
                             Talk(SAY_LK_FROSTMOURNE_ESCAPE);
                     }
                     break;
                 default:
                     break;
             }
         }
References _lastTalkTimeBuff, _phase, ACTION_BREAK_FROSTMOURNE, ACTION_RESTORE_LIGHT, ACTION_START_ATTACK, ACTION_TELEPORT_BACK, AREA_THE_FROZEN_THRONE, Unit::CastSpell(), DATA_HIGHLORD_TIRION_FORDRING, SummonList::DoAction(), EQUIP_BROKEN_FROSTMOURNE, EVENT_START_ATTACK, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), BossAI::instance, ScriptedAI::IsHeroic(), Unit::IsInCombat(), ScriptedAI::me, NPC_STRANGULATE_VEHICLE, PHASE_FROSTMOURNE, PHASE_OUTRO, SAY_LK_FROSTMOURNE_ESCAPE, ScriptedAI::SetEquipmentSlots(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), SPELL_SUMMON_BROKEN_FROSTMOURNE, SPELL_SUMMON_BROKEN_FROSTMOURNE_2, BossAI::summons, CreatureAI::Talk(), and WEATHER_STATE_FINE.
Referenced by JustDied(), JustReachedHome(), and Reset().
EnterCombat()
void boss_the_lich_king::boss_the_lich_kingAI::EnterCombat (Unit * target) inline override virtual
Reimplemented from BossAI.
Definition at line 671 of file boss_the_lich_king.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_THE_LICH_KING, target->ToPlayer()) || !me->IsVisible())
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             _phase = PHASE_ONE;
             instance->SetBossState(DATA_THE_LICH_KING, IN_PROGRESS);
             me->setActive(true);
             me->SetInCombatWithZone();
             me->RemoveAurasDueToSpell(SPELL_EMOTE_SIT_NO_SHEATH); // just to be sure
             events.ScheduleEvent(EVENT_BERSERK, 900000, EVENT_GROUP_BERSERK);
             events.ScheduleEvent(EVENT_SUMMON_SHAMBLING_HORROR, 15000, EVENT_GROUP_ABILITIES);
             events.ScheduleEvent(EVENT_SUMMON_DRUDGE_GHOUL, 10000, EVENT_GROUP_ABILITIES);
             events.ScheduleEvent(EVENT_INFEST, 5000, EVENT_GROUP_ABILITIES);
             events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(30000, 31000), EVENT_GROUP_ABILITIES);
             if (IsHeroic())
                 events.ScheduleEvent(EVENT_SHADOW_TRAP, 15500, EVENT_GROUP_ABILITIES);
         }
References _phase, InstanceScript::CheckRequiredBosses(), DATA_THE_LICH_KING, InstanceScript::DoCastSpellOnPlayers(), EnterEvadeMode(), EVENT_BERSERK, EVENT_GROUP_ABILITIES, EVENT_GROUP_BERSERK, EVENT_INFEST, EVENT_NECROTIC_PLAGUE, EVENT_SHADOW_TRAP, EVENT_SUMMON_DRUDGE_GHOUL, EVENT_SUMMON_SHAMBLING_HORROR, IN_PROGRESS, BossAI::instance, ScriptedAI::IsHeroic(), Unit::IsVisible(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, PHASE_ONE, Unit::RemoveAurasDueToSpell(), WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetInCombatWithZone(), SPELL_EMOTE_SIT_NO_SHEATH, Object::ToPlayer(), and urand().
EnterEvadeMode()
void boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1256 of file boss_the_lich_king.cpp.
         {
             EntryCheckPredicate pred(NPC_STRANGULATE_VEHICLE);
             summons.DoAction(ACTION_TELEPORT_BACK, pred);
             instance->SetBossState(DATA_THE_LICH_KING, FAIL);
             me->CastSpell((Unit*)nullptr, SPELL_KILL_FROSTMOURNE_PLAYERS, true);
             BossAI::EnterEvadeMode();
             me->SetReactState(REACT_AGGRESSIVE);
             if (Creature* tirion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_HIGHLORD_TIRION_FORDRING)))
                 tirion->AI()->EnterEvadeMode();
         }
References ACTION_TELEPORT_BACK, Unit::CastSpell(), DATA_HIGHLORD_TIRION_FORDRING, DATA_THE_LICH_KING, SummonList::DoAction(), CreatureAI::EnterEvadeMode(), FAIL, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, NPC_STRANGULATE_VEHICLE, REACT_AGGRESSIVE, InstanceScript::SetBossState(), Creature::SetReactState(), SPELL_KILL_FROSTMOURNE_PLAYERS, and BossAI::summons.
Referenced by EnterCombat().
GetData()
uint32 boss_the_lich_king::boss_the_lich_kingAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1226 of file boss_the_lich_king.cpp.
         {
             switch (type)
             {
                 case DATA_PLAGUE_STACK:
                     return _necroticPlagueStack;
                 case DATA_VILE:
                     return _vileSpiritExplosions;
                 default:
                     break;
             }
             return 0;
         }
References _necroticPlagueStack, _vileSpiritExplosions, DATA_PLAGUE_STACK, and DATA_VILE.
JustDied()
void boss_the_lich_king::boss_the_lich_kingAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 664 of file boss_the_lich_king.cpp.
         {
             _JustDied();
             DoAction(ACTION_RESTORE_LIGHT);
             me->PlayDirectSound(17374);
         }
References BossAI::_JustDied(), ACTION_RESTORE_LIGHT, DoAction(), ScriptedAI::me, and WorldObject::PlayDirectSound().
JustReachedHome()
void boss_the_lich_king::boss_the_lich_kingAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 695 of file boss_the_lich_king.cpp.
         {
             _JustReachedHome();
             DoAction(ACTION_RESTORE_LIGHT);
             // Reset The Frozen Throne gameobjects
             FrozenThroneResetWorker reset;
             Acore::GameObjectWorker<FrozenThroneResetWorker> worker(me, reset);
             Cell::VisitGridObjects(me, worker, 333.0f);
             me->AddAura(SPELL_EMOTE_SIT_NO_SHEATH, me);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             me->SetReactState(REACT_PASSIVE);
             me->SetStandState(UNIT_STAND_STATE_SIT);
         }
References BossAI::_JustReachedHome(), ACTION_RESTORE_LIGHT, Unit::AddAura(), DoAction(), ScriptedAI::me, REACT_PASSIVE, Object::SetFlag(), Creature::SetReactState(), Unit::SetStandState(), SPELL_EMOTE_SIT_NO_SHEATH, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STAND_STATE_SIT, and Cell::VisitGridObjects().
JustSummoned()
void boss_the_lich_king::boss_the_lich_kingAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 846 of file boss_the_lich_king.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_SHAMBLING_HORROR:
                 case NPC_DRUDGE_GHOUL:
                     summon->SetHomePosition(CenterPosition);
                     summon->CastSpell(summon, SPELL_RISEN_WITCH_DOCTOR_SPAWN, true);
                     summon->SetReactState(REACT_PASSIVE);
                     summon->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
                     summon->m_Events.AddEvent(new StartMovementEvent(me, summon), summon->m_Events.CalculateTime(5000));
                     break;
                 case NPC_RAGING_SPIRIT:
                     summon->SetHomePosition(CenterPosition);
                     break;
                 case NPC_VILE_SPIRIT:
                     {
                         summon->SetReactState(REACT_PASSIVE);
                         summon->GetMotionMaster()->MoveRandom(10.0f);
                         if (_phase == PHASE_THREE)
                             summon->m_Events.AddEvent(new VileSpiritActivateEvent(summon), summon->m_Events.CalculateTime(15000));
                         break;
                     }
                 case NPC_STRANGULATE_VEHICLE:
                     summons.Summon(summon);
                     return;
                 case NPC_DEFILE:
                 case NPC_SHADOW_TRAP_TRIGGER:
                     summon->m_positionZ = 840.86f;
                     summon->UpdatePosition(summon->GetPositionX(), summon->GetPositionY(), summon->GetPositionZ(), summon->GetOrientation(), true);
                     summon->StopMovingOnCurrentPos();
                     break;
                 case NPC_VALKYR_SHADOWGUARD:
                     if (_phase == PHASE_THREE || events.GetNextEventTime(EVENT_QUAKE_2))
                         summon->DespawnOrUnsummon(1);
                     break;
                 default:
                     break;
             }
             BossAI::JustSummoned(summon);
         }
References _phase, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), CenterPosition, Creature::DespawnOrUnsummon(), EMOTE_ONESHOT_EMERGE, EVENT_QUAKE_2, Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HandleEmoteCommand(), BossAI::JustSummoned(), Unit::m_Events, Position::m_positionZ, ScriptedAI::me, MotionMaster::MoveRandom(), NPC_DEFILE, NPC_DRUDGE_GHOUL, NPC_RAGING_SPIRIT, NPC_SHADOW_TRAP_TRIGGER, NPC_SHAMBLING_HORROR, NPC_STRANGULATE_VEHICLE, NPC_VALKYR_SHADOWGUARD, NPC_VILE_SPIRIT, PHASE_THREE, REACT_PASSIVE, Creature::SetHomePosition(), Creature::SetReactState(), SPELL_RISEN_WITCH_DOCTOR_SPAWN, Unit::StopMovingOnCurrentPos(), SummonList::Summon(), BossAI::summons, and Unit::UpdatePosition().
KilledUnit()
void boss_the_lich_king::boss_the_lich_kingAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 721 of file boss_the_lich_king.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER && !me->IsInEvadeMode() && _phase != PHASE_OUTRO && _lastTalkTimeKill + 5 < time(nullptr))
             {
                 _lastTalkTimeKill = time(nullptr);
                 Talk(SAY_LK_KILL);
             }
         }
References _lastTalkTimeKill, _phase, Object::GetTypeId(), Creature::IsInEvadeMode(), ScriptedAI::me, PHASE_OUTRO, SAY_LK_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_the_lich_king::boss_the_lich_kingAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 926 of file boss_the_lich_king.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch (pointId)
             {
                 case POINT_CENTER_1:
                     me->SetFacingTo(0.0f);
                     Talk(SAY_LK_REMORSELESS_WINTER);
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     me->CastSpell(me, SPELL_REMORSELESS_WINTER_1, false);
                     //events.DelayEvents(62500, EVENT_GROUP_BERSERK); // delay berserk timer, its not ticking during phase transitions, bullshit, 15mins on movies
                     events.ScheduleEvent(EVENT_QUAKE, 62500);
                     events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, 3500, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SUMMON_ICE_SPHERE, 8000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, 4000, EVENT_GROUP_ABILITIES);
                     break;
                 case POINT_CENTER_2:
                     me->SetFacingTo(0.0f);
                     Talk(SAY_LK_REMORSELESS_WINTER);
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     me->CastSpell(me, SPELL_REMORSELESS_WINTER_2, false);
                     summons.DespawnEntry(NPC_VALKYR_SHADOWGUARD);
                     //events.DelayEvents(62500, EVENT_GROUP_BERSERK); // delay berserk timer, its not ticking during phase transitions, bullshit, 15 mins on movies
                     events.ScheduleEvent(EVENT_QUAKE_2, 62500);
                     events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, 3500, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SUMMON_ICE_SPHERE, 8000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, 4000, EVENT_GROUP_ABILITIES);
                     break;
                 default:
                     break;
             }
         }
References AREA_THE_FROZEN_THRONE, Unit::CastSpell(), SummonList::DespawnEntry(), EVENT_GROUP_ABILITIES, EVENT_PAIN_AND_SUFFERING, EVENT_QUAKE, EVENT_QUAKE_2, EVENT_SUMMON_ICE_SPHERE, EVENT_SUMMON_RAGING_SPIRIT, WorldObject::GetMap(), ScriptedAI::me, MUSIC_SPECIAL, NPC_VALKYR_SHADOWGUARD, POINT_CENTER_1, POINT_CENTER_2, POINT_MOTION_TYPE, SAY_LK_REMORSELESS_WINTER, Unit::SetFacingTo(), Map::SetZoneMusic(), SPELL_REMORSELESS_WINTER_1, SPELL_REMORSELESS_WINTER_2, BossAI::summons, and CreatureAI::Talk().
Reset()
void boss_the_lich_king::boss_the_lich_kingAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 646 of file boss_the_lich_king.cpp.
         {
             _phase = PHASE_NONE;
             _necroticPlagueStack = 0;
             _vileSpiritExplosions = 0;
             _positionCheckTimer = 5000;
             _lastTalkTimeKill = 0;
             _lastTalkTimeBuff = 0;
             _bFrostmournePhase = false;
             _bFordringMustFallYell = false;
             _Reset();
             DoAction(ACTION_RESTORE_LIGHT);
             SetEquipmentSlots(true);
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC))
                 me->SetStandState(UNIT_STAND_STATE_SIT);
         }
References _bFordringMustFallYell, _bFrostmournePhase, _lastTalkTimeBuff, _lastTalkTimeKill, _necroticPlagueStack, _phase, _positionCheckTimer, BossAI::_Reset(), _vileSpiritExplosions, ACTION_RESTORE_LIGHT, DoAction(), Object::HasFlag(), ScriptedAI::me, PHASE_NONE, ScriptedAI::SetEquipmentSlots(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_STAND_STATE_SIT.
SetData()
void boss_the_lich_king::boss_the_lich_kingAI::SetData (uint32 type, uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 1241 of file boss_the_lich_king.cpp.
         {
             switch (type)
             {
                 case DATA_PLAGUE_STACK:
                     _necroticPlagueStack = std::max(value, _necroticPlagueStack);
                     break;
                 case DATA_VILE:
                     _vileSpiritExplosions += value;
                     break;
                 default:
                     break;
             }
         }
References _necroticPlagueStack, _vileSpiritExplosions, DATA_PLAGUE_STACK, and DATA_VILE.
SpellHit()
void boss_the_lich_king::boss_the_lich_kingAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 907 of file boss_the_lich_king.cpp.
         {
             if (spell->Id == HARVESTED_SOUL_BUFF && me->IsInCombat() && !IsHeroic() && _phase != PHASE_OUTRO && _lastTalkTimeBuff + 5 <= time(nullptr))
             {
                 _lastTalkTimeBuff = time(nullptr);
                 Talk(SAY_LK_FROSTMOURNE_KILL);
             }
         }
References _lastTalkTimeBuff, _phase, HARVESTED_SOUL_BUFF, SpellInfo::Id, ScriptedAI::IsHeroic(), Unit::IsInCombat(), ScriptedAI::me, PHASE_OUTRO, SAY_LK_FROSTMOURNE_KILL, and CreatureAI::Talk().
SpellHitTarget()
void boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 916 of file boss_the_lich_king.cpp.
         {
             if (spell->Id == REMORSELESS_WINTER_1 || spell->Id == REMORSELESS_WINTER_2)
             {
                 me->GetMap()->SetZoneOverrideLight(AREA_THE_FROZEN_THRONE, LIGHT_SNOWSTORM, 5s);
                 me->GetMap()->SetZoneWeather(AREA_THE_FROZEN_THRONE, WEATHER_STATE_LIGHT_SNOW, 0.5f);
                 summons.DespawnEntry(NPC_SHADOW_TRAP_TRIGGER);
             }
         }
References AREA_THE_FROZEN_THRONE, SummonList::DespawnEntry(), WorldObject::GetMap(), SpellInfo::Id, LIGHT_SNOWSTORM, ScriptedAI::me, NPC_SHADOW_TRAP_TRIGGER, REMORSELESS_WINTER_1, REMORSELESS_WINTER_2, Map::SetZoneOverrideLight(), Map::SetZoneWeather(), BossAI::summons, and WEATHER_STATE_LIGHT_SNOW.
SummonedCreatureDies()
void boss_the_lich_king::boss_the_lich_kingAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 889 of file boss_the_lich_king.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_SHAMBLING_HORROR:
                 case NPC_DRUDGE_GHOUL:
                 case NPC_ICE_SPHERE:
                 case NPC_VALKYR_SHADOWGUARD:
                 case NPC_RAGING_SPIRIT:
                 case NPC_VILE_SPIRIT:
                     summon->ToTempSummon()->SetTimer(5000);
                     summon->ToTempSummon()->SetTempSummonType(TEMPSUMMON_TIMED_DESPAWN);
                     break;
                 default:
                     break;
             }
         }
References Object::GetEntry(), NPC_DRUDGE_GHOUL, NPC_ICE_SPHERE, NPC_RAGING_SPIRIT, NPC_SHAMBLING_HORROR, NPC_VALKYR_SHADOWGUARD, NPC_VILE_SPIRIT, TempSummon::SetTempSummonType(), TempSummon::SetTimer(), TEMPSUMMON_TIMED_DESPAWN, and Unit::ToTempSummon().
UpdateAI()
void boss_the_lich_king::boss_the_lich_kingAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 961 of file boss_the_lich_king.cpp.
         {
             if (_phase == PHASE_NONE)
                 return;
             // check phase first to prevent updating victim and entering evade mode when not wanted
             if (!((1 << _phase) & PHASE_MASK_NO_VICTIM))
                 if (!UpdateVictim())
                     return;
             // handle falling players so they don't fall infinitely
             if (_positionCheckTimer <= diff)
             {
                 _positionCheckTimer = 5000;
                 Map::PlayerList const& players = me->GetMap()->GetPlayers();
                 if (!players.isEmpty())
                     for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                         if (Player* player = itr->GetSource())
                             if (player->GetPositionZ() < 700.0f)
                                 Unit::Kill(me, player);
             }
             else
                 _positionCheckTimer -= diff;
             events.Update(diff);
             // during Remorseless Winter phases The Lich King is channeling a spell, but we must continue casting other spells
             if (me->HasUnitState(UNIT_STATE_CASTING) && !((1 << _phase) & PHASE_MASK_NO_CAST_CHECK))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     Talk(SAY_LK_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK2, true);
                     break;
                 case EVENT_START_ATTACK:
                     me->SetReactState(REACT_AGGRESSIVE);
                     if (_phase == PHASE_FROSTMOURNE)
                     {
                         _bFrostmournePhase = false;
                         _phase = PHASE_THREE;
                         events.RescheduleEvent(EVENT_DEFILE, 0, EVENT_GROUP_ABILITIES);
                         events.RescheduleEvent(EVENT_SOUL_REAPER, urand(7000, 12000), EVENT_GROUP_ABILITIES);
                         for (SummonList::iterator i = summons.begin(); i != summons.end(); ++i)
                             if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                                 if (summon->GetEntry() == NPC_RAGING_SPIRIT)
                                     summon->SetReactState(REACT_AGGRESSIVE);
                     }
                     break;
                 case EVENT_QUAKE:
                     _phase = PHASE_TWO;
                     events.CancelEventGroup(EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_INFEST, 14000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SUMMON_VALKYR, 20000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SOUL_REAPER, 40000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_DEFILE, 38000, EVENT_GROUP_ABILITIES);
                     me->InterruptNonMeleeSpells(false);
                     me->ClearUnitState(UNIT_STATE_CASTING);
                     me->SetFacingTo(0.0f);
                     me->CastSpell((Unit*)nullptr, SPELL_QUAKE, false);
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     Talk(SAY_LK_QUAKE);
                     break;
                 case EVENT_QUAKE_2:
                     _phase = PHASE_THREE;
                     events.CancelEventGroup(EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_SOUL_REAPER, 40000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_DEFILE, 38000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_VILE_SPIRITS, 20000, EVENT_GROUP_VILE_SPIRITS);
                     events.ScheduleEvent(IsHeroic() ? EVENT_HARVEST_SOULS : EVENT_HARVEST_SOUL, 14000, EVENT_GROUP_ABILITIES);
                     me->InterruptNonMeleeSpells(false);
                     me->ClearUnitState(UNIT_STATE_CASTING);
                     me->SetFacingTo(0.0f);
                     me->CastSpell((Unit*)nullptr, SPELL_QUAKE, false);
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     Talk(SAY_LK_QUAKE);
                     break;
                 // ABILITIES:
                 case EVENT_SUMMON_SHAMBLING_HORROR:
                     me->CastSpell(me, SPELL_SUMMON_SHAMBLING_HORROR, false);
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     events.ScheduleEvent(EVENT_SUMMON_SHAMBLING_HORROR, 60000, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_SUMMON_DRUDGE_GHOUL:
                     me->CastSpell(me, SPELL_SUMMON_DRUDGE_GHOULS, false);
                     events.ScheduleEvent(EVENT_SUMMON_DRUDGE_GHOUL, 30000, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_INFEST:
                     me->CastSpell(me, SPELL_INFEST, false);
                     events.ScheduleEvent(EVENT_INFEST, 22500, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_NECROTIC_PLAGUE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, NecroticPlagueTargetCheck(me, NECROTIC_PLAGUE_LK, NECROTIC_PLAGUE_PLR)))
                     {
                         Talk(EMOTE_NECROTIC_PLAGUE_WARNING, target);
                         me->CastSpell(target, SPELL_NECROTIC_PLAGUE, false);
                         events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(30000, 31000), EVENT_GROUP_ABILITIES);
                     }
                     else
                         events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, 5000, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_SHADOW_TRAP:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, ShadowTrapLKTargetSelector(me, true, true, 100.0f)))
                         me->CastSpell(target, SPELL_SHADOW_TRAP, false);
                     events.ScheduleEvent(EVENT_SHADOW_TRAP, 15500, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_PAIN_AND_SUFFERING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
                     {
                         //events.DelayEventsToMax(500, EVENT_GROUP_ABILITIES);
                         me->SetFacingTo(me->GetAngle(target));
                         me->CastSpell(target, SPELL_PAIN_AND_SUFFERING, false);
                     }
                     events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, (IsHeroic() ? urand(1250, 1750) : urand(1750, 2250)), EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_SUMMON_ICE_SPHERE:
                     me->CastSpell((Unit*)nullptr, SPELL_SUMMON_ICE_SPHERE, false);
                     events.ScheduleEvent(EVENT_SUMMON_ICE_SPHERE, 7500, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_SUMMON_RAGING_SPIRIT:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                         me->CastSpell(target, SPELL_RAGING_SPIRIT, false);
                     events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, (!HealthAbovePct(40) ? 15000 : 20000), EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_DEFILE:
                     {
                         uint32 evTime = events.GetNextEventTime(EVENT_SUMMON_VALKYR);
                         // if defile (cast time 2sec) is less than 3 before valkyr appears
                         // we've to decide
                         if (evTime && (events.GetTimer() > evTime || evTime - events.GetTimer() < 5000))
{
                             // if valkyr is less than 1.5 secs after defile (cast time 2 sec) then we've a sync issue, so
                             // we need to cancel it (break) and schedule a defile to be casted 5 or 4 seconds after valkyr
                             if (events.GetTimer() > evTime || evTime - events.GetTimer() < 3500)
{
                                 uint32 t = events.GetTimer() > evTime ? 0 : evTime - events.GetTimer();
                                 events.ScheduleEvent(EVENT_DEFILE, t + (Is25ManRaid() ? 5000 : 4000), EVENT_GROUP_ABILITIES);
                                 break;
                             }
                             // if valkyr is coming between 1.5 and 3 seconds after defile then we've to
                             // delay valkyr just a bit
                             events.RescheduleEvent(EVENT_SUMMON_VALKYR, 5000, EVENT_GROUP_ABILITIES);
                         }
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, DefileTargetSelector(me)))
{
                             Talk(EMOTE_DEFILE_WARNING);
                             me->CastSpell(target, SPELL_DEFILE, false);
                             // defile has a fixed CD (from dbm) that can be variable only
                             // if no target has been found at the moment (schedule after 1 second)
                             events.ScheduleEvent(EVENT_DEFILE, 32500, EVENT_GROUP_ABILITIES);
                         }
                         else
{
                             // be sure it happen trying each seconds if no target
                             events.ScheduleEvent(EVENT_DEFILE, 1000, EVENT_GROUP_ABILITIES);
                         }
                     }
                     break;
                 case EVENT_SOUL_REAPER:
                     if (me->IsWithinMeleeRange(me->GetVictim()))
                     {
                         me->CastSpell(me->GetVictim(), SPELL_SOUL_REAPER, false);
                         events.ScheduleEvent(EVENT_SOUL_REAPER, 30500, EVENT_GROUP_ABILITIES);
                     }
                     else
                         events.ScheduleEvent(EVENT_SOUL_REAPER, 1000, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_SUMMON_VALKYR:
                     {
                         me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                         Talk(SAY_LK_SUMMON_VALKYR);
                         me->CastSpell((Unit*)nullptr, SUMMON_VALKYR, false);
                         events.ScheduleEvent(EVENT_SUMMON_VALKYR, 45000, EVENT_GROUP_ABILITIES);
                         // schedule a defile (or reschedule it) if next defile event
                         // doesn't exist ( now > next defile ) or defile is coming too soon
                         uint32 minTime = (Is25ManRaid() ? 5000 : 4000);
                         if (uint32 evTime = events.GetNextEventTime(EVENT_DEFILE))
                             if (events.GetTimer() > evTime || evTime - events.GetTimer() < minTime)
{
                                 events.RescheduleEvent(EVENT_DEFILE, minTime, EVENT_GROUP_ABILITIES);
                             }
                     }
                     break;
                 case EVENT_VILE_SPIRITS:
                     me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                     me->CastSpell((Unit*)nullptr, SPELL_VILE_SPIRITS, false);
                     events.ScheduleEvent(EVENT_VILE_SPIRITS, 30000, EVENT_GROUP_VILE_SPIRITS);
                     break;
                 case EVENT_HARVEST_SOUL:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, NonTankLKTargetSelector(me, true, true, 55.0f)))
                     {
                         Talk(SAY_LK_HARVEST_SOUL);
                         me->CastSpell(target, SPELL_HARVEST_SOUL, false);
                         events.ScheduleEvent(EVENT_HARVEST_SOUL, 75000, EVENT_GROUP_ABILITIES);
                     }
                     else
                         events.ScheduleEvent(EVENT_HARVEST_SOUL, 10000, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_HARVEST_SOULS:
                     Talk(SAY_LK_HARVEST_SOUL);
                     me->CastSpell((Unit*)nullptr, SPELL_HARVEST_SOULS, false);
                     _phase = PHASE_FROSTMOURNE;
                     me->SetReactState(REACT_PASSIVE);
                     me->AttackStop();
                     events.ScheduleEvent(EVENT_START_ATTACK, 55000);
                     events.DelayEvents(52500, EVENT_GROUP_VILE_SPIRITS);
                     events.CancelEvent(EVENT_DEFILE);
                     events.CancelEvent(EVENT_SOUL_REAPER);
                     events.ScheduleEvent(EVENT_FROSTMOURNE_HEROIC, 6000, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_HARVEST_SOULS, urand(100000, 110000), EVENT_GROUP_ABILITIES);
                     for (SummonList::iterator i = summons.begin(); i != summons.end(); ++i)
                         if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
{
                             if (summon->GetEntry() == NPC_VILE_SPIRIT)
{
                                 summon->m_Events.KillAllEvents(true);
                                 summon->m_Events.AddEvent(new VileSpiritActivateEvent(summon), summon->m_Events.CalculateTime(55000));
                                 summon->GetMotionMaster()->Clear(true);
                                 summon->StopMoving();
                                 summon->SetReactState(REACT_PASSIVE);
                                 summon->AttackStop();
                             }
                             else if (summon->GetEntry() == NPC_RAGING_SPIRIT)
{
                                 summon->GetMotionMaster()->Clear(true);
                                 summon->StopMoving();
                                 summon->SetReactState(REACT_PASSIVE);
                                 summon->AttackStop();
                             }
                         }
                     break;
                 case EVENT_FROSTMOURNE_HEROIC:
                     _bFrostmournePhase = true;
                     if (TempSummon* terenas = me->GetMap()->SummonCreature(NPC_TERENAS_MENETHIL_FROSTMOURNE_H, TerenasSpawnHeroic, nullptr, 55000))
                     {
                         terenas->AI()->DoAction(ACTION_FROSTMOURNE_INTRO);
                         if (Creature* spawner = terenas->FindNearestCreature(NPC_WORLD_TRIGGER_INFINITE_AOI, 100.0f, true))
{
                             spawner->CastSpell(spawner, SPELL_SUMMON_SPIRIT_BOMB_1, true);  // summons bombs randomly
                             spawner->CastSpell(spawner, SPELL_SUMMON_SPIRIT_BOMB_2, true);  // summons bombs on players
                             spawner->m_Events.AddEvent(new TriggerWickedSpirit(spawner), spawner->m_Events.CalculateTime(3000));
                             terenas->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC); // to avoid being healed by player trinket procs. terenas' health doesn't matter on heroic
                         }
                     }
                     break;
                 default:
                     break;
             }
             if (!me->HasReactState(REACT_PASSIVE) && me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim()) && me->GetMotionMaster()->GetCurrentMovementGeneratorType() != POINT_MOTION_TYPE && !me->IsWithinLOSInMap(me->GetVictim()))
                 me->GetMotionMaster()->MoveCharge(me->GetVictim()->GetPositionX(), me->GetVictim()->GetPositionY(), me->GetVictim()->GetPositionZ(), me->GetSpeed(MOVE_RUN), POINT_NONE);
             DoMeleeAttackIfReady();
         }
References _bFrostmournePhase, _phase, _positionCheckTimer, ACTION_FROSTMOURNE_INTRO, AREA_THE_FROZEN_THRONE, Unit::AttackStop(), SummonList::begin(), MapRefMgr::begin(), Unit::CastSpell(), Unit::ClearUnitState(), UnitAI::DoMeleeAttackIfReady(), EMOTE_DEFILE_WARNING, EMOTE_NECROTIC_PLAGUE_WARNING, SummonList::end(), MapRefMgr::end(), EVENT_BERSERK, EVENT_DEFILE, EVENT_FROSTMOURNE_HEROIC, EVENT_GROUP_ABILITIES, EVENT_GROUP_VILE_SPIRITS, EVENT_HARVEST_SOUL, EVENT_HARVEST_SOULS, EVENT_INFEST, EVENT_NECROTIC_PLAGUE, EVENT_PAIN_AND_SUFFERING, EVENT_QUAKE, EVENT_QUAKE_2, EVENT_SHADOW_TRAP, EVENT_SOUL_REAPER, EVENT_START_ATTACK, EVENT_SUMMON_DRUDGE_GHOUL, EVENT_SUMMON_ICE_SPHERE, EVENT_SUMMON_RAGING_SPIRIT, EVENT_SUMMON_SHAMBLING_HORROR, EVENT_SUMMON_VALKYR, EVENT_VILE_SPIRITS, WorldObject::FindNearestCreature(), Position::GetAngle(), ObjectAccessor::GetCreature(), MotionMaster::GetCurrentMovementGeneratorType(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::GetVictim(), Creature::HasReactState(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), Unit::InterruptNonMeleeSpells(), ScriptedAI::Is25ManRaid(), LinkedListHead::isEmpty(), ScriptedAI::IsHeroic(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::Kill(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveCharge(), MUSIC_SPECIAL, NECROTIC_PLAGUE_LK, NECROTIC_PLAGUE_PLR, NPC_RAGING_SPIRIT, NPC_TERENAS_MENETHIL_FROSTMOURNE_H, NPC_VILE_SPIRIT, NPC_WORLD_TRIGGER_INFINITE_AOI, PHASE_FROSTMOURNE, PHASE_MASK_NO_CAST_CHECK, PHASE_MASK_NO_VICTIM, PHASE_NONE, PHASE_THREE, PHASE_TWO, POINT_MOTION_TYPE, POINT_NONE, REACT_AGGRESSIVE, REACT_PASSIVE, SAY_LK_BERSERK, SAY_LK_HARVEST_SOUL, SAY_LK_QUAKE, SAY_LK_SUMMON_VALKYR, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetFacingTo(), Creature::SetReactState(), Map::SetZoneMusic(), SPELL_BERSERK2, SPELL_DEFILE, SPELL_HARVEST_SOUL, SPELL_HARVEST_SOULS, SPELL_INFEST, SPELL_NECROTIC_PLAGUE, SPELL_PAIN_AND_SUFFERING, SPELL_QUAKE, SPELL_RAGING_SPIRIT, SPELL_SHADOW_TRAP, SPELL_SOUL_REAPER, SPELL_SUMMON_DRUDGE_GHOULS, SPELL_SUMMON_ICE_SPHERE, SPELL_SUMMON_SHAMBLING_HORROR, SPELL_SUMMON_SPIRIT_BOMB_1, SPELL_SUMMON_SPIRIT_BOMB_2, SPELL_VILE_SPIRITS, SUMMON_VALKYR, Map::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TerenasSpawnHeroic, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_bFordringMustFallYell
bool boss_the_lich_king::boss_the_lich_kingAI::_bFordringMustFallYell
Definition at line 644 of file boss_the_lich_king.cpp.
Referenced by DamageTaken(), and Reset().
_bFrostmournePhase
bool boss_the_lich_king::boss_the_lich_kingAI::_bFrostmournePhase
Definition at line 643 of file boss_the_lich_king.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
_lastTalkTimeBuff
uint32 boss_the_lich_king::boss_the_lich_kingAI::_lastTalkTimeBuff
Definition at line 642 of file boss_the_lich_king.cpp.
Referenced by DoAction(), Reset(), and SpellHit().
_lastTalkTimeKill
uint32 boss_the_lich_king::boss_the_lich_kingAI::_lastTalkTimeKill
Definition at line 641 of file boss_the_lich_king.cpp.
Referenced by KilledUnit(), and Reset().
_necroticPlagueStack
uint32 boss_the_lich_king::boss_the_lich_kingAI::_necroticPlagueStack
Definition at line 638 of file boss_the_lich_king.cpp.
Referenced by GetData(), Reset(), and SetData().
_phase
uint8 boss_the_lich_king::boss_the_lich_kingAI::_phase
Definition at line 637 of file boss_the_lich_king.cpp.
Referenced by DamageTaken(), DoAction(), EnterCombat(), JustSummoned(), KilledUnit(), Reset(), SpellHit(), and UpdateAI().
_positionCheckTimer
uint16 boss_the_lich_king::boss_the_lich_kingAI::_positionCheckTimer
Definition at line 640 of file boss_the_lich_king.cpp.
Referenced by Reset(), and UpdateAI().
_vileSpiritExplosions
uint32 boss_the_lich_king::boss_the_lich_kingAI::_vileSpiritExplosions
Definition at line 639 of file boss_the_lich_king.cpp.
Referenced by GetData(), Reset(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp