Azerotcore-wotlk: instance_ulduar::instance_ulduar_InstanceMapScript Struct Reference
instance_ulduar::instance_ulduar_InstanceMapScript Struct Reference
Public Member Functions
instance_ulduar_InstanceMapScript (Map *pMap)
void Initialize () override
void FillInitialWorldStates (WorldPacket &packet) override
void OnPlayerEnter (Player *player) override
bool IsEncounterInProgress () const override
void ProcessEvent (WorldObject *, uint32 eventId) override
void SpawnHodirChests (int rd)
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OpenIfDone (uint32 encounter, GameObject *go, GOState state)
void ShowKeeperGossip (uint8 type, Creature *cr, ObjectGuid guid=ObjectGuid::Empty)
void OnGameObjectCreate (GameObject *gameObject) override
void setChestsLootable (uint32 boss)
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 data) const override
uint32 GetData (uint32 type) const override
void OnUnitDeath (Unit *unit) override
std::string GetSaveData () override
void Load (const char *strIn) override
void Update (uint32 diff) override
void SpawnLeviathanEncounterVehicles (uint8 mode)
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 C_of_Ulduar_MASK
int m_difficulty
ObjectGuid m_uiLeviathanGUID
ObjectGuid m_uiIgnisGUID
ObjectGuid m_uiRazorscaleGUID
ObjectGuid m_uiXT002GUID
ObjectGuid m_auiAssemblyGUIDs [3]
ObjectGuid m_uiKologarnGUID
ObjectGuid m_uiAuriayaGUID
ObjectGuid m_uiMimironGUID
ObjectGuid m_uiHodirGUID
ObjectGuid m_uiThorimGUID
ObjectGuid m_uiFreyaGUID
ObjectGuid m_uiVezaxGUID
ObjectGuid m_uiYoggSaronGUID
ObjectGuid m_uiAlgalonGUID
ObjectGuid m_leviathanDoorsGUID
ObjectGuid m_leviathanVisualTowers [4][2]
ObjectGuid m_RepairSGUID [2]
ObjectGuid m_lightningWalls [2]
bool m_leviathanTowers [4]
GuidList _leviathanVehicles
uint32 m_unbrokenAchievement
uint32 m_mageBarrier
ObjectGuid m_RazorscaleHarpoonFireStateGUID [4]
ObjectGuid m_xt002DoorsGUID
ObjectGuid KologarnDoorGUID
ObjectGuid m_assemblyDoorsGUID
ObjectGuid m_archivumDoorsGUID
ObjectGuid m_thorimGameobjectsGUID [5]
bool hmHodir
ObjectGuid m_hodirNormalChest
ObjectGuid m_hodirHardmodeChest
Position normalChestPosition = { 1967.152588f, -204.188461f, 432.686951f, 5.50957f }
Position hardChestPosition = { 2035.94600f, -202.084885f, 432.686859f, 3.164077f }
ObjectGuid m_MimironDoor [3]
ObjectGuid m_MimironLeviathanMKIIguid
ObjectGuid m_MimironVX001guid
ObjectGuid m_MimironACUguid
ObjectGuid m_FreyaElder [3]
uint32 m_conspeedatoryAttempt
ObjectGuid m_saraGUID
ObjectGuid m_yoggsaronBrainGUID
ObjectGuid m_yoggsaronDoorsGUID
ObjectGuid m_algalonSigilDoorGUID [3]
ObjectGuid m_algalonFloorGUID [2]
ObjectGuid m_algalonUniverseGUID
ObjectGuid m_algalonTrapdoorGUID
ObjectGuid m_brannBronzebeardAlgGUID
ObjectGuid m_brannBronzebeardBaseCamp
uint32 m_algalonTimer
EventMap _events
bool m_mimironTramUsed
ObjectGuid m_mimironTramGUID
ObjectGuid m_keepersgateGUID
ObjectGuid m_keepersGossipGUID [4]
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 37 of file instance_ulduar.cpp.
Constructor & Destructor Documentation
instance_ulduar_InstanceMapScript()
instance_ulduar::instance_ulduar_InstanceMapScript::instance_ulduar_InstanceMapScript (Map * pMap) inline
Definition at line 39 of file instance_ulduar.cpp.
                                                      : InstanceScript(pMap)
         {
             Initialize();
             // 0: 10 man difficulty
             // 1: 25 man difficulty
             m_difficulty = (pMap->Is25ManRaid() ? 0 : 1);
         };
References Initialize(), Map::Is25ManRaid(), and m_difficulty.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_ulduar::instance_ulduar_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
Definition at line 1141 of file instance_ulduar.cpp.
         {
             switch (criteria_id)
             {
                 case 10042:
                 case 10352:
                     return (C_of_Ulduar_MASK & (1 << TYPE_LEVIATHAN)) == 0;
                 case 10342:
                 case 10355:
                     return (C_of_Ulduar_MASK & (1 << TYPE_IGNIS)) == 0;
                 case 10340:
                 case 10353:
                     return (C_of_Ulduar_MASK & (1 << TYPE_RAZORSCALE)) == 0;
                 case 10341:
                 case 10354:
                     return (C_of_Ulduar_MASK & (1 << TYPE_XT002)) == 0;
                 case 10598:
                 case 10599:
                     return (C_of_Ulduar_MASK & (1 << TYPE_ASSEMBLY)) == 0;
                 case 10348:
                 case 10357:
                     return (C_of_Ulduar_MASK & (1 << TYPE_KOLOGARN)) == 0;
                 case 10351:
                 case 10363:
                     return (C_of_Ulduar_MASK & (1 << TYPE_AURIAYA)) == 0;
                 case 10439:
                 case 10719:
                     return (C_of_Ulduar_MASK & (1 << TYPE_HODIR)) == 0;
                 case 10403:
                 case 10404:
                     return (C_of_Ulduar_MASK & (1 << TYPE_THORIM)) == 0;
                 case 10582:
                 case 10583:
                     return (C_of_Ulduar_MASK & (1 << TYPE_FREYA)) == 0;
                 case 10347:
                 case 10361:
                     return (C_of_Ulduar_MASK & (1 << TYPE_MIMIRON)) == 0;
                 case 10349:
                 case 10362:
                     return (C_of_Ulduar_MASK & (1 << TYPE_VEZAX)) == 0;
                 case 10350:
                 case 10364:
                     return (C_of_Ulduar_MASK & (1 << TYPE_YOGGSARON)) == 0;
             }
             return false;
         }
References C_of_Ulduar_MASK, TYPE_ASSEMBLY, TYPE_AURIAYA, TYPE_FREYA, TYPE_HODIR, TYPE_IGNIS, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_RAZORSCALE, TYPE_THORIM, TYPE_VEZAX, TYPE_XT002, and TYPE_YOGGSARON.
FillInitialWorldStates()
void instance_ulduar::instance_ulduar_InstanceMapScript::FillInitialWorldStates (WorldPacket & packet) inline override virtual
Reimplemented from InstanceScript.
Definition at line 160 of file instance_ulduar.cpp.
         {
             packet << uint32(WORLD_STATE_ALGALON_TIMER_ENABLED) << uint32(m_algalonTimer && m_algalonTimer <= 60);
             packet << uint32(WORLD_STATE_ALGALON_DESPAWN_TIMER) << uint32(std::min<uint32>(m_algalonTimer, 60));
         }
References m_algalonTimer, and WORLD_STATE_ALGALON_TIMER_ENABLED.
GetData()
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 965 of file instance_ulduar.cpp.
         {
             switch(type)
             {
                 case TYPE_LEVIATHAN:
                 case TYPE_IGNIS:
                 case TYPE_RAZORSCALE:
                 case TYPE_XT002:
                 case TYPE_ASSEMBLY:
                 case TYPE_KOLOGARN:
                 case TYPE_AURIAYA:
                 case TYPE_MIMIRON:
                 case TYPE_HODIR:
                 case TYPE_THORIM:
                 case TYPE_FREYA:
                 case TYPE_VEZAX:
                 case TYPE_YOGGSARON:
                 case TYPE_ALGALON:
                 case TYPE_WATCHERS:
                     return m_auiEncounter[type];
                 case EVENT_TOWER_OF_LIFE_DESTROYED:
                 case EVENT_TOWER_OF_STORM_DESTROYED:
                 case EVENT_TOWER_OF_FROST_DESTROYED:
                 case EVENT_TOWER_OF_FLAMES_DESTROYED:
                     return m_leviathanTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED];
                 case DATA_MAGE_BARRIER:
                     return m_mageBarrier;
                 case DATA_UNBROKEN_ACHIEVEMENT:
                     return m_unbrokenAchievement;
                 case DATA_CALL_TRAM:
                     return m_mimironTramUsed;
             }
             return 0;
         }
References DATA_CALL_TRAM, DATA_MAGE_BARRIER, DATA_UNBROKEN_ACHIEVEMENT, EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, m_auiEncounter, m_leviathanTowers, m_mageBarrier, m_mimironTramUsed, m_unbrokenAchievement, TYPE_ALGALON, TYPE_ASSEMBLY, TYPE_AURIAYA, TYPE_FREYA, TYPE_HODIR, TYPE_IGNIS, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_RAZORSCALE, TYPE_THORIM, TYPE_VEZAX, TYPE_WATCHERS, TYPE_XT002, and TYPE_YOGGSARON.
Referenced by Load(), OnCreatureCreate(), OnGameObjectCreate(), OnUnitDeath(), OpenIfDone(), SetData(), and ShowKeeperGossip().
GetGuidData()
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 838 of file instance_ulduar.cpp.
         {
             switch (data)
             {
                 // Bosses
                 case TYPE_LEVIATHAN:
                     return m_uiLeviathanGUID;
                 case TYPE_IGNIS:
                     return m_uiIgnisGUID;
                 case TYPE_RAZORSCALE:
                     return m_uiRazorscaleGUID;
                 case TYPE_XT002:
                     return m_uiXT002GUID;
                 case TYPE_KOLOGARN:
                     return m_uiKologarnGUID;
                 case TYPE_AURIAYA:
                     return m_uiAuriayaGUID;
                 case TYPE_MIMIRON:
                     return m_uiMimironGUID;
                 case TYPE_HODIR:
                     return m_uiHodirGUID;
                 case TYPE_THORIM:
                     return m_uiThorimGUID;
                 case TYPE_FREYA:
                     return m_uiFreyaGUID;
                 case TYPE_VEZAX:
                     return m_uiVezaxGUID;
                 case TYPE_YOGGSARON:
                     return m_uiYoggSaronGUID;
                 case TYPE_ALGALON:
                     return m_uiAlgalonGUID;
                 case DATA_STEELBREAKER:
                     return m_auiAssemblyGUIDs[0];
                 case DATA_MOLGEIM:
                     return m_auiAssemblyGUIDs[1];
                 case DATA_BRUNDIR:
                     return m_auiAssemblyGUIDs[2];
                 // Flame Leviathan
                 case DATA_REPAIR_STATION1:
                     return m_RepairSGUID[0];
                 case DATA_REPAIR_STATION2:
                     return m_RepairSGUID[1];
                 case DATA_LIGHTNING_WALL1:
                     return m_lightningWalls[0];
                 case DATA_LIGHTNING_WALL2:
                     return m_lightningWalls[1];
                 case GO_LEVIATHAN_DOORS:
                     return m_leviathanDoorsGUID;
                 // Razorscales Harpoon Fire State GUIDs
                 case DATA_HARPOON_FIRE_STATE_1:
                 case DATA_HARPOON_FIRE_STATE_2:
                 case DATA_HARPOON_FIRE_STATE_3:
                 case DATA_HARPOON_FIRE_STATE_4:
                     return m_RazorscaleHarpoonFireStateGUID[data - 200];
                 // XT-002
                 case GO_XT002_DOORS:
                     return m_xt002DoorsGUID;
                 // XT-002
                 case GO_KOLOGARN_DOORS:
                     return KologarnDoorGUID;
                 // Thorim
                 case DATA_THORIM_LEVER_GATE:
                 case DATA_THORIM_LEVER:
                 case DATA_THORIM_FENCE:
                 case DATA_THORIM_FIRST_DOORS:
                 case DATA_THORIM_SECOND_DOORS:
                     return m_thorimGameobjectsGUID[data - DATA_THORIM_LEVER_GATE];
                 // Hodir chests
                 case GO_HODIR_CHEST_HARD:
                 case GO_HODIR_CHEST_HARD_HERO:
                     return m_hodirHardmodeChest;
                 case GO_HODIR_CHEST_NORMAL:
                 case GO_HODIR_CHEST_NORMAL_HERO:
                     return m_hodirNormalChest;
                 // Freya Elders
                 case NPC_ELDER_IRONBRANCH:
                 case NPC_ELDER_STONEBARK:
                 case NPC_ELDER_BRIGHTLEAF:
                     return m_FreyaElder[data - NPC_ELDER_IRONBRANCH];
                 // Mimiron's first vehicle (spawned by default)
                 case DATA_MIMIRON_LEVIATHAN_MKII:
                     return m_MimironLeviathanMKIIguid;
                 case DATA_MIMIRON_VX001:
                     return m_MimironVX001guid;
                 case DATA_MIMIRON_ACU:
                     return m_MimironACUguid;
                 case DATA_GO_MIMIRON_DOOR_1:
                 case DATA_GO_MIMIRON_DOOR_2:
                 case DATA_GO_MIMIRON_DOOR_3:
                     return m_MimironDoor[data - 311];
                 // Yogg-Saron
                 case GO_YOGG_SARON_DOORS:
                     return m_yoggsaronDoorsGUID;
                 case NPC_SARA:
                     return m_saraGUID;
                 case NPC_BRAIN_OF_YOGG_SARON:
                     return m_yoggsaronBrainGUID;
                 // Algalon the Observer
                 case GO_DOODAD_UL_SIGILDOOR_01:
                     return m_algalonSigilDoorGUID[0];
                 case GO_DOODAD_UL_SIGILDOOR_02:
                     return m_algalonSigilDoorGUID[1];
                 case GO_DOODAD_UL_SIGILDOOR_03:
                     return m_algalonSigilDoorGUID[2];
                 case GO_DOODAD_UL_UNIVERSEFLOOR_01:
                     return m_algalonFloorGUID[0];
                 case GO_DOODAD_UL_UNIVERSEFLOOR_02:
                     return m_algalonFloorGUID[1];
                 case GO_DOODAD_UL_UNIVERSEGLOBE01:
                     return m_algalonUniverseGUID;
                 case GO_DOODAD_UL_ULDUAR_TRAPDOOR_03:
                     return m_algalonTrapdoorGUID;
                 case NPC_BRANN_BRONZBEARD_ALG:
                     return m_brannBronzebeardAlgGUID;
             }
             return ObjectGuid::Empty;
         }
References DATA_BRUNDIR, DATA_GO_MIMIRON_DOOR_1, DATA_GO_MIMIRON_DOOR_2, DATA_GO_MIMIRON_DOOR_3, DATA_HARPOON_FIRE_STATE_1, DATA_HARPOON_FIRE_STATE_2, DATA_HARPOON_FIRE_STATE_3, DATA_HARPOON_FIRE_STATE_4, DATA_LIGHTNING_WALL1, DATA_LIGHTNING_WALL2, DATA_MIMIRON_ACU, DATA_MIMIRON_LEVIATHAN_MKII, DATA_MIMIRON_VX001, DATA_MOLGEIM, DATA_REPAIR_STATION1, DATA_REPAIR_STATION2, DATA_STEELBREAKER, DATA_THORIM_FENCE, DATA_THORIM_FIRST_DOORS, DATA_THORIM_LEVER, DATA_THORIM_LEVER_GATE, DATA_THORIM_SECOND_DOORS, ObjectGuid::Empty, GO_DOODAD_UL_SIGILDOOR_01, GO_DOODAD_UL_SIGILDOOR_02, GO_DOODAD_UL_SIGILDOOR_03, GO_DOODAD_UL_ULDUAR_TRAPDOOR_03, GO_DOODAD_UL_UNIVERSEFLOOR_01, GO_DOODAD_UL_UNIVERSEFLOOR_02, GO_DOODAD_UL_UNIVERSEGLOBE01, GO_HODIR_CHEST_HARD, GO_HODIR_CHEST_HARD_HERO, GO_HODIR_CHEST_NORMAL, GO_HODIR_CHEST_NORMAL_HERO, GO_KOLOGARN_DOORS, GO_LEVIATHAN_DOORS, GO_XT002_DOORS, GO_YOGG_SARON_DOORS, KologarnDoorGUID, m_algalonFloorGUID, m_algalonSigilDoorGUID, m_algalonTrapdoorGUID, m_algalonUniverseGUID, m_auiAssemblyGUIDs, m_brannBronzebeardAlgGUID, m_FreyaElder, m_hodirHardmodeChest, m_hodirNormalChest, m_leviathanDoorsGUID, m_lightningWalls, m_MimironACUguid, m_MimironDoor, m_MimironLeviathanMKIIguid, m_MimironVX001guid, m_RazorscaleHarpoonFireStateGUID, m_RepairSGUID, m_saraGUID, m_thorimGameobjectsGUID, m_uiAlgalonGUID, m_uiAuriayaGUID, m_uiFreyaGUID, m_uiHodirGUID, m_uiIgnisGUID, m_uiKologarnGUID, m_uiLeviathanGUID, m_uiMimironGUID, m_uiRazorscaleGUID, m_uiThorimGUID, m_uiVezaxGUID, m_uiXT002GUID, m_uiYoggSaronGUID, m_xt002DoorsGUID, m_yoggsaronBrainGUID, m_yoggsaronDoorsGUID, NPC_BRAIN_OF_YOGG_SARON, NPC_BRANN_BRONZBEARD_ALG, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRANCH, NPC_ELDER_STONEBARK, NPC_SARA, TYPE_ALGALON, TYPE_AURIAYA, TYPE_FREYA, TYPE_HODIR, TYPE_IGNIS, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_RAZORSCALE, TYPE_THORIM, TYPE_VEZAX, TYPE_XT002, and TYPE_YOGGSARON.
Referenced by SetData().
GetSaveData()
std::string instance_ulduar::instance_ulduar_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 1046 of file instance_ulduar.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "U U " << m_auiEncounter[0] << ' ' << m_auiEncounter[1] << ' ' << m_auiEncounter[2] << ' ' << m_auiEncounter[3] << ' '
                        << m_auiEncounter[4] << ' ' << m_auiEncounter[5] << ' ' << m_auiEncounter[6] << ' ' << m_auiEncounter[7] << ' '
                        << m_auiEncounter[8] << ' ' << m_auiEncounter[9] << ' ' << m_auiEncounter[10] << ' ' << m_auiEncounter[11] << ' '
                        << m_auiEncounter[12] << ' ' << m_auiEncounter[13] << ' ' << m_auiEncounter[14] << ' ' << m_conspeedatoryAttempt << ' '
                        << m_unbrokenAchievement << ' ' << m_algalonTimer << ' ' << C_of_Ulduar_MASK << ' ' << m_mageBarrier;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References C_of_Ulduar_MASK, m_algalonTimer, m_auiEncounter, m_conspeedatoryAttempt, m_mageBarrier, m_unbrokenAchievement, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_ulduar::instance_ulduar_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 132 of file instance_ulduar.cpp.
         {
             // Bosses
             memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
             C_of_Ulduar_MASK = 0;
             // Flame Leviathan
             for (uint8 i = 0; i < 4; ++i)
                 m_leviathanTowers[i] = false;
             _leviathanVehicles.clear();
             m_unbrokenAchievement   = 1;
             m_mageBarrier           = 0;
             // Hodir
             hmHodir = true; // If players fail the Hardmode then becomes false
             // Freya
             m_conspeedatoryAttempt  = 0;
             // Algalon
             m_algalonTimer          = 0;
             // Shared
             _events.Reset();
             m_mimironTramUsed       = false;
         }
References _events, _leviathanVehicles, C_of_Ulduar_MASK, hmHodir, m_algalonTimer, m_auiEncounter, m_conspeedatoryAttempt, m_leviathanTowers, m_mageBarrier, m_mimironTramUsed, m_unbrokenAchievement, and EventMap::Reset().
Referenced by instance_ulduar_InstanceMapScript().
IsEncounterInProgress()
bool instance_ulduar::instance_ulduar_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 192 of file instance_ulduar.cpp.
         {
             for (uint8 i = 0; i < (MAX_ENCOUNTER - 1); ++i)
             {
                 if (m_auiEncounter[i] == IN_PROGRESS)
                     return true;
             }
             // Leviathan does not use IN_PROGRESS type, instead SPECIAL is set and never reset,
             // Check if he is in combat.
             if (Unit* l = instance->GetCreature(m_uiLeviathanGUID))
                 if (l->IsInCombat())
                     return true;
             return false;
         }
References Map::GetCreature(), IN_PROGRESS, InstanceScript::instance, m_auiEncounter, m_uiLeviathanGUID, and MAX_ENCOUNTER.
Load()
void instance_ulduar::instance_ulduar_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
Definition at line 1061 of file instance_ulduar.cpp.
         {
             if (!strIn)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(strIn);
             char dataHead1, dataHead2;
             std::istringstream loadStream(strIn);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'U' && dataHead2 == 'U')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     loadStream >> m_auiEncounter[i];
                     if (m_auiEncounter[i] == IN_PROGRESS && i != TYPE_WATCHERS)
                         m_auiEncounter[i] = NOT_STARTED;
                 }
                 // Achievements
                 loadStream >> m_conspeedatoryAttempt;
                 loadStream >> m_unbrokenAchievement;
                 // Algalon
                 loadStream >> m_algalonTimer;
                 if (m_algalonTimer == TIMER_ALGALON_SUMMONED)
                     m_algalonTimer = TIMER_ALGALON_TO_SUMMON;
                 if (m_algalonTimer && m_algalonTimer <= 60 && GetData(TYPE_ALGALON) != DONE)
                 {
                     DoUpdateWorldState(WORLD_STATE_ALGALON_TIMER_ENABLED, 1);
                     DoUpdateWorldState(WORLD_STATE_ALGALON_DESPAWN_TIMER, m_algalonTimer);
                 }
                 // achievement Conqueror/Champion of Ulduar
                 loadStream >> C_of_Ulduar_MASK;
                 //Base Camp - Mage Barrier status
                 loadStream >> m_mageBarrier;
             }
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References C_of_Ulduar_MASK, DONE, InstanceScript::DoUpdateWorldState(), GetData(), IN_PROGRESS, m_algalonTimer, m_auiEncounter, m_conspeedatoryAttempt, m_mageBarrier, m_unbrokenAchievement, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, TIMER_ALGALON_SUMMONED, TIMER_ALGALON_TO_SUMMON, TYPE_ALGALON, TYPE_WATCHERS, WORLD_STATE_ALGALON_DESPAWN_TIMER, and WORLD_STATE_ALGALON_TIMER_ENABLED.
OnCreatureCreate()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
These creatures are summoned by something else than Algalon but need to be controlled/despawned by him - so they need to be registered in his summon list
Reimplemented from InstanceScript.
Definition at line 288 of file instance_ulduar.cpp.
         {
             switch(creature->GetEntry())
             {
                 case NPC_LEVIATHAN:
                     m_uiLeviathanGUID = creature->GetGUID();
                     break;
                 case NPC_IGNIS:
                     m_uiIgnisGUID = creature->GetGUID();
                     break;
                 case NPC_RAZORSCALE:
                     m_uiRazorscaleGUID = creature->GetGUID();
                     break;
                 case NPC_XT002:
                     m_uiXT002GUID = creature->GetGUID();
                     break;
                 case NPC_STEELBREAKER:
                     m_auiAssemblyGUIDs[0] = creature->GetGUID();
                     break;
                 case NPC_MOLGEIM:
                     m_auiAssemblyGUIDs[1] = creature->GetGUID();
                     break;
                 case NPC_BRUNDIR:
                     m_auiAssemblyGUIDs[2] = creature->GetGUID();
                     break;
                 case NPC_KOLOGARN:
                     m_uiKologarnGUID = creature->GetGUID();
                     if (GetData(TYPE_KOLOGARN) == DONE)
                     {
                         creature->SetDisableGravity(true);
                         creature->SetPosition(creature->GetHomePosition());
                         creature->setDeathState(JUST_DIED);
                         creature->StopMovingOnCurrentPos();
                     }
                     break;
                 case NPC_AURIAYA:
                     m_uiAuriayaGUID = creature->GetGUID();
                     break;
                 case NPC_MIMIRON:
                     m_uiMimironGUID = creature->GetGUID();
                     break;
                 case NPC_HODIR:
                     m_uiHodirGUID = creature->GetGUID();
                     break;
                 case NPC_THORIM:
                     m_uiThorimGUID = creature->GetGUID();
                     break;
                 case NPC_FREYA:
                     m_uiFreyaGUID = creature->GetGUID();
                     break;
                 case NPC_VEZAX:
                     m_uiVezaxGUID = creature->GetGUID();
                     break;
                 case NPC_YOGGSARON:
                     m_uiYoggSaronGUID = creature->GetGUID();
                     break;
                 case NPC_ALGALON:
                     m_uiAlgalonGUID = creature->GetGUID();
                     break;
                 case NPC_HARPOON_FIRE_STATE:
                     {
                         if( creature->GetPositionX() > 595 )
                             m_RazorscaleHarpoonFireStateGUID[3] = creature->GetGUID();
                         else if( creature->GetPositionX() > 585 )
                             m_RazorscaleHarpoonFireStateGUID[2] = creature->GetGUID();
                         else if( creature->GetPositionX() > 575 )
                             m_RazorscaleHarpoonFireStateGUID[1] = creature->GetGUID();
                         else
                             m_RazorscaleHarpoonFireStateGUID[0] = creature->GetGUID();
                     }
                     break;
                 case NPC_MIMIRON_LEVIATHAN_MKII:
                     m_MimironLeviathanMKIIguid = creature->GetGUID();
                     break;
                 case NPC_MIMIRON_VX001:
                     m_MimironVX001guid = creature->GetGUID();
                     break;
                 case NPC_MIMIRON_ACU:
                     m_MimironACUguid = creature->GetGUID();
                     break;
                 case NPC_FREYA_GOSSIP:
                     m_keepersGossipGUID[TYPE_FREYA - TYPE_FREYA] = creature->GetGUID();
                     ShowKeeperGossip(TYPE_FREYA, creature);
                     break;
                 case NPC_HODIR_GOSSIP:
                     m_keepersGossipGUID[TYPE_HODIR - TYPE_FREYA] = creature->GetGUID();
                     ShowKeeperGossip(TYPE_HODIR, creature);
                     break;
                 case NPC_THORIM_GOSSIP:
                     m_keepersGossipGUID[TYPE_THORIM - TYPE_FREYA] = creature->GetGUID();
                     ShowKeeperGossip(TYPE_THORIM, creature);
                     break;
                 case NPC_MIMIRON_GOSSIP:
                     m_keepersGossipGUID[TYPE_MIMIRON - TYPE_FREYA] = creature->GetGUID();
                     ShowKeeperGossip(TYPE_MIMIRON, creature);
                     break;
                 case NPC_ELDER_IRONBRANCH:
                 case NPC_ELDER_STONEBARK:
                 case NPC_ELDER_BRIGHTLEAF:
                     m_FreyaElder[creature->GetEntry() - NPC_ELDER_IRONBRANCH] = creature->GetGUID();
                     break;
                 case NPC_SARA:
                     m_saraGUID = creature->GetGUID();
                     break;
                 case NPC_BRAIN_OF_YOGG_SARON:
                     m_yoggsaronBrainGUID = creature->GetGUID();
                     break;
                 case NPC_BRANN_BRONZBEARD_ALG:
                     m_brannBronzebeardAlgGUID = creature->GetGUID();
                     break;
                 case NPC_BRANN_BASE_CAMP:
                     m_brannBronzebeardBaseCamp = creature->GetGUID();
                     break;
                 case NPC_ALGALON_VOID_ZONE_VISUAL_STALKER:
                 case NPC_ALGALON_STALKER_ASTEROID_TARGET_01:
                 case NPC_ALGALON_STALKER_ASTEROID_TARGET_02:
                 case NPC_UNLEASHED_DARK_MATTER:
                     if (Creature* algalon = instance->GetCreature(m_uiAlgalonGUID))
                         algalon->AI()->JustSummoned(creature);
                     break;
             }
         }
References DONE, Map::GetCreature(), GetData(), Object::GetEntry(), Object::GetGUID(), Creature::GetHomePosition(), Position::GetPositionX(), InstanceScript::instance, JUST_DIED, m_auiAssemblyGUIDs, m_brannBronzebeardAlgGUID, m_brannBronzebeardBaseCamp, m_FreyaElder, m_keepersGossipGUID, m_MimironACUguid, m_MimironLeviathanMKIIguid, m_MimironVX001guid, m_RazorscaleHarpoonFireStateGUID, m_saraGUID, m_uiAlgalonGUID, m_uiAuriayaGUID, m_uiFreyaGUID, m_uiHodirGUID, m_uiIgnisGUID, m_uiKologarnGUID, m_uiLeviathanGUID, m_uiMimironGUID, m_uiRazorscaleGUID, m_uiThorimGUID, m_uiVezaxGUID, m_uiXT002GUID, m_uiYoggSaronGUID, m_yoggsaronBrainGUID, NPC_ALGALON, NPC_ALGALON_STALKER_ASTEROID_TARGET_01, NPC_ALGALON_STALKER_ASTEROID_TARGET_02, NPC_ALGALON_VOID_ZONE_VISUAL_STALKER, NPC_AURIAYA, NPC_BRAIN_OF_YOGG_SARON, NPC_BRANN_BASE_CAMP, NPC_BRANN_BRONZBEARD_ALG, NPC_BRUNDIR, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRANCH, NPC_ELDER_STONEBARK, NPC_FREYA, NPC_FREYA_GOSSIP, NPC_HARPOON_FIRE_STATE, NPC_HODIR, NPC_HODIR_GOSSIP, NPC_IGNIS, NPC_KOLOGARN, NPC_LEVIATHAN, NPC_MIMIRON, NPC_MIMIRON_ACU, NPC_MIMIRON_GOSSIP, NPC_MIMIRON_LEVIATHAN_MKII, NPC_MIMIRON_VX001, NPC_MOLGEIM, NPC_RAZORSCALE, NPC_SARA, NPC_STEELBREAKER, NPC_THORIM, NPC_THORIM_GOSSIP, NPC_UNLEASHED_DARK_MATTER, NPC_VEZAX, NPC_XT002, NPC_YOGGSARON, Creature::setDeathState(), Creature::SetDisableGravity(), Creature::SetPosition(), ShowKeeperGossip(), Unit::StopMovingOnCurrentPos(), TYPE_FREYA, TYPE_HODIR, TYPE_KOLOGARN, TYPE_MIMIRON, and TYPE_THORIM.
OnCreatureRemove()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 414 of file instance_ulduar.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_BRANN_BRONZBEARD_ALG:
                     if (m_brannBronzebeardAlgGUID == creature->GetGUID())
                         m_brannBronzebeardAlgGUID.Clear();
                     break;
             }
         }
References ObjectGuid::Clear(), Object::GetEntry(), Object::GetGUID(), m_brannBronzebeardAlgGUID, and NPC_BRANN_BRONZBEARD_ALG.
OnGameObjectCreate()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 444 of file instance_ulduar.cpp.
         {
             switch (gameObject->GetEntry())
             {
                 // Flame Leviathan
                 case GO_REPAIR_STATION_TRAP:
                     {
                         if(m_RepairSGUID[0])
                             m_RepairSGUID[1] = gameObject->GetGUID();
                         else
                             m_RepairSGUID[0] = gameObject->GetGUID();
                         break;
                     }
                 case GO_LIGHTNING_WALL1:
                     m_lightningWalls[0] = gameObject->GetGUID();
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     break;
                 case GO_LIGHTNING_WALL2:
                     m_lightningWalls[1] = gameObject->GetGUID();
                     break;
                 case GO_MIMIRONS_TARGETTING_CRYSTAL:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[3][0] = gameObject->GetGUID();
                     break;
                 case GO_FREYAS_TARGETTING_CRYSTAL:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[0][0] = gameObject->GetGUID();
                     break;
                 case GO_HODIRS_TARGETTING_CRYSTAL:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[2][0] = gameObject->GetGUID();
                     break;
                 case GO_THORIMS_TARGETTING_CRYSTAL:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[1][0] = gameObject->GetGUID();
                     break;
                 case GO_MIMIRONS_GENERATOR:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[3][1] = gameObject->GetGUID();
                     break;
                 case GO_FREYAS_GENERATOR:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[0][1] = gameObject->GetGUID();
                     break;
                 case GO_HODIRS_GENERATOR:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[2][1] = gameObject->GetGUID();
                     break;
                 case GO_THORIMS_GENERATOR:
                     OpenIfDone(TYPE_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                     m_leviathanVisualTowers[1][1] = gameObject->GetGUID();
                     break;
                 case GO_LEVIATHAN_DOORS:
                     if (GetData(TYPE_LEVIATHAN) >= DONE)
                         gameObject->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                     m_leviathanDoorsGUID = gameObject->GetGUID();
                     break;
                 // XT-002, Kologarn, Assembly of Iron
                 case GO_XT002_DOORS:
                     m_xt002DoorsGUID = gameObject->GetGUID();
                     break;
                 case GO_KOLOGARN_DOORS:
                     KologarnDoorGUID = gameObject->GetGUID();
                     break;
                 case GO_KOLOGARN_BRIDGE:
                     OpenIfDone(TYPE_KOLOGARN, gameObject, GO_STATE_READY);
                     break;
                 case GO_ASSEMBLY_DOORS:
                     m_assemblyDoorsGUID = gameObject->GetGUID();
                     break;
                 case GO_ARCHIVUM_DOORS:
                     m_archivumDoorsGUID = gameObject->GetGUID();
                     OpenIfDone(TYPE_ASSEMBLY, gameObject, GO_STATE_ACTIVE);
                     break;
                 // Thorim
                 case GO_ARENA_LEVER_GATE:
                     m_thorimGameobjectsGUID[DATA_THORIM_LEVER_GATE - DATA_THORIM_LEVER_GATE] = gameObject->GetGUID();
                     break;
                 case GO_ARENA_LEVER:
                     m_thorimGameobjectsGUID[DATA_THORIM_LEVER - DATA_THORIM_LEVER_GATE] = gameObject->GetGUID();
                     break;
                 case GO_ARENA_FENCE:
                     m_thorimGameobjectsGUID[DATA_THORIM_FENCE - DATA_THORIM_LEVER_GATE] = gameObject->GetGUID();
                     break;
                 case GO_FIRST_COLOSSUS_DOORS:
                     m_thorimGameobjectsGUID[DATA_THORIM_FIRST_DOORS - DATA_THORIM_LEVER_GATE] = gameObject->GetGUID();
                     break;
                 case GO_SECOND_COLOSSUS_DOORS:
                     m_thorimGameobjectsGUID[DATA_THORIM_SECOND_DOORS - DATA_THORIM_LEVER_GATE] = gameObject->GetGUID();
                     break;
                 // Yogg-Saron
                 case GO_YOGG_SARON_DOORS:
                     m_yoggsaronDoorsGUID = gameObject->GetGUID();
                     break;
                 case GO_KEEPERS_GATE:
                     if (GetData(TYPE_MIMIRON) == DONE && GetData(TYPE_FREYA) == DONE && GetData(TYPE_HODIR) == DONE && GetData(TYPE_THORIM) == DONE)
                     {
                         instance->LoadGrid(1903.0f, 248.0f);
                         gameObject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_LOCKED);
                     }
                     m_keepersgateGUID = gameObject->GetGUID();
                     break;
                 // Mimiron, Hodir, Vezax
                 case GO_MIMIRON_ELEVATOR:
                     gameObject->EnableCollision(false);
                     break;
                 case GO_MIMIRON_DOOR_1:
                     m_MimironDoor[0] = gameObject->GetGUID();
                     break;
                 case GO_MIMIRON_DOOR_2:
                     m_MimironDoor[1] = gameObject->GetGUID();
                     break;
                 case GO_MIMIRON_DOOR_3:
                     m_MimironDoor[2] = gameObject->GetGUID();
                     break;
                 case GO_HODIR_FROZEN_DOOR:
                 case GO_HODIR_DOOR:
                     if (GetData(TYPE_HODIR) == DONE)
                         if( gameObject->GetGoState() != GO_STATE_ACTIVE )
{
                             gameObject->SetLootState(GO_READY);
                             gameObject->UseDoorOrButton(0, false);
                         }
                     break;
                 case GO_VEZAX_DOOR:
                     if( GetData(TYPE_VEZAX) == DONE )
                         if( gameObject->GetGoState() != GO_STATE_ACTIVE )
{
                             gameObject->SetLootState(GO_READY);
                             gameObject->UseDoorOrButton(0, false);
                         }
                     break;
                 case GO_SNOW_MOUND:
                     gameObject->EnableCollision(false);
                     break;
                 case GO_MIMIRON_TRAM:
                     if (GetData(TYPE_MIMIRON) == DONE)
                         m_mimironTramUsed = true;
                     m_mimironTramGUID = gameObject->GetGUID();
                     break;
                 // Algalon the Observer
                 case GO_CELESTIAL_PLANETARIUM_ACCESS_10:
                 case GO_CELESTIAL_PLANETARIUM_ACCESS_25:
                     if (m_algalonTimer)
                         gameObject->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                     break;
                 case GO_DOODAD_UL_SIGILDOOR_01:
                     m_algalonSigilDoorGUID[0] = gameObject->GetGUID();
                     if (m_algalonTimer)
                         gameObject->SetGoState(GO_STATE_ACTIVE);
                     break;
                 case GO_DOODAD_UL_SIGILDOOR_02:
                     m_algalonSigilDoorGUID[1] = gameObject->GetGUID();
                     if (m_algalonTimer)
                         gameObject->SetGoState(GO_STATE_ACTIVE);
                     break;
                 case GO_DOODAD_UL_SIGILDOOR_03:
                     m_algalonSigilDoorGUID[2] = gameObject->GetGUID();
                     break;
                 case GO_DOODAD_UL_UNIVERSEFLOOR_01:
                     m_algalonFloorGUID[0] = gameObject->GetGUID();
                     break;
                 case GO_DOODAD_UL_UNIVERSEFLOOR_02:
                     m_algalonFloorGUID[1] = gameObject->GetGUID();
                     break;
                 case GO_DOODAD_UL_UNIVERSEGLOBE01:
                     m_algalonUniverseGUID = gameObject->GetGUID();
                     break;
                 case GO_DOODAD_UL_ULDUAR_TRAPDOOR_03:
                     m_algalonTrapdoorGUID = gameObject->GetGUID();
                     break;
                 // Herbs
                 case 191019: // Adder's Tongue
                 case 190176: // Frost Lotus
                 case 190171: // Lichbloom
                 case 190170: // Talandra's Rose
                 case 189973: // Goldclover
                     if (GetData(TYPE_FREYA) == DONE)
                         gameObject->SetRespawnTime(7 * DAY);
                     break;
             }
         }
References DATA_THORIM_FENCE, DATA_THORIM_FIRST_DOORS, DATA_THORIM_LEVER, DATA_THORIM_LEVER_GATE, DATA_THORIM_SECOND_DOORS, DAY, DONE, GameObject::EnableCollision(), GAMEOBJECT_FLAGS, GetData(), Object::GetEntry(), GameObject::GetGoState(), Object::GetGUID(), GO_ARCHIVUM_DOORS, GO_ARENA_FENCE, GO_ARENA_LEVER, GO_ARENA_LEVER_GATE, GO_ASSEMBLY_DOORS, GO_CELESTIAL_PLANETARIUM_ACCESS_10, GO_CELESTIAL_PLANETARIUM_ACCESS_25, GO_DOODAD_UL_SIGILDOOR_01, GO_DOODAD_UL_SIGILDOOR_02, GO_DOODAD_UL_SIGILDOOR_03, GO_DOODAD_UL_ULDUAR_TRAPDOOR_03, GO_DOODAD_UL_UNIVERSEFLOOR_01, GO_DOODAD_UL_UNIVERSEFLOOR_02, GO_DOODAD_UL_UNIVERSEGLOBE01, GO_FIRST_COLOSSUS_DOORS, GO_FLAG_IN_USE, GO_FLAG_LOCKED, GO_FREYAS_GENERATOR, GO_FREYAS_TARGETTING_CRYSTAL, GO_HODIR_DOOR, GO_HODIR_FROZEN_DOOR, GO_HODIRS_GENERATOR, GO_HODIRS_TARGETTING_CRYSTAL, GO_KEEPERS_GATE, GO_KOLOGARN_BRIDGE, GO_KOLOGARN_DOORS, GO_LEVIATHAN_DOORS, GO_LIGHTNING_WALL1, GO_LIGHTNING_WALL2, GO_MIMIRON_DOOR_1, GO_MIMIRON_DOOR_2, GO_MIMIRON_DOOR_3, GO_MIMIRON_ELEVATOR, GO_MIMIRON_TRAM, GO_MIMIRONS_GENERATOR, GO_MIMIRONS_TARGETTING_CRYSTAL, GO_READY, GO_REPAIR_STATION_TRAP, GO_SECOND_COLOSSUS_DOORS, GO_SNOW_MOUND, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, GO_THORIMS_GENERATOR, GO_THORIMS_TARGETTING_CRYSTAL, GO_VEZAX_DOOR, GO_XT002_DOORS, GO_YOGG_SARON_DOORS, InstanceScript::instance, KologarnDoorGUID, Map::LoadGrid(), m_algalonFloorGUID, m_algalonSigilDoorGUID, m_algalonTimer, m_algalonTrapdoorGUID, m_algalonUniverseGUID, m_archivumDoorsGUID, m_assemblyDoorsGUID, m_keepersgateGUID, m_leviathanDoorsGUID, m_leviathanVisualTowers, m_lightningWalls, m_MimironDoor, m_mimironTramGUID, m_mimironTramUsed, m_RepairSGUID, m_thorimGameobjectsGUID, m_xt002DoorsGUID, m_yoggsaronDoorsGUID, OpenIfDone(), Object::RemoveFlag(), Object::SetFlag(), GameObject::SetGoState(), GameObject::SetLootState(), GameObject::SetRespawnTime(), TYPE_ASSEMBLY, TYPE_FREYA, TYPE_HODIR, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_THORIM, TYPE_VEZAX, and GameObject::UseDoorOrButton().
OnPlayerEnter()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
Definition at line 166 of file instance_ulduar.cpp.
         {
             // mimiron tram:
             instance->LoadGrid(2307.0f, 284.632f);
             if (GameObject* MimironTram = instance->GetGameObject(m_mimironTramGUID))
                 player->UpdateVisibilityOf(MimironTram);
             if (!m_uiAlgalonGUID && m_algalonTimer && (m_algalonTimer <= 60 || m_algalonTimer == TIMER_ALGALON_TO_SUMMON))
             {
                 TempSummon* algalon = instance->SummonCreature(NPC_ALGALON, AlgalonLandPos);
                 if (!algalon)
                     return;
                 if (m_algalonTimer <= 60)
                 {
                     _events.RescheduleEvent(EVENT_UPDATE_ALGALON_TIMER, 60000);
                     algalon->AI()->DoAction(ACTION_INIT_ALGALON);
                 }
                 else // if (m_algalonTimer = TIMER_ALGALON_TO_SUMMON)
                 {
                     m_algalonTimer = TIMER_ALGALON_SUMMONED;
                     algalon->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                 }
             }
         }
References _events, ACTION_INIT_ALGALON, Creature::AI(), AlgalonLandPos, UnitAI::DoAction(), EVENT_UPDATE_ALGALON_TIMER, Map::GetGameObject(), InstanceScript::instance, Map::LoadGrid(), m_algalonTimer, m_mimironTramGUID, m_uiAlgalonGUID, NPC_ALGALON, Object::RemoveFlag(), EventMap::RescheduleEvent(), Map::SummonCreature(), TIMER_ALGALON_SUMMONED, TIMER_ALGALON_TO_SUMMON, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and Player::UpdateVisibilityOf().
OnUnitDeath()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 1005 of file instance_ulduar.cpp.
         {
             // Feeds on Tears achievement
             if (unit->GetTypeId() == TYPEID_PLAYER)
             {
                 if (GetData(TYPE_ALGALON) == IN_PROGRESS)
                     if (Creature* algalon = instance->GetCreature(m_uiAlgalonGUID))
                         algalon->AI()->DoAction(ACTION_FEEDS_ON_TEARS_FAILED);
             }
             else if (unit->GetTypeId() == TYPEID_UNIT && unit->GetAreaId() == 4656 /*Conservatory of Life*/)
             {
                 if (time(nullptr) > (m_conspeedatoryAttempt + DAY))
                 {
                     DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, 21597 /*CON-SPEED-ATORY_TIMED_CRITERIA*/);
                     m_conspeedatoryAttempt = time(nullptr);
                     SaveToDB();
                 }
             }
             // achievement Champion/Conqueror of Ulduar
             if (unit->GetTypeId() == TYPEID_PLAYER)
                 for (uint8 i = 0; i <= 12; ++i)
                 {
                     bool go = false;
                     if (i == TYPE_LEVIATHAN)
                     {
                         if (Creature* c = instance->GetCreature(m_uiLeviathanGUID))
                             if (c->IsInCombat())
                                 go = true;
                     }
                     else
                         go = (m_auiEncounter[i] == IN_PROGRESS);
                     if (go && (C_of_Ulduar_MASK & (1 << i)) == 0)
                     {
                         C_of_Ulduar_MASK |= (1 << i);
                         SaveToDB();
                     }
                 }
         }
References ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_FEEDS_ON_TEARS_FAILED, C_of_Ulduar_MASK, DAY, InstanceScript::DoStartTimedAchievement(), WorldObject::GetAreaId(), Map::GetCreature(), GetData(), Object::GetTypeId(), IN_PROGRESS, InstanceScript::instance, m_auiEncounter, m_conspeedatoryAttempt, m_uiAlgalonGUID, m_uiLeviathanGUID, InstanceScript::SaveToDB(), TYPE_ALGALON, TYPE_LEVIATHAN, TYPEID_PLAYER, and TYPEID_UNIT.
OpenIfDone()
void instance_ulduar::instance_ulduar_InstanceMapScript::OpenIfDone (uint32 encounter, GameObject * go, GOState state) inline
Definition at line 425 of file instance_ulduar.cpp.
         {
             if (GetData(encounter) == DONE)
                 go->SetGoState(state);
         }
References DONE, GetData(), and GameObject::SetGoState().
Referenced by OnGameObjectCreate().
ProcessEvent()
void instance_ulduar::instance_ulduar_InstanceMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
Definition at line 209 of file instance_ulduar.cpp.
         {
             // destory towers
             if (eventId >= EVENT_TOWER_OF_LIFE_DESTROYED && eventId <= EVENT_TOWER_OF_FLAMES_DESTROYED)
                 SetData(eventId, 0);
         }
References EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, and SetData().
Referenced by SetData().
setChestsLootable()
void instance_ulduar::instance_ulduar_InstanceMapScript::setChestsLootable (uint32 boss) inline
Definition at line 628 of file instance_ulduar.cpp.
         {
             if (boss)
             {
                 switch (boss)
                 {
                     case TYPE_HODIR:
                         if (hmHodir)
                             if (GameObject* go = instance->GetGameObject(m_hodirHardmodeChest))
                                 go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                         if (GameObject* go = instance->GetGameObject(m_hodirNormalChest))
                             go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                         break;
                 }
             }
         }
References GAMEOBJECT_FLAGS, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, hmHodir, InstanceScript::instance, m_hodirHardmodeChest, m_hodirNormalChest, and TYPE_HODIR.
Referenced by SetData().
SetData()
void instance_ulduar::instance_ulduar_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 645 of file instance_ulduar.cpp.
         {
             switch(type)
             {
                 case TYPE_LEVIATHAN:
                     m_auiEncounter[type] = data;
                     if (data == DONE)
                     {
                         Map::PlayerList const& pList = instance->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                             if (Vehicle* veh = itr->GetSource()->GetVehicle())
                                 veh->Dismiss();
                     }
                     break;
                 case TYPE_IGNIS:
                 case TYPE_RAZORSCALE:
                 case TYPE_XT002:
                 case TYPE_AURIAYA:
                 case TYPE_VEZAX:
                 case TYPE_YOGGSARON:
                 case TYPE_KOLOGARN:
                     m_auiEncounter[type] = data;
                     break;
                 case TYPE_ASSEMBLY:
                     if (GameObject* go = instance->GetGameObject(m_assemblyDoorsGUID))
                         go->SetGoState(data == IN_PROGRESS ? GO_STATE_READY : GO_STATE_ACTIVE);
                     if (GameObject* go = instance->GetGameObject(m_archivumDoorsGUID))
                         go->SetGoState(data == DONE ? GO_STATE_ACTIVE : GO_STATE_READY);
                     m_auiEncounter[type] = data;
                     break;
                 case TYPE_MIMIRON:
                 case TYPE_HODIR:
                 case TYPE_THORIM:
                 case TYPE_FREYA:
                     m_auiEncounter[type] = data;
                     ShowKeeperGossip(type, nullptr, m_keepersGossipGUID[type - TYPE_FREYA]);
                     if (GetData(TYPE_MIMIRON) == DONE && GetData(TYPE_FREYA) == DONE && GetData(TYPE_HODIR) == DONE && GetData(TYPE_THORIM) == DONE)
                     {
                         if (GameObject* go = instance->GetGameObject(m_keepersgateGUID))
                             go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_LOCKED);
                     }
                     if (type == TYPE_MIMIRON && data == IN_PROGRESS) // after reaching him without tram and starting the fight
                         m_mimironTramUsed = true;
                     if (GetData(TYPE_HODIR) == DONE)
                         setChestsLootable(TYPE_HODIR);
                     break;
                 case TYPE_SPAWN_HODIR_CACHE:
                     // Is the difficulty 10 man(0) ? return 10 man : return 25 man;
                     SpawnHodirChests(m_difficulty == 0 ? 0 : 1);
                     break;
                 case TYPE_HODIR_HM_FAIL:
                     if (GameObject* go = instance->GetGameObject(m_hodirHardmodeChest))
                     {
                         hmHodir = false;
                         go->Delete();
                         m_hodirHardmodeChest.Clear();
                     }
                     break;
                 case TYPE_WATCHERS:
                     m_auiEncounter[type] |= 1 << data;
                     break;
                 case DATA_MAGE_BARRIER:
                     m_mageBarrier = data;
                     break;
                 case EVENT_TOWER_OF_LIFE_DESTROYED:
                 case EVENT_TOWER_OF_STORM_DESTROYED:
                 case EVENT_TOWER_OF_FROST_DESTROYED:
                 case EVENT_TOWER_OF_FLAMES_DESTROYED:
                     {
                         instance->LoadGrid(364.0f, -16.0f); //make sure leviathan is loaded
                         m_leviathanTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED] = data;
                         for (uint8 i = 0; i < 2; ++i)
{
                             if (GameObject *gameObject = instance->GetGameObject(m_leviathanVisualTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED][i]))
{
                                 gameObject->SetGoState(GO_STATE_ACTIVE);
                             }
                         }
                         return;
                     }
                 case DATA_VEHICLE_SPAWN:
                     SpawnLeviathanEncounterVehicles(data);
                     return;
                 case DATA_UNBROKEN_ACHIEVEMENT:
                     m_unbrokenAchievement = data;
                     SaveToDB();
                     return;
                 case DATA_DESPAWN_ALGALON:
                     DoUpdateWorldState(WORLD_STATE_ALGALON_TIMER_ENABLED, 1);
                     DoUpdateWorldState(WORLD_STATE_ALGALON_DESPAWN_TIMER, 60);
                     m_algalonTimer = 60;
                     _events.RescheduleEvent(EVENT_UPDATE_ALGALON_TIMER, 60000);
                     SaveToDB();
                     return;
                 case DATA_ALGALON_SUMMON_STATE:
                 case DATA_ALGALON_DEFEATED:
                     DoUpdateWorldState(WORLD_STATE_ALGALON_TIMER_ENABLED, 0);
                     m_algalonTimer = (type == DATA_ALGALON_DEFEATED ? TIMER_ALGALON_DEFEATED : TIMER_ALGALON_SUMMONED);
                     _events.CancelEvent(EVENT_UPDATE_ALGALON_TIMER);
                     SaveToDB();
                     return;
                 case TYPE_ALGALON:
                     m_auiEncounter[type] = data;
                     if (GameObject* go = instance->GetGameObject(GetGuidData(GO_DOODAD_UL_SIGILDOOR_03)))
                     {
                         go->SetGoState(data != IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                         go->EnableCollision(false);
                     }
                     if (GameObject* go = instance->GetGameObject(GetGuidData(GO_DOODAD_UL_UNIVERSEFLOOR_01)))
                     {
                         go->SetGoState(data != IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                         go->EnableCollision(false);
                     }
                     if (GameObject* go = instance->GetGameObject(GetGuidData(GO_DOODAD_UL_UNIVERSEFLOOR_02)))
                     {
                         go->SetGoState(data == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                         go->EnableCollision(false);
                     }
                     if (GameObject* go = instance->GetGameObject(GetGuidData(GO_DOODAD_UL_UNIVERSEGLOBE01)))
                     {
                         go->SetGoState(data == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                         go->EnableCollision(false);
                     }
                     if (GameObject* go = instance->GetGameObject(GetGuidData(GO_DOODAD_UL_ULDUAR_TRAPDOOR_03)))
                     {
                         go->SetGoState(data == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                         go->EnableCollision(false);
                     }
                     break;
                 // Achievement
                 case DATA_DWARFAGEDDON:
                     DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_SPELL_TARGET, SPELL_DWARFAGEDDON);
                     DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_DWARFAGEDDON);
                     return;
                 case DATA_CALL_TRAM:
                     if (GameObject* MimironTram = instance->GetGameObject(m_mimironTramGUID))
                         if (StaticTransport* t = MimironTram->ToStaticTransport())
{
                             if (data == 0 && t->GetGoState() == GO_STATE_ACTIVE && t->GetPathProgress() == t->GetPauseTime())
                                 MimironTram->SetGoState(GO_STATE_READY);
                             if (data == 1 && t->GetGoState() == GO_STATE_READY && t->GetPathProgress() == 0)
                                 MimironTram->SetGoState(GO_STATE_ACTIVE);
                         }
                     break;
                 case DATA_BRANN_MEMOTESAY:
                     if (Creature* cr = instance->GetCreature(m_brannBronzebeardBaseCamp))
                     {
                         cr->TextEmote("Go to your vehicles!", nullptr, true);
                     }
                     break;
                 case DATA_BRANN_EASY_MODE:
                     ProcessEvent(nullptr, EVENT_TOWER_OF_STORM_DESTROYED);
                     ProcessEvent(nullptr, EVENT_TOWER_OF_FROST_DESTROYED);
                     ProcessEvent(nullptr, EVENT_TOWER_OF_FLAMES_DESTROYED);
                     ProcessEvent(nullptr, EVENT_TOWER_OF_LIFE_DESTROYED);
                     break;
             }
             // take care of herbs
             if (type == TYPE_FREYA && data == DONE)
             {
                 std::list<GameObject*> goList;
                 if (Creature* freya = instance->GetCreature(GetGuidData(TYPE_FREYA)))
                 {
                     freya->GetGameObjectListWithEntryInGrid(goList, 191019 /*Adder's Tongue*/, 333.0f);
                     freya->GetGameObjectListWithEntryInGrid(goList, 190176 /*Frost Lotus*/, 333.0f);
                     freya->GetGameObjectListWithEntryInGrid(goList, 190171 /*Lichbloom*/, 333.0f);
                     freya->GetGameObjectListWithEntryInGrid(goList, 190170 /*Talandra's Rose*/, 333.0f);
                     freya->GetGameObjectListWithEntryInGrid(goList, 189973 /*Goldclover*/, 333.0f);
                     for (std::list<GameObject*>::const_iterator itr = goList.begin(); itr != goList.end(); ++itr)
                         (*itr)->SetRespawnTime(7 * DAY);
                 }
             }
             if (data == DONE || type == TYPE_LEVIATHAN || type == TYPE_WATCHERS)
                 SaveToDB();
             if (type > TYPE_LEVIATHAN && type < TYPE_WATCHERS && data == IN_PROGRESS)
             {
                 Map::PlayerList const& pList = instance->GetPlayers();
                 for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                     if (Vehicle* veh = itr->GetSource()->GetVehicle())
                         veh->Dismiss();
             }
         }
References _events, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_TIMED_TYPE_SPELL_TARGET, MapRefMgr::begin(), EventMap::CancelEvent(), ObjectGuid::Clear(), DATA_ALGALON_DEFEATED, DATA_ALGALON_SUMMON_STATE, DATA_BRANN_EASY_MODE, DATA_BRANN_MEMOTESAY, DATA_CALL_TRAM, DATA_DESPAWN_ALGALON, DATA_DWARFAGEDDON, DATA_MAGE_BARRIER, DATA_UNBROKEN_ACHIEVEMENT, DATA_VEHICLE_SPAWN, DAY, DONE, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateAchievementCriteria(), InstanceScript::DoUpdateWorldState(), MapRefMgr::end(), EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, EVENT_UPDATE_ALGALON_TIMER, GAMEOBJECT_FLAGS, Map::GetCreature(), GetData(), Map::GetGameObject(), GetGuidData(), Map::GetPlayers(), GO_DOODAD_UL_SIGILDOOR_03, GO_DOODAD_UL_ULDUAR_TRAPDOOR_03, GO_DOODAD_UL_UNIVERSEFLOOR_01, GO_DOODAD_UL_UNIVERSEFLOOR_02, GO_DOODAD_UL_UNIVERSEGLOBE01, GO_FLAG_LOCKED, GO_STATE_ACTIVE, GO_STATE_READY, hmHodir, IN_PROGRESS, InstanceScript::instance, Map::LoadGrid(), m_algalonTimer, m_archivumDoorsGUID, m_assemblyDoorsGUID, m_auiEncounter, m_brannBronzebeardBaseCamp, m_difficulty, m_hodirHardmodeChest, m_keepersgateGUID, m_keepersGossipGUID, m_leviathanTowers, m_leviathanVisualTowers, m_mageBarrier, m_mimironTramGUID, m_mimironTramUsed, m_unbrokenAchievement, ProcessEvent(), EventMap::RescheduleEvent(), InstanceScript::SaveToDB(), setChestsLootable(), ShowKeeperGossip(), SpawnHodirChests(), SpawnLeviathanEncounterVehicles(), SPELL_DWARFAGEDDON, TIMER_ALGALON_DEFEATED, TIMER_ALGALON_SUMMONED, GameObject::ToStaticTransport(), TYPE_ALGALON, TYPE_ASSEMBLY, TYPE_AURIAYA, TYPE_FREYA, TYPE_HODIR, TYPE_HODIR_HM_FAIL, TYPE_IGNIS, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_RAZORSCALE, TYPE_SPAWN_HODIR_CACHE, TYPE_THORIM, TYPE_VEZAX, TYPE_WATCHERS, TYPE_XT002, TYPE_YOGGSARON, WORLD_STATE_ALGALON_DESPAWN_TIMER, and WORLD_STATE_ALGALON_TIMER_ENABLED.
Referenced by ProcessEvent(), and Update().
ShowKeeperGossip()
void instance_ulduar::instance_ulduar_InstanceMapScript::ShowKeeperGossip (uint8 type, Creature * cr, ObjectGuid guid = ObjectGuid::Empty) inline
Definition at line 431 of file instance_ulduar.cpp.
         {
             if (!cr)
             {
                 cr = instance->GetCreature(guid);
                 if (!cr)
                     return;
             }
             bool on = (GetData(type) == DONE && !(GetData(TYPE_WATCHERS) & (1 << (type - TYPE_FREYA))));
             cr->SetVisible(on);
         }
References DONE, Map::GetCreature(), GetData(), InstanceScript::instance, Unit::SetVisible(), TYPE_FREYA, and TYPE_WATCHERS.
Referenced by OnCreatureCreate(), and SetData().
SpawnHodirChests()
void instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests (int rd) inline
Definition at line 216 of file instance_ulduar.cpp.
         {
             if (Creature* cr = instance->GetCreature(m_uiHodirGUID))
             {
                 switch (rd)
                 {
                     case 0: // 10 man chest
                     {
                         if (!m_hodirNormalChest)
{
                             if (GameObject* go = cr->SummonGameObject(
                                 GO_HODIR_CHEST_NORMAL,
                                 normalChestPosition.GetPositionX(),
                                 normalChestPosition.GetPositionY(),
                                 normalChestPosition.GetPositionZ(),
                                 normalChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                                 m_hodirNormalChest = go->GetGUID();
                                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                             }
                         }
                         if (!m_hodirHardmodeChest)
{
                             if (GameObject* go = cr->SummonGameObject(
                                 GO_HODIR_CHEST_HARD,
                                 hardChestPosition.GetPositionX(),
                                 hardChestPosition.GetPositionY(),
                                 hardChestPosition.GetPositionZ(),
                                 hardChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                                 m_hodirHardmodeChest = go->GetGUID();
                                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                                 hmHodir = true;
                             }
                         }
                         break;
                     }
                     case 1: // 25 man chest
                     {
                         if (!m_hodirNormalChest)
{
                             if (GameObject* go = cr->SummonGameObject(
                                 GO_HODIR_CHEST_NORMAL_HERO,
                                 normalChestPosition.GetPositionX(),
                                 normalChestPosition.GetPositionY(),
                                 normalChestPosition.GetPositionZ(),
                                 normalChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                                 m_hodirNormalChest = go->GetGUID();
                                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                             }
                         }
                         if (!m_hodirHardmodeChest)
{
                             if (GameObject* go = cr->SummonGameObject(
                                 GO_HODIR_CHEST_HARD_HERO,
                                 hardChestPosition.GetPositionX(),
                                 hardChestPosition.GetPositionY(),
                                 hardChestPosition.GetPositionZ(),
                                 hardChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                                 m_hodirHardmodeChest = go->GetGUID();
                                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                                 hmHodir = true;
                             }
                         }
                         break;
                     }
                 }
             }
         }
References GAMEOBJECT_FLAGS, Map::GetCreature(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_NOT_SELECTABLE, GO_HODIR_CHEST_HARD, GO_HODIR_CHEST_HARD_HERO, GO_HODIR_CHEST_NORMAL, GO_HODIR_CHEST_NORMAL_HERO, hardChestPosition, hmHodir, InstanceScript::instance, m_hodirHardmodeChest, m_hodirNormalChest, m_uiHodirGUID, normalChestPosition, and WorldObject::SummonGameObject().
Referenced by SetData().
SpawnLeviathanEncounterVehicles()
void instance_ulduar::instance_ulduar_InstanceMapScript::SpawnLeviathanEncounterVehicles (uint8 mode)
Definition at line 1232 of file instance_ulduar.cpp.
 {
     if (!_leviathanVehicles.empty())
     {
         for (ObjectGuid const& guid : _leviathanVehicles)
             if (Creature* cr = instance->GetCreature(guid))
                 if (Vehicle* veh = cr->GetVehicleKit())
                     veh->Dismiss();
         _leviathanVehicles.clear();
     }
     if (mode < VEHICLE_POS_NONE)
     {
         for (uint8 i = 0; i < (instance->Is25ManRaid() ? 5 : 2); ++i)
         {
             if (TempSummon* veh = instance->SummonCreature(NPC_SALVAGED_SIEGE_ENGINE, vehiclePositions[15 * mode + i]))
             {
                 _leviathanVehicles.push_back(veh->GetGUID());
             }
             if (TempSummon* veh = instance->SummonCreature(NPC_VEHICLE_CHOPPER, vehiclePositions[15 * mode + i + 5]))
             {
                 _leviathanVehicles.push_back(veh->GetGUID());
             }
             if (TempSummon* veh = instance->SummonCreature(NPC_SALVAGED_DEMOLISHER, vehiclePositions[15 * mode + i + 10]))
             {
                 _leviathanVehicles.push_back(veh->GetGUID());
             }
         }
     }
 }
References _leviathanVehicles, Map::GetCreature(), InstanceScript::instance, Map::Is25ManRaid(), NPC_SALVAGED_DEMOLISHER, NPC_SALVAGED_SIEGE_ENGINE, NPC_VEHICLE_CHOPPER, Map::SummonCreature(), VEHICLE_POS_NONE, and vehiclePositions.
Referenced by SetData().
Update()
void instance_ulduar::instance_ulduar_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 1111 of file instance_ulduar.cpp.
         {
             if (_events.Empty())
                 return;
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case EVENT_UPDATE_ALGALON_TIMER:
                     if (m_algalonTimer == TIMER_ALGALON_DEFEATED)
                     {
                         return;
                     }
                     SaveToDB();
                     DoUpdateWorldState(WORLD_STATE_ALGALON_DESPAWN_TIMER, --m_algalonTimer);
                     if (m_algalonTimer)
                     {
                         _events.RepeatEvent(60000);
                         return;
                     }
                     SetData(DATA_ALGALON_DEFEATED, 1);
                     if (Creature* algalon = instance->GetCreature(m_uiAlgalonGUID))
                         algalon->AI()->DoAction(ACTION_DESPAWN_ALGALON);
             }
         }
References _events, ACTION_DESPAWN_ALGALON, DATA_ALGALON_DEFEATED, InstanceScript::DoUpdateWorldState(), EventMap::Empty(), EVENT_UPDATE_ALGALON_TIMER, EventMap::ExecuteEvent(), Map::GetCreature(), InstanceScript::instance, m_algalonTimer, m_uiAlgalonGUID, EventMap::RepeatEvent(), InstanceScript::SaveToDB(), SetData(), TIMER_ALGALON_DEFEATED, EventMap::Update(), and WORLD_STATE_ALGALON_DESPAWN_TIMER.
Member Data Documentation
_events
EventMap instance_ulduar::instance_ulduar_InstanceMapScript::_events
Definition at line 126 of file instance_ulduar.cpp.
Referenced by Initialize(), OnPlayerEnter(), SetData(), and Update().
_leviathanVehicles
GuidList instance_ulduar::instance_ulduar_InstanceMapScript::_leviathanVehicles
Definition at line 74 of file instance_ulduar.cpp.
Referenced by Initialize(), and SpawnLeviathanEncounterVehicles().
C_of_Ulduar_MASK
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::C_of_Ulduar_MASK
Definition at line 48 of file instance_ulduar.cpp.
Referenced by CheckAchievementCriteriaMeet(), GetSaveData(), Initialize(), Load(), and OnUnitDeath().
hardChestPosition
Position instance_ulduar::instance_ulduar_InstanceMapScript::hardChestPosition = { 2035.94600f, -202.084885f, 432.686859f, 3.164077f }
Definition at line 99 of file instance_ulduar.cpp.
Referenced by SpawnHodirChests().
hmHodir
bool instance_ulduar::instance_ulduar_InstanceMapScript::hmHodir
Definition at line 95 of file instance_ulduar.cpp.
Referenced by Initialize(), setChestsLootable(), SetData(), and SpawnHodirChests().
KologarnDoorGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::KologarnDoorGUID
Definition at line 85 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_algalonFloorGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonFloorGUID[2]
Definition at line 118 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_algalonSigilDoorGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonSigilDoorGUID[3]
Definition at line 117 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_algalonTimer
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonTimer
Definition at line 123 of file instance_ulduar.cpp.
Referenced by FillInitialWorldStates(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), OnPlayerEnter(), SetData(), and Update().
m_algalonTrapdoorGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonTrapdoorGUID
Definition at line 120 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_algalonUniverseGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonUniverseGUID
Definition at line 119 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_archivumDoorsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_archivumDoorsGUID
Definition at line 89 of file instance_ulduar.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_assemblyDoorsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_assemblyDoorsGUID
Definition at line 88 of file instance_ulduar.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_auiAssemblyGUIDs
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_auiAssemblyGUIDs[3]
Definition at line 57 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_auiEncounter
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Definition at line 47 of file instance_ulduar.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), OnUnitDeath(), and SetData().
m_brannBronzebeardAlgGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_brannBronzebeardAlgGUID
Definition at line 121 of file instance_ulduar.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and OnCreatureRemove().
m_brannBronzebeardBaseCamp
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_brannBronzebeardBaseCamp
Definition at line 122 of file instance_ulduar.cpp.
Referenced by OnCreatureCreate(), and SetData().
m_conspeedatoryAttempt
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_conspeedatoryAttempt
Definition at line 109 of file instance_ulduar.cpp.
Referenced by GetSaveData(), Initialize(), Load(), and OnUnitDeath().
m_difficulty
int instance_ulduar::instance_ulduar_InstanceMapScript::m_difficulty
Definition at line 50 of file instance_ulduar.cpp.
Referenced by instance_ulduar_InstanceMapScript(), and SetData().
m_FreyaElder
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_FreyaElder[3]
Definition at line 108 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_hodirHardmodeChest
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_hodirHardmodeChest
Definition at line 97 of file instance_ulduar.cpp.
Referenced by GetGuidData(), setChestsLootable(), SetData(), and SpawnHodirChests().
m_hodirNormalChest
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_hodirNormalChest
Definition at line 96 of file instance_ulduar.cpp.
Referenced by GetGuidData(), setChestsLootable(), and SpawnHodirChests().
m_keepersgateGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_keepersgateGUID
Definition at line 129 of file instance_ulduar.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_keepersGossipGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_keepersGossipGUID[4]
Definition at line 130 of file instance_ulduar.cpp.
Referenced by OnCreatureCreate(), and SetData().
m_leviathanDoorsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_leviathanDoorsGUID
Definition at line 69 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_leviathanTowers
bool instance_ulduar::instance_ulduar_InstanceMapScript::m_leviathanTowers[4]
Definition at line 73 of file instance_ulduar.cpp.
Referenced by GetData(), Initialize(), and SetData().
m_leviathanVisualTowers
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_leviathanVisualTowers[4][2]
Definition at line 70 of file instance_ulduar.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_lightningWalls
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_lightningWalls[2]
Definition at line 72 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_mageBarrier
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_mageBarrier
Definition at line 76 of file instance_ulduar.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and SetData().
m_MimironACUguid
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_MimironACUguid
Definition at line 105 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_MimironDoor
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_MimironDoor[3]
Definition at line 102 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_MimironLeviathanMKIIguid
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_MimironLeviathanMKIIguid
Definition at line 103 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_mimironTramGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_mimironTramGUID
Definition at line 128 of file instance_ulduar.cpp.
Referenced by OnGameObjectCreate(), OnPlayerEnter(), and SetData().
m_mimironTramUsed
bool instance_ulduar::instance_ulduar_InstanceMapScript::m_mimironTramUsed
Definition at line 127 of file instance_ulduar.cpp.
Referenced by GetData(), Initialize(), OnGameObjectCreate(), and SetData().
m_MimironVX001guid
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_MimironVX001guid
Definition at line 104 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_RazorscaleHarpoonFireStateGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_RazorscaleHarpoonFireStateGUID[4]
Definition at line 79 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_RepairSGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_RepairSGUID[2]
Definition at line 71 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_saraGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_saraGUID
Definition at line 112 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_thorimGameobjectsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_thorimGameobjectsGUID[5]
Definition at line 92 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_uiAlgalonGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiAlgalonGUID
Definition at line 66 of file instance_ulduar.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), OnPlayerEnter(), OnUnitDeath(), and Update().
m_uiAuriayaGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiAuriayaGUID
Definition at line 59 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiFreyaGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiFreyaGUID
Definition at line 63 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiHodirGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiHodirGUID
Definition at line 61 of file instance_ulduar.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SpawnHodirChests().
m_uiIgnisGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiIgnisGUID
Definition at line 54 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiKologarnGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiKologarnGUID
Definition at line 58 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiLeviathanGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiLeviathanGUID
Definition at line 53 of file instance_ulduar.cpp.
Referenced by GetGuidData(), IsEncounterInProgress(), OnCreatureCreate(), and OnUnitDeath().
m_uiMimironGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiMimironGUID
Definition at line 60 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiRazorscaleGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiRazorscaleGUID
Definition at line 55 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiThorimGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiThorimGUID
Definition at line 62 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiVezaxGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiVezaxGUID
Definition at line 64 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiXT002GUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiXT002GUID
Definition at line 56 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_uiYoggSaronGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_uiYoggSaronGUID
Definition at line 65 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_unbrokenAchievement
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_unbrokenAchievement
Definition at line 75 of file instance_ulduar.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and SetData().
m_xt002DoorsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_xt002DoorsGUID
Definition at line 82 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
m_yoggsaronBrainGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_yoggsaronBrainGUID
Definition at line 113 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
m_yoggsaronDoorsGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_yoggsaronDoorsGUID
Definition at line 114 of file instance_ulduar.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
normalChestPosition
Position instance_ulduar::instance_ulduar_InstanceMapScript::normalChestPosition = { 1967.152588f, -204.188461f, 432.686951f, 5.50957f }
Definition at line 98 of file instance_ulduar.cpp.
Referenced by SpawnHodirChests().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp