Azerotcore-wotlk: ConflagrateAuraStateDelayEvent Class Reference
ConflagrateAuraStateDelayEvent Class Reference
#include <Unit.h>
Public Member Functions
ConflagrateAuraStateDelayEvent (Unit *owner, ObjectGuid casterGUID)
bool Execute (uint64 e_time, uint32 p_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * m_owner
ObjectGuid m_casterGUID
Detailed Description
Definition at line 2714 of file Unit.h.
Constructor & Destructor Documentation
ConflagrateAuraStateDelayEvent()
ConflagrateAuraStateDelayEvent::ConflagrateAuraStateDelayEvent (Unit * owner, ObjectGuid casterGUID) inline
Definition at line 2717 of file Unit.h.
 : BasicEvent(), m_owner(owner), m_casterGUID(casterGUID) { }
Member Function Documentation
Execute()
bool ConflagrateAuraStateDelayEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
Definition at line 19503 of file Unit.cpp.
 {
     if (m_owner->IsInWorld())
         if (m_owner->GetAuraEffect(SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_WARLOCK, 0x4, 0, 0, m_casterGUID) || // immolate
                 m_owner->GetAuraEffect(SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_WARLOCK, 0, 0, 0x2, m_casterGUID)) // shadowflame
             m_owner->ModifyAuraState(AURA_STATE_CONFLAGRATE, true);
     return true;
 }
References AURA_STATE_CONFLAGRATE, Unit::GetAuraEffect(), Object::IsInWorld(), m_casterGUID, m_owner, Unit::ModifyAuraState(), SPELL_AURA_PERIODIC_DAMAGE, and SPELLFAMILY_WARLOCK.
Member Data Documentation
m_casterGUID
ObjectGuid ConflagrateAuraStateDelayEvent::m_casterGUID private
Definition at line 2722 of file Unit.h.
Referenced by Execute().
m_owner
Unit* ConflagrateAuraStateDelayEvent::m_owner private
Definition at line 2721 of file Unit.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/game/Entities/Unit/Unit.h
src/server/game/Entities/Unit/Unit.cpp