Azerotcore-wotlk: deps/libmpq/win/dirent.h File Reference
dirent.h File Reference
#include <windows.h>
#include <string.h>
#include <assert.h>
Classes
struct dirent
struct DIR
Macros
#define STRNCPY(dest, src, size) strncpy((dest),(src),(size))
Typedefs
typedef struct dirent dirent
typedef struct DIR DIR
Functions
static DIR * opendir (const char *dirname)
static struct dirent * readdir (DIR *dirp)
static int closedir (DIR *dirp)
static void rewinddir (DIR *dirp)
Macro Definition Documentation
STRNCPY
#define STRNCPY (dest, src, size) strncpy((dest),(src),(size))
Definition at line 93 of file dirent.h.
Typedef Documentation
DIR
typedef struct DIR DIR
dirent
typedef struct dirent dirent
Function Documentation
closedir()
static int closedir (DIR * dirp) static
Definition at line 186 of file dirent.h.
 {
    assert (dirp != NULL);
    /* release search handle */
    if (dirp->search_handle != INVALID_HANDLE_VALUE) {
       FindClose (dirp->search_handle);
       dirp->search_handle = INVALID_HANDLE_VALUE;
    }
    /* release directory handle */
    free (dirp);
    return 0;
 }
References assert(), NULL, and DIR::search_handle.
Referenced by G3D::FileSystem::getContents(), MMAP::getDirContents(), G3D::getFileOrDirListNormal(), and my_dir().
opendir()
static DIR * opendir (const char * dirname) static
Definition at line 102 of file dirent.h.
 {
    DIR *dirp;
    assert (dirname != NULL);
    assert (strlen (dirname) < MAX_PATH);
    /* construct new DIR structure */
    dirp = (DIR*) malloc (sizeof (struct DIR));
    if (dirp != NULL) {
       char *p;
       /* take directory name... */
       STRNCPY (dirp->patt, dirname, sizeof(dirp->patt));
       dirp->patt[MAX_PATH] = '\0';
       /* ... and append search pattern to it */
       p = strchr (dirp->patt, '\0');
       if (dirp->patt < p  &&  *(p-1) != '\\'  &&  *(p-1) != ':') {
          *p++ = '\\';
       }
       *p++ = '*';
       *p = '\0';
       /* open stream and retrieve first file */
       dirp->search_handle = FindFirstFileA (dirp->patt, &dirp->current.data);
       if (dirp->search_handle == INVALID_HANDLE_VALUE) {
          /* invalid search pattern? */
          free (dirp);
          return NULL;
       }
       /* there is an un-processed directory entry in memory now */
       dirp->cached = 1;
    }
    return dirp;
 }
References assert(), DIR::cached, DIR::current, dirent::data, NULL, DIR::patt, DIR::search_handle, and STRNCPY.
Referenced by G3D::FileSystem::getContents(), MMAP::getDirContents(), G3D::getFileOrDirListNormal(), and my_dir().
readdir()
static struct dirent * readdir (DIR * dirp) static
Definition at line 148 of file dirent.h.
 {
    assert (dirp != NULL);
    if (dirp->search_handle == INVALID_HANDLE_VALUE) {
       /* directory stream was opened/rewound incorrectly or ended normally */
       return NULL;
    }
    /* get next directory entry */
    if (dirp->cached != 0) {
       /* a valid directory entry already in memory */
       dirp->cached = 0;
    } else {
       /* read next directory entry from disk */
       if (FindNextFileA (dirp->search_handle, &dirp->current.data) == FALSE) {
          /* the very last file has been processed or an error occured */
          FindClose (dirp->search_handle);
          dirp->search_handle = INVALID_HANDLE_VALUE;
          return NULL;
       }
    }
    /* copy as a multibyte character string */
    STRNCPY ( dirp->current.d_name,
              dirp->current.data.cFileName,
              sizeof(dirp->current.d_name) );
    dirp->current.d_name[MAX_PATH] = '\0';
    return &dirp->current;
 }
References assert(), DIR::cached, DIR::current, dirent::d_name, dirent::data, FALSE, NULL, DIR::search_handle, and STRNCPY.
Referenced by G3D::FileSystem::getContents(), MMAP::getDirContents(), and G3D::getFileOrDirListNormal().
rewinddir()
static void rewinddir (DIR * dirp) static
Definition at line 209 of file dirent.h.
 {
    /* release search handle */
    if (dirp->search_handle != INVALID_HANDLE_VALUE) {
       FindClose (dirp->search_handle);
       dirp->search_handle = INVALID_HANDLE_VALUE;
    }
    /* open new search handle and retrieve first file */
    dirp->search_handle = FindFirstFileA (dirp->patt, &dirp->current.data);
    if (dirp->search_handle == INVALID_HANDLE_VALUE) {
       /* invalid search pattern? */
       free (dirp);
       return;
    }
    /* there is an un-processed directory entry in memory now */
    dirp->cached = 1;
 }
References DIR::cached, DIR::current, dirent::data, DIR::patt, and DIR::search_handle.