Azerotcore-wotlk: DoorsGuidCheck Class Reference
DoorsGuidCheck Class Reference
Public Member Functions
bool operator() (WorldObject *object) const
Detailed Description
Definition at line 540 of file boss_felmyst.cpp.
Member Function Documentation
operator()()
bool DoorsGuidCheck::operator() (WorldObject * object) const inline
Definition at line 543 of file boss_felmyst.cpp.
     {
         if (object->GetTypeId() != TYPEID_UNIT)
             return true;
         Creature* cr = object->ToCreature();
         return cr->GetSpawnId() != 54780 && cr->GetSpawnId() != 54787 && cr->GetSpawnId() != 54801;
     }
References Creature::GetSpawnId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp