Azerotcore-wotlk: VMAP::WModelAreaCallback Class Reference
VMAP::WModelAreaCallback Class Reference
Public Member Functions
WModelAreaCallback (const std::vector< GroupModel > &vals, const Vector3 &down)
void operator() (const Vector3 &point, uint32 entry)
Public Attributes
std::vector< GroupModel >::const_iterator prims
std::vector< GroupModel >::const_iterator hit
float minVol
float zDist
Vector3 zVec
Detailed Description
Definition at line 502 of file WorldModel.cpp.
Constructor & Destructor Documentation
WModelAreaCallback()
VMAP::WModelAreaCallback::WModelAreaCallback (const std::vector< GroupModel > & vals, const Vector3 & down) inline
Definition at line 505 of file WorldModel.cpp.
                                                                                   :
             prims(vals.begin()), hit(vals.end()), minVol(G3D::inf()), zDist(G3D::inf()), zVec(down) { }
Member Function Documentation
operator()()
void VMAP::WModelAreaCallback::operator() (const Vector3 & point, uint32 entry) inline
Definition at line 512 of file WorldModel.cpp.
         {
             float group_Z;
             //float pVol = prims[entry].GetBound().volume();
             //if (pVol < minVol)
             //{
             /* if (prims[entry].iBound.contains(point)) */
             if (prims[entry].IsInsideObject(point, zVec, group_Z))
             {
                 //minVol = pVol;
                 //hit = prims + entry;
                 if (group_Z < zDist)
                 {
                     zDist = group_Z;
                     hit = prims + entry;
                 }
 #ifdef VMAP_DEBUG
                 const GroupModel& gm = prims[entry];
                 printf("%10u %8X %7.3f, %7.3f, %7.3f | %7.3f, %7.3f, %7.3f | z=%f, p_z=%f\n", gm.GetWmoID(), gm.GetMogpFlags(),
                        gm.GetBound().low().x, gm.GetBound().low().y, gm.GetBound().low().z,
                        gm.GetBound().high().x, gm.GetBound().high().y, gm.GetBound().high().z, group_Z, point.z);
 #endif
             }
             //}
             //std::cout << "trying to intersect '" << prims[entry].name << "'\n";
         }
References VMAP::GroupModel::GetBound(), VMAP::GroupModel::GetMogpFlags(), VMAP::GroupModel::GetWmoID(), G3D::AABox::high(), hit, G3D::AABox::low(), prims, printf(), G3D::Vector3::x, G3D::Vector3::y, G3D::Vector3::z, zDist, and zVec.
Member Data Documentation
hit
std::vector<GroupModel>::const_iterator VMAP::WModelAreaCallback::hit
Definition at line 508 of file WorldModel.cpp.
Referenced by VMAP::WorldModel::GetLocationInfo(), VMAP::WorldModel::IntersectPoint(), and operator()().
minVol
float VMAP::WModelAreaCallback::minVol
Definition at line 509 of file WorldModel.cpp.
prims
std::vector<GroupModel>::const_iterator VMAP::WModelAreaCallback::prims
Definition at line 507 of file WorldModel.cpp.
Referenced by operator()().
zDist
float VMAP::WModelAreaCallback::zDist
Definition at line 510 of file WorldModel.cpp.
Referenced by VMAP::WorldModel::GetLocationInfo(), VMAP::WorldModel::IntersectPoint(), and operator()().
zVec
Vector3 VMAP::WModelAreaCallback::zVec
Definition at line 511 of file WorldModel.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/common/Collision/Models/WorldModel.cpp