Azerotcore-wotlk: npc_drake_dealer_hurlunk Class Reference
npc_drake_dealer_hurlunk Class Reference
Public Member Functions
npc_drake_dealer_hurlunk ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 707 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_drake_dealer_hurlunk()
npc_drake_dealer_hurlunk::npc_drake_dealer_hurlunk () inline
Definition at line 710 of file zone_shadowmoon_valley.cpp.
 : CreatureScript("npc_drake_dealer_hurlunk") { }
Member Function Documentation
OnGossipHello()
bool npc_drake_dealer_hurlunk::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 721 of file zone_shadowmoon_valley.cpp.
     {
         if (creature->IsVendor() && player->GetReputationRank(1015) == REP_EXALTED)
             AddGossipItemFor(player, GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetReputationRank(), GOSSIP_ACTION_TRADE, GOSSIP_ICON_VENDOR, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_BROWSE_GOODS, Unit::IsVendor(), REP_EXALTED, and SendGossipMenuFor().
OnGossipSelect()
bool npc_drake_dealer_hurlunk::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 712 of file zone_shadowmoon_valley.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_TRADE)
             player->GetSession()->SendListInventory(creature->GetGUID());
         return true;
     }
References ClearGossipMenuFor(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_TRADE, and WorldSession::SendListInventory().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp