Azerotcore-wotlk: deps/mysqllite/mysys/my_div.c File Reference
my_div.c File Reference
#include "mysys_priv.h"
Functions
char * my_filename (File fd)
Function Documentation
my_filename()
char* my_filename (File fd)
Definition at line 26 of file my_div.c.
 {
   DBUG_ENTER("my_filename");
   if ((uint) fd >= (uint) my_file_limit)
     DBUG_RETURN((char*) "UNKNOWN");
   if (fd >= 0 && my_file_info[fd].type != UNOPEN)
   {
     DBUG_RETURN(my_file_info[fd].name);
   }
   else
     DBUG_RETURN((char*) "UNOPENED");    /* Debug message */
 }
References DBUG_ENTER, DBUG_RETURN, my_file_info, my_file_limit, and UNOPEN.
Referenced by key_cache_read(), key_cache_write(), my_close(), my_fclose(), my_fread(), my_fwrite(), my_pread(), my_pwrite(), my_read(), my_seek(), my_sync(), my_tell(), and my_write().