Azerotcore-wotlk: achievement_quick_shave Class Reference
achievement_quick_shave Class Reference
Public Member Functions
achievement_quick_shave ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1112 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
achievement_quick_shave()
achievement_quick_shave::achievement_quick_shave () inline
Definition at line 1115 of file boss_razorscale.cpp.
 : AchievementCriteriaScript("achievement_quick_shave") {}
Member Function Documentation
OnCheck()
bool achievement_quick_shave::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 1117 of file boss_razorscale.cpp.
     {
         return target && target->GetTypeId() == TYPEID_UNIT && target->GetEntry() == NPC_RAZORSCALE && target->ToCreature()->AI()->GetData(1);
     }
References Creature::AI(), UnitAI::GetData(), Object::GetEntry(), Object::GetTypeId(), NPC_RAZORSCALE, Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp