Azerotcore-wotlk: violet_hold_trashAI Struct Reference
violet_hold_trashAI Struct Reference
Public Member Functions
violet_hold_trashAI (Creature *c)
void ClearDoorSealAura ()
void EnterCombat (Unit *who) override
void AttackStart (Unit *who) override
void JustReachedHome () override
void WaypointReached (uint32 id) override
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void CreatureStartAttackDoor ()
void EnterEvadeMode () override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
bool bAddedWP
uint32 PLoc
bool bAlt
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 255 of file violet_hold.cpp.
Constructor & Destructor Documentation
violet_hold_trashAI()
violet_hold_trashAI::violet_hold_trashAI (Creature * c) inline
Definition at line 257 of file violet_hold.cpp.
                                      : npc_escortAI(c)
     {
         pInstance = c->GetInstanceScript();
         if (pInstance)
             PLoc = pInstance->GetData(DATA_PORTAL_LOCATION);
         bAddedWP = false;
         bAlt = false;
     }
References bAddedWP, bAlt, DATA_PORTAL_LOCATION, ZoneScript::GetData(), WorldObject::GetInstanceScript(), pInstance, and PLoc.
Member Function Documentation
AttackStart()
void violet_hold_trashAI::AttackStart (Unit * who) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 287 of file violet_hold.cpp.
     {
         if (!who->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
             ScriptedAI::AttackStart(who);
     }
References ScriptedAI::AttackStart(), Object::HasFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
ClearDoorSealAura()
void violet_hold_trashAI::ClearDoorSealAura () inline
Definition at line 271 of file violet_hold.cpp.
     {
         if (pInstance)
             if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_DOOR_SEAL_GUID)))
                 c->RemoveAura(SPELL_DESTROY_DOOR_SEAL, me->GetGUID());
     }
References DATA_DOOR_SEAL_GUID, Map::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), InstanceScript::instance, ScriptedAI::me, pInstance, and SPELL_DESTROY_DOOR_SEAL.
CreatureStartAttackDoor()
void violet_hold_trashAI::CreatureStartAttackDoor () inline
Definition at line 372 of file violet_hold.cpp.
     {
         RemoveEscortState(STATE_ESCORT_ESCORTING | STATE_ESCORT_RETURNING | STATE_ESCORT_PAUSED);
         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         me->CastSpell((Unit*)nullptr, SPELL_DESTROY_DOOR_SEAL, true);
     }
References Unit::CastSpell(), ScriptedAI::me, npc_escortAI::RemoveEscortState(), Object::SetFlag(), SPELL_DESTROY_DOOR_SEAL, STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, STATE_ESCORT_RETURNING, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by JustReachedHome(), and WaypointReached().
EnterCombat()
void violet_hold_trashAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 278 of file violet_hold.cpp.
     {
         if (!who->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
         {
             me->InterruptNonMeleeSpells(false);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         }
     }
References Object::HasFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Object::RemoveFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_NOT_SELECTABLE.
EnterEvadeMode()
void violet_hold_trashAI::EnterEvadeMode () inline override virtual
Reimplemented from npc_escortAI.
Definition at line 379 of file violet_hold.cpp.
     {
         if (!HasEscortState(STATE_ESCORT_ESCORTING))
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
             me->SetHomePosition(1845.577759f + rand_norm() * 5 - 2.5f, 800.681152f + rand_norm() * 5 - 2.5f, 44.104248f, M_PI);
         }
         me->DeleteThreatList();
         me->CombatStop(true);
         if (HasEscortState(STATE_ESCORT_ESCORTING))
         {
             AddEscortState(STATE_ESCORT_RETURNING);
             ReturnToLastPoint();
         }
         else
         {
             me->GetMotionMaster()->MoveTargetedHome();
             Reset();
         }
         me->ClearUnitState(UNIT_STATE_EVADE);
     }
References npc_escortAI::AddEscortState(), Unit::ClearUnitState(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), npc_escortAI::HasEscortState(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), rand_norm(), Object::RemoveFlag(), ScriptedAI::Reset(), npc_escortAI::ReturnToLastPoint(), Creature::SetHomePosition(), STATE_ESCORT_ESCORTING, STATE_ESCORT_RETURNING, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_STATE_EVADE.
JustDied()
void violet_hold_trashAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 365 of file violet_hold.cpp.
     {
         if (pInstance)
             if (Creature* portal = ObjectAccessor::GetCreature((*me), pInstance->GetGuidData(DATA_TELEPORTATION_PORTAL_GUID)))
                 CAST_AI(npc_vh_teleportation_portal::npc_vh_teleportation_portalAI, portal->AI())->SummonedMobDied(me);
     }
References CAST_AI, DATA_TELEPORTATION_PORTAL_GUID, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ScriptedAI::me, and pInstance.
JustReachedHome()
void violet_hold_trashAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 293 of file violet_hold.cpp.
     {
         CreatureStartAttackDoor();
     }
References CreatureStartAttackDoor().
MoveInLineOfSight()
void violet_hold_trashAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 305 of file violet_hold.cpp.
     {
         ScriptedAI::MoveInLineOfSight(who);
     }
References CreatureAI::MoveInLineOfSight().
UpdateAI()
void violet_hold_trashAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Reimplemented in npc_azure_sorceror::npc_azure_sorcerorAI, npc_azure_captain::npc_azure_captainAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_binder::npc_azure_binderAI, and npc_azure_invader::npc_azure_invaderAI.
Definition at line 310 of file violet_hold.cpp.
     {
         if (!bAddedWP)
         {
             bAddedWP = true;
             switch(PLoc)
             {
                 case 0:
                     for(int i = 0; i < 6; i++)
                         AddWaypoint(i, FirstPortalTrashWPs[i][0] + irand(-1, 1), FirstPortalTrashWPs[i][1] + irand(-1, 1), FirstPortalTrashWPs[i][2] + irand(-1, 1), 0);
                     me->SetHomePosition(FirstPortalTrashWPs[5][0], FirstPortalTrashWPs[5][1], FirstPortalTrashWPs[5][2], 3.149439f);
                     break;
                 case 1:
                     bAlt = (bool)urand(0, 1);
                     if (!bAlt)
                     {
                         for(int i = 0; i < 9; i++)
                             AddWaypoint(i, SecondPortalTrashWPs1[i][0] + irand(-1, 1), SecondPortalTrashWPs1[i][1] + irand(-1, 1), SecondPortalTrashWPs1[i][2], 0);
                         me->SetHomePosition(SecondPortalTrashWPs1[8][0] + irand(-1, 1), SecondPortalTrashWPs1[8][1] + irand(-1, 1), SecondPortalTrashWPs1[8][2] + irand(-1, 1), 3.149439f);
                     }
                     else
                     {
                         for(int i = 0; i < 8; i++)
                             AddWaypoint(i, SecondPortalTrashWPs2[i][0] + irand(-1, 1), SecondPortalTrashWPs2[i][1] + irand(-1, 1), SecondPortalTrashWPs2[i][2], 0);
                         me->SetHomePosition(SecondPortalTrashWPs2[7][0], SecondPortalTrashWPs2[7][1], SecondPortalTrashWPs2[7][2], 3.149439f);
                     }
                     break;
                 case 2:
                     for(int i = 0; i < 8; i++)
                         AddWaypoint(i, ThirdPortalTrashWPs[i][0] + irand(-1, 1), ThirdPortalTrashWPs[i][1] + irand(-1, 1), ThirdPortalTrashWPs[i][2], 0);
                     me->SetHomePosition(ThirdPortalTrashWPs[7][0], ThirdPortalTrashWPs[7][1], ThirdPortalTrashWPs[7][2], 3.149439f);
                     break;
                 case 3:
                     for(int i = 0; i < 9; i++)
                         AddWaypoint(i, FourthPortalTrashWPs[i][0] + irand(-1, 1), FourthPortalTrashWPs[i][1] + irand(-1, 1), FourthPortalTrashWPs[i][2], 0);
                     me->SetHomePosition(FourthPortalTrashWPs[8][0], FourthPortalTrashWPs[8][1], FourthPortalTrashWPs[8][2], 3.149439f);
                     break;
                 case 4:
                     for(int i = 0; i < 6; i++)
                         AddWaypoint(i, FifthPortalTrashWPs[i][0] + irand(-1, 1), FifthPortalTrashWPs[i][1] + irand(-1, 1), FifthPortalTrashWPs[i][2], 0);
                     me->SetHomePosition(FifthPortalTrashWPs[5][0], FifthPortalTrashWPs[5][1], FifthPortalTrashWPs[5][2], 3.149439f);
                     break;
                 case 5:
                     for(int i = 0; i < 4; i++)
                         AddWaypoint(i, SixthPoralTrashWPs[i][0] + irand(-1, 1), SixthPoralTrashWPs[i][1] + irand(-1, 1), SixthPoralTrashWPs[i][2], 0);
                     me->SetHomePosition(SixthPoralTrashWPs[3][0], SixthPoralTrashWPs[3][1], SixthPoralTrashWPs[3][2], 3.149439f);
                     break;
             }
             SetDespawnAtEnd(false);
             Start(true, true);
         }
         npc_escortAI::UpdateAI(diff);
     }
References npc_escortAI::AddWaypoint(), bAddedWP, bAlt, FifthPortalTrashWPs, FirstPortalTrashWPs, FourthPortalTrashWPs, irand(), ScriptedAI::me, PLoc, SecondPortalTrashWPs1, SecondPortalTrashWPs2, npc_escortAI::SetDespawnAtEnd(), Creature::SetHomePosition(), SixthPoralTrashWPs, npc_escortAI::Start(), ThirdPortalTrashWPs, npc_escortAI::UpdateAI(), and urand().
Referenced by npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), and npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI().
WaypointReached()
void violet_hold_trashAI::WaypointReached (uint32 id) inline override virtual
Implements npc_escortAI.
Definition at line 298 of file violet_hold.cpp.
     {
         if (PLoc < 6)
             if (id == uint16(PLocWPCount[PLoc] - 1 - (bAlt ? 1 : 0)))
                 CreatureStartAttackDoor();
     }
References bAlt, CreatureStartAttackDoor(), PLoc, and PLocWPCount.
Member Data Documentation
bAddedWP
bool violet_hold_trashAI::bAddedWP
Definition at line 267 of file violet_hold.cpp.
Referenced by UpdateAI(), and violet_hold_trashAI().
bAlt
bool violet_hold_trashAI::bAlt
Definition at line 269 of file violet_hold.cpp.
Referenced by UpdateAI(), violet_hold_trashAI(), and WaypointReached().
pInstance
InstanceScript* violet_hold_trashAI::pInstance
Definition at line 266 of file violet_hold.cpp.
Referenced by ClearDoorSealAura(), JustDied(), and violet_hold_trashAI().
PLoc
uint32 violet_hold_trashAI::PLoc
Definition at line 268 of file violet_hold.cpp.
Referenced by UpdateAI(), violet_hold_trashAI(), and WaypointReached().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/VioletHold/violet_hold.cpp