Azerotcore-wotlk: deps/mysqllite/strings/ctype-utf8.c File Reference
ctype-utf8.c File Reference
#include <my_global.h>
#include "m_string.h"
#include "m_ctype.h"
#include <errno.h>
#include "my_uctype.h"
Macros
#define EILSEQ ENOENT
#define MY_UTF8MB3_GENERAL_CI MY_UTF8MB3 "_general_ci"
#define MY_UTF8MB3_GENERAL_CS MY_UTF8MB3 "_general_cs"
#define MY_UTF8MB3_BIN MY_UTF8MB3 "_bin"
#define MY_UTF8MB4_GENERAL_CI MY_UTF8MB4 "_general_ci"
#define MY_UTF8MB4_GENERAL_CS MY_UTF8MB4 "_general_cs"
#define MY_UTF8MB4_BIN MY_UTF8MB4 "_bin"
#define HAVE_CHARSET_utf8
#define HAVE_UNIDATA
#define MY_FILENAME_ESCAPE '@'
Functions
static void my_tosort_unicode (MY_UNICASE_INFO **uni_plane, my_wc_t *wc)
int my_wildcmp_unicode (CHARSET_INFO *cs, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many, MY_UNICASE_INFO **weights)
size_t my_strnxfrm_unicode (CHARSET_INFO *cs, uchar *dst, size_t dstlen, const uchar *src, size_t srclen)
size_t my_strnxfrm_unicode_full_bin (CHARSET_INFO *cs, uchar *dst, size_t dstlen, const uchar *src, size_t srclen)
size_t my_strnxfrmlen_unicode_full_bin (CHARSET_INFO *cs, size_t len)
static int bincmp (const uchar *s, const uchar *se, const uchar *t, const uchar *te)
static int my_utf8_uni (CHARSET_INFO *cs __attribute__((unused)), my_wc_t *pwc, const uchar *s, const uchar *e)
static int my_utf8_uni_no_range (CHARSET_INFO *cs __attribute__((unused)), my_wc_t *pwc, const uchar *s)
static int my_uni_utf8 (CHARSET_INFO *cs __attribute__((unused)), my_wc_t wc, uchar *r, uchar *e)
static int my_uni_utf8_no_range (CHARSET_INFO *cs __attribute__((unused)), my_wc_t wc, uchar *r)
static size_t my_caseup_utf8 (CHARSET_INFO *cs, char *src, size_t srclen, char *dst, size_t dstlen)
static void my_hash_sort_utf8 (CHARSET_INFO *cs, const uchar *s, size_t slen, ulong *n1, ulong *n2)
static size_t my_caseup_str_utf8 (CHARSET_INFO *cs, char *src)
static size_t my_casedn_utf8 (CHARSET_INFO *cs, char *src, size_t srclen, char *dst, size_t dstlen)
static size_t my_casedn_str_utf8 (CHARSET_INFO *cs, char *src)
static int my_strnncoll_utf8 (CHARSET_INFO *cs, const uchar *s, size_t slen, const uchar *t, size_t tlen, my_bool t_is_prefix)
static int my_strnncollsp_utf8 (CHARSET_INFO *cs, const uchar *s, size_t slen, const uchar *t, size_t tlen, my_bool diff_if_only_endspace_difference)
static int my_strcasecmp_utf8 (CHARSET_INFO *cs, const char *s, const char *t)
static int my_wildcmp_utf8 (CHARSET_INFO *cs, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
static size_t my_strnxfrmlen_utf8 (CHARSET_INFO *cs __attribute__((unused)), size_t len)
static uint my_ismbchar_utf8 (CHARSET_INFO *cs, const char *b, const char *e)
static uint my_mbcharlen_utf8 (CHARSET_INFO *cs __attribute__((unused)), uint c)
static int hexlo (int x)
static int my_mb_wc_filename (CHARSET_INFO *cs __attribute__((unused)), my_wc_t *pwc, const uchar *s, const uchar *e)
static int my_wc_mb_filename (CHARSET_INFO *cs __attribute__((unused)), my_wc_t wc, uchar *s, uchar *e)
Variables
static MY_UNICASE_INFO plane00 []
static MY_UNICASE_INFO plane01 []
static MY_UNICASE_INFO plane02 []
static MY_UNICASE_INFO plane03 []
static MY_UNICASE_INFO plane04 []
static MY_UNICASE_INFO plane05 []
static MY_UNICASE_INFO plane1E []
static MY_UNICASE_INFO plane1F []
static MY_UNICASE_INFO plane21 []
static MY_UNICASE_INFO plane24 []
static MY_UNICASE_INFO planeFF []
MY_UNICASE_INFO * my_unicase_default [256]
static MY_UNICASE_INFO turk00 []
MY_UNICASE_INFO * my_unicase_turkish [256]
static uchar ctype_utf8 []
static uchar to_lower_utf8 []
static uchar to_upper_utf8 []
static MY_COLLATION_HANDLER my_collation_ci_handler
MY_CHARSET_HANDLER my_charset_utf8_handler
CHARSET_INFO my_charset_utf8_general_ci
CHARSET_INFO my_charset_utf8_bin
static uint16 touni [5994]
static uint16 uni_0C00_05FF [1344]
static uint16 uni_1E00_1FFF [512]
static uint16 uni_2160_217F [32]
static uint16 uni_24B0_24EF [64]
static uint16 uni_FF20_FF5F [64]
static char filename_safe_char [128]
static MY_COLLATION_HANDLER my_collation_filename_handler
static MY_CHARSET_HANDLER my_charset_filename_handler
CHARSET_INFO my_charset_filename
Macro Definition Documentation
EILSEQ
#define EILSEQ ENOENT
Definition at line 27 of file ctype-utf8.c.
HAVE_CHARSET_utf8
#define HAVE_CHARSET_utf8
Definition at line 41 of file ctype-utf8.c.
HAVE_UNIDATA
#define HAVE_UNIDATA
Definition at line 45 of file ctype-utf8.c.
MY_FILENAME_ESCAPE
#define MY_FILENAME_ESCAPE '@'
Definition at line 4149 of file ctype-utf8.c.
MY_UTF8MB3_BIN
#define MY_UTF8MB3_BIN MY_UTF8MB3 "_bin"
Definition at line 33 of file ctype-utf8.c.
MY_UTF8MB3_GENERAL_CI
#define MY_UTF8MB3_GENERAL_CI MY_UTF8MB3 "_general_ci"
Definition at line 31 of file ctype-utf8.c.
MY_UTF8MB3_GENERAL_CS
#define MY_UTF8MB3_GENERAL_CS MY_UTF8MB3 "_general_cs"
Definition at line 32 of file ctype-utf8.c.
MY_UTF8MB4_BIN
#define MY_UTF8MB4_BIN MY_UTF8MB4 "_bin"
Definition at line 36 of file ctype-utf8.c.
MY_UTF8MB4_GENERAL_CI
#define MY_UTF8MB4_GENERAL_CI MY_UTF8MB4 "_general_ci"
Definition at line 34 of file ctype-utf8.c.
MY_UTF8MB4_GENERAL_CS
#define MY_UTF8MB4_GENERAL_CS MY_UTF8MB4 "_general_cs"
Definition at line 35 of file ctype-utf8.c.
Function Documentation
bincmp()
static int bincmp (const uchar * s, const uchar * se, const uchar * t, const uchar * te) inline static
Definition at line 2070 of file ctype-utf8.c.
 {
   int slen= (int) (se-s), tlen= (int) (te-t);
   int len=min(slen,tlen);
   int cmp= memcmp(s,t,len);
   return cmp ? cmp : slen-tlen;
 }
References cmp, and min.
Referenced by my_strnncoll_utf8(), and my_strnncollsp_utf8().
hexlo()
static int hexlo (int x) static
Definition at line 4104 of file ctype-utf8.c.
 {
   static char hex_lo_digit[256]=
   {
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /*  !"#$%&'()*+,-./ */
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9,-1,-1,-1,-1,-1,-1, /* 0123456789:;<=>? */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* @ABCDEFGHIJKLMNO */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* PQRSTUVWXYZ[\]^_ */
     -1,10,11,12,13,14,15,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* `abcdefghijklmno */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* pqrstuvwxyz{|}~. */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, /* ................ */
   };
   return hex_lo_digit[(unsigned int) x];
 }
References G3D::x.
Referenced by my_mb_wc_filename().
my_casedn_str_utf8()
static size_t my_casedn_str_utf8 (CHARSET_INFO * cs, char * src) static
Definition at line 2402 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int srcres, dstres;
   char *dst= src, *dst0= src;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   DBUG_ASSERT(cs->casedn_multiply == 1);
   while (*src &&
          (srcres= my_utf8_uni_no_range(cs, &wc, (uchar *) src)) > 0)
   {
     int plane= (wc>>8) & 0xFF;
     wc= uni_plane[plane] ? uni_plane[plane][wc & 0xFF].tolower : wc;
     if ((dstres= my_uni_utf8_no_range(cs, wc, (uchar*) dst)) <= 0)
       break;
     src+= srcres;
     dst+= dstres;
   }
   /*
    In rare cases lower string can be shorter than
    the original string, for example:
    "U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE"
    (which is 0xC4B0 in utf8, i.e. two bytes)
    is converted into
    "U+0069 LATIN SMALL LETTER I"
    (which is 0x69 in utf8, i.e. one byte)
    So, we need to put '\0' terminator after converting.
   */
   *dst= '\0';
   return (size_t) (dst - dst0);
 }
References charset_info_st::casedn_multiply, charset_info_st::caseinfo, DBUG_ASSERT, my_uni_utf8_no_range(), my_utf8_uni_no_range(), my_wc_t, and unicase_info_st::tolower.
my_casedn_utf8()
static size_t my_casedn_utf8 (CHARSET_INFO * cs, char * src, size_t srclen, char * dst, size_t dstlen) static
Definition at line 2379 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int srcres, dstres;
   char *srcend= src + srclen, *dstend= dst + dstlen, *dst0= dst;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   DBUG_ASSERT(src != dst || cs->casedn_multiply == 1);
   while ((src < srcend) &&
          (srcres= my_utf8_uni(cs, &wc, (uchar*) src, (uchar*)srcend)) > 0)
   {
     int plane= (wc>>8) & 0xFF;
     wc= uni_plane[plane] ? uni_plane[plane][wc & 0xFF].tolower : wc;
     if ((dstres= my_uni_utf8(cs, wc, (uchar*) dst, (uchar*) dstend)) <= 0)
       break;
     src+= srcres;
     dst+= dstres;
   }
   return (size_t) (dst - dst0);
 }
References charset_info_st::casedn_multiply, charset_info_st::caseinfo, DBUG_ASSERT, my_uni_utf8(), my_utf8_uni(), my_wc_t, and unicase_info_st::tolower.
my_caseup_str_utf8()
static size_t my_caseup_str_utf8 (CHARSET_INFO * cs, char * src) static
Definition at line 2356 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int srcres, dstres;
   char *dst= src, *dst0= src;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   DBUG_ASSERT(cs->caseup_multiply == 1);
   while (*src &&
          (srcres= my_utf8_uni_no_range(cs, &wc, (uchar *) src)) > 0)
   {
     int plane= (wc>>8) & 0xFF;
     wc= uni_plane[plane] ? uni_plane[plane][wc & 0xFF].toupper : wc;
     if ((dstres= my_uni_utf8_no_range(cs, wc, (uchar*) dst)) <= 0)
       break;
     src+= srcres;
     dst+= dstres;
   }
   *dst= '\0';
   return (size_t) (dst - dst0);
 }
References charset_info_st::caseinfo, charset_info_st::caseup_multiply, DBUG_ASSERT, my_uni_utf8_no_range(), my_utf8_uni_no_range(), my_wc_t, and unicase_info_st::toupper.
my_caseup_utf8()
static size_t my_caseup_utf8 (CHARSET_INFO * cs, char * src, size_t srclen, char * dst, size_t dstlen) static
Definition at line 2305 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int srcres, dstres;
   char *srcend= src + srclen, *dstend= dst + dstlen, *dst0= dst;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   DBUG_ASSERT(src != dst || cs->caseup_multiply == 1);
   while ((src < srcend) &&
          (srcres= my_utf8_uni(cs, &wc, (uchar *) src, (uchar*) srcend)) > 0)
   {
     int plane= (wc>>8) & 0xFF;
     wc= uni_plane[plane] ? uni_plane[plane][wc & 0xFF].toupper : wc;
     if ((dstres= my_uni_utf8(cs, wc, (uchar*) dst, (uchar*) dstend)) <= 0)
       break;
     src+= srcres;
     dst+= dstres;
   }
   return (size_t) (dst - dst0);
 }
References charset_info_st::caseinfo, charset_info_st::caseup_multiply, DBUG_ASSERT, my_uni_utf8(), my_utf8_uni(), my_wc_t, and unicase_info_st::toupper.
my_hash_sort_utf8()
static void my_hash_sort_utf8 (CHARSET_INFO * cs, const uchar * s, size_t slen, ulong * n1, ulong * n2) static
Definition at line 2328 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int res;
   const uchar *e=s+slen;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   /*
     Remove end space. We have to do this to be able to compare
     'A ' and 'A' as identical
   */
   while (e > s && e[-1] == ' ')
     e--;
   while ((s < e) && (res=my_utf8_uni(cs,&wc, (uchar *)s, (uchar*)e))>0 )
   {
     int plane = (wc>>8) & 0xFF;
     wc = uni_plane[plane] ? uni_plane[plane][wc & 0xFF].sort : wc;
     n1[0]^= (((n1[0] & 63)+n2[0])*(wc & 0xFF))+ (n1[0] << 8);
     n2[0]+=3;
     n1[0]^= (((n1[0] & 63)+n2[0])*(wc >> 8))+ (n1[0] << 8);
     n2[0]+=3;
     s+=res;
   }
 }
References charset_info_st::caseinfo, my_utf8_uni(), my_wc_t, and unicase_info_st::sort.
my_ismbchar_utf8()
static uint my_ismbchar_utf8 (CHARSET_INFO * cs, const char * b, const char * e) static
Definition at line 2706 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int  res= my_utf8_uni(cs,&wc, (const uchar*)b, (const uchar*)e);
   return (res>1) ? res : 0;
 }
References b, my_utf8_uni(), and my_wc_t.
my_mb_wc_filename()
static int my_mb_wc_filename (CHARSET_INFO *cs __attribute__(unused), my_wc_t * pwc, const uchar * s, const uchar * e) static
Definition at line 4152 of file ctype-utf8.c.
 {
   int byte1, byte2;
   if (s >= e)
     return MY_CS_TOOSMALL;
   if (*s < 128 && filename_safe_char[*s])
   {
     *pwc= *s;
     return 1;
   }
   if (*s != MY_FILENAME_ESCAPE)
     return MY_CS_ILSEQ;
   if (s + 3 > e)
     return MY_CS_TOOSMALL3;
   byte1= s[1];
   byte2= s[2];
   if (byte1 >= 0x30 && byte1 <= 0x7F &&
       byte2 >= 0x30 && byte2 <= 0x7F)
   {
     int code= (byte1 - 0x30) * 80 + byte2 - 0x30;
     if (code < 5994 && touni[code])
     {
       *pwc= touni[code];
       return 3;
     }
     if (byte1 == '@' && byte2 == '@')
     {
      *pwc= 0;
       return 3;
     }
   }
   if (s + 4 > e)
     return MY_CS_TOOSMALL4;
   if ((byte1= hexlo(byte1)) >= 0 &&
       (byte2= hexlo(byte2)) >= 0)
   {
     int byte3= hexlo(s[3]);
     int byte4= hexlo(s[4]);
     if (byte3 >=0 && byte4 >=0)
     {
       *pwc= (byte1 << 12) + (byte2 << 8) + (byte3 << 4) + byte4;
       return 5;
     }
   }
   return MY_CS_ILSEQ;
 }
References filename_safe_char, hexlo(), MY_CS_ILSEQ, MY_CS_TOOSMALL, MY_CS_TOOSMALL3, MY_CS_TOOSMALL4, MY_FILENAME_ESCAPE, and touni.
my_mbcharlen_utf8()
static uint my_mbcharlen_utf8 (CHARSET_INFO *cs __attribute__(unused), uint c) static
Definition at line 2713 of file ctype-utf8.c.
 {
   if (c < 0x80)
     return 1;
   else if (c < 0xc2)
     return 0; /* Illegal mb head */
   else if (c < 0xe0)
     return 2;
   else if (c < 0xf0)
     return 3;
 #ifdef UNICODE_32BIT
   else if (c < 0xf8)
     return 4;
   else if (c < 0xfc)
     return 5;
   else if (c < 0xfe)
     return 6;
 #endif
   return 0; /* Illegal mb head */;
 }
References mpq::c.
my_strcasecmp_utf8()
static int my_strcasecmp_utf8 (CHARSET_INFO * cs, const char * s, const char * t) static
Definition at line 2605 of file ctype-utf8.c.
 {
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   while (s[0] && t[0])
   {
     my_wc_t s_wc,t_wc;
     if ((uchar) s[0] < 128)
     {
       /*
         s[0] is between 0 and 127.
         It represents a single byte character.
         Convert it into weight according to collation.
       */
       s_wc= plane00[(uchar) s[0]].tolower;
       s++;
     }
     else
     {
       int plane, res;
       /*
         Scan a multibyte character.
         In the future it is worth to write a special version of my_utf8_uni()
         for 0-terminated strings which will not take in account length. Now
         we call the regular version of my_utf8_uni() with s+3 in the
         last argument. s+3 is enough to scan any multibyte sequence.
         Calling the regular version of my_utf8_uni is safe for 0-terminated
         strings: we will never lose the end of the string:
         If we have 0 character in the middle of a multibyte sequence,
         then my_utf8_uni will always return a negative number, so the
         loop with finish.
       */
       res= my_utf8_uni(cs,&s_wc, (const uchar*)s, (const uchar*) s + 3);
       /*
          In the case of wrong multibyte sequence we will
          call strcmp() for byte-to-byte comparison.
       */
       if (res <= 0)
         return strcmp(s, t);
       s+= res;
       /* Convert Unicode code into weight according to collation */
       plane=(s_wc>>8) & 0xFF;
       s_wc = uni_plane[plane] ? uni_plane[plane][s_wc & 0xFF].tolower : s_wc;
     }
     /* Do the same for the second string */
     if ((uchar) t[0] < 128)
     {
       /* Convert single byte character into weight */
       t_wc= plane00[(uchar) t[0]].tolower;
       t++;
     }
     else
     {
       int plane;
       int res=my_utf8_uni(cs,&t_wc, (const uchar*)t, (const uchar*) t + 3);
       if (res <= 0)
         return strcmp(s, t);
       t+= res;
       /* Convert code into weight */
       plane=(t_wc>>8) & 0xFF;
       t_wc = uni_plane[plane] ? uni_plane[plane][t_wc & 0xFF].tolower : t_wc;
     }
     /* Now we have two weights, let's compare them */
     if ( s_wc != t_wc )
       return  ((int) s_wc) - ((int) t_wc);
   }
   return ((int)(uchar)s[0]) - ((int) (uchar) t[0]);
 }
References charset_info_st::caseinfo, my_utf8_uni(), my_wc_t, plane00, and unicase_info_st::tolower.
my_strnncoll_utf8()
static int my_strnncoll_utf8 (CHARSET_INFO * cs, const uchar * s, size_t slen, const uchar * t, size_t tlen, my_bool t_is_prefix) static
Definition at line 2441 of file ctype-utf8.c.
 {
   int s_res,t_res;
   my_wc_t UNINIT_VAR(s_wc), t_wc;
   const uchar *se=s+slen;
   const uchar *te=t+tlen;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   while ( s < se && t < te )
   {
     int plane;
     s_res=my_utf8_uni(cs,&s_wc, s, se);
     t_res=my_utf8_uni(cs,&t_wc, t, te);
     if ( s_res <= 0 || t_res <= 0 )
     {
       /* Incorrect string, compare byte by byte value */
       return bincmp(s, se, t, te);
     }
     plane=(s_wc>>8) & 0xFF;
     s_wc = uni_plane[plane] ? uni_plane[plane][s_wc & 0xFF].sort : s_wc;
     plane=(t_wc>>8) & 0xFF;
     t_wc = uni_plane[plane] ? uni_plane[plane][t_wc & 0xFF].sort : t_wc;
     if ( s_wc != t_wc )
     {
       return  s_wc > t_wc ? 1 : -1;
     }
     s+=s_res;
     t+=t_res;
   }
   return (int) (t_is_prefix ? t-te : ((se-s) - (te-t)));
 }
References bincmp(), charset_info_st::caseinfo, my_utf8_uni(), my_wc_t, unicase_info_st::sort, and UNINIT_VAR.
my_strnncollsp_utf8()
static int my_strnncollsp_utf8 (CHARSET_INFO * cs, const uchar * s, size_t slen, const uchar * t, size_t tlen, my_bool diff_if_only_endspace_difference) static
Definition at line 2511 of file ctype-utf8.c.
 {
   int s_res, t_res, res;
   my_wc_t UNINIT_VAR(s_wc),t_wc;
   const uchar *se= s+slen, *te= t+tlen;
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
 #ifndef VARCHAR_WITH_DIFF_ENDSPACE_ARE_DIFFERENT_FOR_UNIQUE
   diff_if_only_endspace_difference= 0;
 #endif
   while ( s < se && t < te )
   {
     int plane;
     s_res=my_utf8_uni(cs,&s_wc, s, se);
     t_res=my_utf8_uni(cs,&t_wc, t, te);
     if ( s_res <= 0 || t_res <= 0 )
     {
       /* Incorrect string, compare byte by byte value */
       return bincmp(s, se, t, te);
     }
     plane=(s_wc>>8) & 0xFF;
     s_wc = uni_plane[plane] ? uni_plane[plane][s_wc & 0xFF].sort : s_wc;
     plane=(t_wc>>8) & 0xFF;
     t_wc = uni_plane[plane] ? uni_plane[plane][t_wc & 0xFF].sort : t_wc;
     if ( s_wc != t_wc )
     {
       return  s_wc > t_wc ? 1 : -1;
     }
     s+=s_res;
     t+=t_res;
   }
   slen= (size_t) (se-s);
   tlen= (size_t) (te-t);
   res= 0;
   if (slen != tlen)
   {
     int swap= 1;
     if (diff_if_only_endspace_difference)
       res= 1;                                   /* Assume 'a' is bigger */
     if (slen < tlen)
     {
       slen= tlen;
       s= t;
       se= te;
       swap= -1;
       res= -res;
     }
     /*
       This following loop uses the fact that in UTF-8
       all multibyte characters are greater than space,
       and all multibyte head characters are greater than
       space. It means if we meet a character greater
       than space, it always means that the longer string
       is greater. So we can reuse the same loop from the
       8bit version, without having to process full multibute
       sequences.
     */
     for ( ; s < se; s++)
     {
       if (*s != ' ')
     return (*s < ' ') ? -swap : swap;
     }
   }
   return res;
 }
References bincmp(), charset_info_st::caseinfo, my_utf8_uni(), my_wc_t, unicase_info_st::sort, swap(), and UNINIT_VAR.
my_strnxfrm_unicode()
size_t my_strnxfrm_unicode (CHARSET_INFO * cs, uchar * dst, size_t dstlen, const uchar * src, size_t srclen)
Definition at line 1905 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int res;
   uchar *de= dst + dstlen;
   uchar *de_beg= de - 1;
   const uchar *se = src + srclen;
   MY_UNICASE_INFO **uni_plane= (cs->state & MY_CS_BINSORT) ?
                                 NULL : cs->caseinfo;
   LINT_INIT(wc);
   DBUG_ASSERT(src);
   while (dst < de_beg)
   {
     if ((res= cs->cset->mb_wc(cs,&wc, src, se)) <= 0)
       break;
     src+=res;
     if (uni_plane)
       my_tosort_unicode(uni_plane, &wc);
     *dst++= (uchar) (wc >> 8);
     if (dst < de)
       *dst++= (uchar) (wc & 0xFF);
   }
   while (dst < de_beg) /* Fill the tail with keys for space character */
   {
     *dst++= 0x00;
     *dst++= 0x20;
   }
   if (dst < de)  /* Clear the last byte, if "dstlen" was an odd number */
     *dst= 0x00;
   return dstlen;
 }
References charset_info_st::caseinfo, charset_info_st::cset, DBUG_ASSERT, LINT_INIT, my_charset_handler_st::mb_wc, MY_CS_BINSORT, my_tosort_unicode(), my_wc_t, NULL, and charset_info_st::state.
my_strnxfrm_unicode_full_bin()
size_t my_strnxfrm_unicode_full_bin (CHARSET_INFO * cs, uchar * dst, size_t dstlen, const uchar * src, size_t srclen)
Definition at line 1951 of file ctype-utf8.c.
 {
   my_wc_t wc;
   uchar *de= dst + dstlen;
   uchar *de_beg= de - 2; /* The beginning of the last chunk */
   const uchar *se = src + srclen;
   LINT_INIT(wc);
   DBUG_ASSERT(src);
   DBUG_ASSERT(cs->state & MY_CS_BINSORT);
   while (dst < de_beg)
   {
     int res;
     if ((res= cs->cset->mb_wc(cs, &wc, src, se)) <= 0)
       break;
     src+= res;
     *dst++= (uchar) (wc >> 16);
     *dst++= (uchar) ((wc >> 8) & 0xFF);
     *dst++= (uchar) (wc & 0xFF);
   }
   while (dst < de_beg) /* Fill the tail with keys for space character */
   {
     *dst++= 0x00;
     *dst++= 0x00;
     *dst++= 0x20;
   }
   /* Clear the last one or two bytes, if "dstlen" was not divisible by 3 */
   if (dst < de)
   {
     *dst++= 0x00;
     if (dst < de)
       *dst= 0x00;
   }
   return dstlen;
 }
References charset_info_st::cset, DBUG_ASSERT, LINT_INIT, my_charset_handler_st::mb_wc, MY_CS_BINSORT, my_wc_t, and charset_info_st::state.
my_strnxfrmlen_unicode_full_bin()
size_t my_strnxfrmlen_unicode_full_bin (CHARSET_INFO * cs, size_t len)
Definition at line 1995 of file ctype-utf8.c.
 {
   return ((len + 3) / cs->mbmaxlen) * 3;
 }
References charset_info_st::mbmaxlen.
my_strnxfrmlen_utf8()
static size_t my_strnxfrmlen_utf8 (CHARSET_INFO *cs __attribute__(unused), size_t len) static
Definition at line 2699 of file ctype-utf8.c.
 {
   return (len * 2 + 2) / 3;
 }
my_tosort_unicode()
static void my_tosort_unicode (MY_UNICASE_INFO ** uni_plane, my_wc_t * wc) inline static
Definition at line 1724 of file ctype-utf8.c.
 {
   int page= *wc >> 8;
   if (page < 256)
   {
     if (uni_plane[page])
       *wc= uni_plane[page][*wc & 0xFF].sort;
   }
   else
   {
     *wc= MY_CS_REPLACEMENT_CHARACTER;
   }
 }
References MY_CS_REPLACEMENT_CHARACTER, and unicase_info_st::sort.
Referenced by my_strnxfrm_unicode(), and my_wildcmp_unicode().
my_uni_utf8()
static int my_uni_utf8 (CHARSET_INFO *cs __attribute__(unused), my_wc_t wc, uchar * r, uchar * e) static
Definition at line 2231 of file ctype-utf8.c.
 {
   int count;
   if (r >= e)
     return MY_CS_TOOSMALL;
   if (wc < 0x80)
     count = 1;
   else if (wc < 0x800)
     count = 2;
   else if (wc < 0x10000)
     count = 3;
 #ifdef UNICODE_32BIT
   else if (wc < 0x200000)
     count = 4;
   else if (wc < 0x4000000)
     count = 5;
   else if (wc <= 0x7fffffff)
     count = 6;
 #endif
     else return MY_CS_ILUNI;
   /*
     e is a character after the string r, not the last character of it.
     Because of it (r+count > e), not (r+count-1 >e )
    */
   if ( r+count > e )
     return MY_CS_TOOSMALLN(count);
   switch (count) {
     /* Fall through all cases!!! */
 #ifdef UNICODE_32BIT
     case 6: r[5] = (uchar) (0x80 | (wc & 0x3f)); wc = wc >> 6; wc |= 0x4000000;
     case 5: r[4] = (uchar) (0x80 | (wc & 0x3f)); wc = wc >> 6; wc |= 0x200000;
     case 4: r[3] = (uchar) (0x80 | (wc & 0x3f)); wc = wc >> 6; wc |= 0x10000;
 #endif
     case 3: r[2] = (uchar) (0x80 | (wc & 0x3f)); wc = wc >> 6; wc |= 0x800;
     case 2: r[1] = (uchar) (0x80 | (wc & 0x3f)); wc = wc >> 6; wc |= 0xc0;
     case 1: r[0] = (uchar) wc;
   }
   return count;
 }
References count(), MY_CS_ILUNI, MY_CS_TOOSMALL, and MY_CS_TOOSMALLN.
Referenced by my_casedn_utf8(), and my_caseup_utf8().
my_uni_utf8_no_range()
static int my_uni_utf8_no_range (CHARSET_INFO *cs __attribute__(unused), my_wc_t wc, uchar * r) static
Definition at line 2280 of file ctype-utf8.c.
 {
   int count;
   if (wc < 0x80)
     count= 1;
   else if (wc < 0x800)
     count= 2;
   else if (wc < 0x10000)
     count= 3;
   else
     return MY_CS_ILUNI;
   switch (count)
   {
     /* Fall through all cases!!! */
     case 3: r[2]= (uchar) (0x80 | (wc & 0x3f)); wc= wc >> 6; wc |= 0x800;
     case 2: r[1]= (uchar) (0x80 | (wc & 0x3f)); wc= wc >> 6; wc |= 0xc0;
     case 1: r[0]= (uchar) wc;
   }
   return count;
 }
References count(), and MY_CS_ILUNI.
Referenced by my_casedn_str_utf8(), and my_caseup_str_utf8().
my_utf8_uni()
static int my_utf8_uni (CHARSET_INFO *cs __attribute__(unused), my_wc_t * pwc, const uchar * s, const uchar * e) static
Definition at line 2080 of file ctype-utf8.c.
 {
   uchar c;
   if (s >= e)
     return MY_CS_TOOSMALL;
   c= s[0];
   if (c < 0x80)
   {
     *pwc = c;
     return 1;
   }
   else if (c < 0xc2)
     return MY_CS_ILSEQ;
   else if (c < 0xe0)
   {
     if (s+2 > e) /* We need 2 characters */
       return MY_CS_TOOSMALL2;
     if (!((s[1] ^ 0x80) < 0x40))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x1f) << 6) | (my_wc_t) (s[1] ^ 0x80);
     return 2;
   }
   else if (c < 0xf0)
   {
     if (s+3 > e) /* We need 3 characters */
       return MY_CS_TOOSMALL3;
     if (!((s[1] ^ 0x80) < 0x40 && (s[2] ^ 0x80) < 0x40 &&
           (c >= 0xe1 || s[1] >= 0xa0)))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x0f) << 12)   |
            ((my_wc_t) (s[1] ^ 0x80) << 6) |
             (my_wc_t) (s[2] ^ 0x80);
     return 3;
   }
 #ifdef UNICODE_32BIT
   else if (c < 0xf8 && sizeof(my_wc_t)*8 >= 32)
   {
     if (s+4 > e) /* We need 4 characters */
       return MY_CS_TOOSMALL4;
     if (!((s[1] ^ 0x80) < 0x40 &&
           (s[2] ^ 0x80) < 0x40 &&
           (s[3] ^ 0x80) < 0x40 &&
           (c >= 0xf1 || s[1] >= 0x90)))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x07) << 18)    |
            ((my_wc_t) (s[1] ^ 0x80) << 12) |
            ((my_wc_t) (s[2] ^ 0x80) << 6)  |
             (my_wc_t) (s[3] ^ 0x80);
     return 4;
   }
    else if (c < 0xfc && sizeof(my_wc_t)*8 >= 32)
   {
     if (s+5 >e) /* We need 5 characters */
       return MY_CS_TOOSMALL5;
     if (!((s[1] ^ 0x80) < 0x40 &&
           (s[2] ^ 0x80) < 0x40 &&
           (s[3] ^ 0x80) < 0x40 &&
           (s[4] ^ 0x80) < 0x40 &&
           (c >= 0xf9 || s[1] >= 0x88)))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x03) << 24) |
            ((my_wc_t) (s[1] ^ 0x80) << 18) |
            ((my_wc_t) (s[2] ^ 0x80) << 12) |
            ((my_wc_t) (s[3] ^ 0x80) << 6) |
             (my_wc_t) (s[4] ^ 0x80);
     return 5;
   }
   else if (c < 0xfe && sizeof(my_wc_t)*8 >= 32)
   {
     if ( s+6 >e ) /* We need 6 characters */
       return MY_CS_TOOSMALL6;
     if (!((s[1] ^ 0x80) < 0x40   &&
           (s[2] ^ 0x80) < 0x40   &&
           (s[3] ^ 0x80) < 0x40   &&
           (s[4] ^ 0x80) < 0x40   &&
           (s[5] ^ 0x80) < 0x40   &&
           (c >= 0xfd || s[1] >= 0x84)))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x01) << 30)
       | ((my_wc_t) (s[1] ^ 0x80) << 24)
       | ((my_wc_t) (s[2] ^ 0x80) << 18)
       | ((my_wc_t) (s[3] ^ 0x80) << 12)
       | ((my_wc_t) (s[4] ^ 0x80) << 6)
       | (my_wc_t) (s[5] ^ 0x80);
     return 6;
   }
 #endif
   return MY_CS_ILSEQ;
 }
References mpq::c, MY_CS_ILSEQ, MY_CS_TOOSMALL, MY_CS_TOOSMALL2, MY_CS_TOOSMALL3, MY_CS_TOOSMALL4, MY_CS_TOOSMALL5, MY_CS_TOOSMALL6, and my_wc_t.
Referenced by my_casedn_utf8(), my_caseup_utf8(), my_hash_sort_utf8(), my_ismbchar_utf8(), my_strcasecmp_utf8(), my_strnncoll_utf8(), and my_strnncollsp_utf8().
my_utf8_uni_no_range()
static int my_utf8_uni_no_range (CHARSET_INFO *cs __attribute__(unused), my_wc_t * pwc, const uchar * s) static
Definition at line 2190 of file ctype-utf8.c.
 {
   uchar c;
   c= s[0];
   if (c < 0x80)
   {
     *pwc = c;
     return 1;
   }
   if (c < 0xc2)
     return MY_CS_ILSEQ;
   if (c < 0xe0)
   {
     if (!((s[1] ^ 0x80) < 0x40))
       return MY_CS_ILSEQ;
     *pwc = ((my_wc_t) (c & 0x1f) << 6) | (my_wc_t) (s[1] ^ 0x80);
     return 2;
   }
   if (c < 0xf0)
   {
     if (!((s[1] ^ 0x80) < 0x40 &&
           (s[2] ^ 0x80) < 0x40 &&
           (c >= 0xe1 || s[1] >= 0xa0)))
       return MY_CS_ILSEQ;
     *pwc= ((my_wc_t) (c & 0x0f) << 12)   |
           ((my_wc_t) (s[1] ^ 0x80) << 6) |
            (my_wc_t) (s[2] ^ 0x80);
     return 3;
   }
   return MY_CS_ILSEQ;
 }
References mpq::c, MY_CS_ILSEQ, and my_wc_t.
Referenced by my_casedn_str_utf8(), and my_caseup_str_utf8().
my_wc_mb_filename()
static int my_wc_mb_filename (CHARSET_INFO *cs __attribute__(unused), my_wc_t wc, uchar * s, uchar * e) static
Definition at line 4210 of file ctype-utf8.c.
 {
   int code;
   char hex[]= "0123456789abcdef";
   if (wc < 128 && filename_safe_char[wc])
   {
     *s= (uchar) wc;
     return 1;
   }
   if (s + 3 > e)
     return MY_CS_TOOSMALL3;
   *s++= MY_FILENAME_ESCAPE;
   if ((wc >= 0x00C0 && wc <= 0x05FF && (code= uni_0C00_05FF[wc - 0x00C0])) ||
       (wc >= 0x1E00 && wc <= 0x1FFF && (code= uni_1E00_1FFF[wc - 0x1E00])) ||
       (wc >= 0x2160 && wc <= 0x217F && (code= uni_2160_217F[wc - 0x2160])) ||
       (wc >= 0x24B0 && wc <= 0x24EF && (code= uni_24B0_24EF[wc - 0x24B0])) ||
       (wc >= 0xFF20 && wc <= 0xFF5F && (code= uni_FF20_FF5F[wc - 0xFF20])))
   {
     *s++= (code / 80) + 0x30;
     *s++= (code % 80) + 0x30;
     return 3;
   }
   /* Non letter */
   if (s + 5 > e)
     return MY_CS_TOOSMALL5;
   *s++= hex[(wc >> 12) & 15];
   *s++= hex[(wc >> 8) & 15];
   *s++= hex[(wc >> 4) & 15];
   *s++= hex[(wc)      & 15];
   return 5;
 }
References filename_safe_char, hex, MY_CS_TOOSMALL3, MY_CS_TOOSMALL5, MY_FILENAME_ESCAPE, uni_0C00_05FF, uni_1E00_1FFF, uni_2160_217F, uni_24B0_24EF, and uni_FF20_FF5F.
my_wildcmp_unicode()
int my_wildcmp_unicode (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many, MY_UNICASE_INFO ** weights)
Definition at line 1749 of file ctype-utf8.c.
 {
   int result= -1;                             /* Not found, using wildcards */
   my_wc_t s_wc, w_wc;
   int scan;
   int (*mb_wc)(struct charset_info_st *, my_wc_t *,
                const uchar *, const uchar *);
   mb_wc= cs->cset->mb_wc;
   while (wildstr != wildend)
   {
     while (1)
     {
       my_bool escaped= 0;
       if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                        (const uchar*)wildend)) <= 0)
         return 1;
       if (w_wc == (my_wc_t) w_many)
       {
         result= 1;                                /* Found an anchor char */
         break;
       }
       wildstr+= scan;
       if (w_wc ==  (my_wc_t) escape && wildstr < wildend)
       {
         if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                          (const uchar*)wildend)) <= 0)
           return 1;
         wildstr+= scan;
         escaped= 1;
       }
       if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                        (const uchar*)str_end)) <= 0)
         return 1;
       str+= scan;
       if (!escaped && w_wc == (my_wc_t) w_one)
       {
         result= 1;                                /* Found an anchor char */
       }
       else
       {
         if (weights)
         {
           my_tosort_unicode(weights, &s_wc);
           my_tosort_unicode(weights, &w_wc);
         }
         if (s_wc != w_wc)
           return 1;                               /* No match */
       }
       if (wildstr == wildend)
         return (str != str_end);                  /* Match if both are at end */
     }
     if (w_wc == (my_wc_t) w_many)
     {                                             /* Found w_many */
       /* Remove any '%' and '_' from the wild search string */
       for ( ; wildstr != wildend ; )
       {
         if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                          (const uchar*)wildend)) <= 0)
           return 1;
         if (w_wc == (my_wc_t)w_many)
         {
           wildstr+= scan;
           continue;
         }
         if (w_wc == (my_wc_t)w_one)
         {
           wildstr+= scan;
           if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                            (const uchar*)str_end)) <=0)
             return 1;
           str+= scan;
           continue;
         }
         break;                                        /* Not a wild character */
       }
       if (wildstr == wildend)
         return 0;                                /* Ok if w_many is last */
       if (str == str_end)
         return -1;
       if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                        (const uchar*)wildend)) <=0)
         return 1;
       wildstr+= scan;
       if (w_wc ==  (my_wc_t)escape)
       {
         if (wildstr < wildend)
         {
           if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                            (const uchar*)wildend)) <=0)
             return 1;
           wildstr+= scan;
         }
       }
       while (1)
       {
         /* Skip until the first character from wildstr is found */
         while (str != str_end)
         {
           if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                            (const uchar*)str_end)) <=0)
             return 1;
           if (weights)
           {
             my_tosort_unicode(weights, &s_wc);
             my_tosort_unicode(weights, &w_wc);
           }
           if (s_wc == w_wc)
             break;
           str+= scan;
         }
         if (str == str_end)
           return -1;
         str+= scan;
         result= my_wildcmp_unicode(cs, str, str_end, wildstr, wildend,
                                    escape, w_one, w_many,
                                    weights);
         if (result <= 0)
           return result;
       }
     }
   }
   return (str != str_end ? 1 : 0);
 }
References charset_info_st::cset, G3D::escape(), my_charset_handler_st::mb_wc, my_tosort_unicode(), my_wc_t, and my_wildcmp_unicode().
Referenced by my_wildcmp_unicode(), and my_wildcmp_utf8().
my_wildcmp_utf8()
static int my_wildcmp_utf8 (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many) static
Definition at line 2687 of file ctype-utf8.c.
 {
   MY_UNICASE_INFO **uni_plane= cs->caseinfo;
   return my_wildcmp_unicode(cs,str,str_end,wildstr,wildend,
                             escape,w_one,w_many,uni_plane);
 }
References charset_info_st::caseinfo, G3D::escape(), and my_wildcmp_unicode().
Variable Documentation
ctype_utf8
uchar ctype_utf8[] static
Initial value:
= {
    0,
   32, 32, 32, 32, 32, 32, 32, 32, 32, 40, 40, 40, 40, 40, 32, 32,
   32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
   72, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
  132,132,132,132,132,132,132,132,132,132, 16, 16, 16, 16, 16, 16,
   16,129,129,129,129,129,129,  1,  1,  1,  1,  1,  1,  1,  1,  1,
    1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 16, 16, 16, 16, 16,
   16,130,130,130,130,130,130,  2,  2,  2,  2,  2,  2,  2,  2,  2,
    2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 16, 16, 16, 16, 32,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  0
}
Definition at line 2010 of file ctype-utf8.c.
filename_safe_char
char filename_safe_char[128] static
Initial value:
=
{
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
  0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,
  0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,
}
Definition at line 4137 of file ctype-utf8.c.
Referenced by my_mb_wc_filename(), and my_wc_mb_filename().
my_charset_filename
CHARSET_INFO my_charset_filename
Definition at line 4296 of file ctype-utf8.c.
Referenced by init_compiled_charsets().
my_charset_filename_handler
MY_CHARSET_HANDLER my_charset_filename_handler static
Initial value:
=
{
    NULL,
    my_ismbchar_utf8,
    my_mbcharlen_utf8,
    my_numchars_mb,
    my_charpos_mb,
    my_well_formed_len_mb,
    my_lengthsp_8bit,
    my_numcells_mb,
    my_mb_wc_filename,
    my_wc_mb_filename,
    my_mb_ctype_mb,
    my_caseup_str_utf8,
    my_casedn_str_utf8,
    my_caseup_utf8,
    my_casedn_utf8,
    my_snprintf_8bit,
    my_long10_to_str_8bit,
    my_longlong10_to_str_8bit,
    my_fill_8bit,
    my_strntol_8bit,
    my_strntoul_8bit,
    my_strntoll_8bit,
    my_strntoull_8bit,
    my_strntod_8bit,
    my_strtoll10_8bit,
    my_strntoull10rnd_8bit,
    my_scan_8bit
}
Definition at line 4263 of file ctype-utf8.c.
my_charset_utf8_bin
CHARSET_INFO my_charset_utf8_bin
Definition at line 2817 of file ctype-utf8.c.
Referenced by init_compiled_charsets().
my_charset_utf8_general_ci
CHARSET_INFO my_charset_utf8_general_ci
Definition at line 2784 of file ctype-utf8.c.
Referenced by init_compiled_charsets(), my_error(), and my_printf_error().
my_charset_utf8_handler
MY_CHARSET_HANDLER my_charset_utf8_handler
Initial value:
=
{
    NULL,
    my_ismbchar_utf8,
    my_mbcharlen_utf8,
    my_numchars_mb,
    my_charpos_mb,
    my_well_formed_len_mb,
    my_lengthsp_8bit,
    my_numcells_mb,
    my_utf8_uni,
    my_uni_utf8,
    my_mb_ctype_mb,
    my_caseup_str_utf8,
    my_casedn_str_utf8,
    my_caseup_utf8,
    my_casedn_utf8,
    my_snprintf_8bit,
    my_long10_to_str_8bit,
    my_longlong10_to_str_8bit,
    my_fill_8bit,
    my_strntol_8bit,
    my_strntoul_8bit,
    my_strntoll_8bit,
    my_strntoull_8bit,
    my_strntod_8bit,
    my_strtoll10_8bit,
    my_strntoull10rnd_8bit,
    my_scan_8bit
}
Definition at line 2751 of file ctype-utf8.c.
my_collation_ci_handler
MY_COLLATION_HANDLER my_collation_ci_handler static
Initial value:
=
{
    NULL,
    my_strnncoll_utf8,
    my_strnncollsp_utf8,
    my_strnxfrm_unicode,
    my_strnxfrmlen_utf8,
    my_like_range_mb,
    my_wildcmp_utf8,
    my_strcasecmp_utf8,
    my_instr_mb,
    my_hash_sort_utf8,
    my_propagate_complex
}
Definition at line 2736 of file ctype-utf8.c.
my_collation_filename_handler
MY_COLLATION_HANDLER my_collation_filename_handler static
Initial value:
=
{
    NULL,
    my_strnncoll_utf8,
    my_strnncollsp_utf8,
    my_strnxfrm_unicode,
    my_strnxfrmlen_utf8,
    my_like_range_mb,
    my_wildcmp_utf8,
    my_strcasecmp_utf8,
    my_instr_mb,
    my_hash_sort_utf8,
    my_propagate_complex
}
Definition at line 4248 of file ctype-utf8.c.
my_unicase_default
MY_UNICASE_INFO* my_unicase_default[256]
Definition at line 1507 of file ctype-utf8.c.
my_unicase_turkish
MY_UNICASE_INFO* my_unicase_turkish[256]
Definition at line 1686 of file ctype-utf8.c.
plane00
MY_UNICASE_INFO plane00[] static
Definition at line 64 of file ctype-utf8.c.
Referenced by my_strcasecmp_utf8().
plane01
MY_UNICASE_INFO plane01[] static
Definition at line 197 of file ctype-utf8.c.
plane02
MY_UNICASE_INFO plane02[] static
Definition at line 328 of file ctype-utf8.c.
plane03
MY_UNICASE_INFO plane03[] static
Definition at line 459 of file ctype-utf8.c.
plane04
MY_UNICASE_INFO plane04[] static
Definition at line 590 of file ctype-utf8.c.
plane05
MY_UNICASE_INFO plane05[] static
Definition at line 721 of file ctype-utf8.c.
plane1E
MY_UNICASE_INFO plane1E[] static
Definition at line 852 of file ctype-utf8.c.
plane1F
MY_UNICASE_INFO plane1F[] static
Definition at line 983 of file ctype-utf8.c.
plane21
MY_UNICASE_INFO plane21[] static
Definition at line 1114 of file ctype-utf8.c.
plane24
MY_UNICASE_INFO plane24[] static
Definition at line 1245 of file ctype-utf8.c.
planeFF
MY_UNICASE_INFO planeFF[] static
Definition at line 1376 of file ctype-utf8.c.
to_lower_utf8
uchar to_lower_utf8[] static
Initial value:
= {
    0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
   16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
   32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
   48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
   64, 97, 98, 99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122, 91, 92, 93, 94, 95,
   96, 97, 98, 99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
  224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
  240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255
}
Definition at line 2032 of file ctype-utf8.c.
to_upper_utf8
uchar to_upper_utf8[] static
Initial value:
= {
    0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
   16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
   32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
   48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
   64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
   80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
   96, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
   80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
  224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
  240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255
}
Definition at line 2051 of file ctype-utf8.c.
touni
uint16 touni[5994] static
Definition at line 3058 of file ctype-utf8.c.
Referenced by my_mb_wc_filename().
turk00
MY_UNICASE_INFO turk00[] static
Definition at line 1552 of file ctype-utf8.c.
uni_0C00_05FF
uint16 uni_0C00_05FF[1344] static
Definition at line 3814 of file ctype-utf8.c.
Referenced by my_wc_mb_filename().
uni_1E00_1FFF
uint16 uni_1E00_1FFF[512] static
Definition at line 3988 of file ctype-utf8.c.
Referenced by my_wc_mb_filename().
uni_2160_217F
uint16 uni_2160_217F[32] static
Initial value:
=
{
  0x0739,0x0789,0x07D9,0x0829,0x0879,0x08C9,0x0919,0x0969,
  0x09B9,0x0A09,0x0A59,0x0AA9,0x0AF9,0x0B49,0x0B99,0x0BE9,
  0x1139,0x1189,0x11D9,0x1229,0x1279,0x12C9,0x1319,0x1369,
  0x13B9,0x1409,0x1459,0x14A9,0x14F9,0x1549,0x1599,0x15E9
}
Definition at line 4058 of file ctype-utf8.c.
Referenced by my_wc_mb_filename().
uni_24B0_24EF
uint16 uni_24B0_24EF[64] static
Initial value:
=
{
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0511,0x0512,
  0x0513,0x0514,0x0515,0x0516,0x0517,0x0518,0x0519,0x051A,
  0x051B,0x051C,0x051D,0x051E,0x051F,0x0520,0x0521,0x0522,
  0x0523,0x0524,0x0525,0x0526,0x0527,0x0528,0x0529,0x052A,
  0x0531,0x0532,0x0533,0x0534,0x0535,0x0536,0x0537,0x0538,
  0x0539,0x053A,0x053B,0x053C,0x053D,0x053E,0x053F,0x0540,
  0x0541,0x0542,0x0543,0x0544,0x0545,0x0546,0x0547,0x0548,
  0x0549,0x054A,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
}
Definition at line 4068 of file ctype-utf8.c.
Referenced by my_wc_mb_filename().
uni_FF20_FF5F
uint16 uni_FF20_FF5F[64] static
Initial value:
=
{
  0x0000,0x0560,0x05B0,0x0600,0x0650,0x06A0,0x06F0,0x0740,
  0x0790,0x07E0,0x0830,0x0880,0x08D0,0x0920,0x0970,0x09C0,
  0x0A10,0x0A60,0x0AB0,0x0B00,0x0B50,0x0BA0,0x0BF0,0x0C40,
  0x0C90,0x0CE0,0x0D30,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0F60,0x0FB0,0x1000,0x1050,0x10A0,0x10F0,0x1140,
  0x1190,0x11E0,0x1230,0x1280,0x12D0,0x1320,0x1370,0x13C0,
  0x1410,0x1460,0x14B0,0x1500,0x1550,0x15A0,0x15F0,0x1640,
  0x1690,0x16E0,0x1730,0x0000,0x0000,0x0000,0x0000,0x0000
}
Definition at line 4082 of file ctype-utf8.c.
Referenced by my_wc_mb_filename().