Azerotcore-wotlk: npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI Struct Reference
npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI Struct Reference
Public Member Functions
npc_bh_thalorien_dawnseekerAI (Creature *c)
void Reset () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void MovementInform (uint32 type, uint32 id) override
void EnterEvadeMode () override
void SetData (uint32 type, uint32 id) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
ObjectGuid morlenGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 128 of file zone_isle_of_queldanas.cpp.
Constructor & Destructor Documentation
npc_bh_thalorien_dawnseekerAI()
npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::npc_bh_thalorien_dawnseekerAI (Creature * c) inline
Definition at line 130 of file zone_isle_of_queldanas.cpp.
                                                    : ScriptedAI(c), summons(me)
         {
         }
Member Function Documentation
DamageTaken()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 212 of file zone_isle_of_queldanas.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 me->setActive(false);
                 EnterEvadeMode();
             }
         }
References EnterEvadeMode(), Unit::GetHealth(), ScriptedAI::me, and WorldObject::setActive().
EnterEvadeMode()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 428 of file zone_isle_of_queldanas.cpp.
         {
             if (me->isActiveObject())
                 return;
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), WorldObject::isActiveObject(), and ScriptedAI::me.
Referenced by DamageTaken(), and UpdateAI().
JustSummoned()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 172 of file zone_isle_of_queldanas.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
MovementInform()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 422 of file zone_isle_of_queldanas.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == EVENT_CHARGE)
                 events.ScheduleEvent(EVENT_SET_FACING, 0);
         }
References EVENT_CHARGE, EVENT_SET_FACING, and POINT_MOTION_TYPE.
Reset()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 139 of file zone_isle_of_queldanas.cpp.
         {
             me->SetVisible(false);
             me->SetRegeneratingHealth(true);
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             me->SetStandState(UNIT_STAND_STATE_STAND);
             playerGUID.Clear();
             morlenGUID.Clear();
             summons.DespawnAll();
             if (Creature* c = me->FindNearestCreature(NPC_THALORIEN_REMAINS, 100.0f, true))
                 c->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             events.Reset();
             events.ScheduleEvent(EVENT_CHECK_PLAYER, 5000);
             events.ScheduleEvent(EVENT_SUMMON_SOLDIERS, 0);
             events.ScheduleEvent(EVENT_TALK_INTRO_0, 3000);
             events.ScheduleEvent(EVENT_TALK_INTRO_1, 8000);
             events.ScheduleEvent(EVENT_TALK_INTRO_2, 15000);
             events.ScheduleEvent(EVENT_TALK_INTRO_3, 22000);
             events.ScheduleEvent(EVENT_SALUTE, 24000);
             events.ScheduleEvent(EVENT_SOLDIERS_RUN_AWAY, 30000);
             events.ScheduleEvent(EVENT_GO_FIGHTPOINT, 31000);
             events.ScheduleEvent(EVENT_TALK_SPAWN_0, 38000);
             events.ScheduleEvent(EVENT_SUMMON_MORLEN, 44000);
             events.ScheduleEvent(EVENT_TALK_SPAWN_1, 47000);
             events.ScheduleEvent(EVENT_TALK_MORLEN_0, 52000);
             events.ScheduleEvent(EVENT_TALK_MORLEN_1, 58000);
             events.ScheduleEvent(EVENT_SPAWN_WAVE_1, 61000);
             events.ScheduleEvent(EVENT_SPELL_BLADESTORM, urand(6000, 15000));
             events.ScheduleEvent(EVENT_SPELL_MORTAL_STRIKE, urand(3000, 7000));
             events.ScheduleEvent(EVENT_SPELL_HEROIC_STRIKE, urand(4000, 10000));
         }
References ObjectGuid::Clear(), SummonList::DespawnAll(), EMOTE_ONESHOT_NONE, EVENT_CHECK_PLAYER, EVENT_GO_FIGHTPOINT, EVENT_SALUTE, EVENT_SOLDIERS_RUN_AWAY, EVENT_SPAWN_WAVE_1, EVENT_SPELL_BLADESTORM, EVENT_SPELL_HEROIC_STRIKE, EVENT_SPELL_MORTAL_STRIKE, EVENT_SUMMON_MORLEN, EVENT_SUMMON_SOLDIERS, EVENT_TALK_INTRO_0, EVENT_TALK_INTRO_1, EVENT_TALK_INTRO_2, EVENT_TALK_INTRO_3, EVENT_TALK_MORLEN_0, EVENT_TALK_MORLEN_1, EVENT_TALK_SPAWN_0, EVENT_TALK_SPAWN_1, WorldObject::FindNearestCreature(), ScriptedAI::me, morlenGUID, NPC_THALORIEN_REMAINS, playerGUID, Creature::SetRegeneratingHealth(), Unit::SetStandState(), Object::SetUInt32Value(), Unit::SetVisible(), summons, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, UNIT_STAND_STATE_STAND, and urand().
SetData()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData (uint32 type, uint32 id) inline override virtual
Reimplemented from UnitAI.
Definition at line 435 of file zone_isle_of_queldanas.cpp.
         {
             if (type == 1 && id == 1 && !me->isActiveObject())
                 if (Player* p = me->SelectNearestPlayer(50.0f))
                 {
                     me->SetVisible(true);
                     me->SetRegeneratingHealth(false);
                     me->setActive(true);
                     playerGUID = p->GetGUID();
                 }
         }
References WorldObject::isActiveObject(), ScriptedAI::me, playerGUID, WorldObject::SelectNearestPlayer(), WorldObject::setActive(), Creature::SetRegeneratingHealth(), and Unit::SetVisible().
SummonedCreatureDespawn()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 177 of file zone_isle_of_queldanas.cpp.
         {
             summons.Despawn(summon);
             if (summon->GetEntry() != NPC_SUNWELL_DEFENDER && me->isActiveObject())
             {
                 if (summon->GetEntry() == NPC_MORLEN_COLDGRIP)
                 {
                     me->RemoveAurasDueToSpell(67541);
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                     me->GetMotionMaster()->MoveCharge(11779.30f, -7065.43f, 24.92f, me->GetSpeed(MOVE_RUN), EVENT_CHARGE);
                     events.ScheduleEvent(EVENT_OUTRO_0, 0);
                     events.ScheduleEvent(EVENT_OUTRO_1, 5000);
                     events.ScheduleEvent(EVENT_OUTRO_2, 12000);
                     events.ScheduleEvent(EVENT_OUTRO_3, 19000);
                 }
                 else if (summons.size() == 1)
                 {
                     me->RemoveAurasDueToSpell(67541);
                     me->GetMotionMaster()->MoveCharge(11779.30f, -7065.43f, 24.92f, me->GetSpeed(MOVE_RUN), EVENT_CHARGE);
                     switch(summon->GetEntry())
                     {
                         case NPC_SCOURGE_ZOMBIE:
                             events.ScheduleEvent(EVENT_SPAWN_WAVE_2, 3000);
                             break;
                         case NPC_GHOUL_INVADER:
                             events.ScheduleEvent(EVENT_SPAWN_WAVE_3, 3000);
                             break;
                         case NPC_CRYPT_RAIDER:
                             events.ScheduleEvent(EVENT_SUMMONS_ATTACK, 3000);
                             break;
                     }
                 }
             }
         }
References SummonList::Despawn(), EMOTE_ONESHOT_NONE, EVENT_CHARGE, EVENT_OUTRO_0, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_SPAWN_WAVE_2, EVENT_SPAWN_WAVE_3, EVENT_SUMMONS_ATTACK, Object::GetEntry(), Unit::GetMotionMaster(), Unit::GetSpeed(), WorldObject::isActiveObject(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveCharge(), NPC_CRYPT_RAIDER, NPC_GHOUL_INVADER, NPC_MORLEN_COLDGRIP, NPC_SCOURGE_ZOMBIE, NPC_SUNWELL_DEFENDER, Unit::RemoveAurasDueToSpell(), Object::SetUInt32Value(), SummonList::size(), summons, and UNIT_NPC_EMOTESTATE.
UpdateAI()
void npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 222 of file zone_isle_of_queldanas.cpp.
         {
             if (!me->isActiveObject())
                 return;
             UpdateVictim();
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (uint32 evId = events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_CHECK_PLAYER:
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                         if (p->GetExactDist(me) <= 50.0f)
{
                             events.RepeatEvent(5000);
                             break;
                         }
                     me->setActive(false);
                     EnterEvadeMode();
                     return;
                 case EVENT_SUMMON_SOLDIERS:
                     for (uint8 i = 0; i < SUNWELL_DEFENDER_NUM; ++i)
                         me->SummonCreature(NPC_SUNWELL_DEFENDER, SunwellDefenderPos[i], TEMPSUMMON_TIMED_DESPAWN, 33000 + (i / 5) * 5000);
                     break;
                 case EVENT_TALK_INTRO_0:
                 case EVENT_TALK_INTRO_1:
                 case EVENT_TALK_INTRO_2:
                 case EVENT_TALK_INTRO_3:
                     Talk(SAY_INTRO_0 + (evId - EVENT_TALK_INTRO_0));
                     break;
                 case EVENT_SALUTE:
                     me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                     for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                         if (Creature* c = ObjectAccessor::GetCreature(*me, *itr))
                             c->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                     break;
                 case EVENT_SOLDIERS_RUN_AWAY:
                     {
                         uint8 count = 0;
                         for (SummonList::iterator itr = summons.begin(); itr != summons.end();)
{
                             ++count;
                             if (Creature* c = ObjectAccessor::GetCreature(*me, *itr))
{
                                 c->SetWalk(false);
                                 c->GetMotionMaster()->MovePoint(0, 11863.35f, -7073.44f, 27.40f);
                             }
                             SummonList::iterator itr2 = itr++;
                             summons.erase(itr2);
                             if (count >= 5)
{
                                 if (!summons.empty())
{
                                     events.RepeatEvent(5000);
                                     return;
                                 }
                                 else
{
                                     return;
                                 }
                             }
                         }
                     }
                     break;
                 case EVENT_GO_FIGHTPOINT:
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePoint(0, 11779.30f, -7065.43f, 24.92f);
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                     break;
                 case EVENT_TALK_SPAWN_0:
                 case EVENT_TALK_SPAWN_1:
                     Talk(SAY_SPAWN_0 + (evId - EVENT_TALK_SPAWN_0));
                     break;
                 case EVENT_SUMMON_MORLEN:
                     if (Creature* c = me->SummonCreature(NPC_MORLEN_COLDGRIP, 11766.70f, -7050.57f, 25.17f, 5.56f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
                         morlenGUID = c->GetGUID();
                     break;
                 case EVENT_TALK_MORLEN_0:
                 case EVENT_TALK_MORLEN_1:
                     if (Creature* c = ObjectAccessor::GetCreature(*me, morlenGUID))
                         c->AI()->Talk(SAY_MORLEN_0 + (evId - EVENT_TALK_MORLEN_0));
                     break;
                 case EVENT_SPAWN_WAVE_1:
                 case EVENT_SPAWN_WAVE_2:
                 case EVENT_SPAWN_WAVE_3:
                     if (Creature* c = ObjectAccessor::GetCreature(*me, morlenGUID))
                     {
                         c->AI()->Talk(SAY_MORLEN_1 + (evId - EVENT_SPAWN_WAVE_1));
                         switch (evId)
{
                             // emerge cast tr false 66947
                             case EVENT_SPAWN_WAVE_1:
{
                                     Position spawnPos = c->GetPosition();
                                     spawnPos.m_orientation = 5.80f;
                                     spawnPos.m_positionX += 5.0f * cos(4.5f);
                                     spawnPos.m_positionY += 5.0f * sin(4.5f);
                                     for (uint8 i = 0; i < 5; ++i)
                                         if (me->SummonCreature(NPC_SCOURGE_ZOMBIE, spawnPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000))
{
                                             spawnPos.m_positionX += 2.5f * cos(4.5f);
                                             spawnPos.m_positionY += 2.5f * sin(4.5f);
                                         }
                                 }
                                 break;
                             case EVENT_SPAWN_WAVE_2:
{
                                     Position spawnPos = c->GetPosition();
                                     spawnPos.m_orientation = 5.80f;
                                     spawnPos.m_positionX += 7.0f * cos(4.0f);
                                     spawnPos.m_positionY += 7.0f * sin(4.0f);
                                     for (uint8 i = 0; i < 3; ++i)
                                         if (Creature* s = me->SummonCreature(NPC_GHOUL_INVADER, spawnPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000))
{
                                             s->CastSpell(s, 66947, false); // emerge effect
                                             spawnPos.m_positionX += 4.0f * cos(4.5f);
                                             spawnPos.m_positionY += 4.0f * sin(4.5f);
                                         }
                                 }
                                 break;
                             case EVENT_SPAWN_WAVE_3:
{
                                     Position spawnPos = c->GetPosition();
                                     spawnPos.m_orientation = 5.80f;
                                     spawnPos.m_positionX += 8.0f * cos(4.0f);
                                     spawnPos.m_positionY += 8.0f * sin(4.0f);
                                     for (uint8 i = 0; i < 3; ++i)
                                         if (Creature* s = me->SummonCreature(NPC_CRYPT_RAIDER, spawnPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 2000))
{
                                             s->CastSpell(s, 66947, false); // emerge effect
                                             spawnPos.m_positionX += 4.0f * cos(4.5f);
                                             spawnPos.m_positionY += 4.0f * sin(4.5f);
                                         }
                                 }
                                 break;
                         }
                     }
                     events.ScheduleEvent(EVENT_SUMMONS_ATTACK, 3000);
                     break;
                 case EVENT_SUMMONS_ATTACK:
                     for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                         if (Creature* c = ObjectAccessor::GetCreature(*me, *itr))
{
                             if (c->GetEntry() == NPC_MORLEN_COLDGRIP && summons.size() != 1)
                                 continue;
                             else
                                 c->AI()->Talk(SAY_MORLEN_4);
                             c->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             c->AI()->AttackStart(me);
                         }
                     break;
                 case EVENT_OUTRO_0:
                 case EVENT_OUTRO_1:
                 case EVENT_OUTRO_2:
                 case EVENT_OUTRO_3:
                     Talk(SAY_OUTRO_0 + (evId - EVENT_OUTRO_0));
                     if (evId == EVENT_OUTRO_3)
                         events.ScheduleEvent(EVENT_OUTRO_KNEEL, 6000);
                     break;
                 case EVENT_OUTRO_KNEEL:
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                         p->KilledMonsterCredit(NPC_THALORIEN_KILL_CREDIT);
                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                     events.ScheduleEvent(EVENT_DISAPPEAR, 6000);
                     break;
                 case EVENT_DISAPPEAR:
                     me->SetVisible(false);
                     me->setActive(false);
                     EnterEvadeMode();
                     break;
                 case EVENT_SET_FACING:
                     me->SetFacingTo(2.45f);
                     break;
                 case EVENT_SPELL_BLADESTORM:
                     if (me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim()))
                         me->CastSpell(me->GetVictim(), 67541, false);
                     events.RepeatEvent(urand(25000, 35000));
                     break;
                 case EVENT_SPELL_MORTAL_STRIKE:
                     if (me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim()))
                         me->CastSpell(me->GetVictim(), 67542, false);
                     events.RepeatEvent(urand(7000, 12000));
                     break;
                 case EVENT_SPELL_HEROIC_STRIKE:
                     if (me->GetVictim() && me->IsWithinMeleeRange(me->GetVictim()))
                         me->CastSpell(me->GetVictim(), 57846, false);
                     events.RepeatEvent(urand(5000, 10000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References SummonList::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_SALUTE, EMOTE_STATE_READY2H, SummonList::empty(), SummonList::end(), EnterEvadeMode(), SummonList::erase(), EVENT_CHECK_PLAYER, EVENT_DISAPPEAR, EVENT_GO_FIGHTPOINT, EVENT_OUTRO_0, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_OUTRO_KNEEL, EVENT_SALUTE, EVENT_SET_FACING, EVENT_SOLDIERS_RUN_AWAY, EVENT_SPAWN_WAVE_1, EVENT_SPAWN_WAVE_2, EVENT_SPAWN_WAVE_3, EVENT_SPELL_BLADESTORM, EVENT_SPELL_HEROIC_STRIKE, EVENT_SPELL_MORTAL_STRIKE, EVENT_SUMMON_MORLEN, EVENT_SUMMON_SOLDIERS, EVENT_SUMMONS_ATTACK, EVENT_TALK_INTRO_0, EVENT_TALK_INTRO_1, EVENT_TALK_INTRO_2, EVENT_TALK_INTRO_3, EVENT_TALK_MORLEN_0, EVENT_TALK_MORLEN_1, EVENT_TALK_SPAWN_0, EVENT_TALK_SPAWN_1, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPosition(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), WorldObject::isActiveObject(), Unit::IsWithinMeleeRange(), Position::m_orientation, Position::m_positionX, Position::m_positionY, ScriptedAI::me, morlenGUID, MotionMaster::MovePoint(), NPC_CRYPT_RAIDER, NPC_GHOUL_INVADER, NPC_MORLEN_COLDGRIP, NPC_SCOURGE_ZOMBIE, NPC_SUNWELL_DEFENDER, NPC_THALORIEN_KILL_CREDIT, playerGUID, SAY_INTRO_0, SAY_MORLEN_0, SAY_MORLEN_1, SAY_MORLEN_4, SAY_OUTRO_0, SAY_SPAWN_0, WorldObject::setActive(), Unit::SetFacingTo(), Unit::SetStandState(), Object::SetUInt32Value(), Unit::SetVisible(), Creature::SetWalk(), SummonList::size(), WorldObject::SummonCreature(), summons, SUNWELL_DEFENDER_NUM, SunwellDefenderPos, CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_EMOTESTATE, UNIT_STAND_STATE_KNEEL, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::events
Definition at line 134 of file zone_isle_of_queldanas.cpp.
morlenGUID
ObjectGuid npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::morlenGUID
Definition at line 137 of file zone_isle_of_queldanas.cpp.
Referenced by Reset(), and UpdateAI().
playerGUID
ObjectGuid npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::playerGUID
Definition at line 136 of file zone_isle_of_queldanas.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
summons
SummonList npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::summons
Definition at line 135 of file zone_isle_of_queldanas.cpp.
Referenced by JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp