Azerotcore-wotlk: DynamicObject Class Reference
DynamicObject Class Reference
#include <DynamicObject.h>
Public Member Functions
DynamicObject (bool isWorldObject)
~DynamicObject () override
void AddToWorld () override
void RemoveFromWorld () override
void CleanupsBeforeDelete (bool finalCleanup=true) override
bool CreateDynamicObject (ObjectGuid::LowType guidlow, Unit *caster, uint32 spellId, Position const &pos, float radius, DynamicObjectType type)
void Update (uint32 p_time) override
void Remove ()
void SetDuration (int32 newDuration)
int32 GetDuration () const
void Delay (int32 delaytime)
void SetAura (Aura *aura)
void RemoveAura ()
void SetCasterViewpoint ()
void RemoveCasterViewpoint ()
Unit * GetCaster () const
void BindToCaster ()
void UnbindFromCaster ()
uint32 GetSpellId () const
ObjectGuid GetCasterGUID () const
float GetRadius () const
bool IsViewpoint () const
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
virtual std::string const & GetNameForLocaleIdx (LocaleConstant) const
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
virtual uint8 getLevelForTarget (WorldObject const *) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< DynamicObject >
bool IsInGrid () const
void AddToGrid (GridRefMgr< DynamicObject > &m)
void RemoveFromGrid ()
Protected Attributes
Aura * _aura
Aura * _removedAura
Unit * _caster
int32 _duration
bool _isViewpoint
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Additional Inherited Members
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
virtual bool IsAlwaysVisibleFor (WorldObject const *) const
virtual bool IsInvisibleDueToDespawn () const
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Detailed Description
Definition at line 34 of file DynamicObject.h.
Constructor & Destructor Documentation
DynamicObject()
DynamicObject::DynamicObject (bool isWorldObject)
Definition at line 27 of file DynamicObject.cpp.
                                                : WorldObject(isWorldObject), MovableMapObject(),
     _aura(nullptr), _removedAura(nullptr), _caster(nullptr), _duration(0), _isViewpoint(false)
 {
     m_objectType |= TYPEMASK_DYNAMICOBJECT;
     m_objectTypeId = TYPEID_DYNAMICOBJECT;
     m_updateFlag = (UPDATEFLAG_LOWGUID | UPDATEFLAG_STATIONARY_POSITION | UPDATEFLAG_POSITION);
     m_valuesCount = DYNAMICOBJECT_END;
 }
References DYNAMICOBJECT_END, Object::m_objectType, Object::m_objectTypeId, Object::m_updateFlag, Object::m_valuesCount, TYPEID_DYNAMICOBJECT, TYPEMASK_DYNAMICOBJECT, UPDATEFLAG_LOWGUID, UPDATEFLAG_POSITION, and UPDATEFLAG_STATIONARY_POSITION.
~DynamicObject()
DynamicObject::~DynamicObject () override
Definition at line 38 of file DynamicObject.cpp.
 {
     // make sure all references were properly removed
     ASSERT(!_aura);
     ASSERT(!_caster);
     ASSERT(!_isViewpoint);
     delete _removedAura;
 }
References _aura, _caster, _isViewpoint, _removedAura, and ASSERT.
Member Function Documentation
AddToWorld()
void DynamicObject::AddToWorld () override virtual
Register the dynamicObject for guid lookup and for caster
Reimplemented from Object.
Definition at line 60 of file DynamicObject.cpp.
 {
     if (!IsInWorld())
     {
         GetMap()->GetObjectsStore().Insert<DynamicObject>(GetGUID(), this);
         WorldObject::AddToWorld();
         BindToCaster();
     }
 }
References WorldObject::AddToWorld(), BindToCaster(), Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), and Object::IsInWorld().
BindToCaster()
void DynamicObject::BindToCaster ()
Definition at line 234 of file DynamicObject.cpp.
 {
     ASSERT(!_caster);
     _caster = ObjectAccessor::GetUnit(*this, GetCasterGUID());
     ASSERT(_caster);
     ASSERT(_caster->GetMap() == GetMap());
     _caster->_RegisterDynObject(this);
 }
References _caster, Unit::_RegisterDynObject(), ASSERT, GetCasterGUID(), WorldObject::GetMap(), and ObjectAccessor::GetUnit().
Referenced by AddToWorld().
CleanupsBeforeDelete()
void DynamicObject::CleanupsBeforeDelete (bool finalCleanup = true) override virtual
Reimplemented from WorldObject.
Definition at line 47 of file DynamicObject.cpp.
 {
     if (Transport* transport = GetTransport())
     {
         transport->RemovePassenger(this);
         SetTransport(nullptr);
         m_movementInfo.transport.Reset();
         m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
     }
     WorldObject::CleanupsBeforeDelete(finalCleanup);
 }
References WorldObject::CleanupsBeforeDelete(), WorldObject::GetTransport(), WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::RemoveMovementFlag(), MovementInfo::TransportInfo::Reset(), WorldObject::SetTransport(), and MovementInfo::transport.
CreateDynamicObject()
bool DynamicObject::CreateDynamicObject (ObjectGuid::LowType guidlow, Unit * caster, uint32 spellId, Position const & pos, float radius, DynamicObjectType type)
Definition at line 99 of file DynamicObject.cpp.
 {
     SetMap(caster->GetMap());
     Relocate(pos);
     if (!IsPositionValid())
     {
         LOG_ERROR("dyobject", "DynamicObject (spell %u) not created. Suggested coordinates isn't valid (X: %f Y: %f)", spellId, GetPositionX(), GetPositionY());
         return false;
     }
     WorldObject::_Create(guidlow, HighGuid::DynamicObject, caster->GetPhaseMask());
     UpdatePositionData();
     SetEntry(spellId);
     SetObjectScale(1);
     SetGuidValue(DYNAMICOBJECT_CASTER, caster->GetGUID());
     // The lower word of DYNAMICOBJECT_BYTES must be 0x0001. This value means that the visual radius will be overriden
     // by client for most of the "ground patch" visual effect spells and a few "skyfall" ones like Hurricane.
     // If any other value is used, the client will _always_ use the radius provided in DYNAMICOBJECT_RADIUS, but
     // precompensation is necessary (eg radius *= 2) for many spells. Anyway, blizz sends 0x0001 for all the spells
     // I saw sniffed...
     SetByteValue(DYNAMICOBJECT_BYTES, 0, type);
     SetUInt32Value(DYNAMICOBJECT_SPELLID, spellId);
     SetFloatValue(DYNAMICOBJECT_RADIUS, radius);
     SetUInt32Value(DYNAMICOBJECT_CASTTIME, World::GetGameTimeMS());
     if (IsWorldObject())
         setActive(true);    //must before add to map to be put in world container
     if (!GetMap()->AddToMap(this, true))
     {
         // Returning false will cause the object to be deleted - remove from transport
         return false;
     }
     return true;
 }
References WorldObject::_Create(), DynamicObject, DYNAMICOBJECT_BYTES, DYNAMICOBJECT_CASTER, DYNAMICOBJECT_CASTTIME, DYNAMICOBJECT_RADIUS, DYNAMICOBJECT_SPELLID, World::GetGameTimeMS(), Object::GetGUID(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::IsPositionValid(), WorldObject::IsWorldObject(), LOG_ERROR, pos(), Position::Relocate(), WorldObject::setActive(), Object::SetByteValue(), Object::SetEntry(), Object::SetFloatValue(), Object::SetGuidValue(), WorldObject::SetMap(), Object::SetObjectScale(), Object::SetUInt32Value(), and WorldObject::UpdatePositionData().
Referenced by Spell::EffectAddFarsight(), and Spell::EffectPersistentAA().
Delay()
void DynamicObject::Delay (int32 delaytime)
Definition at line 196 of file DynamicObject.cpp.
 {
     SetDuration(GetDuration() - delaytime);
 }
References GetDuration(), and SetDuration().
GetCaster()
Unit* DynamicObject::GetCaster () const inline
Definition at line 55 of file DynamicObject.h.
 { return _caster; }
References _caster.
Referenced by MotionTransport::DelayedTeleportTransport(), DynObjAura::FillTargetMap(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
GetCasterGUID()
ObjectGuid DynamicObject::GetCasterGUID () const inline
Definition at line 59 of file DynamicObject.h.
 { return GetGuidValue(DYNAMICOBJECT_CASTER); }
References DYNAMICOBJECT_CASTER, and Object::GetGuidValue().
Referenced by BindToCaster(), WorldObjectChangeAccumulator::Visit(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
GetDuration()
int32 DynamicObject::GetDuration () const
Definition at line 180 of file DynamicObject.cpp.
 {
     if (!_aura)
         return _duration;
     else
         return _aura->GetDuration();
 }
References _aura, _duration, and Aura::GetDuration().
Referenced by Delay(), and Update().
GetRadius()
float DynamicObject::GetRadius () const inline
Definition at line 60 of file DynamicObject.h.
 { return GetFloatValue(DYNAMICOBJECT_RADIUS); }
References DYNAMICOBJECT_RADIUS, and Object::GetFloatValue().
Referenced by DynObjAura::FillTargetMap().
GetSpellId()
uint32 DynamicObject::GetSpellId () const inline
Definition at line 58 of file DynamicObject.h.
 {  return GetUInt32Value(DYNAMICOBJECT_SPELLID); }
References DYNAMICOBJECT_SPELLID, and Object::GetUInt32Value().
Referenced by MotionTransport::DelayedTeleportTransport(), Unit::GetDynObject(), and Unit::RemoveDynObject().
IsViewpoint()
bool DynamicObject::IsViewpoint () const inline
Definition at line 61 of file DynamicObject.h.
 { return _isViewpoint; }
References _isViewpoint.
Referenced by Acore::MessageDistDeliverer::Visit().
Remove()
void DynamicObject::Remove ()
Definition at line 170 of file DynamicObject.cpp.
 {
     if (IsInWorld())
     {
         SendObjectDeSpawnAnim(GetGUID());
         RemoveFromWorld();
         AddObjectToRemoveList();
     }
 }
References WorldObject::AddObjectToRemoveList(), Object::GetGUID(), Object::IsInWorld(), RemoveFromWorld(), and WorldObject::SendObjectDeSpawnAnim().
Referenced by Unit::RemoveDynObject(), and Update().
RemoveAura()
void DynamicObject::RemoveAura ()
Definition at line 207 of file DynamicObject.cpp.
 {
     ASSERT(_aura && !_removedAura);
     _removedAura = _aura;
     _aura = nullptr;
     if (!_removedAura->IsRemoved())
         _removedAura->_Remove(AURA_REMOVE_BY_DEFAULT);
 }
References _aura, Aura::_Remove(), _removedAura, ASSERT, AURA_REMOVE_BY_DEFAULT, and Aura::IsRemoved().
Referenced by RemoveFromWorld().
RemoveCasterViewpoint()
void DynamicObject::RemoveCasterViewpoint ()
Definition at line 225 of file DynamicObject.cpp.
 {
     if (Player* caster = _caster->ToPlayer())
     {
         caster->SetViewpoint(this, false);
         _isViewpoint = false;
     }
 }
References _caster, _isViewpoint, and Object::ToPlayer().
Referenced by RemoveFromWorld().
RemoveFromWorld()
void DynamicObject::RemoveFromWorld () override virtual
Remove the dynamicObject from the accessor and from all lists of objects in world
Reimplemented from Object.
Definition at line 73 of file DynamicObject.cpp.
 {
     if (IsInWorld())
     {
         if (_isViewpoint)
             RemoveCasterViewpoint();
         if (_aura)
             RemoveAura();
         // dynobj could get removed in Aura::RemoveAura
         if (!IsInWorld())
             return;
         UnbindFromCaster();
         if (Transport* transport = GetTransport())
             transport->RemovePassenger(this, true);
         WorldObject::RemoveFromWorld();
         GetMap()->GetObjectsStore().Remove<DynamicObject>(GetGUID());
     }
 }
References _aura, _isViewpoint, Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), WorldObject::GetTransport(), Object::IsInWorld(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), RemoveAura(), RemoveCasterViewpoint(), WorldObject::RemoveFromWorld(), and UnbindFromCaster().
Referenced by Remove().
SetAura()
void DynamicObject::SetAura (Aura * aura)
Definition at line 201 of file DynamicObject.cpp.
 {
     ASSERT(!_aura && aura);
     _aura = aura;
 }
References _aura, and ASSERT.
Referenced by DynObjAura::DynObjAura().
SetCasterViewpoint()
void DynamicObject::SetCasterViewpoint ()
Definition at line 216 of file DynamicObject.cpp.
 {
     if (Player* caster = _caster->ToPlayer())
     {
         caster->SetViewpoint(this, true);
         _isViewpoint = true;
     }
 }
References _caster, _isViewpoint, and Object::ToPlayer().
Referenced by Spell::EffectAddFarsight().
SetDuration()
void DynamicObject::SetDuration (int32 newDuration)
Definition at line 188 of file DynamicObject.cpp.
 {
     if (!_aura)
         _duration = newDuration;
     else
         _aura->SetDuration(newDuration);
 }
References _aura, _duration, and Aura::SetDuration().
Referenced by Delay(), and Spell::EffectAddFarsight().
UnbindFromCaster()
void DynamicObject::UnbindFromCaster ()
Definition at line 243 of file DynamicObject.cpp.
 {
     ASSERT(_caster);
     _caster->_UnregisterDynObject(this);
     _caster = nullptr;
 }
References _caster, Unit::_UnregisterDynObject(), and ASSERT.
Referenced by RemoveFromWorld().
Update()
void DynamicObject::Update (uint32 p_time) override virtual
Reimplemented from WorldObject.
Definition at line 139 of file DynamicObject.cpp.
 {
     // caster has to be always available and in the same map
     ASSERT(_caster);
     ASSERT(_caster->GetMap() == GetMap());
     bool expired = false;
     if (_aura)
     {
         if (!_aura->IsRemoved())
             _aura->UpdateOwner(p_time, this);
         // _aura may be set to null in Aura::UpdateOwner call
         if (_aura && (_aura->IsRemoved() || _aura->IsExpired()))
             expired = true;
     }
     else
     {
         if (GetDuration() > int32(p_time))
             _duration -= p_time;
         else
             expired = true;
     }
     if (expired)
         Remove();
     else
         sScriptMgr->OnDynamicObjectUpdate(this, p_time);
 }
References _aura, _caster, _duration, ASSERT, GetDuration(), WorldObject::GetMap(), Aura::IsExpired(), Aura::IsRemoved(), Remove(), sScriptMgr, and Aura::UpdateOwner().
Member Data Documentation
_aura
Aura* DynamicObject::_aura protected
Definition at line 64 of file DynamicObject.h.
Referenced by GetDuration(), RemoveAura(), RemoveFromWorld(), SetAura(), SetDuration(), Update(), and ~DynamicObject().
_caster
Unit* DynamicObject::_caster protected
Definition at line 66 of file DynamicObject.h.
Referenced by BindToCaster(), GetCaster(), RemoveCasterViewpoint(), SetCasterViewpoint(), UnbindFromCaster(), Update(), and ~DynamicObject().
_duration
int32 DynamicObject::_duration protected
Definition at line 67 of file DynamicObject.h.
Referenced by GetDuration(), SetDuration(), and Update().
_isViewpoint
bool DynamicObject::_isViewpoint protected
Definition at line 68 of file DynamicObject.h.
Referenced by IsViewpoint(), RemoveCasterViewpoint(), RemoveFromWorld(), SetCasterViewpoint(), and ~DynamicObject().
_removedAura
Aura* DynamicObject::_removedAura protected
Definition at line 65 of file DynamicObject.h.
Referenced by RemoveAura(), and ~DynamicObject().
The documentation for this class was generated from the following files:
src/server/game/Entities/DynamicObject/DynamicObject.h
src/server/game/Entities/DynamicObject/DynamicObject.cpp