Azerotcore-wotlk: HostileReference Class Reference
HostileReference Class Reference
#include <ThreatMgr.h>
Public Member Functions
HostileReference (Unit *refUnit, ThreatMgr *threatMgr, float threat)
void addThreat (float modThreat)
void setThreat (float threat)
void addThreatPercent (int32 percent)
float getThreat () const
bool isOnline () const
void setTempThreat (float threat)
void addTempThreat (float threat)
void resetTempThreat ()
float getTempThreatModifier ()
void updateOnlineStatus ()
void setOnlineOfflineState (bool isOnline)
bool operator== (const HostileReference &hostileRef) const
ObjectGuid getUnitGuid () const
void removeReference ()
HostileReference * next ()
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Public Member Functions inherited from Reference< Unit, ThreatMgr >
Reference ()
virtual ~Reference ()=default
void link (Unit *toObj, ThreatMgr *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Unit, ThreatMgr > * next ()
Reference< Unit, ThreatMgr > const * next () const
Reference< Unit, ThreatMgr > * prev ()
Reference< Unit, ThreatMgr > const * prev () const
Reference< Unit, ThreatMgr > * nocheck_next ()
Reference< Unit, ThreatMgr > const * nocheck_next () const
Reference< Unit, ThreatMgr > * nocheck_prev ()
Reference< Unit, ThreatMgr > const * nocheck_prev () const
Unit * operator-> () const
Unit * getTarget () const
ThreatMgr * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Private Member Functions
void fireStatusChanged (ThreatRefStatusChangeEvent &threatRefStatusChangeEvent)
Unit * GetSourceUnit ()
Private Attributes
float iThreat
float iTempThreatModifier
ObjectGuid iUnitGuid
bool iOnline
Additional Inherited Members
Detailed Description
Definition at line 46 of file ThreatMgr.h.
Constructor & Destructor Documentation
HostileReference()
HostileReference::HostileReference (Unit * refUnit, ThreatMgr * threatMgr, float threat)
Definition at line 94 of file ThreatMgr.cpp.
 {
     iThreat = threat;
     iTempThreatModifier = 0.0f;
     link(refUnit, threatMgr);
     iUnitGuid = refUnit->GetGUID();
     iOnline = true;
 }
References Object::GetGUID(), iOnline, iTempThreatModifier, iThreat, iUnitGuid, and Reference< Unit, ThreatMgr >::link().
Member Function Documentation
addTempThreat()
void HostileReference::addTempThreat (float threat) inline
Definition at line 69 of file ThreatMgr.h.
     {
         iTempThreatModifier = threat;
         if (iTempThreatModifier != 0.0f)
             addThreat(iTempThreatModifier);
     }
References addThreat(), and iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), and setTempThreat().
addThreat()
void HostileReference::addThreat (float modThreat)
Definition at line 136 of file ThreatMgr.cpp.
 {
     iThreat += modThreat;
     // the threat is changed. Source and target unit have to be available
     // if the link was cut before relink it again
     if (!isOnline())
         updateOnlineStatus();
     if (modThreat != 0.0f)
     {
         ThreatRefStatusChangeEvent event(UEV_THREAT_REF_THREAT_CHANGE, this, modThreat);
         fireStatusChanged(event);
     }
     if (isValid() && modThreat >= 0.0f)
     {
         Unit* target = getTarget();
         if (target->GetEntry() != NPC_EYE_OF_KILROGG) // Excluded Eye of Kilrogg
         {
             Unit* victimOwner = target->GetCharmerOrOwner();
             if (victimOwner && victimOwner->IsAlive())
             {
                 GetSource()->addThreat(victimOwner, 0.0f); // create a threat to the owner of a pet, if the pet attacks
             }
         }
     }
 }
References ThreatMgr::addThreat(), fireStatusChanged(), Unit::GetCharmerOrOwner(), Object::GetEntry(), Reference< Unit, ThreatMgr >::GetSource(), Reference< Unit, ThreatMgr >::getTarget(), Unit::IsAlive(), isOnline(), Reference< Unit, ThreatMgr >::isValid(), iThreat, NPC_EYE_OF_KILROGG, UEV_THREAT_REF_THREAT_CHANGE, and updateOnlineStatus().
Referenced by ThreatMgr::_addThreat(), addTempThreat(), ThreatContainer::addThreat(), addThreatPercent(), resetTempThreat(), and setThreat().
addThreatPercent()
void HostileReference::addThreatPercent (int32 percent)
Definition at line 163 of file ThreatMgr.cpp.
 {
     // Xinef: Do not allow to modify threat by percent if threat is negative (forced to big value < 0 by spells adding temporary threat)
     // Xinef: When the temporary effect ends, temporary threat is added back which results in huge additional amount of threat
     if (iThreat <= 0)
         return;
     float tmpThreat = iThreat;
     AddPct(tmpThreat, percent);
     addThreat(tmpThreat - iThreat);
 }
References AddPct(), addThreat(), and iThreat.
Referenced by HostileRefMgr::addThreatPercent().
fireStatusChanged()
void HostileReference::fireStatusChanged (ThreatRefStatusChangeEvent & threatRefStatusChangeEvent) private
Definition at line 128 of file ThreatMgr.cpp.
 {
     if (GetSource())
         GetSource()->processThreatEvent(&threatRefStatusChangeEvent);
 }
References Reference< Unit, ThreatMgr >::GetSource(), and ThreatMgr::processThreatEvent().
Referenced by addThreat(), removeReference(), and setOnlineOfflineState().
GetSourceUnit()
Unit * HostileReference::GetSourceUnit () private
Definition at line 237 of file ThreatMgr.cpp.
 {
     return (GetSource()->GetOwner());
 }
References Reference< Unit, ThreatMgr >::GetSource().
Referenced by updateOnlineStatus().
getTempThreatModifier()
float HostileReference::getTempThreatModifier () inline
Definition at line 85 of file ThreatMgr.h.
 { return iTempThreatModifier; }
References iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), ThreatMgr::getThreatWithoutTemp(), npc_pet_mage_mirror_image::InitializeAI(), and ThreatMgr::tauntApply().
getThreat()
float HostileReference::getThreat () const inline
Definition at line 58 of file ThreatMgr.h.
 { return iThreat; }
References iThreat.
Referenced by Spell::EffectTaunt(), ThreatMgr::getThreat(), ThreatMgr::getThreatWithoutTemp(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), Acore::ThreatOrderPred::operator()(), ThreatMgr::processThreatEvent(), ThreatContainer::selectNextVictim(), setTempThreat(), setThreat(), and ThreatMgr::tauntApply().
getUnitGuid()
ObjectGuid HostileReference::getUnitGuid () const inline
Definition at line 98 of file ThreatMgr.h.
 { return iUnitGuid; }
References iUnitGuid.
Referenced by ThreatContainer::getReferenceByTarget(), Unit::IsInCombatWith(), operator==(), ThreatMgr::processThreatEvent(), Unit::SendChangeCurrentVictimOpcode(), Unit::SendRemoveFromThreatListOpcode(), and updateOnlineStatus().
isOnline()
bool HostileReference::isOnline () const inline
Definition at line 60 of file ThreatMgr.h.
 { return iOnline; }
References iOnline.
Referenced by addThreat(), debug_commandscript::HandleDebugHostileRefListCommand(), ThreatMgr::processThreatEvent(), and setOnlineOfflineState().
next()
HostileReference* HostileReference::next () inline
Definition at line 107 of file ThreatMgr.h.
 { return ((HostileReference*) Reference<Unit, ThreatMgr>::next()); }
Referenced by HostileRefMgr::addTempThreat(), HostileRefMgr::addThreatPercent(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), HostileRefMgr::setOnlineOfflineState(), Unit::SetPhaseMask(), HostileRefMgr::threatAssist(), Map::Update(), HostileRefMgr::updateThreatTables(), and HostileRefMgr::UpdateVisibility().
operator==()
bool HostileReference::operator== (const HostileReference & hostileRef) const inline
Definition at line 94 of file ThreatMgr.h.
 { return hostileRef.getUnitGuid() == getUnitGuid(); }
References getUnitGuid().
removeReference()
void HostileReference::removeReference ()
Definition at line 227 of file ThreatMgr.cpp.
 {
     invalidate();
     ThreatRefStatusChangeEvent event(UEV_THREAT_REF_REMOVE_FROM_LIST, this);
     fireStatusChanged(event);
 }
References fireStatusChanged(), Reference< Unit, ThreatMgr >::invalidate(), and UEV_THREAT_REF_REMOVE_FROM_LIST.
Referenced by HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferences(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), and HostileRefMgr::UpdateVisibility().
resetTempThreat()
void HostileReference::resetTempThreat () inline
Definition at line 76 of file ThreatMgr.h.
     {
         if (iTempThreatModifier != 0.0f)
         {
             addThreat(-iTempThreatModifier);
             iTempThreatModifier = 0.0f;
         }
     }
References addThreat(), and iTempThreatModifier.
Referenced by HostileRefMgr::addTempThreat(), and ThreatMgr::tauntFadeOut().
setOnlineOfflineState()
void HostileReference::setOnlineOfflineState (bool isOnline)
Definition at line 212 of file ThreatMgr.cpp.
 {
     if (iOnline != isOnline)
     {
         iOnline = isOnline;
         ThreatRefStatusChangeEvent event(UEV_THREAT_REF_ONLINE_STATUS, this);
         fireStatusChanged(event);
     }
 }
References fireStatusChanged(), iOnline, isOnline(), and UEV_THREAT_REF_ONLINE_STATUS.
Referenced by ThreatMgr::_addThreat(), HostileRefMgr::setOnlineOfflineState(), sourceObjectDestroyLink(), and updateOnlineStatus().
setTempThreat()
void HostileReference::setTempThreat (float threat) inline
Definition at line 64 of file ThreatMgr.h.
     {
         addTempThreat(threat - getThreat());
     }
References addTempThreat(), and getThreat().
Referenced by ThreatMgr::tauntApply().
setThreat()
void HostileReference::setThreat (float threat) inline
Definition at line 54 of file ThreatMgr.h.
 { addThreat(threat - getThreat()); }
References addThreat(), and getThreat().
sourceObjectDestroyLink()
void HostileReference::sourceObjectDestroyLink () override virtual
Implements Reference< Unit, ThreatMgr >.
Definition at line 120 of file ThreatMgr.cpp.
 {
     setOnlineOfflineState(false);
 }
References setOnlineOfflineState().
targetObjectBuildLink()
void HostileReference::targetObjectBuildLink () override virtual
Implements Reference< Unit, ThreatMgr >.
Definition at line 105 of file ThreatMgr.cpp.
 {
     getTarget()->addHatedBy(this);
 }
References Unit::addHatedBy(), and Reference< Unit, ThreatMgr >::getTarget().
targetObjectDestroyLink()
void HostileReference::targetObjectDestroyLink () override virtual
Implements Reference< Unit, ThreatMgr >.
Definition at line 112 of file ThreatMgr.cpp.
 {
     getTarget()->removeHatedBy(this);
 }
References Reference< Unit, ThreatMgr >::getTarget(), and Unit::removeHatedBy().
updateOnlineStatus()
void HostileReference::updateOnlineStatus ()
Definition at line 178 of file ThreatMgr.cpp.
 {
     bool online = false;
     if (!isValid())
         if (Unit* target = ObjectAccessor::GetUnit(*GetSourceUnit(), getUnitGuid()))
             link(target, GetSource());
     // only check for online status if
     // ref is valid
     // target is no player or not gamemaster
     // target is not in flight
     if (isValid()
             && (getTarget()->GetTypeId() != TYPEID_PLAYER || !getTarget()->ToPlayer()->IsGameMaster())
             && !getTarget()->IsInFlight()
             && getTarget()->IsInMap(GetSourceUnit())
             && getTarget()->InSamePhase(GetSourceUnit())
        )
     {
         Creature* creature = GetSourceUnit()->ToCreature();
         online = getTarget()->isInAccessiblePlaceFor(creature);
         if (!online)
         {
             if (creature->IsWithinCombatRange(getTarget(), creature->m_CombatDistance))
                 online = true;                              // not accessible but stays online
         }
     }
     setOnlineOfflineState(online);
 }
References Reference< Unit, ThreatMgr >::GetSource(), GetSourceUnit(), Reference< Unit, ThreatMgr >::getTarget(), ObjectAccessor::GetUnit(), getUnitGuid(), Unit::isInAccessiblePlaceFor(), Reference< Unit, ThreatMgr >::isValid(), Unit::IsWithinCombatRange(), Reference< Unit, ThreatMgr >::link(), Creature::m_CombatDistance, setOnlineOfflineState(), Object::ToCreature(), and TYPEID_PLAYER.
Referenced by addThreat(), and HostileRefMgr::updateThreatTables().
Member Data Documentation
iOnline
bool HostileReference::iOnline private
Definition at line 128 of file ThreatMgr.h.
Referenced by HostileReference(), isOnline(), and setOnlineOfflineState().
iTempThreatModifier
float HostileReference::iTempThreatModifier private
Definition at line 126 of file ThreatMgr.h.
Referenced by addTempThreat(), getTempThreatModifier(), HostileReference(), and resetTempThreat().
iThreat
float HostileReference::iThreat private
Definition at line 125 of file ThreatMgr.h.
Referenced by addThreat(), addThreatPercent(), getThreat(), and HostileReference().
iUnitGuid
ObjectGuid HostileReference::iUnitGuid private
Definition at line 127 of file ThreatMgr.h.
Referenced by getUnitGuid(), and HostileReference().
The documentation for this class was generated from the following files:
src/server/game/Combat/ThreatMgr.h
src/server/game/Combat/ThreatMgr.cpp