Azerotcore-wotlk: detail::uint128_wrapper Struct Reference
detail::uint128_wrapper Struct Reference
#include <format-inl.h>
Public Member Functions
uint128_wrapper ()=default
constexpr uint128_wrapper (uint64_t high, uint64_t low) FMT_NOEXCEPT
constexpr uint64_t high () const FMT_NOEXCEPT
constexpr uint64_t low () const FMT_NOEXCEPT
uint128_wrapper & operator+= (uint64_t n) FMT_NOEXCEPT
Public Attributes
uint64_t high_
uint64_t low_
Detailed Description
Definition at line 778 of file format-inl.h.
Constructor & Destructor Documentation
uint128_wrapper() [1/2]
detail::uint128_wrapper::uint128_wrapper () default
References high(), and low().
uint128_wrapper() [2/2]
constexpr detail::uint128_wrapper::uint128_wrapper (uint64_t high, uint64_t low) inline constexpr
Definition at line 803 of file format-inl.h.
       : high_{high},
         low_{low} {}
References high().
Member Function Documentation
high()
constexpr uint64_t detail::uint128_wrapper::high () const inline constexpr
Definition at line 807 of file format-inl.h.
 { return high_; }
References high_.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), uint128_wrapper(), detail::dragonbox::umul128_upper64(), and detail::dragonbox::umul192_upper64().
low()
constexpr uint64_t detail::uint128_wrapper::low () const inline constexpr
Definition at line 808 of file format-inl.h.
 { return low_; }
References low_.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), and uint128_wrapper().
operator+=()
uint128_wrapper& detail::uint128_wrapper::operator+= (uint64_t n) inline
Definition at line 810 of file format-inl.h.
{
 #  if defined(_MSC_VER) && defined(_M_X64)
     unsigned char carry = _addcarry_u64(0, low_, n, &low_);
     _addcarry_u64(carry, high_, 0, &high_);
     return *this;
 #  else
     uint64_t sum = low_ + n;
     high_ += (sum < low_ ? 1 : 0);
     low_ = sum;
     return *this;
 #  endif
   }
References high_, and low_.
Member Data Documentation
high_
uint64_t detail::uint128_wrapper::high_
Definition at line 800 of file format-inl.h.
Referenced by high(), and operator+=().
low_
uint64_t detail::uint128_wrapper::low_
Definition at line 801 of file format-inl.h.
Referenced by low(), and operator+=().
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/format-inl.h