Azerotcore-wotlk: spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript Class Reference
spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_blood_council_summon_shadow_resonance_SpellScript)
void SetDest (SpellDestination &dest)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1748 of file boss_blood_prince_council.cpp.
Member Function Documentation
PrepareSpellScript()
spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::PrepareSpellScript (spell_blood_council_summon_shadow_resonance_SpellScript) private
Register()
void spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1780 of file boss_blood_prince_council.cpp.
         {
             OnDestinationTargetSelect += SpellDestinationTargetSelectFn(spell_blood_council_summon_shadow_resonance_SpellScript::SetDest, EFFECT_0, TARGET_DEST_CASTER_RANDOM);
         }
References EFFECT_0, SpellScript::OnDestinationTargetSelect, SetDest(), SpellDestinationTargetSelectFn, and TARGET_DEST_CASTER_RANDOM.
SetDest()
void spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest (SpellDestination & dest) inline private
Definition at line 1752 of file boss_blood_prince_council.cpp.
         {
             Unit* summoner = GetCaster();
             float x = dest._position.GetPositionX();
             float y = dest._position.GetPositionY();
             float angle = summoner->GetAngle(x, y);
             if (dest._position.GetExactDist2d(summoner) > 35.0f && x > 4585.0f && y > 2716.0f && y < 2822.0f)
                 return;
             for (uint8 a = 0; a < 2; ++a)
                 for (uint8 i = 6; i > 0; --i)
                 {
                     float destX = summoner->GetPositionX() + cos(angle + a * M_PI) * i * 10.0f;
                     float destY = summoner->GetPositionY() + sin(angle + a * M_PI) * i * 10.0f;
                     if (summoner->GetMap()->isInLineOfSight(summoner->GetPositionX(), summoner->GetPositionY(), summoner->GetPositionZ() + 10.0f, destX, destY, summoner->GetPositionZ() + 10.0f, summoner->GetPhaseMask(), LINEOFSIGHT_ALL_CHECKS) && destX > 4585.0f && destY > 2716.0f && destY < 2822.0f)
                     {
                         float destZ = summoner->GetMapHeight(summoner->GetPhaseMask(), destX, destY, summoner->GetPositionZ());
                         if (fabs(destZ - summoner->GetPositionZ()) < 10.0f) // valid z found
{
                             dest._position.Relocate(destX, destY, destZ);
                             return;
                         }
                     }
                 }
             dest._position.Relocate(summoner->GetPositionX(), summoner->GetPositionY(), summoner->GetPositionZ());
         }
References SpellDestination::_position, mpq::a, Position::GetAngle(), SpellScript::GetCaster(), Position::GetExactDist2d(), WorldObject::GetMap(), WorldObject::GetMapHeight(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::isInLineOfSight(), LINEOFSIGHT_ALL_CHECKS, M_PI, Position::Relocate(), G3D::x, and G3D::y.
Referenced by Register().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp