Azerotcore-wotlk: deps/mysqllite/strings/dtoa.c File Reference
dtoa.c File Reference
#include <my_base.h>
#include <my_global.h>
#include <m_string.h>
Classes
union U
struct Bigint
struct Stack_alloc
Macros
#define DTOA_BUFF_SIZE (420 * sizeof(void *))
#define DTOA_OVERFLOW 9999
#define word0(x) (x)->L[1]
#define word1(x) (x)->L[0]
#define dval(x) (x)->d
#define Exp_shift 20
#define Exp_shift1 20
#define Exp_msk1 0x100000
#define Exp_mask 0x7ff00000
#define P 53
#define Bias 1023
#define Emin (-1022)
#define Exp_1 0x3ff00000
#define Exp_11 0x3ff00000
#define Ebits 11
#define Frac_mask 0xfffff
#define Frac_mask1 0xfffff
#define Ten_pmax 22
#define Bletch 0x10
#define Bndry_mask 0xfffff
#define Bndry_mask1 0xfffff
#define LSB 1
#define Sign_bit 0x80000000
#define Log2P 1
#define Tiny1 1
#define Quick_max 14
#define Int_max 14
#define Flt_Rounds 1
#define Rounding Flt_Rounds
#define rounded_product(a, b) a*= b
#define rounded_quotient(a, b) a/= b
#define Big0 (Frac_mask1 | Exp_msk1*(DBL_MAX_EXP+Bias-1))
#define Big1 0xffffffff
#define FFFFFFFF 0xffffffffUL
#define Kmax 15
#define Bcopy(x, y)
#define P5A_MAX (sizeof(p5_a)/sizeof(*p5_a) - 1)
#define d0 word0(&d)
#define d1 word1(&d)
#define d0 word0(d)
#define d1 word1(d)
#define Scale_Bit 0x10
#define n_bigtens 5
Typedefs
typedef int32 Long
typedef uint32 ULong
typedef int64 LLong
typedef uint64 ULLong
typedef struct Bigint Bigint
typedef struct Stack_alloc Stack_alloc
Functions
static double my_strtod_int (const char *, char **, int *, char *, size_t)
static char * dtoa (double, int, int, int *, int *, char **, char *, size_t)
static void dtoa_free (char *, char *, size_t)
size_t my_fcvt (double x, int precision, char *to, my_bool *error)
Converts a given floating point number to a zero-terminated string representation using the 'f' format.
size_t my_gcvt (double x, my_gcvt_arg_type type, int width, char *to, my_bool *error)
Converts a given floating point number to a zero-terminated string representation with a given field width using the 'e' format (aka scientific notation) or the 'f' one.
double my_strtod (const char *str, char **end, int *error)
Converts string to double (string does not have to be zero-terminated)
double my_atof (const char *nptr)
static Bigint * Balloc (int k, Stack_alloc *alloc)
static void Bfree (Bigint *v, Stack_alloc *alloc)
static char * dtoa_alloc (int i, Stack_alloc *alloc)
static Bigint * multadd (Bigint *b, int m, int a, Stack_alloc *alloc)
static Bigint * s2b (const char *s, int nd0, int nd, ULong y9, Stack_alloc *alloc)
static int hi0bits (register ULong x)
static int lo0bits (ULong *y)
static Bigint * i2b (int i, Stack_alloc *alloc)
static Bigint * mult (Bigint *a, Bigint *b, Stack_alloc *alloc)
static Bigint * pow5mult (Bigint *b, int k, Stack_alloc *alloc)
static Bigint * lshift (Bigint *b, int k, Stack_alloc *alloc)
static int cmp (Bigint *a, Bigint *b)
static Bigint * diff (Bigint *a, Bigint *b, Stack_alloc *alloc)
static double ulp (U *x)
static double b2d (Bigint *a, int *e)
static Bigint * d2b (U *d, int *e, int *bits, Stack_alloc *alloc)
static double ratio (Bigint *a, Bigint *b)
static int quorem (Bigint *b, Bigint *S)
Variables
static ULong powers5 []
static Bigint p5_a []
static const double tens []
static const double bigtens [] = { 1e16, 1e32, 1e64, 1e128, 1e256 }
static const double tinytens []
Macro Definition Documentation
Bcopy
#define Bcopy (x, y)
Value:
                          memcpy((char *)&x->sign, (char *)&y->sign,   \
                          2*sizeof(int) + y->wds*sizeof(ULong))
Definition at line 619 of file dtoa.c.
Bias
#define Bias 1023
Definition at line 574 of file dtoa.c.
Big0
#define Big0 (Frac_mask1 | Exp_msk1*(DBL_MAX_EXP+Bias-1))
Definition at line 611 of file dtoa.c.
Big1
#define Big1 0xffffffff
Definition at line 612 of file dtoa.c.
Bletch
#define Bletch 0x10
Definition at line 582 of file dtoa.c.
Bndry_mask
#define Bndry_mask 0xfffff
Definition at line 583 of file dtoa.c.
Bndry_mask1
#define Bndry_mask1 0xfffff
Definition at line 584 of file dtoa.c.
d0 [1/2]
#define d0 word0(&d)
d0 [2/2]
#define d0 word0(d)
d1 [1/2]
#define d1 word1(&d)
d1 [2/2]
#define d1 word1(d)
DTOA_BUFF_SIZE
#define DTOA_BUFF_SIZE (420 * sizeof(void *))
Appears to suffice to not call malloc() in most cases.
Todo:
see if it is possible to get rid of malloc(). this constant is sufficient to avoid malloc() on all inputs I have tried.
Definition at line 49 of file dtoa.c.
DTOA_OVERFLOW
#define DTOA_OVERFLOW 9999
Definition at line 52 of file dtoa.c.
dval
#define dval (x) (x)->d
Definition at line 561 of file dtoa.c.
Ebits
#define Ebits 11
Definition at line 578 of file dtoa.c.
Emin
#define Emin (-1022)
Definition at line 575 of file dtoa.c.
Exp_1
#define Exp_1 0x3ff00000
Definition at line 576 of file dtoa.c.
Exp_11
#define Exp_11 0x3ff00000
Definition at line 577 of file dtoa.c.
Exp_mask
#define Exp_mask 0x7ff00000
Definition at line 572 of file dtoa.c.
Exp_msk1
#define Exp_msk1 0x100000
Definition at line 571 of file dtoa.c.
Exp_shift
#define Exp_shift 20
Definition at line 569 of file dtoa.c.
Exp_shift1
#define Exp_shift1 20
Definition at line 570 of file dtoa.c.
FFFFFFFF
#define FFFFFFFF 0xffffffffUL
Definition at line 613 of file dtoa.c.
Flt_Rounds
#define Flt_Rounds 1
Definition at line 596 of file dtoa.c.
Frac_mask
#define Frac_mask 0xfffff
Definition at line 579 of file dtoa.c.
Frac_mask1
#define Frac_mask1 0xfffff
Definition at line 580 of file dtoa.c.
Int_max
#define Int_max 14
Definition at line 590 of file dtoa.c.
Kmax
#define Kmax 15
Definition at line 617 of file dtoa.c.
Log2P
#define Log2P 1
Definition at line 587 of file dtoa.c.
LSB
#define LSB 1
Definition at line 585 of file dtoa.c.
n_bigtens
#define n_bigtens 5
Definition at line 1298 of file dtoa.c.
P
#define P 53
Definition at line 573 of file dtoa.c.
P5A_MAX
#define P5A_MAX (sizeof(p5_a)/sizeof(*p5_a) - 1)
Definition at line 1004 of file dtoa.c.
Quick_max
#define Quick_max 14
Definition at line 589 of file dtoa.c.
rounded_product
#define rounded_product (a, b) a*= b
Definition at line 608 of file dtoa.c.
rounded_quotient
#define rounded_quotient (a, b) a/= b
Definition at line 609 of file dtoa.c.
Rounding
#define Rounding Flt_Rounds
Definition at line 605 of file dtoa.c.
Scale_Bit
#define Scale_Bit 0x10
Definition at line 1297 of file dtoa.c.
Sign_bit
#define Sign_bit 0x80000000
Definition at line 586 of file dtoa.c.
Ten_pmax
#define Ten_pmax 22
Definition at line 581 of file dtoa.c.
Tiny1
#define Tiny1 1
Definition at line 588 of file dtoa.c.
word0
#define word0 (x) (x)->L[1]
Definition at line 557 of file dtoa.c.
word1
#define word1 (x) (x)->L[0]
Definition at line 558 of file dtoa.c.
Typedef Documentation
Bigint
typedef struct Bigint Bigint
LLong
typedef int64 LLong
Definition at line 547 of file dtoa.c.
Long
typedef int32 Long
Definition at line 545 of file dtoa.c.
Stack_alloc
typedef struct Stack_alloc Stack_alloc
ULLong
typedef uint64 ULLong
Definition at line 548 of file dtoa.c.
ULong
typedef uint32 ULong
Definition at line 546 of file dtoa.c.
Function Documentation
b2d()
static double b2d (Bigint * a, int * e) static
Definition at line 1174 of file dtoa.c.
 {
   ULong *xa, *xa0, w, y, z;
   int k;
   U d;
 #define d0 word0(&d)
 #define d1 word1(&d)
   xa0= a->p.x;
   xa= xa0 + a->wds;
   y= *--xa;
   k= hi0bits(y);
   *e= 32 - k;
   if (k < Ebits)
   {
     d0= Exp_1 | y >> (Ebits - k);
     w= xa > xa0 ? *--xa : 0;
     d1= y << ((32-Ebits) + k) | w >> (Ebits - k);
     goto ret_d;
   }
   z= xa > xa0 ? *--xa : 0;
   if (k-= Ebits)
   {
     d0= Exp_1 | y << k | z >> (32 - k);
     y= xa > xa0 ? *--xa : 0;
     d1= z << k | y >> (32 - k);
   }
   else
   {
     d0= Exp_1 | y;
     d1= z;
   }
  ret_d:
 #undef d0
 #undef d1
   return dval(&d);
 }
References mpq::a, mpq::d, d0, d1, dval, Ebits, Exp_1, hi0bits(), G3D::y, and G3D::z.
Referenced by ratio().
Balloc()
static Bigint* Balloc (int k, Stack_alloc * alloc) static
Definition at line 659 of file dtoa.c.
 {
   Bigint *rv;
   if (k <= Kmax &&  alloc->freelist[k])
   {
     rv= alloc->freelist[k];
     alloc->freelist[k]= rv->p.next;
   }
   else
   {
     int x, len;
     x= 1 << k;
     len= MY_ALIGN(sizeof(Bigint) + x * sizeof(ULong), SIZEOF_CHARP);
     if (alloc->free + len <= alloc->end)
     {
       rv= (Bigint*) alloc->free;
       alloc->free+= len;
     }
     else
       rv= (Bigint*) malloc(len);
     rv->k= k;
     rv->maxwds= x;
   }
   rv->sign= rv->wds= 0;
   rv->p.x= (ULong*) (rv + 1);
   return rv;
 }
References Stack_alloc::free, Stack_alloc::freelist, Bigint::k, Bigint::maxwds, MY_ALIGN, Bigint::next, Bigint::p, Bigint::sign, Bigint::wds, G3D::x, and Bigint::x.
Referenced by d2b(), diff(), dtoa(), i2b(), lshift(), mult(), multadd(), my_strtod_int(), and s2b().
Bfree()
static void Bfree (Bigint * v, Stack_alloc * alloc) static
Definition at line 696 of file dtoa.c.
 {
   char *gptr= (char*) v;                       /* generic pointer */
   if (gptr < alloc->begin || gptr >= alloc->end)
     free(gptr);
   else if (v->k <= Kmax)
   {
     /*
       Maintain free lists only for stack objects: this way we don't
       have to bother with freeing lists in the end of dtoa;
       heap should not be used normally anyway.
     */
     v->p.next= alloc->freelist[v->k];
     alloc->freelist[v->k]= v;
   }
 }
References Stack_alloc::end, Stack_alloc::freelist, Bigint::k, Kmax, Bigint::next, and Bigint::p.
Referenced by dtoa(), lshift(), multadd(), my_strtod_int(), and pow5mult().
cmp()
static int cmp (Bigint * a, Bigint * b) static
Definition at line 1084 of file dtoa.c.
 {
   ULong *xa, *xa0, *xb, *xb0;
   int i, j;
   i= a->wds;
   j= b->wds;
   if (i-= j)
     return i;
   xa0= a->p.x;
   xa= xa0 + j;
   xb0= b->p.x;
   xb= xb0 + j;
   for (;;)
   {
     if (*--xa != *--xb)
       return *xa < *xb ? -1 : 1;
     if (xa <= xa0)
       break;
   }
   return 0;
 }
References mpq::a, and b.
Referenced by diff(), dtoa(), my_strtod_int(), and quorem().
d2b()
static Bigint* d2b (U * d, int * e, int * bits, Stack_alloc * alloc) static
Definition at line 1213 of file dtoa.c.
 {
   Bigint *b;
   int de, k;
   ULong *x, y, z;
   int i;
 #define d0 word0(d)
 #define d1 word1(d)
   b= Balloc(1, alloc);
   x= b->p.x;
   z= d0 & Frac_mask;
   d0 &= 0x7fffffff;       /* clear sign bit, which we ignore */
   if ((de= (int)(d0 >> Exp_shift)))
     z|= Exp_msk1;
   if ((y= d1))
   {
     if ((k= lo0bits(&y)))
     {
       x[0]= y | z << (32 - k);
       z>>= k;
     }
     else
       x[0]= y;
     i= b->wds= (x[1]= z) ? 2 : 1;
   }
   else
   {
     k= lo0bits(&z);
     x[0]= z;
     i= b->wds= 1;
     k+= 32;
   }
   if (de)
   {
     *e= de - Bias - (P-1) + k;
     *bits= P - k;
   }
   else
   {
     *e= de - Bias - (P-1) + 1 + k;
     *bits= 32*i - hi0bits(x[i-1]);
   }
   return b;
 #undef d0
 #undef d1
 }
References b, Balloc(), Bias, G3D::bits(), d0, d1, Exp_msk1, Exp_shift, Frac_mask, hi0bits(), lo0bits(), P, G3D::x, G3D::y, and G3D::z.
Referenced by dtoa(), and my_strtod_int().
diff()
static Bigint* diff (Bigint * a, Bigint * b, Stack_alloc * alloc) static
Definition at line 1108 of file dtoa.c.
 {
   Bigint *c;
   int i, wa, wb;
   ULong *xa, *xae, *xb, *xbe, *xc;
   ULLong borrow, y;
   i= cmp(a,b);
   if (!i)
   {
     c= Balloc(0, alloc);
     c->wds= 1;
     c->p.x[0]= 0;
     return c;
   }
   if (i < 0)
   {
     c= a;
     a= b;
     b= c;
     i= 1;
   }
   else
     i= 0;
   c= Balloc(a->k, alloc);
   c->sign= i;
   wa= a->wds;
   xa= a->p.x;
   xae= xa + wa;
   wb= b->wds;
   xb= b->p.x;
   xbe= xb + wb;
   xc= c->p.x;
   borrow= 0;
   do
   {
     y= (ULLong)*xa++ - *xb++ - borrow;
     borrow= y >> 32 & (ULong)1;
     *xc++= (ULong) (y & FFFFFFFF);
   }
   while (xb < xbe);
   while (xa < xae)
   {
     y= *xa++ - borrow;
     borrow= y >> 32 & (ULong)1;
     *xc++= (ULong) (y & FFFFFFFF);
   }
   while (!*--xc)
     wa--;
   c->wds= wa;
   return c;
 }
References mpq::a, b, Balloc(), mpq::c, cmp(), FFFFFFFF, and G3D::y.
Referenced by Battleground::_CheckSafePositions(), Battleground::_ProcessJoin(), Battleground::_ProcessLeave(), Battleground::_ProcessProgress(), Battleground::_ProcessResurrect(), InstanceSaveMgr::_ResetOrWarnAll(), WorldObject::AddToNotify(), Creature::AllLootRemovedFromCorpse(), Player::ApplySpellMod(), arena_slab_regind(), AuctionListingRunnable(), BattlegroundQueue::BattlegroundQueueUpdate(), spell_item_arcane_shroud::CalculateAmount(), spell_item_the_eye_of_diminution::CalculateAmount(), WaypointMovementGenerator< Creature >::CanMove(), Map::CanUnload(), Player::CheckAreaExploreAndOutdoor(), SmartAI::CheckConditions(), VehicleAI::CheckConditions(), ObjectMgr::CheckCreatureTemplate(), boss_twinemperorsAI::CheckEnrage(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::CheckTombReset(), G3D::CollisionDetection::closestPointOnTrianglePerimeter(), ConvertADT(), Creature::CreateFromProto(), MapInstanced::CreateInstanceForPlayer(), decimal_shift(), MapInstanced::DelayedUpdate(), DialogueHelper::DialogueUpdate(), hyjalAI::DoOverrun(), WaypointMovementGenerator< Creature >::DoUpdate(), RandomMovementGenerator< T >::DoUpdate(), ConfusedMovementGenerator< T >::DoUpdate(), dtIntersectSegmentPoly2D(), dtoa(), dtNavMesh::findNearestPolyInTile(), get_milliseconds(), Battleground::GetFreeSlotsForTeam(), Creature::GetVendorItemCurrentCount(), Acore::XP::GetZeroDifference(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), boss_twinemperorsAI::HandleBugs(), spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript::HandleEffectPeriodic(), boss_malygos::boss_malygosAI::HandleIntroSpeech(), WorldSession::HandleMoveWorldportAck(), spell_wailing_souls_periodic::spell_wailing_souls_periodic_AuraScript::HandlePeriodicTick(), WorldSocket::HandlePing(), boss_onyxia::boss_onyxiaAI::HandleWhelpSpam(), Creature::InitEntry(), ChaseAngle::IsAngleOkay(), MCNKLiquidData::IsWater(), large_ralloc_no_move_shrink(), ObjectMgr::LoadCreatures(), Group::LoadGroupFromDB(), InstanceSaveMgr::LoadResetTimes(), Unit::MeleeSpellMissChance(), Battleground::ModifyStartDelayTime(), npc_brewfest_keg_reciver::npc_brewfest_keg_reciverAI::MoveInLineOfSight(), my_strtod_int(), my_system_gmt_sec(), ScriptMgr::OnBattlegroundUpdate(), ScriptMgr::OnCreatureUpdate(), ScriptMgr::OnDynamicObjectUpdate(), ScriptMgr::OnGameObjectUpdate(), ScriptMgr::OnMapUpdate(), ScriptMgr::OnTransportUpdate(), SmartScript::OnUpdate(), ScriptMgr::OnWeatherUpdate(), ScriptMgr::OnWorldUpdate(), ScriptMgr::OnZeroDifferenceCalculation(), FollowMovementGenerator< T >::PositionOkay(), BattlegroundAB::PostUpdateImpl(), BattlegroundAV::PostUpdateImpl(), BattlegroundDS::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundIC::PostUpdateImpl(), BattlegroundRV::PostUpdateImpl(), BattlegroundSA::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), dtFindNearestPolyQuery::process(), process_int_arg(), randtime(), dtNavMeshQuery::raycast(), MapUpdater::schedule_lfg_update(), MapUpdater::schedule_update(), WorldSession::SendAuctionBidderNotification(), PeriodicTimer::TReset(), boss_twinemperorsAI::TryActivateAfterTTelep(), boss_twinemperorsAI::TryHealBrother(), PeriodicTimer::TUpdate(), G3D::UprightFrame::unwrapYaw(), PeriodicTimer::Update(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), TimeTrackerSmall::Update(), IntervalTimer::Update(), TimeTracker::Update(), Warden::Update(), BfCapturePoint::Update(), Battlefield::Update(), BattlefieldMgr::Update(), Battleground::Update(), BattlegroundMgr::Update(), AsyncAuctionListingMgr::Update(), AvgDiffTracker::Update(), SavingSystemMgr::Update(), OPvPCapturePoint::Update(), OutdoorPvP::Update(), OutdoorPvPMgr::Update(), Weather::Update(), WeatherMgr::Update(), World::Update(), BattlefieldWG::Update(), Pet::Update(), MotionTransport::Update(), StaticTransport::Update(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::Update(), instance_blackrock_spire::instance_blackrock_spireMapScript::Update(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_zulaman::instance_zulaman_InstanceMapScript::Update(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Update(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_gundrak::instance_gundrak_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OPvPCapturePointNA::Update(), OutdoorPvPNA::Update(), OPvPCapturePointTF::Update(), OutdoorPvPTF::Update(), OutdoorPvPZM::Update(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update(), instance_mechanar::instance_mechanar_InstanceMapScript::Update(), WorldSession::Update(), AuraEffect::Update(), Aura::Update(), GameObject::Update(), Creature::Update(), TempSummon::Update(), MapMgr::Update(), RotateMovementGenerator::Update(), go_bells::go_bellsAI::UpdateAI(), npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), CombatAI::UpdateAI(), CasterAI::UpdateAI(), VehicleAI::UpdateAI(), BossAI::UpdateAI(), WorldBossAI::UpdateAI(), npc_escortAI::UpdateAI(), SmartAI::UpdateAI(), SmartGameObjectAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), npc_rocknot::npc_rocknotAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_moira_bronzebeard::boss_moira_bronzebeardAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::UpdateAI(), boss_midnight::boss_midnightAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), netherspite_infernal::netherspite_infernalAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), prince_axes::prince_axesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_aran_elemental::water_elementalAI::UpdateAI(), npc_kilrek::npc_kilrekAI::UpdateAI(), npc_fiendish_imp::npc_fiendish_impAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), npc_tito::npc_titoAI::UpdateAI(), boss_strawman::boss_strawmanAI::UpdateAI(), boss_tinhead::boss_tinheadAI::UpdateAI(), boss_roar::boss_roarAI::UpdateAI(), boss_crone::boss_croneAI::UpdateAI(), npc_cyclone::npc_cycloneAI::UpdateAI(), boss_bigbadwolf::boss_bigbadwolfAI::UpdateAI(), boss_julianne::boss_julianneAI::UpdateAI(), boss_romulo::boss_romuloAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_image_of_medivh::npc_image_of_medivhAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_priestess_lackey_commonAI::UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_warlord_salaris::boss_warlord_salarisAI::UpdateAI(), boss_garaxxas::boss_garaxxasAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), boss_zelfan::boss_zelfanAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), boss_vexallus::boss_vexallusAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_dkc1_gothik::npc_dkc1_gothikAI::UpdateAI(), npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_baroness_anastari::boss_baroness_anastariAI::UpdateAI(), boss_brutallus::boss_brutallusAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), boss_muru::boss_muruAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_yenniku::npc_yennikuAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), npc_akilzon_eagle::npc_akilzon_eagleAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_thurg::boss_thurgAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_gazakrothAI::UpdateAI(), boss_lord_raadan::boss_lord_raadanAI::UpdateAI(), boss_darkheart::boss_darkheartAI::UpdateAI(), boss_slither::boss_slitherAI::UpdateAI(), boss_fenstalker::boss_fenstalkerAI::UpdateAI(), boss_koragg::boss_koraggAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_janalai_hatcher::npc_janalai_hatcherAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_gahzranka::boss_gahzrankaAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), npc_batrider::npc_batriderAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), npc_healing_ward::npc_healing_wardAI::UpdateAI(), npc_shade_of_jindo::npc_shade_of_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), npc_spawn_of_marli::npc_spawn_of_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI::UpdateAI(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::UpdateAI(), npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI::UpdateAI(), npc_brew_bubble::npc_brew_bubbleAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::UpdateAI(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_costumed_orphan_matron::npc_costumed_orphan_matronAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::UpdateAI(), boss_headless_horseman::boss_headless_horsemanAI::UpdateAI(), boss_headless_horseman_head::boss_headless_horseman_headAI::UpdateAI(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::UpdateAI(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::UpdateAI(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::UpdateAI(), npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), npc_ancient_wisp::npc_ancient_wispAI::UpdateAI(), npc_doomfire_targetting::npc_doomfire_targettingAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), alliance_rifleman::alliance_riflemanAI::UpdateAI(), hyjalAI::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_aeonus::boss_aeonusAI::UpdateAI(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::UpdateAI(), boss_temporus::boss_temporusAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), npc_time_rift::npc_time_riftAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), npc_hive_zara_larva::npc_hive_zara_larvaAI::UpdateAI(), boss_buru::boss_buruAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_rajaxx::boss_rajaxxAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_eye_tentacle::eye_tentacleAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), npc_giant_eye_tentacle::giant_eye_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_veklor::boss_veklorAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_muglash::npc_muglashAI::UpdateAI(), npc_spitelashes::npc_spitelashesAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_depth_charge::npc_depth_chargeAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_thrall_warchief::npc_thrall_warchiefAI::UpdateAI(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_custodian_of_time::npc_custodian_of_timeAI::UpdateAI(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_ame::npc_ameAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_anubarak_spike::npc_anubarak_spikeAI::UpdateAI(), boss_faction_championsAI::UpdateAI(), npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_dred::boss_dredAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_ghostly_priest::npc_ghostly_priestAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_phantom_hallucination::npc_phantom_hallucinationAI::UpdateAI(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::UpdateAI(), npc_spectral_footman::npc_spectral_footmanAI::UpdateAI(), npc_tortured_rifleman::npc_tortured_riflemanAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::UpdateAI(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::UpdateAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), npc_frostbite_invisible_stalker::npc_frostbite_invisible_stalkerAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), npc_living_mojo::npc_living_mojoAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_dark_nucleus::npc_dark_nucleusAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_icc_blood_beast::npc_icc_blood_beastAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_stinky_icc::npc_stinky_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_addAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_gunship_mage::npc_gunship_mageAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_darnavan::npc_darnavanAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_little_ooze::npc_little_oozeAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_ice_tomb::npc_ice_tombAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_impaling_spear::npc_impaling_spearAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::UpdateAI(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::UpdateAI(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::UpdateAI(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_severed_essence::npc_icc_severed_essenceAI::UpdateAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::UpdateAI(), boss_loatheb::boss_loathebAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_razuvious::boss_razuviousAI::UpdateAI(), boss_razuvious_minion::boss_razuvious_minionAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), npc_hover_disk::npc_hover_diskAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_magus_telestra::boss_magus_telestraAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), npc_crystal_spike::npc_crystal_spikeAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), dark_rune_protectors::dark_rune_protectorsAI::UpdateAI(), dark_rune_stormcaller::dark_rune_stormcallerAI::UpdateAI(), iron_golem_custodian::iron_golem_custodianAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_living_constellation::npc_living_constellationAI::UpdateAI(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::UpdateAI(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_auriaya::boss_auriayaAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::UpdateAI(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_hodirs_fury::npc_hodirs_furyAI::UpdateAI(), npc_mimirons_inferno::npc_mimirons_infernoAI::UpdateAI(), npc_thorims_hammer::npc_thorims_hammerAI::UpdateAI(), npc_storm_beacon_spawn::npc_storm_beacon_spawnAI::UpdateAI(), boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI::UpdateAI(), npc_mechanolift::npc_mechanoliftAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_lifebinder::boss_freya_lifebinderAI::UpdateAI(), boss_freya_healthy_spore::boss_freya_healthy_sporeAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), npc_ulduar_icicle::npc_ulduar_icicleAI::UpdateAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::UpdateAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI::UpdateAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::UpdateAI(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::UpdateAI(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), boss_thorim_trap::boss_thorim_trapAI::UpdateAI(), boss_thorim_pillar::boss_thorim_pillarAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_xt002_heart::npc_xt002_heartAI::UpdateAI(), npc_xt002_pummeller::npc_xt002_pummellerAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI::UpdateAI(), boss_yoggsaron::boss_yoggsaronAI::UpdateAI(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::UpdateAI(), boss_yoggsaron_death_orb::boss_yoggsaron_death_orbAI::UpdateAI(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::UpdateAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::UpdateAI(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::UpdateAI(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::UpdateAI(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::UpdateAI(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::UpdateAI(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::UpdateAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_skadi_grauf::boss_skadi_graufAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_koralon::boss_koralonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), npc_frozen_orb::npc_frozen_orbAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), npc_erekem_guard::npc_erekem_guardAI::UpdateAI(), boss_lavanthor::boss_lavanthorAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_ravenous_worg::npc_ravenous_worgAI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_boneguard_footman::npc_boneguard_footmanAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_jungle_punch_target::npc_jungle_punch_targetAI::UpdateAI(), npc_frosthound::npc_frosthoundAI::UpdateAI(), npc_iron_watcher::npc_iron_watcherAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_icefang::npc_icefangAI::UpdateAI(), npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI::UpdateAI(), npc_wg_queue::npc_wg_queueAI::UpdateAI(), npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), npc_stolen_soul::npc_stolen_soulAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), npc_voidtraveler::npc_voidtravelerAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::UpdateAI(), boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), npc_creature_generator_akama::npc_creature_generator_akamaAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_lady_malande::boss_lady_malandeAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), npc_inner_demon::npc_inner_demonAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::UpdateAI(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), npc_naga_distiller::npc_naga_distillerAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::UpdateAI(), boss_olm_the_summoner::boss_olm_the_summonerAI::UpdateAI(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::UpdateAI(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::UpdateAI(), boss_krosh_firehand::boss_krosh_firehandAI::UpdateAI(), boss_broggok::boss_broggokAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::UpdateAI(), boss_the_maker::boss_the_makerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_nazan::boss_nazanAI::UpdateAI(), boss_vazruden::boss_vazrudenAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), npc_omrogg_heads::npc_omrogg_headsAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_commander_sarannis::boss_commander_sarannisAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_laj::boss_lajAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_warp_splinter::boss_warp_splinterAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_void_reaver::boss_void_reaverAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::UpdateAI(), npc_ragin_flames::npc_ragin_flamesAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_corki::npc_corkiAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::UpdateAI(), npc_raliq_the_drunk::npc_raliq_the_drunkAI::UpdateAI(), npc_salsalabim::npc_salsalabimAI::UpdateAI(), npc_ishanah::ishanahAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_floon::npc_floonAI::UpdateAI(), npc_cooshcoosh::npc_cooshcooshAI::UpdateAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI(), npc_pet_gen_soul_trader_beacon::UpdateAI(), npc_pet_gen_argent_pony_bridle::UpdateAI(), npc_pet_gen_target_following_bomb::UpdateAI(), npc_pet_gen_valkyr_guardian::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_pet_gen_wind_rider_cub::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_pet_gen_toxic_wasteling::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_mage_mirror_image::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), emerald_dragonAI::UpdateAI(), npc_dream_fog::npc_dream_fogAI::UpdateAI(), boss_taerar::boss_taerarAI::UpdateAI(), go_witherbark_totem_bundle::go_witherbark_totem_bundleAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), go_heat::go_heatAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), generic_creature::generic_creatureAI::UpdateAI(), trigger_periodic::trigger_periodicAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_elder_clearwater::npc_elder_clearwaterAI::UpdateAI(), npc_riggle_bassbait::npc_riggle_bassbaitAI::UpdateAI(), npc_training_dummy::npc_training_dummyAI::UpdateAI(), npc_target_dummy::npc_target_dummyAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), npc_dancing_flames::npc_dancing_flamesAI::UpdateAI(), npc_doctor::npc_doctorAI::UpdateAI(), npc_garments_of_quests::npc_garments_of_questsAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), CritterAI::UpdateAI(), PetAI::UpdateAI(), Player::UpdateContestedPvP(), SmartAI::UpdateDespawn(), Item::UpdateDuration(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_ranshalla::npc_ranshallaAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::UpdateEscortAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_isla_starmane::npc_isla_starmaneAI::UpdateEscortAI(), BattlegroundQueue::UpdateEvents(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), MotionMaster::UpdateMotion(), Aura::UpdateOwner(), SmartAI::UpdatePath(), lfg::LFGQueue::UpdateQueueTimers(), lfg::LFGMgr::UpdateRaidBrowser(), World::UpdateSessions(), WorldSession::UpdateTimeOutTime(), SmartScript::UpdateTimer(), Creature::UpdateVendorItemCurrentCount(), and WorldUpdateLoop().
dtoa()
static char * dtoa (double dd, int mode, int ndigits, int * decpt, int * sign, char ** rve, char * buf, size_t buf_size) static
Definition at line 2140 of file dtoa.c.
 {
   /*
     Arguments ndigits, decpt, sign are similar to those
     of ecvt and fcvt; trailing zeros are suppressed from
     the returned string.  If not null, *rve is set to point
     to the end of the return value.  If d is +-Infinity or NaN,
     then *decpt is set to DTOA_OVERFLOW.
     mode:
           0 ==> shortest string that yields d when read in
                 and rounded to nearest.
           1 ==> like 0, but with Steele & White stopping rule;
                 e.g. with IEEE P754 arithmetic , mode 0 gives
                 1e23 whereas mode 1 gives 9.999999999999999e22.
           2 ==> max(1,ndigits) significant digits.  This gives a
                 return value similar to that of ecvt, except
                 that trailing zeros are suppressed.
           3 ==> through ndigits past the decimal point.  This
                 gives a return value similar to that from fcvt,
                 except that trailing zeros are suppressed, and
                 ndigits can be negative.
           4,5 ==> similar to 2 and 3, respectively, but (in
                 round-nearest mode) with the tests of mode 0 to
                 possibly return a shorter string that rounds to d.
                 With IEEE arithmetic and compilation with
                 -DHonor_FLT_ROUNDS, modes 4 and 5 behave the same
                 as modes 2 and 3 when FLT_ROUNDS != 1.
           6-9 ==> Debugging modes similar to mode - 4:  don't try
                 fast floating-point estimate (if applicable).
       Values of mode other than 0-9 are treated as mode 0.
     Sufficient space is allocated to the return value
     to hold the suppressed trailing zeros.
   */
   int bbits, b2, b5, be, dig, i, ieps, UNINIT_VAR(ilim), ilim0,
     UNINIT_VAR(ilim1), j, j1, k, k0, k_check, leftright, m2, m5, s2, s5,
     spec_case, try_quick;
   Long L;
   int denorm;
   ULong x;
   Bigint *b, *b1, *delta, *mlo, *mhi, *S;
   U d2, eps, u;
   double ds;
   char *s, *s0;
 #ifdef Honor_FLT_ROUNDS
   int rounding;
 #endif
   Stack_alloc alloc;
   alloc.begin= alloc.free= buf;
   alloc.end= buf + buf_size;
   memset(alloc.freelist, 0, sizeof(alloc.freelist));
   u.d= dd;
   if (word0(&u) & Sign_bit)
   {
     /* set sign for everything, including 0's and NaNs */
     *sign= 1;
     word0(&u) &= ~Sign_bit;  /* clear sign bit */
   }
   else
     *sign= 0;
   /* If infinity, set decpt to DTOA_OVERFLOW, if 0 set it to 1 */
   if (((word0(&u) & Exp_mask) == Exp_mask && (*decpt= DTOA_OVERFLOW)) ||
       (!dval(&u) && (*decpt= 1)))
   {
     /* Infinity, NaN, 0 */
     char *res= (char*) dtoa_alloc(2, &alloc);
     res[0]= '0';
     res[1]= '\0';
     if (rve)
       *rve= res + 1;
     return res;
   }
 #ifdef Honor_FLT_ROUNDS
   if ((rounding= Flt_Rounds) >= 2)
   {
     if (*sign)
       rounding= rounding == 2 ? 0 : 2;
     else
       if (rounding != 2)
         rounding= 0;
   }
 #endif
   b= d2b(&u, &be, &bbits, &alloc);
   if ((i= (int)(word0(&u) >> Exp_shift1 & (Exp_mask>>Exp_shift1))))
   {
     dval(&d2)= dval(&u);
     word0(&d2) &= Frac_mask1;
     word0(&d2) |= Exp_11;
     /*
       log(x)       ~=~ log(1.5) + (x-1.5)/1.5
       log10(x)      =  log(x) / log(10)
                    ~=~ log(1.5)/log(10) + (x-1.5)/(1.5*log(10))
       log10(d)= (i-Bias)*log(2)/log(10) + log10(d2)
       This suggests computing an approximation k to log10(d) by
       k= (i - Bias)*0.301029995663981
            + ( (d2-1.5)*0.289529654602168 + 0.176091259055681 );
       We want k to be too large rather than too small.
       The error in the first-order Taylor series approximation
       is in our favor, so we just round up the constant enough
       to compensate for any error in the multiplication of
       (i - Bias) by 0.301029995663981; since |i - Bias| <= 1077,
       and 1077 * 0.30103 * 2^-52 ~=~ 7.2e-14,
       adding 1e-13 to the constant term more than suffices.
       Hence we adjust the constant term to 0.1760912590558.
       (We could get a more accurate k by invoking log10,
        but this is probably not worthwhile.)
     */
     i-= Bias;
     denorm= 0;
   }
   else
   {
     /* d is denormalized */
     i= bbits + be + (Bias + (P-1) - 1);
     x= i > 32  ? word0(&u) << (64 - i) | word1(&u) >> (i - 32)
       : word1(&u) << (32 - i);
     dval(&d2)= x;
     word0(&d2)-= 31*Exp_msk1; /* adjust exponent */
     i-= (Bias + (P-1) - 1) + 1;
     denorm= 1;
   }
   ds= (dval(&d2)-1.5)*0.289529654602168 + 0.1760912590558 + i*0.301029995663981;
   k= (int)ds;
   if (ds < 0. && ds != k)
     k--;    /* want k= floor(ds) */
   k_check= 1;
   if (k >= 0 && k <= Ten_pmax)
   {
     if (dval(&u) < tens[k])
       k--;
     k_check= 0;
   }
   j= bbits - i - 1;
   if (j >= 0)
   {
     b2= 0;
     s2= j;
   }
   else
   {
     b2= -j;
     s2= 0;
   }
   if (k >= 0)
   {
     b5= 0;
     s5= k;
     s2+= k;
   }
   else
   {
     b2-= k;
     b5= -k;
     s5= 0;
   }
   if (mode < 0 || mode > 9)
     mode= 0;
 #ifdef Check_FLT_ROUNDS
   try_quick= Rounding == 1;
 #else
   try_quick= 1;
 #endif
   if (mode > 5)
   {
     mode-= 4;
     try_quick= 0;
   }
   leftright= 1;
   switch (mode) {
   case 0:
   case 1:
     ilim= ilim1= -1;
     i= 18;
     ndigits= 0;
     break;
   case 2:
     leftright= 0;
     /* no break */
   case 4:
     if (ndigits <= 0)
       ndigits= 1;
     ilim= ilim1= i= ndigits;
     break;
   case 3:
     leftright= 0;
     /* no break */
   case 5:
     i= ndigits + k + 1;
     ilim= i;
     ilim1= i - 1;
     if (i <= 0)
       i= 1;
   }
   s= s0= dtoa_alloc(i, &alloc);
 #ifdef Honor_FLT_ROUNDS
   if (mode > 1 && rounding != 1)
     leftright= 0;
 #endif
   if (ilim >= 0 && ilim <= Quick_max && try_quick)
   {
     /* Try to get by with floating-point arithmetic. */
     i= 0;
     dval(&d2)= dval(&u);
     k0= k;
     ilim0= ilim;
     ieps= 2; /* conservative */
     if (k > 0)
     {
       ds= tens[k&0xf];
       j= k >> 4;
       if (j & Bletch)
       {
         /* prevent overflows */
         j&= Bletch - 1;
         dval(&u)/= bigtens[n_bigtens-1];
         ieps++;
       }
       for (; j; j>>= 1, i++)
       {
         if (j & 1)
         {
           ieps++;
           ds*= bigtens[i];
         }
       }
       dval(&u)/= ds;
     }
     else if ((j1= -k))
     {
       dval(&u)*= tens[j1 & 0xf];
       for (j= j1 >> 4; j; j>>= 1, i++)
       {
         if (j & 1)
         {
           ieps++;
           dval(&u)*= bigtens[i];
         }
       }
     }
     if (k_check && dval(&u) < 1. && ilim > 0)
     {
       if (ilim1 <= 0)
         goto fast_failed;
       ilim= ilim1;
       k--;
       dval(&u)*= 10.;
       ieps++;
     }
     dval(&eps)= ieps*dval(&u) + 7.;
     word0(&eps)-= (P-1)*Exp_msk1;
     if (ilim == 0)
     {
       S= mhi= 0;
       dval(&u)-= 5.;
       if (dval(&u) > dval(&eps))
         goto one_digit;
       if (dval(&u) < -dval(&eps))
         goto no_digits;
       goto fast_failed;
     }
     if (leftright)
     {
       /* Use Steele & White method of only generating digits needed. */
       dval(&eps)= 0.5/tens[ilim-1] - dval(&eps);
       for (i= 0;;)
       {
         L= (Long) dval(&u);
         dval(&u)-= L;
         *s++= '0' + (int)L;
         if (dval(&u) < dval(&eps))
           goto ret1;
         if (1. - dval(&u) < dval(&eps))
           goto bump_up;
         if (++i >= ilim)
           break;
         dval(&eps)*= 10.;
         dval(&u)*= 10.;
       }
     }
     else
     {
       /* Generate ilim digits, then fix them up. */
       dval(&eps)*= tens[ilim-1];
       for (i= 1;; i++, dval(&u)*= 10.)
       {
         L= (Long)(dval(&u));
         if (!(dval(&u)-= L))
           ilim= i;
         *s++= '0' + (int)L;
         if (i == ilim)
         {
           if (dval(&u) > 0.5 + dval(&eps))
             goto bump_up;
           else if (dval(&u) < 0.5 - dval(&eps))
           {
             while (*--s == '0');
             s++;
             goto ret1;
           }
           break;
         }
       }
     }
   fast_failed:
     s= s0;
     dval(&u)= dval(&d2);
     k= k0;
     ilim= ilim0;
   }
   /* Do we have a "small" integer? */
   if (be >= 0 && k <= Int_max)
   {
     /* Yes. */
     ds= tens[k];
     if (ndigits < 0 && ilim <= 0)
     {
       S= mhi= 0;
       if (ilim < 0 || dval(&u) <= 5*ds)
         goto no_digits;
       goto one_digit;
     }
     for (i= 1;; i++, dval(&u)*= 10.)
     {
       L= (Long)(dval(&u) / ds);
       dval(&u)-= L*ds;
 #ifdef Check_FLT_ROUNDS
       /* If FLT_ROUNDS == 2, L will usually be high by 1 */
       if (dval(&u) < 0)
       {
         L--;
         dval(&u)+= ds;
       }
 #endif
       *s++= '0' + (int)L;
       if (!dval(&u))
       {
         break;
       }
       if (i == ilim)
       {
 #ifdef Honor_FLT_ROUNDS
         if (mode > 1)
         {
           switch (rounding) {
           case 0: goto ret1;
           case 2: goto bump_up;
           }
         }
 #endif
         dval(&u)+= dval(&u);
         if (dval(&u) > ds || (dval(&u) == ds && L & 1))
         {
 bump_up:
           while (*--s == '9')
             if (s == s0)
             {
               k++;
               *s= '0';
               break;
             }
           ++*s++;
         }
         break;
       }
     }
     goto ret1;
   }
   m2= b2;
   m5= b5;
   mhi= mlo= 0;
   if (leftright)
   {
     i = denorm ? be + (Bias + (P-1) - 1 + 1) : 1 + P - bbits;
     b2+= i;
     s2+= i;
     mhi= i2b(1, &alloc);
   }
   if (m2 > 0 && s2 > 0)
   {
     i= m2 < s2 ? m2 : s2;
     b2-= i;
     m2-= i;
     s2-= i;
   }
   if (b5 > 0)
   {
     if (leftright)
     {
       if (m5 > 0)
       {
         mhi= pow5mult(mhi, m5, &alloc);
         b1= mult(mhi, b, &alloc);
         Bfree(b, &alloc);
         b= b1;
       }
       if ((j= b5 - m5))
         b= pow5mult(b, j, &alloc);
     }
     else
       b= pow5mult(b, b5, &alloc);
   }
   S= i2b(1, &alloc);
   if (s5 > 0)
     S= pow5mult(S, s5, &alloc);
   /* Check for special case that d is a normalized power of 2. */
   spec_case= 0;
   if ((mode < 2 || leftright)
 #ifdef Honor_FLT_ROUNDS
       && rounding == 1
 #endif
      )
   {
     if (!word1(&u) && !(word0(&u) & Bndry_mask) &&
         word0(&u) & (Exp_mask & ~Exp_msk1)
        )
     {
       /* The special case */
       b2+= Log2P;
       s2+= Log2P;
       spec_case= 1;
     }
   }
   /*
     Arrange for convenient computation of quotients:
     shift left if necessary so divisor has 4 leading 0 bits.
     Perhaps we should just compute leading 28 bits of S once
     a nd for all and pass them and a shift to quorem, so it
     can do shifts and ors to compute the numerator for q.
   */
   if ((i= ((s5 ? 32 - hi0bits(S->p.x[S->wds-1]) : 1) + s2) & 0x1f))
     i= 32 - i;
   if (i > 4)
   {
     i-= 4;
     b2+= i;
     m2+= i;
     s2+= i;
   }
   else if (i < 4)
   {
     i+= 28;
     b2+= i;
     m2+= i;
     s2+= i;
   }
   if (b2 > 0)
     b= lshift(b, b2, &alloc);
   if (s2 > 0)
     S= lshift(S, s2, &alloc);
   if (k_check)
   {
     if (cmp(b,S) < 0)
     {
       k--;
       /* we botched the k estimate */
       b= multadd(b, 10, 0, &alloc);
       if (leftright)
         mhi= multadd(mhi, 10, 0, &alloc);
       ilim= ilim1;
     }
   }
   if (ilim <= 0 && (mode == 3 || mode == 5))
   {
     if (ilim < 0 || cmp(b,S= multadd(S,5,0, &alloc)) <= 0)
     {
       /* no digits, fcvt style */
 no_digits:
       k= -1 - ndigits;
       goto ret;
     }
 one_digit:
     *s++= '1';
     k++;
     goto ret;
   }
   if (leftright)
   {
     if (m2 > 0)
       mhi= lshift(mhi, m2, &alloc);
     /*
       Compute mlo -- check for special case that d is a normalized power of 2.
     */
     mlo= mhi;
     if (spec_case)
     {
       mhi= Balloc(mhi->k, &alloc);
       Bcopy(mhi, mlo);
       mhi= lshift(mhi, Log2P, &alloc);
     }
     for (i= 1;;i++)
     {
       dig= quorem(b,S) + '0';
       /* Do we yet have the shortest decimal string that will round to d? */
       j= cmp(b, mlo);
       delta= diff(S, mhi, &alloc);
       j1= delta->sign ? 1 : cmp(b, delta);
       Bfree(delta, &alloc);
       if (j1 == 0 && mode != 1 && !(word1(&u) & 1)
 #ifdef Honor_FLT_ROUNDS
           && rounding >= 1
 #endif
          )
       {
         if (dig == '9')
           goto round_9_up;
         if (j > 0)
           dig++;
         *s++= dig;
         goto ret;
       }
       if (j < 0 || (j == 0 && mode != 1 && !(word1(&u) & 1)))
       {
         if (!b->p.x[0] && b->wds <= 1)
         {
           goto accept_dig;
         }
 #ifdef Honor_FLT_ROUNDS
         if (mode > 1)
           switch (rounding) {
           case 0: goto accept_dig;
           case 2: goto keep_dig;
           }
 #endif /*Honor_FLT_ROUNDS*/
         if (j1 > 0)
         {
           b= lshift(b, 1, &alloc);
           j1= cmp(b, S);
           if ((j1 > 0 || (j1 == 0 && dig & 1))
               && dig++ == '9')
             goto round_9_up;
         }
 accept_dig:
         *s++= dig;
         goto ret;
       }
       if (j1 > 0)
       {
 #ifdef Honor_FLT_ROUNDS
         if (!rounding)
           goto accept_dig;
 #endif
         if (dig == '9')
         { /* possible if i == 1 */
 round_9_up:
           *s++= '9';
           goto roundoff;
         }
         *s++= dig + 1;
         goto ret;
       }
 #ifdef Honor_FLT_ROUNDS
 keep_dig:
 #endif
       *s++= dig;
       if (i == ilim)
         break;
       b= multadd(b, 10, 0, &alloc);
       if (mlo == mhi)
         mlo= mhi= multadd(mhi, 10, 0, &alloc);
       else
       {
         mlo= multadd(mlo, 10, 0, &alloc);
         mhi= multadd(mhi, 10, 0, &alloc);
       }
     }
   }
   else
     for (i= 1;; i++)
     {
       *s++= dig= quorem(b,S) + '0';
       if (!b->p.x[0] && b->wds <= 1)
       {
         goto ret;
       }
       if (i >= ilim)
         break;
       b= multadd(b, 10, 0, &alloc);
     }
   /* Round off last digit */
 #ifdef Honor_FLT_ROUNDS
   switch (rounding) {
   case 0: goto trimzeros;
   case 2: goto roundoff;
   }
 #endif
   b= lshift(b, 1, &alloc);
   j= cmp(b, S);
   if (j > 0 || (j == 0 && dig & 1))
   {
 roundoff:
     while (*--s == '9')
       if (s == s0)
       {
         k++;
         *s++= '1';
         goto ret;
       }
     ++*s++;
   }
   else
   {
 #ifdef Honor_FLT_ROUNDS
 trimzeros:
 #endif
     while (*--s == '0');
     s++;
   }
 ret:
   Bfree(S, &alloc);
   if (mhi)
   {
     if (mlo && mlo != mhi)
       Bfree(mlo, &alloc);
     Bfree(mhi, &alloc);
   }
 ret1:
   Bfree(b, &alloc);
   *s= 0;
   *decpt= k + 1;
   if (rve)
     *rve= s;
   return s0;
 }
References b, Balloc(), Bcopy, Stack_alloc::begin, Bfree(), Bias, bigtens, Bletch, Bndry_mask, cmp(), U::d, d2b(), diff(), dtoa_alloc(), DTOA_OVERFLOW, dval, Stack_alloc::end, endif(), G3D::eps(), Exp_11, Exp_mask, Exp_msk1, Exp_shift1, Flt_Rounds, Frac_mask1, Stack_alloc::free, Stack_alloc::freelist, hi0bits(), i2b(), Int_max, Bigint::k, Log2P, lshift(), memset, mult(), multadd(), n_bigtens, P, Bigint::p, pow5mult(), Quick_max, quorem(), ret, Rounding, Bigint::sign, Sign_bit, Ten_pmax, tens, UNINIT_VAR, Bigint::wds, word0, word1, G3D::x, and Bigint::x.
Referenced by my_fcvt(), and my_gcvt().
dtoa_alloc()
static char* dtoa_alloc (int i, Stack_alloc * alloc) static
Definition at line 721 of file dtoa.c.
 {
   char *rv;
   int aligned_size= MY_ALIGN(i, SIZEOF_CHARP);
   if (alloc->free + aligned_size <= alloc->end)
   {
     rv= alloc->free;
     alloc->free+= aligned_size;
   }
   else
     rv= malloc(i);
   return rv;
 }
References Stack_alloc::free, and MY_ALIGN.
Referenced by dtoa().
dtoa_free()
static void dtoa_free (char * gptr, char * buf, size_t buf_size) static
Definition at line 741 of file dtoa.c.
 {
   if (gptr < buf || gptr >= buf + buf_size)
     free(gptr);
 }
Referenced by my_fcvt(), and my_gcvt().
hi0bits()
static int hi0bits (register ULong x) static
Definition at line 815 of file dtoa.c.
 {
   register int k= 0;
   if (!(x & 0xffff0000))
   {
     k= 16;
     x<<= 16;
   }
   if (!(x & 0xff000000))
   {
     k+= 8;
     x<<= 8;
   }
   if (!(x & 0xf0000000))
   {
     k+= 4;
     x<<= 4;
   }
   if (!(x & 0xc0000000))
   {
     k+= 2;
     x<<= 2;
   }
   if (!(x & 0x80000000))
   {
     k++;
     if (!(x & 0x40000000))
       return 32;
   }
   return k;
 }
References G3D::x.
Referenced by b2d(), d2b(), and dtoa().
i2b()
static Bigint* i2b (int i, Stack_alloc * alloc) static
Definition at line 901 of file dtoa.c.
 {
   Bigint *b;
   b= Balloc(1, alloc);
   b->p.x[0]= i;
   b->wds= 1;
   return b;
 }
References b, and Balloc().
Referenced by dtoa(), and my_strtod_int().
lo0bits()
static int lo0bits (ULong * y) static
Definition at line 849 of file dtoa.c.
 {
   register int k;
   register ULong x= *y;
   if (x & 7)
   {
     if (x & 1)
       return 0;
     if (x & 2)
     {
       *y= x >> 1;
       return 1;
     }
     *y= x >> 2;
     return 2;
   }
   k= 0;
   if (!(x & 0xffff))
   {
     k= 16;
     x>>= 16;
   }
   if (!(x & 0xff))
   {
     k+= 8;
     x>>= 8;
   }
   if (!(x & 0xf))
   {
     k+= 4;
     x>>= 4;
   }
   if (!(x & 0x3))
   {
     k+= 2;
     x>>= 2;
   }
   if (!(x & 1))
   {
     k++;
     x>>= 1;
     if (!x)
       return 32;
   }
   *y= x;
   return k;
 }
References G3D::x, and G3D::y.
Referenced by d2b().
lshift()
static Bigint* lshift (Bigint * b, int k, Stack_alloc * alloc) static
Definition at line 1044 of file dtoa.c.
 {
   int i, k1, n, n1;
   Bigint *b1;
   ULong *x, *x1, *xe, z;
   n= k >> 5;
   k1= b->k;
   n1= n + b->wds + 1;
   for (i= b->maxwds; n1 > i; i<<= 1)
     k1++;
   b1= Balloc(k1, alloc);
   x1= b1->p.x;
   for (i= 0; i < n; i++)
     *x1++= 0;
   x= b->p.x;
   xe= x + b->wds;
   if (k&= 0x1f)
   {
     k1= 32 - k;
     z= 0;
     do
     {
       *x1++= *x << k | z;
       z= *x++ >> k1;
     }
     while (x < xe);
     if ((*x1= z))
       ++n1;
   }
   else
     do
       *x1++= *x++;
     while (x < xe);
   b1->wds= n1 - 1;
   Bfree(b, alloc);
   return b1;
 }
References b, Balloc(), Bfree(), Bigint::p, Bigint::wds, G3D::x, Bigint::x, and G3D::z.
Referenced by dtoa(), and my_strtod_int().
mult()
static Bigint* mult (Bigint * a, Bigint * b, Stack_alloc * alloc) static
Definition at line 914 of file dtoa.c.
 {
   Bigint *c;
   int k, wa, wb, wc;
   ULong *x, *xa, *xae, *xb, *xbe, *xc, *xc0;
   ULong y;
   ULLong carry, z;
   if (a->wds < b->wds)
   {
     c= a;
     a= b;
     b= c;
   }
   k= a->k;
   wa= a->wds;
   wb= b->wds;
   wc= wa + wb;
   if (wc > a->maxwds)
     k++;
   c= Balloc(k, alloc);
   for (x= c->p.x, xa= x + wc; x < xa; x++)
     *x= 0;
   xa= a->p.x;
   xae= xa + wa;
   xb= b->p.x;
   xbe= xb + wb;
   xc0= c->p.x;
   for (; xb < xbe; xc0++)
   {
     if ((y= *xb++))
     {
       x= xa;
       xc= xc0;
       carry= 0;
       do
       {
         z= *x++ * (ULLong)y + *xc + carry;
         carry= z >> 32;
         *xc++= (ULong) (z & FFFFFFFF);
       }
       while (x < xae);
       *xc= (ULong) carry;
     }
   }
   for (xc0= c->p.x, xc= xc0 + wc; wc > 0 && !*--xc; --wc) ;
   c->wds= wc;
   return c;
 }
References mpq::a, b, Balloc(), mpq::c, FFFFFFFF, G3D::x, G3D::y, and G3D::z.
Referenced by Player::ApplyRatingMod(), dtoa(), my_strtod_int(), pow5mult(), and boss_twinemperorsAI::SpellHit().
multadd()
static Bigint* multadd (Bigint * b, int m, int a, Stack_alloc * alloc) static
Definition at line 752 of file dtoa.c.
 {
   int i, wds;
   ULong *x;
   ULLong carry, y;
   Bigint *b1;
   wds= b->wds;
   x= b->p.x;
   i= 0;
   carry= a;
   do
   {
     y= *x * (ULLong)m + carry;
     carry= y >> 32;
     *x++= (ULong)(y & FFFFFFFF);
   }
   while (++i < wds);
   if (carry)
   {
     if (wds >= b->maxwds)
     {
       b1= Balloc(b->k+1, alloc);
       Bcopy(b1, b);
       Bfree(b, alloc);
       b= b1;
     }
     b->p.x[wds++]= (ULong) carry;
     b->wds= wds;
   }
   return b;
 }
References mpq::a, b, Balloc(), Bcopy, Bfree(), FFFFFFFF, G3D::x, and G3D::y.
Referenced by dtoa(), pow5mult(), and s2b().
my_atof()
double my_atof (const char * nptr)
Definition at line 474 of file dtoa.c.
 {
   int error;
   const char *end= nptr+65535;                  /* Should be enough */
   return (my_strtod(nptr, (char**) &end, &error));
 }
References error(), and my_strtod().
my_fcvt()
size_t my_fcvt (double x, int precision, char * to, my_bool * error)
Converts a given floating point number to a zero-terminated string representation using the 'f' format.
This function is a wrapper around dtoa() to do the same as sprintf(to, "%-.*f", precision, x), though the conversion is usually more precise. The only difference is in handling [-,+]infinity and nan values, in which case we print '0\0' to the output string and indicate an overflow.
Parameters
x the input floating point number.
precision the number of digits after the decimal point. All properties of sprintf() apply:
if the number of significant digits after the decimal point is less than precision, the resulting string is right-padded with zeros
if the precision is 0, no decimal point appears
if a decimal point appears, at least one digit appears before it
to pointer to the output buffer. The longest string which my_fcvt() can return is FLOATING_POINT_BUFFER bytes (including the terminating '\0').
error if not NULL, points to a location where the status of conversion is stored upon return. FALSE successful conversion TRUE the input number is [-,+]infinity or nan. The output string in this case is always '0'.
Returns
number of written characters (excluding terminating '\0')
Definition at line 89 of file dtoa.c.
 {
   int decpt, sign, len, i;
   char *res, *src, *end, *dst= to;
   char buf[DTOA_BUFF_SIZE];
   DBUG_ASSERT(precision >= 0 && precision < NOT_FIXED_DEC && to != NULL);
   res= dtoa(x, 5, precision, &decpt, &sign, &end, buf, sizeof(buf));
   if (decpt == DTOA_OVERFLOW)
   {
     dtoa_free(res, buf, sizeof(buf));
     *to++= '0';
     *to= '\0';
     if (error != NULL)
       *error= TRUE;
     return 1;
   }
   src= res;
   len= end - src;
   if (sign)
     *dst++= '-';
   if (decpt <= 0)
   {
     *dst++= '0';
     *dst++= '.';
     for (i= decpt; i < 0; i++)
       *dst++= '0';
   }
   for (i= 1; i <= len; i++)
   {
     *dst++= *src++;
     if (i == decpt && i < len)
       *dst++= '.';
   }
   while (i++ <= decpt)
     *dst++= '0';
   if (precision > 0)
   {
     if (len <= decpt)
       *dst++= '.';
     for (i= precision - max(0, (len - decpt)); i > 0; i--)
       *dst++= '0';
   }
   *dst= '\0';
   if (error != NULL)
     *error= FALSE;
   dtoa_free(res, buf, sizeof(buf));
   return dst - to;
 }
References DBUG_ASSERT, dtoa(), DTOA_BUFF_SIZE, dtoa_free(), DTOA_OVERFLOW, error(), FALSE, max, NOT_FIXED_DEC, NULL, G3D::sign(), TRUE, and G3D::x.
Referenced by fetch_float_with_conversion(), and process_dbl_arg().
my_gcvt()
size_t my_gcvt (double x, my_gcvt_arg_type type, int width, char * to, my_bool * error)
Converts a given floating point number to a zero-terminated string representation with a given field width using the 'e' format (aka scientific notation) or the 'f' one.
The format is chosen automatically to provide the most number of significant digits (and thus, precision) with a given field width. In many cases, the result is similar to that of sprintf(to, "%g", x) with a few notable differences:
the conversion is usually more precise than C library functions.
there is no 'precision' argument. instead, we specify the number of characters available for conversion (i.e. a field width).
the result never exceeds the specified field width. If the field is too short to contain even a rounded decimal representation, my_gcvt() indicates overflow and truncates the output string to the specified width.
float-type arguments are handled differently than double ones. For a float input number (i.e. when the 'type' argument is MY_GCVT_ARG_FLOAT) we deliberately limit the precision of conversion by FLT_DIG digits to avoid garbage past the significant digits.
unlike sprintf(), in cases where the 'e' format is preferred, we don't zero-pad the exponent to save space for significant digits. The '+' sign for a positive exponent does not appear for the same reason.
Parameters
x the input floating point number.
type is either MY_GCVT_ARG_FLOAT or MY_GCVT_ARG_DOUBLE. Specifies the type of the input number (see notes above).
width field width in characters. The minimal field width to hold any number representation (albeit rounded) is 7 characters ("-Ne-NNN").
to pointer to the output buffer. The result is always zero-terminated, and the longest returned string is thus 'width + 1' bytes.
error if not NULL, points to a location where the status of conversion is stored upon return. FALSE successful conversion TRUE the input number is [-,+]infinity or nan. The output string in this case is always '0'.
Returns
number of written characters (excluding terminating '\0')
Todo:
Check if it is possible and makes sense to do our own rounding on top of dtoa() instead of calling dtoa() twice in (rare) cases when the resulting string representation does not fit in the specified field width and we want to re-round the input number with fewer significant digits. Examples:
my_gcvt(-9e-3, ..., 4, ...); my_gcvt(-9e-3, ..., 2, ...); my_gcvt(1.87e-3, ..., 4, ...); my_gcvt(55, ..., 1, ...);
We do our best to minimize such cases by:
passing to dtoa() the field width as the number of significant digits
removing the sign of the number early (and decreasing the width before passing it to dtoa())
choosing the proper format to preserve the most number of significant digits.
Definition at line 212 of file dtoa.c.
 {
   int decpt, sign, len, exp_len;
   char *res, *src, *end, *dst= to, *dend= dst + width;
   char buf[DTOA_BUFF_SIZE];
   my_bool have_space, force_e_format;
   DBUG_ASSERT(width > 0 && to != NULL);
   /* We want to remove '-' from equations early */
   if (x < 0.)
     width--;
   res= dtoa(x, 4, type == MY_GCVT_ARG_DOUBLE ? width : min(width, FLT_DIG),
             &decpt, &sign, &end, buf, sizeof(buf));
   if (decpt == DTOA_OVERFLOW)
   {
     dtoa_free(res, buf, sizeof(buf));
     *to++= '0';
     *to= '\0';
     if (error != NULL)
       *error= TRUE;
     return 1;
   }
   if (error != NULL)
     *error= FALSE;
   src= res;
   len= end - res;
   /*
     Number of digits in the exponent from the 'e' conversion.
      The sign of the exponent is taken into account separetely, we don't need
      to count it here.
    */
   exp_len= 1 + (decpt >= 101 || decpt <= -99) + (decpt >= 11 || decpt <= -9);
   /*
      Do we have enough space for all digits in the 'f' format?
      Let 'len' be the number of significant digits returned by dtoa,
      and F be the length of the resulting decimal representation.
      Consider the following cases:
      1. decpt <= 0, i.e. we have "0.NNN" => F = len - decpt + 2
      2. 0 < decpt < len, i.e. we have "NNN.NNN" => F = len + 1
      3. len <= decpt, i.e. we have "NNN00" => F = decpt
   */
   have_space= (decpt <= 0 ? len - decpt + 2 :
                decpt > 0 && decpt < len ? len + 1 :
                decpt) <= width;
   /*
     The following is true when no significant digits can be placed with the
     specified field width using the 'f' format, and the 'e' format
     will not be truncated.
   */
   force_e_format= (decpt <= 0 && width <= 2 - decpt && width >= 3 + exp_len);
   /*
     Assume that we don't have enough space to place all significant digits in
     the 'f' format. We have to choose between the 'e' format and the 'f' one
     to keep as many significant digits as possible.
     Let E and F be the lengths of decimal representaion in the 'e' and 'f'
     formats, respectively. We want to use the 'f' format if, and only if F <= E.
     Consider the following cases:
     1. decpt <= 0.
        F = len - decpt + 2 (see above)
        E = len + (len > 1) + 1 + 1 (decpt <= -99) + (decpt <= -9) + 1
        ("N.NNe-MMM")
        (F <= E) <=> (len == 1 && decpt >= -1) || (len > 1 && decpt >= -2)
        We also need to ensure that if the 'f' format is chosen,
        the field width allows us to place at least one significant digit
        (i.e. width > 2 - decpt). If not, we prefer the 'e' format.
     2. 0 < decpt < len
        F = len + 1 (see above)
        E = len + 1 + 1 + ... ("N.NNeMMM")
        F is always less than E.
     3. len <= decpt <= width
        In this case we have enough space to represent the number in the 'f'
        format, so we prefer it with some exceptions.
     4. width < decpt
        The number cannot be represented in the 'f' format at all, always use
        the 'e' 'one.
   */
   if ((have_space ||
       /*
         Not enough space, let's see if the 'f' format provides the most number
         of significant digits.
       */
        ((decpt <= width && (decpt >= -1 || (decpt == -2 &&
                                             (len > 1 || !force_e_format)))) &&
          !force_e_format)) &&
        /*
          Use the 'e' format in some cases even if we have enough space for the
          'f' one. See comment for MAX_DECPT_FOR_F_FORMAT.
        */
       (!have_space || (decpt >= -MAX_DECPT_FOR_F_FORMAT + 1 &&
                        (decpt <= MAX_DECPT_FOR_F_FORMAT || len > decpt))))
   {
     /* 'f' format */
     int i;
     width-= (decpt < len) + (decpt <= 0 ? 1 - decpt : 0);
     /* Do we have to truncate any digits? */
     if (width < len)
     {
       if (width < decpt)
       {
         if (error != NULL)
           *error= TRUE;
         width= decpt;
       }
       /*
         We want to truncate (len - width) least significant digits after the
         decimal point. For this we are calling dtoa with mode=5, passing the
         number of significant digits = (len-decpt) - (len-width) = width-decpt
       */
       dtoa_free(res, buf, sizeof(buf));
       res= dtoa(x, 5, width - decpt, &decpt, &sign, &end, buf, sizeof(buf));
       src= res;
       len= end - res;
     }
     if (len == 0)
     {
       /* Underflow. Just print '0' and exit */
       *dst++= '0';
       goto end;
     }
     /*
       At this point we are sure we have enough space to put all digits
       returned by dtoa
     */
     if (sign && dst < dend)
       *dst++= '-';
     if (decpt <= 0)
     {
       if (dst < dend)
         *dst++= '0';
       if (len > 0 && dst < dend)
         *dst++= '.';
       for (; decpt < 0 && dst < dend; decpt++)
         *dst++= '0';
     }
     for (i= 1; i <= len && dst < dend; i++)
     {
       *dst++= *src++;
       if (i == decpt && i < len && dst < dend)
         *dst++= '.';
     }
     while (i++ <= decpt && dst < dend)
       *dst++= '0';
   }
   else
   {
     /* 'e' format */
     int decpt_sign= 0;
     if (--decpt < 0)
     {
       decpt= -decpt;
       width--;
       decpt_sign= 1;
     }
     width-= 1 + exp_len; /* eNNN */
     if (len > 1)
       width--;
     if (width <= 0)
     {
       /* Overflow */
       if (error != NULL)
         *error= TRUE;
       width= 0;
     }
     /* Do we have to truncate any digits? */
     if (width < len)
     {
       /* Yes, re-convert with a smaller width */
       dtoa_free(res, buf, sizeof(buf));
       res= dtoa(x, 4, width, &decpt, &sign, &end, buf, sizeof(buf));
       src= res;
       len= end - res;
       if (--decpt < 0)
         decpt= -decpt;
     }
     /*
       At this point we are sure we have enough space to put all digits
       returned by dtoa
     */
     if (sign && dst < dend)
       *dst++= '-';
     if (dst < dend)
       *dst++= *src++;
     if (len > 1 && dst < dend)
     {
       *dst++= '.';
       while (src < end && dst < dend)
         *dst++= *src++;
     }
     if (dst < dend)
       *dst++= 'e';
     if (decpt_sign && dst < dend)
       *dst++= '-';
     if (decpt >= 100 && dst < dend)
     {
       *dst++= decpt / 100 + '0';
       decpt%= 100;
       if (dst < dend)
         *dst++= decpt / 10 + '0';
     }
     else if (decpt >= 10 && dst < dend)
       *dst++= decpt / 10 + '0';
     if (dst < dend)
       *dst++= decpt % 10 + '0';
   }
 end:
   dtoa_free(res, buf, sizeof(buf));
   *dst= '\0';
   return dst - to;
 }
References DBUG_ASSERT, dtoa(), DTOA_BUFF_SIZE, dtoa_free(), DTOA_OVERFLOW, error(), FALSE, MAX_DECPT_FOR_F_FORMAT, min, MY_GCVT_ARG_DOUBLE, NULL, G3D::sign(), TRUE, width, and G3D::x.
Referenced by double2decimal(), fetch_float_with_conversion(), and process_dbl_arg().
my_strtod()
double my_strtod (const char * str, char ** end, int * error)
Converts string to double (string does not have to be zero-terminated)
This is a wrapper around dtoa's version of strtod().
Parameters
str input string
end address of a pointer to the first character after the input string. Upon return the pointer is set to point to the first rejected character.
error Upon return is set to EOVERFLOW in case of underflow or overflow.
Returns
The resulting double value. In case of underflow, 0.0 is returned. In case overflow, signed DBL_MAX is returned.
Definition at line 461 of file dtoa.c.
 {
   char buf[DTOA_BUFF_SIZE];
   double res;
   DBUG_ASSERT(end != NULL && ((str != NULL && *end != NULL) ||
                               (str == NULL && *end == NULL)) &&
               error != NULL);
   res= my_strtod_int(str, end, error, buf, sizeof(buf));
   return (*error == 0) ? res : (res < 0 ? -DBL_MAX : DBL_MAX);
 }
References DBL_MAX, DBUG_ASSERT, DTOA_BUFF_SIZE, error(), my_strtod_int(), and NULL.
Referenced by decimal2double(), getopt_double(), my_atof(), and my_strntod_8bit().
my_strtod_int()
static double my_strtod_int (const char * s00, char ** se, int * error, char * buf, size_t buf_size) static
Definition at line 1329 of file dtoa.c.
 {
   int scale;
   int bb2, bb5, bbe, bd2, bd5, bbbits, bs2, UNINIT_VAR(c), dsign,
      e, e1, esign, i, j, k, nd, nd0, nf, nz, nz0, sign;
   const char *s, *s0, *s1, *end = *se;
   double aadj, aadj1;
   U aadj2, adj, rv, rv0;
   Long L;
   ULong y, z;
   Bigint *bb, *bb1, *bd, *bd0, *bs, *delta;
 #ifdef SET_INEXACT
   int inexact, oldinexact;
 #endif
 #ifdef Honor_FLT_ROUNDS
   int rounding;
 #endif
   Stack_alloc alloc;
   *error= 0;
   alloc.begin= alloc.free= buf;
   alloc.end= buf + buf_size;
   memset(alloc.freelist, 0, sizeof(alloc.freelist));
   sign= nz0= nz= 0;
   dval(&rv)= 0.;
   for (s= s00; s < end; s++)
     switch (*s) {
     case '-':
       sign= 1;
       /* no break */
     case '+':
       s++;
       goto break2;
     case '\t':
     case '\n':
     case '\v':
     case '\f':
     case '\r':
     case ' ':
       continue;
     default:
       goto break2;
     }
  break2:
   if (s >= end)
     goto ret0;
   if (*s == '0')
   {
     nz0= 1;
     while (++s < end && *s == '0') ;
     if (s >= end)
       goto ret;
   }
   s0= s;
   y= z= 0;
   for (nd= nf= 0; s < end && (c= *s) >= '0' && c <= '9'; nd++, s++)
     if (nd < 9)
       y= 10*y + c - '0';
     else if (nd < 16)
       z= 10*z + c - '0';
   nd0= nd;
   if (s < end - 1 && c == '.')
   {
     c= *++s;
     if (!nd)
     {
       for (; s < end && c == '0'; c= *++s)
         nz++;
       if (s < end && c > '0' && c <= '9')
       {
         s0= s;
         nf+= nz;
         nz= 0;
         goto have_dig;
       }
       goto dig_done;
     }
     for (; s < end && c >= '0' && c <= '9'; c = *++s)
     {
  have_dig:
       nz++;
       if (c-= '0')
       {
         nf+= nz;
         for (i= 1; i < nz; i++)
           if (nd++ < 9)
             y*= 10;
           else if (nd <= DBL_DIG + 1)
             z*= 10;
         if (nd++ < 9)
           y= 10*y + c;
         else if (nd <= DBL_DIG + 1)
           z= 10*z + c;
         nz= 0;
       }
     }
   }
  dig_done:
   e= 0;
   if (s < end && (c == 'e' || c == 'E'))
   {
     if (!nd && !nz && !nz0)
       goto ret0;
     s00= s;
     esign= 0;
     if (++s < end)
       switch (c= *s) {
       case '-':
         esign= 1;
       case '+':
         c= *++s;
       }
     if (s < end && c >= '0' && c <= '9')
     {
       while (s < end && c == '0')
         c= *++s;
       if (s < end && c > '0' && c <= '9') {
         L= c - '0';
         s1= s;
         while (++s < end && (c= *s) >= '0' && c <= '9')
           L= 10*L + c - '0';
         if (s - s1 > 8 || L > 19999)
           /* Avoid confusion from exponents
            * so large that e might overflow.
            */
           e= 19999; /* safe for 16 bit ints */
         else
           e= (int)L;
         if (esign)
           e= -e;
       }
       else
         e= 0;
     }
     else
       s= s00;
   }
   if (!nd)
   {
     if (!nz && !nz0)
     {
  ret0:
       s= s00;
       sign= 0;
     }
     goto ret;
   }
   e1= e -= nf;
   /*
     Now we have nd0 digits, starting at s0, followed by a
     decimal point, followed by nd-nd0 digits.  The number we're
     after is the integer represented by those digits times
     10**e
    */
   if (!nd0)
     nd0= nd;
   k= nd < DBL_DIG + 1 ? nd : DBL_DIG + 1;
   dval(&rv)= y;
   if (k > 9)
   {
 #ifdef SET_INEXACT
     if (k > DBL_DIG)
       oldinexact = get_inexact();
 #endif
     dval(&rv)= tens[k - 9] * dval(&rv) + z;
   }
   bd0= 0;
   if (nd <= DBL_DIG
 #ifndef Honor_FLT_ROUNDS
     && Flt_Rounds == 1
 #endif
       )
   {
     if (!e)
       goto ret;
     if (e > 0)
     {
       if (e <= Ten_pmax)
       {
 #ifdef Honor_FLT_ROUNDS
         /* round correctly FLT_ROUNDS = 2 or 3 */
         if (sign)
         {
           rv.d= -rv.d;
           sign= 0;
         }
 #endif
         /* rv = */ rounded_product(dval(&rv), tens[e]);
         goto ret;
       }
       i= DBL_DIG - nd;
       if (e <= Ten_pmax + i)
       {
         /*
           A fancier test would sometimes let us do
           this for larger i values.
         */
 #ifdef Honor_FLT_ROUNDS
         /* round correctly FLT_ROUNDS = 2 or 3 */
         if (sign)
         {
           rv.d= -rv.d;
           sign= 0;
         }
 #endif
         e-= i;
         dval(&rv)*= tens[i];
         /* rv = */ rounded_product(dval(&rv), tens[e]);
         goto ret;
       }
     }
 #ifndef Inaccurate_Divide
     else if (e >= -Ten_pmax)
     {
 #ifdef Honor_FLT_ROUNDS
       /* round correctly FLT_ROUNDS = 2 or 3 */
       if (sign)
       {
         rv.d= -rv.d;
         sign= 0;
       }
 #endif
       /* rv = */ rounded_quotient(dval(&rv), tens[-e]);
       goto ret;
     }
 #endif
   }
   e1+= nd - k;
 #ifdef SET_INEXACT
   inexact= 1;
   if (k <= DBL_DIG)
     oldinexact= get_inexact();
 #endif
   scale= 0;
 #ifdef Honor_FLT_ROUNDS
   if ((rounding= Flt_Rounds) >= 2)
   {
     if (sign)
       rounding= rounding == 2 ? 0 : 2;
     else
       if (rounding != 2)
         rounding= 0;
   }
 #endif
   /* Get starting approximation = rv * 10**e1 */
   if (e1 > 0)
   {
     if ((i= e1 & 15))
       dval(&rv)*= tens[i];
     if (e1&= ~15)
     {
       if (e1 > DBL_MAX_10_EXP)
       {
  ovfl:
         *error= EOVERFLOW;
         /* Can't trust HUGE_VAL */
 #ifdef Honor_FLT_ROUNDS
         switch (rounding)
         {
         case 0: /* toward 0 */
         case 3: /* toward -infinity */
           word0(&rv)= Big0;
           word1(&rv)= Big1;
           break;
         default:
           word0(&rv)= Exp_mask;
           word1(&rv)= 0;
         }
 #else /*Honor_FLT_ROUNDS*/
         word0(&rv)= Exp_mask;
         word1(&rv)= 0;
 #endif /*Honor_FLT_ROUNDS*/
 #ifdef SET_INEXACT
         /* set overflow bit */
         dval(&rv0)= 1e300;
         dval(&rv0)*= dval(&rv0);
 #endif
         if (bd0)
           goto retfree;
         goto ret;
       }
       e1>>= 4;
       for(j= 0; e1 > 1; j++, e1>>= 1)
         if (e1 & 1)
           dval(&rv)*= bigtens[j];
     /* The last multiplication could overflow. */
       word0(&rv)-= P*Exp_msk1;
       dval(&rv)*= bigtens[j];
       if ((z= word0(&rv) & Exp_mask) > Exp_msk1 * (DBL_MAX_EXP + Bias - P))
         goto ovfl;
       if (z > Exp_msk1 * (DBL_MAX_EXP + Bias - 1 - P))
       {
         /* set to largest number (Can't trust DBL_MAX) */
         word0(&rv)= Big0;
         word1(&rv)= Big1;
       }
       else
         word0(&rv)+= P*Exp_msk1;
     }
   }
   else if (e1 < 0)
   {
     e1= -e1;
     if ((i= e1 & 15))
       dval(&rv)/= tens[i];
     if ((e1>>= 4))
     {
       if (e1 >= 1 << n_bigtens)
         goto undfl;
       if (e1 & Scale_Bit)
         scale= 2 * P;
       for(j= 0; e1 > 0; j++, e1>>= 1)
         if (e1 & 1)
           dval(&rv)*= tinytens[j];
       if (scale && (j = 2 * P + 1 - ((word0(&rv) & Exp_mask) >> Exp_shift)) > 0)
       {
         /* scaled rv is denormal; zap j low bits */
         if (j >= 32)
         {
           word1(&rv)= 0;
           if (j >= 53)
             word0(&rv)= (P + 2) * Exp_msk1;
           else
             word0(&rv)&= 0xffffffff << (j - 32);
         }
         else
           word1(&rv)&= 0xffffffff << j;
       }
       if (!dval(&rv))
       {
  undfl:
           dval(&rv)= 0.;
           if (bd0)
             goto retfree;
           goto ret;
       }
     }
   }
   /* Now the hard part -- adjusting rv to the correct value.*/
   /* Put digits into bd: true value = bd * 10^e */
   bd0= s2b(s0, nd0, nd, y, &alloc);
   for(;;)
   {
     bd= Balloc(bd0->k, &alloc);
     Bcopy(bd, bd0);
     bb= d2b(&rv, &bbe, &bbbits, &alloc);  /* rv = bb * 2^bbe */
     bs= i2b(1, &alloc);
     if (e >= 0)
     {
       bb2= bb5= 0;
       bd2= bd5= e;
     }
     else
     {
       bb2= bb5= -e;
       bd2= bd5= 0;
     }
     if (bbe >= 0)
       bb2+= bbe;
     else
       bd2-= bbe;
     bs2= bb2;
 #ifdef Honor_FLT_ROUNDS
     if (rounding != 1)
       bs2++;
 #endif
     j= bbe - scale;
     i= j + bbbits - 1;  /* logb(rv) */
     if (i < Emin)  /* denormal */
       j+= P - Emin;
     else
       j= P + 1 - bbbits;
     bb2+= j;
     bd2+= j;
     bd2+= scale;
     i= bb2 < bd2 ? bb2 : bd2;
     if (i > bs2)
       i= bs2;
     if (i > 0)
     {
       bb2-= i;
       bd2-= i;
       bs2-= i;
     }
     if (bb5 > 0)
     {
       bs= pow5mult(bs, bb5, &alloc);
       bb1= mult(bs, bb, &alloc);
       Bfree(bb, &alloc);
       bb= bb1;
     }
     if (bb2 > 0)
       bb= lshift(bb, bb2, &alloc);
     if (bd5 > 0)
       bd= pow5mult(bd, bd5, &alloc);
     if (bd2 > 0)
       bd= lshift(bd, bd2, &alloc);
     if (bs2 > 0)
       bs= lshift(bs, bs2, &alloc);
     delta= diff(bb, bd, &alloc);
     dsign= delta->sign;
     delta->sign= 0;
     i= cmp(delta, bs);
 #ifdef Honor_FLT_ROUNDS
     if (rounding != 1)
     {
       if (i < 0)
       {
         /* Error is less than an ulp */
         if (!delta->p.x[0] && delta->wds <= 1)
         {
           /* exact */
 #ifdef SET_INEXACT
           inexact= 0;
 #endif
           break;
         }
         if (rounding)
         {
           if (dsign)
           {
             adj.d= 1.;
             goto apply_adj;
           }
         }
         else if (!dsign)
         {
           adj.d= -1.;
           if (!word1(&rv) && !(word0(&rv) & Frac_mask))
           {
             y= word0(&rv) & Exp_mask;
             if (!scale || y > 2*P*Exp_msk1)
             {
               delta= lshift(delta, Log2P, &alloc);
               if (cmp(delta, bs) <= 0)
               adj.d= -0.5;
             }
           }
  apply_adj:
           if (scale && (y= word0(&rv) & Exp_mask) <= 2 * P * Exp_msk1)
             word0(&adj)+= (2 * P + 1) * Exp_msk1 - y;
           dval(&rv)+= adj.d * ulp(&rv);
         }
         break;
       }
       adj.d= ratio(delta, bs);
       if (adj.d < 1.)
         adj.d= 1.;
       if (adj.d <= 0x7ffffffe)
       {
         /* adj = rounding ? ceil(adj) : floor(adj); */
         y= adj.d;
         if (y != adj.d)
         {
           if (!((rounding >> 1) ^ dsign))
             y++;
           adj.d= y;
         }
       }
       if (scale && (y= word0(&rv) & Exp_mask) <= 2 * P * Exp_msk1)
         word0(&adj)+= (2 * P + 1) * Exp_msk1 - y;
       adj.d*= ulp(&rv);
       if (dsign)
         dval(&rv)+= adj.d;
       else
         dval(&rv)-= adj.d;
       goto cont;
     }
 #endif /*Honor_FLT_ROUNDS*/
     if (i < 0)
     {
       /*
         Error is less than half an ulp -- check for special case of mantissa
         a power of two.
       */
       if (dsign || word1(&rv) || word0(&rv) & Bndry_mask ||
           (word0(&rv) & Exp_mask) <= (2 * P + 1) * Exp_msk1)
       {
 #ifdef SET_INEXACT
         if (!delta->x[0] && delta->wds <= 1)
           inexact= 0;
 #endif
         break;
       }
       if (!delta->p.x[0] && delta->wds <= 1)
       {
         /* exact result */
 #ifdef SET_INEXACT
         inexact= 0;
 #endif
         break;
       }
       delta= lshift(delta, Log2P, &alloc);
       if (cmp(delta, bs) > 0)
         goto drop_down;
       break;
     }
     if (i == 0)
     {
       /* exactly half-way between */
       if (dsign)
       {
         if ((word0(&rv) & Bndry_mask1) == Bndry_mask1 &&
             word1(&rv) ==
             ((scale && (y = word0(&rv) & Exp_mask) <= 2 * P * Exp_msk1) ?
              (0xffffffff & (0xffffffff << (2*P+1-(y>>Exp_shift)))) :
              0xffffffff))
         {
           /*boundary case -- increment exponent*/
           word0(&rv)= (word0(&rv) & Exp_mask) + Exp_msk1;
           word1(&rv) = 0;
           dsign = 0;
           break;
         }
       }
       else if (!(word0(&rv) & Bndry_mask) && !word1(&rv))
       {
  drop_down:
         /* boundary case -- decrement exponent */
         if (scale)
         {
           L= word0(&rv) & Exp_mask;
           if (L <= (2 *P + 1) * Exp_msk1)
           {
             if (L > (P + 2) * Exp_msk1)
               /* round even ==> accept rv */
               break;
             /* rv = smallest denormal */
             goto undfl;
           }
         }
         L= (word0(&rv) & Exp_mask) - Exp_msk1;
         word0(&rv)= L | Bndry_mask1;
         word1(&rv)= 0xffffffff;
         break;
       }
       if (!(word1(&rv) & LSB))
         break;
       if (dsign)
         dval(&rv)+= ulp(&rv);
       else
       {
         dval(&rv)-= ulp(&rv);
         if (!dval(&rv))
           goto undfl;
       }
       dsign= 1 - dsign;
       break;
     }
     if ((aadj= ratio(delta, bs)) <= 2.)
     {
       if (dsign)
         aadj= aadj1= 1.;
       else if (word1(&rv) || word0(&rv) & Bndry_mask)
       {
         if (word1(&rv) == Tiny1 && !word0(&rv))
           goto undfl;
         aadj= 1.;
         aadj1= -1.;
       }
       else
       {
         /* special case -- power of FLT_RADIX to be rounded down... */
         if (aadj < 2. / FLT_RADIX)
           aadj= 1. / FLT_RADIX;
         else
           aadj*= 0.5;
         aadj1= -aadj;
       }
     }
     else
     {
       aadj*= 0.5;
       aadj1= dsign ? aadj : -aadj;
 #ifdef Check_FLT_ROUNDS
       switch (Rounding)
       {
       case 2: /* towards +infinity */
         aadj1-= 0.5;
         break;
       case 0: /* towards 0 */
       case 3: /* towards -infinity */
         aadj1+= 0.5;
       }
 #else
       if (Flt_Rounds == 0)
         aadj1+= 0.5;
 #endif /*Check_FLT_ROUNDS*/
     }
     y= word0(&rv) & Exp_mask;
     /* Check for overflow */
     if (y == Exp_msk1 * (DBL_MAX_EXP + Bias - 1))
     {
       dval(&rv0)= dval(&rv);
       word0(&rv)-= P * Exp_msk1;
       adj.d= aadj1 * ulp(&rv);
       dval(&rv)+= adj.d;
       if ((word0(&rv) & Exp_mask) >= Exp_msk1 * (DBL_MAX_EXP + Bias - P))
       {
         if (word0(&rv0) == Big0 && word1(&rv0) == Big1)
           goto ovfl;
         word0(&rv)= Big0;
         word1(&rv)= Big1;
         goto cont;
       }
       else
         word0(&rv)+= P * Exp_msk1;
     }
     else
     {
       if (scale && y <= 2 * P * Exp_msk1)
       {
         if (aadj <= 0x7fffffff)
         {
           if ((z= (ULong) aadj) <= 0)
             z= 1;
           aadj= z;
           aadj1= dsign ? aadj : -aadj;
         }
         dval(&aadj2) = aadj1;
         word0(&aadj2)+= (2 * P + 1) * Exp_msk1 - y;
         aadj1= dval(&aadj2);
         adj.d= aadj1 * ulp(&rv);
         dval(&rv)+= adj.d;
         if (rv.d == 0.)
           goto undfl;
       }
       else
       {
         adj.d= aadj1 * ulp(&rv);
         dval(&rv)+= adj.d;
       }
     }
     z= word0(&rv) & Exp_mask;
 #ifndef SET_INEXACT
     if (!scale)
       if (y == z)
       {
         /* Can we stop now? */
         L= (Long)aadj;
         aadj-= L;
         /* The tolerances below are conservative. */
         if (dsign || word1(&rv) || word0(&rv) & Bndry_mask)
         {
           if (aadj < .4999999 || aadj > .5000001)
             break;
         }
         else if (aadj < .4999999 / FLT_RADIX)
           break;
       }
 #endif
  cont:
     Bfree(bb, &alloc);
     Bfree(bd, &alloc);
     Bfree(bs, &alloc);
     Bfree(delta, &alloc);
   }
 #ifdef SET_INEXACT
   if (inexact)
   {
     if (!oldinexact)
     {
       word0(&rv0)= Exp_1 + (70 << Exp_shift);
       word1(&rv0)= 0;
       dval(&rv0)+= 1.;
     }
   }
   else if (!oldinexact)
     clear_inexact();
 #endif
   if (scale)
   {
     word0(&rv0)= Exp_1 - 2 * P * Exp_msk1;
     word1(&rv0)= 0;
     dval(&rv)*= dval(&rv0);
   }
 #ifdef SET_INEXACT
   if (inexact && !(word0(&rv) & Exp_mask))
   {
     /* set underflow bit */
     dval(&rv0)= 1e-300;
     dval(&rv0)*= dval(&rv0);
   }
 #endif
  retfree:
   Bfree(bb, &alloc);
   Bfree(bd, &alloc);
   Bfree(bs, &alloc);
   Bfree(bd0, &alloc);
   Bfree(delta, &alloc);
  ret:
   *se= (char *)s;
   return sign ? -dval(&rv) : dval(&rv);
 }
References Balloc(), Bcopy, Stack_alloc::begin, Bfree(), Bias, Big0, Big1, bigtens, Bndry_mask, Bndry_mask1, mpq::c, cmp(), U::d, d2b(), diff(), dval, Emin, Stack_alloc::end, endif(), EOVERFLOW, error(), Exp_1, Exp_mask, Exp_msk1, Exp_shift, Flt_Rounds, Frac_mask, Stack_alloc::free, Stack_alloc::freelist, i2b(), Bigint::k, Log2P, LSB, lshift(), memset, mult(), n_bigtens, P, Bigint::p, pow5mult(), ratio(), ret, rounded_product, rounded_quotient, Rounding, s2b(), Scale_Bit, G3D::sign(), Bigint::sign, Ten_pmax, tens, Tiny1, tinytens, ulp(), UNINIT_VAR, Bigint::wds, word0, word1, Bigint::x, G3D::y, and G3D::z.
Referenced by my_strtod().
pow5mult()
static Bigint* pow5mult (Bigint * b, int k, Stack_alloc * alloc) static
Definition at line 1006 of file dtoa.c.
 {
   Bigint *b1, *p5, *p51;
   int i;
   static int p05[3]= { 5, 25, 125 };
   if ((i= k & 3))
     b= multadd(b, p05[i-1], 0, alloc);
   if (!(k>>= 2))
     return b;
   p5= p5_a;
   for (;;)
   {
     if (k & 1)
     {
       b1= mult(b, p5, alloc);
       Bfree(b, alloc);
       b= b1;
     }
     if (!(k>>= 1))
       break;
     /* Calculate next power of 5 */
     if (p5 < p5_a + P5A_MAX)
       ++p5;
     else if (p5 == p5_a + P5A_MAX)
       p5= mult(p5, p5, alloc);
     else
     {
       p51= mult(p5, p5, alloc);
       Bfree(p5, alloc);
       p5= p51;
     }
   }
   return b;
 }
References b, Bfree(), mult(), multadd(), p5_a, and P5A_MAX.
Referenced by dtoa(), and my_strtod_int().
quorem()
static int quorem (Bigint * b, Bigint * S) static
Definition at line 2041 of file dtoa.c.
 {
   int n;
   ULong *bx, *bxe, q, *sx, *sxe;
   ULLong borrow, carry, y, ys;
   n= S->wds;
   if (b->wds < n)
     return 0;
   sx= S->p.x;
   sxe= sx + --n;
   bx= b->p.x;
   bxe= bx + n;
   q= *bxe / (*sxe + 1);  /* ensure q <= true quotient */
   if (q)
   {
     borrow= 0;
     carry= 0;
     do
     {
       ys= *sx++ * (ULLong)q + carry;
       carry= ys >> 32;
       y= *bx - (ys & FFFFFFFF) - borrow;
       borrow= y >> 32 & (ULong)1;
       *bx++= (ULong) (y & FFFFFFFF);
     }
     while (sx <= sxe);
     if (!*bxe)
     {
       bx= b->p.x;
       while (--bxe > bx && !*bxe)
         --n;
       b->wds= n;
     }
   }
   if (cmp(b, S) >= 0)
   {
     q++;
     borrow= 0;
     carry= 0;
     bx= b->p.x;
     sx= S->p.x;
     do
     {
       ys= *sx++ + carry;
       carry= ys >> 32;
       y= *bx - (ys & FFFFFFFF) - borrow;
       borrow= y >> 32 & (ULong)1;
       *bx++= (ULong) (y & FFFFFFFF);
     }
     while (sx <= sxe);
     bx= b->p.x;
     bxe= bx + n;
     if (!*bxe)
     {
       while (--bxe > bx && !*bxe)
         --n;
       b->wds= n;
     }
   }
   return q;
 }
References b, cmp(), FFFFFFFF, Bigint::p, Bigint::wds, Bigint::x, and G3D::y.
Referenced by dtoa().
ratio()
static double ratio (Bigint * a, Bigint * b) static
Definition at line 1263 of file dtoa.c.
 {
   U da, db;
   int k, ka, kb;
   dval(&da)= b2d(a, &ka);
   dval(&db)= b2d(b, &kb);
   k= ka - kb + 32*(a->wds - b->wds);
   if (k > 0)
     word0(&da)+= k*Exp_msk1;
   else
   {
     k= -k;
     word0(&db)+= k*Exp_msk1;
   }
   return dval(&da) / dval(&db);
 }
References mpq::a, b, b2d(), dval, Exp_msk1, and word0.
Referenced by Spell::EffectKnockBack(), my_strtod_int(), and prof_leakcheck().
s2b()
static Bigint* s2b (const char * s, int nd0, int nd, ULong y9, Stack_alloc * alloc) static
Definition at line 786 of file dtoa.c.
 {
   Bigint *b;
   int i, k;
   Long x, y;
   x= (nd + 8) / 9;
   for (k= 0, y= 1; x > y; y <<= 1, k++) ;
   b= Balloc(k, alloc);
   b->p.x[0]= y9;
   b->wds= 1;
   i= 9;
   if (9 < nd0)
   {
     s+= 9;
     do
       b= multadd(b, 10, *s++ - '0', alloc);
     while (++i < nd0);
     s++;
   }
   else
     s+= 10;
   for(; i < nd; i++)
     b= multadd(b, 10, *s++ - '0', alloc);
   return b;
 }
References b, Balloc(), multadd(), G3D::x, and G3D::y.
Referenced by my_strtod_int().
ulp()
static double ulp (U * x) static
Definition at line 1162 of file dtoa.c.
 {
   register Long L;
   U u;
   L= (word0(x) & Exp_mask) - (P - 1)*Exp_msk1;
   word0(&u) = L;
   word1(&u) = 0;
   return dval(&u);
 }
References dval, Exp_mask, Exp_msk1, P, word0, word1, and G3D::x.
Referenced by my_strtod_int().
Variable Documentation
bigtens
const double bigtens[] = { 1e16, 1e32, 1e64, 1e128, 1e256 } static
Definition at line 1288 of file dtoa.c.
Referenced by dtoa(), and my_strtod_int().
p5_a
Bigint p5_a[] static
Initial value:
=
{
  { { powers5 }, 1, 1, 0, 1 },
  { { powers5 + 1 }, 1, 1, 0, 1 },
  { { powers5 + 2 }, 1, 2, 0, 2 },
  { { powers5 + 4 }, 2, 3, 0, 3 },
  { { powers5 + 7 }, 3, 5, 0, 5 },
  { { powers5 + 12 }, 4, 10, 0, 10 },
  { { powers5 + 22 }, 5, 19, 0, 19 }
}
Definition at line 992 of file dtoa.c.
Referenced by pow5mult().
powers5
ULong powers5[] static
Initial value:
=
{
  625UL,
  390625UL,
  2264035265UL, 35UL,
  2242703233UL, 762134875UL,  1262UL,
  3211403009UL, 1849224548UL, 3668416493UL, 3913284084UL, 1593091UL,
  781532673UL,  64985353UL,   253049085UL,  594863151UL,  3553621484UL,
  3288652808UL, 3167596762UL, 2788392729UL, 3911132675UL, 590UL,
  2553183233UL, 3201533787UL, 3638140786UL, 303378311UL, 1809731782UL,
  3477761648UL, 3583367183UL, 649228654UL, 2915460784UL, 487929380UL,
  1011012442UL, 1677677582UL, 3428152256UL, 1710878487UL, 1438394610UL,
  2161952759UL, 4100910556UL, 1608314830UL, 349175UL
}
Definition at line 970 of file dtoa.c.
tens
const double tens[] static
Initial value:
=
{
  1e0, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9,
  1e10, 1e11, 1e12, 1e13, 1e14, 1e15, 1e16, 1e17, 1e18, 1e19,
  1e20, 1e21, 1e22
}
Definition at line 1281 of file dtoa.c.
Referenced by dtoa(), and my_strtod_int().
tinytens
const double tinytens[] static
Initial value:
=
{ 1e-16, 1e-32, 1e-64, 1e-128,
  9007199254740992.*9007199254740992.e-256
}
Definition at line 1289 of file dtoa.c.
Referenced by my_strtod_int().