Azerotcore-wotlk: go_ulduar_pure_saronite_deposit Class Reference
go_ulduar_pure_saronite_deposit Class Reference
Public Member Functions
go_ulduar_pure_saronite_deposit ()
bool OnGossipHello (Player *plr, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 677 of file boss_general_vezax.cpp.
Constructor & Destructor Documentation
go_ulduar_pure_saronite_deposit()
go_ulduar_pure_saronite_deposit::go_ulduar_pure_saronite_deposit () inline
Definition at line 680 of file boss_general_vezax.cpp.
 : GameObjectScript("go_ulduar_pure_saronite_deposit") { }
Member Function Documentation
OnGossipHello()
bool go_ulduar_pure_saronite_deposit::OnGossipHello (Player * plr, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 682 of file boss_general_vezax.cpp.
     {
         if (plr->IsGameMaster())
             return false;
         if (InstanceScript* pInstance = go->GetInstanceScript())
             if (pInstance->GetData(TYPE_XT002) != DONE && pInstance->GetData(TYPE_MIMIRON) != DONE && pInstance->GetData(TYPE_THORIM) != DONE && pInstance->GetData(TYPE_FREYA) != DONE && pInstance->GetData(TYPE_HODIR) != DONE)
             {
                 std::string accountName;
                 AccountMgr::GetName(plr->GetSession()->GetAccountId(), accountName);
                 sBan->BanAccount(accountName, "0s", "Tele hack", "Server");
                 return true;
             }
         return false;
     }
References DONE, WorldSession::GetAccountId(), WorldObject::GetInstanceScript(), AccountMgr::GetName(), Player::GetSession(), Player::IsGameMaster(), sBan, TYPE_FREYA, TYPE_HODIR, TYPE_MIMIRON, TYPE_THORIM, and TYPE_XT002.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp