Azerotcore-wotlk: PreparedStatementTask Class Reference
PreparedStatementTask Class Reference
#include <PreparedStatement.h>
Public Member Functions
PreparedStatementTask (PreparedStatementBase *stmt, bool async=false)
~PreparedStatementTask ()
bool Execute () override
PreparedQueryResultFuture GetFuture ()
Public Member Functions inherited from SQLOperation
SQLOperation ()
virtual ~SQLOperation ()
virtual int call ()
virtual void SetConnection (MySQLConnection *con)
Protected Attributes
PreparedStatementBase * m_stmt
bool m_has_result
PreparedQueryResultPromise * m_result
Additional Inherited Members
Public Attributes inherited from SQLOperation
MySQLConnection * m_conn
Detailed Description
Definition at line 115 of file PreparedStatement.h.
Constructor & Destructor Documentation
PreparedStatementTask()
PreparedStatementTask::PreparedStatementTask (PreparedStatementBase * stmt, bool async = false)
Definition at line 123 of file PreparedStatement.cpp.
                                                                                     :
 m_stmt(stmt), m_result(nullptr)
 {
     m_has_result = async; // If it's async, then there's a result
     if (async)
         m_result = new PreparedQueryResultPromise();
 }
References m_has_result, and m_result.
~PreparedStatementTask()
PreparedStatementTask::~PreparedStatementTask ()
Definition at line 131 of file PreparedStatement.cpp.
 {
     delete m_stmt;
     if (m_has_result && m_result != nullptr)
         delete m_result;
 }
References m_has_result, m_result, and m_stmt.
Member Function Documentation
Execute()
bool PreparedStatementTask::Execute () override virtual
Implements SQLOperation.
Definition at line 138 of file PreparedStatement.cpp.
 {
     if (m_has_result)
     {
         PreparedResultSet* result = m_conn->Query(m_stmt);
         if (!result || !result->GetRowCount())
         {
             delete result;
             m_result->set_value(PreparedQueryResult(nullptr));
             return false;
         }
         m_result->set_value(PreparedQueryResult(result));
         return true;
     }
     return m_conn->Execute(m_stmt);
 }
References MySQLConnection::Execute(), PreparedResultSet::GetRowCount(), SQLOperation::m_conn, m_has_result, m_result, m_stmt, and MySQLConnection::Query().
GetFuture()
PreparedQueryResultFuture PreparedStatementTask::GetFuture () inline
Definition at line 122 of file PreparedStatement.h.
 { return m_result->get_future(); }
Referenced by DatabaseWorkerPool< T >::AsyncQuery().
Member Data Documentation
m_has_result
bool PreparedStatementTask::m_has_result protected
Definition at line 126 of file PreparedStatement.h.
Referenced by Execute(), PreparedStatementTask(), and ~PreparedStatementTask().
m_result
PreparedQueryResultPromise* PreparedStatementTask::m_result protected
Definition at line 127 of file PreparedStatement.h.
Referenced by Execute(), PreparedStatementTask(), and ~PreparedStatementTask().
m_stmt
PreparedStatementBase* PreparedStatementTask::m_stmt protected
Definition at line 125 of file PreparedStatement.h.
Referenced by Execute(), and ~PreparedStatementTask().
The documentation for this class was generated from the following files:
src/server/database/Database/PreparedStatement.h
src/server/database/Database/PreparedStatement.cpp