Azerotcore-wotlk: src/server/authserver/Main.cpp File Reference
Main.cpp File Reference
Authentication Server main program.
#include "AppenderDB.h"
#include "AuthSocketMgr.h"
#include "Banner.h"
#include "Common.h"
#include "Config.h"
#include "DatabaseEnv.h"
#include "DatabaseLoader.h"
#include "DeadlineTimer.h"
#include "GitRevision.h"
#include "IPLocation.h"
#include "Log.h"
#include "IoContext.h"
#include "MySQLThreading.h"
#include "ProcessPriority.h"
#include "RealmList.h"
#include "SecretMgr.h"
#include "SharedDefines.h"
#include "Util.h"
#include <boost/asio/signal_set.hpp>
#include <boost/version.hpp>
#include <csignal>
#include <openssl/crypto.h>
#include <openssl/opensslv.h>
Macros
#define _ACORE_REALM_CONFIG "authserver.conf"
Functions
bool StartDB ()
Initialize connection to the database.
void StopDB ()
Close the connection to the database.
void SignalHandler (std::weak_ptr< Acore::Asio::IoContext > ioContextRef, boost::system::error_code const &error, int signalNumber)
void KeepDatabaseAliveHandler (std::weak_ptr< Acore::Asio::DeadlineTimer > dbPingTimerRef, int32 dbPingInterval, boost::system::error_code const &error)
void BanExpiryHandler (std::weak_ptr< Acore::Asio::DeadlineTimer > banExpiryCheckTimerRef, int32 banExpiryCheckInterval, boost::system::error_code const &error)
void usage (const char *prog)
Print out the usage string for this program on the console.
int main (int argc, char **argv)
Launch the auth server.
Detailed Description
Authentication Server main program.
This file contains the main program for the authentication server
Definition in file Main.cpp.
Macro Definition Documentation
_ACORE_REALM_CONFIG
#define _ACORE_REALM_CONFIG "authserver.conf"
Definition at line 51 of file Main.cpp.
Function Documentation
BanExpiryHandler()
void BanExpiryHandler (std::weak_ptr< Acore::Asio::DeadlineTimer > banExpiryCheckTimerRef, int32 banExpiryCheckInterval, boost::system::error_code const & error)
Definition at line 258 of file Main.cpp.
 {
     if (!error)
     {
         if (std::shared_ptr<Acore::Asio::DeadlineTimer> banExpiryCheckTimer = banExpiryCheckTimerRef.lock())
         {
             LoginDatabase.Execute(LoginDatabase.GetPreparedStatement(LOGIN_DEL_EXPIRED_IP_BANS));
             LoginDatabase.Execute(LoginDatabase.GetPreparedStatement(LOGIN_UPD_EXPIRED_ACCOUNT_BANS));
             banExpiryCheckTimer->expires_from_now(boost::posix_time::seconds(banExpiryCheckInterval));
             banExpiryCheckTimer->async_wait(std::bind(&BanExpiryHandler, banExpiryCheckTimerRef, banExpiryCheckInterval, std::placeholders::_1));
         }
     }
 }
References error(), LOGIN_DEL_EXPIRED_IP_BANS, LOGIN_UPD_EXPIRED_ACCOUNT_BANS, LoginDatabase, and G3D::units::seconds().
Referenced by main().
KeepDatabaseAliveHandler()
void KeepDatabaseAliveHandler (std::weak_ptr< Acore::Asio::DeadlineTimer > dbPingTimerRef, int32 dbPingInterval, boost::system::error_code const & error)
Definition at line 243 of file Main.cpp.
 {
     if (!error)
     {
         if (std::shared_ptr<Acore::Asio::DeadlineTimer> dbPingTimer = dbPingTimerRef.lock())
         {
             LOG_INFO("server.authserver", "Ping MySQL to keep connection alive");
             LoginDatabase.KeepAlive();
             dbPingTimer->expires_from_now(boost::posix_time::minutes(dbPingInterval));
             dbPingTimer->async_wait(std::bind(&KeepDatabaseAliveHandler, dbPingTimerRef, dbPingInterval, std::placeholders::_1));
         }
     }
 }
References error(), LOG_INFO, LoginDatabase, and G3D::units::minutes().
Referenced by main().
main()
int main (int argc, char ** argv)
Launch the auth server.
Definition at line 70 of file Main.cpp.
 {
     Acore::Impl::CurrentServerProcessHolder::_type = SERVER_PROCESS_AUTHSERVER;
     signal(SIGABRT, &Acore::AbortHandler);
     // Command line parsing to get the configuration file name
     std::string configFile = sConfigMgr->GetConfigPath() + std::string(_ACORE_REALM_CONFIG);
     int count = 1;
     while (count < argc)
     {
         if (strcmp(argv[count], "-c") == 0)
         {
             if (++count >= argc)
             {
                 printf("Runtime-Error: -c option requires an input argument\n");
                 usage(argv[0]);
                 return 1;
             }
             else
                 configFile = argv[count];
         }
         ++count;
     }
     // Add file and args in config
     sConfigMgr->Configure(configFile, std::vector<std::string>(argv, argv + argc));
     if (!sConfigMgr->LoadAppConfigs())
         return 1;
     // Init logging
     sLog->RegisterAppender<AppenderDB>();
     sLog->Initialize();
     Acore::Banner::Show("authserver",
         [](std::string_view text)
         {
             FMT_LOG_INFO("server.authserver", text);
         },
         []()
         {
             FMT_LOG_INFO("server.authserver", "> Using configuration file       {}", sConfigMgr->GetFilename());
             FMT_LOG_INFO("server.authserver", "> Using SSL version:             {} (library: {})", OPENSSL_VERSION_TEXT, SSLeay_version(SSLEAY_VERSION));
             FMT_LOG_INFO("server.authserver", "> Using Boost version:           {}.{}.{}", BOOST_VERSION / 100000, BOOST_VERSION / 100 % 1000, BOOST_VERSION % 100);
         });
     // authserver PID file creation
     std::string pidFile = sConfigMgr->GetOption<std::string>("PidFile", "");
     if (!pidFile.empty())
     {
         if (uint32 pid = CreatePIDFile(pidFile))
             LOG_INFO("server.authserver", "Daemon PID: %u\n", pid); // outError for red color in console
         else
         {
             LOG_ERROR("server.authserver", "Cannot create PID file %s (possible error: permission)\n", pidFile.c_str());
             return 1;
         }
     }
     // Initialize the database connection
     if (!StartDB())
         return 1;
     sSecretMgr->Initialize();
     // Load IP Location Database
     sIPLocation->Load();
     std::shared_ptr<void> dbHandle(nullptr, [](void*) { StopDB(); });
     std::shared_ptr<Acore::Asio::IoContext> ioContext = std::make_shared<Acore::Asio::IoContext>();
     // Get the list of realms for the server
     sRealmList->Initialize(*ioContext, sConfigMgr->GetOption<int32>("RealmsStateUpdateDelay", 20));
     std::shared_ptr<void> sRealmListHandle(nullptr, [](void*) { sRealmList->Close(); });
     if (sRealmList->GetRealms().empty())
     {
         LOG_ERROR("server.authserver", "No valid realms specified.");
         return 1;
     }
     // Start the listening port (acceptor) for auth connections
     int32 port = sConfigMgr->GetOption<int32>("RealmServerPort", 3724);
     if (port < 0 || port > 0xFFFF)
     {
         LOG_ERROR("server.authserver", "Specified port out of allowed range (1-65535)");
         return 1;
     }
     std::string bindIp = sConfigMgr->GetOption<std::string>("BindIP", "0.0.0.0");
     if (!sAuthSocketMgr.StartNetwork(*ioContext, bindIp, port))
     {
         LOG_ERROR("server.authserver", "Failed to initialize network");
         return 1;
     }
     std::shared_ptr<void> sAuthSocketMgrHandle(nullptr, [](void*) { sAuthSocketMgr.StopNetwork(); });
     // Set signal handlers
     boost::asio::signal_set signals(*ioContext, SIGINT, SIGTERM);
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     signals.add(SIGBREAK);
 #endif
     signals.async_wait(std::bind(&SignalHandler, std::weak_ptr<Acore::Asio::IoContext>(ioContext), std::placeholders::_1, std::placeholders::_2));
     // Set process priority according to configuration settings
     SetProcessPriority("server.authserver", sConfigMgr->GetOption<int32>(CONFIG_PROCESSOR_AFFINITY, 0), sConfigMgr->GetOption<bool>(CONFIG_HIGH_PRIORITY, false));
     // Enabled a timed callback for handling the database keep alive ping
     int32 dbPingInterval = sConfigMgr->GetOption<int32>("MaxPingTime", 30);
     std::shared_ptr<Acore::Asio::DeadlineTimer> dbPingTimer = std::make_shared<Acore::Asio::DeadlineTimer>(*ioContext);
     dbPingTimer->expires_from_now(boost::posix_time::minutes(dbPingInterval));
     dbPingTimer->async_wait(std::bind(&KeepDatabaseAliveHandler, std::weak_ptr<Acore::Asio::DeadlineTimer>(dbPingTimer), dbPingInterval, std::placeholders::_1));
     int32 banExpiryCheckInterval = sConfigMgr->GetOption<int32>("BanExpiryCheckInterval", 60);
     std::shared_ptr<Acore::Asio::DeadlineTimer> banExpiryCheckTimer = std::make_shared<Acore::Asio::DeadlineTimer>(*ioContext);
     banExpiryCheckTimer->expires_from_now(boost::posix_time::seconds(banExpiryCheckInterval));
     banExpiryCheckTimer->async_wait(std::bind(&BanExpiryHandler, std::weak_ptr<Acore::Asio::DeadlineTimer>(banExpiryCheckTimer), banExpiryCheckInterval, std::placeholders::_1));
     // Start the io service worker loop
     ioContext->run();
     banExpiryCheckTimer->cancel();
     dbPingTimer->cancel();
     LOG_INFO("server.authserver", "Halting process...");
     signals.cancel();
     return 0;
 }
References _ACORE_REALM_CONFIG, Acore::Impl::CurrentServerProcessHolder::_type, Acore::AbortHandler(), BanExpiryHandler(), CONFIG_HIGH_PRIORITY, CONFIG_PROCESSOR_AFFINITY, count(), CreatePIDFile(), FMT_LOG_INFO, KeepDatabaseAliveHandler(), LOG_ERROR, LOG_INFO, G3D::units::minutes(), printf(), sAuthSocketMgr, sConfigMgr, G3D::units::seconds(), SERVER_PROCESS_AUTHSERVER, SetProcessPriority(), Acore::Banner::Show(), SignalHandler(), sIPLocation, sLog, sRealmList, sSecretMgr, StartDB(), StopDB(), and usage().
SignalHandler()
void SignalHandler (std::weak_ptr< Acore::Asio::IoContext > ioContextRef, boost::system::error_code const & error, int signalNumber)
Definition at line 232 of file Main.cpp.
 {
     if (!error)
     {
         if (std::shared_ptr<Acore::Asio::IoContext> ioContext = ioContextRef.lock())
         {
             ioContext->stop();
         }
     }
 }
References error().
Referenced by main().
StartDB()
bool StartDB ()
Initialize connection to the database.
Initialize connection to the databases.
Get the realm Id from the configuration file
Clean the database before starting
Insert version info into DB
Definition at line 206 of file Main.cpp.
 {
     MySQL::Library_Init();
     // Load databases
     // NOTE: While authserver is singlethreaded you should keep synch_threads == 1.
     // Increasing it is just silly since only 1 will be used ever.
     DatabaseLoader loader("server.authserver");
     loader
         .AddDatabase(LoginDatabase, "Login");
     if (!loader.Load())
         return false;
     LOG_INFO("server.authserver", "Started auth database connection pool.");
     sLog->SetRealmId(0); // Enables DB appenders when realm is set.
     return true;
 }
References DatabaseLoader::AddDatabase(), MySQL::Library_Init(), DatabaseLoader::Load(), LOG_INFO, LoginDatabase, and sLog.
Referenced by main().
StopDB()
void StopDB ()
Close the connection to the database.
Definition at line 226 of file Main.cpp.
 {
     LoginDatabase.Close();
     MySQL::Library_End();
 }
References MySQL::Library_End(), and LoginDatabase.
Referenced by main().
usage()
void usage (const char * prog)
Print out the usage string for this program on the console.
Definition at line 63 of file Main.cpp.
 {
     LOG_INFO("server.authserver", "Usage: \n %s [<options>]\n"
         "    -c config_file           use config_file as configuration file\n\r", prog);
 }
References LOG_INFO, and prog.
Referenced by main().