Azerotcore-wotlk: CharmInfo Struct Reference
CharmInfo Struct Reference
#include <Unit.h>
Public Member Functions
CharmInfo (Unit *unit)
~CharmInfo ()
void RestoreState ()
uint32 GetPetNumber () const
void SetPetNumber (uint32 petnumber, bool statwindow)
void SetCommandState (CommandStates st)
CommandStates GetCommandState () const
bool HasCommandState (CommandStates state) const
void InitPossessCreateSpells ()
void InitCharmCreateSpells ()
void InitPetActionBar ()
void InitEmptyActionBar (bool withAttack=true)
bool AddSpellToActionBar (SpellInfo const *spellInfo, ActiveStates newstate=ACT_DECIDE)
bool RemoveSpellFromActionBar (uint32 spell_id)
void LoadPetActionBar (const std::string &data)
void BuildActionBar (WorldPacket *data)
void SetSpellAutocast (SpellInfo const *spellInfo, bool state)
void SetActionBar (uint8 index, uint32 spellOrAction, ActiveStates type)
UnitActionBarEntry const * GetActionBarEntry (uint8 index) const
void ToggleCreatureAutocast (SpellInfo const *spellInfo, bool apply)
CharmSpellInfo * GetCharmSpell (uint8 index)
GlobalCooldownMgr & GetGlobalCooldownMgr ()
void SetIsCommandAttack (bool val)
bool IsCommandAttack ()
void SetIsCommandFollow (bool val)
bool IsCommandFollow ()
void SetIsAtStay (bool val)
bool IsAtStay ()
void SetIsFollowing (bool val)
bool IsFollowing ()
void SetIsReturning (bool val)
bool IsReturning ()
void SaveStayPosition (bool atCurrentPos)
void GetStayPosition (float &x, float &y, float &z)
void RemoveStayPosition ()
bool HasStayPosition ()
void SetForcedSpell (uint32 id)
int32 GetForcedSpell ()
void SetForcedTargetGUID (ObjectGuid guid=ObjectGuid::Empty)
ObjectGuid GetForcedTarget ()
void SetPlayerReactState (ReactStates s)
ReactStates GetPlayerReactState () const
Private Attributes
Unit * _unit
UnitActionBarEntry PetActionBar [MAX_UNIT_ACTION_BAR_INDEX]
CharmSpellInfo _charmspells [4]
CommandStates _CommandState
uint32 _petnumber
ReactStates _oldReactState
bool _isCommandAttack
bool _isCommandFollow
bool _isAtStay
bool _isFollowing
bool _isReturning
int32 _forcedSpellId
ObjectGuid _forcedTargetGUID
float _stayX
float _stayY
float _stayZ
GlobalCooldownMgr _GlobalCooldownMgr
Detailed Description
Definition at line 1221 of file Unit.h.
Constructor & Destructor Documentation
CharmInfo()
CharmInfo::CharmInfo (Unit * unit) explicit
Definition at line 14947 of file Unit.cpp.
     : _unit(unit), _CommandState(COMMAND_FOLLOW), _petnumber(0), _oldReactState(REACT_PASSIVE),
       _isCommandAttack(false), _isCommandFollow(false), _isAtStay(false), _isFollowing(false), _isReturning(false),
       _forcedSpellId(0), _stayX(0.0f), _stayY(0.0f), _stayZ(0.0f)
 {
     for (uint8 i = 0; i < MAX_SPELL_CHARM; ++i)
         _charmspells[i].SetActionAndType(0, ACT_DISABLED);
     if (_unit->GetTypeId() == TYPEID_UNIT)
     {
         _oldReactState = _unit->ToCreature()->GetReactState();
         _unit->ToCreature()->SetReactState(REACT_PASSIVE);
     }
 }
References _charmspells, _oldReactState, _unit, ACT_DISABLED, Creature::GetReactState(), Object::GetTypeId(), MAX_SPELL_CHARM, REACT_PASSIVE, Creature::SetReactState(), Object::ToCreature(), and TYPEID_UNIT.
~CharmInfo()
CharmInfo::~CharmInfo ()
Definition at line 14962 of file Unit.cpp.
 {
 }
Member Function Documentation
AddSpellToActionBar()
bool CharmInfo::AddSpellToActionBar (SpellInfo const * spellInfo, ActiveStates newstate = ACT_DECIDE)
Definition at line 15085 of file Unit.cpp.
 {
     uint32 spell_id = spellInfo->Id;
     uint32 first_id = spellInfo->GetFirstRankSpell()->Id;
     // new spell rank can be already listed
     for (uint8 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
     {
         if (uint32 action = PetActionBar[i].GetAction())
         {
             if (PetActionBar[i].IsActionBarForSpell() && sSpellMgr->GetFirstSpellInChain(action) == first_id)
             {
                 PetActionBar[i].SetAction(spell_id);
                 return true;
             }
         }
     }
     // or use empty slot in other case
     for (uint8 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
     {
         if (!PetActionBar[i].GetAction() && PetActionBar[i].IsActionBarForSpell())
         {
             SetActionBar(i, spell_id, newstate == ACT_DECIDE ? spellInfo->IsAutocastable() ? ACT_DISABLED : ACT_PASSIVE : newstate);
             return true;
         }
     }
     return false;
 }
References ACT_DECIDE, ACT_DISABLED, ACT_PASSIVE, SpellInfo::GetFirstRankSpell(), SpellInfo::Id, SpellInfo::IsAutocastable(), MAX_UNIT_ACTION_BAR_INDEX, PetActionBar, UnitActionBarEntry::SetAction(), SetActionBar(), and sSpellMgr.
Referenced by Pet::addSpell(), InitCharmCreateSpells(), and InitPossessCreateSpells().
BuildActionBar()
void CharmInfo::BuildActionBar (WorldPacket * data)
Definition at line 15183 of file Unit.cpp.
 {
     for (uint32 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
         *data << uint32(PetActionBar[i].packedData);
 }
References MAX_UNIT_ACTION_BAR_INDEX, and PetActionBar.
Referenced by Player::CharmSpellInitialize(), Player::PetSpellInitialize(), and Player::PossessSpellInitialize().
GetActionBarEntry()
UnitActionBarEntry const* CharmInfo::GetActionBarEntry (uint8 index) const inline
Definition at line 1249 of file Unit.h.
 { return &(PetActionBar[index]); }
References index, and PetActionBar.
Referenced by Pet::CleanupActionBar(), WorldSession::HandlePetSetAction(), and Pet::SavePetToDB().
GetCharmSpell()
CharmSpellInfo* CharmInfo::GetCharmSpell (uint8 index) inline
Definition at line 1253 of file Unit.h.
 { return &(_charmspells[index]); }
References _charmspells, and index.
Referenced by Player::CharmSpellInitialize(), and Creature::GetPetAutoSpellOnPos().
GetCommandState()
CommandStates CharmInfo::GetCommandState () const inline
Definition at line 1231 of file Unit.h.
 { return _CommandState; }
References _CommandState.
Referenced by Player::CharmSpellInitialize(), and Player::PetSpellInitialize().
GetForcedSpell()
int32 CharmInfo::GetForcedSpell () inline
Definition at line 1273 of file Unit.h.
 { return _forcedSpellId; }
References _forcedSpellId.
Referenced by WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), and PetAI::UpdateAI().
GetForcedTarget()
ObjectGuid CharmInfo::GetForcedTarget () inline
Definition at line 1275 of file Unit.h.
 { return _forcedTargetGUID; }
References _forcedTargetGUID.
Referenced by PetAI::UpdateAI().
GetGlobalCooldownMgr()
GlobalCooldownMgr& CharmInfo::GetGlobalCooldownMgr () inline
Definition at line 1255 of file Unit.h.
 { return _GlobalCooldownMgr; }
References _GlobalCooldownMgr.
Referenced by Spell::CancelGlobalCooldown(), Spell::CheckPetCast(), Spell::HasGlobalCooldown(), Spell::TriggerGlobalCooldown(), and PetAI::UpdateAI().
GetPetNumber()
uint32 CharmInfo::GetPetNumber () const inline
Definition at line 1227 of file Unit.h.
 { return _petnumber; }
References _petnumber.
Referenced by Pet::_LoadSpellCooldowns(), Pet::_SaveAuras(), Pet::_SaveSpellCooldowns(), Pet::_SaveSpells(), WorldSession::HandlePetRename(), Pet::resetTalentsForAllPetsOf(), Pet::SavePetToDB(), WorldSession::SendStablePetCallback(), and Player::UnsummonPetTemporaryIfAny().
GetPlayerReactState()
ReactStates CharmInfo::GetPlayerReactState () const inline
Definition at line 1279 of file Unit.h.
 { return _oldReactState; }
References _oldReactState.
Referenced by Player::UpdateCharmedAI().
GetStayPosition()
void CharmInfo::GetStayPosition (float & x, float & y, float & z)
Definition at line 19395 of file Unit.cpp.
 {
     x = _stayX;
     y = _stayY;
     z = _stayZ;
 }
References _stayX, _stayY, _stayZ, G3D::x, G3D::y, and G3D::z.
Referenced by PetAI::HandleReturnMovement().
HasCommandState()
bool CharmInfo::HasCommandState (CommandStates state) const inline
Definition at line 1232 of file Unit.h.
 { return (_CommandState == state); }
References _CommandState.
Referenced by PetAI::AttackStart(), PetAI::CanAttack(), AuraEffect::HandleModPossessPet(), PetAI::HandleReturnMovement(), and PetAI::UpdateAI().
HasStayPosition()
bool CharmInfo::HasStayPosition ()
Definition at line 19409 of file Unit.cpp.
 {
     return _stayX && _stayY && _stayZ;
 }
References _stayX, _stayY, and _stayZ.
Referenced by PetAI::HandleReturnMovement().
InitCharmCreateSpells()
void CharmInfo::InitCharmCreateSpells ()
Definition at line 15033 of file Unit.cpp.
 {
     InitPetActionBar();
     if (_unit->GetTypeId() == TYPEID_PLAYER)                // charmed players don't have spells
     {
         //InitEmptyActionBar();
         return;
     }
     //InitPetActionBar();
     for (uint32 x = 0; x < MAX_SPELL_CHARM; ++x)
     {
         uint32 spellId = _unit->ToCreature()->m_spells[x];
         SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
         if (!spellInfo)
         {
             _charmspells[x].SetActionAndType(spellId, ACT_DISABLED);
             continue;
         }
         if (spellInfo->IsPassive())
         {
             _unit->CastSpell(_unit, spellInfo, true);
             _charmspells[x].SetActionAndType(spellId, ACT_PASSIVE);
         }
         else
         {
             _charmspells[x].SetActionAndType(spellId, ACT_DISABLED);
             ActiveStates newstate = ACT_PASSIVE;
             if (!spellInfo->IsAutocastable())
                 newstate = ACT_PASSIVE;
             else
             {
                 if (spellInfo->NeedsExplicitUnitTarget())
                 {
                     newstate = ACT_ENABLED;
                     ToggleCreatureAutocast(spellInfo, true);
                 }
                 else
                     newstate = ACT_DISABLED;
             }
             AddSpellToActionBar(spellInfo, newstate);
         }
     }
 }
References _charmspells, _unit, ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, AddSpellToActionBar(), Unit::CastSpell(), Object::GetTypeId(), InitPetActionBar(), SpellInfo::IsAutocastable(), SpellInfo::IsPassive(), Creature::m_spells, MAX_SPELL_CHARM, SpellInfo::NeedsExplicitUnitTarget(), UnitActionBarEntry::SetActionAndType(), sSpellMgr, Object::ToCreature(), ToggleCreatureAutocast(), TYPEID_PLAYER, and G3D::x.
Referenced by Guardian::InitStats(), and Unit::SetCharmedBy().
InitEmptyActionBar()
void CharmInfo::InitEmptyActionBar (bool withAttack = true)
Definition at line 14987 of file Unit.cpp.
 {
     if (withAttack)
         SetActionBar(ACTION_BAR_INDEX_START, COMMAND_ATTACK, ACT_COMMAND);
     else
         SetActionBar(ACTION_BAR_INDEX_START, 0, ACT_PASSIVE);
     for (uint32 x = ACTION_BAR_INDEX_START + 1; x < ACTION_BAR_INDEX_END; ++x)
         SetActionBar(x, 0, ACT_PASSIVE);
 }
References ACT_COMMAND, ACT_PASSIVE, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_START, COMMAND_ATTACK, SetActionBar(), and G3D::x.
Referenced by InitPossessCreateSpells().
InitPetActionBar()
void CharmInfo::InitPetActionBar ()
Definition at line 14972 of file Unit.cpp.
 {
     // the first 3 SpellOrActions are attack, follow and stay
     for (uint32 i = 0; i < ACTION_BAR_INDEX_PET_SPELL_START - ACTION_BAR_INDEX_START; ++i)
         SetActionBar(ACTION_BAR_INDEX_START + i, COMMAND_ATTACK - i, ACT_COMMAND);
     // middle 4 SpellOrActions are spells/special attacks/abilities
     for (uint32 i = 0; i < ACTION_BAR_INDEX_PET_SPELL_END - ACTION_BAR_INDEX_PET_SPELL_START; ++i)
         SetActionBar(ACTION_BAR_INDEX_PET_SPELL_START + i, 0, ACT_PASSIVE);
     // last 3 SpellOrActions are reactions
     for (uint32 i = 0; i < ACTION_BAR_INDEX_END - ACTION_BAR_INDEX_PET_SPELL_END; ++i)
         SetActionBar(ACTION_BAR_INDEX_PET_SPELL_END + i, COMMAND_ATTACK - i, ACT_REACTION);
 }
References ACT_COMMAND, ACT_PASSIVE, ACT_REACTION, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_PET_SPELL_END, ACTION_BAR_INDEX_PET_SPELL_START, ACTION_BAR_INDEX_START, COMMAND_ATTACK, and SetActionBar().
Referenced by InitCharmCreateSpells(), and Pet::InitPetCreateSpells().
InitPossessCreateSpells()
void CharmInfo::InitPossessCreateSpells ()
Definition at line 14997 of file Unit.cpp.
 {
     if (_unit->GetTypeId() == TYPEID_UNIT)
     {
         // Adding switch until better way is found. Malcrom
         // Adding entrys to this switch will prevent COMMAND_ATTACK being added to pet bar.
         switch (_unit->GetEntry())
         {
             case 23575: // Mindless Abomination
             case 24783: // Trained Rock Falcon
             case 27664: // Crashin' Thrashin' Racer
             case 40281: // Crashin' Thrashin' Racer
             case 23109: // Vengeful Spirit
                 break;
             default:
                 InitEmptyActionBar();
                 break;
         }
         for (uint32 i = 0; i < MAX_CREATURE_SPELLS; ++i)
         {
             uint32 spellId = _unit->ToCreature()->m_spells[i];
             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
             if (spellInfo)
             {
                 if (spellInfo->IsPassive())
                     _unit->CastSpell(_unit, spellInfo, true);
                 else
                     AddSpellToActionBar(spellInfo, ACT_PASSIVE);
             }
         }
     }
     else
         InitEmptyActionBar();
 }
References _unit, ACT_PASSIVE, AddSpellToActionBar(), Unit::CastSpell(), Object::GetEntry(), Object::GetTypeId(), InitEmptyActionBar(), SpellInfo::IsPassive(), Creature::m_spells, MAX_CREATURE_SPELLS, sSpellMgr, Object::ToCreature(), and TYPEID_UNIT.
Referenced by Unit::SetCharmedBy().
IsAtStay()
bool CharmInfo::IsAtStay ()
Definition at line 19419 of file Unit.cpp.
 {
     return _isAtStay;
 }
References _isAtStay.
Referenced by PetAI::HandleReturnMovement(), PetAI::SelectNextTarget(), and PetAI::UpdateAI().
IsCommandAttack()
bool CharmInfo::IsCommandAttack ()
Definition at line 19357 of file Unit.cpp.
 {
     return _isCommandAttack;
 }
References _isCommandAttack.
Referenced by PetAI::AttackStart(), PetAI::CanAttack(), PetAI::DoAttack(), WorldSession::HandlePetActionHelper(), and PetAI::UpdateAI().
IsCommandFollow()
bool CharmInfo::IsCommandFollow ()
Definition at line 19367 of file Unit.cpp.
 {
     return _isCommandFollow;
 }
References _isCommandFollow.
Referenced by PetAI::CanAttack().
IsFollowing()
bool CharmInfo::IsFollowing ()
Definition at line 19429 of file Unit.cpp.
 {
     return _isFollowing;
 }
References _isFollowing.
Referenced by PetAI::HandleReturnMovement(), and PetAI::SelectNextTarget().
IsReturning()
bool CharmInfo::IsReturning ()
Definition at line 19439 of file Unit.cpp.
 {
     return _isReturning;
 }
References _isReturning.
Referenced by PetAI::CanAttack(), PetAI::HandleReturnMovement(), PetAI::MovementInform(), and PetAI::SelectNextTarget().
LoadPetActionBar()
void CharmInfo::LoadPetActionBar (const std::string & data)
Definition at line 15153 of file Unit.cpp.
 {
     Tokenizer tokens(data, ' ');
     if (tokens.size() != (ACTION_BAR_INDEX_END - ACTION_BAR_INDEX_START) * 2)
         return;                                             // non critical, will reset to default
     uint8 index = ACTION_BAR_INDEX_START;
     Tokenizer::const_iterator iter = tokens.begin();
     for (; index < ACTION_BAR_INDEX_END; ++iter, ++index)
     {
         // use unsigned cast to avoid sign negative format use at long-> ActiveStates (int) conversion
         ActiveStates type  = ActiveStates(atol(*iter));
         ++iter;
         uint32 action = uint32(atol(*iter));
         PetActionBar[index].SetActionAndType(action, type);
         // check correctness
         if (PetActionBar[index].IsActionBarForSpell())
         {
             SpellInfo const* spelInfo = sSpellMgr->GetSpellInfo(PetActionBar[index].GetAction());
             if (!spelInfo)
                 SetActionBar(index, 0, ACT_PASSIVE);
             else if (!spelInfo->IsAutocastable())
                 SetActionBar(index, PetActionBar[index].GetAction(), ACT_PASSIVE);
         }
     }
 }
References ACT_PASSIVE, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_START, Tokenizer::begin(), index, SpellInfo::IsAutocastable(), PetActionBar, UnitActionBarEntry::SetActionAndType(), SetActionBar(), Tokenizer::size(), and sSpellMgr.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
RemoveSpellFromActionBar()
bool CharmInfo::RemoveSpellFromActionBar (uint32 spell_id)
Definition at line 15115 of file Unit.cpp.
 {
     uint32 first_id = sSpellMgr->GetFirstSpellInChain(spell_id);
     for (uint8 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
     {
         if (uint32 action = PetActionBar[i].GetAction())
         {
             if (PetActionBar[i].IsActionBarForSpell() && sSpellMgr->GetFirstSpellInChain(action) == first_id)
             {
                 SetActionBar(i, 0, ACT_PASSIVE);
                 return true;
             }
         }
     }
     return false;
 }
References ACT_PASSIVE, MAX_UNIT_ACTION_BAR_INDEX, PetActionBar, SetActionBar(), and sSpellMgr.
Referenced by Pet::removeSpell().
RemoveStayPosition()
void CharmInfo::RemoveStayPosition ()
Definition at line 19402 of file Unit.cpp.
 {
     _stayX = 0.0f;
     _stayY = 0.0f;
     _stayZ = 0.0f;
 }
References _stayX, _stayY, and _stayZ.
Referenced by WorldSession::HandlePetActionHelper().
RestoreState()
void CharmInfo::RestoreState ()
Definition at line 14966 of file Unit.cpp.
 {
     if (Creature* creature = _unit->ToCreature())
         creature->SetReactState(_oldReactState);
 }
References _oldReactState, _unit, and Object::ToCreature().
Referenced by Unit::DeleteCharmInfo().
SaveStayPosition()
void CharmInfo::SaveStayPosition (bool atCurrentPos)
At this point a new spline destination is enabled because of Unit::StopMoving()
Definition at line 19372 of file Unit.cpp.
 {
     G3D::Vector3 stayPos = G3D::Vector3();
     if (atCurrentPos)
     {
         float z = INVALID_HEIGHT;
         _unit->UpdateAllowedPositionZ(_unit->GetPositionX(), _unit->GetPositionY(), z);
         stayPos = G3D::Vector3(_unit->GetPositionX(), _unit->GetPositionY(), z != INVALID_HEIGHT ? z : _unit->GetPositionZ());
     }
     else
         stayPos = _unit->movespline->FinalDestination();
     if (_unit->movespline->onTransport)
         if (TransportBase* transport = _unit->GetDirectTransport())
             transport->CalculatePassengerPosition(stayPos.x, stayPos.y, stayPos.z);
     _stayX = stayPos.x;
     _stayY = stayPos.y;
     _stayZ = stayPos.z;
 }
References _stayX, _stayY, _stayZ, _unit, Movement::MoveSpline::FinalDestination(), Unit::GetDirectTransport(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), INVALID_HEIGHT, Unit::movespline, Movement::MoveSpline::onTransport, WorldObject::UpdateAllowedPositionZ(), G3D::Vector3::x, G3D::Vector3::y, G3D::Vector3::z, and G3D::z.
Referenced by WorldSession::HandlePetActionHelper(), and Pet::Update().
SetActionBar()
void CharmInfo::SetActionBar (uint8 index, uint32 spellOrAction, ActiveStates type) inline
Definition at line 1245 of file Unit.h.
     {
         PetActionBar[index].SetActionAndType(spellOrAction, type);
     }
References index, PetActionBar, and UnitActionBarEntry::SetActionAndType().
Referenced by AddSpellToActionBar(), Pet::CleanupActionBar(), WorldSession::HandlePetSetAction(), InitEmptyActionBar(), InitPetActionBar(), LoadPetActionBar(), and RemoveSpellFromActionBar().
SetCommandState()
void CharmInfo::SetCommandState (CommandStates st) inline
Definition at line 1230 of file Unit.h.
 { _CommandState = st; }
References _CommandState.
Referenced by WorldSession::HandlePetActionHelper(), and Pet::Update().
SetForcedSpell()
void CharmInfo::SetForcedSpell (uint32 id) inline
Definition at line 1272 of file Unit.h.
 { _forcedSpellId = id; }
References _forcedSpellId.
Referenced by WorldSession::HandlePetActionHelper(), PetAI::HandleReturnMovement(), Unit::PetSpellFail(), and PetAI::SpellHit().
SetForcedTargetGUID()
void CharmInfo::SetForcedTargetGUID (ObjectGuid guid = ObjectGuid::Empty) inline
Definition at line 1274 of file Unit.h.
 { _forcedTargetGUID = guid; }
References _forcedTargetGUID.
Referenced by WorldSession::HandlePetActionHelper(), PetAI::HandleReturnMovement(), Unit::PetSpellFail(), and PetAI::SpellHit().
SetIsAtStay()
void CharmInfo::SetIsAtStay (bool val)
Definition at line 19414 of file Unit.cpp.
 {
     _isAtStay = val;
 }
References _isAtStay.
Referenced by Pet::AddToWorld(), PetAI::ClearCharmInfoFlags(), PetAI::DoAttack(), Spell::EffectResurrectPet(), WorldSession::HandlePetActionHelper(), PetAI::MovementInform(), Unit::PetSpellFail(), and Pet::Update().
SetIsCommandAttack()
void CharmInfo::SetIsCommandAttack (bool val)
Definition at line 19352 of file Unit.cpp.
 {
     _isCommandAttack = val;
 }
References _isCommandAttack.
Referenced by PetAI::_stopAttack(), Pet::AddToWorld(), PetAI::ClearCharmInfoFlags(), WorldSession::HandlePetActionHelper(), Unit::PetSpellFail(), and Pet::Update().
SetIsCommandFollow()
void CharmInfo::SetIsCommandFollow (bool val)
Definition at line 19362 of file Unit.cpp.
 {
     _isCommandFollow = val;
 }
References _isCommandFollow.
Referenced by Pet::AddToWorld(), PetAI::ClearCharmInfoFlags(), WorldSession::HandlePetActionHelper(), and Pet::Update().
SetIsFollowing()
void CharmInfo::SetIsFollowing (bool val)
Definition at line 19424 of file Unit.cpp.
 {
     _isFollowing = val;
 }
References _isFollowing.
Referenced by Pet::AddToWorld(), PetAI::ClearCharmInfoFlags(), Spell::EffectResurrectPet(), WorldSession::HandlePetActionHelper(), PetAI::MovementInform(), Unit::PetSpellFail(), and Pet::Update().
SetIsReturning()
void CharmInfo::SetIsReturning (bool val)
Definition at line 19434 of file Unit.cpp.
 {
     _isReturning = val;
 }
References _isReturning.
Referenced by Pet::AddToWorld(), PetAI::ClearCharmInfoFlags(), WorldSession::HandlePetActionHelper(), PetAI::HandleReturnMovement(), Unit::PetSpellFail(), and Pet::Update().
SetPetNumber()
void CharmInfo::SetPetNumber (uint32 petnumber, bool statwindow)
Definition at line 15144 of file Unit.cpp.
 {
     _petnumber = petnumber;
     if (statwindow)
         _unit->SetUInt32Value(UNIT_FIELD_PETNUMBER, _petnumber);
     else
         _unit->SetUInt32Value(UNIT_FIELD_PETNUMBER, 0);
 }
References _petnumber, _unit, Object::SetUInt32Value(), and UNIT_FIELD_PETNUMBER.
Referenced by Pet::HandleAsynchLoadFailed(), misc_commandscript::HandleCreatePetCommand(), Unit::InitTamedPet(), Unit::RemoveCharmedBy(), and Unit::SetCharmedBy().
SetPlayerReactState()
void CharmInfo::SetPlayerReactState (ReactStates s) inline
Definition at line 1278 of file Unit.h.
 { _oldReactState = s; }
References _oldReactState.
Referenced by WorldSession::HandlePetActionHelper().
SetSpellAutocast()
void CharmInfo::SetSpellAutocast (SpellInfo const * spellInfo, bool state)
Definition at line 15189 of file Unit.cpp.
 {
     for (uint8 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
     {
         if (spellInfo->Id == PetActionBar[i].GetAction() && PetActionBar[i].IsActionBarForSpell())
         {
             PetActionBar[i].SetType(state ? ACT_ENABLED : ACT_DISABLED);
             break;
         }
     }
 }
References ACT_DISABLED, ACT_ENABLED, UnitActionBarEntry::GetAction(), SpellInfo::Id, UnitActionBarEntry::IsActionBarForSpell(), MAX_UNIT_ACTION_BAR_INDEX, PetActionBar, and UnitActionBarEntry::SetType().
Referenced by WorldSession::HandlePetSpellAutocastOpcode().
ToggleCreatureAutocast()
void CharmInfo::ToggleCreatureAutocast (SpellInfo const * spellInfo, bool apply)
Definition at line 15134 of file Unit.cpp.
 {
     if (spellInfo->IsPassive())
         return;
     for (uint32 x = 0; x < MAX_SPELL_CHARM; ++x)
         if (spellInfo->Id == _charmspells[x].GetAction())
             _charmspells[x].SetType(apply ? ACT_ENABLED : ACT_DISABLED);
 }
References _charmspells, ACT_DISABLED, ACT_ENABLED, ByteConverter::apply(), UnitActionBarEntry::GetAction(), SpellInfo::Id, SpellInfo::IsPassive(), MAX_SPELL_CHARM, UnitActionBarEntry::SetType(), and G3D::x.
Referenced by WorldSession::HandlePetSpellAutocastOpcode(), and InitCharmCreateSpells().
Member Data Documentation
_charmspells
CharmSpellInfo CharmInfo::_charmspells[4] private
Definition at line 1284 of file Unit.h.
Referenced by CharmInfo(), GetCharmSpell(), InitCharmCreateSpells(), and ToggleCreatureAutocast().
_CommandState
CommandStates CharmInfo::_CommandState private
Definition at line 1285 of file Unit.h.
Referenced by GetCommandState(), HasCommandState(), and SetCommandState().
_forcedSpellId
int32 CharmInfo::_forcedSpellId private
Definition at line 1296 of file Unit.h.
Referenced by GetForcedSpell(), and SetForcedSpell().
_forcedTargetGUID
ObjectGuid CharmInfo::_forcedTargetGUID private
Definition at line 1297 of file Unit.h.
Referenced by GetForcedTarget(), and SetForcedTargetGUID().
_GlobalCooldownMgr
GlobalCooldownMgr CharmInfo::_GlobalCooldownMgr private
Definition at line 1302 of file Unit.h.
Referenced by GetGlobalCooldownMgr().
_isAtStay
bool CharmInfo::_isAtStay private
Definition at line 1293 of file Unit.h.
Referenced by IsAtStay(), and SetIsAtStay().
_isCommandAttack
bool CharmInfo::_isCommandAttack private
Definition at line 1291 of file Unit.h.
Referenced by IsCommandAttack(), and SetIsCommandAttack().
_isCommandFollow
bool CharmInfo::_isCommandFollow private
Definition at line 1292 of file Unit.h.
Referenced by IsCommandFollow(), and SetIsCommandFollow().
_isFollowing
bool CharmInfo::_isFollowing private
Definition at line 1294 of file Unit.h.
Referenced by IsFollowing(), and SetIsFollowing().
_isReturning
bool CharmInfo::_isReturning private
Definition at line 1295 of file Unit.h.
Referenced by IsReturning(), and SetIsReturning().
_oldReactState
ReactStates CharmInfo::_oldReactState private
Definition at line 1289 of file Unit.h.
Referenced by CharmInfo(), GetPlayerReactState(), RestoreState(), and SetPlayerReactState().
_petnumber
uint32 CharmInfo::_petnumber private
Definition at line 1286 of file Unit.h.
Referenced by GetPetNumber(), and SetPetNumber().
_stayX
float CharmInfo::_stayX private
Definition at line 1298 of file Unit.h.
Referenced by GetStayPosition(), HasStayPosition(), RemoveStayPosition(), and SaveStayPosition().
_stayY
float CharmInfo::_stayY private
Definition at line 1299 of file Unit.h.
Referenced by GetStayPosition(), HasStayPosition(), RemoveStayPosition(), and SaveStayPosition().
_stayZ
float CharmInfo::_stayZ private
Definition at line 1300 of file Unit.h.
Referenced by GetStayPosition(), HasStayPosition(), RemoveStayPosition(), and SaveStayPosition().
_unit
Unit* CharmInfo::_unit private
Definition at line 1282 of file Unit.h.
Referenced by CharmInfo(), InitCharmCreateSpells(), InitPossessCreateSpells(), RestoreState(), SaveStayPosition(), and SetPetNumber().
PetActionBar
UnitActionBarEntry CharmInfo::PetActionBar[MAX_UNIT_ACTION_BAR_INDEX] private
Definition at line 1283 of file Unit.h.
Referenced by AddSpellToActionBar(), BuildActionBar(), GetActionBarEntry(), LoadPetActionBar(), RemoveSpellFromActionBar(), SetActionBar(), and SetSpellAutocast().
The documentation for this struct was generated from the following files:
src/server/game/Entities/Unit/Unit.h
src/server/game/Entities/Unit/Unit.cpp