Azerotcore-wotlk: boss_anubarak_trial::boss_anubarak_trialAI Struct Reference
boss_anubarak_trial::boss_anubarak_trialAI Struct Reference
Public Member Functions
boss_anubarak_trialAI (Creature *pCreature)
void Reset () override
void DoAction (int32 param) override
void EnterCombat (Unit *) override
void JustReachedHome () override
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *summon) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
void MoveInLineOfSight (Unit *who) override
bool CanAIAttack (const Unit *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
SummonList summons
EventMap events
bool bIntro
bool bPhase3
ObjectGuid SphereGUID [6]
ObjectGuid BurrowGUID [4]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 156 of file boss_anubarak_trial.cpp.
Constructor & Destructor Documentation
boss_anubarak_trialAI()
boss_anubarak_trial::boss_anubarak_trialAI::boss_anubarak_trialAI (Creature * pCreature) inline
Definition at line 158 of file boss_anubarak_trial.cpp.
                                                    : ScriptedAI(pCreature), summons(me)
         {
             pInstance = (InstanceScript*)pCreature->GetInstanceScript();
             events.Reset();
             bIntro = false;
             bPhase3 = false;
             me->ApplySpellImmune(0, IMMUNITY_ID, RAID_MODE(66193, 67855, 67856, 67857), true);
             me->m_SightDistance = 90.0f; // for MoveInLineOfSight distance
         }
References Unit::ApplySpellImmune(), bIntro, bPhase3, WorldObject::GetInstanceScript(), IMMUNITY_ID, Creature::m_SightDistance, ScriptedAI::me, pInstance, and ScriptedAI::RAID_MODE().
Member Function Documentation
CanAIAttack()
bool boss_anubarak_trial::boss_anubarak_trialAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 419 of file boss_anubarak_trial.cpp.
         {
             return target->GetEntry() != NPC_FROST_SPHERE;
         }
References Object::GetEntry(), and NPC_FROST_SPHERE.
DoAction()
void boss_anubarak_trial::boss_anubarak_trialAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 194 of file boss_anubarak_trial.cpp.
         {
             switch( param )
             {
                 case -1:
                     summons.DespawnAll();
                     break;
             }
         }
References SummonList::DespawnAll(), and summons.
EnterCombat()
void boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 204 of file boss_anubarak_trial.cpp.
         {
             me->setActive(true);
             events.Reset();
             events.RescheduleEvent(EVENT_ENRAGE, 600000);
             events.RescheduleEvent(EVENT_SPELL_FREEZING_SLASH, urand(7000, 15000));
             events.RescheduleEvent(EVENT_SPELL_PENETRATING_COLD, urand(15000, 20000));
             events.RescheduleEvent(EVENT_SUMMON_NERUBIAN, urand(5000, 8000));
             events.RescheduleEvent(EVENT_SUBMERGE, SUBMERGE_INTERVAL);
             if( !IsHeroic() )
                 events.RescheduleEvent(EVENT_RESPAWN_SPHERE, 4000);
             for (ObjectGuid const& guid : summons)
                 if (pInstance)
                     if (Creature* c = pInstance->instance->GetCreature(guid))
                     {
                         c->GetMotionMaster()->MoveIdle();
                         c->StopMoving();
                         c->CastSpell(c, SPELL_SUBMERGE, false);
                         c->AI()->DoAction(1);
                     }
             summons.clear();
             for( uint8 i = 0; i < 4; ++i )
                 if( Creature* c = me->SummonCreature(NPC_BURROW, AnubLocs[i + 1]) )
                     BurrowGUID[i] = c->GetGUID();
             for( uint8 i = 0; i < 6; ++i )
                 if( Creature* c = me->SummonCreature(NPC_FROST_SPHERE, AnubLocs[i + 5]) )
                     SphereGUID[i] = c->GetGUID();
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             if( pInstance )
                 pInstance->SetData(TYPE_ANUBARAK, IN_PROGRESS);
         }
References AnubLocs, BurrowGUID, SummonList::clear(), CreatureAI::DoZoneInCombat(), EVENT_ENRAGE, EVENT_RESPAWN_SPHERE, EVENT_SPELL_FREEZING_SLASH, EVENT_SPELL_PENETRATING_COLD, EVENT_SUBMERGE, EVENT_SUMMON_NERUBIAN, Map::GetCreature(), IN_PROGRESS, InstanceScript::instance, ScriptedAI::IsHeroic(), ScriptedAI::me, NPC_BURROW, NPC_FROST_SPHERE, pInstance, SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), SPELL_SUBMERGE, SphereGUID, SUBMERGE_INTERVAL, WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TYPE_ANUBARAK, and urand().
EnterEvadeMode()
void boss_anubarak_trial::boss_anubarak_trialAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 392 of file boss_anubarak_trial.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             if( pInstance )
                 pInstance->SetData(TYPE_FAILED, 1);
         }
References SummonList::DespawnAll(), ScriptedAI::me, pInstance, ZoneScript::SetData(), Object::SetFlag(), summons, TYPE_FAILED, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_anubarak_trial::boss_anubarak_trialAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 377 of file boss_anubarak_trial.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             Talk(SAY_DEATH);
             if( pInstance )
                 pInstance->SetData(TYPE_ANUBARAK, DONE);
         }
References SummonList::DespawnAll(), DONE, pInstance, SAY_DEATH, ZoneScript::SetData(), summons, CreatureAI::Talk(), and TYPE_ANUBARAK.
JustReachedHome()
void boss_anubarak_trial::boss_anubarak_trialAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 239 of file boss_anubarak_trial.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_anubarak_trial::boss_anubarak_trialAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 369 of file boss_anubarak_trial.cpp.
         {
             if( !summon )
                 return;
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_anubarak_trial::boss_anubarak_trialAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 386 of file boss_anubarak_trial.cpp.
         {
             if( who->GetTypeId() == TYPEID_PLAYER )
                 Talk(SAY_KILL_PLAYER);
         }
References Object::GetTypeId(), SAY_KILL_PLAYER, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 401 of file boss_anubarak_trial.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER || me->GetExactDistSq(who) > 6400.0f) // 80yd*80yd
                 return;
             if (me->getStandState() != UNIT_STAND_STATE_STAND)
                 me->SetStandState(UNIT_STAND_STATE_STAND);
             if (!bIntro)
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 if( !me->IsInCombat() )
                     Talk(SAY_INTRO);
                 bIntro = true;
             }
             ScriptedAI::MoveInLineOfSight(who);
         }
References bIntro, Position::GetExactDistSq(), Unit::getStandState(), Object::GetTypeId(), Unit::IsInCombat(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), Object::RemoveFlag(), SAY_INTRO, Unit::SetStandState(), CreatureAI::Talk(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STAND_STATE_STAND.
Reset()
void boss_anubarak_trial::boss_anubarak_trialAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 176 of file boss_anubarak_trial.cpp.
         {
             me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             summons.DespawnAll();
             for( uint8 i = 0; i < 10; ++i )
             {
                 float angle = rand_norm() * 2 * M_PI;
                 float dist = rand_norm() * 40.0f;
                 if( Creature* c = me->SummonCreature(NPC_SCARAB, AnubLocs[0].GetPositionX() + cos(angle) * dist, AnubLocs[0].GetPositionY() + sin(angle) * dist, AnubLocs[0].GetPositionZ(), 0.0f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000) )
                 {
                     c->SetFaction(FACTION_PREY);
                     c->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     c->GetMotionMaster()->MoveRandom(15.0f);
                 }
             }
         }
References AnubLocs, SummonList::DespawnAll(), FACTION_PREY, Position::GetPositionX(), ScriptedAI::me, NPC_SCARAB, rand_norm(), Object::SetFlag(), Unit::SetStandState(), WorldObject::SummonCreature(), summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STAND_STATE_SUBMERGED.
UpdateAI()
void boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 244 of file boss_anubarak_trial.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             if( !bPhase3 && HealthBelowPct(30) && !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE) && !me->HasAura(SPELL_SUBMERGE) && !me->HasAura(SPELL_EMERGE) )
             {
                 bPhase3 = true;
                 events.CancelEvent(EVENT_SUBMERGE);
                 events.CancelEvent(EVENT_EMERGE);
                 events.CancelEvent(EVENT_EMERGE_2);
                 if( !IsHeroic() )
                     events.CancelEvent(EVENT_SUMMON_NERUBIAN);
                 me->CastSpell((Unit*)nullptr, SPELL_LEECHING_SWARM, false);
                 Talk(EMOTE_LEECHING_SWARM);
                 Talk(SAY_LEECHING_SWARM);
                 return;
             }
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_ENRAGE:
                     {
                         me->CastSpell(me, SPELL_BERSERK, true);
                     }
                     break;
                 case EVENT_RESPAWN_SPHERE:
                     {
                         uint8 StartAt = urand(0, 5);
                         uint8 i = StartAt;
                         do
{
                             if( Creature* c = ObjectAccessor::GetCreature(*me, SphereGUID[i]) )
                                 if( !c->HasAura(SPELL_FROST_SPHERE) )
{
                                     if( Creature* c = me->SummonCreature(NPC_FROST_SPHERE, AnubLocs[i + 5]) )
                                         SphereGUID[i] = c->GetGUID();
                                     break;
                                 }
                             i = (i + 1) % 6;
                         } while( i != StartAt );
                         events.RepeatEvent(4000);
                     }
                     break;
                 case EVENT_SPELL_FREEZING_SLASH:
                     {
                         if( me->GetVictim() )
                             me->CastSpell(me->GetVictim(), SPELL_FREEZING_SLASH, false);
                         events.RepeatEvent(urand(15000, 20000));
                     }
                     break;
                 case EVENT_SPELL_PENETRATING_COLD:
                     {
                         me->CastCustomSpell(SPELL_PENETRATING_COLD, SPELLVALUE_MAX_TARGETS, RAID_MODE(2, 5, 2, 5));
                         events.RepeatEvent(18000);
                     }
                     break;
                 case EVENT_SUMMON_NERUBIAN:
                     {
                         me->CastCustomSpell(SPELL_SUMMON_BURROWER, SPELLVALUE_MAX_TARGETS, RAID_MODE(1, 2, 2, 4));
                         events.RepeatEvent(45000);
                     }
                     break;
                 case EVENT_SUBMERGE:
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         bool berserk = me->HasAura(SPELL_BERSERK);
                         me->RemoveAllAuras();
                         if (berserk)
                             me->CastSpell(me, SPELL_BERSERK, true);
                         Talk(EMOTE_SUBMERGE);
                         Talk(EMOTE_BURROWER);
                         me->CastSpell(me, SPELL_SUBMERGE, false);
                         events.CancelEvent(EVENT_SUMMON_NERUBIAN);
                         events.CancelEvent(EVENT_SPELL_FREEZING_SLASH);
                         events.CancelEvent(EVENT_SPELL_PENETRATING_COLD);
                         events.RescheduleEvent(EVENT_EMERGE, EMERGE_INTERVAL);
                         events.RescheduleEvent(EVENT_SPELL_SUMMON_SPIKE, 2500);
                         events.RescheduleEvent(EVENT_SUMMON_SCARAB, 3000);
                     }
                     break;
                 case EVENT_SUMMON_SCARAB:
                     {
                         uint8 i = urand(0, 3);
                         if( Creature* c = ObjectAccessor::GetCreature(*me, BurrowGUID[i]) )
                             me->CastSpell(c, SPELL_SUMMON_SCARAB, true);
                         events.RepeatEvent(4000);
                     }
                     break;
                 case EVENT_EMERGE:
                     {
                         me->CastSpell(me, SPELL_SPIKE_TELE, true);
                         summons.DespawnEntry(NPC_SPIKE);
                         events.CancelEvent(EVENT_SUMMON_SCARAB);
                         events.RescheduleEvent(EVENT_EMERGE_2, 2000);
                     }
                     break;
                 case EVENT_EMERGE_2:
                     {
                         Talk(SAY_EMERGE);
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         me->setAttackTimer(BASE_ATTACK, 3000);
                         me->RemoveAura(SPELL_SUBMERGE);
                         me->CastSpell(me, SPELL_EMERGE, false);
                         events.RescheduleEvent(EVENT_SUMMON_NERUBIAN, urand(5000, 8000));
                         events.RescheduleEvent(EVENT_SPELL_FREEZING_SLASH, urand(7000, 15000));
                         events.RescheduleEvent(EVENT_SPELL_PENETRATING_COLD, urand(15000, 20000));
                         events.RescheduleEvent(EVENT_SUBMERGE, SUBMERGE_INTERVAL);
                     }
                     break;
                 case EVENT_SPELL_SUMMON_SPIKE:
                     me->CastSpell(me, SPELL_SUMMON_SPIKE, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References AnubLocs, BASE_ATTACK, bPhase3, BurrowGUID, Unit::CastCustomSpell(), Unit::CastSpell(), SummonList::DespawnEntry(), UnitAI::DoMeleeAttackIfReady(), EMERGE_INTERVAL, EMOTE_BURROWER, EMOTE_LEECHING_SWARM, EMOTE_SUBMERGE, EVENT_EMERGE, EVENT_EMERGE_2, EVENT_ENRAGE, EVENT_RESPAWN_SPHERE, EVENT_SPELL_FREEZING_SLASH, EVENT_SPELL_PENETRATING_COLD, EVENT_SPELL_SUMMON_SPIKE, EVENT_SUBMERGE, EVENT_SUMMON_NERUBIAN, EVENT_SUMMON_SCARAB, ObjectAccessor::GetCreature(), Unit::GetVictim(), Unit::HasAura(), Object::HasFlag(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), ScriptedAI::IsHeroic(), ScriptedAI::me, NPC_FROST_SPHERE, NPC_SPIKE, ScriptedAI::RAID_MODE(), Unit::RemoveAllAuras(), Unit::RemoveAura(), Object::RemoveFlag(), SAY_EMERGE, SAY_LEECHING_SWARM, Unit::setAttackTimer(), Object::SetFlag(), SPELL_BERSERK, SPELL_EMERGE, SPELL_FREEZING_SLASH, SPELL_FROST_SPHERE, SPELL_LEECHING_SWARM, SPELL_PENETRATING_COLD, SPELL_SPIKE_TELE, SPELL_SUBMERGE, SPELL_SUMMON_BURROWER, SPELL_SUMMON_SCARAB, SPELL_SUMMON_SPIKE, SPELLVALUE_MAX_TARGETS, SphereGUID, SUBMERGE_INTERVAL, WorldObject::SummonCreature(), summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bIntro
bool boss_anubarak_trial::boss_anubarak_trialAI::bIntro
Definition at line 171 of file boss_anubarak_trial.cpp.
Referenced by boss_anubarak_trialAI(), and MoveInLineOfSight().
bPhase3
bool boss_anubarak_trial::boss_anubarak_trialAI::bPhase3
Definition at line 172 of file boss_anubarak_trial.cpp.
Referenced by boss_anubarak_trialAI(), and UpdateAI().
BurrowGUID
ObjectGuid boss_anubarak_trial::boss_anubarak_trialAI::BurrowGUID[4]
Definition at line 174 of file boss_anubarak_trial.cpp.
Referenced by EnterCombat(), and UpdateAI().
events
EventMap boss_anubarak_trial::boss_anubarak_trialAI::events
Definition at line 170 of file boss_anubarak_trial.cpp.
pInstance
InstanceScript* boss_anubarak_trial::boss_anubarak_trialAI::pInstance
Definition at line 168 of file boss_anubarak_trial.cpp.
Referenced by boss_anubarak_trialAI(), EnterCombat(), EnterEvadeMode(), and JustDied().
SphereGUID
ObjectGuid boss_anubarak_trial::boss_anubarak_trialAI::SphereGUID[6]
Definition at line 173 of file boss_anubarak_trial.cpp.
Referenced by EnterCombat(), and UpdateAI().
summons
SummonList boss_anubarak_trial::boss_anubarak_trialAI::summons
Definition at line 169 of file boss_anubarak_trial.cpp.
Referenced by DoAction(), EnterCombat(), EnterEvadeMode(), JustDied(), JustSummoned(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp