Azerotcore-wotlk: deps/mysqllite/include/my_dbug.h File Reference
my_dbug.h File Reference
#include <signal.h>
Classes
struct _db_stack_frame_
Macros
#define DBUG_ENTER(a)
#define DBUG_LEAVE _db_return_ (__LINE__, &_db_stack_frame_)
#define DBUG_RETURN(a1) do {DBUG_LEAVE; return(a1);} while(0)
#define DBUG_VOID_RETURN do {DBUG_LEAVE; return;} while(0)
#define DBUG_EXECUTE(keyword, a1) do {if (_db_keyword_(0, (keyword), 0)) { a1 }} while(0)
#define DBUG_EXECUTE_IF(keyword, a1) do {if (_db_keyword_(0, (keyword), 1)) { a1 }} while(0)
#define DBUG_EVALUATE(keyword, a1, a2) (_db_keyword_(0,(keyword), 0) ? (a1) : (a2))
#define DBUG_EVALUATE_IF(keyword, a1, a2) (_db_keyword_(0,(keyword), 1) ? (a1) : (a2))
#define DBUG_PRINT(keyword, arglist) do {_db_pargs_(__LINE__,keyword); _db_doprnt_ arglist;} while(0)
#define DBUG_PUSH(a1) _db_push_ (a1)
#define DBUG_POP() _db_pop_ ()
#define DBUG_SET(a1) _db_set_ (a1)
#define DBUG_SET_INITIAL(a1) _db_set_init_ (a1)
#define DBUG_PROCESS(a1) _db_process_(a1)
#define DBUG_FILE _db_fp_()
#define DBUG_SETJMP(a1) (_db_setjmp_ (), setjmp (a1))
#define DBUG_LONGJMP(a1, a2) (_db_longjmp_ (), longjmp (a1, a2))
#define DBUG_DUMP(keyword, a1, a2) _db_dump_(__LINE__,keyword,a1,a2)
#define DBUG_END() _db_end_ ()
#define DBUG_LOCK_FILE _db_lock_file_()
#define DBUG_UNLOCK_FILE _db_unlock_file_()
#define DBUG_ASSERT(A) assert(A)
#define DBUG_EXPLAIN(buf, len) _db_explain_(0, (buf),(len))
#define DBUG_EXPLAIN_INITIAL(buf, len) _db_explain_init_((buf),(len))
#define DEBUGGER_OFF do { _dbug_on_= 0; } while(0)
#define DEBUGGER_ON do { _dbug_on_= 1; } while(0)
#define DBUG_ABORT() (_db_flush_(), abort())
#define DBUG_CHECK_CRASH(func, op)
#define DBUG_CRASH_ENTER(func) DBUG_ENTER(func); DBUG_CHECK_CRASH(func, "_crash_enter")
#define DBUG_CRASH_RETURN(val) DBUG_CHECK_CRASH(_db_get_func_(), "_crash_return")
#define DBUG_CRASH_VOID_RETURN DBUG_CHECK_CRASH (_db_get_func_(), "_crash_return")
#define DBUG_SUICIDE() (_db_flush_(), _db_suicide_())
#define DBUG_SYNC_POINT(lock_name, lock_timeout)
Functions
my_bool _db_keyword_ (struct _db_code_state_ *, const char *, int)
int _db_explain_ (struct _db_code_state_ *cs, char *buf, size_t len)
int _db_explain_init_ (char *buf, size_t len)
int _db_is_pushed_ (void)
void _db_setjmp_ (void)
void _db_longjmp_ (void)
void _db_process_ (const char *name)
void _db_push_ (const char *control)
void _db_pop_ (void)
void _db_set_ (const char *control)
void _db_set_init_ (const char *control)
void _db_enter_ (const char *_func_, const char *_file_, uint _line_, struct _db_stack_frame_ *_stack_frame_)
void _db_return_ (uint _line_, struct _db_stack_frame_ *_stack_frame_)
void _db_pargs_ (uint _line_, const char *keyword)
void _db_doprnt_ (const char *format,...) ATTRIBUTE_FORMAT(printf
void void _db_dump_ (uint _line_, const char *keyword, const unsigned char *memory, size_t length)
void _db_end_ (void)
void _db_lock_file_ (void)
void _db_unlock_file_ (void)
FILE * _db_fp_ (void)
void _db_flush_ ()
const char * _db_get_func_ (void)
void _db_suicide_ ()
Variables
my_bool _dbug_on_
Macro Definition Documentation
DBUG_ABORT
#define DBUG_ABORT () (_db_flush_(), abort())
Definition at line 102 of file my_dbug.h.
DBUG_ASSERT
#define DBUG_ASSERT (A) assert(A)
Definition at line 96 of file my_dbug.h.
DBUG_CHECK_CRASH
#define DBUG_CHECK_CRASH (func, op)
Value:
  do { char _dbuf_[255]; strxnmov(_dbuf_, sizeof(_dbuf_)-1, (func), (op)); \
    DBUG_EXECUTE_IF(_dbuf_, DBUG_ABORT()); } while(0)
Definition at line 114 of file my_dbug.h.
DBUG_CRASH_ENTER
#define DBUG_CRASH_ENTER (func) DBUG_ENTER(func); DBUG_CHECK_CRASH(func, "_crash_enter")
Definition at line 117 of file my_dbug.h.
DBUG_CRASH_RETURN
#define DBUG_CRASH_RETURN (val) DBUG_CHECK_CRASH(_db_get_func_(), "_crash_return")
Definition at line 119 of file my_dbug.h.
DBUG_CRASH_VOID_RETURN
#define DBUG_CRASH_VOID_RETURN DBUG_CHECK_CRASH (_db_get_func_(), "_crash_return")
Definition at line 121 of file my_dbug.h.
DBUG_DUMP
#define DBUG_DUMP (keyword, a1, a2) _db_dump_(__LINE__,keyword,a1,a2)
Definition at line 92 of file my_dbug.h.
DBUG_END
#define DBUG_END () _db_end_ ()
Definition at line 93 of file my_dbug.h.
DBUG_ENTER
#define DBUG_ENTER (a)
Value:
        struct _db_stack_frame_ _db_stack_frame_; \
        _db_enter_ (a,__FILE__,__LINE__,&_db_stack_frame_)
Definition at line 69 of file my_dbug.h.
DBUG_EVALUATE
#define DBUG_EVALUATE (keyword, a1, a2) (_db_keyword_(0,(keyword), 0) ? (a1) : (a2))
Definition at line 78 of file my_dbug.h.
DBUG_EVALUATE_IF
#define DBUG_EVALUATE_IF (keyword, a1, a2) (_db_keyword_(0,(keyword), 1) ? (a1) : (a2))
Definition at line 80 of file my_dbug.h.
DBUG_EXECUTE
#define DBUG_EXECUTE (keyword, a1) do {if (_db_keyword_(0, (keyword), 0)) { a1 }} while(0)
Definition at line 74 of file my_dbug.h.
DBUG_EXECUTE_IF
#define DBUG_EXECUTE_IF (keyword, a1) do {if (_db_keyword_(0, (keyword), 1)) { a1 }} while(0)
Definition at line 76 of file my_dbug.h.
DBUG_EXPLAIN
#define DBUG_EXPLAIN (buf, len) _db_explain_(0, (buf),(len))
Definition at line 97 of file my_dbug.h.
DBUG_EXPLAIN_INITIAL
#define DBUG_EXPLAIN_INITIAL (buf, len) _db_explain_init_((buf),(len))
Definition at line 98 of file my_dbug.h.
DBUG_FILE
#define DBUG_FILE _db_fp_()
Definition at line 89 of file my_dbug.h.
DBUG_LEAVE
#define DBUG_LEAVE _db_return_ (__LINE__, &_db_stack_frame_)
Definition at line 71 of file my_dbug.h.
DBUG_LOCK_FILE
#define DBUG_LOCK_FILE _db_lock_file_()
Definition at line 94 of file my_dbug.h.
DBUG_LONGJMP
#define DBUG_LONGJMP (a1, a2) (_db_longjmp_ (), longjmp (a1, a2))
Definition at line 91 of file my_dbug.h.
DBUG_POP
#define DBUG_POP () _db_pop_ ()
Definition at line 85 of file my_dbug.h.
DBUG_PRINT
#define DBUG_PRINT (keyword, arglist) do {_db_pargs_(__LINE__,keyword); _db_doprnt_ arglist;} while(0)
Definition at line 82 of file my_dbug.h.
DBUG_PROCESS
#define DBUG_PROCESS (a1) _db_process_(a1)
Definition at line 88 of file my_dbug.h.
DBUG_PUSH
#define DBUG_PUSH (a1) _db_push_ (a1)
Definition at line 84 of file my_dbug.h.
DBUG_RETURN
#define DBUG_RETURN (a1) do {DBUG_LEAVE; return(a1);} while(0)
Definition at line 72 of file my_dbug.h.
DBUG_SET
#define DBUG_SET (a1) _db_set_ (a1)
Definition at line 86 of file my_dbug.h.
DBUG_SET_INITIAL
#define DBUG_SET_INITIAL (a1) _db_set_init_ (a1)
Definition at line 87 of file my_dbug.h.
DBUG_SETJMP
#define DBUG_SETJMP (a1) (_db_setjmp_ (), setjmp (a1))
Definition at line 90 of file my_dbug.h.
DBUG_SUICIDE
#define DBUG_SUICIDE () (_db_flush_(), _db_suicide_())
Definition at line 136 of file my_dbug.h.
DBUG_SYNC_POINT
#define DBUG_SYNC_POINT (lock_name, lock_timeout)
Definition at line 187 of file my_dbug.h.
DBUG_UNLOCK_FILE
#define DBUG_UNLOCK_FILE _db_unlock_file_()
Definition at line 95 of file my_dbug.h.
DBUG_VOID_RETURN
#define DBUG_VOID_RETURN do {DBUG_LEAVE; return;} while(0)
Definition at line 73 of file my_dbug.h.
DEBUGGER_OFF
#define DEBUGGER_OFF do { _dbug_on_= 0; } while(0)
Definition at line 99 of file my_dbug.h.
DEBUGGER_ON
#define DEBUGGER_ON do { _dbug_on_= 1; } while(0)
Definition at line 100 of file my_dbug.h.
Function Documentation
_db_doprnt_()
void _db_doprnt_ (const char * format, ...)
_db_dump_()
void void _db_dump_ (uint _line_, const char * keyword, const unsigned char * memory, size_t length)
Definition at line 1311 of file dbug.c.
 {
   int pos;
   CODE_STATE *cs;
   get_code_state_or_return;
   if (_db_keyword_(cs, keyword, 0))
   {
     if (!cs->locked)
       pthread_mutex_lock(&THR_LOCK_dbug);
     DoPrefix(cs, _line_);
     if (TRACING)
     {
       Indent(cs, cs->level + 1);
       pos= min(max(cs->level-cs->stack->sub_level,0)*INDENT,80);
     }
     else
     {
       fprintf(cs->stack->out_file, "%s: ", cs->func);
     }
     (void) fprintf(cs->stack->out_file, "%s: Memory: 0x%lx  Bytes: (%ld)\n",
             keyword, (ulong) memory, (long) length);
     pos=0;
     while (length-- > 0)
     {
       uint tmp= *((unsigned char*) memory++);
       if ((pos+=3) >= 80)
       {
         fputc('\n',cs->stack->out_file);
         pos=3;
       }
       fputc(_dig_vec_upper[((tmp >> 4) & 15)], cs->stack->out_file);
       fputc(_dig_vec_upper[tmp & 15], cs->stack->out_file);
       fputc(' ',cs->stack->out_file);
     }
     (void) fputc('\n',cs->stack->out_file);
     DbugFlush(cs);
   }
 }
References _db_keyword_(), _dig_vec_upper, DbugFlush(), DoPrefix(), fprintf(), _db_code_state_::func, get_code_state_or_return, INDENT, Indent(), G3D::length(), _db_code_state_::level, _db_code_state_::locked, max, min, settings::out_file, pos(), _db_code_state_::stack, settings::sub_level, THR_LOCK_dbug, and TRACING.
_db_end_()
void _db_end_ (void)
Definition at line 1616 of file dbug.c.
 {
   struct settings *discard;
   static struct settings tmp;
   CODE_STATE *cs;
   /*
     Set _dbug_on_ to be able to do full reset even when DEBUGGER_OFF was
     called after dbug was initialized
   */
   _dbug_on_= 1;
   get_code_state_or_return;
   while ((discard= cs->stack))
   {
     if (discard == &init_settings)
       break;
     cs->stack= discard->next;
     FreeState(cs, discard, 1);
   }
   tmp= init_settings;
   /* Use mutex lock to make it less likely anyone access out_file */
   pthread_mutex_lock(&THR_LOCK_dbug);
   init_settings.flags=    OPEN_APPEND;
   init_settings.out_file= stderr;
   init_settings.prof_file= stderr;
   init_settings.maxdepth= 0;
   init_settings.delay= 0;
   init_settings.sub_level= 0;
   init_settings.functions= 0;
   init_settings.p_functions= 0;
   init_settings.keywords= 0;
   init_settings.processes= 0;
   pthread_mutex_unlock(&THR_LOCK_dbug);
   FreeState(cs, &tmp, 0);
 }
References _dbug_on_, settings::delay, settings::flags, FreeState(), settings::functions, get_code_state_or_return, init_settings, settings::keywords, settings::maxdepth, settings::next, OPEN_APPEND, settings::out_file, settings::p_functions, settings::processes, settings::prof_file, settings::sub_level, and THR_LOCK_dbug.
_db_enter_()
void _db_enter_ (const char * _func_, const char * _file_, uint _line_, struct _db_stack_frame_ * _stack_frame_)
Definition at line 1094 of file dbug.c.
 {
   int save_errno;
   CODE_STATE *cs;
   if (!((cs=code_state())))
   {
     _stack_frame_->level= 0; /* Set to avoid valgrind warnings if dbug is enabled later */
     _stack_frame_->prev= 0;
     return;
   }
   save_errno= errno;
   _stack_frame_->func= cs->func;
   _stack_frame_->file= cs->file;
   cs->func=  _func_;
   cs->file=  _file_;
   _stack_frame_->prev= cs->framep;
   _stack_frame_->level= ++cs->level | framep_trace_flag(cs, cs->framep);
   cs->framep= _stack_frame_;
   switch (DoTrace(cs)) {
   case ENABLE_TRACE:
     cs->framep->level|= TRACE_ON;
     if (!TRACING) break;
     /* fall through */
   case DO_TRACE:
     if (TRACING)
     {
       if (!cs->locked)
         pthread_mutex_lock(&THR_LOCK_dbug);
       DoPrefix(cs, _line_);
       Indent(cs, cs->level);
       (void) fprintf(cs->stack->out_file, ">%s\n", cs->func);
       DbugFlush(cs);                       /* This does a unlock */
     }
     break;
   case DISABLE_TRACE:
     cs->framep->level&= ~TRACE_ON;
     /* fall through */
   case DONT_TRACE:
     break;
   }
   errno=save_errno;
 }
References code_state(), DbugFlush(), DISABLE_TRACE, DO_TRACE, DONT_TRACE, DoPrefix(), DoTrace(), ENABLE_TRACE, errno, _db_code_state_::file, _db_stack_frame_::file, fprintf(), _db_code_state_::framep, framep_trace_flag, _db_code_state_::func, _db_stack_frame_::func, Indent(), _db_code_state_::level, _db_stack_frame_::level, _db_code_state_::locked, settings::out_file, _db_stack_frame_::prev, _db_code_state_::stack, THR_LOCK_dbug, TRACE_ON, and TRACING.
_db_explain_()
int _db_explain_ (struct _db_code_state_ * cs, char * buf, size_t len)
Definition at line 996 of file dbug.c.
 {
   char *start=buf, *end=buf+len-4;
   get_code_state_if_not_set_or_return *buf=0;
   op_list_to_buf('d', cs->stack->keywords, DEBUGGING);
   op_int_to_buf ('D', cs->stack->delay, 0);
   op_list_to_buf('f', cs->stack->functions, cs->stack->functions);
   op_bool_to_buf('F', cs->stack->flags & FILE_ON);
   op_bool_to_buf('i', cs->stack->flags & PID_ON);
   op_list_to_buf('g', cs->stack->p_functions, PROFILING);
   op_bool_to_buf('L', cs->stack->flags & LINE_ON);
   op_bool_to_buf('n', cs->stack->flags & DEPTH_ON);
   op_bool_to_buf('N', cs->stack->flags & NUMBER_ON);
   op_str_to_buf(
     ((cs->stack->flags & FLUSH_ON_WRITE ? 0 : 32) |
      (cs->stack->flags & OPEN_APPEND ? 'A' : 'O')),
     cs->stack->name, cs->stack->out_file != stderr);
   op_list_to_buf('p', cs->stack->processes, cs->stack->processes);
   op_bool_to_buf('P', cs->stack->flags & PROCESS_ON);
   op_bool_to_buf('r', cs->stack->sub_level != 0);
   op_intf_to_buf('t', cs->stack->maxdepth, MAXDEPTH, TRACING);
   op_bool_to_buf('T', cs->stack->flags & TIMESTAMP_ON);
   *buf= '\0';
   return 0;
 overflow:
   *end++= '.';
   *end++= '.';
   *end++= '.';
   *end=   '\0';
   return 1;
 }
References DEBUGGING, settings::delay, DEPTH_ON, FILE_ON, settings::flags, FLUSH_ON_WRITE, settings::functions, get_code_state_if_not_set_or_return, settings::keywords, LINE_ON, MAXDEPTH, settings::maxdepth, settings::name, NUMBER_ON, op_bool_to_buf, op_int_to_buf, op_intf_to_buf, op_list_to_buf, op_str_to_buf, OPEN_APPEND, settings::out_file, settings::p_functions, PID_ON, PROCESS_ON, settings::processes, PROFILING, _db_code_state_::stack, settings::sub_level, TIMESTAMP_ON, and TRACING.
Referenced by _db_explain_init_().
_db_explain_init_()
int _db_explain_init_ (char * buf, size_t len)
Definition at line 1052 of file dbug.c.
 {
   CODE_STATE cs;
   bzero((uchar*) &cs,sizeof(cs));
   cs.stack=&init_settings;
   return _db_explain_(&cs, buf, len);
 }
References _db_explain_(), bzero, init_settings, and _db_code_state_::stack.
_db_flush_()
void _db_flush_ ()
Definition at line 2219 of file dbug.c.
 {
   CODE_STATE *cs= NULL;
   get_code_state_or_return;
   (void) fflush(cs->stack->out_file);
 }
References get_code_state_or_return, NULL, settings::out_file, and _db_code_state_::stack.
_db_fp_()
FILE* _db_fp_ (void)
Definition at line 1685 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return NULL;
   return cs->stack->out_file;
 }
_db_get_func_()
const char* _db_get_func_ (void)
Definition at line 2262 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return NULL;
   return cs->func;
 }
References _db_code_state_::func, get_code_state_or_return, and NULL.
_db_is_pushed_()
int _db_is_pushed_ (void)
Returns TRUE if session-local settings have been set.
Definition at line 838 of file dbug.c.
 {
   CODE_STATE *cs= NULL;
   get_code_state_or_return FALSE;
   return (cs->stack != &init_settings);
 }
References FALSE, get_code_state_or_return, init_settings, NULL, and _db_code_state_::stack.
_db_keyword_()
my_bool _db_keyword_ (struct _db_code_state_ * cs, const char * keyword, int strict)
Definition at line 1712 of file dbug.c.
 {
   get_code_state_if_not_set_or_return FALSE;
   strict=strict ? INCLUDE : INCLUDE|MATCHED;
   return DEBUGGING && DoTrace(cs) & DO_TRACE &&
          InList(cs->stack->keywords, keyword) & strict;
 }
References DEBUGGING, DO_TRACE, DoTrace(), FALSE, get_code_state_if_not_set_or_return, INCLUDE, InList(), settings::keywords, MATCHED, and _db_code_state_::stack.
Referenced by _db_doprnt_(), and _db_dump_().
_db_lock_file_()
void _db_lock_file_ (void)
Definition at line 2246 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   pthread_mutex_lock(&THR_LOCK_dbug);
   cs->locked=1;
 }
References get_code_state_or_return, _db_code_state_::locked, and THR_LOCK_dbug.
_db_longjmp_()
void _db_longjmp_ (void)
_db_pargs_()
void _db_pargs_ (uint _line_, const char * keyword)
Definition at line 1219 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   cs->u_line= _line_;
   cs->u_keyword= keyword;
 }
References get_code_state_or_return, _db_code_state_::u_keyword, and _db_code_state_::u_line.
_db_pop_()
void _db_pop_ (void)
Definition at line 886 of file dbug.c.
 {
   struct settings *discard;
   uint old_fflags;
   CODE_STATE *cs;
   get_code_state_or_return;
   discard= cs->stack;
   if (discard != &init_settings)
   {
     old_fflags=fflags(cs);
     cs->stack= discard->next;
     FreeState(cs, discard, 1);
     FixTraceFlags(old_fflags, cs);
   }
 }
References fflags, FixTraceFlags(), FreeState(), get_code_state_or_return, init_settings, settings::next, and _db_code_state_::stack.
_db_process_()
void _db_process_ (const char * name)
Definition at line 410 of file dbug.c.
 {
   CODE_STATE *cs;
   if (!db_process)
     db_process= name;
   get_code_state_or_return;
   cs->process= name;
 }
References db_process, get_code_state_or_return, name, and _db_code_state_::process.
_db_push_()
void _db_push_ (const char * control)
Definition at line 822 of file dbug.c.
 {
   CODE_STATE *cs;
   uint old_fflags;
   get_code_state_or_return;
   old_fflags=fflags(cs);
   PushState(cs);
   if (DbugParse(cs, control))
     FixTraceFlags(old_fflags, cs);
 }
References DbugParse(), fflags, FixTraceFlags(), get_code_state_or_return, and PushState().
_db_return_()
void _db_return_ (uint _line_, struct _db_stack_frame_ * _stack_frame_)
Definition at line 1160 of file dbug.c.
 {
   int save_errno=errno;
   uint _slevel_= _stack_frame_->level & ~TRACE_ON;
   CODE_STATE *cs;
   get_code_state_or_return;
   if (cs->framep != _stack_frame_)
   {
     char buf[512];
     my_snprintf(buf, sizeof(buf), ERR_MISSING_RETURN, cs->func);
     DbugExit(buf);
   }
   if (DoTrace(cs) & DO_TRACE)
   {
     if (TRACING)
     {
       if (!cs->locked)
         pthread_mutex_lock(&THR_LOCK_dbug);
       DoPrefix(cs, _line_);
       Indent(cs, cs->level);
       (void) fprintf(cs->stack->out_file, "<%s\n", cs->func);
       DbugFlush(cs);
     }
   }
   /*
     Check to not set level < 0. This can happen if DBUG was disabled when
     function was entered and enabled in function.
   */
   cs->level= _slevel_ != 0 ? _slevel_ - 1 : 0;
   cs->func= _stack_frame_->func;
   cs->file= _stack_frame_->file;
   if (cs->framep != NULL)
     cs->framep= cs->framep->prev;
   errno=save_errno;
 }
References DbugExit(), DbugFlush(), DO_TRACE, DoPrefix(), DoTrace(), ERR_MISSING_RETURN, errno, _db_code_state_::file, _db_stack_frame_::file, fprintf(), _db_code_state_::framep, _db_code_state_::func, _db_stack_frame_::func, get_code_state_or_return, Indent(), _db_code_state_::level, _db_stack_frame_::level, _db_code_state_::locked, my_snprintf(), NULL, settings::out_file, _db_stack_frame_::prev, _db_code_state_::stack, THR_LOCK_dbug, TRACE_ON, and TRACING.
_db_set_()
void _db_set_ (const char * control)
Definition at line 792 of file dbug.c.
 {
   CODE_STATE *cs;
   uint old_fflags;
   get_code_state_or_return;
   old_fflags=fflags(cs);
   if (cs->stack == &init_settings)
     PushState(cs);
   if (DbugParse(cs, control))
     FixTraceFlags(old_fflags, cs);
 }
References DbugParse(), fflags, FixTraceFlags(), get_code_state_or_return, init_settings, PushState(), and _db_code_state_::stack.
_db_set_init_()
void _db_set_init_ (const char * control)
Definition at line 860 of file dbug.c.
 {
   CODE_STATE tmp_cs;
   bzero((uchar*) &tmp_cs, sizeof(tmp_cs));
   tmp_cs.stack= &init_settings;
   tmp_cs.process= db_process ? db_process : "dbug";
   DbugParse(&tmp_cs, control);
 }
References bzero, db_process, DbugParse(), init_settings, _db_code_state_::process, and _db_code_state_::stack.
_db_setjmp_()
void _db_setjmp_ (void)
_db_suicide_()
void _db_suicide_ ()
Definition at line 2228 of file dbug.c.
 {
   int retval;
   sigset_t new_mask;
   sigfillset(&new_mask);
   fprintf(stderr, "SIGKILL myself\n");
   fflush(stderr);
   retval= kill(getpid(), SIGKILL);
   assert(retval == 0);
   retval= sigsuspend(&new_mask);
   fprintf(stderr, "sigsuspend returned %d errno %d \n", retval, errno);
   assert(FALSE); /* With full signal mask, we should never return here. */
 }
References assert(), errno, FALSE, and fprintf().
_db_unlock_file_()
void _db_unlock_file_ (void)
Definition at line 2254 of file dbug.c.
 {
   CODE_STATE *cs;
   get_code_state_or_return;
   cs->locked=0;
   pthread_mutex_unlock(&THR_LOCK_dbug);
 }
References get_code_state_or_return, _db_code_state_::locked, and THR_LOCK_dbug.
Variable Documentation
_dbug_on_
my_bool _dbug_on_ extern
Definition at line 241 of file dbug.c.
Referenced by _db_end_(), and code_state().