Azerotcore-wotlk: npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI Struct Reference
npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI Struct Reference
Public Member Functions
npc_commander_eligor_dawnbringerAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void StoreTargets ()
void ChangeImage (uint32 entry, uint32 model, uint8 text)
void TurnAudience ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
ObjectGuid audienceList [10]
ObjectGuid imageList [5]
uint8 talkWing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1508 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
npc_commander_eligor_dawnbringerAI()
npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::npc_commander_eligor_dawnbringerAI (Creature * creature) inline
Definition at line 1510 of file zone_dragonblight.cpp.
                                                                : ScriptedAI(creature)
         {
             talkWing = 0;
         }
References talkWing.
Member Function Documentation
ChangeImage()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage (uint32 entry, uint32 model, uint8 text) inline
Definition at line 1661 of file zone_dragonblight.cpp.
         {
             if (Creature* creature = ObjectAccessor::GetCreature(*me, imageList[talkWing]))
             {
                 Talk(text);
                 creature->SetEntry(entry);
                 creature->SetDisplayId(model);
                 creature->CastSpell(creature, SPELL_HEROIC_IMAGE_CHANNEL);
                 _events.ScheduleEvent(EVENT_TALK_COMPLETE, 40000);
             }
         }
References _events, EVENT_TALK_COMPLETE, ObjectAccessor::GetCreature(), imageList, ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_HEROIC_IMAGE_CHANNEL, CreatureAI::Talk(), and talkWing.
Referenced by MovementInform().
MovementInform()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1529 of file zone_dragonblight.cpp.
         {
             if (type == POINT_MOTION_TYPE)
             {
                 if (id == 1)
                 {
                     me->SetFacingTo(PosTalkLocations[talkWing].m_orientation);
                     TurnAudience();
                     switch (talkWing)
                     {
                         case 0: // Pinnacle of Naxxramas
{
                                 switch (urand (0, 1))
{
                                     case 0:
                                         ChangeImage(NPC_IMAGE_OF_KELTHUZAD, MODEL_IMAGE_OF_KELTHUZAD, SAY_KELTHUZAD_1);
                                         _events.ScheduleEvent(EVENT_KELTHUZAD_2, 8000);
                                         break;
                                     case 1:
                                         ChangeImage(NPC_IMAGE_OF_SAPPHIRON, MODEL_IMAGE_OF_SAPPHIRON, SAY_SAPPHIRON);
                                         break;
                                 }
                             }
                             break;
                         case 1: // Death knight wing of Naxxramas
{
                                 switch (urand (0, 2))
{
                                     case 0:
                                         ChangeImage(NPC_IMAGE_OF_RAZUVIOUS, MODEL_IMAGE_OF_RAZUVIOUS, SAY_RAZUVIOUS);
                                         break;
                                     case 1:
                                         ChangeImage(NPC_IMAGE_OF_GOTHIK, MODEL_IMAGE_OF_GOTHIK, SAY_GOTHIK);
                                         break;
                                     case 2:
                                         ChangeImage(NPC_IMAGE_OF_THANE, MODEL_IMAGE_OF_THANE, SAY_DEATH_KNIGHTS_1);
                                         _events.ScheduleEvent(EVENT_DEATH_KNIGHTS_2, 10000);
                                         break;
                                 }
                             }
                             break;
                         case 2: // Blighted abomination wing of Naxxramas
{
                                 switch (urand (0, 3))
{
                                     case 0:
                                         ChangeImage(NPC_IMAGE_OF_PATCHWERK, MODEL_IMAGE_OF_PATCHWERK, SAY_PATCHWERK);
                                         break;
                                     case 1:
                                         ChangeImage(NPC_IMAGE_OF_GROBBULUS, MODEL_IMAGE_OF_GROBBULUS, SAY_GROBBULUS);
                                         break;
                                     case 2:
                                         ChangeImage(NPC_IMAGE_OF_THADDIUS, MODEL_IMAGE_OF_THADDIUS, SAY_THADDIUS);
                                         break;
                                     case 3:
                                         ChangeImage(NPC_IMAGE_OF_GLUTH, MODEL_IMAGE_OF_GLUTH, SAY_GLUTH);
                                         break;
                                 }
                             }
                             break;
                         case 3: // Accursed spider wing of Naxxramas
{
                                 switch (urand (0, 2))
{
                                     case 0:
                                         ChangeImage(NPC_IMAGE_OF_ANUBREKHAN, MODEL_IMAGE_OF_ANUBREKHAN, SAY_ANUBREKHAN);
                                         break;
                                     case 1:
                                         ChangeImage(NPC_IMAGE_OF_FAERLINA, MODEL_IMAGE_OF_FAERLINA, SAY_FAERLINA);
                                         break;
                                     case 2:
                                         ChangeImage(NPC_IMAGE_OF_MAEXXNA, MODEL_IMAGE_OF_MAEXXNA, SAY_MAEXXNA);
                                         break;
                                 }
                             }
                             break;
                         case 4: // Dread plague wing of Naxxramas
{
                                 switch (urand (0, 2))
{
                                     case 0:
                                         ChangeImage(NPC_IMAGE_OF_NOTH, MODEL_IMAGE_OF_NOTH, SAY_NOTH);
                                         break;
                                     case 1:
                                         ChangeImage(NPC_IMAGE_OF_HEIGAN, MODEL_IMAGE_OF_HEIGAN, SAY_HEIGAN_1);
                                         _events.ScheduleEvent(EVENT_HEIGAN_2, 8000);
                                         break;
                                     case 2:
                                         ChangeImage(NPC_IMAGE_OF_LOATHEB, MODEL_IMAGE_OF_LOATHEB, SAY_LOATHEB);
                                         break;
                                 }
                             }
                             break;
                         case 5: // Home
                             _events.ScheduleEvent(EVENT_START_RANDOM, 30000);
                             break;
                     }
                 }
             }
         }
References _events, ChangeImage(), EVENT_DEATH_KNIGHTS_2, EVENT_HEIGAN_2, EVENT_KELTHUZAD_2, EVENT_START_RANDOM, ScriptedAI::me, MODEL_IMAGE_OF_ANUBREKHAN, MODEL_IMAGE_OF_FAERLINA, MODEL_IMAGE_OF_GLUTH, MODEL_IMAGE_OF_GOTHIK, MODEL_IMAGE_OF_GROBBULUS, MODEL_IMAGE_OF_HEIGAN, MODEL_IMAGE_OF_KELTHUZAD, MODEL_IMAGE_OF_LOATHEB, MODEL_IMAGE_OF_MAEXXNA, MODEL_IMAGE_OF_NOTH, MODEL_IMAGE_OF_PATCHWERK, MODEL_IMAGE_OF_RAZUVIOUS, MODEL_IMAGE_OF_SAPPHIRON, MODEL_IMAGE_OF_THADDIUS, MODEL_IMAGE_OF_THANE, NPC_IMAGE_OF_ANUBREKHAN, NPC_IMAGE_OF_FAERLINA, NPC_IMAGE_OF_GLUTH, NPC_IMAGE_OF_GOTHIK, NPC_IMAGE_OF_GROBBULUS, NPC_IMAGE_OF_HEIGAN, NPC_IMAGE_OF_KELTHUZAD, NPC_IMAGE_OF_LOATHEB, NPC_IMAGE_OF_MAEXXNA, NPC_IMAGE_OF_NOTH, NPC_IMAGE_OF_PATCHWERK, NPC_IMAGE_OF_RAZUVIOUS, NPC_IMAGE_OF_SAPPHIRON, NPC_IMAGE_OF_THADDIUS, NPC_IMAGE_OF_THANE, POINT_MOTION_TYPE, PosTalkLocations, SAY_ANUBREKHAN, SAY_DEATH_KNIGHTS_1, SAY_FAERLINA, SAY_GLUTH, SAY_GOTHIK, SAY_GROBBULUS, SAY_HEIGAN_1, SAY_KELTHUZAD_1, SAY_LOATHEB, SAY_MAEXXNA, SAY_NOTH, SAY_PATCHWERK, SAY_RAZUVIOUS, SAY_SAPPHIRON, SAY_THADDIUS, EventMap::ScheduleEvent(), Unit::SetFacingTo(), talkWing, TurnAudience(), and urand().
Reset()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1515 of file zone_dragonblight.cpp.
         {
             talkWing = 0;
             for (uint8 i = 0; i < 10; ++i)
                 audienceList[i].Clear();
             for (uint8 i = 0; i < 5; ++i)
                 imageList[i].Clear();
             _events.ScheduleEvent(EVENT_GET_TARGETS, 5000);
             _events.ScheduleEvent(EVENT_START_RANDOM, 20000);
         }
References _events, audienceList, EVENT_GET_TARGETS, EVENT_START_RANDOM, imageList, EventMap::ScheduleEvent(), and talkWing.
StoreTargets()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::StoreTargets () inline
Definition at line 1631 of file zone_dragonblight.cpp.
         {
             uint8 creturesCount = 0;
             for (uint8 ii = 0; ii < 3; ++ii)
             {
                 std::list<Creature*> creatureList;
                 GetCreatureListWithEntryInGrid(creatureList, me, AudienceMobs[ii], 15.0f);
                 for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
                 {
                     if (Creature* creature = *itr)
                     {
                         audienceList[creturesCount] = creature->GetGUID();
                         ++creturesCount;
                     }
                 }
             }
             if (Creature* creature = me->FindNearestCreature(NPC_IMAGE_OF_KELTHUZAD, 20.0f, true))
                 imageList[0] = creature->GetGUID();
             if (Creature* creature = me->FindNearestCreature(NPC_IMAGE_OF_RAZUVIOUS, 20.0f, true))
                 imageList[1] = creature->GetGUID();
             if (Creature* creature = me->FindNearestCreature(NPC_IMAGE_OF_PATCHWERK, 20.0f, true))
                 imageList[2] = creature->GetGUID();
             if (Creature* creature = me->FindNearestCreature(NPC_IMAGE_OF_ANUBREKHAN, 20.0f, true))
                 imageList[3] = creature->GetGUID();
             if (Creature* creature = me->FindNearestCreature(NPC_IMAGE_OF_NOTH, 20.0f, true))
                 imageList[4] = creature->GetGUID();
         }
References audienceList, AudienceMobs, WorldObject::FindNearestCreature(), GetCreatureListWithEntryInGrid(), imageList, ScriptedAI::me, NPC_IMAGE_OF_ANUBREKHAN, NPC_IMAGE_OF_KELTHUZAD, NPC_IMAGE_OF_NOTH, NPC_IMAGE_OF_PATCHWERK, and NPC_IMAGE_OF_RAZUVIOUS.
Referenced by UpdateAI().
TurnAudience()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::TurnAudience () inline
Definition at line 1673 of file zone_dragonblight.cpp.
         {
             for (uint8 i = 0; i < 10; ++i)
             {
                 if (Creature* creature = ObjectAccessor::GetCreature(*me, audienceList[i]))
                     creature->SetFacingToObject(me);
             }
         }
References audienceList, ObjectAccessor::GetCreature(), and ScriptedAI::me.
Referenced by MovementInform().
UpdateAI()
void npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1682 of file zone_dragonblight.cpp.
         {
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_START_RANDOM:
                         talkWing = urand (0, 4);
                         Talk(talkWing);
                         _events.ScheduleEvent(EVENT_MOVE_TO_POINT, 8000);
                         break;
                     case EVENT_MOVE_TO_POINT:
                         me->SetWalk(true);
                         me->GetMotionMaster()->Clear();
                         me->GetMotionMaster()->MovePoint(1, PosTalkLocations[talkWing].m_positionX, PosTalkLocations[talkWing].m_positionY, PosTalkLocations[talkWing].m_positionZ);
                         break;
                     case EVENT_TALK_COMPLETE:
                         talkWing = 5;
                         Talk(talkWing);
                         _events.ScheduleEvent(EVENT_MOVE_TO_POINT, 5000);
                         break;
                     case EVENT_GET_TARGETS:
                         StoreTargets();
                         break;
                     case EVENT_KELTHUZAD_2:
                         Talk(SAY_KELTHUZAD_2);
                         _events.ScheduleEvent(EVENT_KELTHUZAD_3, 8000);
                         break;
                     case EVENT_KELTHUZAD_3:
                         Talk(SAY_KELTHUZAD_3);
                         break;
                     case EVENT_DEATH_KNIGHTS_2:
                         Talk(SAY_DEATH_KNIGHTS_2);
                         if (Creature* creature = ObjectAccessor::GetCreature(*me, imageList[talkWing]))
{
                             creature->SetEntry(NPC_IMAGE_OF_BLAUMEUX);
                             creature->SetDisplayId(MODEL_IMAGE_OF_BLAUMEUX);
                         }
                         _events.ScheduleEvent(EVENT_DEATH_KNIGHTS_3, 10000);
                         break;
                     case EVENT_DEATH_KNIGHTS_3:
                         Talk(SAY_DEATH_KNIGHTS_3);
                         if (Creature* creature = ObjectAccessor::GetCreature(*me, imageList[talkWing]))
{
                             creature->SetEntry(NPC_IMAGE_OF_ZELIEK);
                             creature->SetDisplayId(MODEL_IMAGE_OF_ZELIEK);
                         }
                         _events.ScheduleEvent(EVENT_DEATH_KNIGHTS_4, 10000);
                         break;
                     case EVENT_DEATH_KNIGHTS_4:
                         Talk(SAY_DEATH_KNIGHTS_4);
                         break;
                     case EVENT_HEIGAN_2:
                         Talk(SAY_HEIGAN_2);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, MotionMaster::Clear(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_DEATH_KNIGHTS_2, EVENT_DEATH_KNIGHTS_3, EVENT_DEATH_KNIGHTS_4, EVENT_GET_TARGETS, EVENT_HEIGAN_2, EVENT_KELTHUZAD_2, EVENT_KELTHUZAD_3, EVENT_MOVE_TO_POINT, EVENT_START_RANDOM, EVENT_TALK_COMPLETE, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), imageList, ScriptedAI::me, MODEL_IMAGE_OF_BLAUMEUX, MODEL_IMAGE_OF_ZELIEK, MotionMaster::MovePoint(), NPC_IMAGE_OF_BLAUMEUX, NPC_IMAGE_OF_ZELIEK, PosTalkLocations, SAY_DEATH_KNIGHTS_2, SAY_DEATH_KNIGHTS_3, SAY_DEATH_KNIGHTS_4, SAY_HEIGAN_2, SAY_KELTHUZAD_2, SAY_KELTHUZAD_3, EventMap::ScheduleEvent(), Creature::SetWalk(), StoreTargets(), CreatureAI::Talk(), talkWing, EventMap::Update(), and urand().
Member Data Documentation
_events
EventMap npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::_events private
Definition at line 1746 of file zone_dragonblight.cpp.
Referenced by ChangeImage(), MovementInform(), Reset(), and UpdateAI().
audienceList
ObjectGuid npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::audienceList[10] private
Definition at line 1747 of file zone_dragonblight.cpp.
Referenced by Reset(), StoreTargets(), and TurnAudience().
imageList
ObjectGuid npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::imageList[5] private
Definition at line 1748 of file zone_dragonblight.cpp.
Referenced by ChangeImage(), Reset(), StoreTargets(), and UpdateAI().
talkWing
uint8 npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::talkWing private
Definition at line 1749 of file zone_dragonblight.cpp.
Referenced by ChangeImage(), MovementInform(), npc_commander_eligor_dawnbringerAI(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp