Azerotcore-wotlk: deps/mysqllite/mysys/my_aes.c File Reference
my_aes.c File Reference
#include <my_global.h>
#include <m_string.h>
#include "my_aes.h"
Classes
struct KEYINSTANCE
Macros
#define AES_BLOCK_SIZE 16 /* Block size in bytes */
#define AES_BAD_DATA -1 /* If bad data discovered during decoding */
Enumerations
enum encrypt_dir { AES_ENCRYPT , AES_DECRYPT }
Functions
static int my_aes_create_key (KEYINSTANCE *aes_key, enum encrypt_dir direction, const char *key, int key_length)
int my_aes_encrypt (const char *source, int source_length, char *dest, const char *key, int key_length)
int my_aes_decrypt (const char *source, int source_length, char *dest, const char *key, int key_length)
int my_aes_get_size (int source_length)
Macro Definition Documentation
AES_BAD_DATA
#define AES_BAD_DATA -1 /* If bad data discovered during decoding */
Definition at line 31 of file my_aes.c.
AES_BLOCK_SIZE
#define AES_BLOCK_SIZE 16 /* Block size in bytes */
Definition at line 29 of file my_aes.c.
Enumeration Type Documentation
encrypt_dir
enum encrypt_dir
Enumerator
AES_ENCRYPT
AES_DECRYPT
Definition at line 27 of file my_aes.c.
 { AES_ENCRYPT, AES_DECRYPT };
Function Documentation
my_aes_create_key()
static int my_aes_create_key (KEYINSTANCE * aes_key, enum encrypt_dir direction, const char * key, int key_length) static
Definition at line 58 of file my_aes.c.
 {
   uint8 rkey[AES_KEY_LENGTH/8];  /* The real key to be used for encryption */
   uint8 *rkey_end=rkey+AES_KEY_LENGTH/8; /* Real key boundary */
   uint8 *ptr;           /* Start of the real key*/
   const char *sptr;         /* Start of the working key */
   const char *key_end=key+key_length;   /* Working key boundary*/
   bzero((char*) rkey,AES_KEY_LENGTH/8);      /* Set initial key  */
   for (ptr= rkey, sptr= key; sptr < key_end; ptr++,sptr++)
   {
     if (ptr == rkey_end)
       ptr= rkey;  /*  Just loop over tmp_key until we used all key */
     *ptr^= (uint8) *sptr;
   }
 #ifdef AES_USE_KEY_BITS
   /*
    This block is intended to allow more weak encryption if application
    build with libmysqld needs to correspond to export regulations
    It should be never used in normal distribution as does not give
    any speed improvement.
    To get worse security define AES_USE_KEY_BITS to number of bits
    you want key to be. It should be divisible by 8
    WARNING: Changing this value results in changing of enryption for
    all key lengths  so altering this value will result in impossibility
    to decrypt data encrypted with previous value
   */
 #define AES_USE_KEY_BYTES (AES_USE_KEY_BITS/8)
   /*
    To get weaker key we use first AES_USE_KEY_BYTES bytes of created key
    and cyclically copy them until we created all required key length
   */
   for (ptr= rkey+AES_USE_KEY_BYTES, sptr=rkey ; ptr < rkey_end;
        ptr++,sptr++)
   {
     if (sptr == rkey+AES_USE_KEY_BYTES)
       sptr=rkey;
     *ptr=*sptr;
   }
 #endif
   if (direction == AES_DECRYPT)
      aes_key->nr = rijndaelKeySetupDec(aes_key->rk, rkey, AES_KEY_LENGTH);
   else
      aes_key->nr = rijndaelKeySetupEnc(aes_key->rk, rkey, AES_KEY_LENGTH);
   return 0;
 }
References AES_DECRYPT, AES_KEY_LENGTH, bzero, KEYINSTANCE::nr, ptr(), rijndaelKeySetupDec(), rijndaelKeySetupEnc(), and KEYINSTANCE::rk.
Referenced by my_aes_decrypt(), and my_aes_encrypt().
my_aes_decrypt()
int my_aes_decrypt (const char * source, int source_length, char * dest, const char * key, int key_length)
Definition at line 174 of file my_aes.c.
 {
   KEYINSTANCE aes_key;
   uint8 block[AES_BLOCK_SIZE];  /* 128 bit block used for padding */
   int rc;           /* Result codes */
   int num_blocks;       /* Number of complete blocks */
   uint pad_len;         /* Pad size for the last block */
   int i;
   if ((rc=my_aes_create_key(&aes_key,AES_DECRYPT,key,key_length)))
     return rc;
   num_blocks = source_length/AES_BLOCK_SIZE;
   if ((source_length != num_blocks*AES_BLOCK_SIZE) || num_blocks ==0 )
     return AES_BAD_DATA; /* Input size has to be even and at least one block */
   for (i = num_blocks-1; i > 0; i--)   /* Decode all but last blocks */
   {
     rijndaelDecrypt(aes_key.rk, aes_key.nr, (const uint8*) source,
             (uint8*) dest);
     source+= AES_BLOCK_SIZE;
     dest+= AES_BLOCK_SIZE;
   }
   rijndaelDecrypt(aes_key.rk, aes_key.nr, (const uint8*) source, block);
   /* Use last char in the block as size */
   pad_len = (uint) (uchar) block[AES_BLOCK_SIZE-1];
   if (pad_len > AES_BLOCK_SIZE)
     return AES_BAD_DATA;
   /* We could also check whole padding but we do not really need this */
   memcpy(dest, block, AES_BLOCK_SIZE - pad_len);
   return AES_BLOCK_SIZE*num_blocks - pad_len;
 }
References AES_BAD_DATA, AES_BLOCK_SIZE, AES_DECRYPT, memcpy, my_aes_create_key(), KEYINSTANCE::nr, rijndaelDecrypt(), and KEYINSTANCE::rk.
my_aes_encrypt()
int my_aes_encrypt (const char * source, int source_length, char * dest, const char * key, int key_length)
Definition at line 126 of file my_aes.c.
 {
   KEYINSTANCE aes_key;
   uint8 block[AES_BLOCK_SIZE];  /* 128 bit block used for padding */
   int rc;           /* result codes */
   int num_blocks;       /* number of complete blocks */
   char pad_len;         /* pad size for the last block */
   int i;
   if ((rc= my_aes_create_key(&aes_key,AES_ENCRYPT,key,key_length)))
     return rc;
   num_blocks = source_length/AES_BLOCK_SIZE;
   for (i = num_blocks; i > 0; i--)   /* Encode complete blocks */
   {
     rijndaelEncrypt(aes_key.rk, aes_key.nr, (const uint8*) source,
             (uint8*) dest);
     source+= AES_BLOCK_SIZE;
     dest+= AES_BLOCK_SIZE;
   }
   /* Encode the rest. We always have incomplete block */
   pad_len = AES_BLOCK_SIZE - (source_length - AES_BLOCK_SIZE*num_blocks);
   memcpy(block, source, 16 - pad_len);
   bfill(block + AES_BLOCK_SIZE - pad_len, pad_len, pad_len);
   rijndaelEncrypt(aes_key.rk, aes_key.nr, block, (uint8*) dest);
   return AES_BLOCK_SIZE*(num_blocks + 1);
 }
References AES_BLOCK_SIZE, AES_ENCRYPT, bfill, memcpy, my_aes_create_key(), KEYINSTANCE::nr, rijndaelEncrypt(), and KEYINSTANCE::rk.
my_aes_get_size()
int my_aes_get_size (int source_length)
Definition at line 224 of file my_aes.c.
 {
   return AES_BLOCK_SIZE*(source_length/AES_BLOCK_SIZE)+AES_BLOCK_SIZE;
 }
References AES_BLOCK_SIZE.