Azerotcore-wotlk: npc_nerubian_burrower::npc_nerubian_burrowerAI Struct Reference
npc_nerubian_burrower::npc_nerubian_burrowerAI Struct Reference
Public Member Functions
npc_nerubian_burrowerAI (Creature *pCreature)
void Reset () override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
bool CanAIAttack (const Unit *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 614 of file boss_anubarak_trial.cpp.
Constructor & Destructor Documentation
npc_nerubian_burrowerAI()
npc_nerubian_burrower::npc_nerubian_burrowerAI::npc_nerubian_burrowerAI (Creature * pCreature) inline
Definition at line 616 of file boss_anubarak_trial.cpp.
                                                      : ScriptedAI(pCreature)
         {
             // I am summoned by another npc (SPELL_EFFECT_FORCE_CAST), inform Anub'arak
             if (InstanceScript* pInstance = me->GetInstanceScript())
                 if (ObjectGuid guid = pInstance->GetGuidData(TYPE_ANUBARAK))
                     if (Creature* anub = pInstance->instance->GetCreature(guid))
                         CAST_AI(boss_anubarak_trial::boss_anubarak_trialAI, anub->AI())->JustSummoned(me);
         }
References CAST_AI, WorldObject::GetInstanceScript(), ScriptedAI::me, and TYPE_ANUBARAK.
Member Function Documentation
CanAIAttack()
bool npc_nerubian_burrower::npc_nerubian_burrowerAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 716 of file boss_anubarak_trial.cpp.
         {
             return target->GetEntry() != NPC_FROST_SPHERE;
         }
References Object::GetEntry(), and NPC_FROST_SPHERE.
JustDied()
void npc_nerubian_burrower::npc_nerubian_burrowerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 711 of file boss_anubarak_trial.cpp.
         {
             me->m_Events.AddEvent(new HideNpcEvent(*me), me->m_Events.CalculateTime(5000));
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::m_Events, and ScriptedAI::me.
Reset()
void npc_nerubian_burrower::npc_nerubian_burrowerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 627 of file boss_anubarak_trial.cpp.
         {
             me->SetCorpseDelay(10 * 60);
             me->CastSpell(me, SPELL_EXPOSE_WEAKNESS, true);
             me->CastSpell(me, SPELL_SPIDER_FRENZY, true);
             events.Reset();
             events.RescheduleEvent(EVENT_SUBMERGE, 30000);
             if( IsHeroic() )
                 events.RescheduleEvent(EVENT_SPELL_SHADOW_STRIKE, urand(30000, 45000));
             if( Unit* target = me->SelectNearestTarget(250.0f) )
             {
                 AttackStart(target);
                 DoZoneInCombat();
             }
         }
References ScriptedAI::AttackStart(), Unit::CastSpell(), CreatureAI::DoZoneInCombat(), EVENT_SPELL_SHADOW_STRIKE, EVENT_SUBMERGE, ScriptedAI::IsHeroic(), ScriptedAI::me, Creature::SelectNearestTarget(), Creature::SetCorpseDelay(), SPELL_EXPOSE_WEAKNESS, SPELL_SPIDER_FRENZY, and urand().
SpellHitTarget()
void npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 643 of file boss_anubarak_trial.cpp.
         {
             if( !target || !spell )
                 return;
             if( spell->Id == SPELL_SHADOW_STRIKE )
             {
                 float o = target->GetOrientation();
                 if( o >= M_PI )
                     o -= M_PI;
                 else
                     o += M_PI;
                 me->NearTeleportTo(target->GetPositionX() + cos(o) * 5.0f, target->GetPositionY() + sin(o) * 5.0f, target->GetPositionZ() + 0.6f, target->GetOrientation());
                 AttackStart(target);
                 me->GetMotionMaster()->MoveChase(target);
                 events.DelayEvents(3000);
             }
         }
References ScriptedAI::AttackStart(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveChase(), Unit::NearTeleportTo(), and SPELL_SHADOW_STRIKE.
UpdateAI()
void npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 662 of file boss_anubarak_trial.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_SHADOW_STRIKE:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 250.0f, true) )
                         me->CastSpell(target, SPELL_SHADOW_STRIKE, false);
                     events.RepeatEvent(urand(30000, 45000));
                     break;
                 case EVENT_SUBMERGE:
                     if( HealthBelowPct(80) && !me->HasAura(RAID_MODE(66193, 67855, 67856, 67857)) ) // not having permafrost - allow submerge
                     {
                         me->GetMotionMaster()->MoveIdle();
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         me->RemoveAllAuras();
                         me->CastSpell(me, SPELL_EXPOSE_WEAKNESS, true);
                         me->CastSpell(me, SPELL_SPIDER_FRENZY, true);
                         me->CastSpell(me, SPELL_SUBMERGE, false);
                         events.DelayEvents(15000);
                         events.RescheduleEvent(EVENT_EMERGE, 10000);
                     }
                     else
                         events.RepeatEvent(3000);
                     break;
                 case EVENT_EMERGE:
                     me->SetHealth(me->GetMaxHealth());
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->CastSpell(me, SPELL_EMERGE, false);
                     me->RemoveAura(SPELL_SUBMERGE);
                     events.RescheduleEvent(EVENT_SUBMERGE, 30000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_EMERGE, EVENT_SPELL_SHADOW_STRIKE, EVENT_SUBMERGE, Unit::GetMaxHealth(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), ScriptedAI::RAID_MODE(), Unit::RemoveAllAuras(), Unit::RemoveAura(), Object::RemoveFlag(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Object::SetFlag(), Unit::SetHealth(), SPELL_EMERGE, SPELL_EXPOSE_WEAKNESS, SPELL_SHADOW_STRIKE, SPELL_SPIDER_FRENZY, SPELL_SUBMERGE, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_nerubian_burrower::npc_nerubian_burrowerAI::events
Definition at line 625 of file boss_anubarak_trial.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp