Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tsd_win.h File Reference
tsd_win.h File Reference
Classes
struct tsd_wrapper_t
Macros
#define JEMALLOC_INTERNAL_TSD_WIN_H
Functions
JEMALLOC_ALWAYS_INLINE bool tsd_cleanup_wrapper (void)
JEMALLOC_ALWAYS_INLINE void tsd_wrapper_set (tsd_wrapper_t *wrapper)
JEMALLOC_ALWAYS_INLINE tsd_wrapper_t * tsd_wrapper_get (bool init)
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_get (bool init)
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t *val)
Variables
DWORD tsd_tsd
tsd_wrapper_t tsd_boot_wrapper
bool tsd_booted
Macro Definition Documentation
JEMALLOC_INTERNAL_TSD_WIN_H
#define JEMALLOC_INTERNAL_TSD_WIN_H
Definition at line 4 of file tsd_win.h.
Function Documentation
tsd_boot()
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
Definition at line 98 of file tsd_win.h.
                {
     if (tsd_boot0()) {
         return true;
     }
     tsd_boot1();
     return false;
 }
References tsd_boot0(), and tsd_boot1().
tsd_boot0()
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
Definition at line 70 of file tsd_win.h.
                 {
     tsd_tsd = TlsAlloc();
     if (tsd_tsd == TLS_OUT_OF_INDEXES) {
         return true;
     }
     malloc_tsd_cleanup_register(&tsd_cleanup_wrapper);
     tsd_wrapper_set(&tsd_boot_wrapper);
     tsd_booted = true;
     return false;
 }
References malloc_tsd_cleanup_register, tsd_boot_wrapper, tsd_booted, tsd_cleanup_wrapper(), tsd_tsd, and tsd_wrapper_set().
Referenced by tsd_boot().
tsd_boot1()
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
Definition at line 82 of file tsd_win.h.
                 {
     tsd_wrapper_t *wrapper;
     wrapper = (tsd_wrapper_t *)
         malloc_tsd_malloc(sizeof(tsd_wrapper_t));
     if (wrapper == NULL) {
         malloc_write("<jemalloc>: Error allocating TSD\n");
         abort();
     }
     tsd_boot_wrapper.initialized = false;
     tsd_cleanup(&tsd_boot_wrapper.val);
     wrapper->initialized = false;
     tsd_t initializer = TSD_INITIALIZER;
     wrapper->val = initializer;
     tsd_wrapper_set(wrapper);
 }
References tsd_wrapper_t::initialized, malloc_tsd_malloc, malloc_write, NULL, tsd_boot_wrapper, tsd_cleanup, TSD_INITIALIZER, tsd_wrapper_set(), and tsd_wrapper_t::val.
Referenced by tsd_boot().
tsd_booted_get()
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
Definition at line 107 of file tsd_win.h.
                      {
     return tsd_booted;
 }
References tsd_booted.
tsd_cleanup_wrapper()
JEMALLOC_ALWAYS_INLINE bool tsd_cleanup_wrapper (void)
Definition at line 17 of file tsd_win.h.
{
     DWORD error = GetLastError();
     tsd_wrapper_t *wrapper = (tsd_wrapper_t *)TlsGetValue(tsd_tsd);
     SetLastError(error);
     if (wrapper == NULL) {
         return false;
     }
     if (wrapper->initialized) {
         wrapper->initialized = false;
         tsd_cleanup(&wrapper->val);
         if (wrapper->initialized) {
             /* Trigger another cleanup round. */
             return true;
         }
     }
     malloc_tsd_dalloc(wrapper);
     return false;
 }
References error(), tsd_wrapper_t::initialized, malloc_tsd_dalloc, NULL, tsd_cleanup, tsd_tsd, and tsd_wrapper_t::val.
Referenced by tsd_boot0().
tsd_get()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_get (bool init)
Definition at line 118 of file tsd_win.h.
                    {
     tsd_wrapper_t *wrapper;
     assert(tsd_booted);
     wrapper = tsd_wrapper_get(init);
     if (tsd_get_allocates() && !init && wrapper == NULL) {
         return NULL;
     }
     return &wrapper->val;
 }
References assert(), NULL, tsd_booted, tsd_get_allocates(), tsd_wrapper_get(), and tsd_wrapper_t::val.
tsd_get_allocates()
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
Definition at line 112 of file tsd_win.h.
{
     return true;
 }
Referenced by tsd_get().
tsd_set()
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t * val)
Definition at line 130 of file tsd_win.h.
                     {
     tsd_wrapper_t *wrapper;
     assert(tsd_booted);
     wrapper = tsd_wrapper_get(true);
     if (likely(&wrapper->val != val)) {
         wrapper->val = *(val);
     }
     wrapper->initialized = true;
 }
References assert(), tsd_wrapper_t::initialized, likely, tsd_booted, tsd_wrapper_get(), and tsd_wrapper_t::val.
tsd_wrapper_get()
JEMALLOC_ALWAYS_INLINE tsd_wrapper_t* tsd_wrapper_get (bool init)
Definition at line 47 of file tsd_win.h.
{
     DWORD error = GetLastError();
     tsd_wrapper_t *wrapper = (tsd_wrapper_t *) TlsGetValue(tsd_tsd);
     SetLastError(error);
     if (init && unlikely(wrapper == NULL)) {
         wrapper = (tsd_wrapper_t *)
             malloc_tsd_malloc(sizeof(tsd_wrapper_t));
         if (wrapper == NULL) {
             malloc_write("<jemalloc>: Error allocating TSD\n");
             abort();
         } else {
             wrapper->initialized = false;
             /* MSVC is finicky about aggregate initialization. */
             tsd_t tsd_initializer = TSD_INITIALIZER;
             wrapper->val = tsd_initializer;
         }
         tsd_wrapper_set(wrapper);
     }
     return wrapper;
 }
References error(), tsd_wrapper_t::initialized, malloc_tsd_malloc, malloc_write, NULL, TSD_INITIALIZER, tsd_tsd, tsd_wrapper_set(), unlikely, and tsd_wrapper_t::val.
Referenced by tsd_get(), and tsd_set().
tsd_wrapper_set()
JEMALLOC_ALWAYS_INLINE void tsd_wrapper_set (tsd_wrapper_t * wrapper)
Definition at line 39 of file tsd_win.h.
{
     if (!TlsSetValue(tsd_tsd, (void *)wrapper)) {
         malloc_write("<jemalloc>: Error setting TSD\n");
         abort();
     }
 }
References malloc_write, and tsd_tsd.
Referenced by tsd_boot0(), tsd_boot1(), and tsd_wrapper_get().
Variable Documentation
tsd_boot_wrapper
tsd_wrapper_t tsd_boot_wrapper extern
Definition at line 49 of file tsd.c.
Referenced by tsd_boot0(), and tsd_boot1().
tsd_booted
bool tsd_booted extern
Definition at line 53 of file tsd.c.
Referenced by tsd_boot0(), tsd_booted_get(), tsd_fetch_slow(), tsd_get(), and tsd_set().
tsd_tsd
DWORD tsd_tsd extern
Definition at line 43 of file tsd.c.
Referenced by tsd_boot0(), tsd_cleanup_wrapper(), tsd_wrapper_get(), and tsd_wrapper_set().