Azerotcore-wotlk: deps/libmpq/libmpq/explode.h File Reference
explode.h File Reference
#include "pack_begin.h"
#include "pack_end.h"
Classes
struct PACK_STRUCT
struct pkzip_data_s
Macros
#define LIBMPQ_PKZIP_CMP_BINARY 0 /* binary compression. */
#define LIBMPQ_PKZIP_CMP_ASCII 1 /* ascii compression. */
#define LIBMPQ_PKZIP_CMP_NO_ERROR 0
#define LIBMPQ_PKZIP_CMP_INV_DICTSIZE 1
#define LIBMPQ_PKZIP_CMP_INV_MODE 2
#define LIBMPQ_PKZIP_CMP_BAD_DATA 3
#define LIBMPQ_PKZIP_CMP_ABORT 4
Functions
uint32_t libmpq__do_decompress_pkzip (uint8_t *work_buf, void *param)
Macro Definition Documentation
LIBMPQ_PKZIP_CMP_ABORT
#define LIBMPQ_PKZIP_CMP_ABORT 4
Definition at line 37 of file explode.h.
LIBMPQ_PKZIP_CMP_ASCII
#define LIBMPQ_PKZIP_CMP_ASCII 1 /* ascii compression. */
Definition at line 32 of file explode.h.
LIBMPQ_PKZIP_CMP_BAD_DATA
#define LIBMPQ_PKZIP_CMP_BAD_DATA 3
Definition at line 36 of file explode.h.
LIBMPQ_PKZIP_CMP_BINARY
#define LIBMPQ_PKZIP_CMP_BINARY 0 /* binary compression. */
Definition at line 31 of file explode.h.
LIBMPQ_PKZIP_CMP_INV_DICTSIZE
#define LIBMPQ_PKZIP_CMP_INV_DICTSIZE 1
Definition at line 34 of file explode.h.
LIBMPQ_PKZIP_CMP_INV_MODE
#define LIBMPQ_PKZIP_CMP_INV_MODE 2
Definition at line 35 of file explode.h.
LIBMPQ_PKZIP_CMP_NO_ERROR
#define LIBMPQ_PKZIP_CMP_NO_ERROR 0
Definition at line 33 of file explode.h.
Function Documentation
libmpq__do_decompress_pkzip()
uint32_t libmpq__do_decompress_pkzip (uint8_t * work_buf, void * param)
Definition at line 529 of file explode.c.
{
     /* some common variables. */
     pkzip_cmp_s *mpq_pkzip = (pkzip_cmp_s *)work_buf;
     /* set the whole work buffer to zeros. */
     memset(mpq_pkzip, 0, sizeof(pkzip_cmp_s));
     /* initialize work struct and load compressed data. */
     mpq_pkzip->read_buf   = data_read_input;
     mpq_pkzip->write_buf  = data_write_output;
     mpq_pkzip->param      = param;
     mpq_pkzip->in_pos     = sizeof(mpq_pkzip->in_buf);
     mpq_pkzip->in_bytes   = mpq_pkzip->read_buf((char *)mpq_pkzip->in_buf, &mpq_pkzip->in_pos, mpq_pkzip->param);
     /* check if we have pkzip data. */
     if (mpq_pkzip->in_bytes <= 4) {
         return LIBMPQ_PKZIP_CMP_BAD_DATA;
     }
     /* get the compression type. */
     mpq_pkzip->cmp_type   = mpq_pkzip->in_buf[0];
     /* get the dictionary size. */
     mpq_pkzip->dsize_bits = mpq_pkzip->in_buf[1];
     /* initialize 16-bit bit buffer. */
     mpq_pkzip->bit_buf    = mpq_pkzip->in_buf[2];
     /* extra (over 8) bits. */
     mpq_pkzip->extra_bits = 0;
     /* position in input buffer. */
     mpq_pkzip->in_pos     = 3;
     /* check if valid dictionary size. */
     if (4 > mpq_pkzip->dsize_bits || mpq_pkzip->dsize_bits > 6) {
         return LIBMPQ_PKZIP_CMP_INV_DICTSIZE;
     }
     /* shifted by 'sar' instruction. */
     mpq_pkzip->dsize_mask = 0xFFFF >> (0x10 - mpq_pkzip->dsize_bits);
     /* check if we are using binary compression. */
     if (mpq_pkzip->cmp_type != LIBMPQ_PKZIP_CMP_BINARY) {
         /* check if we are using ascii compression. */
         if (mpq_pkzip->cmp_type != LIBMPQ_PKZIP_CMP_ASCII) {
             return LIBMPQ_PKZIP_CMP_INV_MODE;
         }
         /* create ascii buffer. */
         memcpy(mpq_pkzip->bits_asc, pkzip_bits_asc, sizeof(mpq_pkzip->bits_asc));
         generate_tables_ascii(mpq_pkzip);
     }
     /* create the tables for decode. */
     memcpy(mpq_pkzip->slen_bits, pkzip_slen_bits, sizeof(mpq_pkzip->slen_bits));
     generate_tables_decode(0x10, mpq_pkzip->slen_bits, pkzip_len_code, mpq_pkzip->pos2);
     /* create the tables for decode. */
     memcpy(mpq_pkzip->clen_bits, pkzip_clen_bits, sizeof(mpq_pkzip->clen_bits));
     memcpy(mpq_pkzip->len_base, pkzip_len_base, sizeof(mpq_pkzip->len_base));
     memcpy(mpq_pkzip->dist_bits, pkzip_dist_bits, sizeof(mpq_pkzip->dist_bits));
     generate_tables_decode(0x40, mpq_pkzip->dist_bits, pkzip_dist_code, mpq_pkzip->pos1);
     /* check if data extraction works. */
     if (expand(mpq_pkzip) != 0x306) {
         return LIBMPQ_PKZIP_CMP_NO_ERROR;
     }
     /* something failed, so return error. */
     return LIBMPQ_PKZIP_CMP_ABORT;
 }
References data_read_input(), data_write_output(), expand(), generate_tables_ascii(), generate_tables_decode(), LIBMPQ_PKZIP_CMP_ABORT, LIBMPQ_PKZIP_CMP_ASCII, LIBMPQ_PKZIP_CMP_BAD_DATA, LIBMPQ_PKZIP_CMP_BINARY, LIBMPQ_PKZIP_CMP_INV_DICTSIZE, LIBMPQ_PKZIP_CMP_INV_MODE, LIBMPQ_PKZIP_CMP_NO_ERROR, memcpy, memset, pkzip_bits_asc, pkzip_clen_bits, pkzip_dist_bits, pkzip_dist_code, pkzip_len_base, pkzip_len_code, and pkzip_slen_bits.
Referenced by libmpq__decompress_pkzip().