Azerotcore-wotlk: DefileTargetSelector Struct Reference
DefileTargetSelector Struct Reference
Public Member Functions
DefileTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 433 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
DefileTargetSelector()
DefileTargetSelector::DefileTargetSelector (Creature * source) inline
Definition at line 436 of file boss_the_lich_king.cpp.
 : _source(source) { }
Member Function Documentation
operator()()
bool DefileTargetSelector::operator() (Unit const * target) const inline
Definition at line 437 of file boss_the_lich_king.cpp.
     {
         if (!target)
             return false;
         if (!target->IsAlive())
             return false;
         if (target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (_source->GetExactDist(target) > 100.0f)
             return false;
         if (target->HasAura(SPELL_HARVEST_SOUL_VALKYR) || target->HasAura(SPELL_VALKYR_TARGET_SEARCH))
             return false;
         if (!_source->IsWithinLOSInMap(target))
             return false;
         return true;
     }
References _source, Position::GetExactDist(), Object::GetTypeId(), Unit::HasAura(), Unit::IsAlive(), WorldObject::IsWithinLOSInMap(), SPELL_HARVEST_SOUL_VALKYR, SPELL_VALKYR_TARGET_SEARCH, and TYPEID_PLAYER.
Member Data Documentation
_source
Creature const* DefileTargetSelector::_source private
Definition at line 455 of file boss_the_lich_king.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp