Azerotcore-wotlk: ObjectAccessor Namespace Reference
ObjectAccessor Namespace Reference
Functions
WorldObject * GetWorldObject (WorldObject const &, ObjectGuid const guid)
Object * GetObjectByTypeMask (WorldObject const &, ObjectGuid const guid, uint32 typemask)
Corpse * GetCorpse (WorldObject const &u, ObjectGuid const guid)
GameObject * GetGameObject (WorldObject const &u, ObjectGuid const guid)
Transport * GetTransport (WorldObject const &u, ObjectGuid const guid)
DynamicObject * GetDynamicObject (WorldObject const &u, ObjectGuid const guid)
Unit * GetUnit (WorldObject const &, ObjectGuid const guid)
Creature * GetCreature (WorldObject const &u, ObjectGuid const guid)
Pet * GetPet (WorldObject const &, ObjectGuid const guid)
Player * GetPlayer (Map const *, ObjectGuid const guid)
Player * GetPlayer (WorldObject const &, ObjectGuid const guid)
Creature * GetCreatureOrPetOrVehicle (WorldObject const &, ObjectGuid const)
Player * FindPlayer (ObjectGuid const guid)
Player * FindPlayerByLowGUID (ObjectGuid::LowType lowguid)
Player * FindConnectedPlayer (ObjectGuid const guid)
Player * FindPlayerByName (std::string const &name, bool checkInWorld=true)
HashMapHolder< Player >::MapType const & GetPlayers ()
template<class T >
void AddObject (T *object)
template<class T >
void RemoveObject (T *object)
void SaveAllPlayers ()
template<>
void AddObject (Player *player)
template<>
void RemoveObject (Player *player)
Function Documentation
AddObject() [1/2]
template<> void ObjectAccessor::AddObject (Player * player)
Definition at line 281 of file ObjectAccessor.cpp.
 {
     HashMapHolder<Player>::Insert(player);
     PlayerNameMapHolder::Insert(player);
 }
References PlayerNameMapHolder::Insert(), and HashMapHolder< T >::Insert().
AddObject() [2/2]
template<class T > void ObjectAccessor::AddObject (T * object)
Definition at line 91 of file ObjectAccessor.h.
     {
         HashMapHolder<T>::Insert(object);
     }
References HashMapHolder< T >::Insert().
Referenced by WorldSession::HandlePlayerLoginFromDB().
FindConnectedPlayer()
Player * ObjectAccessor::FindConnectedPlayer (ObjectGuid const guid)
Definition at line 257 of file ObjectAccessor.cpp.
 {
     return HashMapHolder<Player>::Find(guid);
 }
References HashMapHolder< T >::Find().
Referenced by Battleground::_ProcessJoin(), InstanceSaveMgr::_ResetSave(), Guild::AddMember(), ArenaTeam::AddMember(), InstanceMap::AddPlayerToMap(), ArenaTeam::BroadcastPacket(), Player::CanUninviteFromGroup(), Group::ChangeLeader(), Group::ChangeMembersGroup(), lfg::LFGQueue::CheckCompatibility(), ArenaTeam::Create(), Guild::DeleteMember(), ArenaTeam::DelMember(), Group::Disband(), BGQueueInviteEvent::Execute(), BGQueueRemoveEvent::Execute(), Guild::Member::FindPlayer(), ArenaTeam::FinishGame(), GmTicket::GetAssignedPlayer(), ArenaTeam::GetAverageMMR(), SocialMgr::GetFriendInfo(), Creature::GetLootRecipient(), GameObject::GetLootRecipient(), GmTicket::GetPlayer(), CalendarMgr::GetPlayerEvents(), ChatHandler::getSelectedPlayer(), ChatHandler::getSelectedPlayerOrSelf(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharDeleteOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharRenameCallBack(), WorldSession::HandleChatIgnoredOpcode(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupDeclineOpcode(), misc_commandscript::HandleGroupListCommand(), WorldSession::HandleGroupSetLeaderOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionSignOpcode(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandleRaidTargetUpdateOpcode(), WorldSession::HandleSendMail(), lfg::LFGMgr::HasIgnore(), BattlegroundMgr::InviteGroupToBG(), lfg::LFGMgr::LoadLFGDungeons(), lfg::LFGMgr::MakeNewGroup(), ArenaTeam::NotifyStatsChanged(), Group::OfflineReadyCheck(), lfg::LFGGroupScript::OnRemoveMember(), Group::RemoveMember(), PetitionMgr::RemovePetitionByOwnerAndType(), Player::RemovePetitionsAndSigns(), BattlegroundQueue::RemovePlayer(), Player::ResetInstances(), ArenaTeam::Roster(), AuctionHouseMgr::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionSalePendingMail(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), CalendarMgr::SendCalendarClearPendingAction(), CalendarMgr::SendCalendarCommandResult(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), lfg::LFGMgr::SendLfgBootProposalUpdate(), lfg::LFGMgr::SendLfgJoinResult(), lfg::LFGMgr::SendLfgQueueStatus(), WorldSession::SendLfgRoleCheckUpdate(), lfg::LFGMgr::SendLfgRoleCheckUpdate(), lfg::LFGMgr::SendLfgRoleChosen(), lfg::LFGMgr::SendLfgUpdateParty(), lfg::LFGMgr::SendLfgUpdatePlayer(), lfg::LFGMgr::SendLfgUpdateProposal(), Group::SendLootAllPassed(), Group::SendLootRoll(), Group::SendLootRollWon(), Group::SendLootStartRoll(), WorldSession::SendNameQueryOpcode(), CalendarMgr::SendPacketToAllEventRelatives(), Channel::SendToOne(), Group::SendUpdateToPlayer(), ArenaTeam::SetCaptain(), InstanceSaveMgr::UnbindAllFor(), lfg::LFGMgr::UpdateRaidBrowser(), and GameObject::Use().
FindPlayer()
Player * ObjectAccessor::FindPlayer (ObjectGuid const guid)
Definition at line 245 of file ObjectAccessor.cpp.
 {
     Player* player = HashMapHolder<Player>::Find(guid);
     return player && player->IsInWorld() ? player : nullptr;
 }
References HashMapHolder< T >::Find(), and Object::IsInWorld().
Referenced by Battleground::_ProcessJoin(), Battleground::_ProcessResurrect(), Loot::AddItem(), BfGraveyard::AddPlayer(), Battleground::AddPlayerToResurrectQueue(), Group::BroadcastGroupUpdate(), OutdoorPvP::BroadcastPacket(), Battlefield::BroadcastPacketToQueue(), Battlefield::BroadcastPacketToWar(), Battlefield::BroadcastPacketToZone(), SocialMgr::BroadcastToFriendListers(), OutdoorPvPEP::BuffTeams(), BattlegroundSA::CaptureGraveyard(), BattlefieldWG::CapturePointTaken(), Guild::Member::ChangeRank(), OPvPCapturePointTF::ChangeState(), Spell::CheckCast(), SpellInfo::CheckTarget(), Group::ConvertToRaid(), Group::CountTheRoll(), AccountMgr::DeleteAccount(), ArenaTeamMgr::DistributeArenaPoints(), Spell::DoAllEffectOnTarget(), Battlefield::DoPlaySoundToAll(), AuctionListItemsDelayEvent::Execute(), AuctionListOwnerItemsDelayEvent::Execute(), FindPlayerByLowGUID(), lfg::LFGMgr::FinishDungeon(), Item::GetOwner(), Group::GroupLoot(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleInspectArenaTeamsOpcode(), BattlefieldWG::HandleKill(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleSummonResponseOpcode(), Battlefield::InvitePlayersInQueueToWar(), Battlefield::InvitePlayersInZoneToQueue(), Battlefield::InvitePlayersInZoneToWar(), ArenaTeam::IsFighting(), Battlefield::KickAfkPlayers(), Battlefield::KickPlayerFromBattlefield(), Unit::Kill(), lfg::LFGMgr::MakeNewGroup(), Group::NeedBeforeGreed(), Loot::NotifyItemRemoved(), Loot::NotifyMoneyRemoved(), Loot::NotifyQuestItemRemoved(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), BattlefieldWG::OnCreatureCreate(), Acore::WorldObjectSpellTargetCheck::operator()(), BfGraveyard::RelocateDeadPlayers(), Battleground::RelocateDeadPlayers(), BfGraveyard::RemovePlayer(), lfg::LFGMgr::RemoveProposal(), Group::ResetMaxEnchantingLevel(), BfGraveyard::Resurrect(), Spell::SelectEffectTypeImplicitTargets(), BfCapturePoint::SendChangePhase(), BattlefieldWG::SendInitWorldStatesToAll(), BfCapturePoint::SendObjectiveComplete(), OPvPCapturePoint::SendObjectiveComplete(), Acore::VisibleNotifier::SendToSelf(), BfCapturePoint::SendUpdateWorldState(), Battlefield::SendUpdateWorldState(), OPvPCapturePoint::SendUpdateWorldState(), OutdoorPvP::SendUpdateWorldState(), OPvPCapturePointZM_GraveYard::SetBeaconState(), Channel::SetOwner(), Player::SummonIfPossible(), Battlefield::TeamCastSpell(), OutdoorPvP::TeamCastSpell(), BfCapturePoint::Update(), OPvPCapturePoint::Update(), BattlefieldWG::UpdatedDestroyedTowerCount(), Group::UpdateLooterGuid(), BattlefieldWG::UpdateTenacity(), BattlefieldWG::UpdateVehicleCountWG(), GameObject::Use(), and WorldObjectChangeAccumulator::Visit().
FindPlayerByLowGUID()
Player * ObjectAccessor::FindPlayerByLowGUID (ObjectGuid::LowType lowguid)
Definition at line 251 of file ObjectAccessor.cpp.
 {
     ObjectGuid guid = ObjectGuid::Create<HighGuid::Player>(lowguid);
     return ObjectAccessor::FindPlayer(guid);
 }
References FindPlayer().
Referenced by Player::DeleteFromDB(), misc_commandscript::HandleGetDistanceCommand(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMailTakeItem(), lookup_commandscript::LookupPlayerSearchCommand(), ObjectMgr::ReturnOrDeleteOldMails(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), and Acore::ChatCommands::PlayerIdentifier::TryConsume().
FindPlayerByName()
Player * ObjectAccessor::FindPlayerByName (std::string const & name, bool checkInWorld = true)
Definition at line 271 of file ObjectAccessor.cpp.
 {
     if (Player* player = PlayerNameMapHolder::Find(name))
         if (!checkInWorld || player->IsInWorld())
             return player;
     return nullptr;
 }
References PlayerNameMapHolder::Find().
Referenced by BanMgr::BanCharacter(), ChatHandler::extractLowGuidFromLink(), ChatHandler::extractPlayerTarget(), ChatHandler::GetPlayerGroupAndGUIDByName(), WorldSession::HandleArenaTeamInviteOpcode(), ban_commandscript::HandleBanInfoCharacterCommand(), WorldSession::HandleCalendarEventInvite(), misc_commandscript::HandleCombatStopCommand(), misc_commandscript::HandleFreezeCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), WorldSession::HandleGroupChangeSubGroupOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), Guild::HandleInviteMember(), WorldSession::HandleMessagechatOpcode(), npc_commandscript::HandleNpcWhisperCommand(), misc_commandscript::HandleSkirmishCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), misc_commandscript::HandleUnFreezeCommand(), message_commandscript::HandleWhispersCommand(), WorldSession::HandleWhoisOpcode(), Channel::Invite(), Channel::KickOrBan(), BanMgr::RemoveBanCharacter(), Channel::SetMode(), Channel::SetOwner(), and Acore::ChatCommands::PlayerIdentifier::TryConsume().
GetCorpse()
Corpse * ObjectAccessor::GetCorpse (WorldObject const & u, ObjectGuid const guid)
Definition at line 179 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetCorpse(guid);
 }
References Map::GetCorpse(), and WorldObject::GetMap().
Referenced by Spell::CheckEffectTarget(), WorldSession::DoLootRelease(), GetWorldObject(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMoneyOpcode(), Map::RemoveAllObjectsInRemoveList(), and Player::SendLoot().
GetCreature()
Creature * ObjectAccessor::GetCreature (WorldObject const & u, ObjectGuid const guid)
Definition at line 210 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetCreature(guid);
 }
References Map::GetCreature(), and WorldObject::GetMap().
Referenced by at_zulgurub_entrance_speech::_OnTrigger(), boss_kologarn::boss_kologarnAI::AttachLeftArm(), boss_kologarn::boss_kologarnAI::AttachRightArm(), boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI(), npc_anubisath_sentinel::aqsentinelAI::CallBuddiesToAttack(), boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage(), boss_shade_of_akama::boss_shade_of_akamaAI::ChannelersAction(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckCaravan(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::CheckChannelers(), boss_volazj::boss_volazjAI::CheckPhaseMinions(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons(), npc_twiggy_flathead::npc_twiggy_flatheadAI::CleanUp(), npc_thassarian2::npc_thassarian2AI::Cleanup(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::DamageDealt(), boss_julianne::boss_julianneAI::DamageTaken(), boss_romulo::boss_romuloAI::DamageTaken(), npc_mograine::npc_mograineAI::DamageTaken(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_twilight_halion::boss_twilight_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::DamageTaken(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_kologarn_arms::boss_kologarn_armsAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), Battleground::DelCreature(), SummonList::DespawnAll(), SummonList::DespawnEntry(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::DespawnOachanoa(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DespawnOOCSummons(), hyjalAI::DeSpawnVeins(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), boss_netherspite::boss_netherspiteAI::DestroyPortals(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), npc_argent_captainAI::DoAction(), SummonList::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), boss_paletress::boss_paletressAI::DoAction(), npc_molten_golem::npc_molten_golemAI::DoAction(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoSummonAction(), SummonList::DoZoneInCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_kiljaeden::boss_kiljaedenAI::EmpowerOrb(), boss_romulo::boss_romuloAI::EnterCombat(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), npc_risen_archmage::npc_risen_archmageAI::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_illidari_council_memberAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_priestess_lackey_commonAI::EnterCombat(), boss_sacrolash::boss_sacrolashAI::EnterCombat(), boss_alythess::boss_alythessAI::EnterCombat(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::EnterCombat(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::EnterCombat(), npc_burning_spirit::npc_burning_spiritAI::EnterEvadeMode(), boss_priestess_lackey_commonAI::EnterEvadeMode(), boss_sacrolash::boss_sacrolashAI::EnterEvadeMode(), boss_alythess::boss_alythessAI::EnterEvadeMode(), boss_entropius::boss_entropiusAI::EnterEvadeMode(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::EnterEvadeMode(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterEvadeMode(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), npc_tirion_fordring_tft::npc_tirion_fordringAI::EnterEvadeMode(), npc_argent_captainAI::EnterEvadeMode(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(), boss_halazzi::boss_halazziAI::EnterPhase(), AssistDelayEvent::Execute(), IceTombSummonEvent::Execute(), startFollow::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_salramm::boss_salrammAI::ExplodeGhoul(), spell_festergut_blighted_spores::spell_festergut_blighted_spores_AuraScript::ExtraEffect(), spell_the_lich_king_restore_soul::spell_the_lich_king_restore_soul_SpellScript::FilterTargets(), npc_thrall_bfu::npc_thrall_bfuAI::FollowThrall(), brann_bronzebeard::brann_bronzebeardAI::GetAbedneum(), GetCreatureOrPetOrVehicle(), SummonList::GetCreatureWithEntry(), SummonList::GetEntryCount(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetEntryFromSummons(), npc_arthas::npc_arthasAI::GetEventNpc(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::getFuture(), boss_skadi::boss_skadiAI::GetGrauf(), boss_hodir::boss_hodirAI::GetHelper(), brann_bronzebeard::brann_bronzebeardAI::GetKaddrak(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::GetKelidan(), brann_bronzebeard::brann_bronzebeardAI::GetMarnak(), GetObjectByTypeMask(), boss_twinemperorsAI::GetOtherBoss(), npc_anubisath_sentinel::aqsentinelAI::GetOtherSentinels(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::GetPlate(), boss_moroes::boss_moroesAI::GetRandomGuest(), boss_twin_valkyrAI::GetSister(), npc_air_force_bots::npc_air_force_botsAI::GetSummonedGuard(), TempSummon::GetSummonerCreatureBase(), GetUnit(), GetWorldObject(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), spell_sha_totem_of_wrath::HandleAfterCast(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), BattlegroundIC::HandleCapturedNodes(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), spell_mage_summon_water_elemental::HandleDummy(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::HandleEffectRemove(), spell_black_template_harpooners_mark::spell_black_template_harpooners_mark_AuraScript::HandleEffectRemove(), spell_leotheras_insidious_whisper::spell_leotheras_insidious_whisper_AuraScript::HandleEffectRemove(), spell_botanica_call_of_the_falcon::spell_botanica_call_of_the_falcon_AuraScript::HandleEffectRemove(), spell_alar_ember_blast::spell_alar_ember_blast_SpellScript::HandleForceCast(), spell_assembly_meltdown::spell_assembly_meltdown_SpellScript::HandleInstaKill(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectRemove(), Unit::HandleProcTriggerSpell(), spell_sartharion_lava_strike::spell_sartharion_lava_strike_SpellScript::HandleSchoolDamage(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_putricide_unbound_plague::spell_putricide_unbound_plague_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), SummonList::HasEntry(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), npc_cork_gizelton::npc_cork_gizeltonAI::ImmuneFlagSet(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), go_troll_cage::go_troll_cageAI::initBlyCrewMember(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::InitializeAI(), SummonList::IsAnyCreatureAlive(), SummonList::IsAnyCreatureInCombat(), Unit::isAttackingPlayer(), IsEncounterComplete(), npc_direbrew_minion::npc_direbrew_minionAI::IsSummonedBy(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::IsSummonedBy(), npc_living_inferno::npc_living_infernoAI::IsSummonedBy(), npc_kinetic_bomb::npc_kinetic_bombAI::IsSummonedBy(), npc_putricide_oozeAI::IsSummonedBy(), npc_raging_spirit::npc_raging_spiritAI::IsSummonedBy(), npc_suppresser::npc_suppresserAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), boss_terestian_illhoof::boss_terestianAI::JustDied(), npc_tito::npc_titoAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_kalec::boss_kalecAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustDied(), boss_entropius::boss_entropiusAI::JustDied(), boss_mandokir::boss_mandokirAI::JustDied(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), npc_anubisath_sentinel::aqsentinelAI::JustDied(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::JustDied(), boss_sartharion_dragonAI::JustDied(), npc_memory::npc_memoryAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), npc_stinky_icc::npc_stinky_iccAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), npc_little_ooze::npc_little_oozeAI::JustDied(), npc_big_ooze::npc_big_oozeAI::JustDied(), npc_precious_icc::npc_precious_iccAI::JustDied(), npc_raging_spirit::npc_raging_spiritAI::JustDied(), npc_spirit_warden::npc_spirit_wardenAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_thaddius_summon::boss_thaddius_summonAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::JustDied(), brann_bronzebeard::brann_bronzebeardAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_freya_summons::boss_freya_summonsAI::JustDied(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::JustDied(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::JustDied(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::JustDied(), npc_massive_jormungar::npc_massive_jormungarAI::JustDied(), npc_ferocious_rhino::npc_ferocious_rhinoAI::JustDied(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::JustDied(), npc_frenzied_worgen::npc_frenzied_worgenAI::JustDied(), violet_hold_trashAI::JustDied(), npc_akama_shade::npc_akamaAI::JustDied(), boss_illidari_council_memberAI::JustDied(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustDied(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::JustDied(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), npc_infernal_attacker::npc_infernal_attackerAI::JustDied(), npc_illidari_spawn::npc_illidari_spawnAI::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_twilight_halion::boss_twilight_halionAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::JustDied(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::JustDied(), boss_halion::boss_halionAI::JustReachedHome(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::JustSummoned(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), npc_collapsing_star::npc_collapsing_starAI::JustSummoned(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), Player::KilledMonsterCredit(), boss_priestess_lackey_commonAI::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), spell_kaelthas_kael_phase_two::spell_kaelthas_kael_phase_two_SpellScript::Load(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_fel_guard_hound::npc_fel_guard_houndAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_burning_spirit::npc_burning_spiritAI::MovementInform(), npc_sergeant_bly::npc_sergeant_blyAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), npc_big_ooze::npc_big_oozeAI::npc_big_oozeAI(), npc_little_ooze::npc_little_oozeAI::npc_little_oozeAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), spell_blood_queen_frenzied_bloodthirst::spell_blood_queen_frenzied_bloodthirst_AuraScript::OnApply(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), achievement_cant_do_that_while_stunned::OnCheck(), achievement_auriaya_crazy_cat_lady::OnCheck(), achievement_auriaya_nine_lives::OnCheck(), achievement_kologarn_looks_could_kill::OnCheck(), achievement_kologarn_rubble_and_roll::OnCheck(), achievement_kologarn_with_open_arms::OnCheck(), achievement_xt002_nerf_engineering::OnCheck(), achievement_xt002_nerf_gravity_bombs::OnCheck(), achievement_thorim_stand_in_the_lightning::OnCheck(), achievement_thorim_lose_your_illusion::OnCheck(), achievement_yogg_saron_darkness::OnCheck(), achievement_yogg_saron_he_waits_dreaming::OnCheck(), go_shadowforge_brazier::OnGossipHello(), go_palehoof_sphere::OnGossipHello(), go_broggok_lever::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), go_orb_of_domination::OnGossipHello(), go_blackened_urn::OnGossipHello(), go_acherus_soul_prison::OnGossipHello(), go_ulduar_do_not_push_this_button::OnGossipHello(), go_strange_pool::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_harpoon_canon::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), spell_blood_queen_frenzied_bloodthirst::spell_blood_queen_frenzied_bloodthirst_AuraScript::OnRemove(), at_trigger_the_beast_movement::OnTrigger(), at_the_beast_room::OnTrigger(), AreaTrigger_at_sunwell_madrigosa::OnTrigger(), AreaTrigger_at_sunwell_eredar_twins::OnTrigger(), at_baltharus_plateau::OnTrigger(), at_lady_deathwhisper_entrance::OnTrigger(), at_sindragosa_lair::OnTrigger(), at_icc_start_frostwing_gauntlet::OnTrigger(), at_icc_gauntlet_event::OnTrigger(), at_icc_putricide_trap::OnTrigger(), at_thaddius_entrance::OnTrigger(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::PassengerBoarded(), npc_doctor::npc_doctorAI::PatientSaved(), BattlegroundDS::PostUpdateImpl(), BattlegroundRV::PostUpdateImpl(), npc_simone::npc_simoneAI::Precious(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveAll(), boss_festergut::boss_festergutAI::RemoveBlight(), SummonList::RemoveNotExisting(), npc_cork_gizelton::npc_cork_gizeltonAI::RemoveSummons(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_terestian_illhoof::boss_terestianAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::Reset(), npc_anubisath_sentinel::aqsentinelAI::Reset(), boss_paletress::boss_paletressAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_freya::boss_freyaAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_illidari_council::boss_illidari_councilAI::Reset(), npc_captain_saeed::npc_captain_saeedAI::Reset(), SmartScript::ResetBaseObject(), SummonList::Respawn(), RespawnAssemblyOfIron(), boss_sartharion::boss_sartharionAI::RespawnDragons(), RestoreAssemblyHealth(), BfGraveyard::Resurrect(), Player::RewardQuest(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::RunRunicSmash(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::Say(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::Say(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::SelectCouncilMember(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), Player::SendInitWorldStates(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), npc_anubisath_sentinel::aqsentinelAI::SendMyListToBuddies(), Battlefield::SendWarningToPlayer(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), boss_kaelthas::boss_kaelthasAI::SetData(), boss_the_beast::boss_thebeastAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_thassarian2::npc_thassarian2AI::SetData(), npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID(), npc_cork_gizelton::npc_cork_gizeltonAI::SetGUID(), Unit::SetPhaseMask(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SpawnAnubArak(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::SummonChannelers(), PassengerController::SummonCreatures(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), npc_captain_saeed::npc_captain_saeedAI::SummonsAction(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonsFollow(), npc_sergeant_bly::npc_sergeant_blyAI::switchFactionIfAlive(), npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_Pathaleons_Image(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::TurnAudience(), Unit::UnsummonAllTotems(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_julianne::boss_julianneAI::UpdateAI(), boss_romulo::boss_romuloAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_time_rift::npc_time_riftAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), npc_voidtraveler::npc_voidtravelerAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_suppresser::npc_suppresserAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), npc_warmage_violetstand::npc_warmage_violetstandAI::UpdateAI(), npc_injured_patient::npc_injured_patientAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), brann_bronzebeard::brann_bronzebeardAI::WaypointReached(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), npc_varian_wrynn::npc_varian_wrynnAI::WaypointReached(), hyjalAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), and npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart().
GetCreatureOrPetOrVehicle()
Creature * ObjectAccessor::GetCreatureOrPetOrVehicle (WorldObject const & u, ObjectGuid const guid)
Definition at line 234 of file ObjectAccessor.cpp.
 {
     if (guid.IsPet())
         return GetPet(u, guid);
     if (guid.IsCreatureOrVehicle())
         return GetCreature(u, guid);
     return nullptr;
 }
References GetCreature(), GetPet(), ObjectGuid::IsCreatureOrVehicle(), and ObjectGuid::IsPet().
Referenced by Unit::GetFirstMinion(), Unit::GetGuardianPet(), Player::GetNextQuest(), Player::GetNPCIfCanInteractWith(), ChatHandler::getSelectedCreature(), WorldSession::HandleDismissCritter(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), WorldSession::HandleSpellClick(), Player::PrepareQuestMenu(), WorldSession::SendPetNameQuery(), Player::SendPreparedQuest(), Player::SendQuestGiverStatusMultiple(), and Player::UpdateForQuestWorldObjects().
GetDynamicObject()
DynamicObject * ObjectAccessor::GetDynamicObject (WorldObject const & u, ObjectGuid const guid)
Definition at line 194 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetDynamicObject(guid);
 }
References Map::GetDynamicObject(), and WorldObject::GetMap().
Referenced by GetObjectByTypeMask(), and GetWorldObject().
GetGameObject()
GameObject * ObjectAccessor::GetGameObject (WorldObject const & u, ObjectGuid const guid)
Definition at line 184 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetGameObject(guid);
 }
References Map::GetGameObject(), and WorldObject::GetMap().
Referenced by Unit::_UpdateSpells(), boss_mimiron::boss_mimironAI::CloseDoorAndButton(), Battleground::DelObject(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), Battleground::DoorClose(), Battleground::DoorOpen(), boss_kiljaeden::boss_kiljaedenAI::EmpowerOrb(), boss_xt002::boss_xt002AI::EnterCombat(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::FilterTargets(), BfCapturePoint::GetCapturePointGo(), Unit::GetGameObject(), GameObject::GetLinkedTrap(), GetObjectByTypeMask(), boss_thorim::boss_thorimAI::GetThorimObject(), GetWorldObject(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), boss_netherspite::boss_netherspiteAI::HandleDoors(), spell_warl_demonic_circle_summon::HandleDummyTick(), WorldSession::HandleGameObjectUseOpcode(), boss_drakos::boss_drakosAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), boss_xt002::boss_xt002AI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), go_shadowforge_brazier::OnGossipHello(), BattlegroundDS::PostUpdateImpl(), BattlefieldWG::ProcessEvent(), Unit::RemoveAllGameObjects(), Unit::RemoveGameObject(), boss_xt002::boss_xt002AI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), SmartScript::ResetBaseObject(), brann_bronzebeard::brann_bronzebeardAI::ResetEvent(), boss_mimiron::boss_mimironAI::ResetGameObjects(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::ResetOrbs(), BattlegroundEY::RespawnFlagAfterDrop(), BattlegroundWS::RespawnFlagAfterDrop(), boss_svala::boss_svalaAI::SetData(), boss_kaelthas::boss_kaelthasAI::SetRoomState(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::SpellHit(), BattlegroundDS::StartingEventOpenDoors(), boss_flame_leviathan::boss_flame_leviathanAI::TurnGates(), boss_flame_leviathan::boss_flame_leviathanAI::TurnHealStations(), boss_majordomo::boss_majordomoAI::UpdateAI(), npc_crystal_spike::npc_crystal_spikeAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), Player::UpdateForQuestWorldObjects(), BattlegroundRV::UpdatePillars(), and brann_bronzebeard::brann_bronzebeardAI::WaypointReached().
GetObjectByTypeMask()
Object * ObjectAccessor::GetObjectByTypeMask (WorldObject const & p, ObjectGuid const guid, uint32 typemask)
Definition at line 141 of file ObjectAccessor.cpp.
 {
     switch (guid.GetHigh())
     {
         case HighGuid::Item:
             if (typemask & TYPEMASK_ITEM && p.GetTypeId() == TYPEID_PLAYER)
                 return ((Player const&)p).GetItemByGuid(guid);
             break;
         case HighGuid::Player:
             if (typemask & TYPEMASK_PLAYER)
                 return GetPlayer(p, guid);
             break;
         case HighGuid::Transport:
         case HighGuid::Mo_Transport:
         case HighGuid::GameObject:
             if (typemask & TYPEMASK_GAMEOBJECT)
                 return GetGameObject(p, guid);
             break;
         case HighGuid::Unit:
         case HighGuid::Vehicle:
             if (typemask & TYPEMASK_UNIT)
                 return GetCreature(p, guid);
             break;
         case HighGuid::Pet:
             if (typemask & TYPEMASK_UNIT)
                 return GetPet(p, guid);
             break;
         case HighGuid::DynamicObject:
             if (typemask & TYPEMASK_DYNAMICOBJECT)
                 return GetDynamicObject(p, guid);
             break;
         default:
             return nullptr;
     }
     return nullptr;
 }
References DynamicObject, GameObject, GetCreature(), GetDynamicObject(), GetGameObject(), ObjectGuid::GetHigh(), GetPet(), GetPlayer(), Object::GetTypeId(), Item, Mo_Transport, Pet, Player, Transport, TYPEID_PLAYER, TYPEMASK_DYNAMICOBJECT, TYPEMASK_GAMEOBJECT, TYPEMASK_ITEM, TYPEMASK_PLAYER, TYPEMASK_UNIT, Unit, and Vehicle.
Referenced by Player::GetViewpoint(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestgiverRequestRewardOpcode(), WorldSession::HandleQuestgiverStatusQueryOpcode(), and Player::SendPreparedQuest().
GetPet()
Pet * ObjectAccessor::GetPet (WorldObject const & u, ObjectGuid const guid)
Definition at line 215 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetPet(guid);
 }
References WorldObject::GetMap(), and Map::GetPet().
Referenced by Unit::AddPetAura(), GetCreatureOrPetOrVehicle(), GetObjectByTypeMask(), Player::GetPet(), GetUnit(), GetWorldObject(), WorldSession::HandlePetRename(), WorldSession::HandlePetStopAttack(), and Unit::RemovePetAura().
GetPlayer() [1/2]
Player * ObjectAccessor::GetPlayer (Map const * m, ObjectGuid const guid)
Definition at line 220 of file ObjectAccessor.cpp.
 {
     if (Player * player = HashMapHolder<Player>::Find(guid))
         if (player->IsInWorld() && player->GetMap() == m)
             return player;
     return nullptr;
 }
Referenced by npc_hidden_cultist::npc_hidden_cultistAI::AttackPlayer(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::CheckEventFail(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::CheckEventFail(), BattlegroundWS::CheckFlagKeeperInArea(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer(), npc_simon_bunny::npc_simon_bunnyAI::CheckPlayer(), GameObject::CheckRitualList(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons(), Unit::ClearComboPointHolders(), GameObject::ClearRitualList(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::CreditPlayer(), npc_eris_hevenfire::npc_eris_hevenfireAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_anubarak_spike::npc_anubarak_spikeAI::DoAction(), BattlegroundIC::DoAction(), npc_shay_leafrunner::npc_shay_leafrunnerAI::EnterEvadeMode(), npc_clintar_spirit::npc_clintar_spiritAI::EnterEvadeMode(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), EoEDrakeEnterVehicleEvent::Execute(), VerasEnvenom::Execute(), instance_stratholme::instance_stratholme_InstanceMapScript::gate_critter_delay(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Unit::GetDiseasesByCaster(), NPCStaveQuestAI::GetGossipPlayer(), FollowerAI::GetLeaderForFollower(), GetObjectByTypeMask(), Puppet::GetOwner(), npc_pet_gen_soul_trader_beacon::GetOwner(), GetPlayer(), npc_escortAI::GetPlayerForEscort(), boss_headless_horseman::boss_headless_horsemanAI::GetRhymePlayer(), Player::GetSelectedPlayer(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::getSummoner(), GetUnit(), npc_wild_wyrm::npc_wild_wyrmAI::GetValidPlayer(), GetWorldObject(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_simon_bunny::npc_simon_bunnyAI::GiveRewardForLevel(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::GotStinged(), WorldSession::HandleAcceptGrantLevel(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), WorldSession::HandleEjectPassenger(), WorldSession::HandleEnterPlayerVehicle(), WorldSession::HandleGrantLevel(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleInspectOpcode(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleQueryInspectAchievements(), WorldSession::HandleQuestConfirmAccept(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestPushResult(), pyrewood_ambush::pyrewood_ambushAI::JustDied(), npc_zulaman_hostage::npc_zulaman_hostageAI::JustDied(), npc_shay_leafrunner::npc_shay_leafrunnerAI::JustDied(), npc_clintar_spirit::npc_clintar_spiritAI::JustDied(), npc_ice_tomb::npc_ice_tombAI::JustDied(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), npc_unworthy_initiate::npc_unworthy_initiateAI::MovementInform(), npc_hive_zara_larva::npc_hive_zara_larvaAI::MovementInform(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_doctor::npc_doctorAI::PatientDied(), BattlegroundWS::PostUpdateImpl(), npc_hidden_cultist::npc_hidden_cultistAI::PreScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), npc_pet_gen_mojo::ReceiveEmote(), BattlegroundWS::RemoveAssaultAuras(), npc_finklestein::npc_finklesteinAI::RightClickCauldron(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::Say(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), Map::ScriptsProcess(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::SetGUID(), Unit::SetOwnerGUID(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget(), npc_finklestein::npc_finklesteinAI::StartNextTask(), SmartAI::StopFollow(), pyrewood_ambush::pyrewood_ambushAI::SummonCreatureWithRandomTarget(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), GameObject::Update(), npc_kernobee::npc_kernobeeAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_anubarak_spike::npc_anubarak_spikeAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_ice_tomb::npc_ice_tombAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), GameObject::Use(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
GetPlayer() [2/2]
Player * ObjectAccessor::GetPlayer (WorldObject const & u, ObjectGuid const guid)
Definition at line 229 of file ObjectAccessor.cpp.
 {
     return GetPlayer(u.GetMap(), guid);
 }
References WorldObject::GetMap(), and GetPlayer().
GetPlayers()
HashMapHolder< Player >::MapType const & ObjectAccessor::GetPlayers ()
Definition at line 80 of file ObjectAccessor.cpp.
 {
     return HashMapHolder<Player>::GetContainer();
 }
References HashMapHolder< T >::GetContainer().
Referenced by MapMgr::GetNumPlayersInInstances(), gm_commandscript::HandleGMListIngameCommand(), misc_commandscript::HandleMuteCommand(), reset_commandscript::HandleResetAllCommand(), SaveAllPlayers(), and WhoListCacheMgr::Update().
GetTransport()
Transport * ObjectAccessor::GetTransport (WorldObject const & u, ObjectGuid const guid)
Definition at line 189 of file ObjectAccessor.cpp.
 {
     return u.GetMap()->GetTransport(guid);
 }
References WorldObject::GetMap(), and Map::GetTransport().
Referenced by ResetEncounterEvent::Execute().
GetUnit()
Unit * ObjectAccessor::GetUnit (WorldObject const & u, ObjectGuid const guid)
Definition at line 199 of file ObjectAccessor.cpp.
 {
     if (guid.IsPlayer())
         return GetPlayer(u, guid);
     if (guid.IsPet())
         return GetPet(u, guid);
     return GetCreature(u, guid);
 }
References GetCreature(), GetPet(), GetPlayer(), ObjectGuid::IsPet(), and ObjectGuid::IsPlayer().
Referenced by FleeingMovementGenerator< T >::_setMoveData(), Player::AddComboPoints(), Vehicle::AddPassenger(), DynamicObject::BindToCaster(), Spell::cancel(), boss_archimonde::boss_archimondeAI::CanUseFingerOfDeath(), npc_hallows_end_soh::npc_hallows_end_sohAI::CastFires(), SmartAI::CheckConditions(), VehicleAI::CheckConditions(), Player::ClearComboPoints(), Aura::Create(), npc_mograine::npc_mograineAI::DamageTaken(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken(), Spell::DelayedChannel(), boss_zuljin::boss_zuljinAI::DespawnAdds(), UnitAI::DoAddAuraToAllHostilePlayers(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), boss_archimonde::boss_archimondeAI::DoCastProtection(), UnitAI::DoCastToAllHostilePlayers(), PointMovementGenerator< T >::DoFinalize(), FleeingMovementGenerator< T >::DoInitialize(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), Spell::EffectJumpDest(), Spell::EffectPersistentAA(), boss_faction_championsAI::EnemiesInRange(), boss_malchezaar::boss_malchezaarAI::EnfeebleHealthEffect(), boss_malchezaar::boss_malchezaarAI::EnfeebleResetHealth(), SmartAI::EnterEvadeMode(), boss_halazzi::boss_halazziAI::EnterPhase(), boss_zuljin::boss_zuljinAI::EnterPhase(), AssistDelayEvent::Execute(), RedirectSpellEvent::Execute(), ReflectEvent::Execute(), AuraMunchingQueue::Execute(), DealDebrisDamage::Execute(), spell_eoe_ph3_surge_of_power::spell_eoe_ph3_surge_of_power_SpellScript::FilterTargets(), spell_putricide_mutated_transformation_dmg::spell_putricide_mutated_transformation_dmg_SpellScript::FilterTargetsInitial(), boss_supremus::boss_supremusAI::FindHatefulStrikeTarget(), npc_hallows_end_soh::npc_hallows_end_sohAI::FinishEvent(), boss_shade_of_aran::boss_aranAI::FlameWreathEffect(), Aura::GetCaster(), Unit::GetCharm(), Unit::GetCharmer(), Unit::GetFirstControlled(), SmartScript::GetLastInvoker(), Minion::GetOwner(), GameObject::GetOwner(), Unit::GetOwner(), Vehicle::GetPassenger(), Unit::GetRedirectThreatTarget(), ChatHandler::getSelectedObject(), Player::GetSelectedUnit(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::GetTarget(), SmartScript::GetTargets(), spell_dk_scourge_strike::HandleAfterHit(), Pet::HandleAsynchLoadFailed(), WorldSession::HandleAttackSwingOpcode(), AuraEffect::HandleAuraRetainComboPoints(), boss_janalai::boss_janalaiAI::HandleBombSequence(), WorldSession::HandleChangeSeatsOnControlledVehicle(), spell_item_gnomish_death_ray::HandleDummy(), Unit::HandleDummyAuraProc(), spell_rog_killing_spree::spell_rog_killing_spree_AuraScript::HandleEffectPeriodic(), WorldSession::HandleEjectPassenger(), gobject_commandscript::HandleGameObjectDeleteCommand(), WorldSession::HandleMirrorImageDataRequest(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetSetAction(), spell_item_lil_phylactery::HandleProc(), spell_rog_blade_flurry::HandleProc(), Unit::HandleProcTriggerSpell(), spell_kaelthas_nether_beam::spell_kaelthas_nether_beam_SpellScript::HandleScriptEffect(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleTextEmoteOpcode(), Spell::HandleThreatSpells(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Spell::InitExplicitTargets(), boss_aeonus::boss_aeonusAI::InitializeAI(), Totem::InitStats(), NPCStaveQuestAI::IsFairFight(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), boss_sapphiron::boss_sapphironAI::IsValidExplosionTarget(), Vehicle::IsVehicleInUse(), npc_kilrek::npc_kilrekAI::JustDied(), npc_demon_chain::npc_demon_chainAI::JustDied(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustDied(), boss_zuljin::boss_zuljinAI::JustDied(), npc_zulian_prowler::npc_zulian_prowlerAI::JustDied(), npc_eye_tentacle::eye_tentacleAI::JustDied(), npc_claw_tentacle::claw_tentacleAI::JustDied(), npc_giant_claw_tentacle::giant_claw_tentacleAI::JustDied(), npc_giant_eye_tentacle::giant_eye_tentacleAI::JustDied(), npc_snobold_vassal::npc_snobold_vassalAI::JustDied(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::JustDied(), boss_freya_iron_root::boss_freya_iron_rootAI::JustDied(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::JustDied(), npc_inner_demon::npc_inner_demonAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), npc_frost_tomb::npc_frost_tombAI::JustDied(), boss_aeonus::boss_aeonusAI::JustReachedHome(), boss_archimonde::boss_archimondeAI::JustSummoned(), netherspite_infernal::netherspite_infernalAI::KilledUnit(), boss_selin_fireheart::boss_selin_fireheartAI::MovementInform(), npc_akilzon_eagle::npc_akilzon_eagleAI::MovementInform(), npc_pet_mage_mirror_image::MySelectNextTarget(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::OnPeriodic(), AbominationDespawner::operator()(), Unit::OutDebugInfo(), SmartScript::ProcessAction(), ThreatMgr::processThreatEvent(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), Vehicle::RelocatePassengers(), Unit::RemoveCharmedBy(), GameObject::RemoveFromOwner(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::RemoveTargetAura(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), boss_archimonde::boss_archimondeAI::Reset(), boss_faction_championsAI::SelectEnemyCaster(), Spell::SelectImplicitAreaTargets(), boss_cthun::cthunAI::SelectRandomNotStomach(), npc_scholomance_occultist::npc_scholomance_occultistAI::SelectUnitCasting(), Player::SendComboPoints(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::SetDest(), Unit::SetFeared(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::SetGUID(), Unit::SetSpeed(), Spell::Spell(), Vehicle::TeleportVehicle(), npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_eachother(), TotemAI::UpdateAI(), npc_rocknot::npc_rocknotAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_bigbadwolf::boss_bigbadwolfAI::UpdateAI(), npc_image_of_medivh::npc_image_of_medivhAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_healing_ward::npc_healing_wardAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), npc_ancient_wisp::npc_ancient_wispAI::UpdateAI(), npc_doomfire_targetting::npc_doomfire_targettingAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), hyjalAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_garments_of_quests::npc_garments_of_questsAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), PetAI::UpdateAI(), npc_frost_tomb::npc_frost_tombAI::UpdateAI(), Spell::UpdateChanneledTargetList(), HostileReference::updateOnlineStatus(), Spell::UpdatePointers(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), boss_anetheron::boss_anetheronAI::WaypointReached(), boss_azgalor::boss_azgalorAI::WaypointReached(), boss_kazrogal::boss_kazrogalAI::WaypointReached(), boss_rage_winterchill::boss_rage_winterchillAI::WaypointReached(), npc_giant_infernal::npc_giant_infernalAI::WaypointReached(), npc_abomination::npc_abominationAI::WaypointReached(), npc_ghoul::npc_ghoulAI::WaypointReached(), npc_necromancer::npc_necromancerAI::WaypointReached(), npc_banshee::npc_bansheeAI::WaypointReached(), npc_crypt_fiend::npc_crypt_fiendAI::WaypointReached(), npc_fel_stalker::npc_fel_stalkerAI::WaypointReached(), npc_frost_wyrm::npc_frost_wyrmAI::WaypointReached(), npc_gargoyle::npc_gargoyleAI::WaypointReached(), and Vehicle::~Vehicle().
GetWorldObject()
WorldObject * ObjectAccessor::GetWorldObject (WorldObject const & p, ObjectGuid const guid)
Definition at line 115 of file ObjectAccessor.cpp.
 {
     switch (guid.GetHigh())
     {
         case HighGuid::Player:
             return GetPlayer(p, guid);
         case HighGuid::Transport:
         case HighGuid::Mo_Transport:
         case HighGuid::GameObject:
             return GetGameObject(p, guid);
         case HighGuid::Vehicle:
         case HighGuid::Unit:
             return GetCreature(p, guid);
         case HighGuid::Pet:
             return GetPet(p, guid);
         case HighGuid::DynamicObject:
             return GetDynamicObject(p, guid);
         case HighGuid::Corpse:
             return GetCorpse(p, guid);
         default:
             return nullptr;
     }
     return nullptr;
 }
References Corpse, DynamicObject, GameObject, GetCorpse(), GetCreature(), GetDynamicObject(), GetGameObject(), ObjectGuid::GetHigh(), GetPet(), GetPlayer(), Mo_Transport, Pet, Player, Transport, Unit, and Vehicle.
Referenced by ObjectGuidList::GetObjectList(), SpellCastTargets::GetObjectTargetChannel(), TempSummon::GetSummoner(), Acore::VisibleNotifier::SendToSelf(), SpellCastTargets::Update(), and Spell::UpdatePointers().
RemoveObject() [1/2]
template<> void ObjectAccessor::RemoveObject (Player * player)
Definition at line 288 of file ObjectAccessor.cpp.
 {
     HashMapHolder<Player>::Remove(player);
     PlayerNameMapHolder::Remove(player);
 }
References PlayerNameMapHolder::Remove(), and HashMapHolder< T >::Remove().
RemoveObject() [2/2]
template<class T > void ObjectAccessor::RemoveObject (T * object)
Definition at line 97 of file ObjectAccessor.h.
     {
         HashMapHolder<T>::Remove(object);
     }
References HashMapHolder< T >::Remove().
Referenced by Map::DeleteFromWorld().
SaveAllPlayers()
void ObjectAccessor::SaveAllPlayers ()
Definition at line 262 of file ObjectAccessor.cpp.
 {
     std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
     HashMapHolder<Player>::MapType const& m = GetPlayers();
     for (HashMapHolder<Player>::MapType::const_iterator itr = m.begin(); itr != m.end(); ++itr)
         itr->second->SaveToDB(false, false);
 }
References GetPlayers().
Referenced by misc_commandscript::HandleSaveAllCommand().