Azerotcore-wotlk: TimedFleeingMovementGenerator Class Reference
TimedFleeingMovementGenerator Class Reference
#include <FleeingMovementGenerator.h>
Public Member Functions
TimedFleeingMovementGenerator (ObjectGuid fright, uint32 time)
MovementGeneratorType GetMovementGeneratorType ()
bool Update (Unit *, uint32)
void Finalize (Unit *)
Public Member Functions inherited from FleeingMovementGenerator< Creature >
FleeingMovementGenerator (ObjectGuid fright)
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoFinalize (Player *owner)
void DoReset (Creature *)
bool DoUpdate (Creature *, uint32)
MovementGeneratorType GetMovementGeneratorType ()
Public Member Functions inherited from MovementGeneratorMedium< T, D >
void Initialize (Unit *u) override
void Reset (Unit *u) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
TimeTracker i_totalFleeTime
Detailed Description
Definition at line 56 of file FleeingMovementGenerator.h.
Constructor & Destructor Documentation
TimedFleeingMovementGenerator()
TimedFleeingMovementGenerator::TimedFleeingMovementGenerator (ObjectGuid fright, uint32 time) inline
Definition at line 59 of file FleeingMovementGenerator.h.
                                                                   :
         FleeingMovementGenerator<Creature>(fright),
         i_totalFleeTime(time) {}
Member Function Documentation
Finalize()
void TimedFleeingMovementGenerator::Finalize (Unit * owner) virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 377 of file FleeingMovementGenerator.cpp.
 {
     owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
     owner->ClearUnitState(UNIT_STATE_FLEEING | UNIT_STATE_FLEEING_MOVE);
     if (owner->GetVictim())
         owner->SetTarget(owner->GetVictim()->GetGUID());
 }
References Unit::ClearUnitState(), Object::GetGUID(), Unit::GetVictim(), Object::RemoveFlag(), Unit::SetTarget(), UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, UNIT_STATE_FLEEING, and UNIT_STATE_FLEEING_MOVE.
GetMovementGeneratorType()
MovementGeneratorType TimedFleeingMovementGenerator::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 63 of file FleeingMovementGenerator.h.
 { return TIMED_FLEEING_MOTION_TYPE; }
References TIMED_FLEEING_MOTION_TYPE.
Update()
bool TimedFleeingMovementGenerator::Update (Unit * owner, uint32 time_diff) virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 385 of file FleeingMovementGenerator.cpp.
 {
     if (!owner->IsAlive())
         return false;
     if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || owner->IsMovementPreventedByCasting())
     {
         owner->StopMoving();
         return true;
     }
     i_totalFleeTime.Update(time_diff);
     if (i_totalFleeTime.Passed())
         return false;
     // This calls grant-parent Update method hiden by FleeingMovementGenerator::Update(Creature &, uint32) version
     // This is done instead of casting Unit& to Creature& and call parent method, then we can use Unit directly
     return MovementGeneratorMedium< Creature, FleeingMovementGenerator<Creature> >::Update(owner, time_diff);
 }
References Unit::HasUnitState(), i_totalFleeTime, Unit::IsAlive(), Unit::IsMovementPreventedByCasting(), TimeTracker::Passed(), Unit::StopMoving(), UNIT_STATE_NOT_MOVE, and TimeTracker::Update().
Member Data Documentation
i_totalFleeTime
TimeTracker TimedFleeingMovementGenerator::i_totalFleeTime private
Definition at line 68 of file FleeingMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.h
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp