Azerotcore-wotlk: AssistanceMovementGenerator Class Reference
AssistanceMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
AssistanceMovementGenerator (float _x, float _y, float _z)
MovementGeneratorType GetMovementGeneratorType ()
void Finalize (Unit *)
Public Member Functions inherited from PointMovementGenerator< Creature >
PointMovementGenerator (uint32 _id, float _x, float _y, float _z, float _speed=0.0f, float orientation=0.0f, const Movement::PointsArray *_path=nullptr, bool generatePath=false, bool forceDestination=false, ObjectGuid chargeTargetGUID=ObjectGuid::Empty)
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoReset (Creature *)
bool DoUpdate (Creature *, uint32)
void MovementInform (Creature *)
void unitSpeedChanged ()
MovementGeneratorType GetMovementGeneratorType ()
bool GetDestination (float &x, float &y, float &z) const
Public Member Functions inherited from MovementGeneratorMedium< T, D >
void Initialize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual bool GetResetPosition (float &, float &, float &)
Detailed Description
Definition at line 61 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
AssistanceMovementGenerator()
AssistanceMovementGenerator::AssistanceMovementGenerator (float _x, float _y, float _z) inline
Definition at line 64 of file PointMovementGenerator.h.
                                                               :
         PointMovementGenerator<Creature>(0, _x, _y, _z) {}
Member Function Documentation
Finalize()
void AssistanceMovementGenerator::Finalize (Unit * unit) virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 197 of file PointMovementGenerator.cpp.
 {
     unit->ToCreature()->SetNoCallAssistance(false);
     unit->ToCreature()->CallAssistance();
     if (unit->IsAlive())
         unit->GetMotionMaster()->MoveSeekAssistanceDistract(sWorld->getIntConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY));
 }
References Creature::CallAssistance(), CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY, Unit::GetMotionMaster(), Unit::IsAlive(), MotionMaster::MoveSeekAssistanceDistract(), Creature::SetNoCallAssistance(), sWorld, and Object::ToCreature().
GetMovementGeneratorType()
MovementGeneratorType AssistanceMovementGenerator::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 67 of file PointMovementGenerator.h.
 { return ASSISTANCE_MOTION_TYPE; }
References ASSISTANCE_MOTION_TYPE.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp