Azerotcore-wotlk: src/server/game/Spells/SpellInfo.h File Reference
SpellInfo.h File Reference
#include "DBCStructure.h"
#include "Object.h"
#include "SharedDefines.h"
#include "SpellAuraDefines.h"
#include "Util.h"
Classes
class SpellImplicitTargetInfo
struct SpellImplicitTargetInfo::StaticData
class SpellEffectInfo
struct SpellEffectInfo::StaticData
class SpellInfo
Enumerations
enum SpellCastTargetFlags {
TARGET_FLAG_NONE = 0x00000000 , TARGET_FLAG_UNUSED_1 = 0x00000001 , TARGET_FLAG_UNIT = 0x00000002 , TARGET_FLAG_UNIT_RAID = 0x00000004 ,
TARGET_FLAG_UNIT_PARTY = 0x00000008 , TARGET_FLAG_ITEM = 0x00000010 , TARGET_FLAG_SOURCE_LOCATION = 0x00000020 , TARGET_FLAG_DEST_LOCATION = 0x00000040 ,
TARGET_FLAG_UNIT_ENEMY = 0x00000080 , TARGET_FLAG_UNIT_ALLY = 0x00000100 , TARGET_FLAG_CORPSE_ENEMY = 0x00000200 , TARGET_FLAG_UNIT_DEAD = 0x00000400 ,
TARGET_FLAG_GAMEOBJECT = 0x00000800 , TARGET_FLAG_TRADE_ITEM = 0x00001000 , TARGET_FLAG_STRING = 0x00002000 , TARGET_FLAG_GAMEOBJECT_ITEM = 0x00004000 ,
TARGET_FLAG_CORPSE_ALLY = 0x00008000 , TARGET_FLAG_UNIT_MINIPET = 0x00010000 , TARGET_FLAG_GLYPH_SLOT = 0x00020000 , TARGET_FLAG_DEST_TARGET = 0x00040000 ,
TARGET_FLAG_UNUSED20 = 0x00080000 , TARGET_FLAG_UNIT_PASSENGER = 0x00100000 , TARGET_FLAG_UNIT_MASK , TARGET_FLAG_GAMEOBJECT_MASK = TARGET_FLAG_GAMEOBJECT | TARGET_FLAG_GAMEOBJECT_ITEM ,
TARGET_FLAG_CORPSE_MASK = TARGET_FLAG_CORPSE_ALLY | TARGET_FLAG_CORPSE_ENEMY , TARGET_FLAG_ITEM_MASK = TARGET_FLAG_TRADE_ITEM | TARGET_FLAG_ITEM | TARGET_FLAG_GAMEOBJECT_ITEM
}
enum SpellTargetSelectionCategories {
TARGET_SELECT_CATEGORY_NYI , TARGET_SELECT_CATEGORY_DEFAULT , TARGET_SELECT_CATEGORY_CHANNEL , TARGET_SELECT_CATEGORY_NEARBY ,
TARGET_SELECT_CATEGORY_CONE , TARGET_SELECT_CATEGORY_AREA , TARGET_SELECT_CATEGORY_TRAJ
}
enum SpellTargetReferenceTypes {
TARGET_REFERENCE_TYPE_NONE , TARGET_REFERENCE_TYPE_CASTER , TARGET_REFERENCE_TYPE_TARGET , TARGET_REFERENCE_TYPE_LAST ,
TARGET_REFERENCE_TYPE_SRC , TARGET_REFERENCE_TYPE_DEST
}
enum SpellTargetObjectTypes {
TARGET_OBJECT_TYPE_NONE = 0 , TARGET_OBJECT_TYPE_SRC , TARGET_OBJECT_TYPE_DEST , TARGET_OBJECT_TYPE_UNIT ,
TARGET_OBJECT_TYPE_UNIT_AND_DEST , TARGET_OBJECT_TYPE_GOBJ , TARGET_OBJECT_TYPE_GOBJ_ITEM , TARGET_OBJECT_TYPE_ITEM ,
TARGET_OBJECT_TYPE_CORPSE , TARGET_OBJECT_TYPE_CORPSE_ENEMY , TARGET_OBJECT_TYPE_CORPSE_ALLY
}
enum SpellTargetCheckTypes {
TARGET_CHECK_DEFAULT , TARGET_CHECK_ENTRY , TARGET_CHECK_ENEMY , TARGET_CHECK_ALLY ,
TARGET_CHECK_PARTY , TARGET_CHECK_RAID , TARGET_CHECK_RAID_CLASS , TARGET_CHECK_PASSENGER ,
TARGET_CHECK_CORPSE
}
enum SpellTargetDirectionTypes {
TARGET_DIR_NONE , TARGET_DIR_FRONT , TARGET_DIR_BACK , TARGET_DIR_RIGHT ,
TARGET_DIR_LEFT , TARGET_DIR_FRONT_RIGHT , TARGET_DIR_BACK_RIGHT , TARGET_DIR_BACK_LEFT ,
TARGET_DIR_FRONT_LEFT , TARGET_DIR_RANDOM , TARGET_DIR_ENTRY
}
enum SpellEffectImplicitTargetTypes { EFFECT_IMPLICIT_TARGET_NONE = 0 , EFFECT_IMPLICIT_TARGET_EXPLICIT , EFFECT_IMPLICIT_TARGET_CASTER }
enum SpellSpecificType {
SPELL_SPECIFIC_NORMAL = 0 , SPELL_SPECIFIC_SEAL = 1 , SPELL_SPECIFIC_AURA = 3 , SPELL_SPECIFIC_STING = 4 ,
SPELL_SPECIFIC_CURSE = 5 , SPELL_SPECIFIC_ASPECT = 6 , SPELL_SPECIFIC_TRACKER = 7 , SPELL_SPECIFIC_WARLOCK_ARMOR = 8 ,
SPELL_SPECIFIC_MAGE_ARMOR = 9 , SPELL_SPECIFIC_ELEMENTAL_SHIELD = 10 , SPELL_SPECIFIC_MAGE_POLYMORPH = 11 , SPELL_SPECIFIC_JUDGEMENT = 13 ,
SPELL_SPECIFIC_WARLOCK_CORRUPTION = 17 , SPELL_SPECIFIC_FOOD = 19 , SPELL_SPECIFIC_DRINK = 20 , SPELL_SPECIFIC_FOOD_AND_DRINK = 21 ,
SPELL_SPECIFIC_PRESENCE = 22 , SPELL_SPECIFIC_CHARM = 23 , SPELL_SPECIFIC_SCROLL = 24 , SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE = 25 ,
SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT = 26 , SPELL_SPECIFIC_HAND = 27
}
enum SpellCustomAttributes {
SPELL_ATTR0_CU_ENCHANT_PROC = 0x00000001 , SPELL_ATTR0_CU_CONE_BACK = 0x00000002 , SPELL_ATTR0_CU_CONE_LINE = 0x00000004 , SPELL_ATTR0_CU_SHARE_DAMAGE = 0x00000008 ,
SPELL_ATTR0_CU_NO_INITIAL_THREAT = 0x00000010 , SPELL_ATTR0_CU_AURA_CC = 0x00000020 , SPELL_ATTR0_CU_DONT_BREAK_STEALTH = 0x00000040 , SPELL_ATTR0_CU_NO_PVP_FLAG = 0x00000080 ,
SPELL_ATTR0_CU_DIRECT_DAMAGE = 0x00000100 , SPELL_ATTR0_CU_CHARGE = 0x00000200 , SPELL_ATTR0_CU_PICKPOCKET = 0x00000400 , SPELL_ATTR0_CU_NONE4 = 0x00000800 ,
SPELL_ATTR0_CU_NEGATIVE_EFF0 = 0x00001000 , SPELL_ATTR0_CU_NEGATIVE_EFF1 = 0x00002000 , SPELL_ATTR0_CU_NEGATIVE_EFF2 = 0x00004000 , SPELL_ATTR0_CU_IGNORE_ARMOR = 0x00008000 ,
SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER = 0x00010000 , SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET = 0x00020000 , SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET = 0x00040000 , SPELL_ATTR0_CU_NEEDS_AMMO_DATA = 0x00080000 ,
SPELL_ATTR0_CU_BINARY_SPELL = 0x00100000 , SPELL_ATTR0_CU_NO_POSITIVE_TAKEN_BONUS = 0x00200000 , SPELL_ATTR0_CU_SINGLE_AURA_STACK = 0x00400000 , SPELL_ATTR0_CU_SCHOOLMASK_NORMAL_WITH_MAGIC = 0x00800000 ,
SPELL_ATTR0_CU_ENCOUNTER_REWARD = 0x01000000 , SPELL_ATTR0_CU_POSITIVE_EFF0 = 0x02000000 , SPELL_ATTR0_CU_POSITIVE_EFF1 = 0x04000000 , SPELL_ATTR0_CU_POSITIVE_EFF2 = 0x08000000 ,
SPELL_ATTR0_CU_REJECT_AURA_SAVING = 0x10000000 , SPELL_ATTR0_CU_FORCE_AURA_SAVING = 0x20000800 , SPELL_ATTR0_CU_NEGATIVE = SPELL_ATTR0_CU_NEGATIVE_EFF0 | SPELL_ATTR0_CU_NEGATIVE_EFF1 | SPELL_ATTR0_CU_NEGATIVE_EFF2 , SPELL_ATTR0_CU_POSITIVE = SPELL_ATTR0_CU_POSITIVE_EFF0 | SPELL_ATTR0_CU_POSITIVE_EFF1 | SPELL_ATTR0_CU_POSITIVE_EFF2
}
Functions
uint32 GetTargetFlagMask (SpellTargetObjectTypes objType)
Enumeration Type Documentation
SpellCastTargetFlags
enum SpellCastTargetFlags
Enumerator
TARGET_FLAG_NONE
TARGET_FLAG_UNUSED_1
TARGET_FLAG_UNIT
TARGET_FLAG_UNIT_RAID
TARGET_FLAG_UNIT_PARTY
TARGET_FLAG_ITEM
TARGET_FLAG_SOURCE_LOCATION
TARGET_FLAG_DEST_LOCATION
TARGET_FLAG_UNIT_ENEMY
TARGET_FLAG_UNIT_ALLY
TARGET_FLAG_CORPSE_ENEMY
TARGET_FLAG_UNIT_DEAD
TARGET_FLAG_GAMEOBJECT
TARGET_FLAG_TRADE_ITEM
TARGET_FLAG_STRING
TARGET_FLAG_GAMEOBJECT_ITEM
TARGET_FLAG_CORPSE_ALLY
TARGET_FLAG_UNIT_MINIPET
TARGET_FLAG_GLYPH_SLOT
TARGET_FLAG_DEST_TARGET
TARGET_FLAG_UNUSED20
TARGET_FLAG_UNIT_PASSENGER
TARGET_FLAG_UNIT_MASK
TARGET_FLAG_GAMEOBJECT_MASK
TARGET_FLAG_CORPSE_MASK
TARGET_FLAG_ITEM_MASK
Definition at line 43 of file SpellInfo.h.
 {
     TARGET_FLAG_NONE            = 0x00000000,
     TARGET_FLAG_UNUSED_1        = 0x00000001,               // not used
     TARGET_FLAG_UNIT            = 0x00000002,               // pguid
     TARGET_FLAG_UNIT_RAID       = 0x00000004,               // not sent, used to validate target (if raid member)
     TARGET_FLAG_UNIT_PARTY      = 0x00000008,               // not sent, used to validate target (if party member)
     TARGET_FLAG_ITEM            = 0x00000010,               // pguid
     TARGET_FLAG_SOURCE_LOCATION = 0x00000020,               // pguid, 3 float
     TARGET_FLAG_DEST_LOCATION   = 0x00000040,               // pguid, 3 float
     TARGET_FLAG_UNIT_ENEMY      = 0x00000080,               // not sent, used to validate target (if enemy)
     TARGET_FLAG_UNIT_ALLY       = 0x00000100,               // not sent, used to validate target (if ally)
     TARGET_FLAG_CORPSE_ENEMY    = 0x00000200,               // pguid
     TARGET_FLAG_UNIT_DEAD       = 0x00000400,               // not sent, used to validate target (if dead creature)
     TARGET_FLAG_GAMEOBJECT      = 0x00000800,               // pguid, used with TARGET_GAMEOBJECT_TARGET
     TARGET_FLAG_TRADE_ITEM      = 0x00001000,               // pguid
     TARGET_FLAG_STRING          = 0x00002000,               // string
     TARGET_FLAG_GAMEOBJECT_ITEM = 0x00004000,               // not sent, used with TARGET_GAMEOBJECT_ITEM_TARGET
     TARGET_FLAG_CORPSE_ALLY     = 0x00008000,               // pguid
     TARGET_FLAG_UNIT_MINIPET    = 0x00010000,               // pguid, used to validate target (if non combat pet)
     TARGET_FLAG_GLYPH_SLOT      = 0x00020000,               // used in glyph spells
     TARGET_FLAG_DEST_TARGET     = 0x00040000,               // sometimes appears with DEST_TARGET spells (may appear or not for a given spell)
     TARGET_FLAG_UNUSED20        = 0x00080000,               // uint32 counter, loop { vec3 - screen position (?), guid }, not used so far
     TARGET_FLAG_UNIT_PASSENGER  = 0x00100000,               // guessed, used to validate target (if vehicle passenger)
     TARGET_FLAG_UNIT_MASK = TARGET_FLAG_UNIT | TARGET_FLAG_UNIT_RAID | TARGET_FLAG_UNIT_PARTY
                             | TARGET_FLAG_UNIT_ENEMY | TARGET_FLAG_UNIT_ALLY | TARGET_FLAG_UNIT_DEAD | TARGET_FLAG_UNIT_MINIPET | TARGET_FLAG_UNIT_PASSENGER,
     TARGET_FLAG_GAMEOBJECT_MASK = TARGET_FLAG_GAMEOBJECT | TARGET_FLAG_GAMEOBJECT_ITEM,
     TARGET_FLAG_CORPSE_MASK = TARGET_FLAG_CORPSE_ALLY | TARGET_FLAG_CORPSE_ENEMY,
     TARGET_FLAG_ITEM_MASK = TARGET_FLAG_TRADE_ITEM | TARGET_FLAG_ITEM | TARGET_FLAG_GAMEOBJECT_ITEM,
 };
SpellCustomAttributes
enum SpellCustomAttributes
Enumerator
SPELL_ATTR0_CU_ENCHANT_PROC
SPELL_ATTR0_CU_CONE_BACK
SPELL_ATTR0_CU_CONE_LINE
SPELL_ATTR0_CU_SHARE_DAMAGE
SPELL_ATTR0_CU_NO_INITIAL_THREAT
SPELL_ATTR0_CU_AURA_CC
SPELL_ATTR0_CU_DONT_BREAK_STEALTH
SPELL_ATTR0_CU_NO_PVP_FLAG
SPELL_ATTR0_CU_DIRECT_DAMAGE
SPELL_ATTR0_CU_CHARGE
SPELL_ATTR0_CU_PICKPOCKET
SPELL_ATTR0_CU_NONE4
SPELL_ATTR0_CU_NEGATIVE_EFF0
SPELL_ATTR0_CU_NEGATIVE_EFF1
SPELL_ATTR0_CU_NEGATIVE_EFF2
SPELL_ATTR0_CU_IGNORE_ARMOR
SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER
SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET
SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET
SPELL_ATTR0_CU_NEEDS_AMMO_DATA
SPELL_ATTR0_CU_BINARY_SPELL
SPELL_ATTR0_CU_NO_POSITIVE_TAKEN_BONUS
SPELL_ATTR0_CU_SINGLE_AURA_STACK
SPELL_ATTR0_CU_SCHOOLMASK_NORMAL_WITH_MAGIC
SPELL_ATTR0_CU_ENCOUNTER_REWARD
SPELL_ATTR0_CU_POSITIVE_EFF0
SPELL_ATTR0_CU_POSITIVE_EFF1
SPELL_ATTR0_CU_POSITIVE_EFF2
SPELL_ATTR0_CU_REJECT_AURA_SAVING
SPELL_ATTR0_CU_FORCE_AURA_SAVING
SPELL_ATTR0_CU_NEGATIVE
SPELL_ATTR0_CU_POSITIVE
Definition at line 174 of file SpellInfo.h.
 {
     SPELL_ATTR0_CU_ENCHANT_PROC                  = 0x00000001,
     SPELL_ATTR0_CU_CONE_BACK                     = 0x00000002,
     SPELL_ATTR0_CU_CONE_LINE                     = 0x00000004,
     SPELL_ATTR0_CU_SHARE_DAMAGE                  = 0x00000008,
     SPELL_ATTR0_CU_NO_INITIAL_THREAT             = 0x00000010,
     SPELL_ATTR0_CU_AURA_CC                       = 0x00000020,
     SPELL_ATTR0_CU_DONT_BREAK_STEALTH            = 0x00000040,
     SPELL_ATTR0_CU_NO_PVP_FLAG                   = 0x00000080,
     SPELL_ATTR0_CU_DIRECT_DAMAGE                 = 0x00000100,
     SPELL_ATTR0_CU_CHARGE                        = 0x00000200,
     SPELL_ATTR0_CU_PICKPOCKET                    = 0x00000400,
     SPELL_ATTR0_CU_NONE4                         = 0x00000800,   // UNUSED
     SPELL_ATTR0_CU_NEGATIVE_EFF0                 = 0x00001000,
     SPELL_ATTR0_CU_NEGATIVE_EFF1                 = 0x00002000,
     SPELL_ATTR0_CU_NEGATIVE_EFF2                 = 0x00004000,
     SPELL_ATTR0_CU_IGNORE_ARMOR                  = 0x00008000,
     SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER      = 0x00010000,
     SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET      = 0x00020000,
     SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET         = 0x00040000,
     SPELL_ATTR0_CU_NEEDS_AMMO_DATA               = 0x00080000,
     SPELL_ATTR0_CU_BINARY_SPELL                  = 0x00100000,
     SPELL_ATTR0_CU_NO_POSITIVE_TAKEN_BONUS       = 0x00200000,
     SPELL_ATTR0_CU_SINGLE_AURA_STACK             = 0x00400000, // pussywizard
     SPELL_ATTR0_CU_SCHOOLMASK_NORMAL_WITH_MAGIC  = 0x00800000,
     SPELL_ATTR0_CU_ENCOUNTER_REWARD              = 0x01000000, // pussywizard
     SPELL_ATTR0_CU_POSITIVE_EFF0                 = 0x02000000,
     SPELL_ATTR0_CU_POSITIVE_EFF1                 = 0x04000000,
     SPELL_ATTR0_CU_POSITIVE_EFF2                 = 0x08000000,
     SPELL_ATTR0_CU_REJECT_AURA_SAVING            = 0x10000000,
     SPELL_ATTR0_CU_FORCE_AURA_SAVING             = 0x20000800,
     SPELL_ATTR0_CU_NEGATIVE                      = SPELL_ATTR0_CU_NEGATIVE_EFF0 | SPELL_ATTR0_CU_NEGATIVE_EFF1 | SPELL_ATTR0_CU_NEGATIVE_EFF2,
     SPELL_ATTR0_CU_POSITIVE                      = SPELL_ATTR0_CU_POSITIVE_EFF0 | SPELL_ATTR0_CU_POSITIVE_EFF1 | SPELL_ATTR0_CU_POSITIVE_EFF2,
 };
SpellEffectImplicitTargetTypes
enum SpellEffectImplicitTargetTypes
Enumerator
EFFECT_IMPLICIT_TARGET_NONE
EFFECT_IMPLICIT_TARGET_EXPLICIT
EFFECT_IMPLICIT_TARGET_CASTER
Definition at line 140 of file SpellInfo.h.
 {
     EFFECT_IMPLICIT_TARGET_NONE = 0,
     EFFECT_IMPLICIT_TARGET_EXPLICIT,
     EFFECT_IMPLICIT_TARGET_CASTER,
 };
SpellSpecificType
enum SpellSpecificType
Enumerator
SPELL_SPECIFIC_NORMAL
SPELL_SPECIFIC_SEAL
SPELL_SPECIFIC_AURA
SPELL_SPECIFIC_STING
SPELL_SPECIFIC_CURSE
SPELL_SPECIFIC_ASPECT
SPELL_SPECIFIC_TRACKER
SPELL_SPECIFIC_WARLOCK_ARMOR
SPELL_SPECIFIC_MAGE_ARMOR
SPELL_SPECIFIC_ELEMENTAL_SHIELD
SPELL_SPECIFIC_MAGE_POLYMORPH
SPELL_SPECIFIC_JUDGEMENT
SPELL_SPECIFIC_WARLOCK_CORRUPTION
SPELL_SPECIFIC_FOOD
SPELL_SPECIFIC_DRINK
SPELL_SPECIFIC_FOOD_AND_DRINK
SPELL_SPECIFIC_PRESENCE
SPELL_SPECIFIC_CHARM
SPELL_SPECIFIC_SCROLL
SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE
SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT
SPELL_SPECIFIC_HAND
Definition at line 148 of file SpellInfo.h.
 {
     SPELL_SPECIFIC_NORMAL                        = 0,
     SPELL_SPECIFIC_SEAL                          = 1,
     SPELL_SPECIFIC_AURA                          = 3,
     SPELL_SPECIFIC_STING                         = 4,
     SPELL_SPECIFIC_CURSE                         = 5,
     SPELL_SPECIFIC_ASPECT                        = 6,
     SPELL_SPECIFIC_TRACKER                       = 7,
     SPELL_SPECIFIC_WARLOCK_ARMOR                 = 8,
     SPELL_SPECIFIC_MAGE_ARMOR                    = 9,
     SPELL_SPECIFIC_ELEMENTAL_SHIELD              = 10,
     SPELL_SPECIFIC_MAGE_POLYMORPH                = 11,
     SPELL_SPECIFIC_JUDGEMENT                     = 13,
     SPELL_SPECIFIC_WARLOCK_CORRUPTION            = 17,
     SPELL_SPECIFIC_FOOD                          = 19,
     SPELL_SPECIFIC_DRINK                         = 20,
     SPELL_SPECIFIC_FOOD_AND_DRINK                = 21,
     SPELL_SPECIFIC_PRESENCE                      = 22,
     SPELL_SPECIFIC_CHARM                         = 23,
     SPELL_SPECIFIC_SCROLL                        = 24,
     SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE         = 25,
     SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT          = 26,
     SPELL_SPECIFIC_HAND                          = 27,
 };
SpellTargetCheckTypes
enum SpellTargetCheckTypes
Enumerator
TARGET_CHECK_DEFAULT
TARGET_CHECK_ENTRY
TARGET_CHECK_ENEMY
TARGET_CHECK_ALLY
TARGET_CHECK_PARTY
TARGET_CHECK_RAID
TARGET_CHECK_RAID_CLASS
TARGET_CHECK_PASSENGER
TARGET_CHECK_CORPSE
Definition at line 112 of file SpellInfo.h.
 {
     TARGET_CHECK_DEFAULT,
     TARGET_CHECK_ENTRY,
     TARGET_CHECK_ENEMY,
     TARGET_CHECK_ALLY,
     TARGET_CHECK_PARTY,
     TARGET_CHECK_RAID,
     TARGET_CHECK_RAID_CLASS,
     TARGET_CHECK_PASSENGER,
     TARGET_CHECK_CORPSE,
 };
SpellTargetDirectionTypes
enum SpellTargetDirectionTypes
Enumerator
TARGET_DIR_NONE
TARGET_DIR_FRONT
TARGET_DIR_BACK
TARGET_DIR_RIGHT
TARGET_DIR_LEFT
TARGET_DIR_FRONT_RIGHT
TARGET_DIR_BACK_RIGHT
TARGET_DIR_BACK_LEFT
TARGET_DIR_FRONT_LEFT
TARGET_DIR_RANDOM
TARGET_DIR_ENTRY
Definition at line 125 of file SpellInfo.h.
 {
     TARGET_DIR_NONE,
     TARGET_DIR_FRONT,
     TARGET_DIR_BACK,
     TARGET_DIR_RIGHT,
     TARGET_DIR_LEFT,
     TARGET_DIR_FRONT_RIGHT,
     TARGET_DIR_BACK_RIGHT,
     TARGET_DIR_BACK_LEFT,
     TARGET_DIR_FRONT_LEFT,
     TARGET_DIR_RANDOM,
     TARGET_DIR_ENTRY,
 };
SpellTargetObjectTypes
enum SpellTargetObjectTypes
Enumerator
TARGET_OBJECT_TYPE_NONE
TARGET_OBJECT_TYPE_SRC
TARGET_OBJECT_TYPE_DEST
TARGET_OBJECT_TYPE_UNIT
TARGET_OBJECT_TYPE_UNIT_AND_DEST
TARGET_OBJECT_TYPE_GOBJ
TARGET_OBJECT_TYPE_GOBJ_ITEM
TARGET_OBJECT_TYPE_ITEM
TARGET_OBJECT_TYPE_CORPSE
TARGET_OBJECT_TYPE_CORPSE_ENEMY
TARGET_OBJECT_TYPE_CORPSE_ALLY
Definition at line 96 of file SpellInfo.h.
 {
     TARGET_OBJECT_TYPE_NONE = 0,
     TARGET_OBJECT_TYPE_SRC,
     TARGET_OBJECT_TYPE_DEST,
     TARGET_OBJECT_TYPE_UNIT,
     TARGET_OBJECT_TYPE_UNIT_AND_DEST,
     TARGET_OBJECT_TYPE_GOBJ,
     TARGET_OBJECT_TYPE_GOBJ_ITEM,
     TARGET_OBJECT_TYPE_ITEM,
     TARGET_OBJECT_TYPE_CORPSE,
     // only for effect target type
     TARGET_OBJECT_TYPE_CORPSE_ENEMY,
     TARGET_OBJECT_TYPE_CORPSE_ALLY,
 };
SpellTargetReferenceTypes
enum SpellTargetReferenceTypes
Enumerator
TARGET_REFERENCE_TYPE_NONE
TARGET_REFERENCE_TYPE_CASTER
TARGET_REFERENCE_TYPE_TARGET
TARGET_REFERENCE_TYPE_LAST
TARGET_REFERENCE_TYPE_SRC
TARGET_REFERENCE_TYPE_DEST
Definition at line 86 of file SpellInfo.h.
 {
     TARGET_REFERENCE_TYPE_NONE,
     TARGET_REFERENCE_TYPE_CASTER,
     TARGET_REFERENCE_TYPE_TARGET,
     TARGET_REFERENCE_TYPE_LAST,
     TARGET_REFERENCE_TYPE_SRC,
     TARGET_REFERENCE_TYPE_DEST,
 };
SpellTargetSelectionCategories
enum SpellTargetSelectionCategories
Enumerator
TARGET_SELECT_CATEGORY_NYI
TARGET_SELECT_CATEGORY_DEFAULT
TARGET_SELECT_CATEGORY_CHANNEL
TARGET_SELECT_CATEGORY_NEARBY
TARGET_SELECT_CATEGORY_CONE
TARGET_SELECT_CATEGORY_AREA
TARGET_SELECT_CATEGORY_TRAJ
Definition at line 75 of file SpellInfo.h.
 {
     TARGET_SELECT_CATEGORY_NYI,
     TARGET_SELECT_CATEGORY_DEFAULT,
     TARGET_SELECT_CATEGORY_CHANNEL,
     TARGET_SELECT_CATEGORY_NEARBY,
     TARGET_SELECT_CATEGORY_CONE,
     TARGET_SELECT_CATEGORY_AREA,
     TARGET_SELECT_CATEGORY_TRAJ,
 };
Function Documentation
GetTargetFlagMask()
uint32 GetTargetFlagMask (SpellTargetObjectTypes objType)
Definition at line 30 of file SpellInfo.cpp.
 {
     switch (objType)
     {
         case TARGET_OBJECT_TYPE_DEST:
             return TARGET_FLAG_DEST_LOCATION;
         case TARGET_OBJECT_TYPE_UNIT_AND_DEST:
             return TARGET_FLAG_DEST_LOCATION | TARGET_FLAG_UNIT;
         case TARGET_OBJECT_TYPE_CORPSE_ALLY:
             return TARGET_FLAG_CORPSE_ALLY;
         case TARGET_OBJECT_TYPE_CORPSE_ENEMY:
             return TARGET_FLAG_CORPSE_ENEMY;
         case TARGET_OBJECT_TYPE_CORPSE:
             return TARGET_FLAG_CORPSE_ALLY | TARGET_FLAG_CORPSE_ENEMY;
         case TARGET_OBJECT_TYPE_UNIT:
             return TARGET_FLAG_UNIT;
         case TARGET_OBJECT_TYPE_GOBJ:
             return TARGET_FLAG_GAMEOBJECT;
         case TARGET_OBJECT_TYPE_GOBJ_ITEM:
             return TARGET_FLAG_GAMEOBJECT_ITEM;
         case TARGET_OBJECT_TYPE_ITEM:
             return TARGET_FLAG_ITEM;
         case TARGET_OBJECT_TYPE_SRC:
             return TARGET_FLAG_SOURCE_LOCATION;
         default:
             return TARGET_FLAG_NONE;
     }
 }
References TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_GAMEOBJECT_ITEM, TARGET_FLAG_ITEM, TARGET_FLAG_NONE, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_UNIT, TARGET_OBJECT_TYPE_CORPSE, TARGET_OBJECT_TYPE_CORPSE_ALLY, TARGET_OBJECT_TYPE_CORPSE_ENEMY, TARGET_OBJECT_TYPE_DEST, TARGET_OBJECT_TYPE_GOBJ, TARGET_OBJECT_TYPE_GOBJ_ITEM, TARGET_OBJECT_TYPE_ITEM, TARGET_OBJECT_TYPE_SRC, TARGET_OBJECT_TYPE_UNIT, and TARGET_OBJECT_TYPE_UNIT_AND_DEST.
Referenced by SpellEffectInfo::GetMissingTargetMask(), SpellEffectInfo::GetProvidedTargetMask(), and Spell::SelectSpellTargets().