Azerotcore-wotlk: DefaultTargetSelector Struct Reference
DefaultTargetSelector Struct Reference
#include <UnitAI.h>
Public Member Functions
DefaultTargetSelector (Unit const *unit, float dist, bool playerOnly, int32 aura)
bool operator() (Unit const *target) const
Public Attributes
const Unit * me
float m_dist
bool m_playerOnly
int32 m_aura
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 42 of file UnitAI.h.
Constructor & Destructor Documentation
DefaultTargetSelector()
DefaultTargetSelector::DefaultTargetSelector (Unit const * unit, float dist, bool playerOnly, int32 aura) inline
Definition at line 53 of file UnitAI.h.
 : me(unit), m_dist(dist), m_playerOnly(playerOnly), m_aura(aura) {}
Member Function Documentation
operator()()
bool DefaultTargetSelector::operator() (Unit const * target) const inline
Definition at line 55 of file UnitAI.h.
     {
         if (!me)
             return false;
         if (!target)
             return false;
         if (m_playerOnly && (target->GetTypeId() != TYPEID_PLAYER))
             return false;
         if (m_dist > 0.0f && !me->IsWithinCombatRange(target, m_dist))
             return false;
         if (m_dist < 0.0f && me->IsWithinCombatRange(target, -m_dist))
             return false;
         if (m_aura)
         {
             if (m_aura > 0)
             {
                 if (!target->HasAura(m_aura))
                     return false;
             }
             else
             {
                 if (target->HasAura(-m_aura))
                     return false;
             }
         }
         return true;
     }
References Object::GetTypeId(), Unit::HasAura(), Unit::IsWithinCombatRange(), m_aura, m_dist, m_playerOnly, me, and TYPEID_PLAYER.
Member Data Documentation
m_aura
int32 DefaultTargetSelector::m_aura
Definition at line 47 of file UnitAI.h.
Referenced by operator()().
m_dist
float DefaultTargetSelector::m_dist
Definition at line 45 of file UnitAI.h.
Referenced by operator()().
m_playerOnly
bool DefaultTargetSelector::m_playerOnly
Definition at line 46 of file UnitAI.h.
Referenced by operator()().
me
const Unit* DefaultTargetSelector::me
Definition at line 44 of file UnitAI.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/game/AI/CoreAI/UnitAI.h