Azerotcore-wotlk: boss_xt002::boss_xt002AI Struct Reference
boss_xt002::boss_xt002AI Struct Reference
Public Member Functions
boss_xt002AI (Creature *pCreature)
void RescheduleEvents ()
void Reset () override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void AttachHeart ()
void JustReachedHome () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
uint8 _healthCheck
bool _hardMode
bool _nerfAchievement
bool _gravityAchievement
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 131 of file boss_xt002.cpp.
Constructor & Destructor Documentation
boss_xt002AI()
boss_xt002::boss_xt002AI::boss_xt002AI (Creature * pCreature) inline
Definition at line 133 of file boss_xt002.cpp.
                                           : ScriptedAI(pCreature), summons(me)
         {
             m_pInstance = pCreature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
AttachHeart()
void boss_xt002::boss_xt002AI::AttachHeart () inline
Definition at line 184 of file boss_xt002.cpp.
         {
             if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                 heart->SetHealth(heart->GetMaxHealth());
             else if (Creature* accessory = me->SummonCreature(NPC_XT002_HEART, *me, TEMPSUMMON_MANUAL_DESPAWN))
             {
                 accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                 if (!me->HandleSpellClick(accessory, 0))
                     accessory->DespawnOrUnsummon();
             }
         }
References Vehicle::GetPassenger(), Unit::GetVehicleKit(), Unit::HandleSpellClick(), HEART_VEHICLE_SEAT, ScriptedAI::me, NPC_XT002_HEART, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by EnterCombat().
DoAction()
void boss_xt002::boss_xt002AI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 255 of file boss_xt002.cpp.
         {
             if (param == DATA_XT002_NERF_ENGINEERING)
             {
                 _nerfAchievement = false;
                 return;
             }
             if (param == DATA_XT002_GRAVITY_ACHIEV)
             {
                 _gravityAchievement = false;
                 return;
             }
             if (!me->IsAlive() || _hardMode)
                 return;
             // heart destory
             if (param == ACTION_HEART_BROKEN)
             {
                 _hardMode = true;
                 me->SetLootMode(3); // hard mode + normal loot
                 me->SetMaxHealth(me->GetMaxHealth());
                 me->SetHealth(me->GetMaxHealth());
                 me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
                 me->CastSpell(me, SPELL_HEARTBREAK, true);
                 me->TextEmote("XT-002 Deconstructor's heart is severed from his body.", nullptr, true);
                 events.ScheduleEvent(EVENT_REMOVE_EMOTE, 4000);
                 return;
             }
             // damage from heart
             if (param > 0)
             {
                 // avoid reducing health under 1
                 int32 _final = std::min(param, int32(me->GetHealth() - 1));
                 me->ModifyHealth(-_final);
                 me->LowerPlayerDamageReq(_final);
             }
         }
References _gravityAchievement, _hardMode, _nerfAchievement, ACTION_HEART_BROKEN, Unit::CastSpell(), DATA_XT002_GRAVITY_ACHIEV, DATA_XT002_NERF_ENGINEERING, EVENT_REMOVE_EMOTE, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::IsAlive(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, Unit::ModifyHealth(), Object::SetByteValue(), Unit::SetHealth(), Creature::SetLootMode(), Unit::SetMaxHealth(), SPELL_HEARTBREAK, Unit::TextEmote(), UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, and UNIT_STAND_STATE_STAND.
EnterCombat()
void boss_xt002::boss_xt002AI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 198 of file boss_xt002.cpp.
         {
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             events.ScheduleEvent(EVENT_ENRAGE, 600000, 0, 0);
             events.ScheduleEvent(EVENT_CHECK_ROOM, 5000, 0, 0);
             RescheduleEvents(); // Other events are scheduled here
             me->setActive(true);
             me->Yell("New toys? For me? I promise I won't break them this time!", LANG_UNIVERSAL);
             me->PlayDirectSound(XT_SOUND_AGGRO);
             if (m_pInstance)
             {
                 m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER);
                 m_pInstance->SetData(TYPE_XT002, IN_PROGRESS);
                 if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                     pGo->SetGoState(GO_STATE_READY);
             }
             me->CallForHelp(175);
             me->SetInCombatWithZone();
             AttachHeart();
         }
References ACHIEVEMENT_MUST_DECONSTRUCT_FASTER, ACHIEVEMENT_TIMED_TYPE_EVENT, AttachHeart(), Creature::CallForHelp(), InstanceScript::DoStartTimedAchievement(), EMOTE_ONESHOT_NONE, EVENT_CHECK_ROOM, EVENT_ENRAGE, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_READY, GO_XT002_DOORS, IN_PROGRESS, LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, WorldObject::PlayDirectSound(), RescheduleEvents(), WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), Object::SetUInt32Value(), TYPE_XT002, UNIT_NPC_EMOTESTATE, XT_SOUND_AGGRO, and Unit::Yell().
GetData()
uint32 boss_xt002::boss_xt002AI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 298 of file boss_xt002.cpp.
         {
             if (param == DATA_XT002_NERF_ENGINEERING)
                 return _nerfAchievement;
             else if (param == DATA_XT002_GRAVITY_ACHIEV)
                 return _gravityAchievement;
             return 0;
         }
References _gravityAchievement, _nerfAchievement, DATA_XT002_GRAVITY_ACHIEV, and DATA_XT002_NERF_ENGINEERING.
JustDied()
void boss_xt002::boss_xt002AI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 239 of file boss_xt002.cpp.
         {
             me->Yell("You are bad... Toys... Very... Baaaaad!", LANG_UNIVERSAL);
             me->PlayDirectSound(XT_SOUND_DEATH);
             if (m_pInstance)
             {
                 m_pInstance->SetData(TYPE_XT002, DONE);
                 if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                     pGo->SetGoState(GO_STATE_ACTIVE);
             }
             // Despawn summons
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), DONE, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, GO_XT002_DOORS, LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, WorldObject::PlayDirectSound(), ZoneScript::SetData(), summons, TYPE_XT002, XT_SOUND_DEATH, and Unit::Yell().
JustReachedHome()
void boss_xt002::boss_xt002AI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 196 of file boss_xt002.cpp.
 { me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_xt002::boss_xt002AI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 181 of file boss_xt002.cpp.
 { summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_xt002::boss_xt002AI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 222 of file boss_xt002.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER && !urand(0, 2))
             {
                 if (urand(0, 1))
                 {
                     me->Yell("I... I think I broke it.", LANG_UNIVERSAL);
                     me->PlayDirectSound(XT_SOUND_SLAY1);
                 }
                 else
                 {
                     me->Yell("I guess it doesn't bend that way.", LANG_UNIVERSAL);
                     me->PlayDirectSound(XT_SOUND_SLAY2);
                 }
             }
         }
References Object::GetTypeId(), LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), TYPEID_PLAYER, urand(), XT_SOUND_SLAY1, XT_SOUND_SLAY2, and Unit::Yell().
RescheduleEvents()
void boss_xt002::boss_xt002AI::RescheduleEvents () inline
Definition at line 146 of file boss_xt002.cpp.
         {
             events.RescheduleEvent(EVENT_GRAVITY_BOMB, 1000, 1);
             events.RescheduleEvent(EVENT_TYMPANIC_TANTARUM, 60000, 1);
             if (!_hardMode)
                 events.RescheduleEvent(EVENT_HEALTH_CHECK, 2000, 1);
         }
References _hardMode, EVENT_GRAVITY_BOMB, EVENT_HEALTH_CHECK, and EVENT_TYMPANIC_TANTARUM.
Referenced by EnterCombat(), and UpdateAI().
Reset()
void boss_xt002::boss_xt002AI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 154 of file boss_xt002.cpp.
         {
             summons.DespawnAll();
             events.Reset();
             me->ResetLootMode();
             me->RemoveAllAuras();
             // first heart expose
             _healthCheck = 75;
             _hardMode = false;
             _nerfAchievement = true;
             _gravityAchievement = true;
             me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
             me->SetControlled(false, UNIT_STATE_STUNNED);
             if (m_pInstance)
             {
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER);
                 m_pInstance->SetData(TYPE_XT002, NOT_STARTED);
                 if (GameObject* pGo = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_XT002_DOORS)))
                     pGo->SetGoState(GO_STATE_ACTIVE);
             }
         }
References _gravityAchievement, _hardMode, _healthCheck, _nerfAchievement, ACHIEVEMENT_MUST_DECONSTRUCT_FASTER, ACHIEVEMENT_TIMED_TYPE_EVENT, SummonList::DespawnAll(), InstanceScript::DoStopTimedAchievement(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, GO_XT002_DOORS, m_pInstance, ScriptedAI::me, NOT_STARTED, Unit::RemoveAllAuras(), Object::RemoveFlag(), Creature::ResetLootMode(), Object::SetByteValue(), Unit::SetControlled(), ZoneScript::SetData(), summons, TYPE_XT002, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, and UNIT_STATE_STUNNED.
SummonedCreatureDespawn()
void boss_xt002::boss_xt002AI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 182 of file boss_xt002.cpp.
 { summons.Despawn(cr); }
References SummonList::Despawn(), and summons.
UpdateAI()
void boss_xt002::boss_xt002AI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 308 of file boss_xt002.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 // Control events
                 case EVENT_HEALTH_CHECK:
                     if (_hardMode)
                     {
                         return;
                     }
                     if (me->HealthBelowPct(_healthCheck))
                     {
                         _healthCheck -= 25;
                         me->SetControlled(true, UNIT_STATE_STUNNED);
                         me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_SUBMERGED); // submerge with animation
                         me->Yell("So tired. I will rest for just a moment!", LANG_UNIVERSAL);
                         me->PlayDirectSound(XT_SOUND_HEART_OPEN);
                         events.CancelEventGroup(1);
                         events.ScheduleEvent(EVENT_START_SECOND_PHASE, 5000);
                         return;
                     }
                     events.RepeatEvent(1000);
                     break;
                 case EVENT_CHECK_ROOM:
                     events.RepeatEvent(5000);
                     if (me->GetPositionX() < 722 || me->GetPositionX() > 987 || me->GetPositionY() < -139 || me->GetPositionY() > 124)
                         EnterEvadeMode();
                     return;
                 // Abilities events
                 case EVENT_GRAVITY_BOMB:
                     me->CastCustomSpell(SPELL_GRAVITY_BOMB, SPELLVALUE_MAX_TARGETS, 1, me, true);
                     events.ScheduleEvent(EVENT_SEARING_LIGHT, 10000, 1);
                     break;
                 case EVENT_SEARING_LIGHT:
                     me->CastCustomSpell(SPELL_SEARING_LIGHT, SPELLVALUE_MAX_TARGETS, 1, me, true);
                     events.ScheduleEvent(EVENT_GRAVITY_BOMB, 10000, 1);
                     break;
                 case EVENT_TYMPANIC_TANTARUM:
                     me->TextEmote("XT-002 Deconstructor begins to cause the earth to quake.", nullptr, true);
                     me->Yell("NO! NO! NO! NO! NO!", LANG_UNIVERSAL);
                     me->PlayDirectSound(XT_SOUND_TANTARUM);
                     me->CastSpell(me, SPELL_TYMPANIC_TANTARUM, true);
                     events.RepeatEvent(60000);
                     return;
                 case EVENT_ENRAGE:
                     me->Yell("I'm tired of these toys. I don't want to play anymore!", LANG_UNIVERSAL);
                     me->PlayDirectSound(XT_SOUND_ENRAGE);
                     me->CastSpell(me, SPELL_XT002_ENRAGE, true);
                     break;
                 // Animation events
                 case EVENT_START_SECOND_PHASE:
                     me->TextEmote("XT-002 Deconstructor's heart is exposed and leaking energy.", nullptr, true);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                     if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                         heart->GetAI()->DoAction(ACTION_AWAKEN_HEART);
                     events.ScheduleEvent(EVENT_RESTORE, 30000);
                     return;
                 // Restore from heartbreak
                 case EVENT_RESTORE:
                     if (_hardMode)
                     {
                         return;
                     }
                     me->Yell("I'm ready to play!", LANG_UNIVERSAL);
                     me->PlayDirectSound(XT_SOUND_HEART_CLOSED);
                     me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND); // emerge
                     // Hide heart
                     if (Unit* heart = me->GetVehicleKit() ? me->GetVehicleKit()->GetPassenger(HEART_VEHICLE_SEAT) : nullptr)
                         heart->GetAI()->DoAction(ACTION_HIDE_HEART);
                     events.ScheduleEvent(EVENT_REMOVE_EMOTE, 4000);
                     return;
                 case EVENT_REMOVE_EMOTE:
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                     me->SetControlled(false, UNIT_STATE_STUNNED);
                     RescheduleEvents();
                     return;
             }
             // Disabled by stunned state
             DoMeleeAttackIfReady();
         }
References _hardMode, _healthCheck, ACTION_AWAKEN_HEART, ACTION_HIDE_HEART, Unit::CastCustomSpell(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_ROOM, EVENT_ENRAGE, EVENT_GRAVITY_BOMB, EVENT_HEALTH_CHECK, EVENT_REMOVE_EMOTE, EVENT_RESTORE, EVENT_SEARING_LIGHT, EVENT_START_SECOND_PHASE, EVENT_TYMPANIC_TANTARUM, Vehicle::GetPassenger(), Position::GetPositionX(), Position::GetPositionY(), Unit::GetVehicleKit(), Unit::HasUnitState(), Unit::HealthBelowPct(), HEART_VEHICLE_SEAT, LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), Object::RemoveFlag(), RescheduleEvents(), Object::SetByteValue(), Unit::SetControlled(), Object::SetFlag(), SPELL_GRAVITY_BOMB, SPELL_SEARING_LIGHT, SPELL_TYMPANIC_TANTARUM, SPELL_XT002_ENRAGE, SPELLVALUE_MAX_TARGETS, Unit::TextEmote(), UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, UNIT_STAND_STATE_SUBMERGED, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, CreatureAI::UpdateVictim(), XT_SOUND_ENRAGE, XT_SOUND_HEART_CLOSED, XT_SOUND_HEART_OPEN, XT_SOUND_TANTARUM, and Unit::Yell().
Member Data Documentation
_gravityAchievement
bool boss_xt002::boss_xt002AI::_gravityAchievement
Definition at line 142 of file boss_xt002.cpp.
Referenced by DoAction(), GetData(), and Reset().
_hardMode
bool boss_xt002::boss_xt002AI::_hardMode
Definition at line 140 of file boss_xt002.cpp.
Referenced by DoAction(), RescheduleEvents(), Reset(), and UpdateAI().
_healthCheck
uint8 boss_xt002::boss_xt002AI::_healthCheck
Definition at line 139 of file boss_xt002.cpp.
Referenced by Reset(), and UpdateAI().
_nerfAchievement
bool boss_xt002::boss_xt002AI::_nerfAchievement
Definition at line 141 of file boss_xt002.cpp.
Referenced by DoAction(), GetData(), and Reset().
events
EventMap boss_xt002::boss_xt002AI::events
Definition at line 143 of file boss_xt002.cpp.
m_pInstance
InstanceScript* boss_xt002::boss_xt002AI::m_pInstance
Definition at line 138 of file boss_xt002.cpp.
Referenced by boss_xt002AI(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_xt002::boss_xt002AI::summons
Definition at line 144 of file boss_xt002.cpp.
Referenced by JustDied(), JustSummoned(), Reset(), and SummonedCreatureDespawn().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp