Azerotcore-wotlk: deps/mysqllite/mysys/my_rename.c File Reference
my_rename.c File Reference
#include "mysys_priv.h"
#include <my_dir.h>
#include "mysys_err.h"
#include "m_string.h"
Functions
int my_rename (const char *from, const char *to, myf MyFlags)
Function Documentation
my_rename()
int my_rename (const char * from, const char * to, myf MyFlags)
Definition at line 24 of file my_rename.c.
 {
   int error = 0;
   DBUG_ENTER("my_rename");
   DBUG_PRINT("my",("from %s to %s MyFlags %d", from, to, MyFlags));
 #if defined(HAVE_FILE_VERSIONS)
   {             /* Check that there isn't a old file */
     int save_errno;
     MY_STAT my_stat_result;
     save_errno=my_errno;
     if (my_stat(to,&my_stat_result,MYF(0)))
     {
       my_errno=EEXIST;
       error= -1;
       if (MyFlags & MY_FAE+MY_WME)
     my_error(EE_LINK, MYF(ME_BELL+ME_WAITTANG),from,to,my_errno);
       DBUG_RETURN(error);
     }
     my_errno=save_errno;
   }
 #endif
 #if defined(HAVE_RENAME)
 #if defined(__WIN__)
   /*
     On windows we can't rename over an existing file:
     Remove any conflicting files:
   */
   (void) my_delete(to, MYF(0));
 #endif
   if (rename(from,to))
 #else
   if (link(from, to) || unlink(from))
 #endif
   {
     my_errno=errno;
     error = -1;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_LINK, MYF(ME_BELL+ME_WAITTANG),from,to,my_errno);
   }
   else if (MyFlags & MY_SYNC_DIR)
   {
 #ifdef NEED_EXPLICIT_SYNC_DIR
     /* do only the needed amount of syncs: */
     char dir_from[FN_REFLEN], dir_to[FN_REFLEN];
     size_t dir_from_length, dir_to_length;
     dirname_part(dir_from, from, &dir_from_length);
     dirname_part(dir_to, to, &dir_to_length);
     if (my_sync_dir(dir_from, MyFlags) ||
         (strcmp(dir_from, dir_to) &&
          my_sync_dir(dir_to, MyFlags)))
       error= -1;
 #endif
   }
   DBUG_RETURN(error);
 } /* my_rename */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), EE_LINK, endif(), errno, error(), FN_REFLEN, ME_BELL, ME_WAITTANG, my_delete(), my_errno, my_error(), MY_FAE, MY_STAT, my_stat(), MY_SYNC_DIR, my_sync_dir(), MY_WME, and MYF.
Referenced by inline_mysql_file_rename(), my_redel(), and my_rename_with_symlink().