Azerotcore-wotlk: boss_twinemperorsAI Struct Reference
boss_twinemperorsAI Struct Reference abstract
Public Member Functions
boss_twinemperorsAI (Creature *creature)
virtual bool IAmVeklor ()=0
void Reset () override=0
virtual void CastSpellOnBug (Creature *target)=0
void TwinReset ()
Creature * GetOtherBoss ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterCombat (Unit *who) override
void SpellHit (Unit *caster, const SpellInfo *entry) override
void TryHealBrother (uint32 diff)
void TeleportToMyBrother ()
void SetAfterTeleport ()
bool TryActivateAfterTTelep (uint32 diff)
void MoveInLineOfSight (Unit *who) override
Creature * RespawnNearbyBugsAndGetOne ()
void HandleBugs (uint32 diff)
void CheckEnrage (uint32 diff)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 Heal_Timer
uint32 Teleport_Timer
bool AfterTeleport
uint32 AfterTeleportTimer
bool DontYellWhenDead
uint32 Abuse_Bug_Timer
uint32 BugsTimer
bool tspellcast
uint32 EnrageTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 65 of file boss_twinemperors.cpp.
Constructor & Destructor Documentation
boss_twinemperorsAI()
boss_twinemperorsAI::boss_twinemperorsAI (Creature * creature) inline
Definition at line 67 of file boss_twinemperors.cpp.
                                            : ScriptedAI(creature)
     {
         instance = creature->GetInstanceScript();
     }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
CastSpellOnBug()
virtual void boss_twinemperorsAI::CastSpellOnBug (Creature * target) pure virtual
Implemented in boss_veklor::boss_veklorAI, and boss_veknilash::boss_veknilashAI.
Referenced by HandleBugs().
CheckEnrage()
void boss_twinemperorsAI::CheckEnrage (uint32 diff) inline
Definition at line 365 of file boss_twinemperors.cpp.
     {
         if (EnrageTimer <= diff)
         {
             if (!me->IsNonMeleeSpellCast(true))
             {
                 DoCast(me, SPELL_BERSERK);
                 EnrageTimer = 60 * 60000;
             }
             else EnrageTimer = 0;
         }
         else EnrageTimer -= diff;
     }
References diff(), UnitAI::DoCast(), EnrageTimer, Unit::IsNonMeleeSpellCast(), ScriptedAI::me, and SPELL_BERSERK.
Referenced by boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
DamageTaken()
void boss_twinemperorsAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 106 of file boss_twinemperors.cpp.
     {
         Unit* pOtherBoss = GetOtherBoss();
         if (pOtherBoss)
         {
             float dPercent = ((float)damage) / ((float)me->GetMaxHealth());
             int odmg = (int)(dPercent * ((float)pOtherBoss->GetMaxHealth()));
             int ohealth = pOtherBoss->GetHealth() - odmg;
             pOtherBoss->SetHealth(ohealth > 0 ? ohealth : 0);
             if (ohealth <= 0)
             {
                 pOtherBoss->setDeathState(JUST_DIED);
                 pOtherBoss->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
             }
         }
     }
References Unit::GetHealth(), Unit::GetMaxHealth(), GetOtherBoss(), JUST_DIED, ScriptedAI::me, Unit::setDeathState(), Object::SetFlag(), Unit::SetHealth(), UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_LOOTABLE.
EnterCombat()
void boss_twinemperorsAI::EnterCombat (Unit * who) inline override virtual
Todo:
we should activate the other boss location so he can start attackning even if nobody
Reimplemented from ScriptedAI.
Definition at line 142 of file boss_twinemperors.cpp.
     {
         DoZoneInCombat();
         Creature* pOtherBoss = GetOtherBoss();
         if (pOtherBoss)
         {
             // is near I dont know how to do that
             ScriptedAI* otherAI = CAST_AI(ScriptedAI, pOtherBoss->AI());
             if (!pOtherBoss->IsInCombat())
             {
                 DoPlaySoundToSet(me, IAmVeklor() ? SOUND_VL_AGGRO : SOUND_VN_AGGRO);
                 otherAI->AttackStart(who);
                 otherAI->DoZoneInCombat();
             }
         }
     }
References Creature::AI(), ScriptedAI::AttackStart(), CAST_AI, ScriptedAI::DoPlaySoundToSet(), CreatureAI::DoZoneInCombat(), GetOtherBoss(), IAmVeklor(), Unit::IsInCombat(), ScriptedAI::me, SOUND_VL_AGGRO, and SOUND_VN_AGGRO.
GetOtherBoss()
Creature* boss_twinemperorsAI::GetOtherBoss () inline
Definition at line 101 of file boss_twinemperors.cpp.
     {
         return ObjectAccessor::GetCreature(*me, instance->GetGuidData(IAmVeklor() ? DATA_VEKNILASH : DATA_VEKLOR));
     }
References DATA_VEKLOR, DATA_VEKNILASH, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), IAmVeklor(), instance, and ScriptedAI::me.
Referenced by DamageTaken(), EnterCombat(), JustDied(), SpellHit(), TeleportToMyBrother(), and TryHealBrother().
HandleBugs()
void boss_twinemperorsAI::HandleBugs (uint32 diff) inline
Definition at line 335 of file boss_twinemperors.cpp.
     {
         if (BugsTimer < diff || Abuse_Bug_Timer <= diff)
         {
             Creature* c = RespawnNearbyBugsAndGetOne();
             if (Abuse_Bug_Timer <= diff)
             {
                 if (c)
                 {
                     CastSpellOnBug(c);
                     Abuse_Bug_Timer = urand(10000, 17000);
                 }
                 else
                 {
                     Abuse_Bug_Timer = 1000;
                 }
             }
             else
             {
                 Abuse_Bug_Timer -= diff;
             }
             BugsTimer = 2000;
         }
         else
         {
             BugsTimer -= diff;
             Abuse_Bug_Timer -= diff;
         }
     }
References Abuse_Bug_Timer, BugsTimer, mpq::c, CastSpellOnBug(), diff(), RespawnNearbyBugsAndGetOne(), and urand().
Referenced by boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
IAmVeklor()
virtual bool boss_twinemperorsAI::IAmVeklor () pure virtual
Implemented in boss_veklor::boss_veklorAI, and boss_veknilash::boss_veknilashAI.
Referenced by EnterCombat(), GetOtherBoss(), JustDied(), KilledUnit(), TeleportToMyBrother(), and TryHealBrother().
JustDied()
void boss_twinemperorsAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 123 of file boss_twinemperors.cpp.
     {
         Creature* pOtherBoss = GetOtherBoss();
         if (pOtherBoss)
         {
             pOtherBoss->SetHealth(0);
             pOtherBoss->setDeathState(JUST_DIED);
             pOtherBoss->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
             CAST_AI(boss_twinemperorsAI, pOtherBoss->AI())->DontYellWhenDead = true;
         }
         if (!DontYellWhenDead)                              // I hope AI is not threaded
             DoPlaySoundToSet(me, IAmVeklor() ? SOUND_VL_DEATH : SOUND_VN_DEATH);
     }
References Creature::AI(), CAST_AI, DontYellWhenDead, ScriptedAI::DoPlaySoundToSet(), GetOtherBoss(), IAmVeklor(), JUST_DIED, ScriptedAI::me, Creature::setDeathState(), Object::SetFlag(), Unit::SetHealth(), SOUND_VL_DEATH, SOUND_VN_DEATH, UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_LOOTABLE.
KilledUnit()
void boss_twinemperorsAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 137 of file boss_twinemperors.cpp.
     {
         DoPlaySoundToSet(me, IAmVeklor() ? SOUND_VL_KILL : SOUND_VN_KILL);
     }
References ScriptedAI::DoPlaySoundToSet(), IAmVeklor(), ScriptedAI::me, SOUND_VL_KILL, and SOUND_VN_KILL.
MoveInLineOfSight()
void boss_twinemperorsAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 287 of file boss_twinemperors.cpp.
     {
         if (!who || me->GetVictim())
             return;
         if (me->_CanDetectFeignDeathOf(who) && me->CanCreatureAttack(who))
         {
             if (me->IsWithinDistInMap(who, PULL_RANGE, true, false) && me->GetDistanceZ(who) <= /*CREATURE_Z_ATTACK_RANGE*/7 /*there are stairs*/)
             {
                 //if (who->HasStealthAura())
                 //    who->RemoveSpellsCausingAura(SPELL_AURA_MOD_STEALTH);
                 AttackStart(who);
             }
         }
     }
References Creature::_CanDetectFeignDeathOf(), ScriptedAI::AttackStart(), Creature::CanCreatureAttack(), WorldObject::GetDistanceZ(), Unit::GetVictim(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, and PULL_RANGE.
Reset()
void boss_twinemperorsAI::Reset () override pure virtual
Reimplemented from ScriptedAI.
Implemented in boss_veklor::boss_veklorAI, and boss_veknilash::boss_veknilashAI.
RespawnNearbyBugsAndGetOne()
Creature* boss_twinemperorsAI::RespawnNearbyBugsAndGetOne () inline
Definition at line 303 of file boss_twinemperors.cpp.
     {
         std::list<Creature*> lUnitList;
         me->GetCreatureListWithEntryInGrid(lUnitList, 15316, 150.0f);
         me->GetCreatureListWithEntryInGrid(lUnitList, 15317, 150.0f);
         if (lUnitList.empty())
             return nullptr;
         Creature* nearb = nullptr;
         for (std::list<Creature*>::const_iterator iter = lUnitList.begin(); iter != lUnitList.end(); ++iter)
         {
             Creature* c = *iter;
             if (c)
             {
                 if (c->isDead())
                 {
                     c->Respawn();
                     c->SetFaction(FACTION_CREATURE);
                     c->RemoveAllAuras();
                 }
                 if (c->IsWithinDistInMap(me, ABUSE_BUG_RANGE))
                 {
                     if (!nearb || (rand() % 4) == 0)
                         nearb = c;
                 }
             }
         }
         return nearb;
     }
References ABUSE_BUG_RANGE, mpq::c, FACTION_CREATURE, WorldObject::GetCreatureListWithEntryInGrid(), and ScriptedAI::me.
Referenced by HandleBugs().
SetAfterTeleport()
void boss_twinemperorsAI::SetAfterTeleport () inline
Definition at line 229 of file boss_twinemperors.cpp.
     {
         me->InterruptNonMeleeSpells(false);
         DoStopAttack();
         DoResetThreat();
         DoCast(me, SPELL_TWIN_TELEPORT_VISUAL);
         me->AddUnitState(UNIT_STATE_STUNNED);
         AfterTeleport = true;
         AfterTeleportTimer = 2000;
         tspellcast = false;
     }
References Unit::AddUnitState(), AfterTeleport, AfterTeleportTimer, UnitAI::DoCast(), ScriptedAI::DoResetThreat(), ScriptedAI::DoStopAttack(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, SPELL_TWIN_TELEPORT_VISUAL, tspellcast, and UNIT_STATE_STUNNED.
Referenced by TeleportToMyBrother().
SpellHit()
void boss_twinemperorsAI::SpellHit (Unit * caster, const SpellInfo * entry) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 160 of file boss_twinemperors.cpp.
     {
         if (caster == me)
             return;
         Creature* pOtherBoss = GetOtherBoss();
         if (entry->Id != SPELL_HEAL_BROTHER || !pOtherBoss)
             return;
         // add health so we keep same percentage for both brothers
         uint32 mytotal = me->GetMaxHealth(), histotal = pOtherBoss->GetMaxHealth();
         float mult = ((float)mytotal) / ((float)histotal);
         if (mult < 1)
             mult = 1.0f / mult;
 #define HEAL_BROTHER_AMOUNT 30000.0f
         uint32 largerAmount = (uint32)((HEAL_BROTHER_AMOUNT * mult) - HEAL_BROTHER_AMOUNT);
         if (mytotal > histotal)
         {
             uint32 h = me->GetHealth() + largerAmount;
             me->SetHealth(std::min(mytotal, h));
         }
         else
         {
             uint32 h = pOtherBoss->GetHealth() + largerAmount;
             pOtherBoss->SetHealth(std::min(histotal, h));
         }
     }
References Unit::GetHealth(), Unit::GetMaxHealth(), GetOtherBoss(), HEAL_BROTHER_AMOUNT, SpellInfo::Id, ScriptedAI::me, min, mult(), Unit::SetHealth(), and SPELL_HEAL_BROTHER.
TeleportToMyBrother()
void boss_twinemperorsAI::TeleportToMyBrother () inline
Definition at line 206 of file boss_twinemperors.cpp.
     {
         Teleport_Timer = TELEPORTTIME;
         if (IAmVeklor())
             return;                                         // mechanics handled by veknilash so they teleport exactly at the same time and to correct coordinates
         Creature* pOtherBoss = GetOtherBoss();
         if (pOtherBoss)
         {
             //me->Yell("Teleporting ...", LANG_UNIVERSAL);
             Position thisPos;
             thisPos.Relocate(me);
             Position otherPos;
             otherPos.Relocate(pOtherBoss);
             pOtherBoss->SetPosition(thisPos);
             me->SetPosition(otherPos);
             SetAfterTeleport();
             CAST_AI(boss_twinemperorsAI,  pOtherBoss->AI())->SetAfterTeleport();
         }
     }
References Creature::AI(), CAST_AI, GetOtherBoss(), IAmVeklor(), ScriptedAI::me, Position::Relocate(), SetAfterTeleport(), Creature::SetPosition(), Teleport_Timer, and TELEPORTTIME.
Referenced by boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
TryActivateAfterTTelep()
bool boss_twinemperorsAI::TryActivateAfterTTelep (uint32 diff) inline
Definition at line 241 of file boss_twinemperors.cpp.
     {
         if (AfterTeleport)
         {
             if (!tspellcast)
             {
                 me->ClearUnitState(UNIT_STATE_STUNNED);
                 DoCast(me, SPELL_TWIN_TELEPORT);
                 me->AddUnitState(UNIT_STATE_STUNNED);
             }
             tspellcast = true;
             if (AfterTeleportTimer <= diff)
             {
                 AfterTeleport = false;
                 me->ClearUnitState(UNIT_STATE_STUNNED);
                 if (Unit* nearu = me->SelectNearestTarget(100))
                 {
                     //DoYell(nearu->GetName(), LANG_UNIVERSAL);
                     AttackStart(nearu);
                     me->AddThreat(nearu, 10000);
                 }
                 return true;
             }
             else
             {
                 AfterTeleportTimer -= diff;
                 // update important timers which would otherwise get skipped
                 if (EnrageTimer > diff)
                     EnrageTimer -= diff;
                 else
                     EnrageTimer = 0;
                 if (Teleport_Timer > diff)
                     Teleport_Timer -= diff;
                 else
                     Teleport_Timer = 0;
                 return false;
             }
         }
         else
         {
             return true;
         }
     }
References Unit::AddThreat(), Unit::AddUnitState(), AfterTeleport, AfterTeleportTimer, ScriptedAI::AttackStart(), Unit::ClearUnitState(), diff(), UnitAI::DoCast(), EnrageTimer, ScriptedAI::me, Creature::SelectNearestTarget(), SPELL_TWIN_TELEPORT, Teleport_Timer, tspellcast, and UNIT_STATE_STUNNED.
Referenced by boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
TryHealBrother()
void boss_twinemperorsAI::TryHealBrother (uint32 diff) inline
Definition at line 189 of file boss_twinemperors.cpp.
     {
         if (IAmVeklor())                                    // this spell heals caster and the other brother so let VN cast it
             return;
         if (Heal_Timer <= diff)
         {
             Unit* pOtherBoss = GetOtherBoss();
             if (pOtherBoss && pOtherBoss->IsWithinDist(me, 60))
             {
                 DoCast(pOtherBoss, SPELL_HEAL_BROTHER);
                 Heal_Timer = 1000;
             }
         }
         else Heal_Timer -= diff;
     }
References diff(), UnitAI::DoCast(), GetOtherBoss(), Heal_Timer, IAmVeklor(), WorldObject::IsWithinDist(), ScriptedAI::me, and SPELL_HEAL_BROTHER.
Referenced by boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
TwinReset()
void boss_twinemperorsAI::TwinReset () inline
Definition at line 87 of file boss_twinemperors.cpp.
     {
         Heal_Timer = 0;                                     // first heal immediately when they get close together
         Teleport_Timer = TELEPORTTIME;
         AfterTeleport = false;
         tspellcast = false;
         AfterTeleportTimer = 0;
         Abuse_Bug_Timer = urand(10000, 17000);
         BugsTimer = 2000;
         me->ClearUnitState(UNIT_STATE_STUNNED);
         DontYellWhenDead = false;
         EnrageTimer = 15 * 60000;
     }
References Abuse_Bug_Timer, AfterTeleport, AfterTeleportTimer, BugsTimer, Unit::ClearUnitState(), DontYellWhenDead, EnrageTimer, Heal_Timer, ScriptedAI::me, Teleport_Timer, TELEPORTTIME, tspellcast, UNIT_STATE_STUNNED, and urand().
Referenced by boss_veknilash::boss_veknilashAI::Reset(), and boss_veklor::boss_veklorAI::Reset().
Member Data Documentation
Abuse_Bug_Timer
uint32 boss_twinemperorsAI::Abuse_Bug_Timer
Definition at line 79 of file boss_twinemperors.cpp.
Referenced by HandleBugs(), and TwinReset().
AfterTeleport
bool boss_twinemperorsAI::AfterTeleport
Definition at line 76 of file boss_twinemperors.cpp.
Referenced by SetAfterTeleport(), TryActivateAfterTTelep(), TwinReset(), and boss_veklor::boss_veklorAI::UpdateAI().
AfterTeleportTimer
uint32 boss_twinemperorsAI::AfterTeleportTimer
Definition at line 77 of file boss_twinemperors.cpp.
Referenced by SetAfterTeleport(), TryActivateAfterTTelep(), and TwinReset().
BugsTimer
uint32 boss_twinemperorsAI::BugsTimer
Definition at line 79 of file boss_twinemperors.cpp.
Referenced by HandleBugs(), and TwinReset().
DontYellWhenDead
bool boss_twinemperorsAI::DontYellWhenDead
Definition at line 78 of file boss_twinemperors.cpp.
Referenced by JustDied(), and TwinReset().
EnrageTimer
uint32 boss_twinemperorsAI::EnrageTimer
Definition at line 81 of file boss_twinemperors.cpp.
Referenced by CheckEnrage(), TryActivateAfterTTelep(), and TwinReset().
Heal_Timer
uint32 boss_twinemperorsAI::Heal_Timer
Definition at line 74 of file boss_twinemperors.cpp.
Referenced by TryHealBrother(), and TwinReset().
instance
InstanceScript* boss_twinemperorsAI::instance
Definition at line 72 of file boss_twinemperors.cpp.
Referenced by boss_twinemperorsAI(), and GetOtherBoss().
Teleport_Timer
uint32 boss_twinemperorsAI::Teleport_Timer
Definition at line 75 of file boss_twinemperors.cpp.
Referenced by TeleportToMyBrother(), TryActivateAfterTTelep(), TwinReset(), boss_veknilash::boss_veknilashAI::UpdateAI(), and boss_veklor::boss_veklorAI::UpdateAI().
tspellcast
bool boss_twinemperorsAI::tspellcast
Definition at line 80 of file boss_twinemperors.cpp.
Referenced by SetAfterTeleport(), TryActivateAfterTTelep(), and TwinReset().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp