Azerotcore-wotlk: TransportAnimation Struct Reference
TransportAnimation Struct Reference
#include <TransportMgr.h>
Public Member Functions
TransportAnimation ()
bool GetAnimNode (uint32 time, TransportAnimationEntry const *&curr, TransportAnimationEntry const *&next, float &percPos) const
void GetAnimRotation (uint32 time, G3D::Quat &curr, G3D::Quat &next, float &percRot) const
Public Attributes
TransportPathContainer Path
TransportPathRotationContainer Rotations
uint32 TotalTime
Detailed Description
Definition at line 86 of file TransportMgr.h.
Constructor & Destructor Documentation
TransportAnimation()
TransportAnimation::TransportAnimation () inline
Definition at line 88 of file TransportMgr.h.
 : TotalTime(0) { }
Member Function Documentation
GetAnimNode()
bool TransportAnimation::GetAnimNode (uint32 time, TransportAnimationEntry const *& curr, TransportAnimationEntry const *& next, float & percPos) const
Definition at line 494 of file TransportMgr.cpp.
 {
     if (Path.empty())
         return false;
     for (TransportPathContainer::const_reverse_iterator itr = Path.rbegin(); itr != Path.rend(); ++itr)
         if (time >= itr->first)
         {
             curr = itr->second;
             ASSERT(itr != Path.rbegin());
             --itr;
             next = itr->second;
             percPos = float(time - curr->TimeSeg) / float(next->TimeSeg - curr->TimeSeg);
             return true;
         }
     return false;
 }
References ASSERT, next(), Path, and TransportAnimationEntry::TimeSeg.
Referenced by StaticTransport::RelocateToProgress().
GetAnimRotation()
void TransportAnimation::GetAnimRotation (uint32 time, G3D::Quat & curr, G3D::Quat & next, float & percRot) const
Definition at line 513 of file TransportMgr.cpp.
 {
     if (Rotations.empty())
     {
         curr = G3D::Quat(0.0f, 0.0f, 0.0f, 1.0f);
         next = G3D::Quat(0.0f, 0.0f, 0.0f, 1.0f);
         percRot = 0.0f;
         return;
     }
     for (TransportPathRotationContainer::const_reverse_iterator itr = Rotations.rbegin(); itr != Rotations.rend(); ++itr)
         if (time >= itr->first)
         {
             uint32 currSeg = itr->second->TimeSeg, nextSeg;
             curr = G3D::Quat(itr->second->X, itr->second->Y, itr->second->Z, itr->second->W);
             if (itr != Rotations.rbegin())
             {
                 --itr;
                 next = G3D::Quat(itr->second->X, itr->second->Y, itr->second->Z, itr->second->W);
                 nextSeg = itr->second->TimeSeg;
             }
             else
             {
                 next = G3D::Quat(Rotations.begin()->second->X, Rotations.begin()->second->Y, Rotations.begin()->second->Z, Rotations.begin()->second->W);
                 nextSeg = this->TotalTime;
             }
             percRot = float(time - currSeg) / float(nextSeg - currSeg);
             return;
         }
     curr = G3D::Quat(0.0f, 0.0f, 0.0f, 1.0f);
     next = G3D::Quat(0.0f, 0.0f, 0.0f, 1.0f);
     percRot = 0.0f;
 }
References next(), Rotations, and TotalTime.
Referenced by StaticTransport::RelocateToProgress().
Member Data Documentation
Path
TransportPathContainer TransportAnimation::Path
Definition at line 90 of file TransportMgr.h.
Referenced by TransportMgr::AddPathNodeToTransport(), and GetAnimNode().
Rotations
TransportPathRotationContainer TransportAnimation::Rotations
Definition at line 91 of file TransportMgr.h.
Referenced by GetAnimRotation().
TotalTime
uint32 TransportAnimation::TotalTime
Definition at line 92 of file TransportMgr.h.
Referenced by TransportMgr::AddPathNodeToTransport(), StaticTransport::Create(), GetAnimRotation(), and StaticTransport::GetPeriod().
The documentation for this struct was generated from the following files:
src/server/game/Maps/TransportMgr.h
src/server/game/Maps/TransportMgr.cpp