Azerotcore-wotlk: G3D::SmallArray< T, N > Class Template Reference
G3D::SmallArray< T, N > Class Template Reference
#include <SmallArray.h>
Public Member Functions
SmallArray ()
int size () const
void resize (int n, bool shrinkIfNecessary=true)
void clear (bool shrinkIfNecessary=true)
void clearAndSetMemoryManager (MemoryManager::Ref &m)
T & operator[] (int i)
const T & operator[] (int i) const
void push (const T &v)
void append (const T &v)
void append (const T &v, const T &v2)
void append (const T &v, const T &v2, const T &v3)
void append (const T &v, const T &v2, const T &v3, const T &v4)
int findIndex (const T &v)
void fastRemove (int i, bool shrinkIfNecessary=false)
T pop ()
void popDiscard ()
T & next ()
bool contains (const T &value) const
template<int MIN_ELEMENTS>
SmallArray< T, N > & operator= (const Array< T, MIN_ELEMENTS > &src)
const T & last () const
T & last ()
Private Attributes
int m_size
T m_embedded [N]
Array< T > m_rest
Detailed Description
template<class T, int N>
class G3D::SmallArray< T, N >
Embeds N elements to reduce allocation time and increase memory coherence when working with arrays of arrays. Offers a limited subset of the functionality of G3D::Array.
Definition at line 23 of file SmallArray.h.
Constructor & Destructor Documentation
SmallArray()
template<class T , int N> G3D::SmallArray< T, N >::SmallArray () inline
Definition at line 35 of file SmallArray.h.
 : m_size(0) {}
Member Function Documentation
append() [1/4]
template<class T , int N> void G3D::SmallArray< T, N >::append (const T & v) inline
Definition at line 82 of file SmallArray.h.
{
         push(v);
     }
References G3D::SmallArray< T, N >::push().
append() [2/4]
template<class T , int N> void G3D::SmallArray< T, N >::append (const T & v, const T & v2) inline
Definition at line 86 of file SmallArray.h.
{
         push(v);
         push(v2);
     }
References G3D::SmallArray< T, N >::push().
append() [3/4]
template<class T , int N> void G3D::SmallArray< T, N >::append (const T & v, const T & v2, const T & v3) inline
Definition at line 91 of file SmallArray.h.
{
         push(v);
         push(v2);
         push(v3);
     }
References G3D::SmallArray< T, N >::push().
append() [4/4]
template<class T , int N> void G3D::SmallArray< T, N >::append (const T & v, const T & v2, const T & v3, const T & v4) inline
Definition at line 97 of file SmallArray.h.
{
         push(v);
         push(v2);
         push(v3);
         push(v4);
     }
References G3D::SmallArray< T, N >::push().
clear()
template<class T , int N> void G3D::SmallArray< T, N >::clear (bool shrinkIfNecessary = true) inline
Definition at line 46 of file SmallArray.h.
{
         resize(0, shrinkIfNecessary);
     }
References G3D::SmallArray< T, N >::resize().
Referenced by G3D::SmallArray< T, N >::clearAndSetMemoryManager().
clearAndSetMemoryManager()
template<class T , int N> void G3D::SmallArray< T, N >::clearAndSetMemoryManager (MemoryManager::Ref & m) inline
Definition at line 50 of file SmallArray.h.
{
         clear();
         m_rest.clearAndSetMemoryManager(m);
     }
References G3D::SmallArray< T, N >::clear(), and G3D::SmallArray< T, N >::m_rest.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert().
contains()
template<class T , int N> bool G3D::SmallArray< T, N >::contains (const T & value) const inline
Definition at line 162 of file SmallArray.h.
{
         for (int i = std::min(m_size, N) - 1; i >= 0; --i) {
             if (m_embedded[i] == value) {
                 return true;
             }
         }
         return m_rest.contains(value);
     }
References G3D::SmallArray< T, N >::m_embedded, G3D::SmallArray< T, N >::m_rest, G3D::SmallArray< T, N >::m_size, and min.
Referenced by G3D::MeshAlg::Vertex::inEdge(), and G3D::MeshAlg::Vertex::inFace().
fastRemove()
template<class T , int N> void G3D::SmallArray< T, N >::fastRemove (int i, bool shrinkIfNecessary = false) inline
Definition at line 115 of file SmallArray.h.
{
         debugAssert(i < m_size && i >= 0);
         if (i < N) {
             if (m_size <= N) {
                 // Exclusively embedded
                 m_embedded[i] = m_embedded[m_size - 1];
             } else {
                 // Move one down from the rest array
                 m_embedded[i] = m_rest.pop();
             }
         } else {
             // Removing from the rest array
             m_rest.fastRemove(i - N, shrinkIfNecessary);
         }
         --m_size;
     }
References debugAssert, G3D::SmallArray< T, N >::m_embedded, G3D::SmallArray< T, N >::m_rest, and G3D::SmallArray< T, N >::m_size.
Referenced by G3D::MeshAlg::computeAdjacency(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
findIndex()
template<class T , int N> int G3D::SmallArray< T, N >::findIndex (const T & v) inline
Find the index of v or -1 if not found
Definition at line 105 of file SmallArray.h.
{
         for (int i = 0; i < N; ++i) {
             if (m_embedded[i] == v) {
                 return i;
             }
         }
         return m_rest.findIndex(v) + N;
     }
References G3D::SmallArray< T, N >::m_embedded, and G3D::SmallArray< T, N >::m_rest.
last() [1/2]
template<class T , int N> T& G3D::SmallArray< T, N >::last () inline
Definition at line 184 of file SmallArray.h.
                      {
         return (*this)[size() - 1];
     }
References G3D::SmallArray< T, N >::size().
last() [2/2]
template<class T , int N> const T& G3D::SmallArray< T, N >::last () const inline
Definition at line 180 of file SmallArray.h.
{
         return (*this)[size() - 1];
     }
References G3D::SmallArray< T, N >::size().
next()
template<class T , int N> T& G3D::SmallArray< T, N >::next () inline
Definition at line 153 of file SmallArray.h.
                      {
         ++m_size;
         if (m_size <= N) {
             return m_embedded[m_size - 1];
         } else {
             return m_rest.next();
         }
     }
References G3D::SmallArray< T, N >::m_embedded, G3D::SmallArray< T, N >::m_rest, and G3D::SmallArray< T, N >::m_size.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and G3D::MeshEdgeTable::insert().
operator=()
template<class T , int N> template<int MIN_ELEMENTS> SmallArray<T, N>& G3D::SmallArray< T, N >::operator= (const Array< T, MIN_ELEMENTS > & src) inline
Definition at line 172 of file SmallArray.h.
{
         resize(src.size());
         for (int i = 0; i < src.size(); ++i) {
             (*this)[i] = src[i];
         }
         return *this;
     }
References G3D::SmallArray< T, N >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
operator[]() [1/2]
template<class T , int N> T& G3D::SmallArray< T, N >::operator[] (int i) inline
Definition at line 55 of file SmallArray.h.
{
         debugAssert(i < m_size && i >= 0);
         if (i < N) {
             return m_embedded[i];
         } else {
             return m_rest[i - N];
         }
     }
References debugAssert, G3D::SmallArray< T, N >::m_embedded, and G3D::SmallArray< T, N >::m_rest.
operator[]() [2/2]
template<class T , int N> const T& G3D::SmallArray< T, N >::operator[] (int i) const inline
Definition at line 64 of file SmallArray.h.
{
         debugAssert(i < m_size && i >= 0);
         if (i < N) {
             return m_embedded[i];
         } else {
             return m_rest[i - N];
         }
     }
References debugAssert, G3D::SmallArray< T, N >::m_embedded, and G3D::SmallArray< T, N >::m_rest.
pop()
template<class T , int N> T G3D::SmallArray< T, N >::pop () inline
Definition at line 132 of file SmallArray.h.
             {
         debugAssert(m_size > 0);
         if (m_size <= N) {
             // Popping from embedded, don't need a temporary
             --m_size;
             return m_embedded[m_size];
         } else {
             // Popping from rest
             --m_size;
             return m_rest.pop();
         }
     }
References debugAssert, G3D::SmallArray< T, N >::m_embedded, G3D::SmallArray< T, N >::m_rest, and G3D::SmallArray< T, N >::m_size.
Referenced by G3D::MeshAlg::computeAdjacency().
popDiscard()
template<class T , int N> void G3D::SmallArray< T, N >::popDiscard () inline
Definition at line 145 of file SmallArray.h.
{
         debugAssert(m_size > 0);
         if (m_size > N) {
             m_rest.popDiscard();
         }
         --m_size;
     }
References debugAssert, G3D::SmallArray< T, N >::m_rest, and G3D::SmallArray< T, N >::m_size.
push()
template<class T , int N> void G3D::SmallArray< T, N >::push (const T & v) inline
Definition at line 73 of file SmallArray.h.
{
         ++m_size;
         if (m_size <= N) {
             m_embedded[m_size - 1] = v;
         } else {
             m_rest.append(v);
         }
     }
References G3D::SmallArray< T, N >::m_embedded, G3D::SmallArray< T, N >::m_rest, and G3D::SmallArray< T, N >::m_size.
Referenced by G3D::SmallArray< T, N >::append(), and G3D::MeshEdgeTable::insert().
resize()
template<class T , int N> void G3D::SmallArray< T, N >::resize (int n, bool shrinkIfNecessary = true) inline
Definition at line 41 of file SmallArray.h.
{
         m_rest.resize(std::max(0, n - N), shrinkIfNecessary);
         m_size = n;
     }
References G3D::SmallArray< T, N >::m_rest, G3D::SmallArray< T, N >::m_size, and max.
Referenced by G3D::SmallArray< T, N >::clear(), and G3D::SmallArray< T, N >::operator=().
size()
template<class T , int N> int G3D::SmallArray< T, N >::size () const inline
Definition at line 37 of file SmallArray.h.
{
         return m_size;
     }
References G3D::SmallArray< T, N >::m_size.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advanceCell(), G3D::MeshAlg::computeAdjacency(), G3D::MeshAlg::debugCheckConsistency(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::MeshEdgeTable::insert(), G3D::SmallArray< T, N >::last(), G3D::MeshEdgeTable::Iterator::operator++(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove(), and G3D::MeshAlg::weldBoundaryEdges().
Member Data Documentation
m_embedded
template<class T , int N> T G3D::SmallArray< T, N >::m_embedded[N] private
First N elements
Definition at line 28 of file SmallArray.h.
Referenced by G3D::SmallArray< T, N >::contains(), G3D::SmallArray< T, N >::fastRemove(), G3D::SmallArray< T, N >::findIndex(), G3D::SmallArray< T, N >::next(), G3D::SmallArray< T, N >::operator[](), G3D::SmallArray< T, N >::pop(), and G3D::SmallArray< T, N >::push().
m_rest
template<class T , int N> Array<T> G3D::SmallArray< T, N >::m_rest private
Remaining elements
Definition at line 31 of file SmallArray.h.
Referenced by G3D::SmallArray< T, N >::clearAndSetMemoryManager(), G3D::SmallArray< T, N >::contains(), G3D::SmallArray< T, N >::fastRemove(), G3D::SmallArray< T, N >::findIndex(), G3D::SmallArray< T, N >::next(), G3D::SmallArray< T, N >::operator[](), G3D::SmallArray< T, N >::pop(), G3D::SmallArray< T, N >::popDiscard(), G3D::SmallArray< T, N >::push(), and G3D::SmallArray< T, N >::resize().
m_size
template<class T , int N> int G3D::SmallArray< T, N >::m_size private
Definition at line 25 of file SmallArray.h.
Referenced by G3D::SmallArray< T, N >::contains(), G3D::SmallArray< T, N >::fastRemove(), G3D::SmallArray< T, N >::next(), G3D::SmallArray< T, N >::pop(), G3D::SmallArray< T, N >::popDiscard(), G3D::SmallArray< T, N >::push(), G3D::SmallArray< T, N >::resize(), and G3D::SmallArray< T, N >::size().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/SmallArray.h