Azerotcore-wotlk: instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript Struct Reference
instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript Struct Reference
Public Member Functions
instance_hellfire_ramparts_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *go) override
bool SetBossState (uint32 type, EncounterState state) override
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid felIronChestGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 27 of file instance_hellfire_ramparts.cpp.
Constructor & Destructor Documentation
instance_hellfire_ramparts_InstanceMapScript()
instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::instance_hellfire_ramparts_InstanceMapScript (Map * map) inline
Definition at line 29 of file instance_hellfire_ramparts.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetSaveData()
std::string instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 58 of file instance_hellfire_ramparts.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "H R " << GetBossSaveData();
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData().
Initialize()
void instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 31 of file instance_hellfire_ramparts.cpp.
         {
             SetBossNumber(MAX_ENCOUNTERS);
         }
References MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Load()
void instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
Definition at line 65 of file instance_hellfire_ramparts.cpp.
         {
             if (!strIn)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(strIn);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'H' && dataHead2 == 'R')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
         }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, SetBossState(), and SPECIAL.
OnGameObjectCreate()
void instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 36 of file instance_hellfire_ramparts.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_FEL_IRON_CHEST_NORMAL:
                 case GO_FEL_IRON_CHECT_HEROIC:
                     felIronChestGUID = go->GetGUID();
                     break;
             }
         }
References felIronChestGUID, Object::GetEntry(), Object::GetGUID(), GO_FEL_IRON_CHECT_HEROIC, and GO_FEL_IRON_CHEST_NORMAL.
SetBossState()
bool instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 47 of file instance_hellfire_ramparts.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             if (type == DATA_VAZRUDEN && state == DONE)
                 if (GameObject* chest = instance->GetGameObject(felIronChestGUID))
                     chest->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             return true;
         }
References DATA_VAZRUDEN, DONE, felIronChestGUID, GAMEOBJECT_FLAGS, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, and InstanceScript::SetBossState().
Referenced by Load().
Member Data Documentation
felIronChestGUID
ObjectGuid instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript::felIronChestGUID protected
Definition at line 89 of file instance_hellfire_ramparts.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/instance_hellfire_ramparts.cpp