Azerotcore-wotlk: utf8::iterator< octet_iterator > Class Template Reference
utf8::iterator< octet_iterator > Class Template Reference
#include <checked.h>
Public Member Functions
iterator ()
iterator (const octet_iterator &octet_it, const octet_iterator &range_start, const octet_iterator &range_end)
octet_iterator base () const
uint32_t operator* () const
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
Private Attributes
octet_iterator it
octet_iterator range_start
octet_iterator range_end
Detailed Description
template<typename octet_iterator>
class utf8::iterator< octet_iterator >
Definition at line 268 of file checked.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename octet_iterator > utf8::iterator< octet_iterator >::iterator () inline
Definition at line 273 of file checked.h.
 {}
iterator() [2/2]
template<typename octet_iterator > utf8::iterator< octet_iterator >::iterator (const octet_iterator< octet_iterator > & octet_it, const octet_iterator< octet_iterator > & range_start, const octet_iterator< octet_iterator > & range_end) inline explicit
Definition at line 274 of file checked.h.
                                                           :
                it(octet_it), range_start(range_start), range_end(range_end)
       {
           if (it < range_start || it > range_end)
               throw std::out_of_range("Invalid utf-8 iterator position");
       }
References utf8::iterator< octet_iterator >::range_end.
Member Function Documentation
base()
template<typename octet_iterator > octet_iterator utf8::iterator< octet_iterator >::base () const inline
Definition at line 283 of file checked.h.
 { return it; }
References utf8::iterator< octet_iterator >::it.
operator!=()
template<typename octet_iterator > bool utf8::iterator< octet_iterator >::operator!= (const iterator< octet_iterator > & rhs) const inline
Definition at line 295 of file checked.h.
       {
           return !(operator == (rhs));
       }
References utf8::iterator< octet_iterator >::operator==().
operator*()
template<typename octet_iterator > uint32_t utf8::iterator< octet_iterator >::operator* () const inline
Definition at line 284 of file checked.h.
       {
           octet_iterator temp = it;
           return utf8::next(temp, range_end);
       }
References utf8::iterator< octet_iterator >::it, utf8::next(), and utf8::iterator< octet_iterator >::range_end.
operator++() [1/2]
template<typename octet_iterator > iterator& utf8::iterator< octet_iterator >::operator++ () inline
Definition at line 299 of file checked.h.
       {
           utf8::next(it, range_end);
           return *this;
       }
References utf8::iterator< octet_iterator >::it, utf8::next(), and utf8::iterator< octet_iterator >::range_end.
operator++() [2/2]
template<typename octet_iterator > iterator utf8::iterator< octet_iterator >::operator++ (int) inline
Definition at line 304 of file checked.h.
       {
           iterator temp = *this;
           utf8::next(it, range_end);
           return temp;
       }
References utf8::iterator< octet_iterator >::it, utf8::next(), and utf8::iterator< octet_iterator >::range_end.
operator--() [1/2]
template<typename octet_iterator > iterator& utf8::iterator< octet_iterator >::operator-- () inline
Definition at line 310 of file checked.h.
       {
           utf8::prior(it, range_start);
           return *this;
       }
References utf8::iterator< octet_iterator >::it, utf8::prior(), and utf8::iterator< octet_iterator >::range_start.
operator--() [2/2]
template<typename octet_iterator > iterator utf8::iterator< octet_iterator >::operator-- (int) inline
Definition at line 315 of file checked.h.
       {
           iterator temp = *this;
           utf8::prior(it, range_start);
           return temp;
       }
References utf8::iterator< octet_iterator >::it, utf8::prior(), and utf8::iterator< octet_iterator >::range_start.
operator==()
template<typename octet_iterator > bool utf8::iterator< octet_iterator >::operator== (const iterator< octet_iterator > & rhs) const inline
Definition at line 289 of file checked.h.
       {
           if (range_start != rhs.range_start || range_end != rhs.range_end)
               throw std::logic_error("Comparing utf-8 iterators defined with different ranges");
           return (it == rhs.it);
       }
References utf8::iterator< octet_iterator >::it, utf8::iterator< octet_iterator >::range_end, and utf8::iterator< octet_iterator >::range_start.
Referenced by utf8::iterator< octet_iterator >::operator!=().
Member Data Documentation
it
template<typename octet_iterator > octet_iterator utf8::iterator< octet_iterator >::it private
Definition at line 269 of file checked.h.
Referenced by utf8::iterator< octet_iterator >::base(), utf8::iterator< octet_iterator >::operator*(), utf8::iterator< octet_iterator >::operator++(), utf8::iterator< octet_iterator >::operator--(), and utf8::iterator< octet_iterator >::operator==().
range_end
template<typename octet_iterator > octet_iterator utf8::iterator< octet_iterator >::range_end private
Definition at line 271 of file checked.h.
Referenced by utf8::iterator< octet_iterator >::iterator(), utf8::iterator< octet_iterator >::operator*(), utf8::iterator< octet_iterator >::operator++(), and utf8::iterator< octet_iterator >::operator==().
range_start
template<typename octet_iterator > octet_iterator utf8::iterator< octet_iterator >::range_start private
Definition at line 270 of file checked.h.
Referenced by utf8::iterator< octet_iterator >::operator--(), and utf8::iterator< octet_iterator >::operator==().
The documentation for this class was generated from the following file:
deps/utf8cpp/utf8/checked.h