Azerotcore-wotlk: VMAP::VMapFactory Class Reference
VMAP::VMapFactory Class Reference
#include <VMapFactory.h>
Static Public Member Functions
static VMapMgr2 * createOrGetVMapMgr ()
static void clear ()
Detailed Description
Definition at line 28 of file VMapFactory.h.
Member Function Documentation
clear()
void VMAP::VMapFactory::clear () static
Definition at line 39 of file VMapFactory.cpp.
     {
         delete gVMapMgr;
         gVMapMgr = nullptr;
     }
References VMAP::gVMapMgr.
Referenced by World::~World().
createOrGetVMapMgr()
VMapMgr2 * VMAP::VMapFactory::createOrGetVMapMgr () static
Definition at line 27 of file VMapFactory.cpp.
     {
         if (!gVMapMgr)
         {
             gVMapMgr = new VMapMgr2();
         }
         return gVMapMgr;
     }
References VMAP::gVMapMgr.
Referenced by Map::CheckCollisionAndGetValidCoords(), Map::ExistVMap(), DynamicMapTree::GetAreaAndLiquidData(), Map::GetAreaInfo(), Map::GetFullTerrainStatusForPosition(), Map::GetHeight(), Map::GetLiquidData(), server_commandscript::HandleServerDebugCommand(), GameObjectModel::initialize(), Map::isInLineOfSight(), World::LoadConfigSettings(), Map::LoadVMap(), World::SetInitialWorldSettings(), Map::UnloadGrid(), and GameObjectModel::~GameObjectModel().
The documentation for this class was generated from the following files:
src/common/Collision/Management/VMapFactory.h
src/common/Collision/Management/VMapFactory.cpp