Azerotcore-wotlk: deps/recastnavigation/Detour/Include/DetourAlloc.h File Reference
DetourAlloc.h File Reference
#include <stddef.h>
Typedefs
typedef void *() dtAllocFunc(size_t size, dtAllocHint hint)
A memory allocation function.
typedef void() dtFreeFunc(void *ptr)
Enumerations
enum dtAllocHint { DT_ALLOC_PERM , DT_ALLOC_TEMP }
Functions
void dtAllocSetCustom (dtAllocFunc *allocFunc, dtFreeFunc *freeFunc)
void * dtAlloc (size_t size, dtAllocHint hint)
void dtFree (void *ptr)
Typedef Documentation
dtAllocFunc
typedef void*() dtAllocFunc(size_t size, dtAllocHint hint)
A memory allocation function.
See also
dtAllocSetCustom
Definition at line 37 of file DetourAlloc.h.
dtFreeFunc
typedef void() dtFreeFunc(void *ptr)
A memory deallocation function.
Parameters
[in] ptr A pointer to a memory block previously allocated using dtAllocFunc.
See also
dtAllocSetCustom
Definition at line 42 of file DetourAlloc.h.
Enumeration Type Documentation
dtAllocHint
enum dtAllocHint
Provides hint values to the memory allocator on how long the memory is expected to be used.
Enumerator
DT_ALLOC_PERM
Memory persist after a function call.
DT_ALLOC_TEMP
Memory used temporarily within a function.
Definition at line 26 of file DetourAlloc.h.
 {
     DT_ALLOC_PERM,
     DT_ALLOC_TEMP
 };
Function Documentation
dtAlloc()
void* dtAlloc (size_t size, dtAllocHint hint)
Allocates a memory block.
Parameters
[in] size The size, in bytes of memory, to allocate.
[in] hint A hint to the allocator on how long the memory is expected to be in use.
Returns
A pointer to the beginning of the allocated memory block, or null if the allocation failed.
See also
dtFree
Definition at line 41 of file DetourAlloc.cpp.
 {
     return sAllocFunc(size, hint);
 }
References sAllocFunc.
Referenced by createBVTree(), dtAllocNavMesh(), dtAllocNavMeshQuery(), dtCreateNavMeshData(), dtNodePool::dtNodePool(), dtNodeQueue::dtNodeQueue(), dtNavMeshQuery::init(), dtNavMesh::init(), and MMAP::MMapMgr::loadMap().
dtAllocSetCustom()
void dtAllocSetCustom (dtAllocFunc * allocFunc, dtFreeFunc * freeFunc)
Sets the base custom allocation functions to be used by Detour.
Parameters
[in] allocFunc The memory allocation function to be used by dtAlloc
[in] freeFunc The memory de-allocation function to be used by dtFree
Definition at line 35 of file DetourAlloc.cpp.
 {
     sAllocFunc = allocFunc ? allocFunc : dtAllocDefault;
     sFreeFunc = freeFunc ? freeFunc : dtFreeDefault;
 }
References dtAllocDefault(), dtFreeDefault(), sAllocFunc, and sFreeFunc.
Referenced by World::SetInitialWorldSettings().
dtFree()
void dtFree (void * ptr)
Deallocates a memory block.
Parameters
[in] ptr A pointer to a memory block previously allocated using dtAlloc.
See also
dtAlloc
Definition at line 46 of file DetourAlloc.cpp.
 {
     if (ptr)
         sFreeFunc(ptr);
 }
References ptr(), and sFreeFunc.
Referenced by ContinentBuilder::Build(), createBVTree(), dtCreateNavMeshData(), dtFreeNavMesh(), dtFreeNavMeshQuery(), dtNavMeshQuery::init(), MMAP::MMapMgr::loadMap(), dtNavMesh::removeTile(), BuilderThread::svc(), dtNavMesh::~dtNavMesh(), dtNavMeshQuery::~dtNavMeshQuery(), dtNodePool::~dtNodePool(), and dtNodeQueue::~dtNodeQueue().