Azerotcore-wotlk: npc_tiger_matriarch::npc_tiger_matriarchAI Struct Reference
npc_tiger_matriarch::npc_tiger_matriarchAI Struct Reference
Public Member Functions
npc_tiger_matriarchAI (Creature *creature)
void EnterCombat (Unit *) override
void IsSummonedBy (Unit *summoner) override
void KilledUnit (Unit *victim) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
ObjectGuid _tigerGuid
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 151 of file zone_durotar.cpp.
Constructor & Destructor Documentation
npc_tiger_matriarchAI()
npc_tiger_matriarch::npc_tiger_matriarchAI::npc_tiger_matriarchAI (Creature * creature) inline
Definition at line 153 of file zone_durotar.cpp.
                                                   : ScriptedAI(creature)
         {
         }
Member Function Documentation
DamageTaken()
void npc_tiger_matriarch::npc_tiger_matriarchAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 192 of file zone_durotar.cpp.
         {
             if (!attacker || !attacker->IsSummon())
                 return;
             if (HealthBelowPct(20))
             {
                 damage = 0;
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 if (Unit* vehSummoner = attacker->ToTempSummon()->GetSummonerUnit())
                 {
                     vehSummoner->AddAura(SPELL_SUMMON_ZENTABRA_TRIGGER, vehSummoner);
                     vehSummoner->CastSpell(vehSummoner, SPELL_SUMMON_ZENTABRA, true);
                     attacker->CastSpell(attacker, SPELL_EJECT_PASSENGERS, true);
                     vehSummoner->RemoveAurasDueToSpell(SPELL_NO_SUMMON_AURA);
                     vehSummoner->RemoveAurasDueToSpell(SPELL_DETECT_INVIS);
                     vehSummoner->RemoveAurasDueToSpell(SPELL_SPIRIT_OF_THE_TIGER_RIDER);
                     vehSummoner->RemoveAurasDueToSpell(SPELL_SUMMON_ZENTABRA_TRIGGER);
                 }
                 me->DespawnOrUnsummon();
             }
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), TempSummon::GetSummonerUnit(), ScriptedAI::HealthBelowPct(), Unit::IsSummon(), ScriptedAI::me, Object::SetFlag(), SPELL_DETECT_INVIS, SPELL_EJECT_PASSENGERS, SPELL_NO_SUMMON_AURA, SPELL_SPIRIT_OF_THE_TIGER_RIDER, SPELL_SUMMON_ZENTABRA, SPELL_SUMMON_ZENTABRA_TRIGGER, Unit::ToTempSummon(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
EnterCombat()
void npc_tiger_matriarch::npc_tiger_matriarchAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 157 of file zone_durotar.cpp.
         {
             _events.Reset();
             _events.ScheduleEvent(EVENT_POUNCE, 100);
             _events.ScheduleEvent(EVENT_NOSUMMON, 50000);
         }
References _events, EVENT_NOSUMMON, EVENT_POUNCE, EventMap::Reset(), and EventMap::ScheduleEvent().
IsSummonedBy()
void npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy (Unit * summoner) inline override virtual
Reimplemented from CreatureAI.
Definition at line 164 of file zone_durotar.cpp.
         {
             if (summoner->GetTypeId() != TYPEID_PLAYER || !summoner->GetVehicle())
                 return;
             _tigerGuid = summoner->GetVehicle()->GetBase()->GetGUID();
             if (Unit* tiger = ObjectAccessor::GetUnit(*me, _tigerGuid))
             {
                 me->AddThreat(tiger, 500000.0f);
                 DoCast(me, SPELL_FURIOUS_BITE);
             }
         }
References _tigerGuid, Unit::AddThreat(), UnitAI::DoCast(), Vehicle::GetBase(), Object::GetGUID(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVehicle(), ScriptedAI::me, SPELL_FURIOUS_BITE, and TYPEID_PLAYER.
KilledUnit()
void npc_tiger_matriarch::npc_tiger_matriarchAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 177 of file zone_durotar.cpp.
         {
             if (victim->GetTypeId() != TYPEID_UNIT || !victim->IsSummon())
                 return;
             if (Unit* vehSummoner = victim->ToTempSummon()->GetSummonerUnit())
             {
                 vehSummoner->RemoveAurasDueToSpell(SPELL_NO_SUMMON_AURA);
                 vehSummoner->RemoveAurasDueToSpell(SPELL_DETECT_INVIS);
                 vehSummoner->RemoveAurasDueToSpell(SPELL_SPIRIT_OF_THE_TIGER_RIDER);
                 vehSummoner->RemoveAurasDueToSpell(SPELL_SUMMON_ZENTABRA_TRIGGER);
             }
             me->DespawnOrUnsummon();
         }
References Creature::DespawnOrUnsummon(), TempSummon::GetSummonerUnit(), Object::GetTypeId(), Unit::IsSummon(), ScriptedAI::me, SPELL_DETECT_INVIS, SPELL_NO_SUMMON_AURA, SPELL_SPIRIT_OF_THE_TIGER_RIDER, SPELL_SUMMON_ZENTABRA_TRIGGER, Unit::ToTempSummon(), and TYPEID_UNIT.
UpdateAI()
void npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 216 of file zone_durotar.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (!_tigerGuid)
                 return;
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_POUNCE:
                         DoCastVictim(SPELL_POUNCE);
                         _events.ScheduleEvent(EVENT_POUNCE, 30000);
                         break;
                     case EVENT_NOSUMMON: // Reapply SPELL_NO_SUMMON_AURA
                         if (Unit* tiger = ObjectAccessor::GetUnit(*me, _tigerGuid))
{
                             if (tiger->IsSummon())
                                 if (Unit* vehSummoner = tiger->ToTempSummon()->GetSummonerUnit())
                                     me->AddAura(SPELL_NO_SUMMON_AURA, vehSummoner);
                         }
                         _events.ScheduleEvent(EVENT_NOSUMMON, 50000);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, _tigerGuid, Unit::AddAura(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EVENT_NOSUMMON, EVENT_POUNCE, EventMap::ExecuteEvent(), TempSummon::GetSummonerUnit(), ObjectAccessor::GetUnit(), ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_NO_SUMMON_AURA, SPELL_POUNCE, Unit::ToTempSummon(), EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_events
EventMap npc_tiger_matriarch::npc_tiger_matriarchAI::_events private
Definition at line 252 of file zone_durotar.cpp.
Referenced by EnterCombat(), and UpdateAI().
_tigerGuid
ObjectGuid npc_tiger_matriarch::npc_tiger_matriarchAI::_tigerGuid private
Definition at line 253 of file zone_durotar.cpp.
Referenced by IsSummonedBy(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_durotar.cpp