Azerotcore-wotlk: npc_commander_dawnforge::npc_commander_dawnforgeAI Struct Reference
npc_commander_dawnforge::npc_commander_dawnforgeAI Struct Reference
Public Member Functions
npc_commander_dawnforgeAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summoned) override
void Turn_to_Pathaleons_Image ()
void Turn_to_eachother ()
bool CanStartEvent (Player *player)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid PlayerGUID
ObjectGuid ardonisGUID
ObjectGuid pathaleonGUID
uint32 Phase
uint32 PhaseSubphase
uint32 Phase_Timer
bool isEvent
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1369 of file zone_netherstorm.cpp.
Constructor & Destructor Documentation
npc_commander_dawnforgeAI()
npc_commander_dawnforge::npc_commander_dawnforgeAI::npc_commander_dawnforgeAI (Creature * creature) inline
Definition at line 1371 of file zone_netherstorm.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
CanStartEvent()
bool npc_commander_dawnforge::npc_commander_dawnforgeAI::CanStartEvent (Player * player) inline
Definition at line 1438 of file zone_netherstorm.cpp.
         {
             if (!isEvent)
             {
                 Creature* ardonis = me->FindNearestCreature(CreatureEntry[0], 10.0f);
                 if (!ardonis)
                     return false;
                 ardonisGUID = ardonis->GetGUID();
                 PlayerGUID = player->GetGUID();
                 isEvent = true;
                 Turn_to_eachother();
                 return true;
             }
             LOG_DEBUG("scripts.ai", "npc_commander_dawnforge event already in progress, need to wait.");
             return false;
         }
References ardonisGUID, WorldObject::FindNearestCreature(), Object::GetGUID(), isEvent, LOG_DEBUG, ScriptedAI::me, PlayerGUID, and Turn_to_eachother().
EnterCombat()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1394 of file zone_netherstorm.cpp.
 { }
JustSummoned()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1396 of file zone_netherstorm.cpp.
         {
             pathaleonGUID = summoned->GetGUID();
         }
References Object::GetGUID(), and pathaleonGUID.
Reset()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1382 of file zone_netherstorm.cpp.
         {
             PlayerGUID.Clear();
             ardonisGUID.Clear();
             pathaleonGUID.Clear();
             Phase = 1;
             PhaseSubphase = 0;
             Phase_Timer = 4000;
             isEvent = false;
         }
References ardonisGUID, ObjectGuid::Clear(), isEvent, pathaleonGUID, Phase_Timer, PhaseSubphase, and PlayerGUID.
Referenced by UpdateAI().
Turn_to_eachother()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_eachother () inline
Definition at line 1422 of file zone_netherstorm.cpp.
         {
             if (Unit* ardonis = ObjectAccessor::GetUnit(*me, ardonisGUID))
             {
                 // Turn Dawnforge
                 me->SetFacingToObject(ardonis);
                 // Turn Ardonis
                 ardonis->SetFacingToObject(me);
                 //Set state
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 ardonis->SetStandState(UNIT_STAND_STATE_STAND);
             }
         }
References ardonisGUID, ObjectAccessor::GetUnit(), ScriptedAI::me, Unit::SetFacingToObject(), Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
Referenced by CanStartEvent(), and UpdateAI().
Turn_to_Pathaleons_Image()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_Pathaleons_Image () inline
Definition at line 1402 of file zone_netherstorm.cpp.
         {
             Creature* ardonis = ObjectAccessor::GetCreature(*me, ardonisGUID);
             Creature* pathaleon = ObjectAccessor::GetCreature(*me, pathaleonGUID);
             if (!ardonis || !pathaleon)
                 return;
             // Turn Dawnforge
             me->SetFacingToObject(pathaleon);
             // Turn Ardonis
             ardonis->SetFacingToObject(pathaleon);
             //Set them to kneel
             me->SetStandState(UNIT_STAND_STATE_KNEEL);
             ardonis->SetStandState(UNIT_STAND_STATE_KNEEL);
         }
References ardonisGUID, ObjectAccessor::GetCreature(), ScriptedAI::me, pathaleonGUID, Unit::SetFacingToObject(), Unit::SetStandState(), and UNIT_STAND_STATE_KNEEL.
Referenced by UpdateAI().
UpdateAI()
void npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1459 of file zone_netherstorm.cpp.
         {
             //Is event even running?
             if (!isEvent)
                 return;
             //Phase timing
             if (Phase_Timer >= diff)
             {
                 Phase_Timer -= diff;
                 return;
             }
             Creature* ardonis = ObjectAccessor::GetCreature(*me, ardonisGUID);
             Creature* pathaleon = ObjectAccessor::GetCreature(*me, pathaleonGUID);
             Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
             if (!ardonis || !player)
             {
                 Reset();
                 return;
             }
             if (Phase > 4 && !pathaleon)
             {
                 Reset();
                 return;
             }
             //Phase 1 Dawnforge say
             switch (Phase)
             {
                 case 1:
                     Talk(SAY_COMMANDER_DAWNFORGE_1);
                     ++Phase;
                     Phase_Timer = 16000;
                     break;
                 //Phase 2 Ardonis say
                 case 2:
                     ardonis->AI()->Talk(SAY_ARCANIST_ARDONIS_1);
                     ++Phase;
                     Phase_Timer = 16000;
                     break;
                 //Phase 3 Dawnforge say
                 case 3:
                     Talk(SAY_COMMANDER_DAWNFORGE_2);
                     ++Phase;
                     Phase_Timer = 16000;
                     break;
                 //Phase 4 Pathaleon spawns up to phase 9
                 case 4:
                     //spawn pathaleon's image
                     me->SummonCreature(CreatureEntry[2], 2325.851563f, 2799.534668f, 133.084229f, 6.038996f, TEMPSUMMON_TIMED_DESPAWN, 90000);
                     ++Phase;
                     Phase_Timer = 500;
                     break;
                 //Phase 5 Pathaleon say
                 case 5:
                     pathaleon->AI()->Talk(SAY_PATHALEON_CULATOR_IMAGE_1);
                     ++Phase;
                     Phase_Timer = 6000;
                     break;
                 //Phase 6
                 case 6:
                     switch (PhaseSubphase)
                     {
                         //Subphase 1: Turn Dawnforge and Ardonis
                         case 0:
                             Turn_to_Pathaleons_Image();
                             ++PhaseSubphase;
                             Phase_Timer = 8000;
                             break;
                         //Subphase 2 Dawnforge say
                         case 1:
                             Talk(SAY_COMMANDER_DAWNFORGE_3);
                             PhaseSubphase = 0;
                             ++Phase;
                             Phase_Timer = 8000;
                             break;
                     }
                     break;
                 //Phase 7 Pathaleons say 3 Sentence, every sentence need a subphase
                 case 7:
                     switch (PhaseSubphase)
                     {
                         //Subphase 1
                         case 0:
                             pathaleon->AI()->Talk(SAY_PATHALEON_CULATOR_IMAGE_2);
                             ++PhaseSubphase;
                             Phase_Timer = 12000;
                             break;
                         //Subphase 2
                         case 1:
                             pathaleon->AI()->Talk(SAY_PATHALEON_CULATOR_IMAGE_2_1);
                             ++PhaseSubphase;
                             Phase_Timer = 16000;
                             break;
                         //Subphase 3
                         case 2:
                             pathaleon->AI()->Talk(SAY_PATHALEON_CULATOR_IMAGE_2_2);
                             PhaseSubphase = 0;
                             ++Phase;
                             Phase_Timer = 10000;
                             break;
                     }
                     break;
                 //Phase 8 Dawnforge & Ardonis say
                 case 8:
                     Talk(SAY_COMMANDER_DAWNFORGE_4);
                     ardonis->AI()->Talk(SAY_ARCANIST_ARDONIS_2);
                     ++Phase;
                     Phase_Timer = 4000;
                     break;
                 //Phase 9 Pathaleons Despawn, Reset Dawnforge & Ardonis angle
                 case 9:
                     Turn_to_eachother();
                     //hide pathaleon, unit will despawn shortly
                     pathaleon->SetVisible(false);
                     PhaseSubphase = 0;
                     ++Phase;
                     Phase_Timer = 3000;
                     break;
                 //Phase 10 Dawnforge say
                 case 10:
                     Talk(SAY_COMMANDER_DAWNFORGE_5);
                     player->AreaExploredOrEventHappens(QUEST_INFO_GATHERING);
                     Reset();
                     break;
             }
         }
References Creature::AI(), ardonisGUID, Player::AreaExploredOrEventHappens(), ObjectAccessor::GetCreature(), ObjectAccessor::GetPlayer(), isEvent, ScriptedAI::me, pathaleonGUID, Phase, Phase_Timer, PhaseSubphase, PlayerGUID, QUEST_INFO_GATHERING, Reset(), SAY_ARCANIST_ARDONIS_1, SAY_ARCANIST_ARDONIS_2, SAY_COMMANDER_DAWNFORGE_1, SAY_COMMANDER_DAWNFORGE_2, SAY_COMMANDER_DAWNFORGE_3, SAY_COMMANDER_DAWNFORGE_4, SAY_COMMANDER_DAWNFORGE_5, SAY_PATHALEON_CULATOR_IMAGE_1, SAY_PATHALEON_CULATOR_IMAGE_2, SAY_PATHALEON_CULATOR_IMAGE_2_1, SAY_PATHALEON_CULATOR_IMAGE_2_2, Unit::SetVisible(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, Turn_to_eachother(), and Turn_to_Pathaleons_Image().
Member Data Documentation
ardonisGUID
ObjectGuid npc_commander_dawnforge::npc_commander_dawnforgeAI::ardonisGUID
Definition at line 1374 of file zone_netherstorm.cpp.
Referenced by CanStartEvent(), Reset(), Turn_to_eachother(), Turn_to_Pathaleons_Image(), and UpdateAI().
isEvent
bool npc_commander_dawnforge::npc_commander_dawnforgeAI::isEvent
Definition at line 1380 of file zone_netherstorm.cpp.
Referenced by CanStartEvent(), Reset(), and UpdateAI().
pathaleonGUID
ObjectGuid npc_commander_dawnforge::npc_commander_dawnforgeAI::pathaleonGUID
Definition at line 1375 of file zone_netherstorm.cpp.
Referenced by JustSummoned(), Reset(), Turn_to_Pathaleons_Image(), and UpdateAI().
Phase
uint32 npc_commander_dawnforge::npc_commander_dawnforgeAI::Phase
Definition at line 1377 of file zone_netherstorm.cpp.
Referenced by UpdateAI().
Phase_Timer
uint32 npc_commander_dawnforge::npc_commander_dawnforgeAI::Phase_Timer
Definition at line 1379 of file zone_netherstorm.cpp.
Referenced by Reset(), and UpdateAI().
PhaseSubphase
uint32 npc_commander_dawnforge::npc_commander_dawnforgeAI::PhaseSubphase
Definition at line 1378 of file zone_netherstorm.cpp.
Referenced by Reset(), and UpdateAI().
PlayerGUID
ObjectGuid npc_commander_dawnforge::npc_commander_dawnforgeAI::PlayerGUID
Definition at line 1373 of file zone_netherstorm.cpp.
Referenced by CanStartEvent(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_netherstorm.cpp