Azerotcore-wotlk: formatter< tuple_join_view< Char, T... >, Char > Struct Template Reference
formatter< tuple_join_view< Char, T... >, Char > Struct Template Reference
#include <ranges.h>
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (const tuple_join_view< Char, T... > &value, FormatContext &ctx) -> typename FormatContext::iterator
Private Member Functions
template<typename FormatContext , size_t... N>
auto format (const tuple_join_view< Char, T... > &value, FormatContext &ctx, detail::index_sequence< N... >) -> typename FormatContext::iterator
template<typename FormatContext >
auto format_args (const tuple_join_view< Char, T... > &, FormatContext &ctx) -> typename FormatContext::iterator
template<typename FormatContext , typename Arg , typename... Args>
auto format_args (const tuple_join_view< Char, T... > &value, FormatContext &ctx, const Arg &arg, const Args &... args) -> typename FormatContext::iterator
Detailed Description
template<typename Char, typename... T>
struct formatter< tuple_join_view< Char, T... >, Char >
Definition at line 378 of file ranges.h.
Member Function Documentation
format() [1/2]
template<typename Char , typename... T> template<typename FormatContext > auto formatter< tuple_join_view< Char, T... >, Char >::format (const tuple_join_view< Char, T... > & value, FormatContext & ctx) -> typename FormatContext::iterator inline
Definition at line 385 of file ranges.h.
{
     return format(value, ctx, detail::make_index_sequence<sizeof...(T)>{});
   }
References format().
format() [2/2]
template<typename Char , typename... T> template<typename FormatContext , size_t... N> auto formatter< tuple_join_view< Char, T... >, Char >::format (const tuple_join_view< Char, T... > & value, FormatContext & ctx, detail::index_sequence< N... >) -> typename FormatContext::iterator inline private
Definition at line 392 of file ranges.h.
{
     using std::get;
     return format_args(value, ctx, get<N>(value.tuple)...);
   }
format_args() [1/2]
template<typename Char , typename... T> template<typename FormatContext > auto formatter< tuple_join_view< Char, T... >, Char >::format_args (const tuple_join_view< Char, T... > & , FormatContext & ctx) -> typename FormatContext::iterator inline private
Definition at line 400 of file ranges.h.
{
     // NOTE: for compilers that support C++17, this empty function instantiation
     // can be replaced with a constexpr branch in the variadic overload.
     return ctx.out();
   }
format_args() [2/2]
template<typename Char , typename... T> template<typename FormatContext , typename Arg , typename... Args> auto formatter< tuple_join_view< Char, T... >, Char >::format_args (const tuple_join_view< Char, T... > & value, FormatContext & ctx, const Arg & arg, const Args &... args) -> typename FormatContext::iterator inline private
Definition at line 408 of file ranges.h.
{
     using base = formatter<typename std::decay<Arg>::type, Char>;
     auto out = base().format(arg, ctx);
     if (sizeof...(Args) > 0) {
       out = std::copy(value.sep.begin(), value.sep.end(), out);
       ctx.advance_to(out);
       return format_args(value, ctx, args...);
     }
     return out;
   }
References arg(), and detail::copy().
parse()
template<typename Char , typename... T> template<typename ParseContext > FMT_CONSTEXPR auto formatter< tuple_join_view< Char, T... >, Char >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 380 of file ranges.h.
{
     return ctx.begin();
   }
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/ranges.h