Azerotcore-wotlk: LootStore Class Reference
LootStore Class Reference
#include <LootMgr.h>
Public Member Functions
LootStore (char const *name, char const *entryName, bool ratesAllowed)
virtual ~LootStore ()
uint32 LoadAndCollectLootIds (LootIdSet &ids_set)
void ResetConditions ()
void Verify () const
void CheckLootRefs (LootIdSet *ref_set=nullptr) const
void ReportUnusedIds (LootIdSet const &ids_set) const
void ReportNonExistingId (uint32 lootId) const
void ReportNonExistingId (uint32 lootId, const char *ownerType, uint32 ownerId) const
bool HaveLootFor (uint32 loot_id) const
bool HaveQuestLootFor (uint32 loot_id) const
bool HaveQuestLootForPlayer (uint32 loot_id, Player const *player) const
LootTemplate const * GetLootFor (uint32 loot_id) const
LootTemplate * GetLootForConditionFill (uint32 loot_id) const
char const * GetName () const
char const * GetEntryName () const
bool IsRatesAllowed () const
Protected Member Functions
uint32 LoadLootTable ()
void Clear ()
Private Attributes
LootTemplateMap m_LootTemplates
char const * m_name
char const * m_entryName
bool m_ratesAllowed
Detailed Description
Definition at line 207 of file LootMgr.h.
Constructor & Destructor Documentation
LootStore()
LootStore::LootStore (char const * name, char const * entryName, bool ratesAllowed) inline explicit
Definition at line 210 of file LootMgr.h.
         : m_name(name), m_entryName(entryName), m_ratesAllowed(ratesAllowed) {}
~LootStore()
virtual LootStore::~LootStore () inline virtual
Definition at line 213 of file LootMgr.h.
 { Clear(); }
References Clear().
Member Function Documentation
CheckLootRefs()
void LootStore::CheckLootRefs (LootIdSet * ref_set = nullptr) const
Definition at line 273 of file LootMgr.cpp.
 {
     for (LootTemplateMap::const_iterator ltItr = m_LootTemplates.begin(); ltItr != m_LootTemplates.end(); ++ltItr)
         ltItr->second->CheckLootRefs(m_LootTemplates, ref_set);
 }
References m_LootTemplates.
Referenced by reload_commandscript::HandleReloadLootTemplatesCreatureCommand(), reload_commandscript::HandleReloadLootTemplatesDisenchantCommand(), reload_commandscript::HandleReloadLootTemplatesFishingCommand(), reload_commandscript::HandleReloadLootTemplatesGameobjectCommand(), reload_commandscript::HandleReloadLootTemplatesItemCommand(), reload_commandscript::HandleReloadLootTemplatesMailCommand(), reload_commandscript::HandleReloadLootTemplatesMillingCommand(), reload_commandscript::HandleReloadLootTemplatesPickpocketingCommand(), reload_commandscript::HandleReloadLootTemplatesProspectingCommand(), reload_commandscript::HandleReloadLootTemplatesSkinningCommand(), reload_commandscript::HandleReloadLootTemplatesSpellCommand(), and LoadLootTemplates_Reference().
Clear()
void LootStore::Clear () protected
Definition at line 123 of file LootMgr.cpp.
 {
     for (LootTemplateMap::const_iterator itr = m_LootTemplates.begin(); itr != m_LootTemplates.end(); ++itr)
         delete itr->second;
     m_LootTemplates.clear();
 }
References m_LootTemplates.
Referenced by LoadLootTable(), and ~LootStore().
GetEntryName()
char const* LootStore::GetEntryName () const inline
Definition at line 232 of file LootMgr.h.
 { return m_entryName; }
References m_entryName.
Referenced by ReportUnusedIds().
GetLootFor()
LootTemplate const * LootStore::GetLootFor (uint32 loot_id) const
Definition at line 243 of file LootMgr.cpp.
 {
     LootTemplateMap::const_iterator tab = m_LootTemplates.find(loot_id);
     if (tab == m_LootTemplates.end())
         return nullptr;
     return tab->second;
 }
References m_LootTemplates.
Referenced by LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), LootTemplate::CopyConditions(), Loot::FillLoot(), LootItemStorage::LoadStoredLoot(), LootTemplate::Process(), and LootTemplate::LootGroup::Process().
GetLootForConditionFill()
LootTemplate * LootStore::GetLootForConditionFill (uint32 loot_id) const
Definition at line 253 of file LootMgr.cpp.
 {
     LootTemplateMap::const_iterator tab = m_LootTemplates.find(loot_id);
     if (tab == m_LootTemplates.end())
         return nullptr;
     return tab->second;
 }
References m_LootTemplates.
Referenced by ConditionMgr::isSourceTypeValid(), and ConditionMgr::LoadConditions().
GetName()
char const* LootStore::GetName () const inline
Definition at line 231 of file LootMgr.h.
 { return m_name; }
References m_name.
Referenced by Loot::FillLoot(), LootStoreItem::IsValid(), LoadLootTable(), ReportNonExistingId(), ReportUnusedIds(), and LootTemplate::LootGroup::Verify().
HaveLootFor()
bool LootStore::HaveLootFor (uint32 loot_id) const inline
Definition at line 224 of file LootMgr.h.
 { return m_LootTemplates.find(loot_id) != m_LootTemplates.end(); }
References m_LootTemplates.
Referenced by Spell::CheckItems(), ConditionMgr::isSourceTypeValid(), and Creature::setDeathState().
HaveQuestLootFor()
bool LootStore::HaveQuestLootFor (uint32 loot_id) const
Definition at line 214 of file LootMgr.cpp.
 {
     LootTemplateMap::const_iterator itr = m_LootTemplates.find(loot_id);
     if (itr == m_LootTemplates.end())
         return false;
     // scan loot for quest items
     return itr->second->HasQuestDrop(m_LootTemplates);
 }
References m_LootTemplates.
Referenced by ObjectMgr::LoadGameObjectForQuests().
HaveQuestLootForPlayer()
bool LootStore::HaveQuestLootForPlayer (uint32 loot_id, Player const * player) const
Definition at line 224 of file LootMgr.cpp.
 {
     LootTemplateMap::const_iterator tab = m_LootTemplates.find(loot_id);
     if (tab != m_LootTemplates.end())
         if (tab->second->HasQuestDropForPlayer(m_LootTemplates, player))
             return true;
     return false;
 }
References m_LootTemplates.
Referenced by GameObject::ActivateToQuest().
IsRatesAllowed()
bool LootStore::IsRatesAllowed () const inline
Definition at line 233 of file LootMgr.h.
 { return m_ratesAllowed; }
References m_ratesAllowed.
Referenced by LootTemplate::Process(), and LootTemplate::LootGroup::Process().
LoadAndCollectLootIds()
uint32 LootStore::LoadAndCollectLootIds (LootIdSet & ids_set)
Definition at line 263 of file LootMgr.cpp.
 {
     uint32 count = LoadLootTable();
     for (LootTemplateMap::const_iterator tab = m_LootTemplates.begin(); tab != m_LootTemplates.end(); ++tab)
         lootIdSet.insert(tab->first);
     return count;
 }
References count(), LoadLootTable(), and m_LootTemplates.
Referenced by LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
LoadLootTable()
uint32 LootStore::LoadLootTable () protected
Definition at line 140 of file LootMgr.cpp.
 {
     LootTemplateMap::const_iterator tab;
     // Clearing store (for reloading case)
     Clear();
     //                                                  0     1            2               3         4         5             6
     QueryResult result = WorldDatabase.PQuery("SELECT Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount FROM %s", GetName());
     if (!result)
         return 0;
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 entry               = fields[0].GetUInt32();
         uint32 item                = fields[1].GetUInt32();
         int32  reference           = fields[2].GetInt32();
         float  chance              = fields[3].GetFloat();
         bool   needsquest          = fields[4].GetBool();
         uint16 lootmode            = fields[5].GetUInt16();
         uint8  groupid             = fields[6].GetUInt8();
         int32  mincount            = fields[7].GetUInt8();
         int32  maxcount            = fields[8].GetUInt8();
         if (maxcount > std::numeric_limits<uint8>::max())
         {
             LOG_ERROR("sql.sql", "Table '%s' Entry %d Item %d: MaxCount value (%u) to large. must be less %u - skipped", GetName(), entry, item, maxcount, std::numeric_limits<uint8>::max());
             continue;                                   // error already printed to log/console.
         }
         if (lootmode == 0)
         {
             LOG_ERROR("sql.sql", "Table '%s' Entry %d Item %d: LootMode is equal to 0, item will never drop - setting mode 1", GetName(), entry, item);
             lootmode = 1;
         }
         LootStoreItem* storeitem = new LootStoreItem(item, reference, chance, needsquest, lootmode, groupid, mincount, maxcount);
         if (!storeitem->IsValid(*this, entry))            // Validity checks
         {
             delete storeitem;
             continue;
         }
         // Looking for the template of the entry
         // often entries are put together
         if (m_LootTemplates.empty() || tab->first != entry)
         {
             // Searching the template (in case template Id changed)
             tab = m_LootTemplates.find(entry);
             if (tab == m_LootTemplates.end())
             {
                 std::pair< LootTemplateMap::iterator, bool > pr = m_LootTemplates.insert(LootTemplateMap::value_type(entry, new LootTemplate()));
                 tab = pr.first;
             }
         }
         // else is empty - template Id and iter are the same
         // finally iter refers to already existed or just created <entry, LootTemplate>
         // Adds current row to the template
         tab->second->AddEntry(storeitem);
         ++count;
     } while (result->NextRow());
     Verify();                                           // Checks validity of the loot store
     return count;
 }
References Clear(), count(), Field::GetBool(), Field::GetFloat(), Field::GetInt32(), GetName(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), LootStoreItem::IsValid(), LOG_ERROR, m_LootTemplates, max, reference(), Verify(), and WorldDatabase.
Referenced by LoadAndCollectLootIds().
ReportNonExistingId() [1/2]
void LootStore::ReportNonExistingId (uint32 lootId) const
Definition at line 286 of file LootMgr.cpp.
 {
     LOG_ERROR("sql.sql", "Table '%s' Entry %d does not exist", GetName(), lootId);
 }
References GetName(), and LOG_ERROR.
Referenced by LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
ReportNonExistingId() [2/2]
void LootStore::ReportNonExistingId (uint32 lootId, const char * ownerType, uint32 ownerId) const
Definition at line 291 of file LootMgr.cpp.
 {
     LOG_ERROR("sql.sql", "Table '%s' Entry %d does not exist but it is used by %s %d", GetName(), lootId, ownerType, ownerId);
 }
References GetName(), and LOG_ERROR.
ReportUnusedIds()
void LootStore::ReportUnusedIds (LootIdSet const & ids_set) const
Definition at line 279 of file LootMgr.cpp.
 {
     // all still listed ids isn't referenced
     for (LootIdSet::const_iterator itr = lootIdSet.begin(); itr != lootIdSet.end(); ++itr)
         LOG_ERROR("sql.sql", "Table '%s' Entry %d isn't %s and not referenced from loot, and thus useless.", GetName(), *itr, GetEntryName());
 }
References GetEntryName(), GetName(), and LOG_ERROR.
Referenced by LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
ResetConditions()
void LootStore::ResetConditions ()
Definition at line 234 of file LootMgr.cpp.
 {
     for (LootTemplateMap::iterator itr = m_LootTemplates.begin(); itr != m_LootTemplates.end(); ++itr)
     {
         ConditionList empty;
         itr->second->CopyConditions(empty);
     }
 }
References m_LootTemplates.
Referenced by ConditionMgr::LoadConditions().
Verify()
void LootStore::Verify () const
Definition at line 132 of file LootMgr.cpp.
 {
     for (LootTemplateMap::const_iterator i = m_LootTemplates.begin(); i != m_LootTemplates.end(); ++i)
         i->second->Verify(*this, i->first);
 }
References m_LootTemplates.
Referenced by LoadLootTable().
Member Data Documentation
m_entryName
char const* LootStore::m_entryName private
Definition at line 240 of file LootMgr.h.
Referenced by GetEntryName().
m_LootTemplates
LootTemplateMap LootStore::m_LootTemplates private
Definition at line 238 of file LootMgr.h.
Referenced by CheckLootRefs(), Clear(), GetLootFor(), GetLootForConditionFill(), HaveLootFor(), HaveQuestLootFor(), HaveQuestLootForPlayer(), LoadAndCollectLootIds(), LoadLootTable(), ResetConditions(), and Verify().
m_name
char const* LootStore::m_name private
Definition at line 239 of file LootMgr.h.
Referenced by GetName().
m_ratesAllowed
bool LootStore::m_ratesAllowed private
Definition at line 241 of file LootMgr.h.
Referenced by IsRatesAllowed().
The documentation for this class was generated from the following files:
src/server/game/Loot/LootMgr.h
src/server/game/Loot/LootMgr.cpp