Azerotcore-wotlk: src/common/Collision/BoundingIntervalHierarchy.h File Reference
BoundingIntervalHierarchy.h File Reference
#include "G3D/AABox.h"
#include "G3D/Ray.h"
#include "G3D/Vector3.h"
#include "Define.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <stdexcept>
#include <vector>
Classes
struct AABound
class BIH
struct BIH::buildData
struct BIH::StackNode
class BIH::BuildStats
Macros
#define MAX_STACK_SIZE 64
Functions
static uint32 floatToRawIntBits (float f)
static float intBitsToFloat (uint32 i)
Macro Definition Documentation
MAX_STACK_SIZE
#define MAX_STACK_SIZE 64
Definition at line 34 of file BoundingIntervalHierarchy.h.
Function Documentation
floatToRawIntBits()
static uint32 floatToRawIntBits (float f) inline static
Definition at line 38 of file BoundingIntervalHierarchy.h.
 {
     static_assert(sizeof(float) == sizeof(uint32), "Size of uint32 and float must be equal for this to work");
     uint32 ret;
     memcpy(&ret, &f, sizeof(float));
     return ret;
 }
References f(), memcpy, and ret.
Referenced by BIH::intersectRay(), and BIH::subdivide().
intBitsToFloat()
static float intBitsToFloat (uint32 i) inline static
Definition at line 46 of file BoundingIntervalHierarchy.h.
 {
     static_assert(sizeof(float) == sizeof(uint32), "Size of uint32 and float must be equal for this to work");
     float ret;
     memcpy(&ret, &i, sizeof(uint32));
     return ret;
 }
References memcpy, and ret.
Referenced by BIH::intersectPoint(), and BIH::intersectRay().