Azerotcore-wotlk: boss_illidari_council::boss_illidari_councilAI Struct Reference
boss_illidari_council::boss_illidari_councilAI Struct Reference
Public Member Functions
boss_illidari_councilAI (Creature *creature)
void Reset () override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void DoAction (int32 param) override
void UpdateAI (uint32) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid councilGUIDs [4]
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 145 of file illidari_council.cpp.
Constructor & Destructor Documentation
boss_illidari_councilAI()
boss_illidari_council::boss_illidari_councilAI::boss_illidari_councilAI (Creature * creature) inline
Definition at line 147 of file illidari_council.cpp.
                                                     : BossAI(creature, DATA_ILLIDARI_COUNCIL)
         {
         }
Member Function Documentation
AttackStart()
void boss_illidari_council::boss_illidari_councilAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 162 of file illidari_council.cpp.
 { }
DoAction()
void boss_illidari_council::boss_illidari_councilAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 165 of file illidari_council.cpp.
         {
             if (!me->isActiveObject() && param == ACTION_START_ENCOUNTER)
             {
                 me->setActive(true);
                 councilGUIDs[0] = instance->GetGuidData(NPC_GATHIOS_THE_SHATTERER);
                 councilGUIDs[1] = instance->GetGuidData(NPC_HIGH_NETHERMANCER_ZEREVOR);
                 councilGUIDs[2] = instance->GetGuidData(NPC_LADY_MALANDE);
                 councilGUIDs[3] = instance->GetGuidData(NPC_VERAS_DARKSHADOW);
                 bool spoken = false;
                 for (uint8 i = 0; i < 4; ++i)
                 {
                     if (Creature* member = ObjectAccessor::GetCreature(*me, councilGUIDs[i]))
                     {
                         if (!spoken && (roll_chance_i(33) || i == 3))
{
                             spoken = true;
                             member->AI()->Talk(SAY_COUNCIL_AGGRO);
                         }
                         member->SetOwnerGUID(me->GetGUID());
                         member->SetInCombatWithZone();
                     }
                 }
             }
             else if (param == ACTION_ENRAGE)
             {
                 Creature* member = nullptr;
                 for (uint8 i = 0; i < 4; ++i)
                     if ((member = ObjectAccessor::GetCreature(*me, councilGUIDs[i])))
                         member->AI()->DoAction(ACTION_ENRAGE);
             }
             else if (param == ACTION_END_ENCOUNTER)
             {
                 me->setActive(false);
                 Creature* member = nullptr;
                 for (uint8 i = 0; i < 4; ++i)
                     if ((member = ObjectAccessor::GetCreature(*me, councilGUIDs[i])))
                         if (member->IsAlive())
                             Unit::Kill(me, member);
                 Unit::Kill(me, me);
             }
         }
References ACTION_END_ENCOUNTER, ACTION_ENRAGE, ACTION_START_ENCOUNTER, Creature::AI(), councilGUIDs, UnitAI::DoAction(), ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), BossAI::instance, WorldObject::isActiveObject(), Unit::IsAlive(), Unit::Kill(), ScriptedAI::me, NPC_GATHIOS_THE_SHATTERER, NPC_HIGH_NETHERMANCER_ZEREVOR, NPC_LADY_MALANDE, NPC_VERAS_DARKSHADOW, roll_chance_i(), SAY_COUNCIL_AGGRO, and WorldObject::setActive().
MoveInLineOfSight()
void boss_illidari_council::boss_illidari_councilAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 163 of file illidari_council.cpp.
 { }
Reset()
void boss_illidari_council::boss_illidari_councilAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 153 of file illidari_council.cpp.
         {
             BossAI::Reset();
             Creature* member = nullptr;
             for (uint8 i = 0; i < 4; ++i)
                 if ((member = ObjectAccessor::GetCreature(*me, councilGUIDs[i])))
                     member->AI()->EnterEvadeMode();
         }
References Creature::AI(), councilGUIDs, CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), ScriptedAI::me, and BossAI::Reset().
UpdateAI()
void boss_illidari_council::boss_illidari_councilAI::UpdateAI (uint32) inline override virtual
Reimplemented from BossAI.
Definition at line 209 of file illidari_council.cpp.
         {
             if (!me->isActiveObject())
                 return;
             if (!SelectTargetFromPlayerList(115.0f))
             {
                 EnterEvadeMode();
                 return;
             }
             me->CastSpell(me, SPELL_EMPYREAL_BALANCE, true);
         }
References Unit::CastSpell(), CreatureAI::EnterEvadeMode(), WorldObject::isActiveObject(), ScriptedAI::me, ScriptedAI::SelectTargetFromPlayerList(), and SPELL_EMPYREAL_BALANCE.
Member Data Documentation
councilGUIDs
ObjectGuid boss_illidari_council::boss_illidari_councilAI::councilGUIDs[4]
Definition at line 151 of file illidari_council.cpp.
Referenced by DoAction(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/illidari_council.cpp