Azerotcore-wotlk: Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset > Struct Template Reference
Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset > Struct Template Reference
#include <ChatCommand.h>
Static Public Member Functions
static ChatCommandResult TryConsumeTo (Tuple &tuple, ChatHandler const *handler, std::string_view args)
Detailed Description
template<typename Tuple, typename NestedNextType, size_t offset>
struct Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >
Definition at line 76 of file ChatCommand.h.
Member Function Documentation
TryConsumeTo()
template<typename Tuple , typename NestedNextType , size_t offset> static ChatCommandResult Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >::TryConsumeTo (Tuple & tuple, ChatHandler const * handler, std::string_view args) inline static
Definition at line 78 of file ChatCommand.h.
         {
             // try with the argument
             auto& myArg = std::get<offset>(tuple);
             myArg.emplace();
             ChatCommandResult result1 = ArgInfo<NestedNextType>::TryConsume(myArg.value(), handler, args);
             if (result1)
                 if ((result1 = ConsumeFromOffset<Tuple, offset + 1>(tuple, handler, *result1)))
                     return result1;
             // try again omitting the argument
             myArg = std::nullopt;
             ChatCommandResult result2 = ConsumeFromOffset<Tuple, offset + 1>(tuple, handler, args);
             if (result2)
                 return result2;
             if (result1.HasErrorMessage() && result2.HasErrorMessage())
             {
                 return Acore::StringFormat("%s \"%s\"\n%s \"%s\"",
                     GetAcoreString(handler, LANG_CMDPARSER_EITHER), result2.GetErrorMessage().c_str(),
                     GetAcoreString(handler, LANG_CMDPARSER_OR), result1.GetErrorMessage().c_str());
             }
             else if (result1.HasErrorMessage())
                 return result1;
             else
                 return result2;
         }
References Acore::Impl::ChatCommands::GetAcoreString(), Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage(), Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage(), LANG_CMDPARSER_EITHER, LANG_CMDPARSER_OR, and Acore::StringFormat().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommand.h