Azerotcore-wotlk: OnlyOnceAreaTriggerScript Class Reference
OnlyOnceAreaTriggerScript Class Reference abstract
#include <ScriptMgr.h>
Public Member Functions
bool OnTrigger (Player *, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
virtual bool _OnTrigger (Player *, AreaTrigger const *)=0
void ResetAreaTriggerDone (InstanceScript *, uint32)
void ResetAreaTriggerDone (Player const *, AreaTrigger const *)
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Private Member Functions
AreaTriggerScript (const char *name)
Detailed Description
Definition at line 557 of file ScriptMgr.h.
Member Function Documentation
_OnTrigger()
virtual bool OnlyOnceAreaTriggerScript::_OnTrigger (Player * , AreaTrigger const *) protected pure virtual
Implemented in at_zulgurub_entrance_speech.
Referenced by OnTrigger().
AreaTriggerScript()
AreaTriggerScript::AreaTriggerScript private
Definition at line 548 of file ScriptMgr.cpp.
     : ScriptObject(name)
 {
     ScriptRegistry<AreaTriggerScript>::AddScript(this);
 }
OnTrigger()
bool OnlyOnceAreaTriggerScript::OnTrigger (Player * player, AreaTrigger const * trigger) override virtual
Reimplemented from AreaTriggerScript.
Definition at line 3250 of file ScriptMgr.cpp.
 {
     uint32 const triggerId = trigger->entry;
     if (InstanceScript* instance = player->GetInstanceScript())
     {
         if (instance->IsAreaTriggerDone(triggerId))
         {
             return true;
         }
         else
         {
             instance->MarkAreaTriggerDone(triggerId);
         }
     }
     return _OnTrigger(player, trigger);
 }
References _OnTrigger(), AreaTrigger::entry, and WorldObject::GetInstanceScript().
ResetAreaTriggerDone() [1/2]
void OnlyOnceAreaTriggerScript::ResetAreaTriggerDone (InstanceScript * script, uint32 triggerId) protected
Definition at line 3267 of file ScriptMgr.cpp.
 {
     script->ResetAreaTriggerDone(triggerId);
 }
References InstanceScript::ResetAreaTriggerDone().
Referenced by ResetAreaTriggerDone().
ResetAreaTriggerDone() [2/2]
void OnlyOnceAreaTriggerScript::ResetAreaTriggerDone (Player const * player, AreaTrigger const * trigger) protected
Definition at line 3272 of file ScriptMgr.cpp.
 {
     if (InstanceScript* instance = player->GetInstanceScript())
     {
         ResetAreaTriggerDone(instance, trigger->entry);
     }
 }
References AreaTrigger::entry, WorldObject::GetInstanceScript(), and ResetAreaTriggerDone().
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptMgr.h
src/server/game/Scripting/ScriptMgr.cpp