Azerotcore-wotlk: OutdoorPvPEP Class Reference
OutdoorPvPEP Class Reference
#include <OutdoorPvPEP.h>
Public Member Functions
OutdoorPvPEP ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPacket &data) override
void SendRemoveWorldStates (Player *player) override
void BuffTeams ()
void SetControlledState (uint32 index, TeamId teamId)
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
~OutdoorPvP () override
void DeleteSpawns ()
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId ()
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
TeamId EP_ControlsId [EP_TOWER_NUM]
uint32 m_AllianceTowersControlled
uint32 m_HordeTowersControlled
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap m_capturePoints
PlayerSet m_players [2]
uint32 m_TypeId
bool m_sendUpdate
std::map< ObjectGuid::LowType, GameObject * > m_GoScriptStore
std::map< ObjectGuid::LowType, Creature * > m_CreatureScriptStore
Map * m_map
Detailed Description
Definition at line 289 of file OutdoorPvPEP.h.
Constructor & Destructor Documentation
OutdoorPvPEP()
OutdoorPvPEP::OutdoorPvPEP ()
Definition at line 609 of file OutdoorPvPEP.cpp.
 {
     m_TypeId = OUTDOOR_PVP_EP;
     memset(EP_ControlsId, TEAM_NEUTRAL, sizeof(EP_ControlsId));
     m_AllianceTowersControlled = 0;
     m_HordeTowersControlled = 0;
 }
References EP_ControlsId, m_AllianceTowersControlled, m_HordeTowersControlled, OutdoorPvP::m_TypeId, memset, OUTDOOR_PVP_EP, and TEAM_NEUTRAL.
Member Function Documentation
BuffTeams()
void OutdoorPvPEP::BuffTeams ()
Definition at line 685 of file OutdoorPvPEP.cpp.
 {
     for (PlayerSet::iterator itr = m_players[0].begin(); itr != m_players[0].end(); ++itr)
     {
         if (Player* player = ObjectAccessor::FindPlayer(*itr))
         {
             for (int i = 0; i < 4; ++i)
                 player->RemoveAurasDueToSpell(EP_AllianceBuffs[i]);
             if (m_AllianceTowersControlled && m_AllianceTowersControlled < 5)
                 player->CastSpell(player, EP_AllianceBuffs[m_AllianceTowersControlled - 1], true);
         }
     }
     for (PlayerSet::iterator itr = m_players[1].begin(); itr != m_players[1].end(); ++itr)
     {
         if (Player* player = ObjectAccessor::FindPlayer(*itr))
         {
             for (int i = 0; i < 4; ++i)
                 player->RemoveAurasDueToSpell(EP_HordeBuffs[i]);
             if (m_HordeTowersControlled && m_HordeTowersControlled < 5)
                 player->CastSpell(player, EP_HordeBuffs[m_HordeTowersControlled - 1], true);
         }
     }
 }
References EP_AllianceBuffs, EP_HordeBuffs, ObjectAccessor::FindPlayer(), m_AllianceTowersControlled, m_HordeTowersControlled, and OutdoorPvP::m_players.
Referenced by Update().
FillInitialWorldStates()
void OutdoorPvPEP::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OutdoorPvP.
Definition at line 714 of file OutdoorPvPEP.cpp.
 {
     data << EP_UI_TOWER_COUNT_A << m_AllianceTowersControlled;
     data << EP_UI_TOWER_COUNT_H << m_HordeTowersControlled;
     data << EP_UI_TOWER_SLIDER_DISPLAY << uint32(0);
     data << EP_UI_TOWER_SLIDER_POS << uint32(50);
     data << EP_UI_TOWER_SLIDER_N << uint32(100);
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
     {
         itr->second->FillInitialWorldStates(data);
     }
 }
References EP_UI_TOWER_COUNT_A, EP_UI_TOWER_COUNT_H, EP_UI_TOWER_SLIDER_DISPLAY, EP_UI_TOWER_SLIDER_N, EP_UI_TOWER_SLIDER_POS, m_AllianceTowersControlled, OutdoorPvP::m_capturePoints, and m_HordeTowersControlled.
HandlePlayerEnterZone()
void OutdoorPvPEP::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 653 of file OutdoorPvPEP.cpp.
 {
     // add buffs
     if (player->GetTeamId() == TEAM_ALLIANCE)
     {
         if (m_AllianceTowersControlled && m_AllianceTowersControlled < 5)
             player->CastSpell(player, EP_AllianceBuffs[m_AllianceTowersControlled - 1], true);
     }
     else
     {
         if (m_HordeTowersControlled && m_HordeTowersControlled < 5)
             player->CastSpell(player, EP_HordeBuffs[m_HordeTowersControlled - 1], true);
     }
     OutdoorPvP::HandlePlayerEnterZone(player, zone);
 }
References Unit::CastSpell(), EP_AllianceBuffs, EP_HordeBuffs, Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), m_AllianceTowersControlled, m_HordeTowersControlled, and TEAM_ALLIANCE.
HandlePlayerLeaveZone()
void OutdoorPvPEP::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 669 of file OutdoorPvPEP.cpp.
 {
     // remove buffs
     if (player->GetTeamId() == TEAM_ALLIANCE)
     {
         for (int i = 0; i < 4; ++i)
             player->RemoveAurasDueToSpell(EP_AllianceBuffs[i]);
     }
     else
     {
         for (int i = 0; i < 4; ++i)
             player->RemoveAurasDueToSpell(EP_HordeBuffs[i]);
     }
     OutdoorPvP::HandlePlayerLeaveZone(player, zone);
 }
References EP_AllianceBuffs, EP_HordeBuffs, Player::GetTeamId(), OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and TEAM_ALLIANCE.
SendRemoveWorldStates()
void OutdoorPvPEP::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 727 of file OutdoorPvPEP.cpp.
 {
     player->SendUpdateWorldState(EP_UI_TOWER_COUNT_A, 0);
     player->SendUpdateWorldState(EP_UI_TOWER_COUNT_H, 0);
     player->SendUpdateWorldState(EP_UI_TOWER_SLIDER_DISPLAY, 0);
     player->SendUpdateWorldState(EP_UI_TOWER_SLIDER_POS, 0);
     player->SendUpdateWorldState(EP_UI_TOWER_SLIDER_N, 0);
     player->SendUpdateWorldState(EP_EWT_A, 0);
     player->SendUpdateWorldState(EP_EWT_H, 0);
     player->SendUpdateWorldState(EP_EWT_N, 0);
     player->SendUpdateWorldState(EP_EWT_N_A, 0);
     player->SendUpdateWorldState(EP_EWT_N_H, 0);
     player->SendUpdateWorldState(EP_PWT_A, 0);
     player->SendUpdateWorldState(EP_PWT_H, 0);
     player->SendUpdateWorldState(EP_PWT_N, 0);
     player->SendUpdateWorldState(EP_PWT_N_A, 0);
     player->SendUpdateWorldState(EP_PWT_N_H, 0);
     player->SendUpdateWorldState(EP_NPT_A, 0);
     player->SendUpdateWorldState(EP_NPT_H, 0);
     player->SendUpdateWorldState(EP_NPT_N, 0);
     player->SendUpdateWorldState(EP_NPT_N_A, 0);
     player->SendUpdateWorldState(EP_NPT_N_H, 0);
     player->SendUpdateWorldState(EP_CGT_A, 0);
     player->SendUpdateWorldState(EP_CGT_H, 0);
     player->SendUpdateWorldState(EP_CGT_N, 0);
     player->SendUpdateWorldState(EP_CGT_N_A, 0);
     player->SendUpdateWorldState(EP_CGT_N_H, 0);
 }
References EP_CGT_A, EP_CGT_H, EP_CGT_N, EP_CGT_N_A, EP_CGT_N_H, EP_EWT_A, EP_EWT_H, EP_EWT_N, EP_EWT_N_A, EP_EWT_N_H, EP_NPT_A, EP_NPT_H, EP_NPT_N, EP_NPT_N_A, EP_NPT_N_H, EP_PWT_A, EP_PWT_H, EP_PWT_N, EP_PWT_N_A, EP_PWT_N_H, EP_UI_TOWER_COUNT_A, EP_UI_TOWER_COUNT_H, EP_UI_TOWER_SLIDER_DISPLAY, EP_UI_TOWER_SLIDER_N, EP_UI_TOWER_SLIDER_POS, and Player::SendUpdateWorldState().
SetControlledState()
void OutdoorPvPEP::SetControlledState (uint32 index, TeamId teamId)
Definition at line 709 of file OutdoorPvPEP.cpp.
 {
     EP_ControlsId[index] = teamId;
 }
References EP_ControlsId, and index.
SetupOutdoorPvP()
bool OutdoorPvPEP::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
Definition at line 617 of file OutdoorPvPEP.cpp.
 {
     for (uint8 i = 0; i < EPBuffZonesNum; ++i)
         RegisterZone(EPBuffZones[i]);
     SetMapFromZone(EPBuffZones[0]);
     AddCapturePoint(new OPvPCapturePointEP_EWT(this));
     AddCapturePoint(new OPvPCapturePointEP_PWT(this));
     AddCapturePoint(new OPvPCapturePointEP_CGT(this));
     AddCapturePoint(new OPvPCapturePointEP_NPT(this));
     return true;
 }
References OutdoorPvP::AddCapturePoint(), EPBuffZones, EPBuffZonesNum, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
Update()
bool OutdoorPvPEP::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
Definition at line 632 of file OutdoorPvPEP.cpp.
 {
     if (OutdoorPvP::Update(diff))
     {
         m_AllianceTowersControlled = 0;
         m_HordeTowersControlled = 0;
         for (int i = 0; i < EP_TOWER_NUM; ++i)
         {
             if (EP_ControlsId[i] == TEAM_ALLIANCE)
                 ++m_AllianceTowersControlled;
             else if (EP_ControlsId[i] == TEAM_HORDE)
                 ++m_HordeTowersControlled;
             SendUpdateWorldState(EP_UI_TOWER_COUNT_A, m_AllianceTowersControlled);
             SendUpdateWorldState(EP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
             BuffTeams();
         }
         return true;
     }
     return false;
 }
References BuffTeams(), diff(), EP_ControlsId, EP_TOWER_NUM, EP_UI_TOWER_COUNT_A, EP_UI_TOWER_COUNT_H, m_AllianceTowersControlled, m_HordeTowersControlled, OutdoorPvP::SendUpdateWorldState(), TEAM_ALLIANCE, TEAM_HORDE, and OutdoorPvP::Update().
Member Data Documentation
EP_ControlsId
TeamId OutdoorPvPEP::EP_ControlsId[EP_TOWER_NUM] private
Definition at line 311 of file OutdoorPvPEP.h.
Referenced by OutdoorPvPEP(), SetControlledState(), and Update().
m_AllianceTowersControlled
uint32 OutdoorPvPEP::m_AllianceTowersControlled private
Definition at line 313 of file OutdoorPvPEP.h.
Referenced by BuffTeams(), FillInitialWorldStates(), HandlePlayerEnterZone(), OutdoorPvPEP(), and Update().
m_HordeTowersControlled
uint32 OutdoorPvPEP::m_HordeTowersControlled private
Definition at line 314 of file OutdoorPvPEP.h.
Referenced by BuffTeams(), FillInitialWorldStates(), HandlePlayerEnterZone(), OutdoorPvPEP(), and Update().
The documentation for this class was generated from the following files:
src/server/scripts/OutdoorPvP/OutdoorPvPEP.h
src/server/scripts/OutdoorPvP/OutdoorPvPEP.cpp