Azerotcore-wotlk: deps/mysqllite/mysys/my_thr_init.c File Reference
my_thr_init.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
#include <signal.h>
Functions
pthread_key (struct st_my_thread_var *, THR_KEY_mysys)
static uint get_thread_lib (void)
my_bool my_thread_basic_global_init (void)
void my_thread_basic_global_reinit (void)
my_bool my_thread_global_init (void)
void my_thread_global_end (void)
my_bool my_thread_init (void)
void my_thread_end (void)
struct st_my_thread_var * _my_thread_var (void)
my_thread_id my_thread_dbug_id ()
const char * my_thread_name (void)
void ** my_thread_var_dbug ()
Variables
mysql_mutex_t THR_LOCK_malloc
mysql_mutex_t THR_LOCK_open
mysql_mutex_t THR_LOCK_lock
mysql_mutex_t THR_LOCK_isam
mysql_mutex_t THR_LOCK_myisam
mysql_mutex_t THR_LOCK_heap
mysql_mutex_t THR_LOCK_net
mysql_mutex_t THR_LOCK_charset
mysql_mutex_t THR_LOCK_threads
mysql_mutex_t THR_LOCK_time
mysql_mutex_t THR_LOCK_myisam_mmap
mysql_cond_t THR_COND_threads
uint THR_thread_count = 0
uint my_thread_end_wait_time = 5
mysql_mutex_t LOCK_localtime_r
mysql_mutex_t LOCK_gethostbyname_r
static my_bool my_thread_basic_global_init_done = 0
static my_thread_id thread_id = 0
Function Documentation
_my_thread_var()
struct st_my_thread_var* _my_thread_var (void)
Definition at line 446 of file my_thr_init.c.
 {
   return  my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
 }
References my_pthread_getspecific.
get_thread_lib()
static uint get_thread_lib (void) static
Definition at line 493 of file my_thr_init.c.
 {
 #ifdef _CS_GNU_LIBPTHREAD_VERSION
   char buff[64];
   confstr(_CS_GNU_LIBPTHREAD_VERSION, buff, sizeof(buff));
   if (!strncasecmp(buff, "NPTL", 4))
     return THD_LIB_NPTL;
   if (!strncasecmp(buff, "linuxthreads", 12))
     return THD_LIB_LT;
 #endif
   return THD_LIB_OTHER;
 }
References THD_LIB_LT, THD_LIB_NPTL, and THD_LIB_OTHER.
Referenced by my_thread_global_init().
my_thread_basic_global_init()
my_bool my_thread_basic_global_init (void)
Perform a minimal initialisation of mysys, when compiled with threads. The initialisation performed is sufficient to:
allocate memory
perform file operations
use charsets
use my_errno
See also
my_basic_init
my_thread_basic_global_reinit
Definition at line 82 of file my_thr_init.c.
 {
   int pth_ret;
   if (my_thread_basic_global_init_done)
     return 0;
   my_thread_basic_global_init_done= 1;
 #ifdef PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
   /*
     Set mutex type to "fast" a.k.a "adaptive"
     In this case the thread may steal the mutex from some other thread
     that is waiting for the same mutex.  This will save us some
     context switches but may cause a thread to 'starve forever' while
     waiting for the mutex (not likely if the code within the mutex is
     short).
   */
   pthread_mutexattr_init(&my_fast_mutexattr);
   pthread_mutexattr_settype(&my_fast_mutexattr,
                             PTHREAD_MUTEX_ADAPTIVE_NP);
 #endif
 #ifdef PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP
   /*
     Set mutex type to "errorcheck"
   */
   pthread_mutexattr_init(&my_errorcheck_mutexattr);
   pthread_mutexattr_settype(&my_errorcheck_mutexattr,
                             PTHREAD_MUTEX_ERRORCHECK);
 #endif
   mysql_mutex_init(key_THR_LOCK_malloc, &THR_LOCK_malloc, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_open, &THR_LOCK_open, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_charset, &THR_LOCK_charset, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_threads, &THR_LOCK_threads, MY_MUTEX_INIT_FAST);
   if ((pth_ret= pthread_key_create(&THR_KEY_mysys, NULL)) != 0)
   {
     fprintf(stderr, "Can't initialize threads: error %d\n", pth_ret);
     return 1;
   }
   if (my_thread_init())
     return 1;
   return 0;
 }
References fprintf(), MY_MUTEX_INIT_FAST, my_thread_basic_global_init_done, my_thread_init(), mysql_mutex_init, NULL, THR_LOCK_charset, THR_LOCK_malloc, THR_LOCK_open, and THR_LOCK_threads.
Referenced by my_basic_init(), and my_thread_global_init().
my_thread_basic_global_reinit()
void my_thread_basic_global_reinit (void)
Re-initialize components initialized early with my_thread_basic_global_init. Some mutexes were initialized before the instrumentation. Destroy + create them again, now that the instrumentation is in place. This is safe, since this function() is called before creating new threads, so the mutexes are not in use.
Definition at line 139 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   DBUG_ASSERT(my_thread_basic_global_init_done);
 #ifdef HAVE_PSI_INTERFACE
   my_init_mysys_psi_keys();
 #endif
   mysql_mutex_destroy(&THR_LOCK_malloc);
   mysql_mutex_init(key_THR_LOCK_malloc, &THR_LOCK_malloc, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_open);
   mysql_mutex_init(key_THR_LOCK_open, &THR_LOCK_open, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_charset);
   mysql_mutex_init(key_THR_LOCK_charset, &THR_LOCK_charset, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_threads);
   mysql_mutex_init(key_THR_LOCK_threads, &THR_LOCK_threads, MY_MUTEX_INIT_FAST);
   tmp= my_pthread_getspecific(struct st_my_thread_var*, THR_KEY_mysys);
   DBUG_ASSERT(tmp);
   mysql_mutex_destroy(&tmp->mutex);
   mysql_mutex_init(key_my_thread_var_mutex, &tmp->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_destroy(&tmp->suspend);
   mysql_cond_init(key_my_thread_var_suspend, &tmp->suspend, NULL);
 }
References DBUG_ASSERT, st_my_thread_var::mutex, MY_MUTEX_INIT_FAST, my_pthread_getspecific, my_thread_basic_global_init_done, mysql_cond_destroy, mysql_cond_init, mysql_mutex_destroy, mysql_mutex_init, NULL, st_my_thread_var::suspend, THR_LOCK_charset, THR_LOCK_malloc, THR_LOCK_open, and THR_LOCK_threads.
my_thread_dbug_id()
my_thread_id my_thread_dbug_id (void)
Definition at line 456 of file my_thr_init.c.
 {
   return my_thread_var->id;
 }
References my_thread_var.
Referenced by my_thread_name().
my_thread_end()
void my_thread_end (void)
Definition at line 393 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   tmp= my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_end(): tmp: 0x%lx  pthread_self: 0x%lx  thread_id: %ld\n",
       (long) tmp, (long) pthread_self(), tmp ? (long) tmp->id : 0L);
 #endif
 #ifdef HAVE_PSI_INTERFACE
   /*
     Remove the instrumentation for this thread.
     This must be done before trashing st_my_thread_var,
     because the LF_HASH depends on it.
   */
   if (PSI_server)
     PSI_server->delete_current_thread();
 #endif
   if (tmp && tmp->init)
   {
 #if !defined(DBUG_OFF)
     /* tmp->dbug is allocated inside DBUG library */
     if (tmp->dbug)
     {
       DBUG_POP();
       free(tmp->dbug);
       tmp->dbug=0;
     }
 #endif
 #if !defined(__bsdi__) && !defined(__OpenBSD__)
  /* bsdi and openbsd 3.5 dumps core here */
     mysql_cond_destroy(&tmp->suspend);
 #endif
     mysql_mutex_destroy(&tmp->mutex);
     free(tmp);
     /*
       Decrement counter for number of running threads. We are using this
       in my_thread_global_end() to wait until all threads have called
       my_thread_end and thus freed all memory they have allocated in
       my_thread_init() and DBUG_xxxx
     */
     mysql_mutex_lock(&THR_LOCK_threads);
     DBUG_ASSERT(THR_thread_count != 0);
     if (--THR_thread_count == 0)
       mysql_cond_signal(&THR_COND_threads);
     mysql_mutex_unlock(&THR_LOCK_threads);
   }
   pthread_setspecific(THR_KEY_mysys,0);
 }
References st_my_thread_var::dbug, DBUG_ASSERT, DBUG_POP, fprintf(), st_my_thread_var::id, st_my_thread_var::init, st_my_thread_var::mutex, my_pthread_getspecific, mysql_cond_destroy, mysql_cond_signal, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, PSI_server, st_my_thread_var::pthread_self, st_my_thread_var::suspend, THR_COND_threads, THR_LOCK_threads, and THR_thread_count.
Referenced by my_end(), and mysql_thread_end().
my_thread_global_end()
void my_thread_global_end (void)
Definition at line 246 of file my_thr_init.c.
 {
   struct timespec abstime;
   my_bool all_threads_killed= 1;
   set_timespec(abstime, my_thread_end_wait_time);
   mysql_mutex_lock(&THR_LOCK_threads);
   while (THR_thread_count > 0)
   {
     int error= mysql_cond_timedwait(&THR_COND_threads, &THR_LOCK_threads,
                                     &abstime);
     if (error == ETIMEDOUT || error == ETIME)
     {
 #ifdef HAVE_PTHREAD_KILL
       /*
         We shouldn't give an error here, because if we don't have
         pthread_kill(), programs like mysqld can't ensure that all threads
         are killed when we enter here.
       */
       if (THR_thread_count)
         fprintf(stderr,
                 "Error in my_thread_global_end(): %d threads didn't exit\n",
                 THR_thread_count);
 #endif
       all_threads_killed= 0;
       break;
     }
   }
   mysql_mutex_unlock(&THR_LOCK_threads);
   pthread_key_delete(THR_KEY_mysys);
 #ifdef PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
   pthread_mutexattr_destroy(&my_fast_mutexattr);
 #endif
 #ifdef PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP
   pthread_mutexattr_destroy(&my_errorcheck_mutexattr);
 #endif
   mysql_mutex_destroy(&THR_LOCK_malloc);
   mysql_mutex_destroy(&THR_LOCK_open);
   mysql_mutex_destroy(&THR_LOCK_lock);
   mysql_mutex_destroy(&THR_LOCK_isam);
   mysql_mutex_destroy(&THR_LOCK_myisam);
   mysql_mutex_destroy(&THR_LOCK_myisam_mmap);
   mysql_mutex_destroy(&THR_LOCK_heap);
   mysql_mutex_destroy(&THR_LOCK_net);
   mysql_mutex_destroy(&THR_LOCK_time);
   mysql_mutex_destroy(&THR_LOCK_charset);
   if (all_threads_killed)
   {
     mysql_mutex_destroy(&THR_LOCK_threads);
     mysql_cond_destroy(&THR_COND_threads);
   }
 #if !defined(HAVE_LOCALTIME_R) || !defined(HAVE_GMTIME_R)
   mysql_mutex_destroy(&LOCK_localtime_r);
 #endif
 #ifndef HAVE_GETHOSTBYNAME_R
   mysql_mutex_destroy(&LOCK_gethostbyname_r);
 #endif
   my_thread_basic_global_init_done= 0;
 }
References error(), ETIME, fprintf(), LOCK_gethostbyname_r, LOCK_localtime_r, my_thread_basic_global_init_done, my_thread_end_wait_time, mysql_cond_destroy, mysql_cond_timedwait, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, pthread_key_delete, set_timespec, THR_COND_threads, THR_LOCK_charset, THR_LOCK_heap, THR_LOCK_isam, THR_LOCK_lock, THR_LOCK_malloc, THR_LOCK_myisam, THR_LOCK_myisam_mmap, THR_LOCK_net, THR_LOCK_open, THR_LOCK_threads, THR_LOCK_time, and THR_thread_count.
Referenced by my_end(), and my_thread_global_init().
my_thread_global_init()
my_bool my_thread_global_init (void)
Definition at line 182 of file my_thr_init.c.
 {
   if (my_thread_basic_global_init())
     return 1;
   thd_lib_detected= get_thread_lib();
 #ifdef TARGET_OS_LINUX
   /*
     BUG#24507: Race conditions inside current NPTL pthread_exit()
     implementation.
     To avoid a possible segmentation fault during concurrent
     executions of pthread_exit(), a dummy thread is spawned which
     initializes internal variables of pthread lib. See bug description
     for a full explanation.
     TODO: Remove this code when fixed versions of glibc6 are in common
     use.
   */
   if (thd_lib_detected == THD_LIB_NPTL)
   {
     pthread_t       dummy_thread;
     pthread_attr_t  dummy_thread_attr;
     pthread_attr_init(&dummy_thread_attr);
     pthread_attr_setdetachstate(&dummy_thread_attr, PTHREAD_CREATE_JOINABLE);
     if (pthread_create(&dummy_thread,&dummy_thread_attr,
                        nptl_pthread_exit_hack_handler, NULL) == 0)
       (void)pthread_join(dummy_thread, NULL);
   }
 #endif /* TARGET_OS_LINUX */
   mysql_mutex_init(key_THR_LOCK_lock, &THR_LOCK_lock, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_isam, &THR_LOCK_isam, MY_MUTEX_INIT_SLOW);
   mysql_mutex_init(key_THR_LOCK_myisam, &THR_LOCK_myisam, MY_MUTEX_INIT_SLOW);
   mysql_mutex_init(key_THR_LOCK_myisam_mmap, &THR_LOCK_myisam_mmap, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_heap, &THR_LOCK_heap, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_net, &THR_LOCK_net, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_time, &THR_LOCK_time, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_THR_COND_threads, &THR_COND_threads, NULL);
 #if !defined(HAVE_LOCALTIME_R) || !defined(HAVE_GMTIME_R)
   mysql_mutex_init(key_LOCK_localtime_r, &LOCK_localtime_r, MY_MUTEX_INIT_SLOW);
 #endif
 #ifndef HAVE_GETHOSTBYNAME_R
   mysql_mutex_init(key_LOCK_gethostbyname_r,
                    &LOCK_gethostbyname_r, MY_MUTEX_INIT_SLOW);
 #endif
 #ifdef _MSC_VER
   install_sigabrt_handler();
 #endif
   if (my_thread_init())
   {
     my_thread_global_end();         /* Clean up */
     return 1;
   }
   return 0;
 }
References get_thread_lib(), LOCK_gethostbyname_r, LOCK_localtime_r, MY_MUTEX_INIT_FAST, MY_MUTEX_INIT_SLOW, my_thread_basic_global_init(), my_thread_global_end(), my_thread_init(), mysql_cond_init, mysql_mutex_init, NULL, thd_lib_detected, THD_LIB_NPTL, THR_COND_threads, THR_LOCK_heap, THR_LOCK_isam, THR_LOCK_lock, THR_LOCK_myisam, THR_LOCK_myisam_mmap, THR_LOCK_net, and THR_LOCK_time.
Referenced by my_basic_init(), and my_init().
my_thread_init()
my_bool my_thread_init (void)
Definition at line 330 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   my_bool error=0;
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_init(): thread_id: 0x%lx\n",
           (ulong) pthread_self());
 #endif
   if (my_pthread_getspecific(struct st_my_thread_var *,THR_KEY_mysys))
   {
 #ifdef EXTRA_DEBUG_THREADS
     fprintf(stderr,"my_thread_init() called more than once in thread 0x%lx\n",
             (long) pthread_self());
 #endif
     goto end;
   }
 #ifdef _MSC_VER
   install_sigabrt_handler();
 #endif
   if (!(tmp= (struct st_my_thread_var *) calloc(1, sizeof(*tmp))))
   {
     error= 1;
     goto end;
   }
   pthread_setspecific(THR_KEY_mysys,tmp);
   tmp->pthread_self= pthread_self();
   mysql_mutex_init(key_my_thread_var_mutex, &tmp->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_my_thread_var_suspend, &tmp->suspend, NULL);
   tmp->stack_ends_here= (char*)&tmp +
                          STACK_DIRECTION * (long)my_thread_stack_size;
   mysql_mutex_lock(&THR_LOCK_threads);
   tmp->id= ++thread_id;
   ++THR_thread_count;
   mysql_mutex_unlock(&THR_LOCK_threads);
   tmp->init= 1;
 #ifndef DBUG_OFF
   /* Generate unique name for thread */
   (void) my_thread_name();
 #endif
 end:
   return error;
 }
References error(), fprintf(), st_my_thread_var::id, st_my_thread_var::init, st_my_thread_var::mutex, MY_MUTEX_INIT_FAST, my_pthread_getspecific, my_thread_name(), my_thread_stack_size, mysql_cond_init, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, NULL, st_my_thread_var::pthread_self, st_my_thread_var::stack_ends_here, st_my_thread_var::suspend, THR_LOCK_threads, THR_thread_count, and thread_id.
Referenced by my_thread_basic_global_init(), my_thread_global_init(), mysql_server_init(), and mysql_thread_init().
my_thread_name()
const char* my_thread_name (void)
Definition at line 469 of file my_thr_init.c.
 {
   char name_buff[100];
   struct st_my_thread_var *tmp=my_thread_var;
   if (!tmp->name[0])
   {
     my_thread_id id= my_thread_dbug_id();
     sprintf(name_buff,"T@%lu", (ulong) id);
     strmake(tmp->name,name_buff,THREAD_NAME_SIZE);
   }
   return tmp->name;
 }
References my_thread_dbug_id(), my_thread_var, st_my_thread_var::name, sprintf(), strmake(), and THREAD_NAME_SIZE.
Referenced by DoPrefix(), my_thread_init(), thr_alarm(), and thr_multi_unlock().
my_thread_var_dbug()
void** my_thread_var_dbug ()
Definition at line 484 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp=
     my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
   return tmp && tmp->init ? &tmp->dbug : 0;
 }
References st_my_thread_var::dbug, st_my_thread_var::init, and my_pthread_getspecific.
Referenced by code_state().
pthread_key()
pthread_key (struct st_my_thread_var * , THR_KEY_mysys)
Variable Documentation
LOCK_gethostbyname_r
mysql_mutex_t LOCK_gethostbyname_r
Definition at line 38 of file my_thr_init.c.
Referenced by my_gethostbyname_r(), my_gethostbyname_r_free(), my_thread_global_end(), and my_thread_global_init().
LOCK_localtime_r
mysql_mutex_t LOCK_localtime_r
Definition at line 35 of file my_thr_init.c.
Referenced by gmtime_r(), localtime_r(), my_thread_global_end(), and my_thread_global_init().
my_thread_basic_global_init_done
my_bool my_thread_basic_global_init_done = 0 static
True if my_thread_basic_global_init() has been called.
Definition at line 70 of file my_thr_init.c.
Referenced by my_thread_basic_global_init(), my_thread_basic_global_reinit(), and my_thread_global_end().
my_thread_end_wait_time
uint my_thread_end_wait_time = 5
Definition at line 33 of file my_thr_init.c.
Referenced by my_thread_global_end().
THR_COND_threads
mysql_cond_t THR_COND_threads
Definition at line 31 of file my_thr_init.c.
Referenced by my_thread_end(), my_thread_global_end(), and my_thread_global_init().
THR_LOCK_charset
mysql_mutex_t THR_LOCK_charset
Definition at line 28 of file my_thr_init.c.
Referenced by get_internal_charset(), my_thread_basic_global_init(), my_thread_basic_global_reinit(), and my_thread_global_end().
THR_LOCK_heap
mysql_mutex_t THR_LOCK_heap
Definition at line 27 of file my_thr_init.c.
Referenced by my_thread_global_end(), and my_thread_global_init().
THR_LOCK_isam
mysql_mutex_t THR_LOCK_isam
Definition at line 27 of file my_thr_init.c.
Referenced by my_thread_global_end(), and my_thread_global_init().
THR_LOCK_lock
mysql_mutex_t THR_LOCK_lock
Definition at line 27 of file my_thr_init.c.
Referenced by my_thread_global_end(), my_thread_global_init(), thr_lock_delete(), thr_lock_init(), and thr_print_locks().
THR_LOCK_malloc
mysql_mutex_t THR_LOCK_malloc
Definition at line 26 of file my_thr_init.c.
Referenced by my_thread_basic_global_init(), my_thread_basic_global_reinit(), and my_thread_global_end().
THR_LOCK_myisam
mysql_mutex_t THR_LOCK_myisam
Definition at line 27 of file my_thr_init.c.
Referenced by my_thread_global_end(), and my_thread_global_init().
THR_LOCK_myisam_mmap
mysql_mutex_t THR_LOCK_myisam_mmap
Definition at line 29 of file my_thr_init.c.
Referenced by my_thread_global_end(), and my_thread_global_init().
THR_LOCK_net
mysql_mutex_t THR_LOCK_net
Definition at line 28 of file my_thr_init.c.
Referenced by my_thread_global_end(), and my_thread_global_init().
THR_LOCK_open
mysql_mutex_t THR_LOCK_open
Definition at line 26 of file my_thr_init.c.
Referenced by create_temp_file(), my_close(), my_dir(), my_fclose(), my_fdopen(), my_fopen(), my_register_filename(), my_thread_basic_global_init(), my_thread_basic_global_reinit(), and my_thread_global_end().
THR_LOCK_threads
mysql_mutex_t THR_LOCK_threads
Definition at line 28 of file my_thr_init.c.
Referenced by my_thread_basic_global_init(), my_thread_basic_global_reinit(), my_thread_end(), my_thread_global_end(), and my_thread_init().
THR_LOCK_time
mysql_mutex_t THR_LOCK_time
Definition at line 28 of file my_thr_init.c.
Referenced by my_micro_time_and_time(), my_thread_global_end(), and my_thread_global_init().
THR_thread_count
uint THR_thread_count = 0
Definition at line 32 of file my_thr_init.c.
Referenced by my_thread_end(), my_thread_global_end(), and my_thread_init().
thread_id
my_thread_id thread_id = 0 static
Definition at line 308 of file my_thr_init.c.
Referenced by my_thread_init(), thr_abort_locks_for_thread(), and thr_alarm_kill().