Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/nstime.h File Reference
nstime.h File Reference
Classes
struct nstime_t
Macros
#define NSTIME_SEC_MAX KQU(18446744072)
#define NSTIME_ZERO_INITIALIZER {0}
Typedefs
typedef bool() nstime_monotonic_t(void)
typedef bool() nstime_update_t(nstime_t *)
Functions
void nstime_init (nstime_t *time, uint64_t ns)
void nstime_init2 (nstime_t *time, uint64_t sec, uint64_t nsec)
uint64_t nstime_ns (const nstime_t *time)
uint64_t nstime_sec (const nstime_t *time)
uint64_t nstime_msec (const nstime_t *time)
uint64_t nstime_nsec (const nstime_t *time)
void nstime_copy (nstime_t *time, const nstime_t *source)
int nstime_compare (const nstime_t *a, const nstime_t *b)
void nstime_add (nstime_t *time, const nstime_t *addend)
void nstime_iadd (nstime_t *time, uint64_t addend)
void nstime_subtract (nstime_t *time, const nstime_t *subtrahend)
void nstime_isubtract (nstime_t *time, uint64_t subtrahend)
void nstime_imultiply (nstime_t *time, uint64_t multiplier)
void nstime_idivide (nstime_t *time, uint64_t divisor)
uint64_t nstime_divide (const nstime_t *time, const nstime_t *divisor)
Variables
nstime_monotonic_t *JET_MUTABLE nstime_monotonic
nstime_update_t *JET_MUTABLE nstime_update
Macro Definition Documentation
NSTIME_SEC_MAX
#define NSTIME_SEC_MAX KQU(18446744072)
Definition at line 5 of file nstime.h.
NSTIME_ZERO_INITIALIZER
#define NSTIME_ZERO_INITIALIZER {0}
Definition at line 6 of file nstime.h.
Typedef Documentation
nstime_monotonic_t
typedef bool() nstime_monotonic_t(void)
Definition at line 28 of file nstime.h.
nstime_update_t
typedef bool() nstime_update_t(nstime_t *)
Definition at line 31 of file nstime.h.
Function Documentation
nstime_add()
void nstime_add (nstime_t * time, const nstime_t * addend)
Definition at line 52 of file nstime.c.
{
     assert(UINT64_MAX - time->ns >= addend->ns);
     time->ns += addend->ns;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_compare()
int nstime_compare (const nstime_t * a, const nstime_t * b)
Definition at line 47 of file nstime.c.
{
     return (a->ns > b->ns) - (a->ns < b->ns);
 }
References mpq::a, and b.
Referenced by nstime_subtract(), and nstime_update_impl().
nstime_copy()
void nstime_copy (nstime_t * time, const nstime_t * source)
Definition at line 42 of file nstime.c.
{
     *time = *source;
 }
Referenced by nstime_update_impl().
nstime_divide()
uint64_t nstime_divide (const nstime_t * time, const nstime_t * divisor)
Definition at line 95 of file nstime.c.
{
     assert(divisor->ns != 0);
     return time->ns / divisor->ns;
 }
References assert(), and nstime_t::ns.
nstime_iadd()
void nstime_iadd (nstime_t * time, uint64_t addend)
Definition at line 59 of file nstime.c.
{
     assert(UINT64_MAX - time->ns >= addend);
     time->ns += addend;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_idivide()
void nstime_idivide (nstime_t * time, uint64_t divisor)
Definition at line 88 of file nstime.c.
{
     assert(divisor != 0);
     time->ns /= divisor;
 }
References assert(), and nstime_t::ns.
nstime_imultiply()
void nstime_imultiply (nstime_t * time, uint64_t multiplier)
Definition at line 80 of file nstime.c.
{
     assert((((time->ns | multiplier) & (UINT64_MAX << (sizeof(uint64_t) <<
         2))) == 0) || ((time->ns * multiplier) / multiplier == time->ns));
     time->ns *= multiplier;
 }
References assert(), nstime_t::ns, and UINT64_MAX.
nstime_init()
void nstime_init (nstime_t * time, uint64_t ns)
Definition at line 12 of file nstime.c.
{
     time->ns = ns;
 }
References nstime_t::ns.
nstime_init2()
void nstime_init2 (nstime_t * time, uint64_t sec, uint64_t nsec)
Definition at line 17 of file nstime.c.
{
     time->ns = sec * BILLION + nsec;
 }
References BILLION, nstime_t::ns, and sec.
Referenced by nstime_get().
nstime_isubtract()
void nstime_isubtract (nstime_t * time, uint64_t subtrahend)
Definition at line 73 of file nstime.c.
{
     assert(time->ns >= subtrahend);
     time->ns -= subtrahend;
 }
References assert(), and nstime_t::ns.
nstime_msec()
uint64_t nstime_msec (const nstime_t * time)
Definition at line 27 of file nstime.c.
{
     return time->ns / MILLION;
 }
References MILLION, and nstime_t::ns.
nstime_ns()
uint64_t nstime_ns (const nstime_t * time)
Definition at line 22 of file nstime.c.
{
     return time->ns;
 }
References nstime_t::ns.
nstime_nsec()
uint64_t nstime_nsec (const nstime_t * time)
Definition at line 37 of file nstime.c.
{
     return time->ns % BILLION;
 }
References BILLION, and nstime_t::ns.
nstime_sec()
uint64_t nstime_sec (const nstime_t * time)
Definition at line 32 of file nstime.c.
{
     return time->ns / BILLION;
 }
References BILLION, and nstime_t::ns.
nstime_subtract()
void nstime_subtract (nstime_t * time, const nstime_t * subtrahend)
Definition at line 66 of file nstime.c.
{
     assert(nstime_compare(time, subtrahend) >= 0);
     time->ns -= subtrahend->ns;
 }
References assert(), nstime_t::ns, and nstime_compare().
Variable Documentation
nstime_monotonic
nstime_monotonic_t* JET_MUTABLE nstime_monotonic extern
Definition at line 153 of file nstime.c.
nstime_update
nstime_update_t* JET_MUTABLE nstime_update extern
Definition at line 170 of file nstime.c.