Azerotcore-wotlk: npc_ringo Class Reference
npc_ringo Class Reference
Classes
struct npc_ringoAI
Public Member Functions
npc_ringo ()
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 170 of file zone_ungoro_crater.cpp.
Constructor & Destructor Documentation
npc_ringo()
npc_ringo::npc_ringo () inline
Definition at line 173 of file zone_ungoro_crater.cpp.
 : CreatureScript("npc_ringo") { }
Member Function Documentation
GetAI()
CreatureAI* npc_ringo::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 189 of file zone_ungoro_crater.cpp.
     {
         return new npc_ringoAI(creature);
     }
OnQuestAccept()
bool npc_ringo::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 175 of file zone_ungoro_crater.cpp.
     {
         if (quest->GetQuestId() == QUEST_A_LITTLE_HELP)
         {
             if (npc_ringoAI* ringoAI = CAST_AI(npc_ringo::npc_ringoAI, creature->AI()))
             {
                 creature->SetStandState(UNIT_STAND_STATE_STAND);
                 ringoAI->StartFollow(player, FACTION_ESCORTEE_N_NEUTRAL_PASSIVE, quest);
             }
         }
         return true;
     }
References Creature::AI(), CAST_AI, FACTION_ESCORTEE_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_A_LITTLE_HELP, Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_ungoro_crater.cpp