Azerotcore-wotlk: src/server/game/Handlers/CalendarHandler.cpp File Reference
CalendarHandler.cpp File Reference
#include "ArenaTeamMgr.h"
#include "CalendarMgr.h"
#include "DatabaseEnv.h"
#include "DisableMgr.h"
#include "GameEventMgr.h"
#include "GuildMgr.h"
#include "InstanceSaveMgr.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Opcodes.h"
#include "Player.h"
#include "SocialMgr.h"
#include "utf8.h"
#include "WorldSession.h"
Functions
bool validUtf8String (WorldPacket &recvData, std::string &s, std::string action, ObjectGuid playerGUID)
Function Documentation
validUtf8String()
bool validUtf8String (WorldPacket & recvData, std::string & s, std::string action, ObjectGuid playerGUID)
Definition at line 226 of file CalendarHandler.cpp.
 {
     if (!utf8::is_valid(s.begin(), s.end()))
     {
         LOG_INFO("network.opcode", "CalendarHandler: Player (%s) attempt to %s an event with invalid name or description (packet modification)",
             playerGUID.ToString().c_str(), action.c_str());
         recvData.rfinish();
         return false;
     }
     return true;
 }
References utf8::is_valid(), LOG_INFO, ByteBuffer::rfinish(), and ObjectGuid::ToString().
Referenced by WorldSession::HandleCalendarAddEvent(), and WorldSession::HandleCalendarUpdateEvent().