Azerotcore-wotlk: deps/mysqllite/mysys/ptr_cmp.c File Reference
ptr_cmp.c File Reference
#include "mysys_priv.h"
#include <myisampack.h>
Macros
#define cmp(N) if (first[N] != last[N]) return (int) first[N] - (int) last[N]
Functions
static int ptr_compare (size_t *compare_length, uchar **a, uchar **b)
static int ptr_compare_0 (size_t *compare_length, uchar **a, uchar **b)
static int ptr_compare_1 (size_t *compare_length, uchar **a, uchar **b)
static int ptr_compare_2 (size_t *compare_length, uchar **a, uchar **b)
static int ptr_compare_3 (size_t *compare_length, uchar **a, uchar **b)
qsort2_cmp get_ptr_compare (size_t size)
void my_store_ptr (uchar *buff, size_t pack_length, my_off_t pos)
my_off_t my_get_ptr (uchar *ptr, size_t pack_length)
Macro Definition Documentation
cmp
#define cmp (N) if (first[N] != last[N]) return (int) first[N] - (int) last[N]
Definition at line 79 of file ptr_cmp.c.
Function Documentation
get_ptr_compare()
qsort2_cmp get_ptr_compare (size_t size)
Definition at line 59 of file ptr_cmp.c.
 {
   if (size < 4)
     return (qsort2_cmp) ptr_compare;
   switch (size & 3) {
     case 0: return (qsort2_cmp) ptr_compare_0;
     case 1: return (qsort2_cmp) ptr_compare_1;
     case 2: return (qsort2_cmp) ptr_compare_2;
     case 3: return (qsort2_cmp) ptr_compare_3;
     }
   return 0;                 /* Impossible */
 }
References ptr_compare(), ptr_compare_0(), ptr_compare_1(), ptr_compare_2(), and ptr_compare_3().
Referenced by my_string_ptr_sort().
my_get_ptr()
my_off_t my_get_ptr (uchar * ptr, size_t pack_length)
Definition at line 205 of file ptr_cmp.c.
 {
   my_off_t pos;
   switch (pack_length) {
 #if SIZEOF_OFF_T > 4
   case 8: pos= (my_off_t) mi_uint8korr(ptr); break;
   case 7: pos= (my_off_t) mi_uint7korr(ptr); break;
   case 6: pos= (my_off_t) mi_uint6korr(ptr); break;
   case 5: pos= (my_off_t) mi_uint5korr(ptr); break;
 #endif
   case 4: pos= (my_off_t) mi_uint4korr(ptr); break;
   case 3: pos= (my_off_t) mi_uint3korr(ptr); break;
   case 2: pos= (my_off_t) mi_uint2korr(ptr); break;
   case 1: pos= (my_off_t) *(uchar*) ptr; break;
   default: DBUG_ASSERT(0); return 0;
   }
  return pos;
 }
References DBUG_ASSERT, mi_uint2korr, mi_uint3korr, mi_uint4korr, mi_uint5korr, mi_uint6korr, mi_uint7korr, mi_uint8korr, pos(), and ptr().
my_store_ptr()
void my_store_ptr (uchar * buff, size_t pack_length, my_off_t pos)
Definition at line 187 of file ptr_cmp.c.
 {
   switch (pack_length) {
 #if SIZEOF_OFF_T > 4
   case 8: mi_int8store(buff,pos); break;
   case 7: mi_int7store(buff,pos); break;
   case 6: mi_int6store(buff,pos); break;
   case 5: mi_int5store(buff,pos); break;
 #endif
   case 4: mi_int4store(buff,pos); break;
   case 3: mi_int3store(buff,pos); break;
   case 2: mi_int2store(buff,pos); break;
   case 1: buff[0]= (uchar) pos; break;
   default: DBUG_ASSERT(0);
   }
   return;
 }
References DBUG_ASSERT, mi_int2store, mi_int3store, mi_int4store, mi_int5store, mi_int6store, mi_int7store, mi_int8store, and pos().
ptr_compare()
static int ptr_compare (size_t * compare_length, uchar ** a, uchar ** b) static
Definition at line 83 of file ptr_cmp.c.
 {
   reg3 int length= *compare_length;
   reg1 uchar *first,*last;
   first= *a; last= *b;
   while (--length)
   {
     if (*first++ != *last++)
       return (int) first[-1] - (int) last[-1];
   }
   return (int) first[0] - (int) last[0];
 }
References mpq::a, b, detail::first(), G3D::length(), reg1, and reg3.
Referenced by get_ptr_compare().
ptr_compare_0()
static int ptr_compare_0 (size_t * compare_length, uchar ** a, uchar ** b) static
Definition at line 98 of file ptr_cmp.c.
 {
   reg3 int length= *compare_length;
   reg1 uchar *first,*last;
   first= *a; last= *b;
  loop:
   cmp(0);
   cmp(1);
   cmp(2);
   cmp(3);
   if ((length-=4))
   {
     first+=4;
     last+=4;
     goto loop;
   }
   return (0);
 }
References mpq::a, b, cmp, detail::first(), G3D::length(), reg1, and reg3.
Referenced by get_ptr_compare().
ptr_compare_1()
static int ptr_compare_1 (size_t * compare_length, uchar ** a, uchar ** b) static
Definition at line 119 of file ptr_cmp.c.
 {
   reg3 int length= *compare_length-1;
   reg1 uchar *first,*last;
   first= *a+1; last= *b+1;
   cmp(-1);
  loop:
   cmp(0);
   cmp(1);
   cmp(2);
   cmp(3);
   if ((length-=4))
   {
     first+=4;
     last+=4;
     goto loop;
   }
   return (0);
 }
References mpq::a, b, cmp, detail::first(), G3D::length(), reg1, and reg3.
Referenced by get_ptr_compare().
ptr_compare_2()
static int ptr_compare_2 (size_t * compare_length, uchar ** a, uchar ** b) static
Definition at line 140 of file ptr_cmp.c.
 {
   reg3 int length= *compare_length-2;
   reg1 uchar *first,*last;
   first= *a +2 ; last= *b +2;
   cmp(-2);
   cmp(-1);
  loop:
   cmp(0);
   cmp(1);
   cmp(2);
   cmp(3);
   if ((length-=4))
   {
     first+=4;
     last+=4;
     goto loop;
   }
   return (0);
 }
References mpq::a, b, cmp, detail::first(), G3D::length(), reg1, and reg3.
Referenced by get_ptr_compare().
ptr_compare_3()
static int ptr_compare_3 (size_t * compare_length, uchar ** a, uchar ** b) static
Definition at line 162 of file ptr_cmp.c.
 {
   reg3 int length= *compare_length-3;
   reg1 uchar *first,*last;
   first= *a +3 ; last= *b +3;
   cmp(-3);
   cmp(-2);
   cmp(-1);
  loop:
   cmp(0);
   cmp(1);
   cmp(2);
   cmp(3);
   if ((length-=4))
   {
     first+=4;
     last+=4;
     goto loop;
   }
   return (0);
 }
References mpq::a, b, cmp, detail::first(), G3D::length(), reg1, and reg3.
Referenced by get_ptr_compare().