Azerotcore-wotlk: DBCDatabaseLoader Struct Reference
DBCDatabaseLoader Struct Reference
#include <DBCDatabaseLoader.h>
Public Member Functions
DBCDatabaseLoader (char const *dbTable, char const *dbcFormatString, std::vector< char * > &stringPool)
char * Load (uint32 &records, char **&indexTable)
Private Member Functions
char * CloneStringToPool (std::string const &str)
DBCDatabaseLoader (DBCDatabaseLoader const &right)=delete
DBCDatabaseLoader & operator= (DBCDatabaseLoader const &right)=delete
Private Attributes
char const * _sqlTableName
char const * _dbcFormat
int32 _sqlIndexPos
uint32 _recordSize
std::vector< char * > & _stringPool
Detailed Description
Definition at line 25 of file DBCDatabaseLoader.h.
Constructor & Destructor Documentation
DBCDatabaseLoader() [1/2]
DBCDatabaseLoader::DBCDatabaseLoader (char const * dbTable, char const * dbcFormatString, std::vector< char * > & stringPool)
Definition at line 23 of file DBCDatabaseLoader.cpp.
     : _sqlTableName(tableName),
       _dbcFormat(dbcFormatString),
       _sqlIndexPos(0),
       _recordSize(0),
       _stringPool(stringPool)
 {
     // Get sql index position
     int32 indexPos = -1;
     _recordSize = DBCFileLoader::GetFormatRecordSize(_dbcFormat, &indexPos);
     ASSERT(_recordSize);
 }
References _dbcFormat, _recordSize, ASSERT, and DBCFileLoader::GetFormatRecordSize().
DBCDatabaseLoader() [2/2]
DBCDatabaseLoader::DBCDatabaseLoader (DBCDatabaseLoader const & right) private delete
Member Function Documentation
CloneStringToPool()
char * DBCDatabaseLoader::CloneStringToPool (std::string const & str) private
Definition at line 131 of file DBCDatabaseLoader.cpp.
 {
     char* buf = new char[str.size() + 1];
     memcpy(buf, str.c_str(), str.size() + 1);
     _stringPool.push_back(buf);
     return buf;
 }
References _stringPool.
Referenced by Load().
Load()
char * DBCDatabaseLoader::Load (uint32 & records, char **& indexTable)
Definition at line 37 of file DBCDatabaseLoader.cpp.
 {
     std::string query = Acore::StringFormat("SELECT * FROM `%s` ORDER BY `ID` DESC", _sqlTableName);
     // no error if empty set
     QueryResult result = WorldDatabase.Query(query.c_str());
     if (!result)
         return nullptr;
     // Check if sql index pos is valid
     if (int32(result->GetFieldCount() - 1) < _sqlIndexPos)
     {
         ASSERT(false, "Invalid index pos for dbc: '%s'", _sqlTableName);
         return nullptr;
     }
     // Resize index table
     // database query *MUST* contain ORDER BY `index_field` DESC clause
     uint32 indexTableSize = std::max(records, (*result)[_sqlIndexPos].GetUInt32() + 1);
     if (indexTableSize > records)
     {
         char** tmpIdxTable = new char* [indexTableSize];
         memset(tmpIdxTable, 0, indexTableSize * sizeof(char*));
         memcpy(tmpIdxTable, indexTable, records * sizeof(char*));
         delete[] indexTable;
         indexTable = tmpIdxTable;
     }
     std::unique_ptr<char[]> dataTable = std::make_unique<char[]>(result->GetRowCount() * _recordSize);
     std::unique_ptr<uint32[]> newIndexes = std::make_unique<uint32[]>(result->GetRowCount());
     uint32 newRecords = 0;
     // Insert sql data into the data array
     do
     {
         Field* fields = result->Fetch();
         uint32 indexValue = fields[_sqlIndexPos].GetUInt32();
         char* dataValue = indexTable[indexValue];
         // If exist in DBC file override from DB
         newIndexes[newRecords] = indexValue;
         dataValue = &dataTable[newRecords++ * _recordSize];
         uint32 dataOffset = 0;
         uint32 sqlColumnNumber = 0;
         char const* dbcFormat = _dbcFormat;
         for (; (*dbcFormat); ++dbcFormat)
         {
             switch (*dbcFormat)
             {
                 case FT_FLOAT:
                     *reinterpret_cast<float*>(&dataValue[dataOffset]) = fields[sqlColumnNumber].GetFloat();
                     dataOffset += sizeof(float);
                     break;
                 case FT_IND:
                 case FT_INT:
                     *reinterpret_cast<uint32*>(&dataValue[dataOffset]) = fields[sqlColumnNumber].GetUInt32();
                     dataOffset += sizeof(uint32);
                     break;
                 case FT_BYTE:
                     *reinterpret_cast<uint8*>(&dataValue[dataOffset]) = fields[sqlColumnNumber].GetUInt8();
                     dataOffset += sizeof(uint8);
                     break;
                 case FT_STRING:
                     *reinterpret_cast<char**>(&dataValue[dataOffset]) = CloneStringToPool(fields[sqlColumnNumber].GetString());
                     dataOffset += sizeof(char*);
                     break;
                 case FT_SORT:
                 case FT_NA:
                     break;
                 default:
                     ASSERT(false, "Unsupported data type '%c' in table '%s'", *dbcFormat, _sqlTableName);
                     return nullptr;
             }
             ++sqlColumnNumber;
         }
         ASSERT(sqlColumnNumber == result->GetFieldCount(), "SQL format string does not match database for table: '%s'", _sqlTableName);
         ASSERT(dataOffset == _recordSize);
     } while (result->NextRow());
     ASSERT(newRecords == result->GetRowCount());
     // insert new records to index table
     for (uint32 i = 0; i < newRecords; ++i)
         indexTable[newIndexes[i]] = &dataTable[i * _recordSize];
     records = indexTableSize;
     return dataTable.release();
 }
References _dbcFormat, _recordSize, _sqlIndexPos, _sqlTableName, ASSERT, CloneStringToPool(), FT_BYTE, FT_FLOAT, FT_IND, FT_INT, FT_NA, FT_SORT, FT_STRING, Field::GetUInt32(), Acore::StringFormat(), and WorldDatabase.
operator=()
DBCDatabaseLoader& DBCDatabaseLoader::operator= (DBCDatabaseLoader const & right) private delete
Member Data Documentation
_dbcFormat
char const* DBCDatabaseLoader::_dbcFormat private
Definition at line 33 of file DBCDatabaseLoader.h.
Referenced by DBCDatabaseLoader(), and Load().
_recordSize
uint32 DBCDatabaseLoader::_recordSize private
Definition at line 35 of file DBCDatabaseLoader.h.
Referenced by DBCDatabaseLoader(), and Load().
_sqlIndexPos
int32 DBCDatabaseLoader::_sqlIndexPos private
Definition at line 34 of file DBCDatabaseLoader.h.
Referenced by Load().
_sqlTableName
char const* DBCDatabaseLoader::_sqlTableName private
Definition at line 32 of file DBCDatabaseLoader.h.
Referenced by Load().
_stringPool
std::vector<char*>& DBCDatabaseLoader::_stringPool private
Definition at line 36 of file DBCDatabaseLoader.h.
Referenced by CloneStringToPool().
The documentation for this struct was generated from the following files:
src/server/shared/DataStores/DBCDatabaseLoader.h
src/server/shared/DataStores/DBCDatabaseLoader.cpp