Azerotcore-wotlk: boss_anubrekhan::boss_anubrekhanAI Struct Reference
boss_anubrekhan::boss_anubrekhanAI Struct Reference
Public Member Functions
boss_anubrekhanAI (Creature *c)
void SummonCryptGuards ()
void Reset () override
void JustSummoned (Creature *cr) override
void SummonedCreatureDies (Creature *cr, Unit *) override
void SummonedCreatureDespawn (Creature *cr) override
void JustDied (Unit *killer) override
void KilledUnit (Unit *victim) override
void EnterCombat (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
bool sayGreet
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 73 of file boss_anubrekhan.cpp.
Constructor & Destructor Documentation
boss_anubrekhanAI()
boss_anubrekhan::boss_anubrekhanAI::boss_anubrekhanAI (Creature * c) inline explicit
Definition at line 75 of file boss_anubrekhan.cpp.
                                                 : BossAI(c, BOSS_ANUB), summons(me)
         {
             pInstance = c->GetInstanceScript();
             sayGreet = false;
         }
References mpq::c, pInstance, and sayGreet.
Member Function Documentation
EnterCombat()
void boss_anubrekhan::boss_anubrekhanAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 160 of file boss_anubrekhan.cpp.
         {
             BossAI::EnterCombat(who);
             me->CallForHelp(30.0f);
             Talk(SAY_AGGRO);
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_ANUB_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
             }
             events.ScheduleEvent(EVENT_IMPALE, 15000);
             events.ScheduleEvent(EVENT_LOCUST_SWARM, urand(70000, 120000));
             events.ScheduleEvent(EVENT_BERSERK, 600000);
             if (!summons.HasEntry(NPC_CRYPT_GUARD))
             {
                 SummonCryptGuards();
             }
             if (!Is25ManRaid())
             {
                 events.ScheduleEvent(EVENT_SPAWN_GUARD, urand(15000, 20000));
             }
         }
References Creature::CallForHelp(), DATA_ANUB_GATE, BossAI::EnterCombat(), EVENT_BERSERK, EVENT_IMPALE, EVENT_LOCUST_SWARM, EVENT_SPAWN_GUARD, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_READY, SummonList::HasEntry(), ScriptedAI::Is25ManRaid(), ScriptedAI::me, NPC_CRYPT_GUARD, pInstance, SAY_AGGRO, SummonCryptGuards(), summons, CreatureAI::Talk(), and urand().
JustDied()
void boss_anubrekhan::boss_anubrekhanAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 137 of file boss_anubrekhan.cpp.
         {
             BossAI::JustDied(killer);
             summons.DespawnAll();
             if (pInstance)
             {
                 pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
             }
         }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, SummonList::DespawnAll(), InstanceScript::DoStartTimedAchievement(), BossAI::JustDied(), pInstance, and summons.
JustSummoned()
void boss_anubrekhan::boss_anubrekhanAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from BossAI.
Definition at line 110 of file boss_anubrekhan.cpp.
         {
             if (me->IsInCombat())
             {
                 cr->SetInCombatWithZone();
                 if (cr->GetEntry() == NPC_CRYPT_GUARD)
                 {
                     cr->AI()->Talk(EMOTE_SPAWN, me);
                 }
             }
             summons.Summon(cr);
         }
References Creature::AI(), EMOTE_SPAWN, Object::GetEntry(), Unit::IsInCombat(), ScriptedAI::me, NPC_CRYPT_GUARD, Creature::SetInCombatWithZone(), SummonList::Summon(), summons, and CreatureAI::Talk().
KilledUnit()
void boss_anubrekhan::boss_anubrekhanAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 147 of file boss_anubrekhan.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
             victim->CastSpell(victim, SPELL_SUMMON_CORPSE_SCRABS_5, true, nullptr, nullptr, me->GetGUID());
             if (pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References Unit::CastSpell(), DATA_IMMORTAL_FAIL, Object::GetGUID(), Object::GetTypeId(), ScriptedAI::me, pInstance, SAY_SLAY, ZoneScript::SetData(), SPELL_SUMMON_CORPSE_SCRABS_5, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_anubrekhan::boss_anubrekhanAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 185 of file boss_anubrekhan.cpp.
         {
             if (!sayGreet && who->GetTypeId() == TYPEID_PLAYER)
             {
                 Talk(SAY_GREET);
                 sayGreet = true;
             }
             ScriptedAI::MoveInLineOfSight(who);
         }
References Object::GetTypeId(), CreatureAI::MoveInLineOfSight(), SAY_GREET, sayGreet, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_anubrekhan::boss_anubrekhanAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 95 of file boss_anubrekhan.cpp.
         {
             BossAI::Reset();
             events.Reset();
             summons.DespawnAll();
             SummonCryptGuards();
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_ANUB_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
             }
         }
References DATA_ANUB_GATE, SummonList::DespawnAll(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, ScriptedAI::me, pInstance, BossAI::Reset(), SummonCryptGuards(), and summons.
SummonCryptGuards()
void boss_anubrekhan::boss_anubrekhanAI::SummonCryptGuards () inline
Definition at line 86 of file boss_anubrekhan.cpp.
         {
             if (Is25ManRaid())
             {
                 me->SummonCreature(NPC_CRYPT_GUARD, 3299.732f, -3502.489f, 287.077f, 2.378f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 60000);
                 me->SummonCreature(NPC_CRYPT_GUARD, 3299.086f, -3450.929f, 287.077f, 3.999f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 60000);
             }
         }
References ScriptedAI::Is25ManRaid(), ScriptedAI::me, NPC_CRYPT_GUARD, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by EnterCombat(), and Reset().
SummonedCreatureDespawn()
void boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from BossAI.
Definition at line 132 of file boss_anubrekhan.cpp.
         {
             summons.Despawn(cr);
         }
References SummonList::Despawn(), and summons.
SummonedCreatureDies()
void boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDies (Creature * cr, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 123 of file boss_anubrekhan.cpp.
         {
             if (cr->GetEntry() == NPC_CRYPT_GUARD)
             {
                 cr->CastSpell(cr, SPELL_SUMMON_CORPSE_SCRABS_10, true, nullptr, nullptr, me->GetGUID());
                 cr->AI()->Talk(EMOTE_SCARAB);
             }
         }
References Creature::AI(), Unit::CastSpell(), EMOTE_SCARAB, Object::GetEntry(), Object::GetGUID(), ScriptedAI::me, NPC_CRYPT_GUARD, SPELL_SUMMON_CORPSE_SCRABS_10, and CreatureAI::Talk().
UpdateAI()
void boss_anubrekhan::boss_anubrekhanAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 195 of file boss_anubrekhan.cpp.
         {
             if (!me->IsInCombat() && sayGreet)
             {
                 for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 {
                     if (pInstance)
                     {
                         if (Creature* cr = pInstance->instance->GetCreature(*itr))
{
                             if (cr->IsInCombat())
                                 DoZoneInCombat();
                         }
                     }
                 }
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_IMPALE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                     {
                         me->CastSpell(target, RAID_MODE(SPELL_IMPALE_10, SPELL_IMPALE_25), false);
                     }
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_LOCUST_SWARM:
                     Talk(EMOTE_LOCUST);
                     me->CastSpell(me, RAID_MODE(SPELL_LOCUST_SWARM_10, SPELL_LOCUST_SWARM_25), false);
                     events.ScheduleEvent(EVENT_SPAWN_GUARD, 3000);
                     events.RepeatEvent(90000);
                     break;
                 case EVENT_SPAWN_GUARD:
                     me->SummonCreature(NPC_CRYPT_GUARD, 3331.217f, -3476.607f, 287.074f, 3.269f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 60000);
                     break;
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References SummonList::begin(), Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::DoZoneInCombat(), EMOTE_LOCUST, SummonList::end(), EVENT_BERSERK, EVENT_IMPALE, EVENT_LOCUST_SWARM, EVENT_SPAWN_GUARD, Map::GetCreature(), Unit::HasUnitState(), InstanceScript::instance, Unit::IsInCombat(), ScriptedAI::me, NPC_CRYPT_GUARD, pInstance, ScriptedAI::RAID_MODE(), sayGreet, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BERSERK, SPELL_IMPALE_10, SPELL_IMPALE_25, SPELL_LOCUST_SWARM_10, SPELL_LOCUST_SWARM_25, WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_anubrekhan::boss_anubrekhanAI::events
Definition at line 82 of file boss_anubrekhan.cpp.
pInstance
InstanceScript* boss_anubrekhan::boss_anubrekhanAI::pInstance
Definition at line 81 of file boss_anubrekhan.cpp.
Referenced by boss_anubrekhanAI(), EnterCombat(), JustDied(), KilledUnit(), Reset(), and UpdateAI().
sayGreet
bool boss_anubrekhan::boss_anubrekhanAI::sayGreet
Definition at line 84 of file boss_anubrekhan.cpp.
Referenced by boss_anubrekhanAI(), MoveInLineOfSight(), and UpdateAI().
summons
SummonList boss_anubrekhan::boss_anubrekhanAI::summons
Definition at line 83 of file boss_anubrekhan.cpp.
Referenced by EnterCombat(), JustDied(), JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp