Azerotcore-wotlk: deps/zlib/infback.c File Reference
infback.c File Reference
#include "zutil.h"
#include "inftrees.h"
#include "inflate.h"
#include "inffast.h"
#include "inffixed.h"
Macros
#define LOAD()
#define RESTORE()
#define INITBITS()
#define PULL()
#define PULLBYTE()
#define NEEDBITS(n)
#define BITS(n) ((unsigned)hold & ((1U << (n)) - 1))
#define DROPBITS(n)
#define BYTEBITS()
#define ROOM()
Functions
void fixedtables OF ((struct inflate_state FAR *state))
int ZEXPORT inflateBackInit_ (z_streamp strm, int windowBits, unsigned char FAR *window, const char *version, int stream_size)
void fixedtables (struct inflate_state FAR *state)
int ZEXPORT inflateBack (z_streamp strm, in_func in, void FAR *in_desc, out_func out, void FAR *out_desc)
int ZEXPORT inflateBackEnd (z_streamp strm)
Macro Definition Documentation
BITS
#define BITS (n) ((unsigned)hold & ((1U << (n)) - 1))
Definition at line 190 of file infback.c.
BYTEBITS
#define BYTEBITS ()
Value:
    do { \
        hold >>= bits & 7; \
        bits -= bits & 7; \
    } while (0)
Definition at line 201 of file infback.c.
DROPBITS
#define DROPBITS (n)
Value:
    do { \
        hold >>= (n); \
        bits -= (unsigned)(n); \
    } while (0)
Definition at line 194 of file infback.c.
INITBITS
#define INITBITS ()
Value:
    do { \
        hold = 0; \
        bits = 0; \
    } while (0)
Definition at line 150 of file infback.c.
LOAD
#define LOAD ()
Value:
    do { \
        put = strm->next_out; \
        left = strm->avail_out; \
        next = strm->next_in; \
        have = strm->avail_in; \
        hold = state->hold; \
        bits = state->bits; \
    } while (0)
Definition at line 128 of file infback.c.
NEEDBITS
#define NEEDBITS (n)
Value:
    do { \
        while (bits < (unsigned)(n)) \
            PULLBYTE(); \
    } while (0)
Definition at line 183 of file infback.c.
PULL
#define PULL ()
Value:
    do { \
        if (have == 0) { \
            have = in(in_desc, &next); \
            if (have == 0) { \
                next = Z_NULL; \
                ret = Z_BUF_ERROR; \
                goto inf_leave; \
            } \
        } \
    } while (0)
Definition at line 158 of file infback.c.
PULLBYTE
#define PULLBYTE ()
Value:
    do { \
        PULL(); \
        have--; \
        hold += (unsigned long)(*next++) << bits; \
        bits += 8; \
    } while (0)
Definition at line 172 of file infback.c.
RESTORE
#define RESTORE ()
Value:
    do { \
        strm->next_out = put; \
        strm->avail_out = left; \
        strm->next_in = next; \
        strm->avail_in = have; \
        state->hold = hold; \
        state->bits = bits; \
    } while (0)
Definition at line 139 of file infback.c.
ROOM
#define ROOM ()
Value:
    do { \
        if (left == 0) { \
            put = state->window; \
            left = state->wsize; \
            state->whave = left; \
            if (out(out_desc, put, left)) { \
                ret = Z_BUF_ERROR; \
                goto inf_leave; \
            } \
        } \
    } while (0)
Definition at line 210 of file infback.c.
Function Documentation
fixedtables()
void fixedtables (struct inflate_state FAR * state)
Definition at line 82 of file infback.c.
 {
 #ifdef BUILDFIXED
     static int virgin = 1;
     static code *lenfix, *distfix;
     static code fixed[544];
     /* build fixed huffman tables if first call (may not be thread safe) */
     if (virgin) {
         unsigned sym, bits;
         static code *next;
         /* literal/length table */
         sym = 0;
         while (sym < 144) state->lens[sym++] = 8;
         while (sym < 256) state->lens[sym++] = 9;
         while (sym < 280) state->lens[sym++] = 7;
         while (sym < 288) state->lens[sym++] = 8;
         next = fixed;
         lenfix = next;
         bits = 9;
         inflate_table(LENS, state->lens, 288, &(next), &(bits), state->work);
         /* distance table */
         sym = 0;
         while (sym < 32) state->lens[sym++] = 5;
         distfix = next;
         bits = 5;
         inflate_table(DISTS, state->lens, 32, &(next), &(bits), state->work);
         /* do this just once */
         virgin = 0;
     }
 #else /* !BUILDFIXED */
 #   include "inffixed.h"
 #endif /* BUILDFIXED */
     state->lencode = lenfix;
     state->lenbits = 9;
     state->distcode = distfix;
     state->distbits = 5;
 }
References G3D::bits(), inflate_state::distbits, inflate_state::distcode, distfix, DISTS, fixed, inflate_table(), inflate_state::lenbits, inflate_state::lencode, lenfix, inflate_state::lens, LENS, next(), and inflate_state::work.
Referenced by inflateBack().
inflateBack()
int ZEXPORT inflateBack (z_streamp strm, in_func in, void FAR * in_desc, out_func out, void FAR * out_desc)
Definition at line 250 of file infback.c.
 {
     struct inflate_state FAR *state;
     unsigned char FAR *next;    /* next input */
     unsigned char FAR *put;     /* next output */
     unsigned have, left;        /* available input and output */
     unsigned long hold;         /* bit buffer */
     unsigned bits;              /* bits in bit buffer */
     unsigned copy;              /* number of stored or match bytes to copy */
     unsigned char FAR *from;    /* where to copy match bytes from */
     code here;                  /* current decoding table entry */
     code last;                  /* parent table entry */
     unsigned len;               /* length to copy for repeats, bits to drop */
     int ret;                    /* return code */
     static const unsigned short order[19] = /* permutation of code lengths */
         {16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15};
     /* Check that the strm exists and that the state was initialized */
     if (strm == Z_NULL || strm->state == Z_NULL)
         return Z_STREAM_ERROR;
     state = (struct inflate_state FAR *)strm->state;
     /* Reset the state */
     strm->msg = Z_NULL;
     state->mode = TYPE;
     state->last = 0;
     state->whave = 0;
     next = strm->next_in;
     have = next != Z_NULL ? strm->avail_in : 0;
     hold = 0;
     bits = 0;
     put = state->window;
     left = state->wsize;
     /* Inflate until end of block marked as last */
     for (;;)
         switch (state->mode) {
         case TYPE:
             /* determine and dispatch block type */
             if (state->last) {
                 BYTEBITS();
                 state->mode = DONE;
                 break;
             }
             NEEDBITS(3);
             state->last = BITS(1);
             DROPBITS(1);
             switch (BITS(2)) {
             case 0:                             /* stored block */
                 Tracev((stderr, "inflate:     stored block%s\n",
                         state->last ? " (last)" : ""));
                 state->mode = STORED;
                 break;
             case 1:                             /* fixed block */
                 fixedtables(state);
                 Tracev((stderr, "inflate:     fixed codes block%s\n",
                         state->last ? " (last)" : ""));
                 state->mode = LEN;              /* decode codes */
                 break;
             case 2:                             /* dynamic block */
                 Tracev((stderr, "inflate:     dynamic codes block%s\n",
                         state->last ? " (last)" : ""));
                 state->mode = TABLE;
                 break;
             case 3:
                 strm->msg = (char *)"invalid block type";
                 state->mode = BAD;
             }
             DROPBITS(2);
             break;
         case STORED:
             /* get and verify stored block length */
             BYTEBITS();                         /* go to byte boundary */
             NEEDBITS(32);
             if ((hold & 0xffff) != ((hold >> 16) ^ 0xffff)) {
                 strm->msg = (char *)"invalid stored block lengths";
                 state->mode = BAD;
                 break;
             }
             state->length = (unsigned)hold & 0xffff;
             Tracev((stderr, "inflate:       stored length %u\n",
                     state->length));
             INITBITS();
             /* copy stored block from input to output */
             while (state->length != 0) {
                 copy = state->length;
                 PULL();
                 ROOM();
                 if (copy > have) copy = have;
                 if (copy > left) copy = left;
                 zmemcpy(put, next, copy);
                 have -= copy;
                 next += copy;
                 left -= copy;
                 put += copy;
                 state->length -= copy;
             }
             Tracev((stderr, "inflate:       stored end\n"));
             state->mode = TYPE;
             break;
         case TABLE:
             /* get dynamic table entries descriptor */
             NEEDBITS(14);
             state->nlen = BITS(5) + 257;
             DROPBITS(5);
             state->ndist = BITS(5) + 1;
             DROPBITS(5);
             state->ncode = BITS(4) + 4;
             DROPBITS(4);
 #ifndef PKZIP_BUG_WORKAROUND
             if (state->nlen > 286 || state->ndist > 30) {
                 strm->msg = (char *)"too many length or distance symbols";
                 state->mode = BAD;
                 break;
             }
 #endif
             Tracev((stderr, "inflate:       table sizes ok\n"));
             /* get code length code lengths (not a typo) */
             state->have = 0;
             while (state->have < state->ncode) {
                 NEEDBITS(3);
                 state->lens[order[state->have++]] = (unsigned short)BITS(3);
                 DROPBITS(3);
             }
             while (state->have < 19)
                 state->lens[order[state->have++]] = 0;
             state->next = state->codes;
             state->lencode = (code const FAR *)(state->next);
             state->lenbits = 7;
             ret = inflate_table(CODES, state->lens, 19, &(state->next),
                                 &(state->lenbits), state->work);
             if (ret) {
                 strm->msg = (char *)"invalid code lengths set";
                 state->mode = BAD;
                 break;
             }
             Tracev((stderr, "inflate:       code lengths ok\n"));
             /* get length and distance code code lengths */
             state->have = 0;
             while (state->have < state->nlen + state->ndist) {
                 for (;;) {
                     here = state->lencode[BITS(state->lenbits)];
                     if ((unsigned)(here.bits) <= bits) break;
                     PULLBYTE();
                 }
                 if (here.val < 16) {
                     DROPBITS(here.bits);
                     state->lens[state->have++] = here.val;
                 }
                 else {
                     if (here.val == 16) {
                         NEEDBITS(here.bits + 2);
                         DROPBITS(here.bits);
                         if (state->have == 0) {
                             strm->msg = (char *)"invalid bit length repeat";
                             state->mode = BAD;
                             break;
                         }
                         len = (unsigned)(state->lens[state->have - 1]);
                         copy = 3 + BITS(2);
                         DROPBITS(2);
                     }
                     else if (here.val == 17) {
                         NEEDBITS(here.bits + 3);
                         DROPBITS(here.bits);
                         len = 0;
                         copy = 3 + BITS(3);
                         DROPBITS(3);
                     }
                     else {
                         NEEDBITS(here.bits + 7);
                         DROPBITS(here.bits);
                         len = 0;
                         copy = 11 + BITS(7);
                         DROPBITS(7);
                     }
                     if (state->have + copy > state->nlen + state->ndist) {
                         strm->msg = (char *)"invalid bit length repeat";
                         state->mode = BAD;
                         break;
                     }
                     while (copy--)
                         state->lens[state->have++] = (unsigned short)len;
                 }
             }
             /* handle error breaks in while */
             if (state->mode == BAD) break;
             /* check for end-of-block code (better have one) */
             if (state->lens[256] == 0) {
                 strm->msg = (char *)"invalid code -- missing end-of-block";
                 state->mode = BAD;
                 break;
             }
             /* build code tables -- note: do not change the lenbits or distbits
                values here (9 and 6) without reading the comments in inftrees.h
                concerning the ENOUGH constants, which depend on those values */
             state->next = state->codes;
             state->lencode = (code const FAR *)(state->next);
             state->lenbits = 9;
             ret = inflate_table(LENS, state->lens, state->nlen, &(state->next),
                                 &(state->lenbits), state->work);
             if (ret) {
                 strm->msg = (char *)"invalid literal/lengths set";
                 state->mode = BAD;
                 break;
             }
             state->distcode = (code const FAR *)(state->next);
             state->distbits = 6;
             ret = inflate_table(DISTS, state->lens + state->nlen, state->ndist,
                             &(state->next), &(state->distbits), state->work);
             if (ret) {
                 strm->msg = (char *)"invalid distances set";
                 state->mode = BAD;
                 break;
             }
             Tracev((stderr, "inflate:       codes ok\n"));
             state->mode = LEN;
         case LEN:
             /* use inflate_fast() if we have enough input and output */
             if (have >= 6 && left >= 258) {
                 RESTORE();
                 if (state->whave < state->wsize)
                     state->whave = state->wsize - left;
                 inflate_fast(strm, state->wsize);
                 LOAD();
                 break;
             }
             /* get a literal, length, or end-of-block code */
             for (;;) {
                 here = state->lencode[BITS(state->lenbits)];
                 if ((unsigned)(here.bits) <= bits) break;
                 PULLBYTE();
             }
             if (here.op && (here.op & 0xf0) == 0) {
                 last = here;
                 for (;;) {
                     here = state->lencode[last.val +
                             (BITS(last.bits + last.op) >> last.bits)];
                     if ((unsigned)(last.bits + here.bits) <= bits) break;
                     PULLBYTE();
                 }
                 DROPBITS(last.bits);
             }
             DROPBITS(here.bits);
             state->length = (unsigned)here.val;
             /* process literal */
             if (here.op == 0) {
                 Tracevv((stderr, here.val >= 0x20 && here.val < 0x7f ?
                         "inflate:         literal '%c'\n" :
                         "inflate:         literal 0x%02x\n", here.val));
                 ROOM();
                 *put++ = (unsigned char)(state->length);
                 left--;
                 state->mode = LEN;
                 break;
             }
             /* process end of block */
             if (here.op & 32) {
                 Tracevv((stderr, "inflate:         end of block\n"));
                 state->mode = TYPE;
                 break;
             }
             /* invalid code */
             if (here.op & 64) {
                 strm->msg = (char *)"invalid literal/length code";
                 state->mode = BAD;
                 break;
             }
             /* length code -- get extra bits, if any */
             state->extra = (unsigned)(here.op) & 15;
             if (state->extra != 0) {
                 NEEDBITS(state->extra);
                 state->length += BITS(state->extra);
                 DROPBITS(state->extra);
             }
             Tracevv((stderr, "inflate:         length %u\n", state->length));
             /* get distance code */
             for (;;) {
                 here = state->distcode[BITS(state->distbits)];
                 if ((unsigned)(here.bits) <= bits) break;
                 PULLBYTE();
             }
             if ((here.op & 0xf0) == 0) {
                 last = here;
                 for (;;) {
                     here = state->distcode[last.val +
                             (BITS(last.bits + last.op) >> last.bits)];
                     if ((unsigned)(last.bits + here.bits) <= bits) break;
                     PULLBYTE();
                 }
                 DROPBITS(last.bits);
             }
             DROPBITS(here.bits);
             if (here.op & 64) {
                 strm->msg = (char *)"invalid distance code";
                 state->mode = BAD;
                 break;
             }
             state->offset = (unsigned)here.val;
             /* get distance extra bits, if any */
             state->extra = (unsigned)(here.op) & 15;
             if (state->extra != 0) {
                 NEEDBITS(state->extra);
                 state->offset += BITS(state->extra);
                 DROPBITS(state->extra);
             }
             if (state->offset > state->wsize - (state->whave < state->wsize ?
                                                 left : 0)) {
                 strm->msg = (char *)"invalid distance too far back";
                 state->mode = BAD;
                 break;
             }
             Tracevv((stderr, "inflate:         distance %u\n", state->offset));
             /* copy match from window to output */
             do {
                 ROOM();
                 copy = state->wsize - state->offset;
                 if (copy < left) {
                     from = put + copy;
                     copy = left - copy;
                 }
                 else {
                     from = put - state->offset;
                     copy = left;
                 }
                 if (copy > state->length) copy = state->length;
                 state->length -= copy;
                 left -= copy;
                 do {
                     *put++ = *from++;
                 } while (--copy);
             } while (state->length != 0);
             break;
         case DONE:
             /* inflate stream terminated properly -- write leftover output */
             ret = Z_STREAM_END;
             if (left < state->wsize) {
                 if (out(out_desc, state->window, state->wsize - left))
                     ret = Z_BUF_ERROR;
             }
             goto inf_leave;
         case BAD:
             ret = Z_DATA_ERROR;
             goto inf_leave;
         default:                /* can't happen, but makes compilers happy */
             ret = Z_STREAM_ERROR;
             goto inf_leave;
         }
     /* Return unused input */
   inf_leave:
     strm->next_in = next;
     strm->avail_in = have;
     return ret;
 }
References BAD, G3D::bits(), BITS, code::bits, BYTEBITS, inflate_state::codes, CODES, detail::copy(), inflate_state::distbits, inflate_state::distcode, DISTS, DONE, DROPBITS, inflate_state::extra, FAR, fixedtables(), inflate_state::have, inflate_state::hold, if(), inflate_fast(), inflate_table(), INITBITS, inflate_state::last, align::left, LEN, inflate_state::lenbits, inflate_state::lencode, inflate_state::length, inflate_state::lens, LENS, LOAD, inflate_state::mode, inflate_state::ncode, inflate_state::ndist, NEEDBITS, next(), inflate_state::next, inflate_state::nlen, inflate_state::offset, code::op, PULL, PULLBYTE, RESTORE, ret, ROOM, STORED, TABLE, Tracev, Tracevv, TYPE, code::val, inflate_state::whave, inflate_state::window, inflate_state::work, inflate_state::wsize, Z_BUF_ERROR, Z_DATA_ERROR, Z_NULL, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
inflateBackEnd()
int ZEXPORT inflateBackEnd (z_streamp strm)
Definition at line 631 of file infback.c.
 {
     if (strm == Z_NULL || strm->state == Z_NULL || strm->zfree == (free_func)0)
         return Z_STREAM_ERROR;
     ZFREE(strm, strm->state);
     strm->state = Z_NULL;
     Tracev((stderr, "inflate: end\n"));
     return Z_OK;
 }
References Tracev, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
inflateBackInit_()
int ZEXPORT inflateBackInit_ (z_streamp strm, int windowBits, unsigned char FAR * window, const char * version, int stream_size)
Definition at line 28 of file infback.c.
 {
     struct inflate_state FAR *state;
     if (version == Z_NULL || version[0] != ZLIB_VERSION[0] ||
         stream_size != (int)(sizeof(z_stream)))
         return Z_VERSION_ERROR;
     if (strm == Z_NULL || window == Z_NULL ||
         windowBits < 8 || windowBits > 15)
         return Z_STREAM_ERROR;
     strm->msg = Z_NULL;                 /* in case we return an error */
     if (strm->zalloc == (alloc_func)0) {
 #ifdef Z_SOLO
         return Z_STREAM_ERROR;
 #else
         strm->zalloc = zcalloc;
         strm->opaque = (voidpf)0;
 #endif
     }
     if (strm->zfree == (free_func)0)
 #ifdef Z_SOLO
         return Z_STREAM_ERROR;
 #else
     strm->zfree = zcfree;
 #endif
     state = (struct inflate_state FAR *)ZALLOC(strm, 1,
                                                sizeof(struct inflate_state));
     if (state == Z_NULL) return Z_MEM_ERROR;
     Tracev((stderr, "inflate: allocated\n"));
     strm->state = (struct internal_state FAR *)state;
     state->dmax = 32768U;
     state->wbits = windowBits;
     state->wsize = 1U << windowBits;
     state->window = window;
     state->wnext = 0;
     state->whave = 0;
     return Z_OK;
 }
References inflate_state::dmax, FAR, Tracev, setup::version, inflate_state::wbits, inflate_state::whave, internal_state::window, inflate_state::window, inflate_state::wnext, inflate_state::wsize, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), and ZLIB_VERSION.
OF()
void fixedtables OF ((struct inflate_state FAR *state))