Azerotcore-wotlk: arg_mapper< Context > Struct Template Reference
arg_mapper< Context > Struct Template Reference
#include <core.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
FMT_CONSTEXPR FMT_INLINE auto map (signed char val) -> int
FMT_CONSTEXPR FMT_INLINE auto map (unsigned char val) -> unsigned
FMT_CONSTEXPR FMT_INLINE auto map (short val) -> int
FMT_CONSTEXPR FMT_INLINE auto map (unsigned short val) -> unsigned
FMT_CONSTEXPR FMT_INLINE auto map (int val) -> int
FMT_CONSTEXPR FMT_INLINE auto map (unsigned val) -> unsigned
FMT_CONSTEXPR FMT_INLINE auto map (long val) -> long_type
FMT_CONSTEXPR FMT_INLINE auto map (unsigned long val) -> ulong_type
FMT_CONSTEXPR FMT_INLINE auto map (long long val) -> long long
FMT_CONSTEXPR FMT_INLINE auto map (unsigned long long val) -> unsigned long long
FMT_CONSTEXPR FMT_INLINE auto map (int128_t val) -> int128_t
FMT_CONSTEXPR FMT_INLINE auto map (uint128_t val) -> uint128_t
FMT_CONSTEXPR FMT_INLINE auto map (bool val) -> bool
template<typename T , FMT_ENABLE_IF(is_char< T >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (T val) -> char_type
FMT_CONSTEXPR FMT_INLINE auto map (float val) -> float
FMT_CONSTEXPR FMT_INLINE auto map (double val) -> double
FMT_CONSTEXPR FMT_INLINE auto map (long double val) -> long double
FMT_CONSTEXPR FMT_INLINE auto map (char_type *val) -> const char_type *
FMT_CONSTEXPR FMT_INLINE auto map (const char_type *val) -> const char_type *
template<typename T , FMT_ENABLE_IF(is_string< T >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &val) -> basic_string_view< char_type >
template<typename T , FMT_ENABLE_IF(std::is_constructible< basic_string_view< char_type >, T >::value && !is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &val) -> basic_string_view< char_type >
template<typename T , FMT_ENABLE_IF(std::is_constructible< std_string_view< char_type >, T >::value && !std::is_constructible< basic_string_view< char_type >, T >::value && !is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &val) -> basic_string_view< char_type >
FMT_CONSTEXPR FMT_INLINE auto map (const signed char *val) -> const char *
FMT_CONSTEXPR FMT_INLINE auto map (const unsigned char *val) -> const char *
FMT_CONSTEXPR FMT_INLINE auto map (signed char *val) -> const char *
FMT_CONSTEXPR FMT_INLINE auto map (unsigned char *val) -> const char *
FMT_CONSTEXPR FMT_INLINE auto map (void *val) -> const void *
FMT_CONSTEXPR FMT_INLINE auto map (const void *val) -> const void *
FMT_CONSTEXPR FMT_INLINE auto map (std::nullptr_t val) -> const void *
template<typename T >
FMT_CONSTEXPR auto map (T) -> enable_if_t< std::is_pointer< T >::value, int >
template<typename T , std::size_t N>
FMT_CONSTEXPR FMT_INLINE auto map (const T(&values)[N]) -> const T(&)[N]
template<typename T , FMT_ENABLE_IF(std::is_enum< T >::value && !has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &val) -> decltype(std::declval< arg_mapper >().map(static_cast< typename std::underlying_type< T >::type >(val)))
template<typename T , FMT_ENABLE_IF(!is_string< T >::value &&!is_char< T >::value &&(has_formatter< T, Context >::value|| has_fallback_formatter< T, char_type >::value)) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &val) -> const T &
template<typename T , FMT_ENABLE_IF(is_named_arg< T >::value) >
FMT_CONSTEXPR FMT_INLINE auto map (const T &named_arg) -> decltype(std::declval< arg_mapper >().map(named_arg.value))
auto map (...) -> unformattable
Detailed Description
template<typename Context>
struct arg_mapper< Context >
Definition at line 1202 of file core.h.
Member Typedef Documentation
char_type
template<typename Context > using arg_mapper< Context >::char_type = typename Context::char_type
Definition at line 1203 of file core.h.
Member Function Documentation
map() [1/35]
template<typename Context > auto arg_mapper< Context >::map (...) -> unformattable inline
Definition at line 1340 of file core.h.
 { return {}; }
map() [2/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (bool val) -> bool inline
Definition at line 1226 of file core.h.
 { return val; }
map() [3/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (char_type * val) -> const char_type* inline
Definition at line 1242 of file core.h.
{
     return val;
   }
map() [4/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const char_type * val) -> const char_type* inline
Definition at line 1245 of file core.h.
{
     return val;
   }
map() [5/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const signed char * val) -> const char* inline
Definition at line 1275 of file core.h.
{
     static_assert(std::is_same<char_type, char>::value, "invalid string type");
     return reinterpret_cast<const char*>(val);
   }
map() [6/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(is_named_arg< T >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & named_arg) -> decltype(std::declval<arg_mapper>().map(named_arg.value)) inline
Definition at line 1335 of file core.h.
{
     return map(named_arg.value);
   }
References arg_mapper< Context >::map(), and named_arg< Char, T >::value.
map() [7/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(is_string< T >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & val) -> basic_string_view<char_type> inline
Definition at line 1249 of file core.h.
{
     static_assert(std::is_same<char_type, char_t<T>>::value,
                   "mixing character types is disallowed");
     return to_string_view(val);
   }
References to_string_view().
map() [8/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_constructible< basic_string_view< char_type >, T >::value && !is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & val) -> basic_string_view<char_type> inline
Definition at line 1260 of file core.h.
{
     return basic_string_view<char_type>(val);
   }
map() [9/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_constructible< std_string_view< char_type >, T >::value && !std::is_constructible< basic_string_view< char_type >, T >::value && !is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & val) -> basic_string_view<char_type> inline
Definition at line 1271 of file core.h.
{
     return std_string_view<char_type>(val);
   }
map() [10/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(!is_string< T >::value &&!is_char< T >::value &&(has_formatter< T, Context >::value|| has_fallback_formatter< T, char_type >::value)) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & val) -> const T& inline
Definition at line 1330 of file core.h.
{
     return val;
   }
map() [11/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_enum< T >::value && !has_formatter< T, Context >::value && !has_fallback_formatter< T, char_type >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T & val) -> decltype(std::declval<arg_mapper>().map(static_cast<typename std::underlying_type<T>::type>(val))) inline
Definition at line 1321 of file core.h.
{
     return map(static_cast<typename std::underlying_type<T>::type>(val));
   }
References arg_mapper< Context >::map().
map() [12/35]
template<typename Context > template<typename T , std::size_t N> FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const T(&) values[N]) -> const T (&)[N] inline
Definition at line 1313 of file core.h.
{
     return values;
   }
map() [13/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const unsigned char * val) -> const char* inline
Definition at line 1279 of file core.h.
{
     static_assert(std::is_same<char_type, char>::value, "invalid string type");
     return reinterpret_cast<const char*>(val);
   }
map() [14/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (const void * val) -> const void* inline
Definition at line 1293 of file core.h.
{
     return val;
   }
map() [15/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (double val) -> double inline
Definition at line 1237 of file core.h.
 { return val; }
map() [16/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (float val) -> float inline
Definition at line 1236 of file core.h.
 { return val; }
map() [17/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (int val) -> int inline
Definition at line 1213 of file core.h.
 { return val; }
map() [18/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (int128_t val) -> int128_t inline
Definition at line 1224 of file core.h.
 { return val; }
map() [19/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (long double val) -> long double inline
Definition at line 1238 of file core.h.
{
     return val;
   }
map() [20/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (long long val) -> long long inline
Definition at line 1219 of file core.h.
 { return val; }
map() [21/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (long val) -> long_type inline
Definition at line 1215 of file core.h.
 { return val; }
map() [22/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (short val) -> int inline
Definition at line 1209 of file core.h.
 { return val; }
map() [23/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (signed char * val) -> const char* inline
Definition at line 1283 of file core.h.
{
     const auto* const_val = val;
     return map(const_val);
   }
References arg_mapper< Context >::map().
map() [24/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (signed char val) -> int inline
Definition at line 1205 of file core.h.
 { return val; }
Referenced by make_arg(), and arg_mapper< Context >::map().
map() [25/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (std::nullptr_t val) -> const void* inline
Definition at line 1296 of file core.h.
{
     return val;
   }
map() [26/35]
template<typename Context > template<typename T , FMT_ENABLE_IF(is_char< T >::value) > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (T val) -> char_type inline
Definition at line 1229 of file core.h.
{
     static_assert(
         std::is_same<T, char>::value || std::is_same<T, char_type>::value,
         "mixing character types is disallowed");
     return val;
   }
map() [27/35]
template<typename Context > template<typename T > FMT_CONSTEXPR auto arg_mapper< Context >::map (T) -> enable_if_t<std::is_pointer<T>::value, int> inline
Definition at line 1303 of file core.h.
{
     // Formatting of arbitrary pointers is disallowed. If you want to output
     // a pointer cast it to "void *" or "const void *". In particular, this
     // forbids formatting of "[const] volatile char *" which is printed as bool
     // by iostreams.
     static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");
     return 0;
   }
map() [28/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (uint128_t val) -> uint128_t inline
Definition at line 1225 of file core.h.
 { return val; }
map() [29/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned char * val) -> const char* inline
Definition at line 1287 of file core.h.
{
     const auto* const_val = val;
     return map(const_val);
   }
References arg_mapper< Context >::map().
map() [30/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned char val) -> unsigned inline
Definition at line 1206 of file core.h.
{
     return val;
   }
map() [31/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned long long val) -> unsigned long long inline
Definition at line 1220 of file core.h.
{
     return val;
   }
map() [32/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned long val) -> ulong_type inline
Definition at line 1216 of file core.h.
{
     return val;
   }
map() [33/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned short val) -> unsigned inline
Definition at line 1210 of file core.h.
{
     return val;
   }
map() [34/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (unsigned val) -> unsigned inline
Definition at line 1214 of file core.h.
 { return val; }
map() [35/35]
template<typename Context > FMT_CONSTEXPR FMT_INLINE auto arg_mapper< Context >::map (void * val) -> const void* inline
Definition at line 1292 of file core.h.
 { return val; }
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/core.h