Azerotcore-wotlk: IdleMovementGenerator Class Reference
IdleMovementGenerator Class Reference
#include <IdleMovementGenerator.h>
Public Member Functions
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Detailed Description
Definition at line 23 of file IdleMovementGenerator.h.
Member Function Documentation
Finalize()
void IdleMovementGenerator::Finalize (Unit *) inline override virtual
Implements MovementGenerator.
Definition at line 27 of file IdleMovementGenerator.h.
 {  }
GetMovementGeneratorType()
MovementGeneratorType IdleMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
Definition at line 30 of file IdleMovementGenerator.h.
 { return IDLE_MOTION_TYPE; }
References IDLE_MOTION_TYPE.
Initialize()
void IdleMovementGenerator::Initialize (Unit * owner) override virtual
Implements MovementGenerator.
Definition at line 26 of file IdleMovementGenerator.cpp.
 {
     Reset(owner);
 }
References Reset().
Reset()
void IdleMovementGenerator::Reset (Unit * owner) override virtual
Implements MovementGenerator.
Definition at line 31 of file IdleMovementGenerator.cpp.
 {
     if (!owner->IsStopped())
         owner->StopMoving();
 }
References Unit::IsStopped(), and Unit::StopMoving().
Referenced by Initialize().
Update()
bool IdleMovementGenerator::Update (Unit * , uint32) inline override virtual
Implements MovementGenerator.
Definition at line 29 of file IdleMovementGenerator.h.
 { return true; }
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.h
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.cpp