Azerotcore-wotlk: MySQLConnection Class Reference
MySQLConnection Class Reference abstract
#include <MySQLConnection.h>
Public Member Functions
MySQLConnection (MySQLConnectionInfo &connInfo)
MySQLConnection (ProducerConsumerQueue< SQLOperation * > *queue, MySQLConnectionInfo &connInfo)
Constructor for synchronous connections.
virtual ~MySQLConnection ()
Constructor for asynchronous connections.
virtual uint32 Open ()
void Close ()
bool PrepareStatements ()
bool Execute (char const *sql)
bool Execute (PreparedStatementBase *stmt)
ResultSet * Query (char const *sql)
PreparedResultSet * Query (PreparedStatementBase *stmt)
bool _Query (char const *sql, MySQLResult **pResult, MySQLField **pFields, uint64 *pRowCount, uint32 *pFieldCount)
bool _Query (PreparedStatementBase *stmt, MySQLPreparedStatement **mysqlStmt, MySQLResult **pResult, uint64 *pRowCount, uint32 *pFieldCount)
void BeginTransaction ()
void RollbackTransaction ()
void CommitTransaction ()
int ExecuteTransaction (std::shared_ptr< TransactionBase > transaction)
size_t EscapeString (char *to, const char *from, size_t length)
void Ping ()
uint32 GetLastError ()
Protected Types
typedef std::vector< std::unique_ptr< MySQLPreparedStatement > > PreparedStatementContainer
Protected Member Functions
bool LockIfReady ()
void Unlock ()
Called by parent databasepool. Will let other threads access this connection.
uint32 GetServerVersion () const
MySQLPreparedStatement * GetPreparedStatement (uint32 index)
void PrepareStatement (uint32 index, std::string const &sql, ConnectionFlags flags)
virtual void DoPrepareStatements ()=0
Protected Attributes
PreparedStatementContainer m_stmts
bool m_reconnecting
PreparedStatements storage.
bool m_prepareError
Are we reconnecting?
Private Member Functions
bool _HandleMySQLErrno (uint32 errNo, uint8 attempts=5)
Was there any error while preparing statements?
MySQLConnection (MySQLConnection const &right)=delete
MySQLConnection & operator= (MySQLConnection const &right)=delete
Private Attributes
ProducerConsumerQueue< SQLOperation * > * m_queue
std::unique_ptr< DatabaseWorker > m_worker
Queue shared with other asynchronous connections.
MySQLHandle * m_Mysql
Core worker task.
MySQLConnectionInfo & m_connectionInfo
MySQL Handle.
ConnectionFlags m_connectionFlags
Connection info (used for logging)
std::mutex m_Mutex
Connection flags (for preparing relevant statements)
Friends
template<class T >
class DatabaseWorkerPool
class PingOperation
Detailed Description
Definition at line 55 of file MySQLConnection.h.
Member Typedef Documentation
PreparedStatementContainer
typedef std::vector<std::unique_ptr<MySQLPreparedStatement> > MySQLConnection::PreparedStatementContainer protected
Definition at line 100 of file MySQLConnection.h.
Constructor & Destructor Documentation
MySQLConnection() [1/3]
MySQLConnection::MySQLConnection (MySQLConnectionInfo & connInfo)
Definition at line 51 of file MySQLConnection.cpp.
                                                               :
 m_reconnecting(false),
 m_prepareError(false),
 m_queue(nullptr),
 m_Mysql(nullptr),
 m_connectionInfo(connInfo),
 m_connectionFlags(CONNECTION_SYNCH) { }
MySQLConnection() [2/3]
MySQLConnection::MySQLConnection (ProducerConsumerQueue< SQLOperation * > * queue, MySQLConnectionInfo & connInfo)
Constructor for synchronous connections.
Definition at line 59 of file MySQLConnection.cpp.
                                                                                                            :
 m_reconnecting(false),
 m_prepareError(false),
 m_queue(queue),
 m_Mysql(nullptr),
 m_connectionInfo(connInfo),
 m_connectionFlags(CONNECTION_ASYNC)
 {
     m_worker = std::make_unique<DatabaseWorker>(m_queue, this);
 }
References m_queue, and m_worker.
~MySQLConnection()
MySQLConnection::~MySQLConnection () virtual
Constructor for asynchronous connections.
Definition at line 70 of file MySQLConnection.cpp.
 {
     Close();
 }
References Close().
MySQLConnection() [3/3]
MySQLConnection::MySQLConnection (MySQLConnection const & right) private delete
Member Function Documentation
_HandleMySQLErrno()
bool MySQLConnection::_HandleMySQLErrno (uint32 errNo, uint8 attempts = 5) private
Was there any error while preparing statements?
Definition at line 532 of file MySQLConnection.cpp.
 {
     switch (errNo)
     {
         case CR_SERVER_GONE_ERROR:
         case CR_SERVER_LOST:
         case CR_SERVER_LOST_EXTENDED:
         {
             if (m_Mysql)
             {
                 LOG_ERROR("sql.sql", "Lost the connection to the MySQL server!");
                 mysql_close(m_Mysql);
                 m_Mysql = nullptr;
             }
             [[fallthrough]];
         }
         case CR_CONN_HOST_ERROR:
         {
             LOG_INFO("sql.sql", "Attempting to reconnect to the MySQL server...");
             m_reconnecting = true;
             uint32 const lErrno = Open();
             if (!lErrno)
             {
                 // Don't remove 'this' pointer unless you want to skip loading all prepared statements...
                 if (!this->PrepareStatements())
                 {
                     LOG_FATAL("sql.sql", "Could not re-prepare statements!");
                     std::this_thread::sleep_for(std::chrono::seconds(10));
                     std::abort();
                 }
                 LOG_INFO("sql.sql", "Successfully reconnected to %s @%s:%s (%s).",
                     m_connectionInfo.database.c_str(), m_connectionInfo.host.c_str(), m_connectionInfo.port_or_socket.c_str(),
                         (m_connectionFlags & CONNECTION_ASYNC) ? "asynchronous" : "synchronous");
                 m_reconnecting = false;
                 return true;
             }
             if ((--attempts) == 0)
             {
                 // Shut down the server when the mysql server isn't
                 // reachable for some time
                 LOG_FATAL("sql.sql", "Failed to reconnect to the MySQL server, "
                              "terminating the server to prevent data corruption!");
                 // We could also initiate a shutdown through using std::raise(SIGTERM)
                 std::this_thread::sleep_for(std::chrono::seconds(10));
                 std::abort();
             }
             else
             {
                 // It's possible this attempted reconnect throws 2006 at us.
                 // To prevent crazy recursive calls, sleep here.
                 std::this_thread::sleep_for(std::chrono::seconds(3)); // Sleep 3 seconds
                 return _HandleMySQLErrno(lErrno, attempts); // Call self (recursive)
             }
         }
         case ER_LOCK_DEADLOCK:
             return false;    // Implemented in TransactionTask::Execute and DatabaseWorkerPool<T>::DirectCommitTransaction
         // Query related errors - skip query
         case ER_WRONG_VALUE_COUNT:
         case ER_DUP_ENTRY:
             return false;
         // Outdated table or database structure - terminate core
         case ER_BAD_FIELD_ERROR:
         case ER_NO_SUCH_TABLE:
             LOG_ERROR("sql.sql", "Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.");
             std::this_thread::sleep_for(std::chrono::seconds(10));
             std::abort();
             return false;
         case ER_PARSE_ERROR:
             LOG_ERROR("sql.sql", "Error while parsing SQL. Core fix required.");
             std::this_thread::sleep_for(std::chrono::seconds(10));
             std::abort();
             return false;
         default:
             LOG_ERROR("sql.sql", "Unhandled MySQL errno %u. Unexpected behaviour possible.", errNo);
             return false;
     }
 }
References CONNECTION_ASYNC, MySQLConnectionInfo::database, MySQLConnectionInfo::host, LOG_ERROR, LOG_FATAL, LOG_INFO, m_connectionFlags, m_connectionInfo, m_Mysql, m_reconnecting, Open(), MySQLConnectionInfo::port_or_socket, and PrepareStatements().
Referenced by _Query(), and Execute().
_Query() [1/2]
bool MySQLConnection::_Query (char const * sql, MySQLResult ** pResult, MySQLField ** pFields, uint64 * pRowCount, uint32 * pFieldCount)
Definition at line 334 of file MySQLConnection.cpp.
 {
     if (!m_Mysql)
         return false;
     {
         uint32 _s = getMSTime();
         if (mysql_query(m_Mysql, sql))
         {
             uint32 lErrno = mysql_errno(m_Mysql);
             LOG_INFO("sql.sql", "SQL: %s", sql);
             LOG_ERROR("sql.sql", "[%u] %s", lErrno, mysql_error(m_Mysql));
             if (_HandleMySQLErrno(lErrno))      // If it returns true, an error was handled successfully (i.e. reconnection)
                 return _Query(sql, pResult, pFields, pRowCount, pFieldCount);    // We try again
             return false;
         }
         else
             LOG_DEBUG("sql.sql", "[%u ms] SQL: %s", getMSTimeDiff(_s, getMSTime()), sql);
         *pResult = reinterpret_cast<MySQLResult*>(mysql_store_result(m_Mysql));
         *pRowCount = mysql_affected_rows(m_Mysql);
         *pFieldCount = mysql_field_count(m_Mysql);
     }
     if (!*pResult )
         return false;
     if (!*pRowCount)
     {
         mysql_free_result(*pResult);
         return false;
     }
     *pFields = reinterpret_cast<MySQLField*>(mysql_fetch_fields(*pResult));
     return true;
 }
References _HandleMySQLErrno(), getMSTime(), getMSTimeDiff(), LOG_DEBUG, LOG_ERROR, LOG_INFO, and m_Mysql.
Referenced by _Query(), and Query().
_Query() [2/2]
bool MySQLConnection::_Query (PreparedStatementBase * stmt, MySQLPreparedStatement ** mysqlStmt, MySQLResult ** pResult, uint64 * pRowCount, uint32 * pFieldCount)
Definition at line 264 of file MySQLConnection.cpp.
 {
     if (!m_Mysql)
         return false;
     uint32 index = stmt->GetIndex();
     MySQLPreparedStatement* m_mStmt = GetPreparedStatement(index);
     ASSERT(m_mStmt);            // Can only be null if preparation failed, server side error or bad query
     m_mStmt->BindParameters(stmt);
     *mysqlStmt = m_mStmt;
     MYSQL_STMT* msql_STMT = m_mStmt->GetSTMT();
     MYSQL_BIND* msql_BIND = m_mStmt->GetBind();
     uint32 _s = getMSTime();
     if (mysql_stmt_bind_param(msql_STMT, msql_BIND))
     {
         uint32 lErrno = mysql_errno(m_Mysql);
         LOG_ERROR("sql.sql", "SQL(p): %s\n [ERROR]: [%u] %s", m_mStmt->getQueryString().c_str(), lErrno, mysql_stmt_error(msql_STMT));
         if (_HandleMySQLErrno(lErrno))  // If it returns true, an error was handled successfully (i.e. reconnection)
             return _Query(stmt, mysqlStmt, pResult, pRowCount, pFieldCount);       // Try again
         m_mStmt->ClearParameters();
         return false;
     }
     if (mysql_stmt_execute(msql_STMT))
     {
         uint32 lErrno = mysql_errno(m_Mysql);
         LOG_ERROR("sql.sql", "SQL(p): %s\n [ERROR]: [%u] %s",
             m_mStmt->getQueryString().c_str(), lErrno, mysql_stmt_error(msql_STMT));
         if (_HandleMySQLErrno(lErrno))  // If it returns true, an error was handled successfully (i.e. reconnection)
             return _Query(stmt, mysqlStmt, pResult, pRowCount, pFieldCount);      // Try again
         m_mStmt->ClearParameters();
         return false;
     }
     LOG_DEBUG("sql.sql", "[%u ms] SQL(p): %s", getMSTimeDiff(_s, getMSTime()), m_mStmt->getQueryString().c_str());
     m_mStmt->ClearParameters();
     *pResult = reinterpret_cast<MySQLResult*>(mysql_stmt_result_metadata(msql_STMT));
     *pRowCount = mysql_stmt_num_rows(msql_STMT);
     *pFieldCount = mysql_stmt_field_count(msql_STMT);
     return true;
 }
References _HandleMySQLErrno(), _Query(), ASSERT, MySQLPreparedStatement::BindParameters(), MySQLPreparedStatement::ClearParameters(), MySQLPreparedStatement::GetBind(), PreparedStatementBase::GetIndex(), getMSTime(), getMSTimeDiff(), GetPreparedStatement(), MySQLPreparedStatement::getQueryString(), MySQLPreparedStatement::GetSTMT(), LOG_DEBUG, LOG_ERROR, and m_Mysql.
BeginTransaction()
void MySQLConnection::BeginTransaction ()
Definition at line 375 of file MySQLConnection.cpp.
 {
     Execute("START TRANSACTION");
 }
References Execute().
Referenced by ExecuteTransaction().
Close()
void MySQLConnection::Close ()
Definition at line 75 of file MySQLConnection.cpp.
 {
     // Stop the worker thread before the statements are cleared
     m_worker.reset();
     m_stmts.clear();
     if (m_Mysql)
     {
         mysql_close(m_Mysql);
         m_Mysql = nullptr;
     }
 }
References m_Mysql, m_stmts, and m_worker.
Referenced by ~MySQLConnection().
CommitTransaction()
void MySQLConnection::CommitTransaction ()
Definition at line 385 of file MySQLConnection.cpp.
 {
     Execute("COMMIT");
 }
References Execute().
Referenced by ExecuteTransaction().
DoPrepareStatements()
virtual void MySQLConnection::DoPrepareStatements () protected pure virtual
Implemented in WorldDatabaseConnection, LoginDatabaseConnection, and CharacterDatabaseConnection.
Referenced by PrepareStatements().
EscapeString()
size_t MySQLConnection::EscapeString (char * to, const char * from, size_t length)
Definition at line 441 of file MySQLConnection.cpp.
 {
     return mysql_real_escape_string(m_Mysql, to, from, length);
 }
References m_Mysql.
Execute() [1/2]
bool MySQLConnection::Execute (char const * sql)
Definition at line 190 of file MySQLConnection.cpp.
 {
     if (!m_Mysql)
         return false;
     {
         uint32 _s = getMSTime();
         if (mysql_query(m_Mysql, sql))
         {
             uint32 lErrno = mysql_errno(m_Mysql);
             LOG_INFO("sql.sql", "SQL: %s", sql);
             LOG_ERROR("sql.sql", "[%u] %s", lErrno, mysql_error(m_Mysql));
             if (_HandleMySQLErrno(lErrno))  // If it returns true, an error was handled successfully (i.e. reconnection)
                 return Execute(sql);       // Try again
             return false;
         }
         else
             LOG_DEBUG("sql.sql", "[%u ms] SQL: %s", getMSTimeDiff(_s, getMSTime()), sql);
     }
     return true;
 }
References _HandleMySQLErrno(), getMSTime(), getMSTimeDiff(), LOG_DEBUG, LOG_ERROR, LOG_INFO, and m_Mysql.
Referenced by BeginTransaction(), CommitTransaction(), BasicStatementTask::Execute(), PreparedStatementTask::Execute(), Execute(), ExecuteTransaction(), and RollbackTransaction().
Execute() [2/2]
bool MySQLConnection::Execute (PreparedStatementBase * stmt)
Definition at line 217 of file MySQLConnection.cpp.
 {
     if (!m_Mysql)
         return false;
     uint32 index = stmt->GetIndex();
     MySQLPreparedStatement* m_mStmt = GetPreparedStatement(index);
     ASSERT(m_mStmt);            // Can only be null if preparation failed, server side error or bad query
     m_mStmt->BindParameters(stmt);
     MYSQL_STMT* msql_STMT = m_mStmt->GetSTMT();
     MYSQL_BIND* msql_BIND = m_mStmt->GetBind();
     uint32 _s = getMSTime();
     if (mysql_stmt_bind_param(msql_STMT, msql_BIND))
     {
         uint32 lErrno = mysql_errno(m_Mysql);
         LOG_ERROR("sql.sql", "SQL(p): %s\n [ERROR]: [%u] %s", m_mStmt->getQueryString().c_str(), lErrno, mysql_stmt_error(msql_STMT));
         if (_HandleMySQLErrno(lErrno))  // If it returns true, an error was handled successfully (i.e. reconnection)
             return Execute(stmt);       // Try again
         m_mStmt->ClearParameters();
         return false;
     }
     if (mysql_stmt_execute(msql_STMT))
     {
         uint32 lErrno = mysql_errno(m_Mysql);
         LOG_ERROR("sql.sql", "SQL(p): %s\n [ERROR]: [%u] %s", m_mStmt->getQueryString().c_str(), lErrno, mysql_stmt_error(msql_STMT));
         if (_HandleMySQLErrno(lErrno))  // If it returns true, an error was handled successfully (i.e. reconnection)
             return Execute(stmt);       // Try again
         m_mStmt->ClearParameters();
         return false;
     }
     LOG_DEBUG("sql.sql", "[%u ms] SQL(p): %s", getMSTimeDiff(_s, getMSTime()), m_mStmt->getQueryString().c_str());
     m_mStmt->ClearParameters();
     return true;
 }
References _HandleMySQLErrno(), ASSERT, MySQLPreparedStatement::BindParameters(), MySQLPreparedStatement::ClearParameters(), Execute(), MySQLPreparedStatement::GetBind(), PreparedStatementBase::GetIndex(), getMSTime(), getMSTimeDiff(), GetPreparedStatement(), MySQLPreparedStatement::getQueryString(), MySQLPreparedStatement::GetSTMT(), LOG_DEBUG, LOG_ERROR, and m_Mysql.
ExecuteTransaction()
int MySQLConnection::ExecuteTransaction (std::shared_ptr< TransactionBase > transaction)
Definition at line 390 of file MySQLConnection.cpp.
 {
     std::vector<SQLElementData> const& queries = transaction->m_queries;
     if (queries.empty())
         return -1;
     BeginTransaction();
     for (auto itr = queries.begin(); itr != queries.end(); ++itr)
     {
         SQLElementData const& data = *itr;
         switch (itr->type)
         {
             case SQL_ELEMENT_PREPARED:
             {
                 PreparedStatementBase* stmt = data.element.stmt;
                 ASSERT(stmt);
                 if (!Execute(stmt))
                 {
                     LOG_WARN("sql.sql", "Transaction aborted. %u queries not executed.", (uint32)queries.size());
                     int errorCode = GetLastError();
                     RollbackTransaction();
                     return errorCode;
                 }
             }
             break;
             case SQL_ELEMENT_RAW:
             {
                 char const* sql = data.element.query;
                 ASSERT(sql);
                 if (!Execute(sql))
                 {
                     LOG_WARN("sql.sql", "Transaction aborted. %u queries not executed.", (uint32)queries.size());
                     int errorCode = GetLastError();
                     RollbackTransaction();
                     return errorCode;
                 }
             }
             break;
         }
     }
     // we might encounter errors during certain queries, and depending on the kind of error
     // we might want to restart the transaction. So to prevent data loss, we only clean up when it's all done.
     // This is done in calling functions DatabaseWorkerPool<T>::DirectCommitTransaction and TransactionTask::Execute,
     // and not while iterating over every element.
     CommitTransaction();
     return 0;
 }
References ASSERT, BeginTransaction(), CommitTransaction(), SQLElementData::element, Execute(), GetLastError(), LOG_WARN, SQLElementUnion::query, RollbackTransaction(), SQL_ELEMENT_PREPARED, SQL_ELEMENT_RAW, and SQLElementUnion::stmt.
Referenced by TransactionTask::TryExecute().
GetLastError()
uint32 MySQLConnection::GetLastError ()
Definition at line 451 of file MySQLConnection.cpp.
 {
     return mysql_errno(m_Mysql);
 }
References m_Mysql.
Referenced by ExecuteTransaction().
GetPreparedStatement()
MySQLPreparedStatement * MySQLConnection::GetPreparedStatement (uint32 index) protected
Definition at line 471 of file MySQLConnection.cpp.
 {
     ASSERT(index < m_stmts.size(), "Tried to access invalid prepared statement index %u (max index " SZFMTD ") on database `%s`, connection type: %s",
         index, m_stmts.size(), m_connectionInfo.database.c_str(), (m_connectionFlags & CONNECTION_ASYNC) ? "asynchronous" : "synchronous");
     MySQLPreparedStatement* ret = m_stmts[index].get();
     if (!ret)
         LOG_ERROR("sql.sql", "Could not fetch prepared statement %u on database `%s`, connection type: %s.",
             index, m_connectionInfo.database.c_str(), (m_connectionFlags & CONNECTION_ASYNC) ? "asynchronous" : "synchronous");
     return ret;
 }
References ASSERT, CONNECTION_ASYNC, MySQLConnectionInfo::database, LOG_ERROR, m_connectionFlags, m_connectionInfo, m_stmts, and SZFMTD.
Referenced by _Query(), and Execute().
GetServerVersion()
uint32 MySQLConnection::GetServerVersion () const protected
Definition at line 466 of file MySQLConnection.cpp.
 {
     return mysql_get_server_version(m_Mysql);
 }
References m_Mysql.
LockIfReady()
bool MySQLConnection::LockIfReady () protected
Tries to acquire lock. If lock is acquired by another thread the calling parent will just try another connection
Definition at line 456 of file MySQLConnection.cpp.
 {
     return m_Mutex.try_lock();
 }
References m_Mutex.
Open()
uint32 MySQLConnection::Open () virtual
Definition at line 89 of file MySQLConnection.cpp.
 {
     MYSQL *mysqlInit;
     mysqlInit = mysql_init(nullptr);
     if (!mysqlInit)
     {
         LOG_ERROR("sql.sql", "Could not initialize Mysql connection to database `%s`", m_connectionInfo.database.c_str());
         return CR_UNKNOWN_ERROR;
     }
     int port;
     char const* unix_socket;
     //unsigned int timeout = 10;
     mysql_options(mysqlInit, MYSQL_SET_CHARSET_NAME, "utf8");
     //mysql_options(mysqlInit, MYSQL_OPT_READ_TIMEOUT, (char const*)&timeout);
     #ifdef _WIN32
     if (m_connectionInfo.host == ".")                                           // named pipe use option (Windows)
     {
         unsigned int opt = MYSQL_PROTOCOL_PIPE;
         mysql_options(mysqlInit, MYSQL_OPT_PROTOCOL, (char const*)&opt);
         port = 0;
         unix_socket = 0;
     }
     else                                                    // generic case
     {
         port = atoi(m_connectionInfo.port_or_socket.c_str());
         unix_socket = 0;
     }
     #else
     if (m_connectionInfo.host == ".")                                           // socket use option (Unix/Linux)
     {
         unsigned int opt = MYSQL_PROTOCOL_SOCKET;
         mysql_options(mysqlInit, MYSQL_OPT_PROTOCOL, (char const*)&opt);
         m_connectionInfo.host = "localhost";
         port = 0;
         unix_socket = m_connectionInfo.port_or_socket.c_str();
     }
     else                                                    // generic case
     {
         port = atoi(m_connectionInfo.port_or_socket.c_str());
         unix_socket = nullptr;
     }
     #endif
     if (m_connectionInfo.ssl != "")
     {
 #if !defined(MARIADB_VERSION_ID) && MYSQL_VERSION_ID >= 80000
         mysql_ssl_mode opt_use_ssl = SSL_MODE_DISABLED;
         if (m_connectionInfo.ssl == "ssl")
         {
             opt_use_ssl = SSL_MODE_REQUIRED;
         }
         mysql_options(mysqlInit, MYSQL_OPT_SSL_MODE, (char const*)&opt_use_ssl);
 #else
         MySQLBool opt_use_ssl = MySQLBool(0);
         if (m_connectionInfo.ssl == "ssl")
         {
             opt_use_ssl = MySQLBool(1);
         }
         mysql_options(mysqlInit, MYSQL_OPT_SSL_ENFORCE, (char const*)&opt_use_ssl);
 #endif
     }
     m_Mysql = reinterpret_cast<MySQLHandle*>(mysql_real_connect(mysqlInit, m_connectionInfo.host.c_str(), m_connectionInfo.user.c_str(),
         m_connectionInfo.password.c_str(), m_connectionInfo.database.c_str(), port, unix_socket, 0));
     if (m_Mysql)
     {
         if (!m_reconnecting)
         {
             LOG_INFO("sql.sql", "MySQL client library: %s", mysql_get_client_info());
             LOG_INFO("sql.sql", "MySQL server ver: %s ", mysql_get_server_info(m_Mysql));
             // MySQL version above 5.1 IS required in both client and server and there is no known issue with different versions above 5.1
             // if (mysql_get_server_version(m_Mysql) != mysql_get_client_version())
             //     LOG_INFO("sql.sql", "[WARNING] MySQL client/server version mismatch; may conflict with behaviour of prepared statements.");
         }
         LOG_INFO("sql.sql", "Connected to MySQL database at %s", m_connectionInfo.host.c_str());
         mysql_autocommit(m_Mysql, 1);
         // set connection properties to UTF8 to properly handle locales for different
         // server configs - core sends data in UTF8, so MySQL must expect UTF8 too
         mysql_set_character_set(m_Mysql, "utf8");
         return 0;
     }
     else
     {
         LOG_ERROR("sql.sql", "Could not connect to MySQL database at %s: %s", m_connectionInfo.host.c_str(), mysql_error(mysqlInit));
         uint32 errorCode = mysql_errno(mysqlInit);
         mysql_close(mysqlInit);
         return errorCode;
     }
 }
References MySQLConnectionInfo::database, MySQLConnectionInfo::host, LOG_ERROR, LOG_INFO, m_connectionInfo, m_Mysql, m_reconnecting, MySQLConnectionInfo::password, MySQLConnectionInfo::port_or_socket, MySQLConnectionInfo::ssl, and MySQLConnectionInfo::user.
Referenced by _HandleMySQLErrno().
operator=()
MySQLConnection& MySQLConnection::operator= (MySQLConnection const & right) private delete
Ping()
void MySQLConnection::Ping ()
Definition at line 446 of file MySQLConnection.cpp.
 {
     mysql_ping(m_Mysql);
 }
References m_Mysql.
Referenced by PingOperation::Execute().
PrepareStatement()
void MySQLConnection::PrepareStatement (uint32 index, std::string const & sql, ConnectionFlags flags) protected
Definition at line 483 of file MySQLConnection.cpp.
 {
     // Check if specified query should be prepared on this connection
     // i.e. don't prepare async statements on synchronous connections
     // to save memory that will not be used.
     if (!(m_connectionFlags & flags))
     {
         m_stmts[index].reset();
         return;
     }
     MYSQL_STMT* stmt = mysql_stmt_init(m_Mysql);
     if (!stmt)
     {
         LOG_ERROR("sql.sql", "In mysql_stmt_init() id: %u, sql: \"%s\"", index, sql.c_str());
         LOG_ERROR("sql.sql", "%s", mysql_error(m_Mysql));
         m_prepareError = true;
     }
     else
     {
         if (mysql_stmt_prepare(stmt, sql.c_str(), static_cast<unsigned long>(sql.size())))
         {
             LOG_ERROR("sql.sql", "In mysql_stmt_prepare() id: %u, sql: \"%s\"", index, sql.c_str());
             LOG_ERROR("sql.sql", "%s", mysql_stmt_error(stmt));
             mysql_stmt_close(stmt);
             m_prepareError = true;
         }
         else
             m_stmts[index] = std::make_unique<MySQLPreparedStatement>(reinterpret_cast<MySQLStmt*>(stmt), sql);
     }
 }
References LOG_ERROR, m_connectionFlags, m_Mysql, m_prepareError, and m_stmts.
Referenced by CharacterDatabaseConnection::DoPrepareStatements(), LoginDatabaseConnection::DoPrepareStatements(), and WorldDatabaseConnection::DoPrepareStatements().
PrepareStatements()
bool MySQLConnection::PrepareStatements ()
Definition at line 184 of file MySQLConnection.cpp.
 {
     DoPrepareStatements();
     return !m_prepareError;
 }
References DoPrepareStatements(), and m_prepareError.
Referenced by _HandleMySQLErrno().
Query() [1/2]
ResultSet * MySQLConnection::Query (char const * sql)
Definition at line 318 of file MySQLConnection.cpp.
 {
     if (!sql)
         return nullptr;
     MySQLResult* result = nullptr;
     MySQLField* fields = nullptr;
     uint64 rowCount = 0;
     uint32 fieldCount = 0;
     if (!_Query(sql, &result, &fields, &rowCount, &fieldCount))
         return nullptr;
     return new ResultSet(result, fields, rowCount, fieldCount);
 }
References _Query().
Referenced by BasicStatementTask::Execute(), PreparedStatementTask::Execute(), and SQLQueryHolderTask::Execute().
Query() [2/2]
PreparedResultSet * MySQLConnection::Query (PreparedStatementBase * stmt)
Definition at line 515 of file MySQLConnection.cpp.
 {
     MySQLPreparedStatement* mysqlStmt = nullptr;
     MySQLResult* result = nullptr;
     uint64 rowCount = 0;
     uint32 fieldCount = 0;
     if (!_Query(stmt, &mysqlStmt, &result, &rowCount, &fieldCount))
         return nullptr;
     if (mysql_more_results(m_Mysql))
     {
         mysql_next_result(m_Mysql);
     }
     return new PreparedResultSet(mysqlStmt->GetSTMT(), result, rowCount, fieldCount);
 }
References _Query(), MySQLPreparedStatement::GetSTMT(), and m_Mysql.
RollbackTransaction()
void MySQLConnection::RollbackTransaction ()
Definition at line 380 of file MySQLConnection.cpp.
 {
     Execute("ROLLBACK");
 }
References Execute().
Referenced by ExecuteTransaction().
Unlock()
void MySQLConnection::Unlock () protected
Called by parent databasepool. Will let other threads access this connection.
Definition at line 461 of file MySQLConnection.cpp.
 {
     m_Mutex.unlock();
 }
References m_Mutex.
Friends And Related Function Documentation
DatabaseWorkerPool
template<class T > friend class DatabaseWorkerPool friend
Definition at line 57 of file MySQLConnection.h.
PingOperation
friend class PingOperation friend
Definition at line 58 of file MySQLConnection.h.
Member Data Documentation
m_connectionFlags
ConnectionFlags MySQLConnection::m_connectionFlags private
Connection info (used for logging)
Definition at line 113 of file MySQLConnection.h.
Referenced by _HandleMySQLErrno(), GetPreparedStatement(), and PrepareStatement().
m_connectionInfo
MySQLConnectionInfo& MySQLConnection::m_connectionInfo private
MySQL Handle.
Definition at line 112 of file MySQLConnection.h.
Referenced by _HandleMySQLErrno(), GetPreparedStatement(), and Open().
m_Mutex
std::mutex MySQLConnection::m_Mutex private
Connection flags (for preparing relevant statements)
Definition at line 114 of file MySQLConnection.h.
Referenced by LockIfReady(), and Unlock().
m_Mysql
MySQLHandle* MySQLConnection::m_Mysql private
Core worker task.
Definition at line 111 of file MySQLConnection.h.
Referenced by _HandleMySQLErrno(), _Query(), Close(), EscapeString(), Execute(), GetLastError(), GetServerVersion(), Open(), Ping(), PrepareStatement(), and Query().
m_prepareError
bool MySQLConnection::m_prepareError protected
Are we reconnecting?
Definition at line 104 of file MySQLConnection.h.
Referenced by PrepareStatement(), and PrepareStatements().
m_queue
ProducerConsumerQueue<SQLOperation*>* MySQLConnection::m_queue private
Definition at line 109 of file MySQLConnection.h.
Referenced by MySQLConnection().
m_reconnecting
bool MySQLConnection::m_reconnecting protected
PreparedStatements storage.
Definition at line 103 of file MySQLConnection.h.
Referenced by _HandleMySQLErrno(), CharacterDatabaseConnection::DoPrepareStatements(), LoginDatabaseConnection::DoPrepareStatements(), WorldDatabaseConnection::DoPrepareStatements(), and Open().
m_stmts
PreparedStatementContainer MySQLConnection::m_stmts protected
Definition at line 102 of file MySQLConnection.h.
Referenced by Close(), CharacterDatabaseConnection::DoPrepareStatements(), LoginDatabaseConnection::DoPrepareStatements(), WorldDatabaseConnection::DoPrepareStatements(), GetPreparedStatement(), and PrepareStatement().
m_worker
std::unique_ptr<DatabaseWorker> MySQLConnection::m_worker private
Queue shared with other asynchronous connections.
Definition at line 110 of file MySQLConnection.h.
Referenced by Close(), and MySQLConnection().
The documentation for this class was generated from the following files:
src/server/database/Database/MySQLConnection.h
src/server/database/Database/MySQLConnection.cpp