Azerotcore-wotlk: npc_nelson::npc_nelsonAI Struct Reference
npc_nelson::npc_nelsonAI Struct Reference
Public Member Functions
npc_nelsonAI (Creature *creature)
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *, Unit *killer) override
void Reset () override
void EnterCombat (Unit *victim) override
void UpdateAI (uint32 diff) override
void SpellHit (Unit *, const SpellInfo *Spell) override
void DoAction (int32 action) override
Public Member Functions inherited from NPCStaveQuestAI
NPCStaveQuestAI (Creature *creature)
uint32 GetFormEntry (std::string)
bool InNormalForm ()
void RevealForm ()
void StorePlayerGUID ()
Player * GetGossipPlayer ()
bool IsAllowedEntry (uint32)
bool UnitIsUnfair (Unit *unit)
bool IsFairFight ()
bool ValidThreatlist ()
void SetHomePosition ()
void PrepareForEncounter ()
void ClearLootIfUnfair (Unit *killer)
bool PlayerEligibleForReward (Unit *killer)
void StoreAttackerGuidValue (Unit *attacker)
bool QuestIncomplete (Unit *unit, uint32 questItem)
void ResetState (uint32)
void EvadeOnFeignDeath ()
virtual void AttackStart (Unit *)
virtual void AttackedBy (Unit *)
virtual void JustDied (Unit *)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool shouldDespawn
Public Attributes inherited from NPCStaveQuestAI
ObjectGuid gossipPlayerGUID
ObjectGuid playerGUID
bool encounterStarted
ThreatContainer::StorageType const & threatList = me->getThreatMgr().getThreatList()
std::map< int, int > entryKeys
std::map< int, std::map< std::string, int > > entryList
std::vector< uint64 > attackerGuids
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 835 of file npc_stave_of_ancients.cpp.
Constructor & Destructor Documentation
npc_nelsonAI()
npc_nelson::npc_nelsonAI::npc_nelsonAI (Creature * creature) inline
Definition at line 837 of file npc_stave_of_ancients.cpp.
 : NPCStaveQuestAI(creature) { }
Member Function Documentation
DoAction()
void npc_nelson::npc_nelsonAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1005 of file npc_stave_of_ancients.cpp.
         {
             if (action == EVENT_ENCOUNTER_START)
             {
                 PrepareForEncounter();
                 events.ScheduleEvent(EVENT_ENCOUNTER_START, 5000);
             }
         }
References EVENT_ENCOUNTER_START, and NPCStaveQuestAI::PrepareForEncounter().
EnterCombat()
void npc_nelson::npc_nelsonAI::EnterCombat (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 877 of file npc_stave_of_ancients.cpp.
         {
             RevealForm();
             me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             if (InNormalForm())
             {
                 return;
             }
             if (encounterStarted)
             {
                 me->CastSpell(me, NELSON_SPELL_SOUL_FLAME, true);
             }
             if (victim && (UnitIsUnfair(victim) || !QuestIncomplete(victim, NELSON_HEAD)))
             {
                 me->CastSpell(victim, SPELL_FOOLS_PLIGHT, true);
             }
             events.ScheduleEvent(EVENT_FOOLS_PLIGHT, urand(2000, 3000));
             events.ScheduleEvent(EVENT_RANGE_CHECK, 1000);
             events.ScheduleEvent(EVENT_UNFAIR_FIGHT, 1000);
             events.ScheduleEvent(NELSON_EVENT_DREADFUL_FRIGHT, 10000);
             events.ScheduleEvent(NELSON_EVENT_CREEPING_DOOM, 5000);
         }
References Unit::CastSpell(), NPCStaveQuestAI::encounterStarted, EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_UNFAIR_FIGHT, NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, NELSON_EVENT_CREEPING_DOOM, NELSON_EVENT_DREADFUL_FRIGHT, NELSON_HEAD, NELSON_SPELL_SOUL_FLAME, NPCStaveQuestAI::QuestIncomplete(), Object::RemoveFlag(), NPCStaveQuestAI::RevealForm(), SPELL_FOOLS_PLIGHT, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, NPCStaveQuestAI::UnitIsUnfair(), and urand().
JustSummoned()
void npc_nelson::npc_nelsonAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 842 of file npc_stave_of_ancients.cpp.
         {
             if (!summon)
             {
                 return;
             }
             // Workaround for increasing the Summoned Guardian damage by using the template modifier value
             summon->Unit::UpdateDamagePhysical(BASE_ATTACK);
             if (me->IsInCombat())
             {
                 summon->AI()->AttackStart(me->GetVictim());
             }
         }
References Creature::AI(), UnitAI::AttackStart(), BASE_ATTACK, Unit::GetVictim(), Unit::IsInCombat(), and ScriptedAI::me.
Reset()
void npc_nelson::npc_nelsonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 868 of file npc_stave_of_ancients.cpp.
         {
             ResetState(NELSON_SPELL_CRIPPLING_CLIP);
             shouldDespawn = false;
             events.Reset();
             me->RemoveAllMinionsByEntry(CREEPING_DOOM_ENTRY);
         }
References CREEPING_DOOM_ENTRY, ScriptedAI::me, NELSON_SPELL_CRIPPLING_CLIP, Unit::RemoveAllMinionsByEntry(), NPCStaveQuestAI::ResetState(), and shouldDespawn.
SpellHit()
void npc_nelson::npc_nelsonAI::SpellHit (Unit * , const SpellInfo * Spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 986 of file npc_stave_of_ancients.cpp.
         {
             if (InNormalForm())
             {
                 return;
             }
             if (me->HasAura(NELSON_SPELL_SOUL_FLAME) && me->HasAura(NELSON_WEAKNESS_FROST_TRAP))
             {
                 me->RemoveAura(NELSON_SPELL_SOUL_FLAME);
             }
             if (!me->HasAura(NELSON_SPELL_CRIPPLING_CLIP) && Spell->Id == NELSON_WEAKNESS_WING_CLIP)
             {
                 me->AddAura(NELSON_SPELL_CRIPPLING_CLIP, me);
                 me->TextEmote(NELSON_WEAKNESS_EMOTE);
             }
         }
References Unit::AddAura(), Unit::HasAura(), NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, NELSON_SPELL_CRIPPLING_CLIP, NELSON_SPELL_SOUL_FLAME, NELSON_WEAKNESS_EMOTE, NELSON_WEAKNESS_FROST_TRAP, NELSON_WEAKNESS_WING_CLIP, Unit::RemoveAura(), and Unit::TextEmote().
SummonedCreatureDies()
void npc_nelson::npc_nelsonAI::SummonedCreatureDies (Creature * , Unit * killer) inline override virtual
Reimplemented from CreatureAI.
Definition at line 858 of file npc_stave_of_ancients.cpp.
         {
             // This should trigger the despawn event when a another player or unit
             // kills a creeping doom unit
             if (UnitIsUnfair(killer))
             {
                 shouldDespawn = true;
             }
         }
References shouldDespawn, and NPCStaveQuestAI::UnitIsUnfair().
UpdateAI()
void npc_nelson::npc_nelsonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 904 of file npc_stave_of_ancients.cpp.
         {
             events.Update(diff);
             uint32 eventId = events.ExecuteEvent();
             // Out of combat events
             switch (eventId)
             {
                 case EVENT_ENCOUNTER_START:
                     me->Say(NELSON_SAY);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     events.ScheduleEvent(EVENT_REVEAL, 5000);
                     break;
                 case EVENT_REVEAL:
                     RevealForm();
                     break;
             }
             if (UpdateVictim())
             {
                 // This should prevent hunters from staying in combat when feign death is used and there is a bystander with 0 threat
                 EvadeOnFeignDeath();
             }
             else
             {
                 return;
             }
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 events.RepeatEvent(1000);
                 return;
             }
             // In combat events
             switch (eventId)
             {
                 case EVENT_FOOLS_PLIGHT:
                     if (UnitIsUnfair(me->GetVictim()) || !QuestIncomplete(me->GetVictim(), NELSON_HEAD))
                     {
                         me->CastSpell(me->GetVictim(), SPELL_FOOLS_PLIGHT, true);
                     }
                     events.RepeatEvent(urand(3000, 6000));
                     break;
                 case EVENT_RANGE_CHECK:
                     if (!me->GetVictim()->IsWithinDist2d(me, 60.0f))
                     {
                         EnterEvadeMode();
                     }
                     else
                     {
                         events.RepeatEvent(2000);
                     }
                     break;
                 case EVENT_UNFAIR_FIGHT:
                     if (!ValidThreatlist() || shouldDespawn)
                     {
                         SetHomePosition();
                         me->RemoveAllMinionsByEntry(CREEPING_DOOM_ENTRY);
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_ATTACKABLE_1 | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         me->CombatStop(true);
                         me->Say(NELSON_DESPAWN_SAY);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                         me->DespawnOrUnsummon(5000);
                         break;
                     }
                     events.RepeatEvent(2000);
                     break;
                 case NELSON_EVENT_DREADFUL_FRIGHT:
                     me->CastSpell(me->GetVictim(), NELSON_SPELL_DREADFUL_FRIGHT, false);
                     events.RepeatEvent(urand(12000, 19000));
                     break;
                 case NELSON_EVENT_CREEPING_DOOM:
                     me->CastSpell(me->GetVictim(), NELSON_SPELL_CREEPING_DOOM, false);
                     events.RepeatEvent(urand(10000, 12000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), Unit::CombatStop(), CREEPING_DOOM_ENTRY, Creature::DespawnOrUnsummon(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_TALK, CreatureAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), EVENT_ENCOUNTER_START, EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_REVEAL, EVENT_UNFAIR_FIGHT, Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), WorldObject::IsWithinDist2d(), ScriptedAI::me, NELSON_DESPAWN_SAY, NELSON_EVENT_CREEPING_DOOM, NELSON_EVENT_DREADFUL_FRIGHT, NELSON_HEAD, NELSON_SAY, NELSON_SPELL_CREEPING_DOOM, NELSON_SPELL_DREADFUL_FRIGHT, NPCStaveQuestAI::QuestIncomplete(), Unit::RemoveAllMinionsByEntry(), Object::RemoveFlag(), NPCStaveQuestAI::RevealForm(), Unit::Say(), Object::SetFlag(), NPCStaveQuestAI::SetHomePosition(), shouldDespawn, SPELL_FOOLS_PLIGHT, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_ATTACKABLE_1, UNIT_STATE_CASTING, NPCStaveQuestAI::UnitIsUnfair(), CreatureAI::UpdateVictim(), urand(), and NPCStaveQuestAI::ValidThreatlist().
Member Data Documentation
events
EventMap npc_nelson::npc_nelsonAI::events
Definition at line 839 of file npc_stave_of_ancients.cpp.
shouldDespawn
bool npc_nelson::npc_nelsonAI::shouldDespawn
Definition at line 840 of file npc_stave_of_ancients.cpp.
Referenced by Reset(), SummonedCreatureDies(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/World/npc_stave_of_ancients.cpp