Azerotcore-wotlk: src/test/server/game/Miscellaneous/FormulasTest.cpp File Reference
FormulasTest.cpp File Reference
#include "Formulas.h"
#include "gtest/gtest.h"
#include "WorldMock.h"
Functions
TEST (FormulasTest, hk_honor_at_level)
TEST (FormulasTest, GetGrayLevel)
TEST (FormulasTest, GetColorCode)
TEST (FormulasTest, GetZeroDifference)
TEST (FormulasTest, BaseGain)
TEST (FormulasTest, Gain)
Function Documentation
TEST() [1/6]
TEST (FormulasTest , BaseGain)
Definition at line 90 of file FormulasTest.cpp.
 {
     EXPECT_EQ(BaseGain(60, 40, CONTENT_1_60), 0);
     EXPECT_EQ(BaseGain(60, 60, CONTENT_1_60), 345);
     EXPECT_EQ(BaseGain(50, 60, CONTENT_1_60), 354);
     EXPECT_EQ(BaseGain(65, 66, CONTENT_61_70), 588);
     EXPECT_EQ(BaseGain(79, 78, CONTENT_71_80), 917);
     // check outError() has been called after passing an invalid ContentLevels content
     EXPECT_EQ(BaseGain(79, 1, ContentLevels(999)), 0);
 }
References Acore::XP::BaseGain(), CONTENT_1_60, CONTENT_61_70, and CONTENT_71_80.
TEST() [2/6]
TEST (FormulasTest , Gain)
Definition at line 102 of file FormulasTest.cpp.
 {
     auto worldMock = new WorldMock();
     sWorld.reset((worldMock));
     // TODO: create mocks of Player and Creature
     // Gain(nullptr, nullptr);
 }
References sWorld.
TEST() [3/6]
TEST (FormulasTest , GetColorCode)
Definition at line 48 of file FormulasTest.cpp.
 {
     EXPECT_EQ(GetColorCode(60, 80), XP_RED);
     EXPECT_EQ(GetColorCode(60, 65), XP_RED);
     EXPECT_EQ(GetColorCode(60, 64), XP_ORANGE);
     EXPECT_EQ(GetColorCode(60, 63), XP_ORANGE);
     EXPECT_EQ(GetColorCode(60, 62), XP_YELLOW);
     EXPECT_EQ(GetColorCode(60, 58), XP_YELLOW);
     EXPECT_EQ(GetColorCode(60, 57), XP_GREEN);
     EXPECT_EQ(GetColorCode(60, 52), XP_GREEN);
     EXPECT_EQ(GetColorCode(60, 51), XP_GRAY);
     EXPECT_EQ(GetColorCode(60, 1), XP_GRAY);
 }
References Acore::XP::GetColorCode(), XP_GRAY, XP_GREEN, XP_ORANGE, XP_RED, and XP_YELLOW.
TEST() [4/6]
TEST (FormulasTest , GetGrayLevel)
Definition at line 36 of file FormulasTest.cpp.
 {
     EXPECT_EQ(GetGrayLevel(0), 0);
     EXPECT_EQ(GetGrayLevel(5), 0);
     EXPECT_EQ(GetGrayLevel(6), 1);
     EXPECT_EQ(GetGrayLevel(39), 31);
     EXPECT_EQ(GetGrayLevel(40), 31);
     EXPECT_EQ(GetGrayLevel(59), 47);
     EXPECT_EQ(GetGrayLevel(60), 51);
     EXPECT_EQ(GetGrayLevel(80), 71);
 }
References Acore::XP::GetGrayLevel().
TEST() [5/6]
TEST (FormulasTest , GetZeroDifference)
Definition at line 62 of file FormulasTest.cpp.
 {
     EXPECT_EQ(GetZeroDifference(1), 5);
     EXPECT_EQ(GetZeroDifference(7), 5);
     EXPECT_EQ(GetZeroDifference(8), 6);
     EXPECT_EQ(GetZeroDifference(9), 6);
     EXPECT_EQ(GetZeroDifference(10), 7);
     EXPECT_EQ(GetZeroDifference(11), 7);
     EXPECT_EQ(GetZeroDifference(12), 8);
     EXPECT_EQ(GetZeroDifference(15), 8);
     EXPECT_EQ(GetZeroDifference(16), 9);
     EXPECT_EQ(GetZeroDifference(19), 9);
     EXPECT_EQ(GetZeroDifference(20), 11);
     EXPECT_EQ(GetZeroDifference(29), 11);
     EXPECT_EQ(GetZeroDifference(30), 12);
     EXPECT_EQ(GetZeroDifference(39), 12);
     EXPECT_EQ(GetZeroDifference(40), 13);
     EXPECT_EQ(GetZeroDifference(44), 13);
     EXPECT_EQ(GetZeroDifference(45), 14);
     EXPECT_EQ(GetZeroDifference(49), 14);
     EXPECT_EQ(GetZeroDifference(50), 15);
     EXPECT_EQ(GetZeroDifference(54), 15);
     EXPECT_EQ(GetZeroDifference(55), 16);
     EXPECT_EQ(GetZeroDifference(59), 16);
     EXPECT_EQ(GetZeroDifference(60), 17);
     EXPECT_EQ(GetZeroDifference(80), 17);
 }
References Acore::XP::GetZeroDifference().
TEST() [6/6]
TEST (FormulasTest , hk_honor_at_level)
Definition at line 25 of file FormulasTest.cpp.
 {
     EXPECT_EQ(hk_honor_at_level(80), 124);
     EXPECT_EQ(hk_honor_at_level(80, 2), 248);
     EXPECT_EQ(hk_honor_at_level(80, 0.5), 62);
     EXPECT_EQ(hk_honor_at_level(1), 2);
     EXPECT_EQ(hk_honor_at_level(1, 10), 16);
     EXPECT_EQ(hk_honor_at_level(2), 4);
     EXPECT_EQ(hk_honor_at_level(3), 5);
 }
References Acore::Honor::hk_honor_at_level().
Referenced by frecv(), fsend(), http_get(), http_parse(), http_post(), http_response(), soap_accept(), soap_alloc_block(), soap_alloc_multipart(), soap_append_lab(), soap_array_pointer_lookup(), soap_array_reference(), soap_attachment(), soap_attachment_reference(), soap_attribute(), soap_begin(), soap_begin_count(), soap_begin_recv(), soap_bind(), soap_check_and_mark(), soap_copy_context(), soap_count_attachments(), soap_dealloc(), soap_delegate_deletion(), soap_delete(), soap_done(), soap_element(), soap_element_begin_in(), soap_element_end(), soap_element_end_in(), soap_element_href(), soap_element_id(), soap_element_start_end_out(), soap_embedded(), soap_embedded_id(), soap_end_block(), soap_end_count(), soap_end_recv(), soap_end_send_flush(), soap_finsert(), soap_first_block(), soap_flush(), soap_flush_raw(), soap_free_iht(), soap_free_ns(), soap_free_pht(), soap_free_temp(), soap_getchunkchar(), soap_getdime(), soap_getdimehdr(), soap_getmimehdr(), soap_getpi(), soap_http_get_body_prefix(), soap_http_skip_body(), soap_id_enter(), soap_id_forward(), soap_id_lookup(), soap_id_smart(), soap_ignore(), soap_ignore_element(), soap_init_send(), soap_is_embedded(), soap_is_shaky(), soap_lookup_type(), soap_mark_lookup(), soap_match_array(), soap_match_att(), soap_match_tag(), soap_move(), soap_next_block(), soap_peek_element(), soap_pointer_enter(), soap_pointer_lookup(), soap_poll(), soap_pop_block(), soap_pop_namespace(), soap_push_block(), soap_push_namespace(), soap_push_ns(), soap_putdime(), soap_putdimehdr(), soap_putelement(), soap_putmime(), soap_putmimehdr(), soap_QName(), soap_ready(), soap_recv(), soap_recv_empty_response(), soap_recv_fault(), soap_recv_mime_attachment(), soap_recv_raw(), soap_reference(), soap_register_plugin_arg(), soap_resolve(), soap_resolve_attachment(), soap_revert(), soap_save_block(), soap_send_fault(), soap_set_attr(), soap_string_in(), soap_try_connect_command(), soap_unlink(), soap_update_pointers(), soap_utilize_ns(), soap_value(), soap_wstring_in(), tcp_closesocket(), tcp_connect(), tcp_disconnect(), tcp_gethostbyname(), tcp_select(), and tcp_shutdownsocket().