Azerotcore-wotlk: BanMgr Class Reference
BanMgr Class Reference
#include <BanMgr.h>
Public Member Functions
BanReturn BanAccount (std::string const &AccountName, std::string const &Duration, std::string const &Reason, std::string const &Author)
Ban an account, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
BanReturn BanAccountByPlayerName (std::string const &CharacterName, std::string const &Duration, std::string const &Reason, std::string const &Author)
Ban an account by player name, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
BanReturn BanIP (std::string const &IP, std::string const &Duration, std::string const &Reason, std::string const &Author)
Ban an IP address, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
BanReturn BanCharacter (std::string const &CharacterName, std::string const &Duration, std::string const &Reason, std::string const &Author)
Ban an character, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
bool RemoveBanAccount (std::string const &AccountName)
Remove a ban from an account.
bool RemoveBanAccountByPlayerName (std::string const &CharacterName)
Remove a ban from an player name.
bool RemoveBanIP (std::string const &IP)
Remove a ban from an account.
bool RemoveBanCharacter (std::string const &CharacterName)
Remove a ban from a character.
Static Public Member Functions
static BanMgr * instance ()
Detailed Description
Definition at line 32 of file BanMgr.h.
Member Function Documentation
BanAccount()
BanReturn BanMgr::BanAccount (std::string const & AccountName, std::string const & Duration, std::string const & Reason, std::string const & Author)
Ban an account, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
Disconnect all affected players (for IP it can be several)
Definition at line 36 of file BanMgr.cpp.
 {
     if (AccountName.empty() || Duration.empty())
         return BAN_SYNTAX_ERROR;
     uint32 DurationSecs = TimeStringToSecs(Duration);
     uint32 AccountID = AccountMgr::GetId(AccountName);
     if (!AccountID)
         return BAN_NOTFOUND;
     LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
     // pussywizard: check existing ban to prevent overriding by a shorter one! >_>
     LoginDatabasePreparedStatement* stmtAccountBanned = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BANNED);
     stmtAccountBanned->setUInt32(0, AccountID);
     PreparedQueryResult banresult = LoginDatabase.Query(stmtAccountBanned);
     if (banresult && ((*banresult)[0].GetUInt32() == (*banresult)[1].GetUInt32() || ((*banresult)[1].GetUInt32() > time(nullptr) + DurationSecs && DurationSecs)))
         return BAN_LONGER_EXISTS;
     // make sure there is only one active ban
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_ACCOUNT_NOT_BANNED);
     stmt->setUInt32(0, AccountID);
     trans->Append(stmt);
     // No SQL injection with prepared statements
     stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_ACCOUNT_BANNED);
     stmt->setUInt32(0, AccountID);
     stmt->setUInt32(1, DurationSecs);
     stmt->setString(2, Author);
     stmt->setString(3, Reason);
     trans->Append(stmt);
     if (WorldSession* session = sWorld->FindSession(AccountID))
         if (session->GetPlayerName() != Author)
             session->KickPlayer("Ban Account at condition 'FindSession(account)->GetPlayerName() != author'");
     if (WorldSession* session = sWorld->FindOfflineSession(AccountID))
         if (session->GetPlayerName() != Author)
             session->KickPlayer("Ban Account at condition 'FindOfflineSession(account)->GetPlayerName() != author'");
     LoginDatabase.CommitTransaction(trans);
     if (sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
     {
         bool IsPermanetly = true;
         if (TimeStringToSecs(Duration) > 0)
             IsPermanetly = false;
         if (!IsPermanetly)
             sWorld->SendWorldText(LANG_BAN_ACCOUNT_YOUBANNEDMESSAGE_WORLD, Author.c_str(), AccountName.c_str(), secsToTimeString(TimeStringToSecs(Duration), true).c_str(), Reason.c_str());
         else
             sWorld->SendWorldText(LANG_BAN_ACCOUNT_YOUPERMBANNEDMESSAGE_WORLD, Author.c_str(), AccountName.c_str(), Reason.c_str());
     }
     return BAN_SUCCESS;
 }
References BAN_LONGER_EXISTS, BAN_NOTFOUND, BAN_SUCCESS, BAN_SYNTAX_ERROR, CONFIG_SHOW_BAN_IN_WORLD, AccountMgr::GetId(), LANG_BAN_ACCOUNT_YOUBANNEDMESSAGE_WORLD, LANG_BAN_ACCOUNT_YOUPERMBANNEDMESSAGE_WORLD, LOGIN_INS_ACCOUNT_BANNED, LOGIN_SEL_ACCOUNT_BANNED, LOGIN_UPD_ACCOUNT_NOT_BANNED, LoginDatabase, secsToTimeString(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), sWorld, and TimeStringToSecs().
BanAccountByPlayerName()
BanReturn BanMgr::BanAccountByPlayerName (std::string const & CharacterName, std::string const & Duration, std::string const & Reason, std::string const & Author)
Ban an account by player name, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
Disconnect all affected players (for IP it can be several)
Definition at line 98 of file BanMgr.cpp.
 {
     if (CharacterName.empty() || Duration.empty())
         return BAN_SYNTAX_ERROR;
     uint32 DurationSecs = TimeStringToSecs(Duration);
     uint32 AccountID = sObjectMgr->GetPlayerAccountIdByPlayerName(CharacterName);
     if (!AccountID)
         return BAN_NOTFOUND;
     LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
     // pussywizard: check existing ban to prevent overriding by a shorter one! >_>
     LoginDatabasePreparedStatement* stmtAccountBanned = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BANNED);
     stmtAccountBanned->setUInt32(0, AccountID);
     PreparedQueryResult banresult = LoginDatabase.Query(stmtAccountBanned);
     if (banresult && ((*banresult)[0].GetUInt32() == (*banresult)[1].GetUInt32() || ((*banresult)[1].GetUInt32() > time(nullptr) + DurationSecs && DurationSecs)))
         return BAN_LONGER_EXISTS;
     // make sure there is only one active ban
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_ACCOUNT_NOT_BANNED);
     stmt->setUInt32(0, AccountID);
     trans->Append(stmt);
     // No SQL injection with prepared statements
     stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_ACCOUNT_BANNED);
     stmt->setUInt32(0, AccountID);
     stmt->setUInt32(1, DurationSecs);
     stmt->setString(2, Author);
     stmt->setString(3, Reason);
     trans->Append(stmt);
     if (WorldSession* session = sWorld->FindSession(AccountID))
         if (session->GetPlayerName() != Author)
             session->KickPlayer("Ban Account at condition 'FindSession(account)->GetPlayerName() != author'");
     if (WorldSession* session = sWorld->FindOfflineSession(AccountID))
         if (session->GetPlayerName() != Author)
             session->KickPlayer("Ban Account at condition 'FindOfflineSession(account)->GetPlayerName() != author'");
     LoginDatabase.CommitTransaction(trans);
     if (sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
     {
         bool IsPermanetly = true;
         if (TimeStringToSecs(Duration) > 0)
             IsPermanetly = false;
         std::string AccountName;
         AccountMgr::GetName(AccountID, AccountName);
         if (!IsPermanetly)
             sWorld->SendWorldText(LANG_BAN_ACCOUNT_YOUBANNEDMESSAGE_WORLD, Author.c_str(), AccountName.c_str(), secsToTimeString(TimeStringToSecs(Duration), true).c_str(), Reason.c_str());
         else
             sWorld->SendWorldText(LANG_BAN_ACCOUNT_YOUPERMBANNEDMESSAGE_WORLD, Author.c_str(), AccountName.c_str(), Reason.c_str());
     }
     return BAN_SUCCESS;
 }
References BAN_LONGER_EXISTS, BAN_NOTFOUND, BAN_SUCCESS, BAN_SYNTAX_ERROR, CONFIG_SHOW_BAN_IN_WORLD, AccountMgr::GetName(), LANG_BAN_ACCOUNT_YOUBANNEDMESSAGE_WORLD, LANG_BAN_ACCOUNT_YOUPERMBANNEDMESSAGE_WORLD, LOGIN_INS_ACCOUNT_BANNED, LOGIN_SEL_ACCOUNT_BANNED, LOGIN_UPD_ACCOUNT_NOT_BANNED, LoginDatabase, secsToTimeString(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), sObjectMgr, sWorld, and TimeStringToSecs().
BanCharacter()
BanReturn BanMgr::BanCharacter (std::string const & CharacterName, std::string const & Duration, std::string const & Reason, std::string const & Author)
Ban an character, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
Pick a player to ban if not online
Definition at line 222 of file BanMgr.cpp.
 {
     Player* target = ObjectAccessor::FindPlayerByName(CharacterName, false);
     uint32 DurationSecs = TimeStringToSecs(Duration);
     ObjectGuid TargetGUID;
     if (!target)
     {
         TargetGUID = sWorld->GetGlobalPlayerGUID(CharacterName);
         if (!TargetGUID)
             return BAN_NOTFOUND;
     }
     else
         TargetGUID = target->GetGUID();
     // make sure there is only one active ban
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHARACTER_BAN);
     stmt->setUInt32(0, TargetGUID.GetCounter());
     CharacterDatabase.Execute(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHARACTER_BAN);
     stmt->setUInt32(0, TargetGUID.GetCounter());
     stmt->setUInt32(1, DurationSecs);
     stmt->setString(2, Author);
     stmt->setString(3, Reason);
     CharacterDatabase.Execute(stmt);
     if (target)
         target->GetSession()->KickPlayer("Ban");
     if (sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
     {
         bool IsPermanetly = true;
         if (TimeStringToSecs(Duration) > 0)
             IsPermanetly = false;
         if (!IsPermanetly)
             sWorld->SendWorldText(LANG_BAN_CHARACTER_YOUBANNEDMESSAGE_WORLD, Author.c_str(), CharacterName.c_str(), secsToTimeString(TimeStringToSecs(Duration), true).c_str(), Reason.c_str());
         else
             sWorld->SendWorldText(LANG_BAN_CHARACTER_YOUPERMBANNEDMESSAGE_WORLD, Author.c_str(), CharacterName.c_str(), Reason.c_str());
     }
     return BAN_SUCCESS;
 }
References BAN_NOTFOUND, BAN_SUCCESS, CHAR_INS_CHARACTER_BAN, CHAR_UPD_CHARACTER_BAN, CharacterDatabase, CONFIG_SHOW_BAN_IN_WORLD, ObjectAccessor::FindPlayerByName(), ObjectGuid::GetCounter(), Object::GetGUID(), Player::GetSession(), WorldSession::KickPlayer(), LANG_BAN_CHARACTER_YOUBANNEDMESSAGE_WORLD, LANG_BAN_CHARACTER_YOUPERMBANNEDMESSAGE_WORLD, secsToTimeString(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), sWorld, and TimeStringToSecs().
BanIP()
BanReturn BanMgr::BanIP (std::string const & IP, std::string const & Duration, std::string const & Reason, std::string const & Author)
Ban an IP address, duration will be parsed using TimeStringToSecs if it is positive, otherwise permban.
Disconnect all affected players (for IP it can be several)
Definition at line 164 of file BanMgr.cpp.
 {
     if (IP.empty() || Duration.empty())
         return BAN_SYNTAX_ERROR;
     uint32 DurationSecs = TimeStringToSecs(Duration);
     // No SQL injection with prepared statements
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BY_IP);
     stmt->setString(0, IP);
     PreparedQueryResult resultAccounts = LoginDatabase.Query(stmt);
     stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_IP_BANNED);
     stmt->setString(0, IP);
     stmt->setUInt32(1, DurationSecs);
     stmt->setString(2, Author);
     stmt->setString(3, Reason);
     LoginDatabase.Execute(stmt);
     if (sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
     {
         bool IsPermanetly = true;
         if (TimeStringToSecs(Duration) > 0)
             IsPermanetly = false;
         if (IsPermanetly)
             sWorld->SendWorldText(LANG_BAN_IP_YOUPERMBANNEDMESSAGE_WORLD, Author.c_str(), IP.c_str(), Reason.c_str());
         else
             sWorld->SendWorldText(LANG_BAN_IP_YOUBANNEDMESSAGE_WORLD, Author.c_str(), IP.c_str(), secsToTimeString(TimeStringToSecs(Duration), true).c_str(), Reason.c_str());
     }
     if (!resultAccounts)
         return BAN_SUCCESS;
     LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
     do
     {
         Field* fields = resultAccounts->Fetch();
         uint32 AccountID = fields[0].GetUInt32();
         if (WorldSession* session = sWorld->FindSession(AccountID))
             if (session->GetPlayerName() != Author)
                 session->KickPlayer("Ban IP at condition 'FindSession(account)->GetPlayerName() != author'");
         if (WorldSession* session = sWorld->FindOfflineSession(AccountID))
             if (session->GetPlayerName() != Author)
                 session->KickPlayer("Ban IP at condition 'FindOfflineSession(account)->GetPlayerName() != author'");
     } while (resultAccounts->NextRow());
     LoginDatabase.CommitTransaction(trans);
     return BAN_SUCCESS;
 }
References BAN_SUCCESS, BAN_SYNTAX_ERROR, CONFIG_SHOW_BAN_IN_WORLD, Field::GetUInt32(), LANG_BAN_IP_YOUBANNEDMESSAGE_WORLD, LANG_BAN_IP_YOUPERMBANNEDMESSAGE_WORLD, LOGIN_INS_IP_BANNED, LOGIN_SEL_ACCOUNT_BY_IP, LoginDatabase, secsToTimeString(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), sWorld, and TimeStringToSecs().
instance()
BanMgr * BanMgr::instance () static
Definition at line 29 of file BanMgr.cpp.
 {
     static BanMgr instance;
     return &instance;
 }
RemoveBanAccount()
bool BanMgr::RemoveBanAccount (std::string const & AccountName)
Remove a ban from an account.
Definition at line 270 of file BanMgr.cpp.
 {
     uint32 AccountID = AccountMgr::GetId(AccountName);
     if (!AccountID)
         return false;
     // NO SQL injection as account is uint32
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_ACCOUNT_NOT_BANNED);
     stmt->setUInt32(0, AccountID);
     LoginDatabase.Execute(stmt);
     return true;
 }
References AccountMgr::GetId(), LOGIN_UPD_ACCOUNT_NOT_BANNED, LoginDatabase, and PreparedStatementBase::setUInt32().
RemoveBanAccountByPlayerName()
bool BanMgr::RemoveBanAccountByPlayerName (std::string const & CharacterName)
Remove a ban from an player name.
Definition at line 285 of file BanMgr.cpp.
 {
     uint32 AccountID = sObjectMgr->GetPlayerAccountIdByPlayerName(CharacterName);
     if (!AccountID)
         return false;
     // NO SQL injection as account is uint32
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_ACCOUNT_NOT_BANNED);
     stmt->setUInt32(0, AccountID);
     LoginDatabase.Execute(stmt);
     return true;
 }
References LOGIN_UPD_ACCOUNT_NOT_BANNED, LoginDatabase, PreparedStatementBase::setUInt32(), and sObjectMgr.
RemoveBanCharacter()
bool BanMgr::RemoveBanCharacter (std::string const & CharacterName)
Remove a ban from a character.
Pick a player to ban if not online
Definition at line 310 of file BanMgr.cpp.
 {
     Player* pBanned = ObjectAccessor::FindPlayerByName(CharacterName, false);
     ObjectGuid guid;
     if (!pBanned)
         guid = sWorld->GetGlobalPlayerGUID(CharacterName);
     else
         guid = pBanned->GetGUID();
     if (!guid)
         return false;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHARACTER_BAN);
     stmt->setUInt32(0, guid.GetCounter());
     CharacterDatabase.Execute(stmt);
     return true;
 }
References CHAR_UPD_CHARACTER_BAN, CharacterDatabase, ObjectAccessor::FindPlayerByName(), ObjectGuid::GetCounter(), Object::GetGUID(), PreparedStatementBase::setUInt32(), and sWorld.
RemoveBanIP()
bool BanMgr::RemoveBanIP (std::string const & IP)
Remove a ban from an account.
Definition at line 300 of file BanMgr.cpp.
 {
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_IP_NOT_BANNED);
     stmt->setString(0, IP);
     LoginDatabase.Execute(stmt);
     return true;
 }
References LOGIN_DEL_IP_NOT_BANNED, LoginDatabase, and PreparedStatementBase::setString().
The documentation for this class was generated from the following files:
src/server/game/Misc/BanMgr.h
src/server/game/Misc/BanMgr.cpp