Azerotcore-wotlk: boss_loken::boss_lokenAI Struct Reference
boss_loken::boss_lokenAI Struct Reference
Public Member Functions
boss_lokenAI (Creature *creature)
void MoveInLineOfSight (Unit *) override
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void LokenSpeach (bool hp)
void KilledUnit (Unit *victim) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
bool isActive
uint32 IntroTimer
uint8 HealthCheck
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 72 of file boss_loken.cpp.
Constructor & Destructor Documentation
boss_lokenAI()
boss_loken::boss_lokenAI::boss_lokenAI (Creature * creature) inline
Definition at line 74 of file boss_loken.cpp.
                                          : ScriptedAI(creature)
         {
             m_pInstance = creature->GetInstanceScript();
             if (m_pInstance)
                 isActive = m_pInstance->GetData(TYPE_LOKEN_INTRO);
         }
References ZoneScript::GetData(), WorldObject::GetInstanceScript(), isActive, m_pInstance, and TYPE_LOKEN_INTRO.
Member Function Documentation
EnterCombat()
void boss_loken::boss_lokenAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 115 of file boss_loken.cpp.
         {
             me->SetInCombatWithZone();
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_ARC_LIGHTNING, 10000);
             events.ScheduleEvent(EVENT_SHOCKWAVE, 3000);
             events.ScheduleEvent(EVENT_LIGHTNING_NOVA, 15000);
             if (m_pInstance)
             {
                 m_pInstance->SetData(TYPE_LOKEN, IN_PROGRESS);
                 if (me->GetMap()->IsHeroic())
                     m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_TIMELY_DEATH);
             }
         }
References ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_TIMELY_DEATH, InstanceScript::DoStartTimedAchievement(), EVENT_ARC_LIGHTNING, EVENT_LIGHTNING_NOVA, EVENT_SHOCKWAVE, WorldObject::GetMap(), IN_PROGRESS, Map::IsHeroic(), m_pInstance, ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and TYPE_LOKEN.
JustDied()
void boss_loken::boss_lokenAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 133 of file boss_loken.cpp.
         {
             Talk(SAY_DEATH);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_LOKEN, DONE);
         }
References DONE, m_pInstance, SAY_DEATH, ZoneScript::SetData(), CreatureAI::Talk(), and TYPE_LOKEN.
KilledUnit()
void boss_loken::boss_lokenAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 162 of file boss_loken.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
LokenSpeach()
void boss_loken::boss_lokenAI::LokenSpeach (bool hp) inline
Definition at line 141 of file boss_loken.cpp.
         {
             if (hp)
             {
                 switch(HealthCheck)
                 {
                     case 75:
                         Talk(SAY_75HEALTH);
                         break;
                     case 50:
                         Talk(SAY_50HEALTH);
                         break;
                     case 25:
                         Talk(SAY_25HEALTH);
                         break;
                 }
             }
             else
                 Talk(SAY_NOVA);
         }
References HealthCheck, SAY_25HEALTH, SAY_50HEALTH, SAY_75HEALTH, SAY_NOVA, and CreatureAI::Talk().
Referenced by UpdateAI().
MoveInLineOfSight()
void boss_loken::boss_lokenAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 88 of file boss_loken.cpp.
 { }
Reset()
void boss_loken::boss_lokenAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 90 of file boss_loken.cpp.
         {
             events.Reset();
             if (m_pInstance)
             {
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_TIMELY_DEATH);
                 m_pInstance->SetData(TYPE_LOKEN, NOT_STARTED);
             }
             HealthCheck = 75;
             IntroTimer = 0;
             me->RemoveAllAuras();
             if (!isActive)
             {
                 me->SetControlled(true, UNIT_STATE_STUNNED);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             }
             else
             {
                 me->SetControlled(false, UNIT_STATE_STUNNED);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             }
         }
References ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_TIMELY_DEATH, InstanceScript::DoStopTimedAchievement(), HealthCheck, IntroTimer, isActive, m_pInstance, ScriptedAI::me, NOT_STARTED, Unit::RemoveAllAuras(), Object::RemoveFlag(), Unit::SetControlled(), ZoneScript::SetData(), Object::SetFlag(), TYPE_LOKEN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STATE_STUNNED.
UpdateAI()
void boss_loken::boss_lokenAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 170 of file boss_loken.cpp.
         {
             if (!isActive)
             {
                 IntroTimer += diff;
                 if (IntroTimer > 5000 && IntroTimer < 10000)
                 {
                     if (SelectTargetFromPlayerList(60))
                     {
                         Talk(SAY_INTRO_1);
                         IntroTimer = 10000;
                     }
                     else
                         IntroTimer = 0;
                 }
                 if (IntroTimer >= 30000 && IntroTimer < 40000)
                 {
                     Talk(SAY_INTRO_2);
                     IntroTimer = 40000;
                 }
                 if (IntroTimer >= 60000)
                 {
                     isActive = true;
                     if (m_pInstance)
                         m_pInstance->SetData(TYPE_LOKEN_INTRO, 1);
                     me->SetControlled(false, UNIT_STATE_STUNNED);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     if (Player* target = SelectTargetFromPlayerList(80))
                         AttackStart(target);
                 }
                 return;
             }
             //Return since we have no target
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_HEALTH:
                     if (HealthBelowPct(HealthCheck))
                     {
                         LokenSpeach(true);
                         HealthCheck -= 25;
                     }
                     events.RepeatEvent(1000);
                     break;
                 case EVENT_LIGHTNING_NOVA:
                     events.RepeatEvent(15000);
                     me->CastSpell(me, SPELL_LIGHTNING_NOVA_VISUAL, true);
                     me->CastSpell(me, SPELL_LIGHTNING_NOVA_THUNDERS, true);
                     events.DelayEvents(5001);
                     events.ScheduleEvent(EVENT_AURA_REMOVE, me->GetMap()->IsHeroic() ? 4000 : 5000);
                     me->CastSpell(me, me->GetMap()->IsHeroic() ? SPELL_LIGHTNING_NOVA_H : SPELL_LIGHTNING_NOVA_N, false);
                     break;
                 case EVENT_SHOCKWAVE:
                     me->CastSpell(me, me->GetMap()->IsHeroic() ? SPELL_PULSING_SHOCKWAVE_H : SPELL_PULSING_SHOCKWAVE_N, false);
                     break;
                 case EVENT_ARC_LIGHTNING:
                     if (Unit* target = SelectTargetFromPlayerList(100, SPELL_ARC_LIGHTNING))
                         me->CastSpell(target, SPELL_ARC_LIGHTNING, false);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_AURA_REMOVE:
                     me->RemoveAura(SPELL_LIGHTNING_NOVA_THUNDERS);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ScriptedAI::AttackStart(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARC_LIGHTNING, EVENT_AURA_REMOVE, EVENT_CHECK_HEALTH, EVENT_LIGHTNING_NOVA, EVENT_SHOCKWAVE, WorldObject::GetMap(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), HealthCheck, IntroTimer, isActive, Map::IsHeroic(), LokenSpeach(), m_pInstance, ScriptedAI::me, Unit::RemoveAura(), Object::RemoveFlag(), SAY_INTRO_1, SAY_INTRO_2, ScriptedAI::SelectTargetFromPlayerList(), Unit::SetControlled(), ZoneScript::SetData(), SPELL_ARC_LIGHTNING, SPELL_LIGHTNING_NOVA_H, SPELL_LIGHTNING_NOVA_N, SPELL_LIGHTNING_NOVA_THUNDERS, SPELL_LIGHTNING_NOVA_VISUAL, SPELL_PULSING_SHOCKWAVE_H, SPELL_PULSING_SHOCKWAVE_N, CreatureAI::Talk(), TYPE_LOKEN_INTRO, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_loken::boss_lokenAI::events
Definition at line 82 of file boss_loken.cpp.
HealthCheck
uint8 boss_loken::boss_lokenAI::HealthCheck
Definition at line 86 of file boss_loken.cpp.
Referenced by LokenSpeach(), Reset(), and UpdateAI().
IntroTimer
uint32 boss_loken::boss_lokenAI::IntroTimer
Definition at line 85 of file boss_loken.cpp.
Referenced by Reset(), and UpdateAI().
isActive
bool boss_loken::boss_lokenAI::isActive
Definition at line 84 of file boss_loken.cpp.
Referenced by boss_lokenAI(), Reset(), and UpdateAI().
m_pInstance
InstanceScript* boss_loken::boss_lokenAI::m_pInstance
Definition at line 81 of file boss_loken.cpp.
Referenced by boss_lokenAI(), EnterCombat(), JustDied(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_loken.cpp