Azerotcore-wotlk: RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell Struct Reference
RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell Struct Reference
#include <RegularGrid.h>
Public Member Functions
bool operator== (const Cell &c2) const
bool isValid () const
Static Public Member Functions
static Cell ComputeCell (float fx, float fy)
Public Attributes
int x
int y
Detailed Description
template<class T, class Node, class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>>
struct RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell
Definition at line 146 of file RegularGrid.h.
Member Function Documentation
ComputeCell()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>> static Cell RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::ComputeCell (float fx, float fy) inline static
Definition at line 151 of file RegularGrid.h.
         {
             Cell c = { int(fx * (1.f / CELL_SIZE) + (CELL_NUMBER / 2)), int(fy * (1.f / CELL_SIZE) + (CELL_NUMBER / 2)) };
             return c;
         }
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::CELL_NUMBER, and CELL_SIZE.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::getGridFor(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay().
isValid()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>> bool RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::isValid () const inline
Definition at line 157 of file RegularGrid.h.
 { return x >= 0 && x < CELL_NUMBER && y >= 0 && y < CELL_NUMBER;}
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::CELL_NUMBER, RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::y.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay().
operator==()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>> bool RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::operator== (const Cell & c2) const inline
Definition at line 149 of file RegularGrid.h.
 { return x == c2.x && y == c2.y;}
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::y.
Member Data Documentation
x
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>> int RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::x
Definition at line 148 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::getGridFor(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::isValid(), and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::operator==().
y
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class PositionFunc = PositionTrait<T>> int RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::y
Definition at line 148 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::getGridFor(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::isValid(), and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::Cell::operator==().
The documentation for this struct was generated from the following file:
src/common/Collision/RegularGrid.h