Azerotcore-wotlk: boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI Struct Reference
boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI Struct Reference
Public Member Functions
boss_thorim_gauntlet_npcsAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool _isCaster
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1280 of file boss_thorim.cpp.
Constructor & Destructor Documentation
boss_thorim_gauntlet_npcsAI()
boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::boss_thorim_gauntlet_npcsAI (Creature * pCreature) inline
Definition at line 1282 of file boss_thorim.cpp.
 : ScriptedAI(pCreature) { }
Member Function Documentation
EnterCombat()
void boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1293 of file boss_thorim.cpp.
         {
             if (me->GetEntry() == NPC_IRON_RING_GUARD)
             {
                 events.ScheduleEvent(EVENT_IR_GUARD_IMPALE, 12000);
                 events.ScheduleEvent(EVENT_IR_GUARD_WHIRL, 5000);
             }
             else if (me->GetEntry() == NPC_DARK_RUNE_ACOLYTE_I)
             {
                 events.ScheduleEvent(EVENT_DR_ACOLYTE_GH, 10000);
                 events.ScheduleEvent(EVENT_DR_ACOLYTE_HS, 5000);
                 events.ScheduleEvent(EVENT_DR_ACOLYTE_R, 7000);
             }
             else if (me->GetEntry() == NPC_IRON_HONOR_GUARD)
             {
                 events.ScheduleEvent(EVENT_IH_GUARD_CLEAVE, 6000);
                 events.ScheduleEvent(EVENT_IH_GUARD_HAMSTRING, 9000);
                 events.ScheduleEvent(EVENT_IH_GUARD_SHIELD_SMASH, 15000);
                 if (Creature* runeGiant = me->FindNearestCreature(NPC_ANCIENT_RUNE_GIANT, 200.0f))
                     runeGiant->AI()->DoAction(ACTION_IRON_HONOR_DIED);
             }
             me->CallForHelp(25);
         }
References ACTION_IRON_HONOR_DIED, Creature::CallForHelp(), EVENT_DR_ACOLYTE_GH, EVENT_DR_ACOLYTE_HS, EVENT_DR_ACOLYTE_R, EVENT_IH_GUARD_CLEAVE, EVENT_IH_GUARD_HAMSTRING, EVENT_IH_GUARD_SHIELD_SMASH, EVENT_IR_GUARD_IMPALE, EVENT_IR_GUARD_WHIRL, WorldObject::FindNearestCreature(), Object::GetEntry(), ScriptedAI::me, NPC_ANCIENT_RUNE_GIANT, NPC_DARK_RUNE_ACOLYTE_I, NPC_IRON_HONOR_GUARD, and NPC_IRON_RING_GUARD.
Reset()
void boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1287 of file boss_thorim.cpp.
         {
             events.Reset();
             _isCaster = (me->GetEntry() == NPC_DARK_RUNE_ACOLYTE_G);
         }
References _isCaster, Object::GetEntry(), ScriptedAI::me, and NPC_DARK_RUNE_ACOLYTE_G.
UpdateAI()
void boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1319 of file boss_thorim.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_IR_GUARD_IMPALE:
                     me->CastSpell(me->GetVictim(), SPELL_IMPALE, false);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_IR_GUARD_WHIRL:
                     me->CastSpell(me->GetVictim(), SPELL_WHIRLING_TRIP, false);
                     events.RepeatEvent(5000);
                     break;
                 case EVENT_DR_ACOLYTE_GH:
                     if (HealthBelowPct(60))
                         me->CastSpell(me, SPELL_GREATER_HEAL, false);
                     else if (Unit* target = DoSelectLowestHpFriendly(60.0f, 20))
                         me->CastSpell(target, SPELL_GREATER_HEAL, false);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_DR_ACOLYTE_HS:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_HOLY_SMITE, false);
                     events.RepeatEvent(1600);
                     break;
                 case EVENT_DR_ACOLYTE_R:
                     if (HealthBelowPct(75) && !me->HasAura(SPELL_RENEW))
                         me->CastSpell(me, SPELL_GREATER_HEAL, false);
                     else if (Unit* target = DoSelectLowestHpFriendly(60.0f, 10))
                         me->CastSpell(target, SPELL_RENEW, false);
                     events.RepeatEvent(7000);
                     break;
                 case EVENT_IH_GUARD_CLEAVE:
                     me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                     events.RepeatEvent(6000);
                     break;
                 case EVENT_IH_GUARD_HAMSTRING:
                     me->CastSpell(me->GetVictim(), SPELL_HAMSTRING, false);
                     events.RepeatEvent(9000);
                     break;
                 case EVENT_IH_GUARD_SHIELD_SMASH:
                     me->CastSpell(me->GetVictim(), SPELL_SHIELD_SMASH, false);
                     events.RepeatEvent(15000);
                     break;
             }
             if (!_isCaster || (me->GetPower(POWER_MANA) * 100 / me->GetMaxPower(POWER_MANA) < 10))
                 DoMeleeAttackIfReady();
         }
References _isCaster, Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSelectLowestHpFriendly(), EVENT_DR_ACOLYTE_GH, EVENT_DR_ACOLYTE_HS, EVENT_DR_ACOLYTE_R, EVENT_IH_GUARD_CLEAVE, EVENT_IH_GUARD_HAMSTRING, EVENT_IH_GUARD_SHIELD_SMASH, EVENT_IR_GUARD_IMPALE, EVENT_IR_GUARD_WHIRL, Unit::GetMaxPower(), Unit::GetPower(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, POWER_MANA, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_CLEAVE, SPELL_GREATER_HEAL, SPELL_HAMSTRING, SPELL_HOLY_SMITE, SPELL_IMPALE, SPELL_RENEW, SPELL_SHIELD_SMASH, SPELL_WHIRLING_TRIP, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_isCaster
bool boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::_isCaster
Definition at line 1285 of file boss_thorim.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::events
Definition at line 1284 of file boss_thorim.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp