Azerotcore-wotlk: deps/argon2/argon2/blake2/blake2.h File Reference
blake2.h File Reference
#include "../argon2.h"
Classes
struct __blake2b_param
struct __blake2b_state
Typedefs
typedef struct __blake2b_param blake2b_param
typedef struct __blake2b_state blake2b_state
Enumerations
enum blake2b_constant {
BLAKE2B_BLOCKBYTES = 128 , BLAKE2B_OUTBYTES = 64 , BLAKE2B_KEYBYTES = 64 , BLAKE2B_SALTBYTES = 16 ,
BLAKE2B_PERSONALBYTES = 16
}
enum { blake2_size_check_0 = 1 / !!(CHAR_BIT == 8) , blake2_size_check_2 }
Functions
ARGON2_LOCAL int blake2b_init (blake2b_state *S, size_t outlen)
ARGON2_LOCAL int blake2b_init_key (blake2b_state *S, size_t outlen, const void *key, size_t keylen)
ARGON2_LOCAL int blake2b_init_param (blake2b_state *S, const blake2b_param *P)
ARGON2_LOCAL int blake2b_update (blake2b_state *S, const void *in, size_t inlen)
ARGON2_LOCAL int blake2b_final (blake2b_state *S, void *out, size_t outlen)
ARGON2_LOCAL int blake2b (void *out, size_t outlen, const void *in, size_t inlen, const void *key, size_t keylen)
ARGON2_LOCAL int blake2b_long (void *out, size_t outlen, const void *in, size_t inlen)
Typedef Documentation
blake2b_param
typedef struct __blake2b_param blake2b_param
blake2b_state
typedef struct __blake2b_state blake2b_state
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
blake2_size_check_0
blake2_size_check_2
Definition at line 63 of file blake2.h.
      {
     blake2_size_check_0 = 1 / !!(CHAR_BIT == 8),
     blake2_size_check_2 =
         1 / !!(sizeof(blake2b_param) == sizeof(uint64_t) * CHAR_BIT)
 };
blake2b_constant
enum blake2b_constant
Enumerator
BLAKE2B_BLOCKBYTES
BLAKE2B_OUTBYTES
BLAKE2B_KEYBYTES
BLAKE2B_SALTBYTES
BLAKE2B_PERSONALBYTES
Definition at line 27 of file blake2.h.
                       {
     BLAKE2B_BLOCKBYTES = 128,
     BLAKE2B_OUTBYTES = 64,
     BLAKE2B_KEYBYTES = 64,
     BLAKE2B_SALTBYTES = 16,
     BLAKE2B_PERSONALBYTES = 16
 };
Function Documentation
blake2b()
ARGON2_LOCAL int blake2b (void * out, size_t outlen, const void * in, size_t inlen, const void * key, size_t keylen)
Definition at line 294 of file blake2b.c.
{
     blake2b_state S;
     int ret = -1;
     /* Verify parameters */
     if (NULL == in && inlen > 0) {
         goto fail;
     }
     if (NULL == out || outlen == 0 || outlen > BLAKE2B_OUTBYTES) {
         goto fail;
     }
     if ((NULL == key && keylen > 0) || keylen > BLAKE2B_KEYBYTES) {
         goto fail;
     }
     if (keylen > 0) {
         if (blake2b_init_key(&S, outlen, key, keylen) < 0) {
             goto fail;
         }
     } else {
         if (blake2b_init(&S, outlen) < 0) {
             goto fail;
         }
     }
     if (blake2b_update(&S, in, inlen) < 0) {
         goto fail;
     }
     ret = blake2b_final(&S, out, outlen);
 fail:
     clear_internal_memory(&S, sizeof(S));
     return ret;
 }
References blake2b_final(), blake2b_init(), blake2b_init_key(), BLAKE2B_KEYBYTES, BLAKE2B_OUTBYTES, blake2b_update(), clear_internal_memory(), NULL, and ret.
Referenced by blake2b_long().
blake2b_final()
ARGON2_LOCAL int blake2b_final (blake2b_state * S, void * out, size_t outlen)
Definition at line 264 of file blake2b.c.
{
     uint8_t buffer[BLAKE2B_OUTBYTES] = {0};
     unsigned int i;
     /* Sanity checks */
     if (S == NULL || out == NULL || outlen < S->outlen) {
         return -1;
     }
     /* Is this a reused state? */
     if (S->f[0] != 0) {
         return -1;
     }
     blake2b_increment_counter(S, S->buflen);
     blake2b_set_lastblock(S);
     memset(&S->buf[S->buflen], 0, BLAKE2B_BLOCKBYTES - S->buflen); /* Padding */
     blake2b_compress(S, S->buf);
     for (i = 0; i < 8; ++i) { /* Output full hash to temp buffer */
         store64(buffer + sizeof(S->h[i]) * i, S->h[i]);
     }
     memcpy(out, buffer, S->outlen);
     clear_internal_memory(buffer, sizeof(buffer));
     clear_internal_memory(S->buf, sizeof(S->buf));
     clear_internal_memory(S->h, sizeof(S->h));
     return 0;
 }
References BLAKE2B_BLOCKBYTES, blake2b_compress(), blake2b_increment_counter(), BLAKE2B_OUTBYTES, blake2b_set_lastblock(), __blake2b_state::buf, __blake2b_state::buflen, clear_internal_memory(), __blake2b_state::f, __blake2b_state::h, memcpy, memset, NULL, __blake2b_state::outlen, and store64().
Referenced by blake2b(), blake2b_long(), and initial_hash().
blake2b_init()
ARGON2_LOCAL int blake2b_init (blake2b_state * S, size_t outlen)
Definition at line 91 of file blake2b.c.
{
     blake2b_param P;
     if (S == NULL) {
         return -1;
     }
     if ((outlen == 0) || (outlen > BLAKE2B_OUTBYTES)) {
         blake2b_invalidate_state(S);
         return -1;
     }
     /* Setup Parameter Block for unkeyed BLAKE2 */
     P.digest_length = (uint8_t)outlen;
     P.key_length = 0;
     P.fanout = 1;
     P.depth = 1;
     P.leaf_length = 0;
     P.node_offset = 0;
     P.node_depth = 0;
     P.inner_length = 0;
     memset(P.reserved, 0, sizeof(P.reserved));
     memset(P.salt, 0, sizeof(P.salt));
     memset(P.personal, 0, sizeof(P.personal));
     return blake2b_init_param(S, &P);
 }
References blake2b_init_param(), blake2b_invalidate_state(), BLAKE2B_OUTBYTES, memset, NULL, and P.
Referenced by blake2b(), blake2b_long(), and initial_hash().
blake2b_init_key()
ARGON2_LOCAL int blake2b_init_key (blake2b_state * S, size_t outlen, const void * key, size_t keylen)
Definition at line 119 of file blake2b.c.
{
     blake2b_param P;
     if (S == NULL) {
         return -1;
     }
     if ((outlen == 0) || (outlen > BLAKE2B_OUTBYTES)) {
         blake2b_invalidate_state(S);
         return -1;
     }
     if ((key == 0) || (keylen == 0) || (keylen > BLAKE2B_KEYBYTES)) {
         blake2b_invalidate_state(S);
         return -1;
     }
     /* Setup Parameter Block for keyed BLAKE2 */
     P.digest_length = (uint8_t)outlen;
     P.key_length = (uint8_t)keylen;
     P.fanout = 1;
     P.depth = 1;
     P.leaf_length = 0;
     P.node_offset = 0;
     P.node_depth = 0;
     P.inner_length = 0;
     memset(P.reserved, 0, sizeof(P.reserved));
     memset(P.salt, 0, sizeof(P.salt));
     memset(P.personal, 0, sizeof(P.personal));
     if (blake2b_init_param(S, &P) < 0) {
         blake2b_invalidate_state(S);
         return -1;
     }
     {
         uint8_t block[BLAKE2B_BLOCKBYTES];
         memset(block, 0, BLAKE2B_BLOCKBYTES);
         memcpy(block, key, keylen);
         blake2b_update(S, block, BLAKE2B_BLOCKBYTES);
         /* Burn the key from stack */
         clear_internal_memory(block, BLAKE2B_BLOCKBYTES);
     }
     return 0;
 }
References BLAKE2B_BLOCKBYTES, blake2b_init_param(), blake2b_invalidate_state(), BLAKE2B_KEYBYTES, BLAKE2B_OUTBYTES, blake2b_update(), clear_internal_memory(), memcpy, memset, NULL, and P.
Referenced by blake2b().
blake2b_init_param()
ARGON2_LOCAL int blake2b_init_param (blake2b_state * S, const blake2b_param * P)
Definition at line 73 of file blake2b.c.
{
     const unsigned char *p = (const unsigned char *)P;
     unsigned int i;
     if (NULL == P || NULL == S) {
         return -1;
     }
     blake2b_init0(S);
     /* IV XOR Parameter Block */
     for (i = 0; i < 8; ++i) {
         S->h[i] ^= load64(&p[i * sizeof(S->h[i])]);
     }
     S->outlen = P->digest_length;
     return 0;
 }
References blake2b_init0(), __blake2b_state::h, load64(), NULL, __blake2b_state::outlen, and P.
Referenced by blake2b_init(), and blake2b_init_key().
blake2b_long()
ARGON2_LOCAL int blake2b_long (void * out, size_t outlen, const void * in, size_t inlen)
Definition at line 333 of file blake2b.c.
{
     uint8_t *out = (uint8_t *)pout;
     blake2b_state blake_state;
     uint8_t outlen_bytes[sizeof(uint32_t)] = {0};
     int ret = -1;
     if (outlen > UINT32_MAX) {
         goto fail;
     }
     /* Ensure little-endian byte order! */
     store32(outlen_bytes, (uint32_t)outlen);
 #define TRY(statement)                                                         \
     do {                                                                       \
         ret = statement;                                                       \
         if (ret < 0) {                                                         \
             goto fail;                                                         \
         }                                                                      \
     } while ((void)0, 0)
     if (outlen <= BLAKE2B_OUTBYTES) {
         TRY(blake2b_init(&blake_state, outlen));
         TRY(blake2b_update(&blake_state, outlen_bytes, sizeof(outlen_bytes)));
         TRY(blake2b_update(&blake_state, in, inlen));
         TRY(blake2b_final(&blake_state, out, outlen));
     } else {
         uint32_t toproduce;
         uint8_t out_buffer[BLAKE2B_OUTBYTES];
         uint8_t in_buffer[BLAKE2B_OUTBYTES];
         TRY(blake2b_init(&blake_state, BLAKE2B_OUTBYTES));
         TRY(blake2b_update(&blake_state, outlen_bytes, sizeof(outlen_bytes)));
         TRY(blake2b_update(&blake_state, in, inlen));
         TRY(blake2b_final(&blake_state, out_buffer, BLAKE2B_OUTBYTES));
         memcpy(out, out_buffer, BLAKE2B_OUTBYTES / 2);
         out += BLAKE2B_OUTBYTES / 2;
         toproduce = (uint32_t)outlen - BLAKE2B_OUTBYTES / 2;
         while (toproduce > BLAKE2B_OUTBYTES) {
             memcpy(in_buffer, out_buffer, BLAKE2B_OUTBYTES);
             TRY(blake2b(out_buffer, BLAKE2B_OUTBYTES, in_buffer,
                         BLAKE2B_OUTBYTES, NULL, 0));
             memcpy(out, out_buffer, BLAKE2B_OUTBYTES / 2);
             out += BLAKE2B_OUTBYTES / 2;
             toproduce -= BLAKE2B_OUTBYTES / 2;
         }
         memcpy(in_buffer, out_buffer, BLAKE2B_OUTBYTES);
         TRY(blake2b(out_buffer, toproduce, in_buffer, BLAKE2B_OUTBYTES, NULL,
                     0));
         memcpy(out, out_buffer, toproduce);
     }
 fail:
     clear_internal_memory(&blake_state, sizeof(blake_state));
     return ret;
 #undef TRY
 }
References blake2b(), blake2b_final(), blake2b_init(), BLAKE2B_OUTBYTES, blake2b_update(), clear_internal_memory(), memcpy, NULL, ret, store32(), TRY, and UINT32_MAX.
Referenced by fill_first_blocks(), and finalize().
blake2b_update()
ARGON2_LOCAL int blake2b_update (blake2b_state * S, const void * in, size_t inlen)
Definition at line 224 of file blake2b.c.
{
     const uint8_t *pin = (const uint8_t *)in;
     if (inlen == 0) {
         return 0;
     }
     /* Sanity check */
     if (S == NULL || in == NULL) {
         return -1;
     }
     /* Is this a reused state? */
     if (S->f[0] != 0) {
         return -1;
     }
     if (S->buflen + inlen > BLAKE2B_BLOCKBYTES) {
         /* Complete current block */
         size_t left = S->buflen;
         size_t fill = BLAKE2B_BLOCKBYTES - left;
         memcpy(&S->buf[left], pin, fill);
         blake2b_increment_counter(S, BLAKE2B_BLOCKBYTES);
         blake2b_compress(S, S->buf);
         S->buflen = 0;
         inlen -= fill;
         pin += fill;
         /* Avoid buffer copies when possible */
         while (inlen > BLAKE2B_BLOCKBYTES) {
             blake2b_increment_counter(S, BLAKE2B_BLOCKBYTES);
             blake2b_compress(S, pin);
             inlen -= BLAKE2B_BLOCKBYTES;
             pin += BLAKE2B_BLOCKBYTES;
         }
     }
     memcpy(&S->buf[S->buflen], pin, inlen);
     S->buflen += (unsigned int)inlen;
     return 0;
 }
References BLAKE2B_BLOCKBYTES, blake2b_compress(), blake2b_increment_counter(), __blake2b_state::buf, __blake2b_state::buflen, __blake2b_state::f, fill(), align::left, memcpy, and NULL.
Referenced by blake2b(), blake2b_init_key(), blake2b_long(), and initial_hash().