Azerotcore-wotlk: deps/mysqllite/mysys/mf_fn_ext.c File Reference
mf_fn_ext.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
char * fn_ext (const char *name)
Function Documentation
fn_ext()
char* fn_ext (const char * name)
Definition at line 36 of file mf_fn_ext.c.
 {
   register const char *pos, *gpos;
   DBUG_ENTER("fn_ext");
   DBUG_PRINT("mfunkt",("name: '%s'",name));
 #if defined(FN_DEVCHAR) || defined(BASKSLASH_MBTAIL)
   {
     char buff[FN_REFLEN];
     size_t res_length;
     gpos= name+ dirname_part(buff,(char*) name, &res_length);
   }
 #else
   if (!(gpos= strrchr(name, FN_LIBCHAR)))
     gpos= name;
 #endif
   pos=strchr(gpos,FN_EXTCHAR);
   DBUG_RETURN((char*) (pos ? pos : strend(gpos)));
 } /* fn_ext */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), FN_EXTCHAR, FN_LIBCHAR, FN_REFLEN, pos(), and strend().
Referenced by find_file_in_path(), my_print_default_files(), search_default_file(), and search_default_file_with_ext().