Azerotcore-wotlk: PlayerOrPetCheck Class Reference
PlayerOrPetCheck Class Reference
#include <ScriptedCreature.h>
Public Member Functions
bool operator() (WorldObject *unit) const
Detailed Description
Definition at line 161 of file ScriptedCreature.h.
Member Function Documentation
operator()()
bool PlayerOrPetCheck::operator() (WorldObject * unit) const inline
Definition at line 164 of file ScriptedCreature.h.
     {
         if (unit->GetTypeId() != TYPEID_PLAYER)
             if (!unit->ToUnit()->GetOwnerGUID().IsPlayer())
                 return true;
         return false;
     }
References Unit::GetOwnerGUID(), Object::GetTypeId(), ObjectGuid::IsPlayer(), Object::ToUnit(), and TYPEID_PLAYER.
The documentation for this class was generated from the following file:
src/server/game/AI/ScriptedAI/ScriptedCreature.h