Azerotcore-wotlk: go_tadpole_cage::go_tadpole_cageAI Struct Reference
go_tadpole_cage::go_tadpole_cageAI Struct Reference
Public Member Functions
go_tadpole_cageAI (GameObject *gameObject)
void SummonTadpoles ()
void OnStateChanged (uint32 state, Unit *) override
void UpdateAI (uint32) override
bool GossipHello (Player *player, bool) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Public Attributes
uint8 requireSummon
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 284 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_tadpole_cageAI()
go_tadpole_cage::go_tadpole_cageAI::go_tadpole_cageAI (GameObject * gameObject) inline
Definition at line 286 of file go_scripts.cpp.
                                                   : GameObjectAI(gameObject)
         {
             requireSummon = 2;
         }
References requireSummon.
Member Function Documentation
GossipHello()
bool go_tadpole_cage::go_tadpole_cageAI::GossipHello (Player * player, bool) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 313 of file go_scripts.cpp.
         {
             if (requireSummon)
                 return false;
             requireSummon = 1;
             if (player->GetQuestStatus(QUEST_OH_NOES_THE_TADPOLES) == QUEST_STATUS_INCOMPLETE)
             {
                 std::list<Creature*> cList;
                 GetCreatureListWithEntryInGrid(cList, me, NPC_WINTERFIN_TADPOLE, 5.0f);
                 for (std::list<Creature*>::const_iterator itr = cList.begin(); itr != cList.end(); ++itr)
                 {
                     player->KilledMonsterCredit(NPC_WINTERFIN_TADPOLE);
                     (*itr)->DespawnOrUnsummon(urand(45000, 60000));
                     (*itr)->GetMotionMaster()->MoveFollow(player, 1.0f, frand(0.0f, 2 * M_PI), MOTION_SLOT_CONTROLLED);
                 }
             }
             return false;
         }
References frand(), GetCreatureListWithEntryInGrid(), Player::GetQuestStatus(), Player::KilledMonsterCredit(), GameObjectAI::me, MOTION_SLOT_CONTROLLED, NPC_WINTERFIN_TADPOLE, QUEST_OH_NOES_THE_TADPOLES, QUEST_STATUS_INCOMPLETE, requireSummon, and urand().
OnStateChanged()
void go_tadpole_cage::go_tadpole_cageAI::OnStateChanged (uint32 state, Unit *) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 301 of file go_scripts.cpp.
         {
             if (requireSummon == 1 && state == GO_READY)
                 requireSummon = 2;
         }
References GO_READY, and requireSummon.
SummonTadpoles()
void go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles () inline
Definition at line 293 of file go_scripts.cpp.
         {
             requireSummon = 0;
             int8 count = urand(1, 3);
             for (int8 i = 0; i < count; ++i)
                 me->SummonCreature(NPC_WINTERFIN_TADPOLE, me->GetPositionX() + cos(2 * M_PI * i / 3.0f) * 0.60f, me->GetPositionY() + sin(2 * M_PI * i / 3.0f) * 0.60f, me->GetPositionZ(), me->GetOrientation(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
         }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GameObjectAI::me, NPC_WINTERFIN_TADPOLE, requireSummon, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void go_tadpole_cage::go_tadpole_cageAI::UpdateAI (uint32) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 307 of file go_scripts.cpp.
         {
             if (me->isSpawned() && requireSummon == 2)
                 SummonTadpoles();
         }
References GameObject::isSpawned(), GameObjectAI::me, requireSummon, and SummonTadpoles().
Member Data Documentation
requireSummon
uint8 go_tadpole_cage::go_tadpole_cageAI::requireSummon
Definition at line 291 of file go_scripts.cpp.
Referenced by go_tadpole_cageAI(), GossipHello(), OnStateChanged(), SummonTadpoles(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/World/go_scripts.cpp