Azerotcore-wotlk: go_main_chambers_access_panel Class Reference
go_main_chambers_access_panel Class Reference
Public Member Functions
go_main_chambers_access_panel ()
bool OnGossipHello (Player *, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 22 of file instance_steam_vault.cpp.
Constructor & Destructor Documentation
go_main_chambers_access_panel()
go_main_chambers_access_panel::go_main_chambers_access_panel () inline
Definition at line 25 of file instance_steam_vault.cpp.
 : GameObjectScript("go_main_chambers_access_panel") { }
Member Function Documentation
OnGossipHello()
bool go_main_chambers_access_panel::OnGossipHello (Player * , GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 27 of file instance_steam_vault.cpp.
     {
         InstanceScript* instance = go->GetInstanceScript();
         if (!instance)
             return false;
         if (go->GetEntry() == GO_ACCESS_PANEL_HYDRO)
             if (instance->GetData(TYPE_HYDROMANCER_THESPIA) == DONE)
             {
                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                 instance->SetData(TYPE_HYDROMANCER_THESPIA, SPECIAL);
             }
         if (go->GetEntry() == GO_ACCESS_PANEL_MEK)
             if (instance->GetData(TYPE_MEKGINEER_STEAMRIGGER) == DONE)
             {
                 go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                 instance->SetData(TYPE_MEKGINEER_STEAMRIGGER, SPECIAL);
             }
         return true;
     }
References DONE, GAMEOBJECT_FLAGS, ZoneScript::GetData(), Object::GetEntry(), WorldObject::GetInstanceScript(), GO_ACCESS_PANEL_HYDRO, GO_ACCESS_PANEL_MEK, GO_FLAG_NOT_SELECTABLE, ZoneScript::SetData(), Object::SetFlag(), SPECIAL, TYPE_HYDROMANCER_THESPIA, and TYPE_MEKGINEER_STEAMRIGGER.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp