Azerotcore-wotlk: achievement_snakes_whyd_it_have_to_be_snakes Class Reference
achievement_snakes_whyd_it_have_to_be_snakes Class Reference
Public Member Functions
achievement_snakes_whyd_it_have_to_be_snakes ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 232 of file boss_slad_ran.cpp.
Constructor & Destructor Documentation
achievement_snakes_whyd_it_have_to_be_snakes()
achievement_snakes_whyd_it_have_to_be_snakes::achievement_snakes_whyd_it_have_to_be_snakes () inline
Definition at line 235 of file boss_slad_ran.cpp.
                                                    : AchievementCriteriaScript("achievement_snakes_whyd_it_have_to_be_snakes")
     {
     }
Member Function Documentation
OnCheck()
bool achievement_snakes_whyd_it_have_to_be_snakes::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 239 of file boss_slad_ran.cpp.
     {
         if (!target)
             return false;
         return target->GetAI()->GetData(target->GetEntry());
     }
References Unit::GetAI(), UnitAI::GetData(), and Object::GetEntry().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Gundrak/boss_slad_ran.cpp