Azerotcore-wotlk: SQLQueryHolderCallback Class Reference
SQLQueryHolderCallback Class Reference
#include <QueryHolder.h>
Public Member Functions
SQLQueryHolderCallback (std::shared_ptr< SQLQueryHolderBase > &&holder, QueryResultHolderFuture &&future)
SQLQueryHolderCallback (SQLQueryHolderCallback &&)=default
SQLQueryHolderCallback & operator= (SQLQueryHolderCallback &&)=default
void AfterComplete (std::function< void(SQLQueryHolderBase const &)> callback) &
bool InvokeIfReady ()
Public Attributes
std::shared_ptr< SQLQueryHolderBase > m_holder
QueryResultHolderFuture m_future
std::function< void(SQLQueryHolderBase const &)> m_callback
Detailed Description
Definition at line 66 of file QueryHolder.h.
Constructor & Destructor Documentation
SQLQueryHolderCallback() [1/2]
SQLQueryHolderCallback::SQLQueryHolderCallback (std::shared_ptr< SQLQueryHolderBase > && holder, QueryResultHolderFuture && future) inline
Definition at line 69 of file QueryHolder.h.
         : m_holder(std::move(holder)), m_future(std::move(future)) { }
SQLQueryHolderCallback() [2/2]
SQLQueryHolderCallback::SQLQueryHolderCallback (SQLQueryHolderCallback &&) default
Member Function Documentation
AfterComplete()
void SQLQueryHolderCallback::AfterComplete (std::function< void(SQLQueryHolderBase const &)> callback) & inline
Definition at line 76 of file QueryHolder.h.
     {
         m_callback = std::move(callback);
     }
Referenced by WorldSession::HandleLoadPetFromDBFirstCallback(), and WorldSession::HandlePlayerLoginOpcode().
InvokeIfReady()
bool SQLQueryHolderCallback::InvokeIfReady ()
Definition at line 88 of file QueryHolder.cpp.
 {
     if (m_future.valid() && m_future.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
     {
         m_callback(*m_holder);
         return true;
     }
     return false;
 }
References m_callback, m_future, m_holder, and G3D::units::seconds().
operator=()
SQLQueryHolderCallback& SQLQueryHolderCallback::operator= (SQLQueryHolderCallback &&) default
Member Data Documentation
m_callback
std::function<void(SQLQueryHolderBase const&)> SQLQueryHolderCallback::m_callback
Definition at line 85 of file QueryHolder.h.
Referenced by InvokeIfReady().
m_future
QueryResultHolderFuture SQLQueryHolderCallback::m_future
Definition at line 84 of file QueryHolder.h.
Referenced by InvokeIfReady().
m_holder
std::shared_ptr<SQLQueryHolderBase> SQLQueryHolderCallback::m_holder
Definition at line 83 of file QueryHolder.h.
Referenced by InvokeIfReady().
The documentation for this class was generated from the following files:
src/server/database/Database/QueryHolder.h
src/server/database/Database/QueryHolder.cpp