Azerotcore-wotlk: FollowerReference Class Reference
FollowerReference Class Reference
#include <FollowerReference.h>
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Additional Inherited Members
Public Member Functions inherited from Reference< Unit, TargetedMovementGeneratorBase >
Reference ()
virtual ~Reference ()=default
void link (Unit *toObj, TargetedMovementGeneratorBase *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Unit, TargetedMovementGeneratorBase > * next ()
Reference< Unit, TargetedMovementGeneratorBase > const * next () const
Reference< Unit, TargetedMovementGeneratorBase > * prev ()
Reference< Unit, TargetedMovementGeneratorBase > const * prev () const
Reference< Unit, TargetedMovementGeneratorBase > * nocheck_next ()
Reference< Unit, TargetedMovementGeneratorBase > const * nocheck_next () const
Reference< Unit, TargetedMovementGeneratorBase > * nocheck_prev ()
Reference< Unit, TargetedMovementGeneratorBase > const * nocheck_prev () const
Unit * operator-> () const
Unit * getTarget () const
TargetedMovementGeneratorBase * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Detailed Description
Definition at line 26 of file FollowerReference.h.
Member Function Documentation
sourceObjectDestroyLink()
void FollowerReference::sourceObjectDestroyLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
Definition at line 32 of file FollowerReference.cpp.
 {
     GetSource()->stopFollowing();
 }
References Reference< Unit, TargetedMovementGeneratorBase >::GetSource(), and TargetedMovementGeneratorBase::stopFollowing().
targetObjectBuildLink()
void FollowerReference::targetObjectBuildLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
Definition at line 22 of file FollowerReference.cpp.
 {
     getTarget()->addFollower(this);
 }
References Unit::addFollower(), and Reference< Unit, TargetedMovementGeneratorBase >::getTarget().
targetObjectDestroyLink()
void FollowerReference::targetObjectDestroyLink () override protected virtual
Implements Reference< Unit, TargetedMovementGeneratorBase >.
Definition at line 27 of file FollowerReference.cpp.
 {
     getTarget()->removeFollower(this);
 }
References Reference< Unit, TargetedMovementGeneratorBase >::getTarget(), and Unit::removeFollower().
The documentation for this class was generated from the following files:
src/server/game/Movement/FollowerReference.h
src/server/game/Movement/FollowerReference.cpp