Azerotcore-wotlk: DBCFileLoader::Record Class Reference
DBCFileLoader::Record Class Reference
#include <DBCFileLoader.h>
Public Member Functions
float getFloat (size_t field) const
uint32 getUInt (size_t field) const
uint8 getUInt8 (size_t field) const
const char * getString (size_t field) const
Private Member Functions
Record (DBCFileLoader &file_, unsigned char *offset_)
Private Attributes
unsigned char * offset
DBCFileLoader & file
Friends
class DBCFileLoader
Detailed Description
Definition at line 46 of file DBCFileLoader.h.
Constructor & Destructor Documentation
Record()
DBCFileLoader::Record::Record (DBCFileLoader & file_, unsigned char * offset_) inline private
Definition at line 80 of file DBCFileLoader.h.
 : offset(offset_), file(file_) { }
Member Function Documentation
getFloat()
float DBCFileLoader::Record::getFloat (size_t field) const inline
Definition at line 49 of file DBCFileLoader.h.
         {
             ASSERT(field < file.fieldCount);
             float val = *reinterpret_cast<float*>(offset + file.GetOffset(field));
             EndianConvert(val);
             return val;
         }
References ASSERT, EndianConvert(), DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData().
getString()
const char* DBCFileLoader::Record::getString (size_t field) const inline
Definition at line 71 of file DBCFileLoader.h.
         {
             ASSERT(field < file.fieldCount);
             size_t stringOffset = getUInt(field);
             ASSERT(stringOffset < file.stringSize);
             return reinterpret_cast<char*>(file.stringTable + stringOffset);
         }
References ASSERT, DBCFileLoader::fieldCount, file, getUInt(), DBCFileLoader::stringSize, and DBCFileLoader::stringTable.
Referenced by DBCFileLoader::AutoProduceStrings().
getUInt()
uint32 DBCFileLoader::Record::getUInt (size_t field) const inline
Definition at line 57 of file DBCFileLoader.h.
         {
             ASSERT(field < file.fieldCount);
             uint32 val = *reinterpret_cast<uint32*>(offset + file.GetOffset(field));
             EndianConvert(val);
             return val;
         }
References ASSERT, EndianConvert(), DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData(), and getString().
getUInt8()
uint8 DBCFileLoader::Record::getUInt8 (size_t field) const inline
Definition at line 65 of file DBCFileLoader.h.
         {
             ASSERT(field < file.fieldCount);
             return *reinterpret_cast<uint8*>(offset + file.GetOffset(field));
         }
References ASSERT, DBCFileLoader::fieldCount, file, DBCFileLoader::GetOffset(), and offset.
Referenced by DBCFileLoader::AutoProduceData().
Friends And Related Function Documentation
DBCFileLoader
friend class DBCFileLoader friend
Definition at line 84 of file DBCFileLoader.h.
Member Data Documentation
file
DBCFileLoader& DBCFileLoader::Record::file private
Definition at line 82 of file DBCFileLoader.h.
Referenced by getFloat(), getString(), getUInt(), and getUInt8().
offset
unsigned char* DBCFileLoader::Record::offset private
Definition at line 81 of file DBCFileLoader.h.
Referenced by getFloat(), getUInt(), and getUInt8().
The documentation for this class was generated from the following file:
src/common/DataStores/DBCFileLoader.h