Azerotcore-wotlk: Acore::ChatCommands::Variant< T1, Ts > Struct Template Reference
Acore::ChatCommands::Variant< T1, Ts > Struct Template Reference
#include <ChatCommandTags.h>
Public Types
using base = std::variant< T1, Ts... >
using first_type = Acore::Impl::ChatCommands::tag_base_t< T1 >
Public Member Functions
template<bool C = have_operators>
std::enable_if_t< C, first_type > operator* () const
template<bool C = have_operators>
operator std::enable_if_t< C, first_type > () const
template<bool C = have_operators>
operator std::enable_if_t< C &&!std::is_same_v< first_type, size_t > &&std::is_convertible_v< first_type, size_t >, size_t > () const
template<bool C = have_operators>
std::enable_if_t< C, bool > operator! () const
template<typename T >
Variant & operator= (T &&arg)
template<size_t index>
constexpr decltype(auto) get ()
template<size_t index>
constexpr decltype(auto) get () const
template<typename type >
constexpr decltype(auto) get ()
template<typename type >
constexpr decltype(auto) get () const
template<typename T >
constexpr decltype(auto) visit (T &&arg)
template<typename T >
constexpr decltype(auto) visit (T &&arg) const
template<typename T >
constexpr bool holds_alternative () const
Static Public Attributes
static constexpr bool have_operators = Acore::Impl::ChatCommands::are_all_assignable<first_type, Acore::Impl::ChatCommands::tag_base_t<Ts>...>::value
Friends
template<bool C = have_operators>
std::enable_if_t< C, std::ostream & > operator<< (std::ostream &os, Acore::ChatCommands::Variant< T1, Ts... > const &v)
Detailed Description
template<typename T1, typename... Ts>
struct Acore::ChatCommands::Variant< T1, Ts >
Definition at line 257 of file ChatCommandTags.h.
Member Typedef Documentation
base
template<typename T1 , typename... Ts> using Acore::ChatCommands::Variant< T1, Ts >::base = std::variant<T1, Ts...>
Definition at line 259 of file ChatCommandTags.h.
first_type
template<typename T1 , typename... Ts> using Acore::ChatCommands::Variant< T1, Ts >::first_type = Acore::Impl::ChatCommands::tag_base_t<T1>
Definition at line 261 of file ChatCommandTags.h.
Member Function Documentation
get() [1/4]
template<typename T1 , typename... Ts> template<size_t index> constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::get () inline constexpr
Definition at line 289 of file ChatCommandTags.h.
 { return std::get<index>(static_cast<base&>(*this)); }
Referenced by debug_commandscript::HandleDebugSetValueCommand(), and Acore::ChatCommands::PlayerIdentifier::TryConsume().
get() [2/4]
template<typename T1 , typename... Ts> template<typename type > constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::get () inline constexpr
Definition at line 293 of file ChatCommandTags.h.
 { return std::get<type>(static_cast<base&>(*this)); }
get() [3/4]
template<typename T1 , typename... Ts> template<size_t index> constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::get () const inline constexpr
Definition at line 291 of file ChatCommandTags.h.
 { return std::get<index>(static_cast<base const&>(*this)); }
get() [4/4]
template<typename T1 , typename... Ts> template<typename type > constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::get () const inline constexpr
Definition at line 295 of file ChatCommandTags.h.
 { return std::get<type>(static_cast<base const&>(*this)); }
holds_alternative()
template<typename T1 , typename... Ts> template<typename T > constexpr bool Acore::ChatCommands::Variant< T1, Ts >::holds_alternative () const inline constexpr
Definition at line 303 of file ChatCommandTags.h.
 { return std::holds_alternative<T>(static_cast<base const&>(*this)); }
Referenced by debug_commandscript::HandleDebugSetValueCommand(), Acore::ChatCommands::PlayerIdentifier::TryConsume(), and Acore::Impl::ChatCommands::ArgInfo< GameTele const * >::TryConsume().
operator std::enable_if_t< C &&!std::is_same_v< first_type, size_t > &&std::is_convertible_v< first_type, size_t >, size_t >()
template<typename T1 , typename... Ts> template<bool C = have_operators> Acore::ChatCommands::Variant< T1, Ts >::operator std::enable_if_t< C &&!std::is_same_v< first_type, size_t > &&std::is_convertible_v< first_type, size_t >, size_t > () const inline
Definition at line 277 of file ChatCommandTags.h.
         {
             return operator*();
         }
References Acore::ChatCommands::Variant< T1, Ts >::operator*().
operator std::enable_if_t< C, first_type >()
template<typename T1 , typename... Ts> template<bool C = have_operators> Acore::ChatCommands::Variant< T1, Ts >::operator std::enable_if_t< C, first_type > () const inline
Definition at line 271 of file ChatCommandTags.h.
         {
             return operator*();
         }
References Acore::ChatCommands::Variant< T1, Ts >::operator*().
operator!()
template<typename T1 , typename... Ts> template<bool C = have_operators> std::enable_if_t<C, bool> Acore::ChatCommands::Variant< T1, Ts >::operator! () const inline
Definition at line 283 of file ChatCommandTags.h.
 { return !**this; }
operator*()
template<typename T1 , typename... Ts> template<bool C = have_operators> std::enable_if_t<C, first_type> Acore::ChatCommands::Variant< T1, Ts >::operator* () const inline
Definition at line 265 of file ChatCommandTags.h.
         {
             return visit(Acore::Impl::CastToVisitor<first_type>());
         }
References Acore::ChatCommands::Variant< T1, Ts >::visit().
Referenced by Acore::ChatCommands::Variant< T1, Ts >::operator std::enable_if_t< C &&!std::is_same_v< first_type, size_t > &&std::is_convertible_v< first_type, size_t >, size_t >(), and Acore::ChatCommands::Variant< T1, Ts >::operator std::enable_if_t< C, first_type >().
operator=()
template<typename T1 , typename... Ts> template<typename T > Variant& Acore::ChatCommands::Variant< T1, Ts >::operator= (T && arg) inline
Definition at line 286 of file ChatCommandTags.h.
 { base::operator=(std::forward<T>(arg)); return *this; }
visit() [1/2]
template<typename T1 , typename... Ts> template<typename T > constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::visit (T && arg) inline constexpr
Definition at line 298 of file ChatCommandTags.h.
 { return std::visit(std::forward<T>(arg), static_cast<base&>(*this)); }
Referenced by Acore::ChatCommands::Variant< T1, Ts >::operator*(), Acore::Impl::ChatCommands::ArgInfo< AchievementEntry const * >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< GameTele const * >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< ItemTemplate const * >::TryConsume(), and Acore::Impl::ChatCommands::ArgInfo< SpellInfo const * >::TryConsume().
visit() [2/2]
template<typename T1 , typename... Ts> template<typename T > constexpr decltype(auto) Acore::ChatCommands::Variant< T1, Ts >::visit (T && arg) const inline constexpr
Definition at line 300 of file ChatCommandTags.h.
 { return std::visit(std::forward<T>(arg), static_cast<base const&>(*this)); }
Friends And Related Function Documentation
operator<<
template<typename T1 , typename... Ts> template<bool C = have_operators> std::enable_if_t<C, std::ostream&> operator<< (std::ostream & os, Acore::ChatCommands::Variant< T1, Ts... > const & v) friend
Definition at line 306 of file ChatCommandTags.h.
         {
             return (os << *v);
         }
Member Data Documentation
have_operators
template<typename T1 , typename... Ts> constexpr bool Acore::ChatCommands::Variant< T1, Ts >::have_operators = Acore::Impl::ChatCommands::are_all_assignable<first_type, Acore::Impl::ChatCommands::tag_base_t<Ts>...>::value static constexpr
Definition at line 262 of file ChatCommandTags.h.
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandTags.h