Azerotcore-wotlk: instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript Struct Reference
instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_magtheridons_lair_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
bool SetBossState (uint32 id, EncounterState state) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (char const *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _magtheridonGUID
GuidSet _wardersSet
GuidSet _cubesSet
GuidSet _columnSet
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 39 of file instance_magtheridons_lair.cpp.
Constructor & Destructor Documentation
instance_magtheridons_lair_InstanceMapScript()
instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::instance_magtheridons_lair_InstanceMapScript (Map * map) inline
Definition at line 41 of file instance_magtheridons_lair.cpp.
                                                                : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTER);
             LoadDoorData(doorData);
             LoadMinionData(minionData);
         }
References doorData, InstanceScript::LoadDoorData(), InstanceScript::LoadMinionData(), MAX_ENCOUNTER, minionData, and InstanceScript::SetBossNumber().
Member Function Documentation
GetSaveData()
std::string instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 177 of file instance_magtheridons_lair.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "M L " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 48 of file instance_magtheridons_lair.cpp.
         {
             _wardersSet.clear();
             _cubesSet.clear();
             _columnSet.clear();
         }
References _columnSet, _cubesSet, and _wardersSet.
Load()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::Load (char const * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 188 of file instance_magtheridons_lair.cpp.
         {
             if (!str)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(str);
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'M' && dataHead2 == 'L')
             {
                 for (uint32 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 55 of file instance_magtheridons_lair.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_MAGTHERIDON:
                     _magtheridonGUID = creature->GetGUID();
                     break;
                 case NPC_HELLFIRE_CHANNELER:
                     AddMinion(creature, true);
                     break;
                 case NPC_HELLFIRE_WARDER:
                     _wardersSet.insert(creature->GetGUID());
                     break;
             }
         }
References _magtheridonGUID, _wardersSet, InstanceScript::AddMinion(), Object::GetEntry(), Object::GetGUID(), NPC_HELLFIRE_CHANNELER, NPC_HELLFIRE_WARDER, and NPC_MAGTHERIDON.
OnCreatureRemove()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 71 of file instance_magtheridons_lair.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_HELLFIRE_CHANNELER:
                     AddMinion(creature, false);
                     break;
             }
         }
References InstanceScript::AddMinion(), Object::GetEntry(), and NPC_HELLFIRE_CHANNELER.
OnGameObjectCreate()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 81 of file instance_magtheridons_lair.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_MAGTHERIDON_DOORS:
                     AddDoor(go, true);
                     break;
                 case GO_MANTICRON_CUBE:
                     _cubesSet.insert(go->GetGUID());
                     break;
                 case GO_MAGTHERIDON_HALL:
                 case GO_MAGTHERIDON_COLUMN0:
                 case GO_MAGTHERIDON_COLUMN1:
                 case GO_MAGTHERIDON_COLUMN2:
                 case GO_MAGTHERIDON_COLUMN3:
                 case GO_MAGTHERIDON_COLUMN4:
                 case GO_MAGTHERIDON_COLUMN5:
                     _columnSet.insert(go->GetGUID());
                     break;
             }
         }
References _columnSet, _cubesSet, InstanceScript::AddDoor(), Object::GetEntry(), Object::GetGUID(), GO_MAGTHERIDON_COLUMN0, GO_MAGTHERIDON_COLUMN1, GO_MAGTHERIDON_COLUMN2, GO_MAGTHERIDON_COLUMN3, GO_MAGTHERIDON_COLUMN4, GO_MAGTHERIDON_COLUMN5, GO_MAGTHERIDON_DOORS, GO_MAGTHERIDON_HALL, and GO_MANTICRON_CUBE.
OnGameObjectRemove()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 103 of file instance_magtheridons_lair.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_MAGTHERIDON_DOORS:
                     AddDoor(go, false);
                     break;
                 case GO_MANTICRON_CUBE:
                     _cubesSet.erase(go->GetGUID());
                     break;
                 case GO_MAGTHERIDON_HALL:
                 case GO_MAGTHERIDON_COLUMN0:
                 case GO_MAGTHERIDON_COLUMN1:
                 case GO_MAGTHERIDON_COLUMN2:
                 case GO_MAGTHERIDON_COLUMN3:
                 case GO_MAGTHERIDON_COLUMN4:
                 case GO_MAGTHERIDON_COLUMN5:
                     _columnSet.erase(go->GetGUID());
                     break;
             }
         }
References _columnSet, _cubesSet, InstanceScript::AddDoor(), Object::GetEntry(), Object::GetGUID(), GO_MAGTHERIDON_COLUMN0, GO_MAGTHERIDON_COLUMN1, GO_MAGTHERIDON_COLUMN2, GO_MAGTHERIDON_COLUMN3, GO_MAGTHERIDON_COLUMN4, GO_MAGTHERIDON_COLUMN5, GO_MAGTHERIDON_DOORS, GO_MAGTHERIDON_HALL, and GO_MANTICRON_CUBE.
SetBossState()
bool instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 125 of file instance_magtheridons_lair.cpp.
         {
             if (!InstanceScript::SetBossState(id, state))
                 return false;
             if (id == TYPE_MAGTHERIDON)
             {
                 if (state == IN_PROGRESS)
                 {
                     for (ObjectGuid const& guid : _wardersSet)
                         if (Creature* warder = instance->GetCreature(guid))
                             if (warder->IsAlive())
{
                                 warder->InterruptNonMeleeSpells(true);
                                 warder->SetInCombatWithZone();
                             }
                 }
                 else
                 {
                     for (ObjectGuid const& guid : _cubesSet)
                         if (GameObject* cube = instance->GetGameObject(guid))
                             cube->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     if (state == NOT_STARTED)
                         SetData(DATA_COLLAPSE, GO_READY);
                 }
             }
             return true;
         }
References _cubesSet, _wardersSet, DATA_COLLAPSE, GAMEOBJECT_FLAGS, Map::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, GO_READY, IN_PROGRESS, InstanceScript::instance, NOT_STARTED, InstanceScript::SetBossState(), SetData(), and TYPE_MAGTHERIDON.
Referenced by Load().
SetData()
void instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 155 of file instance_magtheridons_lair.cpp.
         {
             switch (type)
             {
                 case DATA_CHANNELER_COMBAT:
                     if (GetBossState(TYPE_MAGTHERIDON) != IN_PROGRESS)
                         if (Creature* magtheridon = instance->GetCreature(_magtheridonGUID))
                             magtheridon->SetInCombatWithZone();
                     break;
                 case DATA_ACTIVATE_CUBES:
                     for (ObjectGuid const& guid : _cubesSet)
                         if (GameObject* cube = instance->GetGameObject(guid))
                             cube->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case DATA_COLLAPSE:
                     for (ObjectGuid const& guid : _columnSet)
                         if (GameObject* column = instance->GetGameObject(guid))
                             column->SetGoState(GOState(data));
                     break;
             }
         }
References _columnSet, _cubesSet, _magtheridonGUID, DATA_ACTIVATE_CUBES, DATA_CHANNELER_COMBAT, DATA_COLLAPSE, GAMEOBJECT_FLAGS, InstanceScript::GetBossState(), Map::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, IN_PROGRESS, InstanceScript::instance, and TYPE_MAGTHERIDON.
Referenced by SetBossState().
Member Data Documentation
_columnSet
GuidSet instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::_columnSet private
Definition at line 224 of file instance_magtheridons_lair.cpp.
Referenced by Initialize(), OnGameObjectCreate(), OnGameObjectRemove(), and SetData().
_cubesSet
GuidSet instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::_cubesSet private
Definition at line 223 of file instance_magtheridons_lair.cpp.
Referenced by Initialize(), OnGameObjectCreate(), OnGameObjectRemove(), SetBossState(), and SetData().
_magtheridonGUID
ObjectGuid instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::_magtheridonGUID private
Definition at line 221 of file instance_magtheridons_lair.cpp.
Referenced by OnCreatureCreate(), and SetData().
_wardersSet
GuidSet instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript::_wardersSet private
Definition at line 222 of file instance_magtheridons_lair.cpp.
Referenced by Initialize(), OnCreatureCreate(), and SetBossState().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/instance_magtheridons_lair.cpp