Azerotcore-wotlk: Acore::CheckedBufferOutputIterator< T > Class Template Reference
Acore::CheckedBufferOutputIterator< T > Class Template Reference
#include <Containers.h>
Public Types
using iterator_category = std::output_iterator_tag
using value_type = void
using pointer = T *
using reference = T &
using difference_type = std::ptrdiff_t
Public Member Functions
CheckedBufferOutputIterator (T *buf, size_t n)
T & operator* () const
CheckedBufferOutputIterator & operator++ ()
CheckedBufferOutputIterator operator++ (int)
size_t remaining () const
Private Member Functions
void check () const
Private Attributes
T * _buf
T * _end
Detailed Description
template<class T>
class Acore::CheckedBufferOutputIterator< T >
Definition at line 45 of file Containers.h.
Member Typedef Documentation
difference_type
template<class T > using Acore::CheckedBufferOutputIterator< T >::difference_type = std::ptrdiff_t
Definition at line 52 of file Containers.h.
iterator_category
template<class T > using Acore::CheckedBufferOutputIterator< T >::iterator_category = std::output_iterator_tag
Definition at line 48 of file Containers.h.
pointer
template<class T > using Acore::CheckedBufferOutputIterator< T >::pointer = T*
Definition at line 50 of file Containers.h.
reference
template<class T > using Acore::CheckedBufferOutputIterator< T >::reference = T&
Definition at line 51 of file Containers.h.
value_type
template<class T > using Acore::CheckedBufferOutputIterator< T >::value_type = void
Definition at line 49 of file Containers.h.
Constructor & Destructor Documentation
CheckedBufferOutputIterator()
template<class T > Acore::CheckedBufferOutputIterator< T >::CheckedBufferOutputIterator (T * buf, size_t n) inline
Definition at line 54 of file Containers.h.
 : _buf(buf), _end(buf + n) {}
Member Function Documentation
check()
template<class T > void Acore::CheckedBufferOutputIterator< T >::check () const inline private
Definition at line 66 of file Containers.h.
         {
             if (!(_buf < _end))
             {
                 throw std::out_of_range("index");
             }
         }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::_end.
Referenced by Acore::CheckedBufferOutputIterator< T >::operator*(), and Acore::CheckedBufferOutputIterator< T >::operator++().
operator*()
template<class T > T& Acore::CheckedBufferOutputIterator< T >::operator* () const inline
Definition at line 56 of file Containers.h.
 { check(); return *_buf; }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::check().
operator++() [1/2]
template<class T > CheckedBufferOutputIterator& Acore::CheckedBufferOutputIterator< T >::operator++ () inline
Definition at line 57 of file Containers.h.
 { check(); ++_buf; return *this; }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::check().
operator++() [2/2]
template<class T > CheckedBufferOutputIterator Acore::CheckedBufferOutputIterator< T >::operator++ (int) inline
Definition at line 58 of file Containers.h.
 { CheckedBufferOutputIterator v = *this; operator++(); return v; }
References Acore::CheckedBufferOutputIterator< T >::operator++().
Referenced by Acore::CheckedBufferOutputIterator< T >::operator++().
remaining()
template<class T > size_t Acore::CheckedBufferOutputIterator< T >::remaining () const inline
Definition at line 60 of file Containers.h.
 { return (_end - _buf); }
References Acore::CheckedBufferOutputIterator< T >::_buf, and Acore::CheckedBufferOutputIterator< T >::_end.
Referenced by Utf8toWStr().
Member Data Documentation
_buf
template<class T > T* Acore::CheckedBufferOutputIterator< T >::_buf private
Definition at line 63 of file Containers.h.
Referenced by Acore::CheckedBufferOutputIterator< T >::check(), Acore::CheckedBufferOutputIterator< T >::operator*(), Acore::CheckedBufferOutputIterator< T >::operator++(), and Acore::CheckedBufferOutputIterator< T >::remaining().
_end
template<class T > T* Acore::CheckedBufferOutputIterator< T >::_end private
Definition at line 64 of file Containers.h.
Referenced by Acore::CheckedBufferOutputIterator< T >::check(), and Acore::CheckedBufferOutputIterator< T >::remaining().
The documentation for this class was generated from the following file:
src/common/Utilities/Containers.h