Azerotcore-wotlk: npc_death_knight_initiate::npc_death_knight_initiateAI Struct Reference
npc_death_knight_initiate::npc_death_knight_initiateAI Struct Reference
Public Member Functions
npc_death_knight_initiateAI (Creature *creature)
uint32 GetData (uint32 data) const override
void Reset () override
void SpellHit (Unit *caster, const SpellInfo *pSpell) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _duelInProgress
ObjectGuid _duelGUID
EventMap events
std::set< uint32 > playerGUIDs
uint32 timer = 0
Additional Inherited Members
Static Public Member Functions inherited from CombatAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 233 of file chapter1.cpp.
Constructor & Destructor Documentation
npc_death_knight_initiateAI()
npc_death_knight_initiate::npc_death_knight_initiateAI::npc_death_knight_initiateAI (Creature * creature) inline
Definition at line 235 of file chapter1.cpp.
 : CombatAI(creature) { }
Member Function Documentation
DamageTaken()
void npc_death_knight_initiate::npc_death_knight_initiateAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 281 of file chapter1.cpp.
         {
             if (attacker && _duelInProgress && attacker->IsControlledByPlayer())
             {
                 if (attacker->GetCharmerOrOwnerOrOwnGUID() != _duelGUID)
                     damage = 0;
                 else if (damage >= me->GetHealth())
                 {
                     damage = 0;
                     events.ScheduleEvent(EVENT_DUEL_LOST, 2000);
                     events.ScheduleEvent(EVENT_DUEL_LOST + 1, 6000);
                     _duelGUID.Clear();
                     _duelInProgress = 0;
                     attacker->RemoveGameObject(SPELL_DUEL_FLAG, true);
                     attacker->AttackStop();
                     me->CombatStop(false);
                     me->RemoveAllAuras();
                     me->CastSpell(attacker, SPELL_DUEL_VICTORY, true);
                     me->RestoreFaction();
                 }
             }
         }
References _duelGUID, _duelInProgress, Unit::AttackStop(), Unit::CastSpell(), ObjectGuid::Clear(), Unit::CombatStop(), EVENT_DUEL_LOST, Unit::GetCharmerOrOwnerOrOwnGUID(), Unit::GetHealth(), Unit::IsControlledByPlayer(), CreatureAI::me, Unit::RemoveAllAuras(), Unit::RemoveGameObject(), Unit::RestoreFaction(), SPELL_DUEL_FLAG, and SPELL_DUEL_VICTORY.
GetData()
uint32 npc_death_knight_initiate::npc_death_knight_initiateAI::GetData (uint32 data) const inline override virtual
Reimplemented from UnitAI.
Definition at line 243 of file chapter1.cpp.
         {
             if (data == DATA_IN_PROGRESS)
                 return _duelInProgress;
             return playerGUIDs.find(data) != playerGUIDs.end();
         }
References _duelInProgress, DATA_IN_PROGRESS, and playerGUIDs.
Reset()
void npc_death_knight_initiate::npc_death_knight_initiateAI::Reset () inline override virtual
Reimplemented from CombatAI.
Definition at line 251 of file chapter1.cpp.
         {
             _duelInProgress = false;
             _duelGUID.Clear();
             me->RestoreFaction();
             CombatAI::Reset();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING);
         }
References _duelGUID, _duelInProgress, ObjectGuid::Clear(), CreatureAI::me, CombatAI::Reset(), Unit::RestoreFaction(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_SWIMMING.
SpellHit()
void npc_death_knight_initiate::npc_death_knight_initiateAI::SpellHit (Unit * caster, const SpellInfo * pSpell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 261 of file chapter1.cpp.
         {
             if (!_duelInProgress && pSpell->Id == SPELL_DUEL)
             {
                 playerGUIDs.insert(caster->GetGUID().GetCounter());
                 _duelGUID = caster->GetGUID();
                 _duelInProgress = true;
                 timer = 600000; // clear playerGUIDs after 10 minutes if no one initiates a duel
                 me->GetMotionMaster()->MoveFollow(caster, 2.0f, 0.0f);
                 events.ScheduleEvent(EVENT_SPEAK, 3000);
                 events.ScheduleEvent(EVENT_SPEAK + 1, 7000);
                 events.ScheduleEvent(EVENT_SPEAK + 2, 8000);
                 events.ScheduleEvent(EVENT_SPEAK + 3, 9000);
                 events.ScheduleEvent(EVENT_SPEAK + 4, 10000);
                 events.ScheduleEvent(EVENT_SPEAK + 5, 11000);
             }
         }
References _duelGUID, _duelInProgress, EVENT_SPEAK, ObjectGuid::GetCounter(), Object::GetGUID(), Unit::GetMotionMaster(), SpellInfo::Id, CreatureAI::me, MotionMaster::MoveFollow(), playerGUIDs, SPELL_DUEL, and timer.
UpdateAI()
void npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from CombatAI.
Definition at line 305 of file chapter1.cpp.
         {
             if (timer != 0)
             {
                 if (timer <= diff)
                 {
                     timer = 0;
                     playerGUIDs.clear();
                 }
                 else
                 {
                     timer -= diff;
                 }
             }
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPEAK:
                     Talk(SAY_DUEL, ObjectAccessor::GetPlayer(*me, _duelGUID));
                     break;
                 case EVENT_SPEAK+1:
                     Talk(SAY_DUEL + 1, ObjectAccessor::GetPlayer(*me, _duelGUID));
                     break;
                 case EVENT_SPEAK+2:
                     Talk(SAY_DUEL + 2, ObjectAccessor::GetPlayer(*me, _duelGUID));
                     break;
                 case EVENT_SPEAK+3:
                     Talk(SAY_DUEL + 3, ObjectAccessor::GetPlayer(*me, _duelGUID));
                     break;
                 case EVENT_SPEAK+4:
                     Talk(SAY_DUEL + 4, ObjectAccessor::GetPlayer(*me, _duelGUID));
                     break;
                 case EVENT_SPEAK+5:
                     me->SetFaction(FACTION_UNDEAD_SCOURGE_2);
                     if (Player* player = ObjectAccessor::GetPlayer(*me, _duelGUID))
                         AttackStart(player);
                     return;
                 case EVENT_DUEL_LOST:
                     me->CastSpell(me, 7267, true);
                     break;
                 case EVENT_DUEL_LOST+1:
                     EnterEvadeMode();
                     return;
             }
             if (!events.Empty() || !UpdateVictim())
                 return;
             if (_duelInProgress)
             {
                 if (me->GetVictim()->GetGUID() == _duelGUID && me->GetVictim()->HealthBelowPct(10))
                 {
                     me->GetVictim()->CastSpell(me->GetVictim(), 7267, true); // beg
                     me->GetVictim()->RemoveGameObject(SPELL_DUEL_FLAG, true);
                     EnterEvadeMode();
                     return;
                 }
             }
             CombatAI::UpdateAI(diff);
         }
References _duelGUID, _duelInProgress, UnitAI::AttackStart(), Unit::CastSpell(), CreatureAI::EnterEvadeMode(), EVENT_DUEL_LOST, EVENT_SPEAK, FACTION_UNDEAD_SCOURGE_2, Object::GetGUID(), ObjectAccessor::GetPlayer(), Unit::GetVictim(), Unit::HealthBelowPct(), CreatureAI::me, playerGUIDs, Unit::RemoveGameObject(), SAY_DUEL, Unit::SetFaction(), SPELL_DUEL_FLAG, CreatureAI::Talk(), timer, CombatAI::UpdateAI(), and CreatureAI::UpdateVictim().
Member Data Documentation
_duelGUID
ObjectGuid npc_death_knight_initiate::npc_death_knight_initiateAI::_duelGUID
Definition at line 238 of file chapter1.cpp.
Referenced by DamageTaken(), Reset(), SpellHit(), and UpdateAI().
_duelInProgress
bool npc_death_knight_initiate::npc_death_knight_initiateAI::_duelInProgress
Definition at line 237 of file chapter1.cpp.
Referenced by DamageTaken(), GetData(), Reset(), SpellHit(), and UpdateAI().
events
EventMap npc_death_knight_initiate::npc_death_knight_initiateAI::events
Definition at line 239 of file chapter1.cpp.
playerGUIDs
std::set<uint32> npc_death_knight_initiate::npc_death_knight_initiateAI::playerGUIDs
Definition at line 240 of file chapter1.cpp.
Referenced by GetData(), SpellHit(), and UpdateAI().
timer
uint32 npc_death_knight_initiate::npc_death_knight_initiateAI::timer = 0
Definition at line 241 of file chapter1.cpp.
Referenced by SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp