Azerotcore-wotlk: npc_franklin Class Reference
npc_franklin Class Reference
Classes
struct npc_franklinAI
Public Member Functions
npc_franklin ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1037 of file npc_stave_of_ancients.cpp.
Constructor & Destructor Documentation
npc_franklin()
npc_franklin::npc_franklin () inline
Definition at line 1040 of file npc_stave_of_ancients.cpp.
 : CreatureScript("npc_franklin") { }
Member Function Documentation
GetAI()
CreatureAI* npc_franklin::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 1042 of file npc_stave_of_ancients.cpp.
     {
         return new npc_franklinAI(creature);
     }
OnGossipHello()
bool npc_franklin::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1189 of file npc_stave_of_ancients.cpp.
     {
         if (player->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS) == QUEST_STATUS_INCOMPLETE && !player->HasItemCount(FRANKLIN_HEAD, 1, true))
         {
             uint32 gossipMenuId = creature->GetCreatureTemplate()->GossipMenuId;
             AddGossipItemFor(player, gossipMenuId, GOSSIP_EVENT_START_OPTION_ID, GOSSIP_SENDER_MAIN, 0);
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), FRANKLIN_HEAD, Creature::GetCreatureTemplate(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_EVENT_START_OPTION_ID, GOSSIP_SENDER_MAIN, CreatureTemplate::GossipMenuId, Player::HasItemCount(), QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, and SendGossipMenuFor().
OnGossipSelect()
bool npc_franklin::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1178 of file npc_stave_of_ancients.cpp.
     {
         CloseGossipMenuFor(player);
         if (creature->AI() && CAST_AI(npc_franklin::npc_franklinAI, creature->AI()))
         {
             CAST_AI(npc_franklin::npc_franklinAI, creature->AI())->ScheduleEncounterStart(player->GetGUID());
         }
         return true;
     }
References Creature::AI(), CAST_AI, CloseGossipMenuFor(), and Object::GetGUID().
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_stave_of_ancients.cpp