Azerotcore-wotlk: ReflectEvent Class Reference
ReflectEvent Class Reference
#include <Spell.h>
Public Member Functions
ReflectEvent (Unit *caster, ObjectGuid targetGUID, const SpellInfo *spellInfo)
bool Execute (uint64 e_time, uint32 p_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Protected Attributes
Unit * _caster
ObjectGuid _targetGUID
const SpellInfo * _spellInfo
Detailed Description
Definition at line 825 of file Spell.h.
Constructor & Destructor Documentation
ReflectEvent()
ReflectEvent::ReflectEvent (Unit * caster, ObjectGuid targetGUID, const SpellInfo * spellInfo) inline
Definition at line 828 of file Spell.h.
 : _caster(caster), _targetGUID(targetGUID), _spellInfo(spellInfo) { }
Member Function Documentation
Execute()
bool ReflectEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
Definition at line 7669 of file Spell.cpp.
 {
     Unit* target = ObjectAccessor::GetUnit(*_caster, _targetGUID);
     if (target && _caster->IsInMap(target))
         _caster->ProcDamageAndSpell(target, PROC_FLAG_NONE, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG, PROC_EX_REFLECT, 1, BASE_ATTACK, _spellInfo);
     return true;
 }
References _caster, _spellInfo, _targetGUID, BASE_ATTACK, ObjectAccessor::GetUnit(), WorldObject::IsInMap(), PROC_EX_REFLECT, PROC_FLAG_NONE, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG, and Unit::ProcDamageAndSpell().
Member Data Documentation
_caster
Unit* ReflectEvent::_caster protected
Definition at line 832 of file Spell.h.
Referenced by Execute().
_spellInfo
const SpellInfo* ReflectEvent::_spellInfo protected
Definition at line 834 of file Spell.h.
Referenced by Execute().
_targetGUID
ObjectGuid ReflectEvent::_targetGUID protected
Definition at line 833 of file Spell.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/game/Spells/Spell.h
src/server/game/Spells/Spell.cpp