Azerotcore-wotlk: npc_creature_generator_akama::npc_creature_generator_akamaAI Struct Reference
npc_creature_generator_akama::npc_creature_generator_akamaAI Struct Reference
Public Member Functions
npc_creature_generator_akamaAI (Creature *creature)
void Reset () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap events
SummonList summons
InstanceScript * instance
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 449 of file boss_shade_of_akama.cpp.
Constructor & Destructor Documentation
npc_creature_generator_akamaAI()
npc_creature_generator_akama::npc_creature_generator_akamaAI::npc_creature_generator_akamaAI (Creature * creature) inline
Definition at line 451 of file boss_shade_of_akama.cpp.
                                                            : NullCreatureAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 496 of file boss_shade_of_akama.cpp.
         {
             if (param == ACTION_STOP_SPAWNING || param == ACTION_DESPAWN_ALL)
             {
                 events.Reset();
                 for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 {
                     if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                     {
                         if (summon->GetEntry() != NPC_ASHTONGUE_SORCERER)
                             continue;
                         summon->InterruptNonMeleeSpells(false);
                         summon->GetMotionMaster()->Clear();
                         summon->SetInCombatWithZone();
                     }
                 }
             }
             if (param == ACTION_DESPAWN_ALL)
                 summons.DespawnAll();
             else if (param == ACTION_NO_SORCERERS)
                 events.CancelEvent(EVENT_SUMMON_ASHTONGUE_SORCERER);
             else if (param == ACTION_START_ENCOUNTER)
             {
                 events.ScheduleEvent(EVENT_SUMMON_WAVE_B, 5000);
                 events.ScheduleEvent(EVENT_SUMMON_ASHTONGUE_DEFENDER, 20000);
                 events.ScheduleEvent(EVENT_SUMMON_ASHTONGUE_SORCERER, 35000);
             }
         }
References ACTION_DESPAWN_ALL, ACTION_NO_SORCERERS, ACTION_START_ENCOUNTER, ACTION_STOP_SPAWNING, SummonList::begin(), SummonList::DespawnAll(), SummonList::end(), EVENT_SUMMON_ASHTONGUE_DEFENDER, EVENT_SUMMON_ASHTONGUE_SORCERER, EVENT_SUMMON_WAVE_B, ObjectAccessor::GetCreature(), CreatureAI::me, NPC_ASHTONGUE_SORCERER, and summons.
JustSummoned()
void npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 462 of file boss_shade_of_akama.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_ASHTONGUE_SORCERER)
             {
                 std::list<Creature*> channelerList;
                 me->GetCreaturesWithEntryInRange(channelerList, 120.0f, NPC_ASHTONGUE_CHANNELER);
                 for (std::list<Creature*>::const_iterator itr = channelerList.begin(); itr != channelerList.end(); ++itr)
                 {
                     if ((*itr)->IsAlive() || (*itr)->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                         continue;
                     summon->SetInCombatWithZone();
                     summon->SetReactState(REACT_PASSIVE);
                     summon->GetMotionMaster()->MovePoint(POINT_START, **itr);
                     (*itr)->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     return;
                 }
             }
             summon->SetInCombatWithZone();
             if (Unit* akama = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_AKAMA_SHADE)))
             {
                 summon->AddThreat(akama, 500.0f);
                 summon->AI()->AttackStart(akama);
             }
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), ObjectAccessor::GetCreature(), WorldObject::GetCreaturesWithEntryInRange(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), instance, CreatureAI::me, MotionMaster::MovePoint(), NPC_AKAMA_SHADE, NPC_ASHTONGUE_CHANNELER, NPC_ASHTONGUE_SORCERER, POINT_START, REACT_PASSIVE, Creature::SetInCombatWithZone(), Creature::SetReactState(), SummonList::Summon(), summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void npc_creature_generator_akama::npc_creature_generator_akamaAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 456 of file boss_shade_of_akama.cpp.
         {
             events.Reset();
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), and summons.
SummonedCreatureDies()
void npc_creature_generator_akama::npc_creature_generator_akamaAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 490 of file boss_shade_of_akama.cpp.
         {
             summon->DespawnOrUnsummon(10000);
             summons.Despawn(summon);
         }
References SummonList::Despawn(), Creature::DespawnOrUnsummon(), and summons.
UpdateAI()
void npc_creature_generator_akama::npc_creature_generator_akamaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 525 of file boss_shade_of_akama.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_SUMMON_WAVE_B:
                     me->CastSpell(me, SPELL_ASHTONGUE_WAVE_B, true);
                     events.ScheduleEvent(EVENT_SUMMON_WAVE_B, 45000);
                     break;
                 case EVENT_SUMMON_ASHTONGUE_SORCERER: // left
                     me->CastSpell(me, SPELL_SUMMON_ASHTONGUE_SORCERER, true);
                     events.ScheduleEvent(EVENT_SUMMON_ASHTONGUE_SORCERER, 45000);
                     break;
                 case EVENT_SUMMON_ASHTONGUE_DEFENDER: // right
                     me->CastSpell(me, SPELL_SUMMON_ASHTONGUE_DEFENDER, true);
                     events.ScheduleEvent(EVENT_SUMMON_ASHTONGUE_DEFENDER, 45000);
                     break;
                 default:
                     break;
             }
         }
References Unit::CastSpell(), EVENT_SUMMON_ASHTONGUE_DEFENDER, EVENT_SUMMON_ASHTONGUE_SORCERER, EVENT_SUMMON_WAVE_B, CreatureAI::me, SPELL_ASHTONGUE_WAVE_B, SPELL_SUMMON_ASHTONGUE_DEFENDER, and SPELL_SUMMON_ASHTONGUE_SORCERER.
Member Data Documentation
events
EventMap npc_creature_generator_akama::npc_creature_generator_akamaAI::events private
Definition at line 549 of file boss_shade_of_akama.cpp.
instance
InstanceScript* npc_creature_generator_akama::npc_creature_generator_akamaAI::instance private
Definition at line 551 of file boss_shade_of_akama.cpp.
Referenced by JustSummoned(), and npc_creature_generator_akamaAI().
summons
SummonList npc_creature_generator_akama::npc_creature_generator_akamaAI::summons private
Definition at line 550 of file boss_shade_of_akama.cpp.
Referenced by DoAction(), JustSummoned(), Reset(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp