Azerotcore-wotlk: WorldModelHeader Class Reference
WorldModelHeader Class Reference
#include <Utils.h>
Public Member Functions
WorldModelHeader ()
Static Public Member Functions
static WorldModelHeader Read (FILE *stream)
Public Attributes
uint32 CountMaterials
uint32 CountGroups
uint32 CountPortals
uint32 CountLights
uint32 CountModels
uint32 CountDoodads
uint32 CountSets
uint32 AmbientColorUnk
uint32 WmoId
Vector3 BoundingBox [2]
uint32 LiquidTypeRelated
Detailed Description
Definition at line 192 of file Utils.h.
Constructor & Destructor Documentation
WorldModelHeader()
WorldModelHeader::WorldModelHeader () inline
Definition at line 195 of file Utils.h.
 {}
Member Function Documentation
Read()
WorldModelHeader WorldModelHeader::Read (FILE * stream) static
Definition at line 360 of file Utils.cpp.
 {
     WorldModelHeader ret;
     int count = 0;
     count += fread(&ret.CountMaterials, sizeof(uint32), 1, stream);
     count += fread(&ret.CountGroups, sizeof(uint32), 1, stream);
     count += fread(&ret.CountPortals, sizeof(uint32), 1, stream);
     count += fread(&ret.CountLights, sizeof(uint32), 1, stream);
     count += fread(&ret.CountModels, sizeof(uint32), 1, stream);
     count += fread(&ret.CountDoodads, sizeof(uint32), 1, stream);
     count += fread(&ret.CountSets, sizeof(uint32), 1, stream);
     count += fread(&ret.AmbientColorUnk, sizeof(uint32), 1, stream);
     count += fread(&ret.WmoId, sizeof(uint32), 1, stream);
     ret.BoundingBox[0] = Vector3::Read(stream);
     ret.BoundingBox[1] = Vector3::Read(stream);
     count += fread(&ret.LiquidTypeRelated, sizeof(uint32), 1, stream);
     if (count != 10)
         printf("WorldModelHeader::Read: Failed to read some data expected 10, read %d\n", count);
     return ret;
 }
References count(), printf(), Vector3::Read(), and ret.
Referenced by WorldModelRoot::ReadHeader().
Member Data Documentation
AmbientColorUnk
uint32 WorldModelHeader::AmbientColorUnk
Definition at line 203 of file Utils.h.
BoundingBox
Vector3 WorldModelHeader::BoundingBox[2]
Definition at line 205 of file Utils.h.
CountDoodads
uint32 WorldModelHeader::CountDoodads
Definition at line 201 of file Utils.h.
CountGroups
uint32 WorldModelHeader::CountGroups
Definition at line 197 of file Utils.h.
Referenced by ExtractGameobjectModels(), and WorldModelRoot::ReadGroups().
CountLights
uint32 WorldModelHeader::CountLights
Definition at line 199 of file Utils.h.
CountMaterials
uint32 WorldModelHeader::CountMaterials
Definition at line 196 of file Utils.h.
CountModels
uint32 WorldModelHeader::CountModels
Definition at line 200 of file Utils.h.
CountPortals
uint32 WorldModelHeader::CountPortals
Definition at line 198 of file Utils.h.
CountSets
uint32 WorldModelHeader::CountSets
Definition at line 202 of file Utils.h.
Referenced by WorldModelRoot::ReadDoodadSets().
LiquidTypeRelated
uint32 WorldModelHeader::LiquidTypeRelated
Definition at line 206 of file Utils.h.
WmoId
uint32 WorldModelHeader::WmoId
Definition at line 204 of file Utils.h.
Referenced by ExtractGameobjectModels().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp