Azerotcore-wotlk: DatabaseWorker Class Reference
DatabaseWorker Class Reference
#include <DatabaseWorker.h>
Public Member Functions
DatabaseWorker (ProducerConsumerQueue< SQLOperation * > *newQueue, MySQLConnection *connection)
~DatabaseWorker ()
Private Member Functions
void WorkerThread ()
DatabaseWorker (DatabaseWorker const &right)=delete
DatabaseWorker & operator= (DatabaseWorker const &right)=delete
Private Attributes
ProducerConsumerQueue< SQLOperation * > * _queue
MySQLConnection * _connection
std::thread _workerThread
std::atomic< bool > _cancelationToken
Detailed Description
Definition at line 31 of file DatabaseWorker.h.
Constructor & Destructor Documentation
DatabaseWorker() [1/2]
DatabaseWorker::DatabaseWorker (ProducerConsumerQueue< SQLOperation * > * newQueue, MySQLConnection * connection)
Definition at line 22 of file DatabaseWorker.cpp.
 {
     _connection = connection;
     _queue = newQueue;
     _cancelationToken = false;
     _workerThread = std::thread(&DatabaseWorker::WorkerThread, this);
 }
References _cancelationToken, _connection, _queue, _workerThread, and WorkerThread().
~DatabaseWorker()
DatabaseWorker::~DatabaseWorker ()
Definition at line 30 of file DatabaseWorker.cpp.
 {
     _cancelationToken = true;
     _queue->Cancel();
     _workerThread.join();
 }
References _cancelationToken, _queue, _workerThread, and ProducerConsumerQueue< T >::Cancel().
DatabaseWorker() [2/2]
DatabaseWorker::DatabaseWorker (DatabaseWorker const & right) private delete
Member Function Documentation
operator=()
DatabaseWorker& DatabaseWorker::operator= (DatabaseWorker const & right) private delete
WorkerThread()
void DatabaseWorker::WorkerThread () private
Definition at line 39 of file DatabaseWorker.cpp.
 {
     if (!_queue)
         return;
     for (;;)
     {
         SQLOperation* operation = nullptr;
         _queue->WaitAndPop(operation);
         if (_cancelationToken || !operation)
             return;
         operation->SetConnection(_connection);
         operation->call();
         delete operation;
     }
 }
References _cancelationToken, _connection, _queue, SQLOperation::call(), SQLOperation::SetConnection(), and ProducerConsumerQueue< T >::WaitAndPop().
Referenced by DatabaseWorker().
Member Data Documentation
_cancelationToken
std::atomic<bool> DatabaseWorker::_cancelationToken private
Definition at line 44 of file DatabaseWorker.h.
Referenced by DatabaseWorker(), WorkerThread(), and ~DatabaseWorker().
_connection
MySQLConnection* DatabaseWorker::_connection private
Definition at line 39 of file DatabaseWorker.h.
Referenced by DatabaseWorker(), and WorkerThread().
_queue
ProducerConsumerQueue<SQLOperation*>* DatabaseWorker::_queue private
Definition at line 38 of file DatabaseWorker.h.
Referenced by DatabaseWorker(), WorkerThread(), and ~DatabaseWorker().
_workerThread
std::thread DatabaseWorker::_workerThread private
Definition at line 42 of file DatabaseWorker.h.
Referenced by DatabaseWorker(), and ~DatabaseWorker().
The documentation for this class was generated from the following files:
src/server/database/Database/DatabaseWorker.h
src/server/database/Database/DatabaseWorker.cpp