Azerotcore-wotlk: G3D::GLight Class Reference
G3D::GLight Class Reference
#include <GLight.h>
Public Member Functions
GLight ()
GLight (const Any &any)
operator Any () const
class Sphere effectSphere (float cutoff=30.0f/255) const
class CoordinateFrame frame () const
bool operator== (const GLight &other) const
bool operator!= (const GLight &other) const
Static Public Member Functions
static GLight directional (const Vector3 &toLight, const Color3 &color, bool specular=true, bool diffuse=true)
static GLight point (const Vector3 &pos, const Color3 &color, float constAtt=1, float linAtt=0, float quadAtt=0.5f, bool specular=true, bool diffuse=true)
static GLight spot (const Vector3 &pos, const Vector3 &pointDirection, float cutOffAngleDegrees, const Color3 &color, float constAtt=1, float linAtt=0, float quadAtt=0, bool specular=true, bool diffuse=true)
static GLight spotTarget (const Vector3 &pos, const Vector3 &target, float cutOffAngleDegrees, const Color3 &color, float constAtt=1, float linAtt=0, float quadAtt=0, bool specular=true, bool diffuse=true)
Public Attributes
Vector4 position
Vector3 rightDirection
Vector3 spotDirection
float spotCutoff
bool spotSquare
float attenuation [3]
Color3 color
bool enabled
bool specular
bool diffuse
Detailed Description
A light representation that closely follows the OpenGL light format.
Definition at line 24 of file GLight.h.
Constructor & Destructor Documentation
GLight() [1/2]
G3D::GLight::GLight ()
Definition at line 106 of file GLight.cpp.
                :
     position(0, 0, 0, 0),
     rightDirection(0,0,0),
     spotDirection(0, 0, -1),
     spotCutoff(180),
     spotSquare(false),
     color(Color3::white()),
     enabled(false),
     specular(true),
     diffuse(true) {
     attenuation[0]  = 1.0;
     attenuation[1]  = 0.0;
     attenuation[2]  = 0.0;
 }
References attenuation, and white.
Referenced by GLight().
GLight() [2/2]
G3D::GLight::GLight (const Any & any)
Accepted forms:
GLight::directional(vector3, color3, [bool, [bool]])
GLight::spot(vector3, vector3, #, color3, [#, [#, [#, [#, [bool, [bool]]]])
GLight::point(vector3, color3, [#, [#, [#, [#, [bool, [bool]]]])
GLight { [all fields] }
Definition at line 17 of file GLight.cpp.
{
     any.verifyName("GLight");
     if (any.type() == Any::TABLE) {
         *this = GLight();
         Vector3 spotTarget;
         bool hasSpotTarget = false;
         for (Any::AnyTable::Iterator it = any.table().begin(); it.hasMore(); ++it) {
             const std::string& key = toLower(it->key);
             if (key == "position") {
                 position = it->value;
             } else if (key == "rightdirection") {
                 rightDirection = it->value;
             } else if (key == "spotdirection") {
                 spotDirection = Vector3(it->value).directionOrZero();
             } else if (key == "spottarget") {
                 spotTarget = it->value;
                 hasSpotTarget = true;
             } else if (key == "spotcutoff") {
                 spotCutoff = it->value.number();
             } else if (key == "spotsquare") {
                 spotSquare = it->value.boolean();
             } else if (key == "attenuation") {
                 attenuation[0] = it->value[0].number();
                 attenuation[1] = it->value[1].number();
                 attenuation[2] = it->value[2].number();
             } else if (key == "color") {
                 color = it->value;
             } else if (key == "enabled") {
                 enabled = it->value.boolean();
             } else if (key == "specular") {
                 specular = it->value.boolean();
             } else if (key == "diffuse") {
                 diffuse = it->value.boolean();
             } else {
                 any.verify(false, "Illegal key: " + it->key);
             }
         }
         if (hasSpotTarget) {
             spotDirection = (spotTarget - position.xyz()).direction();
         }
     } else if (toLower(any.name()) == "glight::directional") {
         *this = directional(any[0], any[1],
             (any.size() > 2) ? any[2] : Any(true),
             (any.size() > 3) ? any[3] : Any(true));
     } else if (toLower(any.name()) == "glight::point") {
         *this = point(any[0], any[1],
             (any.size() > 2) ? any[2] : Any(1),
             (any.size() > 3) ? any[3] : Any(0),
             (any.size() > 4) ? any[4] : Any(0.5f),
             (any.size() > 5) ? any[5] : Any(true),
             (any.size() > 6) ? any[6] : Any(true));
     } else if (toLower(any.name()) == "glight::spot") {
         *this = spot(any[0], any[1], any[2], any[3],
             (any.size() > 4) ? any[4] : Any(1),
             (any.size() > 5) ? any[5] : Any(0),
             (any.size() > 6) ? any[6] : Any(0),
             (any.size() > 7) ? any[7] : Any(true),
             (any.size() > 8) ? any[8] : Any(true));
     } else {
         any.verify(false, "Unrecognized name");
     }
 }
References G3D::any(), attenuation, diffuse, directional(), G3D::Vector3::directionOrZero(), enabled, GLight(), point(), position, rightDirection, specular, spot(), spotCutoff, spotDirection, spotSquare, spotTarget(), G3D::Any::TABLE, G3D::toLower(), and G3D::Vector4::xyz().
Member Function Documentation
directional()
GLight G3D::GLight::directional (const Vector3 & toLight, const Color3 & color, bool specular = true, bool diffuse = true) static
Parameters
toLight will be normalized
Definition at line 123 of file GLight.cpp.
{
     GLight L;
     L.position = Vector4(toLight.direction(), 0);
     L.color    = color;
     L.specular = s;
     L.diffuse  = d;
     return L;
 }
References color, mpq::d, diffuse, G3D::Vector3::direction(), position, and specular.
Referenced by GLight().
effectSphere()
Sphere G3D::GLight::effectSphere (float cutoff = 30.0f / 255) const
Returns the sphere within which this light has some noticable effect. May be infinite.
Parameters
cutoff The value at which the light intensity is considered negligible.
Definition at line 183 of file GLight.cpp.
{
     if (position.w == 0) {
         // Directional light
         return Sphere(Vector3::zero(), finf());
     } else {
         // Avoid divide by zero
         cutoff = max(cutoff, 0.00001f);
         float maxIntensity = max(color.r, max(color.g, color.b));
         float radius = finf();
         if (attenuation[2] != 0) {
             // Solve I / attenuation.dot(1, r, r^2) < cutoff for r
             //
             //  a[0] + a[1] r + a[2] r^2 > I/cutoff
             //
             float a = attenuation[2];
             float b = attenuation[1];
             float c = attenuation[0] - maxIntensity / cutoff;
             float discrim = square(b) - 4 * a * c;
             if (discrim >= 0) {
                 discrim = sqrt(discrim);
                 float r1 = (-b + discrim) / (2 * a);
                 float r2 = (-b - discrim) / (2 * a);
                 if (r1 < 0) {
                     if (r2 > 0) {
                         radius = r2;
                     }
                 } else if (r2 > 0) {
                     radius = min(r1, r2);
                 } else {
                     radius = r1;
                 }
             }
         } else if (attenuation[1] != 0) {
             // Solve I / attenuation.dot(1, r) < cutoff for r
             //
             // r * a[1] + a[0] = I / cutoff
             // r = (I / cutoff - a[0]) / a[1]
             float radius = (maxIntensity / cutoff - attenuation[0]) / attenuation[1];
             radius = max(radius, 0.0f);
         }
         return Sphere(position.xyz(), radius);
     }
 }
References mpq::a, attenuation, b, mpq::c, G3D::finf(), G3D::max(), G3D::min(), position, G3D::square(), G3D::Vector4::w, G3D::Vector4::xyz(), and G3D::Vector3::zero().
frame()
CoordinateFrame G3D::GLight::frame () const
Computes a reference frame (e.g., for use with G3D::ShadowMap
Definition at line 241 of file GLight.cpp.
{
     CoordinateFrame f;
     if (rightDirection == Vector3::zero()) {
         // No specified right direction; choose one automatically
         if (position.w == 0) {
             // Directional light
             f.lookAt(-position.xyz());
         } else {
             // Spot light
             f.lookAt(spotDirection);
         }
     } else {
         const Vector3& Z = -spotDirection.direction();
         Vector3 X = rightDirection.direction();
         // Ensure the vectors are not too close together
         while (abs(X.dot(Z)) > 0.9f) {
             X = Vector3::random();
         }
         // Ensure perpendicular
         X -= Z * Z.dot(X);
         const Vector3& Y = Z.cross(X);
         f.rotation.setColumn(Vector3::X_AXIS, X);
         f.rotation.setColumn(Vector3::Y_AXIS, Y);
         f.rotation.setColumn(Vector3::Z_AXIS, Z);
     }
     f.translation = position.xyz();
     return f;
 }
References G3D::abs(), G3D::Vector3::direction(), f(), position, G3D::Vector3::random(), rightDirection, spotDirection, G3D::Vector4::w, X, G3D::Vector3::X_AXIS, G3D::Vector4::xyz(), Y, G3D::Vector3::Y_AXIS, Z, G3D::Vector3::Z_AXIS, and G3D::Vector3::zero().
operator Any()
G3D::GLight::operator Any () const
Converts the Color3 to an Any.
Definition at line 87 of file GLight.cpp.
{
     Any a(Any::TABLE, "GLight");
     a.set("position", position.operator Any());
     a.set("rightDirection", rightDirection.operator Any());
     a.set("spotDirection", spotDirection.operator Any());
     a.set("spotCutoff", spotCutoff);
     a.set("spotSquare", spotSquare);
     Any att(Any::ARRAY);
     att.append(attenuation[0], attenuation[1], attenuation[2]);
     a.set("attenuation", att);
     a.set("color", color.operator Any());
     a.set("enabled", enabled);
     a.set("specular", specular);
     a.set("diffuse", diffuse);
     return a;
 }
References mpq::a, G3D::Any::append(), G3D::Any::ARRAY, and G3D::Any::TABLE.
operator!=()
bool G3D::GLight::operator!= (const GLight & other) const
Definition at line 178 of file GLight.cpp.
{
     return !(*this == other);
 }
operator==()
bool G3D::GLight::operator== (const GLight & other) const
Definition at line 162 of file GLight.cpp.
{
     return (position == other.position) &&
         (rightDirection == other.rightDirection) &&
         (spotDirection == other.spotDirection) &&
         (spotCutoff == other.spotCutoff) &&
         (spotSquare == other.spotSquare) &&
         (attenuation[0] == other.attenuation[0]) &&
         (attenuation[1] == other.attenuation[1]) &&
         (attenuation[2] == other.attenuation[2]) &&
         (color == other.color) &&
         (enabled == other.enabled) &&
         (specular == other.specular) &&
         (diffuse == other.diffuse);
 }
References attenuation, color, diffuse, enabled, position, rightDirection, specular, spotCutoff, spotDirection, and spotSquare.
point()
GLight G3D::GLight::point (const Vector3 & pos, const Color3 & color, float constAtt = 1, float linAtt = 0, float quadAtt = 0.5f, bool specular = true, bool diffuse = true) static
Definition at line 133 of file GLight.cpp.
{
     GLight L;
     L.position = Vector4(pos, 1);
     L.color    = color;
     L.attenuation[0] = constAtt;
     L.attenuation[1] = linAtt;
     L.attenuation[2] = quadAtt;
     L.specular       = s;
     L.diffuse        = d;
     return L;
 }
References attenuation, color, mpq::d, diffuse, pos(), position, and specular.
Referenced by GLight().
spot()
GLight G3D::GLight::spot (const Vector3 & pos, const Vector3 & pointDirection, float cutOffAngleDegrees, const Color3 & color, float constAtt = 1, float linAtt = 0, float quadAtt = 0, bool specular = true, bool diffuse = true) static
Parameters
pointDirection Will be normalized. Points in the direction that light propagates.
cutOffAngleDegrees Must be on the range [0, 90]. This is the angle from the point direction to the edge of the light cone. I.e., a value of 45 produces a light with a 90-degree cone of view.
Definition at line 146 of file GLight.cpp.
{
     GLight L;
     L.position       = Vector4(pos, 1.0f);
     L.spotDirection  = pointDirection.direction();
     debugAssert(cutOffAngleDegrees <= 90);
     L.spotCutoff     = cutOffAngleDegrees;
     L.color          = color;
     L.attenuation[0] = constAtt;
     L.attenuation[1] = linAtt;
     L.attenuation[2] = quadAtt;
     L.specular       = s;
     L.diffuse        = d;
     return L;
 }
References attenuation, color, mpq::d, debugAssert, diffuse, G3D::Vector3::direction(), pos(), position, specular, spotCutoff, and spotDirection.
Referenced by GLight(), and spotTarget().
spotTarget()
static GLight G3D::GLight::spotTarget (const Vector3 & pos, const Vector3 & target, float cutOffAngleDegrees, const Color3 & color, float constAtt = 1, float linAtt = 0, float quadAtt = 0, bool specular = true, bool diffuse = true) inline static
Creates a spot light that looks at a specific point (by calling spot())
Definition at line 94 of file GLight.h.
{
            return spot(pos, target - pos, cutOffAngleDegrees, color, constAtt, linAtt, quadAtt, specular, diffuse);
     }
References diffuse, pos(), specular, and spot().
Referenced by GLight().
Member Data Documentation
attenuation
float G3D::GLight::attenuation[3]
Constant, linear, quadratic
Definition at line 47 of file GLight.h.
Referenced by effectSphere(), GLight(), operator==(), point(), and spot().
color
Color3 G3D::GLight::color
May be outside the range [0, 1]
Definition at line 50 of file GLight.h.
Referenced by directional(), operator==(), point(), and spot().
diffuse
bool G3D::GLight::diffuse
If false, this light does not create diffuse illumination (useful when rendering a specular-only pass).
Definition at line 61 of file GLight.h.
Referenced by directional(), GLight(), operator==(), point(), spot(), and spotTarget().
enabled
bool G3D::GLight::enabled
If false, this light is ignored
Definition at line 53 of file GLight.h.
Referenced by GLight(), and operator==().
position
Vector4 G3D::GLight::position
World space position (for a directional light, w = 0
Definition at line 27 of file GLight.h.
Referenced by directional(), effectSphere(), frame(), GLight(), operator==(), point(), and spot().
rightDirection
Vector3 G3D::GLight::rightDirection
For a spot or directional light, this is the "right vector" that will be used when constructing a reference frame().
Definition at line 31 of file GLight.h.
Referenced by frame(), GLight(), and operator==().
specular
bool G3D::GLight::specular
If false, this light does not create specular highlights (useful when using negative lights).
Definition at line 57 of file GLight.h.
Referenced by directional(), GLight(), operator==(), point(), spot(), and spotTarget().
spotCutoff
float G3D::GLight::spotCutoff
In degrees. 180 = no cutoff (point/dir). Values less than 90 = spot light
Definition at line 37 of file GLight.h.
Referenced by GLight(), operator==(), and spot().
spotDirection
Vector3 G3D::GLight::spotDirection
Direction in which the light faces, if a spot light. This is the "look vector" of the light source.
Definition at line 34 of file GLight.h.
Referenced by frame(), GLight(), operator==(), and spot().
spotSquare
bool G3D::GLight::spotSquare
If true, G3D::SuperShader will render a cone of light large enough to encompass the entire square that bounds the cutoff angle. This produces a square prism instead of a cone of light when used with a G3D::ShadowMap. for an unshadowed light this has no effect.
Definition at line 44 of file GLight.h.
Referenced by GLight(), and operator==().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/GLight.h
deps/g3dlite/source/GLight.cpp