Azerotcore-wotlk: PlayerNameMapHolder Namespace Reference
PlayerNameMapHolder Namespace Reference
Typedefs
typedef std::unordered_map< std::string, Player * > MapType
Functions
void Insert (Player *p)
void Remove (Player *p)
Player * Find (std::string const &name)
Variables
static MapType PlayerNameMap
Typedef Documentation
MapType
typedef std::unordered_map<std::string, Player*> PlayerNameMapHolder::MapType
Definition at line 90 of file ObjectAccessor.cpp.
Function Documentation
Find()
Player* PlayerNameMapHolder::Find (std::string const & name)
Definition at line 103 of file ObjectAccessor.cpp.
     {
         std::string charName(name);
         if (!normalizePlayerName(charName))
             return nullptr;
         auto itr = PlayerNameMap.find(charName);
         return (itr != PlayerNameMap.end()) ? itr->second : nullptr;
     }
References normalizePlayerName(), and PlayerNameMap.
Referenced by ObjectAccessor::FindPlayerByName().
Insert()
void PlayerNameMapHolder::Insert (Player * p)
Definition at line 93 of file ObjectAccessor.cpp.
     {
         PlayerNameMap[p->GetName()] = p;
     }
References WorldObject::GetName(), and PlayerNameMap.
Referenced by ObjectAccessor::AddObject().
Remove()
void PlayerNameMapHolder::Remove (Player * p)
Definition at line 98 of file ObjectAccessor.cpp.
     {
         PlayerNameMap.erase(p->GetName());
     }
References WorldObject::GetName(), and PlayerNameMap.
Referenced by ObjectAccessor::RemoveObject().
Variable Documentation
PlayerNameMap
MapType PlayerNameMapHolder::PlayerNameMap static
Definition at line 91 of file ObjectAccessor.cpp.
Referenced by Find(), Insert(), and Remove().