Azerotcore-wotlk: achievement_flu_shot_shortage Class Reference
achievement_flu_shot_shortage Class Reference
Public Member Functions
achievement_flu_shot_shortage ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 410 of file boss_festergut.cpp.
Constructor & Destructor Documentation
achievement_flu_shot_shortage()
achievement_flu_shot_shortage::achievement_flu_shot_shortage () inline
Definition at line 413 of file boss_festergut.cpp.
 : AchievementCriteriaScript("achievement_flu_shot_shortage") { }
Member Function Documentation
OnCheck()
bool achievement_flu_shot_shortage::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 415 of file boss_festergut.cpp.
     {
         if (target && target->GetTypeId() == TYPEID_UNIT)
             return target->ToCreature()->AI()->GetData(DATA_INOCULATED_STACK) < 3;
         return false;
     }
References Creature::AI(), DATA_INOCULATED_STACK, UnitAI::GetData(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp