Azerotcore-wotlk: G3D::Table< Key, Value, HashFunc, EqualsFunc > Class Template Reference
G3D::Table< Key, Value, HashFunc, EqualsFunc > Class Template Reference
#include <Table.h>
Classes
class Entry
class Iterator
class Node
Public Member Functions
Table ()
void clearAndSetMemoryManager (const MemoryManager::Ref &m)
void setSizeHint (size_t n)
virtual ~Table ()
Table (const ThisType &h)
Table & operator= (const ThisType &h)
size_t debugGetDeepestBucketSize () const
float debugGetAverageBucketSize () const
double debugGetLoad () const
size_t debugGetNumBuckets () const
Iterator begin () const
const Iterator end () const
void clear ()
size_t size () const
void set (const Key &key, const Value &value)
bool getRemove (const Key &key, Key &removedKey, Value &removedValue)
bool remove (const Key &key)
const Key * getKeyPointer (const Key &key) const
Value & get (const Key &key) const
Value * getPointer (const Key &key) const
bool get (const Key &key, Value &val) const
Entry & getCreateEntry (const Key &key, bool &created)
Entry & getCreateEntry (const Key &key)
Value & getCreate (const Key &key)
Value & getCreate (const Key &key, bool &created)
bool containsKey (const Key &key) const
Value & operator[] (const Key &key) const
Array< Key > getKeys () const
void getKeys (Array< Key > &keyArray) const
void getValues (Array< Value > &valueArray) const
void deleteKeys ()
void deleteValues ()
template<class H , class E >
bool operator== (const Table< Key, Value, H, E > &other) const
template<class H , class E >
bool operator!= (const Table< Key, Value, H, E > &other) const
void debugPrintStatus ()
Private Types
typedef Table< Key, Value, HashFunc, EqualsFunc > ThisType
Private Member Functions
void checkIntegrity () const
void * alloc (size_t s) const
void free (void *p) const
void resize (size_t newSize)
void copyFrom (const ThisType &h)
void freeMemory ()
bool remove (const Key &key, Key &removedKey, Value &removedValue, bool updateRemoved)
Entry * getEntryPointer (const Key &key) const
Private Attributes
size_t m_size
Node ** m_bucket
size_t m_numBuckets
MemoryManager::Ref m_memoryManager
Detailed Description
template<class Key, class Value, class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>>
class G3D::Table< Key, Value, HashFunc, EqualsFunc >
An unordered data structure mapping keys to values.
There are two ways of definining custom hash functions (G3D provides built-in ones for most classes):
class Foo {
public:
    std::string     name;
    int             index;
    static size_t hashCode(const Foo& key) {
         return HashTrait<std::string>::hashCode(key.name) + key.index;
    }
 };
 template<> struct HashTrait<class Foo> {
      static size_t hashCode(const Foo& key) { return HashTrait<std::string>::hashCode(key.name) + key.index; }
 };
 // Use Foo::hashCode
 Table<Foo, std::string, Foo> fooTable1;
 // Use HashTrait<Foo>
 Table<Foo, std::string>      fooTable2;
Key must be a pointer, an int, a std::string or provide overloads for:
   template<> struct HashTrait<class Key> {
       static size_t hashCode(const Key& key) { return reinterpret_cast<size_t>( ... ); }
   };
and one of
   template<> struct EqualsTrait<class Key>{
        static bool equals(const Key& a, const Key& b) { return ... ; }
   };
   bool operator==(const Key&, const Key&);
G3D pre-defines HashTrait specializations for common types (like int and std::string). If you use a Table with a different type you must write those functions yourself. For example, an enum would use:
   template<> struct HashTrait<MyEnum> {
       static size_t hashCode(const MyEnum& key) const { return reinterpret_cast<size_t>( key ); }
   };
And rely on the default enum operator==.
Periodically check that debugGetLoad() is low (> 0.1). When it gets near 1.0 your hash function is badly designed and maps too many inputs to the same output.
Definition at line 101 of file Table.h.
Member Typedef Documentation
ThisType
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> typedef Table<Key, Value, HashFunc, EqualsFunc> G3D::Table< Key, Value, HashFunc, EqualsFunc >::ThisType private
Definition at line 120 of file Table.h.
Constructor & Destructor Documentation
Table() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table () inline
Creates an empty hash table using the default MemoryManager.
Definition at line 300 of file Table.h.
             : m_bucket(NULL) {
         m_memoryManager = MemoryManager::create();
         m_numBuckets = 0;
         m_size       = 0;
         m_bucket     = NULL;
         checkIntegrity();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::MemoryManager::create(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, and NULL.
~Table()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> virtual G3D::Table< Key, Value, HashFunc, EqualsFunc >::~Table () inline virtual
Destroys all of the memory allocated by the table, but does not call delete on keys or values if they are pointers. If you want to deallocate things that the table points at, use getKeys() and Array::deleteAll() to delete them.
Definition at line 331 of file Table.h.
                      {
         freeMemory();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory().
Table() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table (const ThisType & h) inline
Uses the default memory manager
Definition at line 336 of file Table.h.
{
         m_memoryManager = MemoryManager::create();
         m_numBuckets = 0;
         m_size = 0;
         m_bucket = NULL;
         this->copyFrom(h);
         checkIntegrity();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::MemoryManager::create(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, and NULL.
Member Function Documentation
alloc()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void* G3D::Table< Key, Value, HashFunc, EqualsFunc >::alloc (size_t s) const inline private
Definition at line 201 of file Table.h.
{
         return m_memoryManager->alloc(s);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize().
begin()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Iterator G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin () const inline
C++ STL style iterator method. Returns the first Entry, which contains a key and value. Use preincrement (++entry) to get to the next element. Do not modify the table while iterating.
Definition at line 562 of file Table.h.
{
         return Iterator(m_numBuckets, m_bucket);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::begin(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::begin(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::clear(), G3D::GCamera::GCamera(), G3D::Any::operator==(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator==(), G3D::XML::serialize(), G3D::AnyTableReader::verifyDone(), and G3D::MeshAlg::weldBoundaryEdges().
checkIntegrity()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity () const inline private
Definition at line 169 of file Table.h.
{
 #       ifdef G3D_DEBUG
            debugAssert(m_bucket == NULL || isValidHeapPointer(m_bucket));
            for (size_t b = 0; b < m_numBuckets; ++b) {
                Node* node = m_bucket[b];
                debugAssert(node == NULL || isValidHeapPointer(node));
                while (node != NULL) {
                    debugAssert(node == NULL || isValidHeapPointer(node));
                    node = node->next;
                }
            }
 #       endif
     }
References b, debugAssert, G3D::isValidHeapPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator=(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
clear()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear () inline
Removes all elements. Guaranteed to free all memory associated with the table.
Definition at line 578 of file Table.h.
                  {
         freeMemory();
         m_numBuckets = 0;
         m_size = 0;
         m_bucket = NULL;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, and NULL.
Referenced by G3D::Any::clear(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::clear(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clear(), G3D::WeakCache< Key, ValueRef >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteKeys(), and G3D::XML::deserialize().
clearAndSetMemoryManager()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager (const MemoryManager::Ref & m) inline
Changes the internal memory manager to m
Definition at line 309 of file Table.h.
{
         clear();
         debugAssert(m_bucket == NULL);
         m_memoryManager = m;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, and NULL.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
containsKey()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey (const Key & key) const inline
Returns true if key is in the table.
Definition at line 874 of file Table.h.
{
        if (m_numBuckets == 0) {
            return false;
        }
        size_t code = HashFunc::hashCode(key);
        size_t b = code % m_numBuckets;
        Node* node = m_bucket[b];
        while (node != NULL) {
            if ((node->hashCode == code) && EqualsFunc::equals(node->entry.key, key)) {
               return true;
            }
            node = node->next;
        }
        return false;
    }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::hashCode(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::contains(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::contains(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::contains(), G3D::XML::containsAttribute(), G3D::AnyVal::get(), G3D::WeakCache< Key, ValueRef >::operator[](), G3D::AnyVal::operator[](), G3D::WeakCache< Key, ValueRef >::remove(), and G3D::MeshAlg::weldBoundaryEdges().
copyFrom()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom (const ThisType & h) inline private
Definition at line 252 of file Table.h.
{
         if (&h == this) {
             return;
         }
         debugAssert(m_bucket == NULL);
         m_size = h.m_size;
         m_numBuckets = h.m_numBuckets;
         m_bucket = (Node**)alloc(sizeof(Node*) * m_numBuckets);
         // No need to NULL elements since we're about to overwrite them
         for (size_t b = 0; b < m_numBuckets; ++b) {
             if (h.m_bucket[b] != NULL) {
                 m_bucket[b] = h.m_bucket[b]->clone(m_memoryManager);
             } else {
                 m_bucket[b] = NULL;
             }
         }
         checkIntegrity();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::alloc(), b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::clone(), debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator=(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
debugGetAverageBucketSize()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> float G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize () const inline
Returns the average size of non-empty buckets.
Definition at line 382 of file Table.h.
{
         uint64 num = 0;
         for (size_t b = 0; b < m_numBuckets; ++b) {
             Node* node = m_bucket[b];
             if (node != NULL) {
                 ++num;
             }
         }
         return (float)((double)size() / num);
     }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::size().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugPrintStatistics(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugPrintStatus().
debugGetDeepestBucketSize()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize () const inline
Returns the length of the deepest m_bucket.
Definition at line 360 of file Table.h.
{
         size_t deepest = 0;
         for (size_t b = 0; b < m_numBuckets; ++b) {
             size_t  count = 0;
             Node*   node = m_bucket[b];
             while (node != NULL) {
                 node = node->next;
                 ++count;
             }
             if (count > deepest) {
                 deepest = count;
             }
         }
         return deepest;
     }
References b, count(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugPrintStatistics(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugPrintStatus().
debugGetLoad()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> double G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetLoad () const inline
A small load (close to zero) means the hash table is acting very efficiently most of the time. A large load (close to 1) means the hash table is acting poorly– all operations will be very slow. A large load will result from a bad hash function that maps too many keys to the same code.
Definition at line 402 of file Table.h.
{
         return (double)size() / m_numBuckets;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::size().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugPrintStatistics(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugPrintStatus().
debugGetNumBuckets()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetNumBuckets () const inline
Returns the number of buckets.
Definition at line 409 of file Table.h.
{
         return m_numBuckets;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets.
debugPrintStatus()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugPrintStatus () inline
Definition at line 995 of file Table.h.
{
         debugPrintf("Deepest bucket size    = %d\n", (int)debugGetDeepestBucketSize());
         debugPrintf("Average bucket size    = %g\n", debugGetAverageBucketSize());
         debugPrintf("Load factor            = %g\n", debugGetLoad());
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetLoad(), and G3D::debugPrintf().
deleteKeys()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteKeys () inline
Calls delete on all of the keys and then clears the table.
Definition at line 939 of file Table.h.
                      {
        for (size_t i = 0; i < m_numBuckets; ++i) {
            Node* node = m_bucket[i];
            while (node != NULL) {
                delete node->entry.key;
                node->entry.key = NULL;
                node = node->next;
            }
        }
        clear();
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
deleteValues()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteValues () inline
Calls delete on all of the values. This is unsafe– do not call unless you know that each value appears at most once.
Does not clear the table, so you are left with a table of NULL pointers.
Definition at line 959 of file Table.h.
{
        for (size_t i = 0; i < m_numBuckets; ++i) {
            Node* node = m_bucket[i];
            while (node != NULL) {
                delete node->entry.value;
                node->entry.value = NULL;
                node = node->next;
            }
        }
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
end()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> const Iterator G3D::Table< Key, Value, HashFunc, EqualsFunc >::end () const inline
C++ STL style iterator method. Returns one after the last iterator element.
Definition at line 570 of file Table.h.
{
         return Iterator();
     }
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::clear(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::end(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::end(), and G3D::MeshAlg::weldBoundaryEdges().
free()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::free (void * p) const inline private
Definition at line 205 of file Table.h.
{
         return m_memoryManager->free(p);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize().
freeMemory()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory () inline private
Frees the heap structures for the nodes.
Definition at line 277 of file Table.h.
                       {
         checkIntegrity();
         for (size_t b = 0; b < m_numBuckets; ++b) {
             Node* node = m_bucket[b];
             while (node != NULL) {
                 Node* next = node->next;
                 Node::destroy(node, m_memoryManager);
                 node = next;
             }
             m_bucket[b] = NULL;
         }
         free(m_bucket);
         m_bucket     = NULL;
         m_numBuckets = 0;
         m_size       = 0;
     }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::destroy(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::free(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, next(), and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator=(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::~Table().
get() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Value& G3D::Table< Key, Value, HashFunc, EqualsFunc >::get (const Key & key) const inline
Returns the value associated with key.
Deprecated:
Use get(key, val) or getPointer(key)
Definition at line 714 of file Table.h.
{
        Entry* e = getEntryPointer(key);
        debugAssertM(e != NULL, "Key not found");
        return e->value;
    }
References debugAssertM, G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer(), NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator[]().
get() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::get (const Key & key, Value & val) const inline
If the key is present in the table, val is set to the associated value and returns true. If the key is not present, returns false.
Definition at line 757 of file Table.h.
{
        Value* v = getPointer(key);
        if (v != NULL) {
            val = *v;
            return true;
        } else {
            return false;
        }
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), and NULL.
getCreate() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Value& G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreate (const Key & key) inline
Returns the current value that key maps to, creating it if necessary.
Definition at line 861 of file Table.h.
{
         return getCreateEntry(key).value;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::Any::operator[](), and G3D::_internal::WeldHelper::smoothNormals().
getCreate() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Value& G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreate (const Key & key, bool & created) inline
Parameters
created True if the element was created.
Definition at line 866 of file Table.h.
{
         return getCreateEntry(key, created).value;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
getCreateEntry() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Entry& G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry (const Key & key) inline
Definition at line 854 of file Table.h.
{
         bool ignore;
         return getCreateEntry(key, ignore);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry().
getCreateEntry() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Entry& G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry (const Key & key, bool & created) inline
Called by getCreate() and set()
Parameters
created Set to true if the entry was created by this method.
Definition at line 772 of file Table.h.
{
         created = false;
         if (m_numBuckets == 0) {
             resize(10);
         }
         size_t code = HashFunc::hashCode(key);
         size_t b = code % m_numBuckets;
         // Go to the m_bucket
         Node* n = m_bucket[b];
         // No m_bucket, so this must be the first
         if (n == NULL) {
             m_bucket[b] = Node::create(key, code, NULL, m_memoryManager);
             ++m_size;
             created = true;
             //checkIntegrity();
             return m_bucket[b]->entry;
         }
         size_t bucketLength = 1;
         // Sometimes a bad hash code will cause all elements
         // to collide.  Detect this case and don't rehash when
         // it occurs; nothing good will come from the rehashing.
         bool allSameCode = true;
         // Try to find the node
         do {
             allSameCode = allSameCode && (code == n->hashCode);
             if ((code == n->hashCode) && EqualsFunc::equals(n->entry.key, key)) {
                // This is the a pre-existing node
                //checkIntegrity();
                return n->entry;
             }
             n = n->next;
             ++bucketLength;
         } while (n != NULL);
         // Allow the load factor to rise as the table gets huge
         const int bucketsPerElement =
             (m_size > 50000) ? 3 :
                 ((m_size > 10000) ? 5 :
                  ((m_size > 5000) ? 10 : 15));
         const size_t maxBucketLength = 3;
         // (Don't bother changing the size of the table if all entries
         // have the same hashcode--they'll still collide)
         if ((bucketLength > maxBucketLength) &&
             ! allSameCode &&
             (m_numBuckets < m_size * bucketsPerElement)) {
             // This m_bucket was really large; rehash if all elements
             // don't have the same hashcode the number of buckets is
             // reasonable.
             // Back off the scale factor as the number of buckets gets
             // large
             float f = 3.0f;
             if (m_numBuckets > 1000000) {
                 f = 1.5f;
             } else if (m_numBuckets > 100000) {
                 f = 2.0f;
             }
             int newSize = iMax((int)(m_numBuckets * f) + 1, (int)(m_size * f));
             resize(newSize);
         }
         // Not found; insert at the head.
         b = code % m_numBuckets;
         m_bucket[b] = Node::create(key, code, m_bucket[b], m_memoryManager);
         ++m_size;
         created = true;
         //checkIntegrity();
         return m_bucket[b]->entry;
     }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::create(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, f(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::hashCode(), G3D::iMax(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize().
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreate(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::set().
getEntryPointer()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Entry* G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer (const Key & key) const inline private
Definition at line 676 of file Table.h.
{
        if (m_numBuckets == 0) {
            return NULL;
        }
        size_t  code = HashFunc::hashCode(key);
        size_t b = code % m_numBuckets;
        Node* node = m_bucket[b];
        while (node != NULL) {
            if ((node->hashCode == code) && EqualsFunc::equals(node->entry.key, key)) {
                return &(node->entry);
            }
            node = node->next;
        }
        return NULL;
    }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::hashCode(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::get(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeyPointer().
getKeyPointer()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> const Key* G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeyPointer (const Key & key) const inline
If a value that is EqualsFunc to member is present, returns a pointer to the version stored in the data structure, otherwise returns NULL.
Definition at line 701 of file Table.h.
{
        const Entry* e = getEntryPointer(key);
        if (e == NULL) {
            return NULL;
        } else {
            return &(e->key);
        }
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, and NULL.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getPointer().
getKeys() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Array<Key> G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys () const inline
Returns an array of all of the keys in the table. You can iterate over the keys to get the values.
Deprecated:
Definition at line 907 of file Table.h.
{
        Array<Key> keyArray;
        getKeys(keyArray);
        return keyArray;
    }
Referenced by BIHWrap< T, BoundsFunc >::balance(), G3D::AnyVal::getKeys(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getMembers(), and G3D::WeakCache< Key, ValueRef >::getValues().
getKeys() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys (Array< Key > & keyArray) const inline
Definition at line 913 of file Table.h.
{
        keyArray.resize(0, DONT_SHRINK_UNDERLYING_ARRAY);
        for (size_t i = 0; i < m_numBuckets; ++i) {
            Node* node = m_bucket[i];
            while (node != NULL) {
                keyArray.append(node->entry.key);
                node = node->next;
            }
        }
    }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, and G3D::Array< T, MIN_ELEMENTS >::resize().
getPointer()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Value* G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer (const Key & key) const inline
Returns a pointer to the element if it exists, or NULL if it does not. Note that if your value type is a pointer, the return value is a pointer to a pointer. Do not remove the element while holding this pointer.
It is easy to accidentally mis-use this method. Consider making a Table<Value*> and using get(key, val) instead, which makes you manage the memory for the values yourself and is less likely to result in pointer errors.
Definition at line 731 of file Table.h.
{
        if (m_numBuckets == 0) {
            return NULL;
        }
        size_t code = HashFunc::hashCode(key);
        size_t b = code % m_numBuckets;
        Node* node = m_bucket[b];
        while (node != NULL) {
           if ((node->hashCode == code) && EqualsFunc::equals(node->entry.key, key)) {
              // found key
              return &(node->entry.value);
           }
           node = node->next;
       }
       // Failed to find key
       return NULL;
    }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::hashCode(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Referenced by G3D::Any::containsKey(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::get(), G3D::XML::get(), G3D::Any::operator==(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator==().
getRemove()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::getRemove (const Key & key, Key & removedKey, Value & removedValue) inline
If member is present, sets removed to the element being removed and returns true. Otherwise returns false and does not write to removed.
Definition at line 660 of file Table.h.
{
        return remove(key, removedKey, removedValue, true);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove().
Referenced by BIHWrap< T, BoundsFunc >::remove().
getValues()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::getValues (Array< Value > & valueArray) const inline
Will contain duplicate values if they exist in the table. This array is parallel to the one returned by getKeys() if the table has not been modified.
Definition at line 925 of file Table.h.
{
        valueArray.resize(0, DONT_SHRINK_UNDERLYING_ARRAY);
        for (size_t i = 0; i < m_numBuckets; ++i) {
            Node* node = m_bucket[i];
            while (node != NULL) {
                valueArray.append(node->entry.value);
                node = node->next;
            }
        }
    }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
operator!=()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> template<class H , class E > bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator!= (const Table< Key, Value, H, E > & other) const inline
Definition at line 991 of file Table.h.
{
         return ! (*this == other);
     }
operator=()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Table& G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator= (const ThisType & h) inline
Definition at line 346 of file Table.h.
{
         // No need to copy if the argument is this
         if (this != &h) {
             // Free the existing nodes
             freeMemory();
             this->copyFrom(h);
             checkIntegrity();
         }
         return *this;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory().
operator==()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> template<class H , class E > bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator== (const Table< Key, Value, H, E > & other) const inline
Definition at line 971 of file Table.h.
{
         if (size() != other.size()) {
             return false;
         }
         for (Iterator it = begin(); it.hasMore(); ++it) {
             const Value* v = other.getPointer(it->key);
             if ((v == NULL) || (*v != it->value)) {
                 // Either the key did not exist or the value was not the same
                 return false;
             }
         }
         // this and other have the same number of keys, so we don't
         // have to check for extra keys in other.
         return true;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::hasMore(), NULL, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::size().
operator[]()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Value& G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator[] (const Key & key) const inline
Short syntax for get.
Definition at line 898 of file Table.h.
{
       return get(key);
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::get().
remove() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove (const Key & key) inline
Removes an element from the table if it is present.
Returns
true if the element was found and removed, otherwise false
Definition at line 668 of file Table.h.
{
        Key x;
        Value v;
        return remove(key, x, v, false);
    }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), and G3D::x.
remove() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove (const Key & key, Key & removedKey, Value & removedValue, bool updateRemoved) inline private
Helper for remove() and getRemove()
Definition at line 606 of file Table.h.
{
         if (m_numBuckets == 0) {
             return false;
         }
         const size_t code = HashFunc::hashCode(key);
         const size_t b = code % m_numBuckets;
         // Go to the m_bucket
         Node* n = m_bucket[b];
         if (n == NULL) {
             return false;
         }
         Node* previous = NULL;
         // Try to find the node
         do {
           if ((code == n->hashCode) && EqualsFunc::equals(n->entry.key, key)) {
               // This is the node; remove it
               // Replace the previous's next pointer
               if (previous == NULL) {
                   m_bucket[b] = n->next;
               } else {
                   previous->next = n->next;
               }
               if (updateRemoved) {
                   removedKey   = n->entry.key;
                   removedValue = n->entry.value;
               }
               // Delete the node
               Node::destroy(n, m_memoryManager);
               --m_size;
               //checkIntegrity();
               return true;
           }
           previous = n;
           n = n->next;
       } while (n != NULL);
       //checkIntegrity();
       return false;
    }
References b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::destroy(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::hashCode(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, NULL, utf8::previous(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::getRemove(), G3D::WeakCache< Key, ValueRef >::operator[](), G3D::WeakCache< Key, ValueRef >::remove(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::Any::remove(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::remove(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::remove(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
resize()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize (size_t newSize) inline private
Re-hashes for a larger m_bucket size.
Definition at line 212 of file Table.h.
{
         // Hang onto the old m_bucket array
         Node** oldBucket = m_bucket;
         // Allocate a new m_bucket array with the new size
         m_bucket = (Node**)alloc(sizeof(Node*) * newSize);
         alwaysAssertM(m_bucket != NULL, "MemoryManager::alloc returned NULL. Out of memory.");
         // Set all pointers to NULL
         System::memset(m_bucket, 0, newSize * sizeof(Node*));
         // Move each node to its new hash location
         for (size_t b = 0; b < m_numBuckets; ++b) {
             Node* node = oldBucket[b];
             // There is a linked list of nodes at this m_bucket
             while (node != NULL) {
                 // Hang onto the old next pointer
                 Node* nextNode = node->next;
                 // Insert at the head of the list for m_bucket[i]
                 size_t i = node->hashCode % newSize;
                 node->next = m_bucket[i];
                 m_bucket[i] = node;
                 // Move on to the next node
                 node = nextNode;
             }
             // Drop the old pointer for cleanliness when debugging
             oldBucket[b] = NULL;
         }
         // Delete the old storage
         free(oldBucket);
         this->m_numBuckets = newSize;
         checkIntegrity();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::alloc(), alwaysAssertM, b, G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::free(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::hashCode, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, G3D::System::memset(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::setSizeHint().
set()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::set (const Key & key, const Value & value) inline
If you insert a pointer into the key or value of a table, you are responsible for deallocating the object eventually. Inserting key into a table is O(1), but may cause a potentially slow rehashing.
Definition at line 599 of file Table.h.
{
         getCreateEntry(key).value = value;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::cloneTree(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::cloneTree(), G3D::XML::deserialize(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::insert(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::AnyVal::operator[](), G3D::WeakCache< Key, ValueRef >::set(), and G3D::MeshAlg::weldBoundaryEdges().
setSizeHint()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::setSizeHint (size_t n) inline
Recommends that the table resize to anticipate at least this number of elements.
Definition at line 318 of file Table.h.
{
         size_t s = n * 3;
         if (s > m_numBuckets) {
             resize(s);
         }
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert().
size()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::size () const inline
Returns the number of keys.
Definition at line 589 of file Table.h.
{
         return m_size;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetLoad(), G3D::XML::numAttributes(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator==(), G3D::Any::size(), G3D::AnyVal::size(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::size(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::size(), and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::size().
Member Data Documentation
m_bucket
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Node** G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_bucket private
Array of Node*.
We don't use Array<Node*> because Table is lower-level than Array. Some elements may be NULL.
Definition at line 192 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteKeys(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteValues(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getValues(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
m_memoryManager
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> MemoryManager::Ref G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_memoryManager private
Definition at line 199 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::alloc(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::free(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
m_numBuckets
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_numBuckets private
Length of the m_bucket array.
Definition at line 197 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetLoad(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetNumBuckets(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteKeys(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::deleteValues(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getValues(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::setSizeHint(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
m_size
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::m_size private
Number of elements in the table.
Definition at line 184 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::size(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Table.h