Azerotcore-wotlk: go_panther_cage Class Reference
go_panther_cage Class Reference
Public Member Functions
go_panther_cage ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 327 of file zone_thousand_needles.cpp.
Constructor & Destructor Documentation
go_panther_cage()
go_panther_cage::go_panther_cage () inline
Definition at line 330 of file zone_thousand_needles.cpp.
 : GameObjectScript("go_panther_cage") { }
Member Function Documentation
OnGossipHello()
bool go_panther_cage::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 332 of file zone_thousand_needles.cpp.
     {
         go->UseDoorOrButton();
         if (player->GetQuestStatus(5151) == QUEST_STATUS_INCOMPLETE)
         {
             if (Creature* panther = go->FindNearestCreature(ENRAGED_PANTHER, 5, true))
             {
                 panther->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 panther->SetReactState(REACT_AGGRESSIVE);
                 panther->AI()->AttackStart(player);
             }
         }
         return true;
     }
References ENRAGED_PANTHER, WorldObject::FindNearestCreature(), Player::GetQuestStatus(), QUEST_STATUS_INCOMPLETE, REACT_AGGRESSIVE, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_thousand_needles.cpp