Azerotcore-wotlk: Utils Class Reference
Utils Class Reference
#include <Utils.h>
Static Public Member Functions
static void Reverse (char word[])
static std::string ReadString (FILE *file)
static uint32 Size (FILE *file)
static Vector3 ToRecast (const Vector3 &val)
static std::string GetAdtPath (const std::string &world, int x, int y)
static std::string FixModelPath (const std::string &path)
template<typename T >
static std::string ToString (T val)
They say its better to declare template functions in the header files.
static float ToRadians (float degrees)
static std::string GetPathBase (const std::string &path)
static Vector3 GetLiquidVert (const IDefinition &def, Vector3 basePosition, float height, int, int, bool translate=true)
static float Distance (float x, float y)
template<typename T >
static bool IsAllZero (T *arr, uint32 size)
static std::string Replace (std::string str, const std::string &oldStr, const std::string &newStr)
static void CreateDir (const std::string &Path)
static void SaveToDisk (FILE *stream, const std::string &path)
static Vector3 ToWoWCoords (const Vector3 &vec)
static std::string GetExtension (std::string path)
static char * GetPlainName (const char *FileName)
static Vector3 TransformDoodadVertex (const IDefinition &def, Vector3 &vec, bool translate=true)
static Vector3 VectorTransform (const Vector3 &vec, const G3D::Matrix4 &matrix, bool normal=false)
static Vector3 TransformWmoDoodad (const DoodadInstance &inst, const WorldModelDefinition &root, Vector3 &vec, bool translate=true)
Detailed Description
Definition at line 364 of file Utils.h.
Member Function Documentation
CreateDir()
void Utils::CreateDir (const std::string & Path) static
Definition at line 47 of file Utils.cpp.
 {
 #ifdef _WIN32
     _mkdir( Path.c_str());
 #else
     mkdir( Path.c_str(), 0777 );
 #endif
 }
Referenced by ExtractDBCs(), and ExtractGameobjectModels().
Distance()
float Utils::Distance (float x, float y) static
Definition at line 171 of file Utils.cpp.
 {
     return sqrt(x * x + y * y);
 }
Referenced by GetLiquidVert().
FixModelPath()
std::string Utils::FixModelPath (const std::string & path) static
Definition at line 102 of file Utils.cpp.
 {
     return Utils::GetPathBase(path) + ".M2";
 }
References GetPathBase().
Referenced by ExtractGameobjectModels(), and Model::Model().
GetAdtPath()
std::string Utils::GetAdtPath (const std::string & world, int x, int y) static
Definition at line 97 of file Utils.cpp.
 {
     return "World\\Maps\\" + world + "\\" + world + "_" + Utils::ToString(x) + "_" + Utils::ToString(y) + ".adt";
 }
References ToString().
Referenced by TileBuilder::BuildTiled().
GetExtension()
std::string Utils::GetExtension (std::string path) static
Definition at line 232 of file Utils.cpp.
 {
     std::string::size_type idx = path.rfind('.');
     std::string extension = "";
     if (idx != std::string::npos)
         extension = path.substr(idx + 1);
     return extension;
 }
Referenced by ExtractGameobjectModels().
GetLiquidVert()
Vector3 Utils::GetLiquidVert (const IDefinition & def, Vector3 basePosition, float height, int x, int y, bool translate = true) static
Definition at line 164 of file Utils.cpp.
 {
     if (Utils::Distance(height, 0.0f) > 0.5f)
         basePosition.z = 0.0f;
     return Utils::TransformDoodadVertex(def, basePosition + Vector3(x * Constants::UnitSize, y * Constants::UnitSize, height), translate);
 }
References Distance(), TransformDoodadVertex(), Constants::UnitSize, and Vector3::z.
Referenced by WorldModelHandler::InsertModelGeometry().
GetPathBase()
std::string Utils::GetPathBase (const std::string & path) static
Definition at line 148 of file Utils.cpp.
 {
     size_t lastIndex = path.find_last_of(".");
     if (lastIndex != std::string::npos)
         return path.substr(0, lastIndex);
     return path;
 }
Referenced by FixModelPath(), and WorldModelRoot::ReadGroups().
GetPlainName()
char * Utils::GetPlainName (const char * FileName) static
Definition at line 534 of file Utils.cpp.
 {
     char* temp;
     if ((temp = (char*)strrchr(FileName, '\\')) != nullptr)
         FileName = temp + 1;
     return (char*)FileName;
 }
Referenced by ExtractGameobjectModels(), and WorldModelGroup::WorldModelGroup().
IsAllZero()
template<typename T > static bool Utils::IsAllZero (T * arr, uint32 size) inline static
Definition at line 386 of file Utils.h.
     {
         for (uint32 i = 0; i < size; ++i)
             if (arr[i])
                 return false;
         return true;
     }
Referenced by LiquidHandler::HandleNewLiquid().
ReadString()
std::string Utils::ReadString (FILE * file) static
Definition at line 67 of file Utils.cpp.
 {
     std::string ret;
     while (true)
     {
         char b;
         if (fread(&b, sizeof(char), 1, file) != 1 || b == 0)
             break;
         ret.push_back(b);
     }
     return ret;
 }
Referenced by WorldModelRoot::ReadDoodadInstances(), DoodadHandler::ReadDoodadPaths(), WDT::ReadGlobalModel(), and WorldModelHandler::ReadModelPaths().
Replace()
std::string Utils::Replace (std::string str, const std::string & oldStr, const std::string & newStr) static
Definition at line 176 of file Utils.cpp.
 {
     size_t pos = 0;
     while ((pos = str.find(oldStr, pos)) != std::string::npos)
     {
         str.replace(pos, oldStr.length(), newStr);
         pos += newStr.length();
     }
     return str;
 }
Reverse()
void Utils::Reverse (char word[]) static
Definition at line 56 of file Utils.cpp.
 {
     int len = strlen(word);
     for (int i = 0; i < len / 2; i++)
     {
         word[i] ^= word[len - i - 1];
         word[len - i - 1] ^= word[i];
         word[i] ^= word[len - i - 1];
     }
 }
SaveToDisk()
void Utils::SaveToDisk (FILE * stream, const std::string & path) static
Definition at line 187 of file Utils.cpp.
 {
     FILE* disk = fopen(path.c_str(), "wb");
     if (!disk)
     {
         printf("SaveToDisk: Could not save file %s to disk, please verify that you have write permissions on that directory\n", path.c_str());
         fclose(stream);
         return;
     }
     uint32 size = Utils::Size(stream);
     uint8* data = new uint8[size];
     // Read the data to an array
     size_t read = fread(data, size, 1, stream);
     if (read != 1)
     {
         printf("SaveToDisk: Error reading from Stream while trying to save file %s to disk.\n", path.c_str());
         fclose(disk);
         fclose(stream);
         return;
     }
     // And write it in the file
     size_t wrote = fwrite(data, size, 1, disk);
     if (wrote != 1)
     {
         printf("SaveToDisk: Error writing to the file while trying to save %s to disk.\n", path.c_str());
         fclose(stream);
         fclose(disk);
         return;
     }
     // Close the filestream
     fclose(disk);
     fclose(stream);
     // Free the used memory
     delete[] data;
 }
References Size().
Referenced by ExtractDBCs().
Size()
uint32 Utils::Size (FILE * file) static
Definition at line 80 of file Utils.cpp.
 {
     // store the old position
     uint32 offset = ftell(file);
     // Get file size
     fseek(file, 0, SEEK_END);
     uint32 size = ftell(file);
     // reset back to the old position
     fseek(file, offset, SEEK_SET);
     return size;
 }
Referenced by Chunk::FindSubChunkOffset(), ChunkedData::Load(), and SaveToDisk().
ToRadians()
float Utils::ToRadians (float degrees) static
Definition at line 136 of file Utils.cpp.
 {
     return Constants::PI * degrees / 180.0f;
 }
References Constants::PI.
Referenced by TransformDoodadVertex().
ToRecast()
Vector3 Utils::ToRecast (const Vector3 & val) static
Definition at line 92 of file Utils.cpp.
 {
     return Vector3(-val.y, val.z, -val.x);
 }
References Vector3::x, Vector3::y, and Vector3::z.
Referenced by Geometry::AddData(), and WorldModelHandler::InsertModelGeometry().
ToString()
template<typename T > static std::string Utils::ToString (T val) inline static
They say its better to declare template functions in the header files.
Definition at line 375 of file Utils.h.
     {
         std::stringstream ss;
         ss << val;
         return ss.str();
     }
Referenced by GetAdtPath().
ToWoWCoords()
Vector3 Utils::ToWoWCoords (const Vector3 & vec) static
Definition at line 227 of file Utils.cpp.
 {
     return Vector3(-vec.z, -vec.x, vec.y);
 }
References vec::x, vec::y, and vec::z.
Referenced by main(), and Model::ReadVertices().
TransformDoodadVertex()
Vector3 Utils::TransformDoodadVertex (const IDefinition & def, Vector3 & vec, bool translate = true) static
http://www.pxr.dk/wowdev/wiki/index.php?title=ADT/v18&oldid=3715
Definition at line 107 of file Utils.cpp.
 {
     // Sources of information:
     // This function applies to both external doodads and WMOs
     // Rotate our Doodad vertex
     G3D::Matrix4 rot = G3D::Matrix3::fromEulerAnglesXYZ(Utils::ToRadians(def.Rotation.z), Utils::ToRadians(-def.Rotation.x), Utils::ToRadians(def.Rotation.y + 180));
     Vector3 ret = Utils::VectorTransform(vec, rot);
     // And finally scale and translate it to our origin
     ret = ret * def.Scale();
     if (translate)
         ret = ret + Vector3(Constants::MaxXY - def.Position.z, Constants::MaxXY - def.Position.x, def.Position.y);
     return ret;
 }
References Constants::MaxXY, IDefinition::Position, IDefinition::Rotation, IDefinition::Scale(), ToRadians(), VectorTransform(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by GetLiquidVert(), DoodadHandler::InsertModelGeometry(), and WorldModelHandler::InsertModelGeometry().
TransformWmoDoodad()
Vector3 Utils::TransformWmoDoodad (const DoodadInstance & inst, const WorldModelDefinition & root, Vector3 & vec, bool translate = true) static
Definition at line 125 of file Utils.cpp.
 {
     G3D::Quat quat = G3D::Quat(-inst.QuatY, inst.QuatZ, -inst.QuatX, inst.QuatW);
     Vector3 ret = Utils::VectorTransform(vec, G3D::Matrix4(quat.toRotationMatrix()));
     ret = ret * (inst.Scale / 1024.0f);
     if (translate)
         ret = ret + Vector3(Constants::MaxXY - inst.Position.z, Constants::MaxXY - inst.Position.x, inst.Position.y);
     return ret;
 }
References Constants::MaxXY, DoodadInstance::Position, DoodadInstance::QuatW, DoodadInstance::QuatX, DoodadInstance::QuatY, DoodadInstance::QuatZ, DoodadInstance::Scale, VectorTransform(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by WorldModelHandler::InsertModelGeometry().
VectorTransform()
Vector3 Utils::VectorTransform (const Vector3 & vec, const G3D::Matrix4 & matrix, bool normal = false) static
Definition at line 141 of file Utils.cpp.
 {
     G3D::Vector3 ret(vec.x, vec.y, vec.z);
     ret = matrix.homoMul(ret, normal ? 0 : 1);
     return Vector3(ret.x, ret.y, ret.z);
 }
References vec::x, vec::y, and vec::z.
Referenced by TransformDoodadVertex(), and TransformWmoDoodad().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp