Azerotcore-wotlk: npc_roxi_ramrocket Class Reference
npc_roxi_ramrocket Class Reference
Public Member Functions
npc_roxi_ramrocket ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 708 of file zone_storm_peaks.cpp.
Constructor & Destructor Documentation
npc_roxi_ramrocket()
npc_roxi_ramrocket::npc_roxi_ramrocket () inline
Definition at line 711 of file zone_storm_peaks.cpp.
 : CreatureScript("npc_roxi_ramrocket") { }
Member Function Documentation
OnGossipHello()
bool npc_roxi_ramrocket::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 713 of file zone_storm_peaks.cpp.
     {
         //Quest Menu
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         //Trainer Menu
         if ( creature->IsTrainer() )
             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRAIN);
         //Vendor Menu
         if ( creature->IsVendor() )
             if (player->HasSpell(SPELL_MECHANO_HOG) || player->HasSpell(SPELL_MEKGINEERS_CHOPPER))
                 AddGossipItemFor(player, GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, GOSSIP_ICON_TRAINER, GOSSIP_ICON_VENDOR, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_TEXT_TRAIN, Player::HasSpell(), Unit::IsQuestGiver(), Unit::IsTrainer(), Unit::IsVendor(), Player::PrepareQuestMenu(), SendGossipMenuFor(), SPELL_MECHANO_HOG, and SPELL_MEKGINEERS_CHOPPER.
OnGossipSelect()
bool npc_roxi_ramrocket::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 732 of file zone_storm_peaks.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_TRAIN:
                 player->GetSession()->SendTrainerList(creature->GetGUID());
                 break;
             case GOSSIP_ACTION_TRADE:
                 player->GetSession()->SendListInventory(creature->GetGUID());
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, WorldSession::SendListInventory(), and WorldSession::SendTrainerList().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_storm_peaks.cpp