Azerotcore-wotlk: deps/zlib/uncompr.c File Reference
uncompr.c File Reference
#include "zlib.h"
Macros
#define ZLIB_INTERNAL
Functions
int ZEXPORT uncompress (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen)
Macro Definition Documentation
ZLIB_INTERNAL
#define ZLIB_INTERNAL
Definition at line 8 of file uncompr.c.
Function Documentation
uncompress()
int ZEXPORT uncompress (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen)
Definition at line 24 of file uncompr.c.
 {
     z_stream stream;
     int err;
     stream.next_in = (Bytef*)source;
     stream.avail_in = (uInt)sourceLen;
     /* Check for source > 64K on 16-bit machine: */
     if ((uLong)stream.avail_in != sourceLen) return Z_BUF_ERROR;
     stream.next_out = dest;
     stream.avail_out = (uInt)*destLen;
     if ((uLong)stream.avail_out != *destLen) return Z_BUF_ERROR;
     stream.zalloc = (alloc_func)0;
     stream.zfree = (free_func)0;
     err = inflateInit(&stream);
     if (err != Z_OK) return err;
     err = inflate(&stream, Z_FINISH);
     if (err != Z_STREAM_END) {
         inflateEnd(&stream);
         if (err == Z_NEED_DICT || (err == Z_BUF_ERROR && stream.avail_in == 0))
             return Z_DATA_ERROR;
         return err;
     }
     *destLen = stream.total_out;
     err = inflateEnd(&stream);
     return err;
 }
References z_stream_s::avail_in, z_stream_s::avail_out, inflate(), inflateEnd(), inflateInit, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::total_out, Z_BUF_ERROR, Z_DATA_ERROR, Z_FINISH, Z_NEED_DICT, Z_OK, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by G3D::BinaryInput::BinaryInput(), AddonHandler::BuildAddonPacket(), G3D::BinaryInput::decompress(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleUpdateAccountData(), WorldSession::ReadAddonsInfo(), and test_compress().