Azerotcore-wotlk: npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI Struct Reference
npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI Struct Reference
Public Member Functions
npc_brann_bronzebeard_algalonAI (Creature *creature)
void DoAction (int32 action) override
void MovementInform (uint32 movementType, uint32 pointId) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
uint32 _currentPoint
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 818 of file boss_algalon_the_observer.cpp.
Constructor & Destructor Documentation
npc_brann_bronzebeard_algalonAI()
npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::npc_brann_bronzebeard_algalonAI (Creature * creature) inline
Definition at line 820 of file boss_algalon_the_observer.cpp.
                                                             : CreatureAI(creature)
         {
         }
Member Function Documentation
DoAction()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 827 of file boss_algalon_the_observer.cpp.
         {
             switch (action)
             {
                 case ACTION_START_INTRO:
                     me->SetWalk(false);
                     _currentPoint = 0;
                     events.Reset();
                     events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, 1);
                     break;
                 case ACTION_FINISH_INTRO:
                     Talk(SAY_BRANN_ALGALON_INTRO_2);
                     events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, 1);
                     break;
                 case ACTION_OUTRO:
                     me->GetMotionMaster()->MovePoint(POINT_BRANN_OUTRO, BrannOutroPos[1]);
                     events.ScheduleEvent(EVENT_BRANN_OUTRO_1, 87500);
                     events.ScheduleEvent(EVENT_BRANN_OUTRO_2, 116500);
                     break;
             }
         }
References _currentPoint, ACTION_FINISH_INTRO, ACTION_OUTRO, ACTION_START_INTRO, BrannOutroPos, EVENT_BRANN_MOVE_INTRO, EVENT_BRANN_OUTRO_1, EVENT_BRANN_OUTRO_2, Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MovePoint(), POINT_BRANN_OUTRO, SAY_BRANN_ALGALON_INTRO_2, Creature::SetWalk(), and CreatureAI::Talk().
MovementInform()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform (uint32 movementType, uint32 pointId) inline override virtual
Reimplemented from CreatureAI.
Definition at line 849 of file boss_algalon_the_observer.cpp.
         {
             if (movementType != POINT_MOTION_TYPE)
                 return;
             uint32 delay = 1;
             _currentPoint = pointId + 1;
             switch (pointId)
             {
                 case 2:
                     delay = 8000;
                     me->SetWalk(true);
                     break;
                 case 6:
                     me->SetFacingTo(4.6156f);
                     me->SetWalk(false);
                     Talk(SAY_BRANN_ALGALON_INTRO_1);
                     events.ScheduleEvent(EVENT_SUMMON_ALGALON, 7500);
                     return;
                 case 10:
                     me->DespawnOrUnsummon(1);
                     return;
                 case POINT_BRANN_OUTRO:
                 case POINT_BRANN_OUTRO_END:
                     return;
             }
             events.ScheduleEvent(EVENT_BRANN_MOVE_INTRO, delay);
         }
References _currentPoint, Creature::DespawnOrUnsummon(), EVENT_BRANN_MOVE_INTRO, EVENT_SUMMON_ALGALON, CreatureAI::me, POINT_BRANN_OUTRO, POINT_BRANN_OUTRO_END, POINT_MOTION_TYPE, SAY_BRANN_ALGALON_INTRO_1, Unit::SetFacingTo(), Creature::SetWalk(), and CreatureAI::Talk().
UpdateAI()
void npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI (uint32 diff) inline override virtual
Implements UnitAI.
Definition at line 879 of file boss_algalon_the_observer.cpp.
         {
             UpdateVictim();
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_BRANN_MOVE_INTRO:
                     if (_currentPoint < MAX_BRANN_WAYPOINTS_INTRO)
                         me->GetMotionMaster()->MovePoint(_currentPoint, BrannIntroWaypoint[_currentPoint]);
                     break;
                 case EVENT_SUMMON_ALGALON:
                     if (me->GetInstanceScript() && !me->GetInstanceScript()->GetGuidData(TYPE_ALGALON))
                         if (Creature* algalon = me->GetMap()->SummonCreature(NPC_ALGALON, AlgalonSummonPos))
                             algalon->AI()->DoAction(ACTION_START_INTRO);
                     break;
                 case EVENT_BRANN_OUTRO_1:
                     Talk(SAY_BRANN_ALGALON_OUTRO);
                     break;
                 case EVENT_BRANN_OUTRO_2:
                     me->GetMotionMaster()->MovePoint(POINT_BRANN_OUTRO_END, BrannOutroPos[2]);
                     break;
             }
         }
References _currentPoint, ACTION_START_INTRO, AlgalonSummonPos, BrannIntroWaypoint, BrannOutroPos, EVENT_BRANN_MOVE_INTRO, EVENT_BRANN_OUTRO_1, EVENT_BRANN_OUTRO_2, EVENT_SUMMON_ALGALON, InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Unit::GetMotionMaster(), MAX_BRANN_WAYPOINTS_INTRO, CreatureAI::me, MotionMaster::MovePoint(), NPC_ALGALON, POINT_BRANN_OUTRO_END, SAY_BRANN_ALGALON_OUTRO, Map::SummonCreature(), CreatureAI::Talk(), TYPE_ALGALON, and CreatureAI::UpdateVictim().
Member Data Documentation
_currentPoint
uint32 npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::_currentPoint
Definition at line 825 of file boss_algalon_the_observer.cpp.
Referenced by DoAction(), MovementInform(), and UpdateAI().
events
EventMap npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::events
Definition at line 824 of file boss_algalon_the_observer.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp