Azerotcore-wotlk: EoEDrakeEnterVehicleEvent Class Reference
EoEDrakeEnterVehicleEvent Class Reference
#include <eye_of_eternity.h>
Public Member Functions
EoEDrakeEnterVehicleEvent (Creature &owner, ObjectGuid playerGUID)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
ObjectGuid _playerGUID
Detailed Description
Definition at line 109 of file eye_of_eternity.h.
Constructor & Destructor Documentation
EoEDrakeEnterVehicleEvent()
EoEDrakeEnterVehicleEvent::EoEDrakeEnterVehicleEvent (Creature & owner, ObjectGuid playerGUID) inline
Definition at line 112 of file eye_of_eternity.h.
 : _owner(owner), _playerGUID(playerGUID) { }
Member Function Documentation
Execute()
bool EoEDrakeEnterVehicleEvent::Execute (uint64 , uint32) override virtual
Reimplemented from BasicEvent.
Definition at line 24 of file instance_eye_of_eternity.cpp.
 {
     if (Player* p = ObjectAccessor::GetPlayer(_owner, _playerGUID))
         if (p->IsInWorld() && !p->IsDuringRemoveFromWorld() && !p->isBeingLoaded() && p->FindMap() == _owner.FindMap())
         {
             p->CastCustomSpell(60683, SPELLVALUE_BASE_POINT0, 1, &_owner, true);
             return true;
         }
     _owner.DespawnOrUnsummon(1);
     return true;
 }
References _owner, _playerGUID, Creature::DespawnOrUnsummon(), WorldObject::FindMap(), ObjectAccessor::GetPlayer(), and SPELLVALUE_BASE_POINT0.
Member Data Documentation
_owner
Creature& EoEDrakeEnterVehicleEvent::_owner private
Definition at line 115 of file eye_of_eternity.h.
Referenced by Execute().
_playerGUID
ObjectGuid EoEDrakeEnterVehicleEvent::_playerGUID private
Definition at line 116 of file eye_of_eternity.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/scripts/Northrend/Nexus/EyeOfEternity/eye_of_eternity.h
src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp