Azerotcore-wotlk: G3D::Triangle Class Reference
G3D::Triangle Class Reference
#include <Triangle.h>
Public Member Functions
Triangle (class BinaryInput &b)
void serialize (class BinaryOutput &b)
void deserialize (class BinaryInput &b)
Triangle ()
Triangle (const Point3 &v0, const Point3 &v1, const Point3 &v2)
~Triangle ()
const Point3 & vertex (int n) const
const Vector3 & edge01 () const
const Vector3 & edge02 () const
float area () const
Vector3::Axis primaryAxis () const
const Vector3 & normal () const
Point3 center () const
const Plane & plane () const
Point3 randomPoint () const
void getRandomSurfacePoint (Point3 &P, Vector3 &N=Vector3::ignore()) const
bool operator== (const Triangle &other) const
size_t hashCode () const
void getBounds (class AABox &) const
bool intersect (const class Ray &ray, float &distance, float baryCoord[3]) const
Intersect the ray at distance less than distance.
Private Member Functions
void init (const Vector3 &v0, const Vector3 &v1, const Vector3 &v2)
Private Attributes
Vector3 _vertex [3]
Vector3 edgeDirection [3]
float edgeMagnitude [3]
Plane _plane
Vector3::Axis _primaryAxis
Vector3 _edge01
Vector3 _edge02
float _area
Friends
class CollisionDetection
class Ray
Detailed Description
A generic triangle representation. This should not be used as the underlying triangle for creating models; it is intended for providing fast property queries but requires a lot of storage and is mostly immutable.
Definition at line 34 of file Triangle.h.
Constructor & Destructor Documentation
Triangle() [1/3]
Triangle< T >::Triangle (class BinaryInput & b)
Definition at line 68 of file Triangle.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Triangle() [2/3]
Triangle< T >::Triangle ()
Definition at line 54 of file Triangle.cpp.
                    {
     init(Vector3::zero(), Vector3::zero(), Vector3::zero());
 }
References init(), and G3D::Vector3::zero().
Triangle() [3/3]
Triangle< T >::Triangle (const Point3 & v0, const Point3 & v1, const Point3 & v2)
Definition at line 59 of file Triangle.cpp.
{
     init(v0, v1, v2);
 }
References init().
~Triangle()
Triangle< T >::~Triangle ()
Definition at line 64 of file Triangle.cpp.
                     {
 }
Member Function Documentation
area()
float Triangle< T >::area () const
Definition at line 88 of file Triangle.cpp.
{
     return _area;
 }
References _area.
center()
Vector3 Triangle< T >::center () const
Barycenter
Definition at line 103 of file Triangle.cpp.
{
     return (_vertex[0] + _vertex[1] + _vertex[2]) / 3.0;
 }
References _vertex.
deserialize()
void Triangle< T >::deserialize (class BinaryInput & b)
Definition at line 80 of file Triangle.cpp.
{
     _vertex[0].deserialize(b);
     _vertex[1].deserialize(b);
     _vertex[2].deserialize(b);
     init(_vertex[0], _vertex[1], _vertex[2]);
 }
References _vertex, b, G3D::Vector3::deserialize(), and init().
Referenced by Triangle().
edge01()
const Vector3& G3D::Triangle::edge01 () const inline
vertex[1] - vertex[0]
Definition at line 76 of file Triangle.h.
{
         return _edge01;
     }
References _edge01.
Referenced by intersect().
edge02()
const Vector3& G3D::Triangle::edge02 () const inline
vertex[2] - vertex[0]
Definition at line 81 of file Triangle.h.
{
         return _edge02;
     }
References _edge02.
Referenced by intersect().
getBounds()
void Triangle< T >::getBounds (class AABox & out) const
Definition at line 124 of file Triangle.cpp.
{
     Vector3 lo = _vertex[0];
     Vector3 hi = lo;
     for (int i = 1; i < 3; ++i) {
         lo = lo.min(_vertex[i]);
         hi = hi.max(_vertex[i]);
     }
     out = AABox(lo, hi);
 }
References _vertex, G3D::Vector3::max(), and G3D::Vector3::min().
Referenced by BoundsTrait< class G3D::Triangle >::getBounds(), and BoundsTrait< class G3D::Triangle * >::getBounds().
getRandomSurfacePoint()
void G3D::Triangle::getRandomSurfacePoint (Point3 & P, Vector3 & N = Vector3::ignore()) const inline
Definition at line 101 of file Triangle.h.
{
         P = randomPoint();
         N = normal();
     }
References normal(), P, and randomPoint().
hashCode()
size_t G3D::Triangle::hashCode () const inline
Definition at line 123 of file Triangle.h.
{
         return
             _vertex[0].hashCode() +
             (_vertex[1].hashCode() >> 2) +
             (_vertex[2].hashCode() >> 3);
     }
References _vertex, and G3D::Vector3::hashCode().
Referenced by HashTrait< G3D::Triangle >::hashCode().
init()
void Triangle< T >::init (const Vector3 & v0, const Vector3 & v1, const Vector3 & v2) private
Definition at line 25 of file Triangle.cpp.
{
     _plane = Plane(v0, v1, v2);
     _vertex[0] = v0;
     _vertex[1] = v1;
     _vertex[2] = v2;
     static int next[] = {1,2,0};
     for (int i = 0; i < 3; ++i) {
         const Vector3& e  = _vertex[next[i]] - _vertex[i];
         edgeMagnitude[i]  = e.magnitude();
         if (edgeMagnitude[i] == 0) {
             edgeDirection[i] = Vector3::zero();
         } else {
             edgeDirection[i] = e / (float)edgeMagnitude[i];
         }
     }
     _edge01 = _vertex[1] - _vertex[0];
     _edge02 = _vertex[2] - _vertex[0];
     _primaryAxis = _plane.normal().primaryAxis();
     _area = 0.5f * edgeDirection[0].cross(edgeDirection[2]).magnitude() * (edgeMagnitude[0] * edgeMagnitude[2]);
         //0.5f * (_vertex[1] - _vertex[0]).cross(_vertex[2] - _vertex[0]).dot(_plane.normal());
 }
References _area, _edge01, _edge02, _plane, _primaryAxis, _vertex, G3D::Vector3::cross(), edgeDirection, edgeMagnitude, G3D::Vector3::magnitude(), next(), G3D::Plane::normal(), G3D::Vector3::primaryAxis(), and G3D::Vector3::zero().
Referenced by deserialize(), and Triangle().
intersect()
bool Triangle< T >::intersect (const class Ray & ray, float & distance, float baryCoord[3]) const
Intersect the ray at distance less than distance.
Parameters
distance Set to the maximum distance (can be G3D::inf()) to search for an intersection. On return, this is the smaller of the distance to the intersection, if one exists, and the original value.
baryCoord If a triangle is hit before distance, a the barycentric coordinates of the hit location on the triangle. Otherwise, unmodified.
Returns
True if there was an intersection before the original distance.
Definition at line 137 of file Triangle.cpp.
{
     static const float EPS = 1e-5f;
     // See RTR2 ch. 13.7 for the algorithm.
     const Vector3& e1 = edge01();
     const Vector3& e2 = edge02();
     const Vector3 p(ray.direction().cross(e2));
     const float a = e1.dot(p);
     if (abs(a) < EPS) {
         // Determinant is ill-conditioned; abort early
         return false;
     }
     const float f = 1.0f / a;
     const Vector3 s(ray.origin() - vertex(0));
     const float u = f * s.dot(p);
     if ((u < 0.0f) || (u > 1.0f)) {
         // We hit the plane of the m_geometry, but outside the m_geometry
         return false;
     }
     const Vector3 q(s.cross(e1));
     const float v = f * ray.direction().dot(q);
     if ((v < 0.0f) || ((u + v) > 1.0f)) {
         // We hit the plane of the triangle, but outside the triangle
         return false;
     }
     const float t = f * e2.dot(q);
     if ((t > 0.0f) && (t < distance)) {
         // This is a new hit, closer than the previous one
         distance = t;
         baryCoord[0] = 1.0f - u - v;
         baryCoord[1] = u;
         baryCoord[2] = v;
         return true;
     } else {
         // This hit is after the previous hit, so ignore it
         return false;
     }
 }
References mpq::a, G3D::abs(), G3D::Vector3::cross(), G3D::Ray::direction(), G3D::distance(), G3D::Vector3::dot(), edge01(), edge02(), f(), G3D::Ray::origin(), and vertex().
normal()
const Vector3 & Triangle< T >::normal () const
Definition at line 93 of file Triangle.cpp.
{
     return _plane.normal();
 }
References _plane, and G3D::Plane::normal().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedTriangle(), G3D::CollisionDetection::fixedSolidBoxIntersectsFixedTriangle(), and getRandomSurfacePoint().
operator==()
bool G3D::Triangle::operator== (const Triangle & other) const inline
For two triangles to be equal they must have the same vertices in the same order. That is, vertex[0] == vertex[0], etc.
Definition at line 113 of file Triangle.h.
{
         for (int i = 0; i < 3; ++i) {
             if (_vertex[i] != other._vertex[i]) {
                 return false;
             }
         }
         return true;
     }
References _vertex.
plane()
const Plane & Triangle< T >::plane () const
Definition at line 98 of file Triangle.cpp.
{
     return _plane;
 }
References _plane.
primaryAxis()
Vector3::Axis G3D::Triangle::primaryAxis () const inline
Definition at line 87 of file Triangle.h.
{
         return _primaryAxis;
     }
References _primaryAxis.
randomPoint()
Vector3 Triangle< T >::randomPoint () const
Returns a random point in the triangle.
Definition at line 107 of file Triangle.cpp.
{
     // Choose a random point in the parallelogram
     float s = uniformRandom();
     float t = uniformRandom();
     if (t > 1.0f - s) {
         // Outside the triangle; reflect about the
         // diagonal of the parallelogram
         t = 1.0f - t;
         s = 1.0f - s;
     }
     return _edge01 * s + _edge02 * t + _vertex[0];
 }
References _edge01, _edge02, _vertex, and G3D::uniformRandom().
Referenced by getRandomSurfacePoint().
serialize()
void Triangle< T >::serialize (class BinaryOutput & b)
Definition at line 73 of file Triangle.cpp.
{
     _vertex[0].serialize(b);
     _vertex[1].serialize(b);
     _vertex[2].serialize(b);
 }
References _vertex, b, and G3D::Vector3::serialize().
vertex()
const Point3& G3D::Triangle::vertex (int n) const inline
0, 1, or 2
Definition at line 70 of file Triangle.h.
{
         debugAssert((n >= 0) && (n < 3));
         return _vertex[n];
     }
References _vertex, and debugAssert.
Referenced by G3D::MeshBuilder::addTriangle(), G3D::CollisionDetection::collisionTimeForMovingPointFixedTriangle(), G3D::CollisionDetection::fixedSolidBoxIntersectsFixedTriangle(), intersect(), and G3D::CoordinateFrame::toObjectSpace().
Friends And Related Function Documentation
CollisionDetection
friend class CollisionDetection friend
Definition at line 36 of file Triangle.h.
Ray
friend class Ray friend
Definition at line 37 of file Triangle.h.
Member Data Documentation
_area
float G3D::Triangle::_area private
Definition at line 53 of file Triangle.h.
Referenced by area(), and init().
_edge01
Vector3 G3D::Triangle::_edge01 private
vertex[1] - vertex[0]
Definition at line 48 of file Triangle.h.
Referenced by edge01(), init(), and randomPoint().
_edge02
Vector3 G3D::Triangle::_edge02 private
vertex[2] - vertex[0]
Definition at line 51 of file Triangle.h.
Referenced by edge02(), init(), and randomPoint().
_plane
Plane G3D::Triangle::_plane private
Definition at line 44 of file Triangle.h.
Referenced by init(), normal(), and plane().
_primaryAxis
Vector3::Axis G3D::Triangle::_primaryAxis private
Definition at line 45 of file Triangle.h.
Referenced by init(), and primaryAxis().
_vertex
Vector3 G3D::Triangle::_vertex[3] private
Definition at line 39 of file Triangle.h.
Referenced by center(), deserialize(), getBounds(), hashCode(), init(), operator==(), randomPoint(), serialize(), and vertex().
edgeDirection
Vector3 G3D::Triangle::edgeDirection[3] private
edgeDirection[i] is the normalized vector v[i+1] - v[i]
Definition at line 42 of file Triangle.h.
Referenced by init().
edgeMagnitude
float G3D::Triangle::edgeMagnitude[3] private
Definition at line 43 of file Triangle.h.
Referenced by init().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Triangle.h
deps/g3dlite/source/Triangle.cpp