Azerotcore-wotlk: achievement_resilient_victory Class Reference
achievement_resilient_victory Class Reference
Public Member Functions
achievement_resilient_victory ()
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 28 of file achievement_scripts.cpp.
Constructor & Destructor Documentation
achievement_resilient_victory()
achievement_resilient_victory::achievement_resilient_victory () inline
Definition at line 31 of file achievement_scripts.cpp.
 : AchievementCriteriaScript("achievement_resilient_victory") { }
Member Function Documentation
OnCheck()
bool achievement_resilient_victory::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 33 of file achievement_scripts.cpp.
     {
         Battleground* bg = source->GetBattleground();
         return bg && bg->GetBgTypeID(true) == BATTLEGROUND_AB && bg->ToBattlegroundAB()->IsTeamScores500Disadvantage(source->GetTeamId());
     }
References BATTLEGROUND_AB, bg(), Player::GetBattleground(), and Player::GetTeamId().
The documentation for this class was generated from the following file:
src/server/scripts/World/achievement_scripts.cpp