Azerotcore-wotlk: Guild::Member Class Reference
Guild::Member Class Reference
#include <Guild.h>
Public Member Functions
Member (uint32 guildId, ObjectGuid guid, uint8 rankId)
void SetStats (Player *player)
void SetStats (std::string const &name, uint8 level, uint8 _class, uint8 gender, uint32 zoneId, uint32 accountId)
bool CheckStats () const
void SetPublicNote (std::string const &publicNote)
void SetOfficerNote (std::string const &officerNote)
void SetZoneID (uint32 id)
void SetLevel (uint8 var)
void AddFlag (uint8 var)
void RemFlag (uint8 var)
void ResetFlags ()
bool LoadFromDB (Field *fields)
void SaveToDB (CharacterDatabaseTransaction trans) const
void WritePacket (WorldPacket &data, bool sendOfficerNote) const
ObjectGuid GetGUID () const
std::string const & GetName () const
uint32 GetAccountId () const
uint8 GetRankId () const
uint64 GetLogoutTime () const
std::string GetPublicNote () const
std::string GetOfficerNote () const
uint8 GetClass () const
uint8 GetLevel () const
uint8 GetGender () const
uint8 GetFlags () const
uint32 GetZoneId () const
bool IsOnline ()
void ChangeRank (uint8 newRank)
void UpdateLogoutTime ()
bool IsRank (uint8 rankId) const
bool IsRankNotLower (uint8 rankId) const
bool IsSamePlayer (ObjectGuid guid) const
void UpdateBankWithdrawValue (CharacterDatabaseTransaction trans, uint8 tabId, uint32 amount)
int32 GetBankWithdrawValue (uint8 tabId) const
void ResetValues ()
Player * FindPlayer () const
Private Attributes
uint32 m_guildId
ObjectGuid m_guid
std::string m_name
uint32 m_zoneId
uint8 m_level
uint8 m_class
uint8 m_gender
uint8 m_flags
uint64 m_logoutTime
uint32 m_accountId
uint8 m_rankId
std::string m_publicNote
std::string m_officerNote
int32 m_bankWithdraw [GUILD_BANK_MAX_TABS+1]
Detailed Description
Definition at line 285 of file Guild.h.
Constructor & Destructor Documentation
Member()
Guild::Member::Member (uint32 guildId, ObjectGuid guid, uint8 rankId) inline
Definition at line 288 of file Guild.h.
                                                              :
             m_guildId(guildId),
             m_guid(guid),
             m_zoneId(0),
             m_level(0),
             m_class(0),
             m_flags(GUILDMEMBER_STATUS_NONE),
             m_logoutTime(::time(nullptr)),
             m_accountId(0),
             m_rankId(rankId)
         {
             memset(m_bankWithdraw, 0, (GUILD_BANK_MAX_TABS + 1) * sizeof(int32));
         }
References GUILD_BANK_MAX_TABS, and m_bankWithdraw.
Member Function Documentation
AddFlag()
void Guild::Member::AddFlag (uint8 var) inline
Definition at line 311 of file Guild.h.
 { m_flags |= var; }
References m_flags.
ChangeRank()
void Guild::Member::ChangeRank (uint8 newRank)
Definition at line 638 of file Guild.cpp.
 {
     m_rankId = newRank;
     // Update rank information in player's field, if he is online.
     if (Player* player = FindPlayer())
         player->SetRank(newRank);
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_RANK);
     stmt->setUInt8 (0, newRank);
     stmt->setUInt32(1, m_guid.GetCounter());
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_MEMBER_RANK, CharacterDatabase, ObjectAccessor::FindPlayer(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::_SetLeaderGUID().
CheckStats()
bool Guild::Member::CheckStats () const
Definition at line 695 of file Guild.cpp.
 {
     if (m_level < 1)
     {
         LOG_ERROR("guild", "Player (%s) has a broken data in field `characters`.`level`, deleting him from guild!", m_guid.ToString().c_str());
         return false;
     }
     if (m_class < CLASS_WARRIOR || m_class >= MAX_CLASSES)
     {
         LOG_ERROR("guild", "Player (%s) has a broken data in field `characters`.`class`, deleting him from guild!", m_guid.ToString().c_str());
         return false;
     }
     return true;
 }
References LOG_ERROR, and MAX_CLASSES.
Referenced by Guild::AddMember().
FindPlayer()
Player* Guild::Member::FindPlayer () const inline
Definition at line 344 of file Guild.h.
 { return ObjectAccessor::FindConnectedPlayer(m_guid); }
References ObjectAccessor::FindConnectedPlayer(), and m_guid.
Referenced by Guild::DeleteMember().
GetAccountId()
uint32 Guild::Member::GetAccountId () const inline
Definition at line 321 of file Guild.h.
 { return m_accountId; }
References m_accountId.
GetBankWithdrawValue()
int32 Guild::Member::GetBankWithdrawValue (uint8 tabId) const
Definition at line 760 of file Guild.cpp.
 {
     // Guild master has unlimited amount.
     if (IsRank(GR_GUILDMASTER))
         return tabId == GUILD_BANK_MAX_TABS ? GUILD_WITHDRAW_MONEY_UNLIMITED : GUILD_WITHDRAW_SLOT_UNLIMITED;
     return m_bankWithdraw[tabId];
 }
References GR_GUILDMASTER, GUILD_BANK_MAX_TABS, GUILD_WITHDRAW_MONEY_UNLIMITED, and GUILD_WITHDRAW_SLOT_UNLIMITED.
Referenced by Guild::_GetMemberRemainingMoney(), and Guild::_GetMemberRemainingSlots().
GetClass()
uint8 Guild::Member::GetClass () const inline
Definition at line 326 of file Guild.h.
 { return m_class; }
References m_class.
GetFlags()
uint8 Guild::Member::GetFlags () const inline
Definition at line 329 of file Guild.h.
 { return m_flags; }
References m_flags.
GetGender()
uint8 Guild::Member::GetGender () const inline
Definition at line 328 of file Guild.h.
 { return m_gender; }
References m_gender.
GetGUID()
ObjectGuid Guild::Member::GetGUID () const inline
Definition at line 319 of file Guild.h.
 { return m_guid; }
References m_guid.
Referenced by Guild::_SetLeaderGUID(), and Guild::MassInviteToEvent().
GetLevel()
uint8 Guild::Member::GetLevel () const inline
Definition at line 327 of file Guild.h.
 { return m_level; }
References m_level.
GetLogoutTime()
uint64 Guild::Member::GetLogoutTime () const inline
Definition at line 323 of file Guild.h.
 { return m_logoutTime; }
References m_logoutTime.
GetName()
std::string const& Guild::Member::GetName () const inline
Definition at line 320 of file Guild.h.
 { return m_name; }
References m_name.
Referenced by Guild::DeleteMember().
GetOfficerNote()
std::string Guild::Member::GetOfficerNote () const inline
Definition at line 325 of file Guild.h.
 { return m_officerNote; }
References m_officerNote.
GetPublicNote()
std::string Guild::Member::GetPublicNote () const inline
Definition at line 324 of file Guild.h.
 { return m_publicNote; }
References m_publicNote.
GetRankId()
uint8 Guild::Member::GetRankId () const inline
Definition at line 322 of file Guild.h.
 { return m_rankId; }
References m_rankId.
Referenced by Guild::_GetMemberRemainingMoney(), Guild::_GetMemberRemainingSlots(), Guild::DeleteMember(), WorldSession::HandlePlayerLoginFromDB(), Guild::HandleRemoveMember(), Guild::HandleUpdateMemberRank(), and Guild::SendPermissions().
GetZoneId()
uint32 Guild::Member::GetZoneId () const inline
Definition at line 330 of file Guild.h.
 { return m_zoneId; }
References m_zoneId.
IsOnline()
bool Guild::Member::IsOnline () inline
Definition at line 331 of file Guild.h.
 { return (m_flags & GUILDMEMBER_STATUS_ONLINE); }
References GUILDMEMBER_STATUS_ONLINE, and m_flags.
IsRank()
bool Guild::Member::IsRank (uint8 rankId) const inline
Definition at line 336 of file Guild.h.
 { return m_rankId == rankId; }
References m_rankId.
Referenced by Guild::Validate().
IsRankNotLower()
bool Guild::Member::IsRankNotLower (uint8 rankId) const inline
Definition at line 337 of file Guild.h.
 { return m_rankId <= rankId; }
References m_rankId.
Referenced by Guild::HandleRemoveMember().
IsSamePlayer()
bool Guild::Member::IsSamePlayer (ObjectGuid guid) const inline
Definition at line 338 of file Guild.h.
 { return m_guid == guid; }
References m_guid.
LoadFromDB()
bool Guild::Member::LoadFromDB (Field * fields)
Definition at line 666 of file Guild.cpp.
 {
     m_publicNote  = fields[3].GetString();
     m_officerNote = fields[4].GetString();
     for (uint8 i = 0; i <= GUILD_BANK_MAX_TABS; ++i)
         m_bankWithdraw[i] = fields[5 + i].GetUInt32();
     SetStats(fields[12].GetString(),
              fields[13].GetUInt8(),                         // characters.level
              fields[14].GetUInt8(),                         // characters.class
              fields[15].GetUInt8(),                         // characters.gender
              fields[16].GetUInt16(),                        // characters.zone
              fields[17].GetUInt32());                       // characters.account
     m_logoutTime = fields[18].GetUInt32();                  // characters.logout_time
     if (!CheckStats())
         return false;
     if (!m_zoneId)
     {
         LOG_ERROR("guild", "Player (%s) has broken zone-data", m_guid.ToString().c_str());
         m_zoneId = Player::GetZoneIdFromDB(m_guid);
     }
     ResetFlags();
     return true;
 }
References Field::GetString(), Field::GetUInt32(), Player::GetZoneIdFromDB(), GUILD_BANK_MAX_TABS, and LOG_ERROR.
Referenced by Guild::LoadMemberFromDB().
RemFlag()
void Guild::Member::RemFlag (uint8 var) inline
Definition at line 312 of file Guild.h.
 { m_flags &= ~var; }
References m_flags.
ResetFlags()
void Guild::Member::ResetFlags () inline
Definition at line 313 of file Guild.h.
 { m_flags = GUILDMEMBER_STATUS_NONE; }
References GUILDMEMBER_STATUS_NONE, and m_flags.
Referenced by Guild::AddMember().
ResetValues()
void Guild::Member::ResetValues ()
Definition at line 751 of file Guild.cpp.
 {
     for (uint8 tabId = 0; tabId <= GUILD_BANK_MAX_TABS; ++tabId)
         m_bankWithdraw[tabId] = 0;
 }
References GUILD_BANK_MAX_TABS.
SaveToDB()
void Guild::Member::SaveToDB (CharacterDatabaseTransaction trans) const
Definition at line 652 of file Guild.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_MEMBER);
     stmt->setUInt32(0, m_guildId);
     stmt->setUInt32(1, m_guid.GetCounter());
     stmt->setUInt8 (2, m_rankId);
     stmt->setString(3, m_publicNote);
     stmt->setString(4, m_officerNote);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References CHAR_INS_GUILD_MEMBER, CharacterDatabase, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Guild::AddMember().
SetLevel()
void Guild::Member::SetLevel (uint8 var) inline
Definition at line 309 of file Guild.h.
 { m_level = var; }
References m_level.
SetOfficerNote()
void Guild::Member::SetOfficerNote (std::string const & officerNote)
Definition at line 625 of file Guild.cpp.
 {
     if (m_officerNote == officerNote)
         return;
     m_officerNote = officerNote;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_OFFNOTE);
     stmt->setString(0, officerNote);
     stmt->setUInt32(1, m_guid.GetCounter());
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_MEMBER_OFFNOTE, CharacterDatabase, PreparedStatementBase::setString(), and PreparedStatementBase::setUInt32().
SetPublicNote()
void Guild::Member::SetPublicNote (std::string const & publicNote)
Definition at line 612 of file Guild.cpp.
 {
     if (m_publicNote == publicNote)
         return;
     m_publicNote = publicNote;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MEMBER_PNOTE);
     stmt->setString(0, publicNote);
     stmt->setUInt32(1, m_guid.GetCounter());
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_MEMBER_PNOTE, CharacterDatabase, PreparedStatementBase::setString(), and PreparedStatementBase::setUInt32().
SetStats() [1/2]
void Guild::Member::SetStats (Player * player)
Definition at line 592 of file Guild.cpp.
 {
     m_name      = player->GetName();
     m_level     = player->getLevel();
     m_class     = player->getClass();
     m_gender    = player->getGender();
     m_zoneId    = player->GetZoneId();
     m_accountId = player->GetSession()->GetAccountId();
 }
References WorldSession::GetAccountId(), Unit::getClass(), Unit::getGender(), Unit::getLevel(), WorldObject::GetName(), Player::GetSession(), WorldObject::GetZoneId(), and Guild::m_name.
Referenced by Guild::AddMember().
SetStats() [2/2]
void Guild::Member::SetStats (std::string const & name, uint8 level, uint8 _class, uint8 gender, uint32 zoneId, uint32 accountId)
Definition at line 602 of file Guild.cpp.
 {
     m_name      = name;
     m_level     = level;
     m_class     = _class;
     m_gender    = gender;
     m_zoneId    = zoneId;
     m_accountId = accountId;
 }
References Guild::m_name.
SetZoneID()
void Guild::Member::SetZoneID (uint32 id) inline
Definition at line 308 of file Guild.h.
 { m_zoneId = id; }
References m_zoneId.
UpdateBankWithdrawValue()
void Guild::Member::UpdateBankWithdrawValue (CharacterDatabaseTransaction trans, uint8 tabId, uint32 amount)
Definition at line 736 of file Guild.cpp.
 {
     m_bankWithdraw[tabId] += amount;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_MEMBER_WITHDRAW);
     stmt->setUInt32(0, m_guid.GetCounter());
     for (uint8 i = 0; i <= GUILD_BANK_MAX_TABS;)
     {
         uint32 withdraw = m_bankWithdraw[i++];
         stmt->setUInt32(i, withdraw);
     }
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References CHAR_INS_GUILD_MEMBER_WITHDRAW, CharacterDatabase, GUILD_BANK_MAX_TABS, and PreparedStatementBase::setUInt32().
Referenced by Guild::HandleMemberWithdrawMoney().
UpdateLogoutTime()
void Guild::Member::UpdateLogoutTime () inline
Definition at line 335 of file Guild.h.
 { m_logoutTime = ::time(nullptr); }
References m_logoutTime.
WritePacket()
void Guild::Member::WritePacket (WorldPacket & data, bool sendOfficerNote) const
Definition at line 711 of file Guild.cpp.
 {
     data << m_guid
          << uint8(m_flags)
          << m_name
          << uint32(m_rankId)
          << uint8(m_level)
          << uint8(m_class)
          << uint8(m_gender)
          << uint32(m_zoneId);
     if (!m_flags)
         data << float(float(::time(nullptr) - m_logoutTime) / DAY);
     data << m_publicNote;
     if (sendOfficerNote)
         data << m_officerNote;
     else
         data << "";
 }
References DAY, and Guild::m_name.
Member Data Documentation
m_accountId
uint32 Guild::Member::m_accountId private
Definition at line 357 of file Guild.h.
Referenced by GetAccountId().
m_bankWithdraw
int32 Guild::Member::m_bankWithdraw[GUILD_BANK_MAX_TABS+1] private
Definition at line 363 of file Guild.h.
Referenced by Member().
m_class
uint8 Guild::Member::m_class private
Definition at line 353 of file Guild.h.
Referenced by GetClass().
m_flags
uint8 Guild::Member::m_flags private
Definition at line 355 of file Guild.h.
Referenced by AddFlag(), GetFlags(), IsOnline(), RemFlag(), and ResetFlags().
m_gender
uint8 Guild::Member::m_gender private
Definition at line 354 of file Guild.h.
Referenced by GetGender().
m_guid
ObjectGuid Guild::Member::m_guid private
Definition at line 349 of file Guild.h.
Referenced by FindPlayer(), GetGUID(), and IsSamePlayer().
m_guildId
uint32 Guild::Member::m_guildId private
Definition at line 347 of file Guild.h.
m_level
uint8 Guild::Member::m_level private
Definition at line 352 of file Guild.h.
Referenced by GetLevel(), and SetLevel().
m_logoutTime
uint64 Guild::Member::m_logoutTime private
Definition at line 356 of file Guild.h.
Referenced by GetLogoutTime(), and UpdateLogoutTime().
m_name
std::string Guild::Member::m_name private
Definition at line 350 of file Guild.h.
Referenced by GetName().
m_officerNote
std::string Guild::Member::m_officerNote private
Definition at line 361 of file Guild.h.
Referenced by GetOfficerNote().
m_publicNote
std::string Guild::Member::m_publicNote private
Definition at line 360 of file Guild.h.
Referenced by GetPublicNote().
m_rankId
uint8 Guild::Member::m_rankId private
Definition at line 359 of file Guild.h.
Referenced by GetRankId(), IsRank(), and IsRankNotLower().
m_zoneId
uint32 Guild::Member::m_zoneId private
Definition at line 351 of file Guild.h.
Referenced by GetZoneId(), and SetZoneID().
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp