Azerotcore-wotlk: deps/mysqllite/mysys/my_pread.c File Reference
my_pread.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include "my_base.h"
#include <m_string.h>
#include <errno.h>
Functions
size_t my_pread (File Filedes, uchar *Buffer, size_t Count, my_off_t offset, myf MyFlags)
size_t my_pwrite (File Filedes, const uchar *Buffer, size_t Count, my_off_t offset, myf MyFlags)
Function Documentation
my_pread()
size_t my_pread (File Filedes, uchar * Buffer, size_t Count, my_off_t offset, myf MyFlags)
Definition at line 48 of file my_pread.c.
 {
   size_t readbytes;
   int error= 0;
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
   int save_errno;
 #endif
   DBUG_ENTER("my_pread");
   DBUG_PRINT("my",("fd: %d  Seek: %llu  Buffer: %p  Count: %lu  MyFlags: %d",
              Filedes, (ulonglong)offset, Buffer, (ulong)Count, MyFlags));
   for (;;)
   {
     errno= 0;    /* Linux, Windows don't reset this on EOF/success */
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
     mysql_mutex_lock(&my_file_info[Filedes].mutex);
     readbytes= (uint) -1;
     error= (lseek(Filedes, offset, MY_SEEK_SET) == (my_off_t) -1 ||
            (readbytes= read(Filedes, Buffer, Count)) != Count);
     save_errno= errno;
     mysql_mutex_unlock(&my_file_info[Filedes].mutex);
     if (error)
       errno= save_errno;
 #else
 #if defined(_WIN32)
     readbytes= my_win_pread(Filedes, Buffer, Count, offset);
 #else
     readbytes= pread(Filedes, Buffer, Count, offset);
 #endif
     error= (readbytes != Count);
 #endif
     if(error)
     {
       my_errno= errno ? errno : -1;
       if (errno == 0 || (readbytes != (size_t) -1 &&
                       (MyFlags & (MY_NABP | MY_FNABP))))
          my_errno= HA_ERR_FILE_TOO_SHORT;
       DBUG_PRINT("warning",("Read only %d bytes off %u from %d, errno: %d",
                             (int) readbytes, (uint) Count,Filedes,my_errno));
       if ((readbytes == 0 || readbytes == (size_t) -1) && errno == EINTR)
       {
         DBUG_PRINT("debug", ("my_pread() was interrupted and returned %d",
                              (int) readbytes));
         continue;                              /* Interrupted */
       }
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         if (readbytes == (size_t) -1)
           my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
         else if (MyFlags & (MY_NABP | MY_FNABP))
           my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
       }
       if (readbytes == (size_t) -1 || (MyFlags & (MY_FNABP | MY_NABP)))
         DBUG_RETURN(MY_FILE_ERROR);         /* Return with error */
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       DBUG_RETURN(0);                      /* Read went ok; Return 0 */
     DBUG_RETURN(readbytes);                /* purecov: inspected */
   }
 } /* my_pread */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, error(), HA_ERR_FILE_TOO_SHORT, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_file_info, my_filename(), MY_FNABP, MY_NABP, MY_SEEK_SET, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, and read.
Referenced by inline_mysql_file_pread(), key_cache_read(), and read_block().
my_pwrite()
size_t my_pwrite (File Filedes, const uchar * Buffer, size_t Count, my_off_t offset, myf MyFlags)
Definition at line 136 of file my_pread.c.
 {
   size_t writtenbytes, written;
   uint errors;
   DBUG_ENTER("my_pwrite");
   DBUG_PRINT("my",("fd: %d  Seek: %llu  Buffer: %p  Count: %lu  MyFlags: %d",
              Filedes, offset, Buffer, (ulong)Count, MyFlags));
   errors= 0;
   written= 0;
   for (;;)
   {
 #if !defined (HAVE_PREAD) && !defined (_WIN32)
     int error;
     writtenbytes= (size_t) -1;
     mysql_mutex_lock(&my_file_info[Filedes].mutex);
     error= (lseek(Filedes, offset, MY_SEEK_SET) != (my_off_t) -1 &&
             (writtenbytes= write(Filedes, Buffer, Count)) == Count);
     mysql_mutex_unlock(&my_file_info[Filedes].mutex);
     if (error)
       break;
 #elif defined (_WIN32)
     writtenbytes= my_win_pwrite(Filedes, Buffer, Count, offset);
 #else
     writtenbytes= pwrite(Filedes, Buffer, Count, offset);
 #endif
     if(writtenbytes == Count)
       break;
     my_errno= errno;
     if (writtenbytes != (size_t) -1)
     {
       written+= writtenbytes;
       Buffer+= writtenbytes;
       Count-= writtenbytes;
       offset+= writtenbytes;
     }
     DBUG_PRINT("error",("Write only %u bytes", (uint) writtenbytes));
 #ifndef NO_BACKGROUND
     if (my_thread_var->abort)
       MyFlags&= ~ MY_WAIT_IF_FULL;      /* End if aborted by user */
     if ((my_errno == ENOSPC || my_errno == EDQUOT) &&
         (MyFlags & MY_WAIT_IF_FULL))
     {
       wait_for_free_space(my_filename(Filedes), errors);
       errors++;
       continue;
     }
     if ((writtenbytes && writtenbytes != (size_t) -1) || my_errno == EINTR)
       continue;                 /* Retry */
 #endif
     if (MyFlags & (MY_NABP | MY_FNABP))
     {
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         my_error(EE_WRITE, MYF(ME_BELL | ME_WAITTANG),
                  my_filename(Filedes),my_errno);
       }
       DBUG_RETURN(MY_FILE_ERROR);       /* Error on read */
     }
     else
       break;                    /* Return bytes written */
   }
   DBUG_EXECUTE_IF("check", my_seek(Filedes, -1, SEEK_SET, MYF(0)););
   if (MyFlags & (MY_NABP | MY_FNABP))
     DBUG_RETURN(0);         /* Want only errors */
   DBUG_RETURN(writtenbytes+written); /* purecov: inspected */
 } /* my_pwrite */
References Acore::Count(), DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, EDQUOT, EE_WRITE, errno, error(), mpq::errors, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_file_info, my_filename(), MY_FNABP, MY_NABP, my_seek(), MY_SEEK_SET, my_thread_var, MY_WAIT_IF_FULL, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, SEEK_SET, wait_for_free_space(), and write.
Referenced by find_key_block(), flush_cached_blocks(), inline_mysql_file_pwrite(), and key_cache_write().