Azerotcore-wotlk: basic_format_args< Context > Class Template Reference
basic_format_args< Context > Class Template Reference
#include <core.h>
Public Types
using size_type = int
using format_arg = basic_format_arg< Context >
Public Member Functions
constexpr basic_format_args ()
template<typename... Args>
constexpr FMT_INLINE basic_format_args (const format_arg_store< Context, Args... > &store)
constexpr FMT_INLINE basic_format_args (const dynamic_format_arg_store< Context > &store)
constexpr basic_format_args (const format_arg *args, int count)
FMT_CONSTEXPR auto get (int id) const -> format_arg
template<typename Char >
auto get (basic_string_view< Char > name) const -> format_arg
template<typename Char >
auto get_id (basic_string_view< Char > name) const -> int
auto max_size () const -> int
Private Member Functions
constexpr auto is_packed () const -> bool
auto has_named_args () const -> bool
FMT_CONSTEXPR auto type (int index) const -> detail::type
constexpr FMT_INLINE basic_format_args (unsigned long long desc, const detail::value< Context > *values)
constexpr basic_format_args (unsigned long long desc, const format_arg *args)
Private Attributes
unsigned long long desc_
union {
const detail::value< Context > * values_
const format_arg * args_
};
Detailed Description
template<typename Context>
class basic_format_args< Context >
\rst A view of a collection of formatting arguments. To avoid lifetime issues it should only be used as a parameter type in type-erased functions such as vformat::
void vlog(string_view format_str, format_args args); // OK format_args args = make_format_args(42); // Error: dangling reference \endrst
Definition at line 1740 of file core.h.
Member Typedef Documentation
format_arg
template<typename Context > using basic_format_args< Context >::format_arg = basic_format_arg<Context>
Definition at line 1743 of file core.h.
size_type
template<typename Context > using basic_format_args< Context >::size_type = int
Definition at line 1742 of file core.h.
Constructor & Destructor Documentation
basic_format_args() [1/6]
template<typename Context > constexpr FMT_INLINE basic_format_args< Context >::basic_format_args (unsigned long long desc, const detail::value< Context > * values) inline constexpr private
Definition at line 1774 of file core.h.
       : desc_(desc), values_(values) {}
basic_format_args() [2/6]
template<typename Context > constexpr basic_format_args< Context >::basic_format_args (unsigned long long desc, const format_arg * args) inline constexpr private
Definition at line 1777 of file core.h.
       : desc_(desc), args_(args) {}
basic_format_args() [3/6]
template<typename Context > constexpr basic_format_args< Context >::basic_format_args () inline constexpr
Definition at line 1781 of file core.h.
 : desc_(0), args_(nullptr) {}
basic_format_args() [4/6]
template<typename Context > template<typename... Args> constexpr FMT_INLINE basic_format_args< Context >::basic_format_args (const format_arg_store< Context, Args... > & store) inline constexpr
\rst Constructs a basic_format_args object from ~fmtformat_arg_store. \endrst
Definition at line 1789 of file core.h.
       : basic_format_args(format_arg_store<Context, Args...>::desc,
                           store.data_.args()) {}
basic_format_args() [5/6]
template<typename Context > constexpr FMT_INLINE basic_format_args< Context >::basic_format_args (const dynamic_format_arg_store< Context > & store) inline constexpr
\rst Constructs a basic_format_args object from ~fmtdynamic_format_arg_store. \endrst
Definition at line 1800 of file core.h.
       : basic_format_args(store.get_types(), store.data()) {}
basic_format_args() [6/6]
template<typename Context > constexpr basic_format_args< Context >::basic_format_args (const format_arg * args, int count) inline constexpr
\rst Constructs a basic_format_args object from a dynamic set of arguments. \endrst
Definition at line 1809 of file core.h.
       : basic_format_args(detail::is_unpacked_bit | detail::to_unsigned(count),
                           args) {}
Member Function Documentation
get() [1/2]
template<typename Context > template<typename Char > auto basic_format_args< Context >::get (basic_string_view< Char > name) const -> format_arg inline
Definition at line 1828 of file core.h.
{
     int id = get_id(name);
     return id >= 0 ? get(id) : format_arg();
   }
References locale_ref::get(), and name.
get() [2/2]
template<typename Context > FMT_CONSTEXPR auto basic_format_args< Context >::get (int id) const -> format_arg inline
Returns the argument with the specified id.
Definition at line 1814 of file core.h.
{
     format_arg arg;
     if (!is_packed()) {
       if (id < max_size()) arg = args_[id];
       return arg;
     }
     if (id >= detail::max_packed_args) return arg;
     arg.type_ = type(id);
     if (arg.type_ == detail::type::none_type) return arg;
     arg.value_ = values_[id];
     return arg;
   }
References arg(), and max_packed_args.
Referenced by basic_printf_context< OutputIt, Char >::arg(), and basic_format_context< OutputIt, Char >::arg().
get_id()
template<typename Context > template<typename Char > auto basic_format_args< Context >::get_id (basic_string_view< Char > name) const -> int inline
Definition at line 1834 of file core.h.
{
     if (!has_named_args()) return -1;
     const auto& named_args =
         (is_packed() ? values_[-1] : args_[-1].value_).named_args;
     for (size_t i = 0; i < named_args.size; ++i) {
       if (named_args.data[i].name == name) return named_args.data[i].id;
     }
     return -1;
   }
References name.
Referenced by basic_format_context< OutputIt, Char >::arg_id().
has_named_args()
template<typename Context > auto basic_format_args< Context >::has_named_args () const -> bool inline private
Definition at line 1764 of file core.h.
{
     return (desc_ & detail::has_named_args_bit) != 0;
   }
References has_named_args_bit.
is_packed()
template<typename Context > constexpr auto basic_format_args< Context >::is_packed () const -> bool inline constexpr private
Definition at line 1761 of file core.h.
{
     return (desc_ & detail::is_unpacked_bit) == 0;
   }
References is_unpacked_bit.
max_size()
template<typename Context > auto basic_format_args< Context >::max_size () const -> int inline
Definition at line 1844 of file core.h.
{
     unsigned long long max_packed = detail::max_packed_args;
     return static_cast<int>(is_packed() ? max_packed
                                         : desc_ & ~detail::is_unpacked_bit);
   }
References is_unpacked_bit, and max_packed_args.
type()
template<typename Context > FMT_CONSTEXPR auto basic_format_args< Context >::type (int index) const -> detail::type inline private
Definition at line 1768 of file core.h.
{
     int shift = index * detail::packed_arg_bits;
     unsigned int mask = (1 << detail::packed_arg_bits) - 1;
     return static_cast<detail::type>((desc_ >> shift) & mask);
   }
References index, and packed_arg_bits.
Member Data Documentation
union { ... }
args_
template<typename Context > const format_arg* basic_format_args< Context >::args_
Definition at line 1758 of file core.h.
desc_
template<typename Context > unsigned long long basic_format_args< Context >::desc_ private
Definition at line 1750 of file core.h.
values_
template<typename Context > const detail::value<Context>* basic_format_args< Context >::values_
Definition at line 1757 of file core.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h