Azerotcore-wotlk: npc_midsummer_torch_target::npc_midsummer_torch_targetAI Struct Reference
npc_midsummer_torch_target::npc_midsummer_torch_targetAI Struct Reference
Public Member Functions
npc_midsummer_torch_targetAI (Creature *c)
void SetPlayerGUID (ObjectGuid guid, uint8 cnt)
bool CanBeSeen (Player const *seer) override
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
void FillPositions ()
void SelectPosition ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid playerGUID
uint32 startTimer
uint32 teleTimer
std::vector< Position > posVec
uint8 counter
uint8 maxCount
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 101 of file midsummer.cpp.
Constructor & Destructor Documentation
npc_midsummer_torch_targetAI()
npc_midsummer_torch_target::npc_midsummer_torch_targetAI::npc_midsummer_torch_targetAI (Creature * c) inline
Definition at line 103 of file midsummer.cpp.
                                                   : ScriptedAI(c)
         {
             teleTimer = 0;
             startTimer = 1;
             posVec.clear();
             playerGUID.Clear();
             me->CastSpell(me, 43313, true);
             counter = 0;
             maxCount = 0;
         }
References Unit::CastSpell(), ObjectGuid::Clear(), counter, maxCount, ScriptedAI::me, playerGUID, posVec, startTimer, and teleTimer.
Member Function Documentation
CanBeSeen()
bool npc_midsummer_torch_target::npc_midsummer_torch_targetAI::CanBeSeen (Player const * seer) inline override virtual
Reimplemented from CreatureAI.
Definition at line 127 of file midsummer.cpp.
         {
             return seer->GetGUID() == playerGUID;
         }
References Object::GetGUID(), and playerGUID.
FillPositions()
void npc_midsummer_torch_target::npc_midsummer_torch_targetAI::FillPositions () inline
Definition at line 181 of file midsummer.cpp.
         {
             std::list<GameObject*> gobjList;
             me->GetGameObjectListWithEntryInGrid(gobjList, 187708 /*TORCH_GO*/, 30.0f);
             for (std::list<GameObject*>::const_iterator itr = gobjList.begin(); itr != gobjList.end(); ++itr)
             {
                 Position pos;
                 pos.Relocate(*itr);
                 posVec.push_back(pos);
             }
         }
References WorldObject::GetGameObjectListWithEntryInGrid(), ScriptedAI::me, posVec, and Position::Relocate().
Referenced by UpdateAI().
SelectPosition()
void npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SelectPosition () inline
Definition at line 193 of file midsummer.cpp.
         {
             if (posVec.empty())
                 return;
             int8 num = urand(0, posVec.size() - 1);
             Position pos;
             pos.Relocate(posVec.at(num));
             me->m_last_notify_position.Relocate(0.0f, 0.0f, 0.0f);
             me->m_last_notify_mstime = World::GetGameTimeMS() + 10000;
             me->NearTeleportTo(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation());
         }
References World::GetGameTimeMS(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::m_last_notify_mstime, Unit::m_last_notify_position, ScriptedAI::me, Unit::NearTeleportTo(), posVec, Position::Relocate(), and urand().
Referenced by UpdateAI().
SetPlayerGUID()
void npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SetPlayerGUID (ObjectGuid guid, uint8 cnt) inline
Definition at line 121 of file midsummer.cpp.
         {
             playerGUID = guid;
             maxCount = cnt;
         }
References maxCount, and playerGUID.
SpellHit()
void npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SpellHit (Unit * caster, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 132 of file midsummer.cpp.
         {
             if (posVec.empty())
                 return;
             // Triggered spell from torch
             if (spellInfo->Id == 46054 && caster->GetTypeId() == TYPEID_PLAYER)
             {
                 me->CastSpell(me, 45724, true); // hit visual anim
                 if (++counter >= maxCount)
                 {
                     caster->CastSpell(caster, (caster->ToPlayer()->GetTeamId() ? 46651 : 45719), true); // quest complete spell
                     me->DespawnOrUnsummon(1);
                     return;
                 }
                 teleTimer = 1;
             }
         }
References Unit::CastSpell(), counter, Creature::DespawnOrUnsummon(), Player::GetTeamId(), Object::GetTypeId(), SpellInfo::Id, maxCount, ScriptedAI::me, posVec, teleTimer, Object::ToPlayer(), and TYPEID_PLAYER.
UpdateAI()
void npc_midsummer_torch_target::npc_midsummer_torch_targetAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 151 of file midsummer.cpp.
         {
             if (startTimer)
             {
                 startTimer += diff;
                 if (startTimer >= 200)
                 {
                     startTimer = 0;
                     FillPositions();
                     SelectPosition();
                 }
             }
             if (teleTimer)
             {
                 teleTimer += diff;
                 if (teleTimer >= 750 && teleTimer < 10000)
                 {
                     teleTimer = 10000;
                     SelectPosition();
                 }
                 else if (teleTimer >= 10500)
                 {
                     if (Player* plr = ObjectAccessor::GetPlayer(*me, playerGUID))
                         plr->UpdateTriggerVisibility();
                     teleTimer = 0;
                 }
             }
         }
References FillPositions(), ObjectAccessor::GetPlayer(), ScriptedAI::me, playerGUID, SelectPosition(), startTimer, and teleTimer.
Member Data Documentation
counter
uint8 npc_midsummer_torch_target::npc_midsummer_torch_targetAI::counter
Definition at line 118 of file midsummer.cpp.
Referenced by npc_midsummer_torch_targetAI(), and SpellHit().
maxCount
uint8 npc_midsummer_torch_target::npc_midsummer_torch_targetAI::maxCount
Definition at line 119 of file midsummer.cpp.
Referenced by npc_midsummer_torch_targetAI(), SetPlayerGUID(), and SpellHit().
playerGUID
ObjectGuid npc_midsummer_torch_target::npc_midsummer_torch_targetAI::playerGUID
Definition at line 114 of file midsummer.cpp.
Referenced by CanBeSeen(), npc_midsummer_torch_targetAI(), SetPlayerGUID(), and UpdateAI().
posVec
std::vector<Position> npc_midsummer_torch_target::npc_midsummer_torch_targetAI::posVec
Definition at line 117 of file midsummer.cpp.
Referenced by FillPositions(), npc_midsummer_torch_targetAI(), SelectPosition(), and SpellHit().
startTimer
uint32 npc_midsummer_torch_target::npc_midsummer_torch_targetAI::startTimer
Definition at line 115 of file midsummer.cpp.
Referenced by npc_midsummer_torch_targetAI(), and UpdateAI().
teleTimer
uint32 npc_midsummer_torch_target::npc_midsummer_torch_targetAI::teleTimer
Definition at line 116 of file midsummer.cpp.
Referenced by npc_midsummer_torch_targetAI(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/midsummer.cpp