Azerotcore-wotlk: LoadPetFromDBQueryHolder Class Reference
LoadPetFromDBQueryHolder Class Reference
Public Member Functions
LoadPetFromDBQueryHolder (uint32 petNumber, bool current, uint32 diffTime, std::string &&actionBar, uint32 health, uint32 mana)
uint32 GetPetNumber () const
uint32 GetDiffTime () const
bool GetCurrent () const
uint32 GetSavedHealth () const
uint32 GetSavedMana () const
std::string GetActionBar () const
bool Initialize ()
Public Member Functions inherited from SQLQueryHolder< T >
bool SetPreparedQuery (size_t index, PreparedStatement< T > *stmt)
Public Member Functions inherited from SQLQueryHolderBase
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (size_t size)
PreparedQueryResult GetPreparedResult (size_t index) const
void SetPreparedResult (size_t index, PreparedResultSet *result)
Private Types
enum { AURAS , SPELLS , COOLDOWNS , MAX }
Private Attributes
const uint32 _petNumber
const bool _current
const uint32 _diffTime
const std::string _actionBar
const uint32 _savedHealth
const uint32 _savedMana
Additional Inherited Members
Protected Member Functions inherited from SQLQueryHolderBase
bool SetPreparedQueryImpl (size_t index, PreparedStatementBase *stmt)
Detailed Description
Definition at line 38 of file PetHandler.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
AURAS
SPELLS
COOLDOWNS
MAX
Definition at line 58 of file PetHandler.cpp.
     {
         AURAS,
         SPELLS,
         COOLDOWNS,
         MAX
     };
Constructor & Destructor Documentation
LoadPetFromDBQueryHolder()
LoadPetFromDBQueryHolder::LoadPetFromDBQueryHolder (uint32 petNumber, bool current, uint32 diffTime, std::string && actionBar, uint32 health, uint32 mana) inline
Definition at line 41 of file PetHandler.cpp.
         : _petNumber(petNumber),
         _current(current),
         _diffTime(diffTime),
         _actionBar(std::move(actionBar)),
         _savedHealth(health),
         _savedMana(mana) { }
Member Function Documentation
GetActionBar()
std::string LoadPetFromDBQueryHolder::GetActionBar () const inline
Definition at line 54 of file PetHandler.cpp.
 { return _actionBar; }
References _actionBar.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
GetCurrent()
bool LoadPetFromDBQueryHolder::GetCurrent () const inline
Definition at line 51 of file PetHandler.cpp.
 { return _current; }
References _current.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
GetDiffTime()
uint32 LoadPetFromDBQueryHolder::GetDiffTime () const inline
Definition at line 50 of file PetHandler.cpp.
 { return _diffTime; }
References _diffTime.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
GetPetNumber()
uint32 LoadPetFromDBQueryHolder::GetPetNumber () const inline
Definition at line 49 of file PetHandler.cpp.
 { return _petNumber; }
References _petNumber.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
GetSavedHealth()
uint32 LoadPetFromDBQueryHolder::GetSavedHealth () const inline
Definition at line 52 of file PetHandler.cpp.
 { return _savedHealth; }
References _savedHealth.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
GetSavedMana()
uint32 LoadPetFromDBQueryHolder::GetSavedMana () const inline
Definition at line 53 of file PetHandler.cpp.
 { return _savedMana; }
References _savedMana.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
Initialize()
bool LoadPetFromDBQueryHolder::Initialize ()
Definition at line 75 of file PetHandler.cpp.
 {
     SetSize(MAX);
     bool res = true;
     CharacterDatabasePreparedStatement* stmt = nullptr;
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_AURA);
     stmt->setUInt32(0, _petNumber);
     res &= SetPreparedQuery(AURAS, stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_SPELL);
     stmt->setUInt32(0, _petNumber);
     res &= SetPreparedQuery(SPELLS, stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_SPELL_COOLDOWN);
     stmt->setUInt32(0, _petNumber);
     res &= SetPreparedQuery(COOLDOWNS, stmt);
     return res;
 }
References _petNumber, AURAS, CHAR_SEL_PET_AURA, CHAR_SEL_PET_SPELL, CHAR_SEL_PET_SPELL_COOLDOWN, CharacterDatabase, COOLDOWNS, MAX, SQLQueryHolder< T >::SetPreparedQuery(), SQLQueryHolderBase::SetSize(), PreparedStatementBase::setUInt32(), and SPELLS.
Member Data Documentation
_actionBar
const std::string LoadPetFromDBQueryHolder::_actionBar private
Definition at line 70 of file PetHandler.cpp.
Referenced by GetActionBar().
_current
const bool LoadPetFromDBQueryHolder::_current private
Definition at line 68 of file PetHandler.cpp.
Referenced by GetCurrent().
_diffTime
const uint32 LoadPetFromDBQueryHolder::_diffTime private
Definition at line 69 of file PetHandler.cpp.
Referenced by GetDiffTime().
_petNumber
const uint32 LoadPetFromDBQueryHolder::_petNumber private
Definition at line 67 of file PetHandler.cpp.
Referenced by GetPetNumber(), and Initialize().
_savedHealth
const uint32 LoadPetFromDBQueryHolder::_savedHealth private
Definition at line 71 of file PetHandler.cpp.
Referenced by GetSavedHealth().
_savedMana
const uint32 LoadPetFromDBQueryHolder::_savedMana private
Definition at line 72 of file PetHandler.cpp.
Referenced by GetSavedMana().
The documentation for this class was generated from the following file:
src/server/game/Handlers/PetHandler.cpp