Azerotcore-wotlk: DBCStorageBase Class Reference
DBCStorageBase Class Reference abstract
Interface class for common access.
#include <DBCStore.h>
Public Member Functions
DBCStorageBase (char const *fmt)
virtual ~DBCStorageBase ()
char const * GetFormat () const
uint32 GetFieldCount () const
virtual bool Load (char const *path)=0
virtual bool LoadStringsFrom (char const *path)=0
virtual void LoadFromDB (char const *table, char const *format)=0
Protected Member Functions
bool Load (char const *path, char **&indexTable)
bool LoadStringsFrom (char const *path, char **indexTable)
void LoadFromDB (char const *table, char const *format, char **&indexTable)
Protected Attributes
uint32 _fieldCount
char const * _fileFormat
char * _dataTable
std::vector< char * > _stringPool
uint32 _indexTableSize
Detailed Description
Interface class for common access.
Definition at line 143 of file DBCStore.h.
Constructor & Destructor Documentation
DBCStorageBase()
DBCStorageBase::DBCStorageBase (char const * fmt)
Definition at line 21 of file DBCStore.cpp.
                                               : _fieldCount(0), _fileFormat(fmt), _dataTable(nullptr), _indexTableSize(0)
 {
 }
~DBCStorageBase()
DBCStorageBase::~DBCStorageBase () virtual
Definition at line 25 of file DBCStore.cpp.
 {
     delete[] _dataTable;
     for (char* strings : _stringPool)
         delete[] strings;
 }
References _dataTable, and _stringPool.
Member Function Documentation
GetFieldCount()
uint32 DBCStorageBase::GetFieldCount () const inline
Definition at line 150 of file DBCStore.h.
 { return _fieldCount; }
References _fieldCount.
Referenced by LoadDBC().
GetFormat()
char const* DBCStorageBase::GetFormat () const inline
Definition at line 149 of file DBCStore.h.
 { return _fileFormat; }
References _fileFormat.
Referenced by LoadDBC().
Load() [1/2]
virtual bool DBCStorageBase::Load (char const * path) pure virtual
Implemented in DBCStorage< T >.
Referenced by DBCStorage< T >::Load(), and LoadFromDB().
Load() [2/2]
bool DBCStorageBase::Load (char const * path, char **& indexTable) protected
Definition at line 32 of file DBCStore.cpp.
 {
     indexTable = nullptr;
     DBCFileLoader dbc;
     // Check if load was sucessful, only then continue
     if (!dbc.Load(path, _fileFormat))
         return false;
     _fieldCount = dbc.GetCols();
     // load raw non-string data
     _dataTable = dbc.AutoProduceData(_fileFormat, _indexTableSize, indexTable);
     // load strings from dbc data
     if (char* stringBlock = dbc.AutoProduceStrings(_fileFormat, _dataTable))
         _stringPool.push_back(stringBlock);
     // error in dbc file at loading if nullptr
     return indexTable != nullptr;
 }
References _dataTable, _fieldCount, _fileFormat, _indexTableSize, _stringPool, DBCFileLoader::AutoProduceData(), DBCFileLoader::AutoProduceStrings(), DBCFileLoader::GetCols(), and DBCFileLoader::Load().
LoadFromDB() [1/2]
virtual void DBCStorageBase::LoadFromDB (char const * table, char const * format) pure virtual
Implemented in DBCStorage< T >.
Referenced by DBCStorage< T >::LoadFromDB().
LoadFromDB() [2/2]
void DBCStorageBase::LoadFromDB (char const * table, char const * format, char **& indexTable) protected
Definition at line 74 of file DBCStore.cpp.
 {
     _stringPool.push_back(DBCDatabaseLoader(table, format, _stringPool).Load(_indexTableSize, indexTable));
 }
References _indexTableSize, _stringPool, and Load().
LoadStringsFrom() [1/2]
virtual bool DBCStorageBase::LoadStringsFrom (char const * path) pure virtual
Implemented in DBCStorage< T >.
Referenced by DBCStorage< T >::LoadStringsFrom().
LoadStringsFrom() [2/2]
bool DBCStorageBase::LoadStringsFrom (char const * path, char ** indexTable) protected
Definition at line 55 of file DBCStore.cpp.
 {
     // DBC must be already loaded using Load
     if (!indexTable)
         return false;
     DBCFileLoader dbc;
     // Check if load was successful, only then continue
     if (!dbc.Load(path, _fileFormat))
         return false;
     // load strings from another locale dbc data
     if (char* stringBlock = dbc.AutoProduceStrings(_fileFormat, _dataTable))
         _stringPool.push_back(stringBlock);
     return true;
 }
References _dataTable, _fileFormat, _stringPool, DBCFileLoader::AutoProduceStrings(), and DBCFileLoader::Load().
Member Data Documentation
_dataTable
char* DBCStorageBase::_dataTable protected
Definition at line 163 of file DBCStore.h.
Referenced by Load(), LoadStringsFrom(), and ~DBCStorageBase().
_fieldCount
uint32 DBCStorageBase::_fieldCount protected
Definition at line 161 of file DBCStore.h.
Referenced by GetFieldCount(), and Load().
_fileFormat
char const* DBCStorageBase::_fileFormat protected
Definition at line 162 of file DBCStore.h.
Referenced by GetFormat(), Load(), and LoadStringsFrom().
_indexTableSize
uint32 DBCStorageBase::_indexTableSize protected
Definition at line 165 of file DBCStore.h.
Referenced by DBCStorage< T >::begin(), DBCStorage< T >::end(), DBCStorage< T >::GetNumRows(), Load(), LoadFromDB(), and DBCStorage< T >::LookupEntry().
_stringPool
std::vector<char*> DBCStorageBase::_stringPool protected
Definition at line 164 of file DBCStore.h.
Referenced by Load(), LoadFromDB(), LoadStringsFrom(), and ~DBCStorageBase().
The documentation for this class was generated from the following files:
src/server/shared/DataStores/DBCStore.h
src/server/shared/DataStores/DBCStore.cpp