Azerotcore-wotlk: go_amberpine_outhouse Class Reference
go_amberpine_outhouse Class Reference
Public Member Functions
go_amberpine_outhouse ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *go, uint32, uint32 action) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1505 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_amberpine_outhouse()
go_amberpine_outhouse::go_amberpine_outhouse () inline
Definition at line 1508 of file go_scripts.cpp.
 : GameObjectScript("go_amberpine_outhouse") { }
Member Function Documentation
OnGossipHello()
bool go_amberpine_outhouse::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1510 of file go_scripts.cpp.
     {
         QuestStatus status = player->GetQuestStatus(QUEST_DOING_YOUR_DUTY);
         if (status == QUEST_STATUS_INCOMPLETE || status == QUEST_STATUS_COMPLETE || status == QUEST_STATUS_REWARDED)
         {
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_USE_OUTHOUSE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             SendGossipMenuFor(player, GOSSIP_OUTHOUSE_VACANT, go->GetGUID());
         }
         else
             SendGossipMenuFor(player, GOSSIP_OUTHOUSE_INUSE, go->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_OUTHOUSE_INUSE, GOSSIP_OUTHOUSE_VACANT, GOSSIP_SENDER_MAIN, GOSSIP_USE_OUTHOUSE, QUEST_DOING_YOUR_DUTY, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_REWARDED, and SendGossipMenuFor().
OnGossipSelect()
bool go_amberpine_outhouse::OnGossipSelect (Player * player, GameObject * go, uint32 , uint32 action) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1524 of file go_scripts.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
         {
             CloseGossipMenuFor(player);
             Creature* target = GetClosestCreatureWithEntry(player, NPC_OUTHOUSE_BUNNY, 3.0f);
             if (target)
             {
                 target->AI()->SetData(1, player->getGender());
                 go->CastSpell(target, SPELL_INDISPOSED_III);
             }
             go->CastSpell(player, SPELL_INDISPOSED);
             if (player->HasItemCount(ITEM_ANDERHOLS_SLIDER_CIDER))
                 player->CastSpell(player, SPELL_CREATE_AMBERSEEDS, true);
             return true;
         }
         else
         {
             CloseGossipMenuFor(player);
             player->GetSession()->SendNotification(GO_ANDERHOLS_SLIDER_CIDER_NOT_FOUND);
             return false;
         }
     }
References Creature::AI(), Unit::CastSpell(), GameObject::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), GetClosestCreatureWithEntry(), Unit::getGender(), Player::GetSession(), GO_ANDERHOLS_SLIDER_CIDER_NOT_FOUND, GOSSIP_ACTION_INFO_DEF, Player::HasItemCount(), ITEM_ANDERHOLS_SLIDER_CIDER, NPC_OUTHOUSE_BUNNY, WorldSession::SendNotification(), UnitAI::SetData(), SPELL_CREATE_AMBERSEEDS, SPELL_INDISPOSED, and SPELL_INDISPOSED_III.
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp