Azerotcore-wotlk: npc_giant_claw_tentacle::giant_claw_tentacleAI Struct Reference
npc_giant_claw_tentacle::giant_claw_tentacleAI Struct Reference
Public Member Functions
giant_claw_tentacleAI (Creature *creature)
void JustDied (Unit *) override
void Reset () override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 GroundRuptureTimer
uint32 ThrashTimer
uint32 HamstringTimer
uint32 EvadeTimer
ObjectGuid Portal
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1104 of file boss_cthun.cpp.
Constructor & Destructor Documentation
giant_claw_tentacleAI()
npc_giant_claw_tentacle::giant_claw_tentacleAI::giant_claw_tentacleAI (Creature * creature) inline
Definition at line 1106 of file boss_cthun.cpp.
                                                   : ScriptedAI(creature)
         {
             SetCombatMovement(false);
             if (Creature* pPortal = me->SummonCreature(NPC_GIANT_PORTAL, *me, TEMPSUMMON_CORPSE_DESPAWN))
             {
                 pPortal->SetReactState(REACT_PASSIVE);
                 Portal = pPortal->GetGUID();
             }
         }
References ScriptedAI::me, NPC_GIANT_PORTAL, Portal, REACT_PASSIVE, ScriptedAI::SetCombatMovement(), WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_DESPAWN.
Member Function Documentation
EnterCombat()
void npc_giant_claw_tentacle::giant_claw_tentacleAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1138 of file boss_cthun.cpp.
         {
             DoZoneInCombat();
         }
References CreatureAI::DoZoneInCombat().
JustDied()
void npc_giant_claw_tentacle::giant_claw_tentacleAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1123 of file boss_cthun.cpp.
         {
             if (Unit* p = ObjectAccessor::GetUnit(*me, Portal))
                 Unit::Kill(p, p);
         }
References ObjectAccessor::GetUnit(), Unit::Kill(), ScriptedAI::me, and Portal.
Reset()
void npc_giant_claw_tentacle::giant_claw_tentacleAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1129 of file boss_cthun.cpp.
         {
             //First rupture should happen half a second after we spawn
             GroundRuptureTimer = 500;
             HamstringTimer = 2000;
             ThrashTimer = 5000;
             EvadeTimer = 5000;
         }
References EvadeTimer, GroundRuptureTimer, HamstringTimer, and ThrashTimer.
UpdateAI()
void npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1143 of file boss_cthun.cpp.
         {
             //Check if we have a target
             if (!UpdateVictim())
                 return;
             //EvadeTimer
             if (!me->IsWithinMeleeRange(me->GetVictim()))
             {
                 if (EvadeTimer <= diff)
                 {
                     if (Unit* p = ObjectAccessor::GetUnit(*me, Portal))
                         Unit::Kill(p, p);
                     //Dissapear and reappear at new position
                     me->SetVisible(false);
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0);
                     if (!target)
                     {
                         Unit::Kill(me, me);
                         return;
                     }
                     if (!target->HasAura(SPELL_DIGESTIVE_ACID))
                     {
                         me->SetPosition(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0);
                         if (Creature* pPortal = me->SummonCreature(NPC_GIANT_PORTAL, *me, TEMPSUMMON_CORPSE_DESPAWN))
{
                             pPortal->SetReactState(REACT_PASSIVE);
                             Portal = pPortal->GetGUID();
                         }
                         GroundRuptureTimer = 500;
                         HamstringTimer = 2000;
                         ThrashTimer = 5000;
                         EvadeTimer = 5000;
                         AttackStart(target);
                     }
                     me->SetVisible(true);
                 }
                 else EvadeTimer -= diff;
             }
             //GroundRuptureTimer
             if (GroundRuptureTimer <= diff)
             {
                 DoCastVictim(SPELL_GROUND_RUPTURE);
                 GroundRuptureTimer = 30000;
             }
             else GroundRuptureTimer -= diff;
             //ThrashTimer
             if (ThrashTimer <= diff)
             {
                 DoCastVictim(SPELL_THRASH);
                 ThrashTimer = 10000;
             }
             else ThrashTimer -= diff;
             //HamstringTimer
             if (HamstringTimer <= diff)
             {
                 DoCastVictim(SPELL_HAMSTRING);
                 HamstringTimer = 10000;
             }
             else HamstringTimer -= diff;
             DoMeleeAttackIfReady();
         }
References ScriptedAI::AttackStart(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EvadeTimer, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ObjectAccessor::GetUnit(), Unit::GetVictim(), GroundRuptureTimer, HamstringTimer, Unit::HasAura(), Unit::IsWithinMeleeRange(), Unit::Kill(), ScriptedAI::me, NPC_GIANT_PORTAL, Portal, REACT_PASSIVE, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetPosition(), Unit::SetVisible(), SPELL_DIGESTIVE_ACID, SPELL_GROUND_RUPTURE, SPELL_HAMSTRING, SPELL_THRASH, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, ThrashTimer, and CreatureAI::UpdateVictim().
Member Data Documentation
EvadeTimer
uint32 npc_giant_claw_tentacle::giant_claw_tentacleAI::EvadeTimer
Definition at line 1120 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
GroundRuptureTimer
uint32 npc_giant_claw_tentacle::giant_claw_tentacleAI::GroundRuptureTimer
Definition at line 1117 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
HamstringTimer
uint32 npc_giant_claw_tentacle::giant_claw_tentacleAI::HamstringTimer
Definition at line 1119 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
Portal
ObjectGuid npc_giant_claw_tentacle::giant_claw_tentacleAI::Portal
Definition at line 1121 of file boss_cthun.cpp.
Referenced by giant_claw_tentacleAI(), JustDied(), and UpdateAI().
ThrashTimer
uint32 npc_giant_claw_tentacle::giant_claw_tentacleAI::ThrashTimer
Definition at line 1118 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp