Azerotcore-wotlk: boss_drakos::boss_drakosAI Struct Reference
boss_drakos::boss_drakosAI Struct Reference
Public Member Functions
boss_drakosAI (Creature *c)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 68 of file boss_drakos.cpp.
Constructor & Destructor Documentation
boss_drakosAI()
boss_drakos::boss_drakosAI::boss_drakosAI (Creature * c) inline
Definition at line 70 of file boss_drakos.cpp.
                                    : ScriptedAI(c)
         {
             pInstance = c->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
EnterCombat()
void boss_drakos::boss_drakosAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 86 of file boss_drakos.cpp.
         {
             Talk(SAY_AGGRO);
             if (pInstance)
                 pInstance->SetData(DATA_DRAKOS, IN_PROGRESS);
             me->SetInCombatWithZone();
             events.RescheduleEvent(EVENT_MAGIC_PULL, urand(10000, 15000));
             events.RescheduleEvent(EVENT_THUNDERING_STOMP, urand(3000, 6000));
             events.RescheduleEvent(EVENT_SUMMON, 2000);
         }
References DATA_DRAKOS, EVENT_MAGIC_PULL, EVENT_SUMMON, EVENT_THUNDERING_STOMP, IN_PROGRESS, ScriptedAI::me, pInstance, SAY_AGGRO, ZoneScript::SetData(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), and urand().
JustDied()
void boss_drakos::boss_drakosAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 100 of file boss_drakos.cpp.
         {
             Talk(SAY_DEATH);
             if (pInstance)
             {
                 pInstance->SetData(DATA_DRAKOS, DONE);
                 for( uint8 i = 0; i < 3; ++i )
                     if( ObjectGuid guid = pInstance->GetGuidData(DATA_DCD_1 + i) )
                         if( GameObject* pGo = ObjectAccessor::GetGameObject(*me, guid) )
                             if( pGo->GetGoState() != GO_STATE_ACTIVE )
{
                                 pGo->SetLootState(GO_READY);
                                 pGo->UseDoorOrButton(0, false);
                             }
             }
         }
References DATA_DCD_1, DATA_DRAKOS, DONE, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_READY, GO_STATE_ACTIVE, ScriptedAI::me, pInstance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
JustSummoned()
void boss_drakos::boss_drakosAI::JustSummoned (Creature *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 124 of file boss_drakos.cpp.
 {}
KilledUnit()
void boss_drakos::boss_drakosAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 118 of file boss_drakos.cpp.
         {
             Talk(SAY_KILL);
         }
References SAY_KILL, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_drakos::boss_drakosAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 123 of file boss_drakos.cpp.
 {}
Reset()
void boss_drakos::boss_drakosAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 78 of file boss_drakos.cpp.
         {
             if (pInstance)
                 pInstance->SetData(DATA_DRAKOS, NOT_STARTED);
             events.Reset();
         }
References DATA_DRAKOS, NOT_STARTED, pInstance, and ZoneScript::SetData().
UpdateAI()
void boss_drakos::boss_drakosAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 126 of file boss_drakos.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             DoMeleeAttackIfReady();
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_MAGIC_PULL:
                     {
                         Talk(SAY_PULL);
                         //me->TextEmote(TEXT_MAGIC_PULL, nullptr, true);
                         me->CastSpell(me, SPELL_MAGIC_PULL, false);
                         events.RepeatEvent(urand(15000, 25000));
                         events.ScheduleEvent(EVENT_SUMMON_x4, 1500);
                     }
                     break;
                 case EVENT_THUNDERING_STOMP:
                     {
                         Talk(SAY_STOMP);
                         me->CastSpell(me, SPELL_THUNDERING_STOMP, false);
                         events.RepeatEvent(urand(10000, 20000));
                     }
                     break;
                 case EVENT_SUMMON:
                     {
                         for( uint8 i = 0; i < 2; ++i )
{
                             float angle = rand_norm() * 2 * M_PI;
                             me->SummonCreature(NPC_UNSTABLE_SPHERE, me->GetPositionX() + 5.0f * cos(angle), me->GetPositionY() + 5.0f * sin(angle), me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 18000);
                         }
                         events.RepeatEvent(2000);
                     }
                     break;
                 case EVENT_SUMMON_x4:
                     for( uint8 i = 0; i < 4; ++i )
                     {
                         float angle = rand_norm() * 2 * M_PI;
                         me->SummonCreature(NPC_UNSTABLE_SPHERE, me->GetPositionX() + 5.0f * cos(angle), me->GetPositionY() + 5.0f * sin(angle), me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 18000);
                     }
                     break;
             }
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_MAGIC_PULL, EVENT_SUMMON, EVENT_SUMMON_x4, EVENT_THUNDERING_STOMP, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasUnitState(), ScriptedAI::me, NPC_UNSTABLE_SPHERE, rand_norm(), SAY_PULL, SAY_STOMP, SPELL_MAGIC_PULL, SPELL_THUNDERING_STOMP, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_drakos::boss_drakosAI::events
Definition at line 76 of file boss_drakos.cpp.
pInstance
InstanceScript* boss_drakos::boss_drakosAI::pInstance
Definition at line 75 of file boss_drakos.cpp.
Referenced by boss_drakosAI(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Oculus/boss_drakos.cpp