Azerotcore-wotlk: G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle Class Reference
G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle Class Reference
#include <PointKDTree.h>
Public Member Functions
Handle ()
Handle (const T &v)
void setPosition (const Vector3 &v)
const Vector3 & position () const
Public Attributes
T value
Private Attributes
Vector3 m_position
Detailed Description
template<class T, class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>>
class G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle
Definition at line 110 of file PointKDTree.h.
Constructor & Destructor Documentation
Handle() [1/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::Handle () inline
Definition at line 117 of file PointKDTree.h.
 {}
Handle() [2/2]
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::Handle (const T & v) inline
Definition at line 118 of file PointKDTree.h.
                                   : value(v) {
             PositionFunc::getPosition(v, m_position);
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::m_position.
Member Function Documentation
position()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> const Vector3& G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::position () const inline
Definition at line 127 of file PointKDTree.h.
{
             return m_position;
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::m_position.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::AxisComparator::operator()().
setPosition()
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> void G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::setPosition (const Vector3 & v) inline
Used by makeNode to create fake handles for partitioning.
Definition at line 123 of file PointKDTree.h.
{
             m_position = v;
         }
References G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::m_position.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode().
Member Data Documentation
m_position
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Vector3 G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::m_position private
Definition at line 112 of file PointKDTree.h.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::Handle(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::position(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::setPosition().
value
template<class T , class PositionFunc = PositionTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> T G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Handle::value
Definition at line 115 of file PointKDTree.h.
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointKDTree.h