Azerotcore-wotlk: instance_molten_core::instance_molten_core_InstanceMapScript Struct Reference
instance_molten_core::instance_molten_core_InstanceMapScript Struct Reference
Public Member Functions
instance_molten_core_InstanceMapScript (Map *map)
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
ObjectGuid GetGuidData (uint32 type) const override
bool SetBossState (uint32 bossId, EncounterState state) override
void DoAction (int32 action) override
void SummonMajordomoExecutus ()
bool CheckMajordomoExecutus () const
std::string GetSaveData () override
void Load (char const *data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
std::unordered_map< uint32, ObjectGuid > _circlesGUIDs
std::unordered_map< uint32, ObjectGuid > _runesGUIDs
ObjectGuid _golemaggGUID
GuidSet _golemaggMinionsGUIDS
ObjectGuid _ragnarosGUID
ObjectGuid _lavaSteamGUID
ObjectGuid _lavaSplashGUID
ObjectGuid _majordomoExecutusGUID
ObjectGuid _cacheOfTheFirelordGUID
ObjectGuid _garrGUID
ObjectGuid _magmadarGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 62 of file instance_molten_core.cpp.
Constructor & Destructor Documentation
instance_molten_core_InstanceMapScript()
instance_molten_core::instance_molten_core_InstanceMapScript::instance_molten_core_InstanceMapScript (Map * map) inline
Definition at line 64 of file instance_molten_core.cpp.
                                                          : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTER);
             LoadMinionData(minionData);
         }
References InstanceScript::LoadMinionData(), MAX_ENCOUNTER, minionData, and InstanceScript::SetBossNumber().
Member Function Documentation
CheckMajordomoExecutus()
bool instance_molten_core::instance_molten_core_InstanceMapScript::CheckMajordomoExecutus () const inline
Definition at line 357 of file instance_molten_core.cpp.
         {
             if (GetBossState(DATA_RAGNAROS) == DONE)
             {
                 return false;
             }
             for (uint8 i = 0; i < DATA_MAJORDOMO_EXECUTUS; ++i)
             {
                 if (i == DATA_LUCIFRON)
                 {
                     continue;
                 }
                 if (GetBossState(i) != DONE)
                 {
                     return false;
                 }
             }
             // Prevent spawning if Ragnaros is present
             if (instance->GetCreature(_ragnarosGUID))
             {
                 return false;
             }
             return true;
         }
References _ragnarosGUID, DATA_LUCIFRON, DATA_MAJORDOMO_EXECUTUS, DATA_RAGNAROS, DONE, InstanceScript::GetBossState(), Map::GetCreature(), and InstanceScript::instance.
Referenced by Load(), OnPlayerEnter(), and SetBossState().
DoAction()
void instance_molten_core::instance_molten_core_InstanceMapScript::DoAction (int32 action) inline override virtual
Reimplemented from InstanceScript.
Definition at line 325 of file instance_molten_core.cpp.
         {
             if (action == ACTION_RESET_GOLEMAGG_ENCOUNTER)
             {
                 if (Creature* golemagg = instance->GetCreature(_golemaggGUID))
                 {
                     golemagg->AI()->EnterEvadeMode();
                 }
                 if (!_golemaggMinionsGUIDS.empty())
                 {
                     for (ObjectGuid const& minionGuid : _golemaggMinionsGUIDS)
                     {
                         if (Creature* minion = instance->GetCreature(minionGuid))
{
                             minion->AI()->EnterEvadeMode();
                         }
                     }
                 }
             }
         }
References _golemaggGUID, _golemaggMinionsGUIDS, ACTION_RESET_GOLEMAGG_ENCOUNTER, Map::GetCreature(), and InstanceScript::instance.
GetGuidData()
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 216 of file instance_molten_core.cpp.
         {
             switch (type)
             {
                 case DATA_GOLEMAGG:
                     return _golemaggGUID;
                 case DATA_MAJORDOMO_EXECUTUS:
                     return _majordomoExecutusGUID;
                 case DATA_GARR:
                     return _garrGUID;
                 case DATA_LAVA_STEAM:
                     return _lavaSteamGUID;
                 case DATA_LAVA_SPLASH:
                     return _lavaSplashGUID;
                 case DATA_RAGNAROS:
                     return _ragnarosGUID;
             }
             return ObjectGuid::Empty;
         }
References _garrGUID, _golemaggGUID, _lavaSplashGUID, _lavaSteamGUID, _majordomoExecutusGUID, _ragnarosGUID, DATA_GARR, DATA_GOLEMAGG, DATA_LAVA_SPLASH, DATA_LAVA_STEAM, DATA_MAJORDOMO_EXECUTUS, DATA_RAGNAROS, and ObjectGuid::Empty.
GetSaveData()
std::string instance_molten_core::instance_molten_core_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 386 of file instance_molten_core.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "M C " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_molten_core::instance_molten_core_InstanceMapScript::Load (char const * data) inline override virtual
Reimplemented from InstanceScript.
Definition at line 397 of file instance_molten_core.cpp.
         {
             if (!data)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(data);
             char dataHead1, dataHead2;
             std::istringstream loadStream(data);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'M' && dataHead2 == 'C')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > TO_BE_DECIDED)
                     {
                         tmpState = NOT_STARTED;
                     }
                     SetBossState(i, static_cast<EncounterState>(tmpState));
                 }
                 if (CheckMajordomoExecutus())
                 {
                     SummonMajordomoExecutus();
                 }
             }
             else
             {
                 OUT_LOAD_INST_DATA_FAIL;
             }
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References CheckMajordomoExecutus(), IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), SummonMajordomoExecutus(), and TO_BE_DECIDED.
OnCreatureCreate()
void instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 78 of file instance_molten_core.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_GOLEMAGG_THE_INCINERATOR:
                 {
                     _golemaggGUID = creature->GetGUID();
                     break;
                 }
                 case NPC_CORE_RAGER:
                 {
                     _golemaggMinionsGUIDS.insert(creature->GetGUID());
                     break;
                 }
                 case NPC_MAJORDOMO_EXECUTUS:
                 {
                     _majordomoExecutusGUID = creature->GetGUID();
                     break;
                 }
                 case NPC_GARR:
                 {
                     _garrGUID = creature->GetGUID();
                     break;
                 }
                 case NPC_RAGNAROS:
                 {
                     _ragnarosGUID = creature->GetGUID();
                     break;
                 }
                 case NPC_FIRESWORN:
                 case NPC_FLAMEWALKER:
                 case NPC_FLAMEWALKER_PROTECTOR:
                 case NPC_FLAMEWALKER_PRIEST:
                 case NPC_FLAMEWALKER_HEALER:
                 case NPC_FLAMEWALKER_ELITE:
                 {
                     AddMinion(creature, true);
                     break;
                 }
             }
         }
References _garrGUID, _golemaggGUID, _golemaggMinionsGUIDS, _majordomoExecutusGUID, _ragnarosGUID, InstanceScript::AddMinion(), Object::GetEntry(), Object::GetGUID(), NPC_CORE_RAGER, NPC_FIRESWORN, NPC_FLAMEWALKER, NPC_FLAMEWALKER_ELITE, NPC_FLAMEWALKER_HEALER, NPC_FLAMEWALKER_PRIEST, NPC_FLAMEWALKER_PROTECTOR, NPC_GARR, NPC_GOLEMAGG_THE_INCINERATOR, NPC_MAJORDOMO_EXECUTUS, and NPC_RAGNAROS.
OnCreatureRemove()
void instance_molten_core::instance_molten_core_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 120 of file instance_molten_core.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_FIRESWORN:
                 {
                     AddMinion(creature, false);
                     break;
                 }
                 case NPC_FLAMEWALKER:
                 case NPC_FLAMEWALKER_PROTECTOR:
                 case NPC_FLAMEWALKER_PRIEST:
                 case NPC_FLAMEWALKER_HEALER:
                 case NPC_FLAMEWALKER_ELITE:
                 {
                     AddMinion(creature, false);
                     break;
                 }
             }
         }
References InstanceScript::AddMinion(), Object::GetEntry(), NPC_FIRESWORN, NPC_FLAMEWALKER, NPC_FLAMEWALKER_ELITE, NPC_FLAMEWALKER_HEALER, NPC_FLAMEWALKER_PRIEST, and NPC_FLAMEWALKER_PROTECTOR.
OnGameObjectCreate()
void instance_molten_core::instance_molten_core_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 141 of file instance_molten_core.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_CACHE_OF_THE_FIRELORD:
                 {
                     _cacheOfTheFirelordGUID = go->GetGUID();
                     break;
                 }
                 case GO_CIRCLE_GEDDON:
                 case GO_CIRCLE_GARR:
                 case GO_CIRCLE_GEHENNAS:
                 case GO_CIRCLE_GOLEMAGG:
                 case GO_CIRCLE_MAGMADAR:
                 case GO_CIRCLE_SHAZZRAH:
                 case GO_CIRCLE_SULFURON:
                 {
                     for (uint8 i = 0; i < MAX_MC_LINKED_BOSS_OBJ; ++i)
                     {
                         if (linkedBossObjData[i].circleId != go->GetEntry())
{
                             continue;
                         }
                         if (GetBossState(linkedBossObjData[i].bossId) == DONE)
{
                             go->DespawnOrUnsummon();
                         }
                         else
{
                             _circlesGUIDs[linkedBossObjData[i].bossId] = go->GetGUID();
                         }
                     }
                     break;
                 }
                 case GO_RUNE_KRESS:
                 case GO_RUNE_MOHN:
                 case GO_RUNE_BLAZ:
                 case GO_RUNE_MAZJ:
                 case GO_RUNE_ZETH:
                 case GO_RUNE_THERI:
                 case GO_RUNE_KORO:
                 {
                     for (uint8 i = 0; i < MAX_MC_LINKED_BOSS_OBJ; ++i)
                     {
                         if (linkedBossObjData[i].runeId != go->GetEntry())
{
                             continue;
                         }
                         if (GetBossState(linkedBossObjData[i].bossId) == DONE)
{
                             go->SetGoState(GO_STATE_ACTIVE);
                         }
                         else
{
                             _runesGUIDs[linkedBossObjData[i].bossId] = go->GetGUID();
                         }
                     }
                     break;
                 }
                 case GO_LAVA_STEAM:
                 {
                     _lavaSteamGUID = go->GetGUID();
                     break;
                 }
                 case GO_LAVA_SPLASH:
                 {
                     _lavaSplashGUID = go->GetGUID();
                     break;
                 }
             }
         }
References _cacheOfTheFirelordGUID, _circlesGUIDs, _lavaSplashGUID, _lavaSteamGUID, _runesGUIDs, MCBossObject::bossId, GameObject::DespawnOrUnsummon(), DONE, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_CACHE_OF_THE_FIRELORD, GO_CIRCLE_GARR, GO_CIRCLE_GEDDON, GO_CIRCLE_GEHENNAS, GO_CIRCLE_GOLEMAGG, GO_CIRCLE_MAGMADAR, GO_CIRCLE_SHAZZRAH, GO_CIRCLE_SULFURON, GO_LAVA_SPLASH, GO_LAVA_STEAM, GO_RUNE_BLAZ, GO_RUNE_KORO, GO_RUNE_KRESS, GO_RUNE_MAZJ, GO_RUNE_MOHN, GO_RUNE_THERI, GO_RUNE_ZETH, GO_STATE_ACTIVE, linkedBossObjData, MAX_MC_LINKED_BOSS_OBJ, and GameObject::SetGoState().
OnPlayerEnter()
void instance_molten_core::instance_molten_core_InstanceMapScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
Definition at line 70 of file instance_molten_core.cpp.
         {
             if (CheckMajordomoExecutus())
             {
                 SummonMajordomoExecutus();
             }
         }
References CheckMajordomoExecutus(), and SummonMajordomoExecutus().
SetBossState()
bool instance_molten_core::instance_molten_core_InstanceMapScript::SetBossState (uint32 bossId, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 237 of file instance_molten_core.cpp.
         {
             if (!InstanceScript::SetBossState(bossId, state))
             {
                 return false;
             }
             if (bossId == DATA_MAJORDOMO_EXECUTUS && state == DONE)
             {
                 DoRespawnGameObject(_cacheOfTheFirelordGUID, 7 * DAY);
             }
             else if (bossId == DATA_GOLEMAGG)
             {
                 switch (state)
                 {
                     case NOT_STARTED:
                     case FAIL:
                     {
                         if (!_golemaggMinionsGUIDS.empty())
{
                             for (ObjectGuid const& minionGuid : _golemaggMinionsGUIDS)
{
                                 Creature* minion = instance->GetCreature(minionGuid);
                                 if (minion && minion->isDead())
{
                                     minion->Respawn();
                                 }
                             }
                         }
                         break;
                     }
                     case IN_PROGRESS:
                     {
                         if (!_golemaggMinionsGUIDS.empty())
{
                             for (ObjectGuid const& minionGuid : _golemaggMinionsGUIDS)
{
                                 if (Creature* minion = instance->GetCreature(minionGuid))
{
                                     minion->AI()->DoZoneInCombat(nullptr, 150.0f);
                                 }
                             }
                         }
                         break;
                     }
                     case DONE:
                     {
                         if (!_golemaggMinionsGUIDS.empty())
{
                             for (ObjectGuid const& minionGuid : _golemaggMinionsGUIDS)
{
                                 if (Creature* minion = instance->GetCreature(minionGuid))
{
                                     minion->CastSpell(minion, SPELL_CORE_RAGER_QUIET_SUICIDE, true);
                                 }
                             }
                             _golemaggMinionsGUIDS.clear();
                         }
                         break;
                     }
                     default:
                         break;
                 }
             }
             // Perform needed checks for Majordomu
             if (bossId < DATA_MAJORDOMO_EXECUTUS && state == DONE)
             {
                 if (GameObject* circle = instance->GetGameObject(_circlesGUIDs[bossId]))
                 {
                     circle->DespawnOrUnsummon();
                     _circlesGUIDs[bossId].Clear();
                 }
                 if (GameObject* rune = instance->GetGameObject(_runesGUIDs[bossId]))
                 {
                     rune->SetGoState(GO_STATE_ACTIVE);
                     _runesGUIDs[bossId].Clear();
                 }
                 if (CheckMajordomoExecutus())
                 {
                     SummonMajordomoExecutus();
                 }
             }
             return true;
         }
References _cacheOfTheFirelordGUID, _circlesGUIDs, _golemaggMinionsGUIDS, _runesGUIDs, CheckMajordomoExecutus(), DATA_GOLEMAGG, DATA_MAJORDOMO_EXECUTUS, DAY, DONE, InstanceScript::DoRespawnGameObject(), FAIL, Map::GetCreature(), Map::GetGameObject(), GO_STATE_ACTIVE, IN_PROGRESS, InstanceScript::instance, Unit::isDead(), NOT_STARTED, Creature::Respawn(), InstanceScript::SetBossState(), SPELL_CORE_RAGER_QUIET_SUICIDE, and SummonMajordomoExecutus().
Referenced by Load().
SummonMajordomoExecutus()
void instance_molten_core::instance_molten_core_InstanceMapScript::SummonMajordomoExecutus () inline
Definition at line 347 of file instance_molten_core.cpp.
         {
             if (instance->GetCreature(_majordomoExecutusGUID))
             {
                 return;
             }
             instance->SummonCreature(NPC_MAJORDOMO_EXECUTUS, GetBossState(DATA_MAJORDOMO_EXECUTUS) != DONE ? MajordomoSummonPos : MajordomoRagnaros);
         }
References _majordomoExecutusGUID, DATA_MAJORDOMO_EXECUTUS, DONE, InstanceScript::GetBossState(), Map::GetCreature(), InstanceScript::instance, MajordomoRagnaros, MajordomoSummonPos, NPC_MAJORDOMO_EXECUTUS, and Map::SummonCreature().
Referenced by Load(), OnPlayerEnter(), and SetBossState().
Member Data Documentation
_cacheOfTheFirelordGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_cacheOfTheFirelordGUID private
Definition at line 453 of file instance_molten_core.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
_circlesGUIDs
std::unordered_map<uint32, ObjectGuid> instance_molten_core::instance_molten_core_InstanceMapScript::_circlesGUIDs private
Definition at line 440 of file instance_molten_core.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
_garrGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_garrGUID private
Definition at line 454 of file instance_molten_core.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_golemaggGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_golemaggGUID private
Definition at line 444 of file instance_molten_core.cpp.
Referenced by DoAction(), GetGuidData(), and OnCreatureCreate().
_golemaggMinionsGUIDS
GuidSet instance_molten_core::instance_molten_core_InstanceMapScript::_golemaggMinionsGUIDS private
Definition at line 445 of file instance_molten_core.cpp.
Referenced by DoAction(), OnCreatureCreate(), and SetBossState().
_lavaSplashGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_lavaSplashGUID private
Definition at line 450 of file instance_molten_core.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
_lavaSteamGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_lavaSteamGUID private
Definition at line 449 of file instance_molten_core.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
_magmadarGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_magmadarGUID private
Definition at line 455 of file instance_molten_core.cpp.
_majordomoExecutusGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_majordomoExecutusGUID private
Definition at line 452 of file instance_molten_core.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SummonMajordomoExecutus().
_ragnarosGUID
ObjectGuid instance_molten_core::instance_molten_core_InstanceMapScript::_ragnarosGUID private
Definition at line 448 of file instance_molten_core.cpp.
Referenced by CheckMajordomoExecutus(), GetGuidData(), and OnCreatureCreate().
_runesGUIDs
std::unordered_map<uint32, ObjectGuid> instance_molten_core::instance_molten_core_InstanceMapScript::_runesGUIDs private
Definition at line 441 of file instance_molten_core.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp