Azerotcore-wotlk: GlobalCooldownMgr Class Reference
GlobalCooldownMgr Class Reference
#include <Unit.h>
Public Member Functions
GlobalCooldownMgr ()=default
bool HasGlobalCooldown (SpellInfo const *spellInfo) const
void AddGlobalCooldown (SpellInfo const *spellInfo, uint32 gcd)
void CancelGlobalCooldown (SpellInfo const *spellInfo)
Private Attributes
GlobalCooldownList m_GlobalCooldowns
Detailed Description
Definition at line 1125 of file Unit.h.
Constructor & Destructor Documentation
GlobalCooldownMgr()
GlobalCooldownMgr::GlobalCooldownMgr () default
Member Function Documentation
AddGlobalCooldown()
void GlobalCooldownMgr::AddGlobalCooldown (SpellInfo const * spellInfo, uint32 gcd)
Definition at line 329 of file Unit.cpp.
 {
     m_GlobalCooldowns[spellInfo->StartRecoveryCategory] = GlobalCooldown(gcd, World::GetGameTimeMS());
 }
References World::GetGameTimeMS(), m_GlobalCooldowns, and SpellInfo::StartRecoveryCategory.
Referenced by Player::EquipItem(), and Spell::TriggerGlobalCooldown().
CancelGlobalCooldown()
void GlobalCooldownMgr::CancelGlobalCooldown (SpellInfo const * spellInfo)
Definition at line 334 of file Unit.cpp.
 {
     m_GlobalCooldowns[spellInfo->StartRecoveryCategory].duration = 0;
 }
References m_GlobalCooldowns, and SpellInfo::StartRecoveryCategory.
Referenced by Spell::CancelGlobalCooldown().
HasGlobalCooldown()
bool GlobalCooldownMgr::HasGlobalCooldown (SpellInfo const * spellInfo) const
Definition at line 323 of file Unit.cpp.
 {
     GlobalCooldownList::const_iterator itr = m_GlobalCooldowns.find(spellInfo->StartRecoveryCategory);
     return itr != m_GlobalCooldowns.end() && itr->second.duration && getMSTimeDiff(itr->second.cast_time, World::GetGameTimeMS()) < itr->second.duration;
 }
References World::GetGameTimeMS(), getMSTimeDiff(), m_GlobalCooldowns, and SpellInfo::StartRecoveryCategory.
Referenced by Spell::CheckPetCast(), Spell::HasGlobalCooldown(), and PetAI::UpdateAI().
Member Data Documentation
m_GlobalCooldowns
GlobalCooldownList GlobalCooldownMgr::m_GlobalCooldowns private
Definition at line 1136 of file Unit.h.
Referenced by AddGlobalCooldown(), CancelGlobalCooldown(), and HasGlobalCooldown().
The documentation for this class was generated from the following files:
src/server/game/Entities/Unit/Unit.h
src/server/game/Entities/Unit/Unit.cpp