Azerotcore-wotlk: dtQueryFilter Class Reference
dtQueryFilter Class Reference
Detour
#include <DetourNavMeshQuery.h>
Public Member Functions
dtQueryFilter ()
virtual ~dtQueryFilter ()
virtual bool passFilter (const dtPolyRef ref, const dtMeshTile *tile, const dtPoly *poly) const
virtual float getCost (const float *pa, const float *pb, const dtPolyRef prevRef, const dtMeshTile *prevTile, const dtPoly *prevPoly, const dtPolyRef curRef, const dtMeshTile *curTile, const dtPoly *curPoly, const dtPolyRef nextRef, const dtMeshTile *nextTile, const dtPoly *nextPoly) const
Getters and setters for the default implementation data.
float getAreaCost (const int i) const
void setAreaCost (const int i, const float cost)
unsigned short getIncludeFlags () const
void setIncludeFlags (const unsigned short flags)
unsigned short getExcludeFlags () const
void setExcludeFlags (const unsigned short flags)
Private Attributes
float m_areaCost [DT_MAX_AREAS]
Cost per area type. (Used by default implementation.)
unsigned short m_includeFlags
Flags for polygons that can be visited. (Used by default implementation.)
unsigned short m_excludeFlags
Flags for polygons that should not be visted. (Used by default implementation.)
Detailed Description
Defines polygon filtering and traversal costs for navigation mesh query operations.
The Default Implementation
At construction: All area costs default to 1.0. All flags are included and none are excluded.
If a polygon has both an include and an exclude flag, it will be excluded.
The way filtering works, a navigation mesh polygon must have at least one flag set to ever be considered by a query. So a polygon with no flags will never be considered.
Setting the include flags to 0 will result in all polygons being excluded.
Custom Implementations
DT_VIRTUAL_QUERYFILTER must be defined in order to extend this class.
Implement a custom query filter by overriding the virtual passFilter() and getCost() functions. If this is done, both functions should be as fast as possible. Use cached local copies of data rather than accessing your own objects where possible.
Custom implementations do not need to adhere to the flags or cost logic used by the default implementation.
In order for A* searches to work properly, the cost should be proportional to the travel distance. Implementing a cost modifier less than 1.0 is likely to lead to problems during pathfinding.
See also
dtNavMeshQuery
Definition at line 35 of file DetourNavMeshQuery.h.
Constructor & Destructor Documentation
dtQueryFilter()
dtQueryFilter::dtQueryFilter ()
Definition at line 63 of file DetourNavMeshQuery.cpp.
                              :
     m_includeFlags(0xffff),
     m_excludeFlags(0)
 {
     for (int i = 0; i < DT_MAX_AREAS; ++i)
         m_areaCost[i] = 1.0f;
 }
References DT_MAX_AREAS, and m_areaCost.
~dtQueryFilter()
virtual dtQueryFilter::~dtQueryFilter () inline virtual
Definition at line 45 of file DetourNavMeshQuery.h.
 { }
Member Function Documentation
getAreaCost()
float dtQueryFilter::getAreaCost (const int i) const inline
Returns the traversal cost of the area.
Parameters
[in] i The id of the area.
Returns
The traversal cost of the area.
Definition at line 93 of file DetourNavMeshQuery.h.
 { return m_areaCost[i]; }
References m_areaCost.
Referenced by dtQueryFilterExt::getCost().
getCost()
float dtQueryFilter::getCost (const float * pa, const float * pb, const dtPolyRef prevRef, const dtMeshTile * prevTile, const dtPoly * prevPoly, const dtPolyRef curRef, const dtMeshTile * curTile, const dtPoly * curPoly, const dtPolyRef nextRef, const dtMeshTile * nextTile, const dtPoly * nextPoly) const inline virtual
Returns cost to move from the beginning to the end of a line segment that is fully contained within a polygon.
Parameters
[in] pa The start position on the edge of the previous and current polygon. [(x, y, z)]
[in] pb The end position on the edge of the current and next polygon. [(x, y, z)]
[in] prevRef The reference id of the previous polygon. [opt]
[in] prevTile The tile containing the previous polygon. [opt]
[in] prevPoly The previous polygon. [opt]
[in] curRef The reference id of the current polygon.
[in] curTile The tile containing the current polygon.
[in] curPoly The current polygon.
[in] nextRef The refernece id of the next polygon. [opt]
[in] nextTile The tile containing the next polygon. [opt]
[in] nextPoly The next polygon. [opt]
Reimplemented in dtQueryFilterExt.
Definition at line 94 of file DetourNavMeshQuery.cpp.
 {
     return dtVdist(pa, pb) * m_areaCost[curPoly->getArea()];
 }
References dtVdist(), dtPoly::getArea(), and m_areaCost.
Referenced by dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::raycast(), and dtNavMeshQuery::updateSlicedFindPath().
getExcludeFlags()
unsigned short dtQueryFilter::getExcludeFlags () const inline
Returns the exclude flags for the filter. Any polygons that include one ore more of these flags will be excluded from the operation.
Definition at line 112 of file DetourNavMeshQuery.h.
 { return m_excludeFlags; }
References m_excludeFlags.
getIncludeFlags()
unsigned short dtQueryFilter::getIncludeFlags () const inline
Returns the include flags for the filter. Any polygons that include one or more of these flags will be included in the operation.
Definition at line 103 of file DetourNavMeshQuery.h.
 { return m_includeFlags; }
References m_includeFlags.
Referenced by PathGenerator::UpdateFilter().
passFilter()
bool dtQueryFilter::passFilter (const dtPolyRef ref, const dtMeshTile * tile, const dtPoly * poly) const inline virtual
Returns true if the polygon can be visited. (I.e. Is traversable.)
Parameters
[in] ref The reference id of the polygon test.
[in] tile The tile containing the polygon.
[in] poly The polygon to test.
Definition at line 87 of file DetourNavMeshQuery.cpp.
 {
     return (poly->flags & m_includeFlags) != 0 && (poly->flags & m_excludeFlags) == 0;
 }
References dtPoly::flags, m_excludeFlags, and m_includeFlags.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPoint(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::isValidPolyRef(), dtNavMeshQuery::moveAlongSurface(), dtNavMeshQuery::queryPolygonsInTile(), dtNavMeshQuery::raycast(), and dtNavMeshQuery::updateSlicedFindPath().
setAreaCost()
void dtQueryFilter::setAreaCost (const int i, const float cost) inline
Sets the traversal cost of the area.
Parameters
[in] i The id of the area.
[in] cost The new cost of traversing the area.
Definition at line 98 of file DetourNavMeshQuery.h.
 { m_areaCost[i] = cost; }
References m_areaCost.
setExcludeFlags()
void dtQueryFilter::setExcludeFlags (const unsigned short flags) inline
Sets the exclude flags for the filter.
Parameters
[in] flags The new flags.
Definition at line 116 of file DetourNavMeshQuery.h.
 { m_excludeFlags = flags; }
References m_excludeFlags.
Referenced by PathGenerator::CreateFilter(), and main().
setIncludeFlags()
void dtQueryFilter::setIncludeFlags (const unsigned short flags) inline
Sets the include flags for the filter.
Parameters
[in] flags The new flags.
Definition at line 107 of file DetourNavMeshQuery.h.
 { m_includeFlags = flags; }
References m_includeFlags.
Referenced by PathGenerator::CreateFilter(), main(), and PathGenerator::UpdateFilter().
Member Data Documentation
m_areaCost
float dtQueryFilter::m_areaCost[DT_MAX_AREAS] private
Cost per area type. (Used by default implementation.)
Definition at line 37 of file DetourNavMeshQuery.h.
Referenced by dtQueryFilter(), getAreaCost(), getCost(), and setAreaCost().
m_excludeFlags
unsigned short dtQueryFilter::m_excludeFlags private
Flags for polygons that should not be visted. (Used by default implementation.)
Definition at line 39 of file DetourNavMeshQuery.h.
Referenced by getExcludeFlags(), passFilter(), and setExcludeFlags().
m_includeFlags
unsigned short dtQueryFilter::m_includeFlags private
Flags for polygons that can be visited. (Used by default implementation.)
Definition at line 38 of file DetourNavMeshQuery.h.
Referenced by getIncludeFlags(), passFilter(), and setIncludeFlags().
The documentation for this class was generated from the following files:
deps/recastnavigation/Detour/Include/DetourNavMeshQuery.h
deps/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp