Azerotcore-wotlk: instance_ahnkahet::instance_ahnkahet_InstanceScript Struct Reference
instance_ahnkahet::instance_ahnkahet_InstanceScript Struct Reference
Public Member Functions
instance_ahnkahet_InstanceScript (Map *pMap)
void OnCreatureCreate (Creature *pCreature) override
void OnGameObjectCreate (GameObject *pGo) override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 type) const override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Member Functions
bool IsAllSpheresActivated () const
Private Attributes
ObjectGuid elderNadox_GUID
ObjectGuid princeTaldaram_GUID
ObjectGuid jedogaShadowseeker_GUID
ObjectGuid heraldVolazj_GUID
ObjectGuid amanitar_GUID
ObjectGuid taldaramPlatform_GUID
ObjectGuid taldaramGate_GUID
std::array< uint32, 2 > teldaramSpheres
bool canSaveBossStates
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 30 of file instance_ahnkahet.cpp.
Constructor & Destructor Documentation
instance_ahnkahet_InstanceScript()
instance_ahnkahet::instance_ahnkahet_InstanceScript::instance_ahnkahet_InstanceScript (Map * pMap) inline
Definition at line 32 of file instance_ahnkahet.cpp.
                                                     : InstanceScript(pMap), canSaveBossStates(false)
         {
             SetBossNumber(MAX_ENCOUNTER);
             teldaramSpheres.fill(NOT_STARTED);
         }
References MAX_ENCOUNTER, NOT_STARTED, InstanceScript::SetBossNumber(), and teldaramSpheres.
Member Function Documentation
GetData()
uint32 instance_ahnkahet::instance_ahnkahet_InstanceScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 143 of file instance_ahnkahet.cpp.
         {
             switch (type)
             {
                 case DATA_TELDRAM_SPHERE1:
                     return teldaramSpheres.at(0);
                 case DATA_TELDRAM_SPHERE2:
                     return teldaramSpheres.at(1);
             }
             return 0;
         }
References DATA_TELDRAM_SPHERE1, DATA_TELDRAM_SPHERE2, and teldaramSpheres.
GetGuidData()
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 156 of file instance_ahnkahet.cpp.
         {
             switch (type)
             {
                 case DATA_ELDER_NADOX:
                     return elderNadox_GUID;
                 case DATA_PRINCE_TALDARAM:
                     return princeTaldaram_GUID;
                 case DATA_JEDOGA_SHADOWSEEKER:
                     return jedogaShadowseeker_GUID;
                 case DATA_HERALD_VOLAZJ:
                     return heraldVolazj_GUID;
                 case DATA_AMANITAR:
                     return amanitar_GUID;
             }
             return ObjectGuid::Empty;
         }
References amanitar_GUID, DATA_AMANITAR, DATA_ELDER_NADOX, DATA_HERALD_VOLAZJ, DATA_JEDOGA_SHADOWSEEKER, DATA_PRINCE_TALDARAM, elderNadox_GUID, ObjectGuid::Empty, heraldVolazj_GUID, jedogaShadowseeker_GUID, and princeTaldaram_GUID.
GetSaveData()
std::string instance_ahnkahet::instance_ahnkahet_InstanceScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 175 of file instance_ahnkahet.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             // Encounter states
             saveStream << "A K " << GetBossSaveData();
             // Extra data
             saveStream << teldaramSpheres[0] << ' ' << teldaramSpheres[1];
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and teldaramSpheres.
IsAllSpheresActivated()
bool instance_ahnkahet::instance_ahnkahet_InstanceScript::IsAllSpheresActivated () const inline private
Definition at line 246 of file instance_ahnkahet.cpp.
         {
             return teldaramSpheres.at(0) == DONE && teldaramSpheres.at(1) == DONE;
         }
References DONE, and teldaramSpheres.
Referenced by OnGameObjectCreate(), and SetData().
Load()
void instance_ahnkahet::instance_ahnkahet_InstanceScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 190 of file instance_ahnkahet.cpp.
         {
             if (!in)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'A' && dataHead2 == 'K')
             {
                 // Encounter states
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                     {
                         tmpState = NOT_STARTED;
                     }
                     SetBossState(i, EncounterState(tmpState));
                 }
                 // Extra data
                 loadStream >> teldaramSpheres[0] >> teldaramSpheres[1];
             }
             else
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             canSaveBossStates = true;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References canSaveBossStates, IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), SPECIAL, and teldaramSpheres.
OnCreatureCreate()
void instance_ahnkahet::instance_ahnkahet_InstanceScript::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 38 of file instance_ahnkahet.cpp.
         {
             switch (pCreature->GetEntry())
             {
                 case NPC_ELDER_NADOX:
                     elderNadox_GUID = pCreature->GetGUID();
                     break;
                 case NPC_PRINCE_TALDARAM:
                     princeTaldaram_GUID = pCreature->GetGUID();
                     break;
                 case NPC_JEDOGA_SHADOWSEEKER:
                     jedogaShadowseeker_GUID = pCreature->GetGUID();
                     break;
                 case NPC_HERALD_JOLAZJ:
                     heraldVolazj_GUID = pCreature->GetGUID();
                     break;
                 case NPC_AMANITAR:
                     amanitar_GUID = pCreature->GetGUID();
                     break;
             }
         }
References amanitar_GUID, elderNadox_GUID, Object::GetEntry(), Object::GetGUID(), heraldVolazj_GUID, jedogaShadowseeker_GUID, NPC_AMANITAR, NPC_ELDER_NADOX, NPC_HERALD_JOLAZJ, NPC_JEDOGA_SHADOWSEEKER, NPC_PRINCE_TALDARAM, and princeTaldaram_GUID.
OnGameObjectCreate()
void instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate (GameObject * pGo) inline override virtual
Reimplemented from InstanceScript.
Definition at line 60 of file instance_ahnkahet.cpp.
         {
             switch (pGo->GetEntry())
             {
                 case GO_TELDARAM_PLATFORM:
                 {
                     taldaramPlatform_GUID = pGo->GetGUID();
                     if (IsAllSpheresActivated() || GetBossState(DATA_PRINCE_TALDARAM) == DONE)
                     {
                         HandleGameObject(ObjectGuid::Empty, true, pGo);
                     }
                     break;
                 }
                 case GO_TELDARAM_SPHERE1:
                 case GO_TELDARAM_SPHERE2:
                 {
                     if (teldaramSpheres.at(pGo->GetEntry() == GO_TELDARAM_SPHERE1 ? 0 : 1) == DONE || GetBossState(DATA_PRINCE_TALDARAM) == DONE)
                     {
                         pGo->SetGoState(GO_STATE_ACTIVE);
                         pGo->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     else
                     {
                         pGo->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     break;
                 }
                 case GO_TELDARAM_DOOR:
                 {
                     taldaramGate_GUID = pGo->GetGUID(); // Web gate past Prince Taldaram
                     if (GetBossState(DATA_PRINCE_TALDARAM) == DONE)
                     {
                         HandleGameObject(ObjectGuid::Empty, true, pGo);
                     }
                     break;
                 }
             }
         }
References DATA_PRINCE_TALDARAM, DONE, ObjectGuid::Empty, GAMEOBJECT_FLAGS, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GO_TELDARAM_DOOR, GO_TELDARAM_PLATFORM, GO_TELDARAM_SPHERE1, GO_TELDARAM_SPHERE2, InstanceScript::HandleGameObject(), IsAllSpheresActivated(), Object::RemoveFlag(), Object::SetFlag(), GameObject::SetGoState(), taldaramGate_GUID, taldaramPlatform_GUID, and teldaramSpheres.
SetBossState()
bool instance_ahnkahet::instance_ahnkahet_InstanceScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 102 of file instance_ahnkahet.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
             {
                 return false;
             }
             if (type == DATA_PRINCE_TALDARAM && state == DONE)
             {
                 HandleGameObject(taldaramGate_GUID, true);
             }
             if (canSaveBossStates)
             {
                 SaveToDB();
             }
             return true;
         }
References canSaveBossStates, DATA_PRINCE_TALDARAM, DONE, InstanceScript::HandleGameObject(), InstanceScript::SaveToDB(), InstanceScript::SetBossState(), and taldaramGate_GUID.
Referenced by Load().
SetData()
void instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 122 of file instance_ahnkahet.cpp.
         {
             if (type == DATA_TELDRAM_SPHERE1 || type == DATA_TELDRAM_SPHERE2)
             {
                 teldaramSpheres[type == DATA_TELDRAM_SPHERE1 ? 0 : 1] = data;
                 SaveToDB();
                 if (IsAllSpheresActivated())
                 {
                     HandleGameObject(taldaramPlatform_GUID, true, nullptr);
                     Creature* teldaram = instance->GetCreature(princeTaldaram_GUID);
                     if (teldaram && teldaram->IsAlive())
                     {
                         teldaram->AI()->DoAction(ACTION_REMOVE_PRISON);
                     }
                 }
             }
         }
References ACTION_REMOVE_PRISON, Creature::AI(), DATA_TELDRAM_SPHERE1, DATA_TELDRAM_SPHERE2, UnitAI::DoAction(), Map::GetCreature(), InstanceScript::HandleGameObject(), InstanceScript::instance, Unit::IsAlive(), IsAllSpheresActivated(), princeTaldaram_GUID, InstanceScript::SaveToDB(), taldaramPlatform_GUID, and teldaramSpheres.
Member Data Documentation
amanitar_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::amanitar_GUID private
Definition at line 238 of file instance_ahnkahet.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
canSaveBossStates
bool instance_ahnkahet::instance_ahnkahet_InstanceScript::canSaveBossStates private
Definition at line 244 of file instance_ahnkahet.cpp.
Referenced by Load(), and SetBossState().
elderNadox_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::elderNadox_GUID private
Definition at line 234 of file instance_ahnkahet.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
heraldVolazj_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::heraldVolazj_GUID private
Definition at line 237 of file instance_ahnkahet.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
jedogaShadowseeker_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::jedogaShadowseeker_GUID private
Definition at line 236 of file instance_ahnkahet.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
princeTaldaram_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::princeTaldaram_GUID private
Definition at line 235 of file instance_ahnkahet.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
taldaramGate_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::taldaramGate_GUID private
Definition at line 242 of file instance_ahnkahet.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
taldaramPlatform_GUID
ObjectGuid instance_ahnkahet::instance_ahnkahet_InstanceScript::taldaramPlatform_GUID private
Definition at line 241 of file instance_ahnkahet.cpp.
Referenced by OnGameObjectCreate(), and SetData().
teldaramSpheres
std::array<uint32, 2> instance_ahnkahet::instance_ahnkahet_InstanceScript::teldaramSpheres private
Definition at line 243 of file instance_ahnkahet.cpp.
Referenced by GetData(), GetSaveData(), instance_ahnkahet_InstanceScript(), IsAllSpheresActivated(), Load(), OnGameObjectCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/instance_ahnkahet.cpp