Azerotcore-wotlk: G3D::XML Class Reference
G3D::XML Class Reference
Easy loading and saving of XML and HTML files.
#include <XML.h>
Public Types
enum Type { VALUE , TAG }
typedef Table< std::string, XML > AttributeTable
Public Member Functions
XML ()
XML (const std::string &v)
XML (const double &v)
XML (float v)
XML (int v)
XML (Type tagType, const std::string &name, const AttributeTable &at, const Array< XML > &ch=Array< XML >())
XML (Type tagType, const std::string &name, const Array< XML > &ch=Array< XML >())
XML (TextInput &t)
void serialize (TextOutput &t) const
void deserialize (TextInput &t)
void load (const std::string &filename)
void save (const std::string &filename) const
void parse (const std::string &s)
void unparse (std::string &s) const
const AttributeTable & attributeTable () const
const Array< XML > & childArray () const
int numChildren () const
size_t numAttributes () const
const XML & operator[] (int i) const
const XML & operator[] (const std::string &k) const
bool containsAttribute (const std::string &k) const
XML get (const std::string &k, const XML &defaultVal) const
Type type () const
const std::string name () const
const std::string & string () const
double number () const
bool boolean () const
operator std::string () const
operator bool () const
operator double () const
operator float () const
operator int () const
Private Attributes
Type m_type
std::string m_name
std::string m_value
AttributeTable m_attribute
Array< XML > m_child
Detailed Description
Easy loading and saving of XML and HTML files.
The XML class is intended primarily for interchange with other programs. We recommend using G3D::Any to make your own human-readable formats because it is a more general syntax, the implementation is more efficient, and contains better error handling.
Every XML is either a VALUE, or a TAG that contains both a table of its XML attributes and an array of its children. Children are nested tags and the strings between the nested tags.
No validation is performed, and the XML must be completely legal. XML Entity references (e.g., the ampersand codes for greater than and less than) are not automatically converted.
Tags with names that begin with "!" or "?" are ignored. Comment tags must end with "-->" e.g.,
  <?xml version="1.0" encoding="ISO-8859-1"?>
  <!DOCTYPE note SYSTEM "Note.dtd">
See also
G3D::Any, http://www.grinninglizard.com/tinyxml/
  child0 ...
  ...
  child2 ...
Definition at line 65 of file XML.h.
Member Typedef Documentation
AttributeTable
typedef Table<std::string, XML> G3D::XML::AttributeTable
Definition at line 70 of file XML.h.
Member Enumeration Documentation
Type
enum G3D::XML::Type
Enumerator
VALUE
TAG
Definition at line 68 of file XML.h.
 {VALUE, TAG};
Constructor & Destructor Documentation
XML() [1/8]
G3D::XML::XML () inline
Definition at line 82 of file XML.h.
 : m_type(VALUE) {}
XML() [2/8]
G3D::XML::XML (const std::string & v) inline
Definition at line 84 of file XML.h.
 : m_type(VALUE), m_value(v) {}
XML() [3/8]
G3D::XML::XML (const double & v) inline
Definition at line 86 of file XML.h.
 : m_type(VALUE), m_value(format("%f", v)) {}
XML() [4/8]
G3D::XML::XML (float v) inline
Definition at line 88 of file XML.h.
 : m_type(VALUE), m_value(format("%f", v)) {}
XML() [5/8]
G3D::XML::XML (int v) inline
Definition at line 90 of file XML.h.
 : m_type(VALUE), m_value(format("%d", v)) {}
XML() [6/8]
G3D::XML::XML (Type tagType, const std::string & name, const AttributeTable & at, const Array< XML > & ch = Array<XML>()) inline
Parameters
tagType Must be XML::TAG to dismbiguate from the string constructor
Definition at line 93 of file XML.h.
                                                                                                             : m_type(TAG), m_name(name), m_attribute(at), m_child(ch) {
         (void)tagType;
         debugAssert(tagType == TAG);
     }
References debugAssert, and TAG.
XML() [7/8]
G3D::XML::XML (Type tagType, const std::string & name, const Array< XML > & ch = Array<XML>()) inline
Parameters
tagType Must be XML::TAG to dismbiguate from the string constructor
Definition at line 99 of file XML.h.
                                                                                   : m_type(TAG), m_name(name), m_child(ch) {
         (void)tagType;
         debugAssert(tagType == TAG);
     }
References debugAssert, and TAG.
XML() [8/8]
G3D::XML::XML (TextInput & t)
Definition at line 22 of file XML.cpp.
                      : m_type(VALUE) {
     deserialize(t);
 }
References deserialize().
Member Function Documentation
attributeTable()
const AttributeTable& G3D::XML::attributeTable () const inline
Definition at line 118 of file XML.h.
{
         return m_attribute;
     }
References m_attribute.
boolean()
bool G3D::XML::boolean () const
Returns false if a TAG.
Definition at line 31 of file XML.cpp.
{
     return TextInput::parseBoolean(m_value);
 }
References m_value, and G3D::TextInput::parseBoolean().
Referenced by operator bool().
childArray()
const Array<XML>& G3D::XML::childArray () const inline
Definition at line 122 of file XML.h.
{
         return m_child;
     }
References m_child.
containsAttribute()
bool G3D::XML::containsAttribute (const std::string & k) const inline
Definition at line 147 of file XML.h.
{
         return m_attribute.containsKey(k);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), and m_attribute.
deserialize()
void G3D::XML::deserialize (TextInput & t)
Definition at line 125 of file XML.cpp.
{
  begin:
     Token n = t.read();
     m_attribute.clear();
     m_child.clear();
     m_name = "";
     m_value = "";
     if ((n.type() == Token::SYMBOL) && (n.string() == "<")) {
         // Beginning a tag
         // Read name
         n = t.read();
         debugAssert(n.type() == Token::SYMBOL);
         bool isComment =
             (n.string() == "!") &&
             (t.peek().type() == Token::SYMBOL) &&
             (t.peek().string() == "--");
         // ignored tag:        <?xml> or <!xml>
         // comment tag:        <!--   ... -->
         if ((n.string() == "?") || ((n.string() == "!") && ! isComment)) {
             // Ignore this tag
             while (t.hasMore() && ! ((n.type() == Token::SYMBOL) && (n.string() == ">"))) {
                 n = t.read();
             }
             goto begin;
         } else if (isComment) {
             // Ignore until "-->"
             bool prevWasDash = false;
             while (t.hasMore() && ! ((n.type() == Token::SYMBOL) && (n.string() == ">") && prevWasDash)) {
                 prevWasDash = (n.type() == Token::SYMBOL) && (n.string() == "--");
                 n = t.read();
             }
             goto begin;
         }
         // Keep reading until no colon
         m_name += n.string();
         n = t.read();
         while ((n.type() == Token::SYMBOL) && (n.string() == ":")) {
             //  tag with namespace: <x:y>
             m_name += ":" + t.readSymbol();
             n = t.read();
         }
         // Read end of tag/close
         bool done = false;
         while (! done) {
             debugAssert(n.type() == Token::SYMBOL);
             if (n.string() == "/") {
                 // empty-element tag:  <foo/>
                 // Consume the close tag
                 t.readSymbol(">");
                 done = true;
             } else if (n.string() == ">") {
                 // End of open tag: read children until close tag
                 while (! atClose(t, m_name)) {
                     m_child.next().deserialize(t);
                 }
                 // Read close tag (we wouldn't be here unless it parses correctly)
                 while (t.hasMore() && ! (t.readSymbol() == ">")) {}
                 done = true;
             } else {
                 // Attribute pair
                 std::string k = n.string();
                 t.readSymbol("=");
                 std::string v = t.read().string();
                 m_attribute.set(k, v);
                 // Advance to next
                 n = t.read();
             }
         }
     } else {
         // Beginning embedded content.  Read until the end of file or the next tag.
         m_type = VALUE;
         m_value += n.string();
         n = t.peek();
         while (t.hasMore() && ! ((n.type() == Token::SYMBOL) && (n.string() == "<"))) {
             m_value += " " + t.read().string();
             n = t.peek();
         }
     }
 }
References G3D::atClose(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), debugAssert, detail::digits::done, G3D::TextInput::hasMore(), m_attribute, m_child, m_name, m_type, m_value, G3D::TextInput::peek(), G3D::TextInput::read(), G3D::TextInput::readSymbol(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), G3D::Token::string(), G3D::Token::SYMBOL, G3D::Token::type(), and VALUE.
Referenced by load(), parse(), and XML().
get()
XML G3D::XML::get (const std::string & k, const XML & defaultVal) const inline
Note that the result is always copied, making this inefficient for return values that are not VALUEs.
Definition at line 153 of file XML.h.
{
         const XML* x = m_attribute.getPointer(k);
         if (x) {
             return *x;
         } else {
             return defaultVal;
         }
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), m_attribute, and G3D::x.
load()
void G3D::XML::load (const std::string & filename)
Definition at line 36 of file XML.cpp.
{
     TextInput::Settings s;
     s.cppBlockComments = false;
     s.cppLineComments = false;
     s.proofSymbols = false;
     TextInput t(filename, s);
     deserialize(t);
 }
References G3D::TextInput::Settings::cppBlockComments, G3D::TextInput::Settings::cppLineComments, deserialize(), and G3D::TextInput::Settings::proofSymbols.
name()
const std::string G3D::XML::name () const inline
The name, if this is a TAG.
Definition at line 167 of file XML.h.
{
         return m_name;
     }
References m_name.
numAttributes()
size_t G3D::XML::numAttributes () const inline
Attribute table size; zero for a TAG
Definition at line 132 of file XML.h.
{
         return m_attribute.size();
     }
References m_attribute, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::size().
number()
double G3D::XML::number () const
Parse as a number. Returns nan() if a TAG or unparseable as a number.
Definition at line 26 of file XML.cpp.
{
     return TextInput::parseNumber(m_value);
 }
References m_value, and G3D::TextInput::parseNumber().
Referenced by mpq::File::__repr__(), mpq::File::__str__(), operator double(), operator float(), and operator int().
numChildren()
int G3D::XML::numChildren () const inline
Array size; zero for a VALUE
Definition at line 127 of file XML.h.
{
         return m_child.size();
     }
References m_child.
operator bool()
G3D::XML::operator bool () const inline
Definition at line 186 of file XML.h.
{
         return boolean();
     }
References boolean().
operator double()
G3D::XML::operator double () const inline
Definition at line 190 of file XML.h.
{
         return number();
     }
References number().
operator float()
G3D::XML::operator float () const inline
Definition at line 194 of file XML.h.
{
         return float(number());
     }
References number().
operator int()
G3D::XML::operator int () const inline
Definition at line 198 of file XML.h.
{
         return iRound(number());
     }
References G3D::iRound(), and number().
operator std::string()
G3D::XML::operator std::string () const inline
Definition at line 182 of file XML.h.
{
         return m_value;
     }
References m_value.
operator[]() [1/2]
const XML& G3D::XML::operator[] (const std::string & k) const inline
Return the attribute with this name.
Definition at line 143 of file XML.h.
{
         return m_attribute[k];
     }
References m_attribute.
operator[]() [2/2]
const XML& G3D::XML::operator[] (int i) const inline
Return child i. Children are nested tags and the unquoted strings of characters between tags.
Definition at line 138 of file XML.h.
{
         return m_child[i];
     }
References m_child.
parse()
void G3D::XML::parse (const std::string & s)
Definition at line 91 of file XML.cpp.
{
     TextInput t(TextInput::FROM_STRING, s);
     deserialize(t);
 }
References deserialize(), and G3D::TextInput::FROM_STRING.
save()
void G3D::XML::save (const std::string & filename) const
Definition at line 47 of file XML.cpp.
{
     std::string s;
     unparse(s);
     writeWholeFile(filename, s);
 }
References unparse(), and G3D::writeWholeFile().
serialize()
void G3D::XML::serialize (TextOutput & t) const
Definition at line 65 of file XML.cpp.
{
     if (m_type == VALUE) {
         // Raw string; no quotes
         t.writeSymbol(m_value);
     } else {
         t.printf("<%s", m_name.c_str());
         for (AttributeTable::Iterator it = m_attribute.begin(); it.isValid(); ++it) {
             t.printf(" %s=\"%s\"", it->key.c_str(), it->value.m_value.c_str());
         }
         t.printf(">");
         t.writeNewline();
         t.pushIndent();
         for (int i = 0; i < m_child.size(); ++i) {
             m_child[i].serialize(t);
             if (m_child[i].m_type == VALUE) {
                 // Only tags know to append a newline
                 t.writeNewline();
             }
         }
         t.popIndent();
         t.printf("</%s>", m_name.c_str());
         t.writeNewline();
     }
 }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), m_attribute, m_child, m_name, m_type, m_value, G3D::TextOutput::popIndent(), G3D::TextOutput::printf(), G3D::TextOutput::pushIndent(), VALUE, G3D::TextOutput::writeNewline(), and G3D::TextOutput::writeSymbol().
Referenced by unparse().
string()
const std::string& G3D::XML::string () const inline
Returns "" if a TAG.
Definition at line 172 of file XML.h.
{
         return m_value;
     }
References m_value.
type()
Type G3D::XML::type () const inline
Definition at line 162 of file XML.h.
                       {
         return m_type;
     }
References m_type.
unparse()
void G3D::XML::unparse (std::string & s) const
Definition at line 54 of file XML.cpp.
{
     TextOutput::Settings set;
     set.wordWrap = TextOutput::Settings::WRAP_WITHOUT_BREAKING;
     TextOutput t(set);
     serialize(t);
     t.commitString(s);
 }
References G3D::TextOutput::commitString(), serialize(), set(), and G3D::TextOutput::Settings::WRAP_WITHOUT_BREAKING.
Referenced by save().
Member Data Documentation
m_attribute
AttributeTable G3D::XML::m_attribute private
Definition at line 77 of file XML.h.
Referenced by attributeTable(), containsAttribute(), deserialize(), get(), numAttributes(), operator[](), and serialize().
m_child
Array<XML> G3D::XML::m_child private
Definition at line 78 of file XML.h.
Referenced by childArray(), deserialize(), numChildren(), operator[](), and serialize().
m_name
std::string G3D::XML::m_name private
Definition at line 75 of file XML.h.
Referenced by deserialize(), name(), and serialize().
m_type
Type G3D::XML::m_type private
Definition at line 74 of file XML.h.
Referenced by deserialize(), serialize(), and type().
m_value
std::string G3D::XML::m_value private
Definition at line 76 of file XML.h.
Referenced by boolean(), deserialize(), number(), operator std::string(), serialize(), and string().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/XML.h
deps/g3dlite/source/XML.cpp