Azerotcore-wotlk: G3D::CRTMemoryManager Class Reference
G3D::CRTMemoryManager Class Reference
#include <MemoryManager.h>
Public Types
typedef shared_ptr< class MemoryManager > Ref
Public Types inherited from G3D::MemoryManager
typedef shared_ptr< class MemoryManager > Ref
Public Member Functions
virtual void * alloc (size_t s)
virtual void free (void *ptr)
virtual bool isThreadsafe () const
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static CRTMemoryManager::Ref create ()
Static Public Member Functions inherited from G3D::MemoryManager
static MemoryManager::Ref create ()
Protected Member Functions
CRTMemoryManager ()
Protected Member Functions inherited from G3D::MemoryManager
MemoryManager ()
Detailed Description
A MemoryManager implemented using the C runtime. Not recommended for general use; this is largely for debugging.
Definition at line 77 of file MemoryManager.h.
Member Typedef Documentation
Ref
typedef shared_ptr<class MemoryManager> G3D::CRTMemoryManager::Ref
Definition at line 82 of file MemoryManager.h.
Constructor & Destructor Documentation
CRTMemoryManager()
G3D::CRTMemoryManager::CRTMemoryManager () protected
Definition at line 69 of file MemoryManager.cpp.
 {}
Referenced by create().
Member Function Documentation
alloc()
void * G3D::CRTMemoryManager::alloc (size_t s) virtual
Return a pointer to s bytes of memory that are unused by the rest of the program. The contents of the memory are undefined
Reimplemented from G3D::MemoryManager.
Definition at line 72 of file MemoryManager.cpp.
{
     return ::malloc(s);
 }
create()
CRTMemoryManager::Ref G3D::CRTMemoryManager::create () static
There's only one instance of this memory manager; it is cached after the first creation.
Definition at line 87 of file MemoryManager.cpp.
{
     static CRTMemoryManager::Ref m(new CRTMemoryManager());
     return m;
 }
References CRTMemoryManager().
free()
void G3D::CRTMemoryManager::free (void * ptr) virtual
Invoke to declare that this memory will no longer be used by the program. The memory manager is not required to actually reuse or release this memory.
Reimplemented from G3D::MemoryManager.
Definition at line 77 of file MemoryManager.cpp.
{
     return ::free(ptr);
 }
References ptr().
isThreadsafe()
bool G3D::CRTMemoryManager::isThreadsafe () const virtual
Returns true if this memory manager is threadsafe (i.e., alloc and free can be called asychronously)
Reimplemented from G3D::MemoryManager.
Definition at line 82 of file MemoryManager.cpp.
{
     return true;
 }
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/MemoryManager.h
deps/g3dlite/source/MemoryManager.cpp