Azerotcore-wotlk: at_icc_start_frostwing_gauntlet Class Reference
at_icc_start_frostwing_gauntlet Class Reference
Public Member Functions
at_icc_start_frostwing_gauntlet ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 2331 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
at_icc_start_frostwing_gauntlet()
at_icc_start_frostwing_gauntlet::at_icc_start_frostwing_gauntlet () inline
Definition at line 2334 of file icecrown_citadel.cpp.
 : AreaTriggerScript("at_icc_start_frostwing_gauntlet") { }
Member Function Documentation
OnTrigger()
bool at_icc_start_frostwing_gauntlet::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 2336 of file icecrown_citadel.cpp.
     {
         if (InstanceScript* instance = player->GetInstanceScript())
             if (instance->GetBossState(DATA_SISTER_SVALNA) != DONE)
                 if (Creature* crok = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_CROK_SCOURGEBANE)))
                 {
                     if (!crok->IsAlive())
                     {
                         FrostwingGauntletRespawner respawner;
                         Acore::CreatureWorker<FrostwingGauntletRespawner> worker(crok, respawner);
                         Cell::VisitGridObjects(crok, worker, 333.0f);
                         return true;
                     }
                     else
                         crok->AI()->DoAction(ACTION_START_GAUNTLET);
                 }
         return true;
     }
References ACTION_START_GAUNTLET, DATA_CROK_SCOURGEBANE, DATA_SISTER_SVALNA, DONE, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and Cell::VisitGridObjects().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp