Azerotcore-wotlk: UpdateMask Class Reference
UpdateMask Class Reference
#include <UpdateMask.h>
Public Types
enum UpdateMaskCount { CLIENT_UPDATE_MASK_BITS = sizeof(ClientUpdateMaskType) * 8 }
typedef uint32 ClientUpdateMaskType
Type representing how client reads update mask.
Public Member Functions
UpdateMask ()
UpdateMask (UpdateMask const &right)
~UpdateMask ()
void SetBit (uint32 index)
void UnsetBit (uint32 index)
bool GetBit (uint32 index) const
void AppendToPacket (ByteBuffer *data)
uint32 GetBlockCount () const
uint32 GetCount () const
void SetCount (uint32 valuesCount)
void Clear ()
UpdateMask & operator= (UpdateMask const &right)
UpdateMask & operator&= (UpdateMask const &right)
UpdateMask & operator|= (UpdateMask const &right)
UpdateMask operator| (UpdateMask const &right)
Private Attributes
uint32 _fieldCount {0}
uint32 _blockCount {0}
uint8 * _bits {nullptr}
Detailed Description
Definition at line 25 of file UpdateMask.h.
Member Typedef Documentation
ClientUpdateMaskType
typedef uint32 UpdateMask::ClientUpdateMaskType
Type representing how client reads update mask.
Definition at line 29 of file UpdateMask.h.
Member Enumeration Documentation
UpdateMaskCount
enum UpdateMask::UpdateMaskCount
Enumerator
CLIENT_UPDATE_MASK_BITS
Definition at line 31 of file UpdateMask.h.
     {
         CLIENT_UPDATE_MASK_BITS = sizeof(ClientUpdateMaskType) * 8,
     };
Constructor & Destructor Documentation
UpdateMask() [1/2]
UpdateMask::UpdateMask () inline
Definition at line 36 of file UpdateMask.h.
 { }
UpdateMask() [2/2]
UpdateMask::UpdateMask (UpdateMask const & right) inline
Definition at line 38 of file UpdateMask.h.
                                         : _bits(nullptr)
     {
         SetCount(right.GetCount());
         memcpy(_bits, right._bits, sizeof(uint8) * _blockCount * 32);
     }
References _bits, _blockCount, memcpy, align::right, and SetCount().
~UpdateMask()
UpdateMask::~UpdateMask () inline
Definition at line 44 of file UpdateMask.h.
 { delete[] _bits; }
References _bits.
Member Function Documentation
AppendToPacket()
void UpdateMask::AppendToPacket (ByteBuffer * data) inline
Definition at line 50 of file UpdateMask.h.
     {
         for (uint32 i = 0; i < GetBlockCount(); ++i)
         {
             ClientUpdateMaskType maskPart = 0;
             for (uint32 j = 0; j < CLIENT_UPDATE_MASK_BITS; ++j)
                 if (_bits[CLIENT_UPDATE_MASK_BITS * i + j])
                     maskPart |= 1 << j;
             *data << maskPart;
         }
     }
References _bits, CLIENT_UPDATE_MASK_BITS, and GetBlockCount().
Referenced by Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
Clear()
void UpdateMask::Clear () inline
Definition at line 77 of file UpdateMask.h.
     {
         if (_bits)
             memset(_bits, 0, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
     }
References _bits, _blockCount, CLIENT_UPDATE_MASK_BITS, and memset.
Referenced by Object::ClearUpdateMask().
GetBit()
bool UpdateMask::GetBit (uint32 index) const inline
Definition at line 48 of file UpdateMask.h.
 { return _bits[index] != 0; }
References _bits, and index.
Referenced by Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
GetBlockCount()
uint32 UpdateMask::GetBlockCount () const inline
Definition at line 63 of file UpdateMask.h.
 { return _blockCount; }
References _blockCount.
Referenced by AppendToPacket(), Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), and Unit::BuildValuesUpdate().
GetCount()
uint32 UpdateMask::GetCount () const inline
Definition at line 64 of file UpdateMask.h.
 { return _fieldCount; }
References _fieldCount.
Referenced by operator&=(), and operator|=().
operator&=()
UpdateMask& UpdateMask::operator&= (UpdateMask const & right) inline
Definition at line 93 of file UpdateMask.h.
     {
         ASSERT(right.GetCount() <= GetCount());
         for (uint32 i = 0; i < _fieldCount; ++i)
             _bits[i] &= right._bits[i];
         return *this;
     }
References _bits, _fieldCount, ASSERT, GetCount(), and align::right.
operator=()
UpdateMask& UpdateMask::operator= (UpdateMask const & right) inline
Definition at line 83 of file UpdateMask.h.
     {
         if (this == &right)
             return *this;
         SetCount(right.GetCount());
         memcpy(_bits, right._bits, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
         return *this;
     }
References _bits, _blockCount, CLIENT_UPDATE_MASK_BITS, memcpy, align::right, and SetCount().
operator|()
UpdateMask UpdateMask::operator| (UpdateMask const & right) inline
Definition at line 111 of file UpdateMask.h.
     {
         UpdateMask ret(*this);
         ret |= right;
         return ret;
     }
References ret, and align::right.
operator|=()
UpdateMask& UpdateMask::operator|= (UpdateMask const & right) inline
Definition at line 102 of file UpdateMask.h.
     {
         ASSERT(right.GetCount() <= GetCount());
         for (uint32 i = 0; i < _fieldCount; ++i)
             _bits[i] |= right._bits[i];
         return *this;
     }
References _bits, _fieldCount, ASSERT, GetCount(), and align::right.
SetBit()
void UpdateMask::SetBit (uint32 index) inline
Definition at line 46 of file UpdateMask.h.
 { _bits[index] = 1; }
References _bits, and index.
Referenced by Object::_LoadIntoDataField(), Object::AddGuidValue(), Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), Object::ForceValuesUpdateAtIndex(), Object::RemoveByteFlag(), Object::RemoveFlag(), Object::RemoveGuidValue(), Object::SetByteFlag(), Object::SetFlag(), Object::SetFloatValue(), Object::SetGuidValue(), Object::SetInt32Value(), Object::SetUInt16Value(), Object::SetUInt32Value(), Object::SetUInt64Value(), and Object::UpdateUInt32Value().
SetCount()
void UpdateMask::SetCount (uint32 valuesCount) inline
Definition at line 66 of file UpdateMask.h.
     {
         delete[] _bits;
         _fieldCount = valuesCount;
         _blockCount = (valuesCount + CLIENT_UPDATE_MASK_BITS - 1) / CLIENT_UPDATE_MASK_BITS;
         _bits = new uint8[_blockCount * CLIENT_UPDATE_MASK_BITS];
         memset(_bits, 0, sizeof(uint8) * _blockCount * CLIENT_UPDATE_MASK_BITS);
     }
References _bits, _blockCount, _fieldCount, CLIENT_UPDATE_MASK_BITS, and memset.
Referenced by Object::_InitValues(), Object::BuildValuesUpdate(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), operator=(), and UpdateMask().
UnsetBit()
void UpdateMask::UnsetBit (uint32 index) inline
Definition at line 47 of file UpdateMask.h.
 { _bits[index] = 0; }
References _bits, and index.
Referenced by Unit::SetLevel().
Member Data Documentation
_bits
uint8* UpdateMask::_bits {nullptr} private
Definition at line 121 of file UpdateMask.h.
Referenced by AppendToPacket(), Clear(), GetBit(), operator&=(), operator=(), operator|=(), SetBit(), SetCount(), UnsetBit(), UpdateMask(), and ~UpdateMask().
_blockCount
uint32 UpdateMask::_blockCount {0} private
Definition at line 120 of file UpdateMask.h.
Referenced by Clear(), GetBlockCount(), operator=(), SetCount(), and UpdateMask().
_fieldCount
uint32 UpdateMask::_fieldCount {0} private
Definition at line 119 of file UpdateMask.h.
Referenced by GetCount(), operator&=(), operator|=(), and SetCount().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/Updates/UpdateMask.h