Azerotcore-wotlk: item_only_for_flight Class Reference
item_only_for_flight Class Reference
Public Member Functions
item_only_for_flight ()
bool OnUse (Player *player, Item *item, SpellCastTargets const &) override
Public Member Functions inherited from ItemScript
bool IsDatabaseBound () const override
virtual bool OnQuestAccept (Player *, Item *, Quest const *)
virtual bool OnRemove (Player *, Item *)
virtual bool OnCastItemCombatSpell (Player *, Unit *, SpellInfo const *, Item *)
virtual bool OnExpire (Player *, ItemTemplate const *)
virtual void OnGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from ItemScript
ItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 46 of file item_scripts.cpp.
Constructor & Destructor Documentation
item_only_for_flight()
item_only_for_flight::item_only_for_flight () inline
Definition at line 49 of file item_scripts.cpp.
 : ItemScript("item_only_for_flight") { }
Member Function Documentation
OnUse()
bool item_only_for_flight::OnUse (Player * player, Item * item, SpellCastTargets const &) inline override virtual
Reimplemented from ItemScript.
Definition at line 51 of file item_scripts.cpp.
     {
         uint32 itemId = item->GetEntry();
         bool disabled = false;
         //for special scripts
         switch (itemId)
         {
             case 24538:
                 if (player->GetAreaId() != 3628)
                     disabled = true;
                 break;
             case 34489:
                 if (player->GetZoneId() != 4080)
                     disabled = true;
                 break;
             case 34475:
                 if (const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(SPELL_ARCANE_CHARGES))
                     Spell::SendCastResult(player, spellInfo, 1, SPELL_FAILED_NOT_ON_GROUND);
                 break;
         }
         // allow use in flight only
         if (player->IsInFlight() && !disabled)
             return false;
         // error
         player->SendEquipError(EQUIP_ERR_CANT_DO_RIGHT_NOW, item, nullptr);
         return true;
     }
References EQUIP_ERR_CANT_DO_RIGHT_NOW, WorldObject::GetAreaId(), Object::GetEntry(), WorldObject::GetZoneId(), Unit::IsInFlight(), Spell::SendCastResult(), Player::SendEquipError(), SPELL_ARCANE_CHARGES, SPELL_FAILED_NOT_ON_GROUND, and sSpellMgr.
The documentation for this class was generated from the following file:
src/server/scripts/World/item_scripts.cpp