Azerotcore-wotlk: SuckBackEvent Class Reference
SuckBackEvent Class Reference
Public Member Functions
SuckBackEvent (Creature &owner, uint32 action)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
uint32 _action
Detailed Description
Definition at line 111 of file boss_reliquary_of_souls.cpp.
Constructor & Destructor Documentation
SuckBackEvent()
SuckBackEvent::SuckBackEvent (Creature & owner, uint32 action) inline
Definition at line 114 of file boss_reliquary_of_souls.cpp.
 : BasicEvent(), _owner(owner), _action(action) { }
Member Function Documentation
Execute()
bool SuckBackEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 116 of file boss_reliquary_of_souls.cpp.
     {
         if (_owner.IsSummon())
             if (Unit* summoner = _owner.ToTempSummon()->GetSummonerUnit())
             {
                 summoner->GetAI()->DoAction(_action);
                 _owner.SetStandState(UNIT_STAND_STATE_SUBMERGED);
                 _owner.DespawnOrUnsummon(200);
             }
         return true;
     }
References _action, _owner, Creature::DespawnOrUnsummon(), TempSummon::GetSummonerUnit(), Unit::IsSummon(), Unit::SetStandState(), Unit::ToTempSummon(), and UNIT_STAND_STATE_SUBMERGED.
Member Data Documentation
_action
uint32 SuckBackEvent::_action private
Definition at line 130 of file boss_reliquary_of_souls.cpp.
Referenced by Execute().
_owner
Creature& SuckBackEvent::_owner private
Definition at line 129 of file boss_reliquary_of_souls.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp