Azerotcore-wotlk: src/server/game/Tools/PlayerDump.cpp File Reference
PlayerDump.cpp File Reference
#include "AccountMgr.h"
#include "Common.h"
#include "DatabaseEnv.h"
#include "ObjectMgr.h"
#include "PlayerDump.h"
#include "World.h"
Classes
struct DumpTable
Macros
#define DUMP_TABLE_COUNT 27
#define ROLLBACK(DR) {fclose(fin); return (DR);}
Functions
static bool findtoknth (std::string &str, int n, std::string::size_type &s, std::string::size_type &e)
std::string gettoknth (std::string &str, int n)
bool findnth (std::string &str, int n, std::string::size_type &s, std::string::size_type &e)
std::string gettablename (std::string &str)
bool changenth (std::string &str, int n, const char *with, bool insert=false, bool nonzero=false)
std::string getnth (std::string &str, int n)
bool changetoknth (std::string &str, int n, const char *with, bool insert=false, bool nonzero=false)
uint32 registerNewGuid (uint32 oldGuid, std::map< uint32, uint32 > &guidMap, uint32 hiGuid)
bool changeGuid (std::string &str, int n, std::map< uint32, uint32 > &guidMap, uint32 hiGuid, bool nonzero=false)
bool changetokGuid (std::string &str, int n, std::map< uint32, uint32 > &guidMap, uint32 hiGuid, bool nonzero=false)
std::string CreateDumpString (char const *tableName, QueryResult result)
void StoreGUID (QueryResult result, uint32 field, std::set< uint32 > &guids)
void StoreGUID (QueryResult result, uint32 data, uint32 field, std::set< uint32 > &guids)
void fixNULLfields (std::string &line)
Variables
static DumpTable dumpTables [DUMP_TABLE_COUNT]
Macro Definition Documentation
DUMP_TABLE_COUNT
#define DUMP_TABLE_COUNT 27
Definition at line 25 of file PlayerDump.cpp.
ROLLBACK
#define ROLLBACK (DR) {fclose(fin); return (DR);}
Definition at line 401 of file PlayerDump.cpp.
Function Documentation
changeGuid()
bool changeGuid (std::string & str, int n, std::map< uint32, uint32 > & guidMap, uint32 hiGuid, bool nonzero = false)
Definition at line 171 of file PlayerDump.cpp.
 {
     char chritem[20];
     uint32 oldGuid = atoi(getnth(str, n).c_str());
     if (nonzero && oldGuid == 0)
         return true;                                        // not an error
     uint32 newGuid = registerNewGuid(oldGuid, guidMap, hiGuid);
     snprintf(chritem, 20, "%u", newGuid);
     return changenth(str, n, chritem, false, nonzero);
 }
References changenth(), getnth(), and registerNewGuid().
Referenced by PlayerDumpReader::LoadDump().
changenth()
bool changenth (std::string & str, int n, const char * with, bool insert = false, bool nonzero = false)
Definition at line 120 of file PlayerDump.cpp.
 {
     std::string::size_type s, e;
     if (!findnth(str, n, s, e))
         return false;
     if (nonzero && str.substr(s, e - s) == "0")
         return true;                                        // not an error
     if (!insert)
         str.replace(s, e - s, with);
     else
         str.insert(s, with);
     return true;
 }
References findnth().
Referenced by changeGuid(), and PlayerDumpReader::LoadDump().
changetokGuid()
bool changetokGuid (std::string & str, int n, std::map< uint32, uint32 > & guidMap, uint32 hiGuid, bool nonzero = false)
Definition at line 184 of file PlayerDump.cpp.
 {
     char chritem[20];
     uint32 oldGuid = atoi(gettoknth(str, n).c_str());
     if (nonzero && oldGuid == 0)
         return true;                                        // not an error
     uint32 newGuid = registerNewGuid(oldGuid, guidMap, hiGuid);
     snprintf(chritem, 20, "%u", newGuid);
     return changetoknth(str, n, chritem, false, nonzero);
 }
References changetoknth(), gettoknth(), and registerNewGuid().
changetoknth()
bool changetoknth (std::string & str, int n, const char * with, bool insert = false, bool nonzero = false)
Definition at line 145 of file PlayerDump.cpp.
 {
     std::string::size_type s = 0, e = 0;
     if (!findtoknth(str, n, s, e))
         return false;
     if (nonzero && str.substr(s, e - s) == "0")
         return true;                                        // not an error
     if (!insert)
         str.replace(s, e - s, with);
     else
         str.insert(s, with);
     return true;
 }
References findtoknth().
Referenced by changetokGuid().
CreateDumpString()
std::string CreateDumpString (char const * tableName, QueryResult result)
Definition at line 197 of file PlayerDump.cpp.
 {
     if (!tableName || !result) return "";
     std::ostringstream ss;
     ss << "INSERT INTO `" << tableName << "` VALUES (";
     Field* fields = result->Fetch();
     for (uint32 i = 0; i < result->GetFieldCount(); ++i)
     {
         if (i == 0) ss << '\'';
         else ss << ", '";
         std::string s = fields[i].GetString();
         CharacterDatabase.EscapeString(s);
         ss << s;
         ss << '\'';
     }
     ss << ");";
     return ss.str();
 }
References CharacterDatabase, and Field::GetString().
Referenced by PlayerDumpWriter::DumpTable().
findnth()
bool findnth (std::string & str, int n, std::string::size_type & s, std::string::size_type & e)
Definition at line 87 of file PlayerDump.cpp.
 {
     s = str.find("VALUES ('") + 9;
     if (s == std::string::npos) return false;
     do
     {
         e = str.find('\'', s);
         if (e == std::string::npos) return false;
     } while (str[e - 1] == '\\');
     for (int i = 1; i < n; ++i)
     {
         do
         {
             s = e + 4;
             e = str.find('\'', s);
             if (e == std::string::npos) return false;
         } while (str[e - 1] == '\\');
     }
     return true;
 }
Referenced by changenth(), and getnth().
findtoknth()
static bool findtoknth (std::string & str, int n, std::string::size_type & s, std::string::size_type & e) static
Definition at line 64 of file PlayerDump.cpp.
 {
     int i;
     s = e = 0;
     std::string::size_type size = str.size();
     for (i = 1; s < size && i < n; s++) if (str[s] == ' ') ++i;
     if (i < n)
         return false;
     e = str.find(' ', s);
     return e != std::string::npos;
 }
Referenced by changetoknth(), and gettoknth().
fixNULLfields()
void fixNULLfields (std::string & line)
Definition at line 403 of file PlayerDump.cpp.
 {
     std::string nullString("'NULL'");
     size_t pos = line.find(nullString);
     while (pos != std::string::npos)
     {
         line.replace(pos, nullString.length(), "NULL");
         pos = line.find(nullString);
     }
 }
References pos().
Referenced by PlayerDumpReader::LoadDump().
getnth()
std::string getnth (std::string & str, int n)
Definition at line 136 of file PlayerDump.cpp.
 {
     std::string::size_type s, e;
     if (!findnth(str, n, s, e))
         return "";
     return str.substr(s, e - s);
 }
References findnth().
Referenced by changeGuid(), and PlayerDumpReader::LoadDump().
gettablename()
std::string gettablename (std::string & str)
Definition at line 110 of file PlayerDump.cpp.
 {
     std::string::size_type s = 13;
     std::string::size_type e = str.find("`", s);
     if (e == std::string::npos)
         return "";
     return str.substr(s, e - s);
 }
Referenced by PlayerDumpReader::LoadDump().
gettoknth()
std::string gettoknth (std::string & str, int n)
Definition at line 78 of file PlayerDump.cpp.
 {
     std::string::size_type s = 0, e = 0;
     if (!findtoknth(str, n, s, e))
         return "";
     return str.substr(s, e - s);
 }
References findtoknth().
Referenced by changetokGuid(), and StoreGUID().
registerNewGuid()
uint32 registerNewGuid (uint32 oldGuid, std::map< uint32, uint32 > & guidMap, uint32 hiGuid)
Definition at line 160 of file PlayerDump.cpp.
 {
     std::map<uint32, uint32>::const_iterator itr = guidMap.find(oldGuid);
     if (itr != guidMap.end())
         return itr->second;
     uint32 newguid = hiGuid + guidMap.size();
     guidMap[oldGuid] = newguid;
     return newguid;
 }
Referenced by changeGuid(), and changetokGuid().
StoreGUID() [1/2]
void StoreGUID (QueryResult result, uint32 data, uint32 field, std::set< uint32 > & guids)
Definition at line 255 of file PlayerDump.cpp.
 {
     Field* fields = result->Fetch();
     std::string dataStr = fields[data].GetString();
     uint32 guid = atoi(gettoknth(dataStr, field).c_str());
     if (guid)
         guids.insert(guid);
 }
References Field::GetString(), and gettoknth().
StoreGUID() [2/2]
void StoreGUID (QueryResult result, uint32 field, std::set< uint32 > & guids)
Definition at line 247 of file PlayerDump.cpp.
 {
     Field* fields = result->Fetch();
     uint32 guid = fields[field].GetUInt32();
     if (guid)
         guids.insert(guid);
 }
References Field::GetUInt32().
Referenced by PlayerDumpWriter::DumpTable().
Variable Documentation
dumpTables
DumpTable dumpTables[DUMP_TABLE_COUNT] static
Initial value:
=
{
    { "characters",                       DTT_CHARACTER  },
    { "character_account_data",           DTT_CHAR_TABLE },
    { "character_achievement",            DTT_CHAR_TABLE },
    { "character_achievement_progress",   DTT_CHAR_TABLE },
    { "character_action",                 DTT_CHAR_TABLE },
    { "character_aura",                   DTT_CHAR_TABLE },
    { "character_declinedname",           DTT_CHAR_TABLE },
    { "character_equipmentsets",          DTT_EQSET_TABLE},
    { "character_glyphs",                 DTT_CHAR_TABLE },
    { "character_homebind",               DTT_CHAR_TABLE },
    { "character_inventory",              DTT_INVENTORY  },
    { "character_pet",                    DTT_PET        },
    { "character_pet_declinedname",       DTT_PET        },
    { "character_queststatus",            DTT_CHAR_TABLE },
    { "character_queststatus_rewarded",   DTT_CHAR_TABLE },
    { "character_reputation",             DTT_CHAR_TABLE },
    { "character_skills",                 DTT_CHAR_TABLE },
    { "character_spell",                  DTT_CHAR_TABLE },
    { "character_spell_cooldown",         DTT_CHAR_TABLE },
    { "character_talent",                 DTT_CHAR_TABLE },
    { "mail",                             DTT_MAIL       },
    { "mail_items",                       DTT_MAIL_ITEM  },
    { "pet_aura",                         DTT_PET_TABLE  },
    { "pet_spell",                        DTT_PET_TABLE  },
    { "pet_spell_cooldown",               DTT_PET_TABLE  },
    { "item_instance",                    DTT_ITEM       },
    { "character_gifts",                  DTT_ITEM_GIFT  },
}
Definition at line 32 of file PlayerDump.cpp.
Referenced by PlayerDumpWriter::GetDump(), and PlayerDumpReader::LoadDump().