Azerotcore-wotlk: boss_bigbadwolf::boss_bigbadwolfAI Struct Reference
boss_bigbadwolf::boss_bigbadwolfAI Struct Reference
Public Member Functions
boss_bigbadwolfAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *) override
void JustReachedHome () override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 ChaseTimer
uint32 FearTimer
uint32 SwipeTimer
ObjectGuid HoodGUID
float TempThreat
bool IsChasing
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 848 of file bosses_opera.cpp.
Constructor & Destructor Documentation
boss_bigbadwolfAI()
boss_bigbadwolf::boss_bigbadwolfAI::boss_bigbadwolfAI (Creature * creature) inline
Definition at line 850 of file bosses_opera.cpp.
                                               : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript().
Member Function Documentation
EnterCombat()
void boss_bigbadwolf::boss_bigbadwolfAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 878 of file bosses_opera.cpp.
         {
             Talk(SAY_WOLF_AGGRO);
             DoZoneInCombat();
         }
References SAY_WOLF_AGGRO.
JustDied()
void boss_bigbadwolf::boss_bigbadwolfAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 894 of file bosses_opera.cpp.
         {
             DoPlaySoundToSet(me, SOUND_WOLF_DEATH);
             instance->SetBossState(DATA_OPERA_PERFORMANCE, DONE);
         }
References DATA_OPERA_PERFORMANCE, DONE, InstanceScript::SetBossState(), and SOUND_WOLF_DEATH.
JustReachedHome()
void boss_bigbadwolf::boss_bigbadwolfAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 889 of file bosses_opera.cpp.
         {
             me->DespawnOrUnsummon();
         }
KilledUnit()
void boss_bigbadwolf::boss_bigbadwolfAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 884 of file bosses_opera.cpp.
         {
             Talk(SAY_WOLF_SLAY);
         }
References SAY_WOLF_SLAY.
Reset()
void boss_bigbadwolf::boss_bigbadwolfAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 866 of file bosses_opera.cpp.
         {
             ChaseTimer = 30000;
             FearTimer = urand(25000, 35000);
             SwipeTimer = 5000;
             HoodGUID.Clear();
             TempThreat = 0;
             IsChasing = false;
         }
References ObjectGuid::Clear(), and urand().
UpdateAI()
void boss_bigbadwolf::boss_bigbadwolfAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 901 of file bosses_opera.cpp.
         {
             if (!UpdateVictim())
                 return;
             DoMeleeAttackIfReady();
             if (ChaseTimer <= diff)
             {
                 if (!IsChasing)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                     {
                         Talk(SAY_WOLF_HOOD);
                         DoCast(target, SPELL_LITTLE_RED_RIDING_HOOD, true);
                         TempThreat = DoGetThreat(target);
                         if (TempThreat)
                             DoModifyThreatPercent(target, -100);
                         HoodGUID = target->GetGUID();
                         me->AddThreat(target, 1000000.0f);
                         ChaseTimer = 20000;
                         IsChasing = true;
                     }
                 }
                 else
                 {
                     IsChasing = false;
                     if (Unit* target = ObjectAccessor::GetUnit(*me, HoodGUID))
                     {
                         HoodGUID.Clear();
                         if (DoGetThreat(target))
                             DoModifyThreatPercent(target, -100);
                         me->AddThreat(target, TempThreat);
                         TempThreat = 0;
                     }
                     ChaseTimer = 40000;
                 }
             }
             else
                 ChaseTimer -= diff;
             if (IsChasing)
                 return;
             if (FearTimer <= diff)
             {
                 DoCastVictim(SPELL_TERRIFYING_HOWL);
                 FearTimer = urand(25000, 35000);
             }
             else
                 FearTimer -= diff;
             if (SwipeTimer <= diff)
             {
                 DoCastVictim(SPELL_WIDE_SWIPE);
                 SwipeTimer = urand(25000, 30000);
             }
             else
                 SwipeTimer -= diff;
         }
References ObjectGuid::Clear(), ObjectAccessor::GetUnit(), SAY_WOLF_HOOD, SELECT_TARGET_RANDOM, SPELL_LITTLE_RED_RIDING_HOOD, SPELL_TERRIFYING_HOWL, SPELL_WIDE_SWIPE, and urand().
Member Data Documentation
ChaseTimer
uint32 boss_bigbadwolf::boss_bigbadwolfAI::ChaseTimer
Definition at line 857 of file bosses_opera.cpp.
FearTimer
uint32 boss_bigbadwolf::boss_bigbadwolfAI::FearTimer
Definition at line 858 of file bosses_opera.cpp.
HoodGUID
ObjectGuid boss_bigbadwolf::boss_bigbadwolfAI::HoodGUID
Definition at line 861 of file bosses_opera.cpp.
instance
InstanceScript* boss_bigbadwolf::boss_bigbadwolfAI::instance
Definition at line 855 of file bosses_opera.cpp.
IsChasing
bool boss_bigbadwolf::boss_bigbadwolfAI::IsChasing
Definition at line 864 of file bosses_opera.cpp.
SwipeTimer
uint32 boss_bigbadwolf::boss_bigbadwolfAI::SwipeTimer
Definition at line 859 of file bosses_opera.cpp.
TempThreat
float boss_bigbadwolf::boss_bigbadwolfAI::TempThreat
Definition at line 862 of file bosses_opera.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp