Azerotcore-wotlk: SpellTargetSelector Struct Reference
SpellTargetSelector Struct Reference
#include <UnitAI.h>
Public Member Functions
SpellTargetSelector (Unit *caster, uint32 spellId)
bool operator() (Unit const *target) const
Private Attributes
Unit const * _caster
SpellInfo const * _spellInfo
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 92 of file UnitAI.h.
Constructor & Destructor Documentation
SpellTargetSelector()
SpellTargetSelector::SpellTargetSelector (Unit * caster, uint32 spellId)
Definition at line 304 of file UnitAI.cpp.
                                                                      :
     _caster(caster), _spellInfo(sSpellMgr->GetSpellForDifficultyFromSpell(sSpellMgr->GetSpellInfo(spellId), caster))
 {
     ASSERT(_spellInfo);
 }
References _spellInfo, and ASSERT.
Member Function Documentation
operator()()
bool SpellTargetSelector::operator() (Unit const * target) const
Definition at line 310 of file UnitAI.cpp.
 {
     if (!target)
         return false;
     if (_spellInfo->CheckTarget(_caster, target) != SPELL_CAST_OK)
         return false;
     // copypasta from Spell::CheckRange
     uint32 range_type = _spellInfo->RangeEntry ? _spellInfo->RangeEntry->type : 0;
     float max_range = _caster->GetSpellMaxRangeForTarget(target, _spellInfo);
     float min_range = _caster->GetSpellMinRangeForTarget(target, _spellInfo);
     if (target && target != _caster)
     {
         if (range_type == SPELL_RANGE_MELEE)
         {
             // Because of lag, we can not check too strictly here.
             if (!_caster->IsWithinMeleeRange(target, max_range))
                 return false;
         }
         else if (!_caster->IsWithinCombatRange(target, max_range))
             return false;
         if (range_type == SPELL_RANGE_RANGED)
         {
             if (_caster->IsWithinMeleeRange(target))
                 return false;
         }
         else if (min_range && _caster->IsWithinCombatRange(target, min_range)) // skip this check if min_range = 0
             return false;
     }
     return true;
 }
References _caster, _spellInfo, SpellInfo::CheckTarget(), Unit::GetSpellMaxRangeForTarget(), Unit::GetSpellMinRangeForTarget(), Unit::IsWithinCombatRange(), Unit::IsWithinMeleeRange(), SpellInfo::RangeEntry, SPELL_CAST_OK, SPELL_RANGE_MELEE, SPELL_RANGE_RANGED, and SpellRangeEntry::type.
Member Data Documentation
_caster
Unit const* SpellTargetSelector::_caster private
Definition at line 99 of file UnitAI.h.
Referenced by operator()().
_spellInfo
SpellInfo const* SpellTargetSelector::_spellInfo private
Definition at line 100 of file UnitAI.h.
Referenced by operator()(), and SpellTargetSelector().
The documentation for this struct was generated from the following files:
src/server/game/AI/CoreAI/UnitAI.h
src/server/game/AI/CoreAI/UnitAI.cpp