Azerotcore-wotlk: ScriptMgr Class Reference
ScriptMgr Class Reference
#include <ScriptMgr.h>
Public Types
typedef void(* ScriptLoaderCallbackType) ()
Public Member Functions
void Initialize ()
void LoadDatabase ()
void FillSpellSummary ()
void CheckIfScriptsInDatabaseExist ()
const char * ScriptsVersion () const
void IncrementScriptCount ()
uint32 GetScriptCount () const
void SetScriptLoader (ScriptLoaderCallbackType script_loader_callback)
void Unload ()
void CreateSpellScripts (uint32 spellId, std::list< SpellScript * > &scriptVector)
void CreateAuraScripts (uint32 spellId, std::list< AuraScript * > &scriptVector)
void CreateSpellScriptLoaders (uint32 spellId, std::vector< std::pair< SpellScriptLoader *, std::multimap< uint32, uint32 >::iterator > > &scriptVector)
void OnNetworkStart ()
void OnNetworkStop ()
void OnSocketOpen (std::shared_ptr< WorldSocket > socket)
void OnSocketClose (std::shared_ptr< WorldSocket > socket)
void OnPacketReceive (WorldSession *session, WorldPacket const &packet)
void OnPacketSend (WorldSession *session, WorldPacket const &packet)
void OnLoadCustomDatabaseTable ()
void OnOpenStateChange (bool open)
void OnBeforeConfigLoad (bool reload)
void OnAfterConfigLoad (bool reload)
void OnBeforeFinalizePlayerWorldSession (uint32 &cacheVersion)
void OnMotdChange (std::string &newMotd)
void OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
void OnShutdownCancel ()
void OnWorldUpdate (uint32 diff)
void OnStartup ()
void OnShutdown ()
void OnHonorCalculation (float &honor, uint8 level, float multiplier)
void OnGrayLevelCalculation (uint8 &grayLevel, uint8 playerLevel)
void OnColorCodeCalculation (XPColorChar &color, uint8 playerLevel, uint8 mobLevel)
void OnZeroDifferenceCalculation (uint8 &diff, uint8 playerLevel)
void OnBaseGainCalculation (uint32 &gain, uint8 playerLevel, uint8 mobLevel, ContentLevels content)
void OnGainCalculation (uint32 &gain, Player *player, Unit *unit)
void OnGroupRateCalculation (float &rate, uint32 count, bool isRaid)
void OnAfterArenaRatingCalculation (Battleground *const bg, int32 &winnerMatchmakerChange, int32 &loserMatchmakerChange, int32 &winnerChange, int32 &loserChange)
void OnBeforeUpdatingPersonalRating (int32 &mod, uint32 type)
void OnCreateMap (Map *map)
void OnDestroyMap (Map *map)
void OnLoadGridMap (Map *map, GridMap *gmap, uint32 gx, uint32 gy)
void OnUnloadGridMap (Map *map, GridMap *gmap, uint32 gx, uint32 gy)
void OnPlayerEnterMap (Map *map, Player *player)
void OnPlayerLeaveMap (Map *map, Player *player)
void OnMapUpdate (Map *map, uint32 diff)
InstanceScript * CreateInstanceScript (InstanceMap *map)
bool OnQuestAccept (Player *player, Item *item, Quest const *quest)
bool OnItemUse (Player *player, Item *item, SpellCastTargets const &targets)
bool OnItemExpire (Player *player, ItemTemplate const *proto)
bool OnItemRemove (Player *player, Item *item)
bool OnCastItemCombatSpell (Player *player, Unit *victim, SpellInfo const *spellInfo, Item *item)
void OnGossipSelect (Player *player, Item *item, uint32 sender, uint32 action)
void OnGossipSelectCode (Player *player, Item *item, uint32 sender, uint32 action, const char *code)
bool OnGossipHello (Player *player, Creature *creature)
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *player, Creature *creature, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest)
bool OnQuestSelect (Player *player, Creature *creature, Quest const *quest)
bool OnQuestComplete (Player *player, Creature *creature, Quest const *quest)
bool OnQuestReward (Player *player, Creature *creature, Quest const *quest, uint32 opt)
uint32 GetDialogStatus (Player *player, Creature *creature)
CreatureAI * GetCreatureAI (Creature *creature)
void OnCreatureUpdate (Creature *creature, uint32 diff)
bool OnGossipHello (Player *player, GameObject *go)
bool OnGossipSelect (Player *player, GameObject *go, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *player, GameObject *go, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *player, GameObject *go, Quest const *quest)
bool OnQuestReward (Player *player, GameObject *go, Quest const *quest, uint32 opt)
uint32 GetDialogStatus (Player *player, GameObject *go)
void OnGameObjectDestroyed (GameObject *go, Player *player)
void OnGameObjectDamaged (GameObject *go, Player *player)
void OnGameObjectLootStateChanged (GameObject *go, uint32 state, Unit *unit)
void OnGameObjectStateChanged (GameObject *go, uint32 state)
void OnGameObjectUpdate (GameObject *go, uint32 diff)
GameObjectAI * GetGameObjectAI (GameObject *go)
bool OnAreaTrigger (Player *player, AreaTrigger const *trigger)
Battleground * CreateBattleground (BattlegroundTypeId typeId)
OutdoorPvP * CreateOutdoorPvP (OutdoorPvPData const *data)
std::vector< Acore::ChatCommands::ChatCommandBuilder > GetChatCommands ()
void OnWeatherChange (Weather *weather, WeatherState state, float grade)
void OnWeatherUpdate (Weather *weather, uint32 diff)
void OnAuctionAdd (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionRemove (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionSuccessful (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionExpire (AuctionHouseObject *ah, AuctionEntry *entry)
void OnBeforeAuctionHouseMgrSendAuctionWonMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *bidder, uint32 &bidder_accId, bool &sendNotification, bool &updateAchievementCriteria, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionSalePendingMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, uint32 &profit, bool &sendNotification, bool &updateAchievementCriteria, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionExpiredMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, bool &sendNotification, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *oldBidder, uint32 &oldBidder_accId, Player *newBidder, uint32 &newPrice, bool &sendNotification, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *bidder, uint32 &bidder_accId, bool &sendMail)
void OnBeforeAuctionHouseMgrUpdate ()
bool OnConditionCheck (Condition *condition, ConditionSourceInfo &sourceInfo)
void OnInstall (Vehicle *veh)
void OnUninstall (Vehicle *veh)
void OnReset (Vehicle *veh)
void OnInstallAccessory (Vehicle *veh, Creature *accessory)
void OnAddPassenger (Vehicle *veh, Unit *passenger, int8 seatId)
void OnRemovePassenger (Vehicle *veh, Unit *passenger)
void OnDynamicObjectUpdate (DynamicObject *dynobj, uint32 diff)
void OnAddPassenger (Transport *transport, Player *player)
void OnAddCreaturePassenger (Transport *transport, Creature *creature)
void OnRemovePassenger (Transport *transport, Player *player)
void OnTransportUpdate (Transport *transport, uint32 diff)
void OnRelocate (Transport *transport, uint32 waypointId, uint32 mapId, float x, float y, float z)
bool OnCriteriaCheck (uint32 scriptId, Player *source, Unit *target, uint32 criteria_id)
void OnBeforePlayerUpdate (Player *player, uint32 p_time)
void OnPlayerUpdate (Player *player, uint32 p_time)
void OnSendInitialPacketsBeforeAddToMap (Player *player, WorldPacket &data)
void OnPlayerReleasedGhost (Player *player)
void OnPVPKill (Player *killer, Player *killed)
void OnPlayerPVPFlagChange (Player *player, bool state)
void OnCreatureKill (Player *killer, Creature *killed)
void OnCreatureKilledByPet (Player *petOwner, Creature *killed)
void OnPlayerKilledByCreature (Creature *killer, Player *killed)
void OnPlayerLevelChanged (Player *player, uint8 oldLevel)
void OnPlayerFreeTalentPointsChanged (Player *player, uint32 newPoints)
void OnPlayerTalentsReset (Player *player, bool noCost)
void OnPlayerMoneyChanged (Player *player, int32 &amount)
void OnGivePlayerXP (Player *player, uint32 &amount, Unit *victim)
void OnPlayerReputationChange (Player *player, uint32 factionID, int32 &standing, bool incremental)
void OnPlayerReputationRankChange (Player *player, uint32 factionID, ReputationRank newRank, ReputationRank oldRank, bool increased)
void OnPlayerLearnSpell (Player *player, uint32 spellID)
void OnPlayerForgotSpell (Player *player, uint32 spellID)
void OnPlayerDuelRequest (Player *target, Player *challenger)
void OnPlayerDuelStart (Player *player1, Player *player2)
void OnPlayerDuelEnd (Player *winner, Player *loser, DuelCompleteType type)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg)
void OnBeforeSendChatMessage (Player *player, uint32 &type, uint32 &lang, std::string &msg)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Player *receiver)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Group *group)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Guild *guild)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Channel *channel)
void OnPlayerEmote (Player *player, uint32 emote)
void OnPlayerTextEmote (Player *player, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
void OnPlayerSpellCast (Player *player, Spell *spell, bool skipCheck)
void OnPlayerLogin (Player *player)
void OnPlayerLoadFromDB (Player *player)
void OnPlayerLogout (Player *player)
void OnPlayerCreate (Player *player)
void OnPlayerSave (Player *player)
void OnPlayerDelete (ObjectGuid guid, uint32 accountId)
void OnPlayerFailedDelete (ObjectGuid guid, uint32 accountId)
void OnPlayerBindToInstance (Player *player, Difficulty difficulty, uint32 mapid, bool permanent)
void OnPlayerUpdateZone (Player *player, uint32 newZone, uint32 newArea)
void OnPlayerUpdateArea (Player *player, uint32 oldArea, uint32 newArea)
bool OnBeforePlayerTeleport (Player *player, uint32 mapid, float x, float y, float z, float orientation, uint32 options, Unit *target)
void OnPlayerUpdateFaction (Player *player)
void OnPlayerAddToBattleground (Player *player, Battleground *bg)
void OnPlayerQueueRandomDungeon (Player *player, uint32 &rDungeonId)
void OnPlayerRemoveFromBattleground (Player *player, Battleground *bg)
void OnAchievementComplete (Player *player, AchievementEntry const *achievement)
bool OnBeforeAchievementComplete (Player *player, AchievementEntry const *achievement)
void OnCriteriaProgress (Player *player, AchievementCriteriaEntry const *criteria)
bool OnBeforeCriteriaProgress (Player *player, AchievementCriteriaEntry const *criteria)
void OnAchievementSave (CharacterDatabaseTransaction trans, Player *player, uint16 achiId, CompletedAchievementData achiData)
void OnCriteriaSave (CharacterDatabaseTransaction trans, Player *player, uint16 critId, CriteriaProgress criteriaData)
void OnGossipSelect (Player *player, uint32 menu_id, uint32 sender, uint32 action)
void OnGossipSelectCode (Player *player, uint32 menu_id, uint32 sender, uint32 action, const char *code)
void OnPlayerBeingCharmed (Player *player, Unit *charmer, uint32 oldFactionId, uint32 newFactionId)
void OnAfterPlayerSetVisibleItemSlot (Player *player, uint8 slot, Item *item)
void OnAfterPlayerMoveItemFromInventory (Player *player, Item *it, uint8 bag, uint8 slot, bool update)
void OnEquip (Player *player, Item *it, uint8 bag, uint8 slot, bool update)
void OnPlayerJoinBG (Player *player)
void OnPlayerJoinArena (Player *player)
void GetCustomGetArenaTeamId (const Player *player, uint8 slot, uint32 &teamID) const
void GetCustomArenaPersonalRating (const Player *player, uint8 slot, uint32 &rating) const
void OnGetMaxPersonalArenaRatingRequirement (const Player *player, uint32 minSlot, uint32 &maxArenaRating) const
void OnLootItem (Player *player, Item *item, uint32 count, ObjectGuid lootguid)
void OnCreateItem (Player *player, Item *item, uint32 count)
void OnQuestRewardItem (Player *player, Item *item, uint32 count)
bool OnBeforePlayerQuestComplete (Player *player, uint32 quest_id)
void OnBeforePlayerDurabilityRepair (Player *player, ObjectGuid npcGUID, ObjectGuid itemGUID, float &discountMod, uint8 guildBank)
void OnBeforeBuyItemFromVendor (Player *player, ObjectGuid vendorguid, uint32 vendorslot, uint32 &item, uint8 count, uint8 bag, uint8 slot)
void OnBeforeStoreOrEquipNewItem (Player *player, uint32 vendorslot, uint32 &item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const *pProto, Creature *pVendor, VendorItem const *crItem, bool bStore)
void OnAfterStoreOrEquipNewItem (Player *player, uint32 vendorslot, Item *item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const *pProto, Creature *pVendor, VendorItem const *crItem, bool bStore)
void OnAfterUpdateMaxPower (Player *player, Powers &power, float &value)
void OnAfterUpdateMaxHealth (Player *player, float &value)
void OnBeforeUpdateAttackPowerAndDamage (Player *player, float &level, float &val2, bool ranged)
void OnAfterUpdateAttackPowerAndDamage (Player *player, float &level, float &base_attPower, float &attPowerMod, float &attPowerMultiplier, bool ranged)
void OnBeforeInitTalentForLevel (Player *player, uint8 &level, uint32 &talentPointsForLevel)
void OnFirstLogin (Player *player)
void OnPlayerCompleteQuest (Player *player, Quest const *quest)
void OnBattlegroundDesertion (Player *player, BattlegroundDesertionType const desertionType)
bool CanJoinInBattlegroundQueue (Player *player, ObjectGuid BattlemasterGuid, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, GroupJoinBattlegroundResult &err)
bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *player)
void OnBeforeTempSummonInitStats (Player *player, TempSummon *tempSummon, uint32 &duration)
void OnBeforeGuardianInitStatsForLevel (Player *player, Guardian *guardian, CreatureTemplate const *cinfo, PetType &petType)
void OnAfterGuardianInitStatsForLevel (Player *player, Guardian *guardian)
void OnBeforeLoadPetFromDB (Player *player, uint32 &petentry, uint32 &petnumber, bool &current, bool &forceLoadFromDB)
bool CanJoinInArenaQueue (Player *player, ObjectGuid BattlemasterGuid, uint8 arenaslot, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, uint8 IsRated, GroupJoinBattlegroundResult &err)
bool CanBattleFieldPort (Player *player, uint8 arenaType, BattlegroundTypeId BGTypeID, uint8 action)
bool CanGroupInvite (Player *player, std::string &membername)
bool CanGroupAccept (Player *player, Group *group)
bool CanSellItem (Player *player, Item *item, Creature *creature)
bool CanSendMail (Player *player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string &subject, std::string &body, uint32 money, uint32 COD, Item *item)
void PetitionBuy (Player *player, Creature *creature, uint32 &charterid, uint32 &cost, uint32 &type)
void PetitionShowList (Player *player, Creature *creature, uint32 &CharterEntry, uint32 &CharterDispayID, uint32 &CharterCost)
void OnRewardKillRewarder (Player *player, bool isDungeon, float &rate)
bool CanGiveMailRewardAtGiveLevel (Player *player, uint8 level)
void OnDeleteFromDB (CharacterDatabaseTransaction trans, uint32 guid)
bool CanRepopAtGraveyard (Player *player)
void OnGetMaxSkillValue (Player *player, uint32 skill, int32 &result, bool IsPure)
bool CanAreaExploreAndOutdoor (Player *player)
void OnVictimRewardBefore (Player *player, Player *victim, uint32 &killer_title, uint32 &victim_title)
void OnVictimRewardAfter (Player *player, Player *victim, uint32 &killer_title, uint32 &victim_rank, float &honor_f)
void OnCustomScalingStatValueBefore (Player *player, ItemTemplate const *proto, uint8 slot, bool apply, uint32 &CustomScalingStatValue)
void OnCustomScalingStatValue (Player *player, ItemTemplate const *proto, uint32 &statType, int32 &val, uint8 itemProtoStatNumber, uint32 ScalingStatValue, ScalingStatValuesEntry const *ssv)
bool CanArmorDamageModifier (Player *player)
void OnGetFeralApBonus (Player *player, int32 &feral_bonus, int32 dpsMod, ItemTemplate const *proto, ScalingStatValuesEntry const *ssv)
bool CanApplyWeaponDependentAuraDamageMod (Player *player, Item *item, WeaponAttackType attackType, AuraEffect const *aura, bool apply)
bool CanApplyEquipSpell (Player *player, SpellInfo const *spellInfo, Item *item, bool apply, bool form_change)
bool CanApplyEquipSpellsItemSet (Player *player, ItemSetEffect *eff)
bool CanCastItemCombatSpell (Player *player, Unit *target, WeaponAttackType attType, uint32 procVictim, uint32 procEx, Item *item, ItemTemplate const *proto)
bool CanCastItemUseSpell (Player *player, Item *item, SpellCastTargets const &targets, uint8 cast_count, uint32 glyphIndex)
void OnApplyAmmoBonuses (Player *player, ItemTemplate const *proto, float &currentAmmoDPS)
bool CanEquipItem (Player *player, uint8 slot, uint16 &dest, Item *pItem, bool swap, bool not_loading)
bool CanUnequipItem (Player *player, uint16 pos, bool swap)
bool CanUseItem (Player *player, ItemTemplate const *proto, InventoryResult &result)
bool CanSaveEquipNewItem (Player *player, Item *item, uint16 pos, bool update)
bool CanApplyEnchantment (Player *player, Item *item, EnchantmentSlot slot, bool apply, bool apply_dur, bool ignore_condition)
void OnGetQuestRate (Player *player, float &result)
bool PassedQuestKilledMonsterCredit (Player *player, Quest const *qinfo, uint32 entry, uint32 real_entry, ObjectGuid guid)
bool CheckItemInSlotAtLoadInventory (Player *player, Item *item, uint8 slot, uint8 &err, uint16 &dest)
bool NotAvoidSatisfy (Player *player, DungeonProgressionRequirements const *ar, uint32 target_map, bool report)
bool NotVisibleGloballyFor (Player *player, Player const *u)
void OnGetArenaPersonalRating (Player *player, uint8 slot, uint32 &result)
void OnGetArenaTeamId (Player *player, uint8 slot, uint32 &result)
void OnIsFFAPvP (Player *player, bool &result)
void OnIsPvP (Player *player, bool &result)
void OnGetMaxSkillValueForLevel (Player *player, uint16 &result)
bool NotSetArenaTeamInfoField (Player *player, uint8 slot, ArenaTeamInfoType type, uint32 value)
bool CanJoinLfg (Player *player, uint8 roles, lfg::LfgDungeonSet &dungeons, const std::string &comment)
bool CanEnterMap (Player *player, MapEntry const *entry, InstanceTemplate const *instance, MapDifficulty const *mapDiff, bool loginCheck)
bool CanInitTrade (Player *player, Player *target)
void OnSetServerSideVisibility (Player *player, ServerSideVisibilityType &type, AccountTypes &sec)
void OnSetServerSideVisibilityDetect (Player *player, ServerSideVisibilityType &type, AccountTypes &sec)
void AnticheatSetSkipOnePacketForASH (Player *player, bool apply)
void AnticheatSetCanFlybyServer (Player *player, bool apply)
void AnticheatSetUnderACKmount (Player *player)
void AnticheatSetRootACKUpd (Player *player)
void AnticheatUpdateMovementInfo (Player *player, MovementInfo const &movementInfo)
void AnticheatSetJumpingbyOpcode (Player *player, bool jump)
bool AnticheatHandleDoubleJump (Player *player, Unit *mover)
bool AnticheatCheckMovementInfo (Player *player, MovementInfo const &movementInfo, Unit *mover, bool jump)
void OnAccountLogin (uint32 accountId)
void OnLastIpUpdate (uint32 accountId, std::string ip)
void OnFailedAccountLogin (uint32 accountId)
void OnEmailChange (uint32 accountId)
void OnFailedEmailChange (uint32 accountId)
void OnPasswordChange (uint32 accountId)
void OnFailedPasswordChange (uint32 accountId)
void OnGuildAddMember (Guild *guild, Player *player, uint8 &plRank)
void OnGuildRemoveMember (Guild *guild, Player *player, bool isDisbanding, bool isKicked)
void OnGuildMOTDChanged (Guild *guild, const std::string &newMotd)
void OnGuildInfoChanged (Guild *guild, const std::string &newInfo)
void OnGuildCreate (Guild *guild, Player *leader, const std::string &name)
void OnGuildDisband (Guild *guild)
void OnGuildMemberWitdrawMoney (Guild *guild, Player *player, uint32 &amount, bool isRepair)
void OnGuildMemberDepositMoney (Guild *guild, Player *player, uint32 &amount)
void OnGuildItemMove (Guild *guild, Player *player, Item *pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
void OnGuildEvent (Guild *guild, uint8 eventType, ObjectGuid::LowType playerGuid1, ObjectGuid::LowType playerGuid2, uint8 newRank)
void OnGuildBankEvent (Guild *guild, uint8 eventType, uint8 tabId, ObjectGuid::LowType playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
bool CanGuildSendBankList (Guild const *guild, WorldSession *session, uint8 tabId, bool sendAllSlots)
void OnGroupAddMember (Group *group, ObjectGuid guid)
void OnGroupInviteMember (Group *group, ObjectGuid guid)
void OnGroupRemoveMember (Group *group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, const char *reason)
void OnGroupChangeLeader (Group *group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
void OnGroupDisband (Group *group)
bool CanGroupJoinBattlegroundQueue (Group const *group, Player *member, Battleground const *bgTemplate, uint32 MinPlayerCount, bool isRated, uint32 arenaSlot)
void OnCreate (Group *group, Player *leader)
void OnGlobalItemDelFromDB (CharacterDatabaseTransaction trans, ObjectGuid::LowType itemGuid)
void OnGlobalMirrorImageDisplayItem (const Item *item, uint32 &display)
void OnBeforeUpdateArenaPoints (ArenaTeam *at, std::map< ObjectGuid, uint32 > &ap)
void OnAfterRefCount (Player const *player, Loot &loot, bool canRate, uint16 lootMode, LootStoreItem *LootStoreItem, uint32 &maxcount, LootStore const &store)
void OnBeforeDropAddItem (Player const *player, Loot &loot, bool canRate, uint16 lootMode, LootStoreItem *LootStoreItem, LootStore const &store)
bool OnItemRoll (Player const *player, LootStoreItem const *LootStoreItem, float &chance, Loot &loot, LootStore const &store)
bool OnBeforeLootEqualChanced (Player const *player, LootStoreItemList EqualChanced, Loot &loot, LootStore const &store)
void OnInitializeLockedDungeons (Player *player, uint8 &level, uint32 &lockData, lfg::LFGDungeonData const *dungeon)
void OnAfterInitializeLockedDungeons (Player *player)
void OnAfterUpdateEncounterState (Map *map, EncounterCreditType type, uint32 creditEntry, Unit *source, Difficulty difficulty_fixed, DungeonEncounterList const *encounters, uint32 dungeonCompleted, bool updated)
void OnBeforeWorldObjectSetPhaseMask (WorldObject const *worldObject, uint32 &oldPhaseMask, uint32 &newPhaseMask, bool &useCombinedPhases, bool &update)
uint32 IncreaseScheduledScriptsCount ()
uint32 DecreaseScheduledScriptCount ()
uint32 DecreaseScheduledScriptCount (size_t count)
bool IsScriptScheduled () const
void OnHeal (Unit *healer, Unit *reciever, uint32 &gain)
void OnDamage (Unit *attacker, Unit *victim, uint32 &damage)
void ModifyPeriodicDamageAurasTick (Unit *target, Unit *attacker, uint32 &damage)
void ModifyMeleeDamage (Unit *target, Unit *attacker, uint32 &damage)
void ModifySpellDamageTaken (Unit *target, Unit *attacker, int32 &damage)
void ModifyHealRecieved (Unit *target, Unit *attacker, uint32 &addHealth)
uint32 DealDamage (Unit *AttackerUnit, Unit *pVictim, uint32 damage, DamageEffectType damagetype)
void OnBeforeRollMeleeOutcomeAgainst (const Unit *attacker, const Unit *victim, WeaponAttackType attType, int32 &attackerMaxSkillValueForLevel, int32 &victimMaxSkillValueForLevel, int32 &attackerWeaponSkill, int32 &victimDefenseSkill, int32 &crit_chance, int32 &miss_chance, int32 &dodge_chance, int32 &parry_chance, int32 &block_chance)
void OnAuraRemove (Unit *unit, AuraApplication *aurApp, AuraRemoveMode mode)
bool IfNormalReaction (Unit const *unit, Unit const *target, ReputationRank &repRank)
bool IsNeedModSpellDamagePercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool IsNeedModMeleeDamagePercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool IsNeedModHealPercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool CanSetPhaseMask (Unit const *unit, uint32 newPhaseMask, bool update)
bool IsCustomBuildValuesUpdate (Unit const *unit, uint8 updateType, ByteBuffer &fieldBuffer, Player const *target, uint16 index)
void OnPlayerMove (Player *player, MovementInfo movementInfo, uint32 opcode)
void Creature_SelectLevel (const CreatureTemplate *cinfo, Creature *creature)
void OnBattlegroundStart (Battleground *bg)
void OnBattlegroundEndReward (Battleground *bg, Player *player, TeamId winnerTeamId)
void OnBattlegroundUpdate (Battleground *bg, uint32 diff)
void OnBattlegroundAddPlayer (Battleground *bg, Player *player)
void OnBattlegroundBeforeAddPlayer (Battleground *bg, Player *player)
void OnBattlegroundRemovePlayerAtLeave (Battleground *bg, Player *player)
void OnQueueUpdate (BattlegroundQueue *queue, BattlegroundBracketId bracket_id, bool isRated, uint32 arenaRatedTeamId)
void OnAddGroup (BattlegroundQueue *queue, GroupQueueInfo *ginfo, uint32 &index, Player *leader, Group *grp, PvPDifficultyEntry const *bracketEntry, bool isPremade)
bool CanFillPlayersToBG (BattlegroundQueue *queue, Battleground *bg, const int32 aliFree, const int32 hordeFree, BattlegroundBracketId bracket_id)
bool CanFillPlayersToBGWithSpecific (BattlegroundQueue *queue, Battleground *bg, const int32 aliFree, const int32 hordeFree, BattlegroundBracketId thisBracketId, BattlegroundQueue *specificQueue, BattlegroundBracketId specificBracketId)
void OnCheckNormalMatch (BattlegroundQueue *queue, uint32 &Coef, Battleground *bgTemplate, BattlegroundBracketId bracket_id, uint32 &minPlayers, uint32 &maxPlayers)
bool CanSendMessageBGQueue (BattlegroundQueue *queue, Player *leader, Battleground *bg, PvPDifficultyEntry const *bracketEntry)
bool OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue *queue, Player *leader, GroupQueueInfo *ginfo, PvPDifficultyEntry const *bracketEntry, bool isRated)
bool OnBeforeSendExitMessageArenaQueue (BattlegroundQueue *queue, GroupQueueInfo *ginfo)
void OnGetSlotByType (const uint32 type, uint8 &slot)
void OnGetArenaPoints (ArenaTeam *at, float &points)
void OnArenaTypeIDToQueueID (const BattlegroundTypeId bgTypeId, const uint8 arenaType, uint32 &queueTypeID)
void OnArenaQueueIdToArenaType (const BattlegroundQueueTypeId bgQueueTypeId, uint8 &ArenaType)
void OnSetArenaMaxPlayersPerTeam (const uint8 arenaType, uint32 &maxPlayerPerTeam)
void OnCalcMaxDuration (Aura const *aura, int32 &maxDuration)
bool CanModAuraEffectDamageDone (AuraEffect const *auraEff, Unit *target, AuraApplication const *aurApp, uint8 mode, bool apply)
bool CanModAuraEffectModDamagePercentDone (AuraEffect const *auraEff, Unit *target, AuraApplication const *aurApp, uint8 mode, bool apply)
void OnSpellCheckCast (Spell *spell, bool strict, SpellCastResult &res)
bool CanPrepare (Spell *spell, SpellCastTargets const *targets, AuraEffect const *triggeredByAura)
bool CanScalingEverything (Spell *spell)
bool CanSelectSpecTalent (Spell *spell)
void OnScaleAuraUnitAdd (Spell *spell, Unit *target, uint32 effectMask, bool checkIfValid, bool implicit, uint8 auraScaleMask, TargetInfo &targetInfo)
void OnRemoveAuraScaleTargets (Spell *spell, TargetInfo &targetInfo, uint8 auraScaleMask, bool &needErase)
void OnBeforeAuraRankForLevel (SpellInfo const *spellInfo, SpellInfo const *latestSpellInfo, uint8 level)
void OnGameEventStart (uint16 EventID)
void OnGameEventStop (uint16 EventID)
void OnBeforeMailDraftSendMailTo (MailDraft *mailDraft, MailReceiver const &receiver, MailSender const &sender, MailCheckMask &checked, uint32 &deliver_delay, uint32 &custom_expiration, bool &deleteMailItemsFromDB, bool &sendMail)
void SetRealmCompleted (AchievementEntry const *achievement)
bool IsCompletedCriteria (AchievementMgr *mgr, AchievementCriteriaEntry const *achievementCriteria, AchievementEntry const *achievement, CriteriaProgress const *progress)
bool IsRealmCompleted (AchievementGlobalMgr const *globalmgr, AchievementEntry const *achievement, std::chrono::system_clock::time_point completionTime)
void OnBeforeCheckCriteria (AchievementMgr *mgr, AchievementCriteriaEntryList const *achievementCriteriaList)
bool CanCheckCriteria (AchievementMgr *mgr, AchievementCriteriaEntry const *achievementCriteria)
void OnInitStatsForLevel (Guardian *guardian, uint8 petlevel)
void OnCalculateMaxTalentPointsForLevel (Pet *pet, uint8 level, uint8 &points)
bool CanUnlearnSpellSet (Pet *pet, uint32 level, uint32 spell)
bool CanUnlearnSpellDefault (Pet *pet, SpellInfo const *spellEntry)
bool CanResetTalents (Pet *pet)
bool CanAddMember (ArenaTeam *team, ObjectGuid PlayerGuid)
void OnGetPoints (ArenaTeam *team, uint32 memberRating, float &points)
bool CanSaveToDB (ArenaTeam *team)
void OnConstructObject (Object *origin)
void OnDestructObject (Object *origin)
void OnConstructPlayer (Player *origin)
void OnDestructPlayer (Player *origin)
void OnConstructGroup (Group *origin)
void OnDestructGroup (Group *origin)
void OnConstructInstanceSave (InstanceSave *origin)
void OnDestructInstanceSave (InstanceSave *origin)
void OnItemCreate (Item *item, ItemTemplate const *itemProto, Player const *owner)
bool CanApplySoulboundFlag (Item *item, ItemTemplate const *proto)
bool CanItemApplyEquipSpell (Player *player, Item *item)
bool CanSendAuctionHello (WorldSession const *session, ObjectGuid guid, Creature *creature)
void ValidateSpellAtCastSpell (Player *player, uint32 &oldSpellId, uint32 &spellId, uint8 &castCount, uint8 &castFlags)
void OnPlayerSetPhase (const AuraEffect *auraEff, AuraApplication const *aurApp, uint8 mode, bool apply, uint32 &newPhase)
void ValidateSpellAtCastSpellResult (Player *player, Unit *mover, Spell *spell, uint32 oldSpellId, uint32 spellId)
void OnAfterLootTemplateProcess (Loot *loot, LootTemplate const *tab, LootStore const &store, Player *lootOwner, bool personal, bool noEmptyError, uint16 lootMode)
void OnInstanceSave (InstanceSave *instanceSave)
void OnHandleDevCommand (Player *player, std::string &argstr)
void OnAfterDatabasesLoaded (uint32 updateFlags)
Static Public Member Functions
static ScriptMgr * instance ()
Private Member Functions
ScriptMgr ()
virtual ~ScriptMgr ()
Private Attributes
uint32 _scriptCount
std::atomic< long > _scheduledScripts
ScriptLoaderCallbackType _script_loader_callback
Friends
class ScriptObject
Detailed Description
Definition at line 1475 of file ScriptMgr.h.
Member Typedef Documentation
ScriptLoaderCallbackType
typedef void(* ScriptMgr::ScriptLoaderCallbackType) ()
Definition at line 1495 of file ScriptMgr.h.
Constructor & Destructor Documentation
ScriptMgr()
ScriptMgr::ScriptMgr () private
Definition at line 51 of file ScriptMgr.cpp.
     : _scriptCount(0), _scheduledScripts(0), _script_loader_callback(nullptr) { }
Member Function Documentation
AnticheatCheckMovementInfo()
bool ScriptMgr::AnticheatCheckMovementInfo (Player * player, MovementInfo const & movementInfo, Unit * mover, bool jump)
Definition at line 2710 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->AnticheatCheckMovementInfo(player, movementInfo, mover, jump))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
AnticheatHandleDoubleJump()
bool ScriptMgr::AnticheatHandleDoubleJump (Player * player, Unit * mover)
Definition at line 2699 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->AnticheatHandleDoubleJump(player, mover))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
AnticheatSetCanFlybyServer()
void ScriptMgr::AnticheatSetCanFlybyServer (Player * player, bool apply)
Definition at line 2674 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatSetCanFlybyServer(player, apply);
 }
References ByteConverter::apply(), and FOREACH_SCRIPT.
AnticheatSetJumpingbyOpcode()
void ScriptMgr::AnticheatSetJumpingbyOpcode (Player * player, bool jump)
Definition at line 2689 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatSetJumpingbyOpcode(player, jump);
 }
References FOREACH_SCRIPT.
AnticheatSetRootACKUpd()
void ScriptMgr::AnticheatSetRootACKUpd (Player * player)
Definition at line 2684 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatSetRootACKUpd(player);
 }
References FOREACH_SCRIPT.
AnticheatSetSkipOnePacketForASH()
void ScriptMgr::AnticheatSetSkipOnePacketForASH (Player * player, bool apply)
Definition at line 2669 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatSetSkipOnePacketForASH(player, apply);
 }
References ByteConverter::apply(), and FOREACH_SCRIPT.
AnticheatSetUnderACKmount()
void ScriptMgr::AnticheatSetUnderACKmount (Player * player)
Definition at line 2679 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatSetUnderACKmount(player);
 }
References FOREACH_SCRIPT.
AnticheatUpdateMovementInfo()
void ScriptMgr::AnticheatUpdateMovementInfo (Player * player, MovementInfo const & movementInfo)
Definition at line 2694 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->AnticheatUpdateMovementInfo(player, movementInfo);
 }
References FOREACH_SCRIPT.
CanAddMember()
bool ScriptMgr::CanAddMember (ArenaTeam * team, ObjectGuid PlayerGuid)
Definition at line 3018 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(ArenaScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanAddMember(team, PlayerGuid))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanApplyEnchantment()
bool ScriptMgr::CanApplyEnchantment (Player * player, Item * item, EnchantmentSlot slot, bool apply, bool apply_dur, bool ignore_condition)
Definition at line 2530 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanApplyEnchantment(player, item, slot, apply, apply_dur, ignore_condition))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References ByteConverter::apply(), FOR_SCRIPTS_RET, and ret.
CanApplyEquipSpell()
bool ScriptMgr::CanApplyEquipSpell (Player * player, SpellInfo const * spellInfo, Item * item, bool apply, bool form_change)
Definition at line 2437 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanApplyEquipSpell(player, spellInfo, item, apply, form_change))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References ByteConverter::apply(), FOR_SCRIPTS_RET, and ret.
CanApplyEquipSpellsItemSet()
bool ScriptMgr::CanApplyEquipSpellsItemSet (Player * player, ItemSetEffect * eff)
Definition at line 2448 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanApplyEquipSpellsItemSet(player, eff))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanApplySoulboundFlag()
bool ScriptMgr::CanApplySoulboundFlag (Item * item, ItemTemplate const * proto)
Definition at line 3050 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(MiscScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanApplySoulboundFlag(item, proto))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanApplyWeaponDependentAuraDamageMod()
bool ScriptMgr::CanApplyWeaponDependentAuraDamageMod (Player * player, Item * item, WeaponAttackType attackType, AuraEffect const * aura, bool apply)
Definition at line 2426 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanApplyWeaponDependentAuraDamageMod(player, item, attackType, aura, apply))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References ByteConverter::apply(), FOR_SCRIPTS_RET, and ret.
CanAreaExploreAndOutdoor()
bool ScriptMgr::CanAreaExploreAndOutdoor (Player * player)
Definition at line 2379 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanAreaExploreAndOutdoor(player))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanArmorDamageModifier()
bool ScriptMgr::CanArmorDamageModifier (Player * player)
Definition at line 2410 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanArmorDamageModifier(player))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanBattleFieldPort()
bool ScriptMgr::CanBattleFieldPort (Player * player, uint8 arenaType, BattlegroundTypeId BGTypeID, uint8 action)
Definition at line 2277 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanBattleFieldPort(player, arenaType, BGTypeID, action))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanCastItemCombatSpell()
bool ScriptMgr::CanCastItemCombatSpell (Player * player, Unit * target, WeaponAttackType attType, uint32 procVictim, uint32 procEx, Item * item, ItemTemplate const * proto)
Definition at line 2459 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanCastItemCombatSpell(player, target, attType, procVictim, procEx, item, proto))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanCastItemUseSpell()
bool ScriptMgr::CanCastItemUseSpell (Player * player, Item * item, SpellCastTargets const & targets, uint8 cast_count, uint32 glyphIndex)
Definition at line 2470 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanCastItemUseSpell(player, item, targets, cast_count, glyphIndex))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanCheckCriteria()
bool ScriptMgr::CanCheckCriteria (AchievementMgr * mgr, AchievementCriteriaEntry const * achievementCriteria)
Definition at line 2964 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(AchievementScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanCheckCriteria(mgr, achievementCriteria))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanEnterMap()
bool ScriptMgr::CanEnterMap (Player * player, MapEntry const * entry, InstanceTemplate const * instance, MapDifficulty const * mapDiff, bool loginCheck)
Definition at line 2637 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanEnterMap(player, entry, instance, mapDiff, loginCheck))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, instance(), and ret.
CanEquipItem()
bool ScriptMgr::CanEquipItem (Player * player, uint8 slot, uint16 & dest, Item * pItem, bool swap, bool not_loading)
Definition at line 2486 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanEquipItem(player, slot, dest, pItem, swap, not_loading))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, ret, and swap().
CanFillPlayersToBG()
bool ScriptMgr::CanFillPlayersToBG (BattlegroundQueue * queue, Battleground * bg, const int32 aliFree, const int32 hordeFree, BattlegroundBracketId bracket_id)
Definition at line 2165 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(BGScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->CanFillPlayersToBG(queue, bg, aliFree, hordeFree, bracket_id))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References bg(), FOR_SCRIPTS_RET, and ret.
CanFillPlayersToBGWithSpecific()
bool ScriptMgr::CanFillPlayersToBGWithSpecific (BattlegroundQueue * queue, Battleground * bg, const int32 aliFree, const int32 hordeFree, BattlegroundBracketId thisBracketId, BattlegroundQueue * specificQueue, BattlegroundBracketId specificBracketId)
Definition at line 2176 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(BGScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->CanFillPlayersToBGWithSpecific(queue, bg, aliFree, hordeFree, thisBracketId, specificQueue, specificBracketId))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References bg(), FOR_SCRIPTS_RET, and ret.
CanGiveMailRewardAtGiveLevel()
bool ScriptMgr::CanGiveMailRewardAtGiveLevel (Player * player, uint8 level)
Definition at line 2347 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanGiveMailRewardAtGiveLevel(player, level))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanGroupAccept()
bool ScriptMgr::CanGroupAccept (Player * player, Group * group)
Definition at line 2299 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanGroupAccept(player, group))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanGroupInvite()
bool ScriptMgr::CanGroupInvite (Player * player, std::string & membername)
Definition at line 2288 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanGroupInvite(player, membername))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanGroupJoinBattlegroundQueue()
bool ScriptMgr::CanGroupJoinBattlegroundQueue (Group const * group, Player * member, Battleground const * bgTemplate, uint32 MinPlayerCount, bool isRated, uint32 arenaSlot)
Definition at line 2732 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(GroupScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanGroupJoinBattlegroundQueue(group, member, bgTemplate, MinPlayerCount, isRated, arenaSlot))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanGuildSendBankList()
bool ScriptMgr::CanGuildSendBankList (Guild const * guild, WorldSession * session, uint8 tabId, bool sendAllSlots)
Definition at line 2721 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(GuildScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanGuildSendBankList(guild, session, tabId, sendAllSlots))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanInitTrade()
bool ScriptMgr::CanInitTrade (Player * player, Player * target)
Definition at line 2648 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanInitTrade(player, target))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanItemApplyEquipSpell()
bool ScriptMgr::CanItemApplyEquipSpell (Player * player, Item * item)
Definition at line 3101 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(MiscScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanItemApplyEquipSpell(player, item))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanJoinInArenaQueue()
bool ScriptMgr::CanJoinInArenaQueue (Player * player, ObjectGuid BattlemasterGuid, uint8 arenaslot, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, uint8 IsRated, GroupJoinBattlegroundResult & err)
Definition at line 2266 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanJoinInArenaQueue(player, BattlemasterGuid, arenaslot, BGTypeID, joinAsGroup, IsRated, err))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanJoinInBattlegroundQueue()
bool ScriptMgr::CanJoinInBattlegroundQueue (Player * player, ObjectGuid BattlemasterGuid, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, GroupJoinBattlegroundResult & err)
Definition at line 1754 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->CanJoinInBattlegroundQueue(player, BattlemasterGuid, BGTypeID, joinAsGroup, err))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanJoinLfg()
bool ScriptMgr::CanJoinLfg (Player * player, uint8 roles, lfg::LfgDungeonSet & dungeons, const std::string & comment)
Definition at line 2626 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanJoinLfg(player, roles, dungeons, comment))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanModAuraEffectDamageDone()
bool ScriptMgr::CanModAuraEffectDamageDone (AuraEffect const * auraEff, Unit * target, AuraApplication const * aurApp, uint8 mode, bool apply)
Definition at line 2857 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(SpellSC, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanModAuraEffectDamageDone(auraEff, target, aurApp, mode, apply))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References ByteConverter::apply(), FOR_SCRIPTS_RET, and ret.
CanModAuraEffectModDamagePercentDone()
bool ScriptMgr::CanModAuraEffectModDamagePercentDone (AuraEffect const * auraEff, Unit * target, AuraApplication const * aurApp, uint8 mode, bool apply)
Definition at line 2868 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(SpellSC, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanModAuraEffectModDamagePercentDone(auraEff, target, aurApp, mode, apply))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References ByteConverter::apply(), FOR_SCRIPTS_RET, and ret.
CanPrepare()
bool ScriptMgr::CanPrepare (Spell * spell, SpellCastTargets const * targets, AuraEffect const * triggeredByAura)
Definition at line 2884 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(SpellSC, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanPrepare(spell, targets, triggeredByAura))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanRepopAtGraveyard()
bool ScriptMgr::CanRepopAtGraveyard (Player * player)
Definition at line 2363 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanRepopAtGraveyard(player))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanResetTalents()
bool ScriptMgr::CanResetTalents (Pet * pet)
Definition at line 3007 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PetScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanResetTalents(pet))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSaveEquipNewItem()
bool ScriptMgr::CanSaveEquipNewItem (Player * player, Item * item, uint16 pos, bool update)
Definition at line 2519 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSaveEquipNewItem(player, item, pos, update))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, pos(), and ret.
CanSaveToDB()
bool ScriptMgr::CanSaveToDB (ArenaTeam * team)
Definition at line 3034 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(ArenaScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSaveToDB(team))
             ret = false; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanScalingEverything()
bool ScriptMgr::CanScalingEverything (Spell * spell)
Definition at line 2895 of file ScriptMgr.cpp.
 {
     bool ret = false;
     FOR_SCRIPTS_RET(SpellSC, itr, end, ret) // return true by default if not scripts
         if (itr->second->CanScalingEverything(spell))
             ret = true; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSelectSpecTalent()
bool ScriptMgr::CanSelectSpecTalent (Spell * spell)
Definition at line 2906 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(SpellSC, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSelectSpecTalent(spell))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSellItem()
bool ScriptMgr::CanSellItem (Player * player, Item * item, Creature * creature)
Definition at line 2310 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSellItem(player, item, creature))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSendAuctionHello()
bool ScriptMgr::CanSendAuctionHello (WorldSession const * session, ObjectGuid guid, Creature * creature)
Definition at line 3112 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(MiscScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSendAuctionHello(session, guid, creature))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSendMail()
bool ScriptMgr::CanSendMail (Player * player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string & subject, std::string & body, uint32 money, uint32 COD, Item * item)
Definition at line 2321 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSendMail(player, receiverGuid, mailbox, subject, body, money, COD, item))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanSendMessageBGQueue()
bool ScriptMgr::CanSendMessageBGQueue (BattlegroundQueue * queue, Player * leader, Battleground * bg, PvPDifficultyEntry const * bracketEntry)
Definition at line 2824 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(BGScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSendMessageBGQueue(queue, leader, bg, bracketEntry))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References bg(), FOR_SCRIPTS_RET, and ret.
CanSetPhaseMask()
bool ScriptMgr::CanSetPhaseMask (Unit const * unit, uint32 newPhaseMask, bool update)
Definition at line 2797 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanSetPhaseMask(unit, newPhaseMask, update))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanUnequipItem()
bool ScriptMgr::CanUnequipItem (Player * player, uint16 pos, bool swap)
Definition at line 2497 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanUnequipItem(player, pos, swap))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, pos(), ret, and swap().
CanUnlearnSpellDefault()
bool ScriptMgr::CanUnlearnSpellDefault (Pet * pet, SpellInfo const * spellEntry)
Definition at line 2996 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PetScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanUnlearnSpellDefault(pet, spellEntry))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanUnlearnSpellSet()
bool ScriptMgr::CanUnlearnSpellSet (Pet * pet, uint32 level, uint32 spell)
Definition at line 2985 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PetScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanUnlearnSpellSet(pet, level, spell))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CanUseItem()
bool ScriptMgr::CanUseItem (Player * player, ItemTemplate const * proto, InventoryResult & result)
Definition at line 2508 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CanUseItem(player, proto, result))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CheckIfScriptsInDatabaseExist()
void ScriptMgr::CheckIfScriptsInDatabaseExist ()
Definition at line 157 of file ScriptMgr.cpp.
 {
     for (auto const& scriptName : sObjectMgr->GetScriptNames())
     {
         if (uint32 sid = sObjectMgr->GetScriptId(scriptName.c_str()))
         {
             if (!ScriptRegistry<SpellScriptLoader>::GetScriptById(sid) &&
                 !ScriptRegistry<ServerScript>::GetScriptById(sid) &&
                 !ScriptRegistry<WorldScript>::GetScriptById(sid) &&
                 !ScriptRegistry<FormulaScript>::GetScriptById(sid) &&
                 !ScriptRegistry<WorldMapScript>::GetScriptById(sid) &&
                 !ScriptRegistry<InstanceMapScript>::GetScriptById(sid) &&
                 !ScriptRegistry<BattlegroundMapScript>::GetScriptById(sid) &&
                 !ScriptRegistry<ItemScript>::GetScriptById(sid) &&
                 !ScriptRegistry<CreatureScript>::GetScriptById(sid) &&
                 !ScriptRegistry<GameObjectScript>::GetScriptById(sid) &&
                 !ScriptRegistry<AreaTriggerScript>::GetScriptById(sid) &&
                 !ScriptRegistry<BattlegroundScript>::GetScriptById(sid) &&
                 !ScriptRegistry<OutdoorPvPScript>::GetScriptById(sid) &&
                 !ScriptRegistry<CommandScript>::GetScriptById(sid) &&
                 !ScriptRegistry<WeatherScript>::GetScriptById(sid) &&
                 !ScriptRegistry<AuctionHouseScript>::GetScriptById(sid) &&
                 !ScriptRegistry<ConditionScript>::GetScriptById(sid) &&
                 !ScriptRegistry<VehicleScript>::GetScriptById(sid) &&
                 !ScriptRegistry<DynamicObjectScript>::GetScriptById(sid) &&
                 !ScriptRegistry<TransportScript>::GetScriptById(sid) &&
                 !ScriptRegistry<AchievementCriteriaScript>::GetScriptById(sid) &&
                 !ScriptRegistry<PlayerScript>::GetScriptById(sid) &&
                 !ScriptRegistry<GuildScript>::GetScriptById(sid) &&
                 !ScriptRegistry<BGScript>::GetScriptById(sid) &&
                 !ScriptRegistry<AchievementScript>::GetScriptById(sid) &&
                 !ScriptRegistry<ArenaTeamScript>::GetScriptById(sid) &&
                 !ScriptRegistry<SpellSC>::GetScriptById(sid) &&
                 !ScriptRegistry<MiscScript>::GetScriptById(sid) &&
                 !ScriptRegistry<PetScript>::GetScriptById(sid) &&
                 !ScriptRegistry<CommandSC>::GetScriptById(sid) &&
                 !ScriptRegistry<ArenaScript>::GetScriptById(sid) &&
                 !ScriptRegistry<GroupScript>::GetScriptById(sid) &&
                 !ScriptRegistry<DatabaseScript>::GetScriptById(sid))
                 {
                     LOG_ERROR("sql.sql", "Script named '%s' is assigned in the database, but has no code!", scriptName.c_str());
                 }
         }
     }
 }
References LOG_ERROR, and sObjectMgr.
Referenced by LoadDatabase().
CheckItemInSlotAtLoadInventory()
bool ScriptMgr::CheckItemInSlotAtLoadInventory (Player * player, Item * item, uint8 slot, uint8 & err, uint16 & dest)
Definition at line 2557 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->CheckItemInSlotAtLoadInventory(player, item, slot, err, dest))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
CreateAuraScripts()
void ScriptMgr::CreateAuraScripts (uint32 spellId, std::list< AuraScript * > & scriptVector)
Definition at line 311 of file ScriptMgr.cpp.
 {
     SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
     for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
     {
         SpellScriptLoader* tmpscript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
         if (!tmpscript)
             continue;
         AuraScript* script = tmpscript->GetAuraScript();
         if (!script)
             continue;
         script->_Init(&tmpscript->GetName(), spellId);
         scriptVector.push_back(script);
     }
 }
References _SpellScript::_Init(), SpellScriptLoader::GetAuraScript(), ScriptObject::GetName(), ScriptRegistry< TScript >::GetScriptById(), and sObjectMgr.
CreateBattleground()
Battleground * ScriptMgr::CreateBattleground (BattlegroundTypeId typeId)
Definition at line 1047 of file ScriptMgr.cpp.
 {
     // TODO: Implement script-side battlegrounds.
     ABORT();
     return nullptr;
 }
References ABORT.
CreateInstanceScript()
InstanceScript * ScriptMgr::CreateInstanceScript (InstanceMap * map)
Definition at line 666 of file ScriptMgr.cpp.
 {
     ASSERT(map);
     GET_SCRIPT_RET(InstanceMapScript, map->GetScriptId(), tmpscript, nullptr);
     return tmpscript->GetInstanceScript(map);
 }
References ASSERT, GET_SCRIPT_RET, and InstanceMap::GetScriptId().
CreateOutdoorPvP()
OutdoorPvP * ScriptMgr::CreateOutdoorPvP (OutdoorPvPData const * data)
Definition at line 1054 of file ScriptMgr.cpp.
 {
     ASSERT(data);
     GET_SCRIPT_RET(OutdoorPvPScript, data->ScriptId, tmpscript, nullptr);
     return tmpscript->GetOutdoorPvP();
 }
References ASSERT, and GET_SCRIPT_RET.
CreateSpellScriptLoaders()
void ScriptMgr::CreateSpellScriptLoaders (uint32 spellId, std::vector< std::pair< SpellScriptLoader *, std::multimap< uint32, uint32 >::iterator > > & scriptVector)
Definition at line 332 of file ScriptMgr.cpp.
 {
     SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
     scriptVector.reserve(std::distance(bounds.first, bounds.second));
     for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
     {
         SpellScriptLoader* tmpscript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
         if (!tmpscript)
             continue;
         scriptVector.push_back(std::make_pair(tmpscript, itr));
     }
 }
References G3D::distance(), ScriptRegistry< TScript >::GetScriptById(), and sObjectMgr.
CreateSpellScripts()
void ScriptMgr::CreateSpellScripts (uint32 spellId, std::list< SpellScript * > & scriptVector)
Definition at line 290 of file ScriptMgr.cpp.
 {
     SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
     for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
     {
         SpellScriptLoader* tmpscript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
         if (!tmpscript)
             continue;
         SpellScript* script = tmpscript->GetSpellScript();
         if (!script)
             continue;
         script->_Init(&tmpscript->GetName(), spellId);
         scriptVector.push_back(script);
     }
 }
References _SpellScript::_Init(), ScriptObject::GetName(), ScriptRegistry< TScript >::GetScriptById(), SpellScriptLoader::GetSpellScript(), and sObjectMgr.
Creature_SelectLevel()
void ScriptMgr::Creature_SelectLevel (const CreatureTemplate * cinfo, Creature * creature)
Definition at line 2045 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AllCreatureScript)->Creature_SelectLevel(cinfo, creature);
 }
References FOREACH_SCRIPT.
DealDamage()
uint32 ScriptMgr::DealDamage (Unit * AttackerUnit, Unit * pVictim, uint32 damage, DamageEffectType damagetype)
Definition at line 2039 of file ScriptMgr.cpp.
 {
     FOR_SCRIPTS_RET(UnitScript, itr, end, damage)
     damage = itr->second->DealDamage(AttackerUnit, pVictim, damage, damagetype);
     return damage;
 }
References FOR_SCRIPTS_RET.
DecreaseScheduledScriptCount() [1/2]
uint32 ScriptMgr::DecreaseScheduledScriptCount () inline
Definition at line 1833 of file ScriptMgr.h.
 { return --_scheduledScripts; }
References _scheduledScripts.
DecreaseScheduledScriptCount() [2/2]
uint32 ScriptMgr::DecreaseScheduledScriptCount (size_t count) inline
Definition at line 1834 of file ScriptMgr.h.
 { return _scheduledScripts -= count; }
References _scheduledScripts, and count().
FillSpellSummary()
void ScriptMgr::FillSpellSummary ()
Definition at line 203 of file ScriptMgr.cpp.
 {
     UnitAI::FillAISpellInfo();
     SpellSummary = new TSpellSummary[sSpellMgr->GetSpellInfoStoreSize()];
     SpellInfo const* pTempSpell;
     for (uint32 i = 0; i < sSpellMgr->GetSpellInfoStoreSize(); ++i)
     {
         SpellSummary[i].Effects = 0;
         SpellSummary[i].Targets = 0;
         pTempSpell = sSpellMgr->GetSpellInfo(i);
         // This spell doesn't exist.
         if (!pTempSpell)
             continue;
         for (uint32 j = 0; j < MAX_SPELL_EFFECTS; ++j)
         {
             // Spell targets self.
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SELF - 1);
             // Spell targets a single enemy.
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_TARGET_ENEMY)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SINGLE_ENEMY - 1);
             // Spell targets AoE at enemy.
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_SRC_AREA_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_DEST_AREA_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_DYNOBJ_ENEMY)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_AOE_ENEMY - 1);
             // Spell targets an enemy.
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_TARGET_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_SRC_AREA_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_DEST_AREA_ENEMY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_DYNOBJ_ENEMY)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_ANY_ENEMY - 1);
             // Spell targets a single friend (or self).
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ALLY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_PARTY)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SINGLE_FRIEND - 1);
             // Spell targets AoE friends.
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER_AREA_PARTY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_LASTTARGET_AREA_PARTY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_AOE_FRIEND - 1);
             // Spell targets any friend (or self).
             if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ALLY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_PARTY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER_AREA_PARTY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_LASTTARGET_AREA_PARTY ||
                     pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER)
                 SpellSummary[i].Targets |= 1 << (SELECT_TARGET_ANY_FRIEND - 1);
             // Make sure that this spell includes a damage effect.
             if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_SCHOOL_DAMAGE ||
                     pTempSpell->Effects[j].Effect == SPELL_EFFECT_INSTAKILL ||
                     pTempSpell->Effects[j].Effect == SPELL_EFFECT_ENVIRONMENTAL_DAMAGE ||
                     pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEALTH_LEECH)
                 SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_DAMAGE - 1);
             // Make sure that this spell includes a healing effect (or an apply aura with a periodic heal).
             if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL ||
                     pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL_MAX_HEALTH ||
                     pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL_MECHANICAL ||
                     (pTempSpell->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA  && pTempSpell->Effects[j].ApplyAuraName == 8))
                 SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_HEALING - 1);
             // Make sure that this spell applies an aura.
             if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA)
                 SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_AURA - 1);
         }
     }
 }
References TSpellSummary::Effects, SpellInfo::Effects, UnitAI::FillAISpellInfo(), MAX_SPELL_EFFECTS, SELECT_EFFECT_AURA, SELECT_EFFECT_DAMAGE, SELECT_EFFECT_HEALING, SELECT_TARGET_ANY_ENEMY, SELECT_TARGET_ANY_FRIEND, SELECT_TARGET_AOE_ENEMY, SELECT_TARGET_AOE_FRIEND, SELECT_TARGET_SELF, SELECT_TARGET_SINGLE_ENEMY, SELECT_TARGET_SINGLE_FRIEND, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_SCHOOL_DAMAGE, SpellSummary, sSpellMgr, TARGET_DEST_DYNOBJ_ENEMY, TARGET_DEST_TARGET_ENEMY, TARGET_SRC_CASTER, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_AREA_PARTY, TARGET_UNIT_DEST_AREA_ENEMY, TARGET_UNIT_LASTTARGET_AREA_PARTY, TARGET_UNIT_SRC_AREA_ENEMY, TARGET_UNIT_TARGET_ALLY, TARGET_UNIT_TARGET_ENEMY, TARGET_UNIT_TARGET_PARTY, and TSpellSummary::Targets.
Referenced by LoadDatabase().
GetChatCommands()
Acore::ChatCommands::ChatCommandTable ScriptMgr::GetChatCommands ()
Definition at line 1062 of file ScriptMgr.cpp.
 {
     Acore::ChatCommands::ChatCommandTable table;
     FOR_SCRIPTS(CommandScript, itr, end)
     {
         Acore::ChatCommands::ChatCommandTable cmds = itr->second->GetCommands();
         std::move(cmds.begin(), cmds.end(), std::back_inserter(table));
     }
     return table;
 }
References FOR_SCRIPTS.
GetCreatureAI()
CreatureAI * ScriptMgr::GetCreatureAI (Creature * creature)
Definition at line 877 of file ScriptMgr.cpp.
 {
     ASSERT(creature);
 #ifdef ELUNA
     if (CreatureAI* luaAI = sEluna->GetAI(creature))
         return luaAI;
 #endif
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, nullptr);
     return tmpscript->GetAI(creature);
 }
References ASSERT, GET_SCRIPT_RET, and Creature::GetScriptId().
GetCustomArenaPersonalRating()
void ScriptMgr::GetCustomArenaPersonalRating (const Player * player, uint8 slot, uint32 & rating) const
Definition at line 1721 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->GetCustomArenaPersonalRating(player, slot, rating);
 }
References FOREACH_SCRIPT.
GetCustomGetArenaTeamId()
void ScriptMgr::GetCustomGetArenaTeamId (const Player * player, uint8 slot, uint32 & teamID) const
Definition at line 1716 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->GetCustomGetArenaTeamId(player, slot, teamID);
 }
References FOREACH_SCRIPT.
GetDialogStatus() [1/2]
uint32 ScriptMgr::GetDialogStatus (Player * player, Creature * creature)
Definition at line 867 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, DIALOG_STATUS_SCRIPTED_NO_STATUS);
     ClearGossipMenuFor(player);
     return tmpscript->GetDialogStatus(player, creature);
 }
References ASSERT, ClearGossipMenuFor(), DIALOG_STATUS_SCRIPTED_NO_STATUS, GET_SCRIPT_RET, and Creature::GetScriptId().
GetDialogStatus() [2/2]
uint32 ScriptMgr::GetDialogStatus (Player * player, GameObject * go)
Definition at line 969 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, DIALOG_STATUS_SCRIPTED_NO_STATUS);
     ClearGossipMenuFor(player);
     return tmpscript->GetDialogStatus(player, go);
 }
References ASSERT, ClearGossipMenuFor(), DIALOG_STATUS_SCRIPTED_NO_STATUS, GET_SCRIPT_RET, and GameObject::GetScriptId().
GetGameObjectAI()
GameObjectAI * ScriptMgr::GetGameObjectAI (GameObject * go)
Definition at line 1023 of file ScriptMgr.cpp.
 {
     ASSERT(go);
 #ifdef ELUNA
     sEluna->OnSpawn(go);
 #endif
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, nullptr);
     return tmpscript->GetAI(go);
 }
References ASSERT, GET_SCRIPT_RET, and GameObject::GetScriptId().
GetScriptCount()
uint32 ScriptMgr::GetScriptCount () const inline
Definition at line 1493 of file ScriptMgr.h.
 { return _scriptCount; }
References _scriptCount.
Referenced by LoadDatabase().
IfNormalReaction()
bool ScriptMgr::IfNormalReaction (Unit const * unit, Unit const * target, ReputationRank & repRank)
Definition at line 2753 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IfNormalReaction(unit, target, repRank))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IncreaseScheduledScriptsCount()
uint32 ScriptMgr::IncreaseScheduledScriptsCount () inline
Definition at line 1832 of file ScriptMgr.h.
 { return ++_scheduledScripts; }
References _scheduledScripts.
IncrementScriptCount()
void ScriptMgr::IncrementScriptCount () inline
Definition at line 1492 of file ScriptMgr.h.
 { ++_scriptCount; }
References _scriptCount.
Initialize()
void ScriptMgr::Initialize (void)
Definition at line 62 of file ScriptMgr.cpp.
 {
     LOG_INFO("server.loading", "> Loading C++ scripts");
     LOG_INFO("server.loading", " ");
     AddSC_SmartScripts();
     ASSERT(_script_loader_callback,
         "Script loader callback wasn't registered!");
     _script_loader_callback();
 }
References _script_loader_callback, AddSC_SmartScripts(), ASSERT, and LOG_INFO.
instance()
ScriptMgr * ScriptMgr::instance () static
Definition at line 56 of file ScriptMgr.cpp.
 {
     static ScriptMgr instance;
     return &instance;
 }
Referenced by CanEnterMap().
IsCompletedCriteria()
bool ScriptMgr::IsCompletedCriteria (AchievementMgr * mgr, AchievementCriteriaEntry const * achievementCriteria, AchievementEntry const * achievement, CriteriaProgress const * progress)
Definition at line 2937 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(AchievementScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IsCompletedCriteria(mgr, achievementCriteria, achievement, progress))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IsCustomBuildValuesUpdate()
bool ScriptMgr::IsCustomBuildValuesUpdate (Unit const * unit, uint8 updateType, ByteBuffer & fieldBuffer, Player const * target, uint16 index)
Definition at line 2808 of file ScriptMgr.cpp.
 {
     bool ret = false;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (itr->second->IsCustomBuildValuesUpdate(unit, updateType, fieldBuffer, target, index))
             ret = true; // we change ret value only when scripts return true
     return ret;
 }
References FOR_SCRIPTS_RET, index, and ret.
IsNeedModHealPercent()
bool ScriptMgr::IsNeedModHealPercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
Definition at line 2786 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IsNeedModHealPercent(unit, auraEff, doneTotalMod, spellProto))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IsNeedModMeleeDamagePercent()
bool ScriptMgr::IsNeedModMeleeDamagePercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
Definition at line 2775 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IsNeedModMeleeDamagePercent(unit, auraEff, doneTotalMod, spellProto))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IsNeedModSpellDamagePercent()
bool ScriptMgr::IsNeedModSpellDamagePercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
Definition at line 2764 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(UnitScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IsNeedModSpellDamagePercent(unit, auraEff, doneTotalMod, spellProto))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IsRealmCompleted()
bool ScriptMgr::IsRealmCompleted (AchievementGlobalMgr const * globalmgr, AchievementEntry const * achievement, std::chrono::system_clock::time_point completionTime)
Definition at line 2948 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(AchievementScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->IsRealmCompleted(globalmgr, achievement, completionTime))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
IsScriptScheduled()
bool ScriptMgr::IsScriptScheduled () const inline
Definition at line 1835 of file ScriptMgr.h.
 { return _scheduledScripts > 0; }
References _scheduledScripts.
LoadDatabase()
void ScriptMgr::LoadDatabase ()
Definition at line 127 of file ScriptMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     sScriptSystemMgr->LoadScriptWaypoints();
     // Add all scripts that must be loaded after db/maps
     ScriptRegistry<WorldMapScript>::AddALScripts();
     ScriptRegistry<BattlegroundMapScript>::AddALScripts();
     ScriptRegistry<InstanceMapScript>::AddALScripts();
     ScriptRegistry<SpellScriptLoader>::AddALScripts();
     ScriptRegistry<ItemScript>::AddALScripts();
     ScriptRegistry<CreatureScript>::AddALScripts();
     ScriptRegistry<GameObjectScript>::AddALScripts();
     ScriptRegistry<AreaTriggerScript>::AddALScripts();
     ScriptRegistry<BattlegroundScript>::AddALScripts();
     ScriptRegistry<OutdoorPvPScript>::AddALScripts();
     ScriptRegistry<WeatherScript>::AddALScripts();
     ScriptRegistry<ConditionScript>::AddALScripts();
     ScriptRegistry<TransportScript>::AddALScripts();
     ScriptRegistry<AchievementCriteriaScript>::AddALScripts();
     FillSpellSummary();
     CheckIfScriptsInDatabaseExist();
     LOG_INFO("server.loading", ">> Loaded %u C++ scripts in %u ms", GetScriptCount(), GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ScriptRegistry< TScript >::AddALScripts(), CheckIfScriptsInDatabaseExist(), FillSpellSummary(), getMSTime(), GetMSTimeDiffToNow(), GetScriptCount(), LOG_INFO, and sScriptSystemMgr.
ModifyHealRecieved()
void ScriptMgr::ModifyHealRecieved (Unit * target, Unit * attacker, uint32 & addHealth)
Definition at line 2074 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->ModifyHealRecieved(target, attacker, damage);
 }
References FOREACH_SCRIPT.
ModifyMeleeDamage()
void ScriptMgr::ModifyMeleeDamage (Unit * target, Unit * attacker, uint32 & damage)
Definition at line 2064 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->ModifyMeleeDamage(target, attacker, damage);
 }
References FOREACH_SCRIPT.
ModifyPeriodicDamageAurasTick()
void ScriptMgr::ModifyPeriodicDamageAurasTick (Unit * target, Unit * attacker, uint32 & damage)
Definition at line 2059 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->ModifyPeriodicDamageAurasTick(target, attacker, damage);
 }
References FOREACH_SCRIPT.
ModifySpellDamageTaken()
void ScriptMgr::ModifySpellDamageTaken (Unit * target, Unit * attacker, int32 & damage)
Definition at line 2069 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->ModifySpellDamageTaken(target, attacker, damage);
 }
References FOREACH_SCRIPT.
NotAvoidSatisfy()
bool ScriptMgr::NotAvoidSatisfy (Player * player, DungeonProgressionRequirements const * ar, uint32 target_map, bool report)
Definition at line 2568 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->NotAvoidSatisfy(player, ar, target_map, report))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
NotSetArenaTeamInfoField()
bool ScriptMgr::NotSetArenaTeamInfoField (Player * player, uint8 slot, ArenaTeamInfoType type, uint32 value)
Definition at line 2615 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->NotSetArenaTeamInfoField(player, slot, type, value))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
NotVisibleGloballyFor()
bool ScriptMgr::NotVisibleGloballyFor (Player * player, Player const * u)
Definition at line 2579 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->NotVisibleGloballyFor(player, u))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnAccountLogin()
void ScriptMgr::OnAccountLogin (uint32 accountId)
Definition at line 1797 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnAccountLogin(accountId);
 }
References FOREACH_SCRIPT.
OnAchievementComplete()
void ScriptMgr::OnAchievementComplete (Player * player, AchievementEntry const * achievement)
Definition at line 1655 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAchiComplete(player, achievement);
 }
References FOREACH_SCRIPT.
OnAchievementSave()
void ScriptMgr::OnAchievementSave (CharacterDatabaseTransaction trans, Player * player, uint16 achiId, CompletedAchievementData achiData)
Definition at line 1676 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAchiSave(trans, player, achiId, achiData);
 }
References FOREACH_SCRIPT.
OnAddCreaturePassenger()
void ScriptMgr::OnAddCreaturePassenger (Transport * transport, Creature * creature)
Definition at line 1280 of file ScriptMgr.cpp.
 {
     ASSERT(transport);
     ASSERT(creature);
     GET_SCRIPT(TransportScript, transport->GetScriptId(), tmpscript);
     tmpscript->OnAddCreaturePassenger(transport, creature);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnAddGroup()
void ScriptMgr::OnAddGroup (BattlegroundQueue * queue, GroupQueueInfo * ginfo, uint32 & index, Player * leader, Group * grp, PvPDifficultyEntry const * bracketEntry, bool isPremade)
Definition at line 2160 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnAddGroup(queue, ginfo, index, leader, grp, bracketEntry, isPremade);
 }
References FOREACH_SCRIPT, and index.
OnAddPassenger() [1/2]
void ScriptMgr::OnAddPassenger (Transport * transport, Player * player)
Definition at line 1271 of file ScriptMgr.cpp.
 {
     ASSERT(transport);
     ASSERT(player);
     GET_SCRIPT(TransportScript, transport->GetScriptId(), tmpscript);
     tmpscript->OnAddPassenger(transport, player);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnAddPassenger() [2/2]
void ScriptMgr::OnAddPassenger (Vehicle * veh, Unit * passenger, int8 seatId)
Definition at line 1235 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
     ASSERT(passenger);
 #ifdef ELUNA
     sEluna->OnAddPassenger(veh, passenger, seatId);
 #endif
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnAddPassenger(veh, passenger, seatId);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnAfterArenaRatingCalculation()
void ScriptMgr::OnAfterArenaRatingCalculation (Battleground *const bg, int32 & winnerMatchmakerChange, int32 & loserMatchmakerChange, int32 & winnerChange, int32 & loserChange)
Definition at line 2124 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnAfterArenaRatingCalculation(bg, winnerMatchmakerChange, loserMatchmakerChange, winnerChange, loserChange);
 }
References bg(), and FOREACH_SCRIPT.
OnAfterConfigLoad()
void ScriptMgr::OnAfterConfigLoad (bool reload)
Definition at line 417 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnConfigLoad(reload, false);
 #endif
     FOREACH_SCRIPT(WorldScript)->OnAfterConfigLoad(reload);
 }
References FOREACH_SCRIPT.
OnAfterDatabasesLoaded()
void ScriptMgr::OnAfterDatabasesLoaded (uint32 updateFlags)
Definition at line 3153 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(DatabaseScript)->OnAfterDatabasesLoaded(updateFlags);
 }
References FOREACH_SCRIPT.
OnAfterGuardianInitStatsForLevel()
void ScriptMgr::OnAfterGuardianInitStatsForLevel (Player * player, Guardian * guardian)
Definition at line 1786 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterGuardianInitStatsForLevel(player, guardian);
 }
References FOREACH_SCRIPT.
OnAfterInitializeLockedDungeons()
void ScriptMgr::OnAfterInitializeLockedDungeons (Player * player)
Definition at line 2023 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnAfterInitializeLockedDungeons(player);
 }
References FOREACH_SCRIPT.
OnAfterLootTemplateProcess()
void ScriptMgr::OnAfterLootTemplateProcess (Loot * loot, LootTemplate const * tab, LootStore const & store, Player * lootOwner, bool personal, bool noEmptyError, uint16 lootMode)
Definition at line 3133 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnAfterLootTemplateProcess(loot, tab, store, lootOwner, personal, noEmptyError, lootMode);
 }
References FOREACH_SCRIPT.
OnAfterPlayerMoveItemFromInventory()
void ScriptMgr::OnAfterPlayerMoveItemFromInventory (Player * player, Item * it, uint8 bag, uint8 slot, bool update)
Definition at line 1696 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterMoveItemFromInventory(player, it, bag, slot, update);
 }
References FOREACH_SCRIPT.
OnAfterPlayerSetVisibleItemSlot()
void ScriptMgr::OnAfterPlayerSetVisibleItemSlot (Player * player, uint8 slot, Item * item)
Definition at line 1691 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterSetVisibleItemSlot(player, slot, item);
 }
References FOREACH_SCRIPT.
OnAfterRefCount()
void ScriptMgr::OnAfterRefCount (Player const * player, Loot & loot, bool canRate, uint16 lootMode, LootStoreItem * LootStoreItem, uint32 & maxcount, LootStore const & store)
Definition at line 1987 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnAfterRefCount(player, LootStoreItem, loot, canRate, lootMode, maxcount, store);
 }
References FOREACH_SCRIPT.
OnAfterStoreOrEquipNewItem()
void ScriptMgr::OnAfterStoreOrEquipNewItem (Player * player, uint32 vendorslot, Item * item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const * pProto, Creature * pVendor, VendorItem const * crItem, bool bStore)
Definition at line 2094 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterStoreOrEquipNewItem(player, vendorslot, item, count, bag, slot, pProto, pVendor, crItem, bStore);
 }
References count(), and FOREACH_SCRIPT.
OnAfterUpdateAttackPowerAndDamage()
void ScriptMgr::OnAfterUpdateAttackPowerAndDamage (Player * player, float & level, float & base_attPower, float & attPowerMod, float & attPowerMultiplier, bool ranged)
Definition at line 2114 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterUpdateAttackPowerAndDamage(player, level, base_attPower, attPowerMod, attPowerMultiplier, ranged);
 }
References FOREACH_SCRIPT.
OnAfterUpdateEncounterState()
void ScriptMgr::OnAfterUpdateEncounterState (Map * map, EncounterCreditType type, uint32 creditEntry, Unit * source, Difficulty difficulty_fixed, DungeonEncounterList const * encounters, uint32 dungeonCompleted, bool updated)
Definition at line 2028 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnAfterUpdateEncounterState(map, type, creditEntry, source, difficulty_fixed, encounters, dungeonCompleted, updated);
 }
References FOREACH_SCRIPT, and updated.
OnAfterUpdateMaxHealth()
void ScriptMgr::OnAfterUpdateMaxHealth (Player * player, float & value)
Definition at line 2104 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterUpdateMaxHealth(player, value);
 }
References FOREACH_SCRIPT.
OnAfterUpdateMaxPower()
void ScriptMgr::OnAfterUpdateMaxPower (Player * player, Powers & power, float & value)
Definition at line 2099 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAfterUpdateMaxPower(player, power, value);
 }
References FOREACH_SCRIPT.
OnApplyAmmoBonuses()
void ScriptMgr::OnApplyAmmoBonuses (Player * player, ItemTemplate const * proto, float & currentAmmoDPS)
Definition at line 2481 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnApplyAmmoBonuses(player, proto, currentAmmoDPS);
 }
References FOREACH_SCRIPT.
OnAreaTrigger()
bool ScriptMgr::OnAreaTrigger (Player * player, AreaTrigger const * trigger)
Definition at line 1035 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(trigger);
 #ifdef ELUNA
     if (sEluna->OnAreaTrigger(player, trigger))
         return false;
 #endif
     GET_SCRIPT_RET(AreaTriggerScript, sObjectMgr->GetAreaTriggerScriptId(trigger->entry), tmpscript, false);
     return tmpscript->OnTrigger(player, trigger);
 }
References ASSERT, AreaTrigger::entry, GET_SCRIPT_RET, and sObjectMgr.
OnArenaQueueIdToArenaType()
void ScriptMgr::OnArenaQueueIdToArenaType (const BattlegroundQueueTypeId bgQueueTypeId, uint8 & ArenaType)
Definition at line 2208 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaTeamScript)->OnQueueIdToArenaType(bgQueueTypeId, ArenaType);
 }
References FOREACH_SCRIPT.
OnArenaTypeIDToQueueID()
void ScriptMgr::OnArenaTypeIDToQueueID (const BattlegroundTypeId bgTypeId, const uint8 arenaType, uint32 & queueTypeID)
Definition at line 2203 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaTeamScript)->OnTypeIDToQueueID(bgTypeId, arenaType, queueTypeID);
 }
References FOREACH_SCRIPT.
OnAuctionAdd()
void ScriptMgr::OnAuctionAdd (AuctionHouseObject * ah, AuctionEntry * entry)
Definition at line 1095 of file ScriptMgr.cpp.
 {
     ASSERT(ah);
     ASSERT(entry);
 #ifdef ELUNA
     sEluna->OnAdd(ah, entry);
 #endif
     FOREACH_SCRIPT(AuctionHouseScript)->OnAuctionAdd(ah, entry);
 }
References ASSERT, and FOREACH_SCRIPT.
OnAuctionExpire()
void ScriptMgr::OnAuctionExpire (AuctionHouseObject * ah, AuctionEntry * entry)
Definition at line 1131 of file ScriptMgr.cpp.
 {
     ASSERT(ah);
     ASSERT(entry);
 #ifdef ELUNA
     sEluna->OnExpire(ah, entry);
 #endif
     FOREACH_SCRIPT(AuctionHouseScript)->OnAuctionExpire(ah, entry);
 }
References ASSERT, and FOREACH_SCRIPT.
OnAuctionRemove()
void ScriptMgr::OnAuctionRemove (AuctionHouseObject * ah, AuctionEntry * entry)
Definition at line 1107 of file ScriptMgr.cpp.
 {
     ASSERT(ah);
     ASSERT(entry);
 #ifdef ELUNA
     sEluna->OnRemove(ah, entry);
 #endif
     FOREACH_SCRIPT(AuctionHouseScript)->OnAuctionRemove(ah, entry);
 }
References ASSERT, and FOREACH_SCRIPT.
OnAuctionSuccessful()
void ScriptMgr::OnAuctionSuccessful (AuctionHouseObject * ah, AuctionEntry * entry)
Definition at line 1119 of file ScriptMgr.cpp.
 {
     ASSERT(ah);
     ASSERT(entry);
 #ifdef ELUNA
     sEluna->OnSuccessful(ah, entry);
 #endif
     FOREACH_SCRIPT(AuctionHouseScript)->OnAuctionSuccessful(ah, entry);
 }
References ASSERT, and FOREACH_SCRIPT.
OnAuraRemove()
void ScriptMgr::OnAuraRemove (Unit * unit, AuraApplication * aurApp, AuraRemoveMode mode)
Definition at line 2748 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->OnAuraRemove(unit, aurApp, mode);
 }
References FOREACH_SCRIPT.
OnBaseGainCalculation()
void ScriptMgr::OnBaseGainCalculation (uint32 & gain, uint8 playerLevel, uint8 mobLevel, ContentLevels content)
Definition at line 479 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnBaseGainCalculation(gain, playerLevel, mobLevel, content);
 }
References FOREACH_SCRIPT.
OnBattlegroundAddPlayer()
void ScriptMgr::OnBattlegroundAddPlayer (Battleground * bg, Player * player)
Definition at line 2145 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundAddPlayer(bg, player);
 }
References bg(), and FOREACH_SCRIPT.
OnBattlegroundBeforeAddPlayer()
void ScriptMgr::OnBattlegroundBeforeAddPlayer (Battleground * bg, Player * player)
Definition at line 2150 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundBeforeAddPlayer(bg, player);
 }
References bg(), and FOREACH_SCRIPT.
OnBattlegroundDesertion()
void ScriptMgr::OnBattlegroundDesertion (Player * player, BattlegroundDesertionType const desertionType)
Definition at line 1348 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBattlegroundDesertion(player, desertionType);
 }
References FOREACH_SCRIPT.
OnBattlegroundEndReward()
void ScriptMgr::OnBattlegroundEndReward (Battleground * bg, Player * player, TeamId winnerTeamId)
Definition at line 2135 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundEndReward(bg, player, winnerTeamId);
 }
References bg(), and FOREACH_SCRIPT.
OnBattlegroundRemovePlayerAtLeave()
void ScriptMgr::OnBattlegroundRemovePlayerAtLeave (Battleground * bg, Player * player)
Definition at line 2155 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundRemovePlayerAtLeave(bg, player);
 }
References bg(), and FOREACH_SCRIPT.
OnBattlegroundStart()
void ScriptMgr::OnBattlegroundStart (Battleground * bg)
Definition at line 2130 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundStart(bg);
 }
References bg(), and FOREACH_SCRIPT.
OnBattlegroundUpdate()
void ScriptMgr::OnBattlegroundUpdate (Battleground * bg, uint32 diff)
Definition at line 2140 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnBattlegroundUpdate(bg, diff);
 }
References bg(), diff(), and FOREACH_SCRIPT.
OnBeforeAchievementComplete()
bool ScriptMgr::OnBeforeAchievementComplete (Player * player, AchievementEntry const * achievement)
Definition at line 1644 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->OnBeforeAchiComplete(player, achievement))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * bidder, uint32 & bidder_accId, bool & sendMail)
Definition at line 1168 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail(auctionHouseMgr, auction, bidder, bidder_accId, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrSendAuctionExpiredMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionExpiredMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, bool & sendNotification, bool & sendMail)
Definition at line 1158 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionExpiredMail(auctionHouseMgr, auction, owner, owner_accId, sendNotification, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * oldBidder, uint32 & oldBidder_accId, Player * newBidder, uint32 & newPrice, bool & sendNotification, bool & sendMail)
Definition at line 1163 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail(auctionHouseMgr, auction, oldBidder, oldBidder_accId, newBidder, newPrice, sendNotification, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrSendAuctionSalePendingMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionSalePendingMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, bool & sendMail)
Definition at line 1148 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionSalePendingMail(auctionHouseMgr, auction, owner, owner_accId, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, uint32 & profit, bool & sendNotification, bool & updateAchievementCriteria, bool & sendMail)
Definition at line 1153 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail(auctionHouseMgr, auction, owner, owner_accId, profit, sendNotification, updateAchievementCriteria, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrSendAuctionWonMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionWonMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * bidder, uint32 & bidder_accId, bool & sendNotification, bool & updateAchievementCriteria, bool & sendMail)
Definition at line 1143 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrSendAuctionWonMail(auctionHouseMgr, auction, bidder, bidder_accId, sendNotification, updateAchievementCriteria, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforeAuctionHouseMgrUpdate()
void ScriptMgr::OnBeforeAuctionHouseMgrUpdate ()
Definition at line 1173 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AuctionHouseScript)->OnBeforeAuctionHouseMgrUpdate();
 }
References FOREACH_SCRIPT.
OnBeforeAuraRankForLevel()
void ScriptMgr::OnBeforeAuraRankForLevel (SpellInfo const * spellInfo, SpellInfo const * latestSpellInfo, uint8 level)
Definition at line 2927 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(SpellSC)->OnBeforeAuraRankForLevel(spellInfo, latestSpellInfo, level);
 }
References FOREACH_SCRIPT.
OnBeforeBuyItemFromVendor()
void ScriptMgr::OnBeforeBuyItemFromVendor (Player * player, ObjectGuid vendorguid, uint32 vendorslot, uint32 & item, uint8 count, uint8 bag, uint8 slot)
Definition at line 2089 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeBuyItemFromVendor(player, vendorguid, vendorslot, item, count, bag, slot);
 }
References count(), and FOREACH_SCRIPT.
OnBeforeCheckCriteria()
void ScriptMgr::OnBeforeCheckCriteria (AchievementMgr * mgr, AchievementCriteriaEntryList const * achievementCriteriaList)
Definition at line 2959 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AchievementScript)->OnBeforeCheckCriteria(mgr, achievementCriteriaList);
 }
References FOREACH_SCRIPT.
OnBeforeConfigLoad()
void ScriptMgr::OnBeforeConfigLoad (bool reload)
Definition at line 409 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnConfigLoad(reload, true);
 #endif
     FOREACH_SCRIPT(WorldScript)->OnBeforeConfigLoad(reload);
 }
References FOREACH_SCRIPT.
OnBeforeCriteriaProgress()
bool ScriptMgr::OnBeforeCriteriaProgress (Player * player, AchievementCriteriaEntry const * criteria)
Definition at line 1660 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->OnBeforeCriteriaProgress(player, criteria))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforeDropAddItem()
void ScriptMgr::OnBeforeDropAddItem (Player const * player, Loot & loot, bool canRate, uint16 lootMode, LootStoreItem * LootStoreItem, LootStore const & store)
Definition at line 1992 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnBeforeDropAddItem(player, loot, canRate, lootMode, LootStoreItem, store);
 }
References FOREACH_SCRIPT.
OnBeforeFinalizePlayerWorldSession()
void ScriptMgr::OnBeforeFinalizePlayerWorldSession (uint32 & cacheVersion)
Definition at line 425 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(WorldScript)->OnBeforeFinalizePlayerWorldSession(cacheVersion);
 }
References FOREACH_SCRIPT.
OnBeforeGuardianInitStatsForLevel()
void ScriptMgr::OnBeforeGuardianInitStatsForLevel (Player * player, Guardian * guardian, CreatureTemplate const * cinfo, PetType & petType)
Definition at line 1781 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeGuardianInitStatsForLevel(player, guardian, cinfo, petType);
 }
References FOREACH_SCRIPT.
OnBeforeInitTalentForLevel()
void ScriptMgr::OnBeforeInitTalentForLevel (Player * player, uint8 & level, uint32 & talentPointsForLevel)
Definition at line 2119 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeInitTalentForLevel(player, level, talentPointsForLevel);
 }
References FOREACH_SCRIPT.
OnBeforeLoadPetFromDB()
void ScriptMgr::OnBeforeLoadPetFromDB (Player * player, uint32 & petentry, uint32 & petnumber, bool & current, bool & forceLoadFromDB)
Definition at line 1791 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeLoadPetFromDB(player, petentry, petnumber, current, forceLoadFromDB);
 }
References FOREACH_SCRIPT.
OnBeforeLootEqualChanced()
bool ScriptMgr::OnBeforeLootEqualChanced (Player const * player, LootStoreItemList EqualChanced, Loot & loot, LootStore const & store)
Definition at line 2008 of file ScriptMgr.cpp.
{
     bool ret = true; // return true by default
     FOR_SCRIPTS_RET(GlobalScript, itr, end, ret)
         if (!itr->second->OnBeforeLootEqualChanced(player, EqualChanced, loot, store))
             ret = false; // we change ret value only when a script returns false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforeMailDraftSendMailTo()
void ScriptMgr::OnBeforeMailDraftSendMailTo (MailDraft * mailDraft, MailReceiver const & receiver, MailSender const & sender, MailCheckMask & checked, uint32 & deliver_delay, uint32 & custom_expiration, bool & deleteMailItemsFromDB, bool & sendMail)
Definition at line 2241 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MailScript)->OnBeforeMailDraftSendMailTo(mailDraft, receiver, sender, checked, deliver_delay, custom_expiration, deleteMailItemsFromDB, sendMail);
 }
References FOREACH_SCRIPT.
OnBeforePlayerDurabilityRepair()
void ScriptMgr::OnBeforePlayerDurabilityRepair (Player * player, ObjectGuid npcGUID, ObjectGuid itemGUID, float & discountMod, uint8 guildBank)
Definition at line 347 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeDurabilityRepair(player, npcGUID, itemGUID, discountMod, guildBank);
 }
References FOREACH_SCRIPT.
OnBeforePlayerQuestComplete()
bool ScriptMgr::OnBeforePlayerQuestComplete (Player * player, uint32 quest_id)
Definition at line 2251 of file ScriptMgr.cpp.
 {
     bool ret=true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->OnBeforeQuestComplete(player, quest_id))
         ret=false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforePlayerTeleport()
bool ScriptMgr::OnBeforePlayerTeleport (Player * player, uint32 mapid, float x, float y, float z, float orientation, uint32 options, Unit * target)
Definition at line 1614 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
     if (!itr->second->OnBeforeTeleport(player, mapid, x, y, z, orientation, options, target))
         ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, ret, G3D::x, G3D::y, and G3D::z.
OnBeforePlayerUpdate()
void ScriptMgr::OnBeforePlayerUpdate (Player * player, uint32 p_time)
Definition at line 1533 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeUpdate(player, p_time);
 }
References FOREACH_SCRIPT.
OnBeforeRollMeleeOutcomeAgainst()
void ScriptMgr::OnBeforeRollMeleeOutcomeAgainst (const Unit * attacker, const Unit * victim, WeaponAttackType attType, int32 & attackerMaxSkillValueForLevel, int32 & victimMaxSkillValueForLevel, int32 & attackerWeaponSkill, int32 & victimDefenseSkill, int32 & crit_chance, int32 & miss_chance, int32 & dodge_chance, int32 & parry_chance, int32 & block_chance)
Definition at line 2079 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->OnBeforeRollMeleeOutcomeAgainst(attacker, victim, attType, attackerMaxSkillValueForLevel, victimMaxSkillValueForLevel, attackerWeaponSkill, victimDefenseSkill, crit_chance, miss_chance, dodge_chance, parry_chance, block_chance);
 }
References FOREACH_SCRIPT.
OnBeforeSendChatMessage()
void ScriptMgr::OnBeforeSendChatMessage (Player * player, uint32 & type, uint32 & lang, std::string & msg)
Definition at line 1484 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeSendChatMessage(player, type, lang, msg);
 }
References FOREACH_SCRIPT.
OnBeforeSendExitMessageArenaQueue()
bool ScriptMgr::OnBeforeSendExitMessageArenaQueue (BattlegroundQueue * queue, GroupQueueInfo * ginfo)
Definition at line 2846 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(BGScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->OnBeforeSendExitMessageArenaQueue(queue, ginfo))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforeSendJoinMessageArenaQueue()
bool ScriptMgr::OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue * queue, Player * leader, GroupQueueInfo * ginfo, PvPDifficultyEntry const * bracketEntry, bool isRated)
Definition at line 2835 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(BGScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->OnBeforeSendJoinMessageArenaQueue(queue, leader, ginfo, bracketEntry, isRated))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnBeforeStoreOrEquipNewItem()
void ScriptMgr::OnBeforeStoreOrEquipNewItem (Player * player, uint32 vendorslot, uint32 & item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const * pProto, Creature * pVendor, VendorItem const * crItem, bool bStore)
Definition at line 2261 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeStoreOrEquipNewItem(player, vendorslot, item, count, bag, slot, pProto, pVendor, crItem, bStore);
 }
References count(), and FOREACH_SCRIPT.
OnBeforeTempSummonInitStats()
void ScriptMgr::OnBeforeTempSummonInitStats (Player * player, TempSummon * tempSummon, uint32 & duration)
Definition at line 1776 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeTempSummonInitStats(player, tempSummon, duration);
 }
References FOREACH_SCRIPT.
OnBeforeUpdateArenaPoints()
void ScriptMgr::OnBeforeUpdateArenaPoints (ArenaTeam * at, std::map< ObjectGuid, uint32 > & ap)
Definition at line 1982 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnBeforeUpdateArenaPoints(at, ap);
 }
References FOREACH_SCRIPT.
OnBeforeUpdateAttackPowerAndDamage()
void ScriptMgr::OnBeforeUpdateAttackPowerAndDamage (Player * player, float & level, float & val2, bool ranged)
Definition at line 2109 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeforeUpdateAttackPowerAndDamage(player, level, val2, ranged);
 }
References FOREACH_SCRIPT.
OnBeforeUpdatingPersonalRating()
void ScriptMgr::OnBeforeUpdatingPersonalRating (int32 & mod, uint32 type)
Definition at line 2246 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnBeforeUpdatingPersonalRating(mod, type);
 }
References FOREACH_SCRIPT, and mod().
OnBeforeWorldObjectSetPhaseMask()
void ScriptMgr::OnBeforeWorldObjectSetPhaseMask (WorldObject const * worldObject, uint32 & oldPhaseMask, uint32 & newPhaseMask, bool & useCombinedPhases, bool & update)
Definition at line 2033 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnBeforeWorldObjectSetPhaseMask(worldObject, oldPhaseMask, newPhaseMask, useCombinedPhases, update);
 }
References FOREACH_SCRIPT.
OnCalcMaxDuration()
void ScriptMgr::OnCalcMaxDuration (Aura const * aura, int32 & maxDuration)
Definition at line 2219 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(SpellSC)->OnCalcMaxDuration(aura, maxDuration);
 }
References FOREACH_SCRIPT.
OnCalculateMaxTalentPointsForLevel()
void ScriptMgr::OnCalculateMaxTalentPointsForLevel (Pet * pet, uint8 level, uint8 & points)
Definition at line 2980 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PetScript)->OnCalculateMaxTalentPointsForLevel(pet, level, points);
 }
References FOREACH_SCRIPT.
OnCastItemCombatSpell()
bool ScriptMgr::OnCastItemCombatSpell (Player * player, Unit * victim, SpellInfo const * spellInfo, Item * item)
Definition at line 730 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(victim);
     ASSERT(spellInfo);
     ASSERT(item);
     GET_SCRIPT_RET(ItemScript, item->GetScriptId(), tmpscript, true);
     return tmpscript->OnCastItemCombatSpell(player, victim, spellInfo, item);
 }
References ASSERT, GET_SCRIPT_RET, and Item::GetScriptId().
OnCheckNormalMatch()
void ScriptMgr::OnCheckNormalMatch (BattlegroundQueue * queue, uint32 & Coef, Battleground * bgTemplate, BattlegroundBracketId bracket_id, uint32 & minPlayers, uint32 & maxPlayers)
Definition at line 2188 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnCheckNormalMatch(queue, Coef, bgTemplate, bracket_id, minPlayers, maxPlayers);
 }
References FOREACH_SCRIPT.
OnColorCodeCalculation()
void ScriptMgr::OnColorCodeCalculation (XPColorChar & color, uint8 playerLevel, uint8 mobLevel)
Definition at line 469 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnColorCodeCalculation(color, playerLevel, mobLevel);
 }
References FOREACH_SCRIPT.
OnConditionCheck()
bool ScriptMgr::OnConditionCheck (Condition * condition, ConditionSourceInfo & sourceInfo)
Definition at line 1178 of file ScriptMgr.cpp.
 {
     ASSERT(condition);
     GET_SCRIPT_RET(ConditionScript, condition->ScriptId, tmpscript, true);
     return tmpscript->OnConditionCheck(condition, sourceInfo);
 }
References ASSERT, GET_SCRIPT_RET, and Condition::ScriptId.
OnConstructGroup()
void ScriptMgr::OnConstructGroup (Group * origin)
Definition at line 3081 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnConstructGroup(origin);
 }
References FOREACH_SCRIPT.
OnConstructInstanceSave()
void ScriptMgr::OnConstructInstanceSave (InstanceSave * origin)
Definition at line 3091 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnConstructInstanceSave(origin);
 }
References FOREACH_SCRIPT.
OnConstructObject()
void ScriptMgr::OnConstructObject (Object * origin)
Definition at line 3061 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnConstructObject(origin);
 }
References FOREACH_SCRIPT.
OnConstructPlayer()
void ScriptMgr::OnConstructPlayer (Player * origin)
Definition at line 3071 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnConstructPlayer(origin);
 }
References FOREACH_SCRIPT.
OnCreate()
void ScriptMgr::OnCreate (Group * group, Player * leader)
Definition at line 2743 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GroupScript)->OnCreate(group, leader);
 }
References FOREACH_SCRIPT.
OnCreateItem()
void ScriptMgr::OnCreateItem (Player * player, Item * item, uint32 count)
Definition at line 1736 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCreateItem(player, item, count);
 }
References count(), and FOREACH_SCRIPT.
OnCreateMap()
void ScriptMgr::OnCreateMap (Map * map)
Definition at line 513 of file ScriptMgr.cpp.
 {
     ASSERT(map);
 #ifdef ELUNA
     sEluna->OnCreate(map);
 #endif
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnCreate(map);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnCreate((InstanceMap*)map);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnCreate((BattlegroundMap*)map);
     SCR_MAP_END;
 }
References ASSERT, SCR_MAP_BGN, and SCR_MAP_END.
OnCreatureKill()
void ScriptMgr::OnCreatureKill (Player * killer, Creature * killed)
Definition at line 1371 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnCreatureKill(killer, killed);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnCreatureKill(killer, killed);
 }
References FOREACH_SCRIPT.
OnCreatureKilledByPet()
void ScriptMgr::OnCreatureKilledByPet (Player * petOwner, Creature * killed)
Definition at line 1379 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCreatureKilledByPet(petOwner, killed);
 }
References FOREACH_SCRIPT.
OnCreatureUpdate()
void ScriptMgr::OnCreatureUpdate (Creature * creature, uint32 diff)
Definition at line 890 of file ScriptMgr.cpp.
 {
     ASSERT(creature);
     FOREACH_SCRIPT(AllCreatureScript)->OnAllCreatureUpdate(creature, diff);
     GET_SCRIPT(CreatureScript, creature->GetScriptId(), tmpscript);
     tmpscript->OnUpdate(creature, diff);
 }
References ASSERT, diff(), FOREACH_SCRIPT, GET_SCRIPT, and Creature::GetScriptId().
OnCriteriaCheck()
bool ScriptMgr::OnCriteriaCheck (uint32 scriptId, Player * source, Unit * target, uint32 criteria_id)
Definition at line 1328 of file ScriptMgr.cpp.
 {
     ASSERT(source);
     // target can be nullptr.
     GET_SCRIPT_RET(AchievementCriteriaScript, scriptId, tmpscript, false);
     return tmpscript->OnCheck(source, target, criteria_id);
 }
References ASSERT, and GET_SCRIPT_RET.
OnCriteriaProgress()
void ScriptMgr::OnCriteriaProgress (Player * player, AchievementCriteriaEntry const * criteria)
Definition at line 1671 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCriteriaProgress(player, criteria);
 }
References FOREACH_SCRIPT.
OnCriteriaSave()
void ScriptMgr::OnCriteriaSave (CharacterDatabaseTransaction trans, Player * player, uint16 critId, CriteriaProgress criteriaData)
Definition at line 1681 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCriteriaSave(trans, player, critId, criteriaData);
 }
References FOREACH_SCRIPT.
OnCustomScalingStatValue()
void ScriptMgr::OnCustomScalingStatValue (Player * player, ItemTemplate const * proto, uint32 & statType, int32 & val, uint8 itemProtoStatNumber, uint32 ScalingStatValue, ScalingStatValuesEntry const * ssv)
Definition at line 2405 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCustomScalingStatValue(player, proto, statType, val, itemProtoStatNumber, ScalingStatValue, ssv);
 }
References FOREACH_SCRIPT.
OnCustomScalingStatValueBefore()
void ScriptMgr::OnCustomScalingStatValueBefore (Player * player, ItemTemplate const * proto, uint8 slot, bool apply, uint32 & CustomScalingStatValue)
Definition at line 2400 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnCustomScalingStatValueBefore(player, proto, slot, apply, CustomScalingStatValue);
 }
References ByteConverter::apply(), and FOREACH_SCRIPT.
OnDamage()
void ScriptMgr::OnDamage (Unit * attacker, Unit * victim, uint32 & damage)
Definition at line 2054 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->OnDamage(attacker, victim, damage);
 }
References FOREACH_SCRIPT.
OnDeleteFromDB()
void ScriptMgr::OnDeleteFromDB (CharacterDatabaseTransaction trans, uint32 guid)
Definition at line 2358 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnDeleteFromDB(trans, guid);
 }
References FOREACH_SCRIPT.
OnDestroyMap()
void ScriptMgr::OnDestroyMap (Map * map)
Definition at line 534 of file ScriptMgr.cpp.
 {
     ASSERT(map);
 #ifdef ELUNA
     sEluna->OnDestroy(map);
 #endif
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnDestroy(map);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnDestroy((InstanceMap*)map);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnDestroy((BattlegroundMap*)map);
     SCR_MAP_END;
 }
References ASSERT, SCR_MAP_BGN, and SCR_MAP_END.
OnDestructGroup()
void ScriptMgr::OnDestructGroup (Group * origin)
Definition at line 3086 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnDestructGroup(origin);
 }
References FOREACH_SCRIPT.
OnDestructInstanceSave()
void ScriptMgr::OnDestructInstanceSave (InstanceSave * origin)
Definition at line 3096 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnDestructInstanceSave(origin);
 }
References FOREACH_SCRIPT.
OnDestructObject()
void ScriptMgr::OnDestructObject (Object * origin)
Definition at line 3066 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnDestructObject(origin);
 }
References FOREACH_SCRIPT.
OnDestructPlayer()
void ScriptMgr::OnDestructPlayer (Player * origin)
Definition at line 3076 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnDestructPlayer(origin);
 }
References FOREACH_SCRIPT.
OnDynamicObjectUpdate()
void ScriptMgr::OnDynamicObjectUpdate (DynamicObject * dynobj, uint32 diff)
Definition at line 1263 of file ScriptMgr.cpp.
 {
     ASSERT(dynobj);
     FOR_SCRIPTS(DynamicObjectScript, itr, end)
     itr->second->OnUpdate(dynobj, diff);
 }
References ASSERT, diff(), and FOR_SCRIPTS.
OnEmailChange()
void ScriptMgr::OnEmailChange (uint32 accountId)
Definition at line 1812 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnEmailChange(accountId);
 }
References FOREACH_SCRIPT.
OnEquip()
void ScriptMgr::OnEquip (Player * player, Item * it, uint8 bag, uint8 slot, bool update)
Definition at line 1701 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnEquip(player, it, bag, slot, update);
 }
References FOREACH_SCRIPT.
OnFailedAccountLogin()
void ScriptMgr::OnFailedAccountLogin (uint32 accountId)
Definition at line 1807 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnFailedAccountLogin(accountId);
 }
References FOREACH_SCRIPT.
OnFailedEmailChange()
void ScriptMgr::OnFailedEmailChange (uint32 accountId)
Definition at line 1817 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnFailedEmailChange(accountId);
 }
References FOREACH_SCRIPT.
OnFailedPasswordChange()
void ScriptMgr::OnFailedPasswordChange (uint32 accountId)
Definition at line 1827 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnFailedPasswordChange(accountId);
 }
References FOREACH_SCRIPT.
OnFirstLogin()
void ScriptMgr::OnFirstLogin (Player * player)
Definition at line 1746 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnFirstLogin(player);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnFirstLogin(player);
 }
References FOREACH_SCRIPT.
OnGainCalculation()
void ScriptMgr::OnGainCalculation (uint32 & gain, Player * player, Unit * unit)
Definition at line 484 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(unit);
     FOREACH_SCRIPT(FormulaScript)->OnGainCalculation(gain, player, unit);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGameEventStart()
void ScriptMgr::OnGameEventStart (uint16 EventID)
Definition at line 2224 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnGameEventStart(EventID);
 #endif
     FOREACH_SCRIPT(GameEventScript)->OnStart(EventID);
 }
References FOREACH_SCRIPT.
OnGameEventStop()
void ScriptMgr::OnGameEventStop (uint16 EventID)
Definition at line 2232 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnGameEventStop(EventID);
 #endif
     FOREACH_SCRIPT(GameEventScript)->OnStop(EventID);
 }
References FOREACH_SCRIPT.
OnGameObjectDamaged()
void ScriptMgr::OnGameObjectDamaged (GameObject * go, Player * player)
Definition at line 987 of file ScriptMgr.cpp.
 {
     ASSERT(go);
     GET_SCRIPT(GameObjectScript, go->GetScriptId(), tmpscript);
     tmpscript->OnDamaged(go, player);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnGameObjectDestroyed()
void ScriptMgr::OnGameObjectDestroyed (GameObject * go, Player * player)
Definition at line 979 of file ScriptMgr.cpp.
 {
     ASSERT(go);
     GET_SCRIPT(GameObjectScript, go->GetScriptId(), tmpscript);
     tmpscript->OnDestroyed(go, player);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnGameObjectLootStateChanged()
void ScriptMgr::OnGameObjectLootStateChanged (GameObject * go, uint32 state, Unit * unit)
Definition at line 995 of file ScriptMgr.cpp.
 {
     ASSERT(go);
     GET_SCRIPT(GameObjectScript, go->GetScriptId(), tmpscript);
     tmpscript->OnLootStateChanged(go, state, unit);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnGameObjectStateChanged()
void ScriptMgr::OnGameObjectStateChanged (GameObject * go, uint32 state)
Definition at line 1003 of file ScriptMgr.cpp.
 {
     ASSERT(go);
     GET_SCRIPT(GameObjectScript, go->GetScriptId(), tmpscript);
     tmpscript->OnGameObjectStateChanged(go, state);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnGameObjectUpdate()
void ScriptMgr::OnGameObjectUpdate (GameObject * go, uint32 diff)
Definition at line 1011 of file ScriptMgr.cpp.
 {
     ASSERT(go);
 #ifdef ELUNA
     sEluna->UpdateAI(go, diff);
 #endif
     GET_SCRIPT(GameObjectScript, go->GetScriptId(), tmpscript);
     tmpscript->OnUpdate(go, diff);
 }
References ASSERT, diff(), GET_SCRIPT, and GameObject::GetScriptId().
OnGetArenaPersonalRating()
void ScriptMgr::OnGetArenaPersonalRating (Player * player, uint8 slot, uint32 & result)
Definition at line 2590 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetArenaPersonalRating(player, slot, result);
 }
References FOREACH_SCRIPT.
OnGetArenaPoints()
void ScriptMgr::OnGetArenaPoints (ArenaTeam * at, float & points)
Definition at line 2198 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaTeamScript)->OnGetArenaPoints(at, points);
 }
References FOREACH_SCRIPT.
OnGetArenaTeamId()
void ScriptMgr::OnGetArenaTeamId (Player * player, uint8 slot, uint32 & result)
Definition at line 2595 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetArenaTeamId(player, slot, result);
 }
References FOREACH_SCRIPT.
OnGetFeralApBonus()
void ScriptMgr::OnGetFeralApBonus (Player * player, int32 & feral_bonus, int32 dpsMod, ItemTemplate const * proto, ScalingStatValuesEntry const * ssv)
Definition at line 2421 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetFeralApBonus(player, feral_bonus, dpsMod, proto, ssv);
 }
References FOREACH_SCRIPT.
OnGetMaxPersonalArenaRatingRequirement()
void ScriptMgr::OnGetMaxPersonalArenaRatingRequirement (const Player * player, uint32 minSlot, uint32 & maxArenaRating) const
Definition at line 1726 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetMaxPersonalArenaRatingRequirement(player, minSlot, maxArenaRating);
 }
References FOREACH_SCRIPT.
OnGetMaxSkillValue()
void ScriptMgr::OnGetMaxSkillValue (Player * player, uint32 skill, int32 & result, bool IsPure)
Definition at line 2374 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetMaxSkillValue(player, skill, result, IsPure);
 }
References FOREACH_SCRIPT.
OnGetMaxSkillValueForLevel()
void ScriptMgr::OnGetMaxSkillValueForLevel (Player * player, uint16 & result)
Definition at line 2610 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetMaxSkillValueForLevel(player, result);
 }
References FOREACH_SCRIPT.
OnGetPoints()
void ScriptMgr::OnGetPoints (ArenaTeam * team, uint32 memberRating, float & points)
Definition at line 3029 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaScript)->OnGetPoints(team, memberRating, points);
 }
References FOREACH_SCRIPT.
OnGetQuestRate()
void ScriptMgr::OnGetQuestRate (Player * player, float & result)
Definition at line 2541 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnGetQuestRate(player, result);
 }
References FOREACH_SCRIPT.
OnGetSlotByType()
void ScriptMgr::OnGetSlotByType (const uint32 type, uint8 & slot)
Definition at line 2193 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaTeamScript)->OnGetSlotByType(type, slot);
 }
References FOREACH_SCRIPT.
OnGivePlayerXP()
void ScriptMgr::OnGivePlayerXP (Player * player, uint32 & amount, Unit * victim)
Definition at line 1424 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnGiveXP(player, amount, victim);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnGiveXP(player, amount, victim);
 }
References FOREACH_SCRIPT.
OnGlobalItemDelFromDB()
void ScriptMgr::OnGlobalItemDelFromDB (CharacterDatabaseTransaction trans, ObjectGuid::LowType itemGuid)
Definition at line 1969 of file ScriptMgr.cpp.
 {
     ASSERT(trans);
     ASSERT(itemGuid);
     FOREACH_SCRIPT(GlobalScript)->OnItemDelFromDB(trans, itemGuid);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGlobalMirrorImageDisplayItem()
void ScriptMgr::OnGlobalMirrorImageDisplayItem (const Item * item, uint32 & display)
Definition at line 1977 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnMirrorImageDisplayItem(item, display);
 }
References FOREACH_SCRIPT.
OnGossipHello() [1/2]
bool ScriptMgr::OnGossipHello (Player * player, Creature * creature)
Definition at line 779 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
 #ifdef ELUNA
     if (sEluna->OnGossipHello(player, creature))
         return true;
 #endif
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnGossipHello(player, creature);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Creature::GetScriptId().
OnGossipHello() [2/2]
bool ScriptMgr::OnGossipHello (Player * player, GameObject * go)
Definition at line 900 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
 #ifdef ELUNA
     if (sEluna->OnGossipHello(player, go))
         return true;
     if (sEluna->OnGameObjectUse(player, go))
         return true;
 #endif
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnGossipHello(player, go);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and GameObject::GetScriptId().
OnGossipSelect() [1/4]
bool ScriptMgr::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action)
Definition at line 792 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
 #ifdef ELUNA
     if (sEluna->OnGossipSelect(player, creature, sender, action))
         return true;
 #endif
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     return tmpscript->OnGossipSelect(player, creature, sender, action);
 }
References ASSERT, GET_SCRIPT_RET, and Creature::GetScriptId().
OnGossipSelect() [2/4]
bool ScriptMgr::OnGossipSelect (Player * player, GameObject * go, uint32 sender, uint32 action)
Definition at line 915 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
 #ifdef ELUNA
     if (sEluna->OnGossipSelect(player, go, sender, action))
         return true;
 #endif
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, false);
     return tmpscript->OnGossipSelect(player, go, sender, action);
 }
References ASSERT, GET_SCRIPT_RET, and GameObject::GetScriptId().
OnGossipSelect() [3/4]
void ScriptMgr::OnGossipSelect (Player * player, Item * item, uint32 sender, uint32 action)
Definition at line 741 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(item);
 #ifdef ELUNA
     sEluna->HandleGossipSelectOption(player, item, sender, action, "");
 #endif
     GET_SCRIPT(ItemScript, item->GetScriptId(), tmpscript);
     tmpscript->OnGossipSelect(player, item, sender, action);
 }
References ASSERT, GET_SCRIPT, and Item::GetScriptId().
OnGossipSelect() [4/4]
void ScriptMgr::OnGossipSelect (Player * player, uint32 menu_id, uint32 sender, uint32 action)
Definition at line 763 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->HandleGossipSelectOption(player, menu_id, sender, action, "");
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnGossipSelect(player, menu_id, sender, action);
 }
References FOREACH_SCRIPT.
OnGossipSelectCode() [1/4]
bool ScriptMgr::OnGossipSelectCode (Player * player, Creature * creature, uint32 sender, uint32 action, const char * code)
Definition at line 804 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     ASSERT(code);
 #ifdef ELUNA
     if (sEluna->OnGossipSelectCode(player, creature, sender, action, code))
         return true;
 #endif
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     return tmpscript->OnGossipSelectCode(player, creature, sender, action, code);
 }
References ASSERT, GET_SCRIPT_RET, and Creature::GetScriptId().
OnGossipSelectCode() [2/4]
bool ScriptMgr::OnGossipSelectCode (Player * player, GameObject * go, uint32 sender, uint32 action, const char * code)
Definition at line 927 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
     ASSERT(code);
 #ifdef ELUNA
     if (sEluna->OnGossipSelectCode(player, go, sender, action, code))
         return true;
 #endif
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, false);
     return tmpscript->OnGossipSelectCode(player, go, sender, action, code);
 }
References ASSERT, GET_SCRIPT_RET, and GameObject::GetScriptId().
OnGossipSelectCode() [3/4]
void ScriptMgr::OnGossipSelectCode (Player * player, Item * item, uint32 sender, uint32 action, const char * code)
Definition at line 752 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(item);
 #ifdef ELUNA
     sEluna->HandleGossipSelectOption(player, item, sender, action, code);
 #endif
     GET_SCRIPT(ItemScript, item->GetScriptId(), tmpscript);
     tmpscript->OnGossipSelectCode(player, item, sender, action, code);
 }
References ASSERT, GET_SCRIPT, and Item::GetScriptId().
OnGossipSelectCode() [4/4]
void ScriptMgr::OnGossipSelectCode (Player * player, uint32 menu_id, uint32 sender, uint32 action, const char * code)
Definition at line 771 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->HandleGossipSelectOption(player, menu_id, sender, action, code);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnGossipSelectCode(player, menu_id, sender, action, code);
 }
References FOREACH_SCRIPT.
OnGrayLevelCalculation()
void ScriptMgr::OnGrayLevelCalculation (uint8 & grayLevel, uint8 playerLevel)
Definition at line 464 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnGrayLevelCalculation(grayLevel, playerLevel);
 }
References FOREACH_SCRIPT.
OnGroupAddMember()
void ScriptMgr::OnGroupAddMember (Group * group, ObjectGuid guid)
Definition at line 1923 of file ScriptMgr.cpp.
 {
     ASSERT(group);
 #ifdef ELUNA
     sEluna->OnAddMember(group, guid);
 #endif
     FOREACH_SCRIPT(GroupScript)->OnAddMember(group, guid);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGroupChangeLeader()
void ScriptMgr::OnGroupChangeLeader (Group * group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
Definition at line 1950 of file ScriptMgr.cpp.
 {
     ASSERT(group);
 #ifdef ELUNA
     sEluna->OnChangeLeader(group, newLeaderGuid, oldLeaderGuid);
 #endif
     FOREACH_SCRIPT(GroupScript)->OnChangeLeader(group, newLeaderGuid, oldLeaderGuid);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGroupDisband()
void ScriptMgr::OnGroupDisband (Group * group)
Definition at line 1959 of file ScriptMgr.cpp.
 {
     ASSERT(group);
 #ifdef ELUNA
     sEluna->OnDisband(group);
 #endif
     FOREACH_SCRIPT(GroupScript)->OnDisband(group);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGroupInviteMember()
void ScriptMgr::OnGroupInviteMember (Group * group, ObjectGuid guid)
Definition at line 1932 of file ScriptMgr.cpp.
 {
     ASSERT(group);
 #ifdef ELUNA
     sEluna->OnInviteMember(group, guid);
 #endif
     FOREACH_SCRIPT(GroupScript)->OnInviteMember(group, guid);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGroupRateCalculation()
void ScriptMgr::OnGroupRateCalculation (float & rate, uint32 count, bool isRaid)
Definition at line 492 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnGroupRateCalculation(rate, count, isRaid);
 }
References count(), and FOREACH_SCRIPT.
OnGroupRemoveMember()
void ScriptMgr::OnGroupRemoveMember (Group * group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, const char * reason)
Definition at line 1941 of file ScriptMgr.cpp.
 {
     ASSERT(group);
 #ifdef ELUNA
     sEluna->OnRemoveMember(group, guid, method);
 #endif
     FOREACH_SCRIPT(GroupScript)->OnRemoveMember(group, guid, method, kicker, reason);
 }
References ASSERT, and FOREACH_SCRIPT.
OnGuildAddMember()
void ScriptMgr::OnGuildAddMember (Guild * guild, Player * player, uint8 & plRank)
Definition at line 1833 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnAddMember(guild, player, plRank);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnAddMember(guild, player, plRank);
 }
References FOREACH_SCRIPT.
OnGuildBankEvent()
void ScriptMgr::OnGuildBankEvent (Guild * guild, uint8 eventType, uint8 tabId, ObjectGuid::LowType playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
Definition at line 1914 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnBankEvent(guild, eventType, tabId, playerGuid, itemOrMoney, itemStackCount, destTabId);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnBankEvent(guild, eventType, tabId, playerGuid, itemOrMoney, itemStackCount, destTabId);
 }
References FOREACH_SCRIPT.
OnGuildCreate()
void ScriptMgr::OnGuildCreate (Guild * guild, Player * leader, const std::string & name)
Definition at line 1865 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnCreate(guild, leader, name);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnCreate(guild, leader, name);
 }
References FOREACH_SCRIPT, and name.
OnGuildDisband()
void ScriptMgr::OnGuildDisband (Guild * guild)
Definition at line 1873 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnDisband(guild);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnDisband(guild);
 }
References FOREACH_SCRIPT.
OnGuildEvent()
void ScriptMgr::OnGuildEvent (Guild * guild, uint8 eventType, ObjectGuid::LowType playerGuid1, ObjectGuid::LowType playerGuid2, uint8 newRank)
Definition at line 1906 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnEvent(guild, eventType, playerGuid1, playerGuid2, newRank);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnEvent(guild, eventType, playerGuid1, playerGuid2, newRank);
 }
References FOREACH_SCRIPT.
OnGuildInfoChanged()
void ScriptMgr::OnGuildInfoChanged (Guild * guild, const std::string & newInfo)
Definition at line 1857 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnInfoChanged(guild, newInfo);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnInfoChanged(guild, newInfo);
 }
References FOREACH_SCRIPT.
OnGuildItemMove()
void ScriptMgr::OnGuildItemMove (Guild * guild, Player * player, Item * pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
Definition at line 1897 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnItemMove(guild, player, pItem, isSrcBank, srcContainer, srcSlotId, isDestBank, destContainer, destSlotId);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnItemMove(guild, player, pItem, isSrcBank, srcContainer, srcSlotId, isDestBank, destContainer, destSlotId);
 }
References FOREACH_SCRIPT.
OnGuildMemberDepositMoney()
void ScriptMgr::OnGuildMemberDepositMoney (Guild * guild, Player * player, uint32 & amount)
Definition at line 1889 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnMemberDepositMoney(guild, player, amount);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnMemberDepositMoney(guild, player, amount);
 }
References FOREACH_SCRIPT.
OnGuildMemberWitdrawMoney()
void ScriptMgr::OnGuildMemberWitdrawMoney (Guild * guild, Player * player, uint32 & amount, bool isRepair)
Definition at line 1881 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnMemberWitdrawMoney(guild, player, amount, isRepair);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnMemberWitdrawMoney(guild, player, amount, isRepair);
 }
References FOREACH_SCRIPT.
OnGuildMOTDChanged()
void ScriptMgr::OnGuildMOTDChanged (Guild * guild, const std::string & newMotd)
Definition at line 1849 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnMOTDChanged(guild, newMotd);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnMOTDChanged(guild, newMotd);
 }
References FOREACH_SCRIPT.
OnGuildRemoveMember()
void ScriptMgr::OnGuildRemoveMember (Guild * guild, Player * player, bool isDisbanding, bool isKicked)
Definition at line 1841 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnRemoveMember(guild, player, isDisbanding);
 #endif
     FOREACH_SCRIPT(GuildScript)->OnRemoveMember(guild, player, isDisbanding, isKicked);
 }
References FOREACH_SCRIPT.
OnHandleDevCommand()
void ScriptMgr::OnHandleDevCommand (Player * player, std::string & argstr)
Definition at line 3148 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(CommandSC)->OnHandleDevCommand(player, argstr);
 }
References FOREACH_SCRIPT.
OnHeal()
void ScriptMgr::OnHeal (Unit * healer, Unit * reciever, uint32 & gain)
Definition at line 2049 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(UnitScript)->OnHeal(healer, reciever, gain);
 }
References FOREACH_SCRIPT.
OnHonorCalculation()
void ScriptMgr::OnHonorCalculation (float & honor, uint8 level, float multiplier)
Definition at line 459 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnHonorCalculation(honor, level, multiplier);
 }
References FOREACH_SCRIPT.
OnInitializeLockedDungeons()
void ScriptMgr::OnInitializeLockedDungeons (Player * player, uint8 & level, uint32 & lockData, lfg::LFGDungeonData const * dungeon)
Definition at line 2018 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(GlobalScript)->OnInitializeLockedDungeons(player, level, lockData, dungeon);
 }
References FOREACH_SCRIPT.
OnInitStatsForLevel()
void ScriptMgr::OnInitStatsForLevel (Guardian * guardian, uint8 petlevel)
Definition at line 2975 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PetScript)->OnInitStatsForLevel(guardian, petlevel);
 }
References FOREACH_SCRIPT.
OnInstall()
void ScriptMgr::OnInstall (Vehicle * veh)
Definition at line 1186 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
 #ifdef ELUNA
     sEluna->OnInstall(veh);
 #endif
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnInstall(veh);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnInstallAccessory()
void ScriptMgr::OnInstallAccessory (Vehicle * veh, Creature * accessory)
Definition at line 1221 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
     ASSERT(accessory);
 #ifdef ELUNA
     sEluna->OnInstallAccessory(veh, accessory);
 #endif
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnInstallAccessory(veh, accessory);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnInstanceSave()
void ScriptMgr::OnInstanceSave (InstanceSave * instanceSave)
Definition at line 3138 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnInstanceSave(instanceSave);
 }
References FOREACH_SCRIPT.
OnIsFFAPvP()
void ScriptMgr::OnIsFFAPvP (Player * player, bool & result)
Definition at line 2600 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnIsFFAPvP(player, result);
 }
References FOREACH_SCRIPT.
OnIsPvP()
void ScriptMgr::OnIsPvP (Player * player, bool & result)
Definition at line 2605 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnIsPvP(player, result);
 }
References FOREACH_SCRIPT.
OnItemCreate()
void ScriptMgr::OnItemCreate (Item * item, ItemTemplate const * itemProto, Player const * owner)
Definition at line 3045 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnItemCreate(item, itemProto, owner);
 }
References FOREACH_SCRIPT.
OnItemExpire()
bool ScriptMgr::OnItemExpire (Player * player, ItemTemplate const * proto)
Definition at line 704 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(proto);
 #ifdef ELUNA
     if (sEluna->OnExpire(player, proto))
         return false;
 #endif
     GET_SCRIPT_RET(ItemScript, proto->ScriptId, tmpscript, false);
     return tmpscript->OnExpire(player, proto);
 }
References ASSERT, GET_SCRIPT_RET, and ItemTemplate::ScriptId.
OnItemRemove()
bool ScriptMgr::OnItemRemove (Player * player, Item * item)
Definition at line 718 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(item);
 #ifdef ELUNA
     if (sEluna->OnRemove(player, item))
         return false;
 #endif
     GET_SCRIPT_RET(ItemScript, item->GetScriptId(), tmpscript, false);
     return tmpscript->OnRemove(player, item);
 }
References ASSERT, GET_SCRIPT_RET, and Item::GetScriptId().
OnItemRoll()
bool ScriptMgr::OnItemRoll (Player const * player, LootStoreItem const * LootStoreItem, float & chance, Loot & loot, LootStore const & store)
Definition at line 1997 of file ScriptMgr.cpp.
 {
     bool ret = true; // return true by default
     FOR_SCRIPTS_RET(GlobalScript, itr, end, ret)
         if (!itr->second->OnItemRoll(player, LootStoreItem, chance, loot, store))
             ret = false; // we change ret value only when a script returns false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
OnItemUse()
bool ScriptMgr::OnItemUse (Player * player, Item * item, SpellCastTargets const & targets)
Definition at line 690 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(item);
 #ifdef ELUNA
     if (!sEluna->OnUse(player, item, targets))
         return true;
 #endif
     GET_SCRIPT_RET(ItemScript, item->GetScriptId(), tmpscript, false);
     return tmpscript->OnUse(player, item, targets);
 }
References ASSERT, GET_SCRIPT_RET, and Item::GetScriptId().
OnLastIpUpdate()
void ScriptMgr::OnLastIpUpdate (uint32 accountId, std::string ip)
Definition at line 1802 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnLastIpUpdate(accountId, ip);
 }
References FOREACH_SCRIPT.
OnLoadCustomDatabaseTable()
void ScriptMgr::OnLoadCustomDatabaseTable ()
Definition at line 404 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(WorldScript)->OnLoadCustomDatabaseTable();
 }
References FOREACH_SCRIPT.
OnLoadGridMap()
void ScriptMgr::OnLoadGridMap (Map * map, GridMap * gmap, uint32 gx, uint32 gy)
Definition at line 555 of file ScriptMgr.cpp.
 {
     ASSERT(map);
     ASSERT(gmap);
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnLoadGridMap(map, gmap, gx, gy);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnLoadGridMap((InstanceMap*)map, gmap, gx, gy);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnLoadGridMap((BattlegroundMap*)map, gmap, gx, gy);
     SCR_MAP_END;
 }
References ASSERT, SCR_MAP_BGN, and SCR_MAP_END.
OnLootItem()
void ScriptMgr::OnLootItem (Player * player, Item * item, uint32 count, ObjectGuid lootguid)
Definition at line 1731 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnLootItem(player, item, count, lootguid);
 }
References count(), and FOREACH_SCRIPT.
OnMapUpdate()
void ScriptMgr::OnMapUpdate (Map * map, uint32 diff)
Definition at line 642 of file ScriptMgr.cpp.
 {
     ASSERT(map);
 #ifdef ELUNA
     sEluna->OnUpdate(map, diff);
 #endif
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnUpdate(map, diff);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnUpdate((InstanceMap*)map, diff);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnUpdate((BattlegroundMap*)map, diff);
     SCR_MAP_END;
 }
References ASSERT, diff(), SCR_MAP_BGN, and SCR_MAP_END.
OnMotdChange()
void ScriptMgr::OnMotdChange (std::string & newMotd)
Definition at line 430 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(WorldScript)->OnMotdChange(newMotd);
 }
References FOREACH_SCRIPT.
OnNetworkStart()
void ScriptMgr::OnNetworkStart ()
Definition at line 352 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ServerScript)->OnNetworkStart();
 }
References FOREACH_SCRIPT.
OnNetworkStop()
void ScriptMgr::OnNetworkStop ()
Definition at line 357 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ServerScript)->OnNetworkStop();
 }
References FOREACH_SCRIPT.
OnOpenStateChange()
void ScriptMgr::OnOpenStateChange (bool open)
Definition at line 396 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnOpenStateChange(open);
 #endif
     FOREACH_SCRIPT(WorldScript)->OnOpenStateChange(open);
 }
References FOREACH_SCRIPT, and open.
OnPacketReceive()
void ScriptMgr::OnPacketReceive (WorldSession * session, WorldPacket const & packet)
Definition at line 376 of file ScriptMgr.cpp.
 {
     if (SCR_REG_LST(ServerScript).empty())
         return;
     WorldPacket copy(packet);
     FOREACH_SCRIPT(ServerScript)->OnPacketReceive(session, copy);
 }
References detail::copy(), FOREACH_SCRIPT, and SCR_REG_LST.
OnPacketSend()
void ScriptMgr::OnPacketSend (WorldSession * session, WorldPacket const & packet)
Definition at line 385 of file ScriptMgr.cpp.
 {
     ASSERT(session);
     if (SCR_REG_LST(ServerScript).empty())
         return;
     WorldPacket copy(packet);
     FOREACH_SCRIPT(ServerScript)->OnPacketSend(session, copy);
 }
References ASSERT, detail::copy(), FOREACH_SCRIPT, and SCR_REG_LST.
OnPasswordChange()
void ScriptMgr::OnPasswordChange (uint32 accountId)
Definition at line 1822 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AccountScript)->OnPasswordChange(accountId);
 }
References FOREACH_SCRIPT.
OnPlayerAddToBattleground()
void ScriptMgr::OnPlayerAddToBattleground (Player * player, Battleground * bg)
Definition at line 1629 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnAddToBattleground(player, bg);
 }
References bg(), and FOREACH_SCRIPT.
OnPlayerBeingCharmed()
void ScriptMgr::OnPlayerBeingCharmed (Player * player, Unit * charmer, uint32 oldFactionId, uint32 newFactionId)
Definition at line 1686 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnBeingCharmed(player, charmer, oldFactionId, newFactionId);
 }
References FOREACH_SCRIPT.
OnPlayerBindToInstance()
void ScriptMgr::OnPlayerBindToInstance (Player * player, Difficulty difficulty, uint32 mapid, bool permanent)
Definition at line 1593 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnBindToInstance(player, difficulty, mapid, permanent);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnBindToInstance(player, difficulty, mapid, permanent);
 }
References FOREACH_SCRIPT.
OnPlayerChat() [1/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg)
Definition at line 1479 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnChat(player, type, lang, msg);
 }
References FOREACH_SCRIPT.
OnPlayerChat() [2/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Channel * channel)
Definition at line 1504 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnChat(player, type, lang, msg, channel);
 }
References FOREACH_SCRIPT.
OnPlayerChat() [3/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Group * group)
Definition at line 1494 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnChat(player, type, lang, msg, group);
 }
References FOREACH_SCRIPT.
OnPlayerChat() [4/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Guild * guild)
Definition at line 1499 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnChat(player, type, lang, msg, guild);
 }
References FOREACH_SCRIPT.
OnPlayerChat() [5/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Player * receiver)
Definition at line 1489 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnChat(player, type, lang, msg, receiver);
 }
References FOREACH_SCRIPT.
OnPlayerCompleteQuest()
void ScriptMgr::OnPlayerCompleteQuest (Player * player, Quest const * quest)
Definition at line 1338 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnPlayerCompleteQuest(player, quest);
 }
References FOREACH_SCRIPT.
OnPlayerCreate()
void ScriptMgr::OnPlayerCreate (Player * player)
Definition at line 1564 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnCreate(player);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnCreate(player);
 }
References FOREACH_SCRIPT.
OnPlayerDelete()
void ScriptMgr::OnPlayerDelete (ObjectGuid guid, uint32 accountId)
Definition at line 1580 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnDelete(guid.GetCounter());
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnDelete(guid, accountId);
 }
References FOREACH_SCRIPT, and ObjectGuid::GetCounter().
OnPlayerDuelEnd()
void ScriptMgr::OnPlayerDuelEnd (Player * winner, Player * loser, DuelCompleteType type)
Definition at line 1471 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnDuelEnd(winner, loser, type);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnDuelEnd(winner, loser, type);
 }
References FOREACH_SCRIPT.
OnPlayerDuelRequest()
void ScriptMgr::OnPlayerDuelRequest (Player * target, Player * challenger)
Definition at line 1455 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnDuelRequest(target, challenger);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnDuelRequest(target, challenger);
 }
References FOREACH_SCRIPT.
OnPlayerDuelStart()
void ScriptMgr::OnPlayerDuelStart (Player * player1, Player * player2)
Definition at line 1463 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnDuelStart(player1, player2);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnDuelStart(player1, player2);
 }
References FOREACH_SCRIPT.
OnPlayerEmote()
void ScriptMgr::OnPlayerEmote (Player * player, uint32 emote)
Definition at line 1509 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnEmote(player, emote);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnEmote(player, emote);
 }
References FOREACH_SCRIPT.
OnPlayerEnterMap()
void ScriptMgr::OnPlayerEnterMap (Map * map, Player * player)
Definition at line 591 of file ScriptMgr.cpp.
 {
     ASSERT(map);
     ASSERT(player);
 #ifdef ELUNA
     sEluna->OnMapChanged(player);
     sEluna->OnPlayerEnter(map, player);
 #endif
     FOREACH_SCRIPT(AllMapScript)->OnPlayerEnterAll(map, player);
     FOREACH_SCRIPT(PlayerScript)->OnMapChanged(player);
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnPlayerEnter(map, player);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnPlayerEnter((InstanceMap*)map, player);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnPlayerEnter((BattlegroundMap*)map, player);
     SCR_MAP_END;
 }
References ASSERT, FOREACH_SCRIPT, SCR_MAP_BGN, and SCR_MAP_END.
OnPlayerFailedDelete()
void ScriptMgr::OnPlayerFailedDelete (ObjectGuid guid, uint32 accountId)
Definition at line 1588 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnFailedDelete(guid, accountId);
 }
References FOREACH_SCRIPT.
OnPlayerForgotSpell()
void ScriptMgr::OnPlayerForgotSpell (Player * player, uint32 spellID)
Definition at line 1450 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnForgotSpell(player, spellID);
 }
References FOREACH_SCRIPT.
OnPlayerFreeTalentPointsChanged()
void ScriptMgr::OnPlayerFreeTalentPointsChanged (Player * player, uint32 newPoints)
Definition at line 1400 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnFreeTalentPointsChanged(player, points);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnFreeTalentPointsChanged(player, points);
 }
References FOREACH_SCRIPT.
OnPlayerJoinArena()
void ScriptMgr::OnPlayerJoinArena (Player * player)
Definition at line 1711 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnPlayerJoinArena(player);
 }
References FOREACH_SCRIPT.
OnPlayerJoinBG()
void ScriptMgr::OnPlayerJoinBG (Player * player)
Definition at line 1706 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnPlayerJoinBG(player);
 }
References FOREACH_SCRIPT.
OnPlayerKilledByCreature()
void ScriptMgr::OnPlayerKilledByCreature (Creature * killer, Player * killed)
Definition at line 1384 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnPlayerKilledByCreature(killer, killed);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnPlayerKilledByCreature(killer, killed);
 }
References FOREACH_SCRIPT.
OnPlayerLearnSpell()
void ScriptMgr::OnPlayerLearnSpell (Player * player, uint32 spellID)
Definition at line 1445 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnLearnSpell(player, spellID);
 }
References FOREACH_SCRIPT.
OnPlayerLeaveMap()
void ScriptMgr::OnPlayerLeaveMap (Map * map, Player * player)
Definition at line 618 of file ScriptMgr.cpp.
 {
     ASSERT(map);
     ASSERT(player);
 #ifdef ELUNA
     sEluna->OnPlayerLeave(map, player);
 #endif
     FOREACH_SCRIPT(AllMapScript)->OnPlayerLeaveAll(map, player);
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnPlayerLeave(map, player);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnPlayerLeave((InstanceMap*)map, player);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnPlayerLeave((BattlegroundMap*)map, player);
     SCR_MAP_END;
 }
References ASSERT, FOREACH_SCRIPT, SCR_MAP_BGN, and SCR_MAP_END.
OnPlayerLevelChanged()
void ScriptMgr::OnPlayerLevelChanged (Player * player, uint8 oldLevel)
Definition at line 1392 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnLevelChanged(player, oldLevel);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnLevelChanged(player, oldLevel);
 }
References FOREACH_SCRIPT.
OnPlayerLoadFromDB()
void ScriptMgr::OnPlayerLoadFromDB (Player * player)
Definition at line 1551 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnLoadFromDB(player);
 }
References FOREACH_SCRIPT.
OnPlayerLogin()
void ScriptMgr::OnPlayerLogin (Player * player)
Definition at line 1543 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnLogin(player);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnLogin(player);
 }
References FOREACH_SCRIPT.
OnPlayerLogout()
void ScriptMgr::OnPlayerLogout (Player * player)
Definition at line 1556 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnLogout(player);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnLogout(player);
 }
References FOREACH_SCRIPT.
OnPlayerMoneyChanged()
void ScriptMgr::OnPlayerMoneyChanged (Player * player, int32 & amount)
Definition at line 1416 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnMoneyChanged(player, amount);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnMoneyChanged(player, amount);
 }
References FOREACH_SCRIPT.
OnPlayerMove()
void ScriptMgr::OnPlayerMove (Player * player, MovementInfo movementInfo, uint32 opcode)
Definition at line 2084 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MovementHandlerScript)->OnPlayerMove(player, movementInfo, opcode);
 }
References FOREACH_SCRIPT.
OnPlayerPVPFlagChange()
void ScriptMgr::OnPlayerPVPFlagChange (Player * player, bool state)
Definition at line 1366 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnPlayerPVPFlagChange(player, state);
 }
References FOREACH_SCRIPT.
OnPlayerQueueRandomDungeon()
void ScriptMgr::OnPlayerQueueRandomDungeon (Player * player, uint32 & rDungeonId)
Definition at line 1634 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnQueueRandomDungeon(player, rDungeonId);
 }
References FOREACH_SCRIPT.
OnPlayerReleasedGhost()
void ScriptMgr::OnPlayerReleasedGhost (Player * player)
Definition at line 1353 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnPlayerReleasedGhost(player);
 }
References FOREACH_SCRIPT.
OnPlayerRemoveFromBattleground()
void ScriptMgr::OnPlayerRemoveFromBattleground (Player * player, Battleground * bg)
Definition at line 1639 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnRemoveFromBattleground(player, bg);
 }
References bg(), and FOREACH_SCRIPT.
OnPlayerReputationChange()
void ScriptMgr::OnPlayerReputationChange (Player * player, uint32 factionID, int32 & standing, bool incremental)
Definition at line 1432 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnReputationChange(player, factionID, standing, incremental);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnReputationChange(player, factionID, standing, incremental);
 }
References FOREACH_SCRIPT.
OnPlayerReputationRankChange()
void ScriptMgr::OnPlayerReputationRankChange (Player * player, uint32 factionID, ReputationRank newRank, ReputationRank oldRank, bool increased)
Definition at line 1440 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnReputationRankChange(player, factionID, newRank, oldRank, increased);
 }
References FOREACH_SCRIPT.
OnPlayerSave()
void ScriptMgr::OnPlayerSave (Player * player)
Definition at line 1572 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnSave(player);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnSave(player);
 }
References FOREACH_SCRIPT.
OnPlayerSetPhase()
void ScriptMgr::OnPlayerSetPhase (const AuraEffect * auraEff, AuraApplication const * aurApp, uint8 mode, bool apply, uint32 & newPhase)
Definition at line 3143 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->OnPlayerSetPhase(auraEff, aurApp, mode, apply, newPhase);
 }
References ByteConverter::apply(), and FOREACH_SCRIPT.
OnPlayerSpellCast()
void ScriptMgr::OnPlayerSpellCast (Player * player, Spell * spell, bool skipCheck)
Definition at line 1525 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnSpellCast(player, spell, skipCheck);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnSpellCast(player, spell, skipCheck);
 }
References FOREACH_SCRIPT.
OnPlayerTalentsReset()
void ScriptMgr::OnPlayerTalentsReset (Player * player, bool noCost)
Definition at line 1408 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnTalentsReset(player, noCost);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnTalentsReset(player, noCost);
 }
References FOREACH_SCRIPT.
OnPlayerTextEmote()
void ScriptMgr::OnPlayerTextEmote (Player * player, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
Definition at line 1517 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnTextEmote(player, textEmote, emoteNum, guid);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnTextEmote(player, textEmote, emoteNum, guid);
 }
References FOREACH_SCRIPT.
OnPlayerUpdate()
void ScriptMgr::OnPlayerUpdate (Player * player, uint32 p_time)
Definition at line 1538 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnUpdate(player, p_time);
 }
References FOREACH_SCRIPT.
OnPlayerUpdateArea()
void ScriptMgr::OnPlayerUpdateArea (Player * player, uint32 oldArea, uint32 newArea)
Definition at line 1609 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnUpdateArea(player, oldArea, newArea);
 }
References FOREACH_SCRIPT.
OnPlayerUpdateFaction()
void ScriptMgr::OnPlayerUpdateFaction (Player * player)
Definition at line 1624 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnUpdateFaction(player);
 }
References FOREACH_SCRIPT.
OnPlayerUpdateZone()
void ScriptMgr::OnPlayerUpdateZone (Player * player, uint32 newZone, uint32 newArea)
Definition at line 1601 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnUpdateZone(player, newZone, newArea);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnUpdateZone(player, newZone, newArea);
 }
References FOREACH_SCRIPT.
OnPVPKill()
void ScriptMgr::OnPVPKill (Player * killer, Player * killed)
Definition at line 1358 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnPVPKill(killer, killed);
 #endif
     FOREACH_SCRIPT(PlayerScript)->OnPVPKill(killer, killed);
 }
References FOREACH_SCRIPT.
OnQuestAccept() [1/3]
bool ScriptMgr::OnQuestAccept (Player * player, Creature * creature, Quest const * quest)
Definition at line 817 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     ASSERT(quest);
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestAccept(player, creature, quest);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Creature::GetScriptId().
OnQuestAccept() [2/3]
bool ScriptMgr::OnQuestAccept (Player * player, GameObject * go, Quest const * quest)
Definition at line 940 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
     ASSERT(quest);
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestAccept(player, go, quest);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and GameObject::GetScriptId().
OnQuestAccept() [3/3]
bool ScriptMgr::OnQuestAccept (Player * player, Item * item, Quest const * quest)
Definition at line 674 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(item);
     ASSERT(quest);
 #ifdef ELUNA
     if (sEluna->OnQuestAccept(player, item, quest))
         return false;
 #endif
     GET_SCRIPT_RET(ItemScript, item->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestAccept(player, item, quest);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Item::GetScriptId().
OnQuestComplete()
bool ScriptMgr::OnQuestComplete (Player * player, Creature * creature, Quest const * quest)
Definition at line 839 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     ASSERT(quest);
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestComplete(player, creature, quest);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Creature::GetScriptId().
OnQuestReward() [1/2]
bool ScriptMgr::OnQuestReward (Player * player, Creature * creature, Quest const * quest, uint32 opt)
Definition at line 850 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     ASSERT(quest);
 #ifdef ELUNA
     if (sEluna->OnQuestReward(player, creature, quest, opt))
     {
         ClearGossipMenuFor(player);
         return false;
     }
 #endif
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestReward(player, creature, quest, opt);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Creature::GetScriptId().
OnQuestReward() [2/2]
bool ScriptMgr::OnQuestReward (Player * player, GameObject * go, Quest const * quest, uint32 opt)
Definition at line 951 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(go);
     ASSERT(quest);
 #ifdef ELUNA
     if (sEluna->OnQuestAccept(player, go, quest))
         return false;
 #endif
 #ifdef ELUNA
     if (sEluna->OnQuestReward(player, go, quest, opt))
         return false;
 #endif
     GET_SCRIPT_RET(GameObjectScript, go->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestReward(player, go, quest, opt);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and GameObject::GetScriptId().
OnQuestRewardItem()
void ScriptMgr::OnQuestRewardItem (Player * player, Item * item, uint32 count)
Definition at line 1741 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnQuestRewardItem(player, item, count);
 }
References count(), and FOREACH_SCRIPT.
OnQuestSelect()
bool ScriptMgr::OnQuestSelect (Player * player, Creature * creature, Quest const * quest)
Definition at line 828 of file ScriptMgr.cpp.
 {
     ASSERT(player);
     ASSERT(creature);
     ASSERT(quest);
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, false);
     ClearGossipMenuFor(player);
     return tmpscript->OnQuestSelect(player, creature, quest);
 }
References ASSERT, ClearGossipMenuFor(), GET_SCRIPT_RET, and Creature::GetScriptId().
OnQueueUpdate()
void ScriptMgr::OnQueueUpdate (BattlegroundQueue * queue, BattlegroundBracketId bracket_id, bool isRated, uint32 arenaRatedTeamId)
Definition at line 2819 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(BGScript)->OnQueueUpdate(queue, bracket_id, isRated, arenaRatedTeamId);
 }
References FOREACH_SCRIPT.
OnRelocate()
void ScriptMgr::OnRelocate (Transport * transport, uint32 waypointId, uint32 mapId, float x, float y, float z)
Definition at line 1306 of file ScriptMgr.cpp.
 {
     GET_SCRIPT(TransportScript, transport->GetScriptId(), tmpscript);
     tmpscript->OnRelocate(transport, waypointId, mapId, x, y, z);
 }
References GET_SCRIPT, GameObject::GetScriptId(), G3D::x, G3D::y, and G3D::z.
OnRemoveAuraScaleTargets()
void ScriptMgr::OnRemoveAuraScaleTargets (Spell * spell, TargetInfo & targetInfo, uint8 auraScaleMask, bool & needErase)
Definition at line 2922 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(SpellSC)->OnRemoveAuraScaleTargets(spell, targetInfo, auraScaleMask, needErase);
 }
References FOREACH_SCRIPT.
OnRemovePassenger() [1/2]
void ScriptMgr::OnRemovePassenger (Transport * transport, Player * player)
Definition at line 1289 of file ScriptMgr.cpp.
 {
     ASSERT(transport);
     ASSERT(player);
     GET_SCRIPT(TransportScript, transport->GetScriptId(), tmpscript);
     tmpscript->OnRemovePassenger(transport, player);
 }
References ASSERT, GET_SCRIPT, and GameObject::GetScriptId().
OnRemovePassenger() [2/2]
void ScriptMgr::OnRemovePassenger (Vehicle * veh, Unit * passenger)
Definition at line 1249 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
     ASSERT(passenger);
 #ifdef ELUNA
     sEluna->OnRemovePassenger(veh, passenger);
 #endif
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnRemovePassenger(veh, passenger);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnReset()
void ScriptMgr::OnReset (Vehicle * veh)
Definition at line 1212 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnReset(veh);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnRewardKillRewarder()
void ScriptMgr::OnRewardKillRewarder (Player * player, bool isDungeon, float & rate)
Definition at line 2342 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnRewardKillRewarder(player, isDungeon, rate);
 }
References FOREACH_SCRIPT.
OnScaleAuraUnitAdd()
void ScriptMgr::OnScaleAuraUnitAdd (Spell * spell, Unit * target, uint32 effectMask, bool checkIfValid, bool implicit, uint8 auraScaleMask, TargetInfo & targetInfo)
Definition at line 2917 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(SpellSC)->OnScaleAuraUnitAdd(spell, target, effectMask, checkIfValid, implicit, auraScaleMask, targetInfo);
 }
References FOREACH_SCRIPT.
OnSendInitialPacketsBeforeAddToMap()
void ScriptMgr::OnSendInitialPacketsBeforeAddToMap (Player * player, WorldPacket & data)
Definition at line 1343 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnSendInitialPacketsBeforeAddToMap(player, data);
 }
References FOREACH_SCRIPT.
OnSetArenaMaxPlayersPerTeam()
void ScriptMgr::OnSetArenaMaxPlayersPerTeam (const uint8 arenaType, uint32 & maxPlayerPerTeam)
Definition at line 2213 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(ArenaTeamScript)->OnSetArenaMaxPlayersPerTeam(arenaType, maxPlayerPerTeam);
 }
References FOREACH_SCRIPT.
OnSetServerSideVisibility()
void ScriptMgr::OnSetServerSideVisibility (Player * player, ServerSideVisibilityType & type, AccountTypes & sec)
Definition at line 2659 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnSetServerSideVisibility(player, type, sec);
 }
References FOREACH_SCRIPT, and sec.
OnSetServerSideVisibilityDetect()
void ScriptMgr::OnSetServerSideVisibilityDetect (Player * player, ServerSideVisibilityType & type, AccountTypes & sec)
Definition at line 2664 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnSetServerSideVisibilityDetect(player, type, sec);
 }
References FOREACH_SCRIPT, and sec.
OnShutdown()
void ScriptMgr::OnShutdown ()
Definition at line 1320 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnShutdown();
 #endif
     FOREACH_SCRIPT(WorldScript)->OnShutdown();
 }
References FOREACH_SCRIPT.
OnShutdownCancel()
void ScriptMgr::OnShutdownCancel ()
Definition at line 443 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnShutdownCancel();
 #endif
     FOREACH_SCRIPT(WorldScript)->OnShutdownCancel();
 }
References FOREACH_SCRIPT.
OnShutdownInitiate()
void ScriptMgr::OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
Definition at line 435 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnShutdownInitiate(code, mask);
 #endif
     FOREACH_SCRIPT(WorldScript)->OnShutdownInitiate(code, mask);
 }
References FOREACH_SCRIPT.
OnSocketClose()
void ScriptMgr::OnSocketClose (std::shared_ptr< WorldSocket > socket)
Definition at line 369 of file ScriptMgr.cpp.
 {
     ASSERT(socket);
     FOREACH_SCRIPT(ServerScript)->OnSocketClose(socket);
 }
References ASSERT, and FOREACH_SCRIPT.
OnSocketOpen()
void ScriptMgr::OnSocketOpen (std::shared_ptr< WorldSocket > socket)
Definition at line 362 of file ScriptMgr.cpp.
 {
     ASSERT(socket);
     FOREACH_SCRIPT(ServerScript)->OnSocketOpen(socket);
 }
References ASSERT, and FOREACH_SCRIPT.
OnSpellCheckCast()
void ScriptMgr::OnSpellCheckCast (Spell * spell, bool strict, SpellCastResult & res)
Definition at line 2879 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(SpellSC)->OnSpellCheckCast(spell, strict, res);
 }
References FOREACH_SCRIPT.
OnStartup()
void ScriptMgr::OnStartup ()
Definition at line 1312 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnStartup();
 #endif
     FOREACH_SCRIPT(WorldScript)->OnStartup();
 }
References FOREACH_SCRIPT.
OnTransportUpdate()
void ScriptMgr::OnTransportUpdate (Transport * transport, uint32 diff)
Definition at line 1298 of file ScriptMgr.cpp.
 {
     ASSERT(transport);
     GET_SCRIPT(TransportScript, transport->GetScriptId(), tmpscript);
     tmpscript->OnUpdate(transport, diff);
 }
References ASSERT, diff(), GET_SCRIPT, and GameObject::GetScriptId().
OnUninstall()
void ScriptMgr::OnUninstall (Vehicle * veh)
Definition at line 1199 of file ScriptMgr.cpp.
 {
     ASSERT(veh);
     ASSERT(veh->GetBase()->GetTypeId() == TYPEID_UNIT);
 #ifdef ELUNA
     sEluna->OnUninstall(veh);
 #endif
     GET_SCRIPT(VehicleScript, veh->GetBase()->ToCreature()->GetScriptId(), tmpscript);
     tmpscript->OnUninstall(veh);
 }
References ASSERT, GET_SCRIPT, Vehicle::GetBase(), Creature::GetScriptId(), Object::GetTypeId(), Object::ToCreature(), and TYPEID_UNIT.
OnUnloadGridMap()
void ScriptMgr::OnUnloadGridMap (Map * map, GridMap * gmap, uint32 gx, uint32 gy)
Definition at line 573 of file ScriptMgr.cpp.
 {
     ASSERT(map);
     ASSERT(gmap);
     SCR_MAP_BGN(WorldMapScript, map, itr, end, entry, IsWorldMap);
     itr->second->OnUnloadGridMap(map, gmap, gx, gy);
     SCR_MAP_END;
     SCR_MAP_BGN(InstanceMapScript, map, itr, end, entry, IsDungeon);
     itr->second->OnUnloadGridMap((InstanceMap*)map, gmap, gx, gy);
     SCR_MAP_END;
     SCR_MAP_BGN(BattlegroundMapScript, map, itr, end, entry, IsBattleground);
     itr->second->OnUnloadGridMap((BattlegroundMap*)map, gmap, gx, gy);
     SCR_MAP_END;
 }
References ASSERT, SCR_MAP_BGN, and SCR_MAP_END.
OnVictimRewardAfter()
void ScriptMgr::OnVictimRewardAfter (Player * player, Player * victim, uint32 & killer_title, uint32 & victim_rank, float & honor_f)
Definition at line 2395 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnVictimRewardAfter(player, victim, killer_title, victim_rank, honor_f);
 }
References FOREACH_SCRIPT.
OnVictimRewardBefore()
void ScriptMgr::OnVictimRewardBefore (Player * player, Player * victim, uint32 & killer_title, uint32 & victim_title)
Definition at line 2390 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->OnVictimRewardBefore(player, victim, killer_title, victim_title);
 }
References FOREACH_SCRIPT.
OnWeatherChange()
void ScriptMgr::OnWeatherChange (Weather * weather, WeatherState state, float grade)
Definition at line 1075 of file ScriptMgr.cpp.
 {
     ASSERT(weather);
 #ifdef ELUNA
     sEluna->OnChange(weather, weather->GetZone(), state, grade);
 #endif
     GET_SCRIPT(WeatherScript, weather->GetScriptId(), tmpscript);
     tmpscript->OnChange(weather, state, grade);
 }
References ASSERT, GET_SCRIPT, Weather::GetScriptId(), and Weather::GetZone().
OnWeatherUpdate()
void ScriptMgr::OnWeatherUpdate (Weather * weather, uint32 diff)
Definition at line 1087 of file ScriptMgr.cpp.
 {
     ASSERT(weather);
     GET_SCRIPT(WeatherScript, weather->GetScriptId(), tmpscript);
     tmpscript->OnUpdate(weather, diff);
 }
References ASSERT, diff(), GET_SCRIPT, and Weather::GetScriptId().
OnWorldUpdate()
void ScriptMgr::OnWorldUpdate (uint32 diff)
Definition at line 451 of file ScriptMgr.cpp.
 {
 #ifdef ELUNA
     sEluna->OnWorldUpdate(diff);
 #endif
     FOREACH_SCRIPT(WorldScript)->OnUpdate(diff);
 }
References diff(), and FOREACH_SCRIPT.
OnZeroDifferenceCalculation()
void ScriptMgr::OnZeroDifferenceCalculation (uint8 & diff, uint8 playerLevel)
Definition at line 474 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(FormulaScript)->OnZeroDifferenceCalculation(diff, playerLevel);
 }
References diff(), and FOREACH_SCRIPT.
PassedQuestKilledMonsterCredit()
bool ScriptMgr::PassedQuestKilledMonsterCredit (Player * player, Quest const * qinfo, uint32 entry, uint32 real_entry, ObjectGuid guid)
Definition at line 2546 of file ScriptMgr.cpp.
 {
     bool ret = true;
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret) // return true by default if not scripts
         if (!itr->second->PassedQuestKilledMonsterCredit(player, qinfo, entry, real_entry, guid))
             ret = false; // we change ret value only when scripts return false
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
PetitionBuy()
void ScriptMgr::PetitionBuy (Player * player, Creature * creature, uint32 & charterid, uint32 & cost, uint32 & type)
Definition at line 2332 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->PetitionBuy(player, creature, charterid, cost, type);
 }
References FOREACH_SCRIPT.
PetitionShowList()
void ScriptMgr::PetitionShowList (Player * player, Creature * creature, uint32 & CharterEntry, uint32 & CharterDispayID, uint32 & CharterCost)
Definition at line 2337 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(PlayerScript)->PetitionShowList(player, creature, CharterEntry, CharterDispayID, CharterCost);
 }
References FOREACH_SCRIPT.
ScriptsVersion()
const char* ScriptMgr::ScriptsVersion () const inline
Definition at line 1490 of file ScriptMgr.h.
 { return "Integrated Azeroth Scripts"; }
SetRealmCompleted()
void ScriptMgr::SetRealmCompleted (AchievementEntry const * achievement)
Definition at line 2932 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(AchievementScript)->SetRealmCompleted(achievement);
 }
References FOREACH_SCRIPT.
SetScriptLoader()
void ScriptMgr::SetScriptLoader (ScriptLoaderCallbackType script_loader_callback) inline
Sets the script loader callback which is invoked to load scripts (Workaround for circular dependency game <-> scripts)
Definition at line 1499 of file ScriptMgr.h.
     {
         _script_loader_callback = script_loader_callback;
     }
References _script_loader_callback.
ShouldBeRewardedWithMoneyInsteadOfExp()
bool ScriptMgr::ShouldBeRewardedWithMoneyInsteadOfExp (Player * player)
Definition at line 1765 of file ScriptMgr.cpp.
 {
     bool ret = false; // return false by default if not scripts
     FOR_SCRIPTS_RET(PlayerScript, itr, end, ret)
         if (itr->second->ShouldBeRewardedWithMoneyInsteadOfExp(player))
             ret = true; // we change ret value only when a script returns true
     return ret;
 }
References FOR_SCRIPTS_RET, and ret.
Unload()
void ScriptMgr::Unload ()
Definition at line 75 of file ScriptMgr.cpp.
 {
 #define SCR_CLEAR(T) \
         for (SCR_REG_ITR(T) itr = SCR_REG_LST(T).begin(); itr != SCR_REG_LST(T).end(); ++itr) \
             delete itr->second; \
         SCR_REG_LST(T).clear();
     // Clear scripts for every script type.
     SCR_CLEAR(SpellScriptLoader);
     SCR_CLEAR(ServerScript);
     SCR_CLEAR(WorldScript);
     SCR_CLEAR(FormulaScript);
     SCR_CLEAR(WorldMapScript);
     SCR_CLEAR(InstanceMapScript);
     SCR_CLEAR(BattlegroundMapScript);
     SCR_CLEAR(ItemScript);
     SCR_CLEAR(CreatureScript);
     SCR_CLEAR(GameObjectScript);
     SCR_CLEAR(AreaTriggerScript);
     SCR_CLEAR(BattlegroundScript);
     SCR_CLEAR(OutdoorPvPScript);
     SCR_CLEAR(CommandScript);
     SCR_CLEAR(WeatherScript);
     SCR_CLEAR(AuctionHouseScript);
     SCR_CLEAR(ConditionScript);
     SCR_CLEAR(VehicleScript);
     SCR_CLEAR(DynamicObjectScript);
     SCR_CLEAR(TransportScript);
     SCR_CLEAR(AchievementCriteriaScript);
     SCR_CLEAR(PlayerScript);
     SCR_CLEAR(AccountScript);
     SCR_CLEAR(GuildScript);
     SCR_CLEAR(GroupScript);
     SCR_CLEAR(GlobalScript);
     SCR_CLEAR(ModuleScript);
     SCR_CLEAR(BGScript);
     SCR_CLEAR(AchievementScript);
     SCR_CLEAR(ArenaTeamScript);
     SCR_CLEAR(SpellSC);
     SCR_CLEAR(GameEventScript);
     SCR_CLEAR(MailScript);
     SCR_CLEAR(MiscScript);
     SCR_CLEAR(PetScript);
     SCR_CLEAR(ArenaScript);
     SCR_CLEAR(CommandSC);
     SCR_CLEAR(DatabaseScript);
 #undef SCR_CLEAR
     delete[] SpellSummary;
 }
References SCR_CLEAR, and SpellSummary.
ValidateSpellAtCastSpell()
void ScriptMgr::ValidateSpellAtCastSpell (Player * player, uint32 & oldSpellId, uint32 & spellId, uint8 & castCount, uint8 & castFlags)
Definition at line 3123 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->ValidateSpellAtCastSpell(player, oldSpellId, spellId, castCount, castFlags);
 }
References FOREACH_SCRIPT.
ValidateSpellAtCastSpellResult()
void ScriptMgr::ValidateSpellAtCastSpellResult (Player * player, Unit * mover, Spell * spell, uint32 oldSpellId, uint32 spellId)
Definition at line 3128 of file ScriptMgr.cpp.
 {
     FOREACH_SCRIPT(MiscScript)->ValidateSpellAtCastSpellResult(player, mover, spell, oldSpellId, spellId);
 }
References FOREACH_SCRIPT.
~ScriptMgr()
ScriptMgr::~ScriptMgr () private virtual
Definition at line 54 of file ScriptMgr.cpp.
 { }
Friends And Related Function Documentation
ScriptObject
friend class ScriptObject friend
Definition at line 1477 of file ScriptMgr.h.
Member Data Documentation
_scheduledScripts
std::atomic<long> ScriptMgr::_scheduledScripts private
Definition at line 1964 of file ScriptMgr.h.
Referenced by DecreaseScheduledScriptCount(), IncreaseScheduledScriptsCount(), and IsScriptScheduled().
_script_loader_callback
ScriptLoaderCallbackType ScriptMgr::_script_loader_callback private
Definition at line 1966 of file ScriptMgr.h.
Referenced by Initialize(), and SetScriptLoader().
_scriptCount
uint32 ScriptMgr::_scriptCount private
Definition at line 1961 of file ScriptMgr.h.
Referenced by GetScriptCount(), and IncrementScriptCount().
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptMgr.h
src/server/game/Scripting/ScriptMgr.cpp