Azerotcore-wotlk: deps/mysqllite/include/mysql/service_my_snprintf.h File Reference
service_my_snprintf.h File Reference
#include <stdarg.h>
#include <stdlib.h>
Classes
struct my_snprintf_service_st
Macros
#define MYSQL_SERVICE_MY_SNPRINTF_INCLUDED
Functions
size_t my_snprintf (char *to, size_t n, const char *fmt,...)
size_t my_vsnprintf (char *to, size_t n, const char *fmt, va_list ap)
Variables
struct my_snprintf_service_st * my_snprintf_service
Detailed Description
my_snprintf service
Portable and limited vsnprintf() implementation.
This is a portable, limited vsnprintf() implementation, with some extra features. "Portable" means that it'll produce identical result on all platforms (for example, on Windows and Linux system printf e formats the exponent differently, on different systems p either prints leading 0x or not, s may accept null pointer or crash on it). "Limited" means that it does not support all the C89 features. But it supports few extensions, not in any standard.
my_vsnprintf(to, n, fmt, ap)
Parameters
[out] to A buffer to store the result in
[in] n Store up to n-1 characters, followed by an end 0
[in] fmt printf-like format string
[in] ap Arguments
Returns
a number of bytes written to a buffer excluding terminating '\0'
Postcondition
The syntax of a format string is generally the same: % <flag> <width> <precision> <length modifier> <format> where everithing but the format is optional.
Three one-character flags are recognized: '0' has the standard zero-padding semantics; '-' is parsed, but silently ignored; '‘’ (backtick) is only supported for strings (s) and means that the string will be quoted according to MySQL identifier quoting rules.
Both <width> and <precision> can be specified as numbers or '*'.
<length modifier> can be 'l', 'll', or 'z'.
Supported formats are 's' (null pointer is accepted, printed as "(null)"), 'b' (extension, see below), 'c', 'd', 'i', 'u', 'x', 'o', 'X', 'p' (works as 0xx).
Standard syntax for positional arguments $n is supported.
Extensions:
Flag '‘’ (backtick): see above.
Format 'b': binary buffer, prints exactly <precision> bytes from the argument, without stopping at '\0'.
Definition in file service_my_snprintf.h.
Macro Definition Documentation
MYSQL_SERVICE_MY_SNPRINTF_INCLUDED
#define MYSQL_SERVICE_MY_SNPRINTF_INCLUDED
Definition at line 99 of file service_my_snprintf.h.
Function Documentation
my_snprintf()
size_t my_snprintf (char * to, size_t n, const char * fmt, ...)
Definition at line 672 of file my_vsnprintf.c.
 {
   size_t result;
   va_list args;
   va_start(args,fmt);
   result= my_vsnprintf(to, n, fmt, args);
   va_end(args);
   return result;
 }
References fmt, and my_vsnprintf().
Referenced by _db_return_(), CLI_MYSQL_REAL_CONNECT(), default_local_infile_init(), default_local_infile_read(), get_collation_name_alias(), my_end(), my_error(), mysql_autodetect_character_set(), and mysql_detach_stmt_list().
my_vsnprintf()
size_t my_vsnprintf (char * to, size_t n, const char * fmt, va_list ap)
Definition at line 666 of file my_vsnprintf.c.
 {
   return my_vsnprintf_ex(&my_charset_latin1, to, n, fmt, ap);
 }
References fmt, my_charset_latin1, and my_vsnprintf_ex().
Referenced by DbugVfprintf(), my_printv_error(), my_snprintf(), my_snprintf_8bit(), and set_mysql_extended_error().
Variable Documentation
my_snprintf_service
struct my_snprintf_service_st * my_snprintf_service