Azerotcore-wotlk: npc_gargoyle::npc_gargoyleAI Struct Reference
npc_gargoyle::npc_gargoyleAI Struct Reference
Public Member Functions
npc_gargoyleAI (Creature *creature)
void Reset () override
void WaypointReached (uint32 waypointId) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from hyjal_trashAI
hyjal_trashAI (Creature *creature)
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void DamageTaken (Unit *done_by, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool go
uint32 StrikeTimer
uint32 MoveTimer
float Zpos
bool forcemove
Public Attributes inherited from hyjal_trashAI
InstanceScript * instance
bool IsEvent
uint32 Delay
uint32 LastOverronPos
bool IsOverrun
bool SetupOverrun
uint32 OverrunType
uint8 faction
bool useFlyPath
uint32 damageTaken
float DummyTarget [3]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1266 of file hyjal_trash.cpp.
Constructor & Destructor Documentation
npc_gargoyleAI()
npc_gargoyle::npc_gargoyleAI::npc_gargoyleAI (Creature * creature) inline
Definition at line 1268 of file hyjal_trash.cpp.
                                            : hyjal_trashAI(creature)
         {
             instance = creature->GetInstanceScript();
             go = false;
             for (uint8 i = 0; i < 3; ++i)
                 DummyTarget[i] = 0;
             Reset();
         }
References hyjal_trashAI::DummyTarget, WorldObject::GetInstanceScript(), go, hyjal_trashAI::instance, and Reset().
Member Function Documentation
JustDied()
void npc_gargoyle::npc_gargoyleAI::JustDied (Unit * killer) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1305 of file hyjal_trash.cpp.
         {
             float x, y, z;
             me->GetPosition(x, y, z);
             z = me->GetMap()->GetHeight(me->GetPhaseMask(), x, y, z);
             me->GetMotionMaster()->MovePoint(0, x, y, z);
             me->SetPosition(x, y, z, 0);
             hyjal_trashAI::JustDied(killer);
         }
References Map::GetHeight(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetPhaseMask(), Position::GetPosition(), hyjal_trashAI::JustDied(), ScriptedAI::me, MotionMaster::MovePoint(), Creature::SetPosition(), G3D::x, G3D::y, and G3D::z.
Reset()
void npc_gargoyle::npc_gargoyleAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1283 of file hyjal_trash.cpp.
         {
             forcemove = true;
             Zpos = 10.0f;
             StrikeTimer = 2000 + rand() % 5000;
             MoveTimer = 0;
             me->SetDisableGravity(true);
         }
References forcemove, ScriptedAI::me, MoveTimer, Creature::SetDisableGravity(), StrikeTimer, and Zpos.
Referenced by npc_gargoyleAI().
UpdateAI()
void npc_gargoyle::npc_gargoyleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1315 of file hyjal_trash.cpp.
         {
             hyjal_trashAI::UpdateAI(diff);
             if (IsEvent || IsOverrun)
             {
                 CAST_AI(hyjal_trashAI, me->AI())->SetCanAttack(false);
                 npc_escortAI::UpdateAI(diff);
             }
             if (IsEvent)
             {
                 if (!go)
                 {
                     go = true;
                     if (!useFlyPath)
                     {
                         for (uint8 i = 0; i < 3; ++i)
                             AddWaypoint(i, GargoyleWPs[i][0] + irand(-10, 10), GargoyleWPs[i][1] + irand(-10, 10), GargoyleWPs[i][2]);
                         Start(false, true);
                         SetDespawnAtEnd(false);
                     }
                     else  //fly path FlyPathWPs
                     {
                         for (uint8 i = 0; i < 3; ++i)
                             AddWaypoint(i, FlyPathWPs[i][0] + irand(-10, 10),    FlyPathWPs[i][1] + irand(-10, 10),    FlyPathWPs[i][2]);
                         Start(false, true);
                         SetDespawnAtEnd(false);
                     }
                 }
             }
             if (IsOverrun && !UpdateVictim())
             {
                 if (faction == 0)//alliance
                 {
                     if (StrikeTimer <= diff)
                     {
                         me->CastSpell(DummyTarget[0], DummyTarget[1], DummyTarget[2], SPELL_GARGOYLE_STRIKE, false);
                         StrikeTimer = 2000 + rand() % 1000;
                     }
                     else StrikeTimer -= diff;
                 }
             }
             if (!UpdateVictim())
                 return;
             if (!me->IsWithinDist(me->GetVictim(), 20) || forcemove)
             {
                 forcemove = false;
                 if (forcemove)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->Attack(target, false);
                 }
                 if (MoveTimer <= diff)
                 {
                     float x, y, z;
                     me->GetVictim()->GetPosition(x, y, z);
                     me->GetMotionMaster()->MovePoint(0, x, y, z + Zpos);
                     Zpos -= 1.0f;
                     if (Zpos <= 0)
                         Zpos = 0;
                     MoveTimer = 2000;
                 }
                 else MoveTimer -= diff;
             }
             if (StrikeTimer <= diff)
             {
                 if (me->IsWithinDist(me->GetVictim(), 20))
                 {
                     DoCastVictim(SPELL_GARGOYLE_STRIKE);
                     me->StopMoving();
                     me->GetMotionMaster()->Clear();
                     StrikeTimer = 2000 + rand() % 1000;
                 }
                 else StrikeTimer = 0;
             }
             else StrikeTimer -= diff;
         }
References npc_escortAI::AddWaypoint(), Creature::AI(), Unit::Attack(), CAST_AI, Unit::CastSpell(), MotionMaster::Clear(), diff(), UnitAI::DoCastVictim(), hyjal_trashAI::DummyTarget, hyjal_trashAI::faction, FlyPathWPs, forcemove, GargoyleWPs, Unit::GetMotionMaster(), Position::GetPosition(), Unit::GetVictim(), go, irand(), hyjal_trashAI::IsEvent, hyjal_trashAI::IsOverrun, WorldObject::IsWithinDist(), ScriptedAI::me, MotionMaster::MovePoint(), MoveTimer, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), npc_escortAI::SetDespawnAtEnd(), SPELL_GARGOYLE_STRIKE, npc_escortAI::Start(), Unit::StopMoving(), StrikeTimer, npc_escortAI::UpdateAI(), hyjal_trashAI::UpdateAI(), CreatureAI::UpdateVictim(), hyjal_trashAI::useFlyPath, G3D::x, G3D::y, G3D::z, and Zpos.
WaypointReached()
void npc_gargoyle::npc_gargoyleAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 1292 of file hyjal_trash.cpp.
         {
             if (waypointId == 2 && !IsOverrun)
             {
                 Unit* target = ObjectAccessor::GetUnit(*me, instance->GetGuidData(DATA_THRALL));
                 if (target && target->IsAlive())
                 {
                     me->AddThreat(target, 0.0f);
                     DoCast(target, SPELL_GARGOYLE_STRIKE, true);
                 }
             }
         }
References Unit::AddThreat(), DATA_THRALL, UnitAI::DoCast(), InstanceScript::GetGuidData(), ObjectAccessor::GetUnit(), hyjal_trashAI::instance, Unit::IsAlive(), hyjal_trashAI::IsOverrun, ScriptedAI::me, and SPELL_GARGOYLE_STRIKE.
Member Data Documentation
forcemove
bool npc_gargoyle::npc_gargoyleAI::forcemove
Definition at line 1281 of file hyjal_trash.cpp.
Referenced by Reset(), and UpdateAI().
go
bool npc_gargoyle::npc_gargoyleAI::go
Definition at line 1277 of file hyjal_trash.cpp.
Referenced by npc_gargoyleAI(), and UpdateAI().
MoveTimer
uint32 npc_gargoyle::npc_gargoyleAI::MoveTimer
Definition at line 1279 of file hyjal_trash.cpp.
Referenced by Reset(), and UpdateAI().
StrikeTimer
uint32 npc_gargoyle::npc_gargoyleAI::StrikeTimer
Definition at line 1278 of file hyjal_trash.cpp.
Referenced by Reset(), and UpdateAI().
Zpos
float npc_gargoyle::npc_gargoyleAI::Zpos
Definition at line 1280 of file hyjal_trash.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp