Azerotcore-wotlk: Acore::WorldObjectListSearcher< Check > Struct Template Reference
Acore::WorldObjectListSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectListSearcher (WorldObject const *searcher, std::list< WorldObject * > &objects, Check &check, uint32 mapTypeMask=GRID_MAP_TYPE_MASK_ALL)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (GameObjectMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_mapTypeMask
uint32 i_phaseMask
std::list< WorldObject * > & i_objects
Check & i_check
Detailed Description
template<class Check>
struct Acore::WorldObjectListSearcher< Check >
Definition at line 209 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectListSearcher()
template<class Check > Acore::WorldObjectListSearcher< Check >::WorldObjectListSearcher (WorldObject const * searcher, std::list< WorldObject * > & objects, Check & check, uint32 mapTypeMask = GRID_MAP_TYPE_MASK_ALL) inline
Definition at line 216 of file GridNotifiers.h.
             : i_mapTypeMask(mapTypeMask), i_phaseMask(searcher->GetPhaseMask()), i_objects(objects), i_check(check) {}
Member Function Documentation
Visit() [1/6]
template<class Check > void Acore::WorldObjectListSearcher< Check >::Visit (CorpseMapType & m)
Definition at line 269 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CORPSE))
         return;
     for (CorpseMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (i_check(itr->GetSource()))
             i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CORPSE.
Visit() [2/6]
template<class Check > void Acore::WorldObjectListSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 258 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CREATURE))
         return;
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (i_check(itr->GetSource()))
             i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CREATURE.
Visit() [3/6]
template<class Check > void Acore::WorldObjectListSearcher< Check >::Visit (DynamicObjectMapType & m)
Definition at line 291 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_DYNAMICOBJECT))
         return;
     for (DynamicObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (i_check(itr->GetSource()))
             i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_DYNAMICOBJECT.
Visit() [4/6]
template<class Check > void Acore::WorldObjectListSearcher< Check >::Visit (GameObjectMapType & m)
Definition at line 280 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_GAMEOBJECT))
         return;
     for (GameObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (i_check(itr->GetSource()))
             i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_GAMEOBJECT.
Visit() [5/6]
template<class Check > template<class NOT_INTERESTED > void Acore::WorldObjectListSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 225 of file GridNotifiers.h.
 {}
Visit() [6/6]
template<class Check > void Acore::WorldObjectListSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 247 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_PLAYER))
         return;
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (i_check(itr->GetSource()))
             i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_PLAYER.
Member Data Documentation
i_check
template<class Check > Check& Acore::WorldObjectListSearcher< Check >::i_check
Definition at line 214 of file GridNotifiers.h.
i_mapTypeMask
template<class Check > uint32 Acore::WorldObjectListSearcher< Check >::i_mapTypeMask
Definition at line 211 of file GridNotifiers.h.
i_objects
template<class Check > std::list<WorldObject*>& Acore::WorldObjectListSearcher< Check >::i_objects
Definition at line 213 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::WorldObjectListSearcher< Check >::i_phaseMask
Definition at line 212 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h