Azerotcore-wotlk: boss_archavon::boss_archavonAI Struct Reference
boss_archavon::boss_archavonAI Struct Reference
Public Member Functions
boss_archavonAI (Creature *creature)
void Reset () override
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 61 of file boss_archavon.cpp.
Constructor & Destructor Documentation
boss_archavonAI()
boss_archavon::boss_archavonAI::boss_archavonAI (Creature * creature) inline
Definition at line 63 of file boss_archavon.cpp.
                                                 : ScriptedAI(creature)
             {
                 pInstance = me->GetInstanceScript();
             }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
AttackStart()
void boss_archavon::boss_archavonAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 89 of file boss_archavon.cpp.
             {
                 if (me->HasAura(SPELL_STONED_AURA))
                 {
                     return;
                 }
                 ScriptedAI::AttackStart(who);
             }
References ScriptedAI::AttackStart(), Unit::HasAura(), ScriptedAI::me, and SPELL_STONED_AURA.
EnterCombat()
void boss_archavon::boss_archavonAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 99 of file boss_archavon.cpp.
             {
                 events.ScheduleEvent(EVENT_ROCK_SHARDS, 15000);
                 events.ScheduleEvent(EVENT_CHOKING_CLOUD, 30000);
                 events.ScheduleEvent(EVENT_STOMP, 45000);
                 events.ScheduleEvent(EVENT_BERSERK, 300000);
                 if (pInstance)
                 {
                     pInstance->SetData(EVENT_ARCHAVON, IN_PROGRESS);
                 }
             }
References EVENT_ARCHAVON, EVENT_BERSERK, EVENT_CHOKING_CLOUD, EVENT_ROCK_SHARDS, EVENT_STOMP, IN_PROGRESS, pInstance, and ZoneScript::SetData().
JustDied()
void boss_archavon::boss_archavonAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 112 of file boss_archavon.cpp.
             {
                 if (pInstance)
                 {
                     pInstance->SetData(EVENT_ARCHAVON, DONE);
                 }
             }
References DONE, EVENT_ARCHAVON, pInstance, and ZoneScript::SetData().
Reset()
void boss_archavon::boss_archavonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 71 of file boss_archavon.cpp.
             {
                 events.Reset();
                 if (pInstance)
                 {
                     if (pInstance->GetData(DATA_STONED))
                     {
                         if (Aura* aur = me->AddAura(SPELL_STONED_AURA, me))
{
                             aur->SetMaxDuration(60 * MINUTE* IN_MILLISECONDS);
                             aur->SetDuration(60 * MINUTE* IN_MILLISECONDS);
                         }
                     }
                     pInstance->SetData(EVENT_ARCHAVON, NOT_STARTED);
                 }
             }
References Unit::AddAura(), DATA_STONED, EVENT_ARCHAVON, ZoneScript::GetData(), IN_MILLISECONDS, ScriptedAI::me, MINUTE, NOT_STARTED, pInstance, ZoneScript::SetData(), and SPELL_STONED_AURA.
UpdateAI()
void boss_archavon::boss_archavonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 120 of file boss_archavon.cpp.
             {
                 if (!UpdateVictim())
                 {
                     return;
                 }
                 events.Update(diff);
                 if (me->HasUnitState(UNIT_STATE_CASTING))
                 {
                     return;
                 }
                 switch (events.ExecuteEvent())
                 {
                     case EVENT_ROCK_SHARDS:
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             DoCast(target, SPELL_ROCK_SHARDS);
                         }
                         events.RepeatEvent(15000);
                         break;
                     case EVENT_CHOKING_CLOUD:
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1))
{
                             DoCast(target, RAID_MODE(SPELL_CRUSHING_LEAP_10, SPELL_CRUSHING_LEAP_25), true); //10y ~ 80y, ignore range
                         }
                         events.RepeatEvent(30000);
                         break;
                     case EVENT_STOMP:
                     {
                         char buffer[100];
                         sprintf(buffer, "Archavon the Stone Watcher lunges for %s!", me->GetVictim()->GetName().c_str());
                         me->TextEmote(buffer);
                         DoCastVictim(RAID_MODE(SPELL_STOMP_10, SPELL_STOMP_25));
                         events.RepeatEvent(45000);
                         events.ScheduleEvent(EVENT_IMPALE, 3000);
                         break;
                     }
                     case EVENT_IMPALE:
                         DoCastVictim(RAID_MODE(SPELL_IMPALE_10, SPELL_IMPALE_25));
                         break;
                     case EVENT_BERSERK:
                         DoCast(me, SPELL_BERSERK, true);
                         Talk(EMOTE_BERSERK);
                         break;
                     default:
                         break;
                 }
                 DoMeleeAttackIfReady();
             }
References UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_BERSERK, EVENT_BERSERK, EVENT_CHOKING_CLOUD, EVENT_IMPALE, EVENT_ROCK_SHARDS, EVENT_STOMP, WorldObject::GetName(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, ScriptedAI::RAID_MODE(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BERSERK, SPELL_CRUSHING_LEAP_10, SPELL_CRUSHING_LEAP_25, SPELL_IMPALE_10, SPELL_IMPALE_25, SPELL_ROCK_SHARDS, SPELL_STOMP_10, SPELL_STOMP_25, CreatureAI::Talk(), Unit::TextEmote(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_archavon::boss_archavonAI::events
Definition at line 69 of file boss_archavon.cpp.
pInstance
InstanceScript* boss_archavon::boss_archavonAI::pInstance
Definition at line 68 of file boss_archavon.cpp.
Referenced by boss_archavonAI(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/VaultOfArchavon/boss_archavon.cpp