Azerotcore-wotlk: npc_taldaram_flamesphere::npc_taldaram_flamesphereAI Struct Reference
npc_taldaram_flamesphere::npc_taldaram_flamesphereAI Struct Reference
Public Member Functions
npc_taldaram_flamesphereAI (Creature *pCreature)
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 id) override
void IsSummonedBy (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
void SetVictimPos (Position const &pos)
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
Position victimPos
InstanceScript * instance
uint32 uiDespawnTimer
uint32 moveTimer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 101 of file boss_prince_taldaram.cpp.
Constructor & Destructor Documentation
npc_taldaram_flamesphereAI()
npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::npc_taldaram_flamesphereAI (Creature * pCreature) inline
Definition at line 103 of file boss_prince_taldaram.cpp.
                                                         : NullCreatureAI(pCreature),
             instance(pCreature->GetInstanceScript()),
             uiDespawnTimer(13000),
             moveTimer(0)
         {
             pCreature->SetReactState(REACT_PASSIVE);
         }
References REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
DoAction()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 111 of file boss_prince_taldaram.cpp.
         {
             if (action == ACTION_SPHERE)
             {
                 moveTimer = 3000;
             }
         }
References ACTION_SPHERE, and moveTimer.
IsSummonedBy()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::IsSummonedBy (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 127 of file boss_prince_taldaram.cpp.
         {
             // Replace sphere instantly if sphere is summoned after prince death
             if (instance->GetBossState(DATA_PRINCE_TALDARAM) != IN_PROGRESS)
             {
                 me->DespawnOrUnsummon();
                 return;
             }
             DoCastSelf(SPELL_FLAME_SPHERE_SPAWN_EFFECT);
             DoCastSelf(SPELL_FLAME_SPHERE_VISUAL);
             // TODO: replace with DespawnOrUnsummon
             uiDespawnTimer = 13000;
         }
References DATA_PRINCE_TALDARAM, Creature::DespawnOrUnsummon(), UnitAI::DoCastSelf(), InstanceScript::GetBossState(), IN_PROGRESS, instance, CreatureAI::me, SPELL_FLAME_SPHERE_SPAWN_EFFECT, SPELL_FLAME_SPHERE_VISUAL, and uiDespawnTimer.
JustDied()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 143 of file boss_prince_taldaram.cpp.
         {
             DoCastSelf(SPELL_FLAME_SPHERE_DEATH_EFFECT);
         }
References UnitAI::DoCastSelf(), and SPELL_FLAME_SPHERE_DEATH_EFFECT.
MovementInform()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 119 of file boss_prince_taldaram.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_ORB)
             {
                 me->DisappearAndDie();
             }
         }
References Creature::DisappearAndDie(), CreatureAI::me, POINT_MOTION_TYPE, and POINT_ORB.
SetVictimPos()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::SetVictimPos (Position const & pos) inline
Definition at line 196 of file boss_prince_taldaram.cpp.
         {
             victimPos.Relocate(pos);
         }
References pos(), Position::Relocate(), and victimPos.
UpdateAI()
void npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 148 of file boss_prince_taldaram.cpp.
         {
             if (moveTimer)
             {
                 if (moveTimer <= diff)
                 {
                     DoCastSelf(SPELL_FLAME_SPHERE_PERIODIC);
                     float angleOffset = 0.0f;
                     switch (me->GetEntry())
                     {
                         case NPC_FLAME_SPHERE_1:
                             break;
                         case NPC_FLAME_SPHERE_2:
                             angleOffset = DATA_SPHERE_ANGLE_OFFSET;
                             break;
                         case NPC_FLAME_SPHERE_3:
                             angleOffset = -DATA_SPHERE_ANGLE_OFFSET;
                             break;
                         default:
                             return;
                     }
                     float angle = me->GetAngle(&victimPos) + angleOffset;
                     float x = me->GetPositionX() + DATA_SPHERE_DISTANCE * cos(angle);
                     float y = me->GetPositionY() + DATA_SPHERE_DISTANCE * sin(angle);
                     me->GetMotionMaster()->MovePoint(POINT_ORB, x, y, me->GetPositionZ());
                     moveTimer = 0;
                 }
                 else
                 {
                     moveTimer -= diff;
                 }
             }
             if (uiDespawnTimer)
             {
                 if (uiDespawnTimer <= diff)
                 {
                     me->DisappearAndDie();
                     uiDespawnTimer = 0;
                 }
                 else
                     uiDespawnTimer -= diff;
             }
         }
References DATA_SPHERE_ANGLE_OFFSET, DATA_SPHERE_DISTANCE, diff(), Creature::DisappearAndDie(), UnitAI::DoCastSelf(), Position::GetAngle(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), CreatureAI::me, MotionMaster::MovePoint(), moveTimer, NPC_FLAME_SPHERE_1, NPC_FLAME_SPHERE_2, NPC_FLAME_SPHERE_3, POINT_ORB, SPELL_FLAME_SPHERE_PERIODIC, uiDespawnTimer, victimPos, G3D::x, and G3D::y.
Member Data Documentation
instance
InstanceScript* npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::instance private
Definition at line 203 of file boss_prince_taldaram.cpp.
Referenced by IsSummonedBy().
moveTimer
uint32 npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::moveTimer private
Definition at line 205 of file boss_prince_taldaram.cpp.
Referenced by DoAction(), and UpdateAI().
uiDespawnTimer
uint32 npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::uiDespawnTimer private
Definition at line 204 of file boss_prince_taldaram.cpp.
Referenced by IsSummonedBy(), and UpdateAI().
victimPos
Position npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::victimPos private
Definition at line 202 of file boss_prince_taldaram.cpp.
Referenced by SetVictimPos(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_prince_taldaram.cpp