Azerotcore-wotlk: CastArmageddon Class Reference
CastArmageddon Class Reference
Public Member Functions
CastArmageddon (Creature *caster)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _caster
Detailed Description
Definition at line 144 of file boss_kiljaeden.cpp.
Constructor & Destructor Documentation
CastArmageddon()
CastArmageddon::CastArmageddon (Creature * caster) inline
Definition at line 147 of file boss_kiljaeden.cpp.
                                      : _caster(caster)
     {
     }
Member Function Documentation
Execute()
bool CastArmageddon::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 151 of file boss_kiljaeden.cpp.
     {
         _caster->CastSpell(_caster, SPELL_ARMAGEDDON_MISSILE, true);
         _caster->SetPosition(_caster->GetPositionX(), _caster->GetPositionY(), _caster->GetPositionZ() - 20.0f, 0.0f);
         return true;
     }
References _caster, Unit::CastSpell(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::SetPosition(), and SPELL_ARMAGEDDON_MISSILE.
Member Data Documentation
_caster
Creature* CastArmageddon::_caster private
Definition at line 159 of file boss_kiljaeden.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp