Azerotcore-wotlk: deps/recastnavigation/Detour/Include/DetourMath.h File Reference
DetourMath.h File Reference
#include <math.h>
#include <cmath>
Functions
float dtMathFabsf (float x)
float dtMathSqrtf (float x)
float dtMathFloorf (float x)
float dtMathCeilf (float x)
float dtMathCosf (float x)
float dtMathSinf (float x)
float dtMathAtan2f (float y, float x)
bool dtMathIsfinite (float x)
Function Documentation
dtMathAtan2f()
float dtMathAtan2f (float y, float x) inline
Definition at line 21 of file DetourMath.h.
 { return atan2f(y, x); }
References G3D::x, and G3D::y.
dtMathCeilf()
float dtMathCeilf (float x) inline
Definition at line 18 of file DetourMath.h.
 { return ceilf(x); }
References G3D::x.
Referenced by createBVTree().
dtMathCosf()
float dtMathCosf (float x) inline
Definition at line 19 of file DetourMath.h.
 { return cosf(x); }
References G3D::x.
dtMathFabsf()
float dtMathFabsf (float x) inline
Definition at line 15 of file DetourMath.h.
 { return fabsf(x); }
References G3D::x.
dtMathFloorf()
float dtMathFloorf (float x) inline
Definition at line 17 of file DetourMath.h.
 { return floorf(x); }
References G3D::x.
Referenced by createBVTree().
dtMathIsfinite()
bool dtMathIsfinite (float x) inline
Definition at line 22 of file DetourMath.h.
 { return std::isfinite(x); }
References isfinite(), and G3D::x.
Referenced by dtVisfinite(), dtVisfinite2D(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPolysAroundCircle(), and dtNavMeshQuery::findRandomPointAroundCircle().
dtMathSinf()
float dtMathSinf (float x) inline
Definition at line 20 of file DetourMath.h.
 { return sinf(x); }
References G3D::x.
dtMathSqrtf()
float dtMathSqrtf (float x) inline
Definition at line 16 of file DetourMath.h.
 { return sqrtf(x); }
References G3D::x.
Referenced by dtRandomPointInConvexPoly(), dtVdist(), dtVdist2D(), dtVlen(), dtVnormalize(), PathGenerator::FindSmoothPath(), and PathGenerator::GetPathPolyByPosition().