Azerotcore-wotlk: adt_MCIN Class Reference
adt_MCIN Class Reference
#include <adt.h>
Classes
struct adt_CELLS
Public Member Functions
bool prepareLoadedData ()
adt_MCNK * getMCNK (int x, int y)
Public Attributes
uint32 size
struct adt_MCIN::adt_CELLS cells [ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
uint32 fcc
char fcc_txt [4]
Private Attributes
union {
uint32 fcc
char fcc_txt [4]
};
Detailed Description
Definition at line 153 of file adt.h.
Member Function Documentation
getMCNK()
adt_MCNK* adt_MCIN::getMCNK (int x, int y) inline
Definition at line 172 of file adt.h.
     {
         if (cells[x][y].offsMCNK)
             return (adt_MCNK*)((uint8*)this + cells[x][y].offsMCNK - 84);
         return nullptr;
     }
References cells.
Referenced by ConvertADT(), and prepareLoadedData().
prepareLoadedData()
bool adt_MCIN::prepareLoadedData ()
Definition at line 101 of file adt.cpp.
 {
     if (fcc != MCINMagic.fcc)
         return false;
     // Check cells data
     for (int i = 0; i < ADT_CELLS_PER_GRID; i++)
         for (int j = 0; j < ADT_CELLS_PER_GRID; j++)
             if (cells[i][j].offsMCNK && !getMCNK(i, j)->prepareLoadedData())
                 return false;
     return true;
 }
References ADT_CELLS_PER_GRID, cells, fcc, u_map_fcc::fcc, getMCNK(), and MCINMagic.
Member Data Documentation
union { ... }
cells
struct adt_MCIN::adt_CELLS adt_MCIN::cells[ADT_CELLS_PER_GRID][ADT_CELLS_PER_GRID]
Referenced by getMCNK(), and prepareLoadedData().
fcc
uint32 adt_MCIN::fcc
Definition at line 157 of file adt.h.
Referenced by prepareLoadedData().
fcc_txt
char adt_MCIN::fcc_txt[4]
Definition at line 158 of file adt.h.
size
uint32 adt_MCIN::size
Definition at line 161 of file adt.h.
The documentation for this class was generated from the following files:
src/tools/map_extractor/adt.h
src/tools/map_extractor/adt.cpp