Azerotcore-wotlk: npc_arthas::npc_arthasAI Struct Reference
npc_arthas::npc_arthasAI Struct Reference
Public Member Functions
npc_arthasAI (Creature *creature)
Creature * GetEventNpc (uint32 entry)
void ScheduleNextEvent (uint32 currentEvent, uint32 time)
void SummonNextWave ()
void ReorderInstance (uint32 data)
void EnterCombat (Unit *) override
void SendNextWave (uint32 entry)
void SpawnTimeRift ()
void JustDied (Unit *) override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void SummonedCreatureDies (Creature *cr, Unit *) override
void DoAction (int32 param) override
void Reset () override
void WaypointReached (uint32 uiPointId) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
SummonList summons
bool eventInRun
EventMap actionEvents
EventMap combatEvents
uint8 waveGroupId
uint8 waveKillCount
uint8 timeRiftId
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 375 of file culling_of_stratholme.cpp.
Constructor & Destructor Documentation
npc_arthasAI()
npc_arthas::npc_arthasAI::npc_arthasAI (Creature * creature) inline
Definition at line 377 of file culling_of_stratholme.cpp.
                                          : npc_escortAI(creature), summons(me)
         {
             pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DoAction()
void npc_arthas::npc_arthasAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 419 of file culling_of_stratholme.cpp.
         {
             if (param == ACTION_START_EVENT)
             {
                 // Event
                 eventInRun = true;
                 actionEvents.ScheduleEvent(EVENT_ACTION_PHASE1, 0);
             }
             else if (param == ACTION_START_CITY)
             {
                 Talk(SAY_PHASE201);
                 actionEvents.ScheduleEvent(EVENT_ACTION_PHASE2, 12000);
                 SetRun(false);
                 eventInRun = true;
                 me->SummonCreature(NPC_CITY_MAN, EventPos[EVENT_SRC_TOWN_CITYMAN1]);
                 me->SummonCreature(NPC_CITY_MAN2, EventPos[EVENT_SRC_TOWN_CITYMAN2]);
             }
             else if (param == ACTION_KILLED_SALRAMM)
             {
                 waveGroupId = 10;
                 eventInRun = true;
                 SetRun(true);
                 actionEvents.ScheduleEvent(EVENT_ACTION_PHASE2 + 9, 10000);
             }
             else if (param == ACTION_START_TOWN_HALL)
             {
                 Talk(SAY_PHASE301);
                 SetEscortPaused(false);
                 SetRun(false);
                 if (Creature* cr = me->SummonCreature(NPC_CITY_MAN3, EventPos[EVENT_SRC_HALL_CITYMAN1]))
                 {
                     cr->AI()->DoAction(ACTION_FORCE_CHANGE_LOCK);
                 }
                 if (Creature* cr = me->SummonCreature(NPC_CITY_MAN4, EventPos[EVENT_SRC_HALL_CITYMAN2]))
                 {
                     cr->AI()->DoAction(ACTION_FORCE_CHANGE_LOCK);
                 }
                 if (Creature* cr = me->SummonCreature(NPC_CITY_MAN,  EventPos[EVENT_SRC_HALL_CITYMAN3]))
                 {
                     cr->AI()->DoAction(ACTION_FORCE_CHANGE_LOCK);
                 }
             }
             else if (param == ACTION_START_SECRET_PASSAGE)
             {
                 Talk(SAY_PHASE401);
                 SetEscortPaused(false);
                 SetRun(false);
             }
             else if (param == ACTION_START_LAST_CITY)
             {
                 Talk(SAY_PHASE404);
                 SetEscortPaused(false);
                 SetRun(true);
             }
             else if (param == ACTION_START_MALGANIS)
             {
                 summons.DespawnAll();
                 if (Creature* cr = me->SummonCreature(NPC_MAL_GANIS, EventPos[EVENT_SRC_MALGANIS_FINAL]))
                 {
                     summons.Despawn(cr);
                     summons.Summon(cr);
                     cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                     cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 }
                 Talk(SAY_PHASE501);
                 SetEscortPaused(false);
                 SetRun(true);
             }
             else if (param == ACTION_KILLED_MALGANIS)
             {
                 EnterEvadeMode();
                 eventInRun = true;
                 actionEvents.ScheduleEvent(EVENT_ACTION_PHASE5 + 1, 22000);
                 me->SetFacingTo(1.84f);
                 if (!me->GetMap()->GetPlayers().isEmpty())
                     if (Player* player = me->GetMap()->GetPlayers().getFirst()->GetSource())
                         player->RewardPlayerAndGroupAtEvent(31006, player); // Malganis quest entry required
             }
         }
References ACTION_FORCE_CHANGE_LOCK, ACTION_KILLED_MALGANIS, ACTION_KILLED_SALRAMM, ACTION_START_CITY, ACTION_START_EVENT, ACTION_START_LAST_CITY, ACTION_START_MALGANIS, ACTION_START_SECRET_PASSAGE, ACTION_START_TOWN_HALL, actionEvents, SummonList::Despawn(), SummonList::DespawnAll(), npc_escortAI::EnterEvadeMode(), EVENT_ACTION_PHASE1, EVENT_ACTION_PHASE2, EVENT_ACTION_PHASE5, EVENT_SRC_HALL_CITYMAN1, EVENT_SRC_HALL_CITYMAN2, EVENT_SRC_HALL_CITYMAN3, EVENT_SRC_MALGANIS_FINAL, EVENT_SRC_TOWN_CITYMAN1, EVENT_SRC_TOWN_CITYMAN2, eventInRun, EventPos, MapRefMgr::getFirst(), WorldObject::GetMap(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), LinkedListHead::isEmpty(), ScriptedAI::me, NPC_CITY_MAN, NPC_CITY_MAN2, NPC_CITY_MAN3, NPC_CITY_MAN4, NPC_MAL_GANIS, SAY_PHASE201, SAY_PHASE301, SAY_PHASE401, SAY_PHASE404, SAY_PHASE501, EventMap::ScheduleEvent(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), npc_escortAI::SetRun(), SummonList::Summon(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, and waveGroupId.
EnterCombat()
void npc_arthas::npc_arthasAI::EnterCombat (Unit *) override virtual
Reimplemented from ScriptedAI.
Definition at line 1235 of file culling_of_stratholme.cpp.
 {
     DoCast(me, SPELL_ARTHAS_AURA);
     // Fight
     combatEvents.ScheduleEvent(EVENT_COMBAT_EXORCISM, 2000);
     combatEvents.ScheduleEvent(EVENT_COMBAT_HEALTH_CHECK, 2000);
 }
References EVENT_COMBAT_EXORCISM, EVENT_COMBAT_HEALTH_CHECK, and SPELL_ARTHAS_AURA.
GetEventNpc()
Creature * npc_arthas::npc_arthasAI::GetEventNpc (uint32 entry)
Definition at line 1198 of file culling_of_stratholme.cpp.
 {
     for (SummonList::iterator i = summons.begin(); i != summons.end();)
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, *i);
         if (!summon)
             summons.erase(i++);
         else if (summon->GetEntry() == entry)
             return summon;
         else
             ++i;
     }
     return nullptr;
 }
References SummonList::begin(), SummonList::end(), SummonList::erase(), ObjectAccessor::GetCreature(), Object::GetEntry(), ScriptedAI::me, and summons.
Referenced by UpdateAI(), and WaypointReached().
JustDied()
void npc_arthas::npc_arthasAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 399 of file culling_of_stratholme.cpp.
         {
             RemoveEscortState(STATE_ESCORT_ESCORTING);
             if (pInstance)
                 pInstance->SetData(DATA_ARTHAS_REPOSITION, 2);
         }
References DATA_ARTHAS_REPOSITION, pInstance, npc_escortAI::RemoveEscortState(), ZoneScript::SetData(), and STATE_ESCORT_ESCORTING.
JustSummoned()
void npc_arthas::npc_arthasAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 406 of file culling_of_stratholme.cpp.
         {
             summons.Summon(cr);
         }
References SummonList::Summon(), and summons.
ReorderInstance()
void npc_arthas::npc_arthasAI::ReorderInstance (uint32 data)
Definition at line 1244 of file culling_of_stratholme.cpp.
 {
     Start(true, true);
     SetEscortPaused(true);
     SetDespawnAtEnd(false);
     switch (data)
     {
         case COS_PROGRESS_FINISHED_INTRO:
             SetNextWaypoint(9, false);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             break;
         case COS_PROGRESS_FINISHED_CITY_INTRO:
         case COS_PROGRESS_KILLED_MEATHOOK:
         case COS_PROGRESS_KILLED_SALRAMM:
             SetNextWaypoint(12, false);
             me->SetReactState(REACT_DEFENSIVE);
             if (data == COS_PROGRESS_FINISHED_CITY_INTRO)
             {
                 eventInRun = true;
                 actionEvents.RescheduleEvent(EVENT_ACTION_PHASE2 + 8, 10000);
             }
             else if (data == COS_PROGRESS_KILLED_MEATHOOK)
             {
                 waveGroupId = 4;
                 SendNextWave(NPC_MEATHOOK);
             }
             else // if (data == COS_PROGRESS_KILLED_SALRAMM)
             {
                 if (pInstance)
                     pInstance->DoUpdateWorldState(WORLDSTATE_WAVE_COUNT, 10);
                 DoAction(ACTION_KILLED_SALRAMM);
             }
             break;
         case COS_PROGRESS_REACHED_TOWN_HALL:
             SetNextWaypoint(21, false);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             break;
         case COS_PROGRESS_KILLED_EPOCH:
             SetNextWaypoint(32, false);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             break;
         case COS_PROGRESS_LAST_CITY:
             SetNextWaypoint(46, false);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             break;
         case COS_PROGRESS_BEFORE_MALGANIS:
             SetNextWaypoint(55, false);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             break;
     }
     if (data >= COS_PROGRESS_KILLED_EPOCH)
         if (pInstance)
             if (GameObject* pGate = pInstance->instance->GetGameObject(pInstance->GetGuidData(DATA_SHKAF_GATE)))
                 pGate->SetGoState(GO_STATE_READY);
     pInstance->SetData(DATA_SHOW_INFINITE_TIMER, 1);
 }
References ACTION_KILLED_SALRAMM, COS_PROGRESS_BEFORE_MALGANIS, COS_PROGRESS_FINISHED_CITY_INTRO, COS_PROGRESS_FINISHED_INTRO, COS_PROGRESS_KILLED_EPOCH, COS_PROGRESS_KILLED_MEATHOOK, COS_PROGRESS_KILLED_SALRAMM, COS_PROGRESS_LAST_CITY, COS_PROGRESS_REACHED_TOWN_HALL, DATA_SHKAF_GATE, DATA_SHOW_INFINITE_TIMER, EVENT_ACTION_PHASE2, GO_STATE_READY, NPC_MEATHOOK, REACT_DEFENSIVE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and WORLDSTATE_WAVE_COUNT.
Referenced by Reset().
Reset()
void npc_arthas::npc_arthasAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 502 of file culling_of_stratholme.cpp.
         {
             actionEvents.Reset();
             combatEvents.Reset();
             summons.DespawnAll();
             eventInRun = false;
             waveGroupId = 0;
             waveKillCount = 0;
             timeRiftId = 0;
             me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             if (pInstance)
             {
                 pInstance->SetData(DATA_ARTHAS_REPOSITION, 1);
                 uint32 data = pInstance->GetData(DATA_ARTHAS_EVENT);
                 if (data >= COS_PROGRESS_FINISHED_INTRO)
                     ReorderInstance(data);
             }
         }
References actionEvents, combatEvents, COS_PROGRESS_FINISHED_INTRO, DATA_ARTHAS_EVENT, DATA_ARTHAS_REPOSITION, SummonList::DespawnAll(), eventInRun, ZoneScript::GetData(), ScriptedAI::me, pInstance, Object::RemoveFlag(), ReorderInstance(), EventMap::Reset(), ZoneScript::SetData(), summons, timeRiftId, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, waveGroupId, and waveKillCount.
ScheduleNextEvent()
void npc_arthas::npc_arthasAI::ScheduleNextEvent (uint32 currentEvent, uint32 time)
Definition at line 1214 of file culling_of_stratholme.cpp.
 {
     actionEvents.ScheduleEvent(currentEvent + 1, time);
 }
Referenced by UpdateAI().
SendNextWave()
void npc_arthas::npc_arthasAI::SendNextWave (uint32 entry)
Definition at line 1305 of file culling_of_stratholme.cpp.
 {
     if (!pInstance)
         return;
     if (entry == NPC_MEATHOOK)
     {
         waveKillCount = 4;
         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_KILLED_MEATHOOK);
     }
     else if (entry == NPC_SALRAMM)
     {
         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_KILLED_SALRAMM);
         return;
     }
     // Group is killed
     if (++waveKillCount >= 4)
     {
         waveGroupId++;
         if (waveGroupId == 4) // Meathook
             me->SummonCreature(NPC_MEATHOOK, EventPos[EVENT_SRC_MEATHOOK]);
         else if (waveGroupId == 9) // Salramm
             me->SummonCreature(NPC_SALRAMM, EventPos[EVENT_SRC_SALRAMM]);
         else
             SummonNextWave();
         pInstance->DoUpdateWorldState(WORLDSTATE_WAVE_COUNT, waveGroupId + 1);
     }
 }
References COS_PROGRESS_KILLED_MEATHOOK, COS_PROGRESS_KILLED_SALRAMM, DATA_ARTHAS_EVENT, EVENT_SRC_MEATHOOK, EVENT_SRC_SALRAMM, EventPos, NPC_MEATHOOK, NPC_SALRAMM, and WORLDSTATE_WAVE_COUNT.
Referenced by SummonedCreatureDies().
SpawnTimeRift()
void npc_arthas::npc_arthasAI::SpawnTimeRift ()
Definition at line 1336 of file culling_of_stratholme.cpp.
 {
     if (timeRiftId >= 5)
         return;
     for (uint8 i = 0; i < uint8(timeRiftId == 0 ? ENCOUNTER_CHRONO_MAX_SPAWNS_FIRST : ENCOUNTER_CHRONO_MAX_SPAWNS_SECOND); ++i)
     {
         // Spawn everyone at time rift pos
         if (Creature* cr = me->SummonCreature(/*entry*/(uint32)RiftAndSpawnsLocations[timeRiftId][i][0], RiftAndSpawnsLocations[timeRiftId][0][1], RiftAndSpawnsLocations[timeRiftId][0][2], RiftAndSpawnsLocations[timeRiftId][0][3], RiftAndSpawnsLocations[timeRiftId][0][4]))
         {
             if (cr->GetEntry() == NPC_TIME_RIFT)
                 cr->DespawnOrUnsummon(10000);
             else // x, y, z (0 is entry)
             {
                 // first infinite
                 if (i == 1)
                     AttackStart(cr);
                 cr->SetInCombatWithZone();
                 cr->AddThreat(me, 0.0f);
                 cr->SetReactState(REACT_AGGRESSIVE);
                 cr->GetMotionMaster()->MovePoint(POINT_CHRONOS, RiftAndSpawnsLocations[timeRiftId][i][1], RiftAndSpawnsLocations[timeRiftId][i][2], RiftAndSpawnsLocations[timeRiftId][i][3]);
             }
         }
     }
     timeRiftId++;
 }
References ENCOUNTER_CHRONO_MAX_SPAWNS_FIRST, ENCOUNTER_CHRONO_MAX_SPAWNS_SECOND, NPC_TIME_RIFT, POINT_CHRONOS, REACT_AGGRESSIVE, RiftAndSpawnsLocations, and WorldObject::SummonCreature().
Referenced by WaypointReached().
SummonedCreatureDespawn()
void npc_arthas::npc_arthasAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 411 of file culling_of_stratholme.cpp.
 { summons.Despawn(cr); }
References SummonList::Despawn(), and summons.
SummonedCreatureDies()
void npc_arthas::npc_arthasAI::SummonedCreatureDies (Creature * cr, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 413 of file culling_of_stratholme.cpp.
         {
             if (pInstance && pInstance->GetData(DATA_ARTHAS_EVENT) > COS_PROGRESS_FINISHED_INTRO && pInstance->GetData(DATA_ARTHAS_EVENT) < COS_PROGRESS_REACHED_TOWN_HALL)
                 SendNextWave(cr->GetEntry());
         }
References COS_PROGRESS_FINISHED_INTRO, COS_PROGRESS_REACHED_TOWN_HALL, DATA_ARTHAS_EVENT, ZoneScript::GetData(), Object::GetEntry(), pInstance, and SendNextWave().
SummonNextWave()
void npc_arthas::npc_arthasAI::SummonNextWave ()
Definition at line 1219 of file culling_of_stratholme.cpp.
 {
     Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
     if (!PlayerList.isEmpty())
         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
             i->GetSource()->PlayerTalkClass->SendPointOfInterest(1000 + waveGroupId);
     waveKillCount = 0; // this is forced condition!
     uint32 tableId = waveGroupId;
     if (tableId > 4)
         tableId--;
     for (uint32 i = 0; i < ENCOUNTER_WAVES_MAX_SPAWNS; ++i)
         me->SummonCreature(/*entry*/(uint32)WavesLocations[tableId][i][0], WavesLocations[tableId][i][1], WavesLocations[tableId][i][2], WavesLocations[tableId][i][3], WavesLocations[tableId][i][4]);
 }
References MapRefMgr::begin(), ENCOUNTER_WAVES_MAX_SPAWNS, MapRefMgr::end(), LinkedListHead::isEmpty(), and WavesLocations.
Referenced by UpdateAI().
UpdateAI()
void npc_arthas::npc_arthasAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 671 of file culling_of_stratholme.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             if (eventInRun)
             {
                 actionEvents.Update(diff);
                 switch (uint32 currentEvent = actionEvents.ExecuteEvent())
                 {
                     case EVENT_ACTION_PHASE1:
                         SetRun(false);
                         me->SummonCreature(NPC_JAINA, EventPos[EVENT_SRC_JAINA], TEMPSUMMON_DEAD_DESPAWN, 180000);
                         if (Creature* uther = me->SummonCreature(NPC_UTHER, EventPos[EVENT_SRC_UTHER], TEMPSUMMON_DEAD_DESPAWN, 180000))
{
                             uther->GetMotionMaster()->MovePoint(0, EventPos[EVENT_DST_UTHER], false);
                             uther->SetTarget(me->GetGUID());
                             me->SetTarget(uther->GetGUID());
                         }
                         for (int i = 0; i < 3; ++i)
                             if (Creature* horse = me->SummonCreature(NPC_HORSE_ESCORT, EventPos[EVENT_SRC_HORSE1 + i], TEMPSUMMON_DEAD_DESPAWN, 180000))
                                 horse->GetMotionMaster()->MovePoint(0, EventPos[EVENT_DST_HORSE1 + i], false);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+1:
                         // Start Event
                         Start(true, false);
                         SetDespawnAtEnd(false);
                         ScheduleNextEvent(currentEvent, 9000);
                         break;
                     // After waypoint 0
                     case EVENT_ACTION_PHASE1+2:
                         Talk(SAY_PHASE101);
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE1+3:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE102);
                         ScheduleNextEvent(currentEvent, 8000);
                         break;
                     case EVENT_ACTION_PHASE1+4:
                         SetEscortPaused(false);
                         eventInRun = false;
                         Talk(SAY_PHASE103);
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     // After waypoint 1
                     case EVENT_ACTION_PHASE1+5:
                         if (Creature* jaina = GetEventNpc(NPC_JAINA))
                             jaina->SetTarget(me->GetGUID());
                         Talk(SAY_PHASE104);
                         ScheduleNextEvent(currentEvent, 10000);
                         break;
                     case EVENT_ACTION_PHASE1+6:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE105);
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE1+7:
                         Talk(SAY_PHASE106);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+8:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE107);
                         ScheduleNextEvent(currentEvent, 6000);
                         break;
                     case EVENT_ACTION_PHASE1+9:
                         Talk(SAY_PHASE108);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+10:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE109);
                         ScheduleNextEvent(currentEvent, 8000);
                         break;
                     case EVENT_ACTION_PHASE1+11:
                         Talk(SAY_PHASE110);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+12:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE111);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+13:
                         Talk(SAY_PHASE112);
                         ScheduleNextEvent(currentEvent, 11000);
                         break;
                     case EVENT_ACTION_PHASE1+14:
                         if (Creature* jaina = GetEventNpc(NPC_JAINA))
                             jaina->AI()->Talk(SAY_PHASE113);
                         ScheduleNextEvent(currentEvent, 2500);
                         break;
                     case EVENT_ACTION_PHASE1+15:
                         Talk(SAY_PHASE114);
                         ScheduleNextEvent(currentEvent, 9000);
                         break;
                     case EVENT_ACTION_PHASE1+16:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
                             uther->AI()->Talk(SAY_PHASE115);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+17:
                         for (SummonList::const_iterator i = summons.begin(); i != summons.end(); ++i)
{
                             Creature* summon = ObjectAccessor::GetCreature(*me, *i);
                             if (summon && summon->GetEntry() == NPC_HORSE_ESCORT)
                                 summon->GetMotionMaster()->MovePoint(0, EventPos[EVENT_POS_RETREAT], false);
                         }
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE1+18:
                         if (Creature* uther = GetEventNpc(NPC_UTHER))
{
                             uther->SetTarget();
                             uther->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                             uther->GetMotionMaster()->MovePoint(0, EventPos[EVENT_POS_RETREAT], false);
                         }
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE1+19:
                         if (Creature* jaina = GetEventNpc(NPC_JAINA))
{
                             jaina->SetTarget();
                             jaina->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                             jaina->GetMotionMaster()->MovePoint(0, EventPos[EVENT_POS_RETREAT], false);
                         }
                         Talk(SAY_PHASE116);
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE1+20:
                         if (Creature* jaina = GetEventNpc(NPC_JAINA))
{
                             jaina->GetMotionMaster()->MoveIdle();
                             jaina->AI()->Talk(SAY_PHASE117);
                         }
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE1+21:
                         if (Creature* jaina = GetEventNpc(NPC_JAINA))
{
                             jaina->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                             jaina->GetMotionMaster()->MovePoint(0, EventPos[EVENT_POS_RETREAT], false);
                         }
                         summons.DespawnEntry(NPC_HORSE_ESCORT);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE1+22:
                         SetEscortPaused(false);
                         eventInRun = false;
                         me->SetTarget();
                         // dont schedule next, do it in gossip select!
                         break;
                     //After Gossip 1 (waypoint 8)
                     case EVENT_ACTION_PHASE2:
                         summons.DespawnEntry(NPC_INVIS_TARGET); // remove trigger
                         me->SetTarget();
                         SetEscortPaused(false);
                         eventInRun = false;
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     // After waypoint 9
                     case EVENT_ACTION_PHASE2+1:
                         if (Creature* cityman = GetEventNpc(NPC_CITY_MAN))
{
                             cityman->AI()->Talk(SAY_PHASE202);
                             cityman->SetTarget(me->GetGUID());
                             cityman->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
                             cityman->GetMotionMaster()->MovePoint(0, EventPos[EVENT_DST_CITYMAN]);
                         }
                         ScheduleNextEvent(currentEvent, 9000);
                         break;
                     case EVENT_ACTION_PHASE2+2:
                         Talk(SAY_PHASE203);
                         SetEscortPaused(false);
                         eventInRun = false;
                         ScheduleNextEvent(currentEvent, 1500);
                         break;
                     // After waypoint 11
                     case EVENT_ACTION_PHASE2+3:
                         if (Creature* stalker = me->SummonCreature(NPC_INVIS_TARGET, 2081.447f, 1287.770f, 141.3241f, 1.37f, TEMPSUMMON_TIMED_DESPAWN, 10000))
{
                             me->SetFacingToObject(stalker);
                             stalker->DespawnOrUnsummon(500);
                         }
                         Talk(SAY_PHASE205);
                         ScheduleNextEvent(currentEvent, 4000);
                         break;
                     case EVENT_ACTION_PHASE2+4:
                         if (Creature* malganis = me->SummonCreature(NPC_MAL_GANIS, EventPos[EVENT_SRC_MALGANIS], TEMPSUMMON_TIMED_DESPAWN, 60000))
{
                             malganis->CastSpell(malganis, SPELL_MALGANIS_APPEAR, true);
                             malganis->AI()->Talk(SAY_PHASE206);
                             malganis->SetTarget(me->GetGUID());
                             me->SetTarget(malganis->GetGUID());
                             malganis->SetReactState(REACT_PASSIVE);
                             std::list<Creature*> unitList;
                             malganis->GetCreaturesWithEntryInRange(unitList, 20.0f, NPC_CITY_MAN);
                             malganis->GetCreaturesWithEntryInRange(unitList, 20.0f, NPC_CITY_MAN2);
                             for (std::list<Creature*>::const_iterator itr = unitList.begin(); itr != unitList.end(); ++itr)
                                 if ((*itr)->ToCreature())
{
                                     (*itr)->ToCreature()->AI()->DoAction(ACTION_INFECT_CITIZIEN);
                                     (*itr)->GetMotionMaster()->MoveFleeing(malganis, 2000);
                                 }
                             unitList.clear();
                         }
                         ScheduleNextEvent(currentEvent, 12000);
                         break;
                     case EVENT_ACTION_PHASE2+5:
                         if (Creature* malganis = GetEventNpc(NPC_MAL_GANIS))
                             malganis->AI()->Talk(SAY_PHASE207);
                         ScheduleNextEvent(currentEvent, 15000);
                         break;
                     case EVENT_ACTION_PHASE2+6:
                         if (Creature* malganis = GetEventNpc(NPC_MAL_GANIS))
{
                             me->SetTarget();
                             me->SetFacingToObject(malganis);
                             malganis->SetVisible(false);
                         }
                         Talk(SAY_PHASE208);
                         ScheduleNextEvent(currentEvent, 11000);
                         break;
                     case EVENT_ACTION_PHASE2+7:
                         summons.DespawnEntry(NPC_MAL_GANIS);
                         summons.DespawnEntry(NPC_CITY_MAN);
                         summons.DespawnEntry(NPC_CITY_MAN2);
                         Talk(SAY_PHASE209);
                         me->SetReactState(REACT_DEFENSIVE);
                         ScheduleNextEvent(currentEvent, 20000);
                         if (pInstance)
                             pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_FINISHED_CITY_INTRO);
                         break;
                     case EVENT_ACTION_PHASE2+8:
                         if (pInstance)
                             pInstance->SetData(DATA_START_WAVES, 1);
                         SummonNextWave();
                         break;
                     case EVENT_ACTION_PHASE2+9:
                         if (pInstance)
                             pInstance->DoUpdateWorldState(WORLDSTATE_WAVE_COUNT, 0);
                         Talk(SAY_PHASE210);
                         eventInRun = false;
                         SetEscortPaused(false);
                         break;
                     // After waypoint 22
                     case EVENT_ACTION_PHASE3:
                         me->SetReactState(REACT_AGGRESSIVE);
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN3))
                             cr->SetTarget(me->GetGUID());
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN4))
                             cr->SetTarget(me->GetGUID());
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN))
                             cr->SetTarget(me->GetGUID());
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE3+1:
                         me->SetReactState(REACT_AGGRESSIVE);
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN3))
                             cr->AI()->Talk(SAY_PHASE302);
                         ScheduleNextEvent(currentEvent, 7000);
                         break;
                     case EVENT_ACTION_PHASE3+2:
                         Talk(SAY_PHASE303);
                         SetEscortPaused(false);
                         eventInRun = false;
                         ScheduleNextEvent(currentEvent, 0);
                         break;
                     //After waypoint 23
                     case EVENT_ACTION_PHASE3+3:
                         SetRun(true);
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN3))
                             me->CastSpell(cr, SPELL_ARTHAS_CRUSADER_STRIKE, true);
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE3+4:
                         Talk(SAY_PHASE304);
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE3+5:
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN3))
                             cr->AI()->Talk(SAY_PHASE305);
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE3+6:
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN))
{
                             cr->UpdateEntry(NPC_INFINITE_HUNTER, nullptr, false);
                             cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->SetReactState(REACT_PASSIVE);
                         }
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE3+7:
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN4))
{
                             cr->UpdateEntry(NPC_INFINITE_AGENT, nullptr, false);
                             cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->SetReactState(REACT_PASSIVE);
                         }
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE3+8:
                         if (Creature* cr = GetEventNpc(NPC_CITY_MAN3))
{
                             cr->UpdateEntry(NPC_INFINITE_ADVERSARY, nullptr, false);
                             cr->SetReactState(REACT_AGGRESSIVE);
                             cr->SetInCombatWithZone();
                             cr->AddThreat(me, 0.0f);
                         }
                         if (Creature* cr = GetEventNpc(NPC_INFINITE_AGENT)) // it is infinite agent now :)
{
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->SetReactState(REACT_AGGRESSIVE);
                             cr->SetInCombatWithZone();
                             cr->AddThreat(me, 0.0f);
                         }
                         if (Creature* cr = GetEventNpc(NPC_INFINITE_HUNTER)) // it is infinite hunter now :)
{
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->SetReactState(REACT_AGGRESSIVE);
                             cr->SetInCombatWithZone();
                             cr->AddThreat(me, 0.0f);
                         }
                         ScheduleNextEvent(currentEvent, 2000);
                         break;
                     case EVENT_ACTION_PHASE3+9:
                         // Arthas is fighting infinites in town hall
                         if (me->IsInCombat())
{
                             actionEvents.RepeatEvent(1000);
                             return;
                         }
                         summons.DespawnAll();
                         me->Say("I can't afford to spare you.", LANG_UNIVERSAL);
                         me->SetFacingTo(0.0f);
                         ScheduleNextEvent(currentEvent, 5000);
                         break;
                     case EVENT_ACTION_PHASE3+10:
                         Talk(SAY_PHASE306);
                         ScheduleNextEvent(currentEvent, 5000);
                         break;
                     case EVENT_ACTION_PHASE3+11:
                         SetEscortPaused(false);
                         eventInRun = false;
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE3+12:
                         // Arthas is fighting first chronos
                         if (me->IsInCombat())
{
                             actionEvents.RepeatEvent(1000);
                             return;
                         }
                         eventInRun = false;
                         SetEscortPaused(false);
                         Talk(SAY_PHASE308);
                         me->SetFacingTo(M_PI);
                         ScheduleNextEvent(currentEvent, 0);
                         break;
                     case EVENT_ACTION_PHASE3+13:
                         // Arthas is fighting second chronos
                         if (me->IsInCombat())
{
                             actionEvents.RepeatEvent(1000);
                             return;
                         }
                         eventInRun = false;
                         SetEscortPaused(false);
                         Talk(SAY_PHASE311);
                         me->SetFacingTo(M_PI * 3 / 2);
                         ScheduleNextEvent(currentEvent, 0);
                         break;
                     case EVENT_ACTION_PHASE3+14:
                         // Arthas is fighting third chronos
                         if (me->IsInCombat())
{
                             actionEvents.RepeatEvent(1000);
                             return;
                         }
                         me->SetFacingTo(M_PI / 2);
                         ScheduleNextEvent(currentEvent, 8000);
                         break;
                     case EVENT_ACTION_PHASE3+15:
                         Talk(SAY_PHASE313);
                         me->SummonCreature(NPC_TIME_RIFT, EventPos[EVENT_SRC_EPOCH], TEMPSUMMON_TIMED_DESPAWN, 20000);
                         if (Creature* cr = me->SummonCreature(NPC_EPOCH, EventPos[EVENT_SRC_EPOCH]))
{
                             cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             me->SetTarget(cr->GetGUID());
                             cr->GetMotionMaster()->MovePoint(0, EventPos[EVENT_DST_EPOCH]);
                         }
                         ScheduleNextEvent(currentEvent, 3000);
                         break;
                     case EVENT_ACTION_PHASE3+16:
                         if (Creature* cr = GetEventNpc(NPC_EPOCH))
                             cr->AI()->Talk(SAY_PHASE314);
                         ScheduleNextEvent(currentEvent, 14000);
                         break;
                     case EVENT_ACTION_PHASE3+17:
                         Talk(SAY_PHASE315);
                         ScheduleNextEvent(currentEvent, 7000);
                         break;
                     case EVENT_ACTION_PHASE3+18:
                         if (Creature* cr = GetEventNpc(NPC_EPOCH))
{
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             cr->SetReactState(REACT_AGGRESSIVE);
                             cr->AddThreat(me, 0.0f);
                             cr->SetInCombatWithZone();
                         }
                         ScheduleNextEvent(currentEvent, 1000);
                         break;
                     case EVENT_ACTION_PHASE3+19:
                         // Arthas is fighting epoch chronos
                         if (me->IsInCombat())
{
                             actionEvents.RepeatEvent(1000);
                             return;
                         }
                         if (pInstance)
                             pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_KILLED_EPOCH);
                         me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                         eventInRun = false;
                         break;
                     case EVENT_ACTION_PHASE5:
                         if (Creature* cr = GetEventNpc(NPC_MAL_GANIS))
{
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                             cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             cr->SetInCombatWithZone();
                             cr->AddThreat(me, 0.0f);
                             AttackStart(cr);
                         }
                         eventInRun = false;
                         SetEscortPaused(true);
                         break;
                     case EVENT_ACTION_PHASE5+1:
                         Talk(SAY_PHASE503);
                         SetEscortPaused(false);
                         eventInRun = false;
                         ScheduleNextEvent(currentEvent, 5000);
                         break;
                     case EVENT_ACTION_PHASE5+2:
                         me->SetFacingTo(5.28f);
                         Talk(SAY_PHASE504);
                         if (pInstance)
{
                             pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_FINISHED);
                             if (GameObject* go = pInstance->instance->GetGameObject(pInstance->GetGuidData(DATA_EXIT_GATE)))
                                 go->SetGoState(GO_STATE_ACTIVE);
                             if (!me->GetMap()->GetPlayers().isEmpty())
                                 if (Player* player = me->GetMap()->GetPlayers().getFirst()->GetSource())
                                     player->SummonGameObject(DUNGEON_MODE(GO_MALGANIS_CHEST_N, GO_MALGANIS_CHEST_H), 2288.35f, 1498.73f, 128.414f, -0.994837f, 0, 0, 0, 0, 0);
                         }
                         ScheduleNextEvent(currentEvent, 10000);
                         break;
                     case EVENT_ACTION_PHASE5+3:
                         eventInRun = false;
                         me->SetVisible(false);
                         break;
                 }
             }
             //Battling skills
             if (!me->GetVictim())
                 return;
             combatEvents.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (combatEvents.ExecuteEvent())
             {
                 case EVENT_COMBAT_EXORCISM:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, DUNGEON_MODE(SPELL_ARTHAS_EXORCISM_N, SPELL_ARTHAS_EXORCISM_H), false);
                     combatEvents.RepeatEvent(7300);
                     break;
                 case EVENT_COMBAT_HEALTH_CHECK:
                     if (HealthBelowPct(40))
                         me->CastSpell(me, SPELL_ARTHAS_HOLY_LIGHT, false);
                     combatEvents.RepeatEvent(1000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_INFECT_CITIZIEN, actionEvents, npc_escortAI::AttackStart(), SummonList::begin(), Unit::CastSpell(), combatEvents, COS_PROGRESS_FINISHED, COS_PROGRESS_FINISHED_CITY_INTRO, COS_PROGRESS_KILLED_EPOCH, DATA_ARTHAS_EVENT, DATA_EXIT_GATE, DATA_START_WAVES, SummonList::DespawnAll(), SummonList::DespawnEntry(), UnitAI::DoMeleeAttackIfReady(), InstanceScript::DoUpdateWorldState(), ScriptedAI::DUNGEON_MODE(), SummonList::end(), EVENT_ACTION_PHASE1, EVENT_ACTION_PHASE2, EVENT_ACTION_PHASE3, EVENT_ACTION_PHASE5, EVENT_COMBAT_EXORCISM, EVENT_COMBAT_HEALTH_CHECK, EVENT_DST_CITYMAN, EVENT_DST_EPOCH, EVENT_DST_HORSE1, EVENT_DST_UTHER, EVENT_POS_RETREAT, EVENT_SRC_EPOCH, EVENT_SRC_HORSE1, EVENT_SRC_JAINA, EVENT_SRC_MALGANIS, EVENT_SRC_UTHER, eventInRun, EventPos, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Object::GetEntry(), GetEventNpc(), MapRefMgr::getFirst(), Map::GetGameObject(), Object::GetGUID(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Reference< TO, FROM >::GetSource(), Unit::GetVictim(), GO_MALGANIS_CHEST_H, GO_MALGANIS_CHEST_N, GO_STATE_ACTIVE, Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), InstanceScript::instance, LinkedListHead::isEmpty(), Unit::IsInCombat(), LANG_UNIVERSAL, ScriptedAI::me, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), NPC_CITY_MAN, NPC_CITY_MAN2, NPC_CITY_MAN3, NPC_CITY_MAN4, NPC_EPOCH, NPC_HORSE_ESCORT, NPC_INFINITE_ADVERSARY, NPC_INFINITE_AGENT, NPC_INFINITE_HUNTER, NPC_INVIS_TARGET, NPC_JAINA, NPC_MAL_GANIS, NPC_TIME_RIFT, NPC_UTHER, pInstance, REACT_AGGRESSIVE, REACT_DEFENSIVE, REACT_PASSIVE, EventMap::RepeatEvent(), Unit::Say(), SAY_PHASE101, SAY_PHASE102, SAY_PHASE103, SAY_PHASE104, SAY_PHASE105, SAY_PHASE106, SAY_PHASE107, SAY_PHASE108, SAY_PHASE109, SAY_PHASE110, SAY_PHASE111, SAY_PHASE112, SAY_PHASE113, SAY_PHASE114, SAY_PHASE115, SAY_PHASE116, SAY_PHASE117, SAY_PHASE202, SAY_PHASE203, SAY_PHASE205, SAY_PHASE206, SAY_PHASE207, SAY_PHASE208, SAY_PHASE209, SAY_PHASE210, SAY_PHASE302, SAY_PHASE303, SAY_PHASE304, SAY_PHASE305, SAY_PHASE306, SAY_PHASE308, SAY_PHASE311, SAY_PHASE313, SAY_PHASE314, SAY_PHASE315, SAY_PHASE503, SAY_PHASE504, ScheduleNextEvent(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ZoneScript::SetData(), npc_escortAI::SetDespawnAtEnd(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Object::SetFlag(), Creature::SetReactState(), npc_escortAI::SetRun(), Creature::SetTarget(), Unit::SetVisible(), SPELL_ARTHAS_CRUSADER_STRIKE, SPELL_ARTHAS_EXORCISM_H, SPELL_ARTHAS_EXORCISM_N, SPELL_ARTHAS_HOLY_LIGHT, SPELL_MALGANIS_APPEAR, npc_escortAI::Start(), WorldObject::SummonCreature(), SummonNextWave(), summons, CreatureAI::Talk(), TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, UNIT_STATE_CASTING, EventMap::Update(), npc_escortAI::UpdateAI(), and WORLDSTATE_WAVE_COUNT.
WaypointReached()
void npc_arthas::npc_arthasAI::WaypointReached (uint32 uiPointId) inline override virtual
Implements npc_escortAI.
Definition at line 523 of file culling_of_stratholme.cpp.
         {
             switch(uiPointId)
             {
                 // Starting waypoint, After reaching uther and jaina
                 case 0:
                 // On the mountain with uther and jaina
                 case 1:
                 // Reaching city man in city
                 case 9:
                 // Reaching city man in town hall
                 case 23:
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
                 // After intro, in front of bridge
                 case 3:
                     SetRun(true);
                     Talk(SAY_PHASE118);
                     summons.DespawnAll(); // uther, jaina and horses
                     break;
                 // Reached City
                 case 8:
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     SetEscortPaused(true);
                     if (pInstance)
                         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_FINISHED_INTRO);
                     if (Creature* stalker = me->SummonCreature(NPC_INVIS_TARGET, 2026.469f, 1287.088f, 143.596f, 1.37f, TEMPSUMMON_TIMED_DESPAWN, 14000))
                     {
                         me->SetFacingToObject(stalker);
                         stalker->DespawnOrUnsummon(500);
                     }
                     break;
                 // Reached first cityman
                 case 10:
                     if (Creature* cityman = GetEventNpc(NPC_CITY_MAN))
                     {
                         cityman->AI()->Talk(SAY_PHASE204);
                         me->CastSpell(cityman, SPELL_ARTHAS_CRUSADER_STRIKE, true);
                     }
                     break;
                 // Reached second cityman
                 case 11:
                     if (Creature* cityman = GetEventNpc(NPC_CITY_MAN2))
                     {
                         cityman->Say("Oh no...", LANG_UNIVERSAL); // missing script_text
                         me->CastSpell(cityman, SPELL_ARTHAS_CRUSADER_STRIKE, true);
                     }
                     me->SetReactState(REACT_DEFENSIVE);
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
                 // Reached Town Hall
                 case 20:
                     if (pInstance)
                         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_REACHED_TOWN_HALL);
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     SetRun(false);
                     SetEscortPaused(true);
                     break;
                 // Inside Town Hall first scene pos
                 case 22:
                     actionEvents.ScheduleEvent(EVENT_ACTION_PHASE3, 0);
                     eventInRun = true;
                     SetEscortPaused(true);
                     break;
                 // Town Hall, upper floor first fight
                 case 26:
                     SetEscortPaused(true);
                     eventInRun = true;
                     SpawnTimeRift();
                     Talk(SAY_PHASE307);
                     break;
                 // Town Hall, upper floor second fight
                 case 29:
                     SpawnTimeRift();
                     SpawnTimeRift();
                     Talk(SAY_PHASE309);
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
                 // Town Hall, upper floor third fight
                 case 31:
                     SetRun(false);
                     SpawnTimeRift();
                     SpawnTimeRift();
                     Talk(SAY_PHASE312);
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
                 // Book Shelf
                 case 34:
                     Talk(SAY_PHASE402);
                     break;
                 case 35:
                     Talk(SAY_PHASE403);
                     break;
                 // Reached book shelf
                 case 36:
                     SetRun(true);
                     if (pInstance)
                         if (GameObject* pGate = pInstance->instance->GetGameObject(pInstance->GetGuidData(DATA_SHKAF_GATE)))
                             pGate->SetGoState(GO_STATE_ACTIVE);
                     break;
                 // Behind secred passage
                 case 45:
                     SetRun(true);
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     SetEscortPaused(true);
                     if (pInstance)
                         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_LAST_CITY);
                     break;
                 // Some walk talk
                 case 47:
                     SetRun(false);
                     Talk(SAY_PHASE405);
                     break;
                 case 48:
                     SetRun(true);
                     Talk(SAY_PHASE406);
                     break;
                 case 53:
                     Talk(SAY_PHASE407);
                     break;
                 // Before Malganis event
                 case 54:
                     if (pInstance)
                         pInstance->SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_BEFORE_MALGANIS);
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     SetEscortPaused(true);
                     break;
                 // Infront of malganis
                 case 55:
                     Talk(SAY_PHASE502);
                     actionEvents.ScheduleEvent(EVENT_ACTION_PHASE5, 7000);
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
                 // After malganis defeat
                 case 56:
                     SetEscortPaused(true);
                     eventInRun = true;
                     break;
             }
         }
References actionEvents, Unit::CastSpell(), COS_PROGRESS_BEFORE_MALGANIS, COS_PROGRESS_FINISHED_INTRO, COS_PROGRESS_LAST_CITY, COS_PROGRESS_REACHED_TOWN_HALL, DATA_ARTHAS_EVENT, DATA_SHKAF_GATE, SummonList::DespawnAll(), EVENT_ACTION_PHASE3, EVENT_ACTION_PHASE5, eventInRun, GetEventNpc(), Map::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_ACTIVE, InstanceScript::instance, LANG_UNIVERSAL, ScriptedAI::me, NPC_CITY_MAN, NPC_CITY_MAN2, NPC_INVIS_TARGET, pInstance, REACT_DEFENSIVE, SAY_PHASE118, SAY_PHASE204, SAY_PHASE307, SAY_PHASE309, SAY_PHASE312, SAY_PHASE402, SAY_PHASE403, SAY_PHASE405, SAY_PHASE406, SAY_PHASE407, SAY_PHASE502, EventMap::ScheduleEvent(), ZoneScript::SetData(), npc_escortAI::SetEscortPaused(), Unit::SetFacingToObject(), Object::SetFlag(), Creature::SetReactState(), npc_escortAI::SetRun(), SpawnTimeRift(), SPELL_ARTHAS_CRUSADER_STRIKE, WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Member Data Documentation
actionEvents
EventMap npc_arthas::npc_arthasAI::actionEvents
Definition at line 385 of file culling_of_stratholme.cpp.
Referenced by DoAction(), Reset(), UpdateAI(), and WaypointReached().
combatEvents
EventMap npc_arthas::npc_arthasAI::combatEvents
Definition at line 386 of file culling_of_stratholme.cpp.
Referenced by Reset(), and UpdateAI().
eventInRun
bool npc_arthas::npc_arthasAI::eventInRun
Definition at line 384 of file culling_of_stratholme.cpp.
Referenced by DoAction(), Reset(), UpdateAI(), and WaypointReached().
pInstance
InstanceScript* npc_arthas::npc_arthasAI::pInstance
Definition at line 382 of file culling_of_stratholme.cpp.
Referenced by JustDied(), npc_arthasAI(), Reset(), SummonedCreatureDies(), UpdateAI(), and WaypointReached().
summons
SummonList npc_arthas::npc_arthasAI::summons
Definition at line 383 of file culling_of_stratholme.cpp.
Referenced by DoAction(), GetEventNpc(), JustSummoned(), Reset(), SummonedCreatureDespawn(), UpdateAI(), and WaypointReached().
timeRiftId
uint8 npc_arthas::npc_arthasAI::timeRiftId
Definition at line 389 of file culling_of_stratholme.cpp.
Referenced by Reset().
waveGroupId
uint8 npc_arthas::npc_arthasAI::waveGroupId
Definition at line 387 of file culling_of_stratholme.cpp.
Referenced by DoAction(), and Reset().
waveKillCount
uint8 npc_arthas::npc_arthasAI::waveKillCount
Definition at line 388 of file culling_of_stratholme.cpp.
Referenced by Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp