Azerotcore-wotlk: npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI Struct Reference
npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI Struct Reference
Public Member Functions
npc_blood_queen_lana_thelAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
bool _introDone
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1072 of file boss_blood_prince_council.cpp.
Constructor & Destructor Documentation
npc_blood_queen_lana_thelAI()
npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::npc_blood_queen_lana_thelAI (Creature * creature) inline
Definition at line 1074 of file boss_blood_prince_council.cpp.
                                                         : ScriptedAI(creature)
         {
             _introDone = false;
             _instance = creature->GetInstanceScript();
             me->m_SightDistance = 100.0f; // for MoveInLineOfSight distance
         }
References _instance, _introDone, WorldObject::GetInstanceScript(), Creature::m_SightDistance, and ScriptedAI::me.
Member Function Documentation
MoveInLineOfSight()
void npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1096 of file boss_blood_prince_council.cpp.
         {
             if (_introDone)
                 return;
             if (who->GetTypeId() != TYPEID_PLAYER || me->GetExactDist2d(who) > 100.0f)
             {
                 return;
             }
             _introDone = true;
             Talk(SAY_INTRO_1);
             _events.SetPhase(1);
             _events.ScheduleEvent(EVENT_INTRO_1, 14000);
             // summon a visual trigger
             if (Creature* summon = DoSummon(NPC_FLOATING_TRIGGER, triggerPos, 15000, TEMPSUMMON_TIMED_DESPAWN))
             {
                 summon->SetDisplayId(11686); // it's a general npc, and the template has 2 models (first is an infernal)
                 summon->CastSpell(summon, SPELL_OOC_INVOCATION_VISUAL, true);
                 summon->SetSpeed(MOVE_RUN, 0.15f, true);
                 summon->GetMotionMaster()->MovePoint(0, triggerEndPos);
             }
         }
References _events, _introDone, CreatureAI::DoSummon(), EVENT_INTRO_1, Position::GetExactDist2d(), Object::GetTypeId(), ScriptedAI::me, MOVE_RUN, NPC_FLOATING_TRIGGER, SAY_INTRO_1, EventMap::ScheduleEvent(), EventMap::SetPhase(), SPELL_OOC_INVOCATION_VISUAL, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, triggerEndPos, triggerPos, and TYPEID_PLAYER.
MovementInform()
void npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1120 of file boss_blood_prince_council.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_INTRO_DESPAWN)
             {
                 me->SetVisible(false);
             }
         }
References ScriptedAI::me, POINT_INTRO_DESPAWN, POINT_MOTION_TYPE, and Unit::SetVisible().
Reset()
void npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1081 of file boss_blood_prince_council.cpp.
         {
             _events.Reset();
             me->SetDisableGravity(true);
             if (_instance->GetBossState(DATA_BLOOD_PRINCE_COUNCIL) == DONE)
             {
                 me->SetVisible(false);
                 _introDone = true;
             }
             else
             {
                 me->SetVisible(true);
             }
         }
References _events, _instance, _introDone, DATA_BLOOD_PRINCE_COUNCIL, DONE, InstanceScript::GetBossState(), ScriptedAI::me, EventMap::Reset(), Creature::SetDisableGravity(), and Unit::SetVisible().
UpdateAI()
void npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1128 of file boss_blood_prince_council.cpp.
         {
             if (!_events.GetPhaseMask())
             {
                 return;
             }
             _events.Update(diff);
             if (_events.ExecuteEvent() == EVENT_INTRO_1)
             {
                 Talk(SAY_INTRO_2);
                 me->GetMotionMaster()->MovePoint(POINT_INTRO_DESPAWN, introFinalPos);
                 _events.Reset();
                 if (Creature* keleseth = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_PRINCE_KELESETH_GUID)))
                 {
                     keleseth->AI()->DoAction(ACTION_STAND_UP);
                 }
                 if (Creature* taldaram = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_PRINCE_TALDARAM_GUID)))
                 {
                     taldaram->AI()->DoAction(ACTION_STAND_UP);
                 }
                 if (Creature* valanar = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_PRINCE_VALANAR_GUID)))
                 {
                     valanar->AI()->DoAction(ACTION_STAND_UP);
                 }
             }
         }
References _events, _instance, ACTION_STAND_UP, DATA_PRINCE_KELESETH_GUID, DATA_PRINCE_TALDARAM_GUID, DATA_PRINCE_VALANAR_GUID, EVENT_INTRO_1, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), EventMap::GetPhaseMask(), introFinalPos, ScriptedAI::me, MotionMaster::MovePoint(), POINT_INTRO_DESPAWN, EventMap::Reset(), SAY_INTRO_2, CreatureAI::Talk(), and EventMap::Update().
Member Data Documentation
_events
EventMap npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::_events private
Definition at line 1159 of file boss_blood_prince_council.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateAI().
_instance
InstanceScript* npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::_instance private
Definition at line 1160 of file boss_blood_prince_council.cpp.
Referenced by npc_blood_queen_lana_thelAI(), Reset(), and UpdateAI().
_introDone
bool npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::_introDone private
Definition at line 1161 of file boss_blood_prince_council.cpp.
Referenced by MoveInLineOfSight(), npc_blood_queen_lana_thelAI(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp