Azerotcore-wotlk: Acore::VisibleNotifier Struct Reference
Acore::VisibleNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
VisibleNotifier (Player &player, bool gobjOnly, bool largeOnly)
void Visit (GameObjectMapType &)
template<class T >
void Visit (GridRefMgr< T > &m)
void SendToSelf (void)
Public Attributes
Player & i_player
GuidUnorderedSet vis_guids
std::vector< Unit * > & i_visibleNow
bool i_gobjOnly
bool i_largeOnly
UpdateData i_data
Detailed Description
Definition at line 41 of file GridNotifiers.h.
Constructor & Destructor Documentation
VisibleNotifier()
Acore::VisibleNotifier::VisibleNotifier (Player & player, bool gobjOnly, bool largeOnly) inline
Definition at line 50 of file GridNotifiers.h.
                                                                        :
             i_player(player), vis_guids(player.m_clientGUIDs), i_visibleNow(player.m_newVisible), i_gobjOnly(gobjOnly), i_largeOnly(largeOnly)
         {
             i_visibleNow.clear();
         }
References i_visibleNow.
Member Function Documentation
SendToSelf()
void VisibleNotifier::SendToSelf (void)
Definition at line 42 of file GridNotifiers.cpp.
 {
     // at this moment i_clientGUIDs have guids that not iterate at grid level checks
     // but exist one case when this possible and object not out of range: transports
     if (Transport* transport = i_player.GetTransport())
         for (Transport::PassengerSet::const_iterator itr = transport->GetPassengers().begin(); itr != transport->GetPassengers().end(); ++itr)
         {
             if (i_largeOnly != (*itr)->IsVisibilityOverridden())
                 continue;
             if (vis_guids.find((*itr)->GetGUID()) != vis_guids.end())
             {
                 vis_guids.erase((*itr)->GetGUID());
                 switch ((*itr)->GetTypeId())
                 {
                     case TYPEID_GAMEOBJECT:
                         i_player.UpdateVisibilityOf((*itr)->ToGameObject(), i_data, i_visibleNow);
                         break;
                     case TYPEID_PLAYER:
                         i_player.UpdateVisibilityOf((*itr)->ToPlayer(), i_data, i_visibleNow);
                         (*itr)->ToPlayer()->UpdateVisibilityOf(&i_player);
                         break;
                     case TYPEID_UNIT:
                         i_player.UpdateVisibilityOf((*itr)->ToCreature(), i_data, i_visibleNow);
                         break;
                     default:
                         break;
                 }
             }
         }
     for (GuidUnorderedSet::const_iterator it = vis_guids.begin(); it != vis_guids.end(); ++it)
     {
         if (WorldObject* obj = ObjectAccessor::GetWorldObject(i_player, *it))
         {
             if (i_largeOnly != obj->IsVisibilityOverridden())
                 continue;
         }
         // pussywizard: static transports are removed only in RemovePlayerFromMap and here if can no longer detect (eg. phase changed)
         if ((*it).IsTransport())
             if (GameObject* staticTrans = i_player.GetMap()->GetGameObject(*it))
                 if (i_player.CanSeeOrDetect(staticTrans, false, true))
                     continue;
         i_player.m_clientGUIDs.erase(*it);
         i_data.AddOutOfRangeGUID(*it);
         if ((*it).IsPlayer())
         {
             Player* player = ObjectAccessor::FindPlayer(*it);
             if (player && player->IsInMap(&i_player))
                 player->UpdateVisibilityOf(&i_player);
         }
     }
     if (!i_data.HasData())
         return;
     WorldPacket packet;
     i_data.BuildPacket(&packet);
     i_player.GetSession()->SendPacket(&packet);
     for (std::vector<Unit*>::const_iterator it = i_visibleNow.begin(); it != i_visibleNow.end(); ++it)
     {
         if (i_largeOnly != (*it)->IsVisibilityOverridden())
             continue;
         i_player.GetInitialVisiblePackets(*it);
     }
 }
References UpdateData::AddOutOfRangeGUID(), UpdateData::BuildPacket(), WorldObject::CanSeeOrDetect(), ObjectAccessor::FindPlayer(), Map::GetGameObject(), Player::GetInitialVisiblePackets(), WorldObject::GetMap(), Player::GetSession(), WorldObject::GetTransport(), ObjectAccessor::GetWorldObject(), UpdateData::HasData(), i_data, i_largeOnly, i_player, i_visibleNow, WorldObject::IsInMap(), Player::m_clientGUIDs, WorldSession::SendPacket(), TYPEID_GAMEOBJECT, TYPEID_PLAYER, TYPEID_UNIT, Player::UpdateVisibilityOf(), and vis_guids.
Referenced by Unit::ExecuteDelayedUnitRelocationEvent(), and Player::UpdateVisibilityForPlayer().
Visit() [1/2]
void VisibleNotifier::Visit (GameObjectMapType & m)
Definition at line 29 of file GridNotifiers.cpp.
 {
     for (GameObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         GameObject* go = iter->GetSource();
         if (i_largeOnly != go->IsVisibilityOverridden())
             continue;
         vis_guids.erase(go->GetGUID());
         i_player.UpdateVisibilityOf(go, i_data, i_visibleNow);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Object::GetGUID(), i_data, i_largeOnly, i_player, i_visibleNow, WorldObject::IsVisibilityOverridden(), Player::UpdateVisibilityOf(), and vis_guids.
Referenced by Acore::PlayerRelocationNotifier::Visit().
Visit() [2/2]
template<class T > void Acore::VisibleNotifier::Visit (GridRefMgr< T > & m) inline
Definition at line 31 of file GridNotifiersImpl.h.
 {
     // Xinef: Update gameobjects only
     if (i_gobjOnly)
         return;
     for (typename GridRefMgr<T>::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         if (i_largeOnly != iter->GetSource()->IsVisibilityOverridden())
             continue;
         vis_guids.erase(iter->GetSource()->GetGUID());
         i_player.UpdateVisibilityOf(iter->GetSource(), i_data, i_visibleNow);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), i_data, i_gobjOnly, i_largeOnly, i_player, i_visibleNow, Player::UpdateVisibilityOf(), and vis_guids.
Member Data Documentation
i_data
UpdateData Acore::VisibleNotifier::i_data
Definition at line 48 of file GridNotifiers.h.
Referenced by SendToSelf(), Visit(), and Acore::PlayerRelocationNotifier::Visit().
i_gobjOnly
bool Acore::VisibleNotifier::i_gobjOnly
Definition at line 46 of file GridNotifiers.h.
Referenced by Visit().
i_largeOnly
bool Acore::VisibleNotifier::i_largeOnly
Definition at line 47 of file GridNotifiers.h.
Referenced by SendToSelf(), and Visit().
i_player
Player& Acore::VisibleNotifier::i_player
Definition at line 43 of file GridNotifiers.h.
Referenced by SendToSelf(), Visit(), and Acore::PlayerRelocationNotifier::Visit().
i_visibleNow
std::vector<Unit*>& Acore::VisibleNotifier::i_visibleNow
Definition at line 45 of file GridNotifiers.h.
Referenced by SendToSelf(), VisibleNotifier(), Visit(), and Acore::PlayerRelocationNotifier::Visit().
vis_guids
GuidUnorderedSet Acore::VisibleNotifier::vis_guids
Definition at line 44 of file GridNotifiers.h.
Referenced by SendToSelf(), Visit(), and Acore::PlayerRelocationNotifier::Visit().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp
src/server/game/Grids/Notifiers/GridNotifiersImpl.h