Azerotcore-wotlk: World Class Reference
World Class Reference
The World
The World.
#include <World.h>
Public Types
typedef std::list< WorldSession * > Queue
Public Member Functions
World ()
World constructor.
~World ()
World destructor.
WorldSession * FindSession (uint32 id) const
Find a session by its id.
WorldSession * FindOfflineSession (uint32 id) const
WorldSession * FindOfflineSessionForCharacterGUID (ObjectGuid::LowType guidLow) const
void AddSession (WorldSession *s)
void SendAutoBroadcast ()
bool KickSession (uint32 id)
Remove a given session.
void UpdateMaxSessionCounters ()
Get the number of current active sessions.
const SessionMap & GetAllSessions () const
uint32 GetActiveAndQueuedSessionCount () const
uint32 GetActiveSessionCount () const
uint32 GetQueuedSessionCount () const
uint32 GetMaxQueuedSessionCount () const
Get the maximum number of parallel sessions on the server since last reboot.
uint32 GetMaxActiveSessionCount () const
uint32 GetPlayerCount () const
Get number of players.
uint32 GetMaxPlayerCount () const
void IncreasePlayerCount ()
Increase/Decrease number of players.
void DecreasePlayerCount ()
Player * FindPlayerInZone (uint32 zone)
Find a player in a specified zone.
bool IsClosed () const
Deny clients?
void SetClosed (bool val)
Close world.
AccountTypes GetPlayerSecurityLimit () const
Security level limitations.
void SetPlayerSecurityLimit (AccountTypes sec)
void LoadDBAllowedSecurityLevel ()
void SetPlayerAmountLimit (uint32 limit)
Active session server limit.
uint32 GetPlayerAmountLimit () const
void AddQueuedPlayer (WorldSession *)
bool RemoveQueuedPlayer (WorldSession *session)
int32 GetQueuePos (WorldSession *)
bool HasRecentlyDisconnected (WorldSession *)
bool getAllowMovement () const
void SetAllowMovement (bool allow)
Allow/Disallow object movements.
void SetNewCharString (std::string const &str)
Set the string for new characters (first login)
std::string const & GetNewCharString () const
Get the string for new characters (first login)
LocaleConstant GetDefaultDbcLocale () const
std::string const & GetDataPath () const
Get the path where data (dbc, maps) are stored on disk.
time_t const & GetStartTime () const
When server started?
time_t const & GetGameTime () const
What time is it?
uint32 GetUptime () const
Uptime (in secs)
uint32 GetUpdateTime () const
Update time.
void SetRecordDiffInterval (int32 t)
time_t GetNextDailyQuestsResetTime () const
Next daily quests and random bg reset time.
time_t GetNextWeeklyQuestsResetTime () const
time_t GetNextRandomBGResetTime () const
uint16 GetConfigMaxSkillValue () const
Get the maximum skill level a player can reach.
void SetInitialWorldSettings ()
Initialize the World.
void LoadConfigSettings (bool reload=false)
Initialize config values.
void SendWorldText (uint32 string_id,...)
Send a System Message to all players (except self if mentioned)
void SendGlobalText (const char *text, WorldSession *self)
DEPRECATED, only for debug purpose. Send a System Message to all players (except self if mentioned)
void SendGMText (uint32 string_id,...)
Send a System Message to all GMs (except self if mentioned)
void SendGlobalMessage (WorldPacket *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all players (except self if mentioned)
void SendGlobalGMMessage (WorldPacket *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all GMs (except self if mentioned)
bool SendZoneMessage (uint32 zone, WorldPacket *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all players (or players selected team) in the zone (except self if mentioned)
void SendZoneText (uint32 zone, const char *text, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a System Message to all players in the zone (except self if mentioned)
void SendServerMessage (ServerMessageType type, const char *text="", Player *player=nullptr)
Send a server message to the user(s)
bool IsShuttingDown () const
Are we in the middle of a shutdown?
uint32 GetShutDownTimeLeft () const
void ShutdownServ (uint32 time, uint32 options, uint8 exitcode)
Shutdown the server.
void ShutdownCancel ()
Cancel a planned server shutdown.
void ShutdownMsg (bool show=false, Player *player=nullptr)
Display a shutdown message to the user(s)
void Update (uint32 diff)
Update the World !
void UpdateSessions (uint32 diff)
void setRate (Rates rate, float value)
Set a server rate (see Rates)
float getRate (Rates rate) const
Get a server rate (see Rates)
void setBoolConfig (WorldBoolConfigs index, bool value)
Set a server configuration element (see #WorldConfigs)
bool getBoolConfig (WorldBoolConfigs index) const
Get a server configuration element (see #WorldConfigs)
void setFloatConfig (WorldFloatConfigs index, float value)
Set a server configuration element (see #WorldConfigs)
float getFloatConfig (WorldFloatConfigs index) const
Get a server configuration element (see #WorldConfigs)
void setIntConfig (WorldIntConfigs index, uint32 value)
Set a server configuration element (see #WorldConfigs)
uint32 getIntConfig (WorldIntConfigs index) const
Get a server configuration element (see #WorldConfigs)
void setWorldState (uint32 index, uint64 value)
uint64 getWorldState (uint32 index) const
void LoadWorldStates ()
bool IsPvPRealm () const
Are we on a "Player versus Player" server?
bool IsFFAPvPRealm () const
void KickAll ()
Kick (and save) all players.
void KickAllLess (AccountTypes sec)
Kick (and save) all players with security level less sec
uint32 GetNextWhoListUpdateDelaySecs ()
void LoadGlobalPlayerDataStore ()
ObjectGuid GetGlobalPlayerGUID (std::string const &name) const
GlobalPlayerData const * GetGlobalPlayerData (ObjectGuid::LowType guid) const
void AddGlobalPlayerData (ObjectGuid::LowType guid, uint32 accountId, std::string const &name, uint8 gender, uint8 race, uint8 playerClass, uint8 level, uint16 mailCount, uint32 guildId)
void UpdateGlobalPlayerData (ObjectGuid::LowType guid, uint8 mask, std::string const &name, uint8 level=0, uint8 gender=0, uint8 race=0, uint8 playerClass=0)
void UpdateGlobalPlayerMails (ObjectGuid::LowType guid, int16 count, bool add=true)
void UpdateGlobalPlayerGuild (ObjectGuid::LowType guid, uint32 guildId)
void UpdateGlobalPlayerGroup (ObjectGuid::LowType guid, uint32 groupId)
void UpdateGlobalPlayerArenaTeam (ObjectGuid::LowType guid, uint8 slot, uint32 arenaTeamId)
void UpdateGlobalNameData (ObjectGuid::LowType guidLow, std::string const &oldName, std::string const &newName)
void DeleteGlobalPlayerData (ObjectGuid::LowType guid, std::string const &name)
void ProcessCliCommands ()
void QueueCliCommand (CliCommandHolder *commandHolder)
void ForceGameEventUpdate ()
void UpdateRealmCharCount (uint32 accid)
LocaleConstant GetAvailableDbcLocale (LocaleConstant locale) const
void LoadDBVersion ()
void LoadDBRevision ()
char const * GetDBVersion () const
char const * GetWorldDBRevision () const
char const * GetCharacterDBRevision () const
char const * GetAuthDBRevision () const
void LoadAutobroadcasts ()
void UpdateAreaDependentAuras ()
uint32 GetCleaningFlags () const
void SetCleaningFlags (uint32 flags)
void ResetEventSeasonalQuests (uint16 event_id)
time_t GetNextTimeWithDayAndHour (int8 dayOfWeek, int8 hour)
time_t GetNextTimeWithMonthAndHour (int8 month, int8 hour)
std::string const & GetRealmName () const
void SetRealmName (std::string name)
void RemoveOldCorpses ()
Public Member Functions inherited from IWorld
virtual ~IWorld ()
Static Public Member Functions
static World * instance ()
static uint32 GetGameTimeMS ()
What time is it? in ms.
static uint8 GetExitCode ()
static void StopNow (uint8 exitcode)
static bool IsStopped ()
static float GetMaxVisibleDistanceOnContinents ()
static float GetMaxVisibleDistanceInInstances ()
static float GetMaxVisibleDistanceInBGArenas ()
Static Public Attributes
static uint32 m_worldLoopCounter = 0
Protected Member Functions
void _UpdateGameTime ()
Update the game time.
void _UpdateRealmCharCount (PreparedQueryResult resultCharCount)
void InitDailyQuestResetTime ()
void InitWeeklyQuestResetTime ()
void InitMonthlyQuestResetTime ()
void InitRandomBGResetTime ()
void InitCalendarOldEventsDeletionTime ()
void InitGuildResetTime ()
void ResetDailyQuests ()
void ResetWeeklyQuests ()
void ResetMonthlyQuests ()
void ResetRandomBG ()
void CalendarDeleteOldEvents ()
void ResetGuildCap ()
Private Types
typedef std::unordered_map< uint32, time_t > DisconnectMap
typedef std::map< uint32, uint64 > WorldStatesMap
typedef std::map< uint8, std::string > AutobroadcastsMap
typedef std::map< uint8, uint8 > AutobroadcastsWeightMap
Private Member Functions
void DetectDBCLang ()
void AddSession_ (WorldSession *s)
void ProcessQueryCallbacks ()
void FinalizePlayerWorldSession (WorldSession *session)
Executed when a World Session is being finalized. Be it from a normal login or via queue popping.
Private Attributes
uint32 m_ShutdownTimer
uint32 m_ShutdownMask
uint32 m_CleaningFlags
bool m_isClosed
time_t m_startTime
time_t m_gameTime
IntervalTimer m_timers [WUPDATE_COUNT]
time_t mail_expire_check_timer
uint32 m_updateTime
uint32 m_updateTimeSum
SessionMap m_sessions
SessionMap m_offlineSessions
DisconnectMap m_disconnects
uint32 m_maxActiveSessionCount
uint32 m_maxQueuedSessionCount
uint32 m_PlayerCount
uint32 m_MaxPlayerCount
std::string m_newCharString
float rate_values [MAX_RATES]
uint32 m_int_configs [INT_CONFIG_VALUE_COUNT]
bool m_bool_configs [BOOL_CONFIG_VALUE_COUNT]
float m_float_configs [FLOAT_CONFIG_VALUE_COUNT]
WorldStatesMap m_worldstates
uint32 m_playerLimit
AccountTypes m_allowedSecurityLevel
LocaleConstant m_defaultDbcLocale
uint32 m_availableDbcLocaleMask
bool m_allowMovement
std::string m_dataPath
GlobalPlayerDataMap _globalPlayerDataStore
GlobalPlayerNameMap _globalPlayerNameStore
std::string _realmName
LockedQueue< CliCommandHolder * > cliCmdQueue
time_t m_NextDailyQuestReset
time_t m_NextWeeklyQuestReset
time_t m_NextMonthlyQuestReset
time_t m_NextRandomBGReset
time_t m_NextCalendarOldEventsDeletionTime
time_t m_NextGuildReset
Queue m_QueuedPlayer
LockedQueue< WorldSession * > addSessQueue
std::string m_DBVersion
std::string m_WorldDBRevision
std::string m_CharacterDBRevision
std::string m_AuthDBRevision
AutobroadcastsMap m_Autobroadcasts
AutobroadcastsWeightMap m_AutobroadcastsWeights
QueryCallbackProcessor _queryProcessor
Static Private Attributes
static std::atomic_long m_stopEvent = false
static uint8 m_ExitCode = SHUTDOWN_EXIT_CODE
static uint32 m_gameMSTime = 0
static float m_MaxVisibleDistanceOnContinents = DEFAULT_VISIBILITY_DISTANCE
static float m_MaxVisibleDistanceInInstances = DEFAULT_VISIBILITY_INSTANCE
static float m_MaxVisibleDistanceInBGArenas = DEFAULT_VISIBILITY_BGARENAS
Detailed Description
The World.
Definition at line 164 of file World.h.
Member Typedef Documentation
AutobroadcastsMap
typedef std::map<uint8, std::string> World::AutobroadcastsMap private
Definition at line 493 of file World.h.
AutobroadcastsWeightMap
typedef std::map<uint8, uint8> World::AutobroadcastsWeightMap private
Definition at line 496 of file World.h.
DisconnectMap
typedef std::unordered_map<uint32, time_t> World::DisconnectMap private
Definition at line 435 of file World.h.
Queue
typedef std::list<WorldSession*> World::Queue
Definition at line 219 of file World.h.
WorldStatesMap
typedef std::map<uint32, uint64> World::WorldStatesMap private
Definition at line 448 of file World.h.
Constructor & Destructor Documentation
World()
World::World ()
World constructor.
Definition at line 111 of file World.cpp.
 {
     m_playerLimit = 0;
     m_allowedSecurityLevel = SEC_PLAYER;
     m_allowMovement = true;
     m_ShutdownMask = 0;
     m_ShutdownTimer = 0;
     m_gameTime = time(nullptr);
     m_gameMSTime = getMSTime();
     m_startTime = m_gameTime;
     m_maxActiveSessionCount = 0;
     m_maxQueuedSessionCount = 0;
     m_PlayerCount = 0;
     m_MaxPlayerCount = 0;
     m_NextDailyQuestReset = 0;
     m_NextWeeklyQuestReset = 0;
     m_NextMonthlyQuestReset = 0;
     m_NextRandomBGReset = 0;
     m_NextCalendarOldEventsDeletionTime = 0;
     m_NextGuildReset = 0;
     m_defaultDbcLocale = LOCALE_enUS;
     mail_expire_check_timer = 0;
     m_updateTime = 0;
     m_updateTimeSum = 0;
     m_isClosed = false;
     m_CleaningFlags = 0;
     memset(rate_values, 0, sizeof(rate_values));
     memset(m_int_configs, 0, sizeof(m_int_configs));
     memset(m_bool_configs, 0, sizeof(m_bool_configs));
     memset(m_float_configs, 0, sizeof(m_float_configs));
 }
References getMSTime(), LOCALE_enUS, m_allowedSecurityLevel, m_allowMovement, m_bool_configs, m_CleaningFlags, m_defaultDbcLocale, m_float_configs, m_gameMSTime, m_gameTime, m_int_configs, m_isClosed, m_maxActiveSessionCount, m_MaxPlayerCount, m_maxQueuedSessionCount, m_NextCalendarOldEventsDeletionTime, m_NextDailyQuestReset, m_NextGuildReset, m_NextMonthlyQuestReset, m_NextRandomBGReset, m_NextWeeklyQuestReset, m_PlayerCount, m_playerLimit, m_ShutdownMask, m_ShutdownTimer, m_startTime, m_updateTime, m_updateTimeSum, mail_expire_check_timer, memset, rate_values, and SEC_PLAYER.
~World()
World::~World ()
World destructor.
Empty the kicked session set
Definition at line 149 of file World.cpp.
 {
     while (!m_sessions.empty())
     {
         // not remove from queue, prevent loading new sessions
         delete m_sessions.begin()->second;
         m_sessions.erase(m_sessions.begin());
     }
     while (!m_offlineSessions.empty())
     {
         delete m_offlineSessions.begin()->second;
         m_offlineSessions.erase(m_offlineSessions.begin());
     }
     CliCommandHolder* command = nullptr;
     while (cliCmdQueue.next(command))
         delete command;
     VMAP::VMapFactory::clear();
     MMAP::MMapFactory::clear();
     //TODO free addSessQueue
 }
References MMAP::MMapFactory::clear(), VMAP::VMapFactory::clear(), cliCmdQueue, m_offlineSessions, m_sessions, and LockedQueue< T, StorageType >::next().
Member Function Documentation
_UpdateGameTime()
void World::_UpdateGameTime () protected
Update the game time.
update the time
if there is a shutdown timer
... and it is overdue, stop the world (set m_stopEvent)
... else decrease it and if necessary display a shutdown countdown to the users
Definition at line 2686 of file World.cpp.
 {
     time_t thisTime = time(nullptr);
     uint32 elapsed = uint32(thisTime - m_gameTime);
     m_gameTime = thisTime;
     m_gameMSTime = getMSTime();
     if (!IsStopped() && m_ShutdownTimer > 0 && elapsed > 0)
     {
         if (m_ShutdownTimer <= elapsed)
         {
             if (!(m_ShutdownMask & SHUTDOWN_MASK_IDLE) || GetActiveAndQueuedSessionCount() == 0)
                 m_stopEvent = true;                         // exist code already set
             else
                 m_ShutdownTimer = 1;                        // minimum timer value to wait idle state
         }
         else
         {
             m_ShutdownTimer -= elapsed;
             ShutdownMsg();
         }
     }
 }
References GetActiveAndQueuedSessionCount(), getMSTime(), IsStopped(), m_gameMSTime, m_gameTime, m_ShutdownMask, m_ShutdownTimer, m_stopEvent, SHUTDOWN_MASK_IDLE, and ShutdownMsg().
Referenced by Update().
_UpdateRealmCharCount()
void World::_UpdateRealmCharCount (PreparedQueryResult resultCharCount) protected
Definition at line 2964 of file World.cpp.
 {
     if (resultCharCount)
     {
         Field* fields = resultCharCount->Fetch();
         uint32 accountId = fields[0].GetUInt32();
         uint8 charCount = uint8(fields[1].GetUInt64());
         LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_REALM_CHARACTERS_BY_REALM);
         stmt->setUInt32(0, accountId);
         stmt->setUInt32(1, realm.Id.Realm);
         trans->Append(stmt);
         stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_REALM_CHARACTERS);
         stmt->setUInt8(0, charCount);
         stmt->setUInt32(1, accountId);
         stmt->setUInt32(2, realm.Id.Realm);
         trans->Append(stmt);
         LoginDatabase.CommitTransaction(trans);
     }
 }
References Field::GetUInt32(), Realm::Id, LOGIN_DEL_REALM_CHARACTERS_BY_REALM, LOGIN_INS_REALM_CHARACTERS, LoginDatabase, realm, RealmHandle::Realm, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by UpdateRealmCharCount().
AddGlobalPlayerData()
void World::AddGlobalPlayerData (ObjectGuid::LowType guid, uint32 accountId, std::string const & name, uint8 gender, uint8 race, uint8 playerClass, uint8 level, uint16 mailCount, uint32 guildId) virtual
Implements IWorld.
Definition at line 3392 of file World.cpp.
 {
     GlobalPlayerData data;
     data.guidLow = guid;
     data.accountId = accountId;
     data.name = name;
     data.level = level;
     data.race = race;
     data.playerClass = playerClass;
     data.gender = gender;
     data.mailCount = mailCount;
     data.guildId = guildId;
     data.groupId = 0;
     data.arenaTeamId[0] = 0;
     data.arenaTeamId[1] = 0;
     data.arenaTeamId[2] = 0;
     _globalPlayerDataStore[guid] = data;
     _globalPlayerNameStore[name] = guid;
 }
References _globalPlayerDataStore, _globalPlayerNameStore, and name.
Referenced by LoadGlobalPlayerDataStore().
AddQueuedPlayer()
void World::AddQueuedPlayer (WorldSession * sess) virtual
Implements IWorld.
Definition at line 366 of file World.cpp.
 {
     sess->SetInQueue(true);
     m_QueuedPlayer.push_back(sess);
     // The 1st SMSG_AUTH_RESPONSE needs to contain other info too.
     sess->SendAuthResponse(AUTH_WAIT_QUEUE, false, GetQueuePos(sess));
 }
References AUTH_WAIT_QUEUE, GetQueuePos(), m_QueuedPlayer, WorldSession::SendAuthResponse(), and WorldSession::SetInQueue().
Referenced by AddSession_().
AddSession()
void World::AddSession (WorldSession * s) virtual
Implements IWorld.
Definition at line 263 of file World.cpp.
 {
     addSessQueue.add(s);
 }
References LockedQueue< T, StorageType >::add(), and addSessQueue.
AddSession_()
void World::AddSession_ (WorldSession * s) private
Definition at line 268 of file World.cpp.
 {
     ASSERT (s);
     // kick existing session with same account (if any)
     // if character on old session is being loaded, then return
     if (!KickSession(s->GetAccountId()))
     {
         s->KickPlayer("kick existing session with same account");
         delete s; // session not added yet in session list, so not listed in queue
         return;
     }
     SessionMap::const_iterator old = m_sessions.find(s->GetAccountId());
     if (old != m_sessions.end())
     {
         WorldSession* oldSession = old->second;
         if (!RemoveQueuedPlayer(oldSession) && getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
             m_disconnects[s->GetAccountId()] = time(nullptr);
         // pussywizard:
         if (oldSession->HandleSocketClosed())
         {
             // there should be no offline session if current one is logged onto a character
             SessionMap::iterator iter;
             if ((iter = m_offlineSessions.find(oldSession->GetAccountId())) != m_offlineSessions.end())
             {
                 WorldSession* tmp = iter->second;
                 m_offlineSessions.erase(iter);
                 tmp->SetShouldSetOfflineInDB(false);
                 delete tmp;
             }
             oldSession->SetOfflineTime(time(nullptr));
             m_offlineSessions[oldSession->GetAccountId()] = oldSession;
         }
         else
         {
             oldSession->SetShouldSetOfflineInDB(false); // pussywizard: don't set offline in db because new session for that acc is already created
             delete oldSession;
         }
     }
     m_sessions[s->GetAccountId()] = s;
     uint32 Sessions = GetActiveAndQueuedSessionCount();
     uint32 pLimit = GetPlayerAmountLimit();
     // don't count this session when checking player limit
     --Sessions;
     if (pLimit > 0 && Sessions >= pLimit && AccountMgr::IsPlayerAccount(s->GetSecurity()) && !s->CanSkipQueue() && !HasRecentlyDisconnected(s))
     {
         AddQueuedPlayer (s);
         UpdateMaxSessionCounters();
         return;
     }
     s->SendAuthResponse(AUTH_OK, true);
     FinalizePlayerWorldSession(s);
     UpdateMaxSessionCounters();
 }
References AddQueuedPlayer(), ASSERT, AUTH_OK, WorldSession::CanSkipQueue(), CONFIG_INTERVAL_DISCONNECT_TOLERANCE, FinalizePlayerWorldSession(), WorldSession::GetAccountId(), GetActiveAndQueuedSessionCount(), getIntConfig(), GetPlayerAmountLimit(), WorldSession::GetSecurity(), WorldSession::HandleSocketClosed(), HasRecentlyDisconnected(), AccountMgr::IsPlayerAccount(), WorldSession::KickPlayer(), KickSession(), m_disconnects, m_offlineSessions, m_sessions, RemoveQueuedPlayer(), WorldSession::SendAuthResponse(), WorldSession::SetOfflineTime(), WorldSession::SetShouldSetOfflineInDB(), and UpdateMaxSessionCounters().
Referenced by UpdateSessions().
CalendarDeleteOldEvents()
void World::CalendarDeleteOldEvents () protected
Definition at line 3183 of file World.cpp.
 {
     LOG_INFO("server.worldserver", "Calendar deletion of old events.");
     m_NextCalendarOldEventsDeletionTime = time_t(m_NextCalendarOldEventsDeletionTime + DAY);
     sWorld->setWorldState(WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME, uint64(m_NextCalendarOldEventsDeletionTime));
     sCalendarMgr->DeleteOldEvents();
 }
References DAY, LOG_INFO, m_NextCalendarOldEventsDeletionTime, sCalendarMgr, sWorld, and WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME.
Referenced by Update().
DecreasePlayerCount()
void World::DecreasePlayerCount () inline virtual
Implements IWorld.
Definition at line 199 of file World.h.
 { m_PlayerCount--; }
References m_PlayerCount.
DeleteGlobalPlayerData()
void World::DeleteGlobalPlayerData (ObjectGuid::LowType guid, std::string const & name) virtual
Implements IWorld.
Definition at line 3486 of file World.cpp.
 {
     if (guid)
         _globalPlayerDataStore.erase(guid);
     if (!name.empty())
         _globalPlayerNameStore.erase(name);
 }
References _globalPlayerDataStore, _globalPlayerNameStore, and name.
DetectDBCLang()
void World::DetectDBCLang () private
Definition at line 2128 of file World.cpp.
 {
     uint8 m_lang_confid = sConfigMgr->GetOption<int32>("DBC.Locale", 255);
     if (m_lang_confid != 255 && m_lang_confid >= TOTAL_LOCALES)
     {
         LOG_ERROR("server.loading", "Incorrect DBC.Locale! Must be >= 0 and < %d (set to 0)", TOTAL_LOCALES);
         m_lang_confid = LOCALE_enUS;
     }
     ChrRacesEntry const* race = sChrRacesStore.LookupEntry(1);
     std::string availableLocalsStr;
     uint8 default_locale = TOTAL_LOCALES;
     for (uint8 i = default_locale - 1; i < TOTAL_LOCALES; --i) // -1 will be 255 due to uint8
     {
         if (race->name[i][0] != '\0')                     // check by race names
         {
             default_locale = i;
             m_availableDbcLocaleMask |= (1 << i);
             availableLocalsStr += localeNames[i];
             availableLocalsStr += " ";
         }
     }
     if (default_locale != m_lang_confid && m_lang_confid < TOTAL_LOCALES &&
             (m_availableDbcLocaleMask & (1 << m_lang_confid)))
     {
         default_locale = m_lang_confid;
     }
     if (default_locale >= TOTAL_LOCALES)
     {
         LOG_ERROR("server.loading", "Unable to determine your DBC Locale! (corrupt DBC?)");
         exit(1);
     }
     m_defaultDbcLocale = LocaleConstant(default_locale);
     LOG_INFO("server.loading", "Using %s DBC Locale as default. All available DBC locales: %s", localeNames[GetDefaultDbcLocale()], availableLocalsStr.empty() ? "<none>" : availableLocalsStr.c_str());
     LOG_INFO("server.loading", " ");
 }
References GetDefaultDbcLocale(), LOCALE_enUS, localeNames, LOG_ERROR, LOG_INFO, m_availableDbcLocaleMask, m_defaultDbcLocale, ChrRacesEntry::name, sChrRacesStore, sConfigMgr, and TOTAL_LOCALES.
Referenced by SetInitialWorldSettings().
FinalizePlayerWorldSession()
void World::FinalizePlayerWorldSession (WorldSession * session) inline private
Executed when a World Session is being finalized. Be it from a normal login or via queue popping.
Parameters
session The World Session that we are finalizing.
Definition at line 3617 of file World.cpp.
 {
     uint32 cacheVersion = sWorld->getIntConfig(CONFIG_CLIENTCACHE_VERSION);
     sScriptMgr->OnBeforeFinalizePlayerWorldSession(cacheVersion);
     session->SendAddonsInfo();
     session->SendClientCacheVersion(cacheVersion);
     session->SendTutorialsData();
 }
References CONFIG_CLIENTCACHE_VERSION, WorldSession::SendAddonsInfo(), WorldSession::SendClientCacheVersion(), WorldSession::SendTutorialsData(), sScriptMgr, and sWorld.
Referenced by AddSession_(), and RemoveQueuedPlayer().
FindOfflineSession()
WorldSession * World::FindOfflineSession (uint32 id) const virtual
Implements IWorld.
Definition at line 225 of file World.cpp.
 {
     SessionMap::const_iterator itr = m_offlineSessions.find(id);
     if (itr != m_offlineSessions.end())
         return itr->second;
     else
         return nullptr;
 }
References m_offlineSessions.
FindOfflineSessionForCharacterGUID()
WorldSession * World::FindOfflineSessionForCharacterGUID (ObjectGuid::LowType guidLow) const virtual
Implements IWorld.
Definition at line 234 of file World.cpp.
 {
     if (m_offlineSessions.empty())
         return nullptr;
     for (SessionMap::const_iterator itr = m_offlineSessions.begin(); itr != m_offlineSessions.end(); ++itr)
         if (itr->second->GetGuidLow() == guidLow)
             return itr->second;
     return nullptr;
 }
References m_offlineSessions.
FindPlayerInZone()
Player * World::FindPlayerInZone (uint32 zone) virtual
Find a player in a specified zone.
circle through active sessions and return the first player found in the zone
Implements IWorld.
Definition at line 182 of file World.cpp.
 {
     SessionMap::const_iterator itr;
     for (itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (!itr->second)
             continue;
         Player* player = itr->second->GetPlayer();
         if (!player)
             continue;
         if (player->IsInWorld() && player->GetZoneId() == zone)
             return player;
     }
     return nullptr;
 }
References WorldObject::GetZoneId(), Object::IsInWorld(), and m_sessions.
FindSession()
WorldSession * World::FindSession (uint32 id) const virtual
Find a session by its id.
Implements IWorld.
Definition at line 215 of file World.cpp.
 {
     SessionMap::const_iterator itr = m_sessions.find(id);
     if (itr != m_sessions.end())
         return itr->second;                                 // also can return nullptr for kicked session
     else
         return nullptr;
 }
References m_sessions.
ForceGameEventUpdate()
void World::ForceGameEventUpdate () virtual
Implements IWorld.
Definition at line 2485 of file World.cpp.
 {
     m_timers[WUPDATE_EVENTS].Reset();                   // to give time for Update() to be processed
     uint32 nextGameEvent = sGameEventMgr->Update();
     m_timers[WUPDATE_EVENTS].SetInterval(nextGameEvent);
     m_timers[WUPDATE_EVENTS].Reset();
 }
References m_timers, IntervalTimer::Reset(), IntervalTimer::SetInterval(), sGameEventMgr, and WUPDATE_EVENTS.
GetActiveAndQueuedSessionCount()
uint32 World::GetActiveAndQueuedSessionCount () const inline virtual
Implements IWorld.
Definition at line 183 of file World.h.
 { return m_sessions.size(); }
References m_sessions.
Referenced by _UpdateGameTime(), AddSession_(), and ShutdownServ().
GetActiveSessionCount()
uint32 World::GetActiveSessionCount () const inline virtual
Implements IWorld.
Definition at line 184 of file World.h.
 { return m_sessions.size() - m_QueuedPlayer.size(); }
References m_QueuedPlayer, and m_sessions.
Referenced by RemoveQueuedPlayer(), and Update().
getAllowMovement()
bool World::getAllowMovement () const inline virtual
Todo:
Actions on m_allowMovement still to be implemented Is movement allowed?
Implements IWorld.
Definition at line 227 of file World.h.
 { return m_allowMovement; }
References m_allowMovement.
GetAllSessions()
const SessionMap& World::GetAllSessions () const inline virtual
Implements IWorld.
Definition at line 182 of file World.h.
 { return m_sessions; }
References m_sessions.
GetAuthDBRevision()
char const* World::GetAuthDBRevision () const inline virtual
Implements IWorld.
Definition at line 381 of file World.h.
 { return m_AuthDBRevision.c_str(); }
References m_AuthDBRevision.
GetAvailableDbcLocale()
LocaleConstant World::GetAvailableDbcLocale (LocaleConstant locale) const inline virtual
Implements IWorld.
Definition at line 373 of file World.h.
 { if (m_availableDbcLocaleMask & (1 << locale)) return locale; else return m_defaultDbcLocale; }
References m_availableDbcLocaleMask, and m_defaultDbcLocale.
getBoolConfig()
bool World::getBoolConfig (WorldBoolConfigs index) const inline virtual
Get a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 303 of file World.h.
     {
         return index < BOOL_CONFIG_VALUE_COUNT ? m_bool_configs[index] : false;
     }
References BOOL_CONFIG_VALUE_COUNT, index, and m_bool_configs.
GetCharacterDBRevision()
char const* World::GetCharacterDBRevision () const inline virtual
Implements IWorld.
Definition at line 380 of file World.h.
 { return m_CharacterDBRevision.c_str(); }
References m_CharacterDBRevision.
GetCleaningFlags()
uint32 World::GetCleaningFlags () const inline virtual
Implements IWorld.
Definition at line 387 of file World.h.
 { return m_CleaningFlags; }
References m_CleaningFlags.
GetConfigMaxSkillValue()
uint16 World::GetConfigMaxSkillValue () const inline virtual
Get the maximum skill level a player can reach.
Implements IWorld.
Definition at line 259 of file World.h.
     {
         uint16 lvl = uint16(getIntConfig(CONFIG_MAX_PLAYER_LEVEL));
         return lvl > 60 ? 300 + ((lvl - 60) * 75) / 10 : lvl * 5;
     }
References CONFIG_MAX_PLAYER_LEVEL, and getIntConfig().
GetDataPath()
std::string const& World::GetDataPath () const inline virtual
Get the path where data (dbc, maps) are stored on disk.
Implements IWorld.
Definition at line 239 of file World.h.
 { return m_dataPath; }
References m_dataPath.
GetDBVersion()
char const* World::GetDBVersion () const inline virtual
Implements IWorld.
Definition at line 378 of file World.h.
 { return m_DBVersion.c_str(); }
References m_DBVersion.
GetDefaultDbcLocale()
LocaleConstant World::GetDefaultDbcLocale () const inline virtual
Implements IWorld.
Definition at line 236 of file World.h.
 { return m_defaultDbcLocale; }
References m_defaultDbcLocale.
Referenced by DetectDBCLang(), and SetInitialWorldSettings().
GetExitCode()
static uint8 World::GetExitCode () inline static
Definition at line 283 of file World.h.
 { return m_ExitCode; }
References m_ExitCode.
Referenced by main().
getFloatConfig()
float World::getFloatConfig (WorldFloatConfigs index) const inline virtual
Get a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 316 of file World.h.
     {
         return index < FLOAT_CONFIG_VALUE_COUNT ? m_float_configs[index] : 0;
     }
References FLOAT_CONFIG_VALUE_COUNT, index, and m_float_configs.
GetGameTime()
time_t const& World::GetGameTime () const inline virtual
What time is it?
Implements IWorld.
Definition at line 244 of file World.h.
 { return m_gameTime; }
References m_gameTime.
GetGameTimeMS()
static uint32 World::GetGameTimeMS () inline static
What time is it? in ms.
Definition at line 246 of file World.h.
 { return m_gameMSTime; }
References m_gameMSTime.
Referenced by Creature::_AddCreatureSpellCooldown(), Player::_AddSpellCooldown(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), GlobalCooldownMgr::AddGlobalCooldown(), BattlegroundQueue::AddGroup(), WorldObject::AddToNotify(), Unit::ApplyDiminishingAura(), Player::ApplyEquipCooldown(), BattlegroundQueue::BattlegroundQueueUpdate(), AuctionHouseObject::BuildListAuctionItems(), Unit::BuildMovementPacket(), BattlegroundQueue::CheckPremadeMatch(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_AuraScript::CheckProc(), DynamicObject::CreateDynamicObject(), Spell::DoAllEffectOnTarget(), Spell::EffectSanctuary(), Unit::GetDiminishing(), Creature::GetSpellCooldown(), Player::GetSpellCooldownDelay(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldSession::HandleAuctionListOwnerItemsEvent(), WorldSession::HandleBattlefieldStatusOpcode(), WardenWin::HandleData(), spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript::HandleEffectPeriodic(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), GlobalCooldownMgr::HasGlobalCooldown(), Creature::HasSpellCooldown(), Player::HasSpellCooldown(), Player::HasSpellItemCooldown(), Unit::IncrDiminishing(), BattlegroundMgr::InviteGroupToBG(), Creature::IsSpellProhibited(), Unit::IsUnderLastManaUseEffect(), spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript::Load(), spell_gen_turkey_marker::OnPeriodic(), Player::PetSpellInitialize(), BattlegroundQueue::PlayerInvitedToBGUpdateAverageWaitTime(), BattlegroundEY::PostUpdateImpl(), Creature::ProhibitSpellSchool(), Player::RemoveAllSpellCooldown(), Player::RemoveArenaSpellCooldowns(), WardenWin::RequestChecks(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SelectPosition(), Player::SendInitialSpells(), Unit::SendMonsterMove(), Spell::SendSpellGo(), boss_ignis::boss_ignisAI::SetData(), Spell::TakePower(), GameObject::Update(), BattlegroundSA::UpdateDemolisherSpawns(), lfg::LFGMgr::UpdateRaidBrowser(), GameObject::Use(), GameObject::UseDoorOrButton(), and Player::VehicleSpellInitialize().
GetGlobalPlayerData()
GlobalPlayerData const * World::GetGlobalPlayerData (ObjectGuid::LowType guid) const virtual
Implements IWorld.
Definition at line 3494 of file World.cpp.
 {
     // Get data from global storage
     GlobalPlayerDataMap::const_iterator itr = _globalPlayerDataStore.find(guid);
     if (itr != _globalPlayerDataStore.end())
         return &itr->second;
     // Player is not in the global storage, try to get it from the Database
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_DATA_BY_GUID);
     stmt->setUInt32(0, guid);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (result)
     {
         // Player was not in the global storage, but it was found in the database
         // Let's add it to the global storage
         Field* fields = result->Fetch();
         std::string name = fields[2].GetString();
         LOG_INFO("server.worldserver", "Player %s [GUID: %u] was not found in the global storage, but it was found in the database.", name.c_str(), guid);
         sWorld->AddGlobalPlayerData(
             fields[0].GetUInt32(), /*guid*/
             fields[1].GetUInt32(), /*accountId*/
             fields[2].GetString(), /*name*/
             fields[3].GetUInt8(),  /*gender*/
             fields[4].GetUInt8(),  /*race*/
             fields[5].GetUInt8(),  /*class*/
             fields[6].GetUInt8(),  /*level*/
             0,                     /*mail count*/
             0                      /*guild id*/
         );
         itr = _globalPlayerDataStore.find(guid);
         if (itr != _globalPlayerDataStore.end())
         {
             LOG_INFO("server.worldserver", "Player %s [GUID: %u] added to the global storage.", name.c_str(), guid);
             return &itr->second;
         }
     }
     // Player not found
     return nullptr;
 }
References _globalPlayerDataStore, CHAR_SEL_DATA_BY_GUID, CharacterDatabase, Field::GetString(), LOG_INFO, name, PreparedStatementBase::setUInt32(), and sWorld.
GetGlobalPlayerGUID()
ObjectGuid World::GetGlobalPlayerGUID (std::string const & name) const virtual
Implements IWorld.
Definition at line 3542 of file World.cpp.
 {
     // Get data from global storage
     GlobalPlayerNameMap::const_iterator itr = _globalPlayerNameStore.find(name);
     if (itr != _globalPlayerNameStore.end())
         return ObjectGuid::Create<HighGuid::Player>(itr->second);
     // Player is not in the global storage, try to get it from the Database
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_DATA_BY_NAME);
     stmt->setString(0, name);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (result)
     {
         // Player was not in the global storage, but it was found in the database
         // Let's add it to the global storage
         Field* fields = result->Fetch();
         ObjectGuid::LowType guidLow = fields[0].GetUInt32();
         LOG_INFO("server.worldserver", "Player %s [GUID: %u] was not found in the global storage, but it was found in the database.", name.c_str(), guidLow);
         sWorld->AddGlobalPlayerData(
             guidLow,               /*guid*/
             fields[1].GetUInt32(), /*accountId*/
             fields[2].GetString(), /*name*/
             fields[3].GetUInt8(),  /*gender*/
             fields[4].GetUInt8(),  /*race*/
             fields[5].GetUInt8(),  /*class*/
             fields[6].GetUInt8(),  /*level*/
             0,                     /*mail count*/
             0                      /*guild id*/
         );
         itr = _globalPlayerNameStore.find(name);
         if (itr != _globalPlayerNameStore.end())
         {
             LOG_INFO("server.worldserver", "Player %s [GUID: %u] added to the global storage.", name.c_str(), guidLow);
             return ObjectGuid::Create<HighGuid::Player>(guidLow);
         }
     }
     // Player not found
     return ObjectGuid::Empty;
 }
References _globalPlayerNameStore, CHAR_SEL_DATA_BY_NAME, CharacterDatabase, ObjectGuid::Empty, Field::GetUInt32(), LOG_INFO, name, PreparedStatementBase::setString(), and sWorld.
getIntConfig()
uint32 World::getIntConfig (WorldIntConfigs index) const inline virtual
Get a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 329 of file World.h.
     {
         return index < INT_CONFIG_VALUE_COUNT ? m_int_configs[index] : 0;
     }
References index, INT_CONFIG_VALUE_COUNT, and m_int_configs.
Referenced by AddSession_(), GetConfigMaxSkillValue(), HasRecentlyDisconnected(), InitCalendarOldEventsDeletionTime(), IsFFAPvPRealm(), IsPvPRealm(), SetInitialWorldSettings(), and UpdateSessions().
GetMaxActiveSessionCount()
uint32 World::GetMaxActiveSessionCount () const inline virtual
Implements IWorld.
Definition at line 188 of file World.h.
 { return m_maxActiveSessionCount; }
References m_maxActiveSessionCount.
GetMaxPlayerCount()
uint32 World::GetMaxPlayerCount () const inline virtual
Implements IWorld.
Definition at line 191 of file World.h.
 { return m_MaxPlayerCount; }
References m_MaxPlayerCount.
Referenced by Update().
GetMaxQueuedSessionCount()
uint32 World::GetMaxQueuedSessionCount () const inline virtual
Get the maximum number of parallel sessions on the server since last reboot.
Implements IWorld.
Definition at line 187 of file World.h.
 { return m_maxQueuedSessionCount; }
References m_maxQueuedSessionCount.
GetMaxVisibleDistanceInBGArenas()
static float World::GetMaxVisibleDistanceInBGArenas () inline static
Definition at line 348 of file World.h.
 { return m_MaxVisibleDistanceInBGArenas;   }
References m_MaxVisibleDistanceInBGArenas.
Referenced by Battleground::_ProcessJoin(), and BattlegroundMap::InitVisibilityDistance().
GetMaxVisibleDistanceInInstances()
static float World::GetMaxVisibleDistanceInInstances () inline static
Definition at line 347 of file World.h.
 { return m_MaxVisibleDistanceInInstances;  }
References m_MaxVisibleDistanceInInstances.
Referenced by InstanceMap::InitVisibilityDistance().
GetMaxVisibleDistanceOnContinents()
static float World::GetMaxVisibleDistanceOnContinents () inline static
Definition at line 346 of file World.h.
 { return m_MaxVisibleDistanceOnContinents; }
References m_MaxVisibleDistanceOnContinents.
Referenced by Map::InitVisibilityDistance().
GetNewCharString()
std::string const& World::GetNewCharString () const inline virtual
Get the string for new characters (first login)
Implements IWorld.
Definition at line 234 of file World.h.
 { return m_newCharString; }
References m_newCharString.
GetNextDailyQuestsResetTime()
time_t World::GetNextDailyQuestsResetTime () const inline virtual
Next daily quests and random bg reset time.
Implements IWorld.
Definition at line 254 of file World.h.
 { return m_NextDailyQuestReset; }
References m_NextDailyQuestReset.
GetNextRandomBGResetTime()
time_t World::GetNextRandomBGResetTime () const inline virtual
Implements IWorld.
Definition at line 256 of file World.h.
 { return m_NextRandomBGReset; }
References m_NextRandomBGReset.
GetNextTimeWithDayAndHour()
time_t World::GetNextTimeWithDayAndHour (int8 dayOfWeek, int8 hour) virtual
Implements IWorld.
Definition at line 2990 of file World.cpp.
 {
     if (hour < 0 || hour > 23)
         hour = 0;
     time_t curr = time(nullptr);
     tm localTm;
     localtime_r(&curr, &localTm);
     localTm.tm_hour = hour;
     localTm.tm_min  = 0;
     localTm.tm_sec  = 0;
     uint32 add;
     if (dayOfWeek < 0 || dayOfWeek > 6)
         dayOfWeek = (localTm.tm_wday + 1) % 7;
     if (localTm.tm_wday >= dayOfWeek)
         add = (7 - (localTm.tm_wday - dayOfWeek)) * DAY;
     else
         add = (dayOfWeek - localTm.tm_wday) * DAY;
     return mktime(&localTm) + add;
 }
References DAY, and localtime_r().
Referenced by InitCalendarOldEventsDeletionTime(), InitDailyQuestResetTime(), InitGuildResetTime(), InitRandomBGResetTime(), InitWeeklyQuestResetTime(), ResetDailyQuests(), ResetGuildCap(), ResetRandomBG(), and ResetWeeklyQuests().
GetNextTimeWithMonthAndHour()
time_t World::GetNextTimeWithMonthAndHour (int8 month, int8 hour) virtual
Implements IWorld.
Definition at line 3011 of file World.cpp.
 {
     if (hour < 0 || hour > 23)
         hour = 0;
     time_t curr = time(nullptr);
     tm localTm;
     localtime_r(&curr, &localTm);
     localTm.tm_mday = 1;
     localTm.tm_hour = hour;
     localTm.tm_min  = 0;
     localTm.tm_sec  = 0;
     if (month < 0 || month > 11)
     {
         month = (localTm.tm_mon + 1) % 12;
         if (month == 0)
             localTm.tm_year += 1;
     }
     else if (localTm.tm_mon >= month)
         localTm.tm_year += 1;
     localTm.tm_mon = month;
     return mktime(&localTm);
 }
References localtime_r().
Referenced by InitMonthlyQuestResetTime(), and ResetMonthlyQuests().
GetNextWeeklyQuestsResetTime()
time_t World::GetNextWeeklyQuestsResetTime () const inline virtual
Implements IWorld.
Definition at line 255 of file World.h.
 { return m_NextWeeklyQuestReset; }
References m_NextWeeklyQuestReset.
GetNextWhoListUpdateDelaySecs()
uint32 World::GetNextWhoListUpdateDelaySecs () virtual
Implements IWorld.
Definition at line 3606 of file World.cpp.
 {
     if (m_timers[WUPDATE_5_SECS].Passed())
         return 1;
     uint32 t = m_timers[WUPDATE_5_SECS].GetInterval() - m_timers[WUPDATE_5_SECS].GetCurrent();
     t = std::min(t, (uint32)m_timers[WUPDATE_5_SECS].GetInterval());
     return uint32(ceil(t / 1000.0f));
 }
References G3D::ceil(), IntervalTimer::GetCurrent(), IntervalTimer::GetInterval(), m_timers, min, and WUPDATE_5_SECS.
GetPlayerAmountLimit()
uint32 World::GetPlayerAmountLimit () const inline virtual
Implements IWorld.
Definition at line 216 of file World.h.
 { return m_playerLimit; }
References m_playerLimit.
Referenced by AddSession_(), and RemoveQueuedPlayer().
GetPlayerCount()
uint32 World::GetPlayerCount () const inline virtual
Get number of players.
Implements IWorld.
Definition at line 190 of file World.h.
 { return m_PlayerCount; }
References m_PlayerCount.
GetPlayerSecurityLimit()
AccountTypes World::GetPlayerSecurityLimit () const inline virtual
Security level limitations.
Implements IWorld.
Definition at line 210 of file World.h.
 { return m_allowedSecurityLevel; }
References m_allowedSecurityLevel.
GetQueuedSessionCount()
uint32 World::GetQueuedSessionCount () const inline virtual
Implements IWorld.
Definition at line 185 of file World.h.
 { return m_QueuedPlayer.size(); }
References m_QueuedPlayer.
GetQueuePos()
int32 World::GetQueuePos (WorldSession * sess) virtual
Implements IWorld.
Definition at line 355 of file World.cpp.
 {
     uint32 position = 1;
     for (Queue::const_iterator iter = m_QueuedPlayer.begin(); iter != m_QueuedPlayer.end(); ++iter, ++position)
         if ((*iter) == sess)
             return position;
     return 0;
 }
References m_QueuedPlayer.
Referenced by AddQueuedPlayer().
getRate()
float World::getRate (Rates rate) const inline virtual
Get a server rate (see Rates)
Implements IWorld.
Definition at line 293 of file World.h.
 { return rate_values[rate]; }
References rate_values.
Referenced by LoadConfigSettings().
GetRealmName()
std::string const& World::GetRealmName () const inline virtual
Implements IWorld.
Definition at line 394 of file World.h.
 { return _realmName; } // pussywizard
References _realmName.
GetShutDownTimeLeft()
uint32 World::GetShutDownTimeLeft () const inline virtual
Implements IWorld.
Definition at line 279 of file World.h.
 { return m_ShutdownTimer; }
References m_ShutdownTimer.
GetStartTime()
time_t const& World::GetStartTime () const inline virtual
When server started?
Implements IWorld.
Definition at line 242 of file World.h.
 { return m_startTime; }
References m_startTime.
GetUpdateTime()
uint32 World::GetUpdateTime () const inline virtual
Update time.
Implements IWorld.
Definition at line 250 of file World.h.
 { return m_updateTime; }
References m_updateTime.
GetUptime()
uint32 World::GetUptime () const inline virtual
Uptime (in secs)
Implements IWorld.
Definition at line 248 of file World.h.
 { return uint32(m_gameTime - m_startTime); }
References m_gameTime, and m_startTime.
GetWorldDBRevision()
char const* World::GetWorldDBRevision () const inline virtual
Implements IWorld.
Definition at line 379 of file World.h.
 { return m_WorldDBRevision.c_str(); }
References m_WorldDBRevision.
getWorldState()
uint64 World::getWorldState (uint32 index) const virtual
Implements IWorld.
Definition at line 3326 of file World.cpp.
 {
     WorldStatesMap::const_iterator it = m_worldstates.find(index);
     return it != m_worldstates.end() ? it->second : 0;
 }
References index, and m_worldstates.
Referenced by InitCalendarOldEventsDeletionTime(), and InitGuildResetTime().
HasRecentlyDisconnected()
bool World::HasRecentlyDisconnected (WorldSession * session) virtual
Implements IWorld.
Definition at line 333 of file World.cpp.
 {
     if (!session)
         return false;
     if (uint32 tolerance = getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
     {
         for (DisconnectMap::iterator i = m_disconnects.begin(); i != m_disconnects.end();)
         {
             if ((time(nullptr) - i->second) < tolerance)
             {
                 if (i->first == session->GetAccountId())
                     return true;
                 ++i;
             }
             else
                 m_disconnects.erase(i++);
         }
     }
     return false;
 }
References CONFIG_INTERVAL_DISCONNECT_TOLERANCE, WorldSession::GetAccountId(), getIntConfig(), and m_disconnects.
Referenced by AddSession_().
IncreasePlayerCount()
void World::IncreasePlayerCount () inline virtual
Increase/Decrease number of players.
Implements IWorld.
Definition at line 194 of file World.h.
     {
         m_PlayerCount++;
         m_MaxPlayerCount = std::max(m_MaxPlayerCount, m_PlayerCount);
     }
References m_MaxPlayerCount, m_PlayerCount, and max.
InitCalendarOldEventsDeletionTime()
void World::InitCalendarOldEventsDeletionTime () protected
Definition at line 3066 of file World.cpp.
 {
     time_t now = time(nullptr);
     time_t currentDeletionTime = getWorldState(WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME);
     time_t nextDeletionTime = currentDeletionTime ? currentDeletionTime : GetNextTimeWithDayAndHour(-1, getIntConfig(CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR));
     // If the reset time saved in the worldstate is before now it means the server was offline when the reset was supposed to occur.
     // In this case we set the reset time in the past and next world update will do the reset and schedule next one in the future.
     if (currentDeletionTime < now)
         m_NextCalendarOldEventsDeletionTime = nextDeletionTime - DAY;
     else
         m_NextCalendarOldEventsDeletionTime = nextDeletionTime;
     if (!currentDeletionTime)
         sWorld->setWorldState(WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME, uint64(m_NextCalendarOldEventsDeletionTime));
 }
References CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR, DAY, getIntConfig(), GetNextTimeWithDayAndHour(), getWorldState(), m_NextCalendarOldEventsDeletionTime, sWorld, and WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME.
Referenced by SetInitialWorldSettings().
InitDailyQuestResetTime()
void World::InitDailyQuestResetTime () protected
Definition at line 3042 of file World.cpp.
 {
     time_t wstime = time_t(sWorld->getWorldState(WS_DAILY_QUEST_RESET_TIME));
     m_NextDailyQuestReset = wstime ? wstime : GetNextTimeWithDayAndHour(-1, 6);
     if (!wstime)
         sWorld->setWorldState(WS_DAILY_QUEST_RESET_TIME, uint64(m_NextDailyQuestReset));
 }
References GetNextTimeWithDayAndHour(), m_NextDailyQuestReset, sWorld, and WS_DAILY_QUEST_RESET_TIME.
Referenced by SetInitialWorldSettings().
InitGuildResetTime()
void World::InitGuildResetTime () protected
Definition at line 3083 of file World.cpp.
 {
     time_t wstime = time_t(getWorldState(WS_GUILD_DAILY_RESET_TIME));
     m_NextGuildReset = wstime ? wstime : GetNextTimeWithDayAndHour(-1, 6);
     if (!wstime)
         sWorld->setWorldState(WS_GUILD_DAILY_RESET_TIME, uint64(m_NextGuildReset));
 }
References GetNextTimeWithDayAndHour(), getWorldState(), m_NextGuildReset, sWorld, and WS_GUILD_DAILY_RESET_TIME.
Referenced by SetInitialWorldSettings().
InitMonthlyQuestResetTime()
void World::InitMonthlyQuestResetTime () protected
Definition at line 3050 of file World.cpp.
 {
     time_t wstime = time_t(sWorld->getWorldState(WS_MONTHLY_QUEST_RESET_TIME));
     m_NextMonthlyQuestReset = wstime ? wstime : GetNextTimeWithMonthAndHour(-1, 6);
     if (!wstime)
         sWorld->setWorldState(WS_MONTHLY_QUEST_RESET_TIME, uint64(m_NextMonthlyQuestReset));
 }
References GetNextTimeWithMonthAndHour(), m_NextMonthlyQuestReset, sWorld, and WS_MONTHLY_QUEST_RESET_TIME.
Referenced by SetInitialWorldSettings().
InitRandomBGResetTime()
void World::InitRandomBGResetTime () protected
Definition at line 3058 of file World.cpp.
 {
     time_t wstime = time_t(sWorld->getWorldState(WS_BG_DAILY_RESET_TIME));
     m_NextRandomBGReset = wstime ? wstime : GetNextTimeWithDayAndHour(-1, 6);
     if (!wstime)
         sWorld->setWorldState(WS_BG_DAILY_RESET_TIME, uint64(m_NextRandomBGReset));
 }
References GetNextTimeWithDayAndHour(), m_NextRandomBGReset, sWorld, and WS_BG_DAILY_RESET_TIME.
Referenced by SetInitialWorldSettings().
InitWeeklyQuestResetTime()
void World::InitWeeklyQuestResetTime () protected
Definition at line 3034 of file World.cpp.
 {
     time_t wstime = time_t(sWorld->getWorldState(WS_WEEKLY_QUEST_RESET_TIME));
     m_NextWeeklyQuestReset = wstime ? wstime : GetNextTimeWithDayAndHour(4, 6);
     if (!wstime)
         sWorld->setWorldState(WS_WEEKLY_QUEST_RESET_TIME, uint64(m_NextWeeklyQuestReset));
 }
References GetNextTimeWithDayAndHour(), m_NextWeeklyQuestReset, sWorld, and WS_WEEKLY_QUEST_RESET_TIME.
Referenced by SetInitialWorldSettings().
instance()
static World* World::instance () static
IsClosed()
bool World::IsClosed () const virtual
Deny clients?
Implements IWorld.
Definition at line 201 of file World.cpp.
 {
     return m_isClosed;
 }
References m_isClosed.
IsFFAPvPRealm()
bool World::IsFFAPvPRealm () const virtual
Implements IWorld.
Definition at line 3601 of file World.cpp.
 {
     return getIntConfig(CONFIG_GAME_TYPE) == REALM_TYPE_FFA_PVP;
 }
References CONFIG_GAME_TYPE, getIntConfig(), and REALM_TYPE_FFA_PVP.
Referenced by SetInitialWorldSettings().
IsPvPRealm()
bool World::IsPvPRealm () const virtual
Are we on a "Player versus Player" server?
Implements IWorld.
Definition at line 3596 of file World.cpp.
 {
     return getIntConfig(CONFIG_GAME_TYPE) == REALM_TYPE_PVP || getIntConfig(CONFIG_GAME_TYPE) == REALM_TYPE_RPPVP || getIntConfig(CONFIG_GAME_TYPE) == REALM_TYPE_FFA_PVP;
 }
References CONFIG_GAME_TYPE, getIntConfig(), REALM_TYPE_FFA_PVP, REALM_TYPE_PVP, and REALM_TYPE_RPPVP.
IsShuttingDown()
bool World::IsShuttingDown () const inline virtual
Are we in the middle of a shutdown?
Implements IWorld.
Definition at line 278 of file World.h.
 { return m_ShutdownTimer > 0; }
References m_ShutdownTimer.
IsStopped()
static bool World::IsStopped () inline static
Definition at line 285 of file World.h.
 { return m_stopEvent; }
References m_stopEvent.
Referenced by _UpdateGameTime(), ACSoapThread(), AuctionListingRunnable(), CliThread(), WorldSession::HandleSocketClosed(), ShutdownServ(), and WorldUpdateLoop().
KickAll()
void World::KickAll () virtual
Kick (and save) all players.
Implements IWorld.
Definition at line 2663 of file World.cpp.
 {
     m_QueuedPlayer.clear();                                 // prevent send queue update packet and login queued sessions
     // session not removed at kick and will removed in next update tick
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         itr->second->KickPlayer("KickAll sessions");
     // pussywizard: kick offline sessions
     for (SessionMap::const_iterator itr = m_offlineSessions.begin(); itr != m_offlineSessions.end(); ++itr)
         itr->second->KickPlayer("KickAll offline sessions");
 }
References m_offlineSessions, m_QueuedPlayer, and m_sessions.
KickAllLess()
void World::KickAllLess (AccountTypes sec) virtual
Kick (and save) all players with security level less sec
Implements IWorld.
Definition at line 2677 of file World.cpp.
 {
     // session not removed at kick and will removed in next update tick
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetSecurity() < sec)
             itr->second->KickPlayer("KickAllLess");
 }
References m_sessions, and sec.
Referenced by SetPlayerSecurityLimit().
KickSession()
bool World::KickSession (uint32 id) virtual
Remove a given session.
Find the session, kick the user, but we can't delete session at this moment to prevent iterator invalidation
Implements IWorld.
Definition at line 247 of file World.cpp.
 {
     SessionMap::const_iterator itr = m_sessions.find(id);
     if (itr != m_sessions.end() && itr->second)
     {
         if (itr->second->PlayerLoading())
             return false;
         itr->second->KickPlayer("KickSession", false);
     }
     return true;
 }
References m_sessions.
Referenced by AddSession_().
LoadAutobroadcasts()
void World::LoadAutobroadcasts () virtual
Implements IWorld.
Definition at line 2171 of file World.cpp.
 {
     uint32 oldMSTime = getMSTime();
     m_Autobroadcasts.clear();
     m_AutobroadcastsWeights.clear();
     uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST);
     stmt->setInt32(0, realmId);
     PreparedQueryResult result = LoginDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 autobroadcasts definitions. DB table `autobroadcast` is empty for this realm!");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint8 id = fields[0].GetUInt8();
         m_Autobroadcasts[id] = fields[2].GetString();
         m_AutobroadcastsWeights[id] = fields[1].GetUInt8();
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u autobroadcast definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References count(), getMSTime(), GetMSTimeDiffToNow(), Field::GetString(), Field::GetUInt8(), LOG_INFO, LOGIN_SEL_AUTOBROADCAST, LoginDatabase, m_Autobroadcasts, m_AutobroadcastsWeights, and sConfigMgr.
Referenced by SetInitialWorldSettings().
LoadConfigSettings()
void World::LoadConfigSettings (bool reload = false) virtual
Initialize config values.
Read the player limit and the Message of the day from the config file
Read ticket system setting from the config file
Get string for new logins (newly created characters)
Send server info on login?
Read all rates from the config file
Read other configuration items from the config file
Todo:
Add MonsterSight in worldserver.conf or put it as define
Load the CharDelete related config options
Load the ItemDelete related config options
Read the "Data" directory from the config file
Implements IWorld.
Definition at line 430 of file World.cpp.
 {
     if (reload)
     {
         if (!sConfigMgr->Reload())
         {
             LOG_ERROR("server.loading", "World settings reload fail: can't read settings.");
             return;
         }
         sLog->LoadFromConfig();
         sMetric->LoadFromConfigs();
     }
     // Set realm id and enable db logging
     sLog->SetRealmId(realm.Id.Realm);
 #ifdef ELUNA
     if (!reload)
     {
         LOG_INFO("eluna", "Initialize Eluna Lua Engine...");
         Eluna::Initialize();
     }
 #endif
     sScriptMgr->OnBeforeConfigLoad(reload);
     if (!reload)
     {
         SetPlayerAmountLimit(sConfigMgr->GetOption<int32>("PlayerLimit", 1000));
     }
     Motd::SetMotd(sConfigMgr->GetOption<std::string>("Motd", "Welcome to an AzerothCore server"));
     m_bool_configs[CONFIG_ALLOW_TICKETS] = sConfigMgr->GetOption<bool>("AllowTickets", true);
     m_bool_configs[CONFIG_DELETE_CHARACTER_TICKET_TRACE] = sConfigMgr->GetOption<bool>("DeletedCharacterTicketTrace", false);
     SetNewCharString(sConfigMgr->GetOption<std::string>("PlayerStart.String", ""));
     m_int_configs[CONFIG_ENABLE_SINFO_LOGIN] = sConfigMgr->GetOption<int32>("Server.LoginInfo", 0);
     rate_values[RATE_HEALTH]      = sConfigMgr->GetOption<float>("Rate.Health", 1);
     if (rate_values[RATE_HEALTH] < 0)
     {
         LOG_ERROR("server.loading", "Rate.Health (%f) must be > 0. Using 1 instead.", rate_values[RATE_HEALTH]);
         rate_values[RATE_HEALTH] = 1;
     }
     rate_values[RATE_POWER_MANA]  = sConfigMgr->GetOption<float>("Rate.Mana", 1);
     if (rate_values[RATE_POWER_MANA] < 0)
     {
         LOG_ERROR("server.loading", "Rate.Mana (%f) must be > 0. Using 1 instead.", rate_values[RATE_POWER_MANA]);
         rate_values[RATE_POWER_MANA] = 1;
     }
     rate_values[RATE_POWER_RAGE_INCOME] = sConfigMgr->GetOption<float>("Rate.Rage.Income", 1);
     rate_values[RATE_POWER_RAGE_LOSS]   = sConfigMgr->GetOption<float>("Rate.Rage.Loss", 1);
     if (rate_values[RATE_POWER_RAGE_LOSS] < 0)
     {
         LOG_ERROR("server.loading", "Rate.Rage.Loss (%f) must be > 0. Using 1 instead.", rate_values[RATE_POWER_RAGE_LOSS]);
         rate_values[RATE_POWER_RAGE_LOSS] = 1;
     }
     rate_values[RATE_POWER_RUNICPOWER_INCOME] = sConfigMgr->GetOption<float>("Rate.RunicPower.Income", 1);
     rate_values[RATE_POWER_RUNICPOWER_LOSS]   = sConfigMgr->GetOption<float>("Rate.RunicPower.Loss", 1);
     if (rate_values[RATE_POWER_RUNICPOWER_LOSS] < 0)
     {
         LOG_ERROR("server.loading", "Rate.RunicPower.Loss (%f) must be > 0. Using 1 instead.", rate_values[RATE_POWER_RUNICPOWER_LOSS]);
         rate_values[RATE_POWER_RUNICPOWER_LOSS] = 1;
     }
     rate_values[RATE_POWER_FOCUS]                 = sConfigMgr->GetOption<float>("Rate.Focus", 1.0f);
     rate_values[RATE_POWER_ENERGY]                = sConfigMgr->GetOption<float>("Rate.Energy", 1.0f);
     rate_values[RATE_SKILL_DISCOVERY]             = sConfigMgr->GetOption<float>("Rate.Skill.Discovery", 1.0f);
     rate_values[RATE_DROP_ITEM_POOR]              = sConfigMgr->GetOption<float>("Rate.Drop.Item.Poor", 1.0f);
     rate_values[RATE_DROP_ITEM_NORMAL]            = sConfigMgr->GetOption<float>("Rate.Drop.Item.Normal", 1.0f);
     rate_values[RATE_DROP_ITEM_UNCOMMON]          = sConfigMgr->GetOption<float>("Rate.Drop.Item.Uncommon", 1.0f);
     rate_values[RATE_DROP_ITEM_RARE]              = sConfigMgr->GetOption<float>("Rate.Drop.Item.Rare", 1.0f);
     rate_values[RATE_DROP_ITEM_EPIC]              = sConfigMgr->GetOption<float>("Rate.Drop.Item.Epic", 1.0f);
     rate_values[RATE_DROP_ITEM_LEGENDARY]         = sConfigMgr->GetOption<float>("Rate.Drop.Item.Legendary", 1.0f);
     rate_values[RATE_DROP_ITEM_ARTIFACT]          = sConfigMgr->GetOption<float>("Rate.Drop.Item.Artifact", 1.0f);
     rate_values[RATE_DROP_ITEM_REFERENCED]        = sConfigMgr->GetOption<float>("Rate.Drop.Item.Referenced", 1.0f);
     rate_values[RATE_DROP_ITEM_REFERENCED_AMOUNT] = sConfigMgr->GetOption<float>("Rate.Drop.Item.ReferencedAmount", 1.0f);
     rate_values[RATE_DROP_MONEY]                  = sConfigMgr->GetOption<float>("Rate.Drop.Money", 1.0f);
     rate_values[RATE_REWARD_BONUS_MONEY]          = sConfigMgr->GetOption<float>("Rate.RewardBonusMoney", 1.0f);
     rate_values[RATE_XP_KILL]                     = sConfigMgr->GetOption<float>("Rate.XP.Kill", 1.0f);
     rate_values[RATE_XP_BG_KILL]                  = sConfigMgr->GetOption<float>("Rate.XP.BattlegroundKill", 1.0f);
     rate_values[RATE_XP_QUEST]                    = sConfigMgr->GetOption<float>("Rate.XP.Quest", 1.0f);
     rate_values[RATE_XP_EXPLORE]                  = sConfigMgr->GetOption<float>("Rate.XP.Explore", 1.0f);
     rate_values[RATE_XP_PET]                      = sConfigMgr->GetOption<float>("Rate.XP.Pet", 1.0f);
     rate_values[RATE_XP_PET_NEXT_LEVEL]           = sConfigMgr->GetOption<float>("Rate.Pet.LevelXP", 0.05f);
     rate_values[RATE_REPAIRCOST]                  = sConfigMgr->GetOption<float>("Rate.RepairCost", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_POOR]         = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Poor", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_NORMAL]       = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Normal", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_UNCOMMON]     = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Uncommon", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_RARE]         = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Rare", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_EPIC]         = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Epic", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_LEGENDARY]    = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Legendary", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_ARTIFACT]     = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Artifact", 1.0f);
     rate_values[RATE_SELLVALUE_ITEM_HEIRLOOM]     = sConfigMgr->GetOption<float>("Rate.SellValue.Item.Heirloom", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_POOR]         = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Poor", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_NORMAL]       = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Normal", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_UNCOMMON]     = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Uncommon", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_RARE]         = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Rare", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_EPIC]         = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Epic", 1.0f);
     rate_values[ RATE_BUYVALUE_ITEM_LEGENDARY]    = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Legendary", 1.0f);
     rate_values[RATE_BUYVALUE_ITEM_ARTIFACT]      = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Artifact", 1.0f);
     rate_values[RATE_BUYVALUE_ITEM_HEIRLOOM]      = sConfigMgr->GetOption<float>("Rate.BuyValue.Item.Heirloom", 1.0f);
     if (rate_values[RATE_REPAIRCOST] < 0.0f)
     {
         LOG_ERROR("server.loading", "Rate.RepairCost (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_REPAIRCOST]);
         rate_values[RATE_REPAIRCOST] = 0.0f;
     }
     rate_values[RATE_REPUTATION_GAIN]                      = sConfigMgr->GetOption<float>("Rate.Reputation.Gain", 1.0f);
     rate_values[RATE_REPUTATION_LOWLEVEL_KILL]             = sConfigMgr->GetOption<float>("Rate.Reputation.LowLevel.Kill", 1.0f);
     rate_values[RATE_REPUTATION_LOWLEVEL_QUEST]            = sConfigMgr->GetOption<float>("Rate.Reputation.LowLevel.Quest", 1.0f);
     rate_values[RATE_REPUTATION_RECRUIT_A_FRIEND_BONUS]    = sConfigMgr->GetOption<float>("Rate.Reputation.RecruitAFriendBonus", 0.1f);
     rate_values[RATE_CREATURE_NORMAL_DAMAGE]               = sConfigMgr->GetOption<float>("Rate.Creature.Normal.Damage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_ELITE_DAMAGE]          = sConfigMgr->GetOption<float>("Rate.Creature.Elite.Elite.Damage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RAREELITE_DAMAGE]      = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RAREELITE.Damage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE]      = sConfigMgr->GetOption<float>("Rate.Creature.Elite.WORLDBOSS.Damage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RARE_DAMAGE]           = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RARE.Damage", 1.0f);
     rate_values[RATE_CREATURE_NORMAL_HP]                   = sConfigMgr->GetOption<float>("Rate.Creature.Normal.HP", 1.0f);
     rate_values[RATE_CREATURE_ELITE_ELITE_HP]              = sConfigMgr->GetOption<float>("Rate.Creature.Elite.Elite.HP", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RAREELITE_HP]          = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RAREELITE.HP", 1.0f);
     rate_values[RATE_CREATURE_ELITE_WORLDBOSS_HP]          = sConfigMgr->GetOption<float>("Rate.Creature.Elite.WORLDBOSS.HP", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RARE_HP]               = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RARE.HP", 1.0f);
     rate_values[RATE_CREATURE_NORMAL_SPELLDAMAGE]          = sConfigMgr->GetOption<float>("Rate.Creature.Normal.SpellDamage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE]     = sConfigMgr->GetOption<float>("Rate.Creature.Elite.Elite.SpellDamage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE] = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RAREELITE.SpellDamage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE] = sConfigMgr->GetOption<float>("Rate.Creature.Elite.WORLDBOSS.SpellDamage", 1.0f);
     rate_values[RATE_CREATURE_ELITE_RARE_SPELLDAMAGE]      = sConfigMgr->GetOption<float>("Rate.Creature.Elite.RARE.SpellDamage", 1.0f);
     rate_values[RATE_CREATURE_AGGRO]                       = sConfigMgr->GetOption<float>("Rate.Creature.Aggro", 1.0f);
     rate_values[RATE_REST_INGAME]                          = sConfigMgr->GetOption<float>("Rate.Rest.InGame", 1.0f);
     rate_values[RATE_REST_OFFLINE_IN_TAVERN_OR_CITY]       = sConfigMgr->GetOption<float>("Rate.Rest.Offline.InTavernOrCity", 1.0f);
     rate_values[RATE_REST_OFFLINE_IN_WILDERNESS]           = sConfigMgr->GetOption<float>("Rate.Rest.Offline.InWilderness", 1.0f);
     rate_values[RATE_DAMAGE_FALL]                          = sConfigMgr->GetOption<float>("Rate.Damage.Fall", 1.0f);
     rate_values[RATE_AUCTION_TIME]                         = sConfigMgr->GetOption<float>("Rate.Auction.Time", 1.0f);
     rate_values[RATE_AUCTION_DEPOSIT]                      = sConfigMgr->GetOption<float>("Rate.Auction.Deposit", 1.0f);
     rate_values[RATE_AUCTION_CUT]                          = sConfigMgr->GetOption<float>("Rate.Auction.Cut", 1.0f);
     rate_values[RATE_HONOR]                                = sConfigMgr->GetOption<float>("Rate.Honor", 1.0f);
     rate_values[RATE_ARENA_POINTS]                         = sConfigMgr->GetOption<float>("Rate.ArenaPoints", 1.0f);
     rate_values[RATE_INSTANCE_RESET_TIME]                  = sConfigMgr->GetOption<float>("Rate.InstanceResetTime", 1.0f);
     rate_values[RATE_TALENT]                               = sConfigMgr->GetOption<float>("Rate.Talent", 1.0f);
     if (rate_values[RATE_TALENT] < 0.0f)
     {
         LOG_ERROR("server.loading", "Rate.Talent (%f) must be > 0. Using 1 instead.", rate_values[RATE_TALENT]);
         rate_values[RATE_TALENT] = 1.0f;
     }
     rate_values[RATE_MOVESPEED] = sConfigMgr->GetOption<float>("Rate.MoveSpeed", 1.0f);
     if (rate_values[RATE_MOVESPEED] < 0)
     {
         LOG_ERROR("server.loading", "Rate.MoveSpeed (%f) must be > 0. Using 1 instead.", rate_values[RATE_MOVESPEED]);
         rate_values[RATE_MOVESPEED] = 1.0f;
     }
     for (uint8 i = 0; i < MAX_MOVE_TYPE; ++i) playerBaseMoveSpeed[i] = baseMoveSpeed[i] * rate_values[RATE_MOVESPEED];
     rate_values[RATE_CORPSE_DECAY_LOOTED] = sConfigMgr->GetOption<float>("Rate.Corpse.Decay.Looted", 0.5f);
     rate_values[RATE_TARGET_POS_RECALCULATION_RANGE] = sConfigMgr->GetOption<float>("TargetPosRecalculateRange", 1.5f);
     if (rate_values[RATE_TARGET_POS_RECALCULATION_RANGE] < CONTACT_DISTANCE)
     {
         LOG_ERROR("server.loading", "TargetPosRecalculateRange (%f) must be >= %f. Using %f instead.", rate_values[RATE_TARGET_POS_RECALCULATION_RANGE], CONTACT_DISTANCE, CONTACT_DISTANCE);
         rate_values[RATE_TARGET_POS_RECALCULATION_RANGE] = CONTACT_DISTANCE;
     }
     else if (rate_values[RATE_TARGET_POS_RECALCULATION_RANGE] > NOMINAL_MELEE_RANGE)
     {
         LOG_ERROR("server.loading", "TargetPosRecalculateRange (%f) must be <= %f. Using %f instead.",
                        rate_values[RATE_TARGET_POS_RECALCULATION_RANGE], NOMINAL_MELEE_RANGE, NOMINAL_MELEE_RANGE);
         rate_values[RATE_TARGET_POS_RECALCULATION_RANGE] = NOMINAL_MELEE_RANGE;
     }
     rate_values[RATE_DURABILITY_LOSS_ON_DEATH]  = sConfigMgr->GetOption<float>("DurabilityLoss.OnDeath", 10.0f);
     if (rate_values[RATE_DURABILITY_LOSS_ON_DEATH] < 0.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLoss.OnDeath (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_DURABILITY_LOSS_ON_DEATH]);
         rate_values[RATE_DURABILITY_LOSS_ON_DEATH] = 0.0f;
     }
     if (rate_values[RATE_DURABILITY_LOSS_ON_DEATH] > 100.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLoss.OnDeath (%f) must be <= 100. Using 100.0 instead.", rate_values[RATE_DURABILITY_LOSS_ON_DEATH]);
         rate_values[RATE_DURABILITY_LOSS_ON_DEATH] = 0.0f;
     }
     rate_values[RATE_DURABILITY_LOSS_ON_DEATH] = rate_values[RATE_DURABILITY_LOSS_ON_DEATH] / 100.0f;
     rate_values[RATE_DURABILITY_LOSS_DAMAGE] = sConfigMgr->GetOption<float>("DurabilityLossChance.Damage", 0.5f);
     if (rate_values[RATE_DURABILITY_LOSS_DAMAGE] < 0.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLossChance.Damage (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_DURABILITY_LOSS_DAMAGE]);
         rate_values[RATE_DURABILITY_LOSS_DAMAGE] = 0.0f;
     }
     rate_values[RATE_DURABILITY_LOSS_ABSORB] = sConfigMgr->GetOption<float>("DurabilityLossChance.Absorb", 0.5f);
     if (rate_values[RATE_DURABILITY_LOSS_ABSORB] < 0.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLossChance.Absorb (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_DURABILITY_LOSS_ABSORB]);
         rate_values[RATE_DURABILITY_LOSS_ABSORB] = 0.0f;
     }
     rate_values[RATE_DURABILITY_LOSS_PARRY] = sConfigMgr->GetOption<float>("DurabilityLossChance.Parry", 0.05f);
     if (rate_values[RATE_DURABILITY_LOSS_PARRY] < 0.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLossChance.Parry (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_DURABILITY_LOSS_PARRY]);
         rate_values[RATE_DURABILITY_LOSS_PARRY] = 0.0f;
     }
     rate_values[RATE_DURABILITY_LOSS_BLOCK] = sConfigMgr->GetOption<float>("DurabilityLossChance.Block", 0.05f);
     if (rate_values[RATE_DURABILITY_LOSS_BLOCK] < 0.0f)
     {
         LOG_ERROR("server.loading", "DurabilityLossChance.Block (%f) must be >=0. Using 0.0 instead.", rate_values[RATE_DURABILITY_LOSS_BLOCK]);
         rate_values[RATE_DURABILITY_LOSS_BLOCK] = 0.0f;
     }
     m_bool_configs[CONFIG_DURABILITY_LOSS_IN_PVP] = sConfigMgr->GetOption<bool>("DurabilityLoss.InPvP", false);
     m_int_configs[CONFIG_COMPRESSION] = sConfigMgr->GetOption<int32>("Compression", 1);
     if (m_int_configs[CONFIG_COMPRESSION] < 1 || m_int_configs[CONFIG_COMPRESSION] > 9)
     {
         LOG_ERROR("server.loading", "Compression level (%u) must be in range 1..9. Using default compression level (1).", m_int_configs[CONFIG_COMPRESSION]);
         m_int_configs[CONFIG_COMPRESSION] = 1;
     }
     m_bool_configs[CONFIG_ADDON_CHANNEL]                   = sConfigMgr->GetOption<bool>("AddonChannel", true);
     m_bool_configs[CONFIG_CLEAN_CHARACTER_DB]              = sConfigMgr->GetOption<bool>("CleanCharacterDB", false);
     m_int_configs[CONFIG_PERSISTENT_CHARACTER_CLEAN_FLAGS] = sConfigMgr->GetOption<int32>("PersistentCharacterCleanFlags", 0);
     m_int_configs[CONFIG_CHAT_CHANNEL_LEVEL_REQ]           = sConfigMgr->GetOption<int32>("ChatLevelReq.Channel", 1);
     m_int_configs[CONFIG_CHAT_WHISPER_LEVEL_REQ]           = sConfigMgr->GetOption<int32>("ChatLevelReq.Whisper", 1);
     m_int_configs[CONFIG_CHAT_SAY_LEVEL_REQ]               = sConfigMgr->GetOption<int32>("ChatLevelReq.Say", 1);
     m_int_configs[CONFIG_PARTY_LEVEL_REQ]                  = sConfigMgr->GetOption<int32>("PartyLevelReq", 1);
     m_int_configs[CONFIG_TRADE_LEVEL_REQ]                  = sConfigMgr->GetOption<int32>("LevelReq.Trade", 1);
     m_int_configs[CONFIG_TICKET_LEVEL_REQ]                 = sConfigMgr->GetOption<int32>("LevelReq.Ticket", 1);
     m_int_configs[CONFIG_AUCTION_LEVEL_REQ]                = sConfigMgr->GetOption<int32>("LevelReq.Auction", 1);
     m_int_configs[CONFIG_MAIL_LEVEL_REQ]                   = sConfigMgr->GetOption<int32>("LevelReq.Mail", 1);
     m_bool_configs[CONFIG_ALLOW_PLAYER_COMMANDS]           = sConfigMgr->GetOption<bool>("AllowPlayerCommands", 1);
     m_bool_configs[CONFIG_PRESERVE_CUSTOM_CHANNELS]        = sConfigMgr->GetOption<bool>("PreserveCustomChannels", false);
     m_int_configs[CONFIG_PRESERVE_CUSTOM_CHANNEL_DURATION] = sConfigMgr->GetOption<int32>("PreserveCustomChannelDuration", 14);
     m_int_configs[CONFIG_INTERVAL_SAVE]                    = sConfigMgr->GetOption<int32>("PlayerSaveInterval", 15 * MINUTE * IN_MILLISECONDS);
     m_int_configs[CONFIG_INTERVAL_DISCONNECT_TOLERANCE]    = sConfigMgr->GetOption<int32>("DisconnectToleranceInterval", 0);
     m_bool_configs[CONFIG_STATS_SAVE_ONLY_ON_LOGOUT]       = sConfigMgr->GetOption<bool>("PlayerSave.Stats.SaveOnlyOnLogout", true);
     m_int_configs[CONFIG_MIN_LEVEL_STAT_SAVE] = sConfigMgr->GetOption<int32>("PlayerSave.Stats.MinLevel", 0);
     if (m_int_configs[CONFIG_MIN_LEVEL_STAT_SAVE] > MAX_LEVEL || int32(m_int_configs[CONFIG_MIN_LEVEL_STAT_SAVE]) < 0)
     {
         LOG_ERROR("server.loading", "PlayerSave.Stats.MinLevel (%i) must be in range 0..80. Using default, do not save character stats (0).", m_int_configs[CONFIG_MIN_LEVEL_STAT_SAVE]);
         m_int_configs[CONFIG_MIN_LEVEL_STAT_SAVE] = 0;
     }
     m_int_configs[CONFIG_INTERVAL_MAPUPDATE] = sConfigMgr->GetOption<int32>("MapUpdateInterval", 100);
     if (m_int_configs[CONFIG_INTERVAL_MAPUPDATE] < MIN_MAP_UPDATE_DELAY)
     {
         LOG_ERROR("server.loading", "MapUpdateInterval (%i) must be greater %u. Use this minimal value.", m_int_configs[CONFIG_INTERVAL_MAPUPDATE], MIN_MAP_UPDATE_DELAY);
         m_int_configs[CONFIG_INTERVAL_MAPUPDATE] = MIN_MAP_UPDATE_DELAY;
     }
     if (reload)
         sMapMgr->SetMapUpdateInterval(m_int_configs[CONFIG_INTERVAL_MAPUPDATE]);
     m_int_configs[CONFIG_INTERVAL_CHANGEWEATHER] = sConfigMgr->GetOption<int32>("ChangeWeatherInterval", 10 * MINUTE * IN_MILLISECONDS);
     if (reload)
     {
         uint32 val = sConfigMgr->GetOption<int32>("WorldServerPort", 8085);
         if (val != m_int_configs[CONFIG_PORT_WORLD])
             LOG_ERROR("server.loading", "WorldServerPort option can't be changed at worldserver.conf reload, using current value (%u).", m_int_configs[CONFIG_PORT_WORLD]);
     }
     else
         m_int_configs[CONFIG_PORT_WORLD] = sConfigMgr->GetOption<int32>("WorldServerPort", 8085);
     m_bool_configs[CONFIG_CLOSE_IDLE_CONNECTIONS]   = sConfigMgr->GetOption<bool>("CloseIdleConnections", true);
     m_int_configs[CONFIG_SOCKET_TIMEOUTTIME]        = sConfigMgr->GetOption<int32>("SocketTimeOutTime", 900000);
     m_int_configs[CONFIG_SOCKET_TIMEOUTTIME_ACTIVE] = sConfigMgr->GetOption<int32>("SocketTimeOutTimeActive", 60000);
     m_int_configs[CONFIG_SESSION_ADD_DELAY]         = sConfigMgr->GetOption<int32>("SessionAddDelay", 10000);
     m_float_configs[CONFIG_GROUP_XP_DISTANCE]             = sConfigMgr->GetOption<float>("MaxGroupXPDistance", 74.0f);
     m_float_configs[CONFIG_MAX_RECRUIT_A_FRIEND_DISTANCE] = sConfigMgr->GetOption<float>("MaxRecruitAFriendBonusDistance", 100.0f);
     m_float_configs[CONFIG_SIGHT_MONSTER] = sConfigMgr->GetOption<float>("MonsterSight", 50);
     if (reload)
     {
         uint32 val = sConfigMgr->GetOption<int32>("GameType", 0);
         if (val != m_int_configs[CONFIG_GAME_TYPE])
             LOG_ERROR("server.loading", "GameType option can't be changed at worldserver.conf reload, using current value (%u).", m_int_configs[CONFIG_GAME_TYPE]);
     }
     else
         m_int_configs[CONFIG_GAME_TYPE] = sConfigMgr->GetOption<int32>("GameType", 0);
     if (reload)
     {
         uint32 val = sConfigMgr->GetOption<int32>("RealmZone", REALM_ZONE_DEVELOPMENT);
         if (val != m_int_configs[CONFIG_REALM_ZONE])
             LOG_ERROR("server.loading", "RealmZone option can't be changed at worldserver.conf reload, using current value (%u).", m_int_configs[CONFIG_REALM_ZONE]);
     }
     else
         m_int_configs[CONFIG_REALM_ZONE] = sConfigMgr->GetOption<int32>("RealmZone", REALM_ZONE_DEVELOPMENT);
     m_int_configs[CONFIG_STRICT_PLAYER_NAMES]                  = sConfigMgr->GetOption<int32> ("StrictPlayerNames",  0);
     m_int_configs[CONFIG_STRICT_CHARTER_NAMES]                 = sConfigMgr->GetOption<int32> ("StrictCharterNames", 0);
     m_int_configs[CONFIG_STRICT_CHANNEL_NAMES]                 = sConfigMgr->GetOption<int32> ("StrictChannelNames", 0);
     m_int_configs[CONFIG_STRICT_PET_NAMES]                     = sConfigMgr->GetOption<int32> ("StrictPetNames",     0);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_ACCOUNTS]             = sConfigMgr->GetOption<bool>("AllowTwoSide.Accounts", true);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_CALENDAR] = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Calendar", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHAT]     = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Chat", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL]  = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Channel", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP]    = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Group", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD]    = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Guild", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION]  = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Auction", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_MAIL]     = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Mail", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_WHO_LIST]             = sConfigMgr->GetOption<bool>("AllowTwoSide.WhoList", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_ADD_FRIEND]           = sConfigMgr->GetOption<bool>("AllowTwoSide.AddFriend", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_TRADE]                = sConfigMgr->GetOption<bool>("AllowTwoSide.Trade", false);
     m_bool_configs[CONFIG_ALLOW_TWO_SIDE_INTERACTION_EMOTE]    = sConfigMgr->GetOption<bool>("AllowTwoSide.Interaction.Emote", false);
     m_int_configs[CONFIG_MIN_PLAYER_NAME] = sConfigMgr->GetOption<int32> ("MinPlayerName",  2);
     if (m_int_configs[CONFIG_MIN_PLAYER_NAME] < 1 || m_int_configs[CONFIG_MIN_PLAYER_NAME] > MAX_PLAYER_NAME)
     {
         LOG_ERROR("server.loading", "MinPlayerName (%i) must be in range 1..%u. Set to 2.", m_int_configs[CONFIG_MIN_PLAYER_NAME], MAX_PLAYER_NAME);
         m_int_configs[CONFIG_MIN_PLAYER_NAME] = 2;
     }
     m_int_configs[CONFIG_MIN_CHARTER_NAME] = sConfigMgr->GetOption<int32> ("MinCharterName", 2);
     if (m_int_configs[CONFIG_MIN_CHARTER_NAME] < 1 || m_int_configs[CONFIG_MIN_CHARTER_NAME] > MAX_CHARTER_NAME)
     {
         LOG_ERROR("server.loading", "MinCharterName (%i) must be in range 1..%u. Set to 2.", m_int_configs[CONFIG_MIN_CHARTER_NAME], MAX_CHARTER_NAME);
         m_int_configs[CONFIG_MIN_CHARTER_NAME] = 2;
     }
     m_int_configs[CONFIG_MIN_PET_NAME] = sConfigMgr->GetOption<int32> ("MinPetName",     2);
     if (m_int_configs[CONFIG_MIN_PET_NAME] < 1 || m_int_configs[CONFIG_MIN_PET_NAME] > MAX_PET_NAME)
     {
         LOG_ERROR("server.loading", "MinPetName (%i) must be in range 1..%u. Set to 2.", m_int_configs[CONFIG_MIN_PET_NAME], MAX_PET_NAME);
         m_int_configs[CONFIG_MIN_PET_NAME] = 2;
     }
     m_int_configs[CONFIG_CHARTER_COST_GUILD]     = sConfigMgr->GetOption<int32>("Guild.CharterCost", 1000);
     m_int_configs[CONFIG_CHARTER_COST_ARENA_2v2] = sConfigMgr->GetOption<int32>("ArenaTeam.CharterCost.2v2", 800000);
     m_int_configs[CONFIG_CHARTER_COST_ARENA_3v3] = sConfigMgr->GetOption<int32>("ArenaTeam.CharterCost.3v3", 1200000);
     m_int_configs[CONFIG_CHARTER_COST_ARENA_5v5] = sConfigMgr->GetOption<int32>("ArenaTeam.CharterCost.5v5", 2000000);
     m_int_configs[CONFIG_MAX_WHO_LIST_RETURN] = sConfigMgr->GetOption<int32>("MaxWhoListReturns", 49);
     m_int_configs[CONFIG_CHARACTER_CREATING_DISABLED]           = sConfigMgr->GetOption<int32>("CharacterCreating.Disabled", 0);
     m_int_configs[CONFIG_CHARACTER_CREATING_DISABLED_RACEMASK]  = sConfigMgr->GetOption<int32>("CharacterCreating.Disabled.RaceMask", 0);
     m_int_configs[CONFIG_CHARACTER_CREATING_DISABLED_CLASSMASK] = sConfigMgr->GetOption<int32>("CharacterCreating.Disabled.ClassMask", 0);
     m_int_configs[CONFIG_CHARACTERS_PER_REALM] = sConfigMgr->GetOption<int32>("CharactersPerRealm", 10);
     if (m_int_configs[CONFIG_CHARACTERS_PER_REALM] < 1 || m_int_configs[CONFIG_CHARACTERS_PER_REALM] > 10)
     {
         LOG_ERROR("server.loading", "CharactersPerRealm (%i) must be in range 1..10. Set to 10.", m_int_configs[CONFIG_CHARACTERS_PER_REALM]);
         m_int_configs[CONFIG_CHARACTERS_PER_REALM] = 10;
     }
     // must be after CONFIG_CHARACTERS_PER_REALM
     m_int_configs[CONFIG_CHARACTERS_PER_ACCOUNT] = sConfigMgr->GetOption<int32>("CharactersPerAccount", 50);
     if (m_int_configs[CONFIG_CHARACTERS_PER_ACCOUNT] < m_int_configs[CONFIG_CHARACTERS_PER_REALM])
     {
         LOG_ERROR("server.loading", "CharactersPerAccount (%i) can't be less than CharactersPerRealm (%i).", m_int_configs[CONFIG_CHARACTERS_PER_ACCOUNT], m_int_configs[CONFIG_CHARACTERS_PER_REALM]);
         m_int_configs[CONFIG_CHARACTERS_PER_ACCOUNT] = m_int_configs[CONFIG_CHARACTERS_PER_REALM];
     }
     m_int_configs[CONFIG_HEROIC_CHARACTERS_PER_REALM] = sConfigMgr->GetOption<int32>("HeroicCharactersPerRealm", 1);
     if (int32(m_int_configs[CONFIG_HEROIC_CHARACTERS_PER_REALM]) < 0 || m_int_configs[CONFIG_HEROIC_CHARACTERS_PER_REALM] > 10)
     {
         LOG_ERROR("server.loading", "HeroicCharactersPerRealm (%i) must be in range 0..10. Set to 1.", m_int_configs[CONFIG_HEROIC_CHARACTERS_PER_REALM]);
         m_int_configs[CONFIG_HEROIC_CHARACTERS_PER_REALM] = 1;
     }
     m_int_configs[CONFIG_CHARACTER_CREATING_MIN_LEVEL_FOR_HEROIC_CHARACTER] = sConfigMgr->GetOption<int32>("CharacterCreating.MinLevelForHeroicCharacter", 55);
     m_int_configs[CONFIG_SKIP_CINEMATICS] = sConfigMgr->GetOption<int32>("SkipCinematics", 0);
     if (int32(m_int_configs[CONFIG_SKIP_CINEMATICS]) < 0 || m_int_configs[CONFIG_SKIP_CINEMATICS] > 2)
     {
         LOG_ERROR("server.loading", "SkipCinematics (%i) must be in range 0..2. Set to 0.", m_int_configs[CONFIG_SKIP_CINEMATICS]);
         m_int_configs[CONFIG_SKIP_CINEMATICS] = 0;
     }
     if (reload)
     {
         uint32 val = sConfigMgr->GetOption<int32>("MaxPlayerLevel", DEFAULT_MAX_LEVEL);
         if (val != m_int_configs[CONFIG_MAX_PLAYER_LEVEL])
             LOG_ERROR("server.loading", "MaxPlayerLevel option can't be changed at config reload, using current value (%u).", m_int_configs[CONFIG_MAX_PLAYER_LEVEL]);
     }
     else
         m_int_configs[CONFIG_MAX_PLAYER_LEVEL] = sConfigMgr->GetOption<int32>("MaxPlayerLevel", DEFAULT_MAX_LEVEL);
     if (m_int_configs[CONFIG_MAX_PLAYER_LEVEL] > MAX_LEVEL || m_int_configs[CONFIG_MAX_PLAYER_LEVEL] < 1)
     {
         LOG_ERROR("server.loading", "MaxPlayerLevel (%i) must be in range 1..%u. Set to %u.", m_int_configs[CONFIG_MAX_PLAYER_LEVEL], MAX_LEVEL, MAX_LEVEL);
         m_int_configs[CONFIG_MAX_PLAYER_LEVEL] = MAX_LEVEL;
     }
     m_int_configs[CONFIG_MIN_DUALSPEC_LEVEL] = sConfigMgr->GetOption<int32>("MinDualSpecLevel", 40);
     m_int_configs[CONFIG_START_PLAYER_LEVEL] = sConfigMgr->GetOption<int32>("StartPlayerLevel", 1);
     if (m_int_configs[CONFIG_START_PLAYER_LEVEL] < 1 || m_int_configs[CONFIG_START_PLAYER_LEVEL] > m_int_configs[CONFIG_MAX_PLAYER_LEVEL])
     {
         LOG_ERROR("server.loading", "StartPlayerLevel (%i) must be in range 1..MaxPlayerLevel(%u). Set to 1.", m_int_configs[CONFIG_START_PLAYER_LEVEL], m_int_configs[CONFIG_MAX_PLAYER_LEVEL]);
         m_int_configs[CONFIG_START_PLAYER_LEVEL] = 1;
     }
     m_int_configs[CONFIG_START_HEROIC_PLAYER_LEVEL] = sConfigMgr->GetOption<int32>("StartHeroicPlayerLevel", 55);
     if (m_int_configs[CONFIG_START_HEROIC_PLAYER_LEVEL] < 1 || m_int_configs[CONFIG_START_HEROIC_PLAYER_LEVEL] > m_int_configs[CONFIG_MAX_PLAYER_LEVEL])
     {
         LOG_ERROR("server.loading", "StartHeroicPlayerLevel (%i) must be in range 1..MaxPlayerLevel(%u). Set to 55.",
                        m_int_configs[CONFIG_START_HEROIC_PLAYER_LEVEL], m_int_configs[CONFIG_MAX_PLAYER_LEVEL]);
         m_int_configs[CONFIG_START_HEROIC_PLAYER_LEVEL] = 55;
     }
     m_int_configs[CONFIG_START_PLAYER_MONEY] = sConfigMgr->GetOption<int32>("StartPlayerMoney", 0);
     if (int32(m_int_configs[CONFIG_START_PLAYER_MONEY]) < 0 || int32(m_int_configs[CONFIG_START_PLAYER_MONEY]) > MAX_MONEY_AMOUNT)
     {
         LOG_ERROR("server.loading", "StartPlayerMoney (%i) must be in range 0..%u. Set to %u.", m_int_configs[CONFIG_START_PLAYER_MONEY], MAX_MONEY_AMOUNT, 0);
         m_int_configs[CONFIG_START_PLAYER_MONEY] = 0;
     }
     m_int_configs[CONFIG_MAX_HONOR_POINTS] = sConfigMgr->GetOption<int32>("MaxHonorPoints", 75000);
     if (int32(m_int_configs[CONFIG_MAX_HONOR_POINTS]) < 0)
     {
         LOG_ERROR("server.loading", "MaxHonorPoints (%i) can't be negative. Set to 0.", m_int_configs[CONFIG_MAX_HONOR_POINTS]);
         m_int_configs[CONFIG_MAX_HONOR_POINTS] = 0;
     }
     m_int_configs[CONFIG_START_HONOR_POINTS] = sConfigMgr->GetOption<int32>("StartHonorPoints", 0);
     if (int32(m_int_configs[CONFIG_START_HONOR_POINTS]) < 0 || int32(m_int_configs[CONFIG_START_HONOR_POINTS]) > int32(m_int_configs[CONFIG_MAX_HONOR_POINTS]))
     {
         LOG_ERROR("server.loading", "StartHonorPoints (%i) must be in range 0..MaxHonorPoints(%u). Set to %u.",
                        m_int_configs[CONFIG_START_HONOR_POINTS], m_int_configs[CONFIG_MAX_HONOR_POINTS], 0);
         m_int_configs[CONFIG_START_HONOR_POINTS] = 0;
     }
     m_int_configs[CONFIG_MAX_ARENA_POINTS] = sConfigMgr->GetOption<int32>("MaxArenaPoints", 10000);
     if (int32(m_int_configs[CONFIG_MAX_ARENA_POINTS]) < 0)
     {
         LOG_ERROR("server.loading", "MaxArenaPoints (%i) can't be negative. Set to 0.", m_int_configs[CONFIG_MAX_ARENA_POINTS]);
         m_int_configs[CONFIG_MAX_ARENA_POINTS] = 0;
     }
     m_int_configs[CONFIG_START_ARENA_POINTS] = sConfigMgr->GetOption<int32>("StartArenaPoints", 0);
     if (int32(m_int_configs[CONFIG_START_ARENA_POINTS]) < 0 || int32(m_int_configs[CONFIG_START_ARENA_POINTS]) > int32(m_int_configs[CONFIG_MAX_ARENA_POINTS]))
     {
         LOG_ERROR("server.loading", "StartArenaPoints (%i) must be in range 0..MaxArenaPoints(%u). Set to %u.",
                        m_int_configs[CONFIG_START_ARENA_POINTS], m_int_configs[CONFIG_MAX_ARENA_POINTS], 0);
         m_int_configs[CONFIG_START_ARENA_POINTS] = 0;
     }
     m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL] = sConfigMgr->GetOption<int32>("RecruitAFriend.MaxLevel", 60);
     if (m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL] > m_int_configs[CONFIG_MAX_PLAYER_LEVEL]
         || int32(m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL]) < 0)
     {
         LOG_ERROR("server.loading", "RecruitAFriend.MaxLevel (%i) must be in the range 0..MaxLevel(%u). Set to %u.",
                        m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL], m_int_configs[CONFIG_MAX_PLAYER_LEVEL], 60);
         m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL] = 60;
     }
     m_int_configs[CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL_DIFFERENCE] = sConfigMgr->GetOption<int32>("RecruitAFriend.MaxDifference", 4);
     m_bool_configs[CONFIG_ALL_TAXI_PATHS] = sConfigMgr->GetOption<bool>("AllFlightPaths", false);
     m_int_configs[CONFIG_INSTANT_TAXI]    = sConfigMgr->GetOption<int32>("InstantFlightPaths", 0);
     m_bool_configs[CONFIG_INSTANCE_IGNORE_LEVEL]    = sConfigMgr->GetOption<bool>("Instance.IgnoreLevel", false);
     m_bool_configs[CONFIG_INSTANCE_IGNORE_RAID]     = sConfigMgr->GetOption<bool>("Instance.IgnoreRaid", false);
     m_bool_configs[CONFIG_INSTANCE_GMSUMMON_PLAYER] = sConfigMgr->GetOption<bool>("Instance.GMSummonPlayer", false);
     m_bool_configs[CONFIG_INSTANCE_SHARED_ID]       = sConfigMgr->GetOption<bool>("Instance.SharedNormalHeroicId", false);
     m_int_configs[CONFIG_INSTANCE_RESET_TIME_HOUR]               = sConfigMgr->GetOption<int32>("Instance.ResetTimeHour", 4);
     m_int_configs[CONFIG_INSTANCE_RESET_TIME_RELATIVE_TIMESTAMP] = sConfigMgr->GetOption<int32>("Instance.ResetTimeRelativeTimestamp", 1135814400);
     m_int_configs[CONFIG_INSTANCE_UNLOAD_DELAY]                  = sConfigMgr->GetOption<int32>("Instance.UnloadDelay", 30 * MINUTE * IN_MILLISECONDS);
     m_int_configs[CONFIG_MAX_PRIMARY_TRADE_SKILL] = sConfigMgr->GetOption<int32>("MaxPrimaryTradeSkill", 2);
     m_int_configs[CONFIG_MIN_PETITION_SIGNS]      = sConfigMgr->GetOption<int32>("MinPetitionSigns", 9);
     if (m_int_configs[CONFIG_MIN_PETITION_SIGNS] > 9 || int32(m_int_configs[CONFIG_MIN_PETITION_SIGNS]) < 0)
     {
         LOG_ERROR("server.loading", "MinPetitionSigns (%i) must be in range 0..9. Set to 9.", m_int_configs[CONFIG_MIN_PETITION_SIGNS]);
         m_int_configs[CONFIG_MIN_PETITION_SIGNS] = 9;
     }
     m_int_configs[CONFIG_GM_LOGIN_STATE]        = sConfigMgr->GetOption<int32>("GM.LoginState", 2);
     m_int_configs[CONFIG_GM_VISIBLE_STATE]      = sConfigMgr->GetOption<int32>("GM.Visible", 2);
     m_int_configs[CONFIG_GM_CHAT]               = sConfigMgr->GetOption<int32>("GM.Chat", 2);
     m_int_configs[CONFIG_GM_WHISPERING_TO]      = sConfigMgr->GetOption<int32>("GM.WhisperingTo", 2);
     m_int_configs[CONFIG_GM_LEVEL_IN_GM_LIST]   = sConfigMgr->GetOption<int32>("GM.InGMList.Level", SEC_ADMINISTRATOR);
     m_int_configs[CONFIG_GM_LEVEL_IN_WHO_LIST]  = sConfigMgr->GetOption<int32>("GM.InWhoList.Level", SEC_ADMINISTRATOR);
     m_int_configs[CONFIG_START_GM_LEVEL]        = sConfigMgr->GetOption<int32>("GM.StartLevel", 1);
     if (m_int_configs[CONFIG_START_GM_LEVEL] < m_int_configs[CONFIG_START_PLAYER_LEVEL])
     {
         LOG_ERROR("server.loading", "GM.StartLevel (%i) must be in range StartPlayerLevel(%u)..%u. Set to %u.",
                        m_int_configs[CONFIG_START_GM_LEVEL], m_int_configs[CONFIG_START_PLAYER_LEVEL], MAX_LEVEL, m_int_configs[CONFIG_START_PLAYER_LEVEL]);
         m_int_configs[CONFIG_START_GM_LEVEL] = m_int_configs[CONFIG_START_PLAYER_LEVEL];
     }
     else if (m_int_configs[CONFIG_START_GM_LEVEL] > MAX_LEVEL)
     {
         LOG_ERROR("server.loading", "GM.StartLevel (%i) must be in range 1..%u. Set to %u.", m_int_configs[CONFIG_START_GM_LEVEL], MAX_LEVEL, MAX_LEVEL);
         m_int_configs[CONFIG_START_GM_LEVEL] = MAX_LEVEL;
     }
     m_bool_configs[CONFIG_ALLOW_GM_GROUP]       = sConfigMgr->GetOption<bool>("GM.AllowInvite", false);
     m_bool_configs[CONFIG_ALLOW_GM_FRIEND]      = sConfigMgr->GetOption<bool>("GM.AllowFriend", false);
     m_bool_configs[CONFIG_GM_LOWER_SECURITY]    = sConfigMgr->GetOption<bool>("GM.LowerSecurity", false);
     m_float_configs[CONFIG_CHANCE_OF_GM_SURVEY] = sConfigMgr->GetOption<float>("GM.TicketSystem.ChanceOfGMSurvey", 50.0f);
     m_int_configs[CONFIG_GROUP_VISIBILITY]      = sConfigMgr->GetOption<int32>("Visibility.GroupMode", 1);
     m_int_configs[CONFIG_MAIL_DELIVERY_DELAY]   = sConfigMgr->GetOption<int32>("MailDeliveryDelay", HOUR);
     m_int_configs[CONFIG_UPTIME_UPDATE]         = sConfigMgr->GetOption<int32>("UpdateUptimeInterval", 10);
     if (int32(m_int_configs[CONFIG_UPTIME_UPDATE]) <= 0)
     {
         LOG_ERROR("server.loading", "UpdateUptimeInterval (%i) must be > 0, set to default 10.", m_int_configs[CONFIG_UPTIME_UPDATE]);
         m_int_configs[CONFIG_UPTIME_UPDATE] = 1;
     }
     if (reload)
     {
         m_timers[WUPDATE_UPTIME].SetInterval(m_int_configs[CONFIG_UPTIME_UPDATE]*MINUTE * IN_MILLISECONDS);
         m_timers[WUPDATE_UPTIME].Reset();
     }
     // log db cleanup interval
     m_int_configs[CONFIG_LOGDB_CLEARINTERVAL] = sConfigMgr->GetOption<int32>("LogDB.Opt.ClearInterval", 10);
     if (int32(m_int_configs[CONFIG_LOGDB_CLEARINTERVAL]) <= 0)
     {
         LOG_ERROR("server.loading", "LogDB.Opt.ClearInterval (%i) must be > 0, set to default 10.", m_int_configs[CONFIG_LOGDB_CLEARINTERVAL]);
         m_int_configs[CONFIG_LOGDB_CLEARINTERVAL] = 10;
     }
     if (reload)
     {
         m_timers[WUPDATE_CLEANDB].SetInterval(m_int_configs[CONFIG_LOGDB_CLEARINTERVAL] * MINUTE * IN_MILLISECONDS);
         m_timers[WUPDATE_CLEANDB].Reset();
     }
     m_int_configs[CONFIG_LOGDB_CLEARTIME] = sConfigMgr->GetOption<int32>("LogDB.Opt.ClearTime", 1209600); // 14 days default
     LOG_INFO("server.loading", "Will clear `logs` table of entries older than %i seconds every %u minutes.",
                     m_int_configs[CONFIG_LOGDB_CLEARTIME], m_int_configs[CONFIG_LOGDB_CLEARINTERVAL]);
     m_int_configs[CONFIG_TELEPORT_TIMEOUT_NEAR]             = sConfigMgr->GetOption<int32>("TeleportTimeoutNear", 25); // pussywizard
     m_int_configs[CONFIG_TELEPORT_TIMEOUT_FAR]              = sConfigMgr->GetOption<int32>("TeleportTimeoutFar", 45); // pussywizard
     m_int_configs[CONFIG_MAX_ALLOWED_MMR_DROP]              = sConfigMgr->GetOption<int32>("MaxAllowedMMRDrop", 500); // pussywizard
     m_bool_configs[CONFIG_ENABLE_LOGIN_AFTER_DC]            = sConfigMgr->GetOption<bool>("EnableLoginAfterDC", true); // pussywizard
     m_bool_configs[CONFIG_DONT_CACHE_RANDOM_MOVEMENT_PATHS] = sConfigMgr->GetOption<bool>("DontCacheRandomMovementPaths", true); // pussywizard
     m_int_configs[CONFIG_SKILL_CHANCE_ORANGE] = sConfigMgr->GetOption<int32>("SkillChance.Orange", 100);
     m_int_configs[CONFIG_SKILL_CHANCE_YELLOW] = sConfigMgr->GetOption<int32>("SkillChance.Yellow", 75);
     m_int_configs[CONFIG_SKILL_CHANCE_GREEN]  = sConfigMgr->GetOption<int32>("SkillChance.Green", 25);
     m_int_configs[CONFIG_SKILL_CHANCE_GREY]   = sConfigMgr->GetOption<int32>("SkillChance.Grey", 0);
     m_int_configs[CONFIG_SKILL_CHANCE_MINING_STEPS]     = sConfigMgr->GetOption<int32>("SkillChance.MiningSteps", 75);
     m_int_configs[CONFIG_SKILL_CHANCE_SKINNING_STEPS]   = sConfigMgr->GetOption<int32>("SkillChance.SkinningSteps", 75);
     m_bool_configs[CONFIG_SKILL_PROSPECTING] = sConfigMgr->GetOption<bool>("SkillChance.Prospecting", false);
     m_bool_configs[CONFIG_SKILL_MILLING]     = sConfigMgr->GetOption<bool>("SkillChance.Milling", false);
     m_int_configs[CONFIG_SKILL_GAIN_CRAFTING] = sConfigMgr->GetOption<int32>("SkillGain.Crafting", 1);
     m_int_configs[CONFIG_SKILL_GAIN_DEFENSE] = sConfigMgr->GetOption<int32>("SkillGain.Defense", 1);
     m_int_configs[CONFIG_SKILL_GAIN_GATHERING] = sConfigMgr->GetOption<int32>("SkillGain.Gathering", 1);
     m_int_configs[CONFIG_SKILL_GAIN_WEAPON] = sConfigMgr->GetOption<int32>("SkillGain.Weapon", 1);
     m_int_configs[CONFIG_MAX_OVERSPEED_PINGS] = sConfigMgr->GetOption<int32>("MaxOverspeedPings", 2);
     if (m_int_configs[CONFIG_MAX_OVERSPEED_PINGS] != 0 && m_int_configs[CONFIG_MAX_OVERSPEED_PINGS] < 2)
     {
         LOG_ERROR("server.loading", "MaxOverspeedPings (%i) must be in range 2..infinity (or 0 to disable check). Set to 2.", m_int_configs[CONFIG_MAX_OVERSPEED_PINGS]);
         m_int_configs[CONFIG_MAX_OVERSPEED_PINGS] = 2;
     }
     m_bool_configs[CONFIG_SAVE_RESPAWN_TIME_IMMEDIATELY] = sConfigMgr->GetOption<bool>("SaveRespawnTimeImmediately", true);
     m_bool_configs[CONFIG_WEATHER]                       = sConfigMgr->GetOption<bool>("ActivateWeather", true);
     m_int_configs[CONFIG_DISABLE_BREATHING] = sConfigMgr->GetOption<int32>("DisableWaterBreath", SEC_CONSOLE);
     m_bool_configs[CONFIG_ALWAYS_MAX_SKILL_FOR_LEVEL] = sConfigMgr->GetOption<bool>("AlwaysMaxSkillForLevel", false);
     if (reload)
     {
         uint32 val = sConfigMgr->GetOption<int32>("Expansion", 2);
         if (val != m_int_configs[CONFIG_EXPANSION])
             LOG_ERROR("server.loading", "Expansion option can't be changed at worldserver.conf reload, using current value (%u).", m_int_configs[CONFIG_EXPANSION]);
     }
     else
         m_int_configs[CONFIG_EXPANSION] = sConfigMgr->GetOption<int32>("Expansion", 2);
     m_int_configs[CONFIG_CHATFLOOD_MESSAGE_COUNT]    = sConfigMgr->GetOption<int32>("ChatFlood.MessageCount", 10);
     m_int_configs[CONFIG_CHATFLOOD_MESSAGE_DELAY]    = sConfigMgr->GetOption<int32>("ChatFlood.MessageDelay", 1);
     m_int_configs[CONFIG_CHATFLOOD_MUTE_TIME]        = sConfigMgr->GetOption<int32>("ChatFlood.MuteTime", 10);
     m_bool_configs[CONFIG_CHAT_MUTE_FIRST_LOGIN]     = sConfigMgr->GetOption<bool>("Chat.MuteFirstLogin", false);
     m_int_configs[CONFIG_CHAT_TIME_MUTE_FIRST_LOGIN] = sConfigMgr->GetOption<int32>("Chat.MuteTimeFirstLogin", 120);
     m_int_configs[CONFIG_EVENT_ANNOUNCE] = sConfigMgr->GetOption<int32>("Event.Announce", 0);
     m_float_configs[CONFIG_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS] = sConfigMgr->GetOption<float>("CreatureFamilyFleeAssistanceRadius", 30.0f);
     m_float_configs[CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS]      = sConfigMgr->GetOption<float>("CreatureFamilyAssistanceRadius", 10.0f);
     m_int_configs[CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY]         = sConfigMgr->GetOption<int32>("CreatureFamilyAssistanceDelay", 2000);
     m_int_configs[CONFIG_CREATURE_FAMILY_ASSISTANCE_PERIOD]        = sConfigMgr->GetOption<int32>("CreatureFamilyAssistancePeriod", 3000);
     m_int_configs[CONFIG_CREATURE_FAMILY_FLEE_DELAY]               = sConfigMgr->GetOption<int32>("CreatureFamilyFleeDelay", 7000);
     m_int_configs[CONFIG_WORLD_BOSS_LEVEL_DIFF] = sConfigMgr->GetOption<int32>("WorldBossLevelDiff", 3);
     m_bool_configs[CONFIG_QUEST_ENABLE_QUEST_TRACKER] = sConfigMgr->GetOption<bool>("Quests.EnableQuestTracker", false);
     // note: disable value (-1) will assigned as 0xFFFFFFF, to prevent overflow at calculations limit it to max possible player level MAX_LEVEL(100)
     m_int_configs[CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF] = sConfigMgr->GetOption<int32>("Quests.LowLevelHideDiff", 4);
     if (m_int_configs[CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF] > MAX_LEVEL)
         m_int_configs[CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF] = MAX_LEVEL;
     m_int_configs[CONFIG_QUEST_HIGH_LEVEL_HIDE_DIFF] = sConfigMgr->GetOption<int32>("Quests.HighLevelHideDiff", 7);
     if (m_int_configs[CONFIG_QUEST_HIGH_LEVEL_HIDE_DIFF] > MAX_LEVEL)
         m_int_configs[CONFIG_QUEST_HIGH_LEVEL_HIDE_DIFF] = MAX_LEVEL;
     m_bool_configs[CONFIG_QUEST_IGNORE_RAID]          = sConfigMgr->GetOption<bool>("Quests.IgnoreRaid", false);
     m_bool_configs[CONFIG_QUEST_IGNORE_AUTO_ACCEPT]   = sConfigMgr->GetOption<bool>("Quests.IgnoreAutoAccept", false);
     m_bool_configs[CONFIG_QUEST_IGNORE_AUTO_COMPLETE] = sConfigMgr->GetOption<bool>("Quests.IgnoreAutoComplete", false);
     m_int_configs[CONFIG_RANDOM_BG_RESET_HOUR] = sConfigMgr->GetOption<int32>("Battleground.Random.ResetHour", 6);
     if (m_int_configs[CONFIG_RANDOM_BG_RESET_HOUR] > 23)
     {
         LOG_ERROR("server.loading", "Battleground.Random.ResetHour (%i) can't be load. Set to 6.", m_int_configs[CONFIG_RANDOM_BG_RESET_HOUR]);
         m_int_configs[CONFIG_RANDOM_BG_RESET_HOUR] = 6;
     }
     m_int_configs[CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR] = sConfigMgr->GetOption<int32>("Calendar.DeleteOldEventsHour", 6);
     if (m_int_configs[CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR] > 23 || int32(m_int_configs[CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR]) < 0)
     {
         LOG_ERROR("server.loading", "Calendar.DeleteOldEventsHour (%i) can't be load. Set to 6.", m_int_configs[CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR]);
         m_int_configs[CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR] = 6;
     }
     m_int_configs[CONFIG_GUILD_RESET_HOUR] = sConfigMgr->GetOption<int32>("Guild.ResetHour", 6);
     if (m_int_configs[CONFIG_GUILD_RESET_HOUR] > 23)
     {
         LOG_ERROR("server.loading", "Guild.ResetHour (%i) can't be load. Set to 6.", m_int_configs[CONFIG_GUILD_RESET_HOUR]);
         m_int_configs[CONFIG_GUILD_RESET_HOUR] = 6;
     }
     m_int_configs[CONFIG_GUILD_BANK_INITIAL_TABS] = sConfigMgr->GetOption<int32>("Guild.BankInitialTabs", 0);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_0] = sConfigMgr->GetOption<int32>("Guild.BankTabCost0", 1000000);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_1] = sConfigMgr->GetOption<int32>("Guild.BankTabCost1", 2500000);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_2] = sConfigMgr->GetOption<int32>("Guild.BankTabCost2", 5000000);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_3] = sConfigMgr->GetOption<int32>("Guild.BankTabCost3", 10000000);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_4] = sConfigMgr->GetOption<int32>("Guild.BankTabCost4", 25000000);
     m_int_configs[CONFIG_GUILD_BANK_TAB_COST_5] = sConfigMgr->GetOption<int32>("Guild.BankTabCost5", 50000000);
     m_bool_configs[CONFIG_DETECT_POS_COLLISION] = sConfigMgr->GetOption<bool>("DetectPosCollision", true);
     m_bool_configs[CONFIG_RESTRICTED_LFG_CHANNEL]      = sConfigMgr->GetOption<bool>("Channel.RestrictedLfg", true);
     m_bool_configs[CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL] = sConfigMgr->GetOption<bool>("Channel.SilentlyGMJoin", false);
     m_bool_configs[CONFIG_TALENTS_INSPECTING]                = sConfigMgr->GetOption<bool>("TalentsInspecting", true);
     m_bool_configs[CONFIG_CHAT_FAKE_MESSAGE_PREVENTING]      = sConfigMgr->GetOption<bool>("ChatFakeMessagePreventing", false);
     m_int_configs[CONFIG_CHAT_STRICT_LINK_CHECKING_SEVERITY] = sConfigMgr->GetOption<int32>("ChatStrictLinkChecking.Severity", 0);
     m_int_configs[CONFIG_CHAT_STRICT_LINK_CHECKING_KICK]     = sConfigMgr->GetOption<int32>("ChatStrictLinkChecking.Kick", 0);
     m_int_configs[CONFIG_CORPSE_DECAY_NORMAL]    = sConfigMgr->GetOption<int32>("Corpse.Decay.NORMAL", 60);
     m_int_configs[CONFIG_CORPSE_DECAY_RARE]      = sConfigMgr->GetOption<int32>("Corpse.Decay.RARE", 300);
     m_int_configs[CONFIG_CORPSE_DECAY_ELITE]     = sConfigMgr->GetOption<int32>("Corpse.Decay.ELITE", 300);
     m_int_configs[CONFIG_CORPSE_DECAY_RAREELITE] = sConfigMgr->GetOption<int32>("Corpse.Decay.RAREELITE", 300);
     m_int_configs[CONFIG_CORPSE_DECAY_WORLDBOSS] = sConfigMgr->GetOption<int32>("Corpse.Decay.WORLDBOSS", 3600);
     m_int_configs[CONFIG_DEATH_SICKNESS_LEVEL]            = sConfigMgr->GetOption<int32> ("Death.SicknessLevel", 11);
     m_bool_configs[CONFIG_DEATH_CORPSE_RECLAIM_DELAY_PVP] = sConfigMgr->GetOption<bool>("Death.CorpseReclaimDelay.PvP", true);
     m_bool_configs[CONFIG_DEATH_CORPSE_RECLAIM_DELAY_PVE] = sConfigMgr->GetOption<bool>("Death.CorpseReclaimDelay.PvE", true);
     m_bool_configs[CONFIG_DEATH_BONES_WORLD]              = sConfigMgr->GetOption<bool>("Death.Bones.World", true);
     m_bool_configs[CONFIG_DEATH_BONES_BG_OR_ARENA]        = sConfigMgr->GetOption<bool>("Death.Bones.BattlegroundOrArena", true);
     m_bool_configs[CONFIG_DIE_COMMAND_MODE] = sConfigMgr->GetOption<bool>("Die.Command.Mode", true);
     // always use declined names in the russian client
     m_bool_configs[CONFIG_DECLINED_NAMES_USED] =
         (m_int_configs[CONFIG_REALM_ZONE] == REALM_ZONE_RUSSIAN) ? true : sConfigMgr->GetOption<bool>("DeclinedNames", false);
     m_float_configs[CONFIG_LISTEN_RANGE_SAY]       = sConfigMgr->GetOption<float>("ListenRange.Say", 25.0f);
     m_float_configs[CONFIG_LISTEN_RANGE_TEXTEMOTE] = sConfigMgr->GetOption<float>("ListenRange.TextEmote", 25.0f);
     m_float_configs[CONFIG_LISTEN_RANGE_YELL]      = sConfigMgr->GetOption<float>("ListenRange.Yell", 300.0f);
     m_bool_configs[CONFIG_BATTLEGROUND_DISABLE_QUEST_SHARE_IN_BG]           = sConfigMgr->GetOption<bool>("Battleground.DisableQuestShareInBG", false);
     m_bool_configs[CONFIG_BATTLEGROUND_DISABLE_READY_CHECK_IN_BG]           = sConfigMgr->GetOption<bool>("Battleground.DisableReadyCheckInBG", false);
     m_bool_configs[CONFIG_BATTLEGROUND_CAST_DESERTER]                       = sConfigMgr->GetOption<bool>("Battleground.CastDeserter", true);
     m_bool_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_ENABLE]              = sConfigMgr->GetOption<bool>("Battleground.QueueAnnouncer.Enable", false);
     m_int_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_LEVEL]      = sConfigMgr->GetOption<uint32>("Battleground.QueueAnnouncer.Limit.MinLevel", 0);
     m_int_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_PLAYERS]    = sConfigMgr->GetOption<uint32>("Battleground.QueueAnnouncer.Limit.MinPlayers", 3);
     m_int_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY]           = sConfigMgr->GetOption<uint32>("Battleground.QueueAnnouncer.SpamProtection.Delay", 30);
     m_bool_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_PLAYERONLY]          = sConfigMgr->GetOption<bool>("Battleground.QueueAnnouncer.PlayerOnly", false);
     m_bool_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_TIMED]               = sConfigMgr->GetOption<bool>("Battleground.QueueAnnouncer.Timed", false);
     m_int_configs[CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_TIMER]                = sConfigMgr->GetOption<uint32>("Battleground.QueueAnnouncer.Timer", 30000);
     m_bool_configs[CONFIG_BATTLEGROUND_STORE_STATISTICS_ENABLE]             = sConfigMgr->GetOption<bool>("Battleground.StoreStatistics.Enable", false);
     m_bool_configs[CONFIG_BATTLEGROUND_TRACK_DESERTERS]                     = sConfigMgr->GetOption<bool>("Battleground.TrackDeserters.Enable", false);
     m_int_configs[CONFIG_BATTLEGROUND_PREMATURE_FINISH_TIMER]               = sConfigMgr->GetOption<int32> ("Battleground.PrematureFinishTimer", 5 * MINUTE * IN_MILLISECONDS);
     m_int_configs[CONFIG_BATTLEGROUND_INVITATION_TYPE]                      = sConfigMgr->GetOption<int32>("Battleground.InvitationType", 0);
     m_int_configs[CONFIG_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH]         = sConfigMgr->GetOption<int32> ("Battleground.PremadeGroupWaitForMatch", 30 * MINUTE * IN_MILLISECONDS);
     m_bool_configs[CONFIG_BG_XP_FOR_KILL]                                   = sConfigMgr->GetOption<bool>("Battleground.GiveXPForKills", false);
     m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK_TIMER]                     = sConfigMgr->GetOption<int32>("Battleground.ReportAFK.Timer", 4);
     m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK]                           = sConfigMgr->GetOption<int32>("Battleground.ReportAFK", 3);
     if (m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK] < 1)
     {
         LOG_ERROR("server.loading", "Battleground.ReportAFK (%d) must be >0. Using 3 instead.", m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK]);
         m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK] = 3;
     }
     else if (m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK] > 9)
     {
         LOG_ERROR("server.loading", "Battleground.ReportAFK (%d) must be <10. Using 3 instead.", m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK]);
         m_int_configs[CONFIG_BATTLEGROUND_REPORT_AFK] = 3;
     }
     m_int_configs[CONFIG_BATTLEGROUND_PLAYER_RESPAWN]        = sConfigMgr->GetOption<int32>("Battleground.PlayerRespawn", 30);
     if (m_int_configs[CONFIG_BATTLEGROUND_PLAYER_RESPAWN] < 3)
     {
         LOG_ERROR("server.loading", "Battleground.PlayerRespawn (%i) must be >2. Using 30 instead.", m_int_configs[CONFIG_BATTLEGROUND_PLAYER_RESPAWN]);
         m_int_configs[CONFIG_BATTLEGROUND_PLAYER_RESPAWN] = 30;
     }
     m_int_configs[CONFIG_BATTLEGROUND_RESTORATION_BUFF_RESPAWN]        = sConfigMgr->GetOption<int32>("Battleground.RestorationBuffRespawn", 20);
     if (m_int_configs[CONFIG_BATTLEGROUND_RESTORATION_BUFF_RESPAWN] < 1)
     {
         LOG_ERROR("server.loading", "Battleground.RestorationBuffRespawn (%i) must be > 0. Using 20 instead.", m_int_configs[CONFIG_BATTLEGROUND_RESTORATION_BUFF_RESPAWN]);
         m_int_configs[CONFIG_BATTLEGROUND_RESTORATION_BUFF_RESPAWN] = 20;
     }
     m_int_configs[CONFIG_BATTLEGROUND_BERSERKING_BUFF_RESPAWN] = sConfigMgr->GetOption<int32>("Battleground.BerserkingBuffRespawn", 120);
     if (m_int_configs[CONFIG_BATTLEGROUND_BERSERKING_BUFF_RESPAWN] < 1)
     {
         LOG_ERROR("server.loading", "Battleground.BerserkingBuffRespawn (%i) must be > 0. Using 120 instead.", m_int_configs[CONFIG_BATTLEGROUND_BERSERKING_BUFF_RESPAWN]);
         m_int_configs[CONFIG_BATTLEGROUND_BERSERKING_BUFF_RESPAWN] = 120;
     }
     m_int_configs[CONFIG_BATTLEGROUND_SPEED_BUFF_RESPAWN] = sConfigMgr->GetOption<int32>("Battleground.SpeedBuffRespawn", 150);
     if (m_int_configs[CONFIG_BATTLEGROUND_SPEED_BUFF_RESPAWN] < 1)
     {
         LOG_ERROR("server.loading", "Battleground.SpeedBuffRespawn (%i) must be > 0. Using 150 instead.", m_int_configs[CONFIG_BATTLEGROUND_SPEED_BUFF_RESPAWN]);
         m_int_configs[CONFIG_BATTLEGROUND_SPEED_BUFF_RESPAWN] = 150;
     }
     m_int_configs[CONFIG_ARENA_MAX_RATING_DIFFERENCE]                = sConfigMgr->GetOption<int32> ("Arena.MaxRatingDifference", 150);
     m_int_configs[CONFIG_ARENA_RATING_DISCARD_TIMER]                 = sConfigMgr->GetOption<int32> ("Arena.RatingDiscardTimer", 10 * MINUTE * IN_MILLISECONDS);
     m_bool_configs[CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS]              = sConfigMgr->GetOption<bool>("Arena.AutoDistributePoints", false);
     m_int_configs[CONFIG_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS]        = sConfigMgr->GetOption<int32> ("Arena.AutoDistributeInterval", 7); // pussywizard: spoiled by implementing constant day and hour, always 7 now
     m_int_configs[CONFIG_ARENA_GAMES_REQUIRED]                       = sConfigMgr->GetOption<int32> ("Arena.GamesRequired", 10);
     m_int_configs[CONFIG_ARENA_SEASON_ID]                            = sConfigMgr->GetOption<int32> ("Arena.ArenaSeason.ID", 1);
     m_int_configs[CONFIG_ARENA_START_RATING]                         = sConfigMgr->GetOption<int32> ("Arena.ArenaStartRating", 0);
     m_int_configs[CONFIG_ARENA_START_PERSONAL_RATING]                = sConfigMgr->GetOption<int32> ("Arena.ArenaStartPersonalRating", 1000);
     m_int_configs[CONFIG_ARENA_START_MATCHMAKER_RATING]              = sConfigMgr->GetOption<int32> ("Arena.ArenaStartMatchmakerRating", 1500);
     m_bool_configs[CONFIG_ARENA_SEASON_IN_PROGRESS]                  = sConfigMgr->GetOption<bool>("Arena.ArenaSeason.InProgress", true);
     m_float_configs[CONFIG_ARENA_WIN_RATING_MODIFIER_1]              = sConfigMgr->GetOption<float>("Arena.ArenaWinRatingModifier1", 48.0f);
     m_float_configs[CONFIG_ARENA_WIN_RATING_MODIFIER_2]              = sConfigMgr->GetOption<float>("Arena.ArenaWinRatingModifier2", 24.0f);
     m_float_configs[CONFIG_ARENA_LOSE_RATING_MODIFIER]               = sConfigMgr->GetOption<float>("Arena.ArenaLoseRatingModifier", 24.0f);
     m_float_configs[CONFIG_ARENA_MATCHMAKER_RATING_MODIFIER]         = sConfigMgr->GetOption<float>("Arena.ArenaMatchmakerRatingModifier", 24.0f);
     m_bool_configs[CONFIG_ARENA_QUEUE_ANNOUNCER_ENABLE]              = sConfigMgr->GetOption<bool> ("Arena.QueueAnnouncer.Enable", false);
     m_bool_configs[CONFIG_ARENA_QUEUE_ANNOUNCER_PLAYERONLY]          = sConfigMgr->GetOption<bool> ("Arena.QueueAnnouncer.PlayerOnly", false);
     m_bool_configs[CONFIG_OFFHAND_CHECK_AT_SPELL_UNLEARN]            = sConfigMgr->GetOption<bool>("OffhandCheckAtSpellUnlearn", true);
     if (int32 clientCacheId = sConfigMgr->GetOption<int32>("ClientCacheVersion", 0))
     {
         // overwrite DB/old value
         if (clientCacheId > 0)
         {
             m_int_configs[CONFIG_CLIENTCACHE_VERSION] = clientCacheId;
             LOG_INFO("server.loading", "Client cache version set to: %u", clientCacheId);
         }
         else
             LOG_ERROR("server.loading", "ClientCacheVersion can't be negative %d, ignored.", clientCacheId);
     }
     m_int_configs[CONFIG_INSTANT_LOGOUT] = sConfigMgr->GetOption<int32>("InstantLogout", SEC_MODERATOR);
     m_int_configs[CONFIG_GUILD_EVENT_LOG_COUNT] = sConfigMgr->GetOption<int32>("Guild.EventLogRecordsCount", GUILD_EVENTLOG_MAX_RECORDS);
     if (m_int_configs[CONFIG_GUILD_EVENT_LOG_COUNT] > GUILD_EVENTLOG_MAX_RECORDS)
         m_int_configs[CONFIG_GUILD_EVENT_LOG_COUNT] = GUILD_EVENTLOG_MAX_RECORDS;
     m_int_configs[CONFIG_GUILD_BANK_EVENT_LOG_COUNT] = sConfigMgr->GetOption<int32>("Guild.BankEventLogRecordsCount", GUILD_BANKLOG_MAX_RECORDS);
     if (m_int_configs[CONFIG_GUILD_BANK_EVENT_LOG_COUNT] > GUILD_BANKLOG_MAX_RECORDS)
         m_int_configs[CONFIG_GUILD_BANK_EVENT_LOG_COUNT] = GUILD_BANKLOG_MAX_RECORDS;
     //visibility on continents
     m_MaxVisibleDistanceOnContinents = sConfigMgr->GetOption<float>("Visibility.Distance.Continents", DEFAULT_VISIBILITY_DISTANCE);
     if (m_MaxVisibleDistanceOnContinents < 45 * sWorld->getRate(RATE_CREATURE_AGGRO))
     {
         LOG_ERROR("server.loading", "Visibility.Distance.Continents can't be less max aggro radius %f", 45 * sWorld->getRate(RATE_CREATURE_AGGRO));
         m_MaxVisibleDistanceOnContinents = 45 * sWorld->getRate(RATE_CREATURE_AGGRO);
     }
     else if (m_MaxVisibleDistanceOnContinents > MAX_VISIBILITY_DISTANCE)
     {
         LOG_ERROR("server.loading", "Visibility.Distance.Continents can't be greater %f", MAX_VISIBILITY_DISTANCE);
         m_MaxVisibleDistanceOnContinents = MAX_VISIBILITY_DISTANCE;
     }
     //visibility in instances
     m_MaxVisibleDistanceInInstances = sConfigMgr->GetOption<float>("Visibility.Distance.Instances", DEFAULT_VISIBILITY_INSTANCE);
     if (m_MaxVisibleDistanceInInstances < 45 * sWorld->getRate(RATE_CREATURE_AGGRO))
     {
         LOG_ERROR("server.loading", "Visibility.Distance.Instances can't be less max aggro radius %f", 45 * sWorld->getRate(RATE_CREATURE_AGGRO));
         m_MaxVisibleDistanceInInstances = 45 * sWorld->getRate(RATE_CREATURE_AGGRO);
     }
     else if (m_MaxVisibleDistanceInInstances > MAX_VISIBILITY_DISTANCE)
     {
         LOG_ERROR("server.loading", "Visibility.Distance.Instances can't be greater %f", MAX_VISIBILITY_DISTANCE);
         m_MaxVisibleDistanceInInstances = MAX_VISIBILITY_DISTANCE;
     }
     //visibility in BG/Arenas
     m_MaxVisibleDistanceInBGArenas = sConfigMgr->GetOption<float>("Visibility.Distance.BGArenas", DEFAULT_VISIBILITY_BGARENAS);
     if (m_MaxVisibleDistanceInBGArenas < 45 * sWorld->getRate(RATE_CREATURE_AGGRO))
     {
         LOG_ERROR("server.loading", "Visibility.Distance.BGArenas can't be less max aggro radius %f", 45 * sWorld->getRate(RATE_CREATURE_AGGRO));
         m_MaxVisibleDistanceInBGArenas = 45 * sWorld->getRate(RATE_CREATURE_AGGRO);
     }
     else if (m_MaxVisibleDistanceInBGArenas > MAX_VISIBILITY_DISTANCE)
     {
         LOG_ERROR("server.loading", "Visibility.Distance.BGArenas can't be greater %f", MAX_VISIBILITY_DISTANCE);
         m_MaxVisibleDistanceInBGArenas = MAX_VISIBILITY_DISTANCE;
     }
     m_int_configs[CONFIG_CHARDELETE_METHOD]    = sConfigMgr->GetOption<int32>("CharDelete.Method", 0);
     m_int_configs[CONFIG_CHARDELETE_MIN_LEVEL] = sConfigMgr->GetOption<int32>("CharDelete.MinLevel", 0);
     m_int_configs[CONFIG_CHARDELETE_KEEP_DAYS] = sConfigMgr->GetOption<int32>("CharDelete.KeepDays", 30);
     m_bool_configs[CONFIG_ITEMDELETE_METHOD]    = sConfigMgr->GetOption<bool>("ItemDelete.Method", 0);
     m_bool_configs[CONFIG_ITEMDELETE_VENDOR]    = sConfigMgr->GetOption<bool>("ItemDelete.Vendor", 0);
     m_int_configs[CONFIG_ITEMDELETE_QUALITY]    = sConfigMgr->GetOption<int32>("ItemDelete.Quality", 3);
     m_int_configs[CONFIG_ITEMDELETE_ITEM_LEVEL] = sConfigMgr->GetOption<int32>("ItemDelete.ItemLevel", 80);
     m_int_configs[CONFIG_FFA_PVP_TIMER] = sConfigMgr->GetOption<int32>("FFAPvPTimer", 30);
     m_int_configs[CONFIG_LOOT_NEED_BEFORE_GREED_ILVL_RESTRICTION] = sConfigMgr->GetOption<int32>("LootNeedBeforeGreedILvlRestriction", 70);
     std::string dataPath = sConfigMgr->GetOption<std::string>("DataDir", "./");
     if (dataPath.empty() || (dataPath.at(dataPath.length() - 1) != '/' && dataPath.at(dataPath.length() - 1) != '\\'))
         dataPath.push_back('/');
 #if AC_PLATFORM == AC_PLATFORM_UNIX || AC_PLATFORM == AC_PLATFORM_APPLE
     if (dataPath[0] == '~')
     {
         const char* home = getenv("HOME");
         if (home)
             dataPath.replace(0, 1, home);
     }
 #endif
     if (reload)
     {
         if (dataPath != m_dataPath)
             LOG_ERROR("server.loading", "DataDir option can't be changed at worldserver.conf reload, using current value (%s).", m_dataPath.c_str());
     }
     else
     {
         m_dataPath = dataPath;
         LOG_INFO("server.loading", "Using DataDir %s", m_dataPath.c_str());
     }
     m_bool_configs[CONFIG_VMAP_INDOOR_CHECK] = sConfigMgr->GetOption<bool>("vmap.enableIndoorCheck", 0);
     bool enableIndoor = sConfigMgr->GetOption<bool>("vmap.enableIndoorCheck", true);
     bool enableLOS = sConfigMgr->GetOption<bool>("vmap.enableLOS", true);
     bool enableHeight = sConfigMgr->GetOption<bool>("vmap.enableHeight", true);
     bool enablePetLOS = sConfigMgr->GetOption<bool>("vmap.petLOS", true);
     if (!enableHeight)
         LOG_ERROR("server.loading", "VMap height checking disabled! Creatures movements and other various things WILL be broken! Expect no support.");
     VMAP::VMapFactory::createOrGetVMapMgr()->setEnableLineOfSightCalc(enableLOS);
     VMAP::VMapFactory::createOrGetVMapMgr()->setEnableHeightCalc(enableHeight);
     LOG_INFO("server.loading", "WORLD: VMap support included. LineOfSight:%i, getHeight:%i, indoorCheck:%i PetLOS:%i", enableLOS, enableHeight, enableIndoor, enablePetLOS);
     m_bool_configs[CONFIG_PET_LOS]            = sConfigMgr->GetOption<bool>("vmap.petLOS", true);
     m_bool_configs[CONFIG_START_ALL_SPELLS]   = sConfigMgr->GetOption<bool>("PlayerStart.AllSpells", false);
     m_int_configs[CONFIG_HONOR_AFTER_DUEL]    = sConfigMgr->GetOption<int32>("HonorPointsAfterDuel", 0);
     m_bool_configs[CONFIG_START_ALL_EXPLORED] = sConfigMgr->GetOption<bool>("PlayerStart.MapsExplored", false);
     m_bool_configs[CONFIG_START_ALL_REP]      = sConfigMgr->GetOption<bool>("PlayerStart.AllReputation", false);
     m_bool_configs[CONFIG_ALWAYS_MAXSKILL]    = sConfigMgr->GetOption<bool>("AlwaysMaxWeaponSkill", false);
     m_bool_configs[CONFIG_PVP_TOKEN_ENABLE]   = sConfigMgr->GetOption<bool>("PvPToken.Enable", false);
     m_int_configs[CONFIG_PVP_TOKEN_MAP_TYPE]  = sConfigMgr->GetOption<int32>("PvPToken.MapAllowType", 4);
     m_int_configs[CONFIG_PVP_TOKEN_ID]        = sConfigMgr->GetOption<int32>("PvPToken.ItemID", 29434);
     m_int_configs[CONFIG_PVP_TOKEN_COUNT]     = sConfigMgr->GetOption<int32>("PvPToken.ItemCount", 1);
     if (m_int_configs[CONFIG_PVP_TOKEN_COUNT] < 1)
         m_int_configs[CONFIG_PVP_TOKEN_COUNT] = 1;
     m_bool_configs[CONFIG_NO_RESET_TALENT_COST]       = sConfigMgr->GetOption<bool>("NoResetTalentsCost", false);
     m_int_configs[CONFIG_TOGGLE_XP_COST]              = sConfigMgr->GetOption<int32>("ToggleXP.Cost", 100000);
     m_bool_configs[CONFIG_SHOW_KICK_IN_WORLD]         = sConfigMgr->GetOption<bool>("ShowKickInWorld", false);
     m_bool_configs[CONFIG_SHOW_MUTE_IN_WORLD]         = sConfigMgr->GetOption<bool>("ShowMuteInWorld", false);
     m_bool_configs[CONFIG_SHOW_BAN_IN_WORLD]          = sConfigMgr->GetOption<bool>("ShowBanInWorld", false);
     m_int_configs[CONFIG_INTERVAL_LOG_UPDATE]         = sConfigMgr->GetOption<int32>("RecordUpdateTimeDiffInterval", 300000);
     m_int_configs[CONFIG_MIN_LOG_UPDATE]              = sConfigMgr->GetOption<int32>("MinRecordUpdateTimeDiff", 100);
     m_int_configs[CONFIG_NUMTHREADS]                  = sConfigMgr->GetOption<int32>("MapUpdate.Threads", 1);
     m_int_configs[CONFIG_MAX_RESULTS_LOOKUP_COMMANDS] = sConfigMgr->GetOption<int32>("Command.LookupMaxResults", 0);
     // Warden
     m_bool_configs[CONFIG_WARDEN_ENABLED]              = sConfigMgr->GetOption<bool>("Warden.Enabled", true);
     m_int_configs[CONFIG_WARDEN_NUM_MEM_CHECKS]        = sConfigMgr->GetOption<int32>("Warden.NumMemChecks", 3);
     m_int_configs[CONFIG_WARDEN_NUM_LUA_CHECKS]        = sConfigMgr->GetOption<int32>("Warden.NumLuaChecks", 1);
     m_int_configs[CONFIG_WARDEN_NUM_OTHER_CHECKS]      = sConfigMgr->GetOption<int32>("Warden.NumOtherChecks", 7);
     m_int_configs[CONFIG_WARDEN_CLIENT_BAN_DURATION]   = sConfigMgr->GetOption<int32>("Warden.BanDuration", 86400);
     m_int_configs[CONFIG_WARDEN_CLIENT_CHECK_HOLDOFF]  = sConfigMgr->GetOption<int32>("Warden.ClientCheckHoldOff", 30);
     m_int_configs[CONFIG_WARDEN_CLIENT_FAIL_ACTION]    = sConfigMgr->GetOption<int32>("Warden.ClientCheckFailAction", 0);
     m_int_configs[CONFIG_WARDEN_CLIENT_RESPONSE_DELAY] = sConfigMgr->GetOption<int32>("Warden.ClientResponseDelay", 600);
     // Dungeon finder
     m_int_configs[CONFIG_LFG_OPTIONSMASK] = sConfigMgr->GetOption<int32>("DungeonFinder.OptionsMask", 5);
     // Max instances per hour
     m_int_configs[CONFIG_MAX_INSTANCES_PER_HOUR] = sConfigMgr->GetOption<int32>("AccountInstancesPerHour", 5);
     // AutoBroadcast
     m_bool_configs[CONFIG_AUTOBROADCAST]         = sConfigMgr->GetOption<bool>("AutoBroadcast.On", false);
     m_int_configs[CONFIG_AUTOBROADCAST_CENTER]   = sConfigMgr->GetOption<int32>("AutoBroadcast.Center", 0);
     m_int_configs[CONFIG_AUTOBROADCAST_INTERVAL] = sConfigMgr->GetOption<int32>("AutoBroadcast.Timer", 60000);
     if (reload)
     {
         m_timers[WUPDATE_AUTOBROADCAST].SetInterval(m_int_configs[CONFIG_AUTOBROADCAST_INTERVAL]);
         m_timers[WUPDATE_AUTOBROADCAST].Reset();
     }
     // MySQL ping time interval
     m_int_configs[CONFIG_DB_PING_INTERVAL] = sConfigMgr->GetOption<int32>("MaxPingTime", 30);
     // misc
     m_bool_configs[CONFIG_PDUMP_NO_PATHS]     = sConfigMgr->GetOption<bool>("PlayerDump.DisallowPaths", true);
     m_bool_configs[CONFIG_PDUMP_NO_OVERWRITE] = sConfigMgr->GetOption<bool>("PlayerDump.DisallowOverwrite", true);
     m_bool_configs[CONFIG_ENABLE_MMAPS]       = sConfigMgr->GetOption<bool>("MoveMaps.Enable", true);
     MMAP::MMapFactory::InitializeDisabledMaps();
     // Wintergrasp
     m_bool_configs[CONFIG_WINTERGRASP_ENABLE]             = sConfigMgr->GetOption<bool>("Wintergrasp.Enable", false);
     m_int_configs[CONFIG_WINTERGRASP_PLR_MAX]             = sConfigMgr->GetOption<int32>("Wintergrasp.PlayerMax", 100);
     m_int_configs[CONFIG_WINTERGRASP_PLR_MIN]             = sConfigMgr->GetOption<int32>("Wintergrasp.PlayerMin", 0);
     m_int_configs[CONFIG_WINTERGRASP_PLR_MIN_LVL]         = sConfigMgr->GetOption<int32>("Wintergrasp.PlayerMinLvl", 77);
     m_int_configs[CONFIG_WINTERGRASP_BATTLETIME]          = sConfigMgr->GetOption<int32>("Wintergrasp.BattleTimer", 30);
     m_int_configs[CONFIG_WINTERGRASP_NOBATTLETIME]        = sConfigMgr->GetOption<int32>("Wintergrasp.NoBattleTimer", 150);
     m_int_configs[CONFIG_WINTERGRASP_RESTART_AFTER_CRASH] = sConfigMgr->GetOption<int32>("Wintergrasp.CrashRestartTimer", 10);
     m_int_configs[CONFIG_BIRTHDAY_TIME]     = sConfigMgr->GetOption<int32>("BirthdayTime", 1222964635);
     m_bool_configs[CONFIG_MINIGOB_MANABONK] = sConfigMgr->GetOption<bool>("Minigob.Manabonk.Enable", true);
     m_bool_configs[CONFIG_ENABLE_CONTINENT_TRANSPORT]            = sConfigMgr->GetOption<bool>("IsContinentTransport.Enabled", true);
     m_bool_configs[CONFIG_ENABLE_CONTINENT_TRANSPORT_PRELOADING] = sConfigMgr->GetOption<bool>("IsPreloadedContinentTransport.Enabled", false);
     m_bool_configs[CONFIG_IP_BASED_ACTION_LOGGING] = sConfigMgr->GetOption<bool>("Allow.IP.Based.Action.Logging", false);
     // Whether to use LoS from game objects
     m_bool_configs[CONFIG_CHECK_GOBJECT_LOS] = sConfigMgr->GetOption<bool>("CheckGameObjectLoS", true);
     m_bool_configs[CONFIG_CALCULATE_CREATURE_ZONE_AREA_DATA]   = sConfigMgr->GetOption<bool>("Calculate.Creature.Zone.Area.Data", false);
     m_bool_configs[CONFIG_CALCULATE_GAMEOBJECT_ZONE_AREA_DATA] = sConfigMgr->GetOption<bool>("Calculate.Gameoject.Zone.Area.Data", false);
     // Player can join LFG anywhere
     m_bool_configs[CONFIG_LFG_LOCATION_ALL] = sConfigMgr->GetOption<bool>("LFG.Location.All", false);
     // Prevent players AFK from being logged out
     m_int_configs[CONFIG_AFK_PREVENT_LOGOUT] = sConfigMgr->GetOption<int32>("PreventAFKLogout", 0);
     // Preload all grids of all non-instanced maps
     m_bool_configs[CONFIG_PRELOAD_ALL_NON_INSTANCED_MAP_GRIDS] = sConfigMgr->GetOption<bool>("PreloadAllNonInstancedMapGrids", false);
     // ICC buff override
     m_int_configs[CONFIG_ICC_BUFF_HORDE] = sConfigMgr->GetOption<int32>("ICC.Buff.Horde", 73822);
     m_int_configs[CONFIG_ICC_BUFF_ALLIANCE] = sConfigMgr->GetOption<int32>("ICC.Buff.Alliance", 73828);
     m_bool_configs[CONFIG_SET_ALL_CREATURES_WITH_WAYPOINT_MOVEMENT_ACTIVE] = sConfigMgr->GetOption<bool>("SetAllCreaturesWithWaypointMovementActive", false);
     // packet spoof punishment
     m_int_configs[CONFIG_PACKET_SPOOF_POLICY] = sConfigMgr->GetOption<int32>("PacketSpoof.Policy", (uint32)WorldSession::DosProtection::POLICY_KICK);
     m_int_configs[CONFIG_PACKET_SPOOF_BANMODE] = sConfigMgr->GetOption<int32>("PacketSpoof.BanMode", (uint32)0);
     if (m_int_configs[CONFIG_PACKET_SPOOF_BANMODE] > 1)
         m_int_configs[CONFIG_PACKET_SPOOF_BANMODE] = (uint32)0;
     m_int_configs[CONFIG_PACKET_SPOOF_BANDURATION] = sConfigMgr->GetOption<int32>("PacketSpoof.BanDuration", 86400);
     // Random Battleground Rewards
     m_int_configs[CONFIG_BG_REWARD_WINNER_HONOR_FIRST] = sConfigMgr->GetOption<int32>("Battleground.RewardWinnerHonorFirst", 30);
     m_int_configs[CONFIG_BG_REWARD_WINNER_ARENA_FIRST] = sConfigMgr->GetOption<int32>("Battleground.RewardWinnerArenaFirst", 25);
     m_int_configs[CONFIG_BG_REWARD_WINNER_HONOR_LAST]  = sConfigMgr->GetOption<int32>("Battleground.RewardWinnerHonorLast", 15);
     m_int_configs[CONFIG_BG_REWARD_WINNER_ARENA_LAST]  = sConfigMgr->GetOption<int32>("Battleground.RewardWinnerArenaLast", 0);
     m_int_configs[CONFIG_BG_REWARD_LOSER_HONOR_FIRST]  = sConfigMgr->GetOption<int32>("Battleground.RewardLoserHonorFirst", 5);
     m_int_configs[CONFIG_BG_REWARD_LOSER_HONOR_LAST]   = sConfigMgr->GetOption<int32>("Battleground.RewardLoserHonorLast", 5);
     m_int_configs[CONFIG_WAYPOINT_MOVEMENT_STOP_TIME_FOR_PLAYER] = sConfigMgr->GetOption<int32>("WaypointMovementStopTimeForPlayer", 120);
     m_int_configs[CONFIG_DUNGEON_ACCESS_REQUIREMENTS_PRINT_MODE]              = sConfigMgr->GetOption<int32>("DungeonAccessRequirements.PrintMode", 1);
     m_bool_configs[CONFIG_DUNGEON_ACCESS_REQUIREMENTS_PORTAL_CHECK_ILVL]      = sConfigMgr->GetOption<bool>("DungeonAccessRequirements.PortalAvgIlevelCheck", false);
     m_bool_configs[CONFIG_DUNGEON_ACCESS_REQUIREMENTS_LFG_DBC_LEVEL_OVERRIDE] = sConfigMgr->GetOption<bool>("DungeonAccessRequirements.LFGLevelDBCOverride", false);
     m_int_configs[CONFIG_DUNGEON_ACCESS_REQUIREMENTS_OPTIONAL_STRING_ID]      = sConfigMgr->GetOption<int32>("DungeonAccessRequirements.OptionalStringID", 0);
     m_int_configs[CONFIG_NPC_EVADE_IF_NOT_REACHABLE] = sConfigMgr->GetOption<int32>("NpcEvadeIfTargetIsUnreachable", 5);
     m_int_configs[CONFIG_NPC_REGEN_TIME_IF_NOT_REACHABLE_IN_RAID] = sConfigMgr->GetOption<int32>("NpcRegenHPTimeIfTargetIsUnreachable", 10);
     m_bool_configs[CONFIG_REGEN_HP_CANNOT_REACH_TARGET_IN_RAID] = sConfigMgr->GetOption<bool>("NpcRegenHPIfTargetIsUnreachable", true);
     //Debug
     m_bool_configs[CONFIG_DEBUG_BATTLEGROUND] = sConfigMgr->GetOption<bool>("Debug.Battleground", false);
     m_bool_configs[CONFIG_DEBUG_ARENA]        = sConfigMgr->GetOption<bool>("Debug.Arena",        false);
     m_int_configs[CONFIG_GM_LEVEL_CHANNEL_MODERATION] = sConfigMgr->GetOption<int32>("Channel.ModerationGMLevel", 1);
     m_bool_configs[CONFIG_SET_BOP_ITEM_TRADEABLE] = sConfigMgr->GetOption<bool>("Item.SetItemTradeable", true);
     // Specifies if IP addresses can be logged to the database
     m_bool_configs[CONFIG_ALLOW_LOGGING_IP_ADDRESSES_IN_DATABASE] = sConfigMgr->GetOption<bool>("AllowLoggingIPAddressesInDatabase", true, true);
     // LFG group mechanics.
     m_int_configs[CONFIG_LFG_MAX_KICK_COUNT] = sConfigMgr->GetOption<int32>("LFG.MaxKickCount", 2);
     if (m_int_configs[CONFIG_LFG_MAX_KICK_COUNT] > 3)
     {
         m_int_configs[CONFIG_LFG_MAX_KICK_COUNT] = 3;
         LOG_ERROR("server.loading", "LFG.MaxKickCount can't be higher than 3.");
     }
     m_int_configs[CONFIG_LFG_KICK_PREVENTION_TIMER] = sConfigMgr->GetOption<int32>("LFG.KickPreventionTimer", 15 * MINUTE * IN_MILLISECONDS) * IN_MILLISECONDS;
     if (m_int_configs[CONFIG_LFG_KICK_PREVENTION_TIMER] > 15 * MINUTE * IN_MILLISECONDS)
     {
         m_int_configs[CONFIG_LFG_KICK_PREVENTION_TIMER] = 15 * MINUTE * IN_MILLISECONDS;
         LOG_ERROR("server.loading", "LFG.KickPreventionTimer can't be higher than 15 minutes.");
     }
     // Realm Availability
     m_bool_configs[CONFIG_REALM_LOGIN_ENABLED] = sConfigMgr->GetOption<bool>("World.RealmAvailability", true);
     // call ScriptMgr if we're reloading the configuration
     sScriptMgr->OnAfterConfigLoad(reload);
 }
References baseMoveSpeed, CONFIG_ADDON_CHANNEL, CONFIG_AFK_PREVENT_LOGOUT, CONFIG_ALL_TAXI_PATHS, CONFIG_ALLOW_GM_FRIEND, CONFIG_ALLOW_GM_GROUP, CONFIG_ALLOW_LOGGING_IP_ADDRESSES_IN_DATABASE, CONFIG_ALLOW_PLAYER_COMMANDS, CONFIG_ALLOW_TICKETS, CONFIG_ALLOW_TWO_SIDE_ACCOUNTS, CONFIG_ALLOW_TWO_SIDE_ADD_FRIEND, CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CALENDAR, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHAT, CONFIG_ALLOW_TWO_SIDE_INTERACTION_EMOTE, CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP, CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD, CONFIG_ALLOW_TWO_SIDE_INTERACTION_MAIL, CONFIG_ALLOW_TWO_SIDE_TRADE, CONFIG_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_ALWAYS_MAX_SKILL_FOR_LEVEL, CONFIG_ALWAYS_MAXSKILL, CONFIG_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS, CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS, CONFIG_ARENA_GAMES_REQUIRED, CONFIG_ARENA_LOSE_RATING_MODIFIER, CONFIG_ARENA_MATCHMAKER_RATING_MODIFIER, CONFIG_ARENA_MAX_RATING_DIFFERENCE, CONFIG_ARENA_QUEUE_ANNOUNCER_ENABLE, CONFIG_ARENA_QUEUE_ANNOUNCER_PLAYERONLY, CONFIG_ARENA_RATING_DISCARD_TIMER, CONFIG_ARENA_SEASON_ID, CONFIG_ARENA_SEASON_IN_PROGRESS, CONFIG_ARENA_START_MATCHMAKER_RATING, CONFIG_ARENA_START_PERSONAL_RATING, CONFIG_ARENA_START_RATING, CONFIG_ARENA_WIN_RATING_MODIFIER_1, CONFIG_ARENA_WIN_RATING_MODIFIER_2, CONFIG_AUCTION_LEVEL_REQ, CONFIG_AUTOBROADCAST, CONFIG_AUTOBROADCAST_CENTER, CONFIG_AUTOBROADCAST_INTERVAL, CONFIG_BATTLEGROUND_BERSERKING_BUFF_RESPAWN, CONFIG_BATTLEGROUND_CAST_DESERTER, CONFIG_BATTLEGROUND_DISABLE_QUEST_SHARE_IN_BG, CONFIG_BATTLEGROUND_DISABLE_READY_CHECK_IN_BG, CONFIG_BATTLEGROUND_INVITATION_TYPE, CONFIG_BATTLEGROUND_PLAYER_RESPAWN, CONFIG_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH, CONFIG_BATTLEGROUND_PREMATURE_FINISH_TIMER, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_ENABLE, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_LEVEL, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_PLAYERS, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_PLAYERONLY, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_SPAM_DELAY, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_TIMED, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_TIMER, CONFIG_BATTLEGROUND_REPORT_AFK, CONFIG_BATTLEGROUND_REPORT_AFK_TIMER, CONFIG_BATTLEGROUND_RESTORATION_BUFF_RESPAWN, CONFIG_BATTLEGROUND_SPEED_BUFF_RESPAWN, CONFIG_BATTLEGROUND_STORE_STATISTICS_ENABLE, CONFIG_BATTLEGROUND_TRACK_DESERTERS, CONFIG_BG_REWARD_LOSER_HONOR_FIRST, CONFIG_BG_REWARD_LOSER_HONOR_LAST, CONFIG_BG_REWARD_WINNER_ARENA_FIRST, CONFIG_BG_REWARD_WINNER_ARENA_LAST, CONFIG_BG_REWARD_WINNER_HONOR_FIRST, CONFIG_BG_REWARD_WINNER_HONOR_LAST, CONFIG_BG_XP_FOR_KILL, CONFIG_BIRTHDAY_TIME, CONFIG_CALCULATE_CREATURE_ZONE_AREA_DATA, CONFIG_CALCULATE_GAMEOBJECT_ZONE_AREA_DATA, CONFIG_CALENDAR_DELETE_OLD_EVENTS_HOUR, CONFIG_CHANCE_OF_GM_SURVEY, CONFIG_CHARACTER_CREATING_DISABLED, CONFIG_CHARACTER_CREATING_DISABLED_CLASSMASK, CONFIG_CHARACTER_CREATING_DISABLED_RACEMASK, CONFIG_CHARACTER_CREATING_MIN_LEVEL_FOR_HEROIC_CHARACTER, CONFIG_CHARACTERS_PER_ACCOUNT, CONFIG_CHARACTERS_PER_REALM, CONFIG_CHARDELETE_KEEP_DAYS, CONFIG_CHARDELETE_METHOD, CONFIG_CHARDELETE_MIN_LEVEL, CONFIG_CHARTER_COST_ARENA_2v2, CONFIG_CHARTER_COST_ARENA_3v3, CONFIG_CHARTER_COST_ARENA_5v5, CONFIG_CHARTER_COST_GUILD, CONFIG_CHAT_CHANNEL_LEVEL_REQ, CONFIG_CHAT_FAKE_MESSAGE_PREVENTING, CONFIG_CHAT_MUTE_FIRST_LOGIN, CONFIG_CHAT_SAY_LEVEL_REQ, CONFIG_CHAT_STRICT_LINK_CHECKING_KICK, CONFIG_CHAT_STRICT_LINK_CHECKING_SEVERITY, CONFIG_CHAT_TIME_MUTE_FIRST_LOGIN, CONFIG_CHAT_WHISPER_LEVEL_REQ, CONFIG_CHATFLOOD_MESSAGE_COUNT, CONFIG_CHATFLOOD_MESSAGE_DELAY, CONFIG_CHATFLOOD_MUTE_TIME, CONFIG_CHECK_GOBJECT_LOS, CONFIG_CLEAN_CHARACTER_DB, CONFIG_CLIENTCACHE_VERSION, CONFIG_CLOSE_IDLE_CONNECTIONS, CONFIG_COMPRESSION, CONFIG_CORPSE_DECAY_ELITE, CONFIG_CORPSE_DECAY_NORMAL, CONFIG_CORPSE_DECAY_RARE, CONFIG_CORPSE_DECAY_RAREELITE, CONFIG_CORPSE_DECAY_WORLDBOSS, CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY, CONFIG_CREATURE_FAMILY_ASSISTANCE_PERIOD, CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS, CONFIG_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS, CONFIG_CREATURE_FAMILY_FLEE_DELAY, CONFIG_DB_PING_INTERVAL, CONFIG_DEATH_BONES_BG_OR_ARENA, CONFIG_DEATH_BONES_WORLD, CONFIG_DEATH_CORPSE_RECLAIM_DELAY_PVE, CONFIG_DEATH_CORPSE_RECLAIM_DELAY_PVP, CONFIG_DEATH_SICKNESS_LEVEL, CONFIG_DEBUG_ARENA, CONFIG_DEBUG_BATTLEGROUND, CONFIG_DECLINED_NAMES_USED, CONFIG_DELETE_CHARACTER_TICKET_TRACE, CONFIG_DETECT_POS_COLLISION, CONFIG_DIE_COMMAND_MODE, CONFIG_DISABLE_BREATHING, CONFIG_DONT_CACHE_RANDOM_MOVEMENT_PATHS, CONFIG_DUNGEON_ACCESS_REQUIREMENTS_LFG_DBC_LEVEL_OVERRIDE, CONFIG_DUNGEON_ACCESS_REQUIREMENTS_OPTIONAL_STRING_ID, CONFIG_DUNGEON_ACCESS_REQUIREMENTS_PORTAL_CHECK_ILVL, CONFIG_DUNGEON_ACCESS_REQUIREMENTS_PRINT_MODE, CONFIG_DURABILITY_LOSS_IN_PVP, CONFIG_ENABLE_CONTINENT_TRANSPORT, CONFIG_ENABLE_CONTINENT_TRANSPORT_PRELOADING, CONFIG_ENABLE_LOGIN_AFTER_DC, CONFIG_ENABLE_MMAPS, CONFIG_ENABLE_SINFO_LOGIN, CONFIG_EVENT_ANNOUNCE, CONFIG_EXPANSION, CONFIG_FFA_PVP_TIMER, CONFIG_GAME_TYPE, CONFIG_GM_CHAT, CONFIG_GM_LEVEL_CHANNEL_MODERATION, CONFIG_GM_LEVEL_IN_GM_LIST, CONFIG_GM_LEVEL_IN_WHO_LIST, CONFIG_GM_LOGIN_STATE, CONFIG_GM_LOWER_SECURITY, CONFIG_GM_VISIBLE_STATE, CONFIG_GM_WHISPERING_TO, CONFIG_GROUP_VISIBILITY, CONFIG_GROUP_XP_DISTANCE, CONFIG_GUILD_BANK_EVENT_LOG_COUNT, CONFIG_GUILD_BANK_INITIAL_TABS, CONFIG_GUILD_BANK_TAB_COST_0, CONFIG_GUILD_BANK_TAB_COST_1, CONFIG_GUILD_BANK_TAB_COST_2, CONFIG_GUILD_BANK_TAB_COST_3, CONFIG_GUILD_BANK_TAB_COST_4, CONFIG_GUILD_BANK_TAB_COST_5, CONFIG_GUILD_EVENT_LOG_COUNT, CONFIG_GUILD_RESET_HOUR, CONFIG_HEROIC_CHARACTERS_PER_REALM, CONFIG_HONOR_AFTER_DUEL, CONFIG_ICC_BUFF_ALLIANCE, CONFIG_ICC_BUFF_HORDE, CONFIG_INSTANCE_GMSUMMON_PLAYER, CONFIG_INSTANCE_IGNORE_LEVEL, CONFIG_INSTANCE_IGNORE_RAID, CONFIG_INSTANCE_RESET_TIME_HOUR, CONFIG_INSTANCE_RESET_TIME_RELATIVE_TIMESTAMP, CONFIG_INSTANCE_SHARED_ID, CONFIG_INSTANCE_UNLOAD_DELAY, CONFIG_INSTANT_LOGOUT, CONFIG_INSTANT_TAXI, CONFIG_INTERVAL_CHANGEWEATHER, CONFIG_INTERVAL_DISCONNECT_TOLERANCE, CONFIG_INTERVAL_LOG_UPDATE, CONFIG_INTERVAL_MAPUPDATE, CONFIG_INTERVAL_SAVE, CONFIG_IP_BASED_ACTION_LOGGING, CONFIG_ITEMDELETE_ITEM_LEVEL, CONFIG_ITEMDELETE_METHOD, CONFIG_ITEMDELETE_QUALITY, CONFIG_ITEMDELETE_VENDOR, CONFIG_LFG_KICK_PREVENTION_TIMER, CONFIG_LFG_LOCATION_ALL, CONFIG_LFG_MAX_KICK_COUNT, CONFIG_LFG_OPTIONSMASK, CONFIG_LISTEN_RANGE_SAY, CONFIG_LISTEN_RANGE_TEXTEMOTE, CONFIG_LISTEN_RANGE_YELL, CONFIG_LOGDB_CLEARINTERVAL, CONFIG_LOGDB_CLEARTIME, CONFIG_LOOT_NEED_BEFORE_GREED_ILVL_RESTRICTION, CONFIG_MAIL_DELIVERY_DELAY, CONFIG_MAIL_LEVEL_REQ, CONFIG_MAX_ALLOWED_MMR_DROP, CONFIG_MAX_ARENA_POINTS, CONFIG_MAX_HONOR_POINTS, CONFIG_MAX_INSTANCES_PER_HOUR, CONFIG_MAX_OVERSPEED_PINGS, CONFIG_MAX_PLAYER_LEVEL, CONFIG_MAX_PRIMARY_TRADE_SKILL, CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL, CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL_DIFFERENCE, CONFIG_MAX_RECRUIT_A_FRIEND_DISTANCE, CONFIG_MAX_RESULTS_LOOKUP_COMMANDS, CONFIG_MAX_WHO_LIST_RETURN, CONFIG_MIN_CHARTER_NAME, CONFIG_MIN_DUALSPEC_LEVEL, CONFIG_MIN_LEVEL_STAT_SAVE, CONFIG_MIN_LOG_UPDATE, CONFIG_MIN_PET_NAME, CONFIG_MIN_PETITION_SIGNS, CONFIG_MIN_PLAYER_NAME, CONFIG_MINIGOB_MANABONK, CONFIG_NO_RESET_TALENT_COST, CONFIG_NPC_EVADE_IF_NOT_REACHABLE, CONFIG_NPC_REGEN_TIME_IF_NOT_REACHABLE_IN_RAID, CONFIG_NUMTHREADS, CONFIG_OFFHAND_CHECK_AT_SPELL_UNLEARN, CONFIG_PACKET_SPOOF_BANDURATION, CONFIG_PACKET_SPOOF_BANMODE, CONFIG_PACKET_SPOOF_POLICY, CONFIG_PARTY_LEVEL_REQ, CONFIG_PDUMP_NO_OVERWRITE, CONFIG_PDUMP_NO_PATHS, CONFIG_PERSISTENT_CHARACTER_CLEAN_FLAGS, CONFIG_PET_LOS, CONFIG_PORT_WORLD, CONFIG_PRELOAD_ALL_NON_INSTANCED_MAP_GRIDS, CONFIG_PRESERVE_CUSTOM_CHANNEL_DURATION, CONFIG_PRESERVE_CUSTOM_CHANNELS, CONFIG_PVP_TOKEN_COUNT, CONFIG_PVP_TOKEN_ENABLE, CONFIG_PVP_TOKEN_ID, CONFIG_PVP_TOKEN_MAP_TYPE, CONFIG_QUEST_ENABLE_QUEST_TRACKER, CONFIG_QUEST_HIGH_LEVEL_HIDE_DIFF, CONFIG_QUEST_IGNORE_AUTO_ACCEPT, CONFIG_QUEST_IGNORE_AUTO_COMPLETE, CONFIG_QUEST_IGNORE_RAID, CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF, CONFIG_RANDOM_BG_RESET_HOUR, CONFIG_REALM_LOGIN_ENABLED, CONFIG_REALM_ZONE, CONFIG_REGEN_HP_CANNOT_REACH_TARGET_IN_RAID, CONFIG_RESTRICTED_LFG_CHANNEL, CONFIG_SAVE_RESPAWN_TIME_IMMEDIATELY, CONFIG_SESSION_ADD_DELAY, CONFIG_SET_ALL_CREATURES_WITH_WAYPOINT_MOVEMENT_ACTIVE, CONFIG_SET_BOP_ITEM_TRADEABLE, CONFIG_SHOW_BAN_IN_WORLD, CONFIG_SHOW_KICK_IN_WORLD, CONFIG_SHOW_MUTE_IN_WORLD, CONFIG_SIGHT_MONSTER, CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL, CONFIG_SKILL_CHANCE_GREEN, CONFIG_SKILL_CHANCE_GREY, CONFIG_SKILL_CHANCE_MINING_STEPS, CONFIG_SKILL_CHANCE_ORANGE, CONFIG_SKILL_CHANCE_SKINNING_STEPS, CONFIG_SKILL_CHANCE_YELLOW, CONFIG_SKILL_GAIN_CRAFTING, CONFIG_SKILL_GAIN_DEFENSE, CONFIG_SKILL_GAIN_GATHERING, CONFIG_SKILL_GAIN_WEAPON, CONFIG_SKILL_MILLING, CONFIG_SKILL_PROSPECTING, CONFIG_SKIP_CINEMATICS, CONFIG_SOCKET_TIMEOUTTIME, CONFIG_SOCKET_TIMEOUTTIME_ACTIVE, CONFIG_START_ALL_EXPLORED, CONFIG_START_ALL_REP, CONFIG_START_ALL_SPELLS, CONFIG_START_ARENA_POINTS, CONFIG_START_GM_LEVEL, CONFIG_START_HEROIC_PLAYER_LEVEL, CONFIG_START_HONOR_POINTS, CONFIG_START_PLAYER_LEVEL, CONFIG_START_PLAYER_MONEY, CONFIG_STATS_SAVE_ONLY_ON_LOGOUT, CONFIG_STRICT_CHANNEL_NAMES, CONFIG_STRICT_CHARTER_NAMES, CONFIG_STRICT_PET_NAMES, CONFIG_STRICT_PLAYER_NAMES, CONFIG_TALENTS_INSPECTING, CONFIG_TELEPORT_TIMEOUT_FAR, CONFIG_TELEPORT_TIMEOUT_NEAR, CONFIG_TICKET_LEVEL_REQ, CONFIG_TOGGLE_XP_COST, CONFIG_TRADE_LEVEL_REQ, CONFIG_UPTIME_UPDATE, CONFIG_VMAP_INDOOR_CHECK, CONFIG_WARDEN_CLIENT_BAN_DURATION, CONFIG_WARDEN_CLIENT_CHECK_HOLDOFF, CONFIG_WARDEN_CLIENT_FAIL_ACTION, CONFIG_WARDEN_CLIENT_RESPONSE_DELAY, CONFIG_WARDEN_ENABLED, CONFIG_WARDEN_NUM_LUA_CHECKS, CONFIG_WARDEN_NUM_MEM_CHECKS, CONFIG_WARDEN_NUM_OTHER_CHECKS, CONFIG_WAYPOINT_MOVEMENT_STOP_TIME_FOR_PLAYER, CONFIG_WEATHER, CONFIG_WINTERGRASP_BATTLETIME, CONFIG_WINTERGRASP_ENABLE, CONFIG_WINTERGRASP_NOBATTLETIME, CONFIG_WINTERGRASP_PLR_MAX, CONFIG_WINTERGRASP_PLR_MIN, CONFIG_WINTERGRASP_PLR_MIN_LVL, CONFIG_WINTERGRASP_RESTART_AFTER_CRASH, CONFIG_WORLD_BOSS_LEVEL_DIFF, CONTACT_DISTANCE, VMAP::VMapFactory::createOrGetVMapMgr(), DEFAULT_MAX_LEVEL, DEFAULT_VISIBILITY_BGARENAS, DEFAULT_VISIBILITY_DISTANCE, DEFAULT_VISIBILITY_INSTANCE, getRate(), GUILD_BANKLOG_MAX_RECORDS, GUILD_EVENTLOG_MAX_RECORDS, HOUR, Realm::Id, IN_MILLISECONDS, AIRegistry::Initialize(), MMAP::MMapFactory::InitializeDisabledMaps(), LOG_ERROR, LOG_INFO, m_bool_configs, m_dataPath, m_float_configs, m_int_configs, m_MaxVisibleDistanceInBGArenas, m_MaxVisibleDistanceInInstances, m_MaxVisibleDistanceOnContinents, m_timers, MAX_CHARTER_NAME, MAX_LEVEL, MAX_MONEY_AMOUNT, MAX_MOVE_TYPE, MAX_PET_NAME, MAX_PLAYER_NAME, MAX_VISIBILITY_DISTANCE, MIN_MAP_UPDATE_DELAY, MINUTE, NOMINAL_MELEE_RANGE, playerBaseMoveSpeed, WorldSession::DosProtection::POLICY_KICK, RATE_ARENA_POINTS, RATE_AUCTION_CUT, RATE_AUCTION_DEPOSIT, RATE_AUCTION_TIME, RATE_BUYVALUE_ITEM_ARTIFACT, RATE_BUYVALUE_ITEM_EPIC, RATE_BUYVALUE_ITEM_HEIRLOOM, RATE_BUYVALUE_ITEM_LEGENDARY, RATE_BUYVALUE_ITEM_NORMAL, RATE_BUYVALUE_ITEM_POOR, RATE_BUYVALUE_ITEM_RARE, RATE_BUYVALUE_ITEM_UNCOMMON, RATE_CORPSE_DECAY_LOOTED, RATE_CREATURE_AGGRO, RATE_CREATURE_ELITE_ELITE_DAMAGE, RATE_CREATURE_ELITE_ELITE_HP, RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE, RATE_CREATURE_ELITE_RARE_DAMAGE, RATE_CREATURE_ELITE_RARE_HP, RATE_CREATURE_ELITE_RARE_SPELLDAMAGE, RATE_CREATURE_ELITE_RAREELITE_DAMAGE, RATE_CREATURE_ELITE_RAREELITE_HP, RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE, RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE, RATE_CREATURE_ELITE_WORLDBOSS_HP, RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE, RATE_CREATURE_NORMAL_DAMAGE, RATE_CREATURE_NORMAL_HP, RATE_CREATURE_NORMAL_SPELLDAMAGE, RATE_DAMAGE_FALL, RATE_DROP_ITEM_ARTIFACT, RATE_DROP_ITEM_EPIC, RATE_DROP_ITEM_LEGENDARY, RATE_DROP_ITEM_NORMAL, RATE_DROP_ITEM_POOR, RATE_DROP_ITEM_RARE, RATE_DROP_ITEM_REFERENCED, RATE_DROP_ITEM_REFERENCED_AMOUNT, RATE_DROP_ITEM_UNCOMMON, RATE_DROP_MONEY, RATE_DURABILITY_LOSS_ABSORB, RATE_DURABILITY_LOSS_BLOCK, RATE_DURABILITY_LOSS_DAMAGE, RATE_DURABILITY_LOSS_ON_DEATH, RATE_DURABILITY_LOSS_PARRY, RATE_HEALTH, RATE_HONOR, RATE_INSTANCE_RESET_TIME, RATE_MOVESPEED, RATE_POWER_ENERGY, RATE_POWER_FOCUS, RATE_POWER_MANA, RATE_POWER_RAGE_INCOME, RATE_POWER_RAGE_LOSS, RATE_POWER_RUNICPOWER_INCOME, RATE_POWER_RUNICPOWER_LOSS, RATE_REPAIRCOST, RATE_REPUTATION_GAIN, RATE_REPUTATION_LOWLEVEL_KILL, RATE_REPUTATION_LOWLEVEL_QUEST, RATE_REPUTATION_RECRUIT_A_FRIEND_BONUS, RATE_REST_INGAME, RATE_REST_OFFLINE_IN_TAVERN_OR_CITY, RATE_REST_OFFLINE_IN_WILDERNESS, RATE_REWARD_BONUS_MONEY, RATE_SELLVALUE_ITEM_ARTIFACT, RATE_SELLVALUE_ITEM_EPIC, RATE_SELLVALUE_ITEM_HEIRLOOM, RATE_SELLVALUE_ITEM_LEGENDARY, RATE_SELLVALUE_ITEM_NORMAL, RATE_SELLVALUE_ITEM_POOR, RATE_SELLVALUE_ITEM_RARE, RATE_SELLVALUE_ITEM_UNCOMMON, RATE_SKILL_DISCOVERY, RATE_TALENT, RATE_TARGET_POS_RECALCULATION_RANGE, rate_values, RATE_XP_BG_KILL, RATE_XP_EXPLORE, RATE_XP_KILL, RATE_XP_PET, RATE_XP_PET_NEXT_LEVEL, RATE_XP_QUEST, realm, RealmHandle::Realm, REALM_ZONE_DEVELOPMENT, REALM_ZONE_RUSSIAN, IntervalTimer::Reset(), sConfigMgr, SEC_ADMINISTRATOR, SEC_CONSOLE, SEC_MODERATOR, VMAP::IVMapMgr::setEnableHeightCalc(), VMAP::IVMapMgr::setEnableLineOfSightCalc(), IntervalTimer::SetInterval(), Motd::SetMotd(), SetNewCharString(), SetPlayerAmountLimit(), sLog, sMapMgr, sMetric, sScriptMgr, sWorld, WUPDATE_AUTOBROADCAST, WUPDATE_CLEANDB, and WUPDATE_UPTIME.
Referenced by SetInitialWorldSettings().
LoadDBAllowedSecurityLevel()
void World::LoadDBAllowedSecurityLevel () virtual
Implements IWorld.
Definition at line 3107 of file World.cpp.
 {
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_REALMLIST_SECURITY_LEVEL);
     stmt->setInt32(0, int32(realm.Id.Realm));
     PreparedQueryResult result = LoginDatabase.Query(stmt);
     if (result)
         SetPlayerSecurityLimit(AccountTypes(result->Fetch()->GetUInt8()));
 }
References Realm::Id, LOGIN_SEL_REALMLIST_SECURITY_LEVEL, LoginDatabase, realm, RealmHandle::Realm, PreparedStatementBase::setInt32(), and SetPlayerSecurityLimit().
Referenced by SetInitialWorldSettings().
LoadDBRevision()
void World::LoadDBRevision () virtual
Implements IWorld.
Definition at line 3225 of file World.cpp.
 {
     QueryResult resultWorld     = WorldDatabase.Query("SELECT date FROM version_db_world ORDER BY date DESC LIMIT 1");
     QueryResult resultCharacter = CharacterDatabase.Query("SELECT date FROM version_db_characters ORDER BY date DESC LIMIT 1");
     QueryResult resultAuth      = LoginDatabase.Query("SELECT date FROM version_db_auth ORDER BY date DESC LIMIT 1");
     if (resultWorld)
     {
         Field* fields = resultWorld->Fetch();
         m_WorldDBRevision = fields[0].GetString();
     }
     if (resultCharacter)
     {
         Field* fields = resultCharacter->Fetch();
         m_CharacterDBRevision = fields[0].GetString();
     }
     if (resultAuth)
     {
         Field* fields = resultAuth->Fetch();
         m_AuthDBRevision = fields[0].GetString();
     }
     if (m_WorldDBRevision.empty())
     {
         m_WorldDBRevision = "Unkown World Database Revision";
     }
     if (m_CharacterDBRevision.empty())
     {
         m_CharacterDBRevision = "Unkown Character Database Revision";
     }
     if (m_AuthDBRevision.empty())
     {
         m_AuthDBRevision = "Unkown Auth Database Revision";
     }
 }
References CharacterDatabase, Field::GetString(), LoginDatabase, m_AuthDBRevision, m_CharacterDBRevision, m_WorldDBRevision, and WorldDatabase.
LoadDBVersion()
void World::LoadDBVersion () virtual
Implements IWorld.
Definition at line 3208 of file World.cpp.
 {
     QueryResult result = WorldDatabase.Query("SELECT db_version, cache_id FROM version LIMIT 1");
     if (result)
     {
         Field* fields = result->Fetch();
         m_DBVersion              = fields[0].GetString();
         // will be overwrite by config values if different and non-0
         m_int_configs[CONFIG_CLIENTCACHE_VERSION] = fields[1].GetUInt32();
     }
     if (m_DBVersion.empty())
         m_DBVersion = "Unknown world database.";
 }
References CONFIG_CLIENTCACHE_VERSION, Field::GetString(), Field::GetUInt32(), m_DBVersion, m_int_configs, and WorldDatabase.
LoadGlobalPlayerDataStore()
void World::LoadGlobalPlayerDataStore () virtual
Implements IWorld.
Definition at line 3337 of file World.cpp.
 {
     uint32 oldMSTime = getMSTime();
     _globalPlayerDataStore.clear();
     QueryResult result = CharacterDatabase.Query("SELECT guid, account, name, gender, race, class, level FROM characters WHERE deleteDate IS NULL");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 Players data.");
         return;
     }
     uint32 count = 0;
     // query to load number of mails by receiver
     std::map<uint32, uint16> _mailCountMap;
     QueryResult mailCountResult = CharacterDatabase.Query("SELECT receiver, COUNT(receiver) FROM mail GROUP BY receiver");
     if (mailCountResult)
     {
         do
         {
             Field* fields = mailCountResult->Fetch();
             _mailCountMap[fields[0].GetUInt32()] = uint16(fields[1].GetUInt64());
         } while (mailCountResult->NextRow());
     }
     do
     {
         Field* fields = result->Fetch();
         ObjectGuid::LowType guidLow = fields[0].GetUInt32();
         // count mails
         uint16 mailCount = 0;
         std::map<uint32, uint16>::const_iterator itr = _mailCountMap.find(guidLow);
         if (itr != _mailCountMap.end())
             mailCount = itr->second;
         AddGlobalPlayerData(
             guidLow,               /*guid*/
             fields[1].GetUInt32(), /*accountId*/
             fields[2].GetString(), /*name*/
             fields[3].GetUInt8(),  /*gender*/
             fields[4].GetUInt8(),  /*race*/
             fields[5].GetUInt8(),  /*class*/
             fields[6].GetUInt8(),  /*level*/
             mailCount,             /*mail count*/
             0                      /*guild id*/);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %d Players data in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _globalPlayerDataStore, AddGlobalPlayerData(), CharacterDatabase, count(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), and LOG_INFO.
LoadWorldStates()
void World::LoadWorldStates () virtual
Implements IWorld.
Definition at line 3275 of file World.cpp.
 {
     uint32 oldMSTime = getMSTime();
     QueryResult result = CharacterDatabase.Query("SELECT entry, value FROM worldstates");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 world states. DB table `worldstates` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         m_worldstates[fields[0].GetUInt32()] = fields[1].GetUInt32();
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u world states in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References CharacterDatabase, count(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_INFO, and m_worldstates.
Referenced by SetInitialWorldSettings().
ProcessCliCommands()
void World::ProcessCliCommands () virtual
Implements IWorld.
Definition at line 2879 of file World.cpp.
 {
     CliCommandHolder::Print zprint = nullptr;
     void* callbackArg = nullptr;
     CliCommandHolder* command = nullptr;
     while (cliCmdQueue.next(command))
     {
         LOG_DEBUG("server.worldserver", "CLI command under processing...");
         zprint = command->m_print;
         callbackArg = command->m_callbackArg;
         CliHandler handler(callbackArg, zprint);
         handler.ParseCommands(command->m_command);
         if (command->m_commandFinished)
             command->m_commandFinished(callbackArg, !handler.HasSentErrorMessage());
         delete command;
     }
 }
References cliCmdQueue, ChatHandler::HasSentErrorMessage(), LOG_DEBUG, CliCommandHolder::m_callbackArg, CliCommandHolder::m_command, CliCommandHolder::m_commandFinished, CliCommandHolder::m_print, LockedQueue< T, StorageType >::next(), and CliHandler::ParseCommands().
Referenced by Update().
ProcessQueryCallbacks()
void World::ProcessQueryCallbacks () private
Definition at line 3332 of file World.cpp.
 {
     _queryProcessor.ProcessReadyCallbacks();
 }
References _queryProcessor, and AsyncCallbackProcessor< T >::ProcessReadyCallbacks().
Referenced by Update().
QueueCliCommand()
void World::QueueCliCommand (CliCommandHolder * commandHolder) inline virtual
Implements IWorld.
Definition at line 367 of file World.h.
 { cliCmdQueue.add(commandHolder); }
References LockedQueue< T, StorageType >::add(), and cliCmdQueue.
RemoveOldCorpses()
void World::RemoveOldCorpses () virtual
Implements IWorld.
Definition at line 3591 of file World.cpp.
 {
     m_timers[WUPDATE_CORPSES].SetCurrent(m_timers[WUPDATE_CORPSES].GetInterval());
 }
References m_timers, IntervalTimer::SetCurrent(), and WUPDATE_CORPSES.
RemoveQueuedPlayer()
bool World::RemoveQueuedPlayer (WorldSession * session) virtual
Implements IWorld.
Definition at line 375 of file World.cpp.
 {
     uint32 sessions = GetActiveSessionCount();
     uint32 position = 1;
     Queue::iterator iter = m_QueuedPlayer.begin();
     // search to remove and count skipped positions
     bool found = false;
     for (; iter != m_QueuedPlayer.end(); ++iter, ++position)
     {
         if (*iter == sess)
         {
             sess->SetInQueue(false);
             sess->ResetTimeOutTime(false);
             iter = m_QueuedPlayer.erase(iter);
             found = true;
             break;
         }
     }
     // if session not queued then it was an active session
     if (!found)
     {
         ASSERT(sessions > 0);
         --sessions;
     }
     // accept first in queue
     if ((!GetPlayerAmountLimit() || sessions < GetPlayerAmountLimit()) && !m_QueuedPlayer.empty())
     {
         WorldSession* pop_sess = m_QueuedPlayer.front();
         pop_sess->SetInQueue(false);
         pop_sess->ResetTimeOutTime(false);
         pop_sess->SendAuthWaitQueue(0);
         pop_sess->SendAccountDataTimes(GLOBAL_CACHE_MASK);
         FinalizePlayerWorldSession(pop_sess);
         m_QueuedPlayer.pop_front();
         // update iter to point first queued socket or end() if queue is empty now
         iter = m_QueuedPlayer.begin();
         position = 1;
     }
     // update queue position from iter to end()
     for (; iter != m_QueuedPlayer.end(); ++iter, ++position)
         (*iter)->SendAuthWaitQueue(position);
     return found;
 }
References ASSERT, FinalizePlayerWorldSession(), GetActiveSessionCount(), GetPlayerAmountLimit(), GLOBAL_CACHE_MASK, m_QueuedPlayer, WorldSession::ResetTimeOutTime(), WorldSession::SendAccountDataTimes(), WorldSession::SendAuthWaitQueue(), and WorldSession::SetInQueue().
Referenced by AddSession_(), and UpdateSessions().
ResetDailyQuests()
void World::ResetDailyQuests () protected
Definition at line 3091 of file World.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_QUEST_STATUS_DAILY);
     CharacterDatabase.Execute(stmt);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetPlayer())
             itr->second->GetPlayer()->ResetDailyQuestStatus();
     m_NextDailyQuestReset = GetNextTimeWithDayAndHour(-1, 6);
     sWorld->setWorldState(WS_DAILY_QUEST_RESET_TIME, uint64(m_NextDailyQuestReset));
     // change available dailies
     sPoolMgr->ChangeDailyQuests();
 }
References CHAR_DEL_QUEST_STATUS_DAILY, CharacterDatabase, GetNextTimeWithDayAndHour(), m_NextDailyQuestReset, m_sessions, sPoolMgr, sWorld, and WS_DAILY_QUEST_RESET_TIME.
Referenced by Update().
ResetEventSeasonalQuests()
void World::ResetEventSeasonalQuests (uint16 event_id) virtual
Implements IWorld.
Definition at line 3157 of file World.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_QUEST_STATUS_SEASONAL);
     stmt->setUInt16(0, event_id);
     CharacterDatabase.Execute(stmt);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetPlayer())
             itr->second->GetPlayer()->ResetSeasonalQuestStatus(event_id);
 }
References CHAR_DEL_QUEST_STATUS_SEASONAL, CharacterDatabase, m_sessions, and PreparedStatementBase::setUInt16().
ResetGuildCap()
void World::ResetGuildCap () protected
Definition at line 3192 of file World.cpp.
 {
     LOG_INFO("server.worldserver", "Guild Daily Cap reset.");
     m_NextGuildReset = GetNextTimeWithDayAndHour(-1, 6);
     sWorld->setWorldState(WS_GUILD_DAILY_RESET_TIME, uint64(m_NextGuildReset));
     sGuildMgr->ResetTimes();
 }
References GetNextTimeWithDayAndHour(), LOG_INFO, m_NextGuildReset, sGuildMgr, sWorld, and WS_GUILD_DAILY_RESET_TIME.
Referenced by Update().
ResetMonthlyQuests()
void World::ResetMonthlyQuests () protected
Definition at line 3142 of file World.cpp.
 {
     LOG_INFO("server.worldserver", "Monthly quests reset for all characters.");
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_QUEST_STATUS_MONTHLY);
     CharacterDatabase.Execute(stmt);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetPlayer())
             itr->second->GetPlayer()->ResetMonthlyQuestStatus();
     m_NextMonthlyQuestReset = GetNextTimeWithMonthAndHour(-1, 6);
     sWorld->setWorldState(WS_MONTHLY_QUEST_RESET_TIME, uint64(m_NextMonthlyQuestReset));
 }
References CHAR_DEL_QUEST_STATUS_MONTHLY, CharacterDatabase, GetNextTimeWithMonthAndHour(), LOG_INFO, m_NextMonthlyQuestReset, m_sessions, sWorld, and WS_MONTHLY_QUEST_RESET_TIME.
Referenced by Update().
ResetRandomBG()
void World::ResetRandomBG () protected
Definition at line 3168 of file World.cpp.
 {
     LOG_DEBUG("server.worldserver", "Random BG status reset for all characters.");
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_BATTLEGROUND_RANDOM);
     CharacterDatabase.Execute(stmt);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetPlayer())
             itr->second->GetPlayer()->SetRandomWinner(false);
     m_NextRandomBGReset = GetNextTimeWithDayAndHour(-1, 6);
     sWorld->setWorldState(WS_BG_DAILY_RESET_TIME, uint64(m_NextRandomBGReset));
 }
References CHAR_DEL_BATTLEGROUND_RANDOM, CharacterDatabase, GetNextTimeWithDayAndHour(), LOG_DEBUG, m_NextRandomBGReset, m_sessions, sWorld, and WS_BG_DAILY_RESET_TIME.
Referenced by Update().
ResetWeeklyQuests()
void World::ResetWeeklyQuests () protected
Definition at line 3126 of file World.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_QUEST_STATUS_WEEKLY);
     CharacterDatabase.Execute(stmt);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second->GetPlayer())
             itr->second->GetPlayer()->ResetWeeklyQuestStatus();
     m_NextWeeklyQuestReset = GetNextTimeWithDayAndHour(4, 6);
     sWorld->setWorldState(WS_WEEKLY_QUEST_RESET_TIME, uint64(m_NextWeeklyQuestReset));
     // change available weeklies
     sPoolMgr->ChangeWeeklyQuests();
 }
References CHAR_DEL_QUEST_STATUS_WEEKLY, CharacterDatabase, GetNextTimeWithDayAndHour(), m_NextWeeklyQuestReset, m_sessions, sPoolMgr, sWorld, and WS_WEEKLY_QUEST_RESET_TIME.
Referenced by Update().
SendAutoBroadcast()
void World::SendAutoBroadcast () virtual
Implements IWorld.
Definition at line 2897 of file World.cpp.
 {
     if (m_Autobroadcasts.empty())
         return;
     uint32 weight = 0;
     AutobroadcastsWeightMap selectionWeights;
     std::string msg;
     for (AutobroadcastsWeightMap::const_iterator it = m_AutobroadcastsWeights.begin(); it != m_AutobroadcastsWeights.end(); ++it)
     {
         if (it->second)
         {
             weight += it->second;
             selectionWeights[it->first] = it->second;
         }
     }
     if (weight)
     {
         uint32 selectedWeight = urand(0, weight - 1);
         weight = 0;
         for (AutobroadcastsWeightMap::const_iterator it = selectionWeights.begin(); it != selectionWeights.end(); ++it)
         {
             weight += it->second;
             if (selectedWeight < weight)
             {
                 msg = m_Autobroadcasts[it->first];
                 break;
             }
         }
     }
     else
         msg = m_Autobroadcasts[urand(0, m_Autobroadcasts.size())];
     uint32 abcenter = sWorld->getIntConfig(CONFIG_AUTOBROADCAST_CENTER);
     if (abcenter == 0)
         sWorld->SendWorldText(LANG_AUTO_BROADCAST, msg.c_str());
     else if (abcenter == 1)
     {
         WorldPacket data(SMSG_NOTIFICATION, (msg.size() + 1));
         data << msg;
         sWorld->SendGlobalMessage(&data);
     }
     else if (abcenter == 2)
     {
         sWorld->SendWorldText(LANG_AUTO_BROADCAST, msg.c_str());
         WorldPacket data(SMSG_NOTIFICATION, (msg.size() + 1));
         data << msg;
         sWorld->SendGlobalMessage(&data);
     }
     LOG_DEBUG("server.worldserver", "AutoBroadcast: '%s'", msg.c_str());
 }
References CONFIG_AUTOBROADCAST_CENTER, LANG_AUTO_BROADCAST, LOG_DEBUG, m_Autobroadcasts, m_AutobroadcastsWeights, SMSG_NOTIFICATION, sWorld, and urand().
Referenced by Update().
SendGlobalGMMessage()
void World::SendGlobalGMMessage (WorldPacket * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL) virtual
Send a packet to all GMs (except self if mentioned)
Implements IWorld.
Definition at line 2511 of file World.cpp.
 {
     SessionMap::iterator itr;
     for (itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (itr->second &&
                 itr->second->GetPlayer() &&
                 itr->second->GetPlayer()->IsInWorld() &&
                 itr->second != self &&
                 !AccountMgr::IsPlayerAccount(itr->second->GetSecurity()) &&
                 (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
         {
             itr->second->SendPacket(packet);
         }
     }
 }
References AccountMgr::IsPlayerAccount(), m_sessions, and TEAM_NEUTRAL.
SendGlobalMessage()
void World::SendGlobalMessage (WorldPacket * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL) virtual
Send a packet to all players (except self if mentioned)
Implements IWorld.
Definition at line 2494 of file World.cpp.
 {
     SessionMap::const_iterator itr;
     for (itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (itr->second &&
                 itr->second->GetPlayer() &&
                 itr->second->GetPlayer()->IsInWorld() &&
                 itr->second != self &&
                 (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
         {
             itr->second->SendPacket(packet);
         }
     }
 }
References m_sessions, and TEAM_NEUTRAL.
Referenced by SendGlobalText(), SendServerMessage(), and UpdateGlobalPlayerData().
SendGlobalText()
void World::SendGlobalText (const char * text, WorldSession * self) virtual
DEPRECATED, only for debug purpose. Send a System Message to all players (except self if mentioned)
Implements IWorld.
Definition at line 2614 of file World.cpp.
 {
     WorldPacket data;
     // need copy to prevent corruption by strtok call in LineFromMessage original string
     char* buf = strdup(text);
     char* pos = buf;
     while (char* line = ChatHandler::LineFromMessage(pos))
     {
         ChatHandler::BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, line);
         SendGlobalMessage(&data, self);
     }
     free(buf);
 }
References ChatHandler::BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, ChatHandler::LineFromMessage(), pos(), and SendGlobalMessage().
SendGMText()
void World::SendGMText (uint32 string_id, ...) virtual
Send a System Message to all GMs (except self if mentioned)
Implements IWorld.
Definition at line 2592 of file World.cpp.
 {
     va_list ap;
     va_start(ap, string_id);
     Acore::WorldWorldTextBuilder wt_builder(string_id, &ap);
     Acore::LocalizedPacketListDo<Acore::WorldWorldTextBuilder> wt_do(wt_builder);
     for (SessionMap::iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (!itr->second || !itr->second->GetPlayer() || !itr->second->GetPlayer()->IsInWorld())
             continue;
         if (AccountMgr::IsPlayerAccount(itr->second->GetSecurity()))
             continue;
         wt_do(itr->second->GetPlayer());
     }
     va_end(ap);
 }
References AccountMgr::IsPlayerAccount(), and m_sessions.
SendServerMessage()
void World::SendServerMessage (ServerMessageType type, const char * text = "", Player * player = nullptr) virtual
Send a server message to the user(s)
Implements IWorld.
Definition at line 2787 of file World.cpp.
 {
     WorldPacket data(SMSG_SERVER_MESSAGE, 50);              // guess size
     data << uint32(type);
     if (type <= SERVER_MSG_STRING)
         data << text;
     if (player)
         player->GetSession()->SendPacket(&data);
     else
         SendGlobalMessage(&data);
 }
References Player::GetSession(), SendGlobalMessage(), WorldSession::SendPacket(), SERVER_MSG_STRING, and SMSG_SERVER_MESSAGE.
Referenced by ShutdownCancel(), and ShutdownMsg().
SendWorldText()
void World::SendWorldText (uint32 string_id, ...) virtual
Send a System Message to all players (except self if mentioned)
Implements IWorld.
Definition at line 2573 of file World.cpp.
 {
     va_list ap;
     va_start(ap, string_id);
     Acore::WorldWorldTextBuilder wt_builder(string_id, &ap);
     Acore::LocalizedPacketListDo<Acore::WorldWorldTextBuilder> wt_do(wt_builder);
     for (SessionMap::const_iterator itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (!itr->second || !itr->second->GetPlayer() || !itr->second->GetPlayer()->IsInWorld())
             continue;
         wt_do(itr->second->GetPlayer());
     }
     va_end(ap);
 }
References m_sessions.
SendZoneMessage()
bool World::SendZoneMessage (uint32 zone, WorldPacket * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL) virtual
Send a packet to all players (or players selected team) in the zone (except self if mentioned)
Implements IWorld.
Definition at line 2632 of file World.cpp.
 {
     bool foundPlayerToSend = false;
     SessionMap::const_iterator itr;
     for (itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
     {
         if (itr->second &&
                 itr->second->GetPlayer() &&
                 itr->second->GetPlayer()->IsInWorld() &&
                 itr->second->GetPlayer()->GetZoneId() == zone &&
                 itr->second != self &&
                 (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
         {
             itr->second->SendPacket(packet);
             foundPlayerToSend = true;
         }
     }
     return foundPlayerToSend;
 }
References m_sessions, and TEAM_NEUTRAL.
Referenced by SendZoneText().
SendZoneText()
void World::SendZoneText (uint32 zone, const char * text, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL) virtual
Send a System Message to all players in the zone (except self if mentioned)
Implements IWorld.
Definition at line 2655 of file World.cpp.
 {
     WorldPacket data;
     ChatHandler::BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, text);
     SendZoneMessage(zone, &data, self, teamId);
 }
References ChatHandler::BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, and SendZoneMessage().
SetAllowMovement()
void World::SetAllowMovement (bool allow) inline virtual
Allow/Disallow object movements.
Implements IWorld.
Definition at line 229 of file World.h.
 { m_allowMovement = allow; }
References m_allowMovement.
setBoolConfig()
void World::setBoolConfig (WorldBoolConfigs index, bool value) inline virtual
Set a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 296 of file World.h.
     {
         if (index < BOOL_CONFIG_VALUE_COUNT)
             m_bool_configs[index] = value;
     }
References BOOL_CONFIG_VALUE_COUNT, index, and m_bool_configs.
SetCleaningFlags()
void World::SetCleaningFlags (uint32 flags) inline virtual
Implements IWorld.
Definition at line 388 of file World.h.
 { m_CleaningFlags = flags; }
References m_CleaningFlags.
SetClosed()
void World::SetClosed (bool val) virtual
Close world.
Implements IWorld.
Definition at line 206 of file World.cpp.
 {
     m_isClosed = val;
     // Invert the value, for simplicity for scripters.
     sScriptMgr->OnOpenStateChange(!val);
 }
References m_isClosed, and sScriptMgr.
setFloatConfig()
void World::setFloatConfig (WorldFloatConfigs index, float value) inline virtual
Set a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 309 of file World.h.
     {
         if (index < FLOAT_CONFIG_VALUE_COUNT)
             m_float_configs[index] = value;
     }
References FLOAT_CONFIG_VALUE_COUNT, index, and m_float_configs.
SetInitialWorldSettings()
void World::SetInitialWorldSettings () virtual
Initialize the World.
Server startup begin
Initialize the random number generator
Initialize detour memory management
Initialize VMapMgr function pointers (to untangle game/collision circular deps)
Initialize config settings
Initialize Allowed Security Level
Init highest guids before any table loading to prevent using not initialized guids in some code.
Check the existence of the map files for all starting areas.
Initialize pool manager
Initialize game event manager
Loading strings. Getting no records means core load has to be canceled because no error message can be output.
Update the realm entry in the database with the realm type from the config file
Custom Hook for loading DB items
Load the DBC files
Load dynamic data tables from the database
Handle outdated emails (delete/return)
Load AutoBroadCast
Load and initialize scripts
Initialize game time and timers
Initilize static helper structures
Initialize MapMgr
Initialize Battlegrounds
Initialize outdoor pvp
Initialize Battlefield
Initialize Warden
Implements IWorld.
Definition at line 1447 of file World.cpp.
 {
     uint32 startupBegin = getMSTime();
     srand((unsigned int)time(nullptr));
     dtAllocSetCustom(dtCustomAlloc, dtCustomFree);
     VMAP::VMapMgr2* vmmgr2 = VMAP::VMapFactory::createOrGetVMapMgr();
     vmmgr2->GetLiquidFlagsPtr = &GetLiquidFlags;
     vmmgr2->IsVMAPDisabledForPtr = &DisableMgr::IsVMAPDisabledFor;
     LoadConfigSettings();
     LoadDBAllowedSecurityLevel();
     sObjectMgr->SetHighestGuids();
     if (!sConfigMgr->isDryRun())
     {
         if (!MapMgr::ExistMapAndVMap(0, -6240.32f, 331.033f)
                 || !MapMgr::ExistMapAndVMap(0, -8949.95f, -132.493f)
                 || !MapMgr::ExistMapAndVMap(1, -618.518f, -4251.67f)
                 || !MapMgr::ExistMapAndVMap(0, 1676.35f, 1677.45f)
                 || !MapMgr::ExistMapAndVMap(1, 10311.3f, 832.463f)
                 || !MapMgr::ExistMapAndVMap(1, -2917.58f, -257.98f)
                 || (m_int_configs[CONFIG_EXPANSION] && (
                         !MapMgr::ExistMapAndVMap(530, 10349.6f, -6357.29f) ||
                         !MapMgr::ExistMapAndVMap(530, -3961.64f, -13931.2f))))
         {
             exit(1);
         }
     }
     sPoolMgr->Initialize();
     sGameEventMgr->Initialize();
     LOG_INFO("server.loading", " ");
     LOG_INFO("server.loading", "Loading acore strings...");
     if (!sObjectMgr->LoadAcoreStrings())
         exit(1);                                            // Error message displayed in function already
     //No SQL injection as values are treated as integers
     // not send custom type REALM_FFA_PVP to realm list
     uint32 server_type;
     if (IsFFAPvPRealm())
         server_type = REALM_TYPE_PVP;
     else
         server_type = getIntConfig(CONFIG_GAME_TYPE);
     uint32 realm_zone = getIntConfig(CONFIG_REALM_ZONE);
     LoginDatabase.PExecute("UPDATE realmlist SET icon = %u, timezone = %u WHERE id = '%d'", server_type, realm_zone, realm.Id.Realm);      // One-time query
     sScriptMgr->OnLoadCustomDatabaseTable();
     LOG_INFO("server.loading", "Initialize data stores...");
     LoadDBCStores(m_dataPath);
     DetectDBCLang();
     // Load IP Location Database
     sIPLocation->Load();
     std::vector<uint32> mapIds;
     for (auto const map : sMapStore)
     {
         mapIds.emplace_back(map->MapID);
     }
     vmmgr2->InitializeThreadUnsafe(mapIds);
     MMAP::MMapMgr* mmmgr = MMAP::MMapFactory::createOrGetMMapMgr();
     mmmgr->InitializeThreadUnsafe(mapIds);
     LOG_INFO("server.loading", "Loading Game Graveyard...");
     sGraveyard->LoadGraveyardFromDB();
     LOG_INFO("server.loading", "Loading spell dbc data corrections...");
     sSpellMgr->LoadDbcDataCorrections();
     LOG_INFO("server.loading", "Loading SpellInfo store...");
     sSpellMgr->LoadSpellInfoStore();
     LOG_INFO("server.loading", "Loading Spell Rank Data...");
     sSpellMgr->LoadSpellRanks();
     LOG_INFO("server.loading", "Loading Spell Specific And Aura State...");
     sSpellMgr->LoadSpellSpecificAndAuraState();
     LOG_INFO("server.loading", "Loading SkillLineAbilityMultiMap Data...");
     sSpellMgr->LoadSkillLineAbilityMap();
     LOG_INFO("server.loading", "Loading spell custom attributes...");
     sSpellMgr->LoadSpellCustomAttr();
     LOG_INFO("server.loading", "Loading GameObject models...");
     LoadGameObjectModelList(m_dataPath);
     LOG_INFO("server.loading", "Loading Script Names...");
     sObjectMgr->LoadScriptNames();
     LOG_INFO("server.loading", "Loading Instance Template...");
     sObjectMgr->LoadInstanceTemplate();
     // xinef: Global Storage, should be loaded asap
     LOG_INFO("server.loading", "Load Global Player Data...");
     sWorld->LoadGlobalPlayerDataStore();
     // Must be called before `creature_respawn`/`gameobject_respawn` tables
     LOG_INFO("server.loading", "Loading instances...");
     sInstanceSaveMgr->LoadInstances();
     LOG_INFO("server.loading", "Loading Broadcast texts...");
     sObjectMgr->LoadBroadcastTexts();
     sObjectMgr->LoadBroadcastTextLocales();
     LOG_INFO("server.loading", "Loading Localization strings...");
     uint32 oldMSTime = getMSTime();
     sObjectMgr->LoadCreatureLocales();
     sObjectMgr->LoadGameObjectLocales();
     sObjectMgr->LoadItemLocales();
     sObjectMgr->LoadItemSetNameLocales();
     sObjectMgr->LoadQuestLocales();
     sObjectMgr->LoadQuestOfferRewardLocale();
     sObjectMgr->LoadQuestRequestItemsLocale();
     sObjectMgr->LoadNpcTextLocales();
     sObjectMgr->LoadPageTextLocales();
     sObjectMgr->LoadGossipMenuItemsLocales();
     sObjectMgr->LoadPointOfInterestLocales();
     sObjectMgr->SetDBCLocaleIndex(GetDefaultDbcLocale());        // Get once for all the locale index of DBC language (console/broadcasts)
     LOG_INFO("server.loading", ">> Localization strings loaded in %u ms", GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
     LOG_INFO("server.loading", "Loading Page Texts...");
     sObjectMgr->LoadPageTexts();
     LOG_INFO("server.loading", "Loading Game Object Templates...");         // must be after LoadPageTexts
     sObjectMgr->LoadGameObjectTemplate();
     LOG_INFO("server.loading", "Loading Game Object template addons...");
     sObjectMgr->LoadGameObjectTemplateAddons();
     LOG_INFO("server.loading", "Loading Transport templates...");
     sTransportMgr->LoadTransportTemplates();
     LOG_INFO("server.loading", "Loading Spell Required Data...");
     sSpellMgr->LoadSpellRequired();
     LOG_INFO("server.loading", "Loading Spell Group types...");
     sSpellMgr->LoadSpellGroups();
     LOG_INFO("server.loading", "Loading Spell Learn Skills...");
     sSpellMgr->LoadSpellLearnSkills();                           // must be after LoadSpellRanks
     LOG_INFO("server.loading", "Loading Spell Proc Event conditions...");
     sSpellMgr->LoadSpellProcEvents();
     LOG_INFO("server.loading", "Loading Spell Proc conditions and data...");
     sSpellMgr->LoadSpellProcs();
     LOG_INFO("server.loading", "Loading Spell Bonus Data...");
     sSpellMgr->LoadSpellBonusess();
     LOG_INFO("server.loading", "Loading Aggro Spells Definitions...");
     sSpellMgr->LoadSpellThreats();
     LOG_INFO("server.loading", "Loading Mixology bonuses...");
     sSpellMgr->LoadSpellMixology();
     LOG_INFO("server.loading", "Loading Spell Group Stack Rules...");
     sSpellMgr->LoadSpellGroupStackRules();
     LOG_INFO("server.loading", "Loading NPC Texts...");
     sObjectMgr->LoadGossipText();
     LOG_INFO("server.loading", "Loading Enchant Spells Proc datas...");
     sSpellMgr->LoadSpellEnchantProcData();
     LOG_INFO("server.loading", "Loading Item Random Enchantments Table...");
     LoadRandomEnchantmentsTable();
     LOG_INFO("server.loading", "Loading Disables");
     DisableMgr::LoadDisables();                                  // must be before loading quests and items
     LOG_INFO("server.loading", "Loading Items...");                         // must be after LoadRandomEnchantmentsTable and LoadPageTexts
     sObjectMgr->LoadItemTemplates();
     LOG_INFO("server.loading", "Loading Item set names...");                // must be after LoadItemPrototypes
     sObjectMgr->LoadItemSetNames();
     LOG_INFO("server.loading", "Loading Creature Model Based Info Data...");
     sObjectMgr->LoadCreatureModelInfo();
     LOG_INFO("server.loading", "Loading Creature templates...");
     sObjectMgr->LoadCreatureTemplates();
     LOG_INFO("server.loading", "Loading Equipment templates...");           // must be after LoadCreatureTemplates
     sObjectMgr->LoadEquipmentTemplates();
     LOG_INFO("server.loading", "Loading Creature template addons...");
     sObjectMgr->LoadCreatureTemplateAddons();
     LOG_INFO("server.loading", "Loading Reputation Reward Rates...");
     sObjectMgr->LoadReputationRewardRate();
     LOG_INFO("server.loading", "Loading Creature Reputation OnKill Data...");
     sObjectMgr->LoadReputationOnKill();
     LOG_INFO("server.loading", "Loading Reputation Spillover Data..." );
     sObjectMgr->LoadReputationSpilloverTemplate();
     LOG_INFO("server.loading", "Loading Points Of Interest Data...");
     sObjectMgr->LoadPointsOfInterest();
     LOG_INFO("server.loading", "Loading Creature Base Stats...");
     sObjectMgr->LoadCreatureClassLevelStats();
     LOG_INFO("server.loading", "Loading Creature Data...");
     sObjectMgr->LoadCreatures();
     LOG_INFO("server.loading", "Loading Temporary Summon Data...");
     sObjectMgr->LoadTempSummons();                               // must be after LoadCreatureTemplates() and LoadGameObjectTemplates()
     LOG_INFO("server.loading", "Loading pet levelup spells...");
     sSpellMgr->LoadPetLevelupSpellMap();
     LOG_INFO("server.loading", "Loading pet default spells additional to levelup spells...");
     sSpellMgr->LoadPetDefaultSpells();
     LOG_INFO("server.loading", "Loading Creature Addon Data...");
     sObjectMgr->LoadCreatureAddons();                            // must be after LoadCreatureTemplates() and LoadCreatures()
     LOG_INFO("server.loading", "Loading Gameobject Data...");
     sObjectMgr->LoadGameobjects();
     LOG_INFO("server.loading", "Loading GameObject Addon Data...");
     sObjectMgr->LoadGameObjectAddons();                          // must be after LoadGameObjectTemplate() and LoadGameobjects()
     LOG_INFO("server.loading", "Loading GameObject Quest Items...");
     sObjectMgr->LoadGameObjectQuestItems();
     LOG_INFO("server.loading", "Loading Creature Quest Items...");
     sObjectMgr->LoadCreatureQuestItems();
     LOG_INFO("server.loading", "Loading Creature Linked Respawn...");
     sObjectMgr->LoadLinkedRespawn();                             // must be after LoadCreatures(), LoadGameObjects()
     LOG_INFO("server.loading", "Loading Weather Data...");
     WeatherMgr::LoadWeatherData();
     LOG_INFO("server.loading", "Loading Quests...");
     sObjectMgr->LoadQuests();                                    // must be loaded after DBCs, creature_template, item_template, gameobject tables
     LOG_INFO("server.loading", "Checking Quest Disables");
     DisableMgr::CheckQuestDisables();                           // must be after loading quests
     LOG_INFO("server.loading", "Loading Quest POI");
     sObjectMgr->LoadQuestPOI();
     LOG_INFO("server.loading", "Loading Quests Starters and Enders...");
     sObjectMgr->LoadQuestStartersAndEnders();                    // must be after quest load
     LOG_INFO("server.loading", "Loading Quest Money Rewards...");
     sObjectMgr->LoadQuestMoneyRewards();
     LOG_INFO("server.loading", "Loading Objects Pooling Data...");
     sPoolMgr->LoadFromDB();
     LOG_INFO("server.loading", "Loading Game Event Data...");               // must be after loading pools fully
     sGameEventMgr->LoadHolidayDates();                           // Must be after loading DBC
     sGameEventMgr->LoadFromDB();                                 // Must be after loading holiday dates
     LOG_INFO("server.loading", "Loading UNIT_NPC_FLAG_SPELLCLICK Data..."); // must be after LoadQuests
     sObjectMgr->LoadNPCSpellClickSpells();
     LOG_INFO("server.loading", "Loading Vehicle Template Accessories...");
     sObjectMgr->LoadVehicleTemplateAccessories();                // must be after LoadCreatureTemplates() and LoadNPCSpellClickSpells()
     LOG_INFO("server.loading", "Loading Vehicle Accessories...");
     sObjectMgr->LoadVehicleAccessories();                       // must be after LoadCreatureTemplates() and LoadNPCSpellClickSpells()
     LOG_INFO("server.loading", "Loading SpellArea Data...");                // must be after quest load
     sSpellMgr->LoadSpellAreas();
     LOG_INFO("server.loading", "Loading Area Trigger definitions");
     sObjectMgr->LoadAreaTriggers();
     LOG_INFO("server.loading", "Loading Area Trigger Teleport definitions...");
     sObjectMgr->LoadAreaTriggerTeleports();
     LOG_INFO("server.loading", "Loading Access Requirements...");
     sObjectMgr->LoadAccessRequirements();                        // must be after item template load
     LOG_INFO("server.loading", "Loading Quest Area Triggers...");
     sObjectMgr->LoadQuestAreaTriggers();                         // must be after LoadQuests
     LOG_INFO("server.loading", "Loading Tavern Area Triggers...");
     sObjectMgr->LoadTavernAreaTriggers();
     LOG_INFO("server.loading", "Loading AreaTrigger script names...");
     sObjectMgr->LoadAreaTriggerScripts();
     LOG_INFO("server.loading", "Loading LFG entrance positions..."); // Must be after areatriggers
     sLFGMgr->LoadLFGDungeons();
     LOG_INFO("server.loading", "Loading Dungeon boss data...");
     sObjectMgr->LoadInstanceEncounters();
     LOG_INFO("server.loading", "Loading LFG rewards...");
     sLFGMgr->LoadRewards();
     LOG_INFO("server.loading", "Loading Graveyard-zone links...");
     sGraveyard->LoadGraveyardZones();
     LOG_INFO("server.loading", "Loading spell pet auras...");
     sSpellMgr->LoadSpellPetAuras();
     LOG_INFO("server.loading", "Loading Spell target coordinates...");
     sSpellMgr->LoadSpellTargetPositions();
     LOG_INFO("server.loading", "Loading enchant custom attributes...");
     sSpellMgr->LoadEnchantCustomAttr();
     LOG_INFO("server.loading", "Loading linked spells...");
     sSpellMgr->LoadSpellLinked();
     LOG_INFO("server.loading", "Loading Player Create Data...");
     sObjectMgr->LoadPlayerInfo();
     LOG_INFO("server.loading", "Loading Exploration BaseXP Data...");
     sObjectMgr->LoadExplorationBaseXP();
     LOG_INFO("server.loading", "Loading Pet Name Parts...");
     sObjectMgr->LoadPetNames();
     CharacterDatabaseCleaner::CleanDatabase();
     LOG_INFO("server.loading", "Loading the max pet number...");
     sObjectMgr->LoadPetNumber();
     LOG_INFO("server.loading", "Loading pet level stats...");
     sObjectMgr->LoadPetLevelInfo();
     LOG_INFO("server.loading", "Loading Player level dependent mail rewards...");
     sObjectMgr->LoadMailLevelRewards();
     // Loot tables
     LoadLootTables();
     LOG_INFO("server.loading", "Loading Skill Discovery Table...");
     LoadSkillDiscoveryTable();
     LOG_INFO("server.loading", "Loading Skill Extra Item Table...");
     LoadSkillExtraItemTable();
     LOG_INFO("server.loading", "Loading Skill Perfection Data Table...");
     LoadSkillPerfectItemTable();
     LOG_INFO("server.loading", "Loading Skill Fishing base level requirements...");
     sObjectMgr->LoadFishingBaseSkillLevel();
     LOG_INFO("server.loading", "Loading Achievements...");
     sAchievementMgr->LoadAchievementReferenceList();
     LOG_INFO("server.loading", "Loading Achievement Criteria Lists...");
     sAchievementMgr->LoadAchievementCriteriaList();
     LOG_INFO("server.loading", "Loading Achievement Criteria Data...");
     sAchievementMgr->LoadAchievementCriteriaData();
     LOG_INFO("server.loading", "Loading Achievement Rewards...");
     sAchievementMgr->LoadRewards();
     LOG_INFO("server.loading", "Loading Achievement Reward Locales...");
     sAchievementMgr->LoadRewardLocales();
     LOG_INFO("server.loading", "Loading Completed Achievements...");
     sAchievementMgr->LoadCompletedAchievements();
     LOG_INFO("server.loading", "Loading Item Auctions...");
     sAuctionMgr->LoadAuctionItems();
     LOG_INFO("server.loading", "Loading Auctions...");
     sAuctionMgr->LoadAuctions();
     sGuildMgr->LoadGuilds();
     LOG_INFO("server.loading", "Loading ArenaTeams...");
     sArenaTeamMgr->LoadArenaTeams();
     LOG_INFO("server.loading", "Loading Groups...");
     sGroupMgr->LoadGroups();
     LOG_INFO("server.loading", "Loading ReservedNames...");
     sObjectMgr->LoadReservedPlayersNames();
     LOG_INFO("server.loading", "Loading GameObjects for quests...");
     sObjectMgr->LoadGameObjectForQuests();
     LOG_INFO("server.loading", "Loading BattleMasters...");
     sBattlegroundMgr->LoadBattleMastersEntry();
     LOG_INFO("server.loading", "Loading GameTeleports...");
     sObjectMgr->LoadGameTele();
     LOG_INFO("server.loading", "Loading Gossip menu...");
     sObjectMgr->LoadGossipMenu();
     LOG_INFO("server.loading", "Loading Gossip menu options...");
     sObjectMgr->LoadGossipMenuItems();
     LOG_INFO("server.loading", "Loading Vendors...");
     sObjectMgr->LoadVendors();                                   // must be after load CreatureTemplate and ItemTemplate
     LOG_INFO("server.loading", "Loading Trainers...");
     sObjectMgr->LoadTrainerSpell();                              // must be after load CreatureTemplate
     LOG_INFO("server.loading", "Loading Waypoints...");
     sWaypointMgr->Load();
     LOG_INFO("server.loading", "Loading SmartAI Waypoints...");
     sSmartWaypointMgr->LoadFromDB();
     LOG_INFO("server.loading", "Loading Creature Formations...");
     sFormationMgr->LoadCreatureFormations();
     LOG_INFO("server.loading", "Loading World States...");              // must be loaded before battleground, outdoor PvP and conditions
     LoadWorldStates();
     LOG_INFO("server.loading", "Loading Conditions...");
     sConditionMgr->LoadConditions();
     LOG_INFO("server.loading", "Loading faction change achievement pairs...");
     sObjectMgr->LoadFactionChangeAchievements();
     LOG_INFO("server.loading", "Loading faction change spell pairs...");
     sObjectMgr->LoadFactionChangeSpells();
     LOG_INFO("server.loading", "Loading faction change item pairs...");
     sObjectMgr->LoadFactionChangeItems();
     LOG_INFO("server.loading", "Loading faction change reputation pairs...");
     sObjectMgr->LoadFactionChangeReputations();
     LOG_INFO("server.loading", "Loading faction change title pairs...");
     sObjectMgr->LoadFactionChangeTitles();
     LOG_INFO("server.loading", "Loading faction change quest pairs...");
     sObjectMgr->LoadFactionChangeQuests();
     LOG_INFO("server.loading", "Loading GM tickets...");
     sTicketMgr->LoadTickets();
     LOG_INFO("server.loading", "Loading GM surveys...");
     sTicketMgr->LoadSurveys();
     LOG_INFO("server.loading", "Loading client addons...");
     AddonMgr::LoadFromDB();
     // pussywizard:
     LOG_INFO("server.loading", "Deleting invalid mail items...");
     LOG_INFO("server.loading", " ");
     CharacterDatabase.Execute("DELETE mi FROM mail_items mi LEFT JOIN item_instance ii ON mi.item_guid = ii.guid WHERE ii.guid IS NULL");
     CharacterDatabase.Execute("DELETE mi FROM mail_items mi LEFT JOIN mail m ON mi.mail_id = m.id WHERE m.id IS NULL");
     CharacterDatabase.Execute("UPDATE mail m LEFT JOIN mail_items mi ON m.id = mi.mail_id SET m.has_items=0 WHERE m.has_items<>0 AND mi.mail_id IS NULL");
     LOG_INFO("server.loading", "Returning old mails...");
     LOG_INFO("server.loading", " ");
     sObjectMgr->ReturnOrDeleteOldMails(false);
     LOG_INFO("server.loading", "Loading Autobroadcasts...");
     LoadAutobroadcasts();
     sObjectMgr->LoadSpellScripts();                              // must be after load Creature/Gameobject(Template/Data)
     sObjectMgr->LoadEventScripts();                              // must be after load Creature/Gameobject(Template/Data)
     sObjectMgr->LoadWaypointScripts();
     LOG_INFO("server.loading", "Loading spell script names...");
     sObjectMgr->LoadSpellScriptNames();
     LOG_INFO("server.loading", "Loading Creature Texts...");
     sCreatureTextMgr->LoadCreatureTexts();
     LOG_INFO("server.loading", "Loading Creature Text Locales...");
     sCreatureTextMgr->LoadCreatureTextLocales();
     LOG_INFO("server.loading", "Loading Scripts...");
     sScriptMgr->LoadDatabase();
     LOG_INFO("server.loading", "Validating spell scripts...");
     sObjectMgr->ValidateSpellScripts();
     LOG_INFO("server.loading", "Loading SmartAI scripts...");
     sSmartScriptMgr->LoadSmartAIFromDB();
     LOG_INFO("server.loading", "Loading Calendar data...");
     sCalendarMgr->LoadFromDB();
     LOG_INFO("server.loading", "Initializing SpellInfo precomputed data..."); // must be called after loading items, professions, spells and pretty much anything
     LOG_INFO("server.loading", " ");
     sObjectMgr->InitializeSpellInfoPrecomputedData();
     LOG_INFO("server.loading", "Initialize commands...");
     Acore::ChatCommands::LoadCommandMap();
     LOG_INFO("server.loading", "Initialize game time and timers");
     LOG_INFO("server.loading", " ");
     m_gameTime = time(nullptr);
     m_startTime = m_gameTime;
     LoginDatabase.PExecute("INSERT INTO uptime (realmid, starttime, uptime, revision) VALUES(%u, %u, 0, '%s')",
                            realm.Id.Realm, uint32(m_startTime), GitRevision::GetFullVersion());       // One-time query
     m_timers[WUPDATE_WEATHERS].SetInterval(1 * IN_MILLISECONDS);
     m_timers[WUPDATE_AUCTIONS].SetInterval(MINUTE * IN_MILLISECONDS);
     m_timers[WUPDATE_AUCTIONS].SetCurrent(MINUTE * IN_MILLISECONDS);
     m_timers[WUPDATE_UPTIME].SetInterval(m_int_configs[CONFIG_UPTIME_UPDATE]*MINUTE * IN_MILLISECONDS);
     //Update "uptime" table based on configuration entry in minutes.
     m_timers[WUPDATE_CORPSES].SetInterval(20 * MINUTE * IN_MILLISECONDS);
     //erase corpses every 20 minutes
     m_timers[WUPDATE_CLEANDB].SetInterval(m_int_configs[CONFIG_LOGDB_CLEARINTERVAL]*MINUTE * IN_MILLISECONDS);
     // clean logs table every 14 days by default
     m_timers[WUPDATE_AUTOBROADCAST].SetInterval(getIntConfig(CONFIG_AUTOBROADCAST_INTERVAL));
     m_timers[WUPDATE_PINGDB].SetInterval(getIntConfig(CONFIG_DB_PING_INTERVAL)*MINUTE * IN_MILLISECONDS);  // Mysql ping time in minutes
     // our speed up
     m_timers[WUPDATE_5_SECS].SetInterval(5 * IN_MILLISECONDS);
     m_timers[WUPDATE_WHO_LIST].SetInterval(5 * IN_MILLISECONDS); // update who list cache every 5 seconds
     mail_expire_check_timer = time(nullptr) + 6 * 3600;
     AIRegistry::Initialize();
     LOG_INFO("server.loading", "Starting Map System");
     LOG_INFO("server.loading", " ");
     sMapMgr->Initialize();
     LOG_INFO("server.loading", "Starting Game Event system...");
     LOG_INFO("server.loading", " ");
     uint32 nextGameEvent = sGameEventMgr->StartSystem();
     m_timers[WUPDATE_EVENTS].SetInterval(nextGameEvent);    //depend on next event
     // Delete all characters which have been deleted X days before
     Player::DeleteOldCharacters();
     // Delete all custom channels which haven't been used for PreserveCustomChannelDuration days.
     Channel::CleanOldChannelsInDB();
     LOG_INFO("server.loading", "Initializing Opcodes...");
     opcodeTable.Initialize();
     LOG_INFO("server.loading", "Starting Arena Season...");
     LOG_INFO("server.loading", " ");
     sGameEventMgr->StartArenaSeason();
     sTicketMgr->Initialize();
     LOG_INFO("server.loading", "Starting Battleground System");
     sBattlegroundMgr->CreateInitialBattlegrounds();
     sBattlegroundMgr->InitAutomaticArenaPointDistribution();
     LOG_INFO("server.loading", "Starting Outdoor PvP System");
     sOutdoorPvPMgr->InitOutdoorPvP();
     LOG_INFO("server.loading", "Starting Battlefield System");
     sBattlefieldMgr->InitBattlefield();
     LOG_INFO("server.loading", "Loading Transports...");
     sTransportMgr->SpawnContinentTransports();
     LOG_INFO("server.loading", "Loading Warden Checks..." );
     sWardenCheckMgr->LoadWardenChecks();
     LOG_INFO("server.loading", "Loading Warden Action Overrides..." );
     sWardenCheckMgr->LoadWardenOverrides();
     LOG_INFO("server.loading", "Deleting expired bans...");
     LoginDatabase.Execute("DELETE FROM ip_banned WHERE unbandate <= UNIX_TIMESTAMP() AND unbandate<>bandate");      // One-time query
     LOG_INFO("server.loading", "Calculate next daily quest reset time...");
     InitDailyQuestResetTime();
     LOG_INFO("server.loading", "Calculate next weekly quest reset time..." );
     InitWeeklyQuestResetTime();
     LOG_INFO("server.loading", "Calculate next monthly quest reset time...");
     InitMonthlyQuestResetTime();
     LOG_INFO("server.loading", "Calculate random battleground reset time..." );
     InitRandomBGResetTime();
     LOG_INFO("server.loading", "Calculate deletion of old calendar events time...");
     InitCalendarOldEventsDeletionTime();
     LOG_INFO("server.loading", "Calculate Guild cap reset time...");
     LOG_INFO("server.loading", " ");
     InitGuildResetTime();
     LOG_INFO("server.loading", "Load Petitions...");
     sPetitionMgr->LoadPetitions();
     LOG_INFO("server.loading", "Load Petition Signs...");
     sPetitionMgr->LoadSignatures();
     LOG_INFO("server.loading", "Load Stored Loot Items...");
     sLootItemStorage->LoadStorageFromDB();
     LOG_INFO("server.loading", "Load Channel Rights...");
     ChannelMgr::LoadChannelRights();
     LOG_INFO("server.loading", "Load Channels...");
     ChannelMgr::LoadChannels();
 #ifdef ELUNA
     // in multithread foreach: run scripts
     sEluna->RunScripts();
     sEluna->OnConfigLoad(false, false); // Must be done after Eluna is initialized and scripts have run.
 #endif
     if (sWorld->getBoolConfig(CONFIG_PRELOAD_ALL_NON_INSTANCED_MAP_GRIDS))
     {
         LOG_INFO("server.loading", "Loading all grids for all non-instanced maps...");
         for (uint32 i = 0; i < sMapStore.GetNumRows(); ++i)
         {
             MapEntry const* mapEntry = sMapStore.LookupEntry(i);
             if (mapEntry && !mapEntry->Instanceable())
             {
                 Map* map = sMapMgr->CreateBaseMap(mapEntry->MapID);
                 if (map)
                 {
                     LOG_INFO("server.loading", ">> Loading all grids for map %u", map->GetId());
                     map->LoadAllCells();
                 }
             }
         }
     }
     uint32 startupDuration = GetMSTimeDiffToNow(startupBegin);
     LOG_INFO("server.loading", " ");
     LOG_INFO("server.loading", "WORLD: World initialized in %u minutes %u seconds", (startupDuration / 60000), ((startupDuration % 60000) / 1000)); // outError for red color in console
     LOG_INFO("server.loading", " ");
     METRIC_EVENT("events", "World initialized", "World initialized in " + std::to_string(startupDuration / 60000) + " minutes " + std::to_string((startupDuration % 60000) / 1000) + " seconds");
     if (sConfigMgr->isDryRun())
     {
         LOG_INFO("server.loading", "AzerothCore dry run completed, terminating.");
         exit(0);
     }
 }
References CharacterDatabase, DisableMgr::CheckQuestDisables(), CharacterDatabaseCleaner::CleanDatabase(), Channel::CleanOldChannelsInDB(), CONFIG_AUTOBROADCAST_INTERVAL, CONFIG_DB_PING_INTERVAL, CONFIG_EXPANSION, CONFIG_GAME_TYPE, CONFIG_LOGDB_CLEARINTERVAL, CONFIG_PRELOAD_ALL_NON_INSTANCED_MAP_GRIDS, CONFIG_REALM_ZONE, CONFIG_UPTIME_UPDATE, MMAP::MMapFactory::createOrGetMMapMgr(), VMAP::VMapFactory::createOrGetVMapMgr(), Player::DeleteOldCharacters(), DetectDBCLang(), dtAllocSetCustom(), dtCustomAlloc(), dtCustomFree(), MapMgr::ExistMapAndVMap(), GetDefaultDbcLocale(), GitRevision::GetFullVersion(), Map::GetId(), getIntConfig(), GetLiquidFlags(), VMAP::VMapMgr2::GetLiquidFlagsPtr, getMSTime(), GetMSTimeDiffToNow(), Realm::Id, IN_MILLISECONDS, InitCalendarOldEventsDeletionTime(), InitDailyQuestResetTime(), InitGuildResetTime(), AIRegistry::Initialize(), OpcodeTable::Initialize(), MMAP::MMapMgr::InitializeThreadUnsafe(), VMAP::VMapMgr2::InitializeThreadUnsafe(), InitMonthlyQuestResetTime(), InitRandomBGResetTime(), InitWeeklyQuestResetTime(), MapEntry::Instanceable(), IsFFAPvPRealm(), DisableMgr::IsVMAPDisabledFor(), VMAP::VMapMgr2::IsVMAPDisabledForPtr, Map::LoadAllCells(), LoadAutobroadcasts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), Acore::ChatCommands::LoadCommandMap(), LoadConfigSettings(), LoadDBAllowedSecurityLevel(), LoadDBCStores(), DisableMgr::LoadDisables(), AddonMgr::LoadFromDB(), LoadGameObjectModelList(), LoadLootTables(), LoadRandomEnchantmentsTable(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), LoadSkillPerfectItemTable(), WeatherMgr::LoadWeatherData(), LoadWorldStates(), LOG_INFO, LoginDatabase, m_dataPath, m_gameTime, m_int_configs, m_startTime, m_timers, mail_expire_check_timer, MapEntry::MapID, METRIC_EVENT, MINUTE, opcodeTable, realm, RealmHandle::Realm, REALM_TYPE_PVP, sAchievementMgr, sArenaTeamMgr, sAuctionMgr, sBattlefieldMgr, sBattlegroundMgr, sCalendarMgr, sConditionMgr, sConfigMgr, sCreatureTextMgr, IntervalTimer::SetCurrent(), IntervalTimer::SetInterval(), sFormationMgr, sGameEventMgr, sGraveyard, sGroupMgr, sGuildMgr, sInstanceSaveMgr, sIPLocation, sLFGMgr, sLootItemStorage, sMapMgr, sMapStore, sObjectMgr, sOutdoorPvPMgr, sPetitionMgr, sPoolMgr, sScriptMgr, sSmartScriptMgr, sSmartWaypointMgr, sSpellMgr, sTicketMgr, sTransportMgr, sWardenCheckMgr, sWaypointMgr, sWorld, to_string(), WUPDATE_5_SECS, WUPDATE_AUCTIONS, WUPDATE_AUTOBROADCAST, WUPDATE_CLEANDB, WUPDATE_CORPSES, WUPDATE_EVENTS, WUPDATE_PINGDB, WUPDATE_UPTIME, WUPDATE_WEATHERS, and WUPDATE_WHO_LIST.
setIntConfig()
void World::setIntConfig (WorldIntConfigs index, uint32 value) inline virtual
Set a server configuration element (see #WorldConfigs)
Implements IWorld.
Definition at line 322 of file World.h.
     {
         if (index < INT_CONFIG_VALUE_COUNT)
             m_int_configs[index] = value;
     }
References index, INT_CONFIG_VALUE_COUNT, and m_int_configs.
SetNewCharString()
void World::SetNewCharString (std::string const & str) inline virtual
Set the string for new characters (first login)
Implements IWorld.
Definition at line 232 of file World.h.
 { m_newCharString = str; }
References m_newCharString.
Referenced by LoadConfigSettings().
SetPlayerAmountLimit()
void World::SetPlayerAmountLimit (uint32 limit) inline virtual
Active session server limit.
Implements IWorld.
Definition at line 215 of file World.h.
 { m_playerLimit = limit; }
References m_playerLimit.
Referenced by LoadConfigSettings().
SetPlayerSecurityLimit()
void World::SetPlayerSecurityLimit (AccountTypes sec) virtual
Implements IWorld.
Definition at line 3117 of file World.cpp.
 {
     AccountTypes sec = _sec < SEC_CONSOLE ? _sec : SEC_PLAYER;
     bool update = sec > m_allowedSecurityLevel;
     m_allowedSecurityLevel = sec;
     if (update)
         KickAllLess(m_allowedSecurityLevel);
 }
References KickAllLess(), m_allowedSecurityLevel, sec, SEC_CONSOLE, and SEC_PLAYER.
Referenced by LoadDBAllowedSecurityLevel().
setRate()
void World::setRate (Rates rate, float value) inline virtual
Set a server rate (see Rates)
Implements IWorld.
Definition at line 291 of file World.h.
 { rate_values[rate] = value; }
References rate_values.
SetRealmName()
void World::SetRealmName (std::string name) inline virtual
Implements IWorld.
Definition at line 395 of file World.h.
 { _realmName = name; } // pussywizard
References _realmName, and name.
SetRecordDiffInterval()
void World::SetRecordDiffInterval (int32 t) inline virtual
Implements IWorld.
Definition at line 251 of file World.h.
 { if (t >= 0) m_int_configs[CONFIG_INTERVAL_LOG_UPDATE] = (uint32)t; }
References CONFIG_INTERVAL_LOG_UPDATE, and m_int_configs.
setWorldState()
void World::setWorldState (uint32 index, uint64 value) virtual
Implements IWorld.
Definition at line 3302 of file World.cpp.
 {
     WorldStatesMap::const_iterator it = m_worldstates.find(index);
     if (it != m_worldstates.end())
     {
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_WORLDSTATE);
         stmt->setUInt32(0, uint32(value));
         stmt->setUInt32(1, index);
         CharacterDatabase.Execute(stmt);
     }
     else
     {
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_WORLDSTATE);
         stmt->setUInt32(0, index);
         stmt->setUInt32(1, uint32(value));
         CharacterDatabase.Execute(stmt);
     }
     m_worldstates[index] = value;
 }
References CHAR_INS_WORLDSTATE, CHAR_UPD_WORLDSTATE, CharacterDatabase, index, m_worldstates, and PreparedStatementBase::setUInt32().
ShutdownCancel()
void World::ShutdownCancel () virtual
Cancel a planned server shutdown.
Implements IWorld.
Definition at line 2768 of file World.cpp.
 {
     // nothing cancel or too later
     if (!m_ShutdownTimer || m_stopEvent)
         return;
     ServerMessageType msgid = (m_ShutdownMask & SHUTDOWN_MASK_RESTART) ? SERVER_MSG_RESTART_CANCELLED : SERVER_MSG_SHUTDOWN_CANCELLED;
     m_ShutdownMask = 0;
     m_ShutdownTimer = 0;
     m_ExitCode = SHUTDOWN_EXIT_CODE;                       // to default value
     SendServerMessage(msgid);
     LOG_DEBUG("server.worldserver", "Server %s cancelled.", (m_ShutdownMask & SHUTDOWN_MASK_RESTART ? "restart" : "shuttingdown"));
     sScriptMgr->OnShutdownCancel();
 }
References LOG_DEBUG, m_ExitCode, m_ShutdownMask, m_ShutdownTimer, m_stopEvent, SendServerMessage(), SERVER_MSG_RESTART_CANCELLED, SERVER_MSG_SHUTDOWN_CANCELLED, SHUTDOWN_EXIT_CODE, SHUTDOWN_MASK_RESTART, and sScriptMgr.
ShutdownMsg()
void World::ShutdownMsg (bool show = false, Player * player = nullptr) virtual
Display a shutdown message to the user(s)
Display a message every 12 hours, hours, 5 minutes, minute, 5 seconds and finally seconds
Implements IWorld.
Definition at line 2744 of file World.cpp.
 {
     // not show messages for idle shutdown mode
     if (m_ShutdownMask & SHUTDOWN_MASK_IDLE)
         return;
     if (show ||
             (m_ShutdownTimer < 5 * MINUTE && (m_ShutdownTimer % 15) == 0) || // < 5 min; every 15 sec
             (m_ShutdownTimer < 15 * MINUTE && (m_ShutdownTimer % MINUTE) == 0) || // < 15 min ; every 1 min
             (m_ShutdownTimer < 30 * MINUTE && (m_ShutdownTimer % (5 * MINUTE)) == 0) || // < 30 min ; every 5 min
             (m_ShutdownTimer < 12 * HOUR && (m_ShutdownTimer % HOUR) == 0) || // < 12 h ; every 1 h
             (m_ShutdownTimer > 12 * HOUR && (m_ShutdownTimer % (12 * HOUR)) == 0)) // > 12 h ; every 12 h
     {
         std::string str = secsToTimeString(m_ShutdownTimer).append(".");
         ServerMessageType msgid = (m_ShutdownMask & SHUTDOWN_MASK_RESTART) ? SERVER_MSG_RESTART_TIME : SERVER_MSG_SHUTDOWN_TIME;
         SendServerMessage(msgid, str.c_str(), player);
         LOG_DEBUG("server.worldserver", "Server is %s in %s", (m_ShutdownMask & SHUTDOWN_MASK_RESTART ? "restart" : "shuttingdown"), str.c_str());
     }
 }
References HOUR, LOG_DEBUG, m_ShutdownMask, m_ShutdownTimer, MINUTE, secsToTimeString(), SendServerMessage(), SERVER_MSG_RESTART_TIME, SERVER_MSG_SHUTDOWN_TIME, SHUTDOWN_MASK_IDLE, and SHUTDOWN_MASK_RESTART.
Referenced by _UpdateGameTime(), and ShutdownServ().
ShutdownServ()
void World::ShutdownServ (uint32 time, uint32 options, uint8 exitcode) virtual
Shutdown the server.
If the shutdown time is 0, set m_stopEvent (except if shutdown is 'idle' with remaining sessions)
Else set the shutdown timer and warn users
Implements IWorld.
Definition at line 2716 of file World.cpp.
 {
     // ignore if server shutdown at next tick
     if (IsStopped())
         return;
     m_ShutdownMask = options;
     m_ExitCode = exitcode;
     if (time == 0)
     {
         if (!(options & SHUTDOWN_MASK_IDLE) || GetActiveAndQueuedSessionCount() == 0)
             m_stopEvent = true;                             // exist code already set
         else
             m_ShutdownTimer = 1;                            //So that the session count is re-evaluated at next world tick
     }
     else
     {
         m_ShutdownTimer = time;
         ShutdownMsg(true);
     }
     sScriptMgr->OnShutdownInitiate(ShutdownExitCode(exitcode), ShutdownMask(options));
 }
References GetActiveAndQueuedSessionCount(), IsStopped(), m_ExitCode, m_ShutdownMask, m_ShutdownTimer, m_stopEvent, SHUTDOWN_MASK_IDLE, ShutdownMsg(), and sScriptMgr.
StopNow()
static void World::StopNow (uint8 exitcode) inline static
Definition at line 284 of file World.h.
 { m_stopEvent = true; m_ExitCode = exitcode; }
References m_ExitCode, and m_stopEvent.
Referenced by CliThread(), ArenaTeamMgr::GenerateArenaTeamId(), ObjectMgr::GenerateAuctionID(), ObjectMgr::GenerateCreatureSpawnId(), ObjectMgr::GenerateEquipmentSetGuid(), ObjectMgr::GenerateGameObjectSpawnId(), GroupMgr::GenerateGroupId(), GuildMgr::GenerateGuildId(), MapMgr::GenerateInstanceId(), ObjectMgr::GenerateMailID(), ObjectGuidGeneratorBase::HandleCounterOverflow(), server_commandscript::HandleServerExitCommand(), main(), SignalHandler(), and WorldUpdateLoop().
Update()
void World::Update (uint32 diff) virtual
Update the World !
Update the different timers
Update the game time and check for shutdown time
Update Who List Cache
Handle daily quests reset time
Handle weekly quests reset time
Handle monthly quests reset time
Handle session updates when the timer has passed
Handle weather updates when the timer has passed
Clean logs table
Update objects when the timer has passed (maps, transport, creatures, ...)
Update uptime table
Erase corpses once every 20 minutes
Process Game events when necessary
Ping to keep MySQL connections alive
Implements IWorld.
Definition at line 2207 of file World.cpp.
 {
     METRIC_TIMER("world_update_time_total");
     m_updateTime = diff;
     if (m_int_configs[CONFIG_INTERVAL_LOG_UPDATE])
     {
         m_updateTimeSum += diff;
         if (m_updateTimeSum > m_int_configs[CONFIG_INTERVAL_LOG_UPDATE])
         {
             LOG_INFO("diff", "Average update time diff: %u. Players online: %u.", avgDiffTracker.getAverage(), (uint32)GetActiveSessionCount());
             m_updateTimeSum = 0;
         }
     }
     DynamicVisibilityMgr::Update(GetActiveSessionCount());
     for (int i = 0; i < WUPDATE_COUNT; ++i)
     {
         if (m_timers[i].GetCurrent() >= 0)
             m_timers[i].Update(diff);
         else
             m_timers[i].SetCurrent(0);
     }
     // pussywizard: our speed up and functionality
     if (m_timers[WUPDATE_5_SECS].Passed())
     {
         m_timers[WUPDATE_5_SECS].Reset();
         // moved here from HandleCharEnumOpcode
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_EXPIRED_BANS);
         CharacterDatabase.Execute(stmt);
     }
     _UpdateGameTime();
     if (m_timers[WUPDATE_WHO_LIST].Passed())
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update who list"));
         m_timers[WUPDATE_WHO_LIST].Reset();
         sWhoListCacheMgr->Update();
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Check quest reset times"));
         if (m_gameTime > m_NextDailyQuestReset)
         {
             ResetDailyQuests();
         }
         if (m_gameTime > m_NextWeeklyQuestReset)
         {
             ResetWeeklyQuests();
         }
         if (m_gameTime > m_NextMonthlyQuestReset)
         {
             ResetMonthlyQuests();
         }
     }
     if (m_gameTime > m_NextRandomBGReset)
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Reset random BG"));
         ResetRandomBG();
     }
     if (m_gameTime > m_NextCalendarOldEventsDeletionTime)
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Delete old calendar events"));
         CalendarDeleteOldEvents();
     }
     if (m_gameTime > m_NextGuildReset)
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Reset guild cap"));
         ResetGuildCap();
     }
     // pussywizard:
     // acquire mutex now, this is kind of waiting for listing thread to finish it's work (since it can't process next packet)
     // so we don't have to do it in every packet that modifies auctions
     AsyncAuctionListingMgr::SetAuctionListingAllowed(false);
     {
         std::lock_guard<std::mutex> guard(AsyncAuctionListingMgr::GetLock());
         // pussywizard: handle auctions when the timer has passed
         if (m_timers[WUPDATE_AUCTIONS].Passed())
         {
             METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update expired auctions"));
             m_timers[WUPDATE_AUCTIONS].Reset();
             // pussywizard: handle expired auctions, auctions expired when realm was offline are also handled here (not during loading when many required things aren't loaded yet)
             sAuctionMgr->Update();
         }
         AsyncAuctionListingMgr::Update(diff);
         if (m_gameTime > mail_expire_check_timer)
         {
             sObjectMgr->ReturnOrDeleteOldMails(true);
             mail_expire_check_timer = m_gameTime + 6 * 3600;
         }
         {
             METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update sessions"));
             UpdateSessions(diff);
         }
     }
     // end of section with mutex
     AsyncAuctionListingMgr::SetAuctionListingAllowed(true);
     if (m_timers[WUPDATE_WEATHERS].Passed())
     {
         m_timers[WUPDATE_WEATHERS].Reset();
         WeatherMgr::Update(uint32(m_timers[WUPDATE_WEATHERS].GetInterval()));
     }
     if (sWorld->getIntConfig(CONFIG_LOGDB_CLEARTIME) > 0) // if not enabled, ignore the timer
     {
         if (m_timers[WUPDATE_CLEANDB].Passed())
         {
             METRIC_TIMER("world_update_time", METRIC_TAG("type", "Clean logs table"));
             m_timers[WUPDATE_CLEANDB].Reset();
             LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_OLD_LOGS);
             stmt->setUInt32(0, sWorld->getIntConfig(CONFIG_LOGDB_CLEARTIME));
             stmt->setUInt32(1, uint32(time(0)));
             LoginDatabase.Execute(stmt);
         }
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update LFG 0"));
         sLFGMgr->Update(diff, 0); // pussywizard: remove obsolete stuff before finding compatibility during map update
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update maps"));
         sMapMgr->Update(diff);
     }
     if (sWorld->getBoolConfig(CONFIG_AUTOBROADCAST))
     {
         if (m_timers[WUPDATE_AUTOBROADCAST].Passed())
         {
             METRIC_TIMER("world_update_time", METRIC_TAG("type", "Send autobroadcast"));
             m_timers[WUPDATE_AUTOBROADCAST].Reset();
             SendAutoBroadcast();
         }
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update battlegrounds"));
         sBattlegroundMgr->Update(diff);
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update outdoor pvp"));
         sOutdoorPvPMgr->Update(diff);
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update battlefields"));
         sBattlefieldMgr->Update(diff);
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update LFG 2"));
         sLFGMgr->Update(diff, 2); // pussywizard: handle created proposals
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Process query callbacks"));
         // execute callbacks from sql queries that were queued recently
         ProcessQueryCallbacks();
     }
     if (m_timers[WUPDATE_UPTIME].Passed())
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update uptime"));
         uint32 tmpDiff = uint32(m_gameTime - m_startTime);
         uint32 maxOnlinePlayers = GetMaxPlayerCount();
         m_timers[WUPDATE_UPTIME].Reset();
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_UPTIME_PLAYERS);
         stmt->setUInt32(0, tmpDiff);
         stmt->setUInt16(1, uint16(maxOnlinePlayers));
         stmt->setUInt32(2, realm.Id.Realm);
         stmt->setUInt32(3, uint32(m_startTime));
         LoginDatabase.Execute(stmt);
     }
     if (m_timers[WUPDATE_CORPSES].Passed())
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Remove old corpses"));
         m_timers[WUPDATE_CORPSES].Reset();
         sMapMgr->DoForAllMaps([](Map* map)
         {
             map->RemoveOldCorpses();
         });
     }
     if (m_timers[WUPDATE_EVENTS].Passed())
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update game events"));
         m_timers[WUPDATE_EVENTS].Reset();                   // to give time for Update() to be processed
         uint32 nextGameEvent = sGameEventMgr->Update();
         m_timers[WUPDATE_EVENTS].SetInterval(nextGameEvent);
         m_timers[WUPDATE_EVENTS].Reset();
     }
     if (m_timers[WUPDATE_PINGDB].Passed())
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Ping MySQL"));
         m_timers[WUPDATE_PINGDB].Reset();
         LOG_DEBUG("sql.driver", "Ping MySQL to keep connection alive");
         CharacterDatabase.KeepAlive();
         LoginDatabase.KeepAlive();
         WorldDatabase.KeepAlive();
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update instance reset times"));
         // update the instance reset times
         sInstanceSaveMgr->Update();
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Process cli commands"));
         // And last, but not least handle the issued cli commands
         ProcessCliCommands();
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update world scripts"));
         sScriptMgr->OnWorldUpdate(diff);
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update saving system"));
         SavingSystemMgr::Update(diff);
     }
     {
         METRIC_TIMER("world_update_time", METRIC_TAG("type", "Update metrics"));
         // Stats logger update
         sMetric->Update();
         METRIC_VALUE("update_time_diff", diff);
     }
 }
References _UpdateGameTime(), avgDiffTracker, CalendarDeleteOldEvents(), CHAR_DEL_EXPIRED_BANS, CharacterDatabase, CONFIG_AUTOBROADCAST, CONFIG_INTERVAL_LOG_UPDATE, CONFIG_LOGDB_CLEARTIME, diff(), GetActiveSessionCount(), AvgDiffTracker::getAverage(), AsyncAuctionListingMgr::GetLock(), GetMaxPlayerCount(), Realm::Id, LOG_DEBUG, LOG_INFO, LOGIN_DEL_OLD_LOGS, LOGIN_UPD_UPTIME_PLAYERS, LoginDatabase, m_gameTime, m_int_configs, m_NextCalendarOldEventsDeletionTime, m_NextDailyQuestReset, m_NextGuildReset, m_NextMonthlyQuestReset, m_NextRandomBGReset, m_NextWeeklyQuestReset, m_startTime, m_timers, m_updateTime, m_updateTimeSum, mail_expire_check_timer, METRIC_TAG, METRIC_TIMER, METRIC_VALUE, ProcessCliCommands(), ProcessQueryCallbacks(), realm, RealmHandle::Realm, Map::RemoveOldCorpses(), IntervalTimer::Reset(), ResetDailyQuests(), ResetGuildCap(), ResetMonthlyQuests(), ResetRandomBG(), ResetWeeklyQuests(), sAuctionMgr, sBattlefieldMgr, sBattlegroundMgr, SendAutoBroadcast(), AsyncAuctionListingMgr::SetAuctionListingAllowed(), IntervalTimer::SetCurrent(), IntervalTimer::SetInterval(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), sGameEventMgr, sInstanceSaveMgr, sLFGMgr, sMapMgr, sMetric, sObjectMgr, sOutdoorPvPMgr, sScriptMgr, sWhoListCacheMgr, sWorld, IntervalTimer::Update(), AsyncAuctionListingMgr::Update(), SavingSystemMgr::Update(), WeatherMgr::Update(), DynamicVisibilityMgr::Update(), UpdateSessions(), WorldDatabase, WUPDATE_5_SECS, WUPDATE_AUCTIONS, WUPDATE_AUTOBROADCAST, WUPDATE_CLEANDB, WUPDATE_CORPSES, WUPDATE_COUNT, WUPDATE_EVENTS, WUPDATE_PINGDB, WUPDATE_UPTIME, WUPDATE_WEATHERS, and WUPDATE_WHO_LIST.
UpdateAreaDependentAuras()
void World::UpdateAreaDependentAuras () virtual
Implements IWorld.
Definition at line 3264 of file World.cpp.
 {
     SessionMap::const_iterator itr;
     for (itr = m_sessions.begin(); itr != m_sessions.end(); ++itr)
         if (itr->second && itr->second->GetPlayer() && itr->second->GetPlayer()->IsInWorld())
         {
             itr->second->GetPlayer()->UpdateAreaDependentAuras(itr->second->GetPlayer()->GetAreaId());
             itr->second->GetPlayer()->UpdateZoneDependentAuras(itr->second->GetPlayer()->GetZoneId());
         }
 }
References m_sessions.
UpdateGlobalNameData()
void World::UpdateGlobalNameData (ObjectGuid::LowType guidLow, std::string const & oldName, std::string const & newName) virtual
Implements IWorld.
Definition at line 3480 of file World.cpp.
 {
     _globalPlayerNameStore.erase(oldName);
     _globalPlayerNameStore[newName] = guidLow;
 }
References _globalPlayerNameStore.
UpdateGlobalPlayerArenaTeam()
void World::UpdateGlobalPlayerArenaTeam (ObjectGuid::LowType guid, uint8 slot, uint32 arenaTeamId) virtual
Implements IWorld.
Definition at line 3471 of file World.cpp.
 {
     GlobalPlayerDataMap::iterator itr = _globalPlayerDataStore.find(guid);
     if (itr == _globalPlayerDataStore.end())
         return;
     itr->second.arenaTeamId[slot] = arenaTeamId;
 }
References _globalPlayerDataStore.
UpdateGlobalPlayerData()
void World::UpdateGlobalPlayerData (ObjectGuid::LowType guid, uint8 mask, std::string const & name, uint8 level = 0, uint8 gender = 0, uint8 race = 0, uint8 playerClass = 0) virtual
Implements IWorld.
Definition at line 3414 of file World.cpp.
 {
     GlobalPlayerDataMap::iterator itr = _globalPlayerDataStore.find(guid);
     if (itr == _globalPlayerDataStore.end())
         return;
     if (mask & PLAYER_UPDATE_DATA_LEVEL)
         itr->second.level = level;
     if (mask & PLAYER_UPDATE_DATA_RACE)
         itr->second.race = race;
     if (mask & PLAYER_UPDATE_DATA_CLASS)
         itr->second.playerClass = playerClass;
     if (mask & PLAYER_UPDATE_DATA_GENDER)
         itr->second.gender = gender;
     if (mask & PLAYER_UPDATE_DATA_NAME)
         itr->second.name = name;
     WorldPacket data(SMSG_INVALIDATE_PLAYER, 8);
     data << guid;
     SendGlobalMessage(&data);
 }
References _globalPlayerDataStore, name, PLAYER_UPDATE_DATA_CLASS, PLAYER_UPDATE_DATA_GENDER, PLAYER_UPDATE_DATA_LEVEL, PLAYER_UPDATE_DATA_NAME, PLAYER_UPDATE_DATA_RACE, SendGlobalMessage(), and SMSG_INVALIDATE_PLAYER.
UpdateGlobalPlayerGroup()
void World::UpdateGlobalPlayerGroup (ObjectGuid::LowType guid, uint32 groupId) virtual
Implements IWorld.
Definition at line 3462 of file World.cpp.
 {
     GlobalPlayerDataMap::iterator itr = _globalPlayerDataStore.find(guid);
     if (itr == _globalPlayerDataStore.end())
         return;
     itr->second.groupId = groupId;
 }
References _globalPlayerDataStore.
UpdateGlobalPlayerGuild()
void World::UpdateGlobalPlayerGuild (ObjectGuid::LowType guid, uint32 guildId) virtual
Implements IWorld.
Definition at line 3454 of file World.cpp.
 {
     GlobalPlayerDataMap::iterator itr = _globalPlayerDataStore.find(guid);
     if (itr == _globalPlayerDataStore.end())
         return;
     itr->second.guildId = guildId;
 }
References _globalPlayerDataStore.
UpdateGlobalPlayerMails()
void World::UpdateGlobalPlayerMails (ObjectGuid::LowType guid, int16 count, bool add = true) virtual
Implements IWorld.
Definition at line 3436 of file World.cpp.
 {
     GlobalPlayerDataMap::iterator itr = _globalPlayerDataStore.find(guid);
     if (itr == _globalPlayerDataStore.end())
         return;
     if (!add)
     {
         itr->second.mailCount = count;
         return;
     }
     int16 icount = (int16)itr->second.mailCount;
     if (count < 0 && abs(count) > icount)
         count = -icount;
     itr->second.mailCount = uint16(icount + count); // addition or subtraction
 }
References _globalPlayerDataStore, abs(), count(), and if().
UpdateMaxSessionCounters()
void World::UpdateMaxSessionCounters () virtual
Get the number of current active sessions.
Implements IWorld.
Definition at line 3202 of file World.cpp.
 {
     m_maxActiveSessionCount = std::max(m_maxActiveSessionCount, uint32(m_sessions.size() - m_QueuedPlayer.size()));
     m_maxQueuedSessionCount = std::max(m_maxQueuedSessionCount, uint32(m_QueuedPlayer.size()));
 }
References m_maxActiveSessionCount, m_maxQueuedSessionCount, m_QueuedPlayer, m_sessions, and max.
Referenced by AddSession_().
UpdateRealmCharCount()
void World::UpdateRealmCharCount (uint32 accid) virtual
Implements IWorld.
Definition at line 2957 of file World.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHARACTER_COUNT);
     stmt->setUInt32(0, accountId);
     _queryProcessor.AddCallback(CharacterDatabase.AsyncQuery(stmt).WithPreparedCallback(std::bind(&World::_UpdateRealmCharCount, this, std::placeholders::_1)));
 }
References _queryProcessor, _UpdateRealmCharCount(), AsyncCallbackProcessor< T >::AddCallback(), CHAR_SEL_CHARACTER_COUNT, CharacterDatabase, and PreparedStatementBase::setUInt32().
UpdateSessions()
void World::UpdateSessions (uint32 diff) virtual
Add new sessions
Then send an update signal to remaining ones
and remove not active sessions from the list
Implements IWorld.
Definition at line 2800 of file World.cpp.
 {
     {
         METRIC_DETAILED_NO_THRESHOLD_TIMER("world_update_time",
             METRIC_TAG("type", "Add sessions"),
             METRIC_TAG("parent_type", "Update sessions"));
         WorldSession* sess = nullptr;
         while (addSessQueue.next(sess))
         {
             AddSession_(sess);
         }
     }
     for (SessionMap::iterator itr = m_sessions.begin(), next; itr != m_sessions.end(); itr = next)
     {
         next = itr;
         ++next;
         WorldSession* pSession = itr->second;
         WorldSessionFilter updater(pSession);
         // pussywizard:
         if (pSession->HandleSocketClosed())
         {
             if (!RemoveQueuedPlayer(pSession) && getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
                 m_disconnects[pSession->GetAccountId()] = time(nullptr);
             m_sessions.erase(itr);
             // there should be no offline session if current one is logged onto a character
             SessionMap::iterator iter;
             if ((iter = m_offlineSessions.find(pSession->GetAccountId())) != m_offlineSessions.end())
             {
                 WorldSession* tmp = iter->second;
                 m_offlineSessions.erase(iter);
                 tmp->SetShouldSetOfflineInDB(false);
                 delete tmp;
             }
             pSession->SetOfflineTime(time(nullptr));
             m_offlineSessions[pSession->GetAccountId()] = pSession;
             continue;
         }
         [[maybe_unused]] uint32 currentSessionId = itr->first;
         METRIC_DETAILED_TIMER("world_update_sessions_time", METRIC_TAG("account_id", std::to_string(currentSessionId)));
         if (!pSession->Update(diff, updater))
         {
             if (!RemoveQueuedPlayer(pSession) && getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
                 m_disconnects[pSession->GetAccountId()] = time(nullptr);
             m_sessions.erase(itr);
             if (m_offlineSessions.find(pSession->GetAccountId()) != m_offlineSessions.end()) // pussywizard: don't set offline in db because offline session for that acc is present (character is in world)
                 pSession->SetShouldSetOfflineInDB(false);
             delete pSession;
         }
     }
     // pussywizard:
     if (m_offlineSessions.empty())
         return;
     uint32 currTime = time(nullptr);
     for (SessionMap::iterator itr = m_offlineSessions.begin(), next; itr != m_offlineSessions.end(); itr = next)
     {
         next = itr;
         ++next;
         WorldSession* pSession = itr->second;
         if (!pSession->GetPlayer() || pSession->GetOfflineTime() + 60 < currTime || pSession->IsKicked())
         {
             m_offlineSessions.erase(itr);
             if (m_sessions.find(pSession->GetAccountId()) != m_sessions.end())
                 pSession->SetShouldSetOfflineInDB(false); // pussywizard: don't set offline in db because new session for that acc is already created
             delete pSession;
         }
     }
 }
References AddSession_(), addSessQueue, CONFIG_INTERVAL_DISCONNECT_TOLERANCE, diff(), WorldSession::GetAccountId(), getIntConfig(), WorldSession::GetOfflineTime(), WorldSession::GetPlayer(), WorldSession::HandleSocketClosed(), WorldSession::IsKicked(), m_disconnects, m_offlineSessions, m_sessions, METRIC_DETAILED_NO_THRESHOLD_TIMER, METRIC_DETAILED_TIMER, METRIC_TAG, next(), LockedQueue< T, StorageType >::next(), RemoveQueuedPlayer(), WorldSession::SetOfflineTime(), WorldSession::SetShouldSetOfflineInDB(), to_string(), and WorldSession::Update().
Referenced by Update().
Member Data Documentation
_globalPlayerDataStore
GlobalPlayerDataMap World::_globalPlayerDataStore private
Definition at line 464 of file World.h.
Referenced by AddGlobalPlayerData(), DeleteGlobalPlayerData(), GetGlobalPlayerData(), LoadGlobalPlayerDataStore(), UpdateGlobalPlayerArenaTeam(), UpdateGlobalPlayerData(), UpdateGlobalPlayerGroup(), UpdateGlobalPlayerGuild(), and UpdateGlobalPlayerMails().
_globalPlayerNameStore
GlobalPlayerNameMap World::_globalPlayerNameStore private
Definition at line 465 of file World.h.
Referenced by AddGlobalPlayerData(), DeleteGlobalPlayerData(), GetGlobalPlayerGUID(), and UpdateGlobalNameData().
_queryProcessor
QueryCallbackProcessor World::_queryProcessor private
Definition at line 500 of file World.h.
Referenced by ProcessQueryCallbacks(), and UpdateRealmCharCount().
_realmName
std::string World::_realmName private
Definition at line 467 of file World.h.
Referenced by GetRealmName(), and SetRealmName().
addSessQueue
LockedQueue<WorldSession*> World::addSessQueue private
Definition at line 485 of file World.h.
Referenced by AddSession(), and UpdateSessions().
cliCmdQueue
LockedQueue<CliCommandHolder*> World::cliCmdQueue private
Definition at line 470 of file World.h.
Referenced by ProcessCliCommands(), QueueCliCommand(), and ~World().
m_allowedSecurityLevel
AccountTypes World::m_allowedSecurityLevel private
Definition at line 451 of file World.h.
Referenced by GetPlayerSecurityLimit(), SetPlayerSecurityLimit(), and World().
m_allowMovement
bool World::m_allowMovement private
Definition at line 455 of file World.h.
Referenced by getAllowMovement(), SetAllowMovement(), and World().
m_AuthDBRevision
std::string World::m_AuthDBRevision private
Definition at line 491 of file World.h.
Referenced by GetAuthDBRevision(), and LoadDBRevision().
m_Autobroadcasts
AutobroadcastsMap World::m_Autobroadcasts private
Definition at line 494 of file World.h.
Referenced by LoadAutobroadcasts(), and SendAutoBroadcast().
m_AutobroadcastsWeights
AutobroadcastsWeightMap World::m_AutobroadcastsWeights private
Definition at line 497 of file World.h.
Referenced by LoadAutobroadcasts(), and SendAutoBroadcast().
m_availableDbcLocaleMask
uint32 World::m_availableDbcLocaleMask private
Definition at line 453 of file World.h.
Referenced by DetectDBCLang(), and GetAvailableDbcLocale().
m_bool_configs
bool World::m_bool_configs[BOOL_CONFIG_VALUE_COUNT] private
Definition at line 446 of file World.h.
Referenced by getBoolConfig(), LoadConfigSettings(), setBoolConfig(), and World().
m_CharacterDBRevision
std::string World::m_CharacterDBRevision private
Definition at line 490 of file World.h.
Referenced by GetCharacterDBRevision(), and LoadDBRevision().
m_CleaningFlags
uint32 World::m_CleaningFlags private
Definition at line 422 of file World.h.
Referenced by GetCleaningFlags(), SetCleaningFlags(), and World().
m_dataPath
std::string World::m_dataPath private
Definition at line 456 of file World.h.
Referenced by GetDataPath(), LoadConfigSettings(), and SetInitialWorldSettings().
m_DBVersion
std::string World::m_DBVersion private
Definition at line 488 of file World.h.
Referenced by GetDBVersion(), and LoadDBVersion().
m_defaultDbcLocale
LocaleConstant World::m_defaultDbcLocale private
Definition at line 452 of file World.h.
Referenced by DetectDBCLang(), GetAvailableDbcLocale(), GetDefaultDbcLocale(), and World().
m_disconnects
DisconnectMap World::m_disconnects private
Definition at line 436 of file World.h.
Referenced by AddSession_(), HasRecentlyDisconnected(), and UpdateSessions().
m_ExitCode
uint8 World::m_ExitCode = SHUTDOWN_EXIT_CODE static private
Definition at line 418 of file World.h.
Referenced by GetExitCode(), ShutdownCancel(), ShutdownServ(), and StopNow().
m_float_configs
float World::m_float_configs[FLOAT_CONFIG_VALUE_COUNT] private
Definition at line 447 of file World.h.
Referenced by getFloatConfig(), LoadConfigSettings(), setFloatConfig(), and World().
m_gameMSTime
uint32 World::m_gameMSTime = 0 static private
Definition at line 431 of file World.h.
Referenced by _UpdateGameTime(), GetGameTimeMS(), and World().
m_gameTime
time_t World::m_gameTime private
Definition at line 427 of file World.h.
Referenced by _UpdateGameTime(), GetGameTime(), GetUptime(), SetInitialWorldSettings(), Update(), and World().
m_int_configs
uint32 World::m_int_configs[INT_CONFIG_VALUE_COUNT] private
Definition at line 445 of file World.h.
Referenced by getIntConfig(), LoadConfigSettings(), LoadDBVersion(), SetInitialWorldSettings(), setIntConfig(), SetRecordDiffInterval(), Update(), and World().
m_isClosed
bool World::m_isClosed private
Definition at line 424 of file World.h.
Referenced by IsClosed(), SetClosed(), and World().
m_maxActiveSessionCount
uint32 World::m_maxActiveSessionCount private
Definition at line 437 of file World.h.
Referenced by GetMaxActiveSessionCount(), UpdateMaxSessionCounters(), and World().
m_MaxPlayerCount
uint32 World::m_MaxPlayerCount private
Definition at line 440 of file World.h.
Referenced by GetMaxPlayerCount(), IncreasePlayerCount(), and World().
m_maxQueuedSessionCount
uint32 World::m_maxQueuedSessionCount private
Definition at line 438 of file World.h.
Referenced by GetMaxQueuedSessionCount(), UpdateMaxSessionCounters(), and World().
m_MaxVisibleDistanceInBGArenas
float World::m_MaxVisibleDistanceInBGArenas = DEFAULT_VISIBILITY_BGARENAS static private
Definition at line 461 of file World.h.
Referenced by GetMaxVisibleDistanceInBGArenas(), and LoadConfigSettings().
m_MaxVisibleDistanceInInstances
float World::m_MaxVisibleDistanceInInstances = DEFAULT_VISIBILITY_INSTANCE static private
Definition at line 460 of file World.h.
Referenced by GetMaxVisibleDistanceInInstances(), and LoadConfigSettings().
m_MaxVisibleDistanceOnContinents
float World::m_MaxVisibleDistanceOnContinents = DEFAULT_VISIBILITY_DISTANCE static private
Definition at line 459 of file World.h.
Referenced by GetMaxVisibleDistanceOnContinents(), and LoadConfigSettings().
m_newCharString
std::string World::m_newCharString private
Definition at line 442 of file World.h.
Referenced by GetNewCharString(), and SetNewCharString().
m_NextCalendarOldEventsDeletionTime
time_t World::m_NextCalendarOldEventsDeletionTime private
Definition at line 477 of file World.h.
Referenced by CalendarDeleteOldEvents(), InitCalendarOldEventsDeletionTime(), Update(), and World().
m_NextDailyQuestReset
time_t World::m_NextDailyQuestReset private
Definition at line 473 of file World.h.
Referenced by GetNextDailyQuestsResetTime(), InitDailyQuestResetTime(), ResetDailyQuests(), Update(), and World().
m_NextGuildReset
time_t World::m_NextGuildReset private
Definition at line 478 of file World.h.
Referenced by InitGuildResetTime(), ResetGuildCap(), Update(), and World().
m_NextMonthlyQuestReset
time_t World::m_NextMonthlyQuestReset private
Definition at line 475 of file World.h.
Referenced by InitMonthlyQuestResetTime(), ResetMonthlyQuests(), Update(), and World().
m_NextRandomBGReset
time_t World::m_NextRandomBGReset private
Definition at line 476 of file World.h.
Referenced by GetNextRandomBGResetTime(), InitRandomBGResetTime(), ResetRandomBG(), Update(), and World().
m_NextWeeklyQuestReset
time_t World::m_NextWeeklyQuestReset private
Definition at line 474 of file World.h.
Referenced by GetNextWeeklyQuestsResetTime(), InitWeeklyQuestResetTime(), ResetWeeklyQuests(), Update(), and World().
m_offlineSessions
SessionMap World::m_offlineSessions private
Definition at line 434 of file World.h.
Referenced by AddSession_(), FindOfflineSession(), FindOfflineSessionForCharacterGUID(), KickAll(), UpdateSessions(), and ~World().
m_PlayerCount
uint32 World::m_PlayerCount private
Definition at line 439 of file World.h.
Referenced by DecreasePlayerCount(), GetPlayerCount(), IncreasePlayerCount(), and World().
m_playerLimit
uint32 World::m_playerLimit private
Definition at line 450 of file World.h.
Referenced by GetPlayerAmountLimit(), SetPlayerAmountLimit(), and World().
m_QueuedPlayer
Queue World::m_QueuedPlayer private
Definition at line 481 of file World.h.
Referenced by AddQueuedPlayer(), GetActiveSessionCount(), GetQueuedSessionCount(), GetQueuePos(), KickAll(), RemoveQueuedPlayer(), and UpdateMaxSessionCounters().
m_sessions
SessionMap World::m_sessions private
Definition at line 433 of file World.h.
Referenced by AddSession_(), FindPlayerInZone(), FindSession(), GetActiveAndQueuedSessionCount(), GetActiveSessionCount(), GetAllSessions(), KickAll(), KickAllLess(), KickSession(), ResetDailyQuests(), ResetEventSeasonalQuests(), ResetMonthlyQuests(), ResetRandomBG(), ResetWeeklyQuests(), SendGlobalGMMessage(), SendGlobalMessage(), SendGMText(), SendWorldText(), SendZoneMessage(), UpdateAreaDependentAuras(), UpdateMaxSessionCounters(), UpdateSessions(), and ~World().
m_ShutdownMask
uint32 World::m_ShutdownMask private
Definition at line 420 of file World.h.
Referenced by _UpdateGameTime(), ShutdownCancel(), ShutdownMsg(), ShutdownServ(), and World().
m_ShutdownTimer
uint32 World::m_ShutdownTimer private
Definition at line 419 of file World.h.
Referenced by _UpdateGameTime(), GetShutDownTimeLeft(), IsShuttingDown(), ShutdownCancel(), ShutdownMsg(), ShutdownServ(), and World().
m_startTime
time_t World::m_startTime private
Definition at line 426 of file World.h.
Referenced by GetStartTime(), GetUptime(), SetInitialWorldSettings(), Update(), and World().
m_stopEvent
std::atomic_long World::m_stopEvent = false static private
Definition at line 417 of file World.h.
Referenced by _UpdateGameTime(), IsStopped(), ShutdownCancel(), ShutdownServ(), and StopNow().
m_timers
IntervalTimer World::m_timers[WUPDATE_COUNT] private
Definition at line 428 of file World.h.
Referenced by ForceGameEventUpdate(), GetNextWhoListUpdateDelaySecs(), LoadConfigSettings(), RemoveOldCorpses(), SetInitialWorldSettings(), and Update().
m_updateTime
uint32 World::m_updateTime private
Definition at line 430 of file World.h.
Referenced by GetUpdateTime(), Update(), and World().
m_updateTimeSum
uint32 World::m_updateTimeSum private
Definition at line 430 of file World.h.
Referenced by Update(), and World().
m_WorldDBRevision
std::string World::m_WorldDBRevision private
Definition at line 489 of file World.h.
Referenced by GetWorldDBRevision(), and LoadDBRevision().
m_worldLoopCounter
uint32 World::m_worldLoopCounter = 0 static
Definition at line 172 of file World.h.
Referenced by FreezeDetector::Handler(), and WorldUpdateLoop().
m_worldstates
WorldStatesMap World::m_worldstates private
Definition at line 449 of file World.h.
Referenced by getWorldState(), LoadWorldStates(), and setWorldState().
mail_expire_check_timer
time_t World::mail_expire_check_timer private
Definition at line 429 of file World.h.
Referenced by SetInitialWorldSettings(), Update(), and World().
rate_values
float World::rate_values[MAX_RATES] private
Definition at line 444 of file World.h.
Referenced by getRate(), LoadConfigSettings(), setRate(), and World().
The documentation for this class was generated from the following files:
src/server/game/World/World.h
src/server/game/World/World.cpp