Azerotcore-wotlk: src/tools/vmap4_extractor/vmapexport.h File Reference
vmapexport.h File Reference
#include "loadlib/loadlib.h"
#include <string>
#include <unordered_map>
Namespaces
VMAP
Enumerations
enum ModelFlags { MOD_M2 = 1 , MOD_WORLDSPAWN = 1 << 1 , MOD_HAS_BOUND = 1 << 2 }
Functions
uint32 GenerateUniqueObjectId (uint32 clientId, uint16 clientDoodadId)
bool FileExists (const char *file)
void strToLower (char *str)
bool ExtractSingleWmo (std::string &fname)
bool ExtractSingleModel (std::string &fname)
void ExtractGameobjectModels ()
Variables
const char * szWorkDirWmo
std::unordered_map< std::string, WMODoodadData > WmoDoodads
Enumeration Type Documentation
ModelFlags
enum ModelFlags
Enumerator
MOD_M2
MOD_WORLDSPAWN
MOD_HAS_BOUND
Definition at line 31 of file vmapexport.h.
 {
     MOD_M2 = 1,
     MOD_WORLDSPAWN = 1 << 1,
     MOD_HAS_BOUND = 1 << 2
 };
Function Documentation
ExtractGameobjectModels()
void ExtractGameobjectModels ()
Definition at line 104 of file MeshExtractor.cpp.
 {
     Constants::ToWoWCoords = true;
     printf("Extracting GameObject models\n");
     std::string baseBuildingsPath = "Buildings/";
     std::string baseVmapsPath = "vmaps/";
     Utils::CreateDir(baseVmapsPath);
     Utils::CreateDir(baseBuildingsPath);
     FILE* modelList = fopen((baseVmapsPath + "GameObjectModels.list").c_str(), "wb");
     if (!modelList)
     {
         printf("Could not create file vmaps/GameObjectModels.list, please make sure that you have the write permissions in the folder\n");
         return;
     }
     DBC* dbc = MPQHandler->GetDBC("GameObjectDisplayInfo");
     for (std::vector<Record*>::iterator itr = dbc->Records.begin(); itr != dbc->Records.end(); ++itr)
     {
         std::string path = (*itr)->GetString(1);
         std::string fileName = Utils::GetPlainName(path.c_str());
         std::string extension = Utils::GetExtension(fileName);
         // Convert the extension to lowercase
         std::transform(extension.begin(), extension.end(), extension.begin(), ::tolower);
         if (extension == "mdx" || extension == "m2")
         {
             fileName = Utils::FixModelPath(fileName);
             Model model(path);
             if (model.IsBad)
                 continue;
             FILE* output = fopen((baseBuildingsPath + fileName).c_str(), "wb");
             if (!output)
             {
                 printf("Could not create file %s, please check that you have write permissions\n", (baseBuildingsPath + fileName).c_str());
                 continue;
             }
             // Placeholder for 0 values
             int Nop[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
             fwrite(Constants::VMAPMagic, 8, 1, output);
             uint32 numVerts = model.Header.CountBoundingVertices;
             fwrite(&numVerts, sizeof(uint32), 1, output);
             uint32 numGroups = 1;
             fwrite(&numGroups, sizeof(uint32), 1, output);
             fwrite(Nop, 4 * 3, 1, output);  // rootwmoid, flags, groupid
             fwrite(Nop, sizeof(float), 3 * 2, output);//bbox, only needed for WMO currently
             fwrite(Nop, 4, 1, output);// liquidflags
             fwrite("GRP ", 4, 1, output);
             uint32 branches = 1;
             uint32 wsize = sizeof(branches) + sizeof(uint32) * branches;
             fwrite(&wsize, sizeof(uint32), 1, output);
             fwrite(&branches, sizeof(branches), 1, output);
             uint32 numTris = model.Header.CountBoundingTriangles;
             fwrite(&numTris, sizeof(uint32), 1, output);
             fwrite("INDX", 4, 1, output);
             wsize = sizeof(uint32) + sizeof(unsigned short) * numTris;
             fwrite(&wsize, sizeof(int), 1, output);
             fwrite(&numTris, sizeof(uint32), 1, output);
             uint16* indices = new uint16[numTris];
             if (numTris > 0)
             {
                 uint32 i = 0;
                 for (std::vector<Triangle<uint16>>::iterator itr2 = model.Triangles.begin(); itr2 != model.Triangles.end(); ++itr2, ++i)
                 {
                     indices[i * 3 + 0] = itr2->V0;
                     indices[i * 3 + 1] = itr2->V1;
                     indices[i * 3 + 2] = itr2->V2;
                 }
                 fwrite(indices, sizeof(uint16), numTris, output);
             }
             fwrite("VERT", 4, 1, output);
             wsize = sizeof(int) + sizeof(float) * 3 * numVerts;
             fwrite(&wsize, sizeof(int), 1, output);
             fwrite(&numVerts, sizeof(int), 1, output);
             float* vertices = new float[numVerts * 3];
             if (numVerts > 0)
             {
                 uint32 i = 0;
                 for (std::vector<Vector3>::iterator itr2 = model.Vertices.begin(); itr2 != model.Vertices.end(); ++itr2, ++i)
                 {
                     vertices[i * 3 + 0] = itr2->x;
                     vertices[i * 3 + 1] = itr2->y;
                     vertices[i * 3 + 2] = itr2->z;
                 }
                 fwrite(vertices, sizeof(float), numVerts * 3, output);
             }
             fclose(output);
             delete[] indices;
             delete[] vertices;
             uint32 displayId = (*itr)->Values[0];
             uint32 pathLength = fileName.size();
             fwrite(&displayId, sizeof(uint32), 1, modelList);
             fwrite(&pathLength, sizeof(uint32), 1, modelList);
             fwrite(fileName.c_str(), sizeof(char), pathLength, modelList);
         }
         else if (extension == "wmo")
         {
             WorldModelRoot model(path);
             FILE* output = fopen((baseBuildingsPath + fileName).c_str(), "wb");
             if (!output)
             {
                 printf("Could not create file %s, please check that you have write permissions\n", (baseBuildingsPath + fileName).c_str());
                 continue;
             }
             fwrite(Constants::VMAPMagic, 1, 8, output);
             uint32 numVertices = 0;
             fwrite(&numVertices, sizeof(uint32), 1, output); // will be filled later
             fwrite(&model.Header.CountGroups, sizeof(uint32), 1, output);
             fwrite(&model.Header.WmoId, sizeof(uint32), 1, output);
             const char grp[] = { 'G', 'R', 'P', ' ' };
             for (std::vector<WorldModelGroup>::iterator itr2 = model.Groups.begin(); itr2 != model.Groups.end(); ++itr2)
             {
                 const WMOGroupHeader& header = itr2->Header;
                 fwrite(&header.Flags, sizeof(uint32), 1, output);
                 fwrite(&header.WmoId, sizeof(uint32), 1, output);
                 fwrite(&header.BoundingBox[0], sizeof(uint32), 1, output);
                 fwrite(&header.BoundingBox[1], sizeof(uint32), 1, output);
                 uint32 LiquidFlags = itr2->HasLiquidData ? 1 : 0;
                 fwrite(&LiquidFlags, sizeof(uint32), 1, output);
                 fwrite(grp, sizeof(char), sizeof(grp), output);
                 uint32 k = 0;
                 uint32 mobaBatch = itr2->MOBALength / 12;
                 uint32* MobaEx = new uint32[mobaBatch * 4];
                 for (uint32 i = 8; i < itr2->MOBALength; i += 12)
                     MobaEx[k++] = itr2->MOBA[i];
                 int mobaSizeGrp = mobaBatch * 4 + 4;
                 fwrite(&mobaSizeGrp, 4, 1, output);
                 fwrite(&mobaBatch, 4, 1, output);
                 fwrite(MobaEx, 4, k, output);
                 delete[] MobaEx;
                 //@TODO: Finish this.
             }
             fclose(output);
         }
     }
     fclose(modelList);
     printf("GameObject models extraction finished!");
     Constants::ToWoWCoords = false;
 }
References WMOGroupHeader::BoundingBox, ModelHeader::CountBoundingTriangles, ModelHeader::CountBoundingVertices, WorldModelHeader::CountGroups, Utils::CreateDir(), ExtractSingleModel(), ExtractSingleWmo(), Utils::FixModelPath(), fixname2(), fixnamen(), WMOGroupHeader::Flags, MPQMgr::GetDBC(), GetExtension(), Utils::GetExtension(), GetPlainName(), Utils::GetPlainName(), WorldModelRoot::Groups, Model::Header, WorldModelRoot::Header, Model::IsBad, model_list, MPQHandler, DBCFile::open(), printf(), VMAP::RAW_VMAP_MAGIC, DBC::Records, strToLower(), szWorkDirWmo, Constants::ToWoWCoords, Model::Triangles, Model::Vertices, Constants::VMAPMagic, WorldModelHeader::WmoId, and WMOGroupHeader::WmoId.
Referenced by main().
ExtractSingleModel()
bool ExtractSingleModel (std::string & fname)
Definition at line 25 of file gameobject_extract.cpp.
 {
     if (fname.length() < 4)
         return false;
     std::string extension = fname.substr(fname.length() - 4, 4);
     if (extension == ".mdx" || extension == ".MDX" || extension == ".mdl" || extension == ".MDL")
     {
         // replace .mdx -> .m2
         fname.erase(fname.length() - 2, 2);
         fname.append("2");
     }
     // >= 3.1.0 ADT MMDX section store filename.m2 filenames for corresponded .m2 file
     // nothing do
     std::string originalName = fname;
     char* name = GetPlainName((char*)fname.c_str());
     fixnamen(name, strlen(name));
     fixname2(name, strlen(name));
     std::string output(szWorkDirWmo);
     output += "/";
     output += name;
     if (FileExists(output.c_str()))
         return true;
     Model mdl(originalName);
     if (!mdl.open())
         return false;
     return mdl.ConvertToVMAPModel(output.c_str());
 }
References Model::ConvertToVMAPModel(), FileExists(), fixname2(), fixnamen(), GetPlainName(), Model::open(), and szWorkDirWmo.
Referenced by ExtractGameobjectModels(), ADTFile::init(), and WMORoot::open().
ExtractSingleWmo()
bool ExtractSingleWmo (std::string & fname)
Definition at line 105 of file vmapexport.cpp.
 {
     // Copy files from archive
     std::string originalName = fname;
     char szLocalFile[1024];
     char* plain_name = GetPlainName(&fname[0]);
     fixnamen(plain_name, strlen(plain_name));
     fixname2(plain_name, strlen(plain_name));
     sprintf(szLocalFile, "%s/%s", szWorkDirWmo, plain_name);
     if (FileExists(szLocalFile))
         return true;
     int p = 0;
     // Select root wmo files
     char const* rchr = strrchr(plain_name, '_');
     if (rchr != nullptr)
     {
         char cpy[4];
         memcpy(cpy, rchr, 4);
         for (int m : cpy)
         {
             if (isdigit(m))
                 p++;
         }
     }
     if (p == 3)
         return true;
     bool file_ok = true;
     printf("Extracting %s\n", originalName.c_str());
     WMORoot froot(originalName);
     if (!froot.open())
     {
         printf("Couldn't open RootWmo!!!\n");
         return false;
     }
     FILE* output = fopen(szLocalFile, "wb");
     if (!output)
     {
         printf("couldn't open %s for writing!\n", szLocalFile);
         return false;
     }
     froot.ConvertToVMAPRootWmo(output);
     WMODoodadData& doodads = WmoDoodads[plain_name];
     std::swap(doodads, froot.DoodadData);
     int Wmo_nVertices = 0;
     //printf("root has %d groups\n", froot->nGroups);
     if (froot.nGroups != 0)
     {
         for (uint32 i = 0; i < froot.nGroups; ++i)
         {
             char temp[1024];
             strncpy(temp, fname.c_str(), 1024);
             temp[fname.length() - 4] = 0;
             char groupFileName[1024];
             int ret = snprintf(groupFileName, 1024, "%s_%03u.wmo", temp, i);
             if (ret < 0)
             {
                 printf("Error when formatting string");
                 return false;
             }
             //printf("Trying to open groupfile %s\n",groupFileName);
             string s = groupFileName;
             WMOGroup fgroup(s);
             if (!fgroup.open())
             {
                 printf("Could not open all Group file for: %s\n", plain_name);
                 file_ok = false;
                 break;
             }
             Wmo_nVertices += fgroup.ConvertToVMAPGroupWmo(output, &froot, preciseVectorData);
             for (uint16 groupReference : fgroup.DoodadReferences)
             {
                 if (groupReference >= doodads.Spawns.size())
                     continue;
                 uint32 doodadNameIndex = doodads.Spawns[groupReference].NameIndex;
                 if (froot.ValidDoodadNames.find(doodadNameIndex) == froot.ValidDoodadNames.end())
                     continue;
                 doodads.References.insert(groupReference);
             }
         }
     }
     fseek(output, 8, SEEK_SET); // store the correct no of vertices
     fwrite(&Wmo_nVertices, sizeof(int), 1, output);
     fclose(output);
     // Delete the extracted file in the case of an error
     if (!file_ok)
         remove(szLocalFile);
     return true;
 }
References WMOGroup::ConvertToVMAPGroupWmo(), WMORoot::ConvertToVMAPRootWmo(), WMORoot::DoodadData, WMOGroup::DoodadReferences, FileExists(), fixname2(), fixnamen(), GetPlainName(), memcpy, WMORoot::nGroups, WMORoot::open(), WMOGroup::open(), preciseVectorData, printf(), WMODoodadData::References, ret, SEEK_SET, WMODoodadData::Spawns, sprintf(), swap(), szWorkDirWmo, WMORoot::ValidDoodadNames, and WmoDoodads.
Referenced by ExtractGameobjectModels(), ADTFile::init(), and WDTFile::init().
FileExists()
bool FileExists (const char * file)
Definition at line 137 of file System.cpp.
 {
     int fp = _open(FileName, OPEN_FLAGS);
     if (fp != -1)
     {
         _close(fp);
         return true;
     }
     return false;
 }
References mpq::file, and OPEN_FLAGS.
Referenced by ExtractDBCFiles(), ExtractSingleModel(), ExtractSingleWmo(), LoadCommonMPQFiles(), LoadLocaleMPQFiles(), and main().
GenerateUniqueObjectId()
uint32 GenerateUniqueObjectId (uint32 clientId, uint16 clientDoodadId)
Definition at line 79 of file vmapexport.cpp.
 {
     return uniqueObjectIds.emplace(std::make_pair(clientId, clientDoodadId), uint32(uniqueObjectIds.size() + 1)).first->second;
 }
References uniqueObjectIds.
Referenced by Doodad::Extract(), MapObject::Extract(), and Doodad::ExtractSet().
strToLower()
void strToLower (char * str)
Definition at line 96 of file vmapexport.cpp.
 {
     while (*str)
     {
         *str = tolower(*str);
         ++str;
     }
 }
Variable Documentation
szWorkDirWmo
const char* szWorkDirWmo extern
Definition at line 75 of file vmapexport.cpp.
Referenced by Doodad::Extract(), MapObject::Extract(), ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and main().
WmoDoodads
std::unordered_map<std::string, WMODoodadData> WmoDoodads extern
Definition at line 71 of file vmapexport.cpp.
Referenced by ExtractSingleWmo(), ADTFile::init(), and WDTFile::init().