Azerotcore-wotlk: ActivePoolData Class Reference
ActivePoolData Class Reference
#include <PoolMgr.h>
Public Member Functions
template<typename T >
bool IsActiveObject (uint32 db_guid_or_pool_id) const
uint32 GetActiveObjectCount (uint32 pool_id) const
template<typename T >
void ActivateObject (uint32 db_guid_or_pool_id, uint32 pool_id)
template<typename T >
void RemoveObject (uint32 db_guid_or_pool_id, uint32 pool_id)
ActivePoolObjects GetActiveQuests () const
template<>
bool IsActiveObject (uint32 db_guid) const
template<>
bool IsActiveObject (uint32 db_guid) const
template<>
bool IsActiveObject (uint32 sub_pool_id) const
template<>
bool IsActiveObject (uint32 quest_id) const
template<>
void ActivateObject (uint32 db_guid, uint32 pool_id)
template<>
void ActivateObject (uint32 db_guid, uint32 pool_id)
template<>
void ActivateObject (uint32 sub_pool_id, uint32 pool_id)
template<>
void ActivateObject (uint32 quest_id, uint32 pool_id)
template<>
void RemoveObject (uint32 db_guid, uint32 pool_id)
template<>
void RemoveObject (uint32 db_guid, uint32 pool_id)
template<>
void RemoveObject (uint32 sub_pool_id, uint32 pool_id)
template<>
void RemoveObject (uint32 quest_id, uint32 pool_id)
Private Attributes
ActivePoolObjects mSpawnedCreatures
ActivePoolObjects mSpawnedGameobjects
ActivePoolObjects mActiveQuests
ActivePoolPools mSpawnedPools
Detailed Description
Definition at line 45 of file PoolMgr.h.
Member Function Documentation
ActivateObject() [1/5]
template<> void ActivePoolData::ActivateObject (uint32 db_guid, uint32 pool_id)
Definition at line 64 of file PoolMgr.cpp.
 {
     mSpawnedCreatures.insert(db_guid);
     ++mSpawnedPools[pool_id];
 }
References mSpawnedCreatures, and mSpawnedPools.
ActivateObject() [2/5]
template<> void ActivePoolData::ActivateObject (uint32 db_guid, uint32 pool_id)
Definition at line 71 of file PoolMgr.cpp.
 {
     mSpawnedGameobjects.insert(db_guid);
     ++mSpawnedPools[pool_id];
 }
References mSpawnedGameobjects, and mSpawnedPools.
ActivateObject() [3/5]
template<typename T > void ActivePoolData::ActivateObject (uint32 db_guid_or_pool_id, uint32 pool_id)
Referenced by PoolGroup< T >::SpawnObject().
ActivateObject() [4/5]
template<> void ActivePoolData::ActivateObject (uint32 quest_id, uint32 pool_id)
Definition at line 85 of file PoolMgr.cpp.
 {
     mActiveQuests.insert(quest_id);
     ++mSpawnedPools[pool_id];
 }
References mActiveQuests, and mSpawnedPools.
ActivateObject() [5/5]
template<> void ActivePoolData::ActivateObject (uint32 sub_pool_id, uint32 pool_id)
Definition at line 78 of file PoolMgr.cpp.
 {
     mSpawnedPools[sub_pool_id] = 0;
     ++mSpawnedPools[pool_id];
 }
References mSpawnedPools.
GetActiveObjectCount()
uint32 ActivePoolData::GetActiveObjectCount (uint32 pool_id) const
Definition at line 29 of file PoolMgr.cpp.
 {
     ActivePoolPools::const_iterator itr = mSpawnedPools.find(pool_id);
     return itr != mSpawnedPools.end() ? itr->second : 0;
 }
References mSpawnedPools.
Referenced by PoolGroup< T >::SpawnObject().
GetActiveQuests()
ActivePoolObjects ActivePoolData::GetActiveQuests () const inline
Definition at line 59 of file PoolMgr.h.
 { return mActiveQuests; } // a copy of the set
References mActiveQuests.
Referenced by PoolGroup< T >::SpawnObject().
IsActiveObject() [1/5]
template<> bool ActivePoolData::IsActiveObject (uint32 db_guid) const
Definition at line 37 of file PoolMgr.cpp.
 {
     return mSpawnedCreatures.find(db_guid) != mSpawnedCreatures.end();
 }
References mSpawnedCreatures.
IsActiveObject() [2/5]
template<> bool ActivePoolData::IsActiveObject (uint32 db_guid) const
Definition at line 44 of file PoolMgr.cpp.
 {
     return mSpawnedGameobjects.find(db_guid) != mSpawnedGameobjects.end();
 }
References mSpawnedGameobjects.
IsActiveObject() [3/5]
template<typename T > bool ActivePoolData::IsActiveObject (uint32 db_guid_or_pool_id) const
Referenced by PoolGroup< T >::DespawnObject(), PoolMgr::IsSpawnedObject(), and PoolGroup< T >::SpawnObject().
IsActiveObject() [4/5]
template<> bool ActivePoolData::IsActiveObject (uint32 quest_id) const
Definition at line 58 of file PoolMgr.cpp.
 {
     return mActiveQuests.find(quest_id) != mActiveQuests.end();
 }
References mActiveQuests.
IsActiveObject() [5/5]
template<> bool ActivePoolData::IsActiveObject (uint32 sub_pool_id) const
Definition at line 51 of file PoolMgr.cpp.
 {
     return mSpawnedPools.find(sub_pool_id) != mSpawnedPools.end();
 }
References mSpawnedPools.
RemoveObject() [1/5]
template<> void ActivePoolData::RemoveObject (uint32 db_guid, uint32 pool_id)
Definition at line 92 of file PoolMgr.cpp.
 {
     mSpawnedCreatures.erase(db_guid);
     uint32& val = mSpawnedPools[pool_id];
     if (val > 0)
         --val;
 }
References mSpawnedCreatures, and mSpawnedPools.
RemoveObject() [2/5]
template<> void ActivePoolData::RemoveObject (uint32 db_guid, uint32 pool_id)
Definition at line 101 of file PoolMgr.cpp.
 {
     mSpawnedGameobjects.erase(db_guid);
     uint32& val = mSpawnedPools[pool_id];
     if (val > 0)
         --val;
 }
References mSpawnedGameobjects, and mSpawnedPools.
RemoveObject() [3/5]
template<typename T > void ActivePoolData::RemoveObject (uint32 db_guid_or_pool_id, uint32 pool_id)
Referenced by PoolGroup< T >::DespawnObject().
RemoveObject() [4/5]
template<> void ActivePoolData::RemoveObject (uint32 quest_id, uint32 pool_id)
Definition at line 119 of file PoolMgr.cpp.
 {
     mActiveQuests.erase(quest_id);
     uint32& val = mSpawnedPools[pool_id];
     if (val > 0)
         --val;
 }
References mActiveQuests, and mSpawnedPools.
RemoveObject() [5/5]
template<> void ActivePoolData::RemoveObject (uint32 sub_pool_id, uint32 pool_id)
Definition at line 110 of file PoolMgr.cpp.
 {
     mSpawnedPools.erase(sub_pool_id);
     uint32& val = mSpawnedPools[pool_id];
     if (val > 0)
         --val;
 }
References mSpawnedPools.
Member Data Documentation
mActiveQuests
ActivePoolObjects ActivePoolData::mActiveQuests private
Definition at line 63 of file PoolMgr.h.
Referenced by ActivateObject(), GetActiveQuests(), IsActiveObject(), and RemoveObject().
mSpawnedCreatures
ActivePoolObjects ActivePoolData::mSpawnedCreatures private
Definition at line 61 of file PoolMgr.h.
Referenced by ActivateObject(), IsActiveObject(), and RemoveObject().
mSpawnedGameobjects
ActivePoolObjects ActivePoolData::mSpawnedGameobjects private
Definition at line 62 of file PoolMgr.h.
Referenced by ActivateObject(), IsActiveObject(), and RemoveObject().
mSpawnedPools
ActivePoolPools ActivePoolData::mSpawnedPools private
Definition at line 64 of file PoolMgr.h.
Referenced by ActivateObject(), GetActiveObjectCount(), IsActiveObject(), and RemoveObject().
The documentation for this class was generated from the following files:
src/server/game/Pools/PoolMgr.h
src/server/game/Pools/PoolMgr.cpp