Azerotcore-wotlk: ansi_color_escape< Char > Struct Template Reference
ansi_color_escape< Char > Struct Template Reference
#include <color.h>
Public Member Functions
FMT_CONSTEXPR ansi_color_escape (detail::color_type text_color, const char *esc) FMT_NOEXCEPT
FMT_CONSTEXPR ansi_color_escape (emphasis em) FMT_NOEXCEPT
FMT_CONSTEXPR operator const Char * () const FMT_NOEXCEPT
FMT_CONSTEXPR const Char * begin () const FMT_NOEXCEPT
FMT_CONSTEXPR_CHAR_TRAITS const Char * end () const FMT_NOEXCEPT
Static Private Member Functions
static FMT_CONSTEXPR void to_esc (uint8_t c, Char *out, char delimiter) FMT_NOEXCEPT
Private Attributes
Char buffer [7u+3u *4u+1u]
Detailed Description
template<typename Char>
struct ansi_color_escape< Char >
Definition at line 374 of file color.h.
Constructor & Destructor Documentation
ansi_color_escape() [1/2]
template<typename Char > FMT_CONSTEXPR ansi_color_escape< Char >::ansi_color_escape (detail::color_type text_color, const char * esc) inline
Definition at line 375 of file color.h.
{
     // If we have a terminal color, we need to output another escape code
     // sequence.
     if (!text_color.is_rgb) {
       bool is_background = esc == string_view("\x1b[48;2;");
       uint32_t value = text_color.value.term_color;
       // Background ASCII codes are the same as the foreground ones but with
       // 10 more.
       if (is_background) value += 10u;
       size_t index = 0;
       buffer[index++] = static_cast<Char>('\x1b');
       buffer[index++] = static_cast<Char>('[');
       if (value >= 100u) {
         buffer[index++] = static_cast<Char>('1');
         value %= 100u;
       }
       buffer[index++] = static_cast<Char>('0' + value / 10u);
       buffer[index++] = static_cast<Char>('0' + value % 10u);
       buffer[index++] = static_cast<Char>('m');
       buffer[index++] = static_cast<Char>('\0');
       return;
     }
     for (int i = 0; i < 7; i++) {
       buffer[i] = static_cast<Char>(esc[i]);
     }
     rgb color(text_color.value.rgb_color);
     to_esc(color.r, buffer + 7, ';');
     to_esc(color.g, buffer + 11, ';');
     to_esc(color.b, buffer + 15, 'm');
     buffer[19] = static_cast<Char>(0);
   }
References index, ansi_color_escape< Char >::to_esc(), and value< Context >::value().
ansi_color_escape() [2/2]
template<typename Char > FMT_CONSTEXPR ansi_color_escape< Char >::ansi_color_escape (emphasis em) inline
Definition at line 411 of file color.h.
{
     uint8_t em_codes[4] = {};
     uint8_t em_bits = static_cast<uint8_t>(em);
     if (em_bits & static_cast<uint8_t>(emphasis::bold)) em_codes[0] = 1;
     if (em_bits & static_cast<uint8_t>(emphasis::italic)) em_codes[1] = 3;
     if (em_bits & static_cast<uint8_t>(emphasis::underline)) em_codes[2] = 4;
     if (em_bits & static_cast<uint8_t>(emphasis::strikethrough))
       em_codes[3] = 9;
     size_t index = 0;
     for (int i = 0; i < 4; ++i) {
       if (!em_codes[i]) continue;
       buffer[index++] = static_cast<Char>('\x1b');
       buffer[index++] = static_cast<Char>('[');
       buffer[index++] = static_cast<Char>('0' + em_codes[i]);
       buffer[index++] = static_cast<Char>('m');
     }
     buffer[index++] = static_cast<Char>(0);
   }
References bold, index, italic, strikethrough, and underline.
Member Function Documentation
begin()
template<typename Char > FMT_CONSTEXPR const Char* ansi_color_escape< Char >::begin () const inline
Definition at line 432 of file color.h.
 { return buffer; }
References ansi_color_escape< Char >::buffer.
end()
template<typename Char > FMT_CONSTEXPR_CHAR_TRAITS const Char* ansi_color_escape< Char >::end () const inline
Definition at line 433 of file color.h.
{
     return buffer + std::char_traits<Char>::length(buffer);
   }
References G3D::length().
operator const Char *()
template<typename Char > FMT_CONSTEXPR ansi_color_escape< Char >::operator const Char * () const inline
Definition at line 430 of file color.h.
 { return buffer; }
References ansi_color_escape< Char >::buffer.
to_esc()
template<typename Char > static FMT_CONSTEXPR void ansi_color_escape< Char >::to_esc (uint8_t c, Char * out, char delimiter) inline static private
Definition at line 440 of file color.h.
{
     out[0] = static_cast<Char>('0' + c / 100);
     out[1] = static_cast<Char>('0' + c / 10 % 10);
     out[2] = static_cast<Char>('0' + c % 10);
     out[3] = static_cast<Char>(delimiter);
   }
References mpq::c.
Referenced by ansi_color_escape< Char >::ansi_color_escape().
Member Data Documentation
buffer
template<typename Char > Char ansi_color_escape< Char >::buffer[7u+3u *4u+1u] private
Definition at line 438 of file color.h.
Referenced by ansi_color_escape< Char >::begin(), and ansi_color_escape< Char >::operator const Char *().
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/color.h