Azerotcore-wotlk: deps/mysqllite/libmysql/errmsg.c File Reference
errmsg.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include "errmsg.h"
Functions
const char ** get_client_errmsgs ()
void init_client_errs (void)
void finish_client_errs (void)
Variables
const char * client_errors []
Function Documentation
finish_client_errs()
void finish_client_errs (void)
Definition at line 122 of file errmsg.c.
 {
   (void) my_error_unregister(CR_ERROR_FIRST, CR_ERROR_LAST);
 }
References CR_ERROR_FIRST, CR_ERROR_LAST, and my_error_unregister().
Referenced by mysql_server_end().
get_client_errmsgs()
const char** get_client_errmsgs ()
Definition at line 91 of file errmsg.c.
 {
   return client_errors;
 }
References client_errors.
Referenced by init_client_errs().
init_client_errs()
void init_client_errs (void)
Definition at line 106 of file errmsg.c.
 {
   (void) my_error_register(get_client_errmsgs, CR_ERROR_FIRST, CR_ERROR_LAST);
 }
References CR_ERROR_FIRST, CR_ERROR_LAST, get_client_errmsgs(), and my_error_register().
Referenced by mysql_server_init().
Variable Documentation
client_errors
const char* client_errors[]
Definition at line 26 of file errmsg.c.
Referenced by get_client_errmsgs().