Azerotcore-wotlk: boss_victor_nefarius::boss_victor_nefariusAI Struct Reference
boss_victor_nefarius::boss_victor_nefariusAI Struct Reference
Public Member Functions
boss_victor_nefariusAI (Creature *creature)
void Initialize ()
void Reset () override
bool CanAIAttack (const Unit *) const override
void JustReachedHome () override
void BeginEvent (Player *target)
void SummonedCreatureDies (Creature *summon, Unit *) override
void JustSummoned (Creature *) override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void EnterCombat (Unit *) override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 SpawnedAdds
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 169 of file boss_nefarian.cpp.
Constructor & Destructor Documentation
boss_victor_nefariusAI()
boss_victor_nefarius::boss_victor_nefariusAI::boss_victor_nefariusAI (Creature * creature) inline
Definition at line 171 of file boss_nefarian.cpp.
                                                    : BossAI(creature, DATA_NEFARIAN)
         {
             Initialize();
         }
References Initialize().
Member Function Documentation
BeginEvent()
void boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent (Player * target) inline
Definition at line 206 of file boss_nefarian.cpp.
         {
             _EnterCombat();
             Talk(SAY_GAMESBEGIN_2);
             me->SetFaction(FACTION_DRAGONFLIGHT_BLACK);
             me->SetUInt32Value(UNIT_NPC_FLAGS, 0);
             DoCast(me, SPELL_NEFARIANS_BARRIER);
             me->SetStandState(UNIT_STAND_STATE_STAND);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             AttackStart(target);
             events.ScheduleEvent(EVENT_SHADOW_BOLT, urand(3000, 10000));
             events.ScheduleEvent(EVENT_FEAR, urand(10000, 20000));
             events.ScheduleEvent(EVENT_MIND_CONTROL, urand(30000, 35000));
             events.ScheduleEvent(EVENT_SPAWN_ADD, 10000);
         }
References BossAI::_EnterCombat(), ScriptedAI::AttackStart(), UnitAI::DoCast(), EVENT_FEAR, EVENT_MIND_CONTROL, EVENT_SHADOW_BOLT, EVENT_SPAWN_ADD, FACTION_DRAGONFLIGHT_BLACK, ScriptedAI::me, SAY_GAMESBEGIN_2, Unit::SetFaction(), Object::SetFlag(), Unit::SetStandState(), Object::SetUInt32Value(), SPELL_NEFARIANS_BARRIER, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_FLAGS, UNIT_STAND_STATE_STAND, and urand().
Referenced by sGossipSelect().
CanAIAttack()
bool boss_victor_nefarius::boss_victor_nefariusAI::CanAIAttack (const Unit *) const inline override virtual
Reimplemented from UnitAI.
Definition at line 199 of file boss_nefarian.cpp.
 { return me->IsVisible(); }
References Unit::IsVisible(), and ScriptedAI::me.
Initialize()
void boss_victor_nefarius::boss_victor_nefariusAI::Initialize (void) inline
Definition at line 176 of file boss_nefarian.cpp.
         {
             SpawnedAdds = 0;
         }
References SpawnedAdds.
Referenced by boss_victor_nefariusAI(), and Reset().
JustReachedHome()
void boss_victor_nefarius::boss_victor_nefariusAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 201 of file boss_nefarian.cpp.
         {
             Reset();
         }
References Reset().
JustSummoned()
void boss_victor_nefarius::boss_victor_nefariusAI::JustSummoned (Creature *) inline override virtual
Reimplemented from BossAI.
Definition at line 236 of file boss_nefarian.cpp.
 { }
Reset()
void boss_victor_nefarius::boss_victor_nefariusAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 181 of file boss_nefarian.cpp.
         {
             Initialize();
             if (me->GetMapId() == 469)
             {
                 if (!me->FindNearestCreature(NPC_NEFARIAN, 1000.0f, true))
                     _Reset();
                 me->SetVisible(true);
                 me->SetPhaseMask(1, true);
                 me->SetUInt32Value(UNIT_NPC_FLAGS, 1);
                 me->SetFaction(FACTION_FRIENDLY);
                 me->SetStandState(UNIT_STAND_STATE_SIT_HIGH_CHAIR);
                 me->RemoveAura(SPELL_NEFARIANS_BARRIER);
             }
         }
References BossAI::_Reset(), FACTION_FRIENDLY, WorldObject::FindNearestCreature(), WorldLocation::GetMapId(), Initialize(), ScriptedAI::me, NPC_NEFARIAN, Unit::RemoveAura(), Unit::SetFaction(), Unit::SetPhaseMask(), Unit::SetStandState(), Object::SetUInt32Value(), Unit::SetVisible(), SPELL_NEFARIANS_BARRIER, UNIT_NPC_FLAGS, and UNIT_STAND_STATE_SIT_HIGH_CHAIR.
Referenced by JustReachedHome().
SetData()
void boss_victor_nefarius::boss_victor_nefariusAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 238 of file boss_nefarian.cpp.
         {
             if ( type == 1 && data == 1)
             {
                 me->StopMoving();
                 events.ScheduleEvent(EVENT_PATH_2, 9000);
             }
             if (type == 1 && data == 2)
                 events.ScheduleEvent(EVENT_SUCCESS_1, 5000);
         }
References EVENT_PATH_2, EVENT_SUCCESS_1, ScriptedAI::me, and Unit::StopMoving().
sGossipSelect()
void boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 379 of file boss_nefarian.cpp.
         {
             if (sender == GOSSIP_ID && action == GOSSIP_OPTION_ID)
             {
                 // pussywizard:
                 InstanceScript* instance = player->GetInstanceScript();
                 if (!instance || instance->GetBossState(DATA_NEFARIAN) == DONE)
                     return;
                 CloseGossipMenuFor(player);
                 Talk(SAY_GAMESBEGIN_1);
                 BeginEvent(player);
             }
         }
References BeginEvent(), CloseGossipMenuFor(), DATA_NEFARIAN, DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), GOSSIP_ID, GOSSIP_OPTION_ID, BossAI::instance, SAY_GAMESBEGIN_1, and CreatureAI::Talk().
SummonedCreatureDies()
void boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 224 of file boss_nefarian.cpp.
         {
             if (summon->GetEntry() != NPC_NEFARIAN)
             {
                 summon->UpdateEntry(NPC_BONE_CONSTRUCT);
                 summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 summon->SetReactState(REACT_PASSIVE);
                 summon->SetStandState(UNIT_STAND_STATE_DEAD);
             }
         }
References Object::GetEntry(), NPC_BONE_CONSTRUCT, NPC_NEFARIAN, REACT_PASSIVE, Object::SetFlag(), Creature::SetReactState(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_DEAD, and Creature::UpdateEntry().
UpdateAI()
void boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 250 of file boss_nefarian.cpp.
         {
             if (!UpdateVictim())
             {
                 events.Update(diff);
                 while (uint32 eventId = events.ExecuteEvent())
                 {
                     switch (eventId)
                     {
                         case EVENT_PATH_2:
                             me->GetMotionMaster()->MovePath(NEFARIUS_PATH_2, false);
                             events.ScheduleEvent(EVENT_CHAOS_1, 7000);
                             break;
                         case EVENT_CHAOS_1:
                             if (Creature* gyth = me->FindNearestCreature(NPC_GYTH, 75.0f, true))
{
                                 me->SetFacingToObject(gyth);
                                 Talk(SAY_CHAOS_SPELL);
                             }
                             events.ScheduleEvent(EVENT_CHAOS_2, 2000);
                             break;
                         case EVENT_CHAOS_2:
                             DoCast(SPELL_CHROMATIC_CHAOS);
                             me->SetFacingTo(1.570796f);
                             break;
                         case EVENT_SUCCESS_1:
                             if (Unit* player = me->SelectNearestPlayer(60.0f))
{
                                 me->SetFacingToObject(player);
                                 Talk(SAY_SUCCESS);
                                 if (GameObject* portcullis1 = me->FindNearestGameObject(GO_PORTCULLIS_ACTIVE, 65.0f))
                                     portcullis1->SetGoState(GO_STATE_ACTIVE);
                                 if (GameObject* portcullis2 = me->FindNearestGameObject(GO_PORTCULLIS_TOBOSSROOMS, 80.0f))
                                     portcullis2->SetGoState(GO_STATE_ACTIVE);
                             }
                             events.ScheduleEvent(EVENT_SUCCESS_2, 4000);
                             break;
                         case EVENT_SUCCESS_2:
                             DoCast(me, SPELL_VAELASTRASZZ_SPAWN);
                             me->DespawnOrUnsummon(1000);
                             break;
                         case EVENT_PATH_3:
                             me->GetMotionMaster()->MovePath(NEFARIUS_PATH_3, false);
                             break;
                         default:
                             break;
                     }
                 }
                 return;
             }
             // Only do this if we haven't spawned nefarian yet
             if (UpdateVictim() && SpawnedAdds <= 42)
             {
                 events.Update(diff);
                 if (me->HasUnitState(UNIT_STATE_CASTING))
                     return;
                 while (uint32 eventId = events.ExecuteEvent())
                 {
                     switch (eventId)
                     {
                         case EVENT_SHADOW_BOLT:
                             switch (urand(0, 1))
{
                                 case 0:
                                     DoCastVictim(SPELL_SHADOWBOLT_VOLLEY);
                                     break;
                                 case 1:
                                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40, true))
                                         DoCast(target, SPELL_SHADOWBOLT);
                                     break;
                             }
                             DoResetThreat();
                             events.ScheduleEvent(EVENT_SHADOW_BOLT, urand(3000, 10000));
                             break;
                         case EVENT_FEAR:
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40, true))
                                 DoCast(target, SPELL_FEAR);
                             events.ScheduleEvent(EVENT_FEAR, urand(10000, 20000));
                             break;
                         case EVENT_MIND_CONTROL:
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40, true))
                                 DoCast(target, SPELL_SHADOW_COMMAND);
                             events.ScheduleEvent(EVENT_MIND_CONTROL, urand(30000, 35000));
                             break;
                         case EVENT_SPAWN_ADD:
                             for (uint8 i=0; i<2; ++i)
{
                                 uint32 CreatureID;
                                 if (urand(0, 2) == 0)
                                     CreatureID = NPC_CHROMATIC_DRAKANOID;
                                 else
                                     CreatureID = Entry[urand(0, 4)];
                                 if (Creature* dragon = me->SummonCreature(CreatureID, DrakeSpawnLoc[i]))
{
                                     dragon->SetFaction(FACTION_DRAGONFLIGHT_BLACK);
                                     dragon->AI()->AttackStart(me->GetVictim());
                                 }
                                 if (++SpawnedAdds >= 42)
{
                                     if (Creature* nefarian = me->SummonCreature(NPC_NEFARIAN, NefarianLoc[0]))
{
                                         nefarian->setActive(true);
                                         nefarian->SetCanFly(true);
                                         nefarian->SetDisableGravity(true);
                                         nefarian->CastSpell(nullptr, SPELL_SHADOWFLAME_INITIAL);
                                         nefarian->GetMotionMaster()->MovePoint(1, NefarianLoc[1]);
                                     }
                                     events.CancelEvent(EVENT_MIND_CONTROL);
                                     events.CancelEvent(EVENT_FEAR);
                                     events.CancelEvent(EVENT_SHADOW_BOLT);
                                     me->SetVisible(false);
                                     return;
                                 }
                             }
                             events.ScheduleEvent(EVENT_SPAWN_ADD, 4000);
                             break;
                     }
                     if (me->HasUnitState(UNIT_STATE_CASTING))
                         return;
                 }
             }
         }
References Creature::DespawnOrUnsummon(), diff(), UnitAI::DoCast(), UnitAI::DoCastVictim(), ScriptedAI::DoResetThreat(), DrakeSpawnLoc, Entry, EVENT_CHAOS_1, EVENT_CHAOS_2, EVENT_FEAR, EVENT_MIND_CONTROL, EVENT_PATH_2, EVENT_PATH_3, EVENT_SHADOW_BOLT, EVENT_SPAWN_ADD, EVENT_SUCCESS_1, EVENT_SUCCESS_2, FACTION_DRAGONFLIGHT_BLACK, WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), Unit::GetMotionMaster(), Unit::GetVictim(), GO_PORTCULLIS_ACTIVE, GO_PORTCULLIS_TOBOSSROOMS, GO_STATE_ACTIVE, Unit::HasUnitState(), ScriptedAI::me, MotionMaster::MovePath(), NefarianLoc, NEFARIUS_PATH_2, NEFARIUS_PATH_3, NPC_CHROMATIC_DRAKANOID, NPC_GYTH, NPC_NEFARIAN, SAY_CHAOS_SPELL, SAY_SUCCESS, SELECT_TARGET_RANDOM, WorldObject::SelectNearestPlayer(), UnitAI::SelectTarget(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetVisible(), SpawnedAdds, SPELL_CHROMATIC_CHAOS, SPELL_FEAR, SPELL_SHADOW_COMMAND, SPELL_SHADOWBOLT, SPELL_SHADOWBOLT_VOLLEY, SPELL_SHADOWFLAME_INITIAL, SPELL_VAELASTRASZZ_SPAWN, WorldObject::SummonCreature(), CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
SpawnedAdds
uint32 boss_victor_nefarius::boss_victor_nefariusAI::SpawnedAdds private
Definition at line 395 of file boss_nefarian.cpp.
Referenced by Initialize(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp