Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/jemalloc_internal_externs.h File Reference
jemalloc_internal_externs.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/tsd_types.h"
Functions
void * a0malloc (size_t size)
void a0dalloc (void *ptr)
void * bootstrap_malloc (size_t size)
void * bootstrap_calloc (size_t num, size_t size)
void bootstrap_free (void *ptr)
void arena_set (unsigned ind, arena_t *arena)
unsigned narenas_total_get (void)
arena_t * arena_init (tsdn_t *tsdn, unsigned ind, extent_hooks_t *extent_hooks)
arena_tdata_t * arena_tdata_get_hard (tsd_t *tsd, unsigned ind)
arena_t * arena_choose_hard (tsd_t *tsd, bool internal)
void arena_migrate (tsd_t *tsd, unsigned oldind, unsigned newind)
void iarena_cleanup (tsd_t *tsd)
void arena_cleanup (tsd_t *tsd)
void arenas_tdata_cleanup (tsd_t *tsd)
void jemalloc_prefork (void)
void jemalloc_postfork_parent (void)
void jemalloc_postfork_child (void)
bool malloc_initialized (void)
void je_sdallocx_noflags (void *ptr, size_t size)
Variables
bool malloc_slow
bool opt_abort
bool opt_abort_conf
bool opt_confirm_conf
const char * opt_junk
bool opt_junk_alloc
bool opt_junk_free
bool opt_utrace
bool opt_xmalloc
bool opt_zero
unsigned opt_narenas
unsigned ncpus
unsigned narenas_auto
unsigned manual_arena_base
atomic_p_t arenas []
Function Documentation
a0dalloc()
void a0dalloc (void * ptr)
Definition at line 255 of file jemalloc.c.
                     {
     a0idalloc(ptr, true);
 }
References a0idalloc(), and ptr().
Referenced by arena_tdata_get_hard(), and arenas_tdata_cleanup().
a0malloc()
void* a0malloc (size_t size)
Definition at line 250 of file jemalloc.c.
                       {
     return a0ialloc(size, false, true);
 }
References a0ialloc().
Referenced by arena_tdata_get_hard().
arena_choose_hard()
arena_t* arena_choose_hard (tsd_t * tsd, bool internal)
Definition at line 499 of file jemalloc.c.
{
     arena_t *ret JEMALLOC_CC_SILENCE_INIT(NULL);
     if (have_percpu_arena && PERCPU_ARENA_ENABLED(opt_percpu_arena)) {
         unsigned choose = percpu_arena_choose();
         ret = arena_get(tsd_tsdn(tsd), choose, true);
         assert(ret != NULL);
         arena_bind(tsd, arena_ind_get(ret), false);
         arena_bind(tsd, arena_ind_get(ret), true);
         return ret;
     }
     if (narenas_auto > 1) {
         unsigned i, j, choose[2], first_null;
         bool is_new_arena[2];
         /*
          * Determine binding for both non-internal and internal
          * allocation.
          *
          *   choose[0]: For application allocation.
          *   choose[1]: For internal metadata allocation.
          */
         for (j = 0; j < 2; j++) {
             choose[j] = 0;
             is_new_arena[j] = false;
         }
         first_null = narenas_auto;
         malloc_mutex_lock(tsd_tsdn(tsd), &arenas_lock);
         assert(arena_get(tsd_tsdn(tsd), 0, false) != NULL);
         for (i = 1; i < narenas_auto; i++) {
             if (arena_get(tsd_tsdn(tsd), i, false) != NULL) {
                 /*
                  * Choose the first arena that has the lowest
                  * number of threads assigned to it.
                  */
                 for (j = 0; j < 2; j++) {
                     if (arena_nthreads_get(arena_get(
                         tsd_tsdn(tsd), i, false), !!j) <
                         arena_nthreads_get(arena_get(
                         tsd_tsdn(tsd), choose[j], false),
                         !!j)) {
                         choose[j] = i;
                     }
                 }
             } else if (first_null == narenas_auto) {
                 /*
                  * Record the index of the first uninitialized
                  * arena, in case all extant arenas are in use.
                  *
                  * NB: It is possible for there to be
                  * discontinuities in terms of initialized
                  * versus uninitialized arenas, due to the
                  * "thread.arena" mallctl.
                  */
                 first_null = i;
             }
         }
         for (j = 0; j < 2; j++) {
             if (arena_nthreads_get(arena_get(tsd_tsdn(tsd),
                 choose[j], false), !!j) == 0 || first_null ==
                 narenas_auto) {
                 /*
                  * Use an unloaded arena, or the least loaded
                  * arena if all arenas are already initialized.
                  */
                 if (!!j == internal) {
                     ret = arena_get(tsd_tsdn(tsd),
                         choose[j], false);
                 }
             } else {
                 arena_t *arena;
                 /* Initialize a new arena. */
                 choose[j] = first_null;
                 arena = arena_init_locked(tsd_tsdn(tsd),
                     choose[j],
                     (extent_hooks_t *)&extent_hooks_default);
                 if (arena == NULL) {
                     malloc_mutex_unlock(tsd_tsdn(tsd),
                         &arenas_lock);
                     return NULL;
                 }
                 is_new_arena[j] = true;
                 if (!!j == internal) {
                     ret = arena;
                 }
             }
             arena_bind(tsd, choose[j], !!j);
         }
         malloc_mutex_unlock(tsd_tsdn(tsd), &arenas_lock);
         for (j = 0; j < 2; j++) {
             if (is_new_arena[j]) {
                 assert(choose[j] > 0);
                 arena_new_create_background_thread(
                     tsd_tsdn(tsd), choose[j]);
             }
         }
     } else {
         ret = arena_get(tsd_tsdn(tsd), 0, false);
         arena_bind(tsd, 0, false);
         arena_bind(tsd, 0, true);
     }
     return ret;
 }
References arena, arena_bind(), arena_get(), arena_ind_get(), arena_init_locked(), arena_new_create_background_thread(), arena_nthreads_get, arenas_lock, assert(), extent_hooks_default, have_percpu_arena, JEMALLOC_CC_SILENCE_INIT, malloc_mutex_lock(), malloc_mutex_unlock(), narenas_auto, NULL, opt_percpu_arena, percpu_arena_choose(), PERCPU_ARENA_ENABLED, ret, and tsd_tsdn().
arena_cleanup()
void arena_cleanup (tsd_t * tsd)
Definition at line 623 of file jemalloc.c.
{
     arena_t *arena;
     arena = tsd_arena_get(tsd);
     if (arena != NULL) {
         arena_unbind(tsd, arena_ind_get(arena), false);
     }
 }
References arena, arena_ind_get(), arena_unbind(), and NULL.
arena_init()
arena_t* arena_init (tsdn_t * tsdn, unsigned ind, extent_hooks_t * extent_hooks)
Definition at line 364 of file jemalloc.c.
{
     arena_t *arena;
     malloc_mutex_lock(tsdn, &arenas_lock);
     arena = arena_init_locked(tsdn, ind, extent_hooks);
     malloc_mutex_unlock(tsdn, &arenas_lock);
     arena_new_create_background_thread(tsdn, ind);
     return arena;
 }
References arena, arena_init_locked(), arena_new_create_background_thread(), arenas_lock, malloc_mutex_lock(), and malloc_mutex_unlock().
Referenced by malloc_init_hard_a0_locked().
arena_migrate()
void arena_migrate (tsd_t * tsd, unsigned oldind, unsigned newind)
Definition at line 397 of file jemalloc.c.
{
     arena_t *oldarena, *newarena;
     oldarena = arena_get(tsd_tsdn(tsd), oldind, false);
     newarena = arena_get(tsd_tsdn(tsd), newind, false);
     arena_nthreads_dec(oldarena, false);
     arena_nthreads_inc(newarena, false);
     tsd_arena_set(tsd, newarena);
 }
References arena_get(), arena_nthreads_dec, arena_nthreads_inc, and tsd_tsdn().
arena_set()
void arena_set (unsigned ind, arena_t * arena)
Definition at line 297 of file jemalloc.c.
{
     atomic_store_p(&arenas[ind], arena, ATOMIC_RELEASE);
 }
References arena, arenas, and ATOMIC_RELEASE.
arena_tdata_get_hard()
arena_tdata_t* arena_tdata_get_hard (tsd_t * tsd, unsigned ind)
Definition at line 422 of file jemalloc.c.
{
     arena_tdata_t *tdata, *arenas_tdata_old;
     arena_tdata_t *arenas_tdata = tsd_arenas_tdata_get(tsd);
     unsigned narenas_tdata_old, i;
     unsigned narenas_tdata = tsd_narenas_tdata_get(tsd);
     unsigned narenas_actual = narenas_total_get();
     /*
      * Dissociate old tdata array (and set up for deallocation upon return)
      * if it's too small.
      */
     if (arenas_tdata != NULL && narenas_tdata < narenas_actual) {
         arenas_tdata_old = arenas_tdata;
         narenas_tdata_old = narenas_tdata;
         arenas_tdata = NULL;
         narenas_tdata = 0;
         tsd_arenas_tdata_set(tsd, arenas_tdata);
         tsd_narenas_tdata_set(tsd, narenas_tdata);
     } else {
         arenas_tdata_old = NULL;
         narenas_tdata_old = 0;
     }
     /* Allocate tdata array if it's missing. */
     if (arenas_tdata == NULL) {
         bool *arenas_tdata_bypassp = tsd_arenas_tdata_bypassp_get(tsd);
         narenas_tdata = (ind < narenas_actual) ? narenas_actual : ind+1;
         if (tsd_nominal(tsd) && !*arenas_tdata_bypassp) {
             *arenas_tdata_bypassp = true;
             arenas_tdata = (arena_tdata_t *)a0malloc(
                 sizeof(arena_tdata_t) * narenas_tdata);
             *arenas_tdata_bypassp = false;
         }
         if (arenas_tdata == NULL) {
             tdata = NULL;
             goto label_return;
         }
         assert(tsd_nominal(tsd) && !*arenas_tdata_bypassp);
         tsd_arenas_tdata_set(tsd, arenas_tdata);
         tsd_narenas_tdata_set(tsd, narenas_tdata);
     }
     /*
      * Copy to tdata array.  It's possible that the actual number of arenas
      * has increased since narenas_total_get() was called above, but that
      * causes no correctness issues unless two threads concurrently execute
      * the arenas.create mallctl, which we trust mallctl synchronization to
      * prevent.
      */
     /* Copy/initialize tickers. */
     for (i = 0; i < narenas_actual; i++) {
         if (i < narenas_tdata_old) {
             ticker_copy(&arenas_tdata[i].decay_ticker,
                 &arenas_tdata_old[i].decay_ticker);
         } else {
             ticker_init(&arenas_tdata[i].decay_ticker,
                 DECAY_NTICKS_PER_UPDATE);
         }
     }
     if (narenas_tdata > narenas_actual) {
         memset(&arenas_tdata[narenas_actual], 0, sizeof(arena_tdata_t)
             * (narenas_tdata - narenas_actual));
     }
     /* Read the refreshed tdata array. */
     tdata = &arenas_tdata[ind];
 label_return:
     if (arenas_tdata_old != NULL) {
         a0dalloc(arenas_tdata_old);
     }
     return tdata;
 }
References a0dalloc(), a0malloc(), assert(), DECAY_NTICKS_PER_UPDATE, memset, narenas_total_get(), NULL, ticker_copy(), ticker_init(), and tsd_nominal().
arenas_tdata_cleanup()
void arenas_tdata_cleanup (tsd_t * tsd)
Definition at line 633 of file jemalloc.c.
{
     arena_tdata_t *arenas_tdata;
     /* Prevent tsd->arenas_tdata from being (re)created. */
     *tsd_arenas_tdata_bypassp_get(tsd) = true;
     arenas_tdata = tsd_arenas_tdata_get(tsd);
     if (arenas_tdata != NULL) {
         tsd_arenas_tdata_set(tsd, NULL);
         a0dalloc(arenas_tdata);
     }
 }
References a0dalloc(), and NULL.
bootstrap_calloc()
void* bootstrap_calloc (size_t num, size_t size)
Definition at line 275 of file jemalloc.c.
{
     size_t num_size;
     num_size = num * size;
     if (unlikely(num_size == 0)) {
         assert(num == 0 || size == 0);
         num_size = 1;
     }
     return a0ialloc(num_size, true, false);
 }
References a0ialloc(), assert(), and unlikely.
bootstrap_free()
void bootstrap_free (void * ptr)
Definition at line 288 of file jemalloc.c.
{
     if (unlikely(ptr == NULL)) {
         return;
     }
     a0idalloc(ptr, false);
 }
References a0idalloc(), NULL, ptr(), and unlikely.
bootstrap_malloc()
void* bootstrap_malloc (size_t size)
Definition at line 266 of file jemalloc.c.
{
     if (unlikely(size == 0)) {
         size = 1;
     }
     return a0ialloc(size, false, false);
 }
References a0ialloc(), and unlikely.
iarena_cleanup()
void iarena_cleanup (tsd_t * tsd)
Definition at line 613 of file jemalloc.c.
{
     arena_t *iarena;
     iarena = tsd_iarena_get(tsd);
     if (iarena != NULL) {
         arena_unbind(tsd, arena_ind_get(iarena), true);
     }
 }
References arena_ind_get(), arena_unbind(), and NULL.
je_sdallocx_noflags()
void je_sdallocx_noflags (void * ptr, size_t size)
Definition at line 3606 of file jemalloc.c.
{
     LOG("core.sdallocx.entry", "ptr: %p, size: %zu, flags: 0", ptr,
         size);
     if (!free_fastpath(ptr, size, true)) {
         sdallocx_default(ptr, size, 0);
     }
     LOG("core.sdallocx.exit", "");
 }
References free_fastpath(), LOG, ptr(), and sdallocx_default().
jemalloc_postfork_child()
void jemalloc_postfork_child (void)
Definition at line 3894 of file jemalloc.c.
{
     tsd_t *tsd;
     unsigned i, narenas;
     assert(malloc_initialized());
     tsd = tsd_fetch();
     tsd_postfork_child(tsd);
     witness_postfork_child(tsd_witness_tsdp_get(tsd));
     /* Release all mutexes, now that fork() has completed. */
     for (i = 0, narenas = narenas_total_get(); i < narenas; i++) {
         arena_t *arena;
         if ((arena = arena_get(tsd_tsdn(tsd), i, false)) != NULL) {
             arena_postfork_child(tsd_tsdn(tsd), arena);
         }
     }
     prof_postfork_child(tsd_tsdn(tsd));
     if (have_background_thread) {
         background_thread_postfork_child(tsd_tsdn(tsd));
     }
     malloc_mutex_postfork_child(tsd_tsdn(tsd), &arenas_lock);
     tcache_postfork_child(tsd_tsdn(tsd));
     ctl_postfork_child(tsd_tsdn(tsd));
 }
Referenced by malloc_init_hard_recursible().
jemalloc_postfork_parent()
void jemalloc_postfork_parent (void)
Definition at line 3855 of file jemalloc.c.
 {
     tsd_t *tsd;
     unsigned i, narenas;
 #ifdef JEMALLOC_MUTEX_INIT_CB
     if (!malloc_initialized()) {
         return;
     }
 #endif
     assert(malloc_initialized());
     tsd = tsd_fetch();
     tsd_postfork_parent(tsd);
     witness_postfork_parent(tsd_witness_tsdp_get(tsd));
     /* Release all mutexes, now that fork() has completed. */
     for (i = 0, narenas = narenas_total_get(); i < narenas; i++) {
         arena_t *arena;
         if ((arena = arena_get(tsd_tsdn(tsd), i, false)) != NULL) {
             arena_postfork_parent(tsd_tsdn(tsd), arena);
         }
     }
     prof_postfork_parent(tsd_tsdn(tsd));
     if (have_background_thread) {
         background_thread_postfork_parent(tsd_tsdn(tsd));
     }
     malloc_mutex_postfork_parent(tsd_tsdn(tsd), &arenas_lock);
     tcache_postfork_parent(tsd_tsdn(tsd));
     ctl_postfork_parent(tsd_tsdn(tsd));
 }
Referenced by malloc_init_hard_recursible().
jemalloc_prefork()
void jemalloc_prefork (void)
Definition at line 3781 of file jemalloc.c.
 {
     tsd_t *tsd;
     unsigned i, j, narenas;
     arena_t *arena;
 #ifdef JEMALLOC_MUTEX_INIT_CB
     if (!malloc_initialized()) {
         return;
     }
 #endif
     assert(malloc_initialized());
     tsd = tsd_fetch();
     narenas = narenas_total_get();
     witness_prefork(tsd_witness_tsdp_get(tsd));
     /* Acquire all mutexes in a safe order. */
     ctl_prefork(tsd_tsdn(tsd));
     tcache_prefork(tsd_tsdn(tsd));
     malloc_mutex_prefork(tsd_tsdn(tsd), &arenas_lock);
     if (have_background_thread) {
         background_thread_prefork0(tsd_tsdn(tsd));
     }
     prof_prefork0(tsd_tsdn(tsd));
     if (have_background_thread) {
         background_thread_prefork1(tsd_tsdn(tsd));
     }
     /* Break arena prefork into stages to preserve lock order. */
     for (i = 0; i < 8; i++) {
         for (j = 0; j < narenas; j++) {
             if ((arena = arena_get(tsd_tsdn(tsd), j, false)) !=
                 NULL) {
                 switch (i) {
                 case 0:
                     arena_prefork0(tsd_tsdn(tsd), arena);
                     break;
                 case 1:
                     arena_prefork1(tsd_tsdn(tsd), arena);
                     break;
                 case 2:
                     arena_prefork2(tsd_tsdn(tsd), arena);
                     break;
                 case 3:
                     arena_prefork3(tsd_tsdn(tsd), arena);
                     break;
                 case 4:
                     arena_prefork4(tsd_tsdn(tsd), arena);
                     break;
                 case 5:
                     arena_prefork5(tsd_tsdn(tsd), arena);
                     break;
                 case 6:
                     arena_prefork6(tsd_tsdn(tsd), arena);
                     break;
                 case 7:
                     arena_prefork7(tsd_tsdn(tsd), arena);
                     break;
                 default: not_reached();
                 }
             }
         }
     }
     prof_prefork1(tsd_tsdn(tsd));
     tsd_prefork(tsd);
 }
Referenced by malloc_init_hard_recursible().
malloc_initialized()
bool malloc_initialized (void)
Definition at line 209 of file jemalloc.c.
{
     return (malloc_init_state == malloc_init_initialized);
 }
References malloc_init_initialized, and malloc_init_state.
Referenced by ifree(), imalloc_init_check(), isfree(), je_dallocx(), je_malloc_usable_size(), je_rallocx(), je_realloc(), je_sallocx(), je_xallocx(), JEMALLOC_ATTR(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), malloc_init(), malloc_init_hard_needed(), percpu_arena_as_initialized(), and sdallocx_default().
narenas_total_get()
unsigned narenas_total_get (void)
Definition at line 721 of file jemalloc_internal.h.
 {
     unsigned narenas;
     malloc_mutex_lock(&arenas_lock);
     narenas = narenas_total;
     malloc_mutex_unlock(&arenas_lock);
     return (narenas);
 }
References arenas_lock, ATOMIC_ACQUIRE, malloc_mutex_lock(), malloc_mutex_unlock(), and narenas_total.
Referenced by arena_init_locked(), arena_tdata_get_hard(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), malloc_init_narenas(), and stats_print_atexit().
Variable Documentation
arenas
atomic_p_t arenas[] extern
Definition at line 624 of file jemalloc_internal.h.
Referenced by arena_set(), and malloc_init_hard_a0_locked().
malloc_slow
bool malloc_slow extern
Definition at line 106 of file jemalloc.c.
Referenced by malloc_slow_flag_init().
manual_arena_base
unsigned manual_arena_base extern
Definition at line 95 of file jemalloc.c.
Referenced by malloc_init_hard_a0_locked(), and malloc_init_narenas().
narenas_auto
unsigned narenas_auto extern
Definition at line 94 of file jemalloc.c.
Referenced by arena_choose_hard(), malloc_init_hard_a0_locked(), and malloc_init_narenas().
ncpus
unsigned ncpus extern
Definition at line 75 of file jemalloc.c.
Referenced by malloc_init_hard_recursible(), malloc_init_narenas(), and malloc_narenas_default().
opt_abort
bool opt_abort extern
Definition at line 32 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), malloc_init_hard_a0_locked(), malloc_init_hard_recursible(), and malloc_init_narenas().
opt_abort_conf
bool opt_abort_conf extern
Definition at line 39 of file jemalloc.c.
Referenced by malloc_abort_invalid_conf(), and malloc_conf_init_helper().
opt_confirm_conf
bool opt_confirm_conf extern
Definition at line 47 of file jemalloc.c.
Referenced by malloc_conf_init_helper().
opt_junk
const char* opt_junk extern
Definition at line 48 of file jemalloc.c.
Referenced by malloc_conf_init_helper().
opt_junk_alloc
bool opt_junk_alloc extern
Definition at line 55 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), and malloc_slow_flag_init().
opt_junk_free
bool opt_junk_free extern
Definition at line 62 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), and malloc_slow_flag_init().
opt_narenas
unsigned opt_narenas extern
Definition at line 73 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), and malloc_init_narenas().
opt_utrace
bool opt_utrace extern
Definition at line 70 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), and malloc_slow_flag_init().
opt_xmalloc
bool opt_xmalloc extern
Definition at line 71 of file jemalloc.c.
Referenced by imalloc_body(), imalloc_init_check(), je_rallocx(), je_realloc(), malloc_conf_init_helper(), and malloc_slow_flag_init().
opt_zero
bool opt_zero extern
Definition at line 72 of file jemalloc.c.
Referenced by malloc_conf_init_helper(), and malloc_slow_flag_init().