Azerotcore-wotlk: AsyncAcceptor Class Reference
AsyncAcceptor Class Reference
#include <AsyncAcceptor.h>
Public Types
typedef void(* AcceptCallback) (tcp::socket &&newSocket, uint32 threadIndex)
Public Member Functions
AsyncAcceptor (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port)
template<class T >
void AsyncAccept ()
template<AcceptCallback acceptCallback>
void AsyncAcceptWithCallback ()
bool Bind ()
void Close ()
void SetSocketFactory (std::function< std::pair< tcp::socket *, uint32 >()> func)
Private Member Functions
std::pair< tcp::socket *, uint32 > DefeaultSocketFactory ()
Private Attributes
tcp::acceptor _acceptor
tcp::endpoint _endpoint
tcp::socket _socket
std::atomic< bool > _closed
std::function< std::pair< tcp::socket *, uint32 >)> _socketFactory
Detailed Description
Definition at line 36 of file AsyncAcceptor.h.
Member Typedef Documentation
AcceptCallback
typedef void(* AsyncAcceptor::AcceptCallback) (tcp::socket &&newSocket, uint32 threadIndex)
Definition at line 39 of file AsyncAcceptor.h.
Constructor & Destructor Documentation
AsyncAcceptor()
AsyncAcceptor::AsyncAcceptor (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port) inline
Definition at line 41 of file AsyncAcceptor.h.
                                                                                        :
         _acceptor(ioContext), _endpoint(Acore::Net::make_address(bindIp), port),
         _socket(ioContext), _closed(false), _socketFactory(std::bind(&AsyncAcceptor::DefeaultSocketFactory, this))
     {
     }
Member Function Documentation
AsyncAccept()
template<class T > void AsyncAcceptor::AsyncAccept
Definition at line 135 of file AsyncAcceptor.h.
 {
     _acceptor.async_accept(_socket, [this](boost::system::error_code error)
     {
         if (!error)
         {
             try
             {
                 // this-> is required here to fix an segmentation fault in gcc 4.7.2 - reason is lambdas in a templated class
                 std::make_shared<T>(std::move(this->_socket))->Start();
             }
             catch (boost::system::system_error const& err)
             {
                 LOG_INFO("network", "Failed to retrieve client's remote address %s", err.what());
             }
         }
         // lets slap some more this-> on this so we can fix this bug with gcc 4.7.2 throwing internals in yo face
         if (!_closed)
             this->AsyncAccept<T>();
     });
 }
References _acceptor, _closed, _socket, error(), LOG_INFO, and system_error().
AsyncAcceptWithCallback()
template<AcceptCallback acceptCallback> void AsyncAcceptor::AsyncAcceptWithCallback () inline
Definition at line 51 of file AsyncAcceptor.h.
     {
         tcp::socket* socket;
         uint32 threadIndex;
         std::tie(socket, threadIndex) = _socketFactory();
         _acceptor.async_accept(*socket, [this, socket, threadIndex](boost::system::error_code error)
         {
             if (!error)
             {
                 try
                 {
                     socket->non_blocking(true);
                     acceptCallback(std::move(*socket), threadIndex);
                 }
                 catch (boost::system::system_error const& err)
                 {
                     LOG_INFO("network", "Failed to initialize client's socket %s", err.what());
                 }
             }
             if (!_closed)
                 this->AsyncAcceptWithCallback<acceptCallback>();
         });
     }
References _acceptor, _closed, _socketFactory, error(), LOG_INFO, and system_error().
Referenced by AuthSocketMgr::StartNetwork(), and WorldSocketMgr::StartWorldNetwork().
Bind()
bool AsyncAcceptor::Bind () inline
Definition at line 77 of file AsyncAcceptor.h.
     {
         boost::system::error_code errorCode;
         _acceptor.open(_endpoint.protocol(), errorCode);
         if (errorCode)
         {
             LOG_INFO("network", "Failed to open acceptor %s", errorCode.message().c_str());
             return false;
         }
 #if AC_PLATFORM != AC_PLATFORM_WINDOWS
         _acceptor.set_option(boost::asio::ip::tcp::acceptor::reuse_address(true), errorCode);
         if (errorCode)
         {
             LOG_INFO("network", "Failed to set reuse_address option on acceptor %s", errorCode.message().c_str());
             return false;
         }
 #endif
         _acceptor.bind(_endpoint, errorCode);
         if (errorCode)
         {
             LOG_INFO("network", "Could not bind to %s:%u %s", _endpoint.address().to_string().c_str(), _endpoint.port(), errorCode.message().c_str());
             return false;
         }
         _acceptor.listen(ACORE_MAX_LISTEN_CONNECTIONS, errorCode);
         if (errorCode)
         {
             LOG_INFO("network", "Failed to start listening on %s:%u %s", _endpoint.address().to_string().c_str(), _endpoint.port(), errorCode.message().c_str());
             return false;
         }
         return true;
     }
References _acceptor, _endpoint, ACORE_MAX_LISTEN_CONNECTIONS, and LOG_INFO.
Referenced by SocketMgr< SocketType >::StartNetwork().
Close()
void AsyncAcceptor::Close () inline
Definition at line 113 of file AsyncAcceptor.h.
     {
         if (_closed.exchange(true))
             return;
         boost::system::error_code err;
         _acceptor.close(err);
     }
References _acceptor, and _closed.
Referenced by SocketMgr< SocketType >::StopNetwork().
DefeaultSocketFactory()
std::pair<tcp::socket*, uint32> AsyncAcceptor::DefeaultSocketFactory () inline private
Definition at line 125 of file AsyncAcceptor.h.
 { return std::make_pair(&_socket, 0); }
References _socket.
SetSocketFactory()
void AsyncAcceptor::SetSocketFactory (std::function< std::pair< tcp::socket *, uint32 >()> func) inline
Definition at line 122 of file AsyncAcceptor.h.
 { _socketFactory = func; }
References _socketFactory.
Referenced by SocketMgr< SocketType >::StartNetwork().
Member Data Documentation
_acceptor
tcp::acceptor AsyncAcceptor::_acceptor private
Definition at line 127 of file AsyncAcceptor.h.
Referenced by AsyncAccept(), AsyncAcceptWithCallback(), Bind(), and Close().
_closed
std::atomic<bool> AsyncAcceptor::_closed private
Definition at line 130 of file AsyncAcceptor.h.
Referenced by AsyncAccept(), AsyncAcceptWithCallback(), and Close().
_endpoint
tcp::endpoint AsyncAcceptor::_endpoint private
Definition at line 128 of file AsyncAcceptor.h.
Referenced by Bind().
_socket
tcp::socket AsyncAcceptor::_socket private
Definition at line 129 of file AsyncAcceptor.h.
Referenced by AsyncAccept(), and DefeaultSocketFactory().
_socketFactory
std::function<std::pair<tcp::socket*, uint32>)> AsyncAcceptor::_socketFactory private
Definition at line 131 of file AsyncAcceptor.h.
Referenced by AsyncAcceptWithCallback(), and SetSocketFactory().
The documentation for this class was generated from the following file:
src/server/shared/Network/AsyncAcceptor.h