Azerotcore-wotlk: utf8::unchecked Namespace Reference
utf8::unchecked Namespace Reference
Classes
class iterator
Functions
template<typename octet_iterator >
octet_iterator append (uint32_t cp, octet_iterator result)
template<typename octet_iterator >
uint32_t next (octet_iterator &it)
template<typename octet_iterator >
uint32_t peek_next (octet_iterator it)
template<typename octet_iterator >
uint32_t prior (octet_iterator &it)
template<typename octet_iterator >
uint32_t previous (octet_iterator &it)
template<typename octet_iterator , typename distance_type >
void advance (octet_iterator &it, distance_type n)
template<typename octet_iterator >
std::iterator_traits< octet_iterator >::difference_type distance (octet_iterator first, octet_iterator last)
template<typename u16bit_iterator , typename octet_iterator >
octet_iterator utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result)
template<typename u16bit_iterator , typename octet_iterator >
u16bit_iterator utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
octet_iterator utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result)
template<typename octet_iterator , typename u32bit_iterator >
u32bit_iterator utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result)
Function Documentation
advance()
template<typename octet_iterator , typename distance_type > void utf8::unchecked::advance (octet_iterator & it, distance_type n)
Definition at line 113 of file unchecked.h.
         {
             for (distance_type i = 0; i < n; ++i)
                 utf8::unchecked::next(it);
         }
References next().
Referenced by utf8::unchecked::iterator< octet_iterator >::operator++().
append()
template<typename octet_iterator > octet_iterator utf8::unchecked::append (uint32_t cp, octet_iterator result)
Definition at line 38 of file unchecked.h.
         {
             if (cp < 0x80)                        // one octet
                 *(result++) = static_cast<uint8_t>(cp);
             else if (cp < 0x800) {                // two octets
                 *(result++) = static_cast<uint8_t>((cp >> 6)          | 0xc0);
                 *(result++) = static_cast<uint8_t>((cp & 0x3f)        | 0x80);
             }
             else if (cp < 0x10000) {              // three octets
                 *(result++) = static_cast<uint8_t>((cp >> 12)         | 0xe0);
                 *(result++) = static_cast<uint8_t>(((cp >> 6) & 0x3f) | 0x80);
                 *(result++) = static_cast<uint8_t>((cp & 0x3f)        | 0x80);
             }
             else {                                // four octets
                 *(result++) = static_cast<uint8_t>((cp >> 18)         | 0xf0);
                 *(result++) = static_cast<uint8_t>(((cp >> 12) & 0x3f)| 0x80);
                 *(result++) = static_cast<uint8_t>(((cp >> 6) & 0x3f) | 0x80);
                 *(result++) = static_cast<uint8_t>((cp & 0x3f)        | 0x80);
             }
             return result;
         }
Referenced by utf16to8(), and utf32to8().
distance()
template<typename octet_iterator > std::iterator_traits<octet_iterator>::difference_type utf8::unchecked::distance (octet_iterator first, octet_iterator last)
Definition at line 121 of file unchecked.h.
         {
             typename std::iterator_traits<octet_iterator>::difference_type dist;
             for (dist = 0; first < last; ++dist)
                 utf8::unchecked::next(first);
             return dist;
         }
References detail::first(), and next().
next()
template<typename octet_iterator > uint32_t utf8::unchecked::next (octet_iterator & it)
Definition at line 61 of file unchecked.h.
         {
             uint32_t cp = utf8::internal::mask8(*it);
             typename std::iterator_traits<octet_iterator>::difference_type length = utf8::internal::sequence_length(it);
             switch (length) {
                 case 1:
                     break;
                 case 2:
                     it++;
                     cp = ((cp << 6) & 0x7ff) + ((*it) & 0x3f);
                     break;
                 case 3:
                     ++it;
                     cp = ((cp << 12) & 0xffff) + ((utf8::internal::mask8(*it) << 6) & 0xfff);
                     ++it;
                     cp += (*it) & 0x3f;
                     break;
                 case 4:
                     ++it;
                     cp = ((cp << 18) & 0x1fffff) + ((utf8::internal::mask8(*it) << 12) & 0x3ffff);
                     ++it;
                     cp += (utf8::internal::mask8(*it) << 6) & 0xfff;
                     ++it;
                     cp += (*it) & 0x3f;
                     break;
             }
             ++it;
             return cp;
         }
References G3D::length(), utf8::internal::mask8(), and utf8::internal::sequence_length().
Referenced by advance(), distance(), utf8::unchecked::iterator< octet_iterator >::operator*(), peek_next(), prior(), utf8to16(), and utf8to32().
peek_next()
template<typename octet_iterator > uint32_t utf8::unchecked::peek_next (octet_iterator it)
Definition at line 92 of file unchecked.h.
         {
             return utf8::unchecked::next(it);
         }
References next().
previous()
template<typename octet_iterator > uint32_t utf8::unchecked::previous (octet_iterator & it) inline
Definition at line 107 of file unchecked.h.
         {
             return utf8::unchecked::prior(it);
         }
References prior().
prior()
template<typename octet_iterator > uint32_t utf8::unchecked::prior (octet_iterator & it)
Definition at line 98 of file unchecked.h.
         {
             while (utf8::internal::is_trail(*(--it))) ;
             octet_iterator temp = it;
             return utf8::unchecked::next(temp);
         }
References utf8::internal::is_trail(), and next().
Referenced by utf8::unchecked::iterator< octet_iterator >::operator--(), and previous().
utf16to8()
template<typename u16bit_iterator , typename octet_iterator > octet_iterator utf8::unchecked::utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result)
Definition at line 130 of file unchecked.h.
         {
             while (start != end) {
                 uint32_t cp = utf8::internal::mask16(*start++);
             // Take care of surrogate pairs first
                 if (utf8::internal::is_lead_surrogate(cp)) {
                     uint32_t trail_surrogate = utf8::internal::mask16(*start++);
                     cp = (cp << 10) + trail_surrogate + internal::SURROGATE_OFFSET;
                 }
                 result = utf8::unchecked::append(cp, result);
             }
             return result;
         }
References append(), utf8::internal::is_lead_surrogate(), utf8::internal::mask16(), and utf8::internal::SURROGATE_OFFSET.
utf32to8()
template<typename octet_iterator , typename u32bit_iterator > octet_iterator utf8::unchecked::utf32to8 (u32bit_iterator start, u32bit_iterator end, octet_iterator result)
Definition at line 160 of file unchecked.h.
         {
             while (start != end)
                 result = utf8::unchecked::append(*(start++), result);
             return result;
         }
References append().
utf8to16()
template<typename u16bit_iterator , typename octet_iterator > u16bit_iterator utf8::unchecked::utf8to16 (octet_iterator start, octet_iterator end, u16bit_iterator result)
Definition at line 145 of file unchecked.h.
         {
             while (start < end) {
                 uint32_t cp = utf8::unchecked::next(start);
                 if (cp > 0xffff) { //make a surrogate pair
                     *result++ = static_cast<uint16_t>((cp >> 10)   + internal::LEAD_OFFSET);
                     *result++ = static_cast<uint16_t>((cp & 0x3ff) + internal::TRAIL_SURROGATE_MIN);
                 }
                 else
                     *result++ = static_cast<uint16_t>(cp);
             }
             return result;
         }
References utf8::internal::LEAD_OFFSET, next(), and utf8::internal::TRAIL_SURROGATE_MIN.
utf8to32()
template<typename octet_iterator , typename u32bit_iterator > u32bit_iterator utf8::unchecked::utf8to32 (octet_iterator start, octet_iterator end, u32bit_iterator result)
Definition at line 169 of file unchecked.h.
         {
             while (start < end)
                 (*result++) = utf8::unchecked::next(start);
             return result;
         }
References next().