Azerotcore-wotlk: G3D::System Class Reference
G3D::System Class Reference
OS and processor abstraction.
#include <System.h>
Public Types
typedef bool(* OutOfMemoryCallback) (size_t size, bool recoverable)
Static Public Member Functions
static void cleanup ()
static int cpuSpeedMHz ()
static int numCores ()
static bool hasCPUID ()
static bool hasRDTSC ()
static bool hasSSE ()
static bool hasSSE2 ()
static bool hasSSE3 ()
static bool hasMMX ()
static bool has3DNow ()
static const std::string & cpuVendor ()
static G3DEndian machineEndian ()
static const std::string & operatingSystem ()
static const std::string & cpuArchitecture ()
static std::string currentDateString ()
static std::string currentTimeString ()
static void * malloc (size_t bytes)
static void * calloc (size_t n, size_t x)
static void * realloc (void *block, size_t bytes)
static std::string mallocPerformance ()
static void resetMallocPerformanceCounters ()
static std::string mallocStatus ()
static void free (void *p)
static void * alignedMalloc (size_t bytes, size_t alignment)
static void alignedFree (void *ptr)
static void memcpy (void *dst, const void *src, size_t numBytes)
static void memset (void *dst, uint8 value, size_t numBytes)
static std::string currentProgramFilename ()
static std::string & appName ()
static const std::string & version ()
static const std::string & build ()
The optimization status of the G3D library (not the program compiled against it)
static void sleep (RealTime t)
static void consoleClearScreen ()
static bool consoleKeyPressed ()
static int consoleReadKey ()
static RealTime time ()
static void beginCycleCount (uint64 &cycleCount)
static void endCycleCount (uint64 &cycleCount)
static uint64 getCycleCount ()
static void setOutOfMemoryCallback (OutOfMemoryCallback c)
static OutOfMemoryCallback outOfMemoryCallback ()
static void setEnv (const std::string &name, const std::string &value)
static const char * getEnv (const std::string &name)
static void describeSystem (class TextOutput &t)
static void describeSystem (std::string &s)
static std::string findDataFile (const std::string &full, bool exceptionIfNotFound=true, bool caseSensitive=true)
static void setAppDataDir (const std::string &path)
Private Types
enum CPUIDFunction {
CPUID_VENDOR_ID = 0x00000000 , CPUID_PROCESSOR_FEATURES = 0x00000001 , CPUID_NUM_CORES = 0x00000004 , CPUID_GET_HIGHEST_FUNCTION = 0x80000000 ,
CPUID_EXTENDED_FEATURES = 0x80000001
}
Private Member Functions
System ()
Used for the singleton instance only.
void getStandardProcessorExtensions ()
void initTime ()
void init ()
Static Private Member Functions
static System & instance ()
The singleton instance.
static void cpuid (CPUIDFunction func, uint32 &areg, uint32 &breg, uint32 &creg, uint32 &dreg)
Private Attributes
bool m_initialized
int m_cpuSpeed
bool m_hasCPUID
bool m_hasRDTSC
bool m_hasMMX
bool m_hasSSE
bool m_hasSSE2
bool m_hasSSE3
bool m_has3DNOW
bool m_has3DNOW2
bool m_hasAMDMMX
std::string m_cpuVendor
int m_numCores
std::string m_appDataDir
G3DEndian m_machineEndian
std::string m_cpuArch
std::string m_operatingSystem
struct timeval m_start
std::string m_version
OutOfMemoryCallback m_outOfMemoryCallback
RealTime m_realWorldGetTickTime0
uint32 m_highestCPUIDFunction
Detailed Description
OS and processor abstraction.
The first time any method is called the processor will be analyzed. Future calls are then fast.
Timing function overview: System::getCycleCount
actual cycle count
System::getTick
High-resolution time in seconds since program started
System::getLocalTime
High-resolution time in seconds since Jan 1, 1970 (because it is stored in a double, this may be less accurate than getTick)
Definition at line 75 of file System.h.
Member Typedef Documentation
OutOfMemoryCallback
typedef bool(* G3D::System::OutOfMemoryCallback) (size_t size, bool recoverable)
Parameters
size Size of memory that the system was trying to allocate
recoverable If true, the system will attempt to allocate again if the callback returns true. If false, malloc is going to return NULL and this invocation is just to notify the application.
Returns
Return true to force malloc to attempt allocation again if the error was recoverable.
Definition at line 87 of file System.h.
Member Enumeration Documentation
CPUIDFunction
enum G3D::System::CPUIDFunction private
Enumerator
CPUID_VENDOR_ID
CPUID_PROCESSOR_FEATURES
CPUID_NUM_CORES
CPUID_GET_HIGHEST_FUNCTION
CPUID_EXTENDED_FEATURES
Definition at line 146 of file System.h.
{
         CPUID_VENDOR_ID              = 0x00000000,
         CPUID_PROCESSOR_FEATURES     = 0x00000001,
         CPUID_NUM_CORES              = 0x00000004,
         CPUID_GET_HIGHEST_FUNCTION   = 0x80000000,
         CPUID_EXTENDED_FEATURES      = 0x80000001};
Constructor & Destructor Documentation
System()
G3D::System::System () private
Used for the singleton instance only.
Definition at line 104 of file System.cpp.
                :
     m_initialized(false),
     m_cpuSpeed(0),
     m_hasCPUID(false),
     m_hasRDTSC(false),
     m_hasMMX(false),
     m_hasSSE(false),
     m_hasSSE2(false),
     m_hasSSE3(false),
     m_has3DNOW(false),
     m_has3DNOW2(false),
     m_hasAMDMMX(false),
     m_cpuVendor("Uninitialized"),
     m_numCores(1),
     m_machineEndian(G3D_LITTLE_ENDIAN),
     m_cpuArch("Uninitialized"),
     m_operatingSystem("Uninitialized"),
     m_version("Uninitialized"),
     m_outOfMemoryCallback(NULL),
     m_realWorldGetTickTime0(0),
     m_highestCPUIDFunction(0) {
     init();
 }
References init().
Member Function Documentation
alignedFree()
void G3D::System::alignedFree (void * ptr) static
Frees memory allocated with alignedMalloc.
Definition at line 1548 of file System.cpp.
{
     if (_ptr == NULL) {
         return;
     }
     size_t alignedPtr = (size_t)_ptr;
     // Back up one word from the pointer the user passed in.
     // We now have a pointer to a pointer to the true start
     // of the memory block.
     size_t* redirectPtr = (size_t*)(alignedPtr - sizeof(void *));
     // Dereference that pointer so that ptr = true start
     void* truePtr = (void*)redirectPtr[0];
     debugAssert(isValidHeapPointer((void*)truePtr));
     System::free(truePtr);
 }
References debugAssert, free(), G3D::isValidHeapPointer(), and NULL.
Referenced by G3D::BinaryInput::decompress(), G3D::AlignedMemoryManager::free(), G3D::readWholeFile(), G3D::Matrix::Impl::setSize(), G3D::Matrix::svdCore(), G3D::BinaryInput::~BinaryInput(), and G3D::Matrix::Impl::~Impl().
alignedMalloc()
void * G3D::System::alignedMalloc (size_t bytes, size_t alignment) static
Guarantees that the start of the array is aligned to the specified number of bytes.
Definition at line 1484 of file System.cpp.
{
     alwaysAssertM(isPow2((uint32)alignment), "alignment must be a power of 2");
     // We must align to at least a word boundary.
     alignment = max(alignment, sizeof(void *));
     // Pad the allocation size with the alignment size and the size of
     // the redirect pointer.  This is the worst-case size we'll need.
     // Since the alignment size is at least teh word size, we don't
     // need to allocate space for the redirect pointer.  We repeat the max here
     // for clarity.
     size_t totalBytes = bytes + max(alignment, sizeof(void*));
     size_t truePtr = (size_t)System::malloc(totalBytes);
     if (truePtr == 0) {
         // malloc returned NULL
         return NULL;
     }
     debugAssert(isValidHeapPointer((void*)truePtr));
     #ifdef G3D_WINDOWS
     // The blocks we return will not be valid Win32 debug heap
     // pointers because they are offset
     //  debugAssert(_CrtIsValidPointer((void*)truePtr, totalBytes, TRUE) );
     #endif
     // We want alignedPtr % alignment == 0, which we'll compute with a
     // binary AND because 2^n - 1 has the form 1111... in binary.
     const size_t bitMask = (alignment - 1);
     // The return pointer will be the next aligned location that is at
     // least sizeof(void*) after the true pointer. We need the padding
     // to have a place to write the redirect pointer.
     size_t alignedPtr = truePtr + sizeof(void*);
     const size_t remainder = alignedPtr & bitMask;
     // Add what we need to make it to the next alignment boundary, but
     // if the remainder was zero, let it wrap to zero and don't add
     // anything.
     alignedPtr += ((alignment - remainder) & bitMask);
     debugAssert((alignedPtr & bitMask) == 0);
     debugAssert((alignedPtr - truePtr + bytes) <= totalBytes);
     // Immediately before the aligned location, write the true array location
     // so that we can free it correctly.
     size_t* redirectPtr = (size_t *)(alignedPtr - sizeof(void *));
     redirectPtr[0] = truePtr;
     debugAssert(isValidHeapPointer((void*)truePtr));
     #if defined(G3D_WINDOWS) && defined(G3D_DEBUG)
         if (bytes < 0xFFFFFFFF) {
             debugAssert( _CrtIsValidPointer((void*)alignedPtr, (int)bytes, TRUE) );
         }
     #endif
     return (void *)alignedPtr;
 }
References alwaysAssertM, debugAssert, G3D::isPow2(), G3D::isValidHeapPointer(), malloc(), G3D::max(), NULL, and TRUE.
Referenced by G3D::AlignedMemoryManager::alloc(), G3D::BinaryInput::BinaryInput(), G3D::BinaryInput::decompress(), G3D::readWholeFile(), G3D::Matrix::Impl::setSize(), and G3D::Matrix::svdCore().
appName()
std::string & G3D::System::appName () static
Name of this program. Note that you can mutate this string to set your app name explicitly.
Definition at line 742 of file System.cpp.
{
     static std::string n = computeAppName(filenameBase(currentProgramFilename()));
     return n;
 }
References G3D::computeAppName(), currentProgramFilename(), and G3D::filenameBase().
beginCycleCount()
void G3D::System::beginCycleCount (uint64 & cycleCount) inline static
To count the number of cycles a given operation takes:
unsigned long count;
System::beginCycleCount(count);
...
System::endCycleCount(count);
// count now contains the cycle count for the intervening operation.
Definition at line 551 of file System.h.
{
     cycleCount = getCycleCount();
 }
References getCycleCount().
Referenced by G3D::Stopwatch::tick().
build()
const std::string & G3D::System::build () static
The optimization status of the G3D library (not the program compiled against it)
Either "Debug" or "Release", depending on whether _DEBUG was defined at compile-time for the library.
Definition at line 526 of file System.cpp.
{
     const static std::string b =
 #   ifdef _DEBUG
         "Debug";
 #   else
         "Release";
 #   endif
     return b;
 }
References b.
calloc()
void * G3D::System::calloc (size_t n, size_t x) static
Definition at line 1452 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     void* b = System::malloc(n * x);
     debugAssertM(b != NULL, "System::malloc returned NULL");
     debugAssertM(isValidHeapPointer(b), "System::malloc returned an invalid pointer");
     System::memset(b, 0, n * x);
     return b;
 #else
     return ::calloc(n, x);
 #endif
 }
References b, debugAssertM, G3D::isValidHeapPointer(), malloc(), memset(), NULL, and G3D::x.
cleanup()
void G3D::System::cleanup () static
atexit handling code invoked from G3DCleanupHook.
Definition at line 520 of file System.cpp.
                      {
     lastFound.clear();
     directoryArray.clear();
 }
References G3D::Array< T, MIN_ELEMENTS >::clear(), G3D::directoryArray, and G3D::lastFound.
consoleClearScreen()
void G3D::System::consoleClearScreen () static
Clears the console. Console programs only.
Definition at line 839 of file System.cpp.
{
 #   ifdef G3D_WINDOWS
         (void)system("cls");
 #   else
         (void)system("clear");
 #   endif
 }
consoleKeyPressed()
bool G3D::System::consoleKeyPressed () static
Returns true if a key is waiting. Console programs only.
Definition at line 848 of file System.cpp.
{
     #ifdef G3D_WINDOWS
         return _kbhit() != 0;
     #else
         static const int STDIN = 0;
         static bool initialized = false;
         if (! initialized) {
             // Use termios to turn off line buffering
             termios term;
             tcgetattr(STDIN, &term);
             term.c_lflag &= ~ICANON;
             tcsetattr(STDIN, TCSANOW, &term);
             setbuf(stdin, NULL);
             initialized = true;
         }
         #ifdef G3D_LINUX
             int bytesWaiting;
             ioctl(STDIN, FIONREAD, &bytesWaiting);
             return bytesWaiting;
         #else
             timeval timeout;
             fd_set rdset;
             FD_ZERO(&rdset);
             FD_SET(STDIN, &rdset);
             timeout.tv_sec  = 0;
             timeout.tv_usec = 0;
             return select(STDIN + 1, &rdset, NULL, NULL, &timeout);
         #endif
     #endif
 }
References initialized, and NULL.
consoleReadKey()
int G3D::System::consoleReadKey () static
Blocks until a key is read (use consoleKeyPressed to determine if a key is waiting to be read) then returns the character code for that key.
Definition at line 890 of file System.cpp.
{
 #   ifdef G3D_WINDOWS
         return _getch();
 #   else
         char c;
         (void)read(0, &c, 1);
         return c;
 #   endif
 }
References _getch, mpq::c, and read.
cpuArchitecture()
static const std::string& G3D::System::cpuArchitecture () inline static
e.g., 80686
Definition at line 233 of file System.h.
{
         return instance().m_cpuArch;
     }
References instance(), and m_cpuArch.
Referenced by describeSystem().
cpuid()
void G3D::System::cpuid (CPUIDFunction func, uint32 & areg, uint32 & breg, uint32 & creg, uint32 & dreg) static private
Helper macro to call cpuid functions and return all values
See http://software.intel.com/en-us/articles/intel-64-architecture-processor-topology-enumeration/ or http://www.amd.com/us-en/assets/content_type/white_papers_and_tech_docs/25481.pdf
for description of the arguments.
Definition at line 1716 of file System.cpp.
{
 #if ! defined(__PIC__) || defined(__x86_64__)
     // AT&T assembler syntax
     asm volatile(
                  "movl $0, %%ecx   \n\n" /* Wipe ecx */
                  "cpuid            \n\t"
                  : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
                  : "a"(func));
 #else
     // AT&T assembler syntax
     asm volatile(
                  "pushl %%ebx      \n\t" /* save ebx */
                  "movl $0, %%ecx   \n\n" /* Wipe ecx */
                  "cpuid            \n\t"
                  "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                  "popl %%ebx       \n\t" /* restore the old ebx */
                  : "=a"(eax), "=r"(ebx), "=c"(ecx), "=d"(edx)
                  : "a"(func));
 #endif
 }
Referenced by getStandardProcessorExtensions(), and init().
cpuSpeedMHz()
static int G3D::System::cpuSpeedMHz () inline static
Returns the speed of processor 0 in MHz. Always returns 0 on linux.
Definition at line 178 of file System.h.
{
         return instance().m_cpuSpeed;
     }
References instance(), and m_cpuSpeed.
cpuVendor()
static const std::string& G3D::System::cpuVendor () inline static
Definition at line 216 of file System.h.
{
         return instance().m_cpuVendor;
     }
References instance(), and m_cpuVendor.
Referenced by describeSystem().
currentDateString()
std::string G3D::System::currentDateString () static
Returns the current date as a string in the form YYYY-MM-DD
Definition at line 1675 of file System.cpp.
{
     time_t t1;
     ::time(&t1);
     tm* t = localtime(&t1);
     return format("%d-%02d-%02d", t->tm_year + 1900, t->tm_mon + 1, t->tm_mday);
 }
References G3D::format(), localtime(), and time().
Referenced by G3D::generateFilenameBase().
currentProgramFilename()
std::string G3D::System::currentProgramFilename () static
Returns the fully qualified filename for the currently running executable.
This is more reliable than arg[0], which may be intentionally set to an incorrect value by a calling program, relative to a now non-current directory, or obfuscated by sym-links.
[Linux] version written by Nicolai Haehnle prefe.nosp@m.ct_@.nosp@m.gmx.n.nosp@m.et, http://www.flipcode.com/cgi-bin/msg.cgi?showThread=COTD-getexename&forum=cotd&id=-1
Definition at line 748 of file System.cpp.
{
     char filename[2048];
 #   ifdef G3D_WINDOWS
     {
         GetModuleFileNameA(NULL, filename, sizeof(filename));
     }
 #   elif defined(G3D_OSX)
     {
         // Run the 'ps' program to extract the program name
         // from the process ID.
         int pid;
         FILE* fd;
         char cmd[80];
         pid = getpid();
         sprintf(cmd, "ps -p %d -o comm=\"\"", pid);
         fd = popen(cmd, "r");
         int s = fread(filename, 1, sizeof(filename), fd);
         // filename will contain a newline.  Overwrite it:
         filename[s - 1] = '\0';
         pclose(fd);
     }
 #   else
     {
         int ret = readlink("/proc/self/exe", filename, sizeof(filename));
         // In case of an error, leave the handling up to the caller
         if (ret == -1) {
             return "";
         }
         debugAssert((int)sizeof(filename) > ret);
         // Ensure proper NULL termination
         filename[ret] = 0;
     }
     #endif
     return filename;
 }
References debugAssert, NULL, readlink, ret, and sprintf().
Referenced by appName(), describeSystem(), and init().
currentTimeString()
std::string G3D::System::currentTimeString () static
Returns the current 24-hour local time as a string in the form HH:MM:SS
Definition at line 1682 of file System.cpp.
{
     time_t t1;
     ::time(&t1);
     tm* t = localtime(&t1);
     return format("%02d:%02d:%02d", t->tm_hour, t->tm_min, t->tm_sec);
 }
References G3D::format(), localtime(), and time().
describeSystem() [1/2]
void G3D::System::describeSystem (class TextOutput & t) static
Prints a human-readable description of this machine to the text output stream. Either argument may be NULL.
Definition at line 1612 of file System.cpp.
                    {
     t.writeSymbols("App", "{");
     t.writeNewline();
     t.pushIndent();
     {
         var(t, "Name", System::currentProgramFilename());
         char cwd[1024];
         (void)getcwd(cwd, 1024);
         var(t, "cwd", std::string(cwd));
     }
     t.popIndent();
     t.writeSymbols("}");
     t.writeNewline();
     t.writeNewline();
     t.writeSymbols("OS", "{");
     t.writeNewline();
     t.pushIndent();
     {
         var(t, "Name", System::operatingSystem());
     }
     t.popIndent();
     t.writeSymbols("}");
     t.writeNewline();
     t.writeNewline();
     t.writeSymbols("CPU", "{");
     t.writeNewline();
     t.pushIndent();
     {
         var(t, "Vendor", System::cpuVendor());
         var(t, "Architecture", System::cpuArchitecture());
         var(t, "hasCPUID", System::hasCPUID());
         var(t, "hasMMX", System::hasMMX());
         var(t, "hasSSE", System::hasSSE());
         var(t, "hasSSE2", System::hasSSE2());
         var(t, "hasSSE3", System::hasSSE3());
         var(t, "has3DNow", System::has3DNow());
         var(t, "hasRDTSC", System::hasRDTSC());
         var(t, "numCores", System::numCores());
     }
     t.popIndent();
     t.writeSymbols("}");
     t.writeNewline();
     t.writeNewline();
     t.writeSymbols("G3D", "{");
     t.writeNewline();
     t.pushIndent();
     {
         const char* g3dPath = getenv("G3D9DATA");
         var(t, "Link version", G3D_VER);
         var(t, "Compile version", System::version());
         var(t, "G3D9DATA", std::string(g3dPath ? g3dPath : ""));
     }
     t.popIndent();
     t.writeSymbols("}");
     t.writeNewline();
     t.writeNewline();
 }
References cpuArchitecture(), cpuVendor(), currentProgramFilename(), G3D_VER, has3DNow(), hasCPUID(), hasMMX(), hasRDTSC(), hasSSE(), hasSSE2(), hasSSE3(), numCores(), operatingSystem(), G3D::TextOutput::popIndent(), G3D::TextOutput::pushIndent(), G3D::var(), version(), G3D::TextOutput::writeNewline(), and G3D::TextOutput::writeSymbols().
Referenced by describeSystem().
describeSystem() [2/2]
void G3D::System::describeSystem (std::string & s) static
Definition at line 1604 of file System.cpp.
{
     TextOutput t;
     describeSystem(t);
     t.commitString(s);
 }
References G3D::TextOutput::commitString(), and describeSystem().
endCycleCount()
void G3D::System::endCycleCount (uint64 & cycleCount) inline static
Definition at line 556 of file System.h.
{
 #ifndef G3D_OSX
     cycleCount = getCycleCount() - cycleCount;
 #else
     AbsoluteTime end = UpTime();
     Nanoseconds diffNS =
         AbsoluteDeltaToNanoseconds(end, UInt64ToUnsignedWide(cycleCount));
     cycleCount =
         (uint64) ((double) (instance().m_OSXCPUSpeed) *
                   (double) UnsignedWideToUInt64(diffNS) * instance().m_secondsPerNS);
 #endif
 }
References getCycleCount(), and instance().
Referenced by G3D::Stopwatch::tock().
findDataFile()
std::string G3D::System::findDataFile (const std::string & full, bool exceptionIfNotFound = true, bool caseSensitive = true) static
Tries to locate the resource by looking in related directories. If found, returns the full path to the resource, otherwise returns the empty string.
Looks in:
- Literal interpretation of full (i.e., if it contains a fully-qualified name)
- Last directory in which a file was found
- Current directory
- System::appDataDir (which is usually GApp::Settings.dataDir, which defaults to the directory containing the program binary)
- $G3D9DATA directory
- System::appDataDir() + "data/"  (note that this may be a zipfile named "data" with no extension)
- System::appDataDir() + "data.zip/"
- ../data-files/  (windows)
- ../../data-files/ (windows)
- ../../../data-files/ (windows)
Plus the following subdirectories of those:
cubemap
gui
font
icon
models
image
sky
md2
md3
ifs
3ds
Parameters
exceptionIfNotFound If true and the file is not found, throws G3D::FileNotFound.
Definition at line 366 of file System.cpp.
{
 MARK_LOG();
     const std::string full = FilePath::expandEnvironmentVariables(_full);
     // First check if the file exists as requested.  This will go
     // through the FileSystemCache, so most calls do not touch disk.
     if (FileSystem::exists(full, true, caseSensitive)) {
         return full;
     }
 MARK_LOG();
     // Now check where we previously found this file.
     std::string* last = lastFound.getPointer(full);
     if (last != NULL) {
         if (FileSystem::exists(*last, true, caseSensitive)) {
             // Even if cwd has changed the file is still present.
             // We won't notice if it has been deleted, however.
             return *last;
         } else {
             // Remove this from the cache it is invalid
             lastFound.remove(full);
         }
     }
 MARK_LOG();
     const std::string initialAppDataDir(instance().m_appDataDir);
     const char* g3dPath = getenv("G3D9DATA");
     if (directoryArray.size() == 0) {
         // Initialize the directory array
         RealTime t0 = System::time();
         Array<std::string> baseDirArray;
         baseDirArray.append(FileSystem::currentDirectory());
 MARK_LOG();
         if (! initialAppDataDir.empty()) {
 MARK_LOG();
             baseDirArray.append(initialAppDataDir);
             baseDirArray.append(pathConcat(initialAppDataDir, "data"));
             baseDirArray.append(pathConcat(initialAppDataDir, "data.zip"));
         } else {
 MARK_LOG();
             baseDirArray.append("data");
             baseDirArray.append("data.zip");
         }
 MARK_LOG();
 #       ifdef G3D_WINDOWS
         if (g3dPath == NULL) {
             // If running the demos under visual studio from the G3D.sln file,
             // this will locate the data directory.
             const char* paths[] = {"../data-files/", "../../data-files/", "../../../data-files/", NULL};
             for (int i = 0; paths[i]; ++i) {
                 if (FileSystem::exists(pathConcat(paths[i], "G3D-DATA-README.TXT"), true, caseSensitive)) {
                     g3dPath = paths[i];
                     break;
                 }
             }
         }
 #       endif
         if (g3dPath && (initialAppDataDir != g3dPath)) {
             baseDirArray.append(g3dPath);
         }
         static const std::string subdirs[] =
             {"font", "gui", "shader", "model", "cubemap", "icon", "material", "image", "md2", "md3", "ifs", "3ds", "sky", "music", "sound", "scene", ""};
         for (int j = 0; j < baseDirArray.size(); ++j) {
             std::string d = baseDirArray[j];
 //logPrintf("%s", d.c_str());
             if ((d == "") || FileSystem::exists(d)) {
 //logPrintf(" exists\n");
                 directoryArray.append(d);
                 for (int i = 0; ! subdirs[i].empty(); ++i) {
                     const std::string& p = pathConcat(d, subdirs[i]);
                     if (FileSystem::exists(p, true, caseSensitive)) {
                         directoryArray.append(p);
                     }
                 }
             } else {
 //logPrintf(" does not exist\n");
             }
         }
         logLazyPrintf("Initializing System::findDataFile took %fs\n", System::time() - t0);
     }
 MARK_LOG();
     for (int i = 0; i < directoryArray.size(); ++i) {
         const std::string& p = pathConcat(directoryArray[i], full);
         if (FileSystem::exists(p, true, caseSensitive)) {
             lastFound.set(full, p);
             return p;
         }
     }
 MARK_LOG();
     if (errorIfNotFound) {
         // Generate an error message.  Delay this operation until we know that we need it;
         // otherwise all of the string concatenation would run on each successful find.
         std::string locations;
         for (int i = 0; i < directoryArray.size(); ++i) {
             locations += "\'" + pathConcat(directoryArray[i], full) + "'\n";
         }
 MARK_LOG();
         std::string msg = "Could not find '" + full + "'.\n\n";
         msg +=     "  cwd                    = '" + FileSystem::currentDirectory() + "'\n";
         if (g3dPath) {
             msg += "  G3D9DATA               = '" + std::string(g3dPath) + "'";
             if (! FileSystem::exists(g3dPath, true, caseSensitive)) {
                 msg += " (illegal path!)";
             }
             msg += "\n";
         } else {
             msg += "  G3D9DATA               = (environment variable is not defined)\n";
         }
 MARK_LOG();
         msg +=     "  GApp::Settings.dataDir = '" + initialAppDataDir + "'";
         if (! FileSystem::exists(initialAppDataDir, true, caseSensitive)) {
             msg += " (illegal path!)";
         }
         msg += "\n";
         msg += "\nFilenames tested:\n" + locations;
 MARK_LOG();
 logPrintf("%s\n", msg.c_str());
         throw FileNotFound(full, msg);
         alwaysAssertM(false, msg);
     }
 MARK_LOG();
     // Not found
     return "";
 }
References alwaysAssertM, G3D::Array< T, MIN_ELEMENTS >::append(), G3D::FileSystem::currentDirectory(), mpq::d, G3D::directoryArray, G3D::FileSystem::exists(), G3D::FilePath::expandEnvironmentVariables(), instance(), G3D::lastFound, G3D::logLazyPrintf(), G3D::logPrintf(), m_appDataDir, MARK_LOG, NULL, G3D::pathConcat(), G3D::Array< T, MIN_ELEMENTS >::size(), and time().
Referenced by G3D::Any::deserialize(), and G3D::Any::resolveStringAsFilename().
free()
void G3D::System::free (void * p) static
Free data allocated with System::malloc.
Threadsafe on Win32.
Definition at line 1475 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     bufferpool->free(p);
 #else
     return ::free(p);
 #endif
 }
References G3D::bufferpool, and G3D::BufferPool::free().
Referenced by alignedFree(), G3D::bayer_bggr8_to_rgba32f(), G3D::bayer_gbrg8_to_rgba32f(), G3D::bayer_grbg8_to_rgba32f(), G3D::bayer_rggb8_to_rgba32f(), G3D::Queue< T >::clear(), G3D::BinaryOutput::compress(), G3D::ImageFormat::convert(), G3D::GImage::decodeBMP(), G3D::GImage::encodeJPEG(), G3D::GImage::flipRGBAVertical(), G3D::GImage::flipRGBVertical(), G3D::MemoryManager::free(), init(), G3D::Matrix::Impl::operator delete(), G3D::Queue< T >::repackAndRealloc(), G3D::rgba32f_to_bayer_bggr8(), G3D::rgba32f_to_bayer_gbrg8(), G3D::rgba32f_to_bayer_grbg8(), G3D::rgba32f_to_bayer_rggb8(), G3D::Matrix::Impl::setSize(), G3D::vformat(), G3D::BinaryOutput::~BinaryOutput(), G3D::Matrix::Impl::~Impl(), and G3D::PrecomputedRandom::~PrecomputedRandom().
getCycleCount()
static uint64 G3D::System::getCycleCount () static
Referenced by beginCycleCount(), and endCycleCount().
getEnv()
const char * G3D::System::getEnv (const std::string & name) static
Get an environment variable for the current process. Returns NULL if the variable doesn't exist.
Definition at line 1579 of file System.cpp.
{
     return getenv(name.c_str());
 }
getStandardProcessorExtensions()
void G3D::System::getStandardProcessorExtensions () private
Called from init()
Definition at line 557 of file System.cpp.
{
 #if ! defined(G3D_OSX) || defined(G3D_OSX_INTEL)
     if (! m_hasCPUID) {
         return;
     }
     uint32 eaxreg = 0, ebxreg = 0, ecxreg = 0, features = 0;
     cpuid(CPUID_PROCESSOR_FEATURES, eaxreg, ebxreg, ecxreg, features);
 #   define checkBit(var, bit)   ((var & (1 << bit)) ? true : false)
     m_hasRDTSC    = checkBit(features, 4);
     m_hasMMX      = checkBit(features, 23);
     m_hasSSE      = checkBit(features, 25);
     m_hasSSE2     = checkBit(features, 26);
     // Bit 28 is HTT; not checked by G3D
     m_hasSSE3     = checkBit(ecxreg, 0);
     if (m_highestCPUIDFunction >= CPUID_EXTENDED_FEATURES) {
         cpuid(CPUID_EXTENDED_FEATURES, eaxreg, ebxreg, ecxreg, features);
         m_hasAMDMMX = checkBit(features, 22);  // Only on AMD
         m_has3DNOW  = checkBit(features, 31);  // Only on AMD
         m_has3DNOW2 = checkBit(features, 30);  // Only on AMD
     } else {
         m_hasAMDMMX = false;
         m_has3DNOW  = false;
         m_has3DNOW2 = false;
     }
 #   undef checkBit
 #endif
 }
References checkBit, cpuid(), CPUID_EXTENDED_FEATURES, CPUID_PROCESSOR_FEATURES, m_has3DNOW, m_has3DNOW2, m_hasAMDMMX, m_hasCPUID, m_hasMMX, m_hasRDTSC, m_hasSSE, m_hasSSE2, m_hasSSE3, and m_highestCPUIDFunction.
Referenced by init().
has3DNow()
static bool G3D::System::has3DNow () inline static
Definition at line 212 of file System.h.
{
         return instance().m_has3DNOW;
     }
References instance(), and m_has3DNOW.
Referenced by describeSystem().
hasCPUID()
static bool G3D::System::hasCPUID () inline static
Definition at line 188 of file System.h.
{
         return instance().m_hasCPUID;
     }
References instance(), and m_hasCPUID.
Referenced by describeSystem().
hasMMX()
static bool G3D::System::hasMMX () inline static
Definition at line 208 of file System.h.
{
         return instance().m_hasMMX;
     }
References instance(), and m_hasMMX.
Referenced by describeSystem().
hasRDTSC()
static bool G3D::System::hasRDTSC () inline static
Definition at line 192 of file System.h.
{
         return instance().m_hasRDTSC;
     }
References instance(), and m_hasRDTSC.
Referenced by describeSystem().
hasSSE()
static bool G3D::System::hasSSE () inline static
Definition at line 196 of file System.h.
{
         return instance().m_hasSSE;
     }
References instance(), and m_hasSSE.
Referenced by describeSystem().
hasSSE2()
static bool G3D::System::hasSSE2 () inline static
Definition at line 200 of file System.h.
{
         return instance().m_hasSSE2;
     }
References instance(), and m_hasSSE2.
Referenced by describeSystem().
hasSSE3()
static bool G3D::System::hasSSE3 () inline static
Definition at line 204 of file System.h.
{
         return instance().m_hasSSE3;
     }
References instance(), and m_hasSSE3.
Referenced by describeSystem().
init()
void G3D::System::init () private
Definition at line 130 of file System.cpp.
                   {
     // NOTE: Cannot use most G3D data structures or utility functions
     // in here because they are not initialized.
     if (m_initialized) {
         return;
     } else {
         m_initialized = true;
     }
     getG3DVersion(m_version);
     m_machineEndian = checkEndian();
     m_hasCPUID = checkForCPUID();
     // Process the CPUID information
     if (m_hasCPUID) {
         // We read the standard CPUID level 0x00000000 which should
         // be available on every x86 processor.  This fills out
         // a string with the processor vendor tag.
         unsigned int eaxreg = 0, ebxreg = 0, ecxreg = 0, edxreg = 0;
         cpuid(CPUID_VENDOR_ID, eaxreg, ebxreg, ecxreg, edxreg);
         {
             char c[100];
             // Then we connect the single register values to the vendor string
             *((unsigned int*) c)         = ebxreg;
             *((unsigned int*) (c + 4))   = edxreg;
             *((unsigned int*) (c + 8))   = ecxreg;
             c[12] = '\0';
             m_cpuVendor = c;
         }
         switch (ebxreg) {
         case 0x756E6547:        // GenuineIntel
             m_cpuArch = "Intel Processor";
             break;
         case 0x68747541:        // AuthenticAMD
             m_cpuArch = "AMD Processor";
             break;
         default:
             m_cpuArch = "Unknown Processor Vendor";
             break;
         }
         unsigned int highestFunction = eaxreg;
         if (highestFunction >= CPUID_NUM_CORES) {
             cpuid(CPUID_NUM_CORES, eaxreg, ebxreg, ecxreg, edxreg);
             // Number of cores is in (eax>>26) + 1
             m_numCores = (eaxreg >> 26) + 1;
         }
         cpuid(CPUID_GET_HIGHEST_FUNCTION, m_highestCPUIDFunction, ebxreg, ecxreg, edxreg);
     }
     // Get the operating system name (also happens to read some other information)
 #    ifdef G3D_WINDOWS
         HRESULT r = OleInitialize(NULL);
         // Note that this overrides some of the values computed above
         bool success = RegistryUtil::readInt32
             ("HKEY_LOCAL_MACHINE\\HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0",
              "~MHz", m_cpuSpeed);
         HRESULT s = OleInitialize(NULL);
         SYSTEM_INFO systemInfo;
         GetSystemInfo(&systemInfo);
         const char* arch = NULL;
         switch (systemInfo.wProcessorArchitecture) {
         case PROCESSOR_ARCHITECTURE_INTEL:
             arch = "x86 Intel";
             break;
         case PROCESSOR_ARCHITECTURE_AMD64:
             arch = "x64 Intel/AMD";
             break;
         case PROCESSOR_ARCHITECTURE_ARM:
             arch = "ARM";
             break;
         default:
             arch = "Unknown";
             break;
         }
         m_numCores = systemInfo.dwNumberOfProcessors;
         uint64_t maxAddr = reinterpret_cast<uint64_t>(systemInfo.lpMaximumApplicationAddress);
         {
             char c[1024];
             sprintf(c, "%d - %s cores",
                     systemInfo.dwNumberOfProcessors,
                     arch);
             m_cpuArch = c;
         }
         OSVERSIONINFO osVersionInfo;
         osVersionInfo.dwOSVersionInfoSize = sizeof(OSVERSIONINFO);
         success = GetVersionEx(&osVersionInfo) != 0;
         if (success) {
             char c[1000];
             sprintf(c, "Windows %d.%d build %d Platform %d %s",
                 osVersionInfo.dwMajorVersion,
                 osVersionInfo.dwMinorVersion,
                 osVersionInfo.dwBuildNumber,
                 osVersionInfo.dwPlatformId,
                 osVersionInfo.szCSDVersion);
             m_operatingSystem = c;
         } else {
             m_operatingSystem = "Windows";
         }
 #    elif defined(G3D_LINUX) || defined(G3D_FREEBSD)
         {
             // Find the operating system using the 'uname' command
             FILE* f = popen("uname -a", "r");
             int len = 100;
             char* r = (char*)::malloc(len * sizeof(char));
             (void)fgets(r, len, f);
             // Remove trailing newline
             if (r[strlen(r) - 1] == '\n') {
                 r[strlen(r) - 1] = '\0';
             }
             fclose(f);
             f = NULL;
             m_operatingSystem = r;
             ::free(r);
         }
 #   elif defined(G3D_OSX)
         // Operating System:
         SInt32 macVersion;
         Gestalt(gestaltSystemVersion, &macVersion);
         int major = (macVersion >> 8) & 0xFF;
         int minor = (macVersion >> 4) & 0xF;
         int revision = macVersion & 0xF;
         {
             char c[1000];
             sprintf(c, "OS X %x.%x.%x", major, minor, revision);
             m_operatingSystem = c;
         }
         // Clock Cycle Timing Information:
         Gestalt('pclk', &m_OSXCPUSpeed);
         m_cpuSpeed = iRound((double)m_OSXCPUSpeed / (1024 * 1024));
         m_secondsPerNS = 1.0 / 1.0e9;
         // System Architecture:
     const NXArchInfo* pInfo = NXGetLocalArchInfo();
     if (pInfo) {
         m_cpuArch = pInfo->description;
         switch (pInfo->cputype) {
         case CPU_TYPE_POWERPC:
             switch(pInfo->cpusubtype){
         case CPU_SUBTYPE_POWERPC_750:
         case CPU_SUBTYPE_POWERPC_7400:
         case CPU_SUBTYPE_POWERPC_7450:
             m_cpuVendor = "Motorola";
             break;
         case CPU_SUBTYPE_POWERPC_970:
             m_cpuVendor = "IBM";
             break;
         }
         break;
             case CPU_TYPE_I386:
                 m_cpuVendor = "Intel";
                 break;
         }
     }
 #   endif
     initTime();
     getStandardProcessorExtensions();
     m_appDataDir = FilePath::parent(System::currentProgramFilename());
 }
References mpq::c, G3D::checkEndian(), G3D::checkForCPUID(), cpuid(), CPUID_GET_HIGHEST_FUNCTION, CPUID_NUM_CORES, CPUID_VENDOR_ID, currentProgramFilename(), f(), free(), G3D::getG3DVersion(), getStandardProcessorExtensions(), initTime(), G3D::iRound(), m_appDataDir, m_cpuArch, m_cpuSpeed, m_cpuVendor, m_hasCPUID, m_highestCPUIDFunction, m_initialized, m_machineEndian, m_numCores, m_operatingSystem, m_version, malloc(), NULL, G3D::FilePath::parent(), and sprintf().
Referenced by System().
initTime()
void G3D::System::initTime () private
Called from init()
Definition at line 901 of file System.cpp.
                       {
     #ifdef G3D_WINDOWS
         if (QueryPerformanceFrequency(&m_counterFrequency)) {
             QueryPerformanceCounter(&m_start);
         }
         struct _timeb t;
         _ftime(&t);
         m_realWorldGetTickTime0 = (RealTime)t.time - t.timezone * G3D::MINUTE + (t.dstflag ? G3D::HOUR : 0);
     #else
         gettimeofday(&m_start, NULL);
         // "sse" = "seconds since epoch".  The time
         // function returns the seconds since the epoch
         // GMT (perhaps more correctly called UTC).
         time_t gmt = ::time(NULL);
         // No call to free or delete is needed, but subsequent
         // calls to asctime, ctime, mktime, etc. might overwrite
         // local_time_vals.
         tm* localTimeVals = localtime(&gmt);
         time_t local = gmt;
         if (localTimeVals) {
             // tm_gmtoff is already corrected for daylight savings.
             local = local + localTimeVals->tm_gmtoff;
         }
         m_realWorldGetTickTime0 = local;
     #endif
 }
References G3D::HOUR, local, localtime(), m_realWorldGetTickTime0, m_start, G3D::MINUTE, NULL, and time().
Referenced by init().
instance()
System & G3D::System::instance () static private
The singleton instance.
Used instead of a global variable to ensure that the order of intialization is correct, which is critical because other globals may allocate memory using System::malloc.
Definition at line 98 of file System.cpp.
{
     static System thesystem;
     return thesystem;
 }
Referenced by cpuArchitecture(), cpuSpeedMHz(), cpuVendor(), endCycleCount(), findDataFile(), has3DNow(), hasCPUID(), hasMMX(), hasRDTSC(), hasSSE(), hasSSE2(), hasSSE3(), machineEndian(), numCores(), operatingSystem(), outOfMemoryCallback(), setAppDataDir(), setOutOfMemoryCallback(), time(), and version().
machineEndian()
static G3DEndian G3D::System::machineEndian () inline static
Returns the endianness of this machine.
Definition at line 223 of file System.h.
{
         return instance().m_machineEndian;
     }
References instance(), and m_machineEndian.
Referenced by G3D::ReliableConduit::receiveHeader(), G3D::BinaryInput::setEndian(), G3D::BinaryOutput::setEndian(), and G3D::LightweightConduit::waitingMessageType().
malloc()
void * G3D::System::malloc (size_t bytes) static
Uses pooled storage to optimize small allocations (1 byte to 5 kilobytes). Can be 10x to 100x faster than calling malloc or new.
The result must be freed with free.
Threadsafe on Win32.
See also
calloc realloc OutOfMemoryCallback free
Definition at line 1443 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     initMem();
     return bufferpool->malloc(bytes);
 #else
     return ::malloc(bytes);
 #endif
 }
References G3D::bufferpool, G3D::initMem(), and G3D::BufferPool::malloc().
Referenced by G3D::Queue< T >::_copy(), alignedMalloc(), G3D::MemoryManager::alloc(), G3D::bayer_bggr8_to_rgba32f(), G3D::bayer_gbrg8_to_rgba32f(), G3D::bayer_grbg8_to_rgba32f(), G3D::bayer_rggb8_to_rgba32f(), calloc(), G3D::BinaryOutput::compress(), G3D::ImageFormat::convert(), G3D::GImage::decodeBMP(), G3D::GImage::decodePNG(), G3D::GImage::encode(), G3D::GImage::encodeJPEG(), G3D::GImage::flipRGBAVertical(), G3D::GImage::flipRGBVertical(), init(), G3D::Matrix::Impl::operator new(), G3D::PrecomputedRandom::PrecomputedRandom(), G3D::Queue< T >::repackAndRealloc(), G3D::rgba32f_to_bayer_bggr8(), G3D::rgba32f_to_bayer_gbrg8(), G3D::rgba32f_to_bayer_grbg8(), G3D::rgba32f_to_bayer_rggb8(), G3D::Matrix::Impl::setSize(), and G3D::vformat().
mallocPerformance()
std::string G3D::System::mallocPerformance () static
Returns a string describing how well System::malloc is using its internal pooled storage. "heap" memory was slow to allocate; the other data sizes are comparatively fast.
Definition at line 1403 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     return bufferpool->performance();
 #else
     return "NO_BUFFERPOOL";
 #endif
 }
References G3D::bufferpool, and G3D::BufferPool::performance().
mallocStatus()
std::string G3D::System::mallocStatus () static
Returns a string describing the current usage of the buffer pools used for optimizing System::malloc.
Definition at line 1411 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     return bufferpool->status();
 #else
     return "NO_BUFFERPOOL";
 #endif
 }
References G3D::bufferpool, and G3D::BufferPool::status().
memcpy()
void G3D::System::memcpy (void * dst, const void * src, size_t numBytes) static
An implementation of memcpy that may be up to 2x as fast as the C library one on some processors. Guaranteed to have the same behavior as memcpy in all cases.
Definition at line 645 of file System.cpp.
{
 #if defined(G3D_WINDOWS) && defined(_M_IX86) && !defined(__MINGW32__) /* G3DFIX: Don't check if on 64-bit Windows platforms or using MinGW */
     // The overhead of our memcpy seems to only be worthwhile on large arrays
     if (((size_t)dst % 16 == 0) && ((size_t)src % 16 == 0) && (numBytes > 3400000)) {
         memcpyMMX(dst, src, numBytes);
     } else {
         ::memcpy(dst, src, numBytes);
     }
 #else
     ::memcpy(dst, src, numBytes);
 #endif
 }
Referenced by G3D::Array< T, MIN_ELEMENTS >::appendPOD(), G3D::BinaryInput::BinaryInput(), G3D::BinaryOutput::commit(), G3D::ImageFormat::convert(), G3D::Image1::copyArray(), G3D::Image1uint8::copyArray(), G3D::Image3::copyArray(), G3D::Image3uint8::copyArray(), G3D::Image4::copyArray(), G3D::Image4uint8::copyArray(), G3D::Array< T, MIN_ELEMENTS >::copyPOD(), G3D::GImage::flipHorizontal(), G3D::GImage::flipRGBAVertical(), G3D::GImage::flipRGBVertical(), G3D::GImage::flipVertical(), G3D::NetAddress::init(), G3D::TextInput::initFromString(), G3D::MeshAlg::Geometry::operator=(), G3D::Matrix::Impl::operator=(), G3D::BufferPool::realloc(), G3D::BinaryOutput::reserveBytesWhenOutOfMemory(), G3D::GImage::rotate90CW(), G3D::MD5Hash::rotateBytes(), G3D::Image1uint8::save(), G3D::Image3uint8::save(), G3D::Image4uint8::save(), G3D::Matrix::Impl::setRow(), G3D::TextInput::TextInput(), G3D::BinaryOutput::writeBytes(), G3D::BinaryOutput::writeString(), G3D::BinaryOutput::writeString32(), and G3D::BinaryOutput::writeStringEven().
memset()
void G3D::System::memset (void * dst, uint8 value, size_t numBytes) static
An implementation of memset that may be up to 2x as fast as the C library one on some processors. Guaranteed to have the same behavior as memset in all cases.
Michael Herf's fastest memset. n32 must be filled with the same character repeated.
Definition at line 697 of file System.cpp.
{
     alwaysAssertM(dst != NULL, "Cannot memset NULL address.");
 #if defined(G3D_WINDOWS) && defined(_M_IX86) && !defined(__MINGW32__) /* G3DFIX: Don't check if on 64-bit Windows platforms or using MinGW */
     if ((((size_t)dst % 16) == 0) && (numBytes >= 512*1024)) {
         uint32 v = value;
         v = v + (v << 8) + (v << 16) + (v << 24);
         G3D::memfill(dst, v, numBytes);
     } else {
         ::memset(dst, value, numBytes);
     }
 #else
     ::memset(dst, value, numBytes);
 #endif
 }
References alwaysAssertM, and NULL.
Referenced by calloc(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::GThread::GThread(), G3D::NetAddress::init(), G3D::NetAddress::NetAddress(), G3D::GImage::resize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize(), G3D::Matrix::Impl::setZero(), G3D::GThread::start(), and G3D::GThread::terminate().
numCores()
static int G3D::System::numCores () inline static
Returns the number of logical processor cores (i.e., the number of execution units for threads)
Definition at line 184 of file System.h.
{
         return instance().m_numCores;
     }
References instance(), and m_numCores.
Referenced by describeSystem(), and G3D::GThread::numCores().
operatingSystem()
static const std::string& G3D::System::operatingSystem () inline static
e.g., "Windows", "GNU/Linux"
Definition at line 228 of file System.h.
{
         return instance().m_operatingSystem;
     }
References instance(), and m_operatingSystem.
Referenced by describeSystem().
outOfMemoryCallback()
static OutOfMemoryCallback G3D::System::outOfMemoryCallback () inline static
When System::malloc fails to allocate memory because the system is out of memory, it invokes this handler (if it is not NULL). The argument to the callback is the amount of memory that malloc was trying to allocate when it ran out. If the callback returns true, System::malloc will attempt to allocate the memory again. If the callback returns false, then System::malloc will return NULL.
You can use outOfMemoryCallback to free data structures or to register the failure.
Definition at line 402 of file System.h.
{
         return instance().m_outOfMemoryCallback;
     }
References instance(), and m_outOfMemoryCallback.
Referenced by G3D::BufferPool::malloc().
realloc()
void * G3D::System::realloc (void * block, size_t bytes) static
Version of realloc that works with System::malloc.
Definition at line 1465 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     initMem();
     return bufferpool->realloc(block, bytes);
 #else
     return ::realloc(block, bytes);
 #endif
 }
References G3D::bufferpool, G3D::initMem(), and G3D::BufferPool::realloc().
Referenced by G3D::BinaryInput::loadIntoMemory(), and G3D::BinaryOutput::reallocBuffer().
resetMallocPerformanceCounters()
void G3D::System::resetMallocPerformanceCounters () static
Definition at line 1420 of file System.cpp.
{
 #ifndef NO_BUFFERPOOL
     bufferpool->totalMallocs         = 0;
     bufferpool->mallocsFromMedPool   = 0;
     bufferpool->mallocsFromSmallPool = 0;
     bufferpool->mallocsFromTinyPool  = 0;
 #endif
 }
References G3D::bufferpool, G3D::BufferPool::mallocsFromMedPool, G3D::BufferPool::mallocsFromSmallPool, G3D::BufferPool::mallocsFromTinyPool, and G3D::BufferPool::totalMallocs.
setAppDataDir()
void G3D::System::setAppDataDir (const std::string & path) static
Sets the path that the application is using as its data directory. Used by findDataDir as an initial search location. GApp sets this upon constrution.
Definition at line 511 of file System.cpp.
{
     instance().m_appDataDir = path;
     // Wipe the findDataFile cache
     lastFound.clear();
     directoryArray.clear();
 }
References G3D::Array< T, MIN_ELEMENTS >::clear(), G3D::directoryArray, instance(), G3D::lastFound, and m_appDataDir.
setEnv()
void G3D::System::setEnv (const std::string & name, const std::string & value) static
Set an environment variable for the current process
Definition at line 1568 of file System.cpp.
{
     std::string cmd = name + "=" + value;
 #   ifdef G3D_WINDOWS
         _putenv(cmd.c_str());
 #   else
         // Many linux implementations of putenv expect char*
         putenv(const_cast<char*>(cmd.c_str()));
 #   endif
 }
setOutOfMemoryCallback()
static void G3D::System::setOutOfMemoryCallback (OutOfMemoryCallback c) inline static
Definition at line 387 of file System.h.
{
         instance().m_outOfMemoryCallback = c;
     }
References mpq::c, instance(), and m_outOfMemoryCallback.
sleep()
void G3D::System::sleep (RealTime t) static
Causes the current thread to yield for the specified duration and consume almost no CPU. The sleep will be extremely precise; it uses System::time() to calibrate the exact yeild time.
Definition at line 791 of file System.cpp.
{
     // Overhead of calling this function, measured from a previous run.
     static const RealTime OVERHEAD = 0.00006f;
     RealTime now = time();
     RealTime wakeupTime = now + t - OVERHEAD;
     RealTime remainingTime = wakeupTime - now;
     RealTime sleepTime = 0;
     // On Windows, a "time slice" is measured in quanta of 3-5 ms (http://support.microsoft.com/kb/259025)
     // Sleep(0) yields the remainder of the time slice, which could be a long time.
     // A 1 ms minimum time experimentally kept the "Empty GApp" at nearly no CPU load at 100 fps,
     // yet nailed the frame timing perfectly.
     static RealTime minRealSleepTime = 3 * units::milliseconds();
     while (remainingTime > 0) {
         if (remainingTime > minRealSleepTime * 2.5) {
             // Safe to use Sleep with a time... sleep for half the remaining time
             sleepTime = max(remainingTime * 0.5, 0.0005);
         } else if (remainingTime > minRealSleepTime) {
             // Safe to use Sleep with a zero time;
             // causes the program to yield only
             // the current time slice, and then return.
             sleepTime = 0;
         } else {
             // Not safe to use Sleep; busy wait
             sleepTime = -1;
         }
         if (sleepTime >= 0) {
             #ifdef G3D_WINDOWS
                 // Translate to milliseconds
                 Sleep((int)(sleepTime * 1e3));
             #else
                 // Translate to microseconds
                 usleep((int)(sleepTime * 1e6));
             #endif
         }
         now = time();
         remainingTime = wakeupTime - now;
     }
 }
References G3D::max(), G3D::units::milliseconds(), and time().
Referenced by G3D::ReliableConduit::receiveIntoBuffer(), and G3D::ReliableConduit::ReliableConduit().
time()
RealTime G3D::System::time () static
The actual time (measured in seconds since Jan 1 1970 midnight).
Adjusted for local timezone and daylight savings time. This is as accurate and fast as getCycleCount().
Definition at line 936 of file System.cpp.
                       {
 #   ifdef G3D_WINDOWS
         LARGE_INTEGER now;
         QueryPerformanceCounter(&now);
         return ((RealTime)(now.QuadPart - instance().m_start.QuadPart) /
                 instance().m_counterFrequency.QuadPart) + instance().m_realWorldGetTickTime0;
 #   else
         // Linux resolution defaults to 100Hz.
         // There is no need to do a separate RDTSC call as gettimeofday
         // actually uses RDTSC when on systems that support it, otherwise
         // it uses the system clock.
         struct timeval now;
         gettimeofday(&now, NULL);
         return (now.tv_sec  - instance().m_start.tv_sec) +
             (now.tv_usec - instance().m_start.tv_usec) / 1e6
             + instance().m_realWorldGetTickTime0;
 #   endif
 }
References instance(), m_realWorldGetTickTime0, m_start, and NULL.
Referenced by G3D::Stopwatch::after(), G3D::GUniqueID::create(), currentDateString(), currentTimeString(), findDataFile(), G3D::FileSystem::getContents(), initTime(), G3D::ReliableConduit::ReliableConduit(), G3D::Stopwatch::reset(), sleep(), G3D::Stopwatch::tick(), and G3D::Stopwatch::tock().
version()
static const std::string& G3D::System::version () inline static
G3D Version string
Definition at line 321 of file System.h.
{
         return instance().m_version;
     }
References instance(), and m_version.
Referenced by describeSystem().
Member Data Documentation
m_appDataDir
std::string G3D::System::m_appDataDir private
this holds the data directory set by the application (currently GApp) for use by findDataFile
Definition at line 107 of file System.h.
Referenced by findDataFile(), init(), and setAppDataDir().
m_cpuArch
std::string G3D::System::m_cpuArch private
Definition at line 110 of file System.h.
Referenced by cpuArchitecture(), and init().
m_cpuSpeed
int G3D::System::m_cpuSpeed private
Definition at line 92 of file System.h.
Referenced by cpuSpeedMHz(), and init().
m_cpuVendor
std::string G3D::System::m_cpuVendor private
Definition at line 102 of file System.h.
Referenced by cpuVendor(), and init().
m_has3DNOW
bool G3D::System::m_has3DNOW private
Definition at line 99 of file System.h.
Referenced by getStandardProcessorExtensions(), and has3DNow().
m_has3DNOW2
bool G3D::System::m_has3DNOW2 private
Definition at line 100 of file System.h.
Referenced by getStandardProcessorExtensions().
m_hasAMDMMX
bool G3D::System::m_hasAMDMMX private
Definition at line 101 of file System.h.
Referenced by getStandardProcessorExtensions().
m_hasCPUID
bool G3D::System::m_hasCPUID private
Definition at line 93 of file System.h.
Referenced by getStandardProcessorExtensions(), hasCPUID(), and init().
m_hasMMX
bool G3D::System::m_hasMMX private
Definition at line 95 of file System.h.
Referenced by getStandardProcessorExtensions(), and hasMMX().
m_hasRDTSC
bool G3D::System::m_hasRDTSC private
Definition at line 94 of file System.h.
Referenced by getStandardProcessorExtensions(), and hasRDTSC().
m_hasSSE
bool G3D::System::m_hasSSE private
Definition at line 96 of file System.h.
Referenced by getStandardProcessorExtensions(), and hasSSE().
m_hasSSE2
bool G3D::System::m_hasSSE2 private
Definition at line 97 of file System.h.
Referenced by getStandardProcessorExtensions(), and hasSSE2().
m_hasSSE3
bool G3D::System::m_hasSSE3 private
Definition at line 98 of file System.h.
Referenced by getStandardProcessorExtensions(), and hasSSE3().
m_highestCPUIDFunction
uint32 G3D::System::m_highestCPUIDFunction private
Definition at line 133 of file System.h.
Referenced by getStandardProcessorExtensions(), and init().
m_initialized
bool G3D::System::m_initialized private
Definition at line 91 of file System.h.
Referenced by init().
m_machineEndian
G3DEndian G3D::System::m_machineEndian private
Definition at line 109 of file System.h.
Referenced by init(), and machineEndian().
m_numCores
int G3D::System::m_numCores private
Definition at line 103 of file System.h.
Referenced by init(), and numCores().
m_operatingSystem
std::string G3D::System::m_operatingSystem private
Definition at line 111 of file System.h.
Referenced by init(), and operatingSystem().
m_outOfMemoryCallback
OutOfMemoryCallback G3D::System::m_outOfMemoryCallback private
Definition at line 122 of file System.h.
Referenced by outOfMemoryCallback(), and setOutOfMemoryCallback().
m_realWorldGetTickTime0
RealTime G3D::System::m_realWorldGetTickTime0 private
The Real-World time of System::getTick() time 0. Set by initTime
Definition at line 131 of file System.h.
Referenced by initTime(), and time().
m_start
struct timeval G3D::System::m_start private
Definition at line 111 of file System.h.
Referenced by initTime(), and time().
m_version
std::string G3D::System::m_version private
Definition at line 121 of file System.h.
Referenced by init(), and version().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/System.h
deps/g3dlite/source/System.cpp