Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tsd_tls.h File Reference
tsd_tls.h File Reference
Macros
#define JEMALLOC_INTERNAL_TSD_TLS_H
#define JEMALLOC_TSD_TYPE_ATTR(type) __thread type JEMALLOC_TLS_MODEL
Functions
JEMALLOC_TSD_TYPE_ATTR (tsd_t) tsd_tls
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_get (bool init)
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t *val)
Variables
pthread_key_t tsd_tsd
bool tsd_booted
Macro Definition Documentation
JEMALLOC_INTERNAL_TSD_TLS_H
#define JEMALLOC_INTERNAL_TSD_TLS_H
Definition at line 4 of file tsd_tls.h.
JEMALLOC_TSD_TYPE_ATTR
#define JEMALLOC_TSD_TYPE_ATTR (type) __thread type JEMALLOC_TLS_MODEL
Definition at line 6 of file tsd_tls.h.
Function Documentation
JEMALLOC_TSD_TYPE_ATTR()
JEMALLOC_TSD_TYPE_ATTR (tsd_t)
tsd_boot()
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
Definition at line 28 of file tsd_tls.h.
                {
     return tsd_boot0();
 }
References tsd_boot0().
tsd_boot0()
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
Definition at line 14 of file tsd_tls.h.
                 {
     if (pthread_key_create(&tsd_tsd, &tsd_cleanup) != 0) {
         return true;
     }
     tsd_booted = true;
     return false;
 }
References tsd_booted, tsd_cleanup, and tsd_tsd.
Referenced by tsd_boot().
tsd_boot1()
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
Definition at line 23 of file tsd_tls.h.
                 {
     /* Do nothing. */
 }
tsd_booted_get()
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
Definition at line 33 of file tsd_tls.h.
                      {
     return tsd_booted;
 }
References tsd_booted.
tsd_get()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_get (bool init)
Definition at line 44 of file tsd_tls.h.
                    {
     return &tsd_tls;
 }
References tsd_tls.
tsd_get_allocates()
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
Definition at line 38 of file tsd_tls.h.
{
     return false;
 }
tsd_set()
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t * val)
Definition at line 49 of file tsd_tls.h.
                     {
     assert(tsd_booted);
     if (likely(&tsd_tls != val)) {
         tsd_tls = (*val);
     }
     if (pthread_setspecific(tsd_tsd, (void *)(&tsd_tls)) != 0) {
         malloc_write("<jemalloc>: Error setting tsd.\n");
         if (opt_abort) {
             abort();
         }
     }
 }
References assert(), likely, malloc_write, opt_abort, tsd_booted, tsd_tls, and tsd_tsd.
Variable Documentation
tsd_booted
bool tsd_booted extern
Definition at line 53 of file tsd.c.
Referenced by tsd_boot0(), tsd_booted_get(), and tsd_set().
tsd_tsd
pthread_key_t tsd_tsd extern
Definition at line 43 of file tsd.c.
Referenced by tsd_boot0(), and tsd_set().