Azerotcore-wotlk: G3D::UprightSpline Class Reference
G3D::UprightSpline Class Reference
Shortest-path linear velocity spline for camera positions. Always keeps the camera from rolling.
#include <UprightFrame.h>
Public Member Functions
UprightSpline ()
UprightSpline (const Any &any)
virtual Any toAny (const std::string &myName) const override
Any toAny () const
UprightSpline & operator= (const Any &any)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Public Member Functions inherited from G3D::Spline< UprightFrame >
Spline ()
Spline (const Any &any)
void append (float t, const UprightFrame &c)
void append (const UprightFrame &c)
void clear ()
int size () const
void getControl (int i, float &t, UprightFrame &c) const
UprightFrame evaluate (float s) const
Public Member Functions inherited from G3D::SplineBase
SplineBase ()
virtual ~SplineBase ()
float getFinalInterval () const
float duration () const
void computeIndex (float s, int &i, float &u) const
Protected Member Functions
virtual void ensureShortestPath (UprightFrame *A, int N) const
Protected Member Functions inherited from G3D::Spline< UprightFrame >
void getControls (int i, float *T, UprightFrame *A, int N) const
virtual void correct (UprightFrame &A) const
virtual void init (AnyTableReader &propertyTable)
Protected Member Functions inherited from G3D::SplineBase
void computeIndexInBounds (float s, int &i, float &u) const
Additional Inherited Members
Static Public Member Functions inherited from G3D::SplineBase
static Matrix4 computeBasis ()
Public Attributes inherited from G3D::Spline< UprightFrame >
Array< UprightFrame > control
Public Attributes inherited from G3D::SplineBase
Array< float > time
SplineExtrapolationMode extrapolationMode
float finalInterval
SplineInterpolationMode interpolationMode
Protected Attributes inherited from G3D::Spline< UprightFrame >
UprightFrame zero
Detailed Description
Shortest-path linear velocity spline for camera positions. Always keeps the camera from rolling.
See also
G3D::UprightSplineManipulator, G3D::UprightFrame
Definition at line 82 of file UprightFrame.h.
Constructor & Destructor Documentation
UprightSpline() [1/2]
G3D::UprightSpline::UprightSpline ()
Definition at line 117 of file UprightFrame.cpp.
                              : Spline<UprightFrame>() {
 }
Referenced by operator=().
UprightSpline() [2/2]
G3D::UprightSpline::UprightSpline (const Any & any) explicit
Constructs an UprightSpline from an Any object.
The Any format for UprightSpline is:
controls = (UprightFrame, ...), times = (##, ...), cyclic = bool
The controls and times arrays must have the same length.
Definition at line 121 of file UprightFrame.cpp.
{
     any.verifyName("UprightSpline");
     any.verifyType(Any::TABLE);
     extrapolationMode = any["extrapolationMode"];
     const Any& controlsAny = any["control"];
     controlsAny.verifyType(Any::ARRAY);
     control.resize(controlsAny.length());
     for (int controlIndex = 0; controlIndex < control.length(); ++controlIndex) {
         control[controlIndex] = controlsAny[controlIndex];
     }
     const Any& timesAny = any["time"];
     timesAny.verifyType(Any::ARRAY);
     time.resize(timesAny.length());
     for (int timeIndex = 0; timeIndex < time.length(); ++timeIndex) {
         time[timeIndex] = timesAny[timeIndex];
     }
 }
References G3D::any(), G3D::Any::ARRAY, G3D::Spline< UprightFrame >::control, G3D::SplineBase::extrapolationMode, G3D::Any::length(), G3D::Array< T, MIN_ELEMENTS >::length(), G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Any::TABLE, G3D::SplineBase::time, and G3D::Any::verifyType().
Member Function Documentation
deserialize()
void G3D::UprightSpline::deserialize (class BinaryInput & b)
Definition at line 191 of file UprightFrame.cpp.
{
     extrapolationMode = SplineExtrapolationMode(b.readInt32());
     control.resize(b.readInt32());
     for (int i = 0; i < control.size(); ++i) {
         control[i].deserialize(b);
     }
     if (b.hasMore()) {
         time.resize(b.readInt32());
         for (int i = 0; i < time.size(); ++i) {
             time[i] = b.readFloat32();
         }
         debugAssert(time.size() == control.size());
     } else {
         // Import legacy path
         time.resize(control.size());
         for (int i = 0; i < time.size(); ++i) {
             time[i] = (float)i;
         }
     }
 }
References b, G3D::Spline< UprightFrame >::control, debugAssert, G3D::SplineBase::extrapolationMode, G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::SplineBase::time.
ensureShortestPath()
virtual void G3D::UprightSpline::ensureShortestPath (UprightFrame * A, int N) const inline protected virtual
Mutates the array of N control points that begins at A. It is useful to override this method by one that wraps the values if they are angles or quaternions for which "shortest path" interpolation is significant.
Reimplemented from G3D::Spline< UprightFrame >.
Definition at line 85 of file UprightFrame.h.
{
         UprightFrame::unwrapYaw(A, N);
     }
References G3D::UprightFrame::unwrapYaw().
operator=()
UprightSpline & G3D::UprightSpline::operator= (const Any & any)
Definition at line 171 of file UprightFrame.cpp.
{
     *this = UprightSpline(any);
     return *this;
 }
References G3D::any(), and UprightSpline().
serialize()
void G3D::UprightSpline::serialize (class BinaryOutput & b) const
Definition at line 177 of file UprightFrame.cpp.
{
     b.writeInt32(extrapolationMode);
     b.writeInt32(control.size());
     for (int i = 0; i < control.size(); ++i) {
         control[i].serialize(b);
     }
     b.writeInt32(time.size());
     for (int i = 0; i < time.size(); ++i) {
         b.writeFloat32(time[i]);
     }
 }
References b, G3D::Spline< UprightFrame >::control, G3D::SplineBase::extrapolationMode, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::SplineBase::time.
toAny() [1/2]
Any G3D::UprightSpline::toAny () const
Definition at line 166 of file UprightFrame.cpp.
{
     return toAny("UprightSpline");
 }
toAny() [2/2]
Any G3D::UprightSpline::toAny (const std::string & myName) const override virtual
Note that invoking classes can call setName on the returned value instead of passing a name in.
Reimplemented from G3D::Spline< UprightFrame >.
Definition at line 145 of file UprightFrame.cpp.
{
     Any any(Any::TABLE, myName);
     any["extrapolationMode"] = extrapolationMode;
     Any controlsAny(Any::ARRAY);
     for (int controlIndex = 0; controlIndex < control.length(); ++controlIndex) {
         controlsAny.append(control[controlIndex]);
     }
     any["control"] = controlsAny;
     Any timesAny(Any::ARRAY);
     for (int timeIndex = 0; timeIndex < time.length(); ++timeIndex) {
         timesAny.append(Any(time[timeIndex]));
     }
     any["time"] = timesAny;
     return any;
 }
References G3D::any(), G3D::Any::append(), G3D::Any::ARRAY, G3D::Spline< UprightFrame >::control, G3D::SplineBase::extrapolationMode, G3D::Array< T, MIN_ELEMENTS >::length(), G3D::Any::TABLE, and G3D::SplineBase::time.
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/UprightFrame.h
deps/g3dlite/source/UprightFrame.cpp