Azerotcore-wotlk: npc_hourglass_of_eternity::npc_hourglass_of_eternityAI Struct Reference
npc_hourglass_of_eternity::npc_hourglass_of_eternityAI Struct Reference
Public Member Functions
npc_hourglass_of_eternityAI (Creature *c)
bool IsFuture ()
void InitializeAI () override
Player * getSummoner ()
Creature * getFuture ()
uint32 randEntry ()
void UpdateAI (uint32 diff) override
void randomWhisper ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid summonerGUID
ObjectGuid futureGUID
EventMap events
uint8 count [3]
uint8 phase
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 310 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
npc_hourglass_of_eternityAI()
npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::npc_hourglass_of_eternityAI (Creature * c) inline
Definition at line 312 of file zone_dragonblight.cpp.
 : ScriptedAI(c) {}
Member Function Documentation
getFuture()
Creature* npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::getFuture () inline
Definition at line 348 of file zone_dragonblight.cpp.
 { return ObjectAccessor::GetCreature(*me, futureGUID); }
References futureGUID, ObjectAccessor::GetCreature(), and ScriptedAI::me.
Referenced by randomWhisper(), and UpdateAI().
getSummoner()
Player* npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::getSummoner () inline
Definition at line 347 of file zone_dragonblight.cpp.
 { return ObjectAccessor::GetPlayer(*me, summonerGUID); }
References ObjectAccessor::GetPlayer(), ScriptedAI::me, and summonerGUID.
Referenced by randomWhisper(), and UpdateAI().
InitializeAI()
void npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 321 of file zone_dragonblight.cpp.
         {
             if (me->ToTempSummon())
                 if (Unit* summoner = me->ToTempSummon()->GetSummonerUnit())
                 {
                     summonerGUID = summoner->GetGUID();
                     float x, y, z;
                     me->GetNearPoint(summoner, x, y, z, me->GetCombatReach(), 0.0f, rand_norm() * 2 * M_PI);
                     if (Creature* cr = summoner->SummonCreature((IsFuture() ? NPC_FUTURE_YOU : NPC_PAST_YOU), x, y, z, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 210000))
                     {
                         futureGUID = cr->GetGUID();
                         summoner->CastSpell(cr, SPELL_CLONE_CASTER, true);
                         cr->SetFaction(summoner->GetFaction());
                         cr->SetReactState(REACT_AGGRESSIVE);
                     }
                 }
             count[0] = 2;
             count[1] = 2;
             count[2] = 3;
             phase = 0;
             events.Reset();
             events.ScheduleEvent(EVENT_START_EVENT, 4000);
         }
References count, EVENT_START_EVENT, futureGUID, Unit::GetCombatReach(), WorldObject::GetNearPoint(), TempSummon::GetSummonerUnit(), IsFuture(), M_PI, ScriptedAI::me, NPC_FUTURE_YOU, NPC_PAST_YOU, rand_norm(), REACT_AGGRESSIVE, SPELL_CLONE_CASTER, WorldObject::SummonCreature(), summonerGUID, TEMPSUMMON_TIMED_DESPAWN, Unit::ToTempSummon(), G3D::x, G3D::y, and G3D::z.
IsFuture()
bool npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::IsFuture () inline
Definition at line 320 of file zone_dragonblight.cpp.
 { return me->GetEntry() == NPC_FUTURE_HOURGLASS; }
References Object::GetEntry(), ScriptedAI::me, and NPC_FUTURE_HOURGLASS.
Referenced by InitializeAI(), randomWhisper(), and UpdateAI().
randEntry()
uint32 npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randEntry () inline
Definition at line 350 of file zone_dragonblight.cpp.
         {
             return NPC_INFINITE_ASSAILANT + urand(0, 2);
         }
References NPC_INFINITE_ASSAILANT, and urand().
Referenced by UpdateAI().
randomWhisper()
void npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randomWhisper () inline
Definition at line 433 of file zone_dragonblight.cpp.
         {
             std::string text = "";
             switch(urand(0, IsFuture() ? 7 : 5))
             {
                 case 0:
                     text = IsFuture() ? "What? Am I here alone. We both have a stake at this, you know!" : "This equipment looks cool and all, but couldn't we have done a little better? Are you even raiding?";
                     break;
                 case 1:
                     text = IsFuture() ? "No matter what, you can't die, because would mean that I would cease to exist, right? But, I was here before when I was you. I'm so confused!" : "Chromie said that if I don't do this just right, I might wink out of existence. If I go, then you go!";
                     break;
                 case 2:
                     text = IsFuture() ? "Sorry, but Chromie said that I couldn't reveal anything about your future to you. She said that if I did, I would cease to exist." : "I just want you to know that if we get through this alive, I'm making sure that we turn out better than you. No offense.";
                     break;
                 case 3:
                     text = IsFuture() ? "Look at you fight; no wonder I turned to drinking." : "Looks like I'm an underachiever.";
                     break;
                 case 4:
                     text = IsFuture() ? "Wow, I'd forgotten how inexperienced I used to be." : "Wait a minute! If you're here, then that means that in the not-so-distant future I'm going to be you helping me? Are we stuck in a time loop?!";
                     break;
                 case 5:
                     text = IsFuture() ? "I can't believe that I used to wear that." : "I think I'm going to turn to drinking after this.";
                     break;
                 case 6:
                     text = "Listen. I'm not supposed to tell you this, but there's going to be this party that you're invited to. Whatever you do, DO NOT DRINK THE PUNCH!";
                     break;
                 case 7:
                     text = "Wish I could remember how many of the Infinite Dragonflight were going to try to stop you. This fight was so long ago.";
                     break;
             }
             if (Creature* cr = getFuture())
                 cr->Whisper(text, LANG_UNIVERSAL, getSummoner());
         }
References getFuture(), getSummoner(), IsFuture(), LANG_UNIVERSAL, and urand().
Referenced by UpdateAI().
UpdateAI()
void npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 355 of file zone_dragonblight.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_START_EVENT:
                     if (Creature* cr = getFuture())
                         cr->Whisper(IsFuture() ? "Hey there, $N, don't be alarmed. It's me... you... from the future. I'm here to help." : "Whoa! You're me, but from the future! Hey, my equipment got an upgrade! Cool!", LANG_UNIVERSAL, getSummoner());
                     events.ScheduleEvent(EVENT_FIGHT_1, 7000);
                     break;
                 case EVENT_FIGHT_1:
                     if (Creature* cr = getFuture())
                         cr->Whisper(IsFuture() ? "Heads up... here they come. I'll help as much as I can. Let's just keep them off the hourglass!" : "Here come the Infinites! I've got to keep the hourglass safe. Can you help?", LANG_UNIVERSAL, getSummoner());
                     events.ScheduleEvent(EVENT_FIGHT_2, 6000);
                     break;
                 case EVENT_FIGHT_2:
                     {
                         if (phase)
                             randomWhisper();
                         Creature* cr = nullptr;
                         float x, y, z;
                         if (phase < 3)
{
                             for (uint8 i = 0; i < count[phase]; ++i)
{
                                 me->GetNearPoint(me, x, y, z, me->GetCombatReach(), 10.0f, rand_norm() * 2 * M_PI);
                                 if ((cr = me->SummonCreature(randEntry(), x, y, z + 2.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
{
                                     cr->CastSpell(cr, SPELL_TELEPORT_EFFECT, true);
                                     cr->AI()->AttackStart(me);
                                     cr->AddThreat(me, 100.0f);
                                 }
                             }
                         }
                         else if (phase == 3)
{
                             me->GetNearPoint(me, x, y, z, me->GetCombatReach(), 20.0f, rand_norm() * 2 * M_PI);
                             if ((cr = me->SummonCreature(NPC_INFINITE_TIMERENDER, x, y, z, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
{
                                 cr->CastSpell(cr, SPELL_TELEPORT_EFFECT, true);
                                 cr->AI()->AttackStart(me);
                             }
                             events.ScheduleEvent(EVENT_CHECK_FINISH, 20000);
                             return;
                         }
                         ++phase;
                         events.ScheduleEvent(EVENT_FIGHT_2, 35000);
                         break;
                     }
                 case EVENT_CHECK_FINISH:
                     {
                         if (me->FindNearestCreature(NPC_INFINITE_TIMERENDER, 50.0f))
{
                             events.RepeatEvent(5000);
                             return;
                         }
                         if (Player* player = getSummoner())
                             player->GroupEventHappens(IsFuture() ? QUEST_MYSTERY_OF_THE_INFINITE : QUEST_MYSTERY_OF_THE_INFINITE_REDUX, me);
                         me->Whisper(IsFuture() ? "Look, $N, the hourglass has revealed Nozdormu!" : "What the heck? Nozdormu is up there!", LANG_UNIVERSAL, getSummoner());
                         events.ScheduleEvent(EVENT_FINISH_EVENT, 6000);
                         break;
                     }
                 case EVENT_FINISH_EVENT:
                     {
                         me->Whisper(IsFuture() ? "Farewell, $N. Keep us alive and get some better equipment!" : "I feel like I'm being pulled away through time. Thanks for the help....", LANG_UNIVERSAL, getSummoner());
                         me->DespawnOrUnsummon(500);
                         if (getFuture())
                             getFuture()->DespawnOrUnsummon(500);
                         break;
                     }
             }
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), count, Creature::DespawnOrUnsummon(), diff(), EVENT_CHECK_FINISH, EVENT_FIGHT_1, EVENT_FIGHT_2, EVENT_FINISH_EVENT, EVENT_START_EVENT, WorldObject::FindNearestCreature(), Unit::GetCombatReach(), getFuture(), WorldObject::GetNearPoint(), getSummoner(), IsFuture(), LANG_UNIVERSAL, M_PI, ScriptedAI::me, NPC_INFINITE_TIMERENDER, phase, QUEST_MYSTERY_OF_THE_INFINITE, QUEST_MYSTERY_OF_THE_INFINITE_REDUX, rand_norm(), randEntry(), randomWhisper(), SPELL_TELEPORT_EFFECT, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, Unit::Whisper(), G3D::x, G3D::y, and G3D::z.
Member Data Documentation
count
uint8 npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::count[3]
Definition at line 317 of file zone_dragonblight.cpp.
Referenced by InitializeAI(), and UpdateAI().
events
EventMap npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::events
Definition at line 316 of file zone_dragonblight.cpp.
futureGUID
ObjectGuid npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::futureGUID
Definition at line 315 of file zone_dragonblight.cpp.
Referenced by getFuture(), and InitializeAI().
phase
uint8 npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::phase
Definition at line 318 of file zone_dragonblight.cpp.
Referenced by UpdateAI().
summonerGUID
ObjectGuid npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::summonerGUID
Definition at line 314 of file zone_dragonblight.cpp.
Referenced by getSummoner(), and InitializeAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp