Azerotcore-wotlk: G3D::MeshAlg::Vertex Class Reference
G3D::MeshAlg::Vertex Class Reference
#include <MeshAlg.h>
Public Member Functions
Vertex ()
bool inEdge (int e) const
bool inFace (int f) const
Public Attributes
SmallArray< int, 6 > edgeIndex
SmallArray< int, 6 > faceIndex
Detailed Description
Adjacency information for a vertex. Does not contain the vertex position or normal, which are stored in the MeshAlg::Geometry object. Vertexs must be stored in an array parallel to (indexed in the same way as) MeshAlg::Geometry::vertexArray.
Definition at line 57 of file MeshAlg.h.
Constructor & Destructor Documentation
Vertex()
G3D::MeshAlg::Vertex::Vertex () inline
Definition at line 59 of file MeshAlg.h.
 {}
Member Function Documentation
inEdge()
bool G3D::MeshAlg::Vertex::inEdge (int e) const inline
Returns true if e or ~e is in the edgeIndex list.
Definition at line 75 of file MeshAlg.h.
{
             return edgeIndex.contains(~e) || edgeIndex.contains(e);
         }
References G3D::SmallArray< T, N >::contains(), and edgeIndex.
inFace()
bool G3D::MeshAlg::Vertex::inFace (int f) const inline
Definition at line 85 of file MeshAlg.h.
{
             debugAssert(f >= 0);
             return faceIndex.contains(f);
         }
References G3D::SmallArray< T, N >::contains(), debugAssert, f(), and faceIndex.
Member Data Documentation
edgeIndex
SmallArray<int, 6> G3D::MeshAlg::Vertex::edgeIndex
Array of edges adjacent to this vertex. Let e = edgeIndex[i].
edge[(e >= 0) ? e : ~e].vertexIndex[0] == this vertex index.
Edges may be listed multiple times if they are degenerate.
Definition at line 70 of file MeshAlg.h.
Referenced by G3D::MeshAlg::debugCheckConsistency(), inEdge(), and G3D::MeshAlg::weldBoundaryEdges().
faceIndex
SmallArray<int, 6> G3D::MeshAlg::Vertex::faceIndex
Array of faces containing this vertex. Faces may be listed multiple times if they are degenerate.
Definition at line 83 of file MeshAlg.h.
Referenced by G3D::MeshAlg::debugCheckConsistency(), and inFace().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/MeshAlg.h