Azerotcore-wotlk: deps/mysqllite/mysys/mf_soundex.c File Reference
mf_soundex.c File Reference
#include "mysys_priv.h"
#include <m_ctype.h>
#include "my_static.h"
Functions
static char get_scode (CHARSET_INFO *cs, char **ptr, pbool remove_garbage)
void soundex (CHARSET_INFO *cs, register char *out_pntr, char *in_pntr, pbool remove_garbage)
Function Documentation
get_scode()
static char get_scode (CHARSET_INFO * cs, char ** ptr, pbool remove_garbage) static
Definition at line 88 of file mf_soundex.c.
 {
   uchar ch;
   if (remove_garbage)
   {
     while (**ptr && !my_isalpha(cs,**ptr))
       (*ptr)++;
   }
   ch=my_toupper(cs,**ptr);
   if (ch < 'A' || ch > 'Z')
   {
     if (my_isalpha(cs,ch))      /* If extended alfa (country spec) */
       return '0';           /* threat as vokal */
     return 0;               /* Can't map */
   }
   return(soundex_map[ch-'A']);
 } /* get_scode */
References my_isalpha, my_toupper, ptr(), and soundex_map.
Referenced by soundex().
soundex()
void soundex (CHARSET_INFO * cs, register char * out_pntr, char * in_pntr, pbool remove_garbage)
Definition at line 45 of file mf_soundex.c.
 {
   char ch,last_ch;
   reg3 char * end;
   register uchar *map=cs->to_upper;
   if (remove_garbage)
   {
     while (*in_pntr && !my_isalpha(cs,*in_pntr)) /* Skip pre-space */
       in_pntr++;
   }
   *out_pntr++ = map[(uchar)*in_pntr];   /* Copy first letter         */
   last_ch = get_scode(cs,&in_pntr,0);   /* code of the first letter  */
                     /* for the first 'double-letter  */
                     /* check.            */
   end=out_pntr+3;           /* Loop on input letters until   */
                     /* end of input (null) or output */
                     /* letter code count = 3     */
   in_pntr++;
   while (out_pntr < end && (ch = get_scode(cs,&in_pntr,remove_garbage)) != 0)
   {
     in_pntr++;
     if ((ch != '0') && (ch != last_ch)) /* if not skipped or double */
     {
       *out_pntr++ = ch;         /* letter, copy to output */
     }                   /* for next double-letter check */
     last_ch = ch;           /* save code of last input letter */
   }
   while (out_pntr < end)
     *out_pntr++ = '0';
   *out_pntr=0;              /* end string */
   return;
 } /* soundex */
References get_scode(), my_isalpha, reg3, and charset_info_st::to_upper.