Azerotcore-wotlk: npc_elder_clearwater Class Reference
npc_elder_clearwater Class Reference
Classes
struct npc_elder_clearwaterAI
Public Member Functions
npc_elder_clearwater ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnQuestReward (Player *player, Creature *creature, Quest const *quest, uint32) override
CreatureAI * GetAI (Creature *pCreature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 75 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_elder_clearwater()
npc_elder_clearwater::npc_elder_clearwater () inline
Definition at line 78 of file npcs_special.cpp.
 : CreatureScript("npc_elder_clearwater") { }
Member Function Documentation
GetAI()
CreatureAI* npc_elder_clearwater::GetAI (Creature * pCreature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 202 of file npcs_special.cpp.
     {
         return new npc_elder_clearwaterAI (pCreature);
     }
OnGossipHello()
bool npc_elder_clearwater::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 152 of file npcs_special.cpp.
     {
         QuestRelationBounds pObjectQR;
         QuestRelationBounds pObjectQIR;
         // pets also can have quests
         if (creature)
         {
             pObjectQR  = sObjectMgr->GetCreatureQuestRelationBounds(creature->GetEntry());
             pObjectQIR = sObjectMgr->GetCreatureQuestInvolvedRelationBounds(creature->GetEntry());
         }
         else
             return true;
         QuestMenu& qm = player->PlayerTalkClass->GetQuestMenu();
         qm.ClearMenu();
         for (QuestRelations::const_iterator i = pObjectQIR.first; i != pObjectQIR.second; ++i)
         {
             uint32 quest_id = i->second;
             Quest const* quest = sObjectMgr->GetQuestTemplate(quest_id);
             if (!quest)
                 continue;
             if (!creature->AI()->GetData(DATA_DERBY_FINISHED))
             {
                 if (quest_id == QUEST_FISHING_DERBY)
                     player->PlayerTalkClass->SendQuestGiverRequestItems(quest, creature->GetGUID(), player->CanRewardQuest(quest, false), true);
             }
             else
             {
                 if (quest_id != QUEST_FISHING_DERBY)
                     player->PlayerTalkClass->SendQuestGiverRequestItems(quest, creature->GetGUID(), player->CanRewardQuest(quest, false), true);
             }
         }
         return true;
     }
References Creature::AI(), Player::CanRewardQuest(), QuestMenu::ClearMenu(), DATA_DERBY_FINISHED, UnitAI::GetData(), Object::GetEntry(), Object::GetGUID(), PlayerMenu::GetQuestMenu(), Player::PlayerTalkClass, QUEST_FISHING_DERBY, PlayerMenu::SendQuestGiverRequestItems(), and sObjectMgr.
OnQuestReward()
bool npc_elder_clearwater::OnQuestReward (Player * player, Creature * creature, Quest const * quest, uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 191 of file npcs_special.cpp.
     {
         if (!creature->AI()->GetData(DATA_DERBY_FINISHED) && quest->GetQuestId() == QUEST_FISHING_DERBY)
         {
             creature->AI()->DoAction(DATA_DERBY_FINISHED);
             sCreatureTextMgr->SendChat(creature, CLEARWATER_SAY_WINNER, player, CHAT_MSG_MONSTER_YELL, LANG_UNIVERSAL, TEXT_RANGE_MAP);
         }
         return true;
     }
References Creature::AI(), CHAT_MSG_MONSTER_YELL, CLEARWATER_SAY_WINNER, DATA_DERBY_FINISHED, UnitAI::DoAction(), UnitAI::GetData(), Quest::GetQuestId(), LANG_UNIVERSAL, QUEST_FISHING_DERBY, sCreatureTextMgr, and TEXT_RANGE_MAP.
The documentation for this class was generated from the following file:
src/server/scripts/World/npcs_special.cpp