Azerotcore-wotlk: G3D::WeakCache< Key, ValueRef > Class Template Reference
G3D::WeakCache< Key, ValueRef > Class Template Reference
#include <WeakCache.h>
Public Member Functions
ValueRef operator[] (const Key &k)
void getValues (Array< ValueRef > &values)
void clear ()
void set (const Key &k, ValueRef v)
void remove (const Key &k)
Private Types
typedef weak_ptr< typename ValueRef::element_type > ValueWeakRef
Private Attributes
Table< Key, ValueWeakRef > table
Detailed Description
template<class Key, class ValueRef>
class G3D::WeakCache< Key, ValueRef >
A cache that does not prevent its members from being garbage collected. Useful to avoid loading or computing an expression twice. Useful for memoization and dynamic programming.
Maintains a table of weak pointers. Weak pointers do not prevent an object from being garbage collected. If the object is garbage collected, the cache removes its reference.
There are no "contains" or "iterate" methods because elements can be flushed from the cache at any time if they are garbage collected.
Example:
   WeakCache<std::string, shared_ptr<Texture>> textureCache;
   shared_ptr<Texture> loadTexture(std::string s) {
       shared_ptr<Texture> t = textureCache[s];
       if (t.isNull()) {
           t = Texture::fromFile(s);
           textureCache.set(s, t);
       }
       return t;
   }
Definition at line 51 of file WeakCache.h.
Member Typedef Documentation
ValueWeakRef
template<class Key , class ValueRef > typedef weak_ptr<typename ValueRef::element_type> G3D::WeakCache< Key, ValueRef >::ValueWeakRef private
Definition at line 52 of file WeakCache.h.
Member Function Documentation
clear()
template<class Key , class ValueRef > void G3D::WeakCache< Key, ValueRef >::clear () inline
Definition at line 89 of file WeakCache.h.
                  {
         table.clear();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), and G3D::WeakCache< Key, ValueRef >::table.
getValues()
template<class Key , class ValueRef > void G3D::WeakCache< Key, ValueRef >::getValues (Array< ValueRef > & values) inline
Definition at line 78 of file WeakCache.h.
{
         Array<Key> keys;
         table.getKeys(keys);
         for (int i = 0; i < keys.size(); ++i) {
             ValueRef value = (*this)[keys[i]];
             if(notNull(value)) {
                 values.append(value);
             }
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), G3D::notNull(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::WeakCache< Key, ValueRef >::table.
operator[]()
template<class Key , class ValueRef > ValueRef G3D::WeakCache< Key, ValueRef >::operator[] (const Key & k) inline
Returns NULL if the object is not in the cache
Definition at line 62 of file WeakCache.h.
{
         if (table.containsKey(k)) {
             ValueWeakRef w = table[k];
             ValueRef s = w.lock();
             if (! s) {
                 // This object has been collected; clean out its key
                 table.remove(k);
             }
             return s;
         } else {
             return ValueRef();
         }
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), and G3D::WeakCache< Key, ValueRef >::table.
remove()
template<class Key , class ValueRef > void G3D::WeakCache< Key, ValueRef >::remove (const Key & k) inline
Removes k from the cache or does nothing if it is not currently in the cache.
Definition at line 98 of file WeakCache.h.
{
         if (table.containsKey(k)) {
             table.remove(k);
         }
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), and G3D::WeakCache< Key, ValueRef >::table.
set()
template<class Key , class ValueRef > void G3D::WeakCache< Key, ValueRef >::set (const Key & k, ValueRef v) inline
Definition at line 93 of file WeakCache.h.
{
         table.set(k, v);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::set(), and G3D::WeakCache< Key, ValueRef >::table.
Member Data Documentation
table
template<class Key , class ValueRef > Table<Key, ValueWeakRef> G3D::WeakCache< Key, ValueRef >::table private
Definition at line 56 of file WeakCache.h.
Referenced by G3D::WeakCache< Key, ValueRef >::clear(), G3D::WeakCache< Key, ValueRef >::getValues(), G3D::WeakCache< Key, ValueRef >::operator[](), G3D::WeakCache< Key, ValueRef >::remove(), and G3D::WeakCache< Key, ValueRef >::set().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/WeakCache.h