Azerotcore-wotlk: npc_bunthen_plainswind Class Reference
npc_bunthen_plainswind Class Reference
Public Member Functions
npc_bunthen_plainswind ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 59 of file zone_moonglade.cpp.
Constructor & Destructor Documentation
npc_bunthen_plainswind()
npc_bunthen_plainswind::npc_bunthen_plainswind () inline
Definition at line 62 of file zone_moonglade.cpp.
 : CreatureScript("npc_bunthen_plainswind") { }
Member Function Documentation
OnGossipHello()
bool npc_bunthen_plainswind::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 84 of file zone_moonglade.cpp.
     {
         if (player->getClass() != CLASS_DRUID)
             SendGossipMenuFor(player, 4916, creature->GetGUID());
         else if (player->GetTeamId() != TEAM_HORDE)
         {
             if (player->GetQuestStatus(QUEST_SEA_LION_ALLY) == QUEST_STATUS_INCOMPLETE)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_AQ_END, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
             SendGossipMenuFor(player, 4917, creature->GetGUID());
         }
         else if (player->getClass() == CLASS_DRUID && player->GetTeamId() == TEAM_HORDE)
         {
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_THUNDER, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             if (player->GetQuestStatus(QUEST_SEA_LION_HORDE) == QUEST_STATUS_INCOMPLETE)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_AQ_END, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
             SendGossipMenuFor(player, 4918, creature->GetGUID());
         }
         return true;
     }
References AddGossipItemFor(), CLASS_DRUID, Unit::getClass(), Object::GetGUID(), Player::GetQuestStatus(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_AQ_END, GOSSIP_ITEM_THUNDER, GOSSIP_SENDER_MAIN, QUEST_SEA_LION_ALLY, QUEST_SEA_LION_HORDE, QUEST_STATUS_INCOMPLETE, SendGossipMenuFor(), and TEAM_HORDE.
OnGossipSelect()
bool npc_bunthen_plainswind::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 64 of file zone_moonglade.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 CloseGossipMenuFor(player);
                 if (player->getClass() == CLASS_DRUID && player->GetTeamId() == TEAM_HORDE)
                     player->ActivateTaxiPathTo(TAXI_PATH_ID_HORDE);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 SendGossipMenuFor(player, 5373, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 SendGossipMenuFor(player, 5376, creature->GetGUID());
                 break;
         }
         return true;
     }
References Player::ActivateTaxiPathTo(), CLASS_DRUID, ClearGossipMenuFor(), CloseGossipMenuFor(), Unit::getClass(), Object::GetGUID(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, SendGossipMenuFor(), TAXI_PATH_ID_HORDE, and TEAM_HORDE.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_moonglade.cpp