Azerotcore-wotlk: SFMTRand Class Reference
SFMTRand Class Reference
#include <SFMTRand.h>
Public Member Functions
SFMTRand ()
uint32 RandomUInt32 ()
void * operator new (size_t size, std::nothrow_t const &)
void operator delete (void *ptr, std::nothrow_t const &)
void * operator new (size_t size)
void operator delete (void *ptr)
void * operator new[] (size_t size, std::nothrow_t const &)
void operator delete[] (void *ptr, std::nothrow_t const &)
void * operator new[] (size_t size)
void operator delete[] (void *ptr)
Private Attributes
sfmt_t _state
Detailed Description
Definition at line 28 of file SFMTRand.h.
Constructor & Destructor Documentation
SFMTRand()
SFMTRand::SFMTRand ()
Definition at line 60 of file SFMTRand.cpp.
 {
     std::random_device dev;
     if (dev.entropy() > 0)
     {
         std::array<uint32, SFMT_N32> seed;
         std::generate(seed.begin(), seed.end(), std::ref(dev));
         sfmt_init_by_array(&_state, seed.data(), seed.size());
     }
     else
     {
         sfmt_init_gen_rand(&_state, uint32(time(nullptr)));
     }
 }
References _state, sfmt_init_by_array(), and sfmt_init_gen_rand().
Member Function Documentation
operator delete() [1/2]
void SFMTRand::operator delete (void * ptr)
Definition at line 97 of file SFMTRand.cpp.
 {
     _mm_free(ptr);
 }
References ptr().
operator delete() [2/2]
void SFMTRand::operator delete (void * ptr, std::nothrow_t const &)
Definition at line 87 of file SFMTRand.cpp.
 {
     _mm_free(ptr);
 }
References ptr().
operator delete[]() [1/2]
void SFMTRand::operator delete[] (void * ptr)
Definition at line 117 of file SFMTRand.cpp.
 {
     _mm_free(ptr);
 }
References ptr().
operator delete[]() [2/2]
void SFMTRand::operator delete[] (void * ptr, std::nothrow_t const &)
Definition at line 107 of file SFMTRand.cpp.
 {
     _mm_free(ptr);
 }
References ptr().
operator new() [1/2]
void * SFMTRand::operator new (size_t size)
Definition at line 92 of file SFMTRand.cpp.
 {
     return _mm_malloc(size, 16);
 }
operator new() [2/2]
void * SFMTRand::operator new (size_t size, std::nothrow_t const &)
Definition at line 82 of file SFMTRand.cpp.
 {
     return _mm_malloc(size, 16);
 }
operator new[]() [1/2]
void * SFMTRand::operator new[] (size_t size)
Definition at line 112 of file SFMTRand.cpp.
 {
     return _mm_malloc(size, 16);
 }
operator new[]() [2/2]
void * SFMTRand::operator new[] (size_t size, std::nothrow_t const &)
Definition at line 102 of file SFMTRand.cpp.
 {
     return _mm_malloc(size, 16);
 }
RandomUInt32()
uint32 SFMTRand::RandomUInt32 ()
Definition at line 77 of file SFMTRand.cpp.
 {
     return sfmt_genrand_uint32(&_state);
 }
References _state, and sfmt_genrand_uint32().
Referenced by rand32().
Member Data Documentation
_state
sfmt_t SFMTRand::_state private
Definition at line 42 of file SFMTRand.h.
Referenced by RandomUInt32(), and SFMTRand().
The documentation for this class was generated from the following files:
src/common/Utilities/SFMTRand.h
src/common/Utilities/SFMTRand.cpp