Azerotcore-wotlk: ScriptObject Class Reference
ScriptObject Class Reference
#include <ScriptMgr.h>
Public Member Functions
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Protected Member Functions
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Private Attributes
const std::string _name
Friends
class ScriptMgr
Detailed Description
Definition at line 102 of file ScriptMgr.h.
Constructor & Destructor Documentation
ScriptObject()
ScriptObject::ScriptObject (const char * name) inline protected
Definition at line 116 of file ScriptMgr.h.
         : _name(std::string(name))
     {
     }
~ScriptObject()
virtual ScriptObject::~ScriptObject () protected virtual default
Member Function Documentation
checkValidity()
virtual void ScriptObject::checkValidity () inline virtual
Reimplemented in BattlegroundMapScript, InstanceMapScript, and WorldMapScript.
Definition at line 111 of file ScriptMgr.h.
 { }
GetName()
const std::string& ScriptObject::GetName () const inline
Definition at line 113 of file ScriptMgr.h.
 { return _name; }
References _name.
Referenced by ScriptMgr::CreateAuraScripts(), and ScriptMgr::CreateSpellScripts().
isAfterLoadScript()
virtual bool ScriptObject::isAfterLoadScript () const inline virtual
Reimplemented in BattlegroundMapScript, and WorldMapScript.
Definition at line 110 of file ScriptMgr.h.
 { return IsDatabaseBound(); }
References IsDatabaseBound().
IsDatabaseBound()
virtual bool ScriptObject::IsDatabaseBound () const inline virtual
Reimplemented in SpellSC, ArenaTeamScript, BGScript, GroupScript, GuildScript, AchievementCriteriaScript, TransportScript, ConditionScript, WeatherScript, OutdoorPvPScript, BattlegroundScript, AreaTriggerScript, GameObjectScript, CreatureScript, ItemScript, InstanceMapScript, SpellScriptLoader, DatabaseScript, CommandSC, MiscScript, ArenaScript, PetScript, and AchievementScript.
Definition at line 109 of file ScriptMgr.h.
 { return false; }
Referenced by isAfterLoadScript().
Friends And Related Function Documentation
ScriptMgr
friend class ScriptMgr friend
Definition at line 104 of file ScriptMgr.h.
Member Data Documentation
_name
const std::string ScriptObject::_name private
Definition at line 124 of file ScriptMgr.h.
Referenced by GetName().
The documentation for this class was generated from the following file:
src/server/game/Scripting/ScriptMgr.h