Azerotcore-wotlk: src/server/scripts/Commands/cs_script_loader.cpp File Reference
cs_script_loader.cpp File Reference
Functions
void AddSC_account_commandscript ()
void AddSC_achievement_commandscript ()
void AddSC_arena_commandscript ()
void AddSC_ban_commandscript ()
void AddSC_bf_commandscript ()
void AddSC_cast_commandscript ()
void AddSC_character_commandscript ()
void AddSC_cheat_commandscript ()
void AddSC_debug_commandscript ()
void AddSC_deserter_commandscript ()
void AddSC_disable_commandscript ()
void AddSC_event_commandscript ()
void AddSC_gm_commandscript ()
void AddSC_go_commandscript ()
void AddSC_gobject_commandscript ()
void AddSC_guild_commandscript ()
void AddSC_honor_commandscript ()
void AddSC_instance_commandscript ()
void AddSC_learn_commandscript ()
void AddSC_lfg_commandscript ()
void AddSC_list_commandscript ()
void AddSC_lookup_commandscript ()
void AddSC_message_commandscript ()
void AddSC_misc_commandscript ()
void AddSC_mmaps_commandscript ()
void AddSC_modify_commandscript ()
void AddSC_npc_commandscript ()
void AddSC_quest_commandscript ()
void AddSC_reload_commandscript ()
void AddSC_reset_commandscript ()
void AddSC_server_commandscript ()
void AddSC_spectator_commandscript ()
void AddSC_tele_commandscript ()
void AddSC_ticket_commandscript ()
void AddSC_titles_commandscript ()
void AddSC_wp_commandscript ()
void AddSC_player_commandscript ()
void AddCommandsScripts ()
Function Documentation
AddCommandsScripts()
void AddCommandsScripts ()
Definition at line 59 of file cs_script_loader.cpp.
 {
     AddSC_account_commandscript();
     AddSC_achievement_commandscript();
     AddSC_arena_commandscript();
     AddSC_ban_commandscript();
     AddSC_bf_commandscript();
     AddSC_cast_commandscript();
     AddSC_character_commandscript();
     AddSC_cheat_commandscript();
     AddSC_debug_commandscript();
     AddSC_deserter_commandscript();
     AddSC_disable_commandscript();
     AddSC_event_commandscript();
     AddSC_gm_commandscript();
     AddSC_go_commandscript();
     AddSC_gobject_commandscript();
     AddSC_guild_commandscript();
     AddSC_honor_commandscript();
     AddSC_instance_commandscript();
     AddSC_learn_commandscript();
     AddSC_lfg_commandscript();
     AddSC_list_commandscript();
     AddSC_lookup_commandscript();
     AddSC_message_commandscript();
     AddSC_misc_commandscript();
     AddSC_mmaps_commandscript();
     AddSC_modify_commandscript();
     AddSC_npc_commandscript();
     AddSC_quest_commandscript();
     AddSC_reload_commandscript();
     AddSC_reset_commandscript();
     AddSC_server_commandscript();
     AddSC_spectator_commandscript();
     AddSC_tele_commandscript();
     AddSC_ticket_commandscript();
     AddSC_titles_commandscript();
     AddSC_wp_commandscript();
     AddSC_player_commandscript();
 }
References AddSC_account_commandscript(), AddSC_achievement_commandscript(), AddSC_arena_commandscript(), AddSC_ban_commandscript(), AddSC_bf_commandscript(), AddSC_cast_commandscript(), AddSC_character_commandscript(), AddSC_cheat_commandscript(), AddSC_debug_commandscript(), AddSC_deserter_commandscript(), AddSC_disable_commandscript(), AddSC_event_commandscript(), AddSC_gm_commandscript(), AddSC_go_commandscript(), AddSC_gobject_commandscript(), AddSC_guild_commandscript(), AddSC_honor_commandscript(), AddSC_instance_commandscript(), AddSC_learn_commandscript(), AddSC_lfg_commandscript(), AddSC_list_commandscript(), AddSC_lookup_commandscript(), AddSC_message_commandscript(), AddSC_misc_commandscript(), AddSC_mmaps_commandscript(), AddSC_modify_commandscript(), AddSC_npc_commandscript(), AddSC_player_commandscript(), AddSC_quest_commandscript(), AddSC_reload_commandscript(), AddSC_reset_commandscript(), AddSC_server_commandscript(), AddSC_spectator_commandscript(), AddSC_tele_commandscript(), AddSC_ticket_commandscript(), AddSC_titles_commandscript(), and AddSC_wp_commandscript().
AddSC_account_commandscript()
void AddSC_account_commandscript ()
Definition at line 963 of file cs_account.cpp.
 {
     new account_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_achievement_commandscript()
void AddSC_achievement_commandscript ()
Definition at line 81 of file cs_achievement.cpp.
 {
     new achievement_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_arena_commandscript()
void AddSC_arena_commandscript ()
Definition at line 250 of file cs_arena.cpp.
 {
     new arena_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_ban_commandscript()
void AddSC_ban_commandscript ()
Definition at line 775 of file cs_ban.cpp.
 {
     new ban_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_bf_commandscript()
void AddSC_bf_commandscript ()
Definition at line 136 of file cs_bf.cpp.
 {
     new bf_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_cast_commandscript()
void AddSC_cast_commandscript ()
Definition at line 223 of file cs_cast.cpp.
 {
     new cast_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_character_commandscript()
void AddSC_character_commandscript ()
Definition at line 1016 of file cs_character.cpp.
 {
     new character_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_cheat_commandscript()
void AddSC_cheat_commandscript ()
Definition at line 238 of file cs_cheat.cpp.
 {
     new cheat_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_debug_commandscript()
void AddSC_debug_commandscript ()
Definition at line 1256 of file cs_debug.cpp.
 {
     new debug_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_deserter_commandscript()
void AddSC_deserter_commandscript ()
Definition at line 182 of file cs_deserter.cpp.
 {
     new deserter_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_disable_commandscript()
void AddSC_disable_commandscript ()
Definition at line 295 of file cs_disable.cpp.
 {
     new disable_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_event_commandscript()
void AddSC_event_commandscript ()
Definition at line 195 of file cs_event.cpp.
 {
     new event_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_gm_commandscript()
void AddSC_gm_commandscript ()
Definition at line 240 of file cs_gm.cpp.
 {
     new gm_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_go_commandscript()
void AddSC_go_commandscript ()
Definition at line 372 of file cs_go.cpp.
 {
     new go_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_gobject_commandscript()
void AddSC_gobject_commandscript ()
Definition at line 593 of file cs_gobject.cpp.
 {
     new gobject_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_guild_commandscript()
void AddSC_guild_commandscript ()
Definition at line 249 of file cs_guild.cpp.
 {
     new guild_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_honor_commandscript()
void AddSC_honor_commandscript ()
Definition at line 115 of file cs_honor.cpp.
 {
     new honor_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_instance_commandscript()
void AddSC_instance_commandscript ()
Definition at line 268 of file cs_instance.cpp.
 {
     new instance_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_learn_commandscript()
void AddSC_learn_commandscript ()
Definition at line 435 of file cs_learn.cpp.
 {
     new learn_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_lfg_commandscript()
void AddSC_lfg_commandscript ()
Definition at line 132 of file cs_lfg.cpp.
 {
     new lfg_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_list_commandscript()
void AddSC_list_commandscript ()
Definition at line 536 of file cs_list.cpp.
 {
     new list_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_lookup_commandscript()
void AddSC_lookup_commandscript ()
Definition at line 1650 of file cs_lookup.cpp.
 {
     new lookup_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_message_commandscript()
void AddSC_message_commandscript ()
Definition at line 192 of file cs_message.cpp.
 {
     new message_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_misc_commandscript()
void AddSC_misc_commandscript ()
Definition at line 3726 of file cs_misc.cpp.
 {
     new misc_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_mmaps_commandscript()
void AddSC_mmaps_commandscript ()
Definition at line 297 of file cs_mmaps.cpp.
 {
     new mmaps_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_modify_commandscript()
void AddSC_modify_commandscript ()
Definition at line 1270 of file cs_modify.cpp.
 {
     new modify_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_npc_commandscript()
void AddSC_npc_commandscript ()
Definition at line 1279 of file cs_npc.cpp.
 {
     new npc_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_player_commandscript()
void AddSC_player_commandscript ()
Definition at line 66 of file cs_player.cpp.
 {
     new player_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_quest_commandscript()
void AddSC_quest_commandscript ()
Definition at line 300 of file cs_quest.cpp.
 {
     new quest_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_reload_commandscript()
void AddSC_reload_commandscript ()
Definition at line 1169 of file cs_reload.cpp.
 {
     new reload_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_reset_commandscript()
void AddSC_reset_commandscript ()
Definition at line 313 of file cs_reset.cpp.
 {
     new reset_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_server_commandscript()
void AddSC_server_commandscript ()
Definition at line 383 of file cs_server.cpp.
 {
     new server_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_spectator_commandscript()
void AddSC_spectator_commandscript ()
Definition at line 107 of file cs_spectator.cpp.
 {
     new spectator_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_tele_commandscript()
void AddSC_tele_commandscript ()
Definition at line 315 of file cs_tele.cpp.
 {
     new tele_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_ticket_commandscript()
void AddSC_ticket_commandscript ()
Definition at line 536 of file cs_ticket.cpp.
 {
     new ticket_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_titles_commandscript()
void AddSC_titles_commandscript ()
Definition at line 196 of file cs_titles.cpp.
 {
     new titles_commandscript();
 }
Referenced by AddCommandsScripts().
AddSC_wp_commandscript()
void AddSC_wp_commandscript ()
Definition at line 1111 of file cs_wp.cpp.
 {
     new wp_commandscript();
 }
Referenced by AddCommandsScripts().