Azerotcore-wotlk: npc_rimefang::npc_rimefangAI Struct Reference
npc_rimefang::npc_rimefangAI Struct Reference
Public Member Functions
npc_rimefangAI (Creature *creature)
void InitializeAI () override
void Reset () override
void JustReachedHome () override
void JustRespawned () override
void JustDied (Unit *) override
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 point) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
uint8 _icyBlastCounter
bool _summoned
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1503 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
npc_rimefangAI()
npc_rimefang::npc_rimefangAI::npc_rimefangAI (Creature * creature) inline
Definition at line 1505 of file boss_sindragosa.cpp.
                                            : ScriptedAI(creature), _instance(creature->GetInstanceScript()), _summoned(false)
         {
         }
Member Function Documentation
DoAction()
void npc_rimefang::npc_rimefangAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1552 of file boss_sindragosa.cpp.
         {
             if (action == ACTION_START_FROSTWYRM)
             {
                 if (_summoned)
                     return;
                 _summoned = true;
                 if (me->isDead())
                     return;
                 me->setActive(true);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                 float moveTime = me->GetExactDist(&RimefangFlyPos) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                 me->m_Events.AddEvent(new FrostwyrmLandEvent(*me, RimefangLandPos), me->m_Events.CalculateTime(uint64(moveTime) + 250));
                 me->SetDefaultMovementType(IDLE_MOTION_TYPE);
                 me->GetMotionMaster()->MoveIdle();
                 me->StopMoving();
                 me->GetMotionMaster()->MovePoint(POINT_FROSTWYRM_FLY_IN, RimefangFlyPos);
             }
         }
References _summoned, ACTION_START_FROSTWYRM, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Position::GetExactDist(), Unit::GetMotionMaster(), Unit::GetSpeed(), IDLE_MOTION_TYPE, Unit::isDead(), Unit::m_Events, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_FROSTWYRM_FLY_IN, RimefangFlyPos, RimefangLandPos, WorldObject::setActive(), Creature::SetDefaultMovementType(), Object::SetFlag(), Unit::StopMoving(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
EnterCombat()
void npc_rimefang::npc_rimefangAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1596 of file boss_sindragosa.cpp.
         {
             me->CastSpell(me, SPELL_FROST_AURA_RIMEFANG, true);
         }
References Unit::CastSpell(), ScriptedAI::me, and SPELL_FROST_AURA_RIMEFANG.
InitializeAI()
void npc_rimefang::npc_rimefangAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 1509 of file boss_sindragosa.cpp.
         {
             if (!me->isDead())
             {
                 _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
                 Reset();
             }
         }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), Unit::isDead(), ScriptedAI::me, Reset(), and ZoneScript::SetData().
JustDied()
void npc_rimefang::npc_rimefangAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1547 of file boss_sindragosa.cpp.
         {
             _events.Reset();
         }
References _events, and EventMap::Reset().
JustReachedHome()
void npc_rimefang::npc_rimefangAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1532 of file boss_sindragosa.cpp.
         {
             ScriptedAI::JustReachedHome();
             if (_summoned)
             {
                 me->SetDisableGravity(false);
             }
         }
References _summoned, CreatureAI::JustReachedHome(), ScriptedAI::me, and Creature::SetDisableGravity().
JustRespawned()
void npc_rimefang::npc_rimefangAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1541 of file boss_sindragosa.cpp.
         {
             ScriptedAI::JustRespawned();
             _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
         }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), CreatureAI::JustRespawned(), ScriptedAI::me, and ZoneScript::SetData().
MovementInform()
void npc_rimefang::npc_rimefangAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1574 of file boss_sindragosa.cpp.
         {
             if (type != EFFECT_MOTION_TYPE)
                 return;
             if (point == POINT_FROSTWYRM_LAND)
             {
                 me->setActive(false);
                 me->SetDisableGravity(false);
                 me->SetHomePosition(RimefangLandPos);
                 me->SetFacingTo(RimefangLandPos.GetOrientation());
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             }
             else if (point == POINT_LAND_GROUND)
             {
                 me->SetDisableGravity(false);
                 me->SetReactState(REACT_DEFENSIVE);
                 if (Unit* victim = me->SelectVictim())
                     AttackStart(victim);
             }
         }
References ScriptedAI::AttackStart(), EFFECT_MOTION_TYPE, Position::GetOrientation(), ScriptedAI::me, POINT_FROSTWYRM_LAND, POINT_LAND_GROUND, REACT_DEFENSIVE, Object::RemoveFlag(), RimefangLandPos, Creature::SelectVictim(), WorldObject::setActive(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHomePosition(), Creature::SetReactState(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Reset()
void npc_rimefang::npc_rimefangAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1518 of file boss_sindragosa.cpp.
         {
             _events.Reset();
             _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, urand(12000, 15000));
             _events.ScheduleEvent(EVENT_ICY_BLAST, urand(30000, 35000));
             me->SetReactState(REACT_DEFENSIVE);
             _icyBlastCounter = 0;
             if (!_summoned)
             {
                 me->SetDisableGravity(true);
             }
         }
References _events, _icyBlastCounter, _summoned, EVENT_FROST_BREATH_RIMEFANG, EVENT_ICY_BLAST, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Creature::SetReactState(), and urand().
Referenced by InitializeAI().
UpdateAI()
void npc_rimefang::npc_rimefangAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1601 of file boss_sindragosa.cpp.
         {
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_FROST_BREATH_RIMEFANG:
                     if (!me->IsFlying())
                     {
                         me->CastSpell(me->GetVictim(), SPELL_FROST_BREATH, false);
                         _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, urand(20000, 25000));
                     }
                     else
                         _events.ScheduleEvent(EVENT_FROST_BREATH_RIMEFANG, 5000);
                     break;
                 case EVENT_ICY_BLAST:
                     {
                         _icyBlastCounter = RAID_MODE<uint8>(5, 7, 6, 8);
                         me->SetReactState(REACT_PASSIVE);
                         me->GetMotionMaster()->MoveIdle();
                         me->StopMoving();
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->AttackStop();
                         me->SetDisableGravity(true);
                         float floorZ = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                         float destZ;
                         if (floorZ > 190.0f) destZ = floorZ + 25.0f;
                         else destZ = me->GetPositionZ() + 25.0f;
                         me->GetMotionMaster()->MoveTakeoff(0, me->GetPositionX(), me->GetPositionY(), destZ, me->GetSpeed(MOVE_RUN));
                         float moveTime = fabs(destZ - me->GetPositionZ()) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                         _events.ScheduleEvent(EVENT_ICY_BLAST, uint32(moveTime) + urand(60000, 70000));
                         _events.ScheduleEvent(EVENT_ICY_BLAST_CAST, uint32(moveTime) + 250);
                         break;
                     }
                 case EVENT_ICY_BLAST_CAST:
                     if (--_icyBlastCounter)
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
{
                             me->SetFacingToObject(target);
                             me->CastSpell(target, SPELL_ICY_BLAST, false);
                         }
                         _events.ScheduleEvent(EVENT_ICY_BLAST_CAST, 3000);
                     }
                     else
                     {
                         float floorZ = me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                         float destZ;
                         if (floorZ > 190.0f) destZ = floorZ;
                         else destZ = me->GetPositionZ() - 25.0f;
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveLand(POINT_LAND_GROUND, me->GetPositionX(), me->GetPositionY(), destZ, me->GetSpeed(MOVE_RUN));
                     }
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _events, _icyBlastCounter, Unit::AttackStop(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_FROST_BREATH_RIMEFANG, EVENT_ICY_BLAST, EVENT_ICY_BLAST_CAST, EventMap::ExecuteEvent(), WorldObject::GetMapHeight(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsFlying(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), POINT_LAND_GROUND, REACT_PASSIVE, EventMap::ScheduleEvent(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Creature::SetDisableGravity(), Unit::SetFacingToObject(), Creature::SetReactState(), SPELL_FROST_BREATH, SPELL_ICY_BLAST, Unit::StopMoving(), UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_rimefang::npc_rimefangAI::_events private
Definition at line 1671 of file boss_sindragosa.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
_icyBlastCounter
uint8 npc_rimefang::npc_rimefangAI::_icyBlastCounter private
Definition at line 1673 of file boss_sindragosa.cpp.
Referenced by Reset(), and UpdateAI().
_instance
InstanceScript* npc_rimefang::npc_rimefangAI::_instance private
Definition at line 1672 of file boss_sindragosa.cpp.
Referenced by InitializeAI(), and JustRespawned().
_summoned
bool npc_rimefang::npc_rimefangAI::_summoned private
Definition at line 1674 of file boss_sindragosa.cpp.
Referenced by DoAction(), JustReachedHome(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp