Azerotcore-wotlk: at_commander_dawnforge Class Reference
at_commander_dawnforge Class Reference
Public Member Functions
at_commander_dawnforge ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1592 of file zone_netherstorm.cpp.
Constructor & Destructor Documentation
at_commander_dawnforge()
at_commander_dawnforge::at_commander_dawnforge () inline
Definition at line 1595 of file zone_netherstorm.cpp.
 : AreaTriggerScript("at_commander_dawnforge") { }
Member Function Documentation
OnTrigger()
bool at_commander_dawnforge::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1597 of file zone_netherstorm.cpp.
     {
         //if player lost aura or not have at all, we should not try start event.
         if (!player->HasAura(SPELL_SUNFURY_DISGUISE))
             return false;
         if (player->IsAlive() && player->GetQuestStatus(QUEST_INFO_GATHERING) == QUEST_STATUS_INCOMPLETE)
         {
             Creature* Dawnforge = player->FindNearestCreature(CreatureEntry[1], 30.0f);
             if (!Dawnforge)
                 return false;
             if (CAST_AI(npc_commander_dawnforge::npc_commander_dawnforgeAI, Dawnforge->AI())->CanStartEvent(player))
                 return true;
         }
         return false;
     }
References Creature::AI(), CAST_AI, WorldObject::FindNearestCreature(), Player::GetQuestStatus(), Unit::HasAura(), Unit::IsAlive(), QUEST_INFO_GATHERING, QUEST_STATUS_INCOMPLETE, and SPELL_SUNFURY_DISGUISE.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_netherstorm.cpp