Azerotcore-wotlk: npc_valkyr_shadowguard::npc_valkyr_shadowguardAI Struct Reference
npc_valkyr_shadowguard::npc_valkyr_shadowguardAI Struct Reference
Public Member Functions
npc_valkyr_shadowguardAI (Creature *creature)
bool IsHeroic ()
void GoSiphon ()
void OnCharmed (bool) override
void PassengerBoarded (Unit *pass, int8, bool apply) override
== Fields =======================================
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 id) override
void SetGUID (ObjectGuid guid, int32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap _events
Position _destPoint
ObjectGuid _grabbedPlayer
bool didbelow50pct
bool dropped
InstanceScript * _instance
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2517 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
npc_valkyr_shadowguardAI()
npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI (Creature * creature) inline
Definition at line 2519 of file boss_the_lich_king.cpp.
                                                      : NullCreatureAI(creature), didbelow50pct(false), dropped(false), _instance(creature->GetInstanceScript())
         {
             me->SetReactState(REACT_PASSIVE);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, true);
             me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
             _events.Reset();
             _events.ScheduleEvent(EVENT_GRAB_PLAYER, 2500);
             me->SetWalk(false);
         }
References _events, Unit::ApplySpellImmune(), EVENT_GRAB_PLAYER, IMMUNITY_EFFECT, IMMUNITY_STATE, CreatureAI::me, REACT_PASSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetReactState(), Creature::SetWalk(), SPELL_AURA_MOD_TAUNT, and SPELL_EFFECT_ATTACK_ME.
Member Function Documentation
DamageTaken()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 2568 of file boss_the_lich_king.cpp.
         {
             if (IsHeroic() && !didbelow50pct && !dropped && me->HealthBelowPctDamaged(50, damage))
                 GoSiphon();
         }
References didbelow50pct, dropped, GoSiphon(), Unit::HealthBelowPctDamaged(), IsHeroic(), and CreatureAI::me.
GoSiphon()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon () inline
Definition at line 2538 of file boss_the_lich_king.cpp.
         {
             didbelow50pct = true;
             me->CastSpell((Unit*)nullptr, SPELL_EJECT_ALL_PASSENGERS, false);
             float dist = rand_norm() * 10.0f + 5.0f;
             float angle = CenterPosition.GetAngle(me);
             _destPoint.Relocate(CenterPosition.GetPositionX() + dist * cos(angle), CenterPosition.GetPositionY() + dist * sin(angle), 855.0f + frand(0.0f, 4.0f), 0.0f);
             me->SetHomePosition(_destPoint);
             _events.Reset();
             _events.ScheduleEvent(EVENT_MOVE_TO_SIPHON_POS, 0);
         }
References _destPoint, _events, Unit::CastSpell(), CenterPosition, didbelow50pct, EVENT_MOVE_TO_SIPHON_POS, frand(), Position::GetAngle(), Position::GetPositionX(), Position::GetPositionY(), CreatureAI::me, rand_norm(), Position::Relocate(), EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetHomePosition(), and SPELL_EJECT_ALL_PASSENGERS.
Referenced by DamageTaken(), MovementInform(), and PassengerBoarded().
IsHeroic()
bool npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::IsHeroic () inline
Definition at line 2536 of file boss_the_lich_king.cpp.
 { return me->GetMap()->IsHeroic(); }
References WorldObject::GetMap(), Map::IsHeroic(), and CreatureAI::me.
Referenced by DamageTaken(), MovementInform(), and PassengerBoarded().
MovementInform()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 2574 of file boss_the_lich_king.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch (id)
             {
                 case EVENT_CHARGE:
                     {
                         bool valid = false;
                         if (Player* target = ObjectAccessor::GetPlayer(*me, _grabbedPlayer))
                             if (target->FindMap() == me->GetMap() && target->GetExactDist(me) < 15.0f && !target->GetVehicle())
                                 if (GameObject* platform = ObjectAccessor::GetGameObject(*me, _instance->GetGuidData(DATA_ARTHAS_PLATFORM)))
{
                                     std::list<Creature*> triggers;
                                     GetCreatureListWithEntryInGrid(triggers, me, NPC_WORLD_TRIGGER, 150.0f);
                                     triggers.remove_if(HeightDifferenceCheck(platform, 5.0f, true));
                                     if (!triggers.empty())
{
                                         valid = true;
                                         triggers.sort(Acore::ObjectDistanceOrderPred(me));
                                         target->GetMotionMaster()->Clear();
                                         target->UpdatePosition(*me, true);
                                         target->StopMovingOnCurrentPos();
                                         me->CastSpell(target, SPELL_VALKYR_CARRY, false);
                                         _destPoint.Relocate(triggers.front());
                                         _events.Reset();
                                         _events.ScheduleEvent(EVENT_MOVE_TO_DROP_POS, 1000);
                                     }
                                 }
                         if (!valid)
{
                             _events.Reset();
                             _events.ScheduleEvent(EVENT_GRAB_PLAYER, 500);
                             _grabbedPlayer.Clear();
                         }
                     }
                     break;
                 case POINT_DROP_PLAYER:
                     {
                         if (didbelow50pct || dropped)
                             break;
                         if (me->GetExactDist(&_destPoint) > 1.5f) // movement was interrupted (probably by a stun, start again)
{
                             _events.Reset();
                             _events.ScheduleEvent(EVENT_MOVE_TO_DROP_POS, 0);
                             break;
                         }
                         dropped = true;
                         _events.Reset();
                         /*Player* p = nullptr;
                         if (Vehicle* v = me->GetVehicleKit())
                             if (Unit* passenger = v->GetPassenger(0))
                                 p = passenger->ToPlayer();*/
                         me->CastSpell((Unit*)nullptr, SPELL_EJECT_ALL_PASSENGERS, false);
                         if (IsHeroic())
                             GoSiphon();
                         else
                             me->DespawnOrUnsummon(1000);
                     }
                     break;
                 case POINT_START_SIPHON:
                     if (me->GetExactDist(&_destPoint) > 1.5f) // movement was interrupted (probably by a stun, start again)
                     {
                         _events.Reset();
                         _events.ScheduleEvent(EVENT_MOVE_TO_SIPHON_POS, 0);
                         break;
                     }
                     me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, false);
                     me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, false);
                     _events.ScheduleEvent(EVENT_LIFE_SIPHON, 2000);
                     break;
             }
         }
References _destPoint, _events, _grabbedPlayer, _instance, Unit::ApplySpellImmune(), Unit::CastSpell(), ObjectGuid::Clear(), DATA_ARTHAS_PLATFORM, Creature::DespawnOrUnsummon(), didbelow50pct, dropped, EVENT_CHARGE, EVENT_GRAB_PLAYER, EVENT_LIFE_SIPHON, EVENT_MOVE_TO_DROP_POS, EVENT_MOVE_TO_SIPHON_POS, GetCreatureListWithEntryInGrid(), Position::GetExactDist(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), ObjectAccessor::GetPlayer(), GoSiphon(), IMMUNITY_EFFECT, IMMUNITY_STATE, IsHeroic(), CreatureAI::me, NPC_WORLD_TRIGGER, POINT_DROP_PLAYER, POINT_MOTION_TYPE, POINT_START_SIPHON, Position::Relocate(), EventMap::Reset(), EventMap::ScheduleEvent(), SPELL_AURA_MOD_TAUNT, SPELL_EFFECT_ATTACK_ME, SPELL_EJECT_ALL_PASSENGERS, and SPELL_VALKYR_CARRY.
OnCharmed()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::OnCharmed (bool) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 2550 of file boss_the_lich_king.cpp.
 {}
PassengerBoarded()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 2552 of file boss_the_lich_king.cpp.
         {
             if (apply)
             {
                 //pass->ClearUnitState(UNIT_STATE_ONVEHICLE);
                 return;
             }
             pass->RemoveAurasDueToSpell(VEHICLE_SPELL_PARACHUTE);
             if (didbelow50pct || dropped)
                 return;
             if (IsHeroic())
                 GoSiphon();
             else
                 me->DespawnOrUnsummon(1000);
         }
References ByteConverter::apply(), Creature::DespawnOrUnsummon(), didbelow50pct, dropped, GoSiphon(), IsHeroic(), CreatureAI::me, Unit::RemoveAurasDueToSpell(), and VEHICLE_SPELL_PARACHUTE.
SetGUID()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::SetGUID (ObjectGuid guid, int32) inline override virtual
Reimplemented from UnitAI.
Definition at line 2652 of file boss_the_lich_king.cpp.
         {
             _grabbedPlayer = guid;
         }
References _grabbedPlayer.
UpdateAI()
void npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 2657 of file boss_the_lich_king.cpp.
         {
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_STUNNED))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_GRAB_PLAYER:
                     if (!_grabbedPlayer)
                     {
                         me->CastSpell((Unit*)nullptr, SPELL_VALKYR_TARGET_SEARCH, false);
                         _events.ScheduleEvent(EVENT_GRAB_PLAYER, 2000);
                     }
                     break;
                 case EVENT_MOVE_TO_DROP_POS:
                     me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                     me->SetCanFly(false);
                     me->SetDisableGravity(false);
                     me->GetMotionMaster()->MovePoint(POINT_DROP_PLAYER, _destPoint, false);
                     me->SetDisableGravity(true, true);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     break;
                 case EVENT_MOVE_TO_SIPHON_POS:
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE); // just in case if passenger disappears so quickly that EVENT_MOVE_TO_DROP_POS is never executed
                     { int32 bp0 = 80; me->CastCustomSpell(me, 1557, &bp0, nullptr, nullptr, true); }
                     me->SetCanFly(true);
                     me->SetDisableGravity(true);
                     me->SendMovementFlagUpdate();
                     me->GetMotionMaster()->MovePoint(POINT_START_SIPHON, _destPoint);
                     break;
                 case EVENT_LIFE_SIPHON:
                     {
                         Unit* target = nullptr;
                         Unit::AuraEffectList const& tauntAuras = me->GetAuraEffectsByType(SPELL_AURA_MOD_TAUNT);
                         if (!tauntAuras.empty())
                             for (Unit::AuraEffectList::const_reverse_iterator itr = tauntAuras.rbegin(); itr != tauntAuras.rend(); ++itr)
                                 if (Unit* caster = (*itr)->GetCaster())
                                     if (me->IsValidAttackTarget(caster))
{
                                         target = caster;
                                         break;
                                     }
                         if (!target)
                             if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                                 target = lichKing->AI()->SelectTarget(SELECT_TARGET_RANDOM, 0, NonTankLKTargetSelector(lichKing, true, false, 100.0f));
                         if (target)
                             me->CastSpell(target, SPELL_LIFE_SIPHON, false);
                         _events.ScheduleEvent(EVENT_LIFE_SIPHON, 2500);
                     }
                     break;
                 default:
                     break;
             }
         }
References _destPoint, _events, _grabbedPlayer, _instance, Unit::AddUnitState(), Unit::CastCustomSpell(), Unit::CastSpell(), DATA_THE_LICH_KING, EVENT_GRAB_PLAYER, EVENT_LIFE_SIPHON, EVENT_MOVE_TO_DROP_POS, EVENT_MOVE_TO_SIPHON_POS, EventMap::ExecuteEvent(), Unit::GetAuraEffectsByType(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::HasUnitState(), Unit::IsValidAttackTarget(), CreatureAI::me, MotionMaster::MovePoint(), POINT_DROP_PLAYER, POINT_START_SIPHON, Object::RemoveFlag(), EventMap::ScheduleEvent(), SELECT_TARGET_RANDOM, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), SPELL_AURA_MOD_TAUNT, SPELL_LIFE_SIPHON, SPELL_VALKYR_TARGET_SEARCH, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_NO_ENVIRONMENT_UPD, UNIT_STATE_STUNNED, and EventMap::Update().
Member Data Documentation
_destPoint
Position npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::_destPoint
Definition at line 2530 of file boss_the_lich_king.cpp.
Referenced by GoSiphon(), MovementInform(), and UpdateAI().
_events
EventMap npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::_events
Definition at line 2529 of file boss_the_lich_king.cpp.
Referenced by GoSiphon(), MovementInform(), npc_valkyr_shadowguardAI(), and UpdateAI().
_grabbedPlayer
ObjectGuid npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::_grabbedPlayer
Definition at line 2531 of file boss_the_lich_king.cpp.
Referenced by MovementInform(), SetGUID(), and UpdateAI().
_instance
InstanceScript* npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::_instance
Definition at line 2534 of file boss_the_lich_king.cpp.
Referenced by MovementInform(), and UpdateAI().
didbelow50pct
bool npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::didbelow50pct
Definition at line 2532 of file boss_the_lich_king.cpp.
Referenced by DamageTaken(), GoSiphon(), MovementInform(), and PassengerBoarded().
dropped
bool npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::dropped
Definition at line 2533 of file boss_the_lich_king.cpp.
Referenced by DamageTaken(), MovementInform(), and PassengerBoarded().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp