Azerotcore-wotlk: BattlegroundDS Class Reference
BattlegroundDS Class Reference
#include <BattlegroundDS.h>
Public Member Functions
BattlegroundDS ()
~BattlegroundDS () override
void AddPlayer (Player *player) override
void StartingEventCloseDoors () override
void StartingEventOpenDoors () override
void RemovePlayer (Player *player) override
void HandleAreaTrigger (Player *player, uint32 trigger) override
bool SetupBattleground () override
void Init () override
void FillInitialWorldStates (WorldPacket &d) override
void HandleKillPlayer (Player *player, Player *killer) override
bool HandlePlayerUnderMap (Player *player) override
Public Member Functions inherited from Battleground
Battleground ()
virtual ~Battleground ()
void Update (uint32 diff)
virtual void ResetBGSubclass ()
virtual void DestroyGate (Player *, GameObject *)
virtual bool AllNodesConrolledByTeam (TeamId) const
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
char const * GetName () const
BattlegroundTypeId GetBgTypeID (bool GetRandom=false) const
uint32 GetInstanceID () const
BattlegroundStatus GetStatus () const
uint32 GetClientInstanceID () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetLastResurrectTime () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
uint8 GetArenaType () const
TeamId GetWinner () const
uint32 GetScriptId () const
uint32 GetBonusHonorFromKill (uint32 kills) const
bool IsRandom ()
void SetName (char const *Name)
void SetBgTypeID (BattlegroundTypeId TypeID)
void SetRandomTypeID (BattlegroundTypeId TypeID)
void SetInstanceID (uint32 InstanceID)
void SetStatus (BattlegroundStatus Status)
void SetClientInstanceID (uint32 InstanceID)
void SetStartTime (uint32 Time)
void SetEndTime (uint32 Time)
void SetLastResurrectTime (uint32 Time)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (uint8 type)
void SetArenaorBGType (bool _isArena)
void SetWinner (TeamId winner)
void SetScriptId (uint32 scriptId)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int32 diff)
void SetStartDelayTime (int32 Time)
void SetMaxPlayersPerTeam (uint32 MaxPlayers)
void SetMinPlayersPerTeam (uint32 MinPlayers)
void DecreaseInvitedCount (TeamId teamId)
void IncreaseInvitedCount (TeamId teamId)
uint32 GetInvitedCount (TeamId teamId) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (TeamId teamId) const
uint32 GetMaxFreeSlots () const
void AddSpectator (Player *p)
void RemoveSpectator (Player *p)
bool HaveSpectators ()
const SpectatorList & GetSpectators () const
void AddToBeTeleported (ObjectGuid spectator, ObjectGuid participant)
void RemoveToBeTeleported (ObjectGuid spectator)
void SpectatorsSendPacket (WorldPacket &data)
bool isArena () const
bool isBattleground () const
bool isRated () const
BattlegroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
void ReadyMarkerClicked (Player *p)
BattlegroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattlegroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
uint32 GetReviveQueueSize () const
void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (Player *player)
void RelocateDeadPlayers (ObjectGuid queueIndex)
Relocate all players in ReviveQueue to the closest graveyard.
void StartBattleground ()
GameObject * GetBGObject (uint32 type)
Creature * GetBGCreature (uint32 type)
void SetMapId (uint32 MapID)
uint32 GetMapId () const
void SetBgMap (BattlegroundMap *map)
BattlegroundMap * GetBgMap () const
BattlegroundMap * FindBgMap () const
void SetTeamStartLoc (TeamId teamId, float X, float Y, float Z, float O)
void GetTeamStartLoc (TeamId teamId, float &X, float &Y, float &Z, float &O) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
void SendPacketToTeam (TeamId teamId, WorldPacket *packet, Player *sender=nullptr, bool self=true)
void SendPacketToAll (WorldPacket *packet)
void YellToAll (Creature *creature, const char *text, uint32 language)
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToAll (uint32 soundId)
void CastSpellOnTeam (uint32 spellId, TeamId teamId)
void RemoveAuraOnTeam (uint32 spellId, TeamId teamId)
void RewardHonorToTeam (uint32 honor, TeamId teamId)
void RewardReputationToTeam (uint32 factionId, uint32 reputation, TeamId teamId)
uint32 GetRealRepFactionForPlayer (uint32 factionId, Player *player)
void UpdateWorldState (uint32 Field, uint32 Value)
void UpdateWorldStateForPlayer (uint32 Field, uint32 Value, Player *player)
virtual void EndBattleground (TeamId winnerTeamId)
void BlockMovement (Player *player)
void SendWarningToAll (uint32 entry,...)
void SendMessageToAll (uint32 entry, ChatMsg type, Player const *source=nullptr)
void PSendMessageToAll (uint32 entry, ChatMsg type, Player const *source,...)
void SendMessage2ToAll (uint32 entry, ChatMsg type, Player const *source, uint32 strId1=0, uint32 strId2=0)
Group * GetBgRaid (TeamId teamId) const
void SetBgRaid (TeamId teamId, Group *bg_raid)
virtual void UpdatePlayerScore (Player *player, uint32 type, uint32 value, bool doAddHonor=true)
uint32 GetPlayersCountByTeam (TeamId teamId) const
uint32 GetAlivePlayersCountByTeam (TeamId teamId) const
void UpdatePlayersCountByTeam (TeamId teamId, bool remove)
void SetArenaTeamIdForTeam (TeamId teamId, uint32 ArenaTeamId)
uint32 GetArenaTeamIdForTeam (TeamId teamId) const
void SetArenaTeamRatingChangeForTeam (TeamId teamId, int32 RatingChange)
int32 GetArenaTeamRatingChangeForTeam (TeamId teamId) const
void SetArenaMatchmakerRating (TeamId teamId, uint32 MMR)
uint32 GetArenaMatchmakerRating (TeamId teamId) const
void CheckArenaAfterTimerConditions ()
void CheckArenaWinConditions ()
virtual void UpdateArenaWorldState ()
virtual void HandleKillUnit (Creature *, Player *)
virtual void EventPlayerDroppedFlag (Player *)
virtual void EventPlayerClickedOnFlag (Player *, GameObject *)
virtual void EventPlayerDamagedGO (Player *, GameObject *, uint32)
virtual void EventPlayerUsedGO (Player *, GameObject *)
virtual void DoAction (uint32, ObjectGuid)
virtual void HandlePlayerResurrect (Player *)
virtual GraveyardStruct const * GetClosestGraveyard (Player *player)
void AddOrSetPlayerToCorrectBgGroup (Player *player, TeamId teamId)
void RemovePlayerAtLeave (Player *player)
void HandleTriggerBuff (GameObject *gameObject)
void SetHoliday (bool is_holiday)
void SpawnBGObject (uint32 type, uint32 respawntime, uint32 forceRespawnDelay=0)
bool AddObject (uint32 type, uint32 entry, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime=0, GOState goState=GO_STATE_READY)
Creature * AddCreature (uint32 entry, uint32 type, float x, float y, float z, float o, uint32 respawntime=0, MotionTransport *transport=nullptr)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool AddSpiritGuide (uint32 type, float x, float y, float z, float o, TeamId teamId)
int32 GetObjectType (ObjectGuid guid)
void DoorOpen (uint32 type)
void DoorClose (uint32 type)
const char * GetAcoreString (int32 entry)
bool IsPlayerInBattleground (ObjectGuid guid) const
bool ToBeDeleted () const
void RewardXPAtKill (Player *killer, Player *victim)
virtual ObjectGuid GetFlagPickerGUID (TeamId=TEAM_NEUTRAL) const
virtual void SetDroppedFlagGUID (ObjectGuid, TeamId=TEAM_NEUTRAL)
uint32 GetTeamScore (TeamId teamId) const
virtual TeamId GetPrematureWinner ()
uint8 GetUniqueBracketId () const
BattlegroundAV * ToBattlegroundAV ()
BattlegroundAV const * ToBattlegroundAV () const
BattlegroundWS * ToBattlegroundWS ()
BattlegroundWS const * ToBattlegroundWS () const
BattlegroundAB * ToBattlegroundAB ()
BattlegroundAB const * ToBattlegroundAB () const
BattlegroundNA * ToBattlegroundNA ()
BattlegroundNA const * ToBattlegroundNA () const
BattlegroundBE * ToBattlegroundBE ()
BattlegroundBE const * ToBattlegroundBE () const
BattlegroundEY * ToBattlegroundEY ()
BattlegroundEY const * ToBattlegroundEY () const
BattlegroundRL * ToBattlegroundRL ()
BattlegroundRL const * ToBattlegroundRL () const
BattlegroundSA * ToBattlegroundSA ()
BattlegroundSA const * ToBattlegroundSA () const
BattlegroundDS * ToBattlegroundDS ()
BattlegroundDS const * ToBattlegroundDS () const
BattlegroundRV * ToBattlegroundRV ()
BattlegroundRV const * ToBattlegroundRV () const
BattlegroundIC * ToBattlegroundIC ()
BattlegroundIC const * ToBattlegroundIC () const
Protected Member Functions
uint32 getWaterFallStatus ()
void setWaterFallStatus (uint8 status)
uint32 getWaterFallTimer ()
void setWaterFallTimer (uint32 timer)
uint32 getWaterFallKnockbackTimer ()
void setWaterFallKnockbackTimer (uint32 timer)
uint8 getPipeKnockBackCount ()
void setPipeKnockBackCount (uint8 count)
uint32 getPipeKnockBackTimer ()
void setPipeKnockBackTimer (uint32 timer)
Protected Member Functions inherited from Battleground
void EndNow ()
void PlayerAddedToBGCheckIfBGIsRunning (Player *player)
void _ProcessResurrect (uint32 diff)
void _ProcessProgress (uint32 diff)
void _ProcessLeave (uint32 diff)
void _ProcessJoin (uint32 diff)
void _CheckSafePositions (uint32 diff)
Private Member Functions
void PostUpdateImpl (uint32 diff) override
Post-update hook.
Private Attributes
uint32 _waterfallTimer
uint8 _waterfallStatus
uint32 _waterfallKnockbackTimer
uint32 _pipeKnockBackTimer
uint8 _pipeKnockBackCount
Additional Inherited Members
Public Types inherited from Battleground
typedef std::set< Player * > SpectatorList
typedef std::map< ObjectGuid, ObjectGuid > ToBeTeleportedMap
typedef std::map< ObjectGuid, Player * > BattlegroundPlayerMap
typedef std::map< ObjectGuid, BattlegroundScore * > BattlegroundScoreMap
typedef std::map< ObjectGuid, ArenaLogEntryData > ArenaLogEntryDataMap
typedef GuidVector BGObjects
typedef GuidVector BGCreatures
Static Public Member Functions inherited from Battleground
static TeamId GetOtherTeamId (TeamId teamId)
Public Attributes inherited from Battleground
GuidSet readyMarkerClickedSet
ArenaLogEntryDataMap ArenaLogEntries
BGObjects BgObjects
BGCreatures BgCreatures
Protected Attributes inherited from Battleground
BattlegroundScoreMap PlayerScores
BattlegroundPlayerMap m_Players
std::map< ObjectGuid, GuidVector > m_ReviveQueue
uint8 m_Events
BattlegroundStartTimeIntervals StartDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 StartMessageIds [BG_STARTING_EVENT_COUNT]
bool m_BuffChange
bool m_IsRandom
BGHonorMode m_HonorMode
int32 m_TeamScores [BG_TEAMS_COUNT]
uint32 m_UpdateTimer
Detailed Description
Definition at line 84 of file BattlegroundDS.h.
Constructor & Destructor Documentation
BattlegroundDS()
BattlegroundDS::BattlegroundDS ()
Definition at line 27 of file BattlegroundDS.cpp.
 {
     BgObjects.resize(BG_DS_OBJECT_MAX);
     BgCreatures.resize(BG_DS_NPC_MAX);
     _waterfallTimer = 0;
     _waterfallStatus = 0;
     _waterfallKnockbackTimer = 0;
     _pipeKnockBackTimer = 0;
     _pipeKnockBackCount = 0;
     StartDelayTimes[BG_STARTING_EVENT_FIRST]  = BG_START_DELAY_1M;
     StartDelayTimes[BG_STARTING_EVENT_SECOND] = BG_START_DELAY_30S;
     StartDelayTimes[BG_STARTING_EVENT_THIRD]  = BG_START_DELAY_15S;
     StartDelayTimes[BG_STARTING_EVENT_FOURTH] = BG_START_DELAY_NONE;
     //we must set messageIds
     StartMessageIds[BG_STARTING_EVENT_FIRST]  = LANG_ARENA_ONE_MINUTE;
     StartMessageIds[BG_STARTING_EVENT_SECOND] = LANG_ARENA_THIRTY_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_THIRD]  = LANG_ARENA_FIFTEEN_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_FOURTH] = LANG_ARENA_HAS_BEGUN;
 }
References _pipeKnockBackCount, _pipeKnockBackTimer, _waterfallKnockbackTimer, _waterfallStatus, _waterfallTimer, BG_DS_NPC_MAX, BG_DS_OBJECT_MAX, BG_START_DELAY_15S, BG_START_DELAY_1M, BG_START_DELAY_30S, BG_START_DELAY_NONE, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, Battleground::BgCreatures, Battleground::BgObjects, LANG_ARENA_FIFTEEN_SECONDS, LANG_ARENA_HAS_BEGUN, LANG_ARENA_ONE_MINUTE, LANG_ARENA_THIRTY_SECONDS, Battleground::StartDelayTimes, and Battleground::StartMessageIds.
~BattlegroundDS()
BattlegroundDS::~BattlegroundDS () override
Definition at line 49 of file BattlegroundDS.cpp.
 {
 }
Member Function Documentation
AddPlayer()
void BattlegroundDS::AddPlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 151 of file BattlegroundDS.cpp.
 {
     Battleground::AddPlayer(player);
     PlayerScores[player->GetGUID()] = new BattlegroundScore(player);
     Battleground::UpdateArenaWorldState();
 }
References Battleground::AddPlayer(), Object::GetGUID(), Battleground::PlayerScores, and Battleground::UpdateArenaWorldState().
FillInitialWorldStates()
void BattlegroundDS::FillInitialWorldStates (WorldPacket & d) override virtual
Reimplemented from Battleground.
Definition at line 229 of file BattlegroundDS.cpp.
 {
     data << uint32(3610) << uint32(1);                                              // 9 show
     Battleground::UpdateArenaWorldState();
 }
References Battleground::UpdateArenaWorldState().
getPipeKnockBackCount()
uint8 BattlegroundDS::getPipeKnockBackCount () inline protected
Definition at line 117 of file BattlegroundDS.h.
 { return _pipeKnockBackCount; };
References _pipeKnockBackCount.
Referenced by HandleAreaTrigger(), and PostUpdateImpl().
getPipeKnockBackTimer()
uint32 BattlegroundDS::getPipeKnockBackTimer () inline protected
Definition at line 119 of file BattlegroundDS.h.
 { return _pipeKnockBackTimer; };
References _pipeKnockBackTimer.
Referenced by PostUpdateImpl().
getWaterFallKnockbackTimer()
uint32 BattlegroundDS::getWaterFallKnockbackTimer () inline protected
Definition at line 115 of file BattlegroundDS.h.
 { return _waterfallKnockbackTimer; };
References _waterfallKnockbackTimer.
Referenced by PostUpdateImpl().
getWaterFallStatus()
uint32 BattlegroundDS::getWaterFallStatus () inline protected
Definition at line 111 of file BattlegroundDS.h.
 { return _waterfallStatus; };
References _waterfallStatus.
Referenced by PostUpdateImpl().
getWaterFallTimer()
uint32 BattlegroundDS::getWaterFallTimer () inline protected
Definition at line 113 of file BattlegroundDS.h.
 { return _waterfallTimer; };
References _waterfallTimer.
Referenced by PostUpdateImpl().
HandleAreaTrigger()
void BattlegroundDS::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from Battleground.
Definition at line 184 of file BattlegroundDS.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     switch (trigger)
     {
         case 5347:
         case 5348:
             // Remove effects of Demonic Circle Summon
             if (player->HasAura(48018))
                 player->RemoveAurasDueToSpell(48018);
             // Someone has get back into the pipes and the knockback has already been performed,
             // so we reset the knockback count for kicking the player again into the arena.
             if (getPipeKnockBackCount() >= BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT)
                 setPipeKnockBackCount(0);
             break;
         // OUTSIDE OF ARENA, TELEPORT!
         case 5328:
             player->NearTeleportTo(1290.44f, 744.96f, 3.16f, 1.6f);
             break;
         case 5329:
             player->NearTeleportTo(1292.6f, 837.07f, 3.161f, 4.7f);
             break;
         case 5330:
             player->NearTeleportTo(1250.68f, 790.86f, 3.16f, 0.0f);
             break;
         case 5331:
             player->NearTeleportTo(1332.50f, 790.9f, 3.16f, 3.14f);
             break;
         case 5326: // -10
         case 5343: // -40
         case 5344: // -60
             player->NearTeleportTo(1330.0f, 800.0f, 3.16f, player->GetOrientation());
             break;
     }
 }
References BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT, Position::GetOrientation(), getPipeKnockBackCount(), Battleground::GetStatus(), Unit::HasAura(), Unit::NearTeleportTo(), Unit::RemoveAurasDueToSpell(), setPipeKnockBackCount(), and STATUS_IN_PROGRESS.
HandleKillPlayer()
void BattlegroundDS::HandleKillPlayer (Player * player, Player * killer) override virtual
Reimplemented from Battleground.
Definition at line 167 of file BattlegroundDS.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     if (!killer)
     {
         LOG_ERROR("bg.battleground", "BattlegroundDS: Killer player not found");
         return;
     }
     Battleground::HandleKillPlayer(player, killer);
     Battleground::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), Battleground::HandleKillPlayer(), LOG_ERROR, STATUS_IN_PROGRESS, and Battleground::UpdateArenaWorldState().
HandlePlayerUnderMap()
bool BattlegroundDS::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 223 of file BattlegroundDS.cpp.
 {
     player->NearTeleportTo(1299.046f, 784.825f, 9.338f, 2.422f);
     return true;
 }
References Unit::NearTeleportTo().
Init()
void BattlegroundDS::Init () override virtual
Reimplemented from Battleground.
Definition at line 235 of file BattlegroundDS.cpp.
 {
     //call parent's class reset
     Battleground::Init();
 }
References Battleground::Init().
PostUpdateImpl()
void BattlegroundDS::PostUpdateImpl (uint32) override private virtual
Post-update hook.
Will be called after battleground update has passed. May be used to implement custom update effects in subclasses.
Parameters
diff a time difference between two worldserver update loops in milliseconds.
See also
Update(), PreUpdateImpl().
Reimplemented from Battleground.
Definition at line 53 of file BattlegroundDS.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     if (getPipeKnockBackCount() < BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT)
     {
         if (getPipeKnockBackTimer() < diff)
         {
             for (uint32 i = BG_DS_NPC_PIPE_KNOCKBACK_1; i <= BG_DS_NPC_PIPE_KNOCKBACK_2; ++i)
                 if (Creature* waterSpout = GetBgMap()->GetCreature(BgCreatures[i]))
                     waterSpout->CastSpell(waterSpout, BG_DS_SPELL_FLUSH, true);
             setPipeKnockBackCount(getPipeKnockBackCount() + 1);
             setPipeKnockBackTimer(BG_DS_PIPE_KNOCKBACK_DELAY);
         }
         else
             setPipeKnockBackTimer(getPipeKnockBackTimer() - diff);
     }
     if (getWaterFallStatus() == BG_DS_WATERFALL_STATUS_ON) // Repeat knockback while the waterfall still active
     {
         if (getWaterFallKnockbackTimer() < diff)
         {
             if (Creature* waterSpout = GetBgMap()->GetCreature(BgCreatures[BG_DS_NPC_WATERFALL_KNOCKBACK]))
                 waterSpout->CastSpell(waterSpout, BG_DS_SPELL_WATER_SPOUT, true);
             setWaterFallKnockbackTimer(BG_DS_WATERFALL_KNOCKBACK_TIMER);
         }
         else
             setWaterFallKnockbackTimer(getWaterFallKnockbackTimer() - diff);
     }
     if (getWaterFallTimer() < diff)
     {
         if (getWaterFallStatus() == BG_DS_WATERFALL_STATUS_OFF) // Add the water
         {
             DoorClose(BG_DS_OBJECT_WATER_2);
             setWaterFallTimer(BG_DS_WATERFALL_WARNING_DURATION);
             setWaterFallStatus(BG_DS_WATERFALL_STATUS_WARNING);
         }
         else if (getWaterFallStatus() == BG_DS_WATERFALL_STATUS_WARNING) // Active collision and perform knockback
         {
             if (GameObject* gob = GetBgMap()->GetGameObject(BgObjects[BG_DS_OBJECT_WATER_1]))
                 gob->SetGoState(GO_STATE_READY);
             setWaterFallTimer(BG_DS_WATERFALL_DURATION);
             setWaterFallStatus(BG_DS_WATERFALL_STATUS_ON);
             setWaterFallKnockbackTimer(BG_DS_WATERFALL_KNOCKBACK_TIMER);
         }
         else //if (getWaterFallStatus() == BG_DS_WATERFALL_STATUS_ON) // Remove collision and water
         {
             // turn off collision
             if (GameObject* gob = GetBgMap()->GetGameObject(BgObjects[BG_DS_OBJECT_WATER_1]))
                 gob->SetGoState(GO_STATE_ACTIVE);
             DoorOpen(BG_DS_OBJECT_WATER_2);
             setWaterFallTimer(urand(BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_TIMER_MAX));
             setWaterFallStatus(BG_DS_WATERFALL_STATUS_OFF);
         }
     }
     else
         setWaterFallTimer(getWaterFallTimer() - diff);
 }
References BG_DS_NPC_PIPE_KNOCKBACK_1, BG_DS_NPC_PIPE_KNOCKBACK_2, BG_DS_NPC_WATERFALL_KNOCKBACK, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, BG_DS_PIPE_KNOCKBACK_DELAY, BG_DS_PIPE_KNOCKBACK_TOTAL_COUNT, BG_DS_SPELL_FLUSH, BG_DS_SPELL_WATER_SPOUT, BG_DS_WATERFALL_DURATION, BG_DS_WATERFALL_KNOCKBACK_TIMER, BG_DS_WATERFALL_STATUS_OFF, BG_DS_WATERFALL_STATUS_ON, BG_DS_WATERFALL_STATUS_WARNING, BG_DS_WATERFALL_TIMER_MAX, BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_WARNING_DURATION, Battleground::BgCreatures, Battleground::BgObjects, Battleground::DoorClose(), Battleground::DoorOpen(), Battleground::GetBgMap(), ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), getPipeKnockBackCount(), getPipeKnockBackTimer(), Battleground::GetStatus(), getWaterFallKnockbackTimer(), getWaterFallStatus(), getWaterFallTimer(), GO_STATE_ACTIVE, GO_STATE_READY, setPipeKnockBackCount(), setPipeKnockBackTimer(), setWaterFallKnockbackTimer(), setWaterFallStatus(), setWaterFallTimer(), STATUS_IN_PROGRESS, and urand().
RemovePlayer()
void BattlegroundDS::RemovePlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 158 of file BattlegroundDS.cpp.
 {
     if (GetStatus() == STATUS_WAIT_LEAVE)
         return;
     Battleground::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), STATUS_WAIT_LEAVE, and Battleground::UpdateArenaWorldState().
setPipeKnockBackCount()
void BattlegroundDS::setPipeKnockBackCount (uint8 count) inline protected
Definition at line 118 of file BattlegroundDS.h.
 { _pipeKnockBackCount = count; };
References _pipeKnockBackCount.
Referenced by HandleAreaTrigger(), PostUpdateImpl(), and StartingEventOpenDoors().
setPipeKnockBackTimer()
void BattlegroundDS::setPipeKnockBackTimer (uint32 timer) inline protected
Definition at line 120 of file BattlegroundDS.h.
 { _pipeKnockBackTimer = timer; };
References _pipeKnockBackTimer.
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
SetupBattleground()
bool BattlegroundDS::SetupBattleground () override virtual
Reimplemented from Battleground.
Definition at line 241 of file BattlegroundDS.cpp.
 {
     // gates
     if (!AddObject(BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_TYPE_DOOR_1, 1350.95f, 817.2f, 20.8096f, 3.15f, 0, 0, 0.99627f, 0.0862864f, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_TYPE_DOOR_2, 1232.65f, 764.913f, 20.0729f, 6.3f, 0, 0, 0.0310211f, -0.999519f, RESPAWN_IMMEDIATELY)
             // water
             || !AddObject(BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_TYPE_WATER_1, 1291.56f, 790.837f, 7.1f, 3.14238f, 0, 0, 0.694215f, -0.719768f, 120)
             || !AddObject(BG_DS_OBJECT_WATER_2, BG_DS_OBJECT_TYPE_WATER_2, 1291.56f, 790.837f, 7.1f, 3.14238f, 0, 0, 0.694215f, -0.719768f, 120)
             // buffs
             || !AddObject(BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_TYPE_BUFF_1, 1291.7f, 813.424f, 7.11472f, 4.64562f, 0, 0, 0.730314f, -0.683111f, 120)
             || !AddObject(BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_TYPE_BUFF_2, 1291.7f, 768.911f, 7.11472f, 1.55194f, 0, 0, 0.700409f, 0.713742f, 120)
             // knockback creatures
             || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_WATERFALL_KNOCKBACK, 1291.76f, 791.02f, 7.115f, 3.054326f, RESPAWN_IMMEDIATELY)
             || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_PIPE_KNOCKBACK_1, 1369.977f, 817.2882f, 16.08718f, 3.106686f, RESPAWN_IMMEDIATELY)
             || !AddCreature(BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_PIPE_KNOCKBACK_2, 1212.833f, 765.3871f, 16.09484f, 0.0f, RESPAWN_IMMEDIATELY)
             // Arena Ready Marker
             || !AddObject(BG_DS_OBJECT_READY_MARKER_1, ARENA_READY_MARKER_ENTRY, 1229.44f, 759.35f, 17.89f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
             || !AddObject(BG_DS_OBJECT_READY_MARKER_2, ARENA_READY_MARKER_ENTRY, 1352.90f, 822.77f, 17.96f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300))
     {
         LOG_ERROR("sql.sql", "BatteGroundDS: Failed to spawn some object!");
         return false;
     }
     return true;
 }
References Battleground::AddCreature(), Battleground::AddObject(), ARENA_READY_MARKER_ENTRY, BG_DS_NPC_PIPE_KNOCKBACK_1, BG_DS_NPC_PIPE_KNOCKBACK_2, BG_DS_NPC_TYPE_WATER_SPOUT, BG_DS_NPC_WATERFALL_KNOCKBACK, BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_READY_MARKER_1, BG_DS_OBJECT_READY_MARKER_2, BG_DS_OBJECT_TYPE_BUFF_1, BG_DS_OBJECT_TYPE_BUFF_2, BG_DS_OBJECT_TYPE_DOOR_1, BG_DS_OBJECT_TYPE_DOOR_2, BG_DS_OBJECT_TYPE_WATER_1, BG_DS_OBJECT_TYPE_WATER_2, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, LOG_ERROR, and RESPAWN_IMMEDIATELY.
setWaterFallKnockbackTimer()
void BattlegroundDS::setWaterFallKnockbackTimer (uint32 timer) inline protected
Definition at line 116 of file BattlegroundDS.h.
 { _waterfallKnockbackTimer = timer; };
References _waterfallKnockbackTimer.
Referenced by PostUpdateImpl().
setWaterFallStatus()
void BattlegroundDS::setWaterFallStatus (uint8 status) inline protected
Definition at line 112 of file BattlegroundDS.h.
 { _waterfallStatus = status; };
References _waterfallStatus.
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
setWaterFallTimer()
void BattlegroundDS::setWaterFallTimer (uint32 timer) inline protected
Definition at line 114 of file BattlegroundDS.h.
 { _waterfallTimer = timer; };
References _waterfallTimer.
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
StartingEventCloseDoors()
void BattlegroundDS::StartingEventCloseDoors () override virtual
Reimplemented from Battleground.
Definition at line 118 of file BattlegroundDS.cpp.
 {
     for (uint32 i = BG_DS_OBJECT_DOOR_1; i <= BG_DS_OBJECT_DOOR_2; ++i)
         SpawnBGObject(i, RESPAWN_IMMEDIATELY);
 }
References BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, RESPAWN_IMMEDIATELY, and Battleground::SpawnBGObject().
StartingEventOpenDoors()
void BattlegroundDS::StartingEventOpenDoors () override virtual
Reimplemented from Battleground.
Definition at line 124 of file BattlegroundDS.cpp.
 {
     for (uint32 i = BG_DS_OBJECT_DOOR_1; i <= BG_DS_OBJECT_DOOR_2; ++i)
         DoorOpen(i);
     for (uint32 i = BG_DS_OBJECT_BUFF_1; i <= BG_DS_OBJECT_BUFF_2; ++i)
         SpawnBGObject(i, 60);
     setWaterFallTimer(urand(BG_DS_WATERFALL_TIMER_MIN, BG_DS_WATERFALL_TIMER_MAX));
     setWaterFallStatus(BG_DS_WATERFALL_STATUS_OFF);
     setPipeKnockBackTimer(BG_DS_PIPE_KNOCKBACK_FIRST_DELAY);
     setPipeKnockBackCount(0);
     SpawnBGObject(BG_DS_OBJECT_WATER_2, RESPAWN_IMMEDIATELY);
     DoorOpen(BG_DS_OBJECT_WATER_2);
     // Turn off collision
     if (GameObject* gob = GetBgMap()->GetGameObject(BgObjects[BG_DS_OBJECT_WATER_1]))
         gob->SetGoState(GO_STATE_ACTIVE);
     // Remove effects of Demonic Circle Summon
     for (BattlegroundPlayerMap::const_iterator itr = GetPlayers().begin(); itr != GetPlayers().end(); ++itr)
         if (itr->second->HasAura(48018))
             itr->second->RemoveAurasDueToSpell(48018);
 }
References BG_DS_OBJECT_BUFF_1, BG_DS_OBJECT_BUFF_2, BG_DS_OBJECT_DOOR_1, BG_DS_OBJECT_DOOR_2, BG_DS_OBJECT_WATER_1, BG_DS_OBJECT_WATER_2, BG_DS_PIPE_KNOCKBACK_FIRST_DELAY, BG_DS_WATERFALL_STATUS_OFF, BG_DS_WATERFALL_TIMER_MAX, BG_DS_WATERFALL_TIMER_MIN, Battleground::BgObjects, Battleground::DoorOpen(), Battleground::GetBgMap(), ObjectAccessor::GetGameObject(), Battleground::GetPlayers(), GO_STATE_ACTIVE, RESPAWN_IMMEDIATELY, setPipeKnockBackCount(), setPipeKnockBackTimer(), setWaterFallStatus(), setWaterFallTimer(), Battleground::SpawnBGObject(), and urand().
Member Data Documentation
_pipeKnockBackCount
uint8 BattlegroundDS::_pipeKnockBackCount private
Definition at line 107 of file BattlegroundDS.h.
Referenced by BattlegroundDS(), getPipeKnockBackCount(), and setPipeKnockBackCount().
_pipeKnockBackTimer
uint32 BattlegroundDS::_pipeKnockBackTimer private
Definition at line 106 of file BattlegroundDS.h.
Referenced by BattlegroundDS(), getPipeKnockBackTimer(), and setPipeKnockBackTimer().
_waterfallKnockbackTimer
uint32 BattlegroundDS::_waterfallKnockbackTimer private
Definition at line 105 of file BattlegroundDS.h.
Referenced by BattlegroundDS(), getWaterFallKnockbackTimer(), and setWaterFallKnockbackTimer().
_waterfallStatus
uint8 BattlegroundDS::_waterfallStatus private
Definition at line 104 of file BattlegroundDS.h.
Referenced by BattlegroundDS(), getWaterFallStatus(), and setWaterFallStatus().
_waterfallTimer
uint32 BattlegroundDS::_waterfallTimer private
Definition at line 103 of file BattlegroundDS.h.
Referenced by BattlegroundDS(), getWaterFallTimer(), and setWaterFallTimer().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/Zones/BattlegroundDS.h
src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp