Azerotcore-wotlk: boss_kiljaeden::boss_kiljaedenAI Struct Reference
boss_kiljaeden::boss_kiljaedenAI Struct Reference
Public Member Functions
boss_kiljaedenAI (Creature *creature)
void InitializeAI () override
void Reset () override
void EnterEvadeMode () override
void AttackStart (Unit *who) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void DoAction (int32 param) override
void KilledUnit (Unit *victim) override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
void EmpowerOrb (bool empowerAll)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
EventMap events
EventMap events2
uint8 phase
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 280 of file boss_kiljaeden.cpp.
Constructor & Destructor Documentation
boss_kiljaedenAI()
boss_kiljaeden::boss_kiljaedenAI::boss_kiljaedenAI (Creature * creature) inline
Definition at line 282 of file boss_kiljaeden.cpp.
                                              : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             me->SetReactState(REACT_PASSIVE);
         }
References WorldObject::GetInstanceScript(), instance, ScriptedAI::me, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void boss_kiljaeden::boss_kiljaedenAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 318 of file boss_kiljaeden.cpp.
         {
             if (me->GetReactState() == REACT_PASSIVE)
                 return;
             ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), Creature::GetReactState(), ScriptedAI::me, and REACT_PASSIVE.
DamageTaken()
void boss_kiljaeden::boss_kiljaedenAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 325 of file boss_kiljaeden.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 me->SetTarget();
                 me->SetReactState(REACT_PASSIVE);
                 me->RemoveAllAuras();
                 me->DeleteThreatList();
                 me->SetRegeneratingHealth(false);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->HandleEmoteCommand(EMOTE_ONESHOT_DROWN);
                 me->resetAttackTimer();
                 events.Reset();
                 events2.Reset();
                 events2.ScheduleEvent(EVENT_KILL_SELF, 500);
                 damage = 0;
             }
         }
References Unit::DeleteThreatList(), EMOTE_ONESHOT_DROWN, EVENT_KILL_SELF, events2, Unit::GetHealth(), Unit::HandleEmoteCommand(), ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAllAuras(), EventMap::Reset(), Unit::resetAttackTimer(), EventMap::ScheduleEvent(), Object::SetFlag(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Creature::SetTarget(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_kiljaeden::boss_kiljaedenAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 352 of file boss_kiljaeden.cpp.
         {
             if (param == ACTION_NO_KILL_TALK)
             {
                 events.ScheduleEvent(EVENT_NO_KILL_TALK, 0);
                 Talk(SAY_KJ_DARKNESS);
             }
         }
References ACTION_NO_KILL_TALK, EVENT_NO_KILL_TALK, SAY_KJ_DARKNESS, and CreatureAI::Talk().
EmpowerOrb()
void boss_kiljaeden::boss_kiljaedenAI::EmpowerOrb (bool empowerAll) inline
Definition at line 640 of file boss_kiljaeden.cpp.
         {
             for (uint8 i = 0; i < 4; ++i)
             {
                 if (GameObject* orb = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1 + i)))
                 {
                     if (orb->HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE))
                     {
                         orb->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                         if (Creature* trigger = me->SummonTrigger(orb->GetPositionX(), orb->GetPositionY(), orb->GetPositionZ(), 0, 10 * MINUTE * IN_MILLISECONDS))
{
                             trigger->CastSpell(trigger, SPELL_RING_OF_BLUE_FLAMES, true, nullptr, nullptr, trigger->GetGUID());
                             if (Creature* controller = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KILJAEDEN_CONTROLLER)))
                                 controller->AI()->JustSummoned(trigger);
                         }
                         if (!empowerAll)
                             break;
                     }
                 }
             }
         }
References DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1, GAMEOBJECT_FLAGS, ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_NOT_SELECTABLE, IN_MILLISECONDS, instance, ScriptedAI::me, MINUTE, NPC_KILJAEDEN_CONTROLLER, SPELL_RING_OF_BLUE_FLAMES, and WorldObject::SummonTrigger().
Referenced by UpdateAI().
EnterCombat()
void boss_kiljaeden::boss_kiljaedenAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 367 of file boss_kiljaeden.cpp.
         {
             events2.ScheduleEvent(EVENT_TEXT_SPEACH11, 26000, EVENT_GROUP_SPEACH);
             Talk(SAY_KJ_EMERGE);
             events.SetTimer(200000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH85, 1000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH55, 1000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH25, 1000);
             events.ScheduleEvent(EVENT_SPELL_SOUL_FLAY, 0);
             events.ScheduleEvent(EVENT_SPELL_LEGION_LIGHTNING, 7000);
             events.ScheduleEvent(EVENT_SPELL_FIRE_BLOOM, 9000);
             events.ScheduleEvent(EVENT_SUMMON_ORBS, 10000);
         }
References EVENT_CHECK_HEALTH25, EVENT_CHECK_HEALTH55, EVENT_CHECK_HEALTH85, EVENT_GROUP_SPEACH, EVENT_SPELL_FIRE_BLOOM, EVENT_SPELL_LEGION_LIGHTNING, EVENT_SPELL_SOUL_FLAY, EVENT_SUMMON_ORBS, EVENT_TEXT_SPEACH11, events2, SAY_KJ_EMERGE, EventMap::ScheduleEvent(), and CreatureAI::Talk().
EnterEvadeMode()
void boss_kiljaeden::boss_kiljaedenAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 311 of file boss_kiljaeden.cpp.
         {
             if (me->GetReactState() == REACT_PASSIVE)
                 return;
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), Creature::GetReactState(), ScriptedAI::me, and REACT_PASSIVE.
InitializeAI()
void boss_kiljaeden::boss_kiljaedenAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 293 of file boss_kiljaeden.cpp.
         {
             ScriptedAI::InitializeAI();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             phase = PHASE_NORMAL;
             events.Reset();
             events2.Reset();
             events2.ScheduleEvent(EVENT_INIT_FIGHT, 11000);
             events2.ScheduleEvent(EVENT_REBIRTH, 0);
             me->SetVisible(false);
         }
References EVENT_INIT_FIGHT, EVENT_REBIRTH, events2, UnitAI::InitializeAI(), ScriptedAI::me, PHASE_NORMAL, EventMap::Reset(), EventMap::ScheduleEvent(), Object::SetFlag(), Unit::SetVisible(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
JustDied()
void boss_kiljaeden::boss_kiljaedenAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 344 of file boss_kiljaeden.cpp.
         {
             Talk(SAY_KJ_DEATH);
             instance->SetBossState(DATA_KILJAEDEN, DONE);
             if (Creature* controller = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KILJAEDEN_CONTROLLER)))
                 Unit::Kill(controller, controller);
         }
References DATA_KILJAEDEN, DONE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, Unit::Kill(), ScriptedAI::me, NPC_KILJAEDEN_CONTROLLER, SAY_KJ_DEATH, InstanceScript::SetBossState(), and CreatureAI::Talk().
JustSummoned()
void boss_kiljaeden::boss_kiljaedenAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 382 of file boss_kiljaeden.cpp.
         {
             if (summon->GetEntry() == NPC_ARMAGEDDON_TARGET)
             {
                 summon->SetCanFly(true);
                 summon->SetDisableGravity(true);
                 summon->CastSpell(summon, SPELL_ARMAGEDDON_VISUAL, true);
                 summon->SetPosition(summon->GetPositionX(), summon->GetPositionY(), summon->GetPositionZ() + 20.0f, 0.0f);
                 summon->m_Events.AddEvent(new CastArmageddon(summon), summon->m_Events.CalculateTime(6000));
                 summon->DespawnOrUnsummon(10000);
             }
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Creature::DespawnOrUnsummon(), Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::m_Events, NPC_ARMAGEDDON_TARGET, Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetPosition(), and SPELL_ARMAGEDDON_VISUAL.
KilledUnit()
void boss_kiljaeden::boss_kiljaedenAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 361 of file boss_kiljaeden.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER && events.GetNextEventTime(EVENT_NO_KILL_TALK) == 0)
                 Talk(SAY_KJ_SLAY);
         }
References EVENT_NO_KILL_TALK, Object::GetTypeId(), SAY_KJ_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_kiljaeden::boss_kiljaedenAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 306 of file boss_kiljaeden.cpp.
         {
             events.Reset();
         }
UpdateAI()
void boss_kiljaeden::boss_kiljaedenAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 395 of file boss_kiljaeden.cpp.
         {
             events2.Update(diff);
             switch (events2.ExecuteEvent())
             {
                 case EVENT_KILL_SELF:
                     Unit::Kill(me, me);
                     break;
                 case EVENT_REBIRTH:
                     me->SetVisible(true);
                     me->CastSpell(me, SPELL_REBIRTH, false);
                     break;
                 case EVENT_EMPOWER_ORBS1:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_READY1);
                     EmpowerOrb(false);
                     break;
                 case EVENT_EMPOWER_ORBS2:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_READY2);
                     EmpowerOrb(false);
                     break;
                 case EVENT_EMPOWER_ORBS3:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_READY_ALL);
                     EmpowerOrb(true);
                     break;
                 case EVENT_INIT_FIGHT:
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->SetInCombatWithZone();
                     return;
                 case EVENT_TEXT_SPEACH11:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_JOIN);
                     break;
                 case EVENT_TEXT_SPEACH21:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_AWAKEN);
                     break;
                 case EVENT_TEXT_SPEACH22:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                         sCreatureTextMgr->SendChat(anveena, SAY_ANVEENA_IMPRISONED, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_ZONE);
                     break;
                 case EVENT_TEXT_SPEACH23:
                     Talk(SAY_KJ_PHASE3);
                     break;
                 case EVENT_TEXT_SPEACH31:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_LETGO);
                     break;
                 case EVENT_TEXT_SPEACH32:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                         sCreatureTextMgr->SendChat(anveena, SAY_ANVEENA_LOST, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_ZONE);
                     break;
                 case EVENT_TEXT_SPEACH33:
                     Talk(SAY_KJ_PHASE4);
                     break;
                 case EVENT_TEXT_SPEACH41:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_FOCUS);
                     break;
                 case EVENT_TEXT_SPEACH42:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                         sCreatureTextMgr->SendChat(anveena, SAY_ANVEENA_KALEC, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_ZONE);
                     break;
                 case EVENT_TEXT_SPEACH43:
                     if (Creature* kalec = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_KALECGOS_KJ)))
                         kalec->AI()->Talk(SAY_KALECGOS_FATE);
                     break;
                 case EVENT_TEXT_SPEACH44:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                         sCreatureTextMgr->SendChat(anveena, SAY_ANVEENA_GOODBYE, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_ZONE);
                     break;
                 case EVENT_TEXT_SPEACH45:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                     {
                         anveena->RemoveAllAuras();
                         anveena->DespawnOrUnsummon(3500);
                     }
                     break;
                 case EVENT_TEXT_SPEACH46:
                     if (Creature* anveena = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ANVEENA)))
                     {
                         anveena->CastSpell(anveena, SPELL_SACRIFICE_OF_ANVEENA, true);
                         me->CastSpell(me, SPELL_CUSTOM_08_STATE, true);
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
                         events.DelayEvents(7001);
                         events2.ScheduleEvent(EVENT_RESTORE_MELEE, 7000);
                     }
                     Talk(SAY_KJ_PHASE5);
                     break;
                 case EVENT_RESTORE_MELEE:
                     me->RemoveAurasDueToSpell(SPELL_CUSTOM_08_STATE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
                     break;
             }
             if (me->GetReactState() != REACT_AGGRESSIVE)
                 return;
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_HEALTH85:
                     if (me->HealthBelowPct(85))
                     {
                         phase = PHASE_DARKNESS;
                         events2.CancelEvent(EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH21, 16000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH22, 22000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH23, 28000, EVENT_GROUP_SPEACH);
                         events2.RescheduleEvent(EVENT_EMPOWER_ORBS1, 35000);
                         events.DelayEvents(2000);
                         events.ScheduleEvent(EVENT_SPELL_SINISTER_REFLECTION, 500);
                         events.ScheduleEvent(EVENT_SPELL_SHADOW_SPIKE, 1200);
                         events.ScheduleEvent(EVENT_SPELL_FLAME_DART, 3000);
                         events.RescheduleEvent(EVENT_SPELL_DARKNESS, 16000); // will be delayed by 29 secs
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH85, 0);
                     break;
                 case EVENT_CHECK_HEALTH55:
                     if (me->HealthBelowPct(55))
                     {
                         phase = PHASE_ARMAGEDDON;
                         events2.CancelEventGroup(EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH31, 16000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH32, 22000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH33, 28000, EVENT_GROUP_SPEACH);
                         events2.RescheduleEvent(EVENT_EMPOWER_ORBS2, 35000);
                         events.DelayEvents(2000);
                         events.ScheduleEvent(EVENT_SPELL_SINISTER_REFLECTION, 500);
                         events.ScheduleEvent(EVENT_SPELL_SHADOW_SPIKE, 1200);
                         events.RescheduleEvent(EVENT_SPELL_DARKNESS, 15000); // will be delayed by 29 secs
                         events.ScheduleEvent(EVENT_SPELL_ARMAGEDDON, 10000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH55, 0);
                     break;
                 case EVENT_CHECK_HEALTH25:
                     if (me->HealthBelowPct(25))
                     {
                         phase = PHASE_SACRIFICE;
                         events2.CancelEventGroup(EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH41, 8000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH42, 18000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH43, 20200, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH44, 25000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH45, 28000, EVENT_GROUP_SPEACH);
                         events2.ScheduleEvent(EVENT_TEXT_SPEACH46, 30000, EVENT_GROUP_SPEACH);
                         events2.RescheduleEvent(EVENT_EMPOWER_ORBS3, 61000);
                         events.CancelEvent(EVENT_SUMMON_ORBS);
                         events.DelayEvents(4000);
                         events.ScheduleEvent(EVENT_SPELL_SINISTER_REFLECTION, 500);
                         events.ScheduleEvent(EVENT_SPELL_SHADOW_SPIKE, 1200);
                         events.RescheduleEvent(EVENT_SPELL_DARKNESS, 15000); // will be delayed by 29 secs
                         events.ScheduleEvent(EVENT_SPELL_ARMAGEDDON, 1500);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH25, 0);
                     break;
                 case EVENT_SPELL_SOUL_FLAY:
                     me->CastSpell(me->GetVictim(), SPELL_SOUL_FLAY, false);
                     events.ScheduleEvent(EVENT_SPELL_SOUL_FLAY, urand(4000, 5000));
                     break;
                 case EVENT_SPELL_LEGION_LIGHTNING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f, true))
                         me->CastSpell(target, SPELL_LEGION_LIGHTNING, false);
                     events.ScheduleEvent(EVENT_SPELL_LEGION_LIGHTNING, phase == PHASE_SACRIFICE ? 15000 : 30000);
                     events.RescheduleEvent(EVENT_SPELL_SOUL_FLAY, 2000);
                     break;
                 case EVENT_SPELL_FIRE_BLOOM:
                     me->CastCustomSpell(SPELL_FIRE_BLOOM, SPELLVALUE_MAX_TARGETS, 5, me, TRIGGERED_NONE);
                     me->SetTarget(me->GetVictim()->GetGUID());
                     events.ScheduleEvent(EVENT_SPELL_FIRE_BLOOM, phase == PHASE_SACRIFICE ? 20000 : 40000);
                     events.RescheduleEvent(EVENT_SPELL_SOUL_FLAY, 1500);
                     break;
                 case EVENT_SUMMON_ORBS:
                     for (uint8 i = 1; i < phase; ++i)
                     {
                         float x = me->GetPositionX() + 18.0f * cos((i * 2.0f - 1.0f) * M_PI / 3.0f);
                         float y = me->GetPositionY() + 18.0f * sin((i * 2.0f - 1.0f) * M_PI / 3.0f);
                         if (Creature* orb = me->SummonCreature(NPC_SHIELD_ORB, x, y, 40.0f, 0, TEMPSUMMON_CORPSE_DESPAWN))
{
                             Movement::PointsArray movementArray;
                             movementArray.push_back(G3D::Vector3(x, y, 40.0f));
                             // generate movement array
                             for (uint8 j = 1; j < 20; ++j)
{
                                 x = me->GetPositionX() + 18.0f * cos(((i * 2.0f - 1.0f) * M_PI / 3.0f) + (j / 20.0f * 2 * M_PI));
                                 y = me->GetPositionY() + 18.0f * sin(((i * 2.0f - 1.0f) * M_PI / 3.0f) + (j / 20.0f * 2 * M_PI));
                                 movementArray.push_back(G3D::Vector3(x, y, 40.0f));
                             }
                             Movement::MoveSplineInit init(orb);
                             init.MovebyPath(movementArray);
                             init.SetCyclic();
                             init.Launch();
                         }
                     }
                     events.ScheduleEvent(EVENT_SUMMON_ORBS, 40000);
                     break;
                 case EVENT_SPELL_SHADOW_SPIKE:
                     events.DelayEvents(27000);
                     me->CastSpell(me, SPELL_SHADOW_SPIKE, false);
                     break;
                 case EVENT_SPELL_SINISTER_REFLECTION:
                     Talk(SAY_KJ_REFLECTION);
                     me->CastCustomSpell(SPELL_SINISTER_REFLECTION, SPELLVALUE_MAX_TARGETS, 1, me, TRIGGERED_NONE);
                     me->CastCustomSpell(SPELL_SINISTER_REFLECTION, SPELLVALUE_MAX_TARGETS, 1, me, TRIGGERED_NONE);
                     me->CastCustomSpell(SPELL_SINISTER_REFLECTION, SPELLVALUE_MAX_TARGETS, 1, me, TRIGGERED_NONE);
                     me->CastCustomSpell(SPELL_SINISTER_REFLECTION, SPELLVALUE_MAX_TARGETS, 1, me, TRIGGERED_NONE);
                     break;
                 case EVENT_SPELL_FLAME_DART:
                     me->CastSpell(me, SPELL_FLAME_DART, false);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_DART, 10000);
                     break;
                 case EVENT_SPELL_DARKNESS:
                     Talk(EMOTE_KJ_DARKNESS);
                     me->CastSpell(me, SPELL_DARKNESS_OF_A_THOUSAND_SOULS, false);
                     events.ScheduleEvent(EVENT_SPELL_DARKNESS, phase == PHASE_SACRIFICE ? 20000 : 45000);
                     events.DelayEvents(8000);
                     break;
                 case EVENT_SPELL_ARMAGEDDON:
                     me->CastSpell(me, SPELL_ARMAGEDDON_PERIODIC, true);
                     events.ScheduleEvent(EVENT_SPELL_ARMAGEDDON, phase == PHASE_SACRIFICE ? 20000 : 40000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References EventMap::CancelEvent(), EventMap::CancelEventGroup(), Unit::CastCustomSpell(), Unit::CastSpell(), CHAT_MSG_ADDON, UnitAI::DoMeleeAttackIfReady(), EMOTE_KJ_DARKNESS, EmpowerOrb(), EVENT_CHECK_HEALTH25, EVENT_CHECK_HEALTH55, EVENT_CHECK_HEALTH85, EVENT_EMPOWER_ORBS1, EVENT_EMPOWER_ORBS2, EVENT_EMPOWER_ORBS3, EVENT_GROUP_SPEACH, EVENT_INIT_FIGHT, EVENT_KILL_SELF, EVENT_REBIRTH, EVENT_RESTORE_MELEE, EVENT_SPELL_ARMAGEDDON, EVENT_SPELL_DARKNESS, EVENT_SPELL_FIRE_BLOOM, EVENT_SPELL_FLAME_DART, EVENT_SPELL_LEGION_LIGHTNING, EVENT_SPELL_SHADOW_SPIKE, EVENT_SPELL_SINISTER_REFLECTION, EVENT_SPELL_SOUL_FLAY, EVENT_SUMMON_ORBS, EVENT_TEXT_SPEACH11, EVENT_TEXT_SPEACH21, EVENT_TEXT_SPEACH22, EVENT_TEXT_SPEACH23, EVENT_TEXT_SPEACH31, EVENT_TEXT_SPEACH32, EVENT_TEXT_SPEACH33, EVENT_TEXT_SPEACH41, EVENT_TEXT_SPEACH42, EVENT_TEXT_SPEACH43, EVENT_TEXT_SPEACH44, EVENT_TEXT_SPEACH45, EVENT_TEXT_SPEACH46, events2, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), Creature::GetReactState(), Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), instance, Unit::Kill(), LANG_ADDON, Movement::MoveSplineInit::Launch(), ScriptedAI::me, Movement::MoveSplineInit::MovebyPath(), NPC_ANVEENA, NPC_KALECGOS_KJ, NPC_SHIELD_ORB, phase, PHASE_ARMAGEDDON, PHASE_DARKNESS, PHASE_SACRIFICE, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), EventMap::RescheduleEvent(), SAY_ANVEENA_GOODBYE, SAY_ANVEENA_IMPRISONED, SAY_ANVEENA_KALEC, SAY_ANVEENA_LOST, SAY_KALECGOS_AWAKEN, SAY_KALECGOS_FATE, SAY_KALECGOS_FOCUS, SAY_KALECGOS_JOIN, SAY_KALECGOS_LETGO, SAY_KALECGOS_READY1, SAY_KALECGOS_READY2, SAY_KALECGOS_READY_ALL, SAY_KJ_PHASE3, SAY_KJ_PHASE4, SAY_KJ_PHASE5, SAY_KJ_REFLECTION, EventMap::ScheduleEvent(), sCreatureTextMgr, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Movement::MoveSplineInit::SetCyclic(), Object::SetFlag(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Creature::SetTarget(), Unit::SetVisible(), SPELL_ARMAGEDDON_PERIODIC, SPELL_CUSTOM_08_STATE, SPELL_DARKNESS_OF_A_THOUSAND_SOULS, SPELL_FIRE_BLOOM, SPELL_FLAME_DART, SPELL_LEGION_LIGHTNING, SPELL_REBIRTH, SPELL_SACRIFICE_OF_ANVEENA, SPELL_SHADOW_SPIKE, SPELL_SINISTER_REFLECTION, SPELL_SOUL_FLAY, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_DESPAWN, TEXT_RANGE_ZONE, TRIGGERED_NONE, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PACIFIED, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_kiljaeden::boss_kiljaedenAI::events
Definition at line 289 of file boss_kiljaeden.cpp.
events2
EventMap boss_kiljaeden::boss_kiljaedenAI::events2
Definition at line 290 of file boss_kiljaeden.cpp.
Referenced by DamageTaken(), EnterCombat(), InitializeAI(), and UpdateAI().
instance
InstanceScript* boss_kiljaeden::boss_kiljaedenAI::instance
Definition at line 288 of file boss_kiljaeden.cpp.
Referenced by boss_kiljaedenAI(), EmpowerOrb(), JustDied(), and UpdateAI().
phase
uint8 boss_kiljaeden::boss_kiljaedenAI::phase
Definition at line 291 of file boss_kiljaeden.cpp.
Referenced by UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp