Azerotcore-wotlk: ContinentBuilder Class Reference
ContinentBuilder Class Reference
#include <ContinentBuilder.h>
Public Member Functions
ContinentBuilder (std::string continent, uint32 mapId, WDT *wdt, uint32 tn)
void Build ()
void getTileBounds (uint32 tileX, uint32 tileY, float *verts, int vertCount, float *bmin, float *bmax)
void CalculateTileBounds ()
Public Attributes
float bmin [3]
float bmax [3]
Private Attributes
std::string Continent
WDT * TileMap
uint32 MapId
uint32 NumberOfThreads
int tileXMin
int tileYMin
int tileXMax
int tileYMax
Detailed Description
Definition at line 24 of file ContinentBuilder.h.
Constructor & Destructor Documentation
ContinentBuilder()
ContinentBuilder::ContinentBuilder (std::string continent, uint32 mapId, WDT * wdt, uint32 tn) inline
Definition at line 27 of file ContinentBuilder.h.
                                                                              :
         Continent(continent), TileMap(wdt), MapId(mapId),
         NumberOfThreads(tn), tileXMin(64), tileYMin(64), tileXMax(0), tileYMax(0)
     {}
Member Function Documentation
Build()
void ContinentBuilder::Build ()
Definition at line 116 of file ContinentBuilder.cpp.
 {
     char buff[50];
     sprintf(buff, "mmaps/%03u.mmap", MapId);
     FILE* mmap = fopen(buff, "wb");
     if (!mmap)
     {
         printf("Could not create file %s. Check that you have write permissions to the destination folder and try again\n", buff);
         return;
     }
     CalculateTileBounds();
     dtNavMeshParams params;
     std::vector<BuilderThread*> Threads;
     if (TileMap->IsGlobalModel)
     {
         printf("Map %s ( %u ) is a WMO. Building with 1 thread.\n", Continent.c_str(), MapId);
         TileBuilder* builder = new TileBuilder(this, Continent, 0, 0, MapId);
         builder->AddGeometry(TileMap->Model, TileMap->ModelDefinition);
         uint8* nav = builder->BuildInstance(params);
         if (nav)
         {
             // Set some params for the navmesh
             dtMeshHeader* header = (dtMeshHeader*)nav;
             dtVcopy(params.orig, header->bmin);
             params.tileWidth = header->bmax[0] - header->bmin[0];
             params.tileHeight = header->bmax[2] - header->bmin[2];
             params.maxTiles = 1;
             params.maxPolys = header->polyCount;
             fwrite(&params, sizeof(dtNavMeshParams), 1, mmap);
             fclose(mmap);
             char buff[100];
             sprintf(buff, "mmaps/%03u%02i%02i.mmtile", MapId, 0, 0);
             FILE* f = fopen(buff, "wb");
             if (!f)
             {
                 printf("Could not create file %s. Check that you have write permissions to the destination folder and try again\n", buff);
                 return;
             }
             MmapTileHeader mheader;
             mheader.size = builder->DataSize;
             fwrite(&mheader, sizeof(MmapTileHeader), 1, f);
             fwrite(nav, sizeof(unsigned char), builder->DataSize, f);
             fclose(f);
         }
         dtFree(nav);
         delete builder;
     }
     else
     {
         params.maxPolys = 32768;
         params.maxTiles = 4096;
         rcVcopy(params.orig, Constants::Origin);
         params.tileHeight = Constants::TileSize;
         params.tileWidth = Constants::TileSize;
         fwrite(&params, sizeof(dtNavMeshParams), 1, mmap);
         fclose(mmap);
         for (uint32 i = 0; i < NumberOfThreads; ++i)
             Threads.push_back(new BuilderThread(this, params));
         printf("Map %s ( %u ) has %u tiles. Building them with %u threads\n", Continent.c_str(), MapId, uint32(TileMap->TileTable.size()), NumberOfThreads);
         for (std::vector<TilePos>::iterator itr = TileMap->TileTable.begin(); itr != TileMap->TileTable.end(); ++itr)
         {
             bool next = false;
             while (!next)
             {
                 for (std::vector<BuilderThread*>::iterator _th = Threads.begin(); _th != Threads.end(); ++_th)
                 {
                     if ((*_th)->Free)
                     {
                         (*_th)->SetData(itr->X, itr->Y, MapId, Continent);
                         (*_th)->activate();
                         next = true;
                         break;
                     }
                 }
                 // Wait for 20 seconds
                 std::this_thread::sleep_for(std::chrono::seconds(20));
             }
         }
     }
     Cache->Clear();
     // Free memory
     for (std::vector<BuilderThread*>::iterator _th = Threads.begin(); _th != Threads.end(); ++_th)
     {
         (*_th)->wait();
         delete *_th;
     }
 }
References TileBuilder::AddGeometry(), dtMeshHeader::bmax, dtMeshHeader::bmin, TileBuilder::BuildInstance(), Cache, CalculateTileBounds(), CacheClass::Clear(), Continent, TileBuilder::DataSize, dtFree(), dtVcopy(), f(), WDT::IsGlobalModel, MapId, dtNavMeshParams::maxPolys, dtNavMeshParams::maxTiles, WDT::Model, WDT::ModelDefinition, next(), NumberOfThreads, dtNavMeshParams::orig, Constants::Origin, dtMeshHeader::polyCount, printf(), rcVcopy(), G3D::units::seconds(), MmapTileHeader::size, sprintf(), dtNavMeshParams::tileHeight, TileMap, Constants::TileSize, WDT::TileTable, and dtNavMeshParams::tileWidth.
Referenced by ExtractMMaps().
CalculateTileBounds()
void ContinentBuilder::CalculateTileBounds ()
Definition at line 103 of file ContinentBuilder.cpp.
 {
     for (std::vector<TilePos>::iterator itr = TileMap->TileTable.begin(); itr != TileMap->TileTable.end(); ++itr)
     {
         tileXMax = std::max(itr->X, tileXMax);
         tileXMin = std::min(itr->X, tileXMin);
         tileYMax = std::max(itr->Y, tileYMax);
         tileYMin = std::min(itr->Y, tileYMin);
     }
     getTileBounds(tileXMax, tileYMax, nullptr, 0, bmin, bmax);
 }
References bmax, bmin, getTileBounds(), max, min, TileMap, WDT::TileTable, tileXMax, tileXMin, tileYMax, and tileYMin.
Referenced by Build().
getTileBounds()
void ContinentBuilder::getTileBounds (uint32 tileX, uint32 tileY, float * verts, int vertCount, float * bmin, float * bmax)
Definition at line 85 of file ContinentBuilder.cpp.
 {
     // this is for elevation
     if (verts && vertCount)
         rcCalcBounds(verts, vertCount, bmin, bmax);
     else
     {
         bmin[1] = FLT_MIN;
         bmax[1] = FLT_MAX;
     }
     // this is for width and depth
     bmax[0] = (32 - int(tileX)) * Constants::TileSize;
     bmax[2] = (32 - int(tileY)) * Constants::TileSize;
     bmin[0] = bmax[0] - Constants::TileSize;
     bmin[2] = bmax[2] - Constants::TileSize;
 }
References bmax, bmin, FLT_MAX, FLT_MIN, rcCalcBounds(), and Constants::TileSize.
Referenced by CalculateTileBounds().
Member Data Documentation
bmax
float ContinentBuilder::bmax[3]
Definition at line 36 of file ContinentBuilder.h.
Referenced by CalculateTileBounds(), and getTileBounds().
bmin
float ContinentBuilder::bmin[3]
Definition at line 35 of file ContinentBuilder.h.
Referenced by CalculateTileBounds(), and getTileBounds().
Continent
std::string ContinentBuilder::Continent private
Definition at line 38 of file ContinentBuilder.h.
Referenced by Build().
MapId
uint32 ContinentBuilder::MapId private
Definition at line 40 of file ContinentBuilder.h.
Referenced by Build().
NumberOfThreads
uint32 ContinentBuilder::NumberOfThreads private
Definition at line 41 of file ContinentBuilder.h.
Referenced by Build().
TileMap
WDT* ContinentBuilder::TileMap private
Definition at line 39 of file ContinentBuilder.h.
Referenced by Build(), and CalculateTileBounds().
tileXMax
int ContinentBuilder::tileXMax private
Definition at line 44 of file ContinentBuilder.h.
Referenced by CalculateTileBounds().
tileXMin
int ContinentBuilder::tileXMin private
Definition at line 42 of file ContinentBuilder.h.
Referenced by CalculateTileBounds().
tileYMax
int ContinentBuilder::tileYMax private
Definition at line 45 of file ContinentBuilder.h.
Referenced by CalculateTileBounds().
tileYMin
int ContinentBuilder::tileYMin private
Definition at line 43 of file ContinentBuilder.h.
Referenced by CalculateTileBounds().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/ContinentBuilder.h
src/tools/mesh_extractor/ContinentBuilder.cpp