Azerotcore-wotlk: Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck Class Reference
Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck (Unit const *funit, float range)
bool operator() (const Unit *u)
Private Attributes
Unit const * i_funit
float i_range
Detailed Description
Definition at line 846 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck()
Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck (Unit const * funit, float range) inline
Definition at line 849 of file GridNotifiers.h.
             : i_funit(funit), i_range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::operator() (const Unit * u) inline
Definition at line 852 of file GridNotifiers.h.
         {
             return u->IsAlive()
                    && i_funit->IsWithinDistInMap(u, i_range)
                    && !i_funit->IsFriendlyTo(u)
                    && i_funit->IsValidAttackTarget(u)
                    && !u->IsCritter()
                    && !u->IsTotem() //xinef: dont attack totems
                    /*&& i_funit->CanSeeOrDetect(u)*/; // pussywizard: already checked in IsValidAttackTarget(u)
         }
References i_funit, i_range, Unit::IsAlive(), Unit::IsCritter(), Unit::IsFriendlyTo(), Unit::IsTotem(), Unit::IsValidAttackTarget(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_funit
Unit const* Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::i_funit private
Definition at line 863 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::i_range private
Definition at line 864 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h