Azerotcore-wotlk: Acore::AllFriendlyCreaturesInGrid Class Reference
Acore::AllFriendlyCreaturesInGrid Class Reference
#include <GridNotifiers.h>
Public Member Functions
AllFriendlyCreaturesInGrid (Unit const *obj)
bool operator() (Unit *u)
Private Attributes
Unit const * unit
Detailed Description
Definition at line 1308 of file GridNotifiers.h.
Constructor & Destructor Documentation
AllFriendlyCreaturesInGrid()
Acore::AllFriendlyCreaturesInGrid::AllFriendlyCreaturesInGrid (Unit const * obj) inline
Definition at line 1311 of file GridNotifiers.h.
 : unit(obj) {}
Member Function Documentation
operator()()
bool Acore::AllFriendlyCreaturesInGrid::operator() (Unit * u) inline
Definition at line 1312 of file GridNotifiers.h.
         {
             if (u->IsAlive() && u->IsVisible() && u->IsFriendlyTo(unit))
                 return true;
             return false;
         }
References Unit::IsAlive(), Unit::IsFriendlyTo(), Unit::IsVisible(), and unit.
Member Data Documentation
unit
Unit const* Acore::AllFriendlyCreaturesInGrid::unit private
Definition at line 1320 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h