Azerotcore-wotlk: npc_mikhail Class Reference
npc_mikhail Class Reference
Public Member Functions
npc_mikhail ()
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 135 of file zone_wetlands.cpp.
Constructor & Destructor Documentation
npc_mikhail()
npc_mikhail::npc_mikhail () inline
Definition at line 138 of file zone_wetlands.cpp.
 : CreatureScript("npc_mikhail") { }
Member Function Documentation
OnQuestAccept()
bool npc_mikhail::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 140 of file zone_wetlands.cpp.
     {
         if (quest->GetQuestId() == QUEST_MISSING_DIPLO_PT11)
         {
             Creature* pSlim = creature->FindNearestCreature(NPC_TAPOKE_SLIM_JAHN, 25.0f);
             if (!pSlim)
                 return false;
             if (!pSlim->HasStealthAura())
                 pSlim->CastSpell(pSlim, SPELL_STEALTH, true);
             if (npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI* pEscortAI = CAST_AI(npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, pSlim->AI()))
                 pEscortAI->Start(false, false, player->GetGUID(), quest);
         }
         return false;
     }
References Creature::AI(), CAST_AI, Unit::CastSpell(), WorldObject::FindNearestCreature(), Object::GetGUID(), Quest::GetQuestId(), Unit::HasStealthAura(), NPC_TAPOKE_SLIM_JAHN, QUEST_MISSING_DIPLO_PT11, and SPELL_STEALTH.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_wetlands.cpp