Azerotcore-wotlk: WaypointMgr Class Reference
WaypointMgr Class Reference
#include <WaypointMgr.h>
Public Member Functions
void ReloadPath (uint32 id)
void Load ()
WaypointPath const * GetPath (uint32 id) const
Static Public Member Functions
static WaypointMgr * instance ()
Private Member Functions
WaypointMgr ()
~WaypointMgr ()
Private Attributes
WaypointPathContainer _waypointStore
Detailed Description
Definition at line 48 of file WaypointMgr.h.
Constructor & Destructor Documentation
WaypointMgr()
WaypointMgr::WaypointMgr () private
Definition at line 23 of file WaypointMgr.cpp.
 {
 }
~WaypointMgr()
WaypointMgr::~WaypointMgr () private
Definition at line 27 of file WaypointMgr.cpp.
 {
     for (WaypointPathContainer::iterator itr = _waypointStore.begin(); itr != _waypointStore.end(); ++itr)
     {
         for (WaypointPath::const_iterator it = itr->second.begin(); it != itr->second.end(); ++it)
             delete *it;
         itr->second.clear();
     }
     _waypointStore.clear();
 }
References _waypointStore.
Member Function Documentation
GetPath()
WaypointPath const* WaypointMgr::GetPath (uint32 id) const inline
Definition at line 60 of file WaypointMgr.h.
     {
         WaypointPathContainer::const_iterator itr = _waypointStore.find(id);
         if (itr != _waypointStore.end())
             return &itr->second;
         return nullptr;
     }
References _waypointStore.
instance()
WaypointMgr * WaypointMgr::instance () static
Definition at line 40 of file WaypointMgr.cpp.
 {
     static WaypointMgr instance;
     return &instance;
 }
Load()
void WaypointMgr::Load ()
Definition at line 46 of file WaypointMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     //                                                0    1         2           3          4            5           6        7      8           9
     QueryResult result = WorldDatabase.Query("SELECT id, point, position_x, position_y, position_z, orientation, move_type, delay, action, action_chance FROM waypoint_data ORDER BY id, point");
     if (!result)
     {
         LOG_ERROR("sql.sql", ">> Loaded 0 waypoints. DB table `waypoint_data` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         WaypointData* wp = new WaypointData();
         uint32 pathId = fields[0].GetUInt32();
         WaypointPath& path = _waypointStore[pathId];
         float x = fields[2].GetFloat();
         float y = fields[3].GetFloat();
         float z = fields[4].GetFloat();
         float o = fields[5].GetFloat();
         Acore::NormalizeMapCoord(x);
         Acore::NormalizeMapCoord(y);
         wp->id = fields[1].GetUInt32();
         wp->x = x;
         wp->y = y;
         wp->z = z;
         wp->orientation = o;
         wp->move_type = fields[6].GetUInt32();
         if (wp->move_type >= WAYPOINT_MOVE_TYPE_MAX)
         {
             //TC_LOG_ERROR("sql.sql", "Waypoint %u in waypoint_data has invalid move_type, ignoring", wp->id);
             delete wp;
             continue;
         }
         wp->delay = fields[7].GetUInt32();
         wp->event_id = fields[8].GetUInt32();
         wp->event_chance = fields[9].GetInt16();
         path.push_back(wp);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u waypoints in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _waypointStore, count(), WaypointData::delay, WaypointData::event_chance, WaypointData::event_id, Field::GetFloat(), Field::GetInt16(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), WaypointData::id, LOG_ERROR, LOG_INFO, WaypointData::move_type, Acore::NormalizeMapCoord(), WaypointData::orientation, WAYPOINT_MOVE_TYPE_MAX, WorldDatabase, G3D::x, WaypointData::x, G3D::y, WaypointData::y, G3D::z, and WaypointData::z.
ReloadPath()
void WaypointMgr::ReloadPath (uint32 id)
Definition at line 104 of file WaypointMgr.cpp.
 {
     WaypointPathContainer::iterator itr = _waypointStore.find(id);
     if (itr != _waypointStore.end())
     {
         for (WaypointPath::const_iterator it = itr->second.begin(); it != itr->second.end(); ++it)
             delete *it;
         _waypointStore.erase(itr);
     }
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_WAYPOINT_DATA_BY_ID);
     stmt->setUInt32(0, id);
     PreparedQueryResult result = WorldDatabase.Query(stmt);
     if (!result)
         return;
     WaypointPath& path = _waypointStore[id];
     do
     {
         Field* fields = result->Fetch();
         WaypointData* wp = new WaypointData();
         float x = fields[1].GetFloat();
         float y = fields[2].GetFloat();
         float z = fields[3].GetFloat();
         float o = fields[4].GetFloat();
         Acore::NormalizeMapCoord(x);
         Acore::NormalizeMapCoord(y);
         wp->id = fields[0].GetUInt32();
         wp->x = x;
         wp->y = y;
         wp->z = z;
         wp->orientation = o;
         wp->move_type = fields[5].GetUInt32();
         if (wp->move_type >= WAYPOINT_MOVE_TYPE_MAX)
         {
             //TC_LOG_ERROR("sql.sql", "Waypoint %u in waypoint_data has invalid move_type, ignoring", wp->id);
             delete wp;
             continue;
         }
         wp->delay = fields[6].GetUInt32();
         wp->event_id = fields[7].GetUInt32();
         wp->event_chance = fields[8].GetUInt8();
         path.push_back(wp);
     } while (result->NextRow());
 }
References _waypointStore, WaypointData::delay, WaypointData::event_chance, WaypointData::event_id, Field::GetFloat(), Field::GetUInt32(), Field::GetUInt8(), WaypointData::id, WaypointData::move_type, Acore::NormalizeMapCoord(), WaypointData::orientation, PreparedStatementBase::setUInt32(), WAYPOINT_MOVE_TYPE_MAX, WORLD_SEL_WAYPOINT_DATA_BY_ID, WorldDatabase, G3D::x, WaypointData::x, G3D::y, WaypointData::y, G3D::z, and WaypointData::z.
Member Data Documentation
_waypointStore
WaypointPathContainer WaypointMgr::_waypointStore private
Definition at line 73 of file WaypointMgr.h.
Referenced by GetPath(), Load(), ReloadPath(), and ~WaypointMgr().
The documentation for this class was generated from the following files:
src/server/game/Movement/Waypoints/WaypointMgr.h
src/server/game/Movement/Waypoints/WaypointMgr.cpp