Azerotcore-wotlk: WorldSocketMgr Class Reference
WorldSocketMgr Class Reference
User to World Communication
Manages all sockets connected to peers and network threads.
#include <WorldSocketMgr.h>
Public Member Functions
bool StartWorldNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int networkThreads)
Start network, listen at address:port .
void StopNetwork () override
Stops all network threads, It will wait for all running threads .
void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex) override
std::size_t GetApplicationSendBufferSize () const
Public Member Functions inherited from SocketMgr< WorldSocket >
virtual ~SocketMgr ()
virtual bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount)
void Wait ()
int32 GetNetworkThreadCount () const
uint32 SelectThreadWithMinConnections () const
std::pair< tcp::socket *, uint32 > GetSocketForAccept ()
Static Public Member Functions
static WorldSocketMgr & Instance ()
Protected Member Functions
WorldSocketMgr ()
NetworkThread< WorldSocket > * CreateThreads () const override
Protected Member Functions inherited from SocketMgr< WorldSocket >
SocketMgr ()
Static Protected Member Functions
static void OnSocketAccept (tcp::socket &&sock, uint32 threadIndex)
Private Types
typedef SocketMgr< WorldSocket > BaseSocketMgr
Private Attributes
int32 _socketSystemSendBufferSize
int32 _socketApplicationSendBufferSize
bool _tcpNoDelay
Additional Inherited Members
Protected Attributes inherited from SocketMgr< WorldSocket >
AsyncAcceptor * _acceptor
NetworkThread< WorldSocket > * _threads
int32 _threadCount
Detailed Description
Manages all sockets connected to peers and network threads.
Definition at line 31 of file WorldSocketMgr.h.
Member Typedef Documentation
BaseSocketMgr
typedef SocketMgr<WorldSocket> WorldSocketMgr::BaseSocketMgr private
Definition at line 33 of file WorldSocketMgr.h.
Constructor & Destructor Documentation
WorldSocketMgr()
WorldSocketMgr::WorldSocketMgr () protected
Definition at line 40 of file WorldSocketMgr.cpp.
                                :
     BaseSocketMgr(), _socketSystemSendBufferSize(-1), _socketApplicationSendBufferSize(65536), _tcpNoDelay(true)
 {
 }
Member Function Documentation
CreateThreads()
NetworkThread< WorldSocket > * WorldSocketMgr::CreateThreads () const override protected virtual
Implements SocketMgr< WorldSocket >.
Definition at line 115 of file WorldSocketMgr.cpp.
 {
     return new WorldSocketThread[GetNetworkThreadCount()];
 }
References SocketMgr< WorldSocket >::GetNetworkThreadCount().
GetApplicationSendBufferSize()
std::size_t WorldSocketMgr::GetApplicationSendBufferSize () const inline
Definition at line 46 of file WorldSocketMgr.h.
 { return _socketApplicationSendBufferSize; }
Instance()
WorldSocketMgr & WorldSocketMgr::Instance () static
Definition at line 45 of file WorldSocketMgr.cpp.
 {
     static WorldSocketMgr instance;
     return instance;
 }
OnSocketAccept()
static void WorldSocketMgr::OnSocketAccept (tcp::socket && sock, uint32 threadIndex) inline static protected
Definition at line 53 of file WorldSocketMgr.h.
     {
         Instance().OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
     }
References Instance.
Referenced by StartWorldNetwork().
OnSocketOpen()
void WorldSocketMgr::OnSocketOpen (tcp::socket && sock, uint32 threadIndex) override virtual
Reimplemented from SocketMgr< WorldSocket >.
Definition at line 84 of file WorldSocketMgr.cpp.
 {
     // set some options here
     if (_socketSystemSendBufferSize >= 0)
     {
         boost::system::error_code err;
         sock.set_option(boost::asio::socket_base::send_buffer_size(_socketSystemSendBufferSize), err);
         if (err && err != boost::system::errc::not_supported)
         {
             LOG_ERROR("network", "WorldSocketMgr::OnSocketOpen sock.set_option(boost::asio::socket_base::send_buffer_size) err = %s", err.message().c_str());
             return;
         }
     }
     // Set TCP_NODELAY.
     if (_tcpNoDelay)
     {
         boost::system::error_code err;
         sock.set_option(boost::asio::ip::tcp::no_delay(true), err);
         if (err)
         {
             LOG_ERROR("network", "WorldSocketMgr::OnSocketOpen sock.set_option(boost::asio::ip::tcp::no_delay) err = %s", err.message().c_str());
             return;
         }
     }
     BaseSocketMgr::OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
 }
References _socketSystemSendBufferSize, _tcpNoDelay, LOG_ERROR, and SocketMgr< WorldSocket >::OnSocketOpen().
StartWorldNetwork()
bool WorldSocketMgr::StartWorldNetwork (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port, int networkThreads)
Start network, listen at address:port .
Definition at line 51 of file WorldSocketMgr.cpp.
 {
     _tcpNoDelay = sConfigMgr->GetOption<bool>("Network.TcpNodelay", true);
     int const max_connections = ACORE_MAX_LISTEN_CONNECTIONS;
     LOG_DEBUG("network", "Max allowed socket connections %d", max_connections);
     // -1 means use default
     _socketSystemSendBufferSize = sConfigMgr->GetOption<int32>("Network.OutKBuff", -1);
     _socketApplicationSendBufferSize = sConfigMgr->GetOption<int32>("Network.OutUBuff", 65536);
     if (_socketApplicationSendBufferSize <= 0)
     {
         LOG_ERROR("network", "Network.OutUBuff is wrong in your config file");
         return false;
     }
     if (!BaseSocketMgr::StartNetwork(ioContext, bindIp, port, threadCount))
         return false;
     _acceptor->AsyncAcceptWithCallback<&WorldSocketMgr::OnSocketAccept>();
     sScriptMgr->OnNetworkStart();
     return true;
 }
References SocketMgr< WorldSocket >::_acceptor, _socketApplicationSendBufferSize, _socketSystemSendBufferSize, _tcpNoDelay, ACORE_MAX_LISTEN_CONNECTIONS, AsyncAcceptor::AsyncAcceptWithCallback(), LOG_DEBUG, LOG_ERROR, OnSocketAccept(), sConfigMgr, sScriptMgr, and SocketMgr< WorldSocket >::StartNetwork().
StopNetwork()
void WorldSocketMgr::StopNetwork () override virtual
Stops all network threads, It will wait for all running threads .
Reimplemented from SocketMgr< WorldSocket >.
Definition at line 77 of file WorldSocketMgr.cpp.
 {
     BaseSocketMgr::StopNetwork();
     sScriptMgr->OnNetworkStop();
 }
References sScriptMgr, and SocketMgr< WorldSocket >::StopNetwork().
Member Data Documentation
_socketApplicationSendBufferSize
int32 WorldSocketMgr::_socketApplicationSendBufferSize private
Definition at line 60 of file WorldSocketMgr.h.
Referenced by StartWorldNetwork().
_socketSystemSendBufferSize
int32 WorldSocketMgr::_socketSystemSendBufferSize private
Definition at line 59 of file WorldSocketMgr.h.
Referenced by OnSocketOpen(), and StartWorldNetwork().
_tcpNoDelay
bool WorldSocketMgr::_tcpNoDelay private
Definition at line 61 of file WorldSocketMgr.h.
Referenced by OnSocketOpen(), and StartWorldNetwork().
The documentation for this class was generated from the following files:
src/server/game/Server/WorldSocketMgr.h
src/server/game/Server/WorldSocketMgr.cpp