Azerotcore-wotlk: npc_koltira_deathweaver::npc_koltira_deathweaverAI Struct Reference
npc_koltira_deathweaver::npc_koltira_deathweaverAI Struct Reference
Public Member Functions
npc_koltira_deathweaverAI (Creature *creature)
void Reset () override
void EnterEvadeMode () override
void AttackStart (Unit *who) override
void WaypointReached (uint32 waypointId) override
void JustSummoned (Creature *summoned) override
void SummonAcolyte (uint32 uiAmount)
void UpdateAI (uint32 uiDiff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 m_uiWave
uint32 m_uiWave_Timer
ObjectGuid m_uiValrothGUID
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 217 of file chapter2.cpp.
Constructor & Destructor Documentation
npc_koltira_deathweaverAI()
npc_koltira_deathweaver::npc_koltira_deathweaverAI::npc_koltira_deathweaverAI (Creature * creature) inline
Definition at line 219 of file chapter2.cpp.
                                                       : npc_escortAI(creature), summons(me)
         {
             me->SetReactState(REACT_DEFENSIVE);
         }
References ScriptedAI::me, REACT_DEFENSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::AttackStart (Unit * who) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 263 of file chapter2.cpp.
         {
             if (HasEscortState(STATE_ESCORT_PAUSED))
                 return;
             npc_escortAI::AttackStart(who);
         }
References npc_escortAI::AttackStart(), npc_escortAI::HasEscortState(), and STATE_ESCORT_PAUSED.
EnterEvadeMode()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode () inline override virtual
Reimplemented from npc_escortAI.
Definition at line 243 of file chapter2.cpp.
         {
             me->DeleteThreatList();
             me->CombatStop(false);
             me->SetLootRecipient(nullptr);
             if (HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 AddEscortState(STATE_ESCORT_RETURNING);
                 ReturnToLastPoint();
                 LOG_DEBUG("scripts.ai", "EscortAI has left combat and is now returning to last point");
             }
             else
             {
                 me->GetMotionMaster()->MoveTargetedHome();
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                 Reset();
             }
         }
References npc_escortAI::AddEscortState(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), npc_escortAI::HasEscortState(), LOG_DEBUG, ScriptedAI::me, MotionMaster::MoveTargetedHome(), Reset(), npc_escortAI::ReturnToLastPoint(), Object::SetFlag(), Creature::SetLootRecipient(), STATE_ESCORT_ESCORTING, STATE_ESCORT_RETURNING, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
JustSummoned()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 307 of file chapter2.cpp.
         {
             if (Player* player = GetPlayerForEscort())
                 summoned->AI()->AttackStart(player);
             if (summoned->GetEntry() == NPC_HIGH_INQUISITOR_VALROTH)
                 m_uiValrothGUID = summoned->GetGUID();
             summoned->AddThreat(me, 0.0f);
             summoned->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             summons.Summon(summoned);
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), Object::GetGUID(), npc_escortAI::GetPlayerForEscort(), m_uiValrothGUID, ScriptedAI::me, NPC_HIGH_INQUISITOR_VALROTH, Object::RemoveFlag(), SummonList::Summon(), summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Reset()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 229 of file chapter2.cpp.
         {
             if (!HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 m_uiWave = 0;
                 m_uiWave_Timer = 3000;
                 m_uiValrothGUID.Clear();
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->LoadEquipment(0, true);
                 me->RemoveAllAuras();
                 summons.DespawnAll();
             }
         }
References ObjectGuid::Clear(), SummonList::DespawnAll(), npc_escortAI::HasEscortState(), Creature::LoadEquipment(), m_uiValrothGUID, m_uiWave, m_uiWave_Timer, ScriptedAI::me, Unit::RemoveAllAuras(), Object::SetFlag(), STATE_ESCORT_ESCORTING, summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by EnterEvadeMode().
SummonAcolyte()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::SummonAcolyte (uint32 uiAmount) inline
Definition at line 320 of file chapter2.cpp.
         {
             for (uint32 i = 0; i < uiAmount; ++i)
                 me->SummonCreature(NPC_CRIMSON_ACOLYTE, 1642.329f, -6045.818f, 127.583f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 5000);
         }
References ScriptedAI::me, NPC_CRIMSON_ACOLYTE, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
Referenced by UpdateAI().
UpdateAI()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI (uint32 uiDiff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 326 of file chapter2.cpp.
         {
             npc_escortAI::UpdateAI(uiDiff);
             if (HasEscortState(STATE_ESCORT_PAUSED))
             {
                 if (m_uiWave_Timer <= uiDiff)
                 {
                     switch (m_uiWave)
                     {
                         case 0:
                             Talk(SAY_BREAKOUT3);
                             SummonAcolyte(3);
                             m_uiWave_Timer = 20000;
                             break;
                         case 1:
                             Talk(SAY_BREAKOUT4);
                             SummonAcolyte(3);
                             m_uiWave_Timer = 20000;
                             break;
                         case 2:
                             Talk(SAY_BREAKOUT5);
                             SummonAcolyte(4);
                             m_uiWave_Timer = 20000;
                             break;
                         case 3:
                             Talk(SAY_BREAKOUT6);
                             me->SummonCreature(NPC_HIGH_INQUISITOR_VALROTH, 1642.329f, -6045.818f, 127.583f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 1000);
                             m_uiWave_Timer = 1000;
                             break;
                         case 4:
{
                                 Creature* temp = ObjectAccessor::GetCreature(*me, m_uiValrothGUID);
                                 if (!temp || !temp->IsAlive())
{
                                     Talk(SAY_BREAKOUT8);
                                     m_uiWave_Timer = 5000;
                                 }
                                 else
{
                                     // xinef: despawn check
                                     Player* player = GetPlayerForEscort();
                                     if (!player || me->GetDistance(player) > 60.0f)
{
                                         me->DespawnOrUnsummon();
                                         return;
                                     }
                                     m_uiWave_Timer = 2500;
                                     return;                         //return, we don't want m_uiWave to increment now
                                 }
                                 break;
                             }
                         case 5:
                             Talk(SAY_BREAKOUT9);
                             me->RemoveAurasDueToSpell(SPELL_ANTI_MAGIC_ZONE);
                             // i do not know why the armor will also be removed
                             m_uiWave_Timer = 2500;
                             break;
                         case 6:
                             Talk(SAY_BREAKOUT10);
                             SetEscortPaused(false);
                             break;
                     }
                     ++m_uiWave;
                 }
                 else
                     m_uiWave_Timer -= uiDiff;
             }
         }
References Creature::DespawnOrUnsummon(), ObjectAccessor::GetCreature(), WorldObject::GetDistance(), npc_escortAI::GetPlayerForEscort(), npc_escortAI::HasEscortState(), Unit::IsAlive(), m_uiValrothGUID, m_uiWave, m_uiWave_Timer, ScriptedAI::me, NPC_HIGH_INQUISITOR_VALROTH, Unit::RemoveAurasDueToSpell(), SAY_BREAKOUT10, SAY_BREAKOUT3, SAY_BREAKOUT4, SAY_BREAKOUT5, SAY_BREAKOUT6, SAY_BREAKOUT8, SAY_BREAKOUT9, npc_escortAI::SetEscortPaused(), SPELL_ANTI_MAGIC_ZONE, STATE_ESCORT_PAUSED, SummonAcolyte(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and npc_escortAI::UpdateAI().
WaypointReached()
void npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 271 of file chapter2.cpp.
         {
             switch (waypointId)
             {
                 case 0:
                     Talk(SAY_BREAKOUT1);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     break;
                 case 1:
                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                     break;
                 case 2:
                     me->SetStandState(UNIT_STAND_STATE_STAND);
                     //me->UpdateEntry(NPC_KOLTIRA_ALT); //unclear if we must update or not
                     DoCast(me, SPELL_KOLTIRA_TRANSFORM);
                     me->LoadEquipment();
                     break;
                 case 3:
                     SetEscortPaused(true);
                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                     Talk(SAY_BREAKOUT2);
                     DoCast(me, SPELL_ANTI_MAGIC_ZONE);  // cast again that makes bubble up
                     break;
                 case 4:
                     me->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_ALL, false);
                     SetRun(true);
                     break;
                 case 9:
                     me->Mount(MODEL_DEATH_KNIGHT_MOUNT);
                     break;
                 case 10:
                     me->Dismount();
                     break;
             }
         }
References Unit::ApplySpellImmune(), Unit::Dismount(), UnitAI::DoCast(), IMMUNITY_DAMAGE, Creature::LoadEquipment(), ScriptedAI::me, MODEL_DEATH_KNIGHT_MOUNT, Unit::Mount(), Object::RemoveFlag(), SAY_BREAKOUT1, SAY_BREAKOUT2, npc_escortAI::SetEscortPaused(), npc_escortAI::SetRun(), Unit::SetStandState(), SPELL_ANTI_MAGIC_ZONE, SPELL_KOLTIRA_TRANSFORM, SPELL_SCHOOL_MASK_ALL, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STAND_STATE_KNEEL, and UNIT_STAND_STATE_STAND.
Member Data Documentation
m_uiValrothGUID
ObjectGuid npc_koltira_deathweaver::npc_koltira_deathweaverAI::m_uiValrothGUID
Definition at line 226 of file chapter2.cpp.
Referenced by JustSummoned(), Reset(), and UpdateAI().
m_uiWave
uint32 npc_koltira_deathweaver::npc_koltira_deathweaverAI::m_uiWave
Definition at line 224 of file chapter2.cpp.
Referenced by Reset(), and UpdateAI().
m_uiWave_Timer
uint32 npc_koltira_deathweaver::npc_koltira_deathweaverAI::m_uiWave_Timer
Definition at line 225 of file chapter2.cpp.
Referenced by Reset(), and UpdateAI().
summons
SummonList npc_koltira_deathweaver::npc_koltira_deathweaverAI::summons
Definition at line 227 of file chapter2.cpp.
Referenced by JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp