Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/hash.h File Reference
hash.h File Reference
#include "jemalloc/internal/assert.h"
Functions
static uint32_t hash_rotl_32 (uint32_t x, int8_t r)
static uint64_t hash_rotl_64 (uint64_t x, int8_t r)
static uint32_t hash_get_block_32 (const uint32_t *p, int i)
static uint64_t hash_get_block_64 (const uint64_t *p, int i)
static uint32_t hash_fmix_32 (uint32_t h)
static uint64_t hash_fmix_64 (uint64_t k)
static uint32_t hash_x86_32 (const void *key, int len, uint32_t seed)
static void hash_x86_128 (const void *key, const int len, uint32_t seed, uint64_t r_out[2])
static void hash_x64_128 (const void *key, const int len, const uint32_t seed, uint64_t r_out[2])
static void hash (const void *key, size_t len, const uint32_t seed, size_t r_hash[2])
Function Documentation
hash()
static void hash (const void * key, size_t len, const uint32_t seed, size_t r_hash[2]) inline static
Definition at line 304 of file hash.h.
{
     assert(len <= INT_MAX); /* Unfortunate implementation limitation. */
 #if (LG_SIZEOF_PTR == 3 && !defined(JEMALLOC_BIG_ENDIAN))
     hash_x64_128(key, (int)len, seed, (uint64_t *)r_hash);
 #else
     {
         uint64_t hashes[2];
         hash_x86_128(key, (int)len, seed, hashes);
         r_hash[0] = (size_t)hashes[0];
         r_hash[1] = (size_t)hashes[1];
     }
 #endif
 }
References assert(), hash_x64_128(), and hash_x86_128().
Referenced by _my_hash_init(), argon2_hash(), argon2_verify_ctx(), argon2d_hash_raw(), argon2d_verify_ctx(), argon2i_hash_raw(), argon2i_verify_ctx(), argon2id_hash_raw(), argon2id_verify_ctx(), SecretMgr::AttemptTransition(), Warden::BuildChecksum(), calc_hash(), ckh_new(), ckh_pointer_hash(), ckh_string_hash(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf(), hash_key(), hashcmp(), HashTrait< G3D::uint128 >::hashCode(), initialize_bucket(), lf_hash_delete(), lf_hash_destroy(), lf_hash_init(), lf_hash_insert(), lf_hash_search(), mutex_pool_mutex(), my_calc_hash(), my_hash_check(), my_hash_delete(), my_hash_element(), my_hash_first(), my_hash_first_from_hash_value(), my_hash_free(), my_hash_free_elements(), my_hash_key(), my_hash_next(), my_hash_rec_mask(), my_hash_replace(), my_hash_reset(), my_hash_search(), my_hash_search_using_hash_value(), my_hash_update(), prof_bt_hash(), prof_thr_node_hash(), rec_hashnr(), safe_hash_change(), safe_hash_free(), safe_hash_init(), safe_hash_search(), safe_hash_set(), G3D::superFastHash(), UpdateFetcher::Update(), and Acore::Crypto::Argon2::Verify().
hash_fmix_32()
static uint32_t hash_fmix_32 (uint32_t h) inline static
Definition at line 51 of file hash.h.
{
     h ^= h >> 16;
     h *= 0x85ebca6b;
     h ^= h >> 13;
     h *= 0xc2b2ae35;
     h ^= h >> 16;
     return h;
 }
Referenced by hash_x86_128(), and hash_x86_32().
hash_fmix_64()
static uint64_t hash_fmix_64 (uint64_t k) inline static
Definition at line 62 of file hash.h.
{
     k ^= k >> 33;
     k *= KQU(0xff51afd7ed558ccd);
     k ^= k >> 33;
     k *= KQU(0xc4ceb9fe1a85ec53);
     k ^= k >> 33;
     return k;
 }
References KQU.
Referenced by hash_x64_128().
hash_get_block_32()
static uint32_t hash_get_block_32 (const uint32_t * p, int i) inline static
Definition at line 25 of file hash.h.
{
     /* Handle unaligned read. */
     if (unlikely((uintptr_t)p & (sizeof(uint32_t)-1)) != 0) {
         uint32_t ret;
         memcpy(&ret, (uint8_t *)(p + i), sizeof(uint32_t));
         return ret;
     }
     return p[i];
 }
References memcpy, ret, and unlikely.
Referenced by hash_x86_128(), and hash_x86_32().
hash_get_block_64()
static uint64_t hash_get_block_64 (const uint64_t * p, int i) inline static
Definition at line 38 of file hash.h.
{
     /* Handle unaligned read. */
     if (unlikely((uintptr_t)p & (sizeof(uint64_t)-1)) != 0) {
         uint64_t ret;
         memcpy(&ret, (uint8_t *)(p + i), sizeof(uint64_t));
         return ret;
     }
     return p[i];
 }
References memcpy, ret, and unlikely.
Referenced by hash_x64_128().
hash_rotl_32()
static uint32_t hash_rotl_32 (uint32_t x, int8_t r) inline static
Definition at line 15 of file hash.h.
{
     return ((x << r) | (x >> (32 - r)));
 }
References G3D::x.
Referenced by hash_x86_128(), and hash_x86_32().
hash_rotl_64()
static uint64_t hash_rotl_64 (uint64_t x, int8_t r) inline static
Definition at line 20 of file hash.h.
{
     return ((x << r) | (x >> (64 - r)));
 }
References G3D::x.
Referenced by hash_x64_128().
hash_x64_128()
static void hash_x64_128 (const void * key, const int len, const uint32_t seed, uint64_t r_out[2]) inline static
Definition at line 225 of file hash.h.
{
     const uint8_t *data = (const uint8_t *) key;
     const int nblocks = len / 16;
     uint64_t h1 = seed;
     uint64_t h2 = seed;
     const uint64_t c1 = KQU(0x87c37b91114253d5);
     const uint64_t c2 = KQU(0x4cf5ad432745937f);
     /* body */
     {
         const uint64_t *blocks = (const uint64_t *) (data);
         int i;
         for (i = 0; i < nblocks; i++) {
             uint64_t k1 = hash_get_block_64(blocks, i*2 + 0);
             uint64_t k2 = hash_get_block_64(blocks, i*2 + 1);
             k1 *= c1; k1 = hash_rotl_64(k1, 31); k1 *= c2; h1 ^= k1;
             h1 = hash_rotl_64(h1, 27); h1 += h2;
             h1 = h1*5 + 0x52dce729;
             k2 *= c2; k2 = hash_rotl_64(k2, 33); k2 *= c1; h2 ^= k2;
             h2 = hash_rotl_64(h2, 31); h2 += h1;
             h2 = h2*5 + 0x38495ab5;
         }
     }
     /* tail */
     {
         const uint8_t *tail = (const uint8_t*)(data + nblocks*16);
         uint64_t k1 = 0;
         uint64_t k2 = 0;
         switch (len & 15) {
         case 15: k2 ^= ((uint64_t)(tail[14])) << 48; JEMALLOC_FALLTHROUGH
         case 14: k2 ^= ((uint64_t)(tail[13])) << 40; JEMALLOC_FALLTHROUGH
         case 13: k2 ^= ((uint64_t)(tail[12])) << 32; JEMALLOC_FALLTHROUGH
         case 12: k2 ^= ((uint64_t)(tail[11])) << 24; JEMALLOC_FALLTHROUGH
         case 11: k2 ^= ((uint64_t)(tail[10])) << 16; JEMALLOC_FALLTHROUGH
         case 10: k2 ^= ((uint64_t)(tail[ 9])) << 8;  JEMALLOC_FALLTHROUGH
         case  9: k2 ^= ((uint64_t)(tail[ 8])) << 0;
             k2 *= c2; k2 = hash_rotl_64(k2, 33); k2 *= c1; h2 ^= k2;
             JEMALLOC_FALLTHROUGH
         case  8: k1 ^= ((uint64_t)(tail[ 7])) << 56; JEMALLOC_FALLTHROUGH
         case  7: k1 ^= ((uint64_t)(tail[ 6])) << 48; JEMALLOC_FALLTHROUGH
         case  6: k1 ^= ((uint64_t)(tail[ 5])) << 40; JEMALLOC_FALLTHROUGH
         case  5: k1 ^= ((uint64_t)(tail[ 4])) << 32; JEMALLOC_FALLTHROUGH
         case  4: k1 ^= ((uint64_t)(tail[ 3])) << 24; JEMALLOC_FALLTHROUGH
         case  3: k1 ^= ((uint64_t)(tail[ 2])) << 16; JEMALLOC_FALLTHROUGH
         case  2: k1 ^= ((uint64_t)(tail[ 1])) << 8;  JEMALLOC_FALLTHROUGH
         case  1: k1 ^= ((uint64_t)(tail[ 0])) << 0;
             k1 *= c1; k1 = hash_rotl_64(k1, 31); k1 *= c2; h1 ^= k1;
         }
     }
     /* finalization */
     h1 ^= len; h2 ^= len;
     h1 += h2;
     h2 += h1;
     h1 = hash_fmix_64(h1);
     h2 = hash_fmix_64(h2);
     h1 += h2;
     h2 += h1;
     r_out[0] = h1;
     r_out[1] = h2;
 }
References hash_fmix_64(), hash_get_block_64(), hash_rotl_64(), JEMALLOC_FALLTHROUGH, and KQU.
Referenced by hash().
hash_x86_128()
static void hash_x86_128 (const void * key, const int len, uint32_t seed, uint64_t r_out[2]) inline static
Definition at line 123 of file hash.h.
{
     const uint8_t * data = (const uint8_t *) key;
     const int nblocks = len / 16;
     uint32_t h1 = seed;
     uint32_t h2 = seed;
     uint32_t h3 = seed;
     uint32_t h4 = seed;
     const uint32_t c1 = 0x239b961b;
     const uint32_t c2 = 0xab0e9789;
     const uint32_t c3 = 0x38b34ae5;
     const uint32_t c4 = 0xa1e38b93;
     /* body */
     {
         const uint32_t *blocks = (const uint32_t *) (data + nblocks*16);
         int i;
         for (i = -nblocks; i; i++) {
             uint32_t k1 = hash_get_block_32(blocks, i*4 + 0);
             uint32_t k2 = hash_get_block_32(blocks, i*4 + 1);
             uint32_t k3 = hash_get_block_32(blocks, i*4 + 2);
             uint32_t k4 = hash_get_block_32(blocks, i*4 + 3);
             k1 *= c1; k1 = hash_rotl_32(k1, 15); k1 *= c2; h1 ^= k1;
             h1 = hash_rotl_32(h1, 19); h1 += h2;
             h1 = h1*5 + 0x561ccd1b;
             k2 *= c2; k2 = hash_rotl_32(k2, 16); k2 *= c3; h2 ^= k2;
             h2 = hash_rotl_32(h2, 17); h2 += h3;
             h2 = h2*5 + 0x0bcaa747;
             k3 *= c3; k3 = hash_rotl_32(k3, 17); k3 *= c4; h3 ^= k3;
             h3 = hash_rotl_32(h3, 15); h3 += h4;
             h3 = h3*5 + 0x96cd1c35;
             k4 *= c4; k4 = hash_rotl_32(k4, 18); k4 *= c1; h4 ^= k4;
             h4 = hash_rotl_32(h4, 13); h4 += h1;
             h4 = h4*5 + 0x32ac3b17;
         }
     }
     /* tail */
     {
         const uint8_t *tail = (const uint8_t *) (data + nblocks*16);
         uint32_t k1 = 0;
         uint32_t k2 = 0;
         uint32_t k3 = 0;
         uint32_t k4 = 0;
         switch (len & 15) {
         case 15: k4 ^= tail[14] << 16; JEMALLOC_FALLTHROUGH
         case 14: k4 ^= tail[13] << 8; JEMALLOC_FALLTHROUGH
         case 13: k4 ^= tail[12] << 0;
             k4 *= c4; k4 = hash_rotl_32(k4, 18); k4 *= c1; h4 ^= k4;
       JEMALLOC_FALLTHROUGH
         case 12: k3 ^= tail[11] << 24; JEMALLOC_FALLTHROUGH
         case 11: k3 ^= tail[10] << 16; JEMALLOC_FALLTHROUGH
         case 10: k3 ^= tail[ 9] << 8; JEMALLOC_FALLTHROUGH
         case  9: k3 ^= tail[ 8] << 0;
              k3 *= c3; k3 = hash_rotl_32(k3, 17); k3 *= c4; h3 ^= k3;
          JEMALLOC_FALLTHROUGH
         case  8: k2 ^= tail[ 7] << 24; JEMALLOC_FALLTHROUGH
         case  7: k2 ^= tail[ 6] << 16; JEMALLOC_FALLTHROUGH
         case  6: k2 ^= tail[ 5] << 8; JEMALLOC_FALLTHROUGH
         case  5: k2 ^= tail[ 4] << 0;
             k2 *= c2; k2 = hash_rotl_32(k2, 16); k2 *= c3; h2 ^= k2;
       JEMALLOC_FALLTHROUGH
         case  4: k1 ^= tail[ 3] << 24; JEMALLOC_FALLTHROUGH
         case  3: k1 ^= tail[ 2] << 16; JEMALLOC_FALLTHROUGH
         case  2: k1 ^= tail[ 1] << 8; JEMALLOC_FALLTHROUGH
         case  1: k1 ^= tail[ 0] << 0;
             k1 *= c1; k1 = hash_rotl_32(k1, 15); k1 *= c2; h1 ^= k1;
       JEMALLOC_FALLTHROUGH
         }
     }
     /* finalization */
     h1 ^= len; h2 ^= len; h3 ^= len; h4 ^= len;
     h1 += h2; h1 += h3; h1 += h4;
     h2 += h1; h3 += h1; h4 += h1;
     h1 = hash_fmix_32(h1);
     h2 = hash_fmix_32(h2);
     h3 = hash_fmix_32(h3);
     h4 = hash_fmix_32(h4);
     h1 += h2; h1 += h3; h1 += h4;
     h2 += h1; h3 += h1; h4 += h1;
     r_out[0] = (((uint64_t) h2) << 32) | h1;
     r_out[1] = (((uint64_t) h4) << 32) | h3;
 }
References hash_fmix_32(), hash_get_block_32(), hash_rotl_32(), and JEMALLOC_FALLTHROUGH.
Referenced by hash().
hash_x86_32()
static uint32_t hash_x86_32 (const void * key, int len, uint32_t seed) inline static
Definition at line 73 of file hash.h.
{
     const uint8_t *data = (const uint8_t *) key;
     const int nblocks = len / 4;
     uint32_t h1 = seed;
     const uint32_t c1 = 0xcc9e2d51;
     const uint32_t c2 = 0x1b873593;
     /* body */
     {
         const uint32_t *blocks = (const uint32_t *) (data + nblocks*4);
         int i;
         for (i = -nblocks; i; i++) {
             uint32_t k1 = hash_get_block_32(blocks, i);
             k1 *= c1;
             k1 = hash_rotl_32(k1, 15);
             k1 *= c2;
             h1 ^= k1;
             h1 = hash_rotl_32(h1, 13);
             h1 = h1*5 + 0xe6546b64;
         }
     }
     /* tail */
     {
         const uint8_t *tail = (const uint8_t *) (data + nblocks*4);
         uint32_t k1 = 0;
         switch (len & 3) {
         case 3: k1 ^= tail[2] << 16; JEMALLOC_FALLTHROUGH
         case 2: k1 ^= tail[1] << 8; JEMALLOC_FALLTHROUGH
         case 1: k1 ^= tail[0]; k1 *= c1; k1 = hash_rotl_32(k1, 15);
             k1 *= c2; h1 ^= k1;
         }
     }
     /* finalization */
     h1 ^= len;
     h1 = hash_fmix_32(h1);
     return h1;
 }
References hash_fmix_32(), hash_get_block_32(), hash_rotl_32(), and JEMALLOC_FALLTHROUGH.