Azerotcore-wotlk: deps/mysqllite/include/my_dir.h File Reference
my_dir.h File Reference
#include "my_global.h"
#include <sys/stat.h>
Classes
struct fileinfo
struct st_my_dir
Macros
#define MY_S_IFMT S_IFMT /* type of file */
#define MY_S_IFDIR S_IFDIR /* directory */
#define MY_S_IFCHR S_IFCHR /* character special */
#define MY_S_IFBLK S_IFBLK /* block special */
#define MY_S_IFREG S_IFREG /* regular */
#define MY_S_IFIFO S_IFIFO /* fifo */
#define MY_S_ISUID S_ISUID /* set user id on execution */
#define MY_S_ISGID S_ISGID /* set group id on execution */
#define MY_S_ISVTX S_ISVTX /* save swapped text even after use */
#define MY_S_IREAD S_IREAD /* read permission, owner */
#define MY_S_IWRITE S_IWRITE /* write permission, owner */
#define MY_S_IEXEC S_IEXEC /* execute/search permission, owner */
#define MY_S_ISDIR(m) (((m) & MY_S_IFMT) == MY_S_IFDIR)
#define MY_S_ISCHR(m) (((m) & MY_S_IFMT) == MY_S_IFCHR)
#define MY_S_ISBLK(m) (((m) & MY_S_IFMT) == MY_S_IFBLK)
#define MY_S_ISREG(m) (((m) & MY_S_IFMT) == MY_S_IFREG)
#define MY_S_ISFIFO(m) (((m) & MY_S_IFMT) == MY_S_IFIFO)
#define MY_DONT_SORT 512 /* my_lib; Don't sort files */
#define MY_WANT_STAT 1024 /* my_lib; stat files */
#define MY_STAT struct stat /* Orginal struct have what we need */
Typedefs
typedef struct fileinfo FILEINFO
typedef struct st_my_dir MY_DIR
Functions
MY_DIR * my_dir (const char *path, myf MyFlags)
void my_dirend (MY_DIR *buffer)
MY_STAT * my_stat (const char *path, MY_STAT *stat_area, myf my_flags)
int my_fstat (int filenr, MY_STAT *stat_area, myf MyFlags)
Macro Definition Documentation
MY_DONT_SORT
#define MY_DONT_SORT 512 /* my_lib; Don't sort files */
Definition at line 48 of file my_dir.h.
MY_S_IEXEC
#define MY_S_IEXEC S_IEXEC /* execute/search permission, owner */
Definition at line 40 of file my_dir.h.
MY_S_IFBLK
#define MY_S_IFBLK S_IFBLK /* block special */
Definition at line 32 of file my_dir.h.
MY_S_IFCHR
#define MY_S_IFCHR S_IFCHR /* character special */
Definition at line 31 of file my_dir.h.
MY_S_IFDIR
#define MY_S_IFDIR S_IFDIR /* directory */
Definition at line 30 of file my_dir.h.
MY_S_IFIFO
#define MY_S_IFIFO S_IFIFO /* fifo */
Definition at line 34 of file my_dir.h.
MY_S_IFMT
#define MY_S_IFMT S_IFMT /* type of file */
Definition at line 29 of file my_dir.h.
MY_S_IFREG
#define MY_S_IFREG S_IFREG /* regular */
Definition at line 33 of file my_dir.h.
MY_S_IREAD
#define MY_S_IREAD S_IREAD /* read permission, owner */
Definition at line 38 of file my_dir.h.
MY_S_ISBLK
#define MY_S_ISBLK (m) (((m) & MY_S_IFMT) == MY_S_IFBLK)
Definition at line 44 of file my_dir.h.
MY_S_ISCHR
#define MY_S_ISCHR (m) (((m) & MY_S_IFMT) == MY_S_IFCHR)
Definition at line 43 of file my_dir.h.
MY_S_ISDIR
#define MY_S_ISDIR (m) (((m) & MY_S_IFMT) == MY_S_IFDIR)
Definition at line 42 of file my_dir.h.
MY_S_ISFIFO
#define MY_S_ISFIFO (m) (((m) & MY_S_IFMT) == MY_S_IFIFO)
Definition at line 46 of file my_dir.h.
MY_S_ISGID
#define MY_S_ISGID S_ISGID /* set group id on execution */
Definition at line 36 of file my_dir.h.
MY_S_ISREG
#define MY_S_ISREG (m) (((m) & MY_S_IFMT) == MY_S_IFREG)
Definition at line 45 of file my_dir.h.
MY_S_ISUID
#define MY_S_ISUID S_ISUID /* set user id on execution */
Definition at line 35 of file my_dir.h.
MY_S_ISVTX
#define MY_S_ISVTX S_ISVTX /* save swapped text even after use */
Definition at line 37 of file my_dir.h.
MY_S_IWRITE
#define MY_S_IWRITE S_IWRITE /* write permission, owner */
Definition at line 39 of file my_dir.h.
MY_STAT
#define MY_STAT struct stat /* Orginal struct have what we need */
Definition at line 75 of file my_dir.h.
MY_WANT_STAT
#define MY_WANT_STAT 1024 /* my_lib; stat files */
Definition at line 49 of file my_dir.h.
Typedef Documentation
FILEINFO
typedef struct fileinfo FILEINFO
MY_DIR
typedef struct st_my_dir MY_DIR
Function Documentation
my_dir()
MY_DIR* my_dir (const char * path, myf MyFlags)
Definition at line 90 of file my_lib.c.
 {
   char          *buffer;
   MY_DIR        *result= 0;
   FILEINFO      finfo;
   DYNAMIC_ARRAY *dir_entries_storage;
   MEM_ROOT      *names_storage;
   DIR       *dirp;
   struct dirent *dp;
   char      tmp_path[FN_REFLEN+1],*tmp_file;
   char  dirent_tmp[sizeof(struct dirent)+_POSIX_PATH_MAX+1];
   DBUG_ENTER("my_dir");
   DBUG_PRINT("my",("path: '%s' MyFlags: %d",path,MyFlags));
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_lock(&THR_LOCK_open);
 #endif
   dirp = opendir(directory_file_name(tmp_path,(char *) path));
 #if defined(__amiga__)
   if ((dirp->dd_fd) < 0)            /* Directory doesn't exists */
     goto error;
 #endif
   if (dirp == NULL ||
       ! (buffer= my_malloc(ALIGN_SIZE(sizeof(MY_DIR)) +
                            ALIGN_SIZE(sizeof(DYNAMIC_ARRAY)) +
                            sizeof(MEM_ROOT), MyFlags)))
     goto error;
   dir_entries_storage= (DYNAMIC_ARRAY*)(buffer + ALIGN_SIZE(sizeof(MY_DIR)));
   names_storage= (MEM_ROOT*)(buffer + ALIGN_SIZE(sizeof(MY_DIR)) +
                              ALIGN_SIZE(sizeof(DYNAMIC_ARRAY)));
   if (my_init_dynamic_array(dir_entries_storage, sizeof(FILEINFO),
                             ENTRIES_START_SIZE, ENTRIES_INCREMENT))
   {
     my_free(buffer);
     goto error;
   }
   init_alloc_root(names_storage, NAMES_START_SIZE, NAMES_START_SIZE);
   /* MY_DIR structure is allocated and completly initialized at this point */
   result= (MY_DIR*)buffer;
   tmp_file=strend(tmp_path);
   dp= (struct dirent*) dirent_tmp;
   while (!(READDIR(dirp,(struct dirent*) dirent_tmp,dp)))
   {
     if (!(finfo.name= strdup_root(names_storage, dp->d_name)))
       goto error;
     if (MyFlags & MY_WANT_STAT)
     {
       if (!(finfo.mystat= (MY_STAT*)alloc_root(names_storage,
                                                sizeof(MY_STAT))))
         goto error;
       bzero(finfo.mystat, sizeof(MY_STAT));
       (void) strmov(tmp_file,dp->d_name);
       (void) my_stat(tmp_path, finfo.mystat, MyFlags);
       if (!(finfo.mystat->st_mode & MY_S_IREAD))
         continue;
     }
     else
       finfo.mystat= NULL;
     if (push_dynamic(dir_entries_storage, (uchar*)&finfo))
       goto error;
   }
   (void) closedir(dirp);
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_unlock(&THR_LOCK_open);
 #endif
   result->dir_entry= (FILEINFO *)dir_entries_storage->buffer;
   result->number_off_files= dir_entries_storage->elements;
   if (!(MyFlags & MY_DONT_SORT))
     my_qsort((void *) result->dir_entry, result->number_off_files,
           sizeof(FILEINFO), (qsort_cmp) comp_names);
   DBUG_RETURN(result);
  error:
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_unlock(&THR_LOCK_open);
 #endif
   my_errno=errno;
   if (dirp)
     (void) closedir(dirp);
   my_dirend(result);
   if (MyFlags & (MY_FAE | MY_WME))
     my_error(EE_DIR,MYF(ME_BELL+ME_WAITTANG),path,my_errno);
   DBUG_RETURN((MY_DIR *) NULL);
 } /* my_dir */
References ALIGN_SIZE, alloc_root(), buffer, st_dynamic_array::buffer, bzero, closedir(), comp_names(), dirent::d_name, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, directory_file_name(), EE_DIR, st_dynamic_array::elements, ENTRIES_INCREMENT, ENTRIES_START_SIZE, errno, error(), FN_REFLEN, if(), init_alloc_root(), ME_BELL, ME_WAITTANG, my_dirend(), MY_DONT_SORT, my_errno, my_error(), MY_FAE, my_free(), my_init_dynamic_array, my_malloc(), my_qsort(), MY_S_IREAD, MY_STAT, my_stat(), MY_WANT_STAT, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, fileinfo::mystat, fileinfo::name, NAMES_START_SIZE, NULL, opendir(), push_dynamic, qsort_cmp, READDIR, strdup_root(), strend(), strmov(), and THR_LOCK_open.
Referenced by search_default_file_with_ext().
my_dirend()
void my_dirend (MY_DIR * buffer)
Definition at line 65 of file my_lib.c.
 {
   DBUG_ENTER("my_dirend");
   if (buffer)
   {
     delete_dynamic((DYNAMIC_ARRAY*)((char*)buffer +
                                     ALIGN_SIZE(sizeof(MY_DIR))));
     free_root((MEM_ROOT*)((char*)buffer + ALIGN_SIZE(sizeof(MY_DIR)) +
                           ALIGN_SIZE(sizeof(DYNAMIC_ARRAY))), MYF(0));
     my_free(buffer);
   }
   DBUG_VOID_RETURN;
 } /* my_dirend */
References ALIGN_SIZE, DBUG_ENTER, DBUG_VOID_RETURN, delete_dynamic(), free_root(), my_free(), and MYF.
Referenced by my_dir(), and search_default_file_with_ext().
my_fstat()
int my_fstat (int filenr, MY_STAT * stat_area, myf MyFlags)
Referenced by inline_mysql_file_fstat().
my_stat()
MY_STAT* my_stat (const char * path, MY_STAT * stat_area, myf my_flags)
Definition at line 395 of file my_lib.c.
 {
   int m_used;
   DBUG_ENTER("my_stat");
   DBUG_PRINT("my", ("path: '%s'  stat_area: 0x%lx  MyFlags: %d", path,
                     (long) stat_area, my_flags));
   if ((m_used= (stat_area == NULL)))
     if (!(stat_area= (MY_STAT *) my_malloc(sizeof(MY_STAT), my_flags)))
       goto error;
 #ifndef _WIN32
     if (! stat((char *) path, (struct stat *) stat_area) )
       DBUG_RETURN(stat_area);
 #else
     if (! my_win_stat(path, stat_area) )
       DBUG_RETURN(stat_area);
 #endif
   DBUG_PRINT("error",("Got errno: %d from stat", errno));
   my_errno= errno;
   if (m_used)                   /* Free if new area */
     my_free(stat_area);
 error:
   if (my_flags & (MY_FAE+MY_WME))
   {
     my_error(EE_STAT, MYF(ME_BELL+ME_WAITTANG),path,my_errno);
     DBUG_RETURN((MY_STAT *) NULL);
   }
   DBUG_RETURN((MY_STAT *) NULL);
 } /* my_stat */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_STAT, errno, error(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_free(), my_malloc(), MY_STAT, MY_WME, MYF, and NULL.
Referenced by inline_mysql_file_stat(), my_copy(), my_dir(), my_read_charset_file(), my_rename(), and search_default_file_with_ext().