Azerotcore-wotlk: deserter_commandscript Class Reference
deserter_commandscript Class Reference
Public Member Functions
deserter_commandscript ()
ChatCommandTable GetCommands () const override
Returns the command structure for the system.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleDeserterAdd (ChatHandler *handler, uint32 time, bool isInstance)
Applies the Deserter Debuff to a player.
static bool HandleDeserterRemove (ChatHandler *handler, bool isInstance)
Removes the Deserter Debuff from a player.
static bool HandleDeserterInstanceAdd (ChatHandler *handler, uint32 time)
static bool HandleDeserterBGAdd (ChatHandler *handler, uint32 time)
static bool HandleDeserterInstanceRemove (ChatHandler *handler)
static bool HandleDeserterBGRemove (ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 39 of file cs_deserter.cpp.
Constructor & Destructor Documentation
deserter_commandscript()
deserter_commandscript::deserter_commandscript () inline
Definition at line 42 of file cs_deserter.cpp.
 : CommandScript("deserter_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable deserter_commandscript::GetCommands () const inline override virtual
Returns the command structure for the system.
Implements CommandScript.
Definition at line 48 of file cs_deserter.cpp.
     {
         static ChatCommandTable deserterInstanceCommandTable =
         {
             { "add",      HandleDeserterInstanceAdd,    SEC_ADMINISTRATOR,    Console::No },
             { "remove",   HandleDeserterInstanceRemove, SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable deserterBGCommandTable =
         {
             { "add",      HandleDeserterBGAdd,    SEC_ADMINISTRATOR, Console::No },
             { "remove",   HandleDeserterBGRemove, SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable deserterCommandTable =
         {
             { "instance", deserterInstanceCommandTable },
             { "bg",       deserterBGCommandTable }
         };
         static ChatCommandTable commandTable =
         {
             { "deserter", deserterCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, and SEC_ADMINISTRATOR.
HandleDeserterAdd()
static bool deserter_commandscript::HandleDeserterAdd (ChatHandler * handler, uint32 time, bool isInstance) inline static
Applies the Deserter Debuff to a player.
This function applies a Deserter Debuff of the given type (Instance or BG) to the selected player, with the provided duration in seconds.
Parameters
handler The ChatHandler, passed by the system.
time The provided duration in seconds.
isInstance provided by the relaying functions, so we don't have to write that much code :)
Returns
true if everything was correct, false if an error occured.
Example Usage:
.deserter instance add 3600 (one hour)
-or-
.deserter bg add 3600 (one hour)
Definition at line 93 of file cs_deserter.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!time)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Aura* aura = player->AddAura(isInstance ? LFG_SPELL_DUNGEON_DESERTER : BG_SPELL_DESERTER, player);
         if (!aura)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         aura->SetDuration(time * IN_MILLISECONDS);
         return true;
     }
References Unit::AddAura(), BG_SPELL_DESERTER, ChatHandler::getSelectedPlayer(), IN_MILLISECONDS, LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LFG_SPELL_DUNGEON_DESERTER, ChatHandler::SendSysMessage(), Aura::SetDuration(), and ChatHandler::SetSentErrorMessage().
HandleDeserterBGAdd()
static bool deserter_commandscript::HandleDeserterBGAdd (ChatHandler * handler, uint32 time) inline static
See also
HandleDeserterAdd()
Definition at line 164 of file cs_deserter.cpp.
     {
         return HandleDeserterAdd(handler, time, false);
     }
HandleDeserterBGRemove()
static bool deserter_commandscript::HandleDeserterBGRemove (ChatHandler * handler) inline static
See also
HandleDeserterRemove()
Definition at line 176 of file cs_deserter.cpp.
     {
         return HandleDeserterRemove(handler, false);
     }
HandleDeserterInstanceAdd()
static bool deserter_commandscript::HandleDeserterInstanceAdd (ChatHandler * handler, uint32 time) inline static
See also
HandleDeserterAdd()
Definition at line 158 of file cs_deserter.cpp.
     {
         return HandleDeserterAdd(handler, time, true);
     }
HandleDeserterInstanceRemove()
static bool deserter_commandscript::HandleDeserterInstanceRemove (ChatHandler * handler) inline static
See also
HandleDeserterRemove()
Definition at line 170 of file cs_deserter.cpp.
     {
         return HandleDeserterRemove(handler, true);
     }
HandleDeserterRemove()
static bool deserter_commandscript::HandleDeserterRemove (ChatHandler * handler, bool isInstance) inline static
Removes the Deserter Debuff from a player.
This function removes a Deserter Debuff of the given type (Instance or BG) from the selected player.
Parameters
handler The ChatHandler, passed by the system.
isInstance provided by the relaying functions, so we don't have to write that much code :)
Returns
true if everything was correct, false if an error occured.
Example Usage:
.deserter instance remove
-or-
.deserter bg remove
Definition at line 142 of file cs_deserter.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         player->RemoveAura(isInstance ? LFG_SPELL_DUNGEON_DESERTER : BG_SPELL_DESERTER);
         return true;
     }
References BG_SPELL_DESERTER, ChatHandler::getSelectedPlayer(), LANG_NO_CHAR_SELECTED, LFG_SPELL_DUNGEON_DESERTER, Unit::RemoveAura(), ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_deserter.cpp