Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tsd.h File Reference
tsd.h File Reference
#include "jemalloc/internal/arena_types.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/bin_types.h"
#include "jemalloc/internal/jemalloc_internal_externs.h"
#include "jemalloc/internal/prof_types.h"
#include "jemalloc/internal/ql.h"
#include "jemalloc/internal/rtree_tsd.h"
#include "jemalloc/internal/tcache_types.h"
#include "jemalloc/internal/tcache_structs.h"
#include "jemalloc/internal/util.h"
#include "jemalloc/internal/witness.h"
#include "jemalloc/internal/tsd_generic.h"
Classes
struct tsd_s
struct tsdn_s
Macros
#define MALLOC_TEST_TSD
#define MALLOC_TEST_TSD_INITIALIZER
#define MALLOC_TSD
#define TSD_INITIALIZER
#define TSD_MANGLE(n) cant_access_tsd_items_directly_use_a_getter_or_setter_##n
#define tsd_state_t atomic_u32_t
#define tsd_atomic_load atomic_load_u32
#define tsd_atomic_store atomic_store_u32
#define tsd_atomic_exchange atomic_exchange_u32
#define O(n, t, nt) t TSD_MANGLE(n);
#define TSDN_NULL ((tsdn_t *)0)
#define O(n, t, nt)
#define O(n, t, nt)
#define O(n, t, nt)
#define O(n, t, nt)
#define O(n, t, nt)
Enumerations
enum {
tsd_state_nominal = 0 , tsd_state_nominal_slow = 1 , tsd_state_nominal_recompute = 2 , tsd_state_nominal_max = 2 ,
tsd_state_minimal_initialized = 3 , tsd_state_purgatory = 4 , tsd_state_reincarnated = 5 , tsd_state_uninitialized = 6
}
Functions
void * malloc_tsd_malloc (size_t size)
void malloc_tsd_dalloc (void *wrapper)
void malloc_tsd_cleanup_register (bool(*f)(void))
tsd_t * malloc_tsd_boot0 (void)
void malloc_tsd_boot1 (void)
void tsd_cleanup (void *arg)
tsd_t * tsd_fetch_slow (tsd_t *tsd, bool internal)
void tsd_state_set (tsd_t *tsd, uint8_t new_state)
void tsd_slow_update (tsd_t *tsd)
void tsd_prefork (tsd_t *tsd)
void tsd_postfork_parent (tsd_t *tsd)
void tsd_postfork_child (tsd_t *tsd)
void tsd_global_slow_inc (tsdn_t *tsdn)
void tsd_global_slow_dec (tsdn_t *tsdn)
bool tsd_global_slow ()
JEMALLOC_ALWAYS_INLINE uint8_t tsd_state_get (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE tsdn_t * tsd_tsdn (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE bool tsdn_null (const tsdn_t *tsdn)
JEMALLOC_ALWAYS_INLINE tsd_t * tsdn_tsd (tsdn_t *tsdn)
MALLOC_TSD JEMALLOC_ALWAYS_INLINE void tsd_assert_fast (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE bool tsd_fast (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_fetch_impl (bool init, bool minimal)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_fetch_min (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_internal_fetch (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_fetch (void)
static bool tsd_nominal (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE tsdn_t * tsdn_fetch (void)
JEMALLOC_ALWAYS_INLINE rtree_ctx_t * tsd_rtree_ctx (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE rtree_ctx_t * tsdn_rtree_ctx (tsdn_t *tsdn, rtree_ctx_t *fallback)
Macro Definition Documentation
MALLOC_TEST_TSD
#define MALLOC_TEST_TSD
Definition at line 59 of file tsd.h.
MALLOC_TEST_TSD_INITIALIZER
#define MALLOC_TEST_TSD_INITIALIZER
Definition at line 60 of file tsd.h.
MALLOC_TSD
#define MALLOC_TSD
Value:
    O(tcache_enabled,       bool,           bool)       \
    O(arenas_tdata_bypass,  bool,           bool)       \
    O(reentrancy_level,     int8_t,         int8_t)     \
    O(narenas_tdata,        uint32_t,       uint32_t)   \
    O(offset_state,     uint64_t,       uint64_t)   \
    O(thread_allocated,     uint64_t,       uint64_t)   \
    O(thread_deallocated,   uint64_t,       uint64_t)   \
    O(bytes_until_sample,   int64_t,        int64_t)    \
    O(prof_tdata,       prof_tdata_t *,     prof_tdata_t *) \
    O(rtree_ctx,        rtree_ctx_t,        rtree_ctx_t)    \
    O(iarena,           arena_t *,      arena_t *)  \
    O(arena,            arena_t *,      arena_t *)  \
    O(arenas_tdata,     arena_tdata_t *,    arena_tdata_t *)\
    O(binshards,        tsd_binshards_t,    tsd_binshards_t)\
    O(tcache,           tcache_t,       tcache_t)   \
    O(witness_tsd,              witness_tsd_t,      witness_tsdn_t) \
    MALLOC_TEST_TSD
Definition at line 64 of file tsd.h.
O [1/6]
#define O (n, t, nt) t TSD_MANGLE(n);
Definition at line 310 of file tsd.h.
O [2/6]
#define O (n, t, nt)
Value:
JEMALLOC_ALWAYS_INLINE t *                      \
tsd_##n##p_get_unsafe(tsd_t *tsd) {                 \
    return &tsd->TSD_MANGLE(n);                 \
}
Definition at line 310 of file tsd.h.
O [3/6]
#define O (n, t, nt)
Value:
JEMALLOC_ALWAYS_INLINE t *                      \
tsd_##n##p_get(tsd_t *tsd) {                        \
    /*                              \
     * Because the state might change asynchronously if it's    \
     * nominal, we need to make sure that we only read it once. \
     */                             \
    uint8_t state = tsd_state_get(tsd);             \
    assert(state == tsd_state_nominal ||                \
        state == tsd_state_nominal_slow ||              \
        state == tsd_state_nominal_recompute ||         \
        state == tsd_state_reincarnated ||              \
        state == tsd_state_minimal_initialized);            \
    return tsd_##n##p_get_unsafe(tsd);              \
}
Definition at line 310 of file tsd.h.
O [4/6]
#define O (n, t, nt)
Value:
JEMALLOC_ALWAYS_INLINE nt *                     \
tsdn_##n##p_get(tsdn_t *tsdn) {                     \
    if (tsdn_null(tsdn)) {                      \
        return NULL;                        \
    }                               \
    tsd_t *tsd = tsdn_tsd(tsdn);                    \
    return (nt *)tsd_##n##p_get(tsd);               \
}
Definition at line 310 of file tsd.h.
O [5/6]
#define O (n, t, nt)
Value:
JEMALLOC_ALWAYS_INLINE t                        \
tsd_##n##_get(tsd_t *tsd) {                     \
    return *tsd_##n##p_get(tsd);                    \
}
Definition at line 310 of file tsd.h.
O [6/6]
#define O (n, t, nt)
Value:
JEMALLOC_ALWAYS_INLINE void                     \
tsd_##n##_set(tsd_t *tsd, t val) {                  \
    assert(tsd_state_get(tsd) != tsd_state_reincarnated &&      \
        tsd_state_get(tsd) != tsd_state_minimal_initialized);   \
    *tsd_##n##p_get(tsd) = val;                 \
}
Definition at line 310 of file tsd.h.
tsd_atomic_exchange
#define tsd_atomic_exchange atomic_exchange_u32
Definition at line 181 of file tsd.h.
tsd_atomic_load
#define tsd_atomic_load atomic_load_u32
Definition at line 179 of file tsd.h.
tsd_atomic_store
#define tsd_atomic_store atomic_store_u32
Definition at line 180 of file tsd.h.
TSD_INITIALIZER
#define TSD_INITIALIZER
Value:
    {                       \
    ATOMIC_INIT(tsd_state_uninitialized),               \
    TCACHE_ENABLED_ZERO_INITIALIZER,                    \
    false,                              \
    0,                                  \
    0,                                  \
    0,                                  \
    0,                                  \
    0,                                  \
    0,                                  \
    NULL,                               \
    RTREE_CTX_ZERO_INITIALIZER,                     \
    NULL,                               \
    NULL,                               \
    NULL,                               \
    TSD_BINSHARDS_ZERO_INITIALIZER,                 \
    TCACHE_ZERO_INITIALIZER,                        \
    WITNESS_TSD_INITIALIZER                     \
    MALLOC_TEST_TSD_INITIALIZER                     \
}
Definition at line 83 of file tsd.h.
TSD_MANGLE
#define TSD_MANGLE (n) cant_access_tsd_items_directly_use_a_getter_or_setter_##n
Definition at line 170 of file tsd.h.
tsd_state_t
#define tsd_state_t atomic_u32_t
Definition at line 178 of file tsd.h.
TSDN_NULL
#define TSDN_NULL ((tsdn_t *)0)
Definition at line 222 of file tsd.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
tsd_state_nominal
tsd_state_nominal_slow
tsd_state_nominal_recompute
tsd_state_nominal_max
tsd_state_minimal_initialized
tsd_state_purgatory
tsd_state_reincarnated
tsd_state_uninitialized
Definition at line 125 of file tsd.h.
      {
     /* Common case --> jnz. */
     tsd_state_nominal = 0,
     /* Initialized but on slow path. */
     tsd_state_nominal_slow = 1,
     /*
      * Some thread has changed global state in such a way that all nominal
      * threads need to recompute their fast / slow status the next time they
      * get a chance.
      *
      * Any thread can change another thread's status *to* recompute, but
      * threads are the only ones who can change their status *from*
      * recompute.
      */
     tsd_state_nominal_recompute = 2,
     /*
      * The above nominal states should be lower values.  We use
      * tsd_nominal_max to separate nominal states from threads in the
      * process of being born / dying.
      */
     tsd_state_nominal_max = 2,
     /*
      * A thread might free() during its death as its only allocator action;
      * in such scenarios, we need tsd, but set up in such a way that no
      * cleanup is necessary.
      */
     tsd_state_minimal_initialized = 3,
     /* States during which we know we're in thread death. */
     tsd_state_purgatory = 4,
     tsd_state_reincarnated = 5,
     /*
      * What it says on the tin; tsd that hasn't been initialized.  Note
      * that even when the tsd struct lives in TLS, when need to keep track
      * of stuff like whether or not our pthread destructors have been
      * scheduled, so this really truly is different than the nominal state.
      */
     tsd_state_uninitialized = 6
 };
Function Documentation
malloc_tsd_boot0()
tsd_t* malloc_tsd_boot0 (void)
Definition at line 418 of file tsd.c.
{
     tsd_t *tsd;
     ncleanups = 0;
     if (malloc_mutex_init(&tsd_nominal_tsds_lock, "tsd_nominal_tsds_lock",
         WITNESS_RANK_OMIT, malloc_mutex_rank_exclusive)) {
         return NULL;
     }
     if (tsd_boot0()) {
         return NULL;
     }
     tsd = tsd_fetch();
     *tsd_arenas_tdata_bypassp_get(tsd) = true;
     return tsd;
 }
References malloc_mutex_init, malloc_mutex_rank_exclusive, ncleanups, NULL, tsd_boot0(), tsd_fetch(), and WITNESS_RANK_OMIT.
malloc_tsd_boot1()
void malloc_tsd_boot1 (void)
Definition at line 435 of file tsd.c.
{
     tsd_boot1();
     tsd_t *tsd = tsd_fetch();
     /* malloc_slow has been set properly.  Update tsd_slow. */
     tsd_slow_update(tsd);
     *tsd_arenas_tdata_bypassp_get(tsd) = false;
 }
References tsd_boot1(), tsd_fetch(), and tsd_slow_update().
malloc_tsd_cleanup_register()
void malloc_tsd_cleanup_register (bool(*)(void) f)
Definition at line 356 of file tsd.c.
{
     assert(ncleanups < MALLOC_TSD_CLEANUPS_MAX);
     cleanups[ncleanups] = f;
     ncleanups++;
 }
References assert(), cleanups, f(), MALLOC_TSD_CLEANUPS_MAX, and ncleanups.
malloc_tsd_dalloc()
void malloc_tsd_dalloc (void * wrapper)
Definition at line 324 of file tsd.c.
{
     a0dalloc(wrapper);
 }
References a0dalloc.
malloc_tsd_malloc()
void* malloc_tsd_malloc (size_t size)
Definition at line 319 of file tsd.c.
{
     return a0malloc(CACHELINE_CEILING(size));
 }
References a0malloc, and CACHELINE_CEILING.
tsd_assert_fast()
MALLOC_TSD JEMALLOC_ALWAYS_INLINE void tsd_assert_fast (tsd_t * tsd)
Definition at line 321 of file tsd.h.
{
     /*
      * Note that our fastness assertion does *not* include global slowness
      * counters; it's not in general possible to ensure that they won't
      * change asynchronously from underneath us.
      */
References assert(), and malloc_slow.
Referenced by free_default(), ifree(), imalloc(), isfree(), je_dallocx(), and sdallocx_default().
tsd_cleanup()
void tsd_cleanup (void * arg)
Definition at line 373 of file tsd.c.
{
     tsd_t *tsd = (tsd_t *)arg;
     switch (tsd_state_get(tsd)) {
     case tsd_state_uninitialized:
         /* Do nothing. */
         break;
     case tsd_state_minimal_initialized:
         /* This implies the thread only did free() in its life time. */
         /* Fall through. */
     case tsd_state_reincarnated:
         /*
          * Reincarnated means another destructor deallocated memory
          * after the destructor was called.  Cleanup isn't required but
          * is still called for testing and completeness.
          */
         assert_tsd_data_cleanup_done(tsd);
         /* Fall through. */
     case tsd_state_nominal:
     case tsd_state_nominal_slow:
         tsd_do_data_cleanup(tsd);
         tsd_state_set(tsd, tsd_state_purgatory);
         tsd_set(tsd);
         break;
     case tsd_state_purgatory:
         /*
          * The previous time this destructor was called, we set the
          * state to tsd_state_purgatory so that other destructors
          * wouldn't cause re-creation of the tsd.  This time, do
          * nothing, and do not request another callback.
          */
         break;
     default:
         not_reached();
     }
 #ifdef JEMALLOC_JET
     test_callback_t test_callback = *tsd_test_callbackp_get_unsafe(tsd);
     int *data = tsd_test_datap_get_unsafe(tsd);
     if (test_callback != NULL) {
         test_callback(data);
     }
 #endif
 }
References arg(), assert_tsd_data_cleanup_done(), not_reached, NULL, tsd_do_data_cleanup(), tsd_set(), tsd_state_get(), tsd_state_minimal_initialized, tsd_state_nominal, tsd_state_nominal_slow, tsd_state_purgatory, tsd_state_reincarnated, tsd_state_set(), and tsd_state_uninitialized.
tsd_fast()
JEMALLOC_ALWAYS_INLINE bool tsd_fast (tsd_t * tsd)
Definition at line 332 of file tsd.h.
                      {
     bool fast = (tsd_state_get(tsd) == tsd_state_nominal);
     if (fast) {
         tsd_assert_fast(tsd);
     }
Referenced by free_default(), free_fastpath(), imalloc(), je_dallocx(), je_xallocx(), JEMALLOC_ATTR(), pre_reentrancy(), sdallocx_default(), and tsd_fetch_slow().
tsd_fetch()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_fetch (void)
Definition at line 376 of file tsd.h.
                 {
Referenced by arenas_i(), base_map(), base_unmap(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), imalloc(), je_dallocx(), je_mallctl(), je_mallctlbymib(), je_mallctlnametomib(), je_rallocx(), je_realloc(), je_xallocx(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), malloc_init_hard(), malloc_tsd_boot0(), malloc_tsd_boot1(), prof_fdump(), prof_log_stop_final(), prof_sample_threshold_update(), and sdallocx_default().
tsd_fetch_impl()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_fetch_impl (bool init, bool minimal)
Definition at line 342 of file tsd.h.
{
     tsd_t *tsd = tsd_get(init);
     if (!init && tsd_get_allocates() && tsd == NULL) {
         return NULL;
     }
     assert(tsd != NULL);
     if (unlikely(tsd_state_get(tsd) != tsd_state_nominal)) {
         return tsd_fetch_slow(tsd, minimal);
     }
     assert(tsd_fast(tsd));
     tsd_assert_fast(tsd);
Referenced by tsd_fetch_min().
tsd_fetch_min()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_fetch_min (void)
Definition at line 361 of file tsd.h.
                     {
References tsd_fetch_impl().
Referenced by free_default(), and tsd_internal_fetch().
tsd_fetch_slow()
tsd_t* tsd_fetch_slow (tsd_t * tsd, bool internal)
Definition at line 270 of file tsd.c.
{
     assert(!tsd_fast(tsd));
     if (tsd_state_get(tsd) == tsd_state_nominal_slow) {
         /*
          * On slow path but no work needed.  Note that we can't
          * necessarily *assert* that we're slow, because we might be
          * slow because of an asynchronous modification to global state,
          * which might be asynchronously modified *back*.
          */
     } else if (tsd_state_get(tsd) == tsd_state_nominal_recompute) {
         tsd_slow_update(tsd);
     } else if (tsd_state_get(tsd) == tsd_state_uninitialized) {
         if (!minimal) {
             if (tsd_booted) {
                 tsd_state_set(tsd, tsd_state_nominal);
                 tsd_slow_update(tsd);
                 /* Trigger cleanup handler registration. */
                 tsd_set(tsd);
                 tsd_data_init(tsd);
             }
         } else {
             tsd_state_set(tsd, tsd_state_minimal_initialized);
             tsd_set(tsd);
             tsd_data_init_nocleanup(tsd);
         }
     } else if (tsd_state_get(tsd) == tsd_state_minimal_initialized) {
         if (!minimal) {
             /* Switch to fully initialized. */
             tsd_state_set(tsd, tsd_state_nominal);
             assert(*tsd_reentrancy_levelp_get(tsd) >= 1);
             (*tsd_reentrancy_levelp_get(tsd))--;
             tsd_slow_update(tsd);
             tsd_data_init(tsd);
         } else {
             assert_tsd_data_cleanup_done(tsd);
         }
     } else if (tsd_state_get(tsd) == tsd_state_purgatory) {
         tsd_state_set(tsd, tsd_state_reincarnated);
         tsd_set(tsd);
         tsd_data_init_nocleanup(tsd);
     } else {
         assert(tsd_state_get(tsd) == tsd_state_reincarnated);
     }
     return tsd;
 }
References assert(), assert_tsd_data_cleanup_done(), tsd_booted, tsd_data_init(), tsd_data_init_nocleanup(), tsd_fast(), tsd_set(), tsd_slow_update(), tsd_state_get(), tsd_state_minimal_initialized, tsd_state_nominal, tsd_state_nominal_recompute, tsd_state_nominal_slow, tsd_state_purgatory, tsd_state_reincarnated, tsd_state_set(), and tsd_state_uninitialized.
tsd_global_slow()
bool tsd_global_slow ()
Definition at line 151 of file tsd.c.
                   {
     return atomic_load_u32(&tsd_global_slow_count, ATOMIC_RELAXED) > 0;
 }
References ATOMIC_RELAXED.
Referenced by tsd_state_compute().
tsd_global_slow_dec()
void tsd_global_slow_dec (tsdn_t * tsdn)
Definition at line 138 of file tsd.c.
{
     atomic_fetch_sub_u32(&tsd_global_slow_count, 1, ATOMIC_RELAXED);
     /* See the note in ..._inc(). */
     tsd_force_recompute(tsdn);
 }
References ATOMIC_RELAXED, and tsd_force_recompute().
tsd_global_slow_inc()
void tsd_global_slow_inc (tsdn_t * tsdn)
Definition at line 125 of file tsd.c.
{
     atomic_fetch_add_u32(&tsd_global_slow_count, 1, ATOMIC_RELAXED);
     /*
      * We unconditionally force a recompute, even if the global slow count
      * was already positive.  If we didn't, then it would be possible for us
      * to return to the user, have the user synchronize externally with some
      * other thread, and then have that other thread not have picked up the
      * update yet (since the original incrementing thread might still be
      * making its way through the tsd list).
      */
     tsd_force_recompute(tsdn);
 }
References ATOMIC_RELAXED, and tsd_force_recompute().
tsd_internal_fetch()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_internal_fetch (void)
Definition at line 367 of file tsd.h.
{
     tsd_t *tsd = tsd_fetch_min();
     /* Use reincarnated state to prevent full initialization. */
     tsd_state_set(tsd, tsd_state_reincarnated);
References tsd_fetch_min(), tsd_state_reincarnated, and tsd_state_set().
tsd_nominal()
static bool tsd_nominal (tsd_t * tsd) inline static
Definition at line 381 of file tsd.h.
{
Referenced by arena_tdata_get_hard(), assert_tsd_data_cleanup_done(), prof_sample_check(), prof_tdata_get(), and tsd_state_compute().
tsd_postfork_child()
void tsd_postfork_child (tsd_t * tsd)
Definition at line 527 of file tsd.c.
{
     malloc_mutex_postfork_child(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
     ql_new(&tsd_nominal_tsds);
     if (tsd_state_get(tsd) <= tsd_state_nominal_max) {
         tsd_add_nominal(tsd);
     }
 }
References malloc_mutex_postfork_child, ql_new, tsd_add_nominal(), tsd_state_get(), tsd_state_nominal_max, and tsd_tsdn().
tsd_postfork_parent()
void tsd_postfork_parent (tsd_t * tsd)
Definition at line 522 of file tsd.c.
{
     malloc_mutex_postfork_parent(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References malloc_mutex_postfork_parent, and tsd_tsdn().
tsd_prefork()
void tsd_prefork (tsd_t * tsd)
Definition at line 517 of file tsd.c.
{
     malloc_mutex_prefork(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References malloc_mutex_prefork, and tsd_tsdn().
tsd_rtree_ctx()
JEMALLOC_ALWAYS_INLINE rtree_ctx_t* tsd_rtree_ctx (tsd_t * tsd)
Definition at line 395 of file tsd.h.
{
Referenced by arena_dalloc(), arena_reset(), arena_sdalloc(), free_fastpath(), ifree(), isfree(), je_rallocx(), je_realloc(), and je_xallocx().
tsd_slow_update()
void tsd_slow_update (tsd_t * tsd)
Definition at line 171 of file tsd.c.
{
     uint8_t old_state;
     do {
         uint8_t new_state = tsd_state_compute(tsd);
         old_state = tsd_atomic_exchange(&tsd->state, new_state,
             ATOMIC_ACQUIRE);
     } while (old_state == tsd_state_nominal_recompute);
 }
References ATOMIC_ACQUIRE, tsd_s::state, tsd_atomic_exchange, tsd_state_compute(), and tsd_state_nominal_recompute.
Referenced by malloc_tsd_boot1(), tsd_fetch_slow(), and tsd_state_set().
tsd_state_get()
JEMALLOC_ALWAYS_INLINE uint8_t tsd_state_get (tsd_t * tsd)
Definition at line 204 of file tsd.h.
{
     /*
      * This should be atomic.  Unfortunately, compilers right now can't tell
      * that this can be done as a memory comparison, and forces a load into
      * a register that hurts fast-path performance.
      */
     /* return atomic_load_u8(&tsd->state, ATOMIC_RELAXED); */
     return *(uint8_t *)&tsd->state;
 }
References tsd_s::state.
Referenced by pre_reentrancy(), tsd_add_nominal(), tsd_cleanup(), tsd_data_init_nocleanup(), tsd_fetch_slow(), tsd_postfork_child(), tsd_remove_nominal(), and tsd_state_compute().
tsd_state_set()
void tsd_state_set (tsd_t * tsd, uint8_t new_state)
Definition at line 181 of file tsd.c.
{
     /* Only the tsd module can change the state *to* recompute. */
     assert(new_state != tsd_state_nominal_recompute);
     uint8_t old_state = tsd_atomic_load(&tsd->state, ATOMIC_RELAXED);
     if (old_state > tsd_state_nominal_max) {
         /*
          * Not currently in the nominal list, but it might need to be
          * inserted there.
          */
         assert(!tsd_in_nominal_list(tsd));
         tsd_atomic_store(&tsd->state, new_state, ATOMIC_RELAXED);
         if (new_state <= tsd_state_nominal_max) {
             tsd_add_nominal(tsd);
         }
     } else {
         /*
          * We're currently nominal.  If the new state is non-nominal,
          * great; we take ourselves off the list and just enter the new
          * state.
          */
         assert(tsd_in_nominal_list(tsd));
         if (new_state > tsd_state_nominal_max) {
             tsd_remove_nominal(tsd);
             tsd_atomic_store(&tsd->state, new_state,
                 ATOMIC_RELAXED);
         } else {
             /*
              * This is the tricky case.  We're transitioning from
              * one nominal state to another.  The caller can't know
              * about any races that are occuring at the same time,
              * so we always have to recompute no matter what.
              */
             tsd_slow_update(tsd);
         }
     }
 }
References assert(), ATOMIC_RELAXED, tsd_s::state, tsd_add_nominal(), tsd_atomic_load, tsd_atomic_store, tsd_remove_nominal(), tsd_slow_update(), tsd_state_nominal_max, and tsd_state_nominal_recompute.
Referenced by tsd_cleanup(), tsd_fetch_slow(), and tsd_internal_fetch().
tsd_tsdn()
JEMALLOC_ALWAYS_INLINE tsdn_t* tsd_tsdn (tsd_t * tsd)
Definition at line 224 of file tsd.h.
                      {
     return (tsdn_t *)tsd;
 }
Referenced by arena_bin_reset(), arena_bind(), arena_choose_hard(), arena_choose_huge(), arena_choose_impl(), arena_destroy(), arena_i_decay_ctl(), arena_i_decay_ms_ctl_impl(), arena_i_destroy_ctl(), arena_i_dss_ctl(), arena_i_extent_hooks_ctl(), arena_i_initialized_ctl(), arena_i_purge_ctl(), arena_i_reset_destroy_helper(), arena_i_retain_grow_limit_ctl(), arena_migrate(), arena_reset(), arena_reset_finish_background_thread(), arena_reset_prepare_background_thread(), arena_retain_grow_limit_get_set(), arena_unbind(), arenas_create_ctl(), arenas_i(), arenas_i_impl(), arenas_lookup_ctl(), arenas_narenas_ctl(), background_thread_ctl(), ckh_delete(), ckh_grow(), ckh_new(), ckh_shrink(), ctl_arena_init(), ctl_bymib(), ctl_byname(), ctl_init(), ctl_nametomib(), CTL_RO_NL_GEN(), epoch_ctl(), experimental_arenas_i_pactivep_ctl(), experimental_hooks_install_ctl(), experimental_hooks_remove_ctl(), experimental_utilization_batch_query_ctl(), experimental_utilization_query_ctl(), extent_hook_pre_reentrancy(), extent_hooks_set(), free_default(), free_fastpath(), ialloc(), idalloc(), if(), ifree(), imalloc_body(), imalloc_no_sample(), imalloc_sample(), ipalloc(), iralloc(), irallocx_prof(), irealloc_prof(), irealloc_prof_sample(), isfree(), ixallocx_prof(), je_dallocx(), je_mallctl(), je_mallctlbymib(), je_mallctlnametomib(), je_rallocx(), je_realloc(), je_xallocx(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), malloc_init_hard(), max_background_threads_ctl(), percpu_arena_update(), pre_reentrancy(), prof_active_ctl(), prof_boot2(), prof_dump(), prof_dump_file(), prof_dump_prep(), prof_enter(), prof_fdump(), prof_free(), prof_free_sampled_object(), prof_gctx_finish(), prof_gctx_try_destroy(), prof_gdump_ctl(), prof_idump(), prof_leave(), prof_log_bt_index(), prof_log_start_ctl(), prof_log_stop_ctl(), prof_log_stop_final(), prof_log_thr_index(), prof_lookup(), prof_lookup_global(), prof_mdump(), prof_realloc(), prof_reset(), prof_tctx_destroy(), prof_tdata_destroy(), prof_tdata_destroy_locked(), prof_tdata_detach(), prof_tdata_init(), prof_tdata_init_impl(), prof_tdata_reinit(), prof_thread_active_init_ctl(), prof_thread_name_set(), prof_try_log(), sdallocx_default(), tcache_alloc_large(), tcache_alloc_small(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_create_explicit(), tcache_dalloc_large(), tcache_dalloc_small(), tcache_destroy(), tcache_flush_cache(), tcaches_create(), tcaches_create_prep(), tcaches_destroy(), tcaches_elm_remove(), tcaches_flush(), tsd_add_nominal(), tsd_postfork_child(), tsd_postfork_parent(), tsd_prefork(), tsd_remove_nominal(), and tsd_tcache_data_init().
tsdn_fetch()
JEMALLOC_ALWAYS_INLINE tsdn_t* tsdn_fetch (void)
Definition at line 386 of file tsd.h.
                  {
     if (!tsd_booted_get()) {
         return NULL;
     }
Referenced by extent_alloc_default(), extent_merge_default(), hook_reentrantp(), je_malloc_stats_print(), je_malloc_usable_size(), je_nallocx(), je_sallocx(), stats_print_atexit(), zone_free(), zone_free_definite_size(), and zone_realloc().
tsdn_null()
JEMALLOC_ALWAYS_INLINE bool tsdn_null (const tsdn_t * tsdn)
Definition at line 229 of file tsd.h.
{
     return tsdn == NULL;
 }
References NULL.
Referenced by arena_bin_choose_lock(), arena_dalloc(), arena_decay_ticks(), arena_malloc(), arena_malloc_hard(), arena_new(), arena_sdalloc(), base_map(), base_unmap(), check_entry_exit_locking(), extent_addr_randomize(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), iallocztm(), idalloctm(), large_palloc(), malloc_init_hard_cleanup(), prof_gdump(), prof_idump(), and tsdn_tsd().
tsdn_rtree_ctx()
JEMALLOC_ALWAYS_INLINE rtree_ctx_t* tsdn_rtree_ctx (tsdn_t * tsdn, rtree_ctx_t * fallback)
Definition at line 400 of file tsd.h.
{
     /*
      * If tsd cannot be accessed, initialize the fallback rtree_ctx and
      * return a pointer to it.
      */
     if (unlikely(tsdn_null(tsdn))) {
         rtree_ctx_data_init(fallback);
         return fallback;
Referenced by arena_dalloc_no_tcache(), arena_prof_demote(), arena_prof_promote(), arena_salloc(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_vsalloc(), extent_deregister_impl(), extent_grow_retained(), extent_merge_impl(), extent_record(), extent_recycle(), extent_register_impl(), extent_split_impl(), extents_evict(), iealloc(), large_ralloc_no_move_expand(), and tbin_extents_lookup_size_check().
tsdn_tsd()
JEMALLOC_ALWAYS_INLINE tsd_t* tsdn_tsd (tsdn_t * tsdn)
Definition at line 234 of file tsd.h.
{
     assert(!tsdn_null(tsdn));
     return &tsdn->tsd;
 }
References assert(), tsdn_s::tsd, and tsdn_null().
Referenced by arena_bin_choose_lock(), arena_dalloc(), arena_dalloc_large(), arena_dalloc_promoted(), arena_decay_ticks(), arena_malloc(), arena_malloc_hard(), arena_new(), arena_new_create_background_thread(), arena_postfork_child(), arena_sdalloc(), base_map(), base_unmap(), check_entry_exit_locking(), extent_addr_randomize(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), iallocztm(), idalloctm(), je_realloc(), large_palloc(), malloc_init_hard_cleanup(), prof_gdump(), prof_idump(), and prof_log_stop().