Azerotcore-wotlk: Acore::PlayerCommand Namespace Reference
Acore::PlayerCommand Namespace Reference
Functions
bool HandleLearnSpellCommand (ChatHandler *handler, Player *targetPlayer, SpellInfo const *spell, Optional< EXACT_SEQUENCE("all")> allRanks)
bool HandleUnlearnSpellCommand (ChatHandler *handler, Player *targetPlayer, SpellInfo const *spell, Optional< EXACT_SEQUENCE("all")> allRanks)
Function Documentation
HandleLearnSpellCommand()
bool Acore::PlayerCommand::HandleLearnSpellCommand (ChatHandler * handler, Player * targetPlayer, SpellInfo const * spell, Optional< EXACT_SEQUENCE("all")> allRanks)
Definition at line 22 of file PlayerCommand.cpp.
 {
     if (!SpellMgr::IsSpellValid(spell))
     {
         handler->PSendSysMessage(LANG_COMMAND_SPELL_BROKEN, spell->Id);
         handler->SetSentErrorMessage(true);
         return false;
     }
     if (!allRanks && targetPlayer->HasSpell(spell->Id))
     {
         if (targetPlayer == handler->GetPlayer())
             handler->SendSysMessage(LANG_YOU_KNOWN_SPELL);
         else
             handler->PSendSysMessage(LANG_TARGET_KNOWN_SPELL, handler->GetNameLink(targetPlayer).c_str());
         handler->SetSentErrorMessage(true);
         return false;
     }
     targetPlayer->learnSpell(spell->Id, false);
     if (allRanks)
     {
         uint32 spellId = spell->Id;
         while ((spellId = sSpellMgr->GetNextSpellInChain(spellId)))
             targetPlayer->learnSpell(spellId, false);
     }
     if (GetTalentSpellCost(spell->GetFirstRankSpell()->Id))
         targetPlayer->SendTalentsInfoData(false);
     return true;
 }
References SpellInfo::GetFirstRankSpell(), ChatHandler::GetNameLink(), ChatHandler::GetPlayer(), GetTalentSpellCost(), Player::HasSpell(), SpellInfo::Id, SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, LANG_TARGET_KNOWN_SPELL, LANG_YOU_KNOWN_SPELL, Player::learnSpell(), ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), Player::SendTalentsInfoData(), ChatHandler::SetSentErrorMessage(), and sSpellMgr.
Referenced by learn_commandscript::HandleLearnCommand(), and player_commandscript::HandlePlayerLearnCommand().
HandleUnlearnSpellCommand()
bool Acore::PlayerCommand::HandleUnlearnSpellCommand (ChatHandler * handler, Player * targetPlayer, SpellInfo const * spell, Optional< EXACT_SEQUENCE("all")> allRanks)
Definition at line 55 of file PlayerCommand.cpp.
 {
     uint32 spellId = spell->Id;
     if (allRanks)
         spellId = sSpellMgr->GetFirstSpellInChain (spellId);
     if (target->HasSpell(spellId))
         target->removeSpell(spellId, SPEC_MASK_ALL, false);
     else
         handler->SendSysMessage(LANG_FORGET_SPELL);
     if (GetTalentSpellCost(spellId))
         target->SendTalentsInfoData(false);
     return true;
 }
References GetTalentSpellCost(), Player::HasSpell(), SpellInfo::Id, LANG_FORGET_SPELL, Player::removeSpell(), ChatHandler::SendSysMessage(), Player::SendTalentsInfoData(), SPEC_MASK_ALL, and sSpellMgr.
Referenced by player_commandscript::HandlePlayerUnLearnCommand(), and learn_commandscript::HandleUnLearnCommand().