Azerotcore-wotlk: npc_tournament_training_dummy::npc_tournament_training_dummyAI Struct Reference
npc_tournament_training_dummy::npc_tournament_training_dummyAI Struct Reference
Public Member Functions
npc_tournament_training_dummyAI (Creature *creature)
void Reset () override
void EnterEvadeMode () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *caster, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool isVulnerable
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1558 of file zone_icecrown.cpp.
Constructor & Destructor Documentation
npc_tournament_training_dummyAI()
npc_tournament_training_dummy::npc_tournament_training_dummyAI::npc_tournament_training_dummyAI (Creature * creature) inline
Definition at line 1560 of file zone_icecrown.cpp.
                                                             : ScriptedAI(creature)
         {
             SetCombatMovement(false);
             me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
         }
References Unit::ApplySpellImmune(), IMMUNITY_EFFECT, ScriptedAI::me, ScriptedAI::SetCombatMovement(), and SPELL_EFFECT_KNOCK_BACK.
Member Function Documentation
DamageTaken()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1597 of file zone_icecrown.cpp.
         {
             damage = 0;
             events.RescheduleEvent(EVENT_DUMMY_RESET, 10000);
         }
References EVENT_DUMMY_RESET.
EnterEvadeMode()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1589 of file zone_icecrown.cpp.
         {
             if (!_EnterEvadeMode())
                 return;
             Reset();
         }
References CreatureAI::_EnterEvadeMode(), and Reset().
Referenced by UpdateAI().
MoveInLineOfSight()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1675 of file zone_icecrown.cpp.
 { }
Reset()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1569 of file zone_icecrown.cpp.
         {
             me->SetControlled(true, UNIT_STATE_STUNNED);
             isVulnerable = false;
             // Cast Defend spells to max stack size
             switch (me->GetEntry())
             {
                 case NPC_CHARGE_TARGET:
                     DoCast(SPELL_CHARGE_DEFEND);
                     break;
                 case NPC_RANGED_TARGET:
                     me->CastCustomSpell(SPELL_RANGED_DEFEND, SPELLVALUE_AURA_STACK, 3, me);
                     break;
             }
             events.Reset();
             events.ScheduleEvent(EVENT_DUMMY_RECAST_DEFEND, 5000);
         }
References Unit::CastCustomSpell(), UnitAI::DoCast(), EVENT_DUMMY_RECAST_DEFEND, Object::GetEntry(), isVulnerable, ScriptedAI::me, NPC_CHARGE_TARGET, NPC_RANGED_TARGET, Unit::SetControlled(), SPELL_CHARGE_DEFEND, SPELL_RANGED_DEFEND, SPELLVALUE_AURA_STACK, and UNIT_STATE_STUNNED.
Referenced by EnterEvadeMode().
SpellHit()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1603 of file zone_icecrown.cpp.
         {
             switch (me->GetEntry())
             {
                 case NPC_CHARGE_TARGET:
                     if (spell->Id == SPELL_PLAYER_CHARGE)
                         if (isVulnerable)
                             DoCast(caster, SPELL_CHARGE_CREDIT, true);
                     break;
                 case NPC_MELEE_TARGET:
                     if (spell->Id == SPELL_PLAYER_THRUST)
                     {
                         DoCast(caster, SPELL_MELEE_CREDIT, true);
                         if (Unit* target = caster->GetVehicleBase())
                             DoCast(target, SPELL_COUNTERATTACK, true);
                     }
                     break;
                 case NPC_RANGED_TARGET:
                     if (spell->Id == SPELL_PLAYER_BREAK_SHIELD)
                         if (isVulnerable)
                             DoCast(caster, SPELL_RANGED_CREDIT, true);
                     break;
             }
             if (spell->Id == SPELL_PLAYER_BREAK_SHIELD)
                 if (!me->HasAura(SPELL_CHARGE_DEFEND) && !me->HasAura(SPELL_RANGED_DEFEND))
                     isVulnerable = true;
         }
References UnitAI::DoCast(), Object::GetEntry(), Unit::GetVehicleBase(), Unit::HasAura(), SpellInfo::Id, isVulnerable, ScriptedAI::me, NPC_CHARGE_TARGET, NPC_MELEE_TARGET, NPC_RANGED_TARGET, SPELL_CHARGE_CREDIT, SPELL_CHARGE_DEFEND, SPELL_COUNTERATTACK, SPELL_MELEE_CREDIT, SPELL_PLAYER_BREAK_SHIELD, SPELL_PLAYER_CHARGE, SPELL_PLAYER_THRUST, SPELL_RANGED_CREDIT, and SPELL_RANGED_DEFEND.
UpdateAI()
void npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1633 of file zone_icecrown.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_DUMMY_RECAST_DEFEND:
                     switch (me->GetEntry())
                     {
                         case NPC_CHARGE_TARGET:
{
                                 if (!me->HasAura(SPELL_CHARGE_DEFEND))
                                     DoCast(SPELL_CHARGE_DEFEND);
                                 break;
                             }
                         case NPC_RANGED_TARGET:
{
                                 Aura* defend = me->GetAura(SPELL_RANGED_DEFEND);
                                 if (!defend || defend->GetStackAmount() < 3 || defend->GetDuration() <= 8000)
                                     DoCast(SPELL_RANGED_DEFEND);
                                 break;
                             }
                     }
                     isVulnerable = false;
                     events.ScheduleEvent(EVENT_DUMMY_RECAST_DEFEND, 5000);
                     break;
                 case EVENT_DUMMY_RESET:
                     if (UpdateVictim())
                     {
                         EnterEvadeMode();
                         events.ScheduleEvent(EVENT_DUMMY_RESET, 10000);
                     }
                     break;
             }
             if (!UpdateVictim())
                 return;
             if (!me->HasUnitState(UNIT_STATE_STUNNED))
                 me->SetControlled(true, UNIT_STATE_STUNNED);
         }
References diff(), UnitAI::DoCast(), EnterEvadeMode(), EVENT_DUMMY_RECAST_DEFEND, EVENT_DUMMY_RESET, Unit::GetAura(), Aura::GetDuration(), Object::GetEntry(), Aura::GetStackAmount(), Unit::HasAura(), Unit::HasUnitState(), isVulnerable, ScriptedAI::me, NPC_CHARGE_TARGET, NPC_RANGED_TARGET, Unit::SetControlled(), SPELL_CHARGE_DEFEND, SPELL_RANGED_DEFEND, UNIT_STATE_STUNNED, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_tournament_training_dummy::npc_tournament_training_dummyAI::events
Definition at line 1566 of file zone_icecrown.cpp.
isVulnerable
bool npc_tournament_training_dummy::npc_tournament_training_dummyAI::isVulnerable
Definition at line 1567 of file zone_icecrown.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_icecrown.cpp