Azerotcore-wotlk: Channel Class Reference
Channel Class Reference
#include <Channel.h>
Classes
struct PlayerInfo
Public Member Functions
Channel (std::string const &name, uint32 channel_id, uint32 channelDBId, TeamId teamId=TEAM_NEUTRAL, bool announce=true, bool ownership=true)
std::string const & GetName () const
uint32 GetChannelId () const
bool IsConstant () const
bool IsAnnounce () const
bool IsLFG () const
std::string const & GetPassword () const
void SetPassword (std::string const &npassword)
uint32 GetNumPlayers () const
uint8 GetFlags () const
bool HasFlag (uint8 flag) const
void JoinChannel (Player *player, std::string const &pass)
void LeaveChannel (Player *player, bool send=true)
void KickOrBan (Player const *player, std::string const &badname, bool ban)
void Kick (Player const *player, std::string const &badname)
void Ban (Player const *player, std::string const &badname)
void AddBan (ObjectGuid guid, uint32 time)
void UnBan (Player const *player, std::string const &badname)
void UnBan (ObjectGuid guid)
void Password (Player const *player, std::string const &pass)
void SetMode (Player const *player, std::string const &p2n, bool mod, bool set)
void SetOwner (ObjectGuid guid, bool exclaim=true)
void SetOwner (Player const *player, std::string const &name)
void SendWhoOwner (ObjectGuid guid)
void SetModerator (Player const *player, std::string const &newname)
void UnsetModerator (Player const *player, std::string const &newname)
void SetMute (Player const *player, std::string const &newname)
void UnsetMute (Player const *player, std::string const &newname)
void List (Player const *player)
void Announce (Player const *player)
void Say (ObjectGuid guid, std::string const &what, uint32 lang)
void Invite (Player const *player, std::string const &newp)
void Voice (ObjectGuid guid1, ObjectGuid guid2)
void DeVoice (ObjectGuid guid1, ObjectGuid guid2)
void JoinNotify (Player *p)
void LeaveNotify (Player *p)
void FlagsNotify (Player *p)
void ToggleModeration (Player *p)
void AddWatching (Player *p)
void RemoveWatching (Player *p)
Static Public Member Functions
static void CleanOldChannelsInDB ()
Private Types
typedef std::unordered_map< ObjectGuid, PlayerInfo > PlayerContainer
typedef std::unordered_map< ObjectGuid, uint32 > BannedContainer
typedef std::unordered_set< Player * > PlayersWatchingContainer
Private Member Functions
void MakeNotifyPacket (WorldPacket *data, uint8 notify_type)
void MakeJoined (WorldPacket *data, ObjectGuid guid)
void MakeLeft (WorldPacket *data, ObjectGuid guid)
void MakeYouJoined (WorldPacket *data)
void MakeYouLeft (WorldPacket *data)
void MakeWrongPassword (WorldPacket *data)
void MakeNotMember (WorldPacket *data)
void MakeNotModerator (WorldPacket *data)
void MakePasswordChanged (WorldPacket *data, ObjectGuid guid)
void MakeOwnerChanged (WorldPacket *data, ObjectGuid guid)
void MakePlayerNotFound (WorldPacket *data, std::string const &name)
void MakeNotOwner (WorldPacket *data)
void MakeChannelOwner (WorldPacket *data)
void MakeModeChange (WorldPacket *data, ObjectGuid guid, uint8 oldflags)
void MakeAnnouncementsOn (WorldPacket *data, ObjectGuid guid)
void MakeAnnouncementsOff (WorldPacket *data, ObjectGuid guid)
void MakeMuted (WorldPacket *data)
void MakePlayerKicked (WorldPacket *data, ObjectGuid bad, ObjectGuid good)
void MakeBanned (WorldPacket *data)
void MakePlayerBanned (WorldPacket *data, ObjectGuid bad, ObjectGuid good)
void MakePlayerUnbanned (WorldPacket *data, ObjectGuid bad, ObjectGuid good)
void MakePlayerNotBanned (WorldPacket *data, std::string const &name)
void MakePlayerAlreadyMember (WorldPacket *data, ObjectGuid guid)
void MakeInvite (WorldPacket *data, ObjectGuid guid)
void MakeInviteWrongFaction (WorldPacket *data)
void MakeWrongFaction (WorldPacket *data)
void MakeInvalidName (WorldPacket *data)
void MakeNotModerated (WorldPacket *data)
void MakePlayerInvited (WorldPacket *data, std::string const &name)
void MakePlayerInviteBanned (WorldPacket *data, std::string const &name)
void MakeThrottled (WorldPacket *data)
void MakeNotInArea (WorldPacket *data)
void MakeNotInLfg (WorldPacket *data)
void MakeVoiceOn (WorldPacket *data, ObjectGuid guid)
void MakeVoiceOff (WorldPacket *data, ObjectGuid guid)
void MakeModerationOn (WorldPacket *data, ObjectGuid guid)
void MakeModerationOff (WorldPacket *data, ObjectGuid guid)
void SendToAll (WorldPacket *data, ObjectGuid guid=ObjectGuid::Empty)
void SendToAllButOne (WorldPacket *data, ObjectGuid who)
void SendToOne (WorldPacket *data, ObjectGuid who)
void SendToAllWatching (WorldPacket *data)
bool IsOn (ObjectGuid who) const
bool IsBanned (ObjectGuid guid) const
void UpdateChannelInDB () const
void UpdateChannelUseageInDB () const
void AddChannelBanToDB (ObjectGuid guid, uint32 time) const
void RemoveChannelBanFromDB (ObjectGuid guid) const
uint8 GetPlayerFlags (ObjectGuid guid) const
void SetModerator (ObjectGuid guid, bool set)
void SetMute (ObjectGuid guid, bool set)
Private Attributes
bool _announce
bool _moderation
bool _ownership
bool _IsSaved
bool _isOwnerGM
uint8 _flags
uint32 _channelId
uint32 _channelDBId
TeamId _teamId
ObjectGuid _ownerGUID
std::string _name
std::string _password
ChannelRights _channelRights
PlayerContainer playersStore
BannedContainer bannedStore
PlayersWatchingContainer playersWatchingStore
Detailed Description
Definition at line 146 of file Channel.h.
Member Typedef Documentation
BannedContainer
typedef std::unordered_map<ObjectGuid, uint32> Channel::BannedContainer private
Definition at line 328 of file Channel.h.
PlayerContainer
typedef std::unordered_map<ObjectGuid, PlayerInfo> Channel::PlayerContainer private
Definition at line 327 of file Channel.h.
PlayersWatchingContainer
typedef std::unordered_set<Player*> Channel::PlayersWatchingContainer private
Definition at line 329 of file Channel.h.
Constructor & Destructor Documentation
Channel()
Channel::Channel (std::string const & name, uint32 channel_id, uint32 channelDBId, TeamId teamId = TEAM_NEUTRAL, bool announce = true, bool ownership = true)
Definition at line 27 of file Channel.cpp.
                                                                                                                          :
     _announce(announce),
     _ownership(ownership),
     _IsSaved(false),
     _isOwnerGM(false),
     _flags(0),
     _channelId(channelId),
     _channelDBId(channelDBId),
     _teamId(teamId),
     _name(name),
     _password("")
 {
     // set special flags if built-in channel
     if (ChatChannelsEntry const* ch = sChatChannelsStore.LookupEntry(channelId)) // check whether it's a built-in channel
     {
         _announce = false;                                 // no join/leave announces
         _ownership = false;                                // no ownership handout
         _flags |= CHANNEL_FLAG_GENERAL;                    // for all built-in channels
         if (ch->flags & CHANNEL_DBC_FLAG_TRADE)             // for trade channel
             _flags |= CHANNEL_FLAG_TRADE;
         if (ch->flags & CHANNEL_DBC_FLAG_CITY_ONLY2)        // for city only channels
             _flags |= CHANNEL_FLAG_CITY;
         if (ch->flags & CHANNEL_DBC_FLAG_LFG)               // for LFG channel
             _flags |= CHANNEL_FLAG_LFG;
         else                                                // for all other channels
             _flags |= CHANNEL_FLAG_NOT_LFG;
     }
     else                                                    // it's custom channel
     {
         _flags |= CHANNEL_FLAG_CUSTOM;
         // pussywizard:
         _channelRights = ChannelMgr::GetChannelRightsFor(_name);
         if (_channelRights.flags & CHANNEL_RIGHT_FORCE_NO_ANNOUNCEMENTS)
             _announce = false;
         if (_channelRights.flags & CHANNEL_RIGHT_FORCE_ANNOUNCEMENTS)
             _announce = true;
         if (_channelRights.flags & CHANNEL_RIGHT_NO_OWNERSHIP)
             _ownership = false;
         if (_channelRights.flags & CHANNEL_RIGHT_DONT_PRESERVE)
             return;
         _IsSaved = true;
         // Xinef: loading
         if (channelDBId > 0)
             return;
         // If storing custom channels in the db is enabled either load or save the channel
         if (sWorld->getBoolConfig(CONFIG_PRESERVE_CUSTOM_CHANNELS))
         {
             _channelDBId = ++ChannelMgr::_channelIdMax;
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHANNEL);
             stmt->setUInt32(0, _channelDBId);
             stmt->setString(1, name);
             stmt->setUInt32(2, _teamId);
             stmt->setUInt8(3, _announce);
             CharacterDatabase.Execute(stmt);
         }
     }
 }
References _announce, _channelDBId, ChannelMgr::_channelIdMax, _channelRights, _flags, _IsSaved, _name, _ownership, _teamId, CHANNEL_DBC_FLAG_CITY_ONLY2, CHANNEL_DBC_FLAG_LFG, CHANNEL_DBC_FLAG_TRADE, CHANNEL_FLAG_CITY, CHANNEL_FLAG_CUSTOM, CHANNEL_FLAG_GENERAL, CHANNEL_FLAG_LFG, CHANNEL_FLAG_NOT_LFG, CHANNEL_FLAG_TRADE, CHANNEL_RIGHT_DONT_PRESERVE, CHANNEL_RIGHT_FORCE_ANNOUNCEMENTS, CHANNEL_RIGHT_FORCE_NO_ANNOUNCEMENTS, CHANNEL_RIGHT_NO_OWNERSHIP, CHAR_INS_CHANNEL, CharacterDatabase, CONFIG_PRESERVE_CUSTOM_CHANNELS, ChannelRights::flags, ChannelMgr::GetChannelRightsFor(), sChatChannelsStore, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), and sWorld.
Member Function Documentation
AddBan()
void Channel::AddBan (ObjectGuid guid, uint32 time) inline
Definition at line 209 of file Channel.h.
 { bannedStore[guid] = time; }
References bannedStore.
Referenced by ChannelMgr::LoadChannels().
AddChannelBanToDB()
void Channel::AddChannelBanToDB (ObjectGuid guid, uint32 time) const private
Definition at line 121 of file Channel.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHANNEL_BAN);
     stmt->setUInt32(0, _channelDBId);
     stmt->setUInt32(1, guid.GetCounter());
     stmt->setUInt32(2, time);
     CharacterDatabase.Execute(stmt);
 }
References _channelDBId, CHAR_INS_CHANNEL_BAN, CharacterDatabase, ObjectGuid::GetCounter(), and PreparedStatementBase::setUInt32().
Referenced by KickOrBan().
AddWatching()
void Channel::AddWatching (Player * p)
Definition at line 1230 of file Channel.cpp.
 {
     if (!IsOn(p->GetGUID()))
         return;
     playersWatchingStore.insert(p);
 }
References Object::GetGUID(), IsOn(), and playersWatchingStore.
Announce()
void Channel::Announce (Player const * player)
Definition at line 732 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     uint32 sec = player->GetSession()->GetSecurity();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     if (!playersStore[guid].IsModerator() && !AccountMgr::IsGMAccount(sec))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     if (_channelRights.flags & (CHANNEL_RIGHT_FORCE_NO_ANNOUNCEMENTS | CHANNEL_RIGHT_FORCE_ANNOUNCEMENTS))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     _announce = !_announce;
     WorldPacket data;
     if (_announce)
         MakeAnnouncementsOn(&data, guid);
     else
         MakeAnnouncementsOff(&data, guid);
     SendToAll(&data);
     UpdateChannelInDB();
 }
References _announce, _channelRights, CHANNEL_RIGHT_FORCE_ANNOUNCEMENTS, CHANNEL_RIGHT_FORCE_NO_ANNOUNCEMENTS, ChannelRights::flags, Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsGMAccount(), IsOn(), MakeAnnouncementsOff(), MakeAnnouncementsOn(), MakeNotMember(), MakeNotModerator(), playersStore, SendToAll(), SendToOne(), and UpdateChannelInDB().
Ban()
void Channel::Ban (Player const * player, std::string const & badname) inline
Definition at line 208 of file Channel.h.
 { KickOrBan(player, badname, true); }
References KickOrBan().
CleanOldChannelsInDB()
void Channel::CleanOldChannelsInDB () static
Definition at line 138 of file Channel.cpp.
 {
     if (sWorld->getIntConfig(CONFIG_PRESERVE_CUSTOM_CHANNEL_DURATION) > 0)
     {
         CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_OLD_CHANNELS);
         stmt->setUInt32(0, sWorld->getIntConfig(CONFIG_PRESERVE_CUSTOM_CHANNEL_DURATION) * DAY);
         trans->Append(stmt);
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_OLD_CHANNELS_BANS);
         trans->Append(stmt);
         CharacterDatabase.CommitTransaction(trans);
     }
 }
References CHAR_DEL_OLD_CHANNELS, CHAR_DEL_OLD_CHANNELS_BANS, CharacterDatabase, CONFIG_PRESERVE_CUSTOM_CHANNEL_DURATION, DAY, PreparedStatementBase::setUInt32(), and sWorld.
Referenced by World::SetInitialWorldSettings().
DeVoice()
void Channel::DeVoice (ObjectGuid guid1, ObjectGuid guid2)
Definition at line 965 of file Channel.cpp.
 {
 }
FlagsNotify()
void Channel::FlagsNotify (Player * p)
Definition at line 1213 of file Channel.cpp.
 {
     if (_channelRights.flags & CHANNEL_RIGHT_CANT_SPEAK)
         return;
     if (!AccountMgr::IsPlayerAccount(p->GetSession()->GetSecurity()))
         return;
     WorldPacket data(SMSG_USERLIST_UPDATE, 8 + 1 + 1 + 4 + GetName().size());
     data << p->GetGUID();
     data << uint8(GetPlayerFlags(p->GetGUID()));
     data << uint8(GetFlags());
     data << uint32(GetNumPlayers());
     data << GetName();
     SendToAllWatching(&data);
 }
References _channelRights, CHANNEL_RIGHT_CANT_SPEAK, ChannelRights::flags, GetFlags(), Object::GetGUID(), GetName(), GetNumPlayers(), GetPlayerFlags(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsPlayerAccount(), SendToAllWatching(), and SMSG_USERLIST_UPDATE.
Referenced by JoinChannel(), SetModerator(), and SetOwner().
GetChannelId()
uint32 Channel::GetChannelId () const inline
Definition at line 194 of file Channel.h.
 { return _channelId; }
References _channelId.
Referenced by MakeYouJoined(), and MakeYouLeft().
GetFlags()
uint8 Channel::GetFlags () const inline
Definition at line 201 of file Channel.h.
 { return _flags; }
References _flags.
Referenced by FlagsNotify(), IsLFG(), JoinNotify(), LeaveNotify(), List(), and MakeYouJoined().
GetName()
std::string const& Channel::GetName () const inline
Definition at line 193 of file Channel.h.
 { return _name; }
References _name.
Referenced by FlagsNotify(), JoinNotify(), LeaveNotify(), List(), ChatLogScript::OnChat(), UnBan(), and Player::UpdateLocalChannels().
GetNumPlayers()
uint32 Channel::GetNumPlayers () const inline
Definition at line 200 of file Channel.h.
 { return playersStore.size(); }
References playersStore.
Referenced by FlagsNotify(), JoinNotify(), and LeaveNotify().
GetPassword()
std::string const& Channel::GetPassword () const inline
Definition at line 198 of file Channel.h.
 { return _password; }
References _password.
GetPlayerFlags()
uint8 Channel::GetPlayerFlags (ObjectGuid guid) const inline private
Definition at line 291 of file Channel.h.
     {
         PlayerContainer::const_iterator itr = playersStore.find(guid);
         return itr != playersStore.end() ? itr->second.flags : 0;
     }
References playersStore.
Referenced by FlagsNotify(), JoinNotify(), and MakeModeChange().
HasFlag()
bool Channel::HasFlag (uint8 flag) const inline
Definition at line 202 of file Channel.h.
 { return _flags & flag; }
References _flags.
Referenced by JoinChannel(), and ChatLogScript::OnChat().
Invite()
void Channel::Invite (Player const * player, std::string const & newp)
Definition at line 828 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     Player* newp = ObjectAccessor::FindPlayerByName(newname, false);
     if (!newp || !newp->isGMVisible())
     {
         WorldPacket data;
         MakePlayerNotFound(&data, newname);
         SendToOne(&data, guid);
         return;
     }
     if (IsBanned(newp->GetGUID()))
     {
         WorldPacket data;
         MakePlayerInviteBanned(&data, newname);
         SendToOne(&data, guid);
         return;
     }
     if (newp->GetTeamId() != player->GetTeamId())
     {
         WorldPacket data;
         MakeInviteWrongFaction(&data);
         SendToOne(&data, guid);
         return;
     }
     if (IsOn(newp->GetGUID()))
     {
         WorldPacket data;
         MakePlayerAlreadyMember(&data, newp->GetGUID());
         SendToOne(&data, guid);
         return;
     }
     if (!newp->GetSocial()->HasIgnore(guid))
     {
         WorldPacket data;
         MakeInvite(&data, guid);
         SendToOne(&data, newp->GetGUID());
         data.clear();
     }
     WorldPacket data;
     MakePlayerInvited(&data, newp->GetName());
     SendToOne(&data, guid);
 }
References ByteBuffer::clear(), ObjectAccessor::FindPlayerByName(), Object::GetGUID(), WorldObject::GetName(), Player::GetSocial(), Player::GetTeamId(), PlayerSocial::HasIgnore(), IsBanned(), Player::isGMVisible(), IsOn(), MakeInvite(), MakeInviteWrongFaction(), MakeNotMember(), MakePlayerAlreadyMember(), MakePlayerInviteBanned(), MakePlayerInvited(), MakePlayerNotFound(), and SendToOne().
IsAnnounce()
bool Channel::IsAnnounce () const inline
Definition at line 196 of file Channel.h.
 { return _announce; }
References _announce.
IsBanned()
bool Channel::IsBanned (ObjectGuid guid) const private
Definition at line 94 of file Channel.cpp.
 {
     BannedContainer::const_iterator itr = bannedStore.find(guid);
     return itr != bannedStore.end() && itr->second > time(nullptr);
 }
References bannedStore.
Referenced by Invite(), JoinChannel(), KickOrBan(), and UnBan().
IsConstant()
bool Channel::IsConstant () const inline
Definition at line 195 of file Channel.h.
 { return _channelId != 0; }
References _channelId.
Referenced by JoinChannel(), LeaveChannel(), MakeChannelOwner(), and MakeYouLeft().
IsLFG()
bool Channel::IsLFG () const inline
Definition at line 197 of file Channel.h.
 { return GetFlags() & CHANNEL_FLAG_LFG; }
References CHANNEL_FLAG_LFG, and GetFlags().
IsOn()
bool Channel::IsOn (ObjectGuid who) const inline private
Definition at line 283 of file Channel.h.
 { return playersStore.find(who) != playersStore.end(); }
References playersStore.
Referenced by AddWatching(), Announce(), Invite(), JoinChannel(), KickOrBan(), LeaveChannel(), List(), Password(), Say(), SendWhoOwner(), SetMode(), SetOwner(), ToggleModeration(), and UnBan().
JoinChannel()
void Channel::JoinChannel (Player * player, std::string const & pass)
Definition at line 155 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     if (IsOn(guid))
     {
         // Do not send error message for built-in channels
         if (!IsConstant())
         {
             WorldPacket data;
             MakePlayerAlreadyMember(&data, guid);
             SendToOne(&data, guid);
         }
         return;
     }
     if (IsBanned(guid))
     {
         WorldPacket data;
         MakeBanned(&data);
         SendToOne(&data, guid);
         return;
     }
     if (!_password.empty() && pass != _password)
     {
         WorldPacket data;
         MakeWrongPassword(&data);
         SendToOne(&data, guid);
         return;
     }
     if (HasFlag(CHANNEL_FLAG_LFG) &&
             sWorld->getBoolConfig(CONFIG_RESTRICTED_LFG_CHANNEL) &&
             AccountMgr::IsPlayerAccount(player->GetSession()->GetSecurity()) &&
             player->GetGroup())
     {
         WorldPacket data;
         MakeNotInLfg(&data);
         SendToOne(&data, guid);
         return;
     }
     player->JoinedChannel(this);
     if (_announce && (!AccountMgr::IsGMAccount(player->GetSession()->GetSecurity()) ||
                       !sWorld->getBoolConfig(CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL)))
     {
         WorldPacket data;
         MakeJoined(&data, guid);
         SendToAll(&data);
     }
     PlayerInfo pinfo;
     pinfo.player = guid;
     pinfo.flags = MEMBER_FLAG_NONE;
     pinfo.lastSpeakTime = 0;
     pinfo.plrPtr = player;
     playersStore[guid] = pinfo;
     if (_channelRights.joinMessage.length())
         ChatHandler(player->GetSession()).PSendSysMessage("%s", _channelRights.joinMessage.c_str());
     WorldPacket data;
     MakeYouJoined(&data);
     SendToOne(&data, guid);
     JoinNotify(player);
     playersStore[guid].SetOwnerGM(AccountMgr::IsGMAccount(player->GetSession()->GetSecurity()));
     // Custom channel handling
     if (!IsConstant())
     {
         // Update last_used timestamp in db
         if (!playersStore.empty())
             UpdateChannelUseageInDB();
         if (_channelRights.moderators.find(player->GetSession()->GetAccountId()) != _channelRights.moderators.end())
         {
             playersStore[guid].SetModerator(true);
             FlagsNotify(player);
         }
         // If the channel has no owner yet and ownership is allowed, set the new owner.
         // If the channel owner is a GM and the config SilentGMJoinChannel is enabled, set the new owner
         if ((!_ownerGUID || (_isOwnerGM && sWorld->getBoolConfig(CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL))) && _ownership)
         {
             _isOwnerGM = playersStore[guid].IsOwnerGM();
             SetOwner(guid, false);
         }
         if (_channelRights.flags & CHANNEL_RIGHT_CANT_SPEAK)
             playersStore[guid].SetMuted(true);
     }
 }
References _announce, _channelRights, _isOwnerGM, _ownerGUID, _ownership, _password, CHANNEL_FLAG_LFG, CHANNEL_RIGHT_CANT_SPEAK, CONFIG_RESTRICTED_LFG_CHANNEL, CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL, ChannelRights::flags, Channel::PlayerInfo::flags, FlagsNotify(), WorldSession::GetAccountId(), Player::GetGroup(), Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), HasFlag(), IsBanned(), IsConstant(), AccountMgr::IsGMAccount(), IsOn(), AccountMgr::IsPlayerAccount(), Player::JoinedChannel(), ChannelRights::joinMessage, JoinNotify(), Channel::PlayerInfo::lastSpeakTime, MakeBanned(), MakeJoined(), MakeNotInLfg(), MakePlayerAlreadyMember(), MakeWrongPassword(), MakeYouJoined(), MEMBER_FLAG_NONE, ChannelRights::moderators, Channel::PlayerInfo::player, playersStore, Channel::PlayerInfo::plrPtr, ChatHandler::PSendSysMessage(), SendToAll(), SendToOne(), SetOwner(), sWorld, and UpdateChannelUseageInDB().
Referenced by Player::UpdateLocalChannels().
JoinNotify()
void Channel::JoinNotify (Player * p)
Definition at line 1180 of file Channel.cpp.
 {
     if (_channelRights.flags & CHANNEL_RIGHT_CANT_SPEAK)
         return;
     if (!AccountMgr::IsPlayerAccount(p->GetSession()->GetSecurity()))
         return;
     WorldPacket data(SMSG_USERLIST_ADD, 8 + 1 + 1 + 4 + GetName().size());
     data << p->GetGUID();
     data << uint8(GetPlayerFlags(p->GetGUID()));
     data << uint8(GetFlags());
     data << uint32(GetNumPlayers());
     data << GetName();
     SendToAllWatching(&data);
 }
References _channelRights, CHANNEL_RIGHT_CANT_SPEAK, ChannelRights::flags, GetFlags(), Object::GetGUID(), GetName(), GetNumPlayers(), GetPlayerFlags(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsPlayerAccount(), SendToAllWatching(), and SMSG_USERLIST_ADD.
Referenced by JoinChannel().
Kick()
void Channel::Kick (Player const * player, std::string const & badname) inline
Definition at line 207 of file Channel.h.
 { KickOrBan(player, badname, false); }
References KickOrBan().
KickOrBan()
void Channel::KickOrBan (Player const * player, std::string const & badname, bool ban)
Definition at line 319 of file Channel.cpp.
 {
     AccountTypes sec = player->GetSession()->GetSecurity();
     ObjectGuid good = player->GetGUID();
     if (!IsOn(good))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, good);
         return;
     }
     if (!playersStore[good].IsModerator() && !AccountMgr::IsGMAccount(sec))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, good);
         return;
     }
     bool banOffline = false; // pussywizard
     bool isGoodConstantModerator = _channelRights.moderators.find(player->GetSession()->GetAccountId()) != _channelRights.moderators.end();
     ObjectGuid victim;
     uint32 badAccId = 0;
     uint32 badSecurity = 0;
     Player* bad = ObjectAccessor::FindPlayerByName(badname, false);
     if (bad)
     {
         victim = bad->GetGUID();
         badAccId = bad->GetSession()->GetAccountId();
         badSecurity = bad->GetSession()->GetSecurity();
     }
     bool isOnChannel = victim && IsOn(victim);
     if (!isOnChannel)
     {
         if (ban && (AccountMgr::IsGMAccount(sec) || isGoodConstantModerator))
         {
             if (ObjectGuid guid = sWorld->GetGlobalPlayerGUID(badname))
                 if (const GlobalPlayerData* gpd = sWorld->GetGlobalPlayerData(guid.GetCounter()))
                 {
                     if (Player::TeamIdForRace(gpd->race) == Player::TeamIdForRace(player->getRace()))
                     {
                         banOffline = true;
                         victim = guid;
                         badAccId = gpd->accountId;
                     }
                     else
                     {
                         ChatHandler(player->GetSession()).PSendSysMessage("Character %s has other faction!", badname.c_str());
                         return;
                     }
                 }
             if (!banOffline)
             {
                 WorldPacket data;
                 MakePlayerNotFound(&data, badname);
                 SendToOne(&data, good);
                 return;
             }
         }
         else
         {
             WorldPacket data;
             MakePlayerNotFound(&data, badname);
             SendToOne(&data, good);
             return;
         }
     }
     bool changeowner = _ownerGUID == victim;
     bool isBadConstantModerator = _channelRights.moderators.find(badAccId) != _channelRights.moderators.end();
     if (!AccountMgr::IsGMAccount(sec) && !isGoodConstantModerator)
     {
         if (changeowner && good != _ownerGUID)
         {
             WorldPacket data;
             MakeNotOwner(&data);
             SendToOne(&data, good);
             return;
         }
         if ((ban && (_channelRights.flags & CHANNEL_RIGHT_CANT_BAN)) || (!ban && (_channelRights.flags & CHANNEL_RIGHT_CANT_KICK)))
         {
             WorldPacket data;
             MakeNotModerator(&data);
             SendToOne(&data, good);
             return;
         }
         if (isBadConstantModerator || AccountMgr::IsGMAccount(badSecurity))
         {
             WorldPacket data;
             MakeNotModerator(&data);
             SendToOne(&data, good);
             return;
         }
     }
     bool notify = !(AccountMgr::IsGMAccount(sec) && sWorld->getBoolConfig(CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL));
     if (ban)
     {
         if (!IsBanned(victim))
         {
             bannedStore[victim] = time(nullptr) + CHANNEL_BAN_DURATION;
             AddChannelBanToDB(victim, time(nullptr) + CHANNEL_BAN_DURATION);
             if (notify)
             {
                 WorldPacket data;
                 MakePlayerBanned(&data, victim, good);
                 SendToAll(&data);
             }
         }
     }
     else if (notify)
     {
         WorldPacket data;
         MakePlayerKicked(&data, victim, good);
         SendToAll(&data);
     }
     if (isOnChannel)
     {
         playersStore.erase(victim);
         bad->LeftChannel(this);
         RemoveWatching(bad);
         LeaveNotify(bad);
     }
     if (changeowner && _ownership)
     {
         if (good != victim)
             SetOwner(good);
         else if (!playersStore.empty())
         {
             ObjectGuid newowner;
             for (Channel::PlayerContainer::const_iterator itr = playersStore.begin(); itr != playersStore.end(); ++itr)
             {
                 newowner = itr->second.player;
                 if (!itr->second.plrPtr->GetSession()->GetSecurity())
                     break;
             }
             SetOwner(newowner);
         }
         else
             SetOwner(ObjectGuid::Empty);
     }
 }
References _channelRights, _ownerGUID, _ownership, AddChannelBanToDB(), bannedStore, CHANNEL_BAN_DURATION, CHANNEL_RIGHT_CANT_BAN, CHANNEL_RIGHT_CANT_KICK, CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL, ObjectGuid::Empty, ObjectAccessor::FindPlayerByName(), ChannelRights::flags, WorldSession::GetAccountId(), Object::GetGUID(), Unit::getRace(), WorldSession::GetSecurity(), Player::GetSession(), IsBanned(), AccountMgr::IsGMAccount(), IsOn(), LeaveNotify(), Player::LeftChannel(), MakeNotMember(), MakeNotModerator(), MakeNotOwner(), MakePlayerBanned(), MakePlayerKicked(), MakePlayerNotFound(), ChannelRights::moderators, playersStore, ChatHandler::PSendSysMessage(), RemoveWatching(), SendToAll(), SendToOne(), SetOwner(), sWorld, and Player::TeamIdForRace().
Referenced by Ban(), and Kick().
LeaveChannel()
void Channel::LeaveChannel (Player * player, bool send = true)
Definition at line 252 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     if (!IsOn(guid))
     {
         if (send)
         {
             WorldPacket data;
             MakeNotMember(&data);
             SendToOne(&data, guid);
         }
         return;
     }
     if (send)
     {
         WorldPacket data;
         MakeYouLeft(&data);
         SendToOne(&data, guid);
         player->LeftChannel(this);
         data.clear();
     }
     bool changeowner = playersStore[guid].IsOwner();
     playersStore.erase(guid);
     if (_announce && (!AccountMgr::IsGMAccount(player->GetSession()->GetSecurity()) ||
                       !sWorld->getBoolConfig(CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL)))
     {
         WorldPacket data;
         MakeLeft(&data, guid);
         SendToAll(&data);
     }
     RemoveWatching(player);
     LeaveNotify(player);
     if (!IsConstant())
     {
         // Update last_used timestamp in db
         UpdateChannelUseageInDB();
         // If the channel owner left and there are still playersStore inside, pick a new owner
         if (changeowner && _ownership)
         {
             if (!playersStore.empty())
             {
                 ObjectGuid newowner;
                 for (Channel::PlayerContainer::const_iterator itr = playersStore.begin(); itr != playersStore.end(); ++itr)
                 {
                     newowner = itr->second.player;
                     if (AccountMgr::IsGMAccount(itr->second.plrPtr->GetSession()->GetSecurity()))
                         _isOwnerGM = true;
                     else
                         _isOwnerGM = false;
                     if (!itr->second.plrPtr->GetSession()->GetSecurity())
                         break;
                 }
                 SetOwner(newowner);
                 // if the new owner is invisible gm, set flag to automatically choose a new owner
             }
             else
                 SetOwner(ObjectGuid::Empty);
         }
     }
 }
References _announce, _isOwnerGM, _ownership, ByteBuffer::clear(), CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL, ObjectGuid::Empty, Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), IsConstant(), AccountMgr::IsGMAccount(), IsOn(), LeaveNotify(), Player::LeftChannel(), MakeLeft(), MakeNotMember(), MakeYouLeft(), playersStore, RemoveWatching(), SendToAll(), SendToOne(), SetOwner(), sWorld, and UpdateChannelUseageInDB().
Referenced by Player::CleanupChannels(), and Player::UpdateLocalChannels().
LeaveNotify()
void Channel::LeaveNotify (Player * p)
Definition at line 1197 of file Channel.cpp.
 {
     if (_channelRights.flags & CHANNEL_RIGHT_CANT_SPEAK)
         return;
     if (!AccountMgr::IsPlayerAccount(p->GetSession()->GetSecurity()))
         return;
     WorldPacket data(SMSG_USERLIST_REMOVE, 8 + 1 + 4 + GetName().size());
     data << p->GetGUID();
     data << uint8(GetFlags());
     data << uint32(GetNumPlayers());
     data << GetName();
     SendToAllWatching(&data);
 }
References _channelRights, CHANNEL_RIGHT_CANT_SPEAK, ChannelRights::flags, GetFlags(), Object::GetGUID(), GetName(), GetNumPlayers(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsPlayerAccount(), SendToAllWatching(), and SMSG_USERLIST_REMOVE.
Referenced by KickOrBan(), and LeaveChannel().
List()
void Channel::List (Player const * player)
Definition at line 696 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     LOG_DEBUG("chat.system", "SMSG_CHANNEL_LIST %s Channel: %s", player->GetSession()->GetPlayerInfo().c_str(), GetName().c_str());
     WorldPacket data(SMSG_CHANNEL_LIST, 1 + (GetName().size() + 1) + 1 + 4 + playersStore.size() * (8 + 1));
     data << uint8(1);                                   // channel type?
     data << GetName();                                  // channel name
     data << uint8(GetFlags());                          // channel flags?
     size_t pos = data.wpos();
     data << uint32(0);                                  // size of list, placeholder
     uint32 count  = 0;
     if (!(_channelRights.flags & CHANNEL_RIGHT_CANT_SPEAK))
         for (PlayerContainer::const_iterator i = playersStore.begin(); i != playersStore.end(); ++i)
             if (AccountMgr::IsPlayerAccount(i->second.plrPtr->GetSession()->GetSecurity()))
             {
                 data << i->first;
                 data << uint8(i->second.flags); // flags seems to be changed...
                 ++count;
             }
     data.put<uint32>(pos, count);
     SendToOne(&data, guid);
 }
References _channelRights, CHANNEL_RIGHT_CANT_SPEAK, ChannelRights::flags, GetFlags(), Object::GetGUID(), GetName(), WorldSession::GetPlayerInfo(), Player::GetSession(), IsOn(), AccountMgr::IsPlayerAccount(), LOG_DEBUG, MakeNotMember(), playersStore, ByteBuffer::put(), SendToOne(), SMSG_CHANNEL_LIST, and ByteBuffer::wpos().
MakeAnnouncementsOff()
void Channel::MakeAnnouncementsOff (WorldPacket * data, ObjectGuid guid) private
Definition at line 1066 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_ANNOUNCEMENTS_OFF_NOTICE);
     *data << guid;
 }
References CHAT_ANNOUNCEMENTS_OFF_NOTICE, and MakeNotifyPacket().
Referenced by Announce().
MakeAnnouncementsOn()
void Channel::MakeAnnouncementsOn (WorldPacket * data, ObjectGuid guid) private
Definition at line 1060 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_ANNOUNCEMENTS_ON_NOTICE);
     *data << guid;
 }
References CHAT_ANNOUNCEMENTS_ON_NOTICE, and MakeNotifyPacket().
Referenced by Announce().
MakeBanned()
void Channel::MakeBanned (WorldPacket * data) private
Definition at line 1084 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_BANNED_NOTICE);
 }
References CHAT_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by JoinChannel().
MakeChannelOwner()
void Channel::MakeChannelOwner (WorldPacket * data) private
Definition at line 1041 of file Channel.cpp.
 {
     std::string name = "";
     if (!sObjectMgr->GetPlayerNameByGUID(_ownerGUID.GetCounter(), name) || name.empty())
         name = "PLAYER_NOT_FOUND";
     MakeNotifyPacket(data, CHAT_CHANNEL_OWNER_NOTICE);
     *data << ((IsConstant() || !_ownerGUID) ? "Nobody" : name);
 }
References _ownerGUID, CHAT_CHANNEL_OWNER_NOTICE, ObjectGuid::GetCounter(), IsConstant(), MakeNotifyPacket(), and sObjectMgr.
Referenced by SendWhoOwner().
MakeInvalidName()
void Channel::MakeInvalidName (WorldPacket * data) private
Definition at line 1131 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_INVALID_NAME_NOTICE);
 }
References CHAT_INVALID_NAME_NOTICE, and MakeNotifyPacket().
MakeInvite()
void Channel::MakeInvite (WorldPacket * data, ObjectGuid guid) private
Definition at line 1115 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_INVITE_NOTICE);
     *data << guid;
 }
References CHAT_INVITE_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakeInviteWrongFaction()
void Channel::MakeInviteWrongFaction (WorldPacket * data) private
Definition at line 1121 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_INVITE_WRONG_FACTION_NOTICE);
 }
References CHAT_INVITE_WRONG_FACTION_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakeJoined()
void Channel::MakeJoined (WorldPacket * data, ObjectGuid guid) private
Definition at line 976 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_JOINED_NOTICE);
     *data << guid;
 }
References CHAT_JOINED_NOTICE, and MakeNotifyPacket().
Referenced by JoinChannel().
MakeLeft()
void Channel::MakeLeft (WorldPacket * data, ObjectGuid guid) private
Definition at line 982 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_LEFT_NOTICE);
     *data << guid;
 }
References CHAT_LEFT_NOTICE, and MakeNotifyPacket().
Referenced by LeaveChannel().
MakeModeChange()
void Channel::MakeModeChange (WorldPacket * data, ObjectGuid guid, uint8 oldflags) private
Definition at line 1052 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_MODE_CHANGE_NOTICE);
     *data << guid;
     *data << uint8(oldflags);
     *data << uint8(GetPlayerFlags(guid));
 }
References CHAT_MODE_CHANGE_NOTICE, GetPlayerFlags(), and MakeNotifyPacket().
Referenced by SetModerator(), SetMute(), and SetOwner().
MakeModerationOff()
void Channel::MakeModerationOff (WorldPacket * data, ObjectGuid guid) private
Definition at line 1289 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_MODERATION_OFF_NOTICE);
     *data << guid;
 }
References CHAT_MODERATION_OFF_NOTICE, and MakeNotifyPacket().
Referenced by ToggleModeration().
MakeModerationOn()
void Channel::MakeModerationOn (WorldPacket * data, ObjectGuid guid) private
Definition at line 1283 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_MODERATION_ON_NOTICE);
     *data << guid;
 }
References CHAT_MODERATION_ON_NOTICE, and MakeNotifyPacket().
Referenced by ToggleModeration().
MakeMuted()
void Channel::MakeMuted (WorldPacket * data) private
Definition at line 1072 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_MUTED_NOTICE);
 }
References CHAT_MUTED_NOTICE, and MakeNotifyPacket().
Referenced by Say().
MakeNotifyPacket()
void Channel::MakeNotifyPacket (WorldPacket * data, uint8 notify_type) private
Definition at line 969 of file Channel.cpp.
 {
     data->Initialize(SMSG_CHANNEL_NOTIFY, 1 + _name.size());
     *data << uint8(notify_type);
     *data << _name;
 }
References _name, WorldPacket::Initialize(), and SMSG_CHANNEL_NOTIFY.
Referenced by MakeAnnouncementsOff(), MakeAnnouncementsOn(), MakeBanned(), MakeChannelOwner(), MakeInvalidName(), MakeInvite(), MakeInviteWrongFaction(), MakeJoined(), MakeLeft(), MakeModeChange(), MakeModerationOff(), MakeModerationOn(), MakeMuted(), MakeNotInArea(), MakeNotInLfg(), MakeNotMember(), MakeNotModerated(), MakeNotModerator(), MakeNotOwner(), MakeOwnerChanged(), MakePasswordChanged(), MakePlayerAlreadyMember(), MakePlayerBanned(), MakePlayerInviteBanned(), MakePlayerInvited(), MakePlayerKicked(), MakePlayerNotBanned(), MakePlayerNotFound(), MakePlayerUnbanned(), MakeThrottled(), MakeVoiceOff(), MakeVoiceOn(), MakeWrongFaction(), MakeWrongPassword(), MakeYouJoined(), and MakeYouLeft().
MakeNotInArea()
void Channel::MakeNotInArea (WorldPacket * data) private
Definition at line 1158 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_IN_AREA_NOTICE);
 }
References CHAT_NOT_IN_AREA_NOTICE, and MakeNotifyPacket().
MakeNotInLfg()
void Channel::MakeNotInLfg (WorldPacket * data) private
Definition at line 1163 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_IN_LFG_NOTICE);
 }
References CHAT_NOT_IN_LFG_NOTICE, and MakeNotifyPacket().
Referenced by JoinChannel().
MakeNotMember()
void Channel::MakeNotMember (WorldPacket * data) private
Definition at line 1008 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_MEMBER_NOTICE);
 }
References CHAT_NOT_MEMBER_NOTICE, and MakeNotifyPacket().
Referenced by Announce(), Invite(), KickOrBan(), LeaveChannel(), List(), Password(), Say(), SendWhoOwner(), SetMode(), SetOwner(), ToggleModeration(), and UnBan().
MakeNotModerated()
void Channel::MakeNotModerated (WorldPacket * data) private
Definition at line 1136 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_MODERATED_NOTICE);
 }
References CHAT_NOT_MODERATED_NOTICE, and MakeNotifyPacket().
MakeNotModerator()
void Channel::MakeNotModerator (WorldPacket * data) private
Definition at line 1013 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_MODERATOR_NOTICE);
 }
References CHAT_NOT_MODERATOR_NOTICE, and MakeNotifyPacket().
Referenced by Announce(), KickOrBan(), Password(), SetMode(), ToggleModeration(), and UnBan().
MakeNotOwner()
void Channel::MakeNotOwner (WorldPacket * data) private
Definition at line 1036 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_NOT_OWNER_NOTICE);
 }
References CHAT_NOT_OWNER_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan(), SetMode(), and SetOwner().
MakeOwnerChanged()
void Channel::MakeOwnerChanged (WorldPacket * data, ObjectGuid guid) private
Definition at line 1024 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_OWNER_CHANGED_NOTICE);
     *data << guid;
 }
References CHAT_OWNER_CHANGED_NOTICE, and MakeNotifyPacket().
Referenced by SetOwner().
MakePasswordChanged()
void Channel::MakePasswordChanged (WorldPacket * data, ObjectGuid guid) private
Definition at line 1018 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PASSWORD_CHANGED_NOTICE);
     *data << guid;
 }
References CHAT_PASSWORD_CHANGED_NOTICE, and MakeNotifyPacket().
Referenced by Password().
MakePlayerAlreadyMember()
void Channel::MakePlayerAlreadyMember (WorldPacket * data, ObjectGuid guid) private
Definition at line 1109 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_ALREADY_MEMBER_NOTICE);
     *data << guid;
 }
References CHAT_PLAYER_ALREADY_MEMBER_NOTICE, and MakeNotifyPacket().
Referenced by Invite(), and JoinChannel().
MakePlayerBanned()
void Channel::MakePlayerBanned (WorldPacket * data, ObjectGuid bad, ObjectGuid good) private
Definition at line 1089 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_BANNED_NOTICE);
     *data << bad;
     *data << good;
 }
References CHAT_PLAYER_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan().
MakePlayerInviteBanned()
void Channel::MakePlayerInviteBanned (WorldPacket * data, std::string const & name) private
Definition at line 1147 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_INVITE_BANNED_NOTICE);
     *data << name;
 }
References CHAT_PLAYER_INVITE_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakePlayerInvited()
void Channel::MakePlayerInvited (WorldPacket * data, std::string const & name) private
Definition at line 1141 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_INVITED_NOTICE);
     *data << name;
 }
References CHAT_PLAYER_INVITED_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakePlayerKicked()
void Channel::MakePlayerKicked (WorldPacket * data, ObjectGuid bad, ObjectGuid good) private
Definition at line 1077 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_KICKED_NOTICE);
     *data << bad;
     *data << good;
 }
References CHAT_PLAYER_KICKED_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan().
MakePlayerNotBanned()
void Channel::MakePlayerNotBanned (WorldPacket * data, std::string const & name) private
Definition at line 1103 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_NOT_BANNED_NOTICE);
     *data << name;
 }
References CHAT_PLAYER_NOT_BANNED_NOTICE, and MakeNotifyPacket().
MakePlayerNotFound()
void Channel::MakePlayerNotFound (WorldPacket * data, std::string const & name) private
Definition at line 1030 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_NOT_FOUND_NOTICE);
     *data << name;
 }
References CHAT_PLAYER_NOT_FOUND_NOTICE, and MakeNotifyPacket().
Referenced by Invite(), KickOrBan(), SetMode(), SetOwner(), and UnBan().
MakePlayerUnbanned()
void Channel::MakePlayerUnbanned (WorldPacket * data, ObjectGuid bad, ObjectGuid good) private
Definition at line 1096 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_PLAYER_UNBANNED_NOTICE);
     *data << bad;
     *data << good;
 }
References CHAT_PLAYER_UNBANNED_NOTICE, and MakeNotifyPacket().
Referenced by UnBan().
MakeThrottled()
void Channel::MakeThrottled (WorldPacket * data) private
Definition at line 1153 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_THROTTLED_NOTICE);
 }
References CHAT_THROTTLED_NOTICE, and MakeNotifyPacket().
MakeVoiceOff()
void Channel::MakeVoiceOff (WorldPacket * data, ObjectGuid guid) private
Definition at line 1174 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_VOICE_OFF_NOTICE);
     *data << guid;
 }
References CHAT_VOICE_OFF_NOTICE, and MakeNotifyPacket().
MakeVoiceOn()
void Channel::MakeVoiceOn (WorldPacket * data, ObjectGuid guid) private
Definition at line 1168 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_VOICE_ON_NOTICE);
     *data << guid;
 }
References CHAT_VOICE_ON_NOTICE, and MakeNotifyPacket().
MakeWrongFaction()
void Channel::MakeWrongFaction (WorldPacket * data) private
Definition at line 1126 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_WRONG_FACTION_NOTICE);
 }
References CHAT_WRONG_FACTION_NOTICE, and MakeNotifyPacket().
MakeWrongPassword()
void Channel::MakeWrongPassword (WorldPacket * data) private
Definition at line 1003 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_WRONG_PASSWORD_NOTICE);
 }
References CHAT_WRONG_PASSWORD_NOTICE, and MakeNotifyPacket().
Referenced by JoinChannel().
MakeYouJoined()
void Channel::MakeYouJoined (WorldPacket * data) private
Definition at line 988 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_YOU_JOINED_NOTICE);
     *data << uint8(GetFlags());
     *data << uint32(GetChannelId());
     *data << uint32(0);
 }
References CHAT_YOU_JOINED_NOTICE, GetChannelId(), GetFlags(), and MakeNotifyPacket().
Referenced by JoinChannel().
MakeYouLeft()
void Channel::MakeYouLeft (WorldPacket * data) private
Definition at line 996 of file Channel.cpp.
 {
     MakeNotifyPacket(data, CHAT_YOU_LEFT_NOTICE);
     *data << uint32(GetChannelId());
     *data << uint8(IsConstant());
 }
References CHAT_YOU_LEFT_NOTICE, GetChannelId(), IsConstant(), and MakeNotifyPacket().
Referenced by LeaveChannel().
Password()
void Channel::Password (Player const * player, std::string const & pass)
Definition at line 540 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     ChatHandler chat(player->GetSession());
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     if (!playersStore[guid].IsModerator() && !AccountMgr::IsGMAccount(player->GetSession()->GetSecurity()))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     if (_channelRights.flags & CHANNEL_RIGHT_CANT_CHANGE_PASSWORD)
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     _password = pass;
     WorldPacket data;
     MakePasswordChanged(&data, guid);
     SendToAll(&data);
     UpdateChannelInDB();
 }
References _channelRights, _password, CHANNEL_RIGHT_CANT_CHANGE_PASSWORD, ChannelRights::flags, Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsGMAccount(), IsOn(), MakeNotMember(), MakeNotModerator(), MakePasswordChanged(), playersStore, SendToAll(), SendToOne(), and UpdateChannelInDB().
RemoveChannelBanFromDB()
void Channel::RemoveChannelBanFromDB (ObjectGuid guid) const private
Definition at line 130 of file Channel.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHANNEL_BAN);
     stmt->setUInt32(0, _channelDBId);
     stmt->setUInt32(1, guid.GetCounter());
     CharacterDatabase.Execute(stmt);
 }
References _channelDBId, CHAR_DEL_CHANNEL_BAN, CharacterDatabase, ObjectGuid::GetCounter(), and PreparedStatementBase::setUInt32().
Referenced by UnBan().
RemoveWatching()
void Channel::RemoveWatching (Player * p)
Definition at line 1237 of file Channel.cpp.
 {
     PlayersWatchingContainer::iterator itr = playersWatchingStore.find(p);
     if (itr != playersWatchingStore.end())
         playersWatchingStore.erase(itr);
 }
References playersWatchingStore.
Referenced by KickOrBan(), and LeaveChannel().
Say()
void Channel::Say (ObjectGuid guid, std::string const & what, uint32 lang)
Definition at line 773 of file Channel.cpp.
 {
     if (what.empty())
         return;
     if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL))
         lang = LANG_UNIVERSAL;
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     PlayerInfo& pinfo = playersStore[guid];
     if (pinfo.IsMuted())
     {
         WorldPacket data;
         MakeMuted(&data);
         SendToOne(&data, guid);
         return;
     }
     Player* player = pinfo.plrPtr;
     if (player && player->GetSession()->GetSecurity() == AccountTypes::SEC_PLAYER) // pussywizard: prevent spam on populated channels
     {
         uint32 speakDelay = 0;
         if (_channelRights.speakDelay > 0)
             speakDelay = _channelRights.speakDelay;
         else if (playersStore.size() >= 10)
             speakDelay = 5;
         if (!pinfo.IsAllowedToSpeak(speakDelay))
         {
             std::string timeStr = secsToTimeString(pinfo.lastSpeakTime + speakDelay - sWorld->GetGameTime());
             if (_channelRights.speakMessage.length() > 0)
                 player->GetSession()->SendNotification("%s", _channelRights.speakMessage.c_str());
             player->GetSession()->SendNotification("You must wait %s before speaking again.", timeStr.c_str());
             return;
         }
     }
     WorldPacket data;
     if (player)
         ChatHandler::BuildChatPacket(data, CHAT_MSG_CHANNEL, Language(lang), player, player, what, 0, _name);
     else
         ChatHandler::BuildChatPacket(data, CHAT_MSG_CHANNEL, Language(lang), guid, guid, what, 0, "", "", 0, false, _name);
     SendToAll(&data, pinfo.IsModerator() ? ObjectGuid::Empty : guid);
 }
References _channelRights, _name, ChatHandler::BuildChatPacket(), CHAT_MSG_CHANNEL, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, ObjectGuid::Empty, WorldSession::GetSecurity(), Player::GetSession(), Channel::PlayerInfo::IsAllowedToSpeak(), Channel::PlayerInfo::IsModerator(), Channel::PlayerInfo::IsMuted(), IsOn(), LANG_UNIVERSAL, Channel::PlayerInfo::lastSpeakTime, MakeMuted(), MakeNotMember(), playersStore, Channel::PlayerInfo::plrPtr, SEC_PLAYER, secsToTimeString(), WorldSession::SendNotification(), SendToAll(), SendToOne(), ChannelRights::speakDelay, ChannelRights::speakMessage, and sWorld.
SendToAll()
void Channel::SendToAll (WorldPacket * data, ObjectGuid guid = ObjectGuid::Empty) private
Definition at line 935 of file Channel.cpp.
 {
     for (PlayerContainer::const_iterator i = playersStore.begin(); i != playersStore.end(); ++i)
         if (!guid || !i->second.plrPtr->GetSocial()->HasIgnore(guid))
             i->second.plrPtr->GetSession()->SendPacket(data);
 }
References playersStore.
Referenced by Announce(), JoinChannel(), KickOrBan(), LeaveChannel(), Password(), Say(), SetModerator(), SetMute(), SetOwner(), ToggleModeration(), and UnBan().
SendToAllButOne()
void Channel::SendToAllButOne (WorldPacket * data, ObjectGuid who) private
Definition at line 942 of file Channel.cpp.
 {
     for (PlayerContainer::const_iterator i = playersStore.begin(); i != playersStore.end(); ++i)
         if (i->first != who)
             i->second.plrPtr->GetSession()->SendPacket(data);
 }
References playersStore.
SendToAllWatching()
void Channel::SendToAllWatching (WorldPacket * data) private
Definition at line 955 of file Channel.cpp.
 {
     for (PlayersWatchingContainer::const_iterator i = playersWatchingStore.begin(); i != playersWatchingStore.end(); ++i)
         (*i)->GetSession()->SendPacket(data);
 }
References playersWatchingStore.
Referenced by FlagsNotify(), JoinNotify(), and LeaveNotify().
SendToOne()
void Channel::SendToOne (WorldPacket * data, ObjectGuid who) private
Definition at line 949 of file Channel.cpp.
 {
     if (Player* player = ObjectAccessor::FindConnectedPlayer(who))
         player->GetSession()->SendPacket(data);
 }
References ObjectAccessor::FindConnectedPlayer().
Referenced by Announce(), Invite(), JoinChannel(), KickOrBan(), LeaveChannel(), List(), Password(), Say(), SendWhoOwner(), SetMode(), SetOwner(), ToggleModeration(), and UnBan().
SendWhoOwner()
void Channel::SendWhoOwner (ObjectGuid guid)
Definition at line 686 of file Channel.cpp.
 {
     WorldPacket data;
     if (IsOn(guid))
         MakeChannelOwner(&data);
     else
         MakeNotMember(&data);
     SendToOne(&data, guid);
 }
References IsOn(), MakeChannelOwner(), MakeNotMember(), and SendToOne().
SetMode()
void Channel::SetMode (Player const * player, std::string const & p2n, bool mod, bool set)
Definition at line 578 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     uint32 sec = player->GetSession()->GetSecurity();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     if (!playersStore[guid].IsModerator() && !AccountMgr::IsGMAccount(sec))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     if (guid == _ownerGUID && std::string(p2n) == player->GetName() && mod)
         return;
     Player* newp = ObjectAccessor::FindPlayerByName(p2n, false);
     ObjectGuid victim = newp ? newp->GetGUID() : ObjectGuid::Empty;
     if (!victim || !IsOn(victim) ||
             // allow make moderator from another team only if both is GMs
             // at this moment this only way to show channel post for GM from another team
             ((!AccountMgr::IsGMAccount(sec) || !AccountMgr::IsGMAccount(newp->GetSession()->GetSecurity())) && player->GetTeamId() != newp->GetTeamId() &&
              !sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL)))
     {
         WorldPacket data;
         MakePlayerNotFound(&data, p2n);
         SendToOne(&data, guid);
         return;
     }
     if (_ownerGUID == victim && _ownerGUID != guid)
     {
         WorldPacket data;
         MakeNotOwner(&data);
         SendToOne(&data, guid);
         return;
     }
     if (mod)
     {
         bool isBadConstantModerator = _channelRights.moderators.find(newp->GetSession()->GetAccountId()) != _channelRights.moderators.end();
         if (!isBadConstantModerator)
             SetModerator(newp->GetGUID(), set);
     }
     else
     {
         bool isGoodConstantModerator = _channelRights.moderators.find(player->GetSession()->GetAccountId()) != _channelRights.moderators.end();
         if (!AccountMgr::IsGMAccount(sec) && !isGoodConstantModerator)
         {
             if (_channelRights.flags & CHANNEL_RIGHT_CANT_MUTE)
             {
                 WorldPacket data;
                 MakeNotModerator(&data);
                 SendToOne(&data, guid);
                 return;
             }
         }
         SetMute(newp->GetGUID(), set);
     }
 }
References _channelRights, _ownerGUID, CHANNEL_RIGHT_CANT_MUTE, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, ObjectGuid::Empty, ObjectAccessor::FindPlayerByName(), ChannelRights::flags, WorldSession::GetAccountId(), Object::GetGUID(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeamId(), AccountMgr::IsGMAccount(), IsOn(), MakeNotMember(), MakeNotModerator(), MakeNotOwner(), MakePlayerNotFound(), ChannelRights::moderators, playersStore, SendToOne(), set(), SetModerator(), SetMute(), and sWorld.
Referenced by SetModerator(), SetMute(), UnsetModerator(), and UnsetMute().
SetModerator() [1/2]
void Channel::SetModerator (ObjectGuid guid, bool set) inline private
Definition at line 297 of file Channel.h.
     {
         PlayerInfo& pinfo = playersStore[guid];
         if (pinfo.IsModerator() != set)
         {
             uint8 oldFlag = pinfo.flags;
             pinfo.SetModerator(set);
             WorldPacket data;
             MakeModeChange(&data, guid, oldFlag);
             SendToAll(&data);
             FlagsNotify(pinfo.plrPtr);
         }
     }
References Channel::PlayerInfo::flags, FlagsNotify(), Channel::PlayerInfo::IsModerator(), MakeModeChange(), playersStore, Channel::PlayerInfo::plrPtr, SendToAll(), set(), and Channel::PlayerInfo::SetModerator().
SetModerator() [2/2]
void Channel::SetModerator (Player const * player, std::string const & newname) inline
Definition at line 217 of file Channel.h.
 { SetMode(player, newname, true, true); }
References SetMode().
Referenced by SetMode().
SetMute() [1/2]
void Channel::SetMute (ObjectGuid guid, bool set) inline private
Definition at line 313 of file Channel.h.
     {
         PlayerInfo& pinfo = playersStore[guid];
         if (pinfo.IsMuted() != set)
         {
             uint8 oldFlag = pinfo.flags;
             pinfo.SetMuted(set);
             WorldPacket data;
             MakeModeChange(&data, guid, oldFlag);
             SendToAll(&data);
         }
     }
References Channel::PlayerInfo::flags, Channel::PlayerInfo::IsMuted(), MakeModeChange(), playersStore, SendToAll(), set(), and Channel::PlayerInfo::SetMuted().
SetMute() [2/2]
void Channel::SetMute (Player const * player, std::string const & newname) inline
Definition at line 219 of file Channel.h.
 { SetMode(player, newname, false, true); }
References SetMode().
Referenced by SetMode().
SetOwner() [1/2]
void Channel::SetOwner (ObjectGuid guid, bool exclaim = true)
Definition at line 886 of file Channel.cpp.
 {
     if (_ownerGUID)
     {
         // [] will re-add player after it possible removed
         PlayerContainer::iterator p_itr = playersStore.find(_ownerGUID);
         if (p_itr != playersStore.end())
         {
             p_itr->second.SetOwner(false);
             FlagsNotify(p_itr->second.plrPtr);
         }
     }
     _ownerGUID = guid;
     if (_ownerGUID)
     {
         PlayerInfo& pinfo = playersStore[_ownerGUID];
         pinfo.SetModerator(true);
         uint8 oldFlag = pinfo.flags;
         pinfo.SetOwner(true);
         bool notify = true;
         Player* player = ObjectAccessor::FindPlayer(_ownerGUID);
         if (player)
         {
             uint32 sec = player->GetSession()->GetSecurity();
             notify = !(AccountMgr::IsGMAccount(sec) && sWorld->getBoolConfig(CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL));
         }
         WorldPacket data;
         if (notify)
         {
             MakeModeChange(&data, _ownerGUID, oldFlag);
             SendToAll(&data);
         }
         FlagsNotify(pinfo.plrPtr);
         if (exclaim && notify)
         {
             MakeOwnerChanged(&data, _ownerGUID);
             SendToAll(&data);
         }
     }
 }
References _ownerGUID, CONFIG_SILENTLY_GM_JOIN_TO_CHANNEL, ObjectAccessor::FindPlayer(), Channel::PlayerInfo::flags, FlagsNotify(), WorldSession::GetSecurity(), Player::GetSession(), AccountMgr::IsGMAccount(), MakeModeChange(), MakeOwnerChanged(), playersStore, Channel::PlayerInfo::plrPtr, SendToAll(), Channel::PlayerInfo::SetModerator(), Channel::PlayerInfo::SetOwner(), and sWorld.
Referenced by JoinChannel(), KickOrBan(), LeaveChannel(), and SetOwner().
SetOwner() [2/2]
void Channel::SetOwner (Player const * player, std::string const & name)
Definition at line 649 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     uint32 sec = player->GetSession()->GetSecurity();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     bool isGoodConstantModerator = _channelRights.moderators.find(player->GetSession()->GetAccountId()) != _channelRights.moderators.end();
     if (!AccountMgr::IsGMAccount(sec) && guid != _ownerGUID && !isGoodConstantModerator)
     {
         WorldPacket data;
         MakeNotOwner(&data);
         SendToOne(&data, guid);
         return;
     }
     Player* newp = ObjectAccessor::FindPlayerByName(newname, false);
     ObjectGuid victim = newp ? newp->GetGUID() : ObjectGuid::Empty;
     if (!victim || !IsOn(victim) || (newp->GetTeamId() != player->GetTeamId() &&
                                      !sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL)))
     {
         WorldPacket data;
         MakePlayerNotFound(&data, newname);
         SendToOne(&data, guid);
         return;
     }
     SetOwner(victim);
 }
References _channelRights, _ownerGUID, CONFIG_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, ObjectGuid::Empty, ObjectAccessor::FindPlayerByName(), WorldSession::GetAccountId(), Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeamId(), AccountMgr::IsGMAccount(), IsOn(), MakeNotMember(), MakeNotOwner(), MakePlayerNotFound(), ChannelRights::moderators, SendToOne(), SetOwner(), and sWorld.
SetPassword()
void Channel::SetPassword (std::string const & npassword) inline
Definition at line 199 of file Channel.h.
 { _password = npassword; }
References _password.
Referenced by ChannelMgr::LoadChannels().
ToggleModeration()
void Channel::ToggleModeration (Player * p)
Definition at line 1244 of file Channel.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     if (!IsOn(guid))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, guid);
         return;
     }
     const uint32 level = sWorld->getIntConfig(CONFIG_GM_LEVEL_CHANNEL_MODERATION);
     const bool gm = (level && player->GetSession()->GetSecurity() >= level);
     if (!playersStore[guid].IsModerator() && !gm)
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, guid);
         return;
     }
     // toggle channel moderation
     _moderation = !_moderation;
     WorldPacket data;
     if (_moderation)
     {
         MakeModerationOn(&data, guid);
     }
     else
     {
         MakeModerationOff(&data, guid);
     }
     SendToAll(&data);
 }
References _moderation, CONFIG_GM_LEVEL_CHANNEL_MODERATION, Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), MakeModerationOff(), MakeModerationOn(), MakeNotMember(), MakeNotModerator(), playersStore, SendToAll(), SendToOne(), and sWorld.
UnBan() [1/2]
void Channel::UnBan (ObjectGuid guid)
Definition at line 532 of file Channel.cpp.
 {
     if (!IsBanned(guid))
         return;
     bannedStore.erase(guid);
     RemoveChannelBanFromDB(guid);
 }
References bannedStore, IsBanned(), and RemoveChannelBanFromDB().
UnBan() [2/2]
void Channel::UnBan (Player const * player, std::string const & badname)
Definition at line 474 of file Channel.cpp.
 {
     uint32 sec = player->GetSession()->GetSecurity();
     ObjectGuid good = player->GetGUID();
     if (!IsOn(good))
     {
         WorldPacket data;
         MakeNotMember(&data);
         SendToOne(&data, good);
         return;
     }
     if (!playersStore[good].IsModerator() && !AccountMgr::IsGMAccount(sec))
     {
         WorldPacket data;
         MakeNotModerator(&data);
         SendToOne(&data, good);
         return;
     }
     ObjectGuid victim;
     if (ObjectGuid guid = sWorld->GetGlobalPlayerGUID(badname))
         victim = guid;
     if (!victim || !IsBanned(victim))
     {
         WorldPacket data;
         MakePlayerNotFound(&data, badname);
         SendToOne(&data, good);
         return;
     }
     bool isConstantModerator = _channelRights.moderators.find(player->GetSession()->GetAccountId()) != _channelRights.moderators.end();
     if (!AccountMgr::IsGMAccount(sec) && !isConstantModerator)
     {
         if (_channelRights.flags & CHANNEL_RIGHT_CANT_BAN)
         {
             WorldPacket data;
             MakeNotModerator(&data);
             SendToOne(&data, good);
             return;
         }
     }
     if (_channelRights.flags & CHANNEL_RIGHT_CANT_BAN)
         LOG_GM(player->GetSession()->GetAccountId(), "Command: /unban %s %s (Moderator %s [%s, account: %u] unbanned %s [%s])",
             GetName().c_str(), badname.c_str(), player->GetName().c_str(), player->GetGUID().ToString().c_str(), player->GetSession()->GetAccountId(),
             badname.c_str(), victim.ToString().c_str());
     bannedStore.erase(victim);
     RemoveChannelBanFromDB(victim);
     WorldPacket data;
     MakePlayerUnbanned(&data, victim, good);
     SendToAll(&data);
 }
References _channelRights, bannedStore, CHANNEL_RIGHT_CANT_BAN, ChannelRights::flags, WorldSession::GetAccountId(), Object::GetGUID(), GetName(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), IsBanned(), AccountMgr::IsGMAccount(), IsOn(), LOG_GM, MakeNotMember(), MakeNotModerator(), MakePlayerNotFound(), MakePlayerUnbanned(), ChannelRights::moderators, playersStore, RemoveChannelBanFromDB(), SendToAll(), SendToOne(), sWorld, and ObjectGuid::ToString().
UnsetModerator()
void Channel::UnsetModerator (Player const * player, std::string const & newname) inline
Definition at line 218 of file Channel.h.
 { SetMode(player, newname, true, false); }
References SetMode().
UnsetMute()
void Channel::UnsetMute (Player const * player, std::string const & newname) inline
Definition at line 220 of file Channel.h.
 { SetMode(player, newname, false, false); }
References SetMode().
UpdateChannelInDB()
void Channel::UpdateChannelInDB () const private
Definition at line 100 of file Channel.cpp.
 {
     if (_IsSaved)
     {
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHANNEL);
         stmt->setBool(0, _announce);
         stmt->setString(1, _password);
         stmt->setUInt32(2, _channelDBId);
         CharacterDatabase.Execute(stmt);
         LOG_DEBUG("chat.system", "Channel(%s) updated in database", _name.c_str());
     }
 }
References _announce, _channelDBId, _IsSaved, _name, _password, CHAR_UPD_CHANNEL, CharacterDatabase, LOG_DEBUG, PreparedStatementBase::setBool(), PreparedStatementBase::setString(), and PreparedStatementBase::setUInt32().
Referenced by Announce(), and Password().
UpdateChannelUseageInDB()
void Channel::UpdateChannelUseageInDB () const private
Definition at line 114 of file Channel.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHANNEL_USAGE);
     stmt->setUInt32(0, _channelDBId);
     CharacterDatabase.Execute(stmt);
 }
References _channelDBId, CHAR_UPD_CHANNEL_USAGE, CharacterDatabase, and PreparedStatementBase::setUInt32().
Referenced by JoinChannel(), and LeaveChannel().
Voice()
void Channel::Voice (ObjectGuid guid1, ObjectGuid guid2)
Definition at line 961 of file Channel.cpp.
 {
 }
Member Data Documentation
_announce
bool Channel::_announce private
Definition at line 331 of file Channel.h.
Referenced by Announce(), Channel(), IsAnnounce(), JoinChannel(), LeaveChannel(), and UpdateChannelInDB().
_channelDBId
uint32 Channel::_channelDBId private
Definition at line 338 of file Channel.h.
Referenced by AddChannelBanToDB(), Channel(), RemoveChannelBanFromDB(), UpdateChannelInDB(), and UpdateChannelUseageInDB().
_channelId
uint32 Channel::_channelId private
Definition at line 337 of file Channel.h.
Referenced by GetChannelId(), and IsConstant().
_channelRights
ChannelRights Channel::_channelRights private
Definition at line 343 of file Channel.h.
Referenced by Announce(), Channel(), FlagsNotify(), JoinChannel(), JoinNotify(), KickOrBan(), LeaveNotify(), List(), Password(), Say(), SetMode(), SetOwner(), and UnBan().
_flags
uint8 Channel::_flags private
Definition at line 336 of file Channel.h.
Referenced by Channel(), GetFlags(), and HasFlag().
_isOwnerGM
bool Channel::_isOwnerGM private
Definition at line 335 of file Channel.h.
Referenced by JoinChannel(), and LeaveChannel().
_IsSaved
bool Channel::_IsSaved private
Definition at line 334 of file Channel.h.
Referenced by Channel(), and UpdateChannelInDB().
_moderation
bool Channel::_moderation private
Definition at line 332 of file Channel.h.
Referenced by ToggleModeration().
_name
std::string Channel::_name private
Definition at line 341 of file Channel.h.
Referenced by Channel(), GetName(), MakeNotifyPacket(), Say(), and UpdateChannelInDB().
_ownerGUID
ObjectGuid Channel::_ownerGUID private
Definition at line 340 of file Channel.h.
Referenced by JoinChannel(), KickOrBan(), MakeChannelOwner(), SetMode(), and SetOwner().
_ownership
bool Channel::_ownership private
Definition at line 333 of file Channel.h.
Referenced by Channel(), JoinChannel(), KickOrBan(), and LeaveChannel().
_password
std::string Channel::_password private
Definition at line 342 of file Channel.h.
Referenced by GetPassword(), JoinChannel(), Password(), SetPassword(), and UpdateChannelInDB().
_teamId
TeamId Channel::_teamId private
Definition at line 339 of file Channel.h.
Referenced by Channel().
bannedStore
BannedContainer Channel::bannedStore private
Definition at line 345 of file Channel.h.
Referenced by AddBan(), IsBanned(), KickOrBan(), and UnBan().
playersStore
PlayerContainer Channel::playersStore private
Definition at line 344 of file Channel.h.
Referenced by Announce(), GetNumPlayers(), GetPlayerFlags(), IsOn(), JoinChannel(), KickOrBan(), LeaveChannel(), List(), Password(), Say(), SendToAll(), SendToAllButOne(), SetMode(), SetModerator(), SetMute(), SetOwner(), ToggleModeration(), and UnBan().
playersWatchingStore
PlayersWatchingContainer Channel::playersWatchingStore private
Definition at line 346 of file Channel.h.
Referenced by AddWatching(), RemoveWatching(), and SendToAllWatching().
The documentation for this class was generated from the following files:
src/server/game/Chat/Channels/Channel.h
src/server/game/Chat/Channels/Channel.cpp