Azerotcore-wotlk: BoneStormMoveTargetSelector Struct Reference
BoneStormMoveTargetSelector Struct Reference
Public Member Functions
BoneStormMoveTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 74 of file boss_lord_marrowgar.cpp.
Constructor & Destructor Documentation
BoneStormMoveTargetSelector()
BoneStormMoveTargetSelector::BoneStormMoveTargetSelector (Creature * source) inline
Definition at line 77 of file boss_lord_marrowgar.cpp.
 : _source(source) { }
Member Function Documentation
operator()()
bool BoneStormMoveTargetSelector::operator() (Unit const * target) const inline
Definition at line 78 of file boss_lord_marrowgar.cpp.
     {
         if (!target)
             return false;
         if (target->GetExactDist(_source) > 175.0f)
             return false;
         if (target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (target->GetPositionX() > -337.0f)
             return false;
         return target != _source->GetVictim();
     }
References _source, Position::GetExactDist(), Position::GetPositionX(), Object::GetTypeId(), Unit::GetVictim(), and TYPEID_PLAYER.
Member Data Documentation
_source
Creature const* BoneStormMoveTargetSelector::_source private
Definition at line 96 of file boss_lord_marrowgar.cpp.
Referenced by mpq::Archive::__repr__(), and operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp