Azerotcore-wotlk: rcVectorBase< T, H > Class Template Reference
rcVectorBase< T, H > Class Template Reference
#include <RecastAlloc.h>
Public Types
typedef rcSizeType size_type
typedef T value_type
Public Member Functions
rcVectorBase ()
rcVectorBase (const rcVectorBase< T, H > &other)
rcVectorBase (rcSizeType count)
rcVectorBase (rcSizeType count, const T &value)
rcVectorBase (const T *begin, const T *end)
~rcVectorBase ()
bool reserve (rcSizeType size)
void assign (rcSizeType count, const T &value)
void assign (const T *begin, const T *end)
void resize (rcSizeType size)
void resize (rcSizeType size, const T &value)
void clear ()
void push_back (const T &value)
void pop_back ()
rcSizeType size () const
rcSizeType capacity () const
bool empty () const
const T & operator[] (rcSizeType i) const
T & operator[] (rcSizeType i)
const T & front () const
T & front ()
const T & back () const
T & back ()
const T * data () const
T * data ()
T * begin ()
T * end ()
const T * begin () const
const T * end () const
void swap (rcVectorBase< T, H > &other)
rcVectorBase & operator= (const rcVectorBase< T, H > &other)
Private Member Functions
void destroy_range (rcSizeType begin, rcSizeType end)
T * allocate_and_copy (rcSizeType size)
void resize_impl (rcSizeType size, const T *value)
Static Private Member Functions
static void construct (T *p, const T &v)
static void construct (T *p)
static void construct_range (T *begin, T *end)
static void construct_range (T *begin, T *end, const T &value)
static void copy_range (T *dst, const T *begin, const T *end)
Private Attributes
rcSizeType m_size
rcSizeType m_cap
T * m_data
Detailed Description
template<typename T, rcAllocHint H>
class rcVectorBase< T, H >
Variable-sized storage type. Mimics the interface of std::vector<T> with some notable differences:
Uses rcAlloc()/rcFree() to handle storage.
No support for a custom allocator.
Uses signed size instead of size_t to avoid warnings in for loops: "for (int i = 0; i < foo.size(); i++)"
Omits methods of limited utility: insert/erase, (bad performance), at (we don't use exceptions), operator=.
assign() and the pre-sizing constructor follow C++11 semantics – they don't construct a temporary if no value is provided.
push_back() and resize() support adding values from the current vector. Range-based constructors and assign(begin, end) do not.
No specialization for bool.
Definition at line 95 of file RecastAlloc.h.
Member Typedef Documentation
size_type
template<typename T , rcAllocHint H> typedef rcSizeType rcVectorBase< T, H >::size_type
Definition at line 110 of file RecastAlloc.h.
value_type
template<typename T , rcAllocHint H> typedef T rcVectorBase< T, H >::value_type
Definition at line 111 of file RecastAlloc.h.
Constructor & Destructor Documentation
rcVectorBase() [1/5]
template<typename T , rcAllocHint H> rcVectorBase< T, H >::rcVectorBase () inline
Definition at line 113 of file RecastAlloc.h.
 : m_size(0), m_cap(0), m_data(0) {};
rcVectorBase() [2/5]
template<typename T , rcAllocHint H> rcVectorBase< T, H >::rcVectorBase (const rcVectorBase< T, H > & other) inline
Definition at line 114 of file RecastAlloc.h.
 : m_size(0), m_cap(0), m_data(0) { assign(other.begin(), other.end()); }
References rcVectorBase< T, H >::assign(), rcVectorBase< T, H >::begin(), and rcVectorBase< T, H >::end().
rcVectorBase() [3/5]
template<typename T , rcAllocHint H> rcVectorBase< T, H >::rcVectorBase (rcSizeType count) inline explicit
Definition at line 115 of file RecastAlloc.h.
 : m_size(0), m_cap(0), m_data(0) { resize(count); }
References count(), and rcVectorBase< T, H >::resize().
rcVectorBase() [4/5]
template<typename T , rcAllocHint H> rcVectorBase< T, H >::rcVectorBase (rcSizeType count, const T & value) inline
Definition at line 116 of file RecastAlloc.h.
 : m_size(0), m_cap(0), m_data(0) { resize(count, value); }
References count(), and rcVectorBase< T, H >::resize().
rcVectorBase() [5/5]
template<typename T , rcAllocHint H> rcVectorBase< T, H >::rcVectorBase (const T * begin, const T * end) inline
Definition at line 117 of file RecastAlloc.h.
 : m_size(0), m_cap(0), m_data(0) { assign(begin, end); }
References rcVectorBase< T, H >::assign(), rcVectorBase< T, H >::begin(), and rcVectorBase< T, H >::end().
~rcVectorBase()
template<typename T , rcAllocHint H> rcVectorBase< T, H >::~rcVectorBase () inline
Definition at line 118 of file RecastAlloc.h.
 { destroy_range(0, m_size); rcFree(m_data); }
References rcVectorBase< T, H >::destroy_range(), rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcFree().
Member Function Documentation
allocate_and_copy()
template<typename T , rcAllocHint H> T * rcVectorBase< T, H >::allocate_and_copy (rcSizeType size) private
Definition at line 175 of file RecastAlloc.h.
{
     rcAssert(RC_SIZE_MAX / static_cast<rcSizeType>(sizeof(T)) >= size);
     T* new_data = static_cast<T*>(rcAlloc(sizeof(T) * size, H));
     if (new_data) {
         copy_range(new_data, m_data, m_data + m_size);
     }
     return new_data;
 }
References H, RC_SIZE_MAX, rcAlloc(), and rcAssert.
assign() [1/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::assign (const T * begin, const T * end)
Definition at line 184 of file RecastAlloc.h.
{
     clear();
     reserve(end - begin);
     m_size = end - begin;
     copy_range(m_data, begin, end);
 }
References detail::reserve().
assign() [2/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::assign (rcSizeType count, const T & value) inline
Definition at line 123 of file RecastAlloc.h.
 { clear(); resize(count, value); }
References rcVectorBase< T, H >::clear(), count(), and rcVectorBase< T, H >::resize().
Referenced by rcVectorBase< T, H >::rcVectorBase().
back() [1/2]
template<typename T , rcAllocHint H> T& rcVectorBase< T, H >::back () inline
Definition at line 144 of file RecastAlloc.h.
 { rcAssert(m_size); return m_data[m_size - 1]; };
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
back() [2/2]
template<typename T , rcAllocHint H> const T& rcVectorBase< T, H >::back () const inline
Definition at line 143 of file RecastAlloc.h.
 { rcAssert(m_size); return m_data[m_size - 1]; };
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
Referenced by floodRegion(), rcIntArray::pop(), and rcVectorBase< T, H >::pop_back().
begin() [1/2]
template<typename T , rcAllocHint H> T* rcVectorBase< T, H >::begin () inline
Definition at line 148 of file RecastAlloc.h.
 { return m_data; }
References rcVectorBase< T, H >::m_data.
Referenced by rcVectorBase< T, H >::rcVectorBase().
begin() [2/2]
template<typename T , rcAllocHint H> const T* rcVectorBase< T, H >::begin () const inline
Definition at line 150 of file RecastAlloc.h.
 { return m_data; }
References rcVectorBase< T, H >::m_data.
capacity()
template<typename T , rcAllocHint H> rcSizeType rcVectorBase< T, H >::capacity () const inline
Definition at line 135 of file RecastAlloc.h.
 { return m_cap; }
References rcVectorBase< T, H >::m_cap.
clear()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::clear () inline
Definition at line 129 of file RecastAlloc.h.
 { destroy_range(0, m_size); m_size = 0; }
References rcVectorBase< T, H >::destroy_range(), and rcVectorBase< T, H >::m_size.
Referenced by rcVectorBase< T, H >::assign(), expandRegions(), and floodRegion().
construct() [1/2]
template<typename T , rcAllocHint H> static void rcVectorBase< T, H >::construct (T * p) inline static private
Definition at line 101 of file RecastAlloc.h.
 { ::new(rcNewTag(), (void*)p) T; }
construct() [2/2]
template<typename T , rcAllocHint H> static void rcVectorBase< T, H >::construct (T * p, const T & v) inline static private
Definition at line 100 of file RecastAlloc.h.
 { ::new(rcNewTag(), (void*)p) T(v); }
construct_range() [1/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::construct_range (T * begin, T * end) static private
Definition at line 249 of file RecastAlloc.h.
{
     for (T* p = begin; p < end; p++) {
         construct(p);
     }
 }
construct_range() [2/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::construct_range (T * begin, T * end, const T & value) static private
Definition at line 256 of file RecastAlloc.h.
{
     for (T* p = begin; p < end; p++) {
         construct(p, value);
     }
 }
copy_range()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::copy_range (T * dst, const T * begin, const T * end) static private
Definition at line 263 of file RecastAlloc.h.
{
     for (rcSizeType i = 0 ; i < end - begin; i++) {
         construct(dst + i, begin[i]);
     }
 }
data() [1/2]
template<typename T , rcAllocHint H> T* rcVectorBase< T, H >::data () inline
Definition at line 146 of file RecastAlloc.h.
 { return m_data; }
References rcVectorBase< T, H >::m_data.
data() [2/2]
template<typename T , rcAllocHint H> const T* rcVectorBase< T, H >::data () const inline
Definition at line 145 of file RecastAlloc.h.
 { return m_data; }
References rcVectorBase< T, H >::m_data.
destroy_range()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::destroy_range (rcSizeType begin, rcSizeType end) private
Definition at line 269 of file RecastAlloc.h.
{
     for (rcSizeType i = begin; i < end; i++) {
         m_data[i].~T();
     }
 }
Referenced by rcVectorBase< T, H >::clear(), and rcVectorBase< T, H >::~rcVectorBase().
empty()
template<typename T , rcAllocHint H> bool rcVectorBase< T, H >::empty () const inline
Definition at line 136 of file RecastAlloc.h.
 { return size() == 0; }
References rcVectorBase< T, H >::size().
end() [1/2]
template<typename T , rcAllocHint H> T* rcVectorBase< T, H >::end () inline
Definition at line 149 of file RecastAlloc.h.
 { return m_data + m_size; }
References rcVectorBase< T, H >::m_data, and rcVectorBase< T, H >::m_size.
Referenced by rcVectorBase< T, H >::rcVectorBase().
end() [2/2]
template<typename T , rcAllocHint H> const T* rcVectorBase< T, H >::end () const inline
Definition at line 151 of file RecastAlloc.h.
 { return m_data + m_size; }
References rcVectorBase< T, H >::m_data, and rcVectorBase< T, H >::m_size.
front() [1/2]
template<typename T , rcAllocHint H> T& rcVectorBase< T, H >::front () inline
Definition at line 142 of file RecastAlloc.h.
 { rcAssert(m_size); return m_data[0]; }
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
front() [2/2]
template<typename T , rcAllocHint H> const T& rcVectorBase< T, H >::front () const inline
Definition at line 141 of file RecastAlloc.h.
 { rcAssert(m_size); return m_data[0]; }
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
operator=()
template<typename T , rcAllocHint H> rcVectorBase& rcVectorBase< T, H >::operator= (const rcVectorBase< T, H > & other)
operator[]() [1/2]
template<typename T , rcAllocHint H> T& rcVectorBase< T, H >::operator[] (rcSizeType i) inline
Definition at line 139 of file RecastAlloc.h.
 { rcAssert(i >= 0 && i < m_size); return m_data[i]; }
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
operator[]() [2/2]
template<typename T , rcAllocHint H> const T& rcVectorBase< T, H >::operator[] (rcSizeType i) const inline
Definition at line 138 of file RecastAlloc.h.
 { rcAssert(i >= 0 && i < m_size); return m_data[i]; }
References rcVectorBase< T, H >::m_data, rcVectorBase< T, H >::m_size, and rcAssert.
pop_back()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::pop_back () inline
Definition at line 132 of file RecastAlloc.h.
 { rcAssert(m_size > 0); back().~T(); m_size--; }
References rcVectorBase< T, H >::back(), rcVectorBase< T, H >::m_size, and rcAssert.
Referenced by floodRegion(), and rcIntArray::pop().
push_back()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::push_back (const T & value)
Definition at line 191 of file RecastAlloc.h.
{
     // rcLikely increases performance by ~50% on BM_rcVector_PushPreallocated,
     // and by ~2-5% on BM_rcVector_Push.
     if (rcLikely(m_size < m_cap)) {
         construct(m_data + m_size++, value);
         return;
     }
     rcAssert(RC_SIZE_MAX / 2 >= m_size);
     rcSizeType new_cap = m_size ? 2*m_size : 1;
     T* data = allocate_and_copy(new_cap);
     // construct between allocate and destroy+free in case value is
     // in this vector.
     construct(data + m_size, value);
     destroy_range(0, m_size);
     m_size++;
     m_cap = new_cap;
     rcFree(m_data);
     m_data = data;
 }
References RC_SIZE_MAX, rcAssert, rcFree(), and rcLikely.
Referenced by appendStacks(), expandRegions(), floodRegion(), mergeAndFilterLayerRegions(), mergeAndFilterRegions(), rcIntArray::push(), and sortCellsByLevel().
reserve()
template<typename T , rcAllocHint H> bool rcVectorBase< T, H >::reserve (rcSizeType size)
Definition at line 160 of file RecastAlloc.h.
{
     if (count <= m_cap) {
         return true;
     }
     T* new_data = allocate_and_copy(count);
     if (!new_data) {
       return false;
     }
     destroy_range(0, m_size);
     rcFree(m_data);
     m_data = new_data;
     m_cap = count;
     return true;
 }
References count(), and rcFree().
Referenced by mergeAndFilterLayerRegions(), mergeAndFilterRegions(), and rcBuildRegions().
resize() [1/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::resize (rcSizeType size) inline
Definition at line 126 of file RecastAlloc.h.
 { resize_impl(size, NULL); }
References NULL, rcVectorBase< T, H >::resize_impl(), and rcVectorBase< T, H >::size().
Referenced by rcVectorBase< T, H >::assign(), mergeAndFilterLayerRegions(), rcVectorBase< T, H >::rcVectorBase(), and rcIntArray::resize().
resize() [2/2]
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::resize (rcSizeType size, const T & value) inline
Definition at line 127 of file RecastAlloc.h.
 { resize_impl(size, &value); }
References rcVectorBase< T, H >::resize_impl(), and rcVectorBase< T, H >::size().
resize_impl()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::resize_impl (rcSizeType size, const T * value) private
Definition at line 212 of file RecastAlloc.h.
{
     if (size < m_size) {
         destroy_range(size, m_size);
         m_size = size;
     } else if (size > m_size) {
         T* new_data = allocate_and_copy(size);
         // We defer deconstructing/freeing old data until after constructing
         // new elements in case "value" is there.
         if (value) {
             construct_range(new_data + m_size, new_data + size, *value);
         } else {
             construct_range(new_data + m_size, new_data + size);
         }
         destroy_range(0, m_size);
         rcFree(m_data);
         m_data = new_data;
         m_cap = size;
         m_size = size;
     }
 }
References rcFree().
Referenced by rcVectorBase< T, H >::resize().
size()
template<typename T , rcAllocHint H> rcSizeType rcVectorBase< T, H >::size () const inline
Definition at line 134 of file RecastAlloc.h.
 { return m_size; }
References rcVectorBase< T, H >::m_size.
Referenced by appendStacks(), rcVectorBase< T, H >::empty(), expandRegions(), floodRegion(), rcBuildRegions(), rcVectorBase< T, H >::resize(), and rcIntArray::size().
swap()
template<typename T , rcAllocHint H> void rcVectorBase< T, H >::swap (rcVectorBase< T, H > & other)
Definition at line 233 of file RecastAlloc.h.
{
     // TODO: Reorganize headers so we can use rcSwap here.
     rcSizeType tmp_cap = other.m_cap;
     rcSizeType tmp_size = other.m_size;
     T* tmp_data = other.m_data;
     other.m_cap = m_cap;
     other.m_size = m_size;
     other.m_data = m_data;
     m_cap = tmp_cap;
     m_size = tmp_size;
     m_data = tmp_data;
 }
References rcVectorBase< T, H >::m_cap, rcVectorBase< T, H >::m_data, and rcVectorBase< T, H >::m_size.
Member Data Documentation
m_cap
template<typename T , rcAllocHint H> rcSizeType rcVectorBase< T, H >::m_cap private
Definition at line 97 of file RecastAlloc.h.
Referenced by rcVectorBase< T, H >::capacity(), and rcVectorBase< T, H >::swap().
m_data
template<typename T , rcAllocHint H> T* rcVectorBase< T, H >::m_data private
Definition at line 98 of file RecastAlloc.h.
Referenced by rcVectorBase< T, H >::back(), rcVectorBase< T, H >::begin(), rcVectorBase< T, H >::data(), rcVectorBase< T, H >::end(), rcVectorBase< T, H >::front(), rcVectorBase< T, H >::operator[](), rcVectorBase< T, H >::swap(), and rcVectorBase< T, H >::~rcVectorBase().
m_size
template<typename T , rcAllocHint H> rcSizeType rcVectorBase< T, H >::m_size private
Definition at line 96 of file RecastAlloc.h.
Referenced by rcVectorBase< T, H >::back(), rcVectorBase< T, H >::clear(), rcVectorBase< T, H >::end(), rcVectorBase< T, H >::front(), rcVectorBase< T, H >::operator[](), rcVectorBase< T, H >::pop_back(), rcVectorBase< T, H >::size(), rcVectorBase< T, H >::swap(), and rcVectorBase< T, H >::~rcVectorBase().
The documentation for this class was generated from the following file:
deps/recastnavigation/Recast/Include/RecastAlloc.h