Azerotcore-wotlk: TransactionWithResultTask Class Reference
TransactionWithResultTask Class Reference
#include <Transaction.h>
Public Member Functions
TransactionWithResultTask (std::shared_ptr< TransactionBase > trans)
TransactionFuture GetFuture ()
Public Member Functions inherited from TransactionTask
TransactionTask (std::shared_ptr< TransactionBase > trans)
~TransactionTask ()
Public Member Functions inherited from SQLOperation
SQLOperation ()
virtual ~SQLOperation ()
virtual int call ()
virtual void SetConnection (MySQLConnection *con)
Protected Member Functions
bool Execute () override
Protected Member Functions inherited from TransactionTask
int TryExecute ()
void CleanupOnFailure ()
Protected Attributes
TransactionPromise m_result
Protected Attributes inherited from TransactionTask
std::shared_ptr< TransactionBase > m_trans
Additional Inherited Members
Public Attributes inherited from SQLOperation
MySQLConnection * m_conn
Static Protected Attributes inherited from TransactionTask
static std::mutex _deadlockLock
Detailed Description
Definition at line 91 of file Transaction.h.
Constructor & Destructor Documentation
TransactionWithResultTask()
TransactionWithResultTask::TransactionWithResultTask (std::shared_ptr< TransactionBase > trans) inline
Definition at line 94 of file Transaction.h.
 : TransactionTask(trans) { }
Member Function Documentation
Execute()
bool TransactionWithResultTask::Execute () override protected virtual
Reimplemented from TransactionTask.
Definition at line 114 of file Transaction.cpp.
 {
     int errorCode = TryExecute();
     if (!errorCode)
     {
         m_result.set_value(true);
         return true;
     }
     if (errorCode == ER_LOCK_DEADLOCK)
     {
         std::ostringstream threadIdStream;
         threadIdStream << std::this_thread::get_id();
         std::string threadId = threadIdStream.str();
         // Make sure only 1 async thread retries a transaction so they don't keep dead-locking each other
         std::lock_guard<std::mutex> lock(_deadlockLock);
         for (uint32 loopDuration = 0, startMSTime = getMSTime(); loopDuration <= DEADLOCK_MAX_RETRY_TIME_MS; loopDuration = GetMSTimeDiffToNow(startMSTime))
         {
             if (!TryExecute())
             {
                 m_result.set_value(true);
                 return true;
             }
             LOG_WARN("sql.sql", "Deadlocked SQL Transaction, retrying. Loop timer: %u ms, Thread Id: %s", loopDuration, threadId.c_str());
         }
         LOG_ERROR("sql.sql", "Fatal deadlocked SQL Transaction, it will not be retried anymore. Thread Id: %s", threadId.c_str());
     }
     // Clean up now.
     CleanupOnFailure();
     m_result.set_value(false);
     return false;
 }
References TransactionTask::_deadlockLock, TransactionTask::CleanupOnFailure(), DEADLOCK_MAX_RETRY_TIME_MS, ER_LOCK_DEADLOCK, getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_WARN, m_result, and TransactionTask::TryExecute().
GetFuture()
TransactionFuture TransactionWithResultTask::GetFuture () inline
Definition at line 96 of file Transaction.h.
 { return m_result.get_future(); }
Referenced by DatabaseWorkerPool< T >::AsyncCommitTransaction().
Member Data Documentation
m_result
TransactionPromise TransactionWithResultTask::m_result protected
Definition at line 101 of file Transaction.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/database/Database/Transaction.h
src/server/database/Database/Transaction.cpp