Azerotcore-wotlk: npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI Struct Reference
npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI Struct Reference
Public Member Functions
npc_cos_stratholme_citizienAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void DoAction (int32 param) override
void InfectMe (uint32 time)
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool locked
uint32 changeTimer
InstanceScript * pInstance
uint32 allowTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1502 of file culling_of_stratholme.cpp.
Constructor & Destructor Documentation
npc_cos_stratholme_citizienAI()
npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::npc_cos_stratholme_citizienAI (Creature * creature) inline
Definition at line 1504 of file culling_of_stratholme.cpp.
                                                           : ScriptedAI(creature)
         {
             allowTimer = 0;
             pInstance = me->GetInstanceScript();
             if (!pInstance || pInstance->GetData(DATA_ARTHAS_EVENT) < COS_PROGRESS_FINISHED_CITY_INTRO)
                 allowTimer++;
         }
References COS_PROGRESS_FINISHED_CITY_INTRO, and DATA_ARTHAS_EVENT.
Member Function Documentation
DoAction()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1544 of file culling_of_stratholme.cpp.
         {
             if (param == ACTION_INFECT_CITIZIEN)
                 InfectMe(1);
             else if (param == ACTION_FORCE_CHANGE_LOCK)
                 locked = true;
         }
References ACTION_FORCE_CHANGE_LOCK, and ACTION_INFECT_CITIZIEN.
InfectMe()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::InfectMe (uint32 time) inline
Definition at line 1552 of file culling_of_stratholme.cpp.
         {
             locked = true;
             changeTimer = time;
         }
MoveInLineOfSight()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1536 of file culling_of_stratholme.cpp.
         {
             if (!allowTimer && !locked && (who->GetTypeId() == TYPEID_PLAYER || who->IsPet()) && me->GetDistance(who) < 15.0f)
                 InfectMe(2000);
             ScriptedAI::MoveInLineOfSight(who);
         }
References Object::GetTypeId(), Unit::IsPet(), CreatureAI::MoveInLineOfSight(), and TYPEID_PLAYER.
Reset()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1517 of file culling_of_stratholme.cpp.
         {
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             locked = false;
             changeTimer = 0;
             if (pInstance)
             {
                 uint32 data = pInstance->GetData(DATA_ARTHAS_EVENT);
                 if (me->GetDistance(2400, 1200, 135) > 20.0f && data >= COS_PROGRESS_FINISHED_CITY_INTRO)
                 {
                     if (data >= COS_PROGRESS_KILLED_SALRAMM)
                         me->DespawnOrUnsummon(500);
                     else
                         InfectMe(3000);
                 }
             }
         }
References COS_PROGRESS_FINISHED_CITY_INTRO, COS_PROGRESS_KILLED_SALRAMM, DATA_ARTHAS_EVENT, EMOTE_ONESHOT_NONE, ZoneScript::GetData(), and UNIT_NPC_EMOTESTATE.
SpellHit()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1558 of file culling_of_stratholme.cpp.
         {
             if (spellInfo->Id == SPELL_ARTHAS_CRUSADER_STRIKE)
             {
                 if (me->GetEntry() == NPC_CITY_MAN3)
                 {
                     me->StopMoving();
                     me->HandleEmoteCommand(54); // laugh
                 }
                 else
                     Unit::Kill(caster, me);
             }
         }
References SpellInfo::Id, Unit::Kill(), NPC_CITY_MAN3, and SPELL_ARTHAS_CRUSADER_STRIKE.
UpdateAI()
void npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1572 of file culling_of_stratholme.cpp.
         {
             ScriptedAI::UpdateAI(diff);
             if (allowTimer)
             {
                 allowTimer += diff;
                 if (allowTimer >= 8000 && pInstance && pInstance->GetData(DATA_ARTHAS_EVENT) >= COS_PROGRESS_FINISHED_CITY_INTRO)
                     allowTimer = 0;
             }
             if (changeTimer)
             {
                 changeTimer += diff;
                 if (changeTimer >= 2500 && changeTimer < 10000)
                 {
                     me->CastSpell(me, SPELL_GREEN_VISUAL_AURA, true);
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_COWER);
                     changeTimer = 10000;
                 }
                 else if (changeTimer >= 14500 && changeTimer < 20000)
                 {
                     me->UpdateEntry(NPC_RISEN_ZOMBIE, nullptr, false);
                     me->SetReactState(REACT_AGGRESSIVE);
                     changeTimer = 20000;
                 }
                 else if (changeTimer >= 23000)
                 {
                     me->RemoveAura(SPELL_GREEN_VISUAL_AURA);
                     changeTimer = 0;
                 }
             }
         }
References COS_PROGRESS_FINISHED_CITY_INTRO, DATA_ARTHAS_EVENT, EMOTE_STATE_COWER, ZoneScript::GetData(), NPC_RISEN_ZOMBIE, REACT_AGGRESSIVE, SPELL_GREEN_VISUAL_AURA, UNIT_NPC_EMOTESTATE, and ScriptedAI::UpdateAI().
Member Data Documentation
allowTimer
uint32 npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::allowTimer
Definition at line 1515 of file culling_of_stratholme.cpp.
changeTimer
uint32 npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::changeTimer
Definition at line 1513 of file culling_of_stratholme.cpp.
locked
bool npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::locked
Definition at line 1512 of file culling_of_stratholme.cpp.
pInstance
InstanceScript* npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::pInstance
Definition at line 1514 of file culling_of_stratholme.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp