Azerotcore-wotlk: boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI Struct Reference
boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI Struct Reference
Public Member Functions
boss_valithria_dreamwalkerAI (Creature *creature)
void Reset () override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void DoAction (int32 action) override
void HealReceived (Unit *healer, uint32 &heal) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *spell) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void UpdateAI (uint32 diff) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
uint32 _spawnHealth
uint32 const _portalCount
uint32 _missedPortals
bool _under25PercentTalkDone
bool _over75PercentTalkDone
bool _justDied
bool _done
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 288 of file boss_valithria_dreamwalker.cpp.
Constructor & Destructor Documentation
boss_valithria_dreamwalkerAI()
boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::boss_valithria_dreamwalkerAI (Creature * creature) inline
Definition at line 290 of file boss_valithria_dreamwalker.cpp.
                                                          : ScriptedAI(creature),
             _instance(creature->GetInstanceScript()), _portalCount(RAID_MODE<uint32>(3, 8, 3, 8))
         {
             me->SetReactState(REACT_PASSIVE);
             _spawnHealth = 1; // just in case if not set below
             if (CreatureData const* data = sObjectMgr->GetCreatureData(me->GetSpawnId()))
                 if (data->curhealth)
                     _spawnHealth = data->curhealth;
         }
References _spawnHealth, Creature::GetSpawnId(), ScriptedAI::me, REACT_PASSIVE, Creature::SetReactState(), and sObjectMgr.
Member Function Documentation
AttackStart()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 318 of file boss_valithria_dreamwalker.cpp.
 {}
DamageTaken()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 374 of file boss_valithria_dreamwalker.cpp.
         {
             if (me->HealthBelowPctDamaged(25, damage))
             {
                 if (!_under25PercentTalkDone)
                 {
                     _under25PercentTalkDone = true;
                     Talk(SAY_VALITHRIA_25_PERCENT);
                 }
                 if (damage >= me->GetHealth())
                 {
                     damage = 0;
                     if (!_justDied)
                     {
                         _justDied = true;
                         Talk(SAY_VALITHRIA_DEATH);
                         _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
                         if (Creature* trigger = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_TRIGGER)))
                             trigger->AI()->EnterEvadeMode();
                     }
                 }
             }
         }
References _instance, _justDied, _under25PercentTalkDone, DATA_VALITHRIA_TRIGGER, ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetHealth(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, SAY_VALITHRIA_25_PERCENT, SAY_VALITHRIA_DEATH, InstanceScript::SendEncounterUnit(), and CreatureAI::Talk().
DoAction()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 321 of file boss_valithria_dreamwalker.cpp.
         {
             if (action != ACTION_ENTER_COMBAT)
                 return;
             _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me);
             _events.Reset();
             _events.ScheduleEvent(EVENT_INTRO_TALK, 15000);
             _events.ScheduleEvent(EVENT_DREAM_PORTAL, urand(45000, 48000));
             if (IsHeroic())
                 _events.ScheduleEvent(EVENT_BERSERK, 420000);
         }
References _events, _instance, ACTION_ENTER_COMBAT, ENCOUNTER_FRAME_ENGAGE, EVENT_BERSERK, EVENT_DREAM_PORTAL, EVENT_INTRO_TALK, ScriptedAI::IsHeroic(), ScriptedAI::me, EventMap::Reset(), EventMap::ScheduleEvent(), InstanceScript::SendEncounterUnit(), and urand().
GetData()
uint32 boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 474 of file boss_valithria_dreamwalker.cpp.
         {
             if (type == MISSED_PORTALS)
                 return _missedPortals;
             return 0;
         }
References _missedPortals, and MISSED_PORTALS.
HealReceived()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived (Unit * healer, uint32 & heal) inline override virtual
Reimplemented from UnitAI.
Definition at line 334 of file boss_valithria_dreamwalker.cpp.
         {
             if (!me->hasLootRecipient())
                 me->SetLootRecipient(healer);
             me->LowerPlayerDamageReq(heal);
             // encounter complete
             if (me->HealthAbovePctHealed(100, heal) && !_done)
             {
                 _done = true;
                 Talk(SAY_VALITHRIA_SUCCESS);
                 _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
                 _instance->DoRemoveAurasDueToSpellOnPlayers(70766);
                 me->RemoveAurasDueToSpell(SPELL_CORRUPTION_VALITHRIA);
                 me->CastSpell(me, SPELL_ACHIEVEMENT_CHECK, true);
                 me->CastSpell((Unit*)nullptr, SPELL_DREAMWALKERS_RAGE, false);
                 _events.Reset();
                 _events.ScheduleEvent(EVENT_DREAM_SLIP, 3500);
                 _instance->SetBossState(DATA_VALITHRIA_DREAMWALKER, DONE);
                 if (Creature* trigger = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_TRIGGER)))
                     trigger->AI()->EnterEvadeMode();
                 if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_LICH_KING)))
                     lichKing->AI()->Reset();
             }
             else if (!_over75PercentTalkDone && me->HealthAbovePctHealed(75, heal))
             {
                 _over75PercentTalkDone = true;
                 Talk(SAY_VALITHRIA_75_PERCENT);
             }
             else if (_instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) == NOT_STARTED)
             {
                 if (Creature* trigger = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_TRIGGER)))
                 {
                     trigger->AI()->DoAction(ACTION_ENTER_COMBAT);
                     _instance->SetBossState(DATA_VALITHRIA_DREAMWALKER, IN_PROGRESS);
                 }
             }
         }
References _done, _events, _instance, _over75PercentTalkDone, ACTION_ENTER_COMBAT, Unit::CastSpell(), DATA_VALITHRIA_DREAMWALKER, DATA_VALITHRIA_LICH_KING, DATA_VALITHRIA_TRIGGER, DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), ENCOUNTER_FRAME_DISENGAGE, EVENT_DREAM_SLIP, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Creature::hasLootRecipient(), Unit::HealthAbovePctHealed(), IN_PROGRESS, Creature::LowerPlayerDamageReq(), ScriptedAI::me, NOT_STARTED, Unit::RemoveAurasDueToSpell(), EventMap::Reset(), SAY_VALITHRIA_75_PERCENT, SAY_VALITHRIA_SUCCESS, EventMap::ScheduleEvent(), InstanceScript::SendEncounterUnit(), InstanceScript::SetBossState(), Creature::SetLootRecipient(), SPELL_ACHIEVEMENT_CHECK, SPELL_CORRUPTION_VALITHRIA, SPELL_DREAMWALKERS_RAGE, and CreatureAI::Talk().
JustSummoned()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 415 of file boss_valithria_dreamwalker.cpp.
         {
             if (summon->GetEntry() == NPC_DREAM_PORTAL_PRE_EFFECT)
             {
                 summon->m_Events.AddEvent(new DelayedCastEvent(summon, SPELL_SUMMON_DREAM_PORTAL, me->GetGUID(), 6000), summon->m_Events.CalculateTime(15000));
                 summon->m_Events.AddEvent(new AuraRemoveEvent(summon, SPELL_DREAM_PORTAL_VISUAL_PRE), summon->m_Events.CalculateTime(15000));
             }
             else if (summon->GetEntry() == NPC_NIGHTMARE_PORTAL_PRE_EFFECT)
             {
                 summon->m_Events.AddEvent(new DelayedCastEvent(summon, SPELL_SUMMON_NIGHTMARE_PORTAL, me->GetGUID(), 6000), summon->m_Events.CalculateTime(15000));
                 summon->m_Events.AddEvent(new AuraRemoveEvent(summon, SPELL_NIGHTMARE_PORTAL_VISUAL_PRE), summon->m_Events.CalculateTime(15000));
             }
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Object::GetEntry(), Object::GetGUID(), Unit::m_Events, ScriptedAI::me, NPC_DREAM_PORTAL_PRE_EFFECT, NPC_NIGHTMARE_PORTAL_PRE_EFFECT, SPELL_DREAM_PORTAL_VISUAL_PRE, SPELL_NIGHTMARE_PORTAL_VISUAL_PRE, SPELL_SUMMON_DREAM_PORTAL, and SPELL_SUMMON_NIGHTMARE_PORTAL.
MoveInLineOfSight()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 319 of file boss_valithria_dreamwalker.cpp.
 {}
Reset()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 300 of file boss_valithria_dreamwalker.cpp.
         {
             _events.Reset();
             me->SetHealth(_spawnHealth);
             me->LoadCreaturesAddon(true);
             // immune to percent heals
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_OBS_MOD_HEALTH, true);
             me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_PCT, true);
             // Glyph of Dispel Magic - not a percent heal by effect, its cast with custom basepoints
             me->ApplySpellImmune(0, IMMUNITY_ID, 56131, true);
             _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
             _missedPortals = 0;
             _under25PercentTalkDone = false;
             _over75PercentTalkDone = false;
             _justDied = false;
             _done = false;
         }
References _done, _events, _instance, _justDied, _missedPortals, _over75PercentTalkDone, _spawnHealth, _under25PercentTalkDone, Unit::ApplySpellImmune(), ENCOUNTER_FRAME_DISENGAGE, IMMUNITY_EFFECT, IMMUNITY_ID, IMMUNITY_STATE, Creature::LoadCreaturesAddon(), ScriptedAI::me, EventMap::Reset(), InstanceScript::SendEncounterUnit(), Unit::SetHealth(), SPELL_AURA_OBS_MOD_HEALTH, and SPELL_EFFECT_HEAL_PCT.
SpellHit()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 399 of file boss_valithria_dreamwalker.cpp.
         {
             if (spell->Id == SPELL_DREAM_SLIP)
             {
                 me->CastSpell(me, SPELL_CLEAR_ALL, true);
                 me->CastSpell(me, SPELL_AWARD_REPUTATION_BOSS_KILL, true);
                 // this display id was found in sniff instead of the one on aura
                 me->SetDisplayId(11686);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 me->DespawnOrUnsummon(4000);
                 if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_LICH_KING)))
                     lichKing->CastSpell(lichKing, SPELL_SPAWN_CHEST, false);
                 _instance->SetData(DATA_WEEKLY_QUEST_ID, 0); // show hidden npc if necessary
             }
         }
References _instance, Unit::CastSpell(), DATA_VALITHRIA_LICH_KING, DATA_WEEKLY_QUEST_ID, Creature::DespawnOrUnsummon(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), SpellInfo::Id, ScriptedAI::me, ZoneScript::SetData(), Creature::SetDisplayId(), Object::SetFlag(), SPELL_AWARD_REPUTATION_BOSS_KILL, SPELL_CLEAR_ALL, SPELL_DREAM_SLIP, SPELL_SPAWN_CHEST, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
SummonedCreatureDespawn()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 429 of file boss_valithria_dreamwalker.cpp.
         {
             if (summon->GetEntry() == NPC_DREAM_PORTAL || summon->GetEntry() == NPC_NIGHTMARE_PORTAL)
                 if (summon->AI()->GetData(MISSED_PORTALS))
                     ++_missedPortals;
         }
References _missedPortals, Creature::AI(), UnitAI::GetData(), Object::GetEntry(), MISSED_PORTALS, NPC_DREAM_PORTAL, and NPC_NIGHTMARE_PORTAL.
UpdateAI()
void boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 436 of file boss_valithria_dreamwalker.cpp.
         {
             // does not enter combat
             if (_instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) == NOT_STARTED)
             {
                 if (me->GetHealth() != _spawnHealth) // healing when boss cannot be engaged (lower spire not finished, cheating) doesn't start the fight, prevent winning this way
                     me->SetHealth(_spawnHealth);
                 return;
             }
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_INTRO_TALK:
                     Talk(SAY_VALITHRIA_ENTER_COMBAT);
                     break;
                 case EVENT_BERSERK:
                     Talk(SAY_VALITHRIA_BERSERK);
                     break;
                 case EVENT_DREAM_PORTAL:
                     if (!IsHeroic())
                         Talk(SAY_VALITHRIA_DREAM_PORTAL);
                     for (uint32 i = 0; i < _portalCount; ++i)
                         me->CastSpell(me, SUMMON_PORTAL, false);
                     _events.ScheduleEvent(EVENT_DREAM_PORTAL, urand(45000, 48000));
                     break;
                 case EVENT_DREAM_SLIP:
                     me->CastSpell(me, SPELL_DREAM_SLIP, false);
                     break;
                 default:
                     break;
             }
         }
References _events, _instance, _portalCount, _spawnHealth, Unit::CastSpell(), DATA_VALITHRIA_DREAMWALKER, diff(), EVENT_BERSERK, EVENT_DREAM_PORTAL, EVENT_DREAM_SLIP, EVENT_INTRO_TALK, EventMap::ExecuteEvent(), InstanceScript::GetBossState(), Unit::GetHealth(), Unit::HasUnitState(), ScriptedAI::IsHeroic(), ScriptedAI::me, NOT_STARTED, SAY_VALITHRIA_BERSERK, SAY_VALITHRIA_DREAM_PORTAL, SAY_VALITHRIA_ENTER_COMBAT, EventMap::ScheduleEvent(), Unit::SetHealth(), SPELL_DREAM_SLIP, SUMMON_PORTAL, CreatureAI::Talk(), UNIT_STATE_CASTING, EventMap::Update(), and urand().
Member Data Documentation
_done
bool boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_done private
Definition at line 491 of file boss_valithria_dreamwalker.cpp.
Referenced by HealReceived(), and Reset().
_events
EventMap boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_events private
Definition at line 483 of file boss_valithria_dreamwalker.cpp.
Referenced by DoAction(), HealReceived(), Reset(), and UpdateAI().
_instance
InstanceScript* boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_instance private
Definition at line 484 of file boss_valithria_dreamwalker.cpp.
Referenced by DamageTaken(), DoAction(), HealReceived(), Reset(), SpellHit(), and UpdateAI().
_justDied
bool boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_justDied private
Definition at line 490 of file boss_valithria_dreamwalker.cpp.
Referenced by DamageTaken(), and Reset().
_missedPortals
uint32 boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_missedPortals private
Definition at line 487 of file boss_valithria_dreamwalker.cpp.
Referenced by GetData(), Reset(), and SummonedCreatureDespawn().
_over75PercentTalkDone
bool boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_over75PercentTalkDone private
Definition at line 489 of file boss_valithria_dreamwalker.cpp.
Referenced by HealReceived(), and Reset().
_portalCount
uint32 const boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_portalCount private
Definition at line 486 of file boss_valithria_dreamwalker.cpp.
Referenced by UpdateAI().
_spawnHealth
uint32 boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_spawnHealth private
Definition at line 485 of file boss_valithria_dreamwalker.cpp.
Referenced by boss_valithria_dreamwalkerAI(), Reset(), and UpdateAI().
_under25PercentTalkDone
bool boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::_under25PercentTalkDone private
Definition at line 488 of file boss_valithria_dreamwalker.cpp.
Referenced by DamageTaken(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp