Azerotcore-wotlk: AssistanceDistractMovementGenerator Class Reference
AssistanceDistractMovementGenerator Class Reference
#include <IdleMovementGenerator.h>
Public Member Functions
AssistanceDistractMovementGenerator (uint32 timer)
MovementGeneratorType GetMovementGeneratorType () override
void Finalize (Unit *) override
Public Member Functions inherited from DistractMovementGenerator
DistractMovementGenerator (uint32 timer)
void Initialize (Unit *) override
void Reset (Unit *owner) override
bool Update (Unit *, uint32) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Detailed Description
Definition at line 66 of file IdleMovementGenerator.h.
Constructor & Destructor Documentation
AssistanceDistractMovementGenerator()
AssistanceDistractMovementGenerator::AssistanceDistractMovementGenerator (uint32 timer) inline
Definition at line 69 of file IdleMovementGenerator.h.
                                                       :
         DistractMovementGenerator(timer) {}
Member Function Documentation
Finalize()
void AssistanceDistractMovementGenerator::Finalize (Unit * unit) override virtual
Reimplemented from DistractMovementGenerator.
Definition at line 111 of file IdleMovementGenerator.cpp.
 {
     unit->ClearUnitState(UNIT_STATE_DISTRACTED);
     unit->ToCreature()->SetReactState(REACT_AGGRESSIVE);
 }
References Unit::ClearUnitState(), REACT_AGGRESSIVE, Creature::SetReactState(), Object::ToCreature(), and UNIT_STATE_DISTRACTED.
GetMovementGeneratorType()
MovementGeneratorType AssistanceDistractMovementGenerator::GetMovementGeneratorType () inline override virtual
Reimplemented from DistractMovementGenerator.
Definition at line 72 of file IdleMovementGenerator.h.
 { return ASSISTANCE_DISTRACT_MOTION_TYPE; }
References ASSISTANCE_DISTRACT_MOTION_TYPE.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.h
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.cpp