Azerotcore-wotlk: go_loosely_turned_soil::go_loosely_turned_soilAI Struct Reference
go_loosely_turned_soil::go_loosely_turned_soilAI Struct Reference
Public Member Functions
go_loosely_turned_soilAI (GameObject *gameObject)
bool CanBeSeen (Player const *player) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 1564 of file hallows_end.cpp.
Constructor & Destructor Documentation
go_loosely_turned_soilAI()
go_loosely_turned_soil::go_loosely_turned_soilAI::go_loosely_turned_soilAI (GameObject * gameObject) inline
Definition at line 1566 of file hallows_end.cpp.
 : GameObjectAI(gameObject) { }
Member Function Documentation
CanBeSeen()
bool go_loosely_turned_soil::go_loosely_turned_soilAI::CanBeSeen (Player const * player) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1568 of file hallows_end.cpp.
         {
             if (player->IsGameMaster())
             {
                 return true;
             }
             Group const* group = player->GetGroup();
             return group && sLFGMgr->GetDungeon(group->GetGUID()) == lfg::LFG_DUNGEON_HEADLESS_HORSEMAN;
         }
References Player::GetGroup(), Group::GetGUID(), Player::IsGameMaster(), lfg::LFG_DUNGEON_HEADLESS_HORSEMAN, and sLFGMgr.
The documentation for this struct was generated from the following file:
src/server/scripts/Events/hallows_end.cpp