Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/extent_externs.h File Reference
extent_externs.h File Reference
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/mutex_pool.h"
#include "jemalloc/internal/ph.h"
#include "jemalloc/internal/rtree.h"
Functions
extent_t * extent_alloc (tsdn_t *tsdn, arena_t *arena)
void extent_dalloc (tsdn_t *tsdn, arena_t *arena, extent_t *extent)
extent_hooks_t * extent_hooks_get (arena_t *arena)
extent_hooks_t * extent_hooks_set (tsd_t *tsd, arena_t *arena, extent_hooks_t *extent_hooks)
ph_proto (, extent_avail_, extent_tree_t, extent_t) ph_proto(
extent_t bool extents_init (tsdn_t *tsdn, extents_t *extents, extent_state_t state, bool delay_coalesce)
extent_state_t extents_state_get (const extents_t *extents)
size_t extents_npages_get (extents_t *extents)
size_t extents_nextents_get (extents_t *extents, pszind_t ind)
size_t extents_nbytes_get (extents_t *extents, pszind_t ind)
extent_t * extents_alloc (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
void extents_dalloc (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, extent_t *extent)
extent_t * extents_evict (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, size_t npages_min)
void extents_prefork (tsdn_t *tsdn, extents_t *extents)
void extents_postfork_parent (tsdn_t *tsdn, extents_t *extents)
void extents_postfork_child (tsdn_t *tsdn, extents_t *extents)
extent_t * extent_alloc_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
void extent_dalloc_gap (tsdn_t *tsdn, arena_t *arena, extent_t *extent)
void extent_dalloc_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
void extent_destroy_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
bool extent_commit_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_decommit_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_purge_lazy_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_purge_forced_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
extent_t * extent_split_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b)
bool extent_merge_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *a, extent_t *b)
bool extent_boot (void)
void extent_util_stats_get (tsdn_t *tsdn, const void *ptr, size_t *nfree, size_t *nregs, size_t *size)
void extent_util_stats_verbose_get (tsdn_t *tsdn, const void *ptr, size_t *nfree, size_t *nregs, size_t *size, size_t *bin_nfree, size_t *bin_nregs, void **slabcur_addr)
Variables
size_t opt_lg_extent_max_active_fit
rtree_t extents_rtree
const extent_hooks_t extent_hooks_default
mutex_pool_t extent_mutex_pool
extent_heap_
extent_heap_t
Function Documentation
extent_alloc()
extent_t* extent_alloc (tsdn_t * tsdn, arena_t * arena)
Definition at line 180 of file extent.c.
{
     malloc_mutex_lock(tsdn, &arena->extent_avail_mtx);
     extent_t *extent = extent_avail_first(&arena->extent_avail);
     if (extent == NULL) {
         malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
         return base_alloc_extent(tsdn, arena->base);
     }
     extent_avail_remove(&arena->extent_avail, extent);
     atomic_fetch_sub_zu(&arena->extent_avail_cnt, 1, ATOMIC_RELAXED);
     malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
     return extent;
 }
References arena, ATOMIC_RELAXED, arena_s::base, base_alloc_extent, arena_s::extent_avail, arena_s::extent_avail_cnt, extent_avail_first, arena_s::extent_avail_mtx, extent_avail_remove, malloc_mutex_lock(), malloc_mutex_unlock(), and NULL.
Referenced by extent_alloc_wrapper_hard(), extent_grow_retained(), and extent_split_impl().
extent_alloc_wrapper()
extent_t* extent_alloc_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit)
Definition at line 1531 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     extent_t *extent = extent_alloc_retained(tsdn, arena, r_extent_hooks,
         new_addr, size, pad, alignment, slab, szind, zero, commit);
     if (extent == NULL) {
         if (opt_retain && new_addr != NULL) {
             /*
              * When retain is enabled and new_addr is set, we do not
              * attempt extent_alloc_wrapper_hard which does mmap
              * that is very unlikely to succeed (unless it happens
              * to be at the end).
              */
             return NULL;
         }
         extent = extent_alloc_wrapper_hard(tsdn, arena, r_extent_hooks,
             new_addr, size, pad, alignment, slab, szind, zero, commit);
     }
     assert(extent == NULL || extent_dumpable_get(extent));
     return extent;
 }
References arena, assert(), extent_alloc_retained(), extent_alloc_wrapper_hard(), extent_dumpable_get(), extent_hooks_assure_initialized(), NULL, opt_retain, witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
extent_boot()
bool extent_boot (void)
Definition at line 2319 of file extent.c.
                   {
     if (rtree_new(&extents_rtree, true)) {
         return true;
     }
     if (mutex_pool_init(&extent_mutex_pool, "extent_mutex_pool",
         WITNESS_RANK_EXTENT_POOL)) {
         return true;
     }
     if (have_dss) {
         extent_dss_boot();
     }
     return false;
 }
References extent_dss_boot, extent_mutex_pool, extents_rtree, have_dss, mutex_pool_init, rtree_new, and WITNESS_RANK_EXTENT_POOL.
extent_commit_wrapper()
bool extent_commit_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 1936 of file extent.c.
                    {
     return extent_commit_impl(tsdn, arena, r_extent_hooks, extent, offset,
         length, false);
 }
References arena, extent_commit_impl(), and G3D::length().
extent_dalloc()
void extent_dalloc (tsdn_t * tsdn, arena_t * arena, extent_t * extent)
Definition at line 194 of file extent.c.
{
     malloc_mutex_lock(tsdn, &arena->extent_avail_mtx);
     extent_avail_insert(&arena->extent_avail, extent);
     atomic_fetch_add_zu(&arena->extent_avail_cnt, 1, ATOMIC_RELAXED);
     malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
 }
References arena, ATOMIC_RELAXED, arena_s::extent_avail, arena_s::extent_avail_cnt, extent_avail_insert, arena_s::extent_avail_mtx, malloc_mutex_lock(), and malloc_mutex_unlock().
Referenced by extent_alloc_wrapper_hard(), extent_dalloc_gap(), extent_dalloc_wrapper_try(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_split_impl(), and extents_abandon_vm().
extent_dalloc_gap()
void extent_dalloc_gap (tsdn_t * tsdn, arena_t * arena, extent_t * extent)
Definition at line 1739 of file extent.c.
{
     extent_hooks_t *extent_hooks = EXTENT_HOOKS_INITIALIZER;
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     if (extent_register(tsdn, extent)) {
         extent_dalloc(tsdn, arena, extent);
         return;
     }
     extent_dalloc_wrapper(tsdn, arena, &extent_hooks, extent);
 }
References arena, extent_dalloc(), extent_dalloc_wrapper(), EXTENT_HOOKS_INITIALIZER, extent_register(), witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extent_dalloc_wrapper()
void extent_dalloc_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent)
Definition at line 1807 of file extent.c.
{
     assert(extent_dumpable_get(extent));
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     /* Avoid calling the default extent_dalloc unless have to. */
     if (*r_extent_hooks != &extent_hooks_default || extent_may_dalloc()) {
         /*
          * Deregister first to avoid a race with other allocating
          * threads, and reregister if deallocation fails.
          */
         extent_deregister(tsdn, extent);
         if (!extent_dalloc_wrapper_try(tsdn, arena, r_extent_hooks,
             extent)) {
             return;
         }
         extent_reregister(tsdn, extent);
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     /* Try to decommit; purge if that fails. */
     bool zeroed;
     if (!extent_committed_get(extent)) {
         zeroed = true;
     } else if (!extent_decommit_wrapper(tsdn, arena, r_extent_hooks, extent,
         0, extent_size_get(extent))) {
         zeroed = true;
     } else if ((*r_extent_hooks)->purge_forced != NULL &&
         !(*r_extent_hooks)->purge_forced(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), 0,
         extent_size_get(extent), arena_ind_get(arena))) {
         zeroed = true;
     } else if (extent_state_get(extent) == extent_state_muzzy ||
         ((*r_extent_hooks)->purge_lazy != NULL &&
         !(*r_extent_hooks)->purge_lazy(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), 0,
         extent_size_get(extent), arena_ind_get(arena)))) {
         zeroed = false;
     } else {
         zeroed = false;
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     extent_zeroed_set(extent, zeroed);
     if (config_prof) {
         extent_gdump_sub(tsdn, extent);
     }
     extent_record(tsdn, arena, r_extent_hooks, &arena->extents_retained,
         extent, false);
 }
References arena, arena_ind_get(), assert(), config_prof, extent_base_get(), extent_committed_get(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_deregister(), extent_dumpable_get(), extent_gdump_sub(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_default, extent_may_dalloc(), extent_record(), extent_reregister(), extent_size_get(), extent_state_get(), extent_state_muzzy, extent_zeroed_set(), arena_s::extents_retained, NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_dalloc_gap().
extent_decommit_wrapper()
bool extent_decommit_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 1951 of file extent.c.
                    {
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = ((*r_extent_hooks)->decommit == NULL ||
         (*r_extent_hooks)->decommit(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), offset, length,
         arena_ind_get(arena)));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     extent_committed_set(extent, extent_committed_get(extent) && err);
     return err;
 }
References arena, arena_ind_get(), extent_base_get(), extent_committed_get(), extent_committed_set(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), G3D::length(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_dalloc_wrapper().
extent_destroy_wrapper()
void extent_destroy_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent)
Definition at line 1878 of file extent.c.
{
     assert(extent_base_get(extent) != NULL);
     assert(extent_size_get(extent) != 0);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     /* Deregister first to avoid a race with other allocating threads. */
     extent_deregister(tsdn, extent);
     extent_addr_set(extent, extent_base_get(extent));
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     /* Try to destroy; silently fail otherwise. */
     if (*r_extent_hooks == &extent_hooks_default) {
         /* Call directly to propagate tsdn. */
         extent_destroy_default_impl(extent_base_get(extent),
             extent_size_get(extent));
     } else if ((*r_extent_hooks)->destroy != NULL) {
         extent_hook_pre_reentrancy(tsdn, arena);
         (*r_extent_hooks)->destroy(*r_extent_hooks,
             extent_base_get(extent), extent_size_get(extent),
             extent_committed_get(extent), arena_ind_get(arena));
         extent_hook_post_reentrancy(tsdn);
     }
     extent_dalloc(tsdn, arena, extent);
 }
References arena, arena_ind_get(), assert(), extent_addr_set(), extent_base_get(), extent_committed_get(), extent_dalloc(), extent_deregister(), extent_destroy_default_impl(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extent_hooks_get()
extent_hooks_t* extent_hooks_get (arena_t * arena)
Definition at line 202 of file extent.c.
{
     return base_extent_hooks_get(arena->base);
 }
References arena, arena_s::base, and base_extent_hooks_get.
Referenced by extent_hooks_assure_initialized().
extent_hooks_set()
extent_hooks_t* extent_hooks_set (tsd_t * tsd, arena_t * arena, extent_hooks_t * extent_hooks)
Definition at line 207 of file extent.c.
{
     background_thread_info_t *info;
     if (have_background_thread) {
         info = arena_background_thread_info_get(arena);
         malloc_mutex_lock(tsd_tsdn(tsd), &info->mtx);
     }
     extent_hooks_t *ret = base_extent_hooks_set(arena->base, extent_hooks);
     if (have_background_thread) {
         malloc_mutex_unlock(tsd_tsdn(tsd), &info->mtx);
     }
     return ret;
 }
References arena, arena_background_thread_info_get(), arena_s::base, base_extent_hooks_set, have_background_thread, malloc_mutex_lock(), malloc_mutex_unlock(), background_thread_info_s::mtx, ret, and tsd_tsdn().
extent_merge_wrapper()
bool extent_merge_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * a, extent_t * b)
Definition at line 2313 of file extent.c.
{
     return extent_merge_impl(tsdn, arena, r_extent_hooks, a, b, false);
 }
References mpq::a, arena, b, and extent_merge_impl().
extent_purge_forced_wrapper()
bool extent_purge_forced_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 2059 of file extent.c.
                    {
     return extent_purge_forced_impl(tsdn, arena, r_extent_hooks, extent,
         offset, length, false);
 }
References arena, extent_purge_forced_impl(), and G3D::length().
extent_purge_lazy_wrapper()
bool extent_purge_lazy_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 2013 of file extent.c.
                    {
     return extent_purge_lazy_impl(tsdn, arena, r_extent_hooks, extent,
         offset, length, false);
 }
References arena, extent_purge_lazy_impl(), and G3D::length().
extent_split_wrapper()
extent_t* extent_split_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b)
Definition at line 2173 of file extent.c.
{
     return extent_split_impl(tsdn, arena, r_extent_hooks, extent, size_a,
         szind_a, slab_a, size_b, szind_b, slab_b, false);
 }
References arena, and extent_split_impl().
extent_util_stats_get()
void extent_util_stats_get (tsdn_t * tsdn, const void * ptr, size_t * nfree, size_t * nregs, size_t * size)
Definition at line 2337 of file extent.c.
{
     assert(ptr != NULL && nfree != NULL && nregs != NULL && size != NULL);
     const extent_t *extent = iealloc(tsdn, ptr);
     if (unlikely(extent == NULL)) {
         *nfree = *nregs = *size = 0;
         return;
     }
     *size = extent_size_get(extent);
     if (!extent_slab_get(extent)) {
         *nfree = 0;
         *nregs = 1;
     } else {
         *nfree = extent_nfree_get(extent);
         *nregs = bin_infos[extent_szind_get(extent)].nregs;
         assert(*nfree <= *nregs);
         assert(*nfree * extent_usize_get(extent) <= *size);
     }
 }
References assert(), bin_infos, extent_nfree_get(), extent_size_get(), extent_slab_get(), extent_szind_get(), extent_usize_get(), iealloc(), NULL, ptr(), and unlikely.
extent_util_stats_verbose_get()
void extent_util_stats_verbose_get (tsdn_t * tsdn, const void * ptr, size_t * nfree, size_t * nregs, size_t * size, size_t * bin_nfree, size_t * bin_nregs, void ** slabcur_addr)
Definition at line 2360 of file extent.c.
{
     assert(ptr != NULL && nfree != NULL && nregs != NULL && size != NULL
         && bin_nfree != NULL && bin_nregs != NULL && slabcur_addr != NULL);
     const extent_t *extent = iealloc(tsdn, ptr);
     if (unlikely(extent == NULL)) {
         *nfree = *nregs = *size = *bin_nfree = *bin_nregs = 0;
         *slabcur_addr = NULL;
         return;
     }
     *size = extent_size_get(extent);
     if (!extent_slab_get(extent)) {
         *nfree = *bin_nfree = *bin_nregs = 0;
         *nregs = 1;
         *slabcur_addr = NULL;
         return;
     }
     *nfree = extent_nfree_get(extent);
     const szind_t szind = extent_szind_get(extent);
     *nregs = bin_infos[szind].nregs;
     assert(*nfree <= *nregs);
     assert(*nfree * extent_usize_get(extent) <= *size);
     const arena_t *arena = extent_arena_get(extent);
     assert(arena != NULL);
     const unsigned binshard = extent_binshard_get(extent);
     bin_t *bin = &arena->bins[szind].bin_shards[binshard];
     malloc_mutex_lock(tsdn, &bin->lock);
     if (config_stats) {
         *bin_nregs = *nregs * bin->stats.curslabs;
         assert(*bin_nregs >= bin->stats.curregs);
         *bin_nfree = *bin_nregs - bin->stats.curregs;
     } else {
         *bin_nfree = *bin_nregs = 0;
     }
     *slabcur_addr = extent_addr_get(bin->slabcur);
     assert(*slabcur_addr != NULL);
     malloc_mutex_unlock(tsdn, &bin->lock);
 }
References arena, assert(), bin_infos, bins_s::bin_shards, arena_s::bins, config_stats, bin_stats_s::curregs, bin_stats_s::curslabs, extent_addr_get(), extent_arena_get(), extent_binshard_get(), extent_nfree_get(), extent_size_get(), extent_slab_get(), extent_szind_get(), extent_usize_get(), iealloc(), bin_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ptr(), bin_s::slabcur, bin_s::stats, and unlikely.
extents_alloc()
extent_t* extents_alloc (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit)
Definition at line 537 of file extent.c.
{
     assert(size + pad != 0);
     assert(alignment != 0);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_t *extent = extent_recycle(tsdn, arena, r_extent_hooks, extents,
         new_addr, size, pad, alignment, slab, szind, zero, commit, false);
     assert(extent == NULL || extent_dumpable_get(extent));
     return extent;
 }
References arena, assert(), extent_dumpable_get(), extent_recycle(), NULL, witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
extents_dalloc()
void extents_dalloc (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, extent_t * extent)
Definition at line 552 of file extent.c.
{
     assert(extent_base_get(extent) != NULL);
     assert(extent_size_get(extent) != 0);
     assert(extent_dumpable_get(extent));
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_addr_set(extent, extent_base_get(extent));
     extent_zeroed_set(extent, false);
     extent_record(tsdn, arena, r_extent_hooks, extents, extent, false);
 }
References arena, assert(), extent_addr_set(), extent_base_get(), extent_dumpable_get(), extent_record(), extent_size_get(), extent_zeroed_set(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extents_evict()
extent_t* extents_evict (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, size_t npages_min)
Definition at line 567 of file extent.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     malloc_mutex_lock(tsdn, &extents->mtx);
     /*
      * Get the LRU coalesced extent, if any.  If coalescing was delayed,
      * the loop will iterate until the LRU extent is fully coalesced.
      */
     extent_t *extent;
     while (true) {
         /* Get the LRU extent, if any. */
         extent = extent_list_first(&extents->lru);
         if (extent == NULL) {
             goto label_return;
         }
         /* Check the eviction limit. */
         size_t extents_npages = atomic_load_zu(&extents->npages,
             ATOMIC_RELAXED);
         if (extents_npages <= npages_min) {
             extent = NULL;
             goto label_return;
         }
         extents_remove_locked(tsdn, extents, extent);
         if (!extents->delay_coalesce) {
             break;
         }
         /* Try to coalesce. */
         if (extent_try_delayed_coalesce(tsdn, arena, r_extent_hooks,
             rtree_ctx, extents, extent)) {
             break;
         }
         /*
          * The LRU extent was just coalesced and the result placed in
          * the LRU at its neighbor's position.  Start over.
          */
     }
     /*
      * Either mark the extent active or deregister it to protect against
      * concurrent operations.
      */
     switch (extents_state_get(extents)) {
     case extent_state_active:
         not_reached();
     case extent_state_dirty:
     case extent_state_muzzy:
         extent_state_set(extent, extent_state_active);
         break;
     case extent_state_retained:
         extent_deregister(tsdn, extent);
         break;
     default:
         not_reached();
     }
 label_return:
     malloc_mutex_unlock(tsdn, &extents->mtx);
     return extent;
 }
References arena, ATOMIC_RELAXED, extents_s::delay_coalesce, extent_deregister(), extent_list_first(), extent_state_active, extent_state_dirty, extent_state_muzzy, extent_state_retained, extent_state_set(), extent_try_delayed_coalesce(), extents_remove_locked(), extents_state_get(), extents_s::lru, malloc_mutex_lock(), malloc_mutex_unlock(), extents_s::mtx, not_reached, extents_s::npages, NULL, and tsdn_rtree_ctx().
extents_init()
extent_t bool extents_init (tsdn_t * tsdn, extents_t * extents, extent_state_t state, bool delay_coalesce)
Referenced by arena_new().
extents_nbytes_get()
size_t extents_nbytes_get (extents_t * extents, pszind_t ind)
Definition at line 319 of file extent.c.
{
     return atomic_load_zu(&extents->nbytes[pind], ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::nbytes.
extents_nextents_get()
size_t extents_nextents_get (extents_t * extents, pszind_t ind)
Definition at line 314 of file extent.c.
{
     return atomic_load_zu(&extents->nextents[pind], ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::nextents.
extents_npages_get()
size_t extents_npages_get (extents_t * extents)
Definition at line 309 of file extent.c.
{
     return atomic_load_zu(&extents->npages, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::npages.
extents_postfork_child()
void extents_postfork_child (tsdn_t * tsdn, extents_t * extents)
Definition at line 667 of file extent.c.
{
     malloc_mutex_postfork_child(tsdn, &extents->mtx);
 }
References malloc_mutex_postfork_child, and extents_s::mtx.
extents_postfork_parent()
void extents_postfork_parent (tsdn_t * tsdn, extents_t * extents)
Definition at line 662 of file extent.c.
{
     malloc_mutex_postfork_parent(tsdn, &extents->mtx);
 }
References malloc_mutex_postfork_parent, and extents_s::mtx.
extents_prefork()
void extents_prefork (tsdn_t * tsdn, extents_t * extents)
Definition at line 657 of file extent.c.
{
     malloc_mutex_prefork(tsdn, &extents->mtx);
 }
References malloc_mutex_prefork, and extents_s::mtx.
extents_state_get()
extent_state_t extents_state_get (const extents_t * extents)
Definition at line 304 of file extent.c.
{
     return extents->state;
 }
References extents_s::state.
Referenced by extent_activate_locked(), extent_deactivate_locked(), extent_record(), extent_recycle_extract(), extent_try_delayed_coalesce(), extents_abandon_vm(), and extents_evict().
ph_proto()
ph_proto (extent_avail_ , extent_tree_t , extent_t)
Variable Documentation
extent_heap_
extent_heap_
Definition at line 28 of file extent_externs.h.
extent_heap_t
extent_heap_t
Definition at line 28 of file extent_externs.h.
extent_hooks_default
const extent_hooks_t extent_hooks_default extern
Definition at line 67 of file extent.c.
Referenced by extent_alloc_wrapper_hard(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), and extent_split_impl().
extent_mutex_pool
mutex_pool_t extent_mutex_pool extern
Definition at line 18 of file extent.c.
Referenced by extent_boot().
extents_rtree
rtree_t extents_rtree extern
Definition at line 16 of file extent.c.
Referenced by extent_boot(), extent_interior_deregister(), extent_interior_register(), extent_lock_from_addr(), extent_merge_impl(), extent_record(), extent_rtree_leaf_elm_try_lock(), extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), and extent_split_interior().
opt_lg_extent_max_active_fit
size_t opt_lg_extent_max_active_fit extern
Definition at line 20 of file extent.c.
Referenced by extents_first_fit_locked().