Azerotcore-wotlk: spell_warl_drain_soul Class Reference
spell_warl_drain_soul Class Reference
Private Member Functions
PrepareAuraScript (spell_warl_drain_soul)
bool Validate (SpellInfo const *) override
bool CheckProc (ProcEventInfo &eventInfo)
void HandleProc (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void HandleTick (AuraEffect const *aurEff)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1109 of file spell_warlock.cpp.
Member Function Documentation
CheckProc()
bool spell_warl_drain_soul::CheckProc (ProcEventInfo & eventInfo) inline private
Definition at line 1125 of file spell_warlock.cpp.
     {
         // Drain Soul's proc tries to happen each time the warlock lands a killing blow on a unit while channeling.
         // Make sure that the dying unit is afflicted by the caster's Drain Soul debuff in order to avoid a false positive.
         Unit* caster = GetCaster();
         Unit* victim = eventInfo.GetProcTarget();
         if (caster && victim)
         {
             return victim->GetAuraApplicationOfRankedSpell(SPELL_WARLOCK_DRAIN_SOUL_R1, caster->GetGUID()) != 0;
         }
         return false;
     }
References Unit::GetAuraApplicationOfRankedSpell(), AuraScript::GetCaster(), Object::GetGUID(), ProcEventInfo::GetProcTarget(), and SPELL_WARLOCK_DRAIN_SOUL_R1.
Referenced by Register().
HandleProc()
void spell_warl_drain_soul::HandleProc (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
Definition at line 1141 of file spell_warlock.cpp.
     {
         PreventDefaultAction();
         Unit* caster = eventInfo.GetActor();
         // Improved Drain Soul.
         if (Aura const* impDrainSoul = caster->GetAuraOfRankedSpell(SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_R1, caster->GetGUID()))
         {
             int32 amount = CalculatePct(caster->GetMaxPower(POWER_MANA), impDrainSoul->GetSpellInfo()->Effects[EFFECT_2].CalcValue());
             caster->CastCustomSpell(SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_PROC, SPELLVALUE_BASE_POINT0, amount, caster, true, nullptr, aurEff, caster->GetGUID());
         }
     }
References CalculatePct(), Unit::CastCustomSpell(), EFFECT_2, ProcEventInfo::GetActor(), Unit::GetAuraOfRankedSpell(), Object::GetGUID(), Unit::GetMaxPower(), POWER_MANA, AuraScript::PreventDefaultAction(), SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_PROC, SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_R1, and SPELLVALUE_BASE_POINT0.
Referenced by Register().
HandleTick()
void spell_warl_drain_soul::HandleTick (AuraEffect const * aurEff) inline private
Definition at line 1154 of file spell_warlock.cpp.
     {
         Unit* caster = GetCaster();
         Unit* target = GetTarget();
         if (caster && caster->GetTypeId() == TYPEID_PLAYER && caster->ToPlayer()->isHonorOrXPTarget(target))
         {
             if (roll_chance_i(20))
             {
                 caster->CastSpell(caster, SPELL_WARLOCK_CREATE_SOULSHARD, aurEff);
                 // Glyph of Drain Soul - chance to create an additional Soul Shard.
                 if (AuraEffect* aur = caster->GetAuraEffect(SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_AURA, EFFECT_0))
                 {
                     if (roll_chance_i(aur->GetMiscValue()))
                     {
                         caster->CastSpell(caster, SPELL_WARLOCK_CREATE_SOULSHARD, aur);
                     }
                 }
             }
         }
     }
References Unit::CastSpell(), EFFECT_0, Unit::GetAuraEffect(), AuraScript::GetCaster(), AuraScript::GetTarget(), Object::GetTypeId(), Player::isHonorOrXPTarget(), roll_chance_i(), SPELL_WARLOCK_CREATE_SOULSHARD, SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_AURA, Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by Register().
PrepareAuraScript()
spell_warl_drain_soul::PrepareAuraScript (spell_warl_drain_soul) private
Register()
void spell_warl_drain_soul::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1176 of file spell_warlock.cpp.
     {
         DoCheckProc += AuraCheckProcFn(spell_warl_drain_soul::CheckProc);
         OnEffectPeriodic += AuraEffectPeriodicFn(spell_warl_drain_soul::HandleTick, EFFECT_1, SPELL_AURA_PERIODIC_DAMAGE);
         OnEffectProc += AuraEffectProcFn(spell_warl_drain_soul::HandleProc, EFFECT_2, SPELL_AURA_PROC_TRIGGER_SPELL);
     }
References AuraCheckProcFn, AuraEffectPeriodicFn, AuraEffectProcFn, CheckProc(), AuraScript::DoCheckProc, EFFECT_1, EFFECT_2, HandleProc(), HandleTick(), AuraScript::OnEffectPeriodic, AuraScript::OnEffectProc, SPELL_AURA_PERIODIC_DAMAGE, and SPELL_AURA_PROC_TRIGGER_SPELL.
Validate()
bool spell_warl_drain_soul::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1113 of file spell_warlock.cpp.
     {
         return ValidateSpellInfo(
         {
             SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_R1,
             SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_PROC,
             SPELL_WARLOCK_CREATE_SOULSHARD,
             SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_AURA,
             SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_PROC
         });
     }
References SPELL_WARLOCK_CREATE_SOULSHARD, SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_AURA, SPELL_WARLOCK_GLYPH_OF_DRAIN_SOUL_PROC, SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_PROC, SPELL_WARLOCK_IMPROVED_DRAIN_SOUL_R1, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_warlock.cpp