Azerotcore-wotlk: boss_akilzon::boss_akilzonAI Struct Reference
boss_akilzon::boss_akilzonAI Struct Reference
Public Member Functions
boss_akilzonAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void SetWeather (uint32 weather, float grade)
void HandleStormSequence (Unit *Cloud)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
ObjectGuid BirdGUIDs [8]
ObjectGuid TargetGUID
ObjectGuid CycloneGUID
ObjectGuid CloudGUID
uint8 StormCount
bool isRaining
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 87 of file boss_akilzon.cpp.
Constructor & Destructor Documentation
boss_akilzonAI()
boss_akilzon::boss_akilzonAI::boss_akilzonAI (Creature * creature) inline
Definition at line 89 of file boss_akilzon.cpp.
                                            : BossAI(creature, DATA_AKILZONEVENT)
         {
         }
Member Function Documentation
EnterCombat()
void boss_akilzon::boss_akilzonAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 113 of file boss_akilzon.cpp.
         {
             events.ScheduleEvent(EVENT_STATIC_DISRUPTION, urand(10000, 20000)); // 10 to 20 seconds (bosskillers)
             events.ScheduleEvent(EVENT_GUST_OF_WIND, urand(20000, 30000));      // 20 to 30 seconds(bosskillers)
             events.ScheduleEvent(EVENT_CALL_LIGHTNING, urand(10000, 20000));    // totaly random timer. can't find any info on this
             events.ScheduleEvent(EVENT_ELECTRICAL_STORM, 60000);                // 60 seconds(bosskillers)
             events.ScheduleEvent(EVENT_RAIN, urand(47000, 52000));
             events.ScheduleEvent(EVENT_ENRAGE, 10 * MINUTE * IN_MILLISECONDS);  // 10 minutes till enrage(bosskillers)
             Talk(SAY_AGGRO);
             //DoZoneInCombat();
             if (instance)
                 instance->SetData(DATA_AKILZONEVENT, IN_PROGRESS);
         }
References DATA_AKILZONEVENT, EVENT_CALL_LIGHTNING, EVENT_ELECTRICAL_STORM, EVENT_ENRAGE, EVENT_GUST_OF_WIND, EVENT_RAIN, EVENT_STATIC_DISRUPTION, IN_MILLISECONDS, IN_PROGRESS, BossAI::instance, MINUTE, SAY_AGGRO, ZoneScript::SetData(), CreatureAI::Talk(), and urand().
HandleStormSequence()
void boss_akilzon::boss_akilzonAI::HandleStormSequence (Unit * Cloud) inline
Definition at line 155 of file boss_akilzon.cpp.
         {
             if (StormCount < 10 && StormCount > 1)
             {
                 // deal damage
                 int32 bp0 = 800;
                 for (uint8 i = 2; i < StormCount; ++i)
                     bp0 *= 2;
                 std::list<Unit*> tempUnitMap;
                 Acore::AnyAoETargetUnitInObjectRangeCheck u_check(me, me, SIZE_OF_GRIDS);
                 Acore::UnitListSearcher<Acore::AnyAoETargetUnitInObjectRangeCheck> searcher(me, tempUnitMap, u_check);
                 Cell::VisitAllObjects(me, searcher, SIZE_OF_GRIDS);
                 // deal damage
                 for (std::list<Unit*>::const_iterator i = tempUnitMap.begin(); i != tempUnitMap.end(); ++i)
                 {
                     if (Unit* target = (*i))
                     {
                         if (Cloud && !Cloud->IsWithinDist(target, 6, false))
                             Cloud->CastCustomSpell(target, SPELL_ZAP, &bp0, nullptr, nullptr, true, 0, 0, me->GetGUID());
                     }
                 }
                 // visual
                 float x, y, z;
                 z = me->GetPositionZ();
                 for (uint8 i = 0; i < 5 + rand() % 5; ++i)
                 {
                     x = 343.0f + rand() % 60;
                     y = 1380.0f + rand() % 60;
                     if (Unit* trigger = me->SummonTrigger(x, y, z, 0, 2000))
                     {
                         trigger->SetFaction(FACTION_FRIENDLY);
                         trigger->SetMaxHealth(100000);
                         trigger->SetHealth(100000);
                         trigger->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         if (Cloud)
                             Cloud->CastCustomSpell(trigger, /*43661*/SPELL_ZAP, &bp0, nullptr, nullptr, true, 0, 0, Cloud->GetGUID());
                     }
                 }
             }
             ++StormCount;
             if (StormCount > 10)
             {
                 StormCount = 0; // finish
                 events.ScheduleEvent(EVENT_SUMMON_EAGLES, 5000);
                 me->InterruptNonMeleeSpells(false);
                 CloudGUID.Clear();
                 if (Cloud)
                     Unit::DealDamage(Cloud, Cloud, Cloud->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                 SetWeather(WEATHER_STATE_FINE, 0.0f);
                 isRaining = false;
             }
             events.ScheduleEvent(EVENT_STORM_SEQUENCE, 1000);
         }
References Unit::CastCustomSpell(), ObjectGuid::Clear(), CloudGUID, Unit::DealDamage(), DIRECT_DAMAGE, EVENT_STORM_SEQUENCE, EVENT_SUMMON_EAGLES, FACTION_FRIENDLY, Object::GetGUID(), Unit::GetHealth(), Position::GetPositionZ(), Unit::InterruptNonMeleeSpells(), isRaining, WorldObject::IsWithinDist(), ScriptedAI::me, SetWeather(), SIZE_OF_GRIDS, SPELL_SCHOOL_MASK_NORMAL, SPELL_ZAP, StormCount, WorldObject::SummonTrigger(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, Cell::VisitAllObjects(), and WEATHER_STATE_FINE.
Referenced by UpdateAI().
JustDied()
void boss_akilzon::boss_akilzonAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 129 of file boss_akilzon.cpp.
         {
             Talk(SAY_DEATH);
             _JustDied();
             if (instance)
                 instance->SetData(DATA_AKILZONEVENT, DONE);
         }
References BossAI::_JustDied(), DATA_AKILZONEVENT, DONE, BossAI::instance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
KilledUnit()
void boss_akilzon::boss_akilzonAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 137 of file boss_akilzon.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_akilzon::boss_akilzonAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 93 of file boss_akilzon.cpp.
         {
             _Reset();
             TargetGUID.Clear();
             CloudGUID.Clear();
             CycloneGUID.Clear();
             for (uint8 i = 0; i < 8; ++i)
                 BirdGUIDs[i].Clear();
             StormCount = 0;
             isRaining = false;
             if (instance)
                 instance->SetData(DATA_AKILZONEVENT, NOT_STARTED);
             SetWeather(WEATHER_STATE_FINE, 0.0f);
         }
References BossAI::_Reset(), BirdGUIDs, ObjectGuid::Clear(), CloudGUID, CycloneGUID, DATA_AKILZONEVENT, BossAI::instance, isRaining, NOT_STARTED, ZoneScript::SetData(), SetWeather(), StormCount, TargetGUID, and WEATHER_STATE_FINE.
SetWeather()
void boss_akilzon::boss_akilzonAI::SetWeather (uint32 weather, float grade) inline
Definition at line 143 of file boss_akilzon.cpp.
         {
             Map* map = me->GetMap();
             if (!map->IsDungeon())
                 return;
             WorldPacket data(SMSG_WEATHER, (4 + 4 + 4));
             data << uint32(weather) << float(grade) << uint8(0);
             map->SendToPlayers(&data);
         }
References WorldObject::GetMap(), Map::IsDungeon(), ScriptedAI::me, Map::SendToPlayers(), and SMSG_WEATHER.
Referenced by HandleStormSequence(), Reset(), and UpdateAI().
UpdateAI()
void boss_akilzon::boss_akilzonAI::UpdateAI (uint32 diff) inline override virtual
Todo:
: fix it in correct way, that causes player to can fly until logout
Reimplemented from BossAI.
Definition at line 215 of file boss_akilzon.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_STATIC_DISRUPTION:
{
                             Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1);
                             if (!target)
                                 target = me->GetVictim();
                             if (target)
{
                                 TargetGUID = target->GetGUID();
                                 DoCast(target, SPELL_STATIC_DISRUPTION, false);
                                 me->SetInFront(me->GetVictim());
                             }
                             /*if (float dist = me->IsWithinDist3d(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 5.0f) dist = 5.0f;
                             SDisruptAOEVisual_Timer = 1000 + floor(dist / 30 * 1000.0f);*/
                             events.ScheduleEvent(EVENT_STATIC_DISRUPTION, urand(10000, 18000));
                             break;
                         }
                     case EVENT_GUST_OF_WIND:
{
                             Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1);
                             if (!target)
                                 target = me->GetVictim();
                             if (target)
                                 DoCast(target, SPELL_GUST_OF_WIND);
                             events.ScheduleEvent(EVENT_GUST_OF_WIND, urand(20000, 30000));
                             break;
                         }
                     case EVENT_CALL_LIGHTNING:
                         DoCastVictim(SPELL_CALL_LIGHTNING);
                         events.ScheduleEvent(EVENT_CALL_LIGHTNING, urand(12000, 17000)); // totaly random timer. can't find any info on this
                         break;
                     case EVENT_ELECTRICAL_STORM:
{
                             Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 50, true);
                             if (!target)
{
                                 EnterEvadeMode();
                                 return;
                             }
                             target->CastSpell(target, 44007, true); // cloud visual
                             DoCast(target, SPELL_ELECTRICAL_STORM, false); // storm cyclon + visual
                             float x, y, z;
                             target->GetPosition(x, y, z);
                             /*
                             if (target)
{
                                 target->SetDisableGravity(true);
                                 target->MonsterMoveWithSpeed(x, y, me->GetPositionZ()+15, 0);
                             }
                             */
                             Unit* Cloud = me->SummonTrigger(x, y, me->GetPositionZ() + 16, 0, 15000);
                             if (Cloud)
{
                                 CloudGUID = Cloud->GetGUID();
                                 Cloud->SetDisableGravity(true);
                                 Cloud->StopMoving();
                                 Cloud->SetObjectScale(1.0f);
                                 Cloud->SetFaction(FACTION_FRIENDLY);
                                 Cloud->SetMaxHealth(9999999);
                                 Cloud->SetHealth(9999999);
                                 Cloud->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                             }
                             StormCount = 1;
                             events.ScheduleEvent(EVENT_ELECTRICAL_STORM, 60000); // 60 seconds(bosskillers)
                             events.ScheduleEvent(EVENT_RAIN, urand(47000, 52000));
                             break;
                         }
                     case EVENT_RAIN:
                         if (!isRaining)
{
                             SetWeather(WEATHER_STATE_HEAVY_RAIN, 0.9999f);
                             isRaining = true;
                         }
                         else
                             events.ScheduleEvent(EVENT_RAIN, 1000);
                         break;
                     case EVENT_STORM_SEQUENCE:
{
                             Unit* target = ObjectAccessor::GetUnit(*me, CloudGUID);
                             if (!target || !target->IsAlive())
{
                                 EnterEvadeMode();
                                 return;
                             }
                             else if (Unit* Cyclone = ObjectAccessor::GetUnit(*me, CycloneGUID))
                                 Cyclone->CastSpell(target, SPELL_SAND_STORM, true); // keep casting or...
                             HandleStormSequence(target);
                             break;
                         }
                     case EVENT_SUMMON_EAGLES:
                         Talk(SAY_SUMMON);
                         float x, y, z;
                         me->GetPosition(x, y, z);
                         for (uint8 i = 0; i < 8; ++i)
{
                             Unit* bird = ObjectAccessor::GetUnit(*me, BirdGUIDs[i]);
                             if (!bird) //they despawned on die
{
                                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                                     x = target->GetPositionX() + irand(-10, 10);
                                     y = target->GetPositionY() + irand(-10, 10);
                                     z = target->GetPositionZ() + urand(16, 20);
                                     if (z > 95)
                                         z = 95.0f - urand(0, 5);
                                 }
                                 Creature* creature = me->SummonCreature(NPC_SOARING_EAGLE, x, y, z, 0, TEMPSUMMON_CORPSE_DESPAWN, 0);
                                 if (creature)
{
                                     creature->AddThreat(me->GetVictim(), 1.0f);
                                     creature->AI()->AttackStart(me->GetVictim());
                                     BirdGUIDs[i] = creature->GetGUID();
                                 }
                             }
                         }
                         break;
                     case EVENT_ENRAGE:
                         Talk(SAY_ENRAGE);
                         DoCast(me, SPELL_BERSERK, true);
                         events.ScheduleEvent(EVENT_ENRAGE, 600000);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), BirdGUIDs, Unit::CastSpell(), CloudGUID, CycloneGUID, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EVENT_CALL_LIGHTNING, EVENT_ELECTRICAL_STORM, EVENT_ENRAGE, EVENT_GUST_OF_WIND, EVENT_RAIN, EVENT_STATIC_DISRUPTION, EVENT_STORM_SEQUENCE, EVENT_SUMMON_EAGLES, FACTION_FRIENDLY, Object::GetGUID(), Position::GetPosition(), Position::GetPositionZ(), ObjectAccessor::GetUnit(), Unit::GetVictim(), HandleStormSequence(), irand(), Unit::IsAlive(), isRaining, ScriptedAI::me, NPC_SOARING_EAGLE, Object::RemoveFlag(), SAY_ENRAGE, SAY_SUMMON, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetDisableGravity(), Unit::SetFaction(), Unit::SetHealth(), Unit::SetInFront(), Unit::SetMaxHealth(), Object::SetObjectScale(), SetWeather(), SPELL_BERSERK, SPELL_CALL_LIGHTNING, SPELL_ELECTRICAL_STORM, SPELL_GUST_OF_WIND, SPELL_SAND_STORM, SPELL_STATIC_DISRUPTION, Unit::StopMoving(), StormCount, WorldObject::SummonCreature(), WorldObject::SummonTrigger(), CreatureAI::Talk(), TargetGUID, TEMPSUMMON_CORPSE_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, CreatureAI::UpdateVictim(), urand(), and WEATHER_STATE_HEAVY_RAIN.
Member Data Documentation
BirdGUIDs
ObjectGuid boss_akilzon::boss_akilzonAI::BirdGUIDs[8] private
Definition at line 359 of file boss_akilzon.cpp.
Referenced by Reset(), and UpdateAI().
CloudGUID
ObjectGuid boss_akilzon::boss_akilzonAI::CloudGUID private
Definition at line 362 of file boss_akilzon.cpp.
Referenced by HandleStormSequence(), Reset(), and UpdateAI().
CycloneGUID
ObjectGuid boss_akilzon::boss_akilzonAI::CycloneGUID private
Definition at line 361 of file boss_akilzon.cpp.
Referenced by Reset(), and UpdateAI().
isRaining
bool boss_akilzon::boss_akilzonAI::isRaining private
Definition at line 364 of file boss_akilzon.cpp.
Referenced by HandleStormSequence(), Reset(), and UpdateAI().
StormCount
uint8 boss_akilzon::boss_akilzonAI::StormCount private
Definition at line 363 of file boss_akilzon.cpp.
Referenced by HandleStormSequence(), Reset(), and UpdateAI().
TargetGUID
ObjectGuid boss_akilzon::boss_akilzonAI::TargetGUID private
Definition at line 360 of file boss_akilzon.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp