Azerotcore-wotlk: deps/mysqllite/mysys/my_symlink.c File Reference
my_symlink.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <m_string.h>
#include <errno.h>
Macros
#define BUFF_LEN FN_LEN
Functions
int my_readlink (char *to, const char *filename, myf MyFlags)
int my_symlink (const char *content, const char *linkname, myf MyFlags)
int my_is_symlink (const char *filename __attribute__((unused)))
int my_realpath (char *to, const char *filename, myf MyFlags)
Macro Definition Documentation
BUFF_LEN
#define BUFF_LEN FN_LEN
Definition at line 98 of file my_symlink.c.
Function Documentation
my_is_symlink()
int my_is_symlink (const char *filename __attribute__(unused))
Definition at line 102 of file my_symlink.c.
 {
 #if defined (HAVE_LSTAT) && defined (S_ISLNK)
   struct stat stat_buff;
   return !lstat(filename, &stat_buff) && S_ISLNK(stat_buff.st_mode);
 #elif defined (_WIN32)
   DWORD dwAttr = GetFileAttributes(filename);
   return (dwAttr != INVALID_FILE_ATTRIBUTES) &&
     (dwAttr & FILE_ATTRIBUTE_REPARSE_POINT);
 #else  /* No symlinks */
   return 0;
 #endif
 }
my_readlink()
int my_readlink (char * to, const char * filename, myf MyFlags)
Definition at line 35 of file my_symlink.c.
 {
 #ifndef HAVE_READLINK
   strmov(to,filename);
   return 1;
 #else
   int result=0;
   int length;
   DBUG_ENTER("my_readlink");
   if ((length=readlink(filename, to, FN_REFLEN-1)) < 0)
   {
     /* Don't give an error if this wasn't a symlink */
     if ((my_errno=errno) == EINVAL)
     {
       result= 1;
       strmov(to,filename);
     }
     else
     {
       if (MyFlags & MY_WME)
     my_error(EE_CANT_READLINK, MYF(0), filename, errno);
       result= -1;
     }
   }
   else
     to[length]=0;
   DBUG_PRINT("exit" ,("result: %d", result));
   DBUG_RETURN(result);
 #endif /* HAVE_READLINK */
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_READLINK, errno, FN_REFLEN, G3D::length(), my_errno, my_error(), MY_WME, MYF, readlink, and strmov().
Referenced by fn_format(), my_delete_with_symlink(), and my_rename_with_symlink().
my_realpath()
int my_realpath (char * to, const char * filename, myf MyFlags)
Definition at line 121 of file my_symlink.c.
 {
 #if defined(HAVE_REALPATH) && !defined(HAVE_BROKEN_REALPATH)
   int result=0;
   char buff[BUFF_LEN];
   char *ptr;
   DBUG_ENTER("my_realpath");
   DBUG_PRINT("info",("executing realpath"));
   if ((ptr=realpath(filename,buff)))
       strmake(to,ptr,FN_REFLEN-1);
   else
   {
     /*
       Realpath didn't work;  Use my_load_path() which is a poor substitute
       original name but will at least be able to resolve paths that starts
       with '.'.
     */
     DBUG_PRINT("error",("realpath failed with errno: %d", errno));
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_REALPATH, MYF(0), filename, my_errno);
     my_load_path(to, filename, NullS);
     result= -1;
   }
   DBUG_RETURN(result);
 #else
 #ifdef _WIN32
   int ret= GetFullPathName(filename,FN_REFLEN,
                            to,
                            NULL);
   if (ret == 0 || ret > FN_REFLEN)
   {
     if (ret > FN_REFLEN)
       my_errno= ENAMETOOLONG;
     else
       my_errno= EACCES;
     if (MyFlags & MY_WME)
       my_error(EE_REALPATH, MYF(0), filename, my_errno);
       return -1;
   }
 #else
   my_load_path(to, filename, NullS);
 #endif
   return 0;
 #endif
 }
References BUFF_LEN, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_REALPATH, errno, FN_REFLEN, my_errno, my_error(), my_load_path(), MY_WME, MYF, NULL, NullS, ptr(), ret, and strmake().
Referenced by fn_format(), my_create_with_symlink(), and mysql_read_default_options().
my_symlink()
int my_symlink (const char * content, const char * linkname, myf MyFlags)
Definition at line 70 of file my_symlink.c.
 {
 #ifndef HAVE_READLINK
   return 0;
 #else
   int result;
   DBUG_ENTER("my_symlink");
   DBUG_PRINT("enter",("content: %s  linkname: %s", content, linkname));
   result= 0;
   if (symlink(content, linkname))
   {
     result= -1;
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SYMLINK, MYF(0), linkname, content, errno);
   }
   else if ((MyFlags & MY_SYNC_DIR) && my_sync_dir_by_file(linkname, MyFlags))
     result= -1;
   DBUG_RETURN(result);
 #endif /* HAVE_READLINK */
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SYMLINK, errno, my_errno, my_error(), MY_SYNC_DIR, my_sync_dir_by_file(), MY_WME, and MYF.
Referenced by my_create_with_symlink(), and my_rename_with_symlink().