Azerotcore-wotlk: G3D::AABox Class Reference
G3D::AABox Class Reference
#include <AABox.h>
Public Member Functions
AABox ()
AABox (const Point3 &v)
AABox (const class Any &a)
Any toAny () const
bool isEmpty () const
AABox (const Point3 &low, const Point3 &high)
AABox operator* (float f) const
AABox operator/ (float f) const
void set (const Point3 &low, const Point3 &high)
void merge (const AABox &a)
void merge (const Point3 &a)
void merge (const class Box &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
bool isFinite () const
const Point3 & low () const
const Point3 & high () const
Point3 center () const
Point3 corner (int index) const
float extent (int a) const
Vector3 extent () const
void split (const Vector3::Axis &axis, float location, AABox &low, AABox &high) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex, const uint32 testMask, uint32 &childMask) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex=dummy, const uint32 testMask=0xFFFFFFFF) const
bool contains (const AABox &other) const
bool contains (const Point3 &point) const
float area () const
float volume () const
Point3 randomInteriorPoint () const
Point3 randomSurfacePoint () const
bool intersects (const AABox &other) const
bool intersects (const Sphere &other) const
AABox intersect (const AABox &other) const
size_t hashCode () const
bool operator== (const AABox &b) const
bool operator!= (const AABox &b) const
AABox operator+ (const Vector3 &v) const
AABox operator- (const Vector3 &v) const
void getBounds (AABox &out) const
void getBounds (Sphere &out) const
Static Public Member Functions
static const AABox & maxFinite ()
static const AABox & large ()
static const AABox & inf ()
static const AABox & zero ()
static const AABox & empty ()
Private Attributes
Point3 lo
Point3 hi
Static Private Attributes
static int dummy = 0
Friends
class Intersect
Detailed Description
An axis-aligned box.
Definition at line 32 of file AABox.h.
Constructor & Destructor Documentation
AABox() [1/4]
G3D::AABox::AABox () inline
Creates the empty bounds, i.e., an empty set of points.
Definition at line 48 of file AABox.h.
 : lo(fnan(), fnan(), fnan()), hi(fnan(), fnan(), fnan()) {}
Referenced by inf(), intersect(), large(), maxFinite(), operator*(), and zero().
AABox() [2/4]
G3D::AABox::AABox (const Point3 & v) inline explicit
Constructs a zero-volume AABox at v.
Definition at line 53 of file AABox.h.
{
         lo = hi = v;
     }
References hi, and lo.
AABox() [3/4]
G3D::AABox::AABox (const class Any & a) explicit
Format is one of:
AABox(lowpoint, highpoint)
AABox(point)
AABox::empty()
AABox::inf()
AABox() [4/4]
G3D::AABox::AABox (const Point3 & low, const Point3 & high) inline
Assumes that low is less than or equal to high along each dimension. To have this automatically enforced, use AABox(low.min(high), low.max(high));
Definition at line 75 of file AABox.h.
{
         set(low, high);
     }
References high(), low(), and set().
Member Function Documentation
area()
float G3D::AABox::area () const inline
Definition at line 258 of file AABox.h.
{
         if (isEmpty()) { return 0; }
         Vector3 diag = hi - lo;
         return 2.0f * (diag.x * diag.y + diag.y * diag.z + diag.x * diag.z);
     }
References hi, isEmpty(), lo, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
center()
Point3 G3D::AABox::center () const inline
Returns the centroid of the box (NaN if empty)
Definition at line 163 of file AABox.h.
{
         return (lo + hi) * 0.5;
     }
References hi, and lo.
Referenced by G3D::CollisionDetection::fixedSolidBoxIntersectsFixedTriangle(), getBounds(), and G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle().
contains() [1/2]
bool G3D::AABox::contains (const AABox & other) const inline
less than or equal to containment
Definition at line 238 of file AABox.h.
{
         return
             (other.hi.x <= hi.x) &&
             (other.hi.y <= hi.y) &&
             (other.hi.z <= hi.z) &&
             (other.lo.x >= lo.x) &&
             (other.lo.y >= lo.y) &&
             (other.lo.z >= lo.z);
     }
References hi, lo, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::advance(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), VMAP::ModelInstance::GetLocationInfo(), GameObjectModel::GetLocationInfo(), VMAP::ModelInstance::intersectPoint(), BIH::intersectPoint(), GameObjectModel::IntersectPoint(), VMAP::GroupModel::IsInsideObject(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode().
contains() [2/2]
bool G3D::AABox::contains (const Point3 & point) const inline
Definition at line 248 of file AABox.h.
{
         return
             (point.x >= lo.x) &&
             (point.y >= lo.y) &&
             (point.z >= lo.z) &&
             (point.x <= hi.x) &&
             (point.y <= hi.y) &&
             (point.z <= hi.z);
     }
References hi, lo, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
corner()
Vector3 G3D::AABox::corner (int index) const
Definition at line 361 of file AABox.cpp.
{
     // default constructor inits all components to 0
     Vector3 v;
     switch (index)
     {
     case 0:
         v.x = lo.x;
         v.y = lo.y;
         v.z = hi.z;
         break;
     case 1:
         v.x = hi.x;
         v.y = lo.y;
         v.z = hi.z;
         break;
     case 2:
         v.x = hi.x;
         v.y = hi.y;
         v.z = hi.z;
         break;
     case 3:
         v.x = lo.x;
         v.y = hi.y;
         v.z = hi.z;
         break;
     case 4:
         v.x = lo.x;
         v.y = lo.y;
         v.z = lo.z;
         break;
     case 5:
         v.x = hi.x;
         v.y = lo.y;
         v.z = lo.z;
         break;
     case 6:
         v.x = hi.x;
         v.y = hi.y;
         v.z = lo.z;
         break;
     case 7:
         v.x = lo.x;
         v.y = hi.y;
         v.z = lo.z;
         break;
     default:
         debugAssertM(false, "Invalid corner index");
         break;
     }
     return v;
 }
References debugAssertM, hi, index, lo, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by GameObjectModel::initialize(), and GameObjectModel::UpdatePosition().
culledBy() [1/2]
bool G3D::AABox::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex, const uint32 testMask, uint32 & childMask) const
Conservative culling test for up to 32 planes.
Returns true if there exists a plane[p] for which the entire object is in the negative half space (opposite the plane normal).
testMask and childMask are used for optimizing bounding volume hierarchies. The version of this method that produces childMask is slower than the version without; it should only be used for parent nodes.
Parameters
cullingPlaneIndex The index of the first plane for which the entire object is in the negative half-space. The function exits early when one plane is found. -1 when the function returns false (i.e. when no plane culls the whole object).
testMask If bit p is 0, the bounding volume automatically passes the culling test for plane[p] (i.e. it is known that the volume is entirely within the positive half space). The function must return false if testMask is 0 and test all planes when testMask is -1 (0xFFFFFFFF).
childMask Test mask for the children of this volume.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers().
culledBy() [2/2]
bool G3D::AABox::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex = dummy, const uint32 testMask = 0xFFFFFFFF) const
Conservative culling test that does not produce a mask for children.
deserialize()
void G3D::AABox::deserialize (class BinaryInput & b)
Definition at line 99 of file AABox.cpp.
{
     lo = b.readVector3();
     hi = b.readVector3();
 }
References b, hi, and lo.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::deserializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::deserializeStructure().
empty()
const AABox & G3D::AABox::empty () static
Definition at line 61 of file AABox.cpp.
{
     static const AABox b;
     return b;
 }
References b.
Referenced by G3D::Box::getBounds(), and intersect().
extent() [1/2]
Vector3 G3D::AABox::extent () const inline
Definition at line 181 of file AABox.h.
{
         if (isEmpty()) {
             return Vector3::zero();
         }
         return hi - lo;
     }
References hi, isEmpty(), lo, and G3D::Vector3::zero().
Referenced by getBounds(), and randomSurfacePoint().
extent() [2/2]
float G3D::AABox::extent (int a) const inline
Distance from corner(0) to the next corner along axis a.
Definition at line 172 of file AABox.h.
{
         if (isEmpty()) {
             return 0.0f;
         }
         debugAssert(a < 3);
         return hi[a] - lo[a];
     }
References mpq::a, debugAssert, hi, isEmpty(), and lo.
Referenced by G3D::CollisionDetection::fixedSolidBoxIntersectsFixedTriangle().
getBounds() [1/2]
void G3D::AABox::getBounds (AABox & out) const inline
Definition at line 331 of file AABox.h.
{
         out = *this;
     }
getBounds() [2/2]
void G3D::AABox::getBounds (Sphere & out) const
Definition at line 339 of file AABox.cpp.
{
     s.center = center();
     s.radius = extent().length() / 2;
 }
References center(), G3D::Sphere::center, extent(), G3D::Vector3::length(), and G3D::Sphere::radius.
hashCode()
size_t G3D::AABox::hashCode () const inline
Definition at line 297 of file AABox.h.
{
         return lo.hashCode() + hi.hashCode();
     }
References G3D::Vector3::hashCode(), hi, and lo.
Referenced by HashTrait< G3D::AABox >::hashCode().
high()
const Point3& G3D::AABox::high () const inline
Returns not-a-number if empty
Definition at line 141 of file AABox.h.
{
         return hi;
     }
References hi.
Referenced by AABox(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::balance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator(), BIH::buildHierarchy(), VMAP::MyCollisionDetection::collisionLocationForMovingPointFixedAABox(), G3D::CollisionDetection::collisionLocationForMovingPointFixedAABox(), VMAP::TileAssembler::exportGameobjectModels(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), GameObjectModel::initialize(), BIH::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), VMAP::WModelAreaCallback::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Comparator::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::CollisionDetection::rayAABox(), set(), split(), BIH::subdivide(), GameObjectModel::UpdatePosition(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::verifyNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode(), VMAP::ModelSpawn::writeToFile(), and BIH::writeToFile().
inf()
const AABox & G3D::AABox::inf () static
Definition at line 81 of file AABox.cpp.
{
     static const AABox b = AABox(-Vector3::inf(), Vector3::inf());
     return b;
 }
References AABox(), b, and G3D::Vector3::inf().
intersect()
AABox G3D::AABox::intersect (const AABox & other) const inline
Return the intersection of the two boxes
Definition at line 282 of file AABox.h.
{
         if (isEmpty() || other.isEmpty()) {
             return empty();
         }
         const Point3& H = hi.min(other.hi);
         const Point3& L = lo.max(other.lo).min(H);
         if (H.x < L.x && H.y < L.y && H.z < L.z) {
             return empty();
         } else {
             return AABox(L, H);
         }
     }
References AABox(), empty(), H, hi, isEmpty(), lo, G3D::Vector3::max(), G3D::Vector3::min(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle().
intersects() [1/2]
bool G3D::AABox::intersects (const AABox & other) const
Returns true if there is any overlap
Definition at line 175 of file AABox.cpp.
{
     // Must be overlap along all three axes.
     // Try to find a separating axis.
     for (int a = 0; a < 3; ++a) {
         //     |--------|
         // |------|
         if ((lo[a] > other.hi[a]) ||
             (hi[a] < other.lo[a])) {
             return false;
         }
     }
     return true;
 }
References mpq::a, hi, and lo.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++().
intersects() [2/2]
bool G3D::AABox::intersects (const Sphere & other) const
Returns true if there is any overlap. [Jim] Arvo's algorithm from Graphics Gems II
Definition at line 345 of file AABox.cpp.
{
     double d = 0;
     //find the square of the distance
     //from the sphere to the box
     for (int i = 0; i < 3; ++i) {
         if (sphere.center[i] < lo[i]) {
             d += square(sphere.center[i] - lo[i]);
         } else if (sphere.center[i] > hi[i]) {
             d += square(sphere.center[i] - hi[i]);
         }
     }
     return d <= square(sphere.radius);
 }
References G3D::Sphere::center, mpq::d, hi, lo, G3D::Sphere::radius, and G3D::square().
isEmpty()
bool G3D::AABox::isEmpty () const inline
Definition at line 67 of file AABox.h.
{
         return lo.isNaN();
     }
References G3D::Vector3::isNaN(), and lo.
Referenced by area(), extent(), intersect(), isFinite(), merge(), operator!=(), operator==(), toAny(), and volume().
isFinite()
bool G3D::AABox::isFinite () const inline
Definition at line 131 of file AABox.h.
{
         return isEmpty() || (lo.isFinite() && hi.isFinite());
     }
References hi, isEmpty(), G3D::Vector3::isFinite(), and lo.
Referenced by toAny().
large()
const AABox & G3D::AABox::large () static
A large finite box. This is smaller than FLT_MAX because it leaves room to add boxes together.
Definition at line 74 of file AABox.cpp.
{
     static const AABox b = AABox(Vector3::minFinite() * 0.5f,
                                  Vector3::maxFinite() * 0.5f);
     return b;
 }
References AABox(), b, G3D::Vector3::maxFinite(), and G3D::Vector3::minFinite().
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::balance(), and G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle().
low()
const Point3& G3D::AABox::low () const inline
Returns not-a-number if empty
Definition at line 136 of file AABox.h.
{
         return lo;
     }
References lo.
Referenced by AABox(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::balance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::BoxIterator(), BIH::buildHierarchy(), VMAP::MyCollisionDetection::collisionLocationForMovingPointFixedAABox(), G3D::CollisionDetection::collisionLocationForMovingPointFixedAABox(), VMAP::TileAssembler::exportGameobjectModels(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::findDeepestContainingNode(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), GameObjectModel::initialize(), BIH::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), VMAP::WModelAreaCallback::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Comparator::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::BoxIntersectionIterator::operator++(), G3D::CollisionDetection::rayAABox(), set(), split(), BIH::subdivide(), GameObjectModel::UpdatePosition(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::verifyNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode(), VMAP::ModelSpawn::writeToFile(), and BIH::writeToFile().
maxFinite()
const AABox & G3D::AABox::maxFinite () static
The largest possible finite box.
Definition at line 67 of file AABox.cpp.
{
     static const AABox b = AABox(Vector3::minFinite(),
                                  Vector3::maxFinite());
     return b;
 }
References AABox(), b, G3D::Vector3::maxFinite(), and G3D::Vector3::minFinite().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance().
merge() [1/3]
void G3D::AABox::merge (const AABox & a) inline
Grows to include the bounds of a
Definition at line 106 of file AABox.h.
{
         if (isEmpty()) {
             lo = a.lo;
             hi = a.hi;
         } else if (! a.isEmpty()) {
             lo = lo.min(a.lo);
             hi = hi.max(a.hi);
         }
     }
References mpq::a, hi, isEmpty(), lo, G3D::Vector3::max(), and G3D::Vector3::min().
Referenced by BIH::build(), VMAP::TileAssembler::calculateTransformedBound(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::computeBounds(), VMAP::TileAssembler::exportGameobjectModels(), G3D::Box::getBounds(), GameObjectModel::initialize(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and GameObjectModel::UpdatePosition().
merge() [2/3]
void G3D::AABox::merge (const class Box & b)
merge() [3/3]
void G3D::AABox::merge (const Point3 & a) inline
Definition at line 116 of file AABox.h.
{
         if (isEmpty()) {
             lo = hi = a;
         } else {
             lo = lo.min(a);
             hi = hi.max(a);
         }
     }
References mpq::a, hi, isEmpty(), lo, G3D::Vector3::max(), and G3D::Vector3::min().
operator!=()
bool G3D::AABox::operator!= (const AABox & b) const inline
Definition at line 309 of file AABox.h.
{
         if (isEmpty()) {
             return b.isEmpty();
         } else {
             return !((lo == b.lo) && (hi == b.hi));
         }
     }
References b, hi, isEmpty(), and lo.
operator*()
AABox G3D::AABox::operator* (float f) const inline
Definition at line 79 of file AABox.h.
{
         if (f < 0) {
             return AABox(hi * f, lo * f);
         } else {
             return AABox(lo * f, hi * f);
         }
     }
References AABox(), f(), hi, and lo.
operator+()
AABox G3D::AABox::operator+ (const Vector3 & v) const inline
Definition at line 317 of file AABox.h.
{
         AABox out;
         out.lo = lo + v;
         out.hi = hi + v;
         return out;
     }
References hi, and lo.
operator-()
AABox G3D::AABox::operator- (const Vector3 & v) const inline
Definition at line 324 of file AABox.h.
{
         AABox out;
         out.lo = lo - v;
         out.hi = hi - v;
         return out;
     }
References hi, and lo.
operator/()
AABox G3D::AABox::operator/ (float f) const inline
Definition at line 87 of file AABox.h.
{
         return *this * (1.0f / f);
     }
References f().
operator==()
bool G3D::AABox::operator== (const AABox & b) const inline
Definition at line 301 of file AABox.h.
{
         if (isEmpty() && b.isEmpty()) {
             return true;
         } else {
             return (lo == b.lo) && (hi == b.hi);
         }
     }
References b, hi, isEmpty(), and lo.
randomInteriorPoint()
Vector3 G3D::AABox::randomInteriorPoint () const
Definition at line 167 of file AABox.cpp.
{
     return Vector3(
         (float)uniformRandom(lo.x, hi.x),
         (float)uniformRandom(lo.y, hi.y),
         (float)uniformRandom(lo.z, hi.z));
 }
References hi, lo, G3D::uniformRandom(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
randomSurfacePoint()
Vector3 G3D::AABox::randomSurfacePoint () const
Definition at line 129 of file AABox.cpp.
{
     Vector3 extent = hi - lo;
     float aXY = extent.x * extent.y;
     float aYZ = extent.y * extent.z;
     float aZX = extent.z * extent.x;
     float r = (float)uniformRandom(0.0f, aXY + aYZ + aZX);
     // Choose evenly between positive and negative face planes
     float d = ((float)uniformRandom(0, 1) < 0.5f) ? 0.0f : 1.0f;
     // The probability of choosing a given face is proportional to
     // its area.
     if (r < aXY) {
         return
             lo +
             Vector3(
                 (float)uniformRandom(0.0f, extent.x),
                 (float)uniformRandom(0.0f, extent.y),
                 d * extent.z);
     } else if (r < aYZ) {
         return
             lo +
             Vector3(
                 d * extent.x,
                 (float)uniformRandom(0, extent.y),
                 (float)uniformRandom(0, extent.z));
     } else {
         return
             lo +
             Vector3(
                 (float)uniformRandom(0, extent.x),
                 d * extent.y,
                 (float)uniformRandom(0, extent.z));
     }
 }
References mpq::d, extent(), hi, lo, G3D::uniformRandom(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
serialize()
void G3D::AABox::serialize (class BinaryOutput & b) const
Definition at line 93 of file AABox.cpp.
{
     b.writeVector3(lo);
     b.writeVector3(hi);
 }
References b, hi, and lo.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::serializeStructure(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::serializeStructure().
set()
void G3D::AABox::set (const Point3 & low, const Point3 & high) inline
Assumes that low is less than or equal to high along each dimension.
Definition at line 93 of file AABox.h.
{
         debugAssert(
             (low.x <= high.x) &&
             (low.y <= high.y) &&
             (low.z <= high.z));
         debugAssert(! low.isNaN() && ! high.isNaN());
         lo = low;
         hi = high;
     }
References debugAssert, hi, high(), G3D::Vector3::isNaN(), lo, low(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by AABox(), and VMAP::GroupModel_Raw::Read().
split()
void G3D::AABox::split (const Vector3::Axis & axis, float location, AABox & low, AABox & high) const
Splits the box into two AABoxes along the specified axis. low contains the part that was closer to negative infinity along axis, high contains the other part. Either may have zero volume.
Definition at line 112 of file AABox.cpp.
{
     // Low, medium, and high along the chosen axis
     float L = G3D::min(location, lo[axis]);
     float M = G3D::min(G3D::max(location, lo[axis]), hi[axis]);
     float H = G3D::max(location, hi[axis]);
     // Copy over this box.
     high = low = *this;
     // Now move the split points along the special axis
     low.lo[axis] = L;
     low.hi[axis] = M;
     high.lo[axis] = M;
     high.hi[axis] = H;
 }
References H, hi, high(), lo, low(), G3D::max(), and G3D::min().
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::assignSplitBounds().
toAny()
Any G3D::AABox::toAny () const
Definition at line 44 of file AABox.cpp.
{
     if (isEmpty()) {
         return Any(Any::ARRAY, "AABox::empty");
     } else if (! isFinite()) {
         return Any(Any::ARRAY, "AABox::inf");
     } else {
         Any a(Any::ARRAY, "AABox");
         if (lo == hi) {
             a.append(lo);
         } else {
             a.append(lo, hi);
         }
         return a;
     }
 }
References mpq::a, G3D::Any::ARRAY, hi, isEmpty(), isFinite(), and lo.
volume()
float G3D::AABox::volume () const inline
Definition at line 264 of file AABox.h.
{
         if (isEmpty()) { return 0; }
         Vector3 diag = hi - lo;
         return diag.x * diag.y * diag.z;
     }
References hi, isEmpty(), lo, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
zero()
const AABox & G3D::AABox::zero () static
Definition at line 87 of file AABox.cpp.
{
     static const AABox b = AABox(Vector3::zero(), Vector3::zero());
     return b;
 }
References AABox(), b, and G3D::Vector3::zero().
Referenced by GameObjectModel::initialize(), and GameObjectModel::UpdatePosition().
Friends And Related Function Documentation
Intersect
friend class Intersect friend
Definition at line 34 of file AABox.h.
Member Data Documentation
dummy
int G3D::AABox::dummy = 0 static private
Optional argument placeholder
Definition at line 37 of file AABox.h.
hi
Point3 G3D::AABox::hi private
NaN if empty
Definition at line 43 of file AABox.h.
Referenced by AABox(), area(), center(), contains(), corner(), deserialize(), extent(), hashCode(), high(), intersect(), intersects(), isFinite(), merge(), operator!=(), operator*(), operator+(), operator-(), operator==(), randomInteriorPoint(), randomSurfacePoint(), G3D::Intersect::rayAABox(), serialize(), set(), split(), toAny(), and volume().
lo
Point3 G3D::AABox::lo private
NaN if empty
Definition at line 40 of file AABox.h.
Referenced by AABox(), area(), center(), contains(), corner(), deserialize(), extent(), hashCode(), intersect(), intersects(), isEmpty(), isFinite(), low(), merge(), operator!=(), operator*(), operator+(), operator-(), operator==(), randomInteriorPoint(), randomSurfacePoint(), G3D::Intersect::rayAABox(), serialize(), set(), split(), toAny(), and volume().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/AABox.h
deps/g3dlite/source/AABox.cpp