Azerotcore-wotlk: LootValidatorRefMgr Class Reference
LootValidatorRefMgr Class Reference
#include <LootMgr.h>
Public Types
typedef LinkedListHead::Iterator< LootValidatorRef > iterator
Public Types inherited from RefMgr< Loot, LootValidatorRef >
typedef LinkedListHead::Iterator< Reference< Loot, LootValidatorRef > > iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
LootValidatorRef * getFirst ()
LootValidatorRef * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefMgr< Loot, LootValidatorRef >
RefMgr ()=default
virtual ~RefMgr ()
Reference< Loot, LootValidatorRef > * getFirst ()
Reference< Loot, LootValidatorRef > const * getFirst () const
Reference< Loot, LootValidatorRef > * getLast ()
Reference< Loot, LootValidatorRef > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
Definition at line 292 of file LootMgr.h.
Member Typedef Documentation
iterator
typedef LinkedListHead::Iterator< LootValidatorRef > LootValidatorRefMgr::iterator
Definition at line 295 of file LootMgr.h.
Member Function Documentation
begin()
iterator LootValidatorRefMgr::begin () inline
Definition at line 300 of file LootMgr.h.
 { return iterator(getFirst()); }
References getFirst().
end()
iterator LootValidatorRefMgr::end () inline
Definition at line 301 of file LootMgr.h.
 { return iterator(nullptr); }
getFirst()
LootValidatorRef* LootValidatorRefMgr::getFirst () inline
Definition at line 297 of file LootMgr.h.
 { return (LootValidatorRef*)RefMgr<Loot, LootValidatorRef>::getFirst(); }
References RefMgr< TO, FROM >::getFirst().
Referenced by begin().
getLast()
LootValidatorRef* LootValidatorRefMgr::getLast () inline
Definition at line 298 of file LootMgr.h.
 { return (LootValidatorRef*)RefMgr<Loot, LootValidatorRef>::getLast(); }
References RefMgr< TO, FROM >::getLast().
Referenced by rbegin().
rbegin()
iterator LootValidatorRefMgr::rbegin () inline
Definition at line 302 of file LootMgr.h.
 { return iterator(getLast()); }
References getLast().
rend()
iterator LootValidatorRefMgr::rend () inline
Definition at line 303 of file LootMgr.h.
 { return iterator(nullptr); }
The documentation for this class was generated from the following file:
src/server/game/Loot/LootMgr.h