Azerotcore-wotlk: G3D::NetListener Class Reference
G3D::NetListener Class Reference
#include <NetworkDevice.h>
Public Member Functions
~NetListener ()
ReliableConduitRef waitForConnection ()
bool clientWaiting () const
bool ok () const
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static NetListenerRef create (const uint16 port)
Private Member Functions
NetListener (uint16 port)
Private Attributes
SOCKET sock
Friends
class NetworkDevice
Detailed Description
Runs on the server listening for clients trying to make reliable connections.
Deprecated:
Definition at line 547 of file NetworkDevice.h.
Constructor & Destructor Documentation
NetListener()
G3D::NetListener::NetListener (uint16 port) private
Port is in host byte order.
Definition at line 1151 of file NetworkDevice.cpp.
{
     NetworkDevice* nd = NetworkDevice::instance();
     // Start the listener socket
     Log::common()->print("Creating a listener            ");
     sock = socket(AF_INET, SOCK_STREAM, IPPROTO_IP);
     if (sock == SOCKET_ERROR) {
         Log::common()->printf("FAIL");
         Log::common()->println(socketErrorCode());
         return;
     }
     Log::common()->println("Ok");
     const int T = true;
     // Set reuse address so that a new server can start up soon after
     // an old one has closed.
     if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
                    (const char*)&T, sizeof(T)) == SOCKET_ERROR) {
         Log::common()->println("WARNING: Setting socket reuseaddr failed.");
         Log::common()->println(socketErrorCode());
     } else {
         Log::common()->println("Set socket option reuseaddr.");
     }
     if (! nd->bind(sock, NetAddress(0, port))) {
         Log::common()->printf("Unable to bind!\n");
         nd->closesocket(sock);
         sock = (SOCKET)SOCKET_ERROR;
         return;
     }
     Log::common()->printf("Listening on port %5d        ", port);
     // listen is supposed to return 0 when there is no error.
     // The 2nd argument is the number of connections to allow pending
     // at any time.
     int L = listen(sock, 100);
     if (L == SOCKET_ERROR) {
         Log::common()->println("FAIL");
         Log::common()->println(socketErrorCode());
         nd->closesocket(sock);
         sock = (SOCKET)SOCKET_ERROR;
         return;
     }
     Log::common()->println("Ok");
     Log::common()->printf("Now listening on socket %d.\n\n", sock);
 }
References G3D::NetworkDevice::bind(), G3D::NetworkDevice::closesocket(), G3D::Log::common(), G3D::NetworkDevice::instance(), G3D::Log::print(), G3D::Log::printf(), G3D::Log::println(), sock, SOCKET, SOCKET_ERROR, and socketErrorCode().
Referenced by create().
~NetListener()
G3D::NetListener::~NetListener ()
Definition at line 1204 of file NetworkDevice.cpp.
{
     NetworkDevice* nd = NetworkDevice::instance();
     nd->closesocket(sock);
 }
References G3D::NetworkDevice::closesocket(), G3D::NetworkDevice::instance(), and sock.
Member Function Documentation
clientWaiting()
bool G3D::NetListener::clientWaiting () const
True if a client is waiting (i.e. waitForConnection will return immediately).
Definition at line 1248 of file NetworkDevice.cpp.
{
     return readWaiting(sock);
 }
References G3D::readWaiting(), and sock.
create()
NetListenerRef G3D::NetListener::create (const uint16 port) static
Definition at line 1146 of file NetworkDevice.cpp.
{
     return NetListenerRef(new NetListener(port));
 }
References NetListener().
ok()
bool G3D::NetListener::ok () const
Definition at line 1243 of file NetworkDevice.cpp.
{
     return (sock != 0) && (sock != SOCKET_ERROR);
 }
References sock, and SOCKET_ERROR.
waitForConnection()
ReliableConduitRef G3D::NetListener::waitForConnection ()
Block until a connection is received. Returns NULL if something went wrong.
Definition at line 1210 of file NetworkDevice.cpp.
{
     NetworkDevice* nd = NetworkDevice::instance();
     // The address of the connecting host
     SOCKADDR_IN    remote_addr;
     int iAddrLen = sizeof(remote_addr);
     Log::common()->println("Blocking in NetListener::waitForConnection().");
     SOCKET sClient = accept(sock, (struct sockaddr*) &remote_addr,
                             (socklen_t*)&iAddrLen);
     if (sClient == SOCKET_ERROR) {
         Log::common()->println("Error in NetListener::acceptConnection.");
         Log::common()->println(socketErrorCode());
         nd->closesocket(sock);
         return ReliableConduitRef();
     }
     Log::common()->printf("%s connected, transferred to socket %d.\n",
                          inet_ntoa(remote_addr.sin_addr), sClient);
     #ifndef G3D_WINDOWS
     return ReliableConduitRef(new ReliableConduit(sClient,
                      NetAddress(htonl(remote_addr.sin_addr.s_addr),
                                 ntohs(remote_addr.sin_port))));
     #else
     return ReliableConduitRef(ReliableConduitRef(new ReliableConduit(sClient,
                     NetAddress(ntohl(remote_addr.sin_addr.S_un.S_addr),
                                ntohs(remote_addr.sin_port)))));
     #endif
 }
References G3D::NetworkDevice::closesocket(), G3D::Log::common(), G3D::NetworkDevice::instance(), G3D::Log::printf(), G3D::Log::println(), sock, SOCKADDR_IN, SOCKET, SOCKET_ERROR, and socketErrorCode().
Friends And Related Function Documentation
NetworkDevice
friend class NetworkDevice friend
Definition at line 550 of file NetworkDevice.h.
Member Data Documentation
sock
SOCKET G3D::NetListener::sock private
Definition at line 552 of file NetworkDevice.h.
Referenced by clientWaiting(), NetListener(), ok(), waitForConnection(), and ~NetListener().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/NetworkDevice.h
deps/g3dlite/source/NetworkDevice.cpp