Azerotcore-wotlk: npc_a_special_surprise::npc_a_special_surpriseAI Struct Reference
npc_a_special_surprise::npc_a_special_surpriseAI Struct Reference
Public Member Functions
npc_a_special_surpriseAI (Creature *creature)
void Reset () override
bool MeetQuestCondition (Player *player)
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 ExecuteSpeech_Timer
uint32 ExecuteSpeech_Counter
ObjectGuid PlayerGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 651 of file chapter2.cpp.
Constructor & Destructor Documentation
npc_a_special_surpriseAI()
npc_a_special_surprise::npc_a_special_surpriseAI::npc_a_special_surpriseAI (Creature * creature) inline
Definition at line 653 of file chapter2.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
MeetQuestCondition()
bool npc_a_special_surprise::npc_a_special_surpriseAI::MeetQuestCondition (Player * player) inline
Definition at line 668 of file chapter2.cpp.
         {
             switch (me->GetEntry())
             {
                 case 29061:                                     // Ellen Stanbridge
                     if (player->GetQuestStatus(12742) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29072:                                     // Kug Ironjaw
                     if (player->GetQuestStatus(12748) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29067:                                     // Donovan Pulfrost
                     if (player->GetQuestStatus(12744) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29065:                                     // Yazmina Oakenthorn
                     if (player->GetQuestStatus(12743) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29071:                                     // Antoine Brack
                     if (player->GetQuestStatus(12750) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29032:                                     // Malar Bravehorn
                     if (player->GetQuestStatus(12739) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29068:                                     // Goby Blastenheimer
                     if (player->GetQuestStatus(12745) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29073:                                     // Iggy Darktusk
                     if (player->GetQuestStatus(12749) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29074:                                     // Lady Eonys
                     if (player->GetQuestStatus(12747) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
                 case 29070:                                     // Valok the Righteous
                     if (player->GetQuestStatus(12746) == QUEST_STATUS_INCOMPLETE)
                         return true;
                     break;
             }
             return false;
         }
References Object::GetEntry(), Player::GetQuestStatus(), ScriptedAI::me, and QUEST_STATUS_INCOMPLETE.
Referenced by MoveInLineOfSight().
MoveInLineOfSight()
void npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 717 of file chapter2.cpp.
         {
             if (PlayerGUID || who->GetTypeId() != TYPEID_PLAYER || !who->IsWithinDist(me, INTERACTION_DISTANCE))
                 return;
             if (MeetQuestCondition(who->ToPlayer()))
                 PlayerGUID = who->GetGUID();
         }
References Object::GetGUID(), Object::GetTypeId(), INTERACTION_DISTANCE, WorldObject::IsWithinDist(), ScriptedAI::me, MeetQuestCondition(), PlayerGUID, Object::ToPlayer(), and TYPEID_PLAYER.
Reset()
void npc_a_special_surprise::npc_a_special_surpriseAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 659 of file chapter2.cpp.
         {
             ExecuteSpeech_Timer = 0;
             ExecuteSpeech_Counter = 0;
             PlayerGUID.Clear();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
         }
References ObjectGuid::Clear(), ExecuteSpeech_Counter, ExecuteSpeech_Timer, ScriptedAI::me, PlayerGUID, Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Referenced by UpdateAI().
UpdateAI()
void npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI (uint32 diff) inline override virtual
Todo:
simplify text's selection
Reimplemented from ScriptedAI.
Definition at line 727 of file chapter2.cpp.
         {
             if (PlayerGUID && !me->GetVictim() && me->IsAlive())
             {
                 if (ExecuteSpeech_Timer <= diff)
                 {
                     Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
                     if (!player)
                     {
                         Reset();
                         return;
                     }
                     switch (player->getRace())
                     {
                         case RACE_HUMAN:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_5, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_1, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_5, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_7, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_6, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_ORC:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_6, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_1, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_7, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_8, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_8, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_DWARF:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_2, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_2, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_3, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_2, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_5, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_2, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_3, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_NIGHTELF:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_5, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_1, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_6, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_2, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_7, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_UNDEAD_PLAYER:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_3, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_4, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_3, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_1, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_3, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_4, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_TAUREN:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_1, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_5, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_8, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_9, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_9, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_GNOME:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_4, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_1, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_4, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_6, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_5, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_TROLL:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_3, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_7, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_2, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_6, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_9, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_10, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_4, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_10, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_BLOODELF:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_1, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_1, player);
                                     break;
                                 //case 5: //unknown
                                 case 6:
                                     Talk(SAY_EXEC_THINK_3, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_1, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                         case RACE_DRAENEI:
                             switch (ExecuteSpeech_Counter)
{
                                 case 0:
                                     Talk(SAY_EXEC_START_1, player);
                                     break;
                                 case 1:
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     break;
                                 case 2:
                                     Talk(SAY_EXEC_PROG_1, player);
                                     break;
                                 case 3:
                                     Talk(SAY_EXEC_NAME_1, player);
                                     break;
                                 case 4:
                                     Talk(SAY_EXEC_RECOG_2, player);
                                     break;
                                 case 5:
                                     Talk(SAY_EXEC_NOREM_1, player);
                                     break;
                                 case 6:
                                     Talk(SAY_EXEC_THINK_4, player);
                                     break;
                                 case 7:
                                     Talk(SAY_EXEC_LISTEN_1, player);
                                     break;
                                 case 8:
                                     if (Creature* Plaguefist = GetClosestCreatureWithEntry(me, NPC_PLAGUEFIST, 85.0f))
                                         Plaguefist->AI()->Talk(SAY_PLAGUEFIST, player);
                                     break;
                                 case 9:
                                     Talk(SAY_EXEC_TIME_2, player);
                                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     break;
                                 case 10:
                                     Talk(SAY_EXEC_WAITING, player);
                                     break;
                                 case 11:
                                     Talk(EMOTE_DIES);
                                     me->setDeathState(JUST_DIED);
                                     me->SetHealth(0);
                                     return;
                             }
                             break;
                     }
                     if (ExecuteSpeech_Counter >= 9)
                         ExecuteSpeech_Timer = 15000;
                     else
                         ExecuteSpeech_Timer = 7000;
                     ++ExecuteSpeech_Counter;
                 }
                 else
                     ExecuteSpeech_Timer -= diff;
             }
         }
References EMOTE_DIES, ExecuteSpeech_Counter, ExecuteSpeech_Timer, GetClosestCreatureWithEntry(), ObjectAccessor::GetPlayer(), Unit::getRace(), Unit::GetVictim(), Unit::IsAlive(), JUST_DIED, ScriptedAI::me, NPC_PLAGUEFIST, PlayerGUID, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD_PLAYER, Object::RemoveFlag(), Reset(), SAY_EXEC_LISTEN_1, SAY_EXEC_LISTEN_2, SAY_EXEC_LISTEN_3, SAY_EXEC_LISTEN_4, SAY_EXEC_NAME_1, SAY_EXEC_NAME_2, SAY_EXEC_NOREM_1, SAY_EXEC_NOREM_2, SAY_EXEC_NOREM_3, SAY_EXEC_NOREM_4, SAY_EXEC_NOREM_5, SAY_EXEC_NOREM_6, SAY_EXEC_NOREM_7, SAY_EXEC_NOREM_8, SAY_EXEC_NOREM_9, SAY_EXEC_PROG_1, SAY_EXEC_PROG_2, SAY_EXEC_PROG_3, SAY_EXEC_PROG_4, SAY_EXEC_PROG_5, SAY_EXEC_PROG_6, SAY_EXEC_PROG_7, SAY_EXEC_RECOG_1, SAY_EXEC_RECOG_2, SAY_EXEC_RECOG_3, SAY_EXEC_RECOG_4, SAY_EXEC_RECOG_5, SAY_EXEC_RECOG_6, SAY_EXEC_START_1, SAY_EXEC_START_2, SAY_EXEC_START_3, SAY_EXEC_THINK_1, SAY_EXEC_THINK_10, SAY_EXEC_THINK_2, SAY_EXEC_THINK_3, SAY_EXEC_THINK_4, SAY_EXEC_THINK_5, SAY_EXEC_THINK_6, SAY_EXEC_THINK_7, SAY_EXEC_THINK_8, SAY_EXEC_THINK_9, SAY_EXEC_TIME_1, SAY_EXEC_TIME_10, SAY_EXEC_TIME_2, SAY_EXEC_TIME_3, SAY_EXEC_TIME_4, SAY_EXEC_TIME_5, SAY_EXEC_TIME_6, SAY_EXEC_TIME_7, SAY_EXEC_TIME_8, SAY_EXEC_TIME_9, SAY_EXEC_WAITING, SAY_PLAGUEFIST, Creature::setDeathState(), Unit::SetHealth(), Unit::SetStandState(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STAND_STATE_KNEEL, and UNIT_STAND_STATE_STAND.
Member Data Documentation
ExecuteSpeech_Counter
uint32 npc_a_special_surprise::npc_a_special_surpriseAI::ExecuteSpeech_Counter
Definition at line 656 of file chapter2.cpp.
Referenced by Reset(), and UpdateAI().
ExecuteSpeech_Timer
uint32 npc_a_special_surprise::npc_a_special_surpriseAI::ExecuteSpeech_Timer
Definition at line 655 of file chapter2.cpp.
Referenced by Reset(), and UpdateAI().
PlayerGUID
ObjectGuid npc_a_special_surprise::npc_a_special_surpriseAI::PlayerGUID
Definition at line 657 of file chapter2.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp