Azerotcore-wotlk: instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript Struct Reference
instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript Struct Reference
Public Member Functions
instance_ruins_of_ahnqiraj_InstanceMapScript (Map *map)
void OnCreatureCreate (Creature *creature) override
bool SetBossState (uint32 bossId, EncounterState state) override
void SetGuidData (uint32 type, ObjectGuid data) override
ObjectGuid GetGuidData (uint32 type) const override
std::string GetSaveData () override
void Load (char const *data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _kurinaxxGUID
ObjectGuid _rajaxxGUID
ObjectGuid _moamGUID
ObjectGuid _buruGUID
ObjectGuid _ayamissGUID
ObjectGuid _ossirianGUID
ObjectGuid _paralyzedGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 27 of file instance_ruins_of_ahnqiraj.cpp.
Constructor & Destructor Documentation
instance_ruins_of_ahnqiraj_InstanceMapScript()
instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::instance_ruins_of_ahnqiraj_InstanceMapScript (Map * map) inline
Definition at line 29 of file instance_ruins_of_ahnqiraj.cpp.
                                                                : InstanceScript(map)
         {
             SetBossNumber(NUM_ENCOUNTER);
         }
References NUM_ENCOUNTER, and InstanceScript::SetBossNumber().
Member Function Documentation
GetGuidData()
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 73 of file instance_ruins_of_ahnqiraj.cpp.
         {
             switch (type)
             {
                 case DATA_KURINNAXX:
                     return _kurinaxxGUID;
                 case DATA_RAJAXX:
                     return _rajaxxGUID;
                 case DATA_MOAM:
                     return _moamGUID;
                 case DATA_BURU:
                     return _buruGUID;
                 case DATA_AYAMISS:
                     return _ayamissGUID;
                 case DATA_OSSIRIAN:
                     return _ossirianGUID;
                 case DATA_PARALYZED:
                     return _paralyzedGUID;
             }
             return ObjectGuid::Empty;
         }
References _ayamissGUID, _buruGUID, _kurinaxxGUID, _moamGUID, _ossirianGUID, _paralyzedGUID, _rajaxxGUID, DATA_AYAMISS, DATA_BURU, DATA_KURINNAXX, DATA_MOAM, DATA_OSSIRIAN, DATA_PARALYZED, DATA_RAJAXX, and ObjectGuid::Empty.
GetSaveData()
std::string instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 96 of file instance_ruins_of_ahnqiraj.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "R A" << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::Load (char const * data) inline override virtual
Reimplemented from InstanceScript.
Definition at line 107 of file instance_ruins_of_ahnqiraj.cpp.
         {
             if (!data)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(data);
             char dataHead1, dataHead2;
             std::istringstream loadStream(data);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'R' && dataHead2 == 'A')
             {
                 for (uint8 i = 0; i < NUM_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > TO_BE_DECIDED)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, NOT_STARTED, NUM_ENCOUNTER, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and TO_BE_DECIDED.
OnCreatureCreate()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 34 of file instance_ruins_of_ahnqiraj.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_KURINAXX:
                     _kurinaxxGUID = creature->GetGUID();
                     break;
                 case NPC_RAJAXX:
                     _rajaxxGUID = creature->GetGUID();
                     break;
                 case NPC_MOAM:
                     _moamGUID = creature->GetGUID();
                     break;
                 case NPC_BURU:
                     _buruGUID = creature->GetGUID();
                     break;
                 case NPC_AYAMISS:
                     _ayamissGUID = creature->GetGUID();
                     break;
                 case NPC_OSSIRIAN:
                     _ossirianGUID = creature->GetGUID();
                     break;
             }
         }
References _ayamissGUID, _buruGUID, _kurinaxxGUID, _moamGUID, _ossirianGUID, _rajaxxGUID, Object::GetEntry(), Object::GetGUID(), NPC_AYAMISS, NPC_BURU, NPC_KURINAXX, NPC_MOAM, NPC_OSSIRIAN, and NPC_RAJAXX.
SetBossState()
bool instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::SetBossState (uint32 bossId, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 59 of file instance_ruins_of_ahnqiraj.cpp.
         {
             if (!InstanceScript::SetBossState(bossId, state))
                 return false;
             return true;
         }
References InstanceScript::SetBossState().
Referenced by Load().
SetGuidData()
void instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 67 of file instance_ruins_of_ahnqiraj.cpp.
         {
             if (type == DATA_PARALYZED)
                 _paralyzedGUID = data;
         }
References _paralyzedGUID, and DATA_PARALYZED.
Member Data Documentation
_ayamissGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_ayamissGUID private
Definition at line 144 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_buruGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_buruGUID private
Definition at line 143 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_kurinaxxGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_kurinaxxGUID private
Definition at line 140 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_moamGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_moamGUID private
Definition at line 142 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_ossirianGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_ossirianGUID private
Definition at line 145 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_paralyzedGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_paralyzedGUID private
Definition at line 146 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and SetGuidData().
_rajaxxGUID
ObjectGuid instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::_rajaxxGUID private
Definition at line 141 of file instance_ruins_of_ahnqiraj.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp