Azerotcore-wotlk: deps/mysqllite/mysys/list.c File Reference
list.c File Reference
#include "mysys_priv.h"
#include <my_list.h>
Functions
LIST * list_add (LIST *root, LIST *element)
LIST * list_delete (LIST *root, LIST *element)
void list_free (LIST *root, uint free_data)
LIST * list_cons (void *data, LIST *list)
LIST * list_reverse (LIST *root)
uint list_length (LIST *list)
int list_walk (LIST *list, list_walk_action action, uchar *argument)
Function Documentation
list_add()
LIST* list_add (LIST * root, LIST * element)
Definition at line 27 of file list.c.
 {
   DBUG_ENTER("list_add");
   DBUG_PRINT("enter",("root: 0x%lx  element: 0x%lx", (long) root, (long) element));
   if (root)
   {
     if (root->prev)         /* If add in mid of list */
       root->prev->next= element;
     element->prev=root->prev;
     root->prev=element;
   }
   else
     element->prev=0;
   element->next=root;
   DBUG_RETURN(element);         /* New root */
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_list::next, and st_list::prev.
Referenced by list_cons(), mysql_prune_stmt_list(), mysql_stmt_init(), and thr_lock_init().
list_cons()
LIST* list_cons (void * data, LIST * list)
Definition at line 71 of file list.c.
 {
   LIST *new_charset=(LIST*) my_malloc(sizeof(LIST),MYF(MY_FAE));
   if (!new_charset)
     return 0;
   new_charset->data=data;
   return list_add(list,new_charset);
 }
References st_list::data, list(), list_add(), MY_FAE, my_malloc(), and MYF.
list_delete()
LIST* list_delete (LIST * root, LIST * element)
Definition at line 45 of file list.c.
 {
   if (element->prev)
     element->prev->next=element->next;
   else
     root=element->next;
   if (element->next)
     element->next->prev=element->prev;
   return root;
 }
References st_list::next, and st_list::prev.
Referenced by mysql_stmt_close(), and thr_lock_delete().
list_free()
void list_free (LIST * root, uint free_data)
Definition at line 57 of file list.c.
 {
   LIST *next;
   while (root)
   {
     next=root->next;
     if (free_data)
       my_free(root->data);
     my_free(root);
     root=next;
   }
 }
References st_list::data, my_free(), st_list::next, and next().
list_length()
uint list_length (LIST * list)
Definition at line 96 of file list.c.
 {
   uint count;
   for (count=0 ; list ; list=list->next, count++) ;
   return count;
 }
References count(), and list().
list_reverse()
LIST* list_reverse (LIST * root)
Definition at line 81 of file list.c.
 {
   LIST *last;
   last=root;
   while (root)
   {
     last=root;
     root=root->next;
     last->next=last->prev;
     last->prev=root;
   }
   return last;
 }
References st_list::next, and st_list::prev.
list_walk()
int list_walk (LIST * list, list_walk_action action, uchar * argument)
Definition at line 104 of file list.c.
 {
   int error=0;
   while (list)
   {
     if ((error = (*action)(list->data,argument)))
       return error;
     list=list_rest(list);
   }
   return 0;
 }
References error(), list(), and list_rest.