Azerotcore-wotlk: deps/mysqllite/mysys/mf_path.c File Reference
mf_path.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Macros
#define PATH_SEP ':'
Functions
static char * find_file_in_path (char *to, const char *name)
char * my_path (char *to, const char *progname, const char *own_pathname_part)
Macro Definition Documentation
PATH_SEP
#define PATH_SEP ':'
Definition at line 82 of file mf_path.c.
Function Documentation
find_file_in_path()
static char * find_file_in_path (char * to, const char * name) static
Definition at line 85 of file mf_path.c.
 {
   char *path,*pos,dir[2];
   const char *ext="";
   if (!(path=getenv("PATH")))
     return NullS;
   dir[0]=FN_LIBCHAR; dir[1]=0;
 #ifdef PROGRAM_EXTENSION
   if (!fn_ext(name)[0])
     ext=PROGRAM_EXTENSION;
 #endif
   for (pos=path ; (pos=strchr(pos,PATH_SEP)) ; path= ++pos)
   {
     if (path != pos)
     {
       strxmov(strnmov(to,path,(uint) (pos-path)),dir,name,ext,NullS);
       if (!access(to,F_OK))
       {
     to[(uint) (pos-path)+1]=0;  /* Return path only */
     return to;
       }
     }
   }
 #ifdef __WIN__
   to[0]=FN_CURLIB;
   strxmov(to+1,dir,name,ext,NullS);
   if (!access(to,F_OK))         /* Test in current dir */
   {
     to[2]=0;                /* Leave ".\" */
     return to;
   }
 #endif
   return NullS;             /* File not found */
 }
References FN_CURLIB, fn_ext(), FN_LIBCHAR, NullS, PATH_SEP, pos(), strnmov(), and strxmov().
Referenced by my_path().
my_path()
char* my_path (char * to, const char * progname, const char * own_pathname_part)
Definition at line 32 of file mf_path.c.
 {
   char *start, *end, *prog;
   size_t to_length;
   DBUG_ENTER("my_path");
   start=to;                 /* Return this */
   if (progname && (dirname_part(to, progname, &to_length) ||
            find_file_in_path(to,progname) ||
            ((prog=getenv("_")) != 0 &&
                     dirname_part(to, prog, &to_length))))
   {
     (void) intern_filename(to,to);
     if (!test_if_hard_path(to))
     {
       if (!my_getwd(curr_dir,FN_REFLEN,MYF(0)))
     bchange((uchar*) to, 0, (uchar*) curr_dir, strlen(curr_dir), strlen(to)+1);
     }
   }
   else
   {
     if ((end = getenv("MY_BASEDIR_VERSION")) == 0 &&
     (end = getenv("MY_BASEDIR")) == 0)
     {
 #ifdef DEFAULT_BASEDIR
       end= (char*) DEFAULT_BASEDIR;
 #else
       end= (char*) "/my/";
 #endif
     }
     (void) intern_filename(to,end);
     to=strend(to);
     if (to != start && to[-1] != FN_LIBCHAR)
       *to++ = FN_LIBCHAR;
     (void) strmov(to,own_pathname_part);
   }
   DBUG_PRINT("exit",("to: '%s'",start));
   DBUG_RETURN(start);
 } /* my_path */
References bchange(), curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dirname_part(), find_file_in_path(), FN_LIBCHAR, FN_REFLEN, intern_filename(), my_getwd(), MYF, prog, strend(), strmov(), and test_if_hard_path().