Azerotcore-wotlk: instance_uldaman::instance_uldaman_InstanceMapScript Struct Reference
instance_uldaman::instance_uldaman_InstanceMapScript Struct Reference
Public Member Functions
instance_uldaman_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 data) const override
std::string GetSaveData () override
void Load (const char *in) override
void OnCreatureCreate (Creature *creature) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounters [MAX_ENCOUNTERS]
ObjectGuid archaedasTempleDoorGUID
ObjectGuid ancientVaultDoorGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 40 of file instance_uldaman.cpp.
Constructor & Destructor Documentation
instance_uldaman_InstanceMapScript()
instance_uldaman::instance_uldaman_InstanceMapScript::instance_uldaman_InstanceMapScript (Map * map) inline
Definition at line 42 of file instance_uldaman.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetData()
uint32 instance_uldaman::instance_uldaman_InstanceMapScript::GetData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 95 of file instance_uldaman.cpp.
         {
             if (data < MAX_ENCOUNTERS)
             {
                 return _encounters[data];
             }
             return 0;
         }
References _encounters, and MAX_ENCOUNTERS.
GetSaveData()
std::string instance_uldaman::instance_uldaman_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 104 of file instance_uldaman.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "U D " << _encounters[DATA_IRONAYA_DOORS] << ' ' << _encounters[DATA_STONE_KEEPERS] << ' ' << _encounters[DATA_ARCHAEDAS];
             return saveStream.str();
         }
References _encounters, DATA_ARCHAEDAS, DATA_IRONAYA_DOORS, and DATA_STONE_KEEPERS.
Initialize()
void instance_uldaman::instance_uldaman_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 44 of file instance_uldaman.cpp.
         {
             memset(&_encounters, 0, sizeof(_encounters));
         }
References _encounters.
Load()
void instance_uldaman::instance_uldaman_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 111 of file instance_uldaman.cpp.
         {
             if (!in)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'U' && dataHead2 == 'D')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     loadStream >> _encounters[i];
                     if (_encounters[i] == IN_PROGRESS)
                         _encounters[i] = NOT_STARTED;
                 }
             }
         }
References _encounters, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnCreatureCreate()
void instance_uldaman::instance_uldaman_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 131 of file instance_uldaman.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_STONE_KEEPER:
                     if (_encounters[DATA_STONE_KEEPERS] != DONE && !creature->IsAlive())
                         creature->Respawn();
                     break;
             }
         }
References _encounters, DATA_STONE_KEEPERS, DONE, Object::GetEntry(), Unit::IsAlive(), NPC_STONE_KEEPER, and Creature::Respawn().
OnGameObjectCreate()
void instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 49 of file instance_uldaman.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_IRONAYA_SEAL_DOOR:
                 case GO_KEYSTONE:
                     if (_encounters[DATA_IRONAYA_DOORS] == DONE)
                     {
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                         gameobject->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     break;
                 case GO_TEMPLE_DOOR:
                     if (_encounters[DATA_STONE_KEEPERS] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     break;
                 case GO_ANCIENT_VAULT_DOOR:
                     ancientVaultDoorGUID = gameobject->GetGUID();
                     if (_encounters[DATA_ARCHAEDAS] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     break;
                 case GO_ARCHAEDAS_TEMPLE_DOOR:
                     archaedasTempleDoorGUID = gameobject->GetGUID();
                     break;
             }
         }
References _encounters, ancientVaultDoorGUID, archaedasTempleDoorGUID, DATA_ARCHAEDAS, DATA_IRONAYA_DOORS, DATA_STONE_KEEPERS, DONE, ObjectGuid::Empty, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetGUID(), GO_ANCIENT_VAULT_DOOR, GO_ARCHAEDAS_TEMPLE_DOOR, GO_FLAG_NOT_SELECTABLE, GO_IRONAYA_SEAL_DOOR, GO_KEYSTONE, GO_TEMPLE_DOOR, InstanceScript::HandleGameObject(), and Object::SetFlag().
SetData()
void instance_uldaman::instance_uldaman_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 76 of file instance_uldaman.cpp.
         {
             switch (type)
             {
                 case DATA_IRONAYA_DOORS:
                 case DATA_STONE_KEEPERS:
                     _encounters[type] = data;
                     break;
                 case DATA_ARCHAEDAS:
                     _encounters[type] = data;
                     HandleGameObject(ancientVaultDoorGUID, data == DONE, nullptr);
                     HandleGameObject(archaedasTempleDoorGUID, data != IN_PROGRESS, nullptr);
                     break;
             }
             if (data == DONE)
                 SaveToDB();
         }
References _encounters, ancientVaultDoorGUID, archaedasTempleDoorGUID, DATA_ARCHAEDAS, DATA_IRONAYA_DOORS, DATA_STONE_KEEPERS, DONE, InstanceScript::HandleGameObject(), IN_PROGRESS, and InstanceScript::SaveToDB().
Member Data Documentation
_encounters
uint32 instance_uldaman::instance_uldaman_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Definition at line 143 of file instance_uldaman.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnCreatureCreate(), OnGameObjectCreate(), and SetData().
ancientVaultDoorGUID
ObjectGuid instance_uldaman::instance_uldaman_InstanceMapScript::ancientVaultDoorGUID private
Definition at line 145 of file instance_uldaman.cpp.
Referenced by OnGameObjectCreate(), and SetData().
archaedasTempleDoorGUID
ObjectGuid instance_uldaman::instance_uldaman_InstanceMapScript::archaedasTempleDoorGUID private
Definition at line 144 of file instance_uldaman.cpp.
Referenced by OnGameObjectCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp