Azerotcore-wotlk: src/server/game/Entities/Object/Object.h File Reference
Object.h File Reference
#include "Common.h"
#include "DataMap.h"
#include "GridDefines.h"
#include "GridReference.h"
#include "Map.h"
#include "ObjectDefines.h"
#include "ObjectGuid.h"
#include "UpdateData.h"
#include "UpdateMask.h"
#include <set>
#include <string>
#include <sstream>
#include "G3D/Vector3.h"
Classes
class Object
struct Position
struct Position::PositionXYStreamer
struct Position::PositionXYZStreamer
struct Position::PositionXYZOStreamer
class WorldLocation
struct MovementInfo
struct MovementInfo::TransportInfo
struct MovementInfo::JumpInfo
class GridObject< T >
class FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >
class MovableMapObject
class WorldObject
class Acore::ObjectDistanceOrderPred
Namespaces
Acore
Macros
#define MAPID_INVALID 0xFFFFFFFF
Typedefs
typedef std::unordered_map< Player *, UpdateData > UpdateDataMapType
typedef GuidUnorderedSet UpdatePlayerSet
Enumerations
enum TempSummonType {
TEMPSUMMON_TIMED_OR_DEAD_DESPAWN = 1 , TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN = 2 , TEMPSUMMON_TIMED_DESPAWN = 3 , TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT = 4 ,
TEMPSUMMON_CORPSE_DESPAWN = 5 , TEMPSUMMON_CORPSE_TIMED_DESPAWN = 6 , TEMPSUMMON_DEAD_DESPAWN = 7 , TEMPSUMMON_MANUAL_DESPAWN = 8 ,
TEMPSUMMON_DESPAWNED = 9
}
enum PhaseMasks { PHASEMASK_NORMAL = 0x00000001 , PHASEMASK_ANYWHERE = 0xFFFFFFFF }
enum NotifyFlags { NOTIFY_NONE = 0x00 , NOTIFY_AI_RELOCATION = 0x01 , NOTIFY_VISIBILITY_CHANGED = 0x02 , NOTIFY_ALL = 0xFF }
enum MapObjectCellMoveState { MAP_OBJECT_CELL_MOVE_NONE , MAP_OBJECT_CELL_MOVE_ACTIVE , MAP_OBJECT_CELL_MOVE_INACTIVE }
Functions
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
Macro Definition Documentation
MAPID_INVALID
#define MAPID_INVALID 0xFFFFFFFF
Definition at line 458 of file Object.h.
Typedef Documentation
UpdateDataMapType
typedef std::unordered_map<Player*, UpdateData> UpdateDataMapType
Definition at line 85 of file Object.h.
UpdatePlayerSet
typedef GuidUnorderedSet UpdatePlayerSet
Definition at line 86 of file Object.h.
Enumeration Type Documentation
MapObjectCellMoveState
enum MapObjectCellMoveState
Enumerator
MAP_OBJECT_CELL_MOVE_NONE
MAP_OBJECT_CELL_MOVE_ACTIVE
MAP_OBJECT_CELL_MOVE_INACTIVE
Definition at line 644 of file Object.h.
 {
     MAP_OBJECT_CELL_MOVE_NONE, //not in move list
     MAP_OBJECT_CELL_MOVE_ACTIVE, //in move list
     MAP_OBJECT_CELL_MOVE_INACTIVE, //in move list but should not move
 };
NotifyFlags
enum NotifyFlags
Enumerator
NOTIFY_NONE
NOTIFY_AI_RELOCATION
NOTIFY_VISIBILITY_CHANGED
NOTIFY_ALL
Definition at line 58 of file Object.h.
 {
     NOTIFY_NONE                     = 0x00,
     NOTIFY_AI_RELOCATION            = 0x01,
     NOTIFY_VISIBILITY_CHANGED       = 0x02,
     NOTIFY_ALL                      = 0xFF
 };
PhaseMasks
enum PhaseMasks
Enumerator
PHASEMASK_NORMAL
PHASEMASK_ANYWHERE
Definition at line 52 of file Object.h.
 {
     PHASEMASK_NORMAL   = 0x00000001,
     PHASEMASK_ANYWHERE = 0xFFFFFFFF
 };
TempSummonType
enum TempSummonType
Enumerator
TEMPSUMMON_TIMED_OR_DEAD_DESPAWN
TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN
TEMPSUMMON_TIMED_DESPAWN
TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT
TEMPSUMMON_CORPSE_DESPAWN
TEMPSUMMON_CORPSE_TIMED_DESPAWN
TEMPSUMMON_DEAD_DESPAWN
TEMPSUMMON_MANUAL_DESPAWN
TEMPSUMMON_DESPAWNED
Definition at line 39 of file Object.h.
 {
     TEMPSUMMON_TIMED_OR_DEAD_DESPAWN       = 1,             // despawns after a specified time OR when the creature disappears
     TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN     = 2,             // despawns after a specified time OR when the creature dies
     TEMPSUMMON_TIMED_DESPAWN               = 3,             // despawns after a specified time
     TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT = 4,             // despawns after a specified time after the creature is out of combat
     TEMPSUMMON_CORPSE_DESPAWN              = 5,             // despawns instantly after death
     TEMPSUMMON_CORPSE_TIMED_DESPAWN        = 6,             // despawns after a specified time after death
     TEMPSUMMON_DEAD_DESPAWN                = 7,             // despawns when the creature disappears
     TEMPSUMMON_MANUAL_DESPAWN              = 8,             // despawns when UnSummon() is called
     TEMPSUMMON_DESPAWNED                   = 9,             // xinef: DONT USE, INTERNAL USE ONLY
 };
Function Documentation
operator<<() [1/3]
ByteBuffer& operator<< (ByteBuffer & buf, Position::PositionXYStreamer const & streamer)
operator<<() [2/3]
ByteBuffer& operator<< (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
Definition at line 1056 of file Object.cpp.
 {
     float x, y, z, o;
     streamer.m_pos->GetPosition(x, y, z, o);
     buf << x << y << z << o;
     return buf;
 }
References Position::GetPosition(), and Position::PositionXYZOStreamer::m_pos.
operator<<() [3/3]
ByteBuffer& operator<< (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
Definition at line 1040 of file Object.cpp.
 {
     float x, y, z;
     streamer.m_pos->GetPosition(x, y, z);
     buf << x << y << z;
     return buf;
 }
References Position::GetPosition(), and Position::PositionXYZStreamer::m_pos.
Referenced by ByteBuffer::operator<<().
operator>>() [1/3]
ByteBuffer& operator>> (ByteBuffer & buf, Position::PositionXYStreamer const & streamer)
operator>>() [2/3]
ByteBuffer& operator>> (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
Definition at line 1033 of file Object.cpp.
 {
     float x, y, z, o;
     buf >> x >> y >> z >> o;
     streamer.m_pos->Relocate(x, y, z, o);
     return buf;
 }
References Position::PositionXYZOStreamer::m_pos, and Position::Relocate().
operator>>() [3/3]
ByteBuffer& operator>> (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
Definition at line 1048 of file Object.cpp.
 {
     float x, y, z;
     buf >> x >> y >> z;
     streamer.m_pos->Relocate(x, y, z);
     return buf;
 }
References Position::PositionXYZStreamer::m_pos, and Position::Relocate().