Azerotcore-wotlk: boss_professor_putricide::boss_professor_putricideAI Struct Reference
boss_professor_putricide::boss_professor_putricideAI Struct Reference
Public Member Functions
boss_professor_putricideAI (Creature *creature)
void Reset () override
uint32 GetData (uint32 type) const override
void SetData (uint32 id, uint32 data) override
void AttackStart (Unit *who) override
bool CanAIAttack (const Unit *target) const override
void MoveInLineOfSight (Unit *who) override
void EnterCombat (Unit *who) override
void JustReachedHome () override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 id) override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
void ChangePhase ()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint16 sayFestergutDeathTimer
uint16 sayRotfaceDeathTimer
bool bCallEvade
uint8 _experimentState
uint8 _phase
bool bChangePhase
bool bEnteredCombat
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 226 of file boss_professor_putricide.cpp.
Constructor & Destructor Documentation
boss_professor_putricideAI()
boss_professor_putricide::boss_professor_putricideAI::boss_professor_putricideAI (Creature * creature) inline
Definition at line 228 of file boss_professor_putricide.cpp.
                                                        : BossAI(creature, DATA_PROFESSOR_PUTRICIDE)
         {
             bCallEvade = false;
             bEnteredCombat = false;
         }
References bCallEvade, and bEnteredCombat.
Member Function Documentation
AttackStart()
void boss_professor_putricide::boss_professor_putricideAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 278 of file boss_professor_putricide.cpp.
         {
             if (instance->CheckRequiredBosses(DATA_PROFESSOR_PUTRICIDE))
                 BossAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), InstanceScript::CheckRequiredBosses(), DATA_PROFESSOR_PUTRICIDE, and BossAI::instance.
Referenced by UpdateAI().
CanAIAttack()
bool boss_professor_putricide::boss_professor_putricideAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 284 of file boss_professor_putricide.cpp.
         {
             return me->IsVisible() && target->GetPositionZ() > 388.0f && target->GetPositionZ() < 410.0f && target->GetPositionY() > 3157.1f && target->GetExactDist2dSq(4356.0f, 3211.0f) < 80.0f * 80.0f;
         }
References Position::GetExactDist2dSq(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsVisible(), and ScriptedAI::me.
ChangePhase()
void boss_professor_putricide::boss_professor_putricideAI::ChangePhase () inline
Definition at line 674 of file boss_professor_putricide.cpp.
         {
             uint32 heroicDelay = (IsHeroic() ? 25000 : 0);
             events.DelayEvents(24000 + heroicDelay, EVENT_GROUP_ABILITIES);
             me->AttackStop();
             if (!IsHeroic())
             {
                 me->CastSpell(me, SPELL_TEAR_GAS, false);
                 events.ScheduleEvent(EVENT_GO_TO_TABLE, 2500);
             }
             else
             {
                 Talk(SAY_PHASE_TRANSITION_HEROIC);
                 DoCast(me, SPELL_UNSTABLE_EXPERIMENT, true);
                 DoCast(me, SPELL_UNSTABLE_EXPERIMENT, true);
                 // cast variables
                 if (Is25ManRaid())
                 {
                     std::list<Unit*> targetList;
                     Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                     for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                         if (Player* p = itr->GetSource())
                             if (!p->IsGameMaster())
                                 targetList.push_back(p);
                     size_t half = targetList.size() / 2;
                     // half gets ooze variable
                     while (half < targetList.size())
                     {
                         std::list<Unit*>::iterator itr = targetList.begin();
                         advance(itr, urand(0, targetList.size() - 1));
                         (*itr)->CastSpell(*itr, SPELL_OOZE_VARIABLE, true);
                         targetList.erase(itr);
                     }
                     // and half gets gas
                     for (std::list<Unit*>::iterator itr = targetList.begin(); itr != targetList.end(); ++itr)
                         (*itr)->CastSpell(*itr, SPELL_GAS_VARIABLE, true);
                 }
                 me->GetMotionMaster()->MoveCharge(tablePos.GetPositionX(), tablePos.GetPositionY(), tablePos.GetPositionZ(), 15.0f, POINT_TABLE_COMBAT);
             }
             switch (_phase)
             {
                 case 1:
                     _phase = 2;
                     events.ScheduleEvent(EVENT_MALLEABLE_GOO, urand(25000, 28000) + heroicDelay, EVENT_GROUP_ABILITIES);
                     events.ScheduleEvent(EVENT_CHOKING_GAS_BOMB, urand(35000, 40000) + heroicDelay, EVENT_GROUP_ABILITIES);
                     break;
                 case 2:
                     _phase = 3;
                     events.CancelEvent(EVENT_UNSTABLE_EXPERIMENT);
                     break;
                 default:
                     break;
             }
         }
References _phase, utf8::advance(), Unit::AttackStop(), MapRefMgr::begin(), Unit::CastSpell(), UnitAI::DoCast(), MapRefMgr::end(), EVENT_CHOKING_GAS_BOMB, EVENT_GO_TO_TABLE, EVENT_GROUP_ABILITIES, EVENT_MALLEABLE_GOO, EVENT_UNSTABLE_EXPERIMENT, WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::Is25ManRaid(), ScriptedAI::IsHeroic(), ScriptedAI::me, MotionMaster::MoveCharge(), POINT_TABLE_COMBAT, SAY_PHASE_TRANSITION_HEROIC, SPELL_GAS_VARIABLE, SPELL_OOZE_VARIABLE, SPELL_TEAR_GAS, SPELL_UNSTABLE_EXPERIMENT, tablePos, CreatureAI::Talk(), and urand().
Referenced by UpdateAI().
DamageTaken()
void boss_professor_putricide::boss_professor_putricideAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 396 of file boss_professor_putricide.cpp.
         {
             if (bChangePhase)
                 return;
             switch (_phase)
             {
                 case 1:
                     if (HealthAbovePct(80))
                         return;
                     me->SetReactState(REACT_PASSIVE);
                     bChangePhase = true;
                     break;
                 case 2:
                     if (HealthAbovePct(35))
                         return;
                     me->SetReactState(REACT_PASSIVE);
                     bChangePhase = true;
                     break;
                 default:
                     break;
             }
         }
References _phase, bChangePhase, ScriptedAI::HealthAbovePct(), ScriptedAI::me, REACT_PASSIVE, and Creature::SetReactState().
DoAction()
void boss_professor_putricide::boss_professor_putricideAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 469 of file boss_professor_putricide.cpp.
         {
             switch (action)
             {
                 case ACTION_FESTERGUT_COMBAT:
                     me->GetMotionMaster()->MoveCharge(festergutWatchPos.GetPositionX(), festergutWatchPos.GetPositionY(), festergutWatchPos.GetPositionZ(), 15.0f, POINT_FESTERGUT);
                     break;
                 case ACTION_FESTERGUT_DEATH:
                     sayFestergutDeathTimer = 4000;
                     break;
                 case ACTION_FESTERGUT_GAS:
                     Talk(SAY_FESTERGUT_GASEOUS_BLIGHT);
                     DoCast(me, SPELL_RELEASE_GAS_VISUAL, true);
                     break;
                 case ACTION_ROTFACE_COMBAT:
                     me->GetMotionMaster()->MoveCharge(rotfaceWatchPos.GetPositionX(), rotfaceWatchPos.GetPositionY(), rotfaceWatchPos.GetPositionZ(), 15.0f, POINT_ROTFACE);
                     break;
                 case ACTION_ROTFACE_DEATH:
                     sayRotfaceDeathTimer = 4500;
                     break;
                 default:
                     break;
             }
         }
References ACTION_FESTERGUT_COMBAT, ACTION_FESTERGUT_DEATH, ACTION_FESTERGUT_GAS, ACTION_ROTFACE_COMBAT, ACTION_ROTFACE_DEATH, UnitAI::DoCast(), festergutWatchPos, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MoveCharge(), POINT_FESTERGUT, POINT_ROTFACE, rotfaceWatchPos, SAY_FESTERGUT_GASEOUS_BLIGHT, sayFestergutDeathTimer, sayRotfaceDeathTimer, SPELL_RELEASE_GAS_VISUAL, and CreatureAI::Talk().
Referenced by MovementInform().
EnterCombat()
void boss_professor_putricide::boss_professor_putricideAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 295 of file boss_professor_putricide.cpp.
         {
             Position homePos = me->GetHomePosition();
             if (!instance->CheckRequiredBosses(DATA_PROFESSOR_PUTRICIDE, who->ToPlayer()) || me->GetExactDist2d(&homePos) > 10.0f || !me->IsVisible()) // check home position because during festergut/rotface fight, trigger missile after their death can trigger putricide combat
             {
                 me->CombatStop();
                 me->RemoveAllAuras();
                 return;
             }
             bEnteredCombat = true;
             me->CastSpell(me, SPELL_OOZE_TANK_PROTECTION, true);
             events.Reset();
             events.ScheduleEvent(EVENT_BERSERK, 600000);
             events.ScheduleEvent(EVENT_SLIME_PUDDLE, 10000, EVENT_GROUP_ABILITIES);
             events.ScheduleEvent(EVENT_UNSTABLE_EXPERIMENT, urand(30000, 35000), EVENT_GROUP_ABILITIES);
             if (IsHeroic())
                 events.ScheduleEvent(EVENT_UNBOUND_PLAGUE, 20000, EVENT_GROUP_ABILITIES);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_GAS_VARIABLE);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_OOZE_VARIABLE);
             me->setActive(true);
             Talk(SAY_AGGRO);
             DoZoneInCombat(me);
             instance->SetBossState(DATA_PROFESSOR_PUTRICIDE, IN_PROGRESS);
             instance->SetData(DATA_NAUSEA_ACHIEVEMENT, uint32(true));
         }
References bEnteredCombat, Unit::CastSpell(), InstanceScript::CheckRequiredBosses(), Unit::CombatStop(), DATA_NAUSEA_ACHIEVEMENT, DATA_PROFESSOR_PUTRICIDE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), CreatureAI::DoZoneInCombat(), EVENT_BERSERK, EVENT_GROUP_ABILITIES, EVENT_SLIME_PUDDLE, EVENT_UNBOUND_PLAGUE, EVENT_UNSTABLE_EXPERIMENT, Position::GetExactDist2d(), Creature::GetHomePosition(), IN_PROGRESS, BossAI::instance, ScriptedAI::IsHeroic(), Unit::IsVisible(), ScriptedAI::me, Unit::RemoveAllAuras(), SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), ZoneScript::SetData(), SPELL_GAS_VARIABLE, SPELL_OOZE_TANK_PROTECTION, SPELL_OOZE_VARIABLE, CreatureAI::Talk(), Object::ToPlayer(), and urand().
EnterEvadeMode()
void boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 666 of file boss_professor_putricide.cpp.
         {
             Position p = me->GetHomePosition();
             if (!me->IsInCombat() && me->GetExactDist2d(&p) > 10.0f)
                 me->GetMotionMaster()->MoveCharge(tablePos.GetPositionX(), tablePos.GetPositionY(), tablePos.GetPositionZ(), 15.0f, POINT_TABLE);
             BossAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), Position::GetExactDist2d(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsInCombat(), ScriptedAI::me, MotionMaster::MoveCharge(), POINT_TABLE, and tablePos.
Referenced by UpdateAI().
GetData()
uint32 boss_professor_putricide::boss_professor_putricideAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 257 of file boss_professor_putricide.cpp.
         {
             switch (type)
             {
                 case DATA_EXPERIMENT_STAGE:
                     return (uint32)_experimentState;
                 case DATA_PHASE:
                     return (uint32)_phase;
                 case DATA_ABOMINATION:
                     return (uint32)(const_cast<SummonList*>(&summons)->HasEntry(NPC_MUTATED_ABOMINATION_10) || const_cast<SummonList*>(&summons)->HasEntry(NPC_MUTATED_ABOMINATION_25));
             }
             return 0;
         }
References _experimentState, _phase, DATA_ABOMINATION, DATA_EXPERIMENT_STAGE, DATA_PHASE, NPC_MUTATED_ABOMINATION_10, NPC_MUTATED_ABOMINATION_25, and BossAI::summons.
JustDied()
void boss_professor_putricide::boss_professor_putricideAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 343 of file boss_professor_putricide.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
             if (Is25ManRaid() && me->HasAura(SPELL_SHADOWS_FATE))
                 DoCastAOE(SPELL_UNHOLY_INFUSION_CREDIT, true); // ReqTargetAura in dbc
             me->CastSpell((Unit*)nullptr, SPELL_MUTATED_PLAGUE_CLEAR, true);
         }
References BossAI::_JustDied(), Unit::CastSpell(), UnitAI::DoCastAOE(), Unit::HasAura(), ScriptedAI::Is25ManRaid(), ScriptedAI::me, SAY_DEATH, SPELL_MUTATED_PLAGUE_CLEAR, SPELL_SHADOWS_FATE, SPELL_UNHOLY_INFUSION_CREDIT, and CreatureAI::Talk().
JustReachedHome()
void boss_professor_putricide::boss_professor_putricideAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 324 of file boss_professor_putricide.cpp.
         {
             _JustReachedHome();
             if (bEnteredCombat)
             {
                 bEnteredCombat = false;
                 instance->SetBossState(DATA_PROFESSOR_PUTRICIDE, FAIL);
             }
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_GAS_VARIABLE);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_OOZE_VARIABLE);
         }
References BossAI::_JustReachedHome(), bEnteredCombat, DATA_PROFESSOR_PUTRICIDE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), FAIL, BossAI::instance, InstanceScript::SetBossState(), SPELL_GAS_VARIABLE, and SPELL_OOZE_VARIABLE.
JustSummoned()
void boss_professor_putricide::boss_professor_putricideAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 354 of file boss_professor_putricide.cpp.
         {
             if (summon->GetEntry() != 38308 && summon->GetEntry() != 38309 && (!me->IsInCombat() || me->IsInEvadeMode()))
             {
                 summon->DespawnOrUnsummon(1);
                 return;
             }
             summons.Summon(summon);
             switch (summon->GetEntry())
             {
                 case NPC_GROWING_OOZE_PUDDLE:
                     // blizzard casts this spell 7 times initially (confirmed in sniff)
                     for (uint8 i = 0; i < 7; ++i)
                         summon->CastSpell(summon, SPELL_GROW, true);
                     return;
                 case NPC_GAS_CLOUD:
                     // no possible aura seen in sniff adding the aurastate
                     summon->ModifyAuraState(AURA_STATE_UNKNOWN22, true);
                     summon->CastSpell(summon, SPELL_GASEOUS_BLOAT_PROC, true);
                     summon->SetReactState(REACT_PASSIVE);
                     break;
                 case NPC_VOLATILE_OOZE:
                     // no possible aura seen in sniff adding the aurastate
                     summon->ModifyAuraState(AURA_STATE_UNKNOWN19, true);
                     summon->CastSpell(summon, SPELL_OOZE_ERUPTION_SEARCH_PERIODIC, true);
                     summon->SetReactState(REACT_PASSIVE);
                     break;
                 case NPC_CHOKING_GAS_BOMB:
                     summon->CastSpell(summon, SPELL_CHOKING_GAS_BOMB_PERIODIC, true);
                     summon->CastSpell(summon, SPELL_CHOKING_GAS_EXPLOSION_TRIGGER, true);
                     return;
                 case NPC_MUTATED_ABOMINATION_10:
                 case NPC_MUTATED_ABOMINATION_25:
                     return;
             }
             if (me->IsInCombat())
                 summon->SetInCombatWithZone();
         }
References AURA_STATE_UNKNOWN19, AURA_STATE_UNKNOWN22, Unit::CastSpell(), Creature::DespawnOrUnsummon(), Object::GetEntry(), Unit::IsInCombat(), Creature::IsInEvadeMode(), ScriptedAI::me, Unit::ModifyAuraState(), NPC_CHOKING_GAS_BOMB, NPC_GAS_CLOUD, NPC_GROWING_OOZE_PUDDLE, NPC_MUTATED_ABOMINATION_10, NPC_MUTATED_ABOMINATION_25, NPC_VOLATILE_OOZE, REACT_PASSIVE, Creature::SetInCombatWithZone(), Creature::SetReactState(), SPELL_CHOKING_GAS_BOMB_PERIODIC, SPELL_CHOKING_GAS_EXPLOSION_TRIGGER, SPELL_GASEOUS_BLOAT_PROC, SPELL_GROW, SPELL_OOZE_ERUPTION_SEARCH_PERIODIC, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_professor_putricide::boss_professor_putricideAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 337 of file boss_professor_putricide.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_professor_putricide::boss_professor_putricideAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 289 of file boss_professor_putricide.cpp.
         {
             if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                 BossAI::MoveInLineOfSight(who);
         }
References Object::HasFlag(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
MovementInform()
void boss_professor_putricide::boss_professor_putricideAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 420 of file boss_professor_putricide.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch (id)
             {
                 case POINT_FESTERGUT:
                     if (Creature* c = instance->instance->GetCreature(instance->GetGuidData(DATA_FESTERGUT)))
                     {
                         if (c->IsInCombat())
{
                             instance->SetBossState(DATA_FESTERGUT, IN_PROGRESS);
                             me->SetFacingTo(festergutWatchPos.GetOrientation());
                             DoAction(ACTION_FESTERGUT_GAS);
                             c->CastSpell(c, SPELL_GASEOUS_BLIGHT_LARGE, true, nullptr, nullptr, c->GetGUID());
                         }
                         else
{
                             bCallEvade = true;
                         }
                     }
                     break;
                 case POINT_ROTFACE:
                     if (Creature* c = instance->instance->GetCreature(instance->GetGuidData(DATA_ROTFACE)))
                     {
                         if (c->IsInCombat())
{
                             instance->SetBossState(DATA_ROTFACE, IN_PROGRESS);
                             me->SetFacingTo(rotfaceWatchPos.GetOrientation());
                         }
                         else
{
                             bCallEvade = true;
                         }
                     }
                     break;
                 case POINT_TABLE:
                     me->SetFacingTo(tablePos.GetOrientation());
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_USE_STANDING);
                     break;
                 case POINT_TABLE_COMBAT:
                     me->SetFacingTo(tablePos.GetOrientation());
                     me->GetMotionMaster()->Clear(false);
                     me->GetMotionMaster()->MoveIdle();
                     events.ScheduleEvent(EVENT_TABLE_DRINK_STUFF, IsHeroic() ? 25000 : 0);
                     break;
             }
         }
References ACTION_FESTERGUT_GAS, bCallEvade, mpq::c, MotionMaster::Clear(), DATA_FESTERGUT, DATA_ROTFACE, DoAction(), EMOTE_STATE_USE_STANDING, EVENT_TABLE_DRINK_STUFF, festergutWatchPos, Map::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), IN_PROGRESS, BossAI::instance, InstanceScript::instance, ScriptedAI::IsHeroic(), ScriptedAI::me, MotionMaster::MoveIdle(), POINT_FESTERGUT, POINT_MOTION_TYPE, POINT_ROTFACE, POINT_TABLE, POINT_TABLE_COMBAT, rotfaceWatchPos, InstanceScript::SetBossState(), Unit::SetFacingTo(), Object::SetUInt32Value(), SPELL_GASEOUS_BLIGHT_LARGE, tablePos, and UNIT_NPC_EMOTESTATE.
Reset()
void boss_professor_putricide::boss_professor_putricideAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 242 of file boss_professor_putricide.cpp.
         {
             sayFestergutDeathTimer = 0;
             sayRotfaceDeathTimer = 0;
             _experimentState = 0;
             _phase = 1;
             bChangePhase = false;
             _Reset();
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetStandState(UNIT_STAND_STATE_STAND);
             if (instance->GetBossState(DATA_ROTFACE) == DONE && instance->GetBossState(DATA_FESTERGUT) == DONE)
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         }
References _experimentState, _phase, BossAI::_Reset(), bChangePhase, DATA_FESTERGUT, DATA_ROTFACE, DONE, InstanceScript::GetBossState(), BossAI::instance, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), sayFestergutDeathTimer, sayRotfaceDeathTimer, Creature::SetReactState(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_STAND.
SetData()
void boss_professor_putricide::boss_professor_putricideAI::SetData (uint32 id, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 272 of file boss_professor_putricide.cpp.
         {
             if (id == DATA_EXPERIMENT_STAGE)
                 _experimentState = (data ? 1 : 0);
         }
References _experimentState, and DATA_EXPERIMENT_STAGE.
UpdateAI()
void boss_professor_putricide::boss_professor_putricideAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 494 of file boss_professor_putricide.cpp.
         {
             if (sayFestergutDeathTimer)
             {
                 if (sayFestergutDeathTimer <= diff)
                 {
                     sayFestergutDeathTimer = 0;
                     Talk(SAY_FESTERGUT_DEATH);
                     EnterEvadeMode();
                 }
                 else
                     sayFestergutDeathTimer -= diff;
             }
             else if (sayRotfaceDeathTimer)
             {
                 if (sayRotfaceDeathTimer <= diff)
                 {
                     sayRotfaceDeathTimer = 0;
                     Talk(SAY_ROTFACE_DEATH);
                     EnterEvadeMode();
                 }
                 else
                     sayRotfaceDeathTimer -= diff;
             }
             else if (bCallEvade)
             {
                 bCallEvade = false;
                 EnterEvadeMode();
                 return;
             }
             if (!UpdateVictim() || !CheckInRoom())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (bChangePhase)
             {
                 ChangePhase();
                 bChangePhase = false;
                 return;
             }
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     Talk(SAY_BERSERK);
                     DoCast(me, SPELL_BERSERK2);
                     break;
                 case EVENT_SLIME_PUDDLE:
                     {
                         std::list<Unit*> targets;
                         SelectTargetList(targets, 2, SELECT_TARGET_RANDOM, 0.0f, true);
                         if (!targets.empty())
                             for (std::list<Unit*>::iterator itr = targets.begin(); itr != targets.end(); ++itr)
                                 me->CastSpell(*itr, SPELL_SLIME_PUDDLE_TRIGGER, true);
                         events.ScheduleEvent(EVENT_SLIME_PUDDLE, 35000, EVENT_GROUP_ABILITIES);
                     }
                     break;
                 case EVENT_UNSTABLE_EXPERIMENT:
                     Talk(EMOTE_UNSTABLE_EXPERIMENT);
                     me->CastSpell(me, SPELL_UNSTABLE_EXPERIMENT, false);
                     events.ScheduleEvent(EVENT_UNSTABLE_EXPERIMENT, urand(35000, 40000), EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_GO_TO_TABLE:
                     me->CastSpell(me, SPELL_TEAR_GAS_PERIODIC_TRIGGER, true);
                     me->GetMotionMaster()->MoveCharge(tablePos.GetPositionX(), tablePos.GetPositionY(), tablePos.GetPositionZ(), 15.0f, POINT_TABLE_COMBAT);
                     break;
                 case EVENT_TABLE_DRINK_STUFF:
                     switch (_phase)
                     {
                         case 2:
{
                                 SpellInfo const* spell = sSpellMgr->GetSpellInfo(SPELL_CREATE_CONCOCTION);
                                 me->CastSpell(me, SPELL_CREATE_CONCOCTION, false);
                                 events.ScheduleEvent(EVENT_PHASE_TRANSITION, sSpellMgr->GetSpellForDifficultyFromSpell(spell, me)->CalcCastTime() + 2250);
                                 break;
                             }
                         case 3:
{
                                 SpellInfo const* spell = sSpellMgr->GetSpellInfo(SPELL_GUZZLE_POTIONS);
                                 me->CastSpell(me, SPELL_GUZZLE_POTIONS, false);
                                 events.ScheduleEvent(EVENT_PHASE_TRANSITION, sSpellMgr->GetSpellForDifficultyFromSpell(spell, me)->CalcCastTime() + 2250);
                                 break;
                             }
                         default:
                             break;
                     }
                     break;
                 case EVENT_PHASE_TRANSITION:
                     {
                         switch (_phase)
{
                             case 2:
                                 if (Creature* face = me->FindNearestCreature(NPC_TEAR_GAS_TARGET_STALKER, 50.0f))
                                     me->SetFacingToObject(face);
                                 me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                 Talk(SAY_TRANSFORM_1);
                                 events.ScheduleEvent(EVENT_RESUME_ATTACK, 5500);
                                 break;
                             case 3:
                                 if (Creature* face = me->FindNearestCreature(NPC_TEAR_GAS_TARGET_STALKER, 50.0f))
                                     me->SetFacingToObject(face);
                                 me->SetStandState(UNIT_STAND_STATE_KNEEL);
                                 Talk(SAY_TRANSFORM_2);
                                 events.ScheduleEvent(EVENT_RESUME_ATTACK, 8500);
                                 break;
                             default:
                                 break;
                         }
                     }
                     break;
                 case EVENT_RESUME_ATTACK:
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->SetStandState(UNIT_STAND_STATE_STAND);
                     AttackStart(me->GetVictim());
                     // remove Tear Gas
                     me->RemoveAurasDueToSpell(SPELL_TEAR_GAS_PERIODIC_TRIGGER);
                     DoCastAOE(SPELL_TEAR_GAS_CANCEL);
                     if (_phase == 3)
                         summons.DespawnIf(AbominationDespawner(me));
                     instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_GAS_VARIABLE);
                     instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_OOZE_VARIABLE);
                     break;
                 case EVENT_UNBOUND_PLAGUE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, UnboundPlagueTargetSelector(me)))
                     {
                         me->CastSpell(target, SPELL_UNBOUND_PLAGUE, false);
                         me->CastSpell(target, SPELL_UNBOUND_PLAGUE_SEARCHER, false);
                         events.ScheduleEvent(EVENT_UNBOUND_PLAGUE, 90000, EVENT_GROUP_ABILITIES);
                     }
                     else
                         events.ScheduleEvent(EVENT_UNBOUND_PLAGUE, 3500, EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_MALLEABLE_GOO:
                     if (Is25ManRaid())
                     {
                         std::list<Unit*> targets;
                         SelectTargetList(targets, MalleableGooSelector(me), (IsHeroic() ? 3 : 2), SELECT_TARGET_RANDOM);
                         if (!targets.empty())
{
                             Talk(EMOTE_MALLEABLE_GOO);
                             for (std::list<Unit*>::iterator itr = targets.begin(); itr != targets.end(); ++itr)
                                 me->CastSpell(*itr, SPELL_MALLEABLE_GOO, true);
                         }
                     }
                     else
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, MalleableGooSelector(me)))
{
                             Talk(EMOTE_MALLEABLE_GOO);
                             me->CastSpell(target, SPELL_MALLEABLE_GOO, true);
                         }
                     }
                     events.ScheduleEvent(EVENT_MALLEABLE_GOO, urand(25000, 30000), EVENT_GROUP_ABILITIES);
                     break;
                 case EVENT_CHOKING_GAS_BOMB:
                     Talk(EMOTE_CHOKING_GAS_BOMB);
                     me->CastSpell(me, SPELL_CHOKING_GAS_BOMB, false);
                     events.ScheduleEvent(EVENT_CHOKING_GAS_BOMB, urand(35000, 40000), EVENT_GROUP_ABILITIES);
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _phase, AttackStart(), bCallEvade, bChangePhase, Unit::CastSpell(), ChangePhase(), BossAI::CheckInRoom(), SummonList::DespawnIf(), diff(), UnitAI::DoCast(), UnitAI::DoCastAOE(), UnitAI::DoMeleeAttackIfReady(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EMOTE_CHOKING_GAS_BOMB, EMOTE_MALLEABLE_GOO, EMOTE_UNSTABLE_EXPERIMENT, EnterEvadeMode(), EVENT_BERSERK, EVENT_CHOKING_GAS_BOMB, EVENT_GO_TO_TABLE, EVENT_GROUP_ABILITIES, EVENT_MALLEABLE_GOO, EVENT_PHASE_TRANSITION, EVENT_RESUME_ATTACK, EVENT_SLIME_PUDDLE, EVENT_TABLE_DRINK_STUFF, EVENT_UNBOUND_PLAGUE, EVENT_UNSTABLE_EXPERIMENT, WorldObject::FindNearestCreature(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), BossAI::instance, ScriptedAI::Is25ManRaid(), ScriptedAI::IsHeroic(), ScriptedAI::me, MotionMaster::MoveCharge(), NPC_TEAR_GAS_TARGET_STALKER, POINT_TABLE_COMBAT, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), SAY_BERSERK, SAY_FESTERGUT_DEATH, SAY_ROTFACE_DEATH, SAY_TRANSFORM_1, SAY_TRANSFORM_2, sayFestergutDeathTimer, sayRotfaceDeathTimer, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UnitAI::SelectTargetList(), Unit::SetFacingToObject(), Creature::SetReactState(), Unit::SetStandState(), SPELL_BERSERK2, SPELL_CHOKING_GAS_BOMB, SPELL_CREATE_CONCOCTION, SPELL_GAS_VARIABLE, SPELL_GUZZLE_POTIONS, SPELL_MALLEABLE_GOO, SPELL_OOZE_VARIABLE, SPELL_SLIME_PUDDLE_TRIGGER, SPELL_TEAR_GAS_CANCEL, SPELL_TEAR_GAS_PERIODIC_TRIGGER, SPELL_UNBOUND_PLAGUE, SPELL_UNBOUND_PLAGUE_SEARCHER, SPELL_UNSTABLE_EXPERIMENT, sSpellMgr, BossAI::summons, tablePos, CreatureAI::Talk(), UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_experimentState
uint8 boss_professor_putricide::boss_professor_putricideAI::_experimentState
Definition at line 237 of file boss_professor_putricide.cpp.
Referenced by GetData(), Reset(), and SetData().
_phase
uint8 boss_professor_putricide::boss_professor_putricideAI::_phase
Definition at line 238 of file boss_professor_putricide.cpp.
Referenced by ChangePhase(), DamageTaken(), GetData(), Reset(), and UpdateAI().
bCallEvade
bool boss_professor_putricide::boss_professor_putricideAI::bCallEvade
Definition at line 236 of file boss_professor_putricide.cpp.
Referenced by boss_professor_putricideAI(), MovementInform(), and UpdateAI().
bChangePhase
bool boss_professor_putricide::boss_professor_putricideAI::bChangePhase
Definition at line 239 of file boss_professor_putricide.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
bEnteredCombat
bool boss_professor_putricide::boss_professor_putricideAI::bEnteredCombat
Definition at line 240 of file boss_professor_putricide.cpp.
Referenced by boss_professor_putricideAI(), EnterCombat(), and JustReachedHome().
sayFestergutDeathTimer
uint16 boss_professor_putricide::boss_professor_putricideAI::sayFestergutDeathTimer
Definition at line 234 of file boss_professor_putricide.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
sayRotfaceDeathTimer
uint16 boss_professor_putricide::boss_professor_putricideAI::sayRotfaceDeathTimer
Definition at line 235 of file boss_professor_putricide.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp