Azerotcore-wotlk: npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI Struct Reference
npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI Struct Reference
Public Member Functions
npc_icc_gauntlet_controllerAI (Creature *creature)
void ScheduleBroodlings ()
void SummonBroodling ()
void SummonFrostwardens ()
void SummonSpiders ()
void SpidersMoveDown ()
void DoAction (int32 param) override
void Reset () override
void JustReachedHome () override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
InstanceScript * instance
EventMap events
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 3444 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_icc_gauntlet_controllerAI()
npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::npc_icc_gauntlet_controllerAI (Creature * creature) inline
Definition at line 3446 of file icecrown_citadel.cpp.
                                                           : NullCreatureAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 3504 of file icecrown_citadel.cpp.
         {
             if (param == ACTION_START_GAUNTLET)
             {
                 Talk(SAY_INIT);
                 me->setActive(true);
                 events.Reset();
                 events.SetPhase(0);
                 events.ScheduleEvent(EVENT_CHECK_FIGHT, 1000);
                 events.ScheduleEvent(EVENT_GAUNTLET_PHASE1, 0);
                 instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, IN_PROGRESS);
             }
         }
References ACTION_START_GAUNTLET, DATA_SINDRAGOSA_GAUNTLET, EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, IN_PROGRESS, instance, CreatureAI::me, SAY_INIT, WorldObject::setActive(), InstanceScript::SetBossState(), and CreatureAI::Talk().
JustDied()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3534 of file icecrown_citadel.cpp.
         {
             instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, DONE);
         }
References DATA_SINDRAGOSA_GAUNTLET, DONE, instance, and InstanceScript::SetBossState().
JustReachedHome()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 3529 of file icecrown_citadel.cpp.
         {
             me->setActive(false);
         }
References CreatureAI::me, and WorldObject::setActive().
JustSummoned()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3539 of file icecrown_citadel.cpp.
         {
             summons.Summon(summon);
             if (summon->GetPositionZ() > 220.0f)
             {
                 summon->SetDisableGravity(true);
                 summon->SetWalk(true);
             }
         }
References Position::GetPositionZ(), Creature::SetDisableGravity(), Creature::SetWalk(), SummonList::Summon(), and summons.
Reset()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 3518 of file icecrown_citadel.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             if (instance->GetBossState(DATA_SINDRAGOSA_GAUNTLET) != DONE)
             {
                 instance->SetBossState(DATA_SINDRAGOSA_GAUNTLET, NOT_STARTED);
                 SummonSpiders();
             }
         }
References DATA_SINDRAGOSA_GAUNTLET, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), instance, NOT_STARTED, InstanceScript::SetBossState(), summons, and SummonSpiders().
ScheduleBroodlings()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::ScheduleBroodlings () inline
Definition at line 3455 of file icecrown_citadel.cpp.
         {
             for (uint8 i = 0; i < 30; ++i)
                 events.ScheduleEvent(EVENT_SUMMON_BROODLING, 10000 + i * 350);
         }
References EVENT_SUMMON_BROODLING.
Referenced by UpdateAI().
SpidersMoveDown()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown () inline
Definition at line 3493 of file icecrown_citadel.cpp.
         {
             for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 if (Creature* spider = ObjectAccessor::GetCreature(*me, *itr))
                     if (spider->GetPositionZ() > 220.0f)
                     {
                         spider->CastSpell(spider, SPELL_WEB_BEAM2, false);
                         spider->GetMotionMaster()->MovePoint(POINT_ENTER_COMBAT, spider->GetPositionX(), spider->GetPositionY(), 213.03f, false);
                     }
         }
References SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), CreatureAI::me, POINT_ENTER_COMBAT, SPELL_WEB_BEAM2, and summons.
Referenced by UpdateAI().
SummonBroodling()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling () inline
Definition at line 3461 of file icecrown_citadel.cpp.
         {
             float dist = frand(18.0f, 39.0f);
             float o = rand_norm() * 2 * M_PI;
             if (Creature* broodling = me->SummonCreature(NPC_NERUBAR_BROODLING, me->GetPositionX() + cos(o) * dist, me->GetPositionY() + sin(o) * dist, 250.0f, Position::NormalizeOrientation(o - M_PI)))
             {
                 broodling->CastSpell(broodling, SPELL_WEB_BEAM2, false);
                 broodling->GetMotionMaster()->MovePoint(POINT_ENTER_COMBAT, broodling->GetPositionX(), broodling->GetPositionY(), 213.03f, false);
             }
         }
References G3D::frand(), Position::GetPositionX(), Position::GetPositionY(), M_PI, CreatureAI::me, Position::NormalizeOrientation(), NPC_NERUBAR_BROODLING, POINT_ENTER_COMBAT, rand_norm(), SPELL_WEB_BEAM2, and WorldObject::SummonCreature().
Referenced by UpdateAI().
SummonedCreatureDies()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3549 of file icecrown_citadel.cpp.
         {
             summons.Despawn(summon);
             if (summon->GetEntry() != NPC_NERUBAR_BROODLING && summons.GetEntryCount(NPC_NERUBAR_BROODLING) == summons.size())
             {
                 if (events.GetPhaseMask() == 0)
                 {
                     events.SetPhase(1);
                     events.ScheduleEvent(EVENT_GAUNTLET_PHASE2, 0);
                 }
                 else if (events.GetPhaseMask() == 1)
                 {
                     events.SetPhase(2);
                     events.ScheduleEvent(EVENT_GAUNTLET_PHASE3, 0);
                 }
                 else
                     Unit::Kill(me, me);
             }
         }
References SummonList::Despawn(), EVENT_GAUNTLET_PHASE2, EVENT_GAUNTLET_PHASE3, Object::GetEntry(), SummonList::GetEntryCount(), Unit::Kill(), CreatureAI::me, NPC_NERUBAR_BROODLING, SummonList::size(), and summons.
SummonFrostwardens()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonFrostwardens () inline
Definition at line 3472 of file icecrown_citadel.cpp.
         {
             for (uint8 i = 0; i < 3; ++i)
             {
                 me->SummonCreature(i == 1 ? NPC_FROSTWARDEN_SORCERESS : NPC_FROSTWARDEN_WARRIOR, 4173.94f + i * 7.0f, 2409.15f, 211.033f, 1.56f);
                 me->SummonCreature(i == 1 ? NPC_FROSTWARDEN_SORCERESS : NPC_FROSTWARDEN_WARRIOR, 4173.94f + i * 7.0f, 2556.71f, 211.033f, 4.712f);
             }
         }
References CreatureAI::me, NPC_FROSTWARDEN_SORCERESS, NPC_FROSTWARDEN_WARRIOR, and WorldObject::SummonCreature().
Referenced by UpdateAI().
SummonSpiders()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonSpiders () inline
Definition at line 3481 of file icecrown_citadel.cpp.
         {
             me->SummonCreature(NPC_NERUBAR_CHAMPION, 4207.30f, 2532.00f, 256.0, 4.253f);
             me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4228.79f, 2510.36f, 256.0f, 3.577f);
             me->SummonCreature(NPC_NERUBAR_CHAMPION, 4228.34f, 2458.20f, 256.0f, 2.642f);
             me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4207.54f, 2437.18f, 256.0f, 2.073f);
             me->SummonCreature(NPC_NERUBAR_CHAMPION, 4156.20f, 2436.80f, 256.0f, 1.083f);
             me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4133.50f, 2459.28f, 256.0f, 0.483f);
             me->SummonCreature(NPC_NERUBAR_CHAMPION, 4134.28f, 2509.71f, 256.0f, 5.788f);
             me->SummonCreature(NPC_NERUBAR_WEBWEAVER, 4156.29f, 2532.19f, 256.0f, 5.187f);
         }
References CreatureAI::me, NPC_NERUBAR_CHAMPION, NPC_NERUBAR_WEBWEAVER, and WorldObject::SummonCreature().
Referenced by Reset(), and UpdateAI().
UpdateAI()
void npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 3569 of file icecrown_citadel.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_FIGHT:
                     {
                         Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
{
                             if (me->GetDistance(itr->GetSource()) > 100.0f || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
                                 continue;
                             events.ScheduleEvent(EVENT_CHECK_FIGHT, 1000);
                             return;
                         }
                         CreatureAI::EnterEvadeMode();
                         return;
                     }
                 case EVENT_GAUNTLET_PHASE1:
                     ScheduleBroodlings();
                     SpidersMoveDown();
                     break;
                 case EVENT_GAUNTLET_PHASE2:
                     ScheduleBroodlings();
                     SummonFrostwardens();
                     break;
                 case EVENT_GAUNTLET_PHASE3:
                     ScheduleBroodlings();
                     SummonSpiders();
                     SpidersMoveDown();
                     break;
                 case EVENT_SUMMON_BROODLING:
                     SummonBroodling();
                     break;
             }
         }
References MapRefMgr::begin(), diff(), MapRefMgr::end(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, EVENT_GAUNTLET_PHASE2, EVENT_GAUNTLET_PHASE3, EVENT_SUMMON_BROODLING, WorldObject::GetDistance(), WorldObject::GetMap(), Map::GetPlayers(), CreatureAI::me, ScheduleBroodlings(), SpidersMoveDown(), SummonBroodling(), SummonFrostwardens(), and SummonSpiders().
Member Data Documentation
events
EventMap npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::events
Definition at line 3453 of file icecrown_citadel.cpp.
instance
InstanceScript* npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::instance
Definition at line 3452 of file icecrown_citadel.cpp.
Referenced by DoAction(), JustDied(), npc_icc_gauntlet_controllerAI(), and Reset().
summons
SummonList npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::summons
Definition at line 3451 of file icecrown_citadel.cpp.
Referenced by JustSummoned(), Reset(), SpidersMoveDown(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp