Azerotcore-wotlk: deps/zlib/gzwrite.c File Reference
gzwrite.c File Reference
#include "gzguts.h"
Functions
int gz_init OF ((gz_statep))
int gz_comp OF ((gz_statep, int))
int gz_zero OF ((gz_statep, z_off64_t))
int gz_init (gz_statep state)
int gz_comp (gz_statep state, int flush)
int gz_zero (gz_statep state, z_off64_t len)
int ZEXPORT gzwrite (gzFile file, voidpc buf, unsigned len)
int ZEXPORT gzputc (gzFile file, int c)
int ZEXPORT gzputs (gzFile file, const char *str)
int ZEXPORTVA gzprintf (gzFile file, const char *format, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20)
int ZEXPORT gzflush (gzFile file, int flush)
int ZEXPORT gzsetparams (gzFile file, int level, int strategy)
int ZEXPORT gzclose_w (gzFile file)
Function Documentation
gz_comp()
int gz_comp (gz_statep state, int flush)
Definition at line 70 of file gzwrite.c.
 {
     int ret, got;
     unsigned have;
     z_streamp strm = &(state->strm);
     /* allocate memory if this is the first time through */
     if (state->size == 0 && gz_init(state) == -1)
         return -1;
     /* write directly if requested */
     if (state->direct) {
         got = write(state->fd, strm->next_in, strm->avail_in);
         if (got < 0 || (unsigned)got != strm->avail_in) {
             gz_error(state, Z_ERRNO, zstrerror());
             return -1;
         }
         strm->avail_in = 0;
         return 0;
     }
     /* run deflate() on provided input until it produces no more output */
     ret = Z_OK;
     do {
         /* write out current buffer contents if full, or if flushing, but if
            doing Z_FINISH then don't write until we get to Z_STREAM_END */
         if (strm->avail_out == 0 || (flush != Z_NO_FLUSH &&
             (flush != Z_FINISH || ret == Z_STREAM_END))) {
             have = (unsigned)(strm->next_out - state->x.next);
             if (have && ((got = write(state->fd, state->x.next, have)) < 0 ||
                          (unsigned)got != have)) {
                 gz_error(state, Z_ERRNO, zstrerror());
                 return -1;
             }
             if (strm->avail_out == 0) {
                 strm->avail_out = state->size;
                 strm->next_out = state->out;
             }
             state->x.next = strm->next_out;
         }
         /* compress */
         have = strm->avail_out;
         ret = deflate(strm, flush);
         if (ret == Z_STREAM_ERROR) {
             gz_error(state, Z_STREAM_ERROR,
                       "internal error: deflate stream corrupt");
             return -1;
         }
         have -= strm->avail_out;
     } while (have);
     /* if that completed a deflate stream, allow another to start */
     if (flush == Z_FINISH)
         deflateReset(strm);
     /* all done, no errors */
     return 0;
 }
References deflate(), deflateReset(), gz_error(), gz_init(), ret, write, Z_ERRNO, Z_FINISH, Z_NO_FLUSH, Z_OK, Z_STREAM_END, Z_STREAM_ERROR, and zstrerror.
Referenced by gz_zero(), gzclose_w(), gzflush(), gzprintf(), gzsetparams(), and gzwrite().
gz_init()
int gz_init (gz_statep state)
Definition at line 15 of file gzwrite.c.
 {
     int ret;
     z_streamp strm = &(state->strm);
     /* allocate input buffer */
     state->in = malloc(state->want);
     if (state->in == NULL) {
         gz_error(state, Z_MEM_ERROR, "out of memory");
         return -1;
     }
     /* only need output buffer and deflate state if compressing */
     if (!state->direct) {
         /* allocate output buffer */
         state->out = malloc(state->want);
         if (state->out == NULL) {
             free(state->in);
             gz_error(state, Z_MEM_ERROR, "out of memory");
             return -1;
         }
         /* allocate deflate memory, set up for gzip compression */
         strm->zalloc = Z_NULL;
         strm->zfree = Z_NULL;
         strm->opaque = Z_NULL;
         ret = deflateInit2(strm, state->level, Z_DEFLATED,
                            MAX_WBITS + 16, DEF_MEM_LEVEL, state->strategy);
         if (ret != Z_OK) {
             free(state->out);
             free(state->in);
             gz_error(state, Z_MEM_ERROR, "out of memory");
             return -1;
         }
     }
     /* mark state as initialized */
     state->size = state->want;
     /* initialize write buffer if compressing */
     if (!state->direct) {
         strm->avail_out = state->size;
         strm->next_out = state->out;
         state->x.next = strm->next_out;
     }
     return 0;
 }
References DEF_MEM_LEVEL, deflateInit2, gz_error(), MAX_WBITS, NULL, ret, Z_DEFLATED, Z_MEM_ERROR, Z_NULL, and Z_OK.
Referenced by gz_comp(), gzprintf(), and gzwrite().
gz_zero()
int gz_zero (gz_statep state, z_off64_t len)
Definition at line 133 of file gzwrite.c.
 {
     int first;
     unsigned n;
     z_streamp strm = &(state->strm);
     /* consume whatever's left in the input buffer */
     if (strm->avail_in && gz_comp(state, Z_NO_FLUSH) == -1)
         return -1;
     /* compress len zeros (len guaranteed > 0) */
     first = 1;
     while (len) {
         n = GT_OFF(state->size) || (z_off64_t)state->size > len ?
             (unsigned)len : state->size;
         if (first) {
             memset(state->in, 0, n);
             first = 0;
         }
         strm->avail_in = n;
         strm->next_in = state->in;
         state->x.pos += n;
         if (gz_comp(state, Z_NO_FLUSH) == -1)
             return -1;
         len -= n;
     }
     return 0;
 }
References detail::first(), GT_OFF, gz_comp(), memset, Z_NO_FLUSH, and z_off64_t.
Referenced by gzclose_w(), gzflush(), gzprintf(), gzputc(), gzsetparams(), and gzwrite().
gzclose_w()
int ZEXPORT gzclose_w (gzFile file)
Definition at line 527 of file gzwrite.c.
 {
     int ret = Z_OK;
     gz_statep state;
     /* get internal structure */
     if (file == NULL)
         return Z_STREAM_ERROR;
     state = (gz_statep)file;
     /* check that we're writing */
     if (state->mode != GZ_WRITE)
         return Z_STREAM_ERROR;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             ret = state->err;
     }
     /* flush, free memory, and close file */
     if (state->size) {
         if (gz_comp(state, Z_FINISH) == -1)
             ret = state->err;
         if (!state->direct) {
             (void)deflateEnd(&(state->strm));
             free(state->out);
         }
         free(state->in);
     }
     gz_error(state, Z_OK, NULL);
     free(state->path);
     if (close(state->fd) == -1)
         ret = Z_ERRNO;
     free(state);
     return ret;
 }
References close, deflateEnd(), mpq::file, gz_comp(), gz_error(), GZ_WRITE, gz_zero(), if(), NULL, ret, Z_ERRNO, Z_FINISH, Z_OK, and Z_STREAM_ERROR.
Referenced by gzclose().
gzflush()
int ZEXPORT gzflush (gzFile file, int flush)
Definition at line 453 of file gzwrite.c.
 {
     gz_statep state;
     /* get internal structure */
     if (file == NULL)
         return -1;
     state = (gz_statep)file;
     /* check that we're writing and that there's no error */
     if (state->mode != GZ_WRITE || state->err != Z_OK)
         return Z_STREAM_ERROR;
     /* check flush parameter */
     if (flush < 0 || flush > Z_FINISH)
         return Z_STREAM_ERROR;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             return -1;
     }
     /* compress remaining data with requested flush */
     gz_comp(state, flush);
     return state->err;
 }
References mpq::file, gz_comp(), GZ_WRITE, gz_zero(), NULL, Z_FINISH, Z_OK, and Z_STREAM_ERROR.
gzprintf()
int ZEXPORTVA gzprintf (gzFile file, const char * format, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20)
Definition at line 374 of file gzwrite.c.
 {
     int size, len;
     gz_statep state;
     z_streamp strm;
     /* get internal structure */
     if (file == NULL)
         return -1;
     state = (gz_statep)file;
     strm = &(state->strm);
     /* check that can really pass pointer in ints */
     if (sizeof(int) != sizeof(void *))
         return 0;
     /* check that we're writing and that there's no error */
     if (state->mode != GZ_WRITE || state->err != Z_OK)
         return 0;
     /* make sure we have some buffer space */
     if (state->size == 0 && gz_init(state) == -1)
         return 0;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             return 0;
     }
     /* consume whatever's left in the input buffer */
     if (strm->avail_in && gz_comp(state, Z_NO_FLUSH) == -1)
         return 0;
     /* do the printf() into the input buffer, put length in len */
     size = (int)(state->size);
     state->in[size - 1] = 0;
 #ifdef NO_snprintf
 #  ifdef HAS_sprintf_void
     sprintf((char *)(state->in), format, a1, a2, a3, a4, a5, a6, a7, a8,
             a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
     for (len = 0; len < size; len++)
         if (state->in[len] == 0) break;
 #  else
     len = sprintf((char *)(state->in), format, a1, a2, a3, a4, a5, a6, a7, a8,
                   a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
 #  endif
 #else
 #  ifdef HAS_snprintf_void
     snprintf((char *)(state->in), size, format, a1, a2, a3, a4, a5, a6, a7, a8,
              a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
     len = strlen((char *)(state->in));
 #  else
     len = snprintf((char *)(state->in), size, format, a1, a2, a3, a4, a5, a6,
                    a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18,
                    a19, a20);
 #  endif
 #endif
     /* check that printf() results fit in buffer */
     if (len <= 0 || len >= (int)size || state->in[size - 1] != 0)
         return 0;
     /* update buffer and position, defer compression until needed */
     strm->avail_in = (unsigned)len;
     strm->next_in = state->in;
     state->x.pos += len;
     return len;
 }
References mpq::file, format(), gz_comp(), gz_init(), GZ_WRITE, gz_zero(), NULL, sprintf(), Z_NO_FLUSH, and Z_OK.
Referenced by test_gzio().
gzputc()
int ZEXPORT gzputc (gzFile file, int c)
Definition at line 243 of file gzwrite.c.
 {
     unsigned char buf[1];
     gz_statep state;
     z_streamp strm;
     /* get internal structure */
     if (file == NULL)
         return -1;
     state = (gz_statep)file;
     strm = &(state->strm);
     /* check that we're writing and that there's no error */
     if (state->mode != GZ_WRITE || state->err != Z_OK)
         return -1;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             return -1;
     }
     /* try writing to input buffer for speed (state->size == 0 if buffer not
        initialized) */
     if (strm->avail_in < state->size) {
         if (strm->avail_in == 0)
             strm->next_in = state->in;
         strm->next_in[strm->avail_in++] = c;
         state->x.pos++;
         return c & 0xff;
     }
     /* no room in buffer or not initialized, use gz_write() */
     buf[0] = c;
     if (gzwrite(file, buf, 1) != 1)
         return -1;
     return c & 0xff;
 }
References mpq::c, mpq::file, GZ_WRITE, gz_zero(), gzwrite(), NULL, and Z_OK.
Referenced by test_gzio().
gzputs()
int ZEXPORT gzputs (gzFile file, const char * str)
Definition at line 286 of file gzwrite.c.
 {
     int ret;
     unsigned len;
     /* write string */
     len = (unsigned)strlen(str);
     ret = gzwrite(file, str, len);
     return ret == 0 && len != 0 ? -1 : ret;
 }
References mpq::file, gzwrite(), and ret.
Referenced by test_gzio().
gzsetparams()
int ZEXPORT gzsetparams (gzFile file, int level, int strategy)
Definition at line 485 of file gzwrite.c.
 {
     gz_statep state;
     z_streamp strm;
     /* get internal structure */
     if (file == NULL)
         return Z_STREAM_ERROR;
     state = (gz_statep)file;
     strm = &(state->strm);
     /* check that we're writing and that there's no error */
     if (state->mode != GZ_WRITE || state->err != Z_OK)
         return Z_STREAM_ERROR;
     /* if no change is requested, then do nothing */
     if (level == state->level && strategy == state->strategy)
         return Z_OK;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             return -1;
     }
     /* change compression parameters for subsequent input */
     if (state->size) {
         /* flush previous input with previous parameters before changing */
         if (strm->avail_in && gz_comp(state, Z_PARTIAL_FLUSH) == -1)
             return state->err;
         deflateParams(strm, level, strategy);
     }
     state->level = level;
     state->strategy = strategy;
     return Z_OK;
 }
References deflateParams(), mpq::file, gz_comp(), GZ_WRITE, gz_zero(), NULL, Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_ERROR.
gzwrite()
int ZEXPORT gzwrite (gzFile file, voidpc buf, unsigned len)
Definition at line 165 of file gzwrite.c.
 {
     unsigned put = len;
     unsigned n;
     gz_statep state;
     z_streamp strm;
     /* get internal structure */
     if (file == NULL)
         return 0;
     state = (gz_statep)file;
     strm = &(state->strm);
     /* check that we're writing and that there's no error */
     if (state->mode != GZ_WRITE || state->err != Z_OK)
         return 0;
     /* since an int is returned, make sure len fits in one, otherwise return
        with an error (this avoids the flaw in the interface) */
     if ((int)len < 0) {
         gz_error(state, Z_DATA_ERROR, "requested length does not fit in int");
         return 0;
     }
     /* if len is zero, avoid unnecessary operations */
     if (len == 0)
         return 0;
     /* allocate memory if this is the first time through */
     if (state->size == 0 && gz_init(state) == -1)
         return 0;
     /* check for seek request */
     if (state->seek) {
         state->seek = 0;
         if (gz_zero(state, state->skip) == -1)
             return 0;
     }
     /* for small len, copy to input buffer, otherwise compress directly */
     if (len < state->size) {
         /* copy to input buffer, compress when full */
         do {
             if (strm->avail_in == 0)
                 strm->next_in = state->in;
             n = state->size - strm->avail_in;
             if (n > len)
                 n = len;
             memcpy(strm->next_in + strm->avail_in, buf, n);
             strm->avail_in += n;
             state->x.pos += n;
             buf = (char *)buf + n;
             len -= n;
             if (len && gz_comp(state, Z_NO_FLUSH) == -1)
                 return 0;
         } while (len);
     }
     else {
         /* consume whatever's left in the input buffer */
         if (strm->avail_in && gz_comp(state, Z_NO_FLUSH) == -1)
             return 0;
         /* directly compress user buffer to file */
         strm->avail_in = len;
         strm->next_in = (voidp)buf;
         state->x.pos += len;
         if (gz_comp(state, Z_NO_FLUSH) == -1)
             return 0;
     }
     /* input was all buffered or compressed (put will fit in int) */
     return (int)put;
 }
References mpq::file, gz_comp(), gz_error(), gz_init(), GZ_WRITE, gz_zero(), memcpy, NULL, Z_DATA_ERROR, Z_NO_FLUSH, and Z_OK.
Referenced by gz_compress(), gzputc(), and gzputs().
OF() [1/3]
int gz_init OF ((gz_statep))
OF() [2/3]
int gz_comp OF ((gz_statep, int))
OF() [3/3]
int gz_zero OF ((gz_statep, z_off64_t))