Azerotcore-wotlk: SQLQueryHolder< T > Class Template Reference
SQLQueryHolder< T > Class Template Reference
#include <QueryHolder.h>
Public Member Functions
bool SetPreparedQuery (size_t index, PreparedStatement< T > *stmt)
Public Member Functions inherited from SQLQueryHolderBase
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (size_t size)
PreparedQueryResult GetPreparedResult (size_t index) const
void SetPreparedResult (size_t index, PreparedResultSet *result)
Additional Inherited Members
Protected Member Functions inherited from SQLQueryHolderBase
bool SetPreparedQueryImpl (size_t index, PreparedStatementBase *stmt)
Detailed Description
template<typename T>
class SQLQueryHolder< T >
Definition at line 41 of file QueryHolder.h.
Member Function Documentation
SetPreparedQuery()
template<typename T > bool SQLQueryHolder< T >::SetPreparedQuery (size_t index, PreparedStatement< T > * stmt) inline
Definition at line 44 of file QueryHolder.h.
     {
         return SetPreparedQueryImpl(index, stmt);
     }
References SQLQueryHolderBase::SetPreparedQueryImpl().
Referenced by LoginQueryHolder::Initialize(), and LoadPetFromDBQueryHolder::Initialize().
The documentation for this class was generated from the following files:
src/server/database/Database/DatabaseEnvFwd.h
src/server/database/Database/QueryHolder.h