Azerotcore-wotlk: PacketLog Class Reference
PacketLog Class Reference
#include <PacketLog.h>
Public Member Functions
void Initialize ()
bool CanLogPacket () const
void LogPacket (WorldPacket const &packet, Direction direction, boost::asio::ip::address const &addr, uint16 port)
Static Public Member Functions
static PacketLog * instance ()
Private Member Functions
PacketLog ()
~PacketLog ()
Private Attributes
std::mutex _logPacketLock
std::once_flag _initializeFlag
FILE * _file
Detailed Description
Definition at line 33 of file PacketLog.h.
Constructor & Destructor Documentation
PacketLog()
PacketLog::PacketLog () private
Definition at line 60 of file PacketLog.cpp.
                      : _file(nullptr)
 {
     std::call_once(_initializeFlag, &PacketLog::Initialize, this);
 }
References _initializeFlag, and Initialize().
~PacketLog()
PacketLog::~PacketLog () private
Definition at line 65 of file PacketLog.cpp.
 {
     if (_file)
     {
         fclose(_file);
     }
     _file = nullptr;
 }
References _file.
Member Function Documentation
CanLogPacket()
bool PacketLog::CanLogPacket () const inline
Definition at line 45 of file PacketLog.h.
 { return (_file != nullptr); }
Referenced by Initialize().
Initialize()
void PacketLog::Initialize (void)
Definition at line 81 of file PacketLog.cpp.
 {
     std::string logsDir = sConfigMgr->GetOption<std::string>("LogsDir", "");
     if (!logsDir.empty() && (logsDir.at(logsDir.length() - 1) != '/') && (logsDir.at(logsDir.length() - 1) != '\\'))
     {
         logsDir.push_back('/');
     }
     std::string logname = sConfigMgr->GetOption<std::string>("PacketLogFile", "");
     if (!logname.empty())
     {
         _file = fopen((logsDir + logname).c_str(), "wb");
         LogHeader header;
         header.Signature[0] = 'P'; header.Signature[1] = 'K'; header.Signature[2] = 'T';
         header.FormatVersion = 0x0301;
         header.SnifferId = 'T';
         header.Build = 12340;
         header.Locale[0] = 'e'; header.Locale[1] = 'n'; header.Locale[2] = 'U'; header.Locale[3] = 'S';
         std::memset(header.SessionKey, 0, sizeof(header.SessionKey));
         header.SniffStartUnixtime = time(nullptr);
         header.SniffStartTicks = getMSTime();
         header.OptionalDataSize = 0;
         if (CanLogPacket())
         {
             fwrite(&header, sizeof(header), 1, _file);
         }
     }
 }
References _file, LogHeader::Build, CanLogPacket(), LogHeader::FormatVersion, getMSTime(), LogHeader::Locale, memset, LogHeader::OptionalDataSize, sConfigMgr, LogHeader::SessionKey, LogHeader::Signature, LogHeader::SnifferId, LogHeader::SniffStartTicks, and LogHeader::SniffStartUnixtime.
Referenced by PacketLog().
instance()
PacketLog * PacketLog::instance () static
Definition at line 75 of file PacketLog.cpp.
 {
     static PacketLog instance;
     return &instance;
 }
LogPacket()
void PacketLog::LogPacket (WorldPacket const & packet, Direction direction, boost::asio::ip::address const & addr, uint16 port)
Definition at line 113 of file PacketLog.cpp.
 {
     std::lock_guard<std::mutex> lock(_logPacketLock);
     PacketHeader header;
     header.Direction = direction == CLIENT_TO_SERVER ? 0x47534d43 : 0x47534d53;
     header.ConnectionId = 0;
     header.ArrivalTicks = getMSTime();
     header.OptionalDataSize = sizeof(header.OptionalData);
     memset(header.OptionalData.SocketIPBytes, 0, sizeof(header.OptionalData.SocketIPBytes));
     if (addr.is_v4())
     {
         auto bytes = addr.to_v4().to_bytes();
         memcpy(header.OptionalData.SocketIPBytes, bytes.data(), bytes.size());
     }
     else if (addr.is_v6())
     {
         auto bytes = addr.to_v6().to_bytes();
         memcpy(header.OptionalData.SocketIPBytes, bytes.data(), bytes.size());
     }
     header.OptionalData.SocketPort = port;
     header.Length = packet.size() + sizeof(header.Opcode);
     header.Opcode = packet.GetOpcode();
     fwrite(&header, sizeof(header), 1, _file);
     if (!packet.empty())
     {
         fwrite(packet.contents(), 1, packet.size(), _file);
     }
     fflush(_file);
 }
References _file, _logPacketLock, PacketHeader::ArrivalTicks, CLIENT_TO_SERVER, PacketHeader::ConnectionId, ByteBuffer::contents(), PacketHeader::Direction, ByteBuffer::empty(), getMSTime(), WorldPacket::GetOpcode(), PacketHeader::Length, memcpy, memset, PacketHeader::Opcode, PacketHeader::OptionalData, PacketHeader::OptionalDataSize, ByteBuffer::size(), PacketHeader::OptionalData::SocketIPBytes, and PacketHeader::OptionalData::SocketPort.
Member Data Documentation
_file
FILE* PacketLog::_file private
Definition at line 49 of file PacketLog.h.
Referenced by mpq.Reader::__del__(), mpq.Reader::__repr__(), mpq.Reader::_read_block(), Initialize(), LogPacket(), mpq.Reader::read(), mpq.Reader::seek(), and ~PacketLog().
_initializeFlag
std::once_flag PacketLog::_initializeFlag private
Definition at line 39 of file PacketLog.h.
Referenced by PacketLog().
_logPacketLock
std::mutex PacketLog::_logPacketLock private
Definition at line 38 of file PacketLog.h.
Referenced by LogPacket().
The documentation for this class was generated from the following files:
src/server/game/Server/Protocol/PacketLog.h
src/server/game/Server/Protocol/PacketLog.cpp