Azerotcore-wotlk: BGSpamProtect Class Reference
BGSpamProtect Class Reference
#include <BattlegroundSpamProtect.h>
Public Member Functions
bool CanAnnounce (Player *player, Battleground *bg, uint32 minLevel, uint32 queueTotal)
Static Public Member Functions
static BGSpamProtect * instance ()
Detailed Description
Definition at line 26 of file BattlegroundSpamProtect.h.
Member Function Documentation
CanAnnounce()
bool BGSpamProtect::CanAnnounce (Player * player, Battleground * bg, uint32 minLevel, uint32 queueTotal)
Definition at line 57 of file BattlegroundSpamProtect.cpp.
 {
     ObjectGuid guid = player->GetGUID();
     // Check prev time
     if (!IsCorrectDelay(guid))
     {
         return false;
     }
     if (bg)
     {
         // When limited, it announces only if there are at least CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_PLAYERS in queue
         auto limitQueueMinLevel = sWorld->getIntConfig(CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_LEVEL);
         if (limitQueueMinLevel && minLevel >= limitQueueMinLevel)
         {
             // limit only RBG for 80, WSG for lower levels
             auto bgTypeToLimit = minLevel == 80 ? BATTLEGROUND_RB : BATTLEGROUND_WS;
             if (bg->GetBgTypeID() == bgTypeToLimit && queueTotal < sWorld->getIntConfig(CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_PLAYERS))
             {
                 return false;
             }
         }
     }
     AddTime(guid);
     return true;
 }
References anonymous_namespace{BattlegroundSpamProtect.cpp}::AddTime(), BATTLEGROUND_RB, BATTLEGROUND_WS, bg(), CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_LEVEL, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_LIMIT_MIN_PLAYERS, Object::GetGUID(), anonymous_namespace{BattlegroundSpamProtect.cpp}::IsCorrectDelay(), and sWorld.
instance()
BGSpamProtect * BGSpamProtect::instance () static
Definition at line 51 of file BattlegroundSpamProtect.cpp.
 {
     static BGSpamProtect instance;
     return &instance;
 }
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/BattlegroundSpamProtect.h
src/server/game/Battlegrounds/BattlegroundSpamProtect.cpp