Azerotcore-wotlk: VMAP::MapRayCallback Class Reference
VMAP::MapRayCallback Class Reference
Public Member Functions
MapRayCallback (ModelInstance *val)
bool operator() (const G3D::Ray &ray, uint32 entry, float &distance, bool StopAtFirstHit)
bool didHit ()
Protected Attributes
ModelInstance * prims
bool hit
Detailed Description
Definition at line 34 of file MapTree.cpp.
Constructor & Destructor Documentation
MapRayCallback()
VMAP::MapRayCallback::MapRayCallback (ModelInstance * val) inline
Definition at line 37 of file MapTree.cpp.
 : prims(val), hit(false) {}
Member Function Documentation
didHit()
bool VMAP::MapRayCallback::didHit () inline
Definition at line 47 of file MapTree.cpp.
 { return hit; }
References hit.
Referenced by VMAP::StaticMapTree::GetIntersectionTime().
operator()()
bool VMAP::MapRayCallback::operator() (const G3D::Ray & ray, uint32 entry, float & distance, bool StopAtFirstHit) inline
Definition at line 38 of file MapTree.cpp.
         {
             bool result = prims[entry].intersectRay(ray, distance, StopAtFirstHit);
             if (result)
             {
                 hit = true;
             }
             return result;
         }
References G3D::distance(), hit, VMAP::ModelInstance::intersectRay(), and prims.
Member Data Documentation
hit
bool VMAP::MapRayCallback::hit protected
Definition at line 50 of file MapTree.cpp.
Referenced by didHit(), and operator()().
prims
ModelInstance* VMAP::MapRayCallback::prims protected
Definition at line 49 of file MapTree.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/common/Collision/Maps/MapTree.cpp