Azerotcore-wotlk: DBUpdaterUtil Class Reference
DBUpdaterUtil Class Reference
#include <DBUpdater.h>
Static Public Member Functions
static std::string GetCorrectedMySQLExecutable ()
static bool CheckExecutable ()
Static Private Member Functions
static std::string & corrected_path ()
Detailed Description
Definition at line 55 of file DBUpdater.h.
Member Function Documentation
CheckExecutable()
bool DBUpdaterUtil::CheckExecutable () static
Definition at line 40 of file DBUpdater.cpp.
 {
     std::filesystem::path exe(GetCorrectedMySQLExecutable());
     if (!is_regular_file(exe))
     {
         exe = Acore::SearchExecutableInPath("mysql");
         if (!exe.empty() && is_regular_file(exe))
         {
             // Correct the path to the cli
             corrected_path() = absolute(exe).generic_string();
             return true;
         }
         LOG_FATAL("sql.updates", "Didn't find any executable MySQL binary at \'%s\' or in path, correct the path in the *.conf (\"MySQLExecutable\").",
             absolute(exe).generic_string().c_str());
         return false;
     }
     return true;
 }
References corrected_path(), GetCorrectedMySQLExecutable(), LOG_FATAL, and Acore::SearchExecutableInPath().
Referenced by DBUpdater< T >::Populate(), and DBUpdater< T >::Update().
corrected_path()
std::string & DBUpdaterUtil::corrected_path () static private
Definition at line 61 of file DBUpdater.cpp.
 {
     static std::string path;
     return path;
 }
Referenced by CheckExecutable(), and GetCorrectedMySQLExecutable().
GetCorrectedMySQLExecutable()
std::string DBUpdaterUtil::GetCorrectedMySQLExecutable () static
Definition at line 32 of file DBUpdater.cpp.
 {
     if (!corrected_path().empty())
         return corrected_path();
     else
         return BuiltInConfig::GetMySQLExecutable();
 }
References corrected_path(), and BuiltInConfig::GetMySQLExecutable().
Referenced by DBUpdater< T >::ApplyFile(), and CheckExecutable().
The documentation for this class was generated from the following files:
src/server/database/Updater/DBUpdater.h
src/server/database/Updater/DBUpdater.cpp