Azerotcore-wotlk: deps/mysqllite/mysys/sha1.c File Reference
sha1.c File Reference
#include "my_global.h"
#include "m_string.h"
#include "sha1.h"
Macros
#define SHA1CircularShift(bits, word) (((word) << (bits)) | ((word) >> (32-(bits))))
Functions
static void SHA1PadMessage (SHA1_CONTEXT *)
static void SHA1ProcessMessageBlock (SHA1_CONTEXT *)
int mysql_sha1_reset (SHA1_CONTEXT *context)
int mysql_sha1_result (SHA1_CONTEXT *context, uint8 Message_Digest[SHA1_HASH_SIZE])
int mysql_sha1_input (SHA1_CONTEXT *context, const uint8 *message_array, unsigned length)
Variables
const uint32 sha_const_key [5]
static const uint32 K []
Macro Definition Documentation
SHA1CircularShift
#define SHA1CircularShift (bits, word) (((word) << (bits)) | ((word) >> (32-(bits))))
Definition at line 90 of file sha1.c.
Function Documentation
mysql_sha1_input()
int mysql_sha1_input (SHA1_CONTEXT * context, const uint8 * message_array, unsigned length)
Definition at line 209 of file sha1.c.
 {
   if (!length)
     return SHA_SUCCESS;
 #ifndef DBUG_OFF
   /* We assume client konows what it is doing in non-debug mode */
   if (!context || !message_array)
     return SHA_NULL;
   if (context->Computed)
     return (context->Corrupted= SHA_STATE_ERROR);
   if (context->Corrupted)
     return context->Corrupted;
 #endif
   while (length--)
   {
     context->Message_Block[context->Message_Block_Index++]=
       (*message_array & 0xFF);
     context->Length  += 8;  /* Length is in bits */
 #ifndef DBUG_OFF
     /*
       Then we're not debugging we assume we never will get message longer
       2^64 bits.
     */
     if (context->Length == 0)
       return (context->Corrupted= 1);      /* Message is too long */
 #endif
     if (context->Message_Block_Index == 64)
     {
       SHA1ProcessMessageBlock(context);
     }
     message_array++;
   }
   return SHA_SUCCESS;
 }
References SHA1_CONTEXT::Computed, SHA1_CONTEXT::Corrupted, G3D::length(), SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block, SHA1_CONTEXT::Message_Block_Index, SHA1ProcessMessageBlock(), SHA_NULL, SHA_STATE_ERROR, and SHA_SUCCESS.
mysql_sha1_reset()
int mysql_sha1_reset (SHA1_CONTEXT * context)
Definition at line 125 of file sha1.c.
 {
 #ifndef DBUG_OFF
   if (!context)
     return SHA_NULL;
 #endif
   context->Length         = 0;
   context->Message_Block_Index    = 0;
   context->Intermediate_Hash[0]   = sha_const_key[0];
   context->Intermediate_Hash[1]   = sha_const_key[1];
   context->Intermediate_Hash[2]   = sha_const_key[2];
   context->Intermediate_Hash[3]   = sha_const_key[3];
   context->Intermediate_Hash[4]   = sha_const_key[4];
   context->Computed   = 0;
   context->Corrupted  = 0;
   return SHA_SUCCESS;
 }
References SHA1_CONTEXT::Computed, SHA1_CONTEXT::Corrupted, SHA1_CONTEXT::Intermediate_Hash, SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block_Index, sha_const_key, SHA_NULL, and SHA_SUCCESS.
Referenced by check_scramble(), my_make_scrambled_password(), and scramble().
mysql_sha1_result()
int mysql_sha1_result (SHA1_CONTEXT * context, uint8 Message_Digest[SHA1_HASH_SIZE])
Definition at line 165 of file sha1.c.
 {
   int i;
 #ifndef DBUG_OFF
   if (!context || !Message_Digest)
     return SHA_NULL;
   if (context->Corrupted)
     return context->Corrupted;
 #endif
   if (!context->Computed)
   {
     SHA1PadMessage(context);
      /* message may be sensitive, clear it out */
     bzero((char*) context->Message_Block,64);
     context->Length   = 0;    /* and clear length  */
     context->Computed = 1;
   }
   for (i = 0; i < SHA1_HASH_SIZE; i++)
     Message_Digest[i] = (int8)((context->Intermediate_Hash[i>>2] >> 8
              * ( 3 - ( i & 0x03 ) )));
   return SHA_SUCCESS;
 }
References bzero, SHA1_CONTEXT::Computed, SHA1_CONTEXT::Corrupted, SHA1_CONTEXT::Intermediate_Hash, SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block, SHA1_HASH_SIZE, SHA1PadMessage(), SHA_NULL, and SHA_SUCCESS.
Referenced by check_scramble(), my_make_scrambled_password(), and scramble().
SHA1PadMessage()
static void SHA1PadMessage (SHA1_CONTEXT * context) static
Definition at line 375 of file sha1.c.
 {
   /*
     Check to see if the current message block is too small to hold
     the initial padding bits and length.  If so, we will pad the
     block, process it, and then continue padding into a second
     block.
   */
   int i=context->Message_Block_Index;
   if (i > 55)
   {
     context->Message_Block[i++] = 0x80;
     bzero((char*) &context->Message_Block[i],
       sizeof(context->Message_Block[0])*(64-i));
     context->Message_Block_Index=64;
     /* This function sets context->Message_Block_Index to zero  */
     SHA1ProcessMessageBlock(context);
     bzero((char*) &context->Message_Block[0],
       sizeof(context->Message_Block[0])*56);
     context->Message_Block_Index=56;
   }
   else
   {
     context->Message_Block[i++] = 0x80;
     bzero((char*) &context->Message_Block[i],
       sizeof(context->Message_Block[0])*(56-i));
     context->Message_Block_Index=56;
   }
   /*
     Store the message length as the last 8 octets
   */
   context->Message_Block[56] = (int8) (context->Length >> 56);
   context->Message_Block[57] = (int8) (context->Length >> 48);
   context->Message_Block[58] = (int8) (context->Length >> 40);
   context->Message_Block[59] = (int8) (context->Length >> 32);
   context->Message_Block[60] = (int8) (context->Length >> 24);
   context->Message_Block[61] = (int8) (context->Length >> 16);
   context->Message_Block[62] = (int8) (context->Length >> 8);
   context->Message_Block[63] = (int8) (context->Length);
   SHA1ProcessMessageBlock(context);
 }
References bzero, SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block, SHA1_CONTEXT::Message_Block_Index, and SHA1ProcessMessageBlock().
Referenced by mysql_sha1_result().
SHA1ProcessMessageBlock()
static void SHA1ProcessMessageBlock (SHA1_CONTEXT * context) static
Definition at line 272 of file sha1.c.
 {
   int       t;         /* Loop counter        */
   uint32    temp;          /* Temporary word value    */
   uint32    W[80];         /* Word sequence       */
   uint32    A, B, C, D, E;     /* Word buffers        */
   int idx;
   /*
     Initialize the first 16 words in the array W
   */
   for (t = 0; t < 16; t++)
   {
     idx=t*4;
     W[t] = context->Message_Block[idx] << 24;
     W[t] |= context->Message_Block[idx + 1] << 16;
     W[t] |= context->Message_Block[idx + 2] << 8;
     W[t] |= context->Message_Block[idx + 3];
   }
   for (t = 16; t < 80; t++)
   {
     W[t] = SHA1CircularShift(1,W[t-3] ^ W[t-8] ^ W[t-14] ^ W[t-16]);
   }
   A = context->Intermediate_Hash[0];
   B = context->Intermediate_Hash[1];
   C = context->Intermediate_Hash[2];
   D = context->Intermediate_Hash[3];
   E = context->Intermediate_Hash[4];
   for (t = 0; t < 20; t++)
   {
     temp= SHA1CircularShift(5,A) + ((B & C) | ((~B) & D)) + E + W[t] + K[0];
     E = D;
     D = C;
     C = SHA1CircularShift(30,B);
     B = A;
     A = temp;
   }
   for (t = 20; t < 40; t++)
   {
     temp = SHA1CircularShift(5,A) + (B ^ C ^ D) + E + W[t] + K[1];
     E = D;
     D = C;
     C = SHA1CircularShift(30,B);
     B = A;
     A = temp;
   }
   for (t = 40; t < 60; t++)
   {
     temp= (SHA1CircularShift(5,A) + ((B & C) | (B & D) | (C & D)) + E + W[t] +
        K[2]);
     E = D;
     D = C;
     C = SHA1CircularShift(30,B);
     B = A;
     A = temp;
   }
   for (t = 60; t < 80; t++)
   {
     temp = SHA1CircularShift(5,A) + (B ^ C ^ D) + E + W[t] + K[3];
     E = D;
     D = C;
     C = SHA1CircularShift(30,B);
     B = A;
     A = temp;
   }
   context->Intermediate_Hash[0] += A;
   context->Intermediate_Hash[1] += B;
   context->Intermediate_Hash[2] += C;
   context->Intermediate_Hash[3] += D;
   context->Intermediate_Hash[4] += E;
   context->Message_Block_Index = 0;
 }
References idx, SHA1_CONTEXT::Intermediate_Hash, K, SHA1_CONTEXT::Message_Block, SHA1_CONTEXT::Message_Block_Index, and SHA1CircularShift.
Referenced by mysql_sha1_input(), and SHA1PadMessage().
Variable Documentation
K
const uint32 K[] static
Initial value:
=
{
  0x5A827999,
  0x6ED9EBA1,
  0x8F1BBCDC,
  0xCA62C1D6
}
Definition at line 263 of file sha1.c.
Referenced by Acore::Crypto::SRP6::GetSessionVerifier(), AuthSession::HandleLogonProof(), AuthCrypt::Init(), WardenMac::Init(), Acore::Crypto::SRP6::SHA1Interleave(), SHA1ProcessMessageBlock(), and Acore::Crypto::SRP6::VerifyChallengeResponse().
sha_const_key
const uint32 sha_const_key[5]
Initial value:
=
{
  0x67452301,
  0xEFCDAB89,
  0x98BADCFE,
  0x10325476,
  0xC3D2E1F0
}
Definition at line 115 of file sha1.c.
Referenced by mysql_sha1_reset().