Azerotcore-wotlk: deps/jemalloc/src/extent_dss.c File Reference
extent_dss.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/extent_dss.h"
#include "jemalloc/internal/spin.h"
Macros
#define JEMALLOC_EXTENT_DSS_C_
Functions
static void * extent_dss_sbrk (intptr_t increment)
dss_prec_t extent_dss_prec_get (void)
bool extent_dss_prec_set (dss_prec_t dss_prec)
static void extent_dss_extending_start (void)
static void extent_dss_extending_finish (void)
static void * extent_dss_max_update (void *new_addr)
void * extent_alloc_dss (tsdn_t *tsdn, arena_t *arena, void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit)
static bool extent_in_dss_helper (void *addr, void *max)
bool extent_in_dss (void *addr)
bool extent_dss_mergeable (void *addr_a, void *addr_b)
void extent_dss_boot (void)
Variables
const char * opt_dss = DSS_DEFAULT
const char * dss_prec_names []
static atomic_u_t dss_prec_default
static void * dss_base
static atomic_b_t dss_extending
static atomic_b_t dss_exhausted
static atomic_p_t dss_max
Macro Definition Documentation
JEMALLOC_EXTENT_DSS_C_
#define JEMALLOC_EXTENT_DSS_C_
Definition at line 1 of file extent_dss.c.
Function Documentation
extent_alloc_dss()
void* extent_alloc_dss (tsdn_t * tsdn, arena_t * arena, void * new_addr, size_t size, size_t alignment, bool * zero, bool * commit)
Definition at line 110 of file extent_dss.c.
{
     extent_t *gap;
     cassert(have_dss);
     assert(size > 0);
     assert(alignment == ALIGNMENT_CEILING(alignment, PAGE));
     /*
      * sbrk() uses a signed increment argument, so take care not to
      * interpret a large allocation request as a negative increment.
      */
     if ((intptr_t)size < 0) {
         return NULL;
     }
     gap = extent_alloc(tsdn, arena);
     if (gap == NULL) {
         return NULL;
     }
     extent_dss_extending_start();
     if (!atomic_load_b(&dss_exhausted, ATOMIC_ACQUIRE)) {
         /*
          * The loop is necessary to recover from races with other
          * threads that are using the DSS for something other than
          * malloc.
          */
         while (true) {
             void *max_cur = extent_dss_max_update(new_addr);
             if (max_cur == NULL) {
                 goto label_oom;
             }
             /*
              * Compute how much page-aligned gap space (if any) is
              * necessary to satisfy alignment.  This space can be
              * recycled for later use.
              */
             void *gap_addr_page = (void *)(PAGE_CEILING(
                 (uintptr_t)max_cur));
             void *ret = (void *)ALIGNMENT_CEILING(
                 (uintptr_t)gap_addr_page, alignment);
             size_t gap_size_page = (uintptr_t)ret -
                 (uintptr_t)gap_addr_page;
             if (gap_size_page != 0) {
                 extent_init(gap, arena, gap_addr_page,
                     gap_size_page, false, SC_NSIZES,
                     arena_extent_sn_next(arena),
                     extent_state_active, false, true, true,
                     EXTENT_NOT_HEAD);
             }
             /*
              * Compute the address just past the end of the desired
              * allocation space.
              */
             void *dss_next = (void *)((uintptr_t)ret + size);
             if ((uintptr_t)ret < (uintptr_t)max_cur ||
                 (uintptr_t)dss_next < (uintptr_t)max_cur) {
                 goto label_oom; /* Wrap-around. */
             }
             /* Compute the increment, including subpage bytes. */
             void *gap_addr_subpage = max_cur;
             size_t gap_size_subpage = (uintptr_t)ret -
                 (uintptr_t)gap_addr_subpage;
             intptr_t incr = gap_size_subpage + size;
             assert((uintptr_t)max_cur + incr == (uintptr_t)ret +
                 size);
             /* Try to allocate. */
             void *dss_prev = extent_dss_sbrk(incr);
             if (dss_prev == max_cur) {
                 /* Success. */
                 atomic_store_p(&dss_max, dss_next,
                     ATOMIC_RELEASE);
                 extent_dss_extending_finish();
                 if (gap_size_page != 0) {
                     extent_dalloc_gap(tsdn, arena, gap);
                 } else {
                     extent_dalloc(tsdn, arena, gap);
                 }
                 if (!*commit) {
                     *commit = pages_decommit(ret, size);
                 }
                 if (*zero && *commit) {
                     extent_hooks_t *extent_hooks =
                         EXTENT_HOOKS_INITIALIZER;
                     extent_t extent;
                     extent_init(&extent, arena, ret, size,
                         size, false, SC_NSIZES,
                         extent_state_active, false, true,
                         true, EXTENT_NOT_HEAD);
                     if (extent_purge_forced_wrapper(tsdn,
                         arena, &extent_hooks, &extent, 0,
                         size)) {
                         memset(ret, 0, size);
                     }
                 }
                 return ret;
             }
             /*
              * Failure, whether due to OOM or a race with a raw
              * sbrk() call from outside the allocator.
              */
             if (dss_prev == (void *)-1) {
                 /* OOM. */
                 atomic_store_b(&dss_exhausted, true,
                     ATOMIC_RELEASE);
                 goto label_oom;
             }
         }
     }
 label_oom:
     extent_dss_extending_finish();
     extent_dalloc(tsdn, arena, gap);
     return NULL;
 }
References ALIGNMENT_CEILING, arena, arena_extent_sn_next, assert(), ATOMIC_ACQUIRE, ATOMIC_RELEASE, cassert(), dss_exhausted, dss_max, dss_prev, extent_alloc, extent_dalloc, extent_dalloc_gap, extent_dss_extending_finish(), extent_dss_extending_start(), extent_dss_max_update(), extent_dss_sbrk(), EXTENT_HOOKS_INITIALIZER, extent_init(), EXTENT_NOT_HEAD, extent_purge_forced_wrapper, extent_state_active, have_dss, memset, NULL, PAGE, PAGE_CEILING, pages_decommit, ret, SC_NSIZES, uintptr_t, and G3D::zero().
extent_dss_boot()
void extent_dss_boot (void)
Definition at line 262 of file extent_dss.c.
                       {
     cassert(have_dss);
     dss_base = extent_dss_sbrk(0);
     atomic_store_b(&dss_extending, false, ATOMIC_RELAXED);
     atomic_store_b(&dss_exhausted, dss_base == (void *)-1, ATOMIC_RELAXED);
     atomic_store_p(&dss_max, dss_base, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, cassert(), dss_base, dss_exhausted, dss_extending, dss_max, extent_dss_sbrk(), and have_dss.
extent_dss_extending_finish()
static void extent_dss_extending_finish (void) static
Definition at line 85 of file extent_dss.c.
{
     assert(atomic_load_b(&dss_extending, ATOMIC_RELAXED));
     atomic_store_b(&dss_extending, false, ATOMIC_RELEASE);
 }
References assert(), ATOMIC_RELAXED, ATOMIC_RELEASE, and dss_extending.
Referenced by extent_alloc_dss().
extent_dss_extending_start()
static void extent_dss_extending_start (void) static
Definition at line 72 of file extent_dss.c.
{
     spin_t spinner = SPIN_INITIALIZER;
     while (true) {
         bool expected = false;
         if (atomic_compare_exchange_weak_b(&dss_extending, &expected,
             true, ATOMIC_ACQ_REL, ATOMIC_RELAXED)) {
             break;
         }
         spin_adaptive(&spinner);
     }
 }
References ATOMIC_ACQ_REL, ATOMIC_RELAXED, dss_extending, spin_adaptive(), and SPIN_INITIALIZER.
Referenced by extent_alloc_dss().
extent_dss_max_update()
static void* extent_dss_max_update (void * new_addr) static
Definition at line 92 of file extent_dss.c.
{
     /*
      * Get the current end of the DSS as max_cur and assure that dss_max is
      * up to date.
      */
     void *max_cur = extent_dss_sbrk(0);
     if (max_cur == (void *)-1) {
         return NULL;
     }
     atomic_store_p(&dss_max, max_cur, ATOMIC_RELEASE);
     /* Fixed new_addr can only be supported if it is at the edge of DSS. */
     if (new_addr != NULL && max_cur != new_addr) {
         return NULL;
     }
     return max_cur;
 }
References ATOMIC_RELEASE, dss_max, extent_dss_sbrk(), and NULL.
Referenced by extent_alloc_dss().
extent_dss_mergeable()
bool extent_dss_mergeable (void * addr_a, void * addr_b)
Definition at line 246 of file extent_dss.c.
{
     void *max;
     cassert(have_dss);
     if ((uintptr_t)addr_a < (uintptr_t)dss_base && (uintptr_t)addr_b <
         (uintptr_t)dss_base) {
         return true;
     }
     max = atomic_load_p(&dss_max, ATOMIC_ACQUIRE);
     return (extent_in_dss_helper(addr_a, max) ==
         extent_in_dss_helper(addr_b, max));
 }
References ATOMIC_ACQUIRE, cassert(), dss_base, dss_max, extent_in_dss_helper(), have_dss, and max.
extent_dss_prec_get()
dss_prec_t extent_dss_prec_get (void)
Definition at line 52 of file extent_dss.c.
{
     dss_prec_t ret;
     if (!have_dss) {
         return dss_prec_disabled;
     }
     ret = (dss_prec_t)atomic_load_u(&dss_prec_default, ATOMIC_ACQUIRE);
     return ret;
 }
References ATOMIC_ACQUIRE, dss_prec_default, dss_prec_disabled, have_dss, and ret.
extent_dss_prec_set()
bool extent_dss_prec_set (dss_prec_t dss_prec)
Definition at line 63 of file extent_dss.c.
{
     if (!have_dss) {
         return (dss_prec != dss_prec_disabled);
     }
     atomic_store_u(&dss_prec_default, (unsigned)dss_prec, ATOMIC_RELEASE);
     return false;
 }
References ATOMIC_RELEASE, dss_prec_default, dss_prec_disabled, and have_dss.
extent_dss_sbrk()
static void* extent_dss_sbrk (intptr_t increment) static
Definition at line 42 of file extent_dss.c.
{
 #ifdef JEMALLOC_DSS
     return sbrk(increment);
 #else
     not_implemented();
     return NULL;
 #endif
 }
References not_implemented, and NULL.
Referenced by extent_alloc_dss(), extent_dss_boot(), and extent_dss_max_update().
extent_in_dss()
bool extent_in_dss (void * addr)
Definition at line 238 of file extent_dss.c.
{
     cassert(have_dss);
     return extent_in_dss_helper(addr, atomic_load_p(&dss_max,
         ATOMIC_ACQUIRE));
 }
References ATOMIC_ACQUIRE, cassert(), dss_max, extent_in_dss_helper(), and have_dss.
extent_in_dss_helper()
static bool extent_in_dss_helper (void * addr, void * max) static
Definition at line 232 of file extent_dss.c.
{
     return ((uintptr_t)addr >= (uintptr_t)dss_base && (uintptr_t)addr <
         (uintptr_t)max);
 }
References dss_base, and max.
Referenced by extent_dss_mergeable(), and extent_in_dss().
Variable Documentation
dss_base
void* dss_base static
Definition at line 31 of file extent_dss.c.
Referenced by extent_dss_boot(), extent_dss_mergeable(), and extent_in_dss_helper().
dss_exhausted
atomic_b_t dss_exhausted static
Definition at line 35 of file extent_dss.c.
Referenced by extent_alloc_dss(), and extent_dss_boot().
dss_extending
atomic_b_t dss_extending static
Definition at line 33 of file extent_dss.c.
Referenced by extent_dss_boot(), extent_dss_extending_finish(), and extent_dss_extending_start().
dss_max
atomic_p_t dss_max static
Definition at line 37 of file extent_dss.c.
Referenced by extent_alloc_dss(), extent_dss_boot(), extent_dss_max_update(), extent_dss_mergeable(), and extent_in_dss().
dss_prec_default
atomic_u_t dss_prec_default static
Initial value:
= ATOMIC_INIT(
    (unsigned)DSS_PREC_DEFAULT)
Definition at line 27 of file extent_dss.c.
Referenced by extent_dss_prec_get(), and extent_dss_prec_set().
dss_prec_names
const char* dss_prec_names[]
Initial value:
= {
    "disabled",
    "primary",
    "secondary",
    "N/A"
}
Definition at line 14 of file extent_dss.c.
opt_dss
const char* opt_dss = DSS_DEFAULT
Definition at line 12 of file extent_dss.c.