Azerotcore-wotlk: npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI Struct Reference
npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI Struct Reference
Public Member Functions
npc_ulduar_aerial_command_unitAI (Creature *pCreature)
void Reset () override
void AttackStart (Unit *who) override
void SetData (uint32 id, uint32 value) override
void DoAction (int32 param) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void SpellHit (Unit *, const SpellInfo *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
bool bIsEvading
uint8 Phase
bool immobilized
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1620 of file boss_mimiron.cpp.
Constructor & Destructor Documentation
npc_ulduar_aerial_command_unitAI()
npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::npc_ulduar_aerial_command_unitAI (Creature * pCreature) inline
Definition at line 1622 of file boss_mimiron.cpp.
                                                               : ScriptedAI(pCreature), summons(me)
         {
             pInstance = me->GetInstanceScript();
             bIsEvading = false;
             immobilized = false;
             me->SetDisableGravity(true);
         }
References bIsEvading, WorldObject::GetInstanceScript(), immobilized, ScriptedAI::me, pInstance, and Creature::SetDisableGravity().
Member Function Documentation
AttackStart()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1644 of file boss_mimiron.cpp.
         {
             if (who)
                 me->Attack(who, true); // skip following
         }
References Unit::Attack(), and ScriptedAI::me.
Referenced by SetData().
DamageTaken()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1701 of file boss_mimiron.cpp.
         {
             if (damage >= me->GetHealth() || me->GetHealth() < 15000)
             {
                 damage = 0;
                 if (me->GetReactState() == REACT_PASSIVE)
                     return;
                 me->SetReactState(REACT_PASSIVE);
                 if (Phase == 3)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         me->GetMotionMaster()->Clear();
                         me->StopMoving();
                         me->AttackStop();
                         me->SetReactState(REACT_PASSIVE);
                         SetData(1, 0);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         me->MonsterMoveWithSpeed(2744.65f, 2569.46f, 381.34f, me->GetDistance(2744.65f, 2569.46f, 381.34f));
                         me->UpdatePosition(2744.65f, 2569.46f, 381.34f, M_PI, false);
                         if (Creature* c = GetMimiron())
                             c->AI()->SetData(0, 3);
                     }
                 }
                 else if (Phase == 4)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         me->CastSpell(me, SPELL_SELF_REPAIR, false);
                         if (Creature* c = GetMimiron())
{
                             if (c->AI()->GetData(1))
                                 me->CastSpell(me, SPELL_EMERGENCY_MODE, true);
                             if (c->AI()->GetData(2))
                                 me->CastSpell(me, SPELL_BERSERK, true);
                             c->AI()->SetData(0, 6);
                         }
                     }
                 }
             }
         }
References Unit::AttackStop(), Unit::CastSpell(), MotionMaster::Clear(), WorldObject::GetDistance(), Unit::GetHealth(), GetMimiron, Unit::GetMotionMaster(), Creature::GetReactState(), Object::HasFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::MonsterMoveWithSpeed(), REACT_PASSIVE, Unit::RemoveAllAurasExceptType(), SetData(), Object::SetFlag(), Creature::SetReactState(), SPELL_AURA_CONTROL_VEHICLE, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_SELF_REPAIR, Unit::StopMoving(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and Unit::UpdatePosition().
DoAction()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1695 of file boss_mimiron.cpp.
         {
             if (param == 1337)
                 summons.DespawnAll();
         }
References SummonList::DespawnAll(), and summons.
EnterEvadeMode()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1900 of file boss_mimiron.cpp.
         {
             if (bIsEvading)
                 return;
             bIsEvading = true;
             me->RemoveAllAuras();
             me->ExitVehicle();
             _EnterEvadeMode();
             Reset();
             if (Creature* mimiron = GetMimiron())
                 mimiron->AI()->EnterEvadeMode();
             bIsEvading = false;
         }
References CreatureAI::_EnterEvadeMode(), bIsEvading, Unit::ExitVehicle(), GetMimiron, ScriptedAI::me, Unit::RemoveAllAuras(), and Reset().
JustSummoned()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1916 of file boss_mimiron.cpp.
         {
             summons.Summon(s);
             if (s->GetEntry() == NPC_BOMB_BOT)
                 s->m_positionZ = 364.34f;
         }
References Object::GetEntry(), Position::m_positionZ, NPC_BOMB_BOT, SummonList::Summon(), and summons.
KilledUnit()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1866 of file boss_mimiron.cpp.
         {
             if( who->GetTypeId() == TYPEID_PLAYER )
                 if( Creature* c = GetMimiron() )
                 {
                     if( Phase == 3 )
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_ACU_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_HEAD_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_ACU_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_HEAD_SLAY_2);
                         }
                     }
                     else
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_VOLTRON_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_VOLTRON_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_2);
                         }
                     }
                 }
         }
References GetMimiron, Object::GetTypeId(), LANG_UNIVERSAL, SOUND_HEAD_SLAY_1, SOUND_HEAD_SLAY_2, SOUND_VOLTRON_SLAY_1, SOUND_VOLTRON_SLAY_2, TEXT_ACU_SLAIN_1, TEXT_ACU_SLAIN_2, TEXT_VOLTRON_SLAIN_1, TEXT_VOLTRON_SLAIN_2, and TYPEID_PLAYER.
MoveInLineOfSight()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1864 of file boss_mimiron.cpp.
 {}
Reset()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1637 of file boss_mimiron.cpp.
         {
             Phase = 0;
             events.Reset();
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), and summons.
Referenced by EnterEvadeMode().
SetData()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 1650 of file boss_mimiron.cpp.
         {
             if (id == 1) // setting phase to start fighting
             {
                 switch (value)
                 {
                     case 0:
                         Phase = 0;
                         events.Reset();
                         immobilized = false;
                         break;
                     case 3:
                         Phase = 3;
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         if (Unit* target = SelectTargetFromPlayerList(75.0f))
                             AttackStart(target);
                         DoZoneInCombat();
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_PLASMA_BALL, 0);
                         events.ScheduleEvent(EVENT_SUMMON_BOMB_BOT, 15000);
                         events.ScheduleEvent(EVENT_SUMMON_ASSAULT_BOT, 1000);
                         events.ScheduleEvent(EVENT_SUMMON_JUNK_BOT, 10000);
                         if (Creature* c = GetMimiron())
                             if (c->AI()->GetData(1))
                                 events.ScheduleEvent(EVENT_SUMMON_EMERGENCY_FIRE_BOTS, 0);
                         break;
                     case 4:
                         me->SetReactState(REACT_AGGRESSIVE);
                         DoResetThreat();
                         Phase = 4;
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         if (Unit* target = SelectTargetFromPlayerList(75.0f))
                             AttackStart(target);
                         DoZoneInCombat();
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_PLASMA_BALL, 0);
                 }
             }
             else if (id == 2 && !immobilized && Phase == 3) // magnetic core
             {
                 immobilized = true;
                 events.ScheduleEvent(EVENT_MAGNETIC_CORE_PULL_DOWN, 2000);
             }
         }
References AttackStart(), ScriptedAI::DoResetThreat(), CreatureAI::DoZoneInCombat(), EVENT_MAGNETIC_CORE_PULL_DOWN, EVENT_SPELL_PLASMA_BALL, EVENT_SUMMON_ASSAULT_BOT, EVENT_SUMMON_BOMB_BOT, EVENT_SUMMON_EMERGENCY_FIRE_BOTS, EVENT_SUMMON_JUNK_BOT, GetMimiron, immobilized, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), ScriptedAI::SelectTargetFromPlayerList(), Creature::SetReactState(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by DamageTaken(), and UpdateAI().
SpellHit()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1928 of file boss_mimiron.cpp.
         {
             if( spell->Id == SPELL_SELF_REPAIR )
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetReactState(), SPELL_SELF_REPAIR, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
SummonedCreatureDespawn()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1923 of file boss_mimiron.cpp.
         {
             summons.Despawn(s);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1750 of file boss_mimiron.cpp.
         {
             if (!UpdateVictim())
                 return;
             // following :D
             if( Phase == 3 && !immobilized )
                 if( Unit* victim = me->GetVictim() )
                     if( me->GetExactDist2d(victim) > 25.0f )
                     {
                         float angle = victim->GetAngle(me->GetPositionX(), me->GetPositionY());
                         me->SetOrientation( me->GetAngle(victim->GetPositionX(), victim->GetPositionY()) );
                         float x = victim->GetPositionX() + 15.0f * cos(angle);
                         float y = victim->GetPositionY() + 15.0f * sin(angle);
                         // check if there's magnetic core in line of movement
                         Creature* mc = nullptr;
                         std::list<Creature*> cl;
                         me->GetCreaturesWithEntryInRange(cl, me->GetExactDist2d(victim), NPC_MAGNETIC_CORE);
                         for( std::list<Creature*>::iterator itr = cl.begin(); itr != cl.end(); ++itr )
{
                             if ((*itr)->IsInBetween(me, victim, 4.0f) && (*itr)->GetExactDist2d(victim) >= 10.0f) // don't come very close just because there's a magnetic core
{
                                 x = (*itr)->GetPositionX();
                                 y = (*itr)->GetPositionY();
                                 mc = (*itr);
                                 break;
                             }
                         }
                         float speed = me->GetExactDist(x, y, 381.34f);
                         me->MonsterMoveWithSpeed(x, y, 381.34f, speed);
                         me->UpdatePosition(x, y, 381.34f, me->GetAngle(victim), false);
                         if (mc)
{
                             mc->AI()->SetData(0, 0);
                             SetData(2, 1);
                         }
                     }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_PLASMA_BALL:
                     if( !immobilized )
                     {
                         if (Phase == 3)
{
                             if( Unit* victim = me->GetVictim() )
                                 me->CastSpell(victim, SPELL_PLASMA_BALL, false);
                         }
                         else
{
                             if (Unit* victim = SelectTarget(SELECT_TARGET_RANDOM, 0, 27.5f, true))
{
                                 me->SetFacingToObject(victim);
                                 me->CastSpell(victim, SPELL_PLASMA_BALL, false);
                             }
                         }
                     }
                     events.RepeatEvent(3000);
                     break;
                 case EVENT_SUMMON_BOMB_BOT:
                     if( !immobilized )
                         me->CastSpell(me, SPELL_SUMMON_BOMB_BOT, false);
                     events.RepeatEvent(15000);
                     break;
                 case EVENT_SUMMON_ASSAULT_BOT:
                     if( GameObject* pad = me->FindNearestGameObject(RAND(194742, 194746, 194745), 200.0f) )
                         if (Creature* trigger = me->SummonCreature(NPC_BOT_SUMMON_TRIGGER, *pad, TEMPSUMMON_TIMED_DESPAWN, 15000))
                             trigger->AI()->DoAction(2);
                     events.RepeatEvent(30000);
                     break;
                 case EVENT_SUMMON_JUNK_BOT:
                     if( GameObject* pad = me->FindNearestGameObject(RAND(194741, 194744, 194747), 200.0f) )
                         if (Creature* trigger = me->SummonCreature(NPC_BOT_SUMMON_TRIGGER, *pad, TEMPSUMMON_TIMED_DESPAWN, 15000))
                             trigger->AI()->DoAction(1);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_SUMMON_EMERGENCY_FIRE_BOTS:
                     {
                         uint32 ids[3] = {194740, 194743, 194748};
                         for( uint8 i = 0; i < 3; ++i )
                             if( GameObject* pad = me->FindNearestGameObject(ids[i], 200.0f) )
                                 if (Creature* trigger = me->SummonCreature(NPC_BOT_SUMMON_TRIGGER, *pad, TEMPSUMMON_MANUAL_DESPAWN))
                                     trigger->AI()->DoAction(3);
                         events.RepeatEvent(45000);
                     }
                     break;
                 case EVENT_MAGNETIC_CORE_PULL_DOWN:
                     me->CastSpell(me, SPELL_MAGNETIC_CORE, true);
                     me->CastSpell(me, SPELL_SPINNING, true);
                     me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), 365.34f, me->GetExactDist(me->GetPositionX(), me->GetPositionY(), 365.34f));
                     me->UpdatePosition(me->GetPositionX(), me->GetPositionY(), 365.34f, me->GetOrientation(), false);
                     events.ScheduleEvent(EVENT_MAGNETIC_CORE_FREE, 20000);
                     break;
                 case EVENT_MAGNETIC_CORE_FREE:
                     me->RemoveAura(SPELL_SPINNING);
                     me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), 381.34f, me->GetDistance(me->GetPositionX(), me->GetPositionY(), 381.34f));
                     me->UpdatePosition(me->GetPositionX(), me->GetPositionY(), 381.34f, me->GetOrientation(), false);
                     events.ScheduleEvent(EVENT_MAGNETIC_CORE_REMOVE_IMMOBILIZE, 1000);
                     break;
                 case EVENT_MAGNETIC_CORE_REMOVE_IMMOBILIZE:
                     immobilized = false;
                     break;
             }
         }
References Creature::AI(), Unit::CastSpell(), EVENT_MAGNETIC_CORE_FREE, EVENT_MAGNETIC_CORE_PULL_DOWN, EVENT_MAGNETIC_CORE_REMOVE_IMMOBILIZE, EVENT_SPELL_PLASMA_BALL, EVENT_SUMMON_ASSAULT_BOT, EVENT_SUMMON_BOMB_BOT, EVENT_SUMMON_EMERGENCY_FIRE_BOTS, EVENT_SUMMON_JUNK_BOT, WorldObject::FindNearestGameObject(), Position::GetAngle(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistance(), Position::GetExactDist(), Position::GetExactDist2d(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Unit::GetVictim(), Unit::HasUnitState(), immobilized, ScriptedAI::me, Unit::MonsterMoveWithSpeed(), NPC_BOT_SUMMON_TRIGGER, NPC_MAGNETIC_CORE, RAND(), Unit::RemoveAura(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SetData(), UnitAI::SetData(), Unit::SetFacingToObject(), Position::SetOrientation(), SPELL_MAGNETIC_CORE, SPELL_PLASMA_BALL, SPELL_SPINNING, SPELL_SUMMON_BOMB_BOT, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, Unit::UpdatePosition(), and CreatureAI::UpdateVictim().
Member Data Documentation
bIsEvading
bool npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::bIsEvading
Definition at line 1633 of file boss_mimiron.cpp.
Referenced by EnterEvadeMode(), and npc_ulduar_aerial_command_unitAI().
events
EventMap npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::events
Definition at line 1631 of file boss_mimiron.cpp.
immobilized
bool npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::immobilized
Definition at line 1635 of file boss_mimiron.cpp.
Referenced by npc_ulduar_aerial_command_unitAI(), SetData(), and UpdateAI().
Phase
uint8 npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::Phase
Definition at line 1634 of file boss_mimiron.cpp.
pInstance
InstanceScript* npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::pInstance
Definition at line 1630 of file boss_mimiron.cpp.
Referenced by npc_ulduar_aerial_command_unitAI().
summons
SummonList npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::summons
Definition at line 1632 of file boss_mimiron.cpp.
Referenced by DoAction(), JustSummoned(), Reset(), and SummonedCreatureDespawn().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp