Azerotcore-wotlk: npc_pos_after_first_boss::npc_pos_after_first_bossAI Struct Reference
npc_pos_after_first_boss::npc_pos_after_first_bossAI Struct Reference
Public Member Functions
npc_pos_after_first_bossAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 502 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
npc_pos_after_first_bossAI()
npc_pos_after_first_boss::npc_pos_after_first_bossAI::npc_pos_after_first_bossAI (Creature * creature) inline
Definition at line 504 of file pit_of_saron.cpp.
                                                        : NullCreatureAI(creature)
         {
             pInstance = me->GetInstanceScript();
             me->GetMotionMaster()->MovePoint(1, 695.03f, -149.86f, 527.89f);
         }
References WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MovePoint(), and pInstance.
Member Function Documentation
MovementInform()
void npc_pos_after_first_boss::npc_pos_after_first_bossAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 518 of file pit_of_saron.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch(id)
             {
                 case 1:
                     events.RescheduleEvent(id, 0);
                     break;
             }
         }
References POINT_MOTION_TYPE.
Reset()
void npc_pos_after_first_boss::npc_pos_after_first_bossAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 513 of file pit_of_saron.cpp.
         {
             events.Reset();
         }
UpdateAI()
void npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 530 of file pit_of_saron.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     {
                         if (pInstance)
                             if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_GARFROST_GUID)))
{
                                 float angle = c->GetAngle(me);
                                 float x = c->GetPositionX() + cos(angle) * 12.0f;
                                 float y = c->GetPositionY() + sin(angle) * 12.0f;
                                 me->GetMotionMaster()->MovePoint(2, x, y, c->GetPositionZ());
                             }
                         uint8 i = 0;
                         while (FBSData[i].entry)
{
                             if (Creature* c = me->SummonCreature(FBSData[i].entry, 688.69f + i * 1.8f, FBSSpawnPos.GetPositionY() + (float)irand(-2, 2), FBSSpawnPos.GetPositionZ(), 3 * M_PI / 2))
                                 c->GetMotionMaster()->MovePath(FBSData[i].pathId, false);
                             ++i;
                         }
                         events.RescheduleEvent(2, 3000);
                         break;
                     }
                 case 2:
                     if (Creature* c = me->SummonCreature(NPC_TYRANNUS_VOICE, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() - 10.0f, me->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN, 1))
                         c->AI()->Talk(SAY_TYRANNUS_GARFROST);
                     events.RescheduleEvent(3, 4000);
                     break;
                 case 3:
                     Talk(SAY_GENERAL_GARFROST);
                     break;
             }
         }
References DATA_GARFROST_GUID, FBSPosition::entry, FBSData, FBSSpawnPos, Map::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), InstanceScript::instance, irand(), CreatureAI::me, MotionMaster::MovePoint(), NPC_TYRANNUS_VOICE, pInstance, SAY_GENERAL_GARFROST, SAY_TYRANNUS_GARFROST, WorldObject::SummonCreature(), CreatureAI::Talk(), and TEMPSUMMON_TIMED_DESPAWN.
Member Data Documentation
events
EventMap npc_pos_after_first_boss::npc_pos_after_first_bossAI::events
Definition at line 510 of file pit_of_saron.cpp.
pInstance
InstanceScript* npc_pos_after_first_boss::npc_pos_after_first_bossAI::pInstance
Definition at line 511 of file pit_of_saron.cpp.
Referenced by npc_pos_after_first_bossAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp