Azerotcore-wotlk: G3D::Color1 Class Reference
G3D::Color1 Class Reference
#include <Color1.h>
Public Member Functions
Color1 ()
Color1 (class BinaryInput &bi)
Color1 (float v)
Color1 (unorm8 v)
bool isZero () const
bool isOne () const
class Color3 rgb () const
Color1 (const class Color1unorm8 &other)
void serialize (class BinaryOutput &bo) const
void deserialize (class BinaryInput &bi)
Color1 operator+ (const Color1 &other) const
Color1 operator+ (const float other) const
Color1 & operator+= (const Color1 other)
Color1 & operator-= (const Color1 other)
Color1 operator- (const Color1 &other) const
Color1 operator- (const float other) const
Color1 operator- () const
Color1 operator* (const Color1 &other) const
Color1 & operator*= (const Color1 other)
Color1 & operator*= (const float other)
Color1 & operator/= (const float other)
Color1 & operator/= (const Color1 other)
Color1 operator* (const float other) const
Color1 operator/ (const Color1 &other) const
Color1 operator/ (const float other) const
Color1 max (const Color1 &other) const
Color1 min (const Color1 &other) const
Color1 lerp (const Color1 &other, float a) const
size_t hashCode () const
Static Public Member Functions
static const Color1 & one ()
static const Color1 & zero ()
Public Attributes
float value
Private Member Functions
bool operator< (const Color1 &) const
bool operator> (const Color1 &) const
bool operator<= (const Color1 &) const
bool operator>= (const Color1 &) const
Detailed Description
Monochrome color.
Definition at line 28 of file Color1.h.
Constructor & Destructor Documentation
Color1() [1/5]
G3D::Color1::Color1 () inline
Initializes to 0
Definition at line 42 of file Color1.h.
 : value(0) {}
Referenced by lerp(), max(), min(), operator*(), operator+(), operator-(), and operator/().
Color1() [2/5]
G3D::Color1::Color1 (class BinaryInput & bi)
Definition at line 33 of file Color1.cpp.
{
     deserialize(bi);
 }
References deserialize().
Color1() [3/5]
G3D::Color1::Color1 (float v) inline explicit
Definition at line 46 of file Color1.h.
                                     : value(v) {
     }
Color1() [4/5]
G3D::Color1::Color1 (unorm8 v) inline explicit
Definition at line 49 of file Color1.h.
                                      : value(v) {
     }
Color1() [5/5]
G3D::Color1::Color1 (const class Color1unorm8 & other) explicit
Definition at line 53 of file Color1.cpp.
{
     value = other.value;
 }
References value< Context >::value().
Member Function Documentation
deserialize()
void G3D::Color1::deserialize (class BinaryInput & bi)
Definition at line 43 of file Color1.cpp.
{
     value = bi.readFloat32();
 }
References G3D::BinaryInput::readFloat32().
Referenced by Color1().
hashCode()
size_t G3D::Color1::hashCode () const inline
Definition at line 153 of file Color1.h.
{
         return (size_t)(value * 0xFFFFFF);
     }
Referenced by HashTrait< G3D::Color1 >::hashCode().
isOne()
bool G3D::Color1::isOne () const inline
Definition at line 56 of file Color1.h.
{
         return value == 1.0f;
     }
isZero()
bool G3D::Color1::isZero () const inline
Definition at line 52 of file Color1.h.
{
         return value == 0.0f;
     }
lerp()
Color1 G3D::Color1::lerp (const Color1 & other, float a) const inline
Definition at line 148 of file Color1.h.
{
         return Color1(value + (other.value - value) * a);
     }
References mpq::a, Color1(), and value.
Referenced by G3D::lerp().
max()
Color1 G3D::Color1::max (const Color1 & other) const inline
Definition at line 140 of file Color1.h.
{
         return Color1(G3D::max(value, other.value));
     }
References Color1(), G3D::max(), and value.
min()
Color1 G3D::Color1::min (const Color1 & other) const inline
Definition at line 144 of file Color1.h.
{
         return Color1(G3D::min(value, other.value));
     }
References Color1(), G3D::min(), and value.
one()
const Color1 & G3D::Color1::one () static
Definition at line 21 of file Color1.cpp.
{
     static const Color1 x(1.0f);
     return x;
 }
References G3D::x.
operator*() [1/2]
Color1 G3D::Color1::operator* (const Color1 & other) const inline
Definition at line 104 of file Color1.h.
{
         return Color1(value * other.value);
     }
References Color1(), and value.
operator*() [2/2]
Color1 G3D::Color1::operator* (const float other) const inline
Definition at line 128 of file Color1.h.
{
         return Color1(value * other);
     }
References Color1().
operator*=() [1/2]
Color1& G3D::Color1::operator*= (const Color1 other) inline
Definition at line 108 of file Color1.h.
{
         value *= other.value;
         return *this;
     }
References value.
operator*=() [2/2]
Color1& G3D::Color1::operator*= (const float other) inline
Definition at line 113 of file Color1.h.
{
         value *= other;
         return *this;
     }
operator+() [1/2]
Color1 G3D::Color1::operator+ (const Color1 & other) const inline
Definition at line 72 of file Color1.h.
{
         return Color1(value + other.value);
     }
References Color1(), and value.
operator+() [2/2]
Color1 G3D::Color1::operator+ (const float other) const inline
Deprecated:
Definition at line 77 of file Color1.h.
{
         return Color1(value + other);
     }
References Color1().
operator+=()
Color1& G3D::Color1::operator+= (const Color1 other) inline
Definition at line 81 of file Color1.h.
{
         value += other.value;
         return *this;
     }
References value.
operator-() [1/3]
Color1 G3D::Color1::operator- () const inline
Definition at line 100 of file Color1.h.
{
         return Color1(-value);
     }
References Color1().
operator-() [2/3]
Color1 G3D::Color1::operator- (const Color1 & other) const inline
Definition at line 91 of file Color1.h.
{
         return Color1(value - other.value);
     }
References Color1(), and value.
operator-() [3/3]
Color1 G3D::Color1::operator- (const float other) const inline
Deprecated:
Definition at line 96 of file Color1.h.
{
         return Color1(value - other);
     }
References Color1().
operator-=()
Color1& G3D::Color1::operator-= (const Color1 other) inline
Definition at line 86 of file Color1.h.
{
         value -= other.value;
         return *this;
     }
References value.
operator/() [1/2]
Color1 G3D::Color1::operator/ (const Color1 & other) const inline
Definition at line 132 of file Color1.h.
{
         return Color1(value / other.value);
     }
References Color1(), and value.
operator/() [2/2]
Color1 G3D::Color1::operator/ (const float other) const inline
Definition at line 136 of file Color1.h.
{
         return Color1(value / other);
     }
References Color1().
operator/=() [1/2]
Color1& G3D::Color1::operator/= (const Color1 other) inline
Definition at line 123 of file Color1.h.
{
         value /= other.value;
         return *this;
     }
References value.
operator/=() [2/2]
Color1& G3D::Color1::operator/= (const float other) inline
Definition at line 118 of file Color1.h.
{
         value /= other;
         return *this;
     }
operator<()
bool G3D::Color1::operator< (const Color1 &) const private
operator<=()
bool G3D::Color1::operator<= (const Color1 &) const private
operator>()
bool G3D::Color1::operator> (const Color1 &) const private
operator>=()
bool G3D::Color1::operator>= (const Color1 &) const private
rgb()
Color3 G3D::Color1::rgb () const
Returns the value three times
Definition at line 38 of file Color1.cpp.
{
     return Color3(value, value, value);
 }
serialize()
void G3D::Color1::serialize (class BinaryOutput & bo) const
Definition at line 48 of file Color1.cpp.
{
     bo.writeFloat32(value);
 }
References G3D::BinaryOutput::writeFloat32().
zero()
const Color1 & G3D::Color1::zero () static
Definition at line 27 of file Color1.cpp.
{
     const static Color1 x(0.0f);
     return x;
 }
References G3D::x.
Member Data Documentation
value
float G3D::Color1::value
Definition at line 37 of file Color1.h.
Referenced by G3D::Image3::copyArray(), G3D::Image4::copyArray(), lerp(), max(), min(), operator*(), G3D::operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), and operator/=().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Color1.h
deps/g3dlite/source/Color1.cpp