Azerotcore-wotlk: src/server/game/Entities/Player/Player.h File Reference
Player.h File Reference
#include "ArenaTeam.h"
#include "Battleground.h"
#include "DatabaseEnvFwd.h"
#include "DBCStores.h"
#include "GroupReference.h"
#include "InstanceSaveMgr.h"
#include "Item.h"
#include "KillRewarder.h"
#include "MapReference.h"
#include "ObjectMgr.h"
#include "Optional.h"
#include "PetDefines.h"
#include "PlayerTaxi.h"
#include "QuestDef.h"
#include "SpellMgr.h"
#include "TradeData.h"
#include "Unit.h"
#include "WorldSession.h"
#include <string>
#include <vector>
Classes
struct PlayerSpell
struct PlayerTalent
struct SpellModifier
struct SpellCooldown
struct ActionButton
struct PlayerCreateInfoItem
struct PlayerClassLevelInfo
struct PlayerClassInfo
struct PlayerLevelInfo
struct PlayerCreateInfoAction
struct PlayerCreateInfoSkill
struct PlayerInfo
struct PvPInfo
struct DuelInfo
struct Areas
struct RuneInfo
struct Runes
struct EnchantDuration
struct SkillStatusData
struct EquipmentSet
struct ItemPosCount
struct ProgressionRequirement
struct DungeonProgressionRequirements
struct BGData
struct EntryPointData
class Player
Macros
#define PLAYER_MAX_SKILLS 127
#define PLAYER_MAX_DAILY_QUESTS 25
#define PLAYER_EXPLORED_ZONES_SIZE 128
#define DEATH_EXPIRE_STEP (5*MINUTE)
#define MAX_DEATH_COUNT 3
#define PLAYER_SKILL_INDEX(x) (PLAYER_SKILL_INFO_1_1 + ((x)*3))
#define PLAYER_SKILL_VALUE_INDEX(x) (PLAYER_SKILL_INDEX(x)+1)
#define PLAYER_SKILL_BONUS_INDEX(x) (PLAYER_SKILL_INDEX(x)+2)
#define SKILL_VALUE(x) PAIR32_LOPART(x)
#define SKILL_MAX(x) PAIR32_HIPART(x)
#define MAKE_SKILL_VALUE(v, m) MAKE_PAIR32(v, m)
#define SKILL_TEMP_BONUS(x) int16(PAIR32_LOPART(x))
#define SKILL_PERM_BONUS(x) int16(PAIR32_HIPART(x))
#define MAKE_SKILL_BONUS(t, p) MAKE_PAIR32(t, p)
#define SPEC_MASK_ALL 255
#define ACTION_BUTTON_ACTION(X) (uint32(X) & 0x00FFFFFF)
#define ACTION_BUTTON_TYPE(X) ((uint32(X) & 0xFF000000) >> 24)
#define MAX_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
#define MAX_ACTION_BUTTONS 144
#define MAX_RUNES 6
#define MAX_DRUNKEN 4
#define PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET (PLAYER_FIELD_BYTES_2_OFFSET_OVERRIDE_SPELLS_ID / 2)
#define KNOWN_TITLES_SIZE 3
#define MAX_TITLE_INDEX (KNOWN_TITLES_SIZE*64)
#define MAX_TIMERS 3
#define DISABLED_MIRROR_TIMER -1
#define MAX_QUEST_OFFSET 5
#define INVENTORY_SLOT_BAG_0 255
#define MAX_EQUIPMENT_SET_INDEX 10
#define MAX_PLAYED_TIME_INDEX 2
#define MAX_PLAYER_SUMMON_DELAY (2*MINUTE)
#define MAX_MONEY_AMOUNT (0x7FFFFFFF-1)
Typedefs
typedef std::deque< Mail * > PlayerMails
typedef void(* bgZoneRef) (Battleground *, WorldPacket &)
typedef std::unordered_map< uint32, PlayerTalent * > PlayerTalentMap
typedef std::unordered_map< uint32, PlayerSpell * > PlayerSpellMap
typedef std::list< SpellModifier * > SpellModList
typedef GuidList WhisperListContainer
typedef std::map< uint32, SpellCooldown > SpellCooldowns
typedef std::unordered_map< uint32, time_t > InstanceTimeMap
typedef std::map< uint8, ActionButton > ActionButtonList
typedef std::list< PlayerCreateInfoItem > PlayerCreateInfoItems
typedef std::list< uint32 > PlayerCreateInfoSpells
typedef std::list< PlayerCreateInfoAction > PlayerCreateInfoActions
typedef std::list< PlayerCreateInfoSkill > PlayerCreateInfoSkills
typedef std::list< EnchantDuration > EnchantDurationList
typedef std::list< Item * > ItemDurationList
typedef std::map< uint32, QuestStatusData > QuestStatusMap
typedef std::unordered_set< uint32 > RewardedQuestSet
typedef std::map< uint32, bool > QuestStatusSaveMap
typedef std::unordered_map< uint32, SkillStatusData > SkillStatusMap
typedef std::map< uint32, EquipmentSet > EquipmentSets
typedef std::vector< ItemPosCount > ItemPosCountVec
Enumerations
enum SpellModType { SPELLMOD_FLAT = 107 , SPELLMOD_PCT = 108 }
enum PlayerUnderwaterState {
UNDERWATER_NONE = 0x00 , UNDERWATER_INWATER = 0x01 , UNDERWATER_INLAVA = 0x02 , UNDERWATER_INSLIME = 0x04 ,
UNDERWATER_INDARKWATER = 0x08 , UNDERWATER_EXIST_TIMERS = 0x10
}
enum BuyBankSlotResult { ERR_BANKSLOT_FAILED_TOO_MANY = 0 , ERR_BANKSLOT_INSUFFICIENT_FUNDS = 1 , ERR_BANKSLOT_NOTBANKER = 2 , ERR_BANKSLOT_OK = 3 }
enum PlayerSpellState {
PLAYERSPELL_UNCHANGED = 0 , PLAYERSPELL_CHANGED = 1 , PLAYERSPELL_NEW = 2 , PLAYERSPELL_REMOVED = 3 ,
PLAYERSPELL_TEMPORARY = 4
}
enum TalentTree {
TALENT_TREE_WARRIOR_ARMS = 161 , TALENT_TREE_WARRIOR_FURY = 164 , TALENT_TREE_WARRIOR_PROTECTION = 163 , TALENT_TREE_PALADIN_HOLY = 382 ,
TALENT_TREE_PALADIN_PROTECTION = 383 , TALENT_TREE_PALADIN_RETRIBUTION = 381 , TALENT_TREE_HUNTER_BEAST_MASTERY = 361 , TALENT_TREE_HUNTER_MARKSMANSHIP = 363 ,
TALENT_TREE_HUNTER_SURVIVAL = 362 , TALENT_TREE_ROGUE_ASSASSINATION = 182 , TALENT_TREE_ROGUE_COMBAT = 181 , TALENT_TREE_ROGUE_SUBTLETY = 183 ,
TALENT_TREE_PRIEST_DISCIPLINE = 201 , TALENT_TREE_PRIEST_HOLY = 202 , TALENT_TREE_PRIEST_SHADOW = 203 , TALENT_TREE_DEATH_KNIGHT_BLOOD = 398 ,
TALENT_TREE_DEATH_KNIGHT_FROST = 399 , TALENT_TREE_DEATH_KNIGHT_UNHOLY = 400 , TALENT_TREE_SHAMAN_ELEMENTAL = 261 , TALENT_TREE_SHAMAN_ENHANCEMENT = 263 ,
TALENT_TREE_SHAMAN_RESTORATION = 262 , TALENT_TREE_MAGE_ARCANE = 81 , TALENT_TREE_MAGE_FIRE = 41 , TALENT_TREE_MAGE_FROST = 61 ,
TALENT_TREE_WARLOCK_AFFLICTION = 302 , TALENT_TREE_WARLOCK_DEMONOLOGY = 303 , TALENT_TREE_WARLOCK_DESTRUCTION = 301 , TALENT_TREE_DRUID_BALANCE = 283 ,
TALENT_TREE_DRUID_FERAL_COMBAT = 281 , TALENT_TREE_DRUID_RESTORATION = 282
}
enum TrainerSpellState { TRAINER_SPELL_GREEN = 0 , TRAINER_SPELL_RED = 1 , TRAINER_SPELL_GRAY = 2 , TRAINER_SPELL_GREEN_DISABLED = 10 }
enum ActionButtonUpdateState { ACTIONBUTTON_UNCHANGED = 0 , ACTIONBUTTON_CHANGED = 1 , ACTIONBUTTON_NEW = 2 , ACTIONBUTTON_DELETED = 3 }
enum ActionButtonType {
ACTION_BUTTON_SPELL = 0x00 , ACTION_BUTTON_C = 0x01 , ACTION_BUTTON_EQSET = 0x20 , ACTION_BUTTON_MACRO = 0x40 ,
ACTION_BUTTON_CMACRO = ACTION_BUTTON_C | ACTION_BUTTON_MACRO , ACTION_BUTTON_ITEM = 0x80
}
enum ReputationSource {
REPUTATION_SOURCE_KILL , REPUTATION_SOURCE_QUEST , REPUTATION_SOURCE_DAILY_QUEST , REPUTATION_SOURCE_WEEKLY_QUEST ,
REPUTATION_SOURCE_MONTHLY_QUEST , REPUTATION_SOURCE_REPEATABLE_QUEST , REPUTATION_SOURCE_SPELL
}
enum RuneCooldowns { RUNE_BASE_COOLDOWN = 10000 , RUNE_GRACE_PERIOD = 2500 , RUNE_MISS_COOLDOWN = 1500 }
enum RuneType {
RUNE_BLOOD = 0 , RUNE_UNHOLY = 1 , RUNE_FROST = 2 , RUNE_DEATH = 3 ,
NUM_RUNE_TYPES = 4
}
enum PlayerMovementType { MOVE_ROOT = 1 , MOVE_UNROOT = 2 , MOVE_WATER_WALK = 3 , MOVE_LAND_WALK = 4 }
enum DrunkenState { DRUNKEN_SOBER = 0 , DRUNKEN_TIPSY = 1 , DRUNKEN_DRUNK = 2 , DRUNKEN_SMASHED = 3 }
enum PlayerFlags {
PLAYER_FLAGS_GROUP_LEADER = 0x00000001 , PLAYER_FLAGS_AFK = 0x00000002 , PLAYER_FLAGS_DND = 0x00000004 , PLAYER_FLAGS_GM = 0x00000008 ,
PLAYER_FLAGS_GHOST = 0x00000010 , PLAYER_FLAGS_RESTING = 0x00000020 , PLAYER_FLAGS_UNK6 = 0x00000040 , PLAYER_FLAGS_UNK7 = 0x00000080 ,
PLAYER_FLAGS_CONTESTED_PVP = 0x00000100 , PLAYER_FLAGS_IN_PVP = 0x00000200 , PLAYER_FLAGS_HIDE_HELM = 0x00000400 , PLAYER_FLAGS_HIDE_CLOAK = 0x00000800 ,
PLAYER_FLAGS_PLAYED_LONG_TIME = 0x00001000 , PLAYER_FLAGS_PLAYED_TOO_LONG = 0x00002000 , PLAYER_FLAGS_IS_OUT_OF_BOUNDS = 0x00004000 , PLAYER_FLAGS_DEVELOPER = 0x00008000 ,
PLAYER_FLAGS_UNK16 = 0x00010000 , PLAYER_FLAGS_TAXI_BENCHMARK = 0x00020000 , PLAYER_FLAGS_PVP_TIMER = 0x00040000 , PLAYER_FLAGS_UBER = 0x00080000 ,
PLAYER_FLAGS_UNK20 = 0x00100000 , PLAYER_FLAGS_UNK21 = 0x00200000 , PLAYER_FLAGS_COMMENTATOR2 = 0x00400000 , PLAYER_ALLOW_ONLY_ABILITY = 0x00800000 ,
PLAYER_FLAGS_UNK24 = 0x01000000 , PLAYER_FLAGS_NO_XP_GAIN = 0x02000000 , PLAYER_FLAGS_UNK26 = 0x04000000 , PLAYER_FLAGS_UNK27 = 0x08000000 ,
PLAYER_FLAGS_UNK28 = 0x10000000 , PLAYER_FLAGS_UNK29 = 0x20000000 , PLAYER_FLAGS_UNK30 = 0x40000000 , PLAYER_FLAGS_UNK31 = 0x80000000
}
enum PlayerBytesOffsets { PLAYER_BYTES_OFFSET_SKIN_ID = 0 , PLAYER_BYTES_OFFSET_FACE_ID = 1 , PLAYER_BYTES_OFFSET_HAIR_STYLE_ID = 2 , PLAYER_BYTES_OFFSET_HAIR_COLOR_ID = 3 }
enum PlayerBytes2Offsets { PLAYER_BYTES_2_OFFSET_FACIAL_STYLE = 0 , PLAYER_BYTES_2_OFFSET_PARTY_TYPE = 1 , PLAYER_BYTES_2_OFFSET_BANK_BAG_SLOTS = 2 , PLAYER_BYTES_2_OFFSET_REST_STATE = 3 }
enum PlayerBytes3Offsets { PLAYER_BYTES_3_OFFSET_GENDER = 0 , PLAYER_BYTES_3_OFFSET_INEBRIATION = 1 , PLAYER_BYTES_3_OFFSET_PVP_TITLE = 2 , PLAYER_BYTES_3_OFFSET_ARENA_FACTION = 3 }
enum PlayerFieldBytesOffsets { PLAYER_FIELD_BYTES_OFFSET_FLAGS = 0 , PLAYER_FIELD_BYTES_OFFSET_RAF_GRANTABLE_LEVEL = 1 , PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES = 2 , PLAYER_FIELD_BYTES_OFFSET_LIFETIME_MAX_PVP_RANK = 3 }
enum PlayerFieldBytes2Offsets { PLAYER_FIELD_BYTES_2_OFFSET_OVERRIDE_SPELLS_ID = 0 , PLAYER_FIELD_BYTES_2_OFFSET_IGNORE_POWER_REGEN_PREDICTION_MASK = 2 , PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION = 3 }
enum PlayerFieldByteFlags { PLAYER_FIELD_BYTE_TRACK_STEALTHED = 0x00000002 , PLAYER_FIELD_BYTE_RELEASE_TIMER = 0x00000008 , PLAYER_FIELD_BYTE_NO_RELEASE_WINDOW = 0x00000010 }
enum PlayerFieldByte2Flags { PLAYER_FIELD_BYTE2_NONE = 0x00 , PLAYER_FIELD_BYTE2_STEALTH = 0x20 , PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW = 0x40 }
enum MirrorTimerType { FATIGUE_TIMER = 0 , BREATH_TIMER = 1 , FIRE_TIMER = 2 }
enum PlayerExtraFlags {
PLAYER_EXTRA_GM_ON = 0x0001 , PLAYER_EXTRA_ACCEPT_WHISPERS = 0x0004 , PLAYER_EXTRA_TAXICHEAT = 0x0008 , PLAYER_EXTRA_GM_INVISIBLE = 0x0010 ,
PLAYER_EXTRA_GM_CHAT = 0x0020 , PLAYER_EXTRA_HAS_310_FLYER = 0x0040 , PLAYER_EXTRA_SPECTATOR_ON = 0x0080 , PLAYER_EXTRA_PVP_DEATH = 0x0100 ,
PLAYER_EXTRA_SHOW_DK_PET = 0x0400
}
enum AtLoginFlags {
AT_LOGIN_NONE = 0x00 , AT_LOGIN_RENAME = 0x01 , AT_LOGIN_RESET_SPELLS = 0x02 , AT_LOGIN_RESET_TALENTS = 0x04 ,
AT_LOGIN_CUSTOMIZE = 0x08 , AT_LOGIN_RESET_PET_TALENTS = 0x10 , AT_LOGIN_FIRST = 0x20 , AT_LOGIN_CHANGE_FACTION = 0x40 ,
AT_LOGIN_CHANGE_RACE = 0x80 , AT_LOGIN_RESET_AP = 0x100 , AT_LOGIN_RESET_ARENA = 0x200 , AT_LOGIN_CHECK_ACHIEVS = 0x400 ,
AT_LOGIN_RESURRECT = 0x800
}
enum QuestSlotOffsets { QUEST_ID_OFFSET = 0 , QUEST_STATE_OFFSET = 1 , QUEST_COUNTS_OFFSET = 2 , QUEST_TIME_OFFSET = 4 }
enum QuestSlotStateMask { QUEST_STATE_NONE = 0x0000 , QUEST_STATE_COMPLETE = 0x0001 , QUEST_STATE_FAIL = 0x0002 }
enum SkillUpdateState { SKILL_UNCHANGED = 0 , SKILL_CHANGED = 1 , SKILL_NEW = 2 , SKILL_DELETED = 3 }
enum PlayerSlots { PLAYER_SLOT_START = 0 , PLAYER_SLOT_END = 150 , PLAYER_SLOTS_COUNT = (PLAYER_SLOT_END - PLAYER_SLOT_START) }
enum EquipmentSlots {
EQUIPMENT_SLOT_START = 0 , EQUIPMENT_SLOT_HEAD = 0 , EQUIPMENT_SLOT_NECK = 1 , EQUIPMENT_SLOT_SHOULDERS = 2 ,
EQUIPMENT_SLOT_BODY = 3 , EQUIPMENT_SLOT_CHEST = 4 , EQUIPMENT_SLOT_WAIST = 5 , EQUIPMENT_SLOT_LEGS = 6 ,
EQUIPMENT_SLOT_FEET = 7 , EQUIPMENT_SLOT_WRISTS = 8 , EQUIPMENT_SLOT_HANDS = 9 , EQUIPMENT_SLOT_FINGER1 = 10 ,
EQUIPMENT_SLOT_FINGER2 = 11 , EQUIPMENT_SLOT_TRINKET1 = 12 , EQUIPMENT_SLOT_TRINKET2 = 13 , EQUIPMENT_SLOT_BACK = 14 ,
EQUIPMENT_SLOT_MAINHAND = 15 , EQUIPMENT_SLOT_OFFHAND = 16 , EQUIPMENT_SLOT_RANGED = 17 , EQUIPMENT_SLOT_TABARD = 18 ,
EQUIPMENT_SLOT_END = 19
}
enum InventorySlots { INVENTORY_SLOT_BAG_START = 19 , INVENTORY_SLOT_BAG_END = 23 }
enum InventoryPackSlots { INVENTORY_SLOT_ITEM_START = 23 , INVENTORY_SLOT_ITEM_END = 39 }
enum BankItemSlots { BANK_SLOT_ITEM_START = 39 , BANK_SLOT_ITEM_END = 67 }
enum BankBagSlots { BANK_SLOT_BAG_START = 67 , BANK_SLOT_BAG_END = 74 }
enum BuyBackSlots { BUYBACK_SLOT_START = 74 , BUYBACK_SLOT_END = 86 }
enum KeyRingSlots { KEYRING_SLOT_START = 86 , KEYRING_SLOT_END = 118 }
enum CurrencyTokenSlots { CURRENCYTOKEN_SLOT_START = 118 , CURRENCYTOKEN_SLOT_END = 150 }
enum EquipmentSetUpdateState { EQUIPMENT_SET_UNCHANGED = 0 , EQUIPMENT_SET_CHANGED = 1 , EQUIPMENT_SET_NEW = 2 , EQUIPMENT_SET_DELETED = 3 }
enum TransferAbortReason {
TRANSFER_ABORT_NONE = 0x00 , TRANSFER_ABORT_ERROR = 0x01 , TRANSFER_ABORT_MAX_PLAYERS = 0x02 , TRANSFER_ABORT_NOT_FOUND = 0x03 ,
TRANSFER_ABORT_TOO_MANY_INSTANCES = 0x04 , TRANSFER_ABORT_ZONE_IN_COMBAT = 0x06 , TRANSFER_ABORT_INSUF_EXPAN_LVL = 0x07 , TRANSFER_ABORT_DIFFICULTY = 0x08 ,
TRANSFER_ABORT_UNIQUE_MESSAGE = 0x09 , TRANSFER_ABORT_TOO_MANY_REALM_INSTANCES = 0x0A , TRANSFER_ABORT_NEED_GROUP = 0x0B , TRANSFER_ABORT_NOT_FOUND1 = 0x0C ,
TRANSFER_ABORT_NOT_FOUND2 = 0x0D , TRANSFER_ABORT_NOT_FOUND3 = 0x0E , TRANSFER_ABORT_REALM_ONLY = 0x0F , TRANSFER_ABORT_MAP_NOT_ALLOWED = 0x10
}
enum InstanceResetWarningType {
RAID_INSTANCE_WARNING_HOURS = 1 , RAID_INSTANCE_WARNING_MIN = 2 , RAID_INSTANCE_WARNING_MIN_SOON = 3 , RAID_INSTANCE_WELCOME = 4 ,
RAID_INSTANCE_EXPIRED = 5
}
enum RestFlag { REST_FLAG_IN_TAVERN = 0x1 , REST_FLAG_IN_CITY = 0x2 , REST_FLAG_IN_FACTION_AREA = 0x4 }
enum TeleportToOptions {
TELE_TO_GM_MODE = 0x01 , TELE_TO_NOT_LEAVE_TRANSPORT = 0x02 , TELE_TO_NOT_LEAVE_COMBAT = 0x04 , TELE_TO_NOT_UNSUMMON_PET = 0x08 ,
TELE_TO_SPELL = 0x10 , TELE_TO_NOT_LEAVE_VEHICLE = 0x20 , TELE_TO_WITH_PET = 0x40 , TELE_TO_NOT_LEAVE_TAXI = 0x80
}
enum EnviromentalDamage {
DAMAGE_EXHAUSTED = 0 , DAMAGE_DROWNING = 1 , DAMAGE_FALL = 2 , DAMAGE_LAVA = 3 ,
DAMAGE_SLIME = 4 , DAMAGE_FIRE = 5 , DAMAGE_FALL_TO_VOID = 6
}
Type of environmental damages.
enum PlayerChatTag {
CHAT_TAG_NONE = 0x00 , CHAT_TAG_AFK = 0x01 , CHAT_TAG_DND = 0x02 , CHAT_TAG_GM = 0x04 ,
CHAT_TAG_COM = 0x08 , CHAT_TAG_DEV = 0x10
}
enum PlayedTimeIndex { PLAYED_TIME_TOTAL = 0 , PLAYED_TIME_LEVEL = 1 }
enum PlayerLoginQueryIndex {
PLAYER_LOGIN_QUERY_LOAD_FROM = 0 , PLAYER_LOGIN_QUERY_LOAD_AURAS = 3 , PLAYER_LOGIN_QUERY_LOAD_SPELLS = 4 , PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS = 5 ,
PLAYER_LOGIN_QUERY_LOAD_DAILY_QUEST_STATUS = 6 , PLAYER_LOGIN_QUERY_LOAD_REPUTATION = 7 , PLAYER_LOGIN_QUERY_LOAD_INVENTORY = 8 , PLAYER_LOGIN_QUERY_LOAD_ACTIONS = 9 ,
PLAYER_LOGIN_QUERY_LOAD_MAILS = 10 , PLAYER_LOGIN_QUERY_LOAD_MAIL_ITEMS = 11 , PLAYER_LOGIN_QUERY_LOAD_SOCIAL_LIST = 13 , PLAYER_LOGIN_QUERY_LOAD_HOME_BIND = 14 ,
PLAYER_LOGIN_QUERY_LOAD_SPELL_COOLDOWNS = 15 , PLAYER_LOGIN_QUERY_LOAD_DECLINED_NAMES = 16 , PLAYER_LOGIN_QUERY_LOAD_ACHIEVEMENTS = 18 , PLAYER_LOGIN_QUERY_LOAD_CRITERIA_PROGRESS = 19 ,
PLAYER_LOGIN_QUERY_LOAD_EQUIPMENT_SETS = 20 , PLAYER_LOGIN_QUERY_LOAD_ENTRY_POINT = 21 , PLAYER_LOGIN_QUERY_LOAD_GLYPHS = 22 , PLAYER_LOGIN_QUERY_LOAD_TALENTS = 23 ,
PLAYER_LOGIN_QUERY_LOAD_ACCOUNT_DATA = 24 , PLAYER_LOGIN_QUERY_LOAD_SKILLS = 25 , PLAYER_LOGIN_QUERY_LOAD_WEEKLY_QUEST_STATUS = 26 , PLAYER_LOGIN_QUERY_LOAD_RANDOM_BG = 27 ,
PLAYER_LOGIN_QUERY_LOAD_BANNED = 28 , PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS_REW = 29 , PLAYER_LOGIN_QUERY_LOAD_INSTANCE_LOCK_TIMES = 30 , PLAYER_LOGIN_QUERY_LOAD_SEASONAL_QUEST_STATUS = 31 ,
PLAYER_LOGIN_QUERY_LOAD_MONTHLY_QUEST_STATUS = 32 , PLAYER_LOGIN_QUERY_LOAD_BREW_OF_THE_MONTH = 34 , PLAYER_LOGIN_QUERY_LOAD_CORPSE_LOCATION = 35 , MAX_PLAYER_LOGIN_QUERY
}
enum PlayerDelayedOperations {
DELAYED_SAVE_PLAYER = 0x01 , DELAYED_RESURRECT_PLAYER = 0x02 , DELAYED_SPELL_CAST_DESERTER = 0x04 , DELAYED_BG_MOUNT_RESTORE = 0x08 ,
DELAYED_BG_TAXI_RESTORE = 0x10 , DELAYED_BG_GROUP_RESTORE = 0x20 , DELAYED_VEHICLE_TELEPORT = 0x40 , DELAYED_END
}
enum PlayerCharmedAISpells {
SPELL_T_STUN , SPELL_ROOT_OR_FEAR , SPELL_INSTANT_DAMAGE , SPELL_INSTANT_DAMAGE2 ,
SPELL_HIGH_DAMAGE1 , SPELL_HIGH_DAMAGE2 , SPELL_DOT_DAMAGE , SPELL_T_CHARGE ,
SPELL_IMMUNITY , SPELL_FAST_RUN , NUM_CAI_SPELLS
}
enum CharDeleteMethod { CHAR_DELETE_REMOVE = 0 , CHAR_DELETE_UNLINK = 1 }
enum CurrencyItems { ITEM_HONOR_POINTS_ID = 43308 , ITEM_ARENA_POINTS_ID = 43307 }
enum ReferAFriendError {
ERR_REFER_A_FRIEND_NONE = 0x00 , ERR_REFER_A_FRIEND_NOT_REFERRED_BY = 0x01 , ERR_REFER_A_FRIEND_TARGET_TOO_HIGH = 0x02 , ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS = 0x03 ,
ERR_REFER_A_FRIEND_TOO_FAR = 0x04 , ERR_REFER_A_FRIEND_DIFFERENT_FACTION = 0x05 , ERR_REFER_A_FRIEND_NOT_NOW = 0x06 , ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I = 0x07 ,
ERR_REFER_A_FRIEND_NO_TARGET = 0x08 , ERR_REFER_A_FRIEND_NOT_IN_GROUP = 0x09 , ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I = 0x0A , ERR_REFER_A_FRIEND_SUMMON_COOLDOWN = 0x0B ,
ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL = 0x0C , ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S = 0x0D
}
enum PlayerRestState { REST_STATE_RESTED = 0x01 , REST_STATE_NOT_RAF_LINKED = 0x02 , REST_STATE_RAF_LINKED = 0x06 }
enum AdditionalSaving { ADDITIONAL_SAVING_NONE = 0x00 , ADDITIONAL_SAVING_INVENTORY_AND_GOLD = 0x01 , ADDITIONAL_SAVING_QUEST_STATUS = 0x02 }
enum PlayerCommandStates {
CHEAT_NONE = 0x00 , CHEAT_GOD = 0x01 , CHEAT_CASTTIME = 0x02 , CHEAT_COOLDOWN = 0x04 ,
CHEAT_POWER = 0x08 , CHEAT_WATERWALK = 0x10
}
enum InstantFlightGossipAction { GOSSIP_ACTION_TOGGLE_INSTANT_FLIGHT = 500 }
enum EmoteBroadcastTextID { EMOTE_BROADCAST_TEXT_ID_STRANGE_GESTURES = 91243 }
Functions
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
void AddItemsSetItem (Player *player, Item *item)
void RemoveItemsSetItem (Player *player, ItemTemplate const *proto)
Macro Definition Documentation
ACTION_BUTTON_ACTION
#define ACTION_BUTTON_ACTION (X) (uint32(X) & 0x00FFFFFF)
Definition at line 243 of file Player.h.
ACTION_BUTTON_TYPE
#define ACTION_BUTTON_TYPE (X) ((uint32(X) & 0xFF000000) >> 24)
Definition at line 244 of file Player.h.
DEATH_EXPIRE_STEP
#define DEATH_EXPIRE_STEP (5*MINUTE)
Definition at line 70 of file Player.h.
DISABLED_MIRROR_TIMER
#define DISABLED_MIRROR_TIMER -1
Definition at line 560 of file Player.h.
INVENTORY_SLOT_BAG_0
#define INVENTORY_SLOT_BAG_0 255
Definition at line 651 of file Player.h.
KNOWN_TITLES_SIZE
#define KNOWN_TITLES_SIZE 3
Definition at line 534 of file Player.h.
MAKE_SKILL_BONUS
#define MAKE_SKILL_BONUS (t, p) MAKE_PAIR32(t, p)
Definition at line 83 of file Player.h.
MAKE_SKILL_VALUE
#define MAKE_SKILL_VALUE (v, m) MAKE_PAIR32(v, m)
Definition at line 79 of file Player.h.
MAX_ACTION_BUTTON_ACTION_VALUE
#define MAX_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
Definition at line 245 of file Player.h.
MAX_ACTION_BUTTONS
#define MAX_ACTION_BUTTONS 144
Definition at line 269 of file Player.h.
MAX_DEATH_COUNT
#define MAX_DEATH_COUNT 3
Definition at line 71 of file Player.h.
MAX_DRUNKEN
#define MAX_DRUNKEN 4
Definition at line 453 of file Player.h.
MAX_EQUIPMENT_SET_INDEX
#define MAX_EQUIPMENT_SET_INDEX 10
Definition at line 741 of file Player.h.
MAX_MONEY_AMOUNT
#define MAX_MONEY_AMOUNT (0x7FFFFFFF-1)
Definition at line 900 of file Player.h.
MAX_PLAYED_TIME_INDEX
#define MAX_PLAYED_TIME_INDEX 2
Definition at line 832 of file Player.h.
MAX_PLAYER_SUMMON_DELAY
#define MAX_PLAYER_SUMMON_DELAY (2*MINUTE)
Definition at line 899 of file Player.h.
MAX_QUEST_OFFSET
#define MAX_QUEST_OFFSET 5
Definition at line 609 of file Player.h.
MAX_RUNES
#define MAX_RUNES 6
Definition at line 381 of file Player.h.
MAX_TIMERS
#define MAX_TIMERS 3
Definition at line 559 of file Player.h.
MAX_TITLE_INDEX
#define MAX_TITLE_INDEX (KNOWN_TITLES_SIZE*64)
Definition at line 535 of file Player.h.
PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET
#define PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET (PLAYER_FIELD_BYTES_2_OFFSET_OVERRIDE_SPELLS_ID / 2)
Definition at line 532 of file Player.h.
PLAYER_EXPLORED_ZONES_SIZE
#define PLAYER_EXPLORED_ZONES_SIZE 128
Definition at line 67 of file Player.h.
PLAYER_MAX_DAILY_QUESTS
#define PLAYER_MAX_DAILY_QUESTS 25
Definition at line 66 of file Player.h.
PLAYER_MAX_SKILLS
#define PLAYER_MAX_SKILLS 127
Definition at line 65 of file Player.h.
PLAYER_SKILL_BONUS_INDEX
#define PLAYER_SKILL_BONUS_INDEX (x) (PLAYER_SKILL_INDEX(x)+2)
Definition at line 75 of file Player.h.
PLAYER_SKILL_INDEX
#define PLAYER_SKILL_INDEX (x) (PLAYER_SKILL_INFO_1_1 + ((x)*3))
Definition at line 73 of file Player.h.
PLAYER_SKILL_VALUE_INDEX
#define PLAYER_SKILL_VALUE_INDEX (x) (PLAYER_SKILL_INDEX(x)+1)
Definition at line 74 of file Player.h.
SKILL_MAX
#define SKILL_MAX (x) PAIR32_HIPART(x)
Definition at line 78 of file Player.h.
SKILL_PERM_BONUS
#define SKILL_PERM_BONUS (x) int16(PAIR32_HIPART(x))
Definition at line 82 of file Player.h.
SKILL_TEMP_BONUS
#define SKILL_TEMP_BONUS (x) int16(PAIR32_LOPART(x))
Definition at line 81 of file Player.h.
SKILL_VALUE
#define SKILL_VALUE (x) PAIR32_LOPART(x)
Definition at line 77 of file Player.h.
SPEC_MASK_ALL
#define SPEC_MASK_ALL 255
Definition at line 172 of file Player.h.
Typedef Documentation
ActionButtonList
typedef std::map<uint8, ActionButton> ActionButtonList
Definition at line 271 of file Player.h.
bgZoneRef
typedef void(* bgZoneRef) (Battleground *, WorldPacket &)
Definition at line 63 of file Player.h.
EnchantDurationList
typedef std::list<EnchantDuration> EnchantDurationList
Definition at line 434 of file Player.h.
EquipmentSets
typedef std::map<uint32, EquipmentSet> EquipmentSets
Definition at line 743 of file Player.h.
InstanceTimeMap
typedef std::unordered_map<uint32 , time_t> InstanceTimeMap
Definition at line 204 of file Player.h.
ItemDurationList
typedef std::list<Item*> ItemDurationList
Definition at line 435 of file Player.h.
ItemPosCountVec
typedef std::vector<ItemPosCount> ItemPosCountVec
Definition at line 752 of file Player.h.
PlayerCreateInfoActions
typedef std::list<PlayerCreateInfoAction> PlayerCreateInfoActions
Definition at line 316 of file Player.h.
PlayerCreateInfoItems
typedef std::list<PlayerCreateInfoItem> PlayerCreateInfoItems
Definition at line 281 of file Player.h.
PlayerCreateInfoSkills
typedef std::list<PlayerCreateInfoSkill> PlayerCreateInfoSkills
Definition at line 324 of file Player.h.
PlayerCreateInfoSpells
typedef std::list<uint32> PlayerCreateInfoSpells
Definition at line 304 of file Player.h.
PlayerMails
typedef std::deque<Mail*> PlayerMails
Definition at line 62 of file Player.h.
PlayerSpellMap
typedef std::unordered_map<uint32, PlayerSpell*> PlayerSpellMap
Definition at line 188 of file Player.h.
PlayerTalentMap
typedef std::unordered_map<uint32, PlayerTalent*> PlayerTalentMap
Definition at line 187 of file Player.h.
QuestStatusMap
typedef std::map<uint32, QuestStatusData> QuestStatusMap
Definition at line 595 of file Player.h.
QuestStatusSaveMap
typedef std::map<uint32, bool> QuestStatusSaveMap
Definition at line 599 of file Player.h.
RewardedQuestSet
typedef std::unordered_set<uint32> RewardedQuestSet
Definition at line 596 of file Player.h.
SkillStatusMap
typedef std::unordered_map<uint32, SkillStatusData> SkillStatusMap
Definition at line 635 of file Player.h.
SpellCooldowns
typedef std::map<uint32, SpellCooldown> SpellCooldowns
Definition at line 203 of file Player.h.
SpellModList
typedef std::list<SpellModifier*> SpellModList
Definition at line 189 of file Player.h.
WhisperListContainer
typedef GuidList WhisperListContainer
Definition at line 191 of file Player.h.
Enumeration Type Documentation
ActionButtonType
enum ActionButtonType
Enumerator
ACTION_BUTTON_SPELL
ACTION_BUTTON_C
ACTION_BUTTON_EQSET
ACTION_BUTTON_MACRO
ACTION_BUTTON_CMACRO
ACTION_BUTTON_ITEM
Definition at line 222 of file Player.h.
 {
     ACTION_BUTTON_SPELL     = 0x00,
     ACTION_BUTTON_C         = 0x01,                         // click?
     ACTION_BUTTON_EQSET     = 0x20,
     ACTION_BUTTON_MACRO     = 0x40,
     ACTION_BUTTON_CMACRO    = ACTION_BUTTON_C | ACTION_BUTTON_MACRO,
     ACTION_BUTTON_ITEM      = 0x80
 };
ActionButtonUpdateState
enum ActionButtonUpdateState
Enumerator
ACTIONBUTTON_UNCHANGED
ACTIONBUTTON_CHANGED
ACTIONBUTTON_NEW
ACTIONBUTTON_DELETED
Definition at line 214 of file Player.h.
 {
     ACTIONBUTTON_UNCHANGED = 0,
     ACTIONBUTTON_CHANGED   = 1,
     ACTIONBUTTON_NEW       = 2,
     ACTIONBUTTON_DELETED   = 3
 };
AdditionalSaving
enum AdditionalSaving
Enumerator
ADDITIONAL_SAVING_NONE
ADDITIONAL_SAVING_INVENTORY_AND_GOLD
ADDITIONAL_SAVING_QUEST_STATUS
Definition at line 959 of file Player.h.
 {
     ADDITIONAL_SAVING_NONE                      = 0x00,
     ADDITIONAL_SAVING_INVENTORY_AND_GOLD        = 0x01,
     ADDITIONAL_SAVING_QUEST_STATUS              = 0x02,
 };
AtLoginFlags
enum AtLoginFlags
Enumerator
AT_LOGIN_NONE
AT_LOGIN_RENAME
AT_LOGIN_RESET_SPELLS
AT_LOGIN_RESET_TALENTS
AT_LOGIN_CUSTOMIZE
AT_LOGIN_RESET_PET_TALENTS
AT_LOGIN_FIRST
AT_LOGIN_CHANGE_FACTION
AT_LOGIN_CHANGE_RACE
AT_LOGIN_RESET_AP
AT_LOGIN_RESET_ARENA
AT_LOGIN_CHECK_ACHIEVS
AT_LOGIN_RESURRECT
Definition at line 578 of file Player.h.
 {
     AT_LOGIN_NONE              = 0x00,
     AT_LOGIN_RENAME            = 0x01,
     AT_LOGIN_RESET_SPELLS      = 0x02,
     AT_LOGIN_RESET_TALENTS     = 0x04,
     AT_LOGIN_CUSTOMIZE         = 0x08,
     AT_LOGIN_RESET_PET_TALENTS = 0x10,
     AT_LOGIN_FIRST             = 0x20,
     AT_LOGIN_CHANGE_FACTION    = 0x40,
     AT_LOGIN_CHANGE_RACE       = 0x80,
     AT_LOGIN_RESET_AP          = 0x100,
     AT_LOGIN_RESET_ARENA       = 0x200,
     AT_LOGIN_CHECK_ACHIEVS     = 0x400,
     AT_LOGIN_RESURRECT         = 0x800
 };
BankBagSlots
enum BankBagSlots
Enumerator
BANK_SLOT_BAG_START
BANK_SLOT_BAG_END
Definition at line 696 of file Player.h.
 {
     BANK_SLOT_BAG_START         = 67,
     BANK_SLOT_BAG_END           = 74
 };
BankItemSlots
enum BankItemSlots
Enumerator
BANK_SLOT_ITEM_START
BANK_SLOT_ITEM_END
Definition at line 690 of file Player.h.
 {
     BANK_SLOT_ITEM_START        = 39,
     BANK_SLOT_ITEM_END          = 67
 };
BuyBackSlots
enum BuyBackSlots
Enumerator
BUYBACK_SLOT_START
BUYBACK_SLOT_END
Definition at line 702 of file Player.h.
 {
     // stored in m_buybackitems
     BUYBACK_SLOT_START          = 74,
     BUYBACK_SLOT_END            = 86
 };
BuyBankSlotResult
enum BuyBankSlotResult
Enumerator
ERR_BANKSLOT_FAILED_TOO_MANY
ERR_BANKSLOT_INSUFFICIENT_FUNDS
ERR_BANKSLOT_NOTBANKER
ERR_BANKSLOT_OK
Definition at line 104 of file Player.h.
 {
     ERR_BANKSLOT_FAILED_TOO_MANY    = 0,
     ERR_BANKSLOT_INSUFFICIENT_FUNDS = 1,
     ERR_BANKSLOT_NOTBANKER          = 2,
     ERR_BANKSLOT_OK                 = 3
 };
CharDeleteMethod
enum CharDeleteMethod
Enumerator
CHAR_DELETE_REMOVE
CHAR_DELETE_UNLINK
Definition at line 921 of file Player.h.
 {
     CHAR_DELETE_REMOVE = 0,                      // Completely remove from the database
     CHAR_DELETE_UNLINK = 1                       // The character gets unlinked from the account,
                          // the name gets freed up and appears as deleted ingame
 };
CurrencyItems
enum CurrencyItems
Enumerator
ITEM_HONOR_POINTS_ID
ITEM_ARENA_POINTS_ID
Definition at line 928 of file Player.h.
 {
     ITEM_HONOR_POINTS_ID    = 43308,
     ITEM_ARENA_POINTS_ID    = 43307
 };
CurrencyTokenSlots
enum CurrencyTokenSlots
Enumerator
CURRENCYTOKEN_SLOT_START
CURRENCYTOKEN_SLOT_END
Definition at line 715 of file Player.h.
 {
     CURRENCYTOKEN_SLOT_START    = 118,
     CURRENCYTOKEN_SLOT_END      = 150
 };
DrunkenState
enum DrunkenState
Enumerator
DRUNKEN_SOBER
DRUNKEN_TIPSY
DRUNKEN_DRUNK
DRUNKEN_SMASHED
Definition at line 445 of file Player.h.
 {
     DRUNKEN_SOBER   = 0,
     DRUNKEN_TIPSY   = 1,
     DRUNKEN_DRUNK   = 2,
     DRUNKEN_SMASHED = 3
 };
EmoteBroadcastTextID
enum EmoteBroadcastTextID
Enumerator
EMOTE_BROADCAST_TEXT_ID_STRANGE_GESTURES
Definition at line 981 of file Player.h.
 {
     EMOTE_BROADCAST_TEXT_ID_STRANGE_GESTURES = 91243
 };
EnviromentalDamage
enum EnviromentalDamage
Type of environmental damages.
Enumerator
DAMAGE_EXHAUSTED
DAMAGE_DROWNING
DAMAGE_FALL
DAMAGE_LAVA
DAMAGE_SLIME
DAMAGE_FIRE
DAMAGE_FALL_TO_VOID
Definition at line 805 of file Player.h.
 {
     DAMAGE_EXHAUSTED = 0,
     DAMAGE_DROWNING  = 1,
     DAMAGE_FALL      = 2,
     DAMAGE_LAVA      = 3,
     DAMAGE_SLIME     = 4,
     DAMAGE_FIRE      = 5,
     DAMAGE_FALL_TO_VOID = 6                                 // custom case for fall without durability loss
 };
EquipmentSetUpdateState
enum EquipmentSetUpdateState
Enumerator
EQUIPMENT_SET_UNCHANGED
EQUIPMENT_SET_CHANGED
EQUIPMENT_SET_NEW
EQUIPMENT_SET_DELETED
Definition at line 721 of file Player.h.
 {
     EQUIPMENT_SET_UNCHANGED = 0,
     EQUIPMENT_SET_CHANGED   = 1,
     EQUIPMENT_SET_NEW       = 2,
     EQUIPMENT_SET_DELETED   = 3
 };
EquipmentSlots
enum EquipmentSlots
Enumerator
EQUIPMENT_SLOT_START
EQUIPMENT_SLOT_HEAD
EQUIPMENT_SLOT_NECK
EQUIPMENT_SLOT_SHOULDERS
EQUIPMENT_SLOT_BODY
EQUIPMENT_SLOT_CHEST
EQUIPMENT_SLOT_WAIST
EQUIPMENT_SLOT_LEGS
EQUIPMENT_SLOT_FEET
EQUIPMENT_SLOT_WRISTS
EQUIPMENT_SLOT_HANDS
EQUIPMENT_SLOT_FINGER1
EQUIPMENT_SLOT_FINGER2
EQUIPMENT_SLOT_TRINKET1
EQUIPMENT_SLOT_TRINKET2
EQUIPMENT_SLOT_BACK
EQUIPMENT_SLOT_MAINHAND
EQUIPMENT_SLOT_OFFHAND
EQUIPMENT_SLOT_RANGED
EQUIPMENT_SLOT_TABARD
EQUIPMENT_SLOT_END
Definition at line 653 of file Player.h.
 {
     EQUIPMENT_SLOT_START        = 0,
     EQUIPMENT_SLOT_HEAD         = 0,
     EQUIPMENT_SLOT_NECK         = 1,
     EQUIPMENT_SLOT_SHOULDERS    = 2,
     EQUIPMENT_SLOT_BODY         = 3,
     EQUIPMENT_SLOT_CHEST        = 4,
     EQUIPMENT_SLOT_WAIST        = 5,
     EQUIPMENT_SLOT_LEGS         = 6,
     EQUIPMENT_SLOT_FEET         = 7,
     EQUIPMENT_SLOT_WRISTS       = 8,
     EQUIPMENT_SLOT_HANDS        = 9,
     EQUIPMENT_SLOT_FINGER1      = 10,
     EQUIPMENT_SLOT_FINGER2      = 11,
     EQUIPMENT_SLOT_TRINKET1     = 12,
     EQUIPMENT_SLOT_TRINKET2     = 13,
     EQUIPMENT_SLOT_BACK         = 14,
     EQUIPMENT_SLOT_MAINHAND     = 15,
     EQUIPMENT_SLOT_OFFHAND      = 16,
     EQUIPMENT_SLOT_RANGED       = 17,
     EQUIPMENT_SLOT_TABARD       = 18,
     EQUIPMENT_SLOT_END          = 19
 };
InstanceResetWarningType
enum InstanceResetWarningType
Enumerator
RAID_INSTANCE_WARNING_HOURS
RAID_INSTANCE_WARNING_MIN
RAID_INSTANCE_WARNING_MIN_SOON
RAID_INSTANCE_WELCOME
RAID_INSTANCE_EXPIRED
Definition at line 774 of file Player.h.
 {
     RAID_INSTANCE_WARNING_HOURS     = 1,                    // WARNING! %s is scheduled to reset in %d hour(s).
     RAID_INSTANCE_WARNING_MIN       = 2,                    // WARNING! %s is scheduled to reset in %d minute(s)!
     RAID_INSTANCE_WARNING_MIN_SOON  = 3,                    // WARNING! %s is scheduled to reset in %d minute(s). Please exit the zone or you will be returned to your bind location!
     RAID_INSTANCE_WELCOME           = 4,                    // Welcome to %s. This raid instance is scheduled to reset in %s.
     RAID_INSTANCE_EXPIRED           = 5
 };
InstantFlightGossipAction
enum InstantFlightGossipAction
Enumerator
GOSSIP_ACTION_TOGGLE_INSTANT_FLIGHT
Definition at line 976 of file Player.h.
 {
     GOSSIP_ACTION_TOGGLE_INSTANT_FLIGHT = 500
 };
InventoryPackSlots
enum InventoryPackSlots
Enumerator
INVENTORY_SLOT_ITEM_START
INVENTORY_SLOT_ITEM_END
Definition at line 684 of file Player.h.
 {
     INVENTORY_SLOT_ITEM_START   = 23,
     INVENTORY_SLOT_ITEM_END     = 39
 };
InventorySlots
enum InventorySlots
Enumerator
INVENTORY_SLOT_BAG_START
INVENTORY_SLOT_BAG_END
Definition at line 678 of file Player.h.
 {
     INVENTORY_SLOT_BAG_START    = 19,
     INVENTORY_SLOT_BAG_END      = 23
 };
KeyRingSlots
enum KeyRingSlots
Enumerator
KEYRING_SLOT_START
KEYRING_SLOT_END
Definition at line 709 of file Player.h.
 {
     KEYRING_SLOT_START          = 86,
     KEYRING_SLOT_END            = 118
 };
MirrorTimerType
enum MirrorTimerType
Enumerator
FATIGUE_TIMER
BREATH_TIMER
FIRE_TIMER
Definition at line 553 of file Player.h.
 {
     FATIGUE_TIMER      = 0,
     BREATH_TIMER       = 1,
     FIRE_TIMER         = 2
 };
PlayedTimeIndex
enum PlayedTimeIndex
Enumerator
PLAYED_TIME_TOTAL
PLAYED_TIME_LEVEL
Definition at line 826 of file Player.h.
 {
     PLAYED_TIME_TOTAL = 0,
     PLAYED_TIME_LEVEL = 1
 };
PlayerBytes2Offsets
enum PlayerBytes2Offsets
Enumerator
PLAYER_BYTES_2_OFFSET_FACIAL_STYLE
PLAYER_BYTES_2_OFFSET_PARTY_TYPE
PLAYER_BYTES_2_OFFSET_BANK_BAG_SLOTS
PLAYER_BYTES_2_OFFSET_REST_STATE
Definition at line 499 of file Player.h.
 {
     PLAYER_BYTES_2_OFFSET_FACIAL_STYLE      = 0,
     PLAYER_BYTES_2_OFFSET_PARTY_TYPE        = 1,
     PLAYER_BYTES_2_OFFSET_BANK_BAG_SLOTS    = 2,
     PLAYER_BYTES_2_OFFSET_REST_STATE        = 3
 };
PlayerBytes3Offsets
enum PlayerBytes3Offsets
Enumerator
PLAYER_BYTES_3_OFFSET_GENDER
PLAYER_BYTES_3_OFFSET_INEBRIATION
PLAYER_BYTES_3_OFFSET_PVP_TITLE
PLAYER_BYTES_3_OFFSET_ARENA_FACTION
Definition at line 507 of file Player.h.
 {
     PLAYER_BYTES_3_OFFSET_GENDER        = 0,
     PLAYER_BYTES_3_OFFSET_INEBRIATION   = 1,
     PLAYER_BYTES_3_OFFSET_PVP_TITLE     = 2,
     PLAYER_BYTES_3_OFFSET_ARENA_FACTION = 3
 };
PlayerBytesOffsets
enum PlayerBytesOffsets
Enumerator
PLAYER_BYTES_OFFSET_SKIN_ID
PLAYER_BYTES_OFFSET_FACE_ID
PLAYER_BYTES_OFFSET_HAIR_STYLE_ID
PLAYER_BYTES_OFFSET_HAIR_COLOR_ID
Definition at line 491 of file Player.h.
 {
     PLAYER_BYTES_OFFSET_SKIN_ID         = 0,
     PLAYER_BYTES_OFFSET_FACE_ID         = 1,
     PLAYER_BYTES_OFFSET_HAIR_STYLE_ID   = 2,
     PLAYER_BYTES_OFFSET_HAIR_COLOR_ID   = 3
 };
PlayerCharmedAISpells
enum PlayerCharmedAISpells
Enumerator
SPELL_T_STUN
SPELL_ROOT_OR_FEAR
SPELL_INSTANT_DAMAGE
SPELL_INSTANT_DAMAGE2
SPELL_HIGH_DAMAGE1
SPELL_HIGH_DAMAGE2
SPELL_DOT_DAMAGE
SPELL_T_CHARGE
SPELL_IMMUNITY
SPELL_FAST_RUN
NUM_CAI_SPELLS
Definition at line 883 of file Player.h.
 {
     SPELL_T_STUN,
     SPELL_ROOT_OR_FEAR,
     SPELL_INSTANT_DAMAGE,
     SPELL_INSTANT_DAMAGE2,
     SPELL_HIGH_DAMAGE1,
     SPELL_HIGH_DAMAGE2,
     SPELL_DOT_DAMAGE,
     SPELL_T_CHARGE,
     SPELL_IMMUNITY,
     SPELL_FAST_RUN,
     NUM_CAI_SPELLS
 };
PlayerChatTag
enum PlayerChatTag
Enumerator
CHAT_TAG_NONE
CHAT_TAG_AFK
CHAT_TAG_DND
CHAT_TAG_GM
CHAT_TAG_COM
CHAT_TAG_DEV
Definition at line 816 of file Player.h.
 {
     CHAT_TAG_NONE       = 0x00,
     CHAT_TAG_AFK        = 0x01,
     CHAT_TAG_DND        = 0x02,
     CHAT_TAG_GM         = 0x04,
     CHAT_TAG_COM        = 0x08, // Commentator
     CHAT_TAG_DEV        = 0x10,
 };
PlayerCommandStates
enum PlayerCommandStates
Enumerator
CHEAT_NONE
CHEAT_GOD
CHEAT_CASTTIME
CHEAT_COOLDOWN
CHEAT_POWER
CHEAT_WATERWALK
Definition at line 966 of file Player.h.
 {
     CHEAT_NONE = 0x00,
     CHEAT_GOD = 0x01,
     CHEAT_CASTTIME = 0x02,
     CHEAT_COOLDOWN = 0x04,
     CHEAT_POWER = 0x08,
     CHEAT_WATERWALK = 0x10
 };
PlayerDelayedOperations
enum PlayerDelayedOperations
Enumerator
DELAYED_SAVE_PLAYER
DELAYED_RESURRECT_PLAYER
DELAYED_SPELL_CAST_DESERTER
DELAYED_BG_MOUNT_RESTORE
Flag to restore mount state after teleport from BG.
DELAYED_BG_TAXI_RESTORE
Flag to restore taxi state after teleport from BG.
DELAYED_BG_GROUP_RESTORE
Flag to restore group state after teleport from BG.
DELAYED_VEHICLE_TELEPORT
DELAYED_END
Definition at line 871 of file Player.h.
 {
     DELAYED_SAVE_PLAYER         = 0x01,
     DELAYED_RESURRECT_PLAYER    = 0x02,
     DELAYED_SPELL_CAST_DESERTER = 0x04,
     DELAYED_BG_MOUNT_RESTORE    = 0x08,
     DELAYED_BG_TAXI_RESTORE     = 0x10,
     DELAYED_BG_GROUP_RESTORE    = 0x20,
     DELAYED_VEHICLE_TELEPORT    = 0x40,
     DELAYED_END
 };
PlayerExtraFlags
enum PlayerExtraFlags
Enumerator
PLAYER_EXTRA_GM_ON
PLAYER_EXTRA_ACCEPT_WHISPERS
PLAYER_EXTRA_TAXICHEAT
PLAYER_EXTRA_GM_INVISIBLE
PLAYER_EXTRA_GM_CHAT
PLAYER_EXTRA_HAS_310_FLYER
PLAYER_EXTRA_SPECTATOR_ON
PLAYER_EXTRA_PVP_DEATH
PLAYER_EXTRA_SHOW_DK_PET
Definition at line 563 of file Player.h.
 {
     // gm abilities
     PLAYER_EXTRA_GM_ON              = 0x0001,
     PLAYER_EXTRA_ACCEPT_WHISPERS    = 0x0004,
     PLAYER_EXTRA_TAXICHEAT          = 0x0008,
     PLAYER_EXTRA_GM_INVISIBLE       = 0x0010,
     PLAYER_EXTRA_GM_CHAT            = 0x0020,               // Show GM badge in chat messages
     PLAYER_EXTRA_HAS_310_FLYER      = 0x0040,               // Marks if player already has 310% speed flying mount
     PLAYER_EXTRA_SPECTATOR_ON       = 0x0080,               // Marks if player is spectactor
     PLAYER_EXTRA_PVP_DEATH          = 0x0100,               // store PvP death status until corpse creating.
     PLAYER_EXTRA_SHOW_DK_PET        = 0x0400,               // Marks if player should see ghoul on login screen
 };
PlayerFieldByte2Flags
enum PlayerFieldByte2Flags
Enumerator
PLAYER_FIELD_BYTE2_NONE
PLAYER_FIELD_BYTE2_STEALTH
PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW
Definition at line 546 of file Player.h.
 {
     PLAYER_FIELD_BYTE2_NONE                 = 0x00,
     PLAYER_FIELD_BYTE2_STEALTH              = 0x20,
     PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW    = 0x40
 };
PlayerFieldByteFlags
enum PlayerFieldByteFlags
Enumerator
PLAYER_FIELD_BYTE_TRACK_STEALTHED
PLAYER_FIELD_BYTE_RELEASE_TIMER
PLAYER_FIELD_BYTE_NO_RELEASE_WINDOW
Definition at line 538 of file Player.h.
 {
     PLAYER_FIELD_BYTE_TRACK_STEALTHED   = 0x00000002,
     PLAYER_FIELD_BYTE_RELEASE_TIMER     = 0x00000008,       // Display time till auto release spirit
     PLAYER_FIELD_BYTE_NO_RELEASE_WINDOW = 0x00000010        // Display no "release spirit" window at all
 };
PlayerFieldBytes2Offsets
enum PlayerFieldBytes2Offsets
Enumerator
PLAYER_FIELD_BYTES_2_OFFSET_OVERRIDE_SPELLS_ID
PLAYER_FIELD_BYTES_2_OFFSET_IGNORE_POWER_REGEN_PREDICTION_MASK
PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION
Definition at line 523 of file Player.h.
 {
     PLAYER_FIELD_BYTES_2_OFFSET_OVERRIDE_SPELLS_ID                  = 0,    // uint16!
     PLAYER_FIELD_BYTES_2_OFFSET_IGNORE_POWER_REGEN_PREDICTION_MASK  = 2,
     PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION                         = 3
 };
PlayerFieldBytesOffsets
enum PlayerFieldBytesOffsets
Enumerator
PLAYER_FIELD_BYTES_OFFSET_FLAGS
PLAYER_FIELD_BYTES_OFFSET_RAF_GRANTABLE_LEVEL
PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES
PLAYER_FIELD_BYTES_OFFSET_LIFETIME_MAX_PVP_RANK
Definition at line 515 of file Player.h.
 {
     PLAYER_FIELD_BYTES_OFFSET_FLAGS                 = 0,
     PLAYER_FIELD_BYTES_OFFSET_RAF_GRANTABLE_LEVEL   = 1,
     PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES    = 2,
     PLAYER_FIELD_BYTES_OFFSET_LIFETIME_MAX_PVP_RANK = 3
 };
PlayerFlags
enum PlayerFlags
Enumerator
PLAYER_FLAGS_GROUP_LEADER
PLAYER_FLAGS_AFK
PLAYER_FLAGS_DND
PLAYER_FLAGS_GM
PLAYER_FLAGS_GHOST
PLAYER_FLAGS_RESTING
PLAYER_FLAGS_UNK6
PLAYER_FLAGS_UNK7
PLAYER_FLAGS_CONTESTED_PVP
PLAYER_FLAGS_IN_PVP
PLAYER_FLAGS_HIDE_HELM
PLAYER_FLAGS_HIDE_CLOAK
PLAYER_FLAGS_PLAYED_LONG_TIME
PLAYER_FLAGS_PLAYED_TOO_LONG
PLAYER_FLAGS_IS_OUT_OF_BOUNDS
PLAYER_FLAGS_DEVELOPER
PLAYER_FLAGS_UNK16
PLAYER_FLAGS_TAXI_BENCHMARK
PLAYER_FLAGS_PVP_TIMER
PLAYER_FLAGS_UBER
PLAYER_FLAGS_UNK20
PLAYER_FLAGS_UNK21
PLAYER_FLAGS_COMMENTATOR2
PLAYER_ALLOW_ONLY_ABILITY
PLAYER_FLAGS_UNK24
PLAYER_FLAGS_NO_XP_GAIN
PLAYER_FLAGS_UNK26
PLAYER_FLAGS_UNK27
PLAYER_FLAGS_UNK28
PLAYER_FLAGS_UNK29
PLAYER_FLAGS_UNK30
PLAYER_FLAGS_UNK31
Definition at line 455 of file Player.h.
 {
     PLAYER_FLAGS_GROUP_LEADER      = 0x00000001,
     PLAYER_FLAGS_AFK               = 0x00000002,
     PLAYER_FLAGS_DND               = 0x00000004,
     PLAYER_FLAGS_GM                = 0x00000008,
     PLAYER_FLAGS_GHOST             = 0x00000010,
     PLAYER_FLAGS_RESTING           = 0x00000020,
     PLAYER_FLAGS_UNK6              = 0x00000040,
     PLAYER_FLAGS_UNK7              = 0x00000080,               // pre-3.0.3 PLAYER_FLAGS_FFA_PVP flag for FFA PVP state
     PLAYER_FLAGS_CONTESTED_PVP     = 0x00000100,               // Player has been involved in a PvP combat and will be attacked by contested guards
     PLAYER_FLAGS_IN_PVP            = 0x00000200,
     PLAYER_FLAGS_HIDE_HELM         = 0x00000400,
     PLAYER_FLAGS_HIDE_CLOAK        = 0x00000800,
     PLAYER_FLAGS_PLAYED_LONG_TIME  = 0x00001000,               // played long time
     PLAYER_FLAGS_PLAYED_TOO_LONG   = 0x00002000,               // played too long time
     PLAYER_FLAGS_IS_OUT_OF_BOUNDS  = 0x00004000,
     PLAYER_FLAGS_DEVELOPER         = 0x00008000,               // <Dev> prefix for something?
     PLAYER_FLAGS_UNK16             = 0x00010000,               // pre-3.0.3 PLAYER_FLAGS_SANCTUARY flag for player entered sanctuary
     PLAYER_FLAGS_TAXI_BENCHMARK    = 0x00020000,               // taxi benchmark mode (on/off) (2.0.1)
     PLAYER_FLAGS_PVP_TIMER         = 0x00040000,               // 3.0.2, pvp timer active (after you disable pvp manually)
     PLAYER_FLAGS_UBER              = 0x00080000,
     PLAYER_FLAGS_UNK20             = 0x00100000,
     PLAYER_FLAGS_UNK21             = 0x00200000,
     PLAYER_FLAGS_COMMENTATOR2      = 0x00400000,
     PLAYER_ALLOW_ONLY_ABILITY      = 0x00800000,                // used by bladestorm and killing spree, allowed only spells with SPELL_ATTR0_USES_RANGED_SLOT, SPELL_EFFECT_ATTACK, checked only for active player
     PLAYER_FLAGS_UNK24             = 0x01000000,                // disabled all melee ability on tab include autoattack
     PLAYER_FLAGS_NO_XP_GAIN        = 0x02000000,
     PLAYER_FLAGS_UNK26             = 0x04000000,
     PLAYER_FLAGS_UNK27             = 0x08000000,
     PLAYER_FLAGS_UNK28             = 0x10000000,
     PLAYER_FLAGS_UNK29             = 0x20000000,
     PLAYER_FLAGS_UNK30             = 0x40000000,
     PLAYER_FLAGS_UNK31             = 0x80000000,
 };
PlayerLoginQueryIndex
enum PlayerLoginQueryIndex
Enumerator
PLAYER_LOGIN_QUERY_LOAD_FROM
PLAYER_LOGIN_QUERY_LOAD_AURAS
PLAYER_LOGIN_QUERY_LOAD_SPELLS
PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS
PLAYER_LOGIN_QUERY_LOAD_DAILY_QUEST_STATUS
PLAYER_LOGIN_QUERY_LOAD_REPUTATION
PLAYER_LOGIN_QUERY_LOAD_INVENTORY
PLAYER_LOGIN_QUERY_LOAD_ACTIONS
PLAYER_LOGIN_QUERY_LOAD_MAILS
PLAYER_LOGIN_QUERY_LOAD_MAIL_ITEMS
PLAYER_LOGIN_QUERY_LOAD_SOCIAL_LIST
PLAYER_LOGIN_QUERY_LOAD_HOME_BIND
PLAYER_LOGIN_QUERY_LOAD_SPELL_COOLDOWNS
PLAYER_LOGIN_QUERY_LOAD_DECLINED_NAMES
PLAYER_LOGIN_QUERY_LOAD_ACHIEVEMENTS
PLAYER_LOGIN_QUERY_LOAD_CRITERIA_PROGRESS
PLAYER_LOGIN_QUERY_LOAD_EQUIPMENT_SETS
PLAYER_LOGIN_QUERY_LOAD_ENTRY_POINT
PLAYER_LOGIN_QUERY_LOAD_GLYPHS
PLAYER_LOGIN_QUERY_LOAD_TALENTS
PLAYER_LOGIN_QUERY_LOAD_ACCOUNT_DATA
PLAYER_LOGIN_QUERY_LOAD_SKILLS
PLAYER_LOGIN_QUERY_LOAD_WEEKLY_QUEST_STATUS
PLAYER_LOGIN_QUERY_LOAD_RANDOM_BG
PLAYER_LOGIN_QUERY_LOAD_BANNED
PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS_REW
PLAYER_LOGIN_QUERY_LOAD_INSTANCE_LOCK_TIMES
PLAYER_LOGIN_QUERY_LOAD_SEASONAL_QUEST_STATUS
PLAYER_LOGIN_QUERY_LOAD_MONTHLY_QUEST_STATUS
PLAYER_LOGIN_QUERY_LOAD_BREW_OF_THE_MONTH
PLAYER_LOGIN_QUERY_LOAD_CORPSE_LOCATION
MAX_PLAYER_LOGIN_QUERY
Definition at line 835 of file Player.h.
 {
     PLAYER_LOGIN_QUERY_LOAD_FROM                    = 0,
     PLAYER_LOGIN_QUERY_LOAD_AURAS                   = 3,
     PLAYER_LOGIN_QUERY_LOAD_SPELLS                  = 4,
     PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS            = 5,
     PLAYER_LOGIN_QUERY_LOAD_DAILY_QUEST_STATUS      = 6,
     PLAYER_LOGIN_QUERY_LOAD_REPUTATION              = 7,
     PLAYER_LOGIN_QUERY_LOAD_INVENTORY               = 8,
     PLAYER_LOGIN_QUERY_LOAD_ACTIONS                 = 9,
     PLAYER_LOGIN_QUERY_LOAD_MAILS                   = 10,
     PLAYER_LOGIN_QUERY_LOAD_MAIL_ITEMS              = 11,
     PLAYER_LOGIN_QUERY_LOAD_SOCIAL_LIST             = 13,
     PLAYER_LOGIN_QUERY_LOAD_HOME_BIND               = 14,
     PLAYER_LOGIN_QUERY_LOAD_SPELL_COOLDOWNS         = 15,
     PLAYER_LOGIN_QUERY_LOAD_DECLINED_NAMES          = 16,
     PLAYER_LOGIN_QUERY_LOAD_ACHIEVEMENTS            = 18,
     PLAYER_LOGIN_QUERY_LOAD_CRITERIA_PROGRESS       = 19,
     PLAYER_LOGIN_QUERY_LOAD_EQUIPMENT_SETS          = 20,
     PLAYER_LOGIN_QUERY_LOAD_ENTRY_POINT             = 21,
     PLAYER_LOGIN_QUERY_LOAD_GLYPHS                  = 22,
     PLAYER_LOGIN_QUERY_LOAD_TALENTS                 = 23,
     PLAYER_LOGIN_QUERY_LOAD_ACCOUNT_DATA            = 24,
     PLAYER_LOGIN_QUERY_LOAD_SKILLS                  = 25,
     PLAYER_LOGIN_QUERY_LOAD_WEEKLY_QUEST_STATUS     = 26,
     PLAYER_LOGIN_QUERY_LOAD_RANDOM_BG               = 27,
     PLAYER_LOGIN_QUERY_LOAD_BANNED                  = 28,
     PLAYER_LOGIN_QUERY_LOAD_QUEST_STATUS_REW        = 29,
     PLAYER_LOGIN_QUERY_LOAD_INSTANCE_LOCK_TIMES     = 30,
     PLAYER_LOGIN_QUERY_LOAD_SEASONAL_QUEST_STATUS   = 31,
     PLAYER_LOGIN_QUERY_LOAD_MONTHLY_QUEST_STATUS    = 32,
     PLAYER_LOGIN_QUERY_LOAD_BREW_OF_THE_MONTH       = 34,
     PLAYER_LOGIN_QUERY_LOAD_CORPSE_LOCATION         = 35,
     MAX_PLAYER_LOGIN_QUERY
 };
PlayerMovementType
enum PlayerMovementType
Enumerator
MOVE_ROOT
MOVE_UNROOT
MOVE_WATER_WALK
MOVE_LAND_WALK
Definition at line 437 of file Player.h.
 {
     MOVE_ROOT       = 1,
     MOVE_UNROOT     = 2,
     MOVE_WATER_WALK = 3,
     MOVE_LAND_WALK  = 4
 };
PlayerRestState
enum PlayerRestState
Enumerator
REST_STATE_RESTED
REST_STATE_NOT_RAF_LINKED
REST_STATE_RAF_LINKED
Definition at line 952 of file Player.h.
 {
     REST_STATE_RESTED                                = 0x01,
     REST_STATE_NOT_RAF_LINKED                        = 0x02,
     REST_STATE_RAF_LINKED                            = 0x06
 };
PlayerSlots
enum PlayerSlots
Enumerator
PLAYER_SLOT_START
PLAYER_SLOT_END
PLAYER_SLOTS_COUNT
Definition at line 642 of file Player.h.
 {
     // first slot for item stored (in any way in player m_items data)
     PLAYER_SLOT_START           = 0,
     // last+1 slot for item stored (in any way in player m_items data)
     PLAYER_SLOT_END             = 150,
     PLAYER_SLOTS_COUNT          = (PLAYER_SLOT_END - PLAYER_SLOT_START)
 };
PlayerSpellState
enum PlayerSpellState
Enumerator
PLAYERSPELL_UNCHANGED
PLAYERSPELL_CHANGED
PLAYERSPELL_NEW
PLAYERSPELL_REMOVED
PLAYERSPELL_TEMPORARY
Definition at line 112 of file Player.h.
 {
     PLAYERSPELL_UNCHANGED = 0,
     PLAYERSPELL_CHANGED   = 1,
     PLAYERSPELL_NEW       = 2,
     PLAYERSPELL_REMOVED   = 3,
     PLAYERSPELL_TEMPORARY = 4
 };
PlayerUnderwaterState
enum PlayerUnderwaterState
Enumerator
UNDERWATER_NONE
UNDERWATER_INWATER
UNDERWATER_INLAVA
UNDERWATER_INSLIME
UNDERWATER_INDARKWATER
UNDERWATER_EXIST_TIMERS
Definition at line 93 of file Player.h.
 {
     UNDERWATER_NONE                     = 0x00,
     UNDERWATER_INWATER                  = 0x01,             // terrain type is water and player is afflicted by it
     UNDERWATER_INLAVA                   = 0x02,             // terrain type is lava and player is afflicted by it
     UNDERWATER_INSLIME                  = 0x04,             // terrain type is lava and player is afflicted by it
     UNDERWATER_INDARKWATER              = 0x08,             // terrain type is dark water and player is afflicted by it
     UNDERWATER_EXIST_TIMERS             = 0x10
 };
QuestSlotOffsets
enum QuestSlotOffsets
Enumerator
QUEST_ID_OFFSET
QUEST_STATE_OFFSET
QUEST_COUNTS_OFFSET
QUEST_TIME_OFFSET
Definition at line 601 of file Player.h.
 {
     QUEST_ID_OFFSET     = 0,
     QUEST_STATE_OFFSET  = 1,
     QUEST_COUNTS_OFFSET = 2,
     QUEST_TIME_OFFSET   = 4
 };
QuestSlotStateMask
enum QuestSlotStateMask
Enumerator
QUEST_STATE_NONE
QUEST_STATE_COMPLETE
QUEST_STATE_FAIL
Definition at line 611 of file Player.h.
 {
     QUEST_STATE_NONE     = 0x0000,
     QUEST_STATE_COMPLETE = 0x0001,
     QUEST_STATE_FAIL     = 0x0002
 };
ReferAFriendError
enum ReferAFriendError
Enumerator
ERR_REFER_A_FRIEND_NONE
ERR_REFER_A_FRIEND_NOT_REFERRED_BY
ERR_REFER_A_FRIEND_TARGET_TOO_HIGH
ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS
ERR_REFER_A_FRIEND_TOO_FAR
ERR_REFER_A_FRIEND_DIFFERENT_FACTION
ERR_REFER_A_FRIEND_NOT_NOW
ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I
ERR_REFER_A_FRIEND_NO_TARGET
ERR_REFER_A_FRIEND_NOT_IN_GROUP
ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I
ERR_REFER_A_FRIEND_SUMMON_COOLDOWN
ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL
ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S
Definition at line 934 of file Player.h.
 {
     ERR_REFER_A_FRIEND_NONE                          = 0x00,
     ERR_REFER_A_FRIEND_NOT_REFERRED_BY               = 0x01,
     ERR_REFER_A_FRIEND_TARGET_TOO_HIGH               = 0x02,
     ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS = 0x03,
     ERR_REFER_A_FRIEND_TOO_FAR                       = 0x04,
     ERR_REFER_A_FRIEND_DIFFERENT_FACTION             = 0x05,
     ERR_REFER_A_FRIEND_NOT_NOW                       = 0x06,
     ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I             = 0x07,
     ERR_REFER_A_FRIEND_NO_TARGET                     = 0x08,
     ERR_REFER_A_FRIEND_NOT_IN_GROUP                  = 0x09,
     ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I            = 0x0A,
     ERR_REFER_A_FRIEND_SUMMON_COOLDOWN               = 0x0B,
     ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL               = 0x0C,
     ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S              = 0x0D
 };
ReputationSource
enum ReputationSource
Enumerator
REPUTATION_SOURCE_KILL
REPUTATION_SOURCE_QUEST
REPUTATION_SOURCE_DAILY_QUEST
REPUTATION_SOURCE_WEEKLY_QUEST
REPUTATION_SOURCE_MONTHLY_QUEST
REPUTATION_SOURCE_REPEATABLE_QUEST
REPUTATION_SOURCE_SPELL
Definition at line 232 of file Player.h.
 {
     REPUTATION_SOURCE_KILL,
     REPUTATION_SOURCE_QUEST,
     REPUTATION_SOURCE_DAILY_QUEST,
     REPUTATION_SOURCE_WEEKLY_QUEST,
     REPUTATION_SOURCE_MONTHLY_QUEST,
     REPUTATION_SOURCE_REPEATABLE_QUEST,
     REPUTATION_SOURCE_SPELL
 };
RestFlag
enum RestFlag
Enumerator
REST_FLAG_IN_TAVERN
REST_FLAG_IN_CITY
REST_FLAG_IN_FACTION_AREA
Definition at line 785 of file Player.h.
 {
     REST_FLAG_IN_TAVERN         = 0x1,
     REST_FLAG_IN_CITY           = 0x2,
     REST_FLAG_IN_FACTION_AREA   = 0x4, // used with AREA_FLAG_REST_ZONE_*
 };
RuneCooldowns
enum RuneCooldowns
Enumerator
RUNE_BASE_COOLDOWN
RUNE_GRACE_PERIOD
RUNE_MISS_COOLDOWN
Definition at line 383 of file Player.h.
 {
     RUNE_BASE_COOLDOWN  = 10000,
     RUNE_GRACE_PERIOD   = 2500,     // xinef: maximum possible grace period
     RUNE_MISS_COOLDOWN  = 1500,     // cooldown applied on runes when the spell misses
 };
RuneType
enum RuneType
Enumerator
RUNE_BLOOD
RUNE_UNHOLY
RUNE_FROST
RUNE_DEATH
NUM_RUNE_TYPES
Definition at line 390 of file Player.h.
 {
     RUNE_BLOOD      = 0,
     RUNE_UNHOLY     = 1,
     RUNE_FROST      = 2,
     RUNE_DEATH      = 3,
     NUM_RUNE_TYPES  = 4
 };
SkillUpdateState
enum SkillUpdateState
Enumerator
SKILL_UNCHANGED
SKILL_CHANGED
SKILL_NEW
SKILL_DELETED
Definition at line 618 of file Player.h.
 {
     SKILL_UNCHANGED     = 0,
     SKILL_CHANGED       = 1,
     SKILL_NEW           = 2,
     SKILL_DELETED       = 3
 };
SpellModType
enum SpellModType
Enumerator
SPELLMOD_FLAT
SPELLMOD_PCT
Definition at line 86 of file Player.h.
 {
     SPELLMOD_FLAT         = 107,                            // SPELL_AURA_ADD_FLAT_MODIFIER
     SPELLMOD_PCT          = 108                             // SPELL_AURA_ADD_PCT_MODIFIER
 };
TalentTree
enum TalentTree
Enumerator
TALENT_TREE_WARRIOR_ARMS
TALENT_TREE_WARRIOR_FURY
TALENT_TREE_WARRIOR_PROTECTION
TALENT_TREE_PALADIN_HOLY
TALENT_TREE_PALADIN_PROTECTION
TALENT_TREE_PALADIN_RETRIBUTION
TALENT_TREE_HUNTER_BEAST_MASTERY
TALENT_TREE_HUNTER_MARKSMANSHIP
TALENT_TREE_HUNTER_SURVIVAL
TALENT_TREE_ROGUE_ASSASSINATION
TALENT_TREE_ROGUE_COMBAT
TALENT_TREE_ROGUE_SUBTLETY
TALENT_TREE_PRIEST_DISCIPLINE
TALENT_TREE_PRIEST_HOLY
TALENT_TREE_PRIEST_SHADOW
TALENT_TREE_DEATH_KNIGHT_BLOOD
TALENT_TREE_DEATH_KNIGHT_FROST
TALENT_TREE_DEATH_KNIGHT_UNHOLY
TALENT_TREE_SHAMAN_ELEMENTAL
TALENT_TREE_SHAMAN_ENHANCEMENT
TALENT_TREE_SHAMAN_RESTORATION
TALENT_TREE_MAGE_ARCANE
TALENT_TREE_MAGE_FIRE
TALENT_TREE_MAGE_FROST
TALENT_TREE_WARLOCK_AFFLICTION
TALENT_TREE_WARLOCK_DEMONOLOGY
TALENT_TREE_WARLOCK_DESTRUCTION
TALENT_TREE_DRUID_BALANCE
TALENT_TREE_DRUID_FERAL_COMBAT
TALENT_TREE_DRUID_RESTORATION
Definition at line 138 of file Player.h.
 {
     TALENT_TREE_WARRIOR_ARMS = 161,
     TALENT_TREE_WARRIOR_FURY = 164,
     TALENT_TREE_WARRIOR_PROTECTION = 163,
     TALENT_TREE_PALADIN_HOLY = 382,
     TALENT_TREE_PALADIN_PROTECTION = 383,
     TALENT_TREE_PALADIN_RETRIBUTION = 381,
     TALENT_TREE_HUNTER_BEAST_MASTERY = 361,
     TALENT_TREE_HUNTER_MARKSMANSHIP = 363,
     TALENT_TREE_HUNTER_SURVIVAL = 362,
     TALENT_TREE_ROGUE_ASSASSINATION = 182,
     TALENT_TREE_ROGUE_COMBAT = 181,
     TALENT_TREE_ROGUE_SUBTLETY = 183,
     TALENT_TREE_PRIEST_DISCIPLINE = 201,
     TALENT_TREE_PRIEST_HOLY = 202,
     TALENT_TREE_PRIEST_SHADOW = 203,
     TALENT_TREE_DEATH_KNIGHT_BLOOD = 398,
     TALENT_TREE_DEATH_KNIGHT_FROST = 399,
     TALENT_TREE_DEATH_KNIGHT_UNHOLY = 400,
     TALENT_TREE_SHAMAN_ELEMENTAL = 261,
     TALENT_TREE_SHAMAN_ENHANCEMENT = 263,
     TALENT_TREE_SHAMAN_RESTORATION = 262,
     TALENT_TREE_MAGE_ARCANE = 81,
     TALENT_TREE_MAGE_FIRE = 41,
     TALENT_TREE_MAGE_FROST = 61,
     TALENT_TREE_WARLOCK_AFFLICTION = 302,
     TALENT_TREE_WARLOCK_DEMONOLOGY = 303,
     TALENT_TREE_WARLOCK_DESTRUCTION = 301,
     TALENT_TREE_DRUID_BALANCE = 283,
     TALENT_TREE_DRUID_FERAL_COMBAT = 281,
     TALENT_TREE_DRUID_RESTORATION = 282
 };
TeleportToOptions
enum TeleportToOptions
Enumerator
TELE_TO_GM_MODE
TELE_TO_NOT_LEAVE_TRANSPORT
TELE_TO_NOT_LEAVE_COMBAT
TELE_TO_NOT_UNSUMMON_PET
TELE_TO_SPELL
TELE_TO_NOT_LEAVE_VEHICLE
TELE_TO_WITH_PET
TELE_TO_NOT_LEAVE_TAXI
Definition at line 792 of file Player.h.
 {
     TELE_TO_GM_MODE             = 0x01,
     TELE_TO_NOT_LEAVE_TRANSPORT = 0x02,
     TELE_TO_NOT_LEAVE_COMBAT    = 0x04,
     TELE_TO_NOT_UNSUMMON_PET    = 0x08,
     TELE_TO_SPELL               = 0x10,
     TELE_TO_NOT_LEAVE_VEHICLE   = 0x20,
     TELE_TO_WITH_PET            = 0x40,
     TELE_TO_NOT_LEAVE_TAXI      = 0x80
 };
TrainerSpellState
enum TrainerSpellState
Enumerator
TRAINER_SPELL_GREEN
TRAINER_SPELL_RED
TRAINER_SPELL_GRAY
TRAINER_SPELL_GREEN_DISABLED
Definition at line 206 of file Player.h.
 {
     TRAINER_SPELL_GREEN = 0,
     TRAINER_SPELL_RED   = 1,
     TRAINER_SPELL_GRAY  = 2,
     TRAINER_SPELL_GREEN_DISABLED = 10                       // custom value, not send to client: formally green but learn not allowed
 };
TransferAbortReason
enum TransferAbortReason
Enumerator
TRANSFER_ABORT_NONE
TRANSFER_ABORT_ERROR
TRANSFER_ABORT_MAX_PLAYERS
TRANSFER_ABORT_NOT_FOUND
TRANSFER_ABORT_TOO_MANY_INSTANCES
TRANSFER_ABORT_ZONE_IN_COMBAT
TRANSFER_ABORT_INSUF_EXPAN_LVL
TRANSFER_ABORT_DIFFICULTY
TRANSFER_ABORT_UNIQUE_MESSAGE
TRANSFER_ABORT_TOO_MANY_REALM_INSTANCES
TRANSFER_ABORT_NEED_GROUP
TRANSFER_ABORT_NOT_FOUND1
TRANSFER_ABORT_NOT_FOUND2
TRANSFER_ABORT_NOT_FOUND3
TRANSFER_ABORT_REALM_ONLY
TRANSFER_ABORT_MAP_NOT_ALLOWED
Definition at line 754 of file Player.h.
 {
     TRANSFER_ABORT_NONE                     = 0x00,
     TRANSFER_ABORT_ERROR                    = 0x01,
     TRANSFER_ABORT_MAX_PLAYERS              = 0x02,         // Transfer Aborted: instance is full
     TRANSFER_ABORT_NOT_FOUND                = 0x03,         // Transfer Aborted: instance not found
     TRANSFER_ABORT_TOO_MANY_INSTANCES       = 0x04,         // You have entered too many instances recently.
     TRANSFER_ABORT_ZONE_IN_COMBAT           = 0x06,         // Unable to zone in while an encounter is in progress.
     TRANSFER_ABORT_INSUF_EXPAN_LVL          = 0x07,         // You must have <TBC, WotLK> expansion installed to access this area.
     TRANSFER_ABORT_DIFFICULTY               = 0x08,         // <Normal, Heroic, Epic> difficulty mode is not available for %s.
     TRANSFER_ABORT_UNIQUE_MESSAGE           = 0x09,         // Until you've escaped TLK's grasp, you cannot leave this place!
     TRANSFER_ABORT_TOO_MANY_REALM_INSTANCES = 0x0A,         // Additional instances cannot be launched, please try again later.
     TRANSFER_ABORT_NEED_GROUP               = 0x0B,         // 3.1
     TRANSFER_ABORT_NOT_FOUND1               = 0x0C,         // 3.1
     TRANSFER_ABORT_NOT_FOUND2               = 0x0D,         // 3.1
     TRANSFER_ABORT_NOT_FOUND3               = 0x0E,         // 3.2
     TRANSFER_ABORT_REALM_ONLY               = 0x0F,         // All players on party must be from the same realm.
     TRANSFER_ABORT_MAP_NOT_ALLOWED          = 0x10,         // Map can't be entered at this time.
 };
Function Documentation
AddItemsSetItem()
void AddItemsSetItem (Player * player, Item * item)
Definition at line 30 of file Item.cpp.
 {
     ItemTemplate const* proto = item->GetTemplate();
     uint32 setid = proto->ItemSet;
     ItemSetEntry const* set = sItemSetStore.LookupEntry(setid);
     if (!set)
     {
         LOG_ERROR("sql.sql", "Item set %u for item (id %u) not found, mods not applied.", setid, proto->ItemId);
         return;
     }
     if (set->required_skill_id && player->GetSkillValue(set->required_skill_id) < set->required_skill_value)
         return;
     ItemSetEffect* eff = nullptr;
     for (size_t x = 0; x < player->ItemSetEff.size(); ++x)
     {
         if (player->ItemSetEff[x] && player->ItemSetEff[x]->setid == setid)
         {
             eff = player->ItemSetEff[x];
             break;
         }
     }
     if (!eff)
     {
         eff = new ItemSetEffect();
         eff->setid = setid;
         size_t x = 0;
         for (; x < player->ItemSetEff.size(); ++x)
             if (!player->ItemSetEff[x])
                 break;
         if (x < player->ItemSetEff.size())
             player->ItemSetEff[x] = eff;
         else
             player->ItemSetEff.push_back(eff);
     }
     ++eff->item_count;
     for (uint32 x = 0; x < MAX_ITEM_SET_SPELLS; ++x)
     {
         if (!set->spells [x])
             continue;
         //not enough for  spell
         if (set->items_to_triggerspell[x] > eff->item_count)
             continue;
         uint32 z = 0;
         for (; z < MAX_ITEM_SET_SPELLS; ++z)
             if (eff->spells[z] && eff->spells[z]->Id == set->spells[x])
                 break;
         if (z < MAX_ITEM_SET_SPELLS)
             continue;
         //new spell
         for (uint32 y = 0; y < MAX_ITEM_SET_SPELLS; ++y)
         {
             if (!eff->spells[y])                             // free slot
             {
                 SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(set->spells[x]);
                 if (!spellInfo)
                 {
                     LOG_ERROR("entities.item", "WORLD: unknown spell id %u in items set %u effects", set->spells[x], setid);
                     break;
                 }
                 // spell casted only if fit form requirement, in other case will casted at form change
                 if (sScriptMgr->CanItemApplyEquipSpell(player, item))
                 {
                     player->ApplyEquipSpell(spellInfo, nullptr, true);
                 }
                 eff->spells[y] = spellInfo;
                 break;
             }
         }
     }
 }
References Player::ApplyEquipSpell(), Player::GetSkillValue(), Item::GetTemplate(), SpellInfo::Id, ItemSetEffect::item_count, ItemTemplate::ItemId, ItemTemplate::ItemSet, Player::ItemSetEff, LOG_ERROR, MAX_ITEM_SET_SPELLS, set(), ItemSetEffect::setid, sItemSetStore, ItemSetEffect::spells, sScriptMgr, and sSpellMgr.
Referenced by Player::_ApplyAllItemMods(), and Player::EquipItem().
operator<<()
std::ostringstream& operator<< (std::ostringstream & ss, PlayerTaxi const & taxi)
Definition at line 182 of file PlayerTaxi.cpp.
 {
     for (uint8 i = 0; i < TaxiMaskSize; ++i)
         ss << taxi.m_taximask[i] << ' ';
     return ss;
 }
RemoveItemsSetItem()
void RemoveItemsSetItem (Player * player, ItemTemplate const * proto)
Definition at line 116 of file Item.cpp.
 {
     uint32 setid = proto->ItemSet;
     ItemSetEntry const* set = sItemSetStore.LookupEntry(setid);
     if (!set)
     {
         LOG_ERROR("sql.sql", "Item set #%u for item #%u not found, mods not removed.", setid, proto->ItemId);
         return;
     }
     ItemSetEffect* eff = nullptr;
     size_t setindex = 0;
     for (; setindex < player->ItemSetEff.size(); setindex++)
     {
         if (player->ItemSetEff[setindex] && player->ItemSetEff[setindex]->setid == setid)
         {
             eff = player->ItemSetEff[setindex];
             break;
         }
     }
     // can be in case now enough skill requirement for set appling but set has been appliend when skill requirement not enough
     if (!eff)
         return;
     --eff->item_count;
     for (uint32 x = 0; x < MAX_ITEM_SET_SPELLS; x++)
     {
         if (!set->spells[x])
             continue;
         // enough for spell
         if (set->items_to_triggerspell[x] <= eff->item_count)
             continue;
         for (uint32 z = 0; z < MAX_ITEM_SET_SPELLS; z++)
         {
             if (eff->spells[z] && eff->spells[z]->Id == set->spells[x])
             {
                 // spell can be not active if not fit form requirement
                 player->ApplyEquipSpell(eff->spells[z], nullptr, false);
                 eff->spells[z] = nullptr;
                 break;
             }
         }
     }
     if (!eff->item_count)                                    //all items of a set were removed
     {
         ASSERT(eff == player->ItemSetEff[setindex]);
         delete eff;
         player->ItemSetEff[setindex] = nullptr;
     }
 }
References Player::ApplyEquipSpell(), ASSERT, SpellInfo::Id, ItemSetEffect::item_count, ItemTemplate::ItemId, ItemTemplate::ItemSet, Player::ItemSetEff, LOG_ERROR, MAX_ITEM_SET_SPELLS, set(), sItemSetStore, and ItemSetEffect::spells.
Referenced by Player::_RemoveAllItemMods(), Player::DestroyItem(), and Player::RemoveItem().