Azerotcore-wotlk: go_skull_pile Class Reference
go_skull_pile Class Reference
Public Member Functions
go_skull_pile ()
bool OnGossipSelect (Player *player, GameObject *go, uint32 sender, uint32 action) override
bool OnGossipHello (Player *player, GameObject *go) override
void SendActionMenu (Player *player, GameObject *, uint32 action)
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 774 of file zone_terokkar_forest.cpp.
Constructor & Destructor Documentation
go_skull_pile()
go_skull_pile::go_skull_pile () inline
Definition at line 777 of file zone_terokkar_forest.cpp.
 : GameObjectScript("go_skull_pile") { }
Member Function Documentation
OnGossipHello()
bool go_skull_pile::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 791 of file zone_terokkar_forest.cpp.
     {
         if ((player->GetQuestStatus(11885) == QUEST_STATUS_INCOMPLETE) || player->GetQuestRewardStatus(11885))
         {
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_S_DARKSCREECHER_AKKARAI, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_S_KARROG, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_S_GEZZARAK_THE_HUNTRESS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_S_VAKKIZ_THE_WINDRAGER, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
         }
         SendGossipMenuFor(player, go->GetGOInfo()->questgiver.gossipID, go->GetGUID());
         return true;
     }
References AddGossipItemFor(), GameObject::GetGOInfo(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_S_DARKSCREECHER_AKKARAI, GOSSIP_S_GEZZARAK_THE_HUNTRESS, GOSSIP_S_KARROG, GOSSIP_S_VAKKIZ_THE_WINDRAGER, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, GameObjectTemplate::questgiver, and SendGossipMenuFor().
OnGossipSelect()
bool go_skull_pile::OnGossipSelect (Player * player, GameObject * go, uint32 sender, uint32 action) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 779 of file zone_terokkar_forest.cpp.
     {
         ClearGossipMenuFor(player);
         switch (sender)
         {
             case GOSSIP_SENDER_MAIN:
                 SendActionMenu(player, go, action);
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), GOSSIP_SENDER_MAIN, and SendActionMenu().
SendActionMenu()
void go_skull_pile::SendActionMenu (Player * player, GameObject * , uint32 action) inline
Definition at line 805 of file zone_terokkar_forest.cpp.
     {
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 player->CastSpell(player, 40642, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 player->CastSpell(player, 40640, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 player->CastSpell(player, 40632, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 4:
                 player->CastSpell(player, 40644, false);
                 break;
         }
     }
References Unit::CastSpell(), and GOSSIP_ACTION_INFO_DEF.
Referenced by OnGossipSelect().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_terokkar_forest.cpp