Azerotcore-wotlk: npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI Struct Reference
npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI Struct Reference
Public Member Functions
npc_enslaved_netherwing_drakeAI (Creature *creature)
void Reset () override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid PlayerGUID
uint32 FlyTimer
bool Tapped
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 450 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_enslaved_netherwing_drakeAI()
npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::npc_enslaved_netherwing_drakeAI (Creature * creature) inline
Definition at line 452 of file zone_shadowmoon_valley.cpp.
                                                             : ScriptedAI(creature)
         {
             PlayerGUID.Clear();
             Tapped = false;
             Reset();
         }
References ObjectGuid::Clear(), PlayerGUID, Reset(), and Tapped.
Member Function Documentation
MovementInform()
void npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 498 of file zone_shadowmoon_valley.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (id == 1)
             {
                 me->SetVisible(false);
                 me->SetDisableGravity(false);
                 Unit::DealDamage(me, me, me->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                 me->RemoveCorpse();
             }
             me->DespawnOrUnsummon(1);
         }
References Unit::DealDamage(), Creature::DespawnOrUnsummon(), DIRECT_DAMAGE, Unit::GetHealth(), ScriptedAI::me, POINT_MOTION_TYPE, Creature::RemoveCorpse(), Creature::SetDisableGravity(), Unit::SetVisible(), and SPELL_SCHOOL_MASK_NORMAL.
Reset()
void npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 463 of file zone_shadowmoon_valley.cpp.
         {
             if (!Tapped)
                 me->SetFaction(FACTION_ORC_DRAGONMAW);
             FlyTimer = 1000;
             me->SetDisableGravity(false);
             me->SetVisible(true);
         }
References FACTION_ORC_DRAGONMAW, FlyTimer, ScriptedAI::me, Creature::SetDisableGravity(), Unit::SetFaction(), Unit::SetVisible(), and Tapped.
Referenced by npc_enslaved_netherwing_drakeAI().
SpellHit()
void npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 473 of file zone_shadowmoon_valley.cpp.
         {
             if (!caster)
                 return;
             if (caster->GetTypeId() == TYPEID_PLAYER && spell->Id == SPELL_HIT_FORCE_OF_NELTHARAKU && !Tapped)
             {
                 Tapped = true;
                 PlayerGUID = caster->GetGUID();
                 me->SetFaction(FACTION_FLAYER_HUNTER); // Not sure if this is correct, it was taken off of Mordenai.
                 Unit* Dragonmaw = me->FindNearestCreature(NPC_DRAGONMAW_SUBJUGATOR, 50);
                 if (Dragonmaw)
                 {
                     me->AddThreat(Dragonmaw, 100000.0f);
                     AttackStart(Dragonmaw);
                 }
                 HostileReference* ref = me->getThreatMgr().getOnlineContainer().getReferenceByTarget(caster);
                 if (ref)
                     ref->removeReference();
             }
         }
References Unit::AddThreat(), ScriptedAI::AttackStart(), FACTION_FLAYER_HUNTER, WorldObject::FindNearestCreature(), Object::GetGUID(), ThreatMgr::getOnlineContainer(), ThreatContainer::getReferenceByTarget(), Unit::getThreatMgr(), Object::GetTypeId(), SpellInfo::Id, ScriptedAI::me, NPC_DRAGONMAW_SUBJUGATOR, PlayerGUID, HostileReference::removeReference(), Unit::SetFaction(), SPELL_HIT_FORCE_OF_NELTHARAKU, Tapped, and TYPEID_PLAYER.
UpdateAI()
void npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 513 of file zone_shadowmoon_valley.cpp.
         {
             if (!UpdateVictim())
             {
                 if (Tapped)
                 {
                     if (FlyTimer <= diff)
                     {
                         Tapped = false;
                         if (PlayerGUID)
{
                             Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
                             if (player && player->GetQuestStatus(10854) == QUEST_STATUS_INCOMPLETE)
{
                                 DoCast(player, SPELL_FORCE_OF_NELTHARAKU, true);
                                 /*
                                 float x, y, z;
                                 me->GetPosition(x, y, z);
                                 float dx, dy, dz;
                                 me->GetRandomPoint(x, y, z, 20, dx, dy, dz);
                                 dz += 20; // so it's in the air, not ground*/
                                 Position pos;
                                 if (Unit* EscapeDummy = me->FindNearestCreature(NPC_ESCAPE_DUMMY, 30))
                                     pos = EscapeDummy->GetPosition();
                                 else
{
                                     pos = me->GetRandomNearPosition(20);
                                     pos.m_positionZ += 25;
                                 }
                                 me->SetDisableGravity(true);
                                 me->GetMotionMaster()->MovePoint(1, pos);
                             }
                         }
                     }
                     else FlyTimer -= diff;
                 }
                 return;
             }
             DoMeleeAttackIfReady();
         }
References UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), WorldObject::FindNearestCreature(), FlyTimer, Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPosition(), Player::GetQuestStatus(), WorldObject::GetRandomNearPosition(), Position::m_positionZ, ScriptedAI::me, MotionMaster::MovePoint(), NPC_ESCAPE_DUMMY, PlayerGUID, QUEST_STATUS_INCOMPLETE, Creature::SetDisableGravity(), SPELL_FORCE_OF_NELTHARAKU, Tapped, and CreatureAI::UpdateVictim().
Member Data Documentation
FlyTimer
uint32 npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::FlyTimer
Definition at line 460 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), and UpdateAI().
PlayerGUID
ObjectGuid npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::PlayerGUID
Definition at line 459 of file zone_shadowmoon_valley.cpp.
Referenced by npc_enslaved_netherwing_drakeAI(), SpellHit(), and UpdateAI().
Tapped
bool npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::Tapped
Definition at line 461 of file zone_shadowmoon_valley.cpp.
Referenced by npc_enslaved_netherwing_drakeAI(), Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp