Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/emitter.h File Reference
emitter.h File Reference
#include "jemalloc/internal/ql.h"
Classes
struct emitter_col_s
struct emitter_row_s
struct emitter_s
Macros
#define BUF_SIZE 256
#define FMT_SIZE 10
#define EMIT_SIMPLE(type, format)
Typedefs
typedef enum emitter_output_e emitter_output_t
typedef enum emitter_justify_e emitter_justify_t
typedef enum emitter_type_e emitter_type_t
typedef struct emitter_col_s emitter_col_t
typedef struct emitter_row_s emitter_row_t
typedef struct emitter_s emitter_t
Enumerations
enum emitter_output_e { emitter_output_json , emitter_output_table }
enum emitter_justify_e { emitter_justify_left , emitter_justify_right , emitter_justify_none }
enum emitter_type_e {
emitter_type_bool , emitter_type_int , emitter_type_unsigned , emitter_type_uint32 ,
emitter_type_uint64 , emitter_type_size , emitter_type_ssize , emitter_type_string ,
emitter_type_title
}
Functions
static void emitter_printf (emitter_t *emitter, const char *format,...)
static const char * JEMALLOC_FORMAT_ARG (3) emitter_gen_fmt(char *out_fmt
if (justify==emitter_justify_none)
assert (written< out_size)
static void emitter_print_value (emitter_t *emitter, emitter_justify_t justify, int width, emitter_type_t value_type, const void *value)
static void emitter_nest_inc (emitter_t *emitter)
static void emitter_nest_dec (emitter_t *emitter)
static void emitter_indent (emitter_t *emitter)
static void emitter_json_key_prefix (emitter_t *emitter)
static void emitter_init (emitter_t *emitter, emitter_output_t emitter_output, void(*write_cb)(void *, const char *), void *cbopaque)
static void emitter_json_key (emitter_t *emitter, const char *json_key)
static void emitter_json_value (emitter_t *emitter, emitter_type_t value_type, const void *value)
static void emitter_json_kv (emitter_t *emitter, const char *json_key, emitter_type_t value_type, const void *value)
static void emitter_json_array_begin (emitter_t *emitter)
static void emitter_json_array_kv_begin (emitter_t *emitter, const char *json_key)
static void emitter_json_array_end (emitter_t *emitter)
static void emitter_json_object_begin (emitter_t *emitter)
static void emitter_json_object_kv_begin (emitter_t *emitter, const char *json_key)
static void emitter_json_object_end (emitter_t *emitter)
static void emitter_table_dict_begin (emitter_t *emitter, const char *table_key)
static void emitter_table_dict_end (emitter_t *emitter)
static void emitter_table_kv_note (emitter_t *emitter, const char *table_key, emitter_type_t value_type, const void *value, const char *table_note_key, emitter_type_t table_note_value_type, const void *table_note_value)
static void emitter_table_kv (emitter_t *emitter, const char *table_key, emitter_type_t value_type, const void *value)
static void emitter_table_printf (emitter_t *emitter, const char *format,...)
static void emitter_table_row (emitter_t *emitter, emitter_row_t *row)
static void emitter_row_init (emitter_row_t *row)
static void emitter_col_init (emitter_col_t *col, emitter_row_t *row)
static void emitter_kv_note (emitter_t *emitter, const char *json_key, const char *table_key, emitter_type_t value_type, const void *value, const char *table_note_key, emitter_type_t table_note_value_type, const void *table_note_value)
static void emitter_kv (emitter_t *emitter, const char *json_key, const char *table_key, emitter_type_t value_type, const void *value)
static void emitter_dict_begin (emitter_t *emitter, const char *json_key, const char *table_header)
static void emitter_dict_end (emitter_t *emitter)
static void emitter_begin (emitter_t *emitter)
static void emitter_end (emitter_t *emitter)
Variables
static const char size_t out_size
static const char size_t const char * fmt_specifier
static const char size_t const char emitter_justify_t justify
static const char size_t const char emitter_justify_t int width
else
return out_fmt
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 256
EMIT_SIMPLE
#define EMIT_SIMPLE (type, format)
Value:
    emitter_printf(emitter,                     \
        emitter_gen_fmt(fmt, FMT_SIZE, format, justify, width), \
        *(const type *)value);
FMT_SIZE
#define FMT_SIZE 10
Typedef Documentation
emitter_col_t
typedef struct emitter_col_s emitter_col_t
Definition at line 1 of file emitter.h.
emitter_justify_t
typedef enum emitter_justify_e emitter_justify_t
Definition at line 1 of file emitter.h.
emitter_output_t
typedef enum emitter_output_e emitter_output_t
Definition at line 1 of file emitter.h.
emitter_row_t
typedef struct emitter_row_s emitter_row_t
Definition at line 1 of file emitter.h.
emitter_t
typedef struct emitter_s emitter_t
Definition at line 1 of file emitter.h.
emitter_type_t
typedef enum emitter_type_e emitter_type_t
Definition at line 1 of file emitter.h.
Enumeration Type Documentation
emitter_justify_e
enum emitter_justify_e
Enumerator
emitter_justify_left
emitter_justify_right
emitter_justify_none
Definition at line 13 of file emitter.h.
{
     emitter_justify_left,
     emitter_justify_right,
     /* Not for users; just to pass to internal functions. */
     emitter_justify_none
 };
emitter_output_e
enum emitter_output_e
Enumerator
emitter_output_json
emitter_output_table
Definition at line 7 of file emitter.h.
                       {
     emitter_output_json,
     emitter_output_table
 };
emitter_type_e
enum emitter_type_e
Enumerator
emitter_type_bool
emitter_type_int
emitter_type_unsigned
emitter_type_uint32
emitter_type_uint64
emitter_type_size
emitter_type_ssize
emitter_type_string
emitter_type_title
Definition at line 21 of file emitter.h.
                     {
     emitter_type_bool,
     emitter_type_int,
     emitter_type_unsigned,
     emitter_type_uint32,
     emitter_type_uint64,
     emitter_type_size,
     emitter_type_ssize,
     emitter_type_string,
     /*
      * A title is a column title in a table; it's just a string, but it's
      * not quoted.
      */
     emitter_type_title,
 };
Function Documentation
assert()
assert ()
Referenced by _db_suicide_(), arena_bin_choose_lock(), arena_bin_lower_slab(), arena_bin_malloc_hard(), arena_bin_slabs_full_insert(), arena_bin_slabs_nonfull_insert(), arena_bind(), arena_choose_hard(), arena_choose_huge(), arena_choose_impl(), arena_dalloc(), arena_dalloc_bin_slab(), arena_dalloc_no_tcache(), arena_dalloc_promoted(), arena_decay_backlog_update(), arena_decay_backlog_update_last(), arena_decay_epoch_advance_helper(), arena_decay_init(), arena_decay_to_limit(), arena_destroy(), arena_get(), arena_i_decay(), arena_i_destroy_ctl(), arena_init_locked(), arena_is_auto(), arena_malloc(), arena_malloc_hard(), arena_malloc_small(), arena_maybe_decay(), arena_nactive_sub(), arena_new(), arena_prof_alloc_time_get(), arena_prof_alloc_time_set(), arena_prof_demote(), arena_prof_promote(), arena_prof_tctx_get(), arena_prof_tctx_reset(), arena_prof_tctx_set(), arena_ralloc_no_move(), arena_reset(), arena_reset_finish_background_thread(), arena_reset_prepare_background_thread(), arena_retain_grow_limit_get_set(), arena_salloc(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_slab_alloc(), arena_slab_reg_alloc(), arena_slab_reg_alloc_batch(), arena_slab_reg_dalloc(), arena_slab_regind(), arena_stats_init(), arena_stats_merge(), arena_stats_sub_u64(), arena_stats_sub_zu(), arena_tcache_fill_small(), arena_tdata_get_hard(), arena_vsalloc(), arenas_i(), arenas_i2a_impl(), arenas_i_impl(), assert_tsd_data_cleanup_done(), background_thread_boot1(), background_thread_wakeup_time_get(), base_auto_thp_switch(), base_block_alloc(), base_extent_alloc(), base_extent_bump_alloc_helper(), base_extent_bump_alloc_post(), base_get_num_blocks(), base_map(), base_new(), base_stats_get(), base_unmap(), DBCFile::begin(), bin_boot(), bitmap_ffu(), bitmap_get(), bitmap_info_init(), bitmap_set(), bitmap_sfu(), bitmap_unset(), bootstrap_calloc(), boss_flame_leviathan::boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_kologarn::boss_kologarnAI::boss_kologarnAI(), cache_bin_dalloc_easy(), choose_arena(), chunk_alloc(), chunk_alloc_dss(), chunk_alloc_mmap(), chunk_alloc_mmap_slow(), chunk_boot(), chunk_dealloc(), chunk_recycle(), chunk_unmap(), ckh_count(), ckh_delete(), ckh_evict_reloc_insert(), ckh_insert(), ckh_isearch(), ckh_new(), ckh_pointer_hash(), ckh_remove(), ckh_search(), ckh_string_keycomp(), closedir(), G3D::Matrix3::column(), compute_size_with_overflow(), WMOGroup::ConvertToVMAPGroupWmo(), ctl_arena_stats_sdmerge(), ctl_bymib(), ctl_lookup(), div_compute(), div_init(), emitter_begin(), emitter_end(), emitter_json_array_end(), emitter_json_object_end(), emitter_print_value(), DBCFile::end(), experimental_utilization_batch_query_ctl(), experimental_utilization_query_ctl(), extent_activate_locked(), extent_addr_get(), extent_addr_randomize(), extent_alloc_core(), extent_alloc_default(), extent_alloc_dss(), extent_alloc_mmap(), extent_alloc_retained(), extent_alloc_wrapper(), extent_arena_ind_get(), extent_base_get(), extent_binshard_get(), extent_binshard_set(), extent_can_coalesce(), extent_coalesce(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_deactivate_locked(), extent_destroy_wrapper(), extent_dss_extending_finish(), extent_gdump_sub(), extent_grow_retained(), extent_head_no_merge(), extent_init(), extent_interior_deregister(), extent_interior_register(), extent_lock(), extent_lock2(), extent_merge_impl(), extent_nfree_binshard_set(), extent_nfree_dec(), extent_nfree_get(), extent_nfree_inc(), extent_nfree_set(), extent_nfree_sub(), extent_record(), extent_recycle(), extent_recycle_extract(), extent_recycle_split(), extent_reregister(), extent_rtree_leaf_elms_lookup(), extent_size_quantize_ceil(), extent_size_quantize_floor(), extent_size_set(), extent_slab_data_get(), extent_slab_data_get_const(), extent_split_impl(), extent_split_interior(), extent_szind_get(), extent_szind_get_maybe_invalid(), extent_szind_set(), extent_unlock(), extent_unlock2(), extent_util_stats_get(), extent_util_stats_verbose_get(), extents_alloc(), extents_dalloc(), extents_first_fit_locked(), extents_fit_alignment(), extents_insert_locked(), extents_remove_locked(), Doodad::ExtractSet(), G3D::BufferPool::free(), free_fastpath(), get_rate_str(), DBCFile::Record::getByte(), DBCFile::Record::getFloat(), DBCFile::Record::getInt(), DBCFile::getMaxId(), DBCFile::getRecord(), DBCFile::Record::getString(), DBCFile::Record::getUInt(), hash(), hook_install_locked(), hook_remove(), hook_remove_locked(), huge_dalloc(), huge_prof_ctx_get(), huge_prof_ctx_set(), huge_ralloc_no_move(), huge_salloc(), iaalloc(), iallocztm(), idalloct(), idalloctm(), ifree(), imalloc(), imalloc_body(), imalloc_no_sample(), imalloc_sample(), imalloct(), init_opt_stats_print_opts(), ipalloct(), ipallocztm(), iralloct(), isalloc(), isfree(), ixalloc(), ixallocx_prof(), je_dallocx(), je_malloc_usable_size(), je_nallocx(), je_rallocx(), je_realloc(), je_sallocx(), je_xallocx(), JEMALLOC_ATTR(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), large_malloc(), large_palloc(), large_ralloc(), large_ralloc_no_move(), large_ralloc_no_move_expand(), large_ralloc_no_move_shrink(), lg_floor(), log_var_matches_segment(), log_var_update_state(), malloc_abort_invalid_conf(), malloc_getcpu(), malloc_init_hard(), malloc_init_hard_cleanup(), malloc_init_narenas(), malloc_narenas_default(), malloc_tsd_cleanup_register(), mutex_addr_comp(), nstime_add(), nstime_divide(), nstime_iadd(), nstime_idivide(), nstime_imultiply(), nstime_isubtract(), nstime_subtract(), obtain_malloc_conf(), opendir(), os_pages_map(), os_pages_trim(), os_pages_unmap(), pages_boot(), pages_commit_impl(), pages_dodump(), pages_dontdump(), pages_huge_impl(), pages_map(), pages_map_slow(), pages_nohuge_impl(), pages_purge_forced(), pages_purge_lazy(), pages_set_thp_state(), pages_trim(), pages_unmap(), percpu_arena_as_initialized(), percpu_arena_choose(), percpu_arena_ind_limit(), percpu_arena_update(), G3D::Matrix3::polarDecomposition(), post_reentrancy(), pow2_ceil_u32(), pow2_ceil_u64(), pre_reentrancy(), prng_lg_range_u32(), prng_lg_range_u64(), prng_lg_range_zu(), prng_range_u32(), prng_range_u64(), prng_range_zu(), prof_accum_add(), prof_alloc_prep(), prof_alloc_time_get(), prof_alloc_time_set(), prof_dump(), prof_dump_close(), prof_dump_gctx(), prof_dump_write(), prof_enter(), prof_fdump(), prof_free(), prof_free_sampled_object(), prof_gctx_try_destroy(), prof_leave(), prof_log_bt_index(), prof_log_thr_index(), prof_malloc(), prof_mdump(), prof_realloc(), prof_reset(), prof_tctx_destroy(), prof_tctx_get(), prof_tctx_reset(), prof_tctx_set(), prof_tdata_destroy_locked(), prof_tdata_get(), quarantine(), quarantine_drain_one(), readdir(), G3D::Matrix3::row(), rtree_child_leaf_read(), rtree_child_leaf_tryread(), rtree_child_node_read(), rtree_child_node_tryread(), rtree_clear(), rtree_leaf_elm_lookup(), rtree_leaf_elm_lookup_hard(), rtree_leaf_elm_szind_slab_update(), rtree_leaf_elm_szind_write(), rtree_new(), rtree_read(), rtree_szind_slab_read_fast(), rtree_szind_slab_update(), rtree_write(), sa2u(), safety_check_set_redzone(), sc_data_init(), sc_data_update_sc_slab_size(), sc_data_update_slab_size(), sdallocx_default(), sfmt_fill_array32(), sfmt_fill_array64(), sfmt_genrand_uint64(), size_class(), size_classes(), sz_index2size(), sz_index2size_lookup(), sz_pind2sz(), sz_pind2sz_lookup(), sz_s2u_lookup(), sz_sa2u(), sz_size2index_lookup(), tcache_alloc_large(), tcache_alloc_small(), tcache_alloc_small_hard(), tcache_arena_associate(), tcache_arena_dissociate(), tcache_available(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_cleanup(), tcache_dalloc_large(), tcache_dalloc_small(), tcache_flush(), tcache_flush_cache(), tcache_init(), tcache_large_bin_get(), tcache_small_bin_get(), G3D::BufferPool::tinyFree(), G3D::BufferPool::tinyMalloc(), tsd_add_nominal(), tsd_assert_fast(), tsd_data_init_nocleanup(), tsd_fetch_slow(), tsd_force_recompute(), tsd_get(), tsd_remove_nominal(), tsd_set(), tsd_state_set(), tsd_tcache_data_init(), tsdn_tsd(), witness_tsdn_tsd(), zone_force_lock(), zone_force_unlock(), and zone_free_definite_size().
emitter_begin()
static void emitter_begin (emitter_t * emitter) inline static
Definition at line 461 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         assert(emitter->nesting_depth == 0);
         emitter_printf(emitter, "{");
         emitter_nest_inc(emitter);
     } else {
         /*
          * This guarantees that we always call write_cb at least once.
          * This is useful if some invariant is established by each call
          * to write_cb, but doesn't hold initially: e.g., some buffer
          * holds a null-terminated string.
          */
         emitter_printf(emitter, "%s", "");
     }
 }
References assert(), emitter_nest_inc(), emitter_output_json, emitter_printf(), emitter_s::nesting_depth, and emitter_s::output.
Referenced by prof_log_stop(), and stats_print().
emitter_col_init()
static void emitter_col_init (emitter_col_t * col, emitter_row_t * row) inline static
Definition at line 403 of file emitter.h.
{
     ql_elm_new(col, link);
     ql_tail_insert(&row->cols, col, link);
 }
References ql_elm_new, and ql_tail_insert.
Referenced by mutex_stats_init_cols(), and stats_arena_print().
emitter_dict_begin()
static void emitter_dict_begin (emitter_t * emitter, const char * json_key, const char * table_header) inline static
Definition at line 441 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key(emitter, json_key);
         emitter_json_object_begin(emitter);
     } else {
         emitter_table_dict_begin(emitter, table_header);
     }
 }
References emitter_json_key(), emitter_json_object_begin(), emitter_output_json, emitter_table_dict_begin(), and emitter_s::output.
Referenced by stats_general_print().
emitter_dict_end()
static void emitter_dict_end (emitter_t * emitter) inline static
Definition at line 452 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_object_end(emitter);
     } else {
         emitter_table_dict_end(emitter);
     }
 }
References emitter_json_object_end(), emitter_output_json, emitter_table_dict_end(), and emitter_s::output.
Referenced by stats_general_print().
emitter_end()
static void emitter_end (emitter_t * emitter) inline static
Definition at line 478 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         assert(emitter->nesting_depth == 1);
         emitter_nest_dec(emitter);
         emitter_printf(emitter, "\n}\n");
     }
 }
References assert(), emitter_nest_dec(), emitter_output_json, emitter_printf(), emitter_s::nesting_depth, and emitter_s::output.
Referenced by prof_log_stop(), and stats_print().
emitter_indent()
static void emitter_indent (emitter_t * emitter) inline static
Definition at line 196 of file emitter.h.
{
     int amount = emitter->nesting_depth;
     const char *indent_str;
     if (emitter->output == emitter_output_json) {
         indent_str = "\t";
     } else {
         amount *= 2;
         indent_str = " ";
     }
     for (int i = 0; i < amount; i++) {
         emitter_printf(emitter, "%s", indent_str);
     }
 }
References emitter_output_json, emitter_printf(), emitter_s::nesting_depth, and emitter_s::output.
Referenced by emitter_json_array_end(), emitter_json_key_prefix(), emitter_json_object_end(), emitter_table_dict_begin(), and emitter_table_kv_note().
emitter_init()
static void emitter_init (emitter_t * emitter, emitter_output_t emitter_output, void(*)(void *, const char *) write_cb, void * cbopaque) inline static
Definition at line 224 of file emitter.h.
{
     emitter->output = emitter_output;
     emitter->write_cb = write_cb;
     emitter->cbopaque = cbopaque;
     emitter->item_at_depth = false;
     emitter->emitted_key = false;
     emitter->nesting_depth = 0;
 }
References emitter_s::cbopaque, emitter_s::emitted_key, emitter_s::item_at_depth, emitter_s::nesting_depth, emitter_s::output, and emitter_s::write_cb.
Referenced by prof_log_stop(), and stats_print().
emitter_json_array_begin()
static void emitter_json_array_begin (emitter_t * emitter) inline static
Definition at line 270 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key_prefix(emitter);
         emitter_printf(emitter, "[");
         emitter_nest_inc(emitter);
     }
 }
References emitter_json_key_prefix(), emitter_nest_inc(), emitter_output_json, emitter_printf(), and emitter_s::output.
Referenced by emitter_json_array_kv_begin(), and prof_log_emit_traces().
emitter_json_array_end()
static void emitter_json_array_end (emitter_t * emitter) inline static
Definition at line 286 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         assert(emitter->nesting_depth > 0);
         emitter_nest_dec(emitter);
         emitter_printf(emitter, "\n");
         emitter_indent(emitter);
         emitter_printf(emitter, "]");
     }
 }
References assert(), emitter_indent(), emitter_nest_dec(), emitter_output_json, emitter_printf(), emitter_s::nesting_depth, and emitter_s::output.
Referenced by prof_log_emit_allocs(), prof_log_emit_threads(), prof_log_emit_traces(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), and stats_general_print().
emitter_json_array_kv_begin()
static void emitter_json_array_kv_begin (emitter_t * emitter, const char * json_key) inline static
Definition at line 280 of file emitter.h.
{
     emitter_json_key(emitter, json_key);
     emitter_json_array_begin(emitter);
 }
References emitter_json_array_begin(), and emitter_json_key().
Referenced by prof_log_emit_allocs(), prof_log_emit_threads(), prof_log_emit_traces(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), and stats_general_print().
emitter_json_key()
static void emitter_json_key (emitter_t * emitter, const char * json_key) inline static
Definition at line 242 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key_prefix(emitter);
         emitter_printf(emitter, "\"%s\": ", json_key);
         emitter->emitted_key = true;
     }
 }
References emitter_s::emitted_key, emitter_json_key_prefix(), emitter_output_json, emitter_printf(), and emitter_s::output.
Referenced by emitter_dict_begin(), emitter_json_array_kv_begin(), emitter_json_kv(), emitter_json_object_kv_begin(), and emitter_kv_note().
emitter_json_key_prefix()
static void emitter_json_key_prefix (emitter_t * emitter) inline static
Definition at line 211 of file emitter.h.
{
     if (emitter->emitted_key) {
         emitter->emitted_key = false;
         return;
     }
     emitter_printf(emitter, "%s\n", emitter->item_at_depth ? "," : "");
     emitter_indent(emitter);
 }
References emitter_s::emitted_key, emitter_indent(), emitter_printf(), and emitter_s::item_at_depth.
Referenced by emitter_json_array_begin(), emitter_json_key(), emitter_json_object_begin(), and emitter_json_value().
emitter_json_kv()
static void emitter_json_kv (emitter_t * emitter, const char * json_key, emitter_type_t value_type, const void * value) inline static
Definition at line 263 of file emitter.h.
{
     emitter_json_key(emitter, json_key);
     emitter_json_value(emitter, value_type, value);
 }
References emitter_json_key(), and emitter_json_value().
Referenced by prof_log_emit_allocs(), prof_log_emit_metadata(), prof_log_emit_threads(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), stats_arena_print(), stats_general_print(), and stats_print_helper().
emitter_json_object_begin()
static void emitter_json_object_begin (emitter_t * emitter) inline static
Definition at line 297 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key_prefix(emitter);
         emitter_printf(emitter, "{");
         emitter_nest_inc(emitter);
     }
 }
References emitter_json_key_prefix(), emitter_nest_inc(), emitter_output_json, emitter_printf(), and emitter_s::output.
Referenced by emitter_dict_begin(), emitter_json_object_kv_begin(), prof_log_emit_allocs(), prof_log_emit_threads(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), and stats_general_print().
emitter_json_object_end()
static void emitter_json_object_end (emitter_t * emitter) inline static
Definition at line 313 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         assert(emitter->nesting_depth > 0);
         emitter_nest_dec(emitter);
         emitter_printf(emitter, "\n");
         emitter_indent(emitter);
         emitter_printf(emitter, "}");
     }
 }
References assert(), emitter_indent(), emitter_nest_dec(), emitter_output_json, emitter_printf(), emitter_s::nesting_depth, and emitter_s::output.
Referenced by emitter_dict_end(), prof_log_emit_allocs(), prof_log_emit_metadata(), prof_log_emit_threads(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), stats_arena_mutexes_print(), stats_arena_print(), stats_general_print(), stats_print(), and stats_print_helper().
emitter_json_object_kv_begin()
static void emitter_json_object_kv_begin (emitter_t * emitter, const char * json_key) inline static
Definition at line 307 of file emitter.h.
{
     emitter_json_key(emitter, json_key);
     emitter_json_object_begin(emitter);
 }
References emitter_json_key(), and emitter_json_object_begin().
Referenced by prof_log_emit_metadata(), stats_arena_bins_print(), stats_arena_mutexes_print(), stats_arena_print(), stats_general_print(), stats_print(), and stats_print_helper().
emitter_json_value()
static void emitter_json_value (emitter_t * emitter, emitter_type_t value_type, const void * value) inline static
Definition at line 251 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key_prefix(emitter);
         emitter_print_value(emitter, emitter_justify_none, -1,
             value_type, value);
         emitter->item_at_depth = true;
     }
 }
References emitter_json_key_prefix(), emitter_justify_none, emitter_output_json, emitter_print_value(), emitter_s::item_at_depth, and emitter_s::output.
Referenced by emitter_json_kv(), emitter_kv_note(), and prof_log_emit_traces().
emitter_kv()
static void emitter_kv (emitter_t * emitter, const char * json_key, const char * table_key, emitter_type_t value_type, const void * value) inline static
Definition at line 434 of file emitter.h.
{
     emitter_kv_note(emitter, json_key, table_key, value_type, value, NULL,
         emitter_type_bool, NULL);
 }
References emitter_kv_note(), emitter_type_bool, and NULL.
Referenced by stats_arena_print(), and stats_general_print().
emitter_kv_note()
static void emitter_kv_note (emitter_t * emitter, const char * json_key, const char * table_key, emitter_type_t value_type, const void * value, const char * table_note_key, emitter_type_t table_note_value_type, const void * table_note_value) inline static
Definition at line 419 of file emitter.h.
{
     if (emitter->output == emitter_output_json) {
         emitter_json_key(emitter, json_key);
         emitter_json_value(emitter, value_type, value);
     } else {
         emitter_table_kv_note(emitter, table_key, value_type, value,
             table_note_key, table_note_value_type, table_note_value);
     }
     emitter->item_at_depth = true;
 }
References emitter_json_key(), emitter_json_value(), emitter_output_json, emitter_table_kv_note(), emitter_s::item_at_depth, and emitter_s::output.
Referenced by emitter_kv().
emitter_nest_dec()
static void emitter_nest_dec (emitter_t * emitter) inline static
Definition at line 190 of file emitter.h.
{
     emitter->nesting_depth--;
     emitter->item_at_depth = true;
 }
References emitter_s::item_at_depth, and emitter_s::nesting_depth.
Referenced by emitter_end(), emitter_json_array_end(), emitter_json_object_end(), and emitter_table_dict_end().
emitter_nest_inc()
static void emitter_nest_inc (emitter_t * emitter) inline static
Definition at line 184 of file emitter.h.
{
     emitter->nesting_depth++;
     emitter->item_at_depth = false;
 }
References emitter_s::item_at_depth, and emitter_s::nesting_depth.
Referenced by emitter_begin(), emitter_json_array_begin(), emitter_json_object_begin(), and emitter_table_dict_begin().
emitter_print_value()
static void emitter_print_value (emitter_t * emitter, emitter_justify_t justify, int width, emitter_type_t value_type, const void * value) inline static
Definition at line 117 of file emitter.h.
{
     size_t str_written;
 #define BUF_SIZE 256
 #define FMT_SIZE 10
     /*
      * We dynamically generate a format string to emit, to let us use the
      * snprintf machinery.  This is kinda hacky, but gets the job done
      * quickly without having to think about the various snprintf edge
      * cases.
      */
     char fmt[FMT_SIZE];
     char buf[BUF_SIZE];
 #define EMIT_SIMPLE(type, format)                   \
     emitter_printf(emitter,                     \
         emitter_gen_fmt(fmt, FMT_SIZE, format, justify, width), \
         *(const type *)value);
     switch (value_type) {
     case emitter_type_bool:
         emitter_printf(emitter,
             emitter_gen_fmt(fmt, FMT_SIZE, "%s", justify, width),
             *(const bool *)value ?  "true" : "false");
         break;
     case emitter_type_int:
         EMIT_SIMPLE(int, "%d")
         break;
     case emitter_type_unsigned:
         EMIT_SIMPLE(unsigned, "%u")
         break;
     case emitter_type_ssize:
         EMIT_SIMPLE(ssize_t, "%zd")
         break;
     case emitter_type_size:
         EMIT_SIMPLE(size_t, "%zu")
         break;
     case emitter_type_string:
         str_written = malloc_snprintf(buf, BUF_SIZE, "\"%s\"",
             *(const char *const *)value);
         /*
          * We control the strings we output; we shouldn't get anything
          * anywhere near the fmt size.
          */
         assert(str_written < BUF_SIZE);
         emitter_printf(emitter,
             emitter_gen_fmt(fmt, FMT_SIZE, "%s", justify, width), buf);
         break;
     case emitter_type_uint32:
         EMIT_SIMPLE(uint32_t, "%" FMTu32)
         break;
     case emitter_type_uint64:
         EMIT_SIMPLE(uint64_t, "%" FMTu64)
         break;
     case emitter_type_title:
         EMIT_SIMPLE(char *const, "%s");
         break;
     default:
         unreachable();
     }
 #undef BUF_SIZE
 #undef FMT_SIZE
 }
References assert(), BUF_SIZE, EMIT_SIMPLE, emitter_printf(), emitter_type_bool, emitter_type_int, emitter_type_size, emitter_type_ssize, emitter_type_string, emitter_type_title, emitter_type_uint32, emitter_type_uint64, emitter_type_unsigned, fmt, FMT_SIZE, FMTu32, FMTu64, justify, malloc_snprintf, unreachable, and width.
Referenced by emitter_json_value(), emitter_table_kv_note(), and emitter_table_row().
emitter_printf()
static void emitter_printf (emitter_t * emitter, const char * format, ...) inline static
Definition at line 81 of file emitter.h.
{
     va_list ap;
     va_start(ap, format);
     malloc_vcprintf(emitter->write_cb, emitter->cbopaque, format, ap);
     va_end(ap);
 }
References format(), and malloc_vcprintf.
Referenced by emitter_begin(), emitter_end(), emitter_indent(), emitter_json_array_begin(), emitter_json_array_end(), emitter_json_key(), emitter_json_key_prefix(), emitter_json_object_begin(), emitter_json_object_end(), emitter_print_value(), emitter_table_dict_begin(), and emitter_table_kv_note().
emitter_row_init()
static void emitter_row_init (emitter_row_t * row) inline static
Definition at line 398 of file emitter.h.
{
     ql_new(&row->cols);
 }
References ql_new.
Referenced by stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), stats_arena_mutexes_print(), stats_arena_print(), and stats_print_helper().
emitter_table_dict_begin()
static void emitter_table_dict_begin (emitter_t * emitter, const char * table_key) inline static
Definition at line 328 of file emitter.h.
{
     if (emitter->output == emitter_output_table) {
         emitter_indent(emitter);
         emitter_printf(emitter, "%s\n", table_key);
         emitter_nest_inc(emitter);
     }
 }
References emitter_indent(), emitter_nest_inc(), emitter_output_table, emitter_printf(), and emitter_s::output.
Referenced by emitter_dict_begin().
emitter_table_dict_end()
static void emitter_table_dict_end (emitter_t * emitter) inline static
Definition at line 337 of file emitter.h.
{
     if (emitter->output == emitter_output_table) {
         emitter_nest_dec(emitter);
     }
 }
References emitter_nest_dec(), emitter_output_table, and emitter_s::output.
Referenced by emitter_dict_end().
emitter_table_kv()
static void emitter_table_kv (emitter_t * emitter, const char * table_key, emitter_type_t value_type, const void * value) inline static
Definition at line 365 of file emitter.h.
{
     emitter_table_kv_note(emitter, table_key, value_type, value, NULL,
         emitter_type_bool, NULL);
 }
References emitter_table_kv_note(), emitter_type_bool, and NULL.
emitter_table_kv_note()
static void emitter_table_kv_note (emitter_t * emitter, const char * table_key, emitter_type_t value_type, const void * value, const char * table_note_key, emitter_type_t table_note_value_type, const void * table_note_value) inline static
Definition at line 344 of file emitter.h.
{
     if (emitter->output == emitter_output_table) {
         emitter_indent(emitter);
         emitter_printf(emitter, "%s: ", table_key);
         emitter_print_value(emitter, emitter_justify_none, -1,
             value_type, value);
         if (table_note_key != NULL) {
             emitter_printf(emitter, " (%s: ", table_note_key);
             emitter_print_value(emitter, emitter_justify_none, -1,
                 table_note_value_type, table_note_value);
             emitter_printf(emitter, ")");
         }
         emitter_printf(emitter, "\n");
     }
     emitter->item_at_depth = true;
 }
References emitter_indent(), emitter_justify_none, emitter_output_table, emitter_print_value(), emitter_printf(), emitter_s::item_at_depth, NULL, and emitter_s::output.
Referenced by emitter_kv_note(), and emitter_table_kv().
emitter_table_printf()
static void emitter_table_printf (emitter_t * emitter, const char * format, ...) inline static
Definition at line 375 of file emitter.h.
{
     if (emitter->output == emitter_output_table) {
         va_list ap;
         va_start(ap, format);
         malloc_vcprintf(emitter->write_cb, emitter->cbopaque, format, ap);
         va_end(ap);
     }
 }
References emitter_output_table, format(), and malloc_vcprintf.
Referenced by emitter_table_row(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), stats_print(), and stats_print_helper().
emitter_table_row()
static void emitter_table_row (emitter_t * emitter, emitter_row_t * row) inline static
Definition at line 385 of file emitter.h.
{
     if (emitter->output != emitter_output_table) {
         return;
     }
     emitter_col_t *col;
     ql_foreach(col, &row->cols, link) {
         emitter_print_value(emitter, col->justify, col->width,
             col->type, (const void *)&col->bool_val);
     }
     emitter_table_printf(emitter, "\n");
 }
References emitter_col_s::bool_val, emitter_output_table, emitter_print_value(), emitter_table_printf(), emitter_col_s::justify, emitter_s::output, ql_foreach, emitter_col_s::type, and emitter_col_s::width.
Referenced by mutex_stats_emit(), stats_arena_bins_print(), stats_arena_extents_print(), stats_arena_lextents_print(), stats_arena_mutexes_print(), stats_arena_print(), and stats_print_helper().
if()
else if (justify = = emitter_justify_none)
Definition at line 94 of file emitter.h.
{
         written = malloc_snprintf(out_fmt, out_size,
             "%%%s", fmt_specifier);
     } else if (justify == emitter_justify_left) {
References fmt_specifier, malloc_snprintf, out_fmt, and out_size.
JEMALLOC_FORMAT_ARG()
static const char* JEMALLOC_FORMAT_ARG (3) inline static
Variable Documentation
else
else
Initial value:
{
        written = malloc_snprintf(out_fmt, out_size,
            "%%%d%s", width, fmt_specifier)
Definition at line 100 of file emitter.h.
fmt_specifier
fmt_specifier
Definition at line 90 of file emitter.h.
Referenced by if().
justify
const char size_t const char emitter_justify_t justify
Definition at line 91 of file emitter.h.
Referenced by emitter_print_value().
out_fmt
return out_fmt
Definition at line 106 of file emitter.h.
Referenced by if().
out_size
const char size_t out_size
Definition at line 90 of file emitter.h.
Referenced by mpq::extern(), if(), libmpq__block_read(), libmpq__decompress_block(), libmpq__decompress_bzip2(), libmpq__decompress_huffman(), libmpq__decompress_multi(), libmpq__decompress_pkzip(), libmpq__decompress_wave_mono(), libmpq__decompress_wave_stereo(), libmpq__decompress_zlib(), and libmpq__file_read().
width
const char size_t const char emitter_justify_t int width
Initial value:
{
    size_t written
Definition at line 91 of file emitter.h.
Referenced by TileBuilder::BuildTiled(), emitter_print_value(), get_width(), WorldObject::GetMinHeightInWater(), getOutOfWater(), getWeight(), Position::HasInLine(), malloc_vsnprintf(), my_gcvt(), my_vsnprintf_ex(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_width(), specs_setter< Char >::on_width(), printf_width_handler< Char >::operator()(), parse_width(), process_args(), process_bin_arg(), process_dbl_arg(), process_str_arg(), rcCreateHeightfield(), G3D::AnyVal::serialize(), VMAP::WmoLiquid::WmoLiquid(), write(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::write(), write_int_data< Char >::write_int_data(), and write_padded().