Azerotcore-wotlk: KEYINSTANCE Struct Reference
KEYINSTANCE Struct Reference
Public Attributes
int nr
uint32 rk [4 *(AES_MAXNR+1)]
Detailed Description
Definition at line 35 of file my_aes.c.
Member Data Documentation
nr
int KEYINSTANCE::nr
Definition at line 36 of file my_aes.c.
Referenced by my_aes_create_key(), my_aes_decrypt(), and my_aes_encrypt().
rk
uint32 KEYINSTANCE::rk[4 *(AES_MAXNR+1)]
Definition at line 37 of file my_aes.c.
Referenced by my_aes_create_key(), my_aes_decrypt(), and my_aes_encrypt().
The documentation for this struct was generated from the following file:
deps/mysqllite/mysys/my_aes.c