Azerotcore-wotlk: npc_escortAI Struct Reference
npc_escortAI Struct Reference abstract
#include <ScriptedEscortAI.h>
Public Member Functions
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Member Functions
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Private Member Functions
bool AssistPlayerInCombat (Unit *who)
bool IsPlayerOrGroupInRange ()
void FillPointMovementListForCreature ()
Private Attributes
ObjectGuid m_uiPlayerGUID
uint32 m_uiWPWaitTimer
uint32 m_uiPlayerCheckTimer
uint32 m_uiEscortState
float MaxPlayerDistance
Quest const * m_pQuestForEscort
std::list< Escort_Waypoint > WaypointList
std::list< Escort_Waypoint >::iterator CurrentWP
bool m_bIsActiveAttacker
bool m_bIsRunning
bool m_bCanInstantRespawn
bool m_bCanReturnToStart
bool DespawnAtEnd
bool DespawnAtFar
bool ScriptWP
bool HasImmuneToNPCFlags
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 52 of file ScriptedEscortAI.h.
Constructor & Destructor Documentation
npc_escortAI()
npc_escortAI::npc_escortAI (Creature * creature) explicit
Definition at line 36 of file ScriptedEscortAI.cpp.
                                              : ScriptedAI(creature),
     m_uiWPWaitTimer(1000),
     m_uiPlayerCheckTimer(0),
     m_uiEscortState(STATE_ESCORT_NONE),
     MaxPlayerDistance(DEFAULT_MAX_PLAYER_DISTANCE),
     m_pQuestForEscort(nullptr),
     m_bIsActiveAttacker(true),
     m_bIsRunning(false),
     m_bCanInstantRespawn(false),
     m_bCanReturnToStart(false),
     DespawnAtEnd(true),
     DespawnAtFar(true),
     ScriptWP(false),
     HasImmuneToNPCFlags(false)
 {}
~npc_escortAI()
npc_escortAI::~npc_escortAI () inline override
Definition at line 56 of file ScriptedEscortAI.h.
 {}
Member Function Documentation
AddEscortState()
void npc_escortAI::AddEscortState (uint32 escortState) inline
Definition at line 110 of file ScriptedEscortAI.h.
 { m_uiEscortState |= escortState; }
References m_uiEscortState.
Referenced by EnterEvadeMode(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode(), npc_varian_wrynn::npc_varian_wrynnAI::EnterEvadeMode(), npc_thrall_bfu::npc_thrall_bfuAI::EnterEvadeMode(), violet_hold_trashAI::EnterEvadeMode(), SetEscortPaused(), and Start().
AddWaypoint()
void npc_escortAI::AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime = 0)
Definition at line 397 of file ScriptedEscortAI.cpp.
 {
     Escort_Waypoint t(id, x, y, z, waitTime);
     WaypointList.push_back(t);
     // i think SD2 no longer uses this function
     ScriptWP = true;
     /*PointMovement wp;
     wp.m_uiCreatureEntry = me->GetEntry();
     wp.m_uiPointId = id;
     wp.m_fX = x;
     wp.m_fY = y;
     wp.m_fZ = z;
     wp.m_uiWaitTime = WaitTimeMs;
     PointMovementMap[wp.m_uiCreatureEntry].push_back(wp);*/
 }
References ScriptWP, WaypointList, G3D::x, G3D::y, and G3D::z.
Referenced by npc_onyx_flamecaller::npc_onyx_flamecallerAI::AddWaypoints(), boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI(), npc_scarlet_miner::npc_scarlet_minerAI::InitWaypoint(), boss_thorim_lightning_orb::boss_thorim_lightning_orbAI::InitWaypoint(), boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI::InitWaypoint(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), hyjalAI::Retreat(), boss_grand_champion::boss_grand_championAI::SetData(), npc_argent_soldier::npc_argent_soldierAI::SetData(), npc_clintar_spirit::npc_clintar_spiritAI::StartEvent(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), hyjal_trashAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), and npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI().
AssistPlayerInCombat()
bool npc_escortAI::AssistPlayerInCombat (Unit * who) private
Definition at line 73 of file ScriptedEscortAI.cpp.
 {
     if (!who || !who->GetVictim())
     {
         return false;
     }
     if (me->HasReactState(REACT_PASSIVE))
     {
         return false;
     }
     //experimental (unknown) flag not present
     if (!(me->GetCreatureTemplate()->type_flags & CREATURE_TYPE_FLAG_CAN_ASSIST))
     {
         return false;
     }
     //not a player
     if (!who->GetVictim()->GetCharmerOrOwnerPlayerOrPlayerItself())
     {
         return false;
     }
     if (!who->isInAccessiblePlaceFor(me))
     {
         return false;
     }
     if (!CanAIAttack(who))
     {
         return false;
     }
     // we cannot attack in evade mode
     if (me->IsInEvadeMode())
     {
         return false;
     }
     // or if enemy is in evade mode
     if (who->GetTypeId() == TYPEID_UNIT && who->ToCreature()->IsInEvadeMode())
     {
         return false;
     }
     //never attack friendly
     if (!me->IsValidAttackTarget(who))
     {
         return false;
     }
     //too far away and no free sight?
     if (me->IsWithinDistInMap(who, GetMaxPlayerDistance()) && me->IsWithinLOSInMap(who))
     {
         AttackStart(who);
         return true;
     }
     return false;
 }
References AttackStart(), UnitAI::CanAIAttack(), CREATURE_TYPE_FLAG_CAN_ASSIST, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Creature::GetCreatureTemplate(), GetMaxPlayerDistance(), Object::GetTypeId(), Unit::GetVictim(), Creature::HasReactState(), Unit::isInAccessiblePlaceFor(), Creature::IsInEvadeMode(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), ScriptedAI::me, REACT_PASSIVE, Object::ToCreature(), CreatureTemplate::type_flags, and TYPEID_UNIT.
Referenced by MoveInLineOfSight().
AttackStart()
void npc_escortAI::AttackStart (Unit * who) override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_ambassador_hellmaw::boss_ambassador_hellmawAI, violet_hold_trashAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, npc_mimirons_inferno::npc_mimirons_infernoAI, and npc_taretha::npc_tarethaAI.
Definition at line 52 of file ScriptedEscortAI.cpp.
 {
     if (!who)
         return;
     if (me->Attack(who, true))
     {
         MovementGeneratorType type = me->GetMotionMaster()->GetMotionSlotType(MOTION_SLOT_ACTIVE);
         if (type == ESCORT_MOTION_TYPE || type == POINT_MOTION_TYPE)
         {
             me->GetMotionMaster()->MovementExpired();
             //me->DisableSpline();
             me->StopMoving();
         }
         if (IsCombatMovementAllowed())
             me->GetMotionMaster()->MoveChase(who);
     }
 }
References Unit::Attack(), ESCORT_MOTION_TYPE, Unit::GetMotionMaster(), MotionMaster::GetMotionSlotType(), ScriptedAI::IsCombatMovementAllowed(), ScriptedAI::me, MOTION_SLOT_ACTIVE, MotionMaster::MoveChase(), MotionMaster::MovementExpired(), POINT_MOTION_TYPE, and Unit::StopMoving().
Referenced by AssistPlayerInCombat(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::AttackedBy(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::AttackStart(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::AttackStart(), npc_clintar_spirit::npc_clintar_spiritAI::EnterEvadeMode(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), MoveInLineOfSight(), npc_lesser_doomguard::npc_lesser_doomguardAI::MoveInLineOfSight(), npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_arthas::npc_arthasAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
EnterEvadeMode()
void npc_escortAI::EnterEvadeMode () override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_captain_saeed::npc_captain_saeedAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, violet_hold_trashAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_grand_champion::boss_grand_championAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_cork_gizelton::npc_cork_gizeltonAI, hyjalAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, and npc_koltira_deathweaver::npc_koltira_deathweaverAI.
Definition at line 201 of file ScriptedEscortAI.cpp.
 {
     me->RemoveAllAuras();
     me->DeleteThreatList();
     me->CombatStop(true);
     me->SetLootRecipient(nullptr);
     if (HasEscortState(STATE_ESCORT_ESCORTING))
     {
         AddEscortState(STATE_ESCORT_RETURNING);
         ReturnToLastPoint();
         LOG_DEBUG("scripts.ai", "EscortAI has left combat and is now returning to last point");
     }
     else
     {
         me->GetMotionMaster()->MoveTargetedHome();
         if (HasImmuneToNPCFlags)
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         Reset();
     }
 }
References AddEscortState(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), HasEscortState(), HasImmuneToNPCFlags, LOG_DEBUG, ScriptedAI::me, MotionMaster::MoveTargetedHome(), Unit::RemoveAllAuras(), ScriptedAI::Reset(), ReturnToLastPoint(), Object::SetFlag(), Creature::SetLootRecipient(), STATE_ESCORT_ESCORTING, STATE_ESCORT_RETURNING, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by npc_arthas::npc_arthasAI::DoAction(), npc_cork_gizelton::npc_cork_gizeltonAI::EnterEvadeMode(), npc_clintar_spirit::npc_clintar_spiritAI::EnterEvadeMode(), npc_captain_saeed::npc_captain_saeedAI::EnterEvadeMode(), npc_barnes::npc_barnesAI::UpdateAI(), and boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI().
FillPointMovementListForCreature()
void npc_escortAI::FillPointMovementListForCreature () private
Definition at line 415 of file ScriptedEscortAI.cpp.
 {
     ScriptPointVector const& movePoints = sScriptSystemMgr->GetPointMoveList(me->GetEntry());
     if (movePoints.empty())
         return;
     ScriptPointVector::const_iterator itrEnd = movePoints.end();
     for (ScriptPointVector::const_iterator itr = movePoints.begin(); itr != itrEnd; ++itr)
     {
         Escort_Waypoint point(itr->uiPointId, itr->fX, itr->fY, itr->fZ, itr->uiWaitTime);
         WaypointList.push_back(point);
     }
 }
References Object::GetEntry(), ScriptedAI::me, sScriptSystemMgr, and WaypointList.
Referenced by SetNextWaypoint(), and Start().
GenerateWaypointArray()
void npc_escortAI::GenerateWaypointArray (Movement::PointsArray * points)
Definition at line 585 of file ScriptedEscortAI.cpp.
 {
     if (WaypointList.empty())
         return;
     uint32 startingWaypointId = CurrentWP->id;
     // Flying unit, just fill array
     if (me->m_movementInfo.HasMovementFlag((MovementFlags)(MOVEMENTFLAG_CAN_FLY | MOVEMENTFLAG_DISABLE_GRAVITY)))
     {
         // xinef: first point in vector is unit real position
         points->clear();
         points->push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
         for (std::list<Escort_Waypoint>::const_iterator itr = CurrentWP; itr != WaypointList.end(); ++itr)
             points->push_back(G3D::Vector3(itr->x, itr->y, itr->z));
     }
     else
     {
         for (float size = 1.0f; size; size *= 0.5f)
         {
             std::vector<G3D::Vector3> pVector;
             // xinef: first point in vector is unit real position
             pVector.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
             uint32 length = (WaypointList.size() - startingWaypointId) * size;
             uint32 cnt = 0;
             for (std::list<Escort_Waypoint>::const_iterator itr = CurrentWP; itr != WaypointList.end() && cnt <= length; ++itr, ++cnt)
                 pVector.push_back(G3D::Vector3(itr->x, itr->y, itr->z));
             if (pVector.size() > 2) // more than source + dest
             {
                 G3D::Vector3 middle = (pVector[0] + pVector[pVector.size() - 1]) / 2.f;
                 G3D::Vector3 offset;
                 bool continueLoop = false;
                 for (uint32 i = 1; i < pVector.size() - 1; ++i)
                 {
                     offset = middle - pVector[i];
                     if (fabs(offset.x) >= 0xFF || fabs(offset.y) >= 0xFF || fabs(offset.z) >= 0x7F)
                     {
                         // offset is too big, split points
                         continueLoop = true;
                         break;
                     }
                 }
                 if (continueLoop)
                     continue;
             }
             // everything ok
             *points = pVector;
             break;
         }
     }
 }
References CurrentWP, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MovementInfo::HasMovementFlag(), G3D::length(), WorldObject::m_movementInfo, ScriptedAI::me, MOVEMENTFLAG_CAN_FLY, MOVEMENTFLAG_DISABLE_GRAVITY, WaypointList, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by UpdateAI().
GetAttack()
bool npc_escortAI::GetAttack () inline
Definition at line 106 of file ScriptedEscortAI.h.
 { return m_bIsActiveAttacker; }//used in EnterEvadeMode override
References m_bIsActiveAttacker.
Referenced by npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), and npc_bonker_togglevolt::npc_bonker_togglevoltAI::UpdateEscortAI().
GetEventStarterGUID()
ObjectGuid npc_escortAI::GetEventStarterGUID () inline
Definition at line 108 of file ScriptedEscortAI.h.
 { return m_uiPlayerGUID; }
References m_uiPlayerGUID.
GetMaxPlayerDistance()
float npc_escortAI::GetMaxPlayerDistance () inline
Definition at line 102 of file ScriptedEscortAI.h.
 { return MaxPlayerDistance; }
References MaxPlayerDistance.
Referenced by AssistPlayerInCombat(), and IsPlayerOrGroupInRange().
GetPlayerForEscort()
Player* npc_escortAI::GetPlayerForEscort () inline protected
Definition at line 114 of file ScriptedEscortAI.h.
 { return ObjectAccessor::GetPlayer(*me, m_uiPlayerGUID); }
References ObjectAccessor::GetPlayer(), m_uiPlayerGUID, and ScriptedAI::me.
Referenced by npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::DamageTaken(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::EnterCombat(), npc_muglash::npc_muglashAI::EnterCombat(), IsPlayerOrGroupInRange(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), JustDied(), npc_muglash::npc_muglashAI::JustDied(), npc_ame::npc_ameAI::JustDied(), npc_mootoo_the_younger::npc_mootoo_the_youngerAI::JustDied(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::JustDied(), npc_apothecary_hanes::npc_Apothecary_HanesAI::JustDied(), npc_engineer_helice::npc_engineer_heliceAI::JustDied(), npc_maghar_captive::npc_maghar_captiveAI::JustDied(), npc_kurenai_captive::npc_kurenai_captiveAI::JustDied(), npc_captain_saeed::npc_captain_saeedAI::JustDied(), npc_bessy::npc_bessyAI::JustDied(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::JustDied(), npc_isla_starmane::npc_isla_starmaneAI::JustDied(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::JustSummoned(), npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight(), npc_daphne_stilwell::npc_daphne_stilwellAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), npc_captain_saeed::npc_captain_saeedAI::WaypointReached(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::WaypointReached(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), npc_rinji::npc_rinjiAI::WaypointReached(), npc_corporal_keeshan::npc_corporal_keeshanAI::WaypointReached(), npc_deathstalker_erland::npc_deathstalker_erlandAI::WaypointReached(), npc_varian_wrynn::npc_varian_wrynnAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_muglash::npc_muglashAI::WaypointReached(), npc_magwin::npc_magwinAI::WaypointReached(), npc_prospector_remtravel::npc_prospector_remtravelAI::WaypointReached(), npc_kaya_flathoof::npc_kaya_flathoofAI::WaypointReached(), npc_custodian_of_time::npc_custodian_of_timeAI::WaypointReached(), npc_gilthares::npc_giltharesAI::WaypointReached(), npc_lakota_windsong::npc_lakota_windsongAI::WaypointReached(), npc_paoka_swiftmountain::npc_paoka_swiftmountainAI::WaypointReached(), npc_ame::npc_ameAI::WaypointReached(), npc_mootoo_the_younger::npc_mootoo_the_youngerAI::WaypointReached(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached(), npc_engineer_helice::npc_engineer_heliceAI::WaypointReached(), npc_frosthound::npc_frosthoundAI::WaypointReached(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::WaypointReached(), npc_maghar_captive::npc_maghar_captiveAI::WaypointReached(), npc_kurenai_captive::npc_kurenai_captiveAI::WaypointReached(), npc_bessy::npc_bessyAI::WaypointReached(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::WaypointReached(), npc_earthmender_wilda::npc_earthmender_wildaAI::WaypointReached(), npc_kservant::npc_kservantAI::WaypointReached(), npc_isla_starmane::npc_isla_starmaneAI::WaypointReached(), npc_kayra_longmane::npc_kayra_longmaneAI::WaypointReached(), and npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointStart().
GetWaypointPosition()
bool npc_escortAI::GetWaypointPosition (uint32 pointId, float & x, float & y, float & z)
Definition at line 565 of file ScriptedEscortAI.cpp.
 {
     ScriptPointVector const& waypoints = sScriptSystemMgr->GetPointMoveList(me->GetEntry());
     if (waypoints.empty())
         return false;
     for (ScriptPointVector::const_iterator itr = waypoints.begin(); itr != waypoints.end(); ++itr)
     {
         if (itr->uiPointId == pointId)
         {
             x = itr->fX;
             y = itr->fY;
             z = itr->fZ;
             return true;
         }
     }
     return false;
 }
References Object::GetEntry(), ScriptedAI::me, sScriptSystemMgr, G3D::x, G3D::y, and G3D::z.
HasEscortState()
bool npc_escortAI::HasEscortState (uint32 escortState) inline
Definition at line 98 of file ScriptedEscortAI.h.
 { return (m_uiEscortState & escortState); }
References m_uiEscortState.
Referenced by npc_koltira_deathweaver::npc_koltira_deathweaverAI::AttackStart(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::EnterCombat(), npc_muglash::npc_muglashAI::EnterCombat(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::EnterCombat(), npc_rinji::npc_rinjiAI::EnterCombat(), EnterEvadeMode(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode(), npc_varian_wrynn::npc_varian_wrynnAI::EnterEvadeMode(), npc_thrall_bfu::npc_thrall_bfuAI::EnterEvadeMode(), violet_hold_trashAI::EnterEvadeMode(), JustDied(), npc_muglash::npc_muglashAI::JustDied(), npc_engineer_helice::npc_engineer_heliceAI::JustDied(), npc_maghar_captive::npc_maghar_captiveAI::JustDied(), npc_kurenai_captive::npc_kurenai_captiveAI::JustDied(), MoveInLineOfSight(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), MovementInform(), npc_rocknot::npc_rocknotAI::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::Reset(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::Reset(), npc_lurgglbr::npc_lurgglbrAI::Reset(), SetEscortPaused(), Start(), UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), npc_muglash::npc_muglashAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_engineer_helice::npc_engineer_heliceAI::UpdateAI(), and npc_rinji::npc_rinjiAI::UpdateEscortAI().
IsEscorted()
bool npc_escortAI::IsEscorted () inline override virtual
Reimplemented from CreatureAI.
Definition at line 99 of file ScriptedEscortAI.h.
 { return (m_uiEscortState & STATE_ESCORT_ESCORTING); }
References m_uiEscortState, and STATE_ESCORT_ESCORTING.
IsPlayerOrGroupInRange()
bool npc_escortAI::IsPlayerOrGroupInRange () private
Definition at line 223 of file ScriptedEscortAI.cpp.
 {
     if (Player* player = GetPlayerForEscort())
     {
         if (Group* group = player->GetGroup())
         {
             for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
                 if (Player* member = groupRef->GetSource())
                     if (me->IsWithinDistInMap(member, GetMaxPlayerDistance(), true, false))
                         return true;
         }
         else if (me->IsWithinDistInMap(player, GetMaxPlayerDistance(), true, false))
             return true;
     }
     return false;
 }
References GetMaxPlayerDistance(), GetPlayerForEscort(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, and GroupReference::next().
Referenced by UpdateAI().
JustDied()
void npc_escortAI::JustDied (Unit *) override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_cork_gizelton::npc_cork_gizeltonAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_gargoyle::npc_gargoyleAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, boss_azgalor::boss_azgalorAI, boss_anetheron::boss_anetheronAI, npc_isla_starmane::npc_isla_starmaneAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_bessy::npc_bessyAI, npc_captain_saeed::npc_captain_saeedAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_maghar_captive::npc_maghar_captiveAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_engineer_helice::npc_engineer_heliceAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_mootoo_the_younger::npc_mootoo_the_youngerAI, violet_hold_trashAI, brann_bronzebeard::brann_bronzebeardAI, boss_bjarngrim::boss_bjarngrimAI, npc_argent_soldier::npc_argent_soldierAI, npc_ame::npc_ameAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_muglash::npc_muglashAI, npc_arthas::npc_arthasAI, hyjalAI, hyjal_trashAI, npc_frost_wyrm::npc_frost_wyrmAI, and npc_lesser_doomguard::npc_lesser_doomguardAI.
Definition at line 155 of file ScriptedEscortAI.cpp.
 {
     if (!HasEscortState(STATE_ESCORT_ESCORTING) || !m_uiPlayerGUID || !m_pQuestForEscort)
         return;
     if (Player* player = GetPlayerForEscort())
     {
         if (Group* group = player->GetGroup())
         {
             for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
                 if (Player* member = groupRef->GetSource())
                     if (member->IsInMap(player) && member->GetQuestStatus(m_pQuestForEscort->GetQuestId()) == QUEST_STATUS_INCOMPLETE)
                         member->FailQuest(m_pQuestForEscort->GetQuestId());
         }
         else
         {
             if (player->GetQuestStatus(m_pQuestForEscort->GetQuestId()) == QUEST_STATUS_INCOMPLETE)
                 player->FailQuest(m_pQuestForEscort->GetQuestId());
         }
     }
 }
References GetPlayerForEscort(), Quest::GetQuestId(), HasEscortState(), m_pQuestForEscort, m_uiPlayerGUID, GroupReference::next(), QUEST_STATUS_INCOMPLETE, and STATE_ESCORT_ESCORTING.
Referenced by npc_cork_gizelton::npc_cork_gizeltonAI::JustDied().
JustRespawned()
void npc_escortAI::JustRespawned () override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_cork_gizelton::npc_cork_gizeltonAI, and npc_rinji::npc_rinjiAI.
Definition at line 177 of file ScriptedEscortAI.cpp.
 {
     RemoveEscortState(STATE_ESCORT_ESCORTING | STATE_ESCORT_RETURNING | STATE_ESCORT_PAUSED);
     if (!IsCombatMovementAllowed())
         SetCombatMovement(true);
     //add a small delay before going to first waypoint, normal in near all cases
     m_uiWPWaitTimer = 1000;
     if (me->GetFaction() != me->GetCreatureTemplate()->faction)
         me->RestoreFaction();
     Reset();
 }
References CreatureTemplate::faction, Creature::GetCreatureTemplate(), Unit::GetFaction(), ScriptedAI::IsCombatMovementAllowed(), m_uiWPWaitTimer, ScriptedAI::me, RemoveEscortState(), ScriptedAI::Reset(), Unit::RestoreFaction(), ScriptedAI::SetCombatMovement(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, and STATE_ESCORT_RETURNING.
Referenced by npc_rinji::npc_rinjiAI::JustRespawned(), and npc_cork_gizelton::npc_cork_gizeltonAI::JustRespawned().
MoveInLineOfSight()
void npc_escortAI::MoveInLineOfSight (Unit * who) override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_captain_saeed::npc_captain_saeedAI, npc_ancestral_wolf::npc_ancestral_wolfAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, violet_hold_trashAI, npc_custodian_of_time::npc_custodian_of_timeAI, hyjalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, npc_akama_illidan::npc_akama_illidanAI, npc_azure_saboteur::npc_azure_saboteurAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, npc_mimirons_inferno::npc_mimirons_infernoAI, brann_bronzebeard::brann_bronzebeardAI, and npc_taretha::npc_tarethaAI.
Definition at line 135 of file ScriptedEscortAI.cpp.
 {
     if (me->GetVictim())
         return;
     if (!me->HasUnitState(UNIT_STATE_STUNNED) && who->isTargetableForAttack(true, me) && who->isInAccessiblePlaceFor(me))
         if (HasEscortState(STATE_ESCORT_ESCORTING) && AssistPlayerInCombat(who))
             return;
     if (me->CanStartAttack(who))
     {
         if (me->HasUnitState(UNIT_STATE_DISTRACTED))
         {
             me->ClearUnitState(UNIT_STATE_DISTRACTED);
             me->GetMotionMaster()->Clear();
         }
         AttackStart(who);
     }
 }
References AssistPlayerInCombat(), AttackStart(), Creature::CanStartAttack(), MotionMaster::Clear(), Unit::ClearUnitState(), Unit::GetMotionMaster(), Unit::GetVictim(), HasEscortState(), Unit::HasUnitState(), Unit::isInAccessiblePlaceFor(), Unit::isTargetableForAttack(), ScriptedAI::me, STATE_ESCORT_ESCORTING, UNIT_STATE_DISTRACTED, and UNIT_STATE_STUNNED.
Referenced by hyjalAI::MoveInLineOfSight(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::MoveInLineOfSight(), and npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight().
MovementInform()
void npc_escortAI::MovementInform (uint32 moveType, uint32 pointId) override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, and boss_grand_champion::boss_grand_championAI.
Definition at line 327 of file ScriptedEscortAI.cpp.
 {
     // xinef: no action allowed if there is no escort
     if (!HasEscortState(STATE_ESCORT_ESCORTING))
         return;
     if (moveType == POINT_MOTION_TYPE)
     {
         //Combat start position reached, continue waypoint movement
         if (pointId == POINT_LAST_POINT)
         {
             LOG_DEBUG("scripts.ai", "EscortAI has returned to original position before combat");
             me->SetWalk(!m_bIsRunning);
             RemoveEscortState(STATE_ESCORT_RETURNING);
             if (!m_uiWPWaitTimer)
                 m_uiWPWaitTimer = 1;
         }
         else if (pointId == POINT_HOME)
         {
             LOG_DEBUG("scripts.ai", "EscortAI has returned to original home location and will continue from beginning of waypoint list.");
             CurrentWP = WaypointList.begin();
             m_uiWPWaitTimer = 1;
         }
     }
     else if (moveType == ESCORT_MOTION_TYPE)
     {
         if (m_uiWPWaitTimer <= 1 && !HasEscortState(STATE_ESCORT_PAUSED) && CurrentWP != WaypointList.end())
         {
             //Call WP function
             me->SetPosition(CurrentWP->x, CurrentWP->y, CurrentWP->z, me->GetOrientation());
             me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
             WaypointReached(CurrentWP->id);
             m_uiWPWaitTimer = CurrentWP->WaitTimeMs + 1;
             ++CurrentWP;
             if (m_uiWPWaitTimer > 1 || HasEscortState(STATE_ESCORT_PAUSED))
             {
                 if (me->GetMotionMaster()->GetMotionSlotType(MOTION_SLOT_ACTIVE) == ESCORT_MOTION_TYPE)
                     me->GetMotionMaster()->MovementExpired();
                 me->StopMovingOnCurrentPos();
                 me->GetMotionMaster()->MoveIdle();
             }
         }
     }
 }
References CurrentWP, ESCORT_MOTION_TYPE, Unit::GetMotionMaster(), MotionMaster::GetMotionSlotType(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), HasEscortState(), LOG_DEBUG, m_bIsRunning, m_uiWPWaitTimer, ScriptedAI::me, MOTION_SLOT_ACTIVE, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), POINT_HOME, POINT_LAST_POINT, POINT_MOTION_TYPE, RemoveEscortState(), Creature::SetHomePosition(), Creature::SetPosition(), Creature::SetWalk(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, STATE_ESCORT_RETURNING, Unit::StopMovingOnCurrentPos(), WaypointList, and WaypointReached().
Referenced by boss_grand_champion::boss_grand_championAI::MovementInform(), and npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::MovementInform().
RemoveEscortState()
void npc_escortAI::RemoveEscortState (uint32 escortState) inline
Definition at line 111 of file ScriptedEscortAI.h.
 { m_uiEscortState &= ~escortState; }
References m_uiEscortState.
Referenced by violet_hold_trashAI::CreatureStartAttackDoor(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_arthas::npc_arthasAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), JustRespawned(), MovementInform(), brann_bronzebeard::brann_bronzebeardAI::Reset(), SetEscortPaused(), and UpdateAI().
ReturnToLastPoint()
void npc_escortAI::ReturnToLastPoint ()
Definition at line 193 of file ScriptedEscortAI.cpp.
 {
     float x, y, z, o;
     me->SetWalk(false);
     me->GetHomePosition(x, y, z, o);
     me->GetMotionMaster()->MovePoint(POINT_LAST_POINT, x, y, z);
 }
References Creature::GetHomePosition(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), POINT_LAST_POINT, Creature::SetWalk(), G3D::x, G3D::y, and G3D::z.
Referenced by EnterEvadeMode(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode(), npc_varian_wrynn::npc_varian_wrynnAI::EnterEvadeMode(), npc_thrall_bfu::npc_thrall_bfuAI::EnterEvadeMode(), and violet_hold_trashAI::EnterEvadeMode().
SetCanAttack()
void npc_escortAI::SetCanAttack (bool attack) inline
Definition at line 107 of file ScriptedEscortAI.h.
 { m_bIsActiveAttacker = attack; }
References m_bIsActiveAttacker.
SetDespawnAtEnd()
void npc_escortAI::SetDespawnAtEnd (bool despawn) inline
Definition at line 104 of file ScriptedEscortAI.h.
 { DespawnAtEnd = despawn; }
References DespawnAtEnd.
Referenced by boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI::boss_thorim_sif_blizzardAI(), npc_argent_soldier::npc_argent_soldierAI::npc_argent_soldierAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::npc_crok_scourgebaneAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::npc_onyx_flamecallerAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), hyjalAI::Retreat(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), hyjal_trashAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), and npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI().
SetDespawnAtFar()
void npc_escortAI::SetDespawnAtFar (bool despawn) inline
Definition at line 105 of file ScriptedEscortAI.h.
 { DespawnAtFar = despawn; }
References DespawnAtFar.
Referenced by npc_scarlet_miner::npc_scarlet_minerAI::InitCartQuest(), npc_crok_scourgebane::npc_crok_scourgebaneAI::npc_crok_scourgebaneAI(), brann_bronzebeard::brann_bronzebeardAI::Reset(), npc_mootoo_the_younger::npc_mootoo_the_youngerAI::Reset(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::Reset(), and npc_apothecary_hanes::npc_Apothecary_HanesAI::Reset().
SetEscortPaused()
void npc_escortAI::SetEscortPaused (bool on)
Definition at line 524 of file ScriptedEscortAI.cpp.
 {
     if (!HasEscortState(STATE_ESCORT_ESCORTING))
         return;
     if (on)
         AddEscortState(STATE_ESCORT_PAUSED);
     else
         RemoveEscortState(STATE_ESCORT_PAUSED);
 }
References AddEscortState(), HasEscortState(), RemoveEscortState(), STATE_ESCORT_ESCORTING, and STATE_ESCORT_PAUSED.
Referenced by brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::DoAction(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::DoAction(), npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), npc_muglash::npc_muglashAI::DoWaveSummon(), npc_captain_saeed::npc_captain_saeedAI::EnterEvadeMode(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID(), npc_cork_gizelton::npc_cork_gizeltonAI::SetGUID(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), npc_varian_wrynn::npc_varian_wrynnAI::SetHoldState(), npc_thrall_bfu::npc_thrall_bfuAI::SetHoldState(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), npc_barnes::npc_barnesAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_ranshalla::npc_ranshallaAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached(), npc_captain_saeed::npc_captain_saeedAI::WaypointReached(), npc_ranshalla::npc_ranshallaAI::WaypointReached(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_akama_illidan::npc_akama_illidanAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), npc_grimstone::npc_grimstoneAI::WaypointReached(), npc_barnes::npc_barnesAI::WaypointReached(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached(), npc_corporal_keeshan::npc_corporal_keeshanAI::WaypointReached(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::WaypointReached(), npc_tyrion_spybot::npc_tyrion_spybotAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_muglash::npc_muglashAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached(), and npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::WaypointReached().
SetMaxPlayerDistance()
void npc_escortAI::SetMaxPlayerDistance (float newMax) inline
Definition at line 101 of file ScriptedEscortAI.h.
 { MaxPlayerDistance = newMax; }
References MaxPlayerDistance.
SetNextWaypoint() [1/2]
bool npc_escortAI::SetNextWaypoint (uint32 pointId, bool setPosition = true)
Definition at line 541 of file ScriptedEscortAI.cpp.
 {
     if (!WaypointList.empty())
         WaypointList.clear();
     FillPointMovementListForCreature();
     if (WaypointList.empty())
         return false;
     Escort_Waypoint waypoint(0, 0, 0, 0, 0);
     for (CurrentWP = WaypointList.begin(); CurrentWP != WaypointList.end(); ++CurrentWP)
     {
         if (CurrentWP->id == pointId)
         {
             if (setPosition)
                 me->UpdatePosition(CurrentWP->x, CurrentWP->y, CurrentWP->z, me->GetOrientation());
             return true;
         }
     }
     return false;
 }
References CurrentWP, FillPointMovementListForCreature(), Position::GetOrientation(), ScriptedAI::me, Unit::UpdatePosition(), and WaypointList.
SetNextWaypoint() [2/2]
bool npc_escortAI::SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
Definition at line 535 of file ScriptedEscortAI.cpp.
 {
     me->UpdatePosition(x, y, z, orientation);
     return SetNextWaypoint(pointId, false);
 }
References ScriptedAI::me, Unit::UpdatePosition(), G3D::x, G3D::y, and G3D::z.
Referenced by brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), and npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath().
SetRun()
void npc_escortAI::SetRun (bool on = true)
Definition at line 429 of file ScriptedEscortAI.cpp.
 {
     if (on)
     {
         if (!m_bIsRunning)
             me->SetWalk(false);
         else
             LOG_DEBUG("scripts.ai", "EscortAI attempt to set run mode, but is already running.");
     }
     else
     {
         if (m_bIsRunning)
             me->SetWalk(true);
         else
             LOG_DEBUG("scripts.ai", "EscortAI attempt to set walk mode, but is already walking.");
     }
     m_bIsRunning = on;
 }
References LOG_DEBUG, m_bIsRunning, ScriptedAI::me, and Creature::SetWalk().
Referenced by npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::DamageTaken(), npc_arthas::npc_arthasAI::DoAction(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_arthas::npc_arthasAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::WaypointReached(), npc_rinji::npc_rinjiAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), npc_magwin::npc_magwinAI::WaypointReached(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointReached(), npc_mootoo_the_younger::npc_mootoo_the_youngerAI::WaypointReached(), npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached(), npc_maghar_captive::npc_maghar_captiveAI::WaypointReached(), npc_kurenai_captive::npc_kurenai_captiveAI::WaypointReached(), npc_kayra_longmane::npc_kayra_longmaneAI::WaypointReached(), and npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointStart().
Start()
void npc_escortAI::Start (bool isActiveAttacker = true, bool run = false, ObjectGuid playerGUID = ObjectGuid::Empty, Quest const * quest = nullptr, bool instantRespawn = false, bool canLoopPath = false, bool resetWaypoints = true)
Definition at line 450 of file ScriptedEscortAI.cpp.
 {
     if (me->GetVictim())
     {
         LOG_ERROR("entities.unit.ai", "ERROR: EscortAI (script: %s, creature entry: %u) attempts to Start while in combat", me->GetScriptName().c_str(), me->GetEntry());
         return;
     }
     if (HasEscortState(STATE_ESCORT_ESCORTING))
     {
         LOG_ERROR("entities.unit.ai", "EscortAI (script: %s, creature entry: %u) attempts to Start while already escorting", me->GetScriptName().c_str(), me->GetEntry());
         return;
     }
     if (!ScriptWP && resetWaypoints) // sd2 never adds wp in script, but tc does
     {
         if (!WaypointList.empty())
             WaypointList.clear();
         FillPointMovementListForCreature();
     }
     if (WaypointList.empty())
     {
         LOG_ERROR("sql.sql", "EscortAI (script: %s, creature entry: %u) starts with 0 waypoints (possible missing entry in script_waypoint. Quest: %u).",
                          me->GetScriptName().c_str(), me->GetEntry(), quest ? quest->GetQuestId() : 0);
         return;
     }
     //set variables
     m_bIsActiveAttacker = isActiveAttacker;
     m_bIsRunning = run;
     m_uiPlayerGUID = playerGUID;
     m_pQuestForEscort = quest;
     m_bCanInstantRespawn = instantRespawn;
     m_bCanReturnToStart = canLoopPath;
     if (m_bCanReturnToStart && m_bCanInstantRespawn)
         LOG_DEBUG("scripts.ai", "EscortAI is set to return home after waypoint end and instant respawn at waypoint end. Creature will never despawn.");
     if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == WAYPOINT_MOTION_TYPE)
     {
         me->GetMotionMaster()->MovementExpired();
         me->GetMotionMaster()->MoveIdle();
         LOG_DEBUG("scripts.ai", "EscortAI start with WAYPOINT_MOTION_TYPE, changed to MoveIdle.");
     }
     //disable npcflags
     me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
     if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC))
     {
         HasImmuneToNPCFlags = true;
         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
     }
     LOG_DEBUG("scripts.ai", "EscortAI started with " UI64FMTD " waypoints. ActiveAttacker = %d, Run = %d, PlayerGUID = %s",
         uint64(WaypointList.size()), m_bIsActiveAttacker, m_bIsRunning, m_uiPlayerGUID.ToString().c_str());
     CurrentWP = WaypointList.begin();
     //Set initial speed
     if (m_bIsRunning)
         me->SetWalk(false);
     else
         me->SetWalk(true);
     AddEscortState(STATE_ESCORT_ESCORTING);
     if (me->GetMotionMaster()->GetMotionSlotType(MOTION_SLOT_ACTIVE) == ESCORT_MOTION_TYPE)
         me->GetMotionMaster()->MovementExpired();
     me->DisableSpline();
     me->GetMotionMaster()->MoveIdle();
 }
References AddEscortState(), CurrentWP, Unit::DisableSpline(), ESCORT_MOTION_TYPE, FillPointMovementListForCreature(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Unit::GetMotionMaster(), MotionMaster::GetMotionSlotType(), Quest::GetQuestId(), Creature::GetScriptName(), Unit::GetVictim(), HasEscortState(), Object::HasFlag(), HasImmuneToNPCFlags, LOG_DEBUG, LOG_ERROR, m_bCanInstantRespawn, m_bCanReturnToStart, m_bIsActiveAttacker, m_bIsRunning, m_pQuestForEscort, m_uiPlayerGUID, ScriptedAI::me, MOTION_SLOT_ACTIVE, MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), Object::RemoveFlag(), ScriptWP, Object::SetUInt32Value(), Creature::SetWalk(), STATE_ESCORT_ESCORTING, ObjectGuid::ToString(), UI64FMTD, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, WAYPOINT_MOTION_TYPE, and WaypointList.
Referenced by boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI(), boss_thorim_lightning_orb::boss_thorim_lightning_orbAI::boss_thorim_lightning_orbAI(), boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI::boss_thorim_sif_blizzardAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::boss_yoggsaron_cloudAI(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::DoAction(), npc_taretha::npc_tarethaAI::DoAction(), npc_scarlet_miner::npc_scarlet_minerAI::InitCartQuest(), npc_kservant::npc_kservantAI::IsSummonedBy(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::npc_ancestral_wolfAI(), npc_frosthound::npc_frosthoundAI::PassengerBoarded(), npc_icefang::npc_icefangAI::PassengerBoarded(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::Reset(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::Reset(), npc_plaguehound_tracker::npc_plaguehound_trackerAI::Reset(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::Reset(), hyjalAI::Retreat(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), boss_grand_champion::boss_grand_championAI::SetData(), npc_argent_soldier::npc_argent_soldierAI::SetData(), npc_kurenai_captive::npc_kurenai_captiveAI::SetGUID(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::sQuestAccept(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_muglash::npc_muglashAI::sQuestAccept(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::sQuestAccept(), npc_barnes::npc_barnesAI::StartEvent(), npc_clintar_spirit::npc_clintar_spiritAI::StartEvent(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), hyjal_trashAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), and npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI().
UpdateAI()
void npc_escortAI::UpdateAI (uint32 diff) override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_earthmender_wilda::npc_earthmender_wildaAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_engineer_helice::npc_engineer_heliceAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_captain_saeed::npc_captain_saeedAI, npc_maghar_captive::npc_maghar_captiveAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_lurgglbr::npc_lurgglbrAI, npc_azure_saboteur::npc_azure_saboteurAI, npc_azure_sorceror::npc_azure_sorcerorAI, npc_azure_captain::npc_azure_captainAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_binder::npc_azure_binderAI, npc_azure_invader::npc_azure_invaderAI, violet_hold_trashAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_grand_champion::boss_grand_championAI, npc_argent_soldier::npc_argent_soldierAI, npc_ame::npc_ameAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_muglash::npc_muglashAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_arthas::npc_arthasAI, hyjalAI, hyjal_trashAI, npc_gargoyle::npc_gargoyleAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_fel_stalker::npc_fel_stalkerAI, npc_crypt_fiend::npc_crypt_fiendAI, npc_banshee::npc_bansheeAI, npc_necromancer::npc_necromancerAI, npc_ghoul::npc_ghoulAI, npc_abomination::npc_abominationAI, npc_giant_infernal::npc_giant_infernalAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_azgalor::boss_azgalorAI, boss_anetheron::boss_anetheronAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_barnes::npc_barnesAI, and npc_rocknot::npc_rocknotAI.
Definition at line 241 of file ScriptedEscortAI.cpp.
 {
     if (HasEscortState(STATE_ESCORT_ESCORTING) && !me->GetVictim() && m_uiWPWaitTimer && !HasEscortState(STATE_ESCORT_RETURNING))
     {
         if (m_uiWPWaitTimer <= diff)
         {
             if (CurrentWP == WaypointList.end())
             {
                 if (DespawnAtEnd)
                 {
                     if (m_bCanReturnToStart)
                     {
                         float fRetX, fRetY, fRetZ;
                         me->GetRespawnPosition(fRetX, fRetY, fRetZ);
                         me->GetMotionMaster()->MovePoint(POINT_HOME, fRetX, fRetY, fRetZ);
                         m_uiWPWaitTimer = 0;
                         return;
                     }
                     if (m_bCanInstantRespawn)
                     {
                         me->setDeathState(JUST_DIED);
                         me->Respawn();
                     }
                     else
                         me->DespawnOrUnsummon();
                 }
                 // xinef: remove escort state, escort was finished (lack of this line resulted in skipping UpdateEscortAI calls after finished escort)
                 RemoveEscortState(STATE_ESCORT_ESCORTING);
                 return;
             }
             if (!HasEscortState(STATE_ESCORT_PAUSED))
             {
                 // xinef, start escort if there is no spline active
                 if (me->movespline->Finalized())
                 {
                     Movement::PointsArray pathPoints;
                     GenerateWaypointArray(&pathPoints);
                     me->GetMotionMaster()->MoveSplinePath(&pathPoints);
                 }
                 WaypointStart(CurrentWP->id);
                 m_uiWPWaitTimer = 0;
             }
         }
         else
             m_uiWPWaitTimer -= diff;
     }
     //Check if player or any member of his group is within range
     if (HasEscortState(STATE_ESCORT_ESCORTING) && m_uiPlayerGUID && !me->GetVictim() && !HasEscortState(STATE_ESCORT_RETURNING))
     {
         m_uiPlayerCheckTimer += diff;
         if (m_uiPlayerCheckTimer > 1000)
         {
             if (DespawnAtFar && !IsPlayerOrGroupInRange())
             {
                 if (m_bCanInstantRespawn)
                 {
                     me->setDeathState(JUST_DIED);
                     me->Respawn();
                 }
                 else
                     me->DespawnOrUnsummon();
                 return;
             }
             m_uiPlayerCheckTimer = 0;
         }
     }
     UpdateEscortAI(diff);
 }
References CurrentWP, DespawnAtEnd, DespawnAtFar, Creature::DespawnOrUnsummon(), diff(), Movement::MoveSpline::Finalized(), GenerateWaypointArray(), Unit::GetMotionMaster(), Creature::GetRespawnPosition(), Unit::GetVictim(), HasEscortState(), IsPlayerOrGroupInRange(), JUST_DIED, m_bCanInstantRespawn, m_bCanReturnToStart, m_uiPlayerCheckTimer, m_uiPlayerGUID, m_uiWPWaitTimer, ScriptedAI::me, MotionMaster::MovePoint(), Unit::movespline, MotionMaster::MoveSplinePath(), POINT_HOME, RemoveEscortState(), Creature::Respawn(), Creature::setDeathState(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, STATE_ESCORT_RETURNING, UpdateEscortAI(), WaypointList, and WaypointStart().
Referenced by hyjalAI::DoOverrun(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_rocknot::npc_rocknotAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_muglash::npc_muglashAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_custodian_of_time::npc_custodian_of_timeAI::UpdateAI(), npc_ame::npc_ameAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_mimirons_inferno::npc_mimirons_infernoAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_frosthound::npc_frosthoundAI::UpdateAI(), npc_icefang::npc_icefangAI::UpdateAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_garments_of_quests::npc_garments_of_questsAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::UpdateAI(), npc_engineer_helice::npc_engineer_heliceAI::UpdateAI(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), and npc_earthmender_wilda::npc_earthmender_wildaAI::UpdateAI().
UpdateEscortAI()
void npc_escortAI::UpdateEscortAI (uint32 diff) virtual
Reimplemented in npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_isla_starmane::npc_isla_starmaneAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_akama_illidan::npc_akama_illidanAI, npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, brann_bronzebeard::brann_bronzebeardAI, boss_bjarngrim::boss_bjarngrimAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, npc_ranshalla::npc_ranshallaAI, npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_magwin::npc_magwinAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_rinji::npc_rinjiAI, and npc_grimstone::npc_grimstoneAI.
Definition at line 319 of file ScriptedEscortAI.cpp.
 {
     if (!UpdateVictim())
         return;
     DoMeleeAttackIfReady();
 }
References UnitAI::DoMeleeAttackIfReady(), and CreatureAI::UpdateVictim().
Referenced by UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), and npc_ranshalla::npc_ranshallaAI::UpdateEscortAI().
WaypointReached()
virtual void npc_escortAI::WaypointReached (uint32 pointId) pure virtual
Implemented in npc_garments_of_quests::npc_garments_of_questsAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, npc_icefang::npc_icefangAI, npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_lesser_doomguard::npc_lesser_doomguardAI, npc_kayra_longmane::npc_kayra_longmaneAI, npc_isla_starmane::npc_isla_starmaneAI, npc_kservant::npc_kservantAI, npc_earthmender_wilda::npc_earthmender_wildaAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_bessy::npc_bessyAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_maghar_captive::npc_maghar_captiveAI, npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_ancestral_wolf::npc_ancestral_wolfAI, npc_frosthound::npc_frosthoundAI, npc_engineer_helice::npc_engineer_heliceAI, npc_plaguehound_tracker::npc_plaguehound_trackerAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, npc_emily::npc_emilyAI, npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_mootoo_the_younger::npc_mootoo_the_youngerAI, npc_lurgglbr::npc_lurgglbrAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, npc_ame::npc_ameAI, npc_paoka_swiftmountain::npc_paoka_swiftmountainAI, npc_lakota_windsong::npc_lakota_windsongAI, npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI, npc_gilthares::npc_giltharesAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_kaya_flathoof::npc_kaya_flathoofAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_prospector_remtravel::npc_prospector_remtravelAI, npc_magwin::npc_magwinAI, npc_muglash::npc_muglashAI, npc_taretha::npc_tarethaAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, hyjalAI, npc_gargoyle::npc_gargoyleAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_fel_stalker::npc_fel_stalkerAI, npc_crypt_fiend::npc_crypt_fiendAI, npc_banshee::npc_bansheeAI, npc_necromancer::npc_necromancerAI, npc_ghoul::npc_ghoulAI, npc_abomination::npc_abominationAI, npc_giant_infernal::npc_giant_infernalAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, boss_azgalor::boss_azgalorAI, boss_anetheron::boss_anetheronAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_deathstalker_erland::npc_deathstalker_erlandAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_rinji::npc_rinjiAI, npc_ranger_lilatha::npc_ranger_lilathaAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_barnes::npc_barnesAI, npc_rocknot::npc_rocknotAI, npc_grimstone::npc_grimstoneAI, npc_azure_saboteur::npc_azure_saboteurAI, npc_arthas::npc_arthasAI, npc_argent_soldier::npc_argent_soldierAI, npc_akama_illidan::npc_akama_illidanAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_ranshalla::npc_ranshallaAI, boss_bjarngrim::boss_bjarngrimAI, violet_hold_trashAI, brann_bronzebeard::brann_bronzebeardAI, npc_captain_saeed::npc_captain_saeedAI, boss_grand_champion::boss_grand_championAI, and npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI.
Referenced by MovementInform().
WaypointStart()
virtual void npc_escortAI::WaypointStart (uint32) inline virtual
Reimplemented in npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, and npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI.
Definition at line 91 of file ScriptedEscortAI.h.
 {}
Referenced by UpdateAI().
Member Data Documentation
CurrentWP
std::list<Escort_Waypoint>::iterator npc_escortAI::CurrentWP private
Definition at line 130 of file ScriptedEscortAI.h.
Referenced by GenerateWaypointArray(), MovementInform(), SetNextWaypoint(), Start(), and UpdateAI().
DespawnAtEnd
bool npc_escortAI::DespawnAtEnd private
Definition at line 136 of file ScriptedEscortAI.h.
Referenced by SetDespawnAtEnd(), and UpdateAI().
DespawnAtFar
bool npc_escortAI::DespawnAtFar private
Definition at line 137 of file ScriptedEscortAI.h.
Referenced by SetDespawnAtFar(), and UpdateAI().
HasImmuneToNPCFlags
bool npc_escortAI::HasImmuneToNPCFlags private
Definition at line 139 of file ScriptedEscortAI.h.
Referenced by EnterEvadeMode(), and Start().
m_bCanInstantRespawn
bool npc_escortAI::m_bCanInstantRespawn private
Definition at line 134 of file ScriptedEscortAI.h.
Referenced by Start(), and UpdateAI().
m_bCanReturnToStart
bool npc_escortAI::m_bCanReturnToStart private
Definition at line 135 of file ScriptedEscortAI.h.
Referenced by Start(), and UpdateAI().
m_bIsActiveAttacker
bool npc_escortAI::m_bIsActiveAttacker private
Definition at line 132 of file ScriptedEscortAI.h.
Referenced by GetAttack(), SetCanAttack(), and Start().
m_bIsRunning
bool npc_escortAI::m_bIsRunning private
Definition at line 133 of file ScriptedEscortAI.h.
Referenced by MovementInform(), SetRun(), and Start().
m_pQuestForEscort
Quest const* npc_escortAI::m_pQuestForEscort private
Definition at line 127 of file ScriptedEscortAI.h.
Referenced by JustDied(), and Start().
m_uiEscortState
uint32 npc_escortAI::m_uiEscortState private
Definition at line 124 of file ScriptedEscortAI.h.
Referenced by AddEscortState(), HasEscortState(), IsEscorted(), and RemoveEscortState().
m_uiPlayerCheckTimer
uint32 npc_escortAI::m_uiPlayerCheckTimer private
Definition at line 123 of file ScriptedEscortAI.h.
Referenced by UpdateAI().
m_uiPlayerGUID
ObjectGuid npc_escortAI::m_uiPlayerGUID private
Definition at line 121 of file ScriptedEscortAI.h.
Referenced by GetEventStarterGUID(), GetPlayerForEscort(), JustDied(), Start(), and UpdateAI().
m_uiWPWaitTimer
uint32 npc_escortAI::m_uiWPWaitTimer private
Definition at line 122 of file ScriptedEscortAI.h.
Referenced by JustRespawned(), MovementInform(), and UpdateAI().
MaxPlayerDistance
float npc_escortAI::MaxPlayerDistance private
Definition at line 125 of file ScriptedEscortAI.h.
Referenced by GetMaxPlayerDistance(), and SetMaxPlayerDistance().
ScriptWP
bool npc_escortAI::ScriptWP private
Definition at line 138 of file ScriptedEscortAI.h.
Referenced by AddWaypoint(), and Start().
WaypointList
std::list<Escort_Waypoint> npc_escortAI::WaypointList private
Definition at line 129 of file ScriptedEscortAI.h.
Referenced by AddWaypoint(), FillPointMovementListForCreature(), GenerateWaypointArray(), MovementInform(), SetNextWaypoint(), Start(), and UpdateAI().
The documentation for this struct was generated from the following files:
src/server/game/AI/ScriptedAI/ScriptedEscortAI.h
src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp