Azerotcore-wotlk: FarthestTargetSelector Struct Reference
FarthestTargetSelector Struct Reference
#include <UnitAI.h>
Public Member Functions
FarthestTargetSelector (Unit const *unit, float dist, bool playerOnly, bool inLos)
bool operator() (Unit const *target) const
Private Attributes
const Unit * _me
float _dist
bool _playerOnly
bool _inLos
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 148 of file UnitAI.h.
Constructor & Destructor Documentation
FarthestTargetSelector()
FarthestTargetSelector::FarthestTargetSelector (Unit const * unit, float dist, bool playerOnly, bool inLos) inline
Definition at line 150 of file UnitAI.h.
 : _me(unit), _dist(dist), _playerOnly(playerOnly), _inLos(inLos) {}
Member Function Documentation
operator()()
bool FarthestTargetSelector::operator() (Unit const * target) const inline
Definition at line 152 of file UnitAI.h.
     {
         if (!_me || !target)
             return false;
         if (_playerOnly && target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (_dist > 0.0f && !_me->IsWithinCombatRange(target, _dist))
             return false;
         if (_inLos && !_me->IsWithinLOSInMap(target))
             return false;
         return true;
     }
References _dist, _inLos, _me, _playerOnly, Object::GetTypeId(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), and TYPEID_PLAYER.
Member Data Documentation
_dist
float FarthestTargetSelector::_dist private
Definition at line 171 of file UnitAI.h.
Referenced by operator()().
_inLos
bool FarthestTargetSelector::_inLos private
Definition at line 173 of file UnitAI.h.
Referenced by operator()().
_me
const Unit* FarthestTargetSelector::_me private
Definition at line 170 of file UnitAI.h.
Referenced by operator()().
_playerOnly
bool FarthestTargetSelector::_playerOnly private
Definition at line 172 of file UnitAI.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/game/AI/CoreAI/UnitAI.h