Azerotcore-wotlk: deps/mysqllite/include/internal/my_md5.h File Reference
my_md5.h File Reference
Classes
struct my_MD5Context
Macros
#define MY_MD5_HASH(digest, buf, len)
Typedefs
typedef uint32 cvs_uint32
Functions
void my_MD5Init (my_MD5Context *context)
void my_MD5Update (my_MD5Context *context, unsigned char const *buf, unsigned len)
void my_MD5Final (unsigned char digest[16], my_MD5Context *context)
Macro Definition Documentation
MY_MD5_HASH
#define MY_MD5_HASH (digest, buf, len)
Value:
do { \
  my_MD5Context ctx; \
  my_MD5Init (&ctx); \
  my_MD5Update (&ctx, buf, len); \
  my_MD5Final (digest, &ctx); \
} while (0)
Definition at line 51 of file my_md5.h.
Typedef Documentation
cvs_uint32
typedef uint32 cvs_uint32
Definition at line 30 of file my_md5.h.
Function Documentation
my_MD5Final()
void my_MD5Final (unsigned char digest[16], my_MD5Context * context)
Definition at line 141 of file md5.c.
 {
   unsigned count;
   unsigned char *p;
   /* Compute number of bytes mod 64 */
   count = (ctx->bits[0] >> 3) & 0x3F;
   /* Set the first char of padding to 0x80.  This is safe since there is
     always at least one byte free */
   p = ctx->in + count;
   *p++ = 0x80;
   /* Bytes of padding needed to make 64 bytes */
   count = 64 - 1 - count;
   /* Pad out to 56 mod 64 */
   if (count < 8) {
     /* Two lots of padding:  Pad the first block to 64 bytes */
     memset(p, 0, count);
     my_MD5Transform (ctx->buf, ctx->in);
     /* Now fill the next block with 56 bytes */
     memset(ctx->in, 0, 56);
   } else {
     /* Pad block to 56 bytes */
     memset(p, 0, count-8);
   }
   /* Append length in bits and transform */
   putu32(ctx->bits[0], ctx->in + 56);
   putu32(ctx->bits[1], ctx->in + 60);
   my_MD5Transform (ctx->buf, ctx->in);
   putu32(ctx->buf[0], digest);
   putu32(ctx->buf[1], digest + 4);
   putu32(ctx->buf[2], digest + 8);
   putu32(ctx->buf[3], digest + 12);
   memset(ctx, 0, sizeof(ctx));  /* In case it's sensitive */
 }
References my_MD5Context::bits, my_MD5Context::buf, count(), my_MD5Context::in, memset, my_MD5Transform(), and putu32().
my_MD5Init()
void my_MD5Init (my_MD5Context * context)
Definition at line 77 of file md5.c.
 {
   ctx->buf[0] = 0x67452301;
   ctx->buf[1] = 0xefcdab89;
   ctx->buf[2] = 0x98badcfe;
   ctx->buf[3] = 0x10325476;
   ctx->bits[0] = 0;
   ctx->bits[1] = 0;
 }
References my_MD5Context::bits, and my_MD5Context::buf.
my_MD5Update()
void my_MD5Update (my_MD5Context * context, unsigned char const * buf, unsigned len)
Definition at line 93 of file md5.c.
 {
   uint32 t;
   /* Update bitcount */
   t = ctx->bits[0];
   if ((ctx->bits[0] = (t + ((uint32)len << 3)) & 0xffffffff) < t)
     ctx->bits[1]++; /* Carry from low to high */
   ctx->bits[1] += len >> 29;
   t = (t >> 3) & 0x3f;  /* Bytes already in shsInfo->data */
   /* Handle any leading odd-sized chunks */
   if ( t ) {
     unsigned char *p = ctx->in + t;
     t = 64-t;
     if (len < t) {
       memcpy(p, buf, len);
       return;
     }
     memcpy(p, buf, t);
     my_MD5Transform (ctx->buf, ctx->in);
     buf += t;
     len -= t;
   }
   /* Process data in 64-byte chunks */
   while (len >= 64) {
     memcpy(ctx->in, buf, 64);
     my_MD5Transform (ctx->buf, ctx->in);
     buf += 64;
     len -= 64;
   }
   /* Handle any remaining bytes of data. */
   memcpy(ctx->in, buf, len);
 }
References my_MD5Context::bits, my_MD5Context::buf, my_MD5Context::in, memcpy, and my_MD5Transform().