Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/arena_externs.h File Reference
arena_externs.h File Reference
#include "jemalloc/internal/bin.h"
#include "jemalloc/internal/extent_dss.h"
#include "jemalloc/internal/hook.h"
#include "jemalloc/internal/pages.h"
#include "jemalloc/internal/stats.h"
Typedefs
typedef void() arena_dalloc_junk_small_t(void *, const bin_info_t *)
Functions
void arena_basic_stats_merge (tsdn_t *tsdn, arena_t *arena, unsigned *nthreads, const char **dss, ssize_t *dirty_decay_ms, ssize_t *muzzy_decay_ms, size_t *nactive, size_t *ndirty, size_t *nmuzzy)
void arena_stats_merge (tsdn_t *tsdn, arena_t *arena, unsigned *nthreads, const char **dss, ssize_t *dirty_decay_ms, ssize_t *muzzy_decay_ms, size_t *nactive, size_t *ndirty, size_t *nmuzzy, arena_stats_t *astats, bin_stats_t *bstats, arena_stats_large_t *lstats, arena_stats_extents_t *estats)
void arena_extents_dirty_dalloc (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
extent_t * arena_extent_alloc_large (tsdn_t *tsdn, arena_t *arena, size_t usize, size_t alignment, bool *zero)
void arena_extent_dalloc_large_prep (tsdn_t *tsdn, arena_t *arena, extent_t *extent)
void arena_extent_ralloc_large_shrink (tsdn_t *tsdn, arena_t *arena, extent_t *extent, size_t oldsize)
void arena_extent_ralloc_large_expand (tsdn_t *tsdn, arena_t *arena, extent_t *extent, size_t oldsize)
ssize_t arena_dirty_decay_ms_get (arena_t *arena)
bool arena_dirty_decay_ms_set (tsdn_t *tsdn, arena_t *arena, ssize_t decay_ms)
ssize_t arena_muzzy_decay_ms_get (arena_t *arena)
bool arena_muzzy_decay_ms_set (tsdn_t *tsdn, arena_t *arena, ssize_t decay_ms)
void arena_decay (tsdn_t *tsdn, arena_t *arena, bool is_background_thread, bool all)
void arena_reset (tsd_t *tsd, arena_t *arena)
void arena_destroy (tsd_t *tsd, arena_t *arena)
void arena_tcache_fill_small (tsdn_t *tsdn, arena_t *arena, tcache_t *tcache, cache_bin_t *tbin, szind_t binind, uint64_t prof_accumbytes)
void arena_alloc_junk_small (void *ptr, const bin_info_t *bin_info, bool zero)
void * arena_malloc_hard (tsdn_t *tsdn, arena_t *arena, size_t size, szind_t ind, bool zero)
void * arena_palloc (tsdn_t *tsdn, arena_t *arena, size_t usize, size_t alignment, bool zero, tcache_t *tcache)
void arena_prof_promote (tsdn_t *tsdn, void *ptr, size_t usize)
void arena_dalloc_promoted (tsdn_t *tsdn, void *ptr, tcache_t *tcache, bool slow_path)
void arena_dalloc_bin_junked_locked (tsdn_t *tsdn, arena_t *arena, bin_t *bin, szind_t binind, extent_t *extent, void *ptr)
void arena_dalloc_small (tsdn_t *tsdn, void *ptr)
bool arena_ralloc_no_move (tsdn_t *tsdn, void *ptr, size_t oldsize, size_t size, size_t extra, bool zero, size_t *newsize)
void * arena_ralloc (tsdn_t *tsdn, arena_t *arena, void *ptr, size_t oldsize, size_t size, size_t alignment, bool zero, tcache_t *tcache, hook_ralloc_args_t *hook_args)
dss_prec_t arena_dss_prec_get (arena_t *arena)
bool arena_dss_prec_set (arena_t *arena, dss_prec_t dss_prec)
ssize_t arena_dirty_decay_ms_default_get (void)
bool arena_dirty_decay_ms_default_set (ssize_t decay_ms)
ssize_t arena_muzzy_decay_ms_default_get (void)
bool arena_muzzy_decay_ms_default_set (ssize_t decay_ms)
bool arena_retain_grow_limit_get_set (tsd_t *tsd, arena_t *arena, size_t *old_limit, size_t *new_limit)
unsigned arena_nthreads_get (arena_t *arena, bool internal)
void arena_nthreads_inc (arena_t *arena, bool internal)
void arena_nthreads_dec (arena_t *arena, bool internal)
size_t arena_extent_sn_next (arena_t *arena)
arena_t * arena_new (tsdn_t *tsdn, unsigned ind, extent_hooks_t *extent_hooks)
bool arena_init_huge (void)
bool arena_is_huge (unsigned arena_ind)
arena_t * arena_choose_huge (tsd_t *tsd)
bin_t * arena_bin_choose_lock (tsdn_t *tsdn, arena_t *arena, szind_t binind, unsigned *binshard)
void arena_boot (sc_data_t *sc_data)
void arena_prefork0 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork1 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork2 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork3 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork4 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork5 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork6 (tsdn_t *tsdn, arena_t *arena)
void arena_prefork7 (tsdn_t *tsdn, arena_t *arena)
void arena_postfork_parent (tsdn_t *tsdn, arena_t *arena)
void arena_postfork_child (tsdn_t *tsdn, arena_t *arena)
Variables
ssize_t opt_dirty_decay_ms
ssize_t opt_muzzy_decay_ms
percpu_arena_mode_t opt_percpu_arena
const char * percpu_arena_mode_names []
const uint64_t h_steps [SMOOTHSTEP_NSTEPS]
malloc_mutex_t arenas_lock
size_t opt_oversize_threshold
size_t oversize_threshold
arena_dalloc_junk_small_t *JET_MUTABLE arena_dalloc_junk_small
Typedef Documentation
arena_dalloc_junk_small_t
typedef void() arena_dalloc_junk_small_t(void *, const bin_info_t *)
Definition at line 56 of file arena_externs.h.
Function Documentation
arena_alloc_junk_small()
void arena_alloc_junk_small (void * ptr, const bin_info_t * bin_info, bool zero)
Definition at line 1446 of file arena.c.
{
     if (!zero) {
         memset(ptr, JEMALLOC_ALLOC_JUNK, bin_info->reg_size);
     }
 }
References JEMALLOC_ALLOC_JUNK, memset, ptr(), bin_info_s::reg_size, and G3D::zero().
Referenced by arena_malloc_small(), and arena_tcache_fill_small().
arena_basic_stats_merge()
void arena_basic_stats_merge (tsdn_t * tsdn, arena_t * arena, unsigned * nthreads, const char ** dss, ssize_t * dirty_decay_ms, ssize_t * muzzy_decay_ms, size_t * nactive, size_t * ndirty, size_t * nmuzzy)
Definition at line 70 of file arena.c.
{
     *nthreads += arena_nthreads_get(arena, false);
     *dss = dss_prec_names[arena_dss_prec_get(arena)];
     *dirty_decay_ms = arena_dirty_decay_ms_get(arena);
     *muzzy_decay_ms = arena_muzzy_decay_ms_get(arena);
     *nactive += atomic_load_zu(&arena->nactive, ATOMIC_RELAXED);
     *ndirty += extents_npages_get(&arena->extents_dirty);
     *nmuzzy += extents_npages_get(&arena->extents_muzzy);
 }
References arena, arena_dirty_decay_ms_get(), arena_dss_prec_get(), arena_muzzy_decay_ms_get(), arena_nthreads_get(), ATOMIC_RELAXED, dss_prec_names, arena_s::extents_dirty, arena_s::extents_muzzy, extents_npages_get, and arena_s::nactive.
Referenced by arena_stats_merge().
arena_bin_choose_lock()
bin_t* arena_bin_choose_lock (tsdn_t * tsdn, arena_t * arena, szind_t binind, unsigned * binshard)
Definition at line 1365 of file arena.c.
{
     bin_t *bin;
     if (tsdn_null(tsdn) || tsd_arena_get(tsdn_tsd(tsdn)) == NULL) {
         *binshard = 0;
     } else {
         *binshard = tsd_binshardsp_get(tsdn_tsd(tsdn))->binshard[binind];
     }
     assert(*binshard < bin_infos[binind].n_shards);
     bin = &arena->bins[binind].bin_shards[*binshard];
     malloc_mutex_lock(tsdn, &bin->lock);
     return bin;
 }
References arena, assert(), bin_infos, bins_s::bin_shards, arena_s::bins, bin_s::lock, malloc_mutex_lock(), NULL, tsdn_null(), and tsdn_tsd().
Referenced by arena_malloc_small(), and arena_tcache_fill_small().
arena_boot()
void arena_boot (sc_data_t * sc_data)
Definition at line 2171 of file arena.c.
{
     arena_dirty_decay_ms_default_set(opt_dirty_decay_ms);
     arena_muzzy_decay_ms_default_set(opt_muzzy_decay_ms);
     for (unsigned i = 0; i < SC_NBINS; i++) {
         sc_t *sc = &sc_data->sc[i];
         div_init(&arena_binind_div_info[i],
             (1U << sc->lg_base) + (sc->ndelta << sc->lg_delta));
     }
 }
References arena_binind_div_info, arena_dirty_decay_ms_default_set(), arena_muzzy_decay_ms_default_set(), div_init, sc_s::lg_base, sc_s::lg_delta, sc_s::ndelta, opt_dirty_decay_ms, opt_muzzy_decay_ms, sc_data_s::sc, and SC_NBINS.
arena_choose_huge()
arena_t* arena_choose_huge (tsd_t * tsd)
Definition at line 2111 of file arena.c.
{
     /* huge_arena_ind can be 0 during init (will use a0). */
     if (huge_arena_ind == 0) {
         assert(!malloc_initialized());
     }
     arena_t *huge_arena = arena_get(tsd_tsdn(tsd), huge_arena_ind, false);
     if (huge_arena == NULL) {
         /* Create the huge arena on demand. */
         assert(huge_arena_ind != 0);
         huge_arena = arena_get(tsd_tsdn(tsd), huge_arena_ind, true);
         if (huge_arena == NULL) {
             return NULL;
         }
         /*
          * Purge eagerly for huge allocations, because: 1) number of
          * huge allocations is usually small, which means ticker based
          * decay is not reliable; and 2) less immediate reuse is
          * expected for huge allocations.
          */
         if (arena_dirty_decay_ms_default_get() > 0) {
             arena_dirty_decay_ms_set(tsd_tsdn(tsd), huge_arena, 0);
         }
         if (arena_muzzy_decay_ms_default_get() > 0) {
             arena_muzzy_decay_ms_set(tsd_tsdn(tsd), huge_arena, 0);
         }
     }
     return huge_arena;
 }
References arena_dirty_decay_ms_default_get(), arena_dirty_decay_ms_set(), arena_get(), arena_muzzy_decay_ms_default_get(), arena_muzzy_decay_ms_set(), assert(), huge_arena_ind, malloc_initialized, NULL, and tsd_tsdn().
arena_dalloc_bin_junked_locked()
void arena_dalloc_bin_junked_locked (tsdn_t * tsdn, arena_t * arena, bin_t * bin, szind_t binind, extent_t * extent, void * ptr)
Definition at line 1712 of file arena.c.
{
     arena_dalloc_bin_locked_impl(tsdn, arena, bin, binind, extent, ptr,
         true);
 }
References arena, arena_dalloc_bin_locked_impl(), and ptr().
arena_dalloc_promoted()
void arena_dalloc_promoted (tsdn_t * tsdn, void * ptr, tcache_t * tcache, bool slow_path)
Definition at line 1597 of file arena.c.
                     {
     cassert(config_prof);
     assert(opt_prof);
     extent_t *extent = iealloc(tsdn, ptr);
     size_t usize = extent_usize_get(extent);
     size_t bumped_usize = arena_prof_demote(tsdn, extent, ptr);
     if (config_opt_safety_checks && usize < SC_LARGE_MINCLASS) {
         /*
          * Currently, we only do redzoning for small sampled
          * allocations.
          */
         assert(bumped_usize == SC_LARGE_MINCLASS);
         safety_check_verify_redzone(ptr, usize, bumped_usize);
     }
     if (bumped_usize <= tcache_maxclass && tcache != NULL) {
         tcache_dalloc_large(tsdn_tsd(tsdn), tcache, ptr,
             sz_size2index(bumped_usize), slow_path);
     } else {
         large_dalloc(tsdn, extent);
     }
 }
References arena_prof_demote(), assert(), cassert(), config_opt_safety_checks, config_prof, extent_usize_get(), iealloc(), large_dalloc, NULL, opt_prof, ptr(), safety_check_verify_redzone(), SC_LARGE_MINCLASS, sz_size2index(), tcache_dalloc_large(), tcache_maxclass, and tsdn_tsd().
arena_dalloc_small()
void arena_dalloc_small (tsdn_t * tsdn, void * ptr)
Definition at line 1731 of file arena.c.
{
     extent_t *extent = iealloc(tsdn, ptr);
     arena_t *arena = extent_arena_get(extent);
     arena_dalloc_bin(tsdn, arena, extent, ptr);
     arena_decay_tick(tsdn, arena);
 }
References arena, arena_dalloc_bin(), arena_decay_tick(), extent_arena_get(), iealloc(), and ptr().
arena_decay()
void arena_decay (tsdn_t * tsdn, arena_t * arena, bool is_background_thread, bool all)
Definition at line 997 of file arena.c.
{
     if (arena_decay_dirty(tsdn, arena, is_background_thread, all)) {
         return;
     }
     arena_decay_muzzy(tsdn, arena, is_background_thread, all);
 }
References G3D::all(), arena, arena_decay_dirty(), and arena_decay_muzzy().
arena_destroy()
void arena_destroy (tsd_t * tsd, arena_t * arena)
Definition at line 1170 of file arena.c.
{
     assert(base_ind_get(arena->base) >= narenas_auto);
     assert(arena_nthreads_get(arena, false) == 0);
     assert(arena_nthreads_get(arena, true) == 0);
     /*
      * No allocations have occurred since arena_reset() was called.
      * Furthermore, the caller (arena_i_destroy_ctl()) purged all cached
      * extents, so only retained extents may remain.
      */
     assert(extents_npages_get(&arena->extents_dirty) == 0);
     assert(extents_npages_get(&arena->extents_muzzy) == 0);
     /* Deallocate retained memory. */
     arena_destroy_retained(tsd_tsdn(tsd), arena);
     /*
      * Remove the arena pointer from the arenas array.  We rely on the fact
      * that there is no way for the application to get a dirty read from the
      * arenas array unless there is an inherent race in the application
      * involving access of an arena being concurrently destroyed.  The
      * application must synchronize knowledge of the arena's validity, so as
      * long as we use an atomic write to update the arenas array, the
      * application will get a clean read any time after it synchronizes
      * knowledge that the arena is no longer valid.
      */
     arena_set(base_ind_get(arena->base), NULL);
     /*
      * Destroy the base allocator, which manages all metadata ever mapped by
      * this arena.
      */
     base_delete(tsd_tsdn(tsd), arena->base);
 }
References arena, arena_destroy_retained(), arena_nthreads_get(), arena_set, assert(), arena_s::base, base_delete, base_ind_get(), arena_s::extents_dirty, arena_s::extents_muzzy, extents_npages_get, narenas_auto, NULL, and tsd_tsdn().
arena_dirty_decay_ms_default_get()
ssize_t arena_dirty_decay_ms_default_get (void)
Definition at line 1868 of file arena.c.
{
     return atomic_load_zd(&dirty_decay_ms_default, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and dirty_decay_ms_default.
Referenced by arena_choose_huge(), and arena_new().
arena_dirty_decay_ms_default_set()
bool arena_dirty_decay_ms_default_set (ssize_t decay_ms)
Definition at line 1873 of file arena.c.
{
     if (!arena_decay_ms_valid(decay_ms)) {
         return true;
     }
     atomic_store_zd(&dirty_decay_ms_default, decay_ms, ATOMIC_RELAXED);
     return false;
 }
References arena_decay_ms_valid(), ATOMIC_RELAXED, and dirty_decay_ms_default.
Referenced by arena_boot().
arena_dirty_decay_ms_get()
ssize_t arena_dirty_decay_ms_get (arena_t * arena)
Definition at line 777 of file arena.c.
{
     return arena_decay_ms_get(&arena->decay_dirty);
 }
References arena, arena_decay_ms_get(), and arena_s::decay_dirty.
Referenced by arena_basic_stats_merge(), and arena_extents_dirty_dalloc().
arena_dirty_decay_ms_set()
bool arena_dirty_decay_ms_set (tsdn_t * tsdn, arena_t * arena, ssize_t decay_ms)
Definition at line 810 of file arena.c.
                       {
     return arena_decay_ms_set(tsdn, arena, &arena->decay_dirty,
         &arena->extents_dirty, decay_ms);
 }
References arena, arena_decay_ms_set(), arena_s::decay_dirty, and arena_s::extents_dirty.
Referenced by arena_choose_huge().
arena_dss_prec_get()
dss_prec_t arena_dss_prec_get (arena_t * arena)
Definition at line 1854 of file arena.c.
{
     return (dss_prec_t)atomic_load_u(&arena->dss_prec, ATOMIC_ACQUIRE);
 }
References arena, ATOMIC_ACQUIRE, and arena_s::dss_prec.
Referenced by arena_basic_stats_merge().
arena_dss_prec_set()
bool arena_dss_prec_set (arena_t * arena, dss_prec_t dss_prec)
Definition at line 1859 of file arena.c.
{
     if (!have_dss) {
         return (dss_prec != dss_prec_disabled);
     }
     atomic_store_u(&arena->dss_prec, (unsigned)dss_prec, ATOMIC_RELEASE);
     return false;
 }
References arena, ATOMIC_RELEASE, arena_s::dss_prec, dss_prec_disabled, and have_dss.
arena_extent_alloc_large()
extent_t* arena_extent_alloc_large (tsdn_t * tsdn, arena_t * arena, size_t usize, size_t alignment, bool * zero)
Definition at line 428 of file arena.c.
{
     extent_hooks_t *extent_hooks = EXTENT_HOOKS_INITIALIZER;
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     szind_t szind = sz_size2index(usize);
     size_t mapped_add;
     bool commit = true;
     extent_t *extent = extents_alloc(tsdn, arena, &extent_hooks,
         &arena->extents_dirty, NULL, usize, sz_large_pad, alignment, false,
         szind, zero, &commit);
     if (extent == NULL && arena_may_have_muzzy(arena)) {
         extent = extents_alloc(tsdn, arena, &extent_hooks,
             &arena->extents_muzzy, NULL, usize, sz_large_pad, alignment,
             false, szind, zero, &commit);
     }
     size_t size = usize + sz_large_pad;
     if (extent == NULL) {
         extent = extent_alloc_wrapper(tsdn, arena, &extent_hooks, NULL,
             usize, sz_large_pad, alignment, false, szind, zero,
             &commit);
         if (config_stats) {
             /*
              * extent may be NULL on OOM, but in that case
              * mapped_add isn't used below, so there's no need to
              * conditionlly set it to 0 here.
              */
             mapped_add = size;
         }
     } else if (config_stats) {
         mapped_add = 0;
     }
     if (extent != NULL) {
         if (config_stats) {
             arena_stats_lock(tsdn, &arena->stats);
             arena_large_malloc_stats_update(tsdn, arena, usize);
             if (mapped_add != 0) {
                 arena_stats_add_zu(tsdn, &arena->stats,
                     &arena->stats.mapped, mapped_add);
             }
             arena_stats_unlock(tsdn, &arena->stats);
         }
         arena_nactive_add(arena, size >> LG_PAGE);
     }
     return extent;
 }
References arena, arena_large_malloc_stats_update(), arena_may_have_muzzy(), arena_nactive_add(), arena_stats_add_zu(), arena_stats_lock(), arena_stats_unlock(), config_stats, extent_alloc_wrapper, EXTENT_HOOKS_INITIALIZER, extents_alloc, arena_s::extents_dirty, arena_s::extents_muzzy, LG_PAGE, arena_stats_s::mapped, NULL, arena_s::stats, sz_large_pad, sz_size2index(), witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
arena_extent_dalloc_large_prep()
void arena_extent_dalloc_large_prep (tsdn_t * tsdn, arena_t * arena, extent_t * extent)
Definition at line 480 of file arena.c.
{
     if (config_stats) {
         arena_stats_lock(tsdn, &arena->stats);
         arena_large_dalloc_stats_update(tsdn, arena,
             extent_usize_get(extent));
         arena_stats_unlock(tsdn, &arena->stats);
     }
     arena_nactive_sub(arena, extent_size_get(extent) >> LG_PAGE);
 }
References arena, arena_large_dalloc_stats_update(), arena_nactive_sub(), arena_stats_lock(), arena_stats_unlock(), config_stats, extent_size_get(), extent_usize_get(), LG_PAGE, and arena_s::stats.
arena_extent_ralloc_large_expand()
void arena_extent_ralloc_large_expand (tsdn_t * tsdn, arena_t * arena, extent_t * extent, size_t oldsize)
Definition at line 505 of file arena.c.
                      {
     size_t usize = extent_usize_get(extent);
     size_t udiff = usize - oldusize;
     if (config_stats) {
         arena_stats_lock(tsdn, &arena->stats);
         arena_large_ralloc_stats_update(tsdn, arena, oldusize, usize);
         arena_stats_unlock(tsdn, &arena->stats);
     }
     arena_nactive_add(arena, udiff >> LG_PAGE);
 }
References arena, arena_large_ralloc_stats_update(), arena_nactive_add(), arena_stats_lock(), arena_stats_unlock(), config_stats, extent_usize_get(), LG_PAGE, and arena_s::stats.
arena_extent_ralloc_large_shrink()
void arena_extent_ralloc_large_shrink (tsdn_t * tsdn, arena_t * arena, extent_t * extent, size_t oldsize)
Definition at line 491 of file arena.c.
                      {
     size_t usize = extent_usize_get(extent);
     size_t udiff = oldusize - usize;
     if (config_stats) {
         arena_stats_lock(tsdn, &arena->stats);
         arena_large_ralloc_stats_update(tsdn, arena, oldusize, usize);
         arena_stats_unlock(tsdn, &arena->stats);
     }
     arena_nactive_sub(arena, udiff >> LG_PAGE);
 }
References arena, arena_large_ralloc_stats_update(), arena_nactive_sub(), arena_stats_lock(), arena_stats_unlock(), config_stats, extent_usize_get(), LG_PAGE, and arena_s::stats.
arena_extent_sn_next()
size_t arena_extent_sn_next (arena_t * arena)
Definition at line 1937 of file arena.c.
{
     return atomic_fetch_add_zu(&arena->extent_sn_next, 1, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, and arena_s::extent_sn_next.
arena_extents_dirty_dalloc()
void arena_extents_dirty_dalloc (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent)
Definition at line 256 of file arena.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extents_dalloc(tsdn, arena, r_extent_hooks, &arena->extents_dirty,
         extent);
     if (arena_dirty_decay_ms_get(arena) == 0) {
         arena_decay_dirty(tsdn, arena, false, true);
     } else {
         arena_background_thread_inactivity_check(tsdn, arena, false);
     }
 }
References arena, arena_background_thread_inactivity_check(), arena_decay_dirty(), arena_dirty_decay_ms_get(), extents_dalloc, arena_s::extents_dirty, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by arena_slab_dalloc().
arena_init_huge()
bool arena_init_huge (void)
Definition at line 2143 of file arena.c.
                       {
     bool huge_enabled;
     /* The threshold should be large size class. */
     if (opt_oversize_threshold > SC_LARGE_MAXCLASS ||
         opt_oversize_threshold < SC_LARGE_MINCLASS) {
         opt_oversize_threshold = 0;
         oversize_threshold = SC_LARGE_MAXCLASS + PAGE;
         huge_enabled = false;
     } else {
         /* Reserve the index for the huge arena. */
         huge_arena_ind = narenas_total_get();
         oversize_threshold = opt_oversize_threshold;
         huge_enabled = true;
     }
     return huge_enabled;
 }
References huge_arena_ind, narenas_total_get, opt_oversize_threshold, oversize_threshold, PAGE, SC_LARGE_MAXCLASS, and SC_LARGE_MINCLASS.
arena_is_huge()
bool arena_is_huge (unsigned arena_ind)
Definition at line 2163 of file arena.c.
{
     if (huge_arena_ind == 0) {
         return false;
     }
     return (arena_ind == huge_arena_ind);
 }
References huge_arena_ind.
arena_malloc_hard()
void* arena_malloc_hard (tsdn_t * tsdn, arena_t * arena, size_t size, szind_t ind, bool zero)
Definition at line 1514 of file arena.c.
                {
     assert(!tsdn_null(tsdn) || arena != NULL);
     if (likely(!tsdn_null(tsdn))) {
         arena = arena_choose_maybe_huge(tsdn_tsd(tsdn), arena, size);
     }
     if (unlikely(arena == NULL)) {
         return NULL;
     }
     if (likely(size <= SC_SMALL_MAXCLASS)) {
         return arena_malloc_small(tsdn, arena, ind, zero);
     }
     return large_malloc(tsdn, arena, sz_index2size(ind), zero);
 }
References arena, arena_choose_maybe_huge(), arena_malloc_small(), assert(), large_malloc, likely, NULL, SC_SMALL_MAXCLASS, sz_index2size(), tsdn_null(), tsdn_tsd(), unlikely, and G3D::zero().
arena_muzzy_decay_ms_default_get()
ssize_t arena_muzzy_decay_ms_default_get (void)
Definition at line 1882 of file arena.c.
{
     return atomic_load_zd(&muzzy_decay_ms_default, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and muzzy_decay_ms_default.
Referenced by arena_choose_huge(), and arena_new().
arena_muzzy_decay_ms_default_set()
bool arena_muzzy_decay_ms_default_set (ssize_t decay_ms)
Definition at line 1887 of file arena.c.
{
     if (!arena_decay_ms_valid(decay_ms)) {
         return true;
     }
     atomic_store_zd(&muzzy_decay_ms_default, decay_ms, ATOMIC_RELAXED);
     return false;
 }
References arena_decay_ms_valid(), ATOMIC_RELAXED, and muzzy_decay_ms_default.
Referenced by arena_boot().
arena_muzzy_decay_ms_get()
ssize_t arena_muzzy_decay_ms_get (arena_t * arena)
Definition at line 782 of file arena.c.
{
     return arena_decay_ms_get(&arena->decay_muzzy);
 }
References arena, arena_decay_ms_get(), and arena_s::decay_muzzy.
Referenced by arena_basic_stats_merge(), arena_decay_stashed(), and arena_may_have_muzzy().
arena_muzzy_decay_ms_set()
bool arena_muzzy_decay_ms_set (tsdn_t * tsdn, arena_t * arena, ssize_t decay_ms)
Definition at line 817 of file arena.c.
                       {
     return arena_decay_ms_set(tsdn, arena, &arena->decay_muzzy,
         &arena->extents_muzzy, decay_ms);
 }
References arena, arena_decay_ms_set(), arena_s::decay_muzzy, and arena_s::extents_muzzy.
Referenced by arena_choose_huge().
arena_new()
arena_t* arena_new (tsdn_t * tsdn, unsigned ind, extent_hooks_t * extent_hooks)
Definition at line 1942 of file arena.c.
{
     arena_t *arena;
     base_t *base;
     unsigned i;
     if (ind == 0) {
         base = b0get();
     } else {
         base = base_new(tsdn, ind, extent_hooks);
         if (base == NULL) {
             return NULL;
         }
     }
     unsigned nbins_total = 0;
     for (i = 0; i < SC_NBINS; i++) {
         nbins_total += bin_infos[i].n_shards;
     }
     size_t arena_size = sizeof(arena_t) + sizeof(bin_t) * nbins_total;
     arena = (arena_t *)base_alloc(tsdn, base, arena_size, CACHELINE);
     if (arena == NULL) {
         goto label_error;
     }
     atomic_store_u(&arena->nthreads[0], 0, ATOMIC_RELAXED);
     atomic_store_u(&arena->nthreads[1], 0, ATOMIC_RELAXED);
     arena->last_thd = NULL;
     if (config_stats) {
         if (arena_stats_init(tsdn, &arena->stats)) {
             goto label_error;
         }
         ql_new(&arena->tcache_ql);
         ql_new(&arena->cache_bin_array_descriptor_ql);
         if (malloc_mutex_init(&arena->tcache_ql_mtx, "tcache_ql",
             WITNESS_RANK_TCACHE_QL, malloc_mutex_rank_exclusive)) {
             goto label_error;
         }
     }
     if (config_prof) {
         if (prof_accum_init(tsdn, &arena->prof_accum)) {
             goto label_error;
         }
     }
     if (config_cache_oblivious) {
         /*
          * A nondeterministic seed based on the address of arena reduces
          * the likelihood of lockstep non-uniform cache index
          * utilization among identical concurrent processes, but at the
          * cost of test repeatability.  For debug builds, instead use a
          * deterministic seed.
          */
         atomic_store_zu(&arena->offset_state, config_debug ? ind :
             (size_t)(uintptr_t)arena, ATOMIC_RELAXED);
     }
     atomic_store_zu(&arena->extent_sn_next, 0, ATOMIC_RELAXED);
     atomic_store_u(&arena->dss_prec, (unsigned)extent_dss_prec_get(),
         ATOMIC_RELAXED);
     atomic_store_zu(&arena->nactive, 0, ATOMIC_RELAXED);
     extent_list_init(&arena->large);
     if (malloc_mutex_init(&arena->large_mtx, "arena_large",
         WITNESS_RANK_ARENA_LARGE, malloc_mutex_rank_exclusive)) {
         goto label_error;
     }
     /*
      * Delay coalescing for dirty extents despite the disruptive effect on
      * memory layout for best-fit extent allocation, since cached extents
      * are likely to be reused soon after deallocation, and the cost of
      * merging/splitting extents is non-trivial.
      */
     if (extents_init(tsdn, &arena->extents_dirty, extent_state_dirty,
         true)) {
         goto label_error;
     }
     /*
      * Coalesce muzzy extents immediately, because operations on them are in
      * the critical path much less often than for dirty extents.
      */
     if (extents_init(tsdn, &arena->extents_muzzy, extent_state_muzzy,
         false)) {
         goto label_error;
     }
     /*
      * Coalesce retained extents immediately, in part because they will
      * never be evicted (and therefore there's no opportunity for delayed
      * coalescing), but also because operations on retained extents are not
      * in the critical path.
      */
     if (extents_init(tsdn, &arena->extents_retained, extent_state_retained,
         false)) {
         goto label_error;
     }
     if (arena_decay_init(&arena->decay_dirty,
         arena_dirty_decay_ms_default_get(), &arena->stats.decay_dirty)) {
         goto label_error;
     }
     if (arena_decay_init(&arena->decay_muzzy,
         arena_muzzy_decay_ms_default_get(), &arena->stats.decay_muzzy)) {
         goto label_error;
     }
     arena->extent_grow_next = sz_psz2ind(HUGEPAGE);
     arena->retain_grow_limit = sz_psz2ind(SC_LARGE_MAXCLASS);
     if (malloc_mutex_init(&arena->extent_grow_mtx, "extent_grow",
         WITNESS_RANK_EXTENT_GROW, malloc_mutex_rank_exclusive)) {
         goto label_error;
     }
     extent_avail_new(&arena->extent_avail);
     if (malloc_mutex_init(&arena->extent_avail_mtx, "extent_avail",
         WITNESS_RANK_EXTENT_AVAIL, malloc_mutex_rank_exclusive)) {
         goto label_error;
     }
     /* Initialize bins. */
     uintptr_t bin_addr = (uintptr_t)arena + sizeof(arena_t);
     atomic_store_u(&arena->binshard_next, 0, ATOMIC_RELEASE);
     for (i = 0; i < SC_NBINS; i++) {
         unsigned nshards = bin_infos[i].n_shards;
         arena->bins[i].bin_shards = (bin_t *)bin_addr;
         bin_addr += nshards * sizeof(bin_t);
         for (unsigned j = 0; j < nshards; j++) {
             bool err = bin_init(&arena->bins[i].bin_shards[j]);
             if (err) {
                 goto label_error;
             }
         }
     }
     assert(bin_addr == (uintptr_t)arena + arena_size);
     arena->base = base;
     /* Set arena before creating background threads. */
     arena_set(ind, arena);
     nstime_init(&arena->create_time, 0);
     nstime_update(&arena->create_time);
     /* We don't support reentrancy for arena 0 bootstrapping. */
     if (ind != 0) {
         /*
          * If we're here, then arena 0 already exists, so bootstrapping
          * is done enough that we should have tsd.
          */
         assert(!tsdn_null(tsdn));
         pre_reentrancy(tsdn_tsd(tsdn), arena);
         if (test_hooks_arena_new_hook) {
             test_hooks_arena_new_hook();
         }
         post_reentrancy(tsdn_tsd(tsdn));
     }
     return arena;
 label_error:
     if (ind != 0) {
         base_delete(tsdn, base);
     }
     return NULL;
 }
References arena, arena_decay_init(), arena_dirty_decay_ms_default_get(), arena_muzzy_decay_ms_default_get(), arena_set, arena_stats_init(), assert(), ATOMIC_RELAXED, ATOMIC_RELEASE, b0get, arena_s::base, base_alloc, base_delete, base_new, bin_infos, bin_init, bins_s::bin_shards, arena_s::bins, arena_s::binshard_next, CACHELINE, config_cache_oblivious, config_debug, config_prof, config_stats, arena_s::create_time, arena_stats_s::decay_dirty, arena_s::decay_dirty, arena_stats_s::decay_muzzy, arena_s::decay_muzzy, arena_s::dss_prec, arena_s::extent_avail, arena_s::extent_avail_mtx, extent_avail_new, extent_dss_prec_get, arena_s::extent_grow_mtx, arena_s::extent_grow_next, extent_list_init(), arena_s::extent_sn_next, extent_state_dirty, extent_state_muzzy, extent_state_retained, arena_s::extents_dirty, extents_init(), arena_s::extents_muzzy, arena_s::extents_retained, HUGEPAGE, arena_s::large, arena_s::large_mtx, arena_s::last_thd, malloc_mutex_init, malloc_mutex_rank_exclusive, arena_s::nactive, nstime_init, nstime_update, arena_s::nthreads, NULL, arena_s::offset_state, post_reentrancy(), pre_reentrancy(), arena_s::prof_accum, prof_accum_init, ql_new, arena_s::retain_grow_limit, SC_LARGE_MAXCLASS, SC_NBINS, arena_s::stats, sz_psz2ind(), arena_s::tcache_ql_mtx, test_hooks_arena_new_hook, tsdn_null(), tsdn_tsd(), uintptr_t, WITNESS_RANK_ARENA_LARGE, WITNESS_RANK_EXTENT_AVAIL, WITNESS_RANK_EXTENT_GROW, and WITNESS_RANK_TCACHE_QL.
arena_nthreads_dec()
void arena_nthreads_dec (arena_t * arena, bool internal)
Definition at line 1932 of file arena.c.
{
     atomic_fetch_sub_u(&arena->nthreads[internal], 1, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, and arena_s::nthreads.
arena_nthreads_get()
unsigned arena_nthreads_get (arena_t * arena, bool internal)
Definition at line 1922 of file arena.c.
{
     return atomic_load_u(&arena->nthreads[internal], ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, and arena_s::nthreads.
Referenced by arena_basic_stats_merge(), and arena_destroy().
arena_nthreads_inc()
void arena_nthreads_inc (arena_t * arena, bool internal)
Definition at line 1927 of file arena.c.
{
     atomic_fetch_add_u(&arena->nthreads[internal], 1, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, and arena_s::nthreads.
Referenced by arena_postfork_child().
arena_palloc()
void* arena_palloc (tsdn_t * tsdn, arena_t * arena, size_t usize, size_t alignment, bool zero, tcache_t * tcache)
Definition at line 1532 of file arena.c.
{
     void *ret;
     if (usize <= SC_SMALL_MAXCLASS
         && (alignment < PAGE
         || (alignment == PAGE && (usize & PAGE_MASK) == 0))) {
         /* Small; alignment doesn't require special slab placement. */
         ret = arena_malloc(tsdn, arena, usize, sz_size2index(usize),
             zero, tcache, true);
     } else {
         if (likely(alignment <= CACHELINE)) {
             ret = large_malloc(tsdn, arena, usize, zero);
         } else {
             ret = large_palloc(tsdn, arena, usize, alignment, zero);
         }
     }
     return ret;
 }
References arena, arena_malloc(), CACHELINE, large_malloc, large_palloc, likely, PAGE, PAGE_MASK, ret, SC_SMALL_MAXCLASS, sz_size2index(), and G3D::zero().
arena_postfork_child()
void arena_postfork_child (tsdn_t * tsdn, arena_t * arena)
Definition at line 2255 of file arena.c.
{
     unsigned i;
     atomic_store_u(&arena->nthreads[0], 0, ATOMIC_RELAXED);
     atomic_store_u(&arena->nthreads[1], 0, ATOMIC_RELAXED);
     if (tsd_arena_get(tsdn_tsd(tsdn)) == arena) {
         arena_nthreads_inc(arena, false);
     }
     if (tsd_iarena_get(tsdn_tsd(tsdn)) == arena) {
         arena_nthreads_inc(arena, true);
     }
     if (config_stats) {
         ql_new(&arena->tcache_ql);
         ql_new(&arena->cache_bin_array_descriptor_ql);
         tcache_t *tcache = tcache_get(tsdn_tsd(tsdn));
         if (tcache != NULL && tcache->arena == arena) {
             ql_elm_new(tcache, link);
             ql_tail_insert(&arena->tcache_ql, tcache, link);
             cache_bin_array_descriptor_init(
                 &tcache->cache_bin_array_descriptor,
                 tcache->bins_small, tcache->bins_large);
             ql_tail_insert(&arena->cache_bin_array_descriptor_ql,
                 &tcache->cache_bin_array_descriptor, link);
         }
     }
     for (i = 0; i < SC_NBINS; i++) {
         for (unsigned j = 0; j < bin_infos[i].n_shards; j++) {
             bin_postfork_child(tsdn, &arena->bins[i].bin_shards[j]);
         }
     }
     malloc_mutex_postfork_child(tsdn, &arena->large_mtx);
     base_postfork_child(tsdn, arena->base);
     malloc_mutex_postfork_child(tsdn, &arena->extent_avail_mtx);
     extents_postfork_child(tsdn, &arena->extents_dirty);
     extents_postfork_child(tsdn, &arena->extents_muzzy);
     extents_postfork_child(tsdn, &arena->extents_retained);
     malloc_mutex_postfork_child(tsdn, &arena->extent_grow_mtx);
     malloc_mutex_postfork_child(tsdn, &arena->decay_dirty.mtx);
     malloc_mutex_postfork_child(tsdn, &arena->decay_muzzy.mtx);
     if (config_stats) {
         malloc_mutex_postfork_child(tsdn, &arena->tcache_ql_mtx);
     }
 }
References tcache_s::arena, arena, arena_nthreads_inc(), ATOMIC_RELAXED, arena_s::base, base_postfork_child, bin_infos, bin_postfork_child, bins_s::bin_shards, arena_s::bins, tcache_s::bins_large, tcache_s::bins_small, tcache_s::cache_bin_array_descriptor, cache_bin_array_descriptor_init(), config_stats, arena_s::decay_dirty, arena_s::decay_muzzy, arena_s::extent_avail_mtx, arena_s::extent_grow_mtx, arena_s::extents_dirty, arena_s::extents_muzzy, extents_postfork_child, arena_s::extents_retained, arena_s::large_mtx, malloc_mutex_postfork_child, arena_decay_s::mtx, arena_s::nthreads, NULL, ql_elm_new, ql_new, ql_tail_insert, SC_NBINS, tcache_get(), arena_s::tcache_ql_mtx, and tsdn_tsd().
arena_postfork_parent()
void arena_postfork_parent (tsdn_t * tsdn, arena_t * arena)
Definition at line 2231 of file arena.c.
{
     unsigned i;
     for (i = 0; i < SC_NBINS; i++) {
         for (unsigned j = 0; j < bin_infos[i].n_shards; j++) {
             bin_postfork_parent(tsdn,
                 &arena->bins[i].bin_shards[j]);
         }
     }
     malloc_mutex_postfork_parent(tsdn, &arena->large_mtx);
     base_postfork_parent(tsdn, arena->base);
     malloc_mutex_postfork_parent(tsdn, &arena->extent_avail_mtx);
     extents_postfork_parent(tsdn, &arena->extents_dirty);
     extents_postfork_parent(tsdn, &arena->extents_muzzy);
     extents_postfork_parent(tsdn, &arena->extents_retained);
     malloc_mutex_postfork_parent(tsdn, &arena->extent_grow_mtx);
     malloc_mutex_postfork_parent(tsdn, &arena->decay_dirty.mtx);
     malloc_mutex_postfork_parent(tsdn, &arena->decay_muzzy.mtx);
     if (config_stats) {
         malloc_mutex_postfork_parent(tsdn, &arena->tcache_ql_mtx);
     }
 }
References arena, arena_s::base, base_postfork_parent, bin_infos, bin_postfork_parent, bins_s::bin_shards, arena_s::bins, config_stats, arena_s::decay_dirty, arena_s::decay_muzzy, arena_s::extent_avail_mtx, arena_s::extent_grow_mtx, arena_s::extents_dirty, arena_s::extents_muzzy, extents_postfork_parent, arena_s::extents_retained, arena_s::large_mtx, malloc_mutex_postfork_parent, arena_decay_s::mtx, SC_NBINS, and arena_s::tcache_ql_mtx.
arena_prefork0()
void arena_prefork0 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2182 of file arena.c.
{
     malloc_mutex_prefork(tsdn, &arena->decay_dirty.mtx);
     malloc_mutex_prefork(tsdn, &arena->decay_muzzy.mtx);
 }
References arena, arena_s::decay_dirty, arena_s::decay_muzzy, malloc_mutex_prefork, and arena_decay_s::mtx.
arena_prefork1()
void arena_prefork1 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2188 of file arena.c.
{
     if (config_stats) {
         malloc_mutex_prefork(tsdn, &arena->tcache_ql_mtx);
     }
 }
References arena, config_stats, malloc_mutex_prefork, and arena_s::tcache_ql_mtx.
arena_prefork2()
void arena_prefork2 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2195 of file arena.c.
{
     malloc_mutex_prefork(tsdn, &arena->extent_grow_mtx);
 }
References arena, arena_s::extent_grow_mtx, and malloc_mutex_prefork.
arena_prefork3()
void arena_prefork3 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2200 of file arena.c.
{
     extents_prefork(tsdn, &arena->extents_dirty);
     extents_prefork(tsdn, &arena->extents_muzzy);
     extents_prefork(tsdn, &arena->extents_retained);
 }
References arena, arena_s::extents_dirty, arena_s::extents_muzzy, extents_prefork, and arena_s::extents_retained.
arena_prefork4()
void arena_prefork4 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2207 of file arena.c.
{
     malloc_mutex_prefork(tsdn, &arena->extent_avail_mtx);
 }
References arena, arena_s::extent_avail_mtx, and malloc_mutex_prefork.
arena_prefork5()
void arena_prefork5 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2212 of file arena.c.
{
     base_prefork(tsdn, arena->base);
 }
References arena, arena_s::base, and base_prefork.
arena_prefork6()
void arena_prefork6 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2217 of file arena.c.
{
     malloc_mutex_prefork(tsdn, &arena->large_mtx);
 }
References arena, arena_s::large_mtx, and malloc_mutex_prefork.
arena_prefork7()
void arena_prefork7 (tsdn_t * tsdn, arena_t * arena)
Definition at line 2222 of file arena.c.
{
     for (unsigned i = 0; i < SC_NBINS; i++) {
         for (unsigned j = 0; j < bin_infos[i].n_shards; j++) {
             bin_prefork(tsdn, &arena->bins[i].bin_shards[j]);
         }
     }
 }
References arena, bin_infos, bin_prefork, bins_s::bin_shards, arena_s::bins, and SC_NBINS.
arena_prof_promote()
void arena_prof_promote (tsdn_t * tsdn, void * ptr, size_t usize)
Definition at line 1553 of file arena.c.
{
     cassert(config_prof);
     assert(ptr != NULL);
     assert(isalloc(tsdn, ptr) == SC_LARGE_MINCLASS);
     assert(usize <= SC_SMALL_MAXCLASS);
     if (config_opt_safety_checks) {
         safety_check_set_redzone(ptr, usize, SC_LARGE_MINCLASS);
     }
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     extent_t *extent = rtree_extent_read(tsdn, &extents_rtree, rtree_ctx,
         (uintptr_t)ptr, true);
     arena_t *arena = extent_arena_get(extent);
     szind_t szind = sz_size2index(usize);
     extent_szind_set(extent, szind);
     rtree_szind_slab_update(tsdn, &extents_rtree, rtree_ctx, (uintptr_t)ptr,
         szind, false);
     prof_accum_cancel(tsdn, &arena->prof_accum, usize);
     assert(isalloc(tsdn, ptr) == usize);
 }
References arena, assert(), cassert(), config_opt_safety_checks, config_prof, extent_arena_get(), extent_szind_set(), extents_rtree, isalloc(), NULL, arena_s::prof_accum, prof_accum_cancel(), ptr(), rtree_extent_read(), rtree_szind_slab_update(), safety_check_set_redzone(), SC_LARGE_MINCLASS, SC_SMALL_MAXCLASS, sz_size2index(), and tsdn_rtree_ctx().
arena_ralloc()
void* arena_ralloc (tsdn_t * tsdn, arena_t * arena, void * ptr, size_t oldsize, size_t size, size_t alignment, bool zero, tcache_t * tcache, hook_ralloc_args_t * hook_args)
Definition at line 1800 of file arena.c.
{
     size_t usize = sz_s2u(size);
     if (unlikely(usize == 0 || size > SC_LARGE_MAXCLASS)) {
         return NULL;
     }
     if (likely(usize <= SC_SMALL_MAXCLASS)) {
         /* Try to avoid moving the allocation. */
         UNUSED size_t newsize;
         if (!arena_ralloc_no_move(tsdn, ptr, oldsize, usize, 0, zero,
             &newsize)) {
             hook_invoke_expand(hook_args->is_realloc
                 ? hook_expand_realloc : hook_expand_rallocx,
                 ptr, oldsize, usize, (uintptr_t)ptr,
                 hook_args->args);
             return ptr;
         }
     }
     if (oldsize >= SC_LARGE_MINCLASS
         && usize >= SC_LARGE_MINCLASS) {
         return large_ralloc(tsdn, arena, ptr, usize,
             alignment, zero, tcache, hook_args);
     }
     /*
      * size and oldsize are different enough that we need to move the
      * object.  In that case, fall back to allocating new space and copying.
      */
     void *ret = arena_ralloc_move_helper(tsdn, arena, usize, alignment,
         zero, tcache);
     if (ret == NULL) {
         return NULL;
     }
     hook_invoke_alloc(hook_args->is_realloc
         ? hook_alloc_realloc : hook_alloc_rallocx, ret, (uintptr_t)ret,
         hook_args->args);
     hook_invoke_dalloc(hook_args->is_realloc
         ? hook_dalloc_realloc : hook_dalloc_rallocx, ptr, hook_args->args);
     /*
      * Junk/zero-filling were already done by
      * ipalloc()/arena_malloc().
      */
     size_t copysize = (usize < oldsize) ? usize : oldsize;
     memcpy(ret, ptr, copysize);
     isdalloct(tsdn, ptr, oldsize, tcache, NULL, true);
     return ret;
 }
References arena, arena_ralloc_move_helper(), arena_ralloc_no_move(), hook_ralloc_args_s::args, hook_alloc_rallocx, hook_alloc_realloc, hook_dalloc_rallocx, hook_dalloc_realloc, hook_expand_rallocx, hook_expand_realloc, hook_invoke_alloc, hook_invoke_dalloc, hook_invoke_expand, hook_ralloc_args_s::is_realloc, isdalloct(), large_ralloc, likely, memcpy, NULL, ptr(), ret, SC_LARGE_MAXCLASS, SC_LARGE_MINCLASS, SC_SMALL_MAXCLASS, sz_s2u(), unlikely, UNUSED, and G3D::zero().
arena_ralloc_no_move()
bool arena_ralloc_no_move (tsdn_t * tsdn, void * ptr, size_t oldsize, size_t size, size_t extra, bool zero, size_t * newsize)
Definition at line 1740 of file arena.c.
{
     bool ret;
     /* Calls with non-zero extra had to clamp extra. */
     assert(extra == 0 || size + extra <= SC_LARGE_MAXCLASS);
     extent_t *extent = iealloc(tsdn, ptr);
     if (unlikely(size > SC_LARGE_MAXCLASS)) {
         ret = true;
         goto done;
     }
     size_t usize_min = sz_s2u(size);
     size_t usize_max = sz_s2u(size + extra);
     if (likely(oldsize <= SC_SMALL_MAXCLASS && usize_min
         <= SC_SMALL_MAXCLASS)) {
         /*
          * Avoid moving the allocation if the size class can be left the
          * same.
          */
         assert(bin_infos[sz_size2index(oldsize)].reg_size ==
             oldsize);
         if ((usize_max > SC_SMALL_MAXCLASS
             || sz_size2index(usize_max) != sz_size2index(oldsize))
             && (size > oldsize || usize_max < oldsize)) {
             ret = true;
             goto done;
         }
         arena_decay_tick(tsdn, extent_arena_get(extent));
         ret = false;
     } else if (oldsize >= SC_LARGE_MINCLASS
         && usize_max >= SC_LARGE_MINCLASS) {
         ret = large_ralloc_no_move(tsdn, extent, usize_min, usize_max,
             zero);
     } else {
         ret = true;
     }
 done:
     assert(extent == iealloc(tsdn, ptr));
     *newsize = extent_usize_get(extent);
     return ret;
 }
References arena_decay_tick(), assert(), bin_infos, detail::digits::done, extent_arena_get(), extent_usize_get(), iealloc(), large_ralloc_no_move, likely, ptr(), ret, SC_LARGE_MAXCLASS, SC_LARGE_MINCLASS, SC_SMALL_MAXCLASS, sz_s2u(), sz_size2index(), unlikely, and G3D::zero().
Referenced by arena_ralloc().
arena_reset()
void arena_reset (tsd_t * tsd, arena_t * arena)
Definition at line 1096 of file arena.c.
{
     /*
      * Locking in this function is unintuitive.  The caller guarantees that
      * no concurrent operations are happening in this arena, but there are
      * still reasons that some locking is necessary:
      *
      * - Some of the functions in the transitive closure of calls assume
      *   appropriate locks are held, and in some cases these locks are
      *   temporarily dropped to avoid lock order reversal or deadlock due to
      *   reentry.
      * - mallctl("epoch", ...) may concurrently refresh stats.  While
      *   strictly speaking this is a "concurrent operation", disallowing
      *   stats refreshes would impose an inconvenient burden.
      */
     /* Large allocations. */
     malloc_mutex_lock(tsd_tsdn(tsd), &arena->large_mtx);
     for (extent_t *extent = extent_list_first(&arena->large); extent !=
         NULL; extent = extent_list_first(&arena->large)) {
         void *ptr = extent_base_get(extent);
         size_t usize;
         malloc_mutex_unlock(tsd_tsdn(tsd), &arena->large_mtx);
         alloc_ctx_t alloc_ctx;
         rtree_ctx_t *rtree_ctx = tsd_rtree_ctx(tsd);
         rtree_szind_slab_read(tsd_tsdn(tsd), &extents_rtree, rtree_ctx,
             (uintptr_t)ptr, true, &alloc_ctx.szind, &alloc_ctx.slab);
         assert(alloc_ctx.szind != SC_NSIZES);
         if (config_stats || (config_prof && opt_prof)) {
             usize = sz_index2size(alloc_ctx.szind);
             assert(usize == isalloc(tsd_tsdn(tsd), ptr));
         }
         /* Remove large allocation from prof sample set. */
         if (config_prof && opt_prof) {
             prof_free(tsd, ptr, usize, &alloc_ctx);
         }
         large_dalloc(tsd_tsdn(tsd), extent);
         malloc_mutex_lock(tsd_tsdn(tsd), &arena->large_mtx);
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), &arena->large_mtx);
     /* Bins. */
     for (unsigned i = 0; i < SC_NBINS; i++) {
         for (unsigned j = 0; j < bin_infos[i].n_shards; j++) {
             arena_bin_reset(tsd, arena,
                 &arena->bins[i].bin_shards[j]);
         }
     }
     atomic_store_zu(&arena->nactive, 0, ATOMIC_RELAXED);
 }
References arena, arena_bin_reset(), assert(), ATOMIC_RELAXED, bin_infos, bins_s::bin_shards, arena_s::bins, config_prof, config_stats, extent_base_get(), extent_list_first(), extents_rtree, isalloc(), arena_s::large, large_dalloc, arena_s::large_mtx, malloc_mutex_lock(), malloc_mutex_unlock(), arena_s::nactive, NULL, opt_prof, prof_free(), ptr(), rtree_szind_slab_read(), SC_NBINS, SC_NSIZES, alloc_ctx_s::slab, sz_index2size(), alloc_ctx_s::szind, tsd_rtree_ctx(), and tsd_tsdn().
arena_retain_grow_limit_get_set()
bool arena_retain_grow_limit_get_set (tsd_t * tsd, arena_t * arena, size_t * old_limit, size_t * new_limit)
Definition at line 1896 of file arena.c.
{
     assert(opt_retain);
     pszind_t new_ind JEMALLOC_CC_SILENCE_INIT(0);
     if (new_limit != NULL) {
         size_t limit = *new_limit;
         /* Grow no more than the new limit. */
         if ((new_ind = sz_psz2ind(limit + 1) - 1) >= SC_NPSIZES) {
             return true;
         }
     }
     malloc_mutex_lock(tsd_tsdn(tsd), &arena->extent_grow_mtx);
     if (old_limit != NULL) {
         *old_limit = sz_pind2sz(arena->retain_grow_limit);
     }
     if (new_limit != NULL) {
         arena->retain_grow_limit = new_ind;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), &arena->extent_grow_mtx);
     return false;
 }
References arena, assert(), arena_s::extent_grow_mtx, JEMALLOC_CC_SILENCE_INIT, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_retain, arena_s::retain_grow_limit, SC_NPSIZES, sz_pind2sz(), sz_psz2ind(), and tsd_tsdn().
arena_stats_merge()
void arena_stats_merge (tsdn_t * tsdn, arena_t * arena, unsigned * nthreads, const char ** dss, ssize_t * dirty_decay_ms, ssize_t * muzzy_decay_ms, size_t * nactive, size_t * ndirty, size_t * nmuzzy, arena_stats_t * astats, bin_stats_t * bstats, arena_stats_large_t * lstats, arena_stats_extents_t * estats)
Definition at line 83 of file arena.c.
{
     cassert(config_stats);
     arena_basic_stats_merge(tsdn, arena, nthreads, dss, dirty_decay_ms,
         muzzy_decay_ms, nactive, ndirty, nmuzzy);
     size_t base_allocated, base_resident, base_mapped, metadata_thp;
     base_stats_get(tsdn, arena->base, &base_allocated, &base_resident,
         &base_mapped, &metadata_thp);
     arena_stats_lock(tsdn, &arena->stats);
     arena_stats_accum_zu(&astats->mapped, base_mapped
         + arena_stats_read_zu(tsdn, &arena->stats, &arena->stats.mapped));
     arena_stats_accum_zu(&astats->retained,
         extents_npages_get(&arena->extents_retained) << LG_PAGE);
     atomic_store_zu(&astats->extent_avail,
         atomic_load_zu(&arena->extent_avail_cnt, ATOMIC_RELAXED),
         ATOMIC_RELAXED);
     arena_stats_accum_u64(&astats->decay_dirty.npurge,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_dirty.npurge));
     arena_stats_accum_u64(&astats->decay_dirty.nmadvise,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_dirty.nmadvise));
     arena_stats_accum_u64(&astats->decay_dirty.purged,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_dirty.purged));
     arena_stats_accum_u64(&astats->decay_muzzy.npurge,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_muzzy.npurge));
     arena_stats_accum_u64(&astats->decay_muzzy.nmadvise,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_muzzy.nmadvise));
     arena_stats_accum_u64(&astats->decay_muzzy.purged,
         arena_stats_read_u64(tsdn, &arena->stats,
         &arena->stats.decay_muzzy.purged));
     arena_stats_accum_zu(&astats->base, base_allocated);
     arena_stats_accum_zu(&astats->internal, arena_internal_get(arena));
     arena_stats_accum_zu(&astats->metadata_thp, metadata_thp);
     arena_stats_accum_zu(&astats->resident, base_resident +
         (((atomic_load_zu(&arena->nactive, ATOMIC_RELAXED) +
         extents_npages_get(&arena->extents_dirty) +
         extents_npages_get(&arena->extents_muzzy)) << LG_PAGE)));
     arena_stats_accum_zu(&astats->abandoned_vm, atomic_load_zu(
         &arena->stats.abandoned_vm, ATOMIC_RELAXED));
     for (szind_t i = 0; i < SC_NSIZES - SC_NBINS; i++) {
         uint64_t nmalloc = arena_stats_read_u64(tsdn, &arena->stats,
             &arena->stats.lstats[i].nmalloc);
         arena_stats_accum_u64(&lstats[i].nmalloc, nmalloc);
         arena_stats_accum_u64(&astats->nmalloc_large, nmalloc);
         uint64_t ndalloc = arena_stats_read_u64(tsdn, &arena->stats,
             &arena->stats.lstats[i].ndalloc);
         arena_stats_accum_u64(&lstats[i].ndalloc, ndalloc);
         arena_stats_accum_u64(&astats->ndalloc_large, ndalloc);
         uint64_t nrequests = arena_stats_read_u64(tsdn, &arena->stats,
             &arena->stats.lstats[i].nrequests);
         arena_stats_accum_u64(&lstats[i].nrequests,
             nmalloc + nrequests);
         arena_stats_accum_u64(&astats->nrequests_large,
             nmalloc + nrequests);
         /* nfill == nmalloc for large currently. */
         arena_stats_accum_u64(&lstats[i].nfills, nmalloc);
         arena_stats_accum_u64(&astats->nfills_large, nmalloc);
         uint64_t nflush = arena_stats_read_u64(tsdn, &arena->stats,
             &arena->stats.lstats[i].nflushes);
         arena_stats_accum_u64(&lstats[i].nflushes, nflush);
         arena_stats_accum_u64(&astats->nflushes_large, nflush);
         assert(nmalloc >= ndalloc);
         assert(nmalloc - ndalloc <= SIZE_T_MAX);
         size_t curlextents = (size_t)(nmalloc - ndalloc);
         lstats[i].curlextents += curlextents;
         arena_stats_accum_zu(&astats->allocated_large,
             curlextents * sz_index2size(SC_NBINS + i));
     }
     for (pszind_t i = 0; i < SC_NPSIZES; i++) {
         size_t dirty, muzzy, retained, dirty_bytes, muzzy_bytes,
             retained_bytes;
         dirty = extents_nextents_get(&arena->extents_dirty, i);
         muzzy = extents_nextents_get(&arena->extents_muzzy, i);
         retained = extents_nextents_get(&arena->extents_retained, i);
         dirty_bytes = extents_nbytes_get(&arena->extents_dirty, i);
         muzzy_bytes = extents_nbytes_get(&arena->extents_muzzy, i);
         retained_bytes =
             extents_nbytes_get(&arena->extents_retained, i);
         atomic_store_zu(&estats[i].ndirty, dirty, ATOMIC_RELAXED);
         atomic_store_zu(&estats[i].nmuzzy, muzzy, ATOMIC_RELAXED);
         atomic_store_zu(&estats[i].nretained, retained, ATOMIC_RELAXED);
         atomic_store_zu(&estats[i].dirty_bytes, dirty_bytes,
             ATOMIC_RELAXED);
         atomic_store_zu(&estats[i].muzzy_bytes, muzzy_bytes,
             ATOMIC_RELAXED);
         atomic_store_zu(&estats[i].retained_bytes, retained_bytes,
             ATOMIC_RELAXED);
     }
     arena_stats_unlock(tsdn, &arena->stats);
     /* tcache_bytes counts currently cached bytes. */
     atomic_store_zu(&astats->tcache_bytes, 0, ATOMIC_RELAXED);
     malloc_mutex_lock(tsdn, &arena->tcache_ql_mtx);
     cache_bin_array_descriptor_t *descriptor;
     ql_foreach(descriptor, &arena->cache_bin_array_descriptor_ql, link) {
         szind_t i = 0;
         for (; i < SC_NBINS; i++) {
             cache_bin_t *tbin = &descriptor->bins_small[i];
             arena_stats_accum_zu(&astats->tcache_bytes,
                 tbin->ncached * sz_index2size(i));
         }
         for (; i < nhbins; i++) {
             cache_bin_t *tbin = &descriptor->bins_large[i];
             arena_stats_accum_zu(&astats->tcache_bytes,
                 tbin->ncached * sz_index2size(i));
         }
     }
     malloc_mutex_prof_read(tsdn,
         &astats->mutex_prof_data[arena_prof_mutex_tcache_list],
         &arena->tcache_ql_mtx);
     malloc_mutex_unlock(tsdn, &arena->tcache_ql_mtx);
 #define READ_ARENA_MUTEX_PROF_DATA(mtx, ind)                \
     malloc_mutex_lock(tsdn, &arena->mtx);               \
     malloc_mutex_prof_read(tsdn, &astats->mutex_prof_data[ind],     \
         &arena->mtx);                           \
     malloc_mutex_unlock(tsdn, &arena->mtx);
     /* Gather per arena mutex profiling data. */
     READ_ARENA_MUTEX_PROF_DATA(large_mtx, arena_prof_mutex_large);
     READ_ARENA_MUTEX_PROF_DATA(extent_avail_mtx,
         arena_prof_mutex_extent_avail)
     READ_ARENA_MUTEX_PROF_DATA(extents_dirty.mtx,
         arena_prof_mutex_extents_dirty)
     READ_ARENA_MUTEX_PROF_DATA(extents_muzzy.mtx,
         arena_prof_mutex_extents_muzzy)
     READ_ARENA_MUTEX_PROF_DATA(extents_retained.mtx,
         arena_prof_mutex_extents_retained)
     READ_ARENA_MUTEX_PROF_DATA(decay_dirty.mtx,
         arena_prof_mutex_decay_dirty)
     READ_ARENA_MUTEX_PROF_DATA(decay_muzzy.mtx,
         arena_prof_mutex_decay_muzzy)
     READ_ARENA_MUTEX_PROF_DATA(base->mtx,
         arena_prof_mutex_base)
 #undef READ_ARENA_MUTEX_PROF_DATA
     nstime_copy(&astats->uptime, &arena->create_time);
     nstime_update(&astats->uptime);
     nstime_subtract(&astats->uptime, &arena->create_time);
     for (szind_t i = 0; i < SC_NBINS; i++) {
         for (unsigned j = 0; j < bin_infos[i].n_shards; j++) {
             bin_stats_merge(tsdn, &bstats[i],
                 &arena->bins[i].bin_shards[j]);
         }
     }
 }
References arena_stats_s::abandoned_vm, arena_stats_s::allocated_large, arena, arena_basic_stats_merge(), arena_internal_get(), arena_stats_accum_u64(), arena_stats_accum_zu(), arena_stats_lock(), arena_stats_read_u64(), arena_stats_read_zu(), arena_stats_unlock(), assert(), ATOMIC_RELAXED, arena_stats_s::base, arena_s::base, base_stats_get, bin_infos, bins_s::bin_shards, bin_stats_merge(), arena_s::bins, cache_bin_array_descriptor_s::bins_large, cache_bin_array_descriptor_s::bins_small, cassert(), config_stats, arena_s::create_time, arena_stats_large_s::curlextents, arena_stats_s::decay_dirty, arena_stats_s::decay_muzzy, arena_stats_s::extent_avail, arena_s::extent_avail_cnt, arena_s::extents_dirty, arena_s::extents_muzzy, extents_nbytes_get, extents_nextents_get, extents_npages_get, arena_s::extents_retained, arena_stats_s::internal, LG_PAGE, arena_stats_s::lstats, malloc_mutex_lock(), malloc_mutex_prof_read(), malloc_mutex_unlock(), arena_stats_s::mapped, arena_stats_s::metadata_thp, arena_stats_s::mutex_prof_data, arena_s::nactive, cache_bin_s::ncached, arena_stats_large_s::ndalloc, arena_stats_s::ndalloc_large, arena_stats_s::nfills_large, arena_stats_large_s::nflushes, arena_stats_s::nflushes_large, nhbins, arena_stats_decay_s::nmadvise, arena_stats_large_s::nmalloc, arena_stats_s::nmalloc_large, arena_stats_decay_s::npurge, arena_stats_large_s::nrequests, arena_stats_s::nrequests_large, nstime_copy, nstime_subtract, nstime_update, arena_stats_decay_s::purged, ql_foreach, READ_ARENA_MUTEX_PROF_DATA, arena_stats_s::resident, arena_stats_s::retained, SC_NBINS, SC_NPSIZES, SC_NSIZES, SIZE_T_MAX, arena_s::stats, sz_index2size(), arena_stats_s::tcache_bytes, arena_s::tcache_ql_mtx, and arena_stats_s::uptime.
arena_tcache_fill_small()
void arena_tcache_fill_small (tsdn_t * tsdn, arena_t * arena, tcache_t * tcache, cache_bin_t * tbin, szind_t binind, uint64_t prof_accumbytes)
Definition at line 1381 of file arena.c.
{
     unsigned i, nfill, cnt;
     assert(tbin->ncached == 0);
     if (config_prof && arena_prof_accum(tsdn, arena, prof_accumbytes)) {
         prof_idump(tsdn);
     }
     unsigned binshard;
     bin_t *bin = arena_bin_choose_lock(tsdn, arena, binind, &binshard);
     for (i = 0, nfill = (tcache_bin_info[binind].ncached_max >>
         tcache->lg_fill_div[binind]); i < nfill; i += cnt) {
         extent_t *slab;
         if ((slab = bin->slabcur) != NULL && extent_nfree_get(slab) >
             0) {
             unsigned tofill = nfill - i;
             cnt = tofill < extent_nfree_get(slab) ?
                 tofill : extent_nfree_get(slab);
             arena_slab_reg_alloc_batch(
                slab, &bin_infos[binind], cnt,
                tbin->avail - nfill + i);
         } else {
             cnt = 1;
             void *ptr = arena_bin_malloc_hard(tsdn, arena, bin,
                 binind, binshard);
             /*
              * OOM.  tbin->avail isn't yet filled down to its first
              * element, so the successful allocations (if any) must
              * be moved just before tbin->avail before bailing out.
              */
             if (ptr == NULL) {
                 if (i > 0) {
                     memmove(tbin->avail - i,
                         tbin->avail - nfill,
                         i * sizeof(void *));
                 }
                 break;
             }
             /* Insert such that low regions get used first. */
             *(tbin->avail - nfill + i) = ptr;
         }
         if (config_fill && unlikely(opt_junk_alloc)) {
             for (unsigned j = 0; j < cnt; j++) {
                 void* ptr = *(tbin->avail - nfill + i + j);
                 arena_alloc_junk_small(ptr, &bin_infos[binind],
                             true);
             }
         }
     }
     if (config_stats) {
         bin->stats.nmalloc += i;
         bin->stats.nrequests += tbin->tstats.nrequests;
         bin->stats.curregs += i;
         bin->stats.nfills++;
         tbin->tstats.nrequests = 0;
     }
     malloc_mutex_unlock(tsdn, &bin->lock);
     tbin->ncached = i;
     arena_decay_tick(tsdn, arena);
 }
References arena, arena_alloc_junk_small(), arena_bin_choose_lock(), arena_bin_malloc_hard(), arena_decay_tick(), arena_prof_accum(), arena_slab_reg_alloc_batch(), assert(), cache_bin_s::avail, bin_infos, config_fill, config_prof, config_stats, bin_stats_s::curregs, extent_nfree_get(), tcache_s::lg_fill_div, bin_s::lock, malloc_mutex_unlock(), memmove, cache_bin_s::ncached, bin_stats_s::nfills, bin_stats_s::nmalloc, bin_stats_s::nrequests, cache_bin_stats_s::nrequests, NULL, opt_junk_alloc, prof_idump, ptr(), bin_s::slabcur, bin_s::stats, tcache_bin_info, cache_bin_s::tstats, and unlikely.
Variable Documentation
arena_dalloc_junk_small
arena_dalloc_junk_small_t* JET_MUTABLE arena_dalloc_junk_small extern
Definition at line 1456 of file arena.c.
Referenced by arena_dalloc_bin_locked_impl().
arenas_lock
malloc_mutex_t arenas_lock extern
Definition at line 78 of file jemalloc.c.
h_steps
const uint64_t h_steps[SMOOTHSTEP_NSTEPS] extern
Definition at line 38 of file arena.c.
Referenced by arena_decay_backlog_npages_limit().
opt_dirty_decay_ms
ssize_t opt_dirty_decay_ms extern
Definition at line 32 of file arena.c.
Referenced by arena_boot().
opt_muzzy_decay_ms
ssize_t opt_muzzy_decay_ms extern
Definition at line 33 of file arena.c.
Referenced by arena_boot().
opt_oversize_threshold
size_t opt_oversize_threshold extern
Definition at line 47 of file arena.c.
Referenced by arena_init_huge().
opt_percpu_arena
percpu_arena_mode_t opt_percpu_arena extern
Definition at line 30 of file arena.c.
oversize_threshold
size_t oversize_threshold extern
Definition at line 48 of file arena.c.
Referenced by arena_init_huge().
percpu_arena_mode_names
const char* percpu_arena_mode_names[] extern
Definition at line 23 of file arena.c.