Azerotcore-wotlk: spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript Class Reference
spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript Class Reference
Public Member Functions
spell_halion_damage_aoe_summon_SpellScript (uint32 explosionSpell, uint32 auraSpell)
void HandleSummon (SpellEffIndex effIndex)
void Register () override
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Public Attributes
uint32 _explosionSpell
uint32 _auraSpell
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Private Member Functions
PrepareSpellScript (spell_halion_damage_aoe_summon_SpellScript)
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1033 of file boss_halion.cpp.
Constructor & Destructor Documentation
spell_halion_damage_aoe_summon_SpellScript()
spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::spell_halion_damage_aoe_summon_SpellScript (uint32 explosionSpell, uint32 auraSpell) inline
Definition at line 1038 of file boss_halion.cpp.
 : SpellScript(), _explosionSpell(explosionSpell), _auraSpell(auraSpell) { }
Member Function Documentation
HandleSummon()
void spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon (SpellEffIndex effIndex) inline
Definition at line 1040 of file boss_halion.cpp.
         {
             PreventHitDefaultEffect(effIndex);
             Unit* caster = GetCaster();
             uint32 entry = uint32(GetSpellInfo()->Effects[effIndex].MiscValue);
             SummonPropertiesEntry const* properties = sSummonPropertiesStore.LookupEntry(uint32(GetSpellInfo()->Effects[effIndex].MiscValueB));
             uint32 duration = uint32(GetSpellInfo()->GetDuration());
             Position pos = caster->GetPosition();
             if (Creature* summon = caster->GetMap()->SummonCreature(entry, pos, properties, duration, caster, GetSpellInfo()->Id))
             {
                 bool heroic = summon->GetMap()->IsHeroic();
                 bool raid = summon->GetMap()->Is25ManRaid();
                 if (heroic)
                     summon->SetPhaseMask(0x01 | 0x20, true);
                 else if (summon->GetEntry() == NPC_COMBUSTION)
                     summon->SetPhaseMask(0x01, true);
                 else
                     summon->SetPhaseMask(0x20, true);
                 summon->CastCustomSpell(SPELL_SCALE_AURA, SPELLVALUE_AURA_STACK, GetSpellValue()->EffectBasePoints[EFFECT_1], summon);
                 summon->CastSpell(summon, _auraSpell, true);
                 int32 damage = int32((1500 + (GetSpellValue()->EffectBasePoints[EFFECT_1] * 1250)) * (heroic ? 1.25f : 1.0f) * (raid ? 1.5f : 1.0f));
                 caster->CastCustomSpell(_explosionSpell, SPELLVALUE_BASE_POINT0, damage, caster);
             }
         }
References _auraSpell, _explosionSpell, Unit::CastCustomSpell(), EFFECT_1, SpellScript::GetCaster(), WorldObject::GetMap(), Position::GetPosition(), SpellScript::GetSpellInfo(), SpellScript::GetSpellValue(), NPC_COMBUSTION, pos(), SpellScript::PreventHitDefaultEffect(), SPELL_SCALE_AURA, SPELLVALUE_AURA_STACK, SPELLVALUE_BASE_POINT0, sSummonPropertiesStore, and Map::SummonCreature().
Referenced by Register().
PrepareSpellScript()
spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::PrepareSpellScript (spell_halion_damage_aoe_summon_SpellScript) private
Register()
void spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::Register () inline override virtual
Implements _SpellScript.
Definition at line 1069 of file boss_halion.cpp.
         {
             OnEffectHit += SpellEffectFn(spell_halion_damage_aoe_summon_SpellScript::HandleSummon, EFFECT_0, SPELL_EFFECT_SUMMON);
         }
References EFFECT_0, HandleSummon(), SpellScript::OnEffectHit, SPELL_EFFECT_SUMMON, and SpellEffectFn.
Member Data Documentation
_auraSpell
uint32 spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::_auraSpell
Definition at line 1075 of file boss_halion.cpp.
Referenced by HandleSummon().
_explosionSpell
uint32 spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::_explosionSpell
Definition at line 1074 of file boss_halion.cpp.
Referenced by HandleSummon().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp