Azerotcore-wotlk: boss_sister_svalna::boss_sister_svalnaAI Struct Reference
boss_sister_svalna::boss_sister_svalnaAI Struct Reference
Public Member Functions
boss_sister_svalnaAI (Creature *creature)
void Reset () override
void AttackStart (Unit *victim) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void SpellHit (Unit *caster, SpellInfo const *spell) override
void MovementInform (uint32 type, uint32 id) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 992 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
boss_sister_svalnaAI()
boss_sister_svalna::boss_sister_svalnaAI::boss_sister_svalnaAI (Creature * creature) inline
Definition at line 994 of file icecrown_citadel.cpp.
                                                  : BossAI(creature, DATA_SISTER_SVALNA)
         {
         }
Member Function Documentation
AttackStart()
void boss_sister_svalna::boss_sister_svalnaAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1008 of file icecrown_citadel.cpp.
         {
             if (me->HasReactState(REACT_PASSIVE) || me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC))
                 return;
             BossAI::AttackStart(victim);
         }
References ScriptedAI::AttackStart(), Object::HasFlag(), Creature::HasReactState(), ScriptedAI::me, REACT_PASSIVE, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
DoAction()
void boss_sister_svalna::boss_sister_svalnaAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1083 of file icecrown_citadel.cpp.
         {
             switch (action)
             {
                 case ACTION_KILL_CAPTAIN:
                     if (me->IsAlive())
                         me->CastCustomSpell(SPELL_CARESS_OF_DEATH, SPELLVALUE_MAX_TARGETS, 1, me, true);
                     break;
                 case ACTION_START_GAUNTLET:
                     me->setActive(true);
                     events.ScheduleEvent(EVENT_SVALNA_START, 25000);
                     break;
                 case ACTION_RESURRECT_CAPTAINS:
                     events.RescheduleEvent(EVENT_SVALNA_RESURRECT, 7000);
                     break;
                 case ACTION_CAPTAIN_DIES:
                     Talk(SAY_SVALNA_CAPTAIN_DEATH);
                     break;
                 case ACTION_RESET_EVENT:
                     me->setActive(false);
                     Reset();
                     break;
                 default:
                     break;
             }
         }
References ACTION_CAPTAIN_DIES, ACTION_KILL_CAPTAIN, ACTION_RESET_EVENT, ACTION_RESURRECT_CAPTAINS, ACTION_START_GAUNTLET, Unit::CastCustomSpell(), EVENT_SVALNA_RESURRECT, EVENT_SVALNA_START, Unit::IsAlive(), ScriptedAI::me, Reset(), SAY_SVALNA_CAPTAIN_DEATH, WorldObject::setActive(), SPELL_CARESS_OF_DEATH, SPELLVALUE_MAX_TARGETS, and CreatureAI::Talk().
EnterCombat()
void boss_sister_svalna::boss_sister_svalnaAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 1038 of file icecrown_citadel.cpp.
         {
             if (me->HasReactState(REACT_PASSIVE) || me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC))
             {
                 me->CombatStop(false);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 me->SetReactState(REACT_PASSIVE);
                 return;
             }
             _EnterCombat();
             me->LowerPlayerDamageReq(me->GetMaxHealth());
             if (Creature* crok = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_CROK_SCOURGEBANE)))
             {
                 crok->AI()->Talk(SAY_CROK_COMBAT_SVALNA);
                 crok->AI()->AttackStart(me);
             }
             events.ScheduleEvent(EVENT_SVALNA_COMBAT, 9000);
             events.ScheduleEvent(EVENT_IMPALING_SPEAR, urand(15000, 20000));
         }
References BossAI::_EnterCombat(), Unit::CombatStop(), DATA_CROK_SCOURGEBANE, EVENT_IMPALING_SPEAR, EVENT_SVALNA_COMBAT, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), Object::HasFlag(), Creature::HasReactState(), BossAI::instance, Creature::LowerPlayerDamageReq(), ScriptedAI::me, REACT_PASSIVE, SAY_CROK_COMBAT_SVALNA, Object::SetFlag(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and urand().
JustDied()
void boss_sister_svalna::boss_sister_svalnaAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 1015 of file icecrown_citadel.cpp.
         {
             _JustDied();
             Talk(SAY_SVALNA_DEATH);
             if (Creature* crok = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_CROK_SCOURGEBANE))) // _isEventDone = true, setActive(false)
                 crok->AI()->DoAction(ACTION_RESET_EVENT);
             uint64 delay = 6000;
             for (uint32 i = 0; i < 4; ++i)
                 if (Creature* crusader = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_CAPTAIN_ARNATH + i)))
                     if (crusader->IsAlive())
                     {
                         if (crusader->GetEntry() == crusader->GetCreatureData()->id)
{
                             crusader->m_Events.AddEvent(new CaptainSurviveTalk(*crusader), crusader->m_Events.CalculateTime(delay));
                             delay += 6000;
                         }
                         else
                             Unit::Kill(crusader, crusader);
                     }
         }
References BossAI::_JustDied(), ACTION_RESET_EVENT, DATA_CAPTAIN_ARNATH, DATA_CROK_SCOURGEBANE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, Unit::Kill(), ScriptedAI::me, SAY_SVALNA_DEATH, and CreatureAI::Talk().
KilledUnit()
void boss_sister_svalna::boss_sister_svalnaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1058 of file icecrown_citadel.cpp.
         {
             switch (victim->GetTypeId())
             {
                 case TYPEID_PLAYER:
                     Talk(SAY_SVALNA_KILL);
                     break;
                 /*case TYPEID_UNIT: // captains also say something on death and this causes spam
                     switch (victim->GetEntry())
                     {
                         case NPC_CAPTAIN_ARNATH:
                         case NPC_CAPTAIN_BRANDON:
                         case NPC_CAPTAIN_GRONDEL:
                         case NPC_CAPTAIN_RUPERT:
                             Talk(SAY_SVALNA_KILL_CAPTAIN);
                             break;
                         default:
                             break;
                     }
                     break;*/
                 default:
                     break;
             }
         }
References Object::GetTypeId(), SAY_SVALNA_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_sister_svalna::boss_sister_svalnaAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1119 of file icecrown_citadel.cpp.
         {
             if (type != EFFECT_MOTION_TYPE || id != POINT_LAND)
                 return;
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             me->SetCanFly(false);
             me->SetDisableGravity(false);
             me->SetReactState(REACT_AGGRESSIVE);
             DoZoneInCombat(nullptr, 150.0f);
         }
References CreatureAI::DoZoneInCombat(), EFFECT_MOTION_TYPE, ScriptedAI::me, POINT_LAND, REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
Reset()
void boss_sister_svalna::boss_sister_svalnaAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 998 of file icecrown_citadel.cpp.
         {
             _Reset();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             me->SetReactState(REACT_PASSIVE);
             me->SetCanFly(true);
             me->SetDisableGravity(true);
             me->SendMovementFlagUpdate();
         }
References BossAI::_Reset(), ScriptedAI::me, REACT_PASSIVE, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
Referenced by DoAction().
SpellHit()
void boss_sister_svalna::boss_sister_svalnaAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1110 of file icecrown_citadel.cpp.
         {
             if (spell->Id == SPELL_HURL_SPEAR && me->HasAura(SPELL_AETHER_SHIELD))
             {
                 me->RemoveAurasDueToSpell(SPELL_AETHER_SHIELD);
                 Talk(EMOTE_SVALNA_BROKEN_SHIELD, caster);
             }
         }
References EMOTE_SVALNA_BROKEN_SHIELD, Unit::HasAura(), SpellInfo::Id, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SPELL_AETHER_SHIELD, SPELL_HURL_SPEAR, and CreatureAI::Talk().
SpellHitTarget()
void boss_sister_svalna::boss_sister_svalnaAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1131 of file icecrown_citadel.cpp.
         {
             switch (spell->Id)
             {
                 case SPELL_IMPALING_SPEAR_KILL:
                     Unit::Kill(me, target);
                     break;
                 case SPELL_IMPALING_SPEAR:
                     if (TempSummon* summon = target->SummonCreature(NPC_IMPALING_SPEAR, *target))
                     {
                         Talk(EMOTE_SVALNA_IMPALE, target);
                         summon->CastCustomSpell(VEHICLE_SPELL_RIDE_HARDCODED, SPELLVALUE_BASE_POINT0, 1, target, false);
                         summon->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_HIDE_BODY | UNIT_FLAG2_ALLOW_ENEMY_INTERACT);
                     }
                     break;
                 default:
                     break;
             }
         }
References EMOTE_SVALNA_IMPALE, SpellInfo::Id, Unit::Kill(), ScriptedAI::me, NPC_IMPALING_SPEAR, SPELL_IMPALING_SPEAR, SPELL_IMPALING_SPEAR_KILL, SPELLVALUE_BASE_POINT0, WorldObject::SummonCreature(), CreatureAI::Talk(), UNIT_FIELD_FLAGS_2, UNIT_FLAG2_ALLOW_ENEMY_INTERACT, UNIT_FLAG2_HIDE_BODY, and VEHICLE_SPELL_RIDE_HARDCODED.
UpdateAI()
void boss_sister_svalna::boss_sister_svalnaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 1151 of file icecrown_citadel.cpp.
         {
             if (!me->isActiveObject())
                 return;
             UpdateVictim();
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SVALNA_START:
                     Talk(SAY_SVALNA_EVENT_START);
                     break;
                 case EVENT_SVALNA_RESURRECT:
                     Talk(SAY_SVALNA_RESURRECT_CAPTAINS);
                     me->CastSpell(me, SPELL_REVIVE_CHAMPION, false);
                     break;
                 case EVENT_SVALNA_COMBAT:
                     Talk(SAY_SVALNA_AGGRO);
                     break;
                 case EVENT_IMPALING_SPEAR:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true, -SPELL_IMPALING_SPEAR))
                     {
                         DoCast(me, SPELL_AETHER_SHIELD);
                         me->AddAura(70203, me);
                         DoCast(target, SPELL_IMPALING_SPEAR);
                     }
                     events.ScheduleEvent(EVENT_IMPALING_SPEAR, urand(20000, 25000));
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddAura(), Unit::CastSpell(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), EVENT_IMPALING_SPEAR, EVENT_SVALNA_COMBAT, EVENT_SVALNA_RESURRECT, EVENT_SVALNA_START, Unit::HasUnitState(), WorldObject::isActiveObject(), ScriptedAI::me, SAY_SVALNA_AGGRO, SAY_SVALNA_EVENT_START, SAY_SVALNA_RESURRECT_CAPTAINS, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_AETHER_SHIELD, SPELL_IMPALING_SPEAR, SPELL_REVIVE_CHAMPION, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp