Azerotcore-wotlk: deps/mysqllite/mysys/my_alloc.c File Reference
my_alloc.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include <m_string.h>
Macros
#define EXTRA_DEBUG
#define TRASH_MEM(X) TRASH(((char*)(X) + ((X)->size-(X)->left)), (X)->left)
Functions
void init_alloc_root (MEM_ROOT *mem_root, size_t block_size, size_t pre_alloc_size __attribute__((unused)))
void reset_root_defaults (MEM_ROOT *mem_root, size_t block_size, size_t pre_alloc_size __attribute__((unused)))
void * alloc_root (MEM_ROOT *mem_root, size_t length)
void * multi_alloc_root (MEM_ROOT *root,...)
static void mark_blocks_free (MEM_ROOT *root)
void free_root (MEM_ROOT *root, myf MyFlags)
void set_prealloc_root (MEM_ROOT *root, char *ptr)
char * strdup_root (MEM_ROOT *root, const char *str)
char * strmake_root (MEM_ROOT *root, const char *str, size_t len)
void * memdup_root (MEM_ROOT *root, const void *str, size_t len)
Macro Definition Documentation
EXTRA_DEBUG
#define EXTRA_DEBUG
Definition at line 22 of file my_alloc.c.
TRASH_MEM
#define TRASH_MEM (X) TRASH(((char*)(X) + ((X)->size-(X)->left)), (X)->left)
Definition at line 295 of file my_alloc.c.
Function Documentation
alloc_root()
void* alloc_root (MEM_ROOT * mem_root, size_t length)
Definition at line 148 of file my_alloc.c.
 {
 #if defined(HAVE_purify) && defined(EXTRA_DEBUG)
   reg1 USED_MEM *next;
   DBUG_ENTER("alloc_root");
   DBUG_PRINT("enter",("root: 0x%lx", (long) mem_root));
   DBUG_ASSERT(alloc_root_inited(mem_root));
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     if (mem_root->error_handler)
                       (*mem_root->error_handler)();
                     DBUG_SET("-d,simulate_out_of_memory");
                     DBUG_RETURN((void*) 0); /* purecov: inspected */
                   });
   length+=ALIGN_SIZE(sizeof(USED_MEM));
   if (!(next = (USED_MEM*) my_malloc(length,MYF(MY_WME | ME_FATALERROR))))
   {
     if (mem_root->error_handler)
       (*mem_root->error_handler)();
     DBUG_RETURN((uchar*) 0);            /* purecov: inspected */
   }
   next->next= mem_root->used;
   next->size= length;
   mem_root->used= next;
   DBUG_PRINT("exit",("ptr: 0x%lx", (long) (((char*) next)+
                                            ALIGN_SIZE(sizeof(USED_MEM)))));
   DBUG_RETURN((uchar*) (((char*) next)+ALIGN_SIZE(sizeof(USED_MEM))));
 #else
   size_t get_size, block_size;
   uchar* point;
   reg1 USED_MEM *next= 0;
   reg2 USED_MEM **prev;
   DBUG_ENTER("alloc_root");
   DBUG_PRINT("enter",("root: 0x%lx", (long) mem_root));
   DBUG_ASSERT(alloc_root_inited(mem_root));
   DBUG_EXECUTE_IF("simulate_out_of_memory",
                   {
                     /* Avoid reusing an already allocated block */
                     if (mem_root->error_handler)
                       (*mem_root->error_handler)();
                     DBUG_SET("-d,simulate_out_of_memory");
                     DBUG_RETURN((void*) 0); /* purecov: inspected */
                   });
   length= ALIGN_SIZE(length);
   if ((*(prev= &mem_root->free)) != NULL)
   {
     if ((*prev)->left < length &&
     mem_root->first_block_usage++ >= ALLOC_MAX_BLOCK_USAGE_BEFORE_DROP &&
     (*prev)->left < ALLOC_MAX_BLOCK_TO_DROP)
     {
       next= *prev;
       *prev= next->next;            /* Remove block from list */
       next->next= mem_root->used;
       mem_root->used= next;
       mem_root->first_block_usage= 0;
     }
     for (next= *prev ; next && next->left < length ; next= next->next)
       prev= &next->next;
   }
   if (! next)
   {                     /* Time to alloc new block */
     block_size= mem_root->block_size * (mem_root->block_num >> 2);
     get_size= length+ALIGN_SIZE(sizeof(USED_MEM));
     get_size= max(get_size, block_size);
     if (!(next = (USED_MEM*) my_malloc(get_size,MYF(MY_WME | ME_FATALERROR))))
     {
       if (mem_root->error_handler)
     (*mem_root->error_handler)();
       DBUG_RETURN((void*) 0);                      /* purecov: inspected */
     }
     mem_root->block_num++;
     next->next= *prev;
     next->size= get_size;
     next->left= get_size-ALIGN_SIZE(sizeof(USED_MEM));
     *prev=next;
   }
   point= (uchar*) ((char*) next+ (next->size-next->left));
   /*TODO: next part may be unneded due to mem_root->first_block_usage counter*/
   if ((next->left-= length) < mem_root->min_malloc)
   {                     /* Full block */
     *prev= next->next;              /* Remove block from list */
     next->next= mem_root->used;
     mem_root->used= next;
     mem_root->first_block_usage= 0;
   }
   DBUG_PRINT("exit",("ptr: 0x%lx", (ulong) point));
   DBUG_RETURN((void*) point);
 #endif
 }
References ALIGN_SIZE, ALLOC_MAX_BLOCK_TO_DROP, ALLOC_MAX_BLOCK_USAGE_BEFORE_DROP, alloc_root_inited, st_mem_root::block_num, st_mem_root::block_size, DBUG_ASSERT, DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, DBUG_SET, st_mem_root::error_handler, st_mem_root::first_block_usage, st_mem_root::free, G3D::length(), max, ME_FATALERROR, mem_root, st_mem_root::min_malloc, my_malloc(), MY_WME, MYF, next(), NULL, prev(), reg1, reg2, and st_mem_root::used.
Referenced by alloc_stmt_fields(), cli_read_binary_rows(), cli_read_rows(), copy_typelib(), handle_default_option(), init_default_directories(), memdup_root(), multi_alloc_root(), my_dir(), my_load_defaults(), my_search_option_files(), mysql_stmt_prepare(), strmake_root(), tree_insert(), and unpack_fields().
free_root()
void free_root (MEM_ROOT * root, myf MyFlags)
Definition at line 347 of file my_alloc.c.
 {
   reg1 USED_MEM *next,*old;
   DBUG_ENTER("free_root");
   DBUG_PRINT("enter",("root: 0x%lx  flags: %u", (long) root, (uint) MyFlags));
   if (MyFlags & MY_MARK_BLOCKS_FREE)
   {
     mark_blocks_free(root);
     DBUG_VOID_RETURN;
   }
   if (!(MyFlags & MY_KEEP_PREALLOC))
     root->pre_alloc=0;
   for (next=root->used; next ;)
   {
     old=next; next= next->next ;
     if (old != root->pre_alloc)
       my_free(old);
   }
   for (next=root->free ; next ;)
   {
     old=next; next= next->next;
     if (old != root->pre_alloc)
       my_free(old);
   }
   root->used=root->free=0;
   if (root->pre_alloc)
   {
     root->free=root->pre_alloc;
     root->free->left=root->pre_alloc->size-ALIGN_SIZE(sizeof(USED_MEM));
     TRASH_MEM(root->pre_alloc);
     root->free->next=0;
   }
   root->block_num= 4;
   root->first_block_usage= 0;
   DBUG_VOID_RETURN;
 }
References ALIGN_SIZE, st_mem_root::block_num, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_mem_root::first_block_usage, st_mem_root::free, st_used_mem::left, mark_blocks_free(), my_free(), MY_KEEP_PREALLOC, MY_MARK_BLOCKS_FREE, st_used_mem::next, next(), st_mem_root::pre_alloc, reg1, st_used_mem::size, TRASH_MEM, and st_mem_root::used.
Referenced by free_defaults(), free_old_query(), free_rows(), free_tree(), my_dirend(), my_load_defaults(), my_print_default_files(), mysql_client_plugin_deinit(), mysql_free_result(), mysql_stmt_close(), mysql_stmt_prepare(), mysql_stmt_store_result(), reset_stmt_handle(), and stmt_read_row_from_cursor().
init_alloc_root()
void init_alloc_root (MEM_ROOT * mem_root, size_t block_size, size_t pre_alloc_size __attribute__(unused))
Definition at line 46 of file my_alloc.c.
 {
   DBUG_ENTER("init_alloc_root");
   DBUG_PRINT("enter",("root: 0x%lx", (long) mem_root));
   mem_root->free= mem_root->used= mem_root->pre_alloc= 0;
   mem_root->min_malloc= 32;
   mem_root->block_size= block_size - ALLOC_ROOT_MIN_BLOCK_SIZE;
   mem_root->error_handler= 0;
   mem_root->block_num= 4;           /* We shift this with >>2 */
   mem_root->first_block_usage= 0;
 #if !(defined(HAVE_purify) && defined(EXTRA_DEBUG))
   if (pre_alloc_size)
   {
     if ((mem_root->free= mem_root->pre_alloc=
      (USED_MEM*) my_malloc(pre_alloc_size+ ALIGN_SIZE(sizeof(USED_MEM)),
                    MYF(0))))
     {
       mem_root->free->size= pre_alloc_size+ALIGN_SIZE(sizeof(USED_MEM));
       mem_root->free->left= pre_alloc_size;
       mem_root->free->next= 0;
     }
   }
 #endif
   DBUG_VOID_RETURN;
 }
References ALIGN_SIZE, ALLOC_ROOT_MIN_BLOCK_SIZE, st_mem_root::block_num, st_mem_root::block_size, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_mem_root::error_handler, st_mem_root::first_block_usage, st_mem_root::free, st_used_mem::left, mem_root, st_mem_root::min_malloc, my_malloc(), MYF, st_used_mem::next, st_mem_root::pre_alloc, st_used_mem::size, and st_mem_root::used.
mark_blocks_free()
static void mark_blocks_free (MEM_ROOT * root) inline static
Definition at line 299 of file my_alloc.c.
 {
   reg1 USED_MEM *next;
   reg2 USED_MEM **last;
   /* iterate through (partially) free blocks, mark them free */
   last= &root->free;
   for (next= root->free; next; next= *(last= &next->next))
   {
     next->left= next->size - ALIGN_SIZE(sizeof(USED_MEM));
     TRASH_MEM(next);
   }
   /* Combine the free and the used list */
   *last= next=root->used;
   /* now go through the used blocks and mark them free */
   for (; next; next= next->next)
   {
     next->left= next->size - ALIGN_SIZE(sizeof(USED_MEM));
     TRASH_MEM(next);
   }
   /* Now everything is set; Indicate that nothing is used anymore */
   root->used= 0;
   root->first_block_usage= 0;
 }
References ALIGN_SIZE, st_mem_root::first_block_usage, st_mem_root::free, next(), reg1, reg2, TRASH_MEM, and st_mem_root::used.
Referenced by free_root().
memdup_root()
void* memdup_root (MEM_ROOT * root, const void * str, size_t len)
Definition at line 430 of file my_alloc.c.
 {
   char *pos;
   if ((pos=alloc_root(root,len)))
     memcpy(pos,str,len);
   return pos;
 }
References alloc_root(), memcpy, and pos().
Referenced by add_plugin().
multi_alloc_root()
void* multi_alloc_root (MEM_ROOT * root, ...)
Definition at line 264 of file my_alloc.c.
 {
   va_list args;
   char **ptr, *start, *res;
   size_t tot_length, length;
   DBUG_ENTER("multi_alloc_root");
   va_start(args, root);
   tot_length= 0;
   while ((ptr= va_arg(args, char **)))
   {
     length= va_arg(args, uint);
     tot_length+= ALIGN_SIZE(length);
   }
   va_end(args);
   if (!(start= (char*) alloc_root(root, tot_length)))
     DBUG_RETURN(0);                            /* purecov: inspected */
   va_start(args, root);
   res= start;
   while ((ptr= va_arg(args, char **)))
   {
     *ptr= res;
     length= va_arg(args, uint);
     res+= ALIGN_SIZE(length);
   }
   va_end(args);
   DBUG_RETURN((void*) start);
 }
References ALIGN_SIZE, alloc_root(), DBUG_ENTER, DBUG_RETURN, G3D::length(), and ptr().
reset_root_defaults()
void reset_root_defaults (MEM_ROOT * mem_root, size_t block_size, size_t pre_alloc_size __attribute__(unused))
Definition at line 93 of file my_alloc.c.
 {
   DBUG_ASSERT(alloc_root_inited(mem_root));
   mem_root->block_size= block_size - ALLOC_ROOT_MIN_BLOCK_SIZE;
 #if !(defined(HAVE_purify) && defined(EXTRA_DEBUG))
   if (pre_alloc_size)
   {
     size_t size= pre_alloc_size + ALIGN_SIZE(sizeof(USED_MEM));
     if (!mem_root->pre_alloc || mem_root->pre_alloc->size != size)
     {
       USED_MEM *mem, **prev= &mem_root->free;
       /*
         Free unused blocks, so that consequent calls
         to reset_root_defaults won't eat away memory.
       */
       while (*prev)
       {
         mem= *prev;
         if (mem->size == size)
         {
           /* We found a suitable block, no need to do anything else */
           mem_root->pre_alloc= mem;
           return;
         }
         if (mem->left + ALIGN_SIZE(sizeof(USED_MEM)) == mem->size)
         {
           /* remove block from the list and free it */
           *prev= mem->next;
           my_free(mem);
         }
         else
           prev= &mem->next;
       }
       /* Allocate new prealloc block and add it to the end of free list */
       if ((mem= (USED_MEM *) my_malloc(size, MYF(0))))
       {
         mem->size= size;
         mem->left= pre_alloc_size;
         mem->next= *prev;
         *prev= mem_root->pre_alloc= mem;
       }
       else
       {
         mem_root->pre_alloc= 0;
       }
     }
   }
   else
 #endif
     mem_root->pre_alloc= 0;
 }
References ALIGN_SIZE, alloc_root_inited, ALLOC_ROOT_MIN_BLOCK_SIZE, st_mem_root::block_size, DBUG_ASSERT, st_mem_root::free, st_used_mem::left, mem_root, my_free(), my_malloc(), MYF, st_used_mem::next, st_mem_root::pre_alloc, prev(), and st_used_mem::size.
set_prealloc_root()
void set_prealloc_root (MEM_ROOT * root, char * ptr)
Definition at line 390 of file my_alloc.c.
 {
   USED_MEM *next;
   for (next=root->used; next ; next=next->next)
   {
     if ((char*) next <= ptr && (char*) next + next->size > ptr)
     {
       root->pre_alloc=next;
       return;
     }
   }
   for (next=root->free ; next ; next=next->next)
   {
     if ((char*) next <= ptr && (char*) next + next->size > ptr)
     {
       root->pre_alloc=next;
       return;
     }
   }
 }
References st_mem_root::free, next(), st_mem_root::pre_alloc, ptr(), and st_mem_root::used.
strdup_root()
char* strdup_root (MEM_ROOT * root, const char * str)
Definition at line 412 of file my_alloc.c.
 {
   return strmake_root(root, str, strlen(str));
 }
References strmake_root().
Referenced by copy_typelib(), my_dir(), safe_strdup_root(), and unpack_fields().
strmake_root()
char* strmake_root (MEM_ROOT * root, const char * str, size_t len)
Definition at line 418 of file my_alloc.c.
 {
   char *pos;
   if ((pos=alloc_root(root,len+1)))
   {
     memcpy(pos,str,len);
     pos[len]=0;
   }
   return pos;
 }
References alloc_root(), memcpy, and pos().
Referenced by add_directory(), alloc_stmt_fields(), copy_typelib(), strdup_root(), and unpack_fields().