Azerotcore-wotlk: SocialMgr Class Reference
SocialMgr Class Reference
#include <SocialMgr.h>
Public Member Functions
void RemovePlayerSocial (ObjectGuid guid)
void MakeFriendStatusPacket (FriendsResult result, ObjectGuid friend_guid, WorldPacket *data)
void SendFriendStatus (Player *player, FriendsResult result, ObjectGuid friend_guid, bool broadcast)
void BroadcastToFriendListers (Player *player, WorldPacket *packet)
PlayerSocial * LoadFromDB (PreparedQueryResult result, ObjectGuid guid)
Static Public Member Functions
static SocialMgr * instance ()
static void GetFriendInfo (Player *player, ObjectGuid friendGUID, FriendInfo &friendInfo)
Private Types
typedef std::map< ObjectGuid, PlayerSocial > SocialMap
Private Member Functions
SocialMgr ()
~SocialMgr ()
Private Attributes
SocialMap m_socialMap
Detailed Description
Definition at line 125 of file SocialMgr.h.
Member Typedef Documentation
SocialMap
typedef std::map<ObjectGuid, PlayerSocial> SocialMgr::SocialMap private
Definition at line 143 of file SocialMgr.h.
Constructor & Destructor Documentation
SocialMgr()
SocialMgr::SocialMgr () private
Definition at line 198 of file SocialMgr.cpp.
 {
 }
~SocialMgr()
SocialMgr::~SocialMgr () private
Definition at line 202 of file SocialMgr.cpp.
 {
 }
Member Function Documentation
BroadcastToFriendListers()
void SocialMgr::BroadcastToFriendListers (Player * player, WorldPacket * packet)
Definition at line 294 of file SocialMgr.cpp.
 {
     if (!player)
         return;
     TeamId teamId = player->GetTeamId();
     AccountTypes security = player->GetSession()->GetSecurity();
     bool allowTwoSideWhoList = sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_WHO_LIST);
     AccountTypes gmLevelInWhoList = AccountTypes(sWorld->getIntConfig(CONFIG_GM_LEVEL_IN_WHO_LIST));
     for (auto const& itr : m_socialMap)
     {
         auto const& itr2 = itr.second.m_playerSocialMap.find(player->GetGUID());
         if (itr2 != itr.second.m_playerSocialMap.end() && (itr2->second.Flags & SOCIAL_FLAG_FRIEND))
         {
             Player* pFriend = ObjectAccessor::FindPlayer(itr.first);
             // PLAYER see his team only and PLAYER can't see MODERATOR, GAME MASTER, ADMINISTRATOR characters
             // MODERATOR, GAME MASTER, ADMINISTRATOR can see all
             if (pFriend && (!AccountMgr::IsPlayerAccount(pFriend->GetSession()->GetSecurity()) || ((pFriend->GetTeamId() == teamId || allowTwoSideWhoList) && security <= gmLevelInWhoList)) && player->IsVisibleGloballyFor(pFriend))
                 pFriend->GetSession()->SendPacket(packet);
         }
     }
 }
References CONFIG_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_GM_LEVEL_IN_WHO_LIST, ObjectAccessor::FindPlayer(), Object::GetGUID(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeamId(), AccountMgr::IsPlayerAccount(), Player::IsVisibleGloballyFor(), m_socialMap, WorldSession::SendPacket(), SOCIAL_FLAG_FRIEND, and sWorld.
Referenced by SendFriendStatus().
GetFriendInfo()
void SocialMgr::GetFriendInfo (Player * player, ObjectGuid friendGUID, FriendInfo & friendInfo) static
Definition at line 212 of file SocialMgr.cpp.
 {
     if (!player)
         return;
     friendInfo.Status = FRIEND_STATUS_OFFLINE;
     friendInfo.Area = 0;
     friendInfo.Level = 0;
     friendInfo.Class = 0;
     Player* pFriend = ObjectAccessor::FindConnectedPlayer(friendGUID);
     if (!pFriend || AccountMgr::IsGMAccount(pFriend->GetSession()->GetSecurity()))
         return;
     TeamId teamId = player->GetTeamId();
     AccountTypes security = player->GetSession()->GetSecurity();
     bool allowTwoSideWhoList = sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_WHO_LIST);
     AccountTypes gmLevelInWhoList = AccountTypes(sWorld->getIntConfig(CONFIG_GM_LEVEL_IN_WHO_LIST));
     auto const& itr = player->GetSocial()->m_playerSocialMap.find(friendGUID);
     if (itr != player->GetSocial()->m_playerSocialMap.end())
         friendInfo.Note = itr->second.Note;
     // PLAYER see his team only and PLAYER can't see MODERATOR, GAME MASTER, ADMINISTRATOR characters
     // MODERATOR, GAME MASTER, ADMINISTRATOR can see all
     if ((!AccountMgr::IsPlayerAccount(security) || ((pFriend->GetTeamId() == teamId || allowTwoSideWhoList) && pFriend->GetSession()->GetSecurity() <= gmLevelInWhoList)) && pFriend->IsVisibleGloballyFor(player))
     {
         friendInfo.Status = FRIEND_STATUS_ONLINE;
         if (pFriend->isAFK())
             friendInfo.Status = FRIEND_STATUS_AFK;
         if (pFriend->isDND())
             friendInfo.Status = FRIEND_STATUS_DND;
         friendInfo.Area = pFriend->GetZoneId();
         friendInfo.Level = pFriend->getLevel();
         friendInfo.Class = pFriend->getClass();
     }
 }
References FriendInfo::Area, FriendInfo::Class, CONFIG_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_GM_LEVEL_IN_WHO_LIST, ObjectAccessor::FindConnectedPlayer(), FRIEND_STATUS_AFK, FRIEND_STATUS_DND, FRIEND_STATUS_OFFLINE, FRIEND_STATUS_ONLINE, Unit::getClass(), Unit::getLevel(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetSocial(), Player::GetTeamId(), WorldObject::GetZoneId(), Player::isAFK(), Player::isDND(), AccountMgr::IsGMAccount(), AccountMgr::IsPlayerAccount(), Player::IsVisibleGloballyFor(), FriendInfo::Level, PlayerSocial::m_playerSocialMap, FriendInfo::Note, FriendInfo::Status, and sWorld.
Referenced by SendFriendStatus().
instance()
SocialMgr * SocialMgr::instance () static
Definition at line 206 of file SocialMgr.cpp.
 {
     static SocialMgr instance;
     return &instance;
 }
LoadFromDB()
PlayerSocial * SocialMgr::LoadFromDB (PreparedQueryResult result, ObjectGuid guid)
Definition at line 319 of file SocialMgr.cpp.
 {
     PlayerSocial* social = &m_socialMap[guid];
     social->SetPlayerGUID(guid);
     if (!result)
         return social;
     do
     {
         Field* fields = result->Fetch();
         auto friendGuid = ObjectGuid::Create<HighGuid::Player>(fields[0].GetUInt32());
         auto flags = fields[1].GetUInt8();
         auto note = fields[2].GetString();
         social->m_playerSocialMap[friendGuid] = FriendInfo(flags, note);
     } while (result->NextRow());
     return social;
 }
References Field::GetString(), Field::GetUInt8(), PlayerSocial::m_playerSocialMap, m_socialMap, and PlayerSocial::SetPlayerGUID().
MakeFriendStatusPacket()
void SocialMgr::MakeFriendStatusPacket (FriendsResult result, ObjectGuid friend_guid, WorldPacket * data)
Definition at line 250 of file SocialMgr.cpp.
 {
     data->Initialize(SMSG_FRIEND_STATUS, 9);
     *data << uint8(result);
     *data << guid;
 }
References SMSG_FRIEND_STATUS.
RemovePlayerSocial()
void SocialMgr::RemovePlayerSocial (ObjectGuid guid) inline
Definition at line 134 of file SocialMgr.h.
 { m_socialMap.erase(guid); }
References m_socialMap.
SendFriendStatus()
void SocialMgr::SendFriendStatus (Player * player, FriendsResult result, ObjectGuid friend_guid, bool broadcast)
Definition at line 257 of file SocialMgr.cpp.
 {
     FriendInfo fi;
     GetFriendInfo(player, friendGuid, fi);
     WorldPacket data(SMSG_FRIEND_STATUS, 9);
     data << uint8(result);
     data << friendGuid;
     switch (result)
     {
         case FRIEND_ADDED_OFFLINE:
         case FRIEND_ADDED_ONLINE:
             data << fi.Note;
             break;
         default:
             break;
     }
     switch (result)
     {
         case FRIEND_ADDED_ONLINE:
         case FRIEND_ONLINE:
             data << uint8(fi.Status);
             data << uint32(fi.Area);
             data << uint32(fi.Level);
             data << uint32(fi.Class);
             break;
         default:
             break;
     }
     if (broadcast)
         BroadcastToFriendListers(player, &data);
     else
         player->GetSession()->SendPacket(&data);
 }
References FriendInfo::Area, BroadcastToFriendListers(), FriendInfo::Class, FRIEND_ADDED_OFFLINE, FRIEND_ADDED_ONLINE, FRIEND_ONLINE, GetFriendInfo(), Player::GetSession(), FriendInfo::Level, FriendInfo::Note, WorldSession::SendPacket(), SMSG_FRIEND_STATUS, and FriendInfo::Status.
Member Data Documentation
m_socialMap
SocialMap SocialMgr::m_socialMap private
Definition at line 144 of file SocialMgr.h.
Referenced by BroadcastToFriendListers(), LoadFromDB(), and RemovePlayerSocial().
The documentation for this class was generated from the following files:
src/server/game/Entities/Player/SocialMgr.h
src/server/game/Entities/Player/SocialMgr.cpp