Azerotcore-wotlk: boss_essence_of_suffering::boss_essence_of_sufferingAI Struct Reference
boss_essence_of_suffering::boss_essence_of_sufferingAI Struct Reference
Public Member Functions
boss_essence_of_sufferingAI (Creature *creature)
void Reset () override
void DoAction (int32 param) override
void MovementInform (uint32 type, uint32 id) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 274 of file boss_reliquary_of_souls.cpp.
Constructor & Destructor Documentation
boss_essence_of_sufferingAI()
boss_essence_of_suffering::boss_essence_of_sufferingAI::boss_essence_of_sufferingAI (Creature * creature) inline
Definition at line 276 of file boss_reliquary_of_souls.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
DamageTaken()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 305 of file boss_reliquary_of_souls.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 {
                     me->RemoveAurasDueToSpell(SPELL_ESSENCE_OF_SUFFERING_PASSIVE); // prevent fixate from triggering
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     Talk(SUFF_SAY_RECAP);
                     me->SetReactState(REACT_PASSIVE);
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MovePoint(POINT_GO_BACK, me->GetHomePosition(), false);
                     events.Reset();
                 }
             }
         }
References MotionMaster::Clear(), Unit::GetHealth(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Object::HasFlag(), ScriptedAI::me, MotionMaster::MovePoint(), POINT_GO_BACK, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), Object::SetFlag(), Creature::SetReactState(), SPELL_ESSENCE_OF_SUFFERING_PASSIVE, SUFF_SAY_RECAP, CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 285 of file boss_reliquary_of_souls.cpp.
         {
             if (param == ACTION_ENGAGE_ESSENCE)
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->SetInCombatWithZone();
             }
         }
References ACTION_ENGAGE_ESSENCE, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetInCombatWithZone(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 332 of file boss_reliquary_of_souls.cpp.
         {
             Talk(SUFF_SAY_FREED);
             me->CastSpell(me, SPELL_AURA_OF_SUFFERING, true);
             me->CastSpell(me, SPELL_ESSENCE_OF_SUFFERING_PASSIVE, true);
             me->CastSpell(me, SPELL_ESSENCE_OF_SUFFERING_PASSIVE2, true);
             events.ScheduleEvent(EVENT_SUFF_FRENZY, 45000);
             events.ScheduleEvent(EVENT_SUFF_SOUL_DRAIN, 25000);
         }
References Unit::CastSpell(), EVENT_SUFF_FRENZY, EVENT_SUFF_SOUL_DRAIN, ScriptedAI::me, SPELL_AURA_OF_SUFFERING, SPELL_ESSENCE_OF_SUFFERING_PASSIVE, SPELL_ESSENCE_OF_SUFFERING_PASSIVE2, SUFF_SAY_FREED, and CreatureAI::Talk().
KilledUnit()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 323 of file boss_reliquary_of_souls.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SUFF_SAY_SLAY);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SUFF_SAY_SLAY, and CreatureAI::Talk().
MovementInform()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 295 of file boss_reliquary_of_souls.cpp.
         {
             if (type != POINT_MOTION_TYPE || id != POINT_GO_BACK)
                 return;
             me->m_Events.AddEvent(new SuckBackEvent(*me, ACTION_ESSENCE_OF_SUFFERING), me->m_Events.CalculateTime(1500));
             me->SetTarget();
             me->SetFacingTo(M_PI / 2.0f);
         }
References ACTION_ESSENCE_OF_SUFFERING, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::m_Events, ScriptedAI::me, POINT_GO_BACK, POINT_MOTION_TYPE, Unit::SetFacingTo(), and Creature::SetTarget().
Reset()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 280 of file boss_reliquary_of_souls.cpp.
         {
             events.Reset();
         }
UpdateAI()
void boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 343 of file boss_reliquary_of_souls.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SUFF_SOUL_DRAIN:
                     me->CastCustomSpell(SPELL_SOUL_DRAIN, SPELLVALUE_MAX_TARGETS, 3, me, false);
                     events.ScheduleEvent(EVENT_SUFF_SOUL_DRAIN, 30000);
                     break;
                 case EVENT_SUFF_FRENZY:
                     Talk(SUFF_SAY_ENRAGE);
                     Talk(SUFF_EMOTE_ENRAGE);
                     me->CastSpell(me, SPELL_FRENZY, false);
                     events.ScheduleEvent(EVENT_SUFF_FRENZY, 45000);
                     events.ScheduleEvent(EVENT_SUFF_FRENZY_EMOTE, 3000);
                     break;
                 case EVENT_SUFF_FRENZY_EMOTE:
                     Talk(SUFF_EMOTE_ENRAGE);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastCustomSpell(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_SUFF_FRENZY, EVENT_SUFF_FRENZY_EMOTE, EVENT_SUFF_SOUL_DRAIN, Unit::HasUnitState(), ScriptedAI::me, SPELL_FRENZY, SPELL_SOUL_DRAIN, SPELLVALUE_MAX_TARGETS, SUFF_EMOTE_ENRAGE, SUFF_SAY_ENRAGE, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_essence_of_suffering::boss_essence_of_sufferingAI::events
Definition at line 278 of file boss_reliquary_of_souls.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp