Azerotcore-wotlk: npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI Struct Reference
npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI Struct Reference
Public Member Functions
npc_high_overlord_saurfangAI (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void SpellHit (Unit *, SpellInfo const *spell) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
std::list< Creature * > _guardList
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 523 of file boss_deathbringer_saurfang.cpp.
Constructor & Destructor Documentation
npc_high_overlord_saurfangAI()
npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::npc_high_overlord_saurfangAI (Creature * creature) inline
Definition at line 525 of file boss_deathbringer_saurfang.cpp.
                                                          : ScriptedAI(creature)
         {
             ASSERT(creature->GetVehicleKit());
             _instance = me->GetInstanceScript();
         }
References _instance, ASSERT, WorldObject::GetInstanceScript(), Unit::GetVehicleKit(), and ScriptedAI::me.
Member Function Documentation
DoAction()
void npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 538 of file boss_deathbringer_saurfang.cpp.
         {
             switch (action)
             {
                 case ACTION_START_EVENT:
                     {
                         // Prevent crashes
                         if (_events.GetPhaseMask() & PHASE_INTRO_MASK)
                             return;
                         Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG));
                         if (!deathbringer || deathbringer->IsInEvadeMode())
                             return;
                         if (_guardList.empty())
{
                             GetCreatureListWithEntryInGrid(_guardList, me, NPC_SE_KOR_KRON_REAVER, 20.0f);
                             _guardList.sort(Acore::ObjectDistanceOrderPred(me));
                         }
                         uint32 x = 1;
                         for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                             (*itr)->AI()->SetData(0, x++);
                         me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                         Talk(SAY_INTRO_HORDE_1);
                         _events.SetPhase(PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_2, 5000, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_3, 18500, 0, PHASE_INTRO_H);
                         _instance->HandleGameObject(_instance->GetGuidData(GO_SAURFANG_S_DOOR), true);
                         if (GameObject* teleporter = ObjectAccessor::GetGameObject(*me, _instance->GetGuidData(GO_SCOURGE_TRANSPORTER_SAURFANG)))
{
                             _instance->HandleGameObject(ObjectGuid::Empty, false, teleporter);
                             teleporter->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                         }
                         deathbringer->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         deathbringer->SetWalk(false);
                         deathbringer->GetMotionMaster()->MovePoint(POINT_SAURFANG, deathbringerPos.GetPositionX(), deathbringerPos.GetPositionY(), deathbringerPos.GetPositionZ());
                     }
                     break;
                 case ACTION_START_OUTRO:
                     {
                         me->RemoveAurasDueToSpell(SPELL_GRIP_OF_AGONY);
                         me->SetDisableGravity(false);
                         me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), 539.2917f, 10.0f);
                         for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                             (*itr)->AI()->DoAction(ACTION_DESPAWN);
                         /*Talk(SAY_OUTRO_HORDE_1);
                         _events.ScheduleEvent(EVENT_OUTRO_HORDE_1, 10000);
                         _events.ScheduleEvent(EVENT_OUTRO_HORDE_2, 18000);
                         _events.ScheduleEvent(EVENT_OUTRO_HORDE_3, 24000);*/
                     }
                     break;
                 case ACTION_EVADE:
                     {
                         float x, y, z, o;
                         me->GetMotionMaster()->Clear();
                         me->GetHomePosition(x, y, z, o);
                         me->SetPosition(x, y, z, o);
                         me->StopMovingOnCurrentPos();
                         me->SetDisableGravity(false);
                         EnterEvadeMode();
                         for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
{
                             (*itr)->GetMotionMaster()->Clear();
                             (*itr)->GetHomePosition(x, y, z, o);
                             (*itr)->SetPosition(x, y, z, o);
                             (*itr)->StopMovingOnCurrentPos();
                             (*itr)->SetDisableGravity(false);
                             (*itr)->AI()->EnterEvadeMode();
                         }
                     }
                     break;
                 default:
                     break;
             }
         }
References _events, _guardList, _instance, ACTION_DESPAWN, ACTION_EVADE, ACTION_START_EVENT, ACTION_START_OUTRO, MotionMaster::Clear(), DATA_DEATHBRINGER_SAURFANG, deathbringerPos, ObjectGuid::Empty, CreatureAI::EnterEvadeMode(), EVENT_INTRO_HORDE_2, EVENT_INTRO_HORDE_3, GAMEOBJECT_FLAGS, ObjectAccessor::GetCreature(), GetCreatureListWithEntryInGrid(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), EventMap::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_IN_USE, GO_SAURFANG_S_DOOR, GO_SCOURGE_TRANSPORTER_SAURFANG, InstanceScript::HandleGameObject(), Creature::IsInEvadeMode(), ScriptedAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MovePoint(), NPC_SE_KOR_KRON_REAVER, PHASE_INTRO_H, PHASE_INTRO_MASK, POINT_SAURFANG, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_INTRO_HORDE_1, EventMap::ScheduleEvent(), Creature::SetDisableGravity(), EventMap::SetPhase(), Creature::SetPosition(), Creature::SetWalk(), SPELL_GRIP_OF_AGONY, Unit::StopMovingOnCurrentPos(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
MovementInform()
void npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 627 of file boss_deathbringer_saurfang.cpp.
         {
             if (type == POINT_MOTION_TYPE)
             {
                 switch (id)
                 {
                     case POINT_FIRST_STEP:
                         me->SetWalk(false);
                         Talk(SAY_INTRO_HORDE_3);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_4, 6500, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_5, 15500, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_6, 29500, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_7, 43800, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_8, 47000, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_HORDE_9, 46700 + 1000 + 500, 0, PHASE_INTRO_H);
                         _events.ScheduleEvent(EVENT_INTRO_FINISH,  46700 + 1000 + 9000, 0, PHASE_INTRO_H);
                         break;
                     /*case POINT_CORPSE:
                         if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
{
                             deathbringer->CastSpell(me, SPELL_RIDE_VEHICLE, true);
                             deathbringer->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                             deathbringer->setDeathState(ALIVE);
                         }
                         _events.ScheduleEvent(EVENT_OUTRO_HORDE_4, 1000);
                         _events.ScheduleEvent(EVENT_OUTRO_HORDE_5, 4000);
                         break;
                     case POINT_FINAL:
                         if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                             deathbringer->DespawnOrUnsummon();
                         me->DespawnOrUnsummon();
                         break;*/
                     default:
                         break;
                 }
             }
         }
References _events, EVENT_INTRO_FINISH, EVENT_INTRO_HORDE_4, EVENT_INTRO_HORDE_5, EVENT_INTRO_HORDE_6, EVENT_INTRO_HORDE_7, EVENT_INTRO_HORDE_8, EVENT_INTRO_HORDE_9, ScriptedAI::me, PHASE_INTRO_H, POINT_FIRST_STEP, POINT_MOTION_TYPE, SAY_INTRO_HORDE_3, EventMap::ScheduleEvent(), Creature::SetWalk(), and CreatureAI::Talk().
Reset()
void npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 531 of file boss_deathbringer_saurfang.cpp.
         {
             _events.Reset();
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->SetReactState(REACT_PASSIVE);
         }
References _events, ScriptedAI::me, REACT_PASSIVE, EventMap::Reset(), Object::SetFlag(), Creature::SetReactState(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
SpellHit()
void npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 618 of file boss_deathbringer_saurfang.cpp.
         {
             if (spell->Id == SPELL_GRIP_OF_AGONY)
             {
                 me->SetDisableGravity(true);
                 me->GetMotionMaster()->MovePoint(POINT_CHOKE, chokePos[0]);
             }
         }
References chokePos, Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MovePoint(), POINT_CHOKE, Creature::SetDisableGravity(), and SPELL_GRIP_OF_AGONY.
UpdateAI()
void npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 665 of file boss_deathbringer_saurfang.cpp.
         {
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_INTRO_HORDE_2:
                     if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                         deathbringer->AI()->Talk(SAY_INTRO_HORDE_2);
                     break;
                 case EVENT_INTRO_HORDE_3:
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePoint(POINT_FIRST_STEP, firstStepPos.GetPositionX(), firstStepPos.GetPositionY(), firstStepPos.GetPositionZ());
                     break;
                 case EVENT_INTRO_HORDE_4:
                     if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                         deathbringer->AI()->Talk(SAY_INTRO_HORDE_4);
                     break;
                 case EVENT_INTRO_HORDE_5:
                     Talk(SAY_INTRO_HORDE_5);
                     break;
                 case EVENT_INTRO_HORDE_6:
                     Talk(SAY_INTRO_HORDE_6);
                     break;
                 case EVENT_INTRO_HORDE_7:
                     Talk(SAY_INTRO_HORDE_7);
                     break;
                 case EVENT_INTRO_HORDE_8:
                     Talk(SAY_INTRO_HORDE_8);
                     for (std::list<Creature*>::iterator itr = _guardList.begin(); itr != _guardList.end(); ++itr)
                         (*itr)->AI()->DoAction(ACTION_CHARGE);
                     me->GetMotionMaster()->MoveCharge(chargePos[0].GetPositionX(), chargePos[0].GetPositionY(), chargePos[0].GetPositionZ(), 8.5f, POINT_CHARGE);
                     break;
                 case EVENT_INTRO_HORDE_9:
                     if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                     {
                         deathbringer->AI()->DoCast(me, SPELL_GRIP_OF_AGONY);
                         deathbringer->AI()->Talk(SAY_INTRO_HORDE_9);
                     }
                     break;
                 case EVENT_INTRO_FINISH:
                     if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                     {
                         deathbringer->AI()->DoAction(ACTION_INTRO_DONE);
                         deathbringer->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                         if (Player* target = deathbringer->SelectNearestPlayer(100.0f))
                             deathbringer->AI()->AttackStart(target);
                     }
                     break;
                     /*case EVENT_OUTRO_HORDE_1:
                         if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
                             me->SetFacingToObject(deathbringer);
                         Talk(SAY_OUTRO_HORDE_2);
                         break;
                     case EVENT_OUTRO_HORDE_2:
                         Talk(SAY_OUTRO_HORDE_3);
                         break;
                     case EVENT_OUTRO_HORDE_3:
                         if (Creature* deathbringer = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_DEATHBRINGER_SAURFANG)))
{
                             float x, y, z;
                             deathbringer->GetClosePoint(x, y, z, deathbringer->GetObjectSize());
                             me->SetWalk(true);
                             me->GetMotionMaster()->MovePoint(POINT_CORPSE, x, y, z);
                         }
                         break;
                     case EVENT_OUTRO_HORDE_4:
                         me->GetMotionMaster()->MovePoint(POINT_FINAL, finalPos);
                         break;
                     case EVENT_OUTRO_HORDE_5:
                         Talk(SAY_OUTRO_HORDE_4);
                         break;*/
             }
         }
References _events, _guardList, _instance, ACTION_CHARGE, ACTION_INTRO_DONE, chargePos, DATA_DEATHBRINGER_SAURFANG, EVENT_INTRO_FINISH, EVENT_INTRO_HORDE_2, EVENT_INTRO_HORDE_3, EVENT_INTRO_HORDE_4, EVENT_INTRO_HORDE_5, EVENT_INTRO_HORDE_6, EVENT_INTRO_HORDE_7, EVENT_INTRO_HORDE_8, EVENT_INTRO_HORDE_9, EventMap::ExecuteEvent(), firstStepPos, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MovePoint(), POINT_CHARGE, POINT_FIRST_STEP, SAY_INTRO_HORDE_2, SAY_INTRO_HORDE_4, SAY_INTRO_HORDE_5, SAY_INTRO_HORDE_6, SAY_INTRO_HORDE_7, SAY_INTRO_HORDE_8, SAY_INTRO_HORDE_9, WorldObject::SelectNearestPlayer(), Creature::SetWalk(), SPELL_GRIP_OF_AGONY, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and EventMap::Update().
Member Data Documentation
_events
EventMap npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::_events private
Definition at line 743 of file boss_deathbringer_saurfang.cpp.
Referenced by DoAction(), MovementInform(), Reset(), and UpdateAI().
_guardList
std::list<Creature*> npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::_guardList private
Definition at line 745 of file boss_deathbringer_saurfang.cpp.
Referenced by DoAction(), and UpdateAI().
_instance
InstanceScript* npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::_instance private
Definition at line 744 of file boss_deathbringer_saurfang.cpp.
Referenced by DoAction(), npc_high_overlord_saurfangAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp