Azerotcore-wotlk: deps/mysqllite/mysys/my_fstream.c File Reference
my_fstream.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <errno.h>
#include <stdio.h>
Functions
size_t my_fread (FILE *stream, uchar *Buffer, size_t Count, myf MyFlags)
size_t my_fwrite (FILE *stream, const uchar *Buffer, size_t Count, myf MyFlags)
my_off_t my_fseek (FILE *stream, my_off_t pos, int whence, myf MyFlags __attribute__((unused)))
my_off_t my_ftell (FILE *stream, myf MyFlags __attribute__((unused)))
int my_fileno (FILE *f)
Function Documentation
my_fileno()
int my_fileno (FILE * f)
Definition at line 187 of file my_fstream.c.
 {
 #ifdef _WIN32
   return my_win_fileno(f);
 #else
  return fileno(f);
 #endif
 }
References f().
Referenced by my_fclose(), my_fopen(), my_fread(), and my_fwrite().
my_fread()
size_t my_fread (FILE * stream, uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 45 of file my_fstream.c.
 {
   size_t readbytes;
   DBUG_ENTER("my_fread");
   DBUG_PRINT("my",("stream: 0x%lx  Buffer: 0x%lx  Count: %u  MyFlags: %d",
            (long) stream, (long) Buffer, (uint) Count, MyFlags));
   if ((readbytes= fread(Buffer, sizeof(char), Count, stream)) != Count)
   {
     DBUG_PRINT("error",("Read only %d bytes", (int) readbytes));
     if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
     {
       if (ferror(stream))
     my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
          my_filename(my_fileno(stream)),errno);
       else
       if (MyFlags & (MY_NABP | MY_FNABP))
     my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
          my_filename(my_fileno(stream)),errno);
     }
     my_errno=errno ? errno : -1;
     if (ferror(stream) || MyFlags & (MY_NABP | MY_FNABP))
       DBUG_RETURN((size_t) -1);         /* Return with error */
   }
   if (MyFlags & (MY_NABP | MY_FNABP))
     DBUG_RETURN(0);             /* Read ok */
   DBUG_RETURN(readbytes);
 } /* my_fread */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_filename(), my_fileno(), MY_FNABP, MY_NABP, MY_WME, and MYF.
Referenced by inline_mysql_file_fread().
my_fseek()
my_off_t my_fseek (FILE * stream, my_off_t pos, int whence, myf MyFlags __attribute__(unused))
Definition at line 162 of file my_fstream.c.
 {
   DBUG_ENTER("my_fseek");
   DBUG_PRINT("my",("stream: 0x%lx  pos: %lu  whence: %d  MyFlags: %d",
                    (long) stream, (long) pos, whence, MyFlags));
   DBUG_RETURN(fseek(stream, (off_t) pos, whence) ?
           MY_FILEPOS_ERROR : (my_off_t) ftell(stream));
 } /* my_seek */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, MY_FILEPOS_ERROR, mpq::off_t, and pos().
Referenced by my_fwrite().
my_ftell()
my_off_t my_ftell (FILE * stream, myf MyFlags __attribute__(unused))
Definition at line 175 of file my_fstream.c.
 {
   off_t pos;
   DBUG_ENTER("my_ftell");
   DBUG_PRINT("my",("stream: 0x%lx  MyFlags: %d", (long) stream, MyFlags));
   pos=ftell(stream);
   DBUG_PRINT("exit",("ftell: %lu",(ulong) pos));
   DBUG_RETURN((my_off_t) pos);
 } /* my_ftell */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, mpq::off_t, and pos().
my_fwrite()
size_t my_fwrite (FILE * stream, const uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 89 of file my_fstream.c.
 {
   size_t writtenbytes =0;
   my_off_t seekptr;
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
   uint errors;
 #endif
   DBUG_ENTER("my_fwrite");
   DBUG_PRINT("my",("stream: 0x%lx  Buffer: 0x%lx  Count: %u  MyFlags: %d",
            (long) stream, (long) Buffer, (uint) Count, MyFlags));
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
   errors=0;
 #endif
   seekptr= ftell(stream);
   for (;;)
   {
     size_t written;
     if ((written = (size_t) fwrite((char*) Buffer,sizeof(char),
                                    Count, stream)) != Count)
     {
       DBUG_PRINT("error",("Write only %d bytes", (int) writtenbytes));
       my_errno=errno;
       if (written != (size_t) -1)
       {
     seekptr+=written;
     Buffer+=written;
     writtenbytes+=written;
     Count-=written;
       }
 #ifdef EINTR
       if (errno == EINTR)
       {
     (void) my_fseek(stream,seekptr,MY_SEEK_SET,MYF(0));
     continue;
       }
 #endif
 #if !defined(NO_BACKGROUND) && defined(USE_MY_STREAM)
       if (my_thread_var->abort)
     MyFlags&= ~ MY_WAIT_IF_FULL;        /* End if aborted by user */
       if ((errno == ENOSPC || errno == EDQUOT) &&
           (MyFlags & MY_WAIT_IF_FULL))
       {
         wait_for_free_space("[stream]", errors);
         errors++;
         (void) my_fseek(stream,seekptr,MY_SEEK_SET,MYF(0));
         continue;
       }
 #endif
       if (ferror(stream) || (MyFlags & (MY_NABP | MY_FNABP)))
       {
     if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
     {
       my_error(EE_WRITE, MYF(ME_BELL+ME_WAITTANG),
            my_filename(my_fileno(stream)),errno);
     }
     writtenbytes= (size_t) -1;        /* Return that we got error */
     break;
       }
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       writtenbytes= 0;              /* Everything OK */
     else
       writtenbytes+= written;
     break;
   }
   DBUG_RETURN(writtenbytes);
 } /* my_fwrite */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EDQUOT, EE_WRITE, errno, mpq::errors, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_filename(), my_fileno(), MY_FNABP, my_fseek(), MY_NABP, MY_SEEK_SET, my_thread_var, MY_WAIT_IF_FULL, MY_WME, MYF, and wait_for_free_space().
Referenced by inline_mysql_file_fwrite(), and my_b_copy_to_file().