Azerotcore-wotlk: ThreatContainer Class Reference
ThreatContainer Class Reference
#include <ThreatMgr.h>
Public Types
typedef std::list< HostileReference * > StorageType
Public Member Functions
ThreatContainer ()
~ThreatContainer ()
HostileReference * addThreat (Unit *victim, float threat)
void modifyThreatPercent (Unit *victim, int32 percent)
HostileReference * selectNextVictim (Creature *attacker, HostileReference *currentVictim) const
void setDirty (bool isDirty)
bool isDirty () const
bool empty () const
HostileReference * getMostHated () const
HostileReference * getReferenceByTarget (Unit *victim) const
StorageType const & getThreatList () const
Private Member Functions
void remove (HostileReference *hostileRef)
void addReference (HostileReference *hostileRef)
void clearReferences ()
void update ()
Private Attributes
StorageType iThreatList
bool iDirty {false}
Friends
class ThreatMgr
Detailed Description
Definition at line 134 of file ThreatMgr.h.
Member Typedef Documentation
StorageType
typedef std::list<HostileReference*> ThreatContainer::StorageType
Definition at line 139 of file ThreatMgr.h.
Constructor & Destructor Documentation
ThreatContainer()
ThreatContainer::ThreatContainer () inline
Definition at line 141 of file ThreatMgr.h.
 { }
~ThreatContainer()
ThreatContainer::~ThreatContainer () inline
Definition at line 143 of file ThreatMgr.h.
 { clearReferences(); }
References clearReferences().
Member Function Documentation
addReference()
void ThreatContainer::addReference (HostileReference * hostileRef) inline private
Definition at line 175 of file ThreatMgr.h.
     {
         iThreatList.push_back(hostileRef);
     }
References iThreatList.
Referenced by ThreatMgr::_addThreat(), and ThreatMgr::processThreatEvent().
addThreat()
HostileReference * ThreatContainer::addThreat (Unit * victim, float threat)
Definition at line 278 of file ThreatMgr.cpp.
 {
     HostileReference* ref = getReferenceByTarget(victim);
     if (ref)
         ref->addThreat(threat);
     return ref;
 }
References HostileReference::addThreat(), and getReferenceByTarget().
Referenced by ThreatMgr::_addThreat().
clearReferences()
void ThreatContainer::clearReferences () private
Definition at line 246 of file ThreatMgr.cpp.
 {
     for (ThreatContainer::StorageType::const_iterator i = iThreatList.begin(); i != iThreatList.end(); ++i)
     {
         (*i)->unlink();
         delete (*i);
     }
     iThreatList.clear();
 }
References iThreatList.
Referenced by ThreatMgr::clearReferences(), and ~ThreatContainer().
empty()
bool ThreatContainer::empty () const inline
Definition at line 155 of file ThreatMgr.h.
     {
         return iThreatList.empty();
     }
References iThreatList.
Referenced by ThreatMgr::areThreatListsEmpty(), Spell::EffectTaunt(), and ThreatMgr::isThreatListEmpty().
getMostHated()
HostileReference* ThreatContainer::getMostHated () const inline
Definition at line 160 of file ThreatMgr.h.
     {
         return iThreatList.empty() ? nullptr : iThreatList.front();
     }
References iThreatList.
Referenced by Spell::EffectTaunt().
getReferenceByTarget()
HostileReference * ThreatContainer::getReferenceByTarget (Unit * victim) const
Definition at line 259 of file ThreatMgr.cpp.
 {
     if (!victim)
         return nullptr;
     ObjectGuid const guid = victim->GetGUID();
     for (ThreatContainer::StorageType::const_iterator i = iThreatList.begin(); i != iThreatList.end(); ++i)
     {
         HostileReference* ref = (*i);
         if (ref && ref->getUnitGuid() == guid)
             return ref;
     }
     return nullptr;
 }
References Object::GetGUID(), HostileReference::getUnitGuid(), and iThreatList.
Referenced by addThreat(), Spell::EffectTaunt(), ThreatMgr::getThreat(), ThreatMgr::getThreatWithoutTemp(), modifyThreatPercent(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), ThreatMgr::tauntApply(), and ThreatMgr::tauntFadeOut().
getThreatList()
StorageType const& ThreatContainer::getThreatList () const inline
Definition at line 167 of file ThreatMgr.h.
 { return iThreatList; }
References iThreatList.
Referenced by ThreatMgr::getOfflineThreatList(), and ThreatMgr::getThreatList().
isDirty()
bool ThreatContainer::isDirty () const inline
Definition at line 153 of file ThreatMgr.h.
 { return iDirty; }
References iDirty.
Referenced by setDirty().
modifyThreatPercent()
void ThreatContainer::modifyThreatPercent (Unit * victim, int32 percent)
Definition at line 288 of file ThreatMgr.cpp.
 {
     if (HostileReference* ref = getReferenceByTarget(victim))
         ref->addThreatPercent(percent);
 }
References getReferenceByTarget().
Referenced by ThreatMgr::modifyThreatPercent().
remove()
void ThreatContainer::remove (HostileReference * hostileRef) inline private
Definition at line 170 of file ThreatMgr.h.
     {
         iThreatList.remove(hostileRef);
     }
References iThreatList.
Referenced by ThreatMgr::processThreatEvent().
selectNextVictim()
HostileReference * ThreatContainer::selectNextVictim (Creature * attacker, HostileReference * currentVictim) const
Definition at line 309 of file ThreatMgr.cpp.
 {
     // pussywizard: pretty much remade this whole function
     HostileReference* currentRef = nullptr;
     bool found = false;
     bool noPriorityTargetFound = false;
     // pussywizard: currentVictim is needed to compare if threat was exceeded by 10%/30% for melee/range targets (only then switching current target)
     if (currentVictim)
     {
         Unit* cvUnit = currentVictim->getTarget();
         if (!attacker->_CanDetectFeignDeathOf(cvUnit) || !attacker->CanCreatureAttack(cvUnit)) // pussywizard: if currentVictim is not valid => don't compare the threat with it, just take the highest threat valid target
             currentVictim = nullptr;
         else if (cvUnit->IsImmunedToDamageOrSchool(attacker->GetMeleeDamageSchoolMask()) || cvUnit->HasNegativeAuraWithInterruptFlag(AURA_INTERRUPT_FLAG_TAKE_DAMAGE)) // pussywizard: no 10%/30% if currentVictim is immune to damage or has auras breakable by damage
             currentVictim = nullptr;
     }
     ThreatContainer::StorageType::const_iterator lastRef = iThreatList.end();
     --lastRef;
     // pussywizard: iterate from highest to lowest threat
     for (ThreatContainer::StorageType::const_iterator iter = iThreatList.begin(); iter != iThreatList.end() && !found;)
     {
         currentRef = (*iter);
         Unit* target = currentRef->getTarget();
         ASSERT(target); // if the ref has status online the target must be there !
         // pussywizard: don't go to threat comparison if this ref is immune to damage or has aura breakable on damage (second choice target)
         // pussywizard: if this is the last entry on the threat list, then all targets are second choice, set bool to true and loop threat list again, ignoring this section
         if (!noPriorityTargetFound && (target->IsImmunedToDamageOrSchool(attacker->GetMeleeDamageSchoolMask()) || target->HasNegativeAuraWithInterruptFlag(AURA_INTERRUPT_FLAG_TAKE_DAMAGE) || target->HasAuraTypeWithCaster(SPELL_AURA_IGNORED, attacker->GetGUID())))
         {
             if (iter != lastRef)
             {
                 ++iter;
                 continue;
             }
             else
             {
                 noPriorityTargetFound = true;
                 iter = iThreatList.begin();
                 continue;
             }
         }
         // pussywizard: skip not valid targets
         if (attacker->_CanDetectFeignDeathOf(target) && attacker->CanCreatureAttack(target))
         {
             if (currentVictim) // pussywizard: if not nullptr then target must have 10%/30% more threat
             {
                 if (currentVictim == currentRef) // pussywizard: nothing found previously was good and enough, currentRef passed all necessary tests, so end now
                 {
                     found = true;
                     break;
                 }
                 // pussywizard: implement 110% threat rule for targets in melee range and 130% rule for targets in ranged distances
                 if (currentRef->getThreat() > 1.3f * currentVictim->getThreat()) // pussywizard: enough in all cases, end
                 {
                     found = true;
                     break;
                 }
                 else if (currentRef->getThreat() > 1.1f * currentVictim->getThreat()) // pussywizard: enought only if target in melee range
                 {
                     if (attacker->IsWithinMeleeRange(target))
                     {
                         found = true;
                         break;
                     }
                 }
                 else // pussywizard: nothing found previously was good and enough, this and next entries on the list have less than 110% threat, and currentVictim is present and valid as checked before the loop (otherwise it's nullptr), so end now
                 {
                     currentRef = currentVictim;
                     found = true;
                     break;
                 }
             }
             else // pussywizard: no currentVictim, first passing all checks is chosen (highest threat, list is sorted)
             {
                 found = true;
                 break;
             }
         }
         ++iter;
     }
     if (!found)
         currentRef = nullptr;
     return currentRef;
 }
References Creature::_CanDetectFeignDeathOf(), ASSERT, AURA_INTERRUPT_FLAG_TAKE_DAMAGE, Creature::CanCreatureAttack(), Object::GetGUID(), Creature::GetMeleeDamageSchoolMask(), Reference< TO, FROM >::getTarget(), HostileReference::getThreat(), Unit::HasAuraTypeWithCaster(), Unit::HasNegativeAuraWithInterruptFlag(), Unit::IsImmunedToDamageOrSchool(), Unit::IsWithinMeleeRange(), iThreatList, and SPELL_AURA_IGNORED.
Referenced by ThreatMgr::getHostilTarget().
setDirty()
void ThreatContainer::setDirty (bool isDirty) inline
Definition at line 151 of file ThreatMgr.h.
 { iDirty = isDirty; }
References iDirty, and isDirty().
Referenced by ThreatMgr::setDirty().
update()
void ThreatContainer::update () private
Definition at line 297 of file ThreatMgr.cpp.
 {
     if (iDirty && iThreatList.size() > 1)
         iThreatList.sort(Acore::ThreatOrderPred());
     iDirty = false;
 }
References iDirty, and iThreatList.
Referenced by ThreatMgr::getHostilTarget().
Friends And Related Function Documentation
ThreatMgr
friend class ThreatMgr friend
Definition at line 136 of file ThreatMgr.h.
Member Data Documentation
iDirty
bool ThreatContainer::iDirty {false} private
Definition at line 186 of file ThreatMgr.h.
Referenced by isDirty(), setDirty(), and update().
iThreatList
StorageType ThreatContainer::iThreatList private
Definition at line 185 of file ThreatMgr.h.
Referenced by addReference(), clearReferences(), empty(), getMostHated(), getReferenceByTarget(), getThreatList(), remove(), ThreatMgr::resetAggro(), ThreatMgr::resetAllAggro(), selectNextVictim(), and update().
The documentation for this class was generated from the following files:
src/server/game/Combat/ThreatMgr.h
src/server/game/Combat/ThreatMgr.cpp