Azerotcore-wotlk: spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript Class Reference
spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_midsummer_juggling_torch_SpellScript)
bool Load () override
void HandleFinish ()
void HandleDummy (SpellEffIndex effIndex)
void Register () override
Private Attributes
bool handled
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 530 of file midsummer.cpp.
Member Function Documentation
HandleDummy()
void spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::HandleDummy (SpellEffIndex effIndex) inline private
Definition at line 557 of file midsummer.cpp.
         {
             PreventHitDefaultEffect(effIndex);
             Unit* caster = GetCaster();
             if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (Player* target = GetHitPlayer())
                 if (!handled && target->GetQuestRewardStatus(target->GetTeamId() == TEAM_ALLIANCE ? 11657 : 11923))
                 {
                     handled = true;
                     caster->CastSpell(target, SPELL_GIVE_TORCH, true);
                 }
         }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetHitPlayer(), Object::GetTypeId(), handled, SpellScript::PreventHitDefaultEffect(), SPELL_GIVE_TORCH, TEAM_ALLIANCE, and TYPEID_PLAYER.
Referenced by Register().
HandleFinish()
void spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::HandleFinish () inline private
Definition at line 536 of file midsummer.cpp.
         {
             Unit* caster = GetCaster();
             if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (const WorldLocation* loc = GetExplTargetDest())
             {
                 if (loc->GetExactDist(caster) < 3.0f)
                     caster->CastSpell(loc->GetPositionX(), loc->GetPositionY(), loc->GetPositionZ(), SPELL_JUGGLE_SELF, true);
                 else if (loc->GetExactDist(caster) < 10.0f)
                     caster->CastSpell(loc->GetPositionX(), loc->GetPositionY(), loc->GetPositionZ(), SPELL_JUGGLE_SLOW, true);
                 else if (loc->GetExactDist(caster) < 25.0f)
                     caster->CastSpell(loc->GetPositionX(), loc->GetPositionY(), loc->GetPositionZ(), SPELL_JUGGLE_MED, true);
                 else
                     caster->CastSpell(loc->GetPositionX(), loc->GetPositionY(), loc->GetPositionZ(), SPELL_JUGGLE_FAST, true);
             }
             else
                 caster->CastSpell(caster, SPELL_JUGGLE_SELF, true);
         }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetExplTargetDest(), Object::GetTypeId(), SPELL_JUGGLE_FAST, SPELL_JUGGLE_MED, SPELL_JUGGLE_SELF, SPELL_JUGGLE_SLOW, and TYPEID_PLAYER.
Referenced by Register().
Load()
bool spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 535 of file midsummer.cpp.
 { handled = false; return true; }
References handled.
PrepareSpellScript()
spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::PrepareSpellScript (spell_midsummer_juggling_torch_SpellScript) private
Register()
void spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 572 of file midsummer.cpp.
         {
             if (m_scriptSpellId == SPELL_TORCH_CHECK)
                 OnEffectHitTarget += SpellEffectFn(spell_midsummer_juggling_torch_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
             else
                 AfterCast += SpellCastFn(spell_midsummer_juggling_torch_SpellScript::HandleFinish);
         }
References SpellScript::AfterCast, EFFECT_0, HandleDummy(), HandleFinish(), _SpellScript::m_scriptSpellId, SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, SPELL_TORCH_CHECK, SpellCastFn, and SpellEffectFn.
Member Data Documentation
handled
bool spell_midsummer_juggling_torch::spell_midsummer_juggling_torch_SpellScript::handled private
Definition at line 534 of file midsummer.cpp.
Referenced by HandleDummy(), and Load().
The documentation for this class was generated from the following file:
src/server/scripts/Events/midsummer.cpp