Azerotcore-wotlk: WDTFile Class Reference
WDTFile Class Reference
#include <wdtfile.h>
Public Member Functions
WDTFile (char *file_name, char *file_name1)
~WDTFile (void)
bool init (uint32 mapId)
ADTFile * GetMap (int x, int z)
Public Attributes
std::vector< std::string > _wmoNames
Private Attributes
MPQFile _file
std::string filename
Detailed Description
Definition at line 28 of file wdtfile.h.
Constructor & Destructor Documentation
WDTFile()
WDTFile::WDTFile (char * file_name, char * file_name1)
Definition at line 33 of file wdtfile.cpp.
                                                   : _file(file_name)
 {
     filename.append(file_name1, strlen(file_name1));
 }
References filename.
~WDTFile()
WDTFile::~WDTFile (void)
Definition at line 117 of file wdtfile.cpp.
 {
     _file.close();
 }
References _file, and MPQFile::close().
Member Function Documentation
GetMap()
ADTFile * WDTFile::GetMap (int x, int z)
Definition at line 122 of file wdtfile.cpp.
 {
     if (!(x >= 0 && z >= 0 && x < 64 && z < 64))
         return nullptr;
     char name[512];
     snprintf(name, sizeof(name), R"(World\Maps\%s\%s_%d_%d.adt)", filename.c_str(), filename.c_str(), x, z);
     return new ADTFile(name);
 }
References filename, name, G3D::x, and G3D::z.
init()
bool WDTFile::init (uint32 mapId)
Definition at line 38 of file wdtfile.cpp.
 {
     if (_file.isEof())
     {
         //printf("Can't find WDT file.\n");
         return false;
     }
     char fourcc[5];
     uint32 size;
     std::string dirname = std::string(szWorkDirWmo) + "/dir_bin";
     FILE* dirfile;
     dirfile = fopen(dirname.c_str(), "ab");
     if (!dirfile)
     {
         printf("Can't open dirfile!'%s'\n", dirname.c_str());
         return false;
     }
     while (!_file.isEof())
     {
         _file.read(fourcc, 4);
         _file.read(&size, 4);
         flipcc(fourcc);
         fourcc[4] = 0;
         size_t nextpos = _file.getPos() + size;
         if (!strcmp(fourcc, "MAIN"))
         {
         }
         if (!strcmp(fourcc, "MWMO"))
         {
             // global map objects
             if (size)
             {
                 char* buf = new char[size];
                 _file.read(buf, size);
                 char* p = buf;
                 while (p < buf + size)
                 {
                     std::string path(p);
                     char* s = wdtGetPlainName(p);
                     fixnamen(s, strlen(s));
                     fixname2(s, strlen(s));
                     p = p + strlen(p) + 1;
                     _wmoNames.push_back(s);
                     ExtractSingleWmo(path);
                 }
                 delete[] buf;
             }
         }
         else if (!strcmp(fourcc, "MODF"))
         {
             // global wmo instance data
             if (size)
             {
                 uint32 mapObjectCount = size / sizeof(ADT::MODF);
                 for (uint32 i = 0; i < mapObjectCount; ++i)
                 {
                     ADT::MODF mapObjDef;
                     _file.read(&mapObjDef, sizeof(ADT::MODF));
                     MapObject::Extract(mapObjDef, _wmoNames[mapObjDef.Id].c_str(), mapId, 65, 65, dirfile);
                     Doodad::ExtractSet(WmoDoodads[_wmoNames[mapObjDef.Id]], mapObjDef, mapId, 65, 65, dirfile);
                 }
             }
         }
         _file.seek((int)nextpos);
     }
     _file.close();
     fclose(dirfile);
     return true;
 }
References _file, _wmoNames, MPQFile::close(), MapObject::Extract(), Doodad::ExtractSet(), ExtractSingleWmo(), fixname2(), fixnamen(), flipcc(), MPQFile::getPos(), ADT::MODF::Id, MPQFile::isEof(), printf(), MPQFile::read(), MPQFile::seek(), szWorkDirWmo, wdtGetPlainName(), and WmoDoodads.
Member Data Documentation
_file
MPQFile WDTFile::_file private
Definition at line 40 of file wdtfile.h.
Referenced by mpq.Reader::__del__(), mpq.Reader::__repr__(), mpq.Reader::_read_block(), init(), mpq.Reader::read(), mpq.Reader::seek(), and ~WDTFile().
_wmoNames
std::vector<std::string> WDTFile::_wmoNames
Definition at line 37 of file wdtfile.h.
Referenced by init().
filename
std::string WDTFile::filename private
Definition at line 41 of file wdtfile.h.
Referenced by GetMap(), and WDTFile().
The documentation for this class was generated from the following files:
src/tools/vmap4_extractor/wdtfile.h
src/tools/vmap4_extractor/wdtfile.cpp