Azerotcore-wotlk: npc_gunship_boarding_addAI Struct Reference
npc_gunship_boarding_addAI Struct Reference
Public Member Functions
npc_gunship_boarding_addAI (Creature *creature)
void SetData (uint32 type, uint32 data) override
void EnterEvadeMode () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 pointId) override
void UpdateAI (uint32 diff) override
bool CanAIAttack (const Unit *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Member Functions
void SetSlotInfo (uint32 index)
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes
bool anyValid
uint16 checkTimer
bool _usedDesperateResolve
InstanceScript * Instance
SlotInfo const * Slot
uint32 Index
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Definition at line 1533 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
npc_gunship_boarding_addAI()
npc_gunship_boarding_addAI::npc_gunship_boarding_addAI (Creature * creature) inline
Definition at line 1535 of file boss_icecrown_gunship_battle.cpp.
                                                    : ScriptedAI(creature), Instance(creature->GetInstanceScript()), Slot(nullptr), Index(uint32(-1))
     {
         anyValid = true;
         checkTimer = 1000;
         _usedDesperateResolve = false;
         me->m_CombatDistance = 70.0f;
         me->SetRegeneratingHealth(false);
     }
References _usedDesperateResolve, anyValid, checkTimer, Creature::m_CombatDistance, ScriptedAI::me, and Creature::SetRegeneratingHealth().
Member Function Documentation
CanAIAttack()
bool npc_gunship_boarding_addAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1628 of file boss_icecrown_gunship_battle.cpp.
     {
         return Instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS && target->GetTransport() && target->GetTransport() != me->GetTransport() && target->GetPositionZ() < 478.0f && (me->GetEntry() == NPC_SKYBREAKER_SERGEANT || me->GetEntry() == NPC_SKYBREAKER_MARINE ? (target->GetPositionY() < 2431.0f) : (target->GetPositionY() > 2042.0f));
     }
References DATA_ICECROWN_GUNSHIP_BATTLE, InstanceScript::GetBossState(), Object::GetEntry(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::GetTransport(), IN_PROGRESS, Instance, ScriptedAI::me, NPC_SKYBREAKER_MARINE, and NPC_SKYBREAKER_SERGEANT.
Referenced by UpdateAI().
DamageTaken()
void npc_gunship_boarding_addAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1564 of file boss_icecrown_gunship_battle.cpp.
     {
         if (_usedDesperateResolve)
             return;
         if (!me->HealthBelowPctDamaged(25, damage))
             return;
         _usedDesperateResolve = true;
         me->CastSpell(me, SPELL_DESPERATE_RESOLVE, true);
     }
References _usedDesperateResolve, Unit::CastSpell(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, and SPELL_DESPERATE_RESOLVE.
EnterEvadeMode()
void npc_gunship_boarding_addAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1554 of file boss_icecrown_gunship_battle.cpp.
     {
         if (!me->IsAlive() || !me->IsInCombat())
             return;
         me->DeleteThreatList();
         me->CombatStop(true);
         me->GetMotionMaster()->MoveTargetedHome();
         Reset();
     }
References Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), Unit::IsAlive(), Unit::IsInCombat(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), and ScriptedAI::Reset().
MovementInform()
void npc_gunship_boarding_addAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1574 of file boss_icecrown_gunship_battle.cpp.
     {
         if (type == POINT_MOTION_TYPE && pointId == EVENT_CHARGE_PREPATH && Slot)
         {
             me->SetFacingTo(Slot->TargetPosition.GetOrientation());
             me->m_Events.AddEvent(new BattleExperienceEvent(me), me->m_Events.CalculateTime(BattleExperienceEvent::ExperiencedTimes[0]));
             me->CastSpell(me, SPELL_BATTLE_EXPERIENCE, true);
             me->SetReactState(REACT_AGGRESSIVE);
             Position const& otherTransportPos = Instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? OrgrimsHammerTeleportExit : SkybreakerTeleportExit;
             float x, y, z, o;
             otherTransportPos.GetPosition(x, y, z, o);
             Transport* myTransport = me->GetTransport();
             if (!myTransport)
                 return;
             if (Transport* transport = Instance->instance->GetTransport(Instance->GetGuidData(DATA_ICECROWN_GUNSHIP_BATTLE)))
                 if (Transport* destTransport = transport->ToTransport())
                     destTransport->CalculatePassengerPosition(x, y, z, &o);
             float angle = frand(0, M_PI * 2.0f);
             x += 2.0f * std::cos(angle);
             y += 2.0f * std::sin(angle);
             me->SetHomePosition(x, y, z, o);
             myTransport->CalculatePassengerOffset(x, y, z, &o);
             me->SetTransportHomePosition(x, y, z, o);
             me->CastSpell(me, SPELL_TELEPORT_TO_ENEMY_SHIP, true);
         }
     }
References EventProcessor::AddEvent(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), EventProcessor::CalculateTime(), Unit::CastSpell(), DATA_ICECROWN_GUNSHIP_BATTLE, DATA_TEAMID_IN_INSTANCE, EVENT_CHARGE_PREPATH, BattleExperienceEvent::ExperiencedTimes, frand(), ZoneScript::GetData(), InstanceScript::GetGuidData(), Position::GetOrientation(), Position::GetPosition(), WorldObject::GetTransport(), Map::GetTransport(), InstanceScript::instance, Instance, Unit::m_Events, ScriptedAI::me, OrgrimsHammerTeleportExit, POINT_MOTION_TYPE, REACT_AGGRESSIVE, Unit::SetFacingTo(), Creature::SetHomePosition(), Creature::SetReactState(), Creature::SetTransportHomePosition(), SkybreakerTeleportExit, Slot, SPELL_BATTLE_EXPERIENCE, SPELL_TELEPORT_TO_ENEMY_SHIP, SlotInfo::TargetPosition, TEAM_HORDE, and GameObject::ToTransport().
SetData()
void npc_gunship_boarding_addAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 1544 of file boss_icecrown_gunship_battle.cpp.
     {
         if (type == ACTION_SET_SLOT)
         {
             SetSlotInfo(data);
             me->SetReactState(REACT_PASSIVE);
             me->m_Events.AddEvent(new DelayedMovementEvent(me, Slot->TargetPosition), me->m_Events.CalculateTime(3000 * (Index - SLOT_MARINE_1)));
         }
     }
References ACTION_SET_SLOT, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Index, Unit::m_Events, ScriptedAI::me, REACT_PASSIVE, Creature::SetReactState(), SetSlotInfo(), Slot, SLOT_MARINE_1, and SlotInfo::TargetPosition.
SetSlotInfo()
void npc_gunship_boarding_addAI::SetSlotInfo (uint32 index) inline protected
Definition at line 1634 of file boss_icecrown_gunship_battle.cpp.
     {
         Index = index;
         Slot = &((Instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? SkybreakerSlotInfo : OrgrimsHammerSlotInfo)[Index]);
     }
References DATA_TEAMID_IN_INSTANCE, ZoneScript::GetData(), Index, Instance, OrgrimsHammerSlotInfo, SkybreakerSlotInfo, Slot, and TEAM_HORDE.
Referenced by SetData().
UpdateAI()
void npc_gunship_boarding_addAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_gunship_boarding_add::npc_gunship_boarding_add_realAI, and npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI.
Definition at line 1607 of file boss_icecrown_gunship_battle.cpp.
     {
         if (checkTimer <= diff)
         {
             checkTimer = 1000;
             anyValid = false;
             Map::PlayerList const& pl = me->GetMap()->GetPlayers();
             for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                 if (Player* p = itr->GetSource())
                     if (CanAIAttack(p) && me->IsValidAttackTarget(p))
                     {
                         anyValid = true;
                         me->SetInCombatWith(p);
                         p->SetInCombatWith(me);
                         me->AddThreat(p, 0.0f);
                     }
         }
         else
             checkTimer -= diff;
     }
References Unit::AddThreat(), anyValid, MapRefMgr::begin(), CanAIAttack(), checkTimer, MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), Unit::IsValidAttackTarget(), ScriptedAI::me, and Unit::SetInCombatWith().
Referenced by npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), and npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI().
Member Data Documentation
_usedDesperateResolve
bool npc_gunship_boarding_addAI::_usedDesperateResolve protected
Definition at line 1642 of file boss_icecrown_gunship_battle.cpp.
Referenced by DamageTaken(), and npc_gunship_boarding_addAI().
anyValid
bool npc_gunship_boarding_addAI::anyValid protected
Definition at line 1640 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_gunship_boarding_addAI(), UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), and npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI().
checkTimer
uint16 npc_gunship_boarding_addAI::checkTimer protected
Definition at line 1641 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_gunship_boarding_addAI(), and UpdateAI().
Index
uint32 npc_gunship_boarding_addAI::Index protected
Definition at line 1645 of file boss_icecrown_gunship_battle.cpp.
Referenced by SetData(), and SetSlotInfo().
Instance
InstanceScript* npc_gunship_boarding_addAI::Instance protected
Definition at line 1643 of file boss_icecrown_gunship_battle.cpp.
Referenced by CanAIAttack(), MovementInform(), SetSlotInfo(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), and npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI().
Slot
SlotInfo const* npc_gunship_boarding_addAI::Slot protected
Definition at line 1644 of file boss_icecrown_gunship_battle.cpp.
Referenced by MovementInform(), SetData(), and SetSlotInfo().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp