Azerotcore-wotlk: Channel::PlayerInfo Struct Reference
Channel::PlayerInfo Struct Reference
Public Member Functions
bool HasFlag (uint8 flag) const
void SetFlag (uint8 flag)
bool IsOwner () const
void SetOwner (bool state)
bool IsOwnerGM () const
void SetOwnerGM (bool on)
bool IsModerator () const
void SetModerator (bool state)
bool IsMuted () const
void SetMuted (bool state)
bool IsAllowedToSpeak (uint64 speakDelay)
Public Attributes
ObjectGuid player
uint8 flags
uint64 lastSpeakTime
Player * plrPtr
Private Attributes
bool _gmStatus = false
Detailed Description
Definition at line 148 of file Channel.h.
Member Function Documentation
HasFlag()
bool Channel::PlayerInfo::HasFlag (uint8 flag) const inline
Definition at line 155 of file Channel.h.
 { return flags & flag; }
References flags.
Referenced by SetFlag().
IsAllowedToSpeak()
bool Channel::PlayerInfo::IsAllowedToSpeak (uint64 speakDelay) inline
Definition at line 177 of file Channel.h.
         {
             if (lastSpeakTime + speakDelay <= static_cast<uint64>(sWorld->GetGameTime()))
             {
                 lastSpeakTime = sWorld->GetGameTime();
                 return true;
             }
             else
                 return false;
         }
References lastSpeakTime, and sWorld.
Referenced by Channel::Say().
IsModerator()
bool Channel::PlayerInfo::IsModerator () const inline
Definition at line 165 of file Channel.h.
 { return flags & MEMBER_FLAG_MODERATOR; }
References flags, and MEMBER_FLAG_MODERATOR.
Referenced by Channel::Say(), and Channel::SetModerator().
IsMuted()
bool Channel::PlayerInfo::IsMuted () const inline
Definition at line 171 of file Channel.h.
 { return flags & MEMBER_FLAG_MUTED; }
References flags, and MEMBER_FLAG_MUTED.
Referenced by Channel::Say(), and Channel::SetMute().
IsOwner()
bool Channel::PlayerInfo::IsOwner () const inline
Definition at line 157 of file Channel.h.
 { return flags & MEMBER_FLAG_OWNER; }
References flags, and MEMBER_FLAG_OWNER.
IsOwnerGM()
bool Channel::PlayerInfo::IsOwnerGM () const inline
Definition at line 163 of file Channel.h.
 { return _gmStatus; }
References _gmStatus.
SetFlag()
void Channel::PlayerInfo::SetFlag (uint8 flag) inline
Definition at line 156 of file Channel.h.
 { if (!HasFlag(flag)) flags |= flag; }
References flags, and HasFlag().
SetModerator()
void Channel::PlayerInfo::SetModerator (bool state) inline
Definition at line 166 of file Channel.h.
         {
             if (state) flags |= MEMBER_FLAG_MODERATOR;
             else flags &= ~MEMBER_FLAG_MODERATOR;
         }
References flags, and MEMBER_FLAG_MODERATOR.
Referenced by Channel::SetModerator(), and Channel::SetOwner().
SetMuted()
void Channel::PlayerInfo::SetMuted (bool state) inline
Definition at line 172 of file Channel.h.
         {
             if (state) flags |= MEMBER_FLAG_MUTED;
             else flags &= ~MEMBER_FLAG_MUTED;
         }
References flags, and MEMBER_FLAG_MUTED.
Referenced by Channel::SetMute().
SetOwner()
void Channel::PlayerInfo::SetOwner (bool state) inline
Definition at line 158 of file Channel.h.
         {
             if (state) flags |= MEMBER_FLAG_OWNER;
             else flags &= ~MEMBER_FLAG_OWNER;
         }
References flags, and MEMBER_FLAG_OWNER.
Referenced by Channel::SetOwner().
SetOwnerGM()
void Channel::PlayerInfo::SetOwnerGM (bool on) inline
Definition at line 164 of file Channel.h.
 { _gmStatus = on; }
References _gmStatus.
Member Data Documentation
_gmStatus
bool Channel::PlayerInfo::_gmStatus = false private
Definition at line 188 of file Channel.h.
Referenced by IsOwnerGM(), and SetOwnerGM().
flags
uint8 Channel::PlayerInfo::flags
Definition at line 151 of file Channel.h.
Referenced by HasFlag(), IsModerator(), IsMuted(), IsOwner(), Channel::JoinChannel(), SetFlag(), SetModerator(), Channel::SetModerator(), Channel::SetMute(), SetMuted(), SetOwner(), and Channel::SetOwner().
lastSpeakTime
uint64 Channel::PlayerInfo::lastSpeakTime
Definition at line 152 of file Channel.h.
Referenced by IsAllowedToSpeak(), Channel::JoinChannel(), and Channel::Say().
player
ObjectGuid Channel::PlayerInfo::player
Definition at line 150 of file Channel.h.
Referenced by Channel::JoinChannel().
plrPtr
Player* Channel::PlayerInfo::plrPtr
Definition at line 153 of file Channel.h.
Referenced by Channel::JoinChannel(), Channel::Say(), Channel::SetModerator(), and Channel::SetOwner().
The documentation for this struct was generated from the following file:
src/server/game/Chat/Channels/Channel.h