Azerotcore-wotlk: go_arcane_prison Class Reference
go_arcane_prison Class Reference
Public Member Functions
go_arcane_prison ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1182 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_arcane_prison()
go_arcane_prison::go_arcane_prison () inline
Definition at line 1185 of file go_scripts.cpp.
 : GameObjectScript("go_arcane_prison") { }
Member Function Documentation
OnGossipHello()
bool go_arcane_prison::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1187 of file go_scripts.cpp.
     {
         // xinef: prevent spawning hundreds of them
         if (player->GetQuestStatus(QUEST_PRISON_BREAK) == QUEST_STATUS_INCOMPLETE && !go->FindNearestCreature(25318, 20.0f))
         {
             go->SummonCreature(25318, 3485.089844f, 6115.7422188f, 70.966812f, 0, TEMPSUMMON_TIMED_DESPAWN, 60000);
             player->CastSpell(player, SPELL_ARCANE_PRISONER_KILL_CREDIT, true);
             return true;
         }
         return false;
     }
References Unit::CastSpell(), WorldObject::FindNearestCreature(), Player::GetQuestStatus(), QUEST_PRISON_BREAK, QUEST_STATUS_INCOMPLETE, SPELL_ARCANE_PRISONER_KILL_CREDIT, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp