Azerotcore-wotlk: npc_simone::npc_simoneAI Struct Reference
npc_simone::npc_simoneAI Struct Reference
Public Member Functions
npc_simoneAI (Creature *creature)
void SetPreciousGUID ()
Creature * Precious ()
npc_precious::npc_preciousAI * PreciousAI ()
void RespawnPet ()
void HandlePetRespawn ()
void JustRespawned () override
void JustDied (Unit *killer) override
void CorpseRemoved (uint32 &) override
== Triggered Actions Requested ==================
void Reset () override
void EnterCombat (Unit *victim) override
void UpdateAI (uint32 diff) override
void SpellHit (Unit *, const SpellInfo *Spell) override
void ScheduleEncounterStart (ObjectGuid playerGUID)
Public Member Functions inherited from NPCStaveQuestAI
NPCStaveQuestAI (Creature *creature)
uint32 GetFormEntry (std::string)
bool InNormalForm ()
void RevealForm ()
void StorePlayerGUID ()
Player * GetGossipPlayer ()
bool IsAllowedEntry (uint32)
bool UnitIsUnfair (Unit *unit)
bool IsFairFight ()
bool ValidThreatlist ()
void SetHomePosition ()
void PrepareForEncounter ()
void ClearLootIfUnfair (Unit *killer)
bool PlayerEligibleForReward (Unit *killer)
void StoreAttackerGuidValue (Unit *attacker)
bool QuestIncomplete (Unit *unit, uint32 questItem)
void ResetState (uint32)
void EvadeOnFeignDeath ()
virtual void AttackStart (Unit *)
virtual void AttackedBy (Unit *)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
ObjectGuid preciousGUID
Public Attributes inherited from NPCStaveQuestAI
ObjectGuid gossipPlayerGUID
ObjectGuid playerGUID
bool encounterStarted
ThreatContainer::StorageType const & threatList = me->getThreatMgr().getThreatList()
std::map< int, int > entryKeys
std::map< int, std::map< std::string, int > > entryList
std::vector< uint64 > attackerGuids
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 517 of file npc_stave_of_ancients.cpp.
Constructor & Destructor Documentation
npc_simoneAI()
npc_simone::npc_simoneAI::npc_simoneAI (Creature * creature) inline
Definition at line 519 of file npc_stave_of_ancients.cpp.
 : NPCStaveQuestAI(creature) { }
Member Function Documentation
CorpseRemoved()
void npc_simone::npc_simoneAI::CorpseRemoved (uint32 &) inline override virtual
== Triggered Actions Requested ==================
== State checks =================================
Reimplemented from CreatureAI.
Definition at line 618 of file npc_stave_of_ancients.cpp.
         {
             if (!Precious())
             {
                 return;
             }
             if (Precious()->IsInCombat())
             {
                 // If Simone corpse is removed but pet is InCombat, EnterEvadeMode and auto despawn on pet reaching home
                 PreciousAI()->EnterEvadeMode();
                 PreciousAI()->FlagForDespawn();
             }
             else
             {
                 Precious()->DespawnOrUnsummon(0);
             }
         }
References Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), npc_precious::npc_preciousAI::FlagForDespawn(), Precious(), and PreciousAI().
EnterCombat()
void npc_simone::npc_simoneAI::EnterCombat (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 645 of file npc_stave_of_ancients.cpp.
         {
             RevealForm();
             me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             if (!InNormalForm())
             {
                 if (victim && (UnitIsUnfair(victim) || !QuestIncomplete(victim, SIMONE_HEAD)))
                 {
                     me->CastSpell(victim, SPELL_FOOLS_PLIGHT, true);
                 }
                 events.ScheduleEvent(EVENT_RANGE_CHECK, 1000);
                 events.ScheduleEvent(EVENT_UNFAIR_FIGHT, 1000);
                 events.ScheduleEvent(SIMONE_EVENT_CHAIN_LIGHTNING, 3000);
                 events.ScheduleEvent(SIMONE_EVENT_TEMPTRESS_KISS, 1000);
             }
             events.ScheduleEvent(EVENT_FOOLS_PLIGHT, urand(2000, 3000));
         }
References Unit::CastSpell(), EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_UNFAIR_FIGHT, NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, NPCStaveQuestAI::QuestIncomplete(), Object::RemoveFlag(), NPCStaveQuestAI::RevealForm(), SIMONE_EVENT_CHAIN_LIGHTNING, SIMONE_EVENT_TEMPTRESS_KISS, SIMONE_HEAD, SPELL_FOOLS_PLIGHT, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, NPCStaveQuestAI::UnitIsUnfair(), and urand().
HandlePetRespawn()
void npc_simone::npc_simoneAI::HandlePetRespawn () inline
Definition at line 574 of file npc_stave_of_ancients.cpp.
         {
             if (Precious() && Precious()->isDead())
             {
                 RespawnPet();
             }
         }
References Precious(), and RespawnPet().
Referenced by UpdateAI().
JustDied()
void npc_simone::npc_simoneAI::JustDied (Unit * killer) inline override virtual
Reimplemented from NPCStaveQuestAI.
Definition at line 593 of file npc_stave_of_ancients.cpp.
         {
             NPCStaveQuestAI::JustDied(killer);
             if (!Precious())
             {
                 return;
             }
             if (Precious()->isDead())
             {
                 // Make it so that Precious respawns after Simone
                 uint32 respawnTime = me->GetRespawnTime() - time(nullptr);
                 Precious()->SetRespawnTime(respawnTime);
                 return;
             }
             Position petResetPos = me->GetNearPosition(-5.0f, 0.0f);
             if (petResetPos.IsPositionValid())
             {
                 Precious()->SetHomePosition(petResetPos);
             }
         }
References WorldObject::GetNearPosition(), Creature::GetRespawnTime(), Position::IsPositionValid(), NPCStaveQuestAI::JustDied(), ScriptedAI::me, Precious(), Creature::SetHomePosition(), and Creature::SetRespawnTime().
JustRespawned()
void npc_simone::npc_simoneAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 582 of file npc_stave_of_ancients.cpp.
         {
             // Using Respawn() instead of HandlePetRespawn because we want to respawn pet in
             // normal entry form
             if (Precious())
             {
                 Precious()->Respawn();
             }
             Reset();
         }
References Precious(), Reset(), and Creature::Respawn().
Precious()
Creature* npc_simone::npc_simoneAI::Precious () inline
Definition at line 539 of file npc_stave_of_ancients.cpp.
         {
             if (preciousGUID.IsEmpty())
             {
                 SetPreciousGUID();
             }
             if (!preciousGUID.IsEmpty())
             {
                 return ObjectAccessor::GetCreature(*me, preciousGUID);
             }
             return nullptr;
         }
References ObjectAccessor::GetCreature(), ObjectGuid::IsEmpty(), ScriptedAI::me, preciousGUID, and SetPreciousGUID().
Referenced by CorpseRemoved(), HandlePetRespawn(), JustDied(), JustRespawned(), PreciousAI(), RespawnPet(), and UpdateAI().
PreciousAI()
npc_precious::npc_preciousAI* npc_simone::npc_simoneAI::PreciousAI () inline
Definition at line 554 of file npc_stave_of_ancients.cpp.
         {
             if (Precious())
             {
                 return CAST_AI(npc_precious::npc_preciousAI, Precious()->AI());
             }
             return nullptr;
         }
References CAST_AI, and Precious().
Referenced by CorpseRemoved(), ScheduleEncounterStart(), and UpdateAI().
Reset()
void npc_simone::npc_simoneAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 637 of file npc_stave_of_ancients.cpp.
         {
             ResetState(SIMONE_SPELL_SILENCE);
             events.Reset();
             events.ScheduleEvent(SIMONE_EVENT_CHECK_PET_STATE, 2000);
         }
References NPCStaveQuestAI::ResetState(), SIMONE_EVENT_CHECK_PET_STATE, and SIMONE_SPELL_SILENCE.
Referenced by JustRespawned().
RespawnPet()
void npc_simone::npc_simoneAI::RespawnPet () inline
Definition at line 564 of file npc_stave_of_ancients.cpp.
         {
             Position current = me->GetNearPosition(-5.0f, 0.0f);
             Precious()->RemoveCorpse(false, false);
             Precious()->SetPosition(current);
             Precious()->SetHomePosition(current);
             Precious()->setDeathState(JUST_RESPAWNED);
             Precious()->UpdateObjectVisibility(true);
         }
References WorldObject::GetNearPosition(), JUST_RESPAWNED, ScriptedAI::me, Precious(), Creature::RemoveCorpse(), Creature::setDeathState(), Creature::SetHomePosition(), Creature::SetPosition(), and Unit::UpdateObjectVisibility().
Referenced by HandlePetRespawn().
ScheduleEncounterStart()
void npc_simone::npc_simoneAI::ScheduleEncounterStart (ObjectGuid playerGUID) inline
Definition at line 788 of file npc_stave_of_ancients.cpp.
         {
             PrepareForEncounter();
             if (PreciousAI())
             {
                 PreciousAI()->PrepareForEncounter();
             }
             gossipPlayerGUID = playerGUID;
             events.ScheduleEvent(EVENT_ENCOUNTER_START, 1000);
         }
References EVENT_ENCOUNTER_START, NPCStaveQuestAI::gossipPlayerGUID, NPCStaveQuestAI::playerGUID, PreciousAI(), and NPCStaveQuestAI::PrepareForEncounter().
SetPreciousGUID()
void npc_simone::npc_simoneAI::SetPreciousGUID () inline
Definition at line 524 of file npc_stave_of_ancients.cpp.
         {
             if (CreatureGroup* formation = me->GetFormation())
             {
                 const CreatureGroup::CreatureGroupMemberType& members = formation->GetMembers();
                 for (CreatureGroup::CreatureGroupMemberType::const_iterator itr = members.begin(); itr != members.end(); ++itr)
                 {
                     if (itr->first && itr->first->GetOriginalEntry() == PRECIOUS_NORMAL_ENTRY)
                     {
                         preciousGUID = itr->first->GetGUID();
                     }
                 }
             }
         }
References Creature::GetFormation(), ScriptedAI::me, PRECIOUS_NORMAL_ENTRY, and preciousGUID.
Referenced by Precious().
SpellHit()
void npc_simone::npc_simoneAI::SpellHit (Unit * , const SpellInfo * Spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 776 of file npc_stave_of_ancients.cpp.
         {
             if (!InNormalForm())
             {
                 if (Spell->Id == SIMONE_SPELL_WEAKNESS_VIPER_STING)
                 {
                     me->AddAura(SIMONE_SPELL_SILENCE, me);
                     me->TextEmote(SIMONE_WEAKNESS_EMOTE);
                 }
             }
         }
References Unit::AddAura(), NPCStaveQuestAI::InNormalForm(), ScriptedAI::me, SIMONE_SPELL_SILENCE, SIMONE_SPELL_WEAKNESS_VIPER_STING, SIMONE_WEAKNESS_EMOTE, and Unit::TextEmote().
UpdateAI()
void npc_simone::npc_simoneAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 666 of file npc_stave_of_ancients.cpp.
         {
             events.Update(diff);
             uint32 eventId = events.ExecuteEvent();
             // Out of combat events
             switch (eventId)
             {
                 case EVENT_ENCOUNTER_START:
                     me->TextEmote(SIMONE_EMOTE, GetGossipPlayer());
                     me->HandleEmoteCommand(EMOTE_ONESHOT_NONE);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAUGH);
                     events.ScheduleEvent(SIMONE_EVENT_TALK, 4000);
                     break;
                 case SIMONE_EVENT_TALK:
                     me->Say(SIMONE_SAY, GetGossipPlayer());
                     me->HandleEmoteCommand(EMOTE_ONESHOT_TALK);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     if (Precious())
                     {
                         Precious()->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     }
                     events.ScheduleEvent(EVENT_REVEAL, 5000);
                     break;
                 case EVENT_REVEAL:
                     RevealForm();
                     if (PreciousAI())
                     {
                         PreciousAI()->RevealForm();
                     }
                     break;
                 // Prevent hunters from figthing Simone alone
                 case SIMONE_EVENT_CHECK_PET_STATE:
                     if (!me->IsInCombat() && !me->IsInEvadeMode())
                     {
                         if (Precious() && Precious()->isDead())
{
                             HandlePetRespawn();
                         }
                         events.ScheduleEvent(SIMONE_EVENT_CHECK_PET_STATE, 1000);
                     }
                     break;
             }
             if (UpdateVictim())
             {
                 // This should prevent hunters from staying in combat when feign death is used and there is a bystander with 0 threat
                 EvadeOnFeignDeath();
             }
             else
             {
                 return;
             }
             if (me->HasUnitState(UNIT_STATE_CASTING) && eventId != EVENT_RANGE_CHECK && eventId != EVENT_UNFAIR_FIGHT)
             {
                 events.RepeatEvent(1000);
                 return;
             }
             // In combat events
             switch (eventId)
             {
                 case EVENT_FOOLS_PLIGHT:
                     if (InNormalForm() || UnitIsUnfair(me->GetVictim()) || !QuestIncomplete(me->GetVictim(), SIMONE_HEAD))
                     {
                         me->CastSpell(me->GetVictim(), SPELL_FOOLS_PLIGHT, true);
                     }
                     events.RepeatEvent(urand(3000, 6000));
                     break;
                 case EVENT_RANGE_CHECK:
                     if (!me->GetVictim()->IsWithinDist2d(me, 60.0f))
                     {
                         EnterEvadeMode();
                     }
                     else
                     {
                         events.RepeatEvent(2000);
                     }
                     break;
                 case EVENT_UNFAIR_FIGHT:
                     if (!ValidThreatlist() || (PreciousAI() && !PreciousAI()->ValidThreatlist()))
                     {
                         SetHomePosition();
                         PreciousAI()->SetHomePosition();
                         Precious()->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_ATTACKABLE_1 | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_ATTACKABLE_1 | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         Precious()->DespawnOrUnsummon(5000);
                         me->DespawnOrUnsummon(5000);
                         break;
                     }
                     events.RepeatEvent(2000);
                     break;
                 case SIMONE_EVENT_CHAIN_LIGHTNING:
                     me->CastSpell(me->GetVictim(), SIMONE_SPELL_CHAIN_LIGHTNING, false);
                     events.RepeatEvent(7000);
                     break;
                 case SIMONE_EVENT_TEMPTRESS_KISS:
                     me->CastSpell(me->GetVictim(), SIMONE_SPELL_TEMPTRESS_KISS, false);
                     events.RepeatEvent(45000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_LAUGH, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_TALK, CreatureAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), EVENT_ENCOUNTER_START, EVENT_FOOLS_PLIGHT, EVENT_RANGE_CHECK, EVENT_REVEAL, EVENT_UNFAIR_FIGHT, NPCStaveQuestAI::GetGossipPlayer(), Unit::GetVictim(), Unit::HandleEmoteCommand(), HandlePetRespawn(), Unit::HasUnitState(), NPCStaveQuestAI::InNormalForm(), Unit::IsInCombat(), Creature::IsInEvadeMode(), WorldObject::IsWithinDist2d(), ScriptedAI::me, Precious(), PreciousAI(), NPCStaveQuestAI::QuestIncomplete(), Object::RemoveFlag(), NPCStaveQuestAI::RevealForm(), Unit::Say(), Object::SetFlag(), NPCStaveQuestAI::SetHomePosition(), SIMONE_EMOTE, SIMONE_EVENT_CHAIN_LIGHTNING, SIMONE_EVENT_CHECK_PET_STATE, SIMONE_EVENT_TALK, SIMONE_EVENT_TEMPTRESS_KISS, SIMONE_HEAD, SIMONE_SAY, SIMONE_SPELL_CHAIN_LIGHTNING, SIMONE_SPELL_TEMPTRESS_KISS, SPELL_FOOLS_PLIGHT, Unit::TextEmote(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_ATTACKABLE_1, UNIT_STATE_CASTING, NPCStaveQuestAI::UnitIsUnfair(), CreatureAI::UpdateVictim(), urand(), and NPCStaveQuestAI::ValidThreatlist().
Member Data Documentation
events
EventMap npc_simone::npc_simoneAI::events
Definition at line 521 of file npc_stave_of_ancients.cpp.
preciousGUID
ObjectGuid npc_simone::npc_simoneAI::preciousGUID
Definition at line 522 of file npc_stave_of_ancients.cpp.
Referenced by Precious(), and SetPreciousGUID().
The documentation for this struct was generated from the following file:
src/server/scripts/World/npc_stave_of_ancients.cpp