Azerotcore-wotlk: at_hor_shadow_throne Class Reference
at_hor_shadow_throne Class Reference
Public Member Functions
at_hor_shadow_throne ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1313 of file halls_of_reflection.cpp.
Constructor & Destructor Documentation
at_hor_shadow_throne()
at_hor_shadow_throne::at_hor_shadow_throne () inline
Definition at line 1316 of file halls_of_reflection.cpp.
 : AreaTriggerScript("at_hor_shadow_throne") { }
Member Function Documentation
OnTrigger()
bool at_hor_shadow_throne::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1318 of file halls_of_reflection.cpp.
     {
         if (player->IsGameMaster())
             return false;
         InstanceScript* inst = player->GetInstanceScript();
         if (!inst)
             return false;
         if (inst->GetData(DATA_FROSTSWORN_GENERAL) && !inst->GetData(DATA_LK_INTRO))
             inst->SetData(DATA_LK_INTRO, DONE);
         return false;
     }
References DATA_FROSTSWORN_GENERAL, DATA_LK_INTRO, DONE, ZoneScript::GetData(), WorldObject::GetInstanceScript(), Player::IsGameMaster(), and ZoneScript::SetData().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp