Azerotcore-wotlk: counting_buffer< T > Class Template Reference
counting_buffer< T > Class Template Reference final
#include <core.h>
Public Member Functions
counting_buffer ()
auto count () -> size_t
Public Member Functions inherited from buffer< char >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () FMT_NOEXCEPT -> char *
auto begin () const FMT_NOEXCEPT -> const char *
auto end () FMT_NOEXCEPT -> char *
auto end () const FMT_NOEXCEPT -> const char *
auto size () const FMT_NOEXCEPT -> size_t
auto capacity () const FMT_NOEXCEPT -> size_t
auto data () FMT_NOEXCEPT -> char *
auto data () const FMT_NOEXCEPT -> const char *
void clear ()
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const char &value)
void append (const U *begin, const U *end)
void append (const U *begin, const U *end)
auto operator[] (I index) -> char &
auto operator[] (I index) const -> const char &
Protected Member Functions
void grow (size_t) final FMT_OVERRIDE
Protected Member Functions inherited from buffer< char >
buffer (size_t sz) FMT_NOEXCEPT
buffer (char *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
buffer (buffer &&)=default
~buffer ()=default
void set (char *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Private Types
enum { buffer_size = 256 }
Private Attributes
T data_ [buffer_size]
size_t count_ = 0
Additional Inherited Members
Public Types inherited from buffer< char >
using value_type = char
using const_reference = const char &
Detailed Description
template<typename T = char>
class counting_buffer< T >
Definition at line 924 of file core.h.
Member Enumeration Documentation
anonymous enum
template<typename T = char> anonymous enum private
Enumerator
buffer_size
Definition at line 926 of file core.h.
 { buffer_size = 256 };
Constructor & Destructor Documentation
counting_buffer()
template<typename T = char> counting_buffer< T >::counting_buffer () inline
Definition at line 938 of file core.h.
 : buffer<T>(data_, 0, buffer_size) {}
Member Function Documentation
count()
template<typename T = char> auto counting_buffer< T >::count () -> size_t inline
Definition at line 940 of file core.h.
 { return count_ + this->size(); }
References counting_buffer< T >::count_, and buffer< char >::size().
grow()
template<typename T = char> void counting_buffer< T >::grow (size_t capacity) inline final protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements buffer< char >.
Definition at line 931 of file core.h.
{
     if (this->size() != buffer_size) return;
     count_ += this->size();
     this->clear();
   }
References counting_buffer< T >::buffer_size, buffer< char >::clear(), and buffer< char >::size().
Member Data Documentation
count_
template<typename T = char> size_t counting_buffer< T >::count_ = 0 private
Definition at line 928 of file core.h.
Referenced by counting_buffer< T >::count().
data_
template<typename T = char> T counting_buffer< T >::data_[buffer_size] private
Definition at line 927 of file core.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h