Azerotcore-wotlk: EventMap Class Reference
EventMap Class Reference
#include <Util.h>
Public Member Functions
EventMap ()
Reset
Removes all scheduled events and resets time and phase.
void Reset ()
Update
Updates the timer of the event map.
Parameters
time Value to be added to time.
void Update (uint32 time)
GetTimer
Returns
Current timer value.
uint32 GetTimer () const
void SetTimer (uint32 time)
GetPhaseMask
Returns
Active phases as mask.
uint8 GetPhaseMask () const
Empty
Returns
True, if there are no events scheduled.
bool Empty () const
SetPhase
Sets the phase of the map (absolute).
Parameters
phase Phase which should be set. Values: 1 - 8. 0 resets phase.
void SetPhase (uint8 phase)
AddPhase
Activates the given phase (bitwise).
Parameters
phase Phase which should be activated. Values: 1 - 8
void AddPhase (uint8 phase)
RemovePhase
Deactivates the given phase (bitwise).
Parameters
phase Phase which should be deactivated. Values: 1 - 8.
void RemovePhase (uint8 phase)
ScheduleEvent
Creates new event entry in map.
Parameters
eventId The id of the new event.
time The time in milliseconds until the event occurs.
group The group which the event is associated to. Has to be between 1 and 8. 0 means it has no group.
phase The phase in which the event can occur. Has to be between 1 and 8. 0 means it can occur in all phases.
void ScheduleEvent (uint32 eventId, uint32 time, uint32 group=0, uint32 phase=0)
RescheduleEvent
Cancels the given event and reschedules it.
Parameters
eventId The id of the event.
time The time in milliseconds until the event occurs.
group The group which the event is associated to. Has to be between 1 and 8. 0 means it has no group.
phase The phase in which the event can occur. Has to be between 1 and 8. 0 means it can occur in all phases.
void RescheduleEvent (uint32 eventId, uint32 time, uint32 groupId=0, uint32 phase=0)
void RepeatEvent (uint32 time)
ExecuteEvent
Returns the next event to execute and removes it from map.
Returns
Id of the event to execute.
uint32 ExecuteEvent ()
DelayEvents
Delay all events of the same group.
Parameters
delay Amount of delay.
group Group of the events.
void DelayEvents (uint32 delay)
void DelayEventsToMax (uint32 delay, uint32 group)
void DelayEvents (uint32 delay, uint32 group)
CancelEvent
Cancels all events of the specified id.
Parameters
eventId Event id to cancel.
void CancelEvent (uint32 eventId)
CancelEventGroup
Cancel events belonging to specified group.
Parameters
group Group to cancel.
void CancelEventGroup (uint32 group)
GetNextEventTime
Returns
Time of next event.
uint32 GetNextEventTime (uint32 eventId) const
uint32 GetNextEventTime () const
Private Types
typedef std::multimap< uint32, uint32 > EventStore
IsInPhase
Returns wether event map is in specified phase or not.
Parameters
phase Wanted phase.
Returns
True, if phase of event map contains specified phase.
uint32 _time {0}
uint32 _phase {0}
uint32 _lastEvent {0}
EventStore _eventMap
bool IsInPhase (uint8 phase)
Detailed Description
Definition at line 653 of file Util.h.
Member Typedef Documentation
EventStore
typedef std::multimap<uint32, uint32> EventMap::EventStore private
Definition at line 655 of file Util.h.
Constructor & Destructor Documentation
EventMap()
EventMap::EventMap () inline
Definition at line 658 of file Util.h.
 { }
Member Function Documentation
AddPhase()
void EventMap::AddPhase (uint8 phase) inline
Definition at line 735 of file Util.h.
     {
         if (phase && phase <= 8)
         {
             _phase |= (1 << (phase - 1));
         }
     }
References _phase.
CancelEvent()
void EventMap::CancelEvent (uint32 eventId) inline
Definition at line 898 of file Util.h.
     {
         if (Empty())
         {
             return;
         }
         for (EventStore::iterator itr = _eventMap.begin(); itr != _eventMap.end();)
         {
             if (eventId == (itr->second & 0x0000FFFF))
             {
                 itr = _eventMap.erase(itr);
                 continue;
             }
             ++itr;
         }
     }
References _eventMap, and Empty().
Referenced by go_suppression_device::go_suppression_deviceAI::Deactivate(), go_suppression_device::go_suppression_deviceAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::EnterCombat(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterCombat(), BattlegroundWS::EventPlayerCapturedFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), go_suppression_device::go_suppression_deviceAI::OnLootStateChanged(), RescheduleEvent(), BattlegroundWS::RespawnFlagAfterDrop(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), and npc_simon_bunny::npc_simon_bunnyAI::UpdateAI().
CancelEventGroup()
void EventMap::CancelEventGroup (uint32 group) inline
Definition at line 922 of file Util.h.
     {
         if (!group || group > 8 || Empty())
         {
             return;
         }
         uint32 groupMask = (1 << (group + 15));
         for (EventStore::iterator itr = _eventMap.begin(); itr != _eventMap.end();)
         {
             if (itr->second & groupMask)
             {
                 _eventMap.erase(itr);
                 itr = _eventMap.begin();
                 continue;
             }
             ++itr;
         }
     }
References _eventMap, and Empty().
Referenced by npc_simon_bunny::npc_simon_bunnyAI::DoAction(), and boss_kiljaeden::boss_kiljaedenAI::UpdateAI().
DelayEvents() [1/2]
void EventMap::DelayEvents (uint32 delay) inline
Definition at line 842 of file Util.h.
     {
         _time = delay < _time ? _time - delay : 0;
     }
References _time.
DelayEvents() [2/2]
void EventMap::DelayEvents (uint32 delay, uint32 group) inline
Definition at line 869 of file Util.h.
     {
         if (group > 8 || Empty())
         {
             return;
         }
         EventStore delayed;
         for (EventStore::iterator itr = _eventMap.begin(); itr != _eventMap.end();)
         {
             if (!group || (itr->second & (1 << (group + 15))))
             {
                 delayed.insert(EventStore::value_type(itr->first + delay, itr->second));
                 itr = _eventMap.erase(itr);
                 continue;
             }
             ++itr;
         }
         _eventMap.insert(delayed.begin(), delayed.end());
     }
References _eventMap, and Empty().
DelayEventsToMax()
void EventMap::DelayEventsToMax (uint32 delay, uint32 group) inline
Definition at line 847 of file Util.h.
     {
         for (EventStore::iterator itr = _eventMap.begin(); itr != _eventMap.end();)
         {
             if (itr->first < _time + delay && (group == 0 || ((1 << (group + 15)) & itr->second)))
             {
                 ScheduleEvent(itr->second, delay);
                 _eventMap.erase(itr);
                 itr = _eventMap.begin();
                 continue;
             }
             ++itr;
         }
     }
References _eventMap, _time, and ScheduleEvent().
Referenced by boss_faction_championsAI::EventMapGCD().
Empty()
bool EventMap::Empty () const inline
Definition at line 708 of file Util.h.
     {
         return _eventMap.empty();
     }
References _eventMap.
Referenced by CancelEvent(), CancelEventGroup(), DelayEvents(), boss_felmyst::boss_felmystAI::EnterCombat(), ExecuteEvent(), GetNextEventTime(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), and boss_kaelthas::boss_kaelthasAI::UpdateAI().
ExecuteEvent()
uint32 EventMap::ExecuteEvent () inline
Definition at line 811 of file Util.h.
     {
         while (!Empty())
         {
             EventStore::iterator itr = _eventMap.begin();
             if (itr->first > _time)
             {
                 return 0;
             }
             else if (_phase && (itr->second & 0xFF000000) && !((itr->second >> 24) & _phase))
             {
                 _eventMap.erase(itr);
             }
             else
             {
                 uint32 eventId = (itr->second & 0x0000FFFF);
                 _lastEvent = itr->second;
                 _eventMap.erase(itr);
                 return eventId;
             }
         }
         return 0;
     }
References _eventMap, _lastEvent, _phase, _time, and Empty().
Referenced by BattlegroundAB::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), go_bells::go_bellsAI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_ishanah::ishanahAI::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), and npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI().
GetNextEventTime() [1/2]
uint32 EventMap::GetNextEventTime () const inline
Definition at line 971 of file Util.h.
     {
         return Empty() ? 0 : _eventMap.begin()->first;
     }
References _eventMap, and Empty().
GetNextEventTime() [2/2]
uint32 EventMap::GetNextEventTime (uint32 eventId) const inline
Definition at line 949 of file Util.h.
     {
         if (Empty())
         {
             return 0;
         }
         for (auto const& itr : _eventMap)
         {
             if (eventId == (itr.second & 0x0000FFFF))
             {
                 return itr.first;
             }
         }
         return 0;
     }
References _eventMap, and Empty().
Referenced by BattlegroundWS::GetAssaultSpellId(), boss_attumen::boss_attumenAI::KilledUnit(), boss_attumen_midnight::boss_attumen_midnightAI::KilledUnit(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), npc_halion_controller::npc_halion_controllerAI::SetData(), boss_attumen::boss_attumenAI::SpellHit(), boss_attumen_midnight::boss_attumen_midnightAI::SpellHit(), and boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI().
GetPhaseMask()
uint8 EventMap::GetPhaseMask () const inline
Definition at line 699 of file Util.h.
     {
         return _phase;
     }
References _phase.
Referenced by npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), and npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI().
GetTimer()
uint32 EventMap::GetTimer () const inline
Definition at line 685 of file Util.h.
     {
         return _time;
     }
References _time.
IsInPhase()
bool EventMap::IsInPhase (uint8 phase) inline
Definition at line 982 of file Util.h.
     {
         return phase <= 8 && (!phase || _phase & (1 << (phase - 1)));
     }
References _phase.
Referenced by npc_coren_direbrew::npc_coren_direbrewAI::DamageTaken(), npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight(), and npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI().
RemovePhase()
void EventMap::RemovePhase (uint8 phase) inline
Definition at line 748 of file Util.h.
     {
         if (phase && phase <= 8)
         {
             _phase &= ~(1 << (phase - 1));
         }
     }
References _phase.
RepeatEvent()
void EventMap::RepeatEvent (uint32 time) inline
Definition at line 801 of file Util.h.
     {
         _eventMap.insert(EventStore::value_type(_time + time, _lastEvent));
     }
References _eventMap, _lastEvent, and _time.
Referenced by instance_ulduar::instance_ulduar_InstanceMapScript::Update(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), and adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI().
RescheduleEvent()
void EventMap::RescheduleEvent (uint32 eventId, uint32 time, uint32 groupId = 0, uint32 phase = 0) inline
Definition at line 787 of file Util.h.
     {
         CancelEvent(eventId);
         ScheduleEvent(eventId, time, groupId, phase);
     }
References CancelEvent(), and ScheduleEvent().
Referenced by BattlegroundAB::CreateBanner(), npc_kinetic_bomb::npc_kinetic_bombAI::DoAction(), boss_sartharion_dragonAI::DoAction(), BattlegroundEY::EventPlayerCapturedFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), BattlegroundEY::EventPlayerDroppedFlag(), BattlegroundWS::EventPlayerDroppedFlag(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), boss_halion::boss_halionAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::SetData(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), and boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI().
Reset()
void EventMap::Reset () inline
Definition at line 664 of file Util.h.
     {
         _eventMap.clear();
         _time = 0;
         _phase = 0;
     }
References _eventMap, _phase, and _time.
Referenced by boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_halion_controller::npc_halion_controllerAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::DoAction(), BattlegroundAB::EndBattleground(), chromatic_elite_guard::chromatic_elite_guardAI::EnterCombat(), boss_twilight_corrupter::boss_twilight_corrupterAI::EnterCombat(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::EnterCombat(), npc_tiger_matriarch::npc_tiger_matriarchAI::EnterCombat(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::EnterCombat(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::EnterCombat(), boss_twilight_halion::boss_twilight_halionAI::EnterCombat(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::EnterCombat(), boss_magtheridon::boss_magtheridonAI::EnterCombat(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::EnterCombat(), npc_pet_shaman_earth_elemental::EnterCombat(), npc_pet_shaman_fire_elemental::EnterCombat(), boss_moroes::boss_moroesAI::EnterCombat(), boss_krik_thir::boss_krik_thirAI::EnterCombat(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), BattlegroundAB::Init(), BattlegroundEY::Init(), BattlegroundWS::Init(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Initialize(), instance_ulduar::instance_ulduar_InstanceMapScript::Initialize(), boss_kiljaeden::boss_kiljaedenAI::InitializeAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_moroes::boss_moroesAI::InitializeGuests(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::JustDied(), npc_coren_direbrew::npc_coren_direbrewAI::JustDied(), npc_spinestalker::npc_spinestalkerAI::JustDied(), npc_rimefang::npc_rimefangAI::JustDied(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::JustDied(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::Reset(), boss_attumen::boss_attumenAI::Reset(), boss_attumen_midnight::boss_attumen_midnightAI::Reset(), boss_servant_quarters::boss_servant_quartersAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_kalec::boss_kalecAI::Reset(), boss_entropius::boss_entropiusAI::Reset(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::Reset(), npc_coren_direbrew::npc_coren_direbrewAI::Reset(), npc_arthas::npc_arthasAI::Reset(), boss_captain_skarloc::boss_captain_skarlocAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), npc_magwin::npc_magwinAI::Reset(), npc_stillpine_capitive::npc_stillpine_capitiveAI::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_sartharion::boss_sartharionAI::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_twilight_halion::boss_twilight_halionAI::Reset(), npc_halion_controller::npc_halion_controllerAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::Reset(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_spirit_warden::npc_spirit_wardenAI::Reset(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::Reset(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::Reset(), npc_risen_archmage::npc_risen_archmageAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), npc_blazing_skeleton::npc_blazing_skeletonAI::Reset(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::Reset(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::Reset(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::Reset(), boss_svala::boss_svalaAI::Reset(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::Reset(), npc_shandy_dalaran::npc_shandy_dalaranAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), npc_akama_shade::npc_akamaAI::Reset(), boss_doomlord_kazzak::boss_doomlordkazzakAI::Reset(), boss_doomwalker::boss_doomwalkerAI::Reset(), boss_magtheridon::boss_magtheridonAI::Reset(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::Reset(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::Reset(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), boss_attumen::boss_attumenAI::SpellHitTarget(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), and boss_kaelthas::boss_kaelthasAI::UpdateAI().
ScheduleEvent()
void EventMap::ScheduleEvent (uint32 eventId, uint32 time, uint32 group = 0, uint32 phase = 0) inline
Definition at line 764 of file Util.h.
     {
         if (group && group <= 8)
         {
             eventId |= (1 << (group + 15));
         }
         if (phase && phase <= 8)
         {
             eventId |= (1 << (phase + 23));
         }
         _eventMap.insert(EventStore::value_type(_time + time, eventId));
     }
References _eventMap, and _time.
Referenced by go_suppression_device::go_suppression_deviceAI::Activate(), boss_shade_of_akama::boss_shade_of_akamaAI::boss_shade_of_akamaAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::CleanupInstance(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken(), boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), DelayEventsToMax(), npc_coren_direbrew::npc_coren_direbrewAI::DoAction(), npc_xerestrasza::npc_xerestraszaAI::DoAction(), npc_halion_controller::npc_halion_controllerAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_tirion_fordring_tft::npc_tirion_fordringAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::DoAction(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::DoAction(), npc_simon_bunny::npc_simon_bunnyAI::DoAction(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::DoAction(), boss_felmyst::boss_felmystAI::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), npc_akama_shade::npc_akamaAI::DoAction(), socrethar::socretharAI::DoAction(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::EnterCombat(), boss_doomrel::boss_doomrelAI::EnterCombat(), chromatic_elite_guard::chromatic_elite_guardAI::EnterCombat(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::EnterCombat(), boss_attumen::boss_attumenAI::EnterCombat(), boss_attumen_midnight::boss_attumen_midnightAI::EnterCombat(), boss_kiljaeden::boss_kiljaedenAI::EnterCombat(), boss_twilight_corrupter::boss_twilight_corrupterAI::EnterCombat(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::EnterCombat(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::EnterCombat(), npc_tiger_matriarch::npc_tiger_matriarchAI::EnterCombat(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::EnterCombat(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::EnterCombat(), boss_twilight_halion::boss_twilight_halionAI::EnterCombat(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::EnterCombat(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterCombat(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::EnterCombat(), npc_counselor_talbot::npc_counselor_talbotAI::EnterCombat(), boss_warbringer_omrogg::boss_warbringer_omroggAI::EnterCombat(), adyen_the_lightbringer::adyen_the_lightbringerAI::EnterCombat(), exarch_orelis::exarch_orelisAI::EnterCombat(), socrethar::socretharAI::EnterCombat(), kaylaan_the_lost::kaylaan_the_lostAI::EnterCombat(), npc_pet_shaman_earth_elemental::EnterCombat(), npc_pet_shaman_fire_elemental::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_felmyst::boss_felmystAI::EnterCombat(), boss_halion::boss_halionAI::EnterCombat(), npc_beryl_sorcerer::npc_beryl_sorcererAI::EnterCombat(), npc_torturer_lecraft::npc_torturer_lecraftAI::EnterCombat(), anchorite_karja::anchorite_karjaAI::EnterCombat(), npc_ishanah::ishanahAI::EnterCombat(), boss_shade_of_akama::boss_shade_of_akamaAI::EnterEvadeMode(), BattlegroundWS::EventPlayerCapturedFlag(), go_brewfest_music::go_brewfest_musicAI::go_brewfest_musicAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::go_darkmoon_faire_musicAI(), go_midsummer_music::go_midsummer_musicAI::go_midsummer_musicAI(), go_pirate_day_music::go_pirate_day_musicAI::go_pirate_day_musicAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::Initialize(), go_suppression_device::go_suppression_deviceAI::InitializeAI(), boss_kiljaeden::boss_kiljaedenAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_moroes::boss_moroesAI::InitializeGuests(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_attumen::boss_attumenAI::KilledUnit(), boss_attumen_midnight::boss_attumen_midnightAI::KilledUnit(), boss_warbringer_omrogg::boss_warbringer_omroggAI::KilledUnit(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::MoveInLineOfSight(), boss_kaelthas::boss_kaelthasAI::MoveInLineOfSight(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::MovementInform(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::MovementInform(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::MovementInform(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), npc_thassarian2::npc_thassarian2AI::MovementInform(), npc_akama_shade::npc_akamaAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), go_suppression_device::go_suppression_deviceAI::OnLootStateChanged(), BattlegroundAB::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), npc_hidden_cultist::npc_hidden_cultistAI::PreScript(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), RescheduleEvent(), boss_servant_quarters::boss_servant_quartersAI::Reset(), boss_kalec::boss_kalecAI::Reset(), boss_entropius::boss_entropiusAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::Reset(), boss_blight_worm::boss_blight_wormAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_spirit_warden::npc_spirit_wardenAI::Reset(), npc_risen_archmage::npc_risen_archmageAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), npc_blazing_skeleton::npc_blazing_skeletonAI::Reset(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::Reset(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::Reset(), npc_thassarian::npc_thassarianAI::Reset(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::Reset(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::Reset(), boss_doomlord_kazzak::boss_doomlordkazzakAI::Reset(), boss_doomwalker::boss_doomwalkerAI::Reset(), boss_magtheridon::boss_magtheridonAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState(), boss_svala::boss_svalaAI::SetData(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::SetData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::SetData(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_simon_bunny::npc_simon_bunnyAI::SetData(), npc_thassarian2::npc_thassarian2AI::SetData(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::SetData(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::SetGUID(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_akama_shade::npc_akamaAI::sGossipSelect(), npc_crusade_recruit::npc_crusade_recruitAI::sGossipSelect(), boss_attumen::boss_attumenAI::SpellHit(), boss_attumen_midnight::boss_attumen_midnightAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_beryl_sorcerer::npc_beryl_sorcererAI::SpellHit(), npc_magwin::npc_magwinAI::sQuestAccept(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), BattlegroundAB::StartingEventOpenDoors(), BattlegroundEY::StartingEventOpenDoors(), BattlegroundWS::StartingEventOpenDoors(), npc_coren_direbrew::npc_coren_direbrewAI::SummonedCreatureDies(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::SummonSpirits(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), go_bells::go_bellsAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_ishanah::ishanahAI::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), npc_arthas::npc_arthasAI::WaypointReached(), and npc_magwin::npc_magwinAI::WaypointReached().
SetPhase()
void EventMap::SetPhase (uint8 phase) inline
Definition at line 718 of file Util.h.
     {
         if (!phase)
         {
             _phase = 0;
         }
         else if (phase <= 8)
         {
             _phase = (1 << (phase - 1));
         }
     }
References _phase.
Referenced by npc_coren_direbrew::npc_coren_direbrewAI::DamageTaken(), npc_coren_direbrew::npc_coren_direbrewAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), and npc_coren_direbrew::npc_coren_direbrewAI::Reset().
SetTimer()
void EventMap::SetTimer (uint32 time) inline
Definition at line 690 of file Util.h.
     {
         _time = time;
     }
References _time.
Update()
void EventMap::Update (uint32 time) inline
Definition at line 676 of file Util.h.
     {
         _time += time;
     }
References _time.
Referenced by BattlegroundAB::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), go_bells::go_bellsAI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_ishanah::ishanahAI::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), and npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI().
Member Data Documentation
_eventMap
EventStore EventMap::_eventMap private
Definition at line 992 of file Util.h.
Referenced by CancelEvent(), CancelEventGroup(), DelayEvents(), DelayEventsToMax(), Empty(), ExecuteEvent(), GetNextEventTime(), RepeatEvent(), Reset(), and ScheduleEvent().
_lastEvent
uint32 EventMap::_lastEvent {0} private
Definition at line 990 of file Util.h.
Referenced by ExecuteEvent(), and RepeatEvent().
_phase
uint32 EventMap::_phase {0} private
Definition at line 989 of file Util.h.
Referenced by AddPhase(), ExecuteEvent(), GetPhaseMask(), IsInPhase(), RemovePhase(), Reset(), and SetPhase().
_time
uint32 EventMap::_time {0} private
Definition at line 988 of file Util.h.
Referenced by DelayEvents(), DelayEventsToMax(), ExecuteEvent(), GetTimer(), RepeatEvent(), Reset(), ScheduleEvent(), SetTimer(), and Update().
The documentation for this class was generated from the following file:
src/common/Utilities/Util.h