Azerotcore-wotlk: VehicleAI Struct Reference
VehicleAI Struct Reference
#include <CombatAI.h>
Public Member Functions
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Private Member Functions
void LoadConditions ()
void CheckConditions (uint32 diff)
Private Attributes
ConditionList conditions
uint32 m_ConditionsTimer
bool m_DoDismiss
uint32 m_DismissTimer
Additional Inherited Members
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 97 of file CombatAI.h.
Constructor & Destructor Documentation
VehicleAI()
VehicleAI::VehicleAI (Creature * creature) explicit
Definition at line 257 of file CombatAI.cpp.
                                 : CreatureAI(c), m_ConditionsTimer(VEHICLE_CONDITION_CHECK_TIME)
 {
     LoadConditions();
     m_DoDismiss = false;
     m_DismissTimer = VEHICLE_DISMISS_TIME;
 }
References LoadConditions(), m_DismissTimer, m_DoDismiss, and VEHICLE_DISMISS_TIME.
Member Function Documentation
AttackStart()
void VehicleAI::AttackStart (Unit *) inline override virtual
Reimplemented from UnitAI.
Reimplemented in boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_hover_disk::npc_hover_diskAI, npc_vortex_ride::npc_vortex_rideAI, and npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI.
Definition at line 104 of file CombatAI.h.
 {}
CheckConditions()
void VehicleAI::CheckConditions (uint32 diff) private
Definition at line 298 of file CombatAI.cpp.
 {
     if (m_ConditionsTimer < diff)
     {
         if (!conditions.empty())
         {
             if (Vehicle* vehicleKit = me->GetVehicleKit())
                 for (SeatMap::iterator itr = vehicleKit->Seats.begin(); itr != vehicleKit->Seats.end(); ++itr)
                     if (Unit* passenger = ObjectAccessor::GetUnit(*me, itr->second.Passenger.Guid))
                     {
                         if (Player* player = passenger->ToPlayer())
{
                             if (!sConditionMgr->IsObjectMeetToConditions(player, me, conditions))
{
                                 player->ExitVehicle();
                                 return; // check other pessanger in next tick
                             }
                         }
                     }
         }
         m_ConditionsTimer = VEHICLE_CONDITION_CHECK_TIME;
     }
     else
         m_ConditionsTimer -= diff;
 }
References conditions, ObjectAccessor::GetUnit(), Unit::GetVehicleKit(), m_ConditionsTimer, CreatureAI::me, sConditionMgr, Object::ToPlayer(), and VEHICLE_CONDITION_CHECK_TIME.
Referenced by UpdateAI().
LoadConditions()
void VehicleAI::LoadConditions () private
Definition at line 291 of file CombatAI.cpp.
 {
     conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, me->GetEntry());
     if (!conditions.empty())
         LOG_DEBUG("condition", "VehicleAI::LoadConditions: loaded %u conditions", uint32(conditions.size()));
 }
References CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, conditions, Object::GetEntry(), LOG_DEBUG, CreatureAI::me, and sConditionMgr.
Referenced by VehicleAI().
MoveInLineOfSight()
void VehicleAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_hover_disk::npc_hover_diskAI, npc_vortex_ride::npc_vortex_rideAI, and npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI.
Definition at line 103 of file CombatAI.h.
 {}
OnCharmed()
void VehicleAI::OnCharmed (bool apply) override virtual
Implements UnitAI.
Definition at line 281 of file CombatAI.cpp.
 {
     if (!me->GetVehicleKit()->IsVehicleInUse() && !apply && !conditions.empty()) // was used and has conditions
         m_DoDismiss = true; // needs reset
     else if (apply)
         m_DoDismiss = false; // in use again
     m_DismissTimer = VEHICLE_DISMISS_TIME;//reset timer
 }
References ByteConverter::apply(), conditions, Unit::GetVehicleKit(), Vehicle::IsVehicleInUse(), m_DismissTimer, m_DoDismiss, CreatureAI::me, and VEHICLE_DISMISS_TIME.
Permissible()
static int VehicleAI::Permissible (Creature const *) inline static
Definition at line 107 of file CombatAI.h.
 { return PERMIT_BASE_NO; }
References PERMIT_BASE_NO.
UpdateAI()
void VehicleAI::UpdateAI (uint32 diff) override virtual
Implements UnitAI.
Reimplemented in npc_wg_siege_machine::npc_wg_siege_machineAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, boss_skadi_grauf::boss_skadi_graufAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_oculus_drake::npc_oculus_drakeAI, npc_hover_disk::npc_hover_diskAI, npc_vortex_ride::npc_vortex_rideAI, npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, and npc_scarlet_cannon::npc_scarlet_cannonAI.
Definition at line 265 of file CombatAI.cpp.
 {
     CheckConditions(diff);
     if (m_DoDismiss)
     {
         if (m_DismissTimer < diff)
         {
             m_DoDismiss = false;
             me->DespawnOrUnsummon();
         }
         else
             m_DismissTimer -= diff;
     }
 }
References CheckConditions(), Creature::DespawnOrUnsummon(), m_DismissTimer, m_DoDismiss, and CreatureAI::me.
Referenced by npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), and npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI().
Member Data Documentation
conditions
ConditionList VehicleAI::conditions private
Definition at line 112 of file CombatAI.h.
Referenced by CheckConditions(), LoadConditions(), and OnCharmed().
m_ConditionsTimer
uint32 VehicleAI::m_ConditionsTimer private
Definition at line 113 of file CombatAI.h.
Referenced by CheckConditions().
m_DismissTimer
uint32 VehicleAI::m_DismissTimer private
Definition at line 115 of file CombatAI.h.
Referenced by OnCharmed(), UpdateAI(), and VehicleAI().
m_DoDismiss
bool VehicleAI::m_DoDismiss private
Definition at line 114 of file CombatAI.h.
Referenced by OnCharmed(), UpdateAI(), and VehicleAI().
The documentation for this struct was generated from the following files:
src/server/game/AI/CoreAI/CombatAI.h
src/server/game/AI/CoreAI/CombatAI.cpp