Azerotcore-wotlk: npc_putricide_oozeAI Class Reference
npc_putricide_oozeAI Class Reference abstract
Public Member Functions
npc_putricide_oozeAI (Creature *creature, uint32 hitTargetSpellId)
void SetGUID (ObjectGuid guid, int32 type) override
void IsSummonedBy (Unit *) override
void SelectNewTarget ()
void SpellHitTarget (Unit *, SpellInfo const *spell) override
void SpellHit (Unit *, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
virtual void CastMainSpell ()=0
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid targetGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
uint32 _hitTargetSpellId
uint32 _newTargetSelectTimer
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 740 of file boss_professor_putricide.cpp.
Constructor & Destructor Documentation
npc_putricide_oozeAI()
npc_putricide_oozeAI::npc_putricide_oozeAI (Creature * creature, uint32 hitTargetSpellId) inline
Definition at line 743 of file boss_professor_putricide.cpp.
                                                                       : ScriptedAI(creature),
         _hitTargetSpellId(hitTargetSpellId), _newTargetSelectTimer(0)
     {
         me->SetReactState(REACT_PASSIVE);
     }
References ScriptedAI::me, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
CastMainSpell()
virtual void npc_putricide_oozeAI::CastMainSpell () pure virtual
Implemented in npc_gas_cloud::npc_gas_cloudAI, and npc_volatile_ooze::npc_volatile_oozeAI.
Referenced by UpdateAI().
IsSummonedBy()
void npc_putricide_oozeAI::IsSummonedBy (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 757 of file boss_professor_putricide.cpp.
     {
         if (InstanceScript* instance = me->GetInstanceScript())
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
             {
                 if (!professor->IsInCombat())
                     me->DespawnOrUnsummon(1);
                 else
                     professor->AI()->JustSummoned(me);
             }
     }
References DATA_PROFESSOR_PUTRICIDE, Creature::DespawnOrUnsummon(), ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and ScriptedAI::me.
SelectNewTarget()
void npc_putricide_oozeAI::SelectNewTarget () inline
Definition at line 769 of file boss_professor_putricide.cpp.
     {
         targetGUID.Clear();
         me->InterruptNonMeleeSpells(true);
         me->AttackStop();
         me->GetMotionMaster()->Clear();
         me->StopMoving();
         _newTargetSelectTimer = 1000;
     }
References _newTargetSelectTimer, Unit::AttackStop(), ObjectGuid::Clear(), MotionMaster::Clear(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::StopMoving(), and targetGUID.
Referenced by SpellHit(), SpellHitTarget(), and UpdateAI().
SetGUID()
void npc_putricide_oozeAI::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from UnitAI.
Definition at line 751 of file boss_professor_putricide.cpp.
     {
         if (type == -1)
             targetGUID = guid;
     }
References targetGUID.
SpellHit()
void npc_putricide_oozeAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 785 of file boss_professor_putricide.cpp.
     {
         if (spell->Id == SPELL_TEAR_GAS_CREATURE)
             SelectNewTarget();
     }
References SpellInfo::Id, SelectNewTarget(), and SPELL_TEAR_GAS_CREATURE.
SpellHitTarget()
void npc_putricide_oozeAI::SpellHitTarget (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 779 of file boss_professor_putricide.cpp.
     {
         if (!_newTargetSelectTimer && spell->Id == sSpellMgr->GetSpellIdForDifficulty(_hitTargetSpellId, me))
             SelectNewTarget();
     }
References _hitTargetSpellId, _newTargetSelectTimer, SpellInfo::Id, ScriptedAI::me, SelectNewTarget(), and sSpellMgr.
UpdateAI()
void npc_putricide_oozeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 791 of file boss_professor_putricide.cpp.
     {
         if (!_newTargetSelectTimer)
         {
             if ((!me->HasUnitState(UNIT_STATE_CASTING) && !me->GetVictim()) || !me->IsNonMeleeSpellCast(false, false, true, false, true))
                 SelectNewTarget();
             else if (targetGUID)
             {
                 Unit* target = ObjectAccessor::GetUnit(*me, targetGUID);
                 if (me->GetVictim()->GetGUID() != targetGUID || !target || !me->IsValidAttackTarget(target) || target->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH) || target->GetExactDist2dSq(4356.0f, 3211.0f) > 80.0f * 80.0f || target->GetPositionZ() < 380.0f || target->GetPositionZ() > 405.0f)
                     SelectNewTarget();
             }
         }
         DoMeleeAttackIfReady();
         if (!_newTargetSelectTimer)
             return;
         if (me->HasAura(SPELL_TEAR_GAS_CREATURE))
             return;
         if (_newTargetSelectTimer <= diff)
         {
             _newTargetSelectTimer = 0;
             CastMainSpell();
         }
         else
             _newTargetSelectTimer -= diff;
     }
References _newTargetSelectTimer, CastMainSpell(), UnitAI::DoMeleeAttackIfReady(), Position::GetExactDist2dSq(), Object::GetGUID(), Position::GetPositionZ(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasAura(), Object::HasFlag(), Unit::HasUnitState(), Unit::IsNonMeleeSpellCast(), Unit::IsValidAttackTarget(), ScriptedAI::me, SelectNewTarget(), SPELL_TEAR_GAS_CREATURE, targetGUID, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, and UNIT_STATE_CASTING.
Member Data Documentation
_hitTargetSpellId
uint32 npc_putricide_oozeAI::_hitTargetSpellId private
Definition at line 825 of file boss_professor_putricide.cpp.
Referenced by SpellHitTarget().
_newTargetSelectTimer
uint32 npc_putricide_oozeAI::_newTargetSelectTimer private
Definition at line 826 of file boss_professor_putricide.cpp.
Referenced by SelectNewTarget(), SpellHitTarget(), and UpdateAI().
targetGUID
ObjectGuid npc_putricide_oozeAI::targetGUID
Definition at line 749 of file boss_professor_putricide.cpp.
Referenced by SelectNewTarget(), SetGUID(), and UpdateAI().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp