Azerotcore-wotlk: cheat_commandscript Class Reference
cheat_commandscript Class Reference
Public Member Functions
cheat_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGodModeCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleCasttimeCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleCoolDownCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandlePowerCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleCheatStatusCommand (ChatHandler *handler)
static bool HandleWaterWalkCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleTaxiCheatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleExploreCheatCommand (ChatHandler *handler, bool reveal)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 26 of file cs_cheat.cpp.
Constructor & Destructor Documentation
cheat_commandscript()
cheat_commandscript::cheat_commandscript () inline
Definition at line 29 of file cs_cheat.cpp.
 : CommandScript("cheat_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable cheat_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 31 of file cs_cheat.cpp.
     {
         static ChatCommandTable cheatCommandTable =
         {
             { "god",       HandleGodModeCheatCommand,   SEC_GAMEMASTER, Console::No },
             { "casttime",  HandleCasttimeCheatCommand,  SEC_GAMEMASTER, Console::No },
             { "cooldown",  HandleCoolDownCheatCommand,  SEC_GAMEMASTER, Console::No },
             { "power",     HandlePowerCheatCommand,     SEC_GAMEMASTER, Console::No },
             { "waterwalk", HandleWaterWalkCheatCommand, SEC_GAMEMASTER, Console::No },
             { "status",    HandleCheatStatusCommand,    SEC_GAMEMASTER, Console::No },
             { "taxi",      HandleTaxiCheatCommand,      SEC_GAMEMASTER, Console::No },
             { "explore",   HandleExploreCheatCommand,   SEC_GAMEMASTER, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "cheat", cheatCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, and SEC_GAMEMASTER.
HandleCasttimeCheatCommand()
static bool cheat_commandscript::HandleCasttimeCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 72 of file cs_cheat.cpp.
     {
         bool enable = !handler->GetSession()->GetPlayer()->GetCommandStatus(CHEAT_CASTTIME);
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOn(CHEAT_CASTTIME);
             handler->SendSysMessage("CastTime Cheat is ON. Your spells won't have a casttime.");
         }
         else
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOff(CHEAT_CASTTIME);
             handler->SendSysMessage("CastTime Cheat is OFF. Your spells will have a casttime.");
         }
         return true;
     }
References CHEAT_CASTTIME, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::SendSysMessage(), Player::SetCommandStatusOff(), and Player::SetCommandStatusOn().
HandleCheatStatusCommand()
static bool cheat_commandscript::HandleCheatStatusCommand (ChatHandler * handler) inline static
Definition at line 132 of file cs_cheat.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         char const* enabled = "ON";
         char const* disabled = "OFF";
         handler->SendSysMessage(LANG_COMMAND_CHEAT_STATUS);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_GOD, player->GetCommandStatus(CHEAT_GOD) ? enabled : disabled);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_CD, player->GetCommandStatus(CHEAT_COOLDOWN) ? enabled : disabled);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_CT, player->GetCommandStatus(CHEAT_CASTTIME) ? enabled : disabled);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_POWER, player->GetCommandStatus(CHEAT_POWER) ? enabled : disabled);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_WW, player->GetCommandStatus(CHEAT_WATERWALK) ? enabled : disabled);
         handler->PSendSysMessage(LANG_COMMAND_CHEAT_TAXINODES, player->isTaxiCheater() ? enabled : disabled);
         return true;
     }
References CHEAT_CASTTIME, CHEAT_COOLDOWN, CHEAT_GOD, CHEAT_POWER, CHEAT_WATERWALK, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Player::isTaxiCheater(), LANG_COMMAND_CHEAT_CD, LANG_COMMAND_CHEAT_CT, LANG_COMMAND_CHEAT_GOD, LANG_COMMAND_CHEAT_POWER, LANG_COMMAND_CHEAT_STATUS, LANG_COMMAND_CHEAT_TAXINODES, LANG_COMMAND_CHEAT_WW, ChatHandler::PSendSysMessage(), and ChatHandler::SendSysMessage().
HandleCoolDownCheatCommand()
static bool cheat_commandscript::HandleCoolDownCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 92 of file cs_cheat.cpp.
     {
         bool enable = !handler->GetSession()->GetPlayer()->GetCommandStatus(CHEAT_COOLDOWN);
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOn(CHEAT_COOLDOWN);
             handler->SendSysMessage("Cooldown Cheat is ON. You are not on the global cooldown.");
         }
         else
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOff(CHEAT_COOLDOWN);
             handler->SendSysMessage("Cooldown Cheat is OFF. You are on the global cooldown.");
         }
         return true;
     }
References CHEAT_COOLDOWN, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::SendSysMessage(), Player::SetCommandStatusOff(), and Player::SetCommandStatusOn().
HandleExploreCheatCommand()
static bool cheat_commandscript::HandleExploreCheatCommand (ChatHandler * handler, bool reveal) inline static
Definition at line 203 of file cs_cheat.cpp.
     {
         Player* chr = handler->getSelectedPlayer();
         if (!chr)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (reveal)
         {
             handler->PSendSysMessage(LANG_YOU_SET_EXPLORE_ALL, handler->GetNameLink(chr).c_str());
             if (handler->needReportToTarget(chr))
                 ChatHandler(chr->GetSession()).PSendSysMessage(LANG_YOURS_EXPLORE_SET_ALL, handler->GetNameLink().c_str());
         }
         else
         {
             handler->PSendSysMessage(LANG_YOU_SET_EXPLORE_NOTHING, handler->GetNameLink(chr).c_str());
             if (handler->needReportToTarget(chr))
                 ChatHandler(chr->GetSession()).PSendSysMessage(LANG_YOURS_EXPLORE_SET_NOTHING, handler->GetNameLink().c_str());
         }
         for (uint8 i = 0; i < PLAYER_EXPLORED_ZONES_SIZE; ++i)
         {
             if (reveal)
                 handler->GetSession()->GetPlayer()->SetFlag(PLAYER_EXPLORED_ZONES_1+i, 0xFFFFFFFF);
             else
                 handler->GetSession()->GetPlayer()->SetFlag(PLAYER_EXPLORED_ZONES_1+i, 0);
         }
         return true;
     }
References ChatHandler::GetNameLink(), WorldSession::GetPlayer(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSession(), Player::GetSession(), LANG_NO_CHAR_SELECTED, LANG_YOU_SET_EXPLORE_ALL, LANG_YOU_SET_EXPLORE_NOTHING, LANG_YOURS_EXPLORE_SET_ALL, LANG_YOURS_EXPLORE_SET_NOTHING, ChatHandler::needReportToTarget(), PLAYER_EXPLORED_ZONES_1, PLAYER_EXPLORED_ZONES_SIZE, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), Object::SetFlag(), and ChatHandler::SetSentErrorMessage().
HandleGodModeCheatCommand()
static bool cheat_commandscript::HandleGodModeCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 52 of file cs_cheat.cpp.
     {
         bool enable = !handler->GetSession()->GetPlayer()->GetCommandStatus(CHEAT_GOD);
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOn(CHEAT_GOD);
             handler->SendSysMessage("Godmode is ON. You won't take damage.");
         }
         else
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOff(CHEAT_GOD);
             handler->SendSysMessage("Godmode is OFF. You can take damage.");
         }
         return true;
     }
References CHEAT_GOD, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::SendSysMessage(), Player::SetCommandStatusOff(), and Player::SetCommandStatusOn().
HandlePowerCheatCommand()
static bool cheat_commandscript::HandlePowerCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 112 of file cs_cheat.cpp.
     {
         bool enable = !handler->GetSession()->GetPlayer()->GetCommandStatus(CHEAT_POWER);
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOn(CHEAT_POWER);
             handler->SendSysMessage("Power Cheat is ON. You don't need mana/rage/energy to use spells.");
         }
         else
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOff(CHEAT_POWER);
             handler->SendSysMessage("Power Cheat is OFF. You need mana/rage/energy to use spells.");
         }
         return true;
     }
References CHEAT_POWER, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::SendSysMessage(), Player::SetCommandStatusOff(), and Player::SetCommandStatusOn().
HandleTaxiCheatCommand()
static bool cheat_commandscript::HandleTaxiCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 172 of file cs_cheat.cpp.
     {
         Player* chr = handler->getSelectedPlayer();
         if (!chr)
             chr = handler->GetSession()->GetPlayer();
         else if (handler->HasLowerSecurity(chr, ObjectGuid::Empty)) // check online security
             return false;
         bool enable = !chr->isTaxiCheater();
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             chr->SetTaxiCheater(true);
             handler->PSendSysMessage(LANG_YOU_GIVE_TAXIS, handler->GetNameLink(chr).c_str());
             if (handler->needReportToTarget(chr))
                 ChatHandler(chr->GetSession()).PSendSysMessage(LANG_YOURS_TAXIS_ADDED, handler->GetNameLink().c_str());
         }
         else
         {
             chr->SetTaxiCheater(false);
             handler->PSendSysMessage(LANG_YOU_REMOVE_TAXIS, handler->GetNameLink(chr).c_str());
             if (handler->needReportToTarget(chr))
                 ChatHandler(chr->GetSession()).PSendSysMessage(LANG_YOURS_TAXIS_REMOVED, handler->GetNameLink().c_str());
         }
         return true;
     }
References ObjectGuid::Empty, ChatHandler::GetNameLink(), WorldSession::GetPlayer(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSession(), Player::GetSession(), ChatHandler::HasLowerSecurity(), Player::isTaxiCheater(), LANG_YOU_GIVE_TAXIS, LANG_YOU_REMOVE_TAXIS, LANG_YOURS_TAXIS_ADDED, LANG_YOURS_TAXIS_REMOVED, ChatHandler::needReportToTarget(), ChatHandler::PSendSysMessage(), and Player::SetTaxiCheater().
HandleWaterWalkCheatCommand()
static bool cheat_commandscript::HandleWaterWalkCheatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
Definition at line 150 of file cs_cheat.cpp.
     {
         bool enable = !handler->GetSession()->GetPlayer()->GetCommandStatus(CHEAT_WATERWALK);
         if (enableArg)
             enable = *enableArg;
         if (enable)
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOn(CHEAT_WATERWALK);
             handler->GetSession()->GetPlayer()->SetMovement(MOVE_WATER_WALK);               // ON
             handler->SendSysMessage("Waterwalking is ON. You can walk on water.");
         }
         else
         {
             handler->GetSession()->GetPlayer()->SetCommandStatusOff(CHEAT_WATERWALK);
             handler->GetSession()->GetPlayer()->SetMovement(MOVE_LAND_WALK);                // OFF
             handler->SendSysMessage("Waterwalking is OFF. You can't walk on water.");
         }
         return true;
     }
References CHEAT_WATERWALK, Player::GetCommandStatus(), WorldSession::GetPlayer(), ChatHandler::GetSession(), MOVE_LAND_WALK, MOVE_WATER_WALK, ChatHandler::SendSysMessage(), Player::SetCommandStatusOff(), Player::SetCommandStatusOn(), and Player::SetMovement().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_cheat.cpp