Azerotcore-wotlk: deps/mysqllite/mysys/my_getsystime.c File Reference
my_getsystime.c File Reference
#include "mysys_priv.h"
#include "my_static.h"
Macros
#define DELTA_FOR_SECONDS 500000000LL /* Half a second */
#define OFFSET_TO_EPOCH 116444736000000000ULL
Functions
ulonglong my_getsystime ()
time_t my_time (myf flags __attribute__((unused)))
ulonglong my_micro_time ()
ulonglong my_micro_time_and_time (time_t *time_arg)
time_t my_time_possible_from_micro (ulonglong microtime __attribute__((unused)))
Macro Definition Documentation
DELTA_FOR_SECONDS
#define DELTA_FOR_SECONDS 500000000LL /* Half a second */
Definition at line 145 of file my_getsystime.c.
OFFSET_TO_EPOCH
#define OFFSET_TO_EPOCH 116444736000000000ULL
Definition at line 148 of file my_getsystime.c.
Function Documentation
my_getsystime()
ulonglong my_getsystime (void)
Definition at line 28 of file my_getsystime.c.
 {
 #ifdef HAVE_CLOCK_GETTIME
   struct timespec tp;
   clock_gettime(CLOCK_REALTIME, &tp);
   return (ulonglong)tp.tv_sec*10000000+(ulonglong)tp.tv_nsec/100;
 #elif defined(__WIN__)
   LARGE_INTEGER t_cnt;
   if (query_performance_frequency)
   {
     QueryPerformanceCounter(&t_cnt);
     return ((t_cnt.QuadPart / query_performance_frequency * 10000000) +
             ((t_cnt.QuadPart % query_performance_frequency) * 10000000 /
              query_performance_frequency) + query_performance_offset);
   }
   return 0;
 #else
   /* TODO: check for other possibilities for hi-res timestamping */
   struct timeval tv;
   gettimeofday(&tv,NULL);
   return (ulonglong)tv.tv_sec*10000000+(ulonglong)tv.tv_usec*10;
 #endif
 }
References endif(), NULL, query_performance_frequency, and query_performance_offset.
my_micro_time()
ulonglong my_micro_time ()
Definition at line 101 of file my_getsystime.c.
 {
 #if defined(__WIN__)
   ulonglong newtime;
   GetSystemTimeAsFileTime((FILETIME*)&newtime);
   return (newtime/10);
 #elif defined(HAVE_GETHRTIME)
   return gethrtime()/1000;
 #else
   ulonglong newtime;
   struct timeval t;
   /*
     The following loop is here because gettimeofday may fail on some systems
   */
   while (gettimeofday(&t, NULL) != 0)
   {}
   newtime= (ulonglong)t.tv_sec * 1000000 + t.tv_usec;
   return newtime;
 #endif  /* defined(__WIN__) */
 }
References endif(), and NULL.
my_micro_time_and_time()
ulonglong my_micro_time_and_time (time_t * time_arg)
Definition at line 150 of file my_getsystime.c.
 {
 #if defined(__WIN__)
   ulonglong newtime;
   GetSystemTimeAsFileTime((FILETIME*)&newtime);
   *time_arg= (time_t) ((newtime - OFFSET_TO_EPOCH) / 10000000);
   return (newtime/10);
 #elif defined(HAVE_GETHRTIME)
   /*
     Solaris has a very slow time() call. We optimize this by using the very
     fast gethrtime() call and only calling time() every 1/2 second
   */
   static hrtime_t prev_gethrtime= 0;
   static time_t cur_time= 0;
   hrtime_t cur_gethrtime;
   mysql_mutex_lock(&THR_LOCK_time);
   cur_gethrtime= gethrtime();
   /*
     Due to bugs in the Solaris (x86) implementation of gethrtime(),
     the time returned by it might not be monotonic. Don't use the
     cached time(2) value if this is a case.
   */
   if ((prev_gethrtime > cur_gethrtime) ||
       ((cur_gethrtime - prev_gethrtime) > DELTA_FOR_SECONDS))
   {
     cur_time= time(0);
     prev_gethrtime= cur_gethrtime;
   }
   *time_arg= cur_time;
   mysql_mutex_unlock(&THR_LOCK_time);
   return cur_gethrtime/1000;
 #else
   ulonglong newtime;
   struct timeval t;
   /*
     The following loop is here because gettimeofday may fail on some systems
   */
   while (gettimeofday(&t, NULL) != 0)
   {}
   *time_arg= t.tv_sec;
   newtime= (ulonglong)t.tv_sec * 1000000 + t.tv_usec;
   return newtime;
 #endif  /* defined(__WIN__) */
 }
References DELTA_FOR_SECONDS, endif(), mysql_mutex_lock, mysql_mutex_unlock, NULL, OFFSET_TO_EPOCH, and THR_LOCK_time.
Referenced by my_time().
my_time()
time_t my_time (myf flags __attribute__(unused))
Definition at line 62 of file my_getsystime.c.
 {
   time_t t;
 #ifdef HAVE_GETHRTIME
   (void) my_micro_time_and_time(&t);
   return t;
 #else
   /* The following loop is here beacuse time() may fail on some systems */
   while ((t= time(0)) == (time_t) -1)
   {
     if (flags & MY_WME)
       fprintf(stderr, "%s: Warning: time() call failed\n", my_progname);
   }
   return t;
 #endif
 }
References fprintf(), my_micro_time_and_time(), my_progname, and MY_WME.
Referenced by my_time_possible_from_micro().
my_time_possible_from_micro()
time_t my_time_possible_from_micro (ulonglong microtime __attribute__(unused))
Definition at line 213 of file my_getsystime.c.
 {
 #if defined(__WIN__)
   time_t t;
   while ((t= time(0)) == (time_t) -1)
   {}
   return t;
 #elif defined(HAVE_GETHRTIME)
   return my_time(0);                            /* Cached time */
 #else
   return (time_t) (microtime / 1000000);
 #endif  /* defined(__WIN__) */
 }
References my_time().