Azerotcore-wotlk: npc_adventurous_dwarf Class Reference
npc_adventurous_dwarf Class Reference
Classes
struct npc_adventurous_dwarfAI
Public Member Functions
npc_adventurous_dwarf ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1076 of file zone_sholazar_basin.cpp.
Constructor & Destructor Documentation
npc_adventurous_dwarf()
npc_adventurous_dwarf::npc_adventurous_dwarf () inline
Definition at line 1079 of file zone_sholazar_basin.cpp.
 : CreatureScript("npc_adventurous_dwarf") { }
Member Function Documentation
GetAI()
CreatureAI* npc_adventurous_dwarf::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 1089 of file zone_sholazar_basin.cpp.
     {
         return new npc_adventurous_dwarfAI(creature);
     }
OnGossipHello()
bool npc_adventurous_dwarf::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1094 of file zone_sholazar_basin.cpp.
     {
         if (player->GetQuestStatus(QUEST_12634) != QUEST_STATUS_INCOMPLETE)
             return false;
         if (player->GetItemCount(ITEM_ORANGE) < 1)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_OPTION_ORANGE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         if (player->GetItemCount(ITEM_BANANAS) < 2)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_OPTION_BANANAS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
         if (player->GetItemCount(ITEM_PAPAYA) < 1)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_OPTION_PAPAYA, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
         SendGossipMenuFor(player, GOSSIP_MENU_DWARF, creature);
         return true;
     }
References AddGossipItemFor(), Player::GetItemCount(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_MENU_DWARF, GOSSIP_OPTION_BANANAS, GOSSIP_OPTION_ORANGE, GOSSIP_OPTION_PAPAYA, GOSSIP_SENDER_MAIN, ITEM_BANANAS, ITEM_ORANGE, ITEM_PAPAYA, QUEST_12634, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_adventurous_dwarf::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1112 of file zone_sholazar_basin.cpp.
     {
         ClearGossipMenuFor(player);
         uint32 spellId = 0;
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 spellId = SPELL_ADD_ORANGE;
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 spellId = SPELL_ADD_BANANAS;
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 spellId = SPELL_ADD_PAPAYA;
                 break;
         }
         if (spellId)
             player->CastSpell(player, spellId, true);
         creature->AI()->Talk(SAY_DWARF_HELP);
         creature->DespawnOrUnsummon();
         return true;
     }
References Creature::AI(), Unit::CastSpell(), ClearGossipMenuFor(), Creature::DespawnOrUnsummon(), GOSSIP_ACTION_INFO_DEF, SAY_DWARF_HELP, SPELL_ADD_BANANAS, SPELL_ADD_ORANGE, SPELL_ADD_PAPAYA, and CreatureAI::Talk().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_sholazar_basin.cpp