Azerotcore-wotlk: src/server/scripts/Events/childrens_week.cpp File Reference
childrens_week.cpp File Reference
#include "Player.h"
#include "ScriptedCreature.h"
#include "ScriptMgr.h"
#include "SpellAuras.h"
Classes
class npc_winterfin_playmate
struct npc_winterfin_playmate::npc_winterfin_playmateAI
class npc_snowfall_glade_playmate
struct npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI
class npc_the_biggest_tree
struct npc_the_biggest_tree::npc_the_biggest_treeAI
class npc_high_oracle_soo_roo
struct npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI
class npc_elder_kekek
struct npc_elder_kekek::npc_elder_kekekAI
class npc_the_etymidian
struct npc_the_etymidian::npc_the_etymidianAI
class npc_alexstraza_the_lifebinder
struct npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI
class at_bring_your_orphan_to
class npc_cw_area_trigger
struct npc_cw_area_trigger::npc_cw_area_triggerAI
class npc_grizzlemaw_cw_trigger
struct npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI
Enumerations
enum Orphans {
ORPHAN_ORACLE = 33533 , ORPHAN_WOLVAR = 33532 , ORPHAN_BLOOD_ELF = 22817 , ORPHAN_DRAENEI = 22818 ,
ORPHAN_HUMAN = 14305 , ORPHAN_ORCISH = 14444
}
enum Texts {
SAY_NEFARIUS_REND_WIPE = 11 , SAY_SOLAKAR_FIRST_HATCHER = 0 , EMOTE_MASS_ERRUPTION = 0 , EMOTE_LOWHP = 0 ,
EMOTE_FRENZY = 0 , SAY_AGGRO = 0 , SAY_SPAWN = 1 , SAY_SLAY = 2 ,
SAY_DEFEAT = 3 , SAY_SUMMON_MAJ = 4 , SAY_ARRIVAL2_MAJ = 5 , SAY_LAST_ADD = 6 ,
SAY_DEFEAT_2 = 7 , SAY_DEFEAT_3 = 8 , SAY_RAG_SUM_1 = 9 , SAY_RAG_SUM_2 = 10 ,
SAY_ARRIVAL1_RAG = 1 , SAY_ARRIVAL3_RAG = 3 , SAY_SUMMON_MAJ = 0 , SAY_ARRIVAL1_RAG = 1 ,
SAY_ARRIVAL2_MAJ = 2 , SAY_ARRIVAL3_RAG = 3 , SAY_ARRIVAL5_RAG = 4 , SAY_REINFORCEMENTS1 = 5 ,
SAY_REINFORCEMENTS2 = 6 , SAY_HAND = 7 , SAY_WRATH = 8 , SAY_KILL = 9 ,
SAY_MAGMABURST = 10 , EMOTE_SMOLDERING = 0 , EMOTE_IGNITE = 1 , TEXT_ORACLE_ORPHAN_1 = 1 ,
TEXT_ORACLE_ORPHAN_2 = 2 , TEXT_ORACLE_ORPHAN_3 = 3 , TEXT_ORACLE_ORPHAN_4 = 4 , TEXT_ORACLE_ORPHAN_5 = 5 ,
TEXT_ORACLE_ORPHAN_6 = 6 , TEXT_ORACLE_ORPHAN_7 = 7 , TEXT_ORACLE_ORPHAN_8 = 8 , TEXT_ORACLE_ORPHAN_9 = 9 ,
TEXT_ORACLE_ORPHAN_10 = 10 , TEXT_ORACLE_ORPHAN_11 = 11 , TEXT_ORACLE_ORPHAN_12 = 12 , TEXT_ORACLE_ORPHAN_13 = 13 ,
TEXT_ORACLE_ORPHAN_14 = 14 , TEXT_WOLVAR_ORPHAN_1 = 1 , TEXT_WOLVAR_ORPHAN_2 = 2 , TEXT_WOLVAR_ORPHAN_3 = 3 ,
TEXT_WOLVAR_ORPHAN_4 = 4 , TEXT_WOLVAR_ORPHAN_5 = 5 , TEXT_WOLVAR_ORPHAN_10 = 10 , TEXT_WOLVAR_ORPHAN_11 = 11 ,
TEXT_WOLVAR_ORPHAN_12 = 12 , TEXT_WOLVAR_ORPHAN_13 = 13 , TEXT_WINTERFIN_PLAYMATE_1 = 1 , TEXT_WINTERFIN_PLAYMATE_2 = 2 ,
TEXT_SNOWFALL_GLADE_PLAYMATE_1 = 1 , TEXT_SNOWFALL_GLADE_PLAYMATE_2 = 2 , TEXT_SOO_ROO_1 = 1 , TEXT_ELDER_KEKEK_1 = 1 ,
TEXT_ALEXSTRASZA_2 = 2 , TEXT_KRASUS_8 = 8 , SAY_ONDEATH = 0 , SAY_ONSLAY = 1 ,
SAY_SWARM = 2 , SAY_SLEEP = 3 , SAY_INFERNO = 4 , SAY_ONAGGRO = 5 ,
SAY_AGGRO = 1 , SAY_DOOMFIRE = 2 , SAY_AIR_BURST = 3 , SAY_SLAY = 4 ,
SAY_ENRAGE = 5 , SAY_DEATH = 6 , SAY_SOUL_CHARGE = 7 , SAY_ONDEATH = 0 ,
SAY_ONSLAY = 1 , SAY_DOOM = 2 , SAY_ONAGGRO = 3 , SAY_ONSLAY = 0 ,
SAY_MARK = 1 , SAY_ONAGGRO = 2 , SAY_ONDEATH = 0 , SAY_ONSLAY = 1 ,
SAY_DECAY = 2 , SAY_NOVA = 3 , SAY_ONAGGRO = 4 , SAY_KURINAXX_DEATH = 5 ,
EMOTE_AGGRO = 0 , EMOTE_MANA_FULL = 1 , SAY_SUPREME = 0 , SAY_INTRO = 1 ,
SAY_AGGRO = 2 , SAY_SLAY = 3 , SAY_DEATH = 4 , SAY_MATRIARCH_AGGRO = 0 ,
SAY_VOLUNTEER_START = 0 , SAY_VOLUNTEER_END = 1 , SAY_AGGRO = 0 , SAY_INSANITY = 1 ,
SAY_SLAY_1 = 2 , SAY_SLAY_2 = 3 , SAY_SLAY_3 = 4 , SAY_DEATH_1 = 5 ,
SAY_DEATH_2 = 6 , WHISPER_AGGRO = 7 , WHISPER_INSANITY = 8 , WHISPER_SLAY_1 = 9 ,
WHISPER_SLAY_2 = 10 , WHISPER_SLAY_3 = 11 , WHISPER_DEATH_1 = 12 , WHISPER_DEATH_2 = 13 ,
SAY_BALTHARUS_INTRO = 0 , SAY_AGGRO = 1 , SAY_KILL = 2 , SAY_CLONE = 3 ,
SAY_DEATH = 4 , SAY_XERESTRASZA_EVENT = 0 , SAY_XERESTRASZA_EVENT_1 = 1 , SAY_XERESTRASZA_EVENT_2 = 2 ,
SAY_XERESTRASZA_EVENT_3 = 3 , SAY_XERESTRASZA_EVENT_4 = 4 , SAY_XERESTRASZA_EVENT_5 = 5 , SAY_XERESTRASZA_EVENT_6 = 6 ,
SAY_XERESTRASZA_EVENT_7 = 7 , SAY_XERESTRASZA_INTRO = 8 , SAY_AGGRO = 0 , SAY_KILL = 1 ,
SAY_ADDS = 2 , SAY_DEATH = 3 , SAY_REGENERATE = 0 , SAY_INTRO = 1 ,
SAY_AGGRO = 2 , SAY_METEOR_STRIKE = 3 , SAY_PHASE_TWO = 4 , SAY_DEATH = 5 ,
SAY_KILL = 6 , SAY_BERSERK = 7 , EMOTE_CORPOREALITY_POT = 8 , EMOTE_CORPOREALITY_PIP = 9 ,
SAY_SPHERE_PULSE = 1 , SAY_PHASE_THREE = 2 , EMOTE_CORPOREALITY_TIT = 3 , EMOTE_CORPOREALITY_TOT = 4 ,
EMOTE_WARN_LASER = 5 , SAY_AGGRO = 0 , SAY_CONFLAGRATION = 1 , EMOTE_ENRAGED = 2 ,
SAY_KILL = 3 , SAY_AGGRO = 53 , SAY_SLAY_1 = 54 , SAY_SLAY_2 = 55 ,
SAY_DEATH = 56 , SAY_MARK = 57 , SAY_SMASH = 58 , EMOTE_RIMEFANG_ICEBOLT = 59 ,
EMOTE_SMASH = 60 , SAY_INTRO_1 = 0 , SAY_INTRO_2 = 1 , SAY_KELESETH_INVOCATION = 0 ,
EMOTE_KELESETH_INVOCATION = 1 , SAY_KELESETH_SPECIAL = 2 , SAY_KELESETH_KILL = 3 , EMOTE_KELESETH_BERSERK = 4 ,
SAY_KELESETH_DEATH = 5 , SAY_TALDARAM_INVOCATION = 0 , EMOTE_TALDARAM_INVOCATION = 1 , SAY_TALDARAM_SPECIAL = 2 ,
EMOTE_TALDARAM_FLAME = 3 , SAY_TALDARAM_KILL = 4 , EMOTE_TALDARAM_BERSERK = 5 , EMOTE_TALDARAM_DEATH = 6 ,
SAY_VALANAR_INVOCATION = 0 , EMOTE_VALANAR_INVOCATION = 1 , SAY_VALANAR_SPECIAL = 2 , EMOTE_VALANAR_SHOCK_VORTEX = 3 ,
SAY_VALANAR_KILL = 4 , SAY_VALANAR_BERSERK = 5 , SAY_VALANAR_DEATH = 6 , SAY_AGGRO = 0 ,
SAY_VAMPIRIC_BITE = 1 , SAY_MIND_CONTROL = 2 , EMOTE_BLOODTHIRST = 3 , SAY_SWARMING_SHADOWS = 4 ,
EMOTE_SWARMING_SHADOWS = 5 , SAY_PACT_OF_THE_DARKFALLEN = 6 , SAY_AIR_PHASE = 7 , SAY_KILL = 8 ,
SAY_WIPE = 9 , SAY_BERSERK = 10 , SAY_DEATH = 11 , EMOTE_BERSERK_RAID = 12 ,
SAY_SAURFANG_INTRO_1 = 0 , SAY_SAURFANG_INTRO_2 = 1 , SAY_SAURFANG_INTRO_3 = 2 , SAY_SAURFANG_INTRO_4 = 3 ,
SAY_SAURFANG_INTRO_5 = 4 , SAY_SAURFANG_INTRO_6 = 5 , SAY_SAURFANG_INTRO_A = 6 , SAY_SAURFANG_BOARD = 7 ,
SAY_SAURFANG_ENTER_SKYBREAKER = 8 , SAY_SAURFANG_AXETHROWERS = 9 , SAY_SAURFANG_ROCKETEERS = 10 , SAY_SAURFANG_MAGES = 11 ,
SAY_SAURFANG_VICTORY = 12 , SAY_SAURFANG_WIPE = 13 , SAY_MURADIN_INTRO_1 = 0 , SAY_MURADIN_INTRO_2 = 1 ,
SAY_MURADIN_INTRO_3 = 2 , SAY_MURADIN_INTRO_4 = 3 , SAY_MURADIN_INTRO_5 = 4 , SAY_MURADIN_INTRO_6 = 5 ,
SAY_MURADIN_INTRO_7 = 6 , SAY_MURADIN_INTRO_H = 7 , SAY_MURADIN_BOARD = 8 , SAY_MURADIN_ENTER_ORGRIMMS_HAMMER = 9 ,
SAY_MURADIN_RIFLEMAN = 10 , SAY_MURADIN_MORTAR = 11 , SAY_MURADIN_SORCERERS = 12 , SAY_MURADIN_VICTORY = 13 ,
SAY_MURADIN_WIPE = 14 , SAY_ZAFOD_ROCKET_PACK_ACTIVE = 0 , SAY_ZAFOD_ROCKET_PACK_DISABLED = 1 , SAY_OVERHEAT = 0 ,
SAY_PRECIOUS_DIES = 0 , SAY_AGGRO = 1 , EMOTE_SLIME_SPRAY = 2 , SAY_SLIME_SPRAY = 3 ,
EMOTE_UNSTABLE_EXPLOSION = 4 , SAY_UNSTABLE_EXPLOSION = 5 , SAY_KILL = 6 , SAY_BERSERK = 7 ,
SAY_DEATH = 8 , EMOTE_MUTATED_INFECTION = 9 , SAY_ROTFACE_OOZE_FLOOD = 2 , EMOTE_PRECIOUS_ZOMBIES = 0 ,
SAY_AGGRO = 0 , SAY_UNCHAINED_MAGIC = 1 , EMOTE_WARN_BLISTERING_COLD = 2 , SAY_BLISTERING_COLD = 3 ,
SAY_RESPITE_FOR_A_TORMENTED_SOUL = 4 , SAY_AIR_PHASE = 5 , SAY_PHASE_2 = 6 , EMOTE_WARN_FROZEN_ORB = 7 ,
SAY_KILL = 8 , SAY_BERSERK = 9 , SAY_DEATH = 10 , EMOTE_BERSERK_RAID = 11 ,
EMOTE_WEAKENING = 101 , SAY_LK_INTRO_1 = 0 , SAY_LK_INTRO_2 = 1 , SAY_LK_INTRO_3 = 2 ,
SAY_LK_REMORSELESS_WINTER = 4 , SAY_LK_QUAKE = 5 , SAY_LK_SUMMON_VALKYR = 6 , SAY_LK_HARVEST_SOUL = 7 ,
SAY_LK_FROSTMOURNE_ESCAPE = 8 , SAY_LK_FROSTMOURNE_KILL = 9 , SAY_LK_KILL = 10 , SAY_LK_BERSERK = 11 ,
EMOTE_DEFILE_WARNING = 12 , EMOTE_NECROTIC_PLAGUE_WARNING = 13 , SAY_LK_OUTRO_1 = 14 , SAY_LK_OUTRO_2 = 15 ,
SAY_LK_OUTRO_3 = 16 , SAY_LK_OUTRO_4 = 17 , SAY_LK_OUTRO_5 = 18 , SAY_LK_OUTRO_6 = 19 ,
SAY_LK_OUTRO_7 = 20 , SAY_LK_OUTRO_8 = 21 , SAY_TIRION_INTRO_1 = 0 , SAY_TIRION_INTRO_2 = 1 ,
SAY_TIRION_OUTRO_1 = 2 , SAY_TIRION_OUTRO_2 = 3 , SAY_TERENAS_OUTRO_1 = 0 , SAY_TERENAS_OUTRO_2 = 1 ,
SAY_TERENAS_INTRO_1 = 0 , SAY_TERENAS_INTRO_2 = 1 , SAY_TERENAS_INTRO_3 = 2 , SAY_LICH_KING_INTRO = 0 ,
SAY_VALITHRIA_ENTER_COMBAT = 0 , SAY_VALITHRIA_DREAM_PORTAL = 1 , SAY_VALITHRIA_75_PERCENT = 2 , SAY_VALITHRIA_25_PERCENT = 3 ,
SAY_VALITHRIA_DEATH = 4 , SAY_VALITHRIA_PLAYER_DEATH = 5 , SAY_VALITHRIA_BERSERK = 6 , SAY_VALITHRIA_SUCCESS = 7 ,
SAY_TIRION_INTRO_1 = 0 , SAY_TIRION_INTRO_2 = 1 , SAY_TIRION_INTRO_3 = 2 , SAY_TIRION_INTRO_4 = 3 ,
SAY_TIRION_INTRO_H_5 = 4 , SAY_TIRION_INTRO_A_5 = 5 , SAY_LK_INTRO_1 = 0 , SAY_LK_INTRO_2 = 1 ,
SAY_LK_INTRO_3 = 2 , SAY_LK_INTRO_4 = 3 , SAY_LK_INTRO_5 = 4 , SAY_BOLVAR_INTRO_1 = 0 ,
SAY_SAURFANG_INTRO_1 = 15 , SAY_SAURFANG_INTRO_2 = 16 , SAY_SAURFANG_INTRO_3 = 17 , SAY_SAURFANG_INTRO_4 = 18 ,
SAY_MURADIN_INTRO_1 = 13 , SAY_MURADIN_INTRO_2 = 14 , SAY_MURADIN_INTRO_3 = 15 , SAY_TRAP_ACTIVATE = 0 ,
EMOTE_DEATH_PLAGUE_WARNING = 0 , SAY_SVALNA_KILL_CAPTAIN = 1 , SAY_SVALNA_KILL = 4 , SAY_SVALNA_CAPTAIN_DEATH = 5 ,
SAY_SVALNA_DEATH = 6 , EMOTE_SVALNA_IMPALE = 7 , EMOTE_SVALNA_BROKEN_SHIELD = 8 , SAY_CROK_INTRO_1 = 0 ,
SAY_ARNATH_INTRO_2 = 5 , SAY_CROK_INTRO_3 = 1 , SAY_SVALNA_EVENT_START = 0 , SAY_CROK_COMBAT_WP_0 = 2 ,
SAY_CROK_COMBAT_WP_1 = 3 , SAY_CROK_FINAL_WP = 4 , SAY_SVALNA_RESURRECT_CAPTAINS = 2 , SAY_CROK_COMBAT_SVALNA = 5 ,
SAY_SVALNA_AGGRO = 3 , SAY_CAPTAIN_DEATH = 0 , SAY_CAPTAIN_RESURRECTED = 1 , SAY_CAPTAIN_KILL = 2 ,
SAY_CAPTAIN_SECOND_DEATH = 3 , SAY_CAPTAIN_SURVIVE_TALK = 4 , SAY_CROK_WEAKENING_GAUNTLET = 6 , SAY_CROK_WEAKENING_SVALNA = 7 ,
SAY_CROK_DEATH = 8 , SAY_ONBOARD = 0 , SAY_NECROTIC_AURA_APPLIED = 0 , SAY_NECROTIC_AURA_REMOVED = 1 ,
SAY_NECROTIC_AURA_FADING = 2 , SAY_INTRO = 0 , SAY_PHASE_1 , SAY_DEEP_BREATH ,
SAY_SLAY_P1 , SAY_END_P1 , SAY_PHASE_2 , SAY_ANTIMAGIC_SHELL ,
SAY_MAGIC_BLAST , SAY_SLAY_P2 , SAY_END_P2 , SAY_INTRO_PHASE_3 ,
SAY_PHASE_3 , EMOTE_SURGE_OF_POWER_WARNING_P2 , SAY_SURGE_OF_POWER , SAY_BUFFED_BY_SPARK ,
SAY_SLAY_P3 , SAY_SPELL_CASTING_P3 , SAY_DEATH , EMOTE_SURGE_OF_POWER_WARNING_P3 ,
EMOTE_BERSERK , EMOTE_POWER_SPARK = 0 , SAY_ALEXSTRASZA_ONE = 0 , SAY_ALEXSTRASZA_TWO = 1 ,
SAY_ALEXSTRASZA_THREE = 2 , SAY_ALEXSTRASZA_FOUR = 3 , SAY_BRANN_ALGALON_INTRO_1 = 0 , SAY_BRANN_ALGALON_INTRO_2 = 1 ,
SAY_BRANN_ALGALON_OUTRO = 2 , SAY_ALGALON_INTRO_1 = 0 , SAY_ALGALON_INTRO_2 = 1 , SAY_ALGALON_INTRO_3 = 2 ,
SAY_ALGALON_START_TIMER = 3 , SAY_ALGALON_AGGRO = 4 , SAY_ALGALON_COLLAPSING_STAR = 5 , EMOTE_ALGALON_COLLAPSING_STAR = 6 ,
SAY_ALGALON_BIG_BANG = 7 , EMOTE_ALGALON_BIG_BANG = 8 , SAY_ALGALON_ASCEND = 9 , EMOTE_ALGALON_COSMIC_SMASH = 10 ,
SAY_ALGALON_PHASE_TWO = 11 , SAY_ALGALON_OUTRO_1 = 12 , SAY_ALGALON_OUTRO_2 = 13 , SAY_ALGALON_OUTRO_3 = 14 ,
SAY_ALGALON_OUTRO_4 = 15 , SAY_ALGALON_OUTRO_5 = 16 , SAY_ALGALON_DESPAWN_1 = 17 , SAY_ALGALON_DESPAWN_2 = 18 ,
SAY_ALGALON_DESPAWN_3 = 19 , SAY_ALGALON_KILL = 20 , FLAME_LEVIATHAN_SAY_AGGRO = 0 , FLAME_LEVIATHAN_SAY_SLAY ,
FLAME_LEVIATHAN_SAY_DEATH , FLAME_LEVIATHAN_SAY_PURSUE , FLAME_LEVIATHAN_SAY_HARDMODE , FLAME_LEVIATHAN_SAY_TOWER_NONE ,
FLAME_LEVIATHAN_SAY_TOWER_FROST , FLAME_LEVIATHAN_SAY_TOWER_FLAME , FLAME_LEVIATHAN_SAY_TOWER_NATURE , FLAME_LEVIATHAN_SAY_TOWER_STORM ,
FLAME_LEVIATHAN_SAY_PLAYER_RIDING , FLAME_LEVIATHAN_SAY_OVERLOAD , FLAME_LEVIATHAN_EMOTE_PURSUE , FLAME_LEVIATHAN_EMOTE_OVERLOAD ,
FLAME_LEVIATHAN_EMOTE_REPAIR , SAY_AGGRO = 0 , SAY_KILL = 1 , SAY_DEATH = 2 ,
EMOTE_DARK_SHELL = 3 , SAY_INTRO = 0 , SAY_AGGRO = 1 , SAY_SURPREME = 2 ,
SAY_KILL = 3 , SAY_DEATH = 4 , EMOTE_FRENZY = 5 , SAY_RAND = 6 ,
SAY_AGGRO = 0 , SAY_EARTHQUAKE = 1 , SAY_OVERRUN = 2 , SAY_SLAY = 3 ,
SAY_DEATH = 4
}
enum Quests {
QUEST_SPECTRAL_CHALICE = 4083 , QUEST_PLAYMATE_WOLVAR = 13951 , QUEST_PLAYMATE_ORACLE = 13950 , QUEST_THE_BIGGEST_TREE_EVER = 13929 ,
QUEST_THE_BRONZE_DRAGONSHRINE_ORACLE = 13933 , QUEST_THE_BRONZE_DRAGONSHRINE_WOLVAR = 13934 , QUEST_MEETING_A_GREAT_ONE = 13956 , QUEST_THE_MIGHTY_HEMET_NESINGWARY = 13957 ,
QUEST_DOWN_AT_THE_DOCKS = 910 , QUEST_GATEWAY_TO_THE_FRONTIER = 911 , QUEST_BOUGHT_OF_ETERNALS = 1479 , QUEST_SPOOKY_LIGHTHOUSE = 1687 ,
QUEST_STONEWROUGHT_DAM = 1558 , QUEST_DARK_PORTAL_H = 10951 , QUEST_DARK_PORTAL_A = 10952 , QUEST_LORDAERON_THRONE_ROOM = 1800 ,
QUEST_AUCHINDOUN_AND_THE_RING = 10950 , QUEST_TIME_TO_VISIT_THE_CAVERNS_H = 10963 , QUEST_TIME_TO_VISIT_THE_CAVERNS_A = 10962 , QUEST_THE_SEAT_OF_THE_NARUU = 10956 ,
QUEST_CALL_ON_THE_FARSEER = 10968 , QUEST_JHEEL_IS_AT_AERIS_LANDING = 10954 , QUEST_HCHUU_AND_THE_MUSHROOM_PEOPLE = 10945 , QUEST_VISIT_THE_THRONE_OF_ELEMENTS = 10953 ,
QUEST_NOW_WHEN_I_GROW_UP = 11975 , QUEST_HOME_OF_THE_BEAR_MEN = 13930 , QUEST_THE_DRAGON_QUEEN_ORACLE = 13954 , QUEST_THE_DRAGON_QUEEN_WOLVAR = 13955 ,
QUEST_PILGRIM_HORDE = 24541 , QUEST_PILGRIM_ALLIANCE = 24656 , QUEST_GUARDIANS_ALTAR = 4901
}
enum Areatriggers {
AT_DOWN_AT_THE_DOCKS = 3551 , AT_GATEWAY_TO_THE_FRONTIER = 3549 , AT_LORDAERON_THRONE_ROOM = 3547 , AT_BOUGHT_OF_ETERNALS = 3546 ,
AT_SPOOKY_LIGHTHOUSE = 3552 , AT_STONEWROUGHT_DAM = 3548 , AT_DARK_PORTAL = 4356 , NPC_CAVERNS_OF_TIME_CW_TRIGGER = 22872 ,
NPC_EXODAR_01_CW_TRIGGER = 22851 , NPC_EXODAR_02_CW_TRIGGER = 22905 , NPC_AERIS_LANDING_CW_TRIGGER = 22838 , NPC_AUCHINDOUN_CW_TRIGGER = 22831 ,
NPC_SPOREGGAR_CW_TRIGGER = 22829 , NPC_THRONE_OF_ELEMENTS_CW_TRIGGER = 22839 , NPC_SILVERMOON_01_CW_TRIGGER = 22866 , NPC_KRASUS = 27990
}
enum Misc {
DATA_SKILLPOINT_MIN = 230 , NEFARIUS_PATH_2 = 1379671 , NEFARIUS_PATH_3 = 1379672 , GYTH_PATH_1 = 1379681 ,
NEFARIUS_PATH_1 = 1379670 , NEFARIUS_PATH_2 = 1379671 , NEFARIUS_PATH_3 = 1379672 , REND_PATH_1 = 1379680 ,
REND_PATH_2 = 1379681 , TEXT_ID_SUMMON_1 = 4995 , TEXT_ID_SUMMON_2 = 5011 , TEXT_ID_SUMMON_3 = 5012 ,
GOSSIP_ITEM_SUMMON_1 = 4093 , GOSSIP_ITEM_SUMMON_2 = 4109 , GOSSIP_ITEM_SUMMON_3 = 4108 , FACTION_MAJORDOMO_FRIENDLY = 1080 ,
SUMMON_GROUP_ADDS = 1 , POINT_RAGNAROS_SUMMON = 1 , PHASE_NONE = 1 , PHASE_COMBAT = 2 ,
PHASE_DEFEAT_OUTRO = 3 , PHASE_RAGNAROS_SUMMONING = 4 , MAX_SON_OF_FLAME_COUNT = 8 , EVENT_GUEST_TALK = 1 ,
EVENT_GUEST_TALK2 = 2 , EVENT_SPELL_VANISH = 3 , EVENT_SPELL_GARROTE = 4 , EVENT_SPELL_BLIND = 5 ,
EVENT_SPELL_GOUGE = 6 , EVENT_CHECK_HEALTH = 7 , EVENT_SPELL_ENRAGE = 8 , EVENT_KILL_TALK = 9 ,
ACTIVE_GUEST_COUNT = 4 , MAX_GUEST_COUNT = 6 , EVENT_INIT_COMBAT = 1 , EVENT_SPELL_FIREBALL = 2 ,
EVENT_SPELL_PHOENIX = 3 , EVENT_SPELL_FLAMESTRIKE = 4 , EVENT_SPELL_SHOCK_BARRIER = 5 , EVENT_CHECK_HEALTH = 6 ,
EVENT_GRAVITY_LAPSE_1_1 = 7 , EVENT_GRAVITY_LAPSE_1_2 = 8 , EVENT_GRAVITY_LAPSE_2 = 9 , EVENT_GRAVITY_LAPSE_3 = 10 ,
EVENT_GRAVITY_LAPSE_4 = 11 , EVENT_GRAVITY_LAPSE_5 = 12 , EVENT_FINISH_TALK = 13 , ACTION_TELEPORT_PLAYERS = 1 ,
ACTION_KNOCKUP = 2 , ACTION_ALLOW_FLY = 3 , ACTION_REMOVE_FLY = 4 , CREATURE_ARCANE_SPHERE = 24708 ,
MAX_ACTIVE_HELPERS = 4 , MAX_HELPERS_COUNT = 8 , NPC_PURE_ENERGY = 24745 , INTERVAL_MODIFIER = 15 ,
INTERVAL_SWITCH = 6 , EVENT_SPELL_CHAIN_LIGHTNING = 1 , EVENT_SPELL_ARCANE_SHOCK = 2 , EVENT_HEALTH_CHECK = 3 ,
WEAPON_KIRTONOS_STAFF = 11365 , POINT_KIRTONOS_LAND = 13 , KIRTONOS_PATH = 105061 , EMOTE_SUMMONED = 0 ,
EVENT_SPELL_SLASH = 1 , EVENT_SPELL_STOMP = 2 , EVENT_SPELL_BURN = 3 , EVENT_SPELL_BERSERK = 4 ,
ACTION_START_EVENT = 1 , ACTION_SPAWN_FELMYST = 2 , ACTION_SISTER_DIED = 1 , EVENT_SPELL_SHADOW_BLADES = 1 ,
EVENT_SPELL_SHADOW_NOVA = 2 , EVENT_SPELL_CONFOUNDING_BLOW = 3 , EVENT_SHADOW_IMAGE = 4 , EVENT_SPELL_ENRAGE = 5 ,
EVENT_SPELL_CONFLAGRATION = 6 , EVENT_SPELL_BLAZE = 7 , EVENT_SPELL_PYROGENICS = 8 , EVENT_SPELL_FLAME_SEAR = 9 ,
EVENT_SPELL_BERSERK = 1 , EVENT_SPELL_CLEAVE = 2 , EVENT_SPELL_CORROSION = 3 , EVENT_SPELL_GAS_NOVA = 4 ,
EVENT_SPELL_ENCAPSULATE = 5 , EVENT_FLIGHT = 6 , EVENT_LAND = 7 , EVENT_RESTORE_COMBAT = 8 ,
EVENT_RESTORE_COMBAT2 = 9 , EVENT_FLIGHT_SEQ = 100 , EVENT_FLIGHT_VAPOR = 101 , EVENT_FLIGHT_MOVE_UP = 102 ,
EVENT_LAND_FIGHT = 103 , EVENT_FLIGHT_EMOTE = 104 , EVENT_FLIGHT_BREATH1 = 105 , EVENT_FLIGHT_BREATH2 = 106 ,
EVENT_FLIGHT_FLYOVER1 = 107 , EVENT_FLIGHT_FLYOVER2 = 108 , EVENT_CORRUPT_TRIGGERS = 109 , EVENT_INTRO_1 = 20 ,
EVENT_INTRO_2 = 21 , EVENT_INTRO_3 = 22 , EVENT_INTRO_4 = 23 , ACTION_START_EVENT = 1 ,
POINT_GROUND = 1 , POINT_AIR = 2 , POINT_AIR_BREATH_START1 = 3 , POINT_AIR_BREATH_END1 = 4 ,
POINT_AIR_BREATH_START2 = 5 , POINT_AIR_BREATH_END2 = 6 , POINT_MISC = 7 , NPC_FOG_TRIGGER = 23472 ,
PHASE_DECEIVERS = 1 , PHASE_NORMAL = 2 , PHASE_DARKNESS = 3 , PHASE_ARMAGEDDON = 4 ,
PHASE_SACRIFICE = 5 , EVENT_GROUP_SPEACH = 1 , ACTION_START_POST_EVENT = 1 , ACTION_NO_KILL_TALK = 2 ,
EVENT_TEXT_SPEACH11 = 1 , EVENT_TEXT_SPEACH21 = 2 , EVENT_TEXT_SPEACH22 = 3 , EVENT_TEXT_SPEACH23 = 4 ,
EVENT_TEXT_SPEACH31 = 5 , EVENT_TEXT_SPEACH32 = 6 , EVENT_TEXT_SPEACH33 = 7 , EVENT_TEXT_SPEACH41 = 8 ,
EVENT_TEXT_SPEACH42 = 9 , EVENT_TEXT_SPEACH43 = 10 , EVENT_TEXT_SPEACH44 = 11 , EVENT_TEXT_SPEACH45 = 12 ,
EVENT_TEXT_SPEACH46 = 13 , EVENT_RANDOM_TALK = 40 , EVENT_CHECK_PLAYERS = 41 , EVENT_REBIRTH = 50 ,
EVENT_INIT_FIGHT = 51 , EVENT_CHECK_HEALTH85 = 52 , EVENT_CHECK_HEALTH55 = 53 , EVENT_CHECK_HEALTH25 = 54 ,
EVENT_EMPOWER_ORBS1 = 55 , EVENT_EMPOWER_ORBS2 = 56 , EVENT_EMPOWER_ORBS3 = 57 , EVENT_RESTORE_MELEE = 58 ,
EVENT_KILL_SELF = 59 , EVENT_NO_KILL_TALK = 60 , EVENT_SPELL_SOUL_FLAY = 100 , EVENT_SPELL_LEGION_LIGHTNING = 101 ,
EVENT_SPELL_FIRE_BLOOM = 102 , EVENT_SUMMON_ORBS = 103 , EVENT_SPELL_SHADOW_SPIKE = 104 , EVENT_SPELL_SINISTER_REFLECTION = 105 ,
EVENT_SPELL_FLAME_DART = 106 , EVENT_SPELL_DARKNESS = 107 , EVENT_SPELL_ARMAGEDDON = 108 , EVENT_SPELL_ENRAGE = 1 ,
EVENT_SUMMON_ENTROPIUS = 2 , EVENT_SET_INVISIBLE = 3 , EVENT_SPAWN_BLACK_HOLE = 4 , EVENT_SPAWN_DARKNESS = 5 ,
EVENT_START_BLACK_HOLE = 6 , EVENT_SWITCH_BLACK_HOLE_TARGET = 7 , EVENT_ENTROPIUS_AURAS = 8 , EVENT_ENTROPIUS_COMBAT = 9 ,
EVENT_SINGULARITY_DEATH = 10 , DATA_ENRAGE_TIMER = 1 , DATA_NEGATIVE_ENERGY_TARGETS = 2 , MAX_ENCOUNTER = 7 ,
RAND_VENDOR = 2 , WORLDSTATE_SHOW_TIMER = 3104 , WORLDSTATE_TIME_TO_SACRIFICE = 3106 , MAX_PROWLERS_PER_SIDE = 15 ,
MODEL_OHGAN_MOUNT = 15271 , PATH_MANDOKIR = 492861 , POINT_MANDOKIR_END = 24 , CHAINED_SPIRT_COUNT = 20 ,
EQUIP_ID_MAIN_HAND = 0 , SPELL_SNOWBALL = 21343 , SPELL_ORPHAN_OUT = 58818 , DISPLAY_INVISIBLE = 11686 ,
ENCOUNTER_WAVES_NUMBER = 8 , ENCOUNTER_WAVES_MAX_SPAWNS = 4 , ENCOUNTER_CHRONO_NUMBER = 5 , ENCOUNTER_CHRONO_MAX_SPAWNS_FIRST = 5 ,
ENCOUNTER_CHRONO_MAX_SPAWNS_SECOND = 3 , ACTION_INFECT_CITIZIEN = 1 , ACTION_FORCE_CHANGE_LOCK = 2 , POINT_CHRONOS = 1 ,
THRALL_WEAPON_ITEM = 927 , THRALL_SHIELD_ITEM = 2129 , THRALL_MODEL_UNEQUIPPED = 17292 , THRALL_MODEL_EQUIPPED = 18165 ,
ACTION_SET_IMMUNE_FLAG = 1 , ACTION_REMOVE_IMMUNE_FLAG = 2 , ACTION_TRANSFORM = 3 , ACTION_MOVE = 4 ,
ACTION_START_COMBAT = 5 , SPELL_RIFT_CHANNEL = 31387 , EVENT_NEXT_PORTAL = 1 , EVENT_SUMMON_KEEPER = 2 ,
ACTION_OUTRO = 1 , PULL_RANGE = 50 , ABUSE_BUG_RANGE = 20 , VEKLOR_DIST = 20 ,
TELEPORTTIME = 30000 , PATH_ADDS = 81553 , SAY_BLY_FORWARD = 2 , DATA_RESPECT_YOUR_ELDERS = 1 ,
NPC_TWISTED_VISAGE = 30625 , ACHIEV_QUICK_DEMISE_START_EVENT = 20382 , MAX_INSANITY_TARGETS = 5 , DATA_SET_INSANITY_PHASE = 1 ,
MAX_COMBAT_INITIATES = 25 , DATA_VOLUNTEER_WORK = 1 , MAX_EMBRACE_DMG = 20000 , MAX_EMBRACE_DMG_H = 40000 ,
SUMMON_GROUP_TRIGGERS = 0 , ACHIEV_TIMED_START_EVENT = 20381 , EVENT_CHECK_HEALTH_25 = 1 , EVENT_CHECK_HEALTH_50 = 2 ,
EVENT_CHECK_HEALTH_75 = 3 , EVENT_CARRION_BEETELS = 4 , EVENT_LEECHING_SWARM = 5 , EVENT_IMPALE = 6 ,
EVENT_POUND = 7 , EVENT_CLOSE_DOORS = 8 , EVENT_EMERGE = 9 , EVENT_SUMMON_VENOMANCER = 10 ,
EVENT_SUMMON_DARTER = 11 , EVENT_SUMMON_GUARDIAN = 12 , EVENT_SUMMON_ASSASSINS = 13 , EVENT_ENABLE_ROTATE = 14 ,
EVENT_KILL_TALK = 15 , NPC_ANUB_AR_CRUSHER = 28922 , SAY_CRUSHER_AGGRO = 0 , SAY_CRUSHER_EMOTE = 1 ,
SAY_HADRONOX_EMOTE = 0 , ACTION_DESPAWN_ADDS = 1 , ACTION_START_EVENT = 2 , ACTION_SWITCH_PHASE = 1 ,
ACTION_CALL_DRAGON = 2 , ACTION_DRAKE_DIED = 3 , POINT_FINAL_TENEBRON = 8 , POINT_FINAL_SHADRON = 4 ,
POINT_FINAL_VESPERON = 4 , LAVA_LEFT_SIDE = 0 , LAVA_RIGHT_SIDE = 1 , MAX_LEFT_LAVA_TSUNAMIS = 3 ,
MAX_RIGHT_LAVA_TSUNAMIS = 2 , MAX_DRAGONS = 3 , MAX_AREA_TRIGGER_COUNT = 2 , MAX_CYCLONE_COUNT = 5 ,
MAX_TENEBORN_EGGS_SUMMONS = 6 , MAX_BOUNDARY_POSITIONS = 4 , EVENT_CLEAVE = 1 , EVENT_INTIDMDATING_ROAR = 2 ,
EVENT_SUMMON_ADDS1 = 3 , EVENT_SUMMON_ADDS2 = 4 , EVENT_KILL_TALK = 5 , EVENT_BLAST_NOVA = 6 ,
EVENT_LAVA_GOUT = 7 , MAX_PATH_FLAMECALLER_WAYPOINTS = 12 , ACTION_SHOOT = 1 , ACTION_CHECK_CORPOREALITY = 2 ,
ACTION_RESET_ENCOUNTER = 3 , DATA_TWILIGHT_DAMAGE_TAKEN = 1 , DATA_MATERIAL_DAMAGE_TAKEN = 2 , SEAT_NORTH = 0 ,
SEAT_SOUTH = 1 , SEAT_EAST = 2 , SEAT_WEST = 3 , POINT_FLIGHT = 1 ,
POINT_LAND = 2 , POINT_TAKEOFF = 3 , SOUND_ID_DEATH = 17531 , NPC_DRAKKARI_SCYTHECLAW = 26628 ,
NPC_DRAKKARI_GUTRIPPER = 26641 , SAY_CLAW_EMOTE = 0 , EVENT_SPELL_BELLOWING_ROAR = 1 , EVENT_SPELL_GRIEVOUS_BITE = 2 ,
EVENT_SPELL_MANGLING_SLASH = 3 , EVENT_SPELL_FEARSOME_ROAR = 4 , EVENT_SPELL_PIERCING_SLASH = 5 , EVENT_SPELL_RAPTOR_CALL = 6 ,
EVENT_MENACING_CLAW = 7 , NPC_CRYSTAL_CHANNEL_TARGET = 26712 , NPC_CRYSTAL_HANDLER = 26627 , NPC_SUMMON_CRYSTAL_HANDLER_TARGET = 27583 ,
EVENT_SUMMON_FETID_TROLL = 1 , EVENT_SUMMON_SHADOWCASTER = 2 , EVENT_SUMMON_HULKING_CORPSE = 3 , EVENT_SUMMON_CRYSTAL_HANDLER = 4 ,
EVENT_CAST_OFFENSIVE_SPELL = 5 , EVENT_KILL_TALK = 6 , EVENT_CHECK_PHASE = 7 , EVENT_SPELL_SUMMON_MINIONS = 8 ,
ROOM_RIGHT = 0 , ROOM_LEFT = 1 , ROOM_STAIRS = 2 , ACTION_TURN_BONES = 1 ,
EVENT_SPELL_CURSE_OF_LIFE = 1 , EVENT_SPELL_RAIN_OF_FIRE = 2 , EVENT_SPELL_SHADOW_VOLLEY = 3 , EVENT_SPELL_EYE_BEAM = 4 ,
EVENT_SPELL_LIGHTNING_BREATH = 5 , EVENT_SPELL_POISON_CLOUD = 6 , EVENT_SPELL_TURN_FLESH = 7 , EVENT_TURN_FLESH_REAL = 9 ,
EVENT_TURN_BONES_REAL = 10 , EVENT_KILL_TALK = 11 , NPC_LIVING_MOJO = 29830 , NPC_DRAKKARI_ELEMENTAL = 29573 ,
ACTION_MERGE = 1 , ACTION_INFORM = 2 , POINT_MERGE = 1 , SAY_SURGE = 0 ,
EMOTE_ALTAR = 1 , EVENT_COLOSSUS_MIGHTY_BLOW = 1 , EVENT_COLOSSUS_HEALTH_1 = 2 , EVENT_COLOSSUS_HEALTH_2 = 3 ,
EVENT_COLOSSUS_START_FIGHT = 4 , EVENT_ELEMENTAL_HEALTH = 10 , EVENT_ELEMENTAL_SURGE = 11 , EVENT_ELEMENTAL_VOLLEY = 12 ,
EVENT_MOJO_MOJO_WAVE = 20 , EVENT_MOJO_MOJO_PUDDLE = 21 , POINT_START = 0 , EVENT_ECK_BERSERK = 1 ,
EVENT_ECK_BITE = 2 , EVENT_ECK_SPIT = 3 , EVENT_ECK_SPRING = 4 , EVENT_ECK_HEALTH = 5 ,
NPC_SLADRAN_VIPER = 29680 , NPC_SLADRAN_CONSTRICTORS = 29713 , MAX_VIPER = 2 , MAX_CONSTRICTOR = 3 ,
MAX_SUMMONS = 5 , EVENT_POISON_NOVA = 1 , EVENT_POWERFULL_BITE = 2 , EVENT_VENOM_BOLT = 3 ,
EVENT_CHECK_HEALTH1 = 4 , EVENT_CHECK_HEALTH2 = 5 , EVENT_SUMMON1 = 6 , EVENT_SUMMON2 = 7 ,
EVENT_KILL_TALK = 8 , NPC_CORPSE_SCARAB = 16698 , NPC_CRYPT_GUARD = 16573 , ACHIEV_TIMED_START_EVENT = 9891 ,
NPC_NAXXRAMAS_WORSHIPPER = 16506 , NPC_NAXXRAMAS_FOLLOWER = 16505 , MOVE_PHASE_NONE = 0 , MOVE_PHASE_STARTED = 1 ,
MOVE_PHASE_FINISHED = 2 , HORSEMAN_ZELIEK = 0 , HORSEMAN_BLAUMEUX = 1 , HORSEMAN_RIVENDARE = 2 ,
HORSEMAN_KORTHAZZ = 3 , NPC_ZOMBIE_CHOW = 16360 , NPC_LIVING_TRAINEE = 16124 , NPC_LIVING_KNIGHT = 16125 ,
NPC_LIVING_RIDER = 16126 , NPC_DEAD_TRAINEE = 16127 , NPC_DEAD_KNIGHT = 16148 , NPC_DEAD_HORSE = 16149 ,
NPC_DEAD_RIDER = 16150 , NPC_FALLOUT_SLIME = 16290 , NPC_SEWAGE_SLIME = 16375 , NPC_STICHED_GIANT = 16025 ,
PHASE_SLOW_DANCE = 0 , PHASE_FAST_DANCE = 1 , NPC_SOLDIER_OF_THE_FROZEN_WASTES = 16427 , NPC_UNSTOPPABLE_ABOMINATION = 16428 ,
NPC_SOUL_WEAVER = 16429 , NPC_GUARDIAN_OF_ICECROWN = 16441 , ACTION_CALL_HELP_ON = 1 , ACTION_CALL_HELP_OFF = 2 ,
ACTION_SECOND_PHASE = 3 , ACTION_GUARDIANS_OFF = 4 , NPC_WEB_WRAP = 16486 , NPC_MAEXXNA_SPIDERLING = 17055 ,
NPC_PLAGUED_WARRIOR = 16984 , NPC_PLAGUED_CHAMPION = 16983 , NPC_PLAGUED_GUARDIAN = 16981 , ACHIEV_TIMED_START_EVENT = 10286 ,
NPC_DEATH_KNIGHT_UNDERSTUDY = 16803 , NPC_RAZUVIOUS = 16061 , GO_ICE_BLOCK = 181247 , NPC_BLIZZARD = 16474 ,
POINT_CENTER = 1 , ACTION_MAGNETIC_PULL = 1 , ACTION_SUMMON_DIED = 2 , ACTION_RESTORE = 3 ,
GO_TESLA_COIL_LEFT = 181478 , GO_TESLA_COIL_RIGHT = 181477 , NPC_TESLA_COIL = 16218 , NPC_FIRE_MAGUS = 26928 ,
NPC_FROST_MAGUS = 26930 , NPC_ARCANE_MAGUS = 26929 , ACHIEVEMENT_SPLIT_PERSONALITY = 2150 , GAME_EVENT_WINTER_VEIL = 2 ,
NPC_CRYSTAL_SPIKE = 27099 , GO_CRYSTAL_SPIKE = 188537 , POS_GEN_RIGHT = 0 , POS_GEN_LEFT = 1 ,
POS_ROOM_CENTER = 2 , ACTION_SLUG_KILLED = 1 , SPELL_GLARE_OF_THE_TRIBUNAL = 50988 , SPELL_GLARE_OF_THE_TRIBUNAL_H = 59870 ,
SPELL_DARK_MATTER_VISUAL = 51001 , SPELL_DARK_MATTER = 51012 , SPELL_DARK_MATTER_H = 59868 , SPELL_SEARING_GAZE = 51136 ,
SPELL_SEARING_GAZE_H = 59867 , SPELL_DRP_CHARGE = 22120 , SPELL_DRP_CLEAVE = 42724 , SPELL_DRS_LIGHTING_BOLT = 12167 ,
SPELL_DRS_LIGHTING_BOLT_H = 59863 , SPELL_DRS_SHADOW_WORD_PAIN = 15654 , SPELL_DRS_SHADOW_WORD_PAIN_H = 59864 , SPELL_IGC_CRUSH_ARMOR = 33661 ,
SPELL_IGC_GROUND_SMASH = 12734 , SPELL_IGC_GROUND_SMASH_H = 59865 , ACTION_START_EVENT = 0 , ACTION_START_TRIBUNAL = 1 ,
ACTION_GO_TO_SJONNIR = 2 , ACTION_START_SJONNIR_FIGHT = 3 , ACTION_SJONNIR_DEAD = 4 , ACTION_ENTEREVADEMODE = 5 ,
ACTION_WIPE_START = 6 , ACTION_OPEN_DOOR = 7 , QUEST_HALLS_OF_STONE = 13207 , POINT_BRANN_INTRO = 0 ,
MAX_BRANN_WAYPOINTS_INTRO = 11 , POINT_BRANN_OUTRO = 11 , POINT_BRANN_OUTRO_END = 12 , POINT_ALGALON_LAND = 1 ,
POINT_ALGALON_OUTRO = 2 , EVENT_ID_SUPERMASSIVE_START = 21697 , DATA_HAS_FED_ON_TEARS = 1 , DATA_HERALD_OF_THE_TITANS = 2 ,
ACTION_ADD_CHARGE = 1 , POINT_CHANNEL_STEELBREAKER = 1 , ACTION_FERAL_RESPAWN = 1 , ACTION_FERAL_DEATH = 2 ,
ACTION_DESPAWN_ADDS = 3 , ACTION_FERAL_DEATH_WITH_STACK = 4 , DATA_CRAZY_CAT = 10 , DATA_NINE_LIVES = 11 ,
DATA_EVENT_STARTED = 1 , DATA_GET_TOWER_COUNT = 2 , DATA_GET_SHUTDOWN = 3 , TOWER_OF_STORMS = 2 ,
TOWER_OF_FLAMES = 1 , TOWER_OF_FROST = 3 , TOWER_OF_LIFE = 0 , ACTION_START_NORGANNON_EVENT = 1 ,
ACTION_START_NORGANNON_BRANN = 2 , ACTION_START_BRANN_EVENT = 3 , ACTION_DESPAWN_ADDS = 4 , ACTION_DELAY_CANNON = 5 ,
ACTION_DESTROYED_TURRET = 6 , ACTION_REMOVE_10_STACK = 10 , ACTION_REMOVE_25_STACK = 25 , ACTION_REMOVE_2_STACK = 2 ,
ACTION_RESPAWN_TRIO = 1 , ACTION_LUMBERJACKED = -1 , EVENT_PHASE_ADDS = 1 , EVENT_PHASE_FINAL = 2 ,
DATA_GET_ELDER_COUNT = 1 , DATA_BACK_TO_NATURE = 2 , CRITERIA_LUMBERJACKED = 21686 , ACHIEVEMENT_DISARMED_CRITERIA = 21687 ,
DATA_KOLOGARN_LOOKS_ACHIEV = 55 , DATA_KOLOGARN_RUBBLE_ACHIEV = 56 , DATA_KOLOGARN_ARMS_ACHIEV = 57 , ACTION_START_TRASH_DIED = 1 ,
ACTION_ALLOW_HIT = 2 , ACTION_SIF_JOIN_FIGHT = 3 , ACTION_SIF_START_TALK = 4 , ACTION_SIF_START_DOMINION = 5 ,
ACTION_SIF_TRANSFORM = 6 , ACTION_IRON_HONOR_DIED = 7 , EVENT_PHASE_START = 1 , EVENT_PHASE_RING = 2 ,
EVENT_PHASE_OUTRO = 3 , DATA_HIT_BY_LIGHTNING = 1 , DATA_LOSE_YOUR_ILLUSION = 2 , HEART_VEHICLE_SEAT = 0 ,
ACTION_AWAKEN_HEART = -5 , ACTION_HIDE_HEART = -4 , ACTION_HEART_BROKEN = -3 , ACHIEVEMENT_MUST_DECONSTRUCT_FASTER = 21027 ,
DATA_XT002_NERF_ENGINEERING = 50 , DATA_XT002_GRAVITY_ACHIEV = 51 , ACTION_UNSUMMON_CLOUDS = -16 , ACTION_DESPAWN_ADDS = -15 ,
ACTION_START_SUMMONING = -14 , ACTION_YOGG_SARON_APPEAR = -13 , ACTION_YOGG_SARON_DEATH = -12 , ACTION_YOGG_SARON_START_YELL = -11 ,
ACTION_YOGG_SARON_OPEN_PORTAL_YELL = -10 , ACTION_INFLUENCE_TENTACLE_DIED = -9 , ACTION_BRAIN_DAMAGED = -8 , ACTION_REMOVE_STUN = -7 ,
ACTION_YOGG_SARON_START_P3 = -6 , ACTION_YOGG_SARON_HARD_MODE = -5 , ACTION_YOGG_SARON_SHADOW_BEACON = -4 , ACTION_THORIM_START_STORM = -3 ,
ACTION_FAILED_DRIVE_ME_CRAZY = -2 , ACTION_ILLUSION_DRAGONS = 1 , ACTION_ILLUSION_ICECROWN = 2 , ACTION_ILLUSION_STORMWIND = 3 ,
EVENT_PHASE_ONE = 1 , EVENT_PHASE_TWO = 2 , EVENT_PHASE_THREE = 3 , CRITERIA_NOT_GETTING_OLDER = 21001 ,
DATA_GET_KEEPERS_COUNT = 1 , DATA_GET_CURRENT_ILLUSION = 2 , DATA_GET_SARA_PHASE = 3 , DATA_GET_DRIVE_ME_CRAZY = 4 ,
SAY_AGGRO = 0 , SAY_SLAY = 1 , SOUND_DEATH = 13467 , SPELL_ORB_VISUAL = 48044 ,
SPELL_ORB_CHANNEL = 48048 , NPC_ORB_TRIGGER = 22515 , SPELL_AWAKEN_SUBBOSS = 47669 , SPELL_ARCING_SMASH = 48260 ,
SPELL_IMPALE_N = 48261 , SPELL_IMPALE_H = 59268 , SPELL_WITHERING_ROAR_N = 48256 , SPELL_WITHERING_ROAR_H = 59267 ,
SPELL_FREEZE = 16245 , SPELL_ACID_SPIT = 48132 , SPELL_ACID_SPLATTER_N = 48136 , SPELL_ACID_SPLATTER_H = 59272 ,
SPELL_POISON_BREATH_N = 48133 , SPELL_POISON_BREATH_H = 59271 , NPC_JORMUNGAR_WORM = 27228 , SPELL_GORE_N = 48130 ,
SPELL_GORE_H = 59264 , SPELL_GRIEVOUS_WOUND_N = 48105 , SPELL_GRIEVOUS_WOUND_H = 59263 , SPELL_STOMP = 48131 ,
SPELL_CHAIN_LIGHTING_N = 48140 , SPELL_CHAIN_LIGHTING_H = 59273 , SPELL_CRAZED = 48139 , SPELL_TERRIFYING_ROAR = 48144 ,
SPELL_MORTAL_WOUND_N = 48137 , SPELL_MORTAL_WOUND_H = 59265 , SPELL_ENRAGE_1 = 48138 , SPELL_ENRAGE_2 = 48142 ,
ACTION_START_EVENT = 1 , ACTION_UNFREEZE = 2 , ACTION_DESPAWN_ADDS = 3 , ACTION_MINIBOSS_DIED = 4 ,
ACTION_UNFREEZE2 = 5 , SAY_AGGRO = 0 , SAY_KILL = 1 , EMOTE_RANGE = 2 ,
SAY_DEATH = 3 , SAY_DRAKE_DEATH = 5 , SAY_DRAKE_BREATH = 6 , SPELL_CRUSH_N = 50234 ,
SPELL_CRUSH_H = 59330 , SPELL_POISONED_SPEAR_N = 50255 , SPELL_POISONED_SPEAR_H = 59331 , SPELL_WHIRLWIND_N = 50228 ,
SPELL_WHIRLWIND_H = 50228 , SPELL_FLAME_VISUAL = 47592 , SPELL_FLAME_BREATH_N = 47579 , SPELL_FLAME_BREATH_H = 60020 ,
SPELL_LAUNCH_HARPOON = 48642 , NPC_YMIRJAR_WARRIOR = 26690 , NPC_YMIRJAR_WITCH_DOCTOR = 26691 , NPC_YMIRJAR_HARPOONER = 26692 ,
NPC_GRAUF = 26893 , NPC_BREATH_TRIGGER = 28351 , EQUIP_MACE = 17193 , ACTION_START_EVENT = 1 ,
ACTION_REMOVE_SKADI = 2 , ACTION_PHASE2 = 3 , ACTION_MYGIRL_ACHIEVEMENT = 4 , ACHIEV_TIMED_LODI_DODI = 17726 ,
TALK_INTRO_A1 = 0 , TALK_INTRO_A2 = 1 , TALK_INTRO_S1 = 0 , TALK_INTRO_S2 = 0 ,
TALK_INTRO_S3 = 1 , SAY_AGGRO = 2 , SAY_SLAY = 3 , SAY_DEATH = 4 ,
SAY_SACRIFICE_PLAYER = 5 , SPELL_ARTHAS_TRANSFORMING_SVALA = 54142 , SPELL_SVALA_TRANSFORMING1 = 54205 , SPELL_SVALA_TRANSFORMING2 = 54140 ,
SPELL_CALL_FLAMES = 48258 , SPELL_BALL_OF_FLAME = 48246 , SPELL_RITUAL_OF_THE_SWORD = 48276 , SPELL_RITUAL_STRIKE = 48331 ,
SPELL_SINSTER_STRIKE_N = 15667 , SPELL_SINSTER_STRIKE_H = 59409 , EQUIP_SWORD = 40343 , SPELL_PARALYZE = 48278 ,
SPELL_SHADOWS_IN_THE_DARK = 59407 , SPELL_TELEPORT_VISUAL = 64446 , NPC_RITUAL_CHANNELER = 27281 , NPC_ARTHAS = 29280 ,
NPC_FLAME_BRAZIER = 27273 , SAY_AGGRO = 0 , SAY_SLAY = 1 , SAY_DEATH = 2 ,
SAY_SUMMON_BJORN = 3 , SAY_SUMMON_HALDOR = 4 , SAY_SUMMON_RANULF = 5 , SAY_SUMMON_TORGYN = 6 ,
SPELL_BANE_N = 48294 , SPELL_BANE_H = 59301 , SPELL_DARK_SLASH = 48292 , SPELL_FETID_ROT_N = 48291 ,
SPELL_FETID_ROT_H = 59300 , SPELL_SCREAMS_OF_THE_DEAD = 51750 , SPELL_SPIRIT_BURST_N = 48529 , SPELL_SPIRIT_BURST_H = 59305 ,
SPELL_SPIRIT_STRIKE_N = 48423 , SPELL_SPIRIT_STRIKE_H = 59304 , SPELL_SUMMON_AVENGING_SPIRIT = 48592 , SPELL_SUMMON_SPIRIT_FOUNT = 48386 ,
SPELL_CHANNEL_SPIRIT_TO_YMIRON = 48316 , SPELL_CHANNEL_YMIRON_TO_SPIRIT = 48307 , SPELL_SPIRIT_FOUNT_N = 48380 , SPELL_SPIRIT_FOUNT_H = 59320 ,
SPELL_FLAMES = 39199 , NPC_BJORN = 27303 , NPC_BJORN_VISUAL = 27304 , NPC_HALDOR = 27307 ,
NPC_HALDOR_VISUAL = 27310 , NPC_RANULF = 27308 , NPC_RANULF_VISUAL = 27311 , NPC_TORGYN = 27309 ,
NPC_TORGYN_VISUAL = 27312 , NPC_SPIRIT_FOUNT = 27339 , NPC_AVENGING_SPIRIT = 27386 , EMOTE_OVERCHARGE = 0 ,
EMOTE_MINION_RESPAWN = 1 , EMOTE_BERSERK = 2 , NPC_TEMPEST_MINION = 33998 , MAX_TEMPEST_MINIONS = 4 ,
EVENT_SPELL_BLOOD_BOIL = 1 , EVENT_SPELL_BEWILDERING_STRIKE = 2 , EVENT_SPELL_FEL_ACID_BREATH = 3 , EVENT_SPELL_EJECT = 4 ,
EVENT_SPELL_ARCING_SMASH = 5 , EVENT_SPELL_CHARGE = 6 , EVENT_SPELL_BERSERK = 7 , EVENT_SPELL_FEL_GEYSER = 8 ,
EVENT_KILL_TALK = 9 , GROUP_DELAY = 1 , ACTION_FIGHT_MINIONS = 1 , ACTION_RETURN_BLADE = 2 ,
ACTION_ILLIDAN_CAGED = 3 , ACTION_ILLIDAN_DEAD = 4 , ACTION_MAIEV_SET_DIST30 = 5 , ACTION_MAIEV_SET_DIST0 = 6 ,
ACTION_MAIEV_OUTRO = 7 , MAX_EYE_BEAM_POS = 4 , POINT_ILLIDAN_HOVER = 10 , POINT_ILLIDAN_MIDDLE = 11 ,
NPC_ILLIDAN_DB_TARGET = 23070 , NPC_MAIEV_SHADOWSONG = 23197 , GO_CAGE_TRAP = 185916 , EVENT_KILL_TALK = 1 ,
EVENT_CHECK_HEALTH = 2 , EVENT_RANDOM_TALK = 3 , EVENT_SPELL_ENRAGE = 4 , EVENT_SPELL_PRISMATIC_AURA = 5 ,
EVENT_SPELL_SILENCING_SHRIEK = 6 , EVENT_SPELL_FATAL_ATTRACTION = 7 , EVENT_SPELL_SABER_LASH = 8 , ACTION_ESSENCE_OF_SUFFERING = 1 ,
ACTION_ESSENCE_OF_DESIRE = 2 , ACTION_ESSENCE_OF_ANGER = 3 , ACTION_ENGAGE_ESSENCE = 4 , EVENT_ESSENCE_OF_SUFFERING = 1 ,
EVENT_ESSENCE_OF_DESIRE = 2 , EVENT_ESSENCE_OF_ANGER = 3 , EVENT_ENGAGE_ESSENCE = 4 , EVENT_SPAWN_ENSLAVED_SOULS = 5 ,
EVENT_SPAWN_SOUL = 6 , EVENT_SUCK_ESSENCE = 7 , EVENT_SUFF_FRENZY = 10 , EVENT_SUFF_FRENZY_EMOTE = 11 ,
EVENT_SUFF_SOUL_DRAIN = 12 , EVENT_DESI_DEADEN = 20 , EVENT_DESI_SPIRIT_SHOCK = 21 , EVENT_DESI_RUNE_SHIELD = 22 ,
EVENT_ANGER_SPITE = 30 , EVENT_ANGER_SOUL_SCREAM = 31 , EVENT_ANGER_SEETHE = 32 , EVENT_KILL_TALK = 100 ,
POINT_GO_BACK = 1 , SUMMON_GROUP_BROKENS = 1 , POINT_START = 0 , POINT_CHANNEL_SOUL = 1 ,
ACTION_AKAMA_DIED = 1 , ACTION_START_ENCOUNTER = 2 , ACTION_STOP_SPAWNING = 3 , ACTION_DESPAWN_ALL = 4 ,
ACTION_CHANNELERS_START_CHANNEL = 5 , ACTION_KILL_CHANNELERS = 6 , ACTION_NO_SORCERERS = 7 , ACTION_SHADE_DIED = 8 ,
EVENT_AKAMA_START_ENCOUNTER = 1 , EVENT_AKAMA_START_CHANNEL = 2 , EVENT_SPELL_CHAIN_LIGHTNING = 4 , EVENT_SPELL_DESTRUCTIVE_POISON = 5 ,
EVENT_SHADE_CHECK_DISTANCE = 10 , EVENT_SHADE_RESET_ENCOUNTER = 11 , EVENT_SHADE_GATHER_NPCS = 12 , EVENT_SUMMON_WAVE_B = 20 ,
EVENT_SUMMON_ASHTONGUE_SORCERER = 21 , EVENT_SUMMON_ASHTONGUE_DEFENDER = 22 , EVENT_AKAMA_SCENE0 = 29 , EVENT_AKAMA_SCENE1 = 30 ,
EVENT_AKAMA_SCENE2 = 31 , EVENT_AKAMA_SCENE3 = 32 , EVENT_AKAMA_SCENE4 = 33 , EVENT_AKAMA_SCENE5 = 34 ,
EVENT_AKAMA_SCENE6 = 35 , EVENT_AKAMA_SCENE7 = 36 , SET_DATA_INTRO = 1 , EVENT_SPELL_INCINERATE = 1 ,
EVENT_SPELL_DOOM_BLOSSOM = 2 , EVENT_SPELL_CRUSHING_SHADOWS = 3 , EVENT_SPELL_SHADOW_OF_DEATH = 4 , EVENT_TALK_KILL = 10 ,
ACTION_START_ENCOUNTER = 1 , ACTION_END_ENCOUNTER = 2 , ACTION_ENRAGE = 3 , EVENT_SPELL_BLESSING = 1 ,
EVENT_SPELL_AURA = 2 , EVENT_SPELL_SEAL = 3 , EVENT_SPELL_HAMMER_OF_JUSTICE = 4 , EVENT_SPELL_JUDGEMENT = 5 ,
EVENT_SPELL_CONSECRATION = 6 , EVENT_SPELL_FLAMESTRIKE = 10 , EVENT_SPELL_BLIZZARD = 11 , EVENT_SPELL_ARCANE_BOLT = 12 ,
EVENT_SPELL_DAMPEN_MAGIC = 13 , EVENT_SPELL_ARCANE_EXPLOSION = 14 , EVENT_SPELL_REFLECTIVE_SHIELD = 20 , EVENT_SPELL_CIRCLE_OF_HEALING = 21 ,
EVENT_SPELL_DIVINE_WRATH = 22 , EVENT_SPELL_EMPOWERED_SMITE = 23 , EVENT_SPELL_VANISH = 30 , EVENT_SPELL_VANISH_OUT = 31 ,
EVENT_SPELL_ENRAGE = 32 , EVENT_KILL_TALK = 100 , MAX_ADVISORS = 3 , NPC_FATHOM_GUARD_CARIBDIS = 21964 ,
NPC_FATHOM_GUARD_TIDALVESS = 21965 , NPC_FATHOM_GUARD_SHARKKIS = 21966 , NPC_SEER_OLUM = 22820 , GO_CAGE = 185952 ,
EVENT_SPELL_CATACLYSMIC_BOLT = 1 , EVENT_SPELL_ENRAGE = 2 , EVENT_SPELL_SEAR_NOVA = 3 , EVENT_HEALTH_CHECK = 4 ,
EVENT_KILL_TALK = 5 , GROUP_ABILITIES = 1 , NPC_PURE_SPAWN_OF_HYDROSS = 22035 , EVENT_SPELL_MARK_OF_CORRUPTION1 = 1 ,
EVENT_SPELL_MARK_OF_CORRUPTION2 = 2 , EVENT_SPELL_MARK_OF_CORRUPTION3 = 3 , EVENT_SPELL_MARK_OF_CORRUPTION4 = 4 , EVENT_SPELL_MARK_OF_CORRUPTION5 = 5 ,
EVENT_SPELL_MARK_OF_CORRUPTION6 = 6 , EVENT_SPELL_MARK_OF_HYDROSS1 = 7 , EVENT_SPELL_MARK_OF_HYDROSS2 = 8 , EVENT_SPELL_MARK_OF_HYDROSS3 = 9 ,
EVENT_SPELL_MARK_OF_HYDROSS4 = 10 , EVENT_SPELL_MARK_OF_HYDROSS5 = 11 , EVENT_SPELL_MARK_OF_HYDROSS6 = 12 , EVENT_SPELL_WATER_TOMB = 13 ,
EVENT_SPELL_VILE_SLUDGE = 14 , EVENT_SPELL_ENRAGE = 15 , EVENT_CHECK_AURA = 16 , EVENT_KILL_TALK = 17 ,
ITEM_TAINTED_CORE = 31088 , POINT_HOME = 1 , EVENT_SPELL_SHOCK_BLAST = 1 , EVENT_SPELL_STATIC_CHARGE = 2 ,
EVENT_SPELL_ENTANGLE = 3 , EVENT_CHECK_HEALTH = 4 , EVENT_SPELL_FORKED_LIGHTNING = 5 , EVENT_SUMMON_A = 6 ,
EVENT_SUMMON_B = 7 , EVENT_SUMMON_C = 8 , EVENT_SUMMON_D = 9 , EVENT_CHECK_HEALTH2 = 10 ,
EVENT_SUMMON_SPOREBAT = 11 , EVENT_KILL_TALK = 20 , MAX_CHANNELERS = 3 , NPC_GREYHEART_SPELLBINDER = 21806 ,
NPC_SHADOW_OF_LEOTHERAS = 21875 , EVENT_SPELL_BERSERK = 1 , EVENT_HEALTH_CHECK = 2 , EVENT_SWITCH_TO_DEMON = 3 ,
EVENT_SPELL_WHIRLWIND = 4 , EVENT_KILL_TALK = 5 , EVENT_SWITCH_TO_ELF = 6 , EVENT_SPELL_INSIDIOUS_WHISPER = 7 ,
EVENT_SUMMON_DEMON = 8 , EVENT_RESTORE_FIGHT = 9 , EVENT_SPELL_SHADOW_BOLT = 20 , EMOTE_TAKE_BREATH = 0 ,
ACTION_START_EVENT = 1 , MAX_SUMMONS = 9 , NPC_COILFANG_GUARDIAN = 21873 , NPC_COILFANG_AMBUSHER = 21865 ,
EVENT_PHASE_1 = 1 , EVENT_PHASE_2 = 2 , EVENT_SPELL_WHIRL = 3 , EVENT_SPELL_SPOUT = 4 ,
EVENT_SPELL_GEYSER = 5 , EVENT_SPELL_SPOUT_PERIODIC = 6 , NPC_WATER_GLOBULE = 21913 , NPC_TIDEWALKER_LURKER = 21920 ,
EVENT_SPELL_TIDAL_WAVE = 1 , EVENT_SPELL_WATERY_GRAVE = 2 , EVENT_SPELL_EARTHQUAKE = 3 , EVENT_SUMMON_MURLOCS = 4 ,
EVENT_KILL_TALK = 5 , EVENT_SUMMON1 = 1 , EVENT_SUMMON2 = 2 , EVENT_TREACHEROUS_AURA = 3 ,
EVENT_DEMONIC_SHIELD = 4 , EVENT_KILL_TALK = 5 , EVENT_ORBITAL_STRIKE = 6 , EVENT_SHADOW_WHIP = 7 ,
ACTION_FLY_DOWN = 0 , POINT_MIDDLE = 0 , POINT_FLIGHT = 1 , EVENT_SPELL_REVENGE = 1 ,
EVENT_KILL_TALK = 2 , EVENT_AGGRO_TALK = 3 , EVENT_SPELL_FIREBALL = 4 , EVENT_SPELL_CONE_OF_FIRE = 5 ,
EVENT_SPELL_BELLOWING_ROAR = 6 , EVENT_CHANGE_POS = 7 , EVENT_RESTORE_COMBAT = 8 , NPC_HELLFIRE_WATCHER = 17309 ,
EVENT_MORTAL_WOUND = 1 , EVENT_SURGE = 2 , EVENT_RETALIATION = 3 , EVENT_KILL_TALK = 4 ,
EVENT_CHECK_HEALTH = 5 , EMOTE_ENRAGE = 0 , SETDATA_DATA = 1 , SETDATA_YELL = 1 ,
EVENT_CHECK_ROOM = 1 , EVENT_SUMMON_ADDS = 2 , EVENT_SUMMON_ASSASSINS = 3 , EVENT_SPELL_CHARGE = 4 ,
EVENT_MOVE_TO_NEXT_POINT = 5 , EVENT_BLADE_DANCE = 6 , EVENT_FINISH_BLADE_DANCE = 7 , NPC_HARBINGER_SKYRISS_66 = 21466 ,
EVENT_SUMMON_IMAGE1 = 1 , EVENT_SUMMON_IMAGE2 = 2 , EVENT_SPELL_MIND_REND = 3 , EVENT_SPELL_FEAR = 4 ,
EVENT_SPELL_DOMINATION = 5 , EVENT_SPELL_MANA_BURN = 6 , NPC_FRAYER = 19953 , EVENT_SUMMON_SEEDLING = 1 ,
EVENT_TREE_FORM = 2 , EVENT_CHECK_FRAYERS = 3 , EVENT_RESTORE_COMBAT = 4 , EMOTE_SUMMON = 0 ,
MODEL_DEFAULT = 13109 , MODEL_ARCANE = 14213 , MODEL_FIRE = 13110 , MODEL_FROST = 14112 ,
MODEL_NATURE = 14214 , EVENT_ALERGIC_REACTION = 1 , EVENT_TRANSFORM = 2 , EVENT_TELEPORT = 3 ,
EVENT_SUMMON = 4 , EVENT_ARCANE_VOLLEY = 1 , EVENT_WAR_STOMP = 2 , EVENT_SUMMON_TREANT = 3 ,
DISPLAYID_INVISIBLE = 23377 , NPC_EMBER_OF_ALAR = 19551 , NPC_FLAME_PATCH = 20602 , POINT_PLATFORM = 0 ,
POINT_QUILL = 4 , POINT_MIDDLE = 5 , POINT_DIVE = 6 , EVENT_SWITCH_PLATFORM = 1 ,
EVENT_START_QUILLS = 2 , EVENT_RELOCATE_MIDDLE = 3 , EVENT_REBIRTH = 4 , EVENT_SPELL_MELT_ARMOR = 5 ,
EVENT_SPELL_FLAME_PATCH = 6 , EVENT_SPELL_CHARGE = 7 , EVENT_SPELL_DIVE_BOMB = 8 , EVENT_START_DIVE = 9 ,
EVENT_CAST_DIVE_BOMB = 10 , EVENT_SUMMON_DIVE_PHOENIX = 11 , EVENT_REBIRTH_DIVE = 12 , EVENT_SPELL_BERSERK = 13 ,
EVENT_MOVE_TO_PHASE_2 = 20 , EVENT_FINISH_DIVE = 21 , DISPLAYID_INVISIBLE = 11686 , NPC_ASTROMANCER_SOLARIAN_SPOTLIGHT = 18928 ,
NPC_SOLARIUM_AGENT = 18925 , NPC_SOLARIUM_PRIEST = 18806 , EVENT_CHECK_HEALTH = 1 , EVENT_SPELL_ARCANE_MISSILES = 2 ,
EVENT_SPELL_WRATH_OF_ASTROMANCER = 3 , EVENT_SPELL_BLINDING_LIGHT = 4 , EVENT_SPAWN_PORTALS = 5 , EVENT_SUMMON_ADDS = 6 ,
EVENT_REAPPEAR = 7 , EVENT_SPELL_PSYCHIC_SCREAM = 8 , EVENT_SPELL_VOID_BOLT = 9 , POINT_MIDDLE = 1 ,
POINT_AIR = 2 , POINT_START_LAST_PHASE = 3 , DATA_RESURRECT_CAST = 1 , NPC_WORLD_TRIGGER = 19871 ,
NPC_NETHER_VAPOR = 21002 , PHASE_NONE = 0 , PHASE_SINGLE_ADVISOR = 1 , PHASE_WEAPONS = 2 ,
PHASE_ALL_ADVISORS = 3 , PHASE_FINAL = 4 , EVENT_PREFIGHT_PHASE11 = 1 , EVENT_PREFIGHT_PHASE12 = 2 ,
EVENT_PREFIGHT_PHASE21 = 3 , EVENT_PREFIGHT_PHASE22 = 4 , EVENT_PREFIGHT_PHASE31 = 5 , EVENT_PREFIGHT_PHASE32 = 6 ,
EVENT_PREFIGHT_PHASE41 = 7 , EVENT_PREFIGHT_PHASE42 = 8 , EVENT_PREFIGHT_PHASE51 = 9 , EVENT_PREFIGHT_PHASE52 = 10 ,
EVENT_PREFIGHT_PHASE61 = 11 , EVENT_PREFIGHT_PHASE62 = 12 , EVENT_PREFIGHT_PHASE63 = 13 , EVENT_PREFIGHT_PHASE71 = 14 ,
EVENT_GATHER_ADVISORS = 15 , EVENT_SPELL_SEQ_1 = 30 , EVENT_SPELL_SEQ_2 = 31 , EVENT_SPELL_SEQ_3 = 32 ,
EVENT_SPELL_FIREBALL = 33 , EVENT_SPELL_PYROBLAST = 34 , EVENT_SPELL_FLAMESTRIKE = 35 , EVENT_SPELL_ARCANE_DISRUPTION = 36 ,
EVENT_SPELL_MIND_CONTROL = 37 , EVENT_SPELL_SUMMON_PHOENIX = 38 , EVENT_CHECK_HEALTH = 39 , EVENT_SPELL_GRAVITY_LAPSE = 40 ,
EVENT_GRAVITY_LAPSE_END = 41 , EVENT_SPELL_SHOCK_BARRIER = 42 , EVENT_SPELL_NETHER_BEAM = 43 , EVENT_SPELL_NETHER_VAPOR = 44 ,
EVENT_SCENE_1 = 50 , EVENT_SCENE_2 = 51 , EVENT_SCENE_3 = 52 , EVENT_SCENE_4 = 53 ,
EVENT_SCENE_5 = 54 , EVENT_SCENE_6 = 55 , EVENT_SCENE_7 = 56 , EVENT_SCENE_8 = 57 ,
EVENT_SCENE_9 = 58 , EVENT_SCENE_10 = 59 , EVENT_SCENE_11 = 60 , EVENT_SCENE_12 = 61 ,
EVENT_SCENE_13 = 62 , EVENT_SCENE_14 = 63 , EVENT_SCENE_15 = 64 , EVENT_SCENE_16 = 65 ,
NPC_DK_GHOUL = 26125
}
Functions
ObjectGuid getOrphanGUID (Player *player, uint32 orphan)
void AddSC_event_childrens_week ()
Enumeration Type Documentation
Areatriggers
enum Areatriggers
Enumerator
AT_DOWN_AT_THE_DOCKS
AT_GATEWAY_TO_THE_FRONTIER
AT_LORDAERON_THRONE_ROOM
AT_BOUGHT_OF_ETERNALS
AT_SPOOKY_LIGHTHOUSE
AT_STONEWROUGHT_DAM
AT_DARK_PORTAL
NPC_CAVERNS_OF_TIME_CW_TRIGGER
NPC_EXODAR_01_CW_TRIGGER
NPC_EXODAR_02_CW_TRIGGER
NPC_AERIS_LANDING_CW_TRIGGER
NPC_AUCHINDOUN_CW_TRIGGER
NPC_SPOREGGAR_CW_TRIGGER
NPC_THRONE_OF_ELEMENTS_CW_TRIGGER
NPC_SILVERMOON_01_CW_TRIGGER
NPC_KRASUS
Definition at line 105 of file childrens_week.cpp.
 {
     AT_DOWN_AT_THE_DOCKS                    = 3551,
     AT_GATEWAY_TO_THE_FRONTIER              = 3549,
     AT_LORDAERON_THRONE_ROOM                = 3547,
     AT_BOUGHT_OF_ETERNALS                   = 3546,
     AT_SPOOKY_LIGHTHOUSE                    = 3552,
     AT_STONEWROUGHT_DAM                     = 3548,
     AT_DARK_PORTAL                          = 4356,
     NPC_CAVERNS_OF_TIME_CW_TRIGGER          = 22872,
     NPC_EXODAR_01_CW_TRIGGER                = 22851,
     NPC_EXODAR_02_CW_TRIGGER                = 22905,
     NPC_AERIS_LANDING_CW_TRIGGER            = 22838,
     NPC_AUCHINDOUN_CW_TRIGGER               = 22831,
     NPC_SPOREGGAR_CW_TRIGGER                = 22829,
     NPC_THRONE_OF_ELEMENTS_CW_TRIGGER       = 22839,
     NPC_SILVERMOON_01_CW_TRIGGER            = 22866,
     NPC_KRASUS                              = 27990,
 };
Misc
enum Misc
Enumerator
DATA_SKILLPOINT_MIN
NEFARIUS_PATH_2
NEFARIUS_PATH_3
GYTH_PATH_1
NEFARIUS_PATH_1
NEFARIUS_PATH_2
NEFARIUS_PATH_3
REND_PATH_1
REND_PATH_2
TEXT_ID_SUMMON_1
TEXT_ID_SUMMON_2
TEXT_ID_SUMMON_3
GOSSIP_ITEM_SUMMON_1
GOSSIP_ITEM_SUMMON_2
GOSSIP_ITEM_SUMMON_3
FACTION_MAJORDOMO_FRIENDLY
SUMMON_GROUP_ADDS
POINT_RAGNAROS_SUMMON
PHASE_NONE
PHASE_COMBAT
PHASE_DEFEAT_OUTRO
PHASE_RAGNAROS_SUMMONING
MAX_SON_OF_FLAME_COUNT
EVENT_GUEST_TALK
EVENT_GUEST_TALK2
EVENT_SPELL_VANISH
EVENT_SPELL_GARROTE
EVENT_SPELL_BLIND
EVENT_SPELL_GOUGE
EVENT_CHECK_HEALTH
EVENT_SPELL_ENRAGE
EVENT_KILL_TALK
ACTIVE_GUEST_COUNT
MAX_GUEST_COUNT
EVENT_INIT_COMBAT
EVENT_SPELL_FIREBALL
EVENT_SPELL_PHOENIX
EVENT_SPELL_FLAMESTRIKE
EVENT_SPELL_SHOCK_BARRIER
EVENT_CHECK_HEALTH
EVENT_GRAVITY_LAPSE_1_1
EVENT_GRAVITY_LAPSE_1_2
EVENT_GRAVITY_LAPSE_2
EVENT_GRAVITY_LAPSE_3
EVENT_GRAVITY_LAPSE_4
EVENT_GRAVITY_LAPSE_5
EVENT_FINISH_TALK
ACTION_TELEPORT_PLAYERS
ACTION_KNOCKUP
ACTION_ALLOW_FLY
ACTION_REMOVE_FLY
CREATURE_ARCANE_SPHERE
MAX_ACTIVE_HELPERS
MAX_HELPERS_COUNT
NPC_PURE_ENERGY
INTERVAL_MODIFIER
INTERVAL_SWITCH
EVENT_SPELL_CHAIN_LIGHTNING
EVENT_SPELL_ARCANE_SHOCK
EVENT_HEALTH_CHECK
WEAPON_KIRTONOS_STAFF
POINT_KIRTONOS_LAND
KIRTONOS_PATH
EMOTE_SUMMONED
EVENT_SPELL_SLASH
EVENT_SPELL_STOMP
EVENT_SPELL_BURN
EVENT_SPELL_BERSERK
ACTION_START_EVENT
ACTION_SPAWN_FELMYST
ACTION_SISTER_DIED
EVENT_SPELL_SHADOW_BLADES
EVENT_SPELL_SHADOW_NOVA
EVENT_SPELL_CONFOUNDING_BLOW
EVENT_SHADOW_IMAGE
EVENT_SPELL_ENRAGE
EVENT_SPELL_CONFLAGRATION
EVENT_SPELL_BLAZE
EVENT_SPELL_PYROGENICS
EVENT_SPELL_FLAME_SEAR
EVENT_SPELL_BERSERK
EVENT_SPELL_CLEAVE
EVENT_SPELL_CORROSION
EVENT_SPELL_GAS_NOVA
EVENT_SPELL_ENCAPSULATE
EVENT_FLIGHT
EVENT_LAND
EVENT_RESTORE_COMBAT
EVENT_RESTORE_COMBAT2
EVENT_FLIGHT_SEQ
EVENT_FLIGHT_VAPOR
EVENT_FLIGHT_MOVE_UP
EVENT_LAND_FIGHT
EVENT_FLIGHT_EMOTE
EVENT_FLIGHT_BREATH1
EVENT_FLIGHT_BREATH2
EVENT_FLIGHT_FLYOVER1
EVENT_FLIGHT_FLYOVER2
EVENT_CORRUPT_TRIGGERS
EVENT_INTRO_1
EVENT_INTRO_2
EVENT_INTRO_3
EVENT_INTRO_4
ACTION_START_EVENT
POINT_GROUND
POINT_AIR
POINT_AIR_BREATH_START1
POINT_AIR_BREATH_END1
POINT_AIR_BREATH_START2
POINT_AIR_BREATH_END2
POINT_MISC
NPC_FOG_TRIGGER
PHASE_DECEIVERS
PHASE_NORMAL
PHASE_DARKNESS
PHASE_ARMAGEDDON
PHASE_SACRIFICE
EVENT_GROUP_SPEACH
ACTION_START_POST_EVENT
ACTION_NO_KILL_TALK
EVENT_TEXT_SPEACH11
EVENT_TEXT_SPEACH21
EVENT_TEXT_SPEACH22
EVENT_TEXT_SPEACH23
EVENT_TEXT_SPEACH31
EVENT_TEXT_SPEACH32
EVENT_TEXT_SPEACH33
EVENT_TEXT_SPEACH41
EVENT_TEXT_SPEACH42
EVENT_TEXT_SPEACH43
EVENT_TEXT_SPEACH44
EVENT_TEXT_SPEACH45
EVENT_TEXT_SPEACH46
EVENT_RANDOM_TALK
EVENT_CHECK_PLAYERS
EVENT_REBIRTH
EVENT_INIT_FIGHT
EVENT_CHECK_HEALTH85
EVENT_CHECK_HEALTH55
EVENT_CHECK_HEALTH25
EVENT_EMPOWER_ORBS1
EVENT_EMPOWER_ORBS2
EVENT_EMPOWER_ORBS3
EVENT_RESTORE_MELEE
EVENT_KILL_SELF
EVENT_NO_KILL_TALK
EVENT_SPELL_SOUL_FLAY
EVENT_SPELL_LEGION_LIGHTNING
EVENT_SPELL_FIRE_BLOOM
EVENT_SUMMON_ORBS
EVENT_SPELL_SHADOW_SPIKE
EVENT_SPELL_SINISTER_REFLECTION
EVENT_SPELL_FLAME_DART
EVENT_SPELL_DARKNESS
EVENT_SPELL_ARMAGEDDON
EVENT_SPELL_ENRAGE
EVENT_SUMMON_ENTROPIUS
EVENT_SET_INVISIBLE
EVENT_SPAWN_BLACK_HOLE
EVENT_SPAWN_DARKNESS
EVENT_START_BLACK_HOLE
EVENT_SWITCH_BLACK_HOLE_TARGET
EVENT_ENTROPIUS_AURAS
EVENT_ENTROPIUS_COMBAT
EVENT_SINGULARITY_DEATH
DATA_ENRAGE_TIMER
DATA_NEGATIVE_ENERGY_TARGETS
MAX_ENCOUNTER
RAND_VENDOR
WORLDSTATE_SHOW_TIMER
WORLDSTATE_TIME_TO_SACRIFICE
MAX_PROWLERS_PER_SIDE
MODEL_OHGAN_MOUNT
PATH_MANDOKIR
POINT_MANDOKIR_END
CHAINED_SPIRT_COUNT
EQUIP_ID_MAIN_HAND
SPELL_SNOWBALL
SPELL_ORPHAN_OUT
DISPLAY_INVISIBLE
ENCOUNTER_WAVES_NUMBER
ENCOUNTER_WAVES_MAX_SPAWNS
ENCOUNTER_CHRONO_NUMBER
ENCOUNTER_CHRONO_MAX_SPAWNS_FIRST
ENCOUNTER_CHRONO_MAX_SPAWNS_SECOND
ACTION_INFECT_CITIZIEN
ACTION_FORCE_CHANGE_LOCK
POINT_CHRONOS
THRALL_WEAPON_ITEM
THRALL_SHIELD_ITEM
THRALL_MODEL_UNEQUIPPED
THRALL_MODEL_EQUIPPED
ACTION_SET_IMMUNE_FLAG
ACTION_REMOVE_IMMUNE_FLAG
ACTION_TRANSFORM
ACTION_MOVE
ACTION_START_COMBAT
SPELL_RIFT_CHANNEL
EVENT_NEXT_PORTAL
EVENT_SUMMON_KEEPER
ACTION_OUTRO
PULL_RANGE
ABUSE_BUG_RANGE
VEKLOR_DIST
TELEPORTTIME
PATH_ADDS
SAY_BLY_FORWARD
DATA_RESPECT_YOUR_ELDERS
NPC_TWISTED_VISAGE
ACHIEV_QUICK_DEMISE_START_EVENT
MAX_INSANITY_TARGETS
DATA_SET_INSANITY_PHASE
MAX_COMBAT_INITIATES
DATA_VOLUNTEER_WORK
MAX_EMBRACE_DMG
MAX_EMBRACE_DMG_H
SUMMON_GROUP_TRIGGERS
ACHIEV_TIMED_START_EVENT
EVENT_CHECK_HEALTH_25
EVENT_CHECK_HEALTH_50
EVENT_CHECK_HEALTH_75
EVENT_CARRION_BEETELS
EVENT_LEECHING_SWARM
EVENT_IMPALE
EVENT_POUND
EVENT_CLOSE_DOORS
EVENT_EMERGE
EVENT_SUMMON_VENOMANCER
EVENT_SUMMON_DARTER
EVENT_SUMMON_GUARDIAN
EVENT_SUMMON_ASSASSINS
EVENT_ENABLE_ROTATE
EVENT_KILL_TALK
NPC_ANUB_AR_CRUSHER
SAY_CRUSHER_AGGRO
SAY_CRUSHER_EMOTE
SAY_HADRONOX_EMOTE
ACTION_DESPAWN_ADDS
ACTION_START_EVENT
ACTION_SWITCH_PHASE
ACTION_CALL_DRAGON
ACTION_DRAKE_DIED
POINT_FINAL_TENEBRON
POINT_FINAL_SHADRON
POINT_FINAL_VESPERON
LAVA_LEFT_SIDE
LAVA_RIGHT_SIDE
MAX_LEFT_LAVA_TSUNAMIS
MAX_RIGHT_LAVA_TSUNAMIS
MAX_DRAGONS
MAX_AREA_TRIGGER_COUNT
MAX_CYCLONE_COUNT
MAX_TENEBORN_EGGS_SUMMONS
MAX_BOUNDARY_POSITIONS
EVENT_CLEAVE
EVENT_INTIDMDATING_ROAR
EVENT_SUMMON_ADDS1
EVENT_SUMMON_ADDS2
EVENT_KILL_TALK
EVENT_BLAST_NOVA
EVENT_LAVA_GOUT
MAX_PATH_FLAMECALLER_WAYPOINTS
ACTION_SHOOT
ACTION_CHECK_CORPOREALITY
ACTION_RESET_ENCOUNTER
DATA_TWILIGHT_DAMAGE_TAKEN
DATA_MATERIAL_DAMAGE_TAKEN
SEAT_NORTH
SEAT_SOUTH
SEAT_EAST
SEAT_WEST
POINT_FLIGHT
POINT_LAND
POINT_TAKEOFF
SOUND_ID_DEATH
NPC_DRAKKARI_SCYTHECLAW
NPC_DRAKKARI_GUTRIPPER
SAY_CLAW_EMOTE
EVENT_SPELL_BELLOWING_ROAR
EVENT_SPELL_GRIEVOUS_BITE
EVENT_SPELL_MANGLING_SLASH
EVENT_SPELL_FEARSOME_ROAR
EVENT_SPELL_PIERCING_SLASH
EVENT_SPELL_RAPTOR_CALL
EVENT_MENACING_CLAW
NPC_CRYSTAL_CHANNEL_TARGET
NPC_CRYSTAL_HANDLER
NPC_SUMMON_CRYSTAL_HANDLER_TARGET
EVENT_SUMMON_FETID_TROLL
EVENT_SUMMON_SHADOWCASTER
EVENT_SUMMON_HULKING_CORPSE
EVENT_SUMMON_CRYSTAL_HANDLER
EVENT_CAST_OFFENSIVE_SPELL
EVENT_KILL_TALK
EVENT_CHECK_PHASE
EVENT_SPELL_SUMMON_MINIONS
ROOM_RIGHT
ROOM_LEFT
ROOM_STAIRS
ACTION_TURN_BONES
EVENT_SPELL_CURSE_OF_LIFE
EVENT_SPELL_RAIN_OF_FIRE
EVENT_SPELL_SHADOW_VOLLEY
EVENT_SPELL_EYE_BEAM
EVENT_SPELL_LIGHTNING_BREATH
EVENT_SPELL_POISON_CLOUD
EVENT_SPELL_TURN_FLESH
EVENT_TURN_FLESH_REAL
EVENT_TURN_BONES_REAL
EVENT_KILL_TALK
NPC_LIVING_MOJO
NPC_DRAKKARI_ELEMENTAL
ACTION_MERGE
ACTION_INFORM
POINT_MERGE
SAY_SURGE
EMOTE_ALTAR
EVENT_COLOSSUS_MIGHTY_BLOW
EVENT_COLOSSUS_HEALTH_1
EVENT_COLOSSUS_HEALTH_2
EVENT_COLOSSUS_START_FIGHT
EVENT_ELEMENTAL_HEALTH
EVENT_ELEMENTAL_SURGE
EVENT_ELEMENTAL_VOLLEY
EVENT_MOJO_MOJO_WAVE
EVENT_MOJO_MOJO_PUDDLE
POINT_START
EVENT_ECK_BERSERK
EVENT_ECK_BITE
EVENT_ECK_SPIT
EVENT_ECK_SPRING
EVENT_ECK_HEALTH
NPC_SLADRAN_VIPER
NPC_SLADRAN_CONSTRICTORS
MAX_VIPER
MAX_CONSTRICTOR
MAX_SUMMONS
EVENT_POISON_NOVA
EVENT_POWERFULL_BITE
EVENT_VENOM_BOLT
EVENT_CHECK_HEALTH1
EVENT_CHECK_HEALTH2
EVENT_SUMMON1
EVENT_SUMMON2
EVENT_KILL_TALK
NPC_CORPSE_SCARAB
NPC_CRYPT_GUARD
ACHIEV_TIMED_START_EVENT
NPC_NAXXRAMAS_WORSHIPPER
NPC_NAXXRAMAS_FOLLOWER
MOVE_PHASE_NONE
MOVE_PHASE_STARTED
MOVE_PHASE_FINISHED
HORSEMAN_ZELIEK
HORSEMAN_BLAUMEUX
HORSEMAN_RIVENDARE
HORSEMAN_KORTHAZZ
NPC_ZOMBIE_CHOW
NPC_LIVING_TRAINEE
NPC_LIVING_KNIGHT
NPC_LIVING_RIDER
NPC_DEAD_TRAINEE
NPC_DEAD_KNIGHT
NPC_DEAD_HORSE
NPC_DEAD_RIDER
NPC_FALLOUT_SLIME
NPC_SEWAGE_SLIME
NPC_STICHED_GIANT
PHASE_SLOW_DANCE
PHASE_FAST_DANCE
NPC_SOLDIER_OF_THE_FROZEN_WASTES
NPC_UNSTOPPABLE_ABOMINATION
NPC_SOUL_WEAVER
NPC_GUARDIAN_OF_ICECROWN
ACTION_CALL_HELP_ON
ACTION_CALL_HELP_OFF
ACTION_SECOND_PHASE
ACTION_GUARDIANS_OFF
NPC_WEB_WRAP
NPC_MAEXXNA_SPIDERLING
NPC_PLAGUED_WARRIOR
NPC_PLAGUED_CHAMPION
NPC_PLAGUED_GUARDIAN
ACHIEV_TIMED_START_EVENT
NPC_DEATH_KNIGHT_UNDERSTUDY
NPC_RAZUVIOUS
GO_ICE_BLOCK
NPC_BLIZZARD
POINT_CENTER
ACTION_MAGNETIC_PULL
ACTION_SUMMON_DIED
ACTION_RESTORE
GO_TESLA_COIL_LEFT
GO_TESLA_COIL_RIGHT
NPC_TESLA_COIL
NPC_FIRE_MAGUS
NPC_FROST_MAGUS
NPC_ARCANE_MAGUS
ACHIEVEMENT_SPLIT_PERSONALITY
GAME_EVENT_WINTER_VEIL
NPC_CRYSTAL_SPIKE
GO_CRYSTAL_SPIKE
POS_GEN_RIGHT
POS_GEN_LEFT
POS_ROOM_CENTER
ACTION_SLUG_KILLED
SPELL_GLARE_OF_THE_TRIBUNAL
SPELL_GLARE_OF_THE_TRIBUNAL_H
SPELL_DARK_MATTER_VISUAL
SPELL_DARK_MATTER
SPELL_DARK_MATTER_H
SPELL_SEARING_GAZE
SPELL_SEARING_GAZE_H
SPELL_DRP_CHARGE
SPELL_DRP_CLEAVE
SPELL_DRS_LIGHTING_BOLT
SPELL_DRS_LIGHTING_BOLT_H
SPELL_DRS_SHADOW_WORD_PAIN
SPELL_DRS_SHADOW_WORD_PAIN_H
SPELL_IGC_CRUSH_ARMOR
SPELL_IGC_GROUND_SMASH
SPELL_IGC_GROUND_SMASH_H
ACTION_START_EVENT
ACTION_START_TRIBUNAL
ACTION_GO_TO_SJONNIR
ACTION_START_SJONNIR_FIGHT
ACTION_SJONNIR_DEAD
ACTION_ENTEREVADEMODE
ACTION_WIPE_START
ACTION_OPEN_DOOR
QUEST_HALLS_OF_STONE
POINT_BRANN_INTRO
MAX_BRANN_WAYPOINTS_INTRO
POINT_BRANN_OUTRO
POINT_BRANN_OUTRO_END
POINT_ALGALON_LAND
POINT_ALGALON_OUTRO
EVENT_ID_SUPERMASSIVE_START
DATA_HAS_FED_ON_TEARS
DATA_HERALD_OF_THE_TITANS
ACTION_ADD_CHARGE
POINT_CHANNEL_STEELBREAKER
ACTION_FERAL_RESPAWN
ACTION_FERAL_DEATH
ACTION_DESPAWN_ADDS
ACTION_FERAL_DEATH_WITH_STACK
DATA_CRAZY_CAT
DATA_NINE_LIVES
DATA_EVENT_STARTED
DATA_GET_TOWER_COUNT
DATA_GET_SHUTDOWN
TOWER_OF_STORMS
TOWER_OF_FLAMES
TOWER_OF_FROST
TOWER_OF_LIFE
ACTION_START_NORGANNON_EVENT
ACTION_START_NORGANNON_BRANN
ACTION_START_BRANN_EVENT
ACTION_DESPAWN_ADDS
ACTION_DELAY_CANNON
ACTION_DESTROYED_TURRET
ACTION_REMOVE_10_STACK
ACTION_REMOVE_25_STACK
ACTION_REMOVE_2_STACK
ACTION_RESPAWN_TRIO
ACTION_LUMBERJACKED
EVENT_PHASE_ADDS
EVENT_PHASE_FINAL
DATA_GET_ELDER_COUNT
DATA_BACK_TO_NATURE
CRITERIA_LUMBERJACKED
ACHIEVEMENT_DISARMED_CRITERIA
DATA_KOLOGARN_LOOKS_ACHIEV
DATA_KOLOGARN_RUBBLE_ACHIEV
DATA_KOLOGARN_ARMS_ACHIEV
ACTION_START_TRASH_DIED
ACTION_ALLOW_HIT
ACTION_SIF_JOIN_FIGHT
ACTION_SIF_START_TALK
ACTION_SIF_START_DOMINION
ACTION_SIF_TRANSFORM
ACTION_IRON_HONOR_DIED
EVENT_PHASE_START
EVENT_PHASE_RING
EVENT_PHASE_OUTRO
DATA_HIT_BY_LIGHTNING
DATA_LOSE_YOUR_ILLUSION
HEART_VEHICLE_SEAT
ACTION_AWAKEN_HEART
ACTION_HIDE_HEART
ACTION_HEART_BROKEN
ACHIEVEMENT_MUST_DECONSTRUCT_FASTER
DATA_XT002_NERF_ENGINEERING
DATA_XT002_GRAVITY_ACHIEV
ACTION_UNSUMMON_CLOUDS
ACTION_DESPAWN_ADDS
ACTION_START_SUMMONING
ACTION_YOGG_SARON_APPEAR
ACTION_YOGG_SARON_DEATH
ACTION_YOGG_SARON_START_YELL
ACTION_YOGG_SARON_OPEN_PORTAL_YELL
ACTION_INFLUENCE_TENTACLE_DIED
ACTION_BRAIN_DAMAGED
ACTION_REMOVE_STUN
ACTION_YOGG_SARON_START_P3
ACTION_YOGG_SARON_HARD_MODE
ACTION_YOGG_SARON_SHADOW_BEACON
ACTION_THORIM_START_STORM
ACTION_FAILED_DRIVE_ME_CRAZY
ACTION_ILLUSION_DRAGONS
ACTION_ILLUSION_ICECROWN
ACTION_ILLUSION_STORMWIND
EVENT_PHASE_ONE
EVENT_PHASE_TWO
EVENT_PHASE_THREE
CRITERIA_NOT_GETTING_OLDER
DATA_GET_KEEPERS_COUNT
DATA_GET_CURRENT_ILLUSION
DATA_GET_SARA_PHASE
DATA_GET_DRIVE_ME_CRAZY
SAY_AGGRO
SAY_SLAY
SOUND_DEATH
SPELL_ORB_VISUAL
SPELL_ORB_CHANNEL
NPC_ORB_TRIGGER
SPELL_AWAKEN_SUBBOSS
SPELL_ARCING_SMASH
SPELL_IMPALE_N
SPELL_IMPALE_H
SPELL_WITHERING_ROAR_N
SPELL_WITHERING_ROAR_H
SPELL_FREEZE
SPELL_ACID_SPIT
SPELL_ACID_SPLATTER_N
SPELL_ACID_SPLATTER_H
SPELL_POISON_BREATH_N
SPELL_POISON_BREATH_H
NPC_JORMUNGAR_WORM
SPELL_GORE_N
SPELL_GORE_H
SPELL_GRIEVOUS_WOUND_N
SPELL_GRIEVOUS_WOUND_H
SPELL_STOMP
SPELL_CHAIN_LIGHTING_N
SPELL_CHAIN_LIGHTING_H
SPELL_CRAZED
SPELL_TERRIFYING_ROAR
SPELL_MORTAL_WOUND_N
SPELL_MORTAL_WOUND_H
SPELL_ENRAGE_1
SPELL_ENRAGE_2
ACTION_START_EVENT
ACTION_UNFREEZE
ACTION_DESPAWN_ADDS
ACTION_MINIBOSS_DIED
ACTION_UNFREEZE2
SAY_AGGRO
SAY_KILL
EMOTE_RANGE
SAY_DEATH
SAY_DRAKE_DEATH
SAY_DRAKE_BREATH
SPELL_CRUSH_N
SPELL_CRUSH_H
SPELL_POISONED_SPEAR_N
SPELL_POISONED_SPEAR_H
SPELL_WHIRLWIND_N
SPELL_WHIRLWIND_H
SPELL_FLAME_VISUAL
SPELL_FLAME_BREATH_N
SPELL_FLAME_BREATH_H
SPELL_LAUNCH_HARPOON
NPC_YMIRJAR_WARRIOR
NPC_YMIRJAR_WITCH_DOCTOR
NPC_YMIRJAR_HARPOONER
NPC_GRAUF
NPC_BREATH_TRIGGER
EQUIP_MACE
ACTION_START_EVENT
ACTION_REMOVE_SKADI
ACTION_PHASE2
ACTION_MYGIRL_ACHIEVEMENT
ACHIEV_TIMED_LODI_DODI
TALK_INTRO_A1
TALK_INTRO_A2
TALK_INTRO_S1
TALK_INTRO_S2
TALK_INTRO_S3
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SAY_SACRIFICE_PLAYER
SPELL_ARTHAS_TRANSFORMING_SVALA
SPELL_SVALA_TRANSFORMING1
SPELL_SVALA_TRANSFORMING2
SPELL_CALL_FLAMES
SPELL_BALL_OF_FLAME
SPELL_RITUAL_OF_THE_SWORD
SPELL_RITUAL_STRIKE
SPELL_SINSTER_STRIKE_N
SPELL_SINSTER_STRIKE_H
EQUIP_SWORD
SPELL_PARALYZE
SPELL_SHADOWS_IN_THE_DARK
SPELL_TELEPORT_VISUAL
NPC_RITUAL_CHANNELER
NPC_ARTHAS
NPC_FLAME_BRAZIER
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SAY_SUMMON_BJORN
SAY_SUMMON_HALDOR
SAY_SUMMON_RANULF
SAY_SUMMON_TORGYN
SPELL_BANE_N
SPELL_BANE_H
SPELL_DARK_SLASH
SPELL_FETID_ROT_N
SPELL_FETID_ROT_H
SPELL_SCREAMS_OF_THE_DEAD
SPELL_SPIRIT_BURST_N
SPELL_SPIRIT_BURST_H
SPELL_SPIRIT_STRIKE_N
SPELL_SPIRIT_STRIKE_H
SPELL_SUMMON_AVENGING_SPIRIT
SPELL_SUMMON_SPIRIT_FOUNT
SPELL_CHANNEL_SPIRIT_TO_YMIRON
SPELL_CHANNEL_YMIRON_TO_SPIRIT
SPELL_SPIRIT_FOUNT_N
SPELL_SPIRIT_FOUNT_H
SPELL_FLAMES
NPC_BJORN
NPC_BJORN_VISUAL
NPC_HALDOR
NPC_HALDOR_VISUAL
NPC_RANULF
NPC_RANULF_VISUAL
NPC_TORGYN
NPC_TORGYN_VISUAL
NPC_SPIRIT_FOUNT
NPC_AVENGING_SPIRIT
EMOTE_OVERCHARGE
EMOTE_MINION_RESPAWN
EMOTE_BERSERK
NPC_TEMPEST_MINION
MAX_TEMPEST_MINIONS
EVENT_SPELL_BLOOD_BOIL
EVENT_SPELL_BEWILDERING_STRIKE
EVENT_SPELL_FEL_ACID_BREATH
EVENT_SPELL_EJECT
EVENT_SPELL_ARCING_SMASH
EVENT_SPELL_CHARGE
EVENT_SPELL_BERSERK
EVENT_SPELL_FEL_GEYSER
EVENT_KILL_TALK
GROUP_DELAY
ACTION_FIGHT_MINIONS
ACTION_RETURN_BLADE
ACTION_ILLIDAN_CAGED
ACTION_ILLIDAN_DEAD
ACTION_MAIEV_SET_DIST30
ACTION_MAIEV_SET_DIST0
ACTION_MAIEV_OUTRO
MAX_EYE_BEAM_POS
POINT_ILLIDAN_HOVER
POINT_ILLIDAN_MIDDLE
NPC_ILLIDAN_DB_TARGET
NPC_MAIEV_SHADOWSONG
GO_CAGE_TRAP
EVENT_KILL_TALK
EVENT_CHECK_HEALTH
EVENT_RANDOM_TALK
EVENT_SPELL_ENRAGE
EVENT_SPELL_PRISMATIC_AURA
EVENT_SPELL_SILENCING_SHRIEK
EVENT_SPELL_FATAL_ATTRACTION
EVENT_SPELL_SABER_LASH
ACTION_ESSENCE_OF_SUFFERING
ACTION_ESSENCE_OF_DESIRE
ACTION_ESSENCE_OF_ANGER
ACTION_ENGAGE_ESSENCE
EVENT_ESSENCE_OF_SUFFERING
EVENT_ESSENCE_OF_DESIRE
EVENT_ESSENCE_OF_ANGER
EVENT_ENGAGE_ESSENCE
EVENT_SPAWN_ENSLAVED_SOULS
EVENT_SPAWN_SOUL
EVENT_SUCK_ESSENCE
EVENT_SUFF_FRENZY
EVENT_SUFF_FRENZY_EMOTE
EVENT_SUFF_SOUL_DRAIN
EVENT_DESI_DEADEN
EVENT_DESI_SPIRIT_SHOCK
EVENT_DESI_RUNE_SHIELD
EVENT_ANGER_SPITE
EVENT_ANGER_SOUL_SCREAM
EVENT_ANGER_SEETHE
EVENT_KILL_TALK
POINT_GO_BACK
SUMMON_GROUP_BROKENS
POINT_START
POINT_CHANNEL_SOUL
ACTION_AKAMA_DIED
ACTION_START_ENCOUNTER
ACTION_STOP_SPAWNING
ACTION_DESPAWN_ALL
ACTION_CHANNELERS_START_CHANNEL
ACTION_KILL_CHANNELERS
ACTION_NO_SORCERERS
ACTION_SHADE_DIED
EVENT_AKAMA_START_ENCOUNTER
EVENT_AKAMA_START_CHANNEL
EVENT_SPELL_CHAIN_LIGHTNING
EVENT_SPELL_DESTRUCTIVE_POISON
EVENT_SHADE_CHECK_DISTANCE
EVENT_SHADE_RESET_ENCOUNTER
EVENT_SHADE_GATHER_NPCS
EVENT_SUMMON_WAVE_B
EVENT_SUMMON_ASHTONGUE_SORCERER
EVENT_SUMMON_ASHTONGUE_DEFENDER
EVENT_AKAMA_SCENE0
EVENT_AKAMA_SCENE1
EVENT_AKAMA_SCENE2
EVENT_AKAMA_SCENE3
EVENT_AKAMA_SCENE4
EVENT_AKAMA_SCENE5
EVENT_AKAMA_SCENE6
EVENT_AKAMA_SCENE7
SET_DATA_INTRO
EVENT_SPELL_INCINERATE
EVENT_SPELL_DOOM_BLOSSOM
EVENT_SPELL_CRUSHING_SHADOWS
EVENT_SPELL_SHADOW_OF_DEATH
EVENT_TALK_KILL
ACTION_START_ENCOUNTER
ACTION_END_ENCOUNTER
ACTION_ENRAGE
EVENT_SPELL_BLESSING
EVENT_SPELL_AURA
EVENT_SPELL_SEAL
EVENT_SPELL_HAMMER_OF_JUSTICE
EVENT_SPELL_JUDGEMENT
EVENT_SPELL_CONSECRATION
EVENT_SPELL_FLAMESTRIKE
EVENT_SPELL_BLIZZARD
EVENT_SPELL_ARCANE_BOLT
EVENT_SPELL_DAMPEN_MAGIC
EVENT_SPELL_ARCANE_EXPLOSION
EVENT_SPELL_REFLECTIVE_SHIELD
EVENT_SPELL_CIRCLE_OF_HEALING
EVENT_SPELL_DIVINE_WRATH
EVENT_SPELL_EMPOWERED_SMITE
EVENT_SPELL_VANISH
EVENT_SPELL_VANISH_OUT
EVENT_SPELL_ENRAGE
EVENT_KILL_TALK
MAX_ADVISORS
NPC_FATHOM_GUARD_CARIBDIS
NPC_FATHOM_GUARD_TIDALVESS
NPC_FATHOM_GUARD_SHARKKIS
NPC_SEER_OLUM
GO_CAGE
EVENT_SPELL_CATACLYSMIC_BOLT
EVENT_SPELL_ENRAGE
EVENT_SPELL_SEAR_NOVA
EVENT_HEALTH_CHECK
EVENT_KILL_TALK
GROUP_ABILITIES
NPC_PURE_SPAWN_OF_HYDROSS
EVENT_SPELL_MARK_OF_CORRUPTION1
EVENT_SPELL_MARK_OF_CORRUPTION2
EVENT_SPELL_MARK_OF_CORRUPTION3
EVENT_SPELL_MARK_OF_CORRUPTION4
EVENT_SPELL_MARK_OF_CORRUPTION5
EVENT_SPELL_MARK_OF_CORRUPTION6
EVENT_SPELL_MARK_OF_HYDROSS1
EVENT_SPELL_MARK_OF_HYDROSS2
EVENT_SPELL_MARK_OF_HYDROSS3
EVENT_SPELL_MARK_OF_HYDROSS4
EVENT_SPELL_MARK_OF_HYDROSS5
EVENT_SPELL_MARK_OF_HYDROSS6
EVENT_SPELL_WATER_TOMB
EVENT_SPELL_VILE_SLUDGE
EVENT_SPELL_ENRAGE
EVENT_CHECK_AURA
EVENT_KILL_TALK
ITEM_TAINTED_CORE
POINT_HOME
EVENT_SPELL_SHOCK_BLAST
EVENT_SPELL_STATIC_CHARGE
EVENT_SPELL_ENTANGLE
EVENT_CHECK_HEALTH
EVENT_SPELL_FORKED_LIGHTNING
EVENT_SUMMON_A
EVENT_SUMMON_B
EVENT_SUMMON_C
EVENT_SUMMON_D
EVENT_CHECK_HEALTH2
EVENT_SUMMON_SPOREBAT
EVENT_KILL_TALK
MAX_CHANNELERS
NPC_GREYHEART_SPELLBINDER
NPC_SHADOW_OF_LEOTHERAS
EVENT_SPELL_BERSERK
EVENT_HEALTH_CHECK
EVENT_SWITCH_TO_DEMON
EVENT_SPELL_WHIRLWIND
EVENT_KILL_TALK
EVENT_SWITCH_TO_ELF
EVENT_SPELL_INSIDIOUS_WHISPER
EVENT_SUMMON_DEMON
EVENT_RESTORE_FIGHT
EVENT_SPELL_SHADOW_BOLT
EMOTE_TAKE_BREATH
ACTION_START_EVENT
MAX_SUMMONS
NPC_COILFANG_GUARDIAN
NPC_COILFANG_AMBUSHER
EVENT_PHASE_1
EVENT_PHASE_2
EVENT_SPELL_WHIRL
EVENT_SPELL_SPOUT
EVENT_SPELL_GEYSER
EVENT_SPELL_SPOUT_PERIODIC
NPC_WATER_GLOBULE
NPC_TIDEWALKER_LURKER
EVENT_SPELL_TIDAL_WAVE
EVENT_SPELL_WATERY_GRAVE
EVENT_SPELL_EARTHQUAKE
EVENT_SUMMON_MURLOCS
EVENT_KILL_TALK
EVENT_SUMMON1
EVENT_SUMMON2
EVENT_TREACHEROUS_AURA
EVENT_DEMONIC_SHIELD
EVENT_KILL_TALK
EVENT_ORBITAL_STRIKE
EVENT_SHADOW_WHIP
ACTION_FLY_DOWN
POINT_MIDDLE
POINT_FLIGHT
EVENT_SPELL_REVENGE
EVENT_KILL_TALK
EVENT_AGGRO_TALK
EVENT_SPELL_FIREBALL
EVENT_SPELL_CONE_OF_FIRE
EVENT_SPELL_BELLOWING_ROAR
EVENT_CHANGE_POS
EVENT_RESTORE_COMBAT
NPC_HELLFIRE_WATCHER
EVENT_MORTAL_WOUND
EVENT_SURGE
EVENT_RETALIATION
EVENT_KILL_TALK
EVENT_CHECK_HEALTH
EMOTE_ENRAGE
SETDATA_DATA
SETDATA_YELL
EVENT_CHECK_ROOM
EVENT_SUMMON_ADDS
EVENT_SUMMON_ASSASSINS
EVENT_SPELL_CHARGE
EVENT_MOVE_TO_NEXT_POINT
EVENT_BLADE_DANCE
EVENT_FINISH_BLADE_DANCE
NPC_HARBINGER_SKYRISS_66
EVENT_SUMMON_IMAGE1
EVENT_SUMMON_IMAGE2
EVENT_SPELL_MIND_REND
EVENT_SPELL_FEAR
EVENT_SPELL_DOMINATION
EVENT_SPELL_MANA_BURN
NPC_FRAYER
EVENT_SUMMON_SEEDLING
EVENT_TREE_FORM
EVENT_CHECK_FRAYERS
EVENT_RESTORE_COMBAT
EMOTE_SUMMON
MODEL_DEFAULT
MODEL_ARCANE
MODEL_FIRE
MODEL_FROST
MODEL_NATURE
EVENT_ALERGIC_REACTION
EVENT_TRANSFORM
EVENT_TELEPORT
EVENT_SUMMON
EVENT_ARCANE_VOLLEY
EVENT_WAR_STOMP
EVENT_SUMMON_TREANT
DISPLAYID_INVISIBLE
NPC_EMBER_OF_ALAR
NPC_FLAME_PATCH
POINT_PLATFORM
POINT_QUILL
POINT_MIDDLE
POINT_DIVE
EVENT_SWITCH_PLATFORM
EVENT_START_QUILLS
EVENT_RELOCATE_MIDDLE
EVENT_REBIRTH
EVENT_SPELL_MELT_ARMOR
EVENT_SPELL_FLAME_PATCH
EVENT_SPELL_CHARGE
EVENT_SPELL_DIVE_BOMB
EVENT_START_DIVE
EVENT_CAST_DIVE_BOMB
EVENT_SUMMON_DIVE_PHOENIX
EVENT_REBIRTH_DIVE
EVENT_SPELL_BERSERK
EVENT_MOVE_TO_PHASE_2
EVENT_FINISH_DIVE
DISPLAYID_INVISIBLE
NPC_ASTROMANCER_SOLARIAN_SPOTLIGHT
NPC_SOLARIUM_AGENT
NPC_SOLARIUM_PRIEST
EVENT_CHECK_HEALTH
EVENT_SPELL_ARCANE_MISSILES
EVENT_SPELL_WRATH_OF_ASTROMANCER
EVENT_SPELL_BLINDING_LIGHT
EVENT_SPAWN_PORTALS
EVENT_SUMMON_ADDS
EVENT_REAPPEAR
EVENT_SPELL_PSYCHIC_SCREAM
EVENT_SPELL_VOID_BOLT
POINT_MIDDLE
POINT_AIR
POINT_START_LAST_PHASE
DATA_RESURRECT_CAST
NPC_WORLD_TRIGGER
NPC_NETHER_VAPOR
PHASE_NONE
PHASE_SINGLE_ADVISOR
PHASE_WEAPONS
PHASE_ALL_ADVISORS
PHASE_FINAL
EVENT_PREFIGHT_PHASE11
EVENT_PREFIGHT_PHASE12
EVENT_PREFIGHT_PHASE21
EVENT_PREFIGHT_PHASE22
EVENT_PREFIGHT_PHASE31
EVENT_PREFIGHT_PHASE32
EVENT_PREFIGHT_PHASE41
EVENT_PREFIGHT_PHASE42
EVENT_PREFIGHT_PHASE51
EVENT_PREFIGHT_PHASE52
EVENT_PREFIGHT_PHASE61
EVENT_PREFIGHT_PHASE62
EVENT_PREFIGHT_PHASE63
EVENT_PREFIGHT_PHASE71
EVENT_GATHER_ADVISORS
EVENT_SPELL_SEQ_1
EVENT_SPELL_SEQ_2
EVENT_SPELL_SEQ_3
EVENT_SPELL_FIREBALL
EVENT_SPELL_PYROBLAST
EVENT_SPELL_FLAMESTRIKE
EVENT_SPELL_ARCANE_DISRUPTION
EVENT_SPELL_MIND_CONTROL
EVENT_SPELL_SUMMON_PHOENIX
EVENT_CHECK_HEALTH
EVENT_SPELL_GRAVITY_LAPSE
EVENT_GRAVITY_LAPSE_END
EVENT_SPELL_SHOCK_BARRIER
EVENT_SPELL_NETHER_BEAM
EVENT_SPELL_NETHER_VAPOR
EVENT_SCENE_1
EVENT_SCENE_2
EVENT_SCENE_3
EVENT_SCENE_4
EVENT_SCENE_5
EVENT_SCENE_6
EVENT_SCENE_7
EVENT_SCENE_8
EVENT_SCENE_9
EVENT_SCENE_10
EVENT_SCENE_11
EVENT_SCENE_12
EVENT_SCENE_13
EVENT_SCENE_14
EVENT_SCENE_15
EVENT_SCENE_16
NPC_DK_GHOUL
Definition at line 126 of file childrens_week.cpp.
 {
     SPELL_SNOWBALL                          = 21343,
     SPELL_ORPHAN_OUT                        = 58818,
     DISPLAY_INVISIBLE                       = 11686,
 };
Orphans
enum Orphans
Enumerator
ORPHAN_ORACLE
ORPHAN_WOLVAR
ORPHAN_BLOOD_ELF
ORPHAN_DRAENEI
ORPHAN_HUMAN
ORPHAN_ORCISH
Definition at line 23 of file childrens_week.cpp.
 {
     ORPHAN_ORACLE                           = 33533,
     ORPHAN_WOLVAR                           = 33532,
     ORPHAN_BLOOD_ELF                        = 22817,
     ORPHAN_DRAENEI                          = 22818,
     ORPHAN_HUMAN                            = 14305,
     ORPHAN_ORCISH                           = 14444,
 };
Quests
enum Quests
Enumerator
QUEST_SPECTRAL_CHALICE
QUEST_PLAYMATE_WOLVAR
QUEST_PLAYMATE_ORACLE
QUEST_THE_BIGGEST_TREE_EVER
QUEST_THE_BRONZE_DRAGONSHRINE_ORACLE
QUEST_THE_BRONZE_DRAGONSHRINE_WOLVAR
QUEST_MEETING_A_GREAT_ONE
QUEST_THE_MIGHTY_HEMET_NESINGWARY
QUEST_DOWN_AT_THE_DOCKS
QUEST_GATEWAY_TO_THE_FRONTIER
QUEST_BOUGHT_OF_ETERNALS
QUEST_SPOOKY_LIGHTHOUSE
QUEST_STONEWROUGHT_DAM
QUEST_DARK_PORTAL_H
QUEST_DARK_PORTAL_A
QUEST_LORDAERON_THRONE_ROOM
QUEST_AUCHINDOUN_AND_THE_RING
QUEST_TIME_TO_VISIT_THE_CAVERNS_H
QUEST_TIME_TO_VISIT_THE_CAVERNS_A
QUEST_THE_SEAT_OF_THE_NARUU
QUEST_CALL_ON_THE_FARSEER
QUEST_JHEEL_IS_AT_AERIS_LANDING
QUEST_HCHUU_AND_THE_MUSHROOM_PEOPLE
QUEST_VISIT_THE_THRONE_OF_ELEMENTS
QUEST_NOW_WHEN_I_GROW_UP
QUEST_HOME_OF_THE_BEAR_MEN
QUEST_THE_DRAGON_QUEEN_ORACLE
QUEST_THE_DRAGON_QUEEN_WOLVAR
QUEST_PILGRIM_HORDE
QUEST_PILGRIM_ALLIANCE
QUEST_GUARDIANS_ALTAR
Definition at line 74 of file childrens_week.cpp.
 {
     QUEST_PLAYMATE_WOLVAR                   = 13951,
     QUEST_PLAYMATE_ORACLE                   = 13950,
     QUEST_THE_BIGGEST_TREE_EVER             = 13929,
     QUEST_THE_BRONZE_DRAGONSHRINE_ORACLE    = 13933,
     QUEST_THE_BRONZE_DRAGONSHRINE_WOLVAR    = 13934,
     QUEST_MEETING_A_GREAT_ONE               = 13956,
     QUEST_THE_MIGHTY_HEMET_NESINGWARY       = 13957,
     QUEST_DOWN_AT_THE_DOCKS                 = 910,
     QUEST_GATEWAY_TO_THE_FRONTIER           = 911,
     QUEST_BOUGHT_OF_ETERNALS                = 1479,
     QUEST_SPOOKY_LIGHTHOUSE                 = 1687,
     QUEST_STONEWROUGHT_DAM                  = 1558,
     QUEST_DARK_PORTAL_H                     = 10951,
     QUEST_DARK_PORTAL_A                     = 10952,
     QUEST_LORDAERON_THRONE_ROOM             = 1800,
     QUEST_AUCHINDOUN_AND_THE_RING           = 10950,
     QUEST_TIME_TO_VISIT_THE_CAVERNS_H       = 10963,
     QUEST_TIME_TO_VISIT_THE_CAVERNS_A       = 10962,
     QUEST_THE_SEAT_OF_THE_NARUU             = 10956,
     QUEST_CALL_ON_THE_FARSEER               = 10968,
     QUEST_JHEEL_IS_AT_AERIS_LANDING         = 10954,
     QUEST_HCHUU_AND_THE_MUSHROOM_PEOPLE     = 10945,
     QUEST_VISIT_THE_THRONE_OF_ELEMENTS      = 10953,
     QUEST_NOW_WHEN_I_GROW_UP                = 11975,
     QUEST_HOME_OF_THE_BEAR_MEN              = 13930,
     QUEST_THE_DRAGON_QUEEN_ORACLE           = 13954,
     QUEST_THE_DRAGON_QUEEN_WOLVAR           = 13955,
 };
Texts
enum Texts
Enumerator
SAY_NEFARIUS_REND_WIPE
SAY_SOLAKAR_FIRST_HATCHER
EMOTE_MASS_ERRUPTION
EMOTE_LOWHP
EMOTE_FRENZY
SAY_AGGRO
SAY_SPAWN
SAY_SLAY
SAY_DEFEAT
SAY_SUMMON_MAJ
SAY_ARRIVAL2_MAJ
SAY_LAST_ADD
SAY_DEFEAT_2
SAY_DEFEAT_3
SAY_RAG_SUM_1
SAY_RAG_SUM_2
SAY_ARRIVAL1_RAG
SAY_ARRIVAL3_RAG
SAY_SUMMON_MAJ
SAY_ARRIVAL1_RAG
SAY_ARRIVAL2_MAJ
SAY_ARRIVAL3_RAG
SAY_ARRIVAL5_RAG
SAY_REINFORCEMENTS1
SAY_REINFORCEMENTS2
SAY_HAND
SAY_WRATH
SAY_KILL
SAY_MAGMABURST
EMOTE_SMOLDERING
EMOTE_IGNITE
TEXT_ORACLE_ORPHAN_1
TEXT_ORACLE_ORPHAN_2
TEXT_ORACLE_ORPHAN_3
TEXT_ORACLE_ORPHAN_4
TEXT_ORACLE_ORPHAN_5
TEXT_ORACLE_ORPHAN_6
TEXT_ORACLE_ORPHAN_7
TEXT_ORACLE_ORPHAN_8
TEXT_ORACLE_ORPHAN_9
TEXT_ORACLE_ORPHAN_10
TEXT_ORACLE_ORPHAN_11
TEXT_ORACLE_ORPHAN_12
TEXT_ORACLE_ORPHAN_13
TEXT_ORACLE_ORPHAN_14
TEXT_WOLVAR_ORPHAN_1
TEXT_WOLVAR_ORPHAN_2
TEXT_WOLVAR_ORPHAN_3
TEXT_WOLVAR_ORPHAN_4
TEXT_WOLVAR_ORPHAN_5
TEXT_WOLVAR_ORPHAN_10
TEXT_WOLVAR_ORPHAN_11
TEXT_WOLVAR_ORPHAN_12
TEXT_WOLVAR_ORPHAN_13
TEXT_WINTERFIN_PLAYMATE_1
TEXT_WINTERFIN_PLAYMATE_2
TEXT_SNOWFALL_GLADE_PLAYMATE_1
TEXT_SNOWFALL_GLADE_PLAYMATE_2
TEXT_SOO_ROO_1
TEXT_ELDER_KEKEK_1
TEXT_ALEXSTRASZA_2
TEXT_KRASUS_8
SAY_ONDEATH
SAY_ONSLAY
SAY_SWARM
SAY_SLEEP
SAY_INFERNO
SAY_ONAGGRO
SAY_AGGRO
SAY_DOOMFIRE
SAY_AIR_BURST
SAY_SLAY
SAY_ENRAGE
SAY_DEATH
SAY_SOUL_CHARGE
SAY_ONDEATH
SAY_ONSLAY
SAY_DOOM
SAY_ONAGGRO
SAY_ONSLAY
SAY_MARK
SAY_ONAGGRO
SAY_ONDEATH
SAY_ONSLAY
SAY_DECAY
SAY_NOVA
SAY_ONAGGRO
SAY_KURINAXX_DEATH
EMOTE_AGGRO
EMOTE_MANA_FULL
SAY_SUPREME
SAY_INTRO
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SAY_MATRIARCH_AGGRO
SAY_VOLUNTEER_START
SAY_VOLUNTEER_END
SAY_AGGRO
SAY_INSANITY
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH_1
SAY_DEATH_2
WHISPER_AGGRO
WHISPER_INSANITY
WHISPER_SLAY_1
WHISPER_SLAY_2
WHISPER_SLAY_3
WHISPER_DEATH_1
WHISPER_DEATH_2
SAY_BALTHARUS_INTRO
SAY_AGGRO
SAY_KILL
SAY_CLONE
SAY_DEATH
SAY_XERESTRASZA_EVENT
SAY_XERESTRASZA_EVENT_1
SAY_XERESTRASZA_EVENT_2
SAY_XERESTRASZA_EVENT_3
SAY_XERESTRASZA_EVENT_4
SAY_XERESTRASZA_EVENT_5
SAY_XERESTRASZA_EVENT_6
SAY_XERESTRASZA_EVENT_7
SAY_XERESTRASZA_INTRO
SAY_AGGRO
SAY_KILL
SAY_ADDS
SAY_DEATH
SAY_REGENERATE
SAY_INTRO
SAY_AGGRO
SAY_METEOR_STRIKE
SAY_PHASE_TWO
SAY_DEATH
SAY_KILL
SAY_BERSERK
EMOTE_CORPOREALITY_POT
EMOTE_CORPOREALITY_PIP
SAY_SPHERE_PULSE
SAY_PHASE_THREE
EMOTE_CORPOREALITY_TIT
EMOTE_CORPOREALITY_TOT
EMOTE_WARN_LASER
SAY_AGGRO
SAY_CONFLAGRATION
EMOTE_ENRAGED
SAY_KILL
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SAY_MARK
SAY_SMASH
EMOTE_RIMEFANG_ICEBOLT
EMOTE_SMASH
SAY_INTRO_1
SAY_INTRO_2
SAY_KELESETH_INVOCATION
EMOTE_KELESETH_INVOCATION
SAY_KELESETH_SPECIAL
SAY_KELESETH_KILL
EMOTE_KELESETH_BERSERK
SAY_KELESETH_DEATH
SAY_TALDARAM_INVOCATION
EMOTE_TALDARAM_INVOCATION
SAY_TALDARAM_SPECIAL
EMOTE_TALDARAM_FLAME
SAY_TALDARAM_KILL
EMOTE_TALDARAM_BERSERK
EMOTE_TALDARAM_DEATH
SAY_VALANAR_INVOCATION
EMOTE_VALANAR_INVOCATION
SAY_VALANAR_SPECIAL
EMOTE_VALANAR_SHOCK_VORTEX
SAY_VALANAR_KILL
SAY_VALANAR_BERSERK
SAY_VALANAR_DEATH
SAY_AGGRO
SAY_VAMPIRIC_BITE
SAY_MIND_CONTROL
EMOTE_BLOODTHIRST
SAY_SWARMING_SHADOWS
EMOTE_SWARMING_SHADOWS
SAY_PACT_OF_THE_DARKFALLEN
SAY_AIR_PHASE
SAY_KILL
SAY_WIPE
SAY_BERSERK
SAY_DEATH
EMOTE_BERSERK_RAID
SAY_SAURFANG_INTRO_1
SAY_SAURFANG_INTRO_2
SAY_SAURFANG_INTRO_3
SAY_SAURFANG_INTRO_4
SAY_SAURFANG_INTRO_5
SAY_SAURFANG_INTRO_6
SAY_SAURFANG_INTRO_A
SAY_SAURFANG_BOARD
SAY_SAURFANG_ENTER_SKYBREAKER
SAY_SAURFANG_AXETHROWERS
SAY_SAURFANG_ROCKETEERS
SAY_SAURFANG_MAGES
SAY_SAURFANG_VICTORY
SAY_SAURFANG_WIPE
SAY_MURADIN_INTRO_1
SAY_MURADIN_INTRO_2
SAY_MURADIN_INTRO_3
SAY_MURADIN_INTRO_4
SAY_MURADIN_INTRO_5
SAY_MURADIN_INTRO_6
SAY_MURADIN_INTRO_7
SAY_MURADIN_INTRO_H
SAY_MURADIN_BOARD
SAY_MURADIN_ENTER_ORGRIMMS_HAMMER
SAY_MURADIN_RIFLEMAN
SAY_MURADIN_MORTAR
SAY_MURADIN_SORCERERS
SAY_MURADIN_VICTORY
SAY_MURADIN_WIPE
SAY_ZAFOD_ROCKET_PACK_ACTIVE
SAY_ZAFOD_ROCKET_PACK_DISABLED
SAY_OVERHEAT
SAY_PRECIOUS_DIES
SAY_AGGRO
EMOTE_SLIME_SPRAY
SAY_SLIME_SPRAY
EMOTE_UNSTABLE_EXPLOSION
SAY_UNSTABLE_EXPLOSION
SAY_KILL
SAY_BERSERK
SAY_DEATH
EMOTE_MUTATED_INFECTION
SAY_ROTFACE_OOZE_FLOOD
EMOTE_PRECIOUS_ZOMBIES
SAY_AGGRO
SAY_UNCHAINED_MAGIC
EMOTE_WARN_BLISTERING_COLD
SAY_BLISTERING_COLD
SAY_RESPITE_FOR_A_TORMENTED_SOUL
SAY_AIR_PHASE
SAY_PHASE_2
EMOTE_WARN_FROZEN_ORB
SAY_KILL
SAY_BERSERK
SAY_DEATH
EMOTE_BERSERK_RAID
EMOTE_WEAKENING
SAY_LK_INTRO_1
SAY_LK_INTRO_2
SAY_LK_INTRO_3
SAY_LK_REMORSELESS_WINTER
SAY_LK_QUAKE
SAY_LK_SUMMON_VALKYR
SAY_LK_HARVEST_SOUL
SAY_LK_FROSTMOURNE_ESCAPE
SAY_LK_FROSTMOURNE_KILL
SAY_LK_KILL
SAY_LK_BERSERK
EMOTE_DEFILE_WARNING
EMOTE_NECROTIC_PLAGUE_WARNING
SAY_LK_OUTRO_1
SAY_LK_OUTRO_2
SAY_LK_OUTRO_3
SAY_LK_OUTRO_4
SAY_LK_OUTRO_5
SAY_LK_OUTRO_6
SAY_LK_OUTRO_7
SAY_LK_OUTRO_8
SAY_TIRION_INTRO_1
SAY_TIRION_INTRO_2
SAY_TIRION_OUTRO_1
SAY_TIRION_OUTRO_2
SAY_TERENAS_OUTRO_1
SAY_TERENAS_OUTRO_2
SAY_TERENAS_INTRO_1
SAY_TERENAS_INTRO_2
SAY_TERENAS_INTRO_3
SAY_LICH_KING_INTRO
SAY_VALITHRIA_ENTER_COMBAT
SAY_VALITHRIA_DREAM_PORTAL
SAY_VALITHRIA_75_PERCENT
SAY_VALITHRIA_25_PERCENT
SAY_VALITHRIA_DEATH
SAY_VALITHRIA_PLAYER_DEATH
SAY_VALITHRIA_BERSERK
SAY_VALITHRIA_SUCCESS
SAY_TIRION_INTRO_1
SAY_TIRION_INTRO_2
SAY_TIRION_INTRO_3
SAY_TIRION_INTRO_4
SAY_TIRION_INTRO_H_5
SAY_TIRION_INTRO_A_5
SAY_LK_INTRO_1
SAY_LK_INTRO_2
SAY_LK_INTRO_3
SAY_LK_INTRO_4
SAY_LK_INTRO_5
SAY_BOLVAR_INTRO_1
SAY_SAURFANG_INTRO_1
SAY_SAURFANG_INTRO_2
SAY_SAURFANG_INTRO_3
SAY_SAURFANG_INTRO_4
SAY_MURADIN_INTRO_1
SAY_MURADIN_INTRO_2
SAY_MURADIN_INTRO_3
SAY_TRAP_ACTIVATE
EMOTE_DEATH_PLAGUE_WARNING
SAY_SVALNA_KILL_CAPTAIN
SAY_SVALNA_KILL
SAY_SVALNA_CAPTAIN_DEATH
SAY_SVALNA_DEATH
EMOTE_SVALNA_IMPALE
EMOTE_SVALNA_BROKEN_SHIELD
SAY_CROK_INTRO_1
SAY_ARNATH_INTRO_2
SAY_CROK_INTRO_3
SAY_SVALNA_EVENT_START
SAY_CROK_COMBAT_WP_0
SAY_CROK_COMBAT_WP_1
SAY_CROK_FINAL_WP
SAY_SVALNA_RESURRECT_CAPTAINS
SAY_CROK_COMBAT_SVALNA
SAY_SVALNA_AGGRO
SAY_CAPTAIN_DEATH
SAY_CAPTAIN_RESURRECTED
SAY_CAPTAIN_KILL
SAY_CAPTAIN_SECOND_DEATH
SAY_CAPTAIN_SURVIVE_TALK
SAY_CROK_WEAKENING_GAUNTLET
SAY_CROK_WEAKENING_SVALNA
SAY_CROK_DEATH
SAY_ONBOARD
SAY_NECROTIC_AURA_APPLIED
SAY_NECROTIC_AURA_REMOVED
SAY_NECROTIC_AURA_FADING
SAY_INTRO
SAY_PHASE_1
SAY_DEEP_BREATH
SAY_SLAY_P1
SAY_END_P1
SAY_PHASE_2
SAY_ANTIMAGIC_SHELL
SAY_MAGIC_BLAST
SAY_SLAY_P2
SAY_END_P2
SAY_INTRO_PHASE_3
SAY_PHASE_3
EMOTE_SURGE_OF_POWER_WARNING_P2
SAY_SURGE_OF_POWER
SAY_BUFFED_BY_SPARK
SAY_SLAY_P3
SAY_SPELL_CASTING_P3
SAY_DEATH
EMOTE_SURGE_OF_POWER_WARNING_P3
EMOTE_BERSERK
EMOTE_POWER_SPARK
SAY_ALEXSTRASZA_ONE
SAY_ALEXSTRASZA_TWO
SAY_ALEXSTRASZA_THREE
SAY_ALEXSTRASZA_FOUR
SAY_BRANN_ALGALON_INTRO_1
SAY_BRANN_ALGALON_INTRO_2
SAY_BRANN_ALGALON_OUTRO
SAY_ALGALON_INTRO_1
SAY_ALGALON_INTRO_2
SAY_ALGALON_INTRO_3
SAY_ALGALON_START_TIMER
SAY_ALGALON_AGGRO
SAY_ALGALON_COLLAPSING_STAR
EMOTE_ALGALON_COLLAPSING_STAR
SAY_ALGALON_BIG_BANG
EMOTE_ALGALON_BIG_BANG
SAY_ALGALON_ASCEND
EMOTE_ALGALON_COSMIC_SMASH
SAY_ALGALON_PHASE_TWO
SAY_ALGALON_OUTRO_1
SAY_ALGALON_OUTRO_2
SAY_ALGALON_OUTRO_3
SAY_ALGALON_OUTRO_4
SAY_ALGALON_OUTRO_5
SAY_ALGALON_DESPAWN_1
SAY_ALGALON_DESPAWN_2
SAY_ALGALON_DESPAWN_3
SAY_ALGALON_KILL
FLAME_LEVIATHAN_SAY_AGGRO
FLAME_LEVIATHAN_SAY_SLAY
FLAME_LEVIATHAN_SAY_DEATH
FLAME_LEVIATHAN_SAY_PURSUE
FLAME_LEVIATHAN_SAY_HARDMODE
FLAME_LEVIATHAN_SAY_TOWER_NONE
FLAME_LEVIATHAN_SAY_TOWER_FROST
FLAME_LEVIATHAN_SAY_TOWER_FLAME
FLAME_LEVIATHAN_SAY_TOWER_NATURE
FLAME_LEVIATHAN_SAY_TOWER_STORM
FLAME_LEVIATHAN_SAY_PLAYER_RIDING
FLAME_LEVIATHAN_SAY_OVERLOAD
FLAME_LEVIATHAN_EMOTE_PURSUE
FLAME_LEVIATHAN_EMOTE_OVERLOAD
FLAME_LEVIATHAN_EMOTE_REPAIR
SAY_AGGRO
SAY_KILL
SAY_DEATH
EMOTE_DARK_SHELL
SAY_INTRO
SAY_AGGRO
SAY_SURPREME
SAY_KILL
SAY_DEATH
EMOTE_FRENZY
SAY_RAND
SAY_AGGRO
SAY_EARTHQUAKE
SAY_OVERRUN
SAY_SLAY
SAY_DEATH
Definition at line 33 of file childrens_week.cpp.
 {
     TEXT_ORACLE_ORPHAN_1                    = 1,
     TEXT_ORACLE_ORPHAN_2                    = 2,
     TEXT_ORACLE_ORPHAN_3                    = 3,
     TEXT_ORACLE_ORPHAN_4                    = 4,
     TEXT_ORACLE_ORPHAN_5                    = 5,
     TEXT_ORACLE_ORPHAN_6                    = 6,
     TEXT_ORACLE_ORPHAN_7                    = 7,
     TEXT_ORACLE_ORPHAN_8                    = 8,
     TEXT_ORACLE_ORPHAN_9                    = 9,
     TEXT_ORACLE_ORPHAN_10                   = 10,
     TEXT_ORACLE_ORPHAN_11                   = 11,
     TEXT_ORACLE_ORPHAN_12                   = 12,
     TEXT_ORACLE_ORPHAN_13                   = 13,
     TEXT_ORACLE_ORPHAN_14                   = 14,
     TEXT_WOLVAR_ORPHAN_1                    = 1,
     TEXT_WOLVAR_ORPHAN_2                    = 2,
     TEXT_WOLVAR_ORPHAN_3                    = 3,
     TEXT_WOLVAR_ORPHAN_4                    = 4,
     TEXT_WOLVAR_ORPHAN_5                    = 5,
     // 6 - 9 used in Nesingwary script
     TEXT_WOLVAR_ORPHAN_10                   = 10,
     TEXT_WOLVAR_ORPHAN_11                   = 11,
     TEXT_WOLVAR_ORPHAN_12                   = 12,
     TEXT_WOLVAR_ORPHAN_13                   = 13,
     TEXT_WINTERFIN_PLAYMATE_1               = 1,
     TEXT_WINTERFIN_PLAYMATE_2               = 2,
     TEXT_SNOWFALL_GLADE_PLAYMATE_1          = 1,
     TEXT_SNOWFALL_GLADE_PLAYMATE_2          = 2,
     TEXT_SOO_ROO_1                          = 1,
     TEXT_ELDER_KEKEK_1                      = 1,
     TEXT_ALEXSTRASZA_2                      = 2,
     TEXT_KRASUS_8                           = 8,
 };
Function Documentation
AddSC_event_childrens_week()
void AddSC_event_childrens_week ()
Definition at line 1038 of file childrens_week.cpp.
 {
     new npc_elder_kekek();
     new npc_high_oracle_soo_roo();
     new npc_winterfin_playmate();
     new npc_snowfall_glade_playmate();
     new npc_the_etymidian();
     new npc_the_biggest_tree();
     new at_bring_your_orphan_to();
     new npc_grizzlemaw_cw_trigger();
     new npc_cw_area_trigger();
     new npc_alexstraza_the_lifebinder();
 }
Referenced by AddEventsScripts().
getOrphanGUID()
ObjectGuid getOrphanGUID (Player * player, uint32 orphan)
Definition at line 134 of file childrens_week.cpp.
 {
     if (Aura* orphanOut = player->GetAura(SPELL_ORPHAN_OUT))
         if (orphanOut->GetCaster() && orphanOut->GetCaster()->GetEntry() == orphan)
             return orphanOut->GetCaster()->GetGUID();
     return ObjectGuid::Empty;
 }
References ObjectGuid::Empty, Unit::GetAura(), and SPELL_ORPHAN_OUT.
Referenced by npc_winterfin_playmate::npc_winterfin_playmateAI::MoveInLineOfSight(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::MoveInLineOfSight(), npc_the_biggest_tree::npc_the_biggest_treeAI::MoveInLineOfSight(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::MoveInLineOfSight(), npc_elder_kekek::npc_elder_kekekAI::MoveInLineOfSight(), npc_the_etymidian::npc_the_etymidianAI::MoveInLineOfSight(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), and at_bring_your_orphan_to::OnTrigger().