Azerotcore-wotlk: G3D::Capsule Class Reference
G3D::Capsule Class Reference
#include <Capsule.h>
Public Member Functions
Capsule ()
Capsule (class BinaryInput &b)
Capsule (const Vector3 &_p1, const Vector3 &_p2, float _r)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Line axis () const
float radius () const
Vector3 point (int i) const
float height () const
Vector3 center () const
void getReferenceFrame (class CoordinateFrame &cframe) const
bool contains (const Vector3 &p) const
float volume () const
float area () const
void getBounds (AABox &out) const
void getRandomSurfacePoint (Vector3 &P, Vector3 &N) const
Vector3 randomInteriorPoint () const
Private Attributes
Vector3 p1
Vector3 p2
float _radius
Detailed Description
A shape formed by extruding a sphere along a line segment.
Definition at line 27 of file Capsule.h.
Constructor & Destructor Documentation
Capsule() [1/3]
G3D::Capsule::Capsule ()
Uninitialized
Definition at line 29 of file Capsule.cpp.
                  {
 }
Capsule() [2/3]
G3D::Capsule::Capsule (class BinaryInput & b)
Definition at line 24 of file Capsule.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Capsule() [3/3]
G3D::Capsule::Capsule (const Vector3 & _p1, const Vector3 & _p2, float _r)
Definition at line 33 of file Capsule.cpp.
     : p1(_p1), p2(_p2), _radius(_r) {
 }
Member Function Documentation
area()
float G3D::Capsule::area () const
Definition at line 67 of file Capsule.cpp.
{
     return
         // Sphere area
         pow(_radius, 2) * 4 * (float)pi() +
         // Cylinder area
         (float)twoPi() * _radius * (p1 - p2).magnitude();
 }
References _radius, p1, p2, G3D::pi(), pow(), and G3D::twoPi().
axis()
Line G3D::Capsule::axis () const
The line down the center of the capsule
Definition at line 52 of file Capsule.cpp.
{
     return Line::fromTwoPoints(p1, p2);
 }
References G3D::Line::fromTwoPoints(), p1, and p2.
center()
Vector3 G3D::Capsule::center () const inline
Definition at line 62 of file Capsule.h.
{
         return (p1 + p2) / 2.0;
     }
References p1, and p2.
Referenced by getReferenceFrame().
contains()
bool G3D::Capsule::contains (const Vector3 & p) const
Returns true if the point is inside the capsule or on its surface.
Definition at line 86 of file Capsule.cpp.
{
     return LineSegment::fromTwoPoints(p1, p2).distanceSquared(p) <= square(radius());
 }
References G3D::LineSegment::distanceSquared(), G3D::LineSegment::fromTwoPoints(), p1, p2, radius(), and G3D::square().
deserialize()
void G3D::Capsule::deserialize (class BinaryInput & b)
Definition at line 45 of file Capsule.cpp.
{
     p1.deserialize(b);
     p2.deserialize(b);
     _radius = (float)b.readFloat64();
 }
References _radius, b, G3D::Vector3::deserialize(), p1, and p2.
Referenced by Capsule().
getBounds()
void G3D::Capsule::getBounds (AABox & out) const
Get axis aligned bounding box
Definition at line 78 of file Capsule.cpp.
{
     Vector3 min = p1.min(p2) - (Vector3(1, 1, 1) * _radius);
     Vector3 max = p1.max(p2) + (Vector3(1, 1, 1) * _radius);
     out = AABox(min, max);
 }
References _radius, G3D::max(), G3D::Vector3::max(), G3D::min(), G3D::Vector3::min(), p1, and p2.
getRandomSurfacePoint()
void G3D::Capsule::getRandomSurfacePoint (Vector3 & P, Vector3 & N) const
Random world space point with outward facing normal.
Definition at line 91 of file Capsule.cpp.
{
     float h = height();
     float r = radius();
     // Create a random point on a standard capsule and then rotate to the global frame.
     // Relative areas
     float capRelArea  = sqrt(r) / 2.0f;
     float sideRelArea = r * h;
     float r1 = uniformRandom(0, capRelArea * 2 + sideRelArea);
     if (r1 < capRelArea * 2) {
         // Select a point uniformly at random on a sphere
         N = Sphere(Vector3::zero(), 1).randomSurfacePoint();
         p = N * r;
         p.y += sign(p.y) * h / 2.0f;
     } else {
         // Side
         float a = uniformRandom(0, (float)twoPi());
         N.x = cos(a);
         N.y = 0;
         N.z = sin(a);
         p.x = N.x * r;
         p.z = N.y * r;
         p.y = uniformRandom(-h / 2.0f, h / 2.0f);
     }
     // Transform to world space
     CoordinateFrame cframe;
     getReferenceFrame(cframe);
     p = cframe.pointToWorldSpace(p);
     N = cframe.normalToWorldSpace(N);
 }
References mpq::a, getReferenceFrame(), height(), G3D::CoordinateFrame::normalToWorldSpace(), G3D::CoordinateFrame::pointToWorldSpace(), radius(), G3D::Sphere::randomSurfacePoint(), G3D::sign(), G3D::twoPi(), G3D::uniformRandom(), G3D::Vector3::x, G3D::Vector3::y, G3D::Vector3::z, and G3D::Vector3::zero().
getReferenceFrame()
void G3D::Capsule::getReferenceFrame (class CoordinateFrame & cframe) const
Get a reference frame in which the center of mass is the origin and Y is the axis of the capsule.
Definition at line 129 of file Capsule.cpp.
{
     cframe.translation = center();
     Vector3 Y = (p1 - p2).direction();
     Vector3 X = (abs(Y.dot(Vector3::unitX())) > 0.9) ? Vector3::unitY() : Vector3::unitX();
     Vector3 Z = X.cross(Y).direction();
     X = Y.cross(Z);
     cframe.rotation.setColumn(0, X);
     cframe.rotation.setColumn(1, Y);
     cframe.rotation.setColumn(2, Z);
 }
References G3D::abs(), center(), p1, p2, G3D::CoordinateFrame::rotation, G3D::Matrix3::setColumn(), G3D::CoordinateFrame::translation, G3D::Vector3::unitX(), G3D::Vector3::unitY(), X, Y, and Z.
Referenced by getRandomSurfacePoint(), and randomInteriorPoint().
height()
float G3D::Capsule::height () const inline
Distance between the sphere centers. The total extent of the cylinder is 2r + h.
Definition at line 58 of file Capsule.h.
{
         return (p1 - p2).magnitude();
     }
References p1, and p2.
Referenced by getRandomSurfacePoint(), and randomInteriorPoint().
point()
Vector3 G3D::Capsule::point (int i) const inline
Argument may be 0 or 1
Definition at line 51 of file Capsule.h.
{
         debugAssert(i == 0 || i == 1);
         return (i == 0) ? p1 : p2;
     }
References debugAssert, p1, and p2.
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedCapsule(), and G3D::findRayCapsuleIntersectionAux().
radius()
float G3D::Capsule::radius () const inline
Definition at line 46 of file Capsule.h.
{
         return _radius;
     }
References _radius.
Referenced by G3D::CollisionDetection::collisionTimeForMovingSphereFixedCapsule(), contains(), G3D::findRayCapsuleIntersectionAux(), getRandomSurfacePoint(), and randomInteriorPoint().
randomInteriorPoint()
Vector3 G3D::Capsule::randomInteriorPoint () const
Point selected uniformly at random over the volume.
Definition at line 142 of file Capsule.cpp.
{
     float h = height();
     float r = radius();
     // Create a random point in a standard capsule and then rotate to the global frame.
     Vector3 p;
     float hemiVolume = (float)pi() * (r*r*r) * 4 / 6.0f;
     float cylVolume = (float)pi() * square(r) * h;
     float r1 = uniformRandom(0, 2.0f * hemiVolume + cylVolume);
     if (r1 < 2.0 * hemiVolume) {
         p = Sphere(Vector3::zero(), r).randomInteriorPoint();
         p.y += sign(p.y) * h / 2.0f;
     } else {
         // Select a point uniformly at random on a disk
         float a = uniformRandom(0, (float)twoPi());
         float r2 = sqrt(uniformRandom(0, 1)) * r;
         p = Vector3(cos(a) * r2,
                     uniformRandom(-h / 2.0f, h / 2.0f),
                     sin(a) * r2);
     }
     // Transform to world space
     CoordinateFrame cframe;
     getReferenceFrame(cframe);
     return cframe.pointToWorldSpace(p);
 }
References mpq::a, getReferenceFrame(), height(), G3D::pi(), G3D::CoordinateFrame::pointToWorldSpace(), radius(), G3D::Sphere::randomInteriorPoint(), G3D::sign(), G3D::square(), G3D::twoPi(), G3D::uniformRandom(), G3D::Vector3::y, and G3D::Vector3::zero().
serialize()
void G3D::Capsule::serialize (class BinaryOutput & b) const
Definition at line 38 of file Capsule.cpp.
{
     p1.serialize(b);
     p2.serialize(b);
     b.writeFloat64(_radius);
 }
References _radius, b, p1, p2, and G3D::Vector3::serialize().
volume()
float G3D::Capsule::volume () const
Definition at line 57 of file Capsule.cpp.
{
     return
         // Sphere volume
         pow(_radius, 3) * (float)pi() * 4 / 3 +
         // Cylinder volume
         pow(_radius, 2) * (p1 - p2).magnitude();
 }
References _radius, p1, p2, G3D::pi(), and pow().
Member Data Documentation
_radius
float G3D::Capsule::_radius private
Definition at line 32 of file Capsule.h.
Referenced by area(), deserialize(), getBounds(), radius(), serialize(), and volume().
p1
Vector3 G3D::Capsule::p1 private
Definition at line 29 of file Capsule.h.
Referenced by area(), axis(), center(), contains(), deserialize(), getBounds(), getReferenceFrame(), height(), point(), serialize(), and volume().
p2
Vector3 G3D::Capsule::p2 private
Definition at line 30 of file Capsule.h.
Referenced by area(), axis(), center(), contains(), deserialize(), getBounds(), getReferenceFrame(), height(), point(), serialize(), and volume().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Capsule.h
deps/g3dlite/source/Capsule.cpp