Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/log.h File Reference
log.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/malloc_io.h"
#include "jemalloc/internal/mutex.h"
Classes
struct log_var_s
Macros
#define JEMALLOC_LOG_VAR_BUFSIZE 1
#define JEMALLOC_LOG_BUFSIZE 4096
#define LOG_NOT_INITIALIZED 0U
#define LOG_INITIALIZED_NOT_ENABLED 1U
#define LOG_ENABLED 2U
#define LOG_VAR_INIT(name_str) {ATOMIC_INIT(LOG_NOT_INITIALIZED), name_str}
#define log_do_begin(log_var)
#define log_do_end(log_var)
#define LOG(log_var_str, ...)
Typedefs
typedef struct log_var_s log_var_t
Functions
unsigned log_var_update_state (log_var_t *log_var)
static void log_impl_varargs (const char *name,...)
Variables
char log_var_names [JEMALLOC_LOG_VAR_BUFSIZE]
atomic_b_t log_init_done
Macro Definition Documentation
JEMALLOC_LOG_BUFSIZE
#define JEMALLOC_LOG_BUFSIZE 4096
Definition at line 14 of file log.h.
JEMALLOC_LOG_VAR_BUFSIZE
#define JEMALLOC_LOG_VAR_BUFSIZE 1
Definition at line 11 of file log.h.
LOG
#define LOG (log_var_str, ...)
Value:
do {                                    \
    static log_var_t log_var = LOG_VAR_INIT(log_var_str);       \
    log_do_begin(log_var)                       \
        log_impl_varargs((log_var).name, __VA_ARGS__);      \
    log_do_end(log_var)                     \
} while (0)
Definition at line 107 of file log.h.
log_do_begin
#define log_do_begin (log_var)
Value:
if (config_log) {                           \
    unsigned log_state = atomic_load_u(&(log_var).state,        \
        ATOMIC_RELAXED);                        \
    if (unlikely(log_state == LOG_NOT_INITIALIZED)) {       \
        log_state = log_var_update_state(&(log_var));       \
        assert(log_state != LOG_NOT_INITIALIZED);       \
    }                               \
    if (log_state == LOG_ENABLED) {                 \
        {
Definition at line 65 of file log.h.
log_do_end
#define log_do_end (log_var)
Value:
        }                           \
    }                               \
}
Definition at line 76 of file log.h.
LOG_ENABLED
#define LOG_ENABLED 2U
Definition at line 53 of file log.h.
LOG_INITIALIZED_NOT_ENABLED
#define LOG_INITIALIZED_NOT_ENABLED 1U
Definition at line 52 of file log.h.
LOG_NOT_INITIALIZED
#define LOG_NOT_INITIALIZED 0U
Definition at line 51 of file log.h.
LOG_VAR_INIT
#define LOG_VAR_INIT (name_str) {ATOMIC_INIT(LOG_NOT_INITIALIZED), name_str}
Definition at line 55 of file log.h.
Typedef Documentation
log_var_t
typedef struct log_var_s log_var_t
Definition at line 39 of file log.h.
Function Documentation
log_impl_varargs()
static void log_impl_varargs (const char * name, ...) inline static
Definition at line 89 of file log.h.
{
     char buf[JEMALLOC_LOG_BUFSIZE];
     va_list ap;
     va_start(ap, name);
     const char *format = va_arg(ap, const char *);
     size_t dst_offset = 0;
     dst_offset += malloc_snprintf(buf, JEMALLOC_LOG_BUFSIZE, "%s: ", name);
     dst_offset += malloc_vsnprintf(buf + dst_offset,
         JEMALLOC_LOG_BUFSIZE - dst_offset, format, ap);
     dst_offset += malloc_snprintf(buf + dst_offset,
         JEMALLOC_LOG_BUFSIZE - dst_offset, "\n");
     va_end(ap);
     malloc_write(buf);
 }
References format(), JEMALLOC_LOG_BUFSIZE, malloc_snprintf, malloc_vsnprintf, and malloc_write.
log_var_update_state()
unsigned log_var_update_state (log_var_t * log_var)
Definition at line 44 of file log.c.
{
     const char *log_var_begin = log_var->name;
     const char *log_var_end = log_var->name + strlen(log_var->name);
     /* Pointer to one before the beginning of the current segment. */
     const char *segment_begin = log_var_names;
     /*
      * If log_init done is false, we haven't parsed the malloc conf yet.  To
      * avoid log-spew, we default to not displaying anything.
      */
     if (!atomic_load_b(&log_init_done, ATOMIC_ACQUIRE)) {
         return LOG_INITIALIZED_NOT_ENABLED;
     }
     while (true) {
         const char *segment_end = log_var_extract_segment(
             segment_begin);
         assert(segment_end < log_var_names + JEMALLOC_LOG_VAR_BUFSIZE);
         if (log_var_matches_segment(segment_begin, segment_end,
             log_var_begin, log_var_end)) {
             atomic_store_u(&log_var->state, LOG_ENABLED,
                 ATOMIC_RELAXED);
             return LOG_ENABLED;
         }
         if (*segment_end == '\0') {
             /* Hit the end of the segment string with no match. */
             atomic_store_u(&log_var->state,
                 LOG_INITIALIZED_NOT_ENABLED, ATOMIC_RELAXED);
             return LOG_INITIALIZED_NOT_ENABLED;
         }
         /* Otherwise, skip the delimiter and continue. */
         segment_begin = segment_end + 1;
     }
 }
References assert(), ATOMIC_ACQUIRE, ATOMIC_RELAXED, JEMALLOC_LOG_VAR_BUFSIZE, LOG_ENABLED, log_init_done, LOG_INITIALIZED_NOT_ENABLED, log_var_extract_segment(), log_var_matches_segment(), log_var_names, log_var_s::name, and log_var_s::state.
Variable Documentation
log_init_done
atomic_b_t log_init_done extern
Definition at line 7 of file log.c.
Referenced by log_var_update_state().
log_var_names
char log_var_names[JEMALLOC_LOG_VAR_BUFSIZE] extern
Definition at line 6 of file log.c.
Referenced by log_var_update_state().