Azerotcore-wotlk: G3D::Vector3 Class Reference
G3D::Vector3 Class Reference
#include <Vector3.h>
Public Types
enum Axis { X_AXIS =0 , Y_AXIS =1 , Z_AXIS =2 , DETECT_AXIS =-1 }
Public Member Functions
Vector3 ()
Vector3 (const Any &any)
Any toAny (const std::string &name) const
Any toAny () const
Vector3 (const Vector4int8 &)
Vector3 (const class Vector2 &v, float z)
Vector3 (const class Vector3int32 &v)
Vector3 (class BinaryInput &b)
Vector3 (float _x, float _y, float _z)
Vector3 (float coordinate[3])
Vector3 (double coordinate[3])
Vector3 (const class Vector3int16 &v)
Vector3 (class TextInput &t)
Vector3 (const class Color3 &c)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
void serialize (class TextOutput &t) const
void deserialize (class TextInput &t)
const float &__fastcall operator[] (int i) const
float & operator[] (int i)
bool nonZero () const
Axis primaryAxis () const
Vector3 & operator= (const Vector3 &rkVector)=default
Vector3 & operator= (const Any &a)
bool operator== (const Vector3 &rkVector) const
bool operator!= (const Vector3 &rkVector) const
size_t hashCode () const
bool fuzzyEq (const Vector3 &other) const
bool fuzzyNe (const Vector3 &other) const
bool isFinite () const
bool isNaN () const
bool isZero () const
bool isUnit () const
Vector3 movedTowards (const Vector3 &goal, float maxTranslation) const
void moveTowards (const Vector3 &goal, float maxTranslation)
Vector3 __fastcall operator+ (const Vector3 &v) const
Vector3 __fastcall operator- (const Vector3 &v) const
Vector3 __fastcall operator* (float s) const
Vector3 __fastcall operator/ (float s) const
Vector3 __fastcall operator* (const Vector3 &v) const
Vector3 __fastcall operator/ (const Vector3 &v) const
Vector3 __fastcall operator- () const
Vector3 &__fastcall operator+= (const Vector3 &v)
Vector3 &__fastcall operator-= (const Vector3 &v)
Vector3 &__fastcall operator*= (float s)
Vector3 &__fastcall operator/= (float s)
Vector3 &__fastcall operator*= (const Vector3 &v)
Vector3 &__fastcall operator/= (const Vector3 &v)
float length () const
float magnitude () const
Vector3 pow (float p) const
Vector3 direction () const
Vector3 fastDirection () const
Vector3 reflectAbout (const Vector3 &normal) const
Vector3 reflectionDirection (const Vector3 &normal) const
Vector3 directionOrZero () const
Vector3 refractionDirection (const Vector3 &normal, float iInside, float iOutside) const
Vector3 unit () const
Vector3 fastUnit () const
float squaredLength () const
float squaredMagnitude () const
float __fastcall dot (const Vector3 &rkVector) const
Vector3 __fastcall cross (const Vector3 &rkVector) const
Vector3 unitCross (const Vector3 &rkVector) const
class Matrix3 cross () const
Vector3 __fastcall min (const Vector3 &v) const
Vector3 __fastcall max (const Vector3 &v) const
float min () const
float max () const
std::string toString () const
Vector3 clamp (const Vector3 &low, const Vector3 &high) const
Vector3 clamp (float low, float high) const
Vector3 floor () const
Vector3 round () const
Vector3 lerp (const Vector3 &v, float alpha) const
float sum () const
float average () const
void getTangents (Vector3 &X, Vector3 &Y) const
Vector2 xx () const
Vector2 yx () const
Vector2 zx () const
Vector2 xy () const
Vector2 yy () const
Vector2 zy () const
Vector2 xz () const
Vector2 yz () const
Vector2 zz () const
Vector3 xxx () const
Vector3 yxx () const
Vector3 zxx () const
Vector3 xyx () const
Vector3 yyx () const
Vector3 zyx () const
Vector3 xzx () const
Vector3 yzx () const
Vector3 zzx () const
Vector3 xxy () const
Vector3 yxy () const
Vector3 zxy () const
Vector3 xyy () const
Vector3 yyy () const
Vector3 zyy () const
Vector3 xzy () const
Vector3 yzy () const
Vector3 zzy () const
Vector3 xxz () const
Vector3 yxz () const
Vector3 zxz () const
Vector3 xyz () const
Vector3 yyz () const
Vector3 zyz () const
Vector3 xzz () const
Vector3 yzz () const
Vector3 zzz () const
Vector4 xxxx () const
Vector4 yxxx () const
Vector4 zxxx () const
Vector4 xyxx () const
Vector4 yyxx () const
Vector4 zyxx () const
Vector4 xzxx () const
Vector4 yzxx () const
Vector4 zzxx () const
Vector4 xxyx () const
Vector4 yxyx () const
Vector4 zxyx () const
Vector4 xyyx () const
Vector4 yyyx () const
Vector4 zyyx () const
Vector4 xzyx () const
Vector4 yzyx () const
Vector4 zzyx () const
Vector4 xxzx () const
Vector4 yxzx () const
Vector4 zxzx () const
Vector4 xyzx () const
Vector4 yyzx () const
Vector4 zyzx () const
Vector4 xzzx () const
Vector4 yzzx () const
Vector4 zzzx () const
Vector4 xxxy () const
Vector4 yxxy () const
Vector4 zxxy () const
Vector4 xyxy () const
Vector4 yyxy () const
Vector4 zyxy () const
Vector4 xzxy () const
Vector4 yzxy () const
Vector4 zzxy () const
Vector4 xxyy () const
Vector4 yxyy () const
Vector4 zxyy () const
Vector4 xyyy () const
Vector4 yyyy () const
Vector4 zyyy () const
Vector4 xzyy () const
Vector4 yzyy () const
Vector4 zzyy () const
Vector4 xxzy () const
Vector4 yxzy () const
Vector4 zxzy () const
Vector4 xyzy () const
Vector4 yyzy () const
Vector4 zyzy () const
Vector4 xzzy () const
Vector4 yzzy () const
Vector4 zzzy () const
Vector4 xxxz () const
Vector4 yxxz () const
Vector4 zxxz () const
Vector4 xyxz () const
Vector4 yyxz () const
Vector4 zyxz () const
Vector4 xzxz () const
Vector4 yzxz () const
Vector4 zzxz () const
Vector4 xxyz () const
Vector4 yxyz () const
Vector4 zxyz () const
Vector4 xyyz () const
Vector4 yyyz () const
Vector4 zyyz () const
Vector4 xzyz () const
Vector4 yzyz () const
Vector4 zzyz () const
Vector4 xxzz () const
Vector4 yxzz () const
Vector4 zxzz () const
Vector4 xyzz () const
Vector4 yyzz () const
Vector4 zyzz () const
Vector4 xzzz () const
Vector4 yzzz () const
Vector4 zzzz () const
Static Public Member Functions
static void orthonormalize (Vector3 akVector[3])
static Vector3 random (Random &r=Random::common())
Random unit vector, uniformly distributed on the sphere.
static Vector3 cosHemiRandom (const Vector3 &n, Random &r=Random::common())
Random unit vector, distributed according to .
static Vector3 cosSphereRandom (const Vector3 &n, Random &r=Random::common())
static Vector3 cosPowHemiRandom (const Vector3 &n, const float k, Random &r=Random::common())
Random unit vector, distributed according to .
static Vector3 hemiRandom (const Vector3 &normal, Random &r=Random::common())
Random vector distributed over the hemisphere about normal.
static const Vector3 & zero ()
static const Vector3 & one ()
static const Vector3 & unitX ()
static const Vector3 & unitY ()
static const Vector3 & unitZ ()
static const Vector3 & inf ()
static const Vector3 & nan ()
static const Vector3 & minFinite ()
static const Vector3 & maxFinite ()
static Vector3 & ignore ()
Public Attributes
float x
float y
float z
Private Member Functions
bool operator< (const Vector3 &) const
bool operator> (const Vector3 &) const
bool operator<= (const Vector3 &) const
bool operator>= (const Vector3 &) const
Detailed Description
Swizzles Vector classes have swizzle operators, e.g. v.xy(), that allow selection of arbitrary sub-fields. These cannot be used as write masks. Examples
Vector3 v(1, 2, 3);
Vector3 j;
Vector2 b;
b = v.xz();
j = b.xx();
Warning
Do not subclass– this implementation makes assumptions about the memory layout.
Definition at line 58 of file Vector3.h.
Member Enumeration Documentation
Axis
enum G3D::Vector3::Axis
Enumerator
X_AXIS
Y_AXIS
Z_AXIS
DETECT_AXIS
Definition at line 122 of file Vector3.h.
 {X_AXIS=0, Y_AXIS=1, Z_AXIS=2, DETECT_AXIS=-1};
Constructor & Destructor Documentation
Vector3() [1/12]
Vector3::Vector3 () inline
Initializes to zero
Definition at line 604 of file Vector3.h.
                         : x(0.0f), y(0.0f), z(0.0f) {
 }
Referenced by clamp(), cross(), direction(), fastDirection(), max(), min(), operator*(), operator+(), operator-(), operator/(), operator=(), pow(), round(), xxx(), xxy(), xxz(), xyx(), xyy(), xyz(), xzx(), xzy(), xzz(), yxx(), yxy(), yxz(), yyx(), yyy(), yyz(), yzx(), yzy(), yzz(), zxx(), zxy(), zxz(), zyx(), zyy(), zyz(), zzx(), zzy(), and zzz().
Vector3() [2/12]
Vector3::Vector3 (const Any & any) explicit
Parameters
any Must either Vector3(#, #, #) or Vector3 {x = #, y = #, z = #}. Because Point3 is a typedef for Vector3 in the current implementation, this constructor accepts Point3(#, #, #), etc. as well.
Definition at line 54 of file Vector3.cpp.
{
     if (any.name() == "Vector3::inf" || any.name() == "Point3::inf") {
         *this = inf();
         return;
     } else if (any.name() == "Vector3::zero" || any.name() == "Point3::zero") {
         *this = zero();
         return;
     } else if (any.name() == "Vector3::nan" || any.name() == "Point3::nan") {
         *this = nan();
         return;
     }
     any.verifyName("Vector3", "Point3");
     any.verifyType(Any::TABLE, Any::ARRAY);
     any.verifySize(3);
     if (any.type() == Any::ARRAY) {
         x = any[0];
         y = any[1];
         z = any[2];
     } else {
         // Table
         x = any["x"];
         y = any["y"];
         z = any["z"];
     }
 }
References G3D::any(), G3D::Any::ARRAY, inf(), nan(), G3D::Any::TABLE, x, y, z, and zero().
Vector3() [3/12]
Vector3::Vector3 (const Vector4int8 & v)
Divides by 127
Definition at line 109 of file Vector3.cpp.
 : x(v.x / 127.0f), y(v.y / 127.0f), z(v.z / 127.0f) {}
Vector3() [4/12]
Vector3::Vector3 (const class Vector2 & v, float z)
Definition at line 111 of file Vector3.cpp.
                                                  : x(v.x), y(v.y), z(_z) {
 }
Vector3() [5/12]
Vector3::Vector3 (const class Vector3int32 & v)
Definition at line 107 of file Vector3.cpp.
 : x((float)v.x), y((float)v.y), z((float)v.z) {}
Vector3() [6/12]
Vector3::Vector3 (class BinaryInput & b) explicit
Definition at line 178 of file Vector3.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Vector3() [7/12]
Vector3::Vector3 (float _x, float _y, float _z) inline
Definition at line 609 of file Vector3.h.
                                                      : x(fX), y(fY), z(fZ) {
 }
Vector3() [8/12]
Vector3::Vector3 (float coordinate[3]) inline explicit
Definition at line 613 of file Vector3.h.
                                    : x(V[0]), y(V[1]), z(V[2]){
 }
Vector3() [9/12]
Vector3::Vector3 (double coordinate[3]) inline explicit
Definition at line 617 of file Vector3.h.
                                     : x((float)V[0]), y((float)V[1]), z((float)V[2]){
 }
Vector3() [10/12]
Vector3::Vector3 (const class Vector3int16 & v)
Definition at line 183 of file Vector3.cpp.
{
     x = v.x;
     y = v.y;
     z = v.z;
 }
References x, y, and z.
Vector3() [11/12]
Vector3::Vector3 (class TextInput & t) explicit
Definition at line 174 of file Vector3.cpp.
{
     deserialize(t);
 }
References deserialize().
Vector3() [12/12]
Vector3::Vector3 (const class Color3 & c) explicit
Definition at line 105 of file Vector3.cpp.
 : x(v.r), y(v.g), z(v.b) {}
Member Function Documentation
average()
float G3D::Vector3::average () const inline
Definition at line 415 of file Vector3.h.
{
         return sum() / 3.0f;
     }
References sum().
clamp() [1/2]
Vector3 G3D::Vector3::clamp (const Vector3 & low, const Vector3 & high) const inline
Definition at line 329 of file Vector3.h.
{
         return Vector3(
             G3D::clamp(x, low.x, high.x),
             G3D::clamp(y, low.y, high.y),
             G3D::clamp(z, low.z, high.z));
     }
References G3D::clamp(), Vector3(), x, y, and z.
Referenced by G3D::clamp(), and G3D::Plane::halfSpaceContains().
clamp() [2/2]
Vector3 G3D::Vector3::clamp (float low, float high) const inline
Definition at line 336 of file Vector3.h.
{
         return Vector3(
             G3D::clamp(x, low, high),
             G3D::clamp(y, low, high),
             G3D::clamp(z, low, high));
     }
References G3D::clamp(), Vector3(), x, y, and z.
cosHemiRandom()
Vector3 Vector3::cosHemiRandom (const Vector3 & n, Random & r = Random::common()) static
Random unit vector, distributed according to .
That is, so that the probability of is proportional to . Useful in photon mapping for Lambertian scattering.
Distribution rendered by G3D::DirectionHistogram:
Parameters
n Unit vector at the center of the distribution.
[Henrik] Wann Jensen, Realistic Image Synthesis using Photon Mapping eqn 2.24
Definition at line 243 of file Vector3.cpp.
{
     debugAssertM(G3D::fuzzyEq(normal.length(), 1.0f),
                  "cosHemiRandom requires its argument to have unit length");
     float x, y, z;
     r.cosHemi(x, y, z);
     // Make a coordinate system
     const Vector3& Z = normal;
     Vector3 X, Y;
     normal.getTangents(X, Y);
     return
         x * X +
         y * Y +
         z * Z;
 }
References G3D::Random::cosHemi(), debugAssertM, G3D::fuzzyEq(), getTangents(), length(), x, X, y, Y, z, and Z.
cosPowHemiRandom()
Vector3 Vector3::cosPowHemiRandom (const Vector3 & n, const float k, Random & r = Random::common()) static
Random unit vector, distributed according to .
That is, so that the probability of is proportional to . Useful in photon mapping for glossy scattering.
Distribution rendered by G3D::DirectionHistogram:
Parameters
n Unit vector at the center of the distribution.
[Ashikhmin] and Shirley, An anisotropic Phong BRDF model, Journal of Graphics Tools, 2002
Definition at line 283 of file Vector3.cpp.
{
     debugAssertM(G3D::fuzzyEq(normal.length(), 1.0f),
                  "cosPowHemiRandom requires its argument to have unit length");
     float x, y, z;
     r.cosPowHemi(k, x, y, z);
     // Make a coordinate system
     const Vector3& Z = normal;
     Vector3 X, Y;
     normal.getTangents(X, Y);
     return
         x * X +
         y * Y +
         z * Z;
 }
References G3D::Random::cosPowHemi(), debugAssertM, G3D::fuzzyEq(), getTangents(), length(), x, X, y, Y, z, and Z.
cosSphereRandom()
Vector3 Vector3::cosSphereRandom (const Vector3 & n, Random & r = Random::common()) static
Definition at line 263 of file Vector3.cpp.
{
     debugAssertM(G3D::fuzzyEq(normal.length(), 1.0f),
                  "cosSphereRandom requires its argument to have unit length");
     float x, y, z;
     r.cosSphere(x, y, z);
     // Make a coordinate system
     const Vector3& Z = normal;
     Vector3 X, Y;
     normal.getTangents(X, Y);
     return
         x * X +
         y * Y +
         z * Z;
 }
References G3D::Random::cosSphere(), debugAssertM, G3D::fuzzyEq(), getTangents(), length(), x, X, y, Y, z, and Z.
cross() [1/2]
Matrix3 Vector3::cross () const
Returns a matrix such that v.cross() * w = v.cross(w).
[ 0  -v.z  v.y ]
[ v.z  0  -v.x ]
[ -v.y v.x  0  ]
Definition at line 393 of file Vector3.cpp.
{
     return Matrix3( 0, -z,  y,
                     z,  0, -x,
                    -y,  x,  0);
 }
References x, y, and z.
Referenced by getTangents().
cross() [2/2]
Vector3 Vector3::cross (const Vector3 & rkVector) const inline
Cross product. Note that two cross products in a row can be computed more cheaply: v1 x (v2 x v3) = (v1 dot v3) v2 - (v1 dot v2) v3.
Definition at line 768 of file Vector3.h.
{
     return Vector3(y*rkVector.z - z*rkVector.y, z*rkVector.x - x*rkVector.z,
                    x*rkVector.y - y*rkVector.x);
 }
References Vector3(), x, y, and z.
Referenced by G3D::Line::closestPoint(), G3D::_internal::WeldHelper::computeFaceNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::cross(), G3D::Matrix3::eigenSolveSymmetric(), G3D::Triangle::init(), G3D::Triangle::intersect(), VMAP::IntersectTriangle(), G3D::Quat::operator*(), and G3D::Plane::Plane().
deserialize() [1/2]
void Vector3::deserialize (class BinaryInput & b)
Definition at line 190 of file Vector3.cpp.
{
     x = b.readFloat32();
     y = b.readFloat32();
     z = b.readFloat32();
 }
References b, x, y, and z.
Referenced by G3D::Box::deserialize(), G3D::Capsule::deserialize(), G3D::CoordinateFrame::deserialize(), G3D::Cylinder::deserialize(), G3D::Line::deserialize(), G3D::LineSegment::deserialize(), G3D::PhysicsFrame::deserialize(), G3D::Plane::deserialize(), G3D::Ray::deserialize(), G3D::Triangle::deserialize(), G3D::UprightFrame::deserialize(), G3D::deserialize(), and Vector3().
deserialize() [2/2]
void Vector3::deserialize (class TextInput & t)
Definition at line 197 of file Vector3.cpp.
{
     t.readSymbol("(");
     x = (float)t.readNumber();
     t.readSymbol(",");
     y = (float)t.readNumber();
     t.readSymbol(",");
     z = (float)t.readNumber();
     t.readSymbol(")");
 }
References G3D::TextInput::readNumber(), G3D::TextInput::readSymbol(), x, y, and z.
direction()
Vector3 Vector3::direction () const inline
Returns a unit-length version of this vector. Returns nan if length is almost zero.
Definition at line 748 of file Vector3.h.
{
     const float lenSquared = squaredMagnitude();
     const float invSqrt = 1.0f / sqrtf(lenSquared);
     return Vector3(x * invSqrt, y * invSqrt, z * invSqrt);
 }
References squaredMagnitude(), Vector3(), x, y, and z.
Referenced by G3D::Box::axis(), G3D::CollisionDetection::bounceDirection(), G3D::CollisionDetection::collisionTimeForMovingPointFixedTriangle(), G3D::GImage::computeNormalMap(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Cone::Cone(), G3D::GLight::directional(), G3D::findRayCapsuleIntersectionAux(), G3D::GLight::frame(), G3D::Matrix3::fromAxisAngle(), G3D::Quat::fromAxisAngleRotation(), G3D::Line::Line(), G3D::Sphere::merge(), orthonormalize(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::Plane::Plane(), reflectAbout(), reflectionDirection(), refractionDirection(), G3D::CollisionDetection::slideDirection(), G3D::GLight::spot(), G3D::Matrix3::toAxisAngle(), unit(), unitCross(), and G3D::GCamera::worldRay().
directionOrZero()
Vector3 G3D::Vector3::directionOrZero () const inline
Returns Vector3::zero() if the length is nearly zero, otherwise returns a unit vector.
Definition at line 237 of file Vector3.h.
{
         float mag = magnitude();
         if (mag < 0.0000001f) {
             return Vector3::zero();
         } else if (mag < 1.00001f && mag > 0.99999f) {
             return *this;
         } else {
             return *this * (1.0f / mag);
         }
     }
References magnitude(), and zero().
Referenced by G3D::CollisionDetection::collisionTimeForMovingSphereFixedSphere(), G3D::MeshAlg::computeAdjacency(), G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::GLight::GLight(), and G3D::_internal::WeldHelper::smoothNormals().
dot()
float Vector3::dot (const Vector3 & rkVector) const inline
Definition at line 763 of file Vector3.h.
{
     return x*rkVector.x + y*rkVector.y + z*rkVector.z;
 }
References x, y, and z.
Referenced by G3D::CollisionDetection::bounceDirection(), G3D::LineSegment::closestPoint(), G3D::Ray::closestPoint(), G3D::Line::closestPoint(), G3D::CollisionDetection::closestPointOnLineSegment(), G3D::CollisionDetection::collisionTimeForMovingPointFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedTriangle(), G3D::MeshAlg::computeAdjacency(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::ConvexPolyhedron::cut(), G3D::Plane::distance(), G3D::Matrix3::eigenSolveSymmetric(), G3D::findRayCapsuleIntersectionAux(), G3D::Plane::fuzzyContains(), getTangents(), G3D::Plane::halfSpaceContains(), G3D::Plane::halfSpaceContainsFinite(), hemiRandom(), G3D::MeshAlg::identifyBackfaces(), G3D::Triangle::intersect(), G3D::Ray::intersection(), G3D::Line::intersection(), VMAP::IntersectTriangle(), G3D::Matrix3::isRightHanded(), G3D::CoordinateFrame::lookAt(), G3D::Quat::operator*(), orthonormalize(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), G3D::Plane::Plane(), G3D::planeBoxOverlap(), G3D::Cone::randomDirectionInCone(), G3D::CollisionDetection::rayAABox(), reflectAbout(), G3D::Ray::refract(), refractionDirection(), G3D::CollisionDetection::slideDirection(), G3D::_internal::WeldHelper::smoothNormals(), and G3D::GCamera::unproject().
fastDirection()
Vector3 Vector3::fastDirection () const inline
Potentially less accurate but faster than direction(). Only works if System::hasSSE is true.
Definition at line 756 of file Vector3.h.
{
     float lenSquared = x * x + y * y + z * z;
     float invSqrt = rsq(lenSquared);
     return Vector3(x * invSqrt, y * invSqrt, z * invSqrt);
 }
References G3D::rsq(), Vector3(), x, y, and z.
Referenced by fastUnit().
fastUnit()
Vector3 G3D::Vector3::fastUnit () const inline
Returns a normalized vector. May be computed with lower precision than unit
Definition at line 287 of file Vector3.h.
{
         return fastDirection();
     }
References fastDirection().
floor()
Vector3 G3D::Vector3::floor () const inline
Definition at line 344 of file Vector3.h.
{
         return G3D::Vector3(::floor(x), ::floor(y), ::floor(z));
     }
References x, y, and z.
fuzzyEq()
bool Vector3::fuzzyEq (const Vector3 & other) const inline
Definition at line 632 of file Vector3.h.
{
     return G3D::fuzzyEq((*this - other).squaredMagnitude(), 0);
 }
References G3D::fuzzyEq(), and squaredMagnitude().
Referenced by G3D::CollisionDetection::collisionTimeForMovingSphereFixedTriangle(), and G3D::ConvexPolygon::cut().
fuzzyNe()
bool Vector3::fuzzyNe (const Vector3 & other) const inline
Definition at line 638 of file Vector3.h.
{
     return G3D::fuzzyNe((*this - other).squaredMagnitude(), 0);
 }
References G3D::fuzzyNe(), and squaredMagnitude().
getTangents()
void G3D::Vector3::getTangents (Vector3 & X, Vector3 & Y) const inline
Creates two orthonormal tangent vectors X and Y such that if Z = this, X x Y = Z.
Definition at line 437 of file Vector3.h.
{
         debugAssertM(G3D::fuzzyEq(length(), 1.0f),
                      "makeAxes requires Z to have unit length");
         // Choose another vector not perpendicular
         X = (abs(x) < 0.9f) ? Vector3::unitX() : Vector3::unitY();
         // Remove the part that is parallel to Z
         X -= *this * this->dot(X);
         X /= X.length();
         Y = this->cross(X);
     }
References G3D::abs(), cross(), debugAssertM, dot(), G3D::fuzzyEq(), length(), unitX(), unitY(), x, X, and Y.
Referenced by G3D::MeshAlg::computeTangentSpaceBasis(), cosHemiRandom(), cosPowHemiRandom(), cosSphereRandom(), and G3D::findRayCapsuleIntersectionAux().
hashCode()
size_t Vector3::hashCode () const
Definition at line 155 of file Vector3.cpp.
{
     const uint32* u = (const uint32*)this;
     return
         HashTrait<uint32>::hashCode(u[0]) ^
         HashTrait<uint32>::hashCode(~u[1]) ^
         HashTrait<uint32>::hashCode((u[2] << 16) | ~(u[2] >> 16));
 }
References G3D::hashCode().
Referenced by G3D::AABox::hashCode(), G3D::Triangle::hashCode(), HashTrait< G3D::_internal::VN >::hashCode(), HashTrait< G3D::_internal::VNTi >::hashCode(), HashTrait< G3D::Sphere >::hashCode(), and HashTrait< G3D::Vector3 >::hashCode().
hemiRandom()
Vector3 Vector3::hemiRandom (const Vector3 & normal, Random & r = Random::common()) static
Random vector distributed over the hemisphere about normal.
Distribution rendered by G3D::DirectionHistogram:
Definition at line 303 of file Vector3.cpp.
{
     const Vector3& V = Vector3::random(r);
     if (V.dot(normal) < 0) {
         return -V;
     } else {
         return V;
     }
 }
References dot(), and random().
ignore()
Vector3 & Vector3::ignore () static
Can be passed to ignore a vector3 parameter
Definition at line 114 of file Vector3.cpp.
{
     static Vector3 v;
     return v;
 }
inf()
const Vector3 & Vector3::inf () static
Definition at line 124 of file Vector3.cpp.
 { static const Vector3 v((float)G3D::finf(), (float)G3D::finf(), (float)G3D::finf()); return v; }
References G3D::finf().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingPointFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedPlane(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::computeBounds(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::computeBounds(), G3D::MeshBuilder::computeBounds(), G3D::AABox::inf(), G3D::Box::inf(), G3D::Ray::intersection(), G3D::Line::intersection(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::Node(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), Vector3(), and G3D::_internal::Welder::Welder().
isFinite()
bool Vector3::isFinite () const inline
Returns true if this vector has finite length.
Definition at line 644 of file Vector3.h.
{
     return G3D::isFinite(x) && G3D::isFinite(y) && G3D::isFinite(z);
 }
References G3D::isFinite(), x, y, and z.
Referenced by G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::ConvexPolygon::cut(), G3D::Plane::halfSpaceContainsFinite(), and G3D::AABox::isFinite().
isNaN()
bool Vector3::isNaN () const
True if any field is nan
Definition at line 83 of file Vector3.cpp.
{
     return G3D::isNaN(x) || G3D::isNaN(y) || G3D::isNaN(z);
 }
References G3D::isNaN(), x, y, and z.
Referenced by G3D::Box::getBounds(), G3D::AABox::isEmpty(), LoadGameObjectModelList(), and G3D::AABox::set().
isUnit()
bool Vector3::isUnit () const inline
Returns true if this vector has length ~= 1
Definition at line 797 of file Vector3.h.
{
     return G3D::fuzzyEq(squaredMagnitude(), 1.0f);
 }
References G3D::fuzzyEq(), and squaredMagnitude().
Referenced by G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Matrix3::fromUnitAxisAngle(), and G3D::Ray::set().
isZero()
bool Vector3::isZero () const inline
Returns true if this vector has length ~= 0
Definition at line 791 of file Vector3.h.
{
     return G3D::fuzzyEq(fabsf(x) + fabsf(y) + fabsf(z), 0.0f);
 }
References G3D::fuzzyEq(), x, y, and z.
Referenced by G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::_internal::WeldHelper::getIndex(), and G3D::_internal::WeldHelper::smoothNormals().
length()
float Vector3::length () const inline
Same as magnitude
Definition at line 743 of file Vector3.h.
{
     return magnitude();
 }
References magnitude().
Referenced by G3D::Line::closestPoint(), cosHemiRandom(), cosPowHemiRandom(), cosSphereRandom(), G3D::Box::extent(), G3D::findRayCapsuleIntersectionAux(), G3D::AABox::getBounds(), getTangents(), moveTowards(), and G3D::CollisionDetection::rayAABox().
lerp()
Vector3 G3D::Vector3::lerp (const Vector3 & v, float alpha) const inline
Linear interpolation
Definition at line 357 of file Vector3.h.
{
         return (*this) + (v - *this) * alpha;
     }
Referenced by Movement::SplineBase::InitCatmullRom(), G3D::PhysicsFrame::lerp(), and G3D::lerp().
magnitude()
float Vector3::magnitude () const inline
Definition at line 738 of file Vector3.h.
{
     return ::sqrtf(x*x + y*y + z*z);
 }
References x, y, and z.
Referenced by G3D::CollisionDetection::closestPointOnLineSegment(), G3D::CollisionDetection::closestPointOnTrianglePerimeter(), G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), G3D::MeshAlg::computeAreaStatistics(), directionOrZero(), G3D::Quat::exp(), G3D::Plane::fromEquation(), G3D::ConvexPolygon::getArea(), G3D::Triangle::init(), G3D::LineSegment::length(), length(), G3D::length(), G3D::normalize(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedSphere().
max() [1/2]
float G3D::Vector3::max () const inline
Largest element
Definition at line 323 of file Vector3.h.
{
         return G3D::max(G3D::max(x, y), z);
     }
References G3D::max(), x, y, and z.
max() [2/2]
Vector3 Vector3::max (const Vector3 & v) const inline
Definition at line 786 of file Vector3.h.
{
     return Vector3(G3D::max(v.x, x), G3D::max(v.y, y), G3D::max(v.z, z));
 }
References G3D::max(), Vector3(), x, y, and z.
Referenced by G3D::Capsule::getBounds(), G3D::Cylinder::getBounds(), G3D::Triangle::getBounds(), G3D::AABox::intersect(), G3D::max(), G3D::AABox::merge(), VMAP::TriBoundFunc::operator()(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), and G3D::_internal::Welder::Welder().
maxFinite()
const Vector3 & Vector3::maxFinite () static
Largest representable vector
Definition at line 127 of file Vector3.cpp.
 { static const Vector3 v(FLT_MAX, FLT_MAX, FLT_MAX); return v; }
References FLT_MAX.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), G3D::Plane::halfSpaceContains(), G3D::AABox::large(), and G3D::AABox::maxFinite().
min() [1/2]
float G3D::Vector3::min () const inline
Smallest element
Definition at line 318 of file Vector3.h.
{
         return G3D::min(G3D::min(x, y), z);
     }
References G3D::min(), x, y, and z.
min() [2/2]
Vector3 Vector3::min (const Vector3 & v) const inline
Definition at line 781 of file Vector3.h.
{
     return Vector3(G3D::min(v.x, x), G3D::min(v.y, y), G3D::min(v.z, z));
 }
References G3D::min(), Vector3(), x, y, and z.
Referenced by G3D::Capsule::getBounds(), G3D::Cylinder::getBounds(), G3D::Triangle::getBounds(), G3D::AABox::intersect(), G3D::AABox::merge(), G3D::min(), VMAP::TriBoundFunc::operator()(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), and G3D::_internal::Welder::Welder().
minFinite()
const Vector3 & Vector3::minFinite () static
Smallest (most negative) representable vector
Definition at line 126 of file Vector3.cpp.
 { static const Vector3 v(-FLT_MAX, -FLT_MAX, -FLT_MAX); return v; }
References FLT_MAX.
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), G3D::Plane::halfSpaceContains(), G3D::AABox::large(), and G3D::AABox::maxFinite().
movedTowards()
Vector3 Vector3::movedTowards (const Vector3 & goal, float maxTranslation) const
Returns a vector that is this translated towards goal with a maximum translation of maxTranslation.
Definition at line 35 of file Vector3.cpp.
{
     Vector3 t = *this;
     t.moveTowards(goal, maxTranslation);
     return t;
 }
References moveTowards().
moveTowards()
void Vector3::moveTowards (const Vector3 & goal, float maxTranslation)
Definition at line 42 of file Vector3.cpp.
{
     // Apply clamped translation
     Vector3 dX = goal - *this;
     float length = dX.length();
     if ((length < 0.00001f) || (length < maxTranslation)) {
         *this = goal;
     } else {
         *this += G3D::min(1.0f, maxTranslation / length) * dX;
     }
 }
References length(), and G3D::min().
Referenced by movedTowards(), and G3D::CoordinateFrame::moveTowards().
nan()
const Vector3 & Vector3::nan () static
Definition at line 125 of file Vector3.cpp.
 { static const Vector3 v((float)G3D::fnan(), (float)G3D::fnan(), (float)G3D::fnan()); return v; }
References G3D::fnan().
Referenced by Vector3().
nonZero()
bool G3D::Vector3::nonZero () const inline
Definition at line 118 of file Vector3.h.
{
         return (x != 0) || (y != 0) || (z != 0);
     }
References x, y, and z.
one()
const Vector3 & Vector3::one () static
Definition at line 120 of file Vector3.cpp.
 { static const Vector3 v(1, 1, 1); return v; }
Referenced by G3D::Ray::set().
operator!=()
bool Vector3::operator!= (const Vector3 & rkVector) const inline
Definition at line 654 of file Vector3.h.
{
     return ( x != rkVector.x || y != rkVector.y || z != rkVector.z );
 }
References x, y, and z.
operator*() [1/2]
Vector3 Vector3::operator* (const Vector3 & v) const inline
Definition at line 669 of file Vector3.h.
{
     return Vector3(x * rkVector.x, y * rkVector.y, z * rkVector.z);
 }
References Vector3(), x, y, and z.
operator*() [2/2]
Vector3 Vector3::operator* (float s) const inline
Definition at line 673 of file Vector3.h.
{
     return Vector3(x * f, y * f, z * f);
 }
References f(), Vector3(), x, y, and z.
operator*=() [1/2]
Vector3 & Vector3::operator*= (const Vector3 & v) inline
Definition at line 712 of file Vector3.h.
{
     x *= rkVector.x;
     y *= rkVector.y;
     z *= rkVector.z;
     return *this;
 }
References x, y, and z.
operator*=() [2/2]
Vector3 & Vector3::operator*= (float s) inline
Definition at line 704 of file Vector3.h.
{
     x *= fScalar;
     y *= fScalar;
     z *= fScalar;
     return *this;
 }
References x, y, and z.
operator+()
Vector3 Vector3::operator+ (const Vector3 & v) const inline
Definition at line 659 of file Vector3.h.
{
     return Vector3(x + rkVector.x, y + rkVector.y, z + rkVector.z);
 }
References Vector3(), x, y, and z.
operator+=()
Vector3 & Vector3::operator+= (const Vector3 & v) inline
Definition at line 688 of file Vector3.h.
{
     x += rkVector.x;
     y += rkVector.y;
     z += rkVector.z;
     return *this;
 }
References x, y, and z.
operator-() [1/2]
Vector3 Vector3::operator- () const inline
Definition at line 683 of file Vector3.h.
{
     return Vector3(-x, -y, -z);
 }
References Vector3(), x, y, and z.
operator-() [2/2]
Vector3 Vector3::operator- (const Vector3 & v) const inline
Definition at line 664 of file Vector3.h.
{
     return Vector3(x - rkVector.x, y - rkVector.y, z - rkVector.z);
 }
References Vector3(), x, y, and z.
operator-=()
Vector3 & Vector3::operator-= (const Vector3 & v) inline
Definition at line 696 of file Vector3.h.
{
     x -= rkVector.x;
     y -= rkVector.y;
     z -= rkVector.z;
     return *this;
 }
References x, y, and z.
operator/() [1/2]
Vector3 Vector3::operator/ (const Vector3 & v) const inline
Definition at line 678 of file Vector3.h.
{
     return Vector3(x / rkVector.x, y / rkVector.y, z / rkVector.z);
 }
References Vector3(), x, y, and z.
operator/() [2/2]
Vector3 __fastcall G3D::Vector3::operator/ (float s) const inline
Definition at line 159 of file Vector3.h.
{
         return *this * (1.0f / s);
     }
operator/=() [1/2]
Vector3 & Vector3::operator/= (const Vector3 & v) inline
Definition at line 720 of file Vector3.h.
{
     x /= rkVector.x;
     y /= rkVector.y;
     z /= rkVector.z;
     return *this;
 }
References x, y, and z.
operator/=() [2/2]
Vector3& __fastcall G3D::Vector3::operator/= (float s) inline
Definition at line 170 of file Vector3.h.
{
         return (*this *= (1.0f / s));
     }
operator<()
bool G3D::Vector3::operator< (const Vector3 &) const private
operator<=()
bool G3D::Vector3::operator<= (const Vector3 &) const private
operator=() [1/2]
Vector3 & Vector3::operator= (const Any & a)
Definition at line 88 of file Vector3.cpp.
{
     *this = Vector3(a);
     return *this;
 }
References mpq::a, and Vector3().
operator=() [2/2]
Vector3& G3D::Vector3::operator= (const Vector3 & rkVector) default
operator==()
bool Vector3::operator== (const Vector3 & rkVector) const inline
Definition at line 649 of file Vector3.h.
{
     return ( x == rkVector.x && y == rkVector.y && z == rkVector.z );
 }
References x, y, and z.
operator>()
bool G3D::Vector3::operator> (const Vector3 &) const private
operator>=()
bool G3D::Vector3::operator>= (const Vector3 &) const private
operator[]() [1/2]
float & Vector3::operator[] (int i) inline
Definition at line 625 of file Vector3.h.
{
     return ((float*)this)[i];
 }
operator[]() [2/2]
const float & Vector3::operator[] (int i) const inline
Definition at line 621 of file Vector3.h.
{
     return ((float*)this)[i];
 }
orthonormalize()
void Vector3::orthonormalize (Vector3 akVector[3]) static
Gram-Schmidt orthonormalization.
Definition at line 357 of file Vector3.cpp.
{
     // If the input vectors are v0, v1, and v2, then the Gram-Schmidt
     // orthonormalization produces vectors u0, u1, and u2 as follows,
     //
     //   u0 = v0/|v0|
     //   u1 = (v1-(u0*v1)u0)/|v1-(u0*v1)u0|
     //   u2 = (v2-(u0*v2)u0-(u1*v2)u1)/|v2-(u0*v2)u0-(u1*v2)u1|
     //
     // where |A| indicates length of vector A and A*B indicates dot
     // product of vectors A and B.
     // compute u0
     akVector[0] = akVector[0].direction();
     // compute u1
     float fDot0 = akVector[0].dot(akVector[1]);
     akVector[1] -= akVector[0] * fDot0;
     akVector[1] = akVector[1].direction();
     // compute u2
     float fDot1 = akVector[1].dot(akVector[2]);
     fDot0 = akVector[0].dot(akVector[2]);
     akVector[2] -= akVector[0] * fDot0 + akVector[1] * fDot1;
     akVector[2] = akVector[2].direction();
 }
References direction(), and dot().
pow()
Vector3 G3D::Vector3::pow (float p) const inline
Raise each component of this vector to a power
Definition at line 182 of file Vector3.h.
{
         return Vector3(powf(x, p), powf(y, p), powf(z, p));
     }
References Vector3(), x, y, and z.
primaryAxis()
Vector3::Axis Vector3::primaryAxis () const
Returns the largest dimension. Particularly convenient for determining which plane to project a triangle onto for point-in-polygon tests.
Definition at line 129 of file Vector3.cpp.
{
     Axis a = X_AXIS;
     double nx = abs(x);
     double ny = abs(y);
     double nz = abs(z);
     if (nx > ny) {
         if (nx > nz) {
             a = X_AXIS;
         } else {
             a = Z_AXIS;
         }
     } else {
         if (ny > nz) {
             a = Y_AXIS;
         } else {
             a = Z_AXIS;
         }
     }
     return a;
 }
References mpq::a, G3D::abs(), x, X_AXIS, y, Y_AXIS, z, and Z_AXIS.
Referenced by G3D::Triangle::init(), G3D::CollisionDetection::isPointInsideTriangle(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), and G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode().
random()
Vector3 Vector3::random (Random & r = Random::common()) static
Random unit vector, uniformly distributed on the sphere.
Distribution rendered by G3D::DirectionHistogram:
Definition at line 226 of file Vector3.cpp.
{
     Vector3 result;
     r.sphere(result.x, result.y, result.z);
     return result;
 }
References G3D::Random::sphere().
Referenced by G3D::GLight::frame(), and hemiRandom().
reflectAbout()
Vector3 Vector3::reflectAbout (const Vector3 & normal) const
Reflect this vector about the (not necessarily unit) normal. Assumes that both the before and after vectors point away from the base of the normal.
Note that if used for a collision or ray reflection you must negate the resulting vector to get a direction pointing away from the collision.
  V'    N      V
    r   ^   -,
     \  |  /
       |/
See also Vector3::reflectionDirection
Definition at line 233 of file Vector3.cpp.
{
     Vector3 out;
     Vector3 N = normal.direction();
     // 2 * normal.dot(this) * normal - this
     return N * 2 * this->dot(N) - *this;
 }
References direction(), and dot().
Referenced by reflectionDirection().
reflectionDirection()
Vector3 Vector3::reflectionDirection (const Vector3 & normal) const
See also G3D::Ray::reflect. The length is 1.
  V'    N       V
    r   ^    /
     \  |  /
       |'-
Definition at line 315 of file Vector3.cpp.
{
     return -reflectAbout(normal).direction();
 }
References direction(), and reflectAbout().
Referenced by G3D::Ray::reflect().
refractionDirection()
Vector3 Vector3::refractionDirection (const Vector3 & normal, float iInside, float iOutside) const
Returns the direction of a refracted ray, where iExit is the index of refraction for the previous material and iEnter is the index of refraction for the new material. Like Vector3::reflectionDirection, the result has length 1 and is pointed away from the intersection.
Returns Vector3::zero() in the case of total internal refraction.
Parameters
iOutside The index of refraction (eta) outside (on the positive normal side) of the surface.
iInside The index of refraction (eta) inside (on the negative normal side) of the surface.
See also G3D::Ray::refract.
         N      V
         ^    /
         |  /
         |'-
     __--
V'<--
Definition at line 321 of file Vector3.cpp.
{
     // From pg. 24 of Henrik Wann Jensen. Realistic Image Synthesis
     // Using Photon Mapping.  AK Peters. ISBN: 1568811470. July 2001.
     // Invert the directions from Wann Jensen's formulation
     // and normalize the vectors.
     const Vector3 W = -direction();
     Vector3 N = normal.direction();
     float h1 = iOutside;
     float h2 = iInside;
     if (normal.dot(*this) > 0.0f) {
         h1 = iInside;
         h2 = iOutside;
         N  = -N;
     }
     const float hRatio = h1 / h2;
     const float WdotN = W.dot(N);
     float det = 1.0f - (float)square(hRatio) * (1.0f - (float)square(WdotN));
     if (det < 0) {
         // Total internal reflection
         return Vector3::zero();
     } else {
         return -hRatio * (W - WdotN * N) - N * sqrt(det);
     }
 }
References direction(), dot(), G3D::square(), and zero().
Referenced by G3D::Ray::refract().
round()
Vector3 G3D::Vector3::round () const inline
Definition at line 349 of file Vector3.h.
{
         return Vector3(G3D::round(x), G3D::round(y), G3D::round(z));
     }
References G3D::round(), Vector3(), x, y, and z.
serialize() [1/2]
void Vector3::serialize (class BinaryOutput & b) const
Format is three float32's
Definition at line 219 of file Vector3.cpp.
{
     b.writeFloat32(x);
     b.writeFloat32(y);
     b.writeFloat32(z);
 }
References b, x, y, and z.
Referenced by G3D::Triangle::serialize(), G3D::Box::serialize(), G3D::Capsule::serialize(), G3D::CoordinateFrame::serialize(), G3D::Cylinder::serialize(), G3D::Line::serialize(), G3D::LineSegment::serialize(), G3D::PhysicsFrame::serialize(), G3D::Plane::serialize(), G3D::Ray::serialize(), G3D::UprightFrame::serialize(), and G3D::serialize().
serialize() [2/2]
void Vector3::serialize (class TextOutput & t) const
Format is "(%f, %f, %f)"
Definition at line 208 of file Vector3.cpp.
{
    t.writeSymbol("(");
    t.writeNumber(x);
    t.writeSymbol(",");
    t.writeNumber(y);
    t.writeSymbol(",");
    t.writeNumber(z);
    t.writeSymbol(")");
 }
References G3D::TextOutput::writeNumber(), G3D::TextOutput::writeSymbol(), x, y, and z.
squaredLength()
float Vector3::squaredLength () const inline
Same as squaredMagnitude
Definition at line 733 of file Vector3.h.
{
     return squaredMagnitude();
 }
References squaredMagnitude().
Referenced by G3D::CollisionDetection::collisionTimeForMovingSphereFixedSphere(), G3D::Cone::randomDirectionInCone(), and G3D::CollisionDetection::rayAABox().
squaredMagnitude()
float Vector3::squaredMagnitude () const inline
Definition at line 728 of file Vector3.h.
{
     return x*x + y*y + z*z;
 }
References x, y, and z.
Referenced by G3D::CollisionDetection::bounceDirection(), G3D::LineSegment::closestPoint(), G3D::CollisionDetection::conservativeBoxBoxTest(), direction(), fuzzyEq(), fuzzyNe(), isUnit(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), and squaredLength().
sum()
float G3D::Vector3::sum () const inline
Definition at line 411 of file Vector3.h.
{
         return x + y + z;
     }
References x, y, and z.
Referenced by average().
toAny() [1/2]
Any Vector3::toAny () const
Converts the Vector3 to an Any.
Definition at line 94 of file Vector3.cpp.
{
     return toAny("Vector3");
 }
toAny() [2/2]
Any Vector3::toAny (const std::string & name) const
Converts the Vector3 to an Any, using the specified name instead of "Vector3"
Definition at line 99 of file Vector3.cpp.
{
     Any any(Any::ARRAY, name);
     any.append(x, y, z);
     return any;
 }
References G3D::any(), G3D::Any::ARRAY, x, y, and z.
Referenced by G3D::PhysicsFrame::toAny().
toString()
std::string Vector3::toString () const
Definition at line 386 of file Vector3.cpp.
{
     return G3D::format("(%g, %g, %g)", x, y, z);
 }
References G3D::format(), x, y, and z.
Referenced by G3D::CollisionDetection::collisionTimeForMovingSphereFixedTriangle(), LoadGameObjectModelList(), G3D::operator<<(), and G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::verifyNode().
unit()
Vector3 G3D::Vector3::unit () const inline
Synonym for direction
Definition at line 281 of file Vector3.h.
{
         return direction();
     }
References direction().
unitCross()
Vector3 Vector3::unitCross (const Vector3 & rkVector) const inline
Definition at line 774 of file Vector3.h.
{
     Vector3 kCross(y*rkVector.z - z*rkVector.y, z*rkVector.x - x*rkVector.z,
                    x*rkVector.y - y*rkVector.x);
     return kCross.direction();
 }
References direction(), x, y, and z.
unitX()
const Vector3 & Vector3::unitX () static
Definition at line 121 of file Vector3.cpp.
 { static const Vector3 v(1, 0, 0); return v; }
Referenced by G3D::Capsule::getReferenceFrame(), G3D::Cylinder::getReferenceFrame(), getTangents(), G3D::CoordinateFrame::lookAt(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::Matrix4::pitchDegrees(), G3D::Ray::Ray(), and G3D::UprightFrame::toCoordinateFrame().
unitY()
const Vector3 & Vector3::unitY () static
Definition at line 122 of file Vector3.cpp.
 { static const Vector3 v(0, 1, 0); return v; }
Referenced by G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Capsule::getReferenceFrame(), G3D::Cylinder::getReferenceFrame(), getTangents(), G3D::CoordinateFrame::lookAt(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::UprightFrame::toCoordinateFrame(), and G3D::Matrix4::yawDegrees().
unitZ()
const Vector3 & Vector3::unitZ () static
Definition at line 123 of file Vector3.cpp.
 { static const Vector3 v(0, 0, 1); return v; }
Referenced by G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::Matrix4::rollDegrees(), and GameObject::SetLocalRotation().
xx()
Vector2 Vector3::xx () const
Definition at line 411 of file Vector3.cpp.
 { return Vector2       (x, x); }
References x.
xxx()
Vector3 Vector3::xxx () const
Definition at line 423 of file Vector3.cpp.
 { return Vector3       (x, x, x); }
References Vector3(), and x.
xxxx()
Vector4 Vector3::xxxx () const
Definition at line 453 of file Vector3.cpp.
 { return Vector4       (x, x, x, x); }
References x.
xxxy()
Vector4 Vector3::xxxy () const
Definition at line 480 of file Vector3.cpp.
 { return Vector4       (x, x, x, y); }
References x, and y.
xxxz()
Vector4 Vector3::xxxz () const
Definition at line 507 of file Vector3.cpp.
 { return Vector4       (x, x, x, z); }
References x, and z.
xxy()
Vector3 Vector3::xxy () const
Definition at line 432 of file Vector3.cpp.
 { return Vector3       (x, x, y); }
References Vector3(), x, and y.
xxyx()
Vector4 Vector3::xxyx () const
Definition at line 462 of file Vector3.cpp.
 { return Vector4       (x, x, y, x); }
References x, and y.
xxyy()
Vector4 Vector3::xxyy () const
Definition at line 489 of file Vector3.cpp.
 { return Vector4       (x, x, y, y); }
References x, and y.
xxyz()
Vector4 Vector3::xxyz () const
Definition at line 516 of file Vector3.cpp.
 { return Vector4       (x, x, y, z); }
References x, y, and z.
xxz()
Vector3 Vector3::xxz () const
Definition at line 441 of file Vector3.cpp.
 { return Vector3       (x, x, z); }
References Vector3(), x, and z.
xxzx()
Vector4 Vector3::xxzx () const
Definition at line 471 of file Vector3.cpp.
 { return Vector4       (x, x, z, x); }
References x, and z.
xxzy()
Vector4 Vector3::xxzy () const
Definition at line 498 of file Vector3.cpp.
 { return Vector4       (x, x, z, y); }
References x, y, and z.
xxzz()
Vector4 Vector3::xxzz () const
Definition at line 525 of file Vector3.cpp.
 { return Vector4       (x, x, z, z); }
References x, and z.
xy()
Vector2 Vector3::xy () const
Definition at line 414 of file Vector3.cpp.
 { return Vector2       (x, y); }
References x, and y.
xyx()
Vector3 Vector3::xyx () const
Definition at line 426 of file Vector3.cpp.
 { return Vector3       (x, y, x); }
References Vector3(), x, and y.
xyxx()
Vector4 Vector3::xyxx () const
Definition at line 456 of file Vector3.cpp.
 { return Vector4       (x, y, x, x); }
References x, and y.
xyxy()
Vector4 Vector3::xyxy () const
Definition at line 483 of file Vector3.cpp.
 { return Vector4       (x, y, x, y); }
References x, and y.
xyxz()
Vector4 Vector3::xyxz () const
Definition at line 510 of file Vector3.cpp.
 { return Vector4       (x, y, x, z); }
References x, y, and z.
xyy()
Vector3 Vector3::xyy () const
Definition at line 435 of file Vector3.cpp.
 { return Vector3       (x, y, y); }
References Vector3(), x, and y.
xyyx()
Vector4 Vector3::xyyx () const
Definition at line 465 of file Vector3.cpp.
 { return Vector4       (x, y, y, x); }
References x, and y.
xyyy()
Vector4 Vector3::xyyy () const
Definition at line 492 of file Vector3.cpp.
 { return Vector4       (x, y, y, y); }
References x, and y.
xyyz()
Vector4 Vector3::xyyz () const
Definition at line 519 of file Vector3.cpp.
 { return Vector4       (x, y, y, z); }
References x, y, and z.
xyz()
Vector3 Vector3::xyz () const
Definition at line 444 of file Vector3.cpp.
 { return Vector3       (x, y, z); }
References Vector3(), x, y, and z.
xyzx()
Vector4 Vector3::xyzx () const
Definition at line 474 of file Vector3.cpp.
 { return Vector4       (x, y, z, x); }
References x, y, and z.
xyzy()
Vector4 Vector3::xyzy () const
Definition at line 501 of file Vector3.cpp.
 { return Vector4       (x, y, z, y); }
References x, y, and z.
xyzz()
Vector4 Vector3::xyzz () const
Definition at line 528 of file Vector3.cpp.
 { return Vector4       (x, y, z, z); }
References x, y, and z.
xz()
Vector2 Vector3::xz () const
Definition at line 417 of file Vector3.cpp.
 { return Vector2       (x, z); }
References x, and z.
Referenced by G3D::MeshAlg::generateGrid().
xzx()
Vector3 Vector3::xzx () const
Definition at line 429 of file Vector3.cpp.
 { return Vector3       (x, z, x); }
References Vector3(), x, and z.
xzxx()
Vector4 Vector3::xzxx () const
Definition at line 459 of file Vector3.cpp.
 { return Vector4       (x, z, x, x); }
References x, and z.
xzxy()
Vector4 Vector3::xzxy () const
Definition at line 486 of file Vector3.cpp.
 { return Vector4       (x, z, x, y); }
References x, y, and z.
xzxz()
Vector4 Vector3::xzxz () const
Definition at line 513 of file Vector3.cpp.
 { return Vector4       (x, z, x, z); }
References x, and z.
xzy()
Vector3 Vector3::xzy () const
Definition at line 438 of file Vector3.cpp.
 { return Vector3       (x, z, y); }
References Vector3(), x, y, and z.
xzyx()
Vector4 Vector3::xzyx () const
Definition at line 468 of file Vector3.cpp.
 { return Vector4       (x, z, y, x); }
References x, y, and z.
xzyy()
Vector4 Vector3::xzyy () const
Definition at line 495 of file Vector3.cpp.
 { return Vector4       (x, z, y, y); }
References x, y, and z.
xzyz()
Vector4 Vector3::xzyz () const
Definition at line 522 of file Vector3.cpp.
 { return Vector4       (x, z, y, z); }
References x, y, and z.
xzz()
Vector3 Vector3::xzz () const
Definition at line 447 of file Vector3.cpp.
 { return Vector3       (x, z, z); }
References Vector3(), x, and z.
xzzx()
Vector4 Vector3::xzzx () const
Definition at line 477 of file Vector3.cpp.
 { return Vector4       (x, z, z, x); }
References x, and z.
xzzy()
Vector4 Vector3::xzzy () const
Definition at line 504 of file Vector3.cpp.
 { return Vector4       (x, z, z, y); }
References x, y, and z.
xzzz()
Vector4 Vector3::xzzz () const
Definition at line 531 of file Vector3.cpp.
 { return Vector4       (x, z, z, z); }
References x, and z.
yx()
Vector2 Vector3::yx () const
Definition at line 412 of file Vector3.cpp.
 { return Vector2       (y, x); }
References x, and y.
yxx()
Vector3 Vector3::yxx () const
Definition at line 424 of file Vector3.cpp.
 { return Vector3       (y, x, x); }
References Vector3(), x, and y.
yxxx()
Vector4 Vector3::yxxx () const
Definition at line 454 of file Vector3.cpp.
 { return Vector4       (y, x, x, x); }
References x, and y.
yxxy()
Vector4 Vector3::yxxy () const
Definition at line 481 of file Vector3.cpp.
 { return Vector4       (y, x, x, y); }
References x, and y.
yxxz()
Vector4 Vector3::yxxz () const
Definition at line 508 of file Vector3.cpp.
 { return Vector4       (y, x, x, z); }
References x, y, and z.
yxy()
Vector3 Vector3::yxy () const
Definition at line 433 of file Vector3.cpp.
 { return Vector3       (y, x, y); }
References Vector3(), x, and y.
yxyx()
Vector4 Vector3::yxyx () const
Definition at line 463 of file Vector3.cpp.
 { return Vector4       (y, x, y, x); }
References x, and y.
yxyy()
Vector4 Vector3::yxyy () const
Definition at line 490 of file Vector3.cpp.
 { return Vector4       (y, x, y, y); }
References x, and y.
yxyz()
Vector4 Vector3::yxyz () const
Definition at line 517 of file Vector3.cpp.
 { return Vector4       (y, x, y, z); }
References x, y, and z.
yxz()
Vector3 Vector3::yxz () const
Definition at line 442 of file Vector3.cpp.
 { return Vector3       (y, x, z); }
References Vector3(), x, y, and z.
yxzx()
Vector4 Vector3::yxzx () const
Definition at line 472 of file Vector3.cpp.
 { return Vector4       (y, x, z, x); }
References x, y, and z.
yxzy()
Vector4 Vector3::yxzy () const
Definition at line 499 of file Vector3.cpp.
 { return Vector4       (y, x, z, y); }
References x, y, and z.
yxzz()
Vector4 Vector3::yxzz () const
Definition at line 526 of file Vector3.cpp.
 { return Vector4       (y, x, z, z); }
References x, y, and z.
yy()
Vector2 Vector3::yy () const
Definition at line 415 of file Vector3.cpp.
 { return Vector2       (y, y); }
References y.
yyx()
Vector3 Vector3::yyx () const
Definition at line 427 of file Vector3.cpp.
 { return Vector3       (y, y, x); }
References Vector3(), x, and y.
yyxx()
Vector4 Vector3::yyxx () const
Definition at line 457 of file Vector3.cpp.
 { return Vector4       (y, y, x, x); }
References x, and y.
yyxy()
Vector4 Vector3::yyxy () const
Definition at line 484 of file Vector3.cpp.
 { return Vector4       (y, y, x, y); }
References x, and y.
yyxz()
Vector4 Vector3::yyxz () const
Definition at line 511 of file Vector3.cpp.
 { return Vector4       (y, y, x, z); }
References x, y, and z.
yyy()
Vector3 Vector3::yyy () const
Definition at line 436 of file Vector3.cpp.
 { return Vector3       (y, y, y); }
References Vector3(), and y.
yyyx()
Vector4 Vector3::yyyx () const
Definition at line 466 of file Vector3.cpp.
 { return Vector4       (y, y, y, x); }
References x, and y.
yyyy()
Vector4 Vector3::yyyy () const
Definition at line 493 of file Vector3.cpp.
 { return Vector4       (y, y, y, y); }
References y.
yyyz()
Vector4 Vector3::yyyz () const
Definition at line 520 of file Vector3.cpp.
 { return Vector4       (y, y, y, z); }
References y, and z.
yyz()
Vector3 Vector3::yyz () const
Definition at line 445 of file Vector3.cpp.
 { return Vector3       (y, y, z); }
References Vector3(), y, and z.
yyzx()
Vector4 Vector3::yyzx () const
Definition at line 475 of file Vector3.cpp.
 { return Vector4       (y, y, z, x); }
References x, y, and z.
yyzy()
Vector4 Vector3::yyzy () const
Definition at line 502 of file Vector3.cpp.
 { return Vector4       (y, y, z, y); }
References y, and z.
yyzz()
Vector4 Vector3::yyzz () const
Definition at line 529 of file Vector3.cpp.
 { return Vector4       (y, y, z, z); }
References y, and z.
yz()
Vector2 Vector3::yz () const
Definition at line 418 of file Vector3.cpp.
 { return Vector2       (y, z); }
References y, and z.
yzx()
Vector3 Vector3::yzx () const
Definition at line 430 of file Vector3.cpp.
 { return Vector3       (y, z, x); }
References Vector3(), x, y, and z.
yzxx()
Vector4 Vector3::yzxx () const
Definition at line 460 of file Vector3.cpp.
 { return Vector4       (y, z, x, x); }
References x, y, and z.
yzxy()
Vector4 Vector3::yzxy () const
Definition at line 487 of file Vector3.cpp.
 { return Vector4       (y, z, x, y); }
References x, y, and z.
yzxz()
Vector4 Vector3::yzxz () const
Definition at line 514 of file Vector3.cpp.
 { return Vector4       (y, z, x, z); }
References x, y, and z.
yzy()
Vector3 Vector3::yzy () const
Definition at line 439 of file Vector3.cpp.
 { return Vector3       (y, z, y); }
References Vector3(), y, and z.
yzyx()
Vector4 Vector3::yzyx () const
Definition at line 469 of file Vector3.cpp.
 { return Vector4       (y, z, y, x); }
References x, y, and z.
yzyy()
Vector4 Vector3::yzyy () const
Definition at line 496 of file Vector3.cpp.
 { return Vector4       (y, z, y, y); }
References y, and z.
yzyz()
Vector4 Vector3::yzyz () const
Definition at line 523 of file Vector3.cpp.
 { return Vector4       (y, z, y, z); }
References y, and z.
yzz()
Vector3 Vector3::yzz () const
Definition at line 448 of file Vector3.cpp.
 { return Vector3       (y, z, z); }
References Vector3(), y, and z.
yzzx()
Vector4 Vector3::yzzx () const
Definition at line 478 of file Vector3.cpp.
 { return Vector4       (y, z, z, x); }
References x, y, and z.
yzzy()
Vector4 Vector3::yzzy () const
Definition at line 505 of file Vector3.cpp.
 { return Vector4       (y, z, z, y); }
References y, and z.
yzzz()
Vector4 Vector3::yzzz () const
Definition at line 532 of file Vector3.cpp.
 { return Vector4       (y, z, z, z); }
References y, and z.
zero()
const Vector3 & Vector3::zero () static
Definition at line 119 of file Vector3.cpp.
 { static const Vector3 v(0, 0, 0); return v; }
Referenced by G3D::CollisionDetection::closestPointOnTrianglePerimeter(), G3D::CollisionDetection::collisionLocationForMovingPointFixedAABox(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedBox(), G3D::MeshAlg::computeBounds(), G3D::MeshAlg::computeNormals(), directionOrZero(), G3D::GLight::effectSphere(), G3D::AABox::extent(), G3D::GLight::frame(), G3D::GCamera::frustum(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::Capsule::getRandomSurfacePoint(), G3D::Triangle::init(), G3D::CoordinateFrame::isIdentity(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::PhysicsFrame::PhysicsFrame(), G3D::Capsule::randomInteriorPoint(), G3D::Ray::Ray(), refractionDirection(), G3D::Color3::toHSV(), G3D::Triangle::Triangle(), Vector3(), Movement::WriteCatmullRomCyclicPath(), Movement::PacketBuilder::WriteCreate(), and G3D::AABox::zero().
zx()
Vector2 Vector3::zx () const
Definition at line 413 of file Vector3.cpp.
 { return Vector2       (z, x); }
References x, and z.
zxx()
Vector3 Vector3::zxx () const
Definition at line 425 of file Vector3.cpp.
 { return Vector3       (z, x, x); }
References Vector3(), x, and z.
zxxx()
Vector4 Vector3::zxxx () const
Definition at line 455 of file Vector3.cpp.
 { return Vector4       (z, x, x, x); }
References x, and z.
zxxy()
Vector4 Vector3::zxxy () const
Definition at line 482 of file Vector3.cpp.
 { return Vector4       (z, x, x, y); }
References x, y, and z.
zxxz()
Vector4 Vector3::zxxz () const
Definition at line 509 of file Vector3.cpp.
 { return Vector4       (z, x, x, z); }
References x, and z.
zxy()
Vector3 Vector3::zxy () const
Definition at line 434 of file Vector3.cpp.
 { return Vector3       (z, x, y); }
References Vector3(), x, y, and z.
zxyx()
Vector4 Vector3::zxyx () const
Definition at line 464 of file Vector3.cpp.
 { return Vector4       (z, x, y, x); }
References x, y, and z.
zxyy()
Vector4 Vector3::zxyy () const
Definition at line 491 of file Vector3.cpp.
 { return Vector4       (z, x, y, y); }
References x, y, and z.
zxyz()
Vector4 Vector3::zxyz () const
Definition at line 518 of file Vector3.cpp.
 { return Vector4       (z, x, y, z); }
References x, y, and z.
zxz()
Vector3 Vector3::zxz () const
Definition at line 443 of file Vector3.cpp.
 { return Vector3       (z, x, z); }
References Vector3(), x, and z.
zxzx()
Vector4 Vector3::zxzx () const
Definition at line 473 of file Vector3.cpp.
 { return Vector4       (z, x, z, x); }
References x, and z.
zxzy()
Vector4 Vector3::zxzy () const
Definition at line 500 of file Vector3.cpp.
 { return Vector4       (z, x, z, y); }
References x, y, and z.
zxzz()
Vector4 Vector3::zxzz () const
Definition at line 527 of file Vector3.cpp.
 { return Vector4       (z, x, z, z); }
References x, and z.
zy()
Vector2 Vector3::zy () const
Definition at line 416 of file Vector3.cpp.
 { return Vector2       (z, y); }
References y, and z.
zyx()
Vector3 Vector3::zyx () const
Definition at line 428 of file Vector3.cpp.
 { return Vector3       (z, y, x); }
References Vector3(), x, y, and z.
zyxx()
Vector4 Vector3::zyxx () const
Definition at line 458 of file Vector3.cpp.
 { return Vector4       (z, y, x, x); }
References x, y, and z.
zyxy()
Vector4 Vector3::zyxy () const
Definition at line 485 of file Vector3.cpp.
 { return Vector4       (z, y, x, y); }
References x, y, and z.
zyxz()
Vector4 Vector3::zyxz () const
Definition at line 512 of file Vector3.cpp.
 { return Vector4       (z, y, x, z); }
References x, y, and z.
zyy()
Vector3 Vector3::zyy () const
Definition at line 437 of file Vector3.cpp.
 { return Vector3       (z, y, y); }
References Vector3(), y, and z.
zyyx()
Vector4 Vector3::zyyx () const
Definition at line 467 of file Vector3.cpp.
 { return Vector4       (z, y, y, x); }
References x, y, and z.
zyyy()
Vector4 Vector3::zyyy () const
Definition at line 494 of file Vector3.cpp.
 { return Vector4       (z, y, y, y); }
References y, and z.
zyyz()
Vector4 Vector3::zyyz () const
Definition at line 521 of file Vector3.cpp.
 { return Vector4       (z, y, y, z); }
References y, and z.
zyz()
Vector3 Vector3::zyz () const
Definition at line 446 of file Vector3.cpp.
 { return Vector3       (z, y, z); }
References Vector3(), y, and z.
zyzx()
Vector4 Vector3::zyzx () const
Definition at line 476 of file Vector3.cpp.
 { return Vector4       (z, y, z, x); }
References x, y, and z.
zyzy()
Vector4 Vector3::zyzy () const
Definition at line 503 of file Vector3.cpp.
 { return Vector4       (z, y, z, y); }
References y, and z.
zyzz()
Vector4 Vector3::zyzz () const
Definition at line 530 of file Vector3.cpp.
 { return Vector4       (z, y, z, z); }
References y, and z.
zz()
Vector2 Vector3::zz () const
Definition at line 419 of file Vector3.cpp.
 { return Vector2       (z, z); }
References z.
zzx()
Vector3 Vector3::zzx () const
Definition at line 431 of file Vector3.cpp.
 { return Vector3       (z, z, x); }
References Vector3(), x, and z.
zzxx()
Vector4 Vector3::zzxx () const
Definition at line 461 of file Vector3.cpp.
 { return Vector4       (z, z, x, x); }
References x, and z.
zzxy()
Vector4 Vector3::zzxy () const
Definition at line 488 of file Vector3.cpp.
 { return Vector4       (z, z, x, y); }
References x, y, and z.
zzxz()
Vector4 Vector3::zzxz () const
Definition at line 515 of file Vector3.cpp.
 { return Vector4       (z, z, x, z); }
References x, and z.
zzy()
Vector3 Vector3::zzy () const
Definition at line 440 of file Vector3.cpp.
 { return Vector3       (z, z, y); }
References Vector3(), y, and z.
zzyx()
Vector4 Vector3::zzyx () const
Definition at line 470 of file Vector3.cpp.
 { return Vector4       (z, z, y, x); }
References x, y, and z.
zzyy()
Vector4 Vector3::zzyy () const
Definition at line 497 of file Vector3.cpp.
 { return Vector4       (z, z, y, y); }
References y, and z.
zzyz()
Vector4 Vector3::zzyz () const
Definition at line 524 of file Vector3.cpp.
 { return Vector4       (z, z, y, z); }
References y, and z.
zzz()
Vector3 Vector3::zzz () const
Definition at line 449 of file Vector3.cpp.
 { return Vector3       (z, z, z); }
References Vector3(), and z.
zzzx()
Vector4 Vector3::zzzx () const
Definition at line 479 of file Vector3.cpp.
 { return Vector4       (z, z, z, x); }
References x, and z.
zzzy()
Vector4 Vector3::zzzy () const
Definition at line 506 of file Vector3.cpp.
 { return Vector4       (z, z, z, y); }
References y, and z.
zzzz()
Vector4 Vector3::zzzz () const
Definition at line 533 of file Vector3.cpp.
 { return Vector4       (z, z, z, z); }
References z.
Member Data Documentation
x
float G3D::Vector3::x
Definition at line 62 of file Vector3.h.
Referenced by Movement::MoveSplineInitArgs::_checkPathBounds(), RandomMovementGenerator< T >::_setRandomLocation(), G3D::abs(), G3D::all(), G3D::any(), G3D::AABox::area(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), Map::CanReachPositionAndGetValidCoords(), G3D::ceil(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), clamp(), G3D::CollisionDetection::closestPointToRectangle(), G3D::MeshAlg::computeBounds(), G3D::GImage::computeNormalMap(), Movement::MoveSpline::ComputePosition(), G3D::AABox::contains(), G3D::Box::contains(), G3D::AABox::corner(), cosHemiRandom(), cosPowHemiRandom(), cosSphereRandom(), cross(), G3D::ConvexPolygon::cut(), GameObjectModelOwnerImpl::DebugVisualizeCorner(), deserialize(), G3D::AnyVal::deserialize(), direction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), dot(), Spell::EffectCharge(), fastDirection(), G3D::findRayCapsuleIntersectionAux(), floor(), G3D::Color3::fromHSV(), G3D::Matrix3::fromUnitAxisAngle(), G3D::GCamera::frustum(), G3D::MeshAlg::generateGrid(), TransportMgr::GeneratePath(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), MotionMaster::GetDestination(), G3D::Plane::getEquation(), G3D::CoordinateFrame::getHeading(), WorldObject::GetHitSpherePointFor(), VMAP::WmoLiquid::GetLiquidHeight(), Map::GetObjectHitPos(), VMAP::VMapMgr2::GetObjectHitPos(), PathGenerator::getPathLength(), G3D::Capsule::getRandomSurfacePoint(), G3D::Cylinder::getRandomSurfacePoint(), getTangents(), GetVelocity(), G3D::CoordinateFrame::getXYZYPRRadians(), mmaps_commandscript::HandleMmapPathCommand(), PathGenerator::HaveTile(), G3D::iFloor(), VMAP::ModelPosition::init(), G3D::Box::init(), G3D::AABox::intersect(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay(), isFinite(), isNaN(), isZero(), Movement::MoveSplineInit::Launch(), MMAP::TerrainBuilder::loadVMap(), magnitude(), max(), min(), VMAP::ModelInstance::ModelInstance(), MotionMaster::MoveBackwards(), Movement::MoveSplineInit::MoveTo(), nonZero(), operator!=(), VMAP::WModelAreaCallback::operator()(), Movement::TransportPathTransform::operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), Movement::operator<<(), operator==(), Movement::operator>>(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), pow(), primaryAxis(), SmartScript::ProcessAction(), G3D::Cone::randomDirectionInCone(), G3D::AABox::randomInteriorPoint(), G3D::AABox::randomSurfacePoint(), G3D::Intersect::rayAABox(), readCamera(), round(), CharmInfo::SaveStayPosition(), G3D::Matrix4::scale(), serialize(), G3D::AABox::set(), G3D::Ray::set(), G3D::Vector4::set(), G3D::Matrix3::setColumn(), Movement::MoveSplineInit::SetFacing(), G3D::Matrix3::setRow(), G3D::sign(), squaredMagnitude(), WaypointMovementGenerator< Creature >::StartMove(), Movement::MoveSplineInit::Stop(), sum(), toAny(), G3D::Matrix3::toAxisAngle(), G3D::_internal::Welder::toGridCoords(), G3D::Color3::toHSV(), G3D::Plane::toString(), toString(), G3D::CoordinateFrame::toXML(), MMAP::TerrainBuilder::transform(), TranslateLocation(), G3D::truncate(), unitCross(), G3D::GCamera::unproject(), MotionTransport::Update(), Unit::UpdateSplinePosition(), G3D::UprightFrame::UprightFrame(), Vector3(), G3D::Vector4::Vector4(), G3D::Vector4int8::Vector4int8(), G3D::AABox::volume(), Movement::WriteLinearPath(), G3D::BinaryOutput::writeVector3(), xx(), xxx(), xxxx(), xxxy(), xxxz(), xxy(), xxyx(), xxyy(), xxyz(), xxz(), xxzx(), xxzy(), xxzz(), xy(), xyx(), xyxx(), xyxy(), xyxz(), xyy(), xyyx(), xyyy(), xyyz(), xyz(), xyzx(), xyzy(), xyzz(), xz(), xzx(), xzxx(), xzxy(), xzxz(), xzy(), xzyx(), xzyy(), xzyz(), xzz(), xzzx(), xzzy(), xzzz(), yx(), yxx(), yxxx(), yxxy(), yxxz(), yxy(), yxyx(), yxyy(), yxyz(), yxz(), yxzx(), yxzy(), yxzz(), yyx(), yyxx(), yyxy(), yyxz(), yyyx(), yyzx(), yzx(), yzxx(), yzxy(), yzxz(), yzyx(), yzzx(), zx(), zxx(), zxxx(), zxxy(), zxxz(), zxy(), zxyx(), zxyy(), zxyz(), zxz(), zxzx(), zxzy(), zxzz(), zyx(), zyxx(), zyxy(), zyxz(), zyyx(), zyzx(), zzx(), zzxx(), zzxy(), zzxz(), zzyx(), and zzzx().
y
float G3D::Vector3::y
Definition at line 62 of file Vector3.h.
Referenced by Movement::MoveSplineInitArgs::_checkPathBounds(), RandomMovementGenerator< T >::_setRandomLocation(), G3D::abs(), G3D::all(), G3D::any(), G3D::AABox::area(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), Map::CanReachPositionAndGetValidCoords(), G3D::ceil(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), clamp(), G3D::CollisionDetection::closestPointToRectangle(), G3D::MeshAlg::computeBounds(), G3D::GImage::computeNormalMap(), Movement::MoveSpline::ComputePosition(), G3D::AABox::contains(), G3D::Box::contains(), G3D::AABox::corner(), cosHemiRandom(), cosPowHemiRandom(), cosSphereRandom(), cross(), G3D::ConvexPolygon::cut(), GameObjectModelOwnerImpl::DebugVisualizeCorner(), deserialize(), G3D::AnyVal::deserialize(), direction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), dot(), Spell::EffectCharge(), fastDirection(), G3D::findRayCapsuleIntersectionAux(), floor(), G3D::Color3::fromHSV(), G3D::Matrix3::fromUnitAxisAngle(), G3D::GCamera::frustum(), G3D::MeshAlg::generateGrid(), TransportMgr::GeneratePath(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), MotionMaster::GetDestination(), G3D::Plane::getEquation(), WorldObject::GetHitSpherePointFor(), VMAP::WmoLiquid::GetLiquidHeight(), Map::GetObjectHitPos(), VMAP::VMapMgr2::GetObjectHitPos(), PathGenerator::getPathLength(), G3D::Capsule::getRandomSurfacePoint(), G3D::Cylinder::getRandomSurfacePoint(), GetVelocity(), G3D::CoordinateFrame::getXYZYPRRadians(), mmaps_commandscript::HandleMmapPathCommand(), PathGenerator::HaveTile(), G3D::iFloor(), VMAP::ModelPosition::init(), G3D::Box::init(), G3D::AABox::intersect(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay(), isFinite(), isNaN(), isZero(), Movement::MoveSplineInit::Launch(), MMAP::TerrainBuilder::loadVMap(), magnitude(), max(), min(), VMAP::ModelInstance::ModelInstance(), MotionMaster::MoveBackwards(), Movement::MoveSplineInit::MoveTo(), nonZero(), operator!=(), VMAP::WModelAreaCallback::operator()(), Movement::TransportPathTransform::operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), Movement::operator<<(), operator==(), Movement::operator>>(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), pow(), primaryAxis(), SmartScript::ProcessAction(), G3D::Cone::randomDirectionInCone(), G3D::AABox::randomInteriorPoint(), G3D::Capsule::randomInteriorPoint(), G3D::AABox::randomSurfacePoint(), G3D::Intersect::rayAABox(), readCamera(), round(), CharmInfo::SaveStayPosition(), G3D::Matrix4::scale(), serialize(), G3D::AABox::set(), G3D::Ray::set(), G3D::Vector4::set(), G3D::Matrix3::setColumn(), Movement::MoveSplineInit::SetFacing(), G3D::Matrix3::setRow(), G3D::sign(), squaredMagnitude(), WaypointMovementGenerator< Creature >::StartMove(), Movement::MoveSplineInit::Stop(), sum(), toAny(), G3D::Matrix3::toAxisAngle(), G3D::_internal::Welder::toGridCoords(), G3D::Color3::toHSV(), G3D::Plane::toString(), toString(), G3D::CoordinateFrame::toXML(), MMAP::TerrainBuilder::transform(), TranslateLocation(), G3D::truncate(), unitCross(), G3D::GCamera::unproject(), MotionTransport::Update(), Unit::UpdateSplinePosition(), G3D::UprightFrame::UprightFrame(), Vector3(), G3D::Vector4::Vector4(), G3D::Vector4int8::Vector4int8(), G3D::AABox::volume(), Movement::WriteLinearPath(), G3D::BinaryOutput::writeVector3(), xxxy(), xxy(), xxyx(), xxyy(), xxyz(), xxzy(), xy(), xyx(), xyxx(), xyxy(), xyxz(), xyy(), xyyx(), xyyy(), xyyz(), xyz(), xyzx(), xyzy(), xyzz(), xzxy(), xzy(), xzyx(), xzyy(), xzyz(), xzzy(), yx(), yxx(), yxxx(), yxxy(), yxxz(), yxy(), yxyx(), yxyy(), yxyz(), yxz(), yxzx(), yxzy(), yxzz(), yy(), yyx(), yyxx(), yyxy(), yyxz(), yyy(), yyyx(), yyyy(), yyyz(), yyz(), yyzx(), yyzy(), yyzz(), yz(), yzx(), yzxx(), yzxy(), yzxz(), yzy(), yzyx(), yzyy(), yzyz(), yzz(), yzzx(), yzzy(), yzzz(), zxxy(), zxy(), zxyx(), zxyy(), zxyz(), zxzy(), zy(), zyx(), zyxx(), zyxy(), zyxz(), zyy(), zyyx(), zyyy(), zyyz(), zyz(), zyzx(), zyzy(), zyzz(), zzxy(), zzy(), zzyx(), zzyy(), zzyz(), and zzzy().
z
float G3D::Vector3::z
Definition at line 62 of file Vector3.h.
Referenced by Movement::MoveSplineInitArgs::_checkPathBounds(), RandomMovementGenerator< T >::_setRandomLocation(), G3D::abs(), G3D::all(), G3D::any(), G3D::AABox::area(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), Map::CanReachPositionAndGetValidCoords(), G3D::ceil(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), clamp(), G3D::CollisionDetection::closestPointToRectangle(), G3D::MeshAlg::computeBounds(), Movement::MoveSpline::computeFallElevation(), G3D::GImage::computeNormalMap(), G3D::AABox::contains(), G3D::Box::contains(), G3D::AABox::corner(), cosHemiRandom(), cosPowHemiRandom(), cosSphereRandom(), cross(), G3D::ConvexPolygon::cut(), GameObjectModelOwnerImpl::DebugVisualizeCorner(), deserialize(), G3D::AnyVal::deserialize(), direction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), dot(), Spell::EffectCharge(), fastDirection(), G3D::findRayCapsuleIntersectionAux(), floor(), G3D::Color3::fromHSV(), G3D::Matrix3::fromUnitAxisAngle(), G3D::GCamera::frustum(), G3D::MeshAlg::generateGrid(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), MotionMaster::GetDestination(), G3D::Plane::getEquation(), G3D::CoordinateFrame::getHeading(), VMAP::StaticMapTree::getHeight(), DynamicMapTree::getHeight(), WorldObject::GetHitSpherePointFor(), VMAP::ModelInstance::GetLiquidLevel(), GameObjectModel::GetLiquidLevel(), VMAP::ModelInstance::GetLocationInfo(), GameObjectModel::GetLocationInfo(), Map::GetObjectHitPos(), VMAP::VMapMgr2::GetObjectHitPos(), PathGenerator::getPathLength(), G3D::Capsule::getRandomSurfacePoint(), G3D::Cylinder::getRandomSurfacePoint(), Map::GetTransportForPos(), G3D::CoordinateFrame::getXYZYPRRadians(), mmaps_commandscript::HandleMmapPathCommand(), PathGenerator::HaveTile(), G3D::iFloor(), VMAP::ModelPosition::init(), G3D::Box::init(), Movement::MoveSpline::init_spline(), G3D::AABox::intersect(), VMAP::ModelInstance::intersectPoint(), GameObjectModel::IntersectPoint(), isFinite(), isNaN(), isZero(), Movement::MoveSplineInit::Launch(), MMAP::TerrainBuilder::loadVMap(), magnitude(), max(), min(), VMAP::ModelInstance::ModelInstance(), MotionMaster::MoveBackwards(), Movement::MoveSplineInit::MoveTo(), nonZero(), operator!=(), VMAP::WModelAreaCallback::operator()(), Movement::FallInitializer::operator()(), Movement::TransportPathTransform::operator()(), Movement::HoverMovementTransform::operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), Movement::operator<<(), operator==(), Movement::operator>>(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), pow(), primaryAxis(), SmartScript::ProcessAction(), G3D::Cone::randomDirectionInCone(), G3D::AABox::randomInteriorPoint(), G3D::AABox::randomSurfacePoint(), G3D::Intersect::rayAABox(), readCamera(), round(), CharmInfo::SaveStayPosition(), G3D::Matrix4::scale(), serialize(), G3D::AABox::set(), G3D::Ray::set(), G3D::Vector4::set(), G3D::Matrix3::setColumn(), Movement::MoveSplineInit::SetFacing(), G3D::Matrix3::setRow(), G3D::sign(), squaredMagnitude(), WaypointMovementGenerator< Creature >::StartMove(), Movement::MoveSplineInit::Stop(), sum(), toAny(), G3D::Matrix3::toAxisAngle(), G3D::_internal::Welder::toGridCoords(), G3D::Color3::toHSV(), G3D::Plane::toString(), toString(), G3D::CoordinateFrame::toXML(), TranslateLocation(), G3D::truncate(), unitCross(), G3D::GCamera::unproject(), Unit::UpdateSplinePosition(), G3D::UprightFrame::UprightFrame(), Vector3(), G3D::Vector4::Vector4(), G3D::Vector4int8::Vector4int8(), G3D::AABox::volume(), Movement::WriteLinearPath(), G3D::BinaryOutput::writeVector3(), xxxz(), xxyz(), xxz(), xxzx(), xxzy(), xxzz(), xyxz(), xyyz(), xyz(), xyzx(), xyzy(), xyzz(), xz(), xzx(), xzxx(), xzxy(), xzxz(), xzy(), xzyx(), xzyy(), xzyz(), xzz(), xzzx(), xzzy(), xzzz(), yxxz(), yxyz(), yxz(), yxzx(), yxzy(), yxzz(), yyxz(), yyyz(), yyz(), yyzx(), yyzy(), yyzz(), yz(), yzx(), yzxx(), yzxy(), yzxz(), yzy(), yzyx(), yzyy(), yzyz(), yzz(), yzzx(), yzzy(), yzzz(), zx(), zxx(), zxxx(), zxxy(), zxxz(), zxy(), zxyx(), zxyy(), zxyz(), zxz(), zxzx(), zxzy(), zxzz(), zy(), zyx(), zyxx(), zyxy(), zyxz(), zyy(), zyyx(), zyyy(), zyyz(), zyz(), zyzx(), zyzy(), zyzz(), zz(), zzx(), zzxx(), zzxy(), zzxz(), zzy(), zzyx(), zzyy(), zzyz(), zzz(), zzzx(), zzzy(), and zzzz().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Vector3.h
deps/g3dlite/source/Vector3.cpp