Azerotcore-wotlk: boss_lady_deathwhisper::boss_lady_deathwhisperAI Struct Reference
boss_lady_deathwhisper::boss_lady_deathwhisperAI Struct Reference
Public Member Functions
boss_lady_deathwhisperAI (Creature *creature)
void Reset () override
void AttackStart (Unit *victim) override
void EnterCombat (Unit *who) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void JustDied (Unit *killer) override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void SummonWaveP1 ()
void SummonWaveP2 ()
void Summon (uint32 entry, const Position &pos)
void EmpowerCultist ()
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
bool _introDone
ObjectGuid _darnavanGUID
uint32 _waveCounter
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 244 of file boss_lady_deathwhisper.cpp.
Constructor & Destructor Documentation
boss_lady_deathwhisperAI()
boss_lady_deathwhisper::boss_lady_deathwhisperAI::boss_lady_deathwhisperAI (Creature * creature) inline
Definition at line 246 of file boss_lady_deathwhisper.cpp.
 : BossAI(creature, DATA_LADY_DEATHWHISPER), _introDone(false) { }
Member Function Documentation
AttackStart()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 262 of file boss_lady_deathwhisper.cpp.
         {
             if (victim && me->Attack(victim, true) && !(events.GetPhaseMask() & PHASE_ONE_MASK))
                 me->GetMotionMaster()->MoveChase(victim);
         }
References Unit::Attack(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveChase(), and PHASE_ONE_MASK.
DamageTaken()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 297 of file boss_lady_deathwhisper.cpp.
         {
             if (events.GetPhaseMask() & PHASE_ONE_MASK && damage >= me->GetPower(POWER_MANA))
             {
                 // reset threat
                 ThreatContainer::StorageType const& threatlist = me->getThreatMgr().getThreatList();
                 for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
                 {
                     Unit* unit = ObjectAccessor::GetUnit((*me), (*itr)->getUnitGuid());
                     if (unit && DoGetThreat(unit))
                         DoModifyThreatPercent(unit, -100);
                 }
                 Talk(SAY_PHASE_2);
                 Talk(EMOTE_PHASE_2);
                 DoStartMovement(me->GetVictim());
                 damage -= me->GetPower(POWER_MANA);
                 me->SetPower(POWER_MANA, 0);
                 me->RemoveAurasDueToSpell(SPELL_MANA_BARRIER);
                 events.SetPhase(PHASE_TWO);
                 events.ScheduleEvent(EVENT_SPELL_FROSTBOLT, urand(10000, 12000), 0, PHASE_TWO);
                 events.ScheduleEvent(EVENT_SPELL_FROSTBOLT_VOLLEY, urand(19000, 21000), 0, PHASE_TWO);
                 events.ScheduleEvent(EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE, urand(6000, 9000), 0, PHASE_TWO);
                 events.ScheduleEvent(EVENT_SPELL_SUMMON_SHADE, urand(12000, 15000), 0, PHASE_TWO);
                 if (IsHeroic())
                 {
                     me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, true);
                     me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
                     events.ScheduleEvent(EVENT_SUMMON_WAVE_P2, 45000, 0, PHASE_TWO);
                 }
             }
         }
References Unit::ApplySpellImmune(), ScriptedAI::DoGetThreat(), ScriptedAI::DoModifyThreatPercent(), ScriptedAI::DoStartMovement(), EMOTE_PHASE_2, EVENT_SPELL_FROSTBOLT, EVENT_SPELL_FROSTBOLT_VOLLEY, EVENT_SPELL_SUMMON_SHADE, EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE, EVENT_SUMMON_WAVE_P2, Unit::GetPower(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), IMMUNITY_EFFECT, IMMUNITY_STATE, ScriptedAI::IsHeroic(), ScriptedAI::me, PHASE_ONE_MASK, PHASE_TWO, POWER_MANA, Unit::RemoveAurasDueToSpell(), SAY_PHASE_2, Unit::SetPower(), SPELL_AURA_MOD_TAUNT, SPELL_EFFECT_ATTACK_ME, SPELL_MANA_BARRIER, CreatureAI::Talk(), and urand().
DoAction()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 549 of file boss_lady_deathwhisper.cpp.
         {
             if (action != ACTION_START_INTRO)
                 return;
             if (!_introDone && !me->IsInCombat())
             {
                 _introDone = true;
                 Talk(SAY_INTRO_1);
                 events.SetPhase(PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_2, 11000, 0, PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_3, 21000, 0, PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_4, 31500, 0, PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_5, 39500, 0, PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_6, 48500, 0, PHASE_INTRO);
                 events.ScheduleEvent(EVENT_INTRO_7, 58000, 0, PHASE_INTRO);
             }
         }
References _introDone, ACTION_START_INTRO, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_INTRO_5, EVENT_INTRO_6, EVENT_INTRO_7, Unit::IsInCombat(), ScriptedAI::me, PHASE_INTRO, SAY_INTRO_1, and CreatureAI::Talk().
EmpowerCultist()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist () inline
Definition at line 618 of file boss_lady_deathwhisper.cpp.
         {
             if (summons.empty())
                 return;
             std::list<Creature*> temp;
             for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 if (Creature* cre = ObjectAccessor::GetCreature(*me, *itr))
                     if (cre->IsAlive() && (cre->GetEntry() == NPC_CULT_FANATIC || cre->GetEntry() == NPC_CULT_ADHERENT))
                         temp.push_back(cre);
             // noone to empower
             if (temp.empty())
                 return;
             // select random cultist
             Creature* cultist = Acore::Containers::SelectRandomContainerElement(temp);
             if (!cultist)
                 return;
             if (RAND(0, 1))
                 me->CastSpell(cultist, SPELL_DARK_MARTYRDOM_T);
             else
             {
                 me->CastSpell(cultist, cultist->GetEntry() == NPC_CULT_FANATIC ? SPELL_DARK_TRANSFORMATION_T : SPELL_DARK_EMPOWERMENT_T, true);
                 Talk(uint8(cultist->GetEntry() == NPC_CULT_FANATIC ? SAY_DARK_TRANSFORMATION : SAY_DARK_EMPOWERMENT));
             }
         }
References SummonList::begin(), Unit::CastSpell(), SummonList::empty(), SummonList::end(), ObjectAccessor::GetCreature(), Object::GetEntry(), ScriptedAI::me, NPC_CULT_ADHERENT, NPC_CULT_FANATIC, RAND(), SAY_DARK_EMPOWERMENT, SAY_DARK_TRANSFORMATION, Acore::Containers::SelectRandomContainerElement(), SPELL_DARK_EMPOWERMENT_T, SPELL_DARK_MARTYRDOM_T, SPELL_DARK_TRANSFORMATION_T, BossAI::summons, and CreatureAI::Talk().
Referenced by UpdateAI().
EnterCombat()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 268 of file boss_lady_deathwhisper.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_LADY_DEATHWHISPER, who->ToPlayer()))
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             me->setActive(true);
             DoZoneInCombat();
             events.Reset();
             events.SetPhase(PHASE_ONE);
             events.ScheduleEvent(EVENT_BERSERK, 600000);
             events.ScheduleEvent(EVENT_SPELL_DEATH_AND_DECAY, 10000);
             if (GetDifficulty() != RAID_DIFFICULTY_10MAN_NORMAL)
                 events.ScheduleEvent(EVENT_SPELL_DOMINATE_MIND_25, 30000);
             events.ScheduleEvent(EVENT_SPELL_SHADOW_BOLT, 2000, 0, PHASE_ONE);
             events.ScheduleEvent(EVENT_SUMMON_WAVE_P1, 5000, 0, PHASE_ONE);
             events.ScheduleEvent(EVENT_EMPOWER_CULTIST, urand(20000, 30000), 0, PHASE_ONE);
             Talk(SAY_AGGRO);
             me->RemoveAurasDueToSpell(SPELL_SHADOW_CHANNELING);
             me->CastSpell(me, SPELL_MANA_BARRIER, true);
             instance->SetBossState(DATA_LADY_DEATHWHISPER, IN_PROGRESS);
         }
References Unit::CastSpell(), InstanceScript::CheckRequiredBosses(), DATA_LADY_DEATHWHISPER, InstanceScript::DoCastSpellOnPlayers(), CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), EVENT_BERSERK, EVENT_EMPOWER_CULTIST, EVENT_SPELL_DEATH_AND_DECAY, EVENT_SPELL_DOMINATE_MIND_25, EVENT_SPELL_SHADOW_BOLT, EVENT_SUMMON_WAVE_P1, ScriptedAI::GetDifficulty(), IN_PROGRESS, BossAI::instance, LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, PHASE_ONE, RAID_DIFFICULTY_10MAN_NORMAL, Unit::RemoveAurasDueToSpell(), SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_MANA_BARRIER, SPELL_SHADOW_CHANNELING, CreatureAI::Talk(), Object::ToPlayer(), and urand().
JustDied()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 498 of file boss_lady_deathwhisper.cpp.
         {
             Talk(SAY_DEATH);
             std::set<uint32> livingAddEntries;
             // Full House achievement
             for (SummonList::iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 if (Unit* unit = ObjectAccessor::GetUnit(*me, *itr))
                     if (unit->IsAlive() && unit->GetEntry() != NPC_VENGEFUL_SHADE)
                         livingAddEntries.insert(unit->GetEntry());
             if (livingAddEntries.size() >= 5)
                 instance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_FULL_HOUSE, 0, me);
             if (Creature* darnavan = ObjectAccessor::GetCreature(*me, _darnavanGUID))
             {
                 if (darnavan->IsAlive())
                 {
                     darnavan->RemoveAllAuras();
                     darnavan->SetFaction(FACTION_FRIENDLY);
                     darnavan->DeleteThreatList();
                     darnavan->CombatStop(true);
                     darnavan->GetMotionMaster()->MoveIdle();
                     darnavan->StopMoving();
                     darnavan->SetReactState(REACT_PASSIVE);
                     darnavan->m_Events.AddEvent(new DaranavanMoveEvent(*darnavan), darnavan->m_Events.CalculateTime(10000));
                     darnavan->AI()->Talk(SAY_DARNAVAN_RESCUED);
                     if (Player* owner = killer->GetCharmerOrOwnerPlayerOrPlayerItself())
                     {
                         if (Group* group = owner->GetGroup())
{
                             for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
                                 if (Player* member = itr->GetSource())
                                     if (member->IsInMap(owner))
                                         member->KilledMonsterCredit(NPC_DARNAVAN_CREDIT);
                         }
                         else
                             owner->KilledMonsterCredit(NPC_DARNAVAN_CREDIT);
                     }
                 }
             }
             _JustDied();
         }
References _darnavanGUID, BossAI::_JustDied(), ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SummonList::begin(), InstanceScript::DoUpdateAchievementCriteria(), SummonList::end(), FACTION_FRIENDLY, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), ObjectAccessor::GetCreature(), ObjectAccessor::GetUnit(), BossAI::instance, ScriptedAI::me, GroupReference::next(), NPC_DARNAVAN_CREDIT, NPC_VENGEFUL_SHADE, REACT_PASSIVE, SAY_DARNAVAN_RESCUED, SAY_DEATH, SPELL_FULL_HOUSE, BossAI::summons, and CreatureAI::Talk().
JustSummoned()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 463 of file boss_lady_deathwhisper.cpp.
         {
             if (summon->GetEntry() == NPC_DARNAVAN)
                 _darnavanGUID = summon->GetGUID();
             else
                 summons.Summon(summon);
             Unit* target = nullptr;
             if (summon->GetEntry() == NPC_VENGEFUL_SHADE)
             {
                 float minrange = 250.0f;
                 Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                 for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                     if (Player* p = itr->GetSource())
                         if (p != me->GetVictim() && summon->GetExactDist(p) < minrange && me->CanCreatureAttack(p) && me->_CanDetectFeignDeathOf(p))
{
                             target = p;
                             minrange = summon->GetExactDist(p);
                         }
                 summon->ToTempSummon()->DespawnOrUnsummon(30000);
             }
             else
             {
                 target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true);
             }
             summon->AI()->AttackStart(target);
         }
References Creature::_CanDetectFeignDeathOf(), _darnavanGUID, Creature::AI(), UnitAI::AttackStart(), MapRefMgr::begin(), Creature::CanCreatureAttack(), Creature::DespawnOrUnsummon(), MapRefMgr::end(), Object::GetEntry(), Position::GetExactDist(), Object::GetGUID(), WorldObject::GetMap(), Map::GetPlayers(), Unit::GetVictim(), ScriptedAI::me, NPC_DARNAVAN, NPC_VENGEFUL_SHADE, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SummonList::Summon(), BossAI::summons, and Unit::ToTempSummon().
KilledUnit()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 543 of file boss_lady_deathwhisper.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 248 of file boss_lady_deathwhisper.cpp.
         {
             if (Creature* darnavan = ObjectAccessor::GetCreature(*me, _darnavanGUID))
                 darnavan->DespawnOrUnsummon();
             _darnavanGUID.Clear();
             _waveCounter = 0;
             _Reset();
             me->SetPower(POWER_MANA, me->GetMaxPower(POWER_MANA));
             events.SetPhase(PHASE_ONE);
             me->CastSpell(me, SPELL_SHADOW_CHANNELING, false);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, false);
             me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, false);
         }
References _darnavanGUID, BossAI::_Reset(), _waveCounter, Unit::ApplySpellImmune(), Unit::CastSpell(), ObjectGuid::Clear(), ObjectAccessor::GetCreature(), Unit::GetMaxPower(), IMMUNITY_EFFECT, IMMUNITY_STATE, ScriptedAI::me, PHASE_ONE, POWER_MANA, Unit::SetPower(), SPELL_AURA_MOD_TAUNT, SPELL_EFFECT_ATTACK_ME, and SPELL_SHADOW_CHANNELING.
SpellHitTarget()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 647 of file boss_lady_deathwhisper.cpp.
         {
             if (spell->Id == SPELL_DOMINATE_MIND_25)
             {
                 const int32 val = 100;
                 target->CastCustomSpell(target, 73261, &val, nullptr, nullptr, true); // scale aura, +100% size
             }
         }
References Unit::CastCustomSpell(), SpellInfo::Id, and SPELL_DOMINATE_MIND_25.
Summon()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::Summon (uint32 entry, const Position & pos) inline
Definition at line 608 of file boss_lady_deathwhisper.cpp.
         {
             if (me->SummonCreature(entry, pos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 10000))
                 if (TempSummon* trigger = me->SummonCreature(WORLD_TRIGGER, pos, TEMPSUMMON_TIMED_DESPAWN, 2000))
                 {
                     trigger->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                     trigger->CastSpell(trigger, SPELL_TELEPORT_VISUAL, true);
                 }
         }
References ScriptedAI::me, SPELL_TELEPORT_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and WORLD_TRIGGER.
Referenced by SummonWaveP1(), and SummonWaveP2().
SummonedCreatureDespawn()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 493 of file boss_lady_deathwhisper.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and BossAI::summons.
SummonWaveP1()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1 () inline
Definition at line 568 of file boss_lady_deathwhisper.cpp.
         {
             uint8 addIndex = _waveCounter & 1;
             uint8 addIndexOther = uint8(addIndex ^ 1);
             // Summon first add, replace it with Darnavan if weekly quest is active
             if (_waveCounter || instance->GetData(DATA_WEEKLY_QUEST_ID) != QUEST_DEPROGRAMMING_10)
                 Summon(SummonEntries[addIndex], SummonPositions[addIndex * 3]);
             else
                 Summon(NPC_DARNAVAN, SummonPositions[addIndex * 3]);
             Summon(SummonEntries[addIndexOther], SummonPositions[addIndex * 3 + 1]);
             Summon(SummonEntries[addIndex], SummonPositions[addIndex * 3 + 2]);
             if (Is25ManRaid())
             {
                 Summon(SummonEntries[addIndexOther], SummonPositions[addIndexOther * 3]);
                 Summon(SummonEntries[addIndex], SummonPositions[addIndexOther * 3 + 1]);
                 Summon(SummonEntries[addIndexOther], SummonPositions[addIndexOther * 3 + 2]);
                 Summon(SummonEntries[urand(0, 1)], SummonPositions[6]);
             }
             ++_waveCounter;
         }
References _waveCounter, DATA_WEEKLY_QUEST_ID, ZoneScript::GetData(), BossAI::instance, ScriptedAI::Is25ManRaid(), NPC_DARNAVAN, QUEST_DEPROGRAMMING_10, Summon(), SummonEntries, SummonPositions, and urand().
Referenced by UpdateAI().
SummonWaveP2()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP2 () inline
Definition at line 592 of file boss_lady_deathwhisper.cpp.
         {
             if (Is25ManRaid())
             {
                 uint8 addIndex = _waveCounter & 1;
                 Summon(SummonEntries[addIndex], SummonPositions[addIndex * 3]);
                 Summon(SummonEntries[addIndex ^ 1], SummonPositions[addIndex * 3 + 1]);
                 Summon(SummonEntries[addIndex], SummonPositions[addIndex * 3 + 2]);
             }
             else
                 Summon(SummonEntries[urand(0, 1)], SummonPositions[6]);
             ++_waveCounter;
         }
References _waveCounter, ScriptedAI::Is25ManRaid(), Summon(), SummonEntries, SummonPositions, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 331 of file boss_lady_deathwhisper.cpp.
         {
             if ((!UpdateVictim() && !(events.GetPhaseMask() & PHASE_INTRO_MASK)) || !CheckInRoom())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING) && !(events.GetPhaseMask() & PHASE_INTRO_MASK))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_INTRO_2:
                     Talk(SAY_INTRO_2);
                     break;
                 case EVENT_INTRO_3:
                     Talk(SAY_INTRO_3);
                     break;
                 case EVENT_INTRO_4:
                     Talk(SAY_INTRO_4);
                     break;
                 case EVENT_INTRO_5:
                     Talk(SAY_INTRO_5);
                     break;
                 case EVENT_INTRO_6:
                     Talk(SAY_INTRO_6);
                     break;
                 case EVENT_INTRO_7:
                     Talk(SAY_INTRO_7);
                     break;
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     Talk(SAY_BERSERK);
                     break;
                 case EVENT_SPELL_DEATH_AND_DECAY:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, SPELL_DEATH_AND_DECAY, false);
                     events.RepeatEvent(urand(22000, 30000));
                     break;
                 case EVENT_SPELL_DOMINATE_MIND_25:
                     {
                         Talk(SAY_DOMINATE_MIND);
                         std::vector<Player*> validPlayers;
                         Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                             if (Player* plr = itr->GetSource())
                                 if (plr->IsAlive() && !plr->IsGameMaster() && plr->GetExactDist2dSq(me) < (150.0f * 150.0f))
                                     if (!me->GetVictim() || me->GetVictim()->GetGUID() != plr->GetGUID())
{
                                         // shouldn't be casted on any victim of summoned mobs
                                         bool valid = true;
                                         for (ObjectGuid const& guid : summons)
                                             if (Creature* c = ObjectAccessor::GetCreature(*me, guid))
                                                 if (c->IsAlive() && c->GetVictim() && c->GetVictim()->GetGUID() == plr->GetGUID())
{
                                                     valid = false;
                                                     break;
                                                 }
                                         if (valid)
                                             validPlayers.push_back(plr);
                                     }
                         std::vector<Player*>::iterator begin = validPlayers.begin(), end = validPlayers.end();
                         std::random_device rd;
                         std::shuffle(begin, end, std::default_random_engine{rd()});
                         for (uint8 i = 0; i < RAID_MODE<uint8>(0, 1, 1, 3) && i < validPlayers.size(); i++)
{
                             Unit* target = validPlayers[i];
                             me->CastSpell(target, SPELL_DOMINATE_MIND_25, true);
                         }
                         events.RepeatEvent(urand(40000, 45000));
                     }
                     break;
                 case EVENT_SPELL_SHADOW_BOLT:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, SPELL_SHADOW_BOLT, false);
                     events.RepeatEvent(2100);
                     break;
                 case EVENT_SUMMON_WAVE_P1:
                     SummonWaveP1();
                     events.RepeatEvent(IsHeroic() ? 45000 : 60000);
                     break;
                 case EVENT_EMPOWER_CULTIST:
                     EmpowerCultist();
                     events.RepeatEvent(urand(18000, 25000));
                     break;
                 case EVENT_SPELL_FROSTBOLT:
                     me->CastSpell(me->GetVictim(), SPELL_FROSTBOLT, false);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_SPELL_FROSTBOLT_VOLLEY:
                     me->CastSpell((Unit*)nullptr, SPELL_FROSTBOLT_VOLLEY, false);
                     events.RepeatEvent(urand(13000, 15000));
                     break;
                 case EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE:
                     me->CastSpell(me->GetVictim(), SPELL_TOUCH_OF_INSIGNIFICANCE, false);
                     events.RepeatEvent(urand(6000, 9000));
                     break;
                 case EVENT_SUMMON_WAVE_P2:
                     SummonWaveP2();
                     events.RepeatEvent(45000);
                     break;
                 case EVENT_SPELL_SUMMON_SHADE:
                     {
                         uint8 count = 1;
                         if (GetDifficulty() == RAID_DIFFICULTY_25MAN_NORMAL)
                             count = 2;
                         else if (GetDifficulty() == RAID_DIFFICULTY_25MAN_HEROIC)
                             count = 3;
                         std::list<Unit*> targets;
                         SelectTargetList(targets, NonTankTargetSelector(me, true), count, SELECT_TARGET_RANDOM);
                         if (!targets.empty())
                             for (std::list<Unit*>::iterator itr = targets.begin(); itr != targets.end(); ++itr)
                                 me->CastSpell(*itr, SPELL_SUMMON_SHADE, true);
                     }
                     events.RepeatEvent(12000);
                     break;
             }
             if (me->HasAura(SPELL_MANA_BARRIER))
                 return;
             DoMeleeAttackIfReady();
         }
References MapRefMgr::begin(), Unit::CastSpell(), BossAI::CheckInRoom(), UnitAI::DoMeleeAttackIfReady(), EmpowerCultist(), MapRefMgr::end(), EVENT_BERSERK, EVENT_EMPOWER_CULTIST, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_INTRO_5, EVENT_INTRO_6, EVENT_INTRO_7, EVENT_SPELL_DEATH_AND_DECAY, EVENT_SPELL_DOMINATE_MIND_25, EVENT_SPELL_FROSTBOLT, EVENT_SPELL_FROSTBOLT_VOLLEY, EVENT_SPELL_SHADOW_BOLT, EVENT_SPELL_SUMMON_SHADE, EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE, EVENT_SUMMON_WAVE_P1, EVENT_SUMMON_WAVE_P2, ObjectAccessor::GetCreature(), ScriptedAI::GetDifficulty(), Object::GetGUID(), WorldObject::GetMap(), Map::GetPlayers(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), ScriptedAI::IsHeroic(), ScriptedAI::me, PHASE_INTRO_MASK, RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, SAY_BERSERK, SAY_DOMINATE_MIND, SAY_INTRO_2, SAY_INTRO_3, SAY_INTRO_4, SAY_INTRO_5, SAY_INTRO_6, SAY_INTRO_7, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UnitAI::SelectTargetList(), SPELL_BERSERK, SPELL_DEATH_AND_DECAY, SPELL_DOMINATE_MIND_25, SPELL_FROSTBOLT, SPELL_FROSTBOLT_VOLLEY, SPELL_MANA_BARRIER, SPELL_SHADOW_BOLT, SPELL_SUMMON_SHADE, SPELL_TOUCH_OF_INSIGNIFICANCE, BossAI::summons, SummonWaveP1(), SummonWaveP2(), CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_darnavanGUID
ObjectGuid boss_lady_deathwhisper::boss_lady_deathwhisperAI::_darnavanGUID private
Definition at line 658 of file boss_lady_deathwhisper.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
_introDone
bool boss_lady_deathwhisper::boss_lady_deathwhisperAI::_introDone private
Definition at line 657 of file boss_lady_deathwhisper.cpp.
Referenced by DoAction().
_waveCounter
uint32 boss_lady_deathwhisper::boss_lady_deathwhisperAI::_waveCounter private
Definition at line 659 of file boss_lady_deathwhisper.cpp.
Referenced by Reset(), SummonWaveP1(), and SummonWaveP2().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp