Azerotcore-wotlk: src/server/game/Handlers/LFGHandler.cpp File Reference
LFGHandler.cpp File Reference
#include "Group.h"
#include "LFGMgr.h"
#include "ObjectMgr.h"
#include "Opcodes.h"
#include "Player.h"
#include "WorldPacket.h"
#include "WorldSession.h"
Functions
void BuildPlayerLockDungeonBlock (WorldPacket &data, lfg::LfgLockMap const &lock)
void BuildPartyLockDungeonBlock (WorldPacket &data, const lfg::LfgLockPartyMap &lockMap)
Function Documentation
BuildPartyLockDungeonBlock()
void BuildPartyLockDungeonBlock (WorldPacket & data, const lfg::LfgLockPartyMap & lockMap)
Definition at line 36 of file LFGHandler.cpp.
 {
     data << uint8(lockMap.size());
     for (lfg::LfgLockPartyMap::const_iterator it = lockMap.begin(); it != lockMap.end(); ++it)
     {
         data << it->first;                                 // Player guid
         BuildPlayerLockDungeonBlock(data, it->second);
     }
 }
References BuildPlayerLockDungeonBlock().
Referenced by WorldSession::HandleLfgPartyLockInfoRequestOpcode(), and WorldSession::SendLfgJoinResult().
BuildPlayerLockDungeonBlock()
void BuildPlayerLockDungeonBlock (WorldPacket & data, lfg::LfgLockMap const & lock)
Definition at line 26 of file LFGHandler.cpp.
 {
     data << uint32(lock.size());                           // Size of lock dungeons
     for (lfg::LfgLockMap::const_iterator it = lock.begin(); it != lock.end(); ++it)
     {
         data << uint32(it->first);                         // Dungeon entry (id + type)
         data << uint32(it->second);                        // Lock status
     }
 }
Referenced by BuildPartyLockDungeonBlock(), and WorldSession::HandleLfgPlayerLockInfoRequestOpcode().