Azerotcore-wotlk: Acore::Hyperlinks::LinkTags::enchant Struct Reference
Acore::Hyperlinks::LinkTags::enchant Struct Reference
#include <Hyperlinks.h>
Public Types
using value_type = SpellInfo const *
Static Public Member Functions
static constexpr std::string_view tag ()
static bool StoreTo (SpellInfo const *&val, std::string_view data)
Detailed Description
Definition at line 168 of file Hyperlinks.h.
Member Typedef Documentation
value_type
using Acore::Hyperlinks::LinkTags::enchant::value_type = SpellInfo const*
Definition at line 170 of file Hyperlinks.h.
Member Function Documentation
StoreTo()
bool Acore::Hyperlinks::LinkTags::enchant::StoreTo (SpellInfo const *& val, std::string_view data) static
Definition at line 93 of file HyperlinkTags.cpp.
 {
     HyperlinkDataTokenizer t(text);
     uint32 spellId;
     if (!(t.TryConsumeTo(spellId) && t.IsEmpty()))
         return false;
     return (val = sSpellMgr->GetSpellInfo(spellId)) && val->HasAttribute(SPELL_ATTR0_IS_TRADESKILL);
 }
References SpellInfo::HasAttribute(), HyperlinkDataTokenizer::IsEmpty(), SPELL_ATTR0_IS_TRADESKILL, sSpellMgr, and HyperlinkDataTokenizer::TryConsumeTo().
tag()
static constexpr std::string_view Acore::Hyperlinks::LinkTags::enchant::tag () inline static constexpr
Definition at line 171 of file Hyperlinks.h.
 { return "enchant"; }
The documentation for this struct was generated from the following files:
src/server/game/Chat/Hyperlinks.h
src/server/game/Chat/HyperlinkTags.cpp