Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/hook.h File Reference
hook.h File Reference
#include "jemalloc/internal/tsd.h"
Classes
struct hooks_s
struct hook_ralloc_args_s
Macros
#define HOOK_MAX 4
Typedefs
typedef enum hook_alloc_e hook_alloc_t
typedef enum hook_dalloc_e hook_dalloc_t
typedef enum hook_expand_e hook_expand_t
typedef void(* hook_alloc) (void *extra, hook_alloc_t type, void *result, uintptr_t result_raw, uintptr_t args_raw[3])
typedef void(* hook_dalloc) (void *extra, hook_dalloc_t type, void *address, uintptr_t args_raw[3])
typedef void(* hook_expand) (void *extra, hook_expand_t type, void *address, size_t old_usize, size_t new_usize, uintptr_t result_raw, uintptr_t args_raw[4])
typedef struct hooks_s hooks_t
typedef struct hook_ralloc_args_s hook_ralloc_args_t
Enumerations
enum hook_alloc_e {
hook_alloc_malloc , hook_alloc_posix_memalign , hook_alloc_aligned_alloc , hook_alloc_calloc ,
hook_alloc_memalign , hook_alloc_valloc , hook_alloc_mallocx , hook_alloc_realloc ,
hook_alloc_rallocx
}
enum hook_dalloc_e {
hook_dalloc_free , hook_dalloc_dallocx , hook_dalloc_sdallocx , hook_dalloc_realloc ,
hook_dalloc_rallocx
}
enum hook_expand_e { hook_expand_realloc , hook_expand_rallocx , hook_expand_xallocx }
Functions
bool hook_boot ()
void * hook_install (tsdn_t *tsdn, hooks_t *hooks)
void hook_remove (tsdn_t *tsdn, void *opaque)
void hook_invoke_alloc (hook_alloc_t type, void *result, uintptr_t result_raw, uintptr_t args_raw[3])
void hook_invoke_dalloc (hook_dalloc_t type, void *address, uintptr_t args_raw[3])
void hook_invoke_expand (hook_expand_t type, void *address, size_t old_usize, size_t new_usize, uintptr_t result_raw, uintptr_t args_raw[4])
Macro Definition Documentation
HOOK_MAX
#define HOOK_MAX 4
Definition at line 49 of file hook.h.
Typedef Documentation
hook_alloc
typedef void(* hook_alloc) (void *extra, hook_alloc_t type, void *result, uintptr_t result_raw, uintptr_t args_raw[3])
Definition at line 92 of file hook.h.
hook_alloc_t
typedef enum hook_alloc_e hook_alloc_t
Definition at line 1 of file hook.h.
hook_dalloc
typedef void(* hook_dalloc) (void *extra, hook_dalloc_t type, void *address, uintptr_t args_raw[3])
Definition at line 96 of file hook.h.
hook_dalloc_t
typedef enum hook_dalloc_e hook_dalloc_t
Definition at line 1 of file hook.h.
hook_expand
typedef void(* hook_expand) (void *extra, hook_expand_t type, void *address, size_t old_usize, size_t new_usize, uintptr_t result_raw, uintptr_t args_raw[4])
Definition at line 99 of file hook.h.
hook_expand_t
typedef enum hook_expand_e hook_expand_t
Definition at line 1 of file hook.h.
hook_ralloc_args_t
typedef struct hook_ralloc_args_s hook_ralloc_args_t
Definition at line 99 of file hook.h.
hooks_t
typedef struct hooks_s hooks_t
Definition at line 99 of file hook.h.
Enumeration Type Documentation
hook_alloc_e
enum hook_alloc_e
Enumerator
hook_alloc_malloc
hook_alloc_posix_memalign
hook_alloc_aligned_alloc
hook_alloc_calloc
hook_alloc_memalign
hook_alloc_valloc
hook_alloc_mallocx
hook_alloc_realloc
hook_alloc_rallocx
Definition at line 51 of file hook.h.
                   {
     hook_alloc_malloc,
     hook_alloc_posix_memalign,
     hook_alloc_aligned_alloc,
     hook_alloc_calloc,
     hook_alloc_memalign,
     hook_alloc_valloc,
     hook_alloc_mallocx,
     /* The reallocating functions have both alloc and dalloc variants */
     hook_alloc_realloc,
     hook_alloc_rallocx,
 };
hook_dalloc_e
enum hook_dalloc_e
Enumerator
hook_dalloc_free
hook_dalloc_dallocx
hook_dalloc_sdallocx
hook_dalloc_realloc
hook_dalloc_rallocx
Definition at line 70 of file hook.h.
                    {
     hook_dalloc_free,
     hook_dalloc_dallocx,
     hook_dalloc_sdallocx,
     /*
      * The dalloc halves of reallocation (not called if in-place expansion
      * happens).
      */
     hook_dalloc_realloc,
     hook_dalloc_rallocx,
 };
hook_expand_e
enum hook_expand_e
Enumerator
hook_expand_realloc
hook_expand_rallocx
hook_expand_xallocx
Definition at line 85 of file hook.h.
                    {
     hook_expand_realloc,
     hook_expand_rallocx,
     hook_expand_xallocx,
 };
Function Documentation
hook_boot()
bool hook_boot ()
Referenced by malloc_init_hard_a0_locked().
hook_install()
void* hook_install (tsdn_t * tsdn, hooks_t * hooks)
Definition at line 48 of file hook.c.
{
     malloc_mutex_lock(tsdn, &hooks_mu);
     void *ret = hook_install_locked(to_install);
     if (ret != NULL) {
         tsd_global_slow_inc(tsdn);
     }
     malloc_mutex_unlock(tsdn, &hooks_mu);
     return ret;
 }
References hook_install_locked(), malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ret, and tsd_global_slow_inc.
hook_invoke_alloc()
void hook_invoke_alloc (hook_alloc_t type, void * result, uintptr_t result_raw, uintptr_t args_raw[3])
Definition at line 154 of file hook.c.
{
     HOOK_PROLOGUE
     hooks_internal_t hook;
     FOR_EACH_HOOK_BEGIN(&hook)
         hook_alloc h = hook.hooks.alloc_hook;
         if (h != NULL) {
             h(hook.hooks.extra, type, result, result_raw, args_raw);
         }
     FOR_EACH_HOOK_END
     HOOK_EPILOGUE
 }
References FOR_EACH_HOOK_BEGIN, FOR_EACH_HOOK_END, HOOK_EPILOGUE, HOOK_PROLOGUE, and NULL.
hook_invoke_dalloc()
void hook_invoke_dalloc (hook_dalloc_t type, void * address, uintptr_t args_raw[3])
Definition at line 170 of file hook.c.
{
     HOOK_PROLOGUE
     hooks_internal_t hook;
     FOR_EACH_HOOK_BEGIN(&hook)
         hook_dalloc h = hook.hooks.dalloc_hook;
         if (h != NULL) {
             h(hook.hooks.extra, type, address, args_raw);
         }
     FOR_EACH_HOOK_END
     HOOK_EPILOGUE
 }
References FOR_EACH_HOOK_BEGIN, FOR_EACH_HOOK_END, HOOK_EPILOGUE, HOOK_PROLOGUE, and NULL.
hook_invoke_expand()
void hook_invoke_expand (hook_expand_t type, void * address, size_t old_usize, size_t new_usize, uintptr_t result_raw, uintptr_t args_raw[4])
Definition at line 183 of file hook.c.
{
     HOOK_PROLOGUE
     hooks_internal_t hook;
     FOR_EACH_HOOK_BEGIN(&hook)
         hook_expand h = hook.hooks.expand_hook;
         if (h != NULL) {
             h(hook.hooks.extra, type, address, old_usize, new_usize,
                 result_raw, args_raw);
         }
     FOR_EACH_HOOK_END
     HOOK_EPILOGUE
 }
References FOR_EACH_HOOK_BEGIN, FOR_EACH_HOOK_END, HOOK_EPILOGUE, HOOK_PROLOGUE, and NULL.
hook_remove()
void hook_remove (tsdn_t * tsdn, void * opaque)
Definition at line 73 of file hook.c.
{
     if (config_debug) {
         char *hooks_begin = (char *)&hooks[0];
         char *hooks_end = (char *)&hooks[HOOK_MAX];
         char *hook = (char *)opaque;
         assert(hooks_begin <= hook && hook < hooks_end
             && (hook - hooks_begin) % sizeof(seq_hooks_t) == 0);
     }
     malloc_mutex_lock(tsdn, &hooks_mu);
     hook_remove_locked((seq_hooks_t *)opaque);
     tsd_global_slow_dec(tsdn);
     malloc_mutex_unlock(tsdn, &hooks_mu);
 }
References assert(), config_debug, HOOK_MAX, hook_remove_locked(), malloc_mutex_lock(), malloc_mutex_unlock(), and tsd_global_slow_dec.