Azerotcore-wotlk: deps/mysqllite/cmake/stack_direction.c File Reference
stack_direction.c File Reference
Functions
int f (int *a)
int main ()
Variables
volatile int(* ptr_f)(int *) = f
Function Documentation
f()
int f (int * a)
Definition at line 17 of file stack_direction.c.
 {
   int b;
   return(&b > a)?1:0;
 }
References mpq::a, and b.
Referenced by G3D::FileSystem::_exists(), G3D::FileSystem::_isZipfile(), Player::_SaveCharacter(), Unit::AddExtraUnitMovementFlag(), WorldObject::AddToNotify(), Unit::AddUnitMovementFlag(), Unit::AddUnitState(), G3D::applyFilter(), ContinentBuilder::Build(), G3D::byteSize(), BZ2_bzReadOpen(), BZ2_bzWriteOpen(), G3D::FileSystem::cacheLifetime(), Unit::ClearUnitState(), G3D::CollisionDetection::collisionTimeForMovingPointFixedBox(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedBox(), G3D::TextOutput::commit(), G3D::MeshAlg::computeAdjacency(), G3D::MeshAlg::computeFaceNormals(), G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::FileSystem::Dir::contains(), G3D::CoordinateFrame::CoordinateFrame(), G3D::ConvexPolyhedron::cut(), DBC::DBC(), G3D::MeshAlg::debugCheckConsistency(), G3D::deserialize(), G3D::Matrix3::diffOneNorm(), detail::do_write(), G3D::FileSystem::exists(), G3D::FileSystem::fclose(), G3D::findLastSlash(), G3D::findSlash(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidBox(), floatToRawIntBits(), G3D::FileSystem::fopen(), detail::for_each(), detail::for_each_codepoint(), formatter< std::chrono::duration< Rep, Period >, Char >::format(), value< Context >::format_custom_arg(), fprintf(), G3D::GLight::frame(), G3D::Color3::fromHSV(), G3D::GCamera::frustum(), gen_bitlen(), G3D::GCamera::getClipPlanes(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Box::getFaceCorners(), G3D::GCamera::getProjectUnitMatrix(), G3D::ConvexPolyhedron::getVolume(), Movement::MoveSplineFlag::hasAllFlags(), Player::HasAtLoginFlag(), Unit::HasExtraUnitMovementFlag(), Movement::MoveSplineFlag::hasFlag(), Unit::HasUnitMovementFlag(), Unit::HasUnitState(), G3D::MeshAlg::identifyBackfaces(), G3D::MeshAlg::Vertex::inFace(), G3D::MeshAlg::Edge::inFace(), G3D::System::init(), MMAP::MMapFactory::InitializeDisabledMaps(), G3D::Triangle::intersect(), VMAP::IntersectTriangle(), QueryCallback::InvokeIfReady(), G3D::iRound(), G3D::iSign(), WorldObject::isNeedNotify(), G3D::FilePath::isRoot(), G3D::isZipfile(), G3D::Matrix3::l1Norm(), G3D::lerp(), G3D::Matrix3::lInfNorm(), ListFlags(), DBCFileLoader::Load(), LoadDBC(), LoadTile(), G3D::FilePath::makeLegalFilename(), malloc_tsd_cleanup_register(), malloc_vsnprintf(), Movement::MoveSplineFlag::MoveSplineFlag(), detail::multiply(), my_fileno(), myfeof(), WorldObject::NotifyExecuted(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_align(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_dynamic_precision(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_dynamic_width(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_fill(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_precision(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_width(), DBCFile::open(), Model::open(), WMORoot::open(), WMOGroup::open(), Movement::MoveSplineFlag::operator&(), Movement::MoveSplineFlag::operator&=(), G3D::AABox::operator*(), G3D::Box::operator*(), G3D::Matrix2::operator*(), G3D::PhysicsFrame::operator*(), operator*(), G3D::Vector3::operator*(), G3D::PhysicsFrame::operator*=(), G3D::PhysicsFrame::operator+(), G3D::PhysicsFrame::operator+=(), G3D::AABox::operator/(), G3D::Matrix2::operator/(), Movement::MoveSplineFlag::operator|(), Movement::MoveSplineFlag::operator|=(), G3D::FilePath::parse(), parse_format_specs(), G3D::parseFilename(), pcmp(), print(), detail::print(), G3D::readWholeFile(), Unit::RemoveExtraUnitMovementFlag(), WorldObject::RemoveFromNotify(), G3D::FilePath::removeTrailingSlash(), Unit::RemoveUnitMovementFlag(), G3D::Any::resolveStringAsFilename(), rint(), G3D::round(), G3D::serialize(), Player::SetAtLoginFlag(), Unit::SetExtraUnitMovementFlags(), WorldObject::SetNotified(), Unit::SetUnitMovementFlags(), soap_begin_shaky(), soap_end_shaky(), soap_string_in(), soap_wstring_in(), BuilderThread::svc(), G3D::Matrix::svdCore(), G3D::TextInput::TextInput(), G3D::CoordinateFrame::toWorldSpace(), G3D::unorm16(), G3D::unorm8(), G3D::GCamera::unproject(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), boss_garfrost::boss_garfrostAI::UpdateAI(), updateLeftFace(), vformat_to(), vfprintf(), vprint(), G3D::MeshAlg::weldAdjacency(), G3D::MeshAlg::weldBoundaryEdges(), write_padded(), PlayerDumpWriter::WriteDump(), G3D::BinaryOutput::writeFloat32(), G3D::BinaryOutput::writeFloat64(), and G3D::TextOutput::writeSymbols().
main()
int main ()
Definition at line 27 of file stack_direction.c.
 {
   int a;
   return ptr_f(&a);
 }
References mpq::a, and ptr_f.
Variable Documentation
ptr_f
volatile int(* ptr_f) (int *) (int *) = f
Definition at line 26 of file stack_direction.c.
Referenced by main().