Azerotcore-wotlk: Appender Class Reference
Appender Class Reference abstract
#include <Appender.h>
Public Member Functions
Appender (uint8 _id, std::string const &name, LogLevel level=LOG_LEVEL_DISABLED, AppenderFlags flags=APPENDER_FLAGS_NONE)
virtual ~Appender ()
uint8 getId () const
std::string const & getName () const
virtual AppenderType getType () const =0
LogLevel getLogLevel () const
AppenderFlags getFlags () const
void setLogLevel (LogLevel)
void write (LogMessage *message)
virtual void setRealmId (uint32)
Static Public Member Functions
static char const * getLogLevelString (LogLevel level)
Private Member Functions
virtual void _write (LogMessage const *)=0
Private Attributes
uint8 id
std::string name
LogLevel level
AppenderFlags flags
Detailed Description
Definition at line 29 of file Appender.h.
Constructor & Destructor Documentation
Appender()
Appender::Appender (uint8 _id, std::string const & name, LogLevel level = LOG_LEVEL_DISABLED, AppenderFlags flags = APPENDER_FLAGS_NONE)
Definition at line 23 of file Appender.cpp.
                                                                                               :
     id(_id), name(_name), level(_level), flags(_flags) { }
~Appender()
Appender::~Appender () virtual
Definition at line 26 of file Appender.cpp.
 { }
Member Function Documentation
_write()
virtual void Appender::_write (LogMessage const *) private pure virtual
Implemented in AppenderDB, AppenderFile, and AppenderConsole.
Referenced by write().
getFlags()
AppenderFlags Appender::getFlags () const
Definition at line 43 of file Appender.cpp.
 {
     return flags;
 }
References flags.
getId()
uint8 Appender::getId () const
Definition at line 28 of file Appender.cpp.
 {
     return id;
 }
References id.
getLogLevel()
LogLevel Appender::getLogLevel () const
Definition at line 38 of file Appender.cpp.
 {
     return level;
 }
References level.
getLogLevelString()
char const * Appender::getLogLevelString (LogLevel level) static
Definition at line 81 of file Appender.cpp.
 {
     switch (level)
     {
         case LOG_LEVEL_FATAL:
             return "FATAL";
         case LOG_LEVEL_ERROR:
             return "ERROR";
         case LOG_LEVEL_WARN:
             return "WARN";
         case LOG_LEVEL_INFO:
             return "INFO";
         case LOG_LEVEL_DEBUG:
             return "DEBUG";
         case LOG_LEVEL_TRACE:
             return "TRACE";
         default:
             return "DISABLED";
     }
 }
References level, LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_FATAL, LOG_LEVEL_INFO, LOG_LEVEL_TRACE, and LOG_LEVEL_WARN.
Referenced by write().
getName()
std::string const & Appender::getName () const
Definition at line 33 of file Appender.cpp.
 {
     return name;
 }
References name.
getType()
virtual AppenderType Appender::getType () const pure virtual
Implemented in AppenderDB, AppenderFile, and AppenderConsole.
setLogLevel()
void Appender::setLogLevel (LogLevel _level)
Definition at line 48 of file Appender.cpp.
 {
     level = _level;
 }
References _level, and level.
setRealmId()
virtual void Appender::setRealmId (uint32) inline virtual
Reimplemented in AppenderDB.
Definition at line 44 of file Appender.h.
 { }
write()
void Appender::write (LogMessage * message)
Definition at line 53 of file Appender.cpp.
 {
     if (!level || level < message->level)
     {
         return;
     }
     std::ostringstream ss;
     if (flags & APPENDER_FLAGS_PREFIX_TIMESTAMP)
     {
         ss << message->getTimeStr() << ' ';
     }
     if (flags & APPENDER_FLAGS_PREFIX_LOGLEVEL)
     {
         ss << Acore::StringFormat("%-5s ", Appender::getLogLevelString(message->level));
     }
     if (flags & APPENDER_FLAGS_PREFIX_LOGFILTERTYPE)
     {
         ss << '[' << message->type << "] ";
     }
     message->prefix = ss.str();
     _write(message);
 }
References _write(), APPENDER_FLAGS_PREFIX_LOGFILTERTYPE, APPENDER_FLAGS_PREFIX_LOGLEVEL, APPENDER_FLAGS_PREFIX_TIMESTAMP, flags, getLogLevelString(), level, message(), and Acore::StringFormat().
Member Data Documentation
flags
AppenderFlags Appender::flags private
Definition at line 52 of file Appender.h.
Referenced by AppenderFile::AppenderFile(), getFlags(), and write().
id
uint8 Appender::id private
Definition at line 49 of file Appender.h.
Referenced by getId().
level
LogLevel Appender::level private
Definition at line 51 of file Appender.h.
Referenced by getLogLevel(), getLogLevelString(), setLogLevel(), and write().
name
std::string Appender::name private
Definition at line 50 of file Appender.h.
Referenced by AppenderConsole::AppenderConsole(), AppenderFile::AppenderFile(), getName(), and AppenderConsole::InitColors().
The documentation for this class was generated from the following files:
src/common/Logging/Appender.h
src/common/Logging/Appender.cpp