Azerotcore-wotlk: npc_battle_at_valhalas Class Reference
npc_battle_at_valhalas Class Reference
Classes
struct npc_battle_at_valhalasAI
Public Member Functions
npc_battle_at_valhalas ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 110 of file zone_icecrown.cpp.
Constructor & Destructor Documentation
npc_battle_at_valhalas()
npc_battle_at_valhalas::npc_battle_at_valhalas () inline
Definition at line 113 of file zone_icecrown.cpp.
 : CreatureScript("npc_battle_at_valhalas") { }
Member Function Documentation
GetAI()
CreatureAI* npc_battle_at_valhalas::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 372 of file zone_icecrown.cpp.
     {
         return new npc_battle_at_valhalasAI(creature);
     }
OnQuestAccept()
bool npc_battle_at_valhalas::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 338 of file zone_icecrown.cpp.
     {
         npc_battle_at_valhalasAI* vAI = CAST_AI(npc_battle_at_valhalas::npc_battle_at_valhalasAI, creature->AI());
         vAI->ResetData();
         creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
         if (vAI)
             vAI->StartBattle(player->GetGUID(), quest->GetQuestId());
         switch (quest->GetQuestId())
         {
             case QUEST_BFV_FALLEN_HEROES:
                 creature->Say("Valhalas is yours to win or die in, $N. But whatever you do, stay within the bounds of the arena. To flee is to lose and be dishonored.", LANG_UNIVERSAL, player);
                 break;
             case QUEST_BFV_DARK_MASTER:
                 creature->Say("Prepare yourself. Khit'rix will be entering Valhalas from the southeast. Remember, do not leave the ring or you will lose the battle.", LANG_UNIVERSAL, player);
                 break;
             case QUEST_BFV_SIGRID:
                 creature->Yell("Sigrid Iceborn has returned to the heights of Jotunheim to prove herself against $N. When last they met, $N bester her in personal combat. Let us see the outcome of this match.", LANG_UNIVERSAL, player);
                 break;
             case QUEST_BFV_CARNAGE:
                 creature->Say("Carnage is coming! Remember, no matter what you do, do NOT leave the battle ring or I will disqualify you and your group.", LANG_UNIVERSAL);
                 break;
             case QUEST_BFV_THANE:
                 creature->Say("Look to the southeast and you will see the thane upon the platform near Gjonner the Merciless when he shows himself. Let him come down. Stay within the ring of Valhalas.", LANG_UNIVERSAL);
                 break;
             case QUEST_BFV_FINAL:
                 creature->Say("It's too late to run now. Do not leave the ring. Die bravely, $N!", LANG_UNIVERSAL);
                 break;
         }
         return true;
     }
References Creature::AI(), CAST_AI, Object::GetGUID(), Quest::GetQuestId(), LANG_UNIVERSAL, QUEST_BFV_CARNAGE, QUEST_BFV_DARK_MASTER, QUEST_BFV_FALLEN_HEROES, QUEST_BFV_FINAL, QUEST_BFV_SIGRID, QUEST_BFV_THANE, Object::RemoveFlag(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::ResetData(), Unit::Say(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::StartBattle(), UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and Unit::Yell().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_icecrown.cpp