Azerotcore-wotlk: deps/fmt/include/fmt/printf.h File Reference
printf.h File Reference
#include <algorithm>
#include <limits>
#include <ostream>
#include "format.h"
Classes
struct printf_formatter< T >
class basic_printf_parse_context< Char >
class basic_printf_context< OutputIt, Char >
struct int_checker< IsSigned >
struct int_checker< true >
class printf_precision_handler
class is_zero_int
struct make_unsigned_or_bool< T >
struct make_unsigned_or_bool< bool >
class arg_converter< T, Context >
class char_converter< Context >
struct get_cstring< Char >
class printf_width_handler< Char >
class printf_arg_formatter< OutputIt, Char >
Typedefs
template<typename Char >
using basic_printf_context_t = basic_printf_context< detail::buffer_appender< Char >, Char >
using printf_context = basic_printf_context_t< char >
using wprintf_context = basic_printf_context_t< wchar_t >
using printf_args = basic_format_args< printf_context >
using wprintf_args = basic_format_args< wprintf_context >
Functions
template<typename T , typename Context , typename Char >
void convert_arg (basic_format_arg< Context > &arg, Char type)
template<typename Char >
void parse_flags (basic_format_specs< Char > &specs, const Char *&it, const Char *end)
template<typename Char , typename GetArg >
int parse_header (const Char *&it, const Char *end, basic_format_specs< Char > &specs, GetArg get_arg)
template<typename Char , typename Context >
void vprintf (buffer< Char > &buf, basic_string_view< Char > format, basic_format_args< Context > args)
template<typename... T>
auto make_printf_args (const T &... args) -> format_arg_store< printf_context, T... >
template<typename... T>
auto make_wprintf_args (const T &... args) -> format_arg_store< wprintf_context, T... >
template<typename S , typename Char = char_t<S>>
auto vsprintf (const S &fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> std::basic_string< Char >
template<typename S , typename... T, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>>
auto sprintf (const S &fmt, const T &... args) -> std::basic_string< Char >
template<typename S , typename Char = char_t<S>>
auto vfprintf (std::FILE *f, const S &fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int
template<typename S , typename... T, typename Char = char_t<S>>
auto fprintf (std::FILE *f, const S &fmt, const T &... args) -> int
template<typename S , typename Char = char_t<S>>
auto vprintf (const S &fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int
template<typename S , typename... T, FMT_ENABLE_IF(detail::is_string< S >::value) >
auto printf (const S &fmt, const T &... args) -> int
template<typename S , typename Char = char_t<S>>
FMT_DEPRECATED auto vfprintf (std::basic_ostream< Char > &os, const S &fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int
template<typename S , typename... T, typename Char = char_t<S>>
FMT_DEPRECATED auto fprintf (std::basic_ostream< Char > &os, const S &fmt, const T &... args) -> int
Typedef Documentation
basic_printf_context_t
template<typename Char > using basic_printf_context_t = basic_printf_context<detail::buffer_appender<Char>, Char>
Definition at line 520 of file printf.h.
printf_args
using printf_args = basic_format_args<printf_context>
Definition at line 526 of file printf.h.
printf_context
using printf_context = basic_printf_context_t<char>
Definition at line 523 of file printf.h.
wprintf_args
using wprintf_args = basic_format_args<wprintf_context>
Definition at line 527 of file printf.h.
wprintf_context
using wprintf_context = basic_printf_context_t<wchar_t>
Definition at line 524 of file printf.h.
Function Documentation
convert_arg()
template<typename T , typename Context , typename Char > void convert_arg (basic_format_arg< Context > & arg, Char type)
Definition at line 165 of file printf.h.
{
   visit_format_arg(arg_converter<T, Context>(arg, type), arg);
 }
References arg(), and visit_format_arg().
Referenced by vprintf().
fprintf() [1/2]
template<typename S , typename... T, typename Char = char_t<S>> FMT_DEPRECATED auto fprintf (std::basic_ostream< Char > & os, const S & fmt, const T &... args) -> int
Definition at line 643 of file printf.h.
{
   return vfprintf(os, to_string_view(fmt),
                   fmt::make_format_args<basic_printf_context_t<Char>>(args...));
 }
References fmt, make_format_args(), to_string_view(), and vfprintf().
fprintf() [2/2]
template<typename S , typename... T, typename Char = char_t<S>> auto fprintf (std::FILE * f, const S & fmt, const T &... args) -> int inline
\rst Prints formatted data to the file f.
Example**::
fmt::fprintf(stderr, "Don't %s!", "panic"); \endrst
Definition at line 602 of file printf.h.
{
   using context = basic_printf_context_t<Char>;
   return vfprintf(f, to_string_view(fmt),
                   fmt::make_format_args<context>(args...));
 }
References f(), fmt, to_string_view(), and vfprintf().
Referenced by _db_doprnt_(), _db_dump_(), _db_enter_(), _db_return_(), _db_suicide_(), AppenderFile::_write(), Acore::Abort(), Acore::AbortHandler(), Acore::Assert(), detail::assert_fail(), build_tree(), BZ2_bz__AssertH__fail(), cache_empty(), G3D::consolePrint(), ConvertADT(), Log::CreateAppenderFromConfig(), Log::CreateLoggerFromConfig(), CreatePIDFile(), DBUGCloseFile(), DbugExit(), DBUGOpenFile(), DbugVfprintf(), G3D::debugPrint(), default_reporter(), DoPrefix(), error(), Acore::Error(), eval_num_suffix(), Acore::Fatal(), file_compress(), file_uncompress(), find_type_or_exit(), MMAP::IntermediateValues::generateObjFile(), get_argument(), handle_options(), G3D::Log::Log(), main(), my_end(), my_load_defaults(), my_real_read(), my_search_option_files(), my_thread_basic_global_init(), my_thread_end(), my_thread_global_end(), my_thread_init(), my_time(), mysql_read_default_options(), net_clear(), net_real_write(), TileBuilder::OutputDebugVertices(), perror(), G3D::Log::print(), G3D::Log::println(), G3D::prompt(), Log::ReadLoggersFromConfig(), AppenderConsole::ResetColor(), search_default_file_with_ext(), G3D::Log::section(), AppenderConsole::SetColor(), soap_dealloc(), soap_delegate_deletion(), soap_delete(), soap_print_fault(), soap_print_fault_location(), test_compress(), test_dict_deflate(), test_dict_inflate(), test_gzio(), test_inflate(), test_large_deflate(), test_large_inflate(), test_sync(), thr_alarm(), thr_end_alarm(), vutf8printf(), Acore::Warning(), and PlayerDumpWriter::WriteDump().
make_printf_args()
template<typename... T> auto make_printf_args (const T &... args) -> format_arg_store<printf_context, T...> inline
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtprintf_args. \endrst
Definition at line 536 of file printf.h.
{
   return {args...};
 }
make_wprintf_args()
template<typename... T> auto make_wprintf_args (const T &... args) -> format_arg_store<wprintf_context, T...> inline
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtwprintf_args. \endrst
Definition at line 548 of file printf.h.
{
   return {args...};
 }
parse_flags()
template<typename Char > void parse_flags (basic_format_specs< Char > & specs, const Char *& it, const Char * end)
Definition at line 302 of file printf.h.
{
   for (; it != end; ++it) {
     switch (*it) {
     case '-':
       specs.align = align::left;
       break;
     case '+':
       specs.sign = sign::plus;
       break;
     case '0':
       specs.fill[0] = '0';
       break;
     case ' ':
       if (specs.sign != sign::plus) {
         specs.sign = sign::space;
       }
       break;
     case '#':
       specs.alt = true;
       break;
     default:
       return;
     }
   }
 }
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, basic_format_specs< Char >::fill, align::left, sign::plus, basic_format_specs< Char >::sign, and sign::space.
Referenced by parse_header().
parse_header()
template<typename Char , typename GetArg > int parse_header (const Char *& it, const Char * end, basic_format_specs< Char > & specs, GetArg get_arg)
Definition at line 330 of file printf.h.
{
   int arg_index = -1;
   Char c = *it;
   if (c >= '0' && c <= '9') {
     // Parse an argument index (if followed by '$') or a width possibly
     // preceded with '0' flag(s).
     int value = parse_nonnegative_int(it, end, -1);
     if (it != end && *it == '$') {  // value is an argument index
       ++it;
       arg_index = value != -1 ? value : max_value<int>();
     } else {
       if (c == '0') specs.fill[0] = '0';
       if (value != 0) {
         // Nonzero value means that we parsed width and don't need to
         // parse it or flags again, so return now.
         if (value == -1) FMT_THROW(format_error("number is too big"));
         specs.width = value;
         return arg_index;
       }
     }
   }
   parse_flags(specs, it, end);
   // Parse width.
   if (it != end) {
     if (*it >= '0' && *it <= '9') {
       specs.width = parse_nonnegative_int(it, end, -1);
       if (specs.width == -1) FMT_THROW(format_error("number is too big"));
     } else if (*it == '*') {
       ++it;
       specs.width = static_cast<int>(visit_format_arg(
           detail::printf_width_handler<Char>(specs), get_arg(-1)));
     }
   }
   return arg_index;
 }
References mpq::c, basic_format_specs< Char >::fill, FMT_THROW, get_arg(), parse_flags(), parse_nonnegative_int(), visit_format_arg(), and basic_format_specs< Char >::width.
Referenced by vprintf().
printf()
template<typename S , typename... T, FMT_ENABLE_IF(detail::is_string< S >::value) > auto printf (const S & fmt, const T &... args) -> int inline
\rst Prints formatted data to stdout.
Example**::
fmt::printf("Elapsed time: %.2f seconds", 1.23); \endrst
Definition at line 626 of file printf.h.
{
   return vprintf(
       to_string_view(fmt),
       fmt::make_format_args<basic_printf_context_t<char_t<S>>>(args...));
 }
References fmt, make_format_args(), to_string_view(), and vprintf().
Referenced by ContinentBuilder::Build(), MMAP::MapBuilder::buildAllMaps(), TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMap(), MMAP::MapBuilder::buildMeshFromFile(), MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildNavMesh(), MMAP::MapBuilder::buildSingleTile(), MMAP::MapBuilder::buildTile(), TileBuilder::BuildTiled(), VMAP::TileAssembler::calculateTransformedBound(), checkDirectories(), CliThread(), ConvertADT(), WMOGroup::ConvertToVMAPGroupWmo(), Model::ConvertToVMAPModel(), VMAP::TileAssembler::convertWorld2(), CreateDir(), DBC::DBC(), MMAP::MapBuilder::discoverTiles(), MapObject::Extract(), ExtractCameraFiles(), ExtractDBCFiles(), ExtractDBCs(), ExtractFile(), ExtractGameobjectModels(), ExtractMapsFromMpq(), ExtractMMaps(), ExtractSingleWmo(), fillArchiveNameVector(), finish(), MMAP::IntermediateValues::generateObjFile(), MapChunk::GenerateVertices(), MPQMgr::GetFileFrom(), MPQFile::GetFileStream(), handleArgs(), HandleArgs(), server_commandscript::HandleServerSetDiffTimeCommand(), ADTFile::init(), WDTFile::init(), MPQMgr::Initialize(), MPQMgr::InitializeDBC(), FileLoader::loadFile(), MMAP::TerrainBuilder::loadMap(), MMAP::TerrainBuilder::loadOffMeshConnections(), main(), MPQArchive::MPQArchive(), my_load_defaults(), my_print_help(), my_print_variables(), my_read_charset_file(), my_xml_scan(), WMORoot::open(), WMOGroup::open(), VMAP::WModelAreaCallback::operator()(), ParsMapFiles(), PrintCliPrefix(), anonymous_namespace{Config.cpp}::PrintError(), BIH::BuildStats::printStats(), PrintUsage(), process_alarm(), process_alarm_part2(), processArgv(), DoodadHandler::ProcessInternal(), WorldModelHandler::ProcessInternal(), VMAP::WorldModel_Raw::Read(), Vector3::Read(), WorldModelDefinition::Read(), DoodadDefinition::Read(), MapChunkHeader::Read(), MHDR::Read(), ModelHeader::Read(), WorldModelHeader::Read(), DoodadInstance::Read(), DoodadSet::Read(), LiquidHeader::Read(), H2ORenderMask::Read(), H2OHeader::Read(), H2OInformation::Read(), WMOGroupHeader::Read(), WorldModelGroup::ReadBatches(), Model::ReadBoundingTriangles(), ReadBuild(), DoodadHandler::ReadDoodadPaths(), ReadLiquidTypeTableDBC(), ReadMapDBC(), VMAP::TileAssembler::readMapSpawns(), WorldModelGroup::ReadMaterials(), WorldModelHandler::ReadModelPaths(), WDT::ReadTileTable(), WorldModelGroup::ReadTriangles(), Utils::SaveToDisk(), BuilderThread::svc(), test_compress(), test_dict_inflate(), test_gzio(), test_inflate(), test_large_inflate(), test_rb_tree(), test_sync(), G3D::textPrompt(), thr_multi_unlock(), thr_print_lock(), thr_print_locks(), thread_alarm(), Usage(), usage(), utf8print(), and MMAP::IntermediateValues::writeIV().
sprintf()
template<typename S , typename... T, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>> auto sprintf (const S & fmt, const T &... args) -> std::basic_string<Char> inline
\rst Formats arguments and returns the result as a string.
Example**::
std::string message = fmt::sprintf("The answer is %d", 42); \endrst
Definition at line 574 of file printf.h.
{
   using context = basic_printf_context_t<Char>;
   return vsprintf(to_string_view(fmt), fmt::make_format_args<context>(args...));
 }
References fmt, to_string_view(), and vsprintf().
Referenced by ContinentBuilder::Build(), MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildNavMesh(), Acore::Impl::ByteArrayToHexStr(), BattlegroundAV::ChangeMineOwner(), cs_value(), G3D::System::currentProgramFilename(), MMAP::MapBuilder::discoverTiles(), Spell::EffectScriptEffect(), G3D::errnoToString(), ErrorMessage(), BattlegroundAV::EventPlayerAssaultsPoint(), BattlegroundAV::EventPlayerDefendsPoint(), BattlegroundAV::EventPlayerDestroyedPoint(), Doodad::Extract(), MapObject::Extract(), Doodad::ExtractSet(), ExtractSingleWmo(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::FinishAttackDueToWin(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::FinishEventDueToLoss(), WheatyExceptionReport::FormatOutputValue(), MMAP::IntermediateValues::generateObjFile(), get_date(), ScriptInfo::GetDebugInfo(), G3D::getG3DVersion(), GetScriptCommandName(), gzdopen(), gzprintf(), spell_the_flag_of_ownership::HandleScript(), G3D::System::init(), is_commented(), LoadCommonMPQFiles(), LoadLocaleMPQFiles(), MMAP::TerrainBuilder::loadMap(), main(), make_password_from_salt_323(), my_date_to_str(), my_datetime_to_str(), my_make_scrambled_password_323(), my_thread_name(), my_time_to_str(), my_xml_enter(), my_xml_leave(), my_xml_parse(), mysql_set_character_set(), mysql_stmt_bind_param(), mysql_stmt_bind_result(), mysql_stmt_send_long_data(), TileBuilder::OutputDebugVertices(), ParsMapFiles(), WorldModelRoot::ReadGroups(), scan_patches(), MMAP::MapBuilder::shouldSkipTile(), boss_grand_champion::boss_grand_championAI::SpellHit(), Acore::StringFormat(), BuilderThread::svc(), _SpellScript::EffectNameCheck::ToString(), _SpellScript::EffectAuraNameCheck::ToString(), boss_eadric::boss_eadricAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), vio_new(), WheatyExceptionReport::WheatyUnhandledExceptionFilter(), and MMAP::IntermediateValues::writeIV().
vfprintf() [1/2]
template<typename S , typename Char = char_t<S>> FMT_DEPRECATED auto vfprintf (std::basic_ostream< Char > & os, const S & fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int
Definition at line 633 of file printf.h.
            {
   basic_memory_buffer<Char> buffer;
   vprintf(buffer, to_string_view(fmt), args);
   os.write(buffer.data(), static_cast<std::streamsize>(buffer.size()));
   return static_cast<int>(buffer.size());
 }
References buffer, buffer< T >::data(), fmt, buffer< T >::size(), to_string_view(), and vprintf().
vfprintf() [2/2]
template<typename S , typename Char = char_t<S>> auto vfprintf (std::FILE * f, const S & fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int inline
Definition at line 580 of file printf.h.
            {
   basic_memory_buffer<Char> buffer;
   vprintf(buffer, to_string_view(fmt), args);
   size_t size = buffer.size();
   return std::fwrite(buffer.data(), sizeof(Char), size, f) < size
              ? -1
              : static_cast<int>(size);
 }
References buffer, buffer< T >::data(), f(), fmt, buffer< T >::size(), to_string_view(), and vprintf().
Referenced by default_reporter(), fprintf(), inline_mysql_file_fprintf(), inline_mysql_file_vfprintf(), G3D::Log::lazyvprintf(), G3D::Log::vprintf(), vprintf(), and vutf8printf().
vprintf() [1/2]
template<typename Char , typename Context > void vprintf (buffer< Char > & buf, basic_string_view< Char > format, basic_format_args< Context > args)
Definition at line 368 of file printf.h.
{
   using OutputIt = buffer_appender<Char>;
   auto out = OutputIt(buf);
   auto context = basic_printf_context<OutputIt, Char>(out, args);
   auto parse_ctx = basic_printf_parse_context<Char>(format);
   // Returns the argument with specified index or, if arg_index is -1, the next
   // argument.
   auto get_arg = [&](int arg_index) {
     if (arg_index < 0)
       arg_index = parse_ctx.next_arg_id();
     else
       parse_ctx.check_arg_id(--arg_index);
     return detail::get_arg(context, arg_index);
   };
   const Char* start = parse_ctx.begin();
   const Char* end = parse_ctx.end();
   auto it = start;
   while (it != end) {
     if (!detail::find<false, Char>(it, end, '%', it)) {
       it = end;  // detail::find leaves it == nullptr if it doesn't find '%'
       break;
     }
     Char c = *it++;
     if (it != end && *it == c) {
       out = detail::write(
           out, basic_string_view<Char>(start, detail::to_unsigned(it - start)));
       start = ++it;
       continue;
     }
     out = detail::write(out, basic_string_view<Char>(
                                  start, detail::to_unsigned(it - 1 - start)));
     basic_format_specs<Char> specs;
     specs.align = align::right;
     // Parse argument index, flags and width.
     int arg_index = parse_header(it, end, specs, get_arg);
     if (arg_index == 0) parse_ctx.on_error("argument not found");
     // Parse precision.
     if (it != end && *it == '.') {
       ++it;
       c = it != end ? *it : 0;
       if ('0' <= c && c <= '9') {
         specs.precision = parse_nonnegative_int(it, end, 0);
       } else if (c == '*') {
         ++it;
         specs.precision = static_cast<int>(
             visit_format_arg(detail::printf_precision_handler(), get_arg(-1)));
       } else {
         specs.precision = 0;
       }
     }
     auto arg = get_arg(arg_index);
     // For d, i, o, u, x, and X conversion specifiers, if a precision is
     // specified, the '0' flag is ignored
     if (specs.precision >= 0 && arg.is_integral())
       specs.fill[0] =
           ' ';  // Ignore '0' flag for non-numeric types or if '-' present.
     if (specs.precision >= 0 && arg.type() == detail::type::cstring_type) {
       auto str = visit_format_arg(detail::get_cstring<Char>(), arg);
       auto str_end = str + specs.precision;
       auto nul = std::find(str, str_end, Char());
       arg = detail::make_arg<basic_printf_context<OutputIt, Char>>(
           basic_string_view<Char>(
               str, detail::to_unsigned(nul != str_end ? nul - str
                                                       : specs.precision)));
     }
     if (specs.alt && visit_format_arg(detail::is_zero_int(), arg))
       specs.alt = false;
     if (specs.fill[0] == '0') {
       if (arg.is_arithmetic() && specs.align != align::left)
         specs.align = align::numeric;
       else
         specs.fill[0] = ' ';  // Ignore '0' flag for non-numeric types or if '-'
                               // flag is also present.
     }
     // Parse length and convert the argument to the required type.
     c = it != end ? *it++ : 0;
     Char t = it != end ? *it : 0;
     using detail::convert_arg;
     switch (c) {
     case 'h':
       if (t == 'h') {
         ++it;
         t = it != end ? *it : 0;
         convert_arg<signed char>(arg, t);
       } else {
         convert_arg<short>(arg, t);
       }
       break;
     case 'l':
       if (t == 'l') {
         ++it;
         t = it != end ? *it : 0;
         convert_arg<long long>(arg, t);
       } else {
         convert_arg<long>(arg, t);
       }
       break;
     case 'j':
       convert_arg<intmax_t>(arg, t);
       break;
     case 'z':
       convert_arg<size_t>(arg, t);
       break;
     case 't':
       convert_arg<std::ptrdiff_t>(arg, t);
       break;
     case 'L':
       // printf produces garbage when 'L' is omitted for long double, no
       // need to do the same.
       break;
     default:
       --it;
       convert_arg<void>(arg, c);
     }
     // Parse type.
     if (it == end) FMT_THROW(format_error("invalid format string"));
     specs.type = static_cast<char>(*it++);
     if (arg.is_integral()) {
       // Normalize type.
       switch (specs.type) {
       case 'i':
       case 'u':
         specs.type = 'd';
         break;
       case 'c':
         visit_format_arg(
             detail::char_converter<basic_printf_context<OutputIt, Char>>(arg),
             arg);
         break;
       }
     }
     start = it;
     // Format argument.
     out = visit_format_arg(
         detail::printf_arg_formatter<OutputIt, Char>(out, specs, context), arg);
   }
   detail::write(out, basic_string_view<Char>(start, to_unsigned(it - start)));
 }
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, arg(), mpq::c, convert_arg(), basic_format_specs< Char >::fill, find(), FMT_THROW, format(), get_arg(), if(), align::left, align::numeric, parse_header(), parse_nonnegative_int(), basic_format_specs< Char >::precision, align::right, to_unsigned(), basic_format_specs< Char >::type, visit_format_arg(), and detail::write().
Referenced by printf(), vfprintf(), and vsprintf().
vprintf() [2/2]
template<typename S , typename Char = char_t<S>> auto vprintf (const S & fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> int inline
Definition at line 609 of file printf.h.
            {
   return vfprintf(stdout, to_string_view(fmt), args);
 }
References fmt, to_string_view(), and vfprintf().
vsprintf()
template<typename S , typename Char = char_t<S>> auto vsprintf (const S & fmt, basic_format_args< basic_printf_context_t< type_identity_t< Char >>> args) -> std::basic_string<Char> inline
Definition at line 554 of file printf.h.
{
   basic_memory_buffer<Char> buffer;
   vprintf(buffer, to_string_view(fmt), args);
   return to_string(buffer);
 }
References buffer, fmt, to_string(), to_string_view(), and vprintf().
Referenced by WheatyExceptionReport::HeapLog(), sprintf(), and WheatyExceptionReport::StackLog().