Azerotcore-wotlk: MailSender Class Reference
MailSender Class Reference
#include <Mail.h>
Public Member Functions
MailSender (MailMessageType messageType, uint32 sender_guidlow_or_entry, MailStationery stationery=MAIL_STATIONERY_DEFAULT)
MailSender (Object *sender, MailStationery stationery=MAIL_STATIONERY_DEFAULT)
MailSender (CalendarEvent *sender)
MailSender (AuctionEntry *sender)
MailSender (Player *sender)
MailSender (uint32 senderEntry)
MailMessageType GetMailMessageType () const
uint32 GetSenderId () const
MailStationery GetStationery () const
Private Attributes
MailMessageType m_messageType
uint32 m_senderId
MailStationery m_stationery
Detailed Description
Definition at line 81 of file Mail.h.
Constructor & Destructor Documentation
MailSender() [1/6]
MailSender::MailSender (MailMessageType messageType, uint32 sender_guidlow_or_entry, MailStationery stationery = MAIL_STATIONERY_DEFAULT) inline
Definition at line 84 of file Mail.h.
         : m_messageType(messageType), m_senderId(sender_guidlow_or_entry), m_stationery(stationery)
     {
     }
MailSender() [2/6]
MailSender::MailSender (Object * sender, MailStationery stationery = MAIL_STATIONERY_DEFAULT)
Definition at line 31 of file Mail.cpp.
                                                                 : m_stationery(stationery)
 {
     switch (sender->GetTypeId())
     {
         case TYPEID_UNIT:
             m_messageType = MAIL_CREATURE;
             m_senderId = sender->GetEntry();
             break;
         case TYPEID_GAMEOBJECT:
             m_messageType = MAIL_GAMEOBJECT;
             m_senderId = sender->GetEntry();
             break;
         /*case TYPEID_ITEM:
             m_messageType = MAIL_ITEM;
             m_senderId = sender->GetEntry();
             break;*/
         case TYPEID_PLAYER:
             m_messageType = MAIL_NORMAL;
             m_senderId = sender->GetGUID().GetCounter();
             break;
         default:
             m_messageType = MAIL_NORMAL;
             m_senderId = 0;                                 // will show mail from not existed player
             LOG_ERROR("mail", "MailSender::MailSender - Mail have unexpected sender typeid (%u)", sender->GetTypeId());
             break;
     }
 }
References ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUID(), Object::GetTypeId(), LOG_ERROR, m_messageType, m_senderId, MAIL_CREATURE, MAIL_GAMEOBJECT, MAIL_NORMAL, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
MailSender() [3/6]
MailSender::MailSender (CalendarEvent * sender)
Definition at line 59 of file Mail.cpp.
     : m_messageType(MAIL_CALENDAR), m_senderId(sender->GetEventId()), m_stationery(MAIL_STATIONERY_DEFAULT) // what stationery we should use here?
 {
 }
MailSender() [4/6]
MailSender::MailSender (AuctionEntry * sender)
Definition at line 64 of file Mail.cpp.
     : m_messageType(MAIL_AUCTION), m_senderId(sender->GetHouseId()), m_stationery(MAIL_STATIONERY_AUCTION)
 {
 }
MailSender() [5/6]
MailSender::MailSender (Player * sender)
Definition at line 69 of file Mail.cpp.
 {
     m_messageType = MAIL_NORMAL;
     m_stationery = sender->IsGameMaster() ? MAIL_STATIONERY_GM : MAIL_STATIONERY_DEFAULT;
     m_senderId = sender->GetGUID().GetCounter();
 }
References ObjectGuid::GetCounter(), Object::GetGUID(), Player::IsGameMaster(), m_messageType, m_senderId, m_stationery, MAIL_NORMAL, MAIL_STATIONERY_DEFAULT, and MAIL_STATIONERY_GM.
MailSender() [6/6]
MailSender::MailSender (uint32 senderEntry)
Definition at line 76 of file Mail.cpp.
 {
     m_messageType = MAIL_CREATURE;
     m_senderId = senderEntry;
     m_stationery = MAIL_STATIONERY_DEFAULT;
 }
References m_messageType, m_senderId, m_stationery, MAIL_CREATURE, and MAIL_STATIONERY_DEFAULT.
Member Function Documentation
GetMailMessageType()
MailMessageType MailSender::GetMailMessageType () const inline
Definition at line 94 of file Mail.h.
 { return m_messageType; }
References m_messageType.
Referenced by MailDraft::SendMailTo().
GetSenderId()
uint32 MailSender::GetSenderId () const inline
Definition at line 95 of file Mail.h.
 { return m_senderId; }
References m_senderId.
Referenced by MailDraft::SendMailTo().
GetStationery()
MailStationery MailSender::GetStationery () const inline
Definition at line 96 of file Mail.h.
 { return m_stationery; }
References m_stationery.
Referenced by MailDraft::SendMailTo().
Member Data Documentation
m_messageType
MailMessageType MailSender::m_messageType private
Definition at line 98 of file Mail.h.
Referenced by GetMailMessageType(), and MailSender().
m_senderId
uint32 MailSender::m_senderId private
Definition at line 99 of file Mail.h.
Referenced by GetSenderId(), and MailSender().
m_stationery
MailStationery MailSender::m_stationery private
Definition at line 100 of file Mail.h.
Referenced by GetStationery(), and MailSender().
The documentation for this class was generated from the following files:
src/server/game/Mails/Mail.h
src/server/game/Mails/Mail.cpp