Azerotcore-wotlk: boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI Struct Reference
boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI Struct Reference
Public Member Functions
boss_mechano_lord_capacitusAI (Creature *creature)
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void Reset () override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 62 of file boss_mechano_lord_capacitus.cpp.
Constructor & Destructor Documentation
boss_mechano_lord_capacitusAI()
boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::boss_mechano_lord_capacitusAI (Creature * creature) inline
Definition at line 64 of file boss_mechano_lord_capacitus.cpp.
 : BossAI(creature, DATA_MECHANOLORD_CAPACITUS) { }
Member Function Documentation
EnterCombat()
void boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 66 of file boss_mechano_lord_capacitus.cpp.
         {
             _EnterCombat();
             Talk(YELL_AGGRO);
             events.ScheduleEvent(EVENT_HEADCRACK, 6000);
             events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 10000);
             events.ScheduleEvent(EVENT_BERSERK, 180000);
             events.ScheduleEvent(IsHeroic() ? EVENT_POSITIVE_SHIFT : EVENT_REFLECTIVE_DAMAGE_SHIELD, 15000);
         }
References BossAI::_EnterCombat(), EVENT_BERSERK, EVENT_HEADCRACK, EVENT_POSITIVE_SHIFT, EVENT_REFLECTIVE_DAMAGE_SHIELD, EVENT_SUMMON_NETHER_CHARGE, ScriptedAI::IsHeroic(), CreatureAI::Talk(), and YELL_AGGRO.
JustDied()
void boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 82 of file boss_mechano_lord_capacitus.cpp.
         {
             _JustDied();
             Talk(YELL_DEATH);
         }
References BossAI::_JustDied(), CreatureAI::Talk(), and YELL_DEATH.
JustSummoned()
void boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 88 of file boss_mechano_lord_capacitus.cpp.
         {
             summons.Summon(summon);
             summon->GetMotionMaster()->MoveRandom(30.0f);
         }
References Unit::GetMotionMaster(), MotionMaster::MoveRandom(), SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 76 of file boss_mechano_lord_capacitus.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(YELL_KILL);
         }
References Object::GetTypeId(), CreatureAI::Talk(), TYPEID_PLAYER, and YELL_KILL.
UpdateAI()
void boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 94 of file boss_mechano_lord_capacitus.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_HEADCRACK:
                     me->CastSpell(me->GetVictim(), SPELL_HEADCRACK, false);
                     events.ScheduleEvent(EVENT_HEADCRACK, 20000);
                     break;
                 case EVENT_REFLECTIVE_DAMAGE_SHIELD:
                     Talk(YELL_REFLECTIVE_DAMAGE_SHIELD);
                     me->CastSpell(me, SPELL_REFLECTIVE_DAMAGE_SHIELD, false);
                     events.ScheduleEvent(EVENT_REFLECTIVE_MAGIE_SHIELD, 20000);
                     break;
                 case EVENT_REFLECTIVE_MAGIE_SHIELD:
                     Talk(YELL_REFLECTIVE_MAGIC_SHIELD);
                     me->CastSpell(me, SPELL_REFLECTIVE_MAGIC_SHIELD, false);
                     events.ScheduleEvent(EVENT_REFLECTIVE_DAMAGE_SHIELD, 20000);
                     break;
                 case EVENT_SUMMON_NETHER_CHARGE:
                     {
                         Position pos = me->GetRandomNearPosition(8.0f);
                         me->SummonCreature(NPC_NETHER_CHARGE, pos, TEMPSUMMON_TIMED_DESPAWN, 18000);
                         events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 5000);
                         break;
                     }
                 case EVENT_POSITIVE_SHIFT:
                     me->CastSpell(me, SPELL_POLARITY_SHIFT, true);
                     events.ScheduleEvent(EVENT_POSITIVE_SHIFT, 30000);
                     break;
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_BERSERK, EVENT_HEADCRACK, EVENT_POSITIVE_SHIFT, EVENT_REFLECTIVE_DAMAGE_SHIELD, EVENT_REFLECTIVE_MAGIE_SHIELD, EVENT_SUMMON_NETHER_CHARGE, WorldObject::GetRandomNearPosition(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, NPC_NETHER_CHARGE, pos(), SPELL_BERSERK, SPELL_HEADCRACK, SPELL_POLARITY_SHIFT, SPELL_REFLECTIVE_DAMAGE_SHIELD, SPELL_REFLECTIVE_MAGIC_SHIELD, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), YELL_REFLECTIVE_DAMAGE_SHIELD, and YELL_REFLECTIVE_MAGIC_SHIELD.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp