Azerotcore-wotlk: G3D::UprightFrame Class Reference
G3D::UprightFrame Class Reference
Coordinate frame expressed in Euler angles. Unlike a G3D::Quat, UprightFrame always keeps the reference frame from rolling about its own z axis. Particularly useful for cameras.
#include <UprightFrame.h>
Public Member Functions
UprightFrame (const Vector3 &t=Vector3::zero(), float p=0, float y=0)
UprightFrame (const CoordinateFrame &cframe)
UprightFrame (const Any &any)
Any toAny () const
UprightFrame & operator= (const Any &any)
operator CoordinateFrame () const
CoordinateFrame toCoordinateFrame () const
UprightFrame operator+ (const UprightFrame &other) const
UprightFrame operator* (const float k) const
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Static Public Member Functions
static void unwrapYaw (UprightFrame *a, int N)
Public Attributes
Vector3 translation
float pitch
float yaw
Detailed Description
Coordinate frame expressed in Euler angles. Unlike a G3D::Quat, UprightFrame always keeps the reference frame from rolling about its own z axis. Particularly useful for cameras.
See also
G3D::CoordinateFrame, G3D::Matrix4, G3D::PhysicsFrame, G3D::UprightSpline, G3D::UprightSplineManipulator
Definition at line 23 of file UprightFrame.h.
Constructor & Destructor Documentation
UprightFrame() [1/3]
G3D::UprightFrame::UprightFrame (const Vector3 & t = Vector3::zero(), float p = 0, float y = 0) inline
Definition at line 34 of file UprightFrame.h.
         : translation(t), pitch(p), yaw(y) {}
Referenced by operator*(), operator+(), and operator=().
UprightFrame() [2/3]
G3D::UprightFrame::UprightFrame (const CoordinateFrame & cframe)
Definition at line 13 of file UprightFrame.cpp.
{
     Vector3 look = cframe.lookVector();
     yaw = (float)(G3D::pi() + atan2(look.x, look.z));
     pitch = asin(look.y);
     translation = cframe.translation;
 }
References G3D::CoordinateFrame::lookVector(), G3D::pi(), pitch, G3D::CoordinateFrame::translation, translation, G3D::Vector3::x, G3D::Vector3::y, yaw, and G3D::Vector3::z.
UprightFrame() [3/3]
G3D::UprightFrame::UprightFrame (const Any & any) explicit
Constructs an UprightFrame from an Any object.
The Any format for UprightFrame is:
pitch = ##, translation = Vector3(), yaw = ##
Definition at line 23 of file UprightFrame.cpp.
{
     any.verifyName("UprightFrame");
     any.verifyType(Any::TABLE);
     translation = any["translation"];
     pitch = any["pitch"];
     yaw = any["yaw"];
 }
References G3D::any(), pitch, G3D::Any::TABLE, translation, and yaw.
Member Function Documentation
deserialize()
void G3D::UprightFrame::deserialize (class BinaryInput & b)
Definition at line 109 of file UprightFrame.cpp.
{
     translation.deserialize(b);
     pitch = b.readFloat32();
     yaw = b.readFloat32();
 }
References b, G3D::Vector3::deserialize(), pitch, translation, and yaw.
operator CoordinateFrame()
G3D::UprightFrame::operator CoordinateFrame () const inline
Supports implicit cast to CoordinateFrame
Definition at line 54 of file UprightFrame.h.
{
         return toCoordinateFrame();
     }
References toCoordinateFrame().
operator*()
UprightFrame G3D::UprightFrame::operator* (const float k) const
Required for use with spline
Definition at line 67 of file UprightFrame.cpp.
{
     return UprightFrame(translation * k, pitch * k, yaw * k);
 }
References pitch, translation, UprightFrame(), and yaw.
operator+()
UprightFrame G3D::UprightFrame::operator+ (const UprightFrame & other) const
Required for use with spline
Definition at line 62 of file UprightFrame.cpp.
{
     return UprightFrame(translation + other.translation, pitch + other.pitch, yaw + other.yaw);
 }
References pitch, translation, UprightFrame(), and yaw.
operator=()
UprightFrame & G3D::UprightFrame::operator= (const Any & any)
Definition at line 44 of file UprightFrame.cpp.
{
     *this = UprightFrame(any);
     return *this;
 }
References G3D::any(), and UprightFrame().
serialize()
void G3D::UprightFrame::serialize (class BinaryOutput & b) const
Definition at line 102 of file UprightFrame.cpp.
{
     translation.serialize(b);
     b.writeFloat32(pitch);
     b.writeFloat32(yaw);
 }
References b, pitch, G3D::Vector3::serialize(), translation, and yaw.
toAny()
Any G3D::UprightFrame::toAny () const
Definition at line 33 of file UprightFrame.cpp.
{
     Any any(Any::TABLE, "UprightFrame");
     any["translation"] = translation;
     any["pitch"] = pitch;
     any["yaw"] = yaw;
     return any;
 }
References G3D::any(), pitch, G3D::Any::TABLE, translation, and yaw.
toCoordinateFrame()
CoordinateFrame G3D::UprightFrame::toCoordinateFrame () const
Definition at line 49 of file UprightFrame.cpp.
{
     CoordinateFrame cframe;
     Matrix3 P(Matrix3::fromAxisAngle(Vector3::unitX(), pitch));
     Matrix3 Y(Matrix3::fromAxisAngle(Vector3::unitY(), yaw));
     cframe.rotation = Y * P;
     cframe.translation = translation;
     return cframe;
 }
References G3D::Matrix3::fromAxisAngle(), P, pitch, G3D::CoordinateFrame::rotation, G3D::CoordinateFrame::translation, translation, G3D::Vector3::unitX(), G3D::Vector3::unitY(), Y, and yaw.
Referenced by operator CoordinateFrame().
unwrapYaw()
void G3D::UprightFrame::unwrapYaw (UprightFrame * a, int N) static
Unwraps the yaw values in the elements of the array such that they still represent the same angles but strictly increase/decrease without wrapping about zero. For use with Spline<UprightFrame>
Definition at line 72 of file UprightFrame.cpp.
{
     // Use the first point to establish the wrapping convention
     for (int i = 1; i < N; ++i) {
         const float prev = a[i - 1].yaw;
         float& cur = a[i].yaw;
         // No two angles should be more than pi (i.e., 180-degrees) apart.
         if (abs(cur - prev) > G3D::pi()) {
             // These angles must have wrapped at zero, causing them
             // to be interpolated the long way.
             // Find canonical [0, 2pi] versions of these numbers
             float p = (float)wrap(prev, twoPi());
             float c = (float)wrap(cur, twoPi());
             // Find the difference -pi < diff < pi between the current and previous values
             float diff = c - p;
             if (diff < -G3D::pi()) {
                 diff += (float)twoPi();
             } else if (diff > G3D::pi()) {
                 diff -= (float)twoPi();
             }
             // Offset the current from the previous by the difference
             // between them.
             cur = prev + diff;
         }
     }
 }
References mpq::a, G3D::abs(), mpq::c, diff(), G3D::pi(), prev(), G3D::twoPi(), and G3D::wrap().
Referenced by G3D::UprightSpline::ensureShortestPath().
Member Data Documentation
pitch
float G3D::UprightFrame::pitch
-pi/2 < pitch < pi/2 in radians about the X-axis
Definition at line 29 of file UprightFrame.h.
Referenced by deserialize(), operator*(), operator+(), serialize(), toAny(), toCoordinateFrame(), and UprightFrame().
translation
Vector3 G3D::UprightFrame::translation
Definition at line 26 of file UprightFrame.h.
Referenced by deserialize(), operator*(), operator+(), serialize(), toAny(), toCoordinateFrame(), and UprightFrame().
yaw
float G3D::UprightFrame::yaw
In radians about the Y-axis
Definition at line 32 of file UprightFrame.h.
Referenced by deserialize(), operator*(), operator+(), serialize(), toAny(), toCoordinateFrame(), and UprightFrame().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/UprightFrame.h
deps/g3dlite/source/UprightFrame.cpp