Azerotcore-wotlk: deps/recastnavigation/Detour/Source/DetourNavMesh.cpp File Reference
DetourNavMesh.cpp File Reference
#include <float.h>
#include <string.h>
#include <stdio.h>
#include "DetourNavMesh.h"
#include "DetourNode.h"
#include "DetourCommon.h"
#include "DetourMath.h"
#include "DetourAlloc.h"
#include "DetourAssert.h"
#include <new>
Classes
struct dtTileState
struct dtPolyState
Namespaces
anonymous_namespace{DetourNavMesh.cpp}
Functions
bool overlapSlabs (const float *amin, const float *amax, const float *bmin, const float *bmax, const float px, const float py)
static float getSlabCoord (const float *va, const int side)
static void calcSlabEndPoints (const float *va, const float *vb, float *bmin, float *bmax, const int side)
int computeTileHash (int x, int y, const int mask)
unsigned int allocLink (dtMeshTile *tile)
void freeLink (dtMeshTile *tile, unsigned int link)
dtNavMesh * dtAllocNavMesh ()
void dtFreeNavMesh (dtNavMesh *navmesh)
template<bool onlyBoundary>
void anonymous_namespace{DetourNavMesh.cpp}::closestPointOnDetailEdges (const dtMeshTile *tile, const dtPoly *poly, const float *pos, float *closest)
Function Documentation
allocLink()
unsigned int allocLink (dtMeshTile * tile) inline
Definition at line 122 of file DetourNavMesh.cpp.
 {
     if (tile->linksFreeList == DT_NULL_LINK)
         return DT_NULL_LINK;
     unsigned int link = tile->linksFreeList;
     tile->linksFreeList = tile->links[link].next;
     return link;
 }
References DT_NULL_LINK, dtMeshTile::links, dtMeshTile::linksFreeList, and dtLink::next.
Referenced by dtNavMesh::baseOffMeshLinks(), dtNavMesh::connectExtLinks(), dtNavMesh::connectExtOffMeshLinks(), and dtNavMesh::connectIntLinks().
calcSlabEndPoints()
static void calcSlabEndPoints (const float * va, const float * vb, float * bmin, float * bmax, const int side) static
Definition at line 76 of file DetourNavMesh.cpp.
 {
     if (side == 0 || side == 4)
     {
         if (va[2] < vb[2])
         {
             bmin[0] = va[2];
             bmin[1] = va[1];
             bmax[0] = vb[2];
             bmax[1] = vb[1];
         }
         else
         {
             bmin[0] = vb[2];
             bmin[1] = vb[1];
             bmax[0] = va[2];
             bmax[1] = va[1];
         }
     }
     else if (side == 2 || side == 6)
     {
         if (va[0] < vb[0])
         {
             bmin[0] = va[0];
             bmin[1] = va[1];
             bmax[0] = vb[0];
             bmax[1] = vb[1];
         }
         else
         {
             bmin[0] = vb[0];
             bmin[1] = vb[1];
             bmax[0] = va[0];
             bmax[1] = va[1];
         }
     }
 }
Referenced by dtNavMesh::findConnectingPolys().
computeTileHash()
int computeTileHash (int x, int y, const int mask) inline
Definition at line 114 of file DetourNavMesh.cpp.
 {
     const unsigned int h1 = 0x8da6b343; // Large multiplicative constants;
     const unsigned int h2 = 0xd8163841; // here arbitrarily chosen primes
     unsigned int n = h1 * x + h2 * y;
     return (int)(n & mask);
 }
References G3D::x, and G3D::y.
Referenced by dtNavMesh::addTile(), dtNavMesh::getTileAt(), dtNavMesh::getTileRefAt(), dtNavMesh::getTilesAt(), and dtNavMesh::removeTile().
freeLink()
void freeLink (dtMeshTile * tile, unsigned int link) inline
Definition at line 131 of file DetourNavMesh.cpp.
 {
     tile->links[link].next = tile->linksFreeList;
     tile->linksFreeList = link;
 }
References dtMeshTile::links, dtMeshTile::linksFreeList, and dtLink::next.
Referenced by dtNavMesh::unconnectLinks().
getSlabCoord()
static float getSlabCoord (const float * va, const int side) static
Definition at line 67 of file DetourNavMesh.cpp.
 {
     if (side == 0 || side == 4)
         return va[0];
     else if (side == 2 || side == 6)
         return va[2];
     return 0;
 }
Referenced by dtNavMesh::findConnectingPolys().
overlapSlabs()
bool overlapSlabs (const float * amin, const float * amax, const float * bmin, const float * bmax, const float px, const float py) inline
Definition at line 31 of file DetourNavMesh.cpp.
 {
     // Check for horizontal overlap.
     // The segment is shrunken a little so that slabs which touch
     // at end points are not connected.
     const float minx = dtMax(amin[0]+px,bmin[0]+px);
     const float maxx = dtMin(amax[0]-px,bmax[0]-px);
     if (minx > maxx)
         return false;
     // Check vertical overlap.
     const float ad = (amax[1]-amin[1]) / (amax[0]-amin[0]);
     const float ak = amin[1] - ad*amin[0];
     const float bd = (bmax[1]-bmin[1]) / (bmax[0]-bmin[0]);
     const float bk = bmin[1] - bd*bmin[0];
     const float aminy = ad*minx + ak;
     const float amaxy = ad*maxx + ak;
     const float bminy = bd*minx + bk;
     const float bmaxy = bd*maxx + bk;
     const float dmin = bminy - aminy;
     const float dmax = bmaxy - amaxy;
     // Crossing segments always overlap.
     if (dmin*dmax < 0)
         return true;
     // Check for overlap at endpoints.
     const float thr = dtSqr(py*2);
     if (dmin*dmin <= thr || dmax*dmax <= thr)
         return true;
     return false;
 }
References dtMax(), dtMin(), and dtSqr().
Referenced by dtNavMesh::findConnectingPolys().