Azerotcore-wotlk: dtCollectPolysQuery Class Reference
dtCollectPolysQuery Class Reference
Public Member Functions
dtCollectPolysQuery (dtPolyRef *polys, const int maxPolys)
int numCollected () const
bool overflowed () const
void process (const dtMeshTile *tile, dtPoly **polys, dtPolyRef *refs, int count)
Public Member Functions inherited from dtPolyQuery
virtual ~dtPolyQuery ()
Private Attributes
dtPolyRef * m_polys
const int m_maxPolys
int m_numCollected
bool m_overflow
Detailed Description
Definition at line 829 of file DetourNavMeshQuery.cpp.
Constructor & Destructor Documentation
dtCollectPolysQuery()
dtCollectPolysQuery::dtCollectPolysQuery (dtPolyRef * polys, const int maxPolys) inline
Definition at line 837 of file DetourNavMeshQuery.cpp.
         : m_polys(polys), m_maxPolys(maxPolys), m_numCollected(0), m_overflow(false)
     {
     }
Member Function Documentation
numCollected()
int dtCollectPolysQuery::numCollected () const inline
Definition at line 842 of file DetourNavMeshQuery.cpp.
 { return m_numCollected; }
References m_numCollected.
Referenced by dtNavMeshQuery::queryPolygons().
overflowed()
bool dtCollectPolysQuery::overflowed () const inline
Definition at line 843 of file DetourNavMeshQuery.cpp.
 { return m_overflow; }
References m_overflow.
Referenced by dtNavMeshQuery::queryPolygons().
process()
void dtCollectPolysQuery::process (const dtMeshTile * tile, dtPoly ** polys, dtPolyRef * refs, int count) inline virtual
Called for each batch of unique polygons touched by the search area in dtNavMeshQuery::queryPolygons. This can be called multiple times for a single query.
Implements dtPolyQuery.
Definition at line 845 of file DetourNavMeshQuery.cpp.
     {
         dtIgnoreUnused(tile);
         dtIgnoreUnused(polys);
         int numLeft = m_maxPolys - m_numCollected;
         int toCopy = count;
         if (toCopy > numLeft)
         {
             m_overflow = true;
             toCopy = numLeft;
         }
         memcpy(m_polys + m_numCollected, refs, (size_t)toCopy * sizeof(dtPolyRef));
         m_numCollected += toCopy;
     }
References count(), dtIgnoreUnused(), m_maxPolys, m_numCollected, m_overflow, m_polys, and memcpy.
Member Data Documentation
m_maxPolys
const int dtCollectPolysQuery::m_maxPolys private
Definition at line 832 of file DetourNavMeshQuery.cpp.
Referenced by process().
m_numCollected
int dtCollectPolysQuery::m_numCollected private
Definition at line 833 of file DetourNavMeshQuery.cpp.
Referenced by numCollected(), and process().
m_overflow
bool dtCollectPolysQuery::m_overflow private
Definition at line 834 of file DetourNavMeshQuery.cpp.
Referenced by overflowed(), and process().
m_polys
dtPolyRef* dtCollectPolysQuery::m_polys private
Definition at line 831 of file DetourNavMeshQuery.cpp.
Referenced by process().
The documentation for this class was generated from the following file:
deps/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp