Azerotcore-wotlk: TurretAI Struct Reference
TurretAI Struct Reference
#include <CombatAI.h>
Public Member Functions
TurretAI (Creature *c)
bool CanAIAttack (const Unit *who) const override
void AttackStart (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Protected Attributes
float m_minRange
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Detailed Description
Definition at line 81 of file CombatAI.h.
Constructor & Destructor Documentation
TurretAI()
TurretAI::TurretAI (Creature * c) explicit
Definition at line 218 of file CombatAI.cpp.
                               : CreatureAI(c)
 {
     if (!me->m_spells[0])
         LOG_ERROR("entities.unit.ai", "TurretAI set for creature (entry = %u) with spell1=0. AI will do nothing", me->GetEntry());
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(me->m_spells[0]);
     m_minRange = spellInfo ? spellInfo->GetMinRange(false) : 0;
     me->m_CombatDistance = spellInfo ? spellInfo->GetMaxRange(false) : 0;
     me->m_SightDistance = me->m_CombatDistance;
 }
References Object::GetEntry(), SpellInfo::GetMaxRange(), SpellInfo::GetMinRange(), LOG_ERROR, Creature::m_CombatDistance, m_minRange, Creature::m_SightDistance, Creature::m_spells, CreatureAI::me, and sSpellMgr.
Member Function Documentation
AttackStart()
void TurretAI::AttackStart (Unit * who) override virtual
Reimplemented from UnitAI.
Definition at line 238 of file CombatAI.cpp.
 {
     if (who)
         me->Attack(who, false);
 }
References Unit::Attack(), and CreatureAI::me.
CanAIAttack()
bool TurretAI::CanAIAttack (const Unit * who) const override virtual
Reimplemented from UnitAI.
Reimplemented in boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI.
Definition at line 229 of file CombatAI.cpp.
 {
     // TODO: use one function to replace it
     if (!me->IsWithinCombatRange(me->GetVictim(), me->m_CombatDistance)
             || (m_minRange && me->IsWithinCombatRange(me->GetVictim(), m_minRange)))
         return false;
     return true;
 }
References Unit::GetVictim(), Unit::IsWithinCombatRange(), Creature::m_CombatDistance, m_minRange, and CreatureAI::me.
Permissible()
static int TurretAI::Permissible (Creature const *) inline static
Definition at line 89 of file CombatAI.h.
 { return PERMIT_BASE_NO; }
References PERMIT_BASE_NO.
UpdateAI()
void TurretAI::UpdateAI (uint32 diff) override virtual
Implements UnitAI.
Reimplemented in boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI.
Definition at line 244 of file CombatAI.cpp.
 {
     if (!UpdateVictim())
         return;
     if( me->m_spells[0] )
         DoSpellAttackIfReady(me->m_spells[0]);
 }
References UnitAI::DoSpellAttackIfReady(), Creature::m_spells, CreatureAI::me, and CreatureAI::UpdateVictim().
Referenced by boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::UpdateAI().
Member Data Documentation
m_minRange
float TurretAI::m_minRange protected
Definition at line 92 of file CombatAI.h.
Referenced by CanAIAttack(), and TurretAI().
The documentation for this struct was generated from the following files:
src/server/game/AI/CoreAI/CombatAI.h
src/server/game/AI/CoreAI/CombatAI.cpp