Azerotcore-wotlk: Guild::MoveItemData Class Reference
Guild::MoveItemData Class Reference abstract
Public Member Functions
MoveItemData (Guild *guild, Player *player, uint8 container, uint8 slotId)
virtual ~MoveItemData ()
virtual bool IsBank () const =0
virtual bool InitItem ()=0
virtual bool CheckItem (uint32 &splitedAmount)
virtual bool HasStoreRights (MoveItemData *) const
virtual bool HasWithdrawRights (MoveItemData *) const
bool CanStore (Item *pItem, bool swap, bool sendError)
bool CloneItem (uint32 count)
virtual void RemoveItem (CharacterDatabaseTransaction trans, MoveItemData *pOther, uint32 splitedAmount=0)=0
virtual Item * StoreItem (CharacterDatabaseTransaction trans, Item *pItem)=0
virtual void LogBankEvent (CharacterDatabaseTransaction trans, MoveItemData *pFrom, uint32 count) const =0
virtual void LogAction (MoveItemData *pFrom) const
void CopySlots (SlotIds &ids) const
Item * GetItem (bool isCloned=false) const
uint8 GetContainer () const
uint8 GetSlotId () const
Protected Member Functions
virtual InventoryResult CanStore (Item *pItem, bool swap)=0
Protected Attributes
Guild * m_pGuild
Player * m_pPlayer
uint8 m_container
uint8 m_slotId
Item * m_pItem
Item * m_pClonedItem
ItemPosCountVec m_vec
Detailed Description
Definition at line 578 of file Guild.h.
Constructor & Destructor Documentation
MoveItemData()
Guild::MoveItemData::MoveItemData (Guild * guild, Player * player, uint8 container, uint8 slotId) inline
Definition at line 581 of file Guild.h.
                                                                                   : m_pGuild(guild), m_pPlayer(player),
             m_container(container), m_slotId(slotId), m_pItem(nullptr), m_pClonedItem(nullptr) { }
~MoveItemData()
virtual Guild::MoveItemData::~MoveItemData () inline virtual
Definition at line 583 of file Guild.h.
 { }
Member Function Documentation
CanStore() [1/2]
virtual InventoryResult Guild::MoveItemData::CanStore (Item * pItem, bool swap) protected pure virtual
Implemented in Guild::BankMoveItemData, and Guild::PlayerMoveItemData.
CanStore() [2/2]
bool Guild::MoveItemData::CanStore (Item * pItem, bool swap, bool sendError)
Definition at line 816 of file Guild.cpp.
 {
     m_vec.clear();
     InventoryResult msg = CanStore(pItem, swap);
     if (sendError && msg != EQUIP_ERR_OK)
         m_pPlayer->SendEquipError(msg, pItem);
     return (msg == EQUIP_ERR_OK);
 }
References EQUIP_ERR_OK, and swap().
Referenced by Guild::_DoItemsMove().
CheckItem()
bool Guild::MoveItemData::CheckItem (uint32 & splitedAmount) virtual
Definition at line 806 of file Guild.cpp.
 {
     ASSERT(m_pItem);
     if (splitedAmount > m_pItem->GetCount())
         return false;
     if (splitedAmount == m_pItem->GetCount())
         splitedAmount = 0;
     return true;
 }
References ASSERT.
Referenced by Guild::_MoveItems().
CloneItem()
bool Guild::MoveItemData::CloneItem (uint32 count)
Definition at line 825 of file Guild.cpp.
 {
     ASSERT(m_pItem);
     m_pClonedItem = m_pItem->CloneItem(count);
     if (!m_pClonedItem)
     {
         m_pPlayer->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, m_pItem);
         return false;
     }
     return true;
 }
References ASSERT, count(), and EQUIP_ERR_ITEM_NOT_FOUND.
Referenced by Guild::_MoveItems().
CopySlots()
void Guild::MoveItemData::CopySlots (SlotIds & ids) const inline
Definition at line 846 of file Guild.cpp.
 {
     for (ItemPosCountVec::const_iterator itr = m_vec.begin(); itr != m_vec.end(); ++itr)
         ids.insert(uint8(itr->pos));
 }
Referenced by Guild::_SendBankContentUpdate().
GetContainer()
uint8 Guild::MoveItemData::GetContainer () const inline
Definition at line 610 of file Guild.h.
 { return m_container; }
References m_container.
Referenced by Guild::_SendBankContentUpdate(), Guild::BankMoveItemData::HasStoreRights(), Guild::BankMoveItemData::HasWithdrawRights(), LogAction(), Guild::PlayerMoveItemData::LogBankEvent(), Guild::BankMoveItemData::LogBankEvent(), and Guild::BankMoveItemData::RemoveItem().
GetItem()
Item* Guild::MoveItemData::GetItem (bool isCloned = false) const inline
Definition at line 609 of file Guild.h.
 { return isCloned ? m_pClonedItem : m_pItem; }
References m_pClonedItem, and m_pItem.
Referenced by Guild::_DoItemsMove(), LogAction(), Guild::PlayerMoveItemData::LogBankEvent(), and Guild::BankMoveItemData::LogBankEvent().
GetSlotId()
uint8 Guild::MoveItemData::GetSlotId () const inline
Definition at line 611 of file Guild.h.
 { return m_slotId; }
References m_slotId.
Referenced by Guild::_SendBankContentUpdate(), and LogAction().
HasStoreRights()
virtual bool Guild::MoveItemData::HasStoreRights (MoveItemData *) const inline virtual
Reimplemented in Guild::BankMoveItemData.
Definition at line 591 of file Guild.h.
 { return true; }
Referenced by Guild::_MoveItems().
HasWithdrawRights()
virtual bool Guild::MoveItemData::HasWithdrawRights (MoveItemData *) const inline virtual
Reimplemented in Guild::BankMoveItemData.
Definition at line 593 of file Guild.h.
 { return true; }
Referenced by Guild::_MoveItems().
InitItem()
virtual bool Guild::MoveItemData::InitItem () pure virtual
Implemented in Guild::BankMoveItemData, and Guild::PlayerMoveItemData.
Referenced by Guild::_MoveItems().
IsBank()
virtual bool Guild::MoveItemData::IsBank () const pure virtual
Implemented in Guild::BankMoveItemData, and Guild::PlayerMoveItemData.
Referenced by Guild::_SendBankContentUpdate(), Guild::BankMoveItemData::HasStoreRights(), Guild::BankMoveItemData::HasWithdrawRights(), LogAction(), Guild::BankMoveItemData::LogBankEvent(), and Guild::BankMoveItemData::RemoveItem().
LogAction()
void Guild::MoveItemData::LogAction (MoveItemData * pFrom) const virtual
Reimplemented in Guild::BankMoveItemData.
Definition at line 837 of file Guild.cpp.
 {
     ASSERT(pFrom->GetItem());
     sScriptMgr->OnGuildItemMove(m_pGuild, m_pPlayer, pFrom->GetItem(),
                                 pFrom->IsBank(), pFrom->GetContainer(), pFrom->GetSlotId(),
                                 IsBank(), GetContainer(), GetSlotId());
 }
References ASSERT, GetContainer(), GetItem(), GetSlotId(), IsBank(), and sScriptMgr.
Referenced by Guild::_DoItemsMove(), and Guild::BankMoveItemData::LogAction().
LogBankEvent()
virtual void Guild::MoveItemData::LogBankEvent (CharacterDatabaseTransaction trans, MoveItemData * pFrom, uint32 count) const pure virtual
Implemented in Guild::BankMoveItemData, and Guild::PlayerMoveItemData.
Referenced by Guild::_DoItemsMove().
RemoveItem()
virtual void Guild::MoveItemData::RemoveItem (CharacterDatabaseTransaction trans, MoveItemData * pOther, uint32 splitedAmount = 0) pure virtual
Implemented in Guild::PlayerMoveItemData, and Guild::BankMoveItemData.
Referenced by Guild::_DoItemsMove().
StoreItem()
virtual Item* Guild::MoveItemData::StoreItem (CharacterDatabaseTransaction trans, Item * pItem) pure virtual
Implemented in Guild::BankMoveItemData, and Guild::PlayerMoveItemData.
Referenced by Guild::_DoItemsMove().
Member Data Documentation
m_container
uint8 Guild::MoveItemData::m_container protected
Definition at line 618 of file Guild.h.
Referenced by GetContainer().
m_pClonedItem
Item* Guild::MoveItemData::m_pClonedItem protected
Definition at line 621 of file Guild.h.
Referenced by GetItem().
m_pGuild
Guild* Guild::MoveItemData::m_pGuild protected
Definition at line 616 of file Guild.h.
m_pItem
Item* Guild::MoveItemData::m_pItem protected
Definition at line 620 of file Guild.h.
Referenced by GetItem().
m_pPlayer
Player* Guild::MoveItemData::m_pPlayer protected
Definition at line 617 of file Guild.h.
m_slotId
uint8 Guild::MoveItemData::m_slotId protected
Definition at line 619 of file Guild.h.
Referenced by GetSlotId().
m_vec
ItemPosCountVec Guild::MoveItemData::m_vec protected
Definition at line 622 of file Guild.h.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp