Azerotcore-wotlk: utf8::unchecked::iterator< octet_iterator > Class Template Reference
utf8::unchecked::iterator< octet_iterator > Class Template Reference
#include <unchecked.h>
Public Member Functions
iterator ()
iterator (const octet_iterator &octet_it)
octet_iterator base () const
uint32_t operator* () const
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
Private Attributes
octet_iterator it
Detailed Description
template<typename octet_iterator>
class utf8::unchecked::iterator< octet_iterator >
Definition at line 179 of file unchecked.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename octet_iterator > utf8::unchecked::iterator< octet_iterator >::iterator () inline
Definition at line 182 of file unchecked.h.
 {}
iterator() [2/2]
template<typename octet_iterator > utf8::unchecked::iterator< octet_iterator >::iterator (const octet_iterator< octet_iterator > & octet_it) inline explicit
Definition at line 183 of file unchecked.h.
 : it(octet_it) {}
Member Function Documentation
base()
template<typename octet_iterator > octet_iterator utf8::unchecked::iterator< octet_iterator >::base () const inline
Definition at line 185 of file unchecked.h.
 { return it; }
References utf8::unchecked::iterator< octet_iterator >::it.
operator!=()
template<typename octet_iterator > bool utf8::unchecked::iterator< octet_iterator >::operator!= (const iterator< octet_iterator > & rhs) const inline
Definition at line 195 of file unchecked.h.
             {
                 return !(operator == (rhs));
             }
References utf8::unchecked::iterator< octet_iterator >::operator==().
operator*()
template<typename octet_iterator > uint32_t utf8::unchecked::iterator< octet_iterator >::operator* () const inline
Definition at line 186 of file unchecked.h.
             {
                 octet_iterator temp = it;
                 return utf8::unchecked::next(temp);
             }
References utf8::unchecked::iterator< octet_iterator >::it, and utf8::unchecked::next().
operator++() [1/2]
template<typename octet_iterator > iterator& utf8::unchecked::iterator< octet_iterator >::operator++ () inline
Definition at line 199 of file unchecked.h.
             {
                 ::std::advance(it, utf8::internal::sequence_length(it));
                 return *this;
             }
References utf8::unchecked::advance(), utf8::unchecked::iterator< octet_iterator >::it, and utf8::internal::sequence_length().
operator++() [2/2]
template<typename octet_iterator > iterator utf8::unchecked::iterator< octet_iterator >::operator++ (int) inline
Definition at line 204 of file unchecked.h.
             {
                 iterator temp = *this;
                 ::std::advance(it, utf8::internal::sequence_length(it));
                 return temp;
             }
References utf8::unchecked::advance(), utf8::unchecked::iterator< octet_iterator >::it, and utf8::internal::sequence_length().
operator--() [1/2]
template<typename octet_iterator > iterator& utf8::unchecked::iterator< octet_iterator >::operator-- () inline
Definition at line 210 of file unchecked.h.
             {
                 utf8::unchecked::prior(it);
                 return *this;
             }
References utf8::unchecked::iterator< octet_iterator >::it, and utf8::unchecked::prior().
operator--() [2/2]
template<typename octet_iterator > iterator utf8::unchecked::iterator< octet_iterator >::operator-- (int) inline
Definition at line 215 of file unchecked.h.
             {
                 iterator temp = *this;
                 utf8::unchecked::prior(it);
                 return temp;
             }
References utf8::unchecked::iterator< octet_iterator >::it, and utf8::unchecked::prior().
operator==()
template<typename octet_iterator > bool utf8::unchecked::iterator< octet_iterator >::operator== (const iterator< octet_iterator > & rhs) const inline
Definition at line 191 of file unchecked.h.
             {
                 return (it == rhs.it);
             }
References utf8::unchecked::iterator< octet_iterator >::it.
Referenced by utf8::unchecked::iterator< octet_iterator >::operator!=().
Member Data Documentation
it
template<typename octet_iterator > octet_iterator utf8::unchecked::iterator< octet_iterator >::it private
Definition at line 180 of file unchecked.h.
Referenced by utf8::unchecked::iterator< octet_iterator >::base(), utf8::unchecked::iterator< octet_iterator >::operator*(), utf8::unchecked::iterator< octet_iterator >::operator++(), utf8::unchecked::iterator< octet_iterator >::operator--(), and utf8::unchecked::iterator< octet_iterator >::operator==().
The documentation for this class was generated from the following file:
deps/utf8cpp/utf8/unchecked.h