Azerotcore-wotlk: boss_deathbringer_saurfang::boss_deathbringer_saurfangAI Struct Reference
boss_deathbringer_saurfang::boss_deathbringer_saurfangAI Struct Reference
Public Member Functions
boss_deathbringer_saurfangAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
bool CanAIAttack (const Unit *) const override
void AttackStart (Unit *victim) override
void MoveInLineOfSight (Unit *) override
void JustReachedHome () override
void KilledUnit (Unit *victim) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void MovementInform (uint32 type, uint32 id) override
void SpellHitTarget (Unit *, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
void DoAction (int32 action) override
uint32 GetData (uint32 type) const override
void EnterEvadeMode () override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 _fallenChampionCastCount
bool _introDone
bool _frenzied
uint16 _transportCheckTimer
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 244 of file boss_deathbringer_saurfang.cpp.
Constructor & Destructor Documentation
boss_deathbringer_saurfangAI()
boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI (Creature * creature) inline
Definition at line 246 of file boss_deathbringer_saurfang.cpp.
                                                          : BossAI(creature, DATA_DEATHBRINGER_SAURFANG)
         {
             ASSERT(creature->GetVehicleKit()); // we dont actually use it, just check if exists
         }
References ASSERT, and Unit::GetVehicleKit().
Member Function Documentation
AttackStart()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 324 of file boss_deathbringer_saurfang.cpp.
         {
             if (!_introDone || me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC))
                 return;
             ScriptedAI::AttackStart(victim);
         }
References _introDone, ScriptedAI::AttackStart(), Object::HasFlag(), ScriptedAI::me, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
CanAIAttack()
bool boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::CanAIAttack (const Unit *) const inline override virtual
Reimplemented from UnitAI.
Definition at line 319 of file boss_deathbringer_saurfang.cpp.
         {
             return _introDone;
         }
References _introDone.
DamageTaken()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 346 of file boss_deathbringer_saurfang.cpp.
         {
             if (!_frenzied && HealthBelowPct(31)) // AT 30%, not below
             {
                 _frenzied = true;
                 DoCast(me, SPELL_FRENZY);
                 Talk(SAY_FRENZY);
             }
         }
References _frenzied, UnitAI::DoCast(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, SAY_FRENZY, SPELL_FRENZY, and CreatureAI::Talk().
DoAction()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 463 of file boss_deathbringer_saurfang.cpp.
         {
             switch (action)
             {
                 case ACTION_MARK_OF_THE_FALLEN_CHAMPION:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true, -SPELL_MARK_OF_THE_FALLEN_CHAMPION))
                     {
                         ++_fallenChampionCastCount;
                         me->CastSpell(target, SPELL_MARK_OF_THE_FALLEN_CHAMPION, false);
                         me->SetPower(POWER_ENERGY, 0);
                         if (Aura* bloodPower = me->GetAura(SPELL_BLOOD_POWER))
                             bloodPower->RecalculateAmountOfEffects();
                     }
                     break;
                 case ACTION_INTRO_DONE:
                     _introDone = true;
                     break;
                 default:
                     break;
             }
         }
References _fallenChampionCastCount, _introDone, ACTION_INTRO_DONE, ACTION_MARK_OF_THE_FALLEN_CHAMPION, Unit::CastSpell(), Unit::GetAura(), ScriptedAI::me, POWER_ENERGY, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetPower(), SPELL_BLOOD_POWER, and SPELL_MARK_OF_THE_FALLEN_CHAMPION.
EnterCombat()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 272 of file boss_deathbringer_saurfang.cpp.
         {
             if (!_introDone)
             {
                 me->CombatStop();
                 return;
             }
             // pussywizard: without this, the aura is not recalculated the first time
             me->RemoveAurasDueToSpell(SPELL_BLOOD_POWER);
             DoCast(me, SPELL_BLOOD_POWER, true);
             if (!instance->CheckRequiredBosses(DATA_DEATHBRINGER_SAURFANG, who->ToPlayer()))
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             // oh just screw intro, enter combat - no exploits please
             me->setActive(true);
             DoZoneInCombat();
             Talk(SAY_AGGRO);
             events.Reset();
             events.ScheduleEvent(EVENT_SUMMON_BLOOD_BEAST, 30000);
             events.ScheduleEvent(EVENT_BERSERK, (IsHeroic() ? 360000 : 480000));
             events.ScheduleEvent(EVENT_BOILING_BLOOD, 15500, 0);
             events.ScheduleEvent(EVENT_BLOOD_NOVA, 17000, 0);
             events.ScheduleEvent(EVENT_RUNE_OF_BLOOD, 20000, 0);
             _fallenChampionCastCount = 0;
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_MARK_OF_THE_FALLEN_CHAMPION);
             instance->SetBossState(DATA_DEATHBRINGER_SAURFANG, IN_PROGRESS);
         }
References _fallenChampionCastCount, _introDone, InstanceScript::CheckRequiredBosses(), Unit::CombatStop(), DATA_DEATHBRINGER_SAURFANG, UnitAI::DoCast(), InstanceScript::DoCastSpellOnPlayers(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), CreatureAI::DoZoneInCombat(), EnterEvadeMode(), EVENT_BERSERK, EVENT_BLOOD_NOVA, EVENT_BOILING_BLOOD, EVENT_RUNE_OF_BLOOD, EVENT_SUMMON_BLOOD_BEAST, IN_PROGRESS, BossAI::instance, ScriptedAI::IsHeroic(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_BLOOD_POWER, SPELL_MARK_OF_THE_FALLEN_CHAMPION, CreatureAI::Talk(), and Object::ToPlayer().
EnterEvadeMode()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 498 of file boss_deathbringer_saurfang.cpp.
         {
             BossAI::EnterEvadeMode();
             if (Creature* creature = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SAURFANG_EVENT_NPC)))
                 creature->AI()->DoAction(ACTION_EVADE);
         }
References ACTION_EVADE, DATA_SAURFANG_EVENT_NPC, CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, and ScriptedAI::me.
Referenced by EnterCombat(), and UpdateAI().
GetData()
uint32 boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 485 of file boss_deathbringer_saurfang.cpp.
         {
             if (type == DATA_MADE_A_MESS)
             {
                 if (_fallenChampionCastCount < RAID_MODE<uint32>(3, 5, 3, 5))
                     return 1;
             }
             else if (type == FALLEN_CHAMPION_CAST_COUNT)
                 return _fallenChampionCastCount;
             return 0;
         }
References _fallenChampionCastCount, DATA_MADE_A_MESS, and FALLEN_CHAMPION_CAST_COUNT.
JustDied()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 308 of file boss_deathbringer_saurfang.cpp.
         {
             _JustDied();
             DoCast(me, SPELL_ACHIEVEMENT, true);
             Talk(SAY_DEATH);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_MARK_OF_THE_FALLEN_CHAMPION);
             if (Creature* creature = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SAURFANG_EVENT_NPC)))
                 creature->AI()->DoAction(ACTION_START_OUTRO);
         }
References BossAI::_JustDied(), ACTION_START_OUTRO, DATA_SAURFANG_EVENT_NPC, UnitAI::DoCast(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, SAY_DEATH, SPELL_ACHIEVEMENT, SPELL_MARK_OF_THE_FALLEN_CHAMPION, and CreatureAI::Talk().
JustReachedHome()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 334 of file boss_deathbringer_saurfang.cpp.
         {
             _JustReachedHome();
             instance->SetBossState(DATA_DEATHBRINGER_SAURFANG, FAIL);
         }
References BossAI::_JustReachedHome(), DATA_DEATHBRINGER_SAURFANG, FAIL, BossAI::instance, and InstanceScript::SetBossState().
JustSummoned()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 356 of file boss_deathbringer_saurfang.cpp.
         {
             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true))
                 summon->AI()->AttackStart(target);
             //if (IsHeroic())
             //    DoCast(summon, SPELL_SCENT_OF_BLOOD);
             summon->AI()->DoCast(summon, SPELL_BLOOD_LINK_BEAST, true);
             summon->AI()->DoCast(summon, SPELL_RESISTANT_SKIN, true);
             summons.Summon(summon);
             DoZoneInCombat(summon);
         }
References Creature::AI(), UnitAI::AttackStart(), UnitAI::DoCast(), CreatureAI::DoZoneInCombat(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BLOOD_LINK_BEAST, SPELL_RESISTANT_SKIN, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 340 of file boss_deathbringer_saurfang.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 332 of file boss_deathbringer_saurfang.cpp.
 {}
MovementInform()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 375 of file boss_deathbringer_saurfang.cpp.
         {
             if (type != POINT_MOTION_TYPE && id != POINT_SAURFANG)
                 return;
             instance->HandleGameObject(instance->GetGuidData(GO_SAURFANG_S_DOOR), false);
         }
References InstanceScript::GetGuidData(), GO_SAURFANG_S_DOOR, InstanceScript::HandleGameObject(), BossAI::instance, POINT_MOTION_TYPE, and POINT_SAURFANG.
Reset()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 251 of file boss_deathbringer_saurfang.cpp.
         {
             _Reset();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NOT_SELECTABLE);
             me->SetReactState(REACT_DEFENSIVE);
             events.Reset();
             _introDone = false;
             _frenzied = false;
             _fallenChampionCastCount = 0;
             _transportCheckTimer = 1000;
             me->SetPower(POWER_ENERGY, 0);
             DoCast(me, SPELL_ZERO_POWER, true);
             DoCast(me, SPELL_BLOOD_LINK, true);
             DoCast(me, SPELL_BLOOD_POWER, true);
             DoCast(me, SPELL_MARK_OF_THE_FALLEN_CHAMPION_S, true);
             DoCast(me, SPELL_RUNE_OF_BLOOD_S, true);
             me->RemoveAurasDueToSpell(SPELL_BERSERK);
             me->RemoveAurasDueToSpell(SPELL_FRENZY);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_MARK_OF_THE_FALLEN_CHAMPION);
         }
References _fallenChampionCastCount, _frenzied, _introDone, BossAI::_Reset(), _transportCheckTimer, UnitAI::DoCast(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, ScriptedAI::me, POWER_ENERGY, REACT_DEFENSIVE, Unit::RemoveAurasDueToSpell(), Object::SetFlag(), Unit::SetPower(), Creature::SetReactState(), SPELL_BERSERK, SPELL_BLOOD_LINK, SPELL_BLOOD_POWER, SPELL_FRENZY, SPELL_MARK_OF_THE_FALLEN_CHAMPION, SPELL_MARK_OF_THE_FALLEN_CHAMPION_S, SPELL_RUNE_OF_BLOOD_S, SPELL_ZERO_POWER, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_FLAG_NOT_SELECTABLE.
SpellHitTarget()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SpellHitTarget (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 383 of file boss_deathbringer_saurfang.cpp.
         {
             switch (spell->Id)
             {
                 case SPELL_MARK_OF_THE_FALLEN_CHAMPION:
                     Talk(SAY_MARK_OF_THE_FALLEN_CHAMPION);
                     break;
             }
         }
References SpellInfo::Id, SAY_MARK_OF_THE_FALLEN_CHAMPION, SPELL_MARK_OF_THE_FALLEN_CHAMPION, and CreatureAI::Talk().
SummonedCreatureDespawn()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 370 of file boss_deathbringer_saurfang.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and BossAI::summons.
UpdateAI()
void boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 393 of file boss_deathbringer_saurfang.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (_transportCheckTimer <= diff)
             {
                 _transportCheckTimer = 1000;
                 Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                 for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                     if (Player* p = itr->GetSource())
                         if (p->GetTransport())
{
                             EnterEvadeMode();
                             return;
                         }
             }
             else
                 _transportCheckTimer -= diff;
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SUMMON_BLOOD_BEAST:
                         for (uint32 i10 = 0; i10 < 2; ++i10)
                             DoCast(me, SPELL_SUMMON_BLOOD_BEAST + i10);
                         if (Is25ManRaid())
                             for (uint32 i25 = 0; i25 < 3; ++i25)
                                 DoCast(me, SPELL_SUMMON_BLOOD_BEAST_25_MAN + i25);
                         Talk(SAY_BLOOD_BEASTS);
                         events.ScheduleEvent(EVENT_SUMMON_BLOOD_BEAST, 40000);
                         if (IsHeroic())
                             events.ScheduleEvent(EVENT_BLOOD_BEAST_SCENT_OF_BLOOD, 10000);
                         break;
                     case EVENT_BLOOD_BEAST_SCENT_OF_BLOOD:
                         Talk(EMOTE_SCENT_OF_BLOOD);
                         summons.DoAction(ACTION_GAIN_SCENT_OF_BLOOD);
                         break;
                     case EVENT_BLOOD_NOVA:
{
                             me->CastSpell((Unit*)nullptr, SPELL_BLOOD_NOVA_TRIGGER, false);
                             events.ScheduleEvent(EVENT_BLOOD_NOVA, urand(20000, 25000));
                             break;
                         }
                     case EVENT_RUNE_OF_BLOOD:
                         DoCastVictim(SPELL_RUNE_OF_BLOOD);
                         events.ScheduleEvent(EVENT_RUNE_OF_BLOOD, urand(20000, 25000));
                         break;
                     case EVENT_BOILING_BLOOD:
                         me->CastSpell((Unit*)nullptr, SPELL_BOILING_BLOOD, false);
                         events.ScheduleEvent(EVENT_BOILING_BLOOD, urand(15000, 20000));
                         break;
                     case EVENT_BERSERK:
                         DoCast(me, SPELL_BERSERK);
                         Talk(SAY_BERSERK);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _transportCheckTimer, ACTION_GAIN_SCENT_OF_BLOOD, MapRefMgr::begin(), Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_SCENT_OF_BLOOD, MapRefMgr::end(), EnterEvadeMode(), EVENT_BERSERK, EVENT_BLOOD_BEAST_SCENT_OF_BLOOD, EVENT_BLOOD_NOVA, EVENT_BOILING_BLOOD, EVENT_RUNE_OF_BLOOD, EVENT_SUMMON_BLOOD_BEAST, WorldObject::GetMap(), Map::GetPlayers(), Unit::HasUnitState(), ScriptedAI::Is25ManRaid(), ScriptedAI::IsHeroic(), ScriptedAI::me, SAY_BERSERK, SAY_BLOOD_BEASTS, SPELL_BERSERK, SPELL_BLOOD_NOVA_TRIGGER, SPELL_BOILING_BLOOD, SPELL_RUNE_OF_BLOOD, SPELL_SUMMON_BLOOD_BEAST, SPELL_SUMMON_BLOOD_BEAST_25_MAN, BossAI::summons, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_fallenChampionCastCount
uint32 boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::_fallenChampionCastCount private
Definition at line 506 of file boss_deathbringer_saurfang.cpp.
Referenced by DoAction(), EnterCombat(), GetData(), and Reset().
_frenzied
bool boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::_frenzied private
Definition at line 508 of file boss_deathbringer_saurfang.cpp.
Referenced by DamageTaken(), and Reset().
_introDone
bool boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::_introDone private
Definition at line 507 of file boss_deathbringer_saurfang.cpp.
Referenced by AttackStart(), CanAIAttack(), DoAction(), EnterCombat(), and Reset().
_transportCheckTimer
uint16 boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::_transportCheckTimer private
Definition at line 509 of file boss_deathbringer_saurfang.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp