Azerotcore-wotlk: npc_fairbanks Class Reference
npc_fairbanks Class Reference
Classes
struct npc_fairbanksAI
Public Member Functions
npc_fairbanks ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 663 of file instance_scarlet_monastery.cpp.
Constructor & Destructor Documentation
npc_fairbanks()
npc_fairbanks::npc_fairbanks () inline
Definition at line 666 of file instance_scarlet_monastery.cpp.
 : CreatureScript("npc_fairbanks") { }
Member Function Documentation
GetAI()
CreatureAI* npc_fairbanks::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 798 of file instance_scarlet_monastery.cpp.
     {
         return GetScarletMonasteryAI<npc_fairbanksAI>(creature);
     }
OnGossipHello()
bool npc_fairbanks::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 668 of file instance_scarlet_monastery.cpp.
     {
         AddGossipItemFor(player, 0, "Curse? What's going on here, Fairbanks?", GOSSIP_SENDER_MAIN, 1);
         SendGossipMenuFor(player, 100100, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_fairbanks::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 675 of file instance_scarlet_monastery.cpp.
     {
         ClearGossipMenuFor(player);
         switch (uiAction)
         {
             case 1:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "Mograine?", GOSSIP_SENDER_MAIN, 2);
                 SendGossipMenuFor(player, 100101, creature->GetGUID());
                 return true;
             case 2:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "What do you mean?", GOSSIP_SENDER_MAIN, 3);
                 SendGossipMenuFor(player, 100102, creature->GetGUID());
                 return true;
             case 3:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "I still do not fully understand.", GOSSIP_SENDER_MAIN, 4);
                 SendGossipMenuFor(player, 100103, creature->GetGUID());
                 return true;
             case 4:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "Incredible story. So how did he die?", GOSSIP_SENDER_MAIN, 5);
                 SendGossipMenuFor(player, 100104, creature->GetGUID());
                 return true;
             case 5:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "You mean...", GOSSIP_SENDER_MAIN, 6);
                 SendGossipMenuFor(player, 100105, creature->GetGUID());
                 return true;
             case 6:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "How do you know all of this?", GOSSIP_SENDER_MAIN, 7);
                 SendGossipMenuFor(player, 100106, creature->GetGUID());
                 return true;
             case 7:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "A thousand? For one man?", GOSSIP_SENDER_MAIN, 8);
                 SendGossipMenuFor(player, 100107, creature->GetGUID());
                 return true;
             case 8:
                 creature->HandleEmoteCommand(5);
                 AddGossipItemFor(player, 0, "Yet? Yet what?", GOSSIP_SENDER_MAIN, 9);
                 SendGossipMenuFor(player, 100108, creature->GetGUID());
                 return true;
             case 9:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "And did he?", GOSSIP_SENDER_MAIN, 10);
                 SendGossipMenuFor(player, 100109, creature->GetGUID());
                 return true;
             case 10:
                 creature->HandleEmoteCommand(274);
                 AddGossipItemFor(player, 0, "Continue please, Fairbanks.", GOSSIP_SENDER_MAIN, 11);
                 SendGossipMenuFor(player, 100110, creature->GetGUID());
                 return true;
             case 11:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "You mean...", GOSSIP_SENDER_MAIN, 12);
                 SendGossipMenuFor(player, 100111, creature->GetGUID());
                 return true;
             case 12:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "You were right, Fairbanks. That is tragic.", GOSSIP_SENDER_MAIN, 13);
                 SendGossipMenuFor(player, 100112, creature->GetGUID());
                 return true;
             case 13:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "And you did...", GOSSIP_SENDER_MAIN, 14);
                 SendGossipMenuFor(player, 100113, creature->GetGUID());
                 return true;
             case 14:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "You tell an incredible tale, Fairbanks. What of the blade? Is it beyond redemption?", GOSSIP_SENDER_MAIN, 15);
                 SendGossipMenuFor(player, 100114, creature->GetGUID());
                 return true;
             case 15:
                 creature->HandleEmoteCommand(1);
                 AddGossipItemFor(player, 0, "But his son is dead.", GOSSIP_SENDER_MAIN, 16);
                 SendGossipMenuFor(player, 100115, creature->GetGUID());
                 return true;
             case 16:
                 SendGossipMenuFor(player, 100116, creature->GetGUID());
                 // todo: we need to play these 3 emote in sequence, we play only the last one right now.
                 creature->HandleEmoteCommand(274);
                 creature->HandleEmoteCommand(1);
                 creature->HandleEmoteCommand(397);
                 return true;
         }
         return true;
     }
References AddGossipItemFor(), ClearGossipMenuFor(), Object::GetGUID(), GOSSIP_SENDER_MAIN, Unit::HandleEmoteCommand(), and SendGossipMenuFor().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp