Azerotcore-wotlk: npc_eye_of_acherus::npc_eye_of_acherusAI Struct Reference
npc_eye_of_acherus::npc_eye_of_acherusAI Struct Reference
Public Member Functions
npc_eye_of_acherusAI (Creature *creature)
void InitializeAI () override
void MovementInform (uint32 type, uint32 point) override
void SetControl (Player *player, bool on)
void JustSummoned (Creature *creature) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 58 of file chapter1.cpp.
Constructor & Destructor Documentation
npc_eye_of_acherusAI()
npc_eye_of_acherus::npc_eye_of_acherusAI::npc_eye_of_acherusAI (Creature * creature) inline
Definition at line 60 of file chapter1.cpp.
 : NullCreatureAI(creature) { }
Member Function Documentation
InitializeAI()
void npc_eye_of_acherus::npc_eye_of_acherusAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 64 of file chapter1.cpp.
         {
             events.Reset();
             events.ScheduleEvent(EVENT_REMOVE_CONTROL, 500);
             events.ScheduleEvent(EVENT_SPEAK_1, 4000);
             events.ScheduleEvent(EVENT_LAUNCH, 7000);
             me->CastSpell(me, SPELL_EYE_OF_ACHERUS_VISUAL, true);
         }
References Unit::CastSpell(), EVENT_LAUNCH, EVENT_REMOVE_CONTROL, EVENT_SPEAK_1, CreatureAI::me, and SPELL_EYE_OF_ACHERUS_VISUAL.
JustSummoned()
void npc_eye_of_acherus::npc_eye_of_acherusAI::JustSummoned (Creature * creature) inline override virtual
Reimplemented from CreatureAI.
Definition at line 91 of file chapter1.cpp.
         {
             if (Unit* target = creature->SelectNearbyTarget())
                 creature->AI()->AttackStart(target);
         }
References Creature::AI(), UnitAI::AttackStart(), and Unit::SelectNearbyTarget().
MovementInform()
void npc_eye_of_acherus::npc_eye_of_acherusAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from CreatureAI.
Definition at line 75 of file chapter1.cpp.
         {
             if (type == POINT_MOTION_TYPE && point == EYE_POINT_DESTINATION_2)
             {
                 events.ScheduleEvent(EVENT_REGAIN_CONTROL, 1000);
             }
         }
References EVENT_REGAIN_CONTROL, EYE_POINT_DESTINATION_2, and POINT_MOTION_TYPE.
SetControl()
void npc_eye_of_acherus::npc_eye_of_acherusAI::SetControl (Player * player, bool on) inline
Definition at line 83 of file chapter1.cpp.
         {
             WorldPacket data(SMSG_CLIENT_CONTROL_UPDATE, me->GetPackGUID().size() + 1);
             data << me->GetPackGUID();
             data << uint8(on ? 1 : 0);
             player->GetSession()->SendPacket(&data);
         }
References Object::GetPackGUID(), Player::GetSession(), CreatureAI::me, WorldSession::SendPacket(), PackedGuid::size(), and SMSG_CLIENT_CONTROL_UPDATE.
Referenced by UpdateAI().
UpdateAI()
void npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 97 of file chapter1.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_REMOVE_CONTROL:
                     if (Player* player = me->GetCharmerOrOwnerPlayerOrPlayerItself())
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED);
                         SetControl(player, false);
                     }
                     break;
                 case EVENT_SPEAK_1:
                     Talk(EYE_TEXT_LAUNCH, me->GetCharmerOrOwnerPlayerOrPlayerItself());
                     break;
                 case EVENT_LAUNCH:
                     {
                         me->SetSpeed(MOVE_FLIGHT, 5.0f, true);
                         const Position EYE_DESTINATION_1 = { me->GetPositionX() - 40.0f, me->GetPositionY(), me->GetPositionZ() + 10.0f, 0.0f };
                         const Position EYE_DESTINATION_2 = { 1768.0f, -5876.0f, 153.0f, 0.0f };
                         me->GetMotionMaster()->MovePoint(EYE_POINT_DESTINATION_1, EYE_DESTINATION_1);
                         me->GetMotionMaster()->MovePoint(EYE_POINT_DESTINATION_2, EYE_DESTINATION_2);
                         break;
                     }
                 case EVENT_REGAIN_CONTROL:
                     if (Player* player = me->GetCharmerOrOwnerPlayerOrPlayerItself())
                     {
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED);
                         me->SetSpeed(MOVE_FLIGHT, 3.3f, true);
                         SetControl(player, true);
                         Talk(EYE_TEXT_CONTROL, player);
                     }
                     break;
             }
         }
References EVENT_LAUNCH, EVENT_REGAIN_CONTROL, EVENT_REMOVE_CONTROL, EVENT_SPEAK_1, EYE_POINT_DESTINATION_1, EYE_POINT_DESTINATION_2, EYE_TEXT_CONTROL, EYE_TEXT_LAUNCH, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), Object::RemoveFlag(), SetControl(), Object::SetFlag(), Unit::SetSpeed(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_STUNNED.
Member Data Documentation
events
EventMap npc_eye_of_acherus::npc_eye_of_acherusAI::events
Definition at line 62 of file chapter1.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp