Azerotcore-wotlk: npc_image_of_medivh::npc_image_of_medivhAI Struct Reference
npc_image_of_medivh::npc_image_of_medivhAI Struct Reference
Public Member Functions
npc_image_of_medivhAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
uint32 NextStep (uint32 nextStep)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid ArcanagosGUID
uint32 YellTimer
uint8 Step
int32 MTimer
int32 ATimer
bool EventStarted
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 438 of file karazhan.cpp.
Constructor & Destructor Documentation
npc_image_of_medivhAI()
npc_image_of_medivh::npc_image_of_medivhAI::npc_image_of_medivhAI (Creature * creature) inline
Definition at line 440 of file karazhan.cpp.
                                                   : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             Step = 1;
             YellTimer = 5000;
         }
References WorldObject::GetInstanceScript(), instance, Step, and YellTimer.
Member Function Documentation
EnterCombat()
void npc_image_of_medivh::npc_image_of_medivhAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 486 of file karazhan.cpp.
 {}
NextStep()
uint32 npc_image_of_medivh::npc_image_of_medivhAI::NextStep (uint32 nextStep) inline
Definition at line 488 of file karazhan.cpp.
         {
             switch(nextStep)
             {
                 case 1:
                     me->Yell(SAY_DIALOG_MEDIVH_1, LANG_UNIVERSAL);
                     return 10000;
                 case 2:
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         arca->Yell(SAY_DIALOG_ARCANAGOS_2, LANG_UNIVERSAL);
                     return 20000;
                 case 3:
                     me->Yell(SAY_DIALOG_MEDIVH_3, LANG_UNIVERSAL);
                     return 10000;
                 case 4:
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         arca->Yell(SAY_DIALOG_ARCANAGOS_4, LANG_UNIVERSAL);
                     return 20000;
                 case 5:
                     me->Yell(SAY_DIALOG_MEDIVH_5, LANG_UNIVERSAL);
                     return 20000;
                 case 6:
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         arca->Yell(SAY_DIALOG_ARCANAGOS_6, LANG_UNIVERSAL);
                     ATimer = 5500;
                     MTimer = 6600;
                     return 10000;
                 case 7:
                     return 1000;
                 case 8:
                     me->CastSpell(me, SPELL_MANA_SHIELD, true);
                     return 5500;
                 case 9:
                     me->TextEmote(EMOTE_DIALOG_MEDIVH_7);
                     me->CastSpell(me, 30972, true);
                     return 10000;
                 case 10:
                     me->RemoveAurasDueToSpell(30972);
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         me->CastSpell(arca, SPELL_CONFLAGRATION_BLAST, false);
                     return 1000;
                 case 11:
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         arca->Yell(SAY_DIALOG_ARCANAGOS_8, LANG_UNIVERSAL);
                     return 5000;
                 case 12:
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                     {
                         arca->SetSpeed(MOVE_RUN, 2.0f);
                         arca->GetMotionMaster()->MovePoint(0, -11010.82f, -1761.18f, 156.47f);
                         arca->InterruptNonMeleeSpells(true);
                     }
                     return 10000;
                 case 13:
                     me->Yell(SAY_DIALOG_MEDIVH_9, LANG_UNIVERSAL);
                     return 10000;
                 case 14:
                     if (me->GetMap()->IsDungeon())
                     {
                         InstanceMap::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                         for (InstanceMap::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
{
                             if (i->GetSource()->GetQuestStatus(9645) == QUEST_STATUS_INCOMPLETE)
{
                                 i->GetSource()->GroupEventHappens(9645, me);
                                 break;
                             }
                         }
                     }
                     me->DespawnOrUnsummon(100);
                     if (Creature* arca = ObjectAccessor::GetCreature((*me), ArcanagosGUID))
                         arca->DespawnOrUnsummon(100);
                     return 5000;
                 default:
                     return 2000;
             }
         }
References ArcanagosGUID, ATimer, MapRefMgr::begin(), Unit::CastSpell(), Creature::DespawnOrUnsummon(), EMOTE_DIALOG_MEDIVH_7, MapRefMgr::end(), ObjectAccessor::GetCreature(), WorldObject::GetMap(), Map::GetPlayers(), Map::IsDungeon(), LANG_UNIVERSAL, ScriptedAI::me, MOVE_RUN, MTimer, QUEST_STATUS_INCOMPLETE, Unit::RemoveAurasDueToSpell(), SAY_DIALOG_ARCANAGOS_2, SAY_DIALOG_ARCANAGOS_4, SAY_DIALOG_ARCANAGOS_6, SAY_DIALOG_ARCANAGOS_8, SAY_DIALOG_MEDIVH_1, SAY_DIALOG_MEDIVH_3, SAY_DIALOG_MEDIVH_5, SAY_DIALOG_MEDIVH_9, SPELL_CONFLAGRATION_BLAST, SPELL_MANA_SHIELD, Unit::TextEmote(), and Unit::Yell().
Referenced by UpdateAI().
Reset()
void npc_image_of_medivh::npc_image_of_medivhAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 458 of file karazhan.cpp.
         {
             ArcanagosGUID.Clear();
             MTimer = 0;
             ATimer = 0;
             if (instance && !instance->GetGuidData(DATA_IMAGE_OF_MEDIVH))
             {
                 Creature* Arcanagos = me->SummonCreature(NPC_ARCANAGOS, ArcanagosPos[0], ArcanagosPos[1], ArcanagosPos[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000);
                 if (!Arcanagos)
                 {
                     me->DespawnOrUnsummon();
                     return;
                 }
                 instance->SetGuidData(DATA_IMAGE_OF_MEDIVH, me->GetGUID());
                 EventStarted = true;
                 ArcanagosGUID = Arcanagos->GetGUID();
                 Arcanagos->SetFacingToObject(me);
                 me->SetFacingToObject(Arcanagos);
                 Arcanagos->SetCanFly(true);
             }
             else
                 me->DespawnOrUnsummon();
         }
References ArcanagosGUID, ArcanagosPos, ATimer, ObjectGuid::Clear(), DATA_IMAGE_OF_MEDIVH, Creature::DespawnOrUnsummon(), EventStarted, Object::GetGUID(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, MTimer, NPC_ARCANAGOS, Creature::SetCanFly(), Unit::SetFacingToObject(), ZoneScript::SetGuidData(), WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
UpdateAI()
void npc_image_of_medivh::npc_image_of_medivhAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 569 of file karazhan.cpp.
         {
             if (YellTimer <= diff)
             {
                 if (EventStarted)
                     YellTimer = NextStep(Step++);
             }
             else YellTimer -= diff;
             if (Step >= 7 && Step <= 8)
             {
                 ATimer += diff;
                 MTimer += diff;
                 if (ATimer >= 6000)
                 {
                     if (Unit* arca = ObjectAccessor::GetUnit((*me), ArcanagosGUID))
                         arca->CastSpell(me, SPELL_FIRE_BALL, false);
                     ATimer = 0;
                 }
                 if (MTimer >= 6000)
                 {
                     if (Unit* arca = ObjectAccessor::GetUnit((*me), ArcanagosGUID))
                         me->CastSpell(arca, SPELL_FIRE_BALL, false);
                     MTimer = 0;
                 }
             }
         }
References ArcanagosGUID, ATimer, Unit::CastSpell(), EventStarted, ObjectAccessor::GetUnit(), ScriptedAI::me, MTimer, NextStep(), SPELL_FIRE_BALL, Step, and YellTimer.
Member Data Documentation
ArcanagosGUID
ObjectGuid npc_image_of_medivh::npc_image_of_medivhAI::ArcanagosGUID
Definition at line 449 of file karazhan.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
ATimer
int32 npc_image_of_medivh::npc_image_of_medivhAI::ATimer
Definition at line 454 of file karazhan.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
EventStarted
bool npc_image_of_medivh::npc_image_of_medivhAI::EventStarted
Definition at line 456 of file karazhan.cpp.
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* npc_image_of_medivh::npc_image_of_medivhAI::instance
Definition at line 447 of file karazhan.cpp.
Referenced by npc_image_of_medivhAI(), and Reset().
MTimer
int32 npc_image_of_medivh::npc_image_of_medivhAI::MTimer
Definition at line 453 of file karazhan.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
Step
uint8 npc_image_of_medivh::npc_image_of_medivhAI::Step
Definition at line 452 of file karazhan.cpp.
Referenced by npc_image_of_medivhAI(), and UpdateAI().
YellTimer
uint32 npc_image_of_medivh::npc_image_of_medivhAI::YellTimer
Definition at line 451 of file karazhan.cpp.
Referenced by npc_image_of_medivhAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp