Azerotcore-wotlk: G3D::LineSegment Class Reference
G3D::LineSegment Class Reference
#include <LineSegment.h>
Public Member Functions
LineSegment ()
LineSegment (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
virtual ~LineSegment ()
Point3 point (int i) const
Point3 midpoint () const
float length () const
Point3 closestPoint (const Point3 &point) const
double distance (const Point3 &p) const
double distanceSquared (const Point3 &p) const
bool intersectsSolidSphere (const class Sphere &s) const
Point3 randomPoint () const
Static Public Member Functions
static LineSegment fromTwoPoints (const Point3 &point1, const Point3 &point2)
Protected Member Functions
LineSegment (const Point3 &__point, const Vector3 &_direction)
Protected Attributes
Point3 _point
Vector3 direction
Detailed Description
An finite segment of an infinite 3D line.
Definition at line 21 of file LineSegment.h.
Constructor & Destructor Documentation
LineSegment() [1/3]
G3D::LineSegment::LineSegment (const Point3 & __point, const Vector3 & _direction) inline protected
Definition at line 29 of file LineSegment.h.
                                                                   : _point(__point), direction(_direction) {
     }
LineSegment() [2/3]
G3D::LineSegment::LineSegment () inline
Definition at line 34 of file LineSegment.h.
 : _point(Point3::zero()), direction(Vector3::zero()) {}
Referenced by fromTwoPoints().
LineSegment() [3/3]
G3D::LineSegment::LineSegment (class BinaryInput & b)
Definition at line 82 of file LineSegment.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
~LineSegment()
virtual G3D::LineSegment::~LineSegment () inline virtual
Definition at line 42 of file LineSegment.h.
 {}
Member Function Documentation
closestPoint()
Vector3 G3D::LineSegment::closestPoint (const Point3 & point) const
Returns the closest point on the line segment to point.
Definition at line 18 of file LineSegment.cpp.
{
     // The vector from the end of the capsule to the point in question.
     Vector3 v(p - _point);
     // Projection of v onto the line segment scaled by
     // the length of direction.
     float t = direction.dot(v);
     // Avoid some square roots.  Derivation:
     //    t/direction.length() <= direction.length()
     //      t <= direction.squaredLength()
     if ((t >= 0) && (t <= direction.squaredMagnitude())) {
         // The point falls within the segment.  Normalize direction,
         // divide t by the length of direction.
         return _point + direction * t / direction.squaredMagnitude();
     } else {
         // The point does not fall within the segment; see which end is closer.
         // Distance from 0, squared
         float d0Squared = v.squaredMagnitude();
         // Distance from 1, squared
         float d1Squared = (v - direction).squaredMagnitude();
         if (d0Squared < d1Squared) {
             // Point 0 is closer
             return _point;
         } else {
             // Point 1 is closer
             return _point + direction;
         }
     }
 }
References _point, direction, G3D::Vector3::dot(), and G3D::Vector3::squaredMagnitude().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), distance(), and distanceSquared().
deserialize()
void G3D::LineSegment::deserialize (class BinaryInput & b)
Definition at line 93 of file LineSegment.cpp.
{
     _point.deserialize(b);
     direction.deserialize(b);
 }
References _point, b, G3D::Vector3::deserialize(), and direction.
Referenced by LineSegment().
distance()
double G3D::LineSegment::distance (const Point3 & p) const inline
Returns the distance between point and the line
Definition at line 70 of file LineSegment.h.
{
         return (closestPoint(p) - p).magnitude();
     }
References closestPoint().
distanceSquared()
double G3D::LineSegment::distanceSquared (const Point3 & p) const inline
Definition at line 74 of file LineSegment.h.
{
         return (closestPoint(p) - p).squaredMagnitude();
     }
References closestPoint().
Referenced by G3D::Capsule::contains(), G3D::Cylinder::contains(), and intersectsSolidSphere().
fromTwoPoints()
static LineSegment G3D::LineSegment::fromTwoPoints (const Point3 & point1, const Point3 & point2) inline static
Constructs a line from two (not equal) points.
Definition at line 47 of file LineSegment.h.
{
         return LineSegment(point1, point2 - point1);
     }
References LineSegment().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), G3D::Capsule::contains(), and G3D::Cylinder::contains().
intersectsSolidSphere()
bool G3D::LineSegment::intersectsSolidSphere (const class Sphere & s) const
Returns true if some part of this segment is inside the sphere
Definition at line 77 of file LineSegment.cpp.
{
     return distanceSquared(s.center) <= square(s.radius);
 }
References G3D::Sphere::center, distanceSquared(), G3D::Sphere::radius, and G3D::square().
length()
float G3D::LineSegment::length () const inline
Definition at line 58 of file LineSegment.h.
{
         return direction.magnitude();
     }
References direction, and G3D::Vector3::magnitude().
midpoint()
Point3 G3D::LineSegment::midpoint () const inline
Definition at line 54 of file LineSegment.h.
{
         return _point + direction * 0.5f;
     }
References _point, and direction.
point()
Vector3 G3D::LineSegment::point (int i) const
Call with 0 or 1
Definition at line 62 of file LineSegment.cpp.
{
     switch (i) {
     case 0:
         return _point;
     case 1:
         return _point + direction;
     default:
         debugAssertM(i == 0 || i == 1, "Argument to point must be 0 or 1");
         return _point;
     }
 }
References _point, debugAssertM, and direction.
randomPoint()
Vector3 G3D::LineSegment::randomPoint () const
Definition at line 99 of file LineSegment.cpp.
{
     return _point + uniformRandom(0, 1) * direction;
 }
References _point, direction, and G3D::uniformRandom().
serialize()
void G3D::LineSegment::serialize (class BinaryOutput & b) const
Definition at line 87 of file LineSegment.cpp.
{
     _point.serialize(b);
     direction.serialize(b);
 }
References _point, b, direction, and G3D::Vector3::serialize().
Member Data Documentation
_point
Point3 G3D::LineSegment::_point protected
Definition at line 24 of file LineSegment.h.
Referenced by closestPoint(), deserialize(), midpoint(), point(), randomPoint(), and serialize().
direction
Vector3 G3D::LineSegment::direction protected
Not normalized
Definition at line 27 of file LineSegment.h.
Referenced by closestPoint(), deserialize(), length(), midpoint(), point(), randomPoint(), and serialize().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/LineSegment.h
deps/g3dlite/source/LineSegment.cpp