Azerotcore-wotlk: npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI Struct Reference
npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI Struct Reference
Public Member Functions
npc_valkyr_battle_maidenAI (Creature *creature)
void Reset () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from PassiveAI
PassiveAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 FlyBackTimer
float x
float y
float z
uint32 phase
Additional Inherited Members
Static Public Member Functions inherited from PassiveAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 47 of file zone_the_scarlet_enclave.cpp.
Constructor & Destructor Documentation
npc_valkyr_battle_maidenAI()
npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::npc_valkyr_battle_maidenAI (Creature * creature) inline
Definition at line 49 of file zone_the_scarlet_enclave.cpp.
 : PassiveAI(creature) { }
Member Function Documentation
Reset()
void npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 55 of file zone_the_scarlet_enclave.cpp.
         {
             me->setActive(true);
             me->SetVisible(false);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetCanFly(true);
             FlyBackTimer = 500;
             phase = 0;
             me->GetPosition(x, y, z);
             z += 4.0f;
             x -= 3.5f;
             y -= 5.0f;
             me->GetMotionMaster()->Clear(false);
             me->SetPosition(x, y, z, 0.0f);
         }
References MotionMaster::Clear(), FlyBackTimer, Unit::GetMotionMaster(), Position::GetPosition(), CreatureAI::me, WorldObject::setActive(), Creature::SetCanFly(), Object::SetFlag(), Creature::SetPosition(), Unit::SetVisible(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, x, y, and z.
UpdateAI()
void npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from PassiveAI.
Definition at line 72 of file zone_the_scarlet_enclave.cpp.
         {
             if (FlyBackTimer <= diff)
             {
                 Player* player = nullptr;
                 if (me->IsSummon())
                 {
                     if (Unit * summoner = me->ToTempSummon()->GetSummonerUnit())
                     {
                         player = summoner->ToPlayer();
                     }
                 }
                 if (!player)
                 {
                     phase = 3;
                 }
                 switch (phase)
                 {
                     case 0:
                         me->SetWalk(false);
                         me->HandleEmoteCommand(EMOTE_STATE_FLYGRABCLOSED);
                         FlyBackTimer = 500;
                         break;
                     case 1:
                         if (player)
{
                             player->GetClosePoint(x, y, z, me->GetObjectSize());
                         }
                         z += 2.5f;
                         x -= 2.0f;
                         y -= 1.5f;
                         me->GetMotionMaster()->MovePoint(0, x, y, z);
                         if (player)
{
                             me->SetTarget(player->GetGUID());
                         }
                         me->SetVisible(true);
                         FlyBackTimer = 4500;
                         break;
                     case 2:
                         if (player && !player->isResurrectRequested())
{
                             me->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_01);
                             DoCast(player, SPELL_REVIVE, true);
                             Talk(WHISPER_REVIVE, player);
                         }
                         FlyBackTimer = 5000;
                         break;
                     case 3:
                         me->SetVisible(false);
                         FlyBackTimer = 3000;
                         break;
                     case 4:
                         me->DisappearAndDie();
                         break;
                     default:
                         //Nothing To DO
                         break;
                 }
                 ++phase;
             }
             else FlyBackTimer -= diff;
         }
References Creature::DisappearAndDie(), UnitAI::DoCast(), EMOTE_ONESHOT_CUSTOM_SPELL_01, EMOTE_STATE_FLYGRABCLOSED, FlyBackTimer, WorldObject::GetClosePoint(), Object::GetGUID(), Unit::GetMotionMaster(), WorldObject::GetObjectSize(), TempSummon::GetSummonerUnit(), Unit::HandleEmoteCommand(), Player::isResurrectRequested(), Unit::IsSummon(), CreatureAI::me, MotionMaster::MovePoint(), phase, Creature::SetTarget(), Unit::SetVisible(), Creature::SetWalk(), SPELL_REVIVE, CreatureAI::Talk(), Object::ToPlayer(), Unit::ToTempSummon(), WHISPER_REVIVE, x, y, and z.
Member Data Documentation
FlyBackTimer
uint32 npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::FlyBackTimer
Definition at line 51 of file zone_the_scarlet_enclave.cpp.
Referenced by Reset(), and UpdateAI().
phase
uint32 npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::phase
Definition at line 53 of file zone_the_scarlet_enclave.cpp.
Referenced by UpdateAI().
x
float npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::x
Definition at line 52 of file zone_the_scarlet_enclave.cpp.
Referenced by Reset(), and UpdateAI().
y
float npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::y
Definition at line 52 of file zone_the_scarlet_enclave.cpp.
Referenced by Reset(), and UpdateAI().
z
float npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::z
Definition at line 52 of file zone_the_scarlet_enclave.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/zone_the_scarlet_enclave.cpp