Azerotcore-wotlk: deps/mysqllite/include/keycache.h File Reference
keycache.h File Reference
#include "my_sys.h"
Classes
struct st_keycache_wqueue
struct st_key_cache
Macros
#define CHANGED_BLOCKS_HASH 128 /* must be power of 2 */
Typedefs
typedef struct st_block_link BLOCK_LINK
typedef struct st_keycache_page KEYCACHE_PAGE
typedef struct st_hash_link HASH_LINK
typedef struct st_keycache_wqueue KEYCACHE_WQUEUE
typedef struct st_key_cache KEY_CACHE
Functions
int init_key_cache (KEY_CACHE *keycache, uint key_cache_block_size, size_t use_mem, uint division_limit, uint age_threshold)
int resize_key_cache (KEY_CACHE *keycache, uint key_cache_block_size, size_t use_mem, uint division_limit, uint age_threshold)
void change_key_cache_param (KEY_CACHE *keycache, uint division_limit, uint age_threshold)
uchar * key_cache_read (KEY_CACHE *keycache, File file, my_off_t filepos, int level, uchar *buff, uint length, uint block_length, int return_buffer)
int key_cache_insert (KEY_CACHE *keycache, File file, my_off_t filepos, int level, uchar *buff, uint length)
int key_cache_write (KEY_CACHE *keycache, File file, my_off_t filepos, int level, uchar *buff, uint length, uint block_length, int force_write)
int flush_key_blocks (KEY_CACHE *keycache, int file, enum flush_type type)
void end_key_cache (KEY_CACHE *keycache, my_bool cleanup)
my_bool multi_keycache_init (void)
void multi_keycache_free (void)
KEY_CACHE * multi_key_cache_search (uchar *key, uint length)
my_bool multi_key_cache_set (const uchar *key, uint length, KEY_CACHE *key_cache)
void multi_key_cache_change (KEY_CACHE *old_data, KEY_CACHE *new_data)
int reset_key_cache_counters (const char *name, KEY_CACHE *key_cache)
Variables
KEY_CACHE dflt_key_cache_var
KEY_CACHE * dflt_key_cache
Macro Definition Documentation
CHANGED_BLOCKS_HASH
#define CHANGED_BLOCKS_HASH 128 /* must be power of 2 */
Definition at line 40 of file keycache.h.
Typedef Documentation
BLOCK_LINK
typedef struct st_block_link BLOCK_LINK
Definition at line 23 of file keycache.h.
HASH_LINK
typedef struct st_hash_link HASH_LINK
Definition at line 23 of file keycache.h.
KEY_CACHE
typedef struct st_key_cache KEY_CACHE
KEYCACHE_PAGE
typedef struct st_keycache_page KEYCACHE_PAGE
Definition at line 23 of file keycache.h.
KEYCACHE_WQUEUE
typedef struct st_keycache_wqueue KEYCACHE_WQUEUE
Function Documentation
change_key_cache_param()
void change_key_cache_param (KEY_CACHE * keycache, uint division_limit, uint age_threshold)
Definition at line 695 of file mf_keycache.c.
 {
   DBUG_ENTER("change_key_cache_param");
   keycache_pthread_mutex_lock(&keycache->cache_lock);
   if (division_limit)
     keycache->min_warm_blocks= (keycache->disk_blocks *
                 division_limit / 100 + 1);
   if (age_threshold)
     keycache->age_threshold=   (keycache->disk_blocks *
                 age_threshold / 100);
   keycache_pthread_mutex_unlock(&keycache->cache_lock);
   DBUG_VOID_RETURN;
 }
References st_key_cache::age_threshold, st_key_cache::cache_lock, DBUG_ENTER, DBUG_VOID_RETURN, st_key_cache::disk_blocks, keycache_pthread_mutex_lock, keycache_pthread_mutex_unlock, and st_key_cache::min_warm_blocks.
Referenced by resize_key_cache().
end_key_cache()
void end_key_cache (KEY_CACHE * keycache, my_bool cleanup)
Definition at line 724 of file mf_keycache.c.
 {
   DBUG_ENTER("end_key_cache");
   DBUG_PRINT("enter", ("key_cache: 0x%lx", (long) keycache));
   if (!keycache->key_cache_inited)
     DBUG_VOID_RETURN;
   if (keycache->disk_blocks > 0)
   {
     if (keycache->block_mem)
     {
       my_large_free((uchar*) keycache->block_mem);
       keycache->block_mem= NULL;
       my_free(keycache->block_root);
       keycache->block_root= NULL;
     }
     keycache->disk_blocks= -1;
     /* Reset blocks_changed to be safe if flush_all_key_blocks is called */
     keycache->blocks_changed= 0;
   }
   DBUG_PRINT("status", ("used: %lu  changed: %lu  w_requests: %lu  "
                         "writes: %lu  r_requests: %lu  reads: %lu",
                         keycache->blocks_used, keycache->global_blocks_changed,
                         (ulong) keycache->global_cache_w_requests,
                         (ulong) keycache->global_cache_write,
                         (ulong) keycache->global_cache_r_requests,
                         (ulong) keycache->global_cache_read));
   /*
     Reset these values to be able to detect a disabled key cache.
     See Bug#44068 (RESTORE can disable the MyISAM Key Cache).
   */
   keycache->blocks_used= 0;
   keycache->blocks_unused= 0;
   if (cleanup)
   {
     mysql_mutex_destroy(&keycache->cache_lock);
     keycache->key_cache_inited= keycache->can_be_used= 0;
     KEYCACHE_DEBUG_CLOSE;
   }
   DBUG_VOID_RETURN;
 } /* end_key_cache */
References st_key_cache::block_mem, st_key_cache::block_root, st_key_cache::blocks_changed, st_key_cache::blocks_unused, st_key_cache::blocks_used, st_key_cache::cache_lock, st_key_cache::can_be_used, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_key_cache::disk_blocks, st_key_cache::global_blocks_changed, st_key_cache::global_cache_r_requests, st_key_cache::global_cache_read, st_key_cache::global_cache_w_requests, st_key_cache::global_cache_write, st_key_cache::key_cache_inited, KEYCACHE_DEBUG_CLOSE, my_free(), my_large_free, mysql_mutex_destroy, and NULL.
Referenced by resize_key_cache().
flush_key_blocks()
int flush_key_blocks (KEY_CACHE * keycache, int file, enum flush_type type)
Definition at line 4035 of file mf_keycache.c.
 {
   int res= 0;
   DBUG_ENTER("flush_key_blocks");
   DBUG_PRINT("enter", ("keycache: 0x%lx", (long) keycache));
   if (!keycache->key_cache_inited)
     DBUG_RETURN(0);
   keycache_pthread_mutex_lock(&keycache->cache_lock);
   /* While waiting for lock, keycache could have been ended. */
   if (keycache->disk_blocks > 0)
   {
     inc_counter_for_resize_op(keycache);
     res= flush_key_blocks_int(keycache, file, type);
     dec_counter_for_resize_op(keycache);
   }
   keycache_pthread_mutex_unlock(&keycache->cache_lock);
   DBUG_RETURN(res);
 }
References st_key_cache::cache_lock, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dec_counter_for_resize_op(), st_key_cache::disk_blocks, mpq::file, flush_key_blocks_int(), inc_counter_for_resize_op(), st_key_cache::key_cache_inited, keycache_pthread_mutex_lock, and keycache_pthread_mutex_unlock.
init_key_cache()
int init_key_cache (KEY_CACHE * keycache, uint key_cache_block_size, size_t use_mem, uint division_limit, uint age_threshold)
Definition at line 366 of file mf_keycache.c.
 {
   ulong blocks, hash_links;
   size_t length;
   int error;
   DBUG_ENTER("init_key_cache");
   DBUG_ASSERT(key_cache_block_size >= 512);
   KEYCACHE_DEBUG_OPEN;
   if (keycache->key_cache_inited && keycache->disk_blocks > 0)
   {
     DBUG_PRINT("warning",("key cache already in use"));
     DBUG_RETURN(0);
   }
   keycache->global_cache_w_requests= keycache->global_cache_r_requests= 0;
   keycache->global_cache_read= keycache->global_cache_write= 0;
   keycache->disk_blocks= -1;
   if (! keycache->key_cache_inited)
   {
     keycache->key_cache_inited= 1;
     /*
       Initialize these variables once only.
       Their value must survive re-initialization during resizing.
     */
     keycache->in_resize= 0;
     keycache->resize_in_flush= 0;
     keycache->cnt_for_resize_op= 0;
     keycache->waiting_for_resize_cnt.last_thread= NULL;
     keycache->in_init= 0;
     mysql_mutex_init(key_KEY_CACHE_cache_lock,
                      &keycache->cache_lock, MY_MUTEX_INIT_FAST);
     keycache->resize_queue.last_thread= NULL;
   }
   keycache->key_cache_mem_size= use_mem;
   keycache->key_cache_block_size= key_cache_block_size;
   DBUG_PRINT("info", ("key_cache_block_size: %u",
               key_cache_block_size));
   blocks= (ulong) (use_mem / (sizeof(BLOCK_LINK) + 2 * sizeof(HASH_LINK) +
                               sizeof(HASH_LINK*) * 5/4 + key_cache_block_size));
   /* It doesn't make sense to have too few blocks (less than 8) */
   if (blocks >= 8)
   {
     for ( ; ; )
     {
       /* Set my_hash_entries to the next bigger 2 power */
       if ((keycache->hash_entries= next_power(blocks)) < blocks * 5/4)
         keycache->hash_entries<<= 1;
       hash_links= 2 * blocks;
 #if defined(MAX_THREADS)
       if (hash_links < MAX_THREADS + blocks - 1)
         hash_links= MAX_THREADS + blocks - 1;
 #endif
       while ((length= (ALIGN_SIZE(blocks * sizeof(BLOCK_LINK)) +
                ALIGN_SIZE(hash_links * sizeof(HASH_LINK)) +
                ALIGN_SIZE(sizeof(HASH_LINK*) *
                                   keycache->hash_entries))) +
          ((size_t) blocks * keycache->key_cache_block_size) > use_mem)
         blocks--;
       /* Allocate memory for cache page buffers */
       if ((keycache->block_mem=
        my_large_malloc((size_t) blocks * keycache->key_cache_block_size,
               MYF(0))))
       {
         /*
       Allocate memory for blocks, hash_links and hash entries;
       For each block 2 hash links are allocated
         */
         if ((keycache->block_root= (BLOCK_LINK*) my_malloc(length,
                                                            MYF(0))))
           break;
         my_large_free(keycache->block_mem);
         keycache->block_mem= 0;
       }
       if (blocks < 8)
       {
         my_errno= ENOMEM;
         my_error(EE_OUTOFMEMORY, MYF(0), blocks * keycache->key_cache_block_size);
         goto err;
       }
       blocks= blocks / 4*3;
     }
     keycache->blocks_unused= blocks;
     keycache->disk_blocks= (int) blocks;
     keycache->hash_links= hash_links;
     keycache->hash_root= (HASH_LINK**) ((char*) keycache->block_root +
                         ALIGN_SIZE(blocks*sizeof(BLOCK_LINK)));
     keycache->hash_link_root= (HASH_LINK*) ((char*) keycache->hash_root +
                             ALIGN_SIZE((sizeof(HASH_LINK*) *
                             keycache->hash_entries)));
     bzero((uchar*) keycache->block_root,
       keycache->disk_blocks * sizeof(BLOCK_LINK));
     bzero((uchar*) keycache->hash_root,
           keycache->hash_entries * sizeof(HASH_LINK*));
     bzero((uchar*) keycache->hash_link_root,
       keycache->hash_links * sizeof(HASH_LINK));
     keycache->hash_links_used= 0;
     keycache->free_hash_list= NULL;
     keycache->blocks_used= keycache->blocks_changed= 0;
     keycache->global_blocks_changed= 0;
     keycache->blocks_available=0;       /* For debugging */
     /* The LRU chain is empty after initialization */
     keycache->used_last= NULL;
     keycache->used_ins= NULL;
     keycache->free_block_list= NULL;
     keycache->keycache_time= 0;
     keycache->warm_blocks= 0;
     keycache->min_warm_blocks= (division_limit ?
                 blocks * division_limit / 100 + 1 :
                 blocks);
     keycache->age_threshold= (age_threshold ?
                   blocks * age_threshold / 100 :
                   blocks);
     keycache->can_be_used= 1;
     keycache->waiting_for_hash_link.last_thread= NULL;
     keycache->waiting_for_block.last_thread= NULL;
     DBUG_PRINT("exit",
            ("disk_blocks: %d  block_root: 0x%lx  hash_entries: %d\
  hash_root: 0x%lx  hash_links: %d  hash_link_root: 0x%lx",
         keycache->disk_blocks,  (long) keycache->block_root,
         keycache->hash_entries, (long) keycache->hash_root,
         keycache->hash_links,   (long) keycache->hash_link_root));
     bzero((uchar*) keycache->changed_blocks,
       sizeof(keycache->changed_blocks[0]) * CHANGED_BLOCKS_HASH);
     bzero((uchar*) keycache->file_blocks,
       sizeof(keycache->file_blocks[0]) * CHANGED_BLOCKS_HASH);
   }
   else
   {
     /* key_buffer_size is specified too small. Disable the cache. */
     keycache->can_be_used= 0;
   }
   keycache->blocks= keycache->disk_blocks > 0 ? keycache->disk_blocks : 0;
   DBUG_RETURN((int) keycache->disk_blocks);
 err:
   error= my_errno;
   keycache->disk_blocks= 0;
   keycache->blocks=  0;
   if (keycache->block_mem)
   {
     my_large_free((uchar*) keycache->block_mem);
     keycache->block_mem= NULL;
   }
   if (keycache->block_root)
   {
     my_free(keycache->block_root);
     keycache->block_root= NULL;
   }
   my_errno= error;
   keycache->can_be_used= 0;
   DBUG_RETURN(0);
 }
References st_key_cache::age_threshold, ALIGN_SIZE, st_key_cache::block_mem, st_key_cache::block_root, st_key_cache::blocks, st_key_cache::blocks_available, st_key_cache::blocks_changed, st_key_cache::blocks_unused, st_key_cache::blocks_used, bzero, st_key_cache::cache_lock, st_key_cache::can_be_used, st_key_cache::changed_blocks, CHANGED_BLOCKS_HASH, st_key_cache::cnt_for_resize_op, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_key_cache::disk_blocks, EE_OUTOFMEMORY, error(), st_key_cache::file_blocks, st_key_cache::free_block_list, st_key_cache::free_hash_list, st_key_cache::global_blocks_changed, st_key_cache::global_cache_r_requests, st_key_cache::global_cache_read, st_key_cache::global_cache_w_requests, st_key_cache::global_cache_write, st_key_cache::hash_entries, st_key_cache::hash_link_root, st_key_cache::hash_links, st_key_cache::hash_links_used, st_key_cache::hash_root, st_key_cache::in_init, st_key_cache::in_resize, st_key_cache::key_cache_block_size, st_key_cache::key_cache_inited, st_key_cache::key_cache_mem_size, KEYCACHE_DEBUG_OPEN, st_key_cache::keycache_time, st_keycache_wqueue::last_thread, G3D::length(), MAX_THREADS, st_key_cache::min_warm_blocks, my_errno, my_error(), my_free(), my_large_free, my_large_malloc, my_malloc(), MY_MUTEX_INIT_FAST, MYF, mysql_mutex_init, next_power(), NULL, st_key_cache::resize_in_flush, st_key_cache::resize_queue, st_key_cache::used_ins, st_key_cache::used_last, st_key_cache::waiting_for_block, st_key_cache::waiting_for_hash_link, st_key_cache::waiting_for_resize_cnt, and st_key_cache::warm_blocks.
Referenced by resize_key_cache().
key_cache_insert()
int key_cache_insert (KEY_CACHE * keycache, File file, my_off_t filepos, int level, uchar * buff, uint length)
Definition at line 2731 of file mf_keycache.c.
 {
   int error= 0;
   DBUG_ENTER("key_cache_insert");
   DBUG_PRINT("enter", ("fd: %u  pos: %lu  length: %u",
                (uint) file,(ulong) filepos, length));
   if (keycache->key_cache_inited)
   {
     /* Key cache is used */
     reg1 BLOCK_LINK *block;
     uint read_length;
     uint offset;
     int page_st;
     my_bool locked_and_incremented= FALSE;
     /*
       When the keycache is once initialized, we use the cache_lock to
       reliably distinguish the cases of normal operation, resizing, and
       disabled cache. We always increment and decrement
       'cnt_for_resize_op' so that a resizer can wait for pending I/O.
     */
     keycache_pthread_mutex_lock(&keycache->cache_lock);
     /*
       We do not load index data into a disabled cache nor into an
       ongoing resize.
     */
     if (!keycache->can_be_used || keycache->in_resize)
     goto no_key_cache;
     /* Register the pseudo I/O for the next resize. */
     inc_counter_for_resize_op(keycache);
     locked_and_incremented= TRUE;
     /* Loaded data may not always be aligned to cache blocks. */
     offset= (uint) (filepos % keycache->key_cache_block_size);
     /* Load data in key_cache_block_size increments. */
     do
     {
       /* Cache could be disabled or resizing in a later iteration. */
       if (!keycache->can_be_used || keycache->in_resize)
     goto no_key_cache;
       /* Start loading at the beginning of the cache block. */
       filepos-= offset;
       /* Do not load beyond the end of the cache block. */
       read_length= length;
       set_if_smaller(read_length, keycache->key_cache_block_size-offset);
       KEYCACHE_DBUG_ASSERT(read_length > 0);
       /* The block has been read by the caller already. */
       keycache->global_cache_read++;
       /* Request the cache block that matches file/pos. */
       keycache->global_cache_r_requests++;
       block= find_key_block(keycache, file, filepos, level, 0, &page_st);
       if (!block)
       {
         /*
           This happens only for requests submitted during key cache
           resize. The block is not in the cache and shall not go in.
           Stop loading index data.
         */
         goto no_key_cache;
       }
       if (!(block->status & BLOCK_ERROR))
       {
         if ((page_st == PAGE_WAIT_TO_BE_READ) ||
             ((page_st == PAGE_TO_BE_READ) &&
              (offset || (read_length < keycache->key_cache_block_size))))
         {
           /*
             Either
             this is a secondary request for a block to be read into the
             cache. The block is in eviction. It is not yet assigned to
             the requested file block (It does not point to the right
             hash_link). So we cannot call remove_reader() on the block.
             And we cannot access the hash_link directly here. We need to
             wait until the assignment is complete. read_block() executes
             the correct wait when called with primary == FALSE.
             Or
             this is a primary request for a block to be read into the
             cache and the supplied data does not fill the whole block.
             This function is called on behalf of a LOAD INDEX INTO CACHE
             statement, which is a read-only task and allows other
             readers. It is possible that a parallel running reader tries
             to access this block. If it needs more data than has been
             supplied here, it would report an error. To be sure that we
             have all data in the block that is available in the file, we
             read the block ourselves.
             Though reading again what the caller did read already is an
             expensive operation, we need to do this for correctness.
           */
           read_block(keycache, block, keycache->key_cache_block_size,
                      read_length + offset, (page_st == PAGE_TO_BE_READ));
           /*
             A secondary request must now have the block assigned to the
             requested file block. It does not hurt to check it for
             primary requests too.
           */
           DBUG_ASSERT(keycache->can_be_used);
           DBUG_ASSERT(block->hash_link->file == file);
           DBUG_ASSERT(block->hash_link->diskpos == filepos);
           DBUG_ASSERT(block->status & (BLOCK_READ | BLOCK_IN_USE));
         }
         else if (page_st == PAGE_TO_BE_READ)
         {
           /*
             This is a new block in the cache. If we come here, we have
             data for the whole block.
           */
           DBUG_ASSERT(block->hash_link->requests);
           DBUG_ASSERT(block->status & BLOCK_IN_USE);
           DBUG_ASSERT((page_st == PAGE_TO_BE_READ) ||
                       (block->status & BLOCK_READ));
 #if !defined(SERIALIZED_READ_FROM_CACHE)
           keycache_pthread_mutex_unlock(&keycache->cache_lock);
           /*
             Here other threads may step in and register as secondary readers.
             They will register in block->wqueue[COND_FOR_REQUESTED].
           */
 #endif
           /* Copy data from buff */
           memcpy(block->buffer+offset, buff, (size_t) read_length);
 #if !defined(SERIALIZED_READ_FROM_CACHE)
           keycache_pthread_mutex_lock(&keycache->cache_lock);
           DBUG_ASSERT(block->status & BLOCK_IN_USE);
           DBUG_ASSERT((page_st == PAGE_TO_BE_READ) ||
                       (block->status & BLOCK_READ));
 #endif
           /*
             After the data is in the buffer, we can declare the block
             valid. Now other threads do not need to register as
             secondary readers any more. They can immediately access the
             block.
           */
           block->status|= BLOCK_READ;
           block->length= read_length+offset;
           /*
             Do not set block->offset here. If this block is marked
             BLOCK_CHANGED later, we want to flush only the modified part. So
             only a writer may set block->offset down from
             keycache->key_cache_block_size.
           */
           KEYCACHE_DBUG_PRINT("key_cache_insert",
                               ("primary request: new page in cache"));
           /* Signal all pending requests. */
           release_whole_queue(&block->wqueue[COND_FOR_REQUESTED]);
         }
         else
         {
           /*
             page_st == PAGE_READ. The block is in the buffer. All data
             must already be present. Blocks are always read with all
             data available on file. Assert that the block does not have
             less contents than the preloader supplies. If the caller has
             data beyond block->length, it means that a file write has
             been done while this block was in cache and not extended
             with the new data. If the condition is met, we can simply
             ignore the block.
           */
           DBUG_ASSERT((page_st == PAGE_READ) &&
                       (read_length + offset <= block->length));
         }
         /*
           A secondary request must now have the block assigned to the
           requested file block. It does not hurt to check it for primary
           requests too.
         */
         DBUG_ASSERT(block->hash_link->file == file);
         DBUG_ASSERT(block->hash_link->diskpos == filepos);
         DBUG_ASSERT(block->status & (BLOCK_READ | BLOCK_IN_USE));
       } /* end of if (!(block->status & BLOCK_ERROR)) */
       remove_reader(block);
       /* Error injection for coverage testing. */
       DBUG_EXECUTE_IF("key_cache_insert_block_error",
                       block->status|= BLOCK_ERROR; errno=EIO;);
       /* Do not link erroneous blocks into the LRU ring, but free them. */
       if (!(block->status & BLOCK_ERROR))
       {
         /*
           Link the block into the LRU ring if it's the last submitted
           request for the block. This enables eviction for the block.
         */
         unreg_request(keycache, block, 1);
       }
       else
       {
         free_block(keycache, block);
         error= 1;
         break;
       }
       buff+= read_length;
       filepos+= read_length+offset;
       offset= 0;
     } while ((length-= read_length));
   no_key_cache:
     if (locked_and_incremented)
       dec_counter_for_resize_op(keycache);
     keycache_pthread_mutex_unlock(&keycache->cache_lock);
   }
   DBUG_RETURN(error);
 }
References BLOCK_ERROR, BLOCK_IN_USE, BLOCK_READ, st_key_cache::cache_lock, st_key_cache::can_be_used, COND_FOR_REQUESTED, DBUG_ASSERT, DBUG_ENTER, DBUG_EXECUTE_IF, DBUG_PRINT, DBUG_RETURN, dec_counter_for_resize_op(), errno, error(), FALSE, mpq::file, find_key_block(), free_block(), st_key_cache::global_cache_r_requests, st_key_cache::global_cache_read, st_key_cache::in_resize, inc_counter_for_resize_op(), st_key_cache::key_cache_block_size, st_key_cache::key_cache_inited, KEYCACHE_DBUG_ASSERT, KEYCACHE_DBUG_PRINT, keycache_pthread_mutex_lock, keycache_pthread_mutex_unlock, G3D::length(), memcpy, PAGE_READ, PAGE_TO_BE_READ, PAGE_WAIT_TO_BE_READ, read_block(), reg1, release_whole_queue(), remove_reader(), set_if_smaller, TRUE, and unreg_request().
key_cache_read()
uchar* key_cache_read (KEY_CACHE * keycache, File file, my_off_t filepos, int level, uchar * buff, uint length, uint block_length, int return_buffer)
key_cache_write()
int key_cache_write (KEY_CACHE * keycache, File file, my_off_t filepos, int level, uchar * buff, uint length, uint block_length, int force_write)
multi_key_cache_change()
void multi_key_cache_change (KEY_CACHE * old_data, KEY_CACHE * new_data)
Definition at line 357 of file mf_keycaches.c.
 {
   safe_hash_change(&key_cache_hash, (uchar*) old_data, (uchar*) new_data);
 }
References key_cache_hash, and safe_hash_change().
multi_key_cache_search()
KEY_CACHE* multi_key_cache_search (uchar * key, uint length)
Definition at line 326 of file mf_keycaches.c.
 {
   if (!key_cache_hash.hash.records)
     return dflt_key_cache;
   return (KEY_CACHE*) safe_hash_search(&key_cache_hash, key, length);
 }
References dflt_key_cache, st_safe_hash_with_default::hash, key_cache_hash, G3D::length(), st_hash::records, and safe_hash_search().
multi_key_cache_set()
my_bool multi_key_cache_set (const uchar * key, uint length, KEY_CACHE * key_cache)
Definition at line 350 of file mf_keycaches.c.
 {
   return safe_hash_set(&key_cache_hash, key, length, (uchar*) key_cache);
 }
References key_cache_hash, G3D::length(), and safe_hash_set().
multi_keycache_free()
void multi_keycache_free (void)
Definition at line 304 of file mf_keycaches.c.
 {
   safe_hash_free(&key_cache_hash);
 }
References key_cache_hash, and safe_hash_free().
multi_keycache_init()
my_bool multi_keycache_init (void)
Definition at line 298 of file mf_keycaches.c.
 {
   return safe_hash_init(&key_cache_hash, 16, (uchar*) dflt_key_cache);
 }
References dflt_key_cache, key_cache_hash, and safe_hash_init().
reset_key_cache_counters()
int reset_key_cache_counters (const char * name, KEY_CACHE * key_cache)
resize_key_cache()
int resize_key_cache (KEY_CACHE * keycache, uint key_cache_block_size, size_t use_mem, uint division_limit, uint age_threshold)
Definition at line 559 of file mf_keycache.c.
 {
   int blocks;
   DBUG_ENTER("resize_key_cache");
   if (!keycache->key_cache_inited)
     DBUG_RETURN(keycache->disk_blocks);
   if(key_cache_block_size == keycache->key_cache_block_size &&
      use_mem == keycache->key_cache_mem_size)
   {
     change_key_cache_param(keycache, division_limit, age_threshold);
     DBUG_RETURN(keycache->disk_blocks);
   }
   keycache_pthread_mutex_lock(&keycache->cache_lock);
   /*
     We may need to wait for another thread which is doing a resize
     already. This cannot happen in the MySQL server though. It allows
     one resizer only. In set_var.cc keycache->in_init is used to block
     multiple attempts.
   */
   while (keycache->in_resize)
   {
     /* purecov: begin inspected */
     wait_on_queue(&keycache->resize_queue, &keycache->cache_lock);
     /* purecov: end */
   }
   /*
     Mark the operation in progress. This blocks other threads from doing
     a resize in parallel. It prohibits new blocks to enter the cache.
     Read/write requests can bypass the cache during the flush phase.
   */
   keycache->in_resize= 1;
   /* Need to flush only if keycache is enabled. */
   if (keycache->can_be_used)
   {
     /* Start the flush phase. */
     keycache->resize_in_flush= 1;
     if (flush_all_key_blocks(keycache))
     {
       /* TODO: if this happens, we should write a warning in the log file ! */
       keycache->resize_in_flush= 0;
       blocks= 0;
       keycache->can_be_used= 0;
       goto finish;
     }
     DBUG_ASSERT(cache_empty(keycache));
     /* End the flush phase. */
     keycache->resize_in_flush= 0;
   }
   /*
     Some direct read/write operations (bypassing the cache) may still be
     unfinished. Wait until they are done. If the key cache can be used,
     direct I/O is done in increments of key_cache_block_size. That is,
     every block is checked if it is in the cache. We need to wait for
     pending I/O before re-initializing the cache, because we may change
     the block size. Otherwise they could check for blocks at file
     positions where the new block division has none. We do also want to
     wait for I/O done when (if) the cache was disabled. It must not
     run in parallel with normal cache operation.
   */
   while (keycache->cnt_for_resize_op)
     wait_on_queue(&keycache->waiting_for_resize_cnt, &keycache->cache_lock);
   /*
     Free old cache structures, allocate new structures, and initialize
     them. Note that the cache_lock mutex and the resize_queue are left
     untouched. We do not lose the cache_lock and will release it only at
     the end of this function.
   */
   end_key_cache(keycache, 0);           /* Don't free mutex */
   /* The following will work even if use_mem is 0 */
   blocks= init_key_cache(keycache, key_cache_block_size, use_mem,
              division_limit, age_threshold);
 finish:
   /*
     Mark the resize finished. This allows other threads to start a
     resize or to request new cache blocks.
   */
   keycache->in_resize= 0;
   /* Signal waiting threads. */
   release_whole_queue(&keycache->resize_queue);
   keycache_pthread_mutex_unlock(&keycache->cache_lock);
   DBUG_RETURN(blocks);
 }
References cache_empty(), st_key_cache::cache_lock, st_key_cache::can_be_used, change_key_cache_param(), st_key_cache::cnt_for_resize_op, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_key_cache::disk_blocks, end_key_cache(), finish(), flush_all_key_blocks(), st_key_cache::in_resize, init_key_cache(), st_key_cache::key_cache_block_size, st_key_cache::key_cache_inited, st_key_cache::key_cache_mem_size, keycache_pthread_mutex_lock, keycache_pthread_mutex_unlock, release_whole_queue(), st_key_cache::resize_in_flush, st_key_cache::resize_queue, wait_on_queue(), and st_key_cache::waiting_for_resize_cnt.
Variable Documentation
dflt_key_cache
KEY_CACHE * dflt_key_cache
Definition at line 110 of file keycache.h.
Referenced by multi_key_cache_search(), and multi_keycache_init().
dflt_key_cache_var
KEY_CACHE dflt_key_cache_var extern
Definition at line 222 of file mf_keycache.c.