Azerotcore-wotlk: SendEncounterUnit Class Reference
SendEncounterUnit Class Reference
Public Member Functions
SendEncounterUnit (Player *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Player * _owner
Detailed Description
Definition at line 179 of file boss_halion.cpp.
Constructor & Destructor Documentation
SendEncounterUnit()
SendEncounterUnit::SendEncounterUnit (Player * owner) inline
Definition at line 182 of file boss_halion.cpp.
 : _owner(owner) { }
Member Function Documentation
Execute()
bool SendEncounterUnit::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 184 of file boss_halion.cpp.
     {
         InstanceScript* instance = _owner->GetInstanceScript();
         if (!instance || _owner->GetMapId() != 724)
             return true;
         if (instance->GetBossState(DATA_HALION) != IN_PROGRESS)
         {
             _owner->RemoveAurasDueToSpell(SPELL_TWILIGHT_REALM);
             return true;
         }
         WorldPacket data(SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT, 4);
         data << uint32(ENCOUNTER_FRAME_REFRESH_FRAMES);
         _owner->GetSession()->SendPacket(&data);
         return true;
     }
References _owner, DATA_HALION, ENCOUNTER_FRAME_REFRESH_FRAMES, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), WorldLocation::GetMapId(), Player::GetSession(), IN_PROGRESS, Unit::RemoveAurasDueToSpell(), WorldSession::SendPacket(), SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT, and SPELL_TWILIGHT_REALM.
Member Data Documentation
_owner
Player* SendEncounterUnit::_owner private
Definition at line 203 of file boss_halion.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp