Azerotcore-wotlk: npc_simon_bunny::npc_simon_bunnyAI Struct Reference
npc_simon_bunny::npc_simon_bunnyAI Struct Reference
Public Member Functions
npc_simon_bunnyAI (Creature *creature)
void UpdateAI (uint32 diff) override
void DoAction (int32 action) override
void SetData (uint32 type, uint32) override
void SetGUID (ObjectGuid guid, int32 id) override
void StartGame ()
void ResetNode ()
void CheckPlayerSequence ()
void GenerateColorSequence ()
void PrepareClusters (bool clustersOnly=false)
void PlayNextColor ()
void PlayColor (uint8 color)
void SetUpPreGame ()
void GiveRewardForLevel (uint8 level)
void GivePunishment ()
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
bool CheckPlayer ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool large
bool listening
uint8 gameLevel
uint8 fails
uint8 gameTicks
ObjectGuid playerGUID
uint32 clusterIds [SIMON_MAX_COLORS]
float zCoordCorrection
float searchDistance
EventMap _events
std::list< uint8 > colorSequence
std::list< uint8 > playableSequence
std::list< uint8 > playerSequence
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 565 of file zone_blades_edge_mountains.cpp.
Constructor & Destructor Documentation
npc_simon_bunnyAI()
npc_simon_bunny::npc_simon_bunnyAI::npc_simon_bunnyAI (Creature * creature) inline
Definition at line 567 of file zone_blades_edge_mountains.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
CheckPlayer()
bool npc_simon_bunny::npc_simon_bunnyAI::CheckPlayer () inline
Definition at line 986 of file zone_blades_edge_mountains.cpp.
         {
             if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
             {
                 if (player->isDead())
                     return false;
                 if (player->GetDistance2d(me) >= 2.0f * searchDistance)
                 {
                     GivePunishment();
                     return false;
                 }
             }
             else
                 return false;
             return true;
         }
References ObjectAccessor::GetPlayer(), GivePunishment(), ScriptedAI::me, playerGUID, and searchDistance.
Referenced by UpdateAI().
CheckPlayerSequence()
void npc_simon_bunny::npc_simon_bunnyAI::CheckPlayerSequence () inline
Definition at line 797 of file zone_blades_edge_mountains.cpp.
         {
             bool correct = true;
             if (playerSequence.size() <= colorSequence.size())
                 for (std::list<uint8>::const_iterator i = playerSequence.begin(), j = colorSequence.begin(); i != playerSequence.end(); ++i, ++j)
                     if ((*i) != (*j))
                         correct = false;
             if (correct && (playerSequence.size() == colorSequence.size()))
                 DoAction(ACTION_SIMON_CORRECT_FULL_SEQUENCE);
             else if (!correct)
                 DoAction(ACTION_SIMON_WRONG_SEQUENCE);
         }
References ACTION_SIMON_CORRECT_FULL_SEQUENCE, ACTION_SIMON_WRONG_SEQUENCE, colorSequence, DoAction(), and playerSequence.
Referenced by SetData().
DoAction()
void npc_simon_bunny::npc_simon_bunnyAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 635 of file zone_blades_edge_mountains.cpp.
         {
             switch (action)
             {
                 case ACTION_SIMON_ROUND_FINISHED:
                     listening = false;
                     DoCast(SPELL_VISUAL_START_AI_LEVEL);
                     GiveRewardForLevel(gameLevel);
                     _events.CancelEventGroup(0);
                     if (gameLevel == 10)
                         ResetNode();
                     else
                         _events.ScheduleEvent(EVENT_SIMON_SETUP_PRE_GAME, 1000);
                     break;
                 case ACTION_SIMON_CORRECT_FULL_SEQUENCE:
                     gameLevel++;
                     DoAction(ACTION_SIMON_ROUND_FINISHED);
                     break;
                 case ACTION_SIMON_WRONG_SEQUENCE:
                     GivePunishment();
                     DoAction(ACTION_SIMON_ROUND_FINISHED);
                     break;
             }
         }
References _events, ACTION_SIMON_CORRECT_FULL_SEQUENCE, ACTION_SIMON_ROUND_FINISHED, ACTION_SIMON_WRONG_SEQUENCE, EventMap::CancelEventGroup(), UnitAI::DoCast(), EVENT_SIMON_SETUP_PRE_GAME, gameLevel, GivePunishment(), GiveRewardForLevel(), listening, ResetNode(), EventMap::ScheduleEvent(), and SPELL_VISUAL_START_AI_LEVEL.
Referenced by CheckPlayerSequence(), and UpdateAI().
GenerateColorSequence()
void npc_simon_bunny::npc_simon_bunnyAI::GenerateColorSequence () inline
Definition at line 815 of file zone_blades_edge_mountains.cpp.
         {
             colorSequence.clear();
             for (uint8 i = 0; i <= gameLevel; i++)
                 colorSequence.push_back(RAND(SIMON_BLUE, SIMON_RED, SIMON_GREEN, SIMON_YELLOW));
             for (std::list<uint8>::const_iterator i = colorSequence.begin(); i != colorSequence.end(); ++i)
                 playableSequence.push_back(*i);
         }
References colorSequence, gameLevel, playableSequence, RAND(), SIMON_BLUE, SIMON_GREEN, SIMON_RED, and SIMON_YELLOW.
Referenced by SetUpPreGame().
GivePunishment()
void npc_simon_bunny::npc_simon_bunnyAI::GivePunishment () inline
Definition at line 951 of file zone_blades_edge_mountains.cpp.
         {
             if (large)
             {
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                     if (Creature* guardian = me->SummonCreature(NPC_APEXIS_GUARDIAN, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() - zCoordCorrection, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 20000))
                         guardian->AI()->AttackStart(player);
                 ResetNode();
             }
             else
             {
                 fails++;
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                     DoCast(player, SPELL_BAD_PRESS_TRIGGER, true);
                 if (fails >= 4)
                     ResetNode();
             }
         }
References UnitAI::DoCast(), fails, ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), large, ScriptedAI::me, NPC_APEXIS_GUARDIAN, playerGUID, ResetNode(), SPELL_BAD_PRESS_TRIGGER, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and zCoordCorrection.
Referenced by CheckPlayer(), DoAction(), and GiveRewardForLevel().
GiveRewardForLevel()
void npc_simon_bunny::npc_simon_bunnyAI::GiveRewardForLevel (uint8 level) inline
Definition at line 920 of file zone_blades_edge_mountains.cpp.
         {
             uint32 rewSpell = 0;
             switch (level)
             {
                 case 6:
                     if (large)
                         GivePunishment();
                     else
                         rewSpell = SPELL_REWARD_BUFF_1;
                     break;
                 case 8:
                     rewSpell = SPELL_REWARD_BUFF_2;
                     break;
                 case 10:
                     rewSpell = SPELL_REWARD_BUFF_3;
                     break;
             }
             if (rewSpell)
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                     DoCast(player, rewSpell, true);
         }
References UnitAI::DoCast(), ObjectAccessor::GetPlayer(), GivePunishment(), large, ScriptedAI::me, playerGUID, SPELL_REWARD_BUFF_1, SPELL_REWARD_BUFF_2, and SPELL_REWARD_BUFF_3.
Referenced by DoAction().
PlayColor()
void npc_simon_bunny::npc_simon_bunnyAI::PlayColor (uint8 color) inline
Definition at line 851 of file zone_blades_edge_mountains.cpp.
         {
             switch (color)
             {
                 case SIMON_BLUE:
                     DoCast(SPELL_VISUAL_BLUE);
                     DoPlaySoundToSet(me, SOUND_BLUE);
                     break;
                 case SIMON_GREEN:
                     DoCast(SPELL_VISUAL_GREEN);
                     DoPlaySoundToSet(me, SOUND_GREEN);
                     break;
                 case SIMON_RED:
                     DoCast(SPELL_VISUAL_RED);
                     DoPlaySoundToSet(me, SOUND_RED);
                     break;
                 case SIMON_YELLOW:
                     DoCast(SPELL_VISUAL_YELLOW);
                     DoPlaySoundToSet(me, SOUND_YELLOW);
                     break;
             }
         }
References UnitAI::DoCast(), ScriptedAI::DoPlaySoundToSet(), ScriptedAI::me, SIMON_BLUE, SIMON_GREEN, SIMON_RED, SIMON_YELLOW, SOUND_BLUE, SOUND_GREEN, SOUND_RED, SOUND_YELLOW, SPELL_VISUAL_BLUE, SPELL_VISUAL_GREEN, SPELL_VISUAL_RED, and SPELL_VISUAL_YELLOW.
Referenced by PlayNextColor(), and SetData().
PlayNextColor()
void npc_simon_bunny::npc_simon_bunnyAI::PlayNextColor () inline
Definition at line 844 of file zone_blades_edge_mountains.cpp.
         {
             PlayColor(*playableSequence.begin());
             playableSequence.erase(playableSequence.begin());
         }
References playableSequence, and PlayColor().
Referenced by UpdateAI().
PrepareClusters()
void npc_simon_bunny::npc_simon_bunnyAI::PrepareClusters (bool clustersOnly = false) inline
Definition at line 826 of file zone_blades_edge_mountains.cpp.
         {
             for (uint32 clusterId = SIMON_BLUE; clusterId < SIMON_MAX_COLORS; clusterId++)
                 if (GameObject* cluster = me->FindNearestGameObject(clusterIds[clusterId], searchDistance))
                     cluster->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             if (clustersOnly)
                 return;
             for (uint32 auraId = GO_AURA_BLUE; auraId <= GO_AURA_YELLOW; auraId++)
                 if (GameObject* auraGo = me->FindNearestGameObject(auraId, searchDistance))
                     auraGo->RemoveFromWorld();
         }
References clusterIds, WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, GO_AURA_BLUE, GO_AURA_YELLOW, GO_FLAG_NOT_SELECTABLE, ScriptedAI::me, searchDistance, SIMON_BLUE, and SIMON_MAX_COLORS.
Referenced by UpdateAI().
ResetNode()
void npc_simon_bunny::npc_simon_bunnyAI::ResetNode () inline
Definition at line 774 of file zone_blades_edge_mountains.cpp.
         {
             DoPlaySoundToSet(me, SOUND_DISABLE_NODE);
             for (uint32 clusterId = SIMON_BLUE; clusterId < SIMON_MAX_COLORS; clusterId++)
                 if (GameObject* cluster = me->FindNearestGameObject(clusterIds[clusterId], searchDistance))
                     cluster->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             for (uint32 auraId = GO_AURA_BLUE; auraId <= GO_AURA_YELLOW; auraId++)
                 if (GameObject* auraGo = me->FindNearestGameObject(auraId, searchDistance))
                     auraGo->RemoveFromWorld();
             if (GameObject* relic = me->FindNearestGameObject(large ? GO_APEXIS_MONUMENT : GO_APEXIS_RELIC, searchDistance))
                 relic->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             me->DespawnOrUnsummon(1000);
         }
References clusterIds, Creature::DespawnOrUnsummon(), ScriptedAI::DoPlaySoundToSet(), WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, GO_APEXIS_MONUMENT, GO_APEXIS_RELIC, GO_AURA_BLUE, GO_AURA_YELLOW, GO_FLAG_NOT_SELECTABLE, large, ScriptedAI::me, searchDistance, SIMON_BLUE, SIMON_MAX_COLORS, and SOUND_DISABLE_NODE.
Referenced by DoAction(), GivePunishment(), and UpdateAI().
SetData()
void npc_simon_bunny::npc_simon_bunnyAI::SetData (uint32 type, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 661 of file zone_blades_edge_mountains.cpp.
         {
             if (!listening)
                 return;
             uint8 pressedColor = SIMON_MAX_COLORS;
             if (type == clusterIds[SIMON_RED])
                 pressedColor = SIMON_RED;
             else if (type == clusterIds[SIMON_BLUE])
                 pressedColor = SIMON_BLUE;
             else if (type == clusterIds[SIMON_GREEN])
                 pressedColor = SIMON_GREEN;
             else if (type == clusterIds[SIMON_YELLOW])
                 pressedColor = SIMON_YELLOW;
             PlayColor(pressedColor);
             playerSequence.push_back(pressedColor);
             _events.ScheduleEvent(EVENT_SIMON_RESET_CLUSTERS, 500);
             CheckPlayerSequence();
         }
References _events, CheckPlayerSequence(), clusterIds, EVENT_SIMON_RESET_CLUSTERS, listening, PlayColor(), playerSequence, EventMap::ScheduleEvent(), SIMON_BLUE, SIMON_GREEN, SIMON_MAX_COLORS, SIMON_RED, and SIMON_YELLOW.
SetGUID()
void npc_simon_bunny::npc_simon_bunnyAI::SetGUID (ObjectGuid guid, int32 id) inline override virtual
Reimplemented from UnitAI.
Definition at line 684 of file zone_blades_edge_mountains.cpp.
         {
             me->SetCanFly(true);
             large = (bool)id;
             playerGUID = guid;
             StartGame();
         }
References large, ScriptedAI::me, playerGUID, Creature::SetCanFly(), and StartGame().
SetUpPreGame()
void npc_simon_bunny::npc_simon_bunnyAI::SetUpPreGame () inline
Definition at line 878 of file zone_blades_edge_mountains.cpp.
         {
             for (uint32 clusterId = SIMON_BLUE; clusterId < SIMON_MAX_COLORS; clusterId++)
             {
                 if (GameObject* cluster = me->FindNearestGameObject(clusterIds[clusterId], 2.0f * searchDistance))
                 {
                     cluster->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     // break since we don't need glowing auras for large clusters
                     if (large)
                         break;
                     float x, y, z, o;
                     cluster->GetPosition(x, y, z, o);
                     me->NearTeleportTo(x, y, z, o);
                     uint32 preGameSpellId;
                     if (cluster->GetEntry() == clusterIds[SIMON_RED])
                         preGameSpellId = SPELL_PRE_GAME_RED;
                     else if (cluster->GetEntry() == clusterIds[SIMON_BLUE])
                         preGameSpellId = SPELL_PRE_GAME_BLUE;
                     else if (cluster->GetEntry() == clusterIds[SIMON_GREEN])
                         preGameSpellId = SPELL_PRE_GAME_GREEN;
                     else if (cluster->GetEntry() == clusterIds[SIMON_YELLOW])
                         preGameSpellId = SPELL_PRE_GAME_YELLOW;
                     else break;
                     me->CastSpell(cluster, preGameSpellId, true);
                 }
             }
             if (GameObject* relic = me->FindNearestGameObject(large ? GO_APEXIS_MONUMENT : GO_APEXIS_RELIC, searchDistance))
             {
                 float x, y, z, o;
                 relic->GetPosition(x, y, z, o);
                 me->NearTeleportTo(x, y, z + zCoordCorrection, o);
             }
             GenerateColorSequence();
         }
References Unit::CastSpell(), clusterIds, WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, GenerateColorSequence(), GO_APEXIS_MONUMENT, GO_APEXIS_RELIC, GO_FLAG_NOT_SELECTABLE, large, ScriptedAI::me, Unit::NearTeleportTo(), searchDistance, SIMON_BLUE, SIMON_GREEN, SIMON_MAX_COLORS, SIMON_RED, SIMON_YELLOW, SPELL_PRE_GAME_BLUE, SPELL_PRE_GAME_GREEN, SPELL_PRE_GAME_RED, SPELL_PRE_GAME_YELLOW, and zCoordCorrection.
Referenced by UpdateAI().
SpellHitTarget()
void npc_simon_bunny::npc_simon_bunnyAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 973 of file zone_blades_edge_mountains.cpp.
         {
             // Cast SPELL_BAD_PRESS_DAMAGE with scaled basepoints when the visual hits the target.
             // Need Fix: When SPELL_BAD_PRESS_TRIGGER hits target it triggers spell SPELL_BAD_PRESS_DAMAGE by itself
             // so player gets damage equal to calculated damage  dbc basepoints for SPELL_BAD_PRESS_DAMAGE (~50)
             if (spell->Id == SPELL_BAD_PRESS_TRIGGER)
             {
                 int32 bp = (int32)((float)(fails) * 0.33f * target->GetMaxHealth());
                 target->CastCustomSpell(target, SPELL_BAD_PRESS_DAMAGE, &bp, nullptr, nullptr, true);
             }
         }
References Unit::CastCustomSpell(), fails, Unit::GetMaxHealth(), SpellInfo::Id, SPELL_BAD_PRESS_DAMAGE, and SPELL_BAD_PRESS_TRIGGER.
StartGame()
void npc_simon_bunny::npc_simon_bunnyAI::StartGame () inline
Definition at line 697 of file zone_blades_edge_mountains.cpp.
         {
             listening = false;
             gameLevel = 0;
             fails = 0;
             gameTicks = 0;
             zCoordCorrection = large ? 8.0f : 2.75f;
             searchDistance = large ? 13.0f : 5.0f;
             colorSequence.clear();
             playableSequence.clear();
             playerSequence.clear();
             me->SetObjectScale(large ? 2.0f : 1.0f);
             std::list<WorldObject*> ClusterList;
             Acore::AllWorldObjectsInRange objects(me, searchDistance);
             Acore::WorldObjectListSearcher<Acore::AllWorldObjectsInRange> searcher(me, ClusterList, objects);
             Cell::VisitAllObjects(me, searcher, searchDistance);
             for (std::list<WorldObject*>::const_iterator i = ClusterList.begin(); i != ClusterList.end(); ++i)
             {
                 if (GameObject* go = (*i)->ToGameObject())
                 {
                     // We are checking for displayid because all simon nodes have 4 clusters with different entries
                     if (large)
                     {
                         switch (go->GetGOInfo()->displayId)
{
                             case GO_BLUE_CLUSTER_DISPLAY_LARGE:
                                 clusterIds[SIMON_BLUE] = go->GetEntry();
                                 break;
                             case GO_RED_CLUSTER_DISPLAY_LARGE:
                                 clusterIds[SIMON_RED] = go->GetEntry();
                                 break;
                             case GO_GREEN_CLUSTER_DISPLAY_LARGE:
                                 clusterIds[SIMON_GREEN] = go->GetEntry();
                                 break;
                             case GO_YELLOW_CLUSTER_DISPLAY_LARGE:
                                 clusterIds[SIMON_YELLOW] = go->GetEntry();
                                 break;
                         }
                     }
                     else
                     {
                         switch (go->GetGOInfo()->displayId)
{
                             case GO_BLUE_CLUSTER_DISPLAY:
                                 clusterIds[SIMON_BLUE] = go->GetEntry();
                                 break;
                             case GO_RED_CLUSTER_DISPLAY:
                                 clusterIds[SIMON_RED] = go->GetEntry();
                                 break;
                             case GO_GREEN_CLUSTER_DISPLAY:
                                 clusterIds[SIMON_GREEN] = go->GetEntry();
                                 break;
                             case GO_YELLOW_CLUSTER_DISPLAY:
                                 clusterIds[SIMON_YELLOW] = go->GetEntry();
                                 break;
                         }
                     }
                 }
             }
             _events.Reset();
             _events.ScheduleEvent(EVENT_SIMON_ROUND_FINISHED, 1000);
             _events.ScheduleEvent(EVENT_SIMON_PERIODIC_PLAYER_CHECK, 2000);
             if (GameObject* relic = me->FindNearestGameObject(large ? GO_APEXIS_MONUMENT : GO_APEXIS_RELIC, searchDistance))
                 relic->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
         }
References _events, clusterIds, colorSequence, EVENT_SIMON_PERIODIC_PLAYER_CHECK, EVENT_SIMON_ROUND_FINISHED, fails, WorldObject::FindNearestGameObject(), gameLevel, GAMEOBJECT_FLAGS, gameTicks, GO_APEXIS_MONUMENT, GO_APEXIS_RELIC, GO_BLUE_CLUSTER_DISPLAY, GO_BLUE_CLUSTER_DISPLAY_LARGE, GO_FLAG_NOT_SELECTABLE, GO_GREEN_CLUSTER_DISPLAY, GO_GREEN_CLUSTER_DISPLAY_LARGE, GO_RED_CLUSTER_DISPLAY, GO_RED_CLUSTER_DISPLAY_LARGE, GO_YELLOW_CLUSTER_DISPLAY, GO_YELLOW_CLUSTER_DISPLAY_LARGE, large, listening, ScriptedAI::me, playableSequence, playerSequence, EventMap::Reset(), EventMap::ScheduleEvent(), searchDistance, Creature::SetObjectScale(), SIMON_BLUE, SIMON_GREEN, SIMON_RED, SIMON_YELLOW, Object::ToGameObject(), Cell::VisitAllObjects(), and zCoordCorrection.
Referenced by SetGUID().
UpdateAI()
void npc_simon_bunny::npc_simon_bunnyAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 581 of file zone_blades_edge_mountains.cpp.
         {
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case EVENT_SIMON_PERIODIC_PLAYER_CHECK:
                     if (!CheckPlayer())
                         ResetNode();
                     else
                         _events.ScheduleEvent(EVENT_SIMON_PERIODIC_PLAYER_CHECK, 2000);
                     break;
                 case EVENT_SIMON_SETUP_PRE_GAME:
                     SetUpPreGame();
                     _events.CancelEvent(EVENT_SIMON_GAME_TICK);
                     _events.ScheduleEvent(EVENT_SIMON_PLAY_SEQUENCE, 1000);
                     break;
                 case EVENT_SIMON_PLAY_SEQUENCE:
                     if (!playableSequence.empty())
                     {
                         PlayNextColor();
                         _events.ScheduleEvent(EVENT_SIMON_PLAY_SEQUENCE, 1500);
                     }
                     else
                     {
                         listening = true;
                         DoCast(SPELL_VISUAL_START_PLAYER_LEVEL);
                         playerSequence.clear();
                         PrepareClusters();
                         gameTicks = 0;
                         _events.ScheduleEvent(EVENT_SIMON_GAME_TICK, 3000);
                     }
                     break;
                 case EVENT_SIMON_GAME_TICK:
                     DoCast(SPELL_AUDIBLE_GAME_TICK);
                     if (gameTicks > gameLevel)
                         _events.ScheduleEvent(EVENT_SIMON_TOO_LONG_TIME, 500);
                     else
                         _events.ScheduleEvent(EVENT_SIMON_GAME_TICK, 3000);
                     gameTicks++;
                     break;
                 case EVENT_SIMON_RESET_CLUSTERS:
                     PrepareClusters(true);
                     break;
                 case EVENT_SIMON_TOO_LONG_TIME:
                     DoAction(ACTION_SIMON_WRONG_SEQUENCE);
                     break;
                 case EVENT_SIMON_ROUND_FINISHED:
                     DoAction(ACTION_SIMON_ROUND_FINISHED);
                     break;
             }
         }
References _events, ACTION_SIMON_ROUND_FINISHED, ACTION_SIMON_WRONG_SEQUENCE, EventMap::CancelEvent(), CheckPlayer(), DoAction(), UnitAI::DoCast(), EVENT_SIMON_GAME_TICK, EVENT_SIMON_PERIODIC_PLAYER_CHECK, EVENT_SIMON_PLAY_SEQUENCE, EVENT_SIMON_RESET_CLUSTERS, EVENT_SIMON_ROUND_FINISHED, EVENT_SIMON_SETUP_PRE_GAME, EVENT_SIMON_TOO_LONG_TIME, EventMap::ExecuteEvent(), gameLevel, gameTicks, listening, playableSequence, playerSequence, PlayNextColor(), PrepareClusters(), ResetNode(), EventMap::ScheduleEvent(), SetUpPreGame(), SPELL_AUDIBLE_GAME_TICK, SPELL_VISUAL_START_PLAYER_LEVEL, and EventMap::Update().
Member Data Documentation
_events
EventMap npc_simon_bunny::npc_simon_bunnyAI::_events
Definition at line 578 of file zone_blades_edge_mountains.cpp.
Referenced by DoAction(), SetData(), StartGame(), and UpdateAI().
clusterIds
uint32 npc_simon_bunny::npc_simon_bunnyAI::clusterIds[SIMON_MAX_COLORS]
Definition at line 575 of file zone_blades_edge_mountains.cpp.
Referenced by PrepareClusters(), ResetNode(), SetData(), SetUpPreGame(), and StartGame().
colorSequence
std::list<uint8> npc_simon_bunny::npc_simon_bunnyAI::colorSequence
Definition at line 579 of file zone_blades_edge_mountains.cpp.
Referenced by CheckPlayerSequence(), GenerateColorSequence(), and StartGame().
fails
uint8 npc_simon_bunny::npc_simon_bunnyAI::fails
Definition at line 572 of file zone_blades_edge_mountains.cpp.
Referenced by GivePunishment(), SpellHitTarget(), and StartGame().
gameLevel
uint8 npc_simon_bunny::npc_simon_bunnyAI::gameLevel
Definition at line 571 of file zone_blades_edge_mountains.cpp.
Referenced by DoAction(), GenerateColorSequence(), StartGame(), and UpdateAI().
gameTicks
uint8 npc_simon_bunny::npc_simon_bunnyAI::gameTicks
Definition at line 573 of file zone_blades_edge_mountains.cpp.
Referenced by StartGame(), and UpdateAI().
large
bool npc_simon_bunny::npc_simon_bunnyAI::large
Definition at line 569 of file zone_blades_edge_mountains.cpp.
Referenced by GivePunishment(), GiveRewardForLevel(), ResetNode(), SetGUID(), SetUpPreGame(), and StartGame().
listening
bool npc_simon_bunny::npc_simon_bunnyAI::listening
Definition at line 570 of file zone_blades_edge_mountains.cpp.
Referenced by DoAction(), SetData(), StartGame(), and UpdateAI().
playableSequence
std::list<uint8> npc_simon_bunny::npc_simon_bunnyAI::playableSequence
Definition at line 579 of file zone_blades_edge_mountains.cpp.
Referenced by GenerateColorSequence(), PlayNextColor(), StartGame(), and UpdateAI().
playerGUID
ObjectGuid npc_simon_bunny::npc_simon_bunnyAI::playerGUID
Definition at line 574 of file zone_blades_edge_mountains.cpp.
Referenced by CheckPlayer(), GivePunishment(), GiveRewardForLevel(), and SetGUID().
playerSequence
std::list<uint8> npc_simon_bunny::npc_simon_bunnyAI::playerSequence
Definition at line 579 of file zone_blades_edge_mountains.cpp.
Referenced by CheckPlayerSequence(), SetData(), StartGame(), and UpdateAI().
searchDistance
float npc_simon_bunny::npc_simon_bunnyAI::searchDistance
Definition at line 577 of file zone_blades_edge_mountains.cpp.
Referenced by CheckPlayer(), PrepareClusters(), ResetNode(), SetUpPreGame(), and StartGame().
zCoordCorrection
float npc_simon_bunny::npc_simon_bunnyAI::zCoordCorrection
Definition at line 576 of file zone_blades_edge_mountains.cpp.
Referenced by GivePunishment(), SetUpPreGame(), and StartGame().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_blades_edge_mountains.cpp