Azerotcore-wotlk: spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript Class Reference
spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_midsummer_fling_torch_SpellScript)
bool Load () override
SpellCastResult CheckCast ()
void ThrowNextTorch (Unit *caster)
void HandleFinish ()
void HandleScript (SpellEffIndex effIndex)
void Register () override
Private Attributes
bool handled
std::list< Creature * > _crList
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 398 of file midsummer.cpp.
Member Function Documentation
CheckCast()
SpellCastResult spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::CheckCast () inline private
Definition at line 405 of file midsummer.cpp.
         {
             GetCaster()->GetCreaturesWithEntryInRange(_crList, 100.0f, NPC_TORCH_TARGET);
             if (_crList.empty())
             {
                 return SPELL_FAILED_NOT_HERE;
             }
             return SPELL_CAST_OK;
         }
References _crList, SpellScript::GetCaster(), WorldObject::GetCreaturesWithEntryInRange(), NPC_TORCH_TARGET, SPELL_CAST_OK, and SPELL_FAILED_NOT_HERE.
Referenced by Register().
HandleFinish()
void spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::HandleFinish () inline private
Definition at line 442 of file midsummer.cpp.
         {
             Unit* caster = GetCaster();
             if (!caster || !caster->ToPlayer()) // caster cant be null, but meh :p
                 return;
             if (GetSpellInfo()->Id != SPELL_FLING_TORCH_DUMMY)
             {
                 if (!handled)
                     if (const WorldLocation* loc = GetExplTargetDest())
                     {
                         caster->CastSpell(loc->GetPositionX(), loc->GetPositionY(), loc->GetPositionZ(), SPELL_MISSED_TORCH, true);
                         caster->RemoveAurasDueToSpell(SPELL_TORCH_COUNTER);
                     }
                 return;
             }
             ThrowNextTorch(caster);
         }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetExplTargetDest(), SpellScript::GetSpellInfo(), handled, Unit::RemoveAurasDueToSpell(), SPELL_FLING_TORCH_DUMMY, SPELL_MISSED_TORCH, SPELL_TORCH_COUNTER, ThrowNextTorch(), and Object::ToPlayer().
Referenced by Register().
HandleScript()
void spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::HandleScript (SpellEffIndex effIndex) inline private
Definition at line 462 of file midsummer.cpp.
         {
             PreventHitDefaultEffect(effIndex);
             if (Player* target = GetHitPlayer())
             {
                 if (target->GetGUID() != GetCaster()->GetGUID())
                     return;
                 handled = true;
                 if (Aura* aur = target->GetAura(SPELL_TORCH_COUNTER))
                 {
                     aur->ModStackAmount(1);
                     uint8 count = 4;
                     if (target->GetQuestStatus(target->GetTeamId() ? 11925 : 11924) == QUEST_STATUS_INCOMPLETE) // More Torch Catching quests
                         count = 10;
                     if (aur->GetStackAmount() >= count)
                     {
                         //target->CastSpell(target, 46711, true); // Set Flag: all torch returning quests are complete
                         target->CastSpell(target, (target->GetTeamId() ? 46654 : 46081), true); // Quest completion
                         aur->SetDuration(1);
                         return;
                     }
                 }
                 else
                     target->CastSpell(target, SPELL_TORCH_COUNTER, true);
                 ThrowNextTorch(GetCaster());
             }
         }
References SpellScript::GetCaster(), SpellScript::GetHitPlayer(), handled, SpellScript::PreventHitDefaultEffect(), QUEST_STATUS_INCOMPLETE, SPELL_TORCH_COUNTER, and ThrowNextTorch().
Referenced by Register().
Load()
bool spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 403 of file midsummer.cpp.
 { handled = false; return true; }
References handled.
PrepareSpellScript()
spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::PrepareSpellScript (spell_midsummer_fling_torch_SpellScript) private
Register()
void spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 493 of file midsummer.cpp.
         {
             AfterCast += SpellCastFn(spell_midsummer_fling_torch_SpellScript::HandleFinish);
             if (m_scriptSpellId == 45671)
             {
                 OnCheckCast += SpellCheckCastFn(spell_midsummer_fling_torch_SpellScript::CheckCast);
                 OnEffectHitTarget += SpellEffectFn(spell_midsummer_fling_torch_SpellScript::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
             }
         }
References SpellScript::AfterCast, CheckCast(), EFFECT_0, HandleFinish(), HandleScript(), _SpellScript::m_scriptSpellId, SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, SpellCastFn, SpellCheckCastFn, and SpellEffectFn.
ThrowNextTorch()
void spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::ThrowNextTorch (Unit * caster) inline private
Definition at line 416 of file midsummer.cpp.
         {
             uint8 rand = urand(0, _crList.size() - 1);
             Position pos;
             pos.Relocate(0.0f, 0.0f, 0.0f);
             for (std::list<Creature*>::const_iterator itr = _crList.begin(); itr != _crList.end(); ++itr, --rand)
             {
                 if (caster->GetDistance(*itr) < 5)
                 {
                     if (!rand)
                         rand++;
                     continue;
                 }
                 if (!rand)
                 {
                     pos.Relocate(*itr);
                     break;
                 }
             }
             // we have any pos
             if (pos.GetPositionX())
                 caster->CastSpell(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), SPELL_FLING_TORCH, true);
         }
References _crList, Unit::CastSpell(), WorldObject::GetDistance(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::Relocate(), SPELL_FLING_TORCH, and urand().
Referenced by HandleFinish(), and HandleScript().
Member Data Documentation
_crList
std::list<Creature*> spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::_crList private
Definition at line 504 of file midsummer.cpp.
Referenced by CheckCast(), and ThrowNextTorch().
handled
bool spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::handled private
Definition at line 402 of file midsummer.cpp.
Referenced by HandleFinish(), HandleScript(), and Load().
The documentation for this class was generated from the following file:
src/server/scripts/Events/midsummer.cpp