Azerotcore-wotlk: ArenaTeamMgr Class Reference
ArenaTeamMgr Class Reference
#include <ArenaTeamMgr.h>
Public Types
typedef std::unordered_map< uint32, ArenaTeam * > ArenaTeamContainer
Public Member Functions
ArenaTeam * GetArenaTeamById (uint32 arenaTeamId) const
ArenaTeam * GetArenaTeamByName (std::string const &arenaTeamName) const
ArenaTeam * GetArenaTeamByCaptain (ObjectGuid guid) const
ArenaTeam * GetArenaTeamByName (std::string const &arenaTeamName, const uint32 type) const
ArenaTeam * GetArenaTeamByCaptain (ObjectGuid guid, const uint32 type) const
void LoadArenaTeams ()
void AddArenaTeam (ArenaTeam *arenaTeam)
void RemoveArenaTeam (uint32 Id)
ArenaTeamContainer::iterator GetArenaTeamMapBegin ()
ArenaTeamContainer::iterator GetArenaTeamMapEnd ()
ArenaTeamContainer & GetArenaTeams ()
void DistributeArenaPoints ()
uint32 GenerateArenaTeamId ()
void SetNextArenaTeamId (uint32 Id)
uint32 GetNextArenaLogId ()
void SetLastArenaLogId (uint32 id)
uint32 GenerateTempArenaTeamId ()
Static Public Member Functions
static ArenaTeamMgr * instance ()
Protected Attributes
uint32 NextArenaTeamId
uint32 NextTempArenaTeamId
ArenaTeamContainer ArenaTeamStore
uint32 LastArenaLogId
Private Member Functions
ArenaTeamMgr ()
~ArenaTeamMgr ()
Detailed Description
Definition at line 26 of file ArenaTeamMgr.h.
Member Typedef Documentation
ArenaTeamContainer
typedef std::unordered_map<uint32, ArenaTeam*> ArenaTeamMgr::ArenaTeamContainer
Definition at line 34 of file ArenaTeamMgr.h.
Constructor & Destructor Documentation
ArenaTeamMgr()
ArenaTeamMgr::ArenaTeamMgr () private
Definition at line 28 of file ArenaTeamMgr.cpp.
 {
     NextArenaTeamId = 1;
     LastArenaLogId = 0;
     NextTempArenaTeamId = 0xFFF00000;
 }
References LastArenaLogId, NextArenaTeamId, and NextTempArenaTeamId.
~ArenaTeamMgr()
ArenaTeamMgr::~ArenaTeamMgr () private
Definition at line 35 of file ArenaTeamMgr.cpp.
 {
     for (ArenaTeamContainer::iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
         delete itr->second;
 }
References ArenaTeamStore.
Member Function Documentation
AddArenaTeam()
void ArenaTeamMgr::AddArenaTeam (ArenaTeam * arenaTeam)
Definition at line 117 of file ArenaTeamMgr.cpp.
 {
     ArenaTeamStore[arenaTeam->GetId()] = arenaTeam;
 }
References ArenaTeamStore, and ArenaTeam::GetId().
Referenced by LoadArenaTeams().
DistributeArenaPoints()
void ArenaTeamMgr::DistributeArenaPoints ()
Definition at line 194 of file ArenaTeamMgr.cpp.
 {
     // Used to distribute arena points based on last week's stats
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_START);
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_ONLINE_START);
     // Temporary structure for storing maximum points to add values for all players
     std::map<ObjectGuid, uint32> PlayerPoints;
     // At first update all points for all team members
     for (ArenaTeamContainer::iterator teamItr = GetArenaTeamMapBegin(); teamItr != GetArenaTeamMapEnd(); ++teamItr)
         if (ArenaTeam* at = teamItr->second)
         {
             at->UpdateArenaPointsHelper(PlayerPoints);
             sScriptMgr->OnBeforeUpdateArenaPoints(at, PlayerPoints);
         }
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt;
     // Cycle that gives points to all players
     for (std::map<ObjectGuid, uint32>::iterator playerItr = PlayerPoints.begin(); playerItr != PlayerPoints.end(); ++playerItr)
     {
         // Add points to player if online
         if (Player* player = ObjectAccessor::FindPlayer(playerItr->first))
             player->ModifyArenaPoints(playerItr->second, trans);
         else    // Update database
         {
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHAR_ARENA_POINTS);
             stmt->setUInt32(0, playerItr->second);
             stmt->setUInt32(1, playerItr->first.GetCounter());
             trans->Append(stmt);
         }
     }
     CharacterDatabase.CommitTransaction(trans);
     PlayerPoints.clear();
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_ONLINE_END);
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_TEAM_START);
     for (ArenaTeamContainer::iterator titr = GetArenaTeamMapBegin(); titr != GetArenaTeamMapEnd(); ++titr)
     {
         if (ArenaTeam* at = titr->second)
         {
             at->FinishWeek();
             at->SaveToDB();
             at->NotifyStatsChanged();
         }
     }
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_TEAM_END);
     sWorld->SendWorldText(LANG_DIST_ARENA_POINTS_END);
 }
References CHAR_UPD_CHAR_ARENA_POINTS, CharacterDatabase, ObjectAccessor::FindPlayer(), GetArenaTeamMapBegin(), GetArenaTeamMapEnd(), LANG_DIST_ARENA_POINTS_END, LANG_DIST_ARENA_POINTS_ONLINE_END, LANG_DIST_ARENA_POINTS_ONLINE_START, LANG_DIST_ARENA_POINTS_START, LANG_DIST_ARENA_POINTS_TEAM_END, LANG_DIST_ARENA_POINTS_TEAM_START, PreparedStatementBase::setUInt32(), sScriptMgr, and sWorld.
GenerateArenaTeamId()
uint32 ArenaTeamMgr::GenerateArenaTeamId ()
Definition at line 127 of file ArenaTeamMgr.cpp.
 {
     if (NextArenaTeamId >= MAX_ARENA_TEAM_ID)
     {
         LOG_ERROR("bg.arena", "Arena team ids overflow!! Can't continue, shutting down server. ");
         World::StopNow(ERROR_EXIT_CODE);
     }
     return NextArenaTeamId++;
 }
References ERROR_EXIT_CODE, LOG_ERROR, MAX_ARENA_TEAM_ID, NextArenaTeamId, and World::StopNow().
GenerateTempArenaTeamId()
uint32 ArenaTeamMgr::GenerateTempArenaTeamId ()
Definition at line 138 of file ArenaTeamMgr.cpp.
 {
     if (NextTempArenaTeamId >= MAX_TEMP_ARENA_TEAM_ID)
         NextTempArenaTeamId = MAX_ARENA_TEAM_ID;
     return NextTempArenaTeamId++;
 }
References MAX_ARENA_TEAM_ID, MAX_TEMP_ARENA_TEAM_ID, and NextTempArenaTeamId.
GetArenaTeamByCaptain() [1/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByCaptain (ObjectGuid guid) const
Definition at line 93 of file ArenaTeamMgr.cpp.
 {
     for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
     {
         if (itr->second->GetCaptain() == guid)
         {
             return itr->second;
         }
     }
     return nullptr;
 }
References ArenaTeamStore.
GetArenaTeamByCaptain() [2/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByCaptain (ObjectGuid guid, const uint32 type) const
Definition at line 105 of file ArenaTeamMgr.cpp.
 {
     for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
     {
         if (itr->second->GetCaptain() == guid && itr->second->GetType() == type)
         {
             return itr->second;
         }
     }
     return nullptr;
 }
References ArenaTeamStore.
GetArenaTeamById()
ArenaTeam * ArenaTeamMgr::GetArenaTeamById (uint32 arenaTeamId) const
Definition at line 48 of file ArenaTeamMgr.cpp.
 {
     ArenaTeamContainer::const_iterator itr = ArenaTeamStore.find(arenaTeamId);
     if (itr != ArenaTeamStore.end())
         return itr->second;
     return nullptr;
 }
References ArenaTeamStore.
GetArenaTeamByName() [1/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByName (std::string const & arenaTeamName) const
Definition at line 57 of file ArenaTeamMgr.cpp.
 {
     std::string search = arenaTeamName;
     std::transform(search.begin(), search.end(), search.begin(), ::toupper);
     for (ArenaTeamContainer::const_iterator itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
     {
         std::string teamName = itr->second->GetName();
         std::transform(teamName.begin(), teamName.end(), teamName.begin(), ::toupper);
         if (search == teamName)
         {
             return itr->second;
         }
     }
     return nullptr;
 }
References ArenaTeamStore.
GetArenaTeamByName() [2/2]
ArenaTeam * ArenaTeamMgr::GetArenaTeamByName (std::string const & arenaTeamName, const uint32 type) const
Definition at line 73 of file ArenaTeamMgr.cpp.
 {
     std::string search = arenaTeamName;
     std::transform(search.begin(), search.end(), search.begin(), ::toupper);
     for (auto itr = ArenaTeamStore.begin(); itr != ArenaTeamStore.end(); ++itr)
     {
         if (itr->second->GetType() != type)
         {
             continue;
         }
         std::string teamName = itr->second->GetName();
         std::transform(teamName.begin(), teamName.end(), teamName.begin(), ::toupper);
         if (search == teamName)
         {
             return itr->second;
         }
     }
     return nullptr;
 }
References ArenaTeamStore.
GetArenaTeamMapBegin()
ArenaTeamContainer::iterator ArenaTeamMgr::GetArenaTeamMapBegin () inline
Definition at line 46 of file ArenaTeamMgr.h.
 { return ArenaTeamStore.begin(); }
References ArenaTeamStore.
Referenced by DistributeArenaPoints().
GetArenaTeamMapEnd()
ArenaTeamContainer::iterator ArenaTeamMgr::GetArenaTeamMapEnd () inline
Definition at line 47 of file ArenaTeamMgr.h.
 { return ArenaTeamStore.end(); }
References ArenaTeamStore.
Referenced by DistributeArenaPoints().
GetArenaTeams()
ArenaTeamContainer& ArenaTeamMgr::GetArenaTeams () inline
Definition at line 48 of file ArenaTeamMgr.h.
 { return ArenaTeamStore; }
References ArenaTeamStore.
GetNextArenaLogId()
uint32 ArenaTeamMgr::GetNextArenaLogId () inline
Definition at line 55 of file ArenaTeamMgr.h.
 { return ++LastArenaLogId; }
References LastArenaLogId.
instance()
ArenaTeamMgr * ArenaTeamMgr::instance () static
Definition at line 41 of file ArenaTeamMgr.cpp.
 {
     static ArenaTeamMgr instance;
     return &instance;
 }
LoadArenaTeams()
void ArenaTeamMgr::LoadArenaTeams ()
Definition at line 146 of file ArenaTeamMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     // Clean out the trash before loading anything
     CharacterDatabase.Execute("DELETE FROM arena_team_member WHERE arenaTeamId NOT IN (SELECT arenaTeamId FROM arena_team)");       // One-time query
     //                                                        0        1         2         3          4              5            6            7           8
     QueryResult result = CharacterDatabase.Query("SELECT arenaTeamId, name, captainGuid, type, backgroundColor, emblemStyle, emblemColor, borderStyle, borderColor, "
                          //      9        10        11         12           13        14
                          "rating, weekGames, weekWins, seasonGames, seasonWins, `rank` FROM arena_team ORDER BY arenaTeamId ASC");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 arena teams. DB table `arena_team` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     QueryResult result2 = CharacterDatabase.Query(
                               //              0              1           2             3              4                 5          6     7          8                  9      10
                               "SELECT arenaTeamId, atm.guid, atm.weekGames, atm.weekWins, atm.seasonGames, atm.seasonWins, c.name, class, personalRating, matchMakerRating, maxMMR FROM arena_team_member atm"
                               " INNER JOIN arena_team ate USING (arenaTeamId)"
                               " LEFT JOIN characters AS c ON atm.guid = c.guid"
                               " LEFT JOIN character_arena_stats AS cas ON c.guid = cas.guid AND (cas.slot = 0 AND ate.type = 2 OR cas.slot = 1 AND ate.type = 3 OR cas.slot = 2 AND ate.type = 5)"
                               " ORDER BY atm.arenateamid ASC");
     uint32 count = 0;
     do
     {
         ArenaTeam* newArenaTeam = new ArenaTeam;
         if (!newArenaTeam->LoadArenaTeamFromDB(result) || !newArenaTeam->LoadMembersFromDB(result2))
         {
             newArenaTeam->Disband(nullptr);
             delete newArenaTeam;
             continue;
         }
         AddArenaTeam(newArenaTeam);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u arena teams in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References AddArenaTeam(), CharacterDatabase, count(), ArenaTeam::Disband(), getMSTime(), GetMSTimeDiffToNow(), ArenaTeam::LoadArenaTeamFromDB(), ArenaTeam::LoadMembersFromDB(), and LOG_INFO.
RemoveArenaTeam()
void ArenaTeamMgr::RemoveArenaTeam (uint32 Id)
Definition at line 122 of file ArenaTeamMgr.cpp.
 {
     ArenaTeamStore.erase(arenaTeamId);
 }
References ArenaTeamStore.
SetLastArenaLogId()
void ArenaTeamMgr::SetLastArenaLogId (uint32 id) inline
Definition at line 56 of file ArenaTeamMgr.h.
 { LastArenaLogId = id; }
References LastArenaLogId.
SetNextArenaTeamId()
void ArenaTeamMgr::SetNextArenaTeamId (uint32 Id) inline
Definition at line 53 of file ArenaTeamMgr.h.
 { NextArenaTeamId = Id; }
References NextArenaTeamId.
Member Data Documentation
ArenaTeamStore
ArenaTeamContainer ArenaTeamMgr::ArenaTeamStore protected
Definition at line 63 of file ArenaTeamMgr.h.
Referenced by AddArenaTeam(), GetArenaTeamByCaptain(), GetArenaTeamById(), GetArenaTeamByName(), GetArenaTeamMapBegin(), GetArenaTeamMapEnd(), GetArenaTeams(), RemoveArenaTeam(), and ~ArenaTeamMgr().
LastArenaLogId
uint32 ArenaTeamMgr::LastArenaLogId protected
Definition at line 64 of file ArenaTeamMgr.h.
Referenced by ArenaTeamMgr(), GetNextArenaLogId(), and SetLastArenaLogId().
NextArenaTeamId
uint32 ArenaTeamMgr::NextArenaTeamId protected
Definition at line 61 of file ArenaTeamMgr.h.
Referenced by ArenaTeamMgr(), GenerateArenaTeamId(), and SetNextArenaTeamId().
NextTempArenaTeamId
uint32 ArenaTeamMgr::NextTempArenaTeamId protected
Definition at line 62 of file ArenaTeamMgr.h.
Referenced by ArenaTeamMgr(), and GenerateTempArenaTeamId().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/ArenaTeamMgr.h
src/server/game/Battlegrounds/ArenaTeamMgr.cpp