Azerotcore-wotlk: WorldModelGroup Class Reference
WorldModelGroup Class Reference
#include <WorldModelGroup.h>
Public Member Functions
WorldModelGroup (std::string path, int groupIndex)
Public Attributes
ChunkedData * Data
ChunkedData * SubData
int GroupIndex
std::string Name
WMOGroupHeader Header
std::vector< uint8 > TriangleFlags
std::vector< uint8 > TriangleMaterials
std::vector< Triangle< uint16 > > Triangles
std::vector< Vector3 > Vertices
std::vector< Vector3 > Normals
uint16 * MOBA
uint32 MOBALength
bool HasLiquidData
bool IsBad
LiquidHeader LiquidDataHeader
LiquidData LiquidDataGeometry
Private Member Functions
void ReadNormals ()
void ReadLiquid ()
void ReadVertices ()
void ReadTriangles ()
void ReadMaterials ()
void ReadHeader ()
void ReadBatches ()
Detailed Description
Definition at line 23 of file WorldModelGroup.h.
Constructor & Destructor Documentation
WorldModelGroup()
WorldModelGroup::WorldModelGroup (std::string path, int groupIndex)
Definition at line 23 of file WorldModelGroup.cpp.
                                                                  : GroupIndex(groupIndex), MOBA(nullptr), IsBad(false), HasLiquidData(false)
 {
     Data = new ChunkedData(path);
     if (!Data->Stream)
     {
         IsBad = true;
         return;
     }
     Chunk* mainChunk = Data->GetChunkByName("MOGP");
     int32 firstSub = mainChunk->FindSubChunkOffset("MOPY");
     if (firstSub == -1)
         return;
     Name = Utils::GetPlainName(path.c_str());
     FILE* stream = mainChunk->GetStream();
     fseek(stream, firstSub, SEEK_SET);
     SubData = new ChunkedData(stream, mainChunk->Length - firstSub);
     ReadHeader();
     ReadMaterials();
     ReadTriangles();
     ReadVertices();
     ReadNormals();
     ReadLiquid();
     ReadBatches();
 }
References Chunk::FindSubChunkOffset(), Utils::GetPlainName(), Chunk::GetStream(), IsBad, Chunk::Length, Name, ReadBatches(), ReadHeader(), ReadLiquid(), ReadMaterials(), ReadNormals(), ReadTriangles(), ReadVertices(), and SubData.
Member Function Documentation
ReadBatches()
void WorldModelGroup::ReadBatches () private
Definition at line 149 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = Data->GetChunkByName("MOBA");
     if (!chunk)
         return;
     MOBALength = chunk->Length / 2;
     MOBA = new uint16[MOBALength];
     uint32 count = (uint32)fread(MOBA, sizeof(uint16), MOBALength, chunk->GetStream());
     if (count != MOBALength)
         printf("WorldModelGroup::ReadBatches: Error reading data, expected %u, read %u\n", MOBALength, count);
 }
References MOBA, and MOBALength.
Referenced by WorldModelGroup().
ReadHeader()
void WorldModelGroup::ReadHeader () private
Definition at line 139 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = Data->GetChunkByName("MOGP");
     if (!chunk)
         return;
     FILE* stream = chunk->GetStream();
     Header = WMOGroupHeader::Read(stream);
 }
References Header, and WMOGroupHeader::Read().
Referenced by WorldModelGroup().
ReadLiquid()
void WorldModelGroup::ReadLiquid () private
Definition at line 65 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = SubData->GetChunkByName("MLIQ");
     if (!chunk)
         return;
     HasLiquidData = true;
     FILE* stream = chunk->GetStream();
     LiquidDataHeader = LiquidHeader::Read(stream);
     LiquidDataGeometry = LiquidData::Read(stream, LiquidDataHeader);
 }
References ChunkedData::GetChunkByName(), HasLiquidData, LiquidDataGeometry, LiquidDataHeader, LiquidHeader::Read(), LiquidData::Read(), and SubData.
Referenced by WorldModelGroup().
ReadMaterials()
void WorldModelGroup::ReadMaterials () private
Definition at line 116 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = SubData->GetChunkByName("MOPY");
     if (!chunk)
         return;
     FILE* stream = chunk->GetStream();
     uint32 triangleCount = chunk->Length / 2;
     TriangleFlags.reserve(triangleCount);
     TriangleMaterials.reserve(triangleCount);
     for (uint32 i = 0; i < triangleCount; i++)
     {
         uint8 tmp;
         if (fread(&tmp, sizeof(uint8), 1, stream) != 1)
             printf("WorldModelGroup::ReadMaterials: Error reading data, expected 1, read 0\n");
         TriangleFlags.push_back(tmp);
         // Read again for material.
         if (fread(&tmp, sizeof(uint8), 1, stream) != 1)
             printf("WorldModelGroup::ReadMaterials: Error reading data, expected 1, read 0\n");
         TriangleMaterials.push_back(tmp);
     }
 }
References ChunkedData::GetChunkByName(), SubData, TriangleFlags, and TriangleMaterials.
Referenced by WorldModelGroup().
ReadNormals()
void WorldModelGroup::ReadNormals () private
Definition at line 51 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = SubData->GetChunkByName("MONR");
     if (!chunk)
         return;
     uint32 normalCount = chunk->Length / 12;
     ASSERT(normalCount == Vertices.size() && "normalCount is different than the Vertices count");
     Normals.reserve(normalCount);
     FILE* stream = chunk->GetStream();
     for (uint32 i = 0; i < normalCount; i++)
         Normals.push_back(Vector3::Read(stream));
 }
References ASSERT, ChunkedData::GetChunkByName(), Normals, Vector3::Read(), SubData, and Vertices.
Referenced by WorldModelGroup().
ReadTriangles()
void WorldModelGroup::ReadTriangles () private
Definition at line 90 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = SubData->GetChunkByName("MOVI");
     if (!chunk)
         return;
     uint32 triangleCount = chunk->Length / 6;
     ASSERT(triangleCount == TriangleFlags.size() && "triangleCount != TriangleFlags.size()");
     FILE* stream = chunk->GetStream();
     Triangles.reserve(triangleCount);
     for (uint32 i = 0; i < triangleCount; i++)
     {
         uint16 v0;
         uint16 v1;
         uint16 v2;
         int count = 0;
         count += fread(&v0, sizeof(uint16), 1, stream);
         count += fread(&v1, sizeof(uint16), 1, stream);
         count += fread(&v2, sizeof(uint16), 1, stream);
         if (count != 3)
             printf("WorldModelGroup::ReadMaterials: Error reading data, expected 3, read %d\n", count);
         Triangles.push_back(Triangle<uint16>(Constants::TRIANGLE_TYPE_WMO, v0, v1, v2));
     }
 }
References ASSERT, ChunkedData::GetChunkByName(), SubData, Constants::TRIANGLE_TYPE_WMO, TriangleFlags, and Triangles.
Referenced by WorldModelGroup().
ReadVertices()
void WorldModelGroup::ReadVertices () private
Definition at line 77 of file WorldModelGroup.cpp.
 {
     Chunk* chunk = SubData->GetChunkByName("MOVT");
     if (!chunk)
         return;
     uint32 verticeCount = chunk->Length / 12;
     Vertices.reserve(verticeCount);
     FILE* stream = chunk->GetStream();
     for (uint32 i = 0; i < verticeCount; i++)
         Vertices.push_back(Vector3::Read(stream));
 }
References ChunkedData::GetChunkByName(), Vector3::Read(), SubData, and Vertices.
Referenced by WorldModelGroup().
Member Data Documentation
Data
ChunkedData* WorldModelGroup::Data
Definition at line 27 of file WorldModelGroup.h.
GroupIndex
int WorldModelGroup::GroupIndex
Definition at line 29 of file WorldModelGroup.h.
HasLiquidData
bool WorldModelGroup::HasLiquidData
Definition at line 42 of file WorldModelGroup.h.
Referenced by ReadLiquid().
Header
WMOGroupHeader WorldModelGroup::Header
Definition at line 31 of file WorldModelGroup.h.
Referenced by ReadHeader().
IsBad
bool WorldModelGroup::IsBad
Definition at line 43 of file WorldModelGroup.h.
Referenced by WorldModelRoot::ReadGroups(), and WorldModelGroup().
LiquidDataGeometry
LiquidData WorldModelGroup::LiquidDataGeometry
Definition at line 45 of file WorldModelGroup.h.
Referenced by ReadLiquid().
LiquidDataHeader
LiquidHeader WorldModelGroup::LiquidDataHeader
Definition at line 44 of file WorldModelGroup.h.
Referenced by ReadLiquid().
MOBA
uint16* WorldModelGroup::MOBA
Definition at line 39 of file WorldModelGroup.h.
Referenced by ReadBatches().
MOBALength
uint32 WorldModelGroup::MOBALength
Definition at line 40 of file WorldModelGroup.h.
Referenced by ReadBatches().
Name
std::string WorldModelGroup::Name
Definition at line 30 of file WorldModelGroup.h.
Referenced by WorldModelGroup().
Normals
std::vector<Vector3> WorldModelGroup::Normals
Definition at line 37 of file WorldModelGroup.h.
Referenced by ReadNormals().
SubData
ChunkedData* WorldModelGroup::SubData
Definition at line 28 of file WorldModelGroup.h.
Referenced by ReadLiquid(), ReadMaterials(), ReadNormals(), ReadTriangles(), ReadVertices(), and WorldModelGroup().
TriangleFlags
std::vector<uint8> WorldModelGroup::TriangleFlags
Definition at line 33 of file WorldModelGroup.h.
Referenced by ReadMaterials(), and ReadTriangles().
TriangleMaterials
std::vector<uint8> WorldModelGroup::TriangleMaterials
Definition at line 34 of file WorldModelGroup.h.
Referenced by ReadMaterials().
Triangles
std::vector<Triangle<uint16> > WorldModelGroup::Triangles
Definition at line 35 of file WorldModelGroup.h.
Referenced by ReadTriangles().
Vertices
std::vector<Vector3> WorldModelGroup::Vertices
Definition at line 36 of file WorldModelGroup.h.
Referenced by ReadNormals(), and ReadVertices().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/WorldModelGroup.h
src/tools/mesh_extractor/WorldModelGroup.cpp