Azerotcore-wotlk: npc_wg_siege_machine::npc_wg_siege_machineAI Struct Reference
npc_wg_siege_machine::npc_wg_siege_machineAI Struct Reference
Public Member Functions
npc_wg_siege_machineAI (Creature *creature)
bool CanControlVehicle (Unit *passenger)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 checkTimer
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 692 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
npc_wg_siege_machineAI()
npc_wg_siege_machine::npc_wg_siege_machineAI::npc_wg_siege_machineAI (Creature * creature) inline
Definition at line 694 of file zone_wintergrasp.cpp.
                                                    : VehicleAI(creature)
         {
             checkTimer = 0;
         }
References checkTimer.
Member Function Documentation
CanControlVehicle()
bool npc_wg_siege_machine::npc_wg_siege_machineAI::CanControlVehicle (Unit * passenger) inline
Definition at line 701 of file zone_wintergrasp.cpp.
         {
             if (passenger->HasAura(SPELL_LIEUTENANT))
                 return true;
             if (me->GetEntry() == NPC_WINTERGRASP_CATAPULT && passenger->HasAura(SPELL_CORPORAL))
                 return true;
             return false;
         }
References Object::GetEntry(), Unit::HasAura(), CreatureAI::me, NPC_WINTERGRASP_CATAPULT, SPELL_CORPORAL, and SPELL_LIEUTENANT.
Referenced by UpdateAI().
UpdateAI()
void npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
Definition at line 712 of file zone_wintergrasp.cpp.
         {
             VehicleAI::UpdateAI(diff);
             checkTimer += diff;
             if (checkTimer >= 1000)
             {
                 checkTimer = 0;
                 if (me->GetVehicleKit())
                     for (SeatMap::iterator itr = me->GetVehicleKit()->Seats.begin(); itr != me->GetVehicleKit()->Seats.end(); ++itr)
                         if (const VehicleSeatEntry* seatInfo = itr->second.SeatInfo)
                             if (seatInfo->m_flags & VEHICLE_SEAT_FLAG_CAN_CONTROL)
                                 if (Unit* passenger = ObjectAccessor::GetUnit(*me, itr->second.Passenger.Guid))
                                     if (!CanControlVehicle(passenger))
{
                                         passenger->ExitVehicle();
                                         return;
                                     }
             }
         }
References CanControlVehicle(), checkTimer, ObjectAccessor::GetUnit(), Unit::GetVehicleKit(), CreatureAI::me, Vehicle::Seats, VehicleAI::UpdateAI(), and VEHICLE_SEAT_FLAG_CAN_CONTROL.
Member Data Documentation
checkTimer
uint32 npc_wg_siege_machine::npc_wg_siege_machineAI::checkTimer
Definition at line 699 of file zone_wintergrasp.cpp.
Referenced by npc_wg_siege_machineAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp