Azerotcore-wotlk: FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE > Class Template Reference
FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE > Class Template Reference
#include <Object.h>
Public Member Functions
FlaggedValuesArray32 ()
T_FLAGS GetFlags () const
bool HasFlag (FLAG_TYPE flag) const
void AddFlag (FLAG_TYPE flag)
void DelFlag (FLAG_TYPE flag)
T_VALUES GetValue (FLAG_TYPE flag) const
void SetValue (FLAG_TYPE flag, T_VALUES value)
void AddValue (FLAG_TYPE flag, T_VALUES value)
Private Attributes
T_VALUES m_values [ARRAY_SIZE]
T_FLAGS m_flags
Detailed Description
template<class T_VALUES, class T_FLAGS, class FLAG_TYPE, uint8 ARRAY_SIZE>
class FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >
Definition at line 621 of file Object.h.
Constructor & Destructor Documentation
FlaggedValuesArray32()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::FlaggedValuesArray32 () inline
Definition at line 624 of file Object.h.
     {
         memset(&m_values, 0x00, sizeof(T_VALUES) * ARRAY_SIZE);
         m_flags = 0;
     }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags, and FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_values.
Member Function Documentation
AddFlag()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> void FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag (FLAG_TYPE flag) inline
Definition at line 632 of file Object.h.
 { m_flags |= (1 << flag); }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags.
Referenced by GameObject::Create(), StaticTransport::Create(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply(), and Player::SetDrunkValue().
AddValue()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> void FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue (FLAG_TYPE flag, T_VALUES value) inline
Definition at line 637 of file Object.h.
 { m_values[flag] += value; }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_values.
Referenced by GameObject::Create(), StaticTransport::Create(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), AuraEffect::HandleModStealthLevel(), and spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply().
DelFlag()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> void FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag (FLAG_TYPE flag) inline
Definition at line 633 of file Object.h.
 { m_flags &= ~(1 << flag); }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags.
Referenced by AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), and Player::SetDrunkValue().
GetFlags()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> T_FLAGS FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags () const inline
Definition at line 630 of file Object.h.
 { return m_flags; }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags.
Referenced by WorldObject::CanDetectInvisibilityOf(), WorldObject::CanDetectStealthOf(), and WorldObject::CanSeeOrDetect().
GetValue()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> T_VALUES FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue (FLAG_TYPE flag) const inline
Definition at line 635 of file Object.h.
 { return m_values[flag]; }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_values.
Referenced by WorldObject::CanDetectInvisibilityOf(), WorldObject::CanDetectStealthOf(), WorldObject::CanSeeOrDetect(), and Unit::IsVisible().
HasFlag()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> bool FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::HasFlag (FLAG_TYPE flag) const inline
Definition at line 631 of file Object.h.
 { return m_flags & (1 << flag); }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags.
SetValue()
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> void FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue (FLAG_TYPE flag, T_VALUES value) inline
Definition at line 636 of file Object.h.
 { m_values[flag] = value; }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_values.
Referenced by Creature::Create(), AuraEffect::HandleAuraGhost(), Player::SetDrunkValue(), Player::SetGameMaster(), Player::SetGMVisible(), Player::SetServerSideVisibility(), Player::SetServerSideVisibilityDetect(), Unit::SetVisible(), Unit::Unit(), and WorldObject::WorldObject().
Member Data Documentation
m_flags
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> T_FLAGS FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_flags private
Definition at line 641 of file Object.h.
Referenced by FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::FlaggedValuesArray32(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), and FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::HasFlag().
m_values
template<class T_VALUES , class T_FLAGS , class FLAG_TYPE , uint8 ARRAY_SIZE> T_VALUES FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::m_values[ARRAY_SIZE] private
Definition at line 640 of file Object.h.
Referenced by FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::FlaggedValuesArray32(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), and FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/Object.h