Azerotcore-wotlk: G3D::Rect2D Class Reference
G3D::Rect2D Class Reference
#include <Rect2D.h>
Public Member Functions
Rect2D (const Any &any)
Any toAny () const
Rect2D (const Rect2D &r)
Rect2D ()
bool isEmpty () const
Rect2D (const Vector2 &wh)
Vector2 extent () const
Point2 randomPoint () const
Uniformly random point on the interior.
float width () const
float height () const
float x0 () const
float x1 () const
float y0 () const
float y1 () const
Point2 x0y0 () const
Point2 x1y0 () const
Point2 x0y1 () const
Point2 x1y1 () const
Vector2 wh () const
Point2 center () const
float area () const
bool isFinite () const
Rect2D lerp (const Rect2D &other, float alpha) const
bool contains (const Point2 &v) const
bool contains (const Rect2D &r) const
bool intersects (const Rect2D &r) const
bool intersectsOrTouches (const Rect2D &r) const
Rect2D operator* (float s) const
Rect2D operator* (const Vector2 &s) const
Rect2D operator/ (float s) const
Rect2D operator/ (const Vector2 &s) const
Rect2D operator+ (const Vector2 &v) const
Rect2D operator- (const Vector2 &v) const
bool operator== (const Rect2D &other) const
bool operator!= (const Rect2D &other) const
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Point2 corner (int i) const
Rect2D border (float delta) const
Rect2D expand (float delta) const
void merge (const Rect2D &other)
Rect2D (const Rect2D &a, const Rect2D &b)
template<class T >
void clip (const Array< T > &inPoly, Array< T > &outPoly) const
Rect2D largestCenteredSubRect (float ww, float hh) const
Rect2D intersect (const Rect2D &other) const
Static Public Member Functions
static const Rect2D & empty ()
static Rect2D xyxy (float x0, float y0, float x1, float y1)
static Rect2D xyxy (const Point2 &v0, const Point2 &v1)
static Rect2D xywh (float x, float y, float w, float h)
static Rect2D xywh (const Point2 &v, const Vector2 &w)
static Rect2D inf ()
Private Member Functions
Rect2D (bool)
Static Private Member Functions
template<class T >
static bool clipSide2D (const float p, bool clipGreater, int axis, const Array< T > &inPoly, Array< T > &outPoly)
Private Attributes
Point2 min
Point2 max
Detailed Description
If you are using this class for pixel rectangles, keep in mind that the last pixel you can draw to is at x0() + width() - 1.
Definition at line 40 of file Rect2D.h.
Constructor & Destructor Documentation
Rect2D() [1/6]
G3D::Rect2D::Rect2D (bool) inline private
Uninitialized constructor
Definition at line 121 of file Rect2D.h.
 {}
Rect2D() [2/6]
G3D::Rect2D::Rect2D (const Any & any)
Parameters
any Must either Rect2D::xywh(#, #, #, #) or Rect2D::xyxy(#, #, #, #)
Definition at line 41 of file Rect2D.cpp.
{
     if (any.name() == "Rect2D::empty" || any.name() == "AABox2D::empty") {
         *this = empty();
         return;
     }
     any.verifyName("Rect2D::xyxy", "Rect2D::xywh");
     any.verifyType(Any::ARRAY);
     any.verifySize(4);
     if (any.name() == "Rect2D::xywh") {
         *this = Rect2D::xywh(any[0], any[1], any[2], any[3]);
     } else {
         *this = Rect2D::xyxy(any[0], any[1], any[2], any[3]);
     }
 }
References G3D::any(), G3D::Any::ARRAY, empty(), xywh(), and xyxy().
Rect2D() [3/6]
G3D::Rect2D::Rect2D (const Rect2D & r) inline
Definition at line 130 of file Rect2D.h.
 : min(r.min), max(r.max) {}
Rect2D() [4/6]
G3D::Rect2D::Rect2D () inline
Creates the empty set rectangle.
Definition at line 134 of file Rect2D.h.
 : min(fnan(), fnan()), max(fnan(), fnan()) {}
Rect2D() [5/6]
G3D::Rect2D::Rect2D (const Vector2 & wh) inline
Creates a rectangle at 0,0 with the given width and height
Definition at line 144 of file Rect2D.h.
 : min(0, 0), max(wh.x, wh.y) {}
Rect2D() [6/6]
G3D::Rect2D::Rect2D (const Rect2D & a, const Rect2D & b) inline
Computes a rectangle that contains both a and b.
Note that even if or has zero area, its origin will be included.
Definition at line 397 of file Rect2D.h.
{
         *this = a;
         merge(b);
     }
References mpq::a, b, and merge().
Member Function Documentation
area()
float G3D::Rect2D::area () const inline
Definition at line 223 of file Rect2D.h.
{
         return width() * height();
     }
References height(), and width().
border()
Rect2D G3D::Rect2D::border (float delta) const inline
Deprecated:
See also
expand()
Definition at line 359 of file Rect2D.h.
{
         return Rect2D::xywh(x0() + delta,
                      y0() + delta,
                      width() - 2.0f * delta,
                      height() - 2.0f * delta);
     }
References height(), width(), x0(), xywh(), and y0().
center()
Point2 G3D::Rect2D::center () const inline
Definition at line 219 of file Rect2D.h.
{
         return (max + min) * 0.5;
     }
References max, and min.
clip()
template<class T > void G3D::Rect2D::clip (const Array< T > & inPoly, Array< T > & outPoly) const inline
Clips so that the rightmost point of the outPoly is at rect.x1 (e.g. a 800x600 window produces rightmost point 799, not 800). The results are suitable for pixel rendering if iRounded. Templated so that it will work for Vector2,3,4 (the z and w components are interpolated linearly). The template parameter must define T.lerp and contain x and y components.
If the entire polygon is clipped by a single side, the result will be empty. The result might also have zero area but not be empty.
Definition at line 412 of file Rect2D.h.
{
         const bool greaterThan = true;
         const bool lessThan    = false;
         const int  X = 0;
         const int  Y = 1;
         Array<T> temp;
         bool entirelyClipped =
           clipSide2D(x0(), lessThan,    X,    inPoly,  temp)    ||
           clipSide2D(x1(), greaterThan, X,    temp,    outPoly) ||
           clipSide2D(y0(), lessThan,    Y,    outPoly, temp)    ||
           clipSide2D(y1(), greaterThan, Y,    temp,    outPoly);
         if (entirelyClipped) {
             outPoly.clear();
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::clear(), clipSide2D(), X, x0(), x1(), Y, y0(), and y1().
clipSide2D()
template<class T > static bool G3D::Rect2D::clipSide2D (const float p, bool clipGreater, int axis, const Array< T > & inPoly, Array< T > & outPoly) inline static private
Returns true if the whole polygon is clipped.
Parameters
p Value of the point
axis Index [0 or 1] of the axis to clip along?
clipGreater Are we clipping greater than or less than the line?
inPoly Polygon being clipped
outPoly The clipped polygon
Definition at line 53 of file Rect2D.h.
{
         outPoly.clear();
         int i0 = -1;
         Vector2 pt1;
         bool c1 = true;
         float negate = clipGreater ? -1 : 1;
         // Find a point that is not clipped
         for (i0 = 0; (i0 < inPoly.length()) && c1; ++i0) {
             pt1 = inPoly[i0];
             c1  = (negate * pt1[axis]) < (negate * p);
         }
         // We incremented i0 one time to many
         --i0;
         if (c1) {
             // We could not find an unclipped point
             return true;
         }
         outPoly.append(pt1);
         // for each point in inPoly,
         //     if the point is outside the side and the previous one was also outside, continue
         //     if the point is outside the side and the previous one was inside, cut the line
         //     if the point is inside the side and the previous one was also inside, append the points
         //     if the point is inside the side and the previous one was outside, cut the line
         for (int i = 1; i <= inPoly.length(); ++i) {
             T pt2 = inPoly[(i + i0) % inPoly.length()];
             bool    c2  = (negate * pt2[axis]) < (negate * p);
             if (c1 ^ c2) {
                 if (!c1 && c2 && (i > 1)) {
                     // Unclipped to clipped trasition and not the first iteration
                     outPoly.append(pt1);
                 }
                 // only one point is clipped, find where the line crosses the clipping plane
                 float alpha;
                 if (pt2[axis] == pt1[axis]) {
                     alpha = 0;
                 } else {
                     alpha = (p - pt1[axis]) / (pt2[axis] - pt1[axis]);
                 }
                 outPoly.append(pt1.lerp(pt2, alpha));
             } else if (! (c1 || c2) && (i != 1)) {
                 // neither point is clipped (don't do this the first time
                 // because we appended the first pt before the loop)
                 outPoly.append(pt1);
             }
             pt1 = pt2;
             c1 = c2;
         }
         return false;
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Array< T, MIN_ELEMENTS >::clear(), G3D::Array< T, MIN_ELEMENTS >::length(), G3D::Vector2::lerp(), and negate().
Referenced by clip().
contains() [1/2]
bool G3D::Rect2D::contains (const Point2 & v) const inline
Definition at line 275 of file Rect2D.h.
{
         // This will automatically return false if isEmpty()
         return (v.x >= min.x) && (v.y >= min.y) && (v.x <= max.x) && (v.y <= max.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
contains() [2/2]
bool G3D::Rect2D::contains (const Rect2D & r) const inline
Definition at line 280 of file Rect2D.h.
{
         // This will automatically return false if isEmpty()
         return (min.x <= r.min.x) && (min.y <= r.min.y) &&
                (max.x >= r.max.x) && (max.y >= r.max.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
corner()
Point2 G3D::Rect2D::corner (int i) const inline
Returns the corners in the order: (min,min), (max,min), (max,max), (min,max).
Definition at line 339 of file Rect2D.h.
{
         debugAssert(i >= 0 && i < 4);
         switch (i & 3) {
         case 0:
             return Point2(min.x, min.y);
         case 1:
             return Point2(max.x, min.y);
         case 2:
             return Point2(max.x, max.y);
         case 3:
             return Point2(min.x, max.y);
         default:
             // Should never get here
             return Point2(0, 0);
         }
     }
References debugAssert, max, min, G3D::Vector2::x, and G3D::Vector2::y.
Referenced by largestCenteredSubRect().
deserialize()
void G3D::Rect2D::deserialize (class BinaryInput & b)
Definition at line 34 of file Rect2D.cpp.
{
     min.deserialize(b);
     max.deserialize(b);
 }
References b, G3D::Vector2::deserialize(), max, and min.
empty()
const Rect2D & G3D::Rect2D::empty () static
Definition at line 22 of file Rect2D.cpp.
{
     static Rect2D r;
     return r;
 }
Referenced by intersect(), and Rect2D().
expand()
Rect2D G3D::Rect2D::expand (float delta) const inline
Returns a new Rect2D that is bigger/smaller by the specified amount (negative is shrink.)
Definition at line 368 of file Rect2D.h.
{
         float newX = x0() - delta;
         float newY = y0() - delta;
         float newW = width() + 2.0f * delta;
         float newH = height() + 2.0f * delta;
         if (newW < 0.0f) {
             newX = (x0() + width()) / 2.0f;
             newW = 0.0f;
         }
         if (newH < 0.0f) {
             newY = (y0() + height()) / 2.0f;
             newH = 0.0f;
         }
         return Rect2D::xywh(newX, newY, newW, newH);
     }
References height(), width(), x0(), xywh(), and y0().
extent()
Vector2 G3D::Rect2D::extent () const inline
Definition at line 146 of file Rect2D.h.
{
         if (isEmpty()) {
             return Vector2::zero();
         } else {
             return max - min;
         }
     }
References isEmpty(), max, min, and G3D::Vector2::zero().
height()
float G3D::Rect2D::height () const inline
Definition at line 168 of file Rect2D.h.
{
         if (isEmpty()) {
             return 0;
         } else {
             return max.y - min.y;
         }
     }
References isEmpty(), max, min, and G3D::Vector2::y.
Referenced by area(), border(), G3D::GCamera::convertFromUnitToNormal(), expand(), G3D::GCamera::frustum(), G3D::GCamera::getProjectPixelMatrix(), G3D::GCamera::getProjectUnitMatrix(), largestCenteredSubRect(), toAny(), G3D::GCamera::viewportHeight(), G3D::GCamera::viewportWidth(), and G3D::GCamera::worldRay().
inf()
static Rect2D G3D::Rect2D::inf () inline static
Constructs a Rect2D with infinite boundaries. Use isFinite() to test either min or max.
Definition at line 271 of file Rect2D.h.
{
         return xyxy(Vector2::inf(), Vector2::inf());
     }
References G3D::Vector2::inf(), and xyxy().
intersect()
Rect2D G3D::Rect2D::intersect (const Rect2D & other) const inline
Returns the overlap region between the two rectangles. This may have zero area if they do not intersect. See the two-Rect2D constructor and merge() for a way to compute a union-like rectangle.
Definition at line 460 of file Rect2D.h.
{
         if (intersects(other)) {
             return Rect2D::xyxy(min.max(other.min), max.min(other.max));
         } else {
             return empty();
         }
     }
References empty(), intersects(), max, G3D::Vector2::max(), min, G3D::Vector2::min(), and xyxy().
intersects()
bool G3D::Rect2D::intersects (const Rect2D & r) const inline
True if there is non-zero area to the intersection between this and r. Note that two rectangles that are adjacent do not intersect because there is zero area to the overlap, even though one of them "contains" the corners of the other.
Definition at line 289 of file Rect2D.h.
{
         // This will automatically return false if isEmpty()
         return (min.x < r.max.x) && (min.y < r.max.y) &&
                (max.x > r.min.x) && (max.y > r.min.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
Referenced by intersect().
intersectsOrTouches()
bool G3D::Rect2D::intersectsOrTouches (const Rect2D & r) const inline
Like intersection, but counts the adjacent case as touching.
Definition at line 296 of file Rect2D.h.
{
         // This will automatically return false if isEmpty()
         return (min.x <= r.max.x) && (min.y <= r.max.y) &&
                (max.x >= r.min.x) && (max.y >= r.min.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
isEmpty()
bool G3D::Rect2D::isEmpty () const inline
Returns true if this is the empty set, which is distinct from a zero-area rectangle.
Definition at line 139 of file Rect2D.h.
{
         return min.isNaN() && max.isNaN();
     }
References G3D::Vector2::isNaN(), max, and min.
Referenced by extent(), height(), merge(), toAny(), wh(), and width().
isFinite()
bool G3D::Rect2D::isFinite () const inline
Definition at line 227 of file Rect2D.h.
{
         return (min.isFinite() && max.isFinite());
     }
References G3D::Vector2::isFinite(), max, and min.
largestCenteredSubRect()
Rect2D G3D::Rect2D::largestCenteredSubRect (float ww, float hh) const inline
Returns the largest, centered Rect2D that can fit inside this while maintaining the aspect ratio of x:y. Convenient for displaying images in odd-shaped windows.
Definition at line 437 of file Rect2D.h.
{
         float textureAspect = hh / ww;
         float viewAspect = height() / width();
         if (viewAspect > textureAspect) {
             // The view is too tall
             float h = width() * textureAspect;
             float y = (height() - h) / 2;
             return Rect2D::xywh(0, y, width(), h) + corner(0);
         } else {
             // The view is too wide
             float w = height() / textureAspect;
             float x = (width() - w) / 2;
             return Rect2D::xywh(x, 0, w, height()) + corner(0);
         }
     }
References corner(), height(), width(), G3D::x, xywh(), and G3D::y.
lerp()
Rect2D G3D::Rect2D::lerp (const Rect2D & other, float alpha) const inline
Definition at line 231 of file Rect2D.h.
{
         Rect2D out(false);
         out.min = min.lerp(other.min, alpha);
         out.max = max.lerp(other.max, alpha);
         return out;
     }
References G3D::Vector2::lerp(), max, and min.
merge()
void G3D::Rect2D::merge (const Rect2D & other) inline
Definition at line 386 of file Rect2D.h.
{
         if (isEmpty()) {
             *this = other;
         } else if (! other.isEmpty()) {
             min = min.min(other.min);
             max = max.max(other.max);
         }
     }
References isEmpty(), max, G3D::Vector2::max(), min, and G3D::Vector2::min().
Referenced by Rect2D().
operator!=()
bool G3D::Rect2D::operator!= (const Rect2D & other) const inline
Definition at line 330 of file Rect2D.h.
{
         return (min != other.min) || (max != other.max);
     }
References max, and min.
operator*() [1/2]
Rect2D G3D::Rect2D::operator* (const Vector2 & s) const inline
Definition at line 306 of file Rect2D.h.
{
         return xyxy(min * s, max * s);
     }
References max, min, and xyxy().
operator*() [2/2]
Rect2D G3D::Rect2D::operator* (float s) const inline
Definition at line 302 of file Rect2D.h.
{
         return xyxy(min.x * s, min.y * s, max.x * s, max.y * s);
     }
References max, min, G3D::Vector2::x, xyxy(), and G3D::Vector2::y.
operator+()
Rect2D G3D::Rect2D::operator+ (const Vector2 & v) const inline
Definition at line 318 of file Rect2D.h.
{
         return xyxy(min + v, max + v);
     }
References max, min, and xyxy().
operator-()
Rect2D G3D::Rect2D::operator- (const Vector2 & v) const inline
Definition at line 322 of file Rect2D.h.
{
         return xyxy(min - v, max - v);
     }
References max, min, and xyxy().
operator/() [1/2]
Rect2D G3D::Rect2D::operator/ (const Vector2 & s) const inline
Definition at line 314 of file Rect2D.h.
{
         return xyxy(min / s, max / s);
     }
References max, min, and xyxy().
operator/() [2/2]
Rect2D G3D::Rect2D::operator/ (float s) const inline
Definition at line 310 of file Rect2D.h.
{
         return xyxy(min / s, max / s);
     }
References max, min, and xyxy().
operator==()
bool G3D::Rect2D::operator== (const Rect2D & other) const inline
Definition at line 326 of file Rect2D.h.
{
         return (min == other.min) && (max == other.max);
     }
References max, and min.
randomPoint()
Point2 G3D::Rect2D::randomPoint () const inline
Uniformly random point on the interior.
Definition at line 155 of file Rect2D.h.
{
         return Point2(uniformRandom(0, max.x - min.x) + min.x,
                        uniformRandom(0, max.y - min.y) + min.y);
     }
References max, min, G3D::uniformRandom(), G3D::Vector2::x, and G3D::Vector2::y.
serialize()
void G3D::Rect2D::serialize (class BinaryOutput & b) const
Definition at line 28 of file Rect2D.cpp.
{
     min.serialize(b);
     max.serialize(b);
 }
References b, max, min, and G3D::Vector2::serialize().
toAny()
Any G3D::Rect2D::toAny () const
Converts the Rect2D to an Any.
Definition at line 59 of file Rect2D.cpp.
{
     if (isEmpty()) {
         return Any(Any::ARRAY, "Rect2D::empty");
     } else {
         Any any(Any::ARRAY, "Rect2D::xywh");
         any.append(Any(x0()), Any(y0()), Any(width()), Any(height()));
         return any;
     }
 }
References G3D::any(), G3D::Any::ARRAY, height(), isEmpty(), width(), x0(), and y0().
wh()
Vector2 G3D::Rect2D::wh () const inline
Width and height
Definition at line 211 of file Rect2D.h.
{
         if (isEmpty()) {
             return Vector2::zero();
         } else {
             return max - min;
         }
     }
References isEmpty(), max, min, and G3D::Vector2::zero().
width()
float G3D::Rect2D::width () const inline
Definition at line 160 of file Rect2D.h.
{
         if (isEmpty()) {
             return 0;
         } else {
             return max.x - min.x;
         }
     }
References isEmpty(), max, min, and G3D::Vector2::x.
Referenced by area(), border(), G3D::GCamera::convertFromUnitToNormal(), expand(), G3D::GCamera::frustum(), G3D::GCamera::getProjectPixelMatrix(), G3D::GCamera::getProjectUnitMatrix(), largestCenteredSubRect(), toAny(), G3D::GCamera::viewportHeight(), G3D::GCamera::viewportWidth(), and G3D::GCamera::worldRay().
x0()
float G3D::Rect2D::x0 () const inline
Definition at line 176 of file Rect2D.h.
                      {
         return min.x;
     }
References min, and G3D::Vector2::x.
Referenced by border(), clip(), G3D::GCamera::convertFromUnitToNormal(), G3D::Map2D< Storage, Compute >::crop(), expand(), G3D::GCamera::getProjectPixelMatrix(), G3D::Matrix4::orthogonalProjection(), toAny(), and xyxy().
x0y0()
Point2 G3D::Rect2D::x0y0 () const inline
Min, min corner
Definition at line 193 of file Rect2D.h.
{
         return min;
     }
References min.
x0y1()
Point2 G3D::Rect2D::x0y1 () const inline
Definition at line 201 of file Rect2D.h.
{
         return Point2(min.x, max.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
x1()
float G3D::Rect2D::x1 () const inline
Definition at line 180 of file Rect2D.h.
                      {
         return max.x;
     }
References max, and G3D::Vector2::x.
Referenced by clip(), G3D::Map2D< Storage, Compute >::crop(), G3D::Matrix4::orthogonalProjection(), and xyxy().
x1y0()
Point2 G3D::Rect2D::x1y0 () const inline
Definition at line 197 of file Rect2D.h.
{
         return Point2(max.x, min.y);
     }
References max, min, G3D::Vector2::x, and G3D::Vector2::y.
x1y1()
Point2 G3D::Rect2D::x1y1 () const inline
Max,max corner
Definition at line 206 of file Rect2D.h.
{
         return max;
     }
References max.
xywh() [1/2]
static Rect2D G3D::Rect2D::xywh (const Point2 & v, const Vector2 & w) inline static
Definition at line 264 of file Rect2D.h.
{
         return xyxy(v.x, v.y, v.x + w.x, v.y + w.y);
     }
References G3D::Vector2::x, xyxy(), and G3D::Vector2::y.
xywh() [2/2]
static Rect2D G3D::Rect2D::xywh (float x, float y, float w, float h) inline static
Definition at line 260 of file Rect2D.h.
{
         return xyxy(x, y, x + w, y + h);
     }
References G3D::x, xyxy(), and G3D::y.
Referenced by border(), G3D::AnyVal::deserialize(), expand(), largestCenteredSubRect(), Rect2D(), and G3D::Map2D< Storage, Compute >::rect2DBounds().
xyxy() [1/2]
static Rect2D G3D::Rect2D::xyxy (const Point2 & v0, const Point2 & v1) inline static
Definition at line 251 of file Rect2D.h.
{
         Rect2D r(false);
         r.min = v0.min(v1);
         r.max = v0.max(v1);
         return r;
     }
References max, G3D::Vector2::max(), min, and G3D::Vector2::min().
xyxy() [2/2]
static Rect2D G3D::Rect2D::xyxy (float x0, float y0, float x1, float y1) inline static
Definition at line 240 of file Rect2D.h.
{
         Rect2D r(false);
         r.min.x = G3D::min(x0, x1);
         r.min.y = G3D::min(y0, y1);
         r.max.x = G3D::max(x0, x1);
         r.max.y = G3D::max(y0, y1);
         return r;
     }
References G3D::max(), max, G3D::min(), min, G3D::Vector2::x, x0(), x1(), G3D::Vector2::y, y0(), and y1().
Referenced by G3D::Box2D::Box2D(), inf(), intersect(), operator*(), operator+(), operator-(), operator/(), Rect2D(), and xywh().
y0()
float G3D::Rect2D::y0 () const inline
Definition at line 184 of file Rect2D.h.
                      {
         return min.y;
     }
References min, and G3D::Vector2::y.
Referenced by border(), clip(), G3D::Map2D< Storage, Compute >::crop(), expand(), G3D::GCamera::getProjectPixelMatrix(), G3D::Matrix4::orthogonalProjection(), toAny(), and xyxy().
y1()
float G3D::Rect2D::y1 () const inline
Definition at line 188 of file Rect2D.h.
                      {
         return max.y;
     }
References max, and G3D::Vector2::y.
Referenced by clip(), G3D::GCamera::convertFromUnitToNormal(), G3D::Map2D< Storage, Compute >::crop(), G3D::Matrix4::orthogonalProjection(), and xyxy().
Member Data Documentation
max
Point2 G3D::Rect2D::max private
Definition at line 42 of file Rect2D.h.
Referenced by center(), contains(), corner(), deserialize(), extent(), height(), intersect(), intersects(), intersectsOrTouches(), isEmpty(), isFinite(), lerp(), merge(), operator!=(), operator*(), operator+(), operator-(), operator/(), operator==(), randomPoint(), serialize(), wh(), width(), x0y1(), x1(), x1y0(), x1y1(), xyxy(), and y1().
min
Point2 G3D::Rect2D::min private
Definition at line 42 of file Rect2D.h.
Referenced by center(), contains(), corner(), deserialize(), extent(), height(), intersect(), intersects(), intersectsOrTouches(), isEmpty(), isFinite(), lerp(), merge(), operator!=(), operator*(), operator+(), operator-(), operator/(), operator==(), randomPoint(), serialize(), wh(), width(), x0(), x0y0(), x0y1(), x1y0(), xyxy(), and y0().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Rect2D.h
deps/g3dlite/source/Rect2D.cpp