Azerotcore-wotlk: DatabaseWorkerPool< T > Class Template Reference
DatabaseWorkerPool< T > Class Template Reference
#include <DatabaseWorkerPool.h>
Public Types
typedef T::Statements PreparedStatementIndex
Public Member Functions
DatabaseWorkerPool ()
~DatabaseWorkerPool ()
void SetConnectionInfo (std::string const &infoString, uint8 const asyncThreads, uint8 const synchThreads)
uint32 Open ()
void Close ()
bool PrepareStatements ()
Prepares all prepared statements.
MySQLConnectionInfo const * GetConnectionInfo () const
void Execute (char const *sql)
template<typename Format , typename... Args>
void PExecute (Format &&sql, Args &&... args)
void Execute (PreparedStatement< T > *stmt)
void DirectExecute (char const *sql)
template<typename Format , typename... Args>
void DirectPExecute (Format &&sql, Args &&... args)
void DirectExecute (PreparedStatement< T > *stmt)
QueryResult Query (char const *sql, T *connection=nullptr)
template<typename Format , typename... Args>
QueryResult PQuery (Format &&sql, T *conn, Args &&... args)
template<typename Format , typename... Args>
QueryResult PQuery (Format &&sql, Args &&... args)
PreparedQueryResult Query (PreparedStatement< T > *stmt)
QueryCallback AsyncQuery (char const *sql)
QueryCallback AsyncQuery (PreparedStatement< T > *stmt)
SQLQueryHolderCallback DelayQueryHolder (std::shared_ptr< SQLQueryHolder< T >> holder)
SQLTransaction< T > BeginTransaction ()
Begins an automanaged transaction pointer that will automatically rollback if not commited. (Autocommit=0)
void CommitTransaction (SQLTransaction< T > transaction)
TransactionCallback AsyncCommitTransaction (SQLTransaction< T > transaction)
void DirectCommitTransaction (SQLTransaction< T > &transaction)
void ExecuteOrAppend (SQLTransaction< T > &trans, char const *sql)
void ExecuteOrAppend (SQLTransaction< T > &trans, PreparedStatement< T > *stmt)
PreparedStatement< T > * GetPreparedStatement (PreparedStatementIndex index)
void EscapeString (std::string &str)
Apply escape string'ing for current collation. (utf8)
void KeepAlive ()
Keeps all our MySQL connections alive, prevent the server from disconnecting us.
void WarnAboutSyncQueries ([[maybe_unused]] bool warn)
size_t QueueSize () const
Private Types
enum InternalIndex { IDX_ASYNC , IDX_SYNCH , IDX_SIZE }
Private Member Functions
uint32 OpenConnections (InternalIndex type, uint8 numConnections)
unsigned long EscapeString (char *to, char const *from, unsigned long length)
void Enqueue (SQLOperation *op)
T * GetFreeConnection ()
char const * GetDatabaseName () const
Private Attributes
std::unique_ptr< ProducerConsumerQueue< SQLOperation * > > _queue
Queue shared by async worker threads.
std::array< std::vector< std::unique_ptr< T > >, IDX_SIZE > _connections
std::unique_ptr< MySQLConnectionInfo > _connectionInfo
std::vector< uint8 > _preparedStatementSize
uint8 _async_threads
uint8 _synch_threads
Detailed Description
template<class T>
class DatabaseWorkerPool< T >
Definition at line 35 of file DatabaseWorkerPool.h.
Member Typedef Documentation
PreparedStatementIndex
template<class T > typedef T::Statements DatabaseWorkerPool< T >::PreparedStatementIndex
Other
Definition at line 196 of file DatabaseWorkerPool.h.
Member Enumeration Documentation
InternalIndex
template<class T > enum DatabaseWorkerPool::InternalIndex private
Enumerator
IDX_ASYNC
IDX_SYNCH
IDX_SIZE
Definition at line 38 of file DatabaseWorkerPool.h.
     {
         IDX_ASYNC,
         IDX_SYNCH,
         IDX_SIZE
     };
Constructor & Destructor Documentation
DatabaseWorkerPool()
template<class T > DatabaseWorkerPool< T >::DatabaseWorkerPool
Definition at line 61 of file DatabaseWorkerPool.cpp.
     : _queue(new ProducerConsumerQueue<SQLOperation*>()),
       _async_threads(0), _synch_threads(0)
 {
     WPFatal(mysql_thread_safe(), "Used MySQL library isn't thread-safe.");
 #if !defined(MARIADB_VERSION_ID) || MARIADB_VERSION_ID < 100600
     bool isSupportClientDB = mysql_get_client_version() >= MIN_MYSQL_CLIENT_VERSION;
     bool isSameClientDB = mysql_get_client_version() == MYSQL_VERSION_ID;
 #else // MariaDB 10.6+
     bool isSupportClientDB = mysql_get_client_version() >= MIN_MYSQL_CLIENT_VERSION;
     bool isSameClientDB    = true; // Client version 3.2.3?
 #endif
     WPFatal(isSupportClientDB, "AzerothCore does not support MySQL versions below 5.7 and MariaDB 10.2\nSearch the wiki for ACE00043 in Common Errors (https://www.azerothcore.org/wiki/common-errors).");
     WPFatal(isSameClientDB, "Used MySQL library version (%s id %lu) does not match the version id used to compile AzerothCore (id %u).\nSearch the wiki for ACE00046 in Common Errors (https://www.azerothcore.org/wiki/common-errors).",
         mysql_get_client_info(), mysql_get_client_version(), MYSQL_VERSION_ID);
 }
References MIN_MYSQL_CLIENT_VERSION, mysql_get_client_info(), mysql_get_client_version(), mysql_thread_safe(), and WPFatal.
~DatabaseWorkerPool()
template<class T > DatabaseWorkerPool< T >::~DatabaseWorkerPool
Definition at line 81 of file DatabaseWorkerPool.cpp.
 {
     _queue->Cancel();
 }
Member Function Documentation
AsyncCommitTransaction()
template<class T > TransactionCallback DatabaseWorkerPool< T >::AsyncCommitTransaction (SQLTransaction< T > transaction)
Enqueues a collection of one-way SQL operations (can be both adhoc and prepared). The order in which these operations were appended to the transaction will be respected during execution.
Definition at line 285 of file DatabaseWorkerPool.cpp.
 {
 #ifdef ACORE_DEBUG
     switch (transaction->GetSize())
     {
         case 0:
             LOG_DEBUG("sql.driver", "Transaction contains 0 queries. Not executing.");
             break;
         case 1:
             LOG_DEBUG("sql.driver", "Warning: Transaction only holds 1 query, consider removing Transaction context in code.");
             break;
         default:
             break;
     }
 #endif // ACORE_DEBUG
     TransactionWithResultTask* task = new TransactionWithResultTask(transaction);
     TransactionFuture result = task->GetFuture();
     Enqueue(task);
     return TransactionCallback(std::move(result));
 }
References TransactionWithResultTask::GetFuture(), and LOG_DEBUG.
AsyncQuery() [1/2]
template<class T > QueryCallback DatabaseWorkerPool< T >::AsyncQuery (char const * sql)
Asynchronous query (with resultset) methods. Enqueues a query in string format that will set the value of the QueryResultFuture return object as soon as the query is executed. The return value is then processed in ProcessQueryCallback methods.
Definition at line 226 of file DatabaseWorkerPool.cpp.
 {
     BasicStatementTask* task = new BasicStatementTask(sql, true);
     // Store future result before enqueueing - task might get already processed and deleted before returning from this method
     QueryResultFuture result = task->GetFuture();
     Enqueue(task);
     return QueryCallback(std::move(result));
 }
References BasicStatementTask::GetFuture().
AsyncQuery() [2/2]
template<class T > QueryCallback DatabaseWorkerPool< T >::AsyncQuery (PreparedStatement< T > * stmt)
Enqueues a query in prepared format that will set the value of the PreparedQueryResultFuture return object as soon as the query is executed. The return value is then processed in ProcessQueryCallback methods. Statement must be prepared with CONNECTION_ASYNC flag.
Definition at line 236 of file DatabaseWorkerPool.cpp.
 {
     PreparedStatementTask* task = new PreparedStatementTask(stmt, true);
     // Store future result before enqueueing - task might get already processed and deleted before returning from this method
     PreparedQueryResultFuture result = task->GetFuture();
     Enqueue(task);
     return QueryCallback(std::move(result));
 }
References PreparedStatementTask::GetFuture().
BeginTransaction()
template<class T > SQLTransaction< T > DatabaseWorkerPool< T >::BeginTransaction
Begins an automanaged transaction pointer that will automatically rollback if not commited. (Autocommit=0)
Transaction context methods.
Definition at line 256 of file DatabaseWorkerPool.cpp.
 {
     return std::make_shared<Transaction<T>>();
 }
Close()
template<class T > void DatabaseWorkerPool< T >::Close
Closes the actualy MySQL connection.
Shut down the synchronous connections There's no need for locking the connection, because DatabaseWorkerPool<>::Close should only be called after any other thread tasks in the core have exited, meaning there can be no concurrent access at this point.
Definition at line 125 of file DatabaseWorkerPool.cpp.
 {
     LOG_INFO("sql.driver", "Closing down DatabasePool '%s'.", GetDatabaseName());
     _connections[IDX_ASYNC].clear();
     LOG_INFO("sql.driver", "Asynchronous connections on DatabasePool '%s' terminated. "
                 "Proceeding with synchronous connections.",
         GetDatabaseName());
     _connections[IDX_SYNCH].clear();
     LOG_INFO("sql.driver", "All connections on DatabasePool '%s' closed.", GetDatabaseName());
 }
References LOG_INFO.
Referenced by DatabaseLoader::AddDatabase().
CommitTransaction()
template<class T > void DatabaseWorkerPool< T >::CommitTransaction (SQLTransaction< T > transaction)
Enqueues a collection of one-way SQL operations (can be both adhoc and prepared). The order in which these operations were appended to the transaction will be respected during execution.
Definition at line 262 of file DatabaseWorkerPool.cpp.
 {
 #ifdef ACORE_DEBUG
     switch (transaction->GetSize())
     {
     case 0:
         LOG_DEBUG("sql.driver", "Transaction contains 0 queries. Not executing.");
         return;
     case 1:
         LOG_DEBUG("sql.driver", "Warning: Transaction only holds 1 query, consider removing Transaction context in code.");
         break;
     default:
         break;
     }
 #endif // ACORE_DEBUG
     Enqueue(new TransactionTask(transaction));
 }
References LOG_DEBUG.
DelayQueryHolder()
template<class T > SQLQueryHolderCallback DatabaseWorkerPool< T >::DelayQueryHolder (std::shared_ptr< SQLQueryHolder< T >> holder)
Enqueues a vector of SQL operations (can be both adhoc and prepared) that will set the value of the QueryResultHolderFuture return object as soon as the query is executed. The return value is then processed in ProcessQueryCallback methods. Any prepared statements added to this holder need to be prepared with the CONNECTION_ASYNC flag.
Definition at line 246 of file DatabaseWorkerPool.cpp.
 {
     SQLQueryHolderTask* task = new SQLQueryHolderTask(holder);
     // Store future result before enqueueing - task might get already processed and deleted before returning from this method
     QueryResultHolderFuture result = task->GetFuture();
     Enqueue(task);
     return { std::move(holder), std::move(result) };
 }
References SQLQueryHolderTask::GetFuture().
DirectCommitTransaction()
template<class T > void DatabaseWorkerPool< T >::DirectCommitTransaction (SQLTransaction< T > & transaction)
Directly executes a collection of one-way SQL operations (can be both adhoc and prepared). The order in which these operations were appended to the transaction will be respected during execution.
Handle MySQL Errno 1213 without extending deadlock to the core itself
Todo:
More elegant way
Clean up now.
Definition at line 311 of file DatabaseWorkerPool.cpp.
 {
     T* connection = GetFreeConnection();
     int errorCode = connection->ExecuteTransaction(transaction);
     if (!errorCode)
     {
         connection->Unlock();      // OK, operation succesful
         return;
     }
     if (errorCode == ER_LOCK_DEADLOCK)
     {
         //todo: handle multiple sync threads deadlocking in a similar way as async threads
         uint8 loopBreaker = 5;
         for (uint8 i = 0; i < loopBreaker; ++i)
         {
             if (!connection->ExecuteTransaction(transaction))
                 break;
         }
     }
     transaction->Cleanup();
     connection->Unlock();
 }
References ER_LOCK_DEADLOCK.
DirectExecute() [1/2]
template<class T > void DatabaseWorkerPool< T >::DirectExecute (char const * sql)
Direct synchronous one-way statement methods. Directly executes a one-way SQL operation in string format, that will block the calling thread until finished. This method should only be used for queries that are only executed once, e.g during startup.
Definition at line 491 of file DatabaseWorkerPool.cpp.
 {
     if (Acore::IsFormatEmptyOrNull(sql))
         return;
     T* connection = GetFreeConnection();
     connection->Execute(sql);
     connection->Unlock();
 }
References Acore::IsFormatEmptyOrNull().
Referenced by DBUpdater< T >::Apply(), and DatabaseWorkerPool< T >::DirectPExecute().
DirectExecute() [2/2]
template<class T > void DatabaseWorkerPool< T >::DirectExecute (PreparedStatement< T > * stmt)
Directly executes a one-way SQL operation in prepared statement format, that will block the calling thread until finished. Statement must be prepared with the CONNECTION_SYNCH flag.
Delete proxy-class. Not needed anymore
Definition at line 502 of file DatabaseWorkerPool.cpp.
 {
     T* connection = GetFreeConnection();
     connection->Execute(stmt);
     connection->Unlock();
     delete stmt;
 }
DirectPExecute()
template<class T > template<typename Format , typename... Args> void DatabaseWorkerPool< T >::DirectPExecute (Format && sql, Args &&... args) inline
Directly executes a one-way SQL operation in string format -with variable args-, that will block the calling thread until finished. This method should only be used for queries that are only executed once, e.g during startup.
Definition at line 99 of file DatabaseWorkerPool.h.
     {
         if (Acore::IsFormatEmptyOrNull(sql))
             return;
         DirectExecute(Acore::StringFormat(std::forward<Format>(sql), std::forward<Args>(args)...).c_str());
     }
References DatabaseWorkerPool< T >::DirectExecute(), Acore::IsFormatEmptyOrNull(), and Acore::StringFormat().
Enqueue()
template<class T > void DatabaseWorkerPool< T >::Enqueue (SQLOperation * op) private
Definition at line 428 of file DatabaseWorkerPool.cpp.
 {
     _queue->Push(op);
 }
EscapeString() [1/2]
template<class T > unsigned long DatabaseWorkerPool< T >::EscapeString (char * to, char const * from, unsigned long length) private
Definition at line 419 of file DatabaseWorkerPool.cpp.
 {
     if (!to || !from || !length)
         return 0;
     return _connections[IDX_SYNCH].front()->EscapeString(to, from, length);
 }
References G3D::length().
EscapeString() [2/2]
template<class T > void DatabaseWorkerPool< T >::EscapeString (std::string & str)
Apply escape string'ing for current collation. (utf8)
Definition at line 347 of file DatabaseWorkerPool.cpp.
 {
     if (str.empty())
         return;
     char* buf = new char[str.size() * 2 + 1];
     EscapeString(buf, str.c_str(), uint32(str.size()));
     str = buf;
     delete[] buf;
 }
Execute() [1/2]
template<class T > void DatabaseWorkerPool< T >::Execute (char const * sql)
Delayed one-way statement methods. Enqueues a one-way SQL operation in string format that will be executed asynchronously. This method should only be used for queries that are only executed once, e.g during startup.
Definition at line 474 of file DatabaseWorkerPool.cpp.
 {
     if (Acore::IsFormatEmptyOrNull(sql))
         return;
     BasicStatementTask* task = new BasicStatementTask(sql);
     Enqueue(task);
 }
References Acore::IsFormatEmptyOrNull().
Referenced by DatabaseWorkerPool< T >::PExecute().
Execute() [2/2]
template<class T > void DatabaseWorkerPool< T >::Execute (PreparedStatement< T > * stmt)
Enqueues a one-way SQL operation in prepared statement format that will be executed asynchronously. Statement must be prepared with CONNECTION_ASYNC flag.
Definition at line 484 of file DatabaseWorkerPool.cpp.
 {
     PreparedStatementTask* task = new PreparedStatementTask(stmt);
     Enqueue(task);
 }
ExecuteOrAppend() [1/2]
template<class T > void DatabaseWorkerPool< T >::ExecuteOrAppend (SQLTransaction< T > & trans, char const * sql)
Method used to execute ad-hoc statements in a diverse context. Will be wrapped in a transaction if valid object is present, otherwise executed standalone.
Definition at line 513 of file DatabaseWorkerPool.cpp.
 {
     if (!trans)
         Execute(sql);
     else
         trans->Append(sql);
 }
ExecuteOrAppend() [2/2]
template<class T > void DatabaseWorkerPool< T >::ExecuteOrAppend (SQLTransaction< T > & trans, PreparedStatement< T > * stmt)
Method used to execute prepared statements in a diverse context. Will be wrapped in a transaction if valid object is present, otherwise executed standalone.
Definition at line 522 of file DatabaseWorkerPool.cpp.
 {
     if (!trans)
         Execute(stmt);
     else
         trans->Append(stmt);
 }
GetConnectionInfo()
template<class T > MySQLConnectionInfo const* DatabaseWorkerPool< T >::GetConnectionInfo () const inline
Definition at line 60 of file DatabaseWorkerPool.h.
     {
         return _connectionInfo.get();
     }
References DatabaseWorkerPool< T >::_connectionInfo.
Referenced by DBUpdater< T >::ApplyFile(), DBUpdater< T >::Create(), and DBUpdater< T >::Update().
GetDatabaseName()
template<class T > char const * DatabaseWorkerPool< T >::GetDatabaseName private
Definition at line 468 of file DatabaseWorkerPool.cpp.
 {
     return _connectionInfo->database.c_str();
 }
GetFreeConnection()
template<class T > T * DatabaseWorkerPool< T >::GetFreeConnection private
Gets a free connection in the synchronous connection pool. Caller MUST call t->Unlock() after touching the MySQL context to prevent deadlocks.
Block forever until a connection is free
Must be matched with t->Unlock() or you will get deadlocks
Definition at line 440 of file DatabaseWorkerPool.cpp.
 {
 #ifdef ACORE_DEBUG
     if (_warnSyncQueries)
     {
         std::ostringstream ss;
         ss << boost::stacktrace::stacktrace();
         LOG_WARN("sql.performances", "Sync query at:\n%s", ss.str().c_str());
     }
 #endif
     uint8 i = 0;
     auto const num_cons = _connections[IDX_SYNCH].size();
     T* connection = nullptr;
     for (;;)
     {
         connection = _connections[IDX_SYNCH][++i % num_cons].get();
         if (connection->LockIfReady())
             break;
     }
     return connection;
 }
References LOG_WARN.
GetPreparedStatement()
template<class T > PreparedStatement< T > * DatabaseWorkerPool< T >::GetPreparedStatement (PreparedStatementIndex index)
Automanaged (internally) pointer to a prepared statement object for usage in upper level code. Pointer is deleted in this->DirectExecute(PreparedStatement*), this->Query(PreparedStatement*) or PreparedStatementTask::~PreparedStatementTask. This object is not tied to the prepared statement on the MySQL context yet until execution.
Definition at line 341 of file DatabaseWorkerPool.cpp.
 {
     return new PreparedStatement<T>(index, _preparedStatementSize[index]);
 }
References index.
KeepAlive()
template<class T > void DatabaseWorkerPool< T >::KeepAlive
Keeps all our MySQL connections alive, prevent the server from disconnecting us.
Ping synchronous connections
Assuming all worker threads are free, every worker thread will receive 1 ping operation request If one or more worker threads are busy, the ping operations will not be split evenly, but this doesn't matter as the sole purpose is to prevent connections from idling.
Definition at line 359 of file DatabaseWorkerPool.cpp.
 {
     for (auto& connection : _connections[IDX_SYNCH])
     {
         if (connection->LockIfReady())
         {
             connection->Ping();
             connection->Unlock();
         }
     }
     auto const count = _connections[IDX_ASYNC].size();
     for (uint8 i = 0; i < count; ++i)
         Enqueue(new PingOperation);
 }
References count().
Open()
template<class T > uint32 DatabaseWorkerPool< T >::Open
Definition at line 97 of file DatabaseWorkerPool.cpp.
 {
     WPFatal(_connectionInfo.get(), "Connection info was not set!");
     LOG_INFO("sql.driver", "Opening DatabasePool '%s'. "
         "Asynchronous connections: %u, synchronous connections: %u.",
         GetDatabaseName(), _async_threads, _synch_threads);
     uint32 error = OpenConnections(IDX_ASYNC, _async_threads);
     if (error)
         return error;
     error = OpenConnections(IDX_SYNCH, _synch_threads);
     if (!error)
     {
         LOG_INFO("sql.driver", "DatabasePool '%s' opened successfully. " SZFMTD
                     " total connections running.", GetDatabaseName(),
                     (_connections[IDX_SYNCH].size() + _connections[IDX_ASYNC].size()));
     }
     LOG_INFO("sql.driver", " ");
     return error;
 }
References error(), LOG_INFO, SZFMTD, and WPFatal.
Referenced by DatabaseLoader::AddDatabase().
OpenConnections()
template<class T > uint32 DatabaseWorkerPool< T >::OpenConnections (InternalIndex type, uint8 numConnections) private
Definition at line 380 of file DatabaseWorkerPool.cpp.
 {
     for (uint8 i = 0; i < numConnections; ++i)
     {
         // Create the connection
         auto connection = [&] {
             switch (type)
             {
             case IDX_ASYNC:
                 return std::make_unique<T>(_queue.get(), *_connectionInfo);
             case IDX_SYNCH:
                 return std::make_unique<T>(*_connectionInfo);
             default:
                 ABORT();
             }
         }();
         if (uint32 error = connection->Open())
         {
             // Failed to open a connection or invalid version, abort and cleanup
             _connections[type].clear();
             return error;
         }
         else if (connection->GetServerVersion() < MIN_MYSQL_SERVER_VERSION)
         {
             LOG_ERROR("sql.driver", "AzerothCore does not support MySQL versions below 5.7");
             return 1;
         }
         else
         {
             _connections[type].push_back(std::move(connection));
         }
     }
     // Everything is fine
     return 0;
 }
References ABORT, error(), LOG_ERROR, and MIN_MYSQL_SERVER_VERSION.
PExecute()
template<class T > template<typename Format , typename... Args> void DatabaseWorkerPool< T >::PExecute (Format && sql, Args &&... args) inline
Enqueues a one-way SQL operation in string format -with variable args- that will be executed asynchronously. This method should only be used for queries that are only executed once, e.g during startup.
Definition at line 76 of file DatabaseWorkerPool.h.
     {
         if (Acore::IsFormatEmptyOrNull(sql))
             return;
         Execute(Acore::StringFormat(std::forward<Format>(sql), std::forward<Args>(args)...).c_str());
     }
References DatabaseWorkerPool< T >::Execute(), Acore::IsFormatEmptyOrNull(), and Acore::StringFormat().
PQuery() [1/2]
template<class T > template<typename Format , typename... Args> QueryResult DatabaseWorkerPool< T >::PQuery (Format && sql, Args &&... args) inline
Directly executes an SQL query in string format -with variable args- that will block the calling thread until finished. Returns reference counted auto pointer, no need for manual memory management in upper level code.
Definition at line 133 of file DatabaseWorkerPool.h.
     {
         if (Acore::IsFormatEmptyOrNull(sql))
             return QueryResult(nullptr);
         return Query(Acore::StringFormat(std::forward<Format>(sql), std::forward<Args>(args)...).c_str());
     }
References Acore::IsFormatEmptyOrNull(), DatabaseWorkerPool< T >::Query(), and Acore::StringFormat().
PQuery() [2/2]
template<class T > template<typename Format , typename... Args> QueryResult DatabaseWorkerPool< T >::PQuery (Format && sql, T * conn, Args &&... args) inline
Directly executes an SQL query in string format -with variable args- that will block the calling thread until finished. Returns reference counted auto pointer, no need for manual memory management in upper level code.
Definition at line 122 of file DatabaseWorkerPool.h.
     {
         if (Acore::IsFormatEmptyOrNull(sql))
             return QueryResult(nullptr);
         return Query(Acore::StringFormat(std::forward<Format>(sql), std::forward<Args>(args)...).c_str(), conn);
     }
References Acore::IsFormatEmptyOrNull(), DatabaseWorkerPool< T >::Query(), and Acore::StringFormat().
PrepareStatements()
template<class T > bool DatabaseWorkerPool< T >::PrepareStatements
Prepares all prepared statements.
Definition at line 146 of file DatabaseWorkerPool.cpp.
 {
     for (auto& connections : _connections)
     {
         for (auto& connection : connections)
         {
             connection->LockIfReady();
             if (!connection->PrepareStatements())
             {
                 connection->Unlock();
                 Close();
                 return false;
             }
             else
                 connection->Unlock();
             size_t const preparedSize = connection->m_stmts.size();
             if (_preparedStatementSize.size() < preparedSize)
                 _preparedStatementSize.resize(preparedSize);
             for (size_t i = 0; i < preparedSize; ++i)
             {
                 // already set by another connection
                 // (each connection only has prepared statements of it's own type sync/async)
                 if (_preparedStatementSize[i] > 0)
                     continue;
                 if (MySQLPreparedStatement* stmt = connection->m_stmts[i].get())
                 {
                     uint32 const paramCount = stmt->GetParameterCount();
                     // TC only supports uint8 indices.
                     ASSERT(paramCount < std::numeric_limits<uint8>::max());
                     _preparedStatementSize[i] = static_cast<uint8>(paramCount);
                 }
             }
         }
     }
     return true;
 }
References ASSERT, and max.
Referenced by DatabaseLoader::AddDatabase().
Query() [1/2]
template<class T > QueryResult DatabaseWorkerPool< T >::Query (char const * sql, T * connection = nullptr)
Synchronous query (with resultset) methods. Directly executes an SQL query in string format that will block the calling thread until finished. Returns reference counted auto pointer, no need for manual memory management in upper level code.
Definition at line 190 of file DatabaseWorkerPool.cpp.
 {
     if (!connection)
         connection = GetFreeConnection();
     ResultSet* result = connection->Query(sql);
     connection->Unlock();
     if (!result || !result->GetRowCount() || !result->NextRow())
     {
         delete result;
         return QueryResult(nullptr);
     }
     return QueryResult(result);
 }
Referenced by DatabaseWorkerPool< T >::PQuery(), and DBUpdater< T >::Retrieve().
Query() [2/2]
template<class T > PreparedQueryResult DatabaseWorkerPool< T >::Query (PreparedStatement< T > * stmt)
Directly executes an SQL query in prepared format that will block the calling thread until finished. Returns reference counted auto pointer, no need for manual memory management in upper level code. Statement must be prepared with CONNECTION_SYNCH flag.
Delete proxy-class. Not needed anymore
Definition at line 207 of file DatabaseWorkerPool.cpp.
 {
     auto connection = GetFreeConnection();
     PreparedResultSet* ret = connection->Query(stmt);
     connection->Unlock();
     delete stmt;
     if (!ret || !ret->GetRowCount())
     {
         delete ret;
         return PreparedQueryResult(nullptr);
     }
     return PreparedQueryResult(ret);
 }
References ret.
QueueSize()
template<class T > size_t DatabaseWorkerPool< T >::QueueSize
Definition at line 434 of file DatabaseWorkerPool.cpp.
 {
     return _queue->Size();
 }
SetConnectionInfo()
template<class T > void DatabaseWorkerPool< T >::SetConnectionInfo (std::string const & infoString, uint8 const asyncThreads, uint8 const synchThreads)
Definition at line 87 of file DatabaseWorkerPool.cpp.
 {
     _connectionInfo = std::make_unique<MySQLConnectionInfo>(infoString);
     _async_threads = asyncThreads;
     _synch_threads = synchThreads;
 }
Referenced by DatabaseLoader::AddDatabase().
WarnAboutSyncQueries()
template<class T > void DatabaseWorkerPool< T >::WarnAboutSyncQueries ([[maybe_unused] ] bool warn) inline
Definition at line 209 of file DatabaseWorkerPool.h.
     {
 #ifdef ACORE_DEBUG
         _warnSyncQueries = warn;
 #endif
     }
Member Data Documentation
_async_threads
template<class T > uint8 DatabaseWorkerPool< T >::_async_threads private
Definition at line 236 of file DatabaseWorkerPool.h.
_connectionInfo
template<class T > std::unique_ptr<MySQLConnectionInfo> DatabaseWorkerPool< T >::_connectionInfo private
Definition at line 234 of file DatabaseWorkerPool.h.
Referenced by DatabaseWorkerPool< T >::GetConnectionInfo().
_connections
template<class T > std::array<std::vector<std::unique_ptr<T> >, IDX_SIZE> DatabaseWorkerPool< T >::_connections private
Definition at line 233 of file DatabaseWorkerPool.h.
_preparedStatementSize
template<class T > std::vector<uint8> DatabaseWorkerPool< T >::_preparedStatementSize private
Definition at line 235 of file DatabaseWorkerPool.h.
_queue
template<class T > std::unique_ptr<ProducerConsumerQueue<SQLOperation*> > DatabaseWorkerPool< T >::_queue private
Queue shared by async worker threads.
Definition at line 232 of file DatabaseWorkerPool.h.
_synch_threads
template<class T > uint8 DatabaseWorkerPool< T >::_synch_threads private
Definition at line 236 of file DatabaseWorkerPool.h.
The documentation for this class was generated from the following files:
src/server/database/Database/DatabaseLoader.h
src/server/database/Database/DatabaseWorkerPool.h
src/server/database/Database/DatabaseWorkerPool.cpp