Azerotcore-wotlk: CombatAI Class Reference
CombatAI Class Reference
#include <CombatAI.h>
Public Member Functions
CombatAI (Creature *c)
void InitializeAI () override
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Protected Attributes
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Detailed Description
Definition at line 38 of file CombatAI.h.
Constructor & Destructor Documentation
CombatAI()
CombatAI::CombatAI (Creature * c) inline explicit
Definition at line 41 of file CombatAI.h.
 : CreatureAI(c) {}
Member Function Documentation
EnterCombat()
void CombatAI::EnterCombat (Unit * who) override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_boss_gothik_minion::npc_boss_gothik_minionAI, npc_crusade_persuaded::npc_crusade_persuadedAI, and CasterAI.
Definition at line 71 of file CombatAI.cpp.
 {
     for (SpellVct::iterator i = spells.begin(); i != spells.end(); ++i)
     {
         if (AISpellInfo[*i].condition == AICOND_AGGRO)
             me->CastSpell(who, *i, false);
         else if (AISpellInfo[*i].condition == AICOND_COMBAT)
             events.ScheduleEvent(*i, AISpellInfo[*i].cooldown + rand() % AISpellInfo[*i].cooldown);
     }
 }
References AICOND_AGGRO, AICOND_COMBAT, UnitAI::AISpellInfo, Unit::CastSpell(), and CreatureAI::me.
InitializeAI()
void CombatAI::InitializeAI () override virtual
Reimplemented from UnitAI.
Reimplemented in npc_pet_mage_mirror_image, npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI, and CasterAI.
Definition at line 50 of file CombatAI.cpp.
 {
     for (uint32 i = 0; i < MAX_CREATURE_SPELLS; ++i)
         if (me->m_spells[i] && sSpellMgr->GetSpellInfo(me->m_spells[i]))
             spells.push_back(me->m_spells[i]);
     CreatureAI::InitializeAI();
 }
References UnitAI::InitializeAI(), Creature::m_spells, MAX_CREATURE_SPELLS, CreatureAI::me, and sSpellMgr.
Referenced by CasterAI::InitializeAI(), and npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI::InitializeAI().
JustDied()
void CombatAI::JustDied (Unit * killer) override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_pet_dk_ghoul::npc_pet_dk_ghoulAI, and npc_boss_gothik_minion::npc_boss_gothik_minionAI.
Definition at line 64 of file CombatAI.cpp.
 {
     for (SpellVct::iterator i = spells.begin(); i != spells.end(); ++i)
         if (AISpellInfo[*i].condition == AICOND_DIE)
             me->CastSpell(killer, *i, true);
 }
References AICOND_DIE, UnitAI::AISpellInfo, Unit::CastSpell(), and CreatureAI::me.
Permissible()
static int CombatAI::Permissible (Creature const *) inline static
Definition at line 49 of file CombatAI.h.
 { return PERMIT_BASE_NO; }
References PERMIT_BASE_NO.
Reset()
void CombatAI::Reset () override virtual
Reimplemented from UnitAI.
Reimplemented in npc_pet_mage_mirror_image, npc_llod_generic::npc_llod_genericAI, npc_heated_battle::npc_heated_battleAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, npc_crusade_persuaded::npc_crusade_persuadedAI, and npc_death_knight_initiate::npc_death_knight_initiateAI.
Definition at line 59 of file CombatAI.cpp.
 {
     events.Reset();
 }
Referenced by npc_death_knight_initiate::npc_death_knight_initiateAI::Reset(), npc_heated_battle::npc_heated_battleAI::Reset(), and npc_llod_generic::npc_llod_genericAI::Reset().
UpdateAI()
void CombatAI::UpdateAI (uint32 diff) override virtual
Implements UnitAI.
Reimplemented in npc_pet_mage_mirror_image, npc_llod_generic::npc_llod_genericAI, npc_ravenous_worg::npc_ravenous_worgAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_death_knight_initiate::npc_death_knight_initiateAI, and CasterAI.
Definition at line 82 of file CombatAI.cpp.
 {
     if (!UpdateVictim())
         return;
     events.Update(diff);
     if (me->HasUnitState(UNIT_STATE_CASTING))
         return;
     if (uint32 spellId = events.ExecuteEvent())
     {
         DoCast(spellId);
         events.ScheduleEvent(spellId, AISpellInfo[spellId].cooldown + rand() % AISpellInfo[spellId].cooldown);
     }
     else
         DoMeleeAttackIfReady();
 }
References UnitAI::AISpellInfo, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), Unit::HasUnitState(), CreatureAI::me, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Referenced by npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), npc_ravenous_worg::npc_ravenous_worgAI::UpdateAI(), and npc_llod_generic::npc_llod_genericAI::UpdateAI().
Member Data Documentation
events
EventMap CombatAI::events protected
Definition at line 52 of file CombatAI.h.
spells
SpellVct CombatAI::spells protected
Definition at line 53 of file CombatAI.h.
The documentation for this class was generated from the following files:
src/server/game/AI/CoreAI/CombatAI.h
src/server/game/AI/CoreAI/CombatAI.cpp