Azerotcore-wotlk: src/server/game/Entities/Item/Container/Bag.h File Reference
Bag.h File Reference
#include "Item.h"
#include "ItemTemplate.h"
Classes
class Bag
Macros
#define MAX_BAG_SIZE 36
Functions
Item * NewItemOrBag (ItemTemplate const *proto)
Macro Definition Documentation
MAX_BAG_SIZE
#define MAX_BAG_SIZE 36
Definition at line 22 of file Bag.h.
Function Documentation
NewItemOrBag()
Item* NewItemOrBag (ItemTemplate const * proto) inline
Definition at line 66 of file Bag.h.
 {
     return (proto->InventoryType == INVTYPE_BAG) ? new Bag : new Item;
 }
References ItemTemplate::InventoryType, and INVTYPE_BAG.
Referenced by Player::_LoadItem(), Player::_LoadMailedItem(), Item::CreateItem(), AuctionHouseMgr::LoadAuctionItems(), and Guild::BankTab::LoadItemFromDB().