Azerotcore-wotlk: DoodadInstance Class Reference
DoodadInstance Class Reference
#include <Utils.h>
Public Member Functions
DoodadInstance ()
Static Public Member Functions
static DoodadInstance Read (FILE *stream)
Public Attributes
uint32 FileOffset
std::string File
Vector3 Position
float QuatW
float QuatX
float QuatY
float QuatZ
float Scale
uint32 LightColor
Detailed Description
Definition at line 211 of file Utils.h.
Constructor & Destructor Documentation
DoodadInstance()
DoodadInstance::DoodadInstance () inline
Definition at line 214 of file Utils.h.
 {}
Member Function Documentation
Read()
DoodadInstance DoodadInstance::Read (FILE * stream) static
Definition at line 384 of file Utils.cpp.
 {
     DoodadInstance ret;
     int count = 0;
     count += fread(&ret.FileOffset, sizeof(uint32), 1, stream);
     ret.Position = Vector3::Read(stream);
     count += fread(&ret.QuatW, sizeof(float), 1, stream);
     count += fread(&ret.QuatX, sizeof(float), 1, stream);
     count += fread(&ret.QuatY, sizeof(float), 1, stream);
     count += fread(&ret.QuatZ, sizeof(float), 1, stream);
     count += fread(&ret.Scale, sizeof(float), 1, stream);
     count += fread(&ret.LightColor, sizeof(uint32), 1, stream);
     if (count != 7)
         printf("DoodadInstance::Read: Failed to read some data expected 7, read %d\n", count);
     return ret;
 }
References count(), printf(), Vector3::Read(), and ret.
Referenced by WorldModelRoot::ReadDoodadInstances().
Member Data Documentation
File
std::string DoodadInstance::File
Definition at line 216 of file Utils.h.
Referenced by WorldModelRoot::ReadDoodadInstances().
FileOffset
uint32 DoodadInstance::FileOffset
Definition at line 215 of file Utils.h.
Referenced by WorldModelRoot::ReadDoodadInstances().
LightColor
uint32 DoodadInstance::LightColor
Definition at line 223 of file Utils.h.
Position
Vector3 DoodadInstance::Position
Definition at line 217 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
QuatW
float DoodadInstance::QuatW
Definition at line 218 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
QuatX
float DoodadInstance::QuatX
Definition at line 219 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
QuatY
float DoodadInstance::QuatY
Definition at line 220 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
QuatZ
float DoodadInstance::QuatZ
Definition at line 221 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
Scale
float DoodadInstance::Scale
Definition at line 222 of file Utils.h.
Referenced by Utils::TransformWmoDoodad().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp