Azerotcore-wotlk: MoveDelayed Class Reference
MoveDelayed Class Reference
Public Member Functions
MoveDelayed (Creature *owner, float x, float y, float z, float o)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
float _x
float _y
float _z
float _o
Detailed Description
Definition at line 730 of file boss_kiljaeden.cpp.
Constructor & Destructor Documentation
MoveDelayed()
MoveDelayed::MoveDelayed (Creature * owner, float x, float y, float z, float o) inline
Definition at line 733 of file boss_kiljaeden.cpp.
                                                                      : _owner(owner), _x(x), _y(y), _z(z), _o(o)
     {
     }
Member Function Documentation
Execute()
bool MoveDelayed::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 737 of file boss_kiljaeden.cpp.
     {
         Movement::MoveSplineInit init(_owner);
         init.MoveTo(_x, _y, _z, false, true);
         init.SetFacing(_o);
         init.Launch();
         return true;
     }
References _o, _owner, _x, _y, _z, Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MoveTo(), and Movement::MoveSplineInit::SetFacing().
Member Data Documentation
_o
float MoveDelayed::_o private
Definition at line 748 of file boss_kiljaeden.cpp.
Referenced by Execute().
_owner
Creature* MoveDelayed::_owner private
Definition at line 747 of file boss_kiljaeden.cpp.
Referenced by Execute().
_x
float MoveDelayed::_x private
Definition at line 748 of file boss_kiljaeden.cpp.
Referenced by Execute().
_y
float MoveDelayed::_y private
Definition at line 748 of file boss_kiljaeden.cpp.
Referenced by Execute().
_z
float MoveDelayed::_z private
Definition at line 748 of file boss_kiljaeden.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp