Azerotcore-wotlk: npc_bartleby Class Reference
npc_bartleby Class Reference
Classes
struct npc_bartlebyAI
Public Member Functions
npc_bartleby ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 49 of file zone_stormwind_city.cpp.
Constructor & Destructor Documentation
npc_bartleby()
npc_bartleby::npc_bartleby () inline
Definition at line 52 of file zone_stormwind_city.cpp.
 : CreatureScript("npc_bartleby") { }
Member Function Documentation
GetAI()
CreatureAI* npc_bartleby::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 64 of file zone_stormwind_city.cpp.
     {
         return new npc_bartlebyAI(creature);
     }
OnQuestAccept()
bool npc_bartleby::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 54 of file zone_stormwind_city.cpp.
     {
         if (quest->GetQuestId() == QUEST_BEAT)
         {
             creature->SetFaction(FACTION_ENEMY);
             creature->AI()->AttackStart(player);
         }
         return true;
     }
References Creature::AI(), UnitAI::AttackStart(), FACTION_ENEMY, Quest::GetQuestId(), QUEST_BEAT, and Unit::SetFaction().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp