Azerotcore-wotlk: npc_garments_of_quests::npc_garments_of_questsAI Struct Reference
npc_garments_of_quests::npc_garments_of_questsAI Struct Reference
Public Member Functions
npc_garments_of_questsAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpellHit (Unit *caster, SpellInfo const *spell) override
void WaypointReached (uint32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid CasterGUID
bool IsHealed
bool CanRun
uint32 RunAwayTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1240 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_garments_of_questsAI()
npc_garments_of_quests::npc_garments_of_questsAI::npc_garments_of_questsAI (Creature * creature) inline
Definition at line 1242 of file npcs_special.cpp.
                                                      : npc_escortAI(creature)
         {
             Reset();
         }
Member Function Documentation
EnterCombat()
void npc_garments_of_quests::npc_garments_of_questsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1269 of file npcs_special.cpp.
 { }
Reset()
void npc_garments_of_quests::npc_garments_of_questsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1254 of file npcs_special.cpp.
         {
             CasterGUID.Clear();
             IsHealed = false;
             CanRun = false;
             RunAwayTimer = 5000;
             me->SetPvP(true);
             me->SetStandState(UNIT_STAND_STATE_KNEEL);
             // expect database to have RegenHealth=0
             me->SetHealth(me->CountPctFromMaxHealth(70));
         }
References ObjectGuid::Clear(), and UNIT_STAND_STATE_KNEEL.
SpellHit()
void npc_garments_of_quests::npc_garments_of_questsAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1271 of file npcs_special.cpp.
         {
             if (spell->Id == SPELL_LESSER_HEAL_R2 || spell->Id == SPELL_FORTITUDE_R1)
             {
                 //not while in combat
                 if (me->IsInCombat())
                     return;
                 //nothing to be done now
                 if (IsHealed && CanRun)
                     return;
                 if (Player* player = caster->ToPlayer())
                 {
                     switch (me->GetEntry())
                     {
                         case ENTRY_SHAYA:
                             if (player->GetQuestStatus(QUEST_MOON) == QUEST_STATUS_INCOMPLETE)
{
                                 if (IsHealed && !CanRun && spell->Id == SPELL_FORTITUDE_R1)
{
                                     Talk(SAY_THANKS, caster);
                                     CanRun = true;
                                 }
                                 else if (!IsHealed && spell->Id == SPELL_LESSER_HEAL_R2)
{
                                     CasterGUID = caster->GetGUID();
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     Talk(SAY_HEALED, caster);
                                     IsHealed = true;
                                 }
                             }
                             break;
                         case ENTRY_ROBERTS:
                             if (player->GetQuestStatus(QUEST_LIGHT_1) == QUEST_STATUS_INCOMPLETE)
{
                                 if (IsHealed && !CanRun && spell->Id == SPELL_FORTITUDE_R1)
{
                                     Talk(SAY_THANKS, caster);
                                     CanRun = true;
                                 }
                                 else if (!IsHealed && spell->Id == SPELL_LESSER_HEAL_R2)
{
                                     CasterGUID = caster->GetGUID();
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     Talk(SAY_HEALED, caster);
                                     IsHealed = true;
                                 }
                             }
                             break;
                         case ENTRY_DOLF:
                             if (player->GetQuestStatus(QUEST_LIGHT_2) == QUEST_STATUS_INCOMPLETE)
{
                                 if (IsHealed && !CanRun && spell->Id == SPELL_FORTITUDE_R1)
{
                                     Talk(SAY_THANKS, caster);
                                     CanRun = true;
                                 }
                                 else if (!IsHealed && spell->Id == SPELL_LESSER_HEAL_R2)
{
                                     CasterGUID = caster->GetGUID();
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     Talk(SAY_HEALED, caster);
                                     IsHealed = true;
                                 }
                             }
                             break;
                         case ENTRY_KORJA:
                             if (player->GetQuestStatus(QUEST_SPIRIT) == QUEST_STATUS_INCOMPLETE)
{
                                 if (IsHealed && !CanRun && spell->Id == SPELL_FORTITUDE_R1)
{
                                     Talk(SAY_THANKS, caster);
                                     CanRun = true;
                                 }
                                 else if (!IsHealed && spell->Id == SPELL_LESSER_HEAL_R2)
{
                                     CasterGUID = caster->GetGUID();
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     Talk(SAY_HEALED, caster);
                                     IsHealed = true;
                                 }
                             }
                             break;
                         case ENTRY_DG_KEL:
                             if (player->GetQuestStatus(QUEST_DARKNESS) == QUEST_STATUS_INCOMPLETE)
{
                                 if (IsHealed && !CanRun && spell->Id == SPELL_FORTITUDE_R1)
{
                                     Talk(SAY_THANKS, caster);
                                     CanRun = true;
                                 }
                                 else if (!IsHealed && spell->Id == SPELL_LESSER_HEAL_R2)
{
                                     CasterGUID = caster->GetGUID();
                                     me->SetStandState(UNIT_STAND_STATE_STAND);
                                     Talk(SAY_HEALED, caster);
                                     IsHealed = true;
                                 }
                             }
                             break;
                     }
                     // give quest credit, not expect any special quest objectives
                     if (CanRun)
                         player->TalkedToCreature(me->GetEntry(), me->GetGUID());
                 }
             }
         }
References ENTRY_DG_KEL, ENTRY_DOLF, ENTRY_KORJA, ENTRY_ROBERTS, ENTRY_SHAYA, Object::GetGUID(), SpellInfo::Id, QUEST_DARKNESS, QUEST_LIGHT_1, QUEST_LIGHT_2, QUEST_MOON, QUEST_SPIRIT, QUEST_STATUS_INCOMPLETE, SAY_HEALED, SAY_THANKS, SPELL_FORTITUDE_R1, SPELL_LESSER_HEAL_R2, Object::ToPlayer(), and UNIT_STAND_STATE_STAND.
UpdateAI()
void npc_garments_of_quests::npc_garments_of_questsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1385 of file npcs_special.cpp.
         {
             if (CanRun && !me->IsInCombat())
             {
                 if (RunAwayTimer <= diff)
                 {
                     if (Unit* unit = ObjectAccessor::GetUnit(*me, CasterGUID))
                     {
                         switch (me->GetEntry())
{
                             case ENTRY_SHAYA:
                             case ENTRY_ROBERTS:
                             case ENTRY_DOLF:
                             case ENTRY_KORJA:
                             case ENTRY_DG_KEL:
                                 Talk(SAY_GOODBYE, unit);
                                 break;
                         }
                         Start(false, true);
                     }
                     else
                         EnterEvadeMode();                       //something went wrong
                     RunAwayTimer = 30000;
                 }
                 else
                     RunAwayTimer -= diff;
             }
             npc_escortAI::UpdateAI(diff);
         }
References ENTRY_DG_KEL, ENTRY_DOLF, ENTRY_KORJA, ENTRY_ROBERTS, ENTRY_SHAYA, ObjectAccessor::GetUnit(), SAY_GOODBYE, and npc_escortAI::UpdateAI().
WaypointReached()
void npc_garments_of_quests::npc_garments_of_questsAI::WaypointReached (uint32) inline override virtual
Implements npc_escortAI.
Definition at line 1381 of file npcs_special.cpp.
         {
         }
Member Data Documentation
CanRun
bool npc_garments_of_quests::npc_garments_of_questsAI::CanRun
Definition at line 1250 of file npcs_special.cpp.
CasterGUID
ObjectGuid npc_garments_of_quests::npc_garments_of_questsAI::CasterGUID
Definition at line 1247 of file npcs_special.cpp.
IsHealed
bool npc_garments_of_quests::npc_garments_of_questsAI::IsHealed
Definition at line 1249 of file npcs_special.cpp.
RunAwayTimer
uint32 npc_garments_of_quests::npc_garments_of_questsAI::RunAwayTimer
Definition at line 1252 of file npcs_special.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/World/npcs_special.cpp