Azerotcore-wotlk: BattlegroundNA Class Reference
BattlegroundNA Class Reference
#include <BattlegroundNA.h>
Public Member Functions
BattlegroundNA ()
~BattlegroundNA () override
void AddPlayer (Player *player) override
void StartingEventCloseDoors () override
void StartingEventOpenDoors () override
void RemovePlayer (Player *player) override
void HandleAreaTrigger (Player *player, uint32 trigger) override
bool SetupBattleground () override
void Init () override
void FillInitialWorldStates (WorldPacket &d) override
void HandleKillPlayer (Player *player, Player *killer) override
bool HandlePlayerUnderMap (Player *player) override
Public Member Functions inherited from Battleground
Battleground ()
virtual ~Battleground ()
void Update (uint32 diff)
virtual void ResetBGSubclass ()
virtual void DestroyGate (Player *, GameObject *)
virtual bool AllNodesConrolledByTeam (TeamId) const
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
char const * GetName () const
BattlegroundTypeId GetBgTypeID (bool GetRandom=false) const
uint32 GetInstanceID () const
BattlegroundStatus GetStatus () const
uint32 GetClientInstanceID () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetLastResurrectTime () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
uint8 GetArenaType () const
TeamId GetWinner () const
uint32 GetScriptId () const
uint32 GetBonusHonorFromKill (uint32 kills) const
bool IsRandom ()
void SetName (char const *Name)
void SetBgTypeID (BattlegroundTypeId TypeID)
void SetRandomTypeID (BattlegroundTypeId TypeID)
void SetInstanceID (uint32 InstanceID)
void SetStatus (BattlegroundStatus Status)
void SetClientInstanceID (uint32 InstanceID)
void SetStartTime (uint32 Time)
void SetEndTime (uint32 Time)
void SetLastResurrectTime (uint32 Time)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (uint8 type)
void SetArenaorBGType (bool _isArena)
void SetWinner (TeamId winner)
void SetScriptId (uint32 scriptId)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int32 diff)
void SetStartDelayTime (int32 Time)
void SetMaxPlayersPerTeam (uint32 MaxPlayers)
void SetMinPlayersPerTeam (uint32 MinPlayers)
void DecreaseInvitedCount (TeamId teamId)
void IncreaseInvitedCount (TeamId teamId)
uint32 GetInvitedCount (TeamId teamId) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (TeamId teamId) const
uint32 GetMaxFreeSlots () const
void AddSpectator (Player *p)
void RemoveSpectator (Player *p)
bool HaveSpectators ()
const SpectatorList & GetSpectators () const
void AddToBeTeleported (ObjectGuid spectator, ObjectGuid participant)
void RemoveToBeTeleported (ObjectGuid spectator)
void SpectatorsSendPacket (WorldPacket &data)
bool isArena () const
bool isBattleground () const
bool isRated () const
BattlegroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
void ReadyMarkerClicked (Player *p)
BattlegroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattlegroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
uint32 GetReviveQueueSize () const
void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (Player *player)
void RelocateDeadPlayers (ObjectGuid queueIndex)
Relocate all players in ReviveQueue to the closest graveyard.
void StartBattleground ()
GameObject * GetBGObject (uint32 type)
Creature * GetBGCreature (uint32 type)
void SetMapId (uint32 MapID)
uint32 GetMapId () const
void SetBgMap (BattlegroundMap *map)
BattlegroundMap * GetBgMap () const
BattlegroundMap * FindBgMap () const
void SetTeamStartLoc (TeamId teamId, float X, float Y, float Z, float O)
void GetTeamStartLoc (TeamId teamId, float &X, float &Y, float &Z, float &O) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
void SendPacketToTeam (TeamId teamId, WorldPacket *packet, Player *sender=nullptr, bool self=true)
void SendPacketToAll (WorldPacket *packet)
void YellToAll (Creature *creature, const char *text, uint32 language)
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToAll (uint32 soundId)
void CastSpellOnTeam (uint32 spellId, TeamId teamId)
void RemoveAuraOnTeam (uint32 spellId, TeamId teamId)
void RewardHonorToTeam (uint32 honor, TeamId teamId)
void RewardReputationToTeam (uint32 factionId, uint32 reputation, TeamId teamId)
uint32 GetRealRepFactionForPlayer (uint32 factionId, Player *player)
void UpdateWorldState (uint32 Field, uint32 Value)
void UpdateWorldStateForPlayer (uint32 Field, uint32 Value, Player *player)
virtual void EndBattleground (TeamId winnerTeamId)
void BlockMovement (Player *player)
void SendWarningToAll (uint32 entry,...)
void SendMessageToAll (uint32 entry, ChatMsg type, Player const *source=nullptr)
void PSendMessageToAll (uint32 entry, ChatMsg type, Player const *source,...)
void SendMessage2ToAll (uint32 entry, ChatMsg type, Player const *source, uint32 strId1=0, uint32 strId2=0)
Group * GetBgRaid (TeamId teamId) const
void SetBgRaid (TeamId teamId, Group *bg_raid)
virtual void UpdatePlayerScore (Player *player, uint32 type, uint32 value, bool doAddHonor=true)
uint32 GetPlayersCountByTeam (TeamId teamId) const
uint32 GetAlivePlayersCountByTeam (TeamId teamId) const
void UpdatePlayersCountByTeam (TeamId teamId, bool remove)
void SetArenaTeamIdForTeam (TeamId teamId, uint32 ArenaTeamId)
uint32 GetArenaTeamIdForTeam (TeamId teamId) const
void SetArenaTeamRatingChangeForTeam (TeamId teamId, int32 RatingChange)
int32 GetArenaTeamRatingChangeForTeam (TeamId teamId) const
void SetArenaMatchmakerRating (TeamId teamId, uint32 MMR)
uint32 GetArenaMatchmakerRating (TeamId teamId) const
void CheckArenaAfterTimerConditions ()
void CheckArenaWinConditions ()
virtual void UpdateArenaWorldState ()
virtual void HandleKillUnit (Creature *, Player *)
virtual void EventPlayerDroppedFlag (Player *)
virtual void EventPlayerClickedOnFlag (Player *, GameObject *)
virtual void EventPlayerDamagedGO (Player *, GameObject *, uint32)
virtual void EventPlayerUsedGO (Player *, GameObject *)
virtual void DoAction (uint32, ObjectGuid)
virtual void HandlePlayerResurrect (Player *)
virtual GraveyardStruct const * GetClosestGraveyard (Player *player)
void AddOrSetPlayerToCorrectBgGroup (Player *player, TeamId teamId)
void RemovePlayerAtLeave (Player *player)
void HandleTriggerBuff (GameObject *gameObject)
void SetHoliday (bool is_holiday)
void SpawnBGObject (uint32 type, uint32 respawntime, uint32 forceRespawnDelay=0)
bool AddObject (uint32 type, uint32 entry, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime=0, GOState goState=GO_STATE_READY)
Creature * AddCreature (uint32 entry, uint32 type, float x, float y, float z, float o, uint32 respawntime=0, MotionTransport *transport=nullptr)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool AddSpiritGuide (uint32 type, float x, float y, float z, float o, TeamId teamId)
int32 GetObjectType (ObjectGuid guid)
void DoorOpen (uint32 type)
void DoorClose (uint32 type)
const char * GetAcoreString (int32 entry)
bool IsPlayerInBattleground (ObjectGuid guid) const
bool ToBeDeleted () const
void RewardXPAtKill (Player *killer, Player *victim)
virtual ObjectGuid GetFlagPickerGUID (TeamId=TEAM_NEUTRAL) const
virtual void SetDroppedFlagGUID (ObjectGuid, TeamId=TEAM_NEUTRAL)
uint32 GetTeamScore (TeamId teamId) const
virtual TeamId GetPrematureWinner ()
uint8 GetUniqueBracketId () const
BattlegroundAV * ToBattlegroundAV ()
BattlegroundAV const * ToBattlegroundAV () const
BattlegroundWS * ToBattlegroundWS ()
BattlegroundWS const * ToBattlegroundWS () const
BattlegroundAB * ToBattlegroundAB ()
BattlegroundAB const * ToBattlegroundAB () const
BattlegroundNA * ToBattlegroundNA ()
BattlegroundNA const * ToBattlegroundNA () const
BattlegroundBE * ToBattlegroundBE ()
BattlegroundBE const * ToBattlegroundBE () const
BattlegroundEY * ToBattlegroundEY ()
BattlegroundEY const * ToBattlegroundEY () const
BattlegroundRL * ToBattlegroundRL ()
BattlegroundRL const * ToBattlegroundRL () const
BattlegroundSA * ToBattlegroundSA ()
BattlegroundSA const * ToBattlegroundSA () const
BattlegroundDS * ToBattlegroundDS ()
BattlegroundDS const * ToBattlegroundDS () const
BattlegroundRV * ToBattlegroundRV ()
BattlegroundRV const * ToBattlegroundRV () const
BattlegroundIC * ToBattlegroundIC ()
BattlegroundIC const * ToBattlegroundIC () const
Additional Inherited Members
Public Types inherited from Battleground
typedef std::set< Player * > SpectatorList
typedef std::map< ObjectGuid, ObjectGuid > ToBeTeleportedMap
typedef std::map< ObjectGuid, Player * > BattlegroundPlayerMap
typedef std::map< ObjectGuid, BattlegroundScore * > BattlegroundScoreMap
typedef std::map< ObjectGuid, ArenaLogEntryData > ArenaLogEntryDataMap
typedef GuidVector BGObjects
typedef GuidVector BGCreatures
Static Public Member Functions inherited from Battleground
static TeamId GetOtherTeamId (TeamId teamId)
Public Attributes inherited from Battleground
GuidSet readyMarkerClickedSet
ArenaLogEntryDataMap ArenaLogEntries
BGObjects BgObjects
BGCreatures BgCreatures
Protected Member Functions inherited from Battleground
void EndNow ()
void PlayerAddedToBGCheckIfBGIsRunning (Player *player)
void _ProcessResurrect (uint32 diff)
void _ProcessProgress (uint32 diff)
void _ProcessLeave (uint32 diff)
void _ProcessJoin (uint32 diff)
void _CheckSafePositions (uint32 diff)
Protected Attributes inherited from Battleground
BattlegroundScoreMap PlayerScores
BattlegroundPlayerMap m_Players
std::map< ObjectGuid, GuidVector > m_ReviveQueue
uint8 m_Events
BattlegroundStartTimeIntervals StartDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 StartMessageIds [BG_STARTING_EVENT_COUNT]
bool m_BuffChange
bool m_IsRandom
BGHonorMode m_HonorMode
int32 m_TeamScores [BG_TEAMS_COUNT]
uint32 m_UpdateTimer
Detailed Description
Definition at line 46 of file BattlegroundNA.h.
Constructor & Destructor Documentation
BattlegroundNA()
BattlegroundNA::BattlegroundNA ()
Definition at line 26 of file BattlegroundNA.cpp.
 {
     BgObjects.resize(BG_NA_OBJECT_MAX);
     StartDelayTimes[BG_STARTING_EVENT_FIRST]  = BG_START_DELAY_1M;
     StartDelayTimes[BG_STARTING_EVENT_SECOND] = BG_START_DELAY_30S;
     StartDelayTimes[BG_STARTING_EVENT_THIRD]  = BG_START_DELAY_15S;
     StartDelayTimes[BG_STARTING_EVENT_FOURTH] = BG_START_DELAY_NONE;
     //we must set messageIds
     StartMessageIds[BG_STARTING_EVENT_FIRST]  = LANG_ARENA_ONE_MINUTE;
     StartMessageIds[BG_STARTING_EVENT_SECOND] = LANG_ARENA_THIRTY_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_THIRD]  = LANG_ARENA_FIFTEEN_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_FOURTH] = LANG_ARENA_HAS_BEGUN;
 }
References BG_NA_OBJECT_MAX, BG_START_DELAY_15S, BG_START_DELAY_1M, BG_START_DELAY_30S, BG_START_DELAY_NONE, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, Battleground::BgObjects, LANG_ARENA_FIFTEEN_SECONDS, LANG_ARENA_HAS_BEGUN, LANG_ARENA_ONE_MINUTE, LANG_ARENA_THIRTY_SECONDS, Battleground::StartDelayTimes, and Battleground::StartMessageIds.
~BattlegroundNA()
BattlegroundNA::~BattlegroundNA () override
Definition at line 41 of file BattlegroundNA.cpp.
 {
 }
Member Function Documentation
AddPlayer()
void BattlegroundNA::AddPlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 60 of file BattlegroundNA.cpp.
 {
     Battleground::AddPlayer(player);
     PlayerScores[player->GetGUID()] = new BattlegroundScore(player);
     Battleground::UpdateArenaWorldState();
 }
References Battleground::AddPlayer(), Object::GetGUID(), Battleground::PlayerScores, and Battleground::UpdateArenaWorldState().
FillInitialWorldStates()
void BattlegroundNA::FillInitialWorldStates (WorldPacket & d) override virtual
Reimplemented from Battleground.
Definition at line 118 of file BattlegroundNA.cpp.
 {
     data << uint32(0xa11) << uint32(1);           // 9
     Battleground::UpdateArenaWorldState();
 }
References Battleground::UpdateArenaWorldState().
HandleAreaTrigger()
void BattlegroundNA::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from Battleground.
Definition at line 99 of file BattlegroundNA.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     switch (trigger)
     {
         case 4536:                                          // buff trigger?
         case 4537:                                          // buff trigger?
             break;
         // OUTSIDE OF ARENA, TELEPORT!
         case 4917:
         case 5006:
         case 5008:
             player->NearTeleportTo(4054.15f, 2923.7f, 13.4f, player->GetOrientation());
             break;
     }
 }
References Position::GetOrientation(), Battleground::GetStatus(), Unit::NearTeleportTo(), and STATUS_IN_PROGRESS.
HandleKillPlayer()
void BattlegroundNA::HandleKillPlayer (Player * player, Player * killer) override virtual
Reimplemented from Battleground.
Definition at line 76 of file BattlegroundNA.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     if (!killer)
     {
         LOG_ERROR("bg.battleground", "BattlegroundNA: Killer player not found");
         return;
     }
     Battleground::HandleKillPlayer(player, killer);
     Battleground::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), Battleground::HandleKillPlayer(), LOG_ERROR, STATUS_IN_PROGRESS, and Battleground::UpdateArenaWorldState().
HandlePlayerUnderMap()
bool BattlegroundNA::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 93 of file BattlegroundNA.cpp.
 {
     player->NearTeleportTo(4055.504395f, 2919.660645f, 13.611241f, player->GetOrientation());
     return true;
 }
References Position::GetOrientation(), and Unit::NearTeleportTo().
Init()
void BattlegroundNA::Init () override virtual
Reimplemented from Battleground.
Definition at line 124 of file BattlegroundNA.cpp.
 {
     //call parent's class reset
     Battleground::Init();
 }
References Battleground::Init().
RemovePlayer()
void BattlegroundNA::RemovePlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 67 of file BattlegroundNA.cpp.
 {
     if (GetStatus() == STATUS_WAIT_LEAVE)
         return;
     Battleground::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), STATUS_WAIT_LEAVE, and Battleground::UpdateArenaWorldState().
SetupBattleground()
bool BattlegroundNA::SetupBattleground () override virtual
Reimplemented from Battleground.
Definition at line 130 of file BattlegroundNA.cpp.
 {
     // gates
     if (   !AddObject(BG_NA_OBJECT_DOOR_1, BG_NA_OBJECT_TYPE_DOOR_1, 4031.854f, 2966.833f, 12.0462f,  -2.648788f, 0, 0, 0.9697962f, -0.2439165f, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_NA_OBJECT_DOOR_2, BG_NA_OBJECT_TYPE_DOOR_2, 4081.179f, 2874.97f,  12.00171f, 0.4928045f, 0, 0, 0.2439165f, 0.9697962f,  RESPAWN_IMMEDIATELY)
             || !AddObject(BG_NA_OBJECT_DOOR_3, BG_NA_OBJECT_TYPE_DOOR_3, 4023.709f, 2981.777f, 10.70117f, -2.648788f, 0, 0, 0.9697962f, -0.2439165f, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_NA_OBJECT_DOOR_4, BG_NA_OBJECT_TYPE_DOOR_4, 4090.064f, 2858.438f, 10.23631f, 0.4928045f, 0, 0, 0.2439165f,  0.9697962f, RESPAWN_IMMEDIATELY)
             // buffs
             || !AddObject(BG_NA_OBJECT_BUFF_1, BG_NA_OBJECT_TYPE_BUFF_1, 4009.189941f, 2895.250000f, 13.052700f, -1.448624f, 0, 0, 0.6626201f, -0.7489557f, 120)
             || !AddObject(BG_NA_OBJECT_BUFF_2, BG_NA_OBJECT_TYPE_BUFF_2, 4103.330078f, 2946.350098f, 13.051300f, -0.06981307f, 0, 0, 0.03489945f, -0.9993908f, 120)
             // Arena Ready Marker
             || !AddObject(BG_NA_OBJECT_READY_MARKER_1, ARENA_READY_MARKER_ENTRY, 4090.46f, 2875.43f, 12.16f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
             || !AddObject(BG_NA_OBJECT_READY_MARKER_2, ARENA_READY_MARKER_ENTRY, 4022.82f, 2966.61f, 12.17f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300))
     {
         LOG_ERROR("sql.sql", "BatteGroundNA: Failed to spawn some object!");
         return false;
     }
     return true;
 }
References Battleground::AddObject(), ARENA_READY_MARKER_ENTRY, BG_NA_OBJECT_BUFF_1, BG_NA_OBJECT_BUFF_2, BG_NA_OBJECT_DOOR_1, BG_NA_OBJECT_DOOR_2, BG_NA_OBJECT_DOOR_3, BG_NA_OBJECT_DOOR_4, BG_NA_OBJECT_READY_MARKER_1, BG_NA_OBJECT_READY_MARKER_2, BG_NA_OBJECT_TYPE_BUFF_1, BG_NA_OBJECT_TYPE_BUFF_2, BG_NA_OBJECT_TYPE_DOOR_1, BG_NA_OBJECT_TYPE_DOOR_2, BG_NA_OBJECT_TYPE_DOOR_3, BG_NA_OBJECT_TYPE_DOOR_4, LOG_ERROR, and RESPAWN_IMMEDIATELY.
StartingEventCloseDoors()
void BattlegroundNA::StartingEventCloseDoors () override virtual
Reimplemented from Battleground.
Definition at line 45 of file BattlegroundNA.cpp.
 {
     for (uint32 i = BG_NA_OBJECT_DOOR_1; i <= BG_NA_OBJECT_DOOR_4; ++i)
         SpawnBGObject(i, RESPAWN_IMMEDIATELY);
 }
References BG_NA_OBJECT_DOOR_1, BG_NA_OBJECT_DOOR_4, RESPAWN_IMMEDIATELY, and Battleground::SpawnBGObject().
StartingEventOpenDoors()
void BattlegroundNA::StartingEventOpenDoors () override virtual
Reimplemented from Battleground.
Definition at line 51 of file BattlegroundNA.cpp.
 {
     for (uint32 i = BG_NA_OBJECT_DOOR_1; i <= BG_NA_OBJECT_DOOR_2; ++i)
         DoorOpen(i);
     for (uint32 i = BG_NA_OBJECT_BUFF_1; i <= BG_NA_OBJECT_BUFF_2; ++i)
         SpawnBGObject(i, 60);
 }
References BG_NA_OBJECT_BUFF_1, BG_NA_OBJECT_BUFF_2, BG_NA_OBJECT_DOOR_1, BG_NA_OBJECT_DOOR_2, Battleground::DoorOpen(), and Battleground::SpawnBGObject().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/Zones/BattlegroundNA.h
src/server/game/Battlegrounds/Zones/BattlegroundNA.cpp