Azerotcore-wotlk: npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI Struct Reference
npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI Struct Reference
Public Member Functions
npc_pos_martin_or_gorkun_secondAI (Creature *creature)
void MovementInform (uint32 type, uint32 id) override
void DoAction (int32 p) override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint8 i
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 918 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
npc_pos_martin_or_gorkun_secondAI()
npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI (Creature * creature) inline
Definition at line 920 of file pit_of_saron.cpp.
                                                               : NullCreatureAI(creature), summons(me)
         {
             pInstance = me->GetInstanceScript();
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
             i = 0;
             events.Reset();
             events.RescheduleEvent(1, 500);
             events.RescheduleEvent(2, 15000);
             if (pInstance)
                 if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_GUID)))
                 {
                     c->AI()->Talk(SAY_PREFIGHT_1);
                     c->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                     c->SetReactState(REACT_AGGRESSIVE);
                     //c->ClearUnitState(UNIT_STATE_ONVEHICLE);
                     if (Player* plr = c->SelectNearestPlayer(100.0f))
                     {
                         c->AI()->AttackStart(plr);
                         DoZoneInCombat(c);
                     }
                 }
         }
References mpq::c, DATA_TYRANNUS_GUID, CreatureAI::DoZoneInCombat(), EMOTE_STATE_READY1H, Map::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), i, InstanceScript::instance, CreatureAI::me, pInstance, REACT_AGGRESSIVE, SAY_PREFIGHT_1, Object::SetUInt32Value(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_NPC_EMOTESTATE.
Member Function Documentation
DoAction()
void npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction (int32 p) inline override virtual
Reimplemented from UnitAI.
Definition at line 957 of file pit_of_saron.cpp.
         {
             if (p == 1)
                 summons.DespawnAll();
             else if (p == 2)
             {
                 events.Reset();
                 summons.DespawnEntry(NPC_FALLEN_WARRIOR);
                 if (!pInstance)
                     return;
                 me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                 me->GetMotionMaster()->MovePoint(2, TSCenterPos);
                 TSSpawnPos.GetAngle(&TSMidPos);
                 for (ObjectGuid const& guid : summons)
                     if (Creature* c = pInstance->instance->GetCreature(guid))
                     {
                         float hx, hy, hz, ho;
                         c->GetHomePosition(hx, hy, hz, ho);
                         c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_CHEER);
                         float ang = frand(1.92f, 2.36f);
                         float dist = urand(50, 85);
                         c->GetMotionMaster()->MovePoint(0, TSSpawnPos.GetPositionX() + cos(ang)*dist, TSSpawnPos.GetPositionY() + sin(ang)*dist, 628.2f);
                     }
             }
             else if (p == 3)
             {
                 if (pInstance)
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_SINDRAGOSA_GUID)))
                     {
                         for (ObjectGuid const& guid : summons)
                             if (Creature* s = pInstance->instance->GetCreature(guid))
                                 if (s->IsAlive())
                                     Unit::Kill(c, s);
                         if (me->IsAlive())
                             Unit::Kill(c, me);
                     }
             }
         }
References mpq::c, DATA_SINDRAGOSA_GUID, SummonList::DespawnAll(), SummonList::DespawnEntry(), EMOTE_ONESHOT_CHEER, EMOTE_ONESHOT_NONE, G3D::frand(), Position::GetAngle(), Map::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, Unit::IsAlive(), Unit::Kill(), CreatureAI::me, MotionMaster::MovePoint(), NPC_FALLEN_WARRIOR, pInstance, Object::SetUInt32Value(), summons, TSCenterPos, TSMidPos, TSSpawnPos, UNIT_NPC_EMOTESTATE, and urand().
JustSummoned()
void npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1000 of file pit_of_saron.cpp.
         {
             summons.Summon(s);
         }
References SummonList::Summon(), and summons.
MovementInform()
void npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 949 of file pit_of_saron.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == 2)
             {
                 events.RescheduleEvent(5, 1000);
             }
         }
References POINT_MOTION_TYPE.
SummonedCreatureDespawn()
void npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1005 of file pit_of_saron.cpp.
         {
             summons.Despawn(s);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 1010 of file pit_of_saron.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     if (TSData[i].entry)
                     {
                         if (Creature* c = me->SummonCreature(TSData[i].entry, TSSpawnPos))
{
                             c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                             c->GetMotionMaster()->MovePoint(0, TSData[i].x, TSData[i].y, TSHeight);
                         }
                         ++i;
                         events.ScheduleEvent(1, 150);
                     }
                     break;
                 case 2:
                     Talk(me->GetEntry() == NPC_MARTIN_VICTUS_2 ? SAY_GENERAL_ALLIANCE_TRASH : SAY_GENERAL_HORDE_TRASH);
                     events.RescheduleEvent(3, 8000);
                     break;
                 case 3:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_GUID)))
                             c->AI()->Talk(SAY_PREFIGHT_2);
                     me->SetFacingTo(5.26f);
                     me->SetOrientation(5.26f);
                     me->SetHomePosition(*me);
                     for (ObjectGuid const& guid : summons)
                         if (Creature* c = pInstance->instance->GetCreature(guid))
{
                             c->SetFacingTo(5.26f);
                             c->SetOrientation(5.26f);
                             c->SetHomePosition(*c);
                         }
                     events.RescheduleEvent(10, 15000);
                     events.RescheduleEvent(4, 15000);
                     break;
                 case 4:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_TYRANNUS_GUID)))
                             c->AI()->DoAction(1);
                     break;
                 case 5:
                     me->SetFacingTo(TSCenterPos.GetOrientation());
                     Talk(me->GetEntry() == NPC_MARTIN_VICTUS_2 ? SAY_GENERAL_ALLIANCE_OUTRO_1 : SAY_GENERAL_HORDE_OUTRO_1);
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_LEADER_SECOND_GUID)))
                             c->AI()->DoAction(1);
                     break;
                 case 10:
                     if (summons.GetEntryCount(NPC_FALLEN_WARRIOR) < 3)
                         if (Creature* c = me->SummonCreature(NPC_FALLEN_WARRIOR, 1060.95f, 102.79f, 630.2f, 2.01f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
{
                             float offset = frand(0.0f, 10.0f);
                             c->GetMotionMaster()->MovePoint(0, 1047.0f + offset, 118.0f + offset, 628.2f);
                             c->SetHomePosition(*me);
                             for (ObjectGuid const& guid : summons)
                                 if (Creature* s = pInstance->instance->GetCreature(guid))
{
                                     if (s->GetEntry() == NPC_FALLEN_WARRIOR)
                                         continue;
                                     c->SetInCombatWith(s);
                                     s->SetInCombatWith(c);
                                     c->AddThreat(s, 0.0f);
                                     s->AddThreat(c, 0.0f);
                                 }
                         }
                     events.RescheduleEvent(10, 3000);
                     break;
             }
             if (!UpdateVictim())
                 return;
             DoMeleeAttackIfReady();
         }
References mpq::c, DATA_LEADER_SECOND_GUID, DATA_TYRANNUS_GUID, diff(), UnitAI::DoMeleeAttackIfReady(), EMOTE_STATE_READY1H, TSPosition::entry, G3D::frand(), Map::GetCreature(), Object::GetEntry(), SummonList::GetEntryCount(), InstanceScript::GetGuidData(), Position::GetOrientation(), i, InstanceScript::instance, CreatureAI::me, NPC_FALLEN_WARRIOR, NPC_MARTIN_VICTUS_2, pInstance, SAY_GENERAL_ALLIANCE_OUTRO_1, SAY_GENERAL_ALLIANCE_TRASH, SAY_GENERAL_HORDE_OUTRO_1, SAY_GENERAL_HORDE_TRASH, SAY_PREFIGHT_2, Unit::SetFacingTo(), Creature::SetHomePosition(), Position::SetOrientation(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TSCenterPos, TSData, TSHeight, TSSpawnPos, UNIT_NPC_EMOTESTATE, CreatureAI::UpdateVictim(), G3D::x, and G3D::y.
Member Data Documentation
events
EventMap npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::events
Definition at line 945 of file pit_of_saron.cpp.
i
uint8 npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::i
Definition at line 947 of file pit_of_saron.cpp.
Referenced by npc_pos_martin_or_gorkun_secondAI(), and UpdateAI().
pInstance
InstanceScript* npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::pInstance
Definition at line 944 of file pit_of_saron.cpp.
Referenced by DoAction(), npc_pos_martin_or_gorkun_secondAI(), and UpdateAI().
summons
SummonList npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::summons
Definition at line 946 of file pit_of_saron.cpp.
Referenced by DoAction(), JustSummoned(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp