Azerotcore-wotlk: buffer< T > Class Template Reference
buffer< T > Class Template Reference abstract
#include <core.h>
Public Types
using value_type = T
using const_reference = const T &
Public Member Functions
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () FMT_NOEXCEPT -> T *
auto end () FMT_NOEXCEPT -> T *
auto begin () const FMT_NOEXCEPT -> const T *
auto end () const FMT_NOEXCEPT -> const T *
auto size () const FMT_NOEXCEPT -> size_t
auto capacity () const FMT_NOEXCEPT -> size_t
auto data () FMT_NOEXCEPT -> T *
auto data () const FMT_NOEXCEPT -> const T *
void clear ()
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
template<typename I >
auto operator[] (I index) -> T &
template<typename I >
auto operator[] (I index) const -> const T &
template<typename U >
void append (const U *begin, const U *end)
Protected Member Functions
buffer (size_t sz) FMT_NOEXCEPT
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
buffer (buffer &&)=default
void set (T *buf_data, size_t buf_capacity) FMT_NOEXCEPT
virtual void grow (size_t capacity)=0
Private Attributes
T * ptr_
size_t size_
size_t capacity_
Detailed Description
template<typename T>
class buffer< T >
\rst A contiguous memory buffer with an optional growing ability. It is an internal class and shouldn't be used directly, only via ~fmtbasic_memory_buffer. \endrst
Definition at line 749 of file core.h.
Member Typedef Documentation
const_reference
template<typename T > using buffer< T >::const_reference = const T&
Definition at line 779 of file core.h.
value_type
template<typename T > using buffer< T >::value_type = T
Definition at line 778 of file core.h.
Constructor & Destructor Documentation
buffer() [1/4]
template<typename T > buffer< T >::buffer (size_t sz) inline protected
Definition at line 758 of file core.h.
 : size_(sz), capacity_(sz) {}
buffer() [2/4]
template<typename T > buffer< T >::buffer (T * p = nullptr, size_t sz = 0, size_t cap = 0) inline protected
Definition at line 760 of file core.h.
       : ptr_(p),
         size_(sz),
         capacity_(cap) {}
~buffer()
template<typename T > buffer< T >::~buffer () protected default
buffer() [3/4]
template<typename T > buffer< T >::buffer (buffer< T > &&) protected default
buffer() [4/4]
template<typename T > buffer< T >::buffer (const buffer< T > &) delete
Member Function Documentation
append() [1/2]
template<typename T > template<typename U > void buffer< T >::append (const U * begin, const U * end)
Appends data to the end of the buffer.
Referenced by reset_color(), vformat_to(), and detail::formatbuf< Char >::xsputn().
append() [2/2]
template<typename T > template<typename U > void buffer< T >::append (const U * begin, const U * end)
Definition at line 577 of file format.h.
{
   while (begin != end) {
     auto count = to_unsigned(end - begin);
     try_reserve(size_ + count);
     auto free_cap = capacity_ - size_;
     if (free_cap < count) count = free_cap;
     std::uninitialized_copy_n(begin, count, make_checked(ptr_ + size_, count));
     size_ += count;
     begin += count;
   }
 }
References count(), detail::make_checked(), and to_unsigned().
begin() [1/2]
template<typename T > auto buffer< T >::begin () const -> const T* inline
Definition at line 787 of file core.h.
 { return ptr_; }
References buffer< T >::ptr_.
begin() [2/2]
template<typename T > auto buffer< T >::begin () -> T* inline
Definition at line 784 of file core.h.
 { return ptr_; }
References buffer< T >::ptr_.
capacity()
template<typename T > auto buffer< T >::capacity () const -> size_t inline
Returns the capacity of this buffer.
Definition at line 794 of file core.h.
 { return capacity_; }
References buffer< T >::capacity_.
Referenced by iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::grow(), and detail::snprintf_float().
clear()
template<typename T > void buffer< T >::clear () inline
Clears this buffer.
Definition at line 803 of file core.h.
 { size_ = 0; }
References buffer< T >::size_.
Referenced by iterator_buffer< OutputIt, T, Traits >::flush().
data() [1/2]
template<typename T > auto buffer< T >::data () const -> const T* inline
Returns a pointer to the buffer data.
Definition at line 800 of file core.h.
 { return ptr_; }
References buffer< T >::ptr_.
data() [2/2]
template<typename T > auto buffer< T >::data () -> T* inline
Returns a pointer to the buffer data.
Definition at line 797 of file core.h.
 { return ptr_; }
References buffer< T >::ptr_.
Referenced by detail::fallback_format(), detail::format_float(), LoadM2Cameras(), detail::snprintf_float(), vformat(), vfprintf(), vprint(), detail::write_buffer(), and write_int_localized().
end() [1/2]
template<typename T > auto buffer< T >::end () const -> const T* inline
Definition at line 788 of file core.h.
 { return ptr_ + size_; }
References buffer< T >::ptr_, and buffer< T >::size_.
end() [2/2]
template<typename T > auto buffer< T >::end () -> T* inline
Definition at line 785 of file core.h.
 { return ptr_ + size_; }
References buffer< T >::ptr_, and buffer< T >::size_.
Referenced by iterator_buffer< T *, T >::out().
grow()
template<typename T > virtual void buffer< T >::grow (size_t capacity) protected pure virtual
Increases the buffer capacity to hold at least capacity elements.
Implemented in counting_buffer< T >, iterator_buffer< T *, T >, iterator_buffer< OutputIt, T, Traits >, and iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >.
Referenced by buffer< T >::try_reserve().
operator=()
template<typename T > void buffer< T >::operator= (const buffer< T > &) delete
operator[]() [1/2]
template<typename T > template<typename I > auto buffer< T >::operator[] (I index) -> T& inline
Definition at line 828 of file core.h.
 { return ptr_[index]; }
References index, and buffer< T >::ptr_.
operator[]() [2/2]
template<typename T > template<typename I > auto buffer< T >::operator[] (I index) const -> const T& inline
Definition at line 829 of file core.h.
{
     return ptr_[index];
   }
References index, and buffer< T >::ptr_.
push_back()
template<typename T > void buffer< T >::push_back (const T & value) inline
Definition at line 820 of file core.h.
{
     try_reserve(size_ + 1);
     ptr_[size_++] = value;
   }
References buffer< T >::ptr_, buffer< T >::size_, and buffer< T >::try_reserve().
Referenced by detail::format_float(), detail::formatbuf< Char >::overflow(), and vprint().
set()
template<typename T > void buffer< T >::set (T * buf_data, size_t buf_capacity) inline protected
Sets the buffer data and capacity.
Definition at line 769 of file core.h.
{
     ptr_ = buf_data;
     capacity_ = buf_capacity;
   }
References buffer< T >::capacity_, and buffer< T >::ptr_.
Referenced by iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::grow().
size()
template<typename T > auto buffer< T >::size () const -> size_t inline
Returns the size of this buffer.
Definition at line 791 of file core.h.
 { return size_; }
References buffer< T >::size_.
Referenced by iterator_buffer< OutputIt, T, Traits >::count(), iterator_buffer< OutputIt, T, Traits >::flush(), detail::format_float(), detail::format_value(), iterator_buffer< OutputIt, T, Traits >::grow(), G3D::TextInput::initFromString(), G3D::TextInput::readUntilDelimiterAsString(), detail::snprintf_float(), vformat(), vfprintf(), vprint(), and detail::write_buffer().
try_reserve()
template<typename T > void buffer< T >::try_reserve (size_t new_capacity) inline
Definition at line 816 of file core.h.
{
     if (new_capacity > capacity_) grow(new_capacity);
   }
References buffer< T >::capacity_, and buffer< T >::grow().
Referenced by buffer< T >::push_back(), detail::snprintf_float(), and buffer< T >::try_resize().
try_resize()
template<typename T > void buffer< T >::try_resize (size_t count) inline
Definition at line 807 of file core.h.
{
     try_reserve(count);
     size_ = count <= capacity_ ? count : capacity_;
   }
References buffer< T >::capacity_, count(), buffer< T >::size_, and buffer< T >::try_reserve().
Referenced by detail::fallback_format(), detail::format_float(), detail::format_value(), and detail::snprintf_float().
Member Data Documentation
capacity_
template<typename T > size_t buffer< T >::capacity_ private
Definition at line 753 of file core.h.
Referenced by buffer< T >::capacity(), buffer< T >::set(), buffer< T >::try_reserve(), and buffer< T >::try_resize().
ptr_
template<typename T > T* buffer< T >::ptr_ private
Definition at line 751 of file core.h.
Referenced by buffer< T >::begin(), buffer< T >::data(), buffer< T >::end(), buffer< T >::operator[](), buffer< T >::push_back(), and buffer< T >::set().
size_
template<typename T > size_t buffer< T >::size_ private
Definition at line 752 of file core.h.
Referenced by buffer< T >::clear(), buffer< T >::end(), buffer< T >::push_back(), buffer< T >::size(), and buffer< T >::try_resize().
The documentation for this class was generated from the following files:
deps/fmt/include/fmt/core.h
deps/fmt/include/fmt/format.h