Azerotcore-wotlk: SpellArea Struct Reference
SpellArea Struct Reference
#include <SpellMgr.h>
Public Member Functions
bool IsFitToRequirements (Player const *player, uint32 newZone, uint32 newArea) const
Public Attributes
uint32 spellId
uint32 areaId
uint32 questStart
uint32 questEnd
int32 auraSpell
uint32 raceMask
Gender gender
uint32 questStartStatus
uint32 questEndStatus
bool autocast
Detailed Description
Definition at line 510 of file SpellMgr.h.
Member Function Documentation
IsFitToRequirements()
bool SpellArea::IsFitToRequirements (Player const * player, uint32 newZone, uint32 newArea) const
Definition at line 1070 of file SpellMgr.cpp.
 {
     if (gender != GENDER_NONE)                   // not in expected gender
         if (!player || gender != player->getGender())
             return false;
     if (raceMask)                                // not in expected race
         if (!player || !(raceMask & player->getRaceMask()))
             return false;
     if (areaId)                                  // not in expected zone
         if (newZone != areaId && newArea != areaId)
             return false;
     if (questStart)                              // not in expected required quest state
         if (!player || (((1 << player->GetQuestStatus(questStart)) & questStartStatus) == 0))
             return false;
     if (questEnd)                                // not in expected forbidden quest state
         if (!player || (((1 << player->GetQuestStatus(questEnd)) & questEndStatus) == 0))
             return false;
     if (auraSpell)                               // not have expected aura
         if (!player || (auraSpell > 0 && !player->HasAura(auraSpell)) || (auraSpell < 0 && player->HasAura(-auraSpell)))
             return false;
     // Extra conditions -- leaving the possibility add extra conditions...
     switch (spellId)
     {
         case 58600: // No fly Zone - Dalaran
             {
                 if (!player)
                     return false;
                 AreaTableEntry const* pArea = sAreaTableStore.LookupEntry(player->GetAreaId());
                 if (!(pArea && pArea->flags & AREA_FLAG_NO_FLY_ZONE))
                     return false;
                 if (!player->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED) && !player->HasAuraType(SPELL_AURA_FLY))
                     return false;
                 // Xinef: Underbelly elixir
                 if (player->GetPositionZ() < 637.0f && player->HasAuraType(SPELL_AURA_TRANSFORM))
                     return false;
                 break;
             }
         case 58730: // No fly Zone - Wintergrasp
             {
                 if (!player)
                     return false;
                 Battlefield* Bf = sBattlefieldMgr->GetBattlefieldToZoneId(player->GetZoneId());
                 if (!Bf || Bf->CanFlyIn() || (!player->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED) && !player->HasAuraType(SPELL_AURA_FLY)))
                     return false;
                 break;
             }
         // xinef: northrend flying mounts
         // xinef: NE wisp and spectral gryphon
         case 55164:
         case 55173:
             {
                 Battlefield* Bf = sBattlefieldMgr->GetBattlefieldToZoneId(player->GetZoneId());
                 return !Bf || Bf->CanFlyIn();
             }
         case 57940: // Essence of Wintergrasp OUTSIDE
         case 58045: // Essence of Wintergrasp INSIDE
             {
                 if (!player)
                     return false;
                 if (!sWorld->getBoolConfig(CONFIG_WINTERGRASP_ENABLE))
                     return false;
                 Battlefield* Bf = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
                 if (!Bf || player->GetTeamId() != Bf->GetDefenderTeam() || Bf->IsWarTime())
                     return false;
                 break;
             }
         case 74411: // Battleground - Dampening
             {
                 if (!player)
                     return false;
                 if (Battlefield* bf = sBattlefieldMgr->GetBattlefieldToZoneId(player->GetZoneId()))
                     return bf->IsWarTime();
                 break;
             }
         case 68719: // Oil Refinery - Isle of Conquest.
         case 68720: // Quarry - Isle of Conquest.
             {
                 if (!player)
                     return false;
                 Battleground* bg = player->GetBattleground();
                 if (!bg || bg->GetBgTypeID(true) != BATTLEGROUND_IC)
                     return false;
                 uint8 nodeType = spellId == 68719 ? NODE_TYPE_REFINERY : NODE_TYPE_QUARRY;
                 uint8 nodeState = player->GetTeamId() == TEAM_ALLIANCE ? NODE_STATE_CONTROLLED_A : NODE_STATE_CONTROLLED_H;
                 return bg->ToBattlegroundIC()->GetNodeState(nodeType) == nodeState;
             }
         case 56618: // Horde Controls Factory Phase Shift
         case 56617: // Alliance Controls Factory Phase Shift
             {
                 if (!player)
                     return false;
                 Battlefield* bf = sBattlefieldMgr->GetBattlefieldToZoneId(player->GetZoneId());
                 if (!bf || bf->GetTypeId() != BATTLEFIELD_WG)
                     return false;
                 // team that controls the workshop in the specified area
                 uint32 team = bf->GetData(newArea);
                 if (team == TEAM_HORDE)
                     return spellId == 56618;
                 else if (team == TEAM_ALLIANCE)
                     return spellId == 56617;
                 break;
             }
         // Hellscream's Warsong
         case 73816:
         case 73818:
         case 73819:
         case 73820:
         case 73821:
         case 73822:
         // Strength of Wrynn
         case 73762:
         case 73824:
         case 73825:
         case 73826:
         case 73827:
         case 73828:
             if (player)
                 if (InstanceScript* s = const_cast<Player*>(player)->GetInstanceScript())
                     return s->GetData(251 /*DATA_BUFF_AVAILABLE*/) != 0;
             return false;
             break;
     }
     return true;
 }
References AREA_FLAG_NO_FLY_ZONE, areaId, auraSpell, BATTLEFIELD_BATTLEID_WG, BATTLEFIELD_WG, BATTLEGROUND_IC, bg(), Battlefield::CanFlyIn(), CONFIG_WINTERGRASP_ENABLE, AreaTableEntry::flags, gender, GENDER_NONE, WorldObject::GetAreaId(), Player::GetBattleground(), Battlefield::GetData(), Battlefield::GetDefenderTeam(), Unit::getGender(), Position::GetPositionZ(), Player::GetQuestStatus(), Unit::getRaceMask(), Player::GetTeamId(), Battlefield::GetTypeId(), WorldObject::GetZoneId(), Unit::HasAura(), Unit::HasAuraType(), Battlefield::IsWarTime(), NODE_STATE_CONTROLLED_A, NODE_STATE_CONTROLLED_H, NODE_TYPE_QUARRY, NODE_TYPE_REFINERY, questEnd, questEndStatus, questStart, questStartStatus, raceMask, sAreaTableStore, sBattlefieldMgr, SPELL_AURA_FLY, SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, SPELL_AURA_TRANSFORM, spellId, sWorld, TEAM_ALLIANCE, and TEAM_HORDE.
Member Data Documentation
areaId
uint32 SpellArea::areaId
Definition at line 513 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
auraSpell
int32 SpellArea::auraSpell
Definition at line 516 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
autocast
bool SpellArea::autocast
Definition at line 521 of file SpellMgr.h.
Referenced by SpellMgr::LoadSpellAreas().
gender
Gender SpellArea::gender
Definition at line 518 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
questEnd
uint32 SpellArea::questEnd
Definition at line 515 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
questEndStatus
uint32 SpellArea::questEndStatus
Definition at line 520 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
questStart
uint32 SpellArea::questStart
Definition at line 514 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
questStartStatus
uint32 SpellArea::questStartStatus
Definition at line 519 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
raceMask
uint32 SpellArea::raceMask
Definition at line 517 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
spellId
uint32 SpellArea::spellId
Definition at line 512 of file SpellMgr.h.
Referenced by IsFitToRequirements(), and SpellMgr::LoadSpellAreas().
The documentation for this struct was generated from the following files:
src/server/game/Spells/SpellMgr.h
src/server/game/Spells/SpellMgr.cpp