Azerotcore-wotlk: G3D::Welder Class Reference
G3D::Welder Class Reference
#include <Welder.h>
Classes
class Settings
Static Public Member Functions
static void weld (Array< Vector3 > &vertices, Array< Vector2 > &textureCoords, Array< Vector3 > &normals, Array< Array< int > * > &indices, const Settings &settings)
static void weld (Array< Vector3 > &vertices, Array< Vector2 > &textureCoords, Array< Vector3 > &normals, Array< int > &indices, const Settings &settings)
Private Member Functions
Welder ()
Detailed Description
Definition at line 13 of file Welder.h.
Constructor & Destructor Documentation
Welder()
G3D::Welder::Welder () inline private
Definition at line 16 of file Welder.h.
 {}
Member Function Documentation
weld() [1/2]
void G3D::Welder::weld (Array< Vector3 > & vertices, Array< Vector2 > & textureCoords, Array< Vector3 > & normals, Array< Array< int > * > & indices, const Settings & settings) static
Mutates geometry, texCoord, and indexArray so that the output has collocated vertices collapsed (welded).
Parameters
vertices Input and output
textureCoords Input and output
normals Output only
indices Input and output. This is an array of trilist indices.
Definition at line 484 of file Welder.cpp.
{
     _internal::WeldHelper(settings.vertexWeldRadius).process
         (vertexArray, texCoordArray, normalArray, indexArrayArray,
          settings.normalSmoothingAngle, settings.textureWeldRadius, settings.normalWeldRadius);
 }
References G3D::_internal::WeldHelper::process().
Referenced by weld().
weld() [2/2]
static void G3D::Welder::weld (Array< Vector3 > & vertices, Array< Vector2 > & textureCoords, Array< Vector3 > & normals, Array< int > & indices, const Settings & settings) inline static
Mutates geometry, texCoord, and indexArray so that the output has collocated vertices collapsed (welded).
Parameters
vertices Input and output
textureCoords Input and output
normals Output only
indices Input and output. This is an array of trilist indices.
Definition at line 73 of file Welder.h.
{
         Array<Array<int>*> meta;
         meta.append(&indices);
         weld(vertices, textureCoords, normals, meta, settings);
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), and weld().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Welder.h
deps/g3dlite/source/Welder.cpp