Azerotcore-wotlk: npc_aged_dying_ancient_kodo Class Reference
npc_aged_dying_ancient_kodo Class Reference
Classes
struct npc_aged_dying_ancient_kodoAI
Public Member Functions
npc_aged_dying_ancient_kodo ()
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 442 of file zone_desolace.cpp.
Constructor & Destructor Documentation
npc_aged_dying_ancient_kodo()
npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodo () inline
Definition at line 445 of file zone_desolace.cpp.
 : CreatureScript("npc_aged_dying_ancient_kodo") { }
Member Function Documentation
GetAI()
CreatureAI* npc_aged_dying_ancient_kodo::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 505 of file zone_desolace.cpp.
     {
         return new npc_aged_dying_ancient_kodoAI(creature);
     }
OnGossipHello()
bool npc_aged_dying_ancient_kodo::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 493 of file zone_desolace.cpp.
     {
         if (player->HasAura(SPELL_KODO_KOMBO_PLAYER_BUFF) && creature->HasAura(SPELL_KODO_KOMBO_DESPAWN_BUFF))
         {
             player->TalkedToCreature(creature->GetEntry(), ObjectGuid::Empty);
             player->RemoveAurasDueToSpell(SPELL_KODO_KOMBO_PLAYER_BUFF);
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References ObjectGuid::Empty, Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Unit::HasAura(), Unit::RemoveAurasDueToSpell(), SendGossipMenuFor(), SPELL_KODO_KOMBO_DESPAWN_BUFF, SPELL_KODO_KOMBO_PLAYER_BUFF, and Player::TalkedToCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_desolace.cpp