Azerotcore-wotlk: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp File Reference
TargetedMovementGenerator.cpp File Reference
#include "Creature.h"
#include "CreatureAI.h"
#include "MoveSplineInit.h"
#include "Pet.h"
#include "Player.h"
#include "Spell.h"
#include "TargetedMovementGenerator.h"
#include "Transport.h"
Functions
static bool IsMutualChase (Unit *owner, Unit *target)
static Optional< float > GetVelocity (Unit *owner, Unit *target, G3D::Vector3 const &dest, bool playerPet)
static Position const PredictPosition (Unit *target)
Function Documentation
GetVelocity()
static Optional<float> GetVelocity (Unit * owner, Unit * target, G3D::Vector3 const & dest, bool playerPet) static
Definition at line 251 of file TargetedMovementGenerator.cpp.
 {
     Optional<float> speed = {};
     if (!owner->IsInCombat() && !owner->IsVehicle() && !owner->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_POSSESSED) &&
         (owner->IsPet() || owner->IsGuardian() || owner->GetGUID() == target->GetCritterGUID() || owner->GetCharmerOrOwnerGUID() == target->GetGUID()))
     {
         UnitMoveType moveType = Movement::SelectSpeedType(target->GetUnitMovementFlags());
         speed = std::max(target->GetSpeed(moveType), owner->GetSpeed(moveType));
         if (playerPet)
         {
             float distance = owner->GetDistance2d(dest.x, dest.y) - (*speed / 2.f);
             if (distance > 0.f)
             {
                 float multiplier = 1.f + (distance / 10.f);
                 *speed *= multiplier;
             }
             else
             {
                 switch (moveType)
                 {
                     case MOVE_RUN_BACK:
                     case MOVE_SWIM_BACK:
                     case MOVE_FLIGHT_BACK:
                         break;
                     default:
                         *speed *= 0.9f;
                         break;
                 }
             }
         }
     }
     return speed;
 }
References G3D::distance(), Unit::GetCharmerOrOwnerGUID(), Unit::GetCritterGUID(), WorldObject::GetDistance2d(), Object::GetGUID(), Unit::GetSpeed(), Unit::GetUnitMovementFlags(), Object::HasFlag(), Unit::IsGuardian(), Unit::IsInCombat(), Unit::IsPet(), Unit::IsVehicle(), max, MOVE_FLIGHT_BACK, MOVE_RUN_BACK, MOVE_SWIM_BACK, Movement::SelectSpeedType(), UNIT_FIELD_FLAGS, UNIT_FLAG_POSSESSED, G3D::Vector3::x, and G3D::Vector3::y.
Referenced by FollowMovementGenerator< T >::DoUpdate().
IsMutualChase()
static bool IsMutualChase (Unit * owner, Unit * target) static
Definition at line 27 of file TargetedMovementGenerator.cpp.
 {
     if (target->GetMotionMaster()->GetCurrentMovementGeneratorType() != CHASE_MOTION_TYPE)
         return false;
     return target->GetVictim() == owner;
 }
References CHASE_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), and Unit::GetVictim().
Referenced by ChaseMovementGenerator< T >::DoUpdate().
PredictPosition()
static Position const PredictPosition (Unit * target) static
Definition at line 287 of file TargetedMovementGenerator.cpp.
 {
     Position pos = target->GetPosition();
      // 0.5 - it's time (0.5 sec) between starting movement opcode (e.g. MSG_MOVE_START_FORWARD) and MSG_MOVE_HEARTBEAT sent by client
     float speed = target->GetSpeed(Movement::SelectSpeedType(target->GetUnitMovementFlags())) * 0.5f;
     float orientation = target->GetOrientation();
     if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_FORWARD))
     {
         pos.m_positionX += cos(orientation) * speed;
         pos.m_positionY += sin(orientation) * speed;
     }
     else if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_BACKWARD))
     {
         pos.m_positionX -= cos(orientation) * speed;
         pos.m_positionY -= sin(orientation) * speed;
     }
     if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_STRAFE_LEFT))
     {
         pos.m_positionX += cos(orientation + M_PI / 2.f) * speed;
         pos.m_positionY += sin(orientation + M_PI / 2.f) * speed;
     }
     else if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_STRAFE_RIGHT))
     {
         pos.m_positionX += cos(orientation - M_PI / 2.f) * speed;
         pos.m_positionY += sin(orientation - M_PI / 2.f) * speed;
     }
     return pos;
 }
References Position::GetOrientation(), Position::GetPosition(), Unit::GetSpeed(), Unit::GetUnitMovementFlags(), MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, M_PI, MOVEMENTFLAG_BACKWARD, MOVEMENTFLAG_FORWARD, MOVEMENTFLAG_STRAFE_LEFT, MOVEMENTFLAG_STRAFE_RIGHT, pos(), and Movement::SelectSpeedType().
Referenced by FollowMovementGenerator< T >::DoUpdate().