Azerotcore-wotlk: TaskScheduler Class Reference
TaskScheduler Class Reference
#include <TaskScheduler.h>
Classes
struct Compare
Container which provides Task order, insert and reschedule operations.
class Task
class TaskQueue
Public Member Functions
TaskScheduler ()
template<typename P >
TaskScheduler (P &&predicate)
TaskScheduler (TaskScheduler const &)=delete
TaskScheduler (TaskScheduler &&)=delete
TaskScheduler & operator= (TaskScheduler const &)=delete
TaskScheduler & operator= (TaskScheduler &&)=delete
template<typename P >
TaskScheduler & SetValidator (P &&predicate)
Sets a validator which is asked if tasks are allowed to be executed.
TaskScheduler & ClearValidator ()
Clears the validator which is asked if tasks are allowed to be executed.
TaskScheduler & Update (success_t const &callback=EmptyCallback)
TaskScheduler & Update (size_t const milliseconds, success_t const &callback=EmptyCallback)
template<class _Rep , class _Period >
TaskScheduler & Update (std::chrono::duration< _Rep, _Period > const &difftime, success_t const &callback=EmptyCallback)
TaskScheduler & Async (std::function< void()> const &callable)
template<class _Rep , class _Period >
TaskScheduler & Schedule (std::chrono::duration< _Rep, _Period > const &time, task_handler_t const &task)
template<class _Rep , class _Period >
TaskScheduler & Schedule (std::chrono::duration< _Rep, _Period > const &time, group_t const group, task_handler_t const &task)
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & Schedule (std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max, task_handler_t const &task)
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & Schedule (std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max, group_t const group, task_handler_t const &task)
TaskScheduler & CancelAll ()
TaskScheduler & CancelGroup (group_t const group)
TaskScheduler & CancelGroupsOf (std::vector< group_t > const &groups)
template<class _Rep , class _Period >
TaskScheduler & DelayAll (std::chrono::duration< _Rep, _Period > const &duration)
Delays all tasks with the given duration.
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & DelayAll (std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max)
Delays all tasks with a random duration between min and max.
template<class _Rep , class _Period >
TaskScheduler & DelayGroup (group_t const group, std::chrono::duration< _Rep, _Period > const &duration)
Delays all tasks of a group with the given duration.
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & DelayGroup (group_t const group, std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max)
Delays all tasks of a group with a random duration between min and max.
template<class _Rep , class _Period >
TaskScheduler & RescheduleAll (std::chrono::duration< _Rep, _Period > const &duration)
Reschedule all tasks with a given duration.
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & RescheduleAll (std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max)
Reschedule all tasks with a random duration between min and max.
template<class _Rep , class _Period >
TaskScheduler & RescheduleGroup (group_t const group, std::chrono::duration< _Rep, _Period > const &duration)
Reschedule all tasks of a group with the given duration.
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
TaskScheduler & RescheduleGroup (group_t const group, std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max)
Reschedule all tasks of a group with a random duration between min and max.
Private Types
typedef std::chrono::steady_clock clock_t
typedef clock_t::time_point timepoint_t
typedef clock_t::duration duration_t
typedef uint32 group_t
typedef uint32 repeated_t
typedef std::function< void(TaskContext)> task_handler_t
typedef std::function< bool()> predicate_t
typedef std::function< void()> success_t
typedef std::shared_ptr< Task > TaskContainer
typedef std::queue< std::function< void()> > AsyncHolder
Private Member Functions
TaskScheduler & InsertTask (TaskContainer task)
Insert a new task to the enqueued tasks.
template<class _Rep , class _Period >
TaskScheduler & ScheduleAt (timepoint_t const &end, std::chrono::duration< _Rep, _Period > const &time, task_handler_t const &task)
template<class _Rep , class _Period >
TaskScheduler & ScheduleAt (timepoint_t const &end, std::chrono::duration< _Rep, _Period > const &time, group_t const group, task_handler_t const &task)
void Dispatch (success_t const &callback)
Dispatch remaining tasks.
Static Private Member Functions
static bool EmptyValidator ()
static void EmptyCallback ()
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight >
static std::chrono::milliseconds RandomDurationBetween (std::chrono::duration< _RepLeft, _PeriodLeft > const &min, std::chrono::duration< _RepRight, _PeriodRight > const &max)
Private Attributes
std::shared_ptr< TaskScheduler > self_reference
Contains a self reference to track if this object was deleted or not.
timepoint_t _now
The current time point (now)
TaskQueue _task_holder
The Task Queue which contains all task objects.
AsyncHolder _asyncHolder
predicate_t _predicate
Friends
class TaskContext
Detailed Description
The TaskScheduler class provides the ability to schedule std::function's in the near future. Use TaskScheduler::Update to update the scheduler. Popular methods are:
Schedule (Schedules a std::function which will be executed in the near future).
Schedules an asynchronous function which will be executed at the next update tick.
Cancel, Delay & Reschedule (Methods to manipulate already scheduled tasks). Tasks are organized in groups (uint), multiple tasks can have the same group id, you can provide a group or not, but keep in mind that you can only manipulate specific tasks through its group id! Tasks callbacks use the function signature void(TaskContext) where TaskContext provides access to the function schedule plan which makes it possible to repeat the task with the same duration or a new one. It also provides access to the repeat counter which is useful for task that repeat itself often but behave different every time (spoken event dialogs for example).
Definition at line 35 of file TaskScheduler.h.
Member Typedef Documentation
AsyncHolder
typedef std::queue<std::function<void()> > TaskScheduler::AsyncHolder private
Definition at line 151 of file TaskScheduler.h.
clock_t
typedef std::chrono::steady_clock TaskScheduler::clock_t private
Definition at line 40 of file TaskScheduler.h.
duration_t
typedef clock_t::duration TaskScheduler::duration_t private
Definition at line 42 of file TaskScheduler.h.
group_t
typedef uint32 TaskScheduler::group_t private
Definition at line 45 of file TaskScheduler.h.
predicate_t
typedef std::function<bool()> TaskScheduler::predicate_t private
Definition at line 51 of file TaskScheduler.h.
repeated_t
typedef uint32 TaskScheduler::repeated_t private
Definition at line 47 of file TaskScheduler.h.
success_t
typedef std::function<void()> TaskScheduler::success_t private
Definition at line 53 of file TaskScheduler.h.
task_handler_t
typedef std::function<void(TaskContext)> TaskScheduler::task_handler_t private
Definition at line 49 of file TaskScheduler.h.
TaskContainer
typedef std::shared_ptr<Task> TaskScheduler::TaskContainer private
Definition at line 109 of file TaskScheduler.h.
timepoint_t
typedef clock_t::time_point TaskScheduler::timepoint_t private
Definition at line 41 of file TaskScheduler.h.
Constructor & Destructor Documentation
TaskScheduler() [1/4]
TaskScheduler::TaskScheduler () inline
Definition at line 169 of file TaskScheduler.h.
         : self_reference(this, [](TaskScheduler const*) { }), _now(clock_t::now()), _predicate(EmptyValidator) { }
TaskScheduler() [2/4]
template<typename P > TaskScheduler::TaskScheduler (P && predicate) inline
Definition at line 172 of file TaskScheduler.h.
         : self_reference(this, [](TaskScheduler const*) { }), _now(clock_t::now()), _predicate(std::forward<P>(predicate)) { }
TaskScheduler() [3/4]
TaskScheduler::TaskScheduler (TaskScheduler const &) delete
TaskScheduler() [4/4]
TaskScheduler::TaskScheduler (TaskScheduler &&) delete
Member Function Documentation
Async()
TaskScheduler & TaskScheduler::Async (std::function< void()> const & callable)
Schedule an callable function that is executed at the next update tick. Its safe to modify the TaskScheduler from within the callable.
Definition at line 27 of file TaskScheduler.cpp.
 {
     _asyncHolder.push(callable);
     return *this;
 }
References _asyncHolder.
Referenced by TaskContext::Async().
CancelAll()
TaskScheduler & TaskScheduler::CancelAll ()
Cancels all tasks. Never call this from within a task context! Use TaskContext::CancelAll instead!
Clear the task holder
Definition at line 33 of file TaskScheduler.cpp.
 {
     _task_holder.Clear();
     _asyncHolder = AsyncHolder();
     return *this;
 }
References _asyncHolder, _task_holder, and TaskScheduler::TaskQueue::Clear().
Referenced by TaskContext::CancelAll(), and boss_baroness_anastari::boss_baroness_anastariAI::Reset().
CancelGroup()
TaskScheduler & TaskScheduler::CancelGroup (group_t const group)
Cancel all tasks of a single group. Never call this from within a task context! Use TaskContext::CancelGroup instead!
Definition at line 41 of file TaskScheduler.cpp.
 {
     _task_holder.RemoveIf([group](TaskContainer const & task) -> bool
     {
         return task->IsInGroup(group);
     });
     return *this;
 }
References _task_holder, and TaskScheduler::TaskQueue::RemoveIf().
Referenced by TaskContext::CancelGroup(), and CancelGroupsOf().
CancelGroupsOf()
TaskScheduler & TaskScheduler::CancelGroupsOf (std::vector< group_t > const & groups)
Cancels all groups in the given std::vector. Hint: Use std::initializer_list for this: "{1, 2, 3, 4}"
Definition at line 50 of file TaskScheduler.cpp.
 {
     std::for_each(groups.begin(), groups.end(),
                   std::bind(&TaskScheduler::CancelGroup, this, std::placeholders::_1));
     return *this;
 }
References CancelGroup().
Referenced by TaskContext::CancelGroupsOf().
ClearValidator()
TaskScheduler & TaskScheduler::ClearValidator ()
Clears the validator which is asked if tasks are allowed to be executed.
Definition at line 9 of file TaskScheduler.cpp.
 {
     _predicate = EmptyValidator;
     return *this;
 }
References _predicate, and EmptyValidator().
DelayAll() [1/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::DelayAll (std::chrono::duration< _Rep, _Period > const & duration) inline
Delays all tasks with the given duration.
Definition at line 265 of file TaskScheduler.h.
     {
         _task_holder.ModifyIf([&duration](TaskContainer const & task) -> bool
         {
             task->_end += duration;
             return true;
         });
         return *this;
     }
References _task_holder, and TaskScheduler::TaskQueue::ModifyIf().
Referenced by DelayAll().
DelayAll() [2/2]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::DelayAll (std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max) inline
Delays all tasks with a random duration between min and max.
Definition at line 277 of file TaskScheduler.h.
     {
         return DelayAll(RandomDurationBetween(min, max));
     }
References DelayAll(), and RandomDurationBetween().
DelayGroup() [1/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::DelayGroup (group_t const group, std::chrono::duration< _Rep, _Period > const & duration) inline
Delays all tasks of a group with the given duration.
Definition at line 285 of file TaskScheduler.h.
     {
         _task_holder.ModifyIf([&duration, group](TaskContainer const & task) -> bool
         {
             if (task->IsInGroup(group))
             {
                 task->_end += duration;
                 return true;
             }
             else
             {
                 return false;
             }
         });
         return *this;
     }
References _task_holder, and TaskScheduler::TaskQueue::ModifyIf().
Referenced by DelayGroup().
DelayGroup() [2/2]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::DelayGroup (group_t const group, std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max) inline
Delays all tasks of a group with a random duration between min and max.
Definition at line 304 of file TaskScheduler.h.
     {
         return DelayGroup(group, RandomDurationBetween(min, max));
     }
References DelayGroup(), and RandomDurationBetween().
Dispatch()
void TaskScheduler::Dispatch (success_t const & callback) private
Dispatch remaining tasks.
Definition at line 64 of file TaskScheduler.cpp.
 {
     // If the validation failed abort the dispatching here.
     if (!_predicate())
     {
         return;
     }
     // Process all asyncs
     while (!_asyncHolder.empty())
     {
         _asyncHolder.front()();
         _asyncHolder.pop();
         // If the validation failed abort the dispatching here.
         if (!_predicate())
         {
             return;
         }
     }
     while (!_task_holder.IsEmpty())
     {
         if (_task_holder.First()->_end > _now)
         {
             break;
         }
         // Perfect forward the context to the handler
         // Use weak references to catch destruction before callbacks.
         TaskContext context(_task_holder.Pop(), std::weak_ptr<TaskScheduler>(self_reference));
         // Invoke the context
         context.Invoke();
         // If the validation failed abort the dispatching here.
         if (!_predicate())
         {
             return;
         }
     }
     // On finish call the final callback
     callback();
 }
References _asyncHolder, _now, _predicate, _task_holder, TaskScheduler::TaskQueue::First(), TaskContext::Invoke(), TaskScheduler::TaskQueue::IsEmpty(), TaskScheduler::TaskQueue::Pop(), and self_reference.
Referenced by TaskContext::Async(), TaskContext::CancelAll(), TaskContext::CancelGroup(), TaskContext::CancelGroupsOf(), and Update().
EmptyCallback()
static void TaskScheduler::EmptyCallback () inline static private
Definition at line 164 of file TaskScheduler.h.
     {
     }
EmptyValidator()
static bool TaskScheduler::EmptyValidator () inline static private
Definition at line 159 of file TaskScheduler.h.
     {
         return true;
     }
Referenced by ClearValidator().
InsertTask()
TaskScheduler & TaskScheduler::InsertTask (TaskContainer task) private
Insert a new task to the enqueued tasks.
Definition at line 58 of file TaskScheduler.cpp.
 {
     _task_holder.Push(std::move(task));
     return *this;
 }
References _task_holder, and TaskScheduler::TaskQueue::Push().
Referenced by TaskContext::Repeat(), and ScheduleAt().
operator=() [1/2]
TaskScheduler& TaskScheduler::operator= (TaskScheduler &&) delete
operator=() [2/2]
TaskScheduler& TaskScheduler::operator= (TaskScheduler const &) delete
RandomDurationBetween()
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > static std::chrono::milliseconds TaskScheduler::RandomDurationBetween (std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max) inline static private
Definition at line 385 of file TaskScheduler.h.
     {
         auto const milli_min = std::chrono::duration_cast<std::chrono::milliseconds>(min);
         auto const milli_max = std::chrono::duration_cast<std::chrono::milliseconds>(max);
         // TC specific: use SFMT URandom
         return std::chrono::milliseconds(urand(uint32(milli_min.count()), uint32(milli_max.count())));
     }
References urand().
Referenced by DelayAll(), TaskContext::DelayAll(), DelayGroup(), TaskContext::DelayGroup(), TaskContext::Repeat(), RescheduleAll(), TaskContext::RescheduleAll(), RescheduleGroup(), TaskContext::RescheduleGroup(), Schedule(), and TaskContext::Schedule().
RescheduleAll() [1/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::RescheduleAll (std::chrono::duration< _Rep, _Period > const & duration) inline
Reschedule all tasks with a given duration.
Definition at line 313 of file TaskScheduler.h.
     {
         auto const end = _now + duration;
         _task_holder.ModifyIf([end](TaskContainer const & task) -> bool
         {
             task->_end = end;
             return true;
         });
         return *this;
     }
References _now, _task_holder, and TaskScheduler::TaskQueue::ModifyIf().
Referenced by TaskContext::RescheduleAll(), and RescheduleAll().
RescheduleAll() [2/2]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::RescheduleAll (std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max) inline
Reschedule all tasks with a random duration between min and max.
Definition at line 326 of file TaskScheduler.h.
     {
         return RescheduleAll(RandomDurationBetween(min, max));
     }
References RandomDurationBetween(), and RescheduleAll().
RescheduleGroup() [1/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::RescheduleGroup (group_t const group, std::chrono::duration< _Rep, _Period > const & duration) inline
Reschedule all tasks of a group with the given duration.
Definition at line 334 of file TaskScheduler.h.
     {
         auto const end = _now + duration;
         _task_holder.ModifyIf([end, group](TaskContainer const & task) -> bool
         {
             if (task->IsInGroup(group))
             {
                 task->_end = end;
                 return true;
             }
             else
             {
                 return false;
             }
         });
         return *this;
     }
References _now, _task_holder, and TaskScheduler::TaskQueue::ModifyIf().
Referenced by RescheduleGroup().
RescheduleGroup() [2/2]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::RescheduleGroup (group_t const group, std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max) inline
Reschedule all tasks of a group with a random duration between min and max.
Definition at line 354 of file TaskScheduler.h.
     {
         return RescheduleGroup(group, RandomDurationBetween(min, max));
     }
References RandomDurationBetween(), and RescheduleGroup().
Schedule() [1/4]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::Schedule (std::chrono::duration< _Rep, _Period > const & time, group_t const group, task_handler_t const & task) inline
Schedule an event with a fixed rate. Never call this from within a task context! Use TaskContext::Schedule instead!
Definition at line 226 of file TaskScheduler.h.
     {
         return ScheduleAt(_now, time, group, task);
     }
References _now, and ScheduleAt().
Schedule() [2/4]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::Schedule (std::chrono::duration< _Rep, _Period > const & time, task_handler_t const & task) inline
Schedule an event with a fixed rate. Never call this from within a task context! Use TaskContext::Schedule instead!
Definition at line 217 of file TaskScheduler.h.
     {
         return ScheduleAt(_now, time, task);
     }
References _now, and ScheduleAt().
Referenced by boss_baroness_anastari::boss_baroness_anastariAI::EnterCombat(), npc_hallows_end_soh::npc_hallows_end_sohAI::EnterCombat(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset(), Schedule(), and boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession().
Schedule() [3/4]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::Schedule (std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max, group_t const group, task_handler_t const & task) inline
Schedule an event with a fixed rate. Never call this from within a task context! Use TaskContext::Schedule instead!
Definition at line 244 of file TaskScheduler.h.
     {
         return Schedule(RandomDurationBetween(min, max), group, task);
     }
References RandomDurationBetween(), and Schedule().
Schedule() [4/4]
template<class _RepLeft , class _PeriodLeft , class _RepRight , class _PeriodRight > TaskScheduler& TaskScheduler::Schedule (std::chrono::duration< _RepLeft, _PeriodLeft > const & min, std::chrono::duration< _RepRight, _PeriodRight > const & max, task_handler_t const & task) inline
Schedule an event with a randomized rate between min and max rate. Never call this from within a task context! Use TaskContext::Schedule instead!
Definition at line 235 of file TaskScheduler.h.
     {
         return Schedule(RandomDurationBetween(min, max), task);
     }
References RandomDurationBetween(), and Schedule().
ScheduleAt() [1/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::ScheduleAt (timepoint_t const & end, std::chrono::duration< _Rep, _Period > const & time, group_t const group, task_handler_t const & task) inline private
Schedule an event with a fixed rate. Never call this from within a task context! Use TaskContext::schedule instead!
Definition at line 375 of file TaskScheduler.h.
     {
         static repeated_t const DEFAULT_REPEATED = 0;
         return InsertTask(TaskContainer(new Task(end + time, time, group, DEFAULT_REPEATED, task)));
     }
References InsertTask().
ScheduleAt() [2/2]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::ScheduleAt (timepoint_t const & end, std::chrono::duration< _Rep, _Period > const & time, task_handler_t const & task) inline private
Definition at line 366 of file TaskScheduler.h.
     {
         return InsertTask(TaskContainer(new Task(end + time, time, task)));
     }
References InsertTask().
Referenced by Schedule(), and TaskContext::Schedule().
SetValidator()
template<typename P > TaskScheduler& TaskScheduler::SetValidator (P && predicate) inline
Sets a validator which is asked if tasks are allowed to be executed.
Definition at line 182 of file TaskScheduler.h.
     {
         _predicate = std::forward<P>(predicate);
         return *this;
     }
References _predicate.
Referenced by npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::EnterCombat(), and boss_baroness_anastari::boss_baroness_anastariAI::Reset().
Update() [1/3]
TaskScheduler & TaskScheduler::Update (size_t const milliseconds, success_t const & callback = EmptyCallback)
Update the scheduler with a difftime in ms. Calls the optional callback on successfully finish.
Definition at line 22 of file TaskScheduler.cpp.
 {
     return Update(std::chrono::milliseconds(milliseconds), callback);
 }
References Update().
Update() [2/3]
template<class _Rep , class _Period > TaskScheduler& TaskScheduler::Update (std::chrono::duration< _Rep, _Period > const & difftime, success_t const & callback = EmptyCallback) inline
Update the scheduler with a difftime. Calls the optional callback on successfully finish.
Definition at line 202 of file TaskScheduler.h.
     {
         _now += difftime;
         Dispatch(callback);
         return *this;
     }
References _now, and Dispatch().
Update() [3/3]
TaskScheduler & TaskScheduler::Update (success_t const & callback = EmptyCallback)
Update the scheduler to the current time. Calls the optional callback on successfully finish.
Definition at line 15 of file TaskScheduler.cpp.
 {
     _now = clock_t::now();
     Dispatch(callback);
     return *this;
 }
References _now, and Dispatch().
Referenced by Update(), boss_baroness_anastari::boss_baroness_anastariAI::UpdateAI(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::UpdateAI(), go_direbrew_mole_machine::go_direbrew_mole_machineAI::UpdateAI(), and npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI().
Friends And Related Function Documentation
TaskContext
friend class TaskContext friend
Definition at line 37 of file TaskScheduler.h.
Member Data Documentation
_asyncHolder
AsyncHolder TaskScheduler::_asyncHolder private
Contains all asynchronous tasks which will be invoked at the next update tick.
Definition at line 155 of file TaskScheduler.h.
Referenced by Async(), CancelAll(), and Dispatch().
_now
timepoint_t TaskScheduler::_now private
The current time point (now)
Definition at line 146 of file TaskScheduler.h.
Referenced by Dispatch(), RescheduleAll(), RescheduleGroup(), Schedule(), and Update().
_predicate
predicate_t TaskScheduler::_predicate private
Definition at line 157 of file TaskScheduler.h.
Referenced by ClearValidator(), Dispatch(), and SetValidator().
_task_holder
TaskQueue TaskScheduler::_task_holder private
The Task Queue which contains all task objects.
Definition at line 149 of file TaskScheduler.h.
Referenced by CancelAll(), CancelGroup(), DelayAll(), DelayGroup(), Dispatch(), InsertTask(), RescheduleAll(), and RescheduleGroup().
self_reference
std::shared_ptr<TaskScheduler> TaskScheduler::self_reference private
Contains a self reference to track if this object was deleted or not.
Definition at line 143 of file TaskScheduler.h.
Referenced by Dispatch().
The documentation for this class was generated from the following files:
src/common/Utilities/TaskScheduler.h
src/common/Utilities/TaskScheduler.cpp