Azerotcore-wotlk: ThreatCalcHelper Struct Reference
ThreatCalcHelper Struct Reference
#include <ThreatMgr.h>
Static Public Member Functions
static float calcThreat (Unit *hatedUnit, Unit *hatingUnit, float threat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
static bool isValidProcess (Unit *hatedUnit, Unit *hatingUnit, SpellInfo const *threatSpell=nullptr)
Detailed Description
Definition at line 39 of file ThreatMgr.h.
Member Function Documentation
calcThreat()
float ThreatCalcHelper::calcThreat (Unit * hatedUnit, Unit * hatingUnit, float threat, SpellSchoolMask schoolMask = SPELL_SCHOOL_MASK_NORMAL, SpellInfo const * threatSpell = nullptr) static
Definition at line 35 of file ThreatMgr.cpp.
 {
     if (threatSpell)
     {
         if (SpellThreatEntry const*  threatEntry = sSpellMgr->GetSpellThreatEntry(threatSpell->Id))
             if (threatEntry->pctMod != 1.0f)
                 threat *= threatEntry->pctMod;
         // Energize is not affected by Mods
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; i++)
             if (threatSpell->Effects[i].Effect == SPELL_EFFECT_ENERGIZE || threatSpell->Effects[i].ApplyAuraName == SPELL_AURA_PERIODIC_ENERGIZE)
                 return threat;
         if (Player* modOwner = hatedUnit->GetSpellModOwner())
             modOwner->ApplySpellMod(threatSpell->Id, SPELLMOD_THREAT, threat);
     }
     return hatedUnit->ApplyTotalThreatModifier(threat, schoolMask);
 }
References Unit::ApplyTotalThreatModifier(), SpellInfo::Effects, Unit::GetSpellModOwner(), SpellInfo::Id, MAX_SPELL_EFFECTS, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_EFFECT_ENERGIZE, SPELLMOD_THREAT, and sSpellMgr.
Referenced by ThreatMgr::addThreat(), and HostileRefMgr::threatAssist().
isValidProcess()
bool ThreatCalcHelper::isValidProcess (Unit * hatedUnit, Unit * hatingUnit, SpellInfo const * threatSpell = nullptr) static
Definition at line 55 of file ThreatMgr.cpp.
 {
     //function deals with adding threat and adding players and pets into ThreatList
     //mobs, NPCs, guards have ThreatList and HateOfflineList
     //players and pets have only InHateListOf
     //HateOfflineList is used co contain unattackable victims (in-flight, in-water, GM etc.)
     if (!hatedUnit || !hatingUnit)
         return false;
     // not to self
     if (hatedUnit == hatingUnit)
         return false;
     // not to GM
     if (hatedUnit->GetTypeId() == TYPEID_PLAYER && hatedUnit->ToPlayer()->IsGameMaster())
         return false;
     // not to dead and not for dead
     if (!hatedUnit->IsAlive() || !hatingUnit->IsAlive())
         return false;
     // not in same map or phase
     if (!hatedUnit->IsInMap(hatingUnit) || !hatedUnit->InSamePhase(hatingUnit))
         return false;
     // spell not causing threat
     if (threatSpell && threatSpell->HasAttribute(SPELL_ATTR1_NO_THREAT))
         return false;
     ASSERT(hatingUnit->GetTypeId() == TYPEID_UNIT);
     return true;
 }
References ASSERT, Object::GetTypeId(), SpellInfo::HasAttribute(), WorldObject::InSamePhase(), Unit::IsAlive(), Player::IsGameMaster(), WorldObject::IsInMap(), SPELL_ATTR1_NO_THREAT, Object::ToPlayer(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by ThreatMgr::addThreat(), ThreatMgr::doAddThreat(), and HostileRefMgr::threatAssist().
The documentation for this struct was generated from the following files:
src/server/game/Combat/ThreatMgr.h
src/server/game/Combat/ThreatMgr.cpp