Azerotcore-wotlk: boss_alar::boss_alarAI Struct Reference
boss_alar::boss_alarAI Struct Reference
Public Member Functions
boss_alarAI (Creature *creature)
void JustReachedHome () override
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
void JustSummoned (Creature *summon) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 platform
uint8 noQuillTimes
bool startPath
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 92 of file boss_alar.cpp.
Constructor & Destructor Documentation
boss_alarAI()
boss_alar::boss_alarAI::boss_alarAI (Creature * creature) inline
Definition at line 94 of file boss_alar.cpp.
                                         : BossAI(creature, DATA_ALAR)
         {
             startPath = true;
             SetCombatMovement(false);
         }
References ScriptedAI::SetCombatMovement(), and startPath.
Member Function Documentation
DamageTaken()
void boss_alar::boss_alarAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 151 of file boss_alar.cpp.
         {
             if (damage >= me->GetHealth() && platform < POINT_MIDDLE)
             {
                 damage = 0;
                 if (events.GetNextEventTime(EVENT_REBIRTH) == 0)
                 {
                     me->InterruptNonMeleeSpells(false);
                     me->SetHealth(me->GetMaxHealth());
                     me->SetReactState(REACT_PASSIVE);
                     me->CastSpell(me, SPELL_EMBER_BLAST, true);
                     me->setAttackTimer(BASE_ATTACK, 16000);
                     events.Reset();
                     events.ScheduleEvent(EVENT_RELOCATE_MIDDLE, 8000);
                     events.ScheduleEvent(EVENT_MOVE_TO_PHASE_2, 12000);
                     events.ScheduleEvent(EVENT_REBIRTH, 16001);
                 }
             }
         }
References BASE_ATTACK, Unit::CastSpell(), EVENT_MOVE_TO_PHASE_2, EVENT_REBIRTH, EVENT_RELOCATE_MIDDLE, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, platform, POINT_MIDDLE, REACT_PASSIVE, Unit::setAttackTimer(), Unit::SetHealth(), Creature::SetReactState(), and SPELL_EMBER_BLAST.
EnterCombat()
void boss_alar::boss_alarAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 120 of file boss_alar.cpp.
         {
             BossAI::EnterCombat(who);
             events.ScheduleEvent(EVENT_SWITCH_PLATFORM, 0);
         }
References BossAI::EnterCombat(), and EVENT_SWITCH_PLATFORM.
JustDied()
void boss_alar::boss_alarAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 126 of file boss_alar.cpp.
         {
             me->SetModelVisible(true);
             BossAI::JustDied(killer);
             // Xinef: Ruse of the Ashtongue (10946)
             Map::PlayerList const& pl = me->GetMap()->GetPlayers();
             for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
             {
                 Player* player = itr->GetSource();
                 if (player->GetQuestStatus(QUEST_RUSE_OF_THE_ASHTONGUE) == QUEST_STATUS_INCOMPLETE)
                     if (player->HasAura(SPELL_ASHTONGUE_RUSE))
                         player->AreaExploredOrEventHappens(QUEST_RUSE_OF_THE_ASHTONGUE);
             }
         }
References Player::AreaExploredOrEventHappens(), MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), Player::GetQuestStatus(), Unit::HasAura(), BossAI::JustDied(), ScriptedAI::me, QUEST_RUSE_OF_THE_ASHTONGUE, QUEST_STATUS_INCOMPLETE, Unit::SetModelVisible(), and SPELL_ASHTONGUE_RUSE.
JustReachedHome()
void boss_alar::boss_alarAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 104 of file boss_alar.cpp.
         {
             BossAI::JustReachedHome();
             startPath = true;
         }
References BossAI::JustReachedHome(), and startPath.
JustSummoned()
void boss_alar::boss_alarAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 142 of file boss_alar.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_EMBER_OF_ALAR)
                 summon->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_FIRE, true);
         }
References Unit::ApplySpellImmune(), Object::GetEntry(), IMMUNITY_DAMAGE, NPC_EMBER_OF_ALAR, SPELL_SCHOOL_MASK_FIRE, SummonList::Summon(), and BossAI::summons.
MoveInLineOfSight()
void boss_alar::boss_alarAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 149 of file boss_alar.cpp.
 { }
MovementInform()
void boss_alar::boss_alarAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 172 of file boss_alar.cpp.
         {
             if (type != POINT_MOTION_TYPE)
             {
                 if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized() && !me->IsInCombat())
                     startPath = true;
                 return;
             }
             if (id == POINT_PLATFORM)
                 me->setAttackTimer(BASE_ATTACK, 1000);
             else if (id == POINT_QUILL)
                 events.ScheduleEvent(EVENT_START_QUILLS, 1000);
             else if (id == POINT_DIVE)
             {
                 events.ScheduleEvent(EVENT_START_DIVE, 1000);
                 events.ScheduleEvent(EVENT_CAST_DIVE_BOMB, 5000);
             }
         }
References BASE_ATTACK, ESCORT_MOTION_TYPE, EVENT_CAST_DIVE_BOMB, EVENT_START_DIVE, EVENT_START_QUILLS, Movement::MoveSpline::Finalized(), Unit::IsInCombat(), ScriptedAI::me, Unit::movespline, POINT_DIVE, POINT_MOTION_TYPE, POINT_PLATFORM, POINT_QUILL, Unit::setAttackTimer(), and startPath.
Reset()
void boss_alar::boss_alarAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 110 of file boss_alar.cpp.
         {
             BossAI::Reset();
             platform = 0;
             noQuillTimes = 0;
             me->SetModelVisible(true);
             me->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_FIRE, true);
             me->SetReactState(REACT_AGGRESSIVE);
         }
References Unit::ApplySpellImmune(), IMMUNITY_DAMAGE, ScriptedAI::me, noQuillTimes, platform, REACT_AGGRESSIVE, BossAI::Reset(), Unit::SetModelVisible(), Creature::SetReactState(), and SPELL_SCHOOL_MASK_FIRE.
UpdateAI()
void boss_alar::boss_alarAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 192 of file boss_alar.cpp.
         {
             if (startPath)
             {
                 me->StopMoving();
                 startPath = false;
                 if (WaypointPath const* i_path = sWaypointMgr->GetPath(me->GetWaypointPath()))
                 {
                     Movement::PointsArray pathPoints;
                     pathPoints.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                     for (uint8 i = 0; i < i_path->size(); ++i)
                     {
                         WaypointData const* node = i_path->at(i);
                         pathPoints.push_back(G3D::Vector3(node->x, node->y, node->z));
                     }
                     me->GetMotionMaster()->MoveSplinePath(&pathPoints);
                 }
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SWITCH_PLATFORM:
                     if (roll_chance_i(20 * noQuillTimes))
                     {
                         noQuillTimes = 0;
                         platform = RAND(0, 3);
                         me->GetMotionMaster()->MovePoint(POINT_QUILL, alarPoints[POINT_QUILL], false, true);
                         events.ScheduleEvent(EVENT_SWITCH_PLATFORM, 16000);
                     }
                     else
                     {
                         if (noQuillTimes++ > 0)
{
                             me->SetOrientation(alarPoints[platform].GetOrientation());
                             me->SummonCreature(NPC_EMBER_OF_ALAR, *me, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000);
                         }
                         me->GetMotionMaster()->MovePoint(POINT_PLATFORM, alarPoints[platform], false, true);
                         platform = (platform + 1) % 4;
                         events.ScheduleEvent(EVENT_SWITCH_PLATFORM, 30000);
                     }
                     me->setAttackTimer(BASE_ATTACK, 20000);
                     break;
                 case EVENT_START_QUILLS:
                     me->CastSpell(me, SPELL_FLAME_QUILLS, false);
                     break;
                 case EVENT_RELOCATE_MIDDLE:
                     me->SetPosition(alarPoints[POINT_MIDDLE]);
                     break;
                 case EVENT_MOVE_TO_PHASE_2:
                     me->RemoveAurasDueToSpell(SPELL_EMBER_BLAST);
                     me->CastSpell(me, SPELL_REBIRTH_PHASE2, false);
                     break;
                 case EVENT_REBIRTH:
                     me->SetReactState(REACT_AGGRESSIVE);
                     platform = POINT_MIDDLE;
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     events.ScheduleEvent(EVENT_SPELL_MELT_ARMOR, 67000);
                     events.ScheduleEvent(EVENT_SPELL_CHARGE, 10000);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_PATCH, 20000);
                     events.ScheduleEvent(EVENT_SPELL_DIVE_BOMB, 30000);
                     break;
                 case EVENT_SPELL_MELT_ARMOR:
                     me->CastSpell(me->GetVictim(), SPELL_MELT_ARMOR, false);
                     events.ScheduleEvent(EVENT_SPELL_MELT_ARMOR, 60000);
                     break;
                 case EVENT_SPELL_CHARGE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true))
                         me->CastSpell(target, SPELL_CHARGE, false);
                     events.ScheduleEvent(EVENT_SPELL_CHARGE, 30000);
                     break;
                 case EVENT_SPELL_FLAME_PATCH:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true))
                         me->SummonCreature(NPC_FLAME_PATCH, *target, TEMPSUMMON_TIMED_DESPAWN, 2 * MINUTE * IN_MILLISECONDS);
                     events.ScheduleEvent(EVENT_SPELL_FLAME_PATCH, 30000);
                     break;
                 case EVENT_SPELL_DIVE_BOMB:
                     me->GetMotionMaster()->MovePoint(POINT_DIVE, alarPoints[POINT_DIVE], false, true);
                     events.ScheduleEvent(EVENT_SPELL_DIVE_BOMB, 30000);
                     events.DelayEvents(15000);
                     me->setAttackTimer(BASE_ATTACK, 20000);
                     break;
                 case EVENT_START_DIVE:
                     me->CastSpell(me, SPELL_DIVE_BOMB_VISUAL, false);
                     break;
                 case EVENT_CAST_DIVE_BOMB:
                     events.ScheduleEvent(EVENT_SUMMON_DIVE_PHOENIX, 2000);
                     events.ScheduleEvent(EVENT_REBIRTH_DIVE, 6000);
                     events.ScheduleEvent(EVENT_FINISH_DIVE, 10000);
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 90.0f, true))
                     {
                         me->CastSpell(target, SPELL_DIVE_BOMB, false);
                         me->SetPosition(*target);
                         me->StopMovingOnCurrentPos();
                     }
                     me->RemoveAurasDueToSpell(SPELL_DIVE_BOMB_VISUAL);
                     break;
                 case EVENT_SUMMON_DIVE_PHOENIX:
                     {
                         Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 10.0f, true);
                         me->SummonCreature(NPC_EMBER_OF_ALAR, target ? *target : *me, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000);
                         me->SummonCreature(NPC_EMBER_OF_ALAR, target ? *target : *me, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000);
                         break;
                     }
                 case EVENT_REBIRTH_DIVE:
                     me->SetModelVisible(true);
                     me->CastSpell(me, SPELL_REBIRTH_DIVE, false);
                     break;
                 case EVENT_FINISH_DIVE:
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     break;
                 case EVENT_SPELL_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
             }
             if (me->isAttackReady())
             {
                 if (me->IsWithinMeleeRange(me->GetVictim()))
                 {
                     me->AttackerStateUpdate(me->GetVictim());
                     me->resetAttackTimer();
                 }
                 else
                 {
                     me->resetAttackTimer();
                     ThreatContainer::StorageType const& threatList = me->getThreatMgr().getThreatList();
                     for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
                         if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
                             if (me->IsWithinMeleeRange(unit))
{
                                 me->AttackerStateUpdate(unit);
                                 return;
                             }
                     me->CastSpell(me, SPELL_FLAME_BUFFET, false);
                 }
             }
         }
References alarPoints, Unit::AttackerStateUpdate(), BASE_ATTACK, Unit::CastSpell(), EVENT_CAST_DIVE_BOMB, EVENT_FINISH_DIVE, EVENT_MOVE_TO_PHASE_2, EVENT_REBIRTH, EVENT_REBIRTH_DIVE, EVENT_RELOCATE_MIDDLE, EVENT_SPELL_BERSERK, EVENT_SPELL_CHARGE, EVENT_SPELL_DIVE_BOMB, EVENT_SPELL_FLAME_PATCH, EVENT_SPELL_MELT_ARMOR, EVENT_START_DIVE, EVENT_START_QUILLS, EVENT_SUMMON_DIVE_PHOENIX, EVENT_SWITCH_PLATFORM, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Creature::GetWaypointPath(), Unit::HasUnitState(), IN_MILLISECONDS, Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MINUTE, MotionMaster::MoveChase(), MotionMaster::MovePoint(), MotionMaster::MoveSplinePath(), noQuillTimes, NPC_EMBER_OF_ALAR, NPC_FLAME_PATCH, platform, POINT_DIVE, POINT_MIDDLE, POINT_PLATFORM, POINT_QUILL, RAND(), REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Unit::resetAttackTimer(), roll_chance_i(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::setAttackTimer(), Unit::SetModelVisible(), Position::SetOrientation(), Creature::SetPosition(), Creature::SetReactState(), SPELL_BERSERK, SPELL_CHARGE, SPELL_DIVE_BOMB, SPELL_DIVE_BOMB_VISUAL, SPELL_EMBER_BLAST, SPELL_FLAME_BUFFET, SPELL_FLAME_QUILLS, SPELL_MELT_ARMOR, SPELL_REBIRTH_DIVE, SPELL_REBIRTH_PHASE2, startPath, Unit::StopMoving(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), sWaypointMgr, TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), WaypointData::x, WaypointData::y, and WaypointData::z.
Member Data Documentation
noQuillTimes
uint8 boss_alar::boss_alarAI::noQuillTimes
Definition at line 101 of file boss_alar.cpp.
Referenced by Reset(), and UpdateAI().
platform
uint8 boss_alar::boss_alarAI::platform
Definition at line 100 of file boss_alar.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
startPath
bool boss_alar::boss_alarAI::startPath
Definition at line 102 of file boss_alar.cpp.
Referenced by boss_alarAI(), JustReachedHome(), MovementInform(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp