Azerotcore-wotlk: deps/jemalloc/include/jemalloc/jemalloc.h File Reference
jemalloc.h File Reference
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <limits.h>
#include <strings.h>
Classes
struct extent_hooks_s
Macros
#define JEMALLOC_HAVE_ATTR
#define JEMALLOC_HAVE_ATTR_ALLOC_SIZE
#define JEMALLOC_HAVE_ATTR_FORMAT_ARG
#define JEMALLOC_HAVE_ATTR_FORMAT_GNU_PRINTF
#define JEMALLOC_HAVE_ATTR_FORMAT_PRINTF
#define JEMALLOC_OVERRIDE_MEMALIGN
#define JEMALLOC_OVERRIDE_VALLOC
#define JEMALLOC_USABLE_SIZE_CONST
#define JEMALLOC_USE_CXX_THROW
#define je_aligned_alloc aligned_alloc
#define je_calloc calloc
#define je_dallocx dallocx
#define je_free free
#define je_mallctl mallctl
#define je_mallctlbymib mallctlbymib
#define je_mallctlnametomib mallctlnametomib
#define je_malloc malloc
#define je_malloc_conf malloc_conf
#define je_malloc_message malloc_message
#define je_malloc_stats_print malloc_stats_print
#define je_malloc_usable_size malloc_usable_size
#define je_mallocx mallocx
#define je_smallocx_ea6b3e973b477b8061e0076bb257dbd7f3faa756 smallocx_ea6b3e973b477b8061e0076bb257dbd7f3faa756
#define je_nallocx nallocx
#define je_posix_memalign posix_memalign
#define je_rallocx rallocx
#define je_realloc realloc
#define je_sallocx sallocx
#define je_sdallocx sdallocx
#define je_xallocx xallocx
#define je_memalign memalign
#define je_valloc valloc
#define JEMALLOC_VERSION "5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756"
#define JEMALLOC_VERSION_MAJOR 5
#define JEMALLOC_VERSION_MINOR 2
#define JEMALLOC_VERSION_BUGFIX 1
#define JEMALLOC_VERSION_NREV 0
#define JEMALLOC_VERSION_GID "ea6b3e973b477b8061e0076bb257dbd7f3faa756"
#define JEMALLOC_VERSION_GID_IDENT ea6b3e973b477b8061e0076bb257dbd7f3faa756
#define MALLOCX_LG_ALIGN(la) ((int)(la))
#define MALLOCX_ALIGN(a)
#define MALLOCX_ZERO ((int)0x40)
#define MALLOCX_TCACHE(tc) ((int)(((tc)+2) << 8))
#define MALLOCX_TCACHE_NONE MALLOCX_TCACHE(-1)
#define MALLOCX_ARENA(a) ((((int)(a))+1) << 20)
#define MALLCTL_ARENAS_ALL 4096
#define MALLCTL_ARENAS_DESTROYED 4097
#define JEMALLOC_CXX_THROW
#define JEMALLOC_ATTR(s) __attribute__((s))
#define JEMALLOC_ALIGNED(s) JEMALLOC_ATTR(aligned(s))
#define JEMALLOC_ALLOC_SIZE(s) JEMALLOC_ATTR(alloc_size(s))
#define JEMALLOC_ALLOC_SIZE2(s1, s2) JEMALLOC_ATTR(alloc_size(s1, s2))
#define JEMALLOC_EXPORT JEMALLOC_ATTR(visibility("default"))
#define JEMALLOC_FORMAT_ARG(i) JEMALLOC_ATTR(__format_arg__(3))
#define JEMALLOC_FORMAT_PRINTF(s, i) JEMALLOC_ATTR(format(gnu_printf, s, i))
#define JEMALLOC_NOINLINE JEMALLOC_ATTR(noinline)
#define JEMALLOC_NOTHROW JEMALLOC_ATTR(nothrow)
#define JEMALLOC_SECTION(s) JEMALLOC_ATTR(section(s))
#define JEMALLOC_RESTRICT_RETURN
#define JEMALLOC_ALLOCATOR
Typedefs
typedef struct extent_hooks_s extent_hooks_t
typedef void *() extent_alloc_t(extent_hooks_t *, void *, size_t, size_t, bool *, bool *, unsigned)
typedef bool() extent_dalloc_t(extent_hooks_t *, void *, size_t, bool, unsigned)
typedef void() extent_destroy_t(extent_hooks_t *, void *, size_t, bool, unsigned)
typedef bool() extent_commit_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
typedef bool() extent_decommit_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
typedef bool() extent_purge_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
typedef bool() extent_split_t(extent_hooks_t *, void *, size_t, size_t, size_t, bool, unsigned)
typedef bool() extent_merge_t(extent_hooks_t *, void *, size_t, void *, size_t, bool, unsigned)
Functions
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_malloc (size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(malloc) JEMALLOC_ALLOC_SIZE(1)
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_calloc (size_t num, size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(malloc) JEMALLOC_ALLOC_SIZE2(1
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_posix_memalign (void **memptr, size_t alignment, size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(nonnull(1))
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_aligned_alloc (size_t alignment, size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(malloc) JEMALLOC_ALLOC_SIZE(2)
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_realloc (void *ptr, size_t size) JEMALLOC_CXX_THROW JEMALLOC_ALLOC_SIZE(2)
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_free (void *ptr) JEMALLOC_CXX_THROW
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_mallocx (size_t size, int flags) JEMALLOC_ATTR(malloc) JEMALLOC_ALLOC_SIZE(1)
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_rallocx (void *ptr, size_t size, int flags) JEMALLOC_ALLOC_SIZE(2)
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_xallocx (void *ptr, size_t size, size_t extra, int flags)
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_sallocx (const void *ptr, int flags) JEMALLOC_ATTR(pure)
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_dallocx (void *ptr, int flags)
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_sdallocx (void *ptr, size_t size, int flags)
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_nallocx (size_t size, int flags) JEMALLOC_ATTR(pure)
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctl (const char *name, void *oldp, size_t *oldlenp, void *newp, size_t newlen)
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctlnametomib (const char *name, size_t *mibp, size_t *miblenp)
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctlbymib (const size_t *mib, size_t miblen, void *oldp, size_t *oldlenp, void *newp, size_t newlen)
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_malloc_stats_print (void(*write_cb)(void *, const char *), void *je_cbopaque, const char *opts)
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_malloc_usable_size (JEMALLOC_USABLE_SIZE_CONST void *ptr) JEMALLOC_CXX_THROW
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_memalign (size_t alignment, size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(malloc)
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW * je_valloc (size_t size) JEMALLOC_CXX_THROW JEMALLOC_ATTR(malloc)
Variables
JEMALLOC_EXPORT const char * je_malloc_conf
JEMALLOC_EXPORT void(* je_malloc_message)(void *cbopaque, const char *s)
Macro Definition Documentation
je_aligned_alloc
#define je_aligned_alloc aligned_alloc
Definition at line 59 of file jemalloc.h.
je_calloc
#define je_calloc calloc
Definition at line 60 of file jemalloc.h.
je_dallocx
#define je_dallocx dallocx
Definition at line 61 of file jemalloc.h.
je_free
#define je_free free
Definition at line 62 of file jemalloc.h.
je_mallctl
#define je_mallctl mallctl
Definition at line 63 of file jemalloc.h.
je_mallctlbymib
#define je_mallctlbymib mallctlbymib
Definition at line 64 of file jemalloc.h.
je_mallctlnametomib
#define je_mallctlnametomib mallctlnametomib
Definition at line 65 of file jemalloc.h.
je_malloc
#define je_malloc malloc
Definition at line 66 of file jemalloc.h.
je_malloc_conf
#define je_malloc_conf malloc_conf
Definition at line 67 of file jemalloc.h.
je_malloc_message
#define je_malloc_message malloc_message
Definition at line 68 of file jemalloc.h.
je_malloc_stats_print
#define je_malloc_stats_print malloc_stats_print
Definition at line 69 of file jemalloc.h.
je_malloc_usable_size
#define je_malloc_usable_size malloc_usable_size
Definition at line 70 of file jemalloc.h.
je_mallocx
#define je_mallocx mallocx
Definition at line 71 of file jemalloc.h.
je_memalign
#define je_memalign memalign
Definition at line 80 of file jemalloc.h.
je_nallocx
#define je_nallocx nallocx
Definition at line 73 of file jemalloc.h.
je_posix_memalign
#define je_posix_memalign posix_memalign
Definition at line 74 of file jemalloc.h.
je_rallocx
#define je_rallocx rallocx
Definition at line 75 of file jemalloc.h.
je_realloc
#define je_realloc realloc
Definition at line 76 of file jemalloc.h.
je_sallocx
#define je_sallocx sallocx
Definition at line 77 of file jemalloc.h.
je_sdallocx
#define je_sdallocx sdallocx
Definition at line 78 of file jemalloc.h.
je_smallocx_ea6b3e973b477b8061e0076bb257dbd7f3faa756
#define je_smallocx_ea6b3e973b477b8061e0076bb257dbd7f3faa756 smallocx_ea6b3e973b477b8061e0076bb257dbd7f3faa756
Definition at line 72 of file jemalloc.h.
je_valloc
#define je_valloc valloc
Definition at line 81 of file jemalloc.h.
je_xallocx
#define je_xallocx xallocx
Definition at line 79 of file jemalloc.h.
JEMALLOC_ALIGNED
#define JEMALLOC_ALIGNED (s) JEMALLOC_ATTR(aligned(s))
Definition at line 172 of file jemalloc.h.
JEMALLOC_ALLOC_SIZE
#define JEMALLOC_ALLOC_SIZE (s) JEMALLOC_ATTR(alloc_size(s))
Definition at line 174 of file jemalloc.h.
JEMALLOC_ALLOC_SIZE2
#define JEMALLOC_ALLOC_SIZE2 (s1, s2) JEMALLOC_ATTR(alloc_size(s1, s2))
Definition at line 175 of file jemalloc.h.
JEMALLOC_ALLOCATOR
#define JEMALLOC_ALLOCATOR
Definition at line 199 of file jemalloc.h.
JEMALLOC_ATTR
#define JEMALLOC_ATTR (s) __attribute__((s))
Definition at line 171 of file jemalloc.h.
JEMALLOC_CXX_THROW
#define JEMALLOC_CXX_THROW
Definition at line 140 of file jemalloc.h.
JEMALLOC_EXPORT
#define JEMALLOC_EXPORT JEMALLOC_ATTR(visibility("default"))
Definition at line 181 of file jemalloc.h.
JEMALLOC_FORMAT_ARG
#define JEMALLOC_FORMAT_ARG (i) JEMALLOC_ATTR(__format_arg__(3))
Definition at line 184 of file jemalloc.h.
JEMALLOC_FORMAT_PRINTF
#define JEMALLOC_FORMAT_PRINTF (s, i) JEMALLOC_ATTR(format(gnu_printf, s, i))
Definition at line 189 of file jemalloc.h.
JEMALLOC_HAVE_ATTR
#define JEMALLOC_HAVE_ATTR
Definition at line 8 of file jemalloc.h.
JEMALLOC_HAVE_ATTR_ALLOC_SIZE
#define JEMALLOC_HAVE_ATTR_ALLOC_SIZE
Definition at line 11 of file jemalloc.h.
JEMALLOC_HAVE_ATTR_FORMAT_ARG
#define JEMALLOC_HAVE_ATTR_FORMAT_ARG
Definition at line 14 of file jemalloc.h.
JEMALLOC_HAVE_ATTR_FORMAT_GNU_PRINTF
#define JEMALLOC_HAVE_ATTR_FORMAT_GNU_PRINTF
Definition at line 17 of file jemalloc.h.
JEMALLOC_HAVE_ATTR_FORMAT_PRINTF
#define JEMALLOC_HAVE_ATTR_FORMAT_PRINTF
Definition at line 20 of file jemalloc.h.
JEMALLOC_NOINLINE
#define JEMALLOC_NOINLINE JEMALLOC_ATTR(noinline)
Definition at line 195 of file jemalloc.h.
JEMALLOC_NOTHROW
#define JEMALLOC_NOTHROW JEMALLOC_ATTR(nothrow)
Definition at line 196 of file jemalloc.h.
JEMALLOC_OVERRIDE_MEMALIGN
#define JEMALLOC_OVERRIDE_MEMALIGN
Definition at line 26 of file jemalloc.h.
JEMALLOC_OVERRIDE_VALLOC
#define JEMALLOC_OVERRIDE_VALLOC
Definition at line 27 of file jemalloc.h.
JEMALLOC_RESTRICT_RETURN
#define JEMALLOC_RESTRICT_RETURN
Definition at line 198 of file jemalloc.h.
JEMALLOC_SECTION
#define JEMALLOC_SECTION (s) JEMALLOC_ATTR(section(s))
Definition at line 197 of file jemalloc.h.
JEMALLOC_USABLE_SIZE_CONST
#define JEMALLOC_USABLE_SIZE_CONST
Definition at line 36 of file jemalloc.h.
JEMALLOC_USE_CXX_THROW
#define JEMALLOC_USE_CXX_THROW
Definition at line 43 of file jemalloc.h.
JEMALLOC_VERSION
#define JEMALLOC_VERSION "5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756"
Definition at line 90 of file jemalloc.h.
JEMALLOC_VERSION_BUGFIX
#define JEMALLOC_VERSION_BUGFIX 1
Definition at line 93 of file jemalloc.h.
JEMALLOC_VERSION_GID
#define JEMALLOC_VERSION_GID "ea6b3e973b477b8061e0076bb257dbd7f3faa756"
Definition at line 95 of file jemalloc.h.
JEMALLOC_VERSION_GID_IDENT
#define JEMALLOC_VERSION_GID_IDENT ea6b3e973b477b8061e0076bb257dbd7f3faa756
Definition at line 96 of file jemalloc.h.
JEMALLOC_VERSION_MAJOR
#define JEMALLOC_VERSION_MAJOR 5
Definition at line 91 of file jemalloc.h.
JEMALLOC_VERSION_MINOR
#define JEMALLOC_VERSION_MINOR 2
Definition at line 92 of file jemalloc.h.
JEMALLOC_VERSION_NREV
#define JEMALLOC_VERSION_NREV 0
Definition at line 94 of file jemalloc.h.
MALLCTL_ARENAS_ALL
#define MALLCTL_ARENAS_ALL 4096
Definition at line 130 of file jemalloc.h.
MALLCTL_ARENAS_DESTROYED
#define MALLCTL_ARENAS_DESTROYED 4097
Definition at line 135 of file jemalloc.h.
MALLOCX_ALIGN
#define MALLOCX_ALIGN (a)
Value:
     ((int)(((size_t)(a) < (size_t)INT_MAX) ? ffs((int)(a))-1 : \
     ffs((int)(((size_t)(a))>>32))+31))
Definition at line 102 of file jemalloc.h.
MALLOCX_ARENA
#define MALLOCX_ARENA (a) ((((int)(a))+1) << 20)
Definition at line 116 of file jemalloc.h.
MALLOCX_LG_ALIGN
#define MALLOCX_LG_ALIGN (la) ((int)(la))
Definition at line 98 of file jemalloc.h.
MALLOCX_TCACHE
#define MALLOCX_TCACHE (tc) ((int)(((tc)+2) << 8))
Definition at line 111 of file jemalloc.h.
MALLOCX_TCACHE_NONE
#define MALLOCX_TCACHE_NONE MALLOCX_TCACHE(-1)
Definition at line 112 of file jemalloc.h.
MALLOCX_ZERO
#define MALLOCX_ZERO ((int)0x40)
Definition at line 106 of file jemalloc.h.
Typedef Documentation
extent_alloc_t
typedef void*() extent_alloc_t(extent_hooks_t *, void *, size_t, size_t, bool *, bool *, unsigned)
Definition at line 288 of file jemalloc.h.
extent_commit_t
typedef bool() extent_commit_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
Definition at line 312 of file jemalloc.h.
extent_dalloc_t
typedef bool() extent_dalloc_t(extent_hooks_t *, void *, size_t, bool, unsigned)
Definition at line 296 of file jemalloc.h.
extent_decommit_t
typedef bool() extent_decommit_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
Definition at line 320 of file jemalloc.h.
extent_destroy_t
typedef void() extent_destroy_t(extent_hooks_t *, void *, size_t, bool, unsigned)
Definition at line 304 of file jemalloc.h.
extent_hooks_t
typedef struct extent_hooks_s extent_hooks_t
Definition at line 277 of file jemalloc.h.
extent_merge_t
typedef bool() extent_merge_t(extent_hooks_t *, void *, size_t, void *, size_t, bool, unsigned)
Definition at line 344 of file jemalloc.h.
extent_purge_t
typedef bool() extent_purge_t(extent_hooks_t *, void *, size_t, size_t, size_t, unsigned)
Definition at line 328 of file jemalloc.h.
extent_split_t
typedef bool() extent_split_t(extent_hooks_t *, void *, size_t, size_t, size_t, bool, unsigned)
Definition at line 336 of file jemalloc.h.
Function Documentation
je_aligned_alloc()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_aligned_alloc (size_t alignment, size_t size)
je_calloc()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_calloc (size_t num, size_t size)
Referenced by zone_calloc().
je_dallocx()
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_dallocx (void * ptr, int flags)
Definition at line 3487 of file jemalloc.c.
{
     LOG("core.dallocx.entry", "ptr: %p, flags: %d", ptr, flags);
     assert(ptr != NULL);
     assert(malloc_initialized() || IS_INITIALIZER);
     tsd_t *tsd = tsd_fetch();
     bool fast = tsd_fast(tsd);
     check_entry_exit_locking(tsd_tsdn(tsd));
     tcache_t *tcache;
     if (unlikely((flags & MALLOCX_TCACHE_MASK) != 0)) {
         /* Not allowed to be reentrant and specify a custom tcache. */
         assert(tsd_reentrancy_level_get(tsd) == 0);
         if ((flags & MALLOCX_TCACHE_MASK) == MALLOCX_TCACHE_NONE) {
             tcache = NULL;
         } else {
             tcache = tcaches_get(tsd, MALLOCX_TCACHE_GET(flags));
         }
     } else {
         if (likely(fast)) {
             tcache = tsd_tcachep_get(tsd);
             assert(tcache == tcache_get(tsd));
         } else {
             if (likely(tsd_reentrancy_level_get(tsd) == 0)) {
                 tcache = tcache_get(tsd);
             }  else {
                 tcache = NULL;
             }
         }
     }
     UTRACE(ptr, 0, 0);
     if (likely(fast)) {
         tsd_assert_fast(tsd);
         ifree(tsd, ptr, tcache, false);
     } else {
         uintptr_t args_raw[3] = {(uintptr_t)ptr, flags};
         hook_invoke_dalloc(hook_dalloc_dallocx, ptr, args_raw);
         ifree(tsd, ptr, tcache, true);
     }
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.dallocx.exit", "");
 }
References assert(), check_entry_exit_locking(), hook_dalloc_dallocx, hook_invoke_dalloc, ifree(), IS_INITIALIZER, likely, LOG, malloc_initialized(), MALLOCX_TCACHE_GET, MALLOCX_TCACHE_MASK, MALLOCX_TCACHE_NONE, NULL, ptr(), tcache_get(), tcaches_get(), tsd_assert_fast(), tsd_fast(), tsd_fetch(), tsd_tsdn(), uintptr_t, unlikely, and UTRACE.
je_free()
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_free (void * ptr)
Definition at line 2863 of file jemalloc.c.
                    {
     LOG("core.free.entry", "ptr: %p", ptr);
     if (!free_fastpath(ptr, 0, false)) {
         free_default(ptr);
     }
     LOG("core.free.exit", "");
 }
References free_default(), free_fastpath(), LOG, and ptr().
je_mallctl()
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctl (const char * name, void * oldp, size_t * oldlenp, void * newp, size_t newlen)
Definition at line 3645 of file jemalloc.c.
                    {
     int ret;
     tsd_t *tsd;
     LOG("core.mallctl.entry", "name: %s", name);
     if (unlikely(malloc_init())) {
         LOG("core.mallctl.exit", "result: %d", EAGAIN);
         return EAGAIN;
     }
     tsd = tsd_fetch();
     check_entry_exit_locking(tsd_tsdn(tsd));
     ret = ctl_byname(tsd, name, oldp, oldlenp, newp, newlen);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.mallctl.exit", "result: %d", ret);
     return ret;
 }
References check_entry_exit_locking(), ctl_byname, LOG, malloc_init(), ret, tsd_fetch(), tsd_tsdn(), and unlikely.
je_mallctlbymib()
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctlbymib (const size_t * mib, size_t miblen, void * oldp, size_t * oldlenp, void * newp, size_t newlen)
Definition at line 3687 of file jemalloc.c.
{
     int ret;
     tsd_t *tsd;
     LOG("core.mallctlbymib.entry", "");
     if (unlikely(malloc_init())) {
         LOG("core.mallctlbymib.exit", "result: %d", EAGAIN);
         return EAGAIN;
     }
     tsd = tsd_fetch();
     check_entry_exit_locking(tsd_tsdn(tsd));
     ret = ctl_bymib(tsd, mib, miblen, oldp, oldlenp, newp, newlen);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.mallctlbymib.exit", "result: %d", ret);
     return ret;
 }
References check_entry_exit_locking(), ctl_bymib, LOG, malloc_init(), ret, tsd_fetch(), tsd_tsdn(), and unlikely.
je_mallctlnametomib()
JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_mallctlnametomib (const char * name, size_t * mibp, size_t * miblenp)
Definition at line 3667 of file jemalloc.c.
{
     int ret;
     LOG("core.mallctlnametomib.entry", "name: %s", name);
     if (unlikely(malloc_init())) {
         LOG("core.mallctlnametomib.exit", "result: %d", EAGAIN);
         return EAGAIN;
     }
     tsd_t *tsd = tsd_fetch();
     check_entry_exit_locking(tsd_tsdn(tsd));
     ret = ctl_nametomib(tsd, name, mibp, miblenp);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.mallctlnametomib.exit", "result: %d", ret);
     return ret;
 }
References check_entry_exit_locking(), ctl_nametomib, LOG, malloc_init(), ret, tsd_fetch(), tsd_tsdn(), and unlikely.
je_malloc()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_malloc (size_t size)
Referenced by handleOOM(), newImpl(), zone_batch_malloc(), and zone_malloc().
je_malloc_stats_print()
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_malloc_stats_print (void(*)(void *, const char *) write_cb, void * je_cbopaque, const char * opts)
Definition at line 3708 of file jemalloc.c.
                       {
     tsdn_t *tsdn;
     LOG("core.malloc_stats_print.entry", "");
     tsdn = tsdn_fetch();
     check_entry_exit_locking(tsdn);
     stats_print(write_cb, cbopaque, opts);
     check_entry_exit_locking(tsdn);
     LOG("core.malloc_stats_print.exit", "");
 }
References check_entry_exit_locking(), LOG, stats_print, and tsdn_fetch().
Referenced by stats_print_atexit().
je_malloc_usable_size()
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_malloc_usable_size (JEMALLOC_USABLE_SIZE_CONST void * ptr)
Definition at line 3722 of file jemalloc.c.
{
     size_t ret;
     tsdn_t *tsdn;
     LOG("core.malloc_usable_size.entry", "ptr: %p", ptr);
     assert(malloc_initialized() || IS_INITIALIZER);
     tsdn = tsdn_fetch();
     check_entry_exit_locking(tsdn);
     if (unlikely(ptr == NULL)) {
         ret = 0;
     } else {
         if (config_debug || force_ivsalloc) {
             ret = ivsalloc(tsdn, ptr);
             assert(force_ivsalloc || ret != 0);
         } else {
             ret = isalloc(tsdn, ptr);
         }
     }
     check_entry_exit_locking(tsdn);
     LOG("core.malloc_usable_size.exit", "result: %zu", ret);
     return ret;
 }
References assert(), check_entry_exit_locking(), config_debug, force_ivsalloc, IS_INITIALIZER, isalloc(), ivsalloc(), LOG, malloc_initialized(), NULL, ptr(), ret, tsdn_fetch(), and unlikely.
je_mallocx()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_mallocx (size_t size, int flags)
je_memalign()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_memalign (size_t alignment, size_t size)
je_nallocx()
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_nallocx (size_t size, int flags)
Definition at line 3619 of file jemalloc.c.
{
     size_t usize;
     tsdn_t *tsdn;
     assert(size != 0);
     if (unlikely(malloc_init())) {
         LOG("core.nallocx.exit", "result: %zu", ZU(0));
         return 0;
     }
     tsdn = tsdn_fetch();
     check_entry_exit_locking(tsdn);
     usize = inallocx(tsdn, size, flags);
     if (unlikely(usize > SC_LARGE_MAXCLASS)) {
         LOG("core.nallocx.exit", "result: %zu", ZU(0));
         return 0;
     }
     check_entry_exit_locking(tsdn);
     LOG("core.nallocx.exit", "result: %zu", usize);
     return usize;
 }
References assert(), check_entry_exit_locking(), inallocx(), LOG, malloc_init(), SC_LARGE_MAXCLASS, tsdn_fetch(), unlikely, and ZU.
je_posix_memalign()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW JEMALLOC_EXPORT int JEMALLOC_NOTHROW je_posix_memalign (void ** memptr, size_t alignment, size_t size)
Definition at line 2393 of file jemalloc.c.
{
     int ret;
     static_opts_t sopts;
     dynamic_opts_t dopts;
     LOG("core.posix_memalign.entry", "mem ptr: %p, alignment: %zu, "
         "size: %zu", memptr, alignment, size);
     static_opts_init(&sopts);
     dynamic_opts_init(&dopts);
     sopts.bump_empty_aligned_alloc = true;
     sopts.min_alignment = sizeof(void *);
     sopts.oom_string =
         "<jemalloc>: Error allocating aligned memory: out of memory\n";
     sopts.invalid_alignment_string =
         "<jemalloc>: Error allocating aligned memory: invalid alignment\n";
     dopts.result = memptr;
     dopts.num_items = 1;
     dopts.item_size = size;
     dopts.alignment = alignment;
     ret = imalloc(&sopts, &dopts);
     if (sopts.slow) {
         uintptr_t args[3] = {(uintptr_t)memptr, (uintptr_t)alignment,
             (uintptr_t)size};
         hook_invoke_alloc(hook_alloc_posix_memalign, *memptr,
             (uintptr_t)ret, args);
     }
     LOG("core.posix_memalign.exit", "result: %d, alloc ptr: %p", ret,
         *memptr);
     return ret;
 }
References dynamic_opts_s::alignment, static_opts_s::bump_empty_aligned_alloc, dynamic_opts_init(), hook_alloc_posix_memalign, hook_invoke_alloc, imalloc(), static_opts_s::invalid_alignment_string, dynamic_opts_s::item_size, LOG, static_opts_s::min_alignment, dynamic_opts_s::num_items, static_opts_s::oom_string, dynamic_opts_s::result, ret, static_opts_s::slow, static_opts_init(), and uintptr_t.
je_rallocx()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_rallocx (void * ptr, size_t size, int flags)
Definition at line 3216 of file jemalloc.c.
{
     void *p;
     tsd_t *tsd;
     size_t usize;
     size_t old_usize;
     size_t alignment = MALLOCX_ALIGN_GET(flags);
     bool zero = flags & MALLOCX_ZERO;
     arena_t *arena;
     tcache_t *tcache;
     LOG("core.rallocx.entry", "ptr: %p, size: %zu, flags: %d", ptr,
         size, flags);
     assert(ptr != NULL);
     assert(size != 0);
     assert(malloc_initialized() || IS_INITIALIZER);
     tsd = tsd_fetch();
     check_entry_exit_locking(tsd_tsdn(tsd));
     if (unlikely((flags & MALLOCX_ARENA_MASK) != 0)) {
         unsigned arena_ind = MALLOCX_ARENA_GET(flags);
         arena = arena_get(tsd_tsdn(tsd), arena_ind, true);
         if (unlikely(arena == NULL)) {
             goto label_oom;
         }
     } else {
         arena = NULL;
     }
     if (unlikely((flags & MALLOCX_TCACHE_MASK) != 0)) {
         if ((flags & MALLOCX_TCACHE_MASK) == MALLOCX_TCACHE_NONE) {
             tcache = NULL;
         } else {
             tcache = tcaches_get(tsd, MALLOCX_TCACHE_GET(flags));
         }
     } else {
         tcache = tcache_get(tsd);
     }
     alloc_ctx_t alloc_ctx;
     rtree_ctx_t *rtree_ctx = tsd_rtree_ctx(tsd);
     rtree_szind_slab_read(tsd_tsdn(tsd), &extents_rtree, rtree_ctx,
         (uintptr_t)ptr, true, &alloc_ctx.szind, &alloc_ctx.slab);
     assert(alloc_ctx.szind != SC_NSIZES);
     old_usize = sz_index2size(alloc_ctx.szind);
     assert(old_usize == isalloc(tsd_tsdn(tsd), ptr));
     hook_ralloc_args_t hook_args = {false, {(uintptr_t)ptr, size, flags,
         0}};
     if (config_prof && opt_prof) {
         usize = (alignment == 0) ?
             sz_s2u(size) : sz_sa2u(size, alignment);
         if (unlikely(usize == 0
             || usize > SC_LARGE_MAXCLASS)) {
             goto label_oom;
         }
         p = irallocx_prof(tsd, ptr, old_usize, size, alignment, &usize,
             zero, tcache, arena, &alloc_ctx, &hook_args);
         if (unlikely(p == NULL)) {
             goto label_oom;
         }
     } else {
         p = iralloct(tsd_tsdn(tsd), ptr, old_usize, size, alignment,
             zero, tcache, arena, &hook_args);
         if (unlikely(p == NULL)) {
             goto label_oom;
         }
         if (config_stats) {
             usize = isalloc(tsd_tsdn(tsd), p);
         }
     }
     assert(alignment == 0 || ((uintptr_t)p & (alignment - 1)) == ZU(0));
     if (config_stats) {
         *tsd_thread_allocatedp_get(tsd) += usize;
         *tsd_thread_deallocatedp_get(tsd) += old_usize;
     }
     UTRACE(ptr, size, p);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.rallocx.exit", "result: %p", p);
     return p;
 label_oom:
     if (config_xmalloc && unlikely(opt_xmalloc)) {
         malloc_write("<jemalloc>: Error in rallocx(): out of memory\n");
         abort();
     }
     UTRACE(ptr, size, 0);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.rallocx.exit", "result: %p", NULL);
     return NULL;
 }
References arena, arena_get(), assert(), check_entry_exit_locking(), config_prof, config_stats, config_xmalloc, extents_rtree, iralloct(), irallocx_prof(), IS_INITIALIZER, isalloc(), LOG, malloc_initialized(), malloc_write, MALLOCX_ALIGN_GET, MALLOCX_ARENA_GET, MALLOCX_ARENA_MASK, MALLOCX_TCACHE_GET, MALLOCX_TCACHE_MASK, MALLOCX_TCACHE_NONE, MALLOCX_ZERO, NULL, opt_prof, opt_xmalloc, ptr(), rtree_szind_slab_read(), SC_LARGE_MAXCLASS, SC_NSIZES, alloc_ctx_s::slab, sz_index2size(), sz_s2u(), sz_sa2u(), alloc_ctx_s::szind, tcache_get(), tcaches_get(), tsd_fetch(), tsd_rtree_ctx(), tsd_tsdn(), uintptr_t, unlikely, UTRACE, G3D::zero(), and ZU.
je_realloc()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_realloc (void * ptr, size_t size)
Definition at line 2653 of file jemalloc.c.
{
     void *ret;
     tsdn_t *tsdn JEMALLOC_CC_SILENCE_INIT(NULL);
     size_t usize JEMALLOC_CC_SILENCE_INIT(0);
     size_t old_usize = 0;
     size_t size = arg_size;
     LOG("core.realloc.entry", "ptr: %p, size: %zu\n", ptr, size);
     if (unlikely(size == 0)) {
         if (ptr != NULL) {
             /* realloc(ptr, 0) is equivalent to free(ptr). */
             UTRACE(ptr, 0, 0);
             tcache_t *tcache;
             tsd_t *tsd = tsd_fetch();
             if (tsd_reentrancy_level_get(tsd) == 0) {
                 tcache = tcache_get(tsd);
             } else {
                 tcache = NULL;
             }
             uintptr_t args[3] = {(uintptr_t)ptr, size};
             hook_invoke_dalloc(hook_dalloc_realloc, ptr, args);
             ifree(tsd, ptr, tcache, true);
             LOG("core.realloc.exit", "result: %p", NULL);
             return NULL;
         }
         size = 1;
     }
     if (likely(ptr != NULL)) {
         assert(malloc_initialized() || IS_INITIALIZER);
         tsd_t *tsd = tsd_fetch();
         check_entry_exit_locking(tsd_tsdn(tsd));
         hook_ralloc_args_t hook_args = {true, {(uintptr_t)ptr,
             (uintptr_t)arg_size, 0, 0}};
         alloc_ctx_t alloc_ctx;
         rtree_ctx_t *rtree_ctx = tsd_rtree_ctx(tsd);
         rtree_szind_slab_read(tsd_tsdn(tsd), &extents_rtree, rtree_ctx,
             (uintptr_t)ptr, true, &alloc_ctx.szind, &alloc_ctx.slab);
         assert(alloc_ctx.szind != SC_NSIZES);
         old_usize = sz_index2size(alloc_ctx.szind);
         assert(old_usize == isalloc(tsd_tsdn(tsd), ptr));
         if (config_prof && opt_prof) {
             usize = sz_s2u(size);
             if (unlikely(usize == 0
                 || usize > SC_LARGE_MAXCLASS)) {
                 ret = NULL;
             } else {
                 ret = irealloc_prof(tsd, ptr, old_usize, usize,
                     &alloc_ctx, &hook_args);
             }
         } else {
             if (config_stats) {
                 usize = sz_s2u(size);
             }
             ret = iralloc(tsd, ptr, old_usize, size, 0, false,
                 &hook_args);
         }
         tsdn = tsd_tsdn(tsd);
     } else {
         /* realloc(NULL, size) is equivalent to malloc(size). */
         static_opts_t sopts;
         dynamic_opts_t dopts;
         static_opts_init(&sopts);
         dynamic_opts_init(&dopts);
         sopts.null_out_result_on_error = true;
         sopts.set_errno_on_error = true;
         sopts.oom_string =
             "<jemalloc>: Error in realloc(): out of memory\n";
         dopts.result = &ret;
         dopts.num_items = 1;
         dopts.item_size = size;
         imalloc(&sopts, &dopts);
         if (sopts.slow) {
             uintptr_t args[3] = {(uintptr_t)ptr, arg_size};
             hook_invoke_alloc(hook_alloc_realloc, ret,
                 (uintptr_t)ret, args);
         }
         return ret;
     }
     if (unlikely(ret == NULL)) {
         if (config_xmalloc && unlikely(opt_xmalloc)) {
             malloc_write("<jemalloc>: Error in realloc(): "
                 "out of memory\n");
             abort();
         }
         set_errno(ENOMEM);
     }
     if (config_stats && likely(ret != NULL)) {
         tsd_t *tsd;
         assert(usize == isalloc(tsdn, ret));
         tsd = tsdn_tsd(tsdn);
         *tsd_thread_allocatedp_get(tsd) += usize;
         *tsd_thread_deallocatedp_get(tsd) += old_usize;
     }
     UTRACE(ptr, size, ret);
     check_entry_exit_locking(tsdn);
     LOG("core.realloc.exit", "result: %p", ret);
     return ret;
 }
References assert(), check_entry_exit_locking(), config_prof, config_stats, config_xmalloc, dynamic_opts_init(), extents_rtree, hook_alloc_realloc, hook_dalloc_realloc, hook_invoke_alloc, hook_invoke_dalloc, ifree(), imalloc(), iralloc(), irealloc_prof(), IS_INITIALIZER, isalloc(), dynamic_opts_s::item_size, JEMALLOC_CC_SILENCE_INIT, likely, LOG, malloc_initialized(), malloc_write, NULL, static_opts_s::null_out_result_on_error, dynamic_opts_s::num_items, static_opts_s::oom_string, opt_prof, opt_xmalloc, ptr(), dynamic_opts_s::result, ret, rtree_szind_slab_read(), SC_LARGE_MAXCLASS, SC_NSIZES, set_errno(), static_opts_s::set_errno_on_error, alloc_ctx_s::slab, static_opts_s::slow, static_opts_init(), sz_index2size(), sz_s2u(), alloc_ctx_s::szind, tcache_get(), tsd_fetch(), tsd_rtree_ctx(), tsd_tsdn(), tsdn_tsd(), uintptr_t, unlikely, and UTRACE.
je_sallocx()
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_sallocx (const void * ptr, int flags)
Definition at line 3461 of file jemalloc.c.
{
     size_t usize;
     tsdn_t *tsdn;
     LOG("core.sallocx.entry", "ptr: %p, flags: %d", ptr, flags);
     assert(malloc_initialized() || IS_INITIALIZER);
     assert(ptr != NULL);
     tsdn = tsdn_fetch();
     check_entry_exit_locking(tsdn);
     if (config_debug || force_ivsalloc) {
         usize = ivsalloc(tsdn, ptr);
         assert(force_ivsalloc || usize != 0);
     } else {
         usize = isalloc(tsdn, ptr);
     }
     check_entry_exit_locking(tsdn);
     LOG("core.sallocx.exit", "result: %zu", usize);
     return usize;
 }
References assert(), check_entry_exit_locking(), config_debug, force_ivsalloc, IS_INITIALIZER, isalloc(), ivsalloc(), LOG, malloc_initialized(), NULL, ptr(), and tsdn_fetch().
je_sdallocx()
JEMALLOC_EXPORT void JEMALLOC_NOTHROW je_sdallocx (void * ptr, size_t size, int flags)
Definition at line 3594 of file jemalloc.c.
{
     LOG("core.sdallocx.entry", "ptr: %p, size: %zu, flags: %d", ptr,
         size, flags);
     if (flags !=0 || !free_fastpath(ptr, size, true)) {
         sdallocx_default(ptr, size, flags);
     }
     LOG("core.sdallocx.exit", "");
 }
References free_fastpath(), LOG, ptr(), and sdallocx_default().
je_valloc()
JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN void JEMALLOC_NOTHROW* je_valloc (size_t size)
je_xallocx()
JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW je_xallocx (void * ptr, size_t size, size_t extra, int flags)
Definition at line 3390 of file jemalloc.c.
{
     tsd_t *tsd;
     size_t usize, old_usize;
     size_t alignment = MALLOCX_ALIGN_GET(flags);
     bool zero = flags & MALLOCX_ZERO;
     LOG("core.xallocx.entry", "ptr: %p, size: %zu, extra: %zu, "
         "flags: %d", ptr, size, extra, flags);
     assert(ptr != NULL);
     assert(size != 0);
     assert(SIZE_T_MAX - size >= extra);
     assert(malloc_initialized() || IS_INITIALIZER);
     tsd = tsd_fetch();
     check_entry_exit_locking(tsd_tsdn(tsd));
     alloc_ctx_t alloc_ctx;
     rtree_ctx_t *rtree_ctx = tsd_rtree_ctx(tsd);
     rtree_szind_slab_read(tsd_tsdn(tsd), &extents_rtree, rtree_ctx,
         (uintptr_t)ptr, true, &alloc_ctx.szind, &alloc_ctx.slab);
     assert(alloc_ctx.szind != SC_NSIZES);
     old_usize = sz_index2size(alloc_ctx.szind);
     assert(old_usize == isalloc(tsd_tsdn(tsd), ptr));
     /*
      * The API explicitly absolves itself of protecting against (size +
      * extra) numerical overflow, but we may need to clamp extra to avoid
      * exceeding SC_LARGE_MAXCLASS.
      *
      * Ordinarily, size limit checking is handled deeper down, but here we
      * have to check as part of (size + extra) clamping, since we need the
      * clamped value in the above helper functions.
      */
     if (unlikely(size > SC_LARGE_MAXCLASS)) {
         usize = old_usize;
         goto label_not_resized;
     }
     if (unlikely(SC_LARGE_MAXCLASS - size < extra)) {
         extra = SC_LARGE_MAXCLASS - size;
     }
     if (config_prof && opt_prof) {
         usize = ixallocx_prof(tsd, ptr, old_usize, size, extra,
             alignment, zero, &alloc_ctx);
     } else {
         usize = ixallocx_helper(tsd_tsdn(tsd), ptr, old_usize, size,
             extra, alignment, zero);
     }
     if (unlikely(usize == old_usize)) {
         goto label_not_resized;
     }
     if (config_stats) {
         *tsd_thread_allocatedp_get(tsd) += usize;
         *tsd_thread_deallocatedp_get(tsd) += old_usize;
     }
 label_not_resized:
     if (unlikely(!tsd_fast(tsd))) {
         uintptr_t args[4] = {(uintptr_t)ptr, size, extra, flags};
         hook_invoke_expand(hook_expand_xallocx, ptr, old_usize,
             usize, (uintptr_t)usize, args);
     }
     UTRACE(ptr, size, ptr);
     check_entry_exit_locking(tsd_tsdn(tsd));
     LOG("core.xallocx.exit", "result: %zu", usize);
     return usize;
 }
References assert(), check_entry_exit_locking(), config_prof, config_stats, extents_rtree, hook_expand_xallocx, hook_invoke_expand, IS_INITIALIZER, isalloc(), ixallocx_helper(), ixallocx_prof(), LOG, malloc_initialized(), MALLOCX_ALIGN_GET, MALLOCX_ZERO, NULL, opt_prof, ptr(), rtree_szind_slab_read(), SC_LARGE_MAXCLASS, SC_NSIZES, SIZE_T_MAX, alloc_ctx_s::slab, sz_index2size(), alloc_ctx_s::szind, tsd_fast(), tsd_fetch(), tsd_rtree_ctx(), tsd_tsdn(), uintptr_t, unlikely, UTRACE, and G3D::zero().
Variable Documentation
je_malloc_conf
JEMALLOC_EXPORT const char* je_malloc_conf extern
Definition at line 27 of file jemalloc.c.
Referenced by obtain_malloc_conf().
je_malloc_message
JEMALLOC_EXPORT void(* je_malloc_message) (void *cbopaque, const char *s) (void * cbopaque, const char * s) extern
Definition at line 76 of file malloc_io.c.
Referenced by malloc_vcprintf(), and malloc_write().