Azerotcore-wotlk: deps/mysqllite/mysys/my_quick.c File Reference
my_quick.c File Reference
#include "mysys_priv.h"
#include "my_nosys.h"
Functions
size_t my_quick_read (File Filedes, uchar *Buffer, size_t Count, myf MyFlags)
size_t my_quick_write (File Filedes, const uchar *Buffer, size_t Count)
Function Documentation
my_quick_read()
size_t my_quick_read (File Filedes, uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 26 of file my_quick.c.
 {
   size_t readbytes;
 #ifdef _WIN32
   readbytes= my_win_read(Filedes, Buffer, Count);
 #else
   readbytes= read(Filedes, Buffer, Count);
 #endif
   if(readbytes != Count)
   {
 #ifndef DBUG_OFF
     if ((readbytes == 0 || readbytes == (size_t) -1) && errno == EINTR)
     {
       DBUG_PRINT("error", ("my_quick_read() was interrupted and returned %d"
                            ".  This function does not retry the read!",
                            (int) readbytes));
     }
 #endif
     my_errno=errno;
     return readbytes;
   }
   return (MyFlags & (MY_NABP | MY_FNABP)) ? 0 : readbytes;
 }
References Acore::Count(), DBUG_PRINT, errno, my_errno, MY_FNABP, MY_NABP, and read.
my_quick_write()
size_t my_quick_write (File Filedes, const uchar * Buffer, size_t Count)
Definition at line 52 of file my_quick.c.
 {
 #ifdef _WIN32
   return my_win_write(Filedes, Buffer, Count);
 #else
 #ifndef DBUG_OFF
   size_t writtenbytes;
 #endif
   if ((
 #ifndef DBUG_OFF
        writtenbytes =
 #endif
        (size_t) write(Filedes,Buffer,Count)) != Count)
   {
 #ifndef DBUG_OFF
     if ((writtenbytes == 0 || writtenbytes == (size_t) -1) && errno == EINTR)
     {
       DBUG_PRINT("error", ("my_quick_write() was interrupted and returned %d"
                            ".  This function does not retry the write!",
                            (int) writtenbytes));
     }
 #endif
     my_errno=errno;
     return (size_t) -1;
   }
   return 0;
 #endif
 }
References Acore::Count(), DBUG_PRINT, endif(), errno, my_errno, and write.