Azerotcore-wotlk: npc_eris_hevenfire Class Reference
npc_eris_hevenfire Class Reference
Classes
struct npc_eris_hevenfireAI
Public Member Functions
npc_eris_hevenfire ()
CreatureAI * GetAI (Creature *creature) const override
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 61 of file zone_eastern_plaguelands.cpp.
Constructor & Destructor Documentation
npc_eris_hevenfire()
npc_eris_hevenfire::npc_eris_hevenfire () inline
Definition at line 64 of file zone_eastern_plaguelands.cpp.
 : CreatureScript("npc_eris_hevenfire") { }
Member Function Documentation
GetAI()
CreatureAI* npc_eris_hevenfire::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 66 of file zone_eastern_plaguelands.cpp.
     {
         return new npc_eris_hevenfireAI(creature);
     }
OnQuestAccept()
bool npc_eris_hevenfire::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 71 of file zone_eastern_plaguelands.cpp.
     {
         if (quest->GetQuestId() == QUEST_BALANCE_OF_LIGHT_AND_SHADOW)
         {
             creature->AI()->SetData(player->GetFaction(), 0);
             creature->AI()->SetGUID(player->GetGUID());
         }
         return true;
     }
References Creature::AI(), Unit::GetFaction(), Object::GetGUID(), Quest::GetQuestId(), QUEST_BALANCE_OF_LIGHT_AND_SHADOW, UnitAI::SetData(), and UnitAI::SetGUID().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_eastern_plaguelands.cpp