Azerotcore-wotlk: FrostwingVrykulSearcher Class Reference
FrostwingVrykulSearcher Class Reference
Public Member Functions
FrostwingVrykulSearcher (Creature const *source, float range)
bool operator() (Unit *unit)
Private Attributes
Creature const * _source
float _range
Detailed Description
Definition at line 283 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
FrostwingVrykulSearcher()
FrostwingVrykulSearcher::FrostwingVrykulSearcher (Creature const * source, float range) inline
Definition at line 286 of file icecrown_citadel.cpp.
 : _source(source), _range(range) {}
Member Function Documentation
operator()()
bool FrostwingVrykulSearcher::operator() (Unit * unit) inline
Definition at line 288 of file icecrown_citadel.cpp.
     {
         if (!unit->IsAlive())
             return false;
         switch (unit->GetEntry())
         {
             case NPC_YMIRJAR_BATTLE_MAIDEN:
             case NPC_YMIRJAR_DEATHBRINGER:
             case NPC_YMIRJAR_FROSTBINDER:
             case NPC_YMIRJAR_HUNTRESS:
             case NPC_YMIRJAR_WARLORD:
                 break;
             default:
                 return false;
         }
         if (!unit->IsWithinDist(_source, _range, false))
             return false;
         return true;
     }
References _range, _source, Object::GetEntry(), Unit::IsAlive(), WorldObject::IsWithinDist(), NPC_YMIRJAR_BATTLE_MAIDEN, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, and NPC_YMIRJAR_WARLORD.
Member Data Documentation
_range
float FrostwingVrykulSearcher::_range private
Definition at line 313 of file icecrown_citadel.cpp.
Referenced by operator()().
_source
Creature const* FrostwingVrykulSearcher::_source private
Definition at line 312 of file icecrown_citadel.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp