Azerotcore-wotlk: Tokenizer Class Reference
Tokenizer Class Reference
#include <Util.h>
Public Types
typedef std::vector< char const * > StorageType
typedef StorageType::size_type size_type
typedef StorageType::const_iterator const_iterator
typedef StorageType::reference reference
typedef StorageType::const_reference const_reference
Public Member Functions
Tokenizer (const std::string &src, char const sep, uint32 vectorReserve=0)
~Tokenizer ()
const_iterator begin () const
const_iterator end () const
size_type size () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
Private Attributes
char * m_str
StorageType m_storage
Detailed Description
Definition at line 45 of file Util.h.
Member Typedef Documentation
const_iterator
typedef StorageType::const_iterator Tokenizer::const_iterator
Definition at line 52 of file Util.h.
const_reference
typedef StorageType::const_reference Tokenizer::const_reference
Definition at line 54 of file Util.h.
reference
typedef StorageType::reference Tokenizer::reference
Definition at line 53 of file Util.h.
size_type
typedef StorageType::size_type Tokenizer::size_type
Definition at line 50 of file Util.h.
StorageType
typedef std::vector<char const*> Tokenizer::StorageType
Definition at line 48 of file Util.h.
Constructor & Destructor Documentation
Tokenizer()
Tokenizer::Tokenizer (const std::string & src, char const sep, uint32 vectorReserve = 0)
Definition at line 33 of file Util.cpp.
 {
     m_str = new char[src.length() + 1];
     memcpy(m_str, src.c_str(), src.length() + 1);
     if (vectorReserve)
     {
         m_storage.reserve(vectorReserve);
     }
     char* posold = m_str;
     char* posnew = m_str;
     for (;;)
     {
         if (*posnew == sep)
         {
             m_storage.push_back(posold);
             posold = posnew + 1;
             *posnew = '\0';
         }
         else if (*posnew == '\0')
         {
             // Hack like, but the old code accepted these kind of broken strings,
             // so changing it would break other things
             if (posold != posnew)
             {
                 m_storage.push_back(posold);
             }
             break;
         }
         ++posnew;
     }
 }
References m_storage, m_str, and memcpy.
~Tokenizer()
Tokenizer::~Tokenizer () inline
Definition at line 58 of file Util.h.
 { delete[] m_str; }
References m_str.
Member Function Documentation
begin()
const_iterator Tokenizer::begin () const inline
Definition at line 60 of file Util.h.
 { return m_storage.begin(); }
References m_storage.
Referenced by Player::_LoadEntryPointData(), Player::_LoadItem(), misc_commandscript::HandleSkirmishCommand(), ChannelMgr::LoadChannelRights(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureTemplateAddons(), CharmInfo::LoadPetActionBar(), PlayerTaxi::LoadTaxiDestinationsFromString(), PlayerTaxi::LoadTaxiMask(), MoneyStringToMoney(), and Motd::SetMotd().
end()
const_iterator Tokenizer::end () const inline
Definition at line 61 of file Util.h.
 { return m_storage.end(); }
References m_storage.
Referenced by Player::_LoadEntryPointData(), Player::_LoadItem(), misc_commandscript::HandleSkirmishCommand(), ChannelMgr::LoadChannelRights(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureTemplateAddons(), PlayerTaxi::LoadTaxiDestinationsFromString(), PlayerTaxi::LoadTaxiMask(), MoneyStringToMoney(), and Motd::SetMotd().
operator[]() [1/2]
reference Tokenizer::operator[] (size_type i) inline
Definition at line 65 of file Util.h.
 { return m_storage[i]; }
References m_storage.
operator[]() [2/2]
const_reference Tokenizer::operator[] (size_type i) const inline
Definition at line 66 of file Util.h.
 { return m_storage[i]; }
References m_storage.
size()
size_type Tokenizer::size () const inline
Definition at line 63 of file Util.h.
 { return m_storage.size(); }
References m_storage.
Referenced by Object::_LoadIntoDataField(), misc_commandscript::HandleSkirmishCommand(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureTemplateAddons(), DisableMgr::LoadDisables(), Item::LoadFromDB(), CharmInfo::LoadPetActionBar(), Motd::SetMotd(), and Player::SetUInt32ValueInArray().
Member Data Documentation
m_storage
StorageType Tokenizer::m_storage private
Definition at line 70 of file Util.h.
Referenced by begin(), end(), operator[](), size(), and Tokenizer().
m_str
char* Tokenizer::m_str private
Definition at line 69 of file Util.h.
Referenced by Tokenizer(), and ~Tokenizer().
The documentation for this class was generated from the following files:
src/common/Utilities/Util.h
src/common/Utilities/Util.cpp