Azerotcore-wotlk: Acore::Net Namespace Reference
Acore::Net Namespace Reference
Functions
boost::asio::ip::address make_address (char const *str)
boost::asio::ip::address make_address (char const *str, boost::system::error_code &ec)
boost::asio::ip::address make_address (std::string const &str)
boost::asio::ip::address make_address (std::string const &str, boost::system::error_code &ec)
boost::asio::ip::address_v4 make_address_v4 (char const *str)
boost::asio::ip::address_v4 make_address_v4 (char const *str, boost::system::error_code &ec)
boost::asio::ip::address_v4 make_address_v4 (std::string const &str)
boost::asio::ip::address_v4 make_address_v4 (std::string const &str, boost::system::error_code &ec)
uint32 address_to_uint (boost::asio::ip::address_v4 const &address)
bool IsInNetwork (boost::asio::ip::address_v4 const &networkAddress, boost::asio::ip::address_v4 const &mask, boost::asio::ip::address_v4 const &clientAddress)
boost::asio::ip::address_v4 GetDefaultNetmaskV4 (boost::asio::ip::address_v4 const &networkAddress)
bool IsInNetwork (boost::asio::ip::address_v6 const &networkAddress, uint16 prefixLength, boost::asio::ip::address_v6 const &clientAddress)
Function Documentation
address_to_uint()
uint32 Acore::Net::address_to_uint (boost::asio::ip::address_v4 const & address) inline
Definition at line 39 of file IpAddress.h.
 { return address.to_ulong(); }
Referenced by GetDefaultNetmaskV4(), and IpLocationStore::GetLocationRecord().
GetDefaultNetmaskV4()
boost::asio::ip::address_v4 Acore::Net::GetDefaultNetmaskV4 (boost::asio::ip::address_v4 const & networkAddress) inline
Definition at line 43 of file IpNetwork.h.
     {
         if ((address_to_uint(networkAddress) & 0x80000000) == 0)
         {
             return boost::asio::ip::address_v4(0xFF000000);
         }
         if ((address_to_uint(networkAddress) & 0xC0000000) == 0x80000000)
         {
             return boost::asio::ip::address_v4(0xFFFF0000);
         }
         if ((address_to_uint(networkAddress) & 0xE0000000) == 0xC0000000)
         {
             return boost::asio::ip::address_v4(0xFFFFFF00);
         }
         return boost::asio::ip::address_v4(0xFFFFFFFF);
     }
References address_to_uint().
IsInNetwork() [1/2]
bool Acore::Net::IsInNetwork (boost::asio::ip::address_v4 const & networkAddress, boost::asio::ip::address_v4 const & mask, boost::asio::ip::address_v4 const & clientAddress) inline
Definition at line 32 of file IpNetwork.h.
     {
 #if BOOST_VERSION >= 106600
         boost::asio::ip::network_v4 network = boost::asio::ip::make_network_v4(networkAddress, mask);
         boost::asio::ip::address_v4_range hosts = network.hosts();
         return hosts.find(clientAddress) != hosts.end();
 #else
         return (clientAddress.to_ulong() & mask.to_ulong()) == (networkAddress.to_ulong() & mask.to_ulong());
 #endif
     }
Referenced by Realm::GetAddressForClient().
IsInNetwork() [2/2]
bool Acore::Net::IsInNetwork (boost::asio::ip::address_v6 const & networkAddress, uint16 prefixLength, boost::asio::ip::address_v6 const & clientAddress) inline
Definition at line 60 of file IpNetwork.h.
     {
 #if BOOST_VERSION >= 106600
         boost::asio::ip::network_v6 network = boost::asio::ip::make_network_v6(networkAddress, prefixLength);
         boost::asio::ip::address_v6_range hosts = network.hosts();
         return hosts.find(clientAddress) != hosts.end();
 #else
         (void)networkAddress;
         (void)prefixLength;
         (void)clientAddress;
         return false;
 #endif
     }
make_address() [1/4]
boost::asio::ip::address Acore::Net::make_address (char const * str) inline
Definition at line 31 of file IpAddress.h.
 { return boost::asio::ip::address::from_string(str); }
Referenced by IsIPAddress().
make_address() [2/4]
boost::asio::ip::address Acore::Net::make_address (char const * str, boost::system::error_code & ec) inline
Definition at line 32 of file IpAddress.h.
 { return boost::asio::ip::address::from_string(str, ec); }
make_address() [3/4]
boost::asio::ip::address Acore::Net::make_address (std::string const & str) inline
Definition at line 33 of file IpAddress.h.
 { return boost::asio::ip::address::from_string(str); }
make_address() [4/4]
boost::asio::ip::address Acore::Net::make_address (std::string const & str, boost::system::error_code & ec) inline
Definition at line 34 of file IpAddress.h.
 { return boost::asio::ip::address::from_string(str, ec); }
make_address_v4() [1/4]
boost::asio::ip::address_v4 Acore::Net::make_address_v4 (char const * str) inline
Definition at line 35 of file IpAddress.h.
 { return boost::asio::ip::address_v4::from_string(str); }
Referenced by IpLocationStore::GetLocationRecord().
make_address_v4() [2/4]
boost::asio::ip::address_v4 Acore::Net::make_address_v4 (char const * str, boost::system::error_code & ec) inline
Definition at line 36 of file IpAddress.h.
 { return boost::asio::ip::address_v4::from_string(str, ec); }
make_address_v4() [3/4]
boost::asio::ip::address_v4 Acore::Net::make_address_v4 (std::string const & str) inline
Definition at line 37 of file IpAddress.h.
 { return boost::asio::ip::address_v4::from_string(str); }
make_address_v4() [4/4]
boost::asio::ip::address_v4 Acore::Net::make_address_v4 (std::string const & str, boost::system::error_code & ec) inline
Definition at line 38 of file IpAddress.h.
 { return boost::asio::ip::address_v4::from_string(str, ec); }