Azerotcore-wotlk: npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI Struct Reference
npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI Struct Reference
Public Member Functions
npc_rocket_propelled_warheadAI (Creature *creature)
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void JustReachedHome () override
void DoAction (int32) override
void SpellHit (Unit *caster, SpellInfo const *) override
void FinishQuest (bool success, uint32 faction)
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 _faction
bool _finished
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 908 of file zone_grizzly_hills.cpp.
Constructor & Destructor Documentation
npc_rocket_propelled_warheadAI()
npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::npc_rocket_propelled_warheadAI (Creature * creature) inline
Definition at line 910 of file zone_grizzly_hills.cpp.
                                                            : VehicleAI(creature), _faction(ALLIANCE), _finished(false)
         {
         }
Member Function Documentation
DoAction()
void npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::DoAction (int32) inline override virtual
Reimplemented from UnitAI.
Definition at line 930 of file zone_grizzly_hills.cpp.
         {
             FinishQuest(false, _faction);
         }
References _faction, and FinishQuest().
FinishQuest()
void npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::FinishQuest (bool success, uint32 faction) inline
Definition at line 943 of file zone_grizzly_hills.cpp.
         {
             if (_finished)
             {
                 return;
             }
             _finished = true;
             if (success)
             {
                 DoCast(me, faction == ALLIANCE ? SPELL_ALLIANCE_KILL_CREDIT_TORPEDO : SPELL_HORDE_KILL_CREDIT_TORPEDO, true);
             }
             DoCast(me, SPELL_DETONATE, true);
             me->RemoveAllAuras();
             me->SetVisible(false);
             me->GetMotionMaster()->MoveTargetedHome();
         }
References _finished, ALLIANCE, UnitAI::DoCast(), Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MoveTargetedHome(), Unit::RemoveAllAuras(), Unit::SetVisible(), SPELL_ALLIANCE_KILL_CREDIT_TORPEDO, SPELL_DETONATE, and SPELL_HORDE_KILL_CREDIT_TORPEDO.
Referenced by DoAction(), and SpellHit().
JustReachedHome()
void npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 923 of file zone_grizzly_hills.cpp.
         {
             _finished = false;
             me->SetVisible(true);
             me->GetMotionMaster()->Clear(true);
         }
References _finished, MotionMaster::Clear(), Unit::GetMotionMaster(), CreatureAI::me, and Unit::SetVisible().
PassengerBoarded()
void npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 914 of file zone_grizzly_hills.cpp.
         {
             if (apply && who && who->ToPlayer())
             {
                 DoCast(me, SPELL_VEHICLE_WARHEAD_FUSE);
                 _faction = who->ToPlayer()->GetTeamId();
             }
         }
References _faction, ByteConverter::apply(), UnitAI::DoCast(), Player::GetTeamId(), CreatureAI::me, SPELL_VEHICLE_WARHEAD_FUSE, and Object::ToPlayer().
SpellHit()
void npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::SpellHit (Unit * caster, SpellInfo const *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 935 of file zone_grizzly_hills.cpp.
         {
             if (caster && (caster->GetEntry() == NPC_HORDE_LUMBERBOAT || caster->GetEntry() == NPC_ALLIANCE_LUMBERBOAT))
             {
                 FinishQuest(true, _faction);
             }
         }
References _faction, FinishQuest(), Object::GetEntry(), NPC_ALLIANCE_LUMBERBOAT, and NPC_HORDE_LUMBERBOAT.
Member Data Documentation
_faction
uint32 npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::_faction private
Definition at line 964 of file zone_grizzly_hills.cpp.
Referenced by DoAction(), PassengerBoarded(), and SpellHit().
_finished
bool npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::_finished private
Definition at line 965 of file zone_grizzly_hills.cpp.
Referenced by FinishQuest(), and JustReachedHome().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_grizzly_hills.cpp