Azerotcore-wotlk: CreatureAI Class Reference
CreatureAI Class Reference
#include <CreatureAI.h>
Public Member Functions
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Member Functions
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Private Attributes
bool m_MoveInLineOfSight_locked
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Definition at line 65 of file CreatureAI.h.
Constructor & Destructor Documentation
CreatureAI()
CreatureAI::CreatureAI (Creature * creature) inline explicit
Definition at line 81 of file CreatureAI.h.
 : UnitAI(creature), me(creature), m_MoveInLineOfSight_locked(false) {}
~CreatureAI()
CreatureAI::~CreatureAI () inline override
Definition at line 83 of file CreatureAI.h.
 {}
Member Function Documentation
_EnterEvadeMode()
bool CreatureAI::_EnterEvadeMode () protected
Definition at line 293 of file CreatureAI.cpp.
 {
     if (!me->IsAlive())
     {
         return false;
     }
     // don't remove vehicle auras, passengers aren't supposed to drop off the vehicle
     // don't remove clone caster on evade (to be verified)
     me->RemoveEvadeAuras();
     me->ClearComboPointHolders(); // Remove all combo points targeting this unit
     // sometimes bosses stuck in combat?
     me->DeleteThreatList();
     me->CombatStop(true);
     me->LoadCreaturesAddon(true);
     me->SetLootRecipient(nullptr);
     me->ResetPlayerDamageReq();
     me->SetLastDamagedTime(0);
     me->SetCannotReachTarget(false);
     if (CreatureGroup* formation = me->GetFormation())
     {
         formation->MemberEvaded(me);
     }
     if (me->IsInEvadeMode())
     {
         return false;
     }
     return true;
 }
References Unit::ClearComboPointHolders(), Unit::CombatStop(), Unit::DeleteThreatList(), Creature::GetFormation(), Unit::IsAlive(), Creature::IsInEvadeMode(), Creature::LoadCreaturesAddon(), me, Unit::RemoveEvadeAuras(), Creature::ResetPlayerDamageReq(), Creature::SetCannotReachTarget(), Creature::SetLastDamagedTime(), and Creature::SetLootRecipient().
Referenced by boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), EnterEvadeMode(), SmartAI::EnterEvadeMode(), npc_shay_leafrunner::npc_shay_leafrunnerAI::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), npc_argent_captainAI::EnterEvadeMode(), boss_kologarn::boss_kologarnAI::EnterEvadeMode(), npc_ulduar_vx001::npc_ulduar_vx001AI::EnterEvadeMode(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::EnterEvadeMode(), npc_training_dummy::npc_training_dummyAI::EnterEvadeMode(), npc_target_dummy::npc_target_dummyAI::EnterEvadeMode(), and boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI().
AttackedBy()
virtual void CreatureAI::AttackedBy (Unit *) inline virtual
Reimplemented in npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_calvin_montague::npc_calvin_montagueAI, npc_bartleby::npc_bartlebyAI, PetAI, and NPCStaveQuestAI.
Definition at line 126 of file CreatureAI.h.
 {}
Referenced by Unit::CombatStart(), and Unit::DealDamage().
CanBeSeen()
virtual bool CreatureAI::CanBeSeen (Player const *) inline virtual
Reimplemented in npc_midsummer_torch_target::npc_midsummer_torch_targetAI, npc_greatfather_aldrimus::npc_greatfather_aldrimusAI, boss_ahune::boss_ahuneAI, npc_mei_francis_mount::npc_mei_francis_mountAI, npc_steam_powered_auctioneer::npc_steam_powered_auctioneerAI, npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, npc_eris_hevenfire::npc_eris_hevenfireAI, and npc_brewfest_keg_thrower::npc_brewfest_keg_throwerAI.
Definition at line 178 of file CreatureAI.h.
 { return true; }
CanRespawn()
virtual bool CreatureAI::CanRespawn () inline virtual
Definition at line 97 of file CreatureAI.h.
 { return true; }
Referenced by Creature::Update().
CanSeeAlways()
virtual bool CreatureAI::CanSeeAlways (WorldObject const *) inline virtual
Definition at line 176 of file CreatureAI.h.
 { return false; }
CorpseRemoved()
virtual void CreatureAI::CorpseRemoved (uint32 &) inline virtual
== Triggered Actions Requested ==================
== State checks =================================
Reimplemented in SmartAI, npc_simone::npc_simoneAI, and npc_captain_saeed::npc_captain_saeedAI.
Definition at line 166 of file CreatureAI.h.
 {}
Referenced by Creature::RemoveCorpse().
DoSummon() [1/2]
Creature * CreatureAI::DoSummon (uint32 entry, Position const & pos, uint32 despawnTime = 30000, TempSummonType summonType = TEMPSUMMON_CORPSE_TIMED_DESPAWN) protected
Definition at line 361 of file CreatureAI.cpp.
 {
     return me->SummonCreature(entry, pos, summonType, despawnTime);
 }
References me, and WorldObject::SummonCreature().
Referenced by npc_earthmender_wilda::npc_earthmender_wildaAI::DoSpawnAssassin(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), and boss_ichoron::boss_ichoronAI::UpdateAI().
DoSummon() [2/2]
Creature * CreatureAI::DoSummon (uint32 entry, WorldObject * obj, float radius = 5.0f, uint32 despawnTime = 30000, TempSummonType summonType = TEMPSUMMON_CORPSE_TIMED_DESPAWN) protected
Definition at line 366 of file CreatureAI.cpp.
 {
     Position pos = obj->GetRandomNearPosition(radius);
     return me->SummonCreature(entry, pos, summonType, despawnTime);
 }
References WorldObject::GetRandomNearPosition(), me, and WorldObject::SummonCreature().
DoSummonFlyer()
Creature * CreatureAI::DoSummonFlyer (uint32 entry, WorldObject * obj, float flightZ, float radius = 5.0f, uint32 despawnTime = 30000, TempSummonType summonType = TEMPSUMMON_CORPSE_TIMED_DESPAWN) protected
Definition at line 372 of file CreatureAI.cpp.
 {
     Position pos = obj->GetRandomNearPosition(radius);
     pos.m_positionZ += flightZ;
     return me->SummonCreature(entry, pos, summonType, despawnTime);
 }
References WorldObject::GetRandomNearPosition(), Position::m_positionZ, me, and WorldObject::SummonCreature().
Referenced by boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI().
DoZoneInCombat()
void CreatureAI::DoZoneInCombat (Creature * creature = nullptr, float maxRangeToNearestTarget = 250.0f)
Definition at line 90 of file CreatureAI.cpp.
 {
     if (!creature)
     {
         creature = me;
     }
     if (creature->IsInEvadeMode())
     {
         return;
     }
     Map* map = creature->GetMap();
     if (!map->IsDungeon())                                  //use IsDungeon instead of Instanceable, in case battlegrounds will be instantiated
     {
         LOG_ERROR("entities.unit.ai", "DoZoneInCombat call for map that isn't an instance (creature entry = %d)", creature->GetTypeId() == TYPEID_UNIT ? creature->ToCreature()->GetEntry() : 0);
         return;
     }
     Map::PlayerList const& playerList = map->GetPlayers();
     if (playerList.isEmpty())
     {
         return;
     }
     for (Map::PlayerList::const_iterator itr = playerList.begin(); itr != playerList.end(); ++itr)
     {
         if (Player* player = itr->GetSource())
         {
             if (!IsValidCombatTarget(creature, player))
             {
                 continue;
             }
             if (!creature->IsWithinDistInMap(player, maxRangeToNearestTarget))
             {
                 continue;
             }
             creature->SetInCombatWith(player);
             player->SetInCombatWith(creature);
             if (creature->CanHaveThreatList())
             {
                 creature->AddThreat(player, 0.0f);
             }
             /* Causes certain things to never leave the threat list (Priest Lightwell, etc):
             for (Unit::ControlSet::const_iterator itr = player->m_Controlled.begin(); itr != player->m_Controlled.end(); ++itr)
             {
                 creature->SetInCombatWith(*itr);
                 (*itr)->SetInCombatWith(creature);
                 creature->AddThreat(*itr, 0.0f);
             }*/
         }
     }
 }
References Unit::AddThreat(), MapRefMgr::begin(), Unit::CanHaveThreatList(), MapRefMgr::end(), Object::GetEntry(), WorldObject::GetMap(), Map::GetPlayers(), Object::GetTypeId(), Map::IsDungeon(), LinkedListHead::isEmpty(), Creature::IsInEvadeMode(), IsValidCombatTarget(), WorldObject::IsWithinDistInMap(), LOG_ERROR, me, Unit::SetInCombatWith(), Object::ToCreature(), and TYPEID_UNIT.
Referenced by BossAI::_EnterCombat(), npc_coren_direbrew::npc_coren_direbrewAI::DoAction(), npc_direbrew_antagonist::npc_direbrew_antagonistAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), SummonList::DoZoneInCombat(), boss_sartharion_dragonAI::EnterCombat(), boss_netherspite::boss_netherspiteAI::EnterCombat(), boss_malchezaar::boss_malchezaarAI::EnterCombat(), prince_axes::prince_axesAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), boss_terestian_illhoof::boss_terestianAI::EnterCombat(), boss_dorothee::boss_dorotheeAI::EnterCombat(), npc_tito::npc_titoAI::EnterCombat(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::EnterCombat(), npc_akilzon_eagle::npc_akilzon_eagleAI::EnterCombat(), boss_hexlord_addAI::EnterCombat(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), boss_nalorakk::boss_nalorakkAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterCombat(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_venoxis::boss_venoxisAI::EnterCombat(), boss_archimonde::boss_archimondeAI::EnterCombat(), boss_onyxia::boss_onyxiaAI::EnterCombat(), boss_eye_of_cthun::eye_of_cthunAI::EnterCombat(), boss_cthun::cthunAI::EnterCombat(), npc_eye_tentacle::eye_tentacleAI::EnterCombat(), npc_claw_tentacle::claw_tentacleAI::EnterCombat(), npc_giant_claw_tentacle::giant_claw_tentacleAI::EnterCombat(), npc_giant_eye_tentacle::giant_eye_tentacleAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), npc_swarm_scarab::npc_swarm_scarabAI::EnterCombat(), boss_jaraxxus::boss_jaraxxusAI::EnterCombat(), boss_twin_valkyrAI::EnterCombat(), boss_bronjahm::boss_bronjahmAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_garfrost::boss_garfrostAI::EnterCombat(), boss_ick::boss_ickAI::EnterCombat(), npc_cult_fanatic::npc_cult_fanaticAI::EnterCombat(), npc_cult_adherent::npc_cult_adherentAI::EnterCombat(), npc_darnavan::npc_darnavanAI::EnterCombat(), boss_lord_marrowgar::EnterCombat(), npc_argent_captainAI::EnterCombat(), boss_malygos::boss_malygosAI::EnterCombat(), npc_nexus_lord::npc_nexus_lordAI::EnterCombat(), boss_ignis::boss_ignisAI::EnterCombat(), boss_mimiron::boss_mimironAI::EnterCombat(), boss_keleseth::boss_kelesethAI::EnterCombat(), boss_cyanigosa::boss_cyanigosaAI::EnterCombat(), boss_ichoron::boss_ichoronAI::EnterCombat(), boss_lavanthor::boss_lavanthorAI::EnterCombat(), boss_moragg::boss_moraggAI::EnterCombat(), boss_xevozz::boss_xevozzAI::EnterCombat(), boss_zuramat::boss_zuramatAI::EnterCombat(), boss_ahune::boss_ahuneAI::EnterCombat(), boss_curator::boss_curatorAI::EnterCombat(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::EnterCombat(), boss_midnight::boss_midnightAI::EnterCombat(), boss_moroes::boss_moroesAI::EnterCombat(), boss_twinemperorsAI::EnterCombat(), npc_anubisath_sentinel::aqsentinelAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), npc_erekem_guard::npc_erekem_guardAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), StartMovementEvent::Execute(), npc_rookery_hatcher::npc_rookery_hatcherAI::InitializeAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::InitializeAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_eregos::boss_eregosAI::JustSummoned(), boss_onyxia::boss_onyxiaAI::JustSummoned(), BossAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), npc_fiendish_portal::npc_fiendish_portalAI::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_nefarian::boss_nefarianAI::MovementInform(), boss_grand_champion::boss_grand_championAI::MovementInform(), boss_sister_svalna::boss_sister_svalnaAI::MovementInform(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_direbrew_minion::npc_direbrew_minionAI::Reset(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), npc_nerubian_burrower::npc_nerubian_burrowerAI::Reset(), npc_fel_infernal::npc_fel_infernalAI::Reset(), npc_mistress_of_pain::npc_mistress_of_painAI::Reset(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SetData(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SetData(), Creature::SetInCombatWithZone(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), boss_heigan::boss_heiganAI::StartFightPhase(), npc_coren_direbrew::npc_coren_direbrewAI::SummonSister(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), and InstanceScript::UpdateMinionState().
EnterCombat()
virtual void CreatureAI::EnterCombat (Unit *) inline virtual
Reimplemented in generic_creature::generic_creatureAI, boss_taerar::boss_taerarAI, boss_emeriss::boss_emerissAI, boss_lethon::boss_lethonAI, boss_ysondre::boss_ysondreAI, npc_ishanah::ishanahAI, npc_earthmender_wilda::npc_earthmender_wildaAI, npc_phase_hunter::npc_phase_hunterAI, npc_captain_saeed::npc_captain_saeedAI, anchorite_karja::anchorite_karjaAI, boss_void_reaver::boss_void_reaverAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_alar::boss_alarAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_veras_darkshadow::boss_veras_darkshadowAI, boss_lady_malande::boss_lady_malandeAI, boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI, boss_gathios_the_shatterer::boss_gathios_the_shattererAI, boss_najentus::boss_najentusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_supremus::boss_supremusAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_mother_shahraz::boss_shahrazAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, npc_mrfloppy::npc_mrfloppyAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, violet_hold_trashAI, npc_erekem_guard::npc_erekem_guardAI, boss_erekem::boss_erekemAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_keristrasza::boss_keristraszaAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_anomalus::boss_anomalusAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_razuvious::boss_razuviousAI, boss_patchwerk::boss_patchwerkAI, boss_noth::boss_nothAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad::boss_kelthuzadAI, boss_heigan::boss_heiganAI, boss_grobbulus::boss_grobbulusAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, boss_four_horsemen::boss_four_horsemenAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, npc_sindragosa_trash::npc_sindragosa_trashAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_slad_ran::boss_slad_ranAI, boss_moorabi::boss_moorabiAI, boss_gal_darah::boss_gal_darahAI, boss_eck::boss_eckAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_trollgore::boss_trollgoreAI, boss_tharon_ja::boss_tharon_jaAI, boss_novos::boss_novosAI, boss_dred::boss_dredAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_halion::boss_halionAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_krik_thir::boss_krik_thirAI, npc_gilthares::npc_giltharesAI, npc_aquementas::npc_aquementasAI, npc_prospector_remtravel::npc_prospector_remtravelAI, npc_magwin::npc_magwinAI, npc_anubisath_sentinel::aqsentinelAI, boss_twinemperorsAI, boss_buru::boss_buruAI, npc_belnistrasz::npc_belnistraszAI, npc_direbrew_antagonist::npc_direbrew_antagonistAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_deathstalker_erland::npc_deathstalker_erlandAI, npc_rinji::npc_rinjiAI, boss_muru::boss_muruAI, boss_kalecgos::boss_kalecgosAI, boss_felmyst::boss_felmystAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, boss_brutallus::boss_brutallusAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, boss_zelfan::boss_zelfanAI, boss_apoko::boss_apokoAI, boss_garaxxas::boss_garaxxasAI, boss_warlord_salaris::boss_warlord_salarisAI, boss_yazzai::boss_yazzaiAI, boss_eramas_brightblaze::boss_eramas_brightblazeAI, boss_ellris_duskhallow::boss_ellris_duskhallowAI, boss_kagani_nightstrike::boss_kagani_nightstrikeAI, boss_priestess_lackey_commonAI, boss_moroes::boss_moroesAI, boss_midnight::boss_midnightAI, boss_maiden_of_virtue::boss_maiden_of_virtueAI, boss_curator::boss_curatorAI, boss_firemaw::boss_firemawAI, boss_ebonroc::boss_ebonrocAI, boss_broodlord::boss_broodlordAI, boss_quartermaster_zigris, CombatAI, npc_franklin::npc_franklinAI, npc_nelson::npc_nelsonAI, npc_simone::npc_simoneAI, npc_artorius::npc_artoriusAI, boss_sindragosa::boss_sindragosaAI, boss_vaelastrasz::boss_vaelAI, boss_flamegor::boss_flamegorAI, boss_chromaggus::boss_chromaggusAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_the_lich_king::boss_the_lich_kingAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_sartharion::boss_sartharionAI, SmartAI, npc_buru_egg::npc_buru_eggAI, boss_ayamiss::boss_ayamissAI, npc_spring_rabbit::npc_spring_rabbitAI, npc_steam_tonk::npc_steam_tonkAI, npc_guardian::npc_guardianAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_injured_patient::npc_injured_patientAI, npc_doctor::npc_doctorAI, npc_dancing_flames::npc_dancing_flamesAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_precious::npc_preciousAI, npc_pet_shaman_fire_elemental, npc_pet_shaman_earth_elemental, npc_pet_gen_mojo, npc_cooshcoosh::npc_cooshcooshAI, npc_natrualist_bite::npc_natrualist_biteAI, npc_isla_starmane::npc_isla_starmaneAI, npc_floon::npc_floonAI, npc_rotting_forest_rager::npc_rotting_forest_ragerAI, npc_infested_root_walker::npc_infested_root_walkerAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_enraged_spirit::npc_enraged_spiritAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, kaylaan_the_lost::kaylaan_the_lostAI, socrethar::socretharAI, exarch_orelis::exarch_orelisAI, adyen_the_lightbringer::adyen_the_lightbringerAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI, npc_maghar_captive::npc_maghar_captiveAI, npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_daranelle::npc_daranelleAI, npc_nether_drake::npc_nether_drakeAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, npc_ragin_flames::npc_ragin_flamesAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_warp_splinter::boss_warp_splinterAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_laj::boss_lajAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_magtheridon::boss_magtheridonAI, boss_vazruden::boss_vazrudenAI, boss_nazan::boss_nazanAI, boss_the_maker::boss_the_makerAI, npc_shadowmoon_channeler::npc_shadowmoon_channelerAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, boss_broggok::boss_broggokAI, boss_krosh_firehand::boss_krosh_firehandAI, boss_blindeye_the_seer::boss_blindeye_the_seerAI, boss_kiggler_the_crazed::boss_kiggler_the_crazedAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_gruul::boss_gruulAI, boss_the_black_stalker::boss_the_black_stalkerAI, boss_warlord_kalithresh::boss_warlord_kalithreshAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, boss_hydromancer_thespia::boss_thespiaAI, boss_ahune::boss_ahuneAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_doomwalker::boss_doomwalkerAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_illidari_council_memberAI, npc_akama_shade::npc_akamaAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_murmur::boss_murmurAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_anzu::boss_anzuAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_pandemonius::boss_pandemoniusAI, npc_yor::npc_yorAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, boss_exarch_maladaar::boss_exarch_maladaarAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_icefang::npc_icefangAI, npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI, npc_frosthound::npc_frosthoundAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_blessed_banner::npc_blessed_bannerAI, npc_emily::npc_emilyAI, npc_dalaran_warrior::npc_dalaran_warriorAI, npc_dalaran_mage::npc_dalaran_mageAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_counselor_talbot::npc_counselor_talbotAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, boss_ichoron::boss_ichoronAI, boss_cyanigosa::boss_cyanigosaAI, npc_frozen_orb::npc_frozen_orbAI, boss_toravon::boss_toravonAI, boss_koralon::boss_koralonAI, boss_emalon::boss_emalonAI, boss_archavon::boss_archavonAI, boss_ymiron::boss_ymironAI, boss_svala::boss_svalaAI, boss_skadi_grauf::boss_skadi_graufAI, boss_skadi::boss_skadiAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI, boss_keleseth::boss_kelesethAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, boss_xt002::boss_xt002AI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim::boss_thorimAI, boss_razorscale::boss_razorscaleAI, boss_mimiron::boss_mimironAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_freya::boss_freyaAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI, boss_auriaya::boss_auriayaAI, boss_algalon_the_observer::boss_algalon_the_observerAI, iron_golem_custodian::iron_golem_custodianAI, dark_rune_stormcaller::dark_rune_stormcallerAI, dark_rune_protectors::dark_rune_protectorsAI, boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, boss_sjonnir::boss_sjonnirAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_krystallus::boss_krystallusAI, npc_hol_monument::npc_hol_monumentAI, boss_volkhan::boss_volkhanAI, boss_loken::boss_lokenAI, boss_ionar::boss_ionarAI, npc_stormforged_lieutenant::npc_stormforged_lieutenantAI, boss_bjarngrim::boss_bjarngrimAI, npc_centrifuge_construct::npc_centrifuge_constructAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, boss_drakos::boss_drakosAI, npc_crystalline_frayer::npc_crystalline_frayerAI, npc_nexus_lord::npc_nexus_lordAI, boss_malygos::boss_malygosAI, npc_tesla::npc_teslaAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_isle_of_conquest::boss_isle_of_conquestAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_argent_captainAI, boss_sister_svalna::boss_sister_svalnaAI, npc_risen_archmage::npc_risen_archmageAI, npc_rimefang::npc_rimefangAI, npc_precious_icc::npc_precious_iccAI, boss_lord_marrowgar, npc_darnavan::npc_darnavanAI, npc_cult_adherent::npc_cult_adherentAI, npc_cult_fanatic::npc_cult_fanaticAI, npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_stinky_icc::npc_stinky_iccAI, boss_drakkari_elemental::boss_drakkari_elementalAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_ick::boss_ickAI, boss_garfrost::boss_garfrostAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_bronjahm::boss_bronjahmAI, boss_twin_valkyrAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_jaraxxus::boss_jaraxxusAI, boss_faction_championsAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_grand_champion::boss_grand_championAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, npc_argent_soldier::npc_argent_soldierAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_twilight_halion::boss_twilight_halionAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_hadronox::boss_hadronoxAI, boss_anub_arak::boss_anub_arakAI, boss_taldaram::boss_taldaramAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_volazj::boss_volazjAI, boss_elder_nadox::boss_elder_nadoxAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, boss_amanitar::boss_amanitarAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_thrall_warchief::npc_thrall_warchiefAI, npc_shenthul::npc_shenthulAI, npc_omen::npc_omenAI, npc_tiger_matriarch::npc_tiger_matriarchAI, npc_murkdeep::npc_murkdeepAI, npc_webbed_creature::npc_webbed_creatureAI, npc_injured_draenei::npc_injured_draeneiAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_depth_charge::npc_depth_chargeAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_spitelashes::npc_spitelashesAI, npc_muglash::npc_muglashAI, boss_viscidus::boss_viscidusAI, boss_skeram::boss_skeramAI, npc_sartura_royal_guard::npc_sartura_royal_guardAI, boss_sartura::boss_sarturaAI, boss_ouro::boss_ouroAI, boss_huhuran::boss_huhuranAI, boss_fankriss::boss_fankrissAI, npc_giant_eye_tentacle::giant_eye_tentacleAI, npc_giant_claw_tentacle::giant_claw_tentacleAI, npc_claw_tentacle::claw_tentacleAI, npc_eye_tentacle::eye_tentacleAI, boss_cthun::cthunAI, boss_eye_of_cthun::eye_of_cthunAI, boss_yauj::boss_yaujAI, boss_vem::boss_vemAI, boss_kri::boss_kriAI, boss_rajaxx::boss_rajaxxAI, boss_ossirian::boss_ossirianAI, boss_onyxia::boss_onyxiaAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_epoch_hunter::boss_epoch_hunterAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_arthas::npc_arthasAI, boss_salramm::boss_salrammAI, boss_meathook::boss_meathookAI, boss_mal_ganis::boss_mal_ganisAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_epoch::boss_epochAI, hyjalAI, alliance_rifleman::alliance_riflemanAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_fel_stalker::npc_fel_stalkerAI, npc_crypt_fiend::npc_crypt_fiendAI, npc_banshee::npc_bansheeAI, npc_necromancer::npc_necromancerAI, npc_ghoul::npc_ghoulAI, npc_abomination::npc_abominationAI, npc_giant_infernal::npc_giant_infernalAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_azgalor::boss_azgalorAI, boss_archimonde::boss_archimondeAI, npc_doomfire_targetting::npc_doomfire_targettingAI, npc_doomfire::npc_doomfireAI, npc_ancient_wisp::npc_ancient_wispAI, npc_towering_infernal::npc_towering_infernalAI, boss_anetheron::boss_anetheronAI, boss_azuregos::boss_azuregosAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI, npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI, npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI, boss_wushoolay::boss_wushoolayAI, boss_venoxis::boss_venoxisAI, npc_zealot_zath::npc_zealot_zathAI, npc_zealot_lorkhan::npc_zealot_lorkhanAI, boss_thekal::boss_thekalAI, boss_renataki::boss_renatakiAI, npc_spawn_of_marli::npc_spawn_of_marliAI, boss_marli::boss_marliAI, npc_vilebranch_speaker::npc_vilebranch_speakerAI, npc_ohgan::npc_ohganAI, boss_mandokir::boss_mandokirAI, npc_shade_of_jindo::npc_shade_of_jindoAI, npc_healing_ward::npc_healing_wardAI, boss_jindo::boss_jindoAI, npc_batrider::npc_batriderAI, boss_jeklik::boss_jeklikAI, boss_hazzarah::boss_hazzarahAI, boss_hakkar::boss_hakkarAI, boss_grilek::boss_grilekAI, boss_gahzranka::boss_gahzrankaAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_arlokk::boss_arlokkAI, npc_harrison_jones::npc_harrison_jonesAI, npc_zulaman_hostage::npc_zulaman_hostageAI, npc_forest_frog::npc_forest_frogAI, npc_zuljin_vortex::npc_zuljin_vortexAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, npc_janalai_hatchling::npc_janalai_hatchlingAI, npc_janalai_hatcher::npc_janalai_hatcherAI, npc_janalai_firebomb::npc_janalai_firebombAI, boss_janalai::boss_janalaiAI, boss_hexlord_malacrass::boss_hex_lord_malacrassAI, boss_hexlord_addAI, npc_halazzi_lynx::npc_halazzi_lynxAI, boss_halazzi::boss_halazziAI, npc_akilzon_eagle::npc_akilzon_eagleAI, boss_akilzon::boss_akilzonAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_the_scourge_cauldron::npc_the_scourge_cauldronAI, npc_highborne_lamenter::npc_highborne_lamenterAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, npc_calvin_montague::npc_calvin_montagueAI, npc_yenniku::npc_yennikuAI, pyrewood_ambush::pyrewood_ambushAI, npc_greengill_slave::npc_greengill_slaveAI, boss_twilight_corrupter::boss_twilight_corrupterAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, boss_entropius::boss_entropiusAI, boss_kiljaeden::boss_kiljaedenAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalec::boss_kalecAI, boss_baroness_anastari::boss_baroness_anastariAI, npc_scholomance_occultist::npc_scholomance_occultistAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_mograine::npc_mograineAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_unworthy_initiate::npc_unworthy_initiateAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, npc_image_of_medivh::npc_image_of_medivhAI, npc_barnes::npc_barnesAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, npc_cyclone::npc_cycloneAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, npc_tito::npc_titoAI, boss_dorothee::boss_dorotheeAI, boss_terestian_illhoof::boss_terestianAI, npc_fiendish_imp::npc_fiendish_impAI, npc_demon_chain::npc_demon_chainAI, npc_kilrek::npc_kilrekAI, npc_aran_elemental::water_elementalAI, boss_shade_of_aran::boss_aranAI, boss_servant_quarters::boss_servant_quartersAI, prince_axes::prince_axesAI, boss_malchezaar::boss_malchezaarAI, netherspite_infernal::netherspite_infernalAI, boss_nightbane::boss_nightbaneAI, boss_netherspite::boss_netherspiteAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, boss_mr_smite::boss_mr_smiteAI, npc_flamewaker_priest::npc_flamewaker_priestAI, boss_sulfuron::boss_sulfuronAI, boss_shazzrah::boss_shazzrahAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, boss_magmadar::boss_magmadarAI, boss_lucifron::boss_lucifronAI, boss_gehennas::boss_gehennasAI, boss_garr::boss_garrAI, boss_baron_geddon::boss_baron_geddonAI, boss_nefarian::boss_nefarianAI, boss_warmaster_voone::boss_warmastervooneAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_the_beast::boss_thebeastAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, npc_rookery_hatcher::npc_rookery_hatcherAI, boss_rend_blackhand::boss_rend_blackhandAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_highlord_omokk::boss_highlordomokkAI, boss_halycon::boss_halyconAI, boss_gyth::boss_gythAI, chromatic_elite_guard::chromatic_elite_guardAI, boss_drakkisath::boss_drakkisathAI, boss_doomrel::boss_doomrelAI, boss_moira_bronzebeard::boss_moira_bronzebeardAI, boss_magmus::boss_magmusAI, boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI, boss_grizzle::boss_grizzleAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_general_angerforge::boss_general_angerforgeAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_anubshiah::boss_anubshiahAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_vanndar::boss_vanndarAI, boss_galvangar::boss_galvangarAI, boss_drekthar::boss_drektharAI, boss_balinda::boss_balindaAI, WorldBossAI, BossAI, ScriptedAI, CasterAI, boss_sartharion_dragonAI, and npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI.
Definition at line 103 of file CreatureAI.h.
 {}
Referenced by socrethar::socretharAI::UpdateAI().
EnterEvadeMode()
void CreatureAI::EnterEvadeMode () virtual
Reimplemented in npc_target_dummy::npc_target_dummyAI, npc_training_dummy::npc_training_dummyAI, npc_pet_mage_mirror_image, npc_pet_hunter_snake_trap, npc_pet_gen_toxic_wasteling, npc_pet_gen_argent_pony_bridle, npc_captain_saeed::npc_captain_saeedAI, boss_vazruden::boss_vazrudenAI, boss_nazan::boss_nazanAI, boss_ahune::boss_ahuneAI, npc_inner_demon::npc_inner_demonAI, boss_illidari_council_memberAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_icefang::npc_icefangAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_frosthound::npc_frosthoundAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_mrfloppy::npc_mrfloppyAI, npc_future_you::npc_future_youAI, violet_hold_trashAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, boss_ichoron::boss_ichoronAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, boss_ymiron::boss_ymironAI, boss_svala::boss_svalaAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim::boss_thorimAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_mimiron::boss_mimironAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, npc_crystalline_frayer::npc_crystalline_frayerAI, boss_malygos::boss_malygosAI, npc_tesla::npc_teslaAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_noth::boss_nothAI, boss_kelthuzad::boss_kelthuzadAI, npc_argent_captainAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, boss_sindragosa::boss_sindragosaAI, npc_big_ooze::npc_big_oozeAI, npc_little_ooze::npc_little_oozeAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_gunship_boarding_addAI, gunship_npc_AI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, npc_pos_freed_slave::npc_pos_freed_slaveAI, boss_garfrost::boss_garfrostAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_hallucination::npc_phantom_hallucinationAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_bronjahm::boss_bronjahmAI, boss_twin_valkyrAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, boss_gormok::boss_gormokAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_fel_infernal::npc_fel_infernalAI, boss_jaraxxus::boss_jaraxxusAI, npc_toc_pet_hunter::npc_toc_pet_hunterAI, npc_toc_pet_warlock::npc_toc_pet_warlockAI, boss_faction_championsAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_grand_champion::boss_grand_championAI, boss_black_knight::boss_black_knightAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, boss_anub_arak::boss_anub_arakAI, npc_twilight_volunteer::npc_twilight_volunteerAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, boss_amanitar::boss_amanitarAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_cork_gizelton::npc_cork_gizeltonAI, boss_viscidus::boss_viscidusAI, boss_skeram::boss_skeramAI, boss_ossirian::boss_ossirianAI, boss_buru::boss_buruAI, boss_ayamiss::boss_ayamissAI, hyjalAI, npc_hallows_end_soh::npc_hallows_end_sohAI, boss_arlokk::boss_arlokkAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, boss_entropius::boss_entropiusAI, boss_kiljaeden::boss_kiljaedenAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, boss_priestess_lackey_commonAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_gyth::boss_gythAI, boss_doomrel::boss_doomrelAI, npc_burning_spirit::npc_burning_spiritAI, SmartAI, FollowerAI, npc_escortAI, TotemAI, PetAI, CritterAI, NullCreatureAI, PossessedAI, and GuardAI.
Definition at line 197 of file CreatureAI.cpp.
 {
     if (!_EnterEvadeMode())
         return;
     LOG_DEBUG("entities.unit", "Creature %u enters evade mode.", me->GetEntry());
     if (!me->GetVehicle()) // otherwise me will be in evade mode forever
     {
         if (Unit* owner = me->GetCharmerOrOwner())
         {
             me->GetMotionMaster()->Clear(false);
             me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, me->GetFollowAngle(), MOTION_SLOT_ACTIVE);
         }
         else
         {
             // Required to prevent attacking creatures that are evading and cause them to reenter combat
             // Does not apply to MoveFollow
             me->AddUnitState(UNIT_STATE_EVADE);
             me->GetMotionMaster()->MoveTargetedHome();
         }
     }
     // despawn bosses at reset - only verified tbc/woltk bosses with this reset type - add bosses in last line respectively (dungeon/raid) and increase array limit
     CreatureTemplate const* cInfo = sObjectMgr->GetCreatureTemplate(me->GetEntry());
     if (cInfo && cInfo->HasFlagsExtra(CREATURE_FLAG_EXTRA_HARD_RESET))
     {
         me->DespawnOnEvade();
         me->m_Events.AddEvent(new PhasedRespawn(*me), me->m_Events.CalculateTime(20000));
     }
     else // bosses will run back to the spawnpoint at reset
     {
         Reset();
         if (me->IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
         {
             me->GetVehicleKit()->Reset(true);
         }
     }
 }
References _EnterEvadeMode(), EventProcessor::AddEvent(), Unit::AddUnitState(), EventProcessor::CalculateTime(), MotionMaster::Clear(), CREATURE_FLAG_EXTRA_HARD_RESET, Creature::DespawnOnEvade(), Unit::GetCharmerOrOwner(), Object::GetEntry(), Unit::GetFollowAngle(), Unit::GetMotionMaster(), Unit::GetVehicle(), Unit::GetVehicleKit(), CreatureTemplate::HasFlagsExtra(), Unit::IsVehicle(), LOG_DEBUG, Unit::m_Events, me, MOTION_SLOT_ACTIVE, MotionMaster::MoveFollow(), MotionMaster::MoveTargetedHome(), PET_FOLLOW_DIST, UnitAI::Reset(), Vehicle::Reset(), sObjectMgr, and UNIT_STATE_EVADE.
Referenced by BossAI::_EnterCombat(), boss_chromaggus::boss_chromaggusAI::boss_chromaggusAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::CheckChannelers(), BossAI::CheckInRoom(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons(), npc_simone::npc_simoneAI::CorpseRemoved(), npc_salsalabim::npc_salsalabimAI::DamageTaken(), npc_bartleby::npc_bartlebyAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), npc_eris_hevenfire::npc_eris_hevenfireAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), ScriptedAI::EnterEvadeIfOutOfCombatArea(), CritterAI::EnterEvadeMode(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_priestess_lackey_commonAI::EnterEvadeMode(), boss_sacrolash::boss_sacrolashAI::EnterEvadeMode(), boss_alythess::boss_alythessAI::EnterEvadeMode(), boss_kiljaeden::boss_kiljaedenAI::EnterEvadeMode(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::EnterEvadeMode(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), boss_ayamiss::boss_ayamissAI::EnterEvadeMode(), boss_buru::boss_buruAI::EnterEvadeMode(), boss_ossirian::boss_ossirianAI::EnterEvadeMode(), boss_skeram::boss_skeramAI::EnterEvadeMode(), boss_viscidus::boss_viscidusAI::EnterEvadeMode(), npc_twiggy_flathead::npc_twiggy_flatheadAI::EnterEvadeMode(), boss_amanitar::boss_amanitarAI::EnterEvadeMode(), npc_twilight_volunteer::npc_twilight_volunteerAI::EnterEvadeMode(), boss_anub_arak::boss_anub_arakAI::EnterEvadeMode(), boss_halion::boss_halionAI::EnterEvadeMode(), boss_black_knight::boss_black_knightAI::EnterEvadeMode(), boss_bronjahm::boss_bronjahmAI::EnterEvadeMode(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterEvadeMode(), boss_falric::boss_falricAI::EnterEvadeMode(), boss_marwyn::boss_marwynAI::EnterEvadeMode(), npc_ghostly_priest::npc_ghostly_priestAI::EnterEvadeMode(), npc_phantom_mage::npc_phantom_mageAI::EnterEvadeMode(), npc_phantom_hallucination::npc_phantom_hallucinationAI::EnterEvadeMode(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::EnterEvadeMode(), npc_spectral_footman::npc_spectral_footmanAI::EnterEvadeMode(), npc_tortured_rifleman::npc_tortured_riflemanAI::EnterEvadeMode(), boss_frostsworn_general::boss_frostsworn_generalAI::EnterEvadeMode(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::EnterEvadeMode(), boss_garfrost::boss_garfrostAI::EnterEvadeMode(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterEvadeMode(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), npc_tirion_fordring_tft::npc_tirion_fordringAI::EnterEvadeMode(), boss_kelthuzad::boss_kelthuzadAI::EnterEvadeMode(), boss_noth::boss_nothAI::EnterEvadeMode(), boss_thaddius_summon::boss_thaddius_summonAI::EnterEvadeMode(), boss_malygos::boss_malygosAI::EnterEvadeMode(), npc_crystalline_frayer::npc_crystalline_frayerAI::EnterEvadeMode(), boss_urom::boss_uromAI::EnterEvadeMode(), boss_varos::boss_varosAI::EnterEvadeMode(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterEvadeMode(), boss_ignis::boss_ignisAI::EnterEvadeMode(), boss_mimiron::boss_mimironAI::EnterEvadeMode(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::EnterEvadeMode(), boss_razorscale::boss_razorscaleAI::EnterEvadeMode(), boss_thorim::boss_thorimAI::EnterEvadeMode(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::EnterEvadeMode(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::EnterEvadeMode(), boss_svala::boss_svalaAI::EnterEvadeMode(), boss_ymiron::boss_ymironAI::EnterEvadeMode(), boss_cyanigosa::boss_cyanigosaAI::EnterEvadeMode(), boss_erekem::boss_erekemAI::EnterEvadeMode(), boss_ichoron::boss_ichoronAI::EnterEvadeMode(), boss_lavanthor::boss_lavanthorAI::EnterEvadeMode(), boss_moragg::boss_moraggAI::EnterEvadeMode(), boss_xevozz::boss_xevozzAI::EnterEvadeMode(), boss_zuramat::boss_zuramatAI::EnterEvadeMode(), npc_wild_wyrm::npc_wild_wyrmAI::EnterEvadeMode(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterEvadeMode(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::EnterEvadeMode(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::EnterEvadeMode(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(), boss_shade_of_akama::boss_shade_of_akamaAI::EnterEvadeMode(), boss_illidari_council_memberAI::EnterEvadeMode(), boss_ahune::boss_ahuneAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), boss_four_horsemen::boss_four_horsemenAI::IsInRoom(), boss_gothik::boss_gothikAI::IsInRoom(), boss_loatheb::boss_loathebAI::IsInRoom(), boss_maexxna::boss_maexxnaAI::IsInRoom(), boss_sapphiron::boss_sapphironAI::IsInRoom(), ScriptedAI::IsInRoom(), boss_heigan::boss_heiganAI::IsInRoom(), boss_four_horsemen::boss_four_horsemenAI::MovementInform(), FrostwingGauntletRespawner::operator()(), boss_illidari_council::boss_illidari_councilAI::Reset(), Creature::SelectVictim(), npc_warden_mellichar::npc_warden_mellicharAI::SetData(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDespawn(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), Unit::TauntFadeOut(), Creature::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_yenniku::npc_yennikuAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), alliance_rifleman::alliance_riflemanAI::UpdateAI(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::UpdateAI(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::UpdateAI(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), PassiveAI::UpdateAI(), boss_hexlord_addAI::UpdateAI(), boss_illidari_council::boss_illidari_councilAI::UpdateAI(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::UpdateAI(), InstanceScript::UpdateMinionState(), and UpdateVictim().
IsEscorted()
virtual bool CreatureAI::IsEscorted () inline virtual
Reimplemented in SmartAI, and npc_escortAI.
Definition at line 127 of file CreatureAI.h.
 { return false; }
IsSummonedBy()
virtual void CreatureAI::IsSummonedBy (Unit *) inline virtual
Reimplemented in npc_venomhide_hatchling::npc_venomhide_hatchlingAI, npc_spirit_shade::npc_spirit_shadeAI, npc_pet_gen_fetch_ball, npc_kservant::npc_kservantAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI, npc_inner_demon::npc_inner_demonAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI, npc_spiritual_insight::npc_spiritual_insightAI, npc_oculus_drake::npc_oculus_drakeAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_little_ooze::npc_little_oozeAI, npc_bone_spike::npc_bone_spikeAI, npc_tiger_matriarch::npc_tiger_matriarchAI, npc_risen_guardian::npc_risen_guardianAI, npc_burning_spirit::npc_burning_spiritAI, SmartAI, TriggerAI, npc_suppresser::npc_suppresserAI, npc_lk_spirit_bomb::npc_lk_spirit_bombAI, npc_raging_spirit::npc_raging_spiritAI, npc_big_ooze::npc_big_oozeAI, npc_putricide_oozeAI, npc_coldflame::npc_coldflameAI, npc_kinetic_bomb::npc_kinetic_bombAI, npc_living_inferno::npc_living_infernoAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, npc_taldaram_flamesphere::npc_taldaram_flamesphereAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_direbrew_minion::npc_direbrew_minionAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_rend_blackhand::boss_rend_blackhandAI, and boss_gyth::boss_gythAI.
Definition at line 113 of file CreatureAI.h.
 {}
Referenced by TempSummon::InitSummon().
JustDied()
virtual void CreatureAI::JustDied (Unit *) inline virtual
Reimplemented in boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, boss_kalecgos::boss_kalecgosAI, npc_simone::npc_simoneAI, trigger_death::trigger_deathAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, boss_void_reaver::boss_void_reaverAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_alar::boss_alarAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_najentus::boss_najentusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_supremus::boss_supremusAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_mother_shahraz::boss_shahrazAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, npc_nerubar_victim::npc_nerubar_victimAI, npc_frost_tomb::npc_frost_tombAI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_keristrasza::boss_keristraszaAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_anomalus::boss_anomalusAI, npc_scion_of_eternity::npc_scion_of_eternityAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_razuvious::boss_razuviousAI, boss_patchwerk::boss_patchwerkAI, boss_noth::boss_nothAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad::boss_kelthuzadAI, boss_heigan::boss_heiganAI, boss_grobbulus::boss_grobbulusAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, boss_four_horsemen::boss_four_horsemenAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, npc_four_car_garage::npc_four_car_garageAI, npc_darnavan::npc_darnavanAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_slad_ran::boss_slad_ranAI, boss_moorabi::boss_moorabiAI, boss_gal_darah::boss_gal_darahAI, boss_eck::boss_eckAI, boss_trollgore::boss_trollgoreAI, boss_tharon_ja::boss_tharon_jaAI, boss_novos::boss_novosAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_krik_thir::boss_krik_thirAI, boss_hadronox::boss_hadronoxAI, boss_anub_arak::boss_anub_arakAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_webbed_creature::npc_webbed_creatureAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_epoch_hunter::boss_epoch_hunterAI, npc_gargoyle::npc_gargoyleAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, boss_azgalor::boss_azgalorAI, boss_anetheron::boss_anetheronAI, boss_felmyst::boss_felmystAI, boss_brutallus::boss_brutallusAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, boss_moroes::boss_moroesAI, boss_maiden_of_virtue::boss_maiden_of_virtueAI, boss_curator::boss_curatorAI, boss_magmus::boss_magmusAI, SmartAI, GuardAI, CombatAI, npc_pet_pri_shadowfiend, npc_pet_dk_ghoul::npc_pet_dk_ghoulAI, npc_isla_starmane::npc_isla_starmaneAI, npc_enraged_spirit::npc_enraged_spiritAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_bessy::npc_bessyAI, npc_captain_saeed::npc_captain_saeedAI, socrethar::socretharAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_maghar_captive::npc_maghar_captiveAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_warp_splinter::boss_warp_splinterAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_magtheridon::boss_magtheridonAI, boss_vazruden::boss_vazrudenAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_the_maker::boss_the_makerAI, npc_shadowmoon_channeler::npc_shadowmoon_channelerAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, boss_broggok::boss_broggokAI, boss_krosh_firehand::boss_krosh_firehandAI, boss_blindeye_the_seer::boss_blindeye_the_seerAI, boss_kiggler_the_crazed::boss_kiggler_the_crazedAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_gruul::boss_gruulAI, boss_the_black_stalker::boss_the_black_stalkerAI, boss_warlord_kalithresh::boss_warlord_kalithreshAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, boss_hydromancer_thespia::boss_thespiaAI, npc_ahune_frozen_core::npc_ahune_frozen_coreAI, boss_ahune::boss_ahuneAI, npc_inner_demon::npc_inner_demonAI, boss_doomwalker::boss_doomwalkerAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_illidari_council_memberAI, npc_akama_shade::npc_akamaAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_murmur::boss_murmurAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_anzu::boss_anzuAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_pandemonius::boss_pandemoniusAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_exarch_maladaar::boss_exarch_maladaarAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_engineer_helice::npc_engineer_heliceAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_blessed_banner::npc_blessed_bannerAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, npc_q24545_vegard::npc_q24545_vegardAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_mindless_ghoul::npc_mindless_ghoulAI, npc_counselor_talbot::npc_counselor_talbotAI, npc_thassarian2::npc_thassarian2AI, npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_mootoo_the_younger::npc_mootoo_the_youngerAI, violet_hold_trashAI, npc_vh_teleportation_portal::npc_vh_teleportation_portalAI, npc_vh_void_sentry::npc_vh_void_sentryAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, npc_ichor_globule::npc_ichor_globuleAI, boss_ichoron::boss_ichoronAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, boss_toravon::boss_toravonAI, boss_koralon::boss_koralonAI, boss_emalon::boss_emalonAI, boss_archavon::boss_archavonAI, boss_ymiron::boss_ymironAI, boss_svala::boss_svalaAI, boss_skadi::boss_skadiAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, boss_keleseth::boss_kelesethAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI, boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_heart::npc_xt002_heartAI, boss_xt002::boss_xt002AI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_razorscale::boss_razorscaleAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI, npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI, boss_vezax::boss_vezaxAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_iron_root::boss_freya_iron_rootAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, boss_auriaya::boss_auriayaAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, brann_bronzebeard::brann_bronzebeardAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, boss_sjonnir::boss_sjonnirAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_krystallus::boss_krystallusAI, boss_volkhan::boss_volkhanAI, boss_loken::boss_lokenAI, boss_ionar::boss_ionarAI, boss_bjarngrim::boss_bjarngrimAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, boss_drakos::boss_drakosAI, npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI, npc_nexus_lord::npc_nexus_lordAI, boss_malygos::boss_malygosAI, boss_naxxramas_misc::boss_naxxramas_miscAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_maexxna_webwrap::boss_maexxna_webwrapAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_argent_captainAI, boss_sister_svalna::boss_sister_svalnaAI, npc_rotting_frost_giant::npc_rotting_frost_giantAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, npc_spirit_warden::npc_spirit_wardenAI, npc_raging_spirit::npc_raging_spiritAI, boss_the_lich_king::boss_the_lich_kingAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, npc_ice_tomb::npc_ice_tombAI, boss_sindragosa::boss_sindragosaAI, npc_precious_icc::npc_precious_iccAI, npc_big_ooze::npc_big_oozeAI, npc_little_ooze::npc_little_oozeAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, npc_bone_spike::npc_bone_spikeAI, boss_lord_marrowgar, gunship_npc_AI, npc_gunship::npc_gunshipAI, npc_stinky_icc::npc_stinky_iccAI, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_dark_nucleus::npc_dark_nucleusAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_drakkari_elemental::boss_drakkari_elementalAI, boss_tyrannus::boss_tyrannusAI, boss_ick::boss_ickAI, boss_garfrost::boss_garfrostAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_raging_ghoul::npc_hor_raging_ghoulAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_phantom_hallucination::npc_phantom_hallucinationAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_bronjahm::boss_bronjahmAI, boss_twin_valkyrAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_fel_infernal::npc_fel_infernalAI, boss_jaraxxus::boss_jaraxxusAI, boss_faction_championsAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, boss_black_knight::boss_black_knightAI, npc_argent_soldier::npc_argent_soldierAI, npc_memory::npc_memoryAI, npc_living_inferno::npc_living_infernoAI, boss_sartharion_dragonAI, boss_sartharion::boss_sartharionAI, boss_taldaram::boss_taldaramAI, npc_taldaram_flamesphere::npc_taldaram_flamesphereAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_volazj::boss_volazjAI, boss_elder_nadox::boss_elder_nadoxAI, boss_amanitar::boss_amanitarAI, npc_ame::npc_ameAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_omen::npc_omenAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_muglash::npc_muglashAI, npc_anubisath_sentinel::aqsentinelAI, npc_glob_of_viscidus::npc_glob_of_viscidusAI, boss_viscidus::boss_viscidusAI, boss_twinemperorsAI, boss_skeram::boss_skeramAI, boss_sartura::boss_sarturaAI, npc_giant_flesh_tentacle::flesh_tentacleAI, npc_giant_eye_tentacle::giant_eye_tentacleAI, npc_giant_claw_tentacle::giant_claw_tentacleAI, npc_claw_tentacle::claw_tentacleAI, npc_eye_tentacle::eye_tentacleAI, boss_cthun::cthunAI, boss_yauj::boss_yaujAI, boss_vem::boss_vemAI, boss_kri::boss_kriAI, boss_rajaxx::boss_rajaxxAI, boss_ossirian::boss_ossirianAI, boss_kurinnaxx::boss_kurinnaxxAI, npc_buru_egg::npc_buru_eggAI, npc_belnistrasz::npc_belnistraszAI, boss_onyxia::boss_onyxiaAI, npc_medivh_bm::npc_medivh_bmAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_arthas::npc_arthasAI, boss_salramm::boss_salrammAI, boss_meathook::boss_meathookAI, boss_mal_ganis::boss_mal_ganisAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_epoch::boss_epochAI, hyjalAI, hyjal_trashAI, alliance_rifleman::alliance_riflemanAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_archimonde::boss_archimondeAI, npc_towering_infernal::npc_towering_infernalAI, npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_coren_direbrew::npc_coren_direbrewAI, boss_wushoolay::boss_wushoolayAI, boss_venoxis::boss_venoxisAI, boss_thekal::boss_thekalAI, boss_renataki::boss_renatakiAI, boss_marli::boss_marliAI, npc_vilebranch_speaker::npc_vilebranch_speakerAI, npc_ohgan::npc_ohganAI, boss_mandokir::boss_mandokirAI, boss_jindo::boss_jindoAI, boss_jeklik::boss_jeklikAI, boss_hazzarah::boss_hazzarahAI, boss_hakkar::boss_hakkarAI, boss_grilek::boss_grilekAI, boss_gahzranka::boss_gahzrankaAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_arlokk::boss_arlokkAI, npc_zulaman_hostage::npc_zulaman_hostageAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, boss_janalai::boss_janalaiAI, boss_hexlord_malacrass::boss_hex_lord_malacrassAI, boss_halazzi::boss_halazziAI, boss_akilzon::boss_akilzonAI, pyrewood_ambush::pyrewood_ambushAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, boss_entropius::boss_entropiusAI, boss_kiljaeden::boss_kiljaedenAI, npc_kiljaeden_controller::npc_kiljaeden_controllerAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalec::boss_kalecAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_priestess_lackey_commonAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, npc_tito::npc_titoAI, boss_dorothee::boss_dorotheeAI, boss_terestian_illhoof::boss_terestianAI, npc_demon_chain::npc_demon_chainAI, npc_kilrek::npc_kilrekAI, boss_shade_of_aran::boss_aranAI, boss_servant_quarters::boss_servant_quartersAI, boss_malchezaar::boss_malchezaarAI, boss_nightbane::boss_nightbaneAI, boss_netherspite::boss_netherspiteAI, boss_attumen_midnight::boss_attumen_midnightAI, npc_flamewaker_priest::npc_flamewaker_priestAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, boss_razorgore::boss_razorgoreAI, boss_nefarian::boss_nefarianAI, boss_broodlord::boss_broodlordAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_quartermaster_zigris, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_highlord_omokk::boss_highlordomokkAI, boss_halycon::boss_halyconAI, boss_gyth::boss_gythAI, boss_drakkisath::boss_drakkisathAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, boss_balinda::boss_balindaAI, FollowerAI, npc_escortAI, WorldBossAI, BossAI, ScriptedAI, PossessedAI, and NPCStaveQuestAI.
Definition at line 106 of file CreatureAI.h.
 {}
Referenced by Unit::Kill(), boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn(), and spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TriggerWipe().
JustReachedHome()
virtual void CreatureAI::JustReachedHome () inline virtual
Reimplemented in npc_precious::npc_preciousAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, boss_alar::boss_alarAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI, violet_hold_trashAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, boss_xt002::boss_xt002AI, boss_thorim::boss_thorimAI, boss_razorscale::boss_razorscaleAI, boss_mimiron::boss_mimironAI, boss_ignis::boss_ignisAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, boss_vezax::boss_vezaxAI, boss_freya::boss_freyaAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_auriaya::boss_auriayaAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_sindragosa::boss_sindragosaAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, boss_lord_marrowgar, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_gal_darah::boss_gal_darahAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_bronjahm::boss_bronjahmAI, boss_twin_valkyrAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, boss_gormok::boss_gormokAI, boss_jaraxxus::boss_jaraxxusAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_halion::boss_halionAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, boss_aeonus::boss_aeonusAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_thekal::boss_thekalAI, boss_kalecgos::boss_kalecgosAI, npc_scholomance_occultist::npc_scholomance_occultistAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, boss_dorothee::boss_dorotheeAI, boss_moroes::boss_moroesAI, boss_majordomo::boss_majordomoAI, boss_nefarian::boss_nefarianAI, boss_victor_nefarius::boss_victor_nefariusAI, SmartAI, and BossAI.
Definition at line 138 of file CreatureAI.h.
 {}
Referenced by HomeMovementGenerator< Creature >::DoFinalize(), npc_spinestalker::npc_spinestalkerAI::JustReachedHome(), npc_rimefang::npc_rimefangAI::JustReachedHome(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), boss_mimiron::boss_mimironAI::JustReachedHome(), and Creature::RespawnOnEvade().
JustRespawned()
virtual void CreatureAI::JustRespawned () inline virtual
Reimplemented in npc_simone::npc_simoneAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, npc_storm_cloud::npc_storm_cloudAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_rinji::npc_rinjiAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_galvangar::boss_galvangarAI, boss_drekthar::boss_drektharAI, boss_balinda::boss_balindaAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, SmartAI, FollowerAI, and npc_escortAI.
Definition at line 130 of file CreatureAI.h.
 { Reset(); }
References UnitAI::Reset().
Referenced by boss_prince_keleseth_icc::boss_prince_kelesethAI::JustRespawned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustRespawned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustRespawned(), npc_spinestalker::npc_spinestalkerAI::JustRespawned(), npc_rimefang::npc_rimefangAI::JustRespawned(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustRespawned(), and Creature::Update().
JustSummoned()
virtual void CreatureAI::JustSummoned (Creature *) inline virtual
Reimplemented in npc_buru_egg::npc_buru_eggAI, boss_ayamiss::boss_ayamissAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_earthmender_wilda::npc_earthmender_wildaAI, npc_bessy::npc_bessyAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_maghar_captive::npc_maghar_captiveAI, npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_broggok::boss_broggokAI, npc_blessed_banner::npc_blessed_bannerAI, npc_emily::npc_emilyAI, npc_ame::npc_ameAI, npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI, npc_kaya_flathoof::npc_kaya_flathoofAI, npc_muglash::npc_muglashAI, hyjalAI, boss_archimonde::boss_archimondeAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, pyrewood_ambush::pyrewood_ambushAI, npc_rinji::npc_rinjiAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, boss_terestian_illhoof::boss_terestianAI, boss_nightbane::boss_nightbaneAI, boss_vaelastrasz::boss_vaelAI, boss_balinda::boss_balindaAI, npc_nelson::npc_nelsonAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_alar::boss_alarAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_the_black_stalker::boss_the_black_stalkerAI, boss_ahune::boss_ahuneAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_veras_darkshadow::boss_veras_darkshadowAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_supremus::boss_supremusAI, npc_creature_generator_akama::npc_creature_generator_akamaAI, npc_akama_shade::npc_akamaAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, npc_akama_illidan::npc_akama_illidanAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_anzu::boss_anzuAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, boss_emalon::boss_emalonAI, boss_svala::boss_svalaAI, boss_vezax::boss_vezaxAI, npc_algalon_worm_hole::npc_algalon_worm_holeAI, npc_collapsing_star::npc_collapsing_starAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_volkhan::boss_volkhanAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_anomalus::boss_anomalusAI, boss_malygos::boss_malygosAI, boss_noth::boss_nothAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_risen_archmage::npc_risen_archmageAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, boss_the_lich_king::boss_the_lich_kingAI, boss_sindragosa::boss_sindragosaAI, npc_precious_icc::npc_precious_iccAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_slad_ran::boss_slad_ranAI, boss_gal_darah::boss_gal_darahAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_bronjahm::boss_bronjahmAI, boss_trollgore::boss_trollgoreAI, boss_novos::boss_novosAI, boss_gormok::boss_gormokAI, boss_jaraxxus::boss_jaraxxusAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_black_knight::boss_black_knightAI, boss_paletress::boss_paletressAI, boss_halion::boss_halionAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_dragonAI, boss_sartharion::boss_sartharionAI, boss_krik_thir::boss_krik_thirAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_hadronox::boss_hadronoxAI, boss_anub_arak::boss_anub_arakAI, boss_taldaram::boss_taldaramAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_amanitar::boss_amanitarAI, npc_medivh_bm::npc_medivh_bmAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_necromancer::npc_necromancerAI, boss_zuljin::boss_zuljinAI, boss_halazzi::boss_halazziAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, boss_muru::boss_muruAI, npc_kalecgos_kj::npc_kalecgos_kjAI, boss_kiljaeden::boss_kiljaedenAI, npc_kiljaeden_controller::npc_kiljaeden_controllerAI, npc_demonic_vapor_trail::npc_demonic_vapor_trailAI, boss_felmyst::boss_felmystAI, boss_sacrolash::boss_sacrolashAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_priestess_lackey_commonAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, npc_fiendish_portal::npc_fiendish_portalAI, boss_moroes::boss_moroesAI, boss_midnight::boss_midnightAI, boss_curator::boss_curatorAI, boss_majordomo::boss_majordomoAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_gyth::boss_gythAI, npc_grimstone::npc_grimstoneAI, WorldBossAI, BossAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_mimiron::boss_mimironAI, boss_hodir::boss_hodirAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_leader::npc_pos_leaderAI, npc_hor_lich_king::npc_hor_lich_kingAI, boss_twin_valkyrAI, npc_vh_teleportation_portal::npc_vh_teleportation_portalAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_ichoron::boss_ichoronAI, boss_onyxia::boss_onyxiaAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, npc_archmage_landalock::npc_archmage_landalockAI, npc_battle_at_valhalas::npc_battle_at_valhalasAI, boss_skeram::boss_skeramAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_eye_of_acherus::npc_eye_of_acherusAI, SmartAI, deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_frosthound::npc_frosthoundAI, npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI, boss_toravon::boss_toravonAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_heart::npc_xt002_heartAI, boss_xt002::boss_xt002AI, boss_thorim::boss_thorimAI, boss_kologarn::boss_kologarnAI, boss_freya::boss_freyaAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_freya_ward::npc_freya_wardAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_auriaya::boss_auriayaAI, brann_bronzebeard::brann_bronzebeardAI, boss_thaddius::boss_thaddiusAI, boss_razuvious::boss_razuviousAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad::boss_kelthuzadAI, boss_grobbulus::boss_grobbulusAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, npc_arthas::npc_arthasAI, boss_salramm::boss_salrammAI, boss_infinite_corruptor::boss_infinite_corruptorAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, boss_headless_horseman::boss_headless_horsemanAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, npc_toc_boomkin::npc_toc_boomkinAI, npc_toc_hunter::npc_toc_hunterAI, npc_toc_warlock::npc_toc_warlockAI, exarch_orelis::exarch_orelisAI, boss_varos::boss_varosAI, boss_drakos::boss_drakosAI, boss_ick::boss_ickAI, boss_fjola::boss_fjolaAI, boss_eydis::boss_eydisAI, npc_prospector_remtravel::npc_prospector_remtravelAI, boss_victor_nefarius::boss_victor_nefariusAI, and ScriptedAI.
Definition at line 112 of file CreatureAI.h.
 {}
Referenced by spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), TempSummon::InitSummon(), and spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript().
KilledUnit()
virtual void CreatureAI::KilledUnit (Unit *) inline virtual
Reimplemented in boss_emeriss::boss_emerissAI, emerald_dragonAI, npc_q24545_vegard::npc_q24545_vegardAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_razuvious::boss_razuviousAI, boss_patchwerk::boss_patchwerkAI, boss_noth::boss_nothAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_kelthuzad::boss_kelthuzadAI, boss_heigan::boss_heiganAI, boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI, boss_grobbulus::boss_grobbulusAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, boss_four_horsemen::boss_four_horsemenAI, boss_faerlina::boss_faerlinaAI, boss_tyrannus::boss_tyrannusAI, boss_ick::boss_ickAI, boss_garfrost::boss_garfrostAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, boss_bronjahm::boss_bronjahmAI, boss_twin_valkyrAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_anetheron::boss_anetheronAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, boss_akilzon::boss_akilzonAI, netherspite_infernal::netherspite_infernalAI, kaylaan_the_lost::kaylaan_the_lostAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_void_reaver::boss_void_reaverAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_warp_splinter::boss_warp_splinterAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_the_maker::boss_the_makerAI, boss_warlord_kalithresh::boss_warlord_kalithreshAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, boss_hydromancer_thespia::boss_thespiaAI, boss_doomwalker::boss_doomwalkerAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_najentus::boss_najentusAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_pandemonius::boss_pandemoniusAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_zuramat::boss_zuramatAI, boss_ichoron::boss_ichoronAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, boss_svala::boss_svalaAI, boss_palehoof::boss_palehoofAI, boss_xt002::boss_xt002AI, boss_razorscale::boss_razorscaleAI, boss_freya::boss_freyaAI, boss_algalon_the_observer::boss_algalon_the_observerAI, boss_volkhan::boss_volkhanAI, boss_loken::boss_lokenAI, boss_ionar::boss_ionarAI, boss_bjarngrim::boss_bjarngrimAI, boss_malygos::boss_malygosAI, boss_anubrekhan::boss_anubrekhanAI, npc_argent_captainAI, boss_sister_svalna::boss_sister_svalnaAI, boss_the_lich_king::boss_the_lich_kingAI, boss_sindragosa::boss_sindragosaAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, boss_lord_marrowgar, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_black_knight::boss_black_knightAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, boss_hadronox::boss_hadronoxAI, boss_taldaram::boss_taldaramAI, boss_volazj::boss_volazjAI, boss_elder_nadox::boss_elder_nadoxAI, npc_tiger_matriarch::npc_tiger_matriarchAI, boss_buru::boss_buruAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_epoch_hunter::boss_epoch_hunterAI, boss_archimonde::boss_archimondeAI, boss_mandokir::boss_mandokirAI, boss_halazzi::boss_halazziAI, boss_twilight_corrupter::boss_twilight_corrupterAI, boss_kiljaeden::boss_kiljaedenAI, boss_kalecgos::boss_kalecgosAI, boss_felmyst::boss_felmystAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, boss_brutallus::boss_brutallusAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_priestess_lackey_commonAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, boss_vaelastrasz::boss_vaelAI, boss_nefarian::boss_nefarianAI, SmartAI, PossessedAI, boss_sartharion_dragonAI, boss_sathrovarr::boss_sathrovarrAI, boss_xevozz::boss_xevozzAI, boss_sartharion::boss_sartharionAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_magtheridon::boss_magtheridonAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_vazruden::boss_vazrudenAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_gruul::boss_gruulAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_illidari_council_memberAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_mother_shahraz::boss_shahrazAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_exarch_maladaar::boss_exarch_maladaarAI, boss_ymiron::boss_ymironAI, boss_skadi::boss_skadiAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, boss_thorim::boss_thorimAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_auriaya::boss_auriayaAI, boss_sjonnir::boss_sjonnirAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_krystallus::boss_krystallusAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, boss_drakos::boss_drakosAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_keristrasza::boss_keristraszaAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_slad_ran::boss_slad_ranAI, boss_moorabi::boss_moorabiAI, boss_gal_darah::boss_gal_darahAI, boss_trollgore::boss_trollgoreAI, boss_tharon_ja::boss_tharon_jaAI, boss_novos::boss_novosAI, boss_faction_championsAI, boss_saviana_ragefire::boss_saviana_ragefireAI, boss_general_zarithrian::boss_general_zarithrianAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_krik_thir::boss_krik_thirAI, boss_anub_arak::boss_anub_arakAI, boss_twinemperorsAI, boss_skeram::boss_skeramAI, boss_sartura::boss_sarturaAI, boss_ossirian::boss_ossirianAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_captain_skarloc::boss_captain_skarlocAI, boss_salramm::boss_salrammAI, boss_meathook::boss_meathookAI, boss_mal_ganis::boss_mal_ganisAI, boss_epoch::boss_epochAI, npc_necromancer::npc_necromancerAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_azgalor::boss_azgalorAI, npc_towering_infernal::npc_towering_infernalAI, boss_headless_horseman::boss_headless_horsemanAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, boss_janalai::boss_janalaiAI, boss_hexlord_malacrass::boss_hex_lord_malacrassAI, npc_risen_guardian::npc_risen_guardianAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_mograine::npc_mograineAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, boss_terestian_illhoof::boss_terestianAI, boss_shade_of_aran::boss_aranAI, boss_malchezaar::boss_malchezaarAI, boss_moroes::boss_moroesAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, boss_midnight::boss_midnightAI, boss_maiden_of_virtue::boss_maiden_of_virtueAI, boss_curator::boss_curatorAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, ScriptedAI, and PetAI.
Definition at line 109 of file CreatureAI.h.
 {}
Referenced by Unit::Kill().
MoveBackwardsChecks()
void CreatureAI::MoveBackwardsChecks ()
Definition at line 344 of file CreatureAI.cpp.
{
     Unit *victim = me->GetVictim();
     if (
         !victim ||
         !me->IsFreeToMove() || me->HasUnitMovementFlag(MOVEMENTFLAG_ROOT) ||
         (victim->GetTypeId() != TYPEID_PLAYER && !victim->IsPet())
     )
     {
         return;
     }
     float moveDist = me->GetMeleeRange(victim) / 2;
     me->GetMotionMaster()->MoveBackwards(victim, moveDist);
 }
References Unit::GetMeleeRange(), Unit::GetMotionMaster(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasUnitMovementFlag(), Creature::IsFreeToMove(), Unit::IsPet(), me, MotionMaster::MoveBackwards(), MOVEMENTFLAG_ROOT, and TYPEID_PLAYER.
Referenced by Creature::Update().
MoveCircleChecks()
void CreatureAI::MoveCircleChecks ()
Definition at line 327 of file CreatureAI.cpp.
 {
     Unit *victim = me->GetVictim();
     if (
         !victim ||
         !me->IsFreeToMove() || me->HasUnitMovementFlag(MOVEMENTFLAG_ROOT) ||
         !me->IsWithinMeleeRange(victim) || me == victim->GetVictim() ||
         (victim->GetTypeId() != TYPEID_PLAYER && !victim->IsPet())  // only player & pets to save CPU
     )
     {
         return;
     }
     me->GetMotionMaster()->MoveCircleTarget(me->GetVictim());
 }
References Unit::GetMotionMaster(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasUnitMovementFlag(), Creature::IsFreeToMove(), Unit::IsPet(), Unit::IsWithinMeleeRange(), me, MotionMaster::MoveCircleTarget(), MOVEMENTFLAG_ROOT, and TYPEID_PLAYER.
Referenced by Creature::Update().
MoveInLineOfSight()
void CreatureAI::MoveInLineOfSight (Unit * who) protected virtual
Reimplemented in npc_air_force_bots::npc_air_force_botsAI, npc_pet_hunter_snake_trap, npc_natrualist_bite::npc_natrualist_biteAI, npc_captain_saeed::npc_captain_saeedAI, deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI, npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI, npc_ancestral_wolf::npc_ancestral_wolfAI, npc_daranelle::npc_daranelleAI, npc_nether_drake::npc_nether_drakeAI, boss_kaelthas::boss_kaelthasAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_lady_vashj::boss_lady_vashjAI, boss_doomwalker::boss_doomwalkerAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_exarch_maladaar::boss_exarch_maladaarAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_guardian_pavilion::npc_guardian_pavilionAI, npc_black_knight_graveyard::npc_black_knight_graveyardAI, npc_future_you::npc_future_youAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_khunok_the_behemoth::npc_khunok_the_behemothAI, violet_hold_trashAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, npc_ulduar_snow_mound::npc_ulduar_snow_moundAI, npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI, boss_kologarn::boss_kologarnAI, npc_brann_radio::npc_brann_radioAI, npc_hol_monument::npc_hol_monumentAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_kelthuzad::boss_kelthuzadAI, boss_gluth::boss_gluthAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, boss_sindragosa::boss_sindragosaAI, boss_professor_putricide::boss_professor_putricideAI, boss_lord_marrowgar, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, npc_living_mojo::npc_living_mojoAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_krik_thir::boss_krik_thirAI, boss_anub_arak::boss_anub_arakAI, npc_ringo::npc_ringoAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_tooga::npc_toogaAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI, npc_kerlonian::npc_kerlonianAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_depth_charge::npc_depth_chargeAI, boss_twinemperorsAI, boss_ossirian::boss_ossirianAI, npc_hive_zara_larva::npc_hive_zara_larvaAI, npc_onyxia_whelp::npc_onyxia_whelpAI, npc_onyxian_lair_guard::npc_onyxian_lair_guardAI, boss_onyxia::boss_onyxiaAI, npc_medivh_bm::npc_medivh_bmAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, hyjalAI, alliance_rifleman::alliance_riflemanAI, npc_lesser_doomguard::npc_lesser_doomguardAI, npc_doomfire_targetting::npc_doomfire_targettingAI, npc_towering_infernal::npc_towering_infernalAI, npc_love_in_air_snivel::npc_love_in_air_snivelAI, npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI, npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI, npc_cw_area_trigger::npc_cw_area_triggerAI, npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI, npc_the_etymidian::npc_the_etymidianAI, npc_elder_kekek::npc_elder_kekekAI, npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI, npc_the_biggest_tree::npc_the_biggest_treeAI, npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI, npc_winterfin_playmate::npc_winterfin_playmateAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI, npc_brewfest_keg_reciver::npc_brewfest_keg_reciverAI, npc_brewfest_keg_thrower::npc_brewfest_keg_throwerAI, boss_nalorakk::boss_nalorakkAI, npc_andorhal_tower::npc_andorhal_towerAI, npc_the_scourge_cauldron::npc_the_scourge_cauldronAI, npc_grand_magister_rommath::npc_grand_magister_rommathAI, boss_twilight_corrupter::boss_twilight_corrupterAI, npc_fairbanks::npc_fairbanksAI, npc_mograine::npc_mograineAI, npc_scarlet_guard::npc_scarlet_guardAI, npc_a_special_surprise::npc_a_special_surpriseAI, npc_dkc1_gothik::npc_dkc1_gothikAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, boss_dorothee::boss_dorotheeAI, boss_nightbane::boss_nightbaneAI, SmartAI, npc_escortAI, TotemAI, boss_sartharion_dragonAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_brew_bubble::npc_brew_bubbleAI, npc_target_dummy::npc_target_dummyAI, npc_training_dummy::npc_training_dummyAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, boss_alar::boss_alarAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_magtheridon::boss_magtheridonAI, npc_steamrigger_mechanic::npc_steamrigger_mechanicAI, boss_ahune::boss_ahuneAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_illidari_council::boss_illidari_councilAI, npc_akama_illidan::npc_akama_illidanAI, boss_illidan_stormrage::boss_illidan_stormrageAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_blessed_banner::npc_blessed_bannerAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_mrfloppy::npc_mrfloppyAI, npc_azure_saboteur::npc_azure_saboteurAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, npc_ichor_globule::npc_ichor_globuleAI, boss_ichoron::boss_ichoronAI, npc_erekem_guard::npc_erekem_guardAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, boss_keleseth::boss_kelesethAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_heart::npc_xt002_heartAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim_sif::boss_thorim_sifAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_mimiron::boss_mimironAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_ignis::boss_ignisAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, npc_mimirons_inferno::npc_mimirons_infernoAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_assembly_lightning::npc_assembly_lightningAI, brann_bronzebeard::brann_bronzebeardAI, boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI, boss_loken::boss_lokenAI, npc_spark_of_ionar::npc_spark_of_ionarAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, boss_drakos::boss_drakosAI, npc_alexstrasza::npc_alexstraszaAI, npc_hover_disk::npc_hover_diskAI, npc_scion_of_eternity::npc_scion_of_eternityAI, npc_vortex_ride::npc_vortex_rideAI, boss_malygos::boss_malygosAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_vengeful_shade::npc_vengeful_shadeAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_ball_of_flame::npc_ball_of_flameAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_pos_leader::npc_pos_leaderAI, boss_novos::boss_novosAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_jaraxxus::boss_jaraxxusAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, npc_injured_draenei::npc_injured_draeneiAI, npc_onyxia_trigger::npc_onyxia_triggerAI, npc_taretha::npc_tarethaAI, npc_doomfire::npc_doomfireAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI, npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI, npc_janalai_hatcher::npc_janalai_hatcherAI, npc_janalai_firebomb::npc_janalai_firebombAI, npc_akilzon_eagle::npc_akilzon_eagleAI, npc_cyclone::npc_cycloneAI, npc_demon_chain::npc_demon_chainAI, netherspite_infernal::netherspite_infernalAI, FollowerAI, ReactorAI, PetAI, NullCreatureAI, PossessedAI, PassiveAI, and VehicleAI.
Definition at line 161 of file CreatureAI.cpp.
 {
     if (me->GetVictim())
         return;
     // pussywizard: civilian, non-combat pet or any other NOT HOSTILE TO ANYONE (!)
     if (me->IsMoveInLineOfSightDisabled())
         if (me->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET ||      // nothing more to do, return
                 !who->IsInCombat() ||                                         // if not in combat, nothing more to do
                 !me->IsWithinDist(who, ATTACK_DISTANCE, true, false))                      // if in combat and in dist - neutral to all can actually assist other creatures
             return;
     if (me->HasReactState(REACT_AGGRESSIVE) && me->CanStartAttack(who))
         AttackStart(who);
 }
References ATTACK_DISTANCE, UnitAI::AttackStart(), Creature::CanStartAttack(), CREATURE_TYPE_NON_COMBAT_PET, Unit::GetCreatureType(), Unit::GetVictim(), Creature::HasReactState(), Unit::IsInCombat(), Creature::IsMoveInLineOfSightDisabled(), WorldObject::IsWithinDist(), me, and REACT_AGGRESSIVE.
Referenced by boss_sartharion_dragonAI::MoveInLineOfSight(), boss_nightbane::boss_nightbaneAI::MoveInLineOfSight(), boss_dorothee::boss_dorotheeAI::MoveInLineOfSight(), boss_strawman::boss_strawmanAI::MoveInLineOfSight(), boss_tinhead::boss_tinheadAI::MoveInLineOfSight(), boss_roar::boss_roarAI::MoveInLineOfSight(), boss_julianne::boss_julianneAI::MoveInLineOfSight(), boss_romulo::boss_romuloAI::MoveInLineOfSight(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_mograine::npc_mograineAI::MoveInLineOfSight(), boss_twilight_corrupter::boss_twilight_corrupterAI::MoveInLineOfSight(), boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::MoveInLineOfSight(), boss_aeonus::boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::MoveInLineOfSight(), boss_temporus::boss_temporusAI::MoveInLineOfSight(), npc_hive_zara_larva::npc_hive_zara_larvaAI::MoveInLineOfSight(), boss_ossirian::boss_ossirianAI::MoveInLineOfSight(), boss_anub_arak::boss_anub_arakAI::MoveInLineOfSight(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), npc_living_mojo::npc_living_mojoAI::MoveInLineOfSight(), boss_lord_marrowgar::MoveInLineOfSight(), boss_professor_putricide::boss_professor_putricideAI::MoveInLineOfSight(), boss_sindragosa::boss_sindragosaAI::MoveInLineOfSight(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_anubrekhan::boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlina::boss_faerlinaAI::MoveInLineOfSight(), boss_gluth::boss_gluthAI::MoveInLineOfSight(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), boss_palehoof::boss_palehoofAI::MoveInLineOfSight(), npc_massive_jormungar::npc_massive_jormungarAI::MoveInLineOfSight(), npc_ferocious_rhino::npc_ferocious_rhinoAI::MoveInLineOfSight(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::MoveInLineOfSight(), npc_frenzied_worgen::npc_frenzied_worgenAI::MoveInLineOfSight(), violet_hold_trashAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), boss_exarch_maladaar::boss_exarch_maladaarAI::MoveInLineOfSight(), boss_talon_king_ikiss::boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::MoveInLineOfSight(), boss_lady_vashj::boss_lady_vashjAI::MoveInLineOfSight(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::MoveInLineOfSight(), npc_nether_drake::npc_nether_drakeAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_natrualist_bite::npc_natrualist_biteAI::MoveInLineOfSight(), and MoveInLineOfSight_Safe().
MoveInLineOfSight_Safe()
void CreatureAI::MoveInLineOfSight_Safe (Unit * who)
== Reactions At =================================
Definition at line 150 of file CreatureAI.cpp.
 {
     if (m_MoveInLineOfSight_locked)
     {
         return;
     }
     m_MoveInLineOfSight_locked = true;
     MoveInLineOfSight(who);
     m_MoveInLineOfSight_locked = false;
 }
References m_MoveInLineOfSight_locked, and MoveInLineOfSight().
Referenced by CreatureUnitRelocationWorker().
MovementInform()
virtual void CreatureAI::MovementInform (uint32 , uint32) inline virtual
Reimplemented in npc_attracted_reef_bull::npc_attracted_reef_bullAI, npc_janalai_hatcher::npc_janalai_hatcherAI, npc_akilzon_eagle::npc_akilzon_eagleAI, npc_escortAI, ScriptedAI, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_wounded_skirmisher::npc_wounded_skirmisherAI, boss_skadi_grauf::boss_skadi_graufAI, boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI, npc_oculus_drakegiver::npc_oculus_drakegiverAI, boss_icehowl::boss_icehowlAI, npc_glob_of_viscidus::npc_glob_of_viscidusAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, boss_ymiron::boss_ymironAI, npc_released_offspring_harkoa::npc_released_offspring_harkoaAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_iron_watcher::npc_iron_watcherAI, npc_vics_flying_machine::npc_vics_flying_machineAI, npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, npc_hodirs_fury::npc_hodirs_furyAI, npc_assembly_lightning::npc_assembly_lightningAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_announcer_toc5::npc_announcer_toc5AI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_zelfrax::npc_zelfraxAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, boss_kagani_nightstrike::boss_kagani_nightstrikeAI, npc_burning_spirit::npc_burning_spiritAI, npc_wild_wyrm::npc_wild_wyrmAI, boss_the_lich_king::boss_the_lich_kingAI, npc_gunship_rocketeer::npc_gunship_rocketeerAI, npc_gunship_gunner::npc_gunship_gunnerAI, npc_gunship_mage::npc_gunship_mageAI, npc_gunship_boarding_addAI, gunship_npc_AI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, npc_omen::npc_omenAI, boss_majordomo::boss_majordomoAI, boss_sartharion_dragonAI, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_ishanah::ishanahAI, kaylaan_the_lost::kaylaan_the_lostAI, exarch_orelis::exarch_orelisAI, anchorite_karja::anchorite_karjaAI, adyen_the_lightbringer::adyen_the_lightbringerAI, boss_kaelthas::boss_kaelthasAI, npc_akama_shade::npc_akamaAI, npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI, npc_lk_spirit_bomb::npc_lk_spirit_bombAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_sindragosa::boss_sindragosaAI, boss_saviana_ragefire::boss_saviana_ragefireAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_soh::npc_hallows_end_sohAI, boss_felmyst::boss_felmystAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_eye_of_acherus::npc_eye_of_acherusAI, boss_servant_quarters::boss_servant_quartersAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, boss_mr_smite::boss_mr_smiteAI, npc_leryssa::npc_leryssaAI, npc_thassarian2::npc_thassarian2AI, npc_pet_gen_toxic_wasteling, npc_pet_gen_plump_turkey, npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_corki::npc_corkiAI, npc_fel_guard_hound::npc_fel_guard_houndAI, npc_nether_drake::npc_nether_drakeAI, boss_alar::boss_alarAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_nazan::boss_nazanAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_lady_vashj::boss_lady_vashjAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_illidan_stormrage::boss_illidan_stormrageAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI, npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, boss_volkhan::boss_volkhanAI, npc_oculus_drake::npc_oculus_drakeAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, npc_hover_disk::npc_hover_diskAI, boss_malygos::boss_malygosAI, boss_sapphiron::boss_sapphironAI, boss_four_horsemen::boss_four_horsemenAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI, boss_sister_svalna::boss_sister_svalnaAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_professor_putricide::boss_professor_putricideAI, boss_lord_marrowgar, npc_darnavan::npc_darnavanAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, boss_eck::boss_eckAI, npc_pos_leader_second::npc_pos_leader_secondAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI, npc_pos_after_first_boss::npc_pos_after_first_bossAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_garfrost::boss_garfrostAI, npc_fos_leader_second::npc_fos_leader_secondAI, npc_concentrated_ball::npc_concentrated_ballAI, boss_grand_champion::boss_grand_championAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_taldaram::boss_taldaramAI, npc_taldaram_flamesphere::npc_taldaram_flamesphereAI, npc_twilight_volunteer::npc_twilight_volunteerAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_stillpine_capitive::npc_stillpine_capitiveAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_hive_zara_larva::npc_hive_zara_larvaAI, boss_ayamiss::boss_ayamissAI, npc_belnistrasz::npc_belnistraszAI, boss_onyxia::boss_onyxiaAI, boss_captain_skarloc::boss_captain_skarlocAI, boss_mandokir::boss_mandokirAI, boss_nalorakk::boss_nalorakkAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_unworthy_initiate::npc_unworthy_initiateAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_nightbane::boss_nightbaneAI, boss_nefarian::boss_nefarianAI, boss_rend_blackhand::boss_rend_blackhandAI, npc_forest_frog::npc_forest_frogAI, npc_spirit_shade::npc_spirit_shadeAI, PetAI, npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI, boss_algalon_the_observer::boss_algalon_the_observerAI, SmartAI, npc_tooga::npc_toogaAI, and FollowerAI.
Definition at line 133 of file CreatureAI.h.
 {}
Referenced by RotateMovementGenerator::Finalize(), EffectMovementGenerator::Finalize(), WaypointMovementGenerator< Creature >::MovementInform(), and SplineHandler::operator()().
OnCharmed()
void CreatureAI::OnCharmed (bool apply) override virtual
Implements UnitAI.
Reimplemented in npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_assembly_lightning::npc_assembly_lightningAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, and SmartAI.
Definition at line 45 of file CreatureAI.cpp.
 {
     //me->IsAIEnabled = !apply;*/
     me->NeedChangeAI = true;
     me->IsAIEnabled = false;
 }
References Unit::IsAIEnabled, me, and Unit::NeedChangeAI.
Referenced by Unit::SetCharmedBy().
OnSpellClick()
virtual void CreatureAI::OnSpellClick (Unit * , bool &) inline virtual
Reimplemented in SmartAI, boss_flame_leviathan_overload_device::boss_flame_leviathan_overload_deviceAI, and npc_valithria_portal::npc_valithria_portalAI.
Definition at line 174 of file CreatureAI.h.
 { }
Referenced by Unit::HandleSpellClick().
OwnerAttacked()
virtual void CreatureAI::OwnerAttacked (Unit *) inline virtual
Reimplemented in npc_pet_gen_valkyr_guardian, and PetAI.
Definition at line 149 of file CreatureAI.h.
 {}
OwnerAttackedBy()
virtual void CreatureAI::OwnerAttackedBy (Unit *) inline virtual
Reimplemented in npc_scarlet_ghoul::npc_scarlet_ghoulAI, and PetAI.
Definition at line 146 of file CreatureAI.h.
 {}
Referenced by Unit::DealDamage().
PassengerBoarded()
virtual void CreatureAI::PassengerBoarded (Unit * , int8 , bool) inline virtual
== Fields =======================================
Reimplemented in npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI, npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI, boss_kologarn::boss_kologarnAI, npc_hover_disk::npc_hover_diskAI, npc_four_car_garage::npc_four_car_garageAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, npc_scarlet_miner_cart::npc_scarlet_miner_cartAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, SmartAI, npc_vics_flying_machine::npc_vics_flying_machineAI, npc_oculus_drake::npc_oculus_drakeAI, npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI, npc_vortex_ride::npc_vortex_rideAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_wild_wyrm::npc_wild_wyrmAI, boss_kologarn_arms::boss_kologarn_armsAI, and npc_scarlet_cannon::npc_scarlet_cannonAI.
Definition at line 172 of file CreatureAI.h.
 {}
Referenced by Vehicle::AddPassenger(), and Vehicle::RemovePassenger().
ReceiveEmote()
virtual void CreatureAI::ReceiveEmote (Player * , uint32) inline virtual
Reimplemented in npc_plucky::npc_pluckyAI, SmartAI, PetAI, npc_dancing_flames::npc_dancing_flamesAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_pet_gen_mojo, npc_lake_frog::npc_lake_frogAI, npc_shenthul::npc_shenthulAI, and npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI.
Definition at line 143 of file CreatureAI.h.
 {}
SetGazeOn()
void CreatureAI::SetGazeOn (Unit * target) protected
Definition at line 243 of file CreatureAI.cpp.
 {
     if (me->IsValidAttackTarget(target))
     {
         AttackStart(target);
         me->SetReactState(REACT_PASSIVE);
     }
 }
References UnitAI::AttackStart(), Unit::IsValidAttackTarget(), me, REACT_PASSIVE, and Creature::SetReactState().
Referenced by boss_gluth::boss_gluthAI::MoveInLineOfSight(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MySelectNextTarget(), and npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI().
SpellHit()
virtual void CreatureAI::SpellHit (Unit * , SpellInfo const *) inline virtual
Reimplemented in SmartAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, npc_spitelashes::npc_spitelashesAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_midsummer_torch_target::npc_midsummer_torch_targetAI, npc_greengill_slave::npc_greengill_slaveAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_injured_patient::npc_injured_patientAI, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_venture_co_straggler::npc_venture_co_stragglerAI, npc_living_constellation::npc_living_constellationAI, boss_razuvious::boss_razuviousAI, boss_sister_svalna::boss_sister_svalnaAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI, boss_ossirian::boss_ossirianAI, npc_zulian_prowler::npc_zulian_prowlerAI, npc_forest_frog::npc_forest_frogAI, npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_iron_watcher::npc_iron_watcherAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_attracted_reef_bull::npc_attracted_reef_bullAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, boss_thorim::boss_thorimAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_magus_telestra::boss_magus_telestraAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, boss_headless_horseman_head::boss_headless_horseman_headAI, npc_hallows_end_train_fire::npc_hallows_end_train_fireAI, npc_soh_fire_trigger::npc_soh_fire_triggerAI, npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI, PetAI, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI, npc_nether_drake::npc_nether_drakeAI, npc_storm_cloud::npc_storm_cloudAI, npc_drakuru_shackles::npc_drakuru_shacklesAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_wounded_skirmisher::npc_wounded_skirmisherAI, npc_outhouse_bunny::npc_outhouse_bunnyAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI, boss_razorscale::boss_razorscaleAI, boss_ignis::boss_ignisAI, boss_faerlina::boss_faerlinaAI, boss_jaraxxus::boss_jaraxxusAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_zuljin_vortex::npc_zuljin_vortexAI, npc_yenniku::npc_yennikuAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_death_knight_initiate::npc_death_knight_initiateAI, boss_twinemperorsAI, npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI, npc_midsummer_bonfire::npc_midsummer_bonfireAI, boss_majordomo::boss_majordomoAI, npc_venomhide_hatchling::npc_venomhide_hatchlingAI, npc_vics_flying_machine::npc_vics_flying_machineAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, npc_argent_captainAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, npc_putricide_oozeAI, npc_cult_adherent::npc_cult_adherentAI, npc_cult_fanatic::npc_cult_fanaticAI, npc_saurfang_event::npc_saurfang_eventAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_viscidus::boss_viscidusAI, npc_crate_helper::npc_crate_helperAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, ScriptedAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, boss_yoggsaron::boss_yoggsaronAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_pillar::boss_thorim_pillarAI, npc_pool_of_tar::npc_pool_of_tarAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, boss_gothik::boss_gothikAI, npc_pilgrims_bounty_plate::npc_pilgrims_bounty_plateAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI, boss_headless_horseman::boss_headless_horsemanAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, npc_franklin::npc_franklinAI, npc_nelson::npc_nelsonAI, npc_simone::npc_simoneAI, npc_artorius::npc_artoriusAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_captured_rageclaw::npc_captured_rageclawAI, npc_ichor_globule::npc_ichor_globuleAI, npc_ulduar_flames_spread::npc_ulduar_flames_spreadAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI, boss_ionar::boss_ionarAI, boss_urom::boss_uromAI, boss_malygos::boss_malygosAI, npc_frost_sphere::npc_frost_sphereAI, boss_grand_champion::boss_grand_championAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, boss_eadric::boss_eadricAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_omen::npc_omenAI, npc_harrison_jones::npc_harrison_jonesAI, npc_janalai_egg::npc_janalai_eggAI, npc_janalai_firebomb::npc_janalai_firebombAI, boss_halazzi::boss_halazziAI, npc_mograine::npc_mograineAI, boss_julianne::boss_julianneAI, boss_strawman::boss_strawmanAI, boss_shade_of_aran::boss_aranAI, netherspite_infernal::netherspite_infernalAI, npc_ringo::npc_ringoAI, npc_kerlonian::npc_kerlonianAI, npc_mistress_of_pain::npc_mistress_of_painAI, and TotemAI.
Definition at line 120 of file CreatureAI.h.
 {}
Referenced by Spell::DoAllEffectOnTarget().
SpellHitTarget()
virtual void CreatureAI::SpellHitTarget (Unit * , SpellInfo const *) inline virtual
Reimplemented in boss_lethon::boss_lethonAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_oculus_drake::npc_oculus_drakeAI, boss_sister_svalna::boss_sister_svalnaAI, boss_sindragosa::boss_sindragosaAI, boss_rotface::boss_rotfaceAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_festergut::boss_festergutAI, npc_pet_gen_fetch_ball, npc_pet_gen_soul_trader_beacon, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, boss_emalon::boss_emalonAI, boss_skadi_grauf::boss_skadi_graufAI, boss_yoggsaron_voice::boss_yoggsaron_voiceAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_heart::npc_xt002_heartAI, boss_thorim::boss_thorimAI, boss_sapphiron::boss_sapphironAI, boss_grobbulus::boss_grobbulusAI, boss_epoch::boss_epochAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, boss_headless_horseman::boss_headless_horsemanAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_attumen::boss_attumenAI, SmartAI, npc_simon_bunny::npc_simon_bunnyAI, boss_cyanigosa::boss_cyanigosaAI, npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, boss_freya::boss_freyaAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, boss_lord_marrowgar, npc_pos_leader_second::npc_pos_leader_secondAI, npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI, boss_ick::boss_ickAI, npc_hor_lich_king::npc_hor_lich_kingAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, boss_onyxia::boss_onyxiaAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, boss_the_lich_king::boss_the_lich_kingAI, npc_putricide_oozeAI, npc_vengeful_shade::npc_vengeful_shadeAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, ScriptedAI, boss_ymiron::boss_ymironAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_volkhan::boss_volkhanAI, boss_moorabi::boss_moorabiAI, boss_taldaram::boss_taldaramAI, boss_headless_horseman_head::boss_headless_horseman_headAI, npc_demonic_vapor_trail::npc_demonic_vapor_trailAI, boss_quartermaster_zigris, npc_kurenai_captive::npc_kurenai_captiveAI, npc_maghar_captive::npc_maghar_captiveAI, boss_garfrost::boss_garfrostAI, boss_bronjahm::boss_bronjahmAI, and boss_black_knight::boss_black_knightAI.
Definition at line 123 of file CreatureAI.h.
 {}
Referenced by Spell::DoAllEffectOnTarget().
SummonedCreatureDespawn()
virtual void CreatureAI::SummonedCreatureDespawn (Creature *) inline virtual
Reimplemented in SmartAI, hyjalAI, pyrewood_ambush::pyrewood_ambushAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_ahune::boss_ahuneAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_supremus::boss_supremusAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, boss_grobbulus::boss_grobbulusAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, boss_sindragosa::boss_sindragosaAI, npc_precious_icc::npc_precious_iccAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_medivh_bm::npc_medivh_bmAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_necromancer::npc_necromancerAI, boss_zuljin::boss_zuljinAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, WorldBossAI, BossAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_mimiron::boss_mimironAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_leader::npc_pos_leaderAI, npc_hor_lich_king::npc_hor_lich_kingAI, boss_twin_valkyrAI, npc_vh_void_sentry::npc_vh_void_sentryAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_ichoron::boss_ichoronAI, npc_cork_gizelton::npc_cork_gizeltonAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_xt002::boss_xt002AI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_freya_ward::npc_freya_wardAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_gothik::boss_gothikAI, boss_anubrekhan::boss_anubrekhanAI, npc_arthas::npc_arthasAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, and ScriptedAI.
Definition at line 115 of file CreatureAI.h.
 {}
Referenced by TempSummon::UnSummon().
SummonedCreatureDespawnAll()
virtual void CreatureAI::SummonedCreatureDespawnAll () inline virtual
Reimplemented in BossAI.
Definition at line 117 of file CreatureAI.h.
 {}
Referenced by Creature::DespawnOnEvade().
SummonedCreatureDies()
virtual void CreatureAI::SummonedCreatureDies (Creature * , Unit *) inline virtual
Reimplemented in boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_amanitar::boss_amanitarAI, boss_vexallus::boss_vexallusAI, boss_kaelthas::boss_kaelthasAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_the_black_stalker::boss_the_black_stalkerAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, npc_creature_generator_akama::npc_creature_generator_akamaAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_anzu::boss_anzuAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, boss_the_lich_king::boss_the_lich_kingAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_krik_thir::boss_krik_thirAI, boss_elder_nadox::boss_elder_nadoxAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_kiljaeden_controller::npc_kiljaeden_controllerAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_midnight::boss_midnightAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, boss_victor_nefarius::boss_victor_nefariusAI, npc_grimstone::npc_grimstoneAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_emalon::boss_emalonAI, boss_auriaya::boss_auriayaAI, boss_gluth::boss_gluthAI, boss_anubrekhan::boss_anubrekhanAI, npc_arthas::npc_arthasAI, npc_nelson::npc_nelsonAI, boss_taerar::boss_taerarAI, boss_loatheb::boss_loathebAI, boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_sartharion_shadron::boss_sartharion_shadronAI, boss_priestess_delrissa::boss_priestess_delrissaAI, and boss_rend_blackhand::boss_rend_blackhandAI.
Definition at line 116 of file CreatureAI.h.
 {}
Referenced by boss_amanitar::boss_amanitarAI::SummonedCreatureDies().
Talk()
void CreatureAI::Talk (uint8 id, WorldObject const * whisperTarget = nullptr)
Definition at line 55 of file CreatureAI.cpp.
 {
     sCreatureTextMgr->SendChat(me, id, whisperTarget);
 }
References me, and sCreatureTextMgr.
Referenced by npc_mograine::npc_mograineAI::AshbringerEvent(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::AttackStart(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_meathook::boss_meathookAI::boss_meathookAI(), boss_salramm::boss_salrammAI::boss_salrammAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_buru::boss_buruAI::ChaseNewVictim(), npc_ringo::npc_ringoAI::ClearFaint(), npc_kerlonian::npc_kerlonianAI::ClearSleeping(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DamageTaken(), boss_ysondre::boss_ysondreAI::DamageTaken(), boss_lethon::boss_lethonAI::DamageTaken(), boss_emeriss::boss_emerissAI::DamageTaken(), boss_taerar::boss_taerarAI::DamageTaken(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::DamageTaken(), boss_baron_geddon::boss_baron_geddonAI::DamageTaken(), npc_core_rager::npc_core_ragerAI::DamageTaken(), npc_mc_core_hound::npc_mc_core_houndAI::DamageTaken(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken(), boss_essence_of_desire::boss_essence_of_desireAI::DamageTaken(), boss_viscidus::boss_viscidusAI::DamageTaken(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), boss_falric::boss_falricAI::DoAction(), boss_marwyn::boss_marwynAI::DoAction(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_razorgore::boss_razorgoreAI::DoAction(), npc_dkc1_gothik::npc_dkc1_gothikAI::DoAction(), npc_eris_hevenfire::npc_eris_hevenfireAI::DoAction(), npc_direbrew_antagonist::npc_direbrew_antagonistAI::DoAction(), npc_twilight_volunteer::npc_twilight_volunteerAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_xerestrasza::npc_xerestraszaAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_sister_svalna::boss_sister_svalnaAI::DoAction(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::DoAction(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::DoAction(), boss_sacrolash::boss_sacrolashAI::DoAction(), boss_alythess::boss_alythessAI::DoAction(), boss_kalecgos::boss_kalecgosAI::DoAction(), boss_kiljaeden::boss_kiljaedenAI::DoAction(), boss_infinite_corruptor::boss_infinite_corruptorAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), boss_paletress::boss_paletressAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), boss_jormungarAI::DoAction(), boss_tharon_ja::boss_tharon_jaAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction(), boss_thaddius_summon::boss_thaddius_summonAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::DoAction(), npc_akama_illidan::npc_akama_illidanAI::DoAction(), boss_illidari_council_memberAI::DoAction(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), boss_nazan::boss_nazanAI::DoAction(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::DoAction(), boss_archimonde::boss_archimondeAI::DoCastDoomfire(), npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), npc_ranshalla::npc_ranshallaAI::DoContinueEscort(), boss_ichoron::boss_ichoronAI::DoExplodeCompleted(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::DoNice(), npc_earthmender_wilda::npc_earthmender_wildaAI::DoRandomSay(), npc_muglash::npc_muglashAI::DoWaveSummon(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_sartharion_dragonAI::EnterCombat(), boss_balinda::boss_balindaAI::EnterCombat(), boss_drekthar::boss_drektharAI::EnterCombat(), boss_galvangar::boss_galvangarAI::EnterCombat(), boss_vanndar::boss_vanndarAI::EnterCombat(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::EnterCombat(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::EnterCombat(), boss_nefarian::boss_nefarianAI::EnterCombat(), boss_majordomo::boss_majordomoAI::EnterCombat(), boss_attumen::boss_attumenAI::EnterCombat(), boss_nightbane::boss_nightbaneAI::EnterCombat(), boss_malchezaar::boss_malchezaarAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), boss_terestian_illhoof::boss_terestianAI::EnterCombat(), boss_dorothee::boss_dorotheeAI::EnterCombat(), boss_priestess_delrissa::boss_priestess_delrissaAI::EnterCombat(), boss_selin_fireheart::boss_selin_fireheartAI::EnterCombat(), boss_vexallus::boss_vexallusAI::EnterCombat(), npc_crusade_persuaded::npc_crusade_persuadedAI::EnterCombat(), npc_scarlet_courier::npc_scarlet_courierAI::EnterCombat(), npc_mograine::npc_mograineAI::EnterCombat(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::EnterCombat(), boss_kalec::boss_kalecAI::EnterCombat(), boss_sathrovarr::boss_sathrovarrAI::EnterCombat(), boss_kiljaeden::boss_kiljaedenAI::EnterCombat(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::EnterCombat(), boss_twilight_corrupter::boss_twilight_corrupterAI::EnterCombat(), boss_akilzon::boss_akilzonAI::EnterCombat(), boss_halazzi::boss_halazziAI::EnterCombat(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), boss_janalai::boss_janalaiAI::EnterCombat(), boss_nalorakk::boss_nalorakkAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterCombat(), boss_arlokk::boss_arlokkAI::EnterCombat(), boss_hakkar::boss_hakkarAI::EnterCombat(), boss_jeklik::boss_jeklikAI::EnterCombat(), boss_jindo::boss_jindoAI::EnterCombat(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_marli::boss_marliAI::EnterCombat(), boss_thekal::boss_thekalAI::EnterCombat(), npc_hallows_end_soh::npc_hallows_end_sohAI::EnterCombat(), boss_anetheron::boss_anetheronAI::EnterCombat(), boss_archimonde::boss_archimondeAI::EnterCombat(), boss_azgalor::boss_azgalorAI::EnterCombat(), boss_kazrogal::boss_kazrogalAI::EnterCombat(), boss_rage_winterchill::boss_rage_winterchillAI::EnterCombat(), hyjalAI::EnterCombat(), boss_epoch::boss_epochAI::EnterCombat(), boss_infinite_corruptor::boss_infinite_corruptorAI::EnterCombat(), boss_mal_ganis::boss_mal_ganisAI::EnterCombat(), boss_meathook::boss_meathookAI::EnterCombat(), boss_salramm::boss_salrammAI::EnterCombat(), boss_epoch_hunter::boss_epoch_hunterAI::EnterCombat(), boss_lieutenant_drake::boss_lieutenant_drakeAI::EnterCombat(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::EnterCombat(), boss_aeonus::boss_aeonusAI::EnterCombat(), boss_onyxia::boss_onyxiaAI::EnterCombat(), boss_ossirian::boss_ossirianAI::EnterCombat(), boss_sartura::boss_sarturaAI::EnterCombat(), boss_skeram::boss_skeramAI::EnterCombat(), npc_muglash::npc_muglashAI::EnterCombat(), boss_elder_nadox::boss_elder_nadoxAI::EnterCombat(), boss_volazj::boss_volazjAI::EnterCombat(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::EnterCombat(), boss_taldaram::boss_taldaramAI::EnterCombat(), boss_anub_arak::boss_anub_arakAI::EnterCombat(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::EnterCombat(), boss_eadric::boss_eadricAI::EnterCombat(), boss_paletress::boss_paletressAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_jaraxxus::boss_jaraxxusAI::EnterCombat(), boss_twin_valkyrAI::EnterCombat(), boss_bronjahm::boss_bronjahmAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_frostsworn_general::boss_frostsworn_generalAI::EnterCombat(), boss_garfrost::boss_garfrostAI::EnterCombat(), npc_darnavan::npc_darnavanAI::EnterCombat(), boss_lord_marrowgar::EnterCombat(), boss_malygos::boss_malygosAI::EnterCombat(), boss_drakos::boss_drakosAI::EnterCombat(), boss_eregos::boss_eregosAI::EnterCombat(), boss_urom::boss_uromAI::EnterCombat(), boss_varos::boss_varosAI::EnterCombat(), boss_bjarngrim::boss_bjarngrimAI::EnterCombat(), boss_ionar::boss_ionarAI::EnterCombat(), boss_loken::boss_lokenAI::EnterCombat(), boss_volkhan::boss_volkhanAI::EnterCombat(), boss_krystallus::boss_krystallusAI::EnterCombat(), boss_maiden_of_grief::boss_maiden_of_griefAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat(), boss_hodir::boss_hodirAI::EnterCombat(), boss_kologarn::boss_kologarnAI::EnterCombat(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::EnterCombat(), boss_keleseth::boss_kelesethAI::EnterCombat(), boss_skadi::boss_skadiAI::EnterCombat(), boss_svala::boss_svalaAI::EnterCombat(), boss_ymiron::boss_ymironAI::EnterCombat(), boss_cyanigosa::boss_cyanigosaAI::EnterCombat(), boss_ichoron::boss_ichoronAI::EnterCombat(), boss_xevozz::boss_xevozzAI::EnterCombat(), boss_zuramat::boss_zuramatAI::EnterCombat(), npc_emily::npc_emilyAI::EnterCombat(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterCombat(), boss_exarch_maladaar::boss_exarch_maladaarAI::EnterCombat(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::EnterCombat(), boss_pandemonius::boss_pandemoniusAI::EnterCombat(), boss_talon_king_ikiss::boss_talon_king_ikissAI::EnterCombat(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::EnterCombat(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::EnterCombat(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::EnterCombat(), boss_essence_of_suffering::boss_essence_of_sufferingAI::EnterCombat(), boss_essence_of_desire::boss_essence_of_desireAI::EnterCombat(), boss_essence_of_anger::boss_essence_of_angerAI::EnterCombat(), boss_doomlord_kazzak::boss_doomlordkazzakAI::EnterCombat(), boss_doomwalker::boss_doomwalkerAI::EnterCombat(), boss_hydromancer_thespia::boss_thespiaAI::EnterCombat(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::EnterCombat(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::EnterCombat(), boss_gruul::boss_gruulAI::EnterCombat(), boss_high_king_maulgar::boss_high_king_maulgarAI::EnterCombat(), boss_broggok::boss_broggokAI::EnterCombat(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::EnterCombat(), boss_the_maker::boss_the_makerAI::EnterCombat(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::EnterCombat(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::EnterCombat(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::EnterCombat(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::EnterCombat(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::EnterCombat(), boss_commander_sarannis::boss_commander_sarannisAI::EnterCombat(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::EnterCombat(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::EnterCombat(), boss_warp_splinter::boss_warp_splinterAI::EnterCombat(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::EnterCombat(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::EnterCombat(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::EnterCombat(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::EnterCombat(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::EnterCombat(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_broodlord::boss_broodlordAI::EnterCombat(), boss_curator::boss_curatorAI::EnterCombat(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::EnterCombat(), boss_moroes::boss_moroesAI::EnterCombat(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::EnterCombat(), boss_brutallus::boss_brutallusAI::EnterCombat(), boss_kalecgos::boss_kalecgosAI::EnterCombat(), npc_rinji::npc_rinjiAI::EnterCombat(), npc_deathstalker_erland::npc_deathstalker_erlandAI::EnterCombat(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::EnterCombat(), npc_direbrew_antagonist::npc_direbrew_antagonistAI::EnterCombat(), npc_belnistrasz::npc_belnistraszAI::EnterCombat(), boss_buru::boss_buruAI::EnterCombat(), npc_magwin::npc_magwinAI::EnterCombat(), npc_prospector_remtravel::npc_prospector_remtravelAI::EnterCombat(), npc_aquementas::npc_aquementasAI::EnterCombat(), npc_gilthares::npc_giltharesAI::EnterCombat(), boss_krik_thir::boss_krik_thirAI::EnterCombat(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::EnterCombat(), boss_general_zarithrian::boss_general_zarithrianAI::EnterCombat(), boss_halion::boss_halionAI::EnterCombat(), boss_saviana_ragefire::boss_saviana_ragefireAI::EnterCombat(), boss_novos::boss_novosAI::EnterCombat(), boss_tharon_ja::boss_tharon_jaAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_gal_darah::boss_gal_darahAI::EnterCombat(), boss_moorabi::boss_moorabiAI::EnterCombat(), boss_slad_ran::boss_slad_ranAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_four_horsemen::boss_four_horsemenAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_heigan::boss_heiganAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), boss_noth::boss_nothAI::EnterCombat(), boss_patchwerk::boss_patchwerkAI::EnterCombat(), boss_razuvious::boss_razuviousAI::EnterCombat(), boss_anomalus::boss_anomalusAI::EnterCombat(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::EnterCombat(), boss_keristrasza::boss_keristraszaAI::EnterCombat(), boss_magus_telestra::boss_magus_telestraAI::EnterCombat(), boss_ormorok::boss_ormorokAI::EnterCombat(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), npc_torturer_lecraft::npc_torturer_lecraftAI::EnterCombat(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::EnterCombat(), boss_mother_shahraz::boss_shahrazAI::EnterCombat(), boss_najentus::boss_najentusAI::EnterCombat(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::EnterCombat(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::EnterCombat(), boss_lady_vashj::boss_lady_vashjAI::EnterCombat(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::EnterCombat(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::EnterCombat(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::EnterCombat(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::EnterCombat(), boss_void_reaver::boss_void_reaverAI::EnterCombat(), npc_earthmender_wilda::npc_earthmender_wildaAI::EnterCombat(), boss_ysondre::boss_ysondreAI::EnterCombat(), boss_lethon::boss_lethonAI::EnterCombat(), boss_emeriss::boss_emerissAI::EnterCombat(), boss_taerar::boss_taerarAI::EnterCombat(), boss_vazruden::boss_vazrudenAI::EnterEvadeMode(), boss_halazzi::boss_halazziAI::EnterPhase(), boss_zuljin::boss_zuljinAI::EnterPhase(), npc_unworthy_initiate::npc_unworthy_initiateAI::EventStart(), DelayedTalk::Execute(), UtherBatteredHiltEvent::Execute(), CaptainSurviveTalk::Execute(), ChargeRifts::Execute(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_hallows_end_soh::npc_hallows_end_sohAI::FinishEvent(), boss_volkhan::boss_volkhanAI::GoToAnvil(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::GotStinged(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), spell_item_lil_xt::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::HandleExtraEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::HandleExtraEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::HandleExtraEvent(), boss_malygos::boss_malygosAI::HandleIntroSpeech(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_volazj_whisper::spell_volazj_whisper_SpellScript::HandleScriptEffect(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::InitializeAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_aeonus::boss_aeonusAI::InitializeAI(), boss_rend_blackhand::boss_rend_blackhandAI::IsSummonedBy(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_halycon::boss_halyconAI::JustDied(), boss_nefarian::boss_nefarianAI::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_attumen_midnight::boss_attumen_midnightAI::JustDied(), boss_malchezaar::boss_malchezaarAI::JustDied(), boss_shade_of_aran::boss_aranAI::JustDied(), boss_terestian_illhoof::boss_terestianAI::JustDied(), boss_dorothee::boss_dorotheeAI::JustDied(), npc_tito::npc_titoAI::JustDied(), boss_priestess_delrissa::boss_priestess_delrissaAI::JustDied(), boss_selin_fireheart::boss_selin_fireheartAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), boss_sathrovarr::boss_sathrovarrAI::JustDied(), boss_kiljaeden::boss_kiljaedenAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_halazzi::boss_halazziAI::JustDied(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustDied(), boss_janalai::boss_janalaiAI::JustDied(), boss_nalorakk::boss_nalorakkAI::JustDied(), boss_zuljin::boss_zuljinAI::JustDied(), boss_arlokk::boss_arlokkAI::JustDied(), boss_jeklik::boss_jeklikAI::JustDied(), boss_marli::boss_marliAI::JustDied(), boss_thekal::boss_thekalAI::JustDied(), boss_venoxis::boss_venoxisAI::JustDied(), npc_hallows_end_soh::npc_hallows_end_sohAI::JustDied(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustDied(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::JustDied(), boss_archimonde::boss_archimondeAI::JustDied(), hyjalAI::JustDied(), boss_epoch::boss_epochAI::JustDied(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), boss_meathook::boss_meathookAI::JustDied(), boss_salramm::boss_salrammAI::JustDied(), boss_captain_skarloc::boss_captain_skarlocAI::JustDied(), boss_lieutenant_drake::boss_lieutenant_drakeAI::JustDied(), boss_aeonus::boss_aeonusAI::JustDied(), npc_medivh_bm::npc_medivh_bmAI::JustDied(), boss_sartura::boss_sarturaAI::JustDied(), boss_skeram::boss_skeramAI::JustDied(), boss_elder_nadox::boss_elder_nadoxAI::JustDied(), boss_volazj::boss_volazjAI::JustDied(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::JustDied(), boss_taldaram::boss_taldaramAI::JustDied(), boss_sartharion::boss_sartharionAI::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_black_knight::boss_black_knightAI::JustDied(), boss_anubarak_trial::boss_anubarak_trialAI::JustDied(), boss_jaraxxus::boss_jaraxxusAI::JustDied(), boss_twin_valkyrAI::JustDied(), boss_bronjahm::boss_bronjahmAI::JustDied(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustDied(), boss_falric::boss_falricAI::JustDied(), boss_marwyn::boss_marwynAI::JustDied(), boss_frostsworn_general::boss_frostsworn_generalAI::JustDied(), boss_garfrost::boss_garfrostAI::JustDied(), boss_tyrannus::boss_tyrannusAI::JustDied(), boss_drakkari_elemental::boss_drakkari_elementalAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_lord_marrowgar::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), npc_argent_captainAI::JustDied(), boss_thaddius_summon::boss_thaddius_summonAI::JustDied(), boss_malygos::boss_malygosAI::JustDied(), boss_drakos::boss_drakosAI::JustDied(), boss_eregos::boss_eregosAI::JustDied(), boss_urom::boss_uromAI::JustDied(), boss_varos::boss_varosAI::JustDied(), boss_bjarngrim::boss_bjarngrimAI::JustDied(), boss_ionar::boss_ionarAI::JustDied(), boss_loken::boss_lokenAI::JustDied(), boss_volkhan::boss_volkhanAI::JustDied(), boss_krystallus::boss_krystallusAI::JustDied(), boss_maiden_of_grief::boss_maiden_of_griefAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_steelbreaker::boss_steelbreakerAI::JustDied(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustDied(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustDied(), boss_keleseth::boss_kelesethAI::JustDied(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::JustDied(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustDied(), boss_skadi::boss_skadiAI::JustDied(), boss_svala::boss_svalaAI::JustDied(), boss_ymiron::boss_ymironAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), boss_erekem::boss_erekemAI::JustDied(), boss_ichoron::boss_ichoronAI::JustDied(), boss_xevozz::boss_xevozzAI::JustDied(), boss_zuramat::boss_zuramatAI::JustDied(), npc_q24545_vegard::npc_q24545_vegardAI::JustDied(), boss_exarch_maladaar::boss_exarch_maladaarAI::JustDied(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustDied(), boss_pandemonius::boss_pandemoniusAI::JustDied(), boss_talon_king_ikiss::boss_talon_king_ikissAI::JustDied(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::JustDied(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::JustDied(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustDied(), boss_essence_of_anger::boss_essence_of_angerAI::JustDied(), boss_illidari_council_memberAI::JustDied(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustDied(), boss_doomwalker::boss_doomwalkerAI::JustDied(), boss_hydromancer_thespia::boss_thespiaAI::JustDied(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::JustDied(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::JustDied(), boss_gruul::boss_gruulAI::JustDied(), boss_high_king_maulgar::boss_high_king_maulgarAI::JustDied(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::JustDied(), boss_the_maker::boss_the_makerAI::JustDied(), boss_vazruden::boss_vazrudenAI::JustDied(), boss_magtheridon::boss_magtheridonAI::JustDied(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustDied(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustDied(), npc_millhouse_manastorm::npc_millhouse_manastormAI::JustDied(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::JustDied(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::JustDied(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::JustDied(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::JustDied(), boss_commander_sarannis::boss_commander_sarannisAI::JustDied(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::JustDied(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::JustDied(), boss_warp_splinter::boss_warp_splinterAI::JustDied(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::JustDied(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::JustDied(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::JustDied(), boss_curator::boss_curatorAI::JustDied(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::JustDied(), boss_moroes::boss_moroesAI::JustDied(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::JustDied(), boss_brutallus::boss_brutallusAI::JustDied(), boss_felmyst::boss_felmystAI::JustDied(), boss_anetheron::boss_anetheronAI::JustDied(), boss_azgalor::boss_azgalorAI::JustDied(), boss_rage_winterchill::boss_rage_winterchillAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), boss_anub_arak::boss_anub_arakAI::JustDied(), boss_krik_thir::boss_krik_thirAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_general_zarithrian::boss_general_zarithrianAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_novos::boss_novosAI::JustDied(), boss_tharon_ja::boss_tharon_jaAI::JustDied(), boss_trollgore::boss_trollgoreAI::JustDied(), boss_gal_darah::boss_gal_darahAI::JustDied(), boss_moorabi::boss_moorabiAI::JustDied(), boss_slad_ran::boss_slad_ranAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_heigan::boss_heiganAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_patchwerk::boss_patchwerkAI::JustDied(), boss_razuvious::boss_razuviousAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_anomalus::boss_anomalusAI::JustDied(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::JustDied(), boss_keristrasza::boss_keristraszaAI::JustDied(), boss_magus_telestra::boss_magus_telestraAI::JustDied(), boss_ormorok::boss_ormorokAI::JustDied(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustDied(), boss_mother_shahraz::boss_shahrazAI::JustDied(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustDied(), boss_najentus::boss_najentusAI::JustDied(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustDied(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustDied(), boss_lady_vashj::boss_lady_vashjAI::JustDied(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustDied(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustDied(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustDied(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::JustDied(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustDied(), boss_kaelthas::boss_kaelthasAI::JustDied(), boss_void_reaver::boss_void_reaverAI::JustDied(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::JustReachedHome(), boss_drekthar::boss_drektharAI::JustRespawned(), boss_doomlord_kazzak::boss_doomlordkazzakAI::JustRespawned(), boss_anubrekhan::boss_anubrekhanAI::JustSummoned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustSummoned(), boss_terestian_illhoof::boss_terestianAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_kurenai_captive::npc_kurenai_captiveAI::JustSummoned(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::KilledUnit(), boss_curator::boss_curatorAI::KilledUnit(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::KilledUnit(), boss_attumen::boss_attumenAI::KilledUnit(), boss_attumen_midnight::boss_attumen_midnightAI::KilledUnit(), boss_moroes::boss_moroesAI::KilledUnit(), boss_malchezaar::boss_malchezaarAI::KilledUnit(), boss_shade_of_aran::boss_aranAI::KilledUnit(), boss_terestian_illhoof::boss_terestianAI::KilledUnit(), npc_mograine::npc_mograineAI::KilledUnit(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::KilledUnit(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::KilledUnit(), boss_janalai::boss_janalaiAI::KilledUnit(), boss_nalorakk::boss_nalorakkAI::KilledUnit(), boss_zuljin::boss_zuljinAI::KilledUnit(), boss_azgalor::boss_azgalorAI::KilledUnit(), boss_kazrogal::boss_kazrogalAI::KilledUnit(), boss_rage_winterchill::boss_rage_winterchillAI::KilledUnit(), boss_epoch::boss_epochAI::KilledUnit(), boss_mal_ganis::boss_mal_ganisAI::KilledUnit(), boss_meathook::boss_meathookAI::KilledUnit(), boss_salramm::boss_salrammAI::KilledUnit(), boss_captain_skarloc::boss_captain_skarlocAI::KilledUnit(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::KilledUnit(), boss_ossirian::boss_ossirianAI::KilledUnit(), boss_sartura::boss_sarturaAI::KilledUnit(), boss_skeram::boss_skeramAI::KilledUnit(), boss_anub_arak::boss_anub_arakAI::KilledUnit(), boss_krik_thir::boss_krik_thirAI::KilledUnit(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::KilledUnit(), boss_general_zarithrian::boss_general_zarithrianAI::KilledUnit(), boss_saviana_ragefire::boss_saviana_ragefireAI::KilledUnit(), boss_novos::boss_novosAI::KilledUnit(), boss_tharon_ja::boss_tharon_jaAI::KilledUnit(), boss_trollgore::boss_trollgoreAI::KilledUnit(), boss_gal_darah::boss_gal_darahAI::KilledUnit(), boss_moorabi::boss_moorabiAI::KilledUnit(), boss_slad_ran::boss_slad_ranAI::KilledUnit(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::KilledUnit(), boss_keristrasza::boss_keristraszaAI::KilledUnit(), boss_magus_telestra::boss_magus_telestraAI::KilledUnit(), boss_ormorok::boss_ormorokAI::KilledUnit(), boss_drakos::boss_drakosAI::KilledUnit(), boss_eregos::boss_eregosAI::KilledUnit(), boss_urom::boss_uromAI::KilledUnit(), boss_krystallus::boss_krystallusAI::KilledUnit(), boss_maiden_of_grief::boss_maiden_of_griefAI::KilledUnit(), boss_sjonnir::boss_sjonnirAI::KilledUnit(), boss_kologarn::boss_kologarnAI::KilledUnit(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::KilledUnit(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::KilledUnit(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::KilledUnit(), boss_skadi::boss_skadiAI::KilledUnit(), boss_ymiron::boss_ymironAI::KilledUnit(), boss_exarch_maladaar::boss_exarch_maladaarAI::KilledUnit(), boss_talon_king_ikiss::boss_talon_king_ikissAI::KilledUnit(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::KilledUnit(), boss_illidan_stormrage::boss_illidan_stormrageAI::KilledUnit(), boss_mother_shahraz::boss_shahrazAI::KilledUnit(), boss_essence_of_suffering::boss_essence_of_sufferingAI::KilledUnit(), boss_essence_of_desire::boss_essence_of_desireAI::KilledUnit(), boss_essence_of_anger::boss_essence_of_angerAI::KilledUnit(), boss_teron_gorefiend::boss_teron_gorefiendAI::KilledUnit(), boss_illidari_council_memberAI::KilledUnit(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::KilledUnit(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::KilledUnit(), boss_lady_vashj::boss_lady_vashjAI::KilledUnit(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::KilledUnit(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::KilledUnit(), boss_gruul::boss_gruulAI::KilledUnit(), boss_high_king_maulgar::boss_high_king_maulgarAI::KilledUnit(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::KilledUnit(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::KilledUnit(), boss_vazruden::boss_vazrudenAI::KilledUnit(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::KilledUnit(), boss_magtheridon::boss_magtheridonAI::KilledUnit(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::KilledUnit(), boss_warbringer_omrogg::boss_warbringer_omroggAI::KilledUnit(), npc_millhouse_manastorm::npc_millhouse_manastormAI::KilledUnit(), boss_sartharion::boss_sartharionAI::KilledUnit(), boss_xevozz::boss_xevozzAI::KilledUnit(), boss_sathrovarr::boss_sathrovarrAI::KilledUnit(), boss_sartharion_dragonAI::KilledUnit(), boss_nefarian::boss_nefarianAI::KilledUnit(), boss_vaelastrasz::boss_vaelAI::KilledUnit(), boss_majordomo::boss_majordomoAI::KilledUnit(), boss_ragnaros::boss_ragnarosAI::KilledUnit(), boss_priestess_delrissa::boss_priestess_delrissaAI::KilledUnit(), boss_selin_fireheart::boss_selin_fireheartAI::KilledUnit(), boss_vexallus::boss_vexallusAI::KilledUnit(), boss_brutallus::boss_brutallusAI::KilledUnit(), boss_sacrolash::boss_sacrolashAI::KilledUnit(), boss_alythess::boss_alythessAI::KilledUnit(), boss_felmyst::boss_felmystAI::KilledUnit(), boss_kalecgos::boss_kalecgosAI::KilledUnit(), boss_kiljaeden::boss_kiljaedenAI::KilledUnit(), boss_twilight_corrupter::boss_twilight_corrupterAI::KilledUnit(), boss_halazzi::boss_halazziAI::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_archimonde::boss_archimondeAI::KilledUnit(), boss_epoch_hunter::boss_epoch_hunterAI::KilledUnit(), boss_lieutenant_drake::boss_lieutenant_drakeAI::KilledUnit(), boss_aeonus::boss_aeonusAI::KilledUnit(), boss_elder_nadox::boss_elder_nadoxAI::KilledUnit(), boss_volazj::boss_volazjAI::KilledUnit(), boss_taldaram::boss_taldaramAI::KilledUnit(), boss_halion::boss_halionAI::KilledUnit(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), boss_black_knight::boss_black_knightAI::KilledUnit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::KilledUnit(), boss_prince_keleseth_icc::boss_prince_kelesethAI::KilledUnit(), boss_prince_taldaram_icc::boss_prince_taldaramAI::KilledUnit(), boss_prince_valanar_icc::boss_prince_valanarAI::KilledUnit(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::KilledUnit(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::KilledUnit(), boss_festergut::boss_festergutAI::KilledUnit(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::KilledUnit(), boss_lord_marrowgar::KilledUnit(), boss_professor_putricide::boss_professor_putricideAI::KilledUnit(), boss_rotface::boss_rotfaceAI::KilledUnit(), boss_sindragosa::boss_sindragosaAI::KilledUnit(), boss_the_lich_king::boss_the_lich_kingAI::KilledUnit(), boss_sister_svalna::boss_sister_svalnaAI::KilledUnit(), npc_argent_captainAI::KilledUnit(), boss_anubrekhan::boss_anubrekhanAI::KilledUnit(), boss_malygos::boss_malygosAI::KilledUnit(), boss_bjarngrim::boss_bjarngrimAI::KilledUnit(), boss_ionar::boss_ionarAI::KilledUnit(), boss_loken::boss_lokenAI::KilledUnit(), boss_volkhan::boss_volkhanAI::KilledUnit(), boss_algalon_the_observer::boss_algalon_the_observerAI::KilledUnit(), boss_palehoof::boss_palehoofAI::KilledUnit(), boss_svala::boss_svalaAI::KilledUnit(), boss_cyanigosa::boss_cyanigosaAI::KilledUnit(), boss_erekem::boss_erekemAI::KilledUnit(), boss_ichoron::boss_ichoronAI::KilledUnit(), boss_zuramat::boss_zuramatAI::KilledUnit(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::KilledUnit(), boss_pandemonius::boss_pandemoniusAI::KilledUnit(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::KilledUnit(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::KilledUnit(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::KilledUnit(), boss_najentus::boss_najentusAI::KilledUnit(), boss_doomlord_kazzak::boss_doomlordkazzakAI::KilledUnit(), boss_doomwalker::boss_doomwalkerAI::KilledUnit(), boss_hydromancer_thespia::boss_thespiaAI::KilledUnit(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::KilledUnit(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::KilledUnit(), boss_the_maker::boss_the_makerAI::KilledUnit(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::KilledUnit(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::KilledUnit(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::KilledUnit(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::KilledUnit(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::KilledUnit(), boss_commander_sarannis::boss_commander_sarannisAI::KilledUnit(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::KilledUnit(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::KilledUnit(), boss_warp_splinter::boss_warp_splinterAI::KilledUnit(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::KilledUnit(), boss_kaelthas::boss_kaelthasAI::KilledUnit(), boss_void_reaver::boss_void_reaverAI::KilledUnit(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::KilledUnit(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::KilledUnit(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::KilledUnit(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::KilledUnit(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::KilledUnit(), boss_akilzon::boss_akilzonAI::KilledUnit(), boss_anetheron::boss_anetheronAI::KilledUnit(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::KilledUnit(), boss_eadric::boss_eadricAI::KilledUnit(), boss_paletress::boss_paletressAI::KilledUnit(), boss_anubarak_trial::boss_anubarak_trialAI::KilledUnit(), boss_twin_valkyrAI::KilledUnit(), boss_bronjahm::boss_bronjahmAI::KilledUnit(), boss_falric::boss_falricAI::KilledUnit(), boss_marwyn::boss_marwynAI::KilledUnit(), boss_garfrost::boss_garfrostAI::KilledUnit(), boss_tyrannus::boss_tyrannusAI::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_four_horsemen::boss_four_horsemenAI::KilledUnit(), boss_gothik::boss_gothikAI::KilledUnit(), boss_heigan::boss_heiganAI::KilledUnit(), boss_kelthuzad::boss_kelthuzadAI::KilledUnit(), boss_noth::boss_nothAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_razuvious::boss_razuviousAI::KilledUnit(), boss_thaddius::boss_thaddiusAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), boss_steelbreaker::boss_steelbreakerAI::KilledUnit(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::KilledUnit(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::KilledUnit(), boss_hodir::boss_hodirAI::KilledUnit(), npc_q24545_vegard::npc_q24545_vegardAI::KilledUnit(), boss_loken::boss_lokenAI::LokenSpeach(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_scarlet_guard::npc_scarlet_guardAI::MoveInLineOfSight(), boss_twilight_corrupter::boss_twilight_corrupterAI::MoveInLineOfSight(), boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight(), npc_coren_direbrew::npc_coren_direbrewAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::MoveInLineOfSight(), boss_aeonus::boss_aeonusAI::MoveInLineOfSight(), npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight(), boss_ossirian::boss_ossirianAI::MoveInLineOfSight(), npc_draenei_survivor::npc_draenei_survivorAI::MoveInLineOfSight(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), boss_anub_arak::boss_anub_arakAI::MoveInLineOfSight(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), boss_lord_marrowgar::MoveInLineOfSight(), boss_anubrekhan::boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlina::boss_faerlinaAI::MoveInLineOfSight(), boss_gluth::boss_gluthAI::MoveInLineOfSight(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::MoveInLineOfSight(), boss_exarch_maladaar::boss_exarch_maladaarAI::MoveInLineOfSight(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_talon_king_ikiss::boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::MoveInLineOfSight(), boss_lady_vashj::boss_lady_vashjAI::MoveInLineOfSight(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::MoveInLineOfSight(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::MoveInLineOfSight(), boss_kaelthas::boss_kaelthasAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_natrualist_bite::npc_natrualist_biteAI::MoveInLineOfSight(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform(), boss_nightbane::boss_nightbaneAI::MovementInform(), boss_selin_fireheart::boss_selin_fireheartAI::MovementInform(), npc_unworthy_initiate::npc_unworthy_initiateAI::MovementInform(), npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform(), npc_fos_leader_second::npc_fos_leader_secondAI::MovementInform(), boss_garfrost::boss_garfrostAI::MovementInform(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::MovementInform(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::MovementInform(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::MovementInform(), npc_corki::npc_corkiAI::MovementInform(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::MovementInform(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::MovementInform(), boss_saviana_ragefire::boss_saviana_ragefireAI::MovementInform(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform(), boss_ymiron::boss_ymironAI::MovementInform(), boss_icehowl::boss_icehowlAI::MovementInform(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MoveToDock(), npc_adventurous_dwarf::npc_adventurous_dwarfAI::npc_adventurous_dwarfAI(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), go_prince_taldaram_sphere::OnGossipHello(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_adventurous_dwarf::OnGossipSelect(), npc_floon::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), npc_daphne_stilwell::OnQuestAccept(), npc_kerlonian::OnQuestAccept(), npc_gilthares::OnQuestAccept(), npc_lakota_windsong::OnQuestAccept(), npc_paoka_swiftmountain::OnQuestAccept(), npc_engineer_helice::OnQuestAccept(), npc_maghar_captive::OnQuestAccept(), npc_earthmender_wilda::OnQuestAccept(), npc_deathstalker_erland::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_wizzlecrank_shredder::OnQuestAccept(), npc_ame::OnQuestAccept(), npc_ranshalla::OnQuestAccept(), npc_mootoo_the_younger::OnQuestAccept(), npc_bonker_togglevolt::OnQuestAccept(), npc_emily::OnQuestAccept(), npc_bessy::OnQuestAccept(), npc_kayra_longmane::OnQuestAccept(), npc_rocknot::OnQuestReward(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::OwnTalk(), boss_temporus::boss_temporusAI::OwnTalk(), boss_kologarn::boss_kologarnAI::PassengerBoarded(), boss_malchezaar::boss_malchezaarAI::Phase2(), boss_malchezaar::boss_malchezaarAI::Phase3(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), npc_pet_gen_mojo::ReceiveEmote(), npc_chicken_cluck::npc_chicken_cluckAI::ReceiveEmote(), boss_mal_ganis::boss_mal_ganisAI::Reset(), npc_troll_volunteer::npc_troll_volunteerAI::Reset(), npc_blessed_banner::npc_blessed_bannerAI::Reset(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::Reset(), npc_aeranas::npc_aeranasAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::RollStance(), npc_shandy_dalaran::npc_shandy_dalaranAI::RollTask(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), boss_teron_gorefiend::boss_teron_gorefiendAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_ringo::npc_ringoAI::SetFaint(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::SetForm(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID(), npc_kurenai_captive::npc_kurenai_captiveAI::SetGUID(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), npc_kerlonian::npc_kerlonianAI::SetSleeping(), npc_coren_direbrew::npc_coren_direbrewAI::sGossipSelect(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::Shout(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::spawnVoidTraveler(), npc_mograine::npc_mograineAI::SpellHit(), boss_malygos::boss_malygosAI::SpellHit(), boss_urom::boss_uromAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), boss_attumen::boss_attumenAI::SpellHit(), boss_attumen_midnight::boss_attumen_midnightAI::SpellHit(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SpellHit(), boss_viscidus::boss_viscidusAI::SpellHit(), boss_the_lich_king::boss_the_lich_kingAI::SpellHit(), npc_argent_captainAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), boss_faerlina::boss_faerlinaAI::SpellHit(), npc_torturer_lecraft::npc_torturer_lecraftAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), npc_iron_watcher::npc_iron_watcherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), boss_sister_svalna::boss_sister_svalnaAI::SpellHit(), boss_razuvious::boss_razuviousAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_shay_leafrunner::npc_shay_leafrunnerAI::SpellHit(), boss_black_knight::boss_black_knightAI::SpellHitTarget(), boss_garfrost::boss_garfrostAI::SpellHitTarget(), npc_maghar_captive::npc_maghar_captiveAI::SpellHitTarget(), npc_kurenai_captive::npc_kurenai_captiveAI::SpellHitTarget(), boss_moorabi::boss_moorabiAI::SpellHitTarget(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), npc_pet_gen_soul_trader_beacon::SpellHitTarget(), boss_rotface::boss_rotfaceAI::SpellHitTarget(), boss_sister_svalna::boss_sister_svalnaAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), npc_belnistrasz::npc_belnistraszAI::sQuestAccept(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::sQuestAccept(), npc_corporal_keeshan::npc_corporal_keeshanAI::sQuestAccept(), npc_muglash::npc_muglashAI::sQuestAccept(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), hyjalAI::StartEvent(), boss_heigan::boss_heiganAI::StartFightPhase(), npc_stillpine_capitive::npc_stillpine_capitiveAI::StartMoving(), boss_anzu::boss_anzuAI::SummonBroods(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDies(), npc_daphne_stilwell::npc_daphne_stilwellAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), boss_ragnaros::boss_ragnarosAI::SummonMinions(), hyjalAI::SummonNextWave(), boss_dorothee::boss_dorotheeAI::SummonTito(), boss_netherspite::boss_netherspiteAI::SwitchToBanishPhase(), boss_netherspite::boss_netherspiteAI::SwitchToPortalPhase(), boss_nightbane::boss_nightbaneAI::TakeOff(), npc_barnes::npc_barnesAI::Talk(), npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI::Talk(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_midnight::boss_midnightAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), boss_vexallus::boss_vexallusAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_brutallus::boss_brutallusAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), hyjalAI::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_aeonus::boss_aeonusAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_dred::boss_dredAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_loatheb::boss_loathebAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_magus_telestra::boss_magus_telestraAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_jungle_punch_target::npc_jungle_punch_targetAI::UpdateAI(), npc_iron_watcher::npc_iron_watcherAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_wg_queue::npc_wg_queueAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_lady_malande::boss_lady_malandeAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_vazruden::boss_vazrudenAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), npc_omrogg_heads::npc_omrogg_headsAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_commander_sarannis::boss_commander_sarannisAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_laj::boss_lajAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_warp_splinter::boss_warp_splinterAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_void_reaver::boss_void_reaverAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_pet_gen_soul_trader_beacon::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::UpdateEscortAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), npc_captain_saeed::npc_captain_saeedAI::WaypointReached(), npc_ranshalla::npc_ranshallaAI::WaypointReached(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), npc_grimstone::npc_grimstoneAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::WaypointReached(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), npc_rinji::npc_rinjiAI::WaypointReached(), npc_deathstalker_erland::npc_deathstalker_erlandAI::WaypointReached(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::WaypointReached(), npc_tyrion_spybot::npc_tyrion_spybotAI::WaypointReached(), npc_thrall_bfu::npc_thrall_bfuAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), npc_muglash::npc_muglashAI::WaypointReached(), npc_magwin::npc_magwinAI::WaypointReached(), npc_prospector_remtravel::npc_prospector_remtravelAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_kaya_flathoof::npc_kaya_flathoofAI::WaypointReached(), npc_custodian_of_time::npc_custodian_of_timeAI::WaypointReached(), npc_gilthares::npc_giltharesAI::WaypointReached(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointReached(), npc_lakota_windsong::npc_lakota_windsongAI::WaypointReached(), npc_paoka_swiftmountain::npc_paoka_swiftmountainAI::WaypointReached(), npc_ame::npc_ameAI::WaypointReached(), npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached(), npc_mootoo_the_younger::npc_mootoo_the_youngerAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), npc_engineer_helice::npc_engineer_heliceAI::WaypointReached(), npc_ancestral_wolf::npc_ancestral_wolfAI::WaypointReached(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::WaypointReached(), npc_maghar_captive::npc_maghar_captiveAI::WaypointReached(), npc_kurenai_captive::npc_kurenai_captiveAI::WaypointReached(), npc_bessy::npc_bessyAI::WaypointReached(), npc_earthmender_wilda::npc_earthmender_wildaAI::WaypointReached(), npc_kservant::npc_kservantAI::WaypointReached(), npc_isla_starmane::npc_isla_starmaneAI::WaypointReached(), npc_kayra_longmane::npc_kayra_longmaneAI::WaypointReached(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointStart(), and npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointStart().
TriggerAlert()
void CreatureAI::TriggerAlert (Unit const * who) const
Definition at line 178 of file CreatureAI.cpp.
 {
     // If there's no target, or target isn't a player do nothing
     if (!who || who->GetTypeId() != TYPEID_PLAYER)
         return;
     // If this unit isn't an NPC, is already distracted, is in combat, is confused, stunned or fleeing, do nothing
     if (me->GetTypeId() != TYPEID_UNIT || me->IsInCombat() || me->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_STUNNED | UNIT_STATE_FLEEING | UNIT_STATE_DISTRACTED))
         return;
     // Only alert for hostiles!
     if (me->IsCivilian() || me->HasReactState(REACT_PASSIVE) || !me->IsHostileTo(who) || !me->_IsTargetAcceptable(who))
         return;
     // Send alert sound (if any) for this creature
     me->SendAIReaction(AI_REACTION_ALERT);
     // Face the unit (stealthed player) and set distracted state for 5 seconds
     me->SetFacingTo(me->GetAngle(who->GetPositionX(), who->GetPositionY()));
     me->StopMoving();
     me->GetMotionMaster()->MoveDistract(5 * IN_MILLISECONDS);
 }
References Creature::_IsTargetAcceptable(), AI_REACTION_ALERT, Position::GetAngle(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Object::GetTypeId(), Creature::HasReactState(), Unit::HasUnitState(), IN_MILLISECONDS, Creature::IsCivilian(), Unit::IsHostileTo(), Unit::IsInCombat(), me, MotionMaster::MoveDistract(), REACT_PASSIVE, Creature::SendAIReaction(), Unit::SetFacingTo(), Unit::StopMoving(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_STATE_CONFUSED, UNIT_STATE_DISTRACTED, UNIT_STATE_FLEEING, and UNIT_STATE_STUNNED.
Referenced by CreatureUnitRelocationWorker().
UpdateVictim()
bool CreatureAI::UpdateVictim () protected
Definition at line 270 of file CreatureAI.cpp.
 {
     if (!me->IsInCombat())
         return false;
     if (!me->HasReactState(REACT_PASSIVE))
     {
         if (Unit* victim = me->SelectVictim())
             AttackStart(victim);
         return me->GetVictim();
     }
     // xinef: if we have any victim, just return true
     else if (me->GetVictim() && me->GetExactDist(me->GetVictim()) < 30.0f)
         return true;
     else if (me->getThreatMgr().isThreatListEmpty())
     {
         EnterEvadeMode();
         return false;
     }
     return true;
 }
References UnitAI::AttackStart(), EnterEvadeMode(), Position::GetExactDist(), Unit::getThreatMgr(), Unit::GetVictim(), Creature::HasReactState(), Unit::IsInCombat(), ThreatMgr::isThreatListEmpty(), me, REACT_PASSIVE, and Creature::SelectVictim().
Referenced by SmartAI::JustReachedHome(), boss_four_horsemen::boss_four_horsemenAI::MovementInform(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), CombatAI::UpdateAI(), CasterAI::UpdateAI(), ArcherAI::UpdateAI(), TurretAI::UpdateAI(), ReactorAI::UpdateAI(), ScriptedAI::UpdateAI(), BossAI::UpdateAI(), WorldBossAI::UpdateAI(), SmartAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_moira_bronzebeard::boss_moira_bronzebeardAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::UpdateAI(), boss_midnight::boss_midnightAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), prince_axes::prince_axesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_aran_elemental::water_elementalAI::UpdateAI(), npc_kilrek::npc_kilrekAI::UpdateAI(), npc_fiendish_imp::npc_fiendish_impAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), npc_tito::npc_titoAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_warlord_salaris::boss_warlord_salarisAI::UpdateAI(), boss_garaxxas::boss_garaxxasAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), boss_zelfan::boss_zelfanAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), boss_vexallus::boss_vexallusAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_baroness_anastari::boss_baroness_anastariAI::UpdateAI(), boss_brutallus::boss_brutallusAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_muru::boss_muruAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_yenniku::npc_yennikuAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_thurg::boss_thurgAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_gazakrothAI::UpdateAI(), boss_lord_raadan::boss_lord_raadanAI::UpdateAI(), boss_darkheart::boss_darkheartAI::UpdateAI(), boss_slither::boss_slitherAI::UpdateAI(), boss_fenstalker::boss_fenstalkerAI::UpdateAI(), boss_koragg::boss_koraggAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_gahzranka::boss_gahzrankaAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), npc_batrider::npc_batriderAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), npc_spawn_of_marli::npc_spawn_of_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), boss_headless_horseman::boss_headless_horsemanAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), alliance_rifleman::alliance_riflemanAI::UpdateAI(), hyjalAI::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), boss_aeonus::boss_aeonusAI::UpdateAI(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::UpdateAI(), boss_temporus::boss_temporusAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_buru::boss_buruAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_rajaxx::boss_rajaxxAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_eye_tentacle::eye_tentacleAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), npc_giant_eye_tentacle::giant_eye_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_veklor::boss_veklorAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_spitelashes::npc_spitelashesAI::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_thrall_warchief::npc_thrall_warchiefAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_ame::npc_ameAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_dred::boss_dredAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_ghostly_priest::npc_ghostly_priestAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::UpdateAI(), npc_spectral_footman::npc_spectral_footmanAI::UpdateAI(), npc_tortured_rifleman::npc_tortured_riflemanAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::UpdateAI(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::UpdateAI(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), npc_living_mojo::npc_living_mojoAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_dark_nucleus::npc_dark_nucleusAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_stinky_icc::npc_stinky_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_darnavan::npc_darnavanAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_little_ooze::npc_little_oozeAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::UpdateAI(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::UpdateAI(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::UpdateAI(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_severed_essence::npc_icc_severed_essenceAI::UpdateAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::UpdateAI(), boss_loatheb::boss_loathebAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_razuvious::boss_razuviousAI::UpdateAI(), boss_razuvious_minion::boss_razuvious_minionAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_magus_telestra::boss_magus_telestraAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_living_constellation::npc_living_constellationAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_auriaya::boss_auriayaAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::UpdateAI(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::UpdateAI(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_xt002_pummeller::npc_xt002_pummellerAI::UpdateAI(), boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI::UpdateAI(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::UpdateAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_koralon::boss_koralonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), npc_erekem_guard::npc_erekem_guardAI::UpdateAI(), boss_lavanthor::boss_lavanthorAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_amberpine_woodsman::npc_amberpine_woodsmanAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::UpdateAI(), npc_frosthound::npc_frosthoundAI::UpdateAI(), npc_iron_watcher::npc_iron_watcherAI::UpdateAI(), npc_icefang::npc_icefangAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), npc_stolen_soul::npc_stolen_soulAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_lady_malande::boss_lady_malandeAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), npc_inner_demon::npc_inner_demonAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::UpdateAI(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::UpdateAI(), boss_olm_the_summoner::boss_olm_the_summonerAI::UpdateAI(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::UpdateAI(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::UpdateAI(), boss_krosh_firehand::boss_krosh_firehandAI::UpdateAI(), boss_broggok::boss_broggokAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::UpdateAI(), boss_the_maker::boss_the_makerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_nazan::boss_nazanAI::UpdateAI(), boss_vazruden::boss_vazrudenAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_commander_sarannis::boss_commander_sarannisAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_laj::boss_lajAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_warp_splinter::boss_warp_splinterAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_void_reaver::boss_void_reaverAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::UpdateAI(), npc_ragin_flames::npc_ragin_flamesAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_raliq_the_drunk::npc_raliq_the_drunkAI::UpdateAI(), npc_salsalabim::npc_salsalabimAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_floon::npc_floonAI::UpdateAI(), npc_cooshcoosh::npc_cooshcooshAI::UpdateAI(), npc_pet_gen_valkyr_guardian::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), emerald_dragonAI::UpdateAI(), npc_dream_fog::npc_dream_fogAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), generic_creature::generic_creatureAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_training_dummy::npc_training_dummyAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), npc_earthmender_wilda::npc_earthmender_wildaAI::UpdateAI(), AggressorAI::UpdateAI(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::UpdateAI(), npc_zelfrax::npc_zelfraxAI::UpdateAI(), npc_enraged_panther::npc_enraged_pantherAI::UpdateAI(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::UpdateAI(), npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI(), npc_suppresser::npc_suppresserAI::UpdateAI(), npc_centrifuge_construct::npc_centrifuge_constructAI::UpdateAI(), boss_sjonnir_dwarf::boss_sjonnir_dwarfAI::UpdateAI(), npc_xt002_life_spark::npc_xt002_life_sparkAI::UpdateAI(), boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI::UpdateAI(), npc_future_you::npc_future_youAI::UpdateAI(), npc_mrfloppy::npc_mrfloppyAI::UpdateAI(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::UpdateAI(), npc_bushwhacker::npc_bushwhackerAI::UpdateAI(), npc_infernal_attacker::npc_infernal_attackerAI::UpdateAI(), npc_precious::npc_preciousAI::UpdateAI(), npc_escortAI::UpdateEscortAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_isla_starmane::npc_isla_starmaneAI::UpdateEscortAI(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::UpdateEscortAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), and FollowerAI::UpdateFollowerAI().
UpdateVictimWithGaze()
bool CreatureAI::UpdateVictimWithGaze () protected
Definition at line 252 of file CreatureAI.cpp.
 {
     if (!me->IsInCombat())
         return false;
     if (me->HasReactState(REACT_PASSIVE))
     {
         if (me->GetVictim())
             return true;
         else
             me->SetReactState(REACT_AGGRESSIVE);
     }
     if (Unit* victim = me->SelectVictim())
         AttackStart(victim);
     return me->GetVictim();
 }
References UnitAI::AttackStart(), Unit::GetVictim(), Creature::HasReactState(), Unit::IsInCombat(), me, REACT_AGGRESSIVE, REACT_PASSIVE, Creature::SelectVictim(), and Creature::SetReactState().
Referenced by boss_gluth::boss_gluthAI::UpdateAI(), and npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI().
Member Data Documentation
m_MoveInLineOfSight_locked
bool CreatureAI::m_MoveInLineOfSight_locked private
Definition at line 186 of file CreatureAI.h.
Referenced by MoveInLineOfSight_Safe().
me
Creature* const CreatureAI::me protected
Definition at line 68 of file CreatureAI.h.
Referenced by PetAI::_canMeleeAttack(), _EnterEvadeMode(), PetAI::_needToStop(), PetAI::_stopAttack(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::AllowAction(), ArcherAI::ArcherAI(), SmartAI::AssistPlayerInCombat(), PetAI::AttackedBy(), npc_ritual_channeler::npc_ritual_channelerAI::AttackStart(), PossessedAI::AttackStart(), PetAI::AttackStart(), TotemAI::AttackStart(), ArcherAI::AttackStart(), TurretAI::AttackStart(), SmartAI::AttackStart(), npc_ravenous_worg::npc_ravenous_worgAI::AttackStart(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::boss_yoggsaron_brainAI(), boss_yoggsaron_death_orb::boss_yoggsaron_death_orbAI::boss_yoggsaron_death_orbAI(), boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI::boss_yoggsaron_influence_tentacleAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::boss_yoggsaron_keeperAI(), TurretAI::CanAIAttack(), SmartAI::CanAIAttack(), PetAI::CanAttack(), npc_wg_siege_machine::npc_wg_siege_machineAI::CanControlVehicle(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction(), SmartAI::CheckConditions(), VehicleAI::CheckConditions(), boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), PetAI::ClearCharmInfoFlags(), CritterAI::DamageTaken(), boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI::DamageTaken(), npc_mc_core_hound::npc_mc_core_houndAI::DamageTaken(), npc_announcer_toc5::npc_announcer_toc5AI::DamageTaken(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), npc_gunship::npc_gunshipAI::DamageTaken(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_collapsing_star::npc_collapsing_starAI::DamageTaken(), npc_xt002_boombot::npc_xt002_boombotAI::DamageTaken(), npc_hor_leader_second::npc_hor_leader_secondAI::DamageTaken(), npc_ice_tomb::npc_ice_tombAI::DamageTaken(), npc_death_knight_initiate::npc_death_knight_initiateAI::DamageTaken(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::DamageTaken(), SmartAI::DamageTaken(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::DamageTaken(), npc_heated_battle::npc_heated_battleAI::DamageTaken(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), npc_hor_lich_king::npc_hor_lich_kingAI::DoAction(), boss_krick::boss_krickAI::DoAction(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::DoAction(), npc_orb_carrier::npc_orb_carrierAI::DoAction(), npc_kinetic_bomb::npc_kinetic_bombAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_pos_leader_second::npc_pos_leader_secondAI::DoAction(), npc_madrigosa::npc_madrigosaAI::DoAction(), npc_kalecgos_kj::npc_kalecgos_kjAI::DoAction(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::DoAction(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::DoAction(), boss_skadi_grauf::boss_skadi_graufAI::DoAction(), npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction(), npc_naga_distiller::npc_naga_distillerAI::DoAction(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(), PetAI::DoAttack(), DoSummon(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), DoSummonFlyer(), DoZoneInCombat(), SmartAI::EndPath(), CasterAI::EnterCombat(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::EnterCombat(), boss_skadi_grauf::boss_skadi_graufAI::EnterCombat(), SmartAI::EnterCombat(), CombatAI::EnterCombat(), npc_beryl_sorcerer::npc_beryl_sorcererAI::EnterCombat(), EnterEvadeMode(), CritterAI::EnterEvadeMode(), TotemAI::EnterEvadeMode(), SmartAI::EnterEvadeMode(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_mage_mirror_image::EnterEvadeMode(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::FinishQuest(), SmartAI::GenerateWayPointArray(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::GetHarpoonGunIdForThisHFS(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::GetPlate(), npc_spiritual_insight::npc_spiritual_insightAI::GetSpeachId(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::GetSummoner(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), PetAI::HandleReturnMovement(), CombatAI::InitializeAI(), SmartAI::InitializeAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::InitializeAI(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI::InitializeAI(), npc_pet_dk_dancing_rune_weapon::npc_pet_dk_dancing_rune_weaponAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), npc_pet_pri_lightwell::InitializeAI(), SmartAI::IsEscortInvokerInRange(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::IsHeroic(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsHeroic(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::IsSummonedBy(), npc_kinetic_bomb::npc_kinetic_bombAI::IsSummonedBy(), npc_coldflame::npc_coldflameAI::IsSummonedBy(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), TriggerAI::IsSummonedBy(), npc_bone_spike::npc_bone_spikeAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), npc_pet_gen_fetch_ball::IsSummonedBy(), npc_spirit_shade::npc_spirit_shadeAI::IsSummonedBy(), PossessedAI::JustDied(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustDied(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_ice_tomb::npc_ice_tombAI::JustDied(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustDied(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::JustDied(), boss_naxxramas_misc::boss_naxxramas_miscAI::JustDied(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::JustDied(), boss_freya_iron_root::boss_freya_iron_rootAI::JustDied(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), npc_xt002_boombot::npc_xt002_boombotAI::JustDied(), boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI::JustDied(), npc_vh_void_sentry::npc_vh_void_sentryAI::JustDied(), npc_ahune_frozen_core::npc_ahune_frozen_coreAI::JustDied(), npc_pet_dk_ghoul::npc_pet_dk_ghoulAI::JustDied(), npc_pet_pri_shadowfiend::JustDied(), CombatAI::JustDied(), npc_four_car_garage::npc_four_car_garageAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), npc_frost_tomb::npc_frost_tombAI::JustDied(), npc_nerubar_victim::npc_nerubar_victimAI::JustDied(), trigger_death::trigger_deathAI::JustDied(), SmartAI::JustReachedHome(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustReachedHome(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustReachedHome(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::JustReachedHome(), SmartAI::JustRespawned(), npc_xt002_heart::npc_xt002_heartAI::JustSummoned(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::JustSummoned(), npc_collapsing_star::npc_collapsing_starAI::JustSummoned(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), PetAI::KilledUnit(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::KilledUnit(), VehicleAI::LoadConditions(), npc_drakuru_shackles::npc_drakuru_shacklesAI::LockRageclaw(), MoveBackwardsChecks(), MoveCircleChecks(), MoveInLineOfSight(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), SmartAI::MoveInLineOfSight(), npc_scarlet_guard::npc_scarlet_guardAI::MoveInLineOfSight(), npc_fairbanks::npc_fairbanksAI::MoveInLineOfSight(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::MoveInLineOfSight(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::MoveInLineOfSight(), SmartAI::MovementInform(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform(), PetAI::MovementInform(), npc_spirit_shade::npc_spirit_shadeAI::MovementInform(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::MovementInform(), npc_concentrated_ball::npc_concentrated_ballAI::MovementInform(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::MovementInform(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_hover_disk::npc_hover_diskAI::MovementInform(), npc_oculus_drake::npc_oculus_drakeAI::MovementInform(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::MovementInform(), npc_pet_gen_plump_turkey::MovementInform(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::MovementInform(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::MovementInform(), npc_announcer_toc5::npc_announcer_toc5AI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), npc_hor_leader_second::npc_hor_leader_secondAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform(), npc_freed_protodrake::npc_freed_protodrakeAI::MovementInform(), boss_skadi_grauf::boss_skadi_graufAI::MovementInform(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::MovementInform(), SmartAI::MovepointReached(), npc_concentrated_ball::npc_concentrated_ballAI::MoveToNextPoint(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), npc_pet_mage_mirror_image::MySelectNextTarget(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::npc_attracted_reef_bullAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::npc_boss_gothik_minionAI(), npc_concentrated_ball::npc_concentrated_ballAI::npc_concentrated_ballAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::npc_fos_corrupted_soul_fragmentAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::npc_frost_freeze_trapAI(), npc_frost_sphere::npc_frost_sphereAI::npc_frost_sphereAI(), npc_frost_tomb::npc_frost_tombAI::npc_frost_tombAI(), npc_frostbite_invisible_stalker::npc_frostbite_invisible_stalkerAI::npc_frostbite_invisible_stalkerAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::npc_grand_magister_rommathAI(), npc_gunship::npc_gunshipAI::npc_gunshipAI(), npc_hor_leader_second::npc_hor_leader_secondAI::npc_hor_leader_secondAI(), npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI(), npc_hor_lich_king::npc_hor_lich_kingAI::npc_hor_lich_kingAI(), npc_hover_disk::npc_hover_diskAI::npc_hover_diskAI(), npc_ice_tomb::npc_ice_tombAI::npc_ice_tombAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::npc_lk_spirit_bombAI(), npc_oculus_drake::npc_oculus_drakeAI::npc_oculus_drakeAI(), npc_pet_gen_moth::npc_pet_gen_moth(), npc_pet_gen_target_following_bomb::npc_pet_gen_target_following_bomb(), npc_pet_gen_wind_rider_cub::npc_pet_gen_wind_rider_cub(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::npc_pilgrims_bounty_chairAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::npc_pos_after_first_bossAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::npc_pos_collapsing_icicleAI(), npc_pos_freed_slave::npc_pos_freed_slaveAI::npc_pos_freed_slaveAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::npc_pos_icicle_triggerAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_pos_leader::npc_pos_leaderAI::npc_pos_leaderAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::npc_pos_tyrannus_eventsAI(), npc_power_spark::npc_power_sparkAI::npc_power_sparkAI(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::npc_scarlet_miner_cartAI(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::npc_toc5_player_vehicleAI(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::npc_ulduar_expedition_commanderAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::npc_ulduar_expedition_engineerAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::npc_ulduar_flash_freezeAI(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::npc_ulduar_harpoonfirestateAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::npc_ulduar_magnetic_coreAI(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::npc_ulduar_saronite_vaporsAI(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::npc_ulduar_toasty_fireAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), npc_xt002_heart::npc_xt002_heartAI::npc_xt002_heartAI(), npc_zafod_boombox::npc_zafod_boomboxAI::npc_zafod_boomboxAI(), NullCreatureAI::NullCreatureAI(), VehicleAI::OnCharmed(), OnCharmed(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed(), npc_valithria_portal::npc_valithria_portalAI::OnSpellClick(), PetAI::OwnerAttacked(), PetAI::OwnerAttackedBy(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::PassengerBoarded(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::PassengerBoarded(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::PassengerBoarded(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::PassengerBoarded(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::PassengerBoarded(), npc_four_car_garage::npc_four_car_garageAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::PassengerBoarded(), PassiveAI::PassiveAI(), SmartAI::PausePath(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::PlaySound(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::PlaySound(), PossessedAI::PossessedAI(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareChamberIllusion(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareIceCrownIllusion(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareStormwindIllusion(), PetAI::ReceiveEmote(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveAll(), boss_skadi_grauf::boss_skadi_graufAI::RemoveSkadi(), npc_death_knight_initiate::npc_death_knight_initiateAI::Reset(), npc_crusade_persuaded::npc_crusade_persuadedAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_demonic_vapor::npc_demonic_vaporAI::Reset(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), npc_singularity::npc_singularityAI::Reset(), npc_brew_bubble::npc_brew_bubbleAI::Reset(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::Reset(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::Reset(), npc_time_rift::npc_time_riftAI::Reset(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), npc_hor_leader::npc_hor_leaderAI::Reset(), npc_pos_leader::npc_pos_leaderAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_impaling_spear::npc_impaling_spearAI::Reset(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::Reset(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::Reset(), npc_crystal_spike::npc_crystal_spikeAI::Reset(), boss_freya_lifebinder::boss_freya_lifebinderAI::Reset(), boss_freya_healthy_spore::boss_freya_healthy_sporeAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::Reset(), boss_thorim_pillar::boss_thorim_pillarAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Reset(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Reset(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::Reset(), boss_skadi_grauf::boss_skadi_graufAI::Reset(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::Reset(), npc_beryl_sorcerer::npc_beryl_sorcererAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_heated_battle::npc_heated_battleAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_freed_protodrake::npc_freed_protodrakeAI::Reset(), npc_drakuru_shackles::npc_drakuru_shacklesAI::Reset(), npc_captured_rageclaw::npc_captured_rageclawAI::Reset(), npc_naga_distiller::npc_naga_distillerAI::Reset(), npc_pet_pri_shadowfiend::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::ResetOrbs(), SmartAI::ResumePath(), SmartAI::ReturnToLastOOCPos(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::Say(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_skadi_grauf::boss_skadi_graufAI::SelectNextPos(), PetAI::SelectNextTarget(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), SmartAI::SetCombatMove(), npc_eye_of_acherus::npc_eye_of_acherusAI::SetControl(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_pos_leader::npc_pos_leaderAI::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), SmartAI::SetFly(), SmartAI::SetFollow(), SmartAI::SetForcedCombatMove(), SetGazeOn(), npc_gunship::npc_gunshipAI::SetGUID(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::SetGUID(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetGUID(), SmartAI::SetRun(), SmartAI::SetSwim(), npc_maredis_firestar::npc_maredis_firestarAI::sGossipHello(), npc_maredis_firestar::npc_maredis_firestarAI::sGossipSelect(), SmartAI::SmartAI(), boss_skadi_grauf::boss_skadi_graufAI::SpawnFlameTriggers(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), npc_frost_sphere::npc_frost_sphereAI::SpellHit(), npc_ulduar_flames_spread::npc_ulduar_flames_spreadAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::SpellHit(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHit(), npc_pilgrims_bounty_plate::npc_pilgrims_bounty_plateAI::SpellHit(), boss_thorim_pillar::boss_thorim_pillarAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit(), npc_death_knight_initiate::npc_death_knight_initiateAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), PetAI::SpellHit(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::SpellHit(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::SpellHit(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::SpellHit(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::SpellHitTarget(), npc_hor_lich_king::npc_hor_lich_kingAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), boss_skadi_grauf::boss_skadi_graufAI::SpellHitTarget(), npc_pet_gen_fetch_ball::SpellHitTarget(), npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::SpreadFire(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame(), SmartAI::StartPath(), SmartAI::StopFollow(), SmartAI::StopPath(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonFrostwardens(), npc_xt002_heart::npc_xt002_heartAI::SummonPiles(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonSpiders(), Talk(), trigger_periodic::trigger_periodicAI::trigger_periodicAI(), TriggerAlert(), TurretAI::TurretAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UnlockRageclaw(), CombatAI::UpdateAI(), CasterAI::UpdateAI(), ArcherAI::UpdateAI(), TurretAI::UpdateAI(), VehicleAI::UpdateAI(), TotemAI::UpdateAI(), SmartAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_brew_bubble::npc_brew_bubbleAI::UpdateAI(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), npc_time_rift::npc_time_riftAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::UpdateAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), npc_frostbite_invisible_stalker::npc_frostbite_invisible_stalkerAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), npc_ice_tomb::npc_ice_tombAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_impaling_spear::npc_impaling_spearAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::UpdateAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), npc_crystal_spike::npc_crystal_spikeAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::UpdateAI(), boss_freya_lifebinder::boss_freya_lifebinderAI::UpdateAI(), boss_freya_healthy_spore::boss_freya_healthy_sporeAI::UpdateAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::UpdateAI(), npc_ulduar_icicle::npc_ulduar_icicleAI::UpdateAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::UpdateAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_thorim_trap::boss_thorim_trapAI::UpdateAI(), npc_xt002_heart::npc_xt002_heartAI::UpdateAI(), boss_yoggsaron_death_orb::boss_yoggsaron_death_orbAI::UpdateAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::UpdateAI(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::UpdateAI(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::UpdateAI(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI(), boss_skadi_grauf::boss_skadi_graufAI::UpdateAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_ravenous_worg::npc_ravenous_worgAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UpdateAI(), npc_creature_generator_akama::npc_creature_generator_akamaAI::UpdateAI(), npc_naga_distiller::npc_naga_distillerAI::UpdateAI(), npc_pet_gen_target_following_bomb::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_pet_gen_wind_rider_cub::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_pet_gen_toxic_wasteling::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_pet_mage_mirror_image::UpdateAI(), trigger_periodic::trigger_periodicAI::UpdateAI(), PassiveAI::UpdateAI(), PossessedAI::UpdateAI(), CritterAI::UpdateAI(), PetAI::UpdateAI(), npc_demonic_vapor::npc_demonic_vaporAI::UpdateAI(), npc_orb_carrier::npc_orb_carrierAI::UpdateAI(), npc_concentrated_ball::npc_concentrated_ballAI::UpdateAI(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), npc_frost_tomb::npc_frost_tombAI::UpdateAI(), npc_q24545_vegard_dummy::npc_q24545_vegard_dummyAI::UpdateAI(), PetAI::UpdateAllies(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), SmartAI::UpdateDespawn(), SmartAI::UpdatePath(), UpdateVictim(), and UpdateVictimWithGaze().
The documentation for this class was generated from the following files:
src/server/game/AI/CreatureAI.h
src/server/game/AI/CreatureAI.cpp