Azerotcore-wotlk: npc_vh_teleportation_portal::npc_vh_teleportation_portalAI Struct Reference
npc_vh_teleportation_portal::npc_vh_teleportation_portalAI Struct Reference
Public Member Functions
npc_vh_teleportation_portalAI (Creature *c)
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void JustSummoned (Creature *pSummoned) override
void SummonedMobDied (Creature *pSummoned)
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
SummonList listOfMobs
EventMap events
uint8 wave
uint8 addValue
bool bKorG
bool spawned
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 123 of file violet_hold.cpp.
Constructor & Destructor Documentation
npc_vh_teleportation_portalAI()
npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::npc_vh_teleportation_portalAI (Creature * c) inline
Definition at line 125 of file violet_hold.cpp.
                                                    : NullCreatureAI(c), listOfMobs(me)
         {
             pInstance = c->GetInstanceScript();
             events.Reset();
             if (pInstance)
             {
                 wave = pInstance->GetData(DATA_WAVE_COUNT);
                 bKorG = false;
                 spawned = false;
                 if (wave < 12)
                     addValue = 0;
                 else
                     addValue = 1;
                 if (wave % 6 != 0)
                     events.RescheduleEvent(RAND(EVENT_SUMMON_KEEPER_OR_GUARDIAN, EVENT_SUMMON_ELITES), 10000);
                 else
                     events.RescheduleEvent(EVENT_SUMMON_SABOTEOUR, 3000);
             }
         }
References addValue, bKorG, DATA_WAVE_COUNT, EVENT_SUMMON_ELITES, EVENT_SUMMON_KEEPER_OR_GUARDIAN, EVENT_SUMMON_SABOTEOUR, ZoneScript::GetData(), WorldObject::GetInstanceScript(), pInstance, RAND(), spawned, and wave.
Member Function Documentation
JustDied()
void npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 222 of file violet_hold.cpp.
         {
             events.Reset();
             if (wave % 6 == 0) // just to be sure, shouln't occur
                 return;
             if (pInstance)
                 pInstance->SetData(DATA_PORTAL_DEFEATED, 0);
         }
References DATA_PORTAL_DEFEATED, pInstance, ZoneScript::SetData(), and wave.
JustSummoned()
void npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustSummoned (Creature * pSummoned) inline override virtual
Reimplemented from CreatureAI.
Definition at line 231 of file violet_hold.cpp.
         {
             if (pSummoned)
             {
                 listOfMobs.Summon(pSummoned);
                 pInstance->SetGuidData(DATA_ADD_TRASH_MOB, pSummoned->GetGUID());
             }
         }
References DATA_ADD_TRASH_MOB, Object::GetGUID(), listOfMobs, pInstance, ZoneScript::SetGuidData(), and SummonList::Summon().
SummonedMobDied()
void npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::SummonedMobDied (Creature * pSummoned) inline
Definition at line 240 of file violet_hold.cpp.
         {
             if (pSummoned)
             {
                 listOfMobs.Despawn(pSummoned);
                 pInstance->SetGuidData(DATA_DELETE_TRASH_MOB, pSummoned->GetGUID());
             }
         }
References DATA_DELETE_TRASH_MOB, SummonList::Despawn(), Object::GetGUID(), listOfMobs, pInstance, and ZoneScript::SetGuidData().
UpdateAI()
void npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 155 of file violet_hold.cpp.
         {
             if (!pInstance)
                 return;
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SUMMON_KEEPER_OR_GUARDIAN:
                     bKorG = true;
                     spawned = true;
                     if (Creature* c = DoSummon(RAND(NPC_PORTAL_GUARDIAN, NPC_PORTAL_KEEPER), me, 2.0f, 0, TEMPSUMMON_DEAD_DESPAWN))
                         me->CastSpell(c, SPELL_PORTAL_CHANNEL, false);
                     events.RescheduleEvent(EVENT_SUMMON_KEEPER_TRASH, 20000);
                     break;
                 case EVENT_SUMMON_KEEPER_TRASH:
                     for (uint8 i = 0; i < 3 + addValue; ++i)
                     {
                         uint32 entry = RAND(NPC_AZURE_INVADER_1, NPC_AZURE_INVADER_2, NPC_AZURE_SPELLBREAKER_1, NPC_AZURE_SPELLBREAKER_2, NPC_AZURE_MAGE_SLAYER_1, NPC_AZURE_MAGE_SLAYER_2, NPC_AZURE_BINDER_1, NPC_AZURE_BINDER_2);
                         DoSummon(entry, me, 2.0f, 20000, TEMPSUMMON_DEAD_DESPAWN);
                     }
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_SUMMON_ELITES:
                     spawned = true;
                     for (uint8 i = 0; i < 2 + addValue; ++i)
                     {
                         uint32 entry = RAND(NPC_AZURE_CAPTAIN, NPC_AZURE_RAIDER, NPC_AZURE_STALKER, NPC_AZURE_SORCEROR);
                         DoSummon(entry, me, 2.0f, 20000, TEMPSUMMON_DEAD_DESPAWN);
                     }
                     me->SetVisible(false);
                     break;
                 case EVENT_SUMMON_SABOTEOUR:
                     DoSummon(NPC_SABOTEOUR, me, 2.0f, 0, TEMPSUMMON_CORPSE_DESPAWN);
                     me->DespawnOrUnsummon(3000);
                     break;
             }
             if (!spawned)
                 return;
             if (bKorG)
             {
                 if (!me->IsNonMeleeSpellCast(false)) // keeper/guardian died => channeled spell interrupted
                 {
                     // if keeper/guard lost all victims, in enterevademode linking aura is removed, restore it:
                     if (pInstance)
                         for (SummonList::iterator itr = listOfMobs.begin(); itr != listOfMobs.end(); ++itr)
                             if (Creature* c = pInstance->instance->GetCreature(*itr))
                                 if (c->IsAlive() && (c->GetEntry() == NPC_PORTAL_GUARDIAN || c->GetEntry() == NPC_PORTAL_KEEPER))
{
                                     me->CastSpell(c, SPELL_PORTAL_CHANNEL, false);
                                     return;
                                 }
                     Unit::Kill(me, me, false);
                 }
             }
             else
             {
                 if (listOfMobs.empty())
                     Unit::Kill(me, me, false);
             }
         }
References addValue, SummonList::begin(), bKorG, Unit::CastSpell(), Creature::DespawnOrUnsummon(), CreatureAI::DoSummon(), SummonList::empty(), SummonList::end(), EVENT_SUMMON_ELITES, EVENT_SUMMON_KEEPER_OR_GUARDIAN, EVENT_SUMMON_KEEPER_TRASH, EVENT_SUMMON_SABOTEOUR, Map::GetCreature(), InstanceScript::instance, Unit::IsNonMeleeSpellCast(), Unit::Kill(), listOfMobs, CreatureAI::me, NPC_AZURE_BINDER_1, NPC_AZURE_BINDER_2, NPC_AZURE_CAPTAIN, NPC_AZURE_INVADER_1, NPC_AZURE_INVADER_2, NPC_AZURE_MAGE_SLAYER_1, NPC_AZURE_MAGE_SLAYER_2, NPC_AZURE_RAIDER, NPC_AZURE_SORCEROR, NPC_AZURE_SPELLBREAKER_1, NPC_AZURE_SPELLBREAKER_2, NPC_AZURE_STALKER, NPC_PORTAL_GUARDIAN, NPC_PORTAL_KEEPER, NPC_SABOTEOUR, pInstance, RAND(), Unit::SetVisible(), spawned, SPELL_PORTAL_CHANNEL, TEMPSUMMON_CORPSE_DESPAWN, and TEMPSUMMON_DEAD_DESPAWN.
Member Data Documentation
addValue
uint8 npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::addValue
Definition at line 151 of file violet_hold.cpp.
Referenced by npc_vh_teleportation_portalAI(), and UpdateAI().
bKorG
bool npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::bKorG
Definition at line 152 of file violet_hold.cpp.
Referenced by npc_vh_teleportation_portalAI(), and UpdateAI().
events
EventMap npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::events
Definition at line 149 of file violet_hold.cpp.
listOfMobs
SummonList npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::listOfMobs
Definition at line 148 of file violet_hold.cpp.
Referenced by JustSummoned(), SummonedMobDied(), and UpdateAI().
pInstance
InstanceScript* npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::pInstance
Definition at line 147 of file violet_hold.cpp.
Referenced by JustDied(), JustSummoned(), npc_vh_teleportation_portalAI(), SummonedMobDied(), and UpdateAI().
spawned
bool npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::spawned
Definition at line 153 of file violet_hold.cpp.
Referenced by npc_vh_teleportation_portalAI(), and UpdateAI().
wave
uint8 npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::wave
Definition at line 150 of file violet_hold.cpp.
Referenced by JustDied(), and npc_vh_teleportation_portalAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/VioletHold/violet_hold.cpp