Azerotcore-wotlk: G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator Class Reference
G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator Class Reference
#include <Table.h>
Public Member Functions
bool operator!= (const Iterator &other) const
bool operator== (const Iterator &other) const
Iterator & operator++ ()
Iterator operator++ (int)
const Entry & operator* () const
const Value & value () const
const Key & key () const
Entry * operator-> () const
operator Entry * () const
bool isValid () const
bool hasMore () const
Private Member Functions
Iterator ()
Iterator (size_t numBuckets, Node **m_bucket)
void findNext ()
Private Attributes
size_t index
Node * node
size_t m_numBuckets
Node ** m_bucket
bool isDone
Friends
class Table< Key, Value, HashFunc, EqualsFunc >
Detailed Description
template<class Key, class Value, class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>>
class G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator
C++ STL style iterator variable. See begin().
Definition at line 416 of file Table.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator () inline private
Creates the end iterator.
Definition at line 437 of file Table.h.
                    : index(0), node(NULL), m_bucket(NULL) {
             isDone = true;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone.
Iterator() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator (size_t numBuckets, Node ** m_bucket) inline private
Definition at line 441 of file Table.h.
                                                      :
             index(0),
             node(NULL),
             m_numBuckets(numBuckets),
             m_bucket(m_bucket) {
             if (m_numBuckets == 0) {
                 // Empty table
                 isDone = true;
                 return;
             }
 #           ifdef G3D_DEBUG
                 for (unsigned int i = 0; i < m_numBuckets; ++i) {
                     debugAssert((m_bucket[i] == NULL) || isValidHeapPointer(m_bucket[i]));
                 }
 #           endif
             index = 0;
             node = m_bucket[index];
             debugAssert((node == NULL) || isValidHeapPointer(node));
             isDone = false;
             findNext();
             debugAssert((node == NULL) || isValidHeapPointer(node));
         }
References debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::index, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone, G3D::isValidHeapPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node, and NULL.
Member Function Documentation
findNext()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> void G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext () inline private
If node is NULL, then finds the next element by searching through the bucket array. Sets isDone if no more nodes are available.
Definition at line 471 of file Table.h.
{
             while (node == NULL) {
                 ++index;
                 if (index >= m_numBuckets) {
                     m_bucket = NULL;
                     index = 0;
                     isDone = true;
                     return;
                 } else {
                     node = m_bucket[index];
                     debugAssert((node == NULL) || isValidHeapPointer(node));
                 }
             }
             debugAssert(isValidHeapPointer(node));
         }
References debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::index, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone, G3D::isValidHeapPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_bucket, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_numBuckets, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node, and NULL.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator++().
hasMore()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::hasMore () const inline
Deprecated:
Use isValid
Definition at line 551 of file Table.h.
{
             return ! isDone;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone.
Referenced by G3D::GCamera::GCamera(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::operator==(), and G3D::AnyTableReader::verifyDone().
isValid()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isValid () const inline
Definition at line 546 of file Table.h.
{
             return ! isDone;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone.
Referenced by G3D::Any::operator==().
key()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> const Key& G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::key () const inline
Definition at line 532 of file Table.h.
{
             return node->entry.key;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node.
operator Entry *()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator Entry * () const inline
Definition at line 541 of file Table.h.
{
             debugAssert(isValidHeapPointer(node));
             return &(node->entry);
         }
References debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::isValidHeapPointer(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node.
operator!=()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator!= (const Iterator & other) const inline
Definition at line 488 of file Table.h.
{
             return !(*this == other);
         }
operator*()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> const Entry& G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator* () const inline
Definition at line 524 of file Table.h.
{
             return node->entry;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node.
operator++() [1/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Iterator& G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator++ () inline
Pre increment.
Definition at line 504 of file Table.h.
{
             debugAssert(! isDone);
             debugAssert(node != NULL);
             debugAssert(isValidHeapPointer(node));
             debugAssert((node->next == NULL) || isValidHeapPointer(node->next));
             node = node->next;
             findNext();
             debugAssert(isDone || isValidHeapPointer(node));
             return *this;
         }
References debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone, G3D::isValidHeapPointer(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::next, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node, and NULL.
operator++() [2/2]
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Iterator G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator++ (int) inline
Post increment (slower than preincrement).
Definition at line 518 of file Table.h.
{
             Iterator old = *this;
             ++(*this);
             return old;
         }
operator->()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Entry* G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator-> () const inline
Definition at line 536 of file Table.h.
{
             debugAssert(isValidHeapPointer(node));
             return &(node->entry);
         }
References debugAssert, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::isValidHeapPointer(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node.
operator==()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator== (const Iterator & other) const inline
Definition at line 492 of file Table.h.
{
             if (other.isDone || isDone) {
                 // Common case; check against isDone.
                 return (isDone == other.isDone);
             } else {
                 return (node == other.node) && (index == other.index);
             }
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::index, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node.
value()
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> const Value& G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::value () const inline
Definition at line 528 of file Table.h.
{
             return node->entry.value;
         }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::Node::entry, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node, and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value.
Friends And Related Function Documentation
Table< Key, Value, HashFunc, EqualsFunc >
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> friend class Table< Key, Value, HashFunc, EqualsFunc > friend
Definition at line 164 of file Table.h.
Member Data Documentation
index
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::index private
Bucket index.
Definition at line 423 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator==().
isDone
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> bool G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isDone private
Definition at line 432 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::hasMore(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::isValid(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator++(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator==().
m_bucket
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Node** G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_bucket private
Definition at line 431 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator().
m_numBuckets
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> size_t G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::m_numBuckets private
Definition at line 430 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator().
node
template<class Key , class Value , class HashFunc = HashTrait<Key>, class EqualsFunc = EqualsTrait<Key>> Node* G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::node private
Linked list node.
Definition at line 428 of file Table.h.
Referenced by G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::findNext(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::Iterator(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::key(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator Entry *(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator*(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator++(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator->(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::operator==(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::value().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Table.h