Azerotcore-wotlk: npc_ball_of_flame::npc_ball_of_flameAI Struct Reference
npc_ball_of_flame::npc_ball_of_flameAI Struct Reference
Public Member Functions
npc_ball_of_flameAI (Creature *creature)
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *) override
void MovementInform (uint32 type, uint32) override
void SetGUID (ObjectGuid guid, int32) override
void DoAction (int32 action) override
void DamageDealt (Unit *target, uint32 &damage, DamageEffectType) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * _instance
ObjectGuid _chaseGUID
bool _exploded
bool _started
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1252 of file boss_blood_prince_council.cpp.
Constructor & Destructor Documentation
npc_ball_of_flameAI()
npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI (Creature * creature) inline
Definition at line 1254 of file boss_blood_prince_council.cpp.
                                                 : ScriptedAI(creature), _instance(creature->GetInstanceScript())
         {
             _exploded = false;
             _started = false;
             if (me->GetEntry() == NPC_BALL_OF_INFERNO_FLAME)
                 me->CastSpell(me, SPELL_BALL_OF_FLAMES_PROC, true);
             me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 5.0f, me->GetOrientation());
         }
References _exploded, _started, Unit::CastSpell(), Object::GetEntry(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Unit::NearTeleportTo(), NPC_BALL_OF_INFERNO_FLAME, and SPELL_BALL_OF_FLAMES_PROC.
Member Function Documentation
AttackStart()
void npc_ball_of_flame::npc_ball_of_flameAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1268 of file boss_blood_prince_council.cpp.
         {
             if (_started)
                 ScriptedAI::AttackStart(who);
         }
References _started, and ScriptedAI::AttackStart().
Referenced by DoAction().
DamageDealt()
void npc_ball_of_flame::npc_ball_of_flameAI::DamageDealt (Unit * target, uint32 & damage, DamageEffectType) inline override virtual
Reimplemented from UnitAI.
Definition at line 1332 of file boss_blood_prince_council.cpp.
         {
             if (target->GetTypeId() != TYPEID_PLAYER)
             {
                 return;
             }
             if (damage > RAID_MODE<uint32>(23000, 25000, 23000, 25000))
             {
                 _instance->SetData(DATA_ORB_WHISPERER_ACHIEVEMENT, 0);
             }
         }
References _instance, DATA_ORB_WHISPERER_ACHIEVEMENT, Object::GetTypeId(), ZoneScript::SetData(), and TYPEID_PLAYER.
DoAction()
void npc_ball_of_flame::npc_ball_of_flameAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1296 of file boss_blood_prince_council.cpp.
         {
             if (action != ACTION_FLAME_BALL_CHASE || me->IsInCombat())
             {
                 return;
             }
             Player* target = nullptr;
             if (_chaseGUID)
             {
                 target = ObjectAccessor::GetPlayer(*me, _chaseGUID);
             }
             if (!target)
             {
                 target = ScriptedAI::SelectTargetFromPlayerList(150.0f, 0, true);
             }
             if (target)
             {
                 // need to clear states now because this call is before AuraEffect is fully removed
                 _started = true;
                 if (me->GetEntry() == NPC_BALL_OF_INFERNO_FLAME)
                     me->CastSpell(me, SPELL_BALL_OF_FLAMES_PERIODIC, true);
                 me->ClearUnitState(UNIT_STATE_CASTING | UNIT_STATE_STUNNED);
                 me->AddThreat(target, 1000.0f);
                 me->SetCanFly(true);
                 me->SetDisableGravity(true);
                 me->SetHover(true);
                 me->SendMovementFlagUpdate();
                 AttackStart(target);
                 me->SetInCombatWithZone();
                 return;
             }
             me->DespawnOrUnsummon(1);
         }
References _chaseGUID, _started, ACTION_FLAME_BALL_CHASE, Unit::AddThreat(), AttackStart(), Unit::CastSpell(), Unit::ClearUnitState(), Creature::DespawnOrUnsummon(), Object::GetEntry(), ObjectAccessor::GetPlayer(), Unit::IsInCombat(), ScriptedAI::me, NPC_BALL_OF_INFERNO_FLAME, ScriptedAI::SelectTargetFromPlayerList(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetHover(), Creature::SetInCombatWithZone(), SPELL_BALL_OF_FLAMES_PERIODIC, UNIT_STATE_CASTING, and UNIT_STATE_STUNNED.
MoveInLineOfSight()
void npc_ball_of_flame::npc_ball_of_flameAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1274 of file boss_blood_prince_council.cpp.
 {}
MovementInform()
void npc_ball_of_flame::npc_ball_of_flameAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1276 of file boss_blood_prince_council.cpp.
         {
             if (type == CHASE_MOTION_TYPE && !_exploded)
             {
                 me->RemoveAurasDueToSpell(SPELL_BALL_OF_FLAMES_PERIODIC);
                 me->SetReactState(REACT_PASSIVE);
                 me->SetControlled(true, UNIT_STATE_ROOT);
                 me->StopMoving();
                 me->CastSpell(me, SPELL_FLAMES, true);
                 me->DespawnOrUnsummon(999);
                 me->CastSpell(me, SPELL_FLAME_SPHERE_DEATH_EFFECT, true);
                 _exploded = true;
             }
         }
References _exploded, Unit::CastSpell(), CHASE_MOTION_TYPE, Creature::DespawnOrUnsummon(), ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), Unit::SetControlled(), Creature::SetReactState(), SPELL_BALL_OF_FLAMES_PERIODIC, SPELL_FLAME_SPHERE_DEATH_EFFECT, SPELL_FLAMES, Unit::StopMoving(), and UNIT_STATE_ROOT.
SetGUID()
void npc_ball_of_flame::npc_ball_of_flameAI::SetGUID (ObjectGuid guid, int32) inline override virtual
Reimplemented from UnitAI.
Definition at line 1291 of file boss_blood_prince_council.cpp.
         {
             _chaseGUID = guid;
         }
References _chaseGUID.
Member Data Documentation
_chaseGUID
ObjectGuid npc_ball_of_flame::npc_ball_of_flameAI::_chaseGUID
Definition at line 1264 of file boss_blood_prince_council.cpp.
Referenced by DoAction(), and SetGUID().
_exploded
bool npc_ball_of_flame::npc_ball_of_flameAI::_exploded
Definition at line 1265 of file boss_blood_prince_council.cpp.
Referenced by MovementInform(), and npc_ball_of_flameAI().
_instance
InstanceScript* npc_ball_of_flame::npc_ball_of_flameAI::_instance
Definition at line 1263 of file boss_blood_prince_council.cpp.
Referenced by DamageDealt().
_started
bool npc_ball_of_flame::npc_ball_of_flameAI::_started
Definition at line 1266 of file boss_blood_prince_council.cpp.
Referenced by AttackStart(), DoAction(), and npc_ball_of_flameAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp