Azerotcore-wotlk: Acore::AnyPlayerInObjectRangeCheck Class Reference
Acore::AnyPlayerInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyPlayerInObjectRangeCheck (WorldObject const *obj, float range, bool reqAlive=true, bool disallowGM=false)
bool operator() (Player *u)
bool operator() (Player *u, bool checkRange)
Private Attributes
WorldObject const * _obj
float _range
bool _reqAlive
bool _disallowGM
Detailed Description
Definition at line 1233 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyPlayerInObjectRangeCheck()
Acore::AnyPlayerInObjectRangeCheck::AnyPlayerInObjectRangeCheck (WorldObject const * obj, float range, bool reqAlive = true, bool disallowGM = false) inline
Definition at line 1236 of file GridNotifiers.h.
 : _obj(obj), _range(range), _reqAlive(reqAlive), _disallowGM(disallowGM) {}
Member Function Documentation
operator()() [1/2]
bool Acore::AnyPlayerInObjectRangeCheck::operator() (Player * u) inline
Definition at line 1237 of file GridNotifiers.h.
         {
             if (_reqAlive && !u->IsAlive())
                 return false;
             if (_disallowGM && (u->IsGameMaster() || u->IsSpectator()))
                 return false;
             if (!_obj->IsWithinDistInMap(u, _range))
                 return false;
             return true;
         }
References _disallowGM, _obj, _range, _reqAlive, Unit::IsAlive(), Player::IsGameMaster(), Player::IsSpectator(), and WorldObject::IsWithinDistInMap().
operator()() [2/2]
bool Acore::AnyPlayerInObjectRangeCheck::operator() (Player * u, bool checkRange) inline
Definition at line 1252 of file GridNotifiers.h.
         {
             if (checkRange && !_obj->IsWithinDistInMap(u, _range))
                 return false;
             return true;
         }
References _obj, _range, and WorldObject::IsWithinDistInMap().
Member Data Documentation
_disallowGM
bool Acore::AnyPlayerInObjectRangeCheck::_disallowGM private
Definition at line 1264 of file GridNotifiers.h.
Referenced by operator()().
_obj
WorldObject const* Acore::AnyPlayerInObjectRangeCheck::_obj private
Definition at line 1261 of file GridNotifiers.h.
Referenced by operator()().
_range
float Acore::AnyPlayerInObjectRangeCheck::_range private
Definition at line 1262 of file GridNotifiers.h.
Referenced by operator()().
_reqAlive
bool Acore::AnyPlayerInObjectRangeCheck::_reqAlive private
Definition at line 1263 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h