Azerotcore-wotlk: G3D::MemoryManager Class Reference
G3D::MemoryManager Class Reference
#include <MemoryManager.h>
Public Types
typedef shared_ptr< class MemoryManager > Ref
Public Member Functions
virtual void * alloc (size_t s)
virtual void free (void *ptr)
virtual bool isThreadsafe () const
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static MemoryManager::Ref create ()
Protected Member Functions
MemoryManager ()
Detailed Description
Abstraction of memory management. Default implementation uses G3D::System::malloc and is threadsafe.
See also
LargePoolMemoryManager, CRTMemoryManager, AlignedMemoryManager, AreaMemoryManager
Definition at line 24 of file MemoryManager.h.
Member Typedef Documentation
Ref
typedef shared_ptr<class MemoryManager> G3D::MemoryManager::Ref
Definition at line 31 of file MemoryManager.h.
Constructor & Destructor Documentation
MemoryManager()
G3D::MemoryManager::MemoryManager () protected
Definition at line 17 of file MemoryManager.cpp.
 {}
Referenced by create().
Member Function Documentation
alloc()
void * G3D::MemoryManager::alloc (size_t s) virtual
Return a pointer to s bytes of memory that are unused by the rest of the program. The contents of the memory are undefined
Reimplemented in G3D::CRTMemoryManager, G3D::AlignedMemoryManager, and G3D::AreaMemoryManager.
Definition at line 20 of file MemoryManager.cpp.
{
     return System::malloc(s);
 }
References G3D::System::malloc().
create()
MemoryManager::Ref G3D::MemoryManager::create () static
Return the instance. There's only one instance of the default MemoryManager; it is cached after the first creation.
Definition at line 35 of file MemoryManager.cpp.
{
     static MemoryManager::Ref m(new MemoryManager());
     return m;
 }
References MemoryManager().
Referenced by G3D::Array< T, MIN_ELEMENTS >::_copy(), G3D::Array< T, MIN_ELEMENTS >::Array(), G3D::Any::Data::create(), G3D::Any::Data::destroy(), G3D::MeshEdgeTable::MeshEdgeTable(), G3D::_internal::WeldHelper::smoothNormals(), and G3D::Table< Key, Value, HashFunc, EqualsFunc >::Table().
free()
void G3D::MemoryManager::free (void * ptr) virtual
Invoke to declare that this memory will no longer be used by the program. The memory manager is not required to actually reuse or release this memory.
Reimplemented in G3D::AreaMemoryManager, G3D::CRTMemoryManager, and G3D::AlignedMemoryManager.
Definition at line 25 of file MemoryManager.cpp.
{
     System::free(ptr);
 }
References G3D::System::free(), and ptr().
isThreadsafe()
bool G3D::MemoryManager::isThreadsafe () const virtual
Returns true if this memory manager is threadsafe (i.e., alloc and free can be called asychronously)
Reimplemented in G3D::CRTMemoryManager, G3D::AlignedMemoryManager, and G3D::AreaMemoryManager.
Definition at line 30 of file MemoryManager.cpp.
{
     return true;
 }
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/MemoryManager.h
deps/g3dlite/source/MemoryManager.cpp