Azerotcore-wotlk: deps/mysqllite/mysys/my_init.c File Reference
my_init.c File Reference
#include "mysys_priv.h"
#include "my_static.h"
#include "mysys_err.h"
#include <m_string.h>
#include <m_ctype.h>
#include <signal.h>
Macros
#define my_win_init()
#define SCALE_SEC 100
#define SCALE_USEC 10000
Functions
static ulong atoi_octal (const char *str)
my_bool my_basic_init (void)
my_bool my_init (void)
void my_end (int infoflag)
Variables
my_bool my_init_done = 0
my_bool my_basic_init_done = 0
uint mysys_usage_id = 0
ulong my_thread_stack_size = 65536
MYSQL_FILE * mysql_stdin = NULL
static MYSQL_FILE instrumented_stdin
Macro Definition Documentation
my_win_init
#define my_win_init ()
Definition at line 33 of file my_init.c.
SCALE_SEC
#define SCALE_SEC 100
Definition at line 36 of file my_init.c.
SCALE_USEC
#define SCALE_USEC 10000
Definition at line 37 of file my_init.c.
Function Documentation
atoi_octal()
static ulong atoi_octal (const char * str) static
Definition at line 45 of file my_init.c.
 {
   long int tmp;
   while (*str && my_isspace(&my_charset_latin1, *str))
     str++;
   str2int(str,
       (*str == '0' ? 8 : 10),       /* Octalt or decimalt */
       0, INT_MAX, &tmp);
   return (ulong) tmp;
 }
References my_charset_latin1, my_isspace, and str2int().
Referenced by my_basic_init().
my_basic_init()
my_bool my_basic_init (void)
Perform a limited initialisation of mysys. This initialisation is sufficient to:
allocate memory,
read configuration files,
parse command lines arguments. To complete the mysys initialisation, call my_init().
Returns
0 on success
Definition at line 69 of file my_init.c.
 {
   char * str;
   if (my_basic_init_done)
     return 0;
   my_basic_init_done= 1;
   mysys_usage_id++;
   my_umask= 0660;                       /* Default umask for new files */
   my_umask_dir= 0700;                   /* Default umask for new directories */
   /* Default creation of new files */
   if ((str= getenv("UMASK")) != 0)
     my_umask= (int) (atoi_octal(str) | 0600);
   /* Default creation of new dir's */
   if ((str= getenv("UMASK_DIR")) != 0)
     my_umask_dir= (int) (atoi_octal(str) | 0700);
   init_glob_errs();
   instrumented_stdin.m_file= stdin;
   instrumented_stdin.m_psi= NULL;       /* not yet instrumented */
   mysql_stdin= & instrumented_stdin;
   if (my_thread_global_init())
     return 1;
 #if defined(SAFE_MUTEX)
   safe_mutex_global_init();     /* Must be called early */
 #endif
 #if defined(MY_PTHREAD_FASTMUTEX) && !defined(SAFE_MUTEX)
   fastmutex_global_init();              /* Must be called early */
 #endif
 #if defined(HAVE_PTHREAD_INIT)
   pthread_init();           /* Must be called before DBUG_ENTER */
 #endif
   if (my_thread_basic_global_init())
     return 1;
   /* $HOME is needed early to parse configuration files located in ~/ */
   if ((home_dir= getenv("HOME")) != 0)
     home_dir= intern_filename(home_dir_buff, home_dir);
   return 0;
 }
References atoi_octal(), home_dir, home_dir_buff, init_glob_errs(), instrumented_stdin, intern_filename(), st_mysql_file::m_file, st_mysql_file::m_psi, my_basic_init_done, my_thread_basic_global_init(), my_thread_global_init(), my_umask, my_umask_dir, mysql_stdin, mysys_usage_id, NULL, and safe_mutex_global_init().
Referenced by my_init().
my_end()
void my_end (int infoflag)
Definition at line 158 of file my_init.c.
 {
   /*
     this code is suboptimal to workaround a bug in
     Sun CC: Sun C++ 5.6 2004/06/02 for x86, and should not be
     optimized until this compiler is not in use anymore
   */
   FILE *info_file= DBUG_FILE;
   my_bool print_info= (info_file != stderr);
   if (!my_init_done)
     return;
   /*
     We do not use DBUG_ENTER here, as after cleanup DBUG is no longer
     operational, so we cannot use DBUG_RETURN.
   */
   DBUG_PRINT("info",("Shutting down: infoflag: %d  print_info: %d",
                      infoflag, print_info));
   if (!info_file)
   {
     info_file= stderr;
     print_info= 0;
   }
   if ((infoflag & MY_CHECK_ERROR) || print_info)
   {                 /* Test if some file is left open */
     if (my_file_opened | my_stream_opened)
     {
       char ebuff[512];
       my_snprintf(ebuff, sizeof(ebuff), EE(EE_OPEN_WARNING),
                   my_file_opened, my_stream_opened);
       my_message_stderr(EE_OPEN_WARNING, ebuff, ME_BELL);
       DBUG_PRINT("error", ("%s", ebuff));
       my_print_open_files();
     }
   }
   free_charsets();
   my_error_unregister_all();
   my_once_free();
   if ((infoflag & MY_GIVE_INFO) || print_info)
   {
 #ifdef HAVE_GETRUSAGE
     struct rusage rus;
 #ifdef HAVE_purify
     /* Purify assumes that rus is uninitialized after getrusage call */
     bzero((char*) &rus, sizeof(rus));
 #endif
     if (!getrusage(RUSAGE_SELF, &rus))
       fprintf(info_file,"\n\
 User time %.2f, System time %.2f\n\
 Maximum resident set size %ld, Integral resident set size %ld\n\
 Non-physical pagefaults %ld, Physical pagefaults %ld, Swaps %ld\n\
 Blocks in %ld out %ld, Messages in %ld out %ld, Signals %ld\n\
 Voluntary context switches %ld, Involuntary context switches %ld\n",
           (rus.ru_utime.tv_sec * SCALE_SEC +
            rus.ru_utime.tv_usec / SCALE_USEC) / 100.0,
           (rus.ru_stime.tv_sec * SCALE_SEC +
            rus.ru_stime.tv_usec / SCALE_USEC) / 100.0,
           rus.ru_maxrss, rus.ru_idrss,
           rus.ru_minflt, rus.ru_majflt,
           rus.ru_nswap, rus.ru_inblock, rus.ru_oublock,
           rus.ru_msgsnd, rus.ru_msgrcv, rus.ru_nsignals,
           rus.ru_nvcsw, rus.ru_nivcsw);
 #endif
 #if defined(__WIN__) && defined(_MSC_VER)
    _CrtSetReportMode( _CRT_WARN, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_WARN, _CRTDBG_FILE_STDERR );
    _CrtSetReportMode( _CRT_ERROR, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_ERROR, _CRTDBG_FILE_STDERR );
    _CrtSetReportMode( _CRT_ASSERT, _CRTDBG_MODE_FILE );
    _CrtSetReportFile( _CRT_ASSERT, _CRTDBG_FILE_STDERR );
    _CrtCheckMemory();
    _CrtDumpMemoryLeaks();
 #endif
   }
   if (!(infoflag & MY_DONT_FREE_DBUG))
   {
     DBUG_END();                /* Must be done before my_thread_end */
   }
   my_thread_end();
   my_thread_global_end();
 #if defined(SAFE_MUTEX)
   /*
     Check on destroying of mutexes. A few may be left that will get cleaned
     up by C++ destructors
   */
   safe_mutex_end((infoflag & (MY_GIVE_INFO | MY_CHECK_ERROR)) ? stderr :
                  (FILE *) 0);
 #endif /* defined(SAFE_MUTEX) */
 #ifdef __WIN__
   if (have_tcpip)
     WSACleanup();
 #endif /* __WIN__ */
   my_init_done=0;
   my_basic_init_done= 0;
 } /* my_end */
References bzero, DBUG_END, DBUG_FILE, DBUG_PRINT, EE, EE_OPEN_WARNING, fprintf(), free_charsets(), ME_BELL, my_basic_init_done, MY_CHECK_ERROR, MY_DONT_FREE_DBUG, my_error_unregister_all(), my_file_opened, MY_GIVE_INFO, my_init_done, my_message_stderr(), my_once_free(), my_print_open_files, my_snprintf(), my_stream_opened, my_thread_end(), my_thread_global_end(), safe_mutex_end(), SCALE_SEC, and SCALE_USEC.
Referenced by mysql_server_end().
my_init()
my_bool my_init (void)
Definition at line 130 of file my_init.c.
 {
   if (my_init_done)
     return 0;
   my_init_done= 1;
   if (my_basic_init())
     return 1;
   if (my_thread_global_init())
     return 1;
   {
     DBUG_ENTER("my_init");
     DBUG_PROCESS((char*) (my_progname ? my_progname : "unknown"));
     my_win_init();
     DBUG_PRINT("exit", ("home: '%s'", home_dir));
 #ifdef __WIN__
     win32_init_tcp_ip();
 #endif
     DBUG_RETURN(0);
   }
 } /* my_init */
References DBUG_ENTER, DBUG_PRINT, DBUG_PROCESS, DBUG_RETURN, home_dir, my_basic_init(), my_init_done, my_progname, my_thread_global_init(), and my_win_init.
Referenced by mysql_server_init().
Variable Documentation
instrumented_stdin
MYSQL_FILE instrumented_stdin static
Definition at line 57 of file my_init.c.
Referenced by my_basic_init().
my_basic_init_done
my_bool my_basic_init_done = 0
True if my_basic_init() has been called.
Definition at line 41 of file my_init.c.
Referenced by my_basic_init(), and my_end().
my_init_done
my_bool my_init_done = 0
Definition at line 39 of file my_init.c.
Referenced by my_end(), my_init(), and mysql_server_init().
my_thread_stack_size
ulong my_thread_stack_size = 65536
Definition at line 43 of file my_init.c.
Referenced by my_thread_init().
mysql_stdin
MYSQL_FILE* mysql_stdin = NULL
Definition at line 56 of file my_init.c.
Referenced by my_basic_init().
mysys_usage_id
uint mysys_usage_id = 0
Definition at line 42 of file my_init.c.
Referenced by my_basic_init().