Azerotcore-wotlk: pyrewood_ambush Class Reference
pyrewood_ambush Class Reference
Classes
struct pyrewood_ambushAI
Public Member Functions
pyrewood_ambush ()
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 165 of file zone_silverpine_forest.cpp.
Constructor & Destructor Documentation
pyrewood_ambush()
pyrewood_ambush::pyrewood_ambush () inline
Definition at line 168 of file zone_silverpine_forest.cpp.
 : CreatureScript("pyrewood_ambush") { }
Member Function Documentation
GetAI()
CreatureAI* pyrewood_ambush::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 183 of file zone_silverpine_forest.cpp.
     {
         return new pyrewood_ambushAI(creature);
     }
OnQuestAccept()
bool pyrewood_ambush::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 170 of file zone_silverpine_forest.cpp.
     {
         if (quest->GetQuestId() == QUEST_PYREWOOD_AMBUSH && !CAST_AI(pyrewood_ambush::pyrewood_ambushAI, creature->AI())->QuestInProgress)
         {
             CAST_AI(pyrewood_ambush::pyrewood_ambushAI, creature->AI())->QuestInProgress = true;
             CAST_AI(pyrewood_ambush::pyrewood_ambushAI, creature->AI())->Phase = 0;
             CAST_AI(pyrewood_ambush::pyrewood_ambushAI, creature->AI())->KillCount = 0;
             CAST_AI(pyrewood_ambush::pyrewood_ambushAI, creature->AI())->PlayerGUID = player->GetGUID();
         }
         return true;
     }
References Creature::AI(), CAST_AI, Object::GetGUID(), Quest::GetQuestId(), and QUEST_PYREWOOD_AMBUSH.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp