Azerotcore-wotlk: Acore::Banner Namespace Reference
Acore::Banner Namespace Reference
Functions
AC_COMMON_API void Show (std::string_view applicationName, void(*log)(std::string_view text), void(*logExtraInfo)())
Function Documentation
Show()
void Acore::Banner::Show (std::string_view applicationName, void(*)(std::string_view text) log, void(*)() logExtraInfo)
Definition at line 9 of file Banner.cpp.
 {
     log(Acore::StringFormatFmt("{} ({})", GitRevision::GetFullVersion(), applicationName));
     log("<Ctrl-C> to stop.\n");
     log("   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗");
     log("  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║");
     log("  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║");
     log("  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║");
     log("  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║");
     log("  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝");
     log("                                 ██████╗ ██████╗ ██████╗ ███████╗");
     log("                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝");
     log("                                ██║     ██║   ██║██████╔╝█████╗");
     log("                                ██║     ██║   ██║██╔══██╗██╔══╝");
     log("                                ╚██████╗╚██████╔╝██║  ██║███████╗");
     log("                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝\n");
     log("     AzerothCore 3.3.5a  -  www.azerothcore.org\n");
     if (logExtraInfo)
     {
         logExtraInfo();
     }
     log(" ");
 }
References GitRevision::GetFullVersion(), G3D::log(), and Acore::StringFormatFmt().
Referenced by main().