Azerotcore-wotlk: npc_great_bear_spirit Class Reference
npc_great_bear_spirit Class Reference
Public Member Functions
npc_great_bear_spirit ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 117 of file zone_moonglade.cpp.
Constructor & Destructor Documentation
npc_great_bear_spirit()
npc_great_bear_spirit::npc_great_bear_spirit () inline
Definition at line 120 of file zone_moonglade.cpp.
 : CreatureScript("npc_great_bear_spirit") { }
Member Function Documentation
OnGossipHello()
bool npc_great_bear_spirit::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 150 of file zone_moonglade.cpp.
     {
         //ally or horde quest
         if (player->GetQuestStatus(5929) == QUEST_STATUS_INCOMPLETE || player->GetQuestStatus(5930) == QUEST_STATUS_INCOMPLETE)
         {
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BEAR1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
             SendGossipMenuFor(player, 4719, creature->GetGUID());
         }
         else
             SendGossipMenuFor(player, 4718, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_BEAR1, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_great_bear_spirit::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 122 of file zone_moonglade.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BEAR2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 SendGossipMenuFor(player, 4721, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BEAR3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, 4733, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BEAR4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 SendGossipMenuFor(player, 4734, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 SendGossipMenuFor(player, 4735, creature->GetGUID());
                 if (player->GetQuestStatus(5929) == QUEST_STATUS_INCOMPLETE)
                     player->AreaExploredOrEventHappens(5929);
                 if (player->GetQuestStatus(5930) == QUEST_STATUS_INCOMPLETE)
                     player->AreaExploredOrEventHappens(5930);
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Player::AreaExploredOrEventHappens(), ClearGossipMenuFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_BEAR2, GOSSIP_BEAR3, GOSSIP_BEAR4, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_moonglade.cpp