Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/div.h File Reference
div.h File Reference
#include "jemalloc/internal/assert.h"
Classes
struct div_info_s
Typedefs
typedef struct div_info_s div_info_t
Functions
void div_init (div_info_t *div_info, size_t divisor)
static size_t div_compute (div_info_t *div_info, size_t n)
Typedef Documentation
div_info_t
typedef struct div_info_s div_info_t
Definition at line 1 of file div.h.
Function Documentation
div_compute()
static size_t div_compute (div_info_t * div_info, size_t n) inline static
Definition at line 26 of file div.h.
{
     assert(n <= (uint32_t)-1);
     /*
      * This generates, e.g. mov; imul; shr on x86-64. On a 32-bit machine,
      * the compilers I tried were all smart enough to turn this into the
      * appropriate "get the high 32 bits of the result of a multiply" (e.g.
      * mul; mov edx eax; on x86, umull on arm, etc.).
      */
     size_t i = ((uint64_t)n * (uint64_t)div_info->magic) >> 32;
 #ifdef JEMALLOC_DEBUG
     assert(i * div_info->d == n);
 #endif
     return i;
 }
References assert(), and div_info_s::magic.
Referenced by arena_slab_regind().
div_init()
void div_init (div_info_t * div_info, size_t divisor)
Definition at line 30 of file div.c.
{
     /* Nonsensical. */
     assert(d != 0);
     /*
      * This would make the value of magic too high to fit into a uint32_t
      * (we would want magic = 2^32 exactly). This would mess with code gen
      * on 32-bit machines.
      */
     assert(d != 1);
     uint64_t two_to_k = ((uint64_t)1 << 32);
     uint32_t magic = (uint32_t)(two_to_k / d);
     /*
      * We want magic = ceil(2^k / d), but C gives us floor. We have to
      * increment it unless the result was exact (i.e. unless d is a power of
      * two).
      */
     if (two_to_k % d != 0) {
         magic++;
     }
     div_info->magic = magic;
 #ifdef JEMALLOC_DEBUG
     div_info->d = d;
 #endif
 }
References assert(), mpq::d, and div_info_s::magic.