Azerotcore-wotlk: detail::formatbuf< Char > Class Template Reference
detail::formatbuf< Char > Class Template Reference
#include <ostream.h>
Public Member Functions
formatbuf (buffer< Char > &buf)
Protected Member Functions
int_type overflow (int_type ch=traits_type::eof()) FMT_OVERRIDE
std::streamsize xsputn (const Char *s, std::streamsize count) FMT_OVERRIDE
Private Types
using int_type = typename std::basic_streambuf< Char >::int_type
using traits_type = typename std::basic_streambuf< Char >::traits_type
Private Attributes
buffer< Char > & buffer_
Detailed Description
template<class Char>
class detail::formatbuf< Char >
Definition at line 22 of file ostream.h.
Member Typedef Documentation
int_type
template<class Char > using detail::formatbuf< Char >::int_type = typename std::basic_streambuf<Char>::int_type private
Definition at line 24 of file ostream.h.
traits_type
template<class Char > using detail::formatbuf< Char >::traits_type = typename std::basic_streambuf<Char>::traits_type private
Definition at line 25 of file ostream.h.
Constructor & Destructor Documentation
formatbuf()
template<class Char > detail::formatbuf< Char >::formatbuf (buffer< Char > & buf) inline
Definition at line 30 of file ostream.h.
 : buffer_(buf) {}
Member Function Documentation
overflow()
template<class Char > int_type detail::formatbuf< Char >::overflow (int_type ch = traits_type::eof()) inline protected
Definition at line 40 of file ostream.h.
{
     if (!traits_type::eq_int_type(ch, traits_type::eof()))
       buffer_.push_back(static_cast<Char>(ch));
     return ch;
   }
References detail::formatbuf< Char >::buffer_, and buffer< T >::push_back().
xsputn()
template<class Char > std::streamsize detail::formatbuf< Char >::xsputn (const Char * s, std::streamsize count) inline protected
Definition at line 46 of file ostream.h.
{
     buffer_.append(s, s + count);
     return count;
   }
References buffer< T >::append(), detail::formatbuf< Char >::buffer_, and count().
Member Data Documentation
buffer_
template<class Char > buffer<Char>& detail::formatbuf< Char >::buffer_ private
Definition at line 27 of file ostream.h.
Referenced by detail::formatbuf< Char >::overflow(), and detail::formatbuf< Char >::xsputn().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/ostream.h