Azerotcore-wotlk: specs_handler< Char > Class Template Reference
specs_handler< Char > Class Template Reference
#include <format.h>
Public Member Functions
FMT_CONSTEXPR specs_handler (basic_format_specs< Char > &specs, basic_format_parse_context< Char > &parse_ctx, buffer_context< Char > &ctx)
template<typename Id >
FMT_CONSTEXPR void on_dynamic_width (Id arg_id)
template<typename Id >
FMT_CONSTEXPR void on_dynamic_precision (Id arg_id)
void on_error (const char *message)
Public Member Functions inherited from specs_setter< Char >
FMT_CONSTEXPR specs_setter (basic_format_specs< Char > &specs)
FMT_CONSTEXPR specs_setter (const specs_setter &other)
FMT_CONSTEXPR void on_align (align_t align)
FMT_CONSTEXPR void on_fill (basic_string_view< Char > fill)
FMT_CONSTEXPR void on_sign (sign_t s)
FMT_CONSTEXPR void on_hash ()
FMT_CONSTEXPR void on_localized ()
FMT_CONSTEXPR void on_zero ()
FMT_CONSTEXPR void on_width (int width)
FMT_CONSTEXPR void on_precision (int precision)
FMT_CONSTEXPR void end_precision ()
FMT_CONSTEXPR void on_type (Char type)
Private Types
using format_arg = basic_format_arg< buffer_context< Char > >
Private Member Functions
FMT_CONSTEXPR auto get_arg (auto_id) -> format_arg
FMT_CONSTEXPR auto get_arg (int arg_id) -> format_arg
FMT_CONSTEXPR auto get_arg (basic_string_view< Char > arg_id) -> format_arg
Private Attributes
basic_format_parse_context< Char > & parse_context_
buffer_context< Char > & context_
Additional Inherited Members
Protected Attributes inherited from specs_setter< Char >
basic_format_specs< Char > & specs_
Detailed Description
template<typename Char>
class specs_handler< Char >
Definition at line 2072 of file format.h.
Member Typedef Documentation
format_arg
template<typename Char > using specs_handler< Char >::format_arg = basic_format_arg<buffer_context<Char> > private
Definition at line 2078 of file format.h.
Constructor & Destructor Documentation
specs_handler()
template<typename Char > FMT_CONSTEXPR specs_handler< Char >::specs_handler (basic_format_specs< Char > & specs, basic_format_parse_context< Char > & parse_ctx, buffer_context< Char > & ctx) inline
Definition at line 2095 of file format.h.
       : specs_setter<Char>(specs), parse_context_(parse_ctx), context_(ctx) {}
Member Function Documentation
get_arg() [1/3]
template<typename Char > FMT_CONSTEXPR auto specs_handler< Char >::get_arg (auto_id) -> format_arg inline private
Definition at line 2080 of file format.h.
{
     return detail::get_arg(context_, parse_context_.next_arg_id());
   }
References get_arg(), and basic_format_parse_context< Char, ErrorHandler >::next_arg_id().
get_arg() [2/3]
template<typename Char > FMT_CONSTEXPR auto specs_handler< Char >::get_arg (basic_string_view< Char > arg_id) -> format_arg inline private
Definition at line 2089 of file format.h.
{
     parse_context_.check_arg_id(arg_id);
     return detail::get_arg(context_, arg_id);
   }
References basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), and get_arg().
get_arg() [3/3]
template<typename Char > FMT_CONSTEXPR auto specs_handler< Char >::get_arg (int arg_id) -> format_arg inline private
Definition at line 2084 of file format.h.
{
     parse_context_.check_arg_id(arg_id);
     return detail::get_arg(context_, arg_id);
   }
References basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), and get_arg().
on_dynamic_precision()
template<typename Char > template<typename Id > FMT_CONSTEXPR void specs_handler< Char >::on_dynamic_precision (Id arg_id) inline
Definition at line 2105 of file format.h.
{
     this->specs_.precision = get_dynamic_spec<precision_checker>(
         get_arg(arg_id), context_.error_handler());
   }
References basic_format_context< OutputIt, Char >::error_handler(), and get_arg().
on_dynamic_width()
template<typename Char > template<typename Id > FMT_CONSTEXPR void specs_handler< Char >::on_dynamic_width (Id arg_id) inline
Definition at line 2100 of file format.h.
{
     this->specs_.width = get_dynamic_spec<width_checker>(
         get_arg(arg_id), context_.error_handler());
   }
References basic_format_context< OutputIt, Char >::error_handler(), and get_arg().
on_error()
template<typename Char > void specs_handler< Char >::on_error (const char * message) inline
Definition at line 2110 of file format.h.
 { context_.on_error(message); }
References message(), and basic_format_context< OutputIt, Char >::on_error().
Member Data Documentation
context_
template<typename Char > buffer_context<Char>& specs_handler< Char >::context_ private
Definition at line 2075 of file format.h.
parse_context_
template<typename Char > basic_format_parse_context<Char>& specs_handler< Char >::parse_context_ private
Definition at line 2074 of file format.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/format.h