Azerotcore-wotlk: deps/mysqllite/include/internal/my_bitmap.h File Reference
my_bitmap.h File Reference
#include <m_string.h>
Classes
struct st_bitmap
Macros
#define MY_BIT_NONE (~(uint) 0)
#define bitmap_buffer_size(bits) (((bits)+31)/32)*4
#define no_bytes_in_map(map) (((map)->n_bits + 7)/8)
#define no_words_in_map(map) (((map)->n_bits + 31)/32)
#define bytes_word_aligned(bytes) (4*((bytes + 3)/4))
#define _bitmap_set_bit(MAP, BIT)
#define _bitmap_flip_bit(MAP, BIT)
#define _bitmap_clear_bit(MAP, BIT)
#define _bitmap_is_set(MAP, BIT)
#define bitmap_clear_all(MAP) { memset((MAP)->bitmap, 0, 4*no_words_in_map((MAP))); }
#define bitmap_set_all(MAP) (memset((MAP)->bitmap, 0xFF, 4*no_words_in_map((MAP))))
Typedefs
typedef uint32 my_bitmap_map
typedef struct st_bitmap MY_BITMAP
Functions
void create_last_word_mask (MY_BITMAP *map)
my_bool bitmap_init (MY_BITMAP *map, my_bitmap_map *buf, uint n_bits, my_bool thread_safe)
my_bool bitmap_is_clear_all (const MY_BITMAP *map)
my_bool bitmap_is_prefix (const MY_BITMAP *map, uint prefix_size)
my_bool bitmap_is_set_all (const MY_BITMAP *map)
my_bool bitmap_is_subset (const MY_BITMAP *map1, const MY_BITMAP *map2)
my_bool bitmap_is_overlapping (const MY_BITMAP *map1, const MY_BITMAP *map2)
my_bool bitmap_test_and_set (MY_BITMAP *map, uint bitmap_bit)
my_bool bitmap_test_and_clear (MY_BITMAP *map, uint bitmap_bit)
my_bool bitmap_fast_test_and_set (MY_BITMAP *map, uint bitmap_bit)
uint bitmap_set_next (MY_BITMAP *map)
uint bitmap_get_first (const MY_BITMAP *map)
uint bitmap_get_first_set (const MY_BITMAP *map)
uint bitmap_bits_set (const MY_BITMAP *map)
void bitmap_free (MY_BITMAP *map)
void bitmap_set_above (MY_BITMAP *map, uint from_byte, uint use_bit)
void bitmap_set_prefix (MY_BITMAP *map, uint prefix_size)
void bitmap_intersect (MY_BITMAP *map, const MY_BITMAP *map2)
void bitmap_subtract (MY_BITMAP *map, const MY_BITMAP *map2)
void bitmap_union (MY_BITMAP *map, const MY_BITMAP *map2)
void bitmap_xor (MY_BITMAP *map, const MY_BITMAP *map2)
void bitmap_invert (MY_BITMAP *map)
void bitmap_copy (MY_BITMAP *map, const MY_BITMAP *map2)
uint bitmap_lock_set_next (MY_BITMAP *map)
void bitmap_lock_clear_bit (MY_BITMAP *map, uint bitmap_bit)
static void bitmap_set_bit (MY_BITMAP *map, uint bit)
static void bitmap_flip_bit (MY_BITMAP *map, uint bit)
static void bitmap_clear_bit (MY_BITMAP *map, uint bit)
static uint bitmap_is_set (const MY_BITMAP *map, uint bit)
static my_bool bitmap_cmp (const MY_BITMAP *map1, const MY_BITMAP *map2)
Macro Definition Documentation
_bitmap_clear_bit
#define _bitmap_clear_bit (MAP, BIT)
Value:
                                  (((uchar*)(MAP)->bitmap)[(BIT) / 8] \
                                  &= ~ (1 << ((BIT) & 7)))
Definition at line 79 of file my_bitmap.h.
_bitmap_flip_bit
#define _bitmap_flip_bit (MAP, BIT)
Value:
                                  (((uchar*)(MAP)->bitmap)[(BIT) / 8] \
                                  ^= (1 << ((BIT) & 7)))
Definition at line 77 of file my_bitmap.h.
_bitmap_is_set
#define _bitmap_is_set (MAP, BIT)
Value:
                                         (uint) (((uchar*)(MAP)->bitmap)[(BIT) / 8] \
                                         & (1 << ((BIT) & 7)))
Definition at line 81 of file my_bitmap.h.
_bitmap_set_bit
#define _bitmap_set_bit (MAP, BIT)
Value:
                                  (((uchar*)(MAP)->bitmap)[(BIT) / 8] \
                                  |= (1 << ((BIT) & 7)))
Definition at line 75 of file my_bitmap.h.
bitmap_buffer_size
#define bitmap_buffer_size (bits) (((bits)+31)/32)*4
Definition at line 71 of file my_bitmap.h.
bitmap_clear_all
#define bitmap_clear_all (MAP) { memset((MAP)->bitmap, 0, 4*no_words_in_map((MAP))); }
Definition at line 133 of file my_bitmap.h.
bitmap_set_all
#define bitmap_set_all (MAP) (memset((MAP)->bitmap, 0xFF, 4*no_words_in_map((MAP))))
Definition at line 135 of file my_bitmap.h.
bytes_word_aligned
#define bytes_word_aligned (bytes) (4*((bytes + 3)/4))
Definition at line 74 of file my_bitmap.h.
MY_BIT_NONE
#define MY_BIT_NONE (~(uint) 0)
Definition at line 19 of file my_bitmap.h.
no_bytes_in_map
#define no_bytes_in_map (map) (((map)->n_bits + 7)/8)
Definition at line 72 of file my_bitmap.h.
no_words_in_map
#define no_words_in_map (map) (((map)->n_bits + 31)/32)
Definition at line 73 of file my_bitmap.h.
Typedef Documentation
MY_BITMAP
typedef struct st_bitmap MY_BITMAP
my_bitmap_map
typedef uint32 my_bitmap_map
Definition at line 23 of file my_bitmap.h.
Function Documentation
bitmap_bits_set()
uint bitmap_bits_set (const MY_BITMAP * map)
Definition at line 453 of file my_bitmap.c.
 {
   uchar *m= (uchar*)map->bitmap;
   uchar *end= m + no_bytes_in_map(map);
   uint res= 0;
   DBUG_ASSERT(map->bitmap);
   *map->last_word_ptr&= ~map->last_word_mask; /*Reset last bits to zero*/
   while (m < end)
     res+= my_count_bits_ushort(*m++);
   return res;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, my_count_bits_ushort(), and no_bytes_in_map.
bitmap_clear_bit()
static void bitmap_clear_bit (MY_BITMAP * map, uint bit) inline static
Definition at line 108 of file my_bitmap.h.
 {
   DBUG_ASSERT(bit < (map)->n_bits);
   _bitmap_clear_bit(map,bit);
 }
References _bitmap_clear_bit, and DBUG_ASSERT.
Referenced by bitmap_lock_clear_bit().
bitmap_cmp()
static my_bool bitmap_cmp (const MY_BITMAP * map1, const MY_BITMAP * map2) inline static
Definition at line 126 of file my_bitmap.h.
 {
   *(map1)->last_word_ptr|= (map1)->last_word_mask;
   *(map2)->last_word_ptr|= (map2)->last_word_mask;
   return memcmp((map1)->bitmap, (map2)->bitmap, 4*no_words_in_map((map1)))==0;
 }
References no_words_in_map.
bitmap_copy()
void bitmap_copy (MY_BITMAP * map, const MY_BITMAP * map2)
Definition at line 467 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *from= map2->bitmap, *end;
   DBUG_ASSERT(map->bitmap && map2->bitmap &&
               map->n_bits==map2->n_bits);
   end= map->last_word_ptr;
   while (to <= end)
     *to++ = *from++;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
bitmap_fast_test_and_set()
my_bool bitmap_fast_test_and_set (MY_BITMAP * map, uint bitmap_bit)
Definition at line 165 of file my_bitmap.c.
 {
   uchar *value= ((uchar*) map->bitmap) + (bitmap_bit / 8);
   uchar bit= 1 << ((bitmap_bit) & 7);
   uchar res= (*value) & bit;
   *value|= bit;
   return res;
 }
References st_bitmap::bitmap.
Referenced by bitmap_test_and_set().
bitmap_flip_bit()
static void bitmap_flip_bit (MY_BITMAP * map, uint bit) inline static
Definition at line 102 of file my_bitmap.h.
 {
   DBUG_ASSERT(bit < (map)->n_bits);
   _bitmap_flip_bit(map,bit);
 }
References _bitmap_flip_bit, and DBUG_ASSERT.
bitmap_free()
void bitmap_free (MY_BITMAP * map)
Definition at line 137 of file my_bitmap.c.
 {
   DBUG_ENTER("bitmap_free");
   if (map->bitmap)
   {
     if (map->mutex)
       mysql_mutex_destroy(map->mutex);
     my_free(map->bitmap);
     map->bitmap=0;
   }
   DBUG_VOID_RETURN;
 }
References st_bitmap::bitmap, DBUG_ENTER, DBUG_VOID_RETURN, st_bitmap::mutex, my_free(), and mysql_mutex_destroy.
bitmap_get_first()
uint bitmap_get_first (const MY_BITMAP * map)
Definition at line 511 of file my_bitmap.c.
 {
   uchar *byte_ptr;
   uint i,j,k;
   my_bitmap_map *data_ptr, *end= map->last_word_ptr;
   DBUG_ASSERT(map->bitmap);
   data_ptr= map->bitmap;
   *map->last_word_ptr|= map->last_word_mask;
   for (i=0; data_ptr <= end; data_ptr++, i++)
   {
     if (*data_ptr != 0xFFFFFFFF)
     {
       byte_ptr= (uchar*)data_ptr;
       for (j=0; ; j++, byte_ptr++)
       {
         if (*byte_ptr != 0xFF)
         {
           for (k=0; ; k++)
           {
             if (!(*byte_ptr & (1 << k)))
               return (i*32) + (j*8) + k;
           }
         }
       }
     }
   }
   return MY_BIT_NONE;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and MY_BIT_NONE.
Referenced by bitmap_set_next().
bitmap_get_first_set()
uint bitmap_get_first_set (const MY_BITMAP * map)
Definition at line 479 of file my_bitmap.c.
 {
   uchar *byte_ptr;
   uint i,j,k;
   my_bitmap_map *data_ptr, *end= map->last_word_ptr;
   DBUG_ASSERT(map->bitmap);
   data_ptr= map->bitmap;
   *map->last_word_ptr &= ~map->last_word_mask;
   for (i=0; data_ptr <= end; data_ptr++, i++)
   {
     if (*data_ptr)
     {
       byte_ptr= (uchar*)data_ptr;
       for (j=0; ; j++, byte_ptr++)
       {
         if (*byte_ptr)
         {
           for (k=0; ; k++)
           {
             if (*byte_ptr & (1 << k))
               return (i*32) + (j*8) + k;
           }
         }
       }
     }
   }
   return MY_BIT_NONE;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and MY_BIT_NONE.
bitmap_init()
my_bool bitmap_init (MY_BITMAP * map, my_bitmap_map * buf, uint n_bits, my_bool thread_safe)
bitmap_intersect()
void bitmap_intersect (MY_BITMAP * map, const MY_BITMAP * map2)
Definition at line 353 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *from= map2->bitmap, *end;
   uint len= no_words_in_map(map), len2 = no_words_in_map(map2);
   DBUG_ASSERT(map->bitmap && map2->bitmap);
   end= to+min(len,len2);
   *map2->last_word_ptr&= ~map2->last_word_mask; /*Clear last bits in map2*/
   while (to < end)
     *to++ &= *from++;
   if (len2 < len)
   {
     end+=len-len2;
     while (to < end)
       *to++=0;
   }
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, min, and no_words_in_map.
bitmap_invert()
void bitmap_invert (MY_BITMAP * map)
Definition at line 441 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *end;
   DBUG_ASSERT(map->bitmap);
   end= map->last_word_ptr;
   while (to <= end)
     *to++ ^= 0xFFFFFFFF;
 }
References st_bitmap::bitmap, DBUG_ASSERT, and st_bitmap::last_word_ptr.
bitmap_is_clear_all()
my_bool bitmap_is_clear_all (const MY_BITMAP * map)
Definition at line 299 of file my_bitmap.c.
 {
   my_bitmap_map *data_ptr= map->bitmap;
   my_bitmap_map *end;
   if (*map->last_word_ptr & ~map->last_word_mask)
     return FALSE;
   end= map->last_word_ptr;
   for (; data_ptr < end; data_ptr++)
     if (*data_ptr)
       return FALSE;
   return TRUE;
 }
References st_bitmap::bitmap, FALSE, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and TRUE.
bitmap_is_overlapping()
my_bool bitmap_is_overlapping (const MY_BITMAP * map1, const MY_BITMAP * map2)
Definition at line 334 of file my_bitmap.c.
 {
   my_bitmap_map *m1= map1->bitmap, *m2= map2->bitmap, *end;
   DBUG_ASSERT(map1->bitmap && map2->bitmap &&
               map1->n_bits==map2->n_bits);
   end= map1->last_word_ptr;
   *map1->last_word_ptr &= ~map1->last_word_mask;
   *map2->last_word_ptr &= ~map2->last_word_mask;
   while (m1 <= end)
   {
     if ((*m1++) & (*m2++))
       return 1;
   }
   return 0;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
bitmap_is_prefix()
my_bool bitmap_is_prefix (const MY_BITMAP * map, uint prefix_size)
Definition at line 260 of file my_bitmap.c.
 {
   uint prefix_bits= prefix_size & 0x7, res;
   uchar *m= (uchar*)map->bitmap;
   uchar *end_prefix= m+prefix_size/8;
   uchar *end;
   DBUG_ASSERT(m && prefix_size <= map->n_bits);
   end= m+no_bytes_in_map(map);
   while (m < end_prefix)
     if (*m++ != 0xff)
       return 0;
   *map->last_word_ptr&= ~map->last_word_mask; /*Clear bits*/
   res= 0;
   if (prefix_bits && *m++ != (1 << prefix_bits)-1)
     goto ret;
   while (m < end)
     if (*m++ != 0)
       goto ret;
   res= 1;
 ret:
   return res;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, no_bytes_in_map, and ret.
bitmap_is_set()
static uint bitmap_is_set (const MY_BITMAP * map, uint bit) inline static
Definition at line 114 of file my_bitmap.h.
 {
   DBUG_ASSERT(bit < (map)->n_bits);
   return _bitmap_is_set(map,bit);
 }
References _bitmap_is_set, and DBUG_ASSERT.
bitmap_is_set_all()
my_bool bitmap_is_set_all (const MY_BITMAP * map)
Definition at line 287 of file my_bitmap.c.
 {
   my_bitmap_map *data_ptr= map->bitmap;
   my_bitmap_map *end= map->last_word_ptr;
   *map->last_word_ptr |= map->last_word_mask;
   for (; data_ptr <= end; data_ptr++)
     if (*data_ptr != 0xFFFFFFFF)
       return FALSE;
   return TRUE;
 }
References st_bitmap::bitmap, FALSE, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and TRUE.
bitmap_is_subset()
my_bool bitmap_is_subset (const MY_BITMAP * map1, const MY_BITMAP * map2)
Definition at line 314 of file my_bitmap.c.
 {
   my_bitmap_map *m1= map1->bitmap, *m2= map2->bitmap, *end;
   DBUG_ASSERT(map1->bitmap && map2->bitmap &&
               map1->n_bits==map2->n_bits);
   end= map1->last_word_ptr;
   *map1->last_word_ptr &= ~map1->last_word_mask;
   *map2->last_word_ptr &= ~map2->last_word_mask;
   while (m1 <= end)
   {
     if ((*m1++) & ~(*m2++))
       return 0;
   }
   return 1;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
bitmap_lock_clear_bit()
void bitmap_lock_clear_bit (MY_BITMAP * map, uint bitmap_bit)
Definition at line 553 of file my_bitmap.c.
 {
   bitmap_lock(map);
   DBUG_ASSERT(map->bitmap && bitmap_bit < map->n_bits);
   bitmap_clear_bit(map, bitmap_bit);
   bitmap_unlock(map);
 }
References st_bitmap::bitmap, bitmap_clear_bit(), bitmap_lock(), bitmap_unlock(), and DBUG_ASSERT.
bitmap_lock_set_next()
uint bitmap_lock_set_next (MY_BITMAP * map)
Definition at line 543 of file my_bitmap.c.
 {
   uint bit_found;
   bitmap_lock(map);
   bit_found= bitmap_set_next(map);
   bitmap_unlock(map);
   return bit_found;
 }
References bitmap_lock(), bitmap_set_next(), and bitmap_unlock().
bitmap_set_above()
void bitmap_set_above (MY_BITMAP * map, uint from_byte, uint use_bit)
Definition at line 394 of file my_bitmap.c.
 {
   uchar use_byte= use_bit ? 0xff : 0;
   uchar *to= (uchar *)map->bitmap + from_byte;
   uchar *end= (uchar *)map->bitmap + (map->n_bits+7)/8;
   while (to < end)
     *to++= use_byte;
 }
References st_bitmap::bitmap, and st_bitmap::n_bits.
bitmap_set_bit()
static void bitmap_set_bit (MY_BITMAP * map, uint bit) inline static
Definition at line 96 of file my_bitmap.h.
 {
   DBUG_ASSERT(bit < (map)->n_bits);
   _bitmap_set_bit(map,bit);
 }
References _bitmap_set_bit, and DBUG_ASSERT.
Referenced by bitmap_set_next().
bitmap_set_next()
uint bitmap_set_next (MY_BITMAP * map)
Definition at line 232 of file my_bitmap.c.
 {
   uint bit_found;
   DBUG_ASSERT(map->bitmap);
   if ((bit_found= bitmap_get_first(map)) != MY_BIT_NONE)
     bitmap_set_bit(map, bit_found);
   return bit_found;
 }
References st_bitmap::bitmap, bitmap_get_first(), bitmap_set_bit(), DBUG_ASSERT, and MY_BIT_NONE.
Referenced by bitmap_lock_set_next().
bitmap_set_prefix()
void bitmap_set_prefix (MY_BITMAP * map, uint prefix_size)
Definition at line 242 of file my_bitmap.c.
 {
   uint prefix_bytes, prefix_bits, d;
   uchar *m= (uchar *)map->bitmap;
   DBUG_ASSERT(map->bitmap &&
           (prefix_size <= map->n_bits || prefix_size == (uint) ~0));
   set_if_smaller(prefix_size, map->n_bits);
   if ((prefix_bytes= prefix_size / 8))
     memset(m, 0xff, prefix_bytes);
   m+= prefix_bytes;
   if ((prefix_bits= prefix_size & 7))
     *m++= (1 << prefix_bits)-1;
   if ((d= no_bytes_in_map(map)-prefix_bytes))
     bzero(m, d);
 }
References st_bitmap::bitmap, bzero, mpq::d, DBUG_ASSERT, memset, st_bitmap::n_bits, no_bytes_in_map, and set_if_smaller.
bitmap_subtract()
void bitmap_subtract (MY_BITMAP * map, const MY_BITMAP * map2)
Definition at line 405 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *from= map2->bitmap, *end;
   DBUG_ASSERT(map->bitmap && map2->bitmap &&
               map->n_bits==map2->n_bits);
   end= map->last_word_ptr;
   while (to <= end)
     *to++ &= ~(*from++);
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
bitmap_test_and_clear()
my_bool bitmap_test_and_clear (MY_BITMAP * map, uint bitmap_bit)
Definition at line 221 of file my_bitmap.c.
 {
   my_bool res;
   DBUG_ASSERT(map->bitmap && bitmap_bit < map->n_bits);
   bitmap_lock(map);
   res= bitmap_fast_test_and_clear(map, bitmap_bit);
   bitmap_unlock(map);
   return res;
 }
References st_bitmap::bitmap, bitmap_fast_test_and_clear(), bitmap_lock(), bitmap_unlock(), and DBUG_ASSERT.
bitmap_test_and_set()
my_bool bitmap_test_and_set (MY_BITMAP * map, uint bitmap_bit)
Definition at line 188 of file my_bitmap.c.
 {
   my_bool res;
   DBUG_ASSERT(map->bitmap && bitmap_bit < map->n_bits);
   bitmap_lock(map);
   res= bitmap_fast_test_and_set(map, bitmap_bit);
   bitmap_unlock(map);
   return res;
 }
References st_bitmap::bitmap, bitmap_fast_test_and_set(), bitmap_lock(), bitmap_unlock(), and DBUG_ASSERT.
bitmap_union()
void bitmap_union (MY_BITMAP * map, const MY_BITMAP * map2)
Definition at line 418 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *from= map2->bitmap, *end;
   DBUG_ASSERT(map->bitmap && map2->bitmap &&
               map->n_bits==map2->n_bits);
   end= map->last_word_ptr;
   while (to <= end)
     *to++ |= *from++;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
bitmap_xor()
void bitmap_xor (MY_BITMAP * map, const MY_BITMAP * map2)
Definition at line 431 of file my_bitmap.c.
 {
   my_bitmap_map *to= map->bitmap, *from= map2->bitmap, *end= map->last_word_ptr;
   DBUG_ASSERT(map->bitmap && map2->bitmap &&
               map->n_bits==map2->n_bits);
   while (to <= end)
     *to++ ^= *from++;
 }
References st_bitmap::bitmap, DBUG_ASSERT, st_bitmap::last_word_ptr, and st_bitmap::n_bits.
create_last_word_mask()
void create_last_word_mask (MY_BITMAP * map)
Definition at line 40 of file my_bitmap.c.
 {
   /* Get the number of used bits (1..8) in the last byte */
   unsigned int const used= 1U + ((map->n_bits-1U) & 0x7U);
   /*
     Create a mask with the upper 'unused' bits set and the lower 'used'
     bits clear. The bits within each byte is stored in big-endian order.
    */
   unsigned char const mask= (~((1 << used) - 1)) & 255;
   /*
     The first bytes are to be set to zero since they represent real  bits
     in the bitvector. The last bytes are set to 0xFF since they  represent
     bytes not used by the bitvector. Finally the last byte contains  bits
     as set by the mask above.
   */
   unsigned char *ptr= (unsigned char*)&map->last_word_mask;
   map->last_word_ptr= map->bitmap + no_words_in_map(map)-1;
   switch (no_bytes_in_map(map) & 3) {
   case 1:
     map->last_word_mask= ~0U;
     ptr[0]= mask;
     return;
   case 2:
     map->last_word_mask= ~0U;
     ptr[0]= 0;
     ptr[1]= mask;
     return;
   case 3:
     map->last_word_mask= 0U;
     ptr[2]= mask;
     ptr[3]= 0xFFU;
     return;
   case 0:
     map->last_word_mask= 0U;
     ptr[3]= mask;
     return;
   }
 }
References st_bitmap::bitmap, st_bitmap::last_word_mask, st_bitmap::last_word_ptr, st_bitmap::n_bits, no_bytes_in_map, no_words_in_map, and ptr().
Referenced by bitmap_init().