Azerotcore-wotlk: ScriptRegistry< TScript > Class Template Reference
ScriptRegistry< TScript > Class Template Reference
#include <ScriptMgr.h>
Public Types
typedef std::map< uint32, TScript * > ScriptMap
typedef ScriptMap::iterator ScriptMapIterator
typedef std::vector< TScript * > ScriptVector
typedef ScriptVector::iterator ScriptVectorIterator
Static Public Member Functions
static void AddScript (TScript *const script)
static void AddALScripts ()
static TScript * GetScriptById (uint32 id)
Static Public Attributes
static ScriptMap ScriptPointerList
static ScriptVector ALScripts
Static Private Member Functions
static bool _checkMemory (TScript *const script)
Static Private Attributes
static uint32 _scriptIdCounter = 0
Detailed Description
template<class TScript>
class ScriptRegistry< TScript >
Definition at line 2051 of file ScriptMgr.h.
Member Typedef Documentation
ScriptMap
template<class TScript > typedef std::map<uint32, TScript*> ScriptRegistry< TScript >::ScriptMap
Definition at line 2054 of file ScriptMgr.h.
ScriptMapIterator
template<class TScript > typedef ScriptMap::iterator ScriptRegistry< TScript >::ScriptMapIterator
Definition at line 2055 of file ScriptMgr.h.
ScriptVector
template<class TScript > typedef std::vector<TScript*> ScriptRegistry< TScript >::ScriptVector
Definition at line 2057 of file ScriptMgr.h.
ScriptVectorIterator
template<class TScript > typedef ScriptVector::iterator ScriptRegistry< TScript >::ScriptVectorIterator
Definition at line 2058 of file ScriptMgr.h.
Member Function Documentation
_checkMemory()
template<class TScript > static bool ScriptRegistry< TScript >::_checkMemory (TScript *const script) inline static private
Definition at line 2165 of file ScriptMgr.h.
     {
         // See if the script is using the same memory as another script. If this happens, it means that
         // someone forgot to allocate new memory for a script.
         for (ScriptMapIterator it = ScriptPointerList.begin(); it != ScriptPointerList.end(); ++it)
         {
             if (it->second == script)
             {
                 LOG_ERROR("scripts", "Script '%s' has same memory pointer as '%s'.",
                                script->GetName().c_str(), it->second->GetName().c_str());
                 return false;
             }
         }
         return true;
     }
References LOG_ERROR, and ScriptRegistry< TScript >::ScriptPointerList.
Referenced by ScriptRegistry< TScript >::AddALScripts(), and ScriptRegistry< TScript >::AddScript().
AddALScripts()
template<class TScript > static void ScriptRegistry< TScript >::AddALScripts () inline static
Definition at line 2087 of file ScriptMgr.h.
     {
         for(ScriptVectorIterator it = ALScripts.begin(); it != ALScripts.end(); ++it)
         {
             TScript* const script = *it;
             script->checkValidity();
             if (script->IsDatabaseBound())
             {
                 if (!_checkMemory(script))
                 {
                     return;
                 }
                 // Get an ID for the script. An ID only exists if it's a script that is assigned in the database
                 // through a script name (or similar).
                 uint32 id = sObjectMgr->GetScriptId(script->GetName().c_str());
                 if (id)
                 {
                     // Try to find an existing script.
                     TScript const* oldScript = nullptr;
                     for (auto iterator = ScriptPointerList.begin(); iterator != ScriptPointerList.end(); ++iterator)
                     {
                         // If the script names match...
                         if (iterator->second->GetName() == script->GetName())
{
                             // ... It exists.
                             oldScript = iterator->second;
                             break;
                         }
                     }
                     // If the script is already assigned -> delete it!
                     if (oldScript)
                     {
                         delete oldScript;
                     }
                     // Assign new script!
                     ScriptPointerList[id] = script;
                     // Increment script count only with new scripts
                     if (!oldScript)
                     {
                         sScriptMgr->IncrementScriptCount();
                     }
                 }
                 else
                 {
                     // The script uses a script name from database, but isn't assigned to anything.
                     if (script->GetName().find("Smart") == std::string::npos)
                         LOG_ERROR("sql.sql", "Script named '%s' is not assigned in the database.",
                                          script->GetName().c_str());
                 }
             }
             else
             {
                 // We're dealing with a code-only script; just add it.
                 ScriptPointerList[_scriptIdCounter++] = script;
                 sScriptMgr->IncrementScriptCount();
             }
         }
     }
References ScriptRegistry< TScript >::_checkMemory(), ScriptRegistry< TScript >::_scriptIdCounter, ScriptRegistry< TScript >::ALScripts, LOG_ERROR, ScriptRegistry< TScript >::ScriptPointerList, sObjectMgr, and sScriptMgr.
Referenced by ScriptMgr::LoadDatabase().
AddScript()
template<class TScript > static void ScriptRegistry< TScript >::AddScript (TScript *const script) inline static
Definition at line 2066 of file ScriptMgr.h.
     {
         ASSERT(script);
         if (!_checkMemory(script))
             return;
         if (script->isAfterLoadScript())
         {
             ALScripts.push_back(script);
         }
         else
         {
             script->checkValidity();
             // We're dealing with a code-only script; just add it.
             ScriptPointerList[_scriptIdCounter++] = script;
             sScriptMgr->IncrementScriptCount();
         }
     }
References ScriptRegistry< TScript >::_checkMemory(), ScriptRegistry< TScript >::_scriptIdCounter, ScriptRegistry< TScript >::ALScripts, ASSERT, ScriptRegistry< TScript >::ScriptPointerList, and sScriptMgr.
Referenced by AccountScript::AccountScript(), AchievementCriteriaScript::AchievementCriteriaScript(), AchievementScript::AchievementScript(), AllCreatureScript::AllCreatureScript(), AllMapScript::AllMapScript(), AreaTriggerScript::AreaTriggerScript(), ArenaScript::ArenaScript(), ArenaTeamScript::ArenaTeamScript(), AuctionHouseScript::AuctionHouseScript(), BattlegroundMapScript::BattlegroundMapScript(), BattlegroundScript::BattlegroundScript(), BGScript::BGScript(), CommandSC::CommandSC(), CommandScript::CommandScript(), ConditionScript::ConditionScript(), CreatureScript::CreatureScript(), DatabaseScript::DatabaseScript(), DynamicObjectScript::DynamicObjectScript(), FormulaScript::FormulaScript(), GameEventScript::GameEventScript(), GameObjectScript::GameObjectScript(), GlobalScript::GlobalScript(), GroupScript::GroupScript(), GuildScript::GuildScript(), InstanceMapScript::InstanceMapScript(), ItemScript::ItemScript(), MailScript::MailScript(), MiscScript::MiscScript(), ModuleScript::ModuleScript(), MovementHandlerScript::MovementHandlerScript(), OutdoorPvPScript::OutdoorPvPScript(), PetScript::PetScript(), PlayerScript::PlayerScript(), ServerScript::ServerScript(), SpellSC::SpellSC(), SpellScriptLoader::SpellScriptLoader(), TransportScript::TransportScript(), UnitScript::UnitScript(), VehicleScript::VehicleScript(), WeatherScript::WeatherScript(), WorldMapScript::WorldMapScript(), and WorldScript::WorldScript().
GetScriptById()
template<class TScript > static TScript* ScriptRegistry< TScript >::GetScriptById (uint32 id) inline static
Definition at line 2153 of file ScriptMgr.h.
     {
         ScriptMapIterator it = ScriptPointerList.find(id);
         if (it != ScriptPointerList.end())
             return it->second;
         return nullptr;
     }
References ScriptRegistry< TScript >::ScriptPointerList.
Referenced by ScriptMgr::CreateAuraScripts(), ScriptMgr::CreateSpellScriptLoaders(), and ScriptMgr::CreateSpellScripts().
Member Data Documentation
_scriptIdCounter
template<class TScript > uint32 ScriptRegistry< TScript >::_scriptIdCounter = 0 static private
Definition at line 2184 of file ScriptMgr.h.
Referenced by ScriptRegistry< TScript >::AddALScripts(), and ScriptRegistry< TScript >::AddScript().
ALScripts
template<class TScript > std::vector< TScript * > ScriptRegistry< TScript >::ALScripts static
Definition at line 2064 of file ScriptMgr.h.
Referenced by ScriptRegistry< TScript >::AddALScripts(), and ScriptRegistry< TScript >::AddScript().
ScriptPointerList
template<class TScript > std::map< uint32, TScript * > ScriptRegistry< TScript >::ScriptPointerList static
Definition at line 2062 of file ScriptMgr.h.
Referenced by ScriptRegistry< TScript >::_checkMemory(), ScriptRegistry< TScript >::AddALScripts(), ScriptRegistry< TScript >::AddScript(), and ScriptRegistry< TScript >::GetScriptById().
The documentation for this class was generated from the following file:
src/server/game/Scripting/ScriptMgr.h