Azerotcore-wotlk: boss_icehowl::boss_icehowlAI Struct Reference
boss_icehowl::boss_icehowlAI Struct Reference
Public Member Functions
boss_icehowlAI (Creature *pCreature)
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void JustReachedHome () override
bool DoTrampleIfValid ()
void MovementInform (uint32, uint32 id) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
ObjectGuid TargetGUID
float destX
float destY
float destZ
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 773 of file boss_northrend_beasts.cpp.
Constructor & Destructor Documentation
boss_icehowlAI()
boss_icehowl::boss_icehowlAI::boss_icehowlAI (Creature * pCreature) inline
Definition at line 775 of file boss_northrend_beasts.cpp.
                                             : ScriptedAI(pCreature)
         {
             pInstance = pCreature->GetInstanceScript();
             me->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
             me->SetReactState(REACT_PASSIVE);
             if (IsHeroic())
                 me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_DISPEL, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DECREASE_SPEED, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_SPEED_NOT_STACK, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_SPEED_ALWAYS, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_SPEED_SLOW_ALL, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, true); // judgement of justice
             //me->SetLootMode(0); // [LOOT]
         }
References Unit::AddUnitMovementFlag(), Unit::ApplySpellImmune(), WorldObject::GetInstanceScript(), IMMUNITY_EFFECT, IMMUNITY_STATE, ScriptedAI::IsHeroic(), ScriptedAI::me, MOVEMENTFLAG_WALKING, pInstance, REACT_PASSIVE, Creature::SetReactState(), SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_SPEED_ALWAYS, SPELL_AURA_MOD_SPEED_NOT_STACK, SPELL_AURA_MOD_SPEED_SLOW_ALL, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, and SPELL_EFFECT_DISPEL.
Member Function Documentation
AttackStart()
void boss_icehowl::boss_icehowlAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 795 of file boss_northrend_beasts.cpp.
         {
             if (me->GetReactState() != REACT_PASSIVE)
                 ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), Creature::GetReactState(), ScriptedAI::me, and REACT_PASSIVE.
DoTrampleIfValid()
bool boss_icehowl::boss_icehowlAI::DoTrampleIfValid () inline
Definition at line 816 of file boss_northrend_beasts.cpp.
         {
             Map::PlayerList const& lPlayers = me->GetMap()->GetPlayers();
             for( Map::PlayerList::const_iterator itr = lPlayers.begin(); itr != lPlayers.end(); ++itr )
                 if( Unit* p = itr->GetSource() )
                     if( p->IsAlive() && p->GetExactDist(me) <= 12.0f )
                     {
                         DoCastAOE(SPELL_TRAMPLE);
                         return true;
                     }
             return false;
         }
References MapRefMgr::begin(), UnitAI::DoCastAOE(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), ScriptedAI::me, and SPELL_TRAMPLE.
Referenced by MovementInform(), and UpdateAI().
EnterCombat()
void boss_icehowl::boss_icehowlAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 801 of file boss_northrend_beasts.cpp.
         {
             me->setActive(true);
             events.Reset();
             events.ScheduleEvent(EVENT_SPELL_FEROCIOUS_BUTT, urand(15000, 30000));
             events.RescheduleEvent(EVENT_SPELL_WHIRL, urand(10000, 12000));
             events.RescheduleEvent(EVENT_SPELL_ARCTIC_BREATH, 14000);
             events.RescheduleEvent(EVENT_JUMP_MIDDLE, 30000);
         }
References EVENT_JUMP_MIDDLE, EVENT_SPELL_ARCTIC_BREATH, EVENT_SPELL_FEROCIOUS_BUTT, EVENT_SPELL_WHIRL, ScriptedAI::me, WorldObject::setActive(), and urand().
EnterEvadeMode()
void boss_icehowl::boss_icehowlAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1003 of file boss_northrend_beasts.cpp.
         {
             events.Reset();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             if( pInstance )
                 pInstance->SetData(TYPE_FAILED, 1);
         }
References ScriptedAI::me, pInstance, ZoneScript::SetData(), Object::SetFlag(), TYPE_FAILED, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_icehowl::boss_icehowlAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1011 of file boss_northrend_beasts.cpp.
         {
             if( !pInstance )
                 return;
             pInstance->SetData(TYPE_ICEHOWL, DONE);
         }
References DONE, pInstance, ZoneScript::SetData(), and TYPE_ICEHOWL.
JustReachedHome()
void boss_icehowl::boss_icehowlAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 811 of file boss_northrend_beasts.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
MovementInform()
void boss_icehowl::boss_icehowlAI::MovementInform (uint32 , uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 830 of file boss_northrend_beasts.cpp.
         {
             if( id == EVENT_CHARGE )
             {
                 events.Reset();
                 events.RescheduleEvent(EVENT_SPELL_FEROCIOUS_BUTT, urand(5000, 15000));
                 events.RescheduleEvent(EVENT_SPELL_WHIRL, urand(2000, 5000));
                 events.RescheduleEvent(EVENT_SPELL_ARCTIC_BREATH, urand(5000, 8000));
                 events.RescheduleEvent(EVENT_JUMP_MIDDLE, urand(30000, 50000));
                 float angle = me->GetAngle(&Locs[LOC_CENTER]);
                 angle = angle >= M_PI ? angle - M_PI : angle + M_PI;
                 me->UpdatePosition(destX, destY, destZ, angle, true);
                 me->StopMovingOnCurrentPos();
                 if( !DoTrampleIfValid() )
                 {
                     me->CastSpell(me, SPELL_STAGGERED_DAZE, true);
                     me->CastSpell((Unit*)nullptr, SPELL_TRAMPLE, true);
                     Talk(EMOTE_TRAMPLE_CRASH);
                     events.DelayEvents(15000);
                 }
                 else
                 {
                     Talk(EMOTE_TRAMPLE_FAIL);
                     me->CastSpell(me, SPELL_FROTHING_RAGE, true);
                 }
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References Unit::CastSpell(), destX, destY, destZ, DoTrampleIfValid(), EMOTE_TRAMPLE_CRASH, EMOTE_TRAMPLE_FAIL, EVENT_CHARGE, EVENT_JUMP_MIDDLE, EVENT_SPELL_ARCTIC_BREATH, EVENT_SPELL_FEROCIOUS_BUTT, EVENT_SPELL_WHIRL, Position::GetAngle(), LOC_CENTER, Locs, M_PI, ScriptedAI::me, REACT_AGGRESSIVE, Creature::SetReactState(), SPELL_FROTHING_RAGE, SPELL_STAGGERED_DAZE, SPELL_TRAMPLE, Unit::StopMovingOnCurrentPos(), CreatureAI::Talk(), Unit::UpdatePosition(), and urand().
UpdateAI()
void boss_icehowl::boss_icehowlAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 863 of file boss_northrend_beasts.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_FEROCIOUS_BUTT:
                     if( Unit* victim = me->GetVictim() )
                         me->CastSpell(victim, SPELL_FEROCIOUS_BUTT, false);
                     events.RepeatEvent(urand(15000, 30000));
                     break;
                 case EVENT_SPELL_WHIRL:
                     me->CastSpell((Unit*)nullptr, SPELL_WHIRL, false);
                     events.RepeatEvent(urand(15000, 20000));
                     break;
                 case EVENT_SPELL_ARCTIC_BREATH:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 90.0f, true) )
                         me->CastSpell(target, SPELL_ARCTIC_BREATH, false);
                     events.RepeatEvent(urand(20000, 30000));
                     break;
                 case EVENT_JUMP_MIDDLE:
                     me->StopMoving();
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MoveIdle();
                     me->SetReactState(REACT_PASSIVE);
                     me->AttackStop();
                     me->GetMotionMaster()->MoveJump(Locs[LOC_CENTER].GetPositionX(), Locs[LOC_CENTER].GetPositionY(), Locs[LOC_CENTER].GetPositionZ(), 40.0f, 12.0f);
                     me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                     events.Reset();
                     events.RescheduleEvent(EVENT_SPELL_MASSIVE_CRASH, 2000);
                     break;
                 case EVENT_SPELL_MASSIVE_CRASH:
                     me->GetMotionMaster()->Clear();
                     me->CastSpell((Unit*)nullptr, SPELL_MASSIVE_CRASH, false);
                     events.RescheduleEvent(EVENT_GAZE, 2000);
                     break;
                 case EVENT_GAZE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 500.0f, true) )
                     {
                         TargetGUID = target->GetGUID();
                         me->SetGuidValue(UNIT_FIELD_TARGET, TargetGUID);
                         me->SetFacingToObject(target);
                         Talk(EMOTE_TRAMPLE_STARE, target);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                         events.RescheduleEvent(EVENT_JUMP_BACK, 2000);
                     }
                     else // in case something went wrong
                     {
                         events.RescheduleEvent(EVENT_SPELL_FEROCIOUS_BUTT, urand(5000, 15000));
                         events.RescheduleEvent(EVENT_SPELL_WHIRL, urand(2000, 5000));
                         events.RescheduleEvent(EVENT_SPELL_ARCTIC_BREATH, urand(5000, 8000));
                         events.RescheduleEvent(EVENT_JUMP_MIDDLE, urand(30000, 50000));
                         me->GetMotionMaster()->MovementExpired();
                         me->SetReactState(REACT_AGGRESSIVE);
                     }
                     break;
                 case EVENT_JUMP_BACK:
                     {
                         float angle;
                         if( Unit* target = ObjectAccessor::GetPlayer(*me, TargetGUID) )
                             angle = me->GetAngle(target);
                         else // in case something went wrong
                             angle = rand_norm() * 2 * M_PI;
                         float jumpangle = angle >= M_PI ? angle - M_PI : angle + M_PI;
                         float dist = 50.0f;
                         if( angle > 1.0f && angle < 2.0f ) // near main gate
                             dist = 46.0f;
                         destX = Locs[LOC_CENTER].GetPositionX() + cos(angle) * dist;
                         destY = Locs[LOC_CENTER].GetPositionY() + sin(angle) * dist;
                         destZ = Locs[LOC_CENTER].GetPositionZ() + 1.0f;
                         me->StopMoving();
                         me->GetMotionMaster()->MoveJump(Locs[LOC_CENTER].GetPositionX() + cos(jumpangle) * 35.0f, Locs[LOC_CENTER].GetPositionY() + sin(jumpangle) * 35.0f, Locs[LOC_CENTER].GetPositionZ() + 1.0f, 40.0f, 12.0f);
                         events.RescheduleEvent(EVENT_TRAMPLE, 1500);
                         if( pInstance )
                             switch( GetDifficulty() )
{
                                 case RAID_DIFFICULTY_10MAN_NORMAL:
                                     pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_MASSIVE_CRASH);
                                     pInstance->DoCastSpellOnPlayers(SPELL_SURGE_OF_ADRENALINE);
                                     break;
                                 case RAID_DIFFICULTY_25MAN_NORMAL:
                                     pInstance->DoRemoveAurasDueToSpellOnPlayers(67660);
                                     pInstance->DoCastSpellOnPlayers(SPELL_SURGE_OF_ADRENALINE);
                                     break;
                                 case RAID_DIFFICULTY_10MAN_HEROIC:
                                     pInstance->DoRemoveAurasDueToSpellOnPlayers(67661);
                                     break;
                                 case RAID_DIFFICULTY_25MAN_HEROIC:
                                     pInstance->DoRemoveAurasDueToSpellOnPlayers(67662);
                                     break;
                             }
                     }
                     break;
                 case EVENT_TRAMPLE:
                     //Talk(EMOTE_TRAMPLE_START);
                     me->DisableSpline();
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MoveCharge(destX, destY, destZ + 1.0f, 65.0f);
                     me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                     events.RescheduleEvent(EVENT_CHECK_TRAMPLE_PLAYERS, 100);
                     break;
                 case EVENT_CHECK_TRAMPLE_PLAYERS:
                     if( DoTrampleIfValid() )
                     {
                         events.Reset();
                         events.RescheduleEvent(EVENT_SPELL_FEROCIOUS_BUTT, urand(5000, 15000));
                         events.RescheduleEvent(EVENT_SPELL_WHIRL, urand(2000, 5000));
                         events.RescheduleEvent(EVENT_SPELL_ARCTIC_BREATH, urand(5000, 8000));
                         events.RescheduleEvent(EVENT_JUMP_MIDDLE, urand(30000, 50000));
                         Talk(EMOTE_TRAMPLE_FAIL);
                         me->CastSpell(me, SPELL_FROTHING_RAGE, true);
                         me->GetMotionMaster()->MovementExpired();
                         me->SetReactState(REACT_AGGRESSIVE);
                     }
                     // no PopEvent() intended!
                     break;
                 case EVENT_REFRESH_POSITION:
                     //me->SetFacingTo(me->GetOrientation());
                     break;
             }
             if( me->GetReactState() != REACT_PASSIVE )
                 DoMeleeAttackIfReady();
         }
References Unit::AttackStop(), Unit::CastSpell(), MotionMaster::Clear(), destX, destY, destZ, diff(), Unit::DisableSpline(), InstanceScript::DoCastSpellOnPlayers(), UnitAI::DoMeleeAttackIfReady(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), DoTrampleIfValid(), EMOTE_ONESHOT_ROAR, EMOTE_TRAMPLE_FAIL, EMOTE_TRAMPLE_STARE, ObjectGuid::Empty, EVENT_CHECK_TRAMPLE_PLAYERS, EVENT_GAZE, EVENT_JUMP_BACK, EVENT_JUMP_MIDDLE, EVENT_REFRESH_POSITION, EVENT_SPELL_ARCTIC_BREATH, EVENT_SPELL_FEROCIOUS_BUTT, EVENT_SPELL_MASSIVE_CRASH, EVENT_SPELL_WHIRL, EVENT_TRAMPLE, Position::GetAngle(), ScriptedAI::GetDifficulty(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetReactState(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), LOC_CENTER, Locs, M_PI, ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MoveIdle(), MotionMaster::MoveJump(), MotionMaster::MovementExpired(), pInstance, RAID_DIFFICULTY_10MAN_HEROIC, RAID_DIFFICULTY_10MAN_NORMAL, RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, rand_norm(), REACT_AGGRESSIVE, REACT_PASSIVE, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetFacingToObject(), Object::SetGuidValue(), Creature::SetReactState(), SPELL_ARCTIC_BREATH, SPELL_FEROCIOUS_BUTT, SPELL_FROTHING_RAGE, SPELL_MASSIVE_CRASH, SPELL_SURGE_OF_ADRENALINE, SPELL_WHIRL, Unit::StopMoving(), CreatureAI::Talk(), TargetGUID, UNIT_FIELD_TARGET, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
destX
float boss_icehowl::boss_icehowlAI::destX
Definition at line 793 of file boss_northrend_beasts.cpp.
Referenced by MovementInform(), and UpdateAI().
destY
float boss_icehowl::boss_icehowlAI::destY
Definition at line 793 of file boss_northrend_beasts.cpp.
Referenced by MovementInform(), and UpdateAI().
destZ
float boss_icehowl::boss_icehowlAI::destZ
Definition at line 793 of file boss_northrend_beasts.cpp.
Referenced by MovementInform(), and UpdateAI().
events
EventMap boss_icehowl::boss_icehowlAI::events
Definition at line 791 of file boss_northrend_beasts.cpp.
pInstance
InstanceScript* boss_icehowl::boss_icehowlAI::pInstance
Definition at line 790 of file boss_northrend_beasts.cpp.
Referenced by boss_icehowlAI(), EnterEvadeMode(), JustDied(), and UpdateAI().
TargetGUID
ObjectGuid boss_icehowl::boss_icehowlAI::TargetGUID
Definition at line 792 of file boss_northrend_beasts.cpp.
Referenced by UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp