Azerotcore-wotlk: AchievementMgr Class Reference
AchievementMgr Class Reference
#include <AchievementMgr.h>
Public Member Functions
AchievementMgr (Player *player)
~AchievementMgr ()
void Reset ()
void LoadFromDB (PreparedQueryResult achievementResult, PreparedQueryResult criteriaResult)
void SaveToDB (CharacterDatabaseTransaction trans)
void ResetAchievementCriteria (AchievementCriteriaCondition condition, uint32 value, bool evenIfCriteriaComplete=false)
void UpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void CompletedAchievement (AchievementEntry const *entry)
void CheckAllAchievementCriteria ()
void SendAllAchievementData () const
void SendRespondInspectAchievements (Player *player) const
bool HasAchieved (uint32 achievementId) const
Player * GetPlayer () const
void UpdateTimedAchievements (uint32 timeDiff)
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry, uint32 timeLost=0)
void RemoveTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void RemoveCriteriaProgress (AchievementCriteriaEntry const *entry)
Static Public Member Functions
static void DeleteFromDB (ObjectGuid::LowType lowguid)
Private Types
enum ProgressType { PROGRESS_SET , PROGRESS_ACCUMULATE , PROGRESS_HIGHEST , PROGRESS_RESET }
typedef std::map< uint32, uint32 > TimedAchievementMap
Private Member Functions
void SendAchievementEarned (AchievementEntry const *achievement) const
void SendCriteriaUpdate (AchievementCriteriaEntry const *entry, CriteriaProgress const *progress, uint32 timeElapsed, bool timedCompleted) const
CriteriaProgress * GetCriteriaProgress (AchievementCriteriaEntry const *entry)
void SetCriteriaProgress (AchievementCriteriaEntry const *entry, uint32 changeValue, ProgressType ptype=PROGRESS_SET)
void CompletedCriteriaFor (AchievementEntry const *achievement)
bool IsCompletedCriteria (AchievementCriteriaEntry const *achievementCriteria, AchievementEntry const *achievement)
bool IsCompletedAchievement (AchievementEntry const *entry)
bool CanUpdateCriteria (AchievementCriteriaEntry const *criteria, AchievementEntry const *achievement)
void BuildAllDataPacket (WorldPacket *data) const
Private Attributes
Player * m_player
CriteriaProgressMap m_criteriaProgress
CompletedAchievementMap m_completedAchievements
TimedAchievementMap m_timedAchievements
Detailed Description
Definition at line 274 of file AchievementMgr.h.
Member Typedef Documentation
TimedAchievementMap
typedef std::map<uint32, uint32> AchievementMgr::TimedAchievementMap private
Definition at line 312 of file AchievementMgr.h.
Member Enumeration Documentation
ProgressType
enum AchievementMgr::ProgressType private
Enumerator
PROGRESS_SET
PROGRESS_ACCUMULATE
PROGRESS_HIGHEST
PROGRESS_RESET
Definition at line 298 of file AchievementMgr.h.
 { PROGRESS_SET, PROGRESS_ACCUMULATE, PROGRESS_HIGHEST, PROGRESS_RESET };
Constructor & Destructor Documentation
AchievementMgr()
AchievementMgr::AchievementMgr (Player * player)
Definition at line 471 of file AchievementMgr.cpp.
 {
     m_player = player;
 }
References m_player.
~AchievementMgr()
AchievementMgr::~AchievementMgr ()
Definition at line 476 of file AchievementMgr.cpp.
 {
 }
Member Function Documentation
BuildAllDataPacket()
void AchievementMgr::BuildAllDataPacket (WorldPacket * data) const private
used by SMSG_RESPOND_INSPECT_ACHIEVEMENT and SMSG_ALL_ACHIEVEMENT_DATA
Definition at line 2311 of file AchievementMgr.cpp.
 {
     for (CompletedAchievementMap::const_iterator iter = m_completedAchievements.begin(); iter != m_completedAchievements.end(); ++iter)
     {
         // Skip hidden achievements
         AchievementEntry const* achievement = sAchievementStore.LookupEntry(iter->first);
         if (!achievement || achievement->flags & ACHIEVEMENT_FLAG_HIDDEN)
             continue;
         *data << uint32(iter->first);
         data->AppendPackedTime(iter->second.date);
     }
     *data << int32(-1);
     for (CriteriaProgressMap::const_iterator iter = m_criteriaProgress.begin(); iter != m_criteriaProgress.end(); ++iter)
     {
         *data << uint32(iter->first);
         data->appendPackGUID(iter->second.counter);
         *data << GetPlayer()->GetPackGUID();
         *data << uint32(0);
         data->AppendPackedTime(iter->second.date);
         *data << uint32(0);
         *data << uint32(0);
     }
     *data << int32(-1);
 }
References ACHIEVEMENT_FLAG_HIDDEN, ByteBuffer::AppendPackedTime(), ByteBuffer::appendPackGUID(), AchievementEntry::flags, Object::GetPackGUID(), GetPlayer(), m_completedAchievements, m_criteriaProgress, and sAchievementStore.
Referenced by SendAllAchievementData(), and SendRespondInspectAchievements().
CanUpdateCriteria()
bool AchievementMgr::CanUpdateCriteria (AchievementCriteriaEntry const * criteria, AchievementEntry const * achievement) private
Definition at line 2345 of file AchievementMgr.cpp.
 {
     if (DisableMgr::IsDisabledFor(DISABLE_TYPE_ACHIEVEMENT_CRITERIA, criteria->ID, nullptr))
         return false;
     if (achievement->mapID != -1 && GetPlayer()->GetMapId() != uint32(achievement->mapID))
         return false;
     if ((achievement->requiredFaction == ACHIEVEMENT_FACTION_HORDE    && GetPlayer()->GetTeamId(true) != TEAM_HORDE) ||
             (achievement->requiredFaction == ACHIEVEMENT_FACTION_ALLIANCE && GetPlayer()->GetTeamId(true) != TEAM_ALLIANCE))
         return false;
     for (uint32 i = 0; i < MAX_CRITERIA_REQUIREMENTS; ++i)
     {
         if (!criteria->additionalRequirements[i].additionalRequirement_type)
             continue;
         switch (criteria->additionalRequirements[i].additionalRequirement_type)
         {
             case ACHIEVEMENT_CRITERIA_CONDITION_BG_MAP:
                 if (GetPlayer()->GetMapId() != criteria->additionalRequirements[i].additionalRequirement_value)
                     return false;
                 break;
             case ACHIEVEMENT_CRITERIA_CONDITION_NOT_IN_GROUP:
                 if (GetPlayer()->GetGroup())
                     return false;
                 break;
             default:
                 break;
         }
     }
     // don't update already completed criteria
     if (IsCompletedCriteria(criteria, achievement))
         return false;
     return true;
 }
References ACHIEVEMENT_CRITERIA_CONDITION_BG_MAP, ACHIEVEMENT_CRITERIA_CONDITION_NOT_IN_GROUP, ACHIEVEMENT_FACTION_ALLIANCE, ACHIEVEMENT_FACTION_HORDE, AchievementCriteriaEntry::additionalRequirement_type, AchievementCriteriaEntry::additionalRequirement_value, AchievementCriteriaEntry::additionalRequirements, DISABLE_TYPE_ACHIEVEMENT_CRITERIA, GetPlayer(), AchievementCriteriaEntry::ID, IsCompletedCriteria(), DisableMgr::IsDisabledFor(), AchievementEntry::mapID, MAX_CRITERIA_REQUIREMENTS, AchievementEntry::requiredFaction, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by UpdateAchievementCriteria().
CheckAllAchievementCriteria()
void AchievementMgr::CheckAllAchievementCriteria ()
called at player login. The player might have fulfilled some achievements when the achievement system wasn't working yet.
Definition at line 758 of file AchievementMgr.cpp.
 {
     // suppress sending packets
     for (uint32 i = 0; i < ACHIEVEMENT_CRITERIA_TYPE_TOTAL; ++i)
         UpdateAchievementCriteria(AchievementCriteriaTypes(i));
 }
References ACHIEVEMENT_CRITERIA_TYPE_TOTAL, and UpdateAchievementCriteria().
Referenced by Player::CheckAllAchievementCriteria(), and Reset().
CompletedAchievement()
void AchievementMgr::CompletedAchievement (AchievementEntry const * entry)
Currently there's only one achievement that deals with gender-specific titles. Since no common attributes were found, (not even in titleRewardFlags field) we explicitly check by ID. Maybe in the future we could move the achievement_reward condition fields to the condition system.
Definition at line 2181 of file AchievementMgr.cpp.
 {
     // disable for gamemasters with GM-mode enabled
     if (m_player->IsGameMaster())
     {
         LOG_INFO("achievement", "Not available in GM mode.");
         ChatHandler(m_player->GetSession()).PSendSysMessage("Not available in GM mode");
         return;
     }
     if (!sScriptMgr->OnBeforeAchievementComplete(GetPlayer(), achievement))
     {
         return;
     }
     if (achievement->flags & ACHIEVEMENT_FLAG_COUNTER || HasAchieved(achievement->ID))
         return;
     LOG_DEBUG("achievement", "AchievementMgr::CompletedAchievement(%u)", achievement->ID);
     SendAchievementEarned(achievement);
     CompletedAchievementData& ca = m_completedAchievements[achievement->ID];
     ca.date = time(nullptr);
     ca.changed = true;
     sScriptMgr->OnAchievementComplete(GetPlayer(), achievement);
     // pussywizard: set all progress counters to 0, so progress will be deleted from db during save
     {
         bool allRefsCompleted = true;
         uint32 achiCheckId = achievement->refAchievement ? achievement->refAchievement : achievement->ID;
         if (AchievementEntryList const* achRefList = sAchievementMgr->GetAchievementByReferencedId(achiCheckId))
             for (AchievementEntryList::const_iterator itr = achRefList->begin(); itr != achRefList->end(); ++itr)
                 if (!IsCompletedAchievement(*itr))
                 {
                     allRefsCompleted = false;
                     break;
                 }
         if (allRefsCompleted)
             if (AchievementCriteriaEntryList const* cList = sAchievementMgr->GetAchievementCriteriaByAchievement(achiCheckId))
                 for (AchievementCriteriaEntryList::const_iterator itr = cList->begin(); itr != cList->end(); ++itr)
                     if (CriteriaProgress* progress = GetCriteriaProgress(*itr))
                     {
                         progress->changed = true;
                         progress->counter = 0;
                     }
     }
     if (achievement->flags & (ACHIEVEMENT_FLAG_REALM_FIRST_REACH | ACHIEVEMENT_FLAG_REALM_FIRST_KILL) && AccountMgr::IsPlayerAccount(m_player->GetSession()->GetSecurity()))
         sAchievementMgr->SetRealmCompleted(achievement);
     UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, achievement->ID);
     UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS, achievement->points);
     // reward items and titles if any
     AchievementReward const* reward = sAchievementMgr->GetAchievementReward(achievement);
     // no rewards
     if (!reward)
         return;
     // titles
     if (uint32 titleId = reward->titleId[achievement->ID == 1793 ? GetPlayer()->getGender() : uint8(GetPlayer()->GetTeamId())])
         if (CharTitlesEntry const* titleEntry = sCharTitlesStore.LookupEntry(titleId))
             GetPlayer()->SetTitle(titleEntry);
     // mail
     if (reward->sender)
     {
         MailDraft draft(reward->mailTemplate);
         if (!reward->mailTemplate)
         {
             std::string subject = reward->subject;
             std::string text = reward->text;
             LocaleConstant localeConstant = GetPlayer()->GetSession()->GetSessionDbLocaleIndex();
             if (localeConstant != LOCALE_enUS)
             {
                 if(AchievementRewardLocale const* loc = sAchievementMgr->GetAchievementRewardLocale(achievement))
                 {
                     ObjectMgr::GetLocaleString(loc->Subject, localeConstant, subject);
                     ObjectMgr::GetLocaleString(loc->Text, localeConstant, text);
                 }
             }
             draft = MailDraft(subject, text);
         }
         CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
         Item* item = reward->itemId ? Item::CreateItem(reward->itemId, 1, GetPlayer()) : nullptr;
         if (item)
         {
             // save new item before send
             item->SaveToDB(trans);                               // save for prevent lost at next mail load, if send fail then item will deleted
             // item
             draft.AddItem(item);
         }
         draft.SendMailTo(trans, GetPlayer(), MailSender(MAIL_CREATURE, reward->sender));
         CharacterDatabase.CommitTransaction(trans);
     }
 }
References ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS, ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, MailDraft::AddItem(), CompletedAchievementData::changed, CharacterDatabase, Item::CreateItem(), CompletedAchievementData::date, AchievementEntry::flags, GetCriteriaProgress(), ObjectMgr::GetLocaleString(), GetPlayer(), WorldSession::GetSecurity(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), HasAchieved(), AchievementEntry::ID, IsCompletedAchievement(), Player::IsGameMaster(), AccountMgr::IsPlayerAccount(), AchievementReward::itemId, LOCALE_enUS, LOG_DEBUG, LOG_INFO, m_completedAchievements, m_player, MAIL_CREATURE, AchievementReward::mailTemplate, AchievementEntry::points, ChatHandler::PSendSysMessage(), AchievementEntry::refAchievement, sAchievementMgr, Item::SaveToDB(), sCharTitlesStore, SendAchievementEarned(), AchievementReward::sender, MailDraft::SendMailTo(), Player::SetTitle(), sScriptMgr, AchievementReward::subject, AchievementReward::text, AchievementReward::titleId, and UpdateAchievementCriteria().
Referenced by Player::CompletedAchievement(), CompletedCriteriaFor(), and UpdateAchievementCriteria().
CompletedCriteriaFor()
void AchievementMgr::CompletedCriteriaFor (AchievementEntry const * achievement) private
Definition at line 1940 of file AchievementMgr.cpp.
 {
     // counter can never complete
     if (achievement->flags & ACHIEVEMENT_FLAG_COUNTER)
         return;
     // already completed and stored
     if (HasAchieved(achievement->ID))
         return;
     if (IsCompletedAchievement(achievement))
         CompletedAchievement(achievement);
 }
References ACHIEVEMENT_FLAG_COUNTER, CompletedAchievement(), AchievementEntry::flags, HasAchieved(), AchievementEntry::ID, and IsCompletedAchievement().
Referenced by UpdateAchievementCriteria().
DeleteFromDB()
void AchievementMgr::DeleteFromDB (ObjectGuid::LowType lowguid) static
Definition at line 531 of file AchievementMgr.cpp.
 {
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_ACHIEVEMENT);
     stmt->setUInt32(0, lowguid);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS);
     stmt->setUInt32(0, lowguid);
     trans->Append(stmt);
     CharacterDatabase.CommitTransaction(trans);
 }
References CHAR_DEL_CHAR_ACHIEVEMENT, CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS, CharacterDatabase, and PreparedStatementBase::setUInt32().
Referenced by reset_commandscript::HandleResetAchievementsCommand(), and Reset().
GetCriteriaProgress()
CriteriaProgress * AchievementMgr::GetCriteriaProgress (AchievementCriteriaEntry const * entry) private
Definition at line 2016 of file AchievementMgr.cpp.
 {
     CriteriaProgressMap::iterator iter = m_criteriaProgress.find(entry->ID);
     if (iter == m_criteriaProgress.end())
         return nullptr;
     return &(iter->second);
 }
References AchievementCriteriaEntry::ID, and m_criteriaProgress.
Referenced by CompletedAchievement(), IsCompletedAchievement(), IsCompletedCriteria(), SetCriteriaProgress(), and UpdateAchievementCriteria().
GetPlayer()
Player* AchievementMgr::GetPlayer () const inline
Definition at line 291 of file AchievementMgr.h.
 { return m_player; }
References m_player.
Referenced by BuildAllDataPacket(), CanUpdateCriteria(), CompletedAchievement(), LoadFromDB(), SaveToDB(), SendAchievementEarned(), SendAllAchievementData(), SendCriteriaUpdate(), SendRespondInspectAchievements(), SetCriteriaProgress(), and UpdateAchievementCriteria().
HasAchieved()
bool AchievementMgr::HasAchieved (uint32 achievementId) const
Definition at line 2340 of file AchievementMgr.cpp.
 {
     return m_completedAchievements.find(achievementId) != m_completedAchievements.end();
 }
References m_completedAchievements.
Referenced by CompletedAchievement(), CompletedCriteriaFor(), Player::HasAchieved(), IsCompletedCriteria(), ResetAchievementCriteria(), and UpdateAchievementCriteria().
IsCompletedAchievement()
bool AchievementMgr::IsCompletedAchievement (AchievementEntry const * entry) private
Definition at line 1954 of file AchievementMgr.cpp.
 {
     // counter can never complete
     if (entry->flags & ACHIEVEMENT_FLAG_COUNTER)
         return false;
     // for achievement with referenced achievement criterias get from referenced and counter from self
     uint32 achievmentForTestId = entry->refAchievement ? entry->refAchievement : entry->ID;
     uint32 achievmentForTestCount = entry->count;
     AchievementCriteriaEntryList const* cList = sAchievementMgr->GetAchievementCriteriaByAchievement(achievmentForTestId);
     if (!cList)
         return false;
     uint32 count = 0;
     // For SUMM achievements, we have to count the progress of each criteria of the achievement.
     // Oddly, the target count is NOT countained in the achievement, but in each individual criteria
     if (entry->flags & ACHIEVEMENT_FLAG_SUMM)
     {
         for (AchievementCriteriaEntryList::const_iterator itr = cList->begin(); itr != cList->end(); ++itr)
         {
             AchievementCriteriaEntry const* criteria = *itr;
             CriteriaProgress const* progress = GetCriteriaProgress(criteria);
             if (!progress)
                 continue;
             count += progress->counter;
             // for counters, field4 contains the main count requirement
             if (count >= criteria->raw.count)
                 return true;
         }
         return false;
     }
     // Default case - need complete all or
     bool completed_all = true;
     for (AchievementCriteriaEntryList::const_iterator itr = cList->begin(); itr != cList->end(); ++itr)
     {
         AchievementCriteriaEntry const* criteria = *itr;
         bool completed = IsCompletedCriteria(criteria, entry);
         // found an uncompleted criteria, but DONT return false yet - there might be a completed criteria with ACHIEVEMENT_CRITERIA_COMPLETE_FLAG_ALL
         if (completed)
             ++count;
         else
             completed_all = false;
         // completed as have req. count of completed criterias
         if (achievmentForTestCount > 0 && achievmentForTestCount <= count)
             return true;
     }
     // all criterias completed requirement
     if (completed_all && achievmentForTestCount == 0)
         return true;
     return false;
 }
References ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_SUMM, AchievementEntry::count, CriteriaProgress::counter, AchievementEntry::flags, GetCriteriaProgress(), AchievementEntry::ID, IsCompletedCriteria(), AchievementCriteriaEntry::raw, AchievementEntry::refAchievement, and sAchievementMgr.
Referenced by CompletedAchievement(), CompletedCriteriaFor(), IsCompletedCriteria(), and UpdateAchievementCriteria().
IsCompletedCriteria()
bool AchievementMgr::IsCompletedCriteria (AchievementCriteriaEntry const * achievementCriteria, AchievementEntry const * achievement) private
Definition at line 1754 of file AchievementMgr.cpp.
 {
     // counter can never complete
     if (achievement->flags & ACHIEVEMENT_FLAG_COUNTER)
         return false;
     if (achievement->flags & (ACHIEVEMENT_FLAG_REALM_FIRST_REACH | ACHIEVEMENT_FLAG_REALM_FIRST_KILL))
     {
         // someone on this realm has already completed that achievement
         if (sAchievementMgr->IsRealmCompleted(achievement))
             return false;
     }
     // pussywizard: progress will be deleted after getting the achievement (optimization)
     // finished achievement should indicate criteria completed, since not finding progress would start some timed achievements and probably other things
     if (HasAchieved(achievement->ID))
     {
         bool completed = true;
         // completed only after all referenced achievements are also completed
         if (AchievementEntryList const* achRefList = sAchievementMgr->GetAchievementByReferencedId(achievement->ID))
             for (AchievementEntryList::const_iterator itr = achRefList->begin(); itr != achRefList->end(); ++itr)
                 if (!IsCompletedAchievement(*itr))
                 {
                     completed = false;
                     break;
                 }
         if (completed)
             return true;
     }
     CriteriaProgress const* progress = GetCriteriaProgress(achievementCriteria);
     if (!progress)
         return false;
     if (!sScriptMgr->IsCompletedCriteria(this, achievementCriteria, achievement, progress))
         return false;
     switch (achievementCriteria->requiredType)
     {
         case ACHIEVEMENT_CRITERIA_TYPE_WIN_BG:
             return progress->counter >= achievementCriteria->win_bg.winCount;
         case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE:
             return progress->counter >= achievementCriteria->kill_creature.creatureCount;
         case ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL:
             return progress->counter >= achievementCriteria->reach_level.level;
         case ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL:
             return progress->counter >= achievementCriteria->reach_skill_level.skillLevel;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT:
             return progress->counter >= 1;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT:
             return progress->counter >= achievementCriteria->complete_quest_count.totalQuestCount;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY:
             return progress->counter >= achievementCriteria->complete_daily_quest_daily.numberOfDays;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE:
             return progress->counter >= achievementCriteria->complete_quests_in_zone.questCount;
         case ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE:
         case ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE:
             return progress->counter >= achievementCriteria->healing_done.count;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST:
             return progress->counter >= achievementCriteria->complete_daily_quest.questCount;
         case ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING:
             return progress->counter >= achievementCriteria->fall_without_dying.fallHeight;
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST:
             return progress->counter >= 1;
         case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET:
         case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2:
             return progress->counter >= achievementCriteria->be_spell_target.spellCount;
         case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL:
         case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2:
             return progress->counter >= achievementCriteria->cast_spell.castCount;
         case ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE:
             return progress->counter >= achievementCriteria->bg_objective.completeCount;
         case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA:
             return progress->counter >= achievementCriteria->honorable_kill_at_area.killCount;
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL:
             return progress->counter >= 1;
         case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL:
         case ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL:
             return progress->counter >= achievementCriteria->honorable_kill.killCount;
         case ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM:
             return progress->counter >= achievementCriteria->own_item.itemCount;
         case ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA:
             return progress->counter >= achievementCriteria->win_rated_arena.count;
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING:
             return progress->counter >= achievementCriteria->highest_personal_rating.PersonalRating;
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL:
             return progress->counter >= (achievementCriteria->learn_skill_level.skillLevel * 75);
         case ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM:
             return progress->counter >= achievementCriteria->use_item.itemCount;
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM:
             return progress->counter >= achievementCriteria->loot_item.itemCount;
         case ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA:
             return progress->counter >= 1;
         case ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT:
             return progress->counter >= achievementCriteria->buy_bank_slot.numberOfSlots;
         case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION:
             return progress->counter >= achievementCriteria->gain_reputation.reputationAmount;
         case ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION:
             return progress->counter >= achievementCriteria->gain_exalted_reputation.numberOfExaltedFactions;
         case ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP:
             return progress->counter >= achievementCriteria->visit_barber.numberOfVisits;
         case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM:
             return progress->counter >= achievementCriteria->equip_epic_item.count;
         case ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT:
         case ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT:
             return progress->counter >= achievementCriteria->roll_greed_on_loot.count;
         case ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS:
             return progress->counter >= achievementCriteria->hk_class.count;
         case ACHIEVEMENT_CRITERIA_TYPE_HK_RACE:
             return progress->counter >= achievementCriteria->hk_race.count;
         case ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE:
             return progress->counter >= achievementCriteria->do_emote.count;
         case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM:
             return progress->counter >= achievementCriteria->equip_item.count;
         case ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD:
             return progress->counter >= achievementCriteria->quest_reward_money.goldInCopper;
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY:
             return progress->counter >= achievementCriteria->loot_money.goldInCopper;
         case ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT:
             return progress->counter >= achievementCriteria->use_gameobject.useCount;
         case ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL:
             return progress->counter >= achievementCriteria->special_pvp_kill.killCount;
         case ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT:
             return progress->counter >= achievementCriteria->fish_in_gameobject.lootCount;
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS:
             return progress->counter >= achievementCriteria->learn_skillline_spell.spellCount;
         case ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL:
             return progress->counter >= achievementCriteria->win_duel.duelCount;
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE:
             return progress->counter >= achievementCriteria->loot_type.lootTypeCount;
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE:
             return progress->counter >= achievementCriteria->learn_skill_line.spellCount;
         case ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS:
             return progress->counter >= 9000;
         case ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS:
             return progress->counter >= achievementCriteria->use_lfg.dungeonsComplete;
         case ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS:
             return progress->counter >= achievementCriteria->get_killing_blow.killCount;
         case ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN:
             return true;
         case ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA:
             return achievementCriteria->win_arena.count && progress->counter >= achievementCriteria->win_arena.count;
         // handle all statistic-only criteria here
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND:
         case ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP:
         case ACHIEVEMENT_CRITERIA_TYPE_DEATH:
         case ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON:
         case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE:
         case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER:
         case ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING:
         case ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS:
         case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS:
         case ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS:
         case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER:
         case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL:
         case ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL:
         case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE:
         case ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS:
         case ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED:
         case ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS:
         case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION:
         case ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION:
         case ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS:
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED:
         case ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER:
         case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR:
         case ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED:
         case ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN:
         case ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS:
         case ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA:
         default:
             break;
     }
     return false;
 }
References ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE, ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_DEATH, ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP, ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON, ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS, ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN, ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING, ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS, ACHIEVEMENT_CRITERIA_TYPE_HK_RACE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL, ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM, ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA, ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED, ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS, ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP, ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, AchievementCriteriaEntry::be_spell_target, AchievementCriteriaEntry::bg_objective, AchievementCriteriaEntry::buy_bank_slot, AchievementCriteriaEntry::cast_spell, AchievementCriteriaEntry::complete_daily_quest, AchievementCriteriaEntry::complete_daily_quest_daily, AchievementCriteriaEntry::complete_quest_count, AchievementCriteriaEntry::complete_quests_in_zone, CriteriaProgress::counter, AchievementCriteriaEntry::do_emote, AchievementCriteriaEntry::equip_epic_item, AchievementCriteriaEntry::equip_item, AchievementCriteriaEntry::fall_without_dying, AchievementCriteriaEntry::fish_in_gameobject, AchievementEntry::flags, AchievementCriteriaEntry::gain_exalted_reputation, AchievementCriteriaEntry::gain_reputation, AchievementCriteriaEntry::get_killing_blow, GetCriteriaProgress(), HasAchieved(), AchievementCriteriaEntry::healing_done, AchievementCriteriaEntry::highest_personal_rating, AchievementCriteriaEntry::hk_class, AchievementCriteriaEntry::hk_race, AchievementCriteriaEntry::honorable_kill, AchievementCriteriaEntry::honorable_kill_at_area, AchievementEntry::ID, IsCompletedAchievement(), AchievementCriteriaEntry::kill_creature, AchievementCriteriaEntry::learn_skill_level, AchievementCriteriaEntry::learn_skill_line, AchievementCriteriaEntry::learn_skillline_spell, AchievementCriteriaEntry::loot_item, AchievementCriteriaEntry::loot_money, AchievementCriteriaEntry::loot_type, AchievementCriteriaEntry::own_item, AchievementCriteriaEntry::quest_reward_money, AchievementCriteriaEntry::reach_level, AchievementCriteriaEntry::reach_skill_level, AchievementCriteriaEntry::requiredType, AchievementCriteriaEntry::roll_greed_on_loot, sAchievementMgr, AchievementCriteriaEntry::special_pvp_kill, sScriptMgr, AchievementCriteriaEntry::use_gameobject, AchievementCriteriaEntry::use_item, AchievementCriteriaEntry::use_lfg, AchievementCriteriaEntry::visit_barber, AchievementCriteriaEntry::win_arena, AchievementCriteriaEntry::win_bg, AchievementCriteriaEntry::win_duel, and AchievementCriteriaEntry::win_rated_arena.
Referenced by CanUpdateCriteria(), IsCompletedAchievement(), ResetAchievementCriteria(), SetCriteriaProgress(), StartTimedAchievement(), and UpdateAchievementCriteria().
LoadFromDB()
void AchievementMgr::LoadFromDB (PreparedQueryResult achievementResult, PreparedQueryResult criteriaResult)
Definition at line 602 of file AchievementMgr.cpp.
 {
     if (achievementResult)
     {
         do
         {
             Field* fields = achievementResult->Fetch();
             uint32 achievementid = fields[0].GetUInt16();
             // must not happen: cleanup at server startup in sAchievementMgr->LoadCompletedAchievements()
             AchievementEntry const* achievement = sAchievementStore.LookupEntry(achievementid);
             if (!achievement)
                 continue;
             CompletedAchievementData& ca = m_completedAchievements[achievementid];
             ca.date = time_t(fields[1].GetUInt32());
             ca.changed = false;
             // title achievement rewards are retroactive
             if (AchievementReward const* reward = sAchievementMgr->GetAchievementReward(achievement))
                 if (uint32 titleId = reward->titleId[Player::TeamIdForRace(GetPlayer()->getRace())])
                     if (CharTitlesEntry const* titleEntry = sCharTitlesStore.LookupEntry(titleId))
                         if (!GetPlayer()->HasTitle(titleEntry))
                             GetPlayer()->SetTitle(titleEntry);
         } while (achievementResult->NextRow());
     }
     if (criteriaResult)
     {
         do
         {
             Field* fields = criteriaResult->Fetch();
             uint32 id      = fields[0].GetUInt16();
             uint32 counter = fields[1].GetUInt32();
             time_t date    = time_t(fields[2].GetUInt32());
             AchievementCriteriaEntry const* criteria = sAchievementCriteriaStore.LookupEntry(id);
             if (!criteria)
             {
                 // we will remove not existed criteria for all characters
                 LOG_ERROR("achievement", "Non-existing achievement criteria %u data removed from table `character_achievement_progress`.", id);
                 CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_INVALID_ACHIEV_PROGRESS_CRITERIA);
                 stmt->setUInt16(0, uint16(id));
                 CharacterDatabase.Execute(stmt);
                 continue;
             }
             if (criteria->timeLimit && time_t(date + criteria->timeLimit) < time(nullptr))
                 continue;
             CriteriaProgress& progress = m_criteriaProgress[id];
             progress.counter = counter;
             progress.date    = date;
             progress.changed = false;
         } while (criteriaResult->NextRow());
     }
 }
References CriteriaProgress::changed, CompletedAchievementData::changed, CHAR_DEL_INVALID_ACHIEV_PROGRESS_CRITERIA, CharacterDatabase, CriteriaProgress::counter, CriteriaProgress::date, CompletedAchievementData::date, GetPlayer(), Field::GetUInt16(), Field::GetUInt32(), LOG_ERROR, m_completedAchievements, m_criteriaProgress, sAchievementCriteriaStore, sAchievementMgr, sAchievementStore, sCharTitlesStore, Player::SetTitle(), PreparedStatementBase::setUInt16(), Player::TeamIdForRace(), and AchievementCriteriaEntry::timeLimit.
Referenced by Player::LoadFromDB().
RemoveCriteriaProgress()
void AchievementMgr::RemoveCriteriaProgress (AchievementCriteriaEntry const * entry)
Definition at line 2102 of file AchievementMgr.cpp.
 {
     CriteriaProgressMap::iterator criteriaProgress = m_criteriaProgress.find(entry->ID);
     if (criteriaProgress == m_criteriaProgress.end())
         return;
     WorldPacket data(SMSG_CRITERIA_DELETED, 4);
     data << uint32(entry->ID);
     m_player->SendDirectMessage(&data);
     m_criteriaProgress.erase(criteriaProgress);
 }
References AchievementCriteriaEntry::ID, m_criteriaProgress, m_player, Player::SendDirectMessage(), and SMSG_CRITERIA_DELETED.
Referenced by RemoveTimedAchievement(), ResetAchievementCriteria(), and UpdateTimedAchievements().
RemoveTimedAchievement()
void AchievementMgr::RemoveTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
Definition at line 2160 of file AchievementMgr.cpp.
 {
     AchievementCriteriaEntryList const& achievementCriteriaList = sAchievementMgr->GetTimedAchievementCriteriaByType(type);
     for (AchievementCriteriaEntryList::const_iterator i = achievementCriteriaList.begin(); i != achievementCriteriaList.end(); ++i)
     {
         if ((*i)->timerStartEvent != entry)
             continue;
         TimedAchievementMap::iterator timedIter = m_timedAchievements.find((*i)->ID);
         // We don't have timer for this achievement
         if (timedIter == m_timedAchievements.end())
             continue;
         // remove progress
         RemoveCriteriaProgress(*i);
         // Remove the timer
         m_timedAchievements.erase(timedIter);
     }
 }
References m_timedAchievements, RemoveCriteriaProgress(), and sAchievementMgr.
Referenced by Player::RemoveTimedAchievement().
Reset()
void AchievementMgr::Reset ()
Definition at line 480 of file AchievementMgr.cpp.
 {
     for (CompletedAchievementMap::const_iterator iter = m_completedAchievements.begin(); iter != m_completedAchievements.end(); ++iter)
     {
         WorldPacket data(SMSG_ACHIEVEMENT_DELETED, 4);
         data << uint32(iter->first);
         m_player->SendDirectMessage(&data);
     }
     for (CriteriaProgressMap::const_iterator iter = m_criteriaProgress.begin(); iter != m_criteriaProgress.end(); ++iter)
     {
         WorldPacket data(SMSG_CRITERIA_DELETED, 4);
         data << uint32(iter->first);
         m_player->SendDirectMessage(&data);
     }
     m_completedAchievements.clear();
     m_criteriaProgress.clear();
     DeleteFromDB(m_player->GetGUID().GetCounter());
     // re-fill data
     CheckAllAchievementCriteria();
 }
References CheckAllAchievementCriteria(), DeleteFromDB(), ObjectGuid::GetCounter(), Object::GetGUID(), m_completedAchievements, m_criteriaProgress, m_player, Player::SendDirectMessage(), SMSG_ACHIEVEMENT_DELETED, and SMSG_CRITERIA_DELETED.
Referenced by Player::ResetAchievements().
ResetAchievementCriteria()
void AchievementMgr::ResetAchievementCriteria (AchievementCriteriaCondition condition, uint32 value, bool evenIfCriteriaComplete = false)
Definition at line 504 of file AchievementMgr.cpp.
 {
     // disable for gamemasters with GM-mode enabled
     if (m_player->IsGameMaster())
         return;
     LOG_DEBUG("achievement", "AchievementMgr::ResetAchievementCriteria(%u, %u, %u)", condition, value, evenIfCriteriaComplete);
     AchievementCriteriaEntryList const* achievementCriteriaList = sAchievementMgr->GetAchievementCriteriaByCondition(condition, value);
     if (!achievementCriteriaList)
         return;
     for (AchievementCriteriaEntryList::const_iterator i = achievementCriteriaList->begin(); i != achievementCriteriaList->end(); ++i)
     {
         AchievementCriteriaEntry const* achievementCriteria = (*i);
         AchievementEntry const* achievement = sAchievementStore.LookupEntry(achievementCriteria->referredAchievement);
         if (!achievement)
             continue;
         // don't update already completed criteria if not forced or achievement already complete
         if ((IsCompletedCriteria(achievementCriteria, achievement) && !evenIfCriteriaComplete) || HasAchieved(achievement->ID))
             continue;
         RemoveCriteriaProgress(achievementCriteria);
     }
 }
References HasAchieved(), AchievementEntry::ID, IsCompletedCriteria(), Player::IsGameMaster(), LOG_DEBUG, m_player, AchievementCriteriaEntry::referredAchievement, RemoveCriteriaProgress(), sAchievementMgr, and sAchievementStore.
Referenced by Player::ResetAchievementCriteria().
SaveToDB()
void AchievementMgr::SaveToDB (CharacterDatabaseTransaction trans)
Definition at line 546 of file AchievementMgr.cpp.
 {
     if (!m_completedAchievements.empty())
     {
         for (CompletedAchievementMap::iterator iter = m_completedAchievements.begin(); iter != m_completedAchievements.end(); ++iter)
         {
             if (!iter->second.changed)
                 continue;
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_ACHIEVEMENT_BY_ACHIEVEMENT);
             stmt->setUInt16(0, iter->first);
             stmt->setUInt32(1, GetPlayer()->GetGUID().GetCounter());
             trans->Append(stmt);
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHAR_ACHIEVEMENT);
             stmt->setUInt32(0, GetPlayer()->GetGUID().GetCounter());
             stmt->setUInt16(1, iter->first);
             stmt->setUInt32(2, uint32(iter->second.date));
             trans->Append(stmt);
             iter->second.changed = false;
             sScriptMgr->OnAchievementSave(trans, GetPlayer(), iter->first, iter->second);
         }
     }
     if (!m_criteriaProgress.empty())
     {
         for (CriteriaProgressMap::iterator iter = m_criteriaProgress.begin(); iter != m_criteriaProgress.end(); ++iter)
         {
             if (!iter->second.changed)
                 continue;
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS_BY_CRITERIA);
             stmt->setUInt32(0, GetPlayer()->GetGUID().GetCounter());
             stmt->setUInt16(1, iter->first);
             trans->Append(stmt);
             // pussywizard: insert only for (counter != 0) is very important! this is how criteria of completed achievements gets deleted from db (by setting counter to 0); if conflicted during merge - contact me
             if (iter->second.counter)
             {
                 stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHAR_ACHIEVEMENT_PROGRESS);
                 stmt->setUInt32(0, GetPlayer()->GetGUID().GetCounter());
                 stmt->setUInt16(1, iter->first);
                 stmt->setUInt32(2, iter->second.counter);
                 stmt->setUInt32(3, uint32(iter->second.date));
                 trans->Append(stmt);
             }
             iter->second.changed = false;
             sScriptMgr->OnCriteriaSave(trans, GetPlayer(), iter->first, iter->second);
         }
     }
 }
References CHAR_DEL_CHAR_ACHIEVEMENT_BY_ACHIEVEMENT, CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS_BY_CRITERIA, CHAR_INS_CHAR_ACHIEVEMENT, CHAR_INS_CHAR_ACHIEVEMENT_PROGRESS, CharacterDatabase, GetPlayer(), m_completedAchievements, m_criteriaProgress, PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), and sScriptMgr.
Referenced by Player::SaveToDB().
SendAchievementEarned()
void AchievementMgr::SendAchievementEarned (AchievementEntry const * achievement) const private
Definition at line 664 of file AchievementMgr.cpp.
 {
     if (GetPlayer()->GetSession()->PlayerLoading())
         return;
     // Don't send for achievements with ACHIEVEMENT_FLAG_TRACKING
     if (achievement->flags & ACHIEVEMENT_FLAG_HIDDEN)
         return;
     LOG_DEBUG("achievement", "AchievementMgr::SendAchievementEarned(%u)", achievement->ID);
     Guild* guild = sGuildMgr->GetGuildById(GetPlayer()->GetGuildId());
     if (guild)
     {
         Acore::BroadcastTextBuilder _builder(GetPlayer(), CHAT_MSG_GUILD_ACHIEVEMENT, BROADCAST_TEXT_ACHIEVEMENT_EARNED, GetPlayer()->getGender(), GetPlayer(), achievement->ID);
         Acore::LocalizedPacketDo<Acore::BroadcastTextBuilder> _localizer(_builder);
         guild->BroadcastWorker(_localizer, GetPlayer());
     }
     if (achievement->flags & (ACHIEVEMENT_FLAG_REALM_FIRST_KILL | ACHIEVEMENT_FLAG_REALM_FIRST_REACH))
     {
         // If guild exists - send its name to the server
         // If guild does not exist - send player's name to the server
         if (achievement->flags & ACHIEVEMENT_FLAG_REALM_FIRST_KILL && guild)
         {
             WorldPacket data(SMSG_SERVER_FIRST_ACHIEVEMENT, guild->GetName().size() + 1 + 8 + 4 + 4);
             data << guild->GetName();
             data << GetPlayer()->GetGUID();
             data << uint32(achievement->ID);
             data << uint32(0);                                  // display name as plain string in chat (always 0 for guild)
             sWorld->SendGlobalMessage(&data);
         }
         else
         {
             TeamId teamId = GetPlayer()->GetTeamId();
             // broadcast realm first reached
             WorldPacket data(SMSG_SERVER_FIRST_ACHIEVEMENT, GetPlayer()->GetName().size() + 1 + 8 + 4 + 4);
             data << GetPlayer()->GetName();
             data << GetPlayer()->GetGUID();
             data << uint32(achievement->ID);
             std::size_t linkTypePos = data.wpos();
             data << uint32(1);                                  // display name as clickable link in chat
             sWorld->SendGlobalMessage(&data, nullptr, teamId);
             data.put<uint32>(linkTypePos, 0);                   // display name as plain string in chat
             sWorld->SendGlobalMessage(&data, nullptr, teamId == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE);
         }
     }
     // if player is in world he can tell his friends about new achievement
     else if (GetPlayer()->IsInWorld())
     {
         CellCoord p = Acore::ComputeCellCoord(GetPlayer()->GetPositionX(), GetPlayer()->GetPositionY());
         Cell cell(p);
         cell.SetNoCreate();
         Acore::BroadcastTextBuilder _builder(GetPlayer(), CHAT_MSG_ACHIEVEMENT, BROADCAST_TEXT_ACHIEVEMENT_EARNED, GetPlayer()->getGender(), GetPlayer(), achievement->ID);
         Acore::LocalizedPacketDo<Acore::BroadcastTextBuilder> _localizer(_builder);
         Acore::PlayerDistWorker<Acore::LocalizedPacketDo<Acore::BroadcastTextBuilder>> _worker(GetPlayer(), sWorld->getFloatConfig(CONFIG_LISTEN_RANGE_SAY), _localizer);
         TypeContainerVisitor<Acore::PlayerDistWorker<Acore::LocalizedPacketDo<Acore::BroadcastTextBuilder> >, WorldTypeMapContainer > message(_worker);
         Cell::VisitWorldObjects(GetPlayer(), _worker, sWorld->getFloatConfig(CONFIG_LISTEN_RANGE_SAY));
     }
     WorldPacket data(SMSG_ACHIEVEMENT_EARNED, 8 + 4 + 8);
     data << GetPlayer()->GetPackGUID();
     data << uint32(achievement->ID);
     data.AppendPackedTime(time(nullptr));
     data << uint32(0);
     GetPlayer()->SendMessageToSetInRange(&data, sWorld->getFloatConfig(CONFIG_LISTEN_RANGE_SAY), true);
 }
References ACHIEVEMENT_FLAG_HIDDEN, ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, ByteBuffer::AppendPackedTime(), BROADCAST_TEXT_ACHIEVEMENT_EARNED, Guild::BroadcastWorker(), CHAT_MSG_ACHIEVEMENT, CHAT_MSG_GUILD_ACHIEVEMENT, Acore::ComputeCellCoord(), CONFIG_LISTEN_RANGE_SAY, AchievementEntry::flags, Object::GetGUID(), WorldObject::GetName(), Guild::GetName(), AccountMgr::GetName(), Object::GetPackGUID(), GetPlayer(), Player::GetTeamId(), AchievementEntry::ID, Object::IsInWorld(), LOG_DEBUG, message(), ByteBuffer::put(), Player::SendMessageToSetInRange(), Cell::SetNoCreate(), sGuildMgr, SMSG_ACHIEVEMENT_EARNED, SMSG_SERVER_FIRST_ACHIEVEMENT, sWorld, TEAM_ALLIANCE, TEAM_HORDE, Cell::VisitWorldObjects(), and ByteBuffer::wpos().
Referenced by CompletedAchievement().
SendAllAchievementData()
void AchievementMgr::SendAllAchievementData () const
Definition at line 2293 of file AchievementMgr.cpp.
 {
     WorldPacket data(SMSG_ALL_ACHIEVEMENT_DATA, m_completedAchievements.size() * 8 + 4 + m_criteriaProgress.size() * 38 + 4);
     BuildAllDataPacket(&data);
     GetPlayer()->GetSession()->SendPacket(&data);
 }
References BuildAllDataPacket(), GetPlayer(), Player::GetSession(), m_completedAchievements, m_criteriaProgress, WorldSession::SendPacket(), and SMSG_ALL_ACHIEVEMENT_DATA.
Referenced by Player::SendInitialPacketsBeforeAddToMap().
SendCriteriaUpdate()
void AchievementMgr::SendCriteriaUpdate (AchievementCriteriaEntry const * entry, CriteriaProgress const * progress, uint32 timeElapsed, bool timedCompleted) const private
Definition at line 736 of file AchievementMgr.cpp.
 {
     WorldPacket data(SMSG_CRITERIA_UPDATE, 8 + 4 + 8);
     data << uint32(entry->ID);
     // the counter is packed like a packed Guid
     data.appendPackGUID(progress->counter);
     data << GetPlayer()->GetPackGUID();
     if (!entry->timeLimit)
         data << uint32(0);
     else
         data << uint32(timedCompleted ? 0 : 1); // 1 is for keeping the counter at 0 in client
     data.AppendPackedTime(progress->date);
     data << uint32(timeElapsed);    // time elapsed in seconds
     data << uint32(0);              // unk
     GetPlayer()->SendDirectMessage(&data);
 }
References ByteBuffer::AppendPackedTime(), ByteBuffer::appendPackGUID(), CriteriaProgress::counter, CriteriaProgress::date, Object::GetPackGUID(), GetPlayer(), AchievementCriteriaEntry::ID, Player::SendDirectMessage(), SMSG_CRITERIA_UPDATE, and AchievementCriteriaEntry::timeLimit.
Referenced by SetCriteriaProgress().
SendRespondInspectAchievements()
void AchievementMgr::SendRespondInspectAchievements (Player * player) const
Definition at line 2300 of file AchievementMgr.cpp.
 {
     WorldPacket data(SMSG_RESPOND_INSPECT_ACHIEVEMENTS, 9 + m_completedAchievements.size() * 8 + 4 + m_criteriaProgress.size() * 38 + 4);
     data << GetPlayer()->GetPackGUID();
     BuildAllDataPacket(&data);
     player->GetSession()->SendPacket(&data);
 }
References BuildAllDataPacket(), Object::GetPackGUID(), GetPlayer(), Player::GetSession(), m_completedAchievements, m_criteriaProgress, WorldSession::SendPacket(), and SMSG_RESPOND_INSPECT_ACHIEVEMENTS.
Referenced by Player::SendRespondInspectAchievements().
SetCriteriaProgress()
void AchievementMgr::SetCriteriaProgress (AchievementCriteriaEntry const * entry, uint32 changeValue, ProgressType ptype = PROGRESS_SET) private
Definition at line 2026 of file AchievementMgr.cpp.
 {
     // Don't allow to cheat - doing timed achievements without timer active
     TimedAchievementMap::iterator timedIter = m_timedAchievements.find(entry->ID);
     if (entry->timeLimit && timedIter == m_timedAchievements.end())
         return;
     if (!sScriptMgr->OnBeforeCriteriaProgress(GetPlayer(), entry))
     {
         return;
     }
     LOG_DEBUG("achievement", "AchievementMgr::SetCriteriaProgress(%u, %u) for %s", entry->ID, changeValue, m_player->GetGUID().ToString().c_str());
     CriteriaProgress* progress = GetCriteriaProgress(entry);
     if (!progress)
     {
         // not create record for 0 counter but allow it for timed achievements
         // we will need to send 0 progress to client to start the timer
         if (changeValue == 0 && !entry->timeLimit)
             return;
         progress = &m_criteriaProgress[entry->ID];
         progress->counter = changeValue;
     }
     else
     {
         uint32 newValue = 0;
         switch (ptype)
         {
             case PROGRESS_SET:
             case PROGRESS_RESET:
                 newValue = changeValue;
                 break;
             case PROGRESS_ACCUMULATE:
                 {
                     // avoid overflow
                     uint32 max_value = std::numeric_limits<uint32>::max();
                     newValue = max_value - progress->counter > changeValue ? progress->counter + changeValue : max_value;
                     break;
                 }
             case PROGRESS_HIGHEST:
                 newValue = progress->counter < changeValue ? changeValue : progress->counter;
                 break;
         }
         // not update (not mark as changed) if counter will have same value
         if (ptype != PROGRESS_RESET && progress->counter == newValue && !entry->timeLimit)
             return;
         progress->counter = newValue;
     }
     progress->changed = true;
     progress->date = time(nullptr); // set the date to the latest update.
     uint32 timeElapsed = 0;
     bool timedCompleted = false;
     if (entry->timeLimit)
     {
         // has to exist else we wouldn't be here
         timedCompleted = IsCompletedCriteria(entry, sAchievementStore.LookupEntry(entry->referredAchievement));
         // Client expects this in packet
         timeElapsed = entry->timeLimit - (timedIter->second / IN_MILLISECONDS);
         // Remove the timer, we wont need it anymore
         if (timedCompleted)
             m_timedAchievements.erase(timedIter);
     }
     SendCriteriaUpdate(entry, progress, timeElapsed, true);
     sScriptMgr->OnCriteriaProgress(GetPlayer(), entry);
 }
References CriteriaProgress::changed, CriteriaProgress::counter, CriteriaProgress::date, GetCriteriaProgress(), Object::GetGUID(), GetPlayer(), AchievementCriteriaEntry::ID, IN_MILLISECONDS, IsCompletedCriteria(), LOG_DEBUG, m_criteriaProgress, m_player, m_timedAchievements, PROGRESS_ACCUMULATE, PROGRESS_HIGHEST, PROGRESS_RESET, PROGRESS_SET, AchievementCriteriaEntry::referredAchievement, sAchievementStore, SendCriteriaUpdate(), sScriptMgr, AchievementCriteriaEntry::timeLimit, and ObjectGuid::ToString().
Referenced by StartTimedAchievement(), and UpdateAchievementCriteria().
StartTimedAchievement()
void AchievementMgr::StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry, uint32 timeLost = 0)
Definition at line 2137 of file AchievementMgr.cpp.
 {
     AchievementCriteriaEntryList const& achievementCriteriaList = sAchievementMgr->GetTimedAchievementCriteriaByType(type);
     for (AchievementCriteriaEntryList::const_iterator i = achievementCriteriaList.begin(); i != achievementCriteriaList.end(); ++i)
     {
         if ((*i)->timerStartEvent != entry)
             continue;
         AchievementEntry const* achievement = sAchievementStore.LookupEntry((*i)->referredAchievement);
         if (m_timedAchievements.find((*i)->ID) == m_timedAchievements.end() && !IsCompletedCriteria(*i, achievement))
         {
             // Start the timer
             if ((*i)->timeLimit * IN_MILLISECONDS > timeLost)
             {
                 m_timedAchievements[(*i)->ID] = (*i)->timeLimit * IN_MILLISECONDS - timeLost;
                 // and at client too
                 SetCriteriaProgress(*i, 0, PROGRESS_SET);
             }
         }
     }
 }
References IN_MILLISECONDS, IsCompletedCriteria(), m_timedAchievements, PROGRESS_SET, sAchievementMgr, sAchievementStore, and SetCriteriaProgress().
Referenced by Player::StartTimedAchievement().
UpdateAchievementCriteria()
void AchievementMgr::UpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1 = 0, uint32 miscValue2 = 0, Unit * unit = nullptr)
this function will be called whenever the user might have done a criteria relevant action
Definition at line 780 of file AchievementMgr.cpp.
 {
     // disable for gamemasters with GM-mode enabled
     if (m_player->IsGameMaster())
         return;
     if (type >= ACHIEVEMENT_CRITERIA_TYPE_TOTAL)
     {
         LOG_DEBUG("achievement", "UpdateAchievementCriteria: Wrong criteria type %u", type);
         return;
     }
     LOG_DEBUG("achievement", "AchievementMgr::UpdateAchievementCriteria(%u, %u, %u)", type, miscValue1, miscValue2);
     AchievementCriteriaEntryList const* achievementCriteriaList = nullptr;
     switch (type)
     {
         case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE:
         case ACHIEVEMENT_CRITERIA_TYPE_WIN_BG:
         case ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL:
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT:
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE:
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND:
         case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE:
         case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST:
         case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET:
         case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL:
         case ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE:
         case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA:
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL:
         case ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL:
         case ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA:
         case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION:
         case ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS:
         case ACHIEVEMENT_CRITERIA_TYPE_HK_RACE:
         case ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE:
         case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM:
         case ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT:
         case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2:
         case ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT:
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS:
         case ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE:
         case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2:
         case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE:
             if (miscValue1)
             {
                 achievementCriteriaList = sAchievementMgr->GetSpecialAchievementCriteriaByType(type, miscValue1);
                 break;
             }
             achievementCriteriaList = sAchievementMgr->GetAchievementCriteriaByType(type);
             break;
         case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM:
             if (miscValue2)
             {
                 achievementCriteriaList = sAchievementMgr->GetSpecialAchievementCriteriaByType(type, miscValue2);
                 break;
             }
             achievementCriteriaList = sAchievementMgr->GetAchievementCriteriaByType(type);
             break;
         default:
             achievementCriteriaList = sAchievementMgr->GetAchievementCriteriaByType(type);
             break;
     }
     if (!achievementCriteriaList)
         return;
     sScriptMgr->OnBeforeCheckCriteria(this, achievementCriteriaList);
     for (AchievementCriteriaEntryList::const_iterator i = achievementCriteriaList->begin(); i != achievementCriteriaList->end(); ++i)
     {
         AchievementCriteriaEntry const* achievementCriteria = (*i);
         AchievementEntry const* achievement = sAchievementStore.LookupEntry(achievementCriteria->referredAchievement);
         if (!achievement)
             continue;
         if (!CanUpdateCriteria(achievementCriteria, achievement))
             continue;
         if (!sScriptMgr->CanCheckCriteria(this, achievementCriteria))
             continue;
         switch (type)
         {
             // std. case: increment at 1
             case ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS:
             case ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL:
             case ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION:
             case ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS:    /* FIXME: for online player only currently */
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED:
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED:
             case ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED:
             case ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN:
             case ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             // std case: increment at miscvalue1
             case ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS:
             case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS:
             case ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD:
             case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING:
             case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER:
             case ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL:
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY:
             case ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS:/* FIXME: for online player only currently */
             case ACHIEVEMENT_CRITERIA_TYPE_TOTAL_DAMAGE_RECEIVED:
             case ACHIEVEMENT_CRITERIA_TYPE_TOTAL_HEALING_RECEIVED:
             case ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_ACCUMULATE);
                 break;
             // std case: high value at miscvalue1
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD: /* FIXME: for online player only currently */
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_DEALT:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_RECEIVED:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEAL_CASTED:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALING_RECEIVED:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_HIGHEST);
                 break;
             // specialized cases
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     if (achievement->categoryId == CATEGORY_CHILDRENS_WEEK)
                     {
                         AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                         if (!data || !data->Meets(GetPlayer(), nullptr))
                             continue;
                     }
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_BG:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     if (achievementCriteria->win_bg.bgMapID != GetPlayer()->GetMapId())
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     if (achievementCriteria->kill_creature.creatureID != miscValue1)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, miscValue2, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue2)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit, miscValue1))
                         continue;
                     SetCriteriaProgress(achievementCriteria, miscValue2, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL:
                 if (AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria))
                     if (!data->Meets(GetPlayer(), unit))
                         continue;
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->getLevel());
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL:
                 // update at loading or specific skill update
                 if (miscValue1 && miscValue1 != achievementCriteria->reach_skill_level.skillID)
                     continue;
                 if (uint32 skillvalue = GetPlayer()->GetBaseSkillValue(achievementCriteria->reach_skill_level.skillID))
                     SetCriteriaProgress(achievementCriteria, skillvalue);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL:
                 // update at loading or specific skill update
                 if (miscValue1 && miscValue1 != achievementCriteria->learn_skill_level.skillID)
                     continue;
                 if (uint32 maxSkillvalue = GetPlayer()->GetPureMaxSkillValue(achievementCriteria->learn_skill_level.skillID))
                     SetCriteriaProgress(achievementCriteria, maxSkillvalue);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT:
                 if ((miscValue1 && achievementCriteria->complete_achievement.linkedAchievement == miscValue1) || (!miscValue1 && GetPlayer()->HasAchieved(achievementCriteria->complete_achievement.linkedAchievement)))
                     SetCriteriaProgress(achievementCriteria, 1);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT:
                 {
                     SetCriteriaProgress(achievementCriteria, GetPlayer()->GetRewardedQuestCount());
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY:
                 {
                     time_t nextDailyResetTime = sWorld->GetNextDailyQuestsResetTime();
                     CriteriaProgress* progress = GetCriteriaProgress(achievementCriteria);
                     if (!miscValue1) // Login case.
                     {
                         // reset if player missed one day.
                         if (progress && progress->date < (nextDailyResetTime - 2 * DAY))
                             SetCriteriaProgress(achievementCriteria, 0, PROGRESS_SET);
                         continue;
                     }
                     ProgressType progressType;
                     if (!progress)
                         // 1st time. Start count.
                         progressType = PROGRESS_SET;
                     else if (progress->date < (nextDailyResetTime - 2 * DAY))
                         // last progress is older than 2 days. Player missed 1 day => Retart count.
                         progressType = PROGRESS_RESET;
                     else if (progress->date < (nextDailyResetTime - DAY))
                         // last progress is between 1 and 2 days. => 1st time of the day.
                         progressType = PROGRESS_ACCUMULATE;
                     else
                         // last progress is within the day before the reset => Already counted today.
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, progressType);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE:
                 {
                     // speedup for non-login case
                     if (miscValue1 && miscValue1 != achievementCriteria->complete_quests_in_zone.zoneID)
                         continue;
                     uint32 counter = 0;
                     const RewardedQuestSet& rewQuests = GetPlayer()->getRewardedQuests();
                     for (RewardedQuestSet::const_iterator itr = rewQuests.begin(); itr != rewQuests.end(); ++itr)
                     {
                         Quest const* quest = sObjectMgr->GetQuestTemplate(*itr);
                         if (quest && quest->GetZoneOrSort() >= 0 && uint32(quest->GetZoneOrSort()) == achievementCriteria->complete_quests_in_zone.zoneID)
                             ++counter;
                     }
                     SetCriteriaProgress(achievementCriteria, counter);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (GetPlayer()->GetMapId() != achievementCriteria->complete_battleground.mapID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (GetPlayer()->GetMapId() != achievementCriteria->death_at_map.mapID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_DEATH:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     // skip wrong arena achievements, if not achievIdByArenaSlot then normal total death counter
                     bool notfit = false;
                     for (int j = 0; j < MAX_ARENA_SLOT; ++j)
                     {
                         if (achievIdByArenaSlot[j] == achievement->ID)
{
                             Battleground* bg = GetPlayer()->GetBattleground();
                             if (!bg || !bg->isArena() || ArenaTeam::GetSlotByType(bg->GetArenaType()) != j)
                                 notfit = true;
                             break;
                         }
                     }
                     if (notfit)
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     Map const* map = GetPlayer()->IsInWorld() ? GetPlayer()->GetMap() : sMapMgr->FindMap(GetPlayer()->GetMapId(), GetPlayer()->GetInstanceId());
                     if (!map || !map->IsDungeon())
                         continue;
                     // search case
                     bool found = false;
                     for (int j = 0; achievIdForDungeon[j][0]; ++j)
                     {
                         if (achievIdForDungeon[j][0] == achievement->ID)
{
                             if (map->IsRaid())
{
                                 // if raid accepted (ignore difficulty)
                                 if (!achievIdForDungeon[j][2])
                                     break;                      // for
                             }
                             else if (GetPlayer()->GetDungeonDifficulty() == DUNGEON_DIFFICULTY_NORMAL)
{
                                 // dungeon in normal mode accepted
                                 if (!achievIdForDungeon[j][1])
                                     break;                      // for
                             }
                             else
{
                                 // dungeon in heroic mode accepted
                                 if (!achievIdForDungeon[j][3])
                                     break;                      // for
                             }
                             found = true;
                             break;                              // for
                         }
                     }
                     if (!found)
                         continue;
                     //FIXME: work only for instances where max == min for players
                     if (map->ToInstanceMap()->GetMaxPlayers() != achievementCriteria->death_in_dungeon.manLimit)
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (miscValue1 != achievementCriteria->killed_by_creature.creatureEntry)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 // if team check required: must kill by opposition faction
                 if (achievement->ID == 318 && miscValue2 == GetPlayer()->GetTeamId())
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     // miscvalue1 is the ingame fallheight*100 as stored in dbc
                     SetCriteriaProgress(achievementCriteria, miscValue1);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (miscValue2 != achievementCriteria->death_from.type)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST:
                 {
                     // if miscvalues != 0, it contains the questID.
                     if (miscValue1)
                     {
                         if (miscValue1 != achievementCriteria->complete_quest.questID)
                             continue;
                     }
                     else
                     {
                         // login case.
                         if (!GetPlayer()->GetQuestRewardStatus(achievementCriteria->complete_quest.questID))
                             continue;
                     }
                     if (AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria))
                         if (!data->Meets(GetPlayer(), unit))
                             continue;
                     SetCriteriaProgress(achievementCriteria, 1);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET:
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2:
                 {
                     if (!miscValue1 || miscValue1 != achievementCriteria->be_spell_target.spellID)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data)
                         continue;
                     if (!data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL:
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2:
                 {
                     if (!miscValue1 || miscValue1 != achievementCriteria->cast_spell.spellID)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data)
                         continue;
                     if (!data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL:
                 if (miscValue1 && miscValue1 != achievementCriteria->learn_spell.spellID)
                     continue;
                 if (GetPlayer()->HasSpell(achievementCriteria->learn_spell.spellID))
                     SetCriteriaProgress(achievementCriteria, 1);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE:
                 {
                     // miscvalue1=loot_type (note: 0 = LOOT_CORPSE and then it ignored)
                     // miscvalue2=count of item loot
                     if (!miscValue1 || !miscValue2)
                         continue;
                     if (miscValue1 != achievementCriteria->loot_type.lootType)
                         continue;
                     // zone specific
                     if (achievementCriteria->loot_type.lootTypeCount == 1)
                     {
                         // those requirements couldn't be found in the dbc
                         AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                         if (!data || !data->Meets(GetPlayer(), unit))
                             continue;
                     }
                     SetCriteriaProgress(achievementCriteria, miscValue2, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM:
                 // speedup for non-login case
                 if (miscValue1 && achievementCriteria->own_item.itemID != miscValue1)
                     continue;
                 SetCriteriaProgress(achievementCriteria, miscValue2, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA:
                 if (!miscValue1)                            // no update at login
                     continue;
                 // additional requirements
                 if (achievementCriteria->additionalRequirements[0].additionalRequirement_type == ACHIEVEMENT_CRITERIA_CONDITION_NO_LOSE)
                 {
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit, miscValue1))
                     {
                         // reset the progress as we have a win without the requirement.
                         SetCriteriaProgress(achievementCriteria, 0);
                         continue;
                     }
                 }
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (achievementCriteria->use_item.itemID != miscValue1)
                     continue;
                 // Children's Week achievements have extra requirements
                 //if (achievement->categoryId == CATEGORY_CHILDRENS_WEEK || achievement->ID == 1291) // Lonely?
                 {
                     // Xinef: skip progress only if data exists and is not meet
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (data && !data->Meets(GetPlayer(), nullptr))
                         continue;
                 }
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM:
                 // You _have_ to loot that item, just owning it when logging in does _not_ count!
                 if (!miscValue1)
                     continue;
                 if (miscValue1 != achievementCriteria->own_item.itemID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, miscValue2, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA:
                 {
                     WorldMapOverlayEntry const* worldOverlayEntry = sWorldMapOverlayStore.LookupEntry(achievementCriteria->explore_area.areaReference);
                     if (!worldOverlayEntry)
                         break;
                     bool matchFound = false;
                     for (int j = 0; j < MAX_WORLD_MAP_OVERLAY_AREA_IDX; ++j)
                     {
                         AreaTableEntry const* area = sAreaTableStore.LookupEntry(worldOverlayEntry->areatableID[j]);
                         if (!area)
                             break;
                         uint32 playerIndexOffset = uint32(area->exploreFlag) / 32;
                         if (playerIndexOffset >= PLAYER_EXPLORED_ZONES_SIZE)
                             continue;
                         uint32 mask = 1 << (uint32(area->exploreFlag) % 32);
                         if (GetPlayer()->GetUInt32Value(PLAYER_EXPLORED_ZONES_1 + playerIndexOffset) & mask)
{
                             matchFound = true;
                             break;
                         }
                     }
                     if (matchFound)
                         SetCriteriaProgress(achievementCriteria, 1);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetBankBagSlotCount());
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION:
                 {
                     // skip faction check only at loading
                     if (miscValue1 && miscValue1 != achievementCriteria->gain_reputation.factionID)
                         continue;
                     int32 reputation = GetPlayer()->GetReputationMgr().GetReputation(achievementCriteria->gain_reputation.factionID);
                     if (reputation > 0)
                         SetCriteriaProgress(achievementCriteria, reputation);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION:
                 {
                     SetCriteriaProgress(achievementCriteria, GetPlayer()->GetReputationMgr().GetExaltedFactionCount());
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP:
                 {
                     // skip for login case
                     if (!miscValue1)
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM:
                 {
                     // miscvalue1 = itemid
                     // miscvalue2 = itemSlot
                     if (!miscValue1)
                         continue;
                     if (miscValue2 != achievementCriteria->equip_epic_item.itemSlot)
                         continue;
                     // check item level and quality via achievement_criteria_data
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), 0, miscValue1))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT:
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT:
                 {
                     // miscvalue1 = itemid
                     // miscvalue2 = diced value
                     if (!miscValue1)
                         continue;
                     if (miscValue2 != achievementCriteria->roll_greed_on_loot.rollValue)
                         continue;
                     ItemTemplate const* pProto = sObjectMgr->GetItemTemplate(miscValue1);
                     if (!pProto)
                         continue;
                     // check item level via achievement_criteria_data
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), 0, pProto->ItemLevel))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE:
                 {
                     // miscvalue1 = emote
                     if (!miscValue1)
                         continue;
                     if (miscValue1 != achievementCriteria->do_emote.emoteID)
                         continue;
                     if (achievementCriteria->do_emote.count)
                     {
                         // those requirements couldn't be found in the dbc
                         AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                         if (!data || !data->Meets(GetPlayer(), unit))
                             continue;
                     }
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE:
             case ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE:
                 {
                     if (!miscValue1)
                         continue;
                     if (achievementCriteria->additionalRequirements[0].additionalRequirement_type == ACHIEVEMENT_CRITERIA_CONDITION_BG_MAP)
                     {
                         if (GetPlayer()->GetMapId() != achievementCriteria->additionalRequirements[0].additionalRequirement_value)
                             continue;
                         // map specific case (BG in fact) expected player targeted damage/heal
                         if (!unit || unit->GetTypeId() != TYPEID_PLAYER)
                             continue;
                     }
                     SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM:
                 // miscvalue1 = item_id
                 if (!miscValue1)
                     continue;
                 if (miscValue1 != achievementCriteria->equip_item.itemID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT:
                 // miscvalue1 = go entry
                 if (!miscValue1)
                     continue;
                 if (miscValue1 != achievementCriteria->use_gameobject.goEntry)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT:
                 if (!miscValue1)
                     continue;
                 if (miscValue1 != achievementCriteria->fish_in_gameobject.goEntry)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS:
                 {
                     if (miscValue1 && miscValue1 != achievementCriteria->learn_skillline_spell.skillLine)
                         continue;
                     uint32 spellCount = 0;
                     for (PlayerSpellMap::const_iterator spellIter = GetPlayer()->GetSpellMap().begin(); spellIter != GetPlayer()->GetSpellMap().end(); ++spellIter)
                     {
                         SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(spellIter->first);
                         for (SkillLineAbilityMap::const_iterator skillIter = bounds.first; skillIter != bounds.second; ++skillIter)
{
                             if (skillIter->second->SkillLine == achievementCriteria->learn_skillline_spell.skillLine)
{
                                 // xinef: do not add couter twice if by any chance skill is listed twice in dbc (eg. skill 777 and spell 22717)
                                 ++spellCount;
                                 break;
                             }
                         }
                     }
                     SetCriteriaProgress(achievementCriteria, spellCount);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL:
                 // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                 if (!miscValue1)
                     continue;
                 if (achievementCriteria->win_duel.duelCount)
                 {
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data)
                         continue;
                     if (!data->Meets(GetPlayer(), unit))
                         continue;
                 }
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetReputationMgr().GetReveredFactionCount());
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetReputationMgr().GetHonoredFactionCount());
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetReputationMgr().GetVisibleFactionCount());
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM:
             case ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM:
                 {
                     // AchievementMgr::UpdateAchievementCriteria might also be called on login - skip in this case
                     if (!miscValue1)
                         continue;
                     ItemTemplate const* proto = sObjectMgr->GetItemTemplate(miscValue1);
                     if (!proto || proto->Quality < ITEM_QUALITY_EPIC)
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE:
                 {
                     if (miscValue1 && miscValue1 != achievementCriteria->learn_skill_line.skillLine)
                         continue;
                     uint32 spellCount = 0;
                     for (PlayerSpellMap::const_iterator spellIter = GetPlayer()->GetSpellMap().begin(); spellIter != GetPlayer()->GetSpellMap().end(); ++spellIter)
                     {
                         SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(spellIter->first);
                         for (SkillLineAbilityMap::const_iterator skillIter = bounds.first; skillIter != bounds.second; ++skillIter)
{
                             if (skillIter->second->SkillLine == achievementCriteria->learn_skill_line.skillLine)
{
                                 // xinef: do not add couter twice if by any chance skill is listed twice in dbc (eg. skill 777 and spell 22717)
                                 ++spellCount;
                                 break;
                             }
                         }
                     }
                     SetCriteriaProgress(achievementCriteria, spellCount);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS));
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS:
                 if (!miscValue1 || miscValue1 != achievementCriteria->hk_class.classID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HK_RACE:
                 if (!miscValue1 || miscValue1 != achievementCriteria->hk_race.raceID)
                     continue;
                 SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED:
                 SetCriteriaProgress(achievementCriteria, GetPlayer()->GetMoney(), PROGRESS_HIGHEST);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS:
                 {
                     if (!miscValue1)
                     {
                         uint32 points = 0;
                         for (CompletedAchievementMap::iterator itr = m_completedAchievements.begin(); itr != m_completedAchievements.end(); ++itr)
                             if (AchievementEntry const* pAchievement = sAchievementStore.LookupEntry(itr->first))
                                 points += pAchievement->points;
                         SetCriteriaProgress(achievementCriteria, points, PROGRESS_SET);
                     }
                     else
                         SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE:
                 {
                     if (!miscValue1 || miscValue1 != achievementCriteria->bg_objective.objectiveId)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL:
             case ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL:
             case ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS:
                 {
                     // skip login update
                     if (!miscValue1)
                         continue;
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA:
                 {
                     if (!miscValue1 || miscValue1 != achievementCriteria->honorable_kill_at_area.areaID)
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING:
                 {
                     uint32 reqTeamType = achievementCriteria->highest_team_rating.teamtype;
                     if (miscValue1)
                     {
                         if (miscValue2 != reqTeamType)
                             continue;
                         SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_HIGHEST);
                     }
                     else    // login case
                     {
                         for (uint32 arena_slot = 0; arena_slot < MAX_ARENA_SLOT; ++arena_slot)
{
                             uint32 arenaTeamId = GetPlayer()->GetArenaTeamId(arena_slot);
                             if (!arenaTeamId)
                                 continue;
                             ArenaTeam* team = sArenaTeamMgr->GetArenaTeamById(arenaTeamId);
                             if (!team || team->GetType() != reqTeamType)
                                 continue;
                             SetCriteriaProgress(achievementCriteria, team->GetStats().Rating, PROGRESS_HIGHEST);
                             break;
                         }
                     }
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING:
                 {
                     uint32 reqTeamType = achievementCriteria->highest_personal_rating.teamtype;
                     if (miscValue1)
                     {
                         if (miscValue2 != reqTeamType)
                             continue;
                         SetCriteriaProgress(achievementCriteria, miscValue1, PROGRESS_HIGHEST);
                     }
                     else    // login case
                     {
                         for (uint32 arena_slot = 0; arena_slot < MAX_ARENA_SLOT; ++arena_slot)
{
                             uint32 arenaTeamId = GetPlayer()->GetArenaTeamId(arena_slot);
                             if (!arenaTeamId)
                                 continue;
                             ArenaTeam* team = sArenaTeamMgr->GetArenaTeamById(arenaTeamId);
                             if (!team || team->GetType() != reqTeamType)
                                 continue;
                             if (ArenaTeamMember const* member = team->GetMember(GetPlayer()->GetGUID()))
{
                                 SetCriteriaProgress(achievementCriteria, member->PersonalRating, PROGRESS_HIGHEST);
                                 break;
                             }
                         }
                     }
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN:
                 {
                     // This criteria is only called directly after login - with expected miscvalue1 == 1
                     if (!miscValue1)
                         continue;
                     // They have no proper requirements in dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), unit))
                         continue;
                     SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA:
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA: // This also behaves like ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA
                 {
                     // those requirements couldn't be found in the dbc
                     AchievementCriteriaDataSet const* data = sAchievementMgr->GetCriteriaDataSet(achievementCriteria);
                     if (!data || !data->Meets(GetPlayer(), nullptr))
                         continue;
                     // Check map id requirement
                     if (miscValue1 == achievementCriteria->win_arena.mapID)
                         SetCriteriaProgress(achievementCriteria, 1, PROGRESS_ACCUMULATE);
                     break;
                 }
             // std case: not exist in DBC, not triggered in code as result
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_POWER:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_STAT:
             case ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_RATING:
                 break;
             // FIXME: not triggered in code as result, need to implement
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_RAID:
             case ACHIEVEMENT_CRITERIA_TYPE_OWN_RANK:
             case ACHIEVEMENT_CRITERIA_TYPE_TOTAL:
                 break;                                   // Not implemented yet :(
         }
         if (IsCompletedCriteria(achievementCriteria, achievement))
             CompletedCriteriaFor(achievement);
         // check again the completeness for SUMM and REQ COUNT achievements,
         // as they don't depend on the completed criteria but on the sum of the progress of each individual criteria
         if (achievement->flags & ACHIEVEMENT_FLAG_SUMM)
             if (IsCompletedAchievement(achievement))
                 CompletedAchievement(achievement);
         if (AchievementEntryList const* achRefList = sAchievementMgr->GetAchievementByReferencedId(achievement->ID))
             for (AchievementEntryList::const_iterator itr = achRefList->begin(); itr != achRefList->end(); ++itr)
                 if (IsCompletedAchievement(*itr))
                     CompletedAchievement(*itr);
     }
 }
References ACHIEVEMENT_CRITERIA_CONDITION_BG_MAP, ACHIEVEMENT_CRITERIA_CONDITION_NO_LOSE, ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_RAID, ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_DEATH, ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP, ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON, ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS, ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN, ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEAL_CASTED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALING_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_DEALT, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_POWER, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_STAT, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING, ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS, ACHIEVEMENT_CRITERIA_TYPE_HK_RACE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL, ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM, ACHIEVEMENT_CRITERIA_TYPE_OWN_RANK, ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA, ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED, ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_TOTAL, ACHIEVEMENT_CRITERIA_TYPE_TOTAL_DAMAGE_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_TOTAL_HEALING_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS, ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP, ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, ACHIEVEMENT_FLAG_SUMM, achievIdByArenaSlot, achievIdForDungeon, AchievementCriteriaEntry::additionalRequirement_type, AchievementCriteriaEntry::additionalRequirement_value, AchievementCriteriaEntry::additionalRequirements, WorldMapOverlayEntry::areatableID, AchievementCriteriaEntry::be_spell_target, AchievementCriteriaEntry::bg_objective, CanUpdateCriteria(), AchievementCriteriaEntry::cast_spell, CATEGORY_CHILDRENS_WEEK, AchievementEntry::categoryId, AchievementCriteriaEntry::complete_achievement, AchievementCriteriaEntry::complete_battleground, AchievementCriteriaEntry::complete_quest, AchievementCriteriaEntry::complete_quests_in_zone, CompletedAchievement(), CompletedCriteriaFor(), CriteriaProgress::date, DAY, AchievementCriteriaEntry::death_at_map, AchievementCriteriaEntry::death_from, AchievementCriteriaEntry::death_in_dungeon, AchievementCriteriaEntry::do_emote, DUNGEON_DIFFICULTY_NORMAL, AchievementCriteriaEntry::equip_epic_item, AchievementCriteriaEntry::equip_item, AchievementCriteriaEntry::explore_area, AreaTableEntry::exploreFlag, AchievementCriteriaEntry::fish_in_gameobject, AchievementEntry::flags, AchievementCriteriaEntry::gain_reputation, Player::GetArenaTeamId(), Battleground::GetArenaType(), Player::GetBattleground(), GetCriteriaProgress(), WorldObject::GetMap(), InstanceMap::GetMaxPlayers(), ArenaTeam::GetMember(), GetPlayer(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), Player::getRewardedQuests(), ArenaTeam::GetSlotByType(), Player::GetSpellMap(), ArenaTeam::GetStats(), ArenaTeam::GetType(), Object::GetTypeId(), Object::GetUInt32Value(), Quest::GetZoneOrSort(), HasAchieved(), AchievementCriteriaEntry::highest_personal_rating, AchievementCriteriaEntry::highest_team_rating, AchievementCriteriaEntry::hk_class, AchievementCriteriaEntry::hk_race, AchievementCriteriaEntry::honorable_kill_at_area, AchievementEntry::ID, Battleground::isArena(), IsCompletedAchievement(), IsCompletedCriteria(), Map::IsDungeon(), Player::IsGameMaster(), Object::IsInWorld(), Map::IsRaid(), ITEM_QUALITY_EPIC, ItemTemplate::ItemLevel, AchievementCriteriaEntry::kill_creature, AchievementCriteriaEntry::killed_by_creature, AchievementCriteriaEntry::learn_skill_level, AchievementCriteriaEntry::learn_skill_line, AchievementCriteriaEntry::learn_skillline_spell, AchievementCriteriaEntry::learn_spell, LOG_DEBUG, AchievementCriteriaEntry::loot_type, m_completedAchievements, m_player, MAX_ARENA_SLOT, MAX_WORLD_MAP_OVERLAY_AREA_IDX, AchievementCriteriaDataSet::Meets(), AchievementCriteriaEntry::own_item, AchievementCriteriaEntry::PersonalRating, PLAYER_EXPLORED_ZONES_1, PLAYER_EXPLORED_ZONES_SIZE, PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, PROGRESS_ACCUMULATE, PROGRESS_HIGHEST, PROGRESS_RESET, PROGRESS_SET, ItemTemplate::Quality, ArenaTeamStats::Rating, AchievementCriteriaEntry::reach_skill_level, AchievementCriteriaEntry::referredAchievement, AchievementCriteriaEntry::roll_greed_on_loot, sAchievementMgr, sAchievementStore, sAreaTableStore, sArenaTeamMgr, SetCriteriaProgress(), sMapMgr, sObjectMgr, sScriptMgr, sSpellMgr, sWorld, sWorldMapOverlayStore, Map::ToInstanceMap(), TYPEID_PLAYER, AchievementCriteriaEntry::use_gameobject, AchievementCriteriaEntry::use_item, AchievementCriteriaEntry::win_arena, AchievementCriteriaEntry::win_bg, and AchievementCriteriaEntry::win_duel.
Referenced by CheckAllAchievementCriteria(), CompletedAchievement(), and Player::UpdateAchievementCriteria().
UpdateTimedAchievements()
void AchievementMgr::UpdateTimedAchievements (uint32 timeDiff)
Definition at line 2115 of file AchievementMgr.cpp.
 {
     if (!m_timedAchievements.empty())
     {
         for (TimedAchievementMap::iterator itr = m_timedAchievements.begin(); itr != m_timedAchievements.end();)
         {
             // Time is up, remove timer and reset progress
             if (itr->second <= timeDiff)
             {
                 AchievementCriteriaEntry const* entry = sAchievementCriteriaStore.LookupEntry(itr->first);
                 RemoveCriteriaProgress(entry);
                 m_timedAchievements.erase(itr++);
             }
             else
             {
                 itr->second -= timeDiff;
                 ++itr;
             }
         }
     }
 }
References m_timedAchievements, RemoveCriteriaProgress(), and sAchievementCriteriaStore.
Referenced by Player::Update().
Member Data Documentation
m_completedAchievements
CompletedAchievementMap AchievementMgr::m_completedAchievements private
Definition at line 311 of file AchievementMgr.h.
Referenced by BuildAllDataPacket(), CompletedAchievement(), HasAchieved(), LoadFromDB(), Reset(), SaveToDB(), SendAllAchievementData(), SendRespondInspectAchievements(), and UpdateAchievementCriteria().
m_criteriaProgress
CriteriaProgressMap AchievementMgr::m_criteriaProgress private
Definition at line 310 of file AchievementMgr.h.
Referenced by BuildAllDataPacket(), GetCriteriaProgress(), LoadFromDB(), RemoveCriteriaProgress(), Reset(), SaveToDB(), SendAllAchievementData(), SendRespondInspectAchievements(), and SetCriteriaProgress().
m_player
Player* AchievementMgr::m_player private
Definition at line 309 of file AchievementMgr.h.
Referenced by AchievementMgr(), CompletedAchievement(), GetPlayer(), RemoveCriteriaProgress(), Reset(), ResetAchievementCriteria(), SetCriteriaProgress(), and UpdateAchievementCriteria().
m_timedAchievements
TimedAchievementMap AchievementMgr::m_timedAchievements private
Definition at line 313 of file AchievementMgr.h.
Referenced by RemoveTimedAchievement(), SetCriteriaProgress(), StartTimedAchievement(), and UpdateTimedAchievements().
The documentation for this class was generated from the following files:
src/server/game/Achievements/AchievementMgr.h
src/server/game/Achievements/AchievementMgr.cpp