Azerotcore-wotlk: deps/jemalloc/src/jemalloc_cpp.cpp File Reference
jemalloc_cpp.cpp File Reference
#include <mutex>
#include <new>
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
Macros
#define JEMALLOC_CPP_CPP_
Functions
void * operator new (std::size_t size)
void * operator new[] (std::size_t size)
void * operator new (std::size_t size, const std::nothrow_t &) noexcept
void * operator new[] (std::size_t size, const std::nothrow_t &) noexcept
void operator delete (void *ptr) noexcept
void operator delete[] (void *ptr) noexcept
void operator delete (void *ptr, const std::nothrow_t &) noexcept
void operator delete[] (void *ptr, const std::nothrow_t &) noexcept
static JEMALLOC_NOINLINE void * handleOOM (std::size_t size, bool nothrow)
template<bool IsNoExcept>
JEMALLOC_ALWAYS_INLINE void * newImpl (std::size_t size) noexcept(IsNoExcept)
Macro Definition Documentation
JEMALLOC_CPP_CPP_
#define JEMALLOC_CPP_CPP_
Definition at line 4 of file jemalloc_cpp.cpp.
Function Documentation
handleOOM()
static JEMALLOC_NOINLINE void* handleOOM (std::size_t size, bool nothrow) static
Definition at line 44 of file jemalloc_cpp.cpp.
{
     void *ptr = nullptr;
     while (ptr == nullptr) {
         std::new_handler handler;
         // GCC-4.8 and clang 4.0 do not have std::get_new_handler.
         {
             static std::mutex mtx;
             std::lock_guard<std::mutex> lock(mtx);
             handler = std::set_new_handler(nullptr);
             std::set_new_handler(handler);
         }
         if (handler == nullptr)
             break;
         try {
             handler();
         } catch (const std::bad_alloc &) {
             break;
         }
         ptr = je_malloc(size);
     }
     if (ptr == nullptr && !nothrow)
         std::__throw_bad_alloc();
     return ptr;
 }
References je_malloc(), and ptr().
Referenced by newImpl().
newImpl()
template<bool IsNoExcept> JEMALLOC_ALWAYS_INLINE void* newImpl (std::size_t size) noexcept
Definition at line 77 of file jemalloc_cpp.cpp.
{
     void *ptr = je_malloc(size);
     if (likely(ptr != nullptr))
         return ptr;
     return handleOOM(size, IsNoExcept);
 }
References handleOOM(), je_malloc(), likely, and ptr().
operator delete() [1/2]
void operator delete (void * ptr) noexcept
Definition at line 106 of file jemalloc_cpp.cpp.
{
     je_free(ptr);
 }
References je_free, and ptr().
operator delete() [2/2]
void operator delete (void * ptr, const std::nothrow_t &) noexcept
Definition at line 116 of file jemalloc_cpp.cpp.
{
     je_free(ptr);
 }
References je_free, and ptr().
operator delete[]() [1/2]
void operator delete[] (void * ptr) noexcept
Definition at line 111 of file jemalloc_cpp.cpp.
{
     je_free(ptr);
 }
References je_free, and ptr().
operator delete[]() [2/2]
void operator delete[] (void * ptr, const std::nothrow_t &) noexcept
Definition at line 120 of file jemalloc_cpp.cpp.
{
     je_free(ptr);
 }
References je_free, and ptr().
operator new() [1/2]
void * operator new (std::size_t size)
Definition at line 86 of file jemalloc_cpp.cpp.
{
     return newImpl<false>(size);
 }
operator new() [2/2]
void * operator new (std::size_t size, const std::nothrow_t &) noexcept
Definition at line 96 of file jemalloc_cpp.cpp.
{
     return newImpl<true>(size);
 }
operator new[]() [1/2]
void * operator new[] (std::size_t size)
Definition at line 91 of file jemalloc_cpp.cpp.
{
     return newImpl<false>(size);
 }
operator new[]() [2/2]
void * operator new[] (std::size_t size, const std::nothrow_t &) noexcept
Definition at line 101 of file jemalloc_cpp.cpp.
{
     return newImpl<true>(size);
 }