Azerotcore-wotlk: ResultSet Class Reference
ResultSet Class Reference
#include <QueryResult.h>
Public Member Functions
ResultSet (MySQLResult *result, MySQLField *fields, uint64 rowCount, uint32 fieldCount)
~ResultSet ()
bool NextRow ()
uint64 GetRowCount () const
uint32 GetFieldCount () const
std::string GetFieldName (uint32 index) const
Field * Fetch () const
Field const & operator[] (std::size_t index) const
Protected Attributes
std::vector< QueryResultFieldMetadata > _fieldMetadata
uint64 _rowCount
Field * _currentRow
uint32 _fieldCount
Private Member Functions
void CleanUp ()
ResultSet (ResultSet const &right)=delete
ResultSet & operator= (ResultSet const &right)=delete
Private Attributes
MySQLResult * _result
MySQLField * _fields
Detailed Description
Definition at line 25 of file QueryResult.h.
Constructor & Destructor Documentation
ResultSet() [1/2]
ResultSet::ResultSet (MySQLResult * result, MySQLField * fields, uint64 rowCount, uint32 fieldCount)
Definition at line 167 of file QueryResult.cpp.
                                                                                                 :
 _rowCount(rowCount),
 _fieldCount(fieldCount),
 _result(result),
 _fields(fields)
 {
     _fieldMetadata.resize(_fieldCount);
     _currentRow = new Field[_fieldCount];
     for (uint32 i = 0; i < _fieldCount; i++)
     {
         InitializeDatabaseFieldMetadata(&_fieldMetadata[i], &_fields[i], i);
         _currentRow[i].SetMetadata(&_fieldMetadata[i]);
     }
 }
References _currentRow, _fieldCount, _fieldMetadata, _fields, anonymous_namespace{QueryResult.cpp}::InitializeDatabaseFieldMetadata(), and Field::SetMetadata().
~ResultSet()
ResultSet::~ResultSet ()
Definition at line 314 of file QueryResult.cpp.
 {
     CleanUp();
 }
References CleanUp().
ResultSet() [2/2]
ResultSet::ResultSet (ResultSet const & right) private delete
Member Function Documentation
CleanUp()
void ResultSet::CleanUp () private
Definition at line 379 of file QueryResult.cpp.
 {
     if (_currentRow)
     {
         delete [] _currentRow;
         _currentRow = nullptr;
     }
     if (_result)
     {
         mysql_free_result(_result);
         _result = nullptr;
     }
 }
References _currentRow, _result, and mysql_free_result().
Referenced by NextRow(), and ~ResultSet().
Fetch()
Field* ResultSet::Fetch () const inline
Definition at line 36 of file QueryResult.h.
 { return _currentRow; }
GetFieldCount()
uint32 ResultSet::GetFieldCount () const inline
Definition at line 33 of file QueryResult.h.
 { return _fieldCount; }
GetFieldName()
std::string ResultSet::GetFieldName (uint32 index) const
Definition at line 352 of file QueryResult.cpp.
 {
     ASSERT(index < _fieldCount);
     return _fields[index].name;
 }
References _fieldCount, _fields, ASSERT, index, and st_mysql_field::name.
GetRowCount()
uint64 ResultSet::GetRowCount () const inline
Definition at line 32 of file QueryResult.h.
 { return _rowCount; }
NextRow()
bool ResultSet::NextRow ()
Definition at line 324 of file QueryResult.cpp.
 {
     MYSQL_ROW row;
     if (!_result)
         return false;
     row = mysql_fetch_row(_result);
     if (!row)
     {
         CleanUp();
         return false;
     }
     unsigned long* lengths = mysql_fetch_lengths(_result);
     if (!lengths)
     {
         LOG_WARN("sql.sql", "%s:mysql_fetch_lengths, cannot retrieve value lengths. Error %s.", __FUNCTION__, mysql_error(_result->handle));
         CleanUp();
         return false;
     }
     for (uint32 i = 0; i < _fieldCount; i++)
         _currentRow[i].SetStructuredValue(row[i], lengths[i]);
     return true;
 }
References _currentRow, _fieldCount, _result, CleanUp(), st_mysql_res::handle, LOG_WARN, mysql_error(), mysql_fetch_lengths(), and mysql_fetch_row().
operator=()
ResultSet& ResultSet::operator= (ResultSet const & right) private delete
operator[]()
Field const & ResultSet::operator[] (std::size_t index) const
Definition at line 394 of file QueryResult.cpp.
 {
     ASSERT(index < _fieldCount);
     return _currentRow[index];
 }
References _currentRow, _fieldCount, ASSERT, and index.
Member Data Documentation
_currentRow
Field* ResultSet::_currentRow protected
Definition at line 42 of file QueryResult.h.
Referenced by CleanUp(), NextRow(), operator[](), and ResultSet().
_fieldCount
uint32 ResultSet::_fieldCount protected
Definition at line 43 of file QueryResult.h.
Referenced by GetFieldName(), NextRow(), operator[](), and ResultSet().
_fieldMetadata
std::vector<QueryResultFieldMetadata> ResultSet::_fieldMetadata protected
Definition at line 40 of file QueryResult.h.
Referenced by ResultSet().
_fields
MySQLField* ResultSet::_fields private
Definition at line 48 of file QueryResult.h.
Referenced by GetFieldName(), and ResultSet().
_result
MySQLResult* ResultSet::_result private
Definition at line 47 of file QueryResult.h.
Referenced by CleanUp(), and NextRow().
_rowCount
uint64 ResultSet::_rowCount protected
Definition at line 41 of file QueryResult.h.
The documentation for this class was generated from the following files:
src/server/database/Database/QueryResult.h
src/server/database/Database/QueryResult.cpp