Azerotcore-wotlk: GossipMenu Class Reference
GossipMenu Class Reference
#include <GossipDef.h>
Public Member Functions
GossipMenu ()
~GossipMenu ()
void AddMenuItem (int32 menuItemId, uint8 icon, std::string const &message, uint32 sender, uint32 action, std::string const &boxMessage, uint32 boxMoney, bool coded=false)
void SetMenuId (uint32 menu_id)
uint32 GetMenuId () const
void SetLocale (LocaleConstant locale)
LocaleConstant GetLocale () const
uint32 GetMenuItemCount () const
bool Empty () const
GossipMenuItem const * GetItem (uint32 id) const
GossipMenuItemData const * GetItemData (uint32 indexId) const
GossipMenuItemContainer const & GetMenuItems () const
AddMenuItem
Adds a localized gossip menu item from db by menu id and menu item id.
Parameters
menuId Gossip menu id.
menuItemId Gossip menu item id.
sender Identifier of the current menu.
action Custom action given to OnGossipHello.
void AddMenuItem (uint32 menuId, uint32 menuItemId, uint32 sender, uint32 action)
void AddGossipMenuItemData (uint32 menuItemId, uint32 gossipActionMenuId, uint32 gossipActionPoi)
uint32 GetMenuItemSender (uint32 menuItemId) const
uint32 GetMenuItemAction (uint32 menuItemId) const
bool IsMenuItemCoded (uint32 menuItemId) const
void ClearMenu ()
Private Attributes
GossipMenuItemContainer _menuItems
GossipMenuItemDataContainer _menuItemData
uint32 _menuId
LocaleConstant _locale
Detailed Description
Definition at line 160 of file GossipDef.h.
Constructor & Destructor Documentation
GossipMenu()
GossipMenu::GossipMenu ()
Definition at line 27 of file GossipDef.cpp.
 {
     _menuId = 0;
     _locale = DEFAULT_LOCALE;
 }
References _locale, _menuId, and DEFAULT_LOCALE.
~GossipMenu()
GossipMenu::~GossipMenu ()
Definition at line 33 of file GossipDef.cpp.
 {
     ClearMenu();
 }
References ClearMenu().
Member Function Documentation
AddGossipMenuItemData()
void GossipMenu::AddGossipMenuItemData (uint32 menuItemId, uint32 gossipActionMenuId, uint32 gossipActionPoi)
Definition at line 132 of file GossipDef.cpp.
 {
     GossipMenuItemData& itemData = _menuItemData[menuItemId];
     itemData.GossipActionMenuId  = gossipActionMenuId;
     itemData.GossipActionPoi     = gossipActionPoi;
 }
References _menuItemData, GossipMenuItemData::GossipActionMenuId, and GossipMenuItemData::GossipActionPoi.
Referenced by Player::PrepareGossipMenu().
AddMenuItem() [1/2]
void GossipMenu::AddMenuItem (int32 menuItemId, uint8 icon, std::string const & message, uint32 sender, uint32 action, std::string const & boxMessage, uint32 boxMoney, bool coded = false)
Definition at line 38 of file GossipDef.cpp.
 {
     ASSERT(_menuItems.size() <= GOSSIP_MAX_MENU_ITEMS);
     // Find a free new id - script case
     if (menuItemId == -1)
     {
         menuItemId = 0;
         if (!_menuItems.empty())
         {
             for (GossipMenuItemContainer::const_iterator itr = _menuItems.begin(); itr != _menuItems.end(); ++itr)
             {
                 if (int32(itr->first) > menuItemId)
                     break;
                 menuItemId = itr->first + 1;
             }
         }
     }
     GossipMenuItem& menuItem = _menuItems[menuItemId];
     menuItem.MenuItemIcon    = icon;
     menuItem.Message         = message;
     menuItem.IsCoded         = coded;
     menuItem.Sender          = sender;
     menuItem.OptionType      = action;
     menuItem.BoxMessage      = boxMessage;
     menuItem.BoxMoney        = boxMoney;
 }
References _menuItems, ASSERT, GossipMenuItem::BoxMessage, GossipMenuItem::BoxMoney, GOSSIP_MAX_MENU_ITEMS, GossipMenuItem::IsCoded, GossipMenuItem::MenuItemIcon, GossipMenuItem::Message, message(), GossipMenuItem::OptionType, and GossipMenuItem::Sender.
Referenced by AddGossipItemFor(), AddMenuItem(), and Player::PrepareGossipMenu().
AddMenuItem() [2/2]
void GossipMenu::AddMenuItem (uint32 menuId, uint32 menuItemId, uint32 sender, uint32 action)
Find items for given menu id.
Return if there are none.
Iterate over each of them.
Find the one with the given menu item id.
Store texts for localization.
OptionText
BoxText
Check need of localization.
Find localizations from database.
Find localizations from database.
Add menu item with existing method. Menu item id -1 is also used in ADD_GOSSIP_ITEM macro.
Definition at line 77 of file GossipDef.cpp.
 {
     GossipMenuItemsMapBounds bounds = sObjectMgr->GetGossipMenuItemsMapBounds(menuId);
     if (bounds.first == bounds.second)
         return;
     for (GossipMenuItemsContainer::const_iterator itr = bounds.first; itr != bounds.second; ++itr)
     {
         if (itr->second.OptionID != menuItemId)
             continue;
         std::string strOptionText, strBoxText;
         BroadcastText const* optionBroadcastText = sObjectMgr->GetBroadcastText(itr->second.OptionBroadcastTextID);
         BroadcastText const* boxBroadcastText = sObjectMgr->GetBroadcastText(itr->second.BoxBroadcastTextID);
         if (optionBroadcastText)
             ObjectMgr::GetLocaleString(optionBroadcastText->MaleText, GetLocale(), strOptionText);
         else
             strOptionText = itr->second.OptionText;
         if (boxBroadcastText)
             ObjectMgr::GetLocaleString(boxBroadcastText->MaleText, GetLocale(), strBoxText);
         else
             strBoxText = itr->second.BoxText;
         if (GetLocale() != DEFAULT_LOCALE)
         {
             if (!optionBroadcastText)
             {
                 if (GossipMenuItemsLocale const* gossipMenuLocale = sObjectMgr->GetGossipMenuItemsLocale(MAKE_PAIR32(menuId, menuItemId)))
                     ObjectMgr::GetLocaleString(gossipMenuLocale->OptionText, GetLocale(), strOptionText);
             }
             if (!boxBroadcastText)
             {
                 if (GossipMenuItemsLocale const* gossipMenuLocale = sObjectMgr->GetGossipMenuItemsLocale(MAKE_PAIR32(menuId, menuItemId)))
                     ObjectMgr::GetLocaleString(gossipMenuLocale->BoxText, GetLocale(), strBoxText);
             }
         }
         AddMenuItem(-1, itr->second.OptionIcon, strOptionText, sender, action, strBoxText, itr->second.BoxMoney, itr->second.BoxCoded);
     }
 }
References AddMenuItem(), DEFAULT_LOCALE, GetLocale(), ObjectMgr::GetLocaleString(), MAKE_PAIR32(), BroadcastText::MaleText, and sObjectMgr.
ClearMenu()
void GossipMenu::ClearMenu ()
Definition at line 167 of file GossipDef.cpp.
 {
     _menuItems.clear();
     _menuItemData.clear();
 }
References _menuItemData, and _menuItems.
Referenced by PlayerMenu::ClearMenus(), and ~GossipMenu().
Empty()
bool GossipMenu::Empty () const inline
Definition at line 181 of file GossipDef.h.
     {
         return _menuItems.empty();
     }
References _menuItems.
Referenced by PlayerMenu::Empty().
GetItem()
GossipMenuItem const* GossipMenu::GetItem (uint32 id) const inline
Definition at line 186 of file GossipDef.h.
     {
         GossipMenuItemContainer::const_iterator itr = _menuItems.find(id);
         if (itr != _menuItems.end())
             return &itr->second;
         return nullptr;
     }
References _menuItems.
Referenced by Player::OnGossipSelect().
GetItemData()
GossipMenuItemData const* GossipMenu::GetItemData (uint32 indexId) const inline
Definition at line 195 of file GossipDef.h.
     {
         GossipMenuItemDataContainer::const_iterator itr = _menuItemData.find(indexId);
         if (itr != _menuItemData.end())
             return &itr->second;
         return nullptr;
     }
References _menuItemData.
Referenced by npc_thrall_old_hillsbrad::OnGossipSelect(), and Player::OnGossipSelect().
GetLocale()
LocaleConstant GossipMenu::GetLocale () const inline
Definition at line 172 of file GossipDef.h.
 { return _locale; }
References _locale.
Referenced by AddMenuItem().
GetMenuId()
uint32 GossipMenu::GetMenuId () const inline
Definition at line 170 of file GossipDef.h.
 { return _menuId; }
References _menuId.
Referenced by WorldSession::HandleGossipSelectOptionOpcode(), npc_cos_chromie_start::OnGossipSelect(), npc_cos_chromie_middle::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), Player::OnGossipSelect(), PlayerMenu::SendGossipMenu(), and Player::SendPreparedGossip().
GetMenuItemAction()
uint32 GossipMenu::GetMenuItemAction (uint32 menuItemId) const
Definition at line 149 of file GossipDef.cpp.
 {
     GossipMenuItemContainer::const_iterator itr = _menuItems.find(menuItemId);
     if (itr == _menuItems.end())
         return 0;
     return itr->second.OptionType;
 }
References _menuItems.
Referenced by PlayerMenu::GetGossipOptionAction().
GetMenuItemCount()
uint32 GossipMenu::GetMenuItemCount () const inline
Definition at line 176 of file GossipDef.h.
     {
         return _menuItems.size();
     }
References _menuItems.
Referenced by PlayerMenu::SendGossipMenu().
GetMenuItems()
GossipMenuItemContainer const& GossipMenu::GetMenuItems () const inline
Definition at line 210 of file GossipDef.h.
     {
         return _menuItems;
     }
References _menuItems.
Referenced by PlayerMenu::SendGossipMenu().
GetMenuItemSender()
uint32 GossipMenu::GetMenuItemSender (uint32 menuItemId) const
Definition at line 140 of file GossipDef.cpp.
 {
     GossipMenuItemContainer::const_iterator itr = _menuItems.find(menuItemId);
     if (itr == _menuItems.end())
         return 0;
     return itr->second.Sender;
 }
References _menuItems.
Referenced by PlayerMenu::GetGossipOptionSender().
IsMenuItemCoded()
bool GossipMenu::IsMenuItemCoded (uint32 menuItemId) const
Definition at line 158 of file GossipDef.cpp.
 {
     GossipMenuItemContainer::const_iterator itr = _menuItems.find(menuItemId);
     if (itr == _menuItems.end())
         return false;
     return itr->second.IsCoded;
 }
References _menuItems.
Referenced by PlayerMenu::IsGossipOptionCoded().
SetLocale()
void GossipMenu::SetLocale (LocaleConstant locale) inline
Definition at line 171 of file GossipDef.h.
 { _locale = locale; }
References _locale.
Referenced by PlayerMenu::PlayerMenu().
SetMenuId()
void GossipMenu::SetMenuId (uint32 menu_id) inline
Definition at line 169 of file GossipDef.h.
 { _menuId = menu_id; }
References _menuId.
Referenced by Player::PrepareGossipMenu().
Member Data Documentation
_locale
LocaleConstant GossipMenu::_locale private
Definition at line 219 of file GossipDef.h.
Referenced by GetLocale(), GossipMenu(), and SetLocale().
_menuId
uint32 GossipMenu::_menuId private
Definition at line 218 of file GossipDef.h.
Referenced by GetMenuId(), GossipMenu(), and SetMenuId().
_menuItemData
GossipMenuItemDataContainer GossipMenu::_menuItemData private
Definition at line 217 of file GossipDef.h.
Referenced by AddGossipMenuItemData(), ClearMenu(), and GetItemData().
_menuItems
GossipMenuItemContainer GossipMenu::_menuItems private
Definition at line 216 of file GossipDef.h.
Referenced by AddMenuItem(), ClearMenu(), Empty(), GetItem(), GetMenuItemAction(), GetMenuItemCount(), GetMenuItems(), GetMenuItemSender(), and IsMenuItemCoded().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/GossipDef.h
src/server/game/Entities/Creature/GossipDef.cpp