Azerotcore-wotlk: SpellScript::TargetHook Class Reference
SpellScript::TargetHook Class Reference
#include <SpellScript.h>
Public Member Functions
TargetHook (uint8 _effectIndex, uint16 _targetType, bool _area, bool _dest)
bool CheckEffect (SpellInfo const *spellInfo, uint8 effIndex) override
std::string ToString ()
uint16 GetTarget () const
Public Member Functions inherited from _SpellScript::EffectHook
EffectHook (uint8 _effIndex)
virtual ~EffectHook ()
uint8 GetAffectedEffectsMask (SpellInfo const *spellEntry)
bool IsEffectAffected (SpellInfo const *spellEntry, uint8 effIndex)
std::string EffIndexToString ()
Protected Attributes
uint16 targetType
bool area
bool dest
Protected Attributes inherited from _SpellScript::EffectHook
uint8 effIndex
Detailed Description
Definition at line 246 of file SpellScript.h.
Constructor & Destructor Documentation
TargetHook()
SpellScript::TargetHook::TargetHook (uint8 _effectIndex, uint16 _targetType, bool _area, bool _dest)
Definition at line 227 of file SpellScript.cpp.
     : _SpellScript::EffectHook(_effectIndex), targetType(_targetType), area(_area), dest(_dest) { }
Member Function Documentation
CheckEffect()
bool SpellScript::TargetHook::CheckEffect (SpellInfo const * spellInfo, uint8 effIndex) override virtual
Implements _SpellScript::EffectHook.
Definition at line 237 of file SpellScript.cpp.
 {
     if (!targetType)
         return false;
     if (spellEntry->Effects[effIndex].TargetA.GetTarget() != targetType &&
             spellEntry->Effects[effIndex].TargetB.GetTarget() != targetType)
         return false;
     SpellImplicitTargetInfo targetInfo(targetType);
     switch (targetInfo.GetSelectionCategory())
     {
         case TARGET_SELECT_CATEGORY_CHANNEL: // SINGLE
             return !area;
         case TARGET_SELECT_CATEGORY_NEARBY: // BOTH
             return true;
         case TARGET_SELECT_CATEGORY_CONE: // AREA
         case TARGET_SELECT_CATEGORY_AREA: // AREA
             return area;
         case TARGET_SELECT_CATEGORY_DEFAULT:
             switch (targetInfo.GetObjectType())
             {
                 case TARGET_OBJECT_TYPE_SRC: // EMPTY
                     return false;
                 case TARGET_OBJECT_TYPE_DEST: // DEST
                     return dest;
                 default:
                     switch (targetInfo.GetReferenceType())
                     {
                         case TARGET_REFERENCE_TYPE_CASTER: // SINGLE
                             return !area;
                         case TARGET_REFERENCE_TYPE_TARGET: // BOTH
                             return true;
                         default:
                             break;
                     }
                     break;
             }
             break;
         default:
             break;
     }
     return false;
 }
References SpellInfo::Effects, SpellImplicitTargetInfo::GetObjectType(), SpellImplicitTargetInfo::GetReferenceType(), SpellImplicitTargetInfo::GetSelectionCategory(), TARGET_OBJECT_TYPE_DEST, TARGET_OBJECT_TYPE_SRC, TARGET_REFERENCE_TYPE_CASTER, TARGET_REFERENCE_TYPE_TARGET, TARGET_SELECT_CATEGORY_AREA, TARGET_SELECT_CATEGORY_CHANNEL, TARGET_SELECT_CATEGORY_CONE, TARGET_SELECT_CATEGORY_DEFAULT, and TARGET_SELECT_CATEGORY_NEARBY.
GetTarget()
uint16 SpellScript::TargetHook::GetTarget () const inline
Definition at line 252 of file SpellScript.h.
 { return targetType; }
References targetType.
ToString()
std::string SpellScript::TargetHook::ToString ()
Definition at line 230 of file SpellScript.cpp.
 {
     std::ostringstream oss;
     oss << "Index: " << EffIndexToString() << " Target: " << targetType;
     return oss.str();
 }
Member Data Documentation
area
bool SpellScript::TargetHook::area protected
Definition at line 255 of file SpellScript.h.
dest
bool SpellScript::TargetHook::dest protected
Definition at line 256 of file SpellScript.h.
targetType
uint16 SpellScript::TargetHook::targetType protected
Definition at line 254 of file SpellScript.h.
Referenced by GetTarget().
The documentation for this class was generated from the following files:
src/server/game/Spells/SpellScript.h
src/server/game/Spells/SpellScript.cpp