Azerotcore-wotlk: UpdateData Class Reference
UpdateData Class Reference
#include <UpdateData.h>
Public Member Functions
UpdateData ()
void AddOutOfRangeGUID (ObjectGuid guid)
void AddUpdateBlock (const ByteBuffer &block)
void AddUpdateBlock (const UpdateData &block)
bool BuildPacket (WorldPacket *packet)
bool HasData () const
void Clear ()
Protected Member Functions
void Compress (void *dst, uint32 *dst_size, void *src, int src_size)
Protected Attributes
uint32 m_blockCount
GuidVector m_outOfRangeGUIDs
ByteBuffer m_data
Detailed Description
Definition at line 51 of file UpdateData.h.
Constructor & Destructor Documentation
UpdateData()
UpdateData::UpdateData ()
Definition at line 27 of file UpdateData.cpp.
                        : m_blockCount(0)
 {
     m_outOfRangeGUIDs.reserve(15);
 }
References m_outOfRangeGUIDs.
Member Function Documentation
AddOutOfRangeGUID()
void UpdateData::AddOutOfRangeGUID (ObjectGuid guid)
Definition at line 32 of file UpdateData.cpp.
 {
     m_outOfRangeGUIDs.push_back(guid);
 }
References m_outOfRangeGUIDs.
Referenced by Map::SendRemoveTransports(), and Acore::VisibleNotifier::SendToSelf().
AddUpdateBlock() [1/2]
void UpdateData::AddUpdateBlock (const ByteBuffer & block)
Definition at line 37 of file UpdateData.cpp.
 {
     m_data.append(block);
     ++m_blockCount;
 }
References ByteBuffer::append(), m_blockCount, and m_data.
AddUpdateBlock() [2/2]
void UpdateData::AddUpdateBlock (const UpdateData & block)
Definition at line 43 of file UpdateData.cpp.
 {
     m_data.append(block.m_data);
     m_blockCount += block.m_blockCount;
 }
References ByteBuffer::append(), m_blockCount, and m_data.
BuildPacket()
bool UpdateData::BuildPacket (WorldPacket * packet)
Definition at line 105 of file UpdateData.cpp.
 {
     ASSERT(packet->empty());                                // shouldn't happen
     ByteBuffer buf(4 + (m_outOfRangeGUIDs.empty() ? 0 : 1 + 4 + 9 * m_outOfRangeGUIDs.size()) + m_data.wpos());
     buf << (uint32) (!m_outOfRangeGUIDs.empty() ? m_blockCount + 1 : m_blockCount);
     if (!m_outOfRangeGUIDs.empty())
     {
         buf << (uint8) UPDATETYPE_OUT_OF_RANGE_OBJECTS;
         buf << (uint32) m_outOfRangeGUIDs.size();
         for (ObjectGuid const& guid : m_outOfRangeGUIDs)
         {
             buf << guid.WriteAsPacked();
         }
     }
     buf.append(m_data);
     size_t pSize = buf.wpos();                              // use real used data size
     if (pSize > 100)                                       // compress large packets
     {
         uint32 destsize = compressBound(pSize);
         packet->resize(destsize + sizeof(uint32));
         packet->put<uint32>(0, pSize);
         Compress(const_cast<uint8*>(packet->contents()) + sizeof(uint32), &destsize, (void*)buf.contents(), pSize);
         if (destsize == 0)
             return false;
         packet->resize(destsize + sizeof(uint32));
         packet->SetOpcode(SMSG_COMPRESSED_UPDATE_OBJECT);
     }
     else                                                    // send small packets without compression
     {
         packet->append(buf);
         packet->SetOpcode(SMSG_UPDATE_OBJECT);
     }
     return true;
 }
References ByteBuffer::append(), ASSERT, Compress(), compressBound(), ByteBuffer::contents(), ByteBuffer::empty(), m_blockCount, m_data, m_outOfRangeGUIDs, ByteBuffer::put(), ByteBuffer::resize(), WorldPacket::SetOpcode(), SMSG_COMPRESSED_UPDATE_OBJECT, SMSG_UPDATE_OBJECT, UPDATETYPE_OUT_OF_RANGE_OBJECTS, and ByteBuffer::wpos().
Referenced by Group::AddMember(), Map::SendInitTransports(), Map::SendRemoveTransports(), Acore::VisibleNotifier::SendToSelf(), BattlegroundSA::SendTransportInit(), BattlegroundSA::SendTransportsRemove(), Object::SendUpdateToPlayer(), Unit::SetOwnerGUID(), GameObject::Update(), Player::UpdateForQuestWorldObjects(), and Player::UpdateTriggerVisibility().
Clear()
void UpdateData::Clear ()
Definition at line 150 of file UpdateData.cpp.
 {
     m_data.clear();
     m_outOfRangeGUIDs.clear();
     m_blockCount = 0;
 }
References ByteBuffer::clear(), m_blockCount, m_data, and m_outOfRangeGUIDs.
Compress()
void UpdateData::Compress (void * dst, uint32 * dst_size, void * src, int src_size) protected
Definition at line 49 of file UpdateData.cpp.
 {
     z_stream c_stream;
     c_stream.zalloc = (alloc_func)0;
     c_stream.zfree = (free_func)0;
     c_stream.opaque = (voidpf)0;
     // default Z_BEST_SPEED (1)
     int z_res = deflateInit(&c_stream, sWorld->getIntConfig(CONFIG_COMPRESSION));
     if (z_res != Z_OK)
     {
         LOG_ERROR("entities.object", "Can't compress update packet (zlib: deflateInit) Error code: %i (%s)", z_res, zError(z_res));
         *dst_size = 0;
         return;
     }
     c_stream.next_out = (Bytef*)dst;
     c_stream.avail_out = *dst_size;
     c_stream.next_in = (Bytef*)src;
     c_stream.avail_in = (uInt)src_size;
     z_res = deflate(&c_stream, Z_NO_FLUSH);
     if (z_res != Z_OK)
     {
         LOG_ERROR("entities.object", "Can't compress update packet (zlib: deflate) Error code: %i (%s)", z_res, zError(z_res));
         *dst_size = 0;
         return;
     }
     if (c_stream.avail_in != 0)
     {
         LOG_ERROR("entities.object", "Can't compress update packet (zlib: deflate not greedy)");
         *dst_size = 0;
         return;
     }
     z_res = deflate(&c_stream, Z_FINISH);
     if (z_res != Z_STREAM_END)
     {
         LOG_ERROR("entities.object", "Can't compress update packet (zlib: deflate should report Z_STREAM_END instead %i (%s)", z_res, zError(z_res));
         *dst_size = 0;
         return;
     }
     z_res = deflateEnd(&c_stream);
     if (z_res != Z_OK)
     {
         LOG_ERROR("entities.object", "Can't compress update packet (zlib: deflateEnd) Error code: %i (%s)", z_res, zError(z_res));
         *dst_size = 0;
         return;
     }
     *dst_size = c_stream.total_out;
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CONFIG_COMPRESSION, deflate(), deflateEnd(), deflateInit, LOG_ERROR, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, sWorld, z_stream_s::total_out, Z_FINISH, Z_NO_FLUSH, Z_OK, Z_STREAM_END, z_stream_s::zalloc, zError(), and z_stream_s::zfree.
Referenced by BuildPacket().
HasData()
bool UpdateData::HasData () const inline
Definition at line 60 of file UpdateData.h.
 { return m_blockCount > 0 || !m_outOfRangeGUIDs.empty(); }
References m_blockCount, and m_outOfRangeGUIDs.
Referenced by Group::AddMember(), Acore::VisibleNotifier::SendToSelf(), and Player::UpdateTriggerVisibility().
Member Data Documentation
m_blockCount
uint32 UpdateData::m_blockCount protected
Definition at line 64 of file UpdateData.h.
Referenced by AddUpdateBlock(), BuildPacket(), Clear(), and HasData().
m_data
ByteBuffer UpdateData::m_data protected
Definition at line 66 of file UpdateData.h.
Referenced by AddUpdateBlock(), BuildPacket(), and Clear().
m_outOfRangeGUIDs
GuidVector UpdateData::m_outOfRangeGUIDs protected
Definition at line 65 of file UpdateData.h.
Referenced by AddOutOfRangeGUID(), BuildPacket(), Clear(), HasData(), and UpdateData().
The documentation for this class was generated from the following files:
src/server/game/Entities/Object/Updates/UpdateData.h
src/server/game/Entities/Object/Updates/UpdateData.cpp