Azerotcore-wotlk: G3D::Line Class Reference
G3D::Line Class Reference
#include <Line.h>
Public Member Functions
Line ()
Line (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
virtual ~Line ()
Vector3 closestPoint (const Vector3 &pt) const
double distance (const Vector3 &point) const
Vector3 point () const
Vector3 direction () const
Vector3 intersection (const Plane &plane) const
Vector3 closestPoint (const Line &B, float &minDist) const
Vector3 closestPoint (const Line &B) const
Static Public Member Functions
static Line fromTwoPoints (const Vector3 &point1, const Vector3 &point2)
static Line fromPointAndDirection (const Vector3 &point, const Vector3 &direction)
Protected Member Functions
Line (const Vector3 &point, const Vector3 &direction)
Protected Attributes
Vector3 _point
Vector3 _direction
Detailed Description
An infinite 3D line.
Definition at line 25 of file Line.h.
Constructor & Destructor Documentation
Line() [1/3]
G3D::Line::Line (const Vector3 & point, const Vector3 & direction) inline protected
Definition at line 31 of file Line.h.
{
         _point     = point;
         _direction = direction.direction();
     }
References _direction, _point, direction(), G3D::Vector3::direction(), and point().
Line() [2/3]
G3D::Line::Line () inline
Undefined (provided for creating Array<Line> only)
Definition at line 39 of file Line.h.
 {}
Referenced by fromPointAndDirection(), and fromTwoPoints().
Line() [3/3]
G3D::Line::Line (class BinaryInput & b)
Definition at line 35 of file Line.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
~Line()
virtual G3D::Line::~Line () inline virtual
Definition at line 47 of file Line.h.
 {}
Member Function Documentation
closestPoint() [1/3]
Vector3 G3D::Line::closestPoint (const Line & B) const inline
Definition at line 96 of file Line.h.
{
         float m;
         return closestPoint(B, m);
     }
References closestPoint().
closestPoint() [2/3]
Vector3 G3D::Line::closestPoint (const Line & B, float & minDist) const
Finds the closest point to the two lines.
Parameters
minDist Returns the minimum distance between the lines.
[http://objectmix.com/graphics/133793-coordinates-closest-points-pair-skew-lines.html]
Definition at line 68 of file Line.cpp.
{
     const Vector3& P1 = _point;
     const Vector3& U1 = _direction;
     Vector3 P2 = B.point();
     Vector3 U2 = B.direction();
     const Vector3& P21 = P2 - P1;
     const Vector3& M = U2.cross(U1);
     float m2 = M.length();
     Vector3 R = P21.cross(M) / m2;
     float t1 = R.dot(U2);
     minDist = (float)abs(P21.dot(M)) / sqrt(m2);
     return P1 + t1 * U1;
 }
References _direction, _point, G3D::abs(), G3D::Vector3::cross(), direction(), G3D::Vector3::dot(), G3D::Vector3::length(), and point().
closestPoint() [3/3]
Vector3 G3D::Line::closestPoint (const Vector3 & pt) const
Returns the closest point on the line to point.
Definition at line 52 of file Line.cpp.
{
     float t = _direction.dot(pt - _point);
     return _point + _direction * t;
 }
References _direction, _point, and G3D::Vector3::dot().
Referenced by closestPoint(), distance(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox().
deserialize()
void G3D::Line::deserialize (class BinaryInput & b)
Definition at line 46 of file Line.cpp.
{
     _point.deserialize(b);
     _direction.deserialize(b);
 }
References _direction, _point, b, and G3D::Vector3::deserialize().
Referenced by Line().
direction()
Vector3 G3D::Line::direction () const
Returns the direction (or negative direction) of the line
Definition at line 63 of file Line.cpp.
{
     return _direction;
 }
References _direction.
Referenced by closestPoint(), G3D::CollisionDetection::closestPointsBetweenLineAndLine(), fromPointAndDirection(), and Line().
distance()
double G3D::Line::distance (const Vector3 & point) const inline
Returns the distance between point and the line
Definition at line 71 of file Line.h.
{
         return (closestPoint(point) - point).magnitude();
     }
References closestPoint(), and point().
fromPointAndDirection()
static Line G3D::Line::fromPointAndDirection (const Vector3 & point, const Vector3 & direction) inline static
Creates a line from a point and a (nonzero) direction.
Definition at line 59 of file Line.h.
{
         return Line(point, direction);
     }
References direction(), Line(), and point().
Referenced by G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox().
fromTwoPoints()
static Line G3D::Line::fromTwoPoints (const Vector3 & point1, const Vector3 & point2) inline static
Constructs a line from two (not equal) points.
Definition at line 52 of file Line.h.
{
         return Line(point1, point2 - point1);
     }
References Line().
Referenced by G3D::Capsule::axis(), G3D::Cylinder::axis(), and G3D::ConvexPolygon::cut().
intersection()
Vector3 G3D::Line::intersection (const Plane & plane) const
Returns the point where the line and plane intersect. If there is no intersection, returns a point at infinity.
Definition at line 17 of file Line.cpp.
{
     float d;
     Vector3 normal = plane.normal();
     plane.getEquation(normal, d);
     float rate = _direction.dot(normal);
     if (rate == 0) {
         return Vector3::inf();
     } else {
         float t = -(d + _point.dot(normal)) / rate;
         return _point + _direction * t;
     }
 }
References _direction, _point, mpq::d, G3D::Vector3::dot(), G3D::Plane::getEquation(), G3D::Vector3::inf(), and G3D::Plane::normal().
Referenced by G3D::ConvexPolygon::cut().
point()
Vector3 G3D::Line::point () const
Returns a point on the line
Definition at line 58 of file Line.cpp.
{
     return _point;
 }
References _point.
Referenced by closestPoint(), G3D::CollisionDetection::closestPointsBetweenLineAndLine(), distance(), fromPointAndDirection(), and Line().
serialize()
void G3D::Line::serialize (class BinaryOutput & b) const
Definition at line 40 of file Line.cpp.
{
     _point.serialize(b);
     _direction.serialize(b);
 }
References _direction, _point, b, and G3D::Vector3::serialize().
Member Data Documentation
_direction
Vector3 G3D::Line::_direction protected
Definition at line 29 of file Line.h.
Referenced by closestPoint(), deserialize(), direction(), intersection(), Line(), and serialize().
_point
Vector3 G3D::Line::_point protected
Definition at line 28 of file Line.h.
Referenced by closestPoint(), deserialize(), intersection(), Line(), point(), and serialize().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Line.h
deps/g3dlite/source/Line.cpp