Azerotcore-wotlk: boss_thorim_arena_npcs::boss_thorim_arena_npcsAI Struct Reference
boss_thorim_arena_npcs::boss_thorim_arena_npcsAI Struct Reference
Public Member Functions
boss_thorim_arena_npcsAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
bool CanAIAttack (const Unit *target) const override
bool SelectT ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool _isCaster
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1608 of file boss_thorim.cpp.
Constructor & Destructor Documentation
boss_thorim_arena_npcsAI()
boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::boss_thorim_arena_npcsAI (Creature * pCreature) inline
Definition at line 1610 of file boss_thorim.cpp.
 : ScriptedAI(pCreature) { }
Member Function Documentation
CanAIAttack()
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1648 of file boss_thorim.cpp.
         {
             return target->GetPositionX() < 2180 && target->GetPositionZ() < 425;
         }
References Position::GetPositionX(), and Position::GetPositionZ().
EnterCombat()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1623 of file boss_thorim.cpp.
         {
             if (me->GetEntry() == NPC_DARK_RUNE_WARBRINGER)
             {
                 events.ScheduleEvent(EVENT_DR_WARBRINGER_RS, 8000);
             }
             else if (me->GetEntry() == NPC_DARK_RUNE_EVOKER)
             {
                 events.ScheduleEvent(EVENT_DR_EVOKER_RL, 2500);
                 events.ScheduleEvent(EVENT_DR_EVOKER_RM, 4000);
                 events.ScheduleEvent(EVENT_DR_EVOKER_RS, 10000);
             }
             else if (me->GetEntry() == NPC_DARK_RUNE_CHAMPION)
             {
                 events.ScheduleEvent(EVENT_DR_CHAMPION_WH, 6000);
                 events.ScheduleEvent(EVENT_DR_CHAMPION_CH, 12000);
                 events.ScheduleEvent(EVENT_DR_CHAMPION_MS, 8000);
             }
             else if (me->GetEntry() == NPC_DARK_RUNE_COMMONER)
             {
                 events.ScheduleEvent(EVENT_DR_COMMONER_LB, 5000);
                 events.ScheduleEvent(EVENT_DR_COMMONER_PM, 6000);
             }
         }
References EVENT_DR_CHAMPION_CH, EVENT_DR_CHAMPION_MS, EVENT_DR_CHAMPION_WH, EVENT_DR_COMMONER_LB, EVENT_DR_COMMONER_PM, EVENT_DR_EVOKER_RL, EVENT_DR_EVOKER_RM, EVENT_DR_EVOKER_RS, EVENT_DR_WARBRINGER_RS, Object::GetEntry(), ScriptedAI::me, NPC_DARK_RUNE_CHAMPION, NPC_DARK_RUNE_COMMONER, NPC_DARK_RUNE_EVOKER, and NPC_DARK_RUNE_WARBRINGER.
Reset()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1615 of file boss_thorim.cpp.
         {
             _isCaster = (me->GetEntry() == NPC_DARK_RUNE_EVOKER);
             events.Reset();
             if (me->GetEntry() == NPC_DARK_RUNE_WARBRINGER)
                 me->CastSpell(me, SPELL_AURA_OF_CELERITY, true);
         }
References _isCaster, Unit::CastSpell(), Object::GetEntry(), ScriptedAI::me, NPC_DARK_RUNE_EVOKER, NPC_DARK_RUNE_WARBRINGER, and SPELL_AURA_OF_CELERITY.
SelectT()
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT () inline
Definition at line 1653 of file boss_thorim.cpp.
         {
             Player* target = nullptr;
             Map::PlayerList const& pList = me->GetMap()->GetPlayers();
             uint8 num = urand(0, pList.getSize() - 1);
             uint8 count = 0;
             for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr, ++count)
             {
                 if (itr->GetSource()->GetPositionX() > 2180 || !itr->GetSource()->IsAlive() || itr->GetSource()->GetPositionZ() > 425)
                     continue;
                 if (count <= num || !target)
                     target = itr->GetSource();
                 else
                     break;
             }
             if (target)
             {
                 AttackStart(target);
                 me->AddThreat(target, 500.0f);
                 if (me->GetEntry() == NPC_DARK_RUNE_EVOKER && urand(0, 1))
                     me->CastSpell(me, SPELL_RUNIC_SHIELD, false);
                 else if (me->GetEntry() == NPC_DARK_RUNE_CHAMPION && !urand(0, 2))
                     me->CastSpell(target, SPELL_CHARGE, false);
                 return true;
             }
             return false;
         }
References Unit::AddThreat(), ScriptedAI::AttackStart(), MapRefMgr::begin(), Unit::CastSpell(), MapRefMgr::end(), Object::GetEntry(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::getSize(), ScriptedAI::me, NPC_DARK_RUNE_CHAMPION, NPC_DARK_RUNE_EVOKER, SPELL_CHARGE, SPELL_RUNIC_SHIELD, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1683 of file boss_thorim.cpp.
         {
             if (!UpdateVictim() && !SelectT())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_DR_WARBRINGER_RS:
                     me->CastSpell(me->GetVictim(), SPELL_RUNIC_STRIKE, false);
                     events.RepeatEvent(8000);
                     break;
                 case EVENT_DR_EVOKER_RL:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_RUNIC_LIGHTNING, false);
                     events.RepeatEvent(2500);
                     break;
                 case EVENT_DR_EVOKER_RM:
                     if (Unit* target = DoSelectLowestHpFriendly(40.0f, 15))
                         me->CastSpell(target, SPELL_RUNIC_MENDING, false);
                     else
                         me->CastSpell(me, SPELL_RUNIC_MENDING, false);
                     events.RepeatEvent(4000);
                     break;
                 case EVENT_DR_EVOKER_RS:
                     me->CastSpell(me, SPELL_RUNIC_SHIELD, false);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_DR_CHAMPION_CH:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_CHARGE, false);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_DR_CHAMPION_WH:
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED))
                         me->CastSpell(me, SPELL_WHIRLWIND, false);
                     events.RepeatEvent(6000);
                     break;
                 case EVENT_DR_CHAMPION_MS:
                     me->CastSpell(me->GetVictim(), SPELL_MORTAL_STRIKE, false);
                     events.RepeatEvent(8000);
                     break;
                 case EVENT_DR_COMMONER_LB:
                     me->CastSpell(me->GetVictim(), SPELL_LOW_BLOW, false);
                     events.RepeatEvent(5000);
                     break;
                 case EVENT_DR_COMMONER_PM:
                     me->CastSpell(me->GetVictim(), SPELL_PUMMEL, false);
                     events.RepeatEvent(6000);
                     break;
             }
             if (!_isCaster || (me->GetPower(POWER_MANA) * 100 / me->GetMaxPower(POWER_MANA) < 10))
                 DoMeleeAttackIfReady();
         }
References _isCaster, Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSelectLowestHpFriendly(), EVENT_DR_CHAMPION_CH, EVENT_DR_CHAMPION_MS, EVENT_DR_CHAMPION_WH, EVENT_DR_COMMONER_LB, EVENT_DR_COMMONER_PM, EVENT_DR_EVOKER_RL, EVENT_DR_EVOKER_RM, EVENT_DR_EVOKER_RS, EVENT_DR_WARBRINGER_RS, Unit::GetMaxPower(), Unit::GetPower(), Unit::GetVictim(), Object::HasFlag(), Unit::HasUnitState(), ScriptedAI::me, POWER_MANA, SELECT_TARGET_RANDOM, SelectT(), UnitAI::SelectTarget(), SPELL_CHARGE, SPELL_LOW_BLOW, SPELL_MORTAL_STRIKE, SPELL_PUMMEL, SPELL_RUNIC_LIGHTNING, SPELL_RUNIC_MENDING, SPELL_RUNIC_SHIELD, SPELL_RUNIC_STRIKE, SPELL_WHIRLWIND, UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_isCaster
bool boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::_isCaster
Definition at line 1613 of file boss_thorim.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::events
Definition at line 1612 of file boss_thorim.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp