Azerotcore-wotlk: spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript Class Reference
spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_putricide_ooze_channel_SpellScript)
bool Validate (SpellInfo const *spell) override
bool Load () override
void SelectTarget (std::list< WorldObject * > &targets)
void SetTarget (std::list< WorldObject * > &targets)
void StartAttack ()
void Register () override
Private Attributes
WorldObject * _target
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1094 of file boss_professor_putricide.cpp.
Member Function Documentation
Load()
bool spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1105 of file boss_professor_putricide.cpp.
         {
             _target = nullptr;
             return GetCaster()->GetTypeId() == TYPEID_UNIT;
         }
References _target, SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_UNIT.
PrepareSpellScript()
spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::PrepareSpellScript (spell_putricide_ooze_channel_SpellScript) private
Register()
void spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1148 of file boss_professor_putricide.cpp.
         {
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_putricide_ooze_channel_SpellScript::SelectTarget, EFFECT_0, TARGET_UNIT_SRC_AREA_ENEMY);
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_putricide_ooze_channel_SpellScript::SetTarget, EFFECT_1, TARGET_UNIT_SRC_AREA_ENEMY);
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_putricide_ooze_channel_SpellScript::SetTarget, EFFECT_2, TARGET_UNIT_SRC_AREA_ENEMY);
             AfterHit += SpellHitFn(spell_putricide_ooze_channel_SpellScript::StartAttack);
         }
References SpellScript::AfterHit, EFFECT_0, EFFECT_1, EFFECT_2, SpellScript::OnObjectAreaTargetSelect, SelectTarget(), SetTarget(), SpellHitFn, SpellObjectAreaTargetSelectFn, StartAttack(), and TARGET_UNIT_SRC_AREA_ENEMY.
SelectTarget()
void spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget (std::list< WorldObject * > & targets) inline private
Definition at line 1111 of file boss_professor_putricide.cpp.
         {
             // dbc has only 1 field for excluding, this will prevent anyone from getting both at the same time
             targets.remove_if(Acore::UnitAuraCheck(true, SPELL_VOLATILE_OOZE_PROTECTION));
             targets.remove_if(Acore::UnitAuraCheck(true, SPELL_GASEOUS_BLOAT_PROTECTION));
             if (targets.empty())
             {
                 FinishCast(SPELL_FAILED_NO_VALID_TARGETS);
                 GetCaster()->ToCreature()->DespawnOrUnsummon(1);    // despawn next update
                 return;
             }
             WorldObject* target = Acore::Containers::SelectRandomContainerElement(targets);
             targets.clear();
             targets.push_back(target);
             _target = target;
         }
References _target, Creature::DespawnOrUnsummon(), SpellScript::FinishCast(), SpellScript::GetCaster(), Acore::Containers::SelectRandomContainerElement(), SPELL_FAILED_NO_VALID_TARGETS, SPELL_GASEOUS_BLOAT_PROTECTION, SPELL_VOLATILE_OOZE_PROTECTION, and Object::ToCreature().
Referenced by Register().
SetTarget()
void spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SetTarget (std::list< WorldObject * > & targets) inline private
Definition at line 1130 of file boss_professor_putricide.cpp.
         {
             targets.clear();
             if (_target)
                 targets.push_back(_target);
         }
References _target.
Referenced by Register().
StartAttack()
void spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack () inline private
Definition at line 1137 of file boss_professor_putricide.cpp.
         {
             GetCaster()->ClearUnitState(UNIT_STATE_CASTING);
             GetCaster()->DeleteThreatList();
             GetCaster()->ToCreature()->SetInCombatWithZone();
             GetCaster()->ToCreature()->AI()->AttackStart(GetHitUnit());
             GetCaster()->AddThreat(GetHitUnit(), 500000000.0f);    // value seen in sniff
             if (Creature* c = GetCaster()->ToCreature())
                 c->AI()->SetGUID(GetHitUnit()->GetGUID(), -1);
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), mpq::c, Unit::ClearUnitState(), Unit::DeleteThreatList(), SpellScript::GetCaster(), SpellScript::GetHitUnit(), Creature::SetInCombatWithZone(), Object::ToCreature(), and UNIT_STATE_CASTING.
Referenced by Register().
Validate()
bool spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Validate (SpellInfo const * spell) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1098 of file boss_professor_putricide.cpp.
         {
             return ValidateSpellInfo({ spell->ExcludeTargetAuraSpell });
         }
References SpellInfo::ExcludeTargetAuraSpell, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_target
WorldObject* spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::_target private
Definition at line 1156 of file boss_professor_putricide.cpp.
Referenced by Load(), SelectTarget(), and SetTarget().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp