Azerotcore-wotlk: BGQueueRemoveEvent Class Reference
BGQueueRemoveEvent Class Reference
#include <BattlegroundQueue.h>
Public Member Functions
BGQueueRemoveEvent (ObjectGuid pl_guid, uint32 bgInstanceGUID, BattlegroundQueueTypeId bgQueueTypeId, uint32 removeTime)
~BGQueueRemoveEvent () override=default
bool Execute (uint64 e_time, uint32 p_time) override
void Abort (uint64 e_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
void ScheduleAbort ()
Private Attributes
ObjectGuid m_PlayerGuid
uint32 m_BgInstanceGUID
uint32 m_RemoveTime
BattlegroundQueueTypeId m_BgQueueTypeId
Detailed Description
Definition at line 176 of file BattlegroundQueue.h.
Constructor & Destructor Documentation
BGQueueRemoveEvent()
BGQueueRemoveEvent::BGQueueRemoveEvent (ObjectGuid pl_guid, uint32 bgInstanceGUID, BattlegroundQueueTypeId bgQueueTypeId, uint32 removeTime) inline
Definition at line 179 of file BattlegroundQueue.h.
         : m_PlayerGuid(pl_guid), m_BgInstanceGUID(bgInstanceGUID), m_RemoveTime(removeTime), m_BgQueueTypeId(bgQueueTypeId)
     {}
~BGQueueRemoveEvent()
BGQueueRemoveEvent::~BGQueueRemoveEvent () override default
Member Function Documentation
Abort()
void BGQueueRemoveEvent::Abort (uint64 e_time) override virtual
Reimplemented from BasicEvent.
Definition at line 1258 of file BattlegroundQueue.cpp.
 {
     //do nothing
 }
Execute()
bool BGQueueRemoveEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
Definition at line 1217 of file BattlegroundQueue.cpp.
 {
     Player* player = ObjectAccessor::FindConnectedPlayer(m_PlayerGuid);
     // player logged off, so he is no longer in queue
     if (!player)
         return true;
     Battleground* bg = sBattlegroundMgr->GetBattleground(m_BgInstanceGUID);
     // battleground can be already deleted, bg may be nullptr!
     // check if still in queue for this battleground
     uint32 queueSlot = player->GetBattlegroundQueueIndex(m_BgQueueTypeId);
     if (queueSlot < PLAYER_MAX_BATTLEGROUND_QUEUES) // player is in queue
     {
         // confirm the player is invited to this instance id (he didn't requeue in the meanwhile)
         BattlegroundQueue& bgQueue = sBattlegroundMgr->GetBattlegroundQueue(m_BgQueueTypeId);
         if (bgQueue.IsPlayerInvited(m_PlayerGuid, m_BgInstanceGUID, m_RemoveTime))
         {
             // track if player leaves the BG by not clicking enter button
             if (bg && bg->isBattleground() && (bg->GetStatus() == STATUS_IN_PROGRESS || bg->GetStatus() == STATUS_WAIT_JOIN))
             {
                 if (sWorld->getBoolConfig(CONFIG_BATTLEGROUND_TRACK_DESERTERS))
                 {
                     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_DESERTER_TRACK);
                     stmt->setUInt32(0, player->GetGUID().GetCounter());
                     stmt->setUInt8(1, BG_DESERTION_TYPE_NO_ENTER_BUTTON);
                     CharacterDatabase.Execute(stmt);
                 }
                 sScriptMgr->OnBattlegroundDesertion(player, BG_DESERTION_TYPE_NO_ENTER_BUTTON);
             }
             player->RemoveBattlegroundQueueId(m_BgQueueTypeId);
             bgQueue.RemovePlayer(m_PlayerGuid, false, queueSlot);
         }
     }
     return true;
 }
References BG_DESERTION_TYPE_NO_ENTER_BUTTON, CHAR_INS_DESERTER_TRACK, CharacterDatabase, CONFIG_BATTLEGROUND_TRACK_DESERTERS, ObjectAccessor::FindConnectedPlayer(), Player::GetBattlegroundQueueIndex(), ObjectGuid::GetCounter(), Object::GetGUID(), Battleground::GetStatus(), Battleground::isBattleground(), BattlegroundQueue::IsPlayerInvited(), PLAYER_MAX_BATTLEGROUND_QUEUES, Player::RemoveBattlegroundQueueId(), BattlegroundQueue::RemovePlayer(), sBattlegroundMgr, PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sScriptMgr, STATUS_IN_PROGRESS, STATUS_WAIT_JOIN, and sWorld.
Member Data Documentation
m_BgInstanceGUID
uint32 BGQueueRemoveEvent::m_BgInstanceGUID private
Definition at line 189 of file BattlegroundQueue.h.
m_BgQueueTypeId
BattlegroundQueueTypeId BGQueueRemoveEvent::m_BgQueueTypeId private
Definition at line 191 of file BattlegroundQueue.h.
m_PlayerGuid
ObjectGuid BGQueueRemoveEvent::m_PlayerGuid private
Definition at line 188 of file BattlegroundQueue.h.
m_RemoveTime
uint32 BGQueueRemoveEvent::m_RemoveTime private
Definition at line 190 of file BattlegroundQueue.h.
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/BattlegroundQueue.h
src/server/game/Battlegrounds/BattlegroundQueue.cpp