Azerotcore-wotlk: startFollow Class Reference
startFollow Class Reference
Public Member Functions
startFollow (Unit *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * _owner
Detailed Description
Definition at line 83 of file boss_lady_vashj.cpp.
Constructor & Destructor Documentation
startFollow()
startFollow::startFollow (Unit * owner) inline
Definition at line 86 of file boss_lady_vashj.cpp.
 : _owner(owner)  { }
Member Function Documentation
Execute()
bool startFollow::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 88 of file boss_lady_vashj.cpp.
     {
         if (InstanceScript* instance = _owner->GetInstanceScript())
             if (Creature* vashj = ObjectAccessor::GetCreature(*_owner, instance->GetGuidData(NPC_LADY_VASHJ)))
                 _owner->GetMotionMaster()->MoveFollow(vashj, 3.0f, vashj->GetAngle(_owner), MOTION_SLOT_CONTROLLED);
         return true;
     }
References _owner, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), MOTION_SLOT_CONTROLLED, MotionMaster::MoveFollow(), and NPC_LADY_VASHJ.
Member Data Documentation
_owner
Unit* startFollow::_owner private
Definition at line 97 of file boss_lady_vashj.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp