Azerotcore-wotlk: LFGUpdateRequest Class Reference
LFGUpdateRequest Class Reference
Public Member Functions
LFGUpdateRequest (MapUpdater &u, uint32 d)
void call () override
Public Member Functions inherited from UpdateRequest
UpdateRequest ()=default
virtual ~UpdateRequest ()=default
Private Attributes
MapUpdater & m_updater
uint32 m_diff
Detailed Description
Definition at line 55 of file MapUpdater.cpp.
Constructor & Destructor Documentation
LFGUpdateRequest()
LFGUpdateRequest::LFGUpdateRequest (MapUpdater & u, uint32 d) inline
Definition at line 58 of file MapUpdater.cpp.
 : m_updater(u), m_diff(d) {}
Member Function Documentation
call()
void LFGUpdateRequest::call () inline override virtual
Implements UpdateRequest.
Definition at line 60 of file MapUpdater.cpp.
     {
         uint32 startTime = getMSTime();
         sLFGMgr->Update(m_diff, 1);
         uint32 totalTime = getMSTimeDiff(startTime, getMSTime());
         lfgDiffTracker.Update(totalTime);
         m_updater.update_finished();
     }
References getMSTime(), getMSTimeDiff(), lfgDiffTracker, m_diff, m_updater, sLFGMgr, AvgDiffTracker::Update(), and MapUpdater::update_finished().
Member Data Documentation
m_diff
uint32 LFGUpdateRequest::m_diff private
Definition at line 70 of file MapUpdater.cpp.
Referenced by call().
m_updater
MapUpdater& LFGUpdateRequest::m_updater private
Definition at line 69 of file MapUpdater.cpp.
Referenced by call().
The documentation for this class was generated from the following file:
src/server/game/Maps/MapUpdater.cpp