Azerotcore-wotlk: SQLQueryHolderBase Class Reference
SQLQueryHolderBase Class Reference
#include <QueryHolder.h>
Public Member Functions
SQLQueryHolderBase ()=default
virtual ~SQLQueryHolderBase ()
void SetSize (size_t size)
PreparedQueryResult GetPreparedResult (size_t index) const
void SetPreparedResult (size_t index, PreparedResultSet *result)
Protected Member Functions
bool SetPreparedQueryImpl (size_t index, PreparedStatementBase *stmt)
Private Attributes
std::vector< std::pair< PreparedStatementBase *, PreparedQueryResult > > m_queries
Friends
class SQLQueryHolderTask
Detailed Description
Definition at line 24 of file QueryHolder.h.
Constructor & Destructor Documentation
SQLQueryHolderBase()
SQLQueryHolderBase::SQLQueryHolderBase () default
~SQLQueryHolderBase()
SQLQueryHolderBase::~SQLQueryHolderBase () virtual
if the result was never used, free the resources results used already (getresult called) are expected to be deleted
Definition at line 59 of file QueryHolder.cpp.
 {
     for (std::pair<PreparedStatementBase*, PreparedQueryResult>& query : m_queries)
     {
         delete query.first;
     }
 }
References m_queries.
Member Function Documentation
GetPreparedResult()
PreparedQueryResult SQLQueryHolderBase::GetPreparedResult (size_t index) const
Definition at line 37 of file QueryHolder.cpp.
 {
     // Don't call to this function if the index is of a prepared statement
     ASSERT(index < m_queries.size(), "Query holder result index out of range, tried to access index " SZFMTD " but there are only " SZFMTD " results",
         index, m_queries.size());
     return m_queries[index].second;
 }
References ASSERT, m_queries, and SZFMTD.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback(), WorldSession::HandlePlayerLoginFromDB(), and Player::LoadFromDB().
SetPreparedQueryImpl()
bool SQLQueryHolderBase::SetPreparedQueryImpl (size_t index, PreparedStatementBase * stmt) protected
Definition at line 25 of file QueryHolder.cpp.
 {
     if (m_queries.size() <= index)
     {
         LOG_ERROR("sql.sql", "Query index (%u) out of range (size: %u) for prepared statement", uint32(index), (uint32)m_queries.size());
         return false;
     }
     m_queries[index].first = stmt;
     return true;
 }
References LOG_ERROR, and m_queries.
Referenced by SQLQueryHolder< T >::SetPreparedQuery().
SetPreparedResult()
void SQLQueryHolderBase::SetPreparedResult (size_t index, PreparedResultSet * result)
store the result in the holder
Definition at line 46 of file QueryHolder.cpp.
 {
     if (result && !result->GetRowCount())
     {
         delete result;
         result = nullptr;
     }
     if (index < m_queries.size())
         m_queries[index].second = PreparedQueryResult(result);
 }
References PreparedResultSet::GetRowCount(), and m_queries.
SetSize()
void SQLQueryHolderBase::SetSize (size_t size)
to optimize push_back, reserve the number of queries about to be executed
Definition at line 69 of file QueryHolder.cpp.
 {
     m_queries.resize(size);
 }
References m_queries.
Referenced by LoginQueryHolder::Initialize(), and LoadPetFromDBQueryHolder::Initialize().
Friends And Related Function Documentation
SQLQueryHolderTask
friend class SQLQueryHolderTask friend
Definition at line 26 of file QueryHolder.h.
Member Data Documentation
m_queries
std::vector<std::pair<PreparedStatementBase*, PreparedQueryResult> > SQLQueryHolderBase::m_queries private
Definition at line 28 of file QueryHolder.h.
Referenced by GetPreparedResult(), SetPreparedQueryImpl(), SetPreparedResult(), SetSize(), and ~SQLQueryHolderBase().
The documentation for this class was generated from the following files:
src/server/database/Database/QueryHolder.h
src/server/database/Database/QueryHolder.cpp