Azerotcore-wotlk: at_frozen_throne_teleport Class Reference
at_frozen_throne_teleport Class Reference
Public Member Functions
at_frozen_throne_teleport ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 106 of file icecrown_citadel_teleport.cpp.
Constructor & Destructor Documentation
at_frozen_throne_teleport()
at_frozen_throne_teleport::at_frozen_throne_teleport () inline
Definition at line 109 of file icecrown_citadel_teleport.cpp.
 : AreaTriggerScript("at_frozen_throne_teleport") { }
Member Function Documentation
OnTrigger()
bool at_frozen_throne_teleport::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 111 of file icecrown_citadel_teleport.cpp.
     {
         if (player->IsInCombat())
         {
             if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(FROZEN_THRONE_TELEPORT))
                 Spell::SendCastResult(player, spell, 0, SPELL_FAILED_AFFECTING_COMBAT);
             return true;
         }
         if (InstanceScript* instance = player->GetInstanceScript())
             if (instance->GetBossState(DATA_PROFESSOR_PUTRICIDE) == DONE &&
                     instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == DONE &&
                     instance->GetBossState(DATA_SINDRAGOSA) == DONE &&
                     instance->GetBossState(DATA_THE_LICH_KING) != IN_PROGRESS)
                 player->CastSpell(player, FROZEN_THRONE_TELEPORT, false);
         return true;
     }
References Unit::CastSpell(), DATA_BLOOD_QUEEN_LANA_THEL, DATA_PROFESSOR_PUTRICIDE, DATA_SINDRAGOSA, DATA_THE_LICH_KING, DONE, FROZEN_THRONE_TELEPORT, WorldObject::GetInstanceScript(), IN_PROGRESS, Unit::IsInCombat(), Spell::SendCastResult(), SPELL_FAILED_AFFECTING_COMBAT, and sSpellMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel_teleport.cpp