Azerotcore-wotlk: FrostwingGauntletRespawner Class Reference
FrostwingGauntletRespawner Class Reference
Public Member Functions
void operator() (Creature *creature)
Detailed Description
Definition at line 316 of file icecrown_citadel.cpp.
Member Function Documentation
operator()()
void FrostwingGauntletRespawner::operator() (Creature * creature) inline
Definition at line 319 of file icecrown_citadel.cpp.
     {
         switch (creature->GetOriginalEntry())
         {
             case NPC_YMIRJAR_BATTLE_MAIDEN:
             case NPC_YMIRJAR_DEATHBRINGER:
             case NPC_YMIRJAR_FROSTBINDER:
             case NPC_YMIRJAR_HUNTRESS:
             case NPC_YMIRJAR_WARLORD:
                 break;
             case NPC_CROK_SCOURGEBANE:
             case NPC_CAPTAIN_ARNATH:
             case NPC_CAPTAIN_BRANDON:
             case NPC_CAPTAIN_GRONDEL:
             case NPC_CAPTAIN_RUPERT:
                 creature->AI()->DoAction(ACTION_RESET_EVENT);
                 break;
             case NPC_SISTER_SVALNA: // she never dies or the event is over
                 creature->AI()->DoAction(ACTION_RESET_EVENT);
                 creature->AI()->EnterEvadeMode();
                 creature->AI()->Reset();
                 return;
             default:
                 return;
         }
         if (CreatureData const* data = creature->GetCreatureData())
             creature->SetPosition(data->posX, data->posY, data->posZ, data->orientation);
         creature->DespawnOrUnsummon();
         creature->SetRespawnTime(5);
     }
References ACTION_RESET_EVENT, Creature::AI(), Creature::DespawnOrUnsummon(), UnitAI::DoAction(), CreatureAI::EnterEvadeMode(), Creature::GetCreatureData(), Creature::GetOriginalEntry(), NPC_CAPTAIN_ARNATH, NPC_CAPTAIN_BRANDON, NPC_CAPTAIN_GRONDEL, NPC_CAPTAIN_RUPERT, NPC_CROK_SCOURGEBANE, NPC_SISTER_SVALNA, NPC_YMIRJAR_BATTLE_MAIDEN, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, NPC_YMIRJAR_WARLORD, UnitAI::Reset(), Creature::SetPosition(), and Creature::SetRespawnTime().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp