Azerotcore-wotlk: instance_the_black_morass::instance_the_black_morass_InstanceMapScript Struct Reference
instance_the_black_morass::instance_the_black_morass_InstanceMapScript Struct Reference
Public Member Functions
instance_the_black_morass_InstanceMapScript (Map *map)
void Initialize () override
void CleanupInstance ()
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SetData (uint32 type, uint32) override
uint32 GetData (uint32 type) const override
void SetGuidData (uint32 type, ObjectGuid data) override
ObjectGuid GetGuidData (uint32 data) const override
void SummonPortalKeeper ()
void Update (uint32 diff) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
GuidSet encounterNPCs
uint32 encounters [MAX_ENCOUNTER]
ObjectGuid _medivhGUID
uint8 _currentRift
uint8 _shieldPercent
Public Attributes inherited from InstanceScript
Map * instance
Protected Attributes
EventMap Events
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 44 of file instance_the_black_morass.cpp.
Constructor & Destructor Documentation
instance_the_black_morass_InstanceMapScript()
instance_the_black_morass::instance_the_black_morass_InstanceMapScript::instance_the_black_morass_InstanceMapScript (Map * map) inline
Definition at line 46 of file instance_the_black_morass.cpp.
 : InstanceScript(map) { }
Member Function Documentation
CleanupInstance()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::CleanupInstance () inline
Definition at line 62 of file instance_the_black_morass.cpp.
         {
             Events.Reset();
             _currentRift = 0;
             _shieldPercent = 100;
             instance->LoadGrid(-2023.0f, 7121.0f);
             if (Creature* medivh = instance->GetCreature(_medivhGUID))
             {
                 medivh->DespawnOrUnsummon();
                 medivh->SetRespawnTime(3);
             }
             GuidSet eCopy = encounterNPCs;
             for (ObjectGuid const& guid : eCopy)
                 if (Creature* creature = instance->GetCreature(guid))
                     creature->DespawnOrUnsummon();
         }
References _currentRift, _medivhGUID, _shieldPercent, encounterNPCs, Map::GetCreature(), InstanceScript::instance, and Map::LoadGrid().
Referenced by OnPlayerEnter().
GetData()
uint32 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 208 of file instance_the_black_morass.cpp.
         {
             switch (type)
             {
                 case TYPE_CHRONO_LORD_DEJA:
                 case TYPE_TEMPORUS:
                 case TYPE_AEONUS:
                     return encounters[type];
                 case DATA_SHIELD_PERCENT:
                     return _shieldPercent;
                 case DATA_RIFT_NUMBER:
                     return _currentRift;
             }
             return 0;
         }
References _currentRift, _shieldPercent, DATA_RIFT_NUMBER, DATA_SHIELD_PERCENT, encounters, TYPE_AEONUS, TYPE_CHRONO_LORD_DEJA, and TYPE_TEMPORUS.
Referenced by OnPlayerEnter(), and SummonPortalKeeper().
GetGuidData()
ObjectGuid instance_the_black_morass::instance_the_black_morass_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 232 of file instance_the_black_morass.cpp.
         {
             if (data == DATA_MEDIVH)
                 return _medivhGUID;
             return ObjectGuid::Empty;
         }
References _medivhGUID, DATA_MEDIVH, and ObjectGuid::Empty.
GetSaveData()
std::string instance_the_black_morass::instance_the_black_morass_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 314 of file instance_the_black_morass.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "B M " << encounters[0] << ' ' << encounters[1] << ' ' << encounters[2];
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References encounters, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_the_black_morass.cpp.
         {
             memset(&encounters, 0, sizeof(encounters));
             _currentRift = 0;
             _shieldPercent = 100;
             encounterNPCs.clear();
         }
References _currentRift, _shieldPercent, encounterNPCs, and encounters.
IsEncounterInProgress()
bool instance_the_black_morass::instance_the_black_morass_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 81 of file instance_the_black_morass.cpp.
         {
             return false;
         }
Load()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 325 of file instance_the_black_morass.cpp.
         {
             if (!in)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'B' && dataHead2 == 'M')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                     loadStream >> encounters[i];
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References encounters, MAX_ENCOUNTER, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 96 of file instance_the_black_morass.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_MEDIVH:
                     _medivhGUID = creature->GetGUID();
                     break;
                 case NPC_TIME_RIFT:
                 case NPC_CHRONO_LORD_DEJA:
                 case NPC_INFINITE_CHRONO_LORD:
                 case NPC_TEMPORUS:
                 case NPC_INFINITE_TIMEREAVER:
                 case NPC_AEONUS:
                 case NPC_RIFT_KEEPER_WARLOCK:
                 case NPC_RIFT_KEEPER_MAGE:
                 case NPC_RIFT_LORD:
                 case NPC_RIFT_LORD_2:
                 case NPC_INFINITE_ASSASIN:
                 case NPC_INFINITE_WHELP:
                 case NPC_INFINITE_CRONOMANCER:
                 case NPC_INFINITE_EXECUTIONER:
                 case NPC_INFINITE_VANQUISHER:
                     encounterNPCs.insert(creature->GetGUID());
                     break;
             }
         }
References _medivhGUID, encounterNPCs, Object::GetEntry(), Object::GetGUID(), NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_INFINITE_ASSASIN, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_CRONOMANCER, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_TIMEREAVER, NPC_INFINITE_VANQUISHER, NPC_INFINITE_WHELP, NPC_MEDIVH, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, and NPC_TIME_RIFT.
OnCreatureRemove()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnCreatureRemove (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 123 of file instance_the_black_morass.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_TIME_RIFT:
                 case NPC_CHRONO_LORD_DEJA:
                 case NPC_INFINITE_CHRONO_LORD:
                 case NPC_TEMPORUS:
                 case NPC_INFINITE_TIMEREAVER:
                 case NPC_AEONUS:
                 case NPC_RIFT_KEEPER_WARLOCK:
                 case NPC_RIFT_KEEPER_MAGE:
                 case NPC_RIFT_LORD:
                 case NPC_RIFT_LORD_2:
                 case NPC_INFINITE_ASSASIN:
                 case NPC_INFINITE_WHELP:
                 case NPC_INFINITE_CRONOMANCER:
                 case NPC_INFINITE_EXECUTIONER:
                 case NPC_INFINITE_VANQUISHER:
                     encounterNPCs.erase(creature->GetGUID());
                     break;
             }
         }
References encounterNPCs, Object::GetEntry(), Object::GetGUID(), NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_INFINITE_ASSASIN, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_CRONOMANCER, NPC_INFINITE_EXECUTIONER, NPC_INFINITE_TIMEREAVER, NPC_INFINITE_VANQUISHER, NPC_INFINITE_WHELP, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, and NPC_TIME_RIFT.
OnPlayerEnter()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
Definition at line 86 of file instance_the_black_morass.cpp.
         {
             if (instance->GetPlayersCountExceptGMs() <= 1 && GetData(TYPE_AEONUS) != DONE)
                 CleanupInstance();
             player->SendUpdateWorldState(WORLD_STATE_BM, _currentRift > 0 ? 1 : 0);
             player->SendUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
             player->SendUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
         }
References _currentRift, _shieldPercent, CleanupInstance(), DONE, GetData(), Map::GetPlayersCountExceptGMs(), InstanceScript::instance, Player::SendUpdateWorldState(), TYPE_AEONUS, WORLD_STATE_BM, WORLD_STATE_BM_RIFT, and WORLD_STATE_BM_SHIELD.
SetData()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
Definition at line 147 of file instance_the_black_morass.cpp.
         {
             switch (type)
             {
                 case TYPE_AEONUS:
                     {
                         encounters[type] = DONE;
                         SaveToDB();
                         if (Creature* medivh = instance->GetCreature(_medivhGUID))
                             medivh->AI()->DoAction(ACTION_OUTRO);
                         Map::PlayerList const& players = instance->GetPlayers();
                         if (!players.isEmpty())
                             for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                                 if (Player* player = itr->GetSource())
{
                                     if (player->GetQuestStatus(QUEST_OPENING_PORTAL) == QUEST_STATUS_INCOMPLETE)
                                         player->AreaExploredOrEventHappens(QUEST_OPENING_PORTAL);
                                     if (player->GetQuestStatus(QUEST_MASTER_TOUCH) == QUEST_STATUS_INCOMPLETE)
                                         player->AreaExploredOrEventHappens(QUEST_MASTER_TOUCH);
                                 }
                         break;
                     }
                 case TYPE_CHRONO_LORD_DEJA:
                 case TYPE_TEMPORUS:
                     encounters[type] = DONE;
                     Events.RescheduleEvent(EVENT_NEXT_PORTAL, 60000);
                     Events.SetPhase(1);
                     SaveToDB();
                     break;
                 case DATA_RIFT_KILLED:
                     if (!Events.IsInPhase(1))
                         Events.RescheduleEvent(EVENT_NEXT_PORTAL, 4000);
                     break;
                 case DATA_MEDIVH:
                     DoUpdateWorldState(WORLD_STATE_BM, 1);
                     DoUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
                     DoUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
                     Events.RescheduleEvent(EVENT_NEXT_PORTAL, 3000);
                     break;
                 case DATA_DAMAGE_SHIELD:
                     --_shieldPercent;
                     DoUpdateWorldState(WORLD_STATE_BM_SHIELD, _shieldPercent);
                     if (!_shieldPercent)
                         if (Creature* medivh = instance->GetCreature(_medivhGUID))
                             if (medivh->IsAlive())
{
                                 Unit::Kill(medivh, medivh);
                                 // Xinef: delete all spawns
                                 GuidSet eCopy = encounterNPCs;
                                 for (ObjectGuid const& guid : eCopy)
                                     if (Creature* creature = instance->GetCreature(guid))
                                         creature->DespawnOrUnsummon();
                             }
                     break;
             }
         }
References _currentRift, _medivhGUID, _shieldPercent, ACTION_OUTRO, MapRefMgr::begin(), DATA_DAMAGE_SHIELD, DATA_MEDIVH, DATA_RIFT_KILLED, DONE, InstanceScript::DoUpdateWorldState(), encounterNPCs, encounters, MapRefMgr::end(), EVENT_NEXT_PORTAL, Map::GetCreature(), Map::GetPlayers(), InstanceScript::instance, LinkedListHead::isEmpty(), Unit::Kill(), QUEST_MASTER_TOUCH, QUEST_OPENING_PORTAL, QUEST_STATUS_INCOMPLETE, InstanceScript::SaveToDB(), TYPE_AEONUS, TYPE_CHRONO_LORD_DEJA, TYPE_TEMPORUS, WORLD_STATE_BM, WORLD_STATE_BM_RIFT, and WORLD_STATE_BM_SHIELD.
SetGuidData()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 224 of file instance_the_black_morass.cpp.
         {
             if (type == DATA_SUMMONED_NPC)
                 encounterNPCs.insert(data);
             else if (type == DATA_DELETED_NPC)
                 encounterNPCs.erase(data);
         }
References DATA_DELETED_NPC, DATA_SUMMONED_NPC, and encounterNPCs.
SummonPortalKeeper()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper () inline
Definition at line 240 of file instance_the_black_morass.cpp.
         {
             Creature* rift = nullptr;
             for (ObjectGuid const& guid : encounterNPCs)
                 if (Creature* summon = instance->GetCreature(guid))
                     if (summon->GetEntry() == NPC_TIME_RIFT)
                     {
                         rift = summon;
                         break;
                     }
             if (!rift)
                 return;
             int32 entry = 0;
             switch (_currentRift)
             {
                 case 6:
                     entry = GetData(TYPE_CHRONO_LORD_DEJA) == DONE ? (instance->IsHeroic() ? NPC_INFINITE_CHRONO_LORD : -NPC_CHRONO_LORD_DEJA) : NPC_CHRONO_LORD_DEJA;
                     break;
                 case 12:
                     entry = GetData(TYPE_TEMPORUS) == DONE ? (instance->IsHeroic() ? NPC_INFINITE_TIMEREAVER : -NPC_TEMPORUS) : NPC_TEMPORUS;
                     break;
                 case 18:
                     entry = NPC_AEONUS;
                     break;
                 default:
                     entry = RAND(NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_LORD, NPC_RIFT_LORD_2);
                     break;
             }
             Position pos = rift->GetNearPosition(10.0f, 2 * M_PI * rand_norm());
             if (TempSummon* summon = instance->SummonCreature(abs(entry), pos))
             {
                 summon->SetTempSummonType(TEMPSUMMON_CORPSE_TIMED_DESPAWN);
                 summon->SetTimer(3 * MINUTE * IN_MILLISECONDS);
                 if (entry < 0)
                     summon->SetLootMode(0);
                 if (summon->GetEntry() != NPC_AEONUS)
                 {
                     rift->AI()->SetGUID(summon->GetGUID());
                     rift->CastSpell(summon, SPELL_RIFT_CHANNEL, false);
                 }
                 else
                     summon->SetReactState(REACT_DEFENSIVE);
             }
         }
References _currentRift, Creature::AI(), Unit::CastSpell(), DONE, encounterNPCs, Map::GetCreature(), GetData(), WorldObject::GetNearPosition(), IN_MILLISECONDS, InstanceScript::instance, Map::IsHeroic(), MINUTE, NPC_AEONUS, NPC_CHRONO_LORD_DEJA, NPC_INFINITE_CHRONO_LORD, NPC_INFINITE_TIMEREAVER, NPC_RIFT_KEEPER_MAGE, NPC_RIFT_KEEPER_WARLOCK, NPC_RIFT_LORD, NPC_RIFT_LORD_2, NPC_TEMPORUS, NPC_TIME_RIFT, RAND(), rand_norm(), REACT_DEFENSIVE, UnitAI::SetGUID(), SPELL_RIFT_CHANNEL, Map::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TYPE_CHRONO_LORD_DEJA, and TYPE_TEMPORUS.
Referenced by Update().
Update()
void instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 291 of file instance_the_black_morass.cpp.
         {
             Events.Update(diff);
             switch (Events.ExecuteEvent())
             {
                 case EVENT_NEXT_PORTAL:
                     ++_currentRift;
                     DoUpdateWorldState(WORLD_STATE_BM_RIFT, _currentRift);
                     Events.ScheduleEvent(EVENT_SUMMON_KEEPER, 6000);
                     Events.SetPhase(0);
                     if (instance->GetCreature(_medivhGUID))
                     {
                         uint8 position = (_currentRift - 1) % 4;
                         instance->SummonCreature(NPC_TIME_RIFT, PortalLocation[position]);
                     }
                     break;
                 case EVENT_SUMMON_KEEPER:
                     SummonPortalKeeper();
                     break;
             }
         }
References _currentRift, _medivhGUID, InstanceScript::DoUpdateWorldState(), EVENT_NEXT_PORTAL, EVENT_SUMMON_KEEPER, Map::GetCreature(), InstanceScript::instance, NPC_TIME_RIFT, PortalLocation, Map::SummonCreature(), SummonPortalKeeper(), and WORLD_STATE_BM_RIFT.
Member Data Documentation
_currentRift
uint8 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_currentRift
Definition at line 51 of file instance_the_black_morass.cpp.
Referenced by CleanupInstance(), GetData(), Initialize(), OnPlayerEnter(), SetData(), SummonPortalKeeper(), and Update().
_medivhGUID
ObjectGuid instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_medivhGUID
Definition at line 50 of file instance_the_black_morass.cpp.
Referenced by CleanupInstance(), GetGuidData(), OnCreatureCreate(), SetData(), and Update().
_shieldPercent
uint8 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::_shieldPercent
Definition at line 52 of file instance_the_black_morass.cpp.
Referenced by CleanupInstance(), GetData(), Initialize(), OnPlayerEnter(), and SetData().
encounterNPCs
GuidSet instance_the_black_morass::instance_the_black_morass_InstanceMapScript::encounterNPCs
Definition at line 48 of file instance_the_black_morass.cpp.
Referenced by CleanupInstance(), Initialize(), OnCreatureCreate(), OnCreatureRemove(), SetData(), SetGuidData(), and SummonPortalKeeper().
encounters
uint32 instance_the_black_morass::instance_the_black_morass_InstanceMapScript::encounters[MAX_ENCOUNTER]
Definition at line 49 of file instance_the_black_morass.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), and SetData().
Events
EventMap instance_the_black_morass::instance_the_black_morass_InstanceMapScript::Events protected
Definition at line 351 of file instance_the_black_morass.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp