Azerotcore-wotlk: DoodadSet Class Reference
DoodadSet Class Reference
#include <Utils.h>
Public Member Functions
DoodadSet ()
Static Public Member Functions
static DoodadSet Read (FILE *stream)
Public Attributes
std::string Name
uint32 FirstInstanceIndex
uint32 CountInstances
uint32 UnknownZero
Detailed Description
Definition at line 228 of file Utils.h.
Constructor & Destructor Documentation
DoodadSet()
DoodadSet::DoodadSet () inline
Definition at line 231 of file Utils.h.
 {}
Member Function Documentation
Read()
DoodadSet DoodadSet::Read (FILE * stream) static
Definition at line 404 of file Utils.cpp.
 {
     DoodadSet ret;
     char name[21];
     int count = 0;
     count += fread(&name, sizeof(char), 20, stream);
     name[20] = '\0';
     ret.Name = name;
     count += fread(&ret.FirstInstanceIndex, sizeof(uint32), 1, stream);
     count += fread(&ret.CountInstances, sizeof(uint32), 1, stream);
     count += fread(&ret.UnknownZero, sizeof(uint32), 1, stream);
     if (count != 23)
         printf("DoodadSet::Read: Failed to read some data expected 23, read %d\n", count);
     return ret;
 }
References count(), name, printf(), and ret.
Referenced by WorldModelRoot::ReadDoodadSets().
Member Data Documentation
CountInstances
uint32 DoodadSet::CountInstances
Definition at line 234 of file Utils.h.
FirstInstanceIndex
uint32 DoodadSet::FirstInstanceIndex
Definition at line 233 of file Utils.h.
Name
std::string DoodadSet::Name
Definition at line 232 of file Utils.h.
UnknownZero
uint32 DoodadSet::UnknownZero
Definition at line 235 of file Utils.h.
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp