Azerotcore-wotlk: npc_thrall Class Reference
npc_thrall Class Reference
Public Member Functions
npc_thrall ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 128 of file hyjal.cpp.
Constructor & Destructor Documentation
npc_thrall()
npc_thrall::npc_thrall () inline
Definition at line 131 of file hyjal.cpp.
 : CreatureScript("npc_thrall") { }
Member Function Documentation
GetAI()
CreatureAI* npc_thrall::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 186 of file hyjal.cpp.
     {
         if (!creature->GetInstanceScript())
             return nullptr;
         hyjalAI* ai = new hyjalAI(creature);
         ai->Reset();
         ai->EnterEvadeMode();
         ai->Spells[0].SpellId = SPELL_CHAIN_LIGHTNING;
         ai->Spells[0].Cooldown = urand(3000, 8000);
         ai->Spells[0].TargetType = TARGETTYPE_VICTIM;
         ai->Spells[1].SpellId = SPELL_SUMMON_DIRE_WOLF;
         ai->Spells[1].Cooldown = urand(6000, 41000);
         ai->Spells[1].TargetType = TARGETTYPE_RANDOM;
         return ai;
     }
References hyjalAI::Spell::Cooldown, hyjalAI::EnterEvadeMode(), WorldObject::GetInstanceScript(), hyjalAI::Reset(), SPELL_CHAIN_LIGHTNING, SPELL_SUMMON_DIRE_WOLF, hyjalAI::Spell::SpellId, hyjalAI::Spells, hyjalAI::Spell::TargetType, TARGETTYPE_RANDOM, TARGETTYPE_VICTIM, and urand().
OnGossipHello()
bool npc_thrall::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 159 of file hyjal.cpp.
     {
         hyjalAI* ai = CAST_AI(hyjalAI, creature->AI());
         if (ai->EventBegun)
             return false;
         uint32 AnetheronEvent = ai->GetInstanceData(DATA_ANETHERONEVENT);
         // Only let them start the Horde phases if Anetheron is dead.
         if (AnetheronEvent == DONE && ai->GetInstanceData(DATA_ALLIANCE_RETREAT))
         {
             uint32 KazrogalEvent = ai->GetInstanceData(DATA_KAZROGALEVENT);
             uint32 AzgalorEvent  = ai->GetInstanceData(DATA_AZGALOREVENT);
             if (KazrogalEvent == NOT_STARTED)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BEGIN_HORDE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             else if (KazrogalEvent == DONE && AzgalorEvent == NOT_STARTED)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_AZGALOR, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
             else if (AzgalorEvent == DONE)
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_RETREAT, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
         }
         if (player->IsGameMaster())
             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_ITEM_GM1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         SendGossipMenuFor(player, 907, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Creature::AI(), CAST_AI, DATA_ALLIANCE_RETREAT, DATA_ANETHERONEVENT, DATA_AZGALOREVENT, DATA_KAZROGALEVENT, DONE, hyjalAI::EventBegun, Object::GetGUID(), hyjalAI::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ICON_TRAINER, GOSSIP_ITEM_AZGALOR, GOSSIP_ITEM_BEGIN_HORDE, GOSSIP_ITEM_GM1, GOSSIP_ITEM_RETREAT, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), NOT_STARTED, and SendGossipMenuFor().
OnGossipSelect()
bool npc_thrall::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 133 of file hyjal.cpp.
     {
         ClearGossipMenuFor(player);
         hyjalAI* ai = CAST_AI(hyjalAI, creature->AI());
         ai->DeSpawnVeins();//despawn the alliance veins
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1:
                 ai->StartEvent(player);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 ai->FirstBossDead = true;
                 ai->WaveCount = 9;
                 ai->StartEvent(player);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 ai->Retreat();
                 break;
             case GOSSIP_ACTION_INFO_DEF:
                 ai->Debug = !ai->Debug;
                 //TC_LOG_DEBUG("scripts", "HyjalAI - Debug mode has been toggled");
                 break;
         }
         return true;
     }
References Creature::AI(), CAST_AI, ClearGossipMenuFor(), hyjalAI::Debug, hyjalAI::DeSpawnVeins(), hyjalAI::FirstBossDead, GOSSIP_ACTION_INFO_DEF, hyjalAI::Retreat(), hyjalAI::StartEvent(), and hyjalAI::WaveCount.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp