Azerotcore-wotlk: formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char > Struct Template Reference
formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char > Struct Template Reference
#include <chrono.h>
Public Member Functions
FMT_CONSTEXPR formatter ()
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (std::chrono::time_point< std::chrono::system_clock > val, FormatContext &ctx) -> decltype(ctx.out())
Public Member Functions inherited from formatter< std::tm, Char >
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (const std::tm &tm, FormatContext &ctx) const -> decltype(ctx.out())
Static Public Attributes
static constexpr Char default_specs []
Additional Inherited Members
Public Attributes inherited from formatter< std::tm, Char >
basic_string_view< Char > specs
Detailed Description
template<typename Char, typename Duration>
struct formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >
Definition at line 478 of file chrono.h.
Constructor & Destructor Documentation
formatter()
template<typename Char , typename Duration > FMT_CONSTEXPR formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::formatter () inline
Definition at line 480 of file chrono.h.
{
     this->specs = {default_specs, sizeof(default_specs) / sizeof(Char)};
   }
Member Function Documentation
format()
template<typename Char , typename Duration > template<typename FormatContext > auto formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::format (std::chrono::time_point< std::chrono::system_clock > val, FormatContext & ctx) -> decltype(ctx.out()) inline
Definition at line 495 of file chrono.h.
{
     std::tm time = localtime(val);
     return formatter<std::tm, Char>::format(time, ctx);
   }
References format(), and localtime().
parse()
template<typename Char , typename Duration > template<typename ParseContext > FMT_CONSTEXPR auto formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 485 of file chrono.h.
{
     auto it = ctx.begin();
     if (it != ctx.end() && *it == ':') ++it;
     auto end = it;
     while (end != ctx.end() && *end != '}') ++end;
     if (end != it) this->specs = {it, detail::to_unsigned(end - it)};
     return end;
   }
References to_unsigned().
Member Data Documentation
default_specs
template<typename Char , typename Duration > constexpr Char formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::default_specs static constexpr
Initial value:
= {'%', 'Y', '-', '%', 'm', '-',
                                           '%', 'd', ' ', '%', 'H', ':',
                                           '%', 'M', ':', '%', 'S'}
Definition at line 501 of file chrono.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/chrono.h