Azerotcore-wotlk: deps/mysqllite/mysys/array.c File Reference
array.c File Reference
#include "mysys_priv.h"
#include "m_string.h"
Functions
my_bool init_dynamic_array2 (DYNAMIC_ARRAY *array, uint element_size, void *init_buffer, uint init_alloc, uint alloc_increment)
my_bool init_dynamic_array (DYNAMIC_ARRAY *array, uint element_size, uint init_alloc, uint alloc_increment)
my_bool insert_dynamic (DYNAMIC_ARRAY *array, uchar *element)
uchar * alloc_dynamic (DYNAMIC_ARRAY *array)
uchar * pop_dynamic (DYNAMIC_ARRAY *array)
my_bool set_dynamic (DYNAMIC_ARRAY *array, uchar *element, uint idx)
my_bool allocate_dynamic (DYNAMIC_ARRAY *array, uint max_elements)
void get_dynamic (DYNAMIC_ARRAY *array, uchar *element, uint idx)
void delete_dynamic (DYNAMIC_ARRAY *array)
void delete_dynamic_element (DYNAMIC_ARRAY *array, uint idx)
void freeze_size (DYNAMIC_ARRAY *array)
int get_index_dynamic (DYNAMIC_ARRAY *array, uchar *element)
Function Documentation
alloc_dynamic()
uchar* alloc_dynamic (DYNAMIC_ARRAY * array)
Definition at line 130 of file array.c.
 {
   if (array->elements == array->max_element)
   {
     char *new_ptr;
     if (array->buffer == (uchar *)(array + 1))
     {
       /*
         In this senerio, the buffer is statically preallocated,
         so we have to create an all-new malloc since we overflowed
       */
       if (!(new_ptr= (char *) my_malloc((array->max_element+
                                          array->alloc_increment) *
                                         array->size_of_element,
                                         MYF(MY_WME))))
         return 0;
       memcpy(new_ptr, array->buffer,
              array->elements * array->size_of_element);
     }
     else
     if (!(new_ptr=(char*) my_realloc(array->buffer,(array->max_element+
                                      array->alloc_increment)*
                                      array->size_of_element,
                                      MYF(MY_WME | MY_ALLOW_ZERO_PTR))))
       return 0;
     array->buffer= (uchar*) new_ptr;
     array->max_element+=array->alloc_increment;
   }
   return array->buffer+(array->elements++ * array->size_of_element);
 }
References array, memcpy, MY_ALLOW_ZERO_PTR, my_malloc(), my_realloc(), MY_WME, MYF, and LF_DYNARRAY::size_of_element.
Referenced by insert_dynamic(), and my_hash_insert().
allocate_dynamic()
my_bool allocate_dynamic (DYNAMIC_ARRAY * array, uint max_elements)
Definition at line 231 of file array.c.
 {
   if (max_elements >= array->max_element)
   {
     uint size;
     uchar *new_ptr;
     size= (max_elements + array->alloc_increment)/array->alloc_increment;
     size*= array->alloc_increment;
     if (array->buffer == (uchar *)(array + 1))
     {
        /*
          In this senerio, the buffer is statically preallocated,
          so we have to create an all-new malloc since we overflowed
        */
        if (!(new_ptr= (uchar *) my_malloc(size *
                                          array->size_of_element,
                                          MYF(MY_WME))))
          return 0;
        memcpy(new_ptr, array->buffer,
               array->elements * array->size_of_element);
      }
      else
     if (!(new_ptr= (uchar*) my_realloc(array->buffer,size*
                                        array->size_of_element,
                                        MYF(MY_WME | MY_ALLOW_ZERO_PTR))))
       return TRUE;
     array->buffer= new_ptr;
     array->max_element= size;
   }
   return FALSE;
 }
References array, FALSE, if(), memcpy, MY_ALLOW_ZERO_PTR, my_malloc(), my_realloc(), MY_WME, MYF, LF_DYNARRAY::size_of_element, and TRUE.
Referenced by set_dynamic().
delete_dynamic()
void delete_dynamic (DYNAMIC_ARRAY * array)
Definition at line 298 of file array.c.
 {
   /*
     Just mark as empty if we are using a static buffer
   */
   if (array->buffer == (uchar *)(array + 1))
     array->elements= 0;
   else
   if (array->buffer)
   {
     my_free(array->buffer);
     array->buffer=0;
     array->elements=array->max_element=0;
   }
 }
References array, and my_free().
Referenced by free_tmpdir(), init_tmpdir(), my_dirend(), my_hash_free(), my_load_defaults(), and mysql_close_free_options().
delete_dynamic_element()
void delete_dynamic_element (DYNAMIC_ARRAY * array, uint idx)
Definition at line 323 of file array.c.
 {
   char *ptr= (char*) array->buffer+array->size_of_element*idx;
   array->elements--;
   memmove(ptr,ptr+array->size_of_element,
           (array->elements-idx)*array->size_of_element);
 }
References array, idx, memmove, ptr(), and LF_DYNARRAY::size_of_element.
freeze_size()
void freeze_size (DYNAMIC_ARRAY * array)
Definition at line 341 of file array.c.
 {
   uint elements=max(array->elements,1);
   /*
     Do nothing if we are using a static buffer
   */
   if (array->buffer == (uchar *)(array + 1))
     return;
   if (array->buffer && array->max_element != elements)
   {
     array->buffer=(uchar*) my_realloc(array->buffer,
                                      elements*array->size_of_element,
                                      MYF(MY_WME));
     array->max_element=elements;
   }
 }
References array, max, my_realloc(), MY_WME, MYF, and LF_DYNARRAY::size_of_element.
Referenced by init_tmpdir().
get_dynamic()
void get_dynamic (DYNAMIC_ARRAY * array, uchar * element, uint idx)
Definition at line 276 of file array.c.
 {
   if (idx >= array->elements)
   {
     DBUG_PRINT("warning",("To big array idx: %d, array size is %d",
                           idx,array->elements));
     bzero(element,array->size_of_element);
     return;
   }
   memcpy(element,array->buffer+idx*array->size_of_element,
          (size_t) array->size_of_element);
 }
References array, bzero, DBUG_PRINT, idx, memcpy, and LF_DYNARRAY::size_of_element.
get_index_dynamic()
int get_index_dynamic (DYNAMIC_ARRAY * array, uchar * element)
Definition at line 371 of file array.c.
 {
   size_t ret;
   if (array->buffer > element)
     return -1;
   ret= (element - array->buffer) /  array->size_of_element;
   if (ret > array->elements)
     return -1;
   return ret;
 }
References array, if(), ret, and LF_DYNARRAY::size_of_element.
init_dynamic_array()
my_bool init_dynamic_array (DYNAMIC_ARRAY * array, uint element_size, uint init_alloc, uint alloc_increment)
Definition at line 75 of file array.c.
 {
   /* placeholder to preserve ABI */
   return my_init_dynamic_array_ci(array, element_size, init_alloc,
                                   alloc_increment);
 }
References array, and my_init_dynamic_array_ci.
Referenced by add_init_command().
init_dynamic_array2()
my_bool init_dynamic_array2 (DYNAMIC_ARRAY * array, uint element_size, void * init_buffer, uint init_alloc, uint alloc_increment)
Definition at line 43 of file array.c.
 {
   DBUG_ENTER("init_dynamic_array");
   if (!alloc_increment)
   {
     alloc_increment=max((8192-MALLOC_OVERHEAD)/element_size,16);
     if (init_alloc > 8 && alloc_increment > init_alloc * 2)
       alloc_increment=init_alloc*2;
   }
   if (!init_alloc)
   {
     init_alloc=alloc_increment;
     init_buffer= 0;
   }
   array->elements=0;
   array->max_element=init_alloc;
   array->alloc_increment=alloc_increment;
   array->size_of_element=element_size;
   if ((array->buffer= init_buffer))
     DBUG_RETURN(FALSE);
   /*
     Since the dynamic array is usable even if allocation fails here malloc
     should not throw an error
   */
   if (!(array->buffer= (uchar*) my_malloc(element_size*init_alloc, MYF(0))))
     array->max_element=0;
   DBUG_RETURN(FALSE);
 }
References array, DBUG_ENTER, DBUG_RETURN, FALSE, MALLOC_OVERHEAD, max, my_malloc(), MYF, and LF_DYNARRAY::size_of_element.
insert_dynamic()
my_bool insert_dynamic (DYNAMIC_ARRAY * array, uchar * element)
Definition at line 95 of file array.c.
 {
   uchar* buffer;
   if (array->elements == array->max_element)
   {                     /* Call only when nessesary */
     if (!(buffer=alloc_dynamic(array)))
       return TRUE;
   }
   else
   {
     buffer=array->buffer+(array->elements * array->size_of_element);
     array->elements++;
   }
   memcpy(buffer,element,(size_t) array->size_of_element);
   return FALSE;
 }
References alloc_dynamic(), array, buffer, FALSE, memcpy, LF_DYNARRAY::size_of_element, and TRUE.
Referenced by add_init_command(), handle_default_option(), and init_tmpdir().
pop_dynamic()
uchar* pop_dynamic (DYNAMIC_ARRAY * array)
Definition at line 174 of file array.c.
 {
   if (array->elements)
     return array->buffer+(--array->elements * array->size_of_element);
   return 0;
 }
References array, and LF_DYNARRAY::size_of_element.
Referenced by my_hash_delete().
set_dynamic()
my_bool set_dynamic (DYNAMIC_ARRAY * array, uchar * element, uint idx)
Definition at line 199 of file array.c.
 {
   if (idx >= array->elements)
   {
     if (idx >= array->max_element && allocate_dynamic(array, idx))
       return TRUE;
     bzero((uchar*) (array->buffer+array->elements*array->size_of_element),
       (idx - array->elements)*array->size_of_element);
     array->elements=idx+1;
   }
   memcpy(array->buffer+(idx * array->size_of_element),element,
      (size_t) array->size_of_element);
   return FALSE;
 }
References allocate_dynamic(), array, bzero, FALSE, idx, memcpy, LF_DYNARRAY::size_of_element, and TRUE.