Azerotcore-wotlk: Acore::PlayerListSearcherWithSharedVision< Check > Struct Template Reference
Acore::PlayerListSearcherWithSharedVision< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
PlayerListSearcherWithSharedVision (WorldObject const *searcher, std::list< Player * > &objects, Check &check)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
std::list< Player * > & i_objects
Check & i_check
Detailed Description
template<class Check>
struct Acore::PlayerListSearcherWithSharedVision< Check >
Definition at line 506 of file GridNotifiers.h.
Constructor & Destructor Documentation
PlayerListSearcherWithSharedVision()
template<class Check > Acore::PlayerListSearcherWithSharedVision< Check >::PlayerListSearcherWithSharedVision (WorldObject const * searcher, std::list< Player * > & objects, Check & check) inline
Definition at line 512 of file GridNotifiers.h.
             : i_phaseMask(searcher->GetPhaseMask()), i_objects(objects), i_check(check) {}
Member Function Documentation
Visit() [1/3]
template<class Check > void Acore::PlayerListSearcherWithSharedVision< Check >::Visit (CreatureMapType & m)
Definition at line 494 of file GridNotifiersImpl.h.
 {
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (itr->GetSource()->InSamePhase(i_phaseMask) && itr->GetSource()->HasSharedVision())
             for (SharedVisionList::const_iterator i = itr->GetSource()->GetSharedVisionList().begin(); i != itr->GetSource()->GetSharedVisionList().end(); ++i)
                 if (i_check(*i, false))
                     i_objects.push_back(*i);
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void Acore::PlayerListSearcherWithSharedVision< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 518 of file GridNotifiers.h.
 {}
Visit() [3/3]
template<class Check > void Acore::PlayerListSearcherWithSharedVision< Check >::Visit (PlayerMapType & m)
Definition at line 485 of file GridNotifiersImpl.h.
 {
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (itr->GetSource()->InSamePhase(i_phaseMask))
             if (i_check(itr->GetSource(), true))
                 i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Member Data Documentation
i_check
template<class Check > Check& Acore::PlayerListSearcherWithSharedVision< Check >::i_check
Definition at line 510 of file GridNotifiers.h.
i_objects
template<class Check > std::list<Player*>& Acore::PlayerListSearcherWithSharedVision< Check >::i_objects
Definition at line 509 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::PlayerListSearcherWithSharedVision< Check >::i_phaseMask
Definition at line 508 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h