Azerotcore-wotlk: npc_bone_spike::npc_bone_spikeAI Struct Reference
npc_bone_spike::npc_bone_spikeAI Struct Reference
Public Member Functions
npc_bone_spikeAI (Creature *creature)
void DoAction (int32 action) override
void JustDied (Unit *) override
void IsSummonedBy (Unit *summoner) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool hasTrappedUnit
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 369 of file boss_lord_marrowgar.cpp.
Constructor & Destructor Documentation
npc_bone_spikeAI()
npc_bone_spike::npc_bone_spikeAI::npc_bone_spikeAI (Creature * creature) inline
Definition at line 371 of file boss_lord_marrowgar.cpp.
                                              : NullCreatureAI(creature), hasTrappedUnit(false)
         {
         }
Member Function Documentation
DoAction()
void npc_bone_spike::npc_bone_spikeAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 378 of file boss_lord_marrowgar.cpp.
         {
             if (action != -1337)
                 return;
             if (TempSummon* summ = me->ToTempSummon())
                 if (Unit* trapped = summ->GetSummonerUnit())
                 {
                     Position exitPos = {me->GetPositionX(), me->GetPositionY(), 60.0f, me->GetOrientation()};
                     trapped->UpdateAllowedPositionZ(exitPos.GetPositionX(), exitPos.GetPositionY(), exitPos.m_positionZ);
                     exitPos.m_positionZ += 1.0f;
                     if (Unit* vehBase = trapped->GetVehicleBase())
                         vehBase->RemoveAurasByType(SPELL_AURA_CONTROL_VEHICLE, trapped->GetGUID());
                     trapped->_ExitVehicle(&exitPos);
                     trapped->RemoveAurasDueToSpell(SPELL_IMPALED);
                     trapped->GetMotionMaster()->Clear();
                     trapped->UpdatePosition(exitPos, true);
                     trapped->StopMovingOnCurrentPos();
                     trapped->NearTeleportTo(exitPos.GetPositionX(), exitPos.GetPositionY(), exitPos.GetPositionZ(), exitPos.GetOrientation(), false);
                 }
             me->DespawnOrUnsummon(1);
         }
References Creature::DespawnOrUnsummon(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleBase(), Position::m_positionZ, CreatureAI::me, SPELL_AURA_CONTROL_VEHICLE, SPELL_IMPALED, and Unit::ToTempSummon().
Referenced by JustDied(), and UpdateAI().
IsSummonedBy()
void npc_bone_spike::npc_bone_spikeAI::IsSummonedBy (Unit * summoner) inline override virtual
Reimplemented from CreatureAI.
Definition at line 407 of file boss_lord_marrowgar.cpp.
         {
             if (!summoner)
                 return;
             if (Vehicle* v = summoner->GetVehicle())
                 if (Unit* u = v->GetBase())
                     if (u->GetEntry() == NPC_BONE_SPIKE && u->GetTypeId() == TYPEID_UNIT)
                         u->ToCreature()->AI()->DoAction(-1337);
             ObjectGuid petGUID = summoner->GetPetGUID();
             summoner->SetPetGUID(ObjectGuid::Empty);
             me->CastSpell(summoner, SPELL_IMPALED, true);
             summoner->CastSpell(me, SPELL_RIDE_VEHICLE, true);
             //summoner->ClearUnitState(UNIT_STATE_ONVEHICLE);
             summoner->SetPetGUID(petGUID);
             summoner->GetMotionMaster()->Clear();
             summoner->StopMoving();
             events.ScheduleEvent(1, 8000);
             hasTrappedUnit = true;
         }
References Unit::CastSpell(), MotionMaster::Clear(), ObjectGuid::Empty, Unit::GetMotionMaster(), Unit::GetPetGUID(), Unit::GetVehicle(), hasTrappedUnit, CreatureAI::me, NPC_BONE_SPIKE, Unit::SetPetGUID(), SPELL_IMPALED, SPELL_RIDE_VEHICLE, Unit::StopMoving(), and TYPEID_UNIT.
JustDied()
void npc_bone_spike::npc_bone_spikeAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 402 of file boss_lord_marrowgar.cpp.
         {
             DoAction(-1337);
         }
References DoAction().
UpdateAI()
void npc_bone_spike::npc_bone_spikeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 429 of file boss_lord_marrowgar.cpp.
         {
             if (!hasTrappedUnit || !me->IsAlive())
                 return;
             if (TempSummon* summ = me->ToTempSummon())
             {
                 if (Unit* trapped = summ->GetSummonerUnit())
                 {
                     if (!trapped->IsOnVehicle(me) || !trapped->IsAlive() || !me->GetInstanceScript() || me->GetInstanceScript()->GetBossState(DATA_LORD_MARROWGAR) != IN_PROGRESS || trapped->HasAuraType(SPELL_AURA_SPIRIT_OF_REDEMPTION))
                     {
                         DoAction(-1337);
                         return;
                     }
                 }
                 else
                 {
                     me->DespawnOrUnsummon(1);
                     return;
                 }
             }
             else
             {
                 me->DespawnOrUnsummon(1);
                 return;
             }
             events.Update(diff);
             if (events.ExecuteEvent() == 1)
                 if (InstanceScript* instance = me->GetInstanceScript())
                     instance->SetData(DATA_BONED_ACHIEVEMENT, uint32(false));
         }
References DATA_BONED_ACHIEVEMENT, DATA_LORD_MARROWGAR, Creature::DespawnOrUnsummon(), DoAction(), InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), hasTrappedUnit, IN_PROGRESS, Unit::IsAlive(), CreatureAI::me, SPELL_AURA_SPIRIT_OF_REDEMPTION, and Unit::ToTempSummon().
Member Data Documentation
events
EventMap npc_bone_spike::npc_bone_spikeAI::events
Definition at line 375 of file boss_lord_marrowgar.cpp.
hasTrappedUnit
bool npc_bone_spike::npc_bone_spikeAI::hasTrappedUnit
Definition at line 376 of file boss_lord_marrowgar.cpp.
Referenced by IsSummonedBy(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp