Azerotcore-wotlk: Acore::PowerPctOrderPred Class Reference
Acore::PowerPctOrderPred Class Reference
#include <Unit.h>
Public Member Functions
PowerPctOrderPred (Powers power, bool ascending=true)
bool operator() (WorldObject const *objA, WorldObject const *objB) const
bool operator() (Unit const *a, Unit const *b) const
Private Attributes
Powers const _power
bool const _ascending
Detailed Description
Definition at line 2661 of file Unit.h.
Constructor & Destructor Documentation
PowerPctOrderPred()
Acore::PowerPctOrderPred::PowerPctOrderPred (Powers power, bool ascending = true) inline
Definition at line 2664 of file Unit.h.
 : _power(power), _ascending(ascending) { }
Member Function Documentation
operator()() [1/2]
bool Acore::PowerPctOrderPred::operator() (Unit const * a, Unit const * b) const inline
Definition at line 2675 of file Unit.h.
         {
             float rA = a->GetMaxPower(_power) ? float(a->GetPower(_power)) / float(a->GetMaxPower(_power)) : 0.0f;
             float rB = b->GetMaxPower(_power) ? float(b->GetPower(_power)) / float(b->GetMaxPower(_power)) : 0.0f;
             return _ascending ? rA < rB : rA > rB;
         }
References _ascending, _power, Unit::GetMaxPower(), and Unit::GetPower().
operator()() [2/2]
bool Acore::PowerPctOrderPred::operator() (WorldObject const * objA, WorldObject const * objB) const inline
Definition at line 2666 of file Unit.h.
         {
             Unit const* a = objA->ToUnit();
             Unit const* b = objB->ToUnit();
             float rA = (a && a->GetMaxPower(_power)) ? float(a->GetPower(_power)) / float(a->GetMaxPower(_power)) : 0.0f;
             float rB = (b && b->GetMaxPower(_power)) ? float(b->GetPower(_power)) / float(b->GetMaxPower(_power)) : 0.0f;
             return _ascending ? rA < rB : rA > rB;
         }
References _ascending, _power, Unit::GetMaxPower(), Unit::GetPower(), and Object::ToUnit().
Member Data Documentation
_ascending
bool const Acore::PowerPctOrderPred::_ascending private
Definition at line 2684 of file Unit.h.
Referenced by operator()().
_power
Powers const Acore::PowerPctOrderPred::_power private
Definition at line 2683 of file Unit.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.h