Azerotcore-wotlk: Acore::LocalizedPacketDo< Builder > Class Template Reference
Acore::LocalizedPacketDo< Builder > Class Template Reference
#include <GridNotifiers.h>
Public Member Functions
LocalizedPacketDo (Builder &builder)
~LocalizedPacketDo ()
void operator() (Player *p)
Private Attributes
Builder & i_builder
std::vector< WorldPacket * > i_data_cache
Detailed Description
template<class Builder>
class Acore::LocalizedPacketDo< Builder >
Definition at line 1586 of file GridNotifiers.h.
Constructor & Destructor Documentation
LocalizedPacketDo()
template<class Builder > Acore::LocalizedPacketDo< Builder >::LocalizedPacketDo (Builder & builder) inline explicit
Definition at line 1589 of file GridNotifiers.h.
 : i_builder(builder) {}
~LocalizedPacketDo()
template<class Builder > Acore::LocalizedPacketDo< Builder >::~LocalizedPacketDo () inline
Definition at line 1591 of file GridNotifiers.h.
         {
             for (size_t i = 0; i < i_data_cache.size(); ++i)
                 delete i_data_cache[i];
         }
References Acore::LocalizedPacketDo< Builder >::i_data_cache.
Member Function Documentation
operator()()
template<class Builder > void Acore::LocalizedPacketDo< Builder >::operator() (Player * p)
Definition at line 537 of file GridNotifiersImpl.h.
 {
     LocaleConstant loc_idx = p->GetSession()->GetSessionDbLocaleIndex();
     uint32 cache_idx = loc_idx + 1;
     WorldPacket* data;
     // create if not cached yet
     if (i_data_cache.size() < cache_idx + 1 || !i_data_cache[cache_idx])
     {
         if (i_data_cache.size() < cache_idx + 1)
             i_data_cache.resize(cache_idx + 1);
         data = new WorldPacket();
         i_builder(*data, loc_idx);
         i_data_cache[cache_idx] = data;
     }
     else
         data = i_data_cache[cache_idx];
     p->SendDirectMessage(data);
 }
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Player::SendDirectMessage().
Member Data Documentation
i_builder
template<class Builder > Builder& Acore::LocalizedPacketDo< Builder >::i_builder private
Definition at line 1599 of file GridNotifiers.h.
i_data_cache
template<class Builder > std::vector<WorldPacket*> Acore::LocalizedPacketDo< Builder >::i_data_cache private
Definition at line 1600 of file GridNotifiers.h.
Referenced by Acore::LocalizedPacketDo< Builder >::~LocalizedPacketDo().
The documentation for this class was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h