Azerotcore-wotlk: EffectMovementGenerator Class Reference
EffectMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
EffectMovementGenerator (uint32 Id)
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
uint32 m_Id
Detailed Description
Definition at line 72 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
EffectMovementGenerator()
EffectMovementGenerator::EffectMovementGenerator (uint32 Id) inline explicit
Definition at line 75 of file PointMovementGenerator.h.
 : m_Id(Id) {}
Member Function Documentation
Finalize()
void EffectMovementGenerator::Finalize (Unit * unit) override virtual
Implements MovementGenerator.
Definition at line 210 of file PointMovementGenerator.cpp.
 {
     if (unit->GetTypeId() != TYPEID_UNIT)
         return;
     if (unit->GetTypeId() == TYPEID_UNIT && unit->HasUnitMovementFlag(MOVEMENTFLAG_FALLING) && unit->movespline->isFalling()) // pussywizard
         unit->RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
     // Need restore previous movement since we have no proper states system
     //if (unit->IsAlive() && !unit->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_FLEEING))
     //{
     //    if (Unit* victim = unit->GetVictim())
     //        unit->GetMotionMaster()->MoveChase(victim);
     //    else
     //        unit->GetMotionMaster()->Initialize();
     //}
     if (unit->ToCreature()->AI())
         unit->ToCreature()->AI()->MovementInform(EFFECT_MOTION_TYPE, m_Id);
 }
References Creature::AI(), EFFECT_MOTION_TYPE, Object::GetTypeId(), Unit::HasUnitMovementFlag(), Movement::MoveSpline::isFalling(), m_Id, MOVEMENTFLAG_FALLING, CreatureAI::MovementInform(), Unit::movespline, Unit::RemoveUnitMovementFlag(), Object::ToCreature(), and TYPEID_UNIT.
GetMovementGeneratorType()
MovementGeneratorType EffectMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
Definition at line 80 of file PointMovementGenerator.h.
 { return EFFECT_MOTION_TYPE; }
References EFFECT_MOTION_TYPE.
Initialize()
void EffectMovementGenerator::Initialize (Unit *) inline override virtual
Implements MovementGenerator.
Definition at line 76 of file PointMovementGenerator.h.
 {}
Reset()
void EffectMovementGenerator::Reset (Unit *) inline override virtual
Implements MovementGenerator.
Definition at line 78 of file PointMovementGenerator.h.
 {}
Update()
bool EffectMovementGenerator::Update (Unit * unit, uint32) override virtual
Implements MovementGenerator.
Definition at line 205 of file PointMovementGenerator.cpp.
 {
     return !unit->movespline->Finalized();
 }
References Movement::MoveSpline::Finalized(), and Unit::movespline.
Member Data Documentation
m_Id
uint32 EffectMovementGenerator::m_Id private
Definition at line 82 of file PointMovementGenerator.h.
Referenced by Finalize().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp