Azerotcore-wotlk: go_tele_to_dalaran_crystal Class Reference
go_tele_to_dalaran_crystal Class Reference
Public Member Functions
go_tele_to_dalaran_crystal ()
bool OnGossipHello (Player *player, GameObject *) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 993 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_tele_to_dalaran_crystal()
go_tele_to_dalaran_crystal::go_tele_to_dalaran_crystal () inline
Definition at line 996 of file go_scripts.cpp.
 : GameObjectScript("go_tele_to_dalaran_crystal") { }
Member Function Documentation
OnGossipHello()
bool go_tele_to_dalaran_crystal::OnGossipHello (Player * player, GameObject *) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 998 of file go_scripts.cpp.
     {
         if (player->GetQuestRewardStatus(QUEST_TELE_CRYSTAL_FLAG))
             return false;
         player->GetSession()->SendNotification(GO_TELE_TO_DALARAN_CRYSTAL_FAILED);
         return true;
     }
References Player::GetQuestRewardStatus(), Player::GetSession(), GO_TELE_TO_DALARAN_CRYSTAL_FAILED, QUEST_TELE_CRYSTAL_FLAG, and WorldSession::SendNotification().
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp