Azerotcore-wotlk: boss_mandokir::boss_mandokirAI Struct Reference
boss_mandokir::boss_mandokirAI Struct Reference
Public Member Functions
boss_mandokirAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint8 killCount
ObjectGuid chainedSpirtGUIDs [CHAINED_SPIRT_COUNT]
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 111 of file boss_mandokir.cpp.
Constructor & Destructor Documentation
boss_mandokirAI()
boss_mandokir::boss_mandokirAI::boss_mandokirAI (Creature * creature) inline
Definition at line 113 of file boss_mandokir.cpp.
 : BossAI(creature, DATA_MANDOKIR) { }
Member Function Documentation
EnterCombat()
void boss_mandokir::boss_mandokirAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 143 of file boss_mandokir.cpp.
         {
             _EnterCombat();
             events.ScheduleEvent(EVENT_OVERPOWER, urand(7000, 9000));
             events.ScheduleEvent(EVENT_MORTAL_STRIKE, urand(12000, 18000));
             events.ScheduleEvent(EVENT_WHIRLWIND, urand(24000, 30000));
             events.ScheduleEvent(EVENT_CHECK_OHGAN, 1000);
             events.ScheduleEvent(EVENT_WATCH_PLAYER, urand(13000, 15000));
             events.ScheduleEvent(EVENT_CHARGE_PLAYER, urand(33000, 38000));
             me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
             Talk(SAY_AGGRO);
             me->Dismount();
             // Summon Ohgan (Spell missing) TEMP HACK
             me->SummonCreature(NPC_OHGAN, me->GetPositionX() - 3, me->GetPositionY(), me->GetPositionZ(), me->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 35000);
             // Summon Chained Spirits
             for (int i = 0; i < CHAINED_SPIRT_COUNT; ++i)
             {
                 Creature* chainedSpirt = me->SummonCreature(NPC_CHAINED_SPIRT, PosSummonChainedSpirits[i], TEMPSUMMON_CORPSE_DESPAWN);
                 chainedSpirtGUIDs[i] = chainedSpirt->GetGUID();
             }
             DoZoneInCombat();
         }
References BossAI::_EnterCombat(), CHAINED_SPIRT_COUNT, chainedSpirtGUIDs, Unit::Dismount(), CreatureAI::DoZoneInCombat(), EVENT_CHARGE_PLAYER, EVENT_CHECK_OHGAN, EVENT_MORTAL_STRIKE, EVENT_OVERPOWER, EVENT_WATCH_PLAYER, EVENT_WHIRLWIND, Object::GetGUID(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_CHAINED_SPIRT, NPC_OHGAN, PosSummonChainedSpirits, SAY_AGGRO, Creature::SetHomePosition(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and urand().
JustDied()
void boss_mandokir::boss_mandokirAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 133 of file boss_mandokir.cpp.
         {
             // Do not want to unsummon Ohgan
             for (int i = 0; i < CHAINED_SPIRT_COUNT; ++i)
                 if (Creature* unsummon = ObjectAccessor::GetCreature(*me, chainedSpirtGUIDs[i]))
                     unsummon->DespawnOrUnsummon();
             instance->SetBossState(DATA_MANDOKIR, DONE);
             instance->SaveToDB();
         }
References CHAINED_SPIRT_COUNT, chainedSpirtGUIDs, DATA_MANDOKIR, DONE, ObjectAccessor::GetCreature(), BossAI::instance, ScriptedAI::me, InstanceScript::SaveToDB(), and InstanceScript::SetBossState().
KilledUnit()
void boss_mandokir::boss_mandokirAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 166 of file boss_mandokir.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (++killCount == 3)
             {
                 Talk(SAY_DING_KILL);
                 if (Creature* jindo = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_JINDO)))
                     if (jindo->IsAlive())
                         jindo->AI()->Talk(SAY_GRATS_JINDO);
                 DoCast(me, SPELL_LEVEL_UP, true);
                 killCount = 0;
             }
         }
References DATA_JINDO, UnitAI::DoCast(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Object::GetTypeId(), BossAI::instance, killCount, ScriptedAI::me, SAY_DING_KILL, SAY_GRATS_JINDO, SPELL_LEVEL_UP, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_mandokir::boss_mandokirAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 182 of file boss_mandokir.cpp.
         {
             if (type == WAYPOINT_MOTION_TYPE)
             {
                 me->SetWalk(false);
                 if (id == POINT_MANDOKIR_END)
                 {
                     me->SetHomePosition(PosMandokir[0]);
                     instance->SetBossState(DATA_MANDOKIR, NOT_STARTED);
                 }
             }
         }
References DATA_MANDOKIR, BossAI::instance, ScriptedAI::me, NOT_STARTED, POINT_MANDOKIR_END, PosMandokir, InstanceScript::SetBossState(), Creature::SetHomePosition(), Creature::SetWalk(), and WAYPOINT_MOTION_TYPE.
Reset()
void boss_mandokir::boss_mandokirAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 115 of file boss_mandokir.cpp.
         {
             if (me->GetPositionZ() > 140.0f)
             {
                 events.ScheduleEvent(EVENT_CHECK_START, 1000);
                 if (Creature* speaker = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_VILEBRANCH_SPEAKER)))
                     if (!speaker->IsAlive())
                         speaker->Respawn(true);
             }
             killCount = 0;
             me->RemoveAurasDueToSpell(SPELL_FRENZY);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             summons.DespawnAll();
             instance->SetBossState(DATA_OHGAN, NOT_STARTED);
             me->Mount(MODEL_OHGAN_MOUNT);
         }
References DATA_OHGAN, SummonList::DespawnAll(), EVENT_CHECK_START, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetPositionZ(), BossAI::instance, killCount, ScriptedAI::me, MODEL_OHGAN_MOUNT, Unit::Mount(), NOT_STARTED, NPC_VILEBRANCH_SPEAKER, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), InstanceScript::SetBossState(), SPELL_FRENZY, BossAI::summons, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
UpdateAI()
void boss_mandokir::boss_mandokirAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 195 of file boss_mandokir.cpp.
         {
             events.Update(diff);
             if (!UpdateVictim())
             {
                 if (instance->GetBossState(DATA_MANDOKIR) == NOT_STARTED || instance->GetBossState(DATA_MANDOKIR) == SPECIAL)
                 {
                     while (uint32 eventId = events.ExecuteEvent())
                     {
                         switch (eventId)
{
                             case EVENT_CHECK_START:
                                 if (instance->GetBossState(DATA_MANDOKIR) == SPECIAL)
{
                                     me->GetMotionMaster()->MovePoint(0, PosMandokir[1].m_positionX, PosMandokir[1].m_positionY, PosMandokir[1].m_positionZ);
                                     events.ScheduleEvent(EVENT_STARTED, 6000);
                                 }
                                 else
                                     events.ScheduleEvent(EVENT_CHECK_START, 1000);
                                 break;
                             case EVENT_STARTED:
                                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                                 break;
                             default:
                                 break;
                         }
                     }
                 }
                 return;
             }
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_OVERPOWER:
                         DoCastVictim(SPELL_OVERPOWER, true);
                         events.ScheduleEvent(EVENT_OVERPOWER, urand(6000, 12000));
                         break;
                     case EVENT_MORTAL_STRIKE:
                         if (me->GetVictim() && me->GetVictim()->HealthBelowPct(50))
                             DoCastVictim(SPELL_MORTAL_STRIKE, true);
                         events.ScheduleEvent(EVENT_MORTAL_STRIKE, urand(12000, 18000));
                         break;
                     case EVENT_WHIRLWIND:
                         DoCast(me, SPELL_WHIRLWIND);
                         events.ScheduleEvent(EVENT_WHIRLWIND, urand(22000, 26000));
                         break;
                     case EVENT_CHECK_OHGAN:
                         if (instance->GetBossState(DATA_OHGAN) == DONE)
{
                             DoCast(me, SPELL_FRENZY);
                             Talk(SAY_OHGAN_DEAD);
                         }
                         else
                             events.ScheduleEvent(EVENT_CHECK_OHGAN, 1000);
                         break;
                     case EVENT_WATCH_PLAYER:
                         if (Unit* player = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
{
                             DoCast(player, SPELL_WATCH);
                             Talk(SAY_WATCH, player);
                         }
                         events.ScheduleEvent(EVENT_WATCH_PLAYER, urand(12000, 15000));
                         break;
                     case EVENT_CHARGE_PLAYER:
                         DoCast(SelectTarget(SELECT_TARGET_RANDOM, 0, 40, true), SPELL_CHARGE);
                         events.ScheduleEvent(EVENT_CHARGE_PLAYER, urand(22000, 30000));
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References DATA_MANDOKIR, DATA_OHGAN, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_CHARGE_PLAYER, EVENT_CHECK_OHGAN, EVENT_CHECK_START, EVENT_MORTAL_STRIKE, EVENT_OVERPOWER, EVENT_STARTED, EVENT_WATCH_PLAYER, EVENT_WHIRLWIND, InstanceScript::GetBossState(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), BossAI::instance, ScriptedAI::me, MotionMaster::MovePoint(), NOT_STARTED, PosMandokir, Object::RemoveFlag(), SAY_OHGAN_DEAD, SAY_WATCH, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPECIAL, SPELL_CHARGE, SPELL_FRENZY, SPELL_MORTAL_STRIKE, SPELL_OVERPOWER, SPELL_WATCH, SPELL_WHIRLWIND, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
chainedSpirtGUIDs
ObjectGuid boss_mandokir::boss_mandokirAI::chainedSpirtGUIDs[CHAINED_SPIRT_COUNT] private
Definition at line 278 of file boss_mandokir.cpp.
Referenced by EnterCombat(), and JustDied().
killCount
uint8 boss_mandokir::boss_mandokirAI::killCount private
Definition at line 277 of file boss_mandokir.cpp.
Referenced by KilledUnit(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp