Azerotcore-wotlk: spectator_commandscript Class Reference
spectator_commandscript Class Reference
Public Member Functions
spectator_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleSpectatorCommand (ChatHandler *handler)
static bool HandleSpectatorVersionCommand (ChatHandler *handler, uint16 version)
static bool HandleSpectatorResetCommand (ChatHandler *handler)
static bool HandleSpectatorLeaveCommand (ChatHandler *handler)
static bool HandleSpectatorSpectateCommand (ChatHandler *handler, std::string const &name)
static bool HandleSpectatorWatchCommand (ChatHandler *handler, std::string const &name)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 28 of file cs_spectator.cpp.
Constructor & Destructor Documentation
spectator_commandscript()
spectator_commandscript::spectator_commandscript () inline
Definition at line 31 of file cs_spectator.cpp.
 : CommandScript("spectator_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable spectator_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 33 of file cs_spectator.cpp.
     {
         static ChatCommandTable spectatorCommandTable =
         {
             { "version",  HandleSpectatorVersionCommand,  SEC_PLAYER, Console::No },
             { "reset",    HandleSpectatorResetCommand,    SEC_PLAYER, Console::No },
             { "spectate", HandleSpectatorSpectateCommand, SEC_PLAYER, Console::No },
             { "watch",    HandleSpectatorWatchCommand,    SEC_PLAYER, Console::No },
             { "leave",    HandleSpectatorLeaveCommand,    SEC_PLAYER, Console::No },
             { "",         HandleSpectatorCommand,         SEC_PLAYER, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "spect", spectatorCommandTable }
         };
         return commandTable;
     }
References ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), Acore::ChatCommands::No, and SEC_PLAYER.
HandleSpectatorCommand()
static bool spectator_commandscript::HandleSpectatorCommand (ChatHandler * handler) inline static
Definition at line 51 of file cs_spectator.cpp.
     {
         handler->PSendSysMessage("Incorrect syntax.");
         handler->PSendSysMessage("Command has subcommands:");
         handler->PSendSysMessage("   spectate");
         handler->PSendSysMessage("   leave");
         return true;
     }
References ChatHandler::PSendSysMessage().
HandleSpectatorLeaveCommand()
static bool spectator_commandscript::HandleSpectatorLeaveCommand (ChatHandler * handler) inline static
Definition at line 76 of file cs_spectator.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         if (!player->IsSpectator() || !player->FindMap() || !player->FindMap()->IsBattleArena())
         {
             handler->SendSysMessage("You are not a spectator.");
             return true;
         }
         //player->SetIsSpectator(false);
         player->TeleportToEntryPoint();
         return true;
     }
References WorldObject::FindMap(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::IsBattleArena(), Player::IsSpectator(), ChatHandler::SendSysMessage(), and Player::TeleportToEntryPoint().
HandleSpectatorResetCommand()
static bool spectator_commandscript::HandleSpectatorResetCommand (ChatHandler * handler) inline static
Definition at line 67 of file cs_spectator.cpp.
     {
         Player* p = handler->GetSession()->GetPlayer();
         if (!p->IsSpectator())
             return true;
         ArenaSpectator::HandleResetCommand(p);
         return true;
     }
References WorldSession::GetPlayer(), ChatHandler::GetSession(), ArenaSpectator::HandleResetCommand(), and Player::IsSpectator().
HandleSpectatorSpectateCommand()
static bool spectator_commandscript::HandleSpectatorSpectateCommand (ChatHandler * handler, std::string const & name) inline static
Definition at line 90 of file cs_spectator.cpp.
     {
         if (!ArenaSpectator::HandleSpectatorSpectateCommand(handler, name))
             return false;
         return true;
     }
References ArenaSpectator::HandleSpectatorSpectateCommand().
HandleSpectatorVersionCommand()
static bool spectator_commandscript::HandleSpectatorVersionCommand (ChatHandler * handler, uint16 version) inline static
Definition at line 60 of file cs_spectator.cpp.
     {
         if (version < SPECTATOR_ADDON_VERSION)
             ArenaSpectator::SendCommand(handler->GetSession()->GetPlayer(), "%sOUTDATED", SPECTATOR_ADDON_PREFIX);
         return true;
     }
References WorldSession::GetPlayer(), ChatHandler::GetSession(), ArenaSpectator::SendCommand(), SPECTATOR_ADDON_PREFIX, SPECTATOR_ADDON_VERSION, and setup::version.
HandleSpectatorWatchCommand()
static bool spectator_commandscript::HandleSpectatorWatchCommand (ChatHandler * handler, std::string const & name) inline static
Definition at line 98 of file cs_spectator.cpp.
     {
         if (!ArenaSpectator::HandleSpectatorWatchCommand(handler, name))
             return false;
         return true;
     }
References ArenaSpectator::HandleSpectatorWatchCommand().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_spectator.cpp